### ISSUE TITLE
Subject Line personalisation

### ISSUE THREAD

**Issue by lance-spurgeon** [mautic/mautic#100]
Personalise subject lines where we can use any dynamic content or variable fields we have available.

https://www.mautic.org/community/index.php/117-personalised-email-templates/0#p457

**Comment by dbhurley** [comment]
Definitely appreciate the idea! Certainly something we are going to want to look at it in more detail. But I did remove the "urgent" part from the subject line on the issue since it's a feature request.

Thanks!

**Comment by alanhartless** [comment]
This has been included as part of in PR #429.
