### ISSUE TITLE
Toggle on/off on the publish email

### ISSUE THREAD

**Issue by martinstr** [mautic/mautic#10001]
When installing the PR & GrapesJsBuilderBundle plugin and activate it you cant toggle the on/off publish button in the email view without refreshing the page.

Mautic version: v3.0.2
PHP version: 7.2.32

error code: 

`mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 2 passed to Mautic\CoreBundle\Helper\ArrayHelper::getValue() must be of the type array, null given, called in /plugins/GrapesJsBuilderBundle/Model/GrapesJsBuilderModel.php on line 73" at /app/bundles/CoreBundle/Helper/ArrayHelper.php line 27 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 2 passed to Mautic\\CoreBundle\\Helper\\ArrayHelper::getValue() must be of the type array, null given, called in /plugins/GrapesJsBuilderBundle/Model/GrapesJsBuilderModel.php on line 73 at /app/bundles/CoreBundle/Helper/ArrayHelper.php:27)"} []`

**Comment by kuzmany** [comment]
This should fix https://github.com/mautic/plugin-grapesjs-builder/pull/57

**Comment by luizeof** [comment]
This is still a issue at Mautic 3.3.3
