### ISSUE TITLE
Trigger actions based on referrer/URL decision are not working when used in a form campaign.

### ISSUE THREAD

**Issue by evgu** [mautic/mautic#10008]
## Bug Description
We have a number of PDF case studies. Each one is marketed on separate URL on our website. 
I built a single Mautic form which is then displayed on each separate URL/page. Idea is that I use a single mautic form and single campaign to deliver the visitor the relevant case study, based on the URL/page they requested it from.  

When the mautic form is submitted it will pick up the Referrer (i.e. the URL of the relevant case study, where the mautic form is displayed). Then I can use a campaign with a Decision->"Visits a Page" whcih supposedly should pick up the Referrer and then it could be routed to delivering the correct PDF.  

Nonetheless, the trigger actions based on referrer decision seem not working. In the example below even though the Referrer string matches, the non-matching branch of the referrer decision is picked up.

Am I missing something? Has anyone experienced this issue on Referrer matching? 
I also tested for a URL match and it has the same problem.  

<img width="532" alt="image" src="https://user-images.githubusercontent.com/18371928/117684741-901dc880-b1b5-11eb-9b96-4240b47e88a7.png">
-------------------
<img width="595" alt="image" src="https://user-images.githubusercontent.com/18371928/117686774-7a110780-b1b7-11eb-83a9-5bd85a3008a9.png">
-------------------
<img width="531" alt="image" src="https://user-images.githubusercontent.com/18371928/117686663-5e0d6600-b1b7-11eb-8466-7c71a9e16c7e.png">
-------------------
Contact -> Form submitted 
<img width="985" alt="Screenshot 2021-05-10 at 17 40 44" src="https://user-images.githubusercontent.com/18371928/117686380-1981ca80-b1b7-11eb-974e-6da91e55037a.png">
-------------------
<img width="960" alt="image" src="https://user-images.githubusercontent.com/18371928/117687925-95304700-b1b8-11eb-815d-e2c9b4121299.png">
-------------------
<img width="956" alt="image" src="https://user-images.githubusercontent.com/18371928/117687970-a11c0900-b1b8-11eb-9eda-20527e95824c.png">

| Q   | A
| --- | ---
| Mautic version | 3.3.3
| PHP version | 7.3.28

**Comment by evgu** [comment]
@RCheesley if anyone can point me to the correct file containing the code, I can try troubleshooting this.

**Comment by RCheesley** [comment]
Does it work if you put the full URL rather than the fragment?

**Comment by evgu** [comment]
@RCheesley - I tried with full Referrer URL (exactly as seen on the form submission entry), but causes the same issue. Can anyone point me to the source files so I can try to troubleshoot?

**Comment by biozshock** [comment]
Just tested this. Looks like it works.
Steps:
1. Create a campaign form with the action to redirect to the page within mautic.
2. Create a restartable campaign based on that form with 
2.1 Decision: Visits page with URL *page/1*
2.2 Create two actions to add tags.
2.3 On success add also Change campaigns: restart
3. Fill in the form to create/pick a contact
4. After redirect the campaign will be executed on page hit.

https://user-images.githubusercontent.com/169384/183053068-db2e96ff-8819-4b15-b830-7fb681b29dab.mp4
