### ISSUE TITLE
Pending (no sending) for Broadcast or Campaign via AWS SES

### ISSUE THREAD

**Issue by latinlifestyle** [mautic/mautic#10009]
VPS Digital Ocean
1st Test
Ubuntu 18.04 LTS
PHP 7.2
Mautic 2.16.4

2nd Test
Ubuntu 20.04
PHP 7.3
Mautic 3.2.5

In the past 2 days I have been troubleshoot my brand new mautic installation. I Noticed that my config test with a AWS SES was successful. My test email, example email (from emails tab) and direct email (from any contact) work just fine. However when comes to Campaign and Broadcast from at least 2 contact I get a pending (grey) and when comes to broadcast gets failure.
Tried a lots of things from crons to permission etc.

So I installed a second droplet with a Mautic 3.2.5 aside. Same problem. So a I came to a conclusion that is a AWS SES issue. I have absolutely no clue what going on. Couples months ago I did a same steps and work just fine.
PS. I just login in my first AWS Account that use to work flawless create a credentials and put in new mautic installation to see if I missed any configuration. SAME problem. Failure Broadcast send.

Anybody know what's going on. PLEASE HELP.
Thanks

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
