### ISSUE TITLE
[FEATURE] API Access without browser authorization

### ISSUE THREAD

**Issue by trops** [mautic/mautic#1000]
I think it would be insanely useful to have the API work WITHOUT the browser popup authorization. I would like to make a request to the api from my backend service layer direct to Mautic using my keys. With browser auth I cannot use the API unless I was recreating a Mautic interface I imagine. 

So make request to API direct from PHP. No browser Auth. That would save me incredible headaches trying to hack Mautic using point triggers and posting form data from my backend to Mautic.

**Comment by alanhartless** [comment]
Hi Trops,

Many APIs use oauth as the authorization for API use.  It's pretty standard these days.  Are you storing and using the access tokens so that you don't have to reauth through the browser?

**Comment by trops** [comment]
I have an iPhone app, that calls a backend service. There is no browser. I basically would like to update the leads based on things they do in the app. Login, Register, Perform some Action, etc. With browser auth I have no options to use the API.

**Comment by trops** [comment]
I just stumbled upon the REST API....maybe this is what I need?

**Comment by alanhartless** [comment]
Ah I see.  The REST API is behind the Oauth firewall, so you'll have to authorize using a Mautic user. 

Under current circumstances, I think you have three choices:

1) Create a mediator via your backend service.  iPhone app communicates to your backend service which I'm assuming is accessible via the web.  The backend service then communicates with Mautic.  Of course you would have to keep the access tokens valid.  If using an oauth1a token, you don't have to worry about them expiring unless you invalidate them.  For oauth2, you'll have to configure the lifetime of the access token to be very long (in Mautic's Configuration) or implement the refresh token process and configure it's lifetime to be very long.

2) Use a 3rd party app (such as PAW) or service to go through the Oauth process with Mautic, then manually grab the tokens from the database and embed them into your app.  I don't really recommend this because if something happens, you have to wait till your app is released to get the new tokens. 

3) Embed the tracking pixel into your app and use it to track lead activity.  This doesn't require any API auth.  Not sure what iOS limitations there will be with this though.

You're probably referencing https://developer.mautic.org?

**Comment by trops** [comment]
Yes, Im reading about 2-legged OAuth right now and I think that may work! Yes, I was referencing the developer.mautic.org site and saw REST API! haha, so Im going to read more about the 2-legged OAuth with OAuth 1.0 and see if that might work without user involvement. If it does I will be one happy guy.

**Comment by guestisp** [comment]
@trops can't use send custom header when accessing to PS api from you app ? Brower auth is a standard HTTP header encoded in base64, you can easily add it in a couple of line of code.

**Comment by trops** [comment]
Im using the API tester with correct keys and OAuth1a and failing. I assume if this worked then I would be good to go with two-legged OAuth and can use mautic the way I want! Im excited, but can't get this to work. I have the code on my "services" server, and mautic on my other web server trying to communicate to the mautic api located on the web server. Any help would be great.

**Comment by alanhartless** [comment]
Is this still an issue? I've been using the api tester with oauth1a without an issue.  I'm assuming you created oauth 1a credentials?

What does the api tester return as the response from Mautic when attempting to auth?

**Comment by trops** [comment]
Hi Alan,

Well here is what I ended up doing. 

I used the API tester app to create a key, then used that key to connect to the API. This worked fine. 

The issues I am having now are as follows:

1. Cannot update points (not working via point actions and no way to manually change points in admin panel)
2. No way to update points via API

So I cannot use the points feature in Mautic whatsoever. Ive tried logging out, changing user, etc etc. Not sure what to do. If I could update the points via API then that would be oh so cool and easy.

Thanks Again on a fantastic product. Its funny, Im not returning the phone calls from Pardot and Hubspot and they are wondering why..hahahaha

Cant wait to be able to use Mautic fully!

**Comment by alanhartless** [comment]
Do you want to create a new feature request to be able to add points via the API? I don't think we have one pending for that yet.  I think there is one to support adding points manually via the UI though.

What point actions are you trying that aren't working? 

Thanks! That's great :-)

**Comment by trops** [comment]
I have set a landing page wildcard to trigger adding points to an account.

So the page is 

http://www.swingbot.com/Account/Activate/*

And the points are “add 10”.

Nothing happens. And I know nothing is happening for other users because Im getting tons of folks created per day, and they all HAVE to activate their account and thats the page they have to go to. No points for ANY users at all.

This would be such an awesome thing.

I analyze videos into golf lessons automatically by computer. Depending on what you get wrong in your swing, I would like to put leads into different lists to send them info on how to fix what they are doing wrong, purchase products that can help, etc. 

The points would allow me to also score the leads and see how many times they hit the pricing page, watched a drill video, etc etc.

Is this a cron issue possibly? I just want to make sure I am doing everything right and not barking up the wrong tree here.

And I thought I DID put in a feature request. Where can I do that?

Thanks,
John

**Comment by trops** [comment]
I am still trying to get the points working. I have a campaign that uses leas lists, and one of the items in the campaign is to add a point to the lead once they are a member of the lead list. So the user is added to the list, then the campaign, and no points are added. 

Is there a way that I can debug this somehow? The points just do not want to work any way I slice it.

**Comment by derwaldgeist** [comment]
I can't believe that the API access workflow is so overcomplicated with Mautic. Why the heck should I need a manual process involved here, if I want to call APIs between backends?! This is in face the first API I ever saw that uses a manual OAuth step. It should be possible to request a token just using the API credentials.
