### ISSUE TITLE
Bounce Segment Not Getting Updated

### ISSUE THREAD

**Issue by swaraj02** [mautic/mautic#10019]
## Bug Description

Mautic is not able to detect the bounce emails and update it to the Bounce segment. I have configured the settings as per documentation and using Sendgrid mail server and webhook. Bounce contacts are not even getting updated as 'Do not contact'. 

Meanwhile, I am receiving bounce emails in my inbox with the Return-Path: <name+bounce_609d0022cdc3c142236012@domain.com>

Unsubscribe on the other hand works perfectly with the same settings. I am not able to figure out the problem, please help. 

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 7.4.18
| Browser | Google Chrome

### Steps to reproduce
1. Bounce setup done correctly with test connection and fetch folders showing success
2. Run the campaign or segment email to send a bounce email. 
3. Check the mail attached in email settings for bounce management to see if bounce mail has been received in inbox or not. 
4. Check the Bounce Segment that a filter set with "Bounce Email equals Yes". No contact has been added to this segment. 

 
### Log errors
No log errors 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @swaraj02 !
You talk about issue on segment update, but is your contact flagged as bounced ? I have the feeling your issue is more on the communication between bouncing server and Mautic app. Which would mean that your issue is a email transport configuration issue.

Thanks
