### ISSUE TITLE
CLI installer doesn't pull admin username, firstname or lastname from the config

### ISSUE THREAD

**Issue by thinkl33t** [mautic/mautic#10018]
## Bug Description

When installing using the CLI installer, config variables can be set in `local.php`, including the admin's email address and password.  These can additionally be set on the command line, which overrides the values in `local.php`.

Unfortunately, the values set for admin firstname, lastname and username are not pulled from `local.php`, and are instead set to `Admin`, `Mautic` and `admin`.

I've done some digging, and believe this is happening because these values are being provided as defaults for the CLI in InstallCommand.php @ https://github.com/mautic/mautic/blob/3.3/app/bundles/InstallBundle/Command/InstallCommand.php#L127

I believe we could fix this by setting these defaults later if they weren't provided in either the CLI or existing config, similar to how we set `mailer_from_name` here for example at https://github.com/mautic/mautic/blob/3.3/app/bundles/InstallBundle/Command/InstallCommand.php#L298

| Q   | A
| --- | ---
| Mautic version | v3.3.3
| PHP version | 7.3
| Browser | CLI

### Steps to reproduce
1. Set `admin_username` to `foo` in local.php
2. Run CLI installer without setting `--admin_username`
3. Admin user will have the username `admin`

**Comment by shinde-rahul** [comment]
I am able to reproduce the issue. And fix https://github.com/mautic/mautic/pull/10104  work as expected.

**Comment by npracht** [comment]
Please @thinkl33t add your review on https://github.com/mautic/mautic/pull/10104
