### ISSUE TITLE
Database install says it broke

### ISSUE THREAD

**Issue by sbrinaz** [mautic/mautic#1001]
I have a MySQL database and I know I am putting in the write information related to all this.

localhost
database name and user and password are correct.
port 3306
I added a table pre-fix...

MySQL PDO

Not sure if to select MySQLi which I don't know what that is.

**Comment by alanhartless** [comment]
Please provide more details to debug this.  What error are seeing? Is there anything recorded in the app/logs directory and/or your system's PHP error log?

Thanks!

**Comment by alanhartless** [comment]
Just following up to see if this is still an issue or if it was resolved?

**Comment by sbrinaz** [comment]
I actually don’t know how to disable the item on the server.....need some advice there....thanks for following up.

**Comment by escopecz** [comment]
"Disable the item"? What item? Please, try to be more clear about what your problem is. What steps you've taken, did you see some error? Is some error message recorded in the error logs?

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to comment with any update and we'll open it again.
