### ISSUE TITLE
SugarCRM/SuiteCRM API: "Update blank values" setting not working. 

### ISSUE THREAD

**Issue by evgu** [mautic/mautic#10022]
## Bug Description
We use the SugarCRM-Mautic integration plugin. We use SuiteCRM (community edition). 

Mautic API plugin has a setting "Update blank values" - when set, it should update blank values, on both SuiteCRM and Mautic, regardless of data priority. I.e. if one datastore has the value for a mapped field, where the other datastore has a blank, then the value will be updated.  

It appears that this setting makes no difference and blank values are not being updated with the values from the other system. Seems that the chosen data direction prevails instead.  

| Q   | A
| --- | ---
| Mautic version | 3.3.3
| SuiteCRM version | 7.10.30 (not SugarCRM)
| PHP version | 7.3.28
| Browser | Safari, Chrome latest 

### Steps to reproduce
1. Enable "Update blank values" on plugin setting. (ensure OAth and API is otherwise correctly functioning). 
2. Chose SuiteCRM to be the master of data for First Name & Last Name
3. Add new Contact on Mautic with First Name only. Wait for the cron job to sychronise Contact to a SuiteCRM Lead. 
4. Update Last Name on Mautic. 
5. Wait for the next cron run to syncronise. This should the override SuiteCRM Lead's 'Last Name' which was a blank value.   
 
<img width="583" alt="Screenshot 2021-05-14 at 13 56 31" src="https://user-images.githubusercontent.com/18371928/118268809-273c9600-b4be-11eb-82d6-5f873e3152ef.png">

**Comment by npracht** [comment]
Hi @evgu, did you test https://github.com/mautic/mautic/pull/9160 ?
Obviously it is not supported by default without this PR.

**Comment by evgu** [comment]
I can't even test PR #9160, as the standard push to SuiteCRM integration (with all mandatory fields completed) doesn't work for us. #10024 needs reopening. thanks.
