### ISSUE TITLE
Feature Request - Expanded Salesforce Integration

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1002]
Hi,

Would be great to have a Salesforce CRM integration.
That would allow:
* Bi-directional synchronization
* Automatic matching of standard fields (first name, company name...)
* Manual set up of custom fields matching
* Generate tasks into SFDC from a campaign or a form submission

*Our dev team has this task in the backlog. We plan to work on that if none start working on it before.
Feel free to add comments or contribute.*

Attached screenshot of competitor field matching
![crm field mapping](https://cloud.githubusercontent.com/assets/14075239/10448776/5a664c4c-718f-11e5-9e68-2d5a218e067e.png)

Attached screenshot of competitor task scheduler from forms or campaigns
![schedule a task](https://cloud.githubusercontent.com/assets/14075239/10448875/1016ee84-7190-11e5-8a80-3168ab707ff9.png)

**Comment by alanhartless** [comment]
There is already basic Salesforce integration that will push Mautic leads into Salesforce but it does not support bi-directional sync yet or generating tasks.  Will definitely mark this as a feature request to beef that up if you guys aren't able to get to it first! :-)

**Comment by npracht** [comment]
Hi @alanhartless, i'd be very happy to make working our developer team with you on this project, it would be great opportunity to learn how to work together on a project knowing that they'll be more and more contributing to the community.

We'll contact you when we'll start working on it (please do the same if you start before us).

N.

**Comment by ptcc** [comment]
:+1:

**Comment by dhyman** [comment]
We'd be interested in this also - has any progress been made?

**Comment by npracht** [comment]
Hi,

A first step in the SFDC integration has been reached thanks to @mqueme recent development https://github.com/mautic/mautic/pull/1825
Marianela, Are you able on the pull request to show a bit more of what it changes ? Maybe a pull request in the doc also ?

I don't know how far from the feature request here-above we are.

Thanks,

N.

**Comment by mqueme** [comment]
@npracht seems like everything except -> Generate tasks into SFDC from a campaign or a form submission

**Comment by npracht** [comment]
Hi Marialena,
Then this is super great :-)

Thanks a lot for that !
