### ISSUE TITLE
Form statistics dashboard involvement

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1003]
Hi,

Would be great to have more data displayed on the form dashboard in addition to the submissions.
- The amount of views
- The conversion rate (= amount of submissions / amount of views)

_Our dev team has this task in the backlog. We plan to work on that if none start working on it before.
Feel free to add comments or contribute._

Mautic form dashboard
![mautic form dashboard](https://cloud.githubusercontent.com/assets/14075239/10449169/182d4530-7192-11e5-8770-f39b9ac3eb8a.png)

Competitor form dashboard
![competitor form dashboard](https://cloud.githubusercontent.com/assets/14075239/10449168/18273834-7192-11e5-922b-618441c44e13.png)

**Comment by troelsfeodor** [comment]
Would be a great improvement
