### ISSUE TITLE
Feature Request - Spam assassin

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1004]
Hi,

It would be great on the email generator to be able to test the email with Spam Assassin to know if the email is considered as spammy or not.
- Add a button to check in one clic
- Display the result

Spam Assassin is an Open Source mail filter. More on http://spamassassin.apache.org/
_Our dev team has this task in the backlog. We plan to work on that if none start working on it before.
Feel free to add comments or contribute._

---

_Source: http://spamassassin.apache.org/_
**Features**

**Wide-spectrum:** SpamAssassin uses a wide variety of local and network tests to identify spam signatures. This makes it harder for spammers to identify one aspect which they can craft their messages to work around.
**Free software:** it is distributed under the same terms and conditions as other popular open-source software packages such as the Apache web server.
**Easy to extend:** Anti-spam tests and configuration are stored in plain text, making it easy to configure and add new rules.
**Flexible:** SpamAssassin encapsulates its logic in a well-designed, abstract API so it can be integrated anywhere in the email stream. The Mail::SpamAssassin classes can be used on a wide variety of email systems including procmail, sendmail, Postfix, qmail, and many others.
**Easy Configuration:** SpamAssassin requires very little configuration; you do not need to continually update it with details of your mail accounts, mailing list memberships, etc. Once classified, site and user-specific policies can then be applied against spam. Policies can be applied on both mail servers and later using the user's own mail user-agent application.

**Comment by that0n3guy** [comment]
I would like to note that this is easily achieved with 3rd party tools like:
* https://litmus.com/
* https://www.emailonacid.com/
* http://previewmyemail.com/
* https://targeted.io/
* http://www.emailreach.com/
* https://putsmail.com/

I think a good solution may be to provide integration w/ some of these services... maybe just a plugin that works with them.

**Comment by npracht** [comment]
That could be an alternative.
One point, SpamAssassin is free & OpenSource. For sure not as complete as Litmus, but that was not the aim of that feature request about previewing but more about testing the efficiency of your email in terms of spam (too much images, broken links, etc...)

Moreover, those previewer does not give you the results of a spam test where SpamAssassin is powerful.

N.

**Comment by that0n3guy** [comment]
Most of the providers above do spam testing and are much more comprehensive than just using SpamAssassin.  See here:

* https://litmus.com/spam-filter-tests
* http://previewmyemail.com/resources/topics/spam-filter-tests
* https://www.emailonacid.com/spam-testing
* etc...

I think b/c SpamAssassin requires additional server config, it probably should be an add-on.

**Comment by alanhartless** [comment]
There is a PHP library that integrates spamassassin at https://github.com/webeith/php-spamassassin that I've had bookmarked for a while but I haven't gotten around to testing it.  

Personally I find SpamAssassin weak when detecting if one's own email is spammy unless you're a blatant spammer using known spammy URLs. Although it might come in handy with some of the basic content scoring.  I'm inclined to agree that this should be an integration with a service; although if that library works, might be usable in a plugin.
