### ISSUE TITLE
Campaign Graph Statistic - all campaigns showing same graph

### ISSUE THREAD

**Issue by Jakub087** [mautic/mautic#1005]
Hi,

I have several campaigns and some of them are showing same graph for "leads added" - see picture below

![screen shot 2015-10-13 at 15 23 01](https://cloud.githubusercontent.com/assets/14121810/10455933/a3c00b42-71be-11e5-8d7a-226eef2465c6.jpg)

How is this possible? Any idea how to fix this? :)

**Comment by alanhartless** [comment]
I'm not seeing this on any of my campaigns.  What are your campaigns based on (lead lists or campaign forms)? If lead lists, are they showing the same number of leads?

**Comment by Jakub087** [comment]
Hi @alanhartless ,

campaigns are based on campaign forms. After they submit forms, then its followed by 2 actions: 
- "send email"
- "add lead to selected list"

**Comment by alanhartless** [comment]
I'm assuming those campaigns aren't using the same campaign forms as lead sources?

I've checked several Mautic installations with active campaigns and I'm afraid that none are exhibiting this behavior.  Without being able to reproduce, it'll be tricky for us to debug.  Are you able to find anything to pin-point what could be causing it?

**Comment by Jakub087** [comment]
Your assumption is correct. 

I am not able to find pin-points... Will You if I tell You what is my account in Mautic?

Thanks

**Comment by escopecz** [comment]
Is fixed in https://github.com/mautic/mautic/pull/1169 and will be released in Mautic 1.4.0.
