### ISSUE TITLE
Landing page only looks ok when logged in mautic

### ISSUE THREAD

**Issue by sofocle80** [mautic/mautic#10057]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Creating a new landing page, with inline CSS looks ok in Builder, same with preview - looks good while logged in - but once you try from a different pc or logged out from mautic the formatting is misarranged. All the text is aligned to left.

What I want to test is a survey Landing page, using forms.

The code looks like this:
 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document
    </title>
    <link rel="stylesheet" href="style.css" />
    <script type="text/javascript">
      /** This section is only needed once per page if manually copying **/
      if (typeof MauticSDKLoaded == 'undefined') {
        var MauticSDKLoaded = true;
        var head = document.getElementsByTagName('head')[0];
        var script = document.createElement('script');
        script.type = 'text/javascript';
        script.src = 'https://xmail.indaco.ro/media/js/mautic-form.js';
        script.onload = function () {
          MauticSDK.onLoad();
        };
        head.appendChild(script);
        var MauticDomain = 'https://xmail.indaco.ro';
        var MauticLang = {
          submittingMessage: 'Please wait...',
        };
      }
    </script>
    <style>
      * {
        margin: 0;
        padding: 0;
      }
      nav {
        background: #234f77;
        height: 200px;
      }
      nav {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: horizontal;
        -webkit-box-direction: normal;
        -ms-flex-direction: row;
        flex-direction: row;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        border-bottom: 10px #3ea6d5 solid;
      }
      nav .logo {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: horizontal;
        -webkit-box-direction: normal;
        -ms-flex-direction: row;
        flex-direction: row;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
      }
      nav #navitems {
        margin: 0 20px;
      }
      nav img {
        height: 100px;
      }
      nav p {
        color: white;
        font-size: 24px;
        font-family: Arial, Helvetica, sans-serif;
      }
      section {
        padding-top: 50px;
      }
      footer {
        background: #f5f5f5;
        height: 150px;
      }
      .mauticform_wrapper {
        max-width: 920px;
        margin: 20px auto;
        color: #6f6f6f;
        font-weight: 400;
        font-family: 'Source Sans Pro', 'Helvetica Neue', 'Arial', 'sans-serif';
        font-size: 18px;
      }
      .mauticform-name {
        font-weight: bold;
        font-size: 1.5em;
        margin-bottom: 3px;
      }
      .mauticform-description {
        margin-top: 2px;
        margin-bottom: 10px;
      }
      .mauticform-error {
        margin-bottom: 10px;
        color: red;
      }
      .mauticform-message {
        margin-bottom: 10px;
        color: green;
      }
      .mauticform-row {
        display: block;
        margin-bottom: 20px;
        padding: 10px;
        border: 1px solid rgba(87, 77, 77, 0.308);
        border-radius: 10px;
      }
      .mauticform-label {
        font-size: 1.1em;
        display: block;
        font-weight: bold;
        margin-bottom: 5px;
      }
      .mauticform-row.mauticform-required .mauticform-label:after {
        color: #e32;
        content: ' *';
        display: inline;
      }
      .mauticform-helpmessage {
        display: block;
        font-size: 0.9em;
        margin-bottom: 3px;
      }
      .mauticform-errormsg {
        display: block;
        color: red;
        margin-top: 2px;
        display: none;
      }
      .mauticform-selectbox,
      .mauticform-input,
      .mauticform-textarea {
        width: 100%;
        height: 180px;
        padding: 5px;
        overflow: hidden;
        padding: 0.5em 0.5em;
        border: transparent;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
        -ms-overflow-style: none;
        /* IE and Edge */
        scrollbar-width: none;
        /* Firefox */
      }
      .mauticform-checkboxgrp-label {
        font-weight: normal;
      }
      .mauticform-radiogrp-label {
        font-weight: normal;
      }
      .mauticform-button-wrapper .mauticform-button.btn-default {
        color: #5d6c7c;
        background-color: #ffffff;
        border-color: #dddddd;
      }
      .mauticform-button-wrapper .mauticform-button.btn-default:hover {
        color: #7b9cc0;
        background-color: #ffffff;
        border-color: #a1a1a1;
      }
      .mauticform-button-wrapper .mauticform-button {
        display: inline-block;
        margin-bottom: 0;
        font-weight: 600;
        text-align: center;
        vertical-align: middle;
        cursor: pointer;
        background-image: none;
        border: 1px solid transparent;
        white-space: nowrap;
        padding: 6px 12px;
        font-size: 13px;
        line-height: 1.3856;
        border-radius: 3px;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }
      .mauticform-button-wrapper .mauticform-button.btn-default[disabled] {
        background-color: #ffffff;
        border-color: #dddddd;
      }
      .radio-flex-scale-sat {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: horizontal;
        -webkit-box-direction: normal;
        -ms-flex-direction: row;
        flex-direction: row;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: end;
        -ms-flex-align: end;
        align-items: flex-end;
      }
      .radio-flex-scale-sat input {
        margin-right: 10px;
        margin-left: 10px;
      }
      .radio-flex-scale-aff {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: horizontal;
        -webkit-box-direction: normal;
        -ms-flex-direction: row;
        flex-direction: row;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: end;
        -ms-flex-align: end;
        align-items: flex-end;
      }
      .radio-flex-scale-aff input {
        margin-right: 10px;
        margin-left: 10px;
      }
      .aflex {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
      }
      .one-five {
        -webkit-transform: translateX(10px);
        transform: translateX(10px);
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
      }
      .one-five span {
        margin: 0 12px;
        margin-top: 15px;
      }
      .one-five-aff {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-pack: distribute;
        justify-content: space-around;
      }
      .one-five-aff span {
        margin: 0 12px;
      }
      #mauticform_formchestionarfreemiumtest_submit {
        border: none;
      }
      #mauticform_formchestionarfreemiumtest_test_scale {
        margin-bottom: 10px;
      }
      #mauticform_input_formchestionarfreemiumtest_avantaje {
        height: 50px;
      }
      #mauticform_input_formchestionarfreemiumtest_observatii_dezavantaje {
        height: 50px;
      }
      #mauticform_formchestionarfreemiumtest_afirmatii_1__5 {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
      }
      .mauticform-radiogrp-row-afirmatii {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
        text-align: center;
        margin: 10px;
      }
      option {
        margin: 10px 0px;
        color: #6f6f6f;
        font-weight: 400;
        font-family: 'Source Sans Pro', 'Helvetica Neue', 'Arial', 'sans-serif';
      }
      section {
        margin: 0;
        padding: 0;
      }
      @media (max-width: 1090px) {
        .mauticform-row {
          width: 75%;
          margin: auto;
          margin-bottom: 20px;
        }
      }
      @media (max-width: 500px) {
        nav {
          display: -webkit-box;
          display: -ms-flexbox;
          display: flex;
          -webkit-box-orient: vertical;
          -webkit-box-direction: normal;
          -ms-flex-direction: column;
          flex-direction: column;
          -webkit-box-pack: center;
          -ms-flex-pack: center;
          justify-content: center;
          -webkit-box-align: center;
          -ms-flex-align: center;
          align-items: center;
          height: 200px;
          border: none;
        }
        nav .logo {
          display: -webkit-box;
          display: -ms-flexbox;
          display: flex;
          -webkit-box-orient: vertical;
          -webkit-box-direction: normal;
          -ms-flex-direction: column;
          flex-direction: column;
          -webkit-box-align: center;
          -ms-flex-align: center;
          align-items: center;
        }
        nav img {
          height: 100px;
        }
        nav p {
          display: none;
        }
        .one-five-aff {
          display: -webkit-box;
          display: -ms-flexbox;
          display: flex;
          -ms-flex-pack: distribute;
          justify-content: space-around;
        }
        .one-five-aff span {
          margin: 0 12px;
        }
        section {
          padding-top: 10px;
          padding-left: 10px;
          padding-right: 10px;
        }
        .mauticform-row {
          width: 85%;
          margin: auto;
          margin-bottom: 20px;
        }
        .one-five {
          -webkit-transform: translateX(0px);
          transform: translateX(0px);
          display: -webkit-box;
          display: -ms-flexbox;
          display: flex;
          -webkit-box-pack: space-evenly;
          -ms-flex-pack: space-evenly;
          justify-content: space-evenly;
        }
        .one-five-aff span {
          margin-top: 0px;
        }
        .radio-flex-scale-sat {
          display: -webkit-box;
          display: -ms-flexbox;
          display: flex;
          -webkit-box-pack: space-evenly;
          -ms-flex-pack: space-evenly;
          justify-content: space-evenly;
          -webkit-box-align: center;
          -ms-flex-align: center;
          align-items: center;
        }
        .radio-flex-scale-aff {
          display: -webkit-box;
          display: -ms-flexbox;
          display: flex;
          -webkit-box-orient: horizontal;
          -webkit-box-direction: normal;
          -ms-flex-direction: row;
          flex-direction: row;
          -webkit-box-pack: space-evenly;
          -ms-flex-pack: space-evenly;
          justify-content: space-evenly;
          -webkit-box-align: center;
          -ms-flex-align: center;
          align-items: center;
        }
        #hidden {
          display: none;
        }
      }
      @media (max-height: 580px) {
        nav {
          display: -webkit-box;
          display: -ms-flexbox;
          display: flex;
          -webkit-box-orient: vertical;
          -webkit-box-direction: normal;
          -ms-flex-direction: column;
          flex-direction: column;
          -webkit-box-pack: center;
          -ms-flex-pack: center;
          justify-content: center;
          -webkit-box-align: center;
          -ms-flex-align: center;
          align-items: center;
          height: 200px;
          border: none;
        }
        nav .logo {
          display: -webkit-box;
          display: -ms-flexbox;
          display: flex;
          -webkit-box-orient: vertical;
          -webkit-box-direction: normal;
          -ms-flex-direction: column;
          flex-direction: column;
          -webkit-box-align: center;
          -ms-flex-align: center;
          align-items: center;
        }
        nav img {
          height: 100px;
        }
        nav p {
          padding-top: 15px;
        }
        section {
          padding-top: 10px;
          padding-left: 10px;
          padding-right: 10px;
        }
      }
      /*# sourceMappingURL=style.css.map */
    </style>
  </head>
  <body>
    <nav>
      <div class="logo">
        <img id="navitems" src="pathtomypicture..." alt="" />
        <p id="navitems">.......................
        </p>
      </div>
    </nav>
    <div
 id="mauticform_wrapper_formchestionarfreemiumtest" class="mauticform_wrapper" />
      <form
 autocomplete="false" role="form" method="post" action="https://xmail.indaco.ro/x-mautic/form/submit?formId=2" id="mauticform_formchestionarfreemiumtest" data-mautic-form="formchestionarfreemiumtest" enctype="multipart/form-data" />
        <div
 class="mauticform-error" id="mauticform_formchestionarfreemiumtest_error" />
        </div>
        <div
 class="mauticform-message" id="mauticform_formchestionarfreemiumtest_message" />
        </div>
        <div class="mauticform-innerform">
          <div
 class="mauticform-page-wrapper mauticform-page-1" data-mautic-form-page="1" />
            
            
            <main />
              <div
 id="mauticform_wrapper_formchestionarfreemiumtest" class="mauticform_wrapper" />
              <form
 autocomplete="false" role="form" method="pos~t" action="https://xmail.indaco.ro/x-mautic/form/submit?formId=2" id="mauticform_formchestionarfreemiumtest" data-mautic-form="formchestionarfreemiumtest" enctype="multipart/form-data" />
              <div
 class="mauticform-error" id="mauticform_formchestionarfreemiumtest_error" />
              </div>
            <div
 class="mauticform-message" id="mauticform_formchestionarfreemiumtest_message" />
          </div>
          <div class="mauticform-innerform">
            <div
 class="mauticform-page-wrapper mauticform-page-1" data-mautic-form-page="1" />
            <div
 id="mauticform_formchestionarfreemiumtest_introducere1" class="mauticform-row mauticform-freetext mauticform-field-1" />
            <h3
 id="mauticform_label_formchestionarfreemiumtest_introducere1" for="mauticform_input_formchestionarfreemiumtest_introducere1" class="mauticform-label" />
            Vă mulțumim că ați ales ...................!
            </h3>
          <div
 id="mauticform_input_formchestionarfreemiumtest_introducere1" name="mauticform[introducere1]" value="" class="mauticform-freetext" />
          <br style="box-sizing: border-box" />Pentru o mai bună
          înțelegere a nevoilor dumneavoastră și a imbunătățirii
          serviciului prestat, vă rugăm să răspundeți acestui
          chestionar.
          <br style="box-sizing: border-box" />
          <br
 style="box-sizing: border-box" />
          <span
 fr-original-style="color: rgb(226, 80, 65);" style="color: rgb(226, 80, 65); box-sizing: border-box">*Required
          </span
>
          <br style="box-sizing: border-box" />
          <br
 style="box-sizing: border-box" />
        </div>
        </div>
      
      <section id="Q1">
        <div
 id="mauticform_formchestionarfreemiumtest_test_scale" data-validate="test_scale" data-validation-type="radiogrp" class="                        mauticform-row                        mauticform-radiogrp                        mauticform-field-1                        mauticform-required                        " />
        <label
 class="mauticform-label" for="mauticform_radiogrp_radio_test_scale_FNes1">Cum apreciați satisfacția dumneavoastră în legatură cu
          utilizarea portalului ........................?
        </label
>
        <div class="one-five">
          <span>1
          </span> 
          <span>2
          </span> 
          <span>3
          </span> 
          <span>4
          </span>
          <span>5
          </span>
        </div>
        <div class="radio-flex-scale-sat">
          <span id="hidden">Foarte nemulțumit
          </span>
          <div class="mauticform-radiogrp-row">
            <label
 id="mauticform_radiogrp_label_test_scale_10" for="mauticform_radiogrp_radio_test_scale_10" class="mauticform-radiogrp-label">
              <input name="mauticform[utilizarea_portalului_ind1]" class="mauticform-radiogrp-radio" id="mauticform_radiogrp_radio_utilizarea_portalului_ind1_FoarteNemultumitor0" type="radio" value="Foarte Nemultumitor" />
            </label>
          </div>
          <div class="mauticform-radiogrp-row">
            <label
 id="mauticform_radiogrp_label_test_scale_21" for="mauticform_radiogrp_radio_test_scale_21" class="mauticform-radiogrp-label">
              <input name="mauticform[utilizarea_portalului_ind1]" class="mauticform-radiogrp-radio" id="mauticform_radiogrp_radio_utilizarea_portalului_ind1_Nemultimitor1" type="radio" value="Nemultimitor" />
            </label>
          </div>
          <div class="mauticform-radiogrp-row">
            <label
 id="mauticform_radiogrp_label_test_scale_32" for="mauticform_radiogrp_radio_test_scale_32" class="mauticform-radiogrp-label">
              <input name="mauticform[utilizarea_portalului_ind1]" class="mauticform-radiogrp-radio" id="mauticform_radiogrp_radio_utilizarea_portalului_ind1_NiciNici2" type="radio" value="Nici - Nici" />
            </label>
          </div>
          <div class="mauticform-radiogrp-row">
            <label
 id="mauticform_radiogrp_label_test_scale_43" for="mauticform_radiogrp_radio_test_scale_43" class="mauticform-radiogrp-label">
              <input name="mauticform[utilizarea_portalului_ind1]" class="mauticform-radiogrp-radio" id="mauticform_radiogrp_radio_utilizarea_portalului_ind1_Multumitor3" type="radio" value="Multumitor" />
            </label>
          </div>
          <div class="mauticform-radiogrp-row">
            <label
 id="mauticform_radiogrp_label_test_scale_54" for="mauticform_radiogrp_radio_test_scale_54" class="mauticform-radiogrp-label">
              <input name="mauticform[utilizarea_portalului_ind1]" class="mauticform-radiogrp-radio" id="mauticform_radiogrp_radio_utilizarea_portalului_ind1_FoarteMultumitor4" type="radio" value="Foarte Multumitor" />
            </label>
          </div>
          <span id="hidden">Foarte mulțumit
          </span>
        </div>
        <span class="mauticform-errormsg">This is required.
        </span>
        </div>
      </section>
    
    <section id="Q2">
      <div
 id="mauticform_formchestionarfreemiumtest_in_ce_categorie_de_varsta" data-validate="in_ce_categorie_de_varsta" data-validation-type="select" data-validate-multiple="true" class="                  mauticform-row                  mauticform-select                  mauticform-field-2                  mauticform-required                  " />
        <label
 id="mauticform_label_formchestionarfreemiumtest_in_ce_categorie_de_varsta" for="mauticform_input_formchestionarfreemiumtest_in_ce_categorie_de_varsta" class="mauticform-label">În ce categorie de vârstă vă încadrați?
        </label
>
        <select
 id="mauticform_input_formchestionarfreemiumtest_in_ce_categorie_de_varsta" name="mauticform[in_ce_categorie_de_varsta][]" value="" class="mauticform-selectbox" />
          <option value="18-20">18-20
          </option>
          <option value="21-29">21-29
          </option>
          <option value="30-39">30-39
          </option>
          <option value="40-49">40-49
          </option>
          <option value="50-59">50-59
          </option>
          <option value="60 sau mai în vârstă">
            60 sau mai în vârstă
          </option>
        </select>
        <span class="mauticform-errormsg" style="display: none">This is required.
        </span
>
      </div>
    </section>
    
    <section id="Q3">
      <div id="mauticform_formchestionarfreemiumtest_pe_ce_dispozitiv_utilizat" data-validate="pe_ce_dispozitiv_utilizat" data-validation-type="checkboxgrp" class="mauticform-rowmauticform-checkboxgrpmauticform-field-3mauticform-required">
        <label class="mauticform-label" for="mauticform_checkboxgrp_checkbox_pe_ce_dispozitiv_utilizat_Desktop1">Pe ce dispozitiv(e) utilizati portalul ....................?
        </label>
        <div class="mauticform-checkboxgrp-row">
          <label id="mauticform_checkboxgrp_label_pe_ce_dispozitiv_utilizat_Desktop0" for="mauticform_checkboxgrp_checkbox_pe_ce_dispozitiv_utilizat_Desktop0" class="mauticform-checkboxgrp-label">
            <input class="mauticform-checkboxgrp-checkbox" name="mauticform[pe_ce_dispozitiv_utilizat][]" id="mauticform_checkboxgrp_checkbox_pe_ce_dispozitiv_utilizat_Desktop0" type="checkbox" value="Desktop" />
            Desktop
          </label>
        </div>
        <div class="mauticform-checkboxgrp-row">
          <label id="mauticform_checkboxgrp_label_pe_ce_dispozitiv_utilizat_Tableta1" for="mauticform_checkboxgrp_checkbox_pe_ce_dispozitiv_utilizat_Tableta1" class="mauticform-checkboxgrp-label">
            <input class="mauticform-checkboxgrp-checkbox" name="mauticform[pe_ce_dispozitiv_utilizat][]" id="mauticform_checkboxgrp_checkbox_pe_ce_dispozitiv_utilizat_Tableta1" type="checkbox" value="Tableta" />
            Tableta
          </label>
        </div>
        <div class="mauticform-checkboxgrp-row">
          <label id="mauticform_checkboxgrp_label_pe_ce_dispozitiv_utilizat_Smartphone2" for="mauticform_checkboxgrp_checkbox_pe_ce_dispozitiv_utilizat_Smartphone2" class="mauticform-checkboxgrp-label">
            <input class="mauticform-checkboxgrp-checkbox" name="mauticform[pe_ce_dispozitiv_utilizat][]" id="mauticform_checkboxgrp_checkbox_pe_ce_dispozitiv_utilizat_Smartphone2" type="checkbox" value="Smartphone" />
            Smartphone
          </label>
        </div>
        <span class="mauticform-errormsg" style="display: none">This is required.
        </span>
      </div>
    </section>
    
    <section id="Q4">
      <div id="mauticform_formchestionarfreemiumtest_avantaje" data-validate="avantaje" data-validation-type="text" class="mauticform-row mauticform-text mauticform-field-4 mauticform-required">
        <label id="mauticform_label_formchestionarfreemiumtest_avantaje" for="mauticform_input_formchestionarfreemiumtest_avantaje" class="mauticform-label">7)	Prezentați-ne pe scurt, ce avantaje ați observat în experiența utilizării portalului ........
        </label>
        <input id="mauticform_input_formchestionarfreemiumtest_avantaje" name="mauticform[avantaje]" value="" placeholder="Completati aici..." class="mauticform-input" type="text" />
        <span class="mauticform-errormsg" style="display: none;">This is required.
        </span>
      </div>
    </section>
    
    <section id="Q5">
      <div id="mauticform_formchestionarfreemiumtest_observatii_dezavantaje" data-validate="observatii_dezavantaje" data-validation-type="text" class="mauticform-row mauticform-text mauticform-field-5 mauticform-required">
        <label id="mauticform_label_formchestionarfreemiumtest_observatii_dezavantaje" for="mauticform_input_formchestionarfreemiumtest_observatii_dezavantaje" class="mauticform-label">8)	Prezentați-ne pe scurt, ce dezavantaje sau probleme ați întâmpinat în experiența utilizării portalului .........
        </label>
        <input id="mauticform_input_formchestionarfreemiumtest_observatii_dezavantaje" name="mauticform[observatii_dezavantaje]" value="" placeholder="Completati aici..." class="mauticform-input" type="text" />
        <span class="mauticform-errormsg" style="display: none;">Acest camp este obligatoriu
        </span>
      </div>
    </section>
    
    <section id="Q6">
      <div id="mauticform_formchestionarfreemiumtest_afirmatii_1__5" data-validate="afirmatii_1__5" data-validation-type="radiogrp" class="mauticform-row mauticform-radiogrp mauticform-field-6 mauticform-required">
        <label class="mauticform-label" for="mauticform_radiogrp_radio_afirmatii_1__5_FoarteImprobabil1">Cum cotati, pe o scala de la 1 (foarte improbabil) la 5 (foarte probabil), urmatoarele afirmatii:
        </label>
        <span>"As recomanda ........ cunostintelor / colegilor (?) mei."
        </span>
        <div class="aflex">
          <div class="radio-flex-scale-aff">
            <div class="mauticform-radiogrp-row-afirmatii">
              <span id="hidden">Foarte Improbabil 
              </span>
              <label id="mauticform_radiogrp_label_afirmatii_1__5_FoarteImprobabil0" for="mauticform_radiogrp_radio_afirmatii_1__5_FoarteImprobabil0" class="mauticform-radiogrp-label">
                <input name="mauticform[afirmatii_1__5]" class="mauticform-radiogrp-radio" id="mauticform_radiogrp_radio_afirmatii_1__5_FoarteImprobabil0" type="radio" value="Foarte Improbabil" />
              </label>
            </div>
            <div class="mauticform-radiogrp-row-afirmatii">
              <span id="hidden">Improbabil
              </span>
              <label id="mauticform_radiogrp_label_afirmatii_1__5_Improbabil1" for="mauticform_radiogrp_radio_afirmatii_1__5_Improbabil1" class="mauticform-radiogrp-label">
                <input name="mauticform[afirmatii_1__5]" class="mauticform-radiogrp-radio" id="mauticform_radiogrp_radio_afirmatii_1__5_Improbabil1" type="radio" value="Improbabil" />
              </label>
            </div>
            <div class="mauticform-radiogrp-row-afirmatii">
              <span id="hidden">Neutru
              </span>
              <label id="mauticform_radiogrp_label_afirmatii_1__5_Probabil2" for="mauticform_radiogrp_radio_afirmatii_1__5_Probabil2" class="mauticform-radiogrp-label">
                <input name="mauticform[afirmatii_1__5]" class="mauticform-radiogrp-radio" id="mauticform_radiogrp_radio_afirmatii_1__5_Probabil2" type="radio" value="Neutru" />
              </label>
            </div>
            <div class="mauticform-radiogrp-row-afirmatii">
              <span id="hidden">Probabil
              </span>
              </label>
            <label id="mauticform_radiogrp_label_afirmatii_1__5_Probabil2" for="mauticform_radiogrp_radio_afirmatii_1__5_Probabil2" class="mauticform-radiogrp-label">
              <input name="mauticform[afirmatii_1__5]" class="mauticform-radiogrp-radio" id="mauticform_radiogrp_radio_afirmatii_1__5_Probabil3" type="radio" value="Probabil" />
              </div>
            <div class="mauticform-radiogrp-row-afirmatii">
              <span id="hidden"> Foarte Probabil
              </span>
              <label id="mauticform_radiogrp_label_afirmatii_1__5_FoarteProbabil3" for="mauticform_radiogrp_radio_afirmatii_1__5_FoarteProbabil3" class="mauticform-radiogrp-label">
                <input name="mauticform[afirmatii_1__5]" class="mauticform-radiogrp-radio" id="mauticform_radiogrp_radio_afirmatii_1__5_FoarteProbabil4" type="radio" value="Foarte Probabil" />
              </label>
            </div>
          </div>          
        </div> 
      </div>
      </div>
    <span class="mauticform-errormsg" style="display: none;">This is required.
    </span>
    </div>
  </section>

<div
 id="mauticform_formchestionarfreemiumtest_submit" class="            mauticform-row mauticform-button-wrapper mauticform-field-3            " />
  <button
 type="submit" name="mauticform[submit]" id="mauticform_input_formchestionarfreemiumtest_submit" value="" class="mauticform-button btn btn-default" />
    Trimite
  </button>
</div>
</div>
</div>
<input
 type="hidden" name="mauticform[formId]" id="mauticform_formchestionarfreemiumtest_id" value="2" />
<input
 type="hidden" name="mauticform[return]" id="mauticform_formchestionarfreemiumtest_return" value="" />
<input
 type="hidden" name="mauticform[formName]" id="mauticform_formchestionarfreemiumtest_name" value="formchestionarfreemiumtest" />
</form>
</div>
</body>
</html>

| Q   | A
| --- | ---
| Mautic version | 2.16.5
| PHP version | .PHP Version 7.2.24-0ubuntu0.18.04.7
| Browser | Chrome and Firefox

### Steps to reproduce
1. Create a landing page using custom code and mautic forms
2. Page looks good in the builder or Previewing/Public Preview URL **while logged in.**
3. Page look bad with no formatting when you are not logged in
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @sofocle80 !
Please not we don't support 2.x version which is too old.

When you go in your private browser and see the wrong way of display, do you have any message in your console ? I have the feeling you might have a third party file including CSS which is blocked.
