### ISSUE TITLE
CSRF token is invalid

### ISSUE THREAD

**Issue by ichbas** [mautic/mautic#1006]
When attempting to install Mautic I get the following error under Mautic Installation - Environment Check and i cannot get to the next step:
The CSRF token is invalid. Please try to resubmit the form.

When I check the server error log I get the following errors:
20151013T112408: www.website.com/mautic/index.php/s/ajax 
PHP Warning:  SessionHandler::read(): open(/var/php_sessions/sess_33028e14f2dab7e77692cf5e00c8f707, O_RDWR) failed: No such file or directory (2) in /path/to/mautic/app/cache/prod/classes.php on line 411 
PHP Warning:  SessionHandler::write(): open(/var/php_sessions/sess_33028e14f2dab7e77692cf5e00c8f707, O_RDWR) failed: No such file or directory (2) in /path/to/mautic/app/cache/prod/classes.php on line 415 

any ideas on how to fix this?

**Comment by alanhartless** [comment]
This seems to be more of an PHP/server issue and not a Mautic one.  Your php.ini must be configured to write sessions to /var/php_sessions/ but it either doesn't exist or is not writable by your PHP/web user. 

Thanks!

**Comment by ichbas** [comment]
I had my webhost tech support check it out and he said that the directory in question had proper CHMOD.

**Comment by ichbas** [comment]
could you give me an example of what that line in the php.ini should look like so I can double check my php.ini to make sure something isn't wrong?

**Comment by zaibatsu777** [comment]
Any luck?
