### ISSUE TITLE
Oauth1 not working in M4 anymore 

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#10075]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Should be removed in M4

![image](https://user-images.githubusercontent.com/462477/119152537-b0207800-ba50-11eb-8595-d36ab4f2d016.png)

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
@RCheesley

**Comment by RCheesley** [comment]
It should be removed but nobody has made the PR yet. This is intended, we agreed some time ago to remove OAuth1 given that it has been deprecated since 2012.

**Comment by RCheesley** [comment]
Closing this as we have now merged the PR that will remove OAuth1 completely 🎉
