### ISSUE TITLE
themed emails with css classes are not correctly rendered in gmail

### ISSUE THREAD

**Issue by ptcc** [mautic/mautic#1010]
i tested sending an email with a theme and unless all the styles are inline on style attributes, gmail will render the email incorrectly.
This is because of #925

A diferent but related issue: an email with mauve is also incorrectly rendered (the table width is ok, but the rows do not expand to the full intended width, unlike when we see the preview in browser... i think the width has to be explicitly set in the tr and/or td elements)

**Comment by escopecz** [comment]
Style a HTML theme to be rendered correctly with all email clients is a challenge. Does the content in the GMail overflow from the table cell? If the cell width is not set, it should stretch by the content in it. Maybe GMail doesn't display the min-height statement.

Mauve email theme uses inline styles:
https://github.com/mautic/mautic/blob/staging/themes/Mauve/html/email.html.php

**Comment by ptcc** [comment]
I'm sorry for mixing the mauve issue here: it is inline indeed, and so it is a different issue.

I know that getting a theme to render correctly with all email clients is challenging.
Still, we could use what already exists that works nicely:

I'm using Zurb Ink: http://zurb.com/ink/  to build my theme structure, and it works nicely accross most email clients. The issue is that after creating a new email I have to manually run it through an inliner and send it without theme, using the html generated by the inliner.

I tried inlining the theme html itself and using that, but something goes wrong after I create an email using that (when I press "close builder" it hangs with the spinning loading indicator... never returning to the email edition screen).

I can provide my theme here, with inline styles or without... so that you can see what i mean.

**Comment by alanhartless** [comment]
If the close builder hangs, there might be either a JS error or a PHP error.  Can you try repeating the issue with the browser console open to see if there are any JS errors noted?

If it's a 500, then look at your Mautic logs to see if something is revealed there.

**Comment by escopecz** [comment]
Closing this issue for lack of feedback
