### ISSUE TITLE
/stats/lead_lists_leads not returning all data in response

### ISSUE THREAD

**Issue by ManalLiaquat** [mautic/mautic#10100]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | using mautic endpoints
| PHP version | using nodejs
| Browser | Chrome

### Steps to reproduce
1. Call the API
2. it returns only 100 results (if you have more than 100 results in the dashboard)
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

Getting only 100 results from  this `/stats/lead_lists_leads` endpoint but it shows a total of 288

![image](https://user-images.githubusercontent.com/36041100/119660376-0b9d8d80-bde4-11eb-9536-29a618e58ff3.png)

**Comment by kuzmany** [comment]
Did you try start and limit parameter based on docs https://developer.mautic.org/#get-stats-from-a-table ?

**Comment by ManalLiaquat** [comment]
> Did you try start and limit parameter based on docs https://developer.mautic.org/#get-stats-from-a-table ?

Thanks for your reply... Limit param solves my problem, but I have to call API first time to get the total records then pass the total to the same api with limit param then I get all records and this is not good... By default all records should be return

**Comment by kuzmany** [comment]
Any contributions are welcome
