### ISSUE TITLE
Multiple Campaigns Caught Disk Full Error

### ISSUE THREAD

**Issue by atharvitsolutions** [mautic/mautic#10107]
Hi Friends,

I am running a mautic instance with 45,000 contacts segmented differently. 2 day's back I have created around 6 campaigns having 7 emails series in each campaign with segment contact size around 4500. 

I have noticed that all segments contact triggers were well scheduled as per the campaign I have set but unfortunately my hosting encountered an disk full error something like this - "Warning: mysqli_query(): (HY000/1021): Disk full (/dev/shm/#sql_cb9f_36.MAI); waiting for someone to free some space... (errno: 28 "No space left on device")"

I have also noticed that MySQL data size goes to 3151 MB (Hosting allowed size if 6000 MB per MySQL database). I have escalated this issue to the hosting team and they have responded something like this - "This can be caused by huge temporary tables and unoptimized mysql queries running on your websites"

So, my query based on this experience is...
1. Is it advisable to create multiple campaigns ?
2. Is there any database size I should have to allocate to perform multiple campaigns?
3. Is there any limit on the contacts I should keep in mind while creating multiple campaigns?

Mautic Version: v2.16.3
PHP: 7.0

Regards,
Dhaval Goradia

**Comment by atharvitsolutions** [comment]
My another Mautic Instance also triggered same Disk Full error because of Mautic Datasize exceeded 3 GB

**Comment by npracht** [comment]
Hi there,

You need to allocate the server resources necessary for your app !
Also your app version is very old, i'd recommend you to upgrade your Mautic version to 3.x.

I'll close this issue and i let you join the community to discuss this on Slack or Forums.
