### ISSUE TITLE
Campaign without contacts

### ISSUE THREAD

**Issue by ah2020b** [mautic/mautic#10106]
Hi

Every campaign that I created, show there is no contact. And campaing is not sending.

![image](https://user-images.githubusercontent.com/30999942/119892009-86c08a00-bf31-11eb-9e18-58ca2ca8b3cd.png)

![image](https://user-images.githubusercontent.com/30999942/119892143-ba9baf80-bf31-11eb-9f8c-213d48b5b0c9.png)

![image](https://user-images.githubusercontent.com/30999942/119892167-c1c2bd80-bf31-11eb-92e7-30ca0ba434ca.png)
![image](https://user-images.githubusercontent.com/30999942/119892215-d1da9d00-bf31-11eb-96e5-f4671817cf3e.png)

**Comment by atharvitsolutions** [comment]
Possibly your cron jobs are not working 

https://docs.mautic.org/en/setup/cron-jobs

**Comment by npracht** [comment]
Please check your CRONjob and move to forum or slack for discussions.
Best
