### ISSUE TITLE
[BUG] Lead tags disappear from profile when it becomes from anonymous to known lead

### ISSUE THREAD

**Issue by inseti** [mautic/mautic#1011]
I'm using the pixel to track and add a tag to the user when he visits a page in the website.

The tag is added properly to the anonymous lead, but the tag is deleted from his profile when the user becomes a known lead after a form submit.

I can see the visited pages in the lead's log, but the tags that were assigned when he was an anonymous lead have been disappeared.

**Comment by mackadamian** [comment]
We are currently experiencing this issue... on both self hosted and Mautic hosted installations. Seems to have started after the upgrade to version 1.4.0. Tagging is working perfectly, using the pixel to track and add a tag to the user when he visits a page in the website. But when the API runs, the tags are removed.

https://www.mautic.org/community/index.php/969-issue-with-lead-tags/0#p12351
