### ISSUE TITLE
Mautic 4: Clicking on view contacts for a tag shows no contacts

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#10119]
Mautic version: Mautic 4.0-beta

Raised by @Christophe9880 in #10110 

Have made a short vid about it: https://youtu.be/hOpjIoJfk88

I added a "tag" in a campaign, and I could see the tag was added at the contact, but when I click on "view contact" for a certain tag, no contacts were visible, but it's all clear in the vid.

**Comment by RCheesley** [comment]
@Christophe9880 I did some testing on this and the issue is that you have a space in the tag name and the filter is not using double quotes to search for the phrase, so it doesn't find it.

Here's a screen capture: https://youtu.be/-HiYLskwYKY

So the workaround is to add double quotes to the search phrase - but longer term we should probably make sure that we are using that in the search field.

**Comment by Christophe9880** [comment]
Hi Ruth, thx for your reply.
Just did the same search on my Mautic application, and I had the same... It worked if I did the search with the doublequote

![image](https://user-images.githubusercontent.com/82932885/120379522-2dd16700-c320-11eb-8177-ff8b49b49a44.png)

**Comment by RCheesley** [comment]
Pinging @luguenth for your thoughts on this issue?

**Comment by luguenth** [comment]
We defined that in the known issues of the PR.
It'll only appear for tags with whitespace in it. As described, we already tried to avoid this issue. But weren't able to do so :(
![image](https://user-images.githubusercontent.com/9964009/121346692-b6ef2c00-c926-11eb-80e7-b0e8333104a6.png)

**Comment by RCheesley** [comment]
Ahh thanks I had completely forgotten that! So it is something that we need to add in the release notes / documentation as a known issue I guess, and at some point the product team will need to decide how to address that. 

CC @mautic/core-team for thoughts/discussion

**Comment by npracht** [comment]
Why wouldn't we include automatically double quote in the search bar as we already do for companies for instance ?
Eg: create a company with a space in name. Add a contact to it. Go on companies > clic view 1 contact and in the contact list, the search is double quoted.
<img width="311" alt="Capture d’écran 2021-07-13 à 11 22 29" src="https://user-images.githubusercontent.com/14075239/125427051-fabdaa63-a906-450b-b16c-6f530d6605cd.png">

It should follow this same standard. And I believe we can easily get the code/string used here ?
<img width="1440" alt="Capture d’écran 2021-07-13 à 11 26 29" src="https://user-images.githubusercontent.com/14075239/125427760-18e28f30-1633-4133-9f70-2170ca7ea227.png">

**Comment by luguenth** [comment]
Ah that's nice. I thought we tried that. We will look into it :)

**Comment by RCheesley** [comment]
Yeah - that is what I was thinking might have worked, if it's not difficult to implement I think it would save a lot of frustration, as there will be a lot of folks who tag things using plain language rather than with hyphens.
