### ISSUE TITLE
Issue occurred in mautic 4.0.0-beta in Test Messages.

### ISSUE THREAD

**Issue by RehanNischal** [mautic/mautic#10115]
I tried to send a text message by using the Twilio plugin. The first message was sent successfully to a contact. But when I cloned that campaign and triggered it on the same contact with the same text message, an error occurred "Last execution: scheduled". I haven't set any frequency on the text message but it gets queued for the next day.
[](url)
![Capture23](https://user-images.githubusercontent.com/43839944/120111896-4fe8af00-c191-11eb-8854-e1364c803bea.PNG)

**Comment by Christophe9880** [comment]
@RehanNischal @RCheesley I reproduced this on my application and had the same error with the twillio plugin (I did exactly the same, I cloned the form and the campaign)

![image](https://user-images.githubusercontent.com/82932885/120382559-1300f180-c324-11eb-8eac-0f2d9e4f3de3.png)

**Comment by RCheesley** [comment]
Hi folks!

Thanks @RehanNischal for reporting this and @Christophe9880 for confirming!

Can you clarify if this is something new that is happening with Mautic 4? Does this happen in 3.3.3 if you clone the campaign, or does it all go through as expected without any warning?

**Comment by RCheesley** [comment]
@all-contributors please add @RehanNischal for bugs

**Comment by RCheesley** [comment]
@all-contributors please add @Christophe9880 for userTesting

**Comment by AntonioLangiu** [comment]
Hi, I have the same problem with a fresh install of Mautic 4.0.0.

I got just the first message sent to the contact, unless the settings of the contact are higher. However, my expectations are that in case the contact does not have a specific limit setting, it takes the one from Twilio. This does not happens. Even if I increase the Twilio plugin setting for limiting the number of messages, it stops to 1 per contact and reschedules the other messages.

**Comment by RCheesley** [comment]
Folks can you check if updating the default frequency in your global settings makes a difference? I wonder if this is related to https://github.com/mautic/mautic/issues/10416.
