### ISSUE TITLE
creating contacts on the "Do not contact" column does not work when import csv

### ISSUE THREAD

**Issue by iml885203** [mautic/mautic#10127]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
when import csv, creating contacts on the "Do not contact" column does not work.

it only work on update contact.

| Q   | A
| --- | ---
| Mautic version | 3.3.3 |
| PHP version | 7.3.20 |
| Browser | chrome |

### Steps to reproduce
1. Go to "Contacts"
2. click "Import"
3. Choose csv file and click "Upload"
4. select dropdown to Properties > Do not contact and click "import"
 
### Log errors

Contacts imported from csv did not show "Do not contact".

**Comment by npracht** [comment]
Hi there !
This is fixed by https://github.com/mautic/mautic/pull/9732. You can cherrypick it now and it'll be released in 4.0.

Enjoy !
