### ISSUE TITLE
[Bug] - Triggered Campagins

### ISSUE THREAD

**Issue by alvinbenavides** [mautic/mautic#1012]
Hi. I saw other issues related to campaigns and trigger but not this exact problem.

If I run /app/console mautic:campaigns:trigger I get this error. 

It seems to be on the "HAVING" line. Not sure if eh.event_id IN () is supposed to be empty.

```
[Doctrine\DBAL\DBALException] An exception occurred while executing 

SELECT e.lead_id, e.event_id, e.date_triggered, e.is_scheduled 
FROM campaign_lead_event_log e 
WHERE (e.campaign_id = 1) AND (e.lead_id IN (124, 196, 258, 522, 574, 897, 987, 1155, 1174, 1231)) 
HAVING ((SELECT count(eh.event_id) FROM campaign_lead_event_log eh WHERE (eh.lead_id = e.lead_id) AND (eh.event_id IN ())) > 0)
AND ((SELECT count(eh.event_id) FROM campaign_lead_event_log eh WHERE (eh.lead_id = e.lead_id) AND (eh.event_id IN (20, 21, 22))) = 0)

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))) > 0) AND ((SELECT count(eh.event_id) FROM campaign_lead_event_log eh WHERE (' at line 1 
```
This installation is a migration from 1.1.3 to 1.2.0 Not sure if its related. 

I tried fix #969 but still the same error near '))) > 0)...

If you need more info please let me know

Thanks

**Comment by alvinbenavides** [comment]
BTW. This is the campaign I'm running. I marked the events 20,21,22 according to DB

![mautic_campaign](https://cloud.githubusercontent.com/assets/10437896/10519214/72da73ec-732a-11e5-8582-4659e139b7db.png)

**Comment by escopecz** [comment]
Is this still an issue with Mautic 1.2.3?

**Comment by l2aelba** [comment]
@escopecz  seems like yes

**Comment by escopecz** [comment]
Heh, we have 1.2.4 now. Is it still problem in 1.2.4?

**Comment by l2aelba** [comment]
1.2.4 sir #1473

**Comment by escopecz** [comment]
Cool, so I'll close this issue when you created #1473
