### ISSUE TITLE
Remain at form don't working

### ISSUE THREAD

**Issue by Darko-F** [mautic/mautic#10138]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Expexting result **Remain at form**
After Successful Submit Action - ** Form Display Message**
| Q   | A
| --- | ---
| Mautic version | 3.3.3
| PHP version | 7.5
| Browser | Chrome

### Steps to reproduce
1. Create form and use Automatic - Via Javascript (recommended) code in HTML
2.  Settings: Form details - Successful Submit Action - Remain at form
3.  Successful Submit Action
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
