### ISSUE TITLE
[BUG] Form fields can't be reordered

### ISSUE THREAD

**Issue by inseti** [mautic/mautic#1013]
Using version 1.2 is impossible to reorder fields in a form.

If I add a new field and I relocate it in other position different than last position, when I save the field is again in last position.

The same occurs re-ordering any existing field in the form.

**Comment by escopecz** [comment]
This is known issue of 1.2.0. The fix is here:

https://github.com/mautic/mautic/pull/943

and will be available in 1.2.1.
