### ISSUE TITLE
Submit button doesn't always works

### ISSUE THREAD

**Issue by fmulassano** [mautic/mautic#10139]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have just sent out my first campaign with a request to fill in form to update some data.
Some user contact me saying the submit button doesn't work.
yet I tried it on mac with chrome and on linux with chrome and I had no problems.

I see something that varies in user configurations ... what can I do?

| Q   | A
| --- | ---
| Mautic version | 3.3.3
| PHP version | 7.4.18
| Browser | (from user) macOS Catalina (10.15.7) with Safari 14.1.1 and Google Chrome (91.0.4472.77)

### Steps to reproduce
1. 
2. 
 
### Log errors
no errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by fmulassano** [comment]
thank you @RCheesley
