### ISSUE TITLE
Package mautic/core-lib cannot install)

### ISSUE THREAD

**Issue by ger100** [mautic/mautic#10140]
Ubuntu 18.04.5 LTS
PHP version: PHP 7.4.16 
Browser: Crome  89.0.4389.128
Mautic version 4.0
Composer version: 1.6.3

I download Mautic zip file
- The file was unzipped and moved the files and directories from mautic-features directory up to one level into root under my domain
- cd into Mautic root directory
- After "composer install" I receive error message: 

Composer message:
In PathDownloader.php line 55: Package mautic/core-lib cannot install to "/var/www/MYDOMAIN/htdocs/app" inside its source at "/var/www/MYDOMAIN/htdocs/app" 

If I try to open Mautic in browser: server error occurs (HTTP code 500) because:
Nginx log:
No such file or directory in /var/www/MYDOMAIN/htdocs/autoload.php on line 13
message: PHP Fatal error:  require(): Failed opening required '/var/www/MYDOMAIN/htdocs/vendor/autoload.php'

mautic root/var/logs is empty

Did I forget to set anything?

**Comment by RCheesley** [comment]
@ger100 how did you do the install? What commands have you used? cc @nickveenhof

**Comment by ger100** [comment]
I followed the instructions, as it was mentioned here in Mautic github repo:
Installing Mautic is a simple three-step process:
- Download the repository zip then extract the zip to your web root.
- Run the composer install command to install the required packages.

After zip file extraction I got mautic-features folder with subfolders and files. I moved these one level up into root folder of the domain from mautic-features folder.

**Comment by RCheesley** [comment]
Right - but the features branch (Mautic 4) is in beta and should not be used for production - we have not yet updated the install instructions in the readme. We have a whole new way to install with composer with Mautic 4.

I noticed there seems to be a double slash in the path as well:

> /var/www//htdocs/app

Are you planning to use this in production? If so, please use the releases at https://github.com/mautic/mautic/releases or from https://mautic.org/download. Otherwise we will need to take a look at this @nickveenhof maybe?

**Comment by ger100** [comment]
Thank you for the quick reply again. The reason why I would like to install on a server, because I just would like to try the new features especially the new email and page builder. Could you suggest the proper install method? (local or server) Thank you.

The double slash was a github auto correction because I wrote MYDOMAIN into <  > and github deleted
The correct path is /var/www/MYDOMAIN/htdocs/app I made correction in the first post.

**Comment by nickveenhof** [comment]
Hi! I tried to replicate this but wasn't able. Is it possible to post the exact steps so we can reproduce this? It looks like your hosting provider might be able to assist you as well as this could be a folder permission problem

**Comment by nickveenhof** [comment]
Also, it's preferred you use composer 2.0, maybe that could be the issue?

**Comment by ger100** [comment]
Now the install process run without any failure with composer 2.1.3
Thank you for the advice.

The problem occured only with composer 1.

_(DOMAIN is my domain name)_
The folder which contains the contents of features folder is: /var/www/DOMAIN/htdocs
The owner and group of the files and folders and subfolders: www-data:www-data
I have write access for this directory and sub dirs and files as well

cd /var/www/DOMAIN/htdocs
git clone https://github.com/mautic/mautic.git
cp -r /var/www/DOMAIN/htdocs/mautic/* /var/www/DOMAIN/htdocs/
rm -rf mautic
composer install

. . .

In PathDownloader.php line 55:
                                                                                                                                            
  Package mautic/core-lib cannot install to "/var/www/DOMAIN/htdocs/app" inside its source at "/var/www/DOMAIN/htdocs/app"
