### ISSUE TITLE
Error importing leads into Mautic

### ISSUE THREAD

**Issue by Eduardrj** [mautic/mautic#10148]
500 Internal Server Error
PHP Version 7.4.19
Log : [2021-06-10 22:45:29] mautic.CRITICAL: Uncaught PHP Exception LogicException: "Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?)." at /home/public_html/mautic/vendor/symfony/http-foundation/File/MimeType/MimeTypeGuesser.php line 130 {"exception":"[object] (LogicException(code: 0): Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?). at /home/public_html/mautic/vendor/symfony/http-foundation/File/MimeType/MimeTypeGuesser.php:130)"} []

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)  It looks like you need to enable the php_fileinfo extension on your server.
