### ISSUE TITLE
Do Not Contact (Unsubscribe - Email) is not to be a filter for Dynamic Web Contact.

### ISSUE THREAD

**Issue by leoschuler** [mautic/mautic#10147]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I see a feature to include the do Not Contact filter was created (#4977)  BUT, that filter is only available in segment, it is not available in Dynamic Web Content Filters.

| Q   | A
| --- | ---
| Mautic version |  3
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a new Dynamic web Content , set as No the option to be a campaign base DWC.
2. go to the Filter tab
3. the option to filter by "Unsubscribe: Email / SMS"  is not there

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
