### ISSUE TITLE
GrapesJS email builder wipes out HTML head tags

### ISSUE THREAD

**Issue by patrykgruszka** [mautic/mautic#10142]
## Bug Description
Everything that is not in body section is removed from the email HTML when using GrapesJS builder.

| Q   | A
| --- | ---
| Mautic version | 3.3.3 and 4.0.0-beta
| PHP version | 7.4
| Browser | Any

### Steps to reproduce
1. Create email and select template that has HTML head section e.g. Blank
2. Open the builder
3. Close builder and save email
4. Open preview or send example
5. Head tags, custom html declaration or anything except body is replaced with default values

**Comment by RCheesley** [comment]
This should be fixed by #10114 - please can you test @patrykgruszka and let us know in the PR?
