### ISSUE TITLE
Stage-Change retries unlimited times, plus it's impossible to stop

### ISSUE THREAD

**Issue by imihandstand** [mautic/mautic#10145]
## Bug Description
I started using stages and got a huge problem: If a contact gets stage #2 and later a campaign tries to give it stage #1, it generates an error - which is totally okay.

_[Problem 1]_
However, **it retries it from than on every single hour** (and generates so every single hour a new error-notification)!

_[Problem 2]_
**Even worse: It's impossible to stop it even manually:** If I go to the contact and click the orange cross for "_Cancel this event_", it seemingly cancels it (I get the text "_This event was scheduled for June 8, 2021 10:40 pm CEST but has been cancelled._" as supposed to), but in real it does NOT cancel it, which I see from 2 things:
1.) Every hour it still retries that stage-change (and generates so an error-notification),
2.) plus when click that said cross to cancel it and than refresh the contacts page, it is not canceled.

**I recorded this:** https://www.screencast.com/t/12vxHm7d7
At first I show that a retry is scheduled. I cancel that retry. It shows that it's successfully cancelled. I refresh the page ("Neu laden"). After the page reloaded, it's visible that the retry was not cancelled and that it WILL retry it again.

So at the moment the absolute only way to stop these huge amount of error-notifications is to delete all of these contacts...

| Q   | A
| --- | ---
| Mautic version | 3.3.2
| PHP version | 7.3.28
| Browser | Firefox

### Steps to reproduce
1. Create a campaign, where the contact gets the stage #2 and than #1.
2. When it runs and creates an error, try to cancel this event from retrying on the contact's page
 
### Log errors
Nothing

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)  

You may also want to double check that you are not trying to move them to a stage with a lesser weight, per the [docs](https://docs.mautic.org/en/stages#moving-contacts-from-stage-to-stage):

> It is not possible to move a contact to a stage which has a lesser weight than their current stage. For example if they are currently in Stage B which has a weight of 50, you cannot move them to Stage A which has a weight of 25.

**Comment by imihandstand** [comment]
@RCheesley Isn't it a bug if I click CANCEL but it still continues trying it forever...?
And shouldn't it just be skipped (with 1 error) if the stage is lower? Instead of completely breaking the running of the campaign?
