### ISSUE TITLE
CSV import 'do not update existing contacts' switch (enhancement)

### ISSUE THREAD

**Issue by evgu** [mautic/mautic#10158]
Sometimes, when importing contacts from CSV file, we do not want to update the already existing in Mautic contatcs. I.e. we only want to import the new contacts into Mautic and leave any existing contacts as is. 

Suggestion is to: 
1. add a `--no-update` switch to  `bin/console mautic:import`. 
2. Update the help message of `bin/console mautic:import --help` 
3. Add "Do not update existing contacts" tick-box to the 'Import Contacts' web interface. 
4. Update documentation at https://docs.mautic.org/en/contacts/import-contacts

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
