### ISSUE TITLE
Renaming tag breaks ability to edit campaign step

### ISSUE THREAD

**Issue by victorburgos12** [mautic/mautic#10169]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you rename a tag using tag manager plugin and that tag is being used on any campaign step, you will not be able to open that step on campaign builder.
If you rename the tag to previous name, then you are able to open the step on campaign builder.

| Q   | A
| --- | ---
| Mautic version |  v3.3.3
| PHP version | 7.4.20
| Browser | Brave

### Steps to reproduce
1. Create new tag using tag manager plugin.
2. Create campaign with action Modify contact's tags.
3. Select created tag.
4. Close and save campaign.
5. Go to tag manager plugin and rename tag.
6. Go back to campaign and try to change action, you will not be able to do so.
7. <img width="560" alt="tag problem campaign builder" src="https://user-images.githubusercontent.com/37320468/122993174-9edacc00-d36c-11eb-98e8-5a5f9cd18147.png">
8. Action never opens and in php error you get PHP Notice:  Array to string conversion in /app/bundles/LeadBundle/Form/DataTransformer/TagEntityModelTransformer.php on line 120

 
### Log errors
Got error 'PHP message: PHP Notice:  Array to string conversion in /app/bundles/LeadBundle/Form/DataTransformer/TagEntityModelTransformer.php on line 120', referer: https://domain.com/s/campaigns/edit/6

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @victorburgos12 !
What is the tag manager plugin ?

**Comment by victorburgos12** [comment]
Hi @npracht, this is a new plugin created by mautic itself to manage tags.
This is the link here in github https://github.com/mautic/plugin-tagmanager.
<img width="733" alt="mautic tag manager" src="https://user-images.githubusercontent.com/37320468/123128588-e1ee7b00-d410-11eb-843f-b36052c1fcdc.png">

**Comment by RCheesley** [comment]
@luguenth any thoughts on this?

**Comment by luguenth** [comment]
I will look into it :)

**Comment by luguenth** [comment]
The Campaign action is saving the tag as a name and wants to identify the tag via name later. This can't work, because it has a new name and Mautic can't find the corresponding Tag. We would have to rewrite other Core Functions. But I didn't dig deeper than that right now
