### ISSUE TITLE
Assets not downloading in Gmail

### ISSUE THREAD

**Issue by ivan006** [mautic/mautic#10161]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I am having an issue with Gmail on Desktop Chrome blocking Asset downloads?

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 7.3.21
| Browser | Chrome

### Steps to reproduce
The chrome tab opens then closes with no download.

Issue seems to be exclusive to the above setup, works fine in all other browsers and applications. 
https website links work fine.
My setup I have Mailjet and Mautic link tracking,

If I copy that URL from the email and open it into a new tab, it works fine and downloads the asset.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @ivan006 !
Thanks a lot for your message. Nevertheless, we have a lack of information on exact how to reproduce process. Could you please explain in detail your asset configuration, email creation, etc.

Thanks

**Comment by ivan006** [comment]
- Set up a Segment email within Mautic and include an asset link to download a file <a target="_blank" href="https://property.fortressfund.co.za/asset/40:pdfasset%22%3E 
- When you open the email in an email client within Chrome Desktop (for example Gmail in Chrome on Desktop) when you click on the link the asset doesn't download.   (Everywhere else it works perfectly fine.)

IS that enough detail?
