### ISSUE TITLE
Fatal error while creating custom field with type: select

### ISSUE THREAD

**Issue by lutek** [mautic/mautic#1016]
Mautic: 1.2.0
Debian 7.5
PHP-FPM 
PHP 5.6.14-1~dotdeb+7.1 (cli) (built: Oct  2 2015 02:42:28)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v5.0.18, Copyright (c) 2002-2015, by ionCube Ltd.
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Zend Guard Loader v3.3, Copyright (c) 1998-2014, by Zend Technologies

when you add a new field with type select, the application generated an error. The field has been not added.

```
[2015-10-15 18:16:37] mautic.ERROR: Fatal: Call to a member function getProperties() on array - in file /srv/www/mautic/xxxx/releases/20151015040424/app/bundles/LeadBundle/Form/Type/FieldType.php - at line 176 [] []
```

**Comment by alanhartless** [comment]
Hi!

See https://github.com/mautic/mautic/pull/895.
