### ISSUE TITLE
RabbitMQ: redelivery of a message with an empty payload (the page_hit queue)

### ISSUE THREAD

**Issue by WaldemarOrobanche** [mautic/mautic#10177]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
There could be a possible situation when for some reason a message with empty payload could be delivered to the page_hit queue and because of that the `mautic:queue:process` command throws the exception:

```                                                                                                                              
  [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                                             
  Type error: Argument 2 passed to Monolog\Logger::debug() must be of the type array, null given, called in /var/www/html/app/bundles/QueueBundle/Queue/QueueService.php on line 108  
```                                                                                                                                                                             
The processing of page hits will stop working because a message with an empty payload will be redelivered to the queue.

![image](https://user-images.githubusercontent.com/61522964/123448215-94217080-d5d2-11eb-90fc-8e80bb9ee31c.png)

| Q   | A
| --- | ---
| Mautic version | any
| PHP version | any
| Browser | any

### Steps to reproduce
1. Prepare RabbitMQ and Mautic;
2. Execute the `php app/console mautic:queue:process -i page_hit` command;
3. Send an empty message to the `page_hit` queue.
 
### Log errors
```
 [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                                             
  Type error: Argument 2 passed to Monolog\Logger::debug() must be of the type array, null given, called in /var/www/html/app/bundles/QueueBundle/Queue/QueueService.php on line 108
```
[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for reporting this @WaldemarOrobanche - would you be able to take a look at a fix?
