### ISSUE TITLE
Issue for adding non-code contributors

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#10191]
This is a placeholder issue for adding non-code contributors via All Contributors.

Use the command `@ all-contributors add <username> <what for> <relevant links>`

Reference for types: https://allcontributors.org/docs/en/emoji-key

**Comment by RCheesley** [comment]
@all-contributors add @tobsowo for eventOrganizing

**Comment by RCheesley** [comment]
@all-contributors add @fakela for doc, tutorial, talk

**Comment by tobsowo** [comment]
Perfect!
