### ISSUE TITLE
[Cosmetic] Google Analytics input field should be visually larger text area

### ISSUE THREAD

**Issue by pbwebdev** [mautic/mautic#102]
Depending on if you're asking for the Tracking ID or the entire GA code, the field here I believe should indicate that.

Either with help text or the size in the input field.

Suggest changing it to a textarea with height 200px if it is meant for entire GA code, and I hope that is the case for customising the GA code.

http://pbrd.co/1vLuR6m

**Comment by alanhartless** [comment]
I'm glad you reported this as I kept meaning to change this but forget. Right now the input should be your tracking ID, not then entire code snippet (the label is very misleading).  But, I want to change to actually accept the entire code snippet and change the label to not just be more generic to accept any analytics service based code.

**Comment by pbwebdev** [comment]
Code snippet would be preferable as it reduces the chance of error on the users side as well as allowing more advanced users to customise the GA output to what they need.

**Comment by natselection** [comment]
I agree with Pete. One of our users inserted the entire GA snippet because the field says Google Analytics Code which ended up breaking the site because of the excess quotes in the config file where it saves.

**Comment by dbhurley** [comment]
Great suggestions! Let's update to be textarea (I think Google often highlights/copies) the entire code snippet anyways rather than allowing you to select the ID alone.

**Comment by RCheesley** [comment]
Could you also consider if it's possible to use the GTM container instead
of just analytics?  Might well work already, I haven't tried it - but we'd
certainly want to have more than just analytics on our landing pages.
On 2 Mar 2015 21:27, "David Hurley" <notifications@github.com> wrote:

> Great suggestions! Let's update to be textarea (I think Google often
> highlights/copies) the entire code snippet anyways rather than allowing you
> to select the ID alone.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/102#issuecomment-76828747>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.
