### ISSUE TITLE
[bug] New Standalone Form: submit button will duplicate itself

### ISSUE THREAD

**Issue by ephod** [mautic/mautic#1020]
Steps for reproduction:

1. Forms > Manage Forms
2. "+ New" > "New Standalone Form" Select
3. "New Standalone Form" Select "Fields" tab
4. Hover over the "Submit" button to edit its content.
5. Popup window appears
6. Click cancel

The "Submit" button has been duplicated. If you click it again, the submit button will appear 4 times, that means that every single time this action is being called, the submit form will replicate itself.

Mautic version dated 20 October, 2015.

**Comment by escopecz** [comment]
This is known issue of 1.2.0. It will be fixed in 1.2.1. The fix is here:

https://github.com/mautic/mautic/pull/943

It "only" displays a field multiple times, but it is there physically only once. You can see that after save.
