### ISSUE TITLE
Numeric Company Names Aren't Fully Supported

### ISSUE THREAD

**Issue by garbonsai** [mautic/mautic#10210]
## Bug Description
Numeric company names don't seem to be fully supported. I can create a company—"300", for example—and it will be listed on the *Companies* page correctly. But when I try to assign a contact to it, it appears as a different number ("0") in the **Company** drop down on the contact's *Edit* page. If I search for "300" instead, it shows up, but when I click **Apply** it reverts to "0". Interestingly, it shows up as "300" under the **Companies** heading on the right (under the contact's profile picture), next to the contact's name, and in the **Company** column on the *Contacts* page.

This is really frustrating because we're using Mautic to maintain communications with roughly 10,000 organizations that we assign a unique number to (many of them have the same company name despite being completely unrelated—"Biggby Coffee", for example). We can create a custom field to store that number, except you can't search custom fields and you can't add them as a column on the *Companies* page, meaning if there are ten locations with the same name listed, I have to click each one until I find the one I'm looking for.

| Q   | A
| --- | ---
| Mautic version | 3.3.3 (installed by Softaculous)
| PHP version | 7.3.28
| Browser | Firefox Developer Edition 90.0b12 (64-bit) on macOS 10.15.7

### Steps to reproduce
1. On the *Companies* page, create a new company called (for example) "300" (minus quotes)
2. On the *Contacts* page, select a contact and click **Edit**
3. Click the **Company** field—instead of "300", it reads "0" (or "1", "2", "3", etc.)
4. Type "300" into the **Company** field and select the result (which will be "300")
5. Click **Apply**—the **Company** field will now show "0"
 
### Log errors
None.

**Comment by garbonsai** [comment]
I've also tried doing something like "Biggby Coffee (300)" for the **Company** name, but when you go to assign a contact following the steps above, searching for "300" shows both "Biggby Coffee (300)" and "No matches found 300". Clicking the former does nothing—it disappears, leaving you with "No matches found 300".

**Comment by RCheesley** [comment]
Thanks for the bug report @garbonsai :)
