### ISSUE TITLE
Progressive profiling form is not working for company fields

### ISSUE THREAD

**Issue by rodrideme** [mautic/mautic#10220]
## Bug Description
Progressive profiling forms are not working for Company fields. Even after set up on every field for that

| Q   | A
| --- | ---
| Mautic version | 3.3.3
| PHP version | 7.3.27
| Browser | Chrome

### Steps to reproduce
1. Create a form with any company field, for example, Company Name
2. Add a second field like email field in this test just to compare
3. Select yes in Autofill data on the Behaviour tab for the email field and for the company name
3. Insert this form in your Landing Page, Mautic LP, or external. Ensure you have Mautic tracking installed in case of an external LP and for this scenario with Mautic tracking right before </body>. Do not test with Mautic tracking via GTM.
4. Access this landing page in another browser session
5. Fill out the form for the first time.
6. Refresh the page and the email field will be filled (as well as all contact fields are working) but the company name won't be filled.
 
### Log errors
No errors

---
<a href="https://rysolv.com/issues/detail/167d2ae8-e0e3-4b8f-9fbe-e613fb393b0c"><img width="200px" src="https://rysolv.s3.us-east-2.amazonaws.com/FundingButton.png"></a>

**Comment by RCheesley** [comment]
Thanks for reporting the bug and for the detailed writeup @rodrideme !  Does this also happen in Mautic 4?

**Comment by rodrideme** [comment]
@RCheesley @luizeof will release a Mautic 4 installation for me in the next 7 days then I will test again

**Comment by RCheesley** [comment]
@rodrideme just following up on this, is it still an issue with Mautic 4?

**Comment by tejasync** [comment]
@RCheesley This issue is reproducible in Mautic 4 as well.

**Comment by tejasync** [comment]
Prima facie, this is the problematic code: https://github.com/mautic/mautic/blob/4.x/app/bundles/FormBundle/Model/FormModel.php#L853

**Comment by rodrideme** [comment]
@ts-navghane Thank you

**Comment by RCheesley** [comment]
As we are having some issues with Bountysource, I've added the bounty for this issue using an alternative platform, [Rysolv](https://rysolv.com/). Please let me know if you have any thoughts/comments about using Rysolv if you work on this issue!
