### ISSUE TITLE
"Create new category" from Segment doesn't work for users without full access permissions.

### ISSUE THREAD

**Issue by fbugalla** [mautic/mautic#10234]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

"Create new category" from Segment doesn't work for users without full access permissions.

![descarga (1)](https://user-images.githubusercontent.com/10847923/124589916-cf396480-de5a-11eb-8833-1643997d92a5.png)

| Q   | A
| --- | ---
| Mautic version |  3.3.1 / 3.3.3
| PHP version | 7.3
| Browser | Chrome - Firefox

### Steps to reproduce
1. Create new role with enough permission to create segments and categories.
2. Create new user and assign it to the created role.
3. Create new segment and from drop down Category select "Create New Category"
4. Dialog opens incomplete with Loading... message and nothing happens. 

 
### Log errors
mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Permission class not found for segment in permissions classes" at /var/www/html/############/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php line 504 {"exception":"[object] (InvalidArgumentException(code: 0): Permission class not found for segment in permissions classes at /var/www/html/############app/bundles/CoreBundle/Security/Permissions/CorePermissions.php:504)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for making the bug report @fbugalla :)
