### ISSUE TITLE
CKE Editor is loaded "outside" the container

### ISSUE THREAD

**Issue by adiux** [mautic/mautic#10246]
## Bug Description
When I drop a new Dynamic Content Block on the grapesjs canvas the CKEditor is loaded bigger than the popup:
![image](https://user-images.githubusercontent.com/13075514/125170451-70078700-e1af-11eb-96de-c2d3af897746.png)

Maybe this is only a problem with the PR https://github.com/mautic/mautic/pull/10114

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Maybe: Load PR https://github.com/mautic/mautic/pull/10114
2. edit a new email
3. add dynamic content block in grapesjs

**Comment by dennisameling** [comment]
Can confirm this issue only exists in PR #10114. In the `features` branch, Froala is loaded only. However, in the `features` branch the dynamic content is not saved, but I think a different issue was already created for that 👍🏼 

By the way, what you're seeing here is CKEditor's "fly-over" (not sure what the actual name is). It floats above the actual modal. When using the "regular" CKEditor it just adapts to the width of the modal.

![image](https://user-images.githubusercontent.com/17739158/126624788-32dcdd2c-2c02-4540-a6dd-6bdadd158b1b.png)
