### ISSUE TITLE
Merging Anonymous users with users created by API

### ISSUE THREAD

**Issue by bdipaolo** [mautic/mautic#10253]
## Bug Description
I am creating contacts through Zapier whenever a new contact is created in another software.  My issue is that when this new contact is created it doesn't merge with an anonymous user.  I am tracking website and page visits so I know that it would have captured the IP.  I have added an email with a form to fill for double opt in thinking that it would then recognize and sync the IP's but it doesn't seem to do that either.  

How do I get this to sync?  It is important to capture that activity.

| Q   | A
| --- | ---
| Mautic version | 3
| PHP version | PHP Version 7.3.29
| Browser | Safari, Chrome

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by bdipaolo** [comment]
I tried that
