### ISSUE TITLE
Points given by timing ignores timing

### ISSUE THREAD

**Issue by jos0405** [mautic/mautic#10262]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
1. Add a new points rule, where you would give points only if the person comes back after 1 hour.
![image](https://user-images.githubusercontent.com/4246909/125750076-73d56b74-ed20-4d0a-a614-f4fe9cd919fc.png)

2. Visit the page (diff browser obviously)
![image](https://user-images.githubusercontent.com/4246909/125750241-78af547b-25ce-406e-b601-604ef11ac8d5.png)

The points are given right away.
Comment: my cron runs every minute, not sure if it's a contributor to the problem.
Checked if server time / app time difference can be a problem, but  I also tried with 2 days interval, same thing.

| Q   | A
| --- | ---
| Mautic version | 3.3.3. / 3.3.2
| PHP version | 7.3
| Browser | Chrome (not relevant)

### Steps to reproduce
1. Create a rule, where you give points after 1h visit (action must be repeateble)
2. visit page in less then 1h
3. points will be given
 
### Log errors
No errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for the bug report @jos0405 !
