### ISSUE TITLE
Landing Page Hits from Segment Email are not added in Contact History

### ISSUE THREAD

**Issue by eVolpeConsultingGroup** [mautic/mautic#10267]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.3.3
| PHP version | 7.3.24
| Browser | Chrome 91.0.4472.124

### Steps to reproduce
1. Create Segment (default values and settings | Published: Yes)
2. Create Landing Page (default values and settings | Published: Yes)
3. Create Segment Email (default values and settings | Published: Yes)
3.1. Contact segment: Segment (from point 1.)
3.2. Builder: in Customize Slot od Text box choose Insert Link:
- URL: [Page URL] of Landing Page (from point 2.)
- Text: [whatever you want]
- Open in new tab: [checked]
4. Create Contact with real email address
5. Add Contact (from point 4.) to Segment (from point 1.)
6. In Segment Email (from point 3.) choose Send action and confirm pending contacts email to send, in few minutes email was received
7. Open email message (on another IP address) and click link (inserted in point 3.2.)
- link construction: `<Mautic_URL>/r/<redirect_id from entry in page_redirects table>?ct=<serialized and base64 encoded email data>&`
Serialized and base64 encoded email data:
```
[
  'source' => 
  [
    'email',
    [ID of Segment Email],
  ],
  'email' => [ID of Segment Email[,
  'stat' => [tracking_hash from entry in email_stats table],
  'lead' => [ID of Contact],
  'channel' => 
  [
    'email' => [ID of Segment Email],
  ],
)
```
8. Check Contact (from point 4.) History
8.1. **BUG: There is no entry about Page Hit**

### Log errors
There no errors in Mautic logs and PHP logs.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for the detailed report @eVolpeConsultingGroup - are you able to look into this in more detail and maybe make a PR to address it?
