### ISSUE TITLE
User level Email Settings

### ISSUE THREAD

**Issue by pradeepnarayan888** [mautic/mautic#10274]
Hi,

I am trying to create 2 users who can use their own Mail Send Settings.

One user should send from smtp server 1 and 2nd user should send from smtp server 2.

Is this possible?

Thanks

**Comment by RCheesley** [comment]
Hi there, this is not possible in Mautic, furthermore please post questions on https://forum.mautic.org/c/support rather than Github, which is for reporting bugs or contributing code to Mautic. Thanks!
