### ISSUE TITLE
Data slot toolbar is inserted in email html when duplicating buttons

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#10288]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The HTML code that defines the BUTTON slot manipulation(moving, cloning, delete), this one:
![image](https://user-images.githubusercontent.com/31473337/126746704-7daf7312-5441-4591-9bec-8b6472a771ca.png)
Is being included in final HTML of email and it causes issues. It happens for me when I created custom button code in template and I duplicated that button later in editor. This issue does not always happen.

| Q   | A
| --- | ---
| Mautic version | v3.2.4
| PHP version | Docker, base image php:7.3-apache
| Browser | Chrome

### Steps to reproduce

 - Add template with following custom button section:
```
<tr>
    <td data-slot-container="1">
        <div data-slot="button" data-param-padding-top="0" data-param-padding-bottom="0" data-param-link-text="Any text"
             data-param-float="1" data-param-background-color="#11d939" data-param-color="ffffff"
             data-param-href="https://google.com/"
             style='padding-top: 56px; padding-bottom: 25px; text-align: center; font-family: HelveticaNeue, Helvetica, Arial, sans-serif; font-size: 16px;'>
            <a class="button" style='color:#fff; border: solid #11d939; border-width: 16px 39px; border-radius: 4px; background-color:#11d939; text-decoration:none;' href="https://google.com/" target="_blank">
                Any text
            </a>
        </div>
    </td>
</tr>
```
 - Duplicate the button when editing
 - Check email in preview, everything is OK
 - Edit email and enable code mode. Do not save the email. If the bug is triggered, you will find this in your code:
```
<div data-slot-toolbar="true" style="top: -24px;"><span style="color:#fff;margin-left:10px;font-family:sans-serif;font-size:smaller">BUTTON</span><a data-slot-action="delete" alt="delete" class="btn btn-delete btn-default"><i class="fa fa-lg fa-times"></i></a><a data-slot-action="clone" alt="clone" class="btn btn-clone"><i class="fa fa-lg fa-copy"></i></a></div>
```
 - If you can't find that code, refresh, edit email again but do not enable code mode, duplicate the button again and save. and repeat step above.
 - Remember, do not save the email, you can preview it again and it will look OK again.
 - Now send email
 - Check sent email in your inbox, the button will contain weird "BUTTON" text(I censored main text of button):
![image](https://user-images.githubusercontent.com/31473337/126745997-deaf807b-14ed-4dd5-b113-5e88329c7424.png)

It doesn't happen every time but few times should be enough to trigger this bug.
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by ghost** [comment]
I checked default templates and I found that the bug can also be reproduced in Skyline template.

![image](https://user-images.githubusercontent.com/31473337/126748237-6c77123c-44e2-4868-aa6e-3f8bee71cafb.png)

**Comment by npracht** [comment]
You base HTML in the template is not formatted as a standard button of builder.
See:
```html
<div data-slot-container="1" style="min-height: 30px" class="ui-sortable">
<div data-slot="button">                                    
<a href="#" class="button" target="_blank" style="display:inline-block;text-decoration:none;border-color:#4e5d9d;border-width: 10px 20px;border-style:solid; text-decoration: none; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; background-color: #4e5d9d; display: inline-block;font-size: 16px; color: #ffffff; ">
    I want this!
</a>
<div style="clear:both"></div>
</div>
</div>
```

Are you able to reproduce the behaviour with this HTML for button which is the default button code for builder ?

**Comment by ghost** [comment]
I changed first `div` to `td` in the code you sent
I was able to see bad HTML in editor it after 7 tries.
![image](https://user-images.githubusercontent.com/31473337/126754407-50f043ca-c669-4286-9536-dcb0815fc954.png)


This is screenshot or part of mail source(different mail but with the same buttons:

![image](https://user-images.githubusercontent.com/31473337/126753508-310b5307-2bc7-42a0-b063-8a6c29e0cc26.png)

The difference I see is that this "BUTTON" text in email in inbox is not visible with that button you sent, the bad code is still in email however. I was duplicating and then moving button to other part of template to reproduce this.

In my template I moved `class="button"` to `<a href>` tag as you show but after few mails I was still able to reproduce that bug and the 'BUTTON' text still appears in my inbox, I don't know why.

I will paste the original button code(without changing div to tr) and I will post results soon.

**Comment by ghost** [comment]
I know everything now. I am able to reproduce it every time with every code now. I was looking in wrong direction.

The bug has a different source of it. The bug is a result of saving email when data slot toolbar frame is visible in builder. Normally  that toolbar displays when mouse is hovered over element and disappears when mouse is not hovering over it anymore. If you press on button to edit it, the toolbar disappears properly but if you press at the empty place next the button(place need to be a part of data slot) then the toolbar will not disappear when you move mouse away(until you hover over different data slot).

If you save email in this state then the toolbar code will be included in email. It can appear in any element, not only buttons. In text however that code is invisible in email, it creates a empty gap between data slots. The only reason I saw this happening it only because in my case the "BUTTON" text was somehow included on button.
