### ISSUE TITLE
Implement a Rich Text Editor for grapesJS

### ISSUE THREAD

**Issue by adiux** [mautic/mautic#10289]
The refactoring PR (https://github.com/mautic/mautic/pull/10114) removed the legacy Froala editor. Currently, only the default RTE editor from Grapesjs is available. 

Once the refactoring is done, and all other UI bugs are fixed, we can then add CKE (or any other RTE). 

Related issue:
https://github.com/mautic/mautic/issues/10004

**Comment by adiux** [comment]
I believe we should implement the RTE only in the Mautic Grapesjs plugin. So that there is room for different RTEs to be used in different plugins. 

Like this, we don't have the CKE dependency in the preset as well. And Mautic is already loading it.

**Comment by RCheesley** [comment]
For those not familiar with acronyms:
RTE: Rich Text Editor

I agree that it should be possible if someone wanted to, to use a different editor in the GrapesJS builder. I would like if we shipped with CK Editor as standard given that we are using it across the rest of the product.

**Comment by dennisameling** [comment]
For info: you should be able to run `Mautic.ConvertFieldToCkeditor(textarea, {});` (we leveraged that in https://github.com/mautic/grapesjs-preset-mautic/pull/17/files as well) to convert a field into CKEditor. Not sure how it was implemented in the past in the GrapesJS builder.

Unrelated to this issue, but for the future it might be better if we rework that function into something like `Mautic.Editors.Ckeditor.ConvertField(textarea, {})` and `Mautic.Editors.Default.ConvertField(textarea, {})`, to really make those editors more swappable, and allow users to set a default editor they want to use in Mautic.

**Comment by adiux** [comment]
I just implemented RTE (again), and we still have the same problems as I had last time. Eg. editing the text on a button in MJML mode.
![image](https://user-images.githubusercontent.com/13075514/130320819-b36c8aad-7417-4b36-bc5e-deafd7ee4334.png)

Looking into it

**Comment by adiux** [comment]
this fixes the issue to edit buttons: https://github.com/artf/grapesjs/issues/1338

**Comment by adiux** [comment]
fixes https://github.com/mautic/mautic/issues/10004
