### ISSUE TITLE
Can create a new contact with existing e-mail address -  despite being identified as already existing

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#10282]
## Bug Description
Email address is the very unique identifier (by standard) for Mautic contacts.
However - if you try to (quick) add a contact again with the same email address, a quick error message appears with the hint that it already exists. But Mautic nevertheless creates a new contact.

| Q   | A
| --- | ---
| Mautic version |  4.0.1
| PHP version |  7.4
| Browser |  any

### Steps to reproduce
1. create a contact with EMAIL
2. create another contact with the same EMAIL
3. you will see an error message flashing, but will have two contacts with the same email address

**Comment by Corsnec** [comment]
Same here. I can dublicate existing email address by creating a new contact. Looks like its not a true unique key.

**Comment by LeonOltmanns** [comment]
Tested it in M3 v3.3.3 & M4 v4.0.0-rc. Both times I could successfully create a contact having the same Email-Adress as another contact.

**Comment by RCheesley** [comment]
Thanks for the testing folks and for reporting the issue!  I think I actually noticed-but-didnt-notice this when I was working on some of the Cypress test suites!

**Comment by dsp76** [comment]
Still the case with 4.0.1

**Comment by mollux** [comment]
still valid

**Comment by biozshock** [comment]
@RCheesley Can you please confirm that creating contacts must always validate email address for unique?
