### ISSUE TITLE
The Last Active date does not match the last time the contact visited the website (not related to email opens)

### ISSUE THREAD

**Issue by adiux** [mautic/mautic#10285]
## Bug Description
The contacts "date last active" is: 2021-07-08 04:03:48
According to the event history, the contact was visiting the website on June 10, 2021 12:53 pm.

See screenshot
<img width="1121" alt="Screen Shot 2021-07-22 at 11 04 40 AM" src="https://user-images.githubusercontent.com/13075514/126615669-8bf2aa19-e383-4cd2-862f-e6c1376f4ec6.png">

the audit log shows the same as the history (and no entry for manually changing the date)
![image](https://user-images.githubusercontent.com/13075514/126615924-93a349eb-1f53-4e98-b1a3-e15cd227503b.png)

The recorded page hit came from an email. And the URL it the email was wrong - it led to a www to non-www redirect.

My hypothesis is that the email click is not changing the last-active date.

| Q   | A
| --- | ---
| Mautic version | v3.3.3 (was the same on v3.3.0)
| PHP version | 7.4
| Browser | Chrome

### Steps to reproduce
1. Create an email with a link to a non existing URL
2. Send the email
3. Click on the email
4. (email click tracking has to happen, so the Mautic instance has to be online)
5. Go back and compate the last active date and the history entry of the page hit. They should not match.

**Comment by RCheesley** [comment]
Thanks for flagging it up - does this also happen in Mautic 4 do you happen to know?

**Comment by adiux** [comment]
I dont know

**Comment by adiux** [comment]
I did just see it again on 3.3.3. I did update the description.

**Comment by JyFu-py** [comment]
same problem on mautic 4.0.1

![image](https://user-images.githubusercontent.com/67822884/143065740-83c46e41-3ebd-4835-87a6-02fbaaec6981.png)
