### ISSUE TITLE
Gated video can be continued in IOS after the time defined in `data-gate-time`

### ISSUE THREAD

**Issue by ematsakov** [mautic/mautic#10286]
## Bug Description
User can continue watching gated video after it stopped after time setup in `data-gate-time` attribute.

| Q   | A
| --- | ---
| Mautic version | v3.3.2 
| PHP version | PHP 7.4.21
| Browser | IOS Safari / IOS Chrome

### Steps to reproduce
1. Add gated video to site's page.
2. Open page in IOS and start playing video. When video stops ( defined via `data-gate-time` attribute ), you can click play again and continue playing the video.

Example of the page: https://www.ecoparent.ca/test-video-4

Is this something that can be fixed? Or this is simply IOS restrictions?

**Comment by RCheesley** [comment]
Thanks for reporting it @ematsakov - actually I think we have not got this as a feature yet for the new builder (gated video) so I will label this as the legacy builder.

We have not got any resources available to look into this really as all of our energy is directed to the new builder - if you need someone to look into it you may need to use the bounty system.
