### ISSUE TITLE
mautic:campaigns:trigger cronjob very slow after migrating to new server and new mautic version

### ISSUE THREAD

**Issue by lsergei** [mautic/mautic#10294]
Running into very weird issue and looking for community help.

We have pretty heavily used mautic 2.16.1 running on PHP 7.2 and MariaDB 10.5. Few campaigns a day totalling few hundred thousands customers. Dedicated servers for database and code. All works fine.

Since we are running out of disk space we migrated mautic to a new, significantly faster server w/SSD and much more memory. Right after moving code/DB we upgraded mautic to latest v3.

And noticed significant decrease in speed of the job creating emails (mautic:campaigns:trigger). Roughly on old server it processes batch with 100 contacts for less than a second, while on a new server it takes around 40-50+ seconds to process the same 100-customer batch!

What we did:
- expecting bottleneck in PHP updated to latest 7.4 (it was 7.3 before) - no changes
- expecting bottleneck in database we did some config tweaks - no changes. Routine DB operations are running MUCH faster than on the old server so DB is performing allegedly fine.
- numerous tricks to narrow down the problem weren't successful.

References
Old server: PHP 7.2 + MariaDB 10.5, Mautic 2.16. (32Gb RAM, HDD disks)
New server: PHP 7.4 + MariaDB 10.5, Mautic 3.3.3. (128Gb RAM, NV-e SSD disks)

Would appreciate any idea where to look at. Almost got desperate while looking for a possible reason.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
