### ISSUE TITLE
Visited URL Date on segment filter does not respect the filter Visited URL

### ISSUE THREAD

**Issue by rodrideme** [mautic/mautic#10290]
## Bug Description
![Edit Segment - d](https://user-images.githubusercontent.com/3418370/126797596-b5a0e7bd-020e-4747-ae01-fa7a6d86b62e.png)
The scenario to filter contacts who Visited a URL combined with a filter in a specific date (Visited URL Date) or a range does not work. When these filters (Visited a URL and Visited URL Date) are used independently work fine. 
| Q   | A
| --- | ---
| Mautic version | 3.3.3
| PHP version | 7.3.27
| Browser | Chrome

### Steps to reproduce
1. You have to install Mautic tracking on your website in order to test this scenario;
2. Create a segment like the image above, adding VISITED URL and VISITED URL DATE filters;
3. Check whether the segment pulls the right contacts or not;
4. During the test is important to verify the date that the contact has visited the URL. Because the VISITED URL DATE filter works, regardless of the URL and the VISITED URL filter works fine too, but when these filters are combined doesn't work.
 
### Log errors
No errors

**Comment by RCheesley** [comment]
Thanks for reporting the issue @rodrideme - can you test this with Mautic 4 and let us know if it persists please? Thank you!
