### ISSUE TITLE
SenderName with commas leading to illegal address error - Email Sending

### ISSUE THREAD

**Issue by pedroegg** [mautic/mautic#10304]
## Bug Description

| Q   | A
| --- | ---
| Mautic version | 3.3.3
| PHP version | 7.3.27
| Browser | Any

When the sender name of an email have comma, all the emails that should be sent will fail with the illegal address error, this is due to a bug or treatment inside the amazon SES service. The comma maybe be like a field separator inside the amazon code, i don't know. 

I found the same issue here: https://sendy.co/forum/discussion/1201/commas-in-from-name/p1

This link contains also a solution for this problem. I already tested it using my emailing library that uses Amazon SES too, and it worked like a charm! We should just enclose the senderName with double quotes always, even if we do an mime word encode with base64. The double quotes doesn't appear at the email that we receive, works fine.

## Solution:

Example of the solution with yours [code](https://github.com/mautic/mautic/blob/3.3.3/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonApiTransport.php#L341) in `AmazonApiTransport.php`:
```php
$sesArray['FromEmailAddress'] = (!empty($fromName)) ? '"'.mb_encode_mimeheader($fromName).'" <'.$fromEmail.'>' : $fromEmail;
```

To test it: http://sandbox.onlinephpfunctions.com/code/d3b8ec8fbf0a48a41d5b302b1c0507d81390e7f0

### Steps to reproduce

1. Create a new campaign/segment email with the sender name field like this: "Test, test from Brazil" (sender name with comma)
2. The other fields could be anything. Does not matter the sender mail too.
3. Trigger this email sending to any recipient
 
### Log errors

`[2021-07-17 23:18:05] mautic.ERROR: SES API Error: Illegal address [] []`

This error is also from the `InvalidParameterValue` category of amazon SES

**Comment by RCheesley** [comment]
Thanks for raising this issue @pedroegg and for the PR to address it!

**Comment by pedroegg** [comment]
New pull request on the correct branch.
