### ISSUE TITLE
HubSpot contacts pull error

### ISSUE THREAD

**Issue by iBobik** [mautic/mautic#10309]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
On HunSpot one-time contacts pull there are strange warnings. Contects seems pulled correctly, just some does not have last_active filled. 

| Q   | A
| --- | ---
| Mautic version | 4.0.0-rc
| PHP version | 7.4

### Steps to reproduce
1. Configure HubSpot
2. Run`bin/console mautic:integration:fetchleads --integration=Hubspot --fetch-all`
 
### Log errors
There are a lot of this messages:
> Warning: preg_match() expects parameter 2 to be string, array given in /var/www/html/app/bundles/PluginBundle/EventListener/IntegrationSubscriber.php on line 90
>
> Warning: preg_match() expects parameter 2 to be string, array given in /var/www/html/app/bundles/PluginBundle/EventListener/IntegrationSubscriber.php on line 93

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

/data/logs/mautic/mautic_prod-2021-07-31.php 
> [2021-07-31 19:50:42] mautic.WARNING: An exception occurred while executing 'UPDATE leads SET gender = ?, salutation = ?, last_active = ? WHERE id = ?' with params ["m", "Ond\u0159eji", "1615222537682", "4607"]:  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1615222537682' for column `mautic`.`leads`.`last_active` at row 1 [] []
> [2021-07-31 19:50:42] mautic.WARNING: An exception occurred while executing 'UPDATE leads SET gender = ?, salutation = ?, contact_type = ?, last_active = ? WHERE id = ?' with params ["m", "Martine", "Traveller", "1620991065554", "4"]:  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1620991065554' for column `mautic`.`leads`.`last_active` at row 1 [] []
> [2021-07-31 19:50:42] mautic.WARNING: An exception occurred while executing 'UPDATE leads SET gender = ?, salutation = ?, contact_type = ?, last_active = ? WHERE id = ?' with params ["fm", "Honzo", "Fogg Base Member|Traveller", "1626347340413", "25"]:  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1626347340413' for column `mautic`.`leads`.`last_active` at row 1 [] []
> [2021-07-31 19:50:42] mautic.WARNING: An exception occurred while executing 'UPDATE leads SET gender = ?, salutation = ?, contact_type = ?, last_active = ?, facebook = ? WHERE id = ?' with params ["m", "Vito", "Traveller|Leader|Friend", "1607936400000", "https:\/\/www.facebook.com\/profile.php?id=100013754923717", "43"]:  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1607936400000' for column `mautic`.`leads`.`last_active` at row 1 [] []
> [2021-07-31 19:50:42] mautic.WARNING: An exception occurred while executing 'UPDATE leads SET gender = ?, salutation = ?, last_active = ? WHERE id = ?' with params ["m", "Petere", "1627726860646", "44"]:  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1627726860646' for column `mautic`.`leads`.`last_active` at row 1 [] []
> [2021-07-31 19:50:42] mautic.WARNING: An exception occurred while executing 'UPDATE leads SET gender = ?, salutation = ?, contact_type = ?, last_active = ? WHERE id = ?' with params ["m", "Martine", "Evangelist", "1618218964919", "46"]:  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1618218964919' for column `mautic`.`leads`.`last_active` at row 1 [] []
> [2021-07-31 19:50:42] mautic.WARNING: An exception occurred while executing 'UPDATE leads SET last_active = ? WHERE id = ?' with params ["1604361548930", "51"]:  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1604361548930' for column `mautic`.`leads`.`last_active` at row 1 [] []

**Comment by RCheesley** [comment]
Thanks for reporting the issue @iBobik - assume this is something new with Mautic 4 or have you also got this happening in 3.3.3?

**Comment by iBobik** [comment]
It has been cleanly installed on latest v4.0.0-beta.

**Comment by RCheesley** [comment]
Thanks for the clarification, can you double check against the Release Candidate just to ensure that it's still a problem, then we can look to see if we can get this fixed. Thanks!

**Comment by iBobik** [comment]
Yes, I have configured it after upgrade to RC.

Honza Pobořil

**Comment by ilonavarro** [comment]
The problem continues in the official version 4.0.0.

**Comment by ramosrafh** [comment]
Hello everyone! Also using the v4.0.0-rc and having this exact same problem.

**Comment by Mostafa-Rawash** [comment]
Hi there i have same issu with facebook/linkedin plugins

**Comment by lucky-naty** [comment]
Had the same issue with vTiger integration. I've replaced "getHeaders()" with "headers" in strings 90, 93 in 
/var/www/html/app/bundles/PluginBundle/EventListener/IntegrationSubscriber.php
And it's working now. 
I am not a developer, and I know absolutely nothing about the code, this may not be a very reliable way to solve the problem)))

**Comment by TestCLEI** [comment]
The problem continues in the official version 4.0.1.
