### ISSUE TITLE
'--batch-limit option does not exist' suddenly appears in logs

### ISSUE THREAD

**Issue by jayasurya-jeyakodi** [mautic/mautic#10314]
Mautic was sending emails fine. Suddenly it stopped working and then i checked logs to find out the following error

mautic.NOTICE: Symfony\Component\Console\Exception\RuntimeException: The "--batch-limit" option does not exist. (uncaught exception) at /opt/bitnami/mautic/vendor/symfony/console/Input/ArgvInput.php line 223 while running console command `mautic:webhooks:process` [] []

mautic.WARNING: Command `mautic:webhooks:process` exited with status code 1 [] [].

Same for all other mautic commands like mautic:emails:send, campaign:trigger etc.

I don't see this option removed for mautic:emails:send command. Any ideas why its showing error?

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
