### ISSUE TITLE
Dashboard problem

### ISSUE THREAD

**Issue by roblefko** [mautic/mautic#10315]
I updated the page that the user is directed to when the user goes to the mautic root by modifying Configuration | System Settings | Mautic's root URL. I then clicked the X to remove the data in that field, and it was updated to say Mautic Dashboard. I"m now finding that when I log in, I'm brought to a page that just shows text: 
{"activeLink":"#mautic_dashboard_index","mauticContent":"dashboard","route":"\/s\/dashboard","...
I can provide the full contents of the page if that would help, but I assume that this may be enough.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
