### ISSUE TITLE
Color Picker Replacement

### ISSUE THREAD

**Issue by SaraBrewerDesigner** [mautic/mautic#10313]
I ran into a small yet important issue when I tried to use the email builder in mautic. The color picker is extremely limited. I believe this would be worthwhile to replace with one that allows me to enter an rgb value or cmyk value. If I could save colors I used in the past that would also be very useful in establishing uniform branding.

**Comment by kuzmany** [comment]
Mautic 4 use GrapesJs builder, where are different color picker capabilities. Have you already look on it?

![image](https://user-images.githubusercontent.com/462477/128219936-90115ee2-79f8-45fe-96ae-9be9eaee0729.png)

**Comment by RCheesley** [comment]
Closing this issue as it seems to relate to the legacy builder - if that is not the case then please request to re-open and provide a more detailed explanation including Mautic version being used. Thanks!
