### ISSUE TITLE
New Anonymous IP's not displaying in "Live Mode"

### ISSUE THREAD

**Issue by rquatier** [mautic/mautic#10318]
When viewing anonymous IP's of visitors in the Live Mode, the new IP's are blank. In the past they displayed and were highlighted in yellow. The workaround is to refresh the browser page.
However, if you have hundreds of new IPs, locating where you left off can be difficult. Fortunately, I only have a few to look through.

I am using anonymous IP's to identify the companies visiting our website. I have a way to find decision makers within that organization from that point.

Because we only market to U.S. companies, we have a firewall that blocks all IP's other than the U.S. This removes IP's I'd waste my time with otherwise.

DETAILS:
Mautic Version 3.3.3
PHP Version 7.4.19
Browser: Numerous ( Brave, Google & Edge)

Prior to reporting this, I reached out to Jackie Liu from Autoize who confirmed the same issue.

![Image 1 - Blank IP address in Live Mode](https://user-images.githubusercontent.com/11085614/128550327-545f1d76-6004-4d31-8145-f07c9a8dffd1.png)
![Image 2 - Blank IP address in Live Mode](https://user-images.githubusercontent.com/11085614/128550334-4a7f3887-3ca5-4a13-ae90-ee591f5719ff.png)

Thank you,
Richard
(425) 367-9025

**Comment by rquatier** [comment]
Forgot to attach the error log.
[mautic-live-mode-error-log.txt](https://github.com/mautic/mautic/files/6947181/mautic-live-mode-error-log.txt)

**Comment by RCheesley** [comment]
Thanks for reporting the issue @rquatier and for the detailed write up!
