### ISSUE TITLE
UTM tags added incorrect when link have another query string

### ISSUE THREAD

**Issue by brainmangv** [mautic/mautic#10310]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When a link address in email already have a query string, starting with interrogation characher, the utm_source is prepend incorrectly with %3F, instead of the & character.

| Q   | A
| --- | ---
| Mautic version | 3.3.3 
| PHP version | 7.3.27
| Browser | Microsoft Edge V. 92.0.902.55

### Steps to reproduce
1. Create an email with a link address with a query string like this: https://mysite.com?mauwoo_utype=guest
2. In the UTM Tags for Google Analytics Fill the fields with source=mautic, medium =email_mkt, campaign=abandoned_cart_live, content=cart
3. After send the email, the link address in the email will be the incorrect: https://mysite.com?mauwoo_utype=guest%3Futm_source%3Dmautic&utm_medium=email_mkt&utm_campaign=abandoned_cart_live&utm_content=cart

### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for reporting the issue @brainmangv and for the detailed instructions to reproduce the problem!
