### ISSUE TITLE
The API route contacts/batch/edit create duplicates with same email adress

### ISSUE THREAD

**Issue by Ajtak** [mautic/mautic#10327]
Problem is same to #7290, in version 3.3.3 still not solved.

### Steps to reproduce

1. Create a request to create a contact on route PUT 
`http://<url>/api/contacts/batch/edit`

Body request:
```
[
    {	
        "firstname": "Zkouska 3",
        "lastname": "Testname2",
        "email": "test2@test.dk"
    }
]
```

2. Relaunch it.
2. Result : Two identical contacts are created.

**Comment by RCheesley** [comment]
Hey there,

Thanks for reporting this bug. I think that maybe it is related to https://github.com/mautic/mautic/issues/10282.

I did some testing and without specifying an ID I was able to reproduce the issue you mentioned, as soon as I specified the ID as well as the contact info it behaved as expected.

Uploading the screencast here: https://youtu.be/hd-YO8sYniI
