### ISSUE TITLE
Wrong Message-ID. Not correspond to the sending domain

### ISSUE THREAD

**Issue by a1exe1** [mautic/mautic#10337]
## Bug Description
The more details the better...

### Steps to reproduce
1. install mautic on domain1.com
2. use smtp server on domain2.com
 
I have had the Message-ID:  ID@domain1.com but I need ID@domain2.com

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
