### ISSUE TITLE
Cloning an MJML email changes it to HTML

### ISSUE THREAD

**Issue by martin-neumann-gurus** [mautic/mautic#10339]
Your software
My Mautic version is: 3.3.2
My PHP version is: 7.4.21

My problem is:
I am trying to clone an email that was is based on an MJML template. When I clone the email, it reverts to a HTML email. I think a cloned email should be still editable in MJML. That would be the expected behavior.

**Comment by RCheesley** [comment]
Thanks for reporting this, are you able to check if this also is happening with Mautic 4 Release Candidate (in a development area)?

**Comment by RCheesley** [comment]
Hi there,

Tested in the features branch and this issue has indeed been resolved. You will need to update to Mautic 4 when it is released to get the fix.

Thanks for reporting it!
