### ISSUE TITLE
Gated Video block is missing from landing pages on GrapesJS builder TPROD-176

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#10334]
## Bug Description
In the legacy builder it is possible to drop a video onto the landing page, and have it set up as a gated video. The feature is missing in the GrapesJS builder.

Documentation on this feature can be found here: https://docs.mautic.org/en/gated-video

![screenshot-mautic4 ddev site-2021 08 13-15_57_45](https://user-images.githubusercontent.com/2930593/129377320-5cedbefb-a5c0-41e3-ae57-87b6b80b92a2.png)

These are the configuration options, when the video hits the time specified, it should stop playing and a Mautic form show which requires the user to enter their information in order to proceed with watching the video.

**Comment by RCheesley** [comment]
From the Product Team issue https://mautic.atlassian.net/browse/TPROD-176

> Gated video is a feature in the legacy builder that was dependent on Froala. If that is to survive to Mautic 4 without being dependent on the legacy builder, we’ll have to write either a GrapesJS implementation or maybe a plugin for the chosen WYSIWYG (i.e. ckeditor). https://github.com/mautic/mautic/pull/2081/files#diff-f8faf825478dd2b43ebb989eceb2c38d65c9997a733268c2f723a6859d03a551

**Comment by RCheesley** [comment]
https://github.com/artf/grapesjs/blob/dev/src/dom_components/model/ComponentVideo.js there is a video component in GrapesJS so maybe we can extend that for our purposes.

**Comment by npracht** [comment]
Still an issue
