### ISSUE TITLE
Dashboard Login Problem

### ISSUE THREAD

**Issue by roblefko** [mautic/mautic#10330]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When I log in to Mautic, I am directed to the dashboard, https://mautic.myorg.org/s/dashboard. Usually, this works without issue. However, sometimes I am presented with a screen that displays the text shown in the attached file.
[mautic.txt](https://github.com/mautic/mautic/files/6978544/mautic.txt)

The authentication was successful, because I'm able to change my browser URL to https://mautic.myorg.org/s/contacts to proceed. From that point on, I'm able to click on the dashboard link, and it shows successfully.

| Q   | A
| --- | ---
| Mautic version | 3.3.3
| PHP version | 7.3.28
| Browser | Chrome and Edge

### Steps to reproduce
1. log in to Mautic.
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, I think this is most likely going to be a server setup issue, please make a post on https://forum.mautic.org/c/support where the community can help with troubleshooting.
