### ISSUE TITLE
Suddenly, today I could't check contact info.

### ISSUE THREAD

**Issue by fintechee** [mautic/mautic#10346]
### Mautic Version

3.3.3

### PHP version

7.4

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

A bug happened!
I have used Mautic for 3 months.
Amazing platform! really amazing, full-featured and FOSS. Unbelievable!!
But ...... Suddenly, today I found the contact info couldn't be viewed.(I didn't modify anything since yesterday)

https://mydomain/s/contacts/view/xxxxx?_=1629474917045&mauticUserLastActive=2408&mauticLastNotificationId=
Not working.

Status500
Internal Server Error
VersionHTTP/1.0
Transferred230 B (0 B size)
Referrer Policystrict-origin-when-cross-origin

But not able to reproduce everywhere.
If we click the link from the forms list, it works.
If we click the link from the contacts list, it doesn't work,
If we go from the browser address bar, it doesn't work as well.
If we cancel editing the contact info, it doesn't work(we expected the page moves to the contact info page, but the edit page didn't change)

Please help me solve this weird issue.
Many thanks!!

### How can we reproduce this issue?

I don't know whether this issue can be reproduced for everyone.

### Relevant log output

```shell
My log has had problems since the first day I got started with Mautic.
Always not working fine.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by fintechee** [comment]
BTW, I wanted to post a question in your forum, but didn't find a button.
So I post the issue here.

And, I'm a little bit urgent, I plan to use 4.0rc with the existing DB.
Is the DB layout of 4.0rc different from 3.3.3's?

We appreciate any advice. Many thanks.

**Comment by RCheesley** [comment]
Hey there,

Please read the text in the big blue box at the top of the page on the forum. You have to be active for 3 minutes and read 3 posts to be able to post or reply.

Please post there, rather than here. That is where we provide community support. 

Thanks!
