### ISSUE TITLE
mautic install uses multi-schema change, not compatible w/ tidb

### ISSUE THREAD

**Issue by donbowman** [mautic/mautic#10342]
### Mautic Version

4.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

i would like to install mautic using tidb, which is generally mysql compatible. Its a simpler db to use in a kubernetes environment, I use it w/ wordpress.

Mautic needs manual intervention in the install from scratch, the ALTER TABLE x ADD y, ADD z; needs to be converted to ALTER table X add Y;
ALTER table X add Z;

splitting the changes.
https://github.com/pingcap/tidb/issues/14766
is the tidb issue tracking this.

### How can we reproduce this issue?

run tidb:
`tiup playground --monitor=false --db.host 127.0.0.1`

now, use 127.0.0.1 as a database, port 4000. On install, we will see an error due to this statement:

```
ALTER TABLE leads ADD fax VARCHAR(255) DEFAULT NULL, ADD preferred_locale VARCHAR(255) DEFAULT NULL, ADD attribution_date DATETIME DEFAULT NULL, ADD attribution DOUBLE PRECISION DEFAULT NULL, ADD website LONGTEXT DEFAULT NULL, ADD facebook VARCHAR(255) DEFAULT NULL, ADD foursquare VARCHAR(255) DEFAULT NULL, ADD instagram VARCHAR(255) DEFAULT NULL, ADD linkedin VARCHAR(255) DEFAULT NULL, ADD skype VARCHAR(255) DEFAULT NULL, ADD twitter VARCHAR(255) DEFAULT NULL;
ERROR 8200 (HY000): Unsupported multi schema change
```

if this is altered so that each field is individual, e.g.
```
ALTER TABLE companies ADD companynumber_of_employees DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE companies ADD companyfax VARCHAR(255) DEFAULT NULL;
ALTER TABLE companies ADD companyannual_revenue DOUBLE PRECISION DEFAULT NULL;
```

it will work.

this is during initial install 4.0.0-rc

### Relevant log output

```shell
An error occurred while attempting to add default data: An exception occurred while executing 'ALTER TABLE leads ADD fax VARCHAR(255) DEFAULT NULL, ADD preferred_locale VARCHAR(255) DEFAULT NULL, ADD attribution_date DATETIME DEFAULT NULL, ADD attribution DOUBLE PRECISION DEFAULT NULL, ADD website LONGTEXT DEFAULT NULL, ADD facebook VARCHAR(255) DEFAULT NULL, ADD foursquare VARCHAR(255) DEFAULT NULL, ADD instagram VARCHAR(255) DEFAULT NULL, ADD linkedin VARCHAR(255) DEFAULT NULL, ADD skype VARCHAR(255) DEFAULT NULL, ADD twitter VARCHAR(255) DEFAULT NULL': SQLSTATE[HY000]: General error: 8200 Unsupported multi schema change
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there!

Unfortunately we are not yet supporting PHP8, please can you re-test with 7.4 and report back if this is still an issue? Thanks!

**Comment by donbowman** [comment]
yes, same behaviour on 7.4 php

**Comment by RCheesley** [comment]
If you would like to make a PR to address the issue you have reported, here are some guidelines: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests

**Comment by donbowman** [comment]
i will look at this in a bit.

the code that does it seems auto-generated tho (the migrations), is there any guidance around that from a technical standpoint?

**Comment by RCheesley** [comment]
If you make a change to Mautic which affects the database then you would need to generate a migration, the process is documented here: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#step-6-migrations-needed

If you get stuck, do hop into Slack (https://mautic.org/slack for an invite) and join the Product Team channel. I'm sure someone will be able to point you in the right direction!

**Comment by donbowman** [comment]
will do.
its not changing the schema, its changing the generated (historical) migrations, to make this work.

**Comment by donbowman** [comment]
so i asked for some input but no response. i don't really understand the strategy here, but i am using on tidb w/o trouble, and really think its a better forward approach if mautic ever starts to get better at could native.

i'm not sure how one changes the historical migrations, which is what is needed, since they are coded to a specific version of a specific db.

**Comment by mabumusa1** [comment]
@mlahlouh please provide some input on this issue.

I think @donbowman has made some progress, it would be great if we can support him

**Comment by mlahlouh** [comment]
TiDB does not support multi schema change (ALTER TABLE with multi ADD/MODIFY/DROP/CHANGE/ALTER); should run each change in a separate ALTER statement.

I used TiDB before with no issues but with an in-house system (we care about what we used), I think for now there is no open-source application seamless support such as these systems (TiDB/Vitess, etc...).

To solve this issue, we should make the migration in a separate command, But I don't prefer this because it will make the upgrade very slow in all normal MySQLs; It will rebuild the table for each change.

**Comment by donbowman** [comment]
is there a way to `checkpoint` or at least provide `full schema`? e.g. rather than a set of alter statements from some point in time, have a current full set?

I use wordpress, mautic on tidb. its difficult in kubernetes to use non cloud native (cockroachdb, tidb) database.

**Comment by donbowman** [comment]
failing that, i guess some shell script could convert the existing alter statements to compatible ones
