### ISSUE TITLE
Forms - radio group field - can't handle same values in key / value pair

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#10340]
## Bug Description
A radio group field should be able to have same values for different selections. Think about e.g. a quiz, where there are 1 correct and two incorrect answers.

Mautic looses one of the options, that has the same value (it doesn't show it in the form). 

It still should show all values. But when saving the form field, the second option with the same value overwrites the first one.

| Q   | A
| --- | ---
| Mautic version | 3.3.2
| PHP version | any
| Browser | any

### Steps to reproduce
1. try to create a form with radiogroup, where two keys have the same value
2. save and watch it happen
![Bildschirmfoto 2021-08-16 um 17 24 53](https://user-images.githubusercontent.com/1241376/129706000-a6489951-aa52-48d0-93d3-2705d9fa47a6.png)

After saving the field, only two options get saved.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hey there,

This is by design I believe, you will need to use a different way of working if you want to achieve what you are after. Please make a post on the forums at https://forum.mautic.org/c/support and I am sure the community will be able to help you find a better way to do this.
