### ISSUE TITLE
SendGrid API does not send attachments on queue mode

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#10356]
### Mautic Version

4.0.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Send an email with attachment included, the attachment was not delivered when the queue mode is selected but it was working as expected when it was in immediate mode.

### How can we reproduce this issue?

Step 1: Select queue mode
Step 2: Select SendGrid API and configure the key
Step 3: Send an email with an attachment
Step 4: No attachment is found in the email sent

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by luizeof** [comment]
@RCheesley 

Tested on Latest Stable (3.3.4) ... if it is configured in immediate sending .. it works, if it is in queue mode it does not send the attachments.
