### ISSUE TITLE
Problems after updating from v3.1.0 to v3.2.5

### ISSUE THREAD

**Issue by patodorf1** [mautic/mautic#10359]
### Mautic Version

3.1.x series (not supported)

### PHP version

7.2.34

### What browsers are you seeing the problem on?

Chrome

### What happened?

Hi,

Can you please help me with this or give me an idea of where I can start?

After updating from _v3.1.0_ to _v3.2.5_ I tried to open some contacts and they were not working.

This is the lines that I have in the **System log**:

**[2021-08-22 20:59:53]** mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Unable to write to the "/var/www/vhosts/mail.werecruit.it/httpdocs/var/cache/prod" directory." at /var/www/vhosts/mail.werecruit.it/httpdocs/vendor/symfony/filesystem/Filesystem.php line 681 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Unable to write to the \"/var/www/vhosts/mail.werecruit.it/httpdocs/var/cache/prod\" directory. at /var/www/vhosts/mail.werecruit.it/httpdocs/vendor/symfony/filesystem/Filesystem.php:681)"} []

**[2021-08-22 20:59:53]** mautic.ERROR: Symfony\Component\Filesystem\Exception\IOException: Unable to write to the "/var/www/vhosts/mail.werecruit.it/httpdocs/var/cache/prod" directory. - in file /var/www/vhosts/mail.werecruit.it/httpdocs/vendor/symfony/filesystem/Filesystem.php - at line 681 [] []

Thank you!

### How can we reproduce this issue?

Step 1:  Update from UI to V.3.2.5
Step 2: Try to open a contact
Step 3: Have a look to the log

### Relevant log output

```shell
**[2021-08-22 20:59:53]** mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Unable to write to the "/var/www/vhosts/mail.werecruit.it/httpdocs/var/cache/prod" directory." at /var/www/vhosts/mail.werecruit.it/httpdocs/vendor/symfony/filesystem/Filesystem.php line 681 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Unable to write to the \"/var/www/vhosts/mail.werecruit.it/httpdocs/var/cache/prod\" directory. at /var/www/vhosts/mail.werecruit.it/httpdocs/vendor/symfony/filesystem/Filesystem.php:681)"} []

**[2021-08-22 20:59:53]** mautic.ERROR: Symfony\Component\Filesystem\Exception\IOException: Unable to write to the "/var/www/vhosts/mail.werecruit.it/httpdocs/var/cache/prod" directory. - in file /var/www/vhosts/mail.werecruit.it/httpdocs/vendor/symfony/filesystem/Filesystem.php - at line 681 [] []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hey there, you need to clear your cache. In the future, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
