### ISSUE TITLE
How to  enable user registration 

### ISSUE THREAD

**Issue by anushaharish538** [mautic/mautic#10377]
### Mautic Version

4.0.x series

### PHP version

7.4

### What happened?

Enable user registration and give them a subdomain

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Are you asking a multi-tenant solution for Mautic? The project doesn't focus on this feature, however plugins might be able to support it.
