### ISSUE TITLE
RabbitMQ does not work even with local config

### ISSUE THREAD

**Issue by myupchar** [mautic/mautic#10378]
### Mautic Version

3.3.3

### PHP version

7.3.28

### What browsers are you seeing the problem on?

Chrome

### What happened?

This is what we are seeing -

sudo php bin/console mautic:queue:process --env=prod -i page_hit

In Container.php line 348:

You have requested a non-existent service "old_sound_rabbit_mq.mautic_consumer".

We are on v3.3.3

Seems like it was reported earlier but marked stale and nothing happened. This is needed if we are using email queues + when users click on links in the email, they fail because of this error.

When users click on any link in the email, we get this error in log file - 
 mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "old_sound_rabbit_mq.mautic_producer"." at /var/www/html/vendor/symfony/dependency-injection/Container.php line 348 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"old_sound_rabbit_mq.mautic_producer\". at /var/www/html/vendor/symfony/dependency-injection/Container.php:348)"} []

### How can we reproduce this issue?

Step 1: Install Mautic V3.3.3
Step 2: Set up SMTP setting for email via any provider
Step 3: Enable Queue functionality
Step 4: Send any email and then click on links in any email

Or, 
sudo php bin/console mautic:queue:process --env=prod -i page_hit

### Relevant log output

```shell
mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "old_sound_rabbit_mq.mautic_producer"." at /var/www/html/vendor/symfony/dependency-injection/Container.php line 348 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"old_sound_rabbit_mq.mautic_producer\". at /var/www/html/vendor/symfony/dependency-injection/Container.php:348)"} []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please can you test this with Mautic 4?

**Comment by vicampuzano** [comment]
Yes @RCheesley , I'm using Mautic 4 and still having this error.

;)
