### ISSUE TITLE
Installing in the GUI results in a 500 error at pre-flight check stage

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#10371]
### Mautic Version

4.0.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I try to install Mautic 4.0 (current features) in the UI I am seeing a server error at the pre-flight check stage

### How can we reproduce this issue?

Step 1: Clone features branch
Step 2: Run `composer install` to install dependencies
Step 3: Try to install Mautic and notice an error at the top of the page (or a tonne of stack traces in dev mode)

### Relevant log output

```shell
[2021-08-26 18:18:24] mautic.ERROR: Doctrine\DBAL\Exception\ConnectionException: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused - in file /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php - at line 112 [] []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dennisameling** [comment]
It's caused specifically by this piece of code that I added in the GrapesJS refactor PR. It tries to get the active builder from the IntegrationsHelper, but this code apparently is loaded already before Mautic is installed:

https://github.com/mautic/mautic/blob/1090f8f84866cf873544866657f31312132e1511/app/bundles/CoreBundle/Templating/Helper/AssetsHelper.php#L463-LL475

The solution is to wrap it in a conditional that checks if Mautic is installed already. Will create a PR for that.

**Comment by RCheesley** [comment]
OK awesome, thank you for jumping on it so quickly!
