### ISSUE TITLE
import tasks not being processed

### ISSUE THREAD

**Issue by rafalsk** [mautic/mautic#10383]
### Mautic Version

4.0.x series

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

we're importing CSVs 5k rows per file. in-browser imports work fine; off-line server-side imports do not get processed. these ere enqueued and stuck at 0% forever

### How can we reproduce this issue?

Step 1: 5k rows per file
Php 7
IIS

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by rafalsk** [comment]
![image](https://user-images.githubusercontent.com/9338163/131386192-8bc7db6a-1ab5-4d12-8dd8-b7ae3c134aab.png)
Like seen above, the web-imports work fine, the ones put into the server-side processing  queue are to remains stuck forever.

**Comment by rafalsk** [comment]
also, no progress is being reported during an 'online' import.
![image](https://user-images.githubusercontent.com/9338163/131389130-caf7025f-be69-4b9f-a0b2-4cb483f9e18d.png)
it's stuck like above until it completes.

When it completes it looks like this no idea what the error means:
![image](https://user-images.githubusercontent.com/9338163/131389217-42838c75-2102-49c7-b899-ef1676438289.png)

**Comment by rafalsk** [comment]
we've ensured all the cron tasks are running on our instance of Windows Server 2019 through Task managers; they succeed. The import tasks transit into processing state but nothing happens.

**Comment by rafalsk** [comment]
We've managed to capture the error the first time the task is executed:
`Import failed. Reason: There was a database error: The EntityManager is closed.. The import was set to delayed state and will be imported later.`
![image](https://user-images.githubusercontent.com/9338163/131509585-9ddbbe63-521d-4d17-b684-e4544ed02726.png)

and yes.. the file is UTF-8 encoded.

**Comment by RCheesley** [comment]
For your online one, the error is telling you that no data was found on line 5003 - presumably because that's where the data ends :) 

> `Import failed. Reason: There was a database error: The EntityManager is closed.. The import was set to delayed state and will be imported later.`

This generally means that there has been a problem with your database connection during the import. For some reason or another, it has dropped/closed the connection.

What database (type, version) are you using? What collation do you have set up?

Are you importing the same file that you used before to import on the web UI, or a different one?

**Comment by rafalsk** [comment]
> For your online one, the error is telling you that no data was found on line 5003 - presumably because that's where the data ends :)
> 
> > `Import failed. Reason: There was a database error: The EntityManager is closed.. The import was set to delayed state and will be imported later.`
> 
> This generally means that there has been a problem with your database connection during the import. For some reason or another, it has dropped/closed the connection.
> 
It's the same thing with Mautic 4.0 Release, after cache was cleared.
![image](https://user-images.githubusercontent.com/9338163/131635258-597e2f6d-5120-4000-bd0d-6fcfcdd9d2fe.png)

> What database (type, version) are you using? What collation do you have set up?
> 
MySQL 8.0 thought Mautic liked MySQL best, we may feed it anything it wants. Not sure what you mean by collation?

> Are you importing the same file that you used before to import on the web UI, or a different one?

Distinct files, 5K entries each. It chokes right away when sees the file.

**Comment by rafalsk** [comment]
After the update to 4.0 **Release** even foreground tasks wouldn't go through.
I've just noticed that even if one sets the processing limit to '100' (default) and provides it with a file containing 5K rows it seems to be willing to process 5K entries anyway:
![image](https://user-images.githubusercontent.com/9338163/131636303-7a9cbbdd-e5de-4ab7-b264-b94127210c0e.png)
It now remains stuck indefinitely  like seen above even in foreground. The memory limits are well over 1GB RAM for PHP and time execution limits are well over 20 minutes. It's an 8core server with close to 0 utilization.

Other than that the entire UI is accessing the database just fine so..

Rechecked file permissions, tried a much smaller file, same thing
![image](https://user-images.githubusercontent.com/9338163/131637830-68c41924-7350-4cfe-b476-a17a8294d41f.png)
![image](https://user-images.githubusercontent.com/9338163/131639404-a853c898-884f-4843-90b4-5b75e9a83293.png)

yeah now it wouldn't import anything :-) Importing new bunch of data each time, the formatting encoding is UTF8(triple checked it's not UTF8 BOM etc), in release-candidate it used to work in foreground now it doesn't work at all (same configuration, same types of files).

**Comment by rafalsk** [comment]
Now we haven't got a PHP guy around, but seems like "The manager is closed" is a cover-up error code for any kind of exceptions going on under-the hood and it most likely has nothing to do with DB's connectivity. If you could advise in on how to proceed with debugging this we surely would no other errors are to be seen in logs (none for online import and but the manager closed thing during offline)


I can read in docs of Doctrine then it would throw this error.. on each exception i.e. duplicate keys etc.

**Comment by rafalsk** [comment]
We took our time enabled full-blown logging on MySQL and what Mautic attempted to achieve, like it?
[MauticMySqlLog.txt](https://github.com/mautic/mautic/files/7089927/MauticMySqlLog.txt)

**Comment by rafalsk** [comment]
seeing that most likely s*** hit the fan seriously on our end with the database we wiped it out, since still could afford it, and with a fresh install server-side data imports work fine (so far).

Not?  Seems like said it too soon...

![image](https://user-images.githubusercontent.com/9338163/131658762-595a9271-124d-44f8-9639-b7f9aaba3914.png)
after such an error consecutive tasks wouldn't even trigger since due to the below:
![image](https://user-images.githubusercontent.com/9338163/131661344-aa3a7296-7686-43e0-bbe0-a3f81c296341.png)
after unpublishing and re-publishing the import task (which seems to make the 'postponed-indefinitely' one trigger yet again) this time it fails as well but little bit eralier:
![image](https://user-images.githubusercontent.com/9338163/131661783-fbc46216-b557-4cef-8da9-42f2be56a84f.png)

**Comment by rafalsk** [comment]
here's a full log of what's going on within the database during the upload process; as you may see there's something going wrong and a rollback is issued.
[importLog.txt](https://github.com/mautic/mautic/files/7090619/importLog.txt)
Narrowed it down to a field 'based department  Bindhu gents pg behind, SAP Labs Road, opp. Gopalan International School, Shivaji Nagar  Basavanna Nagar, Whitefield, Bengaluru, Karnataka 560048  560048 Bangalore KA  India 919566018460'
Which probably it too long to be stored by the database-scheme you deploy?

**Comment by RCheesley** [comment]
That would likely be an issue. Address information should be separated into the relevant fields, seems you have an issue with the file you are importing causing this information to all be contained in one field.

Closing the issue as this relates to your imported file and not to Mautic itself.
