### ISSUE TITLE
Uploaded images not visible in Email Builder

### ISSUE THREAD

**Issue by rafalsk** [mautic/mautic#10386]
### Mautic Version

4.0.x series

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

When adding new images, the ones already uploaded and not being proposed in the pop-up box. One ends-up uploading them all over again, since once cannot select.
![Uploading image.png…]()

### How can we reproduce this issue?

Step 1: Like described above.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
@adiux this may be something relating to the movement of assets from the builder. Are you able to give any feedback here?

**Comment by adiux** [comment]
@rafalsk can you please upload the printscreen again? I dont see it
