### ISSUE TITLE
mautic:unusedip:delete not working in Mautic 4.0.0

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#10387]
### Mautic Version

4.0.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Calling mautic:unusedip:delete command ends with error
```
./bin/console mautic:unusedip:delete

In UnusedIpDeleteCommand.php line 55:
                                                                                                                      
  Attempted to call an undefined method named "getEntityManager" of class "Doctrine\Bundle\DoctrineBundle\Registry".  
                                                                                                                      

mautic:unusedip:delete [-l|--limit [LIMIT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

The reason for this is doctrine/doctrine-bundle package.
Mautic 3.3.3 uses
```
            "name": "doctrine/doctrine-bundle",
            "version": "1.12.13",
```
This version had `getEntityManager` method
https://github.com/doctrine/DoctrineBundle/blob/1.2.x/Registry.php

Mautic 4.0.0 uses
```
            "name": "doctrine/doctrine-bundle",
            "version": "2.4.2",
```
This version does not have that method:
https://github.com/doctrine/DoctrineBundle/blob/2.4.x/Registry.php

### How can we reproduce this issue?

Step 1: Run Mautic 4.0.0
Step 2: Run command `./bin/console mautic:unusedip:delete`

### Relevant log output

```shell
./bin/console mautic:unusedip:delete

In UnusedIpDeleteCommand.php line 55:
                                                                                                                      
  Attempted to call an undefined method named "getEntityManager" of class "Doctrine\Bundle\DoctrineBundle\Registry".  
                                                                                                                      

mautic:unusedip:delete [-l|--limit [LIMIT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the issue @TPapajCin - there's a PR to address it in #10536 so hopefully this will be addressed in the next release.
