### ISSUE TITLE
Adding filters to Segments has no effect

### ISSUE THREAD

**Issue by rafalsk** [mautic/mautic#10384]
### Mautic Version

4.0.x series

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

Few thousands of contacts; each with an email fields set and reported. Contacts do not assigned to any group. Now after creating a Group with a single filter matching Contacts with the email fields as NOT empty. The result? 0 contacts get matched.

### How can we reproduce this issue?

Step 1: Few thousands of contacts; each with an email fields set and reported. Contacts do not assigned to any group. Now after creating a Group with a single filter matching Contacts with the email fields as NOT empty. The result? 0 contacts get matched.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hey there,

Did you run the segment rebuild cron job? What was the output from the cron job?

Please provide a screenshot of the segment filter than you have configured so that we can better understand the nature of the issue.

**Comment by rafalsk** [comment]
Cheesley, after we've set-up crone tasks on windows the right way the segments are updated without an issue. Closing now.
