### ISSUE TITLE
Duplicating an email gives me a blank email

### ISSUE THREAD

**Issue by cuberoot** [mautic/mautic#1039]
I duplicated an email I had filled with content, which uses a custom template, and the duplicate has no content at all.

I am using Mautic 1.2.

**Comment by ptcc** [comment]
me too :+1:

**Comment by alanhartless** [comment]
I tried to reproduce this by:

1. Creating an email that uses a theme and filled in content
2. Cloned email
3. Viewed builder and the content is there
4. Save and re-open and content is still there

Also tried the same using just the custom HTML (no theme) and the content was also present in the cloned/duplicated email.  

Am I doing something different?

Given I'm using the latest dev snapshot so it's possible it has been fixed although I don't remember a PR addressing this.  We're working on wrapping up the 1.2.1 release.  If this is still an issue with it, we'll work on getting it fixed for 1.2.2 as we've cut off new PRs for 1.2.1.

**Comment by escopecz** [comment]
I also tested the email clone feature 3 times and the email content was always available in the cloned email.

**Comment by ptcc** [comment]
This happens when I use a custom template With My own placeholder fields.
Em 22/10/2015 17:43, "John Linhart" <notifications@github.com> escreveu:

**Comment by escopecz** [comment]
Well, that could be it, but it's hard to fix if we don't have that custom theme.

**Comment by cuberoot** [comment]
You guys can grab my custom theme here: http://mautic.journeytohealingandjoy.com/themes/journey.tar.gz

After I sent out the email, I was able to go back and duplicate it and the content did come through.

**Comment by escopecz** [comment]
Try to add this condition to your theme:

https://github.com/mautic/mautic/blob/staging/themes/Mauve/html/base.html.php#L14

Does the email template work for you in various email clients? You don't have inline styles, you have them in `<style/>` tag. It won't be issue for Mautic though.

Also, your email template is missing this line:
https://github.com/mautic/mautic/blob/staging/themes/Mauve/html/email.html.php#L13

Try to have these statements on the same places as the official themes do to avoid troubles like this.
