### ISSUE TITLE
Very slow query when opening an email.

### ISSUE THREAD

**Issue by jstawski** [mautic/mautic#10394]
### Mautic Version

4.0.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

With an instance of Mautic with 1.9 million leads, 5.3 million lead_lists_leads, and 7.5 million email_stats the **emails/view/{id}** screen takes forever to load, if it even loads. We identified the problematic method to be [getEmailPendingQuery](https://github.com/mautic/mautic/blob/0abd6b79738f7cf096b435d8f87ea998617e17c1/app/bundles/EmailBundle/Entity/EmailRepository.php#L162) . The query takes over 50 seconds to execute in our current system without any load. We were able to bring the query execution time down by using **IN**, instead of **EXISTS** as it performs better on both MySQL and MariaDB, but it is still not good enough.

### How can we reproduce this issue?

Step 1: Load your database with leads, lead_lists_leads, and email_stats
Step 2: Create an email and send it
Step 3: Navigate to the email details and see how long it takes to open

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hey there,

Please take a look at the discussions over on https://github.com/mautic/mautic/pull/9406 :)
