### ISSUE TITLE
No way to unselect the brash tool

### ISSUE THREAD

**Issue by rafalsk** [mautic/mautic#10397]
### Mautic Version

4.0.0

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

![image](https://user-images.githubusercontent.com/9338163/131669106-6c0a376c-dbfd-4d10-a842-34711e430ea9.png)

### How can we reproduce this issue?

Step 1: once selected no way to escape it.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, the way the Brush tool works is, you need to click on the blocks.
1. You either build blocks
2. Or you customize blocks with the Brush.

![image](https://user-images.githubusercontent.com/4246909/132093058-364da801-e53e-4a23-8e1b-ecc5811491d0.png)
