### ISSUE TITLE
Missing check for sql execute return false

### ISSUE THREAD

**Issue by donbowman** [mautic/mautic#10393]
### Mautic Version

4.0.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

In app/bundles/LeadBundle/Entity/CustomFieldRepositoryTrait.php, we can see fetch() called, no check for 'false', and then assumes the result is an array, causing a later throw() error.

This can happen if a lead is deleted.

```
    public function getFieldValues($id, $byGroup = true, $object = 'lead')
    {
        //use DBAL to get entity fields
        $q = $this->getEntitiesDbalQueryBuilder();

        if (is_array($id)) {
            $this->buildSelectClause($q, $id);
            $id = $id['id'];
        } else {
            $q->select($this->getTableAlias().'.*');
        }

        $q->where($this->getTableAlias().'.id = '.(int) $id);
        $values = $q->execute()->fetch();

        return $this->formatFieldValues($values, $byGroup, $object);
    }
```

### How can we reproduce this issue?

its obvious from code inspection above. but, delete a lead that had custom fields, and then you will start seeing errors.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for raising this @donbowman, could you take a look at addressing this in a PR?

Also thanks for the info about how to reproduce - quite often the folks who are testing to reproduce an issue will not be developers but users of Mautic, so don't assume that a code snippet will necessarily allow folks to know how to reproduce the issue - the more help you can give the quicker we can get it tested and addressed! :)

**Comment by donbowman** [comment]
i will get around to the PR.
