### ISSUE TITLE
[BUG] Configuration Save, Apply & Close Buttons Jump Around

### ISSUE THREAD

**Issue by pbwebdev** [mautic/mautic#104]
The save, apply and close buttons jump around from top of the screen to the bottom of the screen depending on where they previously were.

http://pbrd.co/1vLwtgr
http://pbrd.co/1vLwwsA
http://pbrd.co/1vLwCQY

I'm getting use to it now but its a lot of scrolling and guessing.

**Comment by dbhurley** [comment]
Yeah they aren't supposed to move. Nice bug find :+1:

**Comment by alanhartless** [comment]
Hey Peter! This and maybe a couple of your other reported issues seem to be related to JavaScript errors. Can you check your browsers console to see what they might be? Did you by chance just upgrade to rc from beta? If so, try clearing browsers cache and see if these type issues are still present. 

Thanks!
Alan

**Comment by pbwebdev** [comment]
Looked further into it and compared local with our hosted.

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

/s/config/edit?mauticUserLastActive=1&mauticLastNotificationId=64 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Works on local and not on our hosted.

Assuming server issue now that I have to debug.

**Comment by alanhartless** [comment]
Just to verify, by hosted are you referring to your own website or mautic.com?

Thanks!
Alan

**Comment by pbwebdev** [comment]
Self hosted I should say. I think I should have written that after posting.

Can confirm its our server creating issues with this:
POST /s/ajax?mauticUserLastActive=1&mauticLastNotificationId=65 500 (Internal Server Error) in reference to #103 

Checking logs to see if that will shed any light on server config.

**Comment by alanhartless** [comment]
Try looking in app/logs/mautic_prod.php to see if anything is recorded there.

Thanks!
Alan

**Comment by alanhartless** [comment]
Hey Peter,

Just checking to see if this was resolved or if it is still an open issue?

Thanks!
Alan

**Comment by pbwebdev** [comment]
All good.

It was me, not you
