### ISSUE TITLE
E-mails targeting segment not enqueued ?

### ISSUE THREAD

**Issue by rafalsk** [mautic/mautic#10400]
### Mautic Version

4.0.0

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

![image](https://user-images.githubusercontent.com/9338163/131755532-6fef1c31-d343-4b9c-beb6-c938f4dce7c8.png)

as seen above the system 'knows' it should be sending another few thousand messages.
I suppose this is to be accomplished through one of the Crone Jobs.
On my system this never happens.

Is there anything I'm doing wrong?
Below are the crone tasks:
`php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:email:fetch
php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:social:monitoring
php C:\inetpub\wwwroot\project.org\mautic\bin\console  mautic:broadcasts:send
php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:segments:update --env=prod
php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:campaigns:update --env=prod
php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:campaigns:trigger --env=prod
php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:messages:send
php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:emails:send --env=prod
php C:\inetpub\wwwroot\project.org\mautic\bin\console swiftmailer:spool:send --message-limit=40000 --env=prod
php C:\inetpub\wwwroot\project.org\mautic\bin\console mautic:import

`if I trigger this mnually from UI these by send button then it works. Nope.. actually I can see this stopped working all of the sudden as well. It gets stuck at 0 even in UI. There's heavy CPU usage from php.exe so maybe the UI is just not being updated.. will get back on this one.

### How can we reproduce this issue?

Step 1: as above

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by rafalsk** [comment]
Now that's bad :-( 
![image](https://user-images.githubusercontent.com/9338163/131792909-32d4b1eb-7e08-4da1-b047-e2d03de201b2.png)
I see in the morning that supposedly no e-mails were dispatched... and I even do not know thus where thus the high CPU usage of a task spawned specifically to a user operating only your app (the very instance of dedicated php.exe) came from :-(

What's worst of it all is that as you may infer fromt the screenshot it worked for a couple of thousands few hours earlier and there are no error messages in logs :-(*. We've removed any kind of limitations in regards to your app so it could reserve like 10GB of memory had it wanted..

By the way.. the error we've faced on Release Candidate when triggering php  mautic:messages:send seems to be gone so no idea if the direct " swiftmailer:spool:send" thing is still needed.

Anyway we're stuck here now seriously. The very same Cron jobs seemed to work fine with the Release Candidate I believe. (the BAT file remained the same)... 

In Release.. we had trouble with sending through Cron tasks right after installation but it worked from UI with the progress bar going from 2 to around 25K just fine with messages being delivered.

Now we wanted to send anoter batch.

so we 
1) uploaded few more CSV files with ~~5K contacts each. having now in mind the limitations of length fields all went fine now for each import
2) noticed that the UI reports all these pending e-mail dispatched we know from the first time that Cron jobs wouldn't have worked so we triggered Send button next to the email.. but no luck this time... the progress bar remained at 0 the entire night

If you want some SQL logs etc let me know the thing is I'm not seeing any errors. I think you are somehow reading return codes from SQL executions and deciding to rollback on your own since there are no errors in MySQL... just the command's log getting filled in.

**Comment by rafalsk** [comment]
Ok folks listen up... after reading the documentation thoroughly I came over a line saying that a publish data needs to be set for broadcast e-mails to be making it into the queue. 
All right, got it.

**Point Taken.**

**It's within the docs.**

Once set, I can see the e-mails being dispatched through the Cron Job (BAT file in my case).

**Still,** I strongly advise for the publish data to be set automatically ONCE the user toggles the published switch (make it turned off by default) the fact that end-user sees the email as supposedly PUBLISHED and yet **NOT PUBLISHED** (from every practical point of view) is at least confusing. 

Let alone for the fact that it used to dispatch e-mails ANYWAY through the Send command through AJAX without the date-set (still need to test publishing through Ajax as it stopped working for me).

**Comment by rafalsk** [comment]
Now what's worrying me is that as seen below, the emails::send command seems to be going through the sending process all over again?
![image](https://user-images.githubusercontent.com/9338163/131803618-44c2db6f-1c85-45f1-9274-41c59f05bcb7.png)

it's been stuck for long long.. I'm worried it's spamming users all over again with the very same message?

oh my...  just checked the mail server... it's going through the 20K+ recipients all over again.. now that's sick:D

There are no other campaigns.. just a single broadcast email and a single group.. why on earth is it going through all of them once again?:D

By the way; where's the 'marketing e-mail' switch in 4..0? I underline there was no campaign just a single broadcast group and a single (broadcast YES) e-mail defined.

**Comment by RCheesley** [comment]
Hi there, please can you post questions like this on the forums first, before you come here to raise an issue? The forums are where we provide community support and assist with troubleshooting.

Having a message limit of 40000 seems very excessive so I am not surprised your server is struggling. Setting it thus you are saying to process 40000 at a time, as [referenced in the documentation](https://docs.mautic.org/en/setup/cron-jobs#command-parameters).

I will close this issue as it seems you have addressed the issue and the rest seems to be a configuration issue, which should be discussed in the forums, not on GitHub.

**Comment by rafalsk** [comment]
> Hi there, please can you post questions like this on the forums first, before you come here to raise an issue? The forums are where we provide community support and assist with troubleshooting.
> 
> Having a message limit of 40000 seems very excessive so I am not surprised your server is struggling. Setting it thus you are saying to process 40000 at a time, as [referenced in the documentation](https://docs.mautic.org/en/setup/cron-jobs#command-parameters).
> 
> I will close this issue as it seems you have addressed the issue and the rest seems to be a configuration issue, which should be discussed in the forums, not on GitHub.

Ruth, you as the Project Lead, know best that we're no longer in early 70s. And processing of 40 000 of whatever it might be is anything but a large number of elements (we're talking simple input output + database queries, which here is the case). I strongly advise against throwing problems under the napkin :-)
