### ISSUE TITLE
Minimal MySQL version for Mautic 4 is not documented

### ISSUE THREAD

**Issue by ttencate** [mautic/mautic#10414]
### Mautic Version

4.0.0

### PHP version

n/a

### What happened?

On https://github.com/mautic/mautic/blob/0abd6b79738f7cf096b435d8f87ea998617e17c1/UPGRADE-4.0.md it says:

> Minimal MySQL version was increased from x to x

I think some version numbers should be put in the place of the x's :)

### How can we reproduce this issue?

n/a

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Fixed in #10570 if you could review @ttencate :)

Thanks for bringing it to our attention!
