### ISSUE TITLE
Feature Request | "Wait Until" conditions for sending emails

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#1041]
It would be excellent if Mautic was able to send emails based on additional options. 

Ideally:
Wait until X day of the week
Send on every X day of the week
Send on every X weekday of the month (eg: First Monday of the month).

**Comment by alanhartless** [comment]
I think this can be merged with #539 as part of the request for relative timeframes for campaign actions.

**Comment by chasebros** [comment]
+1 for this feature! It would be awesome!
