### ISSUE TITLE
Contactimport fails for the contact if an apostrophe (') is in the Email

### ISSUE THREAD

**Issue by LeonOltmanns** [mautic/mautic#10411]
### Mautic Version

4.0.0

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Chrome

### What happened?

While importing a larger batch of contacts by .CSV i noticed, that I get an error whenever the contact has an apostrophe in the email. For example: "test.o'neil@australia.com.au". The email-field does not seem to allow apostrophes if you import contacts.

On the other hand if you create a contact manually, there seems to be no Issues having an apostrophe in the email itself.

### How can we reproduce this issue?

Step 1: Create a CSV with atleast an email-field.
Step 2: Set the email to have an apostrophe in it. (test.o'neil@australia.com) if you want to copy&paste.
Step 3: Import the CSV
Step 4: You should get an error 

### Relevant log output

```shell
No error has been logged
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the bug @oltmanns-leuchtfeuer - are you able to make a PR to address this?

**Comment by LeonOltmanns** [comment]
@RCheesley Made a PR that should fix this issue. :)
