### ISSUE TITLE
A 404 error occurred when creating a contact

### ISSUE THREAD

**Issue by 000black000** [mautic/mautic#10424]
### Mautic Version

4.0.0

### PHP version

7.4.20

### What browsers are you seeing the problem on?

Chrome

### What happened?

create contact the following error occurred: 

The response has unexpected status code (404).

Response: {"errors":[{"message":"No route found for "POST \/api\/contacts\/new"","code":404,"type":null}]}

### How can we reproduce this issue?

Step 1: POST \/api\/contacts\/new

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there,

Please ensure that you clear the Mautic cache after you have enabled the API. Most folks with this error have not cleared the cache.

In the future, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
