### ISSUE TITLE
Links in tokens are not converted to trackables

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#1042]
Steps to reproduce

1. Create an email with a link like `http://domain.com?test={leadfield=firstname}`
2. Send the email through a campaign or lead list
3. View the email and the link will be raw and not converted into a trackable

There seems to be an issue with searching/replacing dynamically generated URLs with trackables.

This also affects unsubscribe_text tokens and any token really that has a link.

**Comment by ciprianMihalache** [comment]
also if I use the editor and click the link icon

it will transform 

http://domain.com?test={leadfield=firstname}&test2=3

into  

http://domain.com?test=%7Beadfield=firstname%7D&amp;test2=3 (view source of editor)

When I am sending the mail this way the final link is 
http://domain.com?test=corectleadfield&amp;test2=3 (the &amp; is not transformed into &)

So my $_GET explode is

[test] => corectleadfield
[amp;test2] => 3

**Comment by ramezrafla** [comment]
Seems to me you should be using JSON for the value of field 'test'.
