### ISSUE TITLE
MAUTIC - REPORT Error, emails missing from Report

### ISSUE THREAD

**Issue by Dylan-86** [mautic/mautic#10420]
### Mautic Version

4.0.0

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

BUG in "Reports".

We have several tens of emails: some of them are sent by "_Campaigns_", some others are "_Segment_" emails that are sent weekly to specific segments (newsletters). 

I created a "Report" under Reports.

Settings:
Data Source: emails-emails
Data selected: not relevant for the bug, you can select any field.
Show opened by default: YES (not relevant)

Save and close. Check the data.

If I select the timeframe "1st July 2021 - 31st July 2021" I can see ALL the emails, exactly as I expect to see. So, I can see both the "_campaign_" and the "_segment_" emails. Fine. I can check the correct data.

**BUT**, if I select a different timeframe, for example "1st August 2021 - 31 August 2021" (or anything else, the first week of September too) **ONLY** the "_segment_" emails are shown. The "_campaign_" emails are not there. For no reason. I know FOR SURE that those emails have been sent. In addition, if I go and check the single email's data under "_Channels_ - _Emails_" and select one of the emails that is not shown in the report, I can clearly see that it has been sent in that timeframe. And some users reply to those emails, so, again, I know that those emails have been sent.
However, they do not come up in the Report.

I can reproduce this infinitely. Except for the month of July, where everything appears correct. 

Image 1: REPORT with all the emails - July
![image](https://user-images.githubusercontent.com/58813956/132958222-2758dd98-5fd9-4cd2-8882-191a158c954b.png)

Image 2: REPORT without the emails - August
![image](https://user-images.githubusercontent.com/58813956/132958256-b3c8a698-306b-4305-8cfd-ba07131af0ea.png)

Image 3: One of the emails that do not show up in the report, showing that it had been sent.
![image](https://user-images.githubusercontent.com/58813956/132958066-c15a9034-77e0-41c4-b18a-1179c7886e38.png)

### How can we reproduce this issue?

Step 1: Create emails that are used by Campaigns and emails that are "Segment based".
Step 2: after a while, create reports and check if they show the right data, in different time frames.

### Relevant log output

```shell
Nothing useful inside the Log.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by Dylan-86** [comment]
no one?

**Comment by RCheesley** [comment]
@Dylan-86 thanks for reporting this issue with the reports, and for the detailed writeup - this will be really helpful for someone working on reproducing and 🤞  fixing this issue.

Apologies for the delay in triaging, we're pretty short-handed at the moment.

**Comment by Dylan-86** [comment]
> @Dylan-86 thanks for reporting this issue with the reports, and for the detailed writeup - this will be really helpful for someone working on reproducing and crossed_fingers fixing this issue.
> 
> Apologies for the delay in triaging, we're pretty short-handed at the moment.

I've "solved" on the 5th of October by cloning the emails and updating the campaigns with the new emails.
Suddenly, not only the new emails showed up in the reports, but also the "original" emails that were previously missing were there in the report. 

However, the data is somehow wrong for the "old" emails: those emails were sent between September and October but the report shows them as all sent exactly on the 5th of October.

**Comment by Dylan-86** [comment]
@RCheesley 
Update: The report is again EMPTY.
I have thousands of emails going out every day but it seems that they do not fall into the report.
If I select the timeframe 1nov-9nov there's no single email in the report. However, really, thousands of emails go out every day from my Mautic.

**Comment by Dylan-86** [comment]
Update again.

Still empty. No email show up in the report for the past month even though MILLIONS of emails have been sent by Mautic.

Can someone please help here?

**Comment by Dylan-86** [comment]
Update:
I confirm that it's still broken.
The reports show just SOME emails ID but 90% of them are missing.


This report should show all the weekly newsletter that we send. Indeed, one newsletter per week. It shows instead ONLY the newsletter sent on the week of the 15th of November
![image](https://user-images.githubusercontent.com/58813956/145985708-3985e94c-0f4d-4bbb-9229-fdf2f519fa08.png)

**Comment by Dylan-86** [comment]
The issue is still open and still present in the latest version of Mautic.

It is pretty important but it seems that no one cares. It happens when you have several contacts (more than 150k) and you send regular emails, it seems to be a problem with the numbers..
