### ISSUE TITLE
Order Number of a mautic form fields is not being respected in the API call

### ISSUE THREAD

**Issue by abdul-Tz-prog** [mautic/mautic#10436]
### Mautic Version

3.3.x series

### PHP version

7.4.16

### What happened?

If I change the order number of the mautic form field in an API call, it does not changes the order of the field.

`"fields": [
            {
                "label": "expTest",
                "showLabel": true,
                "alias": "expTest",
                "type": "freetext",
                "defaultValue": null,
                "isRequired": false,
                "validationMessage": null,
                "helpMessage": null,
                "order": 3,
                "properties": {
                    "text": "la bla bla bla"
                },
                "validation": [],
                "labelAttributes": null,
                "inputAttributes": null,
                "containerAttributes": null,
                "leadField": null,
                "saveResult": true,
                "isAutoFill": false
            }
]`

As it can be seen in the above JSON code, Just want to edit the **order** of a Field, but it is not working.
Is there any solution for this or this can be considered as an improvement or bug in API ?

### How can we reproduce this issue?

- Step 1:  Get form by id using GET as:  _https://{{anymauticinstance}}/api/forms/{{ID}}_ in Postman

- Step 2: Edit form by id using PATCH as: https://{anymauticinstance}}/api/forms/{{ID}}/edit in postman

- Step3: Paste the JSON response of **Step1** into the body of **Step2** and reverse the **order** (in fields array). e.g: If it is 1,2,3,... then do it like 3,2,1.

But it will not change the order of fields.

### Relevant log output

```shell
Response of PATCH request doesn't changes the order number of fields.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
Interesting - also when you add a new form field via Mautic Backend, some fields will be added last before submit. But e.g. a description field will always appear at place 2 in the form.

I guess, we should be able to define the order of a form via API as intended. This is a bug.

**Comment by RCheesley** [comment]
Hi folks,

As 3.x is now in security support only, could you check to see if this is still the case with Mautic 4 and let us know in a reply? Many thanks!

**Comment by abdul-Tz-prog** [comment]
This is still not resolved. But I will check it again in mautic 4.1.2
