### ISSUE TITLE
CKEditor (or other filter) removes &nbsp;

### ISSUE THREAD

**Issue by ramezrafla** [mautic/mautic#1044]
Many templates use ```&nbsp;``` to force email clients to show empty spaces / divs. Right now CKEditor removes those making some templates look garbled. Is there a way to keep them?

**Comment by ramezrafla** [comment]
Work around for now is to replace ```&nbsp;``` with ```&#8203```. Looking into code to see if we can make a permanent change or a temp swap like in #847

**Comment by alanhartless** [comment]
Is this happening just with slots in themes or also with custom HTML? Is it when there is only an empty div with something like `<div>&nbsp;</div>`?

**Comment by ramezrafla** [comment]
Hey @alanhartless , thanks for the response
It only happens with divs that contains nbsp (and whitespaces) .. i.e. if no real text is present.

I don't know what you mean by 'slots' in themes. We paste in fully operational HTML from email editors.

**Comment by ramezrafla** [comment]
Should I close this issue so not to clutter the list of issues?
