### ISSUE TITLE
SQL Syntax error when dispatching broadcast e-mails

### ISSUE THREAD

**Issue by rafalsk** [mautic/mautic#10449]
### Mautic Version

4.0.0

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?
All of the sudden....

![image](https://user-images.githubusercontent.com/9338163/133755549-75f00ed8-e1a4-4933-b3f8-07ec2f8aee2e.png)

Doesn't look good does it...haven't investigated this further yet.

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by rafalsk** [comment]
(..) seems to be due to some kind of MySQL limitations. After imposing a limit through the --limit parameter and sending out in bunches of 20k messages the error is gone. Any idea which MySQL settings are at play here?

**Comment by kuzmany** [comment]
You should use limit parameter to send by command. For example: 


`mautic:broadcasts:send --limit=10000`

**Comment by rafalsk** [comment]
@kuzmany I like to find solutions instead of artificial limits. That is why I uphold the questions about which particular parameters of MySQL/PHP are at play so that these could be tweaked (..) so that 40K (..) 400+K or even more could be send at once should the memory limits allow.

**Comment by kuzmany** [comment]
The error is with query during the send large email.  Query can exceed the limit of max characters what you have on your mysql config. You can increase it or use --limit parameter, or hire dev to rewrite this part of software.

**Comment by RCheesley** [comment]
Closing this issue based on the conversation above as this is a configuration issue and the solution has been explained. If you wish to hire someone to help you with performance optimisation of Mautic, please make a post in https://forum.mautic.org/c/commercial.

**Comment by mabumusa1** [comment]
Reopening this issue, this is the exact log

```
Error thrown while running command "mautic:broadcasts:send". Message: "An exception occurred while executing 'SELECT ch.lead_id, fr.frequency_number, fr.frequency_time FROM email_stats ch INNER JOIN lead_frequencyrules fr ON ch.lead_id = fr.lead_id WHERE (fr.channel = :channel) AND (fr.frequency_time IS NOT NULL AND fr.frequency_number IS NOT NULL) AND ((ch.date_sent >= case fr.frequency_time                  when 'MONTH' then DATE_SUB(NOW(),INTERVAL 1 MONTH)                  when 'DAY' then DATE_SUB(NOW(),INTERVAL 1 DAY)                  when 'WEEK' then DATE_SUB(NOW(),INTERVAL 1 WEEK)                 end))AND (ch.lead_id IN (

```

We need to tweak the process, @mlahlouh for your input

**Comment by RCheesley** [comment]
Thanks for re-opening with the details @mabumusa1 @mlahlouh - something we can fix with a PR?
