### ISSUE TITLE
Landing Page Doesn't Save Unless You Visit Builder First

### ISSUE THREAD

**Issue by J-Wick4** [mautic/mautic#10441]
### Mautic Version

4.0.0

### PHP version

7.4.23

### What browsers are you seeing the problem on?

Chrome

### What happened?

Saving a new landing page without going to Builder first, locks the page and action buttons.

If Builder is a requirement prior to saving the landing page, then the save buttons should be greyed out until Builder is visited so it's clear to the user. 

### How can we reproduce this issue?

1. Go to Landing Pages in Components
2. Click "NEW" 
3. Select "Blank" template
4. Provide a name for the title.
5. Click "Save" or "Save & Close"

Repeat the steps again, but before clicking "Save & Close" go to the Builder first, then go back to Save, which is successful now. 

### Relevant log output

```shell
Nothing in the Mautic logs.

Chrome Console Reports

POST https://newsletter.MyDomain.net/s/pages/new?mauticUserLastActive=1559&mauticLastNotificationId= 403
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there,

Thanks for reporting the issue, can you confirm if you are using the new builder, on the legacy builder?

**Comment by LeonOltmanns** [comment]
Just tested this on v4.0.0 but was unable to reproduce. Even if I don't visit the builder, the Landing Page still gets saved.

**Comment by RCheesley** [comment]
@oltmanns-leuchtfeuer were you testing on the GrapesJS builder? I was not clear from the post which builder @SpyderZ is referring to!

**Comment by LeonOltmanns** [comment]
@RCheesley Just tested on both GrapesJs aswell as legacy builder. Both worked for me.

**Comment by J-Wick4** [comment]
Hellow, on further digging, it looks like a problem with Cloudflare. I'll go over there and find out the exact reason and report back the resolution in case others encounter this problem.

`<!DOCTYPE html>



 <html class="no-js" lang="en-US"> 
<head>
<title>Attention Required! | Cloudflare</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />

<style type="text/css">body{margin:0;padding:0}</style>



<script>
  if (!navigator.cookieEnabled) {
    window.addEventListener('DOMContentLoaded', function () {
      var cookieEl = document.getElementById('cookie-alert');
      cookieEl.style.display = 'block';
    })
  }
</script>



</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1 data-translate="block_headline">Sorry, you have been blocked</h1>
        <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> domain.net</h2>
      </div>

      <div class="cf-section cf-highlight">
        <div class="cf-wrapper">
          <div class="cf-screenshot-container cf-screenshot-full">
            
              <span class="cf-no-screenshot error"></span>
            
          </div>
        </div>
      </div>

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>

            <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
          </div>

          <div class="cf-column">
            <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>

            <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
          </div>
        </div>
      </div>

      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">690546c36a7a0899</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Your IP</span>: 10.10.10.10</span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
</div>


    </div>
  </div>

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>

</body>
</html>`

**Comment by J-Wick4** [comment]
Okay, I've done a deep dive into this and there is something in Mautic that is triggering Cloudflare WAF rules when saving a new landing page before going into the Builder. 

I'm running standard default WAF rules, this shouldn't be happening. **I have a feeling it's cookie-related as the console error is requesting cookies be turned on.** Cloudflare is seeing this as an XSS / Script attack.

![CF OWASP Block Report](https://user-images.githubusercontent.com/1954540/133861571-2d78f4af-67cc-43f8-9b5a-9f023e583b71.png)
![Chrome Console Error](https://user-images.githubusercontent.com/1954540/133861576-bd06a084-32a6-44ba-b8ed-e14468bfef61.png)

**Comment by J-Wick4** [comment]
Here's the reply from specialists over at Cloudflare.

> Usually this operation involves uploading a bunch of HTML codes with the <script> tag, and this is why most probably the request will trigger OWASP ruleset.

I had to create this WAF firewall rule to achieve proper Mautic functionality. 

![7a822bff7031f02446769ac2a615dbbb5d13db37_2_690x300](https://user-images.githubusercontent.com/1954540/133906992-b431bace-3945-47b2-81e4-11a7dd6c6241.png)

Considering the wide adoption of Cloudflare, it would be advantageous to figuring out a fix to prevent this situation from occurring.

**Comment by npracht** [comment]
I cannot reproduce this behaviour on 4.0.1. When i save without opening the builder it works and i even have a working page based on the template HTML.
