### ISSUE TITLE
Argument 1 passed to Swift_Transport-AbstractTransport::send() must be an instance of Swift_Mime_SimpleMessage (..)

### ISSUE THREAD

**Issue by rafalsk** [mautic/mautic#10451]
### Mautic Version

4.0.0

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

We began to face the following error when processing console swiftmailer:spool:send --message-limit:40000 -env=prod

![image](https://user-images.githubusercontent.com/9338163/133924284-c4dfa1ea-4c25-4420-b29a-b9011ef2455a.png)

Ideas?

### How can we reproduce this issue?

Like above.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by rafalsk** [comment]
(..) that seems to happen with sort of lengthy e-mails. Which yet again seems to boil down to limits. Ideas? It would be sort of a pity be limiting send-outs to 4k of  relatively short e-mail messages per task on 32GB RAM servers

**Comment by kuzmany** [comment]
You should use to send emails `php /path/to/mautic/bin/console mautic:emails:send`

**Comment by RCheesley** [comment]
Closing this issue due per the guidance above.

**Comment by rafalsk** [comment]
> Closing this issue due per the guidance above.

(..) closing due to a guidance. (..) Management of this project seems ridiculous. Just if it was of concern to you, Ruth, the problem is exactly the same when invoking through "php /path/to/mautic/bin/console mautic:emails:send" you probably know better than me that it's just a wrapper for the previous function.
