### ISSUE TITLE
Tracking issue: multi-clicks and/or multi-downloads occur at the same time

### ISSUE THREAD

**Issue by alexandramrx** [mautic/mautic#10461]
### Mautic Version

3.3.x series

### PHP version

7.3.20

### What browsers are you seeing the problem on?

Chrome

### What happened?

Whenever an email is sent, the tracking is abnormal: the number of clicks on the mail and/or the number of downloads (if there is an asset) are far too high, dozens of clicks/DL for every contact at the same time (ex: Mr.A opens the mail and, supposedly, clicks 30 times in a row on the same button in 2 minutes, same with Mr.B, Mrs.C etc). 

For instance, last week I sent an email with a CTA and the amount of clicks is far superior to the number of read (which makes no sens): 12.140 clicks for 3660 read. That's because whenever a contact opens a mail, the tracking indicates that they click on it 20, 30, 40 times.

Therefore, I can't trust the data that comes from the tracking. I know that some providers automatically open and click on every links, but the amount of clicks/DL are really numerous for each contact that opens a mail.

Screenshots of what can be seen on contacts history: (same actions at the same time)
<img width="885" alt="Capture d’écran 2021-09-20 à 12 06 00" src="https://user-images.githubusercontent.com/86416173/134202416-d925cbc7-40bf-4edb-801b-0ace71175511.png">
<img width="885" alt="Capture d’écran 2021-09-20 à 12 04 05" src="https://user-images.githubusercontent.com/86416173/134202399-87597d3b-dde6-4f0b-bbdf-85f6c01658c6.png">

### How can we reproduce this issue?

Can't really reproduce it...

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, thanks for taking the time to report this however I believe that we already have the issue raised here: https://github.com/mautic/mautic/issues/9798 I believe, so I'm going to close this down as a duplicate. Please continue the conversation there.

Also, please consider updating to 4.0 as we will not be making any further fixes other than security fixes for the 3.x series.
