### ISSUE TITLE
"Send a webhook" action does not work in campaigns

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#10464]
### Mautic Version

4.0.0

### PHP version

7.4.23

### What happened?

"Send a webhook" action in campaigns does not work

It seems the problem is basically the same as this(https://github.com/mautic/mautic/pull/10301), the same change(BODY to FORM_PARAMS) needs to be done in app/bundles/WebhookBundle/Helper/CampaignHelper.php file

### How can we reproduce this issue?

Step 1: Run Mautic 4.0.0.
Step 2: Create a campaign with "Send a webhook" action(with proper segment, contacts etc.). Campaign can contain just "Send a webhook" action, add some data fields.
Step 3: Trigger campaign, see that "Send a webhook" is successfully completed in campaign Action summary.
Step 4: Check details of one of contacts that was in the campaign, you will see that webhook action failed;

### Relevant log output

```shell
Passing in the "body" request option as an array to send a request is not supported. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or the "multipart" request option to send a multipart/form-data request.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by Saberi01** [comment]
hi, any news?
i have same problem on 4.0.1
![webhook_error_mautic](https://user-images.githubusercontent.com/93643113/140599475-462448fc-b63f-4376-8f36-d65984ab1f31.JPG)

**Comment by kuzmany** [comment]
I've already tested it and works for me 
![image](https://user-images.githubusercontent.com/462477/140652024-65157a14-7ebd-42d3-ae6f-c6def3496eb3.png)

It's clean installation? Or upgrade?

**Comment by kuzmany** [comment]
This should fixed it https://github.com/mautic/mautic/pull/10580

**Comment by jos0405** [comment]
Nice fix, works for me. Test conf needed, and good to go :D
