### ISSUE TITLE
Content-Security-Policy /  X-Frame-Options check in

### ISSUE THREAD

**Issue by rvm-pmis** [mautic/mautic#10469]
### Mautic Version

3.3.x series

### PHP version

7.4.15

### What browsers are you seeing the problem on?

Chrome, Not relevant

### What happened?

After logging in, go to https://<mautic.hostname>/s/focus/new enter an URL, click Fetch, get one of these errors:

- This website blocks iframe previews with the content-security-policy header. Please try another URL.
- This website blocks iframe previews with the x-frame-options: SAMEORIGIN header. Please try another URL.

### How can we reproduce this issue?

Step 1: configure a server to return the fetched url with headers like this:
Content-Security-Policy 'self' frame-ancestors https://mautic.hostname;
X-Frame-Options: allow-from https://mautic.hostname/
Step 2: see "What happened"

I suspect the problem is in plugins/MauticFocusBundle/Helper/IframeAvailabilityChecker.php in the checkHeaders function:

1. headerContains($headers, 'x-frame-options') => doesn't check if it actually contains 'SAMEORIGIN'. It simply assumes based on the existence of the header.
2. headerContains($headers, 'content-security-policy', "frame-ancestors 'self'") => checks for the substring "frame-ancestors 'self'", but it can be followed by domain names (see step 1) which would allow the request.

I still see this issue in the 4.x codebase (we're using 3.3.3).

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @rvm-pmis thanks for raising this. Can you confirm if this persists in Mautic 4 as we are not providing any fixes for the 3.x series going forward. Thanks!

**Comment by rvm-pmis** [comment]
Yes, same issue in Mautic 4. That part of the code hasn't changed between 3.x and 4.x.

**Comment by npracht** [comment]
Can this be related to this fix https://github.com/mautic/mautic/pull/9743 ?

**Comment by nsrderooy** [comment]
I'd just like to add on to this, Please note that according to the standards;
> In order to allow backwards-compatible deployment, the frame-ancestors directive _obsoletes_ the X-Frame-Options header. If a resource is delivered with an policy that includes a directive named frame-ancestors and whose disposition is "enforce", then the X-Frame-Options header MUST be ignored

https://w3c.github.io/webappsec-csp/#frame-ancestors-and-frame-options
