### ISSUE TITLE
PHP Fatal error:  require(): Failed opening required '/var/www/mautic/var/cache/prod/ContainerBJasLGw/getTranslation_Loader_PhpService.php' (include_path='.:/usr/share/php') in /var/www/mautic/var/cache/prod/ContainerBJasLGw/appAppKernelProdContainer.php on line 2225, referer: https://"sitename"/index.php/installer/step/1

### ISSUE THREAD

**Issue by egroeg** [mautic/mautic#10477]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome, Safari

### What happened?

After entering the database connection information into the installer, I receive an error:

```The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
System administrators, check server logs for errors.```

Not much information is given to me to determine what's wrong.



### How can we reproduce this issue?

Step 1: unzip 5-mautic-400.zip and open a web browser.  Proceed to the database connection details and click next.

### Relevant log output

```shell
Apache [php7:error] [pid 1128] [client "client name":36806] PHP Fatal error:  require(): Failed opening required '/var/www/mautic/var/cache/prod/ContainerO3aXLxE/getTranslation_Loader_PhpService.php' (include_path='.:/usr/share/php') in /var/www/mautic/var/cache/prod/ContainerO3aXLxE/appAppKernelProdContainer.php on line 2225, referer: https://"site name"/index.php/installer/step/1
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, this is generally a permissions issue to do with your server setup. Please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)  

This page on the docs may also be helpful: https://docs.mautic.org/en/troubleshooting/file-ownership-and-permissions.

**Comment by egroeg** [comment]
I followed that document and set up permissions as described in https://docs.mautic.org/en/setup/getting-started
