### ISSUE TITLE
GrapesJS forces <style> tags to be merged and added before </body>

### ISSUE THREAD

**Issue by TiagoValdo** [mautic/mautic#10475]
### Mautic Version

4.0.0

### PHP version

7.4.23

### What browsers are you seeing the problem on?

Chrome

### What happened?

The block design works perfectly, generating proper HTML and style tags, but the issue is that custom CSS is generated on a <style> tag that is appended just before </body>.

While this might work with some e-mail clients, Gmail strips <style> tags from the <body> and the actual e-mail shows pretty much unformatted. The solution would be moving the custom CSS to the <head>.

The built-in edit html function allows to move the <style> tag inside the <head> but upon saving, it will force it to show before </body> again.

#### Before clicking **Edit** button
![before clicking edit button](https://user-images.githubusercontent.com/5880212/134675697-50c72246-4c12-4ef3-95cd-06fd80435f37.jpg)

#### After clicking Edit button and opening HTML modal again
![after clicking edit and opening html edit again](https://user-images.githubusercontent.com/5880212/134675689-ba62f868-38b1-4faa-b94a-e4f22e87d580.jpg)

#### <style> tag moved back to before </body>
![style tag moved back to body](https://user-images.githubusercontent.com/5880212/134675685-fca236a4-85f8-48c4-a6b6-c3e97dc0dade.jpg)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by adiux** [comment]
@TiagoValdo thanks for reporting this. Im not sure I understand your solution correctly. You want to have the style in the <head>?
> The solution would be moving the custom CSS to the .

As far as I know <style> and <head> is quite often ignored anyway.

**Comment by TiagoValdo** [comment]
Hey @adiux , thanks for your reply!

I'm sorry. I just noticed that my original text has been stripped. It should read: 

The solution would be moving the custom CSS to the [head] tag.

Yeah, most email clients would just ignore style tags or have a very limited set of properties/classes/queries support.

Gmail, apparently, is one that requires it to be on the head tag, stripping out anything out of it, unless of course it's inline CSS (style property of the p, div, etc).

So merging all CSS into a single style tag inside the head tag, seems to have the better support with email clients.

**Comment by adiux** [comment]
Hi @TiagoValdo. Thanks for explaining this.

This looks to me as Grapesjs is moving the <style> to the end of the body. Not our code. You can verify it by using their demo https://grapesjs.com/demo-newsletter-editor.html

Did you check out the new MJML mode? For compatibility reasons etc. I would recommend using that.

**Comment by ayoubamine** [comment]
I have the same problem, my emails do not render properly on Gmail, but it's looking good on Apple Mail.

I tested on my dev env to update the `custom_html` field from the `emails` table with my custom HTML code (The build of MJML) as a workaround to prevent refactoring my code when using the builder.

Is there any side effect of this solution (like tracking...)?

**Comment by TiagoValdo** [comment]
Hi @adiux 
> This looks to me as Grapesjs is moving the <style> to the end of the body. Not our code. You can verify it by using their demo https://grapesjs.com/demo-newsletter-editor.html

Thanks for the time for looking into this. Indeed it's a grapes issue. Sorry for the trouble! Please close this issue as it's not related do Mautic.

For now, I've disabled grapesjs and we have been building the e-mail templates with another tool then copying pasting the formated HTML into a blank HTML template that works just fine.

@ayoubamine, all links and other functionality works just fine. We can track opens and click throughs just as fine. And we got proper rendering across all major clients.
