### ISSUE TITLE
Cannot use complex passwords with a quotation for the database password

### ISSUE THREAD

**Issue by vondo** [mautic/mautic#1047]
Mautic Installation - Administrative User

The database installation in step 1 goes smoothly but in step 2 there is a problem:

*An error occurred while attempting to create the admin user: SQLSTATE[HY000] [1045] Access denied for user 'mauticuser'@'localhost' (using password: YES)*

I found out that the database information given in step 1 (Mautic Installation - Database Setup) is saving the data to /app/config/local.php but in my password string I have some special characters and the double quotation mark is the problem here. 

I tried with this password: fU:Mk%4Ddh"Dm2b<Hf#c2}cUQ

but the string saved  to local.php is 

'db_password' => 'fU:Mk%4Ddh\\\\\"Dm2b<Hf#c2}cUQ',

The double quotation mark is escaped but the database connection doesn't work with that when trying to create the admin user for mautic.

**Comment by escopecz** [comment]
Can you try just paste the right password to the local.php file, clear cache and then continue with installation?

**Comment by vondo** [comment]
When I found out the problem I restarted the process, changed the password to something simpler and the installation was done successfully. I just wanted to report this if someone else has the same problem.

**Comment by escopecz** [comment]
Aha, thanks for the report then. I was just afraid you cannot finish the installation because of it.

**Comment by ldrrp** [comment]
This also is the case for Email settings configuration and pretty much any config file password stored. You need to escape characters from breaking the php config file.
