### ISSUE TITLE
MJML email builder - Missing Button "Tags" in Editor Bar

### ISSUE THREAD

**Issue by tongdaitructuyen** [mautic/mautic#10483]
### Mautic Version

4.0.0

### PHP version

7.4.22

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What happened?

![missing](https://user-images.githubusercontent.com/5338282/135015318-dbc7e809-a1ea-4a35-94af-02478d6c6f26.jpg)

I have not find button insert tag?

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, 

I think you are maybe referring to entering variables like first name and last name? If so, type { and you will be able to use them all as a workaround. I think that the extension was not added for CKEditor to allow the dropdown selection (cc @alanhartless was this pushed to the community?)

Here are the available variables from the docs: https://docs.mautic.org/en/setup/variables to help in the meantime.

**Comment by npracht** [comment]
I can confirm this regression. It was possible to have a dropdown with variables available in previous builder.
