### ISSUE TITLE
Email statistics

### ISSUE THREAD

**Issue by david-gap** [mautic/mautic#10492]
### Mautic Version

4.0.0

### PHP version

7.4

### What happened?

Dear support

I created a segment with 701 contacts and sended a e-mail to the contacts.
The email been sended to all contacts but the email statistic shows "604 sent" an no pendings.
By clicking the sent summery the contacts are listed with the correct number of 701 contacts.

I've deleted the cache twice and the are no errors in the console or in the log file.

### How can we reproduce this issue?

Its happens with every email, only with different sent result.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi @david-gap,
Are you sure this is not the difference with your unsubscribed and bounced contacts that are in segment but not addressed by email ?

**Comment by david-gap** [comment]
Hello npracht,
I checked it by creating a bounced and a unsubscribed segment. Both segments are empty. And i also cleared the cache with the command line.

**Comment by jos0405** [comment]
It can happen if
- some of the contacts have no valid email
- or some contacts already recieved this email
