### ISSUE TITLE
Internal Server Error only on Dashboard after creating a "widget"

### ISSUE THREAD

**Issue by Dylan-86** [mautic/mautic#10493]
### Mautic Version

4.0.0

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

A bug happened!

I created a "widget" on the dashboard to show the best open hours for emails. I saved it and got an "internal server error - Uh oh I broke something".
Can't fix, it stays there.

The rest of Mautic works: emails, campaigns, I can access all the sections and pages, except /dashboard/ which keeps throwing this error.

### How can we reproduce this issue?

Step 1: create a "widget" on the dashboard for the best open hours. Do not select any segment or campaign.
That's it.

### Relevant log output

```shell
MAYBE this is the error

mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function createQueryBuilder() on null" at /var/www/mautic/app/bundles/EmailBundle/Stats/Helper/FilterTrait.php line 79 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function createQueryBuilder() on null at /var/www/mautic/app/bundles/EmailBundle/Stats/Helper/FilterTrait.php:79)
[stacktrace]
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by raribeiro** [comment]
Hello @Dylan-86 ! Same problem here. @escopecz @alanhartless , any help? My log's below. :) **V4.0.1**

```
[2021-10-06 12:55:06] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function createQueryBuilder() on null" at /var/www/mautic/htdocs/app/bundles/EmailBundle/Stats/Helper/FilterTrait.php line 79 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function createQueryBuilder() on null at /var/www/mautic/htdocs/app/bundles/EmailBundle/Stats/Helper/FilterTrait.php:79)"} []
```

Ps: I removed the row of best open hours of the table "widgets" and the dashboard returned work

**Comment by Dylan-86** [comment]
Hi @raribeiro 
In the end I solved by creating a new user from my existing account and then removing the old user that gave the dashboard error. Note that the dashboard is unique for each user, therefore other users won't be affected by the error.

**Comment by npracht** [comment]
Hello @raribeiro ! I cannot reproduce on 4.0.1.
@kuzmany you have any advice ?
