### ISSUE TITLE
Two issues after upgrade to 1.2.1

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#1049]
Hi guys, 

I found two issues after upgrade:

1, Mautic\PageBundle\Controller\PublicController::trackingImageAction there missing return statement (response)

mautic.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at /path/app/bootstrap.php.cache line 3063 

2,  

mautic.WARNING: PHP Warning: Cannot modify header information - headers already sent by (output started at /path/app/bootstrap.php.cache:1449) - in file /path/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 61 [

I didn't found solution yet. But mautic don't create mautic_sesion_id and relative cookies.

Thank you for help.

**Comment by alanhartless** [comment]
We need unit/functional testing :-/ 1.2.2 will be released today.  See the PR.
