### ISSUE TITLE
Possibility to access (grapejs) builder instance with javascript missing

### ISSUE THREAD

**Issue by KALA-Typo3** [mautic/mautic#10494]
### Mautic Version

3.3.x series

### PHP version

7.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I am trying to add sections and blocks to the grapejs builder. It is working fine, but I am missing a possibility to access the initialized builder.

A dirty solution I did was to add 
`Mautic.grapesBuilder=builder`
in Assets/library/js/builder.js right after `const builder = new BuilderService( ...` call (Line 21 in my case). I touched the dist too of course.

Is there a reason builder object is unaccessable or is there a better practice

### How can we reproduce this issue?

Try to add custom blocks to the grapejs builder

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by KALA-Typo3** [comment]
https://github.com/mautic/mautic/pull/10510

**Comment by RCheesley** [comment]
@KALA-Typo3 can you confirm if this issue persists in Mautic 4? Mautic 3.x will no longer receive any updates so we will only be accepting PRs which relate to Mautic 4 going forward.

I think maybe you need to take a look at the preset, which is where all of the block customisation takes place: https://github.com/mautic/grapesjs-preset-mautic.
