### ISSUE TITLE
GrapeJS editor : <css input>:116:4:Unknown word

### ISSUE THREAD

**Issue by abdul-Tz-prog** [mautic/mautic#10505]
### Mautic Version

4.0.0

### PHP version

7.4.23

### What browsers are you seeing the problem on?

Chrome

### What happened?

When I try to open code Editor in GrapeJS it shows the alert box with the error: "<css> input>:116:4:Unknown word".
This is a bug I think. If anyone has a solution for this please inform or vote for this bug. It is important to be solved, otherwise many issues will remain in GrapeJS.

Sometimes Even It does not open by clicking on the editor button.

### How can we reproduce this issue?

Step 1: Open Builder in mautic
Step 2: Click on the Edit code button for editing theme code.
Step 3: Click on "Edit"

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Could this be related to https://github.com/mautic/mautic/pull/10564
@abdul-Tz-prog can you please test and confirm ?

**Comment by abdul-Tz-prog** [comment]
@npracht you can see when I change something in my code and save it. It always shows the error like shown in the screenshot. I think this is a different error.

![image](https://user-images.githubusercontent.com/85757348/141082095-efc68746-e2e2-4b25-b5f1-cd9b17fb9d58.png)

**Comment by npracht** [comment]
Thanks a lot for your answer :)

**Comment by abdul-Tz-prog** [comment]
@npracht you are welcome. I am looking forward to a solution regarding this issue. :)
