### ISSUE TITLE
MJML Template Encodes Everything including mj-head 

### ISSUE THREAD

**Issue by TornMarketing** [mautic/mautic#10508]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

We are using <mj-style> to target very specific html structures of our converted HTML
Issue didn't exist in earlier versions of Grapes and MJML in Mautic

ie
	  @media (max-width: 480px) {
	  .section > tbody > tr > td {
	  padding-right: 20px !important;
	  padding-left: 20px !important;
	  }
	  .section-sm > tbody > tr > td {
	  padding-right: 10px !important;
	  padding-left: 10px !important;
	  }
}

When the template is saved via Mautic, these styles are then encoded which ultimately breaks the email template.

Original Code
.section > tbody > tr > td {
padding-right: 20px !important;
padding-left: 20px !important;
}

Converted to
.section &gt; tbody &gt; tr &gt; td {
padding-right: 20px !important;
padding-left: 20px !important;
}

Suggestion is to only encode the mj-body and not the whole saved template

### How can we reproduce this issue?

Step 1: Copy special characters into the style sheet
Step 2: Save the template
Step 3: Revisit the template code, see modified template

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi @TornMarketing !
I don't see any modification in your code before/after. Can you please share again ?
