### ISSUE TITLE
Mautic CRM bundle uses Non UTC times and appends Z (zulu) which I think is wrong

### ISSUE THREAD

**Issue by woutersf** [mautic/mautic#10506]
### Mautic Version

4.0.0

### PHP version

PHP 7.4.22

### What browsers are you seeing the problem on?

Not relevant

### What happened?

sprintf('modifiedon ge %sZ', substr($params['start'], 0, '-6'))

This statement Uses Non UTC dates and creates ZULU (UTC) dates from this in the parameters.

There should be something like: 

```
438                         $given = new DateTime($params['start']);
439                         $given->setTimezone(new DateTimeZone("UTC"));
440                         $oparams['$filter'] = sprintf('modifiedon ge %sZ', $given->format("Y-m-d\TH:i:s"));
```

### How can we reproduce this issue?

Step 1: 
Set up and configure microsoft dynamics

Step 2: 
Set up and configure Mautic
Assumption: Run Mautic in NON UTC timezone

Step 3:
Link some contact fields between Mautic and Micorsoft Dynamics.

Step 4:
Run `bin/console mautic:integration:fetchleads -i Dynamics`
And debug the params passed on to Dynamics (docroot/plugins/MauticCrmBundle/Integration/DynamicsIntegration.php function fetchLeads)

Step 5: 
See that the 
`$oparams['$filter'] = sprintf('modifiedon ge %sZ', gmdate(substr($params['start'], 0, '-6')));`
Gives you an incorrect String and will thus fetch (not all) values from the Dynamics server. If Timezone difference high enough.

FIX suggestion:
I have not yet contributed on the mautic project but I think this is the fix:
`438                         $given = new DateTime($params['date']);
439                         $given->setTimezone(new DateTimeZone("UTC"));
440                         $oparams['$filter'] = sprintf('modifiedon ge %sZ', $given->format("Y-m-d\TH:i:s"));`

I will create the needed branch/PR and try to link it. 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for taking the time to report the bug @woutersf and for making a PR to address it, welcome to the Mautic Community! 🚀
