### ISSUE TITLE
Elastic Unsubscribe callback: not reflected in Email stats

### ISSUE THREAD

**Issue by SMCWX** [mautic/mautic#10529]
### Mautic Version

3.3.x series

### PHP version

7.4.9

### What browsers are you seeing the problem on?

Chrome

### What happened?

We use Elasticemail to send Mautic Campaigns related e-mails.
Since we allow contacts to unsubscribe from emails using Elastic Unsubscribe functionality, as per https://docs.mautic.org/en/channels/emails/bounce-management?_ga=2.8207089.273218918.1633958963-754279336.1633958963, we’ve configured Elastic Email Webhook to send back info about contacts ‘Unsubscribe’ actions.
This is working fine in terms of tagging the contact in Mautic as ‘Unsubscribed’ and setting the ‘Do not contact’ flag.
The problem is that the same info is not reflected in the related Email stats graph–> even if the contact unsubscribed from the email and the callback properly updates the contact in Mautic, the unsubscribe is not being reflected in the Email stats graph.

### How can we reproduce this issue?

Step 1: Configure Mautic to use Elastic to send emails and setup Elastic Webook as per https://docs.mautic.org/en/channels/emails/bounce-management?_ga=2.8207089.273218918.1633958963-754279336.1633958963
Step 2: unsubscribe to a Mautic Email using Elastic Unsubscribe button (added by default to Mautic Emails)
Step 3: see the Mautic contact that unsubscribed being tagged as 'unsubscribed' in Mautic
Step 4: check the related Email stats graph in Mautic and notice how no 'unsubscribe' actions are being reported

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi there,
Unfortunately the 3.x series are not supported anymore as you can read here:
https://github.com/mautic/mautic#supported-versions

Could you please test in latest release to tell us if issue persists?
Thanks!
