### ISSUE TITLE
Where is the Vendor folder?? 

### ISSUE THREAD

**Issue by listinfm** [mautic/mautic#10524]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Unable to update to Mautic 4.0 when starting from scratch! Can't reach the setup page because it cannot find the vendor directory!

In the mautic main directory you have a autoload.php file. This file states: return require __DIR__ . '/vendor/autoload.php';

Where is the vendor directory!!??

am I missing something? 

### How can we reproduce this issue?

Step 1: download and extract project
Step2: try to run

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
