### ISSUE TITLE
Token Array Corruption in Broadcast Send

### ISSUE THREAD

**Issue by maxlawton** [mautic/mautic#10545]
### Mautic Version

3.3.x series

### PHP version

7.3.31

### What happened?

When sending batched broadcasts, the array of tokens propagated through to the message metadata and stored in corresponding EmailStats can become corrupted with the values from the first recipient in the batch. While this behavior doesn't necessarily result in delivery of unexpected content to contacts, it is certainly undesirable.

This occurs when a token exists only within a link URL in the HTML content of the email. For example, with the following email content:

HTML Content
------------

```html
<html>
  <body>
    Hello <a href="https://example/{contactfield=email}">subscriber</a>.
  </body>
</html>
```

Plain Text
----------

```
Hello subscriber.
```

When the **EmailModel** processes a send via **SendEmailToContact**, the original content of the **Email** is bound to the **MailHelper**.

As the `mautic.email_on_send` event is dispatched for the first contact in the batch, the `EmailSubscriber::onEmailGenerate()` handler discovers tokens (via `TokenHelper::findLeadTokens()`) in the original **Email** content bound to the **MailHelper**.

The lead tokens, including `{contactfield=email}`, are added to the event.

As the final listener on that event, the **EmailBundle/BuilderSubscriber** calls `convertUrlsToTokens()`. This contains a call to `parseContentForUrls()`, which replaces content URLs with _trackable_ tokens, and sets the **Event**'s content to that converted HTML, which in turn binds that content to the **MailHelper**'s body.

https://github.com/mautic/mautic/blob/7a5dd9c55c6bd53b77092da52d9f4cf5ac447369/app/bundles/EmailBundle/EventListener/BuilderSubscriber.php#L358

The tokens discovered by the event are merged into the **MailHelper** `$eventTokens` array.

https://github.com/mautic/mautic/blob/7a5dd9c55c6bd53b77092da52d9f4cf5ac447369/app/bundles/EmailBundle/Helper/MailHelper.php#L1637

As the `mautic.email_on_send` event is dispatched for subsequent leads in the batch, the content passed to `TokenHelper::findLeadTokens()` by the **EmailSubscriber** contains the _trackable_ tokens converted by the final listener in the first dispatch, not the original tokens in the **Email** content. Thus, the tokens accumulated within the newly dispatched **EmailEvent** do not contain `{contactfield=email}`. So, when the **MailHelper** `$eventTokens` are updated via `array_merge()`, there is no replacement to overwrite that token value from the first lead in the batch.

Possible Solutions
------------------

1. Include the original HTML in the content passed to `TokenHelper::findLeadTokens()`. This could be achieved by adding a public method to the **EmailSendEvent** which returns `$this->helper->getEmail()`, thereby allowing access to `getCustomHtml()` and `getPlainText()` on the **Email** object for inclusion in the `$content` string.
2. Reorder event subscribers so trackables in content are replaced before contact tokens are extracted. This would prevent population of replaced tokens for all contacts in the batch.
3. Clean contact-specific (e.g. `{contactfield=*}`) tokens out of the **MailHelper**'s `eventTokens` array before merging values from the dispatched **EmailSendEvent**.

### How can we reproduce this issue?

1. Create a "Segment Email", with HTML content having a link in which the url contains a `{contactfield=email}` token string, and with _plainText_ not having any such URL. Assign a segment with several leads and publish the **Email**.
2. Trigger a broadcast send with batch limits, like so (assuming the **Email** has ID `1`): 
  `bin/console mautic:broadcasts:send --channel=email --limit=8 --batch=6 --id=1`
3. Review the resultant entries in the `email_stats` table, comparing the values of `email_stats.email_address` and value associated with the `"{contactfield=email}"` key of the `email_stats.tokens` array.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi there,
Unfortunately the 3.x series are not supported anymore as you can read here:
https://github.com/mautic/mautic#supported-versions

Could you please test in latest release to tell us if issue persists?
Thanks!
