### ISSUE TITLE
Status 500 Internal Server Error for each ajaxActionRequest Request

### ISSUE THREAD

**Issue by kiakahaDZ** [mautic/mautic#10554]
### Mautic Version

3.3.4

### PHP version

7.4.9

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

hello i have created a mautic plugin for mautic 3.3.4, and I have issued each ajaxActionRequest show me an error Status
500 Internal Server Error, I don't know why? 
![image](https://user-images.githubusercontent.com/46278484/138612370-52c6a1ff-e912-4381-8f9d-48bc72bae667.png)

### How can we reproduce this issue?

Step 1: Create an AjaxController.php that contains a function for being called.
Step 2: Create js file that contain ajaxActionRequest 
Step 3: Create a request from view with the includeScript

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi @kiakahaDZ,
Unfortunately the 3.x series are not supported anymore as you can read here:
https://github.com/mautic/mautic#supported-versions

Could you please test in latest release to tell us if issue persists?
Thanks!
