### ISSUE TITLE
Every time when we update contact , in event showing contact created.

### ISSUE THREAD

**Issue by mk1319** [mautic/mautic#10555]
### Mautic Version

4.0.0

### PHP version

7.4.23

### What browsers are you seeing the problem on?

Chrome

### What happened?

In Event Name Showing Contact Created , When we Update Contact 

### How can we reproduce this issue?

Step 1: Create in Contact and open.
Step 2: Click On Edit and save & close.
Step 3: in Event name showing "Contact Created"

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi @mk1319 i cannot reproduce:
<img width="540" alt="Capture d’écran 2021-11-09 à 14 24 20" src="https://user-images.githubusercontent.com/14075239/140931958-f0ba5224-0c0d-4ead-afee-f1dccfcbae94.png">

Can you test in 4.0.1 ? Or maybe i'm doing something wrong ?
