### ISSUE TITLE
Send email for campaign is not working properly. (campaign Creation)

### ISSUE THREAD

**Issue by mk1319** [mautic/mautic#10558]
### Mautic Version

4.0.0

### PHP version

7.4.0

### What happened?

![image](https://user-images.githubusercontent.com/52974165/138899657-077a8fcb-772e-4363-ad05-444bd8759f4c.png)

if you again click on search box , box will move to left side and you can't enter text.

### How can we reproduce this issue?

Step 1: click on create new campaign .
step 2: add action send email .
step 3: search for email template.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi @mk1319 i can reproduce the issue in latest version.
I hope screenshot helps developers. I don't know why this `width` is set like that.
<img width="1440" alt="Capture d’écran 2021-11-09 à 14 18 34" src="https://user-images.githubusercontent.com/14075239/140931178-bc375aeb-451c-4a1c-b283-77a16c40d0d8.png">
