### ISSUE TITLE
Code Mode Issue

### ISSUE THREAD

**Issue by ItDoBeNord** [mautic/mautic#10556]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

**Issue:**

If you have any template selected and load up the builder and click the button for code mode it opens the box up perfectly fine but if you exit the builder and select another template and reload the builder the code mode button now no longer works for ANY email template now.

**Video of issue:** https://www.loom.com/share/0c2475b73fae4fdaad39ec8c6aa6393e

**Workaround:**

I have noticed clearing your cache and cookies seems to fix the issue but breaks again when you go to another template and try to use code mode.

### How can we reproduce this issue?

Video: https://www.loom.com/share/0c2475b73fae4fdaad39ec8c6aa6393e

Step 1: Create a new email template

Step 2: Open Code Mode

Step 3: Close the builder and select another template

Step 4: Try and open Code Mode

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by adiux** [comment]
I believe this will be fixed with PR https://github.com/mautic/mautic/pull/10552 that is ready for testing

**Comment by adiux** [comment]
If it is the same problem an easier workaround would be to reload the browser.

**Comment by npracht** [comment]
Please test and add your review on https://github.com/mautic/mautic/pull/10564

**Comment by npracht** [comment]
Closing in favor of https://github.com/mautic/mautic/issues/10455 (duplicate)
