### ISSUE TITLE
Dynamic Filters not shown in filters tab of Reports

### ISSUE THREAD

**Issue by xnohat** [mautic/mautic#10565]
### Mautic Version

4.0.0

### PHP version

7.3

### What browsers are you seeing the problem on?

Chrome

### What happened?

Dynamic Filters not show in Filters section 

### How can we reproduce this issue?

Step 1: Create new Custom Report
Step 2: set a Filter option Dynamic? to YES
Step 3: Save and Closed Report
Step 4: View report

### Relevant log output

```shell
Mautic not fire any error log
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by Dylan-86** [comment]
Yes, I confirm. I thought it was just a problem on my end.

**Comment by npracht** [comment]
I confirm this is still an issue on 4.0.2-rc on reports.
<img width="875" alt="Capture d’écran 2021-11-09 à 13 06 44" src="https://user-images.githubusercontent.com/14075239/140921471-6758d5f8-6e28-4e17-a132-8acf5e9f9445.png">

<img width="585" alt="Capture d’écran 2021-11-09 à 13 06 32" src="https://user-images.githubusercontent.com/14075239/140921425-ea2129ca-43d7-4714-b865-b5f75eb091c0.png">

**Comment by bulgin** [comment]
Mautic 4.1.1
PHP Version 7.4.27
Centos 7


I'm experiencing this as well - report filters do not appear in the UI.
This started when I migrated from 3X mautic to 4.1.1
Nothing in logs.
