### ISSUE TITLE
MariaDB reporting deadlock on contact update

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#10561]
### Mautic Version

3.3.4

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Seeing errors in the log across multiple instances of Mautic indicating deadlocks occurring during contact updates. This seems to happen sporadically. 

`[2021-10-28 13:47:08] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DeadlockException: "An exception occurred while executing 'UPDATE leads SET date_modified = ?, last_active = ? WHERE id = ?' with params ["2021-10-28 13:47:08", "2021-10-28 13:47:07", "31102"]:  SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction" at /WEB_ROOT/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 34 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DeadlockException(code: 0): An exception occurred while executing 'UPDATE leads SET date_modified = ?, last_active = ? WHERE id = ?' with params [\"2021-10-28 13:47:08\", \"2021-10-28 13:47:07\", \"31102\"]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /WEB_ROOT/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:34, Doctrine\\DBAL\\Driver\\PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /WEB_ROOT/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /WEB_ROOT/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []
`

### How can we reproduce this issue?

I am seeing this across multiple instances regularly in the log. It's not clear how to reproduce, though :(

### Relevant log output

```shell
[2021-10-28 13:47:08] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DeadlockException: "An exception occurred while executing 'UPDATE leads SET date_modified = ?, last_active = ? WHERE id = ?' with params ["2021-10-28 13:47:08", "2021-10-28 13:47:07", "31102"]:  SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction" at /WEB_ROOT/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 34 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DeadlockException(code: 0): An exception occurred while executing 'UPDATE leads SET date_modified = ?, last_active = ? WHERE id = ?' with params [\"2021-10-28 13:47:08\", \"2021-10-28 13:47:07\", \"31102\"]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /WEB_ROOT/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:34, Doctrine\\DBAL\\Driver\\PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /WEB_ROOT/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /WEB_ROOT/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi @stevedrobinson ! 3.x series are not supported any more, see:
https://github.com/mautic/mautic#supported-versions

Can you please test and tell us if issue persists in 4.x ?

**Comment by mabumusa1** [comment]
Hi @npracht ,

I faced this issue as well with version 4.0.2, I still do not know the cause of the issue yet 

Here is the error I got 
`[2021-11-28 07:17:55] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DeadlockException: "An exception occurred while executing 'UPDATE m4_leads SET date_modified = ?, last_active = ? WHERE id = ?' with params ["2021-11-28 07:17:55", "2021-11-28 07:17:55", "311234"]:  SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction" at /home/xxxxx/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 51 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DeadlockException(code: 0): An exception occurred while executing 'UPDATE m4_leads SET date_modified = ?, last_active = ? WHERE id = ?' with params [\"2021-11-28 07:17:55\", \"2021-11-28 07:17:55\", \"311234\"]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /home/xxxxx/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:51, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /home/xxxxx/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /home/xxxxx/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:112)"} []`

**Comment by mzagmajster** [comment]
@mabumusa1 

Could the reason be that mautic cronjob first locked the record and then you tried to update it via browser while the record was still locked?

**Comment by mabumusa1** [comment]
@mzagmajster yes,  this is possible

**Comment by stevedrobinson** [comment]
Still seeing this in version 4.1.1. I just updated a bunch of instances to 4.1.2 and I'll report back if still an issue on that version.

**Comment by RCheesley** [comment]
Thanks for confirming it is still an issue with Mautic 4 - are you still getting the deadlocks in 4.2.0 @stevedrobinson ?

**Comment by kizzlota** [comment]
Got the same issue, any updates on this issue. Does it resolved for the version >= 4.2.0 ?

**Comment by stevedrobinson** [comment]
I am still seeing this with 4.3, though less frequently than when I reported it.

**Comment by rayTawk** [comment]
hi there, I can still seeing this issue happened on Mautic 4.4.1.
it mainly happened when the cronjob run `mautic:segments:update`.
