### ISSUE TITLE
Mautic form is redering in <head>

### ISSUE THREAD

**Issue by rpayanm** [mautic/mautic#10563]
### Mautic Version

4.0.0

### PHP version

7

### What browsers are you seeing the problem on?

Firefox

### What happened?

The form is rendering inside `<head>` when I use it in a modal.

### How can we reproduce this issue?

I'm trying to embed Mautic forms in my drupal site.
I created a page ( '/mautic-form`) and inside I have this:
```
<script type="text/javascript" src="//mautic.coachingrealista.com/mautic/form/generate.js?id=3"></script>
```

When I go to that page (`/mautic-form`), the form renders well:
![image](https://user-images.githubusercontent.com/6087454/139479032-c719bf2e-92ed-4e19-8350-3b3161c6990c.png)

But when I use it inside a modal, the form renders in the `<head>`:
![image](https://user-images.githubusercontent.com/6087454/139478798-d1b12bd2-f761-4c67-ab90-b4224730c528.png)

I looked on the JS console and I didn't see any error.

Is there any way to tell it to render inside a `<div>` with a `ID`, for example?

Or is there anything I can do to the form renders well?

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi @rpayanm !
Thanks for your message. Where did you paste your focus item script ?

**Comment by Arthur-bl-dev** [comment]
i'm in the same problem.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
