### ISSUE TITLE
List of IPs to not track Empty

### ISSUE THREAD

**Issue by CyberZen53** [mautic/mautic#1056]
List of IPs to not track does not appear to save entries. I have tried to enter, apply and save my own IP several times now. After apply or save, the "List of IPs to not track" field is empty.

Version 1.2.1
VPS install on CentOS
IP Lookup Service = Telize

Note that my instance does save other config changes - just not the IP's not to track. This was also an issue with 1.2.0

**Comment by escopecz** [comment]
I can replicate this issue.

**Comment by escopecz** [comment]
The fix is here: https://github.com/mautic/mautic/pull/1059

**Comment by CyberZen53** [comment]
Outstanding, thanks.

**Comment by alanhartless** [comment]
Fixed in 1.2.2
