### ISSUE TITLE
[feature] Easy Two Step Forms (ie... modal forms)

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#1057]
Leadpages has this thing called "two step form".   Its basically a button you click on the site and the form pops up in a modal.  https://blog.leadpages.net/two-step-opt-in-process-list-building/

This is pretty easy to do ourselves (if running something like bootstrap for a css framework) but would be nice to have an easy option for doing this.  Webinarjam also has this feature for their signup buttons and it works well.

**Comment by escopecz** [comment]
Mautic forms can have multiple steps for some time now.
