### ISSUE TITLE
Subscribed Category Filter

### ISSUE THREAD

**Issue by DogByteMarketing** [mautic/mautic#10576]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When building a segment in v4.0.1 using the subscribed category filter, Empty does not work. We're trying to set it up so we can pull everyone who hasn't set preferences and those that have a specific category.

### How can we reproduce this issue?

Create a segment using the subscribed category filter and run the update segments cron.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by kuzmany** [comment]
Categories for contacts looks like incomplete feature. Segments and tags do same with deep integration. I suppose to category for contacts gonna removed in the future.

**Comment by npracht** [comment]
@RCheesley and @alanhartless see Zdeno's comment above. What do you think about this ? Maybe we can add "remove category for contacts" issue on JIRA MAT board ?

**Comment by DogByteMarketing** [comment]
> Categories for contacts looks like incomplete feature. Segments and tags do same with deep integration. I suppose to category for contacts gonna removed in the future.

The reason we even tried this route was that categories weren't working with contact preferences https://github.com/mautic/mautic/issues/10575. If this option is available we can check to see if they have no categories selected and automatically add them to a segment. It probably would be more efficient to use segments to check for a tag instead, but we'll have to build a campaign to add a tag to everyone who currently doesn't belong to our category. This probably is preferred as it'll show those segments already checked when they go to unsubscribe, but the documentation doesn't really lay this out very well to someone is new to the platform. Also if we go this route with segments there isn't really a need for categories except for admins in the backend, as we can assign everyone going through a welcome journey all the category tags they need, and then cron would run to assign them to a segment, which we would then check for in a campaign or assign to inside a segment email.
