### ISSUE TITLE
Only contacts who viewed main email are shown if the emails has a translation

### ISSUE THREAD

**Issue by adiux** [mautic/mautic#10581]
### Mautic Version

3.3.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

A click on the button to display all contacts who viewed a translated email shows only the main emails views.

The link generated is: 
`/s/contacts?search=email_read:181` 

but it should be:
`/s/contacts?search=email_read:180,181`

### How can we reproduce this issue?

Step 1: go to the email overview page
Step 2: click on the view contacts who viewed the email button
Step 3: A link with only one email id is generated: Only the contacts who viewed the main email are displayed in the contact list. The contacts who viewed the translated emails are not shown.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi @adiux knowing that we don't support 3.x branches even for security matter (see https://github.com/mautic/mautic#supported-versions), can you tell if this is still an issue in latest release (4.0.1) ?
Thanks !
