### ISSUE TITLE
Custom email headers

### ISSUE THREAD

**Issue by asquelt** [mautic/mautic#10584]
### Mautic Version

4.0.0

### PHP version

7.4.24

### What browsers are you seeing the problem on?

Not relevant

### What happened?

My email provider (Postmark) has two sets of mailers - for transactional emails (like opt-ins and password resets) and for bulk (newsletters, marketing emails, etc). I can choose between the two with X header in the emails I generate.

eg.
```
X-PM-Message-Stream: broadcast
```
or
```
X-PM-Message-Stream: transactional
```

Currently it's not possible to add a custom email header to email templates.
I think community would benefit if it is possible.

### How can we reproduce this issue?

Step 1: Make email template
Step 2: Observe there is no place where custom header could be added

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hello @asquelt ! Thanks a lot for your message. Nevertheless this is more a feature request to extend existing feature (custom headers) into templates.

The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
