### ISSUE TITLE
Warnings in CI pipeline: `ERROR 1064 (42000) at line 58: You have an error in your SQL syntax`

### ISSUE THREAD

**Issue by dennisameling** [mautic/mautic#10592]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

In the CI pipeline, there's some SQL-related warnings that have been there for months:

```
............................int(4)
int(2)
int(1)
int(3)
.................................   61 / 2243 (  2%)
.............................................................  122 / 2243 (  5%)
.............................................................  183 / 2243 (  8%)
......................................................ERROR 1064 (42000) at line 58: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTR' at line 1
.ERROR 1064 (42000) at line 58: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTR' at line 1
......  244 / 2243 ( 10%)
.............................................................  305 / 2243 ( 13%)
.............................................................  366 / 2243 ( 16%)
``` 

Two challenges:
- Let's find out why these warnings aren't being converted into errors, so we would've spotted them earlier
- Let's find the root cause for this and fix it 😊 

### How can we reproduce this issue?

Running the PHPUnit tests locally or in CI

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mollux** [comment]
@dennisameling 

I tackled this in #10759 (see the explanation under `ensure only sql queries are stored in the fresh_db.sql file` and [this commit](https://github.com/mautic/mautic/pull/10759/commits/5bea6108db15bba9c531acef89a4f074c8733e77))
