### ISSUE TITLE
Boolean required field cannot be set to "No" via UI

### ISSUE THREAD

**Issue by andrew-dixon** [mautic/mautic#10606]
### Mautic Version

4.0.1

### PHP version

7.4.24

### What browsers are you seeing the problem on?

Not relevant

### What happened?

If you have a boolean custom field that is "required" you cannot, via the web UI, set this field to the "No" (false) value, only the "Yes" (true) value. When you click either the "Apply" or "Save & Close" button, it tells you the field(s) set to "No" is required and will not save. This was not the case on v3.x, but is now the case on v4.0.1.

### How can we reproduce this issue?

Step 1: Create a core custom field of data type boolean, set the default value to either No or Yes (doesn't matter) and set the "Required" option to "Yes".
Step 2: Go to a contact and click "Edit"
Step 3: Set the value of the custom field created in Step 1 to "No"
Step 4: Click either "Apply" or "Save & Close" and see the error message that the field is required.

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
I could reproduce this:
![image](https://user-images.githubusercontent.com/4246909/143549551-636080bc-620a-47eb-b90b-ee885730ffe5.png)
My default setting was no btw.

**Comment by mabumusa1** [comment]
Should stay open

**Comment by andrew-dixon** [comment]
@mabumusa1 This issue has been fixed in v4.1 as part of another fix.
