### ISSUE TITLE
html-code is changed inside mj-raw component

### ISSUE THREAD

**Issue by richarddegoffau** [mautic/mautic#10616]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

You can add a "raw" component inside a WJML-theme.
We assume all html-content inside the <mj-raw>tag should be kept unchanged (that's why it's a **raw** component).
But when sending/previewing the e-mail, the code inside the <mj-raw> is changed - including inline styling, and sometimes even html-tags are missing.

### How can we reproduce this issue?

Step 1: Add an e-mail using the "Brienz" theme
Step 2: Add a raw-component
Step 3: Put the following content into the raw component: \<p style="color: #FF0000;"\>Test code\</p\>
Step 4: Save e-mail, and view the preview
Step 5: Inspect the code - you'll see the style-tag has disappeared, and the <p> is not colored red

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by richarddegoffau** [comment]
In Step 3 of my description are the tags stripped - new try:
Step 3: Put the following content into the raw component: "\<p style="color: #ff0000"\>Test code\</p\>"

**Comment by AntoniyaM** [comment]
Also seeing this behavior with Mautic 4.1.1: when going back to edit the email, mj-raw is still in the MJML code, but it's contents are stripped.
