### ISSUE TITLE
Forms: Checkbox values aren't saved in contact information

### ISSUE THREAD

**Issue by LeonOltmanns** [mautic/mautic#10613]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

When using checkbox in a form the value of the checkbox wont be saved into the mapped contact field. 
This error occurred on Mautic 3.3.x and was tested again on 4.0.1 with the same results. 

Even though the results are shown in the Contact-History.
![image](https://user-images.githubusercontent.com/55587275/141958467-9453f53a-c4ee-4756-8c68-766d580773ee.png)

And even the Form-stats:
![image](https://user-images.githubusercontent.com/55587275/141958240-77710b60-f849-47e0-867a-84fa016ab083.png)

It is not persisted / shown in the Contact-details:
![image](https://user-images.githubusercontent.com/55587275/141957893-73d05711-03cb-4dc0-9a1c-c5d463e2799e.png)

### How can we reproduce this issue?

1. (Optional - Create a custom "text" field)
2. Create a form
3. Add an email field
2. Add a checkbox field 
3. Map the checkbox onto that custom text field or any other text-field
4. Add a Label and any Value in the properties-tab
5. Save the form
6. Fill out the form 
7. See that no value has been saved into the mapped field

### Relevant log output

```shell
no log output.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by automatyzuj** [comment]
+1 Regression. Problem still exist with M4.2.

I will be grateful for reopening.
