### ISSUE TITLE
Mautic Unsubscribe link Broken

### ISSUE THREAD

**Issue by LucasBorthiry** [mautic/mautic#10611]
### Mautic Version

3.2.x series (not supported)

### PHP version

7.3.31

### What browsers are you seeing the problem on?

Chrome

### What happened?

When clicking the link unsubscribe in an email sent by a campaign (generated by token {unsubscribe text}) go to an error page

### How can we reproduce this issue?

- Create email with token {unsubscribe_text}
- Create a segment test to send test email with a contact
- Create a campaign send email with segment test
- Contact receive mail with unsubscribe link, click go to error page
- Though unsubscribe is broken but contact still changed to Do Not Contact

### Relevant log output

Uh oh! I think I broke it. If I do it again, please report me to the system administrator!
500 Internal Server Error
Mautibot
Report an issue

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jd6-37** [comment]
I'm having the same exact issue. Was hoping to send our first newsletter today, but this is obviously critically holding us back. FYI, I tried with and without the preference center. We're on v4.0.1.

Edit: Updated to v4.0.2 and it appears to be fixed for me.

**Comment by jos0405** [comment]
Quick question: did you test a real segment send or you did a 'test send' before you noticed the unsub ink broken?

**Comment by elilogan** [comment]
Check permissions on the var/log directory. As a test set them to 777 and then try to click unsubscribe link. Then walk back permissions to whatever is applicable to your application.

**Comment by LucasBorthiry** [comment]
> Quick question: did you test a real segment send or you did a 'test send' before you noticed the unsub ink broken?

yup. I tested a real segment and also a "test send", none of them worked.  

> Check permissions on the var/log directory. As a test set them to 777 and then try to click unsubscribe link. Then walk back permissions to whatever is applicable to your application.

I had read that solution, but I didn't try it. I think that it may work. but what I did was to restore a backup version of the installation and the issue has gone. 

I think I had touched something in the configuration, but I really don't know what. I will be more careful from now on.

**Comment by LucasBorthiry** [comment]
> I'm having the same exact issue. Was hoping to send our first newsletter today, but this is obviously critically holding us back. FYI, I tried with and without the preference center. We're on v4.0.1.
> 
> Edit: Updated to v4.0.2 and it appears to be fixed for me.

@j26w  You should try what @elilogan is saying and report to us so that we know how to deal with this in the future.

**Comment by jos0405** [comment]
User confirmed it was a config error.
