### ISSUE TITLE
Feature request - Add lifecycle stages to lead

### ISSUE THREAD

**Issue by gpassarelli** [mautic/mautic#1061]
Think of Mautic as a CRM, it would be nice if it comes with the core, a field for the lead, where you can setup the lifecycle stage of that lead. Hubspot has this concept and you can read more about it here:
http://knowledge.hubspot.com/contacts-user-guide-v2/how-to-use-lifecycle-stages

It would be nice to have this as a Core field instead of a custom fields, because then we could provide a report where we could have the pipe graph of the  number of leads per stages per month.

**Comment by that0n3guy** [comment]
I'm not sure this needs to be core.  I think the features request is that you want to create reports based on custom fields like the one you mention...  Right?  You could careless if the field was in core or custom as long as you have that report thing.

**Comment by gpassarelli** [comment]
I guess, I can see the option of creating reports based on custom fields as a way to achieve this.

**Comment by alanhartless** [comment]
The option to create reports based on custom fields is already there (filter a lead report).  Is there something more needed?

**Comment by gpassarelli** [comment]
We can filter by a custom field, but it would be nice if we could have more options of graphs, for a speficif field for example.

If a field is a select, for example, show a graph of the number of leads grouped by value options of the select field. 

In the case of "Lifecycle Stage"  the ideal is to have a funnel graph so you can see how your leads are changing their stages. So this is why I thought of being a Core field, so we can "hard code" the order of the stages and create the funnel.

But for custom fields, it's fine to be a line graph

**Comment by rodrideme** [comment]
+1 

Great feature. The sales funnel is the sexiest thing in the marketing universe today. Reduce the gap between marketing and sales, the marketing view if your efforts are paying off, quickly identifies what stage the conversion rate is not good.

Every day the community ask me if it is possible create a similar report in mautic, like this:
http://cdn.business2community.com/wp-content/uploads/2015/04/ee595494-ec70-4ad4-afc4-f33f1cd2ab38.png-755x600.png

I improvised a funnel inside Mautic with lists and custom fields take a look:
http://rodrigodemetrio.com/wp-content/uploads/2015/12/mautic-funnel.png

Will be crazy something like that.

**Comment by npracht** [comment]
Done in #1770 right?
