### ISSUE TITLE
Inline styles stripped when sending/previewing e-mail

### ISSUE THREAD

**Issue by richarddegoffau** [mautic/mautic#10615]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When adding an e-mail based on a HTML (non-WJML) theme - e.g. "Code Mode", all inline styling is stripped when sending/previewing the e-mail. All styles are moved to a <style> tag, but this doesn't show the styling correctly in most mail-clients.

### How can we reproduce this issue?

Step 1: create a new e-mail, and use the "Code Mode" theme
Step 2: set a background-color on the outer box
Step 3: save and send a preview e-mail
Step 4: inspect the code of the email - you'll find all inline styles stripped, and the background-color is not visible (in Outlook for example)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by alexbrazier** [comment]
We are also seeing this in `4.1.0`. Did you find any workaround @richarddegoffau?

**Comment by alexbrazier** [comment]
I've found a workaround for now. It seems to be related to the new WYSIWYG email editor (GrapeJS).
If you go to `Settings->Plugins` and disable GrapeJS you can then select the code mode template and paste the formatted html without it making changes.

**Comment by richarddegoffau** [comment]
> We are also seeing this in `4.1.0`. Did you find any workaround @richarddegoffau?

Turn off the GrapeJS editor is a workaround, but you'll miss the features of GrapeJS too.
I now use only the Brianz theme as a workaround.

**Comment by npracht** [comment]
Closing in favor of https://github.com/mautic/mautic/issues/10572. Duplicate topic.
