### ISSUE TITLE
Boolean Fields in Filters on Reports Broken

### ISSUE THREAD

**Issue by andrew-dixon** [mautic/mautic#10614]
### Mautic Version

4.0.1

### PHP version

7.4.24

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When you select a boolean field in the filters for a report instead of getting the "No", "Yes" and "Clear Filter" options for the value, it shows "No", "Clear Filter" and "Clear Filter" with the first "Clear Filter" pre-selected:

![Screenshot 2021-11-16 at 14 09 12](https://user-images.githubusercontent.com/7441801/142001365-aefc7094-afbc-4732-b4aa-9f0a539c5bd6.png)

### How can we reproduce this issue?

Step 1: Go to Reports
Step 2: Click the "+New" button
Step 3: On the new report page click the "Data" tab
Step 4: On the "Data" tab, click the "Add Filter" button
Step 5: From the "Column" dropdown, select a boolean field, e.g. Clicked
Step 6: See the options are incorrect

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Confirmed, I also have the same issue.

**Comment by RCheesley** [comment]
I wonder if this might be related to the issues we fixed in https://github.com/mautic/mautic/pull/10716 with boolean fields on the contact profile? @patrykgruszka could this be the same issue but in a different part of Mautic?

**Comment by patrykgruszka** [comment]
@RCheesley it is possible. I cannot replicate this issue after update. @jos0405 @andrew-dixon check if the issue still exists in the latest version.

**Comment by andrew-dixon** [comment]
@patrykgruszka @RCheesley I do not have the issue in the latest version either, so I would say that #10716 fixed it. I can also save contacts again in the edit contact view, which also had an issue with boolean fields. 😄
