### ISSUE TITLE
email translations lost and overwritten by parent

### ISSUE THREAD

**Issue by garzettone** [mautic/mautic#10618]
### Mautic Version

4.0.0

### PHP version

PHP 7.4.23

### What browsers are you seeing the problem on?

Not relevant

### What happened?

the issue rperoted here https://github.com/mautic/mautic/pull/10525 it is still not resolved in 4.02 version

### How can we reproduce this issue?

See https://github.com/mautic/mautic/issues/10562 to steps to repeat the problem. There is a video too.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi @garzettone ! This is fixed in 4.0.2 by https://github.com/mautic/mautic/pull/10525
Thanks for using Mautic 🚀

**Comment by npracht** [comment]
Just saw your comment on https://github.com/mautic/mautic/pull/10525#issuecomment-970470626
@kuzmany any advice ? Because i tested and it works.

**Comment by garzettone** [comment]
Have you followed the steps I recorded in this video: https://vimeo.com/641413139/255f0df39d   ?

**Comment by kuzmany** [comment]
That  PR just extend Mautic with method,  what we have to use it in GrapesJS bundle 
Let's test this PR https://github.com/mautic/mautic/pull/10620 
Should fixed it finally
