### ISSUE TITLE
Feature request - Exclude leads from a Leads List on Lead Source Campaign Builder

### ISSUE THREAD

**Issue by gpassarelli** [mautic/mautic#1062]
We can already select several lists as a Lead Source for Campaign Builder, but it would be nice if we could select several lists to exclude the leads that belogs to those lists. So for example we would have the following lists:

**List 1:**
Lead 1
Lead 2
Lead 3
...
**List 2:**
Lead 2
Lead 4
Lead 5
...
**List 3:**
Lead 2

Campaign Builder - Lead Source - Lead Lists
Include Lead lists:
*List 1*, *List 2*
Exclude Lead lists:
*List 3*

And the campaign would only be sent to the following leads:
Lead 1
Lead 3
Lead 4
Lead 5

**Comment by alanhartless** [comment]
The feature is there to create list based on other list membership.  So you could create a new list that has  two filters:

"list membership" "includes" "list1, list2"
"list membership" "excludes" "list3"

Then use that new list as the campaign's lead source.  I think that would work for what you want although an extra step.

**Comment by gpassarelli** [comment]
Sorry I didn't see the option "List Membership" before. 
So you are correct, is already here and I'm fine with having to do this " extra step"
