### ISSUE TITLE
Date as Segment Filter returns 1 day less every time

### ISSUE THREAD

**Issue by alexhammerschmied** [mautic/mautic#10621]
### Mautic Version

4.0.2

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I use a date as filter for a segment with a relative value i.e today, yesterday, 2 days ago, or similar logic it returns one day less every time.
If i put in tomorrow, i get the date of today.

### How can we reproduce this issue?

Step 1: create a custom field "date"
Step 2: create a segment
Step 3: apply filter with custom field date (i.e) "date" equals "today" or "1 day ago"
Step 4: run cronjob mautic:update:segments
Step 5: find contact in segment and check date - it's 1 day less than expected

### Relevant log output

note: my systems runs on CET Europe/Berlin

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by alexhammerschmied** [comment]
I run Version 4.0.2

**Comment by RCheesley** [comment]
Is this still an issue in 4.1.2 @alexhammerschmied ?

**Comment by alexhammerschmied** [comment]
This is resolved in 4.4.1
