### ISSUE TITLE
GrapesJS / mjml style manager read/writes padding differently  

### ISSUE THREAD

**Issue by notz** [mautic/mautic#10629]
### Mautic Version

4.0.2

### PHP version

7.4.15

### What browsers are you seeing the problem on?

Chrome

### What happened?

The GrapesJs style manager reads only the following padding format when selecting an element: `padding="15px 0 0"`. But after changing some values the changed padding is written like this: `padding-top="10px"`.
The next time the element is clicked it reads out the old value or standard settings if the `padding=` isn't present.

On https://grapesjs.com/demo-mjml.html it's is writing the same padding style but it's also reads the values correctly. 

### How can we reproduce this issue?

Step 1: Click an element in GrapeJS / mjml style manager.
Step 2: Change the the top padding
Step 3: Click on another element
Step 4: Click on previous element and check the changed padding  

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by notz** [comment]
Issue seems to be resolved in grapesjs/mjml version 0.5.6 (mautic is using 0.5.5) -> https://github.com/artf/grapesjs-mjml/pull/237

**Comment by notz** [comment]
This bug is fixed by PR #10760

**Comment by npracht** [comment]
Fixed in 4.2.0
