### ISSUE TITLE
Error when using ZohoCRM plugin

### ISSUE THREAD

**Issue by ikolubr** [mautic/mautic#10632]
### Mautic Version

4.0.2

### PHP version

7.4

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What happened?

When trying to push contacts to ZohoCRM, I get the following errors and the contact doesn;t get pushed to Zoho:

When running CRON mautic:campaigns:trigger:
```http_build_query() expects parameter 1 to be array, string given in /var/www/htdocs/vendor/guzzlehttp/guzzle/src/Client.php on line 359```

In Mautic log:
```mautic.ERROR: INTEGRATION ERROR: Zoho -  [] []```

### How can we reproduce this issue?

1. Enable and setup ZohoCRM plugin.
2. Create a contact.
3. Run the crons.

### Relevant log output

```shell
On console when running the cron (mautic:campaigns:trigger) manually:

http_build_query() expects parameter 1 to be array, string given in /var/www/htdocs/vendor/guzzlehttp/guzzle/src/Client.php on line 359

In Mautic's log:
mautic.ERROR: INTEGRATION ERROR: Zoho -  [] []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
This was fixed in https://github.com/mautic/mautic/pull/10674 so closing as a duplicate - please let us know if it's still an issue after you've updated!
