### ISSUE TITLE
Mautic email issue - Mandrill failed to authenticate

### ISSUE THREAD

**Issue by Deaton64** [mautic/mautic#10638]
### Mautic Version

4.0.0

### PHP version

7.4.25

### What browsers are you seeing the problem on?

Chrome

### What happened?

Hello,
this seems very similar to an issue reported with version 3, but no one replied to you and the issue was closed.
I have inherited a Mautic 2 installation, that I have migrated to a Mautic 3 and then to version 4.
Mostly all seems OK, except I get the error:

`[2021-11-23 15:44:22] mautic.ERROR: [MAIL ERROR] Mandrill failed to authenticate (send); a@b.com {"exception":"[object] (Swift_TransportException(code: 0): Mandrill failed to authenticate at /var/www/html/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AbstractTokenArrayTransport.php:300)"} [`

The API key is correct and the email sends, but Mautic seems to think that the email hasn't gone. The API key has an underscore in it, but I've tried a new test key with just letters and numbers and the same thing happens.

I think because of this error, Mautic is sending out lots of emails as it must believe non of the emails have been sent.

I can't see any settings on Mandrill that would prevent this from happening and I'm at a loss where to go next.

Thanks for any help you could give.

### How can we reproduce this issue?

Restored a version 2 DB into a version 3 system and upgraded to version 4.

UPDATE: I created a new Google Cloud instance, selected Mandrill as the mail transport and got the same error.

```[2021-11-24 10:51:46] mautic.ERROR: [MAIL ERROR] Mandrill failed to authenticate (send); a@b.com {"exception":"[object] (Swift_TransportException(code: 0): Mandrill failed to authenticate at /var/www/html/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AbstractTokenArrayTransport.php:300)"} []```

### Relevant log output

```shell
[2021-11-23 15:44:22] mautic.ERROR: [MAIL ERROR] Mandrill failed to authenticate (send); a@b.com {"exception":"[object] (Swift_TransportException(code: 0): Mandrill failed to authenticate at /var/www/html/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AbstractTokenArrayTransport.php:300)"} [
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for raising this bug @Deaton64 and for the detailed explanation of what you're experiencing.

Hopefully not too difficult to address, is it still persisting in the latest versions of Mautic (4.1.2 at this time)?

**Comment by mareksotak** [comment]
Still present in v4.2.2.

Although the emails are being sent, the error shows.

From Settings > Configuration > Email settings
Test connection button > Success!
Sent test email > Mandrill failed to authenticate (with the error log below)
`[2022-05-10 11:26:32] mautic.ERROR: [MAIL ERROR] Mandrill failed to authenticate (send); a@b {"exception":"[object] (Swift_TransportException(code: 0): Mandrill failed to authenticate at /www/app/bundles/EmailBundle/Swiftmailer/Transport/AbstractTokenArrayTransport.php:300)"} []`

The email is sent though. However, when using this in the Send email to specific contact, the email is sent as well, the email form remains open with the same error (Mandrill failed to authenticate), but it does not show up anywhere in the Contact details, that they were sent an email.
