### ISSUE TITLE
Browser auto-complete being triggered on fields where it's not relevant

### ISSUE THREAD

**Issue by TechBill** [mautic/mautic#10631]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

Browser autofill menu opens up masking the calendar selection which is behind the autofill menu.

Need to either remove the input box and use calendar icon to open it or disable the autocomplete on the input box using html autocomplete="off"

Honestly, I don't see a real reason to have an input box there that is editable when a calendar picker is used.

A screenshot of this is available in a thread on Mautic forum - https://forum.mautic.org/t/a-bug-with-specific-date-time-setting-autocomplete-menu-blocking-calendar-picker/21693

### How can we reproduce this issue?

Step 1: Create campaign
Step 2: Choose an action with a specific date/time setting.
Step 3: Select specific date/time setting and click on the input box next to the calendar icon (the calendar icon is not clickable itself)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by TechBill** [comment]
I can see that input box is needed to be able to edit it to more a specific minutes 

Then we just need the autocomplete off and the calendar icon clickable to open calendar picker

**Comment by TechBill** [comment]
Changing the autocomplete="false" to autocomplete="nope" seems to fix it for me

**Comment by TechBill** [comment]
basically any random string lol

**Comment by putzwasser** [comment]
My experience with that is: If you get chrome to stop auto-completing, then firefox will do it and vice-versa. I didn't test any other browsers, but I guess, this feature handled different by every browser. So, there won't be a fix (in the short/medium term). It's a mess.

Therefore, it might be best to add a button next to the input, which opens the date picker.

FWIW: Chrome opens the email address autocompletion for me for most of the backend input fields (e.g. the UTM fields). I don't know why, but it might be worth it to investigate it from an UX point of view.

**Comment by RCheesley** [comment]
Thanks for reporting this @TechBill - I can see how that would be annoying! 

Would you like to take a stab at fixing it?  I came across some docs here in my searching about this topic: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

There is a note on that page which says that browsers may ignore this if the form contains login fields, which I don't think is the case in our situation, so we should take a look and see why it's triggering the auto-complete if it's set to off.
