### ISSUE TITLE
Custom plugin EMAIL_ON_SEND first contact, $event->getTokens() is empty

### ISSUE THREAD

**Issue by ropic** [mautic/mautic#10633]
### Mautic Version

4.0.0

### PHP version

7.4.25

### What browsers are you seeing the problem on?

Not relevant

### What happened?

With custom plugin using listening event ,$event->getTokens() returns empty on first contact

### How can we reproduce this issue?

Step 1: Create custom plugin with event listener EmailEvents::EMAIL_ON_SEND
Step 2: On callback function try to read $event->getTokens()
Step 3: Send mail to multiple contacts
Step 4: Verify on first contact $event->getTokens()

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
@ropic is this still a problem with 4.1.2?
