### ISSUE TITLE
Error occurs when adding Custom Permissions for Role

### ISSUE THREAD

**Issue by thaopv** [mautic/mautic#1064]
I created HelloWorld plugin with custome permission as sample in https://developer.mautic.org/#creating-custom-permissions
But when I login as administrator, create new Role, then add custome permission, error occurs

Here is the log's content
[2015-10-26 09:47:50] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Permission class not found for HelloWorldBundle!" at C:\xampp\htdocs\mautic\app\bundles\CoreBundle\Security\Permissions\CorePermissions.php line 151 {"exception":"[object] (InvalidArgumentException(code: 0): Permission class not found for HelloWorldBundle! at C:\\xampp\\htdocs\\mautic\\app\\bundles\\CoreBundle\\Security\\Permissions\\CorePermissions.php:151)"} []

**Comment by alanhartless** [comment]
Can you post the code to your Permission file? You also might want to jump onto the public #dev channel on slack.  https://mautic.org/slack.

**Comment by thaopv** [comment]
This is content of HelloWorldPermissions.php file

<?php
// addons/HelloWorldBundle/Security/Permissions/HelloWorldPermissions.php

namespace MauticPlugin\HelloWorldBundle\Security\Permissions;

use Symfony\Component\Form\FormBuilderInterface;
use Mautic\CoreBundle\Security\Permissions\AbstractPermissions;

/**
 * Class HelloWorldPermissions
 */
class HelloWorldPermissions extends AbstractPermissions
{

    /**
     * Define available permissions
     *
     * @param $params
     */
    public function __construct($params)
    {
        parent::__construct($params);

        // Add standard category permissions
       	 $this->addStandardPermissions('categories');
    }

    /**
     * Append the permission form fields to the Role form
     *
     * @param FormBuilderInterface $builder
     * @param array                $options
     * @param array                $data
     */
    public function buildForm(FormBuilderInterface &$builder, array $options, array $data)
    {
        // Add standard category form fields
         $this->addStandardFormFields('helloWorld', 'categories', $builder, $data);

    }

    /**
     * Permission set identifier; should be bundleName
     * 
     * @return string
     */
    public function getName()
    {
        return 'helloWorld';
    }
}

**Comment by thaopv** [comment]
I think in file CorePermissions.php
Method public function generatePermissions(array $permissions)
Line of code: $class = $this->getPermissionObject($bundle);
You should check CoreBundle or PluginBundle

**Comment by escopecz** [comment]
@thaopv can you check if you're having this issue with Mautic 1.2.3 as well? I think this PR might fix it: https://github.com/mautic/mautic/pull/1098

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to comment with any update and we can open it again.
