### ISSUE TITLE
Uncaught Error: Unable to parse color from string (libraries.js)

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#10642]
### Mautic Version

3.3.4

### PHP version

7.3

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What happened?

When I changed the PHP timezone and time settings.

Then when I went to the dashboard panel and where it contains charts, it happens again.
Images below show what happens:

![Screenshot_1](https://user-images.githubusercontent.com/94984546/143286248-c97b468c-81ea-49da-b546-28a36c6a3f5a.png)
![Screenshot_2](https://user-images.githubusercontent.com/94984546/143286252-e5bd2bae-ce8c-4ed5-a00b-9ab3b1c148a3.png)

### How can we reproduce this issue?

When I changed the PHP timezone and time settings.

Regional settings > pt_BR | America/Sao_Paulo (UTC -03:00)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by ghost** [comment]
I imported 18 thousand contacts too, but until then everything was normal. With the color chart and etc.

**Comment by ghost** [comment]
Going back to the settings in PHP from the en_US locale got back to normal.

Config em server:
![Screenshot_3](https://user-images.githubusercontent.com/94984546/143375977-2e91af76-33d0-483b-a967-0e1f91893c0b.png)

Dashboard:
![Screenshot_4](https://user-images.githubusercontent.com/94984546/143376000-2e8e1014-97f5-4b09-9e29-33c53460ff21.png)

Dashboard + console:
![Screenshot_5](https://user-images.githubusercontent.com/94984546/143376043-2a7d8392-aea5-4390-84f6-7a97c8d909f1.png)

I believe that changing to the pt_BR locale default it does not recommence the , but yes .

The solution would be to put a replace to consider always. (period) or identify the location and treat one by one?

**Comment by RCheesley** [comment]
He @flippaus - is this still a problem? If so, does it still happen with 4.1.2?

Sorry for the delay in getting back to you on this issue.
