### ISSUE TITLE
Mautic keeps crashing with 150k contacts on a powerful machine

### ISSUE THREAD

**Issue by Dylan-86** [mautic/mautic#10648]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Mautic keeps crashing.

We have approx 150k contacts and in these days we should be sending Black Friday's deals. 
A mess. 
Messages scheduled to be sent at 8 AM local time on Wednesday arrived 15 hours later.
Mautic has already crashed 3 times in 2 days. 

We need help. Paid. 
We need a serious person, with enough experience with Mautic configuration, that can assist us with the following things:
1. Make sure that Mautic does not crash. We are open to change our server but we want to know at this point the exact requirements for a machine that can support Mautic. Right now we are using a powerful machine already, but it seems that it's not enough.
2. Make sure that the emails are properly configured to arrive at the proper time. We are using Amazon SES and we know the per-second limitations but still the timing doesn't make sense.
3. Clear up the database. We did that already a couple of weeks ago, reducing from 11 GB to 5 GB, but I am pretty sure that it's still full of rubbish data that we do not need.

If ANY of this community can help, please reach out to me to discuss a dedicated consulting agreement for this one-time assistance.

Thanks,
D

### How can we reproduce this issue?

Step 1: Have at least 150k contacts on Mautic

Step2: schedule emails to be sent, 150k day 1, 100k day 2, 70k day 3.

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by nikolaknezeviccom** [comment]
You probably already fixed or figured out this, but in case you did not here are some finding from my testing.
Mautic 4.1.0 PHP 7.4

Seems that any segment or any campaign as well as import is done without "resource thinking". I managed to run 700k contacts on Mautic 4.1 with no problem but what I noticed that PHP scripts that run via cron do not clear memory. What that means? 
Well in short more data you have more memory is needed for your php. It relates directly to number of contacts processed. In some cases when creation of segments or camping things might fail with php memory error msg but will continue next time your cron runs from the place where it is hanged. For imports for example you have to disable the file in import history once it fails and click again to enable and it will pick up where it was left.
I will assume that you have a problem with memory as this is the thing that "crashes" or stops your Mautic. Try increasing PHP memory allocation (PS I have mine at 8GB and it still dies after X number of contacts). My test shows that around 4GB of php memory is required for around 200k contacts. Try increasing php memory and see if it works (make sure it is increased for PHP version you are using via cron).

**Comment by renatocron** [comment]
@nikolaknezeviccom how can the PHP keep using memory after the each crontab execution? 

If this is true, maybe have separated instances for crontab and the 'real' mautic server, for exemple, starting a new container for each time a cron job needs to run, or at least keep it spare and restart it from the host hourly so php has a chance to free some memory.

Are you using opcache? 
I only have a ~ 10k contacts, so I can't really tell the difference.

**Comment by npracht** [comment]
Hi @Dylan-86 ! **I'll close the issue, that is a configuration issue.**

We are running 500 instances with up to million contacts and this works well.
I'm glad to help you, you can reach me on slack or find my contact info on https://github.com/npracht
