### ISSUE TITLE
Email Generator Bug Mautic 4.0.2

### ISSUE THREAD

**Issue by xefxipi** [mautic/mautic#10650]
### Mautic Version

4.0.0

### PHP version

7.4.25

### What browsers are you seeing the problem on?

Chrome

### What happened?

I have a probleme to creat or generate an email
Trying to access array offset on value of type bool - in file /home/c1738483c/public_html/app/app/bundles/EmailBundle/Entity/StatRepository.php - at line 525 {"query":"[object] (Doctrine\\DBAL\\Query\\QueryBuilder: SELECT count(es.id) as sent, count(CASE WHEN es.is_read THEN 1 ELSE null END) as \"read\", count(CASE WHEN es.is_failed THEN 1 ELSE null END) as failed FROM maupp_email_stats es LEFT JOIN maupp_emails e ON e.id = es.email_id WHERE (es.date_sent IS NULL OR (es.date_sent BETWEEN :dateFrom AND :dateTo)) AND (e.is_published = :i0ceispublished) GROUP BY es.id)","results":false} []

### How can we reproduce this issue?

Step 1: Once connected go to email
Step 2: New
Step 3 : Template
Step 4  :Create your email template
Step 5 : Apply 
Step 6 : This takes us back to the beginning

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there,

Does this persist in 4.1.2? We pushed quite a lot of bug fixes just recently.  If it's still an issue please can you let us know?

Thanks!
