### ISSUE TITLE
Create new form via "clone" -> one of other existing forms is overwritten (original form stays OK)

### ISSUE THREAD

**Issue by Jakub087** [mautic/mautic#1065]
Hi,

when I create new FORM via cloning existing one, then:

- existing one (original) -  stays OK 
- new one (cloned one) - overwrite one of another forms!

When I create new FORM from scratch, then everything is OK

**Comment by gpassarelli** [comment]
I was having this issue as well, but I didn't know what was causing, so +1

**Comment by alanhartless** [comment]
I'm not able to reproduce this one.

Does it happen consistently with multiple forms or does it seem unique to certain forms? If certain forms, are you able to figure out what the trigger might be or maybe give some details on the form setup so we can try to reproduce.

Thanks!

**Comment by Jakub087** [comment]
I tried it after update to v 1.2.2 and I works fine...
