### ISSUE TITLE
Campaign, can not select existing text messages when creating a text message action

### ISSUE THREAD

**Issue by FKrafft** [mautic/mautic#10652]
### Mautic Version

4.0.0

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Chrome

### What happened?
Running 4.0.2

I was creating a campaign for text messages. 
Existing text messages do not show in the selector within the campaign builder.
You need to create a new text message for each campaign text message action.

![TextMessages-Empty](https://user-images.githubusercontent.com/5633488/143779905-45d6a716-fed7-439d-8362-d98331ea187b.png)

### How can we reproduce this issue?

When sending text messages you should be able to select a specific text message for your campaign action but this is not possible.

Step 1: Create a campaign.
Step 2: Launch campaign builder
Step 3: Choose contact segments
Step 4: Select segment
Step 5: Create action -> Text message

Step 6: BUG: Now you can not select existing text messages. It is empty even if you have created text messages before. 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi @FKrafft are you sure your SMS are enabled.
Can you show a screenshot of your text message list ?
Thanks.
