### ISSUE TITLE
Ok but is there a event listener for email events occurring from an external system? because its not that far fetch to require external event data as this could help qualify leads

### ISSUE THREAD

**Issue by ivan006** [mautic/mautic#10664]
### Mautic Version

4.0.0

### PHP version

7.3.27

### What browsers are you seeing the problem on?

Firefox

### What happened?

Ok but is there a event listener for email events occurring from an external system? because its not that far fetch to require external event data as this could help qualify leads

### How can we reproduce this issue?

Step 1: Ok but is there a event listener for email events occurring from an external system? because its not that far fetch to require external event data as this could help qualify leads

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
I'm sorry i don't understand how we could help you.
