### ISSUE TITLE
Reports doesn't show dynamic filters on M4

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#10676]
### Mautic Version

4.0.0

### PHP version

7.4.24

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

I made new report with Data Source contact and I for example choose filter by Owner and set up this as dynamic. On report page I don't see my filter. Only date range.

### How can we reproduce this issue?

Step 1: Make some report
Step 2 Make new filter and set up it as Dynamic
Step 3: Go to report main page and expand filters. 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, PHP 8.0 is actually not supported with M4.0.0
Are you sure you have PHP 8.0 ?

**Comment by ghost** [comment]
Errata: I use PHP 7.4.24 with M4.1

**Comment by sdragnev** [comment]
I have the same issue with Mautic 4.0.1 and the 4.x branch, and PHP 7.4.

**Comment by ghost** [comment]
Is any chance to fix it in the next update?

**Comment by kuzmany** [comment]
Fix on 4.1.2 with https://github.com/mautic/mautic/pull/10716
Need re-save report.
