### ISSUE TITLE
Treating an array as a string

### ISSUE THREAD

**Issue by TonyBogdanov** [mautic/mautic#10670]
### Mautic Version

4.0.0

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The code at (and after) this line: https://github.com/mautic/mautic/blob/5975231722cfde8bdad783b373c70ad20333db37/app/bundles/PluginBundle/EventListener/IntegrationSubscriber.php#L90

is assuming that the result of `$response->getHeaders()['Content-Type']` is a string, however, that is not the case. As per the specification and comments of `Psr\Http\Message\MessageInterface::getHeaders()` - this method returns an array of arrays of strings. This is so, because an HTTP header *may* include multiple values.

The same assumption is made multiple times for the rest of the code in `Mautic\PluginBundle\EventListener\IntegrationSubscriber::onResponse()` resulting in a PHP Warning.

### How can we reproduce this issue?

Step 1: Configure HubSpot integration.
Step 2: Setup a campaign to push contacts from a segment to the integration.
Step 3: Setup a segment to match a number of contacts.
Step 4: Add a contact to be matched by the above segment.
Step 5: Run `./console mautic:integration:fetchleads -i Hubspot`.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Does any of these PR fix your issue ?
https://github.com/mautic/mautic/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+hubspot

**Comment by TonyBogdanov** [comment]
@npracht I made a mistake in the description of the issue, just edited Step 5.

That being said, I can't really say if any of the PR fix this particular issue, though looking at the code, I think #10598 is exactly fixing this. Either way, it's no longer present as an issue in 4.1.0 or 4.1.1.
