### ISSUE TITLE
MJML full-width not functioning as intended.

### ISSUE THREAD

**Issue by TechBill** [mautic/mautic#10672]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome, Not relevant

### What happened?

full-width="full-width" string is supposed to make mjml wrapper or section background a full width.  This string seems not functional in 4.0.1

More info about full-width on MJML document - https://documentation.mjml.io/#mj-section

### How can we reproduce this issue?

Drop in MJML section or wrapper.
Add full-width="full-width" to section or wrapper attribute and notice it still fixed at 600px 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
I'll mark this as an enhancement.

**Comment by TechBill** [comment]
I would like to add that the full-width does seems to work when "emailed out" however in editor it still show as fixed width. 

You would just need to ignore the fixed width in editor knowing it set to full and send yourself a test email to make sure it's a full width before publishing it.  

The issue is probably the editor itself not the MJML .
