### ISSUE TITLE
Sort dependent fields in form

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#10687]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

All fields which are depend of parent field have got this same "field_order" in database. This makes problems with sort questions. Now this is randomize. Only way to fix this problem is changing "field_order" in the database and don't changing Form in mautic after this.

Problem occurs on M4.1

### How can we reproduce this issue?

Step 1: Make form with a lot of depend fields
Step 2: Check sort these fields on front-end
Step 3: Check "field_order" depends fields in database.

### Relevant log output

```shell
No logs.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by kuzmany** [comment]
I am working on it

**Comment by npracht** [comment]
This is regression of Mautic 4. It was working before.

**Comment by kuzmany** [comment]
@npracht I don't think so, I saw it on M3 months ago. But It happen in very specific situations

**Comment by kuzmany** [comment]
@biggala2310 can you test this PR https://github.com/mautic/mautic/pull/10801 ?

**Comment by kuzmany** [comment]
@biggala2310 really could help your testing on this fix https://github.com/mautic/mautic/pull/10801

**Comment by ghost** [comment]
@kuzmany Hello, I'm sorry for waiting. I tested it on gitpod. On preview sort of depend fields looks better. It is sorted by creation order which may be accept. Still I can't sort it manually. Unfortunelly on gitpod I can't find database to check field_order. So I'm not 100% sure, that problem is fixed.

**Comment by kuzmany** [comment]
Can you share what structure of form before make the issue? Because it's hard to reproduce.

**Comment by ghost** [comment]
I've got something like this:
![image](https://user-images.githubusercontent.com/56032973/153625489-7c6da654-97c1-4215-acf7-ef52b5051cf6.png)
But you see there form after save. I made all depends fields in order: first and last name, e-mail addres, career stage. But mautic add to any field this same field_order, so after save we see random order (second field for first and last name is on last position though I made this field as fourth).
This is my second form with this problem. I've made update to 4.12 before make this.

**Comment by ghost** [comment]
Here I've got exactly this same form after adding all of members fields:
![image](https://user-images.githubusercontent.com/56032973/153630017-0cf50f73-16dd-4eb8-ad06-3d98ca5db07f.png)
All member's fields made In this order: 1. first and last name, 2. e-mail, 3. select, save form, and make next fields for next member.

What I will do with this? I change fields order in database and I will not edit the form in mautic after that.
