### ISSUE TITLE
"Custom headers" not working when send mail through "SendGrid API"

### ISSUE THREAD

**Issue by renatocron** [mautic/mautic#10688]
Hello! 

### Mautic Version

4.1.0 - upgraed from docker 4.0

### PHP version

7.4.25

I have a bug report and a few questions about Mautic.

# Bug Report

I was trying to set X-FOOBAR header to configuring some options but this field is not being sent. 
![image](https://user-images.githubusercontent.com/1919076/146202959-b26f6ca8-184e-48f3-9dc1-06ced10352cd.png)
This customer-header is supposed to be included when I sent e-mails via the contact "Send Mail"

And these headers set on the Advanced on Campaign
![image](https://user-images.githubusercontent.com/1919076/146204145-ca9892d9-b9e3-448e-89c9-88f6548e5493.png)
(Name/From/Reply To/Plain text version is working)

Header `list-unsubscribe` **is also absent** on the sent mails via SendGrid API.

When I configured to use either "Sendgrid - SMTP" or "Other SMTP Server" [SSL+Login] the custom headers and list-unsubscribe is working.

![image](https://user-images.githubusercontent.com/1919076/146206640-60acf1c6-14a4-4f01-83a7-948fce6964d4.png)

# Questions to the community/developers

1. Which is the driver is the recommended way to send mail via Mautic ?
I was reading other issues, and I think that each driver behavior a little different (rate-limits, etc).
Is there any reason Mautic implemented sendgrid/amazon via SDK/API instead of SMTP? Is it faster than using SMTP?
Should I setup postfix/MTA to queue the emails from Mautic?

2. Why Custom-Header from settings are only send on system emails?
In settings, it explains where custom-headers are sent: ```...This includes password reset emails, emails to Mautic users, form post results, directly composed email to contacts, etc. If custom headers are required for an Email (used in campaigns or broadcasts), set customer headers in the Advanced tab of the Email.```
 **Why was this designed like that? Shouldn't the headers at least be copied when new Email Campaigns are added (like the "Mailer is owner" setting is)?**
As a system-admin I don't want to let mautic's users to control which custom-header he add or remove in each email (or at least, to not remove the ones set by the system-admin)
If anyone know the reason "Mautic Email" was removed from settings custom-header, and if I can open an PR to include a new boolean setting (eg: 'always-keep-custom-header') to make those headers always be sent on the all emails.
Is this the 'right' way to tackle this problem? Do I need to really need to change core to implement this, or the plugin is the right approach?
If a new setting okay, can it just exists on the settings.php file and not added in the web?

3. If manage to fix the Mautic to include headers, can I just open an PR this repo?
I'm not full time PHP developer, so I'm not used to the culture and tools. 
I managed include extra headers (hardcoded) using this file:
https://github.com/mautic/mautic/blob/4.x/app/bundles/EmailBundle/Swiftmailer/SendGrid/Mail/SendGridMailMetadata.php#L23
Is this ./app/bundles/ something I could send PR to mautic or is another repository?

**Thank you for reading until here**

### How can we reproduce this issue?

Step 1: Use "SendGrid API" as MTA
Step 2: Configure Custom Header, either on the Settings or in the Email Campaign
Step 3: If using Settings Custom-Headers, send an e-mail via "Send Mail" contact
Step 3: If using Settings Email Campaign, send an e-mail via "Email Campaign" to an segment, configuring the Custom-Header in the "Advanced" area.

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by renatocron** [comment]
UPDATE

Okay, Sendgrid API supports for BatchSend, [this post from 2010 says STMP is preferred if batch is supported, even suggest using an MTA to queue mails](https://sendgrid.com/blog/which-protocol-should-i-use-to-send-email-smtp-or-rest/) but [this other post from 2016 says WEB API is faster](https://sendgrid.com/blog/web-api-or-smtp-relay-how-should-you-send-your-mail/) 

So this is no longer a question.

I saw that some transports firing some events are others are not, eg: `beforeSendPerformed` is sent for AmazonAPI, Spool, AbstractTokenHttp (used by Mandrill) and Sparkpost. 

Maybe maybe this event can only be used if batch is not used on the implementation, but if that was the case, we should have a custom Swift_SmtpTransport that fires yet on ::send

Anyway, back to the headers issue, I'll try to patch SendGrid API to call getHeaders and add then working.
I maybe also sent an extra option to configure extra parameters to sendgrid, like `X-SES-CONFIGURATION-SET` was done on AmazonAPI. If sendgrids ignores `X-SMTP-API` header when calling directly over API, then this should be necessary to set up categories and unique_args

@alanhartless commited 4 years ago https://github.com/mautic/mautic/commit/954df41ca5cbd611331faba32acd8b8c97d21ae0 the comment that the mautic is purposively ignoring system headers if using an Email entity, I would like to know why, and if I can create another boolean to overwrite this behavior

Maybe this 'always-header' config is not necessary, I can use `mailer_custom_headers` that is present on the config.php (but not the interface) and this will be kept for all e-mails.

I'll keep updating this thread as I do more tests.

**Comment by renatocron** [comment]
UPDATE

- `X-SMTPAPI` header do not work (is removed, but ignored by the SendGrid API)
- `mailer_custom_headers`  on config is shown on the interface (I din't got it before because github loaded this file minimized on the commit page)

I will include a new setting for configuring CustomArg and Category when using "SendGrid API", is not that hard!

**Comment by mabumusa1** [comment]
Keep this opened, it has interesting questions that we cover in Mautic 5

**Comment by renatocron** [comment]
Just to keep in mind:

I tried to set up and use pure STMP driver and use the header `X-SMTPAPI` to set the parameters (that works), but then the Sendgrid API webhook for bounces/spam reports stopped working, because the driver is not loaded/active

It could be useful in some scenarios to have all webhook/integrations working when possible, even if the driver is not currently selected as the current sending engine
