### ISSUE TITLE
Segment filter date equals today is not working

### ISSUE THREAD

**Issue by alexhammerschmied** [mautic/mautic#10685]
### Mautic Version

4.1.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The segment filter with date is not behaving properly.
When I add the specific date of today and make a filter like:
"date equals specific date (i.e. 2021-12-14)" it works
"date equals today" doesn't work
but 
"date less than or equal today" is working. 
also 
"date greater than or equal today" is working.
so I could use two filters to achieve my goal but that's not the point. 
Somehow the dynamic date "today" doesn't get validated by the segment filter 
https://www.loom.com/share/d883734977c4448b9f52778842120668

### How can we reproduce this issue?

Step 1: create a new segment
Step 2: Add a filter with a date field to check and put logic to "equals" and insert "today" into the date field of the filter.
Step 3: Add the date of today into the date field in the contact
Step 4: run cronjob mautic:segment:update
Step 5: the contact was NOT added to the segment (but it should)

### Relevant log output

```shell
no log errors
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by oltmanns-leuchtfeuer** [comment]
Hi Alex,

i could not reproduce your error. My test-segment had a filter on "Date Last Active" equals "today" and my test contact was correctly added to that segment.

**Comment by ghost** [comment]
I have got this same problem with M4.1. System convert me "today" to const date like "2021-12-16 00:00" when I saved new segment.

**Comment by npracht** [comment]
@kuzmany you see something about this ? I think you're one of the person introducing this feature.

**Comment by kuzmany** [comment]
> System convert me "today" to const date like "2021-12-16 00:00" when I saved new segment.

If happend this you should try reload assets: `php bin/console m:a:g`

It works for me on last version of Mautic

![image](https://user-images.githubusercontent.com/462477/147599983-e5aac554-ab76-4ae2-95d0-f1bfbff92578.png)

**Comment by kuzmany** [comment]
Rebuilding works for me too. Cannot reproduce

**Comment by kuzmany** [comment]
This should fixed it https://github.com/mautic/mautic/pull/9784
Can you test it?
