### ISSUE TITLE
Multiple Form Instances Validation Issue (same form) 

### ISSUE THREAD

**Issue by BPCreative** [mautic/mautic#10694]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

I am having a similar issue...

I have 2 copies of the same form on the same page.  There is one embedded in the bottom section.  The other instance comes up when the green "Get Started" buttons are clicked (popup/modal). 

The popup instance comes later in the code, so only the one built into the page is validating.  When the submit button is clicked on the popup instance, the page passes a validation message into the URL, which triggers it to send the user to the home page. 

That looks something like this:  https://domain.com/?mauticError=Errors%3A%3Cbr%20%2F%3E%3Col%3E%3Cli%3EPlease%20fill%20out%20your%20first%20name.%3C%2Fli%3E%3Cli%3EPlease%20fill%20out%20your%20last%20name.%3C%2Fli%3E%3Cli%3EPlease%20fill%20out%20your%20email.%3C%2Fli%3E%3Cli%3EPlease%20fill%20out%20your%20phone%20number.%3C%2Fli%3E%3Cli%3EPlease%20select%20the%20option%20that%20best%20matches%20you.%3C%2Fli%3E%3C%2Fol%3E#emr001__se

Here is the link to the page:  http://b-px.xyz//mautic-form-issue/4238

Any ideas what's causing this?

### How can we reproduce this issue?

Step 1:  Add the same form into a page twice.
Step 2:  Click the button without filling out any of the fields.

Or you can just visit the link and look at the problem there.  Click one of the "Get Started" buttons.

### Relevant log output

```shell
n/a
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
I don't know if this issue has been re-introduced : https://github.com/mautic/mautic/pull/8935. Maybe having a look around this part of the code.

**Comment by kuzmany** [comment]
This issue @spka try fixed it times ago https://github.com/mautic/mautic/pull/6761 but not finished yet.
