### ISSUE TITLE
Updating a theme doesn't work, it need hard clear cache

### ISSUE THREAD

**Issue by andres-asm** [mautic/mautic#10704]
### Mautic Version

4.1.1

### PHP version

8.0.13

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I built a new theme (legacy, we have some limitations with grapejs) and I missed adding data-slot tags to some sections, so it wasn't editable.

So I fixed the theme, reinstalled it without changing anything else, but the sections are still not editable.
I can workaround the issue by changing the theme name, then uploading it again, it's a different theme but now it works.

I even diffed the directory trees of both themes and other than the name change they are identical:

```diff
user@host:/srv/web-development/sites/mautic-test$ diff -r themes/cc_holiday themes/cc_holiday_v2
diff -r themes/cc_holiday/config.json themes/cc_holiday_v2/config.json
2c2
<   "name": "CC Holiday",
---
>   "name": "CC Holiday v2",
user@host:/srv/web-development/sites/mautic-test$
```

### How can we reproduce this issue?

Step 1: create a theme, intentinally skip data-containers and data-slots
![image](https://user-images.githubusercontent.com/1721040/147010365-c5ce9f17-260f-40d0-88e7-005592ad9ba4.png)
Step 2: create an email, anything will do, you will see that the sections are not editable
Step 3: fix the intentional mistake, update the theme with the same name
Step 4: create an email again, the same thing happens

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by andres-asm** [comment]
I tried clearing the cache per the instructions here: https://docs.mautic.org/en/troubleshooting
Didn't fix anything

May be related:
https://github.com/mautic/mautic/issues/6486

**Comment by andres-asm** [comment]
I even tried deleting the theme and uploading it again, didn't work.

**Comment by andres-asm** [comment]
Also tried restarting PHP, rebooting my VM, and a private browser window... this is crazy!

**Comment by andres-asm** [comment]
This procedure finally worked:
- Remove the theme from settings/themes
- Create new email, confirm that the theme is not there
- Clear cache (rm -rf var/cache/*)
- Install the theme again

Then... and only then it worked... this makes no sense whatsoever to me

**Comment by npracht** [comment]
Okay it needs a hard clear cache. I'll point this as an issue.

**Comment by andres-asm** [comment]
Yeah seems like it.
In some cases it works, when there are small changes... but in other cases we have to do this whole dance

**Comment by andres-asm** [comment]
why was this closed? it isn't fixed

**Comment by zietbukuel** [comment]
I also have this issue, what I do is switch to another theme back and forth, and then my changes are reflected, sometimes I also need to change the folder name or clear mautic's cache, this is insane... Also, this isn't fixed so why close this issue?

**Comment by andres-asm** [comment]
it seems that it's more important to them to have a small number of open issues than to actually have people reporting them

**Comment by dcrousset** [comment]
With mautic 5, still not working as it should.

I tried everything from this issue, to no avail.  The only thing that worked for me was to have a different name for the zip file to install : 
1 - create updated theme with <unique filename>.zip
2 - In mautic themes, remove the existing theme you want to replace
3 - then install the updated theme

Good luck :o)
