### ISSUE TITLE
Segment filter with custom fields doesn't work

### ISSUE THREAD

**Issue by alfredoct96** [mautic/mautic#10703]
### Mautic Version

4.0.0

### PHP version

7.4.9

### What happened?

Segment filter seem's not work with custom fields.
I added a custom field "Source" with type text and group Core, for Contacts.
Then i added a segment with a filter for field "Source" with comparator "equals" string "Platform".

Added contact with custom field "Source" populated with string "Platform", then call php bin/console mautic:segments:update.
The segment will not be populated

### How can we reproduce this issue?

Step 1: Add custom field with type "text" and group "Core"
Step 2: Add contact with this custom field populated
Step 3: Add segment with filter on this custom field, with comparator "equals"
Step 4: call php bin/console mautic:segments:update

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by MadlenF** [comment]
Hi Alfred, I could reproduce the behavior as described above in Mautic 4.1.1. However, if I just change the name of the custom field, everything works perfectly. In my opinion it is the word "Source" Mautic doesn't like in this case.

**Comment by alfredoct96** [comment]
> Hi Alfred, I could reproduce the behavior as described above in Mautic 4.1.1. However, if I just change the name of the custom field, everything works perfectly. In my opinion it is the word "Source" Mautic doesn't like in this case.

Yes, i saw it yesterdey.
With this filter segment take all the leads that have page hit on page with this source, is it a normal behavior?

**Comment by npracht** [comment]
Hi there, yes some keywords are reserved. Listed here : https://github.com/mautic/mautic/issues/9647
I close the issue here and let's follow up on the other issue.
