### ISSUE TITLE
Mautic deletes default content from Dynamic Content block inner e-mail in classic editor

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#10714]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Because GrapesJS works really bad on M4, I tried use default builder in Mautic. Unfortunately, it deletes my default content from dynamic content block.

### How can we reproduce this issue?

Step 1: Turn off GrapesJS builder
Step 2: Make e-mail with dynamic content block and add some value to default content
Step 3: Save e-mail and check your template.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by markusrock** [comment]
I'd say this is the same issue as https://github.com/mautic/mautic/issues/10540

**Comment by RCheesley** [comment]
Closing in favour of existing issue #10540 please take the discussion over there folks! :)
