### ISSUE TITLE
Leads in the contact tab of the campaign are not loaded

### ISSUE THREAD

**Issue by tomekkowalczyk** [mautic/mautic#10718]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

![image](https://user-images.githubusercontent.com/39382654/147820673-f8820549-f2c5-4380-b65d-80848e17fcd0.png)
Switching to the contacts tab in the campaign does not show contacts, but the loader. I did not notice any errors in the console and application logs

### How can we reproduce this issue?

1. Create campaigns
2. Go to the campaign view in the contact tab

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by anthienvu** [comment]
I meet the same problem with version 4.1.1.

**Comment by RCheesley** [comment]
Thanks for raising this @tomekkowalczyk and for confirming the issue @anthienvu - hopefully a quick fix!

Can you double check you have the latest assets built by using the command:

`bin/console mautic:assets:generate`

Does this make any difference?

**Comment by anthienvu** [comment]
> Thanks for raising this @tomekkowalczyk and for confirming the issue @anthienvu - hopefully a quick fix!
> 
> Can you double check you have the latest assets built by using the command:
> 
> `bin/console mautic:assets:generate`
> 
> Does this make any difference?

I can see the contacts once only if clicking the contact tab right after saved. So I have to save many times to review the contacts. It is not good.
