### ISSUE TITLE
"Import from an existing template" on contact card doesn't work when GrapesJS is off

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#10715]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

"Import from an existing template" on contact card doesn't work when GrapesJS is off. The window is still loading.

### How can we reproduce this issue?

Step 1: Make some e-mail template in any e-mail builder
Step 2: Turn off GrapesJS
Step 3: Click "send e-mail" on contact card and try choose one of existing templates. 

### Relevant log output

```shell
no logs
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @biggala2310 can you confirm that you've cleared your cache and reloaded your browser after you've turned off GrapesJS?

**Comment by medsun88** [comment]
@RCheesley 
Problem persist after clearing Cache and Chrome cache
