### ISSUE TITLE
CSS from GrapesJS doesn't work on Gmail

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#10713]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Gmail doesn't respect CSS which is added by GrapesJS. CSS works only on browser.

I checked it on my old instance with M3.3.4 Emails from GrapeJS looks good on Gmail. I checked a difference between email output in M4.1 and M3.3.4. IMHO this bug is caused by moving <style> from <head> to end of </body>.

### How can we reproduce this issue?

Step 1: Make some e-mail in GrapesJS or add HTML and CSS code to your e-mail template in GrapesJS builder.
Step 2: Send e-mail to some Gmail client.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
Afaik GrapeJS is converting everything into HTML. Thus the embedded MJML compiler is causing the issue. Probably that's not an Mautic issue then, but an GrapeJS or even MJML issue.

@RCheesley how are third party issues be handled? Is there a board that keeps an eye on this?

**Comment by shahriared** [comment]
Same issue!

**Comment by webpaldev** [comment]
I have the same issue,

**Comment by stevedrobinson** [comment]
I didn't see this issue when I posted [Issue 10769](https://github.com/mautic/mautic/issues/10769). I think this is a symptom of the larger problem explained there, assuming @dsp76 and @shahriared are both referring to using the code mode with HTML and not MJML/template-based emails.

**Comment by RCheesley** [comment]
OK let's take this discussion over to #10769 which has a lot more detail, to avoid duplication.

**Comment by dsp76** [comment]
@RCheesley I think both issues are two different things. This issue refers - as I see it - to GrapeJS not properly converting MJML into HTML. We experienced the same and in the past fixed the generated HTML. But by using MJML and letting GrapeJS do its job, there is no way to fix the automatically generated HTML.

So my question still open - how will we keep track on third party issues, that has also relevance for Mautic users?

**Comment by drimlike** [comment]
Same issue here. GrapesJS design made in Mautic aren't rendering the CSS in Gmail.

**Comment by dsp76** [comment]
@drimlike Aren't rendering at all? What exactly is broken?

By the way - these are current Gmail CSS related issues with MJML (used by GrapeJS):
https://github.com/mjmlio/mjml/issues?q=is%3Aissue+gmail+css+is%3Aopen

**Comment by drimlike** [comment]
@dsp76 thanks for your reply!
When sending an email from Mautic using the GrapeJS plugin, the emails received in Gmail lack any formatting or applied CSS. They appear as plain text, as if all HTML and CSS elements have been removed, resulting in an email composed solely of text.

And none of the current Gmail CSS related issues with MJML are matching with this specific issue.

cc @escopecz

**Comment by dsp76** [comment]
We can't confirm it with the description. We are fine with sending Mails from GrapeJS Editor to Gmail.
There is one specific thing, that you need inline styling with gmail - it ignores classes. Maybe this helps.
But please move the discussion to the forum.mautic.org ... its not a general bug.
