### ISSUE TITLE
Bool can no longer be X only Yes and No

### ISSUE THREAD

**Issue by jensolsson** [mautic/mautic#10711]
### Mautic Version

4.0.0

### PHP version

7.4.20

### What browsers are you seeing the problem on?

Safari (but probably every browser)

### What happened?

We rely on that Bool can also be null for custom fields. We use this when a specific field is not relevant for a specific contact. When the contact is initially created it is actually NULL, but when it is set it seem to be no way to unset it. Is this an intended change or a bug?

In < 4.0.0 there was these choices for bool fields:
X | No | Yes

Now in >= 4.0.0 there is only
No | Yes

So once set it cannot be reset. We also noticed that it is no longer possible to reset using the REST API.

### How can we reproduce this issue?

Step 1: Create a field with bool type
Step 2: Set it to Yes or No
Step 3: Try to clear it

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

[2021-12-29 corrected versions above]

**Comment by jensolsson** [comment]
Could this be related to #10415 @kuzmany? I couldn't see anything suspicios in the commit but seem like this change is in the same area.

**Comment by patrykgruszka** [comment]
This issue is related to #10669 and PR #9931.

**Comment by jensolsson** [comment]
@patrykgruszka are you sure?

Here are images from contact edit in pre 4.0.0 and 4.0.0

So it seem to be more than the API that is affected, also the GUI
pre 4.0.0:
![Screenshot 2021-12-29 at 10 41 19](https://user-images.githubusercontent.com/1985582/147650074-c692ed3e-0cf3-46d6-b3c1-f6d1ff522bd7.png)
4.0.0+
![Screenshot 2021-12-29 at 10 55 32](https://user-images.githubusercontent.com/1985582/147650070-f537e62f-1c86-4146-bc91-99404edafca6.png)

**Comment by kuzmany** [comment]
Confirm. This is issue. Before you were able to cancel value by button X

**Comment by patrykgruszka** [comment]
The type casting in the #9931 `app/bundles/CoreBundle/Form/Type/YesNoButtonGroupType.php:57` makes the neutral option disappear and i can't figure out why. When you change it back to `int` then the X option is back.

**Comment by jensolsson** [comment]
@patrykgruszka I have now tried to narrow down the commit that causes it and it seem to be somewhere between 1825a8937a0478d9d9bf3d8fc9313d21e6717b9c and 7065d36d9285eca5d5efd4a6237f057f02e6a6e5

**Comment by patrykgruszka** [comment]
@jensolsson I've tried to revert the #10415 but this has not affected the boolean option in my case. I think it's the f409dbe8fe31c932a4c6fe2931dd186a596eb0e0.

**Comment by jensolsson** [comment]
@patrykgruszka do I understand correctly the main issue is that the checkbox type in symfony requires true / false only and the indeterminate / null state is no longer possible in Symfony. Maybe due to an upgraded Symfony version? 

If so maybe the old X | No | Yes checkbox should be implemented with something other than CheckboxType field? Maybe EnumType can be used instead and styled in the same way? Unfortunately I do not know much about Synfony at all so maybe this is completely wrong.

**Comment by kuzmany** [comment]
Based on M4 upgrade notes https://github.com/mautic/mautic/commit/f409dbe8fe31c932a4c6fe2931dd186a596eb0e0#diff-1a150f9e2ee0e6cf7cb8864a598cb567dfb617a5e3b0e3310aa947d5f518869aR8

> \Mautic\CoreBundle\Form\Type\YesNoButtonGroupType now uses false/true values which Symfony 4 will convert to empty values for No in the UI. This shouldn't cause issues for most unless the field is using a NotBlank constraint, which is no longer valid, or submitting a form via a functional test with 0 as the value of a YesNoButtonGroupType field. 

Seems like @jensolsson has true. From M4 is not possible use placeholder (x)

But If I revert back this line https://github.com/mautic/mautic/commit/f409dbe8fe31c932a4c6fe2931dd186a596eb0e0#diff-47b21ec36fd5a7c80731158a9bb770eb8ed0f3dfc3e09a8bbe68e7ffa969974fR55 It works in UI and I am able to use empty/false/true value of this button group. It works. 

Alan  does not work in Acquia anymore, probably @escopecz can put his expertise on it

**Comment by patrykgruszka** [comment]
I think we should revert changes from #9931, because we are actually using `ChoiceType` and not the `CheckboxType`. I've just tested it on my environment and it works fine (including issues from #9931 which i could not replicate on the 4.1 version). I've published a PR #10716 and I look forward to your opinion.

**Comment by RCheesley** [comment]
Resolved with #10716
