### ISSUE TITLE
With case sensitive file system, Upgrade to Mautic 4 could resulted in PHP fetal error because library folder name was not capitalized

### ISSUE THREAD

**Issue by katzueno** [mautic/mautic#10727]
### Mautic Version

4.0.0

### PHP version

7.4.21

### What browsers are you seeing the problem on?

Not relevant

### What happened?

If you installed Mautic 4.1.1 onto the server with case sensitive file system, you ended up with two PHP fetal errors.
I needed to rename two folder names of a library.

```
PHP Warning:  require(/var/www/vhosts/example/vendor/composer/../markbaker/matrix/classes/src/Functions/adjoint.php): failed to open stream: No such file or directory in /var/www/vhosts/example/vendor/composer/autoload_real.php on line 71
PHP Fatal error:  require(): Failed opening required '/var/www/vhosts/example/vendor/composer/../markbaker/matrix/classes/src/Functions/adjoint.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/vhosts/example/vendor/composer/autoload_real.php on line 71
```

It's because the folder of the library is named as `/vendor/markbaker/matrix/classes/src/functions/` where it should be named as `/vendor/markbaker/matrix/classes/src/Functions/`.

If I renamed the folder from `functions` to `Functions`, PHP fetal error was gone.

Once I fixed the above folder name, the following error started happening.

```
PHP Warning:  require(/var/www/vhosts/example/vendor/composer/../markbaker/matrix/classes/src/Operations/add.php): failed to open stream: No such file or directory in /var/www/vhosts/example/vendor/composer/autoload_real.php on line 71
PHP Fatal error:  require(): Failed opening required '/var/www/vhosts/example/vendor/composer/../markbaker/matrix/classes/src/Operations/add.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/vhosts/example/vendor/composer/autoload_real.php on line 71
```

I just renamed the folder `/markbaker/matrix/classes/src/operations` from `operations` to `Operations` again.

I was upgrading my Mautic 3 instance to Mautic 4 locally.
It was working fine.

Then, after I reimported the Mautic back to the production server, the error happened.

### How can we reproduce this issue?

Step 1: Work on the server which file system is case sensitive
Step 2: Upgrade from Mautic 3.3.4 to Mautic 4.1.1 by using CLI `mautic:update:apply`
Step 3: tried to run any CLI command, and ended up with the PHP fetal error.

FYI, I've also run composer install by myself, and i ended up with the same folder name.
So I guess we may need to report it to the library., not here...

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @katzueno thanks for reporting the bug. Unfortunately I think that this may relate to one of the upstream dependencies we use.

I'll double check with the team and confirm this is the case.
