### ISSUE TITLE
Issue on mautic after installing Virtualmin on the same server as mautic

### ISSUE THREAD

**Issue by fav22** [mautic/mautic#10721]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What happened?

Hello, since I didn't have a basic configuration panel, today I allowed myself to install Virtualmin on the same server as MAUTIC and then I encountered this problem when I visit my mautic Url

`<?php

/*
 * @copyright   2014 Mautic Contributors. All rights reserved
 * @author      Mautic
 *
 * @link        http://mautic.org
 *
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 */
define('MAUTIC_ROOT_DIR', __DIR__);

// Fix for hosts that do not have date.timezone set, it will be reset based on users settings
date_default_timezone_set('UTC');

require_once 'autoload.php';

use Mautic\CoreBundle\ErrorHandler\ErrorHandler;
use Mautic\Middleware\MiddlewareBuilder;
use function Stack\run;

ErrorHandler::register('prod');

run((new MiddlewareBuilder(new AppKernel('prod', false)))->resolve());`

Anyone here can help please ? Thank you all

### How can we reproduce this issue?

Step 1: Installing Virtualmin panel on the same server as Mautic

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
@fav22 this is some configuration error and not a mautic bug. Should be discussed in the forum instead. 
https://forum.mautic.org/

/cc: @RCheesley

**Comment by RCheesley** [comment]
Hi @fav22 please post this on https://forum.mautic.org/c/support, as above this is not a bug with mautic but your server configuration.
