### ISSUE TITLE
infinite loop in configure wheel mautic 3.3.2

### ISSUE THREAD

**Issue by mulham1988** [mautic/mautic#10725]
### Mautic Version

3.3.x series

### PHP version

 7.4.16

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

how can I fix this issue MAUTIC setting wheel
when I want to go to configuration it stalk into infinite  loop the rest of the setting list working well

### How can we reproduce this issue?

  Mautic 3.3 configuration it stalk into infinite  loop

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mulham1988** [comment]
https://user-images.githubusercontent.com/33623909/148062485-96ef6120-f3d7-4a27-8aa4-82fc4999463c.mp4

**Comment by RCheesley** [comment]
Hi @mulham1988 unfortunately we no longer support Mautic 3. Please update to 4.1.2 and if the issue persists, feel free to re-open the issue.
