### ISSUE TITLE
Form submission copy to bcc doesn't work

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#10720]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Looks like this issue "bcc will not receive form results" (see stale: https://github.com/mautic/mautic/issues/5967 or this https://github.com/mautic/mautic/issues/10328) is still happening. In my case with Amazon SES API connection.

### How can we reproduce this issue?

1. Create a form action.
2. Reply to submitter (not necessary) and bcc your own adress.
3. Submit a form and check your inbox... 

No information.

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for raising the bug @dsp76 - @mabumusa1 I thought this was addressed by a PR some time ago but maybe that was in a different area (not in the form action, but in the regular sending, perhaps?).

Hopefully a quick fix!

**Comment by mabumusa1** [comment]
@dsp76 @RCheesley I checked the issue it is not related to SES nor any of the other transports. 

Forms are not passing the fields `CC & BCC` therefore they are not sent.

**Comment by dsp76** [comment]
@mabumusa1 so its not just limited to Amazon SES, but a general problem across all mailers?

**Comment by mabumusa1** [comment]
> @mabumusa1 so its not just limited to Amazon SES, but a general problem across all mailers?

Yes, correct

**Comment by dsp76** [comment]
Not stale... the issue just has not enough attention yet.

**Comment by RCheesley** [comment]
Thanks for keeping it open - what version of Mautic are you currently experiencing this is?
