### ISSUE TITLE
Can not find "Queue" in configuration menu in 4.1.0 version for RabbitMQ setup

### ISSUE THREAD

**Issue by gvaniya** [mautic/mautic#10732]
### Mautic Version

v4.1.0

### PHP version

7.4.25

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Not relevant

### What happened?
![image](https://user-images.githubusercontent.com/61459963/148385948-1e08f909-23f7-4464-b52e-e80560f40639.png)

Can not find "Queue" in configuration menu in 4.0.1 version for RabbitMQ setup

### How can we reproduce this issue?

Step 1: Can not find "Queue" in configuration menu in 4.0.1 version for RabbitMQ setup

### Relevant log output

```shell
sudo php bin/console mautic:queue:process --env=prod -i page_hit
You have not configured mautic to use queue mode, nothing will be processed
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

 @kathrin-schmid @escopecz

**Comment by kuzmany** [comment]
https://docs.mautic.org/en/queue 

`NOTE: Mautic 3.x users who are implementing RabbitMQ or Beanstalkd need to configure the settings directly in their local configuration file. If you are using the legacy Mautic 2.x series the steps below remains the same.`

**Comment by gvaniya** [comment]
> https://docs.mautic.org/en/queue
> 
> `NOTE: Mautic 3.x users who are implementing RabbitMQ or Beanstalkd need to configure the settings directly in their local configuration file. If you are using the legacy Mautic 2.x series the steps below remains the same.`

I have added code in local file but not work queue. 

sudo php bin/console mautic:queue:process --env=prod -i page_hit
**You have not configured mautic to use queue mode, nothing will be processed**

All time same error show.
Please can u guide me how to setup RabbitMQ.

**Comment by dsp76** [comment]
@gvaniya you should switch over to the forum. Looks like the "missing" menu item is actually not missing.
/cc: @RCheesley

**Comment by RCheesley** [comment]
Please take this discussion to the forums @gvaniya as it's not a bug with Mautic itself, but more relating to how to configure it.
