### ISSUE TITLE
Email editor scrolls/jumps down after every `enter`

### ISSUE THREAD

**Issue by putzwasser** [mautic/mautic#10737]
### Mautic Version

4.0.0

### PHP version

7.4.26

### What happened?

While editing long emails (MJML template), the editor jumps/scrolls down every time `enter` gets typed.

This isn't a problem if you don't have a vertical scroll bar or (strangely) if you are at the top of the page/email.
If you scroll a bit to edit text in the middle the editor starts to jump on every `enter`.

### How can we reproduce this issue?

1. Open the email editor of a long email
2. Scroll to the middle
3. Edit a text and hit `enter`

### Relevant log output

```shell
There is none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for raising the bug report @putzwasser !

**Comment by StefanieKolb** [comment]
Is there any progress on this issue? We are experiencing this problem as well and it is very annoying for our editors.

Thanks

**Comment by DalbertHab** [comment]
We faced the same problem. I could trace down to problem to the CKEditor but don't know how to fix the problem:

This CKEditor method scrolls the page
```javascript
            scrollIntoParent: function(a, b, c) {
                var e, d, f, g;
                function l(b, c) {
                    /body|html/.test(a.getName()) ? a.getWindow().$.scrollBy(b, c) : (a.$.scrollLeft += b,
                    a.$.scrollTop += c)
                }
```

The email has to be longer than the viewport. Then press enter in an element which is not at the top or end of page. The current viewport must not at the bottom of the page.

**Comment by supercosh** [comment]
We are experiencing the same problem, also when pasting text. The solution would be to remove the style min-height: 100% from the HTML and BODY Tag of the GrapeJS iframe. Without these styles, the bug is gone.

The bug is also described here: https://dev.ckeditor.com/ticket/9136

**Comment by StefanieKolb** [comment]
The problem is still occuring in 4.4.2

**Comment by supercosh** [comment]
Can confirm, and a very easy CSS fix is mentioned above (https://github.com/mautic/mautic/issues/10737#issuecomment-1157418764). It would be great if this can make it into a release.

**Comment by adiux** [comment]
Looking into it

**Comment by supercosh** [comment]
Hello

Yes, this still is an issue. The fix is described in the Issue!

Regards
Gregor

stale[bot] ***@***.***> schrieb am Fr., 16. Sept. 2022, 02:27:

**Comment by RCheesley** [comment]
https://github.com/mautic/mautic/pull/11491 PR is ready to commit - thanks for the input folks!

**Comment by RCheesley** [comment]
@all-contributors please add @putzwasser for bugs
