### ISSUE TITLE
Unsubsribe and Preview urls generated are incorrect

### ISSUE THREAD

**Issue by ht512512** [mautic/mautic#10739]
### Mautic Version

4.0.0

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

Mautic is setup behind an ssl proxy. 

Mautic base url is configured to be https://myapp.myhost.com:8443/ which works fine for everything in the app 
except that the generated urls for unsubscribe and preview are of the form http://myapp.myhost.com:8443/...........
Note that the urls use http not https.

This means that the email recipients get broken unsubscribe and preview links.

Expected behavior would be that the urls use the configured base https://myapp.myhost.com:8443/

### How can we reproduce this issue?

Step 1: My setup that reproduces the issue consistently is as below.
Proxy listens on port 8443 and terminates ssl, proxies to localhost port 8080
Mautic Docker (v 4) exposes port 8080 mapped to 80
Configuration -> General Settings -> Site URL = https://myapp.myhost.com:8443
All of the Mautic app features work fine. There is no issue with proxying on the data path. Three instances where Mautic uses http instead of https are:
1. unsubscribe url in the emails sent
2. preview url in the emails sent
3. Logout redirects to http://myapp.myhost.com:8443/s/login (which does not exist) instead of secure https://myapp.myhost.com:8443/s/login

### Relevant log output

```shell
NA
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
Tested it with 4.1.1. also and I can't confirm this. The protocol will be respected as set in site URL for e.g the unsubscribe URL and also for the login page after logout. So it seems not to be a general issue with the code.

There is only another issue, as the port will be ignored within the unsubscribe URL.

@ht512512  I'd suggest discussing this in the Mautic Forum - it may rather be a config issue with docker. By forcing to use https: (rewrite) you would have a workaround by the way.

/cc: @RCheesley

**Comment by RCheesley** [comment]
OK thanks and yes, let's move this to the forum please @ht512512 :)
