### ISSUE TITLE
Can't open »Edit Source« modal after email builder was closed

### ISSUE THREAD

**Issue by putzwasser** [mautic/mautic#10736]
### Mautic Version

4.0.0

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Chrome

### What happened?

I'm using MJML email templates and edit the source frequently, because it's often faster for me than the editor.

The edit source modal:
![image](https://user-images.githubusercontent.com/26040044/148437576-14d8f620-66e6-4a28-96af-cb1ddb54762b.png)

 can't, however, opened after closing and re-opening the builder view.

My workflow is to edit the email, close the builder, click on save, and re-open the builder to proof-read, etc. When I open the builder the second time, I can't open the edit source modal again. I can click the button, but the modal doesn't show.
I need to refresh (F5) the browser tab.

### How can we reproduce this issue?

1. Open a MJML email
2. Open the builder
3. Click on edit source 
4. Close the source editor
5. Close the builder
6. Re-Open the builder
7. Click on edit source

### Relevant log output

```shell
The JS console just says: `loading modal`
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by adiux** [comment]
Duplicate. Will be fixed with https://github.com/mautic/mautic/pull/10707
Workaround: Refresh the browser.

**Comment by RCheesley** [comment]
Closing as a duplicate as above.
