### ISSUE TITLE
Relative asset links break when mautic is on a subdomain. (DWC editor)

### ISSUE THREAD

**Issue by putzwasser** [mautic/mautic#10749]
### Mautic Version

4.0.0

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Not relevant

### What happened?

If you create a link to an uploaded asset with the DWC editor using the `{` auto fill/completion feature, it will create a relative link.
If your mautic instance is running on a subdomain (e.g. `mautic.mysite.com`) this relative link will break.

If you click the link, you'll get redirected to an unusable domain. E.g. `https://MyAsset.pdf`

(Actually I don't know if it really is a relative link, as the target url is completely unusable.)

### How can we reproduce this issue?

1. Upload an asset (e.g. a PDF named `MyAssetName.pdf`)
2. Create a DWC with a link to the asset. Type `{` for auto fill and select `MyAssetName.pdf` it will create a link with protocol other and a relative path.
![image](https://user-images.githubusercontent.com/26040044/149212152-b4bdc7fa-3aa0-4a71-bb73-e07d06c3326a.png)

3. Add the DWC to a third party site
4. The DWC container adds a redirect link (in my case mautic.mysite.com/r/{hash}
5. Click the link
6. Get redirected to `https://MyAssetName.pdf`

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
@putzwasser we almost always have mautic running on a subdomain. Links generated are always fine. did you set your Site URL correctly? This is not a bug, its a configuration issue. Please switch to the mautic forum to further discuss. https://forum.mautic.org/

@RCheesley this could be closed.

**Comment by putzwasser** [comment]
Everything was set up correctly. It seems to work now. I don't know what caused the problem. Maybe it was, because I was logged in in the backend?

**Comment by putzwasser** [comment]
(Wanted to click "close with comment")
