### ISSUE TITLE
email_queued: filter on email statistics

### ISSUE THREAD

**Issue by skacco** [mautic/mautic#10748]
### Mautic Version

4.0.0

### PHP version

7.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

A bug happened!

### How can we reproduce this issue?

the email_queued: filter does not show any email but email list report there are some email queued

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
This was resolved with #10803 which is being released in 4.2 at the end of February.
