### ISSUE TITLE
Console Command not working

### ISSUE THREAD

**Issue by luismts** [mautic/mautic#10743]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

I have Mautic v4.1.0 with PHP 7.4 and console commands are doing nothing. Also, I call -hep options and nothing happens.

Does anyone know how to deal with this?

### How can we reproduce this issue?

Use this command
`php bin/console mautic:segments:update`

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
Can't confirm this with neither 4.1.0 nor 4.1.1 ... Both are working.
Seems more to be an individual problem with your instance than with Mautic Code.

@RCheesley should probably be closed

**Comment by dsp76** [comment]
@luismts please open a discussion in the mautic forum. There are some checks you could do, but lets discuss there.

**Comment by RCheesley** [comment]
Thanks @dsp76 and indeed, yes it should go on https://forum.mautic.org/c/support @luismts.
