### ISSUE TITLE
Filtering by "Integration Campaign Members" in a segment results in a silent error

### ISSUE THREAD

**Issue by mortencallesen** [mautic/mautic#10740]
### Mautic Version

4.0.0

### PHP version

7.4

### What happened?

Mautic 4.1.1
Salesforce integration - when setting up a new segment on Mautic, it is not possible to filter by "Integration Campaign Members". This results in a silent error (error 500 on console is visible).

BAS has posted a solution on forums.
https://forum.mautic.org/t/salesforce-integration-campaign-members-filter-not-working-after-upgrade-to-mautic-3/19185/2

### How can we reproduce this issue?

Step 1:  Set up campaign on salesforce
Step 2: Create segment on mautic
Step 3: Set filter criteria on mautic to "Integration Campaign Members" equals Campaign name from Salesforce
Step 4: Save segment

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for raising the issue, hopefully @bastolen will make a PR to resolve this issue! Shout if you need any help with doing that.

**Comment by bastolen** [comment]
> Thanks for raising the issue, hopefully @bastolen will make a PR to resolve this issue! Shout if you need any help with doing that.

Will do 😀 but first I'll check if there is a better solution (which was the reason I didn't do this before), because this way will make you lose the option group functionality and get longer with option names. I'll check later today.
