### ISSUE TITLE
Deleting a tag from tag manager, that is still in use in a form action, will not load edit window

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#10755]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

If you delete a tag from the tag manager, it causes problems:
* A form action allows to add a tag to a submit. After a tag has been deleted, you cant edit the form action anymore (endless loading) - only delete the action.

Would be better to let users know, that tags are still in use for forms / campaigns / segments, before deleting them. Currently it only shows a number of contacts this tag is applied to. Better: show where the tag is also used in the mentioned objects.

### How can we reproduce this issue?

Step 1: Add a "add tag (modify user tags)" action to a form. 
Step 2: Delete that tag from tag manager
Step 3: Try to edit this action in the form

Will not warn before deletion.
Will not load the edit windows and not throw an error.

Probably causes trouble with segments / campaigns too?

### Relevant log output

```shell
2022-01-14 14:28:18] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform data for property path "[add_tags]": Tags for "123456" does not exist!" at /XXX/httpdocs/vendor/symfony/form/Form.php line 1059 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unable to transform data for property path \"[add_tags]\": Tags for \"123456\" does not exist! at /XXX/httpdocs/vendor/symfony/form/Form.php:1059, Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Tags for \"123456\" does not exist! at /XXX/httpdocs/app/bundles/LeadBundle/Form/DataTransformer/TagEntityModelTransformer.php:120)"} []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by LeonOltmanns** [comment]
Just tested it on 4.1.1 using the Instructions given. Had the same error and thus can confirm that this is an issue.

Resulted in the following Logs:

> [2022-01-17 09:48:59] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform data for property path "[add_tags]": Tags for "Test-Tag PR" does not exist!" at /var/www/html/htdocs/vendor/symfony/form/Form.php line 1059 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unable to transform data for property path \"[add_tags]\": Tags for \"Test-Tag PR\" does not exist! at /var/www/m4test.mautic2.leuchtfeuer.com/htdocs/vendor/symfony/form/Form.php:1059, Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Tags for \"Test-Tag PR\" does not exist! at /var/www/html/htdocs/app/bundles/LeadBundle/Form/DataTransformer/TagEntityModelTransformer.php:120)"} []

**Comment by RCheesley** [comment]
Thanks for raising the bug @dsp76 and for confirming @oltmanns-leuchtfeuer! I agree it would be good to check like we do with segments to see if the tag is in use anywhere (e.g. forms, campaigns) before it is deleted.

**Comment by dsp76** [comment]
not stale, still there
