### ISSUE TITLE
Mautic 4.x requires "mautic/core-lib": "^3.0"

### ISSUE THREAD

**Issue by biozshock** [mautic/mautic#10751]
### Mautic Version

4.0.0

### PHP version

7.4.10

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The `composer.json` for branch `4.x` requires `"mautic/core-lib": "^3.0"` and also defines `app` as `"mautic/core-lib": "3.2.x-dev"`. Shouldn't it be `"mautic/core-lib": "4.1.x-dev"`

### How can we reproduce this issue?

Step 1: look into `composer.json`

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the report @biozshock - I've asked @nickveenhof to take a look at your suggestions.

**Comment by RCheesley** [comment]
Actually this is a duplicate of an existing issue: https://github.com/mautic/mautic/issues/10651 so let's take the discussion there.

**Comment by RCheesley** [comment]
Not a duplicate .. different composer-related issue 🤦 Sorry for the confusion!
