### ISSUE TITLE
Code Mode isn't useable in GrapesJS

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#10769]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When building an email using the new GrapesJS builder, the user is given the option of selecting "Code Mode". In Code Mode, the user can paste in html code into the GrapesJS builder instead of MJML and the ui renders the email, seemingly as pasted into the box.

However, as [documented in this issue](https://github.com/mautic/mautic/issues/10475), GrapesJS actually rewrites the HTML, assigning IDs and classes and moving css into a style tag before the `</body>` tag. 

There is no way for a user to actually get the code they put in to the code editor come out the emails sent by Mautic, and it's nearly impossible to get an HTML email to render correctly using code mode in all email clients for this reason. 

Here is some example HTML that really brings home the issue:
```
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">

<head>
    <title>
        {subject}
    </title>
</head>
<body style="background-color:#ffffff;">
  <h2 style="color:red;font-size:18px;font-family:serif;">This is a red serif heading</h2>
  <p><a href="https://www.mautic.org" style="color:white; text-decoration:none; padding:8px 20px; background:orange;">This is an orange button</a></p>
  </body>
</html>
```

Here is how that renders with the old code mode (non-grapes-js) in gmail, essentially just passing it through:
![image](https://user-images.githubusercontent.com/866855/153626324-355f06f6-7a5f-47b6-a5d2-f44410c4d2fa.png)

Here is the code that the new grapes-js editor saves (reformatted for readability):
```
<!DOCTYPE html>
<head>
   <title>
      Demo Code Mode
   </title>
</head>
<body>
   <h2 id="ikph">This is a red serif heading</h2>
   <p><a href="https://www.mautic.org" id="iysd">This is an orange button</a></p>
   <style>#ikph{color:red;font-size:18px;font-family:serif;}#iysd{color:white;text-decoration:none;padding:8px 20px;background:orange;}</style>
</body>
```

Here is how that same code renders in gmail with the new code mode (grapes-js):
![image](https://user-images.githubusercontent.com/866855/153626377-08246e2f-73a3-4fb1-902a-882ea0d7aef7.png)

I interpret this as a bug/regression for either or both of the following reasons:
- Users can't actually use "code mode" to make an email with style that renders correctly in gmail, so we have a feature to make an HTML email that can't actually make an HTML email
- The expectation of users is that the new code mode has at least the same level of functionality as the old code mode - I can paste code into it and get the same code back out when an email is sent.

The way that issue #10475 was closed, it's implied that this is a feature  of GrapesJS, not a bug in Mautic, but I think interpreting it that way is a disservice to our users. I would think that any of the following three would be a better resolution, especially since the [GrapesJS project has implied this is the intended behavior of their editor](https://github.com/artf/grapesjs/issues/546):
- If GrapesJS is enabled, disable Code Mode until a more usable experience can be developed
- If GrapesJS is enabled, make code mode simple textarea in which a user can paste in HTML code that will be sent, without modification, as an email. No preview, no fancy code editor, just a textarea. The resulting email can be previewed using the preview button after saving. 
- After enabling GrapesJS, make Code Mode use the old editor, while templates use the new GrapesJS editor, at least until a new option can be developed
- Use GrapesJS for templates, but for code mode, use another tool or create a new simple preview from scratch that doesn't modify the code pasted in

### How can we reproduce this issue?

Step 1: Enable GrapesJS
Step 2: Create a new email and select "Code Mode"
Step 3: Click the builder and then the "Edit Code" button
Step 4: Paste in the following HTML
```
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">

<head>
    <title>
        {subject}
    </title>
</head>
<body style="background-color:#ffffff;">
  <h2 style="color:red;font-size:18px;font-family:serif;">This is a red serif heading</h2>
  <p><a href="https://www.mautic.org" style="color:white; text-decoration:none; padding:8px 20px; background:orange;">This is an orange button</a></p>
  </body>
</html>
```
Step 5: Save and close the email
Step 6: Use the preview URL or send yourself a test and compare the code you get out to the code you put in

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by PierreAmmeloot** [comment]
I confirm, I have same problem on Mautic 4.

**Comment by dakur** [comment]
I've just ran into this issue as well and discovered the bad rendering in Gmail clients accidentally just before sending to all contacts.

Flow:
- create e-mail using [Bee service](https://beefree.io/) (that's a guarantee for me that it renders well in all clients)
- export HTML from BEE and paste it into Mautic in Code Mode
- send e-mail from Mautic

Quick fix which worked for me was to force the correct code by updating `custom_html` column for appropriate row in `emails` table, but I don't know Mautic database structure well so I'm not sure if it doesn't have any hidden consequences. As I have fresh install with first e-mail, it didn't matter to me much, but I would like to know what to do for further e-mails.

**Comment by webalexstudio** [comment]
Hi. Have same issue with css styles in Gmail from Mautic GrapesJs "Edit Code".
Is there any info about this issue?

**Comment by adiux** [comment]
Can we have a simple HTML/CSS to test this?

**Comment by dakur** [comment]
@adiux Thanks for looking into this. You can try this one:

```html
<!DOCTYPE html>
<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" lang="en">

<head>
	<title></title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->
	<style>
		* {
			box-sizing: border-box;
		}

		body {
			margin: 0;
			padding: 0;
		}

		a[x-apple-data-detectors] {
			color: inherit !important;
			text-decoration: inherit !important;
		}

		#MessageViewBody a {
			color: inherit;
			text-decoration: none;
		}

		p {
			line-height: inherit
		}

		@media (max-width:520px) {
			.row-content {
				width: 100% !important;
			}

			.stack .column {
				width: 100%;
				display: block;
			}
		}
	</style>
</head>

<body style="background-color: #FFFFFF; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;">
	<table class="nl-container" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #FFFFFF;">
		<tbody>
			<tr>
				<td>
					<table class="row row-1" align="center" width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
						<tbody>
							<tr>
								<td>
									<table class="row-content stack" align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 500px;" width="500">
										<tbody>
											<tr>
												<td class="column" width="100%" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;">
													<table class="button_block" width="100%" border="0" cellpadding="10" cellspacing="0" role="presentation" style="mso-table-lspace: 0pt; mso-table-rspace: 0pt;">
														<tr>
															<td>
																<div align="center">
																	<!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="https://github.com/mautic/mautic/issues/10769" style="height:44px;width:68px;v-text-anchor:middle;" arcsize="137%" strokeweight="0.75pt" strokecolor="#8a3b8f" fillcolor="#8a3b8f"><w:anchorlock/><v:textbox inset="0px,0px,0px,0px"><center style="color:#ffffff; font-family:Arial, sans-serif; font-size:16px"><![endif]--><a href="https://github.com/mautic/mautic/issues/10769" target="_blank" style="text-decoration:none;display:inline-block;color:#ffffff;background-color:#8a3b8f;border-radius:60px;width:auto;border-top:1px solid #8a3b8f;border-right:1px solid #8a3b8f;border-bottom:1px solid #8a3b8f;border-left:1px solid #8a3b8f;padding-top:5px;padding-bottom:5px;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;"><span style="padding-left:20px;padding-right:20px;font-size:16px;display:inline-block;letter-spacing:normal;"><span style="font-size: 16px; line-height: 2; word-break: break-word; mso-line-height-alt: 32px;">GO</span></span></a>
																	<!--[if mso]></center></v:textbox></v:roundrect><![endif]-->
																</div>
															</td>
														</tr>
													</table>
												</td>
											</tr>
										</tbody>
									</table>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
		</tbody>
	</table><!-- End -->
</body>

</html>
```

**Comment by webalexstudio** [comment]
Seems like a problem is in "Content-Transfer-Encoding: quoted-printable".
Is it a proper way to change quoted-printable to us-ascii, for example?

**Comment by stevedrobinson** [comment]
@adiux I updated the issue to include some simple html to test the issue, along with screen grabs and detail of how the grapes-js editor is manipulating the code. Let me know if I can do anything else to help clarify the problem.

**Comment by webalexstudio** [comment]
I have tried to send emails with other possible variants of content-encoding in Mautic system, but it did not hep to resolve the problem.

**Comment by webalexstudio** [comment]
Seems like I have catch the problem.
Grapesjs editor merge css styles and set it in the <body> before body end </body>. Most of email clients, do not read such styles. 
If I edit manually html in the db and move all <style> tag into the <head>, all works fine.

**Comment by medsun88** [comment]
GrapesJs is not working in code mode,  I am also facing the same issue like others. 

1. If I enable the GrapesJS plugin , I am not able to send the code mode email as per format, 
I have almost more than 20 such designed email which were working ok earlier. And New GrapesJS has broken all of them while sending. Check issue #10713  and #10475

2. And,  if we disable the GrapesJS Plugin, CKEditor give load error while sending personal email, check issue #10604 

Guys requested to kindly remove the GrapesJS or help the people to fix the issue. 

@kuzmany  @RCheesley @escopecz @alanhartless @dongilbert @mqueme

**Comment by kuzmany** [comment]
That means GrapesJs ruin the custom HTML code  of email, right?  
Then you vote to get back old code mode editor? I vote for it, but let's team decide

**Comment by kuzmany** [comment]
@medsun88 about point 2 - that's different issue, let's focus  on code mode here

**Comment by medsun88** [comment]
> That means GrapesJs ruin the custom HTML code of email, right? Then you vote to get back old code mode editor? I vote for it, but let's team decide

@kuzmany  Yes, GrapesJS has really ruined such a main part of the Email builder. 
------------------------------------------------------------------------------------------
I vote for the old, Legacy editor.
And request all others in this thread to vote for old Editor. 
@stevedrobinson @PierreAmmeloot @dakur @webalexstudio

**Comment by webalexstudio** [comment]
> That means GrapesJs ruin the custom HTML code of email, right? Then you vote to get back old code mode editor? I vote for it, but let's team decide

Hey, your team has tones of such requests about GrapesJs and ruined email html.  Why are you reacting to it like you're hearing about it for the first time?
Check your Github issues, check other resources. You have a big problem with GrapesJs library in Mautic v4.
So please, don't react on this in the way you are reacting.
If your team is not able to fix that problem, just release  the version without GrapesJs editor and inform your users that your team is not able or do not want to fix it.

**Comment by webalexstudio** [comment]
> > That means GrapesJs ruin the custom HTML code of email, right? Then you vote to get back old code mode editor? I vote for it, but let's team decide
> 
> ## @kuzmany Yes, GrapesJS has really ruined such a main part of the Email builder.
> I vote for the old, Legacy editor. And request all others in this thread to vote for old Editor. @stevedrobinson @PierreAmmeloot @dakur @webalexstudio

Fully understand your frustration!
Tones of requests and no reaction. And btw, sending of the emails is one of the main goal of this system, and I can not understand how such issues can be not fixed for a very long time.

**Comment by jacob5544** [comment]
best solution: just give up mautic and save a lot of time!

**Comment by kuzmany** [comment]
@webalexstudio you are able to disable GrapesJs editor, aren't you?

**Comment by medsun88** [comment]
So many people have reported problem about GrapesJS,  All issues mentioned here 

https://github.com/mautic/mautic/labels/builder-grapesjs

@mabumusa1 @adiux @biggala2310  @isaiahdahl @npracht @shekhar677 @shmaltz @

This issue is from a Long time.  Guys vote from Removing GrapesJS , It has spoiled the Mautic. 

@kuzmany  If we disable the GrapesJS as you mentioned above, It starts showing CKEditor load error #10604

If we disable the GrapesJS plugin to fix the issue #10769 , Mautic starts giving CKEditor load error #10604
and to get rid of CKEditor load error #10604, if we enable the GrapesJS plugin, it breaks the Html code mode. 

Guys, at least fix one.  Both issue are related to the core functionality of mautic. 
Mautic core function is sending emails, and both errors are affecting this.

**Comment by jacob5544** [comment]
> So many people have reported problem about GrapesJS, All issues mentioned here
> 
> [ builder-grapesjs](/mautic/mautic/labels/builder-grapesjs)
> 
> @mabumusa1 @adiux @biggala2310 @isaiahdahl @npracht @shekhar677 @shmaltz @
> 
> This issue is from a Long time. Guys vote from Removing GrapesJS , It has spoiled the Mautic.
> 
> @kuzmany If we disable the GrapesJS as you mentioned above, It starts showing CKEditor load error #10604
> 
> If we disable the GrapesJS plugin to fix the issue #10769 , Mautic starts giving CKEditor load error #10604 and to get rid of CKEditor load error #10604, if we enable the GrapesJS plugin, it breaks the Html code mode.
> 
> Guys, at least fix one. Both issue are related to the core functionality of mautic. Mautic core function is sending emails, and both errors are affecting this.

Don't expect the impossible medsun88, there are many other good newsletter systems. it is time to switch! save your time and energy!

**Comment by dakur** [comment]
@jacob5544 Please stop this.

Guys, if I understand well, @adiux and @kuzmany are into this and they are reacting and collecting information about the problem and how to resolve it – that's good signal. Yes, I have my own experience with Mautic features stability and I can't say they're rather good, but if we don't stay rational and calm emotions, we won't move anywhere.

Mautic team, unless the bug is fixed, can anyone share a workaround or at least confirm that updating `custom_html` column in database manually is safe?

**Comment by kuzmany** [comment]
> If we disable the GrapesJS as you mentioned above, It starts showing CKEditor load error https://github.com/mautic/mautic/issues/10604

Fixed by https://github.com/mautic/mautic/pull/10897 (require  `php bin/console mautic:assets:generate`)

**Comment by jacob5544** [comment]
> @jacob5544 Please stop this.

may you should check out this https://github.com/artf/grapesjs/issues/2686
where grapejs dev delete comments which point to the issues!

**Comment by adiux** [comment]
@RCheesley and I looked into this. We think the best solution is:

As @stevedrobinson suggested:

> If GrapesJS is enabled, make code mode simple textarea in which a user can paste in HTML code that will be sent, without modification, as an email. No preview, no fancy code editor, just a textarea. The resulting email can be previewed using the preview button after saving.

We display a simple textarea (emailform_customHtml) above the "Plain Text" field in the advanced tab that can be used to to directly add HTML:
<img width="935" alt="image" src="https://user-images.githubusercontent.com/13075514/155564328-0440278a-c759-48c9-831b-1acecc815921.png">

The builder button to launch GrapesJS will be disabled.
The textarea is only visible if code mode was selected.

Caveat 1:
Once you are in code mode you can not change the template in Grapesjs. E.g. to change texts or images.
If you wish to do so you will have to select an existing theme and then import the HTML inside the grapesjs builder. 

Caveat 2:
There is no security or any other check. People can import faulty HTML, CSS, and JavaScript. 

Do we have some basic checks at the backend?

**Comment by kuzmany** [comment]
@adiux probably would be better keep old code mode editor. I've tried make some draft, how it could work https://github.com/mautic/mautic/pull/10900/. It's experimental, but does what I mean. Just ugly code

What do you think?

**Comment by adiux** [comment]
Thanks @kuzmany for your code. Is the old code mode using any functionality from the old builder? We should not use that code anymore as it is going to go away with v5.

**Comment by kuzmany** [comment]
@adiux I thought deprecated is legacy builder. This is code mode builder with syntax highlighter etc. But How I'm thinking about it, your solution is enough at the moment. And we can add some sweet features like code beatify and syntax highlighter later If we need it.
Can you look on your solution?

**Comment by medsun88** [comment]
> > If we disable the GrapesJS as you mentioned above, It starts showing CKEditor load error #10604
> 
> Fixed by #10897 (require `php bin/console mautic:assets:generate`)

-----------------------

#10897  fix is not working, I checked on production

**Comment by kuzmany** [comment]
@medsun88 did you refresh browser cache?

**Comment by adiux** [comment]
we started working on the proposed solution

**Comment by RCheesley** [comment]
@stevedrobinson @PierreAmmeloot @dakur @webalexstudio @medsun88 @jacob5544 @kuzmany please check the proposed solution from @adiux @volha-pivavarchyk in #10976

**Comment by ghost** [comment]
@RCheesley I see a few lacks in this solution:
1. How can I add image/media to HTML email?
2. Preview is uncomfortable. Requires other card.

**Comment by dakur** [comment]
@RCheesley @volha-pivavarchyk  Thanks for working on this!

Plain textarea is OK for me as a quickfix. But I can see a UX problem with the missing button. Advanced tab is rather an unexpected place where I would definitely NOT search for standard/basic editing e-mail content functionality so I can imagine people scratching their head thinking "how the heck should I insert my HTML?" when there is no button. But yes, it's still better than broken e-mails. :-)

Suggestion: What about leaving the button there (or transform it to a link visually) and re-label it to something like "Edit code" which would switch tabs to Advanced? It's not convenient/consistent either, but at least it's easy to find.

**Comment by kuzmany** [comment]
Probably we should discuss to keep code mode editor with preview, syntax highlighter and media library support.  The remove legacy builder for M5 is related to remove froala editor. Code mode editor does not use it @RCheesley What do you think?

**Comment by PierreAmmeloot** [comment]
@kuzmany I agree your offer !

**Comment by adiux** [comment]
I agree with all you said. This was meant to be a quick fix so that people don't have to mess with the HTML directly in the database, etc.

As a next step: 
Based on your suggestions, I think we should use the builder button to open the code mode editor in a modal.

**Comment by stevedrobinson** [comment]
I think this progression - text box for now, old code editor later makes sense. 

Thank you @adiux for getting a stopgap solution in place.

**Comment by lgwapnitsky** [comment]
Just wrote an entire email blast before seeing this. Not happy. Going to try to switching to old editor so I can get my emails out.

Now following this thread for updates

**Comment by PierreAmmeloot** [comment]
Hello @kuzmany,

What can I do to help with this?

Pierre

**Comment by escopecz** [comment]
Closing this issue as https://github.com/mautic/mautic/pull/11102 will be released in 4.2.2 today. Please create a new issue for bugs or enhancements for this solution.

**Comment by SofiaVGI** [comment]
I think i found a solution.

-> copy the html from the template or email you want to edit
-> create new email with blank template
-> Go to builder
->Edit the code and paste the html. 

This way you can use html template and edit with builder. You can eve save and comeback, it will be possible to edit again.

I'm not a developer so i have no idea why this works. But it does for me

**Comment by drimlike** [comment]
We're getting the same issue as everyone.
What's the final solution?
It looks like the thread has been closed without a fix.

**Comment by drimlike** [comment]
@escopecz hope you're well!
Can we now send emails generated using GrapesJS with a proper rendering in Gmail?

**Comment by jacob5544** [comment]
> We're getting the same issue as everyone. What's the final solution? It looks like the thread has been closed without a fix.

drimlike, the best solution: just give up mautic and save a lot of time! you are welcome!

**Comment by escopecz** [comment]
@drimlike this issue is about missing option to create emails from HTML code. Meaning you prepare the HTML in some other app and paste it to Mautic's email edit page. That is now possible. It used to be more user friendly with code styling and preview. it was called Code Mode editor and was removed when I didn't pay much attention. I'd like to get it back but I and many other developers are now focussed on replacing outdated libraries and releasing Mautic 5. Once that's done I'd like to get the Code Mode editor back.

I'm searching around and it looks like Ruth sent you from https://github.com/mautic/mautic/issues/10713 here. I'll re-open https://github.com/mautic/mautic/issues/10713 as I don't see the relation with this issue.

**Comment by Export-to-csvsidney** [comment]
@stevedrobinson https://lnkr.fun/797c85b
