### ISSUE TITLE
Email sent to wrong locale

### ISSUE THREAD

**Issue by paradiseporridge** [mautic/mautic#10762]
### Mautic Version

3.3.4

### PHP version

7.3.33

### What browsers are you seeing the problem on?

Chrome

### What happened?

Contact with preferred locale "en" (English) received an email with specified language "en_ZA". This contact should have received the parent email with specified language "en" not it's translation "en_ZA".

Mautic\EmailBundle\Model\EmailModel.php
Parent email locale is not added to languages translation local core in email settings that is used in sendEmail() method to determine which email locale should be sent to which contact.
`"languages":{"default":1,"en":{"en_ZA":2,"en_AU":3},"de":{"de_DE":4}}`

It doesn't match 'en' in `{"en_ZA":2,"en_AU":3}` since it is missing and picks the first element which is "en_Za" in my case.

### How can we reproduce this issue?

**Step 1**: Add 3 contacts and set their preferred locales ("en", "en_ZA" and "en_AU").
Contact 1 -> preferred locale "en_ZA"
Contact 2 -> preferred locale "en"
Contact 3 -> preferred locale "en_AU"

**Step 2**: Create segment and add these contacts to this segment.

**Step 3**: Create 4 template emails: one is a parent email  with language "en" (English) and 3 translations ("en_ZA", "en_AU", "de_DE") of this parent emails.
![emails](https://user-images.githubusercontent.com/3449141/149768049-29203443-431a-431a-8570-3af1cbc7d681.png)

**Step 4**: Create a campaign that would send emails to contacts in the segment that was created.
![campaign](https://user-images.githubusercontent.com/3449141/149771126-c52a67eb-e0a6-4951-b1a5-c258f5db2daa.png)

**Result:**
Contact 2 whose preferred locale is "en" received email "Translation Test (en_ZA)" (language: "en_ZA"). 
This contact should have received the parent email "Translation Test (en)" since the contacts preferred locale is "en".

Other contacts received correct emails:
Contact 1 -> "Translation Test (en_ZA)" email
Contact 3 -> "	Translation Test (en_AU)" email

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @paradiseporridge thanks for making the bug report. As 3.x is no longer supported, can you please confirm if this issue persists on 4.1.2? I expect it probably will, but would be most helpful if you could please check.
