### ISSUE TITLE
Can't install  1.2.2 with postgresql

### ISSUE THREAD

**Issue by mihailShumilov** [mautic/mautic#1076]
When i tried to install mautic use username for db as db name
https://monosnap.com/file/EsApyllAtc5ur9FSCNezGjgcFHHhg1

**Comment by alanhartless** [comment]
I just tried installing 1.2.2 on my local postgresql and it installed ok.

![](http://alan.direct/drop/2015-10-28_16-11-44.png)

![](http://alan.direct/drop/2015-10-28_16-13-35.png)

**Comment by mihailShumilov** [comment]
I still can't install
Please take a look
https://monosnap.com/file/4LwDszSy4Du6VJMfF8dv0Y8uxaZfjO

**Comment by mihailShumilov** [comment]
i checkout latest code from master branch
result is the same - can't install

**Comment by mihailShumilov** [comment]
if i remove this line https://github.com/mautic/mautic/blob/master/app/bundles/InstallBundle/Controller/InstallController.php#L444

all works perfect

**Comment by alanhartless** [comment]
What version of Postgresql are you using?

**Comment by mihailShumilov** [comment]
"PostgreSQL 9.4.4 on x86_64-apple-darwin14.3.0, compiled by Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn), 64-bit"

**Comment by mihailShumilov** [comment]
any updates?
