### ISSUE TITLE
I've been on Mautic community forums for months now and i still get the "no post access" banner and cant make posts

### ISSUE THREAD

**Issue by ivan006** [mautic/mautic#10761]
### Mautic Version

4.0.0

### PHP version

na

### What browsers are you seeing the problem on?

Firefox

### What happened?

I cant make any posts

### How can we reproduce this issue?

I did follow instructions and viewed various topics but no luck.
My username is  "ivan006" on the forum

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
This is not the place to report issues with the forum. I will contact you by DM on the forums.
