### ISSUE TITLE
Sending a webhook through campaign trigger using duplicate values

### ISSUE THREAD

**Issue by Orestes2** [mautic/mautic#10776]
### Mautic Version

4.1

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Firefox

### What happened?

This is a post about an unresolved issue https://github.com/mautic/mautic/issues/10214

This issue has not been resolved yet, tested on lastest stable version 4.1.1 

### Steps to reproduce
Go to Campaign builder
Create a Send a Webhook action
Push Add a Value twice
Try to introduce similar Value in both value fields
Push Update
Edit again that action
Duplicate value number has been deleted

![image 1](https://user-images.githubusercontent.com/86715683/123939812-d662fd00-d998-11eb-847a-0d247617d476.png)
![image 2](https://user-images.githubusercontent.com/86715683/123939863-e549af80-d998-11eb-876f-a53482cb6678.png) 

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for raising this again, @Orestes2 - if it happens to go stale please just reply with something and it will prevent the issue being closed.
