### ISSUE TITLE
Mautic campaign action „Update contact“ updates all bool custom fields

### ISSUE THREAD

**Issue by putzwasser** [mautic/mautic#10780]
### Mautic Version

4.0.0

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Not relevant

### What happened?

To comply with the GDPR I created two custom fields:
* `gdp_profiling_opt_in` and
* `gdpr_doi_opt_in_confirmed`

`gdpr_profiling_opt_in` Saves whether a contact consented into storing data about preferences, etc. I implemented this via a checkbox a user can check during sign up. The form's checkbox input is tied to the custom field.
`gdpr_doi_opt_in_confirmed` will be set to true during my double opt in campaign. Here is the problem:

The campaign waits for the user to click the confirmation link in the DOI confirmation email. If it gets clicked, it triggers the `Update contact` action. In the action I want to set `gdpr_doi_opt_in_confirmed` to true:

![image](https://user-images.githubusercontent.com/26040044/150678608-f53000ba-2f7d-4af6-b5d1-cc2e5fa00193.png)

For the field `GDPR - Profiling Opt In` I can't select something like `unchanged`/`default` or the like. Either `yes` or `no` is selected (based on the default value, which is no in my case). I left the setting untouched (i.e. setting it to `no`). The result is that every contact's gdp_profiling_opt_in field gets updated to `no`. That is wrong. I need it to stay as is.

### How can we reproduce this issue?

1. Create a custom bool field
2. create a new user
3. set the custom bool field to the non-default value
4. Create a `Update contact` campaign action and update some random contact field
5. Check the created contact. Their custom bool field was set to the default value (because that is selected in the `Update contact` form).

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by putzwasser** [comment]
Here's a screenshot of the contact's audit log, which also shows  that the wrong field gets updated. It may help to identify the problem...

![image](https://user-images.githubusercontent.com/26040044/151065935-66e78306-f80c-49c0-a28b-a5760a2aa915.png)

**Comment by MadlenF** [comment]
Hi @putzwasser , the issue you described here was fixed in this [PR](https://github.com/mautic/mautic/pull/10716) and is updated in the 4.1.2 version :)

**Comment by putzwasser** [comment]
@MadlenF Thanks for the hint. I updated to 4.1.2 and it seems to work just fine now.
