### ISSUE TITLE
Campaign is not sending 

### ISSUE THREAD

**Issue by ntmoin** [mautic/mautic#10788]
### Mautic Version

4.0.0

### PHP version

php7.4

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What happened?

![image](https://user-images.githubusercontent.com/98025657/150928319-f2bd8013-ceed-46c5-80ab-2068bff42ad7.png)

Campaign is not sending i.e. campaign send success percentage (%) is zero (0) | Contacts under sent campaign doesn't show (it rounds and rounds but no information) | Mautic Version 4.1.1 | php7.4

Note: SMTP mail configuration is okay (tested).

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, what the the source of the campaign: Form or Segment or Both?

**Comment by RCheesley** [comment]
Hi @ntmoin, it's not clear from your bug report if you've triggered the cron job so that the campaign is built and then triggered, could you please clarify?

**Comment by ntmoin** [comment]
No way campaign goes/reaches to the segment subscribers. SMTP integration is fine/functional. We can send test mail or even single mail/campaign to a single contact/subscriber.

The issue for any campaign and for any segment.

I have set corntab cronjob as well like below_
![image](https://user-images.githubusercontent.com/98025657/152753898-f8a3f9f8-3428-4a02-9ace-be9f7b731710.png)
![image](https://user-images.githubusercontent.com/98025657/152753785-3db2dd8e-6902-4102-bc65-d3c5bd5f14e7.png)
