### ISSUE TITLE
Error integrating Manychat with Mautic through Zapier

### ISSUE THREAD

**Issue by cgranobles** [mautic/mautic#10798]
### Mautic Version

4.0.0

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Chrome

### What happened?

I was integrating Manychat with Mautic through Zapier to take a tagged contact and create it as a contact on Mautic. All the steps are done and even finding and mapping the fields, when the test is done to send the contact to Mautic, an error comes out and the contact is not sent. Your help please. Thank you.

### How can we reproduce this issue?

The steps to do the integration are as follows:
1) Choose App & event ->OK
2) Choose account ->OK
3) Configure action. When testing the action, -> ERROR the error comes out: The contact could not be sent to Mautic-> No route found for "POST api/contacts/new"

### Relevant log output

```shell
The contact could not be sent to Mautic.
No route found for "POST /api/contacts/new"
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by cgranobles** [comment]
![Error integración Zapier Mautic](https://user-images.githubusercontent.com/98432582/151076808-882b3947-f172-4ce8-a05d-514bb4984a40.png)

**Comment by jos0405** [comment]
Hi, did you refresh the cache after allowing the API?

**Comment by RCheesley** [comment]
Hi @cgranobles thanks for sharing this. Usually this happens if the API is not enabled in Mautic, or you haven't cleared the cache after enabling it. If this continues to be a problem, please make a post at https://forum.mautic.org/c/support where the community will be able to help you troubleshoot this further.
