### ISSUE TITLE
Filters for Dynamic Web Content no longer respect "Including" logic [$100]

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#10797]
### Mautic Version

4.0.0

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When creating a filter for slot-based dynamic web content, using an including filter like this...
![image](https://user-images.githubusercontent.com/866855/151009222-75553652-49ae-48f4-844b-f9b2e529447a.png)
...should work and did work in version 3. However, since the upgarde to version 4, only equals works. 

It seems that since version 4.0, the "Including" operator no longer works and always returns false, causing any dynamic content using "Including" and a select field to never show.  If you use the same field and value with equals, it works just fine.

### How can we reproduce this issue?

Step 1: Create a slot-based dynamic web content block
Step 2: Set the filter to Country Including [your country] [another country]
Step 3: Embed the slot on a web page
Step 4: validate it doesn't load
Step 5: Modify the filter to be Country Equals [your country]
Step 6: validate content does load

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the bug report @stevedrobinson

**Comment by stevedrobinson** [comment]
FYI - I posted a bounty for this: https://app.bountysource.com/issues/106643135-filters-for-dynamic-web-content-no-longer-respect-including-logic

**Comment by RCheesley** [comment]
@stevedrobinson  have you checked this in recent versions? We did push a fix for operators in filters I believe, in 4.2.1, but this might be affecting a different part of Mautic.

**Comment by stevedrobinson** [comment]
This is still an issue as of 4.2.1. I see there is a possibly relevant fix in 4.2.2. I'll get that upgrade in place soon and retest.

**Comment by stevedrobinson** [comment]
@RCheesley I have verified this is still an issue in version 4.2.2.

**Comment by escopecz** [comment]
@stevedrobinson I wanted to check how the bounty program works but instead I found out this is fixed in https://github.com/mautic/mautic/pull/10871

@RCheesley how should it work in this case? It was fixed by an Acquian.

**Comment by stevedrobinson** [comment]
If it's against Acquia policy or there's no way for acquia to take the bounty, I'm happy to donate it to the project if it goes unclaimed.

**Comment by escopecz** [comment]
There are small issues with the fix and claiming the bounty:
1. 3 Acquia developers have commits in that PR so no one person can claim the bounty for themselves.
2. All of them (us) worked on it during the business hours so they were paid for their work.

I think that donating the bounty to the Mautic OS project would be the best option 🙂

**Comment by escopecz** [comment]
We need one more test and approval on that PR to get it merged to the next release...
