### ISSUE TITLE
Tag Manager does not disappear from right menu even if disabled from plugins list

### ISSUE THREAD

**Issue by tejasync** [mautic/mautic#10811]
### Mautic Version

4.0.0

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Chrome

### What happened?

Mautic Version: 4.1.2

The tag menu doesn't respect the Tag Manager plugin setting (Published: No/Yes) from the plugins list.
Ref:
![Screenshot 2022-01-31 at 19 13 06](https://user-images.githubusercontent.com/54406786/151804587-36b03457-f6a6-4366-a778-79bde68975b0.png)
 

### How can we reproduce this issue?

Step 1: Go to `/plugins` page
Step 2: Find Tag Manager and click on it (observe it is disable by default - still the `Tag` menu appears in the left side menu)
Step 3: Now enable it and click save and close (observe the `Tag` menu in the left side menu)
Step 4: Now again, go back to the `/plugins` page, and disable the Tag Manager from the option by clicking it
Step 5: Observe, `Tag` menu still appears in the left side menu

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Confirmed - just tested in dev mode and the menu item is there despite the tag manager being disabled.

**Comment by RCheesley** [comment]
Not stale
