### ISSUE TITLE
Problem with Asset link

### ISSUE THREAD

**Issue by prowebspot** [mautic/mautic#1082]
I have big problems with asset links after v1.2.1. 
For example this a href="{assetlink=44}" after saving will be converted to a href="%7Bassetlink=44%7D"  and download doesn't work.
The links saved before upgrade look ok.

**Comment by alanhartless** [comment]
Thanks for reporting this.  It's been fixed in #1082 and will be part of 1.2.3.  You can patch your Mautic now to fix this till the release.

https://github.com/mautic/mautic/pull/1083/files
