### ISSUE TITLE
SSO becomes forcefully the default once enabled

### ISSUE THREAD

**Issue by andres-asm** [mautic/mautic#10832]
### Mautic Version

4.1.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Once SSO is enabled, everyone is forced to use SSO login, this is quite difficult since we may give customers access and they may not have an account on our organization.

There should be a switch that allows us to define which login method takes precendence, or alternatively use the normal login at all times with an option to use a login provider

### How can we reproduce this issue?

Step 1: enable SSO with any provider
Step 2: browse to the main page without having an account in the provider

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by andres-asm** [comment]
as a workaround, on nginx at least what I did was

```
    location = / {
       return 301 https://mymauticinstance.com/s/login;
    }
```

Then all users get greeted by the default login page regardless of their location, and we internally can still use the login provider

**Comment by RCheesley** [comment]
Hi @fr500 I'm pretty sure that this is by design, and therefore allowing multiple different login types to co-exist would be a feature request. Can you please post that at https://forum.mautic.org/c/ideas where the community can discuss whether this is something which others would value? Thanks!
