### ISSUE TITLE
Add functional tests for header/footer scripts in landing pages

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#10835]
Works

![image](https://user-images.githubusercontent.com/462477/152553409-8dd3d42f-59a7-4691-b7c7-7dbb6318c0c6.png)

Probably we should add basic functional tests.
Added header/footer script to createTestPage and then check it in content of page.

https://github.com/mautic/mautic/blob/a0ca40058260f9274570e124b8491baf7af4039b/app/bundles/PageBundle/Tests/Controller/PageControllerTest.php#L138

_Originally posted by @kuzmany in https://github.com/mautic/mautic/pull/9695#pullrequestreview-873221096_

**Comment by RCheesley** [comment]
@alfredoct96 would you be able to address this suggestion please?

**Comment by alfredoct96** [comment]
> @alfredoct96 would you be able to address this suggestion please?

@kuzmany i added this test

```
     /**
     * Check that page contains head script and footer script
     */
    public function testScriptsPage(): void
    {
        $model = self::$container->get('mautic.page.model.page');
        $page  = $model->getEntity($this->id);
        $this->client->request('GET', '/'.$page->getAlias());
        $clientResponse         = $this->client->getResponse();
        $clientResponseContent  = $clientResponse->getContent();
        $this->assertStringContainsString($page->getHeadScript(), $clientResponseContent, 'The return must contain the head script');
        $this->assertStringContainsString($page->getFooterScript(), $clientResponseContent, 'The return must contain the footer script');
    }
```

but `$clientResponse->getContent();` return empty string, i tried also with `$page->getContent();` but returns empty array.
How can i get the content of the page to check if script exists inside it?

**Comment by alfredoct96** [comment]
> > @alfredoct96 would you be able to address this suggestion please?
> 
> @kuzmany i added this test
> 
> ```
>      /**
>      * Check that page contains head script and footer script
>      */
>     public function testScriptsPage(): void
>     {
>         $model = self::$container->get('mautic.page.model.page');
>         $page  = $model->getEntity($this->id);
>         $this->client->request('GET', '/'.$page->getAlias());
>         $clientResponse         = $this->client->getResponse();
>         $clientResponseContent  = $clientResponse->getContent();
>         $this->assertStringContainsString($page->getHeadScript(), $clientResponseContent, 'The return must contain the head script');
>         $this->assertStringContainsString($page->getFooterScript(), $clientResponseContent, 'The return must contain the footer script');
>     }
> ```
> 
> but `$clientResponse->getContent();` return empty string, i tried also with `$page->getContent();` but returns empty array. How can i get the content of the page to check if script exists inside it?

up

**Comment by kuzmany** [comment]
@alfredoct96 can you push it as PR? We can look on it then
