### ISSUE TITLE
 Message erro: Hubspot Erro internal error

### ISSUE THREAD

**Issue by HermanMonteiro** [mautic/mautic#10840]
### Mautic Version

3.3.x series (not supported)

### PHP version

7.3.33

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The following appears in the notification UI in Mautic indicating an internal error with the Hubspot integration. I am seeing this appear daily. There is no error in the log.
![erro mautic](https://user-images.githubusercontent.com/7132904/153006693-b9a37122-87f1-460a-8cc6-96090d455dda.png)

### How can we reproduce this issue?

Step 1: Open Mautic dashboard and observe notification UI
Step 2: View app/logs/ for matching error message

### Relevant log output

There is no error in the log about this issue.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @HermanMonteiro, unfortunately we don't support bugs with Mautic 3 any more - please update to Mautic 4.1.2 and lets us know if this persists.
