### ISSUE TITLE
Mautic ID not merged after form submit

### ISSUE THREAD

**Issue by ItDoBeNord** [mautic/mautic#10855]
### Mautic Version

4.1.x series

### PHP version

7.4.25

### What browsers are you seeing the problem on?

Chrome

### What happened?

Hi,

On our website we have a few forms. In Chrome the tracking doesn’t seem to work properly, however it works correctly in Firefox. Are you guys aware of any issues in Chrome?

### How can we reproduce this issue?

Below I describe how I expect it to work and how it currently works in Firefox:

  1.  When I visit the page and accept the cookies a Mautic ID is created in the local storage. For example 123456
  2.  When I submit a form on the site and I’m a know lead the Mautic ID in the local storage changes to the ID I have in Mautic. For example 727272
  3.  All the page hits I do are registered under 727272
  4.  When I want to submit more forms the questions which are answered already in Mautic are hidden.

In Chrome step 2 doesn’t happen. So when I’m a known user the form submit happens under  ID 727272, but all the page hits are registered under ID 123456.

This is a bit annoying because we for example would like to track if users look at specific pages.

The site is built on Wordpress, I added the forms using the Wordpress plugin. The script is loaded after users accept the cookies via Google Tag Manager.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, can you please post this over at https://forum.mautic.org/c/support where the community will be able to help you with troubleshooting the issue and your configuration? Then if it is found to be a bug with Mautic rather than your configuration we can raise a bug as appropriate.

Thanks!
