### ISSUE TITLE
Deduplicate cron is taking too long, any way to speed up?

### ISSUE THREAD

**Issue by russkiimike** [mautic/mautic#10867]
### Mautic Version

4.1.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Resiurces: 8 vCPUs
16GB / 80GB Disk

My problem is: Running deduplicate freezes at around 100k contacts mark!

These errors are showing in the log: N/A

Steps I have tried to fix the problem: Tried installing the custom deduplicate plugin but there's a compatibility issue with 4.1

Is there a way to increase the deduplicate cron speed? Increasing batch limit like with the segments updates? 

### How can we reproduce this issue?

Step 1: Install Mautic with 281k contacts
Step 2: Run deduplciate

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @russkiimike please post this discussion at https://forum.mautic.org/c/support - that is where we provide community support. GitHub is for raising bugs with Mautic. Thanks!
