### ISSUE TITLE
Push to integration button in lead management

### ISSUE THREAD

**Issue by zk89** [mautic/mautic#1086]
I believe it would be very helpful to have a button to manually push a lead to integration (CRM) somewhere in the lead management section or in edit lead. Maybe in the lead management to select a group of leads you wish to push to integration and in edit lead to push a specific lead. Would help with offline efforts i.e. talking with the lead on the phone and based on the conversation moving them to a CRM manually. Posted this on the forums: https://www.mautic.org/community/index.php/955-suite-sugarcrm-with-mautic

**Comment by gpassarelli** [comment]
+1

**Comment by dmarkotter** [comment]
+1

**Comment by revisely** [comment]
+1

**Comment by hansakoch** [comment]
+1

**Comment by 2guti2** [comment]
+1
