### ISSUE TITLE
Migration Version20201120122846 has weak checks on foreign keys that causes migration to fail

### ISSUE THREAD

**Issue by Aerendir** [mautic/mautic#10877]
### Mautic Version

4.1.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The migration fail to complete.

### How can we reproduce this issue?

I don't know precisely how to reproduce the issue.

But the problem is in the way the migration checks the existence of foreign keys: it assumes they are deterministic, but they are not.

I explained in details the bug in https://github.com/mautic/mautic/issues/10870#issuecomment-1045982049 and in https://github.com/mautic/mautic/issues/9129#issuecomment-1044958793

### Relevant log output

```shell
SQLSTATE[42S01]: Base table or view already exists: 1050 Table '*_campaign_summary' already exists
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for raising this and for the PR @Aerendir - much appreciated!
