### ISSUE TITLE
Segment membership select box with preselected first segment

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#10875]
### Mautic Version

4.2.x series

### PHP version

7.4

### What happened?

If I select segment membership filter with include operator I have pre-select value - first of segment

![image](https://user-images.githubusercontent.com/462477/154717964-9365baeb-52d7-4359-972b-ab385755d085.png)

### How can we reproduce this issue?

Step 1:  Try create segment membership filter with include/exclude operator

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by kuzmany** [comment]
@escopecz looks like coming from segments refactoring

**Comment by escopecz** [comment]
Yea, that will be. We don't have fix for it after 2 years of using it. It never became a priority as it has simple workaround just removing the pre-selected option and select the one(s) you want.
