### ISSUE TITLE
Before_Save and After_Save Mautic Contact - Custom

### ISSUE THREAD

**Issue by laabidi21** [mautic/mautic#10880]
### Mautic Version

4.1.x series

### PHP version

7.4.25

### What browsers are you seeing the problem on?

Chrome

### What happened?

it is possible to create a custom code before or after the Update of mautic -Contact, for example to put "Updated" Tag or to make other changes, or to send an Email... ?
is it possible to create a Custom Code for the Contact Module, if yes..  after a Mautic-Update the Custom Code will be overwritten by the new Code?

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @laabidi21 please post questions and how-do-I requests at https://forum.mautic.org/c/support as GitHub is for reporting bugs with Mautic, the forums are for getting support. 

Thanks!
