### ISSUE TITLE
Form editor: Assigning bootstrap col-*-12 CSS class to a form input container attribute breaks form editor UI.

### ISSUE THREAD

**Issue by Absynth723** [mautic/mautic#10881]
### Mautic Version

4.1.x series
4.2.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Chrome, Safari

### What happened?

When creating a custom form, I tried duplicating our main website's look and feel (to properly embed the forms without a design break). The original forms contain the following css classes either in the form input elements or in their containers:
- col-xs-12 
- col-sm-4 
- col-md-3 
As soon as I assign `class="col-xs-12"` to a form element and save it, the "form fields" pane becomes unusuable. I can neither click on the "edit" or "trash" buttons to delete the offending fields, effectively locking me out of editing this form.
I believe this can be fixed by simply not using CSS to display the form field previews in the "Fields" pane.

### How can we reproduce this issue?

Step 1: Create a new form and at least one form field like a text field
Step 2: Assign `class="col-xs-12"` to its container element and save
Step 3: Try to click on edit/trash button in the "form fields" pane.
Step 4: Weep silently.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by Absynth723** [comment]
Screenshot of the non-functioning form fields pane: ![Bildschirmfoto 2022-02-21 um 12 49 25](https://user-images.githubusercontent.com/3737316/154949804-a221b1d9-e4b3-4d33-a7f2-5cae0bb3fa05.png)

**Comment by joshua62493** [comment]
I have seen this but spamming the button (double click for me) does seem to work to get the edit function up. I have only seen this on col-*-12 and not any smaller ones

**Comment by Absynth723** [comment]
Out of 3 form elements, spamclicking on the edit button only works for one, but not the other two. It's a strange behavior, indeed.

**Comment by joshua62493** [comment]
The issue is that setting the element to col-*-12 fills the entire edit section. You can manually edit it for the live page by using the inspect element, finding the col-*-12 and changing it to say 2
![image](https://user-images.githubusercontent.com/37959801/155154796-f5cfa7e7-25eb-4a35-938f-804b90531e25.png)

Essentially the buttons are within the container of the form, and setting the value to fill the container you are putting the element over the buttons

If you still wish to use the dynamic content you may be able to work around this bug by also including the container class. For example class="container col-xs-12" as this appears to leave the buttons working

**Comment by Absynth723** [comment]
@joshua62493 yes, the first part of your comment fixes the symptoms and I can work with the form again, thanks! I'll play around a little more with my test case to find something that works.
I still think that including the CSS classes for the production form page on the edit tabs isn't desirable behavior, because these tabs aren't supposed to be a design preview, just a field preview/selection page.
(Side note, possibly unrelated, what does the "Render CSS" switch do? Seems to have no effect on my bug turning it on or off.)

**Comment by joshua62493** [comment]
I wish I knew but unfortunately I'm not staff for Mautic. I'm an independent developer who was going to build a platform like this until it became available through Softaculous.

**Comment by RCheesley** [comment]
Thanks for all the troubleshooting folks! If someone would like to address this, here are the step by step instructions for creating a pull request: https://contribute.mautic.org/contributing-to-mautic/developer - feel free to shout if you need any help with any steps, just hop into Slack (https://mautic.org/slack to get an invite) and join #t-product.

FYI @joshua62493 Mautic does not really have staff - aside from myself as Project Lead, we are pretty much all volunteers who use Mautic and help to make it better.

**Comment by RCheesley** [comment]
> Side note, possibly unrelated, what does the "Render CSS" switch do? Seems to have no effect on my bug turning it on or off.

This will use the CSS from your Mautic theme if provided, rather than inheriting the CSS from the website. https://docs.mautic.org/en/components/forms/managing-forms#form-style (could definitely improve the docs on this!)
