### ISSUE TITLE
Integration to Sendgrid (API)

### ISSUE THREAD

**Issue by TiagoRodrigues** [mautic/mautic#1088]
Hey guys, thanks for the support and working hard. I'm bringing a problem that occurred to me and I found another guys with the same problem.

Reference
https://www.mautic.org/community/index.php/1051-sendgrid-connection-error

Problem:
Using Sendgrid API retrieves this error:

Connection could not be established with host smtp.sendgrid.net  [Connection timed out #110] Log data: ++ Starting Mautic\EmailBundle\Swiftmailer\Transport\SendgridTransport !! Connection could not be established with host smtp.sendgrid.net  [Connection timed out #110]
++ Starting Mautic\EmailBundle\Swiftmailer\Transport\SendgridTransport !! Connection could not be established with host smtp.sendgrid.net  [Connection timed out #110]

Workaround:
1 - "Service to send emails through" -> Other SMTP Server
2 - SMTP Host -> smtp.sendgrid.net 
3 - SMTP Port -> 465
4 - SMTP encryption type -> SSL
5 - SMTP authentication mode -> Login
6 - Username for the selected mail service -> Put your sendgrid username or email
7 - Password for the selected mail service -> Your Sendgrid Password

I was using Mandrill and tried to use my Sendgrid acc to test and I got the same problem. That's how I could configure Sendgrid.

**Comment by gpassarelli** [comment]
Hi Tiago, I'm using my Mautic, with Sendgrid without any problem. 
Using the "Sendgrid" SMTP server option.

**Comment by alanhartless** [comment]
If you're on a vps, make sure the outgoing port of 587 if using the default sendgrid service is open. If shared hosting, might have to contact them to open it for you. Or the only alternative if a shared host refuses to open is your noted work around. 

But we would like to convert to using sendgrids API like we did for Mandrill so marking this as a feature request.

**Comment by wderuijter** [comment]
+1 for the sendgrid API feature request.

**Comment by zstephen** [comment]
+1 #1488

**Comment by MaxOnTheHill** [comment]
+1  has anything been done on this, or a properly integrated API driven bulk email sender integration???

SMTP integration doesn't really cut it (for .com or .org instances) ... so would love to see this being available as an API ... now that Mandrill moved in-house.

**Comment by zstephen** [comment]
Hi @MaxOnTheHill  Check out #1488 it's seen a bit more progress, while it's for Sparkpost, it's aimed at the same issue given the changes by Mandrill. @jfgrissom built an API, I think it has an outstanding issue or two before it's able to become a PR for 2.1.0
