### ISSUE TITLE
contact record event timestamps weird

### ISSUE THREAD

**Issue by quadcom** [mautic/mautic#10892]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

A contact record that came in through an API push from Calendly via Zapier shows a "Contact Created" date of "Today at 8:37 pm" yet has a Contact Identified date of "Yesterday, 8:37 pm"

![image](https://user-images.githubusercontent.com/7085931/155388066-2e7545fe-3bb8-4c10-9cf7-0d34f80b7b11.png)

### How can we reproduce this issue?

Not exactly sure how to go about recreating this issue. I will keep a watch on future contact creations via the API and see if this happens again.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
We have a [fix](https://github.com/mautic/mautic/pull/10375) for this coming in 4.2.1 so I will close this issue.
