### ISSUE TITLE
Contacts page > Search for ip: xxx.xxx.xxx.xxx does not work

### ISSUE THREAD

**Issue by quadcom** [mautic/mautic#10893]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

An anonymous visitor hit my site and was tracked by IP address. I searched the contacts by IP using the delimiter "ip:"

![image](https://user-images.githubusercontent.com/7085931/155392120-cc1dd665-fb23-4284-b84f-dd173a8ac086.png)

With the IP added. It showed no results.

![image](https://user-images.githubusercontent.com/7085931/155391991-22bd9457-b071-4bc9-83b4-e748ed237be4.png)

But it is there.

![image](https://user-images.githubusercontent.com/7085931/155391940-995a0e73-af40-465e-928c-11d9dd5801a7.png)

### How can we reproduce this issue?

Try a contact search using the modifiers

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @quadcom this is probably because you are not showing anon visitors. To do that you need to concatenate the two:

`ip:<IP Address> is:anonymous`
