### ISSUE TITLE
grapesjs edit source uses previous email

### ISSUE THREAD

**Issue by donbowman** [mautic/mautic#10895]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

create 2 channel emails as mjml.

open first. uilder. select edit code. mod. exit, save and close.
re-open 2nd. builder. edit code. it has the mjml of the first one. the save+cancel buttons are now broken.

4.2-rc1

### How can we reproduce this issue?

create 2 channel emails as mjml.

open first. uilder. select edit code. mod. exit, save and close.
re-open 2nd. builder. edit code. it has the mjml of the first one. the save+cancel buttons are now broken.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by donbowman** [comment]
https://github.com/mautic/mautic/pull/10781 is likely the culprit

**Comment by RCheesley** [comment]
@donbowman please test the PR #10781 - we can't merge the PR without testing and there seems to be an issue which needs to be reviewed / addressed over there, maybe you can help?

**Comment by donbowman** [comment]
that pr was closed without merging.
perhaps you mean #10847 ?

**Comment by donbowman** [comment]
so i have the same experience as ref in #10847 (in https://github.com/mautic/mautic/pull/10847#issuecomment-1034910118), it just doest't work.
i can't open the editor twice to check.

**Comment by RCheesley** [comment]
Yes sorry that was the one! Please leave test results on the PR itself ;)
