### ISSUE TITLE
The Email Builder Example of GrapeJS using {contactfield=firstname} doesn't work. Doesn't recognise "{}"

### ISSUE THREAD

**Issue by Inbroch** [mautic/mautic#10905]
### Mautic Version

4.1.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Chrome

### What happened?

When I'm using the GrapeJS Builder, it won't recognise the {fieldname} in the text fields. The guide and some old bloke on youtube says you can use {contactfield=firstname} but when I used that in the builder and when I sent the test message it said:

Hi [firstname]

I tried in the plain text field and it as I was typing it recognised the {} but then when the sample email got sent, again, it just said:

Hi [firstname]

When I went to use the legacy builder, it wouldn't let me edit any text fields. I followed teh instructions with clearing the cache and still wouldn't work.

### How can we reproduce this issue?

Use the GrapeJS Builder and type {contactfield=firstname} then send a sample email to yourself.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @Inbroch thanks for raising this issue. 

Sending a test email will never (at present) replace the contact fields, as there is no contact data to merge. It is recommended that you set up a test segment with just you in it, which you can use for testing emails in this way.

Please ask for support at https://forum.mautic.org/c/support if you get stuck as this is not a bug with Mautic, which is what we use GitHub issues for. 

Thanks!
