### ISSUE TITLE
Conditional on contact field value preferred locale

### ISSUE THREAD

**Issue by godiez** [mautic/mautic#10906]
### Mautic Version

3.3.x series (not supported)

### PHP version

7.3.33

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Hi,

There's a bug in campaign builder, in condition option (Form field value option), always fails when 'preferred locale' is selected.

When you set up a condition on 'Preferred Locale' field, for example, ![image](https://user-images.githubusercontent.com/6525902/156321307-123d4559-b717-4181-82bd-a543b60640c2.png)

The value 'en' is store with 'English' text. Here it is:

{....s:5:"field";s:16:"preferred_locale";s:8:"operator";s:1:"=";s:5:"value";s:7:"**English**";}, it might be 'en'.

Thanks!

### How can we reproduce this issue?

Step 1: 

- Create a campaign with the 'preferred locale' (no matter which operator do you use) condition
- Run the campaign 
- Always fails

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @godiez and thanks for raising the bug. Unfortunately we no longer support Mautic 3.

If this issue persists in 4.2.0 please ask for the issue to be re-opened.
