### ISSUE TITLE
Forms with 'page breaks' doesn't aling with top of the page after clicking 'next' button.

### ISSUE THREAD

**Issue by misterdipesh** [mautic/mautic#10901]
### Mautic Version

4.1.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### What happened?

We have created a form with multiple page breaks. As I click the next button the content of the following pages loads from the middle of the form, it doesn't align with the header at the top of the page, which lets a few fields above the visible area of the screen.
The issue persists both: for forms placed on a Mautic landing page and for any method I may use to insert it on an external page.
I have tried adding an event listener with the function " window.scrollTo(top); " on the next button itself and it didn't seem to be working. The function works on reload not when the button is clicked. 
I also tried to add up the function "window.scrollTo(top);" inside the  mautic js file. I added this function inside the jquery nextButoon.onClick =function(parms...){
window.scrollTo(top);
.......
}
but none of those works, the issue persists the same.

Expected behavior: Form to load from the top in the next oncoming form page.
Actual behavior: Form loading from the middle of the page leaving a few fields above it.

I guess it must have a very simple solution, but I am clueless by now. I will appreciate any direction for fixing the issue.

### How can we reproduce this issue?

Step 1: Create a form with multiple pages.
Step 2: Apply any theme  and implement it via a script, automated or manual method
Step 3: View the page live. 
Step 4: Click on the Next button

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for raising the issue @misterdipesh - hopefully we can get some eyes on it soon!
