### ISSUE TITLE
Unable to attach a link to a button.

### ISSUE THREAD

**Issue by fintechee** [mautic/mautic#10918]
### Mautic Version

4.2.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

Unable to attach a link to a button.

### How can we reproduce this issue?

Step 1: Open the builder of an email template(Because creating a new template will only bring you an empty editor panel, so you need to clone an existing email template to test).
Step 2: Add a button.
Step 3: Try to attach a link to the button.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by adiux** [comment]
@fintechee this sounds like you have some general problems with your setup. Are there any errors in the browser console?

**Comment by fintechee** [comment]
@[adiux](https://github.com/adiux)
Thank you for your reply.
The problem is, when I moved the mouse over the "link" on the button, the "link" changed to a "move" icon soon.
So, I can't link anything to the button. No error message in the console.

**Comment by fintechee** [comment]
After I switched my VPN, it worked.
So, seems it's an issue caused by network.
