### ISSUE TITLE
Translation config is not working.

### ISSUE THREAD

**Issue by TiagoRodrigues** [mautic/mautic#1091]
After changing translation, the Dashboard doesn't change. Also tried changing the user Language and every possible configuration.

Tried to clear cache. Deleted the content inside cache folder before and also tried deleting after, no changes.

Tried with different languages.
![language](https://cloud.githubusercontent.com/assets/3497845/10819936/b0be12b8-7e29-11e5-8fe5-4c9f0daefda5.png)

Also checked inside "languages" folder, it's everything ok, downloaded.
![cpanel file manager v3](https://cloud.githubusercontent.com/assets/3497845/10820048/24a9e1c0-7e2a-11e5-8930-60d22cc43fa0.png)

Latest Version of Mautic. 
System Status: Everything Writable.

**Comment by escopecz** [comment]
There is already fix for it: https://github.com/mautic/mautic/pull/1080

It'd be nice if you could test it. I just did.

**Comment by TiagoRodrigues** [comment]
Tested and Working.

Thanks.

**Comment by andreab79** [comment]
hi, i have the same problem in last mautic version 2.12, with php 7. i see language and also theme not change. i see in translations folder, language folder it_IT is downloaded and in local.php file, modifies are written but in control panel nothing happens. tx for reply

**Comment by andreab79** [comment]
solved, was an issue related to permissions. right way to install is

1. upload files
2. set 777 permissions for folder config, logs and cache
3. launch installation
4. set language in configuration and user profile

**Comment by escopecz** [comment]
Just FIY, setting permissions to 777 is not recommended for security reasons. Directories should be 775, files 664. The key is to use the same user/group which is not root for editing (uploading) files as the server.

**Comment by andreab79** [comment]
Hi John, really tx!
