### ISSUE TITLE
Db migration problems 4.1.2 - 4.2

### ISSUE THREAD

**Issue by steveb85** [mautic/mautic#10912]
### Mautic Version

4.2.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Chrome, Safari

### What happened?

During Update Migration i get an SQL error that campaign_summary table exists. 
I check my php, and the table exists almost identically as requested in sql statement, but the INDEX IND_hash is slightly different (they finish the same but start differently) 

### How can we reproduce this issue?

Step 1:  php. ….. update find  -> update apply.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by steveb85** [comment]
![mautic db](https://user-images.githubusercontent.com/50031994/156188128-753862f2-2589-4d5e-8467-e94df2927486.png)
![mautic update migrate](https://user-images.githubusercontent.com/50031994/156188150-d462e734-b815-4864-99eb-63bb4e136b6c.png)

**Comment by RCheesley** [comment]
Hi @steveb85 thanks for reporting the issue but we are already tracking it here: https://github.com/mautic/mautic/issues/10870 so please take a look and check out the [relevant PR](https://github.com/mautic/mautic/pull/10878).
