### ISSUE TITLE
4.2 Segments not sortable by headers

### ISSUE THREAD

**Issue by healthstatus** [mautic/mautic#10925]
### Mautic Version

4.2.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Chrome

### What happened?

On the segments page, the system is defaulting to sorting by Modified date, you can click the other headers, but sorting on that header does not happen.

### How can we reproduce this issue?

Step 1:   Go to Segments page
Step 2: click on the column headers to sort by that column

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Confirmed this bug - @alfredoct96 can you take a look as I think it was your PR that introduced the new columns and the sort order change. Thanks!

**Comment by alfredoct96** [comment]
> Confirmed this bug - @alfredoct96 can you take a look as I think it was your PR that introduced the new columns and the sort order change. Thanks!

I fixed it on this PR https://github.com/mautic/mautic/pull/10938
