### ISSUE TITLE
Java console returns No UploadPath Found after updating mautic and enabling grapeJS (again)

### ISSUE THREAD

**Issue by markusrock** [mautic/mautic#10921]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Firefox

### What happened?

After updating from 4.1.2. to 4.2.0 I changed from the Legacy Editor to grapeJS editor. But the Builder does not load.

Basically it is the same as here: https://github.com/mautic/mautic/issues/10473
`mautic:plugins:reload` does not the jpb for me. I deactivated also the plugin and reloaded it again. 

### How can we reproduce this issue?

Step 1: Update from 4.1.2 to 4.2.0
Step 2: Actiavete grapeJS
Step 3: Try to open the email builder

### Relevant log output

```shell
Uncaught Error: No uploadPath found
    l builder.service.js:32
    s builder.js:21
    onclick 220:1
    trigger libraries.js:683
    trigger libraries.js:688
    each libraries.js:153
    each libraries.js:144
    trigger libraries.js:688
    name libraries.js:796
    buttonClick app.js:73
    dispatch libraries.js:465
    handle libraries.js:451
    add libraries.js:453
    on libraries.js:445
    each libraries.js:153
    each libraries.js:144
    on libraries.js:445
    on libraries.js:481
    onPageLoad app.js:73
    each libraries.js:153
    each libraries.js:144
    onPageLoad app.js:72
    each libraries.js:153
    each libraries.js:144
    onPageLoad app.js:69
    <anonymous> 220:8716
builder.service.js:32:12
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by markusrock** [comment]
I tried with Firefox and Edge, so It seems to be not a browser issue.

**Comment by RCheesley** [comment]
Thanks for raising the issue @markusrock - did you specifically try this step: https://github.com/mautic/mautic/issues/10473#issuecomment-928374282?

**Comment by markusrock** [comment]
Yes I tried that.

**Comment by RCheesley** [comment]
OK thanks! Hopefully we will be able to get to the bottom of it!

**Comment by adiux** [comment]
This error indicates that there is no image upload path configured in the HTML. Please double-check your HTML source on the email /edit route. The image path should be written to a form field.

**Comment by markusrock** [comment]
> 

Can you help me out here, where should I check that?
![Screenshot 2022-03-09 091708](https://user-images.githubusercontent.com/73632724/157400539-9a2de46d-5c8a-431d-a521-15031c4e08c4.png)

With the legacy editor, uploading images just works fine.

**Comment by markusrock** [comment]
Little addition: Upgrading to 4.2.1 did not solve the issue.
Edit 03.05.2022; Upgrading to 4.2.2 did not solve the issue.
Edit 07.07.2022: Upgading to 4.4.0 did not solve the issue.
Edit 19.08.2022: Upgading to 4.4.1 did not solve the issue.

**Comment by tjosm** [comment]
I'm having this too.

**Comment by markusrock** [comment]
> I'm having this too.

Which version are you testing with?

**Comment by markusrock** [comment]
I've tested this again with 4.4.5 and the problem still exists for me.
