### ISSUE TITLE
[Feature request] Update Points from API

### ISSUE THREAD

**Issue by trops** [mautic/mautic#1092]
I would like the ability to update the points for a lead using the API just as I can update the users account fields. There is no way currently to update points either in the Admin Panel or API. The only way to update points is in the actions and they are currently not working.

Thank you so much!

**Comment by npracht** [comment]
Hi,

I meet the same need. Which would be very appreciable when you connect the software to another app for instance that has also some scoring rules closely link to the behavior of a lead on this app.

N.

**Comment by escopecz** [comment]
Added to 2.3
