### ISSUE TITLE
Invalid callback elFinderSession::session_start_error, cannot access protected method elFinderSession::session_start_error()Your bug title goes here!

### ISSUE THREAD

**Issue by WhatsOnMautic** [mautic/mautic#10939]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

I can't edit or create campaigns after updating mautic version to 4.2.0

### How can we reproduce this issue?

Step 1: After logging in try to create a campaign and send a test email. when you will try to save the campaign you will see the error that time.
You will see "Uh oh! I think I broke it. If I do it again, please report me to the system administrator! 
500 Internal Server Error
Mautibot
[Report an issue](http://mau.tc/report-issue)" error.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the bug @WhatsOnMautic but without your log files, we can't really troubleshoot.

Please add to the issue description in the section where it is requested, you will find them in var/logs.

**Comment by WhatsOnMautic** [comment]
[mautic_prod-2022-03-08.zip](https://github.com/mautic/mautic/files/8202801/mautic_prod-2022-03-08.zip)
Please check it

**Comment by WhatsOnMautic** [comment]
@RCheesley please check the previous file and help me
