### ISSUE TITLE
Search info text formatting (minor bug after upgrade to 4.2.0)

### ISSUE THREAD

**Issue by sigreer** [mautic/mautic#10936]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Chrome

### What happened?

Search help text is slightly broken - escaped new lines ``\n`` and the **Search Commands** header does not appear on a new line.

### Search Help
Search Operators:\n
\+ (plus sign) - Search for the exact string (i.e. if 'admin', then 'administrator' will not match)\n
! (exclamation mark) - Not equals string\n
" " (double quotes) - Search by phrase\n
( ) (parentheses) - Group expressions together.\n
OR - By default the expressions will be joined as AND statements. Use the OR operator to change that.\n
% - Use the % as a wildcard to search for specific names or values in a phrase (i.e. to find all companies with the word ‘Technologies’ then type '%Technologies%')**Search commands**
is:anonymous
is:unowned
_...seems ok after this point..._

### How can we reproduce this issue?

Step 1:  Upgrade from 4.1.1 (unsure if prevalent on newly installed 4.2.0) - could relate to DB upgrade.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @sigreer thanks for reporting this, I am not able to replicate it at my end - which screen were you in where you noticed this bug?  Can you maybe show a screenshot? Thanks!
