### ISSUE TITLE
Dashboard - Application throws HTTP 500 when user apply filter to report

### ISSUE THREAD

**Issue by dadarya0** [mautic/mautic#10945]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

Application throws HTTP 500 when user apply filter to report "best email read hours"

Issue is related to PR - https://github.com/mautic/mautic/pull/7271

### How can we reproduce this issue?

1. Create new dashboard widget **Best email read hours**
2. Once report is configured apply filter like

  - Company filter
  - Campaign filter
  - Segment filter
3. Click Save button
4. You will get 500 internal server error.

### Relevant log output

```shell
500 Internal Server Error - Call to a member function createQueryBuilder() on null

/app/bundles/EmailBundle/Stats/Helper/FilterTrait.php:31 at
/app/bundles/EmailBundle/Model/EmailModel.php:1885 at Mautic\EmailBundle\Model\EmailModel -> addCompanyFilter ( object(QueryBuilder), '1' )
/app/bundles/EmailBundle/EventListener/DashboardBestHoursSubscriber.php:86 at Mautic\EmailBundle\Model\EmailModel -> getBestHours ( 'date_read', object(DateTime), object(DateTime), array(), true, null )
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for raising the bug @dadarya0 - looks like this has been around for a little while.

Possibly related older issues:
https://github.com/mautic/mautic/issues/10640
https://github.com/mautic/mautic/issues/10493
