### ISSUE TITLE
[forms & permissions] issue with cloning an existing form with a reduced role

### ISSUE THREAD

**Issue by raramuridesign** [mautic/mautic#10943]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

We have created different **roles** for users to perform different functions.
Our role focuses specifically on the **form permissions**.

See screenshot below.
Using these permissions, the user is **UNABLE to CLONE an existing form**.

![image](https://user-images.githubusercontent.com/902376/157259704-6a77cea6-6348-48c7-89bd-553d988f2de5.png)

### How can we reproduce this issue?

Step 1:  Set up a new role, with the permissions as per the screenshot.
Step 2: Login with a user assigned to the role.
Step 3: Create a form from scratch.
Step 4: Attempt to clone the new form.

### Relevant log output

```shell
no logs available
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
@raramuridesign can you please share a screenshot for form permissions ? You show assets permissions but talking about form rights issues.
Thanks !

**Comment by raramuridesign** [comment]
@npracht Sorry about that, new screenshot below.

![image](https://user-images.githubusercontent.com/902376/157259651-a66cc4d7-ed2f-45d5-94e0-55ad7f59e101.png)

**Comment by npracht** [comment]
No problem ! Thank you for the extra instructions.

**Comment by charles-talk2us** [comment]
Hello @npracht, have you managed to have a look at this issue the @raramuridesign raised above?

**Comment by npracht** [comment]
Hello, i checked it but didn't plan to work on solution for this issue. If one of you would like to offer some of your time to dig into it, that would be lovely :)
