### ISSUE TITLE
Form submission does not create company

### ISSUE THREAD

**Issue by tejasync** [mautic/mautic#10949]
### Mautic Version

4.2.x series

### PHP version

PHP 7.4.28

### What browsers are you seeing the problem on?

Chrome

### What happened?

https://github.com/mautic/mautic/pull/9461 PR changed the company unique field from company email to company name.

Now if your form does not have company name in it, it will not create a company entity. See, 'How can we reproduce this issue?' steps to know more.

### How can we reproduce this issue?

Step 1: Create a form with contact name, contact email and company email fields
Step 2: Submit the form
Step 3: Go to company list page, observe company being not created

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
@kuzmany I believe you made the original PR which is referenced in this bug report. Thanks for raising it @ts-navghane :)

**Comment by kuzmany** [comment]
@ts-navghane but you are able to add company email to unique field. Before we use different logic on few places - somewhere looking just for company name, somewhere for name/email/city/country etc.
