### ISSUE TITLE
More than 1 parameter not recoginized in mautic webhook trigger URL

### ISSUE THREAD

**Issue by piyush-cg** [mautic/mautic#10942]
### Mautic Version

4.2.x series

### PHP version

7.3

### What browsers are you seeing the problem on?

Chrome

### What happened?

I tried to trigger a webhook using a custom API with two parameters, but only the first parameter is being read by the service and not the other parameter passed after the ampersand.

For e.g.  if this is defined as the URL https://apiprod.credgenics.com/communication/thirdparty?company_id=ad8b5a88-637f-49a3-b8af-f341dd9db5fd&loan_id=102095

The field loan_id=102095 is not being read

### How can we reproduce this issue?

Step 1: Just trigger any webhook with multiple parameter separated by an ampersand and see if it is getting passed properly

### Relevant log output

```shell
Last execution error: Client error: `POST https://apiprod.credgenics.com/communication/thirdparty?company_id=ad8b5a88-637f-49a3-b8af-f341dd9db5fd&loan_id=102095` resulted in a `400 Bad Request` response: {"message": "failed", "output": "Failed to fetch applicant details"}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for taking the time to report the bug @piyush-cg and for the log error line.
