### ISSUE TITLE
[Feature request] Add Lead to Campaign not from list/form

### ISSUE THREAD

**Issue by trops** [mautic/mautic#1094]
I would like the ability to add a lead to a Campaign as an individual using the API. For example, if a lead does some action, I would like to move that lead to a campaign, and not necessarily need to be in a list.

Is this now possible? I couldn't find how to create a campaign from anything other than a list or a form.

Thanks!

**Comment by escopecz** [comment]
Are you talking about this?:
1. Add/remove a lead to a campaign manually from the lead detail:
![mautic-add-lead-to-a-campaign](https://cloud.githubusercontent.com/assets/1235442/10882204/1c1cf7c6-8169-11e5-9f85-b0c89ff7f22a.png)
2. Add/remove a lead to a campaign automatically from a campaign builder:
![mautic-add-lead-to-a-campaign-builder](https://cloud.githubusercontent.com/assets/1235442/10882252/73559fac-8169-11e5-820e-2d308d2ff585.png)

**Comment by trops** [comment]
Thanks for the reply John,

I was looking to add a user to a campaign without adding them to a list first using the API. 

For example, a user might visit a page and I would like them to immediately be added to a particular campaign but I dont want to have to keep making lists. 

Maybe I just have to and thats the way it is!

Not top priority because I can work around it.



Thanks,
John

**Comment by escopecz** [comment]
Ahh, missed the API part. I think that's not possible via API right now. I'll mark this as a feature request.

**Comment by alanhartless** [comment]
Maybe we're just missing it in the PHP api library?

We have the endpoints in Mautic `/campaigns/{id}/lead/add/{leadId}`
https://github.com/mautic/mautic/blob/17dd7cad9866db2c612645873b9fc6c4319e0597/app/bundles/CampaignBundle/Config/config.php#L44-L44

https://github.com/mautic/mautic/blob/ac05c1c2f7f4e895f94dcf70e9c48f1435e8e740/app/bundles/CampaignBundle/Controller/Api/CampaignApiController.php#L44-L44

**Comment by alanhartless** [comment]
This is in our PHP API library now. https://github.com/mautic/api-library/blob/master/lib/Api/Campaigns.php#L70
