### ISSUE TITLE
Conditional on contact field value preferred locale

### ISSUE THREAD

**Issue by godiez** [mautic/mautic#10940]
### Mautic Version

4.2.x series

### PHP version

7.4.27

### What happened?

Hello,

As @RCheesley said [here](https://github.com/mautic/mautic/issues/10906), this issue persists in 4.2.0

![image](https://user-images.githubusercontent.com/6525902/157037031-0a65bbe1-2131-4e5a-b130-5eee027f18e8.png)

There's a bug in campaign builder, in condition option (Form field value option), always fails when 'preferred locale' is selected.

When you set up a condition on 'Preferred Locale' field, for example,

![image](https://user-images.githubusercontent.com/6525902/157036774-36f01801-8bdc-4d25-995e-50adfea66c1a.png)

The value 'en' is store with 'English' text. Here it is:

{....s:5:"field";s:16:"preferred_locale";s:8:"operator";s:1:"=";s:5:"value";s:7:"English";}, it might be 'en'.

Thanks in advance!

### How can we reproduce this issue?

Step 1: 

- Create a campaign with the 'preferred locale' (no matter which operator do you use) condition
- Run the campaign
- Always fails

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the additional info, I just tweaked the text slightly as some was missing from your original issue!
