### ISSUE TITLE
Dashboard query uses wrong index with certain time intervals when indexed virtual columns are available

### ISSUE THREAD

**Issue by pety-dc** [mautic/mautic#10956]
### Mautic Version

3.3.x series (not supported)

### PHP version

7.4

### What happened?

The data of Dashboard timeline charts are serviced by `Mautic\CoreBundle\Helper\Chart\ChartQuery`

`ChartQuery` has built-in ways to handle the selected time interval to determine how big time unit the query should group data.  (hours, days, weeks, months)

`ChartQuery` is also capable of making use of generated columns. Using generated columns is useful because MySQL can use index on them while using a MySQL function usually prevents using indexes on the column.

For certain tables there are generated columns to help queries that group by `day` 
For example `email_stats` table has `generated_sent_date` column which.
When the selected time interval indicates that data should be grouped by days, `ChartQuery` makes use of the generated column, instead of using `DATE_FORMAT()` function. The behaviour is decided in the `ChartQuery::getDateConstruct` method.

However this leads to incoherent column usage in the query: the select, groupby and orderby claues use the generated column, but `applyDateFilters` adds conditions to the where clause referencing to the original date column. 

Example query:
```
SELECT t.generated_sent_date AS date, COUNT(*) AS count 
FROM email_stats t 
WHERE t.date_sent BETWEEN '2021-12-26 00:00:00' AND '2022-01-26 23:59:59' 
GROUP BY t.generated_sent_date 
ORDER BY t.generated_sent_date ASC
LIMIT 32
```

MySQL optimizer unfortunately sees the index on the generated column better fit the needs of the query instead of the one on the original date column (date_sent)
![image](https://user-images.githubusercontent.com/25766885/157887839-f64abdc9-78af-45b3-8a52-6ecf96330a82.png)

There is a hint in the code that Mautic developer community is somewhat aware of this problem and made the orderby optional:
```
if ($useSqlOrder) {
       // Some queries needs to avoid this because of query performance
       $query->orderBy($dateConstruct, 'ASC');
}
```
Unfortunately the dashboard query uses ordering.

I can't recall where, but somewhere I read that adding zero to the orderby column can make MySQL change which index it uses. (probably for the same reason as it can't use index with functions together)

But if I add another item to the orderby clause (to the count column which is always present) it also fixes MySQL's index usage. 

```
EXPLAIN SELECT t.generated_sent_date AS date, COUNT(*) AS count 
FROM email_stats t 
WHERE t.date_sent BETWEEN '2021-12-26 00:00:00' AND '2022-01-26 23:59:59' 
GROUP BY t.generated_sent_date 
ORDER BY t.generated_sent_date ASC, count ASC
LIMIT 32;
```

![image](https://user-images.githubusercontent.com/25766885/157890753-7048baab-8b57-4ea7-897f-649e79c0f618.png)

code:
```
if ($useSqlOrder) {
            // Some queries needs to avoid this because of query performance
            $query->orderBy($dateConstruct, 'ASC');

            // dateConstuct sometimes refer to an indexed virtual column, which is used in the groupby clause, but not in the where clause.
            // This results in poor query performance if mysql chooses to use the index of the virtual column instead of the column's in the where clause
            // Adding another orderBy clause is a trick helps mysql to pick the proper index
            $query->addOrderBy('count', 'ASC');
        }
```

Now I know that this is hard to reproduce, because it requires a large database. Therefore I won't create a PR. But I wanted the community to know about this trick.

### How can we reproduce this issue?

Step 1: Have generated columns available in your database.
Step 2: Send many emails, fill the email_stats table
Step 3: Use dashboard that shows charts from email_stats table
Step 4: experiance slowness

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @pety-dc - as we don't support Mautic 3 any more, could you clarify if this is the case with the 4.x series? If so we do have large databases that we can test against, so you're welcome to make a PR to address it.

**Comment by pety-dc** [comment]
Hey @RCheesley 
I checked that the code is seemingly the same in Mautic 4, but I didn't have the chance to check whether it behaves the same.
Within a few weeks I'll try to test is.

**Comment by alexleonov-tactiq** [comment]
The problem is still present in 4.4.0, but it's not resolved with the patch above. 

Here is an example of how it looks in Performance Insights:
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/80251529/177227617-2469dfbf-af97-4ec1-8192-33873ad81fb7.png">

And this is the spike in the Mautic's own CPU usage which leads to gateway timeouts:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/80251529/177227667-35793956-3d3a-420b-b023-f813bfeace8d.png">

Then, after the dashboard has loaded and the data is cached for a little while, it performs fine - until the next refresh.

**Comment by alexleonov-tactiq** [comment]
What may or may not be important, there are hundreds of thousands send emails that fall into the one-month period that is the default for the Sent Emails report.

**Comment by alexleonov-tactiq** [comment]
Also, there were 4 data filters in the report: one to only have published emails, and 3 to filter out sent emails with email addresses matching certain patterns.

**Comment by alexleonov-tactiq** [comment]
For now I am surviving by removing the data filters, applying the change proposed above, and creating a couple of indexes like this, and the dashboard loads within a few seconds: 

```
create index idx_report_sent_1 on email_stats (date_sent, generated_sent_date, email_id);
create index idx_report_sent_2 on email_stats (date_sent, date_read, email_id);
```

**Comment by pety-dc** [comment]
@alexleonov-tactiq 

Your query has way more coniditions in the where clause than mine - probably due to applied filters. 
My proposed solution is only supposed to solve only MySQL using the index on the generated date column instead of the original which it does the filtering by. 

Afaik Mysql unfortunately can use only one index for a query.  It may try some index merging/intersecting magic stuff, but sometimes that just makes things worse. This insufficiency can be mitigated by adding composite indexes.
