### ISSUE TITLE
Public preview link should also work for unpublished mails

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#10955]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I think if I'm able to enable and disable the public preview link, it should also work when the mail is not yet published? This is useful for not yet approved mails to be shared with the customer for approval.

Logic should be as follows:
* mail unpublished, preview link disabled by default - can be enabled
* mail published, preview link enabled by default - can be disabled,

Thanks!

### How can we reproduce this issue?

* create a mail
* leave it unpublished, preview link switch is on public by default
* try to open the preview link without being logged into the system

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
@dsp76 thanks for raising this - we have a PR which has been merged relating to this, I believe: https://github.com/mautic/mautic/pull/10845

This makes it turned off by default for emails.

Are you suggesting the bug is that when the email is not published, you can't toggle the switch to enable the preview?

**Comment by dsp76** [comment]
Hi @RCheesley ... no the button can be toggled, but it has no effect. Even when "public preview" is switched on (while mail itself is still unpublished) it doesn't show without logging on to Mautic first. The "public preview" switch should also work for an unpublished mail.

**Comment by RCheesley** [comment]
@dsp76 looks like we just had a PR to fix this in #10971 - can you give it a test?

**Comment by jos0405** [comment]
This is in production as of 4.2.1, I tested and it seems to be working. I take the liberty to close this bug report. If you find any issues, please feel free to reopen.
