### ISSUE TITLE
Mj-group doesn't work in email editor

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#10952]
### Mautic Version

4.2.x series

### PHP version

7.4

### What happened?

If you need prevent columns from stacking on mobile in MJML editor you must use "mj-group" (source https://documentation.mjml.io/#mjml-group ). But it doesn't work on Mautic. After added this to code my sections have got strange width:
![image](https://user-images.githubusercontent.com/56032973/157694953-bf42093f-6893-4f83-b6b8-96928cb7c18b.png)
![image](https://user-images.githubusercontent.com/56032973/157694679-46a245f7-e7a2-4e02-9971-78386a6a8e5f.png)
 

### How can we reproduce this issue?

Step 1: Create email in GrapeJS with MJML
Step 2: Add 2 columns section
Step 3: In code add "<mj-group>" before and after columns
Step 4: Check your e-mail in preview mode.

### Relevant log output

```shell
no logs
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for raising the bug @biggala2310 - @adiux something we have introduced recently maybe? I know that @jos0405 was demonstrating this feature in the last helpdesk meetup and it was working great then, so seems like a regression?

**Comment by adiux** [comment]
@biggala2310 does the code work on MJML.io? I don't think `mj-column` supports/needs `!important`: https://documentation.mjml.io/#mj-column

**Comment by ghost** [comment]
@adiux Yes, I did it. Belive me, I made email template 2 days, checked a lot of codes in github and stackoverflow before I was ready to made my dream template. Why?

**1. full width for section:**:  In options on the sidebar I haven't option: "full-width="full-width" which extend my section's background color to full width (I still don't see full width color in editor, but on preview and in inbox it looks good). I found this option on github and add to code view.
**2. mj-group**: In options on the sidebar I haven't option: no wrap, which add <mj-group> after <mj-section> and </mj-group> before close.  I found this option on github and add to code view.
**3. 100% width for image on mobile** - If I good remember you helped me with this and gave me a code "fluid-on-mobile="true" " Of course, I thank you, but the solution in which you have to enter to the code for such a function or ask on the forum is not the best.
**4. Code window doesn't open after close builder** - when I open MJML code mode, close builder (for example tosave or preview)  and I try come back to builder's MJML code mode, the window doesn't open. I need refresh page to fix this function.

Also I'm having trouble including <mj-style> and with including CSS for mobile.

Topic to close.
