### ISSUE TITLE
Wrong image width in MJML editor

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#10950]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What happened?

When I set up image width as 100%, MJML editor adds also "width=100", without percentage.
![image](https://user-images.githubusercontent.com/56032973/157658316-ec15fd3f-6140-4ecc-81ff-6f40eee4fa5a.png)
![image](https://user-images.githubusercontent.com/56032973/157658367-2aca9dae-50ff-47ad-adb9-ba2480cdd7c0.png)

### How can we reproduce this issue?

Step 1: Create email in MJML editor
Step 2. Set up image width in percentage
Step 3. Image will be displayed in the wrong resolution

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by ghost** [comment]
Important info: this idiotic, wrongly addition of width (from image) to the cell causes this error.

**Comment by RCheesley** [comment]
@biggala2310 please take a moment to re-acquaint yourself with our Code of Conduct: https://contribute.mautic.org/policies/code-of-conduct#5-unacceptable-behavior

I am sure if you were the person who wrote that line of code, you would not feel particularly great reading the coment you just left.  Please be considerate with your comments in the future, and remember that we are all trying to do the best we can here, nobody is perfect, and mistakes can and are made at times.

If you would like to help us fix this issue, I'd be happy to walk through with you how to contribute and also how to help testing so we pick up things like this in the future.

**Comment by ghost** [comment]
Sorry @RCheesley! I checked it and see that this is normal in MJML (source: https://github.com/mjmlio/mjml/issues/1044). In my opinion, this disqualifies MJML, because it shows that it is an outdated framework. I'm rooting for @adiux 's work!

I'm not sure that this topic should be closed. Maybe we should create one with all the shortcomings MJML's editor.

**Comment by adiux** [comment]
I think the workaround is to use the MJML attribute fluid-on-mobile directly in the code. 

`<mj-image fluid-on-mobile="true">`

As mentioned here:
https://github.com/mjmlio/mjml/issues/1323

Maybe you want to add this as a feature request over at grapesjs mjml plugin

**Comment by RCheesley** [comment]
OK thanks for the input @adiux - as this seems to be an issue with MJML rather than a bug with Mautic, I'm going to go ahead and close this issue. @biggala2310 please see above for a workaround and suggestion of where to make your feature request upstream to MJML (slightly less aggressively might be appreciated by the MJML maintainers 😉 ).
