### ISSUE TITLE
Seriously – forbidden?

### ISSUE THREAD

**Issue by blaasvaer** [mautic/mautic#10959]
### Mautic Version

4.2.x series

### PHP version

7.4.21

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When unzipping (after adding the .zip extension to the download myself!?) the download, and going to http://localhost/mautic I get:
```
403 Forbidden 
```
And then after trying to run `composer install`as I thought I would have to ... I get:
`Composer could not find a composer.json file in /Applications/MAMP/htdocs/mautic`

All server requirements are met, database created and read/write OK.

Hmm, I thought this project would have come a bit further since I last checked some years ago.

What am I missing this time around?

### How can we reproduce this issue?

Step 0: Check requirements
Step 1: Download zip-file
Step2: Add .zip extension to the file, as I guess someone forgot to (not mentioned in the docs).
Step 3: unzip and move content of folder to www root/mautic
Step 4: create DB
Step 5: entering site at http://localhost/mautic

Getting 403 Forbidden ...

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by blaasvaer** [comment]
And yes, I did run composer without the ext-imap flag and got it installed through cloning it from git (why do the zip and the clone differ so wildly?). But I still get 403 Forbidden ... I guess I'll just wait another three or four years to see if this project gets less messy to get going at some point.

**Comment by privateidaho** [comment]
Hi, there seems to be a specific issue with 4.2 when installed on a subdirectory.

You need to comment out three lines in .htaccess.

See:

https://forum.mautic.org/t/403-error-after-mautic-3-3-5-update/22859/5

**Comment by blaasvaer** [comment]
Well, didn’t make a difference … anything else I could ‘experiment’ with?

Mvh / Best Regards

Sam Blåsvær
Senior Fullstack Architect
20 70 33 60
***@***.***

Ådiget 16
2610 Rødovre

www.blaasvaer.dk

**Comment by privateidaho** [comment]
That worked for me.  Can't help any further.       

The Mautic team and community is pretty responsive now so I'd expect some comments within 24 hours.

**Comment by blaasvaer** [comment]
Thanks.

Mvh / Best Regards

Sam Blåsvær
Senior Fullstack Architect
20 70 33 60
***@***.***

Ådiget 16
2610 Rødovre

www.blaasvaer.dk

**Comment by RCheesley** [comment]
Hi folks, this is most likely going to be as a result of your server configuration rather than a bug with Mautic. If you don't manage to resolve it with the suggestion above regarding the htaccess, please post your issue over at https://forum.mautic.org/c/support as the forums are for getting help if you encounter problems :)

**Comment by fzngagan** [comment]
https://forum.mautic.org/t/403-forbidden-error-on-wamp/25425/6?u=fzngagan

**Comment by fzngagan** [comment]
I was hit by the same issue and spent hours trying to get things working. Simple fix(**Only advisable for local dev install**): Comment out the `<IfModule authz_core_module>` and `<IfModule !authz_core_module>` sections in the `.htaccess` file.

**Comment by SKJoy** [comment]
Disabling the **ModSecurity** fixed the installer issue on **CentOS WebPanel**

**Version**: Mautic 4.4.9 stable release
**OS**: AlmaLinux 8
**Path**: Subdomain root; https://mautic.domain.com/

**Learn more**: https://forum.mautic.org/t/403-error-after-mautic-3-3-5-update/22859/10
