### ISSUE TITLE
Upgrading to Mautic 4.2 breaks theme associations, destroys custom content.

### ISSUE THREAD

**Issue by J-Wick4** [mautic/mautic#10958]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Chrome

### What happened?

This is a pretty bad one, I almost lost a lot of work, luckily I had backups of the HTML.

1. Upgraded to Mautic 4.2 from the previous version.
2. Went to modify a landing page, Builder option not available, no theme was "Selected."
3. When re-selecting the theme, all custom content is erased and reverted back to the default theme state.
4. Also noticed the themes that I enabled, were disabled and had to go back and add the appropriate code to re-enable them.

What should have happened, was the theme should have been retained and recognized in association with that landing page.

Note: This happened on other sites as well.

### How can we reproduce this issue?

Step 1: On the previous version of Mautic prior to 4.2 create a landing page with the Aurora Theme.
Step 2: Upgrade Mautic to 4.2
Step 3: Go and make additional changes to the landing page.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there,

How are you managing Mautic updates? Did you switch to managing with Composer with the 4.2 update?

Also are you making changes to the core templates (e.g. by editing the files themselves) or do you mean that the content within the emails you have sent in the past is being lost when you are subsequently editing them, because there isn't a theme associated when you go back to edit them?

**Comment by J-Wick4** [comment]
> Hi there,
> 
> How are you managing Mautic updates? Did you switch to managing with Composer with the 4.2 update?
> 
> Also are you making changes to the core templates (e.g. by editing the files themselves) or do you mean that the content within the emails you have sent in the past is being lost when you are subsequently editing them, because there isn't a theme associated when you go back to edit them?

I'm using Composer 2.2.7 to install and manage updates, never switched methods.
I only edited the template config file so it would show up in Mautic, the rest of the template customization was through the builder.

What I gather is there is a dissociation of the relationship between the landing page and template that happens during the upgrade process, which is why no theme is selected and requires reselection which erases and starts over again.

**This is the upgrade process that I use:**

**Step 1**
Check for unfinished migrations
`./bin/console doctrine:migration:migrate`

Now we’re gonna make sure there aren’t any differences between your database schema and how it is supposed to be:

`./bin/console doctrine:schema:update --force`

Clear the Mautic cache:

`./bin/console cache:clear`

Now go browse your Mautic UI to check if everything is running properly, also check the Mautic logs apache logs and PHP logs to see if there’s any new error.

**Step 2**
Find the latest update.

`./bin/console mautic:update:find`

Apply the update.

`./bin/console mautic:update:apply`

Commit the update.

`./bin/console mautic:update:apply --finish`

**Step 3**
Repeat Step 1 commands, check logs for errors.

Finished.

**Comment by escopecz** [comment]
Never use `./bin/console doctrine:schema:update --force` unless you preview the sql queries first and confirm they do not cause any harm.


see https://github.com/mautic/mautic/issues/11204#issuecomment-1161441244

I did not find any migration with "template" being modified. Does the template still exist in your filesystem? I cannot figure out how would 1 column value disappear.
