### ISSUE TITLE
Where is the SendGrid API webhook callback endpoint? (Getting 404)

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#10963]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Where has my SendGrid API Callback Event Webhook gone?
There used to be a webhook...
https://[MY MAUTIC DOMAIN]/mailer/sendgrid_api/callback
Now I'm getting a 404 error with the blue MAUTIC character.
Could someone PLEASE help?
Did it disappear along the line of updates?

### How can we reproduce this issue?

Step 1: 
Check if YOUR MAUTIC SendGrid Webhook works:
https://[YOUR MAUTIC DOMAIN HERE]/mailer/sendgrid_api/callback

Report back.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @omert37,

I found an issue in the forums related to this, which is the appropriate place to get help with problems rather than bugs. I'd suggest you make a reply there: https://forum.mautic.org/t/getting-the-error-404-when-doing-the-test-callback-to-url-in-the-email-monitor/18033
