### ISSUE TITLE
Segments operator does'nt work anymore since update 4.2

### ISSUE THREAD

**Issue by hlorridi-pm** [mautic/mautic#10962]
### Mautic Version

4.2.x series

### PHP version

7.4.26

### What browsers are you seeing the problem on?

Chrome

### What happened?

i've create a segment under v4.1 with email read date >= -4 weeks
now i've update mautic to the last version (4.2) (console mautic:update:find,apply,finish stuff)
now on my segment , the selectbox operator is empty and the value disappeared
error on the js console when i had a new filter

indeed, in the js function , filterId, and operator were never defined
on the following call Mautic.setProcessorForFilterValue(filterId, operator);

```
Mautic.convertLeadFilterInput = function(el) {
    var operatorSelect = mQuery(el);
    
    // Extract the filter number
    var regExp = /_filters_(\d+)_operator/;
    var matches = regExp.exec(operatorSelect.attr('id'));
    var filterNum = matches[1];
    var fieldAlias = mQuery('#leadlist_filters_'+filterNum+'_field');
    var fieldObject = mQuery('#leadlist_filters_'+filterNum+'_object');
    var filterValue = mQuery('#leadlist_filters_'+filterNum+'_properties_filter').val();

    Mautic.loadFilterForm(filterNum, fieldObject.val(), fieldAlias.val(), operatorSelect.val(), function(propertiesFields) {
        var selector = '#leadlist_filters_'+filterNum;
        mQuery(selector+'_properties').html(propertiesFields);

        Mautic.triggerOnPropertiesFormLoadedEvent(selector, filterValue);
    });

    Mautic.setProcessorForFilterValue(filterId, operator);
};
```

### How can we reproduce this issue?

First case : 
Step 1: create a segmentt under a previous version of mautic (4.0, 4.1)
Stetp 2 : use a filter like "email date read greater of equals -4 weeks"
Step 3 : save the segment
Step 4 : update mautic to the last version (4.2)
Step 5 : edit your segment and you'll see that the operator and the value disappeared

Second case : 
Step 1 : under mautic 4.2
step 2: create a segment
step 3: add a new filter "email read date"
step 4 : go to the js console log and you'll see operator not defined error

### Relevant log output

```shell
app.js?v07e9c379:657 Uncaught ReferenceError: operator is not defined
    at Object.Mautic.convertLeadFilterInput (app.js?v07e9c379:657:1206)
    at Object.Mautic.addLeadListFilter (app.js?v07e9c379:664:751)
    at HTMLSelectElement.<anonymous> (app.js?v07e9c379:648:132)
    at HTMLSelectElement.dispatch (libraries.js?v07e9c379:465:447)
    at HTMLSelectElement.elemData.handle (libraries.js?v07e9c379:451:166)
    at Object.trigger (libraries.js?v07e9c379:682:227)
    at HTMLSelectElement.<anonymous> (libraries.js?v07e9c379:688:258)
    at Function.each (libraries.js?v07e9c379:153:170)
    at jQuery.fn.init.each (libraries.js?v07e9c379:144:192)
    at jQuery.fn.init.trigger (libraries.js?v07e9c379:688:229)
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Please try to regenerate the assets using:

`bin/console m:a:g`

**Comment by hlorridi-pm** [comment]
asset already regen

look the function, you pass args that does'nt exist :-/ tthat can't work ```Mautic.setProcessorForFilterValue(filterId, operator);``` filterId and operator are'nt defined

**Comment by RCheesley** [comment]
Ah OK, sorry it wasn't clear that you'd already regenerated the assets as we've had quite a few people getting issues with segments not having filters available which were resolved by that.

**Comment by escopecz** [comment]
I'm looking into this. It seems this was caused by a merge conflict with my PR with segment refactoring and Zdeno's commit https://github.com/mautic/mautic/commit/5334db336986f46a8fa7d39f487624cfb56461e1

I can see the JS error but it still allows me to build the segment filter. I can see that my team already fixed that so I'll cherry-pick the commit shortly.

**Comment by escopecz** [comment]
See https://github.com/mautic/mautic/pull/10985

**Comment by RCheesley** [comment]
@hlorridi-pm please can you test #10985 and see if this resolves the problem for you? If so please leave an approving review under files changed > review changes on the PR. Thanks!
