### ISSUE TITLE
Columns under Contact List Settings does not get saved (Configuration->Contact Settings)

### ISSUE THREAD

**Issue by leoncool** [mautic/mautic#10964]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

After changing the Columns values on the Contact List Settings page (Configuration->Contact Settings) and clicking "Save" or "Save & Close", the options do not get actually saved.  If navigate back to this page, the previous default values are shown again.  No effect at all. 

Is this a bug? 

### How can we reproduce this issue?

Step 1: Navigate to Configuration->Contact Settings
Step 2: Change the order and add new columns to the Contact List Settings. 
Step 3: Save or Save & Close
Step 4: Navigate back to Configuration->Contact Settings again.  Even go to "Contacts" page, same results of the columns are shown. 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by PierreAmmeloot** [comment]
Same problem here.
Same configuration.

**Comment by dobarbarini** [comment]
same problem here

**Comment by dobarbarini** [comment]
Any response from the community? @PierreAmmeloot @leoncool

**Comment by PierreAmmeloot** [comment]
@dobarbarini I see I have the same problem as @leoncool; unfortunately I don't have a solution to propose for the moment.

**Comment by roicahana** [comment]
Same problem here, this happened after I upgraded to the newest version 4.2.1

**Comment by kungfuzi** [comment]
Same problem here. If this helps anyone, as a work around you can manually add the fields in /app/config/local.php in the contact_columns array.

**Comment by ghost** [comment]
+1 after migration to 4.2x

**Comment by kimtiago** [comment]
Me too... 4.2.1

**Comment by eve292** [comment]
Me too

**Comment by mgaido** [comment]
Me too. And "Merge by unique fields with operator" don't work too

**Comment by monkey-theatre** [comment]
The same issue here.

**Comment by vickyberenguer** [comment]
same problem here

**Comment by apradillap** [comment]
@PierreAmmeloot @leoncool Do you have an estimate of the resolution? Thanks!!

**Comment by PierreAmmeloot** [comment]
@apradillap not at this time.

**Comment by dsp76** [comment]
Still happens in version 4.3.1

**Comment by npracht** [comment]
Please test https://github.com/mautic/mautic/pull/11187

**Comment by mabumusa1** [comment]
Keep it open

**Comment by mabumusa1** [comment]
Keep it open
