### ISSUE TITLE
Import completed notification link wrong!

### ISSUE THREAD

**Issue by dichvuhuuich** [mautic/mautic#10960]
### Mautic Version

4.2.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

Import Contact in Browser first, after that click Finish in Background, when finished Mautic shows notification Import completed but link to this result wrong example: https://mauticsitewebsite/s/lead/import/view/4. Correct link is: https://mauticwebsite/s/contacts/import/view/4

### How can we reproduce this issue?

Step 1: Make a csv contact file to import
Step 2: Import this file in browser
Step 3: Click Finish in Background
Step 4: Run command php /path/to/mautic/bin/console mautic:import (or put in cronjob)
Step 5: Check After finish Import completed notification link wrong

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for raising the bug @dichvuhuuich - nice catch! Would you be able to look into making a fix for it at all?

**Comment by npracht** [comment]
It must be somewhere around here:
https://github.com/mautic/mautic/blame/4.x/app/bundles/LeadBundle/Views/Import/progress.html.php#L92

But i also see this:
https://github.com/mautic/mautic/blob/4.x/UPGRADE-3.0.md?plain=1#L351
