### ISSUE TITLE
Segment filter "Downloaded a specific asset" not included all assets

### ISSUE THREAD

**Issue by PierreAmmeloot** [mautic/mautic#10965]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Chrome

### What happened?

I want use a segment filter "Downloaded a specific asset" including one particular asset.
The list of assets is not the same as the documents in the assets section.

This is new since version 4.2.0; I guess it has something to do with the changes from @kuzmany 

### How can we reproduce this issue?

Step 1: Update Mautic on v4.2.0
Step 2: Upload an asset on "Asset Center"
Step 3: Create a segment with filter "Downloaded a specific asset"
Step 4: Find that the document uploaded in the asset section does not appear in the list

### Relevant log output

```shell
No log for this bug.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Can you please share screenshots ? Are you sure your assets are published ?
What let you think @kuzmany introduced this regression ? Any code to relate to this assumption ?

Thanks.

**Comment by PierreAmmeloot** [comment]
@npracht Yes, assets are published. ;-)

**Comment by npracht** [comment]
Still:

1. Can you please share screenshots ?
2. What let you think @kuzmany introduced this regression ?
3. Any code to relate to this assumption ?

**Comment by kuzmany** [comment]
@npracht 4.2 include large segment refactoring. I found the lines cause this limit issue. I will post PR later

**Comment by kuzmany** [comment]
@npracht 4.2 include large segment refactoring. I found the lines cause this limit issue

https://github.com/mautic/mautic/blob/a390b7b2c692d324d0a14838f63783b4a259bcfd/app/bundles/LeadBundle/EventListener/TypeOperatorSubscriber.php#L360

The same  for categories

https://github.com/mautic/mautic/blob/a390b7b2c692d324d0a14838f63783b4a259bcfd/app/bundles/LeadBundle/EventListener/TypeOperatorSubscriber.php#L352

There is limit 10 by default

@escopecz do you have already fix on Acquia branch or we need create new one?

**Comment by escopecz** [comment]
@kuzmany I'm not certain that the limit is to blame. The lookup field functions as a search field, right? When a user starts typing the asset name then the closest 10 results will appear as options. 10 options seem like a good amount to me.

**Comment by kuzmany** [comment]
@escopecz but do not see this ajax lookup call on these fields in segment filters, do you?

**Comment by escopecz** [comment]
That will be the problem here. Maybe it is not attached to the HTML element

**Comment by PierreAmmeloot** [comment]
Hello,

On my case I have an assets name start by "Webinaire Marketing Automation"

<img width="345" alt="Capture d’écran 2022-03-16 à 15 05 42" src="https://user-images.githubusercontent.com/4603318/158608120-671e1f8e-8794-4134-aeb0-8b24971b5b7f.png">

On filter if y search "webinaire" I have the result : "Not match found webinaire" : 

<img width="1254" alt="Capture d’écran 2022-03-16 à 15 05 52" src="https://user-images.githubusercontent.com/4603318/158608141-0ab70aaf-0922-4e60-a340-39ea8ef79b1d.png">

**Comment by PierreAmmeloot** [comment]
Hello @kuzmany @escopecz,

With Mautic 4.2.1 it's work on my side. Thanks you ! 👍
Can you check on your side before closed this issue ?

Pierre

**Comment by escopecz** [comment]
Cool, thanks for retesting!
