### ISSUE TITLE
Sendgrid callback isn't working. Where is it? (Getting 404)

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#10978]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

As I stated in Issue #10963 (which was closed for some reason), there used to be a callback webhook that processed incoming BLOCKED and BOUNCE reports from SendGrid at the following URL:
https://[MY MAUTIC DOMAIN]/mailer/sendgrid_api/callback 
After one of the updates, I don't know which, that webhook seems to have disappeared and is no longer existent as I am getting 404 errors. Could someone please tell me what happened to it (perhaps a URL change?) and or bring it back (urgently) in the next upcoming update?

It poses a BIG problem when the system is no longer processing BOUNCE and BLOCK reports from any one of its ESP providers.

### How can we reproduce this issue?

Step 1: 
See if the webhook exists on your installation:
https://[YOUR MAUTIC DOMAIN]/mailer/sendgrid_api/callback

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @omert37 the other issue was [closed with an explanation](https://github.com/mautic/mautic/issues/10963#issuecomment-1069040425) that configuration issues are to be posted in the forums where we offer community support, GitHub is for posting bugs with Mautic. 

Can you clarify if your instance has been using this and then after an update it stopped working, or did you set up a new instance and configure it, and can't get it set up correctly?

I have asked some other Sendgrid users to take a look and see if it might be a config and/or documentation issue or if it is indeed a bug.

**Comment by jos0405** [comment]
Hi, can you confirm, that you didn't change to SMTP method within Sendgrid? Are you still using the API key to connect to Sendgrid? Thx.

**Comment by mabumusa1** [comment]
I just tested it, it works without issues. try to access this ur from your browser if you get a page that `success` then it works.

**Comment by renatocron** [comment]
@omert37 can you confirm if you are using "Sendgrid API" driver like bellow:
![image](https://user-images.githubusercontent.com/1919076/160647353-b440b9b5-4532-40eb-aba0-fb748851b54f.png)

The endpoint does not work if you use "Sendgrid SMTP"

![image](https://user-images.githubusercontent.com/1919076/160647468-ee4ec53a-c0f2-400f-9d6b-233ac8989a5f.png)

**Comment by omert37** [comment]
You're absolutely correct.
I switched over to SMTP instead of using the API for mailing deliveries.
That's why the CALLBACK endpoint wasn't working.
It only works when I use the API.

**Comment by jos0405** [comment]
Because it's a different endpoint for api and for smtp
Try https://[YOUR MAUTIC DOMAIN]/mailer/sendgrid/callback

**Comment by RCheesley** [comment]
Thanks folks! Going to close this as it indeed does seem to be a configuration error rather than a bug with Mautic! Appreciate the help everybody!
