### ISSUE TITLE
Error 500 after "Campaign -> New" and "Cancel" (Unable to generate a URL for the named route "c" as such route does not exist)

### ISSUE THREAD

**Issue by ekkeguembel** [mautic/mautic#10979]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I start creating a new campaign but hit "cancel" in the process, up comes the beloved "Uh, I think I broke it" HTTP Error 500.

I think this was introduced with 4.1 and still exists in 4.2.0

### How can we reproduce this issue?

Step 1: Go to Campaigns, hit "New"
Step 2: Hit "Cancel"

### Relevant log output

```shell
mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "c" as such route does not exist." at <homedir>/vendor/symfony/routing/Generator/CompiledUrlGenerator.php line 50 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"c\" as such route does not exist. at <homedir>/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"} []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the bug report! Pinging @mautic/campaigns-webhooks-tiger-team for visibility!

**Comment by RCheesley** [comment]
Closing issue as it was fixed with https://github.com/mautic/mautic/pull/11348
