### ISSUE TITLE
Segment list - amount of items in list per page can't be changed

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#10981]
### Mautic Version

4.2.x series

### PHP version

7.4

### What happened?

Amound of list items can't be changed. Will switch back to 30.

### How can we reproduce this issue?

Step 1: go to segment list
Step 2: try to change from default 30 to any other value. Will immediately switch back to 30.

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jonathandhn** [comment]
I can confirm, the bug exist.

The source code of the broken button. 
```
<select autocomplete="false" class="form-control not-chosen pagination-limit" onchange="Mautic.limitTableData('segment',this.value,'list','.page-list', '/s/segments?tmpl=list');">
                                                                    <option value="5">
                            5                        </option>
                                                                    <option value="10">
                            10                        </option>
                                                                    <option value="15">
                            15                        </option>
                                                                    <option value="20">
                            20                        </option>
                                                                    <option value="25">
                            25                        </option>
                                                                    <option selected="selected" value="30">
                            30                        </option>
                                                                    <option value="50">
                            50                        </option>
                                                                    <option value="100">
                            100                        </option>
                                    </select>
```

It links to this JS script : 
/media/js/app.js the script is loaded, no console error to report.
```
Mautic.limitTableData = function(name, limit, tmpl, target, baseUrl) {
    if (typeof baseUrl == 'undefined') {
        baseUrl = window.location.pathname;
    }
    if (baseUrl.indexOf('tmpl') == -1) {
        baseUrl = baseUrl + "?tmpl=" + tmpl
    }
    var route = baseUrl + "&name=" + name + "&limit=" + limit;
    Mautic.loadContent(route, '', 'POST', target);
};
```

**Comment by RCheesley** [comment]
Hey folks!

Please try to regenerate your assets and confirm if it still exists?

https://docs.mautic.org/en/troubleshooting/command-line-tools-cli#mautic-commands

**Comment by dsp76** [comment]
Yep, just tested it and the problem still exists.

**Comment by jonathandhn** [comment]
Have you upgraded first?
________________________________

**Comment by dsp76** [comment]
Seems to work with 4.2.1. and m:a:g now... 
Tested in two different instances.

**Comment by jonathandhn** [comment]
Resolved ! Thanks for the feedback.

De : Ruth Cheesley ***@***.***>
Date : mardi, 29 mars 2022 à 17:45
À : mautic/mautic ***@***.***>
Cc : Jonathan Dahan ***@***.***>, Comment ***@***.***>
Objet : Re: [mautic/mautic] Segment list - amount of items in list per page can't be changed (Issue #10981)

Hey folks!

Please try to regenerate your assets and confirm if it still exists?

https://docs.mautic.org/en/troubleshooting/command-line-tools-cli#mautic-commands
