### ISSUE TITLE
Webhook hasn't worked since the update from v3.3.3 to v4.2.0

### ISSUE THREAD

**Issue by fintechee** [mautic/mautic#10980]
### Mautic Version

4.2.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

It's not a browser problem. It's a server side's issue.

### What happened?

In v3.3.3, after the form submission, the webhook is triggered.

In v4.2.0, after the form submission, the webhook isn't triggered.
I checked the dashboard log, no error message.
I checked the webhook calling records, no records.

### How can we reproduce this issue?

Step 1: Create a form and a webhook.
Step 2: Setup the webhook to be triggered once the event of the form submission occurs.
Step 3: Submit the form and then check the webhook calling history: no records.

### Relevant log output

```shell
No log message, no error message.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the bug report @fintechee - I was not actually able to reproduce this but I did stumble across this bug: https://forum.mautic.org/t/mautic-general-error-1467-failed-to-read-auto-increment-value-from-storage-engine/20861 in my logs which was preventing the form being submitted in the first place.

As soon as I fixed that the form was submitted and the webhook fired as expected.

Please check your logs and see if you have a similar warning.

**Comment by fintechee** [comment]
@RCheesley 
Thank you. Will check it soon.
