### ISSUE TITLE
Template not applied in the email when it is created via API

### ISSUE THREAD

**Issue by zerodois** [mautic/mautic#10997]
### Mautic Version

4.1.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I'm performing an integration with mautic and for that, I'm using its rest api. However, when I create the segment email via the rest api, even though I enter the template parameter correctly, my email is always blank. Is there any way to create an email with an html that I have previously registered on mautic or will I always have to send the complete html? From the interface, I saw that it only fills the html if you click on the builder, otherwise the content is also blank.

### How can we reproduce this issue?

```shell
POST /emails/new
{
      "name": "Email name",
      "subject": "Email subject",
      "emailType": "template",
      "lists": [42],
      "template": "confirmme"
}
```

### Relevant log output

```shell
API RESPONSE:

{
	"email": {
		"isPublished": true,
		"dateAdded": "2022-03-23T20:58:06+00:00",
		"dateModified": null,
		"createdBy": 1,
		"createdByUser": "Felipe Rita",
		"modifiedBy": null,
		"modifiedByUser": null,
		"id": 56,
		"name": "Email X",
		"subject": "SUBJECT TOP",
		"language": "en",
		"category": null,
		"fromAddress": null,
		"fromName": null,
		"replyToAddress": null,
		"bccAddress": null,
		"useOwnerAsMailer": false,
		"utmTags": {
			"utmSource": null,
			"utmMedium": null,
			"utmCampaign": null,
			"utmContent": null
		},
		"customHtml": "",
		"plainText": null,
		"template": "confirmme",
		"emailType": "list",
		"publishUp": null,
		"publishDown": null,
		"readCount": 0,
		"sentCount": 0,
		"revision": 1,
		"assetAttachments": [],
		"variantStartDate": null,
		"variantSentCount": 0,
		"variantReadCount": 0,
		"variantParent": null,
		"variantChildren": [],
		"translationParent": null,
		"translationChildren": [],
		"unsubscribeForm": null,
		"dynamicContent": [],
		"lists": [
			{
				"createdByUser": "Felipe Rita",
				"modifiedByUser": null,
				"id": 56,
				"name": "Segmento da company",
				"publicName": "Segmento da company",
				"alias": "segmento-da-company",
				"description": null,
				"category": null
			}
		],
		"headers": []
	}
}
```
```


### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the bug report @zerodois - does this persist with 4.2.1?

**Comment by zerodois** [comment]
@RCheesley Yes, I retested using version 4.2.1 and the error still persists.

**Comment by jos0405** [comment]
Hello,
Your email is blank, because this is not how API call works. You need to fill in the custom html as well. That will actually create the email content, the template is just a 'background info' for the template rendering. Sorry that it's so confusing :)
Try to add 

 'customHtml' => $htmlTemplate,
  'plainText' => '',

You can see in the response, that custom html wasn't filled.

Please let me know how it worked, if it doesn't fix, plz reopen this. Thank you!
