### ISSUE TITLE
Landing Page Permissions Allow View on everyones login

### ISSUE THREAD

**Issue by ShareBtech** [mautic/mautic#10999]
### Mautic Version

4.2.x series

### PHP version

7.4.16

### What browsers are you seeing the problem on?

Chrome

### What happened?

When assigning Role Permissions on Landing Pages to "View Own" and not "View Others" the new role is still able to view all landing pages.
User cannot do anything with the landing pages but is able to see all lps and urls

### How can we reproduce this issue?

Step 1: Login to Mautic
Step 2: Go to Settings -> User Roles
Step 3: Create a new Role
Step 4: Change the required Permissions on Landing Page
Step 5: Create a test user and associate with new Role
Step 6: Login to mautic with new user (new role)
Step 7: Click on Landing Pages

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the bug report @ShareBtech :)

**Comment by pjrobertson** [comment]
I confirm this is still an issue with Mautic 4.3.1+

Edit: it **looks** like it's something to do with the PageController.php file here: https://github.com/mautic/mautic/blob/4.x/app/bundles/PageBundle/Controller/PageController.php#L73

But unfortunately the code architecture is beyond me so I wouldn't know where to start/how to fix it.

**Comment by pjrobertson** [comment]
This is still and issue in 4.4.5
