### ISSUE TITLE
Unable to connect with shared mailbox in M365

### ISSUE THREAD

**Issue by SzamanSZ** [mautic/mautic#10995]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The IMAP username for shared mailboxes in M365 is in the format _user@domain\sharedmailbox_

It looks like the "\" in the username field somehow causes the problem and Mautic always returns the error "Error communicating with the IMAP server: Can not authenticate to IMAP server: AUTHENTICATE failed."

### How can we reproduce this issue?

In Configuration -> Email settings, I tried to configure Monitored Inbox Settings to monitor shared mailbox in M365. However, the IMAP username for shared mailboxes is in the format user@domain\sharedmailbox

It looks like the "\" in the username field somehow causes the problem and Mautic always returns the error "Error communicating with the IMAP server: Can not authenticate to IMAP server: AUTHENTICATE failed."

Connecting to the standard mailboxes works normally, and the same shared mailbox settings work normally in other software that I've tested.

Here are the M365 settings to connect with shared mailboxes via IMAP so you could try to reproduce the issue:

    Server Type: IMAP - SSL Encrypted
    Port: 993
    Email Address: shared@yourdomain.tld
    IMAP Server: outlook.office365.com
    User Name: user@yourdomain.tld\shared-mailbox-alias (Syntax: user\shared-mailbox)
    Password: user's password

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jonathandhn** [comment]
HI, I'm currently using mautic 4 with an office365 shared mailbox, are you certain you need to type user@yourdomain.tld\shared-mailbox-alias because on mine I'm using shared-mailbox-alias@domain.tld with the shared mailbox password, and I'm listening at "INBOX". Office365 IMAP seams to be using regular emailadress@domain.tld scheme for login, not Ad style.

**Comment by SzamanSZ** [comment]
That's how it is working in Thunderbird and other web apps that I am using (e.g. osTicket). In my setup the shared mailbox doesn't have a password on it's own, just delegation that allows user@mydomain.tld to read and manage the shared mailbox.

While creating the password for the shared mailbox could be the workaround, I believe it should be still possible to login with the user\shared-mailbox style, since I haven't had any problems doing so in other apps so far.
