### ISSUE TITLE
Mautic assigns segments based on un-published custom fields

### ISSUE THREAD

**Issue by christian-krieg** [mautic/mautic#10996]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When defining a filter over a custom contact field to assign segments, the filter behaves non-intuitively when the field is un-published.

# Actual behavior

Instead of inherently deleting the filter condition, the condition is hidden, and any new contact is added to the segment regardless of the custom field's value (I suppose it's something similar to NULL).

# Expected behavior

The expected behavior would be to disable the filter when the underlying filter variable (in this case, a custom field) is un-published, such that the filter does not apply and the contact is not added to the segment.

### How can we reproduce this issue?

1. Create a custom field (e.g. a checkbox group named 'Select')
2. Create a segment and define a filter to add contacts based on the newly created field (e.g., 'Select' contains '1')
3. Un-Publish the custom field created in step 1
4. Add a contact (I only tested this via a campaign form, but I guess this is valid also for manually added contacts)
5. Inspect the contact's segments. The segment from step 2 shows up here **(This is unexpected behavior. Instead, I would expect the segment not to show up)**
6. Inspect the segment's filters. The filter condition based on the custom field of step 2 doesn't show up
7. Now publish the custom field from step 1 again
8. Have a look again on the segment's filters. The filter condition shows up again
9. Deleting the filter condition and un-publishing the custom field restores expected behavior

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the detailed bug report @christian-krieg !
