### ISSUE TITLE
doctrine:schema:update wants to delete custom fields

### ISSUE THREAD

**Issue by uzegonemad** [mautic/mautic#11013]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I'm debugging an issue for a client and in the process called `php bin/console doctrine:schema:update --dump-sql`.

This is returning several statements related to custom fields. There are queries for dropping the custom field indices, followed by queries to drop the custom field columns.

These are active and published custom fields. I'm filing this as a bug report because I would expect custom fields to be considered when running this command. 

---

Separately, like an idiot, I accidentally copy-pasted `php bin/console doctrine:schema:update --dump-sql --force` from the internet which actually began running the commands. I didn't realize until it had dropped about 8-10 custom fields. Thankfully the backup was a few minutes old. Regardless, I thought `--dump-sql` was to be considered a type of "dry run" scenario so if that is indeed the case, maybe mixing it with `--force` should throw a warning?

### How can we reproduce this issue?

Step 1: Add custom fields to mautic
Step 2: Run `php bin/console doctrine:schema:update --dump-sql`
Step 3: (If you're an idiot like me) Run `php bin/console doctrine:schema:update --dump-sql --force`

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
I cannot stress enough to never ever use `bin/console doctrine:schema:update --dump-sql --force`. Mautic use Doctrine in ways the Doctrine developers never expected. Doctrine cannot work with adding columns to a table during runtime which Mautic sadly does for custom fields. Each query that the `bin/console doctrine:schema:update --dump-sql ` command will output must be evaluated before executing.

That being said, I cannot reproduce this. 
1. Does it want to delete all of your custom fields or just some?
2. What database and version do you use?

**Comment by dennisameling** [comment]
@escopecz `bin/console doctrine:schema:update --no-interaction --force` is even mentioned in Mautic's own docs. We should remove it there as well I guess. Running migrations should be all that folks do, right?

https://docs.mautic.org/en/setup/how-to-install-mautic/install-and-manage-mautic-with-composer#updating-mautic-core

**Comment by escopecz** [comment]
@dennisameling ideally, yes. Migrations should do the trick. However, when something goes bad during the upgrade. Like if someone updates from the UI and the migration gets killed in the middle due to timeout then `bin/console doctrine:schema:update --dump-sql` is good for debugging.
