### ISSUE TITLE
Mautic loading slow even after clear cache

### ISSUE THREAD

**Issue by chibimochi** [mautic/mautic#11025]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What happened?

I don't know whether this is a bug or an error. Mautic loading 5 minutes or more even after I clear cache on Mautic directory, /var/cache, using this command rm -rf app/cache/*.  It happened before I updated my Mautic version. Now, 4.2.1 is still the same. here is my VPS data,
4 vCPU Cores
8 GB RAM
50 GB NVMe

Because the loading is too slow, I can't build forms or emails. Nothing appeared. Can't even drag and drop anything.
Any suggestion?

Thank you.

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by PierreAmmeloot** [comment]
Hello @chibimochi,

Are there any errors in the logs?
How did you install Mautic?
How many contacts, segments, campaigns do you have in Mautic?
Does the server host other applications?

Pierre

**Comment by RCheesley** [comment]
Please take this discussion to the forums if you aren't sure if it's a bug. https://forum.mautic.org/c/support :)
