### ISSUE TITLE
Mautic does not support PHP version 8.1.0 / we can't donwgrade PHP version 

### ISSUE THREAD

**Issue by DigitalCoder** [mautic/mautic#11020]
### Mautic Version

4.2.x series

### PHP version

8.1.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Mautic does not support PHP version 8.1.0 
we can't donwgrade PHP version 

Because the hosting servers Gandi.net has removed  PHP versions 7.3 and 7.4.

When do you think Mautic would  release a new version compatible with PHP 8.10 ?

Thx

### How can we reproduce this issue?

Step 0: Check requirements
Step 1: Download zip-file
Step2: Add .zip extension to the file, as I guess someone forgot to (not mentioned in the docs).
Step 3: unzip and move content of folder to www root/mautic
Step 4: create DB
Step 5 : modify .htaccess to resolve 403 forbidden acces when installing in subdirectory
_113 :_ 
<If "%{REQUEST_URI} =~ m#^**/mautic/**(index|index_dev|upgrade/upgrade).php#">

_133 :_
<If "%{REQUEST_URI} =~ m#^**/mautic/**(index|index_dev|upgrade/upgrade).php#">
Step 5: entering site at http://www.domain.com/mautic

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hey there,

Indeed we do not yet support PHP 8, which is specifically called out on our requirements page here: https://www.mautic.org/download/requirements.
 
The WIP PR is here: https://github.com/mautic/mautic/pull/9969 - we are hoping to get some work done on this in our sprint next week at Mautic Developer Days.

Until then I am afraid you will have to find some other way to revert back to 7.4 - for sure the earliest we could think to see this released would be at the end of May, and that is quite ambitious.
