### ISSUE TITLE
BUG - Toggle Anonymous user doesn't work correctly 

### ISSUE THREAD

**Issue by gpassarelli** [mautic/mautic#1102]
## Description 
1. Go to lead lists, click the button to toggle anonymous leads
2. It will filter the leads with the following condition: *is:anonymous*
3. Click the button to toggle the anonymous leads again
4. It will filter the leads with the following condition: *is:anonymous undefined*

The expected behavior is to simple just remove the *is:anonymous* tag.
And if you click the button to toggle again it will filter with the following condition: *undefined*

**Comment by RCheesley** [comment]
I have this bug and I've applied the patch to the 1.core.js file, cleared the cache and my browser cache, but I do not see any difference in behaviour.  Entirely possible that I missed a step somewhere but at the moment it does not seem to fix the problem.
