### ISSUE TITLE
Email subject has "[TEST]" prefix when "Send Example" was clicked before "Send"

### ISSUE THREAD

**Issue by michalfapso** [mautic/mautic#11030]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Firefox, Not relevant

### What happened?

The "[TEST]" prefix should be added to the email subject only when sending an example email with the "Send Example" button. It is implemented in `/app/bundles/EmailBundle/Controller/EmailController.php` in `sendExampleAction()`. I've also added a log message into the `sendExampleAction()` to see when it's called.

One way:
1. Create a new email
2. Click "Send"
3. The email arrives with a **correct** subject **without the "[TEST]" prefix**
4. Click "Send Example"
5. The `sendExampleAction()` should be called, but it isn't.
6. The email arrives with an **incorrect** subject **without the "[TEST]" prefix**. But the "[TEST]" prefix should be there.

And the other:
1. Create a new email
2. Click "Send Example"
3. The `sendExampleAction()` is correctly called.
4. The email arrives with a **correct** subject **with the "[TEST]" prefix**
5. Click "Send"
6. The email arrives with an **incorrect** subject **with the "[TEST]" prefix**. But the "[TEST]" prefix shouldn't be there.

The main issue is that I'd like to send an example email first to my address to see if it is correct. But when I send the email to a whole segment afterwards, it still has the incorrect "[TEST]" prefix.

It seems like there is some kind of a cache so after the email is generated once, it isn't regenerated anymore and the subject is kept the same.

Could you please guide me to the place where the email caching is implemented? I could try to fix it.

I use the docker image `mautic/mautic:v4`, mautic v4.2.1. If you think my `docker-compose.yml` is relevant, I can post it here as well.

### How can we reproduce this issue?

Included in the "What happened?" section.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the detailed report @michalfapso and for being willing to look into fixing this.

@kuzmany can you give any guidance as to where @michalfapso might start to look?

**Comment by kuzmany** [comment]
I think Acquia already use this on production. Probably @escopecz  can share more or share PR directly

**Comment by escopecz** [comment]
This is not an issue for Acuqia as ACS use different modal for sending emails than the community. Quickly looking at the code I see no reason why the `sendExample` action would be cached. Do you have an experience with dev tools in your favorite browser? If you could compare the 2 requests you should see if the `sendExample` action is sent via HTTP requests and it will point you whether the problem is in the frontend or backend.

**Comment by michalfapso** [comment]
Thanks for the hint, @escopecz. My testing email had subject "Email 13" and I've tried it in this order:
1. hitting the "Send" button sends a POST https://myserver.com/s/emails/send/13?mauticUserLastActive=1117&mauticLastNotificationId=
  with request data: `{
	"batch_send[batchlimit]": "100",
	"batch_send[_token]": "BwTi7vJMDLCOnoom5E7OlUebCCEQYNgfK6HFwYmW-eU"
}`
  and it sends the email with the correct subject "Email 13"
2. hitting the "Send Example" button sends a POST https://myserver.com/s/emails/sendExample/13?mauticUserLastActive=23&mauticLastNotificationId=
  with following request data:  `
  {
  	"example_send[emails][list][0]": "myemailaddress@gmail.com",
  	"example_send[_token]": "wUlHMh2uQaFEggNXkSvujittYyF6L1HblY5zqhBoHP0",
  	"example_send[buttons][save]": ""
  }
  `
  and it sends the email with the incorrect subject "Email 13". It should be "[TEST] Email 13".

Also according to my custom log messages in `EmailController.php`, the `sendExampleAction()` was called and the `$subject` variable set on this line:
```
$subject = sprintf('%s %s', static::EXAMPLE_EMAIL_SUBJECT_PREFIX, $entity->getSubject());
$entity->setSubject($subject);
$this->factory->getLogger()->log('info', "subject:$subject");
```
indeed contains the correct subject "[TEST] Email 13".

and even further in that function there is `$model->sendSampleEmailToUser(...)` and when I added another log to `EmailModel.php` inside the function `sendSampleEmailToUser()`:
```
error_log("sendSampleEmailToUser email subject:".($email->getSubject()));
```
it showed the correct subject again "[TEST] Email 13", but still the email arrived with the incorrect subject "Email 13".

Then I added another log to `MailHelper::send()`:
```
$this->message->setSubject($this->subject);
error_log("MailHelper::send() subject:".$this->subject);
error_log("MailHelper::send() subject:".$this->message->getSubject());
```
both showing the correct "[TEST] Email 13".

Nothing changed even when I "Send Example" to another email address not included in any segment.

Do you have any more ideas?

**Comment by escopecz** [comment]
It could be related to a specific email transport. Can you try another transport?

**Comment by automatyzuj** [comment]
+1 AWS as provider here. No logs.

**Comment by djelic** [comment]
We experienced the same issue and after some debugging, it turns out that there is no issue at all, at least not on Mautic side. If you send a test email before you send published email, Gmail will merge those two in same conversation thread. Other users that only receive published email will have subject line without prefix.

You can confirm this by looking at email source (Show original in Gmail) or looking at transport logs.

Hope it helps!
