### ISSUE TITLE
Integration of Gravity Forms with Mautic through API

### ISSUE THREAD

**Issue by RegisScaggiante** [mautic/mautic#1105]
I want to integrate Gravity forms with Mautic. The problem what i found is the excess authentication request by the mautic. I wonder if there is some way to create a lead through the API without authentication request. For each lead created is requesting an authenticating. This way it is impossible to use the API. It doesn't make sense to lead receiving a request for authentication after filling in a form. 
Thanks for help.

**Comment by escopecz** [comment]
Actually, leads shouldn't have to authenticate every request. You, as a system maintainer, should authenticate from your app (or Gravity forms) via Mautic API OAuth once and then all the API requests will use the OAuth token and will be secure.

But, I agree that integration of OAuth takes time when you only need to create a lead from a form. Take a look at https://medium.com/@jan_linhart/the-simplest-way-how-to-submit-a-form-data-to-mautic-1454d3afd005 if it would work for you better.

**Comment by ninjoan** [comment]
any update @RegisScaggiante

**Comment by RegisScaggiante** [comment]
The programmer I hired to make this integration wasn't able to do the job.
Through the API he managed to create the lead in mautic but couldn't enter the lead in any list. Thus, the lead is completely lost there.
For lack of technical knowledge I don't know what else to say, except that I couldn't do what I needed.
The authentication problem initially found, it also failed to resolve.

**Comment by escopecz** [comment]
@RegisScaggiante if you have the plugin code somewhere, maybe it would worth to publish it on GitHub and someone else could finish it. If there was a problem that the Mautic API cannot assign the created lead directly to a list, you can always fill a lead field with a specific value and then create a list with a filter to that value.

**Comment by RegisScaggiante** [comment]
application/x-httpd-php mautic.php
PHP script text

<?php

// Bootup the Composer autoloader
include 'api/vendor/autoload.php';  

use Mautic\Auth\ApiAuth;

$publicKey = '6_2ls1ifgi7dk4wws4sw4g0soo0wgcgsgwcscwwk4wc044s4ocsw'; 
$secretKey = 'tazanlu41msg0g8o88sw8ok8g4k04wo4sksw0kswsc8occw48'; 
$callback  = 'http://estacaofloresta.com.br/teste_mautic/mautic.php'; 

// ApiAuth::initiate will accept an array of OAuth settings
$settings = array(
    'baseUrl'          => 'https://estacaofloresta.mautic.com',       // Base URL of the Mautic instance
    'version'          => 'OAuth2',  // Version of the OAuth can be OAuth2 or OAuth1a. OAuth2 is the default value.
    'clientKey'        => '6_2ls1ifgi7dk4wws4sw4g0soo0wgcgsgwcscwwk4wc044s4ocsw',       // Client/Consumer key from Mautic
    'clientSecret'     => 'tazanlu41msg0g8o88sw8ok8g4k04wo4sksw0kswsc8occw48',       // Client/Consumer secret key from Mautic
    'callback'         => 'http://estacaofloresta.com.br/teste_mautic/mautic.php'        // Redirect URI/Callback URI for this script
);

/*
// If you already have the access token, et al, pass them in as well to prevent the need for reauthorization
$settings['accessToken']        = $accessToken;
$settings['accessTokenSecret']  = $accessTokenSecret; //for OAuth1.0a
$settings['accessTokenExpires'] = $accessTokenExpires; //UNIX timestamp
$settings['refreshToken']       = $refreshToken;
*/

// Initiate the auth object
$auth = ApiAuth::initiate($settings);

# $auth->enableDebugMode();

// Initiate process for obtaining an access token; this will redirect the user to the $authorizationUrl and/or
// set the access_tokens when the user is redirected back after granting authorization

// If the access token is expired, and a refresh token is set above, then a new access token will be requested

if ($auth->validateAccessToken()) {

    echo "<pre>";
    echo "<h1>validateAccessToken 1</h1>";
    echo "</pre>";

    // Obtain the access token returned; call accessTokenUpdated() to catch if the token was updated via a 
    // refresh token

    // $accessTokenData will have the following keys:
    // For OAuth1.0a: access_token, access_token_secret, expires
    // For OAuth2: access_token, expires, token_type, refresh_token

    if ($auth->accessTokenUpdated()) {
        $accessTokenData = $auth->getAccessTokenData();

        //store access token data however you want

        echo "<pre>";
        echo "<h1>accessTokenUpdated 1</h1>";
        echo "</pre>";
    }else{

        echo "<pre>";
        echo "<h1>accessTokenUpdated 0</h1>";
        echo "</pre>";
    }

}else{

    echo "<pre>";
    echo "<h1>validateAccessToken 0</h1>";
    echo "</pre>";
}

**Comment by naomicbush** [comment]
🎉  This is now available:

https://gravityplus.pro/gravity-forms-mautic/

**Comment by true2kozy** [comment]
> 🎉 This is now available:
> 
> https://gravityplus.pro/gravity-forms-mautic/

These guys do not respond when you fill out their form to get this plugins.  They just send you an email asking what you want and never reply or send anything.

**Comment by naomicbush** [comment]
@true2kozy We respond to everyone with a valid email address. I just checked, and don't see anyone without a response. You'd have better luck getting help through the [contact form](https://gravityplus.pro/contact/), though, than a 3 year old, closed issue.
