### ISSUE TITLE
Progressive forms not working!

### ISSUE THREAD

**Issue by incentfit-product** [mautic/mautic#11073]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What happened?

I have a progressive web form.  It's using the functionality referenced in https://github.com/mautic/mautic/pull/8611.  It was previously working just fine when I was on version 3.x but I recently updated to 4.2.1 and now all of my progressive forms are just showing all the fields.

### How can we reproduce this issue?

Create a form with 8 fields, set the "Maximum fields displayed at a time" to 4, and make sure to set "Always display" to "No" on all the fields.  It should show only 4 fields but it shows all 8.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi there, I can reproduce the issue. We'll take care of this.

**Comment by kuzmany** [comment]
This PR should fixed it https://github.com/mautic/mautic/pull/11125
But based on M3 version each field need this these settings of each field

![image](https://user-images.githubusercontent.com/462477/165576740-86d74a19-23f2-4729-baa5-5dfebe9b86ac.png)

**Comment by RCheesley** [comment]
This is resolved with #11125 which will be released at the end of the month in Mautic 4.3 🎉
