### ISSUE TITLE
Already created campaign cannot be published

### ISSUE THREAD

**Issue by noemibuscemi** [mautic/mautic#11079]
### Mautic Version

4.2.x series

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Chrome

### What happened?

An already created campaign cannot be published.
Workaround: clone the campaign and publish

### How can we reproduce this issue?

Step 1: create a campaign
Step 2: save the campaign
Step 3: exit
Step 4: search for the campaign 
Step 5: edit the campaign
Step 6: set the campaign as Published
**Issue**: the campaign cannot be published

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hello @noemibuscemi, I just tested in 4.2.1, and works fine. Any errors in the log?

**Comment by noemibuscemi** [comment]
Regenerating the assets is ok now

**Comment by RCheesley** [comment]
Closing the issue!
