### ISSUE TITLE
ChangeCampaign Event on Points Trigger doesn't work

### ISSUE THREAD

**Issue by carduz** [mautic/mautic#11078]
### Mautic Version

4.2.x series

### PHP version

7.4.29

### What happened?

The event "campaign.changecampaign" (AKA "Modify contact's campaigns") used in Point Triggers and declared Mautic\CampaignBundle\EventListener\PointSubscriber doesn't work, since it still uses "\Mautic\CampaignBundle\Helper\CampaignEventHelper::addRemoveLead" a method which was removed in the last versions.

### How can we reproduce this issue?

Step 1: Create a points trigger
Step 2: Add Modify contact's campaigns event to that points trigger
Step 3: Reach the minimum amount of points required to fire the trigger

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the report @carduz - any chance you would be open to making a PR to address this?

**Comment by carduz** [comment]
I've just rollbacked the previous behavior recreating the deprecated method "addRemoveLead" inside "CampaignEventHelper" using the new methods. But I suppose that if you have marked this method as deprecated the reason is that you are thinking of a better solution, so I've not sent a PR.
