### ISSUE TITLE
Bug with adding fields to email

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#1107]
I was creating a campaign when I realised an email was missing.  Clicked create new email, started populating it, but I can only drag one field in.

Subsequent fields are not input into the text area.

The first field I used was First Name, second was Last Name.  Tried others as well.

I seem to remember this being a bug which I had really early on, but not sure whether it's a new emergence or the same thing again.

**Comment by escopecz** [comment]
Thanks for the report. Could you clarify where did you drag fields into email message? In the email builder? Does it happen only when you create a new email from a campaign or does it happen even if you create a new email from the Email Manager?

**Comment by RCheesley** [comment]
Hi John,

I was using the email builder, indeed.  I think this time it happened when
I was creating a new email from the campaign builder, have not experienced
it using the email builder.

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 2 November 2015 at 13:06, John Linhart <notifications@github.com> wrote:

> Thanks for the report. Could you clarify where did you drag fields into
> email message? In the email builder? Does it happen only when you create a
> new email from a campaign or does it happen even if you create a new email
> from the Email Manager?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/1107#issuecomment-153011627>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by escopecz** [comment]
I tested it and worked for me. Maybe I'd need some more detailed steps I have to take. I did:

1. New campaign
2. Drag in the "Send email" action
3. Click new email in the "Send email" action. It opens a new browser window.
4. Selected the Coffee theme
5. Open the Email Builder
6. Drag&drop random fields to the theme slots
7. Saved email

I didn't notice any problem.
