### ISSUE TITLE
Click on name get an error

### ISSUE THREAD

**Issue by kuunda** [mautic/mautic#1108]
In Campaign > when you click to open an active campaign, you have 4 tabs the Leads tab if you click on the Name of the lead (see red arrow on attached image) you get an 500 error "Uh oh! I think I broke it. If I do it again, please report me to the system administrator! "

![2015-11-01_18-38-20](https://cloud.githubusercontent.com/assets/12907402/10870676/3fad95b6-80c8-11e5-9008-b0410bfde200.png)

**Comment by kuunda** [comment]
Same Issue with Leads see example images uploaded
![2015-11-01_18-45-20](https://cloud.githubusercontent.com/assets/12907402/10870702/de7929f8-80c8-11e5-8fc9-f39577557588.png)

**Comment by escopecz** [comment]
Could you check if https://github.com/mautic/mautic/issues/1051 is the same issue?

**Comment by kuunda** [comment]
Yes and 1 more
On 2 Nov 2015 08:36, John Linhart <notifications@github.com> wrote:Could you check if #1051 is the same issue?

**Comment by escopecz** [comment]
One more? Have you tried to update the database schema as is described in #1051? Were the issues fixed? If no, take a look at the Mautic logs (app/logs/ folder) and server logs to get more information about what is the problem.

**Comment by kuunda** [comment]
I got it fixed, this schema update did the trick thanks

php /path_to_mautic/app/console doctrine:schema:update --dump-sql
