### ISSUE TITLE
"From name" advanced setting does not apply

### ISSUE THREAD

**Issue by noemibuscemi** [mautic/mautic#11081]
### Mautic Version

4.2.x series

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Chrome

### What happened?

"From name" advanced setting does not apply when the email has been sent. 
The sender results to be "info" not the one inserted in the "from name" box.

### How can we reproduce this issue?

Step 1: Create an email
Step 2: Go to "Advanced"
Step 3: Fill in the "From name" box
Step 4: Save
Issue: when the email has been sent, the "from name" inserted does not apply as set

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hello @noemibuscemi ! Could you plz give feedback on the SMTP you are using. There was a similar bug with Amazon SES before couple of versions ago, but it was fixed. Maybe it's related. Thank you.

**Comment by noemibuscemi** [comment]
Sendgrid

**Comment by jos0405** [comment]
Hey, @mabumusa1 !
Any idea why this would be happening?
Thx for input.

**Comment by jos0405** [comment]
Hi quick question: are you using special characters in your from name other then alfabetical values?
