### ISSUE TITLE
No possibility to change the language of the preference center in the UI

### ISSUE THREAD

**Issue by toondeg** [mautic/mautic#11097]
### Mautic Version

4.1.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Chrome

### What happened?

We have a mautic env setup that shares contacts who have different languages.
We are not able to:
_Show a French preference center to a French contact_
_Show a Dutch preference center to a Dutch contact_

The only available option here is English, which is a crucial problem for us because we serve over +6 languages.

There is no possibility to change the text like there was in Mautic 3.x.x.

### How can we reproduce this issue?

Step 1: create preference center
Step 2: change language to ex: French
Step 3: set as preference center page
Step 4: add tokens to GrapeJS page builder manually
Step 5: check page: still english for us

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for raising the issue @toondeg - sounds like something isn't right with showing the correct language strings.

Is it everything on the page which is still showing in the default language or just the tokens?

**Comment by toondeg** [comment]
Hi Ruth

Just the basic language

**Comment by automatyzuj** [comment]
Problem still exists on M4.4

**Comment by toondeg** [comment]
Indeed, still an issue

**Comment by toondeg** [comment]
Just want to express that this is urgent for people in the EU.

This is causing GDPR issues because a user cannot unsub in their own language.

_The phrasing of this article means that language related to GDPR implementations should be both accessible and intelligeble, as well as in a language that the intended audience can be expected to understand._

**Comment by toondeg** [comment]
closed on accident

Just want to express that this is urgent for people in the EU.

This is causing GDPR issues because a user cannot unsub in their own language.

The phrasing of this article means that language related to GDPR implementations should be both accessible and intelligeble, as well as in a language that the intended audience can be expected to understand.

**Comment by RCheesley** [comment]
Have you checked the new PR to add the relevant blocks to the builder? 

Here is the PR to add the blocks to the preset: https://github.com/mautic/grapesjs-preset-mautic/pull/29 - would be great to get some feedback there.

**Comment by toondeg** [comment]
Checked the PR but does not seem to solve the issue, still relevant

**Comment by toondeg** [comment]
reopen

**Comment by leog** [comment]
Still an issue

**Comment by toondeg** [comment]
still an issue
