### ISSUE TITLE
Save E-Mail Link Color unreadable

### ISSUE THREAD

**Issue by zafai** [mautic/mautic#11091]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

When creating or saving an E-Mail the Link/Name of the E-Mail is unreadable/really hard to read.
Would be great if we could change the Link Color there.

![image](https://user-images.githubusercontent.com/10008540/164315585-36e1da51-d72d-48d1-ac76-d1d6e5b7bc6c.png)

### How can we reproduce this issue?

Step 1: Create a new E-Mail and Save it.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
The blue color is the same for everyone, but the German translation should add that space, which is missing. This can be done in transiflex. @kathrin-schmid or @oltmanns-leuchtfeuer , maybe you can do it for German? :)

**Comment by kathrin-schmid** [comment]
@jos0405 , done – i added the space in the german translation via transifex.
