### ISSUE TITLE
[Feature request] Add internal title for landing pages

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#1109]
Sometimes we have the same landing page but with different details for specific regions.  It would be helpful to be able to have an internal title much the same as the emails works, so that they can be distinguished from each other easily without affecting the displayed title.

**Comment by npracht** [comment]
Hi, i think this is important feature as explained by @RCheesley + the title is also used in the browser page & SEO.

When you create a landing page, you have the ability to give a **name to that landing page**. Here, the given name will **serve as SEO Title and as Internal name**.

## Suggestion
* Add in the right menu, a new field called `Internal name` that will serve in the landing page list.
* The actual `Title` input would be kept as `SEO Title`
* This is clearly inspired by what is done for the `email` creation.
