### ISSUE TITLE
Webview_text link corrupted in live emails

### ISSUE THREAD

**Issue by AchieveGirl** [mautic/mautic#11095]
### Mautic Version

4.2.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The issue: Webview token is adding wrong folder and hash to the preview link in live emails.  

I've sent several live emails from the builder, mostly using the Brienz template, but the problem also happened with the Paprika template, and the problem is the URL being generated to include in the email, not browser related.

From the screenshots below, you can see that when you click on the link in the email, it takes you to a folder named preview with "preview?idHash=" in the URL that throws a 404. After some troubleshooting we figured out that if we manually corrected the URL to "view/", then the email previews properly. We can't figure out where in Mautic this misdirection is occurring and how to fix it?

![Screenshot 2022-04-21 140347](https://user-images.githubusercontent.com/31334547/164553061-9f2201e2-7e1c-42c1-a07d-fb5b6d50dedc.png)
![Screenshot 2022-04-21 140817](https://user-images.githubusercontent.com/31334547/164553073-6be8c140-312e-4775-afd7-7503b3eeb62b.png)
![Screenshot 2022-04-21 141130](https://user-images.githubusercontent.com/31334547/164553095-9d153dd3-2fc8-4ed1-bb4d-eea33f503c9b.png)

I posted the issue in the Mautic forums over a week ago without any response - so I'm posting here since it seems to be some sort of bug, rather than any settings we can change within the interface. [https://forum.mautic.org/t/webview-text-link-doesnt-work-properly-in-live-emails-is-this-a-bug/23741](url)

Any help would be greatly appreciated!
 

### How can we reproduce this issue?

I think I've already covered this above, but to recap all I did was create a number of emails using one of two templates, included the webview token and pressed send.

Every email generated/sent has the same issue described above. I'm happy to forward a copy of the email but the links are encoded by Sendgrid so there is no meaningful source code visible. 

Whatever is going on seems to be happening behind the scenes in Mautic during the email generation process - perhaps in one of the .php files?

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, could you plz give me more info:Are you using the {webview_text} as token to generate that ink? Can you give an example link after its generated? Are there numbers shown?

Did you change anything in Config - Email? Is your box looking like this?

![image](https://user-images.githubusercontent.com/4246909/166711031-17b0cbeb-093a-4050-bf2f-9f83a33b04e3.png)

**Comment by AchieveGirl** [comment]
Hi Joey,
Yes, we are using the {webview_text} as token to generate the link and no we have not modified anything in the Config - email. I have already attached the screenshots you request and described how I was able to manually modify the address from the link throwing the 404 to a working link in my post above, and also in my emails to you requesting help on this issue.(April 13/14/20/21 - from kirsten@achieveanything.ca)  You mentioned in one of our exchanges you figured this was something in the back end which is why I filed this bug report. We have yet to find a solution and every time I send out a new batch of emails I get more messages from people telling me the link doesn't work... :(

If you scroll up you can see the screenshots and detailed steps/description... ;) Below is a screenshot to show our unmodified email settings.

If someone could tell us which PHP (or other) file(s) are used to transform the token into a link, and in which directory we would locate them, we'd be happy to try some edits to see if we can fix the misbehaving code. As it stands we have no idea where to look.

![Screenshot 2022-05-04 123653](https://user-images.githubusercontent.com/31334547/166812644-13c58fed-e1da-42fa-871d-ed9a0a89cd8f.png)

**Comment by jos0405** [comment]
Okay, thanks. I keep this bug open.
Regarding the code: you can make a search for webview_text token.
As a workaround you can hardcode the public url of that Email. I know its not ideal, but it would work at least.

**Comment by jos0405** [comment]
Hi @AchieveGirl !
Any progress on this?
Did you by the chance look at the server settings? In some cases server settings can affect redirection.
https://httpd.apache.org/docs/2.4/rewrite/remapping.html

Regards:
Joey

**Comment by AchieveGirl** [comment]
Hi Joey,

Thank you for the update, and no, no progress. It’s really annoying because I’ve been sending out tens of thousands of emails since we last communicated and I wish we could fix it. It seems like it should be something very simple in the code somewhere that is causing the address to generate incorrectly.

Thank you for the article – I’ll have a look this weekend to see if there’s any fix.

Best Regards,
Kirsten

**Comment by AchieveGirl** [comment]
Hi! This issue is not stale - it continues to frustrate us!

**Comment by shanbhardwaj** [comment]
Hi, 
I'm running into the same problem where I get links that look like the following for all emails.
```
https://marketing.example.com/email/unsubscribe/xxxxxxxxxxxxxx
https://marketing.example.com/email/view/xxxxxxxxxxxxxx
```
The xxxxxxxxxxxxxx are generated instead of an actual token
I'm using `{webview_text}` and `{unsubscribe_text}` to generate the links.

**Comment by jos0405** [comment]
What happens if you use {webview_url} and {unsubscribe_url} instead of "text" ?
Are the links okay?
@shanbhardwaj are you using Azure as well?

**Comment by AchieveGirl** [comment]
Hi there,

Please don’t close this issue – we’re still having a problem with it!


Best Regards,
Kirsten Brazier (she/her)
D. Tech. (honoris causa)
President
604-210-4033 ext. 102
[cid:internet_73d808c0-47b2-4f69-b76f-1e80cd3d9296.png] www.achieveanything.ca<http://www.achieveanything.ca> // www.girlsfly2.ca<http://www.girlsfly2.ca>
[cid:FBIcon_73f440b6-79c5-4385-957c-6a5e2e739dbb.png]  @AchieveAnythingFoundation<https://www.facebook.com/AchieveAnythingFoundation> // @SkysNoLimitGirlsFlyToo<https://www.facebook.com/SkysNoLimitGirlsFlyToo>
[cid:TwitterIcon_8cbbc8a1-cb5e-49bd-9a41-0a66149620a1.png] @AchieveGirl<https://twitter.com/AchieveGirl> // @she_is_anything<https://twitter.com/she_is_anything>
[cid:IGIcon_7508ce0f-2901-44b4-9dca-e3deed22ba54.png] @achieve.girl<https://www.instagram.com/achieve.girl> // @she.is.anything<https://www.instagram.com/she.is.anything>
[cid:YTicon_b126e89a-7952-484b-a41c-ce59e675d53c.png] Achieve Anything Foundation<https://www.youtube.com/channel/UCMnzhuWucyIWBry-oV7-JJg>
[cid:AAFlogo2_cb78c6e2-09bc-44e8-90de-c31df78b5948.png]<www.achieveanything.ca>
[cid:GF2logo_a91f661d-80c9-4301-becf-77eac658c001.png]<www.girlsfly2.ca>  [cid:OTIYlogo_6699ac5c-6a58-49df-a06f-414b6d30ea49.png] <www.achieveanything.ca/thisisyou.html>   [cid:PSGlogo_2a456370-a6a2-48b9-80bb-7bbd2c51f323.png] <www.achieveanything.ca>

**Comment by daniellord32** [comment]
I have stumbled onto this issue with our version of mautic. From what I can see it is accessing the incorrect function previewAction and it should be hitting indexAction in the publicController as it is using a Hash id. It is throwing the error as the hash is different from the email id and it obviously does not exist.

**Comment by jos0405** [comment]
Hi,
@daniellord32 - your latest bugfix on the Multi Domain Plugin fixes the issue. Everyone who experiences this bug, plz check if it fixes it for you: https://github.com/FriendlyDotCH/mautic-multi-domain/releases/tag/1.4.1

**Comment by daniellord32** [comment]
Just so people are aware, this issue has been fixed. The issue was found in the multidomainbundle located here: https://github.com/FriendlyDotCH/mautic-multi-domain, you should update the bundle and the webview token will work as expected.
