### ISSUE TITLE
Actions in campaign builder affect all contacts, not the segment selected

### ISSUE THREAD

**Issue by gradualChange** [mautic/mautic#11092]
### Mautic Version

4.2.x series

### PHP version

7,4.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

![Screenshot from 2022-04-21 13-01-54](https://user-images.githubusercontent.com/102276580/164365312-d836f744-157f-4e64-aab5-31609d6b5fda.png)

I created a campaign like this, chose a segment to source contacts from, and then added an action to send out an email. However, instead of just sending the email to those contacts in the segment, the email was sent out to all of the thousands of contacts in my database.

I checked the segment, but it only contained ~10 contacts beforehand and ~10 contacts after all those emails were sent. I don't know why it would have sent emails to every one of the contacts in Mautic.

As a workaround, I have started checking for the tag I add to all contacts who are a part of the segment, which works:
![Screenshot from 2022-04-21 13-51-49](https://user-images.githubusercontent.com/102276580/164368613-6d042214-d31b-4ef6-9978-695d8bd60ec9.png)

### How can we reproduce this issue?

I attempted to reproduce this issue in another 4.2.1 instance but was not able to.

Step 1: Create a campaign and select a segment

Step 2: Add an action to send an email

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @gradualChange - can you just double check that you are not looking at a paginated list when viewing the segment list? What criteria are you using to filter the segment?
