### ISSUE TITLE
[feature] bulk find social networks

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#111]
It would be great if there was some kind of automated way to check for existing social network accounts on a regular basis or on demand - often this isn't added at the time of creating the lead.

**Comment by alanhartless** [comment]
The code is there, we just need to add a "button" to the UI to do it.

**Comment by MaxOnTheHill** [comment]
@alanhartless that is AWESOME .... would love to see this added back in.
FYI: found this online and seemed to work really well ... however he does it:
https://websiteadvantage.com.au/Social-Profile-Search-Tool
