### ISSUE TITLE
It's not possible to insert filters in the segment

### ISSUE THREAD

**Issue by carduz** [mautic/mautic#11104]
### Mautic Version

4.2.x series

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Chrome

### What happened?

When you select a field in the filter section of a segment the field is not added and so you cannot add filters to the segments

### How can we reproduce this issue?

Step 1: Create a new segment
Step 2: Go to the filter section
Step 3: Select a field

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there,

Once you're on 4.2.1 please apply the command `bin/console m:a:g` to regenerate the JavaScript, and make sure you clear your browser cache.
