### ISSUE TITLE
Cloning landing pages doesn't always copy over content

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#1110]
I've had a couple of instances now where I've cloned a landing page, gone to edit the landing page with the builder, and no content exists.

It seems to happen if I hit Apply before I go to the builder - e.g. to save the name of the landing page & settings before I start editing.

Not sure if this is intentional or not!

**Comment by escopecz** [comment]
Yes, I can replicate. If the builder is not opened and the page is saved right after clone, it removes the content.
