### ISSUE TITLE
Filter dates for bounce report don't work

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#11108]
### Mautic Version

4.2.x series

### PHP version

7.4

### What happened?

Tried to filter for DNC date in the predefined bounce report.  The provided date selector has no effect at all. At least the Date to be checked seems not to be the DNC date.

Also defining two more filters dynamically don't work. We only get one field, which seems to be the "less than or equal" field.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/1241376/165079841-3b737281-7bb5-402e-b9fb-6a0480da4554.png">

### How can we reproduce this issue?

1. go to standard reports
2. try to filter by date
3. wont work
4. add 2 new filters for DNC date: 1) greater than or equal and 2) less than or equal, set them to dynamic
5. there will only be shown one more field, which seems to be the 2)

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @dsp76 

Have you tried bin/console `m:a:g` by any chance?

**Comment by dsp76** [comment]
@RCheesley I did. Also tested with 4.3.1 - its not working.

**Comment by dsp76** [comment]
@RCheesley this issue is not having pending feedback anymore.

**Comment by dsp76** [comment]
Still the case with 4.4.4
