### ISSUE TITLE
AND condition not working on segment filters

### ISSUE THREAD

**Issue by minholi** [mautic/mautic#11129]
### Mautic Version

4.2.x series

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Not relevant

### What happened?

AND condition not working on segment filters.

Combining 2 conditions based on custom field values only considers the first field.

### How can we reproduce this issue?

Step 1: Create 2 custom fields
Step 2: Create contacts using 2 or more different values on each field
Step 3: Create a segment and set 2 conditions using AND like the example

![image](https://user-images.githubusercontent.com/980209/165820976-9ffa9769-6635-4922-a4c6-9b19844230dc.png)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, the same segment filter works for me perfectly.

![image](https://user-images.githubusercontent.com/4246909/166704962-3ec50ba4-35a9-4ff9-bfcf-578fd720dc0b.png)

All other segments working properly? This is a selection field, right?

**Comment by minholi** [comment]
Double checked here. It was caused by a wrong contact list import.
