### ISSUE TITLE
API calls are creating session even though they should be stateless

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#11137]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

We noticed slowness and even denial of service for one of our clouds. We noticed there is several millions of API calls happening per day and that Redis which we use as the session storage was the bottleneck. It took us a while to connect the dots but the problem was that the [EmailStep](https://github.com/mautic/mautic/blob/4.x/app/bundles/InstallBundle/Configurator/Step/EmailStep.php#L115) from the InstallBundle is accessing session in its constructor ❗ 

So we created a quick patch of setting the `$user` to `null` because we do not use the InstallBundle but we need some more permanent solution.

One option is to use Local Storage or setting the session in a setter by a compiler pass to move the session out of the constructor.

### How can we reproduce this issue?

Step 1: Make any API call
Step 2: Check that session was created. You and dump and die at the end of `index.php`. Something like `dd($_SESSION)`.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
Wait, there might be very simple solution. I don't see the params that are set from the session used anywhere. Can we just remove the constructor?

**Comment by RCheesley** [comment]
Not stale

**Comment by mabumusa1** [comment]
Keep it open
