### ISSUE TITLE
Mautic does not work on Litespeed server

### ISSUE THREAD

**Issue by nikitakothari06** [mautic/mautic#11146]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Firefox

### What happened?

I have tried installing Mautic 4.2.2 on Litespeed server and it's not working. Post extracting the package when I try to execute the index.php file via browser it gives 403 forbidden error.

I have also tried adding a sub directory path in <If "%{REQUEST_URI} =~ m#^[[relativeurl]]/(index|index_dev|upgrade/upgrade)\.php#"> (Line no. 113) of .htaccess as suggested here. [https://github.com/mautic/mautic/issues/10913#issuecomment-1055681986](url) but it's not working.

Let me know what is causing this issue and how to resolve this

### How can we reproduce this issue?

Step 1:  Try to install mautic on Litespeed server

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by automatyzuj** [comment]
I'm not 100% sure, but I think Mautic is an application that just requires Apache and should be installed only on this kind of server.

**Comment by RCheesley** [comment]
Thanks for replying @automatyzuj - indeed this is documented here: https://www.mautic.org/download/requirements  - please discuss in the ideas forum at https://forum.mautic.org/c/ideas if you think that other servers should be supported and are willing to lead that initative.

As this isn't a bug with Mautic I am going to close the issue down.

**Comment by nikitakothari06** [comment]
Hi,

I just wanted to confirm if Mautic work on a Litespeed server ?

**Comment by geimsdin** [comment]
It works but you have to modify the htaccess using this or something like the attached file
[htaccess.zip](https://github.com/mautic/mautic/files/10491552/htaccess.zip)
