### ISSUE TITLE
Forms: Checkbox values aren't saved in contact information

### ISSUE THREAD

**Issue by automatyzuj** [mautic/mautic#11147]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

When using checkbox in a form the value of the checkbox wont be saved into the mapped contact field.

Link to older issue: https://github.com/mautic/mautic/issues/10613

### How can we reproduce this issue?

1. Create a form
2. Add an email field
3. Add a checkbox field
4. Map the checkbox onto that custom select field.
5. Add a Label and any Value in the properties-tab
6. Save the form
7. Fill out the form
8. See that no value has been saved into the mapped field

### Relevant log output

```shell
no log output.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
As far as I know checkbox can be only mapped to selection or multi select values, not text fields.

**Comment by automatyzuj** [comment]
> As far as I know checkbox can be only mapped to selection or multi select values, not text fields.

It also doesn't work.  @oltmanns-leuchtfeuer tried to map it to text field. But in my unit I tried mapping checkbox agree to select field. I suppose that checkbox value is only mapping correctly to boolean fields.

**Comment by jos0405** [comment]
We should add this info to the documentation, but I'm not sure, that this is a bug.

**Comment by automatyzuj** [comment]
I'm sure that is kind of regression. And I don't know why we should leave this feature? IMHO checkboxes are very good option to collect other type data then boolean.

**Comment by LeonOltmanns** [comment]
I also don't really see the point of limiting checkbox-values to boolean fields, but if it has some technical background reasoning thats fine - then we just need to document this properly.

**Comment by RCheesley** [comment]
This is already in the WIP Forms documentation I am writing for the new docs (the limitation about field types): https://github.com/mautic/user-documentation/pull/68/files#diff-0e566a247c5359efea8a0feff1ccbf99d6087f1fd798703ded243af6284c3ee7R89 (may need to expand the diff on the RST file)
