### ISSUE TITLE
Mautic does not preserve HTML formatting and doctype

### ISSUE THREAD

**Issue by benfavre** [mautic/mautic#11148]
### Mautic Version

4.2.x series

### PHP version

7.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

MJML emails generated (with or without the mjml attibute owa="outlook") do not render properly in outlook.
This worked fine in 3.x.x and is preventing us to upgrade.
We have tracked this down to the modification of the HTML source when running the sanitization process.

### How can we reproduce this issue?

Step 1: Use mautic.
Step 2: Create a MJML email or HTML email
Step 3: Paste the source of the email MJML or HTML
Step 4: Send it to outlook and gmail
Step 5: Notice that outlook renders the mail incorrectly (what is the culprid here ? Incorrect conditionnals or modified header tags ? We don't know yet)
Step 6: Cry and stay on V3.3

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the issue report, but this is a duplicate.

Please check https://github.com/mautic/mautic/issues/10953
