### ISSUE TITLE
mautic:update:find doesn't have an exit/error code (for automation/scripting)

### ISSUE THREAD

**Issue by perler** [mautic/mautic#11152]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

running` php bin/console mautic:update:find 
`doesn't give back an exit code. we would like to run `php bin/console mautic:update:apply` only when an update is available

### How can we reproduce this issue?

Step 1: php bin/console mautic:update:find
Step 2: echo $?

returns 0 even if update is available

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by luismts** [comment]
+1

**Comment by RCheesley** [comment]
Thanks for the report @perler - would you or @luismts be open to making a PR to add this functionality?

**Comment by perler** [comment]
that's way above my abilities, sorry.

**Comment by RCheesley** [comment]
No problems at all, always worth asking just in case!
