### ISSUE TITLE
A/B Testing Parent Percentage

### ISSUE THREAD

**Issue by DogByteMarketing** [mautic/mautic#11155]
![image](https://user-images.githubusercontent.com/40912852/167222886-d31e25a2-d8df-408a-b6e8-56532f10a48c.png)

### Mautic Version

4.2.2 series

### PHP version

7.4

### What happened?

When creating an A/B test and configuring it to be 50% in the new variant, it shows the parent to still have 100% under the variants tab in the email view. Only the child variant has a traffic weight. We're unsure if this effects the email send or not.

### How can we reproduce this issue?

Step 1: Create a new email
Step 2: Build the first email as an HTML template
Step 3: Click drop down next to close and click create A/B
Step 4: Configure the new email and assign 50% as the traffic weight

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, are these emails actually sent out already?

**Comment by DogByteMarketing** [comment]
> Hi, are these emails actually sent out already?

No, when we saw the percentages were incorrect, we deactivated it. Wanted to verify that it was just a display issue first.

**Comment by jos0405** [comment]
Probably a display issue. Do you want to keep the bug open?

**Comment by DogByteMarketing** [comment]
I'll setup a test to see if it functions correctly, but looking through the views it appears to pull the correct percentage based on
\app\bundles\CoreBundle\Views\Variant\row.html.php:19

`$weight        = (int) $variants['properties'][$id]['weight'];`

I'll report back if it does indeed send twice.

**EDIT**: I confirmed it's a display bug. I believe the issue lies with having our emails configured in a queue and when the cron runs to prepare the queue it changes from 100% to 50%.
