### ISSUE TITLE
Decimal Fields from SuiteCRM don't sync with Number Fields in Mautic

### ISSUE THREAD

**Issue by pstevens71** [mautic/mautic#11158]
### Mautic Version

4.1.x series

### PHP version

7.4

### What happened?

Mautic -> SuiteCRM synch seems to work good!  However, one field type has a problem.  In SuiteCRM I have an decimal field ie:  GPA = 2.75 (decimal data type)  and in Mautic I have GPA = Number.... there is no "decimal" option.  It will not synch the value from SuiteCRM to this field no matter what I set the Precision at.

### How can we reproduce this issue?

Step 1:  Create a decimal field in SuiteCRM
Step 2: Create a number field in Mautic
Step 3: sync these two fields with SuiteCRM plugin

Only "0" shows on the Mautic side.

### Relevant log output

```shell
There are no errors output.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @pstevens71 thanks for raising the bug. Can you share what you have set for the rounding and precision fields?

**Comment by pstevens71** [comment]
I tried it with 2 decimal (same setting as SuiteCRM) and 3 decimal and tried it blank.  All resulted in a "0" in Mautic.  Also,, Mautic when syncing did not recognize in SuiteCRM that the field was already populated with a decimal value and because I had "populate blank values selected" it over wrote the decimal value in SuiteCRM with "0.00".

**Comment by pstevens71** [comment]
This is still a problem.

**Comment by RCheesley** [comment]
Thanks for letting us know @pstevens71 - much appreciated! Which version of Mautic/Suite are you on currently?

**Comment by pstevens71** [comment]
I'm on 4.3.1.  I plan to upgrade to the latest soon and will post an update.  This issue has been around for  a few years.  I just recently narrowed it down to being the Decimal fields.  The only data I ever pushed back to SuiteCRM was the lead score.  And it never worked.  I originally thought that the sync back to SuiteCRM didn't work entirely.  When I had a few other fields to push back to SuiteCRM I realized they all worked except for decimal fields.  I haven't tried it yet, but I bet it would work as a workaround if I pushed the decimal value from Mautic to a Text field in SuiteCRM.  However, if you want to use the data in SuiteCRM it really needs to be in a numerical format.

**Comment by RCheesley** [comment]
Ah great to know the specifics, at least it gives us somewhere to start looking! Indeed it does make sense to make it work as it should rather than a workaround that inhibits what you can do in Suite.

**Comment by pstevens71** [comment]
I have tested with 4.4.1.  Number  fields in Mautic do not sync to SuiteCRM either "integer" or "decimal" field types.  I've tested both ways.  Syncing SuiteCRM -> Mautic produces a zero value.  Syncing Mautic -> SuiteCRM does not sync any value.
