### ISSUE TITLE
Page Hit without token is assigned to the last user that had a hit

### ISSUE THREAD

**Issue by Blackclaws** [mautic/mautic#11157]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What happened?

When sending emails to contacts that reference specific landing pages page hits are counted weirdly if the ?ct parameter is removed.

The page hit if removing the ?ct parameter will be assigned to the last contact that had a hit that included the ?ct parameter, even if coming from a totally different device.

The page hit should not be associated with any contact and should instead be an anonymous contact.

### How can we reproduce this issue?

Step 1: Create a Landing Page
Step 2: Create two contacts
Step 3: Send an email to the first contact that includes a link to the page
Step 4: Visit the link in the email, see that it is counted as a page hit.
Step 5: Remove the ?ct parameter and open the landing page without any token in a private window. The page hit is still associated with the user even though there is no way to track that it would be the same user (we've tried this from different IPs and PCs as well)
Step 6: Send an email to the second contact including a link to the page
Step 7: Click on the link in the second email
Step 7: Repeat Step 5, the hits are now associated with the second contact

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @Blackclaws could you elaborate why you are removing the ?ct parameter in the first place? What is the use case where this became a problem for you?

**Comment by Blackclaws** [comment]
The use case where this became a problem is, we simply tried what would happen if we did remove it, or rather if a newsletter recipient started tinkering with the parameters in the url. There is no specific use case but it does seem like unintended behaviour.

**Comment by Blackclaws** [comment]
This issue persists

**Comment by RCheesley** [comment]
Thanks for keeping it open @Blackclaws - which version of Mautic are you experiencing this on? We have a fix from Acquia for a similar issue:

> Tracked external links sent via email when the user is incognito. We track the email correctly but the page visit cant be linked to the user because the ct parameter was unset.

Could you review/test https://github.com/mautic/mautic/pull/11403 and see if this maybe goes some way to addressing the problem?

Here's a guide to testing in the browser: https://contribute.mautic.org/contributing-to-mautic/tester and here's how to report back your findings: https://contribute.mautic.org/contributing-to-mautic/tester#leaving-your-review.
