### ISSUE TITLE
Segment member contact list not loading in tab 4.3 BETA

### ISSUE THREAD

**Issue by jos0405** [mautic/mautic#11169]
### Mautic Version

4.2.x series

### PHP version

7.3

### What browsers are you seeing the problem on?

Chrome

### What happened?

The contact list is not rendering when opening a segment.

### How can we reproduce this issue?

1. Create any segment
2. Open segment and try to see members of this segment

![image](https://user-images.githubusercontent.com/4246909/168980461-4612e641-d697-4e77-98e6-a259da8b7b04.png)

### Relevant log output

```shell
The html looks like this:

            <!--/ tabs controls -->
        </div>

        <!-- start: tab-content -->
        <div class="tab-content pa-md">
            <div class="tab-pane active bdr-w-0 page-list" id="contacts-container" data-target-url="https://domain.com/s/segment/view/2/contact/1">

            <div class="spinner"><i class="fa fa-spin fa-spinner"></i></div>
            </div>
            <div class="tab-pane bdr-w-0 page-list" id="campaign-container">
                <div id="campaign-share-container" style="position: relative">
                    <table id="campaign-share-table" class="table table-bordered table-striped mb-0">
                        <thead>
                        <tr>
                            <th>
                                Campaign                            </th>
                            <th>
                                Share                            </th>
                        </tr>
                        </thead>
                        <tbody>
                                                    <tr>
                                <td>
                                    <a href="/s/campaigns/view/1" data-toggle="ajax">
                                        Double Opt-In                                    </a>
                                </td>
                                <td width="20%">
                                    <span class="campaign-share-stat" data-value="1"
                                          id="campaign-share-stat-1"></span> %
                                </td>
                            </tr>
                                                </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- end: tab-content -->
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
@jos0405 you don't have an error in the console ?

**Comment by npracht** [comment]
I think that might be related to https://github.com/mautic/mautic/pull/11005 cc @escopecz

**Comment by kuzmany** [comment]
Are you working on dev env? If not can you regenerate assets? `mautic:assets:generate`

**Comment by jos0405** [comment]
> Are you working on dev env? If not can you regenerate assets? `mautic:assets:generate`

It's a live install.
I regenerated assets, cleared cache, didn't help.
SSL is on.

**Comment by jos0405** [comment]
This works:
![image](https://user-images.githubusercontent.com/4246909/169074168-4f285cd9-3de4-4015-bb44-df52570fe5b5.png)

Just not when I open the segment.

**Comment by jos0405** [comment]
> I think that might be related to #11005 cc @escopecz

0 errors in console.

**Comment by escopecz** [comment]
@jos0405 I cannot replicate. The contacts are loading via AJAX for me:
![Screen Shot 2022-05-19 at 11 12 41](https://user-images.githubusercontent.com/1235442/169258302-6dff7665-739b-4bf8-a177-4efc7b39bfc7.png)
Can you double check that you've also cleared the browser cache?

**Comment by jos0405** [comment]
Super weird. Must be my environment. I will close it. Thanks for checking.
