### ISSUE TITLE
Contacts seeing each others variables in emails

### ISSUE THREAD

**Issue by richarddegoffau** [mautic/mautic#11170]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When using mautic variables (like {contactfield=email} ) the contacts are seeing each others variables in the email (to be specific: all contactss which are processed in the same batch are seeing the variables of the contact which is first processed).

This happens when using campaigns, which are triggered with cronjob mautic:campaigns:trigger. (default batchsize is 100).

As a workaround, I've set a batch-limit of 1 (mautic:campaigns:trigger --batch-limit=1), but that's slower.

### How can we reproduce this issue?

Step 1: Create a segment with 2 subscribed contacts
Step 2: Create an e-mail which contains the "{contactfield=email}" variable.
Step 3: Create a campaign, which e-mails the created segment, and with the created e-mail.
Step 4: Activate the campaign and look at the mail output.

### Relevant log output

```shell
not applicable
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hello @richarddegoffau , thank you for your report.
Just to be clear: are you using actual custom fields, like {contactfield=email} or are you using the RSS plugin to embed data?

**Comment by richarddegoffau** [comment]
Hello @jos0405 , 

Thank you for your question. I do use custom fields, but also an XML plugin to embed data :https://github.com/fastwarebv/mautic-xml-to-email-bundle.

There may be a relation between this XML-plugin and this bug - when I remove the XML plugin, I can't reproduce the issue.
(but in Mautic 4.1.x - the MauticXmlToEmailBundle plugin works just fine)

**Comment by jos0405** [comment]
Yeah, I suspected that. The xml data is pulled in when the batch is created. Unfortunatly the plugin will modify the email template for the batch, but not work as a custom field for the individual entity.
I understand, that this is not desired outcome, I ran into this myself when I tried to use the RSS plugin the same way :(
It was broken in M3 and M4 the same way as you mentioned above.

Do you make a query for each contact in the xml plugin?
Like `<feed url="https://myurl.com?feedemail={contactfield=email}">` ?

Thanks in advance.

**Comment by richarddegoffau** [comment]
No, my feed url doesn't contain contact-fields, but contains contact-independant content.
My email template looks like (some parts stripped):

`<mjml>`
`    <mj-section padding-top="0" padding-bottom="0">`
`         <mj-column width="600px">`
`		<mj-text font-size="24px" align="center" padding-left="0" padding-right="0">`
`		  <p>{contactfield=firstname} {contactfield=lastname}`
`		  </p>`
`		</mj-text>`
`		<mj-text padding-top="0" padding-bottom="0" padding-left="0" padding-right="0">`
`		  <feed url="https://[domain]/segments/copernica.xml?location=test">`
`			<feeditem loop="root">`
`			    <a href="{feeditem.url}" target="_blank"><img src="{feeditem.image}" id="idn9r" width="600" height="auto"></a>`
`			</feeditem>`
`		  </feed>`
`		</mj-text>`
`	  </mj-column>`
`	</mj-section>`
`	<mj-section background-color="#000" padding-bottom="0" padding-top="0">`
`	  <mj-column width="600px" background-color="#000000">`
`		<mj-text font-size="10px" align="center" color="#ffffff" padding-top="5px" padding-bottom="5px">`
`		  <p>`
`			<a href="https://[domain]/nieuwsbrief/link/{contactfield=email}/{contactfield=unsubscribe_token}" style="color: #ffffff">Uitschrijven</a>`
`		  </p>`
`		</mj-text>`
`	  </mj-column>`
`	</mj-section>`
`  </mj-body>`
`</mjml>`

The part in: `https://[domain]/nieuwsbrief/link/{contactfield=email}/{contactfield=unsubscribe_token}` goes wrong, both variables are filled with fields from another user.
Strange enough: the `{contactfield=firstname} {contactfield=lastname}` are always showing the right content.

**Comment by jos0405** [comment]
Yeah, cause it's in the loop.
Which means it is created by the plugin.
When the batch is called, not individually.
This seems like a plugin error to me.

![image](https://user-images.githubusercontent.com/4246909/169050629-2b754015-76b5-4afe-b29f-1c1bc0015841.png)

**Comment by richarddegoffau** [comment]
_Yeah, cause it's in the loop._
The `https://[domain]/nieuwsbrief/link/{contactfield=email}/{contactfield=unsubscribe_token}` part is outside the loop (and this is the part where is goes wrong).

_This seems like a plugin error to me._
Yes, I think you may be right, however, in Mautic 4.1.x the plugin worked fine - so there must be something changed in Mautic core too.

(Besides, I'm the developer of the MauticXmlToEmail plugin, so I'll look into it)

**Comment by jos0405** [comment]
**Besides, I'm the developer of the MauticXmlToEmail plugin, so I'll look into it**
Lol, you should have started with that :D
If you could fix it it would be awesome!
Do you think we should keep the bug open here?

**Comment by richarddegoffau** [comment]
_Do you think we should keep the bug open here?_
No, I'll close it
