### ISSUE TITLE
Install steps not working

### ISSUE THREAD

**Issue by rmunoz10** [mautic/mautic#11184]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Firefox

### What happened?

I am trying to install following these steps from https://github.com/mautic/mautic but when I open the page I get "resolve());"

Installing Mautic is a simple three-step process:
    [Download the repository zip](https://github.com/mautic/mautic/archive/refs/heads/features.zip) then extract the zip to your web root.
    Run the composer install command to install the required packages.
    Open your browser and complete the installation through the web installer.

### How can we reproduce this issue?

Ubuntu 20.04
Step 1: Installed Apache and Composer. They both work
Step 2: Clicked on the link and it downloads features.zip; then extract the zip to /var/www/html
Step 3: Open browser on http://mylocal and I get 
resolve()); 

### Relevant log output

```shell
No apache or syslog errors
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
