### ISSUE TITLE
Hide "missing" or removed plugins

### ISSUE THREAD

**Issue by LuisOna** [mautic/mautic#1118]
plugin is not removed completely once plugin is removed in plugin directory and cache is cleared.

**Comment by escopecz** [comment]
I can replicate.

**Comment by CreaoticX** [comment]
I just tried deleting a plugin in 2.1.1 and it's still listed under plugins after deleting the folder under the plugin directory, clearing the cache repeatedly, and running update/install plugins to see if that made a difference.

**Comment by CreaoticX** [comment]
I ended up having to go into the database in the new plugins table and delete if from there.  I cleared the cache again afterwards too, but I'm not sure this is necessary.  Interestingly the plugins table has a missing column that still showed 0 even though all the files were removed.

**Comment by alanhartless** [comment]
Likely we are just missing the condition in the query to filter the missing out. The entry is left there because we don't remove the plugins custom schema so if the plugin is reinstalled - it's known what version the schema is in.
