### ISSUE TITLE
Using double optin campaign 

### ISSUE THREAD

**Issue by kuunda** [mautic/mautic#1119]
I have setup and double optin campaign everything worked except the bit where it has to move the user to an a list after 

... the disturbing bit it says it has actually done so but it hasn't.

![2015-11-03_07-44-08](https://cloud.githubusercontent.com/assets/12907402/10903175/d1eff022-81fe-11e5-9593-e9e4afdb93b6.png)

![2015-11-03_07-45-48](https://cloud.githubusercontent.com/assets/12907402/10903208/1f46f5e6-81ff-11e5-8ae5-9cbd4030e8cc.png)

Any suggestions, btw I have waited about a day so 100% convinced there is an issue

**Comment by kuunda** [comment]
@escopecz @alanhartless (hey Alan Lance here)
have you managed to take a look at this yet?

**Comment by escopecz** [comment]
I tested it. Adding a list and removing a list worked for me fine. Well, it threw an error so I had to trigger the campaign multiple times to get it processed to the end. This PR fixed the error message for me and all worked smoothly after that:

https://github.com/mautic/mautic/pull/1100

**Comment by alanhartless** [comment]
@kuunda Can you confirm John's findings?

**Comment by kuunda** [comment]
Hi Alan

Mine still doesn’t work. I have made duplicate copies, I have tested it over and over it doesn’t work. When you look at campaign actions tab it show "
Move to Confirmed List 0 %"

**Comment by escopecz** [comment]
@kuunda when you say still, do you mean with or without the fix in #1100? Because the fix will be available in Mauti 1.2.3.

**Comment by kuunda** [comment]
Yes I meant without the fix

**Comment by escopecz** [comment]
@kuunda could you try now with Mautic 1.2.3?

**Comment by lance-spurgeon** [comment]
Thank you have upgraded. Will this fix for people currently stuck in the campaign already if not how can I get them then forced through the campaign
