### ISSUE TITLE
Cookie GDPR problem: Focus Item Maximum date too far in the future (year 9999)

### ISSUE THREAD

**Issue by MaraKasubke** [mautic/mautic#11201]
### Mautic Version

4.2.x series

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

This is a problem that was reported before: https://github.com/mautic/mautic/issues/9705

It is still relevant as it is GDPR violation. If the cookie is just stored for a session than everything would be okay. But to set the duration to year 9999 does not make sense and is a legal problem.

![2022-05-30_15h53_13](https://user-images.githubusercontent.com/34441995/171007894-574921ce-37f7-4ae3-a040-388d0c2d06f7.png)
 

### How can we reproduce this issue?

Step 1: Create focus and set the interaction field to "once per session".
Step 2: Embed the Focus Item in you website
Step 3: Go to that website and wait till the focus item shows
Step 4: Go to developer tools of the browser and find the cookie section

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by MaraKasubke** [comment]
The problem is still present. Will there be any changes in further mautic updates?

**Comment by mabumusa1** [comment]
@mabumusa1 looking into this in the next month
