### ISSUE TITLE
The text editor inside the builder adds unexpected code. 

### ISSUE THREAD

**Issue by adiux** [mautic/mautic#11205]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome, Not relevant

### What happened?

After opening a MJML theme (e.g. Brienz) and changing the predefined text, the formatting gets "destroyed". E.g. in this case the text gets smaller and I think it is another font:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/13075514/171363086-48b254e7-1144-424d-9ec1-d04d82e10878.png">

In other cases more padding is added.

What happens in the code: the text editor (CKEditor) always adds extra `<p>` tags.

before editing
<img width="821" alt="image" src="https://user-images.githubusercontent.com/13075514/171363307-5e148d5f-3cfa-4db9-a122-972fe7d6ad5e.png">

after editing
<img width="811" alt="image" src="https://user-images.githubusercontent.com/13075514/171363368-f3aac3c1-e817-4ce1-92bb-07e47c28c376.png">

### How can we reproduce this issue?

Step 1: open any MJML email theme (e.g. Brienz)
Step 2: change the title
Step 3: The formatting of the text will change (see above), in the code you will see the `<p>` tags.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by internalfx** [comment]
I have this same problem

**Comment by mabumusa1** [comment]
Still exist

**Comment by jvalousek** [comment]
The problem still persists. It would be great if there was an option to edit the CKEDITOR configuration file somewhere in the administration to override the default settings.
