### ISSUE TITLE
Schema Error Upgrade from 4.2 to 4.3.1 - canno´t drop index

### ISSUE THREAD

**Issue by leoborlot** [mautic/mautic#11204]
### Mautic Version

4.2.x series

### PHP version

php 7.3

### What happened?

Whet we try upgrade from 4.2 to 4.3.1 we recive error on schema update.  The Mautic cannot remove this index from database. 

DROP INDEX IDX_1AE3441319EB6921 ON oauth2_user_client_xref;
DROP INDEX IDX_6480052EF639F774 ON campaign_leadlist_xref;
DROP INDEX IDX_3048A8B2F639F774 ON campaign_form_xref;
DROP INDEX IDX_5995213DF639F774 ON campaign_leads;
DROP INDEX IDX_2E24F01CA832C1C9 ON email_list_xref;
DROP INDEX IDX_CA315778A832C1C9 ON email_assets_xref;
DROP INDEX IDX_9EED7E6655458D ON lead_ips_xref;
DROP INDEX IDX_F2E51EB655458D ON lead_tags_xref;
DROP INDEX IDX_F5F47C7CB9FC8874 ON lead_lists_leads;
DROP INDEX IDX_F4190AB6979B1AD6 ON companies_leads;
DROP INDEX IDX_473919EFEF1A9D84 ON push_notification_list_xref;
DROP INDEX IDX_2F81A41DB42D874D ON channel_url_trackables;
DROP INDEX IDX_C2A3BDBA71F7E88B ON point_lead_event_log;
DROP INDEX IDX_6DF94A56C028CEA2 ON point_lead_action_log;
DROP INDEX IDX_B032FC2EBD5C7E60 ON sms_message_list_xref;
DROP INDEX IDX_A506AFBE2298D193 ON stage_lead_action_log;
DROP INDEX IDX_45207A4A4CE1C902 ON monitoring_leads;

### How can we reproduce this issue?

Install mautic 4.2. and update te database. 
UPgrade to 4.3.1 and try to run the command to update the schema.

`php bin/console doctrine:schema:update --force`

Mautic will return erros like this:
An exception occurred while executing 'DROP INDEX IDX_1AE3441319EB6921 ON oauth2_user_client_xref':                       SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'IDX_1AE3441319EB6921'; check that column/key exists

![chrome_dQmmrn5os7](https://user-images.githubusercontent.com/20361821/171291373-7d05c003-2560-4d9e-af2e-78e202f6bb3a.png)

### Relevant log output

```shell
If I remove this drop index instruction, the another one wokrs fine.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by Cloudore** [comment]
I seem to also been experiencing this issue.
<img width="1220" alt="Screen Shot 2022-06-01 at 8 18 08 PM" src="https://user-images.githubusercontent.com/22532038/171527061-adfd91f7-5514-4943-b0c2-0a74f9d8b299.png">

**Comment by saschafoerster** [comment]
Same here. 
<img width="1124" alt="Bildschirmfoto 2022-06-08 um 21 43 31" src="https://user-images.githubusercontent.com/1153741/172704288-04fee513-8367-46d2-b70b-4c88dce940ec.png">

I tried deleting the index manually, which created another error message. And just as a sidenote: it's already since the recommended switch to composer-installation some weeks ago that our Mautic-instance is not operational. I know it's an open source product, so I try to help debugging, but still i am losing trust in the mautic-development, when untested methods and broken migrations are deployed as "stable". I am ready to help testing more and I hope that soon everything works smooth again.

Has someone an idea what to change manually in the database to fix this error and continue migration?

**Comment by saschafoerster** [comment]
```
sudo -u www-data php bin/console doctrine:schema:update --force --verbose

In SchemaException.php line 72:
                                                                                                         
  [Doctrine\DBAL\Schema\SchemaException (60)]                                                            
  An index with name 'idx_baaebe2f19eb6921' was already defined on table 'mau_oauth2_user_client_xref'.  
                                                                                                         

Exception trace:
  at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:72
 Doctrine\DBAL\Schema\SchemaException::indexAlreadyExists() at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:524
 Doctrine\DBAL\Schema\Table->_addIndex() at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:582
 Doctrine\DBAL\Schema\Table->_addForeignKeyConstraint() at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:79
 Doctrine\DBAL\Schema\Table->__construct() at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:291
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTableDetails() at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:327
 Doctrine\DBAL\Schema\MySqlSchemaManager->listTableDetails() at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:270
 Doctrine\DBAL\Schema\AbstractSchemaManager->listTables() at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:1072
 Doctrine\DBAL\Schema\AbstractSchemaManager->createSchema() at /var/www/html/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:971
 Doctrine\ORM\Tools\SchemaTool->createSchemaForComparison() at /var/www/html/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php:942
 Doctrine\ORM\Tools\SchemaTool->getUpdateSchemaSql() at /var/www/html/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/UpdateCommand.php:79
 Doctrine\ORM\Tools\Console\Command\SchemaTool\UpdateCommand->executeSchemaCommand() at /var/www/html/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php:46
 Doctrine\ORM\Tools\Console\Command\SchemaTool\AbstractCommand->execute() at /var/www/html/mautic/vendor/doctrine/doctrine-bundle/Command/Proxy/UpdateSchemaDoctrineCommand.php:40
 Doctrine\Bundle\DoctrineBundle\Command\Proxy\UpdateSchemaDoctrineCommand->execute() at /var/www/html/mautic/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/html/mautic/vendor/symfony/console/Application.php:1027
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:97
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/mautic/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php:83
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/mautic/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/html/mautic/bin/console:42

doctrine:schema:update [--em EM] [--complete] [--dump-sql] [-f|--force] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by Cloudore** [comment]
This is my output to that same command

`sudo -u www-data php bin/console doctrine:schema:update --force --verbose`
<img width="1010" alt="Screen Shot 2022-06-08 at 4 57 18 PM" src="https://user-images.githubusercontent.com/22532038/172724491-0953723d-96d1-4eec-a2e7-27fb8655456c.png">

Any help, appreciated.

**Comment by zietbukuel** [comment]
I have the exact same issue.
<img width="854" alt="Screen Shot 2022-06-13 at 16 10 46" src="https://user-images.githubusercontent.com/1046971/173446194-4749e85a-ea5c-4972-b33c-5e1976dd4df6.png">

**Comment by J-Wick4** [comment]
I two have the exact same problem. 

I went to the extreme of using the composer method to install a fresh copy of 4.3.1 and experienced the same error right out the gate.

4.3.1 should be pulled back from the "stable" channel until this is fixed.

Centos 7.9
PHP 7.4
MariaDB 10.4.25

**Comment by Cloudore** [comment]
My instance goes 500 every about 24 hours, this is really hurtful to stability.

**Comment by JyFu-py** [comment]
Same problem here

![image](https://user-images.githubusercontent.com/67822884/174079183-226fa97a-eee5-4b0a-af29-fcf3a55aaaf0.png)

To handle update and skip drop index, we have removed line 132 to 141 from app/bundles/CoreBundle/EventListener/DoctrineEventsSubscriber.php with a composer patch

seem related to this commit
https://github.com/mautic/mautic/commit/fcc1d2be66b7dc7e30fcb439ef4991f329f8b21d#diff-b50e24c8ed3c1b015020af4d15c31b0955de2bdb7c3f2dca9175ef2f4ce1c88e

**Comment by luizeof** [comment]
same here ... upgrade process is not so "stable" as in versions prior to 4.3.1

 #9129 already reported a similar error 2 years ago.

**Comment by escopecz** [comment]
Where did you guys found that running `php bin/console doctrine:schema:update --force` is the way to upgrade Mautic? I cannot stress this enough:

**DO NOT RUN THIS COMMAND!!!**

This is the right command to run migrations and update Mautic:

`bin/console doctrine:migrations:migrate`

If you are troubleshooting something, print out the queries that differ from the Doctrine entities, read them carefully, **understand** what they do and execute them one by one after a database backup. To get the list of queries use this command:

`bin/console doctrine:schema:update --dump-sql`

**Comment by Cloudore** [comment]
> Where did you guys found that running `php bin/console doctrine:schema:update --force` is the way to upgrade Mautic? I cannot stress this enough:
> 
> **DO NOT RUN THIS COMMAND!!!**
> 
> This is the right command to run migrations and update Mautic:
> 
> `bin/console doctrine:migrations:migrate`
> 
> If you are troubleshooting something, print out the queries that differ from the Doctrine entities, read them carefully, **understand** what they do and execute them one by one after a database backup. To get the list of queries use this command:
> 
> `bin/console doctrine:schema:update --dump-sql`

We, or at least, have tried this to no avail:

`root@vultr:/var/www/html# sudo -u www-data php bin/console doctrine:migrations:migrate  Mautic Migrations    WARNING! You have 134 previously executed migrations in the database that are not registered migrations.

Are you sure you wish to continue? (y/n)y
WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
No migrations to execute.`

`root@vultr:/var/www/html# sudo -u www-data php bin/console doctrine:schema:update --dump-sql

 The following SQL statements will be executed:

 * DROP INDEX IDX_1AE3441319EB6921 ON oauth2_user_client_xref
 * DROP INDEX IDX_6480052EF639F774 ON campaign_leadlist_xref
 * DROP INDEX IDX_3048A8B2F639F774 ON campaign_form_xref
 * DROP INDEX IDX_5995213DF639F774 ON campaign_leads
 * DROP INDEX IDX_2E24F01CA832C1C9 ON email_list_xref
 * DROP INDEX IDX_CA315778A832C1C9 ON email_assets_xref
 * ALTER TABLE form_fields CHANGE parent_id parent_id VARCHAR(191) DEFAULT NULL
 * DROP INDEX timezone_search ON leads
 * DROP INDEX unique_identifier_search ON leads
 * DROP INDEX last_active_search ON leads
 * DROP INDEX mwb_last_order_stat_search ON leads
 * ALTER TABLE leads ADD fax VARCHAR(191) DEFAULT NULL, ADD website VARCHAR(191) DEFAULT NULL, ADD facebook VARCHAR(191) DEFAULT NULL, ADD foursquare VARCHAR(191) DEFAULT NULL, ADD linkedin VARCHAR(191) DEFAULT NULL, ADD skype VARCHAR(191) DEFAULT NULL, ADD twitter VARCHAR(191) DEFAULT NULL, DROP mwb_last_order_stat, CHANGE preferred_locale preferred_locale VARCHAR(191) DEFAULT NULL, CHANGE instagram instagram VARCHAR(191) DEFAULT NULL, CHANGE gender gender VARCHAR(191) DEFAULT NULL, CHANGE phone2 phone2 VARCHAR(191) DEFAULT NULL, CHANGE contact_person contact_person VARCHAR(191) DEFAULT NULL, CHANGE cedula cedula VARCHAR(191) DEFAULT NULL, CHANGE store store VARCHAR(191) DEFAULT NULL, CHANGE mall mall VARCHAR(191) DEFAULT NULL, CHANGE permisos_de_contacto permisos_de_contacto VARCHAR(191) DEFAULT NULL, CHANGE mwb_customer_group mwb_customer_group VARCHAR(191) DEFAULT NULL, CHANGE mwb_newsletter_subs mwb_newsletter_subs VARCHAR(191) DEFAULT NULL, CHANGE mwb_ship_add_line_1 mwb_ship_add_line_1 VARCHAR(191) DEFAULT NULL, CHANGE mwb_ship_add_line_2 mwb_ship_add_line_2 VARCHAR(191) DEFAULT NULL, CHANGE mwb_ship_city mwb_ship_city VARCHAR(191) DEFAULT NULL, CHANGE mwb_ship_state mwb_ship_state VARCHAR(191) DEFAULT NULL, CHANGE mwb_ship_post_code mwb_ship_post_code VARCHAR(191) DEFAULT NULL, CHANGE mwb_ship_country mwb_ship_country VARCHAR(191) DEFAULT NULL, CHANGE mwb_bill_add_line_1 mwb_bill_add_line_1 VARCHAR(191) DEFAULT NULL, CHANGE mwb_bill_add_line_2 mwb_bill_add_line_2 VARCHAR(191) DEFAULT NULL, CHANGE mwb_bill_city mwb_bill_city VARCHAR(191) DEFAULT NULL, CHANGE mwb_bill_state mwb_bill_state VARCHAR(191) DEFAULT NULL, CHANGE mwb_bill_country mwb_bill_country VARCHAR(191) DEFAULT NULL, CHANGE mwb_order_monetary mwb_order_monetary VARCHAR(191) DEFAULT NULL, CHANGE mwb_order_frequency mwb_order_frequency VARCHAR(191) DEFAULT NULL, CHANGE mwb_order_recency mwb_order_recency VARCHAR(191) DEFAULT NULL, CHANGE mwb_abncart_stat mwb_abncart_stat VARCHAR(191) DEFAULT NULL, CHANGE mwb_abncart_url mwb_abncart_url VARCHAR(191) DEFAULT NULL, CHANGE mwb_last_order_ff_stat mwb_last_order_ff_stat VARCHAR(191) DEFAULT NULL, CHANGE mwb_last_order_track_url mwb_last_order_track_url VARCHAR(191) DEFAULT NULL, CHANGE mwb_last_pay_method mwb_last_pay_method VARCHAR(191) DEFAULT NULL, CHANGE mwb_prod_1_img_url mwb_prod_1_img_url VARCHAR(191) DEFAULT NULL, CHANGE mwb_prod_1_name mwb_prod_1_name VARCHAR(191) DEFAULT NULL, CHANGE mwb_prod_2_img_url mwb_prod_2_img_url VARCHAR(191) DEFAULT NULL, CHANGE mwb_prod_2_name mwb_prod_2_name VARCHAR(191) DEFAULT NULL, CHANGE mwb_prod_3_img_url mwb_prod_3_img_url VARCHAR(191) DEFAULT NULL, CHANGE mwb_prod_3_name mwb_prod_3_name VARCHAR(191) DEFAULT NULL, CHANGE mwb_prod_3_url mwb_prod_3_url VARCHAR(191) DEFAULT NULL, CHANGE mwb_categories mwb_categories VARCHAR(191) DEFAULT NULL, CHANGE mwb_last_categories mwb_last_categories VARCHAR(191) DEFAULT NULL, CHANGE mwb_coupon_code mwb_coupon_code VARCHAR(191) DEFAULT NULL, CHANGE mwb_used_coupons mwb_used_coupons VARCHAR(191) DEFAULT NULL, CHANGE mwb_last_coupon mwb_last_coupon VARCHAR(191) DEFAULT NULL, CHANGE mwb_abdn_coupon mwb_abdn_coupon VARCHAR(191) DEFAULT NULL, CHANGE mwb_prod_skus mwb_prod_skus VARCHAR(191) DEFAULT NULL, CHANGE mwb_last_sku mwb_last_sku VARCHAR(191) DEFAULT NULL
 * CREATE INDEX fax_search ON leads (fax)
 * CREATE INDEX website_search ON leads (website)
 * CREATE INDEX facebook_search ON leads (facebook)
 * CREATE INDEX foursquare_search ON leads (foursquare)
 * CREATE INDEX linkedin_search ON leads (linkedin)
 * CREATE INDEX skype_search ON leads (skype)
 * CREATE INDEX twitter_search ON leads (twitter)
 * CREATE INDEX date_of_birth_search ON leads (date_of_birth)
 * CREATE INDEX mwb_abdn_coupon_search ON leads (mwb_abdn_coupon)
 * CREATE INDEX mwb_prod_skus_search ON leads (mwb_prod_skus)
 * CREATE INDEX mwb_last_sku_search ON leads (mwb_last_sku)
 * CREATE INDEX mwb_last_coupon_search ON leads (mwb_last_coupon)
 * CREATE INDEX mwb_coupon_exp_search ON leads (mwb_coupon_exp)
 * CREATE INDEX mwb_coupon_disc_search ON leads (mwb_coupon_disc)
 * CREATE INDEX mwb_used_coupons_search ON leads (mwb_used_coupons)
 * CREATE INDEX mwb_coupon_code_search ON leads (mwb_coupon_code)
 * CREATE INDEX mwb_abncart_total_search ON leads (mwb_abncart_total)
 * CREATE INDEX mwb_abncart_prods_count_search ON leads (mwb_abncart_prods_count)
 * CREATE INDEX mwb_acc_creation_date_search ON leads (mwb_acc_creation_date)
 * CREATE INDEX mwb_avg_order_value_search ON leads (mwb_avg_order_value)
 * CREATE INDEX mwb_total_val_of_orders_search ON leads (mwb_total_val_of_orders)
 * CREATE INDEX mwb_last_categories_search ON leads (mwb_last_categories)
 * CREATE INDEX mwb_prod_3_url_search ON leads (mwb_prod_3_url)
 * CREATE INDEX mwb_categories_search ON leads (mwb_categories)
 * CREATE INDEX mwb_prod_3_name_search ON leads (mwb_prod_3_name)
 * CREATE INDEX mwb_prod_3_img_url_search ON leads (mwb_prod_3_img_url)
 * CREATE INDEX mwb_prod_2_name_search ON leads (mwb_prod_2_name)
 * CREATE INDEX mwb_prod_2_img_url_search ON leads (mwb_prod_2_img_url)
 * CREATE INDEX mwb_prod_1_name_search ON leads (mwb_prod_1_name)
 * CREATE INDEX mwb_last_order_num_search ON leads (mwb_last_order_num)
 * CREATE INDEX mwb_last_order_ship_date_search ON leads (mwb_last_order_ship_date)
 * CREATE INDEX mwb_last_order_track_num_search ON leads (mwb_last_order_track_num)
 * CREATE INDEX generated_email_domain ON leads (generated_email_domain)
 * DROP INDEX IDX_9EED7E6655458D ON lead_ips_xref
 * DROP INDEX IDX_F2E51EB655458D ON lead_tags_xref
 * DROP INDEX IDX_F5F47C7CB9FC8874 ON lead_lists_leads
 * DROP INDEX companycity_search ON companies
 * DROP INDEX unique_identifier_search ON companies
 * DROP INDEX companyzipcode_search ON companies
 * DROP INDEX companyname_search ON companies
 * DROP INDEX companyaddress1_search ON companies
 * DROP INDEX companyemail_search ON companies
 * DROP INDEX companyphone_search ON companies
 * DROP INDEX companystate_search ON companies
 * DROP INDEX companycountry_search ON companies
 * DROP INDEX companyindustry_search ON companies
 * DROP INDEX companyaddress2_search ON companies
 * ALTER TABLE companies ADD companynumber_of_employees DOUBLE PRECISION DEFAULT NULL, ADD companyfax VARCHAR(191) DEFAULT NULL, ADD companyannual_revenue DOUBLE PRECISION DEFAULT NULL, CHANGE companywebsite companywebsite VARCHAR(191) DEFAULT NULL
 * CREATE INDEX companynumber_of_employees_search ON companies (companynumber_of_employees)
 * CREATE INDEX companyfax_search ON companies (companyfax)
 * CREATE INDEX companyannual_revenue_search ON companies (companyannual_revenue)
 * DROP INDEX IDX_F4190AB6979B1AD6 ON companies_leads
 * DROP INDEX IDX_473919EFEF1A9D84 ON push_notification_list_xref
 * CREATE INDEX page_hit_url ON page_hits (url(128))
 * DROP INDEX IDX_2F81A41DB42D874D ON channel_url_trackables
 * DROP INDEX IDX_6DF94A56C028CEA2 ON point_lead_action_log
 * DROP INDEX IDX_C2A3BDBA71F7E88B ON point_lead_event_log
 * DROP INDEX IDX_B032FC2EBD5C7E60 ON sms_message_list_xref
 * DROP INDEX IDX_A506AFBE2298D193 ON stage_lead_action_log
 * DROP INDEX IDX_45207A4A4CE1C902 ON monitoring_leads
`

**Comment by escopecz** [comment]
@Cloudore do you have some problem with your Mautic you want to solve or is it just that the command gives you some SQL queries you wish to execute so the output is clear? Doctrine was not built for implementation of custom fields that Mautic use so all the queries on the leads and companies tables are result of that. I don't know history of your Mautic instance. Maybe you've changed the table prefix in the past or something similar. I see nothing that needs to be executed unless you are struggling with performance.

**Comment by JyFu-py** [comment]
Sorry but with a fresh composer install (4.3.1) i have this :

![image](https://user-images.githubusercontent.com/67822884/175009108-493c3ebe-5d3c-4edc-89c6-8da7485518b5.png)
![image](https://user-images.githubusercontent.com/67822884/175009392-acbb4359-4d51-4cef-8a0c-ed1d36ec8782.png)

**Comment by Cloudore** [comment]
> @Cloudore do you have some problem with your Mautic you want to solve or is it just that the command gives you some SQL queries you wish to execute so the output is clear? Doctrine was not built for implementation of custom fields that Mautic use so all the queries on the leads and companies tables are result of that. I don't know history of your Mautic instance. Maybe you've changed the table prefix in the past or something similar. I see nothing that needs to be executed unless you are struggling with performance.

Not only do I have a problem, Mautic is unusable almost, loses connection to the DB every 24 hours until I restart it

**Comment by escopecz** [comment]
@Cloudore what does it mean that Mautic loses connection to the DB every 24 hours? It sounds to me more like an infrastructure problem. Not an application problem. Do you have any errors that could help you understand the problem? Isn't the DB server overloaded once/day? Creating indexes may give you some speed improvement for reads. For example for building segments if you have segment filters on those columns. Dropping unnecessary indexes is not that big of a deal. They take some space and make writes slightly slower, but that shouldn't be noticeable. It definitely does not cause dropping of database connection.

@Laffreux-dev that is interesting. There should be no queries on fresh instance as the database schema is built from the entities directly. Can you create new issue for that? It is nothing serious though. Are you having some troubles that you want to solve here?

**Comment by saschafoerster** [comment]
@escopecz 

> Where did you guys found that running `php bin/console doctrine:schema:update --force` is the way to upgrade Mautic? I cannot stress this enough:
> 
> **DO NOT RUN THIS COMMAND!!!**
> 
> This is the right command to run migrations and update Mautic:
> 
> `bin/console doctrine:migrations:migrate`

This command is actually what is written in the mautic-documentation. 

Here is the exact line: 
`bin/console doctrine:schema:update --no-interaction --force`
https://github.com/mautic/mautic-documentation/blob/a23fac82c7f0cf49b71420294082a7a5ffb45015/pages/03.Setup/01.how-to-install-mautic/03.Installing%20with%20Composer/docs.en.md?plain=1#L75

https://docs.mautic.org/en/setup/how-to-install-mautic/install-and-manage-mautic-with-composer

```
Follow the steps below to update your core files.

Run composer update mautic/core-lib --with-dependencies to update Mautic Core and its dependencies.
Run git diff in the folder to determine if any of the scaffolding files have changed. Review the files for any changes and restore any customizations to .htaccess or others.
Commit everything all together in a single commit, so the public remains in sync with the core when checking out branches or running git bisect.
In the event that there are non-trivial conflicts in step 2, you may wish to perform these steps on a branch, and use git merge to combine the updated core files with your customized files. This facilitates the use of a three-way merge tool such as [kdiff3](http://www.gitshah.com/2010/12/how-to-setup-kdiff-as-diff-tool-for-git.html). This setup isn't necessary if your changes are simple; keeping all of your modifications at the beginning or end of the file is a good strategy to keep merges easy.
Run the following commands to update your database with any changes from the release:
bin/console cache:clearbin/console mautic:update:apply --finishbin/console doctrine:migration:migrate --no-interactionbin/console doctrine:schema:update --no-interaction --forcebin/console cache:clear
```
I am really happy that Mautic is an open source product we can use and share (and help). But I am really unhappy with the situation about the whole switch to composer-based installations and the bad documentation and the many problems that I had just for a simple thing as an update. It's almost 2 month that mastic was almost unusable for me. It should have been clearly communicated, that the composer way is beta/alpha and only for developers and not your production-ready.

**Comment by J-Wick4** [comment]
Yeah, some better documentation would really help. 

1) Converting to Composer Method
2) Installing fresh with Composer
3) Upgrading with Composer

If we had a one-page doc with all the commands for each of those situations, it would really be helpful.

**Comment by escopecz** [comment]
@saschafoerster thanks for pointing out the docs. I wasn't aware. I'll remove the command from them.

@SpyderZ that would really be amazing. Any chance you could update the docs at least based on trial and error? You may not feel like an expert on this topic but you are far ahead of me for example.

You folks are early adopters and I would like to thank you for it. The goal is to make the experience smoother for people that will go through it later. That's the open source way. There is no team of professional testers. There is no team full of experts on converting a project to be installable via Composer. Just us. You and me must make it better for the rest.

**Comment by Captain-FLAM** [comment]
I confirm that this trouble still persists ...

I updated from 4.20 to 4.4.1 (standard method, not with composer)
I made migrations (one trouble : I had to delete INDEX **dnc_channel_id_search** ON **lead_donotcontact** ??)

I updated manually my db by executing sql queries got from _doctrine:schema:update --dump-sql_

The next steps are impossible (even manually) to resolve : 

 * DROP INDEX IDX_1AE3441319EB6921 ON oauth2_user_client_xref
 * DROP INDEX IDX_6480052EF639F774 ON campaign_leadlist_xref
 * DROP INDEX IDX_3048A8B2F639F774 ON campaign_form_xref
 * DROP INDEX IDX_5995213DF639F774 ON campaign_leads
 * DROP INDEX IDX_2E24F01CA832C1C9 ON email_list_xref
 * DROP INDEX IDX_CA315778A832C1C9 ON email_assets_xref
 * DROP INDEX IDX_9EED7E6655458D ON lead_ips_xref
 * DROP INDEX IDX_F2E51EB655458D ON lead_tags_xref
 * DROP INDEX IDX_F5F47C7CB9FC8874 ON lead_lists_leads
 * DROP INDEX dnc_channel_id_search ON lead_donotcontact
 * DROP INDEX IDX_F4190AB6979B1AD6 ON companies_leads
 * DROP INDEX IDX_473919EFEF1A9D84 ON push_notification_list_xref
 * DROP INDEX IDX_2F81A41DB42D874D ON channel_url_trackables
 * DROP INDEX IDX_6DF94A56C028CEA2 ON point_lead_action_log
 * DROP INDEX IDX_C2A3BDBA71F7E88B ON point_lead_event_log
 * DROP INDEX IDX_B032FC2EBD5C7E60 ON sms_message_list_xref
 * DROP INDEX IDX_A506AFBE2298D193 ON stage_lead_action_log
 * DROP INDEX webhook_id_date ON webhook_queue
 * DROP INDEX IDX_45207A4A4CE1C902 ON monitoring_leads

**Comment by Plato39** [comment]
Still happening.

**Comment by Mourad-Tlili** [comment]
Is there anything new about this topic?
I'm facing the same issue!

**Comment by Plato39** [comment]
I am pleased to see that this is closed. What is the solution please?

**Comment by sdoering** [comment]
Still seeing this error on fresh installs of 5.x. Is there a solution to fix this, @escopecz?

**Comment by FKrafft** [comment]
@sdoering  I can confirm that I also still have this error. 
Starting having it around 4.4 but I continued upgrading, so now I am running a composer based 5.2.1.
