### ISSUE TITLE
Mautic Emails are not Showing Contact Owner as Reply To Option

### ISSUE THREAD

**Issue by ameerasghar** [mautic/mautic#11212]
### Mautic Version

4.2.x series

### PHP version

7.4

### What happened?

Logging bug on behalf of IncentFit: https://github.com/incentfit

We upgraded to the latest version of Mautic a month ago, and most recently also upgraded to the latest update provided by Mautic.

However, whenever we send out emails from Mautic, our recipients see marketing@incentfit.com as the reply to option. 

Our contacts are always set up with a contact owner, and our emails are also always set up to use the owner as the mailer. Despite that, our recipients see our default email address marketing@incentfit.com as the reply to option.

We have already checked our admin settings, to make sure that marketing@incentfit.com does not over-ride the reply to settings.

Please see images below for further clarification, and proof:

Contact Settings & Contact Owner: 
![Contact Owner - Mautic Bug](https://user-images.githubusercontent.com/46496592/171436587-2bf26500-4275-46f6-9da2-9d618f2c35bf.png)

Email Settings - Use Owner as Mailer: 
![Email Settings - Use Owner as Mailer - Mautic Bug](https://user-images.githubusercontent.com/46496592/171436634-eba2db4f-3e99-4468-ae45-7fa62bc1950e.png)

Email Correspondence - marketing@incentfit.com showing up as reply to email address for recipients: 
![Email Correspondence - Mautic Bug](https://user-images.githubusercontent.com/46496592/171436697-cdef2567-6080-47cf-bc3a-fde3102d1063.png)

### How can we reproduce this issue?

Step 1: Set up a new contact, and assign them a contact owner

Step 2: Set up a new email, and use the owner as the mailer

Step 3: Send out the email from step 2, to the contact set up in step 1

Step 4: The recipient of the email will only see your Mautic default email address as the reply to option _(in our case, marketing@incentfit.com)_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the clear documentation, I think it may also be related / the same issue as #11267 which was reported with the API.

It does not show in the screenshots the actual version you are on, please check with the latest version of Mautic (4.3.1)?

What email transport are you using, in case that might be relevant?

**Comment by ameerasghar** [comment]
We are using AWS SNS via SMTP. We are on the latest version of Mautic as well (4.3.1)

**Comment by ameerasghar** [comment]
@RCheesley
