### ISSUE TITLE
Wrong exit from the categories modal dialogue locks out other users from editing

### ISSUE THREAD

**Issue by jvkroeger** [mautic/mautic#11216]
### Mautic Version

4.2.x series

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce

- Edit a category e.g. at `/s/categories/category/edit/2`
- The modal dialogue opens
--> This causes a value in categories.checked_out and categories.checked_out_by

- Click the "x" in the top right corner to close it or just click somewhere besides the Dialog to close it

### Expected behaviour
categories.checked_out and categories.checked_out_by should be set to NULL

### Actual behaviour
categories.checked_out and categories.checked_out_by are not set to NULL
Instead the checkout stays.
This has the consequence that from then on nobody else is allowed to edit the category. The only way preventing this is to use the "Save&Exit" or "Cancel" button.

The following errors appear (no log entries found):
<img width="462" alt="error1" src="https://user-images.githubusercontent.com/58844002/171844668-35722a79-d9f9-4d0d-bbc5-c42268f37aa8.png">

<img width="610" alt="error2" src="https://user-images.githubusercontent.com/58844002/171844677-99f26614-fbc0-431d-adab-e192146c1826.png">

### How can we reproduce this issue?

- Edit a category e.g. at `/s/categories/category/edit/10`
- The modal dialog opens
   --> This causes a value in categories.checked_out and categories.checked_out_by
- Click the "x" in the top right corner to close it or just click somewhere besides the Dialog to close it

<img width="1031" alt="modal_dialogue_categories" src="https://user-images.githubusercontent.com/58844002/171844712-3fbcbd69-93c2-444d-9c6b-6ad9c2cc5b68.png">

### Relevant log output

```shell
/var/log/apache2/acces.log:

"GET /s/categories/category/edit/10?_=1654255321122&mauticUserLastActive=6&mauticLastNotificationId= HTTP/1.1" 200 669 "https:/my.domain/s/categories" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36"
```

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the bug @jvkroeger - is this something that started to happen after an update?
