### ISSUE TITLE
Container extension "web_profiler" is not registered ERROR after cache:clear --env=DEV

### ISSUE THREAD

**Issue by kathrynvillanueva** [mautic/mautic#11214]
### Mautic Version

4.0.x series (not supported)

### PHP version

7.4.19

### What happened?

**php bin/console cache:clear --env=DEV** command fails with message _Container extension "web_profiler" is not registered._

This worked yesterday but suddenly it doesn't today. I tried reinstalling Mautic from github but this keeps happening.

### How can we reproduce this issue?

Step 1: Clone mautic/mautic from github
Step 2: Run composer install
Step 3: Open local mautic in browser and configure settings then login
Step 4: Install plugins
Step 5: Create a basic plugin
Step 6: Run php bin/console cache:clear --env=DEV

### Relevant log output

```shell
$ php bin/console cache:clear --env=DEV

 // Clearing the cache for the DEV environment with debug true


In ContainerBuilder.php line 217:

  Container extension "web_profiler" is not registered.


cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please can you try using the latest version of Mautic rather than 4.0.x? We no longer support that version. If you are still stuck, please ask for support at https://forum.mautic.org/c/support.
