### ISSUE TITLE
Live mode does not contain information about the added record

### ISSUE THREAD

**Issue by TonyBogdanov** [mautic/mautic#11237]
### Mautic Version

4.2.x series

### PHP version

7.4.19

### What happened?

Opening this as a continuation of #10318 which was never properly addressed.

### How can we reproduce this issue?

See #10318.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @TonyBogdanov thanks for raising the issue. Just so I understand you correctly, is this the exact same situation?

- A server which blocks any traffic from outside the USA
- When using live mode entries are coming into the table but they are not showing the IP address until you refresh the page

**Comment by TonyBogdanov** [comment]
Hi @RCheesley,
> A server which blocks any traffic from outside the USA

No, I think that's just a specific situation the user in the original issue has, but the bug, I believe, is unrelated to any firewalling. I don't have any firewalls or traffic filtering and it's still an issue.

> When using live mode entries are coming into the table but they are not showing the IP address until you refresh the page

New entries are not showing *any* content **at all**.\
Looking at the AJAX response, the HTML for the rest of the columns (but the very first one) is missing altogether.

This is how the record looks when added in live mode: https://prnt.sc/5s_LX0F8Bi7Z \
And this is how it looks when you refresh the page: https://prnt.sc/14Sn05KveMXg

Here's the injected HTML returned by the AJAX response:
```html
<tr class="warning">
   <td>
      <div class="input-group input-group-sm">
         <span class="input-group-addon">
         <input type="checkbox" data-target="tbody" data-toggle="selectrow" class="list-checkbox" name="cb217" value="217"/>
         </span>
         <div class="input-group-btn">
            <button type="button" class="btn btn-default btn-sm dropdown-toggle btn-nospin" data-toggle="dropdown">
            <i class="fa fa-angle-down "></i>
            </button>
            <ul class="pull-left page-list-actions dropdown-menu" role="menu">
               <li>
                  <a class="hidden-xs   -sm -nospin" href="/s/contacts/edit/217" data-toggle="ajax"><span><i class="fa fa-pencil-square-o"></i> <span>Edit</span></span></a>
               </li>
               <li>
                  <a href="/s/contacts/view/217" data-toggle="ajax" data-method="POST" class=""><span><i class="fa fa-info-circle"></i> <span>Details</span></span></a>
               </li>
               <li>
                  <a data-toggle="ajaxmodal" data-target="#MauticSharedModal" data-header="Send a custom email to live.user@example.com" href="/s/contacts/email/217?list=1" class=""><span><i class="fa fa-send"></i> <span>Send email</span></span></a>
               </li>
               <li>
                  <a    class=""
                     href="/s/contacts/delete/217"
                     data-toggle="confirmation"
                     data-precheck=""
                     data-message="Delete this contact?"
                     data-confirm-text="Delete"  data-confirm-callback="executeAction" data-cancel-text="Cancel" data-cancel-callback="dismissConfirmation">
                  <span>
                  <i class="fa fa-fw fa-trash-o text-danger"></i>
                  <span>Delete</span></span>
                  </a>
               </li>
            </ul>
         </div>
      </div>
   </td>
</tr>
```

As you can see a table row element is returned with a cell for the checkbox and dropdown column. The rest of the columns however are missing entirely. That's the bug -- it's not related to the IP whatsoever.

**Comment by RCheesley** [comment]
OK thanks for the clarification - as your description just said look at this old issue, I wanted to be sure we understood what issue you are facing specifically so we can try to get to the bottom of it.
