### ISSUE TITLE
Certain scenario causes grapesjs editor manual code edit to break

### ISSUE THREAD

**Issue by uzegonemad** [mautic/mautic#11239]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What happened?

Under a specific scenario, the "save" button inside of the grapesjs code editor stops working. (I'm actually running Mautic 4.3.1 but that isn't available in the dropdown on this issue screen.)

### How can we reproduce this issue?

1. Open the grapesjs builder for any mjml email
2. In the grapesjs editor, press the "Edit Code" button
3. Press the save button (which should work and close the modal)
4. Close out of the email
5. Open the grapesjs builder for any **OTHER** mjml email
6. In the grapesjs editor, press the "Edit Code" button
7. Press the save button (which should no longer work and not close the modal)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Could you specify:
Are you reporting, that after working with the grapesjs builder the Edit Button doesn't open sometimes?
(To be more specific until refreshing the window?)

**Comment by luizeof** [comment]
same here, sometimes the sidebar with buttons appears empty

**Comment by automatyzuj** [comment]
+1

I have had this problem for a very long time. Refreshing the page helps.

It's a bit tiring becouse I often use functions:
- mj-group to non breaking section
- fluid-on-mobile to full width image on mobile
- full-width to full width background section
which aren't available in grapesjs

**Comment by uzegonemad** [comment]
@jos0405 The edit button will load the code editor, but the "save" button within the code editor (bottom of the screenshot) stops functioning.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/430255/174080675-ff57f80c-e416-4a8c-8bab-bdd2c51dd30b.png">

**Comment by RCheesley** [comment]
Hey folks! Please test #11376 which fixes this issue, then we can get it merged into the next release at the end of the month. 

Here's some instructions on how to test a PR in the browser using Gitpod (very quick to do!) https://contribute.mautic.org/contributing-to-mautic/tester#the-easy-way-using-gitpod.

Here is how to leave your review if it has all worked for you: https://contribute.mautic.org/contributing-to-mautic/tester#leaving-your-review.

Thanks in advance! 🚀

**Comment by RCheesley** [comment]
@all-contributors please add @uzegonemad for bugs
