### ISSUE TITLE
Email configuration not working

### ISSUE THREAD

**Issue by ciprianMihalache** [mautic/mautic#1123]
Hello.

We selected in configuration Service to send mail through: mandrill.

Last mail sent my mandril was on 28.10.2015

We cannot see any mail in mandrill app. I guess the emails are not sent using mandrill.

Our account https://originals.mautic.com

PS: Please also update our emails database. I sent the list (using email and chat) one week ago.

**Comment by escopecz** [comment]
Hello, please, contact Allyde to get help with mautic.com service: https://www.allyde.com/contact
