### ISSUE TITLE
Landing Page / E-mail Editor Broken after 4.3.1 upgrade

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#11238]
### Mautic Version

4.2.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

After an edit on a landing page / email, `null` is added in place of the `<html>` tag and before the `<body>` a `null` is also added, causing the editor to break and not load.

![3fc6241a-2de3-49e8-aee9-233d95332c17](https://user-images.githubusercontent.com/257004/172903318-c9795d12-62fe-496a-897f-1be9319bd553.png)

Accessing the database, we can see that `null` values are added after the `<body>`  tag.

![f394ce30-153d-4614-a77e-7dfeec994bc8](https://user-images.githubusercontent.com/257004/172903336-fb622522-b8eb-45ad-a86c-2090ae66eb34.png)

I believe it is related to #11173, #11205 and #10769 .

### How can we reproduce this issue?

- Step 1: Edit an Landing Page / E-mail created at version 3.3.x
- Step 2: Save and Close
- Step 3: Try open editor again

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, this happens if your template first line is not defining `<!DOCTYPE html>` as first line.
If you have this in your template, you should be fine.

**Comment by luizeof** [comment]
Thank's for your time. What should be the first line of the template? for me to update and perform tests here. Thanks in advance .

**Comment by luizeof** [comment]
Thank's for your time. What should be the first line of the template? for me to update and perform tests here. Thanks in advance .

**Comment by AnujaFromUDA** [comment]
Hi,
Please find the issue below:
We are on Mautic 4.4.2 version.
Whenever, I edit the template from the Builder, and send the email - the email breaks on GMAIL. Can you please suggest anything if this has been fixed already
