### ISSUE TITLE
Email for results only sends if you have a "To:" address

### ISSUE THREAD

**Issue by coreyworrell** [mautic/mautic#11269]
### Mautic Version

4.3.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

If you use the form action to send form results and you specify only CC (not To), the emails will not send. Even though the To: field says it is optional (and should be).

### How can we reproduce this issue?

Step 1: Create new form.
Step 2: Create form action to send form results.
Step 3: Set a "CC:" address, leave "To:" empty.
Step 4: Fill out form
Step 5: No email is sent.

Once you set a "To:" address and fill out form, an email is sent.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the issue @coreyworrell - presume as a workaround for the time being you can put something in the to: field while we look into why it is not working as expected.

What email transport are you using?

**Comment by coreyworrell** [comment]
Yes it’s an easy enough workaround. I am using Postmark SMTP.

**Comment by coreyworrell** [comment]
Was this fixed in #11405?
