### ISSUE TITLE
Send Email via API does not use contact owners from and email address [$250 awarded]

### ISSUE THREAD

**Issue by fiveways** [mautic/mautic#11267]
### Mautic Version

4.3.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

when using API to send email to contact, the contact owners details (email, from and reply-to) are not used. The dewfault mail send settings are used instead of contact owner.

confirmed configuration setting for email settings = "Using each contact's owner as email sender" is set to "Yes"

open internal smtp relay used, no overstamping performed by smtp relay.

### How can we reproduce this issue?

Step 1: use api to send email 
Step 2: check received email 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, we are not yet supporting PHP 8 (we are hoping to release a 4.4.0-beta imminently with support) - does this also happen with 7.4?

May also be related to #11212

**Comment by fiveways** [comment]
for some reason the UI does not load on php7.4, however it appears to load and function on php8.0.

when using php7.4 fpm on apache we get (with no logs logged);
The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
System administrators, check server logs for errors.

however this issue is only related to send email via API, I have not been able to verify if this issue is present with php7.4 as well.

this issue is only related to send email via API requests, manual web based email appear to send correctly from the contact owners email address

**Comment by fiveways** [comment]
issues still occurs on v4.4.0 too

**Comment by abcpro1** [comment]
Hello. Can you assign me this issue? I have a fix for it.

**Comment by npracht** [comment]
@abcpro1 this is done ! Looking forward to see what you can do :)

**Comment by abcpro1** [comment]
Thanks.

**Comment by RCheesley** [comment]
Please see #11347 proposed to fix this issue.

**Comment by RCheesley** [comment]
@fiveways please can you review and test #11347 which should resolve this issue. Please leave the review under Files changed > Start review and approve if it does fix this issue.

**Comment by fiveways** [comment]
good job guys, confirmed its working.
