### ISSUE TITLE
Composer install does not populate all files - had to add missing files manually from github after composer install

### ISSUE THREAD

**Issue by TechBill** [mautic/mautic#11286]
### Mautic Version

4.3.x series

### PHP version

7.4.+

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Did a fresh composer install and noticed some broken images. Posted on forum to see what up with broken images and discovered that there is no image files in the /media/images/ folder while github shows there are suppose to be files in that folder.  

This is not my first composer install, I have a production composer install mautic in action and I was just installing a second mautic on another server but the first one was from 4.2.1 which installed without a hitch.  

The 4.3.1 seems not to be populating the image files during composer install so it probably need to be looked into. '

I maintain 3 different servers and all gave me the same result not populating files into the /media/images/ folder. 

Something must had broken between 4.2.1 and 4.3.1

### How can we reproduce this issue?

Step 1: Do a composer install mautic
Step 2: Check to see if any image files populated in /media/images/ folder 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
I think that this PR might be some way to addressing this: https://github.com/mautic/mautic/pull/10682 but it was still WIP. Maybe @mollux might have some insights?

**Comment by TechBill** [comment]
Other person mentioned the same in my post - https://forum.mautic.org/t/broken-gravatar-image/24566/5

**Comment by alexhammerschmied** [comment]
Hi together, 
i just made a fresh Composer Install with Mautic 4.4 and it does not show any images. Not even in the emails. 
Also when I upload an image inside an email it does not render. It gets uploaded to the folder docroot/media/images.

And i found that all files which should actually live inside of docroot/media/images are in the folder docroot/app/assets/images

**Comment by RCheesley** [comment]
Not stale - to be fixed in Mautic 5

**Comment by saschafoerster** [comment]
> Not stale - to be fixed in Mautic 5

Seems not to be fixed in Mautic 5, @RCheesley :) Can the stale-tag be removed?

**Comment by mollux** [comment]
@saschafoerster can you specify what files are missing? As the original issues was for M4, not M5, and I haven't experienced missing files in composer based M5 installs.

**Comment by saschafoerster** [comment]
I had to copy ... /mautic/docroot/app/assets/images to .../mautic/docroot/media/images and then reload and refresh the cache. I am using Mautic 5.0.2, composer based install (which was a regular installation before). I moved the files manually now, which seems to have helped. But I also used this little change, so Gravatars are not used anymore: 
https://github.com/twentyZen/mautic/pull/1/files

**Comment by mollux** [comment]
@saschafoerster I don't get why.
Can you list the broken images or show a screenshot of the network tab in your browser that shows the broken images?

**Comment by saschafoerster** [comment]
This is, where I found the images: 
<img width="520" alt="Bildschirmfoto 2024-02-03 um 14 44 43" src="https://github.com/mautic/mautic/assets/1153741/4e6bc3b2-f43d-44f4-8abc-9a636a564425">
This is, where I put them, to make them work: 
<img width="516" alt="Bildschirmfoto 2024-02-03 um 14 45 09" src="https://github.com/mautic/mautic/assets/1153741/32fef874-5e5a-4b7f-9bff-1b5b5245f6d1">

**Comment by mollux** [comment]
@saschafoerster van you please show it is broken without copying the files? As it seems you think you need to copy them, while since mautic 4.4 there is a difference between assets static files and user uploaded media files.

So please show something is broken without copying them.

**Comment by mollux** [comment]
See https://github.com/mautic/mautic/pull/10682 for context

**Comment by J-Wick4** [comment]
I had this problem too.

**Comment by mollux** [comment]
@J-Wick4 can you show what's broken if you don't copy the files?

**Comment by J-Wick4** [comment]
> @J-Wick4 can you show what's broken if you don't copy the files?

Pretty much what saschafoerster reported. The user avatar was broken until I moved the images around and cleared the cache.

**Comment by RCheesley** [comment]
As far as I know this is now resolved, but if not please let us know and we can re-open the issue.
