### ISSUE TITLE
The search of one TAG with the API return all tags.

### ISSUE THREAD

**Issue by Kixell-NicolasJardillier** [mautic/mautic#11280]
### Mautic Version

4.3.x series

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Hi,
The search of TAG with the API return all tags.
Following this https://developer.mautic.org/#list-tags

### How can we reproduce this issue?

Step 1 : Create several tags in Mautic and one called myTestTag
Step 2 : Use the API to retrieve one Tag in mautic tags = $tagApi->getList('myTestTag');
All tags are returned

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, can you plz share here the search parameters in your call?
