### ISSUE TITLE
Duplicated Dynamic Content token in GrapesJS email builder, Mautic 4.2.x

### ISSUE THREAD

**Issue by annamunk** [mautic/mautic#11291]
### Mautic Version

4.2.x series

### PHP version

7.4.9

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

GrapesJS builer add duplicated Dynamic Content token on each builder close event. Same story to https://github.com/mautic/mautic/pull/10782#issuecomment-1072250155 and https://github.com/mautic/mautic/issues/10240#issuecomment-1087280530

![dc_duplicated](https://user-images.githubusercontent.com/102536220/175995510-838f82b1-4b82-4d35-8fb3-7448bb99ae09.jpg)
![dc_code_duplicated](https://user-images.githubusercontent.com/102536220/175997092-bfafb7f1-63e7-453d-8ef8-2febf1686d60.jpg)

It could be an issue in [grapesjs-preset-mautic](https://github.com/mautic/grapesjs-preset-mautic) in convertDynamicContentComponentsToTokens function. Instead of clearing the content and saving current configuration, the script adds another token to the existing one.

### How can we reproduce this issue?

1. Create or edit MJML e-mail in GrapesJS builder.
2. Add Dynamic Content block.
3. Close builder, save and open builder again (at least 2-3 times).

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by MadlenF** [comment]
We are still experiencing the same behavior in 4.4.0 version. Are there any news on this?

**Comment by RCheesley** [comment]
This has been merged in the preset and will be released as part of 4.4.4 at the end of the month. Thanks for the PR @irfanhanfi 🚀
