### ISSUE TITLE
Feature Request : Add Leadfields variables into simple email editor

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1130]
Hi,

To add the leadfields, you need to do it via the generator.
Or you can copy code into the generator and then integrate it in the standard WYSIWYG editor.

**What would be great is to add a drop down list of leadfields into the standard WYSIWYG editor**. Quick and easy to access when you make standard emails.
You could also add some other variables as unsubscribe link, hosted version link...
__________________
competitor example:
![capture d ecran 2015-11-05 a 13 01 39](https://cloud.githubusercontent.com/assets/14075239/10967810/7352c3bc-83bd-11e5-8b40-e2c6358bb013.png)
__________________
![capture d ecran 2015-11-05 a 13 01 57](https://cloud.githubusercontent.com/assets/14075239/10967809/735128cc-83bd-11e5-8a54-850d75ca5e56.png)

N.

**Comment by dmarkotter** [comment]
Well, you can get a dropdown list in the WYSIWYG editor by typing {le and waiting a few seconds...

But a dropdown list built into the menu would shorten the learning curve.

**Comment by npracht** [comment]
Hi @dmarkotter, i didn't know that tip. Thanks a lot.
I still think it'll b a better user experience.

Thanks for sharing your feedback.

N.

**Comment by dmarkotter** [comment]
You can also type {un to get the unsubscribe links dropdown.

The problem with these is that they are not very intuitive. You need to do a bit of hunting to find them - they're not mentioned in the docs. There's a blog post here:
https://www.mautic.org/blog/tip-of-the-week-insert-fields/

A button as you suggested would make more sense.

**Comment by that0n3guy** [comment]
I would keep the button outside of the wysiwyg editor so it can be used for plain text as well.

**Comment by npracht** [comment]
@that0n3guy good point. Obviously the conclusion is that it should be more visible on any editor.

N.

**Comment by alanhartless** [comment]
We're probably going to hold off on this for now simply because we're considering an alternative to ckeditor and thus spending time to write a ckeditor plugin to do this would be a waste. But marking this as a feature request for when/if we do make the change.

**Comment by that0n3guy** [comment]
A simple alternative might be to have a selector dropdown with a "copy to clipboard" next to it.  Then if you select a field you can easly copy the "code" to clipboard and copy/paste it into the text.  

This really only works if the insertion field is simplified (like if we use twig) and the html is the same as the text shown.

**Comment by npracht** [comment]
I think it's solved by https://github.com/mautic/mautic/pull/1929

**Comment by npracht** [comment]
@alanhartless I think it's solved by #1929

**Comment by alanhartless** [comment]
Fixed in 2.0
