### ISSUE TITLE
Custom emails are marked as open

### ISSUE THREAD

**Issue by automatyzuj** [mautic/mautic#11305]
### Mautic Version

4.3.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

Custom e-mails are always marked as read immediately after send. This problem exist on M4.12 and M4.4, with and without active GrapeJS. I use AWS.
Problem doesn't happen on M3.3

I didn't find this issue on github.

### How can we reproduce this issue?

Step 1: Send custom e-mail from contact.
Step 2: Refresh contact page.

### Relevant log output

```shell
-
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hello @automatyzuj ! Thank you for reporting this bug.
Can you be plz more specific what do you mean by custom email? Is it Segment email or Template email?

**Comment by automatyzuj** [comment]
Hello @jos0405 I wrote about emails sending from client's card. They are marked as "custom email:".

Templete is made in GrapeJS with MJML.

**Comment by automatyzuj** [comment]
I replace this today and... problem doesn't happen!
It weird, becose I tested it on two independent units (different servers, diffrents AWS accounts). Probably this was AWS SES inner temporary problem. Topic to close.

This is how it looks before:
![image](https://user-images.githubusercontent.com/104569506/177297185-2edd87bb-df13-47c2-a702-88eda744a4a0.png)

**Comment by jos0405** [comment]
Closed by request of original submitter
