### ISSUE TITLE
Mautic not connect on Azure AD

### ISSUE THREAD

**Issue by cdorabiatto** [mautic/mautic#11304]
### Mautic Version

4.3.x series

### PHP version

7.4.19

### What browsers are you seeing the problem on?

Chrome

### What happened?

Hello,

We follow this doc link https://docs.mautic.org/en/authentication but after Config Azure AD, the auth works but dont create the user in Mautic.

How configure the SAML on Azure x Mautic?

### How can we reproduce this issue?

https://docs.mautic.org/en/authentication

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, @cdorabiatto , is this a bug or a Azure specific general question?
I would rather ask it in the forums. https://forum.mautic.org/c/support.
Plz close this bug if you agree. Thank you.

**Comment by efrenanora** [comment]
@cdorabiatto hi, i think we may have the same issue., may i know if you already have a resolution for this? thanks
