### ISSUE TITLE
Internal server 500 error on Custom email theme save button

### ISSUE THREAD

**Issue by abdul-Tz-prog** [mautic/mautic#11301]
### Mautic Version

4.2.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Chrome

### What happened?

When I select Custom theme for email template from the list of themes and give it a name and press the save button. It gives me **"POST https://domainName/s/emails/new?mauticUserLastActive=123&mauticLastNotificationId= 500 (Internal Server Error)"**
in the console of Chrome.
I repeat this process same for the mautic instance of version 4.1.1 and it is working. but in version 4.2.1, it is not working.

### How can we reproduce this issue?

Step 1: Create new email template.
Step 2:  Select custom template and save it.

Error will appear in console "POST https://domainName/s/emails/new?mauticUserLastActive=123&mauticLastNotificationId= 500 (Internal Server Error)"

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there,

Please check the logs directory for the actual log files. Maybe there is some issue with the theme.

**Comment by abdul-Tz-prog** [comment]
yes in logs it says "mautic.ERROR: CAMPAIGN: blank-grapejs is missing a required config file [] []"

**Comment by RCheesley** [comment]
There is your issue then - you need to update the config file. Please refer to the documentation where this is explained: https://docs.mautic.org/en/builders#templates

**Comment by abdul-Tz-prog** [comment]
> There is your issue then - you need to update the config file. Please refer to the documentation where this is explained: https://docs.mautic.org/en/builders#templates

I tried to change my config file. But still have this issue. It says: "mautic.ERROR: CAMPAIGN: blank-grapejs is missing a required config file [] []".
