### ISSUE TITLE
Webhook returns different value for new / update contact if boolean

### ISSUE THREAD

**Issue by jos0405** [mautic/mautic#11315]
### Mautic Version

4.3.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Boolean custom field value is returned in different format via webhook in case of update: "1" instead of "true"

### How can we reproduce this issue?

Step 1: Create a Boolean field called "Test bool" (name doesn't matter)
Step 2: Turn on webhook on update and contact identification (alternatively on deletion too)

![image](https://user-images.githubusercontent.com/4246909/177531039-ba12be99-f565-41ad-beb2-1e63cc553233.png)

Step 3: Make a new contact, choose a value for "Test bool" custom field
Step 4: Update the contact
Step 5: Delete contact

You will get 3 events:
mautic.lead_post_delete
mautic.lead_post_save_new
mautic.lead_post_save_update

Notice, that new contact boolean is returned as "true", delete is returned as "false" (I chenged to false, so its correct) and update is returned as "1" instead of "true".

New contact:
![image](https://user-images.githubusercontent.com/4246909/177531634-022ab99b-9b94-49b7-a761-ee8857a01e50.png)

Update:
![image](https://user-images.githubusercontent.com/4246909/177531717-01b10278-be95-4248-944e-bba528d8396e.png)

Delete:
![image](https://user-images.githubusercontent.com/4246909/177531498-96e477bc-601c-40a8-a838-33b728d88ed4.png)

### Relevant log output

```shell
{
  "mautic.lead_post_delete": [
    {
      "id": "26665",
      "contact": {
        "isPublished": true,
        "dateAdded": "2022-07-06T10:19:24+00:00",
        "dateModified": "2022-07-06T10:20:16+00:00",
        "createdBy": null,
        "createdByUser": null,
        "modifiedBy": 1,
        "modifiedByUser": "Joey Keller",
        "id": null,
        "points": 0,
        "color": null,
        "fields": {
          "core": {
            "test_bool": {
              "id": "146",
              "label": "Test bool",
              "alias": "test_bool",
              "type": "boolean",
              "group": "core",
              "object": "lead",
              "is_fixed": "0",
              "properties": "a:2:{s:2:\"no\";s:2:\"No\";s:3:\"yes\";s:3:\"Yes\";}",
              "default_value": null,
              "value": 1,
              "normalizedValue": "Yes"
            },
			
{
  "mautic.lead_post_save_new": [
    {
      "contact": {
        "isPublished": true,
        "dateAdded": "2022-07-06T10:24:02+00:00",
        "dateModified": "2022-07-06T10:24:02+00:00",
        "createdBy": null,
        "createdByUser": null,
        "modifiedBy": 1,
        "modifiedByUser": "Joey Keller",
        "id": 26666,
        "points": 0,
        "color": null,
        "fields": {
          "core": {
            "test_bool": {
              "id": 146,
              "group": "core",
              "label": "Test bool",
              "alias": "test_bool",
              "type": "boolean",
              "properties": {
                "no": "No",
                "yes": "Yes"
              },
              "value": true,
              "normalizedValue": "Yes"
            },
			
{
  "mautic.lead_post_save_update": [
    {
      "contact": {
        "isPublished": true,
        "dateAdded": "2022-07-06T10:24:02+00:00",
        "dateModified": "2022-07-06T10:24:35+00:00",
        "createdBy": null,
        "createdByUser": null,
        "modifiedBy": 1,
        "modifiedByUser": "Joey Keller",
        "id": 26666,
        "points": 0,
        "color": null,
        "fields": {
          "core": {
            "test_bool": {
              "id": "146",
              "label": "Test bool",
              "alias": "test_bool",
              "type": "boolean",
              "group": "core",
              "object": "lead",
              "is_fixed": "0",
              "properties": "a:2:{s:2:\"no\";s:2:\"No\";s:3:\"yes\";s:3:\"Yes\";}",
              "default_value": null,
              "value": false,
              "normalizedValue": "No"
            },
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by ibonkonesa** [comment]
Could you tell me what files are involved ? This repo is terrifing hug :yum: 

I tried to find where webhooks are triggered but I failed

regards

**Comment by mabumusa1** [comment]
Keep it open
