### ISSUE TITLE
Points aren't change after open a "custom email" sending from the lead card

### ISSUE THREAD

**Issue by automatyzuj** [mautic/mautic#11323]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

If you have configured Point Action: "change points" after opens an email without any limit, leads should gain points always after opened any email. But it doesn't work with emails sent from contact card.

### How can we reproduce this issue?

Step 1: Set up New Point Action +points  when a contact Open an Email with any point's value.
Step 2: Send test email from contact card.
Step 3: Open email.
Step 4: Refresh contact card to check.

### Relevant log output

```shell
-
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by automatyzuj** [comment]
I tag: #7330 - may your improvement fix it.

**Comment by kuzmany** [comment]
This is not bug.
Custom emails are not regular emails.
As @automatyzuj wrote above, need new option to Points action.

**Comment by jos0405** [comment]
@automatyzuj  Can we close this for now as it's not a bug but rather a feature request?

**Comment by automatyzuj** [comment]
Hmm... difficult question. IMHO we must remember that we wrote nowhere about this, that point score doesn't work with opens custom emails.

Text in this action is also confusing.
![image](https://user-images.githubusercontent.com/104569506/178464870-7dd7a47a-dfd6-4a19-8713-4ffd78407ed9.png)

**Comment by kuzmany** [comment]
We can add note to tooltip.
But technically custom email is not related to any email ID, then not generate email stats and then not open actions provided

**Comment by automatyzuj** [comment]
In DB and on contact card we see email read history.

We can use custom emails history in segments. For example with condition: "Read any email (date)" - it also is working with custom emails.

For me, this trick on not adding points for custom emails when in other place custom emails are treated the same as others (segments), makes some illogical precedent. But of course it's a question to the PM if it's a bug or a feature reques. From the sales department's perspective, opening custom e-mails is even more important than mass mailings.

**Comment by kuzmany** [comment]
Ok, Then we can let is as bug.
