### ISSUE TITLE
Media Manager gives a 500 error after change to PHP 8.0

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#11328]
### Mautic Version

4.4.x series

### PHP version

8.0.20

### What browsers are you seeing the problem on?

Chrome

### What happened?

After installing 4.4.0 and seeing that it supports PHP 8.0, I told my NGINX server  block to use PHP 8.0 SOCK.
Everything was great until I opened the Media Manager and got a 500 error.
After reverting the NGINX server block back to use PHP 7.4, Media Manager was working again.

### How can we reproduce this issue?

Step 1: Try opening Media Manager while on MAUTIC 4.4.0 and PHP 8.0. - Media Manager doesn't work.
Step 2: Revert back to PHP 7.4 - Media Manager works.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting this - please provide your logs?

**Comment by omert37** [comment]
The problem was IMAGICK.
Installing the php8.0-imagick solved it.:
**sudo apt install php8.0-imagick**

By the way the "Recommendations" tab in System Info told me my "server is configured properly".
Maybe someone should look into that.
I think it would be a very good idea to reiterate somewhere in the official MAUTIC Documentation all the required PHP 8.0 extensions for MAUTIC.
