### ISSUE TITLE
mautic.ERROR: CAMPAIGN: blank-grapejs is missing a required config file [] []

### ISSUE THREAD

**Issue by abdul-Tz-prog** [mautic/mautic#11336]
> There is your issue then - you need to update the config file. Please refer to the documentation where this is explained: https://docs.mautic.org/en/builders#templates

I tried to change my config file. But still have this issue. It says: "mautic.ERROR: CAMPAIGN: blank-grapejs is missing a required config file [] []".

_Originally posted by @abdul-Tz-prog in https://github.com/mautic/mautic/issues/11301#issuecomment-1183220109_

**Comment by jos0405** [comment]
Hi, plz make sure you are using the right folder structure. The config file has to be in the root of your zip. A common mistake is to place the whole template in a subfolder and zip it in.
I'll close this for now. In case you'll still have a problem, feel free to reopen! :)

**Comment by abdul-Tz-prog** [comment]
@jos0405 Thanks for your reply. I already check this. It is not the case folder structure is fine. Please what else could be the solution for this.
