### ISSUE TITLE
Code 500 after save when I use emoji in text with MJML builder

### ISSUE THREAD

**Issue by automatyzuj** [mautic/mautic#11330]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

When I've got some emoji in text (like: 😃 or 📅) and I click "save" or "save and close" Mautic shows me code 500. 

I checked this adn in M4.12 problem was never happened.

Image from M4.12
![image](https://user-images.githubusercontent.com/104569506/178273284-4c9a9084-70c2-4044-a53e-3fb4b5f766a8.png)

### How can we reproduce this issue?

Step 1: Use some MJML template with GrapesJS and paste to text area some emoji like: 📅
Step 2: Click save.

### Relevant log output

```shell
[2022-07-11 14:50:24] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'UPDATE emails SET custom_html = ? WHERE id = ?' with params ["\r\n\r\n\r\n\r\n
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hello @automatyzuj !

I opened an MJML template and tried to reproduce your issue under Mautic 4.4.0.
I had no problem savind emojies:

![image](https://user-images.githubusercontent.com/4246909/178418652-80f2af93-217a-42e0-91be-f43006fd52b0.png)

Looks like this in the DB:

![image](https://user-images.githubusercontent.com/4246909/178418938-65f991e8-8740-41fd-8ee7-680446422543.png)

Is the encoding like this?
![image](https://user-images.githubusercontent.com/4246909/178419048-1d54632a-af10-4e3a-9b91-ecacc03806e5.png)

**Comment by automatyzuj** [comment]
Upgrade to utf8mb4 works. To close.
