### ISSUE TITLE
Missing Lead Fields when creating emails

### ISSUE THREAD

**Issue by ServicedCloud** [mautic/mautic#11344]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

When creating an email and trying to add a personalised content such as first name, there is no way to add one. Tried to type the left curly braces and the tag suggestions aren't showing up. Also, the tag is missing on the text editor. 

![image](https://user-images.githubusercontent.com/18678691/180122576-e646bcce-4cb9-4b2b-9b56-486a1f1b61b2.png)

### How can we reproduce this issue?

Step 1: Create an email
Step 2: Click Builder
Step 3: Type information

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by ServicedCloud** [comment]
Additional info - when GrapesJS is disabled in configuration, the tags are working with the old set of themes. 

I've seen the post [11290](https://github.com/mautic/mautic/issues/11290)  with a similar problem. This will be a duplicate post and happy to close this.

**Comment by RCheesley** [comment]
Thanks for raising this, it's because the editor has not been switched to CKEditor in the builder.

Just write in the tags and they will be used, as a workaround.

**Comment by ServicedCloud** [comment]
Thanks for your reply. 

Can we enable the CKEditor on our installation or is this a new feature that we need to watch out for?

**Comment by RCheesley** [comment]
New feature that needs to be implemented. We did have it working during the pre-beta stage of the builder but there were some bugs iirc which meant it was removed before we launch as I recall @adiux ? I think that is why we lost the auto-token text anyway, can you confirm? Is it something we can re-introduce?

**Comment by ShayLo82** [comment]
@RCheesley @adiux hi there, I am new to using Mautic and GitHub (only landed here because I was scouring the knowledge base and google about this issue) but I am having the same problem - the dynamic content block seems to be missing in MJML email in GrapesJS builder. Do you happen to know if there any current updates for this issue, or if there's a possibility it might be fixed in the Mautic 5.0-alpha release later this year?
