### ISSUE TITLE
Configuration settings don’t save

### ISSUE THREAD

**Issue by HN-PRO** [mautic/mautic#11359]
### Mautic Version

4.4.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Chrome

### What happened?

I successfully upgraded from 3.3.5 to 4.4.0 using the command, but when I save the config file I get 'Please wait....' and it can't save the information properly.

![image](https://user-images.githubusercontent.com/30229591/181407203-09c29635-96e5-4005-a30f-8227a18f11e6.png)

### How can we reproduce this issue?

Step 1: Click Configuration
Step 2: Modify information
Step 3: Save

### Relevant log output

```shell
recv() failed (104: Connection reset by peer) while reading response header from upstream, client: X.X.X.X, server: , request: "POST /s/config/edit?mauticUserLastActive=34&mauticLastNotificationId= HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "demo.demoMautic.com", referrer: "https://demo.demoMautic.com/s/config/edit"
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there! This is most likely something relating to clearing the cache and the browser cache. Please clear your Mautic cache, try incognito etc

Closing this issue, if you continue to experience problems please ask for support on https://forum.mautic.org/c/support as that's where we provide troubleshooting and support 😄
