### ISSUE TITLE
Contact IDs mismatch

### ISSUE THREAD

**Issue by jevhen-ponomarenko** [mautic/mautic#11365]
### Mautic Version

4.4.x series

### PHP version

7.4.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I have created a contact using POST request to `contacts/new`. The response contained `id: 2982961`. 
After some time, I have tried to add this contact to a segment. This action failed with a 500 error.

After inspecting the MySQL logs, I found that the `contact_id` is not in the contacts table. 

Nevertheless, the contact is still accessible with the `id: 2982961` in the browser and using an API. The API response contains another id value (I guess that should be used as the "primary" id on my side?).
```
GET api/contacts/2982961
{'contact': {'isPublished': True,
  'dateAdded': '2022-07-27T17:24:31+00:00',
  'dateModified': '2022-07-27T17:56:15+00:00',
  'createdBy': None,
  'createdByUser': None,
  'modifiedBy': None,
  'modifiedByUser': ' ',
  'id': **2982909**,  # <---- IDs mismatch
  'points': 7,
  'color': None,
.....
```

Questions:
1. Can anyone explain how I can get a different id than what was provided in the URL? 
2. Should I always get fresh contact details from the API to make further requests? 

### How can we reproduce this issue?

I can't really tell, but I expect that the id mismatch issue is caused by the merging of so-called "visitor" users with an identified user.

### Code of Conduct

- [x] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hello,
When you merge 2 contacts together, one is loosing the ID.
It is connected to merging for sure.
Did you add the anonimous user via API as well?

**Comment by jevhen-ponomarenko** [comment]
We only add identified contacts through the API. The visitor user was probably added by the system when he visited the site for the first time?
