### ISSUE TITLE
Can't create new Email

### ISSUE THREAD

**Issue by thaopv** [mautic/mautic#1137]
I created new Role and giant Email permission: View Own, View Other, Create
I assigned an account with this new Role
Then login by this account, Click Email menu item in the Left menu, click New button
And error occurred
This is log's content
mautic.ERROR: Fatal: Call to a member function getId() on null - in file C:\xampp\htdocs\mautic\app\bundles\FormBundle\Entity\FormRepository.php - at line 62 [] []

**Comment by alanhartless** [comment]
https://github.com/mautic/mautic/pull/1148 should fix this and will be part of 1.2.3.
