### ISSUE TITLE
“From Name” field does not show up on the emails received

### ISSUE THREAD

**Issue by lobo8412** [mautic/mautic#11370]
### Mautic Version

4.4.x series

### PHP version

7.4.25

### What browsers are you seeing the problem on?

Chrome

### What happened?

When sending emails Mautic's “From Name” field does not show up on the emails received. Tried different email clients devices. Instead it only shows the “from email” part i.e the address.

The problem occurs when sending with Amazon SES API

### How can we reproduce this issue?

Steps I have tried to fix the problem: I tried sending emails from segments, single contact and also changing the name in the settings.
See Mautic configuration and inbox screens
https://viajandox.com/error-mautic-2.png

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, there was a similar error back around 3.3.0, but it got fixed.
Was it working for you in previous versions?

**Comment by lobo8412** [comment]
yes, it worked fine in versions prior to 3.3.x
I have had this problem with the last updates

**Comment by jos0405** [comment]
Confirming this issue. However adding the name in Advanced tab will work. It's still a bug.

**Comment by jos0405** [comment]
Hi, this is not an issue anymore in 4.4.x I tested and works with SES API.
If it's still an issue for you please reopen.
