### ISSUE TITLE
Email Builder Gone Mad - Ver 4..4.1

### ISSUE THREAD

**Issue by atharv-it** [mautic/mautic#11377]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

Email desing preview in mautic & email actually receiving in the mailbox (Gmail) is showing completly different layout, alignments, image size, etc.

I use beefree.io to desing my emails and then I copy and paste html code in the mautic builder, mautic shows preview perfectly but when it lands to the actual mail (Gmail), it is showing complitly misaligned. Till mautic version 2.5x it was working perfectly.

Even when I spent hours designing email within mautic builder it occured same issue that in preview everything looks good but in gmail it looks unformatted.
 

### How can we reproduce this issue?

Step 1: Visit https://beefree.io/ 
Step 2: Design mail from scratch or take any pre-built layout 
Step 3: Get html code from beefree.io
Step 5: Come to Mautic > Emails > New
Step 6: Go the email builder and paste html code 
Step 7: Check preview on mautic and check email actually received in gmail

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
If you copy in from another builder, use the blank theme and paste your code in the HTML box under the advanced tab.

That way, the GrapesJS builder will not tidy up the code for you.
