### ISSUE TITLE
Email addresses should be lowercased

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#1138]
If a lead submits a form with lower case email address and after that with a capitalize letter in the same email, Mautic saves 2 different leads. 

I suggest to store and compare emails always as lower cased.

**Comment by that0n3guy** [comment]
I'll just say this for what its worth, but I have clients that if they see their email without capitals in the email, they are irritated...

I think mautic should store it how its entered, but just strtolower to compare (or whatever sql command also does that).
