### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by henningandersson** [mautic/mautic#11386]
### Mautic Version

4.2.x series (not supported)

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I have an MariaDb galera cluster with 3 database nodes and a HAProxy in front of the cluster. 

When installing Mautic (docker build), the administrator role doesn't always get the id=1 because of the way identity auto inserts are handled in galera clusters. That makes the installer fail when inserting the initial admin user as it requires the id for the administrator role to be 1.

The problem is because on the galera cluster the identity seed is split over all the nodes in the cluster. IE in a three node cluster: 
- node 1 uses every third identity starting with id 1, 
- node 2 uses every third identity wharting with id 2, and 
- node 3 uses every third identity starting with id 3.
 
And as one is not shure which of the nodes is used for the database deployment, the admin role doesn't always gets the same id.

### How can we reproduce this issue?

Step 1: Install a MariaDb galera cluster with multiple nodes.
Step 2: Install HAProxy in front of the galera cluster
Step 3: Install Mautic

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems or need help with configuration :)

**Comment by henningandersson** [comment]
Sorry, but I am quite shure that this is an bug in the automatic database installation scropts i Mautic, not a user error.

**Comment by henningandersson** [comment]
> Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems or need help with configuration :)

Sorry, but I am quite shure that this is an bug/logic error in the automatic database installation scripts i Mautic, not a configuration/user error.
