### ISSUE TITLE
SpoolTransport.php send doesn't get a new MessageID after sending

### ISSUE THREAD

**Issue by pwned555** [mautic/mautic#11392]
### Mautic Version

5.0.x series

### PHP version

7.3.11

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The SpoolTransport.php send function doesn't re-assign MessageID to a message after sending an email.  The SendmailTransport.php send function and the AbstractSmtpTransport.php send function do correctly do this.

This probably hasn't shown up as an issue because it would rarely matter, but if you are trying to do any testing / sending mail to a user with multiple catch-all or plus forwarding addresses in Outlook what ends up happening is they will only receive one copy of the email in their mailbox.  Yahoo and Gmail do show all copies, but if an email has the same MessageID in Outlook it won't show multiple versions.

The fix for this is very easy, in the SpoolTransport.php send function we just need to add the following to generate a new MessageID for any emails sending after this one like we do in the two send functions mentioned above

Right before the return $count we would call the following
$message->generateId(); //Make sure a new Message ID is used

### How can we reproduce this issue?
This happens when you queue up emails to send in Mautic.
An example of where this comes up would be if you have an account test@testcompany.com.  When you setup plus forwarding for that account and create two signups in Mautic that should trigger an event at the same time for test+2022_08_11@testcompany.com and test+2022_08_10@testcompany.com, Mautic will send both emails but Outlook will only display one.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, thank you for your bugreport. Is it possible that you make a PR for this solution?

**Comment by RCheesley** [comment]
Closing as PR to address is merged.
