### ISSUE TITLE
User Interface - Changing IP lookup service

### ISSUE THREAD

**Issue by alvinbenavides** [mautic/mautic#114]
For the option of changing IP lookup service in Settings > Configuration > Miscellaneous Settings, the drop down menu opens outside the window and services can't be easily selected.

**Comment by alanhartless** [comment]
Hey Alvin,

What device/browser are you using? This is what it looks like for me:

![screenshot](http://cl.ly/image/3j3O2x3a3f3t/Image%202015-03-01%20at%208.07.11%20PM.png)

Can you get me a screenshot of what you're referring to so I visualize what's happening for you?

Thanks!
Alan

**Comment by alvinbenavides** [comment]
Hi. Thanks for the reply.

I'm using Chrome on my desktop. OS is Debian although I just test on a Windows machine (also chrome) and still the same.

![ip_lookup](https://cloud.githubusercontent.com/assets/10437896/6434590/f0e04e94-c059-11e4-9ebf-ebd00b94a485.gif)

Thanks

**Comment by freak3dot** [comment]
I've seen this in Firefox on Window 8.1 and Fedora. The same thing happens in the form editor field select box.

**Comment by alanhartless** [comment]
This is an issue with Chosen the select library we are using. Looks like it's been complained about for years and still nothing "official" in the repo. (See https://github.com/harvesthq/chosen/issues/155). We may be able to apply some of the hacks listed in that issue as in interim solution.

**Comment by alvinbenavides** [comment]
If its too difficult I guess you could also move the field to the first row in Miscellaneous Settings and avoid using them at the bottom... just a thought.

**Comment by pbwebdev** [comment]
I find this is a similar issue in Joomla when messing around with menu items layout options
