### ISSUE TITLE
Email Builder Removes Colon from: xmlns:o

### ISSUE THREAD

**Issue by edmadcap** [mautic/mautic#11408]
### Mautic Version

4.4.x series

### PHP version

7.4.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After the first save, Email Builder removes the colon from xmlns attributes, such as: xmlns:o

### How can we reproduce this issue?

Step 1: Create a new email
Step 2: Choose the "Code Mode" theme
Step 2: On the Builder screen, paste in your html (which includes "xmlns:o")
Step 3: Click the "Save" button. 
Step 4: "xmlns:o" is now changed to "xmlnso" (no colon). The result is that any email sections using VML will have display issues in Outlook. Other xmlns declarations in the html tag also get their colon removed.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by edmadcap** [comment]
I found the fix: On vendor\joomla\filter\src\InputFilter.php in the cleanAttributes method, update the regex here to allow colons.
`			// Remove all symbols
			$attrSubSet[0] = preg_replace('/[^\p{L}\p{N}\-\s]/u', '', $attrSubSet[0]);`

**Comment by mabumusa1** [comment]
Keep opened
