### ISSUE TITLE
Feature Request - Detail of campaign actions shown in lead's event log

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#1141]
Showing the detail of the a campaign's action/s in the lead's event log would save time, especially when a deployment gets large and complex.

In the screenshot you see that there was a campaign action executed, but without going into that campaign, you can't know what action was actually carried out on that lead.

This would become a problem with scale because if the lead is part of multiple lists that are called upon by multiple campaigns etc..it would become very hard to see what campaign they're engaging with and what actions are being taken on that lead.
![campaign 20action 20detail](https://cloud.githubusercontent.com/assets/10385295/11013102/71a91622-8554-11e5-9f02-eacc5e9e715b.PNG)

**Comment by alanhartless** [comment]
Adding a description to the campaign decision/action should cause it to show up in those boxes making it easier to differentiate. Would that work for your needs?

**Comment by zstephen** [comment]
That would work well thanks

**Comment by escopecz** [comment]
Might be implemented in https://github.com/mautic/mautic/pull/2074
