### ISSUE TITLE
401 with API

### ISSUE THREAD

**Issue by jensenhertz** [mautic/mautic#11421]
### Mautic Version

4.4.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I'm getting 401 when I try to do any API calls.

I tried to rm -rf `var/cache` (as instructed in #9872) but I'm still getting 401 when trying to access the API. No HTTP Basic popup triggered when I access something like /api/contacts?limit=1&minimal=1. Both API and HTTP Basic are enabled.

Any ideas?

### How can we reproduce this issue?

Step 1: Turn on API & Basic Auth
Step 2: Try to access something like `/api/contacts?limit=1&minimal=1`

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, you should not get a popup, it's a server to server communication.
