### ISSUE TITLE
[Feature request] Use titles on admin pages

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#1142]
When I am working with Mautic and I need to go back to previous pages, everything in my history uses a title of 'Mautic'.  It would be far more helpful if it was something like 'Mautic - Forms - Sitename', 'Mautic - Landing Pages - Sitename'.

**Comment by ldrrp** [comment]
+1

Maybe also add the ID or Name of each email/lists etc so when im switching tabs editing many things at once i can see things.

**Comment by jordan8037310** [comment]
+1

**Comment by jordan8037310** [comment]
I played around with this a bit and will likely work on it in the upcoming month.
