### ISSUE TITLE
fatal error on fresh install from git

### ISSUE THREAD

**Issue by mhd-jalilvand** [mautic/mautic#11428]
### Mautic Version

5.0.x series

### PHP version

7.4.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

There is a fatal error on step 3
im using debian 11
php-fpm 7.4.30
composer2
nginx

### How can we reproduce this issue?

Step 1: fresh install after set username password there is fatal error 500 un handled exception on step email setup

### Relevant log output

```shell
mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Neither the property "mailer_sparkpost_region" nor one of the methods "getMailerSparkpostRegion()", "mailerSparkpostRegion()", "isMailerSparkpostRegion()", "hasMailerSparkpostRegion()", "__get()" exist and have public access in class "Mautic\InstallBundle\Configurator\Step\EmailStep"." at [path/to]/mautic/vendor/symfony/property-access/PropertyAccessor.php line 446 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Neither the property \"mailer_sparkpost_region\" nor one of the methods \"getMailerSparkpostRegion()\", \"mailerSparkpostRegion()\", \"isMailerSparkpostRegion()\", \"hasMailerSparkpostRegion()\", \"__get()\" exist and have public access in class \"Mautic\\InstallBundle\\Configurator\\Step\\EmailStep\". at [path/to]/mautic/vendor/symfony/property-access/PropertyAccessor.php:446)"}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
