### ISSUE TITLE
Reply to address is not the same as send address when using mailer is owner

### ISSUE THREAD

**Issue by toondeg** [mautic/mautic#11423]
### Mautic Version

4.3.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What happened?

When setting the “Mailer is owner” setting to “**Yes**” in either the campaign settings or the general Email settings, the From email address and name is indeed taken from the owner of the contact, but **the reply address is not updated** accordingly. 

This remains the original “Reply to address” or the “E-mail address to send mail from” if the first one is empty.

### How can we reproduce this issue?

Step 1: mailer is owner yes
Step 2: leave reply to empty in config
Step 3: create segment email and use mailer is owner
Step 4: send email

Email will have the from adress that is in the config as the reply to address.

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Does this persist in 4.4.1?

**Comment by RCheesley** [comment]
This PR https://github.com/mautic/mautic/pull/11322 fixed it.

Closing as resolved, feel free to request a reopen if it's different to that issue.

**Comment by LordRembo** [comment]
@RCheesley I'm not sure why this issue is closed. The fix is for 5.x but this report was for 4.3

**Comment by RCheesley** [comment]
@LordRembo then we need a backported PR if it is to be released in the 4.4.x series as well - please feel free to make that PR and we can get it reviewed and merged if you need it in the 4.4.x releases. Thanks!

**Comment by LordRembo** [comment]
Looking into this issue again, tested with Mautic 4.4.x
There was a backport of the supposed 5.x fix (addition of `$this->setReplyTo($owner['email']);`), but unfortunately this does not actually fix the problem.
So the initial issue remains present.
@RCheesley is it okay to reopen this ticket, as the original scope was not solved? It's great that 5.x works but this ticket was for 4.x series.

**Comment by LordRembo** [comment]
Ah, never mind @RCheesley. Seems there is an entirely other error at the basis of what's going on in my 4.4.x example. I'll make a new ticket if relevant.

**Comment by RCheesley** [comment]
@LordRembo I've re-opened but shout if you need me to close it again!

**Comment by LordRembo** [comment]
@RCheesley it's safe to close after all. Sorry for the confusion!

**Comment by dsp76** [comment]
@LordRembo if I understand you correctly, you asked for this to be closed? So I close it. If I misunderstood, please let me know.
