### ISSUE TITLE
Segment with URL visited and regexp don't filter

### ISSUE THREAD

**Issue by claracousin1** [mautic/mautic#11427]
### Mautic Version

4.4.x series

### PHP version

7.4.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I make a segment with a filter. I use "URL visited" as field with "regexp" as filter. 
I want to know where the different contacts come from. But, where I do my different segments, with different text based on my different url, I have always the same number of contacts.
I check my regex, and I think it's ok. I just put a text. 
Moreover, I also checked, and I have contacts who don't visit all url. 

Do you any idea?

### How can we reproduce this issue?

1. Create a segment
2. Choose like filter : "email not empty" AND "URL visited regexp _one url of your site_"
3. Save and close
4. Create a other segment 
5. Choose like filter : "email not empty" AND "URL visited regexp _other url of your site_"
6. Save and close
7. Compare the number of contacts

### Relevant log output

```shell
No log
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by PierreAmmeloot** [comment]
Hello @RCheesley,

I have check this issue and for me it's a bug on Mautic 4.x.
If you create two segments with diffrent "visited url" and "regexp" filter you have the same result.

Can you reopen this bug please?

Pierre
P.S.: you can see this response from @jos0405 on forum => https://forum.mautic.org/t/segment-with-url-visited-and-regexp-dont-filter/25300/3?u=pierre_a

**Comment by claracousin1** [comment]
@RCheesley 
I have just noticed a new anomaly concerning the regexp filter. 
I have the same problem on domain name and primary company. 
On the other hand on LastName the regexp filter works. 

**Can you reopen this issue please?**

**Comment by RCheesley** [comment]
Your wish is my command 🧙‍♀️ 🪄 ✨

**Comment by claracousin1** [comment]
Thanks 🙏🏼

**Comment by npracht** [comment]
Hi @claracousin1 can you please test https://github.com/mautic/mautic/pull/11541 ?

**Comment by claracousin1** [comment]
Hi @npracht, it's work ! ✨
Thank you :)
