### ISSUE TITLE
[Feature request] Integrate with Sage

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#1144]
Quite a lot of customers use Sage for their CRM, accounts, etc.  It would be very handy to integrate with it.

A restful interface is available I believe via http://sage.github.io/SData-2.0/

**Comment by npracht** [comment]
:+1: very agree

**Comment by RCheesley** [comment]
We now have a client using Sage Accounts, Manufacturing and potentially considering CRM if it would interact with Mautic - any ideas if this is on the table at the moment or if anybody is working on it?
