### ISSUE TITLE
Segment filter "URL from landingpage" does not work anymore [Mautic 4.4.1]

### ISSUE THREAD

**Issue by MaraKasubke** [mautic/mautic#11459]
### Mautic Version

4.4.x series

### PHP version

7.4.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The segment filter "URL from landingpage" does not filter contacts anymore that come from a mautic landingpage. 

We are not using the landingpage feature at the moment, so it is not that big of a deal for us. But I wanted to document it here.

### How can we reproduce this issue?

Step 1: Create segment
Step 2: Configure filter "URL from landingpage" equals "YES".
Step 3: Wait for segment to build

You can see in the screenshot, that after we updated our Mautic in August, Mautic put all our contacts in that segment since the filter is not working anymore. - We did not change anything in August.
<img width="1006" alt="2022-09-09_10h41_34" src="https://user-images.githubusercontent.com/34441995/189311417-cb479dbc-6844-434c-82c0-7f18a3cf4fba.png">

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, it does work under 4.4.3.
![image](https://user-images.githubusercontent.com/4246909/194818944-b95c7ba2-463d-45ca-959a-828a0393c92d.png)

![image](https://user-images.githubusercontent.com/4246909/194818957-3e329b84-8deb-4009-a14d-4047de72d989.png)

I will close this for now. If you experience it under 4.4.3 please feel free to reopen.
