### ISSUE TITLE
Feature Request - Forms provide checkboxes for self service list removal/addition

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#1145]
Can form fields allow a used to toggle their membership on a particular list?

If they wanted to be on some lists but not others, this would allow us to give them more control over their list membership, consumers like control and it reduces they change that they just say "damn it, unsubscribe me from everything".

It's a bit cumbersome having to do a list change action per form, that means that several forms are needed if there are multiple lists, this is also frustrating for the consumer, and again, they are more likely to unsubscribe from all.

**Comment by alanhartless** [comment]
Right now, afraid not.  But there is an existing request for this #822 so marking this as a duplicate.
