### ISSUE TITLE
Forms are pre-populating with data of other users

### ISSUE THREAD

**Issue by simon-fernandes** [mautic/mautic#11463]
### Mautic Version

3.3.x series (not supported)

### PHP version

7.4.30

### What browsers are you seeing the problem on?

Chrome

### What happened?

Hi, we're running Mautic 3.3.4 (not upgraded yet - it's in the pipeline) and our client has reported to us that sometimes when they visit a webpage on their own website with an embedded Mautic form in it, the forms are being pre-populated with the user data of someone completely different. The form is being added with the automatic method.

This is difficult to debug as it doesn't happen for us - but they have sent us screenshots of this happening and we have no idea why.

Was this a known issue fixed in a version later than 3.3.4?

### How can we reproduce this issue?

Step 1: Hard to say - visiting a webpage shows the data on the form.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, 3.3.4 is not supported anymore.
I have not seen this error in M4.
