### ISSUE TITLE
Landings pages and emails created via the fixtures are broken

### ISSUE THREAD

**Issue by nick-vanpraet** [mautic/mautic#11471]
### Mautic Version

4.3.x series

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Not relevant

### What happened?

In the Doctrine fixtures, 2 emails and 1 landingspage is created. Unfortunately, their data still relies on the old builder. Possibly very old builder, as even disabling GrapesJS does not fix this.

When editing these pages or emails, clicking "build" brings up the old builder UI but it is entirely broken. The console is full of errors.

I suggest updating the csv files to create this content using the new structure.

### How can we reproduce this issue?

Step 1: Install Mautic
Step 2: Run `bin/console doctrine:fixtures:load`
Step 3: Attempt to launch the builder for any of the created emails or page

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mabumusa1** [comment]
Keep it open

**Comment by PierreAmmeloot** [comment]
I have the same problem on my side.
