### ISSUE TITLE
Your bug title goes here!

### ISSUE THREAD

**Issue by karanpal-dhillon** [mautic/mautic#11473]
### Mautic Version

4.4.x series

### PHP version

PHP 7.4.13

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

Email link clicks are not getting tracked.

1 **Your Mautic server is on a public URL. Tracking doesn't work on a localhost.** - Mautic server is on a public URL
2. **Make sure the email was sent to an existing contact via a campaign or a segment email.**  Email was via a campaign, to an existing contact.
3. **Make sure the URL in the href attribute is absolute and valid. It should start with http:// or https://.** href attribute is absolute.
4 .**You've opened the link in a incognito browser.**. Yes. 
5. **Check if the link in the email has been replaced by Mautic's tracking link.**. No. link hasn't been replaced. 

### How can we reproduce this issue?

Step 1: Send an email via campaign. 
Step 2. Check to see if links has been replaced by Mautic's tracking link

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Are you hosting your Mautic on localhost?

**Comment by jos0405** [comment]
Hi, you need to visit pages with a browser, where you don't have the admin cookie. I suspect this is not the case here. I'll close this for now, plz feel free to reopen if you think I'm wrong. Thx.
