### ISSUE TITLE
Page TrackableModel raises warning on invalid URL

### ISSUE THREAD

**Issue by galvani** [mautic/mautic#11488]
### Mautic Version

4.4.x series

### PHP version

7.4

### What happened?

If invalid URL is received parse_url will return **false** but the next test does not take it into account.

https://github.com/mautic/mautic/blob/16e2203ee45b88138d836faa78a87fc60cf20276/app/bundles/PageBundle/Model/TrackableModel.php#L442-L447

this causes array calls to boolean object.

### How can we reproduce this issue?

Step 1: I am not sure how to put there wrong URL but it does happen in production. Code is self explanatory.

### Relevant log output

```shell
PHP Notice:  Trying to access array offset on value of type bool in /var/www/XXXXXX/app/bundles/PageBundle/Model/TrackableModel.php on line 463
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by galvani** [comment]
I offer solution here: https://github.com/mautic/mautic/pull/11486

**Comment by RCheesley** [comment]
Thanks for making the PR @galvani ! 🚀
