### ISSUE TITLE
Improve mautic server load

### ISSUE THREAD

**Issue by ciprianMihalache** [mautic/mautic#1151]
Mautic server is very slow. 

We use forms and sometimes it takes ~30 seconds for form to display.

Please try to improve server speed or make some cloud package prices for users.

**Comment by that0n3guy** [comment]
Are you talking about mautic.com's services?

**Comment by ciprianMihalache** [comment]
yes

**Comment by alanhartless** [comment]
@ciprianMihalache Mautic.com is a service provided by Allyde.  Check out https://status.allyde.com/.

Thanks!
Alan
