### ISSUE TITLE
Not possible to create a report using the datasrouce segment activity log and certain columns

### ISSUE THREAD

**Issue by toondeg** [mautic/mautic#11516]
### Mautic Version

4.3.x series

### PHP version

7.4.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

**What are we trying to create**
As it is important for European based companies to follow the GDPR law we are trying to create an overview to see when a contact was added to a segment and when the contact was removed. (ex: newletters)

When trying to create a report using _Segment activity log_ as a datasource,  _Data added to segment_ as a column and _date removed from segment_ as a column Mautic responds a 500 internal server error.

I've tried multiple setups, but the same error keeps occurring:

- email and date added to segment
- email and date removed from segment
- id and date added to segment
- id and date removed from segment
- all the above combined

### How can we reproduce this issue?

Step 1: create new report
Step 2: select segment activity log as datasource
Step 3: add fields mentionned above

### Relevant log output

```shell
mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT count(*) FROM (SELECT `log_added`.`date_added` AS date_added, `log_removed`.`date_added` AS date_added1 FROM leads l LEFT JOIN lead_event_log log_added ON l.id = log_added.lead_id  AND log_added.bundle = 'lead' AND log_added.object = 'segment'  AND log_added.`action` ='added' AND log_added.date_added BETWEEN ? AND ? LEFT JOIN lead_event_log log_removed ON l.id = log_removed.lead_id  AND log_removed.bundle = 'lead' AND log_removed.object = 'segment'  AND log_removed.`action` ='removed' AND log_removed.date_added BETWEEN ? AND ? AND log_removed.object_id = log_added.object_id  WHERE (log_added.date_added IS NOT NULL) OR (log_removed.date_added IS NOT NULL) GROUP BY l.id,log_added.object_id)
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by LordRembo** [comment]
This issue wasn't fixed, as the proposed PR #1645 was rejected and related ticket #3969 also has no solution provided

**Comment by LordRembo** [comment]
We're still running into this issue on Mautic 4.4.10. The fix for related ticket #3969 does not seem to resolve the issue, as someone else also mentioned in the comments over there.
@RCheesley or @escopecz : could this ticket be reopened?

**Comment by RCheesley** [comment]
@mollux do you know if the team are still experiencing this issue?

**Comment by LordRembo** [comment]
I just tried in a recently updated Mautic 4, and it seems to work now.
Similarly, for Mautic 5.x it's also working.

**Comment by LordRembo** [comment]
@RCheesley so it should be safe to close
