### ISSUE TITLE
Displaying of points

### ISSUE THREAD

**Issue by claracousin1** [mautic/mautic#11522]
### Mautic Version

4.4.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I go to the contact page, if the number of points is greater than 0, the display looks like this: "%points% points".
There is no log, I try to clear cache, and no change.

**Is it the same for you?** 

### How can we reproduce this issue?

1. Go to page contact where the points are greather than 0

### Relevant log output

```shell
No log
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, this seems to happen because the EN translation of the string %points% has changed. If you change the US, it will work.

**Comment by claracousin1** [comment]
Hi @jos0405,
Thank for your answer ! Indeed, in English Us the bug is not present, unlike in French. 
We'll look into fixing the bug !

**Comment by fbugalla** [comment]
HI, it seems in spanish also the string is wrong. Thx

**Comment by MaraKasubke** [comment]
For the German language I see the same bug.

**Comment by jos0405** [comment]
Hi, this is still outstanding, but I think it can be solved via Transiflex.

The string for this field is stored in:
/var/www/html/mautic/restore/var/www/html/mautic/app/bundles/LeadBundle/Translations/en_US/messages.ini
line 540:
`mautic.lead.points.count="{0}0 points|{1}1 point|]1,Inf[%count% points|{-1}-1 point|]-Inf,-1[%count% points"`

In GB version we have:

{0}0 points|{1}1 point|]1,Inf[%points% points|{-1}-1 point|]-Inf,-1[%points% points

%points% was changed to %count% - this is why it's only working in the en_US version.

Plz fix the Leadbundle in your language to mirror the changes in the en_US version.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/12500. The language packages should be rebuilt tonight.

**Comment by claracousin1** [comment]
Thank you @escopecz !

**Comment by jos0405** [comment]
Closing it favor of https://github.com/mautic/mautic/pull/12499
