### ISSUE TITLE
Feature Request : Reference Field values inside Campaign Action 

### ISSUE THREAD

**Issue by malcolmgroves** [mautic/mautic#1152]
I'd like to be able to reference a value from the User's form inside one of the Campaign actions, and have that value resolved at runtime. 

As background, I want to have the same form on multiple different product pages, the only difference is a hidden field that identifies the product name. In the campaign that sits behind that form, I currently would need to have dozens of "Form Field Value" condition\"Modify Lead's Lists" action pairs, one for each product name. It's like a huge if..then..else statement. 

It would be much easier to maintain and clearer to understand if I could simply have one "Modify Lead's Lists" action with a reference to the hidden field in it, say %ProductName% (don't care about the syntax) and have that resolved down to the field value at runtime. 

Here's the community discussion with more background https://www.mautic.org/community/index.php/1112-add-lead-to-list-that-matches-value-in-hidden-form-field

**Comment by alanhartless** [comment]
I'm not sure I'm following the work flow here or able to picture what's desired. You still have to associate the form field's value with the lead list somewhere.  

So if I have form field of ProductName with submissions that has values of ProductA, ProductB, ProductC, and ProductD and I want them to be associated with lead lists ListA, ListB, ListC, and ListD respectively.  What does the alternative to the "huge if..then..else statement" look like?  If using a reference to the hidden field, how are you picturing the UI to tell Mautic that you want a value of ProductA to go to ListA, ProductB to go to ListB and so forth?

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to comment on this issue any time and I will re-open it again.
