### ISSUE TITLE
If Else statement : {formfield}

### ISSUE THREAD

**Issue by l2aelba** [mautic/mautic#1153]
Example , My form with those fields but the **"Phone" field is not required**
```
email: {formfield=email}
phone: {formfield=phone}
````

**Question is :**
How to hide phone: `{formfield=phone}` when users doesnt submited their "Phone" field ?

or any docs about this ?

Thanks

**Comment by l2aelba** [comment]
#849

**Comment by alanhartless** [comment]
Yea, closing this in favor of #849 as a twig email would support this.
