### ISSUE TITLE
Cloning email results in insertion of <p>

### ISSUE THREAD

**Issue by ehillerbrand** [mautic/mautic#1155]
When repeatedly cloning email template <p></p> are entered

**Comment by npracht** [comment]
You may talk about that ? [#1081](https://github.com/mautic/mautic/issues/1081)
You're issue is really poor in terms of explanation, if you could be a bit more expressing your need in details, it would be easier to help :)

N.

**Comment by alanhartless** [comment]
Due to lack of feedback, closing this.  If you can explain a bit more what is happening, we'll reopen and help debug.
