### ISSUE TITLE
PHP Parse Error after clearing cache

### ISSUE THREAD

**Issue by jmdunsing** [mautic/mautic#11562]
### Mautic Version

4.4.x series

### PHP version

7.4.32

### What browsers are you seeing the problem on?

Chrome

### What happened?

Here is what I was doing:

I was adding a template for emails. Realized that the GrapesJS builder was active, but wanted a legacy template, so I disabled GrapesJS builder. Per https://docs.mautic.org/en/builders, to revert to the old builder it recommends to clear the cache and reload the page. I cleared the cache by remote access via winSCP, navigated to <mautic_path>/var/cache and deleted the contents. Upon refresh I have get a site offline page. I have tried rebooting the server, and running multiple php commands (e.g. mautic:update:find) but they all return the same error: 

PHP Parse error:  syntax error, unexpected 'app' (T_STRING) in /var/www/html/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/PostalTransport.php on line 193

In case it helps, here is some additional system information:
Mautic 4.4.1
Ubuntu 20.04
Apache 2.4.41
mysql  Ver 15.1 Distrib 10.5.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### How can we reproduce this issue?

Unfortunately, I don't know if this will be reproducible on other machines/setups

### Relevant log output

```shell
[Sat Oct 08 12:58:14.806445 2022] [php7:notice] [pid 70112] [client <ip_address>] PHP Notice - Undefined variable: inline - in file /var/www/html/mautic/offline.php - at line 77
[Sat Oct 08 12:58:14.806486 2022] [php7:notice] [pid 70112] [client <ip_address>] PHP Notice:  Undefined variable: inline in /var/www/html/mautic/offline.php on line 77
[Sat Oct 08 12:58:14.806497 2022] [php7:notice] [pid 70112] [client <ip_address>] ParseError: syntax error, unexpected 'app' (T_STRING) - in file /var/www/html/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/PostalTransport.php - at line 193
[Sat Oct 08 12:58:14.839264 2022] [php7:notice] [pid 70109] [client <ip_address>] PHP Notice - Undefined variable: inline - in file /var/www/html/mautic/offline.php - at line 77
[Sat Oct 08 12:58:14.839313 2022] [php7:notice] [pid 70109] [client <ip_address>] PHP Notice:  Undefined variable: inline in /var/www/html/mautic/offline.php on line 77
[Sat Oct 08 12:58:14.839327 2022] [php7:notice] [pid 70109] [client <ip_address>] ParseError: syntax error, unexpected 'app' (T_STRING) - in file /var/www/html/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/PostalTransport.php - at line 193
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jmdunsing** [comment]
I seem to have resolved the problem by creating a dev installation, copying the cache and replacing. Note to self, make back-ups of the cache before you delete. :D However, The statement in the templates webpage (https://docs.mautic.org/en/builders) should be updated to prevent users from experiencing the problem in the future or a bug is still present. I would still think the software should be able to rebuild the cache.

**Comment by RCheesley** [comment]
@jmdunsing good to hear you resolved this, please post on https://forum.mautic.org/c/support in the future, as that's where we provide troubleshooting and support. It sounds like there may be a permissions issue with your cache folder - if you make a post on the forums I am sure that someone will be able to help you get to the bottom of it.
