### ISSUE TITLE
Goto Webinar Join-Links are getting mixed up if URLs are trackable

### ISSUE THREAD

**Issue by dkoschig** [mautic/mautic#11569]
### Mautic Version

4.3.x series

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Not relevant

### What happened?

We have setup a Campaign connected to a Segment with Contacts that we want to register to GotoWebinar and send them the correct Join-Links for that event. We have multiple Actions in the Event, like 'Register to GotoWebinar', and additional 'send Email'-Actions as Reminders to be sent at various Points in time to the Contacts.
We found that the Contacts receive Emails with Join-Links that do not belong to the specific User/Email-Address, but to another User instead. So User A will receive the Join-Link for User B for example, which is bad in two ways:
User impersonate other Users on the actual GotoWebinar-Event
User-Participation-Tracking is messed up, we can not say which Users attended the Event and which did not.
This behaviour only occurs if there exists more than one User during Campaign-Trigger Step (mautic/bin/console mautic:campaigns:trigger) and only if Option 'Disable trackable Urls' is set to false. If trackable Urls are disabled, the Join-Links appear to be always correct.

### How can we reproduce this issue?

Step 1: Configure Mautic to connect with GotoWebinar using the default Plugin that Mautic provides
Step 2: Setup a Webinar in GotoWebinar, register with some Email to this Webinar
Step 3: Execute Citrix Sync Script: sudo -u www-data /usr/bin/php /var/www/mautic/bin/console mautic:citrix:sync, this will import the Webinars to Mautic-DB Table: plugin_citrix_events
Step 4: Set Config-Option 'Disable trackable urls' to 'false' in Mautic Email-Settings
Step 5: Setup a Segment with some Filters, e.g. Contacts need to have some specific Tag
Step 6: Setup a Email with HTML using the webinar_link placeholder, e.g. <a href="{webinar_link}">Webinar</a>
Step 7: Setup a Campaign with following Actions: Register to GotoWebinar (using Webinar from Step 2), and a couple additional Send-Email-Events using the Email-Template created in Step 6. Connect the Campaign to the Segment created in Step 5.
Step 8: Create some Contacts in Mautic that meet the Filter-Criteria for the Segment created in Step 5, make sure you have Access to the Email-Addresses of those Contacts. Create a reasonable amount, like 5-8 Contacts.
Step 9: Execute the following Scripts in this order: 
sudo -u www-data /usr/bin/php /var/www/mautic/bin/console mautic:segments:update
sudo -u www-data php /var/www/mautic/bin/console mautic:campaigns:rebuild
sudo -u www-data /usr/bin/php /var/www/mautic/bin/console mautic:campaigns:trigger
sudo -u www-data php /var/www/mautic/bin/console mautic:emails:send -vvv
Step 10: Investigate the Join-Links that were sent. Because we enabled trackable URLs in Step 4, they will point to Mautic before redirecting to the Join-Link from GotoWebinar. Use Network-Tab in Browser to see the Join-URLs to which redirects happen. Compare the Join-Links that were used in those Emails with the Join-Links stored in GotoWebinar or with the plugin_citrix_events.event_desc Table/Column, you will see that the Join-Links used in the actual Mails sent might differ from the Join-Links that are associated with the Email in plugin_citrix_events.event_desc. This Error does not occur if Config-Option 'Disable trackable urls' is set to true.

### Relevant log output

```shell
// Relevant tables
plugin_citrix_events, page_redirects
// Relevant Classes/Functions
app/bundles/EmailBundle/EventListener/BuilderSubscriber.php -> convertUrlsToTokens(), parseContentForUrls()
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting this bug @dkoschig - seems like quite a complex one to test - @oltmanns-leuchtfeuer could your team take a look at this please as I know you use GoTo products at Leuchtfeuer?

**Comment by dkoschig** [comment]
Hint:
Our Company added a small workaround for this issue in our Mautic-Code:
app/bundles/EmailBundle/EventListener/BuilderSubscriber.php
Function convertUrlsToTokens

```
 // CUSTOM CHANGE START
   // We disable trackable Urls for GoToWebinar Emails because this will send incorrect Join-Links to the Users
   if (array_key_exists('{webinar_link}', $event->getTokens())) {
     // Don't convert urls
     return;
   }
// CUSTOM CHANGE END
```

Unfortunately it turned out that `array_key_exists('{webinar_link}', $event->getTokens())` is always true, even for Emails that are not related to Webinar-Mails/GotoWebinar.

Maybe this info somehow helps in resolving the issue

**Comment by nick-vanpraet** [comment]
Just for SEO and future debuggers. If your plugin creates new tokens that people can use in emails, but those tokens' values are going to be unique per user your plugin needs to tell Mautic not to "trackify" them.

Luckily you can do that without patching, as an Event is fired. Subscribe to the `PageEvents::REDIRECT_DO_NOT_TRACK` event and in the function, you'll receive UntrackableUrlsEvent. Call UntrackableUrlsEvent::addNonTrackable for each of your tokens and you're good to go.

Example code:

```
...

  public static function getSubscribedEvents() {
    return [
      PageEvents::REDIRECT_DO_NOT_TRACK => ['addNonTrackable', 0],
    ];
  }

...

  public function addNonTrackable(UntrackableUrlsEvent $event) {
    foreach ($whateverlogic you need to fetch your tokens){
        $event->addNonTrackable("{MYPLUGINSTOKEN}");
    }
  }

...

```
