### ISSUE TITLE
Missing ct= url parameter when sending email via API

### ISSUE THREAD

**Issue by dokime7** [mautic/mautic#11572]
### Mautic Version

4.4.x series

### PHP version

7.4.30

### What happened?

I need to send an email to a contact with API (/emails/:id/contact/:id/send) with a link to a landing page {pagelink=3} which contains a form in order to get additionnal contact information.

When I send email from a contact page on web interface it's working as expected
But when I send email to a contact by using API the `ct` parameter is not added to the landing page url, so a new contact is created instead of update existing.

It seems that the `shouldAppendClickthrough()` method in `app/bundles/EmailBundle/Event/EmailSendEvent.php` returns false because an email is found...

### How can we reproduce this issue?

Step 1: Create a landing page
Step 2: Create an email with a {pagelink=1} tag to the landing page
Step 3: Create a contact with an email address
Step 4: Request the API endpoint `POST /emails/:email_id/contact/:contact_id/send` (replace :email_id and :contact_id)
Step 5: An email is received with a link like `https://domain.tld/landing-page` instead of `https://domain.tld/landing-page?ct=XXXXXXXXXXXXXXXXXXX`

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for the detailed bug report @dokime7 - much appreciated!

Which version of 4.4.x are you currently on?

Would you consider making a PR to address this issue? Some info on how to do that can be found in the [community handbook](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests) - you should make it against the 5.x branch at this time, and duplicate against 4.4 if you want it back-merged into a patch release.

If you need any help do shout in #dev on Slack (get an invite at https://mautic.org/slack).

**Comment by dokime7** [comment]
Version: v4.4.3

Unfortunatly, I don't know how to fix that.

There is a comment here https://github.com/mautic/mautic/blob/fe02a89b4b63ea9ec9f65840a946d91869ce0c7c/app/bundles/EmailBundle/Event/EmailSendEvent.php#L320 that tells that *the email tracking URL conversion process should take care of it* but not, I don't know why.

And even I can read PHP, I've not code with it for many years...

Thanks :)

**Comment by dokime7** [comment]
Does anyone know how to fix this?

**Comment by dokime7** [comment]
UP!
