### ISSUE TITLE
GoTo Webinar Segments filters are broken

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#11577]
### Mautic Version

4.4.x series

### PHP version

7.4.x

### What happened?

Segment filters for webinar fields load without values. 

<img width="840" alt="image" src="https://user-images.githubusercontent.com/1241376/195144102-44566bf2-9bda-4b24-a332-d9cebe5d592e.png">

Only after saving the segment without selection first, the selection fields show up.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/1241376/195144187-4f14e11f-d8dc-48b6-be30-5756ff47f743.png">

However - looks like this fix isn't working anymore: 
https://github.com/mautic/mautic/pull/9251/ @kuzmany 

Webinars will again be shown with the wrong descriptions.

### How can we reproduce this issue?

Step 1: Create a new segment in Mautic 4.4.3
Step 2: Define a filter related to webinars
Step 3: Look at the provided values to choose from

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
I tested to reverse the flip array removal (https://github.com/mautic/mautic/pull/9251) in the mautic/plugins/MauticCitrixBundle/EventListener/LeadSubscriber.php ... 

Compared to the referred PR, there were only two occasions of this (were 4 changes in 9251). It seems to have fixed the "Webinar (registered)" and "Webinar (attended)" filter, but not the "Webinar (did not attend)". There we see the cryptic descriptions (non flipped).

So only a partly success and also I have no clue, why this is now needed again.

The save before you can filter issue is also not solved by that (didn't expect it either).

**Comment by RCheesley** [comment]
Thanks for flagging this up @dsp76 - there were indeed some issues with the filter fields but I thought this was all fixed. Maybe something has been lost from that fix in the current code base, I know we had a lot of conflicts to resolve a while ago so that could be the case. @kuzmany @escopecz would one of you be able to take a look and see if something has gone awry somewhere in the release/merge process please? Thanks!

**Comment by escopecz** [comment]
@kuzmany can you please re-test the changes you made in https://github.com/mautic/mautic/pull/9251? It looks like it caused a regression.
