### ISSUE TITLE
Unsubscribe url problem

### ISSUE THREAD

**Issue by ciprianMihalache** [mautic/mautic#1157]
Problem with usubscribe url

Example: 

<a href="example.com/unsubscribe.php?{leadfield=email}">link</a>

{leadfield=email} is not replaced by leadfield value.

**Comment by alanhartless** [comment]
Just verifying, is this with Mautic's unsubscribe URL or a custom unsubscribe URL? And is it in the latest version of Mautic? I think tokens in URLs was fixed in https://github.com/mautic/mautic/pull/920 which was part of 1.2.1.

**Comment by escopecz** [comment]
Closing for lack of feedback.
