### ISSUE TITLE
Marketing Email gets send multiple times when using translations

### ISSUE THREAD

**Issue by bergwerkweb** [mautic/mautic#11586]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When using "marketing" E-Mails in Campaigns the selected mail should be sent only once, regardless if it is triggered again by a different campaign.

This does NOT work as soon as you work with translations - Only the "Parent" email gets evaluated and marketing emails with different languages get sent multiple times.

There already is an old bug report with a working solution here:
https://github.com/mautic/mautic/issues/8629

### How can we reproduce this issue?

Step 1: Create a Template E-Mail (Language English)
Step 2: Create a Translation for that E-Mail (e.g. Language German)
Step 3: Create a Test Segment and add Users with "preferred language"="de" AND  "preferred language"="en" 
Step 4: Create a "Campaign 1" which triggers sending of email from Step 1
Step 5: Create a "Campaign 2" which, after 2 minutes, also triggers sending of email from Step 1

All "english" contacts receive the mail only once, but all "german" contacts receive the e-mail twice. 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by Darko-F** [comment]
Mautic Version
4.4.x series

PHP version
8.0

I have same issue and confirm this bug.
 Only the "Parent" email gets evaluated and marketing emails with different languages get sent multiple times.

**Comment by RCheesley** [comment]
Thanks for the report folks! If someone can make the PR to fix this we can test and merge it - the fix is outlined in the issue mentioned above. 

Here's some [instructions](https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests), please make the PR against the 5.x branch, and a duplicate against 4.4 if you want the fix to get into a 4.4.x release before we release 5.0.

**Comment by RCheesley** [comment]
Not stale

**Comment by YosuCadilla** [comment]
Ma men bot, not stale, didn't you hear Ruth (rofl)
