### ISSUE TITLE
Mautic Is Not Receiving Mandrill's Spam Webhook

### ISSUE THREAD

**Issue by edutj** [mautic/mautic#1158]
Even though Mandrill is refusing to send e-mails because it was marked as spam, Mautic is not marking the lead as Do Not Contact.

What happens is that Mautic keeps sending while Mandrill refuses it until i delete the lead manually.

**Comment by edutj** [comment]
Any news on this one? Just today mandrill rejected the delivery of an e-mail 380 times. Because Mautic didn't mark the user as do not contact, and was persisting on sending to the lead.

**Comment by alanhartless** [comment]
Did you setup the Mandrill webhook? 

To leverage bounce callbacks, create a Mandrill webhook that points to http://your-mautic.com/mailer/mandrill/callback . Configure it to post to the events bounces, soft bounces, and failures. Finally create two custom metadata fields of hashId and leadId.

If you do have the hook setup, what displays if you hit up the URL manually?

**Comment by alanhartless** [comment]
I just reread the title and realized the request was for the spam webhook specifically.  Can you test the PR above to see if it resolves this?

Thanks.

**Comment by edutj** [comment]
Working. I just tested here.
