### ISSUE TITLE
Contact card is offline when we delete stage used by lead

### ISSUE THREAD

**Issue by automatyzuj** [mautic/mautic#11591]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

I deleted some stages. But contacts still have got these. Now, when I tried open contact card, I've got offline message.

When fater that, I set stage_id = NULL in DB for this lead, contact card works good again. 

### How can we reproduce this issue?

Step 1: Make some stage
Step 2: Add stage to any contact
Step 3: Delete this stage
Step 4: Go back to contact with deleted stage

### Relevant log output

```shell
mautic.NOTICE: PHP Notice - Undefined variable: inline - in file /var/www/mautic/offline.php - at line 77 {"inTemplate":true,"isAjax":true,"message":"The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.","submessage":"System administrators, check server logs for errors.","inDev":false,"base":"/","root":"/var/www/mautic","assetPrefix":"","paths":{"themes":"themes","assets":"media","asset_prefix":"","plugins":"plugins","translations":"translations","local_config":"%kernel.root_dir%/config/local.php","root":"/var/www/ma","app":"app","bundles":"app/bundles","vendor":"vendor"},"assetBase":"/media"} {"hostname":"mautika","pid":12907}
[2022-10-14 15:12:16] mautic.ERROR: Doctrine\ORM\EntityNotFoundException: Entity of type 'Mautic\StageBundle\Entity\Stage' for IDs id(3) was not found - in file /var/www/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/EntityNotFoundException.php - at line 33 []
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the issue @automatyzuj - hopefully a quick fix!

**Comment by biozshock** [comment]
@automatyzuj @RCheesley I was not able to reproduce on 5.x, 4.x and 4.4.4 mautic.

1. Added stage
2. Added stage to contact
3. Removed stage
4. Contact list, contact view and contact edit works fine.

Tried different combinations:

- Create one stage, add to one contact
- Create multiple stages, add to different contact, remove with batch remove
- Create one stage, add to multiple contacts.

Please check that bug is reproducible on latest 4.4.4.

**Comment by biozshock** [comment]
@automatyzuj Can you please check that your database uses InnoDB, and there is a constraint in the database that sets `stage_id` to `NULL`.

You may use a mysqldump console program: `mysqldump --skip-add-drop-table -h [HOST] -u [username] -p --no-data [database name] leads`, PHPMyAdmin or a DBeaver to look for a table DDL.

Table definition should end like:
```SQL
  CONSTRAINT `FK_179045522298D193` FOREIGN KEY (`stage_id`) REFERENCES `stages` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_179045527E3C61F9` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB
```

**Comment by automatyzuj** [comment]
Confirm. Now it works.

**Comment by biozshock** [comment]
@RCheesley @escopecz  i think this can be closed?
