### ISSUE TITLE
SAML-related routes are not accessible

### ISSUE THREAD

**Issue by atatarn** [mautic/mautic#11592]
### Mautic Version

4.4.x series

### PHP version

8.0.24

### What browsers are you seeing the problem on?

Chrome

### What happened?

It is impossible to access any SAML-related routes (/s/saml/login, /saml/metadata.xml) using nginx as a reverse-proxy.
The nginx config was taken here: https://gist.github.com/proffalken/ebfa9debc4eef929b0163d11a80af349
It seems for me that there are no problems with nginx and/or php-fpm installation, because all regular authenticated (/s/dashboard, settings, campaign management) and anonymous (tracking pixels, landing pages) routes are working properly.

But all of the SAML-related ones are redirecting to /.

### How can we reproduce this issue?

* Install fresh mautic 4.4.3 with php-fpm 8.0 and nginx to serve requests
* Grab nginx config from this gist: https://gist.github.com/proffalken/ebfa9debc4eef929b0163d11a80af349
* Try to access /saml/metadata.xml to get metadata file to pass to IDP

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
I believe that this is most likely an issue with server configuration, and therefore best to be discussed at https://forum.mautic.org/c/support.
