### ISSUE TITLE
Integration With Youtube channel

### ISSUE THREAD

**Issue by edutj** [mautic/mautic#1160]
Just as with Wordpress integration, It would be good for Mautic to be able to send Youtube Video Posts Summaries based on a pre-defined time setting. Such as Weekly, Monthly etc.

**Comment by escopecz** [comment]
> Just as with Wordpress integration
I didn't know Mautic - WP plugin can do such thing. Could you describe it in more detail? For example with a use case?

**Comment by edutj** [comment]
Ones who maintain an active Youtube Channel (or Wordpress Blog) post new content almost on a daily basis. If it would be possible for Mautic to gather this information on a weekly / every 2 weeks / monthly and send it to a defined list(s).

This could help keep leads active and interacting with the content a mautic user is promoting.

**Comment by edutj** [comment]
This is a feature request.

**Comment by dbhurley** [comment]
Can we get clarification on how this should be carried out? What does it look like and the process for how it would actually work? From start to finish...the workflow would be helpful as the community explores building this feature!

**Comment by escopecz** [comment]
Implemented in https://github.com/mautic/mautic/pull/2081
