### ISSUE TITLE
401 API Auth

### ISSUE THREAD

**Issue by roymodev** [mautic/mautic#11615]
### Mautic Version

4.4.x series

### PHP version

7.4.25

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Whit the lasts stable version of Mautic (4.4.3) I'm getting 401 when I try to do any API calls.

I tried to rm -rf var/cache but I'm still getting 401 when trying to access the API. No HTTP Basic popup triggered when I access something like /api/contacts?limit=1&minimal=1. Both API and HTTP Basic are enabled.

### How can we reproduce this issue?

Step 1: Turn on API & Basic Auth
Step 2: Try to access something like /api/contacts?limit=1&minimal=1

### Relevant log output

```shell
{
  "errors": [
    {
      "message": "La autorización a la API está denegada.",
      "code": 401,
      "type": "access_denied"
    }
  ]
}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, this is not how basic API works. There is no popup.
Plz check the docs:
https://developer.mautic.org/#oauth-2
