### ISSUE TITLE
Unable to preview image assets

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11616]
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Chrome

### What happened?

When an asset is created, it should be possible to preview it in a modal window:

https://watch.screencastify.com/v/kwy8SiR186W1d2ZS23k5

The preview never happens - it just throws an error in the console:

```
[SyntaxError: Unexpected token '�', "�" is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.processAjaxError (1.core.js?v52c79a5c:600:41)
    at Object.error (9.modals.js?v52c79a5c:140:20)
    at fire (2.jquery.js?v52c79a5c:3268:32)
    at Object.fireWith [as rejectWith] (2.jquery.js?v52c79a5c:3398:8)
    at done (2.jquery.js?v52c79a5c:9307:15)
    at XMLHttpRequest.<anonymous> (2.jquery.js?v52c79a5c:9548:10)]([url](url))
```

Picked this up while testing https://github.com/mautic/mautic/pull/11610 but it exists in the default branch already.

### How can we reproduce this issue?

Step 1: Create an asset of an image (which should be possible to preview)
Step 2: From the asset list, click preview

### Relevant log output

```shell
Nothing in the log - only the console from the browser.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mollux** [comment]
most likely caused by https://github.com/mautic/mautic/pull/11043 and fixed by https://github.com/mautic/mautic/pull/11474 

We definitely need a test to check the outcome

**Comment by mabumusa1** [comment]
Keep open
