### ISSUE TITLE
Error on loading Doctrine fixtures

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11611]
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I am loading fixtures I am seeing this at the end of the process - it seems to load in the fixtures though. From @mollux : probably mixing DDL and DQL queries in the same request, together with PHP 8
 see https://github.com/mautic/mautic/pull/11059 for context.

```
loading [10] Mautic\AssetBundle\DataFixtures\ORM\LoadAssetData
 loading [10] MauticPlugin\MauticCitrixBundle\Tests\DataFixtures\ORM\LoadCitrixData

In Connection.php line 1854:
                                  
  There is no active transaction  
                                  

doctrine:fixtures:load [--append] [--group GROUP] [--em EM] [--purger PURGER] [--purge-exclusions PURGE-EXCLUSIONS] [--shard SHARD] [--purge-with-truncate] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

Failed to execute command bin/console d:f:l: exit status 1
```

### How can we reproduce this issue?

Step 1: Install Mautic
Step 2: Load sample data using ddev exec bin/console d:f:l
Step 3: Note the error thrown

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mollux** [comment]
The DDL queries are coming from the [`LoadFormData`](https://github.com/mautic/mautic/blob/5.x/app/bundles/FormBundle/DataFixtures/ORM/LoadFormData.php#L121
) fixture.

See https://www.doctrine-project.org/projects/doctrine-data-fixtures/en/latest/explanation/transactions-and-purging.html#transactions-and-purging and https://www.doctrine-project.org/projects/doctrine-data-fixtures/en/latest/explanation/transactions-and-purging.html#transactions-and-purging for more context.
