### ISSUE TITLE
Unable to double click elements in media manager outside of an active builder

### ISSUE THREAD

**Issue by bianchim** [mautic/mautic#11624]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When using the media manager in a custom config, the double click was not working at all outputing this message :

![image](https://user-images.githubusercontent.com/19705314/197705309-67e06adb-6785-422d-bfdf-ddf7d82dc732.png)

Going deeper into the code to understand the exact problem I stumbled on this ( this is the same code for versions 4 and 5 of Mautic ): 
https://github.com/mautic/mautic/blob/5.x/app/bundles/CoreBundle/Assets/js/4.builder.js#L1362

the whole process bugs out due to the "underfined" typo in the code. Moreover, the actual value I have is "null" in console, and not "undefined", causing the same issue even when fixed.

I'm not sure of the implications, but changing this line to this would do the trick :
`typeof FroalaEditorForFileManager !== 'underfined' && FroalaEditorForFileManager !== null`

The issue still remains that the media manager does not work without overriding this function, but at least we avoid a en error.

### How can we reproduce this issue?

Step 1: Add a call to "Mautic.openMediaManager()" on a button without an active builde / editor in the page.
For example we used this in a config template for the "/s/config/edit" page : 
`
<button type="button" class="btn btn-default btn-nospin" onclick="Mautic.openMediaManager()">
    <i class="fa fa-photo"></i>
    <?= $translator->trans('mautic.core.media.manager') ?>
</button>
`

Step 2: Double click any media.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the issue - would you be open to considering making a PR to address the bug?

**Comment by bianchim** [comment]
Sorry for the late answer ! 

To be honest I'm not sure what the best course would be for this. The code clearly intends for this to be used in builders only and not any page of Mautic.

What we ended up doing is going the hacky way and override the global function :
`
window.document.fileManagerInsertImageCallback = (_selector, urlString) => {
      const url = new URL(urlString);
      const faviconPathInput = document.querySelector("{{ 'input#' ~ form.custom_favicon_path.vars.id }}");

      if (faviconPathInput instanceof HTMLInputElement) {
        faviconPathInput.value = url.pathname;
      }
    }
`

So while this does fulfill our need, maybe the best course of action would be to add options to `Mautic.openMediaManager()` in order to be able to provide callbacks. But this requires more groundwork to change the whole process to avoid global callback.
