### ISSUE TITLE
Create 5.x PR for #11544

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11628]
@kuzmany please make the PR against 5.x also - this is an older one so I think we haven't got the companion PR yet. Thanks!

_Originally posted by @RCheesley in https://github.com/mautic/mautic/issues/11544#issuecomment-1290407198_

**Comment by kuzmany** [comment]
https://github.com/mautic/mautic/pull/11638

**Comment by RCheesley** [comment]
Not stale

**Comment by mabumusa1** [comment]
Keep open
