### ISSUE TITLE
SAML Session Extremely Short

### ISSUE THREAD

**Issue by onairmarc** [mautic/mautic#11626]
### Mautic Version

4.4.x series

### PHP version

7.4

### What happened?

Signing in via SAML works, but the session is extremely short. Sometimes less than 5 minutes. When building out an email, the session expires and all work is lost due to the session noting being able to be authenticated. I then have to refresh the page and the SAML flow is fired off and re-auth is successful. But all work is lost.

### How can we reproduce this issue?

Step 1: Login via SAML
Step 2: Wait about 5 or so minutes. UI becomes unresponsive, and no buttons work.
Step 3: Refresh the page, SAML flow fires off and Mautic begins working again. Then the session quickly expires.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @mbeinder, what do you have set for your session timeout? Does that make any impact on the SSO timeout if it's raised at all?

I noticed there is a forum post on this: https://forum.mautic.org/t/saml-redirect-on-idle-session-timeout/25645 which you have already posted on (and the older thread as well) so it seems to be happening to a few people.

**Comment by onairmarc** [comment]
@RCheesley, I've never adjusted the session timeout once SAML was setup and it was working perfectly fine until the last update or two. I don't remember which version it broke on.

**Comment by onairmarc** [comment]
I also didn't know I could adjust it, so I'm not sure where I would check that.

**Comment by onairmarc** [comment]
@RCheesley i just updated the session setting in .user.ini and there were no changes to behavior. I restarted the server and re-authed, but there was no change. It was was to 1440 and I upped it to 2000
