### ISSUE TITLE
Not using Site Url Settings for emails

### ISSUE THREAD

**Issue by ShortCipher5** [mautic/mautic#11637]
### Mautic Version

4.4.x series

### PHP version

7.4.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I operate two domains which both point to the same Mautic installation.

mautic.private
mautic.public

I use mautic.private to access the Mautic software - a link which is not accessible to others across the internet. However I have made mautic.public available to allow access to non control-panel links (for tracking and images).

In sending a test email, tracking is not enabled, so this bug wasn't immediately clear. However when sending emails using the mautic.private address the emails have all been sent with mautic.private tracking links - despite the settings configuration being set to mautic.public.

- Mautic should use the URL set in the configuration - not use the url being accessed.

### How can we reproduce this issue?

Step 1: Access Mautic on a domain that is not set in the configuration settings
Step 2: Send email
Step 3: Sent emails will use the address from the active site - not the settings page

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by matbcvo** [comment]
I can confirm Mautic uses domain from access URL on the browser's address bar, not in Configuration -> System Settings -> Site URL (but should use this one instead) for unsubscribe link, web version link etc.

**Comment by shyam-achuthan** [comment]
Similar issue encountered
Mautic was running on xyz.abc.com:8880
Went to configuration and changed to pqr.xyz.com and set relevant pointers

All otehr functionalities of Mautic is working good except
1) preview url still shows localhost:8880
2) Email sending is absolutely fine but tracking urls shows localhost:8880 as a result links in email and as well as view tracking doesnt work

**Comment by jos0405** [comment]
Hi, this is not a feature you can find as default in Mautic.
But you can use a free plugin for this:
https://github.com/FriendlyDotCH/mautic-multi-domain

I'll close this for now.
