### ISSUE TITLE
URL's used as email token are malformed

### ISSUE THREAD

**Issue by JaZo** [mautic/mautic#11643]
### Mautic Version

4.4.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When you use an URL as a token in an email, it converts `&` to `&#38;`, breaking the URL. I can find [several](https://github.com/mautic/mautic/blob/5.x/app/bundles/PageBundle/Model/RedirectModel.php#L114-L117) [workarounds](https://github.com/mautic/mautic/blob/5.x/app/bundles/PageBundle/Model/TrackableModel.php#L118-L121) in the code that replace `&amp;` with `&` before it is inserted as tracking link, but these do not decode the decimal version.

API endpoint used: https://developer.mautic.org/?php#send-email-to-contact

Relevant code points:
 * https://github.com/mautic/mautic/blob/5.x/app/bundles/EmailBundle/Controller/Api/EmailApiController.php#L125
 * https://github.com/mautic/mautic/blob/5.x/app/bundles/CoreBundle/Helper/InputHelper.php#L193

Demo of extracted code that causes the issue: https://3v4l.org/c8rgB

### How can we reproduce this issue?

1. Make sure you have a contact;
2. Create a template email and use `{url}` as the URL of a link;
4. Call the API endpoint: `/api/emails/[ID OF EMAIL]/contact/[ID OF CONTACT]/send` with body:
```
{
    "tokens": {
        "url": "https://localhost/test?foo=bar&email=john.doe%40example.com"
    }
}
```
4. Click the link in the received email;
5. See you're redirected to `https://localhost/test?foo=bar&#38;email=john.doe%40example.com`.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the issue! Is there any chance you might be up for looking into making a PR to fix it? Our docs are here: https://contribute.mautic.org/contributing-to-mautic/developer - it would need to be made against the 5.x branch, and also against 4.4 if you want us to merge it into a bugfix release before 5.0. Shout if you need any help!

**Comment by JaZo** [comment]
I've opened #11644 to address this. Please let me know if something should be changed.
