### ISSUE TITLE
Stored XSS via add note for contact

### ISSUE THREAD

**Issue by ch1nhpd** [mautic/mautic#11647]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Stored XSS

### How can we reproduce this issue?

https://www.youtube.com/watch?v=3MbUBpd3xSI

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Security issues must be reported through the correct channels.
