### ISSUE TITLE
Tracking Emails are not tracked | Number of click on urls 

### ISSUE THREAD

**Issue by CM-AvenirData** [mautic/mautic#11641]
### Mautic Version

3.3.x series (not supported)

### PHP version

7.3

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What happened?

Hi , 

We discovered a bug into the process of email's tracks.

I explain, we built an email with url inside. Mautic creates is own url to track the click on the link.
Example : 

https://foo.com/mautic/r/[ID of the track's url]&fdksnvfdnsbnefdjsvfdknvfd

When people received the mail, they can click on it then they'll going to be redirect on the correct url. BUT in the section "Number of Clicks" We still have 0 clicks on the link.

The problem concern every url. We don't have any error logs. 

I saw that 3.3.x mautic are not supported but please help us..

### How can we reproduce this issue?

Step 1: Create an email with url inside

Step 2 : Send the email to someone

Step 3 : Click on the email and click on url 

Step 4 : Check in the mautic -> Emails -> The email -> Number of click and check the number of click 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Mautic 3.3 is not supported, maybe you can ask for help in the Forums?
https://www.mautic.org/support
