### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by domaingood** [mautic/mautic#11659]
### Mautic Version

5.0.x series

### PHP version

8.1

### What browsers are you seeing the problem on?

Not relevant

### What happened?

upload and then try to install but getting error 
This page isn’t working right now can't currently handle this request.
HTTP ERROR 500

SO cannot install.

# php -v
PHP 8.1.9 (cli) (built: Aug  9 2022 23:45:28) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies
# php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
enchant
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
imap
json
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

mysql  Ver 15.1 Distrib 10.9.3-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

### How can we reproduce this issue?

Step 1:  upload and then try to install but getting error 
This page isn’t working right now can't currently handle this request.
HTTP ERROR 500

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Mautic 4.4.4 is not compaible with 8.1, ust 8.0

**Comment by domaingood** [comment]
I m trying to install mautic 5.x not 4

**Comment by RCheesley** [comment]
It didn't yet have 8.1 support merged.

**Comment by bendaoua** [comment]
That explains, had the same issue installing today with 8.1

**Comment by RCheesley** [comment]
Mautic does not yet support PHP 8.1. Please check the requirements page: https://www.mautic.org/download/requirements

We are hoping to ship support in Mautic 5.0 as it is a major breaking change with a substantial amount of work that needs to be done to support it.

If you want to help get it out sooner please join us on Slack on Fridays (or any day, but Friday is when a lot of folks are around) in #t-product for our Open Source Friday sessions where you can help with testing bugs and features. All done in the browser, just need to know how to use Mautic.

Get an invite to slack at https://mau.tc/slack-invite and learn more about helping contribute as a tester: https://contribute.mautic.org/contributing-to-mautic/tester
