### ISSUE TITLE
Duplicated tags created via API

### ISSUE THREAD

**Issue by Dylan-86** [mautic/mautic#11652]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

We update contacts via API and assign a Tag to them when an "event" happens.

We've got a script that basically runs this way, for all contacts in a specific list on our end:

for 1,n:
 add_tag(user, tag)

Now, the strange thing is what you can see below:
![image](https://user-images.githubusercontent.com/58813956/198965626-25de82a6-c70f-4671-afa1-79219d016995.png)

During a single run of the script, 4 "different" tags have been created. They have different IDs (ID 96 has the most users, 95,94,93 have 1) but the same "name".

Any idea about how to solve this?!

### How can we reproduce this issue?

Step 1: 
Create/Update a list of users via API and assign the same Tag to each.

### Relevant log output

```shell
None
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by Dylan-86** [comment]
I confirm that the issue is still there and easily replicable on our end.

Connect MixPanel to Mautic and duplicated tags are created every now and then. 
![image](https://user-images.githubusercontent.com/58813956/218302221-ba7ebfce-b8c7-4369-b78c-dfc3003be8db.png)

**Comment by RCheesley** [comment]
@Dylan-86 is this still an issue for you?

**Comment by Dylan-86** [comment]
> @Dylan-86 is this still an issue for you?

Honestly  I do not know since we have not imported more contacts recently, but I just ran a script to import some contacts from MixPanel, I'll let you know how it goes in 1 hours, I think.

**Comment by Dylan-86** [comment]
> @Dylan-86 is this still an issue for you?

It seems that the issue is gone. Our developer told me that we put a short delay between each new user's creation to avoid duplicated Tags.
So, it seems that if Mautic receives too many new contacts in a short time, each with the same new tag (created with the first contact), it creates multiple tags, because it can't read in time that the tag already exists.
