### ISSUE TITLE
Entire Mautic Installation 500 Internal Server Error After Clicking Unsubscribe Link

### ISSUE THREAD

**Issue by WildeWebMarketing** [mautic/mautic#11650]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

1. Tested unsubscribe link in email.
2. Unsubscribe page displayed correctly.
3. Refreshed admin dashboard which resulted in a 500 Internal Server Error
4. Cleared Mautic cache, no change

### How can we reproduce this issue?

Step 1: 

### Relevant log output

```shell
mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given" at /home/wildeweb/webapps/Mautic/app/bundles/CoreBundle/EventListener/DashboardSubscriber.php line 101 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given at /home/wildeweb/webapps/Mautic/app/bundles/CoreBundle/EventListener/DashboardSubscriber.php:101)"}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi,
It really matters how you test.
Check this:
https://kb.mautic.org/article/how-to-test-emails-in-mautic.html
Or this:
https://www.youtube.com/watch?v=a1LdcypnO9Q&t=725s

Plz reopen if you still think the bug exists
