### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by komitaltrade** [mautic/mautic#1165]
Is it some particular reason why Mautic don't have multiple Mailbox possibilities (like OROCRM)?

It is not about the issue that Mautic should not to be "girl for everything", it is that I see at least several downsides (vs marketing):

    another tracking channel (as well visual option for dashboard)
    "branding campaigns" (ie) ios9@pinapple.com, iphone6s@pinapple.com (looks much more interesting/atractive to launch campaign with = email prefix, isn't?)
    Subscription is not a Mautic task (on first look), but tracking news@pinapple.com during (ie) ios9 campaign (separated from ios9@pinapple.com actions) can show mutual impact on two complete different actions.

**Comment by alanhartless** [comment]
Are you referring to who the email is "from" when sent from Mautic? Emails have the option on the Advanced tab to set custom from, reply to, etc emails.

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to comment on this issue any time and I will re-open it again.
