### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by tylerfs** [mautic/mautic#1166]
I uploaded a list of new contacts and after that was complete (I think it was complete, the contacts I was importing display in the list but the initial import progress bar never moves from 0/1000) I tried to look at the details of one of the recently imported contacts only to be presented with a 500 Internal Server Error message.

I am not sure what this means or how I go about fixing this issue. This is not the first time that I have imported contacts.

**Comment by escopecz** [comment]
Please, check the Mautic logs (app/logs dir) and server logs for more details.

**Comment by alanhartless** [comment]
Closing due to lack of feedback.  If you are able to find the error in your logs, please provide further details and we'll reopen the ticket.

Thanks!
Alan
