### ISSUE TITLE
Duplicating segment: alias not altered if segment is unpublished

### ISSUE THREAD

**Issue by jos0405** [mautic/mautic#11661]
### Mautic Version

4.4.x series

### PHP version

7.4, 8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I checked this on 4.4.1 - 4.4.4, all impacted.

If you duplicate a segment, which is unpublished, the alias won't be altered.
There should be a number added after segment alias , like test -> test1

### How can we reproduce this issue?

Step 1: take a segment, which is unpublished
![image](https://user-images.githubusercontent.com/4246909/199683473-e5f8ee2f-d09e-4f37-b361-c8be571d80f9.png)
Step 2: duplicate it.
alias not altered.
![image](https://user-images.githubusercontent.com/4246909/199683569-feab114f-1dc4-4979-bef2-be34782628d2.png)
Step 3: Now publish it, and duplicate again. Now it works:
![image](https://user-images.githubusercontent.com/4246909/199683672-092ad0c4-f21c-4fdf-9e0f-cb2e9101b106.png)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by paulpiazzalu** [comment]
Hi @jos0405 
I found the bug.
Do you think you will review this issue?
