### ISSUE TITLE
Exported contacts do not include 'Do Not Contact' flag

### ISSUE THREAD

**Issue by quadcom** [mautic/mautic#11679]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

Exporting contacts to CSV does not include any flag for **do not contact**.

### How can we reproduce this issue?

Step 1:  Export contacts and look at the fields exported

**Why is this an issue:** I just started from scratch as my v4.1.2 install was destroyed after trying to update to 4.4.4. I exported my list of contacts and imported them into v4.4.4. None of the imports have any do not email flags attributed. I knew specifically of one contact that was recently unsubbed and that contact was not flagged after importing. Emailing a contact that has unsubbed leads to future emails being marked as spam and trashes your sender score.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
No, it's not included as a default, but Mautic allows you to create any report. You can create a report where you can show the DNC reason as well, so you can make the perfect import after that.
