### ISSUE TITLE
mautic:leadlists:update strange behavior

### ISSUE THREAD

**Issue by allafa70** [mautic/mautic#1168]
Hi,
the lists on my Mautic installation are not updating correctly so I tried to run this command manually
php /xxxxxxxx/app/console mautic:leadlists:update

and the result I get is:
```
Ricostruzione lead per la lista 1
0 lead totali da aggiungere in gruppo a 300
1508 lead totali da eliminare in gruppi di 300
 1508/1508 [============================] 100%
1800 lead interessati
```

If I try to run it again the message is always the same ... 1508 lead to update but nothing happen
(an arrow show me the progress between 0 and 100%).

I looked at the logs but I cannot find any issue.

How can I check what's happening?
How can I restore the correct behavior?

thanks

**Comment by alanhartless** [comment]
What are the filters for lead list 1?

**Comment by allafa70** [comment]
Hi alanhartless,
thank you for your interest.
Unfortunately I had to change the program used for email marketing because of too many issues with mautic.
The first big problem was the db size produced by mautic.
Now I use Mailwizz.

Thank you again for your support.

**Comment by alanhartless** [comment]
No worries.  If you ever feel the need to circle back to us, we've addressed the database size with email sends which will be part of 1.2.3 when released.  https://github.com/mautic/mautic/pull/1227
