### ISSUE TITLE
Email configuration - navigateur auto-complete override configuration 

### ISSUE THREAD

**Issue by thacac** [mautic/mautic#11699]
### Mautic Version

4.4.x series

### PHP version

8.0.25

### What happened?

Cannot set right email configuration on https domain through Chrome (not tested on others nav)

### How can we reproduce this issue?

Step 1: go to configuration page / email settings
Step 2: the smtp password field is autofill by the navigateur with current user account pwd
Step 3:when saving (as asked), it erases the right config, even if we let the field blank, the auto fill will happen

> cannot configure emails

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, push ESC to remove autofill.
