### ISSUE TITLE
While importing tags not being passed to API if only 1 is selected

### ISSUE THREAD

**Issue by bartoszpijet** [mautic/mautic#11698]
### Mautic Version

4.4.x series (4.4.4)

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

While importing contacts if you select only 1 tag it will not get passed to import request (checked in networking tab). If you select 2 or more everything works fine. Of cause if you select 0 it does not send any tags which is to be desired.

### How can we reproduce this issue?

Step 1: Import CVS (even with only emails)
Step 2: Pass email field to be imported as contact email
Step 3: Select only 1 tag to assign to contacts
Step 4: Selected tag is not being sent to Mautic and is not being imported because of it.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi,
I couldn't reporduce it. I know about this bug back in earlier version of 4.xx but not in 4.4.5.
https://www.loom.com/share/71b03fb8589344e7b58144845afe8a87
I close it for now, maybe issue with your environment.
