### ISSUE TITLE
"Send email to user" emails are not counted as sent if user field is left blank

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#11695]
### Mautic Version

4.4.x series

### PHP version

8.0.15

### What happened?

![image](https://user-images.githubusercontent.com/7994227/224538448-cfcebe7a-cd9c-4ea0-9d86-fd21c4d0f719.png)

Set a "Send email to user" event up to send an email to a TO: address without entering a value in the "Send email to user" field:
![image](https://user-images.githubusercontent.com/7994227/200930190-231a7d0b-27c8-4d8b-a565-d5a2f01bdbd8.png)

This functions, and the email is sent to the email address in the TO: field as expected, however the stats or tracking whether or not the email was sent is not visible ina in a contact's timeline like the email sent to a contact appears:
![image](https://user-images.githubusercontent.com/7994227/200930688-9f491a2e-2b3b-4169-b22d-f22eba54edca.png)

### How can we reproduce this issue?

Step 1: Set a "Send email to user" event up to send an email to a TO: address without entering a value in the "Send email to user" field:
![image](https://user-images.githubusercontent.com/7994227/200930190-231a7d0b-27c8-4d8b-a565-d5a2f01bdbd8.png)
Step 2: Put a contact through the campaign
Step 3: No stats are tracked for the Send email to user step.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mabumusa1** [comment]
Keep open
