### ISSUE TITLE
Template email sent by campaign not accruing stats

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#11694]
### Mautic Version

4.4.x series

### PHP version

8.0.15

### What browsers are you seeing the problem on?

Chrome

### What happened?

Although emails have been sent by a campaign, the associated template emails sent by said campaign do not accrue any stats:

![image](https://user-images.githubusercontent.com/7994227/200875814-34fdf470-1eaf-4e51-a41c-de8dd86ea01e.png)

### How can we reproduce this issue?

1. Create campaign and attach template email to a send email to contact event
2. Put leads through campaign
3. View stats

### Relevant log output

```shell
I am not sure where to find logs for this issue.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, here you can see, that nothing is sent. Not even by campaign.
Plz provide more info with sent emails and reopen this report.

**Comment by vexersa** [comment]
> 
Hi @jos0405, 

I'm not sure what you mean exactly. 

What should I add to this report?
