### ISSUE TITLE
Bug when restoring the Mautic database

### ISSUE THREAD

**Issue by nick-fullstack-dev** [mautic/mautic#11700]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What happened?

I'm trying to transfer my Mautic 4.4.2 installation to another server.
I am using MySQL 8.0.31
I exported the database of my Mautic installation to import it on my new server running the same MySQL version.
When importing I get this error (the data is anonymized):

```
INSERT INTO `email_stats` (`id`, `email_id`, `lead_id`, `list_id`, `ip_id`, `copy_id`, `email_address`, `date_sent`, `is_read`, `is_failed`, `viewed_in_browser`, `date_read`, `tracking_hash`, `retry_count`, `source`, `source_id`, `tokens`, `open_count`, `last_opened`, `open_details`, `generated_sent_date`) VALUES
(22207,	1,	57815,	NULL,	18448,	'xxxd7d7fec670xxxx7ec11ac61ad',	'xxxxx@xxxx.com',	'2022-10-30 23:52:11',	1,	0,	0,	'2022-10-30 23:53:31',	'xxxxab36b6059309433',	0,	'campaign.event',	307,	'a:14:{s:36:\"{dynamiccontent=\"Dynamic Content 1\"}\";s:23:\"Default Dynamic Content\";s:18:\"{unsubscribe_text}\";s:123:\"<a href=\"https://mt.xxxx.net/email/unsubscribe/635fxxxx0593xxx433\">Unsubscribe</a> to stop receiving emails from us.\";s:17:\"{unsubscribe_url}\";s:63:\"https://mt.xxxxx.net/email/unsubscribe/635xxxxx36b6xxxxx433\";s:14:\"{webview_text}\";s:117:\"<a href=\"https://mt.xxx.net/email/view/635xxxx6059xxxxxx33\">Having trouble reading this emai…

Error in query (3105): The value specified for generated column 'generated_sent_date' in table 'email_stats' is not allowed.

```

I don't dare update my Mautic installation if the database backups don't work.

Is there a solution to fix this bug?

### How can we reproduce this issue?

Step 1: export the database
Step 2: import the database

### Relevant log output

```shell
INSERT INTO `email_stats` (`id`, `email_id`, `lead_id`, `list_id`, `ip_id`, `copy_id`, `email_address`, `date_sent`, `is_read`, `is_failed`, `viewed_in_browser`, `date_read`, `tracking_hash`, `retry_count`, `source`, `source_id`, `tokens`, `open_count`, `last_opened`, `open_details`, `generated_sent_date`) VALUES
(22207,	1,	57815,	NULL,	18448,	'xxxd7d7fec670xxxx7ec11ac61ad',	'xxxxx@xxxx.com',	'2022-10-30 23:52:11',	1,	0,	0,	'2022-10-30 23:53:31',	'xxxxab36b6059309433',	0,	'campaign.event',	307,	'a:14:{s:36:\"{dynamiccontent=\"Dynamic Content 1\"}\";s:23:\"Default Dynamic Content\";s:18:\"{unsubscribe_text}\";s:123:\"<a href=\"https://mt.xxxx.net/email/unsubscribe/635fxxxx0593xxx433\">Unsubscribe</a> to stop receiving emails from us.\";s:17:\"{unsubscribe_url}\";s:63:\"https://mt.xxxxx.net/email/unsubscribe/635xxxxx36b6xxxxx433\";s:14:\"{webview_text}\";s:117:\"<a href=\"https://mt.xxxx.net/email/view/635xxxx6059xxxxxx33\">Having trouble reading this emai…

Error in query (3105): The value specified for generated column 'generated_sent_date' in table 'email_stats' is not allowed.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by nick-fullstack-dev** [comment]
I updated my Mautic installation to version 4.4.4, the bug is still present.

I used this solution to work around the problem with Mautic 4.4.4.

edit mysql dump
```
sed -i 's/(generated_sent_date date).+/\1,/' dump.sql
sed -i 's/(generated_email_domain varchar(255)).+/\1,/' dump.sql
```

edit database table 
```
ALTER TABLE email_stats DROP column generated_sent_date;
ALTER TABLE email_stats ADD generated_sent_date date GENERATED ALWAYS AS (concat(year(date_sent),_utf8mb4'-',lpad(month(date_sent),2,_utf8mb4'0'),_utf8mb4'-',lpad(dayofmonth(date_sent),2,_utf8mb4'0'))) VIRTUAL COMMENT '(DC2Type:generated)';
ALTER TABLE email_stats DROP column generated_email_domain;
ALTER TABLE email_stats ADD varchar(255) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (substr(email,(locate(_utf8mb4'@',email) + 1))) VIRTUAL COMMENT '(DC2Type:generated)';
```

Make sure the generated_email_domain of the email_stats table has a default value.

**Comment by fgonzalez** [comment]
I had the same problems,  because of the Generated Columns. 
 All tables with generated values marked as GENERATED ALWAYS and the tag VIRTUAL,  can't store a value, but dump doesn't know that the value is generated.  So the dumps contains the generated value.
When an import occurs the value is there for the "GENERATED ALWAYS" columns this causes a "**not allowed**" error.  
To correct the error we need to manipulate de portion of the dump file, extract the table and insert into command to  modified them.  We need to 
1. Remove the value from the generated column 
2.  in the INSERT TO  command list all the fields in the same order, without the generated field.  Example:
INSERT INTO `mauek_leads`(`id`, `owner_id`, `stage_id`, `is_published`, `date_added`, `created_by`, `created_by_user`, `date_modified`, `modified_by`, `modified_by_user`, `checked_out`, `checked_out_by`, `checked_out_by_user`, `points`, `last_active`, `internal`, `social_cache`, `date_identified`, `preferred_profile_image`, `title`, `firstname`, `lastname`, `company`, `position`, `email`, `phone`, `mobile`, `address1`, `address2`, `city`, `state`, `zipcode`, `timezone`, `country`, `fax`, `preferred_locale`, `attribution_date`, `attribution`, `website`, `facebook`, `foursquare`, `instagram`, `linkedin`, `skype`, `twitter`, `ec`, `llamar`, `matricula`, `ticketms`, `edad`, `estadocivil`, `cumpleanos`, `email2`) VALUES
in this table de generated field is:  generated_email_domain. 

Finally run the new sql INSERT TO  command, and the values will be added.

**Comment by jos0405** [comment]
I can confirm the same issue.

**Comment by jos0405** [comment]
Hi, regarding the leads table:

```
ALTER TABLE leads DROP column generated_email_domain;
ALTER TABLE leads ADD generated_email_domain varchar(255) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (substr(email,(locate(_utf8mb4'@',email) + 1))) VIRTUAL COMMENT '(DC2Type:generated)';
```

**Comment by tobsowo** [comment]
> I updated my Mautic installation to version 4.4.4, the bug is still present.
> 
> I used this solution to work around the problem with Mautic 4.4.4.
> 
> edit mysql dump
> 
> ```
> sed -i 's/(generated_sent_date date).+/\1,/' dump.sql
> sed -i 's/(generated_email_domain varchar(255)).+/\1,/' dump.sql
> ```
> 
> edit database table
> 
> ```
> ALTER TABLE email_stats DROP column generated_sent_date;
> ALTER TABLE email_stats ADD generated_sent_date date GENERATED ALWAYS AS (concat(year(date_sent),_utf8mb4'-',lpad(month(date_sent),2,_utf8mb4'0'),_utf8mb4'-',lpad(dayofmonth(date_sent),2,_utf8mb4'0'))) VIRTUAL COMMENT '(DC2Type:generated)';
> ALTER TABLE email_stats DROP column generated_email_domain;
> ALTER TABLE email_stats ADD varchar(255) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (substr(email,(locate(_utf8mb4'@',email) + 1))) VIRTUAL COMMENT '(DC2Type:generated)';
> ```
> 
> Make sure the generated_email_domain of the email_stats table has a default value.

@githubcom13 I have the same issue and tried following these steps but it is not working.
Please can you help?

**Comment by alexhammerschmied** [comment]
Hi all, 
the problem is here again. 
It occurs in 5.2.1 and 5.2.2

**Comment by alexhammerschmied** [comment]
I solved it by:

**Step 1 Before making the mysqldump:**

`ALTER TABLE leads DROP column generated_email_domain;
ALTER TABLE email-stats DROP column generated_sent_date;`

**Step 2 make the mysqldump**

**Step 3 import your mysqldump to wherever you want your backup**

**Step 4 connect to mysql and run:**
`ALTER TABLE leads ADD generated_email_domain varchar(255) COLLATE utf8mb4_unicode_ci GENERATED ALWAYS AS (substr(email,(locate(_utf8mb4'@',email) + 1))) VIRTUAL COMMENT '(DC2Type:generated)';
ALTER TABLE email_stats
ADD COLUMN generated_sent_date DATE AS (DATE(date_sent)) VIRTUAL COMMENT '(DC2Type:generated)';`

The COMMENT '(DC2Type:generated)' is optional and i think that varchar(255) is actually not necessary for most domains so maybe you can reduce it to varchar(100) or something but this is most likely neglectable.

This is not a fix but a workaround
