### ISSUE TITLE
PHPStan should check for generics if possible.

### ISSUE THREAD

**Issue by biozshock** [mautic/mautic#11708]
### Mautic Version

5.0.x series

### PHP version

8.0.x

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After merging #11587 PHPStan no longer checks for generics. https://github.com/mautic/mautic/pull/11587/files#diff-0361f0c81f363476ddc6f44ab36fcbe66ee685d5f4c2a46b054924591544b766R8

### How can we reproduce this issue?

Step 1: Run PHPStan.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
@biozshock I was fighting with Doctrine's repositories and couldn't found a clean way how to write the typehint. If you'll find a way please let me know!

**Comment by biozshock** [comment]
@escopecz Made that in 2 of my projects. Will see if i can reproduce it here.
