### ISSUE TITLE
IE 10 trying to save asset with asset ID+alias name as filename

### ISSUE THREAD

**Issue by maxitine** [mautic/mautic#1170]
When using Win 8.1 + IE 10 with Mautic, The download action was trying to save assets with a name of "asset ID + alias name" instead of original file name. 

This only happen with IE. Testing with Opera and Firefox seems to have no problem.  I'm using a simplified Chinese version of Windows 8.1. 

Thanks.  

Max

**Comment by maxitine** [comment]
This happened when the original filename is Simplified Chinese (double-bytes). Seems that download action could not parse the original file name properly so alias is used instead. In this case the downloaded files can not be opened since the file name and extension is not proper.

**Comment by alanhartless** [comment]
What do you have saved in your asset table's original_file_name column?

**Comment by maxitine** [comment]
This stores the orginal Chinese filename properly. In fact the issues only exists with IE. Firefox, Opera and Chome seems to be working in the right way.

**Comment by maxitine** [comment]
original_file_name column and tile column holds the same value as they are both auto generated when uploading the asset files.

**Comment by escopecz** [comment]
I'll close this issue with the result that Mautic support only IE versions by the Microsoft itself. That is IE11+:

https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support
