### ISSUE TITLE
Your bug title goes here!

### ISSUE THREAD

**Issue by DevBrunoo** [mautic/mautic#11702]
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

A bug happened! Problem on line 14

return (new 'PhpCsFixer\Config'())

### How can we reproduce this issue?

Step 1: Problem on line 14

return (new 'PhpCsFixer\Config'())

### Relevant log output

```shell
Problem on line 14

return (new 'PhpCsFixer\Config'()).
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
@DevBrunoo I'm closing this issue as it does not have title nor steps to reproduce. If you'll add it please comment here and we can reopen. At this state there is no one who can help you for the lack of information you provided.
