### ISSUE TITLE
Zoho integration pagination on field assignments not working

### ISSUE THREAD

**Issue by isoindisystems** [mautic/mautic#11713]
### Mautic Version

4.4.x series

### PHP version

8.0.25

### What happened?

In the ZOHO Integration Settings you cant switch to page 2,3,4 and so on when you want to edit the field mapping.

### How can we reproduce this issue?

Step 1: Goto to the Zoho integration settings
Step 2: Click on contacts assignments 
Step 3: Click on a page > 1

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by OzInFl** [comment]
FYI Seeing the same with the SugarCRM plugin, cant change pages in the field mappings tab as well..
Mautic 4.4.4
PHP 8.0.25
(apologies if this is in the wrong place - didnt figure it needed a new post, prob same issue)

Update - I applied this change and it has fixed the pagination:
https://forum.mautic.org/t/hubspot-mapping-error/25711/7
