### ISSUE TITLE
psr/simple-cache not compatible with symfony/cache

### ISSUE THREAD

**Issue by kreativekrise** [mautic/mautic#11720]
### Mautic Version

4.4.x series

### PHP version

8.0.25

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When you install Mautic in composer mode, it seems that psr/simple-cache ~3.0.0 was installed, which is not compatible with symfony/cache ~4.4.0.

A downgrade with `composer require psr/simple-cache ~2.0.0` seems to solve the problem.

### How can we reproduce this issue?

1. Follow Instructions at https://docs.mautic.org/en/setup/how-to-install-mautic/install-and-manage-mautic-with-composer
2. Login into Mautic
3. Open Settings -> Marketplace

### Relevant log output

```shell
[2022-11-17 15:17:41] mautic.CRITICAL: Uncaught PHP Exception LogicException: "psr/simple-cache 3.0+ is not compatible with this version of symfony/cache. Please upgrade symfony/cache to 6.0+ or downgrade psr/simple-cache to 1.x or 2.x."
 at /var/www/mautic/vendor/symfony/cache/Psr16Cache.php line 23 {"exception":"[object] (LogicException(code: 0): psr/simple-cache 3.0+ is not compatible with this version of symfony/cache.
 Please upgrade symfony/cache to 6.0+ or downgrade psr/simple-cache to 1.x or 2.x. at /var/www/mautic/vendor/symfony/cache/Psr16Cache.php:23)"} {"hostname":"REDACTED","pid":867093}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by trianity** [comment]
The same error occurs with us, with a fresh Mautic v.4.4.6 composer installation. PHP version 8.0.27

`[2023-02-11 18:11:39] mautic.CRITICAL: Uncaught PHP Exception LogicException: "psr/simple-cache 3.0+ is not compatible with this version of symfony/cache. Please upgrade symfony/cache to 6.0+ or downgrade psr/simple-cache to 1.x or 2.x." at /path-to-mautic/vendor/symfony/cache/Psr16Cache.php line 23 {"exception":"[object] (LogicException(code: 0): psr/simple-cache 3.0+ is not compatible with this version of symfony/cache. Please upgrade symfony/cache to 6.0+ or downgrade psr/simple-cache to 1.x or 2.x. at /path-to-mautic/vendor/symfony/cache/Psr16Cache.php:23)"} {"hostname":"vps.example.com","pid":29375}`

**Comment by tobsowo** [comment]
I am having this same error
`[2023-02-20 18:31:45] mautic.CRITICAL: Uncaught PHP Exception LogicException: "psr/simple-cache 3.0+ is not compatible with this version of symfony/cache. Please upgrade symfony/cache to 6.0+ or downgrade psr/simple-cache to 1.x or 2.x." at /var/www/html/vendor/symfony/cache/Psr16Cache.php line 23 {"exception":"[object] (LogicException(code: 0): psr/simple-cache 3.0+ is not compatible with this version of symfony/cache. Please upgrade symfony/cache to 6.0+ or downgrade psr/simple-cache to 1.x or 2.x. at /var/www/html/vendor/symfony/cache/Psr16Cache.php:23)"} {"hostname":"vps-27fe0396","pid":825}`

**Comment by dsp76** [comment]
Same with 4.4.7 release.

**Comment by mollux** [comment]
This is related to a dependency of Mautic: PhpSpreadsheet

In https://github.com/PHPOffice/PhpSpreadsheet/pull/3019, support was added for `psr/simple-cache:^3.0`.
Mautic has no explicit dependency for `psr/simple-cache`, and   `symfony/cache` doens't block installing `psr/simple-cache:^3.0`, so the latest version is used on composer install

to mitigate this issue, please downgrade the `phpoffice/phpspreadsheet` package:

`composer2 require phpoffice/phpspreadsheet:1.24.0 -w` 

this should downgrade `phpoffice/phpspreadsheet` to `1.24.0`, and `psr/simple-cache` to  `2.0`

example output:
```
./composer.json has been updated
Running composer update phpoffice/phpspreadsheet --with-dependencies
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
  - Downgrading phpoffice/phpspreadsheet (1.28.0 => 1.24.0)
  - Downgrading psr/simple-cache (3.0.0 => 2.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Downloading psr/simple-cache (2.0.0)
  - Downloading phpoffice/phpspreadsheet (1.24.0)
  - Downgrading psr/simple-cache (3.0.0 => 2.0.0): Extracting archive
  - Downgrading phpoffice/phpspreadsheet (1.28.0 => 1.24.0): Extracting archive
Package lightsaml/lightsaml is abandoned, you should avoid using it. Use litesaml/lightsaml instead.
Package misd/phone-number-bundle is abandoned, you should avoid using it. Use odolbeau/phone-number-bundle instead.
Package sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package symfony/inflector is abandoned, you should avoid using it. Use EnglishInflector from the String component instead.
Package symfony/security is abandoned, you should avoid using it. No replacement was suggested.
Package symfony/swiftmailer-bundle is abandoned, you should avoid using it. Use symfony/mailer instead.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
142 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Symfony recipes are disabled: "symfony/flex" not found in the root composer.json

No security vulnerability advisories found
```

The proper solution is to add a controlled list of dependency versions [like Drupal does](https://github.com/drupal/core-recommended).

can you confirm this mitigates the problem?

**Comment by trianity** [comment]
This solution also works:
Delete the contents of the ./vendor directory and run `composer install` on the modified composer.json file.

**Comment by escopecz** [comment]
@mollux shouldn't we add this library version into

https://github.com/mautic/mautic/blob/5.x/app/composer.json

using

https://getcomposer.org/doc/04-schema.md#conflict

statement?

**Comment by mollux** [comment]
@escopecz jup, indeed, I made 2 PR's (4.4 and 5.x)
