### ISSUE TITLE
Add select all records button (including those not visible in list)

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1172]
Hi,

It would be very great on the contact list to be able to **select all results instead of just select the results of the page** displayed.

It could be a little list:
- Select leads of this page (XXX contacts)
- Select all results (XXXX contacts)

![capture d ecran 2015-11-16 a 11 10 34](https://cloud.githubusercontent.com/assets/14075239/11179695/799186a0-8c55-11e5-8053-7fb891f52d6a.png)

N.

**Comment by alanhartless** [comment]
This would be awesome but would have to come with a worker queue feature as well since a database of millions of leads couldn't handle executing something on all leads in one action.

**Comment by forex4noobs** [comment]
This would be great. I have 20,000 contacts. Deleting 100 at a time would be a nightmare.
