### ISSUE TITLE
Button to add Dynamic Content in emails not available when using MJML theme

### ISSUE THREAD

**Issue by minholi** [mautic/mautic#11728]
### Mautic Version

4.4.x series

### PHP version

8.0.25

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Button to add Dynamic Content on MJML based emails is not showed. In the same instance when using HTML themes it works normally.

### How can we reproduce this issue?

Step 1: Create a email using Paprika as template.
Step 2: Look for the "Dynamic Content" button at the sidebar

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hello, there is a fix for this check the related forum post:
https://forum.mautic.org/t/mjml-dynamic-mjml-html/25560/40
