### ISSUE TITLE
Segment clone creates double records

### ISSUE THREAD

**Issue by mzagmajster** [mautic/mautic#11736]
### Mautic Version

4.4.x series

### PHP version

7.4.30

### What browsers are you seeing the problem on?

Firefox

### What happened?

When cloning the segment and then saving it, causes Mautic to create double (identical) records.

### How can we reproduce this issue?

Step 1: Create a segment1 with some filters and save it.
Step 2: Clone segment1 to segment2.
Step 3: On segment2 change name and public name.
Step 4: Save segment2.
Step 5: Search segment2 on segments list (there are two records present ).

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, we also have this issue.
It does only happen if a segment is not published!!!
