### ISSUE TITLE
Cloning marketing messages results in an error

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11731]
Mautic version: 5.x

When I try to clone an existing marketing message I am getting errors:

![screenshot-8080-salemcode8-mautic-ueaf2i2b47v ws-eu74 gitpod io-2022 11 18-11_30_17](https://user-images.githubusercontent.com/2930593/202695662-128579cc-1919-4852-8866-0cf5ff66816d.png)

_Originally posted by @SalemCode8 in https://github.com/mautic/mautic/issues/11668#issuecomment-1323475192_

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/11668, commit https://github.com/mautic/mautic/pull/11668/commits/f4b8900b44ccd9c3ebfb732ba10cd481ba641c5b
