### ISSUE TITLE
Dynamic Content block missing in GrapesJS builder

### ISSUE THREAD

**Issue by mzagmajster** [mautic/mautic#11737]
### Mautic Version

4.4.x series

### PHP version

7.4.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

According to this issue: #11290 there should Dynamic content block on email builder page, but its not. Running mautic version 4.4.4 I tried the following:

- using GrapeJS with my modifications
- using original dist folder from mautic release 4.4.4
- rebuild the entire GrapeJS dist folder by cloning repository, and executing yarn build

Each time I regenerated the assets, but still no luck, dynamic content block does not show.

I have tested this in Chrome and Firefox using normal and incognito mode.

Any suggestions, what else to try?

### How can we reproduce this issue?

Step 1: Create email with Brienz theme selected
Step 2: Save Email
Step 3: Open Builder
Step 4: If you scroll the GrapeJS panel you do not see any Dynamic content block

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by DalbertHab** [comment]
We have the exakt same issue with the mjml templates. The button shows up in html templates only.

**Comment by DalbertHab** [comment]
A possible solution or reason for the error is posted at the forums: https://forum.mautic.org/t/mjml-dynamic-mjml-html/25560/40?page=2

**Comment by jos0405** [comment]
I will close this now, if it doesn't answer your problem, please feel free to reopen.

**Comment by mzagmajster** [comment]
Well, it did not solve the issue in my case. And I also mentioned that I tried to rebuild original source as it was suggested on the link, but with no luck. When I test this on the latest version I will reopen the issue if it, persist
