### ISSUE TITLE
Campaign builder stops responding when clicking an event shortly after clicking save

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#11732]
### Mautic Version

4.4.1 series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

Campaign builder stops responding when clicking an event shortly after clicking save

### How can we reproduce this issue?

1. Open a campaign containing events
2. Click save
3. Promptly edit an event
4. Mautic will render a grey overlay and stop responding. A refresh is required to continue.

Please see loom: https://www.loom.com/share/814708c1f174449782ac8d570f162f93

### Relevant log output

```shell
I cannot find any mention of anything in the logs.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
That is weird.
