### ISSUE TITLE
Unable to edit fields ( native custom fields ) through the web or API

### ISSUE THREAD

**Issue by drptiago** [mautic/mautic#11744]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

When I try to edit a native custom field ( field used by the system as firstname, lastname) as publicly updatable nothing happens.

When I tried to do this with a custom field I created, works.

When I try trough API https://XXXXX/api/fields/contact/6/edit  also does not work "site offline"

Is a brand new instance.

### How can we reproduce this issue?

Step 1: In a brand new instance
Step 2: Goto custom fields
Step 3 : Edit firstname
Step 4 : Set as publicly updatable
Step 5 : save

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by bradjones1** [comment]
Is this specific to just this API endpoint? A site offline error seems to indicate a broader issue with your instance.
