### ISSUE TITLE
The service "mautic.dynamicContent.subscriber" has a dependency on a non-existent service "mautic.focus.helper.token".

### ISSUE THREAD

**Issue by PierreAmmeloot** [mautic/mautic#11751]
### Mautic Version

4.4.x series

### PHP version

7.4.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I load any page on Mautic I have 500 error and log error.

### How can we reproduce this issue?

Step 1: Install fresh Mautic 4.4.4 on server with filer
Step 2 : Load any Mautic page

### Relevant log output

```shell
PHP message: PHP Notice - Undefined variable: inline - in file /var/www/vhosts/XXX/web/offline.php - at line 77

PHP message: PHP Notice: Undefined variable: inline in /var/www/vhosts/XXX/web/offline.php on line 77

PHP message: Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException: The service "mautic.dynamicContent.subscriber" has a dependency on a non-existent service "mautic.focus.helper.token". - in file /var/www/vhosts/XXX/web/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php - at line 86'
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, can't reproduce it, 4.4.4 works like a charm. Could be environment related.
Can you plz ellaborate what "filer" is?

**Comment by escopecz** [comment]
Please check that you have plugins installed. FocusBundle is a plugin. To install all plugins run `bin/console mautic:plugins:install`

**Comment by tjosm** [comment]
I'm also getting this error,

`PHP message: PHP Notice - Undefined variable: inline - in file /var/www/vhosts/XXX/web/offline.php - at line 77`

After upgrading to v4.4.6 from command line.

**Comment by jacquesbh** [comment]
I had to require `mautic/plugin-focus` to fix this issue.

**Comment by jacquesbh** [comment]
do not stale

**Comment by RCheesley** [comment]
Closing this issue as it seems to be related to missing plugins. Feel free to request a re-open if that's not the case.
