### ISSUE TITLE
Support lead owner as an email token

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1176]
Hi,

Those lead fields exists i guess because **you can see them when you edit a lead**.
![capture d ecran 2015-11-18 a 12 21 50](https://cloud.githubusercontent.com/assets/14075239/11240065/04a1e140-8df0-11e5-8e07-eab879802ea6.png)

_______

But when you go on the **"manage fields" tab, you don't have them** (i need their name/alias to use them as leadfields values in emails).
![capture d ecran 2015-11-18 a 12 21 29](https://cloud.githubusercontent.com/assets/14075239/11240062/00b81810-8df0-11e5-8b18-047c80677c15.png)

Thanks a lot,

N.

**Comment by alanhartless** [comment]
Lead owner is not treated as a lead profile field and thus not listed under manage fields and not available for leadfield tokens.

If we added this feature, what would you want the token replaced with? The user's full name?

Thanks,
Alan

**Comment by npracht** [comment]
Hi @alanhartless ,

If you wanna make it correctly, you actually would need 3 fields:
* First name lead owner
* Last name lead owner
* Email address lead owner

**Those are the 3 you need to make a full dynamic signature into an email, those are the one needed to setup from label and from email address** also.

N.

**Comment by escopecz** [comment]
The lead/contact owner signature can be created since this PR: https://github.com/mautic/mautic/pull/1319

I'll close this issue. It can be re-opened when the PR above isn't a solution.

**Comment by jordan8037310** [comment]
I am still interested in the token that is not a {signature} token. For instance if I want to introduce myself, `Hello my name is Jordan, I...`, then I can't use any tokens that are available. Can we re-open this?

**Comment by jordan8037310** [comment]
#3079 is a newer ticket, linking there.

**Comment by isleshocky77** [comment]
@jordan8037310 That was my use-case, I've submitted a PR with testing.
