### ISSUE TITLE
Support setting lead owner as the "from" for automated emails

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1177]
Hi,

It would be great to be able to add leadfields into the advanced settings of the email.

* Eg 1: To **send automatically the email from the lead owner address email / first name / last name**. Add the leadowner lead fields in From name/From address/Reply to address.
* Eg 2: Add the **first name of the lead in the Subject**

![capture d ecran 2015-11-18 a 12 19 52](https://cloud.githubusercontent.com/assets/14075239/11239902/13e8ec62-8def-11e5-9643-c5be804666bf.png)

For that we'd also need to create the lead fields of the lead owner on the "manage fields" tab. I've open another topic here: [#1176](https://github.com/mautic/mautic/issues/1176)

N.

**Comment by alanhartless** [comment]
Subjects already support tokens so you should be able to add the lead's first name in the subject line now.

I can definitely see the benefit of automating the "from email" as the lead's owner.

**Comment by ccallahan23** [comment]
Hello, was this feature ever added?

**Comment by escopecz** [comment]
This PR should do what is described in this issue: https://github.com/mautic/mautic/pull/1319

It will be available in Mautic 1.3.0
