### ISSUE TITLE
Dynamic Content in emails (legacy builder)- default content is not saved properly

### ISSUE THREAD

**Issue by MadlenF** [mautic/mautic#11788]
### Mautic Version

4.4.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When using the legacy builder, the default version of the dynamic content is not saved properly.

Was already reported (but never solved)  in https://github.com/mautic/mautic/issues/10540

### How can we reproduce this issue?

Step 1: Disable GrapesJS plugin
Step 2: Create a new email with the legacy builder 
Step 3: Create a dynamic content
Step 4: Create the default version and a variation with filter
Step 5: Save the email
Step 6: See the default window is empty now (note: If you send the email now to test contacts, they will still get the correct version, it’s just in the editor where the default is not saved. Also seems okay in the database)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mabumusa1** [comment]
Fixed by #11887
