### ISSUE TITLE
Protocol of initial request poisons route matching for subsequent requests

### ISSUE THREAD

**Issue by bradjones1** [mautic/mautic#11799]
### Mautic Version

4.4.x series

### PHP version

8.0.26

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I have Mautic running in a Kubernetes cluster that is accessed both by public clients via a reverse proxy, as well as directly by other services within the internal network. As such, these internal services don't bother going through the reverse proxy.

Because I have a trusted reverse proxy in front of the application that will reject/overwrite any untrusted headers AND their IPs are not stable (Google Cloud) I set my trusted reverse proxy regex to `0.0.0.0/0`.

Anyway, the issue here is that when I now go to access Mautic directly, I get a `404`, presumably because Mautic is refusing to recognize the request unless it looks like it's from a reverse proxy. That seems wrong/excessive, in so far as this configuration option should really only affect whether we trust the `x-forwarded-for` header.

### How can we reproduce this issue?

1. Configure a trusted reverse proxy
2. Access the site without an `x-forwarded-proto` header.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by bradjones1** [comment]
I've been trying to reproduce this locally and it's a bit more insidious than I originally thought... it seems that the router (and presumably the cache? I'm extrapolating my Drupal and Symfony knowledge generally) gets poisoned to prefer either HTTP or HTTPS based on the first request it gets after a cache clear. So if I send an HTTP request, any following HTTP requests are successful, but if I then send one with `x-forwarded-proto: https`, I get no route match.

The same is true in the opposite case; if the first request is a proxied HTTPS request, then any following HTTP requests (as is the case with my API request) get no route match.

**Comment by RCheesley** [comment]
Hi @bradjones1 thanks for raising this. It sounds like this might be more of a configuration issue with your reverse proxy than a bug with Mautic. In that case, please can you search and post at https://forum.mautic.org/c/support, which is where we provide support?

Thanks!

**Comment by bradjones1** [comment]
I disagree; this is a WTF condition. Neither Symfony nor Drupal apps, which are my closest analogues, effectively lock themselves in to only working behind a reverse proxy when it has been added.
