### ISSUE TITLE
Bounce configuration results in 'Email Settings' error

### ISSUE THREAD

**Issue by ehillerbrand** [mautic/mautic#1179]
Entered a monitored email address with proper IMAP parameters in Monitored Inbox Settings.  

Clicked Test Connections and received a Success! message

Folders populated dropdown successfully in Bounce section.  New Configuration set to No.

Selected Folder.  Clicked Apply.  

Received Error message.

Folder drop down defaulted back to original values.

---

Reran use case setting New Configuration to Yes and entered IMAP settings.  Clicked Test Connections.  Received Success! message.  Folder contains drop down corresponding with monitored email address.

Selected Folder.  Entered Imap Settings.

Clicked Test.   Received Success! message.

Clicked Apply.  

Received Error message.

Folder drop down defaulted back to original values.

**Comment by alanhartless** [comment]
What's the error?

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to comment on this issue any time and I will re-open it again.

**Comment by luanfernandes** [comment]
Hi! I'm getting this too. The error is ' This value is not valid. '

**Comment by virlatinus** [comment]
I was also having the same issue.
What I did was that I first configured INBOX as Bounces and Unsubscribe folders and clicked apply. It all went well. Then I returned to the Email Settings page and the IMAP folders were all there. So I selected the correct Bounces and Unsubscribe folders and clicked Save and Close and it worked.

**Comment by Elextric** [comment]
Had exactly the same problem. Thanks to @virlatinus his work-around worked for this bug for me.

**Comment by zeretrelle** [comment]
This bug is still relevant. 

Mautic version 4.4.7

I had to use the workaround posted above and set INBOX as monitored folder,click  "Save", and then change to Bounces_Unsubscribe folder, click "Save".  This way it got properly saved.
