### ISSUE TITLE
Bug - Problem updating a existing leads with a form

### ISSUE THREAD

**Issue by alvinbenavides** [mautic/mautic#118]
I have two landing pages (LP), both in Wordpress using Mautic plugin to insert two different forms in each.

LP1, just collects email and create lead. LP2 collects name, email and phone and creates/update lead.

If a new lead submits LP2 evereithing is OK. If a known lead submits LP2 instead of redirecting the lead to the programmed url, the browser gets stuck in domain.com/mautic/form/submit?formId=2. If I reload page data is finally sent and lead is redirected to the programmed url.

No Mautic error but from web server:

[Mon Mar 02 01:21:41 2015] [warn] [client 190.141.4.243] mod_fcgid: stderr: PHP Catchable fatal error:  Argument 1 passed to Mautic\\LeadBundle\\EventListener\\LeadSubscriber::onLeadMerge() must be an instance of Mautic\\LeadBundle\\EventListener\\LeadMergeEvent, instance of Mautic\\LeadBundle\\Event\\LeadMergeEvent given in /var/www/vhosts/httpdocs/mautic/app/bundles/LeadBundle/EventListener/LeadSubscriber.php on line 253, referer: http://www...

**Comment by alanhartless** [comment]
Hi Alvin,

This has been reported and fixed in #96.

Thanks!
Alan
