### ISSUE TITLE
`MAUTIC_ENV` being a const makes environment management way too difficult

### ISSUE THREAD

**Issue by bradjones1** [mautic/mautic#11801]
### Mautic Version

5.0.x series

### PHP version

8.0.26

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I'm trying to get Mautic working in something of a 12-Factor App fashion for deployment to my cloud-native stack. I'm down the rabbit hole on trying to get structured logging working, which meant I needed to replace (not just add to) the Monolog extension configuration, which meant I had to override the environment-specific configuration file, which made me think, well, I'll just define my own.

That sort of, kind of works while you're clearing the caches at the command line, if you set `SYMFONY_ENV`. But then once you hit the site with web traffic, you go in through `index.php`, which sets the environment to `prod` in a perfunctory manner, but then the Mautic `AppKernel` sets it to... the value of a constant? Which is really difficult to set at runtime, e.g. with an environment variable.

All of which is a lot of work to try and change the logging configuration. I'm now trying to figure out the least hacky way to set the environment, and I'm also confused as to why the `.env.dist` that ships with Mautic sets this as an environment variable?

Curiously, `config_test.php` is the only instance of the environment variable being used, but it seems that in this case the test environment is for running tests and not like, local testing?

### How can we reproduce this issue?

1. Try to set the environment at runtime
2. Can't, it's a constant.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by bradjones1** [comment]
LOL ok... So just discovered that `index_dev.php` is a thing. So I think I'm expecting too much out of the runtime configuration of the application environment? I think this is a great opportunity to kill this model in 5.x and move toward Symfony's runtime component.

**Comment by RCheesley** [comment]
One for @mollux @escopecz et al to discuss! If you'd like to help with the Mautic 5 work @bradjones1 we'd appreciate your input!

**Comment by bradjones1** [comment]
My initial take is to defer to Symfony's default handling for this and use the kernel parameters, and back out of almost all uses of constants, especially in this context. I think the Runtime component would also help a lot with reducing the bespoke code here.

**Comment by escopecz** [comment]
index_dev.php is definitely a prehistoric way how to do this. I'd like to use the way Symfony apps should be using environments. Are you up for the task?

**Comment by bradjones1** [comment]
I don't have the personal bandwidth right now (in the middle of a product launch) but I am using Mautic in production and would like to see it improve. So I do plan to submit some code as I'm able. In the meantime I think it's helpful to document these items as I find them.

**Comment by mabumusa1** [comment]
I am doing some experiments in this area, keep it open
