### ISSUE TITLE
Send form results plaintext

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#1180]
At the moment it seems impossible to use the "send form results" function within the forms for sending the form results plain text. Some of our other systems (a ticketing system for example) can't deal well with HTML mail.

Currently, creating a new e-mail in mautic is a workaround, but having an option for the form results to be sent plain text would be awesome.

**Comment by wderuijter** [comment]
The ticket system shows the line breaks in the email as &#13;&#10;&#13;&#10;some text&#13;&#10;

**Comment by wderuijter** [comment]
Hmm... Can't seem to past this here.

**Comment by alanhartless** [comment]
The form results email should be getting auto-converted to plain text via https://github.com/mautic/mautic/blob/4176dccd760b0eba7d51623c16d3ff2f1077d53a/app/bundles/FormBundle/Helper/FormSubmitHelper.php#L57-L57. 

I sent an email and it has a text/plain part:

```
--_=_swift_v4_1450397432_b071bed49f18b7e3dd596be03e6efd1b_=_
Content-Type: text/plain;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable

EMAIL: test@test.com

--_=_swift_v4_1450397432_b071bed49f18b7e3dd596be03e6efd1b_=_
Content-Type: text/html;
 charset=utf-8
Content-Transfer-Encoding: quoted-printable

<p><strong>Email</strong>: test@test.com</p>```

Do you mean to send an email with no HTML part at all?

**Comment by alanhartless** [comment]
Thinking about it, there was an issue with some fields leading to HTML being added to the plain text data.  @escopecz was that fixed? I remember talking about it but now can't find a reference for it to save my life.

**Comment by escopecz** [comment]
@alanhartless I think you think this: https://github.com/mautic/mautic/pull/1208

But the `<br/>`s were added there by the PR so it shouldn't be the issue here. When I was testing it, I didn't notice there were any HTML elements in the plaintext part of the email.

**Comment by wderuijter** [comment]
@alanhartless The HTML mails get converted to plain text automatically. I understand it now. The problem is that enters/line breaks entered in a form's textarea show up in the plain text mails as <br/>. 
I've just tried this in 1.2.3

Before 1.2.3 the <br/>'s got encoding into weird strings, so it's getting better. I would prefer if there would be no HTML code in the plain text at all.

**Comment by escopecz** [comment]
@wderuijter there is no HTML in the plaintext email at all. If there is, then it is a bug. Please, provide us the email source code where we can see it and reproduce the problem. 

But maybe, it will be enough to say that there are 2 versions of the email. The first is plaintext, the second is HTML. The email client which doesn't know how to parse the HTML will render only the plaintext version and the other way around. So if you want only the plaintext version, ignore the HTML version. I'll mark this issue as closed. If you'll find a bug, we can reopen it.

**Comment by escopecz** [comment]
@wderuijter still has the issue with 1.2.3. More details at https://github.com/mautic/mautic/pull/1208

**Comment by wderuijter** [comment]
Is there a need for more information?
I could provide the source of the emails.

**Comment by escopecz** [comment]
Yes, the source would be helpful. We need the steps to recreate the issue.

**Comment by wderuijter** [comment]
I've added the source of the email in my google drive. [See the source of the mail](https://docs.google.com/document/d/16vEjfpmoCHY1ZZlN1uBNUF8T6LuIgwjJwqoelPvkmxM/edit?usp=sharing)

**Comment by dbhurley** [comment]
Resolved with new editor.
