### ISSUE TITLE
Unable to edit certain leads

### ISSUE THREAD

**Issue by maxitine** [mautic/mautic#1181]
With imported leads nothing happened for some (such as for lead ID 49) after I click on edit button.  The log is like this: 

[2015-11-19 08:26:23] mautic.CRITICAL: Uncaught PHP Exception Exception: "DateTime::__construct(): " at C:\wamp\apps\mautic\app\bundles\CoreBundle\Helper\DateTimeHelper.php line 87 {"exception":"[object] (Exception(code: 0): DateTime::__construct():  at C:\\wamp\\apps\\mautic\\app\\bundles\\CoreBundle\\Helper\\DateTimeHelper.php:87)"} []
[2015-11-19 08:26:23] mautic.ERROR: Fatal: DateTime::__construct():  - in file C:\wamp\apps\mautic\app\bundles\CoreBundle\Helper\DateTimeHelper.php - at line 87 [] []

I'm testing with imported leads with simplified chinese value. 

Thanks

Max

**Comment by maxitine** [comment]
After further test, I found this happened when the imported date field value is in Chinese. These value can be imported but cause errors later. would be good if this could be detected when importing to custom date field.

**Comment by escopecz** [comment]
@maxitine could you provide a CSV you've imported so we would be able to recreate the issue and fix it? Can be a dummy lead data.

**Comment by maxitine** [comment]
Since github does not support csv attachments, I change the file extension to txt. you can rename and test with this. The assigning date fields is imported to a date/time fields in lead table. 
[Uploading marketing sample.txt…]()

**Comment by maxitine** [comment]
Sorry to close this as I'm new to github. Re-opened now.

**Comment by escopecz** [comment]
I'm not able to download the file. It doesn't link to anywhere. Could you please try again? It doesn't matter if it has the txt extension.

**Comment by alanhartless** [comment]
You might have to link to it from another cloud service and/or just paste a snippet directly into the editor within Github's fenced code blocks https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks.

**Comment by maxitine** [comment]
[sample.txt](https://github.com/mautic/mautic/files/68289/sample.txt)

**Comment by maxitine** [comment]
[sample.txt](https://github.com/mautic/mautic/files/68295/sample.txt)

**Comment by escopecz** [comment]
The problem is in the date format:
```
2015年10月31日
```
If you'd want to quick-fix your imported leads, change the format to
```
2015-10-31
```
And you should be fine. We have to modify the import to ignore the date values with unknown formatting. Or throw an error message during the import? Not sure which option is better, but the date in such format cannot be imported.

**Comment by maxitine** [comment]
Thanks. Ignore record with such date value should be fine, just like the records with wrong email address.

**Comment by escopecz** [comment]
Another test case:
1. Create a date lead field with default value 20/07/1981
2. Try to edit a lead. 

It will fail with this error:
```
500 Internal Server Error - DateTime::__construct(): Failed to parse time string (20/07/1981) at position 0 (2): Unexpected character
```
