### ISSUE TITLE
I am getting 403 Forbidden  Access to this resource on the server is denied in Mautic

### ISSUE THREAD

**Issue by rizvism** [mautic/mautic#11810]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

I installed the updates and after the update got the this error, i deleted the folder from my control panel and copied back the files but still i got the same error.

### How can we reproduce this issue?

Step 1: this is the error to be solved

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, did you check if file permissions / ownership are fine?

**Comment by yoosinpaddy** [comment]
Also getting this issue when cloning from git to localhost. I have tried giving full permissions to everyone but still same error
