### ISSUE TITLE
Campaign builder is destroying built graph when...

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#1182]
### Steps to reproduce
1. Create a new campaign.
2. Open the Campaign Builder.
3. Create some basic tree graph from the events, link them together. Do not add a lead source. Just actions and decisions.
4. Close the builder.
5. Hit Apply.

Mautic will return an error message that a lead source is missing. When you open the Campaign Builder again, all events are in the top-left corner and the links between them are lost.

**Comment by wderuijter** [comment]
I've encountered the same issue.

**Comment by harman83in** [comment]
Is there an ETA for this?

**Comment by alanhartless** [comment]
@harman83in Test PR #1566 if you will. Thanks!
