### ISSUE TITLE
Send email to user point action

### ISSUE THREAD

**Issue by versadial** [mautic/mautic#1183]
Feature Request

If lead accumulates a certain number of points, have a trigger option that sends email notification to marketing or admin. Or leave open email option. So lead prospect does not get email, but Admin/Marketing gets notified that the lead reached a certain point value.

**Comment by npracht** [comment]
Hi, this is an important feature to notify anyone for a hot lead.

## Suggestion

1. In the **Point Triggers**, add a new type of **Event** --> `Email notification`
2. Open a popin with differents fields: `Title`, `Description`, `Subject`, `Message`, `To`, `CC`, `BCC`
The point 2 is clearly inspired by **Send form result** action in **Forms**

### Content of message field
It would be great to have the right to add in the content of the message:
* Any `{leadfield=alias}`
* Points
* Point history

**Comment by Robmobius** [comment]
I would love to see this feature included - seems a logical step for marketing automation

**Comment by npracht** [comment]
@escopecz i think it can be closed in favor of https://github.com/mautic/mautic/issues/2433 which is more complete.
