### ISSUE TITLE
UI Issue in Campaign Event View

### ISSUE THREAD

**Issue by akshansh1998** [mautic/mautic#11849]
### Mautic Version

4.4.x series

### PHP version

7.4.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

![image](https://user-images.githubusercontent.com/26520096/211132557-a32e330f-1585-439e-85be-70939b09493d.png)
There needs to be more spacing between the actions or decisions in the mautic campaign view. It sometimes gets confusing what the green and blue lines are and which decision/action it relates to. It took me sometime to understand it which I think is most of us.

### How can we reproduce this issue?

Visit your campaign performance view, where you can see actions and decision that got executed

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by akshansh1998** [comment]
I added some CSS to fix this, as in the picture below.
```
.campaign-event-list .list-group-item {
margin-bottom:10px;
}
```

![image](https://user-images.githubusercontent.com/26520096/211132599-2ceb6354-3f91-46e1-8626-537a822f6800.png)

**Comment by jos0405** [comment]
@akshansh1998 This is a nice update, can you make a PR?

**Comment by akshansh1998** [comment]
> @akshansh1998 This is a nice update, can you make a PR?

I have no experience in making PR to public repositories like this, Can you guide me?
