### ISSUE TITLE
RegExp and Contains filter does not work in Segments if the custom-field is a number

### ISSUE THREAD

**Issue by Moongazer** [mautic/mautic#11875]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Description for `regexp`:
If you use a regexp filter in segments on a custom field which is of type "Number", **ALL leads are added to this segment**. The reason is, that an expression value like `'^[1|2]$'` is casted to `float` (resulting in `0.0`), which submits a database-query like `SELECT * FROM leads WHERE my_testfield REGEXP 0`, returning everything (dangerous)!

Description for `contains`:
If you use a contains filter in segments on a custom field which is of type "Number", **some kind of random leads are added to the segment**. The reason is, that an expression value like `1,2'` is casted to `float` (resulting in `1.0`), which submits a database-query like `SELECT * FROM leads WHERE my_testfield LIKE "%1%"`, returning leads where the field-value is `1`, `91,` or `919`.

## Reproduce for segments:

- Create a custom field for contacts, e.g. Label: `My Test-Field`, Alias: `my_testfield`, Data Type: `Number`, Default: `0`, Precision: `0`, Required: `no`.
- Add randomly some numbers to existing lead-records, with numbers like `1, 2, 10, 91, 12, 200 and 919` (just to make sure that the expression does not look for `2` in `12`).

Reproduce for `regexp`:
- Create a segment, e.g. Name: `Regexp test`, Filter: Chose `My Test-Field`, Operator: `regexp`, Value: `^[1|2]$` (expecting the segment will only contain leads where the value is exactly  `1` or `2`).
- Run `mautic:segments:update` and see that all leads have been added to the segment (Query was `SELECT * FROM leads WHERE my_testfield REGEXP 0`, because value `^[1|2]$` was casted to `0`) (FAIL).

Reproduce for `contains`:
- Create a segment, e.g. Name: `Contains test`, Filter: Chose `My Test-Field`, Operator: `contains`, Value: `1,2` (expecting the segment will only contain leads where the value is exactly `1` or `2`).
- Run `mautic:segments:update` and see that leads have been added to the segment where `my_testfield` is `1, 91, or 919` (Query was `SELECT * FROM leads WHERE my_testfield LIKE '%1%'`, because value `1,2` was casted to `1`)  (FAIL).

## Now, testing these filters in campaigns:
![mautic-campaign-test-regexp](https://user-images.githubusercontent.com/1685510/212775033-e20acded-de4d-4eeb-845b-efeeb3be2629.png)

Using `regexp` in condition:
- Create a campaign, e.g. Name: `Regexp test`, add a segment containing all your leads followed by a condition filter: Chose `My Test-Field`, Operator: `regexp`, Value: `^[1|2]$` and if that is true, send an email (or add it to another test-segment or so)
- Run `mautic:campaigns:update` and `mautic:campaigns:trigger`, **this test was successful!** Regexp is working here (Query was `SELECT * FROM leads WHERE my_testfield REGEXP '^[1|2]$'`) (SUCCESS).

Using `contains` in condition:
- Change the above condition to `contains` and add `1,2` as value.
- Remove the previous added leads from `campaign_leads`
- Run `mautic:campaigns:update` and `mautic:campaigns:trigger`, this test fails also, no leads receiving an email (Query was `SELECT * FROM leads WHERE my_testfield LIKE '%1,2%'`, its not a real failure here, but for a number field I would expect to explode the string and using `IN (1,2)`) (KIND OF FAIL?!).

**Sum-up:**
- For segment filters the value of a condition is casted to the type of the custom-field (which is a number here), which obviously fails if the value is a string.
- The same RegExp as condition filter in campaigns is working like expected.
- The Contains condition in campaigns does somehow work, also it makes no sense to compare the string to number values like this.

**Further debugging description:**
I could not figure out where the casing happens, but in this code places the value `^[1|2]$` was casted to float already:
```
BaseFilerQueryBuilder::applyQuery()
$filterParameters = 0.0 (float)

ContactSegmentQueryBuilder::assembleContactsSegmentQueryBuilder()
$params['par1'] = 0.0 (float)
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mabumusa1** [comment]
Keep opened
