### ISSUE TITLE
SugarCRM/SuiteCRM integration: blank fields in form get populated with last value

### ISSUE THREAD

**Issue by pgorod** [mautic/mautic#1187]
Bug report: Using Mautic integration with SuiteCRM (the same API as SugarCRM), I created a simple form with 'First Name' and 'Email' fields. Added one action to "Push lead to integration".

The lead created in SuiteCRM includes a "Last Name" field that I never populated; I recognized the value that appears there is a 'Last name' of the previous lead I had created in Mautic dashboard.

Then I added a "Last name" field to the form. If I fill it, it gets pushed correctly to the CRM. 

However, if I leave the "Last name" field blank, the same thing happens: the lead gets pushed to the CRM with a value from the last lead created.

**Comment by alanhartless** [comment]
Are you testing this in the same browser session or is it happening across sessions/multiple user agents/sessions? What I'm wondering is if Mautic is tracking you as one lead via cookie.  When you submit a second time, it merges the information with the first lead leading to mixed details.

**Comment by pgorod** [comment]
Same browser session. I don't even close the form tab, i just 
1. open the form, enter a first_name and last_name, submit; 
2. and then enter just a first_name and leave last_name blank. The lead created in SuiteCRM appears with the new first_name, and the last_name is from the first submitted data, instead of blank as expected.

**Comment by alanhartless** [comment]
If you're using the same browser session, you're being tracked as the first lead when you submit the info of the second.  I bet the leads are getting merged in Mautic then sent to SuiteCRM.  Can you verify that by looking for the leads in Mautic after you submit the forms? 

You may want to try testing in anonymous browser sessions and/or different browsers.

**Comment by pgorod** [comment]
Yes, looking at it in Mautic I see the information is being collected correctly, but they are being aggregated under the same lead (I believe the link is made whenever I use the same email in the two form submissions). So this might be deliberate behavior, but it sure is unexpected (well - at least for me).
Of course this brings problems when integrating with SugarCRM/SuiteCRM because on that side, there is no merging, but a new lead gets created...
On the other hand, I saw this a lot because I was just exploring and testing, over and over with the same email. In real-life situations maybe this isn't going to happen a lot.

**Comment by escopecz** [comment]
Not sure what the result of this discussion is. @pgorod any suggestions? Or can we close this issue?

**Comment by pgorod** [comment]
For me, it's "solved", since I understood what was going on.

But I'm not so sure this issue doesn't need some attention, I have to leave it to your best judgment. 

1) Form re-submissions using the same email get merged in Mautic: do you users expect this and understand it?

2) Form re-submissions using the same email get merged in Mautic, but generate a second lead in SugarCRM/SuiteCRM. Is this a problem?

So - as far as I am concerned, you can close; as far being satisfied with the current behavior, I leave that to you, I'm not sufficiently into this whole thing to have an informed opinion. Thanks.

**Comment by escopecz** [comment]
I think the merging feature is the only way how to display all the actions the lead did over time. I wouldn't want to click to 5 different leads with the same information just to join the lead's history in my head. Also the question would be if I'd have 5 leads with the same email address, where would I record the lead actions like email opens and page hits? To one of them? Or all of them? 

I'll close this then.
