### ISSUE TITLE
Mailjet puts only ":" in lead_donotcontact.comment (after softbounces)

### ISSUE THREAD

**Issue by beetofly** [mautic/mautic#11888]
### Mautic Version

4.4.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

#### Problem in Mautic instances with mailjet: 

Mautic process the callback response of mailjet for softbounced emails currently so, that in the database field `comment` in the table `lead_donotcontact` only a colon appears / is persisted.

#### Step 1:

In a Mautic instance with mailjet send an email, for example, to a "softbounce simulator" or an email account, which you configured as "full".

#### Step 2: 

Wait until the response of mailjet for the softbounced email is back [Important: That can take up to three days (see also mailjet api documentation), because mailjet retries to send a softbounced email several times until the email will set to the status "softbounced" in mailjet and the callback to mautic will happen]

#### Step 3:

Open the table `lead_donotcontact` in the mautic database and you will see, that there is only a colon in the comment field of the softbounced email.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by beetofly** [comment]
I have already analysed the problem and will soon make a proposal to solve this problem via a pull request for this issue.

### Reason of this problem:
So far Mautic uses the mailjet data fields `error_related_to` : `error`.
The JSON mailjet response for these both data fields are currently empty for softbounced emails.
But in the JSON mailjet response are the additional fields "hard_bounce" (bool) and "comment" (text) included, which are currently ignored by mautic.

### So a possible solution for this problem:
I will include all relevant mailjet fields, so the "comment" field in "lead_donotcontact" will be
`HARD` : `error_related_to` : `error` : `comment` (if value of hard_bounce in JSON-Response of mailjet is true)
and
`SOFT` : `error_related_to` : `error` : `comment` (if value of hard_bounce in JSON-Response of mailjet is false)   

My pull request with the code changes that implements this solution proposal in mautic will appear shortly.

**Comment by Moongazer** [comment]
I think @Leuchtfeuer is already working on this

**Comment by RCheesley** [comment]
@ekkeguembel are your team working on this?

**Comment by beetofly** [comment]
@RCheesley PR for that issue is merged in 4.4.10

**Comment by beetofly** [comment]
Fixed for mautic 4 via PR Fixes #11888 for mailjet puts only : in lead_donotcontact.comment #11912 (in release 4.4.10)

**Comment by beetofly** [comment]
Fixed for mautic 4 via PR Fixes https://github.com/mautic/mautic/issues/11888 for mailjet puts only : in lead_donotcontact.comment https://github.com/mautic/mautic/pull/11912 (in release 4.4.10)
