### ISSUE TITLE
Cannot emeb stripe pricing table on landing page because of the builders

### ISSUE THREAD

**Issue by LalaRock** [mautic/mautic#11910]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

I have a problem to integrate stripe on a landing page in mautic. I would like to integrate this snippet in a mautic landing page:

```
<script async src="https://js.stripe.com/v3/pricing-table.js"></script>
<stripe-pricing-table pricing-table-id="prctbl_1MSGvoJcMHqHTYoTIVyL1cFb"
publishable-key="pk_test_Lq67Fg0UjiKpjmAYh3InJiri00Go5gF6Y8">
</stripe-pricing-table>
```
The first thing I tried to do was to copy my html code directly into the mautic mode code. The problem is that mautic delete immediatl the `<script></script>` tag after I pasted it in the code.

Then I tried to solve the problem by importing the code as a theme in mautic. But the result gives me a blank page.

I searched other solutions and I discovered that the problem comes by the builder. GrapesJS builder of mautic deletes the `<script></script>` tag automatically. So I disabled the plugin and I tried with the Legacy builder of mautic but now it's not the `<script></script>` tag but the `<stripe-pricing-table></stripe-pricing-table>` tag wich is deleted.

Does anyone know what is the reason of this issue and if he knows how to solve it.
Can another builder wich support the two tags be installed in mautic.

Thank you.

### How can we reproduce this issue?

Step 1:  enable the Grape JS builder in the plugins
Step 2:  copy this snippet in code mode and apply

```
<script async src="https://js.stripe.com/v3/pricing-table.js"></script>
<stripe-pricing-table pricing-table-id="prctbl_1MSGvoJcMHqHTYoTIVyL1cFb"
publishable-key="pk_test_Lq67Fg0UjiKpjmAYh3InJiri00Go5gF6Y8">
</stripe-pricing-table>
```
Step 3 : disable the Grape JS builder in the plugins to use the Legacy builder
Step 4 : copy the snippet in code mode and apply

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
