### ISSUE TITLE
Base64 enabled breaks <mj-hero> 

### ISSUE THREAD

**Issue by TechBill** [mautic/mautic#11941]
### Mautic Version

4.4.x series

### PHP version

7.4.+

### What browsers are you seeing the problem on?

Not relevant

### What happened?

if mj-hero is used in email template with Base64 enabled, it breaks it with a blank area where mj-hero goes at

MJML template in Mautic 
![Screenshot 2023-02-08 at 12 55 09 PM](https://user-images.githubusercontent.com/945103/217625500-4771484e-20f5-4a01-a59d-18b403feaca3.jpg)

Email body result with Base64 enabled (missing hero at top)
![Screenshot 2023-02-08 at 12 54 37 PM](https://user-images.githubusercontent.com/945103/217625586-61aa7cdb-fbe0-4f0a-b3f6-d867a013d7c0.jpg)

### How can we reproduce this issue?

Go to https://mjml.io/try-it-live/-Yj9Gq8wG
Copy and paste mjml code into Mautic 
Send example email to yourself ... review example .. does hero display or missing?
Enable Base64 in Mautic -> Configuration -> Email
Send example email to yourself .. review and does hero display or missing?

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by TechBill** [comment]
Email result with Base64 disabled in configuration 
![Screenshot 2023-02-08 at 12 57 55 PM](https://user-images.githubusercontent.com/945103/217626019-61a97941-bae1-4375-859a-36e313937ca0.jpg)

**Comment by RCheesley** [comment]
@techbill is this still a problem?

**Comment by TechBill** [comment]
I haven't use Base64 for awhile now and problem with Base64 that it would often work fine in Example or email sent using Example button but failed when an actual campaign email was sent out to 6,000 + subscribers which has been an embarrassment to our office. 

Since the latest outlook now just only block the transparent gif or any images that have tracking code attached to it so all other images appears in email without needing to click on "Allow pictures". This clickable banner now only appears if it detects an image with a tracking code attached to it. We decided to steer clear away from Base64 and never use it again.

**Comment by RCheesley** [comment]
Closing this old issue, feel free to request a re-open if it's still an issue.
