### ISSUE TITLE
Crons Stuck on error

### ISSUE THREAD

**Issue by Belgor** [mautic/mautic#1194]
Sometimes - i do not know why because it happens really ocasionally and on random leads happens that cron job stuck on error vhen trying execute event like "Add lead to list Leads list"

After that new cron job cannot be executed and have message like "Cron job already in process".
To get cron jobs runnig againt i have to use command with --force option and everything goes OK again

The messages on which cron stops is like this:

[Doctrine\ORM\ORMInvalidArgumentException]
  A new entity was found through the relationship 'Mautic\LeadBundle\Entity\ListLead#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #68054. To solve this issue: Either exp
  licitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

Alo similar thing happend even with capaign itself (but also ocasionaaly with random leads)
 [Doctrine\ORM\ORMInvalidArgumentException]
  A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#campaign' that was not configured to cascade persist operations for entity: Mautic\CampaignBundle\Entity\Campaign with ID #4. To solve this i
  ssue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

**Comment by escopecz** [comment]
Please, check if some [open PR](https://github.com/mautic/mautic/pulls) would fix this error. I found these which are similar:
https://github.com/mautic/mautic/pull/1100
https://github.com/mautic/mautic/pull/1087

**Comment by Belgor** [comment]
Thank You, i'll try to wait to update 1.2.3 :-)
Since that last issue happened is everythink OK again..
