### ISSUE TITLE
Subfields rendered in wrong order when using dependent fields

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11966]
Subfields are being rendered in wrong order.

1. Create a radio box with 3 chices: 1,2,3
2. Make a field depending on choices.
3. Assign a text field
4. Assign a second text field
5. Assign a URL.

See how URL will be in the middle of the choices. The order is broken.

![Screenshot 2023-02-10 at 11 48 45](https://user-images.githubusercontent.com/4246909/218074116-6435ba80-4342-4fcb-b8a4-d5a1977613dd.png)

_Originally posted by @jos0405 in https://github.com/mautic/mautic/issues/11898#issuecomment-1425619361_

**Comment by dsp76** [comment]
May be related? https://github.com/mautic/mautic/issues/12369

**Comment by b00y0h** [comment]
There is also no ability to order the subfields and this is a problem when using the API to display the form.

**Comment by RCheesley** [comment]
Pretty sure this is resolved in 5.x now so going to close this old bug report.
