### ISSUE TITLE
I cannot delete a decision node from the campaign builder

### ISSUE THREAD

**Issue by cuberoot** [mautic/mautic#1197]
I accidentally created an extra decision node in the campaign builder and I cannot delete it by clicking on the "X" button. 

I am using a self hosted copy of v1.2.2

**Comment by alanhartless** [comment]
What happens when you click on it? Does it disappear but come back after you reopen the campaign? or does click the X do nothing? If it does nothing, are there any JS errors or errors recorded in your app/logs ? (The days logs are also viewable in Configuration).

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to comment on this issue any time and I will re-open it again.

I think it might be also fixed by https://github.com/mautic/mautic/pull/1284
