### ISSUE TITLE
Global Search will sometimes give errors but will continue to work

### ISSUE THREAD

**Issue by JoshuaEstes** [mautic/mautic#11977]
🚀 PR to test which fixes this issue: #12436 

### Mautic Version

5.0.x series

### PHP version

8.0.26

### What browsers are you seeing the problem on?

Firefox
Chrome

### What happened?

<img width="1431" alt="219051145-8682f71e-fd4e-42c3-977a-e63a4819372c" src="https://user-images.githubusercontent.com/447419/219208640-8a72c80a-9c84-4567-8205-0d2dc37aa41a.png">

### How can we reproduce this issue?

GIVEN
* I am logged in
* and I am on any page
WHEN
* I click on the global search icon
* and type my search term
THEN
* I will sometimes see the error message "Your request could not be processed, please try again"

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by websaj** [comment]
same here "Your request could not be processed, please try again"

How can I fix that? Please help me

**Comment by shinde-rahul** [comment]
@RCheesley, Help me move this issue to **Needs Test**  tab.

**Comment by volha-pivavarchyk** [comment]
Could you please look at my [PR](https://github.com/mautic/mautic/pull/12125). PR displays an error message instead of a flash message in cases like this.
