### ISSUE TITLE
mautic:social:monitoring command missing in 5.x branch

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11975]
When trying to use the `mautic:social:monitoring` command on the 5.x branch it is unknown, but on the 4.4 branch it works fine.

To test:

1. Install Mautic on the 5.x branch (or use Gitpod)
2. When install is completed, run the command `ddev exec bin/console list `

This will get you a list of the available commands - notice that the `mautic:social:monitoring` command is missing from the list.

3. Run the same command by going to https://github.com/mautic/mautic under the code tab > change branch to 4.4 and then click the Gitpod link (assuming you use the Chrome extension) - do the same and notice that the command is present in the list.

**Comment by escopecz** [comment]
This is due to the Autowiring PR I did. The commands remained hard-wired and were not auto-configured. I'll remove the hard-wiring and write simple functional tests. It will be first test written for the MauticSocialBundle 🤦

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/11981
