### ISSUE TITLE
Behavior based smart list filters (email received, form submitted, url visited, asset downloaded, etc)

### ISSUE THREAD

**Issue by troelsfeodor** [mautic/mautic#1198]
I'd like to have more options for creating smart lists.
- Similar to "List membership" it would make sense to filter by "Email received" where you can select a specific email
- "Form submitted" would also be helpful

Those two seem pretty straightforward. Any other ideas?

**Comment by npracht** [comment]
+ URL visited.

**Comment by alanhartless** [comment]
I can see where this can be handy.  In some cases, you could use tagging to mimic a similar effect or a campaign with decisions/actions (which would really only help for this point moving forward and not for past actions).

The tricky part for smart filters is translating them into SQL in such a way that doesn't take forever to build the lists especially for databases with millions of leads or recorded actions such as page hits, form submissions, etc. The queries can get quite complicated depending on the number of filters and types of filters.

**Comment by npracht** [comment]
For you information, here is the list of what competitor can do. A very segmentation driven software, so very powerful.
In bold what i think being most important.

* Account attribute
* Contact attribute
* Campaign activity (qualify, open, click in a certain branch)
* Traffic source
* **Website activity (URL viewed,** ...)

![capture d ecran 2015-12-18 a 09 30 17](https://cloud.githubusercontent.com/assets/14075239/11892617/1c5da17a-a56a-11e5-8b9a-1bd6bc92d1ba.png)
![capture d ecran 2015-12-18 a 09 30 27](https://cloud.githubusercontent.com/assets/14075239/11892620/1c6255bc-a56a-11e5-8c8f-2f2d41f51705.png)
![capture d ecran 2015-12-18 a 09 30 49](https://cloud.githubusercontent.com/assets/14075239/11892618/1c603c1e-a56a-11e5-852b-b3f8a4156c2b.png)
![capture d ecran 2015-12-18 a 09 30 58](https://cloud.githubusercontent.com/assets/14075239/11892619/1c606216-a56a-11e5-96c8-40dd1797ce75.png)

**Comment by npracht** [comment]
A piece of answer there concerning the email activity (open): https://github.com/mautic/mautic/pull/1237

**Comment by npracht** [comment]
URL visited // Asset downloaded : https://github.com/mautic/mautic/pull/1567
Email received : https://github.com/mautic/mautic/pull/1237

**Comment by escopecz** [comment]
Some of the filters are prepared for testing here: https://github.com/mautic/mautic/pull/3477

This issue is a mess. I'll close it since I'm lost in what features are logged in other issue, which are done and which are remaining. If there is still some unique feature listed here, create a separate issue for it, please.
