### ISSUE TITLE
Hard coded path somewhere in the application

### ISSUE THREAD

**Issue by gkuyuk** [mautic/mautic#11987]
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Not relevant

### What happened?

 Hard coded path somewhere in the application causing site to go offline if the owner of the site changes in a shared hosting environment (ISPCONFIG). When the owner of the site is changed ispconfig moves the web folder to the new owners home causing the installation path change from /var/client1/web1/.... to /var/client2/web1/..... and after this change the site goes offline. 

### How can we reproduce this issue?

Step 1: Change the path to the installation or change the owner in ispconfig

### Relevant log output

```shell
[Thu Feb 16 17:45:36.822420 2023] [fcgid:warn] [pid 3688:tid 140689689818880] [client 24.12.52.46:42171] mod_fcgid: stderr: Error: Failed opening required '/var/www/clients/client1/web3/web/app/../var/cache/prod/appAppKernelProdContainer.php' (include_path='.:/usr/share/php') - in file /var/www/clients/client1/web3/web/vendor/symfony/http-kernel/Kernel.php - at line 611, referer: https://ea.emailcenters.com/s/login
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by cloudmaker97** [comment]
I have the same problem with plesk after moving from one to another domain, it just creates a new vhost and changes the path. Didn't found a workaround or fix yet for changing the path.

**Comment by cloudmaker97** [comment]
After a short research on my own i found, that the settings are saved in this file: `/app/config/local.php` where you can change the path.

**Comment by gkuyuk** [comment]
Thank you for pointing that out, still it sounds like a bug and would be much better to use a relative path (or detect the path wherever needed) to makethe application easily movable between clients. Again thanks for the information.

**Comment by jos0405** [comment]
Is it solved?
My money is on refreshing the cache.

**Comment by gkuyuk** [comment]
As mentioned in the discussion, it is hardcoded into the file /app/config/local.php refreshing the cache does not solve the issue. We need to get in there and modify the many hardcoded paths manually.

**Comment by dsp76** [comment]
Sure - as you can't edit the config through the frontend. However, I see this as a howto when moving an existing installation to another place. A couple of other directories also need to be updated.

The relative path is a good improvement probably.

**Comment by gkuyuk** [comment]
Yes a relative path would be a great update, since an account owner change in contral panels, such as pless/ispconfig/cpanel etc... would cause the path to change and end user may not be aware. Thanks for taking a minute to look at the ticket.
