### ISSUE TITLE
DEPRECATION - Remove pipedrive from Mautic 5

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#11983]
### Mautic Version

5.0.x series

### PHP version

no matter

### What happened?

Pipedrive plugin stops working. We need to remove it from mautic core and people can install alternative like https://github.com/Webmecanik/mautic-pipedrive-bundle from marketplace/composer.

### How can we reproduce this issue?

- [ ] remove plugin
- [ ] add information on deprecation list when releasing

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
PR to test: https://github.com/mautic/mautic/pull/12081
