### ISSUE TITLE
"Push to integration" mask does not show campaign & campaign member status dropdown

### ISSUE THREAD

**Issue by MadlenF** [mautic/mautic#11996]
### Mautic Version

4.4.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When opening the “push to integration” mask, either via Form Action or Campaign Action, it is not loading the Salesforce campaigns nor the Campaign Member Status.

![image](https://user-images.githubusercontent.com/87804194/220130117-0125c06f-497b-4da5-9c4f-ac524555b825.png)

### How can we reproduce this issue?

1. Create a Standalone-Form (this is also 100% applicable for Campaign Action)

2. Go to Actions and choose “Push to integration”

3. See that you can choose the Integration (in this case Salesforce)

4. Also see that the other two dropdown "Campaign" & "Campaign Member Status" do not appear

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by MadlenF** [comment]
Is solved by https://github.com/mautic/mautic/pull/12002

**Comment by jos0405** [comment]
Thank you @MadlenF  I'll close it in favor of above mentioned PR.
