### ISSUE TITLE
No warning about duplicate leads

### ISSUE THREAD

**Issue by automatyzuj** [mautic/mautic#12004]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

When I create a new lead and enter an existing email address, I don't see an warning that the contact already exists. It was visible for example on M4.1 under email field. 

Tested on 3 units on M4.4.5. 

### How can we reproduce this issue?

Step 1: Make some lead.
Step 2: Try make new lead in mautic with this same email address.

### Relevant log output

```shell
no logs.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by automatyzuj** [comment]
bump still exist on 4.4.7

**Comment by richmarks20** [comment]
still an issue

**Comment by RCheesley** [comment]
Closing this issue as I'm not able to reproduce a lack of warning about duplicate emails in 5.2.

![New-Contact-Mautic-12-09-2024_12_57_PM](https://github.com/user-attachments/assets/d33c4495-3fa4-47cb-8d56-32859cccfab2)
