### ISSUE TITLE
npm install leads to dependency problems: grunt-remove@0.1.0

### ISSUE THREAD

**Issue by adiux** [mautic/mautic#12007]
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

On the newest code I run `npm install`

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: grunt-remove@0.1.0
npm ERR! Found: grunt@1.5.3
npm ERR! node_modules/grunt
npm ERR!   dev grunt@"^1.5.3" from the root project
npm ERR!   peer grunt@">=0.4.2" from grunt-autoprefixer@3.0.4
npm ERR!   node_modules/grunt-autoprefixer
npm ERR!     dev grunt-autoprefixer@"^3.0.4" from the root project
npm ERR!   1 more (load-grunt-tasks)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer grunt@"~0.4.1" from grunt-remove@0.1.0
npm ERR! node_modules/grunt-remove
npm ERR!   dev grunt-remove@"^0.1.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: grunt@0.4.5
npm ERR! node_modules/grunt
npm ERR!   peer grunt@"~0.4.1" from grunt-remove@0.1.0
npm ERR!   node_modules/grunt-remove
npm ERR!     dev grunt-remove@"^0.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### How can we reproduce this issue?

Step 1:  load the latest code from the 5.x branch
Step 2: In the root folder run `npm install`. It will fail to install the dependencies.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by adiux** [comment]
I made a fix for the Gruntfile in the root folder. But I'm not sure how to test it. Where are the `grunt` commands used? 

In addition, I found that there are two Gruntfiles in the project. Both have the same content (and the same problem). Not sure which one is used, or why we have two:

One is in the root folder and the second one is in app/assets/scaffold/files/

**Comment by mollux** [comment]
@adiux at this point both are needed:
* the one in `app/assets/scaffold/files/` is used for composer based installs, where that file is scaffolder into the root of the composer project.

In the future one of those should become redundant. There is a CI check to ensure those files are kept in sync

**Comment by adiux** [comment]
@mollux so I would create a PR that fixes both?

**Comment by adiux** [comment]
There are multiple commands in the Gruntfile. But I can not see where they are run. So Im wondering if they are still used?

**Comment by escopecz** [comment]
Grunt is used to compile LESS files. See https://contribute.mautic.org/contributing-to-mautic/developer/local-environment-setup. It deserves some update I guess. Grunt is not the cool JS tool for some time. I think we are several generations of cool JS tools behind.

**Comment by adiux** [comment]
I think we should have a discussion about that soon (maybe v6). I guess this could be a good option since it seems to be the "Symfony way": https://symfony.com/doc/current/frontend.html
Moving to a package manager is a good first step for whatever comes next.

So we only use `grunt compile-less` as developers. That is what I also see in the Gruntfile. 

There is one other command that is giving this issue: 
https://github.com/mautic/mautic/blob/5.x/Gruntfile.js#L49

Based on the comment, it "remove prod's css files to force recompilation". I would have to install a new package that will do the same thing. But I dont know how to test it, or if it is even worth fixing. If it is not used. Maybe in some production pipeline or something like this?

**Comment by escopecz** [comment]
I think that the `remove` task can be removed. I've never used it personally and it's not used in any workflow AFAIK. There will be rarely need for that after we merge https://github.com/mautic/mautic/pull/11865 and it really does not work like that. The production assets won't be automatically re-created. The `bin/console mautic:assets:generate` command must be run to generate them.
