### ISSUE TITLE
Regexp with numbers as filter for Dynamic Content doesn't work

### ISSUE THREAD

**Issue by MadlenF** [mautic/mautic#12040]
### Mautic Version

4.4.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When using a regexp with numbers in a filter for dynamic content, the dynamic content will never show.

### How can we reproduce this issue?

Step 1: Create a dynamic content (not campaign based)
Step 2: Create custom field with the type text
Step 3: Edit a contact and fill in the custom field from above, e.g. "123"
Step 2: Choose a filter and a regexp e.g. ([^0-9]|^)123([^0-9]|$) 
Step 3: Include the DWC in your website / landing page
Step 4: See the DWC will never show up, although the test-contact matches the criteria

### Relevant log output

```shell
-
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
@MadlenF could you please try to save, reopen and save again? I have an issue, where the resaving suddenly fixes the issue: https://github.com/mautic/mautic/issues/12293
