### ISSUE TITLE
Save dashboard popup has missing language string on 5.x

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#12055]
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When saving a dashboard there is a language string missing on the popup.

### How can we reproduce this issue?

Step 1: Save dashboard

Error:

![screenshot-nimbusweb me-2023 03 03-12_16_27](https://user-images.githubusercontent.com/2930593/222725606-d4c5f416-5c6a-4d1b-b813-c5383e59924c.png)

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by LordRembo** [comment]
Added translation filter to the label ([see linked PR](https://github.com/mautic/mautic/pull/12250))

**Comment by RCheesley** [comment]
Awesome thanks, I'll go and test that!
