### ISSUE TITLE
Allow editing list email content

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#1205]
Yesterday I sent a newsletter about black friday talking about today. Now I have 1000 news suscribers and I cannot resend this emails to the news suscribers just because I cannot change some words.  If I copy the emails is not easy to select the news suscribers as above the clone option dont work (the cloned email is always empty)

Please, I agree one email id is send only one time to each lead but let us edit the content without limitations (or to copy it).  

I know this can be made by campaings but...

Thx for all

**Comment by escopecz** [comment]
Possible now
