### ISSUE TITLE
Some configuration buttons are not displayed correctly

### ISSUE THREAD

**Issue by annamunk** [mautic/mautic#12056]
### Mautic Version

5.0.x series

### PHP version

8.0.2, 8.1.12

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

In Twig templates some YesNoButtonGroupType buttons are not displayed correctly, e.g. in Configuration -> System Settings or Email Settings, preview below. 
![settings_buttons](https://user-images.githubusercontent.com/102536220/222739626-3c6ac8cc-a8b6-42fb-8586-9bbca58f295b.jpg)

### How can we reproduce this issue?

Step 1: Open project with version 5.x.
Step 2: Go to Configuration. 
Step 3: Browse through the individual configuration tabs. In some, for example "Campaign Settings", the buttons are displayed as before. In other tabs, e.g. "System Settings", the buttons look different.

### Relevant log output

```shell
No relevant logs, browser console is clean.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
This supposed to fix it:
https://github.com/mautic/mautic/pull/11938
Can I close it?

**Comment by annamunk** [comment]
@jos0405 yes, all buttons are displayed correctly.
