### ISSUE TITLE
Inconsistency when handling contact field "State" imports

### ISSUE THREAD

**Issue by jmdunsing** [mautic/mautic#12060]
### Mautic Version

4.4.x series

### PHP version

7.4.32

### What happened?

When batch importing contacts via .csv files on the web app, the state contact field is allowed to be all-caps and mautic will import the contact. The state is shown on a location column on the web app at /s/contacts, but in the contacts edit page s/contacts/edit/{id} the state is not displayed. The state contact field is a drop down, so I assume that the api is rejecting the state because all-caps is not in the list.

FWIW, it appears that not all fields are tested (such as state) in the API test scripts.

 I decided to report this as a bug due to the inconsistency.

### How can we reproduce this issue?

Step 1: Use create batch contact API to import a contact with contact field state is all-caps, e.g. CALIFORNIA. This should produce an error response with 400 code

Step 2: Import the same list of contacts via batch import on the web app.

Step 3: Verify state is displayed in all-caps at /s/contacts location column

Step 4: You can also observe that State is not populated if you try to edit the contact.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the bug - would you be open to digging into a fix for this (and maybe adding a test?) :)

**Comment by jmdunsing** [comment]
I think I can dig into it, but I'm no expert with php. I am, however, eager to learn! Would you have some time to explain what to look for?
