### ISSUE TITLE
Campaign Decision "Request Dynamic Content" don't start

### ISSUE THREAD

**Issue by Fra-DS** [mautic/mautic#12062]
### Mautic Version

4.4.x series

### PHP version

7.4.29

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I use the Decision "**Request Dynamic Content**" in a campaign it doesn't fire the action, I have verified this malfunction in the campaign logs looking at the "Decision" tab after starting the campaign.

<img width="907" alt="Schermata 2023-03-07 alle 11 13 02" src="https://user-images.githubusercontent.com/127189407/223391925-a13691ae-4a3d-415f-8831-982f658f8fa2.png">

### How can we reproduce this issue?

---

I’m following the dynamic content documentation shown here for the use of dynamic content: https://mautic-documentation.readthedocs.io/en/latest/components/dynamic_web_content.html?highlight=request%20dynamic#creating-the-request

---
### Step 1

I created three dynamic contents: one by default and two variables:

<img width="1447" alt="Schermata 2023-03-07 alle 10 20 25" src="https://user-images.githubusercontent.com/127189407/223383919-172950c9-8b71-41c2-99d3-3921d243c982.png">

<img width="1446" alt="Schermata 2023-03-07 alle 10 41 26" src="https://user-images.githubusercontent.com/127189407/223384302-5836add1-5e7a-4cbd-8ee4-10b806262f2c.png">

<img width="1447" alt="Schermata 2023-03-07 alle 10 41 15" src="https://user-images.githubusercontent.com/127189407/223384307-f2eaaa36-ce47-4a80-80b7-ffc5bc9273fd.png">

---

### Step 2

I created a new campaign and then entered a "DWC request":

<img width="619" alt="Schermata 2023-03-07 alle 10 52 07" src="https://user-images.githubusercontent.com/127189407/223388362-f8c6b8a6-6e81-4ff5-8e8d-4e2f1601cdde.png">

---
### Step 3

I created a new mail template and then inserted a slot for the DWC adding these attributes:
- data-slot="dwc" 
- data-param-slot-name="dwc-test"

<img width="1680" alt="Schermata 2023-03-07 alle 10 51 37" src="https://user-images.githubusercontent.com/127189407/223389441-0fb4593d-4c55-423a-9897-622d1e57be4c.png">

---
### Step 4

I finished the campaign by adding a two filters, two "Push dynamic content" actions (details in screenshot below) and other two actions that send the email of the previous step:

<img width="1387" alt="Schermata 2023-03-07 alle 10 52 17" src="https://user-images.githubusercontent.com/127189407/223390221-465f32c8-d91b-4369-b89c-e06c88296987.png">

<img width="609" alt="Schermata 2023-03-07 alle 11 08 14" src="https://user-images.githubusercontent.com/127189407/223390764-39110f7d-3a63-49dd-bbe4-3f0f0dff8bfa.png">

---
### Step 5

I started the campaign but nothing happened as it stopped at the first step:

<img width="907" alt="Schermata 2023-03-07 alle 11 13 02" src="https://user-images.githubusercontent.com/127189407/223391925-a13691ae-4a3d-415f-8831-982f658f8fa2.png">

<img width="895" alt="Schermata 2023-03-07 alle 11 12 53" src="https://user-images.githubusercontent.com/127189407/223391928-c77a5781-bfd0-4865-98c9-8affb2bb4534.png">

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by linuxatico** [comment]
No news at all for this issue?
