### ISSUE TITLE
Email Template Builder gets stuck

### ISSUE THREAD

**Issue by mukadessharka** [mautic/mautic#12070]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

Hello guys, 
I'm dealing with mautic latency to open email builder for weeks now.
I'm trying to explain how the problem stands below, and if anybody has faced with it and has a solution, please let me know.

The current version of my installation is 3.1.2, and I was facing with latency on every module inside mautic. It takes too long to open the Contacts list or the Segments, or the Campaign list view. 
Even turning one page back takes way too long. 
So I decided to upgrade from 3 to the latest version that we have now(4.4.6). 
The situation didn't change much, the pages still take a while to load(at least less then before), but the Email Templates, as soon as you edit one of them and try to launch the Builder,  the page gets stuck, trying to open the email template and it takes at least 5 minutes for the **loading**  session to finish.

Please, let me know if there is any other solution related to this issue.

### How can we reproduce this issue?

1.  Load the Email module
2. Edit an existing email template
3. Open the Builder
4. The page gets stuck
![image](https://user-images.githubusercontent.com/89582811/224086135-b11cc394-4efa-462a-8d34-e12a6dcda979.png)
5. It takes more than 5 minutes for the loading sign to stop and giving me the chance to edit the template

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by PierreAmmeloot** [comment]
Hello @mukadessharka,

Can you use a new template GrapeJS compliant?

**Comment by mukadessharka** [comment]
Hi @PierreAmmeloot  
How can I do that? Can you give me some clues?

**Comment by jos0405** [comment]
Hello @mukadessharka 
Check the MJML docs here:
mjml.io
Here is Mautic specific a video that helps:
https://youtu.be/B6ABMjOY3ZU

I will close this for now, as this is not strictly a Mautic issue, most likely connected to your environment.
Maybe raise this topic in the forums if you did the research and still need help.
