### ISSUE TITLE
[LIST EMAIL] Plain text version is sending emails incorrectly

### ISSUE THREAD

**Issue by gpassarelli** [mautic/mautic#1207]
# Description #
I'm not sure how to describe this issue, but when you create a list email with a plain text version of it, the plain text version comes as the plain text version of all previously sent emails. Like this.

Your list contains 3 leads:
* Lead 1
* Lead 2 
* Lead 3

if the plain text version of the email is only the lead name, the leads will receive the plain text version like this:
**Lead:**
Lead 1
**Plain Text Email:**
Lead 1

**Lead:**
Lead 2
**Plain Text Email:**
Lead 1
Lead 2

**Lead:**
Lead 3
**Plain Text Email:**
Lead 1
Lead 2
Lead 3

# TEST #
To make this test easy, configure Mautic to send emails to mailtrap.io is easier to see the HTML version and Text Version of the email.

* Create a list with a sample leads
* Create a new List Email
* Create a plain text version for this email
* Configure the list email to send to that list
* Send the emails
* Check the plain text the last email you received, the content it will be the plain text version of all the previously sent emails

**Comment by gpassarelli** [comment]
OK, so I've made some other test and I've found out that if your select the size of the Batch to 1, this wont happen.

So what Happens is, that the plain text version, will be for all the emails in that batch.

**Comment by escopecz** [comment]
Not sure if this PR fixes your issue. Could you test it? https://github.com/mautic/mautic/pull/1210

**Comment by alanhartless** [comment]
Yea this should be fixed by #1210.  If you find otherwise, we'll reopen the ticket.
