### ISSUE TITLE
500 error in contact view after campaign trigger command

### ISSUE THREAD

**Issue by adiux** [mautic/mautic#12082]
### Mautic Version

5.0.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After a campaign event failed I get a 500er error and can not use Mautic anymore: 

"Key "errors" does not exist as the array is empty." at /var/www/html/app/bundles/LeadBundle/Views/Lead/lead.html.twig line 443

### How can we reproduce this issue?

Step 1:  Not sure how to make a campaign event fail on purpose but this twig template should be more resilient anyway.

### Relevant log output

```shell
"Key "errors" does not exist as the array is empty." at /var/www/html/app/bundles/LeadBundle/Views/Lead/lead.html.twig line 443
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Just came across this testing #11901 - thanks for reporting it @adiux and @annamunk .

Looks like a Twig related bug, hopefully not too challenging to get addressed!

**Comment by Ruffin12** [comment]
J'ai reproduit deux campagnes. la première campagne s'exécute avec succès mais dès que la seconde est enclenchée, il est impossible d'afficher les informations sur le contact. 
Ci-dessous le message du log: mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Key "errors" does not exist as the array is empty." at /var/www/html/mautic-5.x/app/bundles/LeadBundle/Resources/views/Lead/lead.html.twig line 443 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Key \"errors\" does not exist as the array is empty. at /var/www/html/mautic-5.x/app/bundles/LeadBundle/Resources/views/Lead/lead.html.twig:443)"} {"hostname":"serveur001","pid":28576}

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/12764. Please test so it gets released ASAP.
