### ISSUE TITLE
Cantact not upload

### ISSUE THREAD

**Issue by Ritesh421** [mautic/mautic#12086]
### Mautic Version

5.0.x series

### PHP version

8.0.52

### What browsers are you seeing the problem on?

Chrome

### What happened?

When I am uploading email list in Mautic, all emails are not getting uploaded in it.
I have uploaded a list of 40000 and only 18000 emails have been uploaded in it.
Why is this happening

### How can we reproduce this issue?

When I am uploading email list in Mautic, all emails are not getting uploaded in it.
I have uploaded a list of 40000 and only 18000 emails have been uploaded in it.
Why is this happening

### Relevant log output

```shell
When I am uploading email list in Mautic, all emails are not getting uploaded in it.
I have uploaded a list of 40000 and only 18000 emails have been uploaded in it.
Why is this happening
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by Ritesh421** [comment]
When I am uploading email list in Mautic, all emails are not getting uploaded in it.
I have uploaded a list of 40000 and only 18000 emails have been uploaded in it.
Why is this happening

**Comment by Ritesh421** [comment]
your support system is very bad no any support from your side

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
