### ISSUE TITLE
Html Code get scattered will pasting it to builder 

### ISSUE THREAD

**Issue by diti123456789** [mautic/mautic#12090]
### Mautic Version

5.0.x series

### PHP version

2.16.5

### What browsers are you seeing the problem on?

Chrome

### What happened?

HTML Code gets scattered will pasting it to the builder code section, even after multiple time of edits, codes get restored, again and again
![screenshot-crm2 cedcommerce com-2023 03 15-19_18_27](https://user-images.githubusercontent.com/128031902/225560617-bf61672a-4a65-45f9-8ed4-13e1ea80acd9.png)

![Screenshot (289)](https://user-images.githubusercontent.com/128031902/225562231-aea79d7d-889f-46d6-af21-5b2c81ebb557.png)

### How can we reproduce this issue?

![Screenshot (289)](https://user-images.githubusercontent.com/128031902/225564824-e1f5ffb5-6f20-4cc1-bec7-0cbcaa10de64.png)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
I'm sorry, but Mautic 2.16 is no longer supported, I suggest to upgrade to Mautic 3, and then to Mautic 4, cause Mautic 5 is coming soon.
