### ISSUE TITLE
[Feature request] Ability to specify where to send test email

### ISSUE THREAD

**Issue by troelsfeodor** [mautic/mautic#1209]
It's a highly missed feature to be able to send a test email to other's than yourself. Therefore it should be possible to enter email addresses to send the test to (e.g. by comma separation).

**Comment by alanhartless** [comment]
I can see where this would be helpful especially if sending to 3rd party email analyzing service.  As a work around, you can temporary change your email in the profile then change it back but a bit of a pain I know!

**Comment by escopecz** [comment]
I'll close this issue as duplicate of https://github.com/mautic/mautic/issues/1447. This issue is older, but the new one has a better description and active discussion.
