### ISSUE TITLE
Bug #11061 (Fix campaign looping issue) is still in 4.4.7, Fix #11318 needs to be applied to 4.4x branch

### ISSUE THREAD

**Issue by ludovicfourrage** [mautic/mautic#12097]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

We are experiencing the infinite loop campaign bug described here [https://github.com/mautic/mautic/issues/11061](https://github.com/mautic/mautic/issues/11061) which prevents our customers from re-enrolling in our campaigns.

There is a fix that has been merged into the 5.x branch [https://github.com/mautic/mautic/pull/11318](https://github.com/mautic/mautic/pull/11318), but not in the 4.4x branch, and would be very useful.

Right now we are using the --max-contacts=500 option to workaround the cron infinite execution, but this flag doesn't fix the bug it simply allows mautic:campaigns:update to bail. The new contacts that should be added to the campaign are still ignored.

Thank you in advance for bringing the [https://github.com/mautic/mautic/pull/11318](https://github.com/mautic/mautic/pull/11318) fix to the 4.4x branch!

### How can we reproduce this issue?

As per [https://github.com/mautic/mautic/issues/11061](https://github.com/mautic/mautic/issues/11061).

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
Hi, do you have experience with git? The commits from the M5 just need to be cherry-picked. So something like:
1. `git checkout 4.4`
2. `git checkout -b fixing-campaign-loop-m4`
3. `git cherry-pick 860815643f5c090626d55071d59e3eb879929e28` (repeat for all 5 commits in https://github.com/mautic/mautic/pull/11318/commits except the merge commit)
4. `git push`

It may get more complicated if there will be some conflicts but any developer should be able to resolve the conflicts.

**Comment by ludovicfourrage** [comment]
> Hi, do you have experience with git? The commits from the M5 just need to be cherry-picked. So something like:
> 
> 1. `git checkout 4.4`
> 2. `git checkout -b fixing-campaign-loop-m4`
> 3. `git cherry-pick 860815643f5c090626d55071d59e3eb879929e28` (repeat for all 5 commits in https://github.com/mautic/mautic/pull/11318/commits except the merge commit)
> 4. `git push`
> 
> It may get more complicated if there will be some conflicts but any developer should be able to resolve the conflicts.

Thank you John. Will try today and let you know.

**Comment by ludovicfourrage** [comment]
> > Hi, do you have experience with git? The commits from the M5 just need to be cherry-picked. So something like:
> > 
> > 1. `git checkout 4.4`
> > 2. `git checkout -b fixing-campaign-loop-m4`
> > 3. `git cherry-pick 860815643f5c090626d55071d59e3eb879929e28` (repeat for all 5 commits in https://github.com/mautic/mautic/pull/11318/commits except the merge commit)
> > 4. `git push`
> > 
> > It may get more complicated if there will be some conflicts but any developer should be able to resolve the conflicts.
> 
> Thank you John. Will try today and let you know.

Looks like we made it work. Thank you!

**Comment by ludovicfourrage** [comment]
didn't mean to close the issue. The merge should still happen in 4.4.8 hopefully.

**Comment by escopecz** [comment]
Please post here a link to the pull request if you managed to create it.

**Comment by ludovicfourrage** [comment]
> Please post here a link to the pull request if you managed to create it.

I tried the cherry-pick method and couldn't figure it out, sorry. So I looked at the code changes and made the updates manually in our local install.

**Comment by martinstadelmann** [comment]
@ludovicfourrage I cherry-picked the commit on top of the 4.4 branch and opened a new PR in #13524.
