### ISSUE TITLE
Check for theme files exists before rendering

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#12107]
This is the cause of the issue https://github.com/mabumusa1/mautic/blob/a6f798157f2c2da296c93307c3b7b249ca4566d3/app/bundles/FormBundle/Model/FormModel.php#L789

**Comment by jos0405** [comment]
Can we close this?

**Comment by mabumusa1** [comment]
Not yet, I am still working on it. I am just keeping a record of all the issues I find.

Hopefully I will get the templating engine out of Mautic this week
