### ISSUE TITLE
Bug - Role rights error

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1213]
Hi,

I've created a new role that should only **view** leads (not rights on editing/creating/lists).
But id did not worked properly, with those rights i can edit lead and view lists.
___________
Here are the role settings
![capture d ecran 2015-11-30 a 08 42 00](https://cloud.githubusercontent.com/assets/14075239/11466276/0cbb6212-9740-11e5-8c90-4314e8b9ae9b.png)

Thanks a lot,

N.

**Comment by escopecz** [comment]
Answered at https://github.com/mautic/mautic/pull/1214

TL;DR: Lists doesn't have the view own permission. Lists can be public (global) / private instead.

**Comment by npracht** [comment]
Hi @escopecz & @alanhartless ,

What about the fact that **i can edit leads with those rights**? I didn't check the box **Leads/Edit**.
When i arrive on a lead page i shouldn't be able to click on **Edit** to change the info of the lead, i should only be able to see its information.

N.

**Comment by escopecz** [comment]
@npracht I created a role as you did, I created a new user with this role. When I log in as such user, I cannot edit lead nor create a new one. The buttons are not there.

**Comment by npracht** [comment]
Then that should be an error of cache maybe. I'll check and confirm.

--




*Norman Pracht Chief Marketing Officer Webmecanik +33 6 49 46 70 68*

2015-12-04 9:44 GMT+01:00 John Linhart <notifications@github.com>:

**Comment by npracht** [comment]
@escopecz ,

That was probably an issue of cache, i logged out cleaned cache and it works correctly.
Thanks a lot,

N.
