### ISSUE TITLE
weird crash on a certain IMAP mailbox password pattern

### ISSUE THREAD

**Issue by michield** [mautic/mautic#12142]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I got the infamous

    **The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator**

### How can we reproduce this issue?

Step 1: 

In config/local.php

```
    'monitored_email' => array(
        'general' => array(
            'address' => 'XXX',
            'host' => 'YYY',
            'port' => '993',
            'encryption' => '/ssl',
            'user' => 'ZZZ',
            'password' => '7t9V7G&C8Gh7AX%ttcV3M3%7FS@FSVaeECLZtV#k&&boGRrYt',
            'use_attachments' => ''
        ),

```
I've obviously rotated that password, so no worries about posting it here.

basically, my password generator created password with two %-signs and that totally crashed the system.

Step 2: load Mautic. It'll throw this error. Worst of all, no log entries in mautic/logs/XX or anywhere else. I had to dig into the apache logs, and find the line of code in the mautic app to find the cause of it.

Step 3: Be severely puzzled how a config password string seems to be thrown through a templating engine and "interpreted" instead of being taking **as a string** 

### Relevant log output

```shell
[Tue Mar 28 22:00:33.684521 2023] [php7:notice] [pid 534579] [client XXX] PHP Notice - Undefined variable: inline - in file /var/www/html/mautic/offline.php - at line 77
[Tue Mar 28 22:00:33.684733 2023] [php7:notice] [pid 534579] [client XXX] PHP Notice:  Undefined variable: inline in /var/www/html/mautic/offline.php on line 77
[Tue Mar 28 22:00:33.684797 2023] [php7:notice] [pid 534579] [client XXX] Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException: The parameter "ttcV3M3" must be defined. - in file /var/www/html/mautic/var/cache/prod/ContainerS8hv07p/appAppKernelProdContainer.php - at line 7142
[Tue Mar 28 22:00:37.121957 2023] [php7:notice] [pid 534581] [client XXX] PHP Notice - Undefined variable: inline - in file /var/www/html/mautic/offline.php - at line 77
[Tue Mar 28 22:00:37.122107 2023] [php7:notice] [pid 534581] [client XXX] PHP Notice:  Undefined variable: inline in /var/www/html/mautic/offline.php on line 77
[Tue Mar 28 22:00:37.122163 2023] [php7:notice] [pid 534581] [client XXX] Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException: The parameter "ttcV3M3" must be defined. - in file /var/www/html/mautic/var/cache/prod/ContainerS8hv07p/appAppKernelProdContainer.php - at line 7142
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mollux** [comment]
@michield 

this is due to how Symfony processes configuration parameters:

If some parameter value includes the `%` character, you need to escape it by adding another `%` so Symfony doesn't consider it a reference to a parameter name.

see https://symfony.com/doc/4.4/configuration.html#configuration-parameters

So not Mautic specific or a bug in Mautic

**Comment by michield** [comment]
ok, fair enough. I think it may catch someone else at some point, and it's a nasty one, as there is no output whatsoever, not even in logs. I don't even think about checking the % signs when I generate a password. Never occurred to me. 

Up to you to think it's worth fixing. or maybe passing up-stream? Some kind of "no-parse" option for parameters.

**Comment by dsp76** [comment]
May be related to https://github.com/mautic/mautic/issues/12256 ?

**Comment by dsp76** [comment]
This is the issue, were we collect all related issues: 
https://github.com/mautic/mautic/issues/13228

Please join discussion there. Thanks a lot!
