### ISSUE TITLE
Pixel not updating lead already created

### ISSUE THREAD

**Issue by Dcoutelle** [mautic/mautic#1215]
Way to re-create this bug

Create en new lead with custom field : 
/mtracking.gif?email=myemail@somewhere.com&session_id=1
Lead is created and session_id is set to 1
![pixel_step1](https://cloud.githubusercontent.com/assets/14074272/11467498/ba47f1f4-9748-11e5-9f0c-f1f88b313f75.png)

Update same lead, on same computer: 
/mtracking.gif?email=myemail@somewhere.com&session_id=2
![pixel_step1](https://cloud.githubusercontent.com/assets/14074272/11467498/ba47f1f4-9748-11e5-9f0c-f1f88b313f75.png)

Lead is not updated... You can reproduce this problem with any lead's field.

David

**Comment by alanhartless** [comment]
In order to update the lead using a tracking pixel, you need to set the lead field as "publicly updatable." Can you verify if that is the case here?

Thanks,
Alan

**Comment by Dcoutelle** [comment]
Hello Alan,

Yes, publicly updatable is toggled on "YES"

Thanks
David

**Comment by Dcoutelle** [comment]
Alan,

Did you reproduced this bug ?

David

**Comment by escopecz** [comment]
I cannot recreate this bug. The value in a custom field updates without any issue.

**Comment by alanhartless** [comment]
I just tried to reproduce this several times as well and the field was updated with the new value every time.  So maybe something is missing in the puzzle to reproduce this?

**Comment by escopecz** [comment]
Closing for the lack of feedback.
