### ISSUE TITLE
Focus with form return error 500

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#12155]
### Mautic Version

5.0.x series

### PHP version

8.0

### What happened?

If you tried to create modal focus with form, then If you use a form and select it, it returns a 500 error.

### How can we reproduce this issue?

Step 1: Create modal focus with form
Step 2: Choose form

### Relevant log output

```shell
Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "text.html.twig" (looked into: /var/www/html/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /var/www/html/vendor/symfony/twig-bridge/Resources/views/Form)." at /var/www/html/app/bundles/FormBundle/Resources/views/Builder/form.html.twig line 75
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mabumusa1** [comment]
@kuzmany are using a theme?

**Comment by kuzmany** [comment]
@mabumusa1 

This error comming from forms whatare generated from `doctrine:fixtures:load`
It's depraced theme (Mueve).

But If I use regular form with/without a supported theme, there is same kind of error::

`ncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "email.html.twig" `

..

**Comment by mabumusa1** [comment]
@kuzmany please make sure that you have commit e16f8609fa830e1af21f81d8633c6a9dbd559540 included in your code base. the loader uses a different format to leas themes now. so that might be the issue

**Comment by kuzmany** [comment]
@mabumusa1 yes, I am using last 5.x repo.  This issue is related to load twig for field types (text/email/button...)

**Comment by kylehon** [comment]
For folks who encounter same problem, here is a quick fix.

### Mautic Version
v5.0.0-alpha1
Fresh installed

### PHP version
8.1

### Solution
File `./app/bundles/FormBundle/Resources/views/Builder/form.html.twig`
Replace `{%- if theme is empty -%}` into `{%- if theme is not empty -%}`
2 occurrences.

**Comment by dsp76** [comment]
I tested it with 5.0.4 - Focus item, added a form. Focus item loaded and received form submits without issues. Probably its fixed. I close it. Let me know if it needs to be reopened.
