### ISSUE TITLE
Contact details are missing from the Contacts list

### ISSUE THREAD

**Issue by annamunk** [mautic/mautic#12162]
### Mautic Version

5.0.x series

### PHP version

8.0.2, 8.1.6

### What browsers are you seeing the problem on?

Firefox, Chrome, Not relevant

### What happened?

It seems that some contact details are missing from the Contacts list (/contacts). There is only email, points and last activity date, even if the lead has other values filled in.
![contacts_list](https://user-images.githubusercontent.com/102536220/229775538-8e180597-fdae-49cf-8192-e6511c3cc2b8.jpg)

### How can we reproduce this issue?

Step 1: Open the current version 5.x locally or via Gitpod. 
Step 2: Register at least one contact with first name, last name, location and email address filled in.
Step 3: Check the Contacts list (/contacts). 

### Relevant log output

```shell
--No related logs--
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
Ready to test: https://github.com/mautic/mautic/pull/12182
