### ISSUE TITLE
mautic:email:send command process tryagain message returns error

### ISSUE THREAD

**Issue by jiang2013** [mautic/mautic#12160]
### Mautic Version

5.0.x series

### PHP version

8.0.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

For example, if you rename any email (such as a.message) in var/spool/ to a.message.tryagain and execute the mautic : email : send command, an error will be prompted: rename(): supplied resource is not a valid Stream-Context resource.
![image](https://user-images.githubusercontent.com/6244379/229482582-02af2d91-4d9a-4500-b1ab-ef9cc0107c73.png)
![image](https://user-images.githubusercontent.com/6244379/229483839-46d9fe9c-2de1-44e1-bd58-a3098a062b92.png)
this error line of code is rename($tmpFilename, $retryFilename, $handle);  the $handler is from fopen,  when use get_resource_type($handler),  it's return 'stream' ,not 'stream-context'.I don't know how to deal with it. Should I remove this third parameter?

### How can we reproduce this issue?

Step 1: Go to the  var/spool/ directory, rename a message(a.message) to a.message.tryagain
Step 2:  in the terminal run php bin/console mautic:email:send

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by fabiomlferreira** [comment]
I have exactly the same problem. Any solution?

**Comment by jiang2013** [comment]
I removed the third parameters in the tryAgain condition.  just changed the  rename($tmpFilename, $retryFilename, $handle); to  rename($tmpFilename, $retryFilename);  but i'm not sure is right or not😅

**Comment by dsp76** [comment]
From reading your issue I can't find out if you are trying to achieve something special and need support for finishing it (this would be better done in the forum) - or if a standard feature in Mautic is broken?

**Comment by RCheesley** [comment]
I don't actually think this is a bug that Mautic needs to address - it's doing something quite specific (renaming files in the spool) which isn't supported. So in the future this is one for https://forum.mautic.org.
