### ISSUE TITLE
Company segment filter is changed to contact on save

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#12178]
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Chrome

### What happened?

When I create a filter with the company city, it looks like this:

![screenshot-8080-escopecz-mautic-g0dz07yknl6 ws-eu93 gitpod io-2023 04 05-23_31_22](https://user-images.githubusercontent.com/2930593/230226204-ca19989b-c5c8-495c-8247-2951447d6869.png)

When I have saved the segment it visually reverts to the image for a contact's city:

![screenshot-8080-escopecz-mautic-g0dz07yknl6 ws-eu93 gitpod io-2023 04 05-23_31_33](https://user-images.githubusercontent.com/2930593/230226248-52b012e6-8b07-4a86-9d95-0d6889cbaa80.png)

### How can we reproduce this issue?

Step 1: create a company city segment filter
2. Save the segment
3. View the filter. Its a contact city filter now

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by LordRembo** [comment]
found the problem, will add a PR for it
