### ISSUE TITLE
Contact lists are broken in 5.x

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#12176]
Something is broken with contact lists which is resulting in information not being displayed in the line entry.

Tested on 5.x and several other PRs, using the default data. The information (e.g. first and last name) is present on the contact field, just not showing in the list.

![screenshot-8080-escopecz-mautic-kswyij2mf78 ws-eu93 gitpod io-2023 04 06-00_03_54](https://user-images.githubusercontent.com/2930593/230231045-5e8a5b65-0420-4bb5-9135-f7a9fabf2f09.png)

_Originally posted by @RCheesley in https://github.com/mautic/mautic/pull/12171#pullrequestreview-1373843663_

**Comment by RCheesley** [comment]
Closing as a duplicate of https://github.com/mautic/mautic/issues/12162

**Comment by LordRembo** [comment]
For completion sake, this was fixed (&merged) here: https://github.com/mautic/mautic/pull/12182

**Comment by LordRembo** [comment]
@RCheesley Is it possible to also mark this ticket as closed? Would be great if it can be removed from the buglist so it doesn't clutter it.

**Comment by RCheesley** [comment]
Thanks @LordRembo ... goodness knows why I did not close it after posting the comment, probably got distracted 🙄
