### ISSUE TITLE
Embed date-picker into forms for browsers that do not support html5 date fields

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1217]
Hi guys,

The **date format form input** does not works properly with **many browsers** (IE, Firefox, Safari).
http://caniuse.com/#search=date
![capture d ecran 2015-12-01 a 12 05 36](https://cloud.githubusercontent.com/assets/14075239/11499146/2cdd84e6-9824-11e5-9c95-a475a69efc8a.png)

I don't know what could be an alternative, i've find a **JS library which is much more supported** :)
http://api.jqueryui.com/datepicker/#entry-examples
![capture d ecran 2015-12-01 a 12 09 43](https://cloud.githubusercontent.com/assets/14075239/11499178/74a8146c-9824-11e5-9f4d-a914d02c97fb.png)

What do you think about that?

N.

**Comment by escopecz** [comment]
Yes, the date/time field has to be solved by a JS library, because the HTML5 support is still poor in the major browsers. I'd prefer more some library without jQuery dependency. This library will have to be loaded into the embedded websites. No need to load the whole jQuery for it. It could also cause JS conflicts.

**Comment by npracht** [comment]
Hi @escopecz ,

You're right, good point. It was just an idea, you know i'm not very technical (not a dev), i wanted to help by searching a little bit :)

N.

**Comment by alanhartless** [comment]
I'm hesitant to embed a 3rd party JS  date picker library simply because it can get complicated to prevent JS conflicts and CSS conflicts in all the different sites out there. Plus people will want them styled to match their site and that adds a layer of complexity.

**Comment by robwent** [comment]
There is a shim available which will only add a picker to browsers that don't support it.

https://github.com/aFarkas/webshim

Depreciated though.
