### ISSUE TITLE
Mautic 4.4.6 Custom Preference Center

### ISSUE THREAD

**Issue by wcomartin** [mautic/mautic#12202]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I cannot get a Custom Preference Center Landing Page to work, 

I have set the Email Unsubscribe Settings as such, 
![image](https://user-images.githubusercontent.com/2801793/231195408-94cc6aa3-0ea5-4d8f-87ba-683c1d2ed3e8.png)

I have set a Landing page as Preference Center Page
![image](https://user-images.githubusercontent.com/2801793/231194583-e45c130a-53d6-4219-b77c-ee1f7f9e6327.png)

When I set the email to use this page as the Preference Center Page, it still shows the default.
![image](https://user-images.githubusercontent.com/2801793/231194673-5a15c3f1-d411-44f5-a41a-008db34078ca.png)

Is there a setting I am missing?

Also when I open the editor for the Landing Page it doesn't show the extra Preference Center Blocks as described in the documentation.

### How can we reproduce this issue?

Step 1: Create Landing Page set as Preference Center
Step 2: Create Email with Preference Center Page set to newly created Landing Page
Step 3: Click Unsubscribe in Email

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hello,

Can you show your landing page ? How it is built ?
I guess you forgot to insert a validation button slot or something mandatory like that.

**Comment by wcomartin** [comment]
Thank you for your help, I was missing the Save button, 

![image](https://user-images.githubusercontent.com/2801793/231198007-4f620267-b796-409e-afc6-38d81f3e062f.png)
