### ISSUE TITLE
DDEV needs upload_dir set

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#12244]
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When starting DDEV locally on a Mac, the following message is shown:

> You have mutagen enabled and your 'php' project type doesn't have an upload_dir set. 
> For faster startup and less disk usage,
> set upload_dir to where your user-generated files are stored. 

This relates to: https://ddev.readthedocs.io/en/latest/users/install/performance/#filesystem-performance

We should add the upload_dir to the DDEV config.

Adding this here as a good first issue for someone to pick up and make a PR from!

### How can we reproduce this issue?

Step 1: On a mac, clone the repo and cd into the directory
Step 2: (assuming you have Docker/Colima and DDEV set up) type ddev start and you will see the warning notice.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by nox1134** [comment]
Hi @RCheesley! I'd like to work on this issue. 
Could you please assign the issue to me?

**Comment by RCheesley** [comment]
Hi @nox1134 for sure.

Please check our docs here: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests and use the 5.x branch.

We should specify the directories which contain user uploaded materials as outlined here: https://ddev.readthedocs.io/en/latest/users/install/performance/#mutagen-and-user-generated-uploads - in Mautic 5 these are:

- media/files
- media/images

I think those are the only locations but just cc'ing @mollux in case I missed any edge cases (maybe dashboards might be considered user data but not sure?)
