### ISSUE TITLE
 Variable list does not exist edit form

### ISSUE THREAD

**Issue by tomekkowalczyk** [mautic/mautic#12241]
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

 Variable \"list\" does not exist.

### How can we reproduce this issue?

Step 1:  Enter page https://mautic.ddev.site/index_dev.php/s/forms/edit/[id_form]

### Relevant log output

```shell
[2023-04-20 10:16:19] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "list" does not exist." at /var/www/html/app/bundles/FormBundle/Resources/views/Field/group.html.twig line 229 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"list\" does not exist. at /var/www/html/app/bundles/FormBundle/Resources/views/Field/group.html.twig:229)
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by LordRembo** [comment]
~~This is a duplicate of #12208 as well (when adding multiple select)
The fix for the undefined `list` is described in there (an extra check on a variable), but that just exposes a bigger underlying problem.~~

**Comment by LordRembo** [comment]
~~I'll make a PR to fix the `list` problem specifically, and maybe someone else can tackle the other problem in 12208~~

**Comment by LordRembo** [comment]
~~Just so we're on the same page: this issue only happens on forms that include a certain type of field, right? I can't reproduce it on just any form, I've only seen it when certain custom fields are used (see #12208)~~

**Comment by LordRembo** [comment]
My bad, similar issue but somewhere else. Taking a look and will make a PR if I find it

**Comment by LordRembo** [comment]
How did you actually get this error? I can't reproduce it.
I made a PR which adds a check for the list to exist but the fields have validation, so I don't see how you'd get a non-existing list.

**Comment by LordRembo** [comment]
@tomekkowalczyk Can you tell me how you encountered the error (eg. what fields do yo have in the form, …)? I'm reasonably sure the PR I made fixes this issue but I can't reproduce it locally.

**Comment by escopecz** [comment]
@tomekkowalczyk please tell us how to reproduce this issue. There are people spending their time on fixing your issue that no one else can reproduce. There is a [fix](https://github.com/mautic/mautic/pull/12252) for it ready that only you can test. Please be respectful of such amazing people's time and let's get this resolved.

**Comment by LordRembo** [comment]
still relevant I think

**Comment by LordRembo** [comment]
Ah, no, the PR that fixes this is no longer relevant, as the code change also occured in a merge that was applied later. So this issue could be closed.

**Comment by RCheesley** [comment]
@tomekkowalczyk due to the lack of response and people trying to fix this bug but not getting any replies, I'm going to go ahead and assume that it's resolved. If not, please request a re-open. Thanks everyone for trying to figure it out!
