### ISSUE TITLE
Bug - Smartlist missing contacts

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1225]
Hi,

Contacts are not automatically added to the smart list according to their value in a field. Please check attachment.

Filter settings:
![capture d ecran 2015-12-07 a 15 58 00](https://cloud.githubusercontent.com/assets/14075239/11630421/d0f05530-9cfd-11e5-819f-3150bcb3793f.png)

Lead value:
![capture d ecran 2015-12-07 a 15 58 16](https://cloud.githubusercontent.com/assets/14075239/11630419/d0e67bb4-9cfd-11e5-98cc-4f8ddc2d1422.png)

List results:
![capture d ecran 2015-12-07 a 15 58 36](https://cloud.githubusercontent.com/assets/14075239/11630420/d0e7d0d6-9cfd-11e5-991e-1c6b05518b7f.png)

List filter
![capture d ecran 2015-12-07 a 15 58 47](https://cloud.githubusercontent.com/assets/14075239/11630418/d0e66caa-9cfd-11e5-8f82-aaf9ef44a5e4.png)

Could you help ?

N.

**Comment by npracht** [comment]
Hi,

We you able to reproduce ? Do you need more information ?

N.

**Comment by escopecz** [comment]
Just to confirm, your cron for updating lead list is working? What is the output of `php app/console mautic:list:update` command?

**Comment by Dcoutelle** [comment]
Hello John,

on php app/console mautic:list:update we have this output:
Redéfinition des prospects pour la liste 1
0 prospect(s) à ajouter aux lots 300
0 prospect(s) à retirer aux lots 300
0 prospect(s) concerné(s)

We have a cron every 5 min with app/console mautic:leadlists:update --env=prod command

David

**Comment by alanhartless** [comment]
Is there by any chance white space around the value for the lead and/or in the lead list filter? At face value, it looks fine and since it's a lead profile field, should be a super simple query that builds that list.  

Just to confirm, if you go to that lead's profile page and click the Lists button in the upper right hand page actions; the list is not selected right?

**Comment by npracht** [comment]
Hi @alanhartless ,

The list is not selected on the contact. I check if there is a white space on list filter and/or lead field.
Nothing there either.

An idea (i'm not a dev, but sometimes because i'm stupid i say different stuff and it can help. Let's try :p ) Could it be the "&" which could be stored in a different format like ```&amp;``` somewhere and the comparison fails ?

Tell me if there is any way to help you :)

N.

**Comment by escopecz** [comment]
I'll mark it as bug because it was reported 2 times (https://github.com/mautic/mautic/issues/1287)

**Comment by npracht** [comment]
I'm wondering if it's because of space or specific characters cause I'm using "&".

N.
