### ISSUE TITLE
{subject} gets injected into individual mail body

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#12259]
### Mautic Version

4.4.x series

### PHP version

8.0.x

### What happened?

When sending an individual mail and loading an existing one into the editor, it ads {subject} into the first line.

![Bildschirmfoto 2023-04-24 um 18 31 01](https://user-images.githubusercontent.com/1241376/234059984-b89e70c8-0f13-4439-95eb-fd469902a5fc.png)

### How can we reproduce this issue?

Step 1: Create a mail from any template - we used a custom one and confirmed with "blank"
Step 2: Select a contact and send an individual mail. 
Step 3: Load the created mail into the editor and {subject} appears in line 1.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by shinde-rahul** [comment]
@dsp76, I followed the steps given and failed to reproduce it.

**Comment by dsp76** [comment]
Hi @shinde-rahul thanks a lot for trying to reproduce it. 

I was able to do so again in two separate instances with 4.4.9 and would like to further detail the conditions to reproduce it:

- The test mail is created **with the legacy mail editor** with the blank template as a template mail.
- Select a contact and "Send mail".
- Select the prepared test mail to be loaded into the windows.

The bug will happen as described.

It will not happen with GrapeJS enabled.

**Comment by shinde-rahul** [comment]
@dsp76, thanks for the updated steps. I'll check this and revert.
