### ISSUE TITLE
Dynamics Intergration not working

### ISSUE THREAD

**Issue by Nisarg10** [mautic/mautic#12264]
### Mautic Version

4.4.x series

### PHP version

8.0.21

### What happened?

We are trying to integrate Dynamics CRM via Plugins. Plugins is being able to authorize with Azure AD. However, while running test command mentioned in [documentation](https://docs.mautic.org/en/plugins/microsoft-dynamics-crm#test-the-plugin.) it lead to following error.
 
![image](https://user-images.githubusercontent.com/14795254/234305231-95fcdcaa-2dfb-4b6e-8aaa-eeeff77f770b.png)

Contact Mapping and Company Mapping is not available as well like shown in documentation which seems to be the cause of above error.

### Documention Shot 
![image](https://user-images.githubusercontent.com/14795254/234305751-ececff83-3b64-44e4-a29b-9f13b4207c49.png)

### Our Plugin
![image](https://user-images.githubusercontent.com/14795254/234305923-4c003fd1-ef0a-4c7b-a27c-d3014ab7bef9.png)

### How can we reproduce this issue?

Step 1: Click On Dynamics plugin
Step 2: Provide required fields and authorize application.
Step 3: Once Authorize, Select Publish and Save.
Step 4: Select all features available save and close
Step 5: Run `php bin/console mautic:integration:fetchleads -i Dynamics`

### Relevant log output

`Command to fetch contacts from integration
Fetch contacts command is starting

Fetching contacts...
PHP Warning:  Undefined array key "leadFields" in /var/www/html/mautic/plugins/MauticCrmBundle/Integration/DynamicsIntegration.php on line 415

In DynamicsIntegration.php line 419:

  array_keys(): Argument #1 ($array) must be of type array, null given`

_No response_

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dcmax** [comment]
i have a similar issue with DynamicsApi.php, in my case i have found what is the field and removed  from the mappung (there are array field in Mautic that are strings Dynamics or  vice versa.
Other fields are string in mautic longer than 100 char that is the default string size in dynamics, you can enlarge the string lenght in dynamics.

**Comment by Nisarg10** [comment]
@dcmax Thank you for response. 

If I understand correctly, you are requesting that the "Filter Parameters" field be removed from DynamicsAPI.php, but I am unable to do so as I have not reached that point in my execution.

Additionally, during the preparation for integration, we are expected to provide field mapping, but I am not able to map the fields as Tab is not available to map the fields.

**Comment by Nisarg10** [comment]
Hi,

For some reason, now both the options are visible. Haven't changed anything on code.  Closing the issue. Tried to investigate how it came up however came up with nothing. It will be great help if someone can put some light on it.

![image](https://user-images.githubusercontent.com/14795254/235606363-37f609e2-829e-419a-8ea2-7a0fccc4990e.png)
