### ISSUE TITLE
Import merges based on email address (but should honor the "unique" fields)

### ISSUE THREAD

**Issue by ekkeguembel** [mautic/mautic#12277]
### Mautic Version

4.4.x series

### PHP version

7.4

### What happened?

When I have  contact multiple fields flagged as "unique", merging should only occur if ALL of those match.
This works nicely if I create contacts e.g. though a form.

However, when I import contacts through the UI (run the mautic:import console command), new contacts are merged based on "email" alone.

### How can we reproduce this issue?

Step 1: create custom field e.g. "remote_id", and set that to unique
Step 2: create simple CSV file (email, remote_id) with two data lines, with same email but different remote_if
Step 3: Import this file
Step 4: In contacts, you will find those two entries merged into one.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by ssoronid** [comment]
i would like to get this working too on importing from csv, console or trough api.

My usecase is similar, as we should manage uniqueness per mail and owner, not only per mail. Meaning an owner could have the same contact as another owner with their own data each.
