### ISSUE TITLE
RabbitMQ There are no commands defined in the "mautic:queue" namespace

### ISSUE THREAD

**Issue by tomekkowalczyk** [mautic/mautic#12297]
### Mautic Version

5.0.x series

### PHP version

8.1

### What happened?

I wanted to ask about integration with RabbitMQ queue

1. Documentation not up to date https://docs.mautic.org/en/queue is integration still supported?

2. When running the command, I get the error `There are no commands defined in the "mautic:queue" namespace`
![image](https://user-images.githubusercontent.com/39382654/236328301-429f2446-2f0e-4d96-9ea7-7bb776bb4785.png)

3. Is it possible to add RabbitMQ configuration to the standard DDEV config (I have a ready configuration)

### How can we reproduce this issue?

Step 1: Run  php bin/console mautic:queue:process --env=prod -i page_hit

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by galvani** [comment]
![Image](https://github.com/mautic/mautic/assets/556426/cb4b66d6-87dd-405e-902a-70f0d7b3bf55)

**Comment by galvani** [comment]
this command has been deprecated

**Comment by npracht** [comment]
According to @galvani feedback, you might have to run the correct command: `messenger:consume` instead.
I close the issue :)
