### ISSUE TITLE
Campaign conditions problem

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#1229]
I did this campaign:

![image](https://cloud.githubusercontent.com/assets/10166840/11690032/effd77ee-9e94-11e5-9d99-5022def968f8.png)
The form receives data and is in the results database. 
![image](https://cloud.githubusercontent.com/assets/10166840/11690250/0b1c9f5e-9e96-11e5-8cc4-2f92bd197910.png)
![image](https://cloud.githubusercontent.com/assets/10166840/11690271/243f4658-9e96-11e5-9b27-0921e8a6746e.png)

Is a checkbox selector and using like for detect option selected

![image](https://cloud.githubusercontent.com/assets/10166840/11690216/e1028eb8-9e95-11e5-9f6f-5d9686f24d8e.png)
(is not a problem with uppercase or lowercase I tested it already) 

But it dont add the lead to piscinas list 

![image](https://cloud.githubusercontent.com/assets/10166840/11690202/cb20dc3a-9e95-11e5-807a-31618b3876ea.png)

With the condition equals Work fine but is more sensible to changes...

**Comment by alanhartless** [comment]
Try using the % wildcard.  For example, `%piscinas%`.

**Comment by miguelpascual** [comment]
Now works. Thx

He had sworn that he had already tried

**Comment by alanhartless** [comment]
Great!
