### ISSUE TITLE
 Email sending error when i configuring Monitored Inbox Settings 

### ISSUE THREAD

**Issue by topman7777** [mautic/mautic#12298]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What happened?

I can’t send emails after trying to configure Monitored Inbox Settings, it seems many of you have the same problem as me. Hope someone can help, thanks a lot.
![loi4](https://user-images.githubusercontent.com/114727616/236373964-ad34a904-ea4f-41c4-9e66-e6911b64827d.png)
![loi3](https://user-images.githubusercontent.com/114727616/236373975-c1637dcf-0c4c-44f9-ae93-a00a27d5dd25.png)
![loi2](https://user-images.githubusercontent.com/114727616/236373979-0cf33dac-9432-4d2d-9bc6-50fe7cdf1430.png)
![loi1](https://user-images.githubusercontent.com/114727616/236373981-95e2cf94-9ae7-4f4b-806a-c0ae4f1cdd91.png)

### How can we reproduce this issue?

Step 1:  
![loi2](https://user-images.githubusercontent.com/114727616/236374067-8ec7dd72-4596-490c-aacc-eae7ee6bdc61.png)
step 2:
![loi1](https://user-images.githubusercontent.com/114727616/236374071-39cfd46d-8499-4148-af3e-5208c3f067a8.png)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
As per Slack conversation maybe @mabumusa1 can help.
