### ISSUE TITLE
Dynamic content block in email is behaving differently in first save and edit [$50]

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#12293]
### Mautic Version

4.4.x series

### PHP version

8.0.x

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Adding dynamic content based on preferred language, shows languages as values when adding it the first time. Looking into the database record, it shows that instead of the selected language, the first from the list "af" will be saved.

![Bildschirmfoto 2023-05-04 um 08 47 03](https://user-images.githubusercontent.com/1241376/236131988-93c15e86-48bd-4bdc-988d-6bc41999eb9e.png)

Reopening it, suddenly the editor shows language names. Saving it again now also saves it correctly into the database.

![Bildschirmfoto 2023-05-04 um 08 47 45](https://user-images.githubusercontent.com/1241376/236132182-3e9a92ba-9659-4f4e-b25c-a8c07c22dd29.png)

Conclusion: before dynamic content based on preferred language has a chance to work, it need at least to be edited and saved again. 

### How can we reproduce this issue?

Step 1: Add dynamic content to email based on preferred language (will show ISO codes instead of names) and save it. 
Step 2: Check database record for created email - will have a field that shows "af" as language.
Step 3: Reopen email again for edit. Now you are able to select Languages (Locales) by name. Save it again.
Step 4: Check database record for the mail - it now has the correct language code in the dynamic content field.

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by slapshin** [comment]
Hi! What is the status of this bug? I have the same problem.

**Comment by breslavsky** [comment]
Can confirm, the same problem and it very important. Can we donate to solve it?

**Comment by protekshen** [comment]
It's an actual problem, please fix 🙏

**Comment by tomrenneberg** [comment]
I have [posted a 150$ bounty](https://app.bountysource.com/issues/121828576-dynamic-content-block-in-email-is-behaving-differently-in-first-save-and-edit) on this issue and am happy to pay that to whoever gets this done.

**Comment by danadelion** [comment]
@tomrenneberg I've fixed this bug in https://github.com/mautic/mautic/pull/12634. Would you mind testing it to confirm it fixes your issue? I'll then have to fix it for Mautic 5 too otherwise it won't be merged into Mautic 4 either.

**Comment by RCheesley** [comment]
Thanks for posting the bounty @tomrenneberg and for the PR @danadelion, welcome to the community!

I've just set the tests running on the PR and have flagged it up for testing.

**Comment by RCheesley** [comment]
@slapshin @breslavsky @protekshen @tomrenneberg one more test needed on the PR #12634 so we can merge it in the next release!

Here's [how to test in the browser](https://contribute.mautic.org/contributing-to-mautic/tester) - create a new theme using the blank theme to test with.

**Comment by escopecz** [comment]
Merged into Mautic 4.4.10 and Mautic 5.0.0-beta. Both will be released soon.
