### ISSUE TITLE
Email open tracking not working for segment Emails in v4.4.8

### ISSUE THREAD

**Issue by charmgene** [mautic/mautic#12309]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Chrome

### What happened?

Email tracking pixel source URL not using site URL and as a result email opens are not tracked at all as expected. 

### How can we reproduce this issue?

Step 1: create a new segment email.
Step 2: send the segment email.
Step 3: open the segment email in the email client (Gmail).
Step 4: check the source of the email. You can find the img source link for the tracking pixel is broken - it's not using the correct domain. It should be something like {{Mautic_Site_URL}}/email/6456476e85cc967331= 0668.gif.

`<img height=3D"1" width=3D"1" src=3D"**http://mautic**/email/6456476e85cc967331= 0668.gif" alt=3D"" /><img src=3D"http://url5529.my-domain-name.com/wf/open?upn= =3D2rTO4Su3Zqzxptog2pT6FO-2FTTuuHGFp6V12CcxveOtpMrEesQtmtAnu6pHE-2F= rK6QYyGqh1jhdfNtXkDN8eTrh-2FKpeOekhhhkpo2oYUUvfYg8tx3nWsdfsiTrE9hgWzSyzt= qVQHJ8b5gDNRTfhzU6UesxyfEhNClvkERjv4p7geskplbZO9454kdfswe1h0Uy5cDme6nA= -3D-3D" alt=3D"" width=3D"1" height=3D"1" border=3D"0" style=3D"height:1px = !important;width:1px !important;border-width:0 !important;margin-top:0 !imp= ortant;margin-bottom:0 !important;margin-right:0 !important;margin-left:0 != important;padding-top:0 !important;padding-bottom:0 !important;padding-righ= t:0 !important;padding-left:0 !important;"/>`

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, you mentioned, not the right domain is used.
But which domain is used then? Are you using multiple domains?

**Comment by charmgene** [comment]
> 

We're using one domain. It's deployed via docker. 
It's working normally for emails sent via Campaign and I can see the tracking pixel looks like:

```
<img height=3D"1" width=3D"1"=
 src=3D"https://mautic.mydomain.com/email/6457cb71234f337200947.gif" alt=
=3D"" />
```
However, for segment emails, the tracking pixel image source looks like: 

`<img height=3D"1" width=3D"1" src=3D"http://mautic/email/6456476e85cc967331= 0668.gif" alt=3D"" />`

It seems it's not picking up the domain name.

https://mautic.mydomain.com/ is also the Site URL in System Settings.

**Comment by dsp76** [comment]
I tested it today with 4.4.9 and 4.4.7 - the tracking gif is set correctly to the mautic domain, no matter what type of mail. Also I checked with Gmail to make sure, its not Gmail messing things up. I couldn't recreate the error.

@charmgene - please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems.

Thanks a lot!
