### ISSUE TITLE
Owner Tokens / Variables not replaced in E-Mail 

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#12310]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Currently owner field tokens / variables will not be replaced in mails.

We tested with 
{ownerfield=firstname} and
{ownerfield=lastname}

Contactfield variables worked at the same time.

We tested not being loggedin, making sure, the contact has an owner. 

### How can we reproduce this issue?

Step 1:  Create a mail like this:

`This is the owner of {contactfield=firstname} {contactfield=lastname}: {ownerfield=firstname} {ownerfield=lastname}.`

Step 2: create a segment for testing
Step 3: create a campaign, that sends this mail via the just created segment.
Step 4: create a contact and asssign an owner to him.
Step 5: add contact to segment

Wait and see what happens.

Result will look like this:

![Bildschirmfoto 2023-05-08 um 11 27 05](https://user-images.githubusercontent.com/1241376/236788766-bacfcf23-0c84-4a00-8717-6fad72add250.png)

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, this bug is super annoying.
I think this fixes it:
https://github.com/mautic/mautic/pull/10733
I'll close this for now, plz re-open If I'm wrong about the PR, but I know it got fixed.

**Comment by dsp76** [comment]
@jos0405 this works with v5 only, right?
