### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by pravinuttarwar** [mautic/mautic#12319]
### Mautic Version

4.1.x series (not supported)

### PHP version

5.6

### What browsers are you seeing the problem on?

Chrome

### What happened?

Suddenly I started facing permission issue in log after clearing the cache, somehow my /config/edit page was not opening so I cleared the cache but then whole Mautic stopped, here is the log from httpd

> [Tue May 09 18:16:52.634980 2023] [:error] [pid 9123] [client 103.224.241.11:11897] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/mautic/app/logs/mautic_prod-2023-05-09.php" could not be opened: failed to open stream: Permission denied' in /var/www/html/mautic/app/cache/prod/classes.php:2901\nStack trace:\n#0 /var/www/html/mautic/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/mautic/app/cache/prod/classes.php(2831): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/html/mautic/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/html/mautic/vendor/monolog/monolog/src/Monolog/Logger.php(518): Monolog\\Logger->addRecord(400, 'PHP Notice: Doc...', Array)\n#4 /var/www/html/mautic/app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php(427): Monolog\\Logger->log('error', 'PHP Notice: Doc...', Array)\n#5 /var/www/html/mautic/app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php(245): Mautic\\CoreB in /var/www/html/mautic/app/cache/prod/classes.php on line 2901, referer: https://www.mindbowser.com/

### How can we reproduce this issue?

Step 1: open the url marketing.mindbowser.com
Step 2 : 500 error comes

### Relevant log output

```shell
[Tue May 09 18:16:52.634980 2023] [:error] [pid 9123] [client 103.224.241.11:11897] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/mautic/app/logs/mautic_prod-2023-05-09.php" could not be opened: failed to open stream: Permission denied' in /var/www/html/mautic/app/cache/prod/classes.php:2901\nStack trace:\n#0 /var/www/html/mautic/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/mautic/app/cache/prod/classes.php(2831): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/html/mautic/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/html/mautic/vendor/monolog/monolog/src/Monolog/Logger.php(518): Monolog\\Logger->addRecord(400, 'PHP Notice: Doc...', Array)\n#4 /var/www/html/mautic/app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php(427): Monolog\\Logger->log('error', 'PHP Notice: Doc...', Array)\n#5 /var/www/html/mautic/app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php(245): Mautic\\CoreB in /var/www/html/mautic/app/cache/prod/classes.php on line 2901, referer: https://www.mindbowser.com/
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems. This is almost certainly a permissions configuration or caching issue so someone will be able to help you o the forums! Thanks!
