### ISSUE TITLE
Telize : The public API will permanently shut down on November 15th

### ISSUE THREAD

**Issue by l2aelba** [mautic/mautic#1231]
http://www.telize.com/
Just that. Better to make other IP lookup service by default ?

**Comment by Yame-** [comment]
+1
Aha, that's why it wasn't working... 
I've set ours to freegeoip.net. Our worldmap is getting some colors now :)

**Comment by alanhartless** [comment]
Yea...we're deciding what we need to do for this and will address it for 1.2.3. It's possible Mautic traffic pushed the service over the edge :-)
