### ISSUE TITLE
Mautic queued emails sent twice to Amazon SES

### ISSUE THREAD

**Issue by forao** [mautic/mautic#12315]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I send a queued email to a segment of 5 contacts using the AWS SMTP server, Mautic creates 5 .message objects in the /docroot/var/spool directory. This indicates that 5 emails are queued to be sent.

When I execute the "mautic:emails:send" command, the console displays the following message:

[2023-05-09 02:23:47] Processing default mailer spool...
10 emails sent
Content-type: text/html; charset=UTF-8

Checking Amazon SES shows that 10 email sends have been processed. However, each lead receives only one email, which makes a total of 5 successfully received emails.

Although no leads appear to receive duplicate emails, sending 10 emails to the Amazon SMTP server results in double billing for the actual emails sent and limits my email sending capacity to only half of my allotted limit. I'm looking to understand why this is happening and how to fix it, making sure that Mautic sends only 5 emails to AWS.

Here are additional details about my configuration:

* My Amazon AWS instances use an Elastic Load Balancer.
* I have two verified identities on AWS SES for the email being sent via Mautic: domain and email address.
* The connection test in Email Settings within Mautic is successful.
* The email test in Email Settings also sends successfully. In this case, when sending the queue containing the test email, "mautic:emails:send" reports only 1 email sent.
* I have configured Mautic to use Amazon SES - SMTP as the "Service to send email through" with port 587.
* The Amazon SES Region is correctly selected in the Email Settings of Mautic.

If I need to provide further information I'd be glad to do so.

### How can we reproduce this issue?

Step 1: Configure Mautic for sending emails with AWS SMTP server (not sure if an enabled Elastic Load Balancer is necessary to reproduce)
Step 2: Configure Mautic to handle emails thru a Queue
Step 2: Create a segment with 5 leads
Step 3: Create an email to be sent to the segment created in the previous step
Step 4: Send the email

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, I'm using Amazon SES without problems with your version. It doesn't mean the bug is not there :)
Do you use CC in your emails?
Could you plz check how many email files are in your spool before executing the send command?
`/var/spool`

**Comment by forao** [comment]
No, I don't use CC on my emails.  Here's a test performed just now:

(uiserver):u53092785:~/mautic/docroot/var/spool$ ls | wc -l
0

<< Hit Send on Test Email on Mautic >>

(uiserver):u53092785:~/mautic/docroot/var/spool$ ls | wc -l
5

(uiserver):u53092785:~/mautic/docroot/var/spool$ ls
2ICzYvmZ3w.message  NyxpTqKU-Q.message  YV4y7KSu7O.message  jqCQC5_-ph.message  uy6zCZTiFx.message

(uiserver):u53092785:~/mautic/docroot/var/spool$ php8.0 html/mautic/bin/console mautic:emails:send

 [2023-05-10 11:39:01] Processing default mailer spool...
 10 emails sent
Content-type: text/html; charset=UTF-8

**Comment by forao** [comment]
Sorry, this is embarrassing: I did have a BCC email in the Advanced tab on the Email setup. It was just kind of hidden in the tab and I had forgotten that I had entered something there. Closing issue and my apologies 🙂
