### ISSUE TITLE
Form Deletion Leaves Table of User Info in Database - GDPR Compliance?

### ISSUE THREAD

**Issue by J-Wick4** [mautic/mautic#12320]
### Mautic Version

4.4.x series

### PHP version

8.0.28

### What browsers are you seeing the problem on?

Chrome

### What happened?

I went through the database and found user data in a table for a form that was deleted from Mautic. This could be troublesome for GDPR compliance.

### How can we reproduce this issue?

Step 1: Create a form.
Step 2: Submit the form with user data.
Step 3: Delete the contacts and Form Entries created by the form.
Step 4: Delete the form.
Step 5: Check tables, see table **form_results_#_public** exists full of user data. 

![Screenshot 2023-05-09 at 11 42 03 PM](https://github.com/mautic/mautic/assets/1954540/127224c9-2c13-44da-9b8e-390b3735cc7c)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi,
The GDPR law orders you to delete data if it's requested.
You can do it by:
![image](https://github.com/mautic/mautic/assets/4246909/4ccdd7e7-33e6-4dc5-8798-5a2e8eb9ebc4)
I realize it's not automatic, but it could harm even more if you would automate it.
I don't think this is a 'bug', but it could be an improvement or Plugin.
Maybe add it as feature request, and plz describe if you are ready to work on it yourself.
I'll close this for now. I'm always happy to keep the conversation going, please reopen if you disagree!
