### ISSUE TITLE
Cannot clear field value over API

### ISSUE THREAD

**Issue by bradjones1** [mautic/mautic#12348]
### Mautic Version

5.0.x series

### PHP version

8.2

### What browsers are you seeing the problem on?

Not relevant

### What happened?

It is not possible to clear a field value (e.g., `email` over the API. I have tried sending `null` and `''` (empty string) and neither is successful; the resulting contact object is returned with the existing value.

### How can we reproduce this issue?

Step 1: Create a contact with an `email` value.
Step 2: Attempt to clear the value over the API.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
Hi @bradjones1,
add the parameter 	"overwriteWithBlank" : true to your statement and null and "" will work.

@RCheesley this needs to be added to the developer doc. Hope this is a valid statement for every field to be patched? Just found it, as this was the same for different fields and its mentioned here and there, but not throughout the docu for each endpoint.

**Comment by RCheesley** [comment]
@bradjones1 @dsp76 sorry for the long delay!

Here is the docs currently in the WIP new instance:

https://mautic-developer.readthedocs.io/en/latest/

5.x branch: https://mautic-developer.readthedocs.io/en/5.x/

Please take a look and if something needs adding, do make a PR! Many thanks!
