### ISSUE TITLE
rename(): supplied resource is not a valid Stream-Context resource #10644

### ISSUE THREAD

**Issue by modifiedcontent** [mautic/mautic#12345]
### Mautic Version

4.4.x series

### PHP version

8.0.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I get the same error [reported here, closed without a solution](https://github.com/mautic/mautic/issues/10644). 

[Full description of the problem here](https://forum.mautic.org/t/mautic-says-emails-sent-but-nothing-has-actually-gone-out/27811). I have used Mautic for years for sending mailings and haven't made any changes to my email configuration on the server.  

### How can we reproduce this issue?

Step 1: Try to send emails?

I wouldn't know how to reproduce the error. If I knew what to break to produce the same error result, I would know how to fix it. 

### Relevant log output

```shell
In ProcessEmailQueueCommand.php line 141:

  rename(): supplied resource is not a valid Stream-Context resource

mautic:emails:send [--message-limit [MESSAGE-LIMIT]] [--time-limit [TIME-LIMIT]] [--do-not-clear] [--recover-timeout [RECOVER-TIMEOUT]] [--clear-timeout [CLEAR-TIMEOUT]] [--lock-name [LOCK-NAME]] [--bypass-locking] [-t|--timeout TIMEOUT] [-x|--lock_mode LOCK_MODE] [-f|--force] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

@Docki-cz @peter-palmer, how have you solved this?

@npracht, do you have any ideas where to start to troubleshoot this?

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
The linked discussion https://forum.mautic.org/t/mautic-says-emails-sent-but-nothing-has-actually-gone-out/27811 ended with a solution. Reason was an outdated PHP Version.
