### ISSUE TITLE
Form and lead fields fail with Chinese and Japanese languages

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#1234]
Chinese, Japanese and other languages not covered by the transliteration change still cause the same issue as described in #998.  Need to add a check to CommonModel::cleanAlias() to prevent empty fields.

**Comment by maxitine** [comment]
After some test I found the form name should not be Chinese, otherwise the form can not function. Changing form name to English will help to work around this issue.

**Comment by maxitine** [comment]
There is a way to transform the Chinese Charactor into phonetic letters (Pinyin) before saving the form. This will resolve the form function name issue in JavaScripts. I saw this in some drupal module.
