### ISSUE TITLE
Error in Zoho CRM plugin

### ISSUE THREAD

**Issue by shahriared** [mautic/mautic#12355]
### Mautic Version

4.4.x series

### PHP version

8.0.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After I finished my integration and set up the cron job, I'm getting the error bellow.

`substr(): Argument #1 ($string) must be of type string, array given`

### How can we reproduce this issue?

Step 1: 
Set up the Zoho CRM integration
Step 2: 
Set up the cronjob for the integration commands or manually run the following command: 
`mautic:integration:synccontacts`

### Relevant log output

```shell
console.CRITICAL: Error thrown while running command "'mautic:integration:synccontacts' --integration=Zoho". Message: "substr(): Argument #1 ($string) must be of type string, array given" {"exception":"[object] (TypeError(code: 0): substr(): Argument #1 ($string) must be of type string, array given at /public_html/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php:666)","command":"'mautic:integration:synccontacts' --integration=Zoho","message":"substr(): Argument #1 ($string) must be of type string, array given"}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by AliMehraei** [comment]
Same issue
