### ISSUE TITLE
Integration from mautic form to SugarCRM leads module

### ISSUE THREAD

**Issue by shivaNV** [mautic/mautic#12375]
### Mautic Version

4.4.x series

### PHP version

8.0.1

### What browsers are you seeing the problem on?

Chrome

### What happened?

We have done integration from Mautic form to SugarCRM but SugarCRM contact mapping tab is showing integration field and Mautic fields of 113 items, total 4 pages but we are able to mapping only two fields but in our mautic form there are 5 fields and here we are not able to go for next page and it not displaying remaining fields,  pls tell me how to solve this problem. and below attached images 

![image](https://github.com/mautic/mautic/assets/134388896/5c1eb813-ab9a-4722-a22c-93af84812389)

![image](https://github.com/mautic/mautic/assets/134388896/82885bbf-00bc-4315-b593-5042000c0689)

### How can we reproduce this issue?

Step 1: ahlaa

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
Hi @shivaNV,
please head over to the forum: forum.mautic.org to find out with the community, if its a bug at all or if its a support issue.
This bug description is not complete at all, not can anyone reproduce it with this limited and missing information. 

Will reopen it, when its discussed and identified as a bug or clear information step by step is added on how to reproduce.
