### ISSUE TITLE
The requested URL was not found on this server.

### ISSUE THREAD

**Issue by Yssndc** [mautic/mautic#12370]
### Mautic Version

5.0.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome

### What happened?

Hello I just finish my mautic configuration it's redirect me to XXX.com/mautic/s/dashboard
but I don't have this directory on my server

### How can we reproduce this issue?

Step 1: I just configured Mautic

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
Please post it in the forum - https://forum.mautic.org/ 
Thats probably not a code issue.
