### ISSUE TITLE
[Feature] Additional Campaign Actions/Decisions

### ISSUE THREAD

**Issue by harbingerlabs** [mautic/mautic#124]
Suggest adding actions to the campaign builder:
### Decisions
- Specific email link clicks
- On-page events like clicking a submit button or specific link
- Visiting any page on website (would require global tracking script)
### Actions
- Send notification to email address or user
- Add a wait step

Overall I love the idea. I've used every major marketing automation tool and a few not so major. I'm interested in helping however I can if needed.

One minor observation; I wonder if Actions and Decisions should be reversed. Actions leads make like opening emails, visiting pages etc... trigger Decisions the marketer makes like add to lists, send email etc...

**Comment by alanhartless** [comment]
Great suggestions!

For "Visiting any page on website (would require global tracking script)," you can do that now by using our tracking pixel. See http://docs.mautic.org/leads/lead_monitoring.html.  Note that with RC2, the /p/ is not required in the mtracking.gif URL.  Then you can use the Visits a page decision and insert the URL (or wildcard based URL) to determine if the outcome of the decision. (If you are using the hosted version, this feature is coming soon).

For the wait step action, we built the wait times into the actions as a "delay" where you can set an interval (i.e 3 days) or a specific date/time before the action is executed. 

We've gone back and forth on the ordering decisions and actions and I think can be either depending on the setup of the campaign.  For example, the campaign start with a Send mail action followed by Opens email and so forth.  Or if the email is sent outside the campaign, maybe the campaign starts with the "Opens email" decision instead. I think no matter what order we put them, there will be scenarios where it seems backwards. :-)

We appreciate your desire to help! Welcome!

Thanks,
Alan

**Comment by harbingerlabs** [comment]
Thanks Alan,

Will dig into the pixel, just didn't see it in the admin section, but glad it's there!

Found the wait steps right after I dropped the above note :)

For the actions, I see your point. In a contact record you'd see 'actions' or things that they've done. Maybe everything is an action? In looking at Pardot, they call it everything 'Available Actions' in Hatchbuck, they're called Steps, but they are referenced as actions throughout.

Another question I have re: the campaign builder is sending unchained emails w/in the same campaign. For example, you have Email 1 w/ an 'Opens email' decision leading to a rise in score. Email 2 is setup to send 3 days later, but isn't dependent on Email 1 being opened (Eloqua does this, one of the very, very few things that I like about them!)

I tested this out but it didn't seem to fire w/ 5 minute increments (EM1 immediate, EM2 5 minutes, EM3 10 minutes) with all having an 'Open email' decision ramping up the score. When I went to edit the campaign steps, the drag-n-drop blocks were all top left aligned and all disconnected from their actions. It may not work that way which is way OK.

Thanks again for your help and looking forward to working with this.

**Comment by that0n3guy** [comment]
I'll bump this feature request.  It seemed odd to me that there is an "opens email" decisions, but not a "clicks on link" decision.

**Comment by escopecz** [comment]
There is a way to track links which points to a webpage with Mautic Tracking Pixel loaded. That option is under *Visits a Page* decision. There is *URL* field where you insert the link.

Just thought it worth mentioning. Maybe it help someone. The *Clicks on link* decision should be build of course.

**Comment by that0n3guy** [comment]
@escopecz True, but that doesn't really tie in w/ the specific email though I don't think.  They could visit that page at a different time.  I usually want to relate their action with an email (thus I know context).

**Comment by escopecz** [comment]
@that0n3guy I check that campaign works like I thought it is. So it will work withing the campaign as it would be the *Clicks on link*.

If you have campaign like this:
```
List -> Send Email -> Opens Email -> Visits Page -> Add Points
```
If a lead which is in the List visits the Page without getting the Email first, the Points will not be added. Points will be added only if the Lead go through all Campaign actions up to the Visits Page.

**Comment by npracht** [comment]
@that0n3guy & @escopecz, the conclusion of that point (because of mine is obviously related) is that "you can reach your goal by doing it differently" ?
Cause yes, you can always try to do it another way, but that's a really different answer between tracking the source of the link (the click) and the arrival of the link (landing page).
As mentioned, that only works if the landing page is tracked and if there is no other way that the lead visited this page, otherwise it can be confusing.

I close my #1009 issue.

N.

**Comment by npracht** [comment]
Hi,

It would be very very great to have a "**Send notification to email address or user**".
Cause today you can do it from Froms actions. But **doing that from campaigns would allow much more situation where it could be relevant**.
Examples:
* You could notify people from a form submission but different people depending on the value selected when the form has been submitted.
* You could notify a salesman when a lead has visited a specific page (customer of product A visits page B).
* and much more...

![capture d ecran 2015-11-25 a 14 18 47](https://cloud.githubusercontent.com/assets/14075239/11398292/fbfa7b70-937f-11e5-927e-25d1c6e53a75.png)

**Comment by npracht** [comment]
I guess this notification systems requested is also related to https://github.com/mautic/mautic/issues/1183
### Notifications are missing on:
* Campaign actions
* Point trigger actions

_They are existing on form action._

**Comment by escopecz** [comment]
I'll close this old issue since it contains several feature requests at once. Some of them exists as a separate feature request and some of them were implemented already. When several features are requested in one issue, it makes it hard to track what's done and what's not. Please, if you still miss something that is still not requested, create a new issue for each such feature.
