### ISSUE TITLE
SQL query returns to much leads

### ISSUE THREAD

**Issue by EsdersGmbH** [mautic/mautic#12415]
### Mautic Version

4.4.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Not relevant

### What happened?

We have companies in Mautic that have no contacts at the moment. In the list of all companies this is confirmed by the Contacts column.
However, when I open the overview of such a company, random leads are displayed. These leads are not related to these companies in any way. 

This made me curious, and I enabled general logging on my local Mariadb server.
I found a very strange query in the log file:
`8 Query	SELECT COUNT(l.id) as count FROM leads l LEFT JOIN users u ON u.id = l.owner_id WHERE (l.firstname LIKE '%ids%') OR (l.lastname LIKE '%ids%') OR (l.email LIKE '%ids%') OR (l.company LIKE '%ids%') OR (l.city LIKE '%ids%') OR (l.state LIKE '%ids%') OR (l.zipcode LIKE '%ids%') OR (l.country LIKE '%ids%')`

It appears that if a company has no leads, all leads that contain the letters "ids" in any of the fields will be displayed. When I run the query in the lead table, I get the same random leads as in the UI.

### How can we reproduce this issue?

Step 1: Create some Companies, with leads that contains "ids" inside of the name, for example.
Step 2: Create one or more Companies without leads.
Step 3: Look inside the empty companies.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
I can confirm this behavior in 4.4.8 ... good find!

**Comment by RCheesley** [comment]
Thanks for reporting and confirming folks, we have a PR in #12464 which fixes this. Please test! 🚀 

Here's how to help with testing: https://contribute.mautic.org/contributing-to-mautic/tester - you can do it in the browser with Gitpod.

**Comment by EsdersGmbH** [comment]
I've tested the pull request and the bug is gone.
