### ISSUE TITLE
[Composer] favicon not found [404]

### ISSUE THREAD

**Issue by putzwasser** [mautic/mautic#12418]
### Mautic Version

4.4.x series

### PHP version

8.0.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I installed Mautic via composer. I noticed that the favicon don't get rendered/loaded.

Mautic tries to load the favicon from `https://mautic.mysite.com/media/images/favicon.ico?v96aac245`, but `mautic/docroot/media/images` is empty. `favicon.ico` is located in `mautic/docroot`.

**Maybe related**
The gravatars for the users won't load, too:
For my initial admin user mautic tries to load `https://i1.wp.com/mautic.mysite.com/media/images/avatar.png?ssl=1`, which is obviously wrong, too.

### How can we reproduce this issue?

1. Install Mautic via composer
2. See missing favicon.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
Hi @putzwasser - I did a new composer install today with 4.4.9. There were issues with earlier versions. Please try the console command mautic:assets:generate. Probably those files have not been correctly copied to the places. 

Actually in my brand new installation favicon and avatar are indeed in the places where they are missing in your installation.

Lets move the discussion to the Mautic forum: https://forum.mautic.org/ as its currently not a recreatable bug.

**Comment by putzwasser** [comment]
I've set up three instances in the last weeks. All of them are missing the contents in `docroot/media/images` I doubt that it isn't reproducible…

**Comment by dsp76** [comment]
@putzwasser as I said - there were issues with earlier versions. But not with the current version 4.4.9 anymore. A good issue description contains all the information to make it reproduceable. I also had trouble in the past to find out whats causing the issue and discussed it with other users in the forum until we were able to reproduce it. Then we opened an issue. 

Reproducable bugs belong here. Until that is achieved, support will be provided by your mautic partners or the community in the forum on a best can do basis.

**Comment by putzwasser** [comment]
> But not with the current version 4.4.9 anymore

I installed 4.4.9—hence opening this issue.

> A good issue description contains all the information to make it reproduceable

There's nothing more that I could provide here. I'd be happy to, but I don't know what I'd add. I had no error messages, etc—except the obvious 404 HTTP response.

> I also had trouble in the past to find out whats causing the issue and discussed it with other users in the forum until we were able to reproduce it. Then we opened an issue.
>
> Reproducable bugs belong here.

I was under the impression that this is reproducible, as it happened three times for me. Going to the forum first made no sense for me as it was clearly a bug, so it would have made no sense to split the conversation about it into a forum, and a github part.
