### ISSUE TITLE
Failed to execute campaign event (OneSignal - Web Notification)

### ISSUE THREAD

**Issue by albertofreitas-wb** [mautic/mautic#12435]
### Mautic Version

4.4.x series

### PHP version

8.0.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I configured a campaign to send a Web Notification (Push). The integration is using OneSignal Plugin. Almost everything is happening correctly, however, when the campaign runs, the push is sent (onesignal receives and returns as information) but, even with the Push, Mautic reports a problem with the notifications. Didn't enter any kind of log!

[Emails sent ok (Amazon SES)]

![image](https://github.com/mautic/mautic/assets/60145319/b3c72f90-638e-4826-bcb2-862b256599df)

### How can we reproduce this issue?

Step 1: Create OneSignal Account
Step 2: Enable Integration
Step 3: Create Campaign (any segment and send web notification)

php /app/console mautic:campaigns:update
php /app/console mautic:campaigns:trigger

### Relevant log output

```shell
NO LOG
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @albertofreitas-wb could you confirm what version of Mautic you're using? You mention using app/console which would suggest it's an unsupported version.

**Comment by RCheesley** [comment]
Closing issue due to lack of feedback and likely using an outdated version of Mautic.
