### ISSUE TITLE
Mautic Technical Debt

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#12449]
Great news! In PR #11970, I installed four phpstan extensions that can detect code issues. While running them, we found 1902 issues that need to be resolved. Don't worry though, most of them are easy fixes and often appear in multiple files. To help you out, I've attached a report with all the issues that need attention. Let's work together to get Mautic's code in tip-top shape!

I am more than happy to mentor and guide you through the process if you want to start a PR

[test-run.txt](https://github.com/mautic/mautic/files/11687664/test-run.txt)

**Comment by galvani** [comment]
@mabumusa1 I thouht of putting a little bounty on it but the link does not work.

**Comment by kuzmany** [comment]
@galvani bountysource is dead, they didn't pay to devs. Some replacement are discussed here https://community.mautic.org/assemblies/product-team/f/39/debates/2

**Comment by biozshock** [comment]
These should fix this issue.
https://github.com/mautic/mautic/pull/13085
https://github.com/mautic/mautic/pull/13110
https://github.com/mautic/mautic/pull/13113
https://github.com/mautic/mautic/pull/13116
https://github.com/mautic/mautic/pull/13112
https://github.com/mautic/mautic/pull/13129
https://github.com/mautic/mautic/pull/13130

**Comment by RCheesley** [comment]
@mabumusa1 is this issue still relevant? If so could you maybe update as to what the status is now? Thanks!

**Comment by RCheesley** [comment]
Closing this old issue.
