### ISSUE TITLE
api/contacts/batch/edit returns 500 error if contacts are with the same data in 'stage' field

### ISSUE THREAD

**Issue by valeriyaduran** [mautic/mautic#12443]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What happened?

api/contacts/batch/edit should return 200 error and should not depend on 'stage' field

### How can we reproduce this issue?

Step 1: 
Send patch request to update 'language' field with contacts that have the same stages.

Actual result: Fields are not updated, 500 status code.
Expected result: Fields are updated, 200 status code.

Request example:
curl -X PATCH -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Basic <Key>' -H 'Connection: keep-alive' -H 'User-Agent: python-requests/2.31.0' -d '[{"id": "<id1>", "language": "Japanese"}, {"id": "<id2>", "language": "Vietnamese"}]' <domain>/api/contacts/batch/edit

### Relevant log output

```shell
{
    "errors": [
        {
            "message": "Looks like I encountered an error (error #500). If I do it again, please report me to the system administrator!",
            "code": 500,
            "type": null
        }
    ]
}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
@valeriyaduran Could it be a misunderstanding? You would still need to send the concerned contacts with the request. You can't select the batch with the patch call together.

https://developer.mautic.org/?php#edit-batch-contact

You probably need to retrieve those contacts before, that you want to edit. You can do a search with getting them. 

https://developer.mautic.org/?php#list-contacts

Anyway - thats not a bug as in "broken". Please move this to the forum.mautic.org where we can discuss the situation and decide if an improvement for the API should be needed as a feature request.

**Comment by valeriyaduran** [comment]
Hi! When I am trying to update 2 existing contacts that have the same stage via api/contacts/batch/edit it returns 500. Why it is not a bug?<img width="841" alt="Screenshot 2023-06-16 at 09 03 12" src="https://github.com/mautic/mautic/assets/36791323/78c86963-9683-451b-8778-4ee270043435">

**Comment by dsp76** [comment]
I don't see any Ids in your example call. I get the impression its not according to the API documentation. But please discuss it in the forum to find the reason. A bug needs to be reproduceable ... it looks to me as if the intended use is not according to the specs...

**Comment by valeriyaduran** [comment]
Request example:
curl -X PATCH -H 'Accept: /' -H 'Accept-Encoding: gzip, deflate' -H 'Authorization: Basic ' -H 'Connection: keep-alive' -H 'User-Agent: python-requests/2.31.0' -d '[{"id":  "some_id", "language": "Japanese"}, {"id": "some_id", "language": "Vietnamese"}]' /api/contacts/batch/edit

I left ids empty (now in the example i wrote "some_id" in an empty area). It can be ids of any contacts that have the same stage.

**Comment by dsp76** [comment]
Thank you. As proposed - please move this topic to the forum and I will be happy to answer your support issue. I just tried it myself - the API call works as designed - but there are two mistakes in the request. The field is called: "preferred_locale" and the values in the example should be "ja" and "vi".

**Comment by valeriyaduran** [comment]
This is not a mistake. This field is a custom text field.
