### ISSUE TITLE
API GET list of segments - inconsistency in results vs. documentation

### ISSUE THREAD

**Issue by tomas-marik** [mautic/mautic#12451]
### Mautic Version

4.4.x series

### PHP version

8.0.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When you retrieve list of segments from API via `GET /api/segments`, obtained list of entities in `lists` property is not an `array` of segments instead is an object literal with keys representing segment ID, ie.:

```json
{
	"total": 2,
	"lists": {
		"1": {
			"isPublished": true,
			"dateAdded": "2023-06-08T08:34:25+00:00",
			"dateModified": "2023-06-08T08:34:25+00:00",
			"createdBy": 1,
			"createdByUser": "XYZ",
			"modifiedBy": null,
			"modifiedByUser": " ",
			"id": 1,
			"name": "test1",
			"publicName": "test1",
			"alias": "test1",
			"description": null,
			"category": null,
			"filters": [],
			"isGlobal": true,
			"isPreferenceCenter": false
		},
		"2": {
			"isPublished": true,
			"dateAdded": "2023-06-08T08:34:31+00:00",
			"dateModified": "2023-06-08T08:34:31+00:00",
			"createdBy": 1,
			"createdByUser": "XYZ",
			"modifiedBy": null,
			"modifiedByUser": " ",
			"id": 2,
			"name": "test2",
			"publicName": "test2",
			"alias": "test2",
			"description": null,
			"category": null,
			"filters": [],
			"isGlobal": true,
			"isPreferenceCenter": false
		}
	}
}
```

However your [documentation](https://developer.mautic.org/?json#list-contact-segments) (select "JSON" in example panel on the right) states that array should be returned and I think this is the correct way of returning list of entities in REST. Some libraries rely on array structure of lists from REST APIs.

I think this will be general issue in lists from REST API, not only in segments.

I am using Mautic API with HTTP Basic Auth.

I would be happy if there is at least some way to control this behavior, ie. with a GET parameter or something like that.

### How can we reproduce this issue?

Step 1: Enable REST API: Configuration > API Settings (API enabled: Yes, Enable HTTP basic auth: Yes).
Step 2: Create few sample segments and make sure they are published.
Step 3: Call `/api/segments` to retrieve results.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
I can confirm the described issue, however from my view the documentation is in sync with the current behavior of the API.
Technically things are not broken here - the API Design might needed to be discussed with the given argumentation. I would suggest to open up a feature request and close this "bug"? 

@RCheesley what do you think? Would also be something for a future "API Tiger Team".

**Comment by dsp76** [comment]
Same is valid for:

- GET /campaigns
- GET /contacts
- GET /companies
... and other list actions. 

Its not very API consumption friendly. For instance - 264 contacts in Mautic (where 32 are identified, the rest anonymous - not filterable!) created over 13k lines of response. 30 companies already generated 6769 lines of response.

@tomas-marik would you please open a feature request here: https://forum.mautic.org/c/ideas/14 ? I will vote for it too!
