### ISSUE TITLE
Reports do not show total of hits on external landing pages

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#1245]
Just had a troubleshooting session with a client which unearthed what seems to be a bug with 1.2.2, pretty sure it's not expected behaviour anyway.
## To reproduce
1. Add Mautic tracking pixel on external websites
2. Create a Mautic landing page
3. Visit external website pages with tracking pixel enabled
4. Visit Mautic landing page 
5. Identify that the lead record has been updated with the visits to the relevant pages
6. Create a report which shows visits to pages and includes unique hits, hits and whatever other fields
## Expected

All external pages and Mautic landing pages should display the unique & total hit count in the report, not only the Mautic landing pages
## Problem

All the external pages are listed, but there is no count of the number of hits.  Visits to the Mautic landing page is logged and is displayed with a count value for unique hits & all hits.

**Comment by alanhartless** [comment]
Is the report's Data Source "Page Hits" or "Landing Pages?" If landing pages, it'll only display Mautic's landing pages.  Page hits should show all Mautic landing pages and tracking pixel hits.

**Comment by RCheesley** [comment]
Hi Alan,

I believe it was page hits, but I will cycle back with the client and report back.

Ruth

**Comment by RCheesley** [comment]
Alan,

If it was landing pages, surely it would only list the Mautic landing pages, and not all the pages on which the tracking pixel has received hits?

The report list included all the pages with hits, plus the Mautic landing page I created to test whether it was also impacting the landing page hits.

Ruth

**Comment by RCheesley** [comment]
It's set to page hits - see screenshots below.

![pastedgraphic-3](https://cloud.githubusercontent.com/assets/2930593/11975294/30f72b4e-a964-11e5-8148-5ffcbd32740c.png)
![pastedgraphic-2](https://cloud.githubusercontent.com/assets/2930593/11975295/30f8f3d4-a964-11e5-94a5-47fb13d844f7.png)
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/2930593/11975296/30fb9260-a964-11e5-9edf-6968acb15f70.png)

**Comment by escopecz** [comment]
I think the issue is that there is "Most visited pages" widget which displays the count, but there is no "Most visited URLs" widget.

From the technical point of view, Mautic Landing Pages has the count cached in the landing page row in the database. So to it is relatively easy to sort the landing pages by this cached count and display them. In case of hits from 3rd party pages, there is no cache for it so the counts would have to be counted on run time which is very resource expensive.

But I understand such a widget is very helpful. I'll mark this as feature request.

**Comment by npracht** [comment]
@escopecz i think it is similar to https://github.com/mautic/mautic/issues/4136
