### ISSUE TITLE
Colours no longer pre-defined in focus item builder

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#12460]
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

In the past when you created a focus item, the colours would be pre-defined using the Mautic brand colours. This helps to see the focus item before you actually start to add content etc.

Currently, there are no colours pre-selected so it's hard for the user to see what it looks like (eg if using a bar).

### How can we reproduce this issue?

Step 1: Create a focus item
Step 2: Go to builder
Step 3: Notice that when you twirl the Colours panel down, no colours are pre-populated.

Maybe this is related to the JS dependency updates? cc @escopecz FYI.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
Yes, this will be a regression. We should fix this before the stable release.

**Comment by RCheesley** [comment]
I _think_ this has somehow been fixed - they are now showing.
