### ISSUE TITLE
Possibile BUG e-mail link tracking

### ISSUE THREAD

**Issue by mgproget** [mautic/mautic#1246]
Way to re-create this bug:
- Mautic v. 1.2.2
- create a list with MORE than one lead
- create an e-mail with an external link on it to a external web page (with pixel on it)
- create a campaign that send the e-mail to the list.

Result:
Only one e-mail is sent with the tracking/redirect URL (ex. http://mydomain/r/259da081cc9d3595ca69a33c9?ct=YTo0OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo4OiJjYW1wYWlnbiI7aToxO2k6MTt9czo1OiJlbWFpbCI7aToyO3M6NDoic3RhdCI7czoxMzoiNTY3MDJlZWQ5Nzc0MSI7czo0OiJsZWFkIjtpOjMxO30%3D).
All other leads receive the e-mail with the original link to the web page (no redirect).

Final result:
Clicks are tracked for one e-mail only.

**Comment by l2aelba** [comment]
https://www.mautic.org/community/index.php/1219-sometimes-mautic-seems-to-automatically-add-trackable-urls-to-t/

**Comment by mgproget** [comment]
@l2aelba that's the problem I'm facing with, not the solution.

**Comment by alanhartless** [comment]
@mgproget What mail transport are you using? (Mandrill, smtp, PHP mail, etc)

**Comment by mgproget** [comment]
I'm using different transport solution and the problem remains (we have more than one instance of Mautic). The one I'm testing this issue is using Sendgrid (with Sendgrid click tracking disabled).

**Comment by tiagomreis** [comment]
@alanhartless same problem here. latest version of mautic, using "Other SMTP server" and then localhost mail server.

2 leads in a list, the lead with the lower ID receive the url with tracking number, the second person receive without the tracking id.

**Comment by alanhartless** [comment]
I just tested on a 1.2.2 installation and it worked there too.  So I'm wondering if there is something with the content of the email and or something with the link itself that is triggering this bug.  Could one of you guys provide the content of an email that has the links leading to this issue?

Thanks!
Alan

**Comment by mgproget** [comment]
@alanhartless 
[email_text.html.zip](https://github.com/mautic/mautic/files/66878/email_text.html.zip)
I'm using the builder, with a custom template.

**Comment by mgproget** [comment]
@alanhartless I've just tried deleting all content and added two words and one link. Same result. I'm going to try with no template at all.

**Comment by tiagomreis** [comment]
@alanhartless using the builder, same issue. The first person with lower id receive with redirection url and the other with no tracking url

PS: Just open the builder, type two word and use the editor to make a link on one of the words.

**Comment by alanhartless** [comment]
Here's a animated gif of what I did on a 1.2.2 install.  http://alan.direct/drop/emaillink.gif

The first time I did a custom HTML link test. So this time I did used the builder/template.  Same thing, all three have the links parsed.

@mgproget I'll try with your email content.

**Comment by alanhartless** [comment]
@mgproget I copied that HTML into a custom HTML email and sent it to 3 leads.  Still works for me. 

Here's a gif of it.  http://alan.direct/drop/emaillink2.gif

there must be a missing factor that is triggering it for you that I'm not doing. Do you have a hunch on what it might be based on watching my gifs?

**Comment by tiagomreis** [comment]
@alanhartless, this is the test code.

<html>
<head>
	<title></title>
</head>
<body>
<p>Teste de <a href="http://google.com">links</a></p>
</body>
</html>

This was done by the builder, based on your gif.

One email was OK, all the others with no tracking url.

**Comment by alanhartless** [comment]
Yup works perfect for me. http://alan.direct/drop/emaillink3.gif

So let's try to figure out what's different between our setups to figure out what's triggering this bug.  

Just to confirm, when you send the email, the first lead has the /r/STRING link but the subsequent leads have google.com link.  Right?

And this happens when using any of the mailers? 

And we're both sending through a lead list and not through a campaign?

**Comment by mgproget** [comment]
the first lead has the /r/STRING link but the subsequent leads have google.com link. Right?

Yes

And this happens when using any of the mailers?

Yes

And we're both sending through a lead list and not through a campaign?

No. I'm sending from a campaign that use a lead list. I've tried with a very simple campaign with one lead list and a 'sen email' action.

**Comment by tiagomreis** [comment]
Same thing, create email template using the builder or souce code on the txt file, create a campaign and associated a list with only 5 leads. Send it.

The lead with lower ID, receive the email with /r/TRACKID and the other 4 leads, receive the google link

**Comment by mgproget** [comment]
@alanhartless I see no differences in your .gif, except for emaillink2.gif, I cannot find this graph, but maybe it's just a custom report you've made.
Some things that could or not matter:
- php version 5.6.16
- I've never setup "Monitored Inbox Settings".
- I've tried changing e-mail language to English (I was using italian), same result one e-mail with redirect link only.
Please do not hesitate to suggest any test that I could try, thank you very much.

**Comment by alanhartless** [comment]
`create a campaign` <- that may be the key.  I was testing with a mass list send.  @mgproget are you using a campaign as well? Let me setup a campaign to test with.

**Comment by mgproget** [comment]
@alanhartless Yes, I'm using a campaign.

**Comment by alanhartless** [comment]
Ok, I did confirm the issue and fixed it.  It'll be part of 1.2.3 since it was a bigger bug. It's part of bigger code changes so probably not easy to patch on your system.  Might have to wait till 1.2.3 is released this week.

**Comment by mgproget** [comment]
@alanhartless Ok, Alan, thank you very much. Should you need help in testing, I'm here.
Pietro

**Comment by escopecz** [comment]
@mgproget tests are always welcome. Here is described the testing workflow: https://github.com/mautic/mautic#how-to-test-a-pull-request
