### ISSUE TITLE
Twilio usage shutdown, needs update

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#12479]
We have a deprecation coming on the Twilio plugin if not updated.

### Source
From https://support.twilio.com/hc/en-us/articles/14910496447771-Shutdown-of-Unregistered-10DLC-Messaging-FAQ

> **Shutdown of Unregistered 10DLC Messaging FAQ**
Effective July 5, 2023, all [10DLC phone numbers](https://support.twilio.com/hc/en-us/articles/360038173654-What-are-the-differences-between-long-codes-short-codes-and-Toll-Free-numbers-for-messaging-to-US-Canada-) used to send SMS and MMS messages to U.S. phone numbers must be fully registered to an approved campaign under your brand. Messages sent using unregistered phone numbers will be subject to a gradual increase of message blocking by Twilio, beginning on July 5, 2023, ultimately leading to a full block of all unregistered U.S.-bound messages sent after August 31, 2023. This article outlines our recommended best practices for making sure you’re registered, and answers common questions on the upcoming changes. For full details of the A2P 10DLC registration process, see [What is A2P 10DLC](https://support.twilio.com/hc/en-us/articles/1260800720410-What-is-A2P-10DLC-).

**Comment by npracht** [comment]
@kuzmany you have worked in this. Do you understand in detail what it implies and what need to be updated ?

**Comment by kuzmany** [comment]
@npracht first time see it, I will open discussion on community side, probably somebody already have experience with it

**Comment by npracht** [comment]
https://support.twilio.com/hc/en-us/articles/223181308-Getting-started-with-Messaging-Services#h_01F906R5EREGT1ZRCZA67WBNDP

 

Step 4 is the important part.  Instead of sending the number, you send the MessagingServiceSid and then Twilio selects the number automatically.  That’s the only code change.  So there are two steps:

 

Add the MessagingServiceSid param to the plugin
If the MessagingServiceSid has a value, then send it instead of the number

**Comment by kuzmany** [comment]
> Add the MessagingServiceSid param to the plugin
> If the MessagingServiceSid has a value, then send it instead of the number

Yes, something like that.

**Comment by npracht** [comment]
We already support SID in plugin.
https://docs.mautic.org/en/plugins/twilio
