### ISSUE TITLE
Your bug title goes here!

### ISSUE THREAD

**Issue by RichardRalston** [mautic/mautic#12472]
### Mautic Version

5.0.x series

### PHP version

8.0.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After installation completes the application will point to the dashboard which is not available.

I have deleted and re-created the site twice it fails at the same spot

There are errors reported in Apache or in mautic

### How can we reproduce this issue?

Step 1: Using built-in Apache on google cloud Debian 11 image install PHP and all components
Step 2: Create MySQL database on Google SQL service
Step 3: assign database permissions SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, REFERENCES
Step 4:create Apache site proxy (can provide if requested)
step 5:extract files to the application directory
step 6:use the web page to install but I cannot set up an email forwarder at this time.  (note there were no issues flagged by the installer)
next page fails with a 404

### Relevant log output

```shell
no logs produced
php modules
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

apache version 2.4.56
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
