### ISSUE TITLE
Logic error with contact fields value (multi selection)  for segmentation

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#12484]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Situation - contact should get send a mail depending on their product interest. Product interest is stored as a contact field with multiple select.

Logic is as follows:

1) client interested in (a OR b) AND NOT (c OR d) -> gets send mail 1
2) client interested in (c OR d) AND NOT  (a OR b) -> gets send mail 2
3) client is interested in (a OR b) AND (c OR d) -> gets send mail 3

We build it as segments:

First it works fine:
contact Field "Product Interest" **including** a,b ... works fine, it triggers when its either a OR b ... or a AND b
... working.

Segment 1)
contact Field "Product Interest" **including** a,b
AND
contact Field "Product Interest" **excluding** c,d 

That's the logic. But it breaks: Mautic now checks for (a **_AND_** b) AND NOT (c **_AND_** d) 
As soon as we combined to conditions with AND, also the single conditions "including" becomes an AND instead OR.
The same error happens for Segment 2) and Segment 3). 

Now we tested the same with tags and it works:

Segment 1)
Tags **including** a,b
AND
Tags **excluding** c,d

Valid entries are for instance: 
- a
- b
- a,b

or Segment 3)
Valid entries are for instance: 
- a,c
- b,d
- a,b,d ...

### How can we reproduce this issue?

Step 1: Create a Multi Select field with 4 properties
Step 2: Create segments with above conditions - one time with checking the values, one time with checking for tags
Step 3: Create a couple of contacts with different interest and the same interest added as tags
 
The segments will have different number of contacts, while they should be the same.

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @dsp76 do we need to keep this one open?

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please feel free to request a re-open if needed.
