### ISSUE TITLE
gui Issue on smaller laptop screens

### ISSUE THREAD

**Issue by dryland404** [mautic/mautic#1248]
details
Win 7 
Chrome
Mautic 1.2.2

On smaller screens (laptops) the form designer gui has components that are unreachable due to being off the bottom of the screen. 
Design should either auto size the pan to the screen size or provide a scroll bar.
![2015-12-16 08_42_54-](https://cloud.githubusercontent.com/assets/16322137/11842506/08e9c0d6-a3d2-11e5-8e79-9c80b2f85578.png)

**Comment by escopecz** [comment]
This is fixed for some time now
