### ISSUE TITLE
Subdirectory install = Forbidden

### ISSUE THREAD

**Issue by pablorq** [mautic/mautic#12496]
### Mautic Version

4.4.x series

### PHP version

8.0.29

### What browsers are you seeing the problem on?

Firefox

### What happened?

After copy the files on a subdirectory from the root web server, access to URL https://myserver.com/mautic/ result in:

># Forbidden
>
>You don't have permission to access this resource.

The access to https://myserver.com/ works ok.

### How can we reproduce this issue?

Step 1: Setup an apache server
Step 2: Extract the files and move to /mautic on the server
Step 3: Go to https://myserver.com/mautic/

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by pablorq** [comment]
Workaround:

Modify the .htaccess:

```
- <If "%{REQUEST_URI} =~ m#^/(index|index_dev|upgrade/upgrade)\.php#">
+ <If "%{REQUEST_URI} =~ m#^/{subdirectory}(index|index_dev|upgrade/upgrade)\.php#">
```

For example, to install it in the "/mautic" subdirectory:
```
<If "%{REQUEST_URI} =~ m#^/mautic/(index|index_dev|upgrade/upgrade)\.php#">
```
