### ISSUE TITLE
Focus Item on mobile not respecting customfields

### ISSUE THREAD

**Issue by ShareBtech** [mautic/mautic#12502]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Chrome, Safari

### What happened?

When creating a focus item and using personalization from the contact card like {contactfield=firstname}, this works well on dekstop and there is no problem displaying it and/or using customfields inside links as well, however on mobile it does not respect the {contactfield=}.  It will just show up on mobile as "Hi {contactfield=firstname}" 

### How can we reproduce this issue?

Step 1:  
1. Create any type of focus item.
2. Add a customfield tag to something inside the focus item.
3. Check the focus item on desktop - works.
4. Check it on mobile - does not work as expected.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @ShareBtech is this still an issue in the latest version of Mautic?

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please feel free to request a re-open if needed.
