### ISSUE TITLE
Contact list filtering by segment does not work

### ISSUE THREAD

**Issue by patrykgruszka** [mautic/mautic#12511]
### Mautic Version

5.0.x series

### PHP version

8.0.12

### What browsers are you seeing the problem on?

Not relevant

### What happened?

If a segment filter is applied to the contact list (e.g. /s/contacts?search=segment:segment-test-1), nothing changes - the entire list is displayed.

### How can we reproduce this issue?

Step 1: Run latest 5.x branch (https://gitpod.io/#https://github.com/mautic/mautic/)
Step 2: Create contacts and segment or just load data fixtures using command: `ddev exec bin/console d:f:l`
Step 4: Go to Segments and click on the link to contact list
![image](https://github.com/mautic/mautic/assets/8580942/fcb475a4-1cad-48ac-a741-a9bfb1d8a54b)
Step 5: There are no contacts in segment **lead-list-1**, but the entire contact list is displayed
![image](https://github.com/mautic/mautic/assets/8580942/c5489d42-1256-406c-a6e6-ffb21dccd50a)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
@mabumusa1 could you please look at it with your Doctrine expertise? I traced the issue to 

https://github.com/mautic/mautic/blob/5.x/app/bundles/LeadBundle/Entity/ExpressionHelperTrait.php#L38

where the second filter for the segment alias is not added to the `CompositeExpression` and I don't get why.

**Comment by escopecz** [comment]
Actually, I have the fix. It was pretty simple. The `with` function is immutable. PR coming soon.

**Comment by escopecz** [comment]
Ready for testing

**Comment by patrykgruszka** [comment]
This issue has been resolved in #12513. Thank you @escopecz!
