### ISSUE TITLE
Add links to {unsubscribe_text} token [feature request]

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#1251]
I try to add /a href="link"/ in this token but is not possible :(

I can add the url clean http://pppppp.com/about and some mail clients accept it as a link but mautic dont track the clicks made in this link.

**Comment by alanhartless** [comment]
I'm not sure I follow.  

Is the issue that links don't work at all when in the {unsubscribe_text} token or is it that they are not converted into a trackables? If it's that they aren't converted into trackables, I think it's the same issue as #1042.

**Comment by miguelpascual** [comment]
If I add this:

![image](https://cloud.githubusercontent.com/assets/10166840/11896518/632a69fe-a587-11e5-89df-bc38fb91d450.png)

I get in preview this:
![image](https://cloud.githubusercontent.com/assets/10166840/11896533/971f7718-a587-11e5-9ab4-d0aa19dc0d31.png)


If I add this:
![image](https://cloud.githubusercontent.com/assets/10166840/11896589/170150b4-a588-11e5-9f4a-cf6440c80544.png)


I get in preview this:
![image](https://cloud.githubusercontent.com/assets/10166840/11896580/0057aab6-a588-11e5-8b4b-09d4cd02cc73.png)

(The link works but is not tracked by mautic it go directly to google)

**Comment by alanhartless** [comment]
Ah ok.  Yea that's the same issue as what's causing #1042.  I'm going to close this as a duplicate and clarify the title of the other to include this.
