### ISSUE TITLE
 remain at form does not work after form submission

### ISSUE THREAD

**Issue by joachim-n** [mautic/mautic#12527]
### Mautic Version

4.4.x series

### PHP version

8.1.13

### What browsers are you seeing the problem on?

Firefox

### What happened?

I created a form in Mautic and set it to 'Remain at form'.

Using the Mautic integration module in Drupal (https://www.drupal.org/project/mautic_paragraph) I created a block which shows the form.

My form is visible in my local dev environment at the page http://localhost:8888/mautic-web-factorial/web/. When I submit the form, the browser redirects to http://localhost:8888. The form in Mautic shows that the submission was successful.

I also tried embedding the form in a plain HTML page, visible at http://localhost:8888/mautic-web-factorial/test-mautic-form.html. When I submit this form, I get redirected to http://localhost:8888.

Finally, I tried embedding the form in a plain HTML page in the webroot, at http://localhost:8888/test-mautic-form.html. When I submit this form, I get redirected to http://localhost:8888.

### How can we reproduce this issue?

1. Create a form in mautic
2. Get the automatic Form HTML, Javascript version
3. Put it in an HTML file
4. Open the HTML in browser, submit the form

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
Just tested it with 4.4.9 in our production environment. 
Embedded the test in this page: https://twentyzen.com/de/stay-in-form/
It stays after submission. Please switch to the mautic forum at [forum.mautic.org](forum.mautic.org) and open a discussion in the support section.

Its not a but. I could imagine, its related to test environment without https etc. This is causing some trouble sometimes.
