### ISSUE TITLE
Documentation - mention disallowing robots hits with the robots.txt file

### ISSUE THREAD

**Issue by ondraknezour** [mautic/mautic#1253]
Inspired with this post https://www.mautic.org/community/index.php/1335-exclude-bots-from-leads-list/p1#p5454 I would like to propose mentioning usage of the robots.txt file somewhere in the documentation with example like

User-agent: *
Disallow: /path-to-your-mautic/mtracking.gif

**Comment by alanhartless** [comment]
I'm not sure that would work.  Shouldn't bots that scan your site with the tracking pixel embedded still result in a hit to the tracking pixel which will log the IP as anonymous?

**Comment by ondraknezour** [comment]
It should work. Each image embedded in the page require new HTTP request and this particular one is disallowed in the robots.txt file, so it should not occur.

**Comment by ondraknezour** [comment]
I disallowed our tracking pixel for all robots yesterday and submitted the new robots.txt file to the Google. After couple of hours all requests for given URL stopped. Before we got hit each one to two hours, none appeared in last nine hours. Will see in couple days if it is permanent change and this solution can be considered working.

**Comment by nvoi** [comment]
it would be great if a list of default user-agents would be easy to add to the robots.txt file, e.g. based on  www.useragentstring.com/pages/api.php

**Comment by escopecz** [comment]
Anyone can improve the docs: https://github.com/mautic/documentation#how-to-contribute-to-the-docs
