### ISSUE TITLE
API credentials filtering does not work

### ISSUE THREAD

**Issue by nick-vanpraet** [mautic/mautic#12537]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

The filtering for the API credentials overview does not seem to work. No matter what I fill in, nothing gets filtered.

### How can we reproduce this issue?

Step 1: Install Mautic
Step 2: Enable API
Step 3: Create some API credentials
Step 4: try to filter

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
Do you mean list contacts? https://developer.mautic.org/?json#list-contacts 
Or anything else?

Could you please provide the call you made and the results you expected to see?

**Comment by nick-vanpraet** [comment]
No, I mean the filtering for the API credentials overview, located at /s/credentials

![image](https://github.com/mautic/mautic/assets/7923739/c054e0e2-c76d-4869-b66e-2353145e90e4)

**Comment by RCheesley** [comment]
This is now resolved with the new UI/UX work in 5.2 so closing the issue.
