### ISSUE TITLE
Invalid login. Please verify credentials. | Azure SAML authentication successful but unable to create user in the mautic | Solved!

### ISSUE THREAD

**Issue by nameisazeem** [mautic/mautic#12532]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

I have integrated SAML authentication for Mautic with Azure as IDP everything has configured accordingly and I have got success in Azure sign in logs, but Mautic was unable to create that user. I got this error
![image](https://github.com/mautic/mautic/assets/55396535/617f1ea0-6b6a-4aab-a01f-e45f256502d6)

### How can we reproduce this issue?

Can someone please guide me through. 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by nameisazeem** [comment]
This has been solved. We found out we needed to use the full xml URL based specification instead of the names of the specification or specification IDs provided by microsoft.

*you can find those urls in the **IDP**s metadata xml file.*

**Don't**
![image](https://github.com/mautic/mautic/assets/55396535/4d3382af-2419-4f6d-a04b-cdfea365ecb7)

**Do**
![image](https://github.com/mautic/mautic/assets/55396535/910c2d6f-e93c-4c20-8437-10ae36a481b2)


**instead of **
surname or Surname as specified in the azure admin portal and the xml.

**Comment by mabumusa1** [comment]
@nameisazeem Thanks for the follow-up. I would love to have you as a Mautic contributor, do you mind adding this tip to docs?

**Comment by nameisazeem** [comment]
Hello @mabumusa1 I don't mind at all. Thank you for asking.
