### ISSUE TITLE
Campaign action contact delete hit Allowed memory size

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#12540]
### Mautic Version

5.0.x series

### PHP version

8.0

### What happened?

Setup campaigns with 50 000 contacts with Contact delete action.
After some batch it hit Allowed memory size error.

### How can we reproduce this issue?

Step 1:  Create campaign with Contact delete action
2. Add 50 000 contacts
3.  Run it
4. You should see hit   Allowed memory size about 20 000 contacts

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mabumusa1** [comment]
@kuzmany what are the settings are using to execute `campaign:trigger` command? I think it has to deal with the number of threads you are using and the number of contacts per batch https://github.com/mautic/mautic/blob/5.x/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php#L289

**Comment by kuzmany** [comment]
Good point.  We use 

I do not think it can help but we can test it. 
It happens just for this action, for other campaign actions, we can process with mils of contacts.
We noticed it with each batch it increases by about 4MB on ram. 

Now we are using  `mautic:campaigns:trigger --campaign-limit=10000 --batch-limit=500` It should be safe

**Comment by mabumusa1** [comment]
I think the issue is around this [line](https://github.com/mautic/mautic/blob/5.x/app/bundles/LeadBundle/Model/FieldModel.php#L667), it should implement batching like this [function](https://github.com/mautic/mautic/blob/5.x/app/bundles/CoreBundle/Entity/CommonRepository.php#L179)

**Comment by RCheesley** [comment]
@kuzmany @mabumusa1 is this something we're still planning to address? If so, what kind of timeline? If not, let's close the issue?

**Comment by kuzmany** [comment]
We do not have solution fo rit
