### ISSUE TITLE
Email Link dont track the user

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#1254]
I send a mail Thx for your suscription to a new lead (me) and I click these link but this visit and form submit is not added to the previous new lead but it appear as a another lead :(

![image](https://cloud.githubusercontent.com/assets/10166840/11866062/da1a2e26-a4a8-11e5-8a3b-d6f867a8950f.png)

![image](https://cloud.githubusercontent.com/assets/10166840/11866094/0bd379b8-a4a9-11e5-8566-f0af6f998bb9.png)

I use the same ip but the identified lead dont have IP recorded :S

**Comment by alanhartless** [comment]
See if #1219 solves this.

**Comment by miguelpascual** [comment]
I think is a problem related to my ip or similar. For users is running correctly now but when I did testing (event deleting myself lead and anonymous browsing mautic done strange things)
