### ISSUE TITLE
Select your preferences

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#1255]
Hi 
I have a problem when I try to identify users in one anonymous form (form without email field)... 

I'll explain now. I hate spam and I want to offer users different kinds of suscriptions:

In the welcome email we send a link to this form:

Landing:
![image](https://cloud.githubusercontent.com/assets/10166840/11847689/ee6341fe-a41e-11e5-8472-0af98684e527.png)

Campaign to assign each user to list 

![image](https://cloud.githubusercontent.com/assets/10166840/11847719/1783982c-a41f-11e5-9d09-6f3d9ad2b9d9.png)

![image](https://cloud.githubusercontent.com/assets/10166840/11866362/f1529d1a-a4aa-11e5-9373-b2d25d66eb9d.png)

Why it dont work? Or There is another way for do it better?
Only did remove from list not add to list (like operator could be correct)

![image](https://cloud.githubusercontent.com/assets/10166840/11866639/ae551f68-a4ac-11e5-827c-c4e043dbecc5.png)

INFO:
In log I have this error:
[2015-12-17 09:42:08] mautic.NOTICE: PHP Notice: Undefined index: public - in file /var/www/vhosts/mawww/app/bundles/CoreBundle/Templating/Helper/SlotsHelper.php - at line 45 [] []

**Comment by miguelpascual** [comment]
If I select only one option it works

![image](https://cloud.githubusercontent.com/assets/10166840/11869611/7001aa28-a4c1-11e5-9589-2141904b632a.png)

I think the like command dosn't have the * to do a like "*piscinas*"

**Comment by miguelpascual** [comment]
And there is another problem. When one user activate one campaign if they want to change their preferences the second time the campaign dont run

![image](https://cloud.githubusercontent.com/assets/10166840/11874565/b6f36b82-a4e0-11e5-92be-f93306f1e47b.png)

**Comment by miguelpascual** [comment]
I think the problem is in the opperator like and I think it dosn't have the * in like "*test*"

**Comment by alanhartless** [comment]
Is this the same issue in #1229?

**Comment by miguelpascual** [comment]
yes this with more explanation :D

**Comment by miguelpascual** [comment]
UPDATE:

I have only a problem: When a lead complete the campaign cannot change their preferences.
I added a remove from campaign action
![image](https://cloud.githubusercontent.com/assets/10166840/11896232/0ee66b24-a585-11e5-9bd9-28d1d1f2e88b.png)

But even removing manually the lead from the campaign it don't rerun the campaign when complete the form again.

![image](https://cloud.githubusercontent.com/assets/10166840/11896310/b0471efa-a585-11e5-9050-fd1d276ccdd1.png)
In this image we can see when a new form send dont make the campaign start :(

**Comment by alanhartless** [comment]
Right now, if a lead is removed from a campaign within a campaign, its marked as a "manually removed" so that they are not automatically added back if the campaign is based on a list with filters. When they are added to a campaign via a form submit, they are marked as "manually added" to keep lead lists from removing the lead based on filters.  

In this case, when they re-submit the form, they are noted as being "manually removed" from the campaign and thus not added back automatically.  Can you confirm this by looking in your database at the `campaign_leads` table for the lead that should have been removed from the campaign.  What values do they have for the manually_removed and manually_added columns?

I can see where that can be an un-wanted behavior.  Seems we need a new flag to note if the lead was manually added by a user or manually added by an automated event (not a lead list filter).

**Comment by miguelpascual** [comment]
The lead is added to the campaign via form submit not smart list.
![image](https://cloud.githubusercontent.com/assets/10166840/11926194/20c49f2e-a7c3-11e5-9f01-22412376e3e6.png)

The campaign 1

![image](https://cloud.githubusercontent.com/assets/10166840/11926219/41d8366c-a7c3-11e5-99d5-7a0171ad7a0c.png)

Test: 

I deleted my data (miguel@interd) And now I'm not in the ddbb and campaign:

![image](https://cloud.githubusercontent.com/assets/10166840/11926279/ae709422-a7c3-11e5-8439-51d25c0e9307.png)
![image](https://cloud.githubusercontent.com/assets/10166840/11926285/b3a26808-a7c3-11e5-814a-ef1c526cd1bb.png)

I register my data as a new lead and send the form to try preferences. 

1º If using one anonymous browser I fill the register form and I go directly to preferences form and I get 2 leads (one with mail and other anonymous that has filled the preferences form) :S Why it dont take the ip or cookie to merge both actions?


2º I restart the test (delete leads etc): Now I fill the preferences form coming from the link in email (thx for register select your preferences) now I have only one lead that is register and filled the form preferences.

The lead is automaticly removed by the 
![image](https://cloud.githubusercontent.com/assets/10166840/11927107/65a4137a-a7ca-11e5-9716-5ce7bb194889.png)

But When I refill the preferences form Nothing appends. The campaign dont run again.

In the ddbb is check manually added:
![image](https://cloud.githubusercontent.com/assets/10166840/11927130/99e7eac6-a7ca-11e5-8a6d-6cf73ae87b05.png)

I need the campaign run each time the user change their preferences. Is it possible?

**Comment by miguelpascual** [comment]
Probably this solution is better than mine --> https://github.com/mautic/mautic/issues/1173#issuecomment-166620646

Asign to a core field the data selected and build smart list with conditions (like the core field)

**Comment by RegisScaggiante** [comment]
when I used the "select" data type core field the filter of smart list not working perfectly. when I started to use the "Text" data type core field, the filter of smart list worked better.
The saved data are separated by commas in the same way.
See if that works for you

**Comment by miguelpascual** [comment]
Thats work. The problem is the same in my campaign change the preferences. If I change the data in the Test field "cursos, otros, algo" to "otros, algo" the smart list dont remove the Lead from the list "cursos"

**Comment by miguelpascual** [comment]
Solved with a standalone form and the action "remove from list" 

![image](https://cloud.githubusercontent.com/assets/10166840/11975729/1418af4a-a971-11e5-8381-b86e463d4c8f.png)

**Comment by escopecz** [comment]
Closing this issue as the result is created the bug request https://github.com/mautic/mautic/issues/1287
