### ISSUE TITLE
Change UI for scheduled email

### ISSUE THREAD

**Issue by jos0405** [mautic/mautic#12555]
### Mautic Version

5.0.x series

### PHP version

7.4, 8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The current way of scheduling email is confusing for many users.
The word published is used 2x:
![image](https://github.com/mautic/mautic/assets/4246909/0dee4a1e-23ab-434b-958c-e35dedd89a85)

Suggestion from @npracht is to have multiple steps in the UI to achieve the same result.
A new schedule button could be introduced (users are looking for it anyway)
![image](https://github.com/mautic/mautic/assets/4246909/04dd4c4a-6c01-4a47-8398-21a82ace5fe5)
Clicking on it would open a modal:
![image](https://github.com/mautic/mautic/assets/4246909/43e3c3d0-8eae-4cbc-8b0d-06fcbbeb7391)
If you choose yes, then a "unpublish date" could be added to preserve current functionality.

### How can we reproduce this issue?

Step 1: Open an email to send
Step 2: Be confused.

### Relevant log output

```shell
None
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Work in progress on @webmecanik side.

**Comment by npracht** [comment]
New UI landing --> https://github.com/mautic/mautic/pull/12832

**Comment by kuzmany** [comment]
Added more screenshots and context https://github.com/mautic/mautic/pull/12832 
Ready to tests
I will add unit tests add on friday I hope

**Comment by andersonjeccel** [comment]
I believe it's fixed now, reopen if not
