### ISSUE TITLE
Bug - Form submission updates wrong lead

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1256]
Hi,

We've noticed that the **form submission of a lead can update a wrong lead**.
* Form integrated onto a website via \<script\> feature
* 2 unkown leads submit the form
* Same IP address
* Different email address for the leads (no unique ID in common)

**---> The second lead erase the first = modify email address, name...**

![capture d ecran 2015-12-17 a 14 01 41](https://cloud.githubusercontent.com/assets/14075239/11870470/6f91fa5a-a4c8-11e5-98cc-6db4cbc78f7a.png)
![capture d ecran 2015-12-17 a 14 01 48](https://cloud.githubusercontent.com/assets/14075239/11870471/6f93ad50-a4c8-11e5-8e53-198a96605805.png)
![capture d ecran 2015-12-17 a 14 01 54](https://cloud.githubusercontent.com/assets/14075239/11870469/6f91b70c-a4c8-11e5-8b60-17d30e152f7e.png)

I think it's a terrible issue, merging 2 different leads cause the soft thinks thy are the same :(
Tell me if you have all information you need.

N.

**Comment by alanhartless** [comment]
See if #1219 solves this.

**Comment by npracht** [comment]
Hi @alanhartless ,

I don't think this is the same issue, in my case the submission is done from a different laptop, --> different cookie, different email.

Different case, isn't it ?

N.

**Comment by npracht** [comment]
Hi @alanhartless ,

Did you have the opportunity to check more about this issue ? This is very critical in terms of marketing automation feature. Merging contacts create critical risks ---> Sending information to the wrong lead.

Thanks a lot for your help and feedbacks.

N.

**Comment by alanhartless** [comment]
@npracht That PR (now in 1.2.3) should prevent this from happening for form posts. Are you creating the lead via a different method? 

There's a discussion for finding leads based on IP in #1030.

**Comment by npracht** [comment]
Let me try to reproduce on that PR and i'll tell you if that works now or not :)

N.

**Comment by npracht** [comment]
Hi @alanhartless ,

I've migrate to 1.2.3 and i cannot reproduce the bug anymore. It seems it has corrected the issue.
Good job :smile: 

N.
