### ISSUE TITLE
Using primary company variables in Email Template

### ISSUE THREAD

**Issue by pascalinger** [mautic/mautic#12563]
### Mautic Version

4.4.x series

### PHP version

8.0.20

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I used the variables as per https://docs.mautic.org/en/setup/variables to output some company data (assuming that the variables would output the contact's primary company's data). I am using the data in an URL:

https://some.domain/text?company_email={contactfield=companyemail|}

All variables are output correctly but the company-specific ones.

### How can we reproduce this issue?

Step 1: Create email template using company-specific variables.
Step 2: Send an email to a contact on-demand or in a campaign.
Step 3: Verify the values are not populated.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by pascalinger** [comment]
Adding some details:

When using the variables in a campaign, the values seem populated correctly in v4.4.9.
When using the variables in a "Send Email" on demand action on the contact detail screen, the values are not propagated correctly.

**Comment by jos0405** [comment]
Hi, this issue is fixed in M5.
You can also merge this into M4.4.9, it will work.
https://github.com/mautic/mautic/pull/11711

In case I'm wrong, plz reopen this case!
