### ISSUE TITLE
Errors thrown in focus item builder in 5.x branch

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#12577]
Mautic version: 5.x branch

The Preview for Focus Items in the FI-Builder is broken and following error got logged on saving the focus item:

`[2023-07-22 09:11:18] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/s/ajax" is not callable: Method "generatePreviewAction" on class "MauticPlugin\MauticFocusBundle\Controller\AjaxController" should be public and non-abstract." at /var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php line 88 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/s/ajax\" is not callable: Method \"generatePreviewAction\" on class \"MauticPlugin\\MauticFocusBundle\\Controller\\AjaxController\" should be public and non-abstract. at /var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php:88, InvalidArgumentException(code: 0): Method \"generatePreviewAction\" on class \"MauticPlugin\\MauticFocusBundle\\Controller\\AjaxController\" should be public and non-abstract. at /var/www/html/vendor/symfony/http-kernel/Controller/ControllerResolver.php:134)"} {"hostname":"mautic-web","pid":2078}
`
This bug was not reproducible on the 5.0 alpha tagged release (I checked via Gitpod using the tag), so it looks like something may have slipped the net in between.

_Originally posted by @oltmanns-leuchtfeuer in https://github.com/mautic/mautic/pull/11945#pullrequestreview-1542073864_

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/commit/9be9da4669792578541f7f18b2ab39d331e648b0
