### ISSUE TITLE
Forms and Website builder not working: You do not have access to the requested area/action

### ISSUE THREAD

**Issue by stepcellwolf** [mautic/mautic#12584]
### Mautic Version

4.4.x series

### PHP version

8.0.29

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### What happened?

I'm not able to create fields in a forms and building a website in a builder - drag and drop or select any type does not work. When I try to create a form I get the following message: You do not have access to the requested area/action

### How can we reproduce this issue?

This issue can be reproduced in in Safari, Chrome and Firefox

1. Go to Components
2. Click on Forms
3. Click on any Select - both same issue new campaign or standalone form
4. Add name on the campaign form
5. Click on Fields
6. Try to select any add a new field dropdown
7. Pop up shows that You do not have access to the requested are/actions

### Relevant log output

```shell
These errors are showing in the log:
/var/www/mautic/var/logs/mautic_prod-2023-03-17.php
[2023-03-17 10:52:57] mautic.WARNING: Grapesjs: no template in query {“hostname”:“[host]”,“pid”:1717621}

Even edit of the Submit button does not load anything.

XHRGEThttps://list.[HOST]/s/forms/field/edit/1?formId=1&_=1679051776739&mauticUserLastActive=11&mauticLastNotificationId=
[HTTP/2 200 OK 88ms]

GET
https://list/.[HOST]/s/forms/field/edit/1?formId=1&_=1679051776739&mauticUserLastActive=11&mauticLastNotificationId=
Status
200
OK
VersionHTTP/2
Transferred840 B (13 B size)
Referrer Policystrict-origin-when-cross-origin
Request PriorityHighest

access-control-allow-credentials
true
access-control-allow-headers
Origin, X-Requested-With, Content-Type, Authorization
access-control-allow-methods
PUT, GET, POST, DELETE, OPTIONS
access-control-allow-origin

access-control-max-age
36000
cache-control
max-age=0, must-revalidate, private
content-security-policy
upgrade-insecure-requests
content-type
application/json
date
Fri, 17 Mar 2023 11:16:28 GMT
expires
Fri, 17 Mar 2023 11:16:28 GMT
permissions-policy
interest-cohort=()
server
nginx
strict-transport-security
max-age=63072000; includeSubDomains; preload
x-content-type-options
nosniff
x-download-options
noopen
X-Firefox-Spdy
h2
x-frame-options
SAMEORIGIN
x-permitted-cross-domain-policies
none
x-sso-wat
You've just been SSOed
x-xss-protection
1; mode=block

Accept
application/json, text/javascript, /; q=0.01
Accept-Encoding
gzip, deflate, br
Accept-Language
en-US,en;q=0.5
Connection
keep-alive
Cookie
messagesUtk=3791286360f643c0b6eca74dbb6415e5; mautic_device_id=di7n5rig60i5a72x8fefc4e; 723b8415532a45d02f3a7b6b06e8bdd1=e0i0ee6c91554kon9g76ra3mrq
DNT
1
Host
list.host
Referer
https://[HOST]/s/forms/edit/1
Sec-Fetch-Dest
empty
Sec-Fetch-Mode
cors
Sec-Fetch-Site
same-origin
TE
trailers
User-Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
X-Requested-With
XMLHttpRequest
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Linking to the forum post: https://forum.mautic.org/t/forms-and-website-builder-not-working/27383

Per the discussions on Slack this is not reproducible with Mautic for other users, and is most likely due to your hosting configuration - therefore it's not a Mautic bug. This will need to be discussed in the forums, not here, as GitHub is only for bugs rather than help with configuration.
