### ISSUE TITLE
HTML characters in contact campaign e-mail events 5.x

### ISSUE THREAD

**Issue by annamunk** [mautic/mautic#12586]
### Mautic Version

5.0.x series

### PHP version

8.0.20, 8.1.6

### What browsers are you seeing the problem on?

Chrome

### What happened?

In Contact details page (s/contacts/view/{id}) HTML characters in campaign events are not processed and become part of the text:
![events](https://github.com/mautic/mautic/assets/102536220/d0d0e267-b26a-4ac5-9bb4-f8dd8b88f90e)
![events_2](https://github.com/mautic/mautic/assets/102536220/9d879069-7e16-47bf-9739-36b8b12bec91)
![upcoming_events](https://github.com/mautic/mautic/assets/102536220/d9306408-7908-4d9a-94b0-159bb54c39f9)

### How can we reproduce this issue?

Step 1: Create campaign with send email action. 
Step 2: Trigger campaign event. 
Step 3: Check the event history and upcoming events of the contact involved in the campaign (s/contacts/view/{id}).

### Relevant log output

```shell
--
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Pretty sure that this has been addressed with the UX changes recently but shout if it needs re-opening!
