### ISSUE TITLE
JS errors when using the focus item builder

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#12588]
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When creating a focus item there errors in the console:

```
libraries.js?v735f0f9d:711     POST https://8080-mollux-mautic-nc7867u6zoh.ws-eu102.gitpod.io/s/ajax?action=plugin:focus:generatePreview&mauticUserLastActive=409&mauticLastNotificationId= 500
send @ libraries.js?v735f0f9d:711
ajax @ libraries.js?v735f0f9d:688
ajaxActionRequest @ app.js?v735f0f9d:38
Mautic.focusUpdatePreview @ focus.js:291
Mautic.launchFocusBuilder @ focus.js:233
onclick @ VM145 1:1
trigger @ libraries.js?v735f0f9d:630
(anonymous) @ libraries.js?v735f0f9d:635
each @ libraries.js?v735f0f9d:99
each @ libraries.js?v735f0f9d:90
trigger @ libraries.js?v735f0f9d:635
jQuery.fn.<computed> @ libraries.js?v735f0f9d:741
buttonClick @ app.js?v735f0f9d:71
dispatch @ libraries.js?v735f0f9d:399
elemData.handle @ libraries.js?v735f0f9d:385
```

Also the z-index of the mautibot box on the focus item is too high I believe - so the focus items show behind it if you don't enter a URL - especially noticeable if you are using Emphasize links > Modal in the Top position! Not sure if this is by default or something new.

### How can we reproduce this issue?

Step 1: Create focus item and go to the builder
Step 2: Make a selection and check the console for the error

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
I cannot reproduce on the current 5.x branch. Please share an image if you get this issue again.
