### ISSUE TITLE
Change channels modal popup is missing save/cancel buttons

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#12597]
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Not relevant

### What happened?

If I select contacts in the contact list and change channels, the save/cancel buttons are missing - probably a Twig issue!

### How can we reproduce this issue?

Step 1: Select one or more contacts in list view
Step 2: Click to change campaigns
Step 3: Note that there is no save/cancel button, which is present for the other options.

![screenshot-8080-mautic-mautic-hq4xmwy3x5m ws-eu102 gitpod io-2023 07 26-19_09_23](https://github.com/mautic/mautic/assets/2930593/4ca26689-7be1-4dff-9595-ad9851105f5f)

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
Ready to test: https://github.com/mautic/mautic/pull/12608
