### ISSUE TITLE
Should not be able to merge a company with itself!

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#12599]
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When you merge a company, a list of available companies is shown, including the current company.

https://watch.screencastify.com/v/jKUDaG5FYYq2TwoTKlHh

This is nonsensical - you would never be merging a company into itself!

### How can we reproduce this issue?

Step 1: Open a company
Step 2: Select the option to merge with another company via the arrow at the top right next to close
Step 3: Notice that the current active company is being shown in the list - it should not be.

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by nishant-s7** [comment]
Hi there! Can I work on this issue?

**Comment by RCheesley** [comment]
Hi @nishant-s7 - for sure. Please verify the issue first (as this was raised quite some time ago) and then check our docs: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests for how to make a PR. Please use the 5.x branch.

**Comment by nishant-s7** [comment]
Hello! Sorry to bother if it is a newbie question but did I do something wrong with my PR?
