### ISSUE TITLE
Error no installer do Mautic 449

### ISSUE THREAD

**Issue by rafaeldros2023** [mautic/mautic#12614]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

We have an error in the Mautic installer 449, step 1, just after entering the database :

The parameter "2023" must be defined. - in file /home/u88168xxxx/domains/blog.xxxxxx.com.br/public_html/mkt/var/cache/prod/ContainerKvlxx3d/appAppKernelProdContainer.php - at line 7142

### How can we reproduce this issue?

Step 1: We have an error in the Mautic installer 449, step 1, just after entering the database

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
Can you try to delete the contents of this cache folder? /home/u88168xxxx/domains/blog.xxxxxx.com.br/public_html/mkt/var/cache/prod
