### ISSUE TITLE
 $contactApi->getList or endpoint /api/contacts search by email does not work

### ISSUE THREAD

**Issue by JosephGabito** [mautic/mautic#12612]
### Mautic Version

v4.4.10

### PHP version

8.1

### What browsers are you seeing the problem on?

Chrome

### What happened?

I encountered an issue while attempting to delete a contact by email using the contact API endpoint. The API documentation states that the `/delete` endpoint only accepts contact IDs, so I first attempted to find the contact ID via the `/contacts` list endpoint, which includes an option to search for specific values.

I tried using the `email:test@example.net` as a search query parameter (url encoded), but unfortunately, it did not work as expected. Instead of returning the contact with the specified email address, the API returned all contacts in the system, showing a total count of 350, even though I only have 3 contacts in my test installation. This issue also occurs when searching for a contact that doesn't exist, which yields the same result - all contacts are returned.

To confirm if the problem was due to my request (using Postman) or the SDK, I decided to install the SDK and use the following method to search for a specific contact:

```php
$contactApi->getList( 'email:text@example.net', 0, 1, '', 'ASC', true, true );
```

Unfortunately, this method also returned all contacts, not just the one with the provided email.

I am currently using basic authentication to access the API.

If anyone has encountered a similar issue or can provide any insights into whether this is a bug or if I'm making a mistake in my approach, I would greatly appreciate your help.

Thank you!

### How can we reproduce this issue?

Step 1: Follow the usual installation guide.
Step 2: Install the SDK
Step 3: Use the method `getList` to retrieve a contact matching a specific email.

### Relevant log output

```shell
1. SDK - https://share.cleanshot.com/28dcmWVd
2. Postman - https://share.cleanshot.com/jGZLmxFJ
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
Looks like I was able to confirm it with 4.4.9 as well. Do you also get an error 400 with it?
By the way - it probably counts your anonymous captured contacts together with the known contacts.

**Comment by JosephGabito** [comment]
Thank you for confirming the issue. I'm happy to know that it's not an isolated occurrence. I haven't encountered error 400 in relation to it. That's what I had assumed too. However, it appears that adding new contacts via the API does not result in an increase in the count (still 350).

**Comment by JosephGabito** [comment]
Was able to make this work. If you're using PHP with Guzzle and wanted to exclude anonymous users. You'll need to construct the URL like the following:

```text
{{baseUrl}}/api/contacts?search=!is:anonymous&limit=0&where[0][col]=email&where[0][expr]=eq&where[0][val]=email@example.com
```

The example above shows how we can query or find a contact by email.

**Comment by yunsii** [comment]
@JosephGabito Save my life! And there is no detailed documents about api query parameters? https://developer.mautic.org/#list-contacts

**Comment by yunsii** [comment]
Okey, I found this brief document about `search` in app.

![image](https://github.com/mautic/mautic/assets/18096089/6009f707-87f0-4e93-9a8d-2c052ac0d741)

That's enough for now, but I don't known why there is no extra information in developer docuement 😂

---

Moreover, multiple search conditions should joined by SPACE

**Comment by RCheesley** [comment]
Hey folks!

https://devdocs.mautic.org is the most up to date. We're trying to move everything over to there but some resources are still needing updating, hence why https://developer.mautic.org still exists.

Sorry about that! Feel free to help at https://github.com/mautic/developer-documentation-new - PRs most welcome!

Going to close this down now as it seems it's resolved.
