### ISSUE TITLE
Installation Mautic-Plugin via composer -- Installation failed --

### ISSUE THREAD

**Issue by laabidi21** [mautic/mautic#12631]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

I made a Switch to Composer in Mautic.
I installed composer and everything in the following instructions: https://docs.mautic.org/en/setup/switch-to-composer
composer version: **Composer version 2.5.8**
**composer diagnose**:
_Checking platform settings: OK
Checking git settings: OK git version 2.30.2
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.5.8
PHP version: 8.0.29
PHP binary path: /usr/bin/php8.0
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
cURL version: 7.74.0 libz 1.2.11 ssl OpenSSL/1.1.1n
zip: extension present, unzip present, 7-Zip not available_

I want to install a Plugin Recaptcha v3 from composer:
**composer require koco/mautic-recaptcha-bundle:3.**
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mautic/composer-plugin[1.0.0, ..., 1.0.1] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
    - koco/mautic-recaptcha-bundle[3.0.0, ..., 3.1.0] require mautic/composer-plugin ^1.0 -> satisfiable by mautic/composer-plugin[1.0.0, 1.0.1].
    - Root composer.json requires koco/mautic-recaptcha-bundle 3.* -> satisfiable by koco/mautic-recaptcha-bundle[3.0.0, 3.0.1, 3.1.0].

### How can we reproduce this issue?

Step 1: 

### Relevant log output

```shell
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mautic/composer-plugin[1.0.0, ..., 1.0.1] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.3.0] but it does not match the constraint.
    - koco/mautic-recaptcha-bundle[3.0.0, ..., 3.1.0] require mautic/composer-plugin ^1.0 -> satisfiable by mautic/composer-plugin[1.0.0, 1.0.1].
    - Root composer.json requires koco/mautic-recaptcha-bundle 3.* -> satisfiable by koco/mautic-recaptcha-bundle[3.0.0, 3.0.1, 3.1.0].
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
