### ISSUE TITLE
Not adding all contacts 

### ISSUE THREAD

**Issue by hmzdon** [mautic/mautic#12632]
### Mautic Version

5.0.x series

### PHP version

*.0

### What happened?

A bug happened!

### How can we reproduce this issue?

I'm adding 624 contacts csv list but mautic adds only 23 contacts I tried again and again but still the same problem. why mautic have bugs?

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
