### ISSUE TITLE
Campaign action "Jump to Event" can not be edited or deleted

### ISSUE THREAD

**Issue by adiux** [mautic/mautic#12639]
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When I create a campaign (from a segment) with 2 actions and then try to jump to the first action, I can not open or delete the "Jump to Event" action anymore. 

<img width="312" alt="image" src="https://github.com/mautic/mautic/assets/13075514/46067503-8e0f-460e-8e92-dd5b6105b5c9">

Trying to edit the "Jump to Event" action brings me to this window
<img width="1188" alt="image" src="https://github.com/mautic/mautic/assets/13075514/d2ebc579-f012-4313-8101-706648ee20ba">

Relevant code:
https://github.com/mautic/mautic/blob/e740f1b639e492866e5b2039d533c81dac0c497a/app/bundles/CampaignBundle/Model/CampaignModel.php#L178

Exact version: v5.0.0-alpha1 (08.08.23)

### How can we reproduce this issue?

Step 1: Create the campaig as in the printscreen with a "Jump to Event" action
Step 2: try to edit or delete the added action

### Relevant log output

```shell
Uncaught PHP Exception Error: "Call to a member function getId() on null" at /var/www/html/app/bundles/CampaignBundle/Model/CampaignModel.php line 181
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
Ready to test https://github.com/mautic/mautic/pull/12762
