### ISSUE TITLE
Mautic Marketplace plugin install -- does not react

### ISSUE THREAD

**Issue by laabidi21** [mautic/mautic#12633]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

Mautic Version: 4.4.9
Php: 8.0
Composer Version: 2.5.8
I chose a Plugin from Mautic - Marketplace, and by clicking on install a PopUp opens to start the installation but in Browser-debug an error which is as follows:

![image](https://github.com/mautic/mautic/assets/48432954/6a42d5a1-6009-444e-bf61-fc798215ba12)

  The HOME or COMPOSER_HOME environment variable must be set for composer to   
  run correctly                                                                
                                                                               

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

  {"hostname":"debian-4gb-nbg1-1","pid":307959}
[2023-08-07 11:45:48] mautic.ERROR: Installation of plugin through Composer has failed:   {"hostname":"debian-4gb-nbg1-1","pid":307959}
[2023-08-07 11:46:04] mautic.WARNING: PHP Warning - require(/var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/getSwiftmailer_EmailSender_ListenerService.php): Failed to open stream: No such file or directory - in file /var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/appAppKernelProdContainer.php - at line 2364  {"hostname":"debian-4gb-nbg1-1","pid":307959}
[2023-08-07 11:46:04] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Failed opening required '/var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/getSwiftmailer_EmailSender_ListenerService.php' (include_path='.:/usr/share/php')" at /var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/appAppKernelProdContainer.php line 2364 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Failed opening required '/var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/getSwiftmailer_EmailSender_ListenerService.php' (include_path='.:/usr/share/php') at /var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/appAppKernelProdContainer.php:2364)
[stacktrace]
#0 /var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/appAppKernelProdContainer.php(2597): ContainerGXZw3Mj\\appAppKernelProdContainer->load()
#1 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(301): ContainerGXZw3Mj\\appAppKernelProdContainer->ContainerGXZw3Mj\\{closure}()
#2 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\\Component\\EventDispatcher\\EventDispatcher::Symfony\\Component\\EventDispatcher\\{closure}()
#3 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch()
#4 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#5 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(103): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#6 /var/www/html/mautic/vendor/symfony/http-kernel/Kernel.php(166): Symfony\\Component\\HttpKernel\\HttpKernel->terminate()
#7 /var/www/html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(32): Symfony\\Component\\HttpKernel\\Kernel->terminate()
#8 /var/www/html/mautic/vendor/stack/run/src/Stack/run.php(16): Stack\\StackedHttpKernel->terminate()
#9 /var/www/html/mautic/docroot/index.php(24): Stack\
un()
#10 {main}
"} {"hostname":"debian-4gb-nbg1-1","pid":307959}
[2023-08-07 11:46:04] mautic.CRITICAL: Exception thrown when handling an exception (RuntimeException: Failed to start the session because headers have already been sent by "/var/www/html/mautic/vendor/symfony/http-foundation/Response.php" at line 1239. at /var/www/html/mautic/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php line 152) {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"/var/www/html/mautic/vendor/symfony/http-foundation/Response.php\" at line 1239. at /var/www/html/mautic/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:152)
[stacktrace]
#0 /var/www/html/mautic/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(359): Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage->start()
#1 /var/www/html/mautic/vendor/symfony/http-foundation/Session/Session.php(251): Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage->getBag()
#2 /var/www/html/mautic/vendor/symfony/http-foundation/Session/Session.php(273): Symfony\\Component\\HttpFoundation\\Session\\Session->getBag()
#3 /var/www/html/mautic/vendor/symfony/http-foundation/Session/Session.php(73): Symfony\\Component\\HttpFoundation\\Session\\Session->getAttributeBag()
#4 /var/www/html/mautic/docroot/app/bundles/CoreBundle/EventListener/EnvironmentSubscriber.php(47): Symfony\\Component\\HttpFoundation\\Session\\Session->get()
#5 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Mautic\\CoreBundle\\EventListener\\EnvironmentSubscriber->onKernelRequestSetTimezone()
#6 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch()
#7 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#8 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#9 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#10 /var/www/html/mautic/docroot/app/bundles/CoreBundle/EventListener/ExceptionListener.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#11 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Mautic\\CoreBundle\\EventListener\\ExceptionListener->onKernelException()
#12 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch()
#13 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#14 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(229): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#15 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(120): Symfony\\Component\\HttpKernel\\HttpKernel->handleThrowable()
#16 /var/www/html/mautic/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php(129): Symfony\\Component\\HttpKernel\\HttpKernel->terminateWithException()
#17 /var/www/html/mautic/vendor/symfony/error-handler/ErrorHandler.php(601): Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::Symfony\\Component\\HttpKernel\\EventListener\\{closure}()
#18 [internal function]: Symfony\\Component\\ErrorHandler\\ErrorHandler->handleException()
#19 {main}
"} {"hostname":"debian-4gb-nbg1-1","pid":307959}

### How can we reproduce this issue?

Step 1: 

### Relevant log output

```shell
The HOME or COMPOSER_HOME environment variable must be set for composer to   
  run correctly                                                                
                                                                               

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

  {"hostname":"debian-4gb-nbg1-1","pid":307959}
[2023-08-07 11:45:48] mautic.ERROR: Installation of plugin through Composer has failed:   {"hostname":"debian-4gb-nbg1-1","pid":307959}
[2023-08-07 11:46:04] mautic.WARNING: PHP Warning - require(/var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/getSwiftmailer_EmailSender_ListenerService.php): Failed to open stream: No such file or directory - in file /var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/appAppKernelProdContainer.php - at line 2364  {"hostname":"debian-4gb-nbg1-1","pid":307959}
[2023-08-07 11:46:04] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Failed opening required '/var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/getSwiftmailer_EmailSender_ListenerService.php' (include_path='.:/usr/share/php')" at /var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/appAppKernelProdContainer.php line 2364 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Failed opening required '/var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/getSwiftmailer_EmailSender_ListenerService.php' (include_path='.:/usr/share/php') at /var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/appAppKernelProdContainer.php:2364)
[stacktrace]
#0 /var/www/html/mautic/var/cache/pro_/ContainerGXZw3Mj/appAppKernelProdContainer.php(2597): ContainerGXZw3Mj\\appAppKernelProdContainer->load()
#1 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(301): ContainerGXZw3Mj\\appAppKernelProdContainer->ContainerGXZw3Mj\\{closure}()
#2 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Symfony\\Component\\EventDispatcher\\EventDispatcher::Symfony\\Component\\EventDispatcher\\{closure}()
#3 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch()
#4 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#5 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(103): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#6 /var/www/html/mautic/vendor/symfony/http-kernel/Kernel.php(166): Symfony\\Component\\HttpKernel\\HttpKernel->terminate()
#7 /var/www/html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(32): Symfony\\Component\\HttpKernel\\Kernel->terminate()
#8 /var/www/html/mautic/vendor/stack/run/src/Stack/run.php(16): Stack\\StackedHttpKernel->terminate()
#9 /var/www/html/mautic/docroot/index.php(24): Stack\
un()
#10 {main}
"} {"hostname":"debian-4gb-nbg1-1","pid":307959}
[2023-08-07 11:46:04] mautic.CRITICAL: Exception thrown when handling an exception (RuntimeException: Failed to start the session because headers have already been sent by "/var/www/html/mautic/vendor/symfony/http-foundation/Response.php" at line 1239. at /var/www/html/mautic/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php line 152) {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"/var/www/html/mautic/vendor/symfony/http-foundation/Response.php\" at line 1239. at /var/www/html/mautic/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:152)
[stacktrace]
#0 /var/www/html/mautic/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(359): Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage->start()
#1 /var/www/html/mautic/vendor/symfony/http-foundation/Session/Session.php(251): Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage->getBag()
#2 /var/www/html/mautic/vendor/symfony/http-foundation/Session/Session.php(273): Symfony\\Component\\HttpFoundation\\Session\\Session->getBag()
#3 /var/www/html/mautic/vendor/symfony/http-foundation/Session/Session.php(73): Symfony\\Component\\HttpFoundation\\Session\\Session->getAttributeBag()
#4 /var/www/html/mautic/docroot/app/bundles/CoreBundle/EventListener/EnvironmentSubscriber.php(47): Symfony\\Component\\HttpFoundation\\Session\\Session->get()
#5 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Mautic\\CoreBundle\\EventListener\\EnvironmentSubscriber->onKernelRequestSetTimezone()
#6 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch()
#7 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#8 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(145): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#9 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(81): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw()
#10 /var/www/html/mautic/docroot/app/bundles/CoreBundle/EventListener/ExceptionListener.php(67): Symfony\\Component\\HttpKernel\\HttpKernel->handle()
#11 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Mautic\\CoreBundle\\EventListener\\ExceptionListener->onKernelException()
#12 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch()
#13 /var/www/html/mautic/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\\Component\\EventDispatcher\\EventDispatcher->callListeners()
#14 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(229): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch()
#15 /var/www/html/mautic/vendor/symfony/http-kernel/HttpKernel.php(120): Symfony\\Component\\HttpKernel\\HttpKernel->handleThrowable()
#16 /var/www/html/mautic/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php(129): Symfony\\Component\\HttpKernel\\HttpKernel->terminateWithException()
#17 /var/www/html/mautic/vendor/symfony/error-handler/ErrorHandler.php(601): Symfony\\Component\\HttpKernel\\EventListener\\DebugHandlersListener::Symfony\\Component\\HttpKernel\\EventListener\\{closure}()
#18 [internal function]: Symfony\\Component\\ErrorHandler\\ErrorHandler->handleException()
#19 {main}
"} {"hostname":"debian-4gb-nbg1-1","pid":307959}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
The errors look like they are cache-related, did you clear the cache after turning on the marketplace features?

**Comment by RCheesley** [comment]
I see you also posted on the forums so I will close this bug report.
