### ISSUE TITLE
Add/edit a field crash the application if the current contacts do not satisfy the rules

### ISSUE THREAD

**Issue by GermanJablo** [mautic/mautic#12643]
### Mautic Version

5.0.x series

### PHP version

7.4.3

### What browsers are you seeing the problem on?

Chrome

### What happened?

Add/edit a field crash the application if the current contacts do not satisfy the rules

### How can we reproduce this issue?

1. Create a contact.
2. In "Custom fields", add or edit a field that has not been defined in the contact, define it as required.
3. When "saving" the Mautic server crashes. The only way I can use it again is to restart my server.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by Nisha-sahu** [comment]
I would like to work on this issue. Please assign me this project.

**Comment by GermanJablo** [comment]
.

**Comment by RCheesley** [comment]
Hi folks, as far as I know this isn't an issue any more. I made the Position field required and checked a user without that field being present and there were no issues, no server crashing.

![Edit-Lewis-Syed-Mautic-12-09-2024_01_02_PM](https://github.com/user-attachments/assets/1aa51a85-555f-4adf-9222-8b4c92009405)

Please feel free to request a re-open if this continues to be an issue with more detail to enable replication. Thanks!
