### ISSUE TITLE
sugests to improve mautic

### ISSUE THREAD

**Issue by RegisScaggiante** [mautic/mautic#1265]
I don't know if I could express myself as clearly as ... but, based on my experience with the mautic, I would like to make some suggestions to improve our software. 

1- categorization lists 
For me it is important to better organize the lists. Just as there are categories of mail, types of landing pages and categories of forms, I think we could have categories lists. This would facilitate the organization. 

2- allow the lead change your email notification preferences. 
Very important in my opinion. Enabling or disabling certain types of information. Lists of categories could be created and the lead could choose to which category he would like to receive information. 

3- show the number of selected and filtered leads. 
For example, I wonder how many leads have in total in my listings. I can not know that. 

4- present the status of e-mail sent the click-through rate obtained and allow for verification of who clicked. 

5- present report details of emails sent by clicking the email itself. 
Facilitate access to specific filter reports sent emails. Such as: leads that canceled the inscription to receive that email, which leads clicked on email link, leads that opened the email. I'm having trouble to get to see these information clearly. I think it would be good that facilitate visualization by adding links to such filters in own email status page that was sent. 

6- Enable sending test email to a specific email 

7- allow filtering the recent events to see only lead conversions. 
In this way it would be possible to display only hits on pages, emails sent or printed forms. 

Thank you for your dedication and good work, I hope to help in this way.

**Comment by alanhartless** [comment]
Hi!

Would you mind separating these into separate issues? It makes it easier to track, assign, and apply code changes against.

Thanks!
Alan

**Comment by RegisScaggiante** [comment]
Ok!
Can i delete this issue after made a separete issues?
Em 21/12/2015 9:44 PM, "Alan Hartless" <notifications@github.com> escreveu:
