### ISSUE TITLE
Error in creating List (Segment) Email via API

### ISSUE THREAD

**Issue by abdul-Tz-prog** [mautic/mautic#12665]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What happened?

Whenever I try to create an email (with segment or list )with payload :

```
{
    "isPublished": false,
    "name": "test API email",
    "subject": "API test email",
    "fromAddress": "some@email.com",
    "fromName": "Entrepositive",
    "customHtml": "<p>My HTML</p>",
    "emailType": "list",
    "lists": [
                  {
                    "id":41
                  }
            ],
    "template":  "blank"
}
```

through API call in Postman, It gives me the error :

```
{
    "errors": [
        {
            "code": 400,
            "message": "lists: This value is not valid.",
            "details": {
                "lists": [
                    "This value is not valid."
                ]
            }
        }
    ]
}
```

But when I try to create an email (without list or segment) using this payload:

```
{
    "isPublished": false,
    "name": "test API email",
    "subject": "API test email",
    "fromAddress": "some@email.com",
    "fromName": "Entrepositive",
    "customHtml": "<p>My HTML</p>",
    "emailType": null,
    "lists": [],
    "template":  "blank"
}
```

then it creates the email in Mautic successfully.

### How can we reproduce this issue?

Step 1: Use this API call in Postman `https://your-mautic-instance/api/emails/new` with your credentials.
Step 2: Provide this JSON as body :
```
{
    "isPublished": false,
    "name": "test API email",
    "subject": "API test email",
    "fromAddress": "some@email.com",
    "fromName": "Entrepositive",
    "customHtml": "<p>My HTML</p>",
    "emailType": "list",
    "lists": [
                  {
                    "id":41
                  }
            ],
    "template":  "blank"
}
```
Step 3: Send this request and it will give you error :
```
{
    "errors": [
        {
            "code": 400,
            "message": "lists: This value is not valid.",
            "details": {
                "lists": [
                    "This value is not valid."
                ]
            }
        }
    ]
}
```

Step 4: for successful API call use this JSON as body in postman: 

```
{
    "isPublished": false,
    "name": "test API email",
    "subject": "API test email",
    "fromAddress": "some@email.com",
    "fromName": "Entrepositive",
    "customHtml": "<p>My HTML</p>",
    "emailType": null,
    "lists": [],
    "template":  "blank"
}
```

then it will create email.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there! 

Maybe the docs here will help?

https://mautic-developer.readthedocs.io/en/latest/rest_api/emails.html#create-email

**Comment by dsp76** [comment]
Thanks @RCheesley for the heads up. Indeed @abdul-Tz-prog there is an error in the data.

`{
    "isPublished": false,
    "name": "test API email",
    "subject": "API test email",
    "fromAddress": "some@email.com",
    "fromName": "Entrepositive",
    "customHtml": "<p>My HTML</p>",
    "emailType": "list",
    "lists": [41],
    "template": "blank"
}
`

"lists" needs to be an array.
