### ISSUE TITLE
Incomplete IP address anonymization

### ISSUE THREAD

**Issue by ekkeguembel** [mautic/mautic#12671]
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

In the audit_log table, IP addresses get nicely truncated in the "details" field, but in the "ip_address" field they are still persisted in clear.
Expected: value should be truncated in the "ip_address" field, too.

Applies to m4 as well as to m5

Add-on: I think we should include a migration to retroactively fix i.e. truncate all the sensitive past data that is currently in the databases (given that anonymize_ip is activated in the instance's config).
Or maybe we offer at least an SQL command that does just that, something like:

`UPDATE audit_log
SET ip_address = CONCAT(SUBSTRING_INDEX(ip_address, '.', 3), '.***')
WHERE ip_address REGEXP '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$';`

### How can we reproduce this issue?

look at any audit_log table
e.g.
`select * from audit_log`
returns lines like
`2113344	0	System	lead	lead	527207	create	a:2:{s:11:"ipAddresses";a:2:{i:0;s:0:"";i:1;s:14:"89.182.230.***";}s:6:"fields";a:2:{s:4:"demo";a:2:{i:0;N;i:1;s:1:"0";}s:15:"demoform_helper";a:2:{i:0;N;i:1;s:1:"0";}}}	2023-08-24 14:38:18	89.182.230.128`

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
@ekkeguembel when reviewing open PRs I came across https://github.com/mautic/mautic/pull/10116 which seems that it might be extended to address this.

Could you take a look? If so we can ask the OP to update the PR and get it tested.

**Comment by ekkeguembel** [comment]
Trying to figure out #10116 (not too easy due to good old "Failed to start mautic: ComposeCmd failed " Gitpod issues)

**Comment by ekkeguembel** [comment]
@RCheesley #10116 does not really seem to be related (I doubt if it makes sense in the first place).
In other words - I would tend to do this one (#12671) isolated. Will place that with our team, if ok.

**Comment by RCheesley** [comment]
OK feel free to work on this part separate - seems like having both addressed makes sense however it happens! Thanks!

**Comment by dadarya0** [comment]
@RCheesley this is fixed in https://github.com/mautic/mautic/pull/10116/commits/244ee11c8d03ba116953541bf52fe2d8630ac537 as part of https://github.com/mautic/mautic/pull/10116
