### ISSUE TITLE
mixed up fields "value" and "lable" when using multi checkbox

### ISSUE THREAD

**Issue by cremigerhonig** [mautic/mautic#12698]
### Mautic Version

4.4.x series

### PHP version

8

### What browsers are you seeing the problem on?

Firefox

### What happened?

When I create a custom field "select multi" (for example as a GDPR checkbox) the fields are mixed up

The left one is supposed to be the "lable" field
the right one is supposed to be the "value" field

in my example it would be
left lable: "I agree"
right value: "agreed"

now I create a form, using the custom fields to choose from
It shows the lable correctly and I can choose it

once the form send the data is saved and if i check the saved data in the contact: 
it saves / displays the "lable" text and not the "value" text in the contact information.

someone else also wrote about this, nobody cared
https://forum.mautic.org/t/custom-field-label/8841

whats wrong?

### How can we reproduce this issue?

as written already

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Seems to be working for me:

![image](https://github.com/mautic/mautic/assets/4246909/81a21115-9bee-44ae-a80b-f7a9510cb331)

![image](https://github.com/mautic/mautic/assets/4246909/88af113c-de11-4db2-8ac9-a4c987ceb3f2)

**Comment by jos0405** [comment]
![image](https://github.com/mautic/mautic/assets/4246909/e1b480d9-9dbb-4c60-8213-345ca1494daa)

**Comment by jos0405** [comment]
Yeah works

**Comment by cremigerhonig** [comment]
no its not working as you just proofen yourself

small reminder:
The left field is supposed to be the "lable" field
the right field is supposed to be the "value" field

in your example:

left field (lable) = yes
right field (value)= 1
and
left field (lable) = no
right field (value)= 0

the selection works, you can choose from yes and no but if you look at your screenshot 

https://user-images.githubusercontent.com/4246909/270557724-e1b480d9-9dbb-4c60-8213-345ca1494daa.png

what is saved in the contact details in the "multi" section is supposed to be the value of the lable so it should be 
"1,0" instead of "yes,no"

its showing the lable instead of the value
