### ISSUE TITLE
Builder not showcasing the code correctly

### ISSUE THREAD

**Issue by omarvasquezs** [mautic/mautic#12701]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Hi Everyone, I have some issues with the mautic mjml email template builder (grapejs) similar to these topics: https://forum.mautic.org/t/custom-mautic-mjml-email-template-builder-bug/28344 https://forum.mautic.org/t/issues-with-mautic-builder/28868 that have not been answered yet. I hope you can help me to find a workaround or a provisional solution. Here are the bugs I found so far:

### How can we reproduce this issue?

- After cloning my custom template and making changes by removing certain components and adding new ones to the template. Initially, the removed components were not visible in the builder interface. However, after saving and closing, they were still present when a test email was sent. Upon revisiting the builder, the deleted components reappeared. Only after a second deletion attempt were the removed components permanently gone.
- After adding new components to an email, and after saving and closing, these changes were reflected in the test email. However, upon returning to the email builder, some components were unexpectedly absent, and reloading the page didn't help. Strangely, test emails still included these missing components, even though they weren't visible in the builder. Sending a test email and then going back to the builder caused the missing components to reappear.
- Editing header text converted the headers to paragraph/body text, and changing code to H2 tags would revert the text to headers, but the change did not hold after saving and closing, test emails did not reflect the H2 tag change, however, after some time passed, the H2 tags seemed to hold. They do revert to paragraph/body text again if edited (as a provisional solution, I increased the size and font weight of the text that I want to look like a heading).

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Duplicate:
https://github.com/mautic/mautic/issues/9987

If I'm wrong, plz reopen.
