### ISSUE TITLE
improve the status of email sent

### ISSUE THREAD

**Issue by RegisScaggiante** [mautic/mautic#1270]
Present the status of e-mail sent the click-through rate obtained and allow for verification of who clicked.

Present report details of emails sent by clicking the email itself.
Facilitate access to specific filter reports sent emails. Such as: leads that canceled the inscription to receive that email, which leads clicked on email link, leads that opened the email. I'm having trouble to get to see these information clearly. I think it would be good that facilitate visualization by adding links to such filters in own email status page that was sent.

**Comment by andrefilo** [comment]
I'm really interested in these features too. Any tool that facilitates the visualization of emails statistics would be great!

**Comment by healthstatus** [comment]
+1
