### ISSUE TITLE
Enable sending test email to a specific email

### ISSUE THREAD

**Issue by RegisScaggiante** [mautic/mautic#1271]

**Comment by escopecz** [comment]
Closing for missing description.

**Comment by vihuarar** [comment]
I think this issue should be re-open, but consider it like a possible new feature...

It is important to send test to different emails.. for example, if you want to check how the message looks in gmail, hotmail, outlook, etc..

**Comment by escopecz** [comment]
@vihuarar I think there are duplicates of this with a description so I'll leave this one closed.

See https://github.com/mautic/mautic/issues/1447, https://github.com/mautic/mautic/issues/1209
