### ISSUE TITLE
Error 500 in image uploading

### ISSUE THREAD

**Issue by Maksimius** [mautic/mautic#12714]
### Mautic Version

4.4.x series

### PHP version

7.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Get error 500 from https://i.froala.com/upload when try to upload image in redactor.
![image](https://github.com/mautic/mautic/assets/12676332/f4c421d9-8cff-4cd1-980c-828a8b4c595a)
![image](https://github.com/mautic/mautic/assets/12676332/447ff4c7-298f-4110-a67f-dec76325ffa1)

How to remove usage of a third-party service?

Same question at https://forum.mautic.org/t/can-not-upload-images-via-editor-froala-error-500/28793

### How can we reproduce this issue?

Step 1:  open "Create email"
Step 2: Press attach image
Step 3: See on the error.

### Relevant log output

```shell
No errors in log.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by npracht** [comment]
Hi @Maksimiusn this is obvisouly a server configuration issue. It does not allow you to communicate with your serveur due to CORS. You should investigate on this side.

You can reach out with community on forums or slack. We keep Github for real app issues.

Thanks a lot for using Mautic Community !

**Comment by Maksimius** [comment]
If you tried to play it back you would see this
![image](https://github.com/mautic/mautic/assets/12676332/f194d99f-2a08-4c14-bc2d-761d9dc64b5b)

**Comment by npracht** [comment]
And what are the logs ?
