### ISSUE TITLE
Import from an existing template - broken since 4.4.8 release

### ISSUE THREAD

**Issue by TechBill** [mautic/mautic#12715]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I thought I have reported this bug since 4.4.8 and I couldn't find my report so I am reporting in case it somehow had disappeared.

Anytime I upgrade past version 4.4.7 then select a contact to [Send email] 

In the email box - the [Import from an exiting template] only produce a blank page]  

I have to go back to 4.4.7 to get my import template working again.  I upgraded to 4.4.10 today and the bug is still there so I went back to 4.4.7 again. 

We use the import from existing template a lot and we would really like to see this fixed in verion 4.4.8 and higher since we are forced to stay at 4.4.7 until it's fixed. 

Thank you

### How can we reproduce this issue?

Step 1:  Upgrade to 4.4.8 or higher
Step 2: Go to Contact page and choose any contact
Step 3: Click [Send email]
Step 4: In the Email modal window, select a template under [Import from an existing template] drop down menu. 

It will be blank and no template will get imported from the selection in the menu. 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Hi, you need to update your assets.
run bin/console m:a:g
clear cache
should be fixed.
Plz reopen if not fixed.
thx.

**Comment by TechBill** [comment]
is run bin/console m🅰️g a typo?  I don't understand this command.  Please advise

**Comment by jos0405** [comment]
Here is the right way to fix it:
`bin/console m:a:g`
then refresh the cache
then clear your browser cache to reload JS

**Comment by jos0405** [comment]
This works up to m 4.4.10 for sure.
