### ISSUE TITLE
Resolved -  #12715

### ISSUE THREAD

**Issue by TechBill** [mautic/mautic#12744]
### Mautic Version

5.0.x series

### PHP version

8.1

https://github.com/mautic/mautic/issues/12715

<img width="675" alt="Screenshot 2023-09-26 at 8 53 55 AM" src="https://github.com/mautic/mautic/assets/945103/f0bf2159-aef1-4202-bc0b-02203bfd18d1">

I sitll had to keep putting 4.4.7 back to get it all back again ... no matter what type of updating I do via console ..
  

### How can we reproduce this issue?

https://github.com/mautic/mautic/issues/12715

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by TechBill** [comment]
Went back to 4.4.7. .... WORKING  ....  See it's not blank anymore 

<img width="670" alt="Screenshot 2023-09-26 at 9 15 34 AM" src="https://github.com/mautic/mautic/assets/945103/3ba39d27-c4cd-47b4-a0b8-e4628aaad56b">


Stop closing tickets without throughly investating it or ask me question or contact me for more information

**Comment by TechBill** [comment]
and yes I deleted cache hunderds .. no thousands of time ... stop asking me about cache ...

**Comment by jos0405** [comment]
Explanation added how to fix.
https://github.com/mautic/mautic/issues/12715
