### ISSUE TITLE
Mautic Nested Variable Support for custom (API) tokens in subject.

### ISSUE THREAD

**Issue by DerLeole** [mautic/mautic#12758]
### Mautic Version

4.4.x series

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When using a custom token variable in the Subject Line of the Email builder, using the "tokens" array in the REST API, the token is correctly exchanged for its value in the subject for the sent Email.

However when a {subject} variable is used within the body/text of an E-Mail the subject text is included verbatim, as it appears in the web ui, without the nested substitution of the variable token. This is nto the case for inbuilt variables like {contactfield=firstname}.

### How can we reproduce this issue?

![image](https://github.com/mautic/mautic/assets/12782603/6ae6e0c9-38ed-44d2-8cf2-750cbb230a54)

![image](https://github.com/mautic/mautic/assets/12782603/3b54ea81-c889-4036-8676-88ae6fe3c2aa)

![image](https://github.com/mautic/mautic/assets/12782603/5d19cc2d-e66a-45e2-a610-90199ebed08d)

![image](https://github.com/mautic/mautic/assets/12782603/fa1469b1-3884-4a96-a2bd-508ed031cec7)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @DerLeole thanks for reporting the bug and sorry for the huge long delay in triaging. We're a bit behind! 🙈 

Can you clarify if you're using core Mautic here, or a third party plugin, for your tokens? Also which version of Mautic?

**Comment by DerLeole** [comment]
Everything used here is Mautic core, without any plugins. The version of mautic used is Mautic 4 (the latest stable build).

**Comment by RCheesley** [comment]
@DerLeole we've done a lot of work in Mautic 5  - is this bug still happening in 5.1.* do you know?

**Comment by RCheesley** [comment]
Closing due to lack of feedback, feel free to request a re-open.
