### ISSUE TITLE
Tracking does not work - maybe it depends with strato smtp server?

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#12755]
### Mautic Version
4.4.10

### PHP version:
8.0.30

### What browsers are you seeing the problem on?
Firefox / Linux Mint

### What happened?

In my double opt-in campaign, the tracking doesn't work. (as here also described). 
https://forum.mautic.org/t/site-tracking-doesnt-work-in-a-campaign/29500

Here is my compaign
![Mautic Double Opt-In Campaign](https://github.com/mautic/mautic/assets/96744684/2920ebe1-2cf7-4650-916f-9a434e51f3a5)

The confirmation e-mail has a link inside but if click on it and visit the site, Mautic doesn't recognise it. I read in one entry of the forum, that another person had an issue with an e-mail account. So maybe Strato ist the reason. 
I wonder, why the normal smtp datas of Strato does not work. 
https://www.strato.de/faq/mail/so-lauten-die-strato-e-mail-server/

In Mautic port 465 doesn't work. Only the 587 with TLS encryption. Normally i use in my e-mail accounts the 465. 

### How can we reproduce this issue?

To find out the reason:
Here is my site - Mautic tracking code is inside.
https://www.stefan-franz.de/newsletter-bestaetigt/

Here are my crown jobs

* * * * * php /var/www/html/mautic/bin/console mautic:campaigns:trigger
*/5 * * * * php /var/www/html/mautic/bin/console mautic:campaigns:rebuild
*/15 * * * * php /var/www/html/mautic/bin/console mautic:segments:update    
* * * * * php /var/www/html/mautic/bin/console mautic:broadcasts:send
* * * * * php /var/www/html/mautic/bin/console mautic:emails:send
0 3 * * * php /var/www/html/mautic/bin/console mautic:unusedip:delete
0 4 * * * php /var/www/html/mautic/bin/console mautic:maintenance:cleanup --days-old=90 --no-interaction

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by stefan-franz** [comment]
Because of Mail Port 465: I found out that per default on hetzner.com the cloud servers have blocked at the first time the port 465 
https://docs.hetzner.com/cloud/servers/faq/

and i have to unlock it after a few weeks. 
So gmail is not working to test if the tracking error depends on strato 

btw: Here is my newsletter joining site - so everyone can test joing and confirm: 
https://www.stefan-franz.de/kontakt/newsletter-anmeldung/

**Comment by stefan-franz** [comment]
Additional Info: For testing i used 3 contacts more times - put in the newsletter form in the website and deleted in mautic after not working. Put it again in the form....

**Comment by RCheesley** [comment]
Hi there, it sounds like this is more of a bug with your setup - which we would support through the forums - rather than being a bug with Mautic which we deal with on Github.

Please can you post the above on https://forum.mautic.org where the community will be able to support you in figuring out why your tracking is not working. Thanks!
