### ISSUE TITLE
Unsubscribe Link in the e-Mail doesn’t work

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#12759]
### Mautic Version

4.4.x series

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Firefox

### What happened?

I sent with the Brienz template a Mail to a segment of 2 contacts (myself 2 different e-mail adresses an names. 
If i click on the unsubscribe link
https://ma.stefan-franz.de/email/unsubscribe/651afc15cc1ce633771996
in the received mail this error comes (site is not available)

Oops! An Error Occurred
The server returned a “500 Internal Server Error”.

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

### How can we reproduce this issue?

What do i have to do? 

I expected, that in this case Mautic generates a page - or am i wrong?

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please could you post this at https://forum.mautic.org  as that's where we help people with troubleshooting.  Thanks!
