### ISSUE TITLE
Filter Date last active in report transformed as date

### ISSUE THREAD

**Issue by cpot** [mautic/mautic#12756]
### Mautic Version

4.4.x series

### PHP version

PHP 8

### What happened?

When i create a filter in a report based on "Last active" and with a relative date '-1 year', if i save and reopen the report filter it has transformed it as the date one year ago.

It should stay relative and display '-1 year' (it is working like that in Segments)

### How can we reproduce this issue?

Step 1: Create a report
Step 2: Add a filter "Date Last Active" "Greater than or equal" "-1 year"
Step 3: Save the report
Step 4: Re-edit the report, relative filter date has been lost

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
While I totally agree with you, for reports it is more a feature request. It never worked like this. Its an improvement.
https://forum.mautic.org/c/ideas/14 is a start point - but for a realization it needs more. I recommend collecting other users, clients that are interested for this to happen - and then collecting some bounty and finding a dev to realize it.
