### ISSUE TITLE
Mailchimp integration

### ISSUE THREAD

**Issue by mvandenbrande** [mautic/mautic#1276]
My subscribers are not pushed to integration, i.e. Mailchimp list.
I am not a developer, so can somebody help me?
Thank you

**Comment by escopecz** [comment]
Take a look at the docs:

**Comment by mvandenbrande** [comment]
Hello, 
How can I make my own e-mail template? I found a tutorial on Youtube: https://www.youtube.com/watch?v=rPz53Z2HDbU, but I don’t know where to find the config etc.
Thanks in advance
Monika

**Comment by escopecz** [comment]
Hi, take a look at

https://developer.mautic.org/#themes
https://www.mautic.org/docs/themes/customize_themes.html
https://www.mautic.org/blog/marketing-automation-theme-development/

The 3 build-in themes are in the /themes directory so you may take a look at them:
https://github.com/mautic/mautic/tree/staging/themes

For the future, ask this kind of questions in the community forum:
https://www.mautic.org/community

The GitHub issues are more for the bug reports or feature reuqests

**Comment by mvandenbrande** [comment]
Hi John,

I will in the future, but I cannot seem to find, where I can change the existing templates. In Github I see the files, but where can I get access to these files for my website?
Every information I found so far, begins with going to the config file, but nowhere I can find how I can access the file.

Thank you
Monika

**Comment by escopecz** [comment]
Hi Monika,

it depends on what you mean by 

> where can I get access to these files for my website?

Do you mean Mautic? The landing pages and emails have the theme setting.

**Comment by mvandenbrande** [comment]
I mean that I want to change the CSS of the existing ‘Nature’ Theme, but where do I find the file? 
Monika

**Comment by escopecz** [comment]
Ah, you should mention that in the beginning.

https://github.com/mautic/mautic/blob/staging/themes/nature/css/nature.css

And in YOUR Mautic, go to Mautic root folder, then */themes/nature/css/nature.css*

**Comment by mvandenbrande** [comment]
that’s just the problem, where do I find my Mautic root folder?
Thank you for your patience.
Monika

**Comment by escopecz** [comment]
Heh, you've installed Mautic somewhere, right? So that is the root folder.

**Comment by mvandenbrande** [comment]
Pffff, I only find some php files, but nothing that refers to config files etc. I’m probably a fool, but I find it hard to find the most basic information on mautic, github, ...
