### ISSUE TITLE
Segment don't show contacts if user has only rights to view the own contacts

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#12763]
### Mautic Version

4.4.x series

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Firefox

### What happened?

I made a more user system.
If i have only the rights for my own contacts, the segment doesn't show the contacts inside the segment below the graphical - only a rotating circle (database, as on the screenshot displayed). 
And if i want to see it, i need a role with contact full contact access. Don’t knot if a bug or if i hat overlooked something

Over 20 contacts are at the moment in this segment (i’m at the very beginning…)

Btw:
About the user rights (in the roles): Every
![Segments - no contacts if not full access to contacts](https://github.com/mautic/mautic/assets/96744684/45cf13ff-9e5b-4b6a-8e1b-461f59ea6718)
 user can see all segments of all user. Can set anywhere that every user can only see the own segments?

### How can we reproduce this issue?

Every user with only access to his own contact hast this problem. 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by Darko-F** [comment]
I have similar bug 
Mautic 4.4.10
PHP 8.0

I have full administrator access and the same problem if I enter segment don't see contact  and also all segments dont shown info number of contacts.

![image](https://github.com/mautic/mautic/assets/76601479/c55f6a8b-1c43-479c-aa02-f394e1337af5)


Edited:

I change to PHP 7.4 I can see now info of contact but cant see contact when I enter to segment.
![image](https://github.com/mautic/mautic/assets/76601479/12c5e1da-c99a-4f17-8064-ca96b8e09c8f)

**Comment by dsp76** [comment]
I close this in favor of the new and more detailed bug description: 
https://github.com/mautic/mautic/issues/13648
@Darko-F if your issue is still there and you were able to recreate it with up-to-date versions, please discuss it in the forum first - and if confirmed open a new ticket for your issue. It looks different to this one.
