### ISSUE TITLE
Campaign action: Send email to user (Broken layout)

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#12761]
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

When following the steps below, the layout appears to be broken for the "Send email to user" action within the campaign builder. I believe that is just CSS.

### How can we reproduce this issue?

Step 1: Create a new campaign or use an existing one.
Step 2: Navigate to "Launch campaign builder".
Step 3: Create the action named "Send email to user."

![image](https://github.com/mautic/mautic/assets/131262825/534eb9a6-afb5-457c-96c5-87c5e417c04a)

### Relevant log output

```shell
None
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by jos0405** [comment]
Yep, it's also present in M5.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/13175

Please test soon. I'd like to release M5 today.
