### ISSUE TITLE
Form submission copy to bcc doesn't work

### ISSUE THREAD

**Issue by Sweely** [mautic/mautic#12786]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Looks like this issue "bcc will not receive form results" (see stale: https://github.com/mautic/mautic/issues/5967 or this https://github.com/mautic/mautic/issues/10328 or this https://github.com/mautic/mautic/issues/10720) is still happening. In my case with Elastic Email API connection. I am on latest stable Mautic version.

### How can we reproduce this issue?

Step 1: Create new form
Step 2: Add new action: Send form results
Step 3: Add one email in To field and 3 emails (comma separated) in BCC
Step 4: When form is submitted - successfully! - only one email is sent to the one in To field, not BCC addresses.

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there,  as the whole email transport system is going to be changed from Mautic 5,  would you be able to check if this is still an issue on the 5.0 alpha release?

https://gitpod.io/#https://github.com/mautic/mautic  you can do this using gitpod  on this link.  note that for Mautic five there is a slightly different cron job for processing the send: https://mautic-documentation.readthedocs.io/en/5.x/configuration/cron_jobs.html#process-email-queue-cron-job -  shout if you get any problems or need any help!

**Comment by Sweely** [comment]
@RCheesley I just fixed this. The reason emails was not working was because I had not set up cron jobs properly during installation. I'm so sorry for wasting everybody's time 😄

**Comment by RCheesley** [comment]
No problem at all and thank you for getting back to us!
