### ISSUE TITLE
Email Stats > Device Graphic not showing up

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#12789]
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

In the email details section, specifically within the Email Stats, there are two graphics: on the left, one displaying email statistics regarding user actions, and on the right, a representation of the devices used by the user to open the email. However, in Mautic 5, the graphic on the right is failing to display the data.

When generating a report, it becomes evident that Mautic is indeed collecting information about the devices; nevertheless, the graphic associated with it is not functioning as expected.

Graphs with data
Mautic 4:
![image](https://github.com/mautic/mautic/assets/131262825/b9cc9ad7-2705-4de9-bb39-813f03c38e3a)
Mautic 5:
![image](https://github.com/mautic/mautic/assets/131262825/7863836d-de6e-4387-8de8-b9194868225b)

----
Graphs with no data
Mautic 4:
![image](https://github.com/mautic/mautic/assets/131262825/8b9b1b43-3547-4a18-ad5b-4642639b2162)
Mautic 5:
![image](https://github.com/mautic/mautic/assets/131262825/aabb86a5-d391-4a43-8265-a70361628b4c)

### How can we reproduce this issue?

**Optional:**
_Step 1: Create Contacts.
Step 2: Add all the newly created contacts to a segment.
Step 3: Craft an Email.
Step 4: Set up a campaign to send the email to the newly created segment and trigger it.
Step 5: Navigate to the email list, select the email used in the campaign, and review the "Email Stats" section. The device graph is not showing data_

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
I was able to see the stats, when I set the time period correctly in Mautic 5.0.4. Only as long as there was no action or when nothing happened in the selected timeframe, the widget remained empty.

<img width="726" alt="image" src="https://github.com/mautic/mautic/assets/1241376/30d66322-59b5-4dd9-a472-6c39534bd16f">

Could you please double check @code5rick and maybe also increase the timeframe of your widget?
