### ISSUE TITLE
A/B test result graphs: percentage figures in statistics seem misleading

### ISSUE THREAD

**Issue by PatrickJenkner** [mautic/mautic#12798]
### Mautic Version

5.0.x series

### PHP version

8.0.20

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When you send an email with an A/B test, both columns of the chart show the same percentage: The number of clicks divided by the number of reads. This makes sense for the clickthrough-column, but it seems unfitting for the column representing the read emails.

<img width="903" alt="Screenshot 1" src="https://github.com/mautic/mautic/assets/139468697/fd0e01d6-8adf-4789-b2d5-f4b097011b42">

<img width="963" alt="Screenshot 2" src="https://github.com/mautic/mautic/assets/139468697/b12e56c2-9e17-439b-aa3d-ad625457ca75">

It would make sense to omit the percentage for the read-column or possibly show the percentage of read emails from all that were sent, but showing the percentage of clicks might be confusing.

### How can we reproduce this issue?

Step 1: Create an email with a link and A/B testing and send it
Step 2: Genrate some clicks
Step 3: Check "A/B Test Stats" and hover over the columns

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
@PatrickJenkner is this issue still one to keep open?

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please feel free to request a re-open if needed.
