### ISSUE TITLE
You do not have access to the requested area/action.

### ISSUE THREAD

**Issue by zyzioziom** [mautic/mautic#1280]
When trying to modify forms (add action or field) i receive JavaScript message: You do not have access to the requested area/action. The same happens in Campaign builder, didn't check a lot but Lists work well.

Nginx shows no errors
Browser console shows no errors

I have admin rights (first and only user)

Any ideas?

Using 1.2.3, downloaded today

**Comment by ShagunParikh** [comment]
I am facing the same issue. When I am trying to add a new field while creating a new campaign form. How did you solve?
FYI, I have an admin full access

**Comment by nchafai** [comment]
Same issue here when using the builder for a new campaign form. 

@dbhurley The issue has been closed without any information.

**Comment by deranjer** [comment]
Shoot, was hoping for more information on this.

**Comment by RCheesley** [comment]
@deranjer this was closed as it is generally a configuration error which should be posted on the forums rather than on Github. It usually relates to the session having timed out. Please post at https://forum.mautic.org/c/support if you are experiencing this problem.
