### ISSUE TITLE
SparkPost Dedicated IP problem

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#12800]
### Mautic Version

4.4.x series

### PHP version

8.0.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I am using my Mautic system to send via the SparkPost API.
For some reason, it IS sending but it is not sending through the Dedicated IP that I have configured there.
Could you please help and/or advise?

Your help would be greatly appreciated.

Thanks in advance.

### How can we reproduce this issue?

Step 1: 
Configure Mautic to use the SparkPost API

Step 2:
Send an email through Mautic

Step 3:
Check received email headers and see if it has been sent via the dedicated IP configured on SparkPost

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
