### ISSUE TITLE
 Mautic Focus and Emoji Display Issue

### ISSUE THREAD

**Issue by mhdhamouday** [mautic/mautic#12801]
### Mautic Version

4.4.10

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

I have encountered a bug in Mautic Focus that prevents emoji characters from displaying correctly when used within Mautic Focus. Instead of displaying the emojis as intended, they appear as encoded characters or placeholders.

### How can we reproduce this issue?

1- Create a Mautic Focus.
2- Include emoji characters in the focus content.
3- implement the campaign on a external website.
4- Observe how the emoji characters are displayed.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the bug @mhdhamouday - are you able to check if it persists in Mautic 5? You can check it using this link: https://gitpod.io/#https://github.com/mautic/mautic.

Thanks!

**Comment by mhdhamouday** [comment]
@RCheesley Thank you! Emojis are displaying correctly after the update to Mautic 5.
