### ISSUE TITLE
Campaign action: Jump to event (Incorrect options)

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#12805]
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

After creating a "Jump to Event" action, if we wish to edit it, the system displays the campaign list instead of the jump event configurations.

Mautic 4 (Correct):
![image](https://github.com/mautic/mautic/assets/131262825/a42423ff-7f72-4a38-a9e3-1470277623b2)

Mautic 5 (Wrong):
![image](https://github.com/mautic/mautic/assets/131262825/225c8dca-2994-4a24-9375-36ead4a22dd8)

### How can we reproduce this issue?

Step 1: Navigate to the "Campaign" section.
Step 2: Begin by creating a new campaign.
Step 3: Click on the "Launch Campaign Builder" option.
Step 4: Add a contact source to your campaign.
Step 5: Create a Decision: "Submits form."
Step 6: Set up an Action: "Send email" (or any other desired action).
Step 7: Create another Action: "Jump to event." Fill in the required information and create it.
Step 8: Attempt to edit the "Jump to event" action. You will notice that the modal displays incorrect information.

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by code5rick** [comment]
**Update**
Another issue I discovered related to this situation is that when we create a campaign using a jump event and save it, everything works as expected. However, when we later edit the campaign and try to modify the "Jump to Event" action, we encounter a problem where we cannot close the modal as it remains uncloseable. As a workaround, we need to refresh the page, but this action results in the campaign disappearing.

**Comment by mollux** [comment]
@code5rick 

this one sounds really similar to #12639, which was fixed via #12762 since 5.0.0-beta1
Is this the same issue?

**Comment by code5rick** [comment]
@mollux yep, it was the same issue. On M5b2 works just fine!

**Comment by mollux** [comment]
thanks! closing this issue
