### ISSUE TITLE
Theme Settings: Default Theme (not working)

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#12807]
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

On Mautic 5 Beta 1, when we navigate to the theme settings and set a specific theme as our default theme, the change is saved successfully. However, the default theme does not take effect as expected.

### How can we reproduce this issue?

Step 1: Navigate to Settings > Theme Settings.
Step 2: Choose a new default theme, such as the "Confirm Me" theme, as it utilizes GrapeJS/MJML.
Step 3: Save the changes.
Step 4: Proceed to Channels > Email.
Step 5: Create a new email, and verify that the default theme selection remains the Mautic default,the "Blank" theme.

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the bug, I have labeled it up and hopefully we will be able to look at this before the Release Candidate!

**Comment by mollux** [comment]
@code5rick 

I think you're mixing 2 concepts:

* the `default theme`setting you're referring to has an impact on landing pages, see the description
![Screenshot 2023-10-31 at 08 41 40](https://github.com/mautic/mautic/assets/3983285/df59d48b-d90a-4de9-9b67-b7588d766efc)
* the default theme for e-mails is a setting that can be configured via config, see the PR adding this functionality. https://github.com/mautic/mautic/pull/9189

so this is not a bug, it's a feature request to expose it via the UI.

**Comment by code5rick** [comment]
@mollux, thank you for the explanation. Although I initially thought it was related to email, after testing, I realized it doesn't actually work for landing pages. Even after installing my landing page templates and setting them as default, it still didn't function as expected.

**Comment by putzwasser** [comment]
This is because Mautic won't update existing landing pages if you change this setting. Changing this affects your newly created landing pages.

Changing an existing landing page's theme currently means that Mautic replaces all the content of that specific landing page with the template content specified in your selected theme.

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please feel free to request a re-open if needed.
