### ISSUE TITLE
Intermittent left menu mislabeling after Report Save

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#12820]
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

In Mautic version M5b2, when creating a new report and saving it, the left menu sometimes incorrectly displays "Components > Assets" instead of the expected "Report" page, causing potential confusion for users. This issue occurs sporadically and is not consistently reproducible, requiring multiple attempts to observe the problem.

![image](https://github.com/mautic/mautic/assets/131262825/98d614dd-967e-4d77-9b3d-aabe58bce247)

### How can we reproduce this issue?

**Information:** This specific method of creating the report sometimes resulted in the described bug, but not always.

Step 1: Navigate to the Reports section.
Step 2: Create a new report.
Step 3: Provide a name ("System Report T14b").
Step 4: Select the "Contacts: Multi Touch Attributions" as the data source.
Step 5: Under the "Data" tab, choose the following columns:

- Address Line 1
- Address Line 2
- Attribution

Step 6: Enable the System Report.
Step 7: Save your changes.

----
I see a lot of log reports, but I'm unsure whether they are related to the fact that the report shows no results or if something is actually happening. If necessary, I can provide my error log.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
I filed a fix for this bug. Please test it so it can be merged soon:

https://github.com/mautic/mautic/pull/13174
