### ISSUE TITLE
Mails are getting unpulished

### ISSUE THREAD

**Issue by AmberBetnation** [mautic/mautic#12821]
### Mautic Version

5.0.x series

### PHP version

7.4.32

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I am seeing a pattern of mails getting unpublished in the last 2 weeks. I have made my emails, published them and put them in unpublished campaigns zo I can send them later. However, the mails are getting unpublished before I can send them.

### How can we reproduce this issue?

Check why or how the mails are getting unpublished so we can find a solution.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as this sounds like it is more of a Mautic configuration issue. Thanks!
