### ISSUE TITLE
mautic tracking loads too many times in astro v3

### ISSUE THREAD

**Issue by Parthvsquare** [mautic/mautic#12846]
### Mautic Version

5.0.x series

### PHP version

latest

### What browsers are you seeing the problem on?

Chrome

### What happened?

I am trying to add mautic tracking into astro project. After upgrading to astro v3, old `mt` of mautic tracking also fires. 
In astro v3 to load script in every page transition, we need to add event [listeners] (https://docs.astro.build/en/guides/view-transitions/#astropage-load). Mautic tracking `mt` function from old page is also kept and ran along side the new mt.js. 

### How can we reproduce this issue?

Step 1: Add mautic tracking to script tag, like following. 

```astro
<script >
document.addEventListener("astro:page-load", ()=> {
(function (w, d, t, u, n, a, m) {
					w["MauticTrackingObject"] = n;
					(w[n] =
						w[n] ||
						function () {
							(w[n].q = w[n].q || []).push(arguments);
						}),
				//@ts-expect-error
						(a = d.createElement(t)),
				//@ts-expect-error
						(m = d.getElementsByTagName(t)[0]);
				//@ts-expect-error
					a.async = 1;
				//@ts-expect-error
					a.src = u;
				//@ts-expect-error
					m.parentNode.insertBefore(a, m);
				})(window, document, "script", "https://company.com/mtc.js", "mt");

				console.log("here");
				//@ts-expect-error
					mt("send", "pageview",{}, {
						onload: function () {
							console.log("loaded");
						},
					},
					{
						onerror: function () {
							console.log("error");
						},
					}
					);}
					</script>
```
After loading, event is fired once then navigating to another page, it fires 3 times. then 4 time etc.
<img width="1006" alt="image" src="https://github.com/mautic/mautic/assets/26404957/c0d2ed51-51fc-4c76-9417-2f9fe77720ab">
This is not seen in GTM. 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by Parthvsquare** [comment]
the log of onload, after navigating to 3rd page
<img width="1024" alt="image" src="https://github.com/mautic/mautic/assets/26404957/f257b7ad-79bc-45ef-a7a4-4d9f9972717c">

**Comment by escopecz** [comment]
Why is this an issue of Mautic and not Astro? It seems that something is triggering the `"astro:page-load"` event multiple times, right? It's not something Mautic can solve.
