### ISSUE TITLE
SQL statement exception for the mautic:campaign:trigger command

### ISSUE THREAD

**Issue by different-thinking** [mautic/mautic#1285]
Hi,

I'm getting the following error when running cron für campaign update:

 [Doctrine\DBAL\DBALException],  An exception occurred while executing 'SELECT max(list_leads.lead_id) as max_id, count(distinct(list_leads.lead_id)) as lead_count FROM lead_lists_leads list_leads WHERE (list_leads.manually_removed = ?) AND (list_leads.leadlist_id IN ()) AND (li
 st_leads.date_added <= '2015-12-26 06:45:02') AND (NOT EXISTS (SELECT null FROM campaign_leads campaign_leads WHERE (campaign_leads.lead_id = list_leads.lead_id) AND (campaign_leads.manually_removed = ?) AND (campaign_leads.campaign_id = 6)))' with params [0, 0]:,  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) AND (list_leads.date_added <= '2015-12-26 06:45:02') AND (NOT EXISTS (SELECT ' at line 1,,,,,,,  [PDOException],  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) AND (list_leads.date_added <= '2015-12-26 06:45:02') AND (NOT EXISTS (SELECT ' at line 1,,,,mautic:campaigns:update [-l|--batch-limit[="..."]] [-m|--max-leads[="..."]] [-i|--campaign-id[="..."]] [-f|--force],,

What to do?

Robert

**Comment by alanhartless** [comment]
Hi Robert,

Try https://github.com/mautic/mautic/pull/1286.

**Comment by different-thinking** [comment]
Hi Alan,

it looks like it is working! I'm getting no error messages for 1.5 hours now!

Thanks!

Robert

**Comment by TiagoGouvea** [comment]
I'm using v1.2.3 and got on cronjob:

Rebuilding leads for campaign 1

  [Doctrine\DBAL\DBALException]
  An exception occurred while executing 'SELECT max(list_leads.lead_id) as max_id, count(distinct(list_leads.lead_id)) as lead_count FROM mauhy_lead_lists_leads list_leads WHERE (list_leads.manually_removed = ?) AND (list_leads.leadlist_id IN ()) AND (list_leads.date_added <= '2016-01-13 10:00:02') AND (NOT EXISTS (SELECT null FROM mauhy_campaign_leads campaign_leads WHERE (campaign_leads.lead_id = list_leads.lead_id) AND (campaign_leads.manually_removed = ?) AND (campaign_leads.campaign_id = 1)))' with params [0, 0]:
  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) AND (list_leads.date_added <= '2016-01-13 10:00:02') AND (NOT EXISTS (SELECT ' at line 1

  [Doctrine\DBAL\Driver\Mysqli\MysqliException]
  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) AND (list_leads.date_added <= '2016-01-13 10:00:02') AND (NOT EXISTS (SELECT ' at line 1

mautic:campaigns:update [-l|--batch-limit[="..."]] [-m|--max-leads[="..."]] [-i|--campaign-id[="..."]] [-f|--force]

**Comment by spatialy** [comment]
Hi all, just having the same problem over and over again.

SOLUTION: run your cronjob or direct CLI command with PHP 5.X, in my case I change my cron jobs from php.... to php5.6.......

Best
