### ISSUE TITLE
Companies: Duplicated search bar and title after searching

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#12859]
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

When performing a search in the "Companies" search bar, there are instances where it duplicates both the search bar and the title. This behavior is not consistent, but it can be easily replicated.

![image](https://github.com/mautic/mautic/assets/131262825/29e56a54-331f-4d71-8443-610c1adc38f0)

### How can we reproduce this issue?

**Note:** To reproduce this issue, you should have multiple companies created.

Step 1: Navigate to "Companies".
Step 2: In the search bar, type, for example, "client" and press Enter.
Step 3: Subsequently, you will notice that both the title and the search bar are duplicated.

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
This seems to be fixed already. Cannot replicate
<img width="363" alt="Screenshot 2024-01-09 at 10 08 41" src="https://github.com/mautic/mautic/assets/1235442/a827d845-441f-4e93-8b0e-547b0828355f">
