### ISSUE TITLE
Companies: Pagination not working

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#12858]
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

In 'Companies,' if we try to go to another page, it doesn't proceed and gives me various errors in the console and in the system error log.
![image](https://github.com/mautic/mautic/assets/131262825/941544fd-dca6-4198-83cc-643ff2bfc7b8)

### How can we reproduce this issue?

**Note:** To reproduce this issue, you should have multiple companies created.

Step 1: Navigate to 'Companies'.
Step 2: Scroll to the bottom and attempt to select a different page.
Step 3: However, when you do this, nothing happens.

----

Chrome Console:
![image](https://github.com/mautic/mautic/assets/131262825/e2bdb01e-4030-4b2c-9c2e-8b4c9ae5fa7c)

### Relevant log output

```shell
[2023-11-02T17:46:08.575040+00:00] mautic.WARNING: PHP Warning - Undefined array key "" - in file /var/www/html/app/bundles/ApiBundle/Helper/BatchIdToEntityHelper.php - at line 160 [] {"hostname":"Mautic5-AA","pid":5888}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by kuzmany** [comment]
It works for me.
I see CORS issue in your console. Double-check If your site_url is the same as your request on the page (with www or without, with https or without)

**Comment by escopecz** [comment]
I also cannot reproduce. How did you install Mautic5-beta2? Perhaps running `bin/console mautic:assets:generate` could also help.

**Comment by code5rick** [comment]
@kuzmany you were right. Indeed we made a mistake: the site_url was an older one. It does work, our bad. Thanks for the help @lenonleite !
