### ISSUE TITLE
Contact associated with Åland Islands: Error 500

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#12863]
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

When creating a new contact and assigning the country "Åland Islands" to it, an error 500 occurs after saving. If we attempt to navigate to the contacts page, access is denied.

### How can we reproduce this issue?

Step 1: Navigate to the "Contacts" page.
Step 2: Create a new contact.
Step 3: Enter the name and email, and select "Åland Islands" from the "Country" dropdown.
![Captura de ecrã 2023-11-03 104316](https://github.com/mautic/mautic/assets/131262825/dc41a586-8f50-4299-a68b-8d9aaf4b9a0b)
Step 4: Afterward, click "Save & Close". and an error 500 will be displayed.
(Optional) Step 5: When attempting to access the "Contacts" page, it denies us entry, and we remain on the same page.

----

![image](https://github.com/mautic/mautic/assets/131262825/3fb909da-d66b-4ae4-b869-e3eea484032e)

I suspect that the problem may be related due to be missing the flag of that specific country/province?

### Relevant log output

```shell
[2023-11-03T10:52:53.287132+00:00] mautic.CRITICAL: Uncaught PHP Exception TypeError: "Mautic\CoreBundle\Twig\Extension\AssetExtension::getCountryFlag(): Return value must be of type string, bool returned" at /var/www/html/app/bundles/CoreBundle/Twig/Extension/AssetExtension.php line 162 {"exception":"[object] (TypeError(code: 0): Mautic\\CoreBundle\\Twig\\Extension\\AssetExtension::getCountryFlag(): Return value must be of type string, bool returned at /var/www/html/app/bundles/CoreBundle/Twig/Extension/AssetExtension.php:162)"} {"hostname":"8d0f74ea457d","pid":150487}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mollux** [comment]
@code5rick 

thanks for reporting this! There are multiple countries that give an error, as there is no flag image available.

I created a small script to find those files, based on the logic in [AssetHelper::getCountryFlag](https://github.com/mautic/mautic/blob/7462a5f045d1a7ba3ec5924fbbeef1e6fe69ec12/app/bundles/CoreBundle/Twig/Helper/AssetsHelper.php#L703):
```php
<?php

$contents = file_get_contents('app/bundles/CoreBundle/Assets/json/countries.json');
$countries = json_decode($contents);

foreach ($countries as $country) {
    $country_clean  =  ucwords(str_replace(' ', '-', $country));
    $file = 'app/assets/images/flags/'.$country_clean.'.png';
    if (!file_exists($file)) {
        echo "$country has no flag image ($file doesn't exist)". PHP_EOL;
    }
}
```

this results in following missing files:
```
Åland Islands has no flag image (app/assets/images/flags/Åland-Islands.png doesn't exist)
Bonaire, Saint Eustatius and Saba has no flag image (app/assets/images/flags/Bonaire,-Saint-Eustatius-and-Saba.png doesn't exist)
Bouvet Island has no flag image (app/assets/images/flags/Bouvet-Island.png doesn't exist)
Curaçao has no flag image (app/assets/images/flags/Curaçao.png doesn't exist)
French Guiana has no flag image (app/assets/images/flags/French-Guiana.png doesn't exist)
Guadeloupe has no flag image (app/assets/images/flags/Guadeloupe.png doesn't exist)
Heard Island and McDonald Islands has no flag image (app/assets/images/flags/Heard-Island-and-McDonald-Islands.png doesn't exist)
Holy See has no flag image (app/assets/images/flags/Holy-See.png doesn't exist)
Ivory Coast has no flag image (app/assets/images/flags/Ivory-Coast.png doesn't exist)
Macao has no flag image (app/assets/images/flags/Macao.png doesn't exist)
Pitcairn has no flag image (app/assets/images/flags/Pitcairn.png doesn't exist)
Réunion has no flag image (app/assets/images/flags/Réunion.png doesn't exist)
Saint Helena, Ascension and Tristan da Cunha has no flag image (app/assets/images/flags/Saint-Helena,-Ascension-and-Tristan-da-Cunha.png doesn't exist)
Saint Pierre and Miquelon has no flag image (app/assets/images/flags/Saint-Pierre-and-Miquelon.png doesn't exist)
Svalbard and Jan Mayen has no flag image (app/assets/images/flags/Svalbard-and-Jan-Mayen.png doesn't exist)
Tahiti has no flag image (app/assets/images/flags/Tahiti.png doesn't exist)
Virgin Islands (British) has no flag image (app/assets/images/flags/Virgin-Islands-(British).png doesn't exist)
Virgin Islands (U.S.) has no flag image (app/assets/images/flags/Virgin-Islands-(U.S.).png doesn't exist)
Wallis and Futuna has no flag image (app/assets/images/flags/Wallis-and-Futuna.png doesn't exist)
Yugoslavia has no flag image (app/assets/images/flags/Yugoslavia.png doesn't exist)
```

As there are multiple flaws in the whole country flags logic (using the label instead of e.g. ISO codes, obsolete flags, not up-to-date list of countries, ...), I will create a PR to mitigate this issue.

A follow-up issue should be created to properly solve and harden country management in Mautic
