### ISSUE TITLE
Unable to send e-mails, Uncaught PHP Exception TypeError: "str_ireplace()

### ISSUE THREAD

**Issue by Tie-fighter** [mautic/mautic#12871]
### Mautic Version

5.0.x series

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

500 Internal Server Error when trying to send e-mails

### How can we reproduce this issue?

Step 1: Try to send e-mail via Channels - EMails - Send Example
Step 2: Campaign e-mails are affected as well

### Relevant log output

```shell
=> /var/www/mautic/var/logs/mautic_prod-2023-11-03.php <==
[2023-11-03 20:16:49] mautic.CRITICAL: Uncaught PHP Exception TypeError: "str_ireplace(): Argument #3 ($subject) must be of type array|string, Symfony\Component\Mime\Address given" at /var/www/mautic/app/bundles/EmailBundle/Helper/MailHelper.php line 699 {"exception":"[object] (TypeError(code: 0): str_ireplace(): Argument #3 ($subject) must be of type array|string, Symfony\\Component\\Mime\\Address given at /var/www/mautic/app/bundles/EmailBundle/Helper/MailHelper.php:699)"} {"hostname":"xxx","pid":6739}
```

`[2023-11-04 13:19:02] console.CRITICAL: Error thrown while running command "mautic:campaigns:trigger". Message: "str_ireplace(): Argument #3 ($subject) must be of type array|string, Symfony\Component\Mime\Address given" {"exception":"[object] (TypeError(code: 0): str_ireplace(): Argument #3 ($subject) must be of type array|string, Symfony\\Component\\Mime\\Address given at /var/www/mautic/app/bundles/EmailBundle/Helper/MailHelper.php:699)","command":"mautic:campaigns:trigger","message":"str_ireplace(): Argument #3 ($subject) must be of type array|string, Symfony\\Component\\Mime\\Address given"} {"hostname":"xxx","pid":2444}`

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by patrykgruszka** [comment]
What are your email DSN settings? I have the same problem but haven't found the cause yet.

**Comment by Tie-fighter** [comment]
I am using a hetzner smtp server. Everything is pretty standard.

PS: Sending test emails in the Email DSN settings works fine btw, the problem is everywhere else in mautic.

**Comment by patrykgruszka** [comment]
Ok, I've managed to replicate this. Setting the **Custom return path (bounce) address** in **Mail Send Settings** is causing a failure while sending the emails. @Tie-fighter is it the same for you?
![image](https://github.com/mautic/mautic/assets/8580942/bfe3dd26-5321-4848-911d-427774a95e26)

@escopecz, @kuzmany, @mabumusa1 Do you have any idea what might be causing this problem in v5? The other headers at this are passed as an array, but the return-path is an `Mime\Address` object. 
https://github.com/mautic/mautic/blob/5.x/app/bundles/EmailBundle/Helper/MailHelper.php#L687

**Comment by mollux** [comment]
@patrykgruszka thanks for highlighting this issue, there is indeed a flaw in the mail header processing.
I'm working on a fix
