### ISSUE TITLE
500 error at first login

### ISSUE THREAD

**Issue by Fred-DTV** [mautic/mautic#12873]
### Mautic Version

5.0.x series

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After finishing the initial setup incl SQL database and creating the admin user I get an immediate 500 error when trying to login.

The error in the logs is the following:
`mautic.CRITICAL: Uncaught PHP Exception Error: "Call to a member function getMessage() on string" at /var/www/mautic/app/bundles/UserBundle/Controller/SecurityController.php line 81 {"exception":"[object] (Error(code: 0): Call to a member function getMessage() on string at /var/www/mautic/app/bundles/UserBundle/Controller/SecurityController.php:81)"} {"hostname":"nextcloud","pid":3076476}
`

At first I thought I had a typo in the password and that's why it couldn't authenticate, but I have changed the password directly in the database (which didn't change anything) and did a complete reinstall with another password, which ended in the same error.

In the apache logs everything seems ok except for this:
`[Fri Nov 03 18:33:32.394462 2023] [php:notice] [pid 3046728] [client 2.39.2.50:45926] PHP Notice:  SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13) in /var/www/mautic/vendor/symfony/http-foundation/Session/Storage/Handler/StrictSessionHandler.php on line 116
`

Another thing that was weird to me is that the initial setup didn't have the e-mail setup page. HAs this been removed in the 5.0.0 setup?

### How can we reproduce this issue?

see above

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as this is most likely to be file/folder permissions related. The forums are the best place for getting help if you encounter problems like this. Thanks!
