### ISSUE TITLE
Many problems after update to Mautic 5

### ISSUE THREAD

**Issue by mhdhamouday** [mautic/mautic#12874]
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

After update to Mautic 5, the focus and campaign is not working.

### What happened?

focus links is show error 500 and in log there is this error message:
[2023-11-06 22:30:24] mautic.WARNING: PHP Warning - Undefined variable $projectRoot - in file xxxx/app/config/paths.php - at line 15 [] {"hostname":"debian","pid":139689}

CAMPAIGN: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e0_.body_text' in 'field list' [] {"hostname":"debian","pid":141488}

### How can we reproduce this issue?

Step 1: create a new focus and go to link /focus/1.js (change id)
![image](https://github.com/mautic/mautic/assets/16991900/01cbda54-af3b-4686-9cb1-1f2abbf42e70)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by escopecz** [comment]
These issues should be fixed now. There were many fixes done to the focus items and $projectRoot since this issue was filed. I'll close it and if you'll still see these issues, please comment and I'll reopen it.

**Comment by zitob9** [comment]
> These issues should be fixed now. There were many fixes done to the focus items and $projectRoot since this issue was filed. I'll close it and if you'll still see these issues, please comment and I'll reopen it.

how did you fix the problem?

**Comment by escopecz** [comment]
Focus item fixes:
https://github.com/mautic/mautic/pulls?q=is%3Apr+focus+items+is%3Aclosed

Project root fixes: 
https://github.com/mautic/mautic/pulls?q=is%3Apr+project+Root+is%3Aclosed+

**Comment by zitob9** [comment]
> Focus item fixes: https://github.com/mautic/mautic/pulls?q=is%3Apr+focus+items+is%3Aclosed
> 
> Project root fixes: https://github.com/mautic/mautic/pulls?q=is%3Apr+project+Root+is%3Aclosed+

Thank you for your assistance. I've tested several suggested solutions, but unfortunately, none of them have worked for me. I'm encountering the issue of "Undefined variable $projectRoot" after upgrading from Mautic 4 to Mautic 5.

**Comment by escopecz** [comment]
Can you post the full error message?

**Comment by zitob9** [comment]
> Can you post the full error message?

2024/01/10 15:02:21 [error] 83844#83844: *361 FastCGI sent in stderr: "PHP message: PHP Warning - Undefined variable $projectRoot - in file /var/www/mysite.com/email/app/config/paths.php - at line 15PHP message: PHP Warning:  Undefined variable $projectRoot in /var/www/mysite.com/email/app/config/paths.php on line 15PHP message: Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The parameter "2FGl2lf3au8bahi" must be defined. - in file /var/www/mysite.com/email/var/cache/prod/ContainerN2dPsF4/AppKernelProdContainer.php - at line 11240" while reading response header from upstream, client: 196.74.11.111, server: trk.mysite.co, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "trk.mysite.co"

**Comment by escopecz** [comment]
I can see it originates from cache. Can you try to remove the cache with `rm -rf var/cache/prod/*`? It will regenerate itself if Mautic has permission to write files to the cache directory.

**Comment by zitob9** [comment]
> rm -rf var/cache/prod/*

nothing changed;

2024/01/10 15:21:32 [error] 83844#83844: *404 FastCGI sent in stderr: "PHP message: PHP Warning - Undefined variable $projectRoot - in file /var/www/mywebsite.com/email/app/config/paths.php - at line 15PHP message: PHP Warning:  Undefined variable $projectRoot in /var/www/mywebsite.com/email/app/config/paths.php on line 15PHP message: Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The parameter "2FGl2lf3au8bahi" must be defined. - in file /var/www/mywebsite.com/email/var/cache/prod/ContainerWrTZhY9/AppKernelProdContainer.php - at line 11234" while reading response header from upstream, client: 196.74.54.111, server: trk.mywebsite.co, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "trk.mywebsite.co"

**Comment by escopecz** [comment]
Does it happen during a specific command or page? Or for everything you do?

**Comment by zitob9** [comment]
> Does it happen during a specific command or page? Or for everything you do?

<img width="866" alt="Screenshot 2024-01-10 at 15 26 43" src="https://github.com/mautic/mautic/assets/17185720/87d80e1c-e450-4845-a92c-4315fa7ef403">

this is error log of nginx: 

2024/01/10 15:21:32 [error] 83844#83844: *404 FastCGI sent in stderr: "PHP message: PHP Warning - Undefined variable $projectRoot - in file /var/www/mywebsite.com/email/app/config/paths.php - at line 15PHP message: PHP Warning: Undefined variable $projectRoot in /var/www/mywebsite.com/email/app/config/paths.php on line 15PHP message: Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The parameter "2FGl2lf3au8bahi" must be defined. - in file /var/www/mywebsite.com/email/var/cache/prod/ContainerWrTZhY9/AppKernelProdContainer.php - at line 11234" while reading response header from upstream, client: 196.74.54.111, server: trk.mywebsite.co, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "trk.mywebsite.co"

**Comment by escopecz** [comment]
Could you test if these changes will resolve it for you? 

https://github.com/mautic/mautic/pull/13193

**Comment by zitob9** [comment]
> Could you test if these changes will resolve it for you?
> 
> #13193

the first problem is solved, but I have a new problem:

2024/01/10 16:16:55 [error] 83844#83844: *545 FastCGI sent in stderr: "PHP message: Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: The parameter "2FGl2lf3au8bahi" must be defined. - in file /var/www/mywebsite.com/email/var/cache/prod/ContainerWrTZhY9/AppKernelProdContainer.php - at line 11234" while reading response header from upstream, client: 196.74.54.149, server: trk.mywebsite.co, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.1-fpm.sock:", host: "trk.mywebsite.co"

**Comment by escopecz** [comment]
That is auto-generated parameter in and auto-generated file in the cache. I can't help with that. The cache reset I posted earlier should resolve that. Another way how to clear cache is this command: `bin/console cache:clear`

**Comment by zitob9** [comment]
> bin/console cache:clear

Thank you so much for your time and your help. I ran 'bin/console cache:clear,' but I encountered:

bin/console cache:clear

                                                                                                                        
 [WARNING] Some commands could not be registered:                                                                       
                                                                                                                        

In AppKernelProdContainer.php line 11234:
                                                    
  The parameter "2FGl2lf3au8bahi" must be defined.  
                                                    

In AppKernelProdContainer.php line 11234:
                                                    
  The parameter "2FGl2lf3au8bahi" must be defined.  
                                                    

In AppKernelProdContainer.php line 11234:
                                                    
  The parameter "2FGl2lf3au8bahi" must be defined.

**Comment by escopecz** [comment]
Yep, so Symfony itself cannot boot due to the corrupted cache. That's why removing the contents of the cache directory is more stable way to clear cache.

Make sure you run these commands from the root folder of your Mautic installation.
If you list what's in the cache with `ls -la var/cache/prod`. You should see a bunch of folders and files. Is that correct? If so, when you run `rm -rf var/cache/prod`, does it return any errors? If you run the `ls -la var/cache/prod` command again, it should be empty. Is it? Then try to just list all Mautic commands with `bin/console` command. Is that working?

**Comment by zitob9** [comment]
> Yep, so Symfony itself cannot boot due to the corrupted cache. That's why removing the contents of the cache directory is more stable way to clear cache.
> 
> Make sure you run these commands from the root folder of your Mautic installation. If you list what's in the cache with `ls -la var/cache/prod`. You should see a bunch of folders and files. Is that correct? If so, when you run `rm -rf var/cache/prod`, does it return any errors? If you run the `ls -la var/cache/prod` command again, it should be empty. Is it? Then try to just list all Mautic commands with `bin/console` command. Is that working?

After re-update Mautic, remove the cache and apply #13193. It works finally.

**Comment by saenzramiro** [comment]
> Could you test if these changes will resolve it for you?
> 
> #13193

Applying those 2 lines in my `paths.php` file and then running` bin/console cache:clear` addressed the issues. Now is all running as expected. Thanks!

**Comment by putzwasser** [comment]
I guess, this can be closed, right?
