### ISSUE TITLE
Focus modal submission does not close modal but re-opens form

### ISSUE THREAD

**Issue by mooror** [mautic/mautic#12881]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

**What happens:**
When the visitor submits the form, the form message is displayed for a short time, and then the form (now empty) is displayed again, and the modal left open.

**What I expect to happen:**
I expect that when a visitor fills out and submits the form that it will display the completed message and then close the modal automatically

### How can we reproduce this issue?

I created a new campaign form, for capturing name and email details for a newsletter sign up form. I also added a honeypot field to this form, and setup up custom functionality for it in the campaign builder. 

![Edit Form - Name and Email Capture Mautic](https://github.com/mautic/mautic/assets/6110819/d96040f1-3bfa-43c9-b75f-304b21eeac6d)
![Edit Campaign Mautic](https://github.com/mautic/mautic/assets/6110819/f371943b-34bb-4dcd-8d03-12d703b27b9b)

After this I created a new focus item, Modal type, for collecting data, and connected the name and email capture form. Also added a bunch of custom css styles
![Newsletter Form](https://github.com/mautic/mautic/assets/6110819/d19905e7-fce0-464b-965a-666fe17f5d85)

Added script tag to the bottom of my page.

### Relevant log output

```shell
Some cookies are misusing the recommended “SameSite“ attribute 2

Cookie “mautic_focus_1” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mooror** [comment]
I am aware of a number of similar issues.

 This is not the same as #2691 or #4111 as I can manually close the modal fine, and all buttons display fine
 Its more similar to #4263, however the solution there was not applicable in my case
 
 It's sounds like it might be the same issue in #6657. But the solution to that was 
 > It has been reported to be due to the Mautic config URL including index.php
 
 Which is not the problem in my case

**Comment by RCheesley** [comment]
Hi @mooror and thanks for reporting this issue and sorry for the delay in triaging. Can you clarify if this is also happening for you in Mautic 5?

**Comment by RCheesley** [comment]
Closing issue due to lack of feedback.
