### ISSUE TITLE
 Bug: Same unsubscibe for all emails after uprade to 1.2.3

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#1288]
If I sent email to lists, unsubscibe link remove still the same lead :(
Mautic 1.2.3

**Comment by alanhartless** [comment]
I'm not able to reproduce this.  I've tried sending locally and through Mandrill via a batch list send and both result in a unsubscribe links that are unique to each lead.  Is there a step I'm missing to reproduce?

**Comment by kuzmany** [comment]
@alanhartless I tried this issue on two different installations.

See video How I test

http://youtu.be/RB4BhVxKmF4?hd=1

**Comment by alanhartless** [comment]
Ok, I see that it's using Mandrill.

Are the unsubscribe links unique? If so, take a look in the email_stats table for the unique string in the URL in the tracking_hash column.  Do the lead IDs match up with the expected email?

**Comment by kuzmany** [comment]
Yes, It's Mandrill.

Unsubscribe links are similar but not the same.
tracking_hashes are different in the tablet, but redirect link forward just for the one of them

**Comment by alanhartless** [comment]
Ah I see. My unsubscribe links aren't getting converted to redirects and I didn't think we had it programmed yet to do so. I'm going to have to see if I can force that to happen to see if we can reproduce.
