### ISSUE TITLE
Dependent Form fields based on selected value not cloned when cloning a form

### ISSUE THREAD

**Issue by multikoop** [mautic/mautic#12898]
### Mautic Version

4.4.x series
v5.0.0-rc1

### PHP version

php:7.4-apache Image

### What browsers are you seeing the problem on?

Chrome

### What happened?

Using Mautic 4.4.10 or v5.0.0-rc1
Creating a campaign form with dependent **Select** fields. e.g. one select list with "Car Makers" an then dependent fields (also **Select**) based on selected value with a select list of the corresponding models.

### Occured behaviour
**When cloning this form, the dependent fields are missing**
<img width="793" alt="image" src="https://github.com/mautic/mautic/assets/400791/216abee7-e644-4d08-b5db-aa3bdb3c6c1c">

### Expected Behaviour
The dependent fields should be cloned as well.
<img width="1216" alt="image" src="https://github.com/mautic/mautic/assets/400791/8685e846-25eb-4700-b698-823d500d6942">

### How can we reproduce this issue?

Step 1: Goto **Components > Forms**
Step 2: Create a campagin **form with a Select field and 2 List Options**.
Step 3: Click "**Add fields based on selected value**". Choose **Select**
Step 4: Add Label, Goto Condition Tab. Define a condition. And also add 2 List options
<img width="510" alt="image" src="https://github.com/mautic/mautic/assets/400791/54c610c5-9543-43d4-8ae0-8eb1aee43399">
Step 5: Save and close.
Step 6: Choose the form and Select "Clone"
<img width="370" alt="image" src="https://github.com/mautic/mautic/assets/400791/05b5376f-c660-4cfd-a53e-2859ec9b0261">

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi @multikoop are you still having this problem with the latest version of Mautic?

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please request a re-open if needed.
