### ISSUE TITLE
[Feature request]  Ability to exclude contacts from a campaign based on tags

### ISSUE THREAD

**Issue by ybombale** [mautic/mautic#1289]
Basically, I would like to be able to run a campaign to all contacts from "XYZ list", but only if they don't have the '*Welcome*' Tag.

**My idea would be something like this:**
**1**- Launch Campaign Builder
**2**- Lead Source > Choose the (Forms or Lists)
**3**- Conditions > Tags -- ('Exist' or 'Doesn't Exist') -- '*Welcome*'
**4**- Add Lead Source.

Thanks in advance.

**Comment by that0n3guy** [comment]
You would do this at the list level.  

* New smart list
* Leads with/without tags 'welcome' 
* create list
* use this list as a lead source.

**Comment by ybombale** [comment]
Ah that is a nice idea, thanks.

However, I think its not what I am looking for in first place. What I meant is something like this:

Example:
Lets say I have a "Gaming site" and I have several forms/lists (Gaming List 1, Gaming List 2,, Gaming List 3, etc) each list is attached to a different promotional follow up **BUT** to the same **welcome follow up** (so the end user gets to knows me the first time he subscribe to my site.)

In case someone signs up on "Gaming List 1", he will receive a **welcome follow up** as well as a **promotional follow up**.

However, in case this same person, join any other **Gaming List** (2 or 3), they would be receiving **only** the **promotional follow up** because they would be carrying the **welcome** tag.

I don't know if now I could explain myself better.
Sorry if not, just I am not native English speaker.

**Comment by that0n3guy** [comment]
What I suggested still works...  I think.  

**Method:**
You have 4 lists: Gaming list 1,2,3 and Welcome list.

* When a person signs up for Gaming list 1, the campaign tags them with "welcome-tag".  They are added via smart list to "welcome list".
* The person later signs up for Gaming list 2, the campaign tags them again with "welcome-tag".  Since the user already has the tag, and was already in the "welcome list" the Welcome campaign should NOT fire again for that user.  

I've not tested this, but I believe this is how it would work.

You might be able to do this without tags as well... do the same as above, but instead of the campaign tagging them, it just ads them to a list.  I don't know if you adding someone to a list twice will cause them to re-run an associated campaign, but I don't think it would.

**Comment by that0n3guy** [comment]
Just for reference, see: https://github.com/mautic/mautic/issues/842#issuecomment-136850198

Quote from that page: 

>>What happens if a lead goes through an entire campaign then is re-added?

>Each event in a campaign can only be executed by the lead once. So if they complete the campaign, they are done and will not be sent through it again unless removed and readded.

**Comment by ybombale** [comment]
hmm, but my problem is that each list has different interests from each other. Lets say, they are all related to gaming, but one is (i.e.) **Xbox Fans** and the other is **PS4 Fans**.

So in this case I just cant add them both to the same **welcome list** because the follow up to each group of users is totally different.

The welcome follow up though, it is the same as its just an introduction to myself.

Check the picture bellow. Maybe it will help you to understand my point, or maybe to help me to understand you better (in case I am still missing something):

(My Idea): http://take.ms/3H79u

Thanks for your time

**Comment by ybombale** [comment]
I think this segmentation option for leads could be added to the already existing **Lead Field Value**. After all the **tags** are part of the core information of the leads (I guess)

**Comment by that0n3guy** [comment]
I'm not sure we are on the same page :), but thats ok, sometimes this is hard to do online.  

From what your saying, I think my solutions still works.   Two questions:
* From what your saying, it sounds like you can say the same "welcome follow up" to all people types (xbox fans, ps4 fans).  Is that correct?
* The people type have topic specific follow-ups sent to them per topic.  Xbox gets xbox followup, ps4 gets ps4 followups.   Correct?

If the above is right, then my solution still works... here is how:

IF you have 3 people types (for example): xbox, ps4, ps3 fans

* You need 4 lists: xbox list, ps4 list, ps3 list, welcome list
* You need 4 campaigns: xbox campaign, ps4 campaign, ps3 campaign, welcome compaign
* Your first 3 campaigns (xbox, ps4, ps3) all add the user into the "welcome list" like so: 
![image](https://cloud.githubusercontent.com/assets/113870/12045433/e7781c30-ae68-11e5-931f-eaf1d8d61e30.png)

* Your last campaign (the "welcome campaign"), This will be non-topic specific messages:
![image](https://cloud.githubusercontent.com/assets/113870/12045470/c5d3993c-ae69-11e5-9986-0fbd67c77e9e.png)

Summary:
To me, this sounds like what you want.   The only problem is if you want to send "xbox welcome" emails that you don't want to send again.  If that's the case, then you would need something like the "lead field value" condition... but that works with tags (I created a feature request here: https://github.com/mautic/mautic/issues/1293)

**Comment by ybombale** [comment]
Well I think we finally are on the same page (or at least quite close) :)

Regarding your questions:

> * From what your saying, it sounds like you can say the same "welcome follow up" to all people types (xbox fans, ps4 fans). Is that correct?

Yes, that's correct.

> * The people type have topic specific follow-ups sent to them per topic. Xbox gets xbox followup, ps4 gets ps4 followups. Correct?

Correct.

So, after seeing your campaign setup diagram, I think its  quite what I was aiming for.

**Let me see if I understood it properly**:

* (taking into account your diagram) once a contact subscribes to the **Xbox list**, he will ALSO be added to the **Welcome Smart List**. Is that correct?

* Next, if the same contact subscribes to the **PS4 list**, he will ALSO be re-added to the **Welcome Smart List** BUT since he already went through the follow ups (the welcome follow up) he would skip the sequence alltogether. Is that right?

If so, please could you help me understand the problem you mentioned at the end:
> The only problem is if you want to send "xbox welcome" emails that you don't want to send again.

This last confused me a bit, because in my case the **welcome emails** are meant to be a one time only event.

Thanks for **creating the feature request**, for **your time** and **patience**.

**Comment by that0n3guy** [comment]
> If so, please could you help me understand the problem you mentioned at the end:

Nevermind that.  We are on the same page now... that might just confuse things :).

> * (taking into account your diagram) once a contact subscribes to the Xbox list, he will ALSO be added to the Welcome Smart List. Is that correct?

> * Next, if the same contact subscribes to the PS4 list, he will ALSO be re-added to the Welcome Smart List BUT since he already went through the follow ups (the welcome follow up) he would skip the sequence alltogether. Is that right?

Yes, correct on both questions.  I would test this: `since he already went through the follow ups (the welcome follow up) he would skip the sequence alltogether.` but that should be how it works.

**Comment by ybombale** [comment]
Ok perfect, then will be testing that and see how it goes.

1000 X thanks for everything.

Also, if its not too much to ask (when you will have some time)... could you please help me to solve the issue I have managing the bounced emails here: [#1292](https://github.com/mautic/mautic/issues/1292)

**Comment by that0n3guy** [comment]
If the above works... please post it here so others can know.  I'll take a look at that other thread.

**Comment by ybombale** [comment]
Ok ;)

**Comment by ybombale** [comment]
I tested it (with 1 email on each campaign) and after the subscriber is re-added to the "Welcome List" this indeed skipped the email on this campaign.

**Comment by escopecz** [comment]
So, is this solved? I think it is with #1293 created. I'm going to close this now. Feel free to re-open if you'd  feel that way ;)
