### ISSUE TITLE
Email are sent to contacts with "Do Not Contact" flag

### ISSUE THREAD

**Issue by notz** [mautic/mautic#12904]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Users that have unsubscribed from newsletters or marketings email still get new mails.

The reason is that many database nowadays are configured to follow ANSI standard. And there are 2 query which are not correctly escaped, thus don't fail but don't return the correct result.

PR #12892 addresses this for the 4.4 branch

This bug is also relevant for 5.x branch

### How can we reproduce this issue?

Step 1: Configure your database sql_mode to use ANSI

```
SET GLOBAL sql_mode = 'ANSI,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_ALL_TABLES';
```

Step 2:  And then test sending to conacts that are set to "do not contact".

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Thanks for reporting the bug @notz and for the PR. Please can you ensure you make a companion PR against the 5.x branch if it impacts 5.x, otherwise it won't be accepted. Thanks!

**Comment by RCheesley** [comment]
@all-contributors please add @notz for bug code

**Comment by mollux** [comment]
@notz thansk for reporting the issue.

I looked into it, and the underlaying issue is that Mautic (any version) is not compatible with `ANSI_QUOTES`, which is part of `ANSI` mode.

The PR you made only addresses 1 specific incompatibility, there are many more.
So more work is needed to make Mautic compatible. I would currently NOT recommend to use Mautic with `ANSI_QUOTES` enabled on database level

**Comment by notz** [comment]
@mollux thx. So what you suggest for mautic, as this is the standard setup on nearly all cloud databases. Add a SQL init command that set the sql_mode or check the sql_mode and display a warning?

I have searched the code and have only found 2 other issues where one is in a test file. The other one is in DownloadRepository. Should i include patches for thos occurences?
