### ISSUE TITLE
Color Picker Malfunction

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#12917]
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

The native Mautic color picker doesn't always function as expected. The issue appears to be related to situations where the user clicks outside the color spectrum, leading to malfunctions.

![image](https://github.com/mautic/mautic/assets/131262825/7f24477d-b9aa-4c6f-a473-ad2bde29ca9b)

### How can we reproduce this issue?

**Important note:** I will provide an example using Point Triggers, but the issue also occurs when creating a new category because we can choose the color in the same manner.
**Tested on 5rc1**

----

Step 1: Navigate to Points > Manage Triggers
Step 2: Create a new trigger
Step 3: Fill the required information
Step 4: In the "Contact Color" field, select the color, and then click outside of it.

![image](https://github.com/mautic/mautic/assets/131262825/db1aa4d7-ae98-481e-a4ca-7f1a0e8063ed)

Step 5: Click on "Save".
_Observation: After saving, note that the color field automatically adds the "#," used in the HEX color, as it should._

![image](https://github.com/mautic/mautic/assets/131262825/5a194ed9-f355-4f61-b586-d6751bfae93d)

Step 6: Now, click on "Save and Close"
Step 7: You will be redirected to the Manage Triggers page. Check the recently created trigger, and the color will appear as a shade of grey.

![image](https://github.com/mautic/mautic/assets/131262825/a594bd21-5578-4d91-b3f2-b1938c84f187)

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by annamunk** [comment]
For some reason the hash is added twice, causing the color to not display correctly on the thumbnail.
![colorpicker](https://github.com/mautic/mautic/assets/102536220/0efafdc7-66fe-46ef-837b-023fef2f4241)
