### ISSUE TITLE
[Issue] Managing Bounced Emails

### ISSUE THREAD

**Issue by ybombale** [mautic/mautic#1292]
Hello,

I'm having problems managing the bounced emails.

I am using Sendgrid, I have set it up as "Other SMTP Server" because I am also facing the same issue mentioned here: https://github.com/mautic/mautic/issues/1088

I have followed all the steps listed in the following guide:
https://www.mautic.org/docs/emails/bounce_management.html

However, although the bounced emails are being sent by Sendgrid to the email I set in "Monitored Inbox Settings", Mautic is unable to fetch the emails and update the leads (change them to my "Bounced Leads List")

Note 1: When testing the accounts in "Monitored Inbox Settings", I get a 'success' message.

Note 2: As mentioned in the "Monitored Email" guide, I've also set the following cron jobs:
               php /path/to/mautic/app/console mautic:fetch:email
              php /path/to/mautic/app/console mautic:list:update

Note 3: I even tried using the script to run Mautic commands from a URL, but it didn't fetch any email.

Any help would be really appreciated it.

Thanks.

**Comment by that0n3guy** [comment]
I would say check your logs, I'm guessing the cron mautic:fetch:email isn't working for some reason.

**Comment by ybombale** [comment]
the mautic/app/logs folder is empty. Any advise?

**Comment by ybombale** [comment]
After I run the script from the command line I get this, (even though there are emails in the inbox):

0 emails processed for {mail.mydomain.com:143/imap/tls/novalidate-cert}INBOX_correo-mautic-bounces@mydomain.com
0 emails processed for {mail.mydomain.com:143/imap/tls/novalidate-cert}INBOX_correo-mautic-unsubs@mydomain.com

**Comment by ybombale** [comment]
Can anybody help me with this issue?
