### ISSUE TITLE
Emails and Landing pages are created multiple times when using "Apply" in Builder

### ISSUE THREAD

**Issue by magdalenaleonow** [mautic/mautic#12928]
### Mautic Version

5.0.x series

### PHP version

8.2.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When creating a new email or landing page, every time "Apply" in builder is clicked, a new email/landing page is created

### How can we reproduce this issue?

1: Create a new landing page/email
2: Fill all required fields 
3: Enter Builder
4: Every time "Apply" is clicked, a new landing page/email is created
5: Another landing page/email is created after saving
![image](https://github.com/mautic/mautic/assets/130159751/1ff93615-b88a-4d39-b90f-53a27defa319)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
@magdalenaleonow I close this now in favor of that one: https://github.com/mautic/mautic/issues/13271 (it seems to be the same issue and has already more interaction). Please join there and add useful information if missing. Thanks a lot!
