### ISSUE TITLE
Memory leak on `mautic:broadcasts:send` command

### ISSUE THREAD

**Issue by iurisilvio** [mautic/mautic#12921]
### Mautic Version

4.4.x series

### PHP version

7.4.33

### What happened?

Memory exaustion after ~50k broadcast messages sent. It happened two times on the same `EmojiHelper` line. I don't know if this is the cause or just a side effect.

The memory linear increases for each batch sent.

### How can we reproduce this issue?

Send a broadcast to a big email list. I'm using AWS SES API for it.

### Relevant log output

```shell
$ php /var/www/html/bin/console mautic:broadcasts:send --limit 1000 --batch 100 -vvv

blackfriday2023
 50000/65372 [=====================>------]  76% 7 mins/10 mins 504.5 MiB
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 135168 bytes) in /var/www/html/app/bundles/CoreBundle/Helper/EmojiHelper.php on line 100

In EmojiHelper.php line 100:
                                                                                            
  [Symfony\Component\ErrorHandler\Error\OutOfMemoryError]                                   
  Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 135168 bytes)  
                                                                                            

Exception trace:
  at /var/www/html/app/bundles/CoreBundle/Helper/EmojiHelper.php:100

mautic:broadcasts:send [-c|--channel [CHANNEL]] [-i|--id [ID]] [--min-contact-id [MIN-CONTACT-ID]] [--max-contact-id [MAX-CONTACT-ID]] [-l|--limit [LIMIT]] [-b|--batch [BATCH]] [--bypass-locking] [-t|--timeout TIMEOUT] [-x|--lock_mode LOCK_MODE] [-f|--force] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there! Sorry for the delay in getting back to you on this.

Can you please clarify if this is also happening with Mautic 5, as there's been a lot of development since the 4.x series.

**Comment by iurisilvio** [comment]
Hi! I'm not using mautic much now, I never ran it on mautic 5.

**Comment by RCheesley** [comment]
Closing due to lack of feedback to troubleshoot the issue and likely using outdated version of Mautic.
