### ISSUE TITLE
Mailer no longer supports SNS confirmation

### ISSUE THREAD

**Issue by glr5048** [mautic/mautic#12930]
### Mautic Version

5.0.x series

### PHP version

8.1

### What browsers are you seeing the problem on?

Not relevant

### What happened?

In Mautic 5.0.x, the mailer callbacks have been consolidated to a single mailer callback (mailer/callback, instead of mailer/amazon_api/callback). Amazon SNS is no longer able to confirm the callback is valid before being able to proceed. This coming from mailerCallbackAction in \app\bundles\EmailBundle\Controller\PublicController.php not properly handling the request.

### How can we reproduce this issue?

Step 1: Set up SES mailer
Step 2: Attempt to connect SNS to the new Mailer callback (domain.com/mailer/callback)
Step 3: Send confirmation to the callback
Step 4: SNS receives 404 because it receives a response of "No email transport that could process this callback was found" 

### Relevant log output

```shell
From the Apache logs:
"POST /mailer/callback HTTP/1.1" 404 4895 "-" "Amazon Simple Notification Service Agent"
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by mabumusa1** [comment]
Hello @glr5048, 

You are right with your observation, SES plugin has moved to an external plugin that I am working on, I will share with you and the community the final plugin (I think I will get it done this week) once that is installed and configured on your Mautic 5 installation, this issue will not appear anymore.

**Comment by micaelomota** [comment]
Hey guys, I just installed mautic using docker (mautic/mautic:6.0.3-20250804-apache) and I'm facing this same issue. Did anybody find a solution?

<img width="943" height="47" alt="Image" src="https://github.com/user-attachments/assets/cc3e8bb4-2981-444f-a7ad-1f8f764f147f" />
