### ISSUE TITLE
[Feature request] Condition based on lead tags

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#1293]
We have a `form field value` and `lead field value` condition... would be nice if we could do this with tags as well.

**Comment by kuzmany** [comment]
:+1:

**Comment by IADDIC** [comment]
+1 for smart tag features like specific emails sent based on tag.  Also ability to sort leads/view leads based upon tag.

**Comment by escopecz** [comment]
@IADDIC FYI, you can filter leads by a tag with searching `tag:tag_name` in the lead manager.

**Comment by IADDIC** [comment]
@escopecz thanks!  I missed that tip!  Keep up the great work.  Rich

**Comment by yyil** [comment]
upvote

**Comment by jjroelofs** [comment]
+1

**Comment by npracht** [comment]
Hi, i think it's related to https://github.com/mautic/mautic/issues/1431

**Comment by andersonid** [comment]
yes, please!

**Comment by escopecz** [comment]
Probably solved by https://github.com/mautic/mautic/pull/2095. Tests are welcome
