### ISSUE TITLE
[feature request] Export of a lead history through API

### ISSUE THREAD

**Issue by bzctoons** [mautic/mautic#1296]
Hello
It could be usefull to have a way to retrieve lead history through API, as example to retrieve all the pages opened by a given lead

**Comment by kuzmany** [comment]
:+1:

**Comment by npracht** [comment]
Hi, must be answered by https://github.com/mautic/mautic/pull/1899

**Comment by escopecz** [comment]
Docs here: https://developer.mautic.org/#get-contact-events
