### ISSUE TITLE
[bug] Cannot use Owner field as filter on smart lists

### ISSUE THREAD

**Issue by 432jhfbs** [mautic/mautic#1297]
I have a problem with smart lists. When I create one, I am trying to filter by owner. From the "Filters" tab I click on the drop down and add "Owner". It then adds this to the filter, and I leave the match as "equals" and then type in the owners name. There is no autocomplete when typing in the owner - this is important as noted below. I have tried putting in the owner three ways:

1. Firstname Lastname
2. Lastname, Firstname
3. Numeric ID

When I click on 'Apply' it goes back to the 'Details' tab of the filter, and the 'Filters' tab is highlighted in red with an exclamation mark next to it. Click on the 'Filters' tab again it says 'A value is required.' on the 'Owner' filter.

When I type in the owner box now, it auto-completes. e.g. I type in the first few letters of the name and it comes up. However, when I try and apply it still has the exclamation mark next to filters.

This has been reproduced by John on Slack chat.

**Comment by 432jhfbs** [comment]
Hopefully this is visible now - Github's bots had marked my account as a bot and so this was hidden.

**Comment by escopecz** [comment]
I can replicate, but I cannot orient in the list filter code well enough to fix it :/
