### ISSUE TITLE
Cannot filter form submissions in the API /api/forms/*/submissions

### ISSUE THREAD

**Issue by jensolsson** [mautic/mautic#12982]
### Mautic Version

4.4.x series

### PHP version

Not relevant

### What happened?

A bug happened!

I tried to retrieve a list of submissions on a form and tried to filter and sort but it does not work.

For example if I add
orderBy = id
orderByDir=asc

It fails with "Looks like I encountered an error (error #500). If I do it again, please report me to the system administrator!"

`[2023-12-05 12:16:26] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT r.submission_id, s.date_submitted as dateSubmitted, s.lead_id as leadId, s.referer, i.ip_address as ipAddress, scrive_company,r.scrive_company_number,r.scrive_adress,r.scrive_postnummer,r.scrive_postort,r.scrive_fakturareferens,r.scrive_faktura_epost,r.scrive_leveransadress,r.scrive_postnummer_leveran,r.scrive_postort_leverans,r.scrive_kontakt_namn,r.scrive_kontakt_epost,r.scrive_kontakt_mobilnr,r.scrive_fname,r.scrive_lname,r.scrive_mobile,r.scrive_email FROM form_results_23 r INNER JOIN form_submissions s ON r.submission_id = s.id LEFT JOIN ip_addresses i ON s.ip_id = i.id WHERE r.form_id = 23 ORDER BY fs.id asc LIMIT 30':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fs.id' in 'order clause'" at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 79 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT r.submission_id, s.date_submitted as dateSubmitted, s.lead_id as leadId, s.referer, i.ip_address as ipAddress, scrive_company,r.scrive_company_number,r.scrive_adress,r.scrive_postnummer,r.scrive_postort,r.scrive_fakturareferens,r.scrive_faktura_epost,r.scrive_leveransadress,r.scrive_postnummer_leveran,r.scrive_postort_leverans,r.scrive_kontakt_namn,r.scrive_kontakt_epost,r.scrive_kontakt_mobilnr,r.scrive_fname,r.scrive_lname,r.scrive_mobile,r.scrive_email FROM form_results_23 r INNER JOIN form_submissions s ON r.submission_id = s.id LEFT JOIN ip_addresses i ON s.ip_id = i.id WHERE r.form_id = 23 ORDER BY fs.id asc LIMIT 30':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'fs.id' in 'order clause' at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fs.id' in 'order clause' at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fs.id' in 'order clause' at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:141)"} `

Should fs.id really be s.id instead? 

Same issue seem to apply to any filters I try to add

### How can we reproduce this issue?

Described above

### Relevant log output

```shell
Above
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by dsp76** [comment]
Tested it with 4.4.12 and 5.0.4... used Basic Auth. Its working fine!
My request is build like this GET {{site}}/forms/FORM_ID/submissions?orderBy=s.date_submitted&orderByDir=asc

Thats according to the docs: https://developer.mautic.org/#list-form-submissions

Please move it to the forum to let us discuss further. Regarding your last question s.id works for me. fs.id breaks it.
