### ISSUE TITLE
GoogleImageProxy Email Bug

### ISSUE THREAD

**Issue by melaleuca** [mautic/mautic#1298]
I have notice that when you send an email to a gmail account with the pixel tracking it updates the last active status of a lead/leads, even when the client has not viewed the email again.

I am guessing google image proxy checks images on a constant base even if the email was sent out months ago. 
I notice a bunch of my leads has the save last active timestamp, when looking at the details looks like GoogleImageProxy is calling the pixel.

Perhaps we should have a way to ignore GoogleImageProxy from calling the pixel tracking as it will update all leads last active time stamp.

**Comment by melaleuca** [comment]
![njx2lcf](https://cloud.githubusercontent.com/assets/91725/12054360/397945fa-aee0-11e5-90fb-23ef4c6264d8.png)

**Comment by that0n3guy** [comment]
+1... not good.

**Comment by hansakoch** [comment]
@melaleuca did you try a whitelist?
https://www.mautic.org/community/index.php/2606-google-apps-gmail-set-up-an-image-url-proxy-whitelist/0
