### ISSUE TITLE
Database Records on Busy Site Out of Control

### ISSUE THREAD

**Issue by healthstatus** [mautic/mautic#1299]
After running Mautic for about a month, I have about 4 million records in the audit log table, 1.7 million each in the ip_addresses, lead_ips_xref, and leads tables and 4.6 million in the page hits.   There needs to be some sort of cleanup function or documentation on what can be pruned out after a certain amount of time.

I have not been able to run the dashboard page for about 2 weeks now, and I am assuming the number of queries it is trying to run is timing out.

**Comment by alanhartless** [comment]
Yes, we've started discussing this and how best to clean things up while realizing some will want to keep data longer than others. 

The audit log table can be truncated however you like.  It's main role is to generate the recent activity tables while also giving some insight into what Mautic may be doing behind the scenes. It can be truncated or pruned based on date without serious implications. (Worse case is your "Recent Activity" lists will be altered). There was also a few minor bugs that caused some unnecessary entries to that table that were addressed in 1.2.3.  

For the leads and IP tables, sounds like a lot of unique visitors.  In your opinion, how long would you want to give anonymous leads "a chance" to be captured and retain their tracked activity? At what point is an anonymous lead "stale" and can be purged? And does it matter if the lead comes back after X amount of time, converts to a known lead, but they've been purged earlier and thus lost their history?

Have you tried 1.2.3? Some queries were optimized to hopefully restore dashboard access for large underlying data sets.

**Comment by healthstatus** [comment]
Yes, have 1.2.3 running.

I think the amount of time should be a configurable setting.  My software business (much lower volume), I would probably want 1 month to 6 weeks to try and convert from anonymous to identified.  My consumer site, I would want about 3 days.   If they came back after that, they are probably looking at something else anyway since our content is rolling pretty fast.

**Comment by dbhurley** [comment]
This has been addressed for 2.1. Will close after the PR is merged.

**Comment by alanhartless** [comment]
New command available in 2.1.0 for this. https://mautic.org/docs/en/setup/cron_jobs.html#cleanup-old-data

**Comment by taropaa** [comment]
@alanhartless Is there a way to only purge anonymous leads, while keeping known ones in? We're planning on using mautic to keep track of existing customers too, so we'd want to keep the identified leads in place. Thank you
