### ISSUE TITLE
check pages for tracking code....

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#1302]
Can you add something to the admin panel that would have mautic crawl all the pages in a website or folder within a website to see if the tracking code is detected and installed correctly?

Or at least be able to check individual urls?

I would also like to be able to check 3rd party websites as well for my code

**Comment by ahansson89** [comment]
I don't think this should be a feature added to the core. It is not hard to make a crawler in node or python that checks for this.

**Comment by 4evermaat** [comment]
Not all of us are programmers. The idea is to make it end-user friendly. But since you seem to make it look so easy, would you like to share some plugin I could add that would do this in a simple gui format?

**Comment by escopecz** [comment]
I can imagine this could be a feature request, but I'd give it very low priority. Because usually, the web pages are generated by some server application. Every such app allows to insert the Mautic tracking pixel into one file and it will show up on every page generated by that app. So I don't see a need to scrape every page generated if the tracking pixel works there. Simply, if it works on one page, it will work on all of them. The checker would be a good tool if we'd write the static HTML pages like in the last century. @4evermaat do you have some real life use case where this checker is needed? Where do you need to add the tracking pixel to every page by hand?

**Comment by 4evermaat** [comment]
Although I suppose it could be automated, I originally intended for it to be more of a button within the config menu of mautic admin panel where a user could verify that the pixel code is installed.

One example would be a forum post on a different website.  You may have an article there or other item and wish to track user engagement on that site.  You usually cannot embed/inject javascript or other code on someone else's website directly, but a forum post usually can accept url images.  That was why I also wanted the ability to customize the image that mautic could serve and not be limited to the 1 x 1 px generated image.  Perhaps have more than one image link.  One could be the standard 1 x 1 px generated image and another one could be a custom image stored as an asset that is still delivered dynamically, but it would blend into the page more.  I hope this makes sense.

I'm just big on redundancy or backups to backups.  How do I 'know' that the tracking code is really there?

I think there was a separate issue about having a dedicated `do not track` cookie and ability to check that the `do not track` cookie is installed in that browser correctly https://github.com/mautic/mautic/issues/1304

**Comment by escopecz** [comment]
I can see you have a lot of ideas. That's great! From the technical point of view:

> I originally intended for it to be more of a button within the config menu of mautic admin panel where a user could verify that the pixel code is installed.

How would Mautic know where you've installed the tracking pixel? Should Mautic scrape the whole pages on the internet?

> One example would be a forum post on a different website. You may have an article there or other item and wish to track user engagement on that site.

I'm not sure if this is illegal or not, but I would't track website which is not mine even though I wrote some content there. But that's my personal believe.

> I also wanted the ability to customize the image that mautic could serve and not be limited to the 1 x 1 px generated image.

You can use whatever image in your post and still add the invisible transparent tracking gif image to the post as well. Very few people will read the source code.

**Comment by 4evermaat** [comment]
>How would Mautic know where you've installed the tracking pixel? Should Mautic scrape all the pages on the internet?

You don't crawl/index the entire internet.  You have a page in the admin panel with a few inputs to crawl specific urls to crawl (e.g. homepage, sitemap.xml or similar page). A checkbox for 'search child pages' would crawl links but only those that are within a certain folder or domain.  You could automate this command with cron job or whatever, but it could be done manually also by submitting a button.

>but I would't track website which is not mine even though I wrote some content there. But that's my personal believe.

People do joint ventures all the time (product launches, guest posts, etc).  Are you suggesting that marketers don't attempt to track those people?

> You can use whatever image in your post and still add the invisible transparent tracking gif image to the post as well. Very few people will read the source code.

The idea is to be able to disguise the tracking gif if needed.  I'm not suggesting to get rid of the existing implementation.  Just to add an additional way to serve the image in case the 1 x 1 image is flagged for spam or something.  I could load a "real" image and no one would be any wiser.
__
an ability to move the tracking gif to a different folder of the website would be nice too.  I might put that in a different request. Does it have to be labeled mtracking.gif?  Or can we just use 301 rewrite to solve the problem?
