### ISSUE TITLE
Error view of a landingpage with smartphone

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#13047]
### Mautic Version

4.4.x series

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Firefox

### What happened?

Mautic 4.4.10
I made a landingpage with form and picture. The Laptops shows it normal - the smartphone view is not usable. 
(btw - to place the image in the middle function i miss/didn't found....)

Here are the screenshots

Laptop - Landingpage Builder:

![Landingpage Builder](https://github.com/mautic/mautic/assets/96744684/52a943ed-ec56-4ad7-98c1-2610c0e03643)

Laptop Preview

![Landingpage Preview - Laptop](https://github.com/mautic/mautic/assets/96744684/b825960b-e7b8-47ce-8db1-3aed3ce79fb1)

Smartphone - No Form is shown on the Smartphone and the image is too big

![View on Smartphone](https://github.com/mautic/mautic/assets/96744684/623caaf7-8e8e-4fe2-9caa-33eabf1c11a4)

### How can we reproduce this issue?

Step 1: Make a Landingpage with a form and image and look with a smartphone to it

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
