### ISSUE TITLE
reminders to update geoip database....

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#1306]
I would like monthly or user-customizable reminders (or notifications) on needing to update the maxmind GeoLite database.  

Also, any error messages in the Mautic log that the database is missing should specify where to go and download the database.

I respect that the updates must be requested manually. I just don't want it to lapse.  Perhaps sharing how often MaxMind updates the GeoLite database would help in determining update frequency.

**Comment by alanhartless** [comment]
I'll be documented this tonight in addition to what we discussed in Slack but there is a way you can cron the updates. Maxmind updates their database on the first Tuesday of each month (http://dev.maxmind.com/geoip/geoip2/geolite2/) although I'm not sure what time.  So add the following cron job to run every Wednesday (there are ways to get a cron to run the first Wednesday of the month but I haven't tested it so you can google it or just run it every Wednesday as it's not gonna hurt anything).  

`php /path/to/mautic/app/console mautic:iplookup:download`

Of course replace /path/to/mautic with the path to your Mautic installation.
