### ISSUE TITLE
Enhancement and Missing Modal Title in GrapeJS

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#13072]
### Mautic Version

5.0.x series

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

In Mautic 5, a new feature was introduced in the GrapeJS builder, allowing users to quickly save changes to emails or landing pages without having to close the builder, save, and reopen it.

However, there is an issue with the modal that displays error messages. It lacks a proper title, and the close button has a white background that doesn't align with the modal's style and color scheme.

### How can we reproduce this issue?

Step 1: Navigate to Channels > Email.
Step 2: Create a new email.
Step 4: After that, do not fill in any other fields. Select any email template.
Step 5: Click on "Builder".
Step 6: Make an edit to the selected email.
Step 7: After editing, on the top right, click on the checkmark icon.
[image](https://github.com/mautic/mautic/assets/131262825/4e9783b4-a94b-47c8-8a78-8b03672af7ca)

Step 8: A modal with a warning will pop up.
[image](https://github.com/mautic/mautic/assets/131262825/311ffc05-4132-4235-8e08-63d015d12ed0)

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by RCheesley** [comment]
Closing as resolved with https://github.com/mautic/mautic/pull/13207.
