### ISSUE TITLE
Using Segment filter in Segments seems to be very inefficient

### ISSUE THREAD

**Issue by driskell** [mautic/mautic#13088]
### Mautic Version

4.4.x series

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When creating a segment that is set to exclude contacts (or include contacts) from many other segments (for example to create a segment of people who did do a set of things), the resulting query is one that includes the query for all segments all combined into a single one, and it tends to be comparatively slow.

A potential solution is:
* When loading lists to rebuild in mautic:segments:update, order them so that those with a Segment filter are only processed once the corresponding segment is rebuilt
* Generate queries that reference the current set of contacts in the segment - don't include the segment query itself

### How can we reproduce this issue?

Step 1: Create a few segments
Step 2: Create a new segment that has filters but one of them excludes contacts from other segments
Step 3: Run the check-builder and note that the segment query includes all segments queries - a rather complex query

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

**Comment by driskell** [comment]
@escopecz Would be great to here thoughts before I start on any change. I am thinking that the segment updates would be extremely faster in my case (and in most I would expect) if it didn't "embed" the query for segments used as filters and instead just used the segment contents. Then in the command to update segments it can use the `getResolutionPlan` to generate in the correct order.

**Comment by escopecz** [comment]
Hi, perhaps you are talking about these 2 options?:
- https://github.com/mautic/mautic/pull/10063
- https://github.com/mautic/mautic/pull/12810

Please join the discussion
