### ISSUE TITLE
DDEV is running in Prod mode

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#13108]
### Mautic Version

5.0.x series

### PHP version

8

### What happened?

Since we implemented the new way to use environments, DDEV is operating in Prod - rather than Dev - mode.

Hopefully a quick fix but it means everyone is testing in prod mode by default.

### How can we reproduce this issue?

Step 1: open a PR on Gitpod and notice that it's not got the developer toolbar along the bottom or in dev mode.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team!

**Comment by LordRembo** [comment]
Does this need a fix though? When starting up a Mautic for development, it's kinda good practice to set up your env config and you can do with it what you want, like adding `APP_ENV=dev` and `APP_DEBUG=1`
I missed this the first times I ran Mautic in DDEV, so maybe a solution is to add some documentation to the dev docs about this?

**Comment by LordRembo** [comment]
Alrighty, should just be a config change. I'll pick this up and add a PR
