### ISSUE TITLE
3rd total crash of Mautic - no data anymore

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#13115]
### Mautic Version

4.4.x series

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Firefox

### What happened?

As here described, i had today the 3rd time a complete empty dasboard and no contacts. 
(https://forum.mautic.org/t/mautic-empty-data-2nd-time/30195)

I hat to rebuild my server to run Mautic again. 

How can i find the reason?

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team!

**Comment by dsp76** [comment]
Hi @stefan-franz ... as with our other discussions, its likely related to misconfigurations of the server. Its not a general issue and can't be recreated.
