### ISSUE TITLE
Inaccurate Dashboard Stats

### ISSUE THREAD

**Issue by bananacy** [mautic/mautic#13120]
### Mautic Version

5.0.x series

### PHP version

8

### What browsers are you seeing the problem on?

Chrome

### What happened?

Dashboard stats charts are inaccurate. Fresh install few days ago, added one contact and left it.. Checked today and it say 6 contacts

https://ibb.co/DW1X2Qy
https://ibb.co/R39ZW6y

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team!

**Comment by bananacy** [comment]
Is it counting Anonymous contacts? I toggled the icon and have 6 anonymous ips, how they were created i don't know.
it says "Contact was created by http://mautic.domain.com/wp-admin/setup-config.php?step=1"
I do NOT have wordpress installed.

**Comment by bananacy** [comment]
The stats seems to have corrected themselves now. and correctly show the new 1 contact i added today and 1 added few days ago. I delete the anonymous ips.

**Comment by RCheesley** [comment]
I'm going to close this one down as it's not a bug (sorry nobody got back to you sooner!) - in the future please post things like this over at https://forum.mautic.org and then if it's determined to be a bug, you can raise it over here.
