### ISSUE TITLE
Change the font for better compatibility and make it self-hosted

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13139]
### Description
Changing the font to improve compatibility and self-hosting it would involve selecting a more universally compatible typeface and hosting it on the platform's servers to optimize font rendering and loading speed.

We are chaning from Open Sans to Source Sans Pro (already used on marketing resources).

### Impact
Implementing this change would likely lead to improved readability, cross-device compatibility, and faster page load times, ultimately enhancing the overall user experience and ensuring we do not depend on Google Fonts servers.

**Comment by valerio-bozzolan** [comment]
Minor additional note:

I'm happy to see this issue as already-closed.

Google Fonts is a problem in general nowadays as far as I always see. Embedding a Google Fonts from Google servers means that every visitor sends their data to Google, in real-time, including but not limiting to: IP address, user agent, browser language preferences, DNT, and other data that easily fingerprint every users, potentially with a 1:1 match factor, easily for Google indeed. Avoidable by self-hosting.

Self-hosting is usually GDPR-super-friendly 👍 Thanks.

**Comment by andersonjeccel** [comment]
@all-contributors please add @andersonjeccel for projectManagement
