### ISSUE TITLE
cron job jailshell failure not processing job

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#1313]
https://github.com/mautic/mautic/issues/1306

I tried to implement a cron job to update the geoLite IP database.  I got the following error:

Cron <user@venus> [ "$(date '+%a')" = "Wed" ] php /home/user/public_html/mautic/app/console mautic:iplookup:download >/dev/null

/usr/local/cpanel/bin/jailshell: line 0: [: missing `]'

![innerplanet cron job failed jailshell](https://cloud.githubusercontent.com/assets/830306/12106185/42f98730-b38f-11e5-934a-1b8603b30692.gif)

So I need to determine if it is mautic's handling of the cron job, or if it is this so-called "jailshell" that is causing the problem?

Now the webhost said something to the effect that if the cron job requires jailshell, then I might be SOL because they disabled jailshell.   So assuming that I need jailshell access, and I cannot get it, is there a workaround cron implementation to execute cron or other automation tasks?

Is jailshell required for *all* mautic cron jobs?
------
edit:  when using just the plain command "php /home/user/public_html/mautic/app/console mautic:iplookup:download", the cron job is a success.  So the problem is a syntax error

**Comment by escopecz** [comment]
I found this definition of jailshell:
>Jailshell is a level of shell (SSH) access that limits a user to his or her specific directory structure. Under regular SSH when users log into their servers they are taken to their home directory and can execute commands within their directory structure.

So it isn't a Mautic issue. I'll close this PR then.
