### ISSUE TITLE
Redesign the entire header

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13137]
### Description
A complete header redesign aims to enhance navigation, accessibility, and visual appeal of the platform's top interface.

### Impact
Revamping the header would significantly improve user engagement, ease of use, and overall aesthetics, resulting in a more enjoyable and efficient user experience.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Still relevant

**Comment by andersonjeccel** [comment]
Improvements were made to the header appearance. It seems enough for now.
