### ISSUE TITLE
Redesign the notification panel

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13141]
### Description
Redesigning the notification panel involves revamping its visual and functional aspects to create a more intuitive and engaging interface for presenting notifications and alerts.

### Impact
A redesigned notification panel could significantly enhance user engagement, making it easier for users to stay informed about important updates within the platform. This improvement would likely lead to increased user interaction with notifications, contributing to a more dynamic and responsive user experience.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Still relevant
