### ISSUE TITLE
Redesign the page body styles

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13142]
### Description
The task involves a comprehensive overhaul of the page body styles to modernize and refine the visual presentation and layout.

### Impact
Redesigning the page body styles would result in a more contemporary and aesthetically pleasing user interface, potentially enhancing user engagement and the overall perception of the platform's design and usability.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Still relevant

**Comment by andersonjeccel** [comment]
Fixed in https://github.com/mautic/mautic/pull/13380
