### ISSUE TITLE
Align tabs to the design system

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13159]
### Description
Tabs in the application are not currently consistent with the established design system, leading to visual disparities and a lack of cohesive design; the objective is to align tabs with the design system's standards.

### Impact
Aligning tabs with the design system will improve the overall visual coherence of the interface, providing users with a consistent and intuitive navigation experience and enhancing the application's aesthetic appeal.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Still relevant

**Comment by andersonjeccel** [comment]
Done
