### ISSUE TITLE
Align search bar to the design system

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13157]
### Description
The current search bar design deviates from the established design system, resulting in inconsistency and a disjointed user experience; we aim to align the search bar with the design system's guidelines.

### Impact
Aligning the search bar with the design system will enhance the overall coherence of the interface, ensuring a consistent look and feel, and improving user recognition and usability of the search functionality.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Still relevant

**Comment by andersonjeccel** [comment]
This was fixed by #14275 and #14353
