### ISSUE TITLE
Improve tags system

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13158]
### Description
Tags within the application currently do not adhere to the design system, causing visual incongruity and inconsistency; our aim is to align tags with the established design system guidelines.

### Impact
Aligning tags with the design system will create a harmonious and uniform appearance, making it easier for users to understand and interact with tagged content while maintaining a cohesive visual identity throughout the application.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Still relevant
