### ISSUE TITLE
New headings design

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13154]
### Description
The current heading design features small font sizes across various headings, which leads to readability issues; we intend to revamp the headings design to address this problem and meet modern webdesign standards.

### Impact
By introducing a new headings design with improved font sizes, readability will be significantly enhanced, making the content more accessible and user-friendly for all users.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Still relevant

**Comment by andersonjeccel** [comment]
Done
