### ISSUE TITLE
Can't update node delay in campaign

### ISSUE THREAD

**Issue by ptcc** [mautic/mautic#1315]
I created a campaign set to wait 1 day and then send an email.
After saving the campaign with "save and close" i f i try to change the delay to 10 minutes(example), and hit "close builder"-> "save and close", mautic says it saved but it did not (in db i can see it is the same and if i go agin to the builder it is still 1 day)

other changes like node position are saved.

**Comment by alanhartless** [comment]
Yea, this was a bug that slipped in via some version prior to 1.2.3.  I'm surprised it hasn't come up earlier.  But https://github.com/mautic/mautic/pull/1284 fixes it and there's a quick hot fix at the bottom of the description for Campaigns if you prefer that rather than all the PR changes.

**Comment by ptcc** [comment]
thanks :) the hotfix works fine
