### ISSUE TITLE
Add a 'provide feedback' link on left sidebar

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13160]
### Description
The absence of a 'provide feedback' link on the left sidebar hinders users' ability to easily share their thoughts or report issues; we intend to add this link for improved communication.

### Impact
Adding a 'provide feedback' link on the left sidebar will enhance user engagement and allow for more efficient feedback collection, fostering a more responsive and user-centric development process.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Still relevant
