### ISSUE TITLE
Improve batch button UI

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#1317]
There is a row of icons in most list views for batch actions when a list item is checked.  When there is a bunch such as on the Manage Leads lists, it gets crowded and confusing as to what's what.  We need to improve this UI.  

![](http://alan.direct/drop/2016-01-05_11-58-05.png)

For one, those buttons should only appear if there is something actually checked.

Two, not sure what it would look like but we need some way to better indicate their purpose.  Not sure if that means converting it to a drop down like menu with an icon and text or what.

**Comment by escopecz** [comment]
Done :)
