### ISSUE TITLE
Mautic 5 Can't find amazon smtp

### ISSUE THREAD

**Issue by RabeeBrahimi** [mautic/mautic#13181]
### Mautic Version

5.0.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

Installed Mautic 5. But when i go to the configuration to configure the smtp. I can't find it, there is a new DSN section but i can't choose an smtp provider to use e.g amazon smtp. 
<img width="909" alt="mautic-config" src="https://github.com/mautic/mautic/assets/130481723/9facfd2f-0156-48ab-9e42-1c0bb599af80">

### How can we reproduce this issue?

Step 1: Install new released 5 mautic
go to configuration to set up a sending provider. 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by escopecz** [comment]
In M5 we had to swap the PHP libraries that are sending emails as the old one (Swift Mailer) is end of life for many years.

There are 2 ways how to configure Amazon SES SMTP on Mautic 5. 

### Composer

One is to install the official Symfony Amazon SES transport via Composer:

`composer require symfony/amazon-mailer`

Docs:
- https://symfony.com/doc/current/mailer.html#using-a-3rd-party-transport
- https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/Mailer/Bridge/Amazon/README.md

### SMTP

Amazon must give you all the credentials you need to input them to the right fields that you can see in your screenshot.

### Amazon SES API

There is a third option to use Amazon SES API plugin that @mabumusa1 is working on. Not sure if that's ready. I'd prefer this option as API is way faster than SMTP. But you can start with one of the options above and get back to this when you'll need to speed this up.

There is also a work being done as we speak on the new Mautic user documentation where all this will be described.

I will close this ticket for now as this is just a documentation question.

**Comment by RabeeBrahimi** [comment]
Thanks will look at the options you mentioned.

**Comment by RabeeBrahimi** [comment]
Is there any new documentation for Version 5? i am finding it difficult to set up a emails to be sent using the queue. Can't find anything in documentation.

**Comment by escopecz** [comment]
Here are the new docs: https://docs.mautic.org/en/5.x/channels/emails.html#email-delivery

**Comment by alvaroenoht** [comment]
Hi, I tried to setup the mailer as the example provided, but is not working, it tells me The "amazon+api" scheme is not supported. o the The "sendgrid+api" scheme is not supported. , I updated the config/local.php file and set it manually, but is not working either. 
PHP8.1 Mautic 5.0.1

**Comment by escopecz** [comment]
For others with this issue, see https://github.com/mautic/mautic/issues/13222#issuecomment-1891088286
