### ISSUE TITLE
HTTP 500 after upgrade to 5.0.1

### ISSUE THREAD

**Issue by Tie-fighter** [mautic/mautic#13196]
### Mautic Version

5.0.x series

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After getting rid of #13192 and completing the update (mautic:update:apply --finish), I am receiving an http error 500 page

### How can we reproduce this issue?

Step 1: Update from 5.0.x to 5.0.1

### Relevant log output

```shell
Nothing in nginx, php-fpm or mautic_prod
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by bananacy** [comment]
I'm also getting error 500, mine's on login
PHP Fatal error:  Uncaught Error: Undefined constant Mautic\UserBundle\UserEvents::USER_FORM_POST_LOCAL_PASSWORD_AUTHENTICATION in /home/xxxxx/xxxxxxx.com/app/bundles/UserBundle/EventListener/PasswordSubscriber.php:22

**Comment by jonathandhn** [comment]
> ### Mautic Version
> 5.0.x series
> 
> ### PHP version
> 8.0.30
> 
> ### What browsers are you seeing the problem on?
> Not relevant
> 
> ### What happened?
> After getting rid of #13192 and completing the update (mautic:update:apply --finish), I am receiving an http error 500 page
> 
> ### How can we reproduce this issue?
> Step 1: Update from 5.0.x to 5.0.1
> 
> ### Relevant log output
> ```shell
> Nothing in nginx, php-fpm or mautic_prod
> ```
> 
> ### Code of Conduct
> * [x]  I confirm that I have read and agree to follow this project's Code of Conduct
> 
> 
> Care about this issue? Want to get it resolved sooner? If you are a [member of Mautic](https://www.mautic.org/become-a-member-of-mautic), you can add some funds to the [Bounties Project](https://opencollective.com/mautic/projects/bounties) so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs [here.](https://contribute.mautic.org/product-team/mautic-bounty-programme)

Hi, may have you tried both to check that bin/console can be executed (chmod 710 at least) and then having tried to clear the cache ( with enough ram to generate the new one so with ```php -d memory_limit=512M bin/console cache:clear``` ) ?

**Comment by bananacy** [comment]
php -d memory_limit=4024M bin/console cache:clear

 // Clearing the cache for the prod environment with debug false

mmap() failed: [12] Cannot allocate memory
mmap() failed: [12] Cannot allocate memory
In Translator.php line 348:
  Error: Out of memory (allocated 196083712) (tried to allocate 495616 bytes)


****
I gave up and put back v4. i'll deal with it in the future. thanks. i'm sure its my fault somehow.

**Comment by Tie-fighter** [comment]
> Hi, may have you tried both to check that bin/console can be executed (chmod 710 at least) and then having tried to clear the cache ( with enough ram to generate the new one so with `php -d memory_limit=512M bin/console cache:clear` ) ?

Yes, did both before reporting the issue.

**Comment by escopecz** [comment]
I don't see any other reason for this error than some of the files being in the M4 state and some in the M5 state. This is the problematic line and constant:

https://github.com/mautic/mautic/blob/5.x/app/bundles/UserBundle/EventListener/PasswordSubscriber.php#L22C37-L22C37

But it is defined:

https://github.com/mautic/mautic/blob/5.x/app/bundles/UserBundle/UserEvents.php#L138

How does your UserEvents.php file looks like?

**Comment by Tie-fighter** [comment]
So overnight the behaviour changed. Maybe some Browsercache or something timed out.
Now I see this error, which I believe is a duplicate

`2024/01/11 10:06:33 [error] 13580#13580: *258 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $projectRoot in /var/www/mautic/app/config/paths.php on line 15" while reading response header from upstream, client: 84.115.223.241, server: mautic.section8.eu, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "[redacted]"`

**Comment by escopecz** [comment]
We have a fix for that ready for testing. Would you mind testing it and giving your review on the pull request? I'll speed up the merge and a bug fix release:

https://github.com/mautic/mautic/pull/13193

**Comment by Tie-fighter** [comment]
> We have a fix for that ready for testing. Would you mind testing it and giving your review on the pull request? I'll speed up the merge and a bug fix release:
> 
> #13193

I would love to!

Is it just adding those three lines like in the PR?
I am test that in the next two hours.

**Comment by RCheesley** [comment]
The docs for testing are at https://mau.tc/tester :)

**Comment by Tie-fighter** [comment]
I have a stupid question.
I applied the patch in order to test it, and the error messages disappeared, but I am still seeing the http 500.
I did a console cache:clear and I restarted the VM jsut to make sure, but nothing changed.
Am I missing some cache?

I have used dev tools cache disabled and different browsers, so I think it is something on the serverside.

**Comment by escopecz** [comment]
Can you try removing the cache files from the filesystem instead of the symfony cache:clear command? Run this in the Mautic root directory:

`rm -rf var/cache/*`

**Comment by Tie-fighter** [comment]
> Can you try removing the cache files from the filesystem instead of the symfony cache:clear command? Run this in the Mautic root directory:
> 
> `rm -rf var/cache/*`

That did it. Seems to be working again. Please allow some time for testing.

**Comment by Tie-fighter** [comment]
Thank you for the timely and friendly support!
