### ISSUE TITLE
Filter "Regexp" in Segment

### ISSUE THREAD

**Issue by sonja1902** [mautic/mautic#13199]
### Mautic Version

4.4.x series

### PHP version

PHP Version 7.4.30

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

Hello!
I would like to share a problem with the segment filter "regexp".

You can use the filter regexp also for dropdown fields, but it does not work. Example: country. 

Do you have any idea what to do in this case? 

### How can we reproduce this issue?

Step 1: Open Segment
Step 2: Go to the Filter
Step 3: Using Country as a field
Step 4: Using Regexp
Step 5: Using regex, I should be able to add a list of values (instead of having to type them in one by one)
Step 6: not working with fields including drop down - but the "Regexp" is shown ??

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
@sonja1902 please double check, how does your regexp condition look like? It works fine for e.g. Germany|Austria|Switzerland with "regexp" and "not regexp". I tested in v5 though.

<img width="628" alt="image" src="https://github.com/mautic/mautic/assets/1241376/750d2d57-a0e2-49ef-8a5f-dccade1f25a7">


You know, that you could also use the including filter?
<img width="611" alt="image" src="https://github.com/mautic/mautic/assets/1241376/ddfff5f1-aea6-404f-85b8-3831f86f5c66">

**Comment by RCheesley** [comment]
Closing due to lack of feedback. Thanks @dsp76 for taking the time to respond!
