### ISSUE TITLE
Segments overview items 'view x contacts' link does not open the correct url to display filtered contacts, when opening in same page

### ISSUE THREAD

**Issue by LordRembo** [mautic/mautic#13200]
### Mautic Version

4.4.x series

### PHP version

8.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

Looking at the Segments overview, you can see the number of contacts in each Segment of the list.
When you click on it, it should display a contacts url with query params that filter the Contacts list (filtered on that segment's name) but it just loads `/s/contacts` instead.
The weird thing is, when you hover on that link, you can see it contains a target url that is correct + you can open that url if you choose to open the link in a new tab (right-click menu on the link).
It's only when straight-up clicking the link that it ignores the filter query params.

It DOES appear that the 'incorrect' url filter the contacts correctly, most of the time. While the url is always wrong when opened in same page, the loaded are inconsistent. So it's difficult to reproduce incorrect filtered lists. Maybe it is caching related?

### How can we reproduce this issue?

Step 1: Go to your Segments overview page
Step 2: Find an item with contacts
Step 3: find the 'View x contacts' link for it
Step 4: right-click that link and open its url in a new tab
Step 5: see that it's url is `/s/contacts?search=segment:<my chosen segment>`
Step 6: go back to your previous tab (the ones with the Segments overview)
Step 4: click the 'View x contacts' item and wait for the page to load
Step 5: see that you are on `/s/contacts` instead of the expected `/s/contacts?search=segment:<my chosen segment>`

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
@LordRembo are you still having this issue in 5.x? I'm not able to reproduce it with the 5.x branch right now.

**Comment by LordRembo** [comment]
@RCheesley indeed, on 5.x it seems to work (not on 5.1). So if we're not following up on M4 anymore I think it's okay to close.
