### ISSUE TITLE
Clone form gives error

### ISSUE THREAD

**Issue by gbela** [mautic/mautic#1320]
I Clone an existing form,rename click Apply and I get the following error.

Uh oh! I think I broke it. If I do it again, please report me to the system administrator!

**Comment by 432jhfbs** [comment]
I think this is a duplicate of:

https://github.com/mautic/mautic/pull/1278

**Comment by escopecz** [comment]
It's not exactly a duplicate. This is a bug request and #1278 is fix, but yes, we can close this issue I think. Any tests of that PR are very welcome.
