### ISSUE TITLE
Send Test mail  result to 500 error if mailer_convert_embed_images param is ON.

### ISSUE THREAD

**Issue by kossanah** [mautic/mautic#13202]
### Mautic Version

5.0.x series

### PHP version

8.1

### What browsers are you seeing the problem on?

Chrome

### What happened?

When sending Test mail, it results to a 500 server error, if the mailer_convert_embed_images param is ON.

### How can we reproduce this issue?

Step 1:  Confirm Email DSN is correctly configured.
Step 2.  Navigate to Channels --> Emails --> Open or create and email, then Click "Send Test Email"

### Relevant log output

```shell
`mautic.CRITICAL: Uncaught PHP Exception Error: "Object of class Mautic\EmailBundle\Mailer\Message\MauticMessage could not be converted to string" at /public_html/app/bundles/EmailBundle/Helper/MailHelper.php line 849 {"exception":"[object] (Error(code: 0): Object of class Mautic\\EmailBundle\\Mailer\\Message\\MauticMessage could not be converted to string at /public_html/app/bundles/EmailBundle/Helper/MailHelper.php:849)"} {"hostname":"myhost.site","pid":39961}`
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by mollux** [comment]
@kossanah I create a PR to address this issue, see https://github.com/mautic/mautic/pull/13219

are you able to test that PR and give feedback?
