### ISSUE TITLE
Problem upgrading from 4.4.10 to 5.0.1

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#13218]
### Mautic Version

5.0.x series

### PHP version

8.0.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I upgraded from 4.4.10 to 5.0.1 and I get this screenshot:
![mautic_screenshot](https://github.com/mautic/mautic/assets/33084245/0c1ac900-2778-43ff-8364-ca54d8c1b603)

I upgraded from the command line (CLI)...
It did everything without any notification.
It even gave me the final "Success! You are now running Version 5.0.1 of Mautic." message
but when surfing over to my Mautic address I still get that error. I tried clearing CACHE... chowning for www-data... chmoding 755 as usual... nothing helped.
What's missing here? Is there a dependency problem of some sort?

NOTE that I did not have any problems upgrading from 2 to 3 and from 3 to 4 with all the minor stable releases in between.
For some reason 4.4.10 to 5.0.1 is throwing this error and I don't know what to do.
I have restored to my backup for now.

### How can we reproduce this issue?

Step 1: Install 4.4.10
Step 2: Upgrade to 5.0.1 using command line (bin/console mautic:update:apply)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by mollux** [comment]
@omert37 can you check the php logs or mautic logs? Those should contain an error message that should clarify what's going on.

**Comment by kanapatrick** [comment]
after do that i have this error : PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Filesystem\Path" not found and my mautic no working again. how to solve

**Comment by kanapatrick** [comment]
PHP Fatal error:  Uncaught Error: Class "Symfony\Component\Filesystem\Path" not found in /var/www/html/automation.qtatech.com/docroot/app/bundles/CoreBundle/Loader/ParameterLoader.php:198
Stack trace:
#0 /var/www/html/automation.qtatech.com/docroot/app/bundles/CoreBundle/Loader/ParameterLoader.php(31): Mautic\CoreBundle\Loader\ParameterLoader::getLocalConfigBaseDir()
#1 /var/www/html/automation.qtatech.com/docroot/app/AppKernel.php(358): Mautic\CoreBundle\Loader\ParameterLoader->__construct()
#2 /var/www/html/automation.qtatech.com/docroot/app/AppKernel.php(228): AppKernel->getParameterLoader()
#3 /var/www/html/automation.qtatech.com/vendor/symfony/framework-bundle/Console/Application.php(169): AppKernel->boot()
#4 /var/www/html/automation.qtatech.com/vendor/symfony/framework-bundle/Console/Application.php(75): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#5 /var/www/html/automation.qtatech.com/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#6 /var/www/html/automation.qtatech.com/bin/console(42): Symfony\Component\Console\Application->run()
#7 {main}
  thrown in /var/www/html/automation.qtatech.com/docroot/app/bundles/CoreBundle/Loader/ParameterLoader.php on line 198

**Comment by escopecz** [comment]
What command did you use to upgrade? Was that command successful? It looks like only part of the files were updated.

**Comment by kanapatrick** [comment]
php bin/console mautic:update:apply  with php 8.0

**Comment by escopecz** [comment]
> Was that command successful?

**Comment by putzwasser** [comment]
1. I suspect you installed Mautic4 using composer
2. If I'm right you'd need to use composer to update
3. See https://forum.mautic.org/t/4-4-10-5-0-1-fails-because-symfony-path-is-not-fount-in-parameterloader-php/30475/1 for the solution. (Amend composer json, run composer update/require)
