### ISSUE TITLE
Latest Docker version point to version V4 instead of V5

### ISSUE THREAD

**Issue by mariushosting** [mautic/mautic#13213]
### Mautic Version

5.0.x series

### PHP version

8.1

### What browsers are you seeing the problem on?

Chrome

### What happened?

:latest tag Docker install version V4 instead of V5 version.

### How can we reproduce this issue?

download :latest get V4 instead of V5

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by mollux** [comment]
@mariushosting we are working on the v5 images, you can follow the progress in https://github.com/mautic/docker-mautic/pull/238.
We are almost ready to release the images, as multiple people confirmed them working.
If all goes well, in the upcoming days we should get everything in place

**Comment by mariushosting** [comment]
> @mariushosting we are working on the v5 images, you can follow the progress in [mautic/docker-mautic#238](https://github.com/mautic/docker-mautic/pull/238). We are almost ready to release the images, as multiple people confirmed them working. If all goes well, in the upcoming days we should get everything in place

Thank you @mollux

**Comment by mariushosting** [comment]
@mollux is V5 docker image released? I haven't seen any update on this,

Thank you!
