### ISSUE TITLE
    - Root composer.json requires mtalkz-mobility/mautic-mtalkz-bundle, it could not be found in any version, there may be a typo in the package name.

### ISSUE THREAD

**Issue by kanapatrick** [mautic/mautic#13227]
### Mautic Version

5.0.x series

### PHP version

8.0

### What happened?

A bug happened!

### How can we reproduce this issue?

Step 1: 

### Relevant log output

```shell
- Root composer.json requires mtalkz-mobility/mautic-mtalkz-bundle, it could not be found in any version, there may be a typo in the package name.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
