### ISSUE TITLE
Unsubscribe not populating lead list

### ISSUE THREAD

**Issue by 750430** [mautic/mautic#1322]
I have noticed an issue when using the Unsubscribe function, we use the one-click method with a link at the bottom of each email. We also have a Smart List set up so any lead who's account has the 'unsubscribed' flag set, gets inserted into this smart list.

I spoke with someone on Slack and their comments were as follows "I have been messing with the one click unsubscribe.. and the same issue happens to me, for one reason or another the unsubscribed value is remaining 0 when it should be changed to 1,and the bounced value is changing, in essence unsubscribes are coming in as bounces, however  you will notice that in the comments of the table it says: User unsubscribed. I think in the 1.2.3 push a column was off by one!"

Closing the discussion with "but that is why your list will not update"

I haven't yet looked at our db to see if anything is changing in there, however, mine and 'jeph's symptoms are similar.

edit: issue #1310 was an issue i raised and has been very helpful in bringing Mautic to a usable state for us, but sadly, doesn't resolve this issue.

**Comment by escopecz** [comment]
Interesting way to describe an issue. TBH, I don't know what that means. Could you write the steps to recreate it? Also, check if https://github.com/mautic/mautic/pull/1310 isn't a fix for your issue.

**Comment by 750430** [comment]
Apologies - will edit

**Comment by 750430** [comment]
Confirmed now functioning (coupled with retrospective change to the db to reflect correct settings)
