### ISSUE TITLE
Symfony mailer not working as expected

### ISSUE THREAD

**Issue by alvaroenoht** [mautic/mautic#13222]
### Mautic Version

5.0.x series

### PHP version

8.1

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I installed mautic via composer, added the sendgrid mailer and amazon mailer via composer as well, but the configuration is not taking the scheme name as shown in the documentation. I have tried ses+api, ses+smtp,sendgrid and sendgrid+api and none work, just says they are not supported.  I changed the config manually in config/local.php and it takes the scheme name, but wont send the email.

### How can we reproduce this issue?

Step 1: New fresh install, add symfony amazon mailer or sendgrid mailer. 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by mollux** [comment]
Hi @alvaroenoht did you clear the container cache? as without doing so won't make Symfony aware of the new mailers.

You can do this by running `./bin/console cache:clear` or if that doesn't work, try `rm -rf var/cache`

If that works, can you link the documentation you followed (most likely https://docs.mautic.org/en/5.x/channels/emails.html#email-delivery) , so we can explain the extra step needed

**Comment by alvaroenoht** [comment]
> Hi @alvaroenoht did you clear the container cache? as without doing so won't make Symfony aware of the new mailers.
> 
> You can do this by running `./bin/console cache:clear` or if that doesn't work, try `rm -rf var/cache`
> 
> If that works, can you link the documentation you followed (most likely https://docs.mautic.org/en/5.x/channels/emails.html#email-delivery) , so we can explain the extra step needed

I did the cache:clear as you said, but nothing. however I did clear manually the /var/cache and the var/cache and that did the trick!. thanks.. also SES region has to be specified.

**Comment by alexrm1x** [comment]
Have in mind that WHERE you run the "composer" command from is EXTREMELY important and can ruin your installation.

You must position on the root path folder or directory where the install is, meaning that if you use the "mautic" user on Debian 12 as example....:

/home/mautic/public_html
(mautic install dir)
/home/mautic/public_html/docroot
(mautic public pages, this is where you point the apache DocumentRoot both in the apache config file:
DocumentRoot /home/mautic/public_html/docroot
and
<Directory /home/mautic/public_html/docroot>).

In case you ran the command in the wrong directory, you can clean the worng install and try the new one:

cd /wrongdirectory
composer remove symfony/sendgrid-mailer

then go to the right one:
cd /home/mautic/public_html
and run 
composer require symfony/sendgrid-mailer

that will allow you to put "sendgrid+api" and the KEY as the official documentation.
