### ISSUE TITLE
Muatic 5.0.2 on Windows environment

### ISSUE THREAD

**Issue by jameswill** [mautic/mautic#13238]
### Mautic Version

5.0.x series

### PHP version

8.0.x

### What browsers are you seeing the problem on?

Firefox

### What happened?

I am trying to install Mautic 5.0.2 on my windows environment where I have installed Apache 2.4, Mysql 8.0 and PHP 8.0

I am installing in a subdirectory hence I have added subdirectory path .htaccess line 133 On starting installation page I am getting the following error.

**The connection was reset

The connection to the server was reset while the page was loading.**

Does Mautic support windows environment ?

### How can we reproduce this issue?

- Download and extract mautic and upload in desired subdirectory.
- added the subdirectory path on line133 on .htaccess
- Trying to access the installation on web.

### Relevant log output

```shell
Didn't find any relavant logs.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
