### ISSUE TITLE
I can't filter leads by email using the REST API

### ISSUE THREAD

**Issue by ptcc** [mautic/mautic#1323]
I'm using the rest API and I'm able to filter stuff like this: GET /leads?search=my.name
but if I add an @ then i allways get signature_invalid. 

I tried with some oauth libraries as well as PAW app.
I also tried with mautic API tester and *it does work* if the parameter goes on the parameters but not if it goes in the query... 

The thing is that the "standard" method that i see oauth1 being used passes parameters in the query.
Is it possible to make it work that way? I think it might help the creation of more API libraries for languages other than PHP...

**Comment by escopecz** [comment]
Try to URL encode the email address. Replace `@` with `%40`.

**Comment by ptcc** [comment]
Also tried that :( its the same

On Mon, Jan 11, 2016 at 10:25 AM, John Linhart <notifications@github.com>
wrote:

> Try to URL encode the email address. Replace @ with %40.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/1323#issuecomment-170500801>.
>



-- 
_________________________________
Tiago Coelho

**Comment by escopecz** [comment]
Tested it with the [API tester](https://github.com/mautic/api-library) and it works for me:
![mautic-search-lead-by-email](https://cloud.githubusercontent.com/assets/1235442/12233700/43cf1b1e-b869-11e5-9d1e-2ec7f578c0af.png)

**Comment by ptcc** [comment]
As I had written before:
"I also tried with mautic API tester and it does work if the parameter goes on the parameters but not if it goes in the query..."

**Comment by escopecz** [comment]
I don't think the parameters in the api tester and parameters in the URL query are somehow different. They are the same. The API tester just puts them into the URL query and makes the CURL. What is the URL query you are trying to make it work?

**Comment by ptcc** [comment]
?search=email:someone@somecompany.com
or encoded... ?search=email%3Asomeone%40somecompany.com
or just ?search=somename
all of these get "invalid signature" (but it works fine when i put the parameters like you did on the screenshot)

**Comment by escopecz** [comment]
What the full API GET request look like? Do you use OAuth1a or OAuth2?

**Comment by ptcc** [comment]
![captura de ecra 2016-01-18 as 15 58 07](https://cloud.githubusercontent.com/assets/482937/12395918/5cfe80dc-bdfc-11e5-9656-9a66926ab908.png)
![captura de ecra 2016-01-18 as 15 57 40](https://cloud.githubusercontent.com/assets/482937/12395919/5d01f7da-bdfc-11e5-9937-b3a54afbf0ab.png)

**Comment by escopecz** [comment]
Well, yes, but that doesn't prove that it doesn't work in a real-life example. The API Tester has to add the OAuth token somewhere in the URL. In that case there would be two question marks in the URL which causes the error. So apart form the URL query added in the API Tester to the place were it shouldn't be, do you have a problem with it in your app?

**Comment by ptcc** [comment]
yes... I get the same behavior when i use it with PAW, restangular, nodejs node-oauth...

**Comment by escopecz** [comment]
Ok. So what is the URL you are using in your app for this API request?

**Comment by ptcc** [comment]
i'm making the request server side... I have no public URL that i can show, but i can share my code (its node.js)

var consumer_key='...',
    consumer_secret='...',
    token='...',
    token_secret='...',
    url='http://crm.prokubo.com/api/leads';

var unirest = require('unirest');

 Request = unirest.get(url);
    Request.oauth({
      consumer_key: consumer_key,
      consumer_secret: consumer_secret,
      token: token,
      token_secret: token_secret
    }).query({
      //search: 'pedro.tiago', //this works!
      //search: 'email:pedro.tiago', //this does not work :(
      search: 'email%3Apedro.tiago', //this does not work either, i get 401 signature_invalid
      limit:'1'
    }).end(function (response) {
      
      console.log(response.body);
    });

**Comment by escopecz** [comment]
That's what I wanted to see. Can you try to search the real email address there? `email:pedro.tiago` is not a valid email address.

**Comment by ptcc** [comment]
just tried it
    search: 'pedro.tiag0@gmail.com',
the output is the same 
    >node mautic2.js
    { error: { message: 'signature_invalid', code: 401 } }

**Comment by cedel1** [comment]
It seems to me that it's not just a problem of filtering. Tried to access the API from python3 using requests-oauthlib library using OAuth1 and when I try to send a character that should be urlencoded (like @ or :), I get 401 - invalid signature. When I replace  @ with _ , the request works.

Filtering aside, the huge problem that I encounter is that I can't create a new lead using OAuth1 with a proper email address... Have tried the above replacement (_ instead of @) and voila - lead created no problem. Also tried the parameters - to no avail.

So I'd hazard a guess it's not a problem of my settings, but rather a problem of the request signature (since after replacing the offending chars everything works).

**Comment by cedel1** [comment]
@escopecz 

Have been digging into this a bit deeper...

> I don't think the parameters in the api tester and parameters in the URL query are somehow different. They are the same. The API tester just puts them into the URL query and makes the CURL.

I don't think that's actually true (at least in case of OAuth1):
1. The parameters fields are posted from the apitester separately - and are passed to api-library also separately. See mautic/api-library/apitester/index.php line 188:
`$response = $oauthObject->makeRequest($url, $postParams, $method, $settings);` and the makeRequest method in mautic/api-library/lib/Auth/OAuth.php starting at l.668. l.695-699.
2. There is no mechanism in neither apitester nor the library itself to separate parameters from "$url" above, so they end up urlencoded as part of the base URL, are not ordered, separated by "&" when building the signature base string and the whole signature is off...

Have a look at commit https://github.com/cedel1/api-library/commit/65f1ede5eb9cd1ef5b67be516d4c70e14d201717 . That should solve the problem for apitester by separating the parameters form the query/endpoint, but does not solve the problem when not using the php api-library  - accessing the API using some other language/library.

**Comment by cedel1** [comment]
@escopecz 
Or maybe just modify the library, instead of modifying the apitester... https://github.com/cedel1/api-library/commit/5f92a24fb9247528607fb1f692d90d36e608894b (slightly tested, but definitely not under all circumstances).

**Comment by cedel1** [comment]
OK, I think I found the problem - the signature at OAuthV1 base string construction in BazingaOAuthServerBundle, So I filed a question with proposed solution (and code to solve it) at https://github.com/willdurand/BazingaOAuthServerBundle/issues/31 .

If I'm correct about the issue, we'll have to wait if/until if gets fixed or override the functions in Mautic.

If the assumptions above are correct, https://github.com/mautic/api-library has the same problem of not encoding the request parameter keys and values and will have to be fixed as well.

The proposed api-library fix is at https://github.com/cedel1/api-library/commit/8ca9bb58269f96366e30193ead095d63ebfffab7 . Applying that will emulate the behavior I have been experiencing python3-oauthlib and maybe the same @ptcc experienced with other libs.

**Comment by alanhartless** [comment]
I agree - definitely a bug upstream. We are weighing our options to determine what we need to do. I'm not sure he's developing that library anymore so we may have to fork it. (I accidentally posted this in the issue with Will, whoops :-) )

**Comment by alanhartless** [comment]
The oauth1a bundle has been fixed with #2330. @cedel1, would you mind PRing https://github.com/cedel1/api-library/commit/35afe061d9cb872a0cba7aab60af428e66ee6870  and https://github.com/cedel1/api-library/commit/8ca9bb58269f96366e30193ead095d63ebfffab7 against our repository so we can fix it on our side.

**Comment by dongilbert** [comment]
Fixed with #2330

**Comment by cedel1** [comment]
Ouch, sorry for my late answer, I can see the changes have been merged with https://github.com/mautic/api-library/pull/54 and the problem solved. Thanks, @alanhartless .
