### ISSUE TITLE
Error 500 in editing campaing

### ISSUE THREAD

**Issue by imgirotto** [mautic/mautic#1326]
When I try to change some items in my campaign I'm constantly getting a 500 error or the changes are not saved. The funny thing is that new items appear, but the old ones did not change. What might be happening?

**Comment by escopecz** [comment]
There is a bug in the campaign event modification. The fix is here in https://github.com/mautic/mautic/pull/1284 . For the detailed error message, check the logs. There is a *System Info* menu item in the right menu where you can see the errors or check the app/logs folder

**Comment by imgirotto** [comment]
Thank you very much! I'll try apply this fix. :)
