### ISSUE TITLE
Modifying or filtering columns in the leads table

### ISSUE THREAD

**Issue by CedricH-BZH** [mautic/mautic#1327]
Could it be possible to filter, choose, re-arrange columns in the "prospect" tab in order to display datas adapted to each needs.

For example, I've added a "status" field in customized prospect fields. Therefore, I'd like to be able to visualise that status directly whatever filter is used.

It would be a great move toward some pre-CRM.

**Comment by nonumber** [comment]
Also the ability to have the List(s) as a column in the Leads table view...

**Comment by escopecz** [comment]
This seems to be similar to https://github.com/mautic/mautic/issues/120
