### ISSUE TITLE
Campaign actions and triggers suggestions

### ISSUE THREAD

**Issue by CedricH-BZH** [mautic/mautic#1328]
I'm playing more and more with campaigns and feel a lot of small "limits"

[x] duplicating - cloning conditions, triggers, events and actions would be great instead of having to recreate for the fifth time the same "trigger" --- treated in  #452
[ ] creating bridges from different "triggers" to the same "result" ie sending a welcome mail to all people who have done another action, whatever that action was. If I have to re-ask an action, even at the 5th time, I may want to send the same mail in the end.
[x] creating triggers on specific urls in a mail. ie I'd love to be able to know who goes to which appstore to add tags to my prospects. And I don't think I'll be able to place a Mautic tracking pixel on Google or Apple stores ... just want to track specific clicks as I have to include all appstores in my mails --- treated in #1126 (would prefer the last proposal through js and json).

**Comment by MiracleMakert** [comment]
I completely agree that first two will benefit a lot the Campaign Builder. 

The third one you can do even now. Add "Decisions" - Visits a page with condition  URL. Go to the "?" and there you can see explanation what you have to do to capture it.

I have created an example how this look like:
<img width="479" alt="screen shot 2016-01-10 at 8 02 40 pm" src="https://cloud.githubusercontent.com/assets/16620970/12223053/57f797e0-b7d5-11e5-96ba-89729be5bfd9.png">

**Comment by CedricH-BZH** [comment]
For third point, you can effectively doing it on your own domain, but not as specified in the example on a tier site.

**Comment by escopecz** [comment]
Those are great suggestions! I'd suggest to separate them into separate issues, because if some community developer sees this, he'll probably back up because it will be too big to handle in one evening. But if you separate them, there is a bigger chance someone develops them. Also, some of them were already reported. For example https://github.com/mautic/mautic/issues/1126

**Comment by escopecz** [comment]
Here is another feature request which is duplicated here: https://github.com/mautic/mautic/issues/452. So that leaves us with only this one:

> creating bridges from different "triggers" to the same "result" ie sending a welcome mail to all people who have done another action, whatever that action was. If I have to re-ask an action, even at the 5th time, I may want to send the same mail in the end.

But I'm not sure I understand what you mean.

**Comment by CedricH-BZH** [comment]
I agree on both tickets references.

On the last one, I've seen yesterday a hint you (John) gave to someone else for a similar problem and your answer was to send to "regroup" to another campaign. I see it as an alternative solution that would work. Therefore creating bunches of campaigns to treat each slice of each decision tree can be painful too (and cumbersome).

Finally that feature request ends in creating complex campaign trees ... eventually with an easy selection of "scripts" or scenariis to place on the way.

**Comment by escopecz** [comment]
As @CedricH-BZH pointed out, there is duplicate feature request (https://github.com/mautic/mautic/issues/1414) for the last unresolved point. We usually close the younger duplicate issues, but in this case, I'll close this one since the younger one has better explanation of the issue.
