### ISSUE TITLE
User Timezone Preference Setting Not Working

### ISSUE THREAD

**Issue by patrykgruszka** [mautic/mautic#13315]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

User preferences regarding timezone settings are not functioning properly. Changing the settings does not result in updating the displayed time on contact view.

### How can we reproduce this issue?

Step 1: Create a contact and note the displayed time on the contact card.
![image](https://github.com/mautic/mautic/assets/8580942/d87814ef-5082-44a3-b8ca-1b7d2e98508e)
Step 2: Change the timezone setting in the account settings (/s/account).
![image](https://github.com/mautic/mautic/assets/8580942/1761d7c2-a2d1-4dd8-a711-f9c56f9759f9)
Step 3: Check if the time has been updated on the contact card.
![image](https://github.com/mautic/mautic/assets/8580942/0d1a5bd8-dce0-4a1c-a1a6-c9d04c81bc3d)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi @patrykgruszka is this still an issue? Did the cache get cleared etc?

**Comment by RCheesley** [comment]
Closing due to lack of feedback, feel free to request a re-open.
