### ISSUE TITLE
Incorrect Event Timestamps in Contact Timeline After Changing Default Timezone

### ISSUE THREAD

**Issue by patrykgruszka** [mautic/mautic#13331]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Under certain circumstances, incorrect dates are displayed for past events that occurred a day prior after altering the Default Timezone within System Settings in Mautic.

### How can we reproduce this issue?

Step 1: Add a new contact
Step 2: Send an email to contact
Step 3: Wait until the next morning (note: issue occurrence may vary throughout the day).
Step 4: Change the Default Timezone within Mautic's System Settings, for example, to America/Los Angeles.
Step 5: Review the contact timeline for inconsistencies.
![image](https://github.com/mautic/mautic/assets/8580942/2bf167b0-0754-4505-ac89-0f5025c13d32)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by magdalenaleonow** [comment]
Hi @patrykgruszka, I tested the solution, everything works!
![image](https://github.com/mautic/mautic/assets/130159751/7c705c04-e179-4550-86d9-5906373ae0e2)

**Comment by patrykgruszka** [comment]
@magdalenaleonow thanks for the confirmation!
