### ISSUE TITLE
Webhoooks test payload is ok. But on event, no data is passed. 

### ISSUE THREAD

**Issue by ScottAMains** [mautic/mautic#13349]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I'm getting some integrations put together to perform actions on events. 
At the moment I'm working on the basics "contact identified".

When clicking send test payload the relevant information is being passed over. 
![Screenshot 2024-02-08 at 19 13 22](https://github.com/mautic/mautic/assets/58055660/a0758abf-bfa7-4b32-a369-8a3e239c8fae)

But when creating a new contact. Nothing is being passed over. 
![Screenshot 2024-02-08 at 19 14 39](https://github.com/mautic/mautic/assets/58055660/52c2826d-0034-4222-9643-97d6b80ed0f0)
![Screenshot 2024-02-08 at 19 14 57](https://github.com/mautic/mautic/assets/58055660/21fd81d4-8cab-4c43-a2c8-2406c1077e01)

![Screenshot 2024-02-08 at 19 15 53](https://github.com/mautic/mautic/assets/58055660/3bad5f44-5c20-483b-80ee-eb713a1fe984)
![Screenshot 2024-02-08 at 19 16 17](https://github.com/mautic/mautic/assets/58055660/9c6baf74-b196-4e20-bfb7-6676ab00ee21)

### How can we reproduce this issue?

Step 1: sending data via webhooks

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi @ScottAMains sorry for the delay in getting back to you - did you resolve this or get support on https://forum.mautic.org in the meantime?

**Comment by RCheesley** [comment]
Closing due to lack of feedback (and it should be posted at https://forum.mautic.org rather than here).
