### ISSUE TITLE
`PageBundle\Form\Type\ConfigType` shows escaped HTML

### ISSUE THREAD

**Issue by putzwasser** [mautic/mautic#13355]
### Mautic Version

5.0.x series

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.1

### What happened?

`PageBundle\Form\Type\ConfigType` let's you add custom tracking JS to Mautic.
You add your custom HTML and Mautic will add it to your landing pages.

Generally, this works well, but after saving this form type shows escaped HTML.

It's an UI/UX bug, because it works as expected (except if you save this again).

**Before saving**
![before saving](https://github.com/mautic/mautic/assets/26040044/677b0253-2cee-4928-9436-df900fac56ea)

**After saving**
![after saving](https://github.com/mautic/mautic/assets/26040044/7610755e-db5d-40c0-8db1-b41c4e96018c)

I guess, this file is responsible: https://github.com/mautic/mautic/blob/5.x/app/bundles/PageBundle/Resources/views/FormTheme/Config/_config_pageconfig_widget.html.twig#L10

Instead of `                    {{ form_row(f) }}` the `google_analytics` type needs to get rendered raw somehow.

### How can we reproduce this issue?

1. Add custom HTML in `Configuration > Landing Page Settings > Analytics script (i.e. Google Analytics) `
2. Save
3. Open this view again → see escaped HTML
4. (Open any landing page, see that the tracking HTML is added as expected)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for the PR to address this @putzwasser - hoping we can get that merged soon with one more test!
