### ISSUE TITLE
Campaign not executing correctly

### ISSUE THREAD

**Issue by MiracleMakert** [mautic/mautic#1338]
Hi guys, 

I am the only one that has issues with the Campaigns? For example. I have a campaign with form. Form is filled and records are stored in person's profile in Mautic. Next step is to send an e-mail. Done. Then none of the "intelligence's" work. No points are given for open e-mail, No points are given for downloaded asset, No tags are added, No list changes, No url open detected. And this is to a batch of 5000 e-mails with detected open e-mails of 1570.

I believe i may have some logic that is different from the one implemented. For example the green and the red points. I noticed on one of my tests, that it executed the red straight away and subtract some points but then i thought it may need to have some delay, as when the campaign to this step - check if it is open straight away and usually it is not, because it is just sent, so may be i have to put a delay? And i have to include hooked on the "Send e-mail"? Or it can be hooked to the main thing, or i have to set some delay?

It will be priceless to see the logic of all elements in the moments, because it looks like a nightmare for me, as if most of the things in the campaign are not executed as i expect. As i said hopefully this is because i expect it to work differently. Can someone explain the main logic behind conditions and checking things on the e-mail. To check if it is open should i hook it to the "send e-mail" node or on the main campaign "node", Should i set definitely a time delay or it has in itself a set time to check for a specific period of time. When i check for opened links - as well. What is the logic. When i check for downloaded assets - i see in the profile's timeline that the person downloaded an asset, but nothing triggers.

I really appreciate your help on getting me to understand it.
Thanks,
N

**Comment by MiracleMakert** [comment]
Here is the example of my campaign with tags /*executed ok*/ and /*not executed*/. Please help me to understand why it is not puling the right things, as it should.

Thanks
![issue](https://cloud.githubusercontent.com/assets/16620970/12216633/3dd91184-b6f1-11e5-9ffe-a2e50986dc1c.jpg)

**Comment by escopecz** [comment]
Just to make sure, the cron jobs are configured correctly?

https://www.mautic.org/getting-started/

**Comment by MiracleMakert** [comment]
I think i did it correct. This is on my Cron:

*/2	*	*	*	*	/usr/local/php5.3/bin/php/ .../app/console mautic:leadlists:update -f	
*/2	*	*	*	*	/usr/local/php5.3/bin/php .../app/console mautic:campaigns:update -f
*/2	*	*	*	*	/usr/local/php5.3/bin/php .../app/console mautic:campaigns:trigger -f
5	*	*	*	*	/usr/local/php5.3/bin/php .../app/console mautic:email:process

Is that correct?

**Comment by escopecz** [comment]
Hard to say. I don't have access to your server. Your hosting provider could tell you more. But each cron should have a log. Try to look at it.
