### ISSUE TITLE
Support multiple languages in form

### ISSUE THREAD

**Issue by TiagoGouvea** [mautic/mautic#1339]
When the user create a form, copy and paste the html code, they don't fell confortable to change the HTML to fix "mauticform-errormsg" and "submit" values. 
Form could have the same as landing page, where the user select the language for it. It can be a great addition to internationalization.
Thanks

**Comment by escopecz** [comment]
Just to confirm I understand correctly, do you want some way to tell Mautic through an embedded form what language the error messages should be?

**Comment by TiagoGouvea** [comment]
Yes. Change HTML are so technical thing... if the user can choose the language, we can better integrate the forms with wordpress plugins.

**Comment by TiagoGouvea** [comment]
Checking now.. I saw that the user can customize the required message and the "submit" text on that button. There's no need to choose a language to use it. It's all configurable.
You can close that issue if you want.

**Comment by michiellucas** [comment]
Is there a way to translate the error messages like  "This is required"?
Is it possible to add the language tot the MauticSDK.onLoad(); 

How do you translate the mautic errors in the embedded forms?
