### ISSUE TITLE
Archiving sent mails

### ISSUE THREAD

**Issue by CedricH-BZH** [mautic/mautic#1341]
Currently we can "modify - clone - delete - send" mails.

It would be useful to be able to archive them to re-activate and clone later for example.

Moreover because once deleted, we loose statistics attached to it.

The best example is the "best wishes" mail that is only useful once a year ... and that I don't want to stay in my focus line the full year.

**Comment by zenzozen** [comment]
+1

**Comment by escopecz** [comment]
Closing this feature request in favour of https://github.com/mautic/mautic/issues/371
