### ISSUE TITLE
[UX] Redundant “New” button in Companies Merge modal

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13416]
The “New” button in the Companies Merge modal currently leads to additional menu options that show without content. 
How to reproduce the bug:
1. Open Companies
2. Click to create a new
3. Fill any information
4. Click to merge
5. The wrong modal is displayed

![Image](https://github.com/mautic/mautic/assets/116097999/2bd88d79-fb32-4c72-bf3f-c0d00ebc979e)

### Impact
It would eliminate unnecessary confusion caused by empty menu options and streamline the process of merging companies. It not only disrupts the workflow but also gives an impression of incomplete or faulty features.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by abansal15** [comment]
Hello @andersonjeccel could you please assign this issue to me i will remove the confusion of the empty menu options by removing it quickly.

**Comment by andersonjeccel** [comment]
@abansal15 Done!
Remember that this issue happen only when the company is not saved yet. For already existing companies, when you edit, it works as expected.

**Comment by PiyushThapaa** [comment]
@andersonjeccel  I want to work on this issue but struggling to find the source code... do you have any suggestions?

**Comment by andersonjeccel** [comment]
@PiyushThapaa It's probably close to this path:

\app\bundles\LeadBundle\


Maybe this? Have to look
\app\bundles\LeadBundle\Controller\CompanyController.php

**Comment by PiyushThapaa** [comment]
@andersonjeccel can you explain me what kind of change you want
Removing the header that contain new button and dropdown??
Whole modal should be like edit's merge modal?

I have been trying for 4 days to solve this issue but because being new to php I am not able to understand how can this issue be solved

**Comment by andersonjeccel** [comment]
@LordRembo Could you help us a bit here?

**Comment by LordRembo** [comment]
I'm gonna let Tim tackle this one.

**Comment by mallezie** [comment]
I did not find it either. My plan was actually to remove the 'Merge' button on the new company overview. This is not needed there IMO, and also solves the issue. 

AFAICT the buttons are added through JS, but no idea where they get passed to the page.

**Comment by andersonjeccel** [comment]
@escopecz Do you know something about this issue? We need some guidance to fix

**Comment by nishant-s7** [comment]
Hi there! I would like to work on this bug, but I'm unclear about the expected result. Should we remove the **Merge** button until the company is not saved?

**Comment by andersonjeccel** [comment]
@nishant-s7 I think the best approach would be what Tim said: when creating a new company, the Merge button must be hidden

thanks for catching this issue!

**Comment by andersonjeccel** [comment]
@all-contributors please add @andersonjeccel for bug
