### ISSUE TITLE
In focus item details statistics don't load (views and unique views)

### ISSUE THREAD

**Issue by magdalenaleonow** [mautic/mautic#13412]
### Mautic Version

5.0.x series

### Way of installing

Other (please specify if relevant in the bug report)

### PHP version

8.2.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The spinner for focus item statistics (Views and Unique views) doesn't stop loading and the statistics never show up
![image](https://github.com/mautic/mautic/assets/130159751/d6f12af5-e839-42a3-8987-884dfe0bc516)

### How can we reproduce this issue?

1: Open any focus item and expand "details"
2: Views and Unique views don't load 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi folks, looks like this was fixed by #13561 so I'm closing this issue :)
