### ISSUE TITLE
Export and send email report is not working for reports

### ISSUE THREAD

**Issue by Galokh66** [mautic/mautic#13424]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Chrome

### What happened?

There is an issue where, scheduling an email to export the report to a given mail id is not working.
Expected behaviour: When a user schedules an email to now/every day/week/month to export a specific report, it should be sent via email to the given email id. When a user clicks on export and send report, the email should be sent via email to the given mail id.

### How can we reproduce this issue?

Step 1: Create a report
Step 2: Edit the report and go to '**Schedule**'
Step 3: Toggle '**Yes**' to Email report.
Step 4: Add email id on which you want to receive the report
Step 5: Select the email schedule time to now.
Step 6: Save and close the report
Step 7: Close the report and search for the created report
Step 8: Click on the arrow dropdown on the left side of report label
Step 9: Select '**Export and Send**' option.
Step 10: UI shows notification that the report is already scheduled, but it does not trigger any email.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by escopecz** [comment]
@Galokh66 The reports are generated by a background command. Try to execute `bin/console mautic:reports:scheduler` to see if the report arrives.

**Comment by Galokh66** [comment]
@escopecz I triggered the command but it does not trigger the emails.
Getting this response:

In RequestStack.php line 126:
                                            
  There is currently no session available.  
 
mautic:reports:scheduler [-report|--report [REPORT]]

**Comment by escopecz** [comment]
I can reproduce:
```
www-data@019482e3f501:~/html$ bin/console mautic:reports:scheduler
10:27:05 ERROR     [mautic] Symfony\Component\HttpFoundation\Exception\SessionNotFoundException: There is currently no session available. (uncaught exception) at /var/www/html/vendor/symfony/http-foundation/RequestStack.php line 126 while running console command `mautic:reports:scheduler`
[stack trace]
#0 /var/www/html/app/bundles/ReportBundle/Model/ReportModel.php(96): Symfony\Component\HttpFoundation\RequestStack->getSession()
#1 /var/www/html/app/bundles/ReportBundle/Model/ReportModel.php(496): Mautic\ReportBundle\Model\ReportModel->getSession()
#2 /var/www/html/app/bundles/ReportBundle/Adapter/ReportDataAdapter.php(27): Mautic\ReportBundle\Model\ReportModel->getReportData(Object(Mautic\ReportBundle\Entity\Report), NULL, Array)
#3 /var/www/html/app/bundles/ReportBundle/Model/ReportExporter.php(70): Mautic\ReportBundle\Adapter\ReportDataAdapter->getReportData(Object(Mautic\ReportBundle\Entity\Report), Object(Mautic\ReportBundle\Model\ReportExportOptions))
#4 /var/www/html/app/bundles/ReportBundle/Model/ReportExporter.php(32): Mautic\ReportBundle\Model\ReportExporter->processReport(Object(Mautic\ReportBundle\Entity\Scheduler))
#5 /var/www/html/app/bundles/ReportBundle/Scheduler/Command/ExportSchedulerCommand.php(43): Mautic\ReportBundle\Model\ReportExporter->processExport(Object(Mautic\ReportBundle\Scheduler\Option\ExportOption))
#6 /var/www/html/vendor/symfony/console/Command/Command.php(298): Mautic\ReportBundle\Scheduler\Command\ExportSchedulerCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Mautic\ReportBundle\Scheduler\Command\ExportSchedulerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Mautic\ReportBundle\Scheduler\Command\ExportSchedulerCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/bin/console(16): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main} ["hostname" => "019482e3f501","pid" => 7030]
10:27:05 CRITICAL  [console] Error thrown while running command "mautic:reports:scheduler". Message: "There is currently no session available." ["exception" => Symfony\Component\HttpFoundation\Exception\SessionNotFoundException^ { …},"command" => "mautic:reports:scheduler","message" => "There is currently no session available."] ["hostname" => "019482e3f501","pid" => 7030]
10:27:05 WARNING   [mautic] Command `mautic:reports:scheduler` exited with status code 1 ["hostname" => "019482e3f501","pid" => 7030]

In RequestStack.php line 126:
                                            
  There is currently no session available. 
```

**Comment by escopecz** [comment]
I wanted to fix it and push it to https://github.com/mautic/mautic/pull/13405 but I accidentally pushed it to the 5.x branch in https://github.com/mautic/mautic/commit/ffe71dd1f109fdf44bbb7384ba519207af078ff1. Let's roll with it. I merged it back to https://github.com/mautic/mautic/pull/13405. Please test it now.

**Comment by Galokh66** [comment]
Okay, I will test it and let you know

**Comment by Galokh66** [comment]
having some issues with it

**Comment by Galokh66** [comment]
Export and send is working now @escopecz
