### ISSUE TITLE
Implementing "real" mail template builder

### ISSUE THREAD

**Issue by CedricH-BZH** [mautic/mautic#1342]
I know templating and creating templates editors is a pain ... therefore, it's a large part in the success of MailChimp or more direct drip marketing competitors.

Could it be possible to integrate a more solid template editor based on blocks and snippets like those you find on CMS plugins ?

You can also find great ressources in opensource projects to integrate a 3rd party builder like : 
http://mosaico.io/

Working with current templates without a good level of css / html is just not an option for many of us.

**Comment by dbhurley** [comment]
This is a great resource. We'll take a closer look at it to see if this would be something easy to integrate. Looks like some style work needs to be done but it's certainly an option. Will depend on the dependencies necessary to make it work easily in a self-hosted environment.

**Comment by that0n3guy** [comment]
+1.  I could care less about this, but other guys in the office seem to think HTML is scary :).

**Comment by that0n3guy** [comment]
Might be good for landing page builder as well...

**Comment by andrefilo** [comment]
This would be an amazing feature that could really make the difference!

**Comment by alanhartless** [comment]
Email templating was rebuilt in 2.0.

**Comment by escopecz** [comment]
Linking this PR just for the reference: https://github.com/mautic/mautic/pull/3387
