### ISSUE TITLE
Contacts API "Select - Multiple" field - set empty value

### ISSUE THREAD

**Issue by rguedes** [mautic/mautic#13425]
### Mautic Version

4.4.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1

### What browsers are you seeing the problem on?

Not relevant

### What happened?

I am trying to set an empty value for a "Select - Multiple" field and it does not work. It works for not-empty values, but it does not work with an empty array or null (which should be the logical candidates for an empty value).

Here is the problem in details:

- I created a field in mautic with the type "Select - Multiple" and added 2 possible vales.
- I am updating the values with a PHP script using mautic/api-library of course.
- The problem is that when I am updating the field values of a specific contact with actual values - it all works, but when I post an empty array or NULL - the value does not change.

### How can we reproduce this issue?

this works:

`      
$data = [
        'multivalue_categories' => ['cat1','cat2'],
      ];

      $mauticUser = $contactApi->edit(
        MAUTIC_ID,
        $data,
        FALSE
      );
      $data = [
        'multivalue_categories' => "cat1|cat2",
      ];

      $mauticUser = $contactApi->edit(
        MAUTIC_ID,
        $data,
        FALSE
      );`

this does not work:

`
    $data = [
      'multivalue_categories' => [],
    ];
    
    $mauticUser = $contactApi->edit(
      MAUTIC_ID,
      $data,
      FALSE
    );
`

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
@rguedes I close this in favor of the existing issue #10992 - could you please join there and help getting all details if yours add more insights?
