### ISSUE TITLE
[UX] "Theme" field is visible even when "Use theme style" is set to "No" when creating a form

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13433]
The “Theme” field is visible regardless of whether the “Use theme style” option is set to “Yes” or “No”. Users might wonder if the “Theme” field has an effect even when “Use theme style” is set to “No”, which is not the case. By ensuring that the “Theme” field is only visible when “Use theme style” is set to “Yes”, we can provide a more consistent and logical user experience.

This issue can be resolved by making the “Theme” field visible only when “Use theme style” is set to “Yes”.

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by abansal15** [comment]
Hello @andersonjeccel could you please assign it to me i assure you i will do it quickly.

**Comment by andersonjeccel** [comment]
@abansal15 Thanks!

**Comment by abansal15** [comment]
@andersonjeccel thanks for assigning me. I am facing some issues in setting up the project locally on Ubuntu could you please guide me how to setup this project locally so that I can start contribution fastly please.

**Comment by andersonjeccel** [comment]
@abansal15 

1. Install Docker
```
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
echo \ "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \ $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \ sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo groupadd docker
sudo usermod -aG docker $USER
logout
```
Log back in
```
systemctl start docker
systemctl enable docker
```
Test functionality with` docker run hello-world`

2. Install DDEV
```
sudo sh -c 'echo ""' && sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://pkg.ddev.com/apt/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/ddev.gpg > /dev/null
sudo chmod a+r /etc/apt/keyrings/ddev.gpg && sudo sh -c 'echo ""'
echo "deb [signed-by=/etc/apt/keyrings/ddev.gpg] https://pkg.ddev.com/apt/ * *" | sudo tee /etc/apt/sources.list.d/ddev.list >/dev/null
sudo sh -c 'echo ""' && sudo apt update && sudo apt install -y ddev
```
3. Download the source code of Mautic
4. Navigate to the user's home directory
5. Create a Mautic folder and paste the source code files into it
6. Open the folder
7. Create a .env.local file
7.1. Set:
```
APP_ENV=dev 
APP_DEBUG=1 
```
and save
8. Return to the Terminal
9. Use cd /mautic to navigate to the directory
10. Start DDEV using `ddev config`
10.1. Provide a name for the installation or press Enter to use "mautic"
10.2. Press Enter again on the next prompt
10.3. When prompted for the project type, type php and press Enter

11. Start DDEV with `ddev start`
12. Run composer
```
ddev ssh
composer install
npm install
```

13. Access the Mautic installation at http://mautic.ddev.site/
14. Complete the installation
14.1. Click Next on the first screen
14.2. In Database Host, Name, Username, and Password, fill in all with db
14.3. Click Next
14.4. Create your username and password and finish

15. Log in

16. Set up GitHub Desktop to use the /mautic folder you created

**Comment by abansal15** [comment]
@andersonjeccel thanks for this a lot

**Comment by abansal15** [comment]
@andersonjeccel when doing the ddev config when i am doing ddev start then this issue is coming i am trying to resolve it but it is not resolved could you please help me in this please 
![image](https://github.com/mautic/mautic/assets/120590200/d8d17bf9-53c0-482b-9be7-bc8c4ee7a5a8)

and sometime this issue comes upon doing the ddev start 
![image](https://github.com/mautic/mautic/assets/120590200/3eb39eb8-1804-4628-919f-70692c32bf35)
in this issue i also tried to remove that docker file using docker rm but nothing happens

**Comment by andersonjeccel** [comment]
@abansal15 

`docker stop $(docker ps -a -q) ` to fix Docker issues

Then `ddev clean --all` to delete everything DDEV did

Delete the entire Mautic folder

Create it again with the source code (using git or GitHub desktop)

Start again from 10. `ddev config`

ALWAYS run `ddev stop` before shutting down your computer.

If you make a mistake and forget, instead of `ddev start` you have to run `ddev restart` next time

**Comment by andersonjeccel** [comment]
@abansal15 Hey, do we have news?

Tell me if you need help

**Comment by abansal15** [comment]
@andersonjeccel thanks for your guide I have resolved the error now I have redirect to the username , password. But sir i was not able to do this task as because in my college mid sem exams are going on . Could you please give me some time till Monday I will raise the pr my midsem exams will gets completed on Saturday. Please understand my situation continuous all the days i have exams.

**Comment by abansal15** [comment]
@andersonjeccel on the usename i am writing mautic and on the password i am writing admin but it is giving invalid login . please verify credentials . could you please help me in solving this problem

**Comment by andersonjeccel** [comment]
@abansal15 You can try some options:

admin / mautic

Or

Maut1cR0cks!

[More info here](https://devdocs.mautic.org/en/5.x/development-environment/environments.html)

**Comment by abansal15** [comment]
Hello @andersonjeccel i have found the FormType.php where the code of choosing the theme yes or no is written but i am not able to find the .html file where the whole page is rendered could you please help me in finding this ?

**Comment by abansal15** [comment]
Hello @andersonjeccel could you please help in the problem of finding the .html file where whole page is rendered ?

**Comment by andersonjeccel** [comment]
Hi @abansal15 
It could be this one: 

`app\bundles\FormBundle\Resources\views\Builder\form.html.twig`

It seems to be related to rendering the sidebar form

But if it's not, you can search inside `app\bundles\FormBundle\Resources\views\` for the other Twig templates

My knowledge is on UX and CSS code, that's why you're being guided through what should happen on a practical scenario instead of technical details

Thanks in advance for being up for this task

**Comment by andersonjeccel** [comment]
@nishant-s7 
Would you like to catch this issue?

**Comment by nishant-s7** [comment]
Yes, sure 👍

**Comment by nishant-s7** [comment]
Hi there!
How do I make javascript changes reflect on the browser? I added a line in `6.forms.js`, but it's not present in the browser debugger. I tried using `ddev exec bin/console m:a:g` and it gave `Production assets have been regenerated.`, but it didn't work.

**Comment by andersonjeccel** [comment]
@nishant-s7 Hey! Did you try activating dev mode on .env.local? It may be a cache issue (on dev mode it's deactivated)

1. Create the `.env.local` file on mautic root
2. Fill the file with:
```
APP_ENV=dev
APP_DEBUG=0
```
3. Save, go to Mautic and reload the page

**Comment by nishant-s7** [comment]
Hi @andersonjeccel 
`.env.local` was already present with only change being `APP_DEBUG=1`. I changed it to `0` but that didn't solve it. Do I have to specify somewhere to use `.env.local`?

**Comment by andersonjeccel** [comment]
@nishant-s7 Try deleting the entire /var/cache folder

**Comment by andersonjeccel** [comment]
Fixed
