### ISSUE TITLE
[UX] The tab Permissions should be disabled when "Has full system access?" is set to Yes

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13441]
This issue happens when creating a new role.
Currently, the “Permissions” tab is visible even when the “Has full system access?” option is set to “Yes”.

When opening it, the tab is blank, so it can indeed lead to confusion and may give an impression of another incomplete or faulty feature. 

This issue can be resolved by hiding the “Permissions” tab when “Has full system access?” is set to “Yes”.

To reach where this bug happens, follow these steps:

1. Open Mautic
2. Open the right sidebar
3. Click on Roles
4. Create a new role (+ New)
5. Set "Has full system access?" to Yes
6. Click on Permissions tab to find it blank

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by andersonjeccel** [comment]
@abansal15

Another one here if you'd like to fix.

**Comment by abansal15** [comment]
Ys sure @andersonjeccel  i will be very happy to do i am just fixing some error in setting the code locally. I will do it as soon as possible. Thanks for providing me the opportunity.

**Comment by andersonjeccel** [comment]
@abansal15 Thanks, I'll come here to check next Tuesday!

I can instruct you to set up DDEV on Windows 10/11 or Ubuntu, ping me if you need.

**Comment by nox1134** [comment]
Hi @andersonjeccel! If no one is working on this issue, I'd like to take up this issue and work on it.
Could you please assign the issue to me?

**Comment by andersonjeccel** [comment]
@nox1134 Here you go

**Comment by vikasgrewal16** [comment]
Sorry for the late review 
But can i also take this issue?
@andersonjeccel

**Comment by andersonjeccel** [comment]
@vikasgrewal16 I'd really like to see this pull request happening
Tell me if you're still up for this task
I'll update the issue description

**Comment by nox1134** [comment]
Hey @andersonjeccel! Sorry it took me a while to get back to you. I was busy with my university exams. I've been working on the issue, and I've managed to resolve it.

**Comment by nox1134** [comment]
Hi @vikasgrewal16! I hope you haven't started working on the issue yet.

**Comment by andersonjeccel** [comment]
Hi @nox1134 
Sorry for the confusion, I'm glad you solved it
A huge thanks!

**Comment by nox1134** [comment]
No problem @andersonjeccel 
Thanks!

**Comment by andersonjeccel** [comment]
Fixed
