### ISSUE TITLE
Issue when import doNotEmail list

### ISSUE THREAD

**Issue by Pixman** [mautic/mautic#1344]
Hello, i'm on Mautic V1.2.3.
I test to import csv dile with theses columns 
email;firstname;lastname;donotemail

donotemail contain 1 or 0 for change status.
on import i have this error 
> (#2) An exception occurred while executing 'UPDATE leads SET firstname = ?, lastname = ?, email = ?, doNotEmail = ? WHERE id = ?' with params ["xxxxxx", "xxxxxx", "xxxxxxxxx@xxxxxx.xx", "0", 724]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'doNotEmail' in 'field list'

it's seem thesql query want to modify a column in lead entity, but the doNotEmail in in different table.

Thank for your help.

**Comment by escopecz** [comment]
I can replicate this issue. Tested with CSV file:

```
email,firstname,lastname,doNotEmail
john@gmail.com, John, Doe, 1
```
