### ISSUE TITLE
Dashboard widget edit/remove functionality is not working

### ISSUE THREAD

**Issue by Galokh66** [mautic/mautic#13443]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When a user tries to edit a widget, the edit panel never loads.
<img width="1792" alt="Screenshot 2024-02-21 at 8 58 26 PM" src="https://github.com/mautic/mautic/assets/88474171/eb445884-a8fc-48d1-9c7a-00fac19011a5">
When a user removes the widget, and reloads the dashboard, the widget appears again.
<img width="1792" alt="Screenshot 2024-02-21 at 8 58 54 PM" src="https://github.com/mautic/mautic/assets/88474171/359a296a-967c-4fc7-9b49-68a45bd5e502">
<img width="1792" alt="Screenshot 2024-02-21 at 8 59 05 PM" src="https://github.com/mautic/mautic/assets/88474171/59f853e1-5653-492d-871d-de2a0a7318f8">

### How can we reproduce this issue?

Step 1: Create a widget on dashboard
Step 2: Try to edit the widget
Step 3: Remove the widget and reload the dashboard

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by Loki321** [comment]
Same issue here but on version 4, accompanied by the error;

`Mixed Content: The page at 'https://mymautic.com/s/dashboard' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mymautic.com/s/dashboard/edit/2?_...'. This request has been blocked; the content must be served over HTTPS.`

**Comment by RCheesley** [comment]
Hi folks,

Please can you try to rebuild your Mautic assets (bin/console m:a:g) and see if this resolves the issue? It might indeed be an issue with mixed content as @Loki321 reports, which is a configuration issue and should be taken to the forum at https://forum.mautic.org for support to help with figuring that out.
