### ISSUE TITLE
Shorthand command notation "m:c:u" is ambiguous on 5.x

### ISSUE THREAD

**Issue by patrykgruszka** [mautic/mautic#13465]
### Mautic Version

5.0.x series

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8.2.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

The shorthand command notation `m:c:u` for `mautic:campaigns:update` is no longer working on 5.x.

### How can we reproduce this issue?

Step 1: run command `php bin/console m:c:u`

### Relevant log output

```shell
Command "m:c:u" is ambiguous.                                                        
Did you mean one of these?                                                           
      mautic:campaigns:update           Rebuild campaigns based on contact segments.   
      mautic:custom-field:update-column Create custom field column in the background.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by escopecz** [comment]
@patrykgruszka I don't think this is a bug. Another command with the same starting letters was added. So Symfony correctly response with this error and tells you what 2 commands are starting with the same letters. Please, use the full command name instead to avoid the same issue in the future. If you need something short when you write it by hand, you can use `bin/console m:ca:u`.
