### ISSUE TITLE
[UX] The Campaigns modal of which a contact is part is shown blank instead of returning a message warning that it is not part of any

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13472]
Currently, when checking which campaigns a contact is part of, the Campaigns modal is shown blank if the contact is not part of any campaign. 

This could potentially cause confusion for users as they might think that the feature is not working properly. This issue can be resolved by hiding the modal then displaying a message that clearly states “This contact is not part of any campaign” when applicable.

![Image](https://github.com/mautic/mautic/assets/116097999/4596eff7-c856-4690-9335-0a06be036ede)

![Image](https://github.com/mautic/mautic/assets/116097999/e23d38f6-492b-4851-92b8-8461da7b7e37)

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by andersonjeccel** [comment]
@patrykgruszka Would you mind if I assign this task to you?

Or perhaps you could suggest someone that would like to work on it pls

**Comment by Vayras** [comment]
Hey! @andersonjeccel I'm an open source contributor, I'm constantly looking for newer projects to contribute to. If this is available to work on let me know, Thanks

**Comment by patrykgruszka** [comment]
Seems like a good issue to start with. @andersonjeccel you can assign it to @Vayras.

**Comment by PiyushThapaa** [comment]
@patrykgruszka  @andersonjeccel Hey, I am interested in this issue if possible can you assign it to me??

**Comment by vikasgrewal16** [comment]
can i get more info on this how can i start my work on this issue

**Comment by andersonjeccel** [comment]
@PiyushThapaa Hey! Would you mind catching this UX issue? #13416 

Just leave a comment on it if you'd be up, thank you!

**Comment by andersonjeccel** [comment]
@vikasgrewal16 I would greatly appreciate your help on this issue: #13441 

Leave a comment there if you'd like to fix, thanks!

**Comment by rohit-sharma-1802** [comment]
@andersonjeccel I want to work on this

**Comment by mallezie** [comment]
Created above PR with some changes. 
Did not go for the full warning message, just making it clear that there are no campaigns in the modal.
