### ISSUE TITLE
Error in campaign builder when cloning campaign

### ISSUE THREAD

**Issue by vln104** [mautic/mautic#1347]
With 1.2.3, I've noticed the following issue while testing issue 1303

1) Create a campaign
![campaign](https://cloud.githubusercontent.com/assets/13978633/12290293/dc348842-b9d8-11e5-8646-308f025b4067.png)
2) Go back to the campaign page and clone the new campaign -> Click Save & Close
3) Open the campaign again and go to the campaign builder and notice that the workflow is not correct:
![campaign_cloned](https://cloud.githubusercontent.com/assets/13978633/12290350/3097ff22-b9d9-11e5-99f4-073466d02d27.png)

**Comment by escopecz** [comment]
Ahh, finally found the issue. I knew I saw it somewhere already. I forgot that it was me who reported it.

https://github.com/mautic/mautic/issues/1182

I'll close this one as a duplicate
