### ISSUE TITLE
Custom Field to store "Checkbox group" input data

### ISSUE THREAD

**Issue by TiagoGouvea** [mautic/mautic#1348]
I created a "Checkbox group" input on my form and I'm trying to save the selections to the Lead record, but without success. I already try custom fields "Text", "Textarea" and "Select" but nothing work.

When I open the lead, on the "Events" I saw the options checked on form submit, ok. But in the Lead details the field are always empty.

* Every time I changed the the custom field, I update the input form to link it and submitted again the form with the lead data.

Will be good to have a field to fit it, and, enable it to be filtered on lists.

**Comment by mqueme** [comment]
I have checked this on latest version of Mautic 2.1.0 php version 7.0.0 and it is updating the lead records, tested on a core field and a custom field, both were updated.
