### ISSUE TITLE
ALT atribute for tracking gif 

### ISSUE THREAD

**Issue by smitione** [mautic/mautic#1349]
Hi, i have a newsletter that send using Mautic.
I have all properly setted up, incluid single point transparent tracking gif, but it seems to be reconverted to a new <img style="display: none;" height="1" width="1" src="http://www.vpsnews.org/index.php/email/5695a83ecc22f.gif" /> but this new image have a missing ALT atribute.
I need to ad this ALT atribute to any image used in my newsletter.
Best regards
SMITIONE

**Comment by escopecz** [comment]
The alt attribute should be part of the `<img/>` tag so I'll mark this as a bug.

You wrote:
> incluid single point transparent tracking gif
Mautic includes the tracking gif for you automatically. You don't have to include it.
