### ISSUE TITLE
Filter to sort leads that do not belong to any lists

### ISSUE THREAD

**Issue by CedricH-BZH** [mautic/mautic#1350]
It's currently really easy to sort leads by one list name. Therefore its difficult to know if some leads are not affected to any list.

I'd like to see a "no-list" token appear when displaying the available lists to sort by.

**Comment by jordan8037310** [comment]
@CedricH-BZH You can accomplish this by creating a List called "NO LIST" or "NOT SORTED" and then adding Filters: List Membership: Exclude -> {add all of your lists}. Not the easiest solution but OK until you can create a list based on an attribute being empty...
