### ISSUE TITLE
[DDEV] Install Screen Buttons Do Nothing

### ISSUE THREAD

**Issue by byt3sage** [mautic/mautic#13508]
### Mautic Version

5.0.x series

### Way of installing

I'm using a Docker image from https://hub.docker.com/r/mautic/mautic

### PHP version

8.2

### What happened?

When creating a new DDEV environment, the buttons on the installer screen may appear to do nothing.

### How can we reproduce this issue?

Step 1: Setup DDEV so that you are greeted by the installer screen (This was on a Mac)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by byt3sage** [comment]
It appears that even though `npm ci` is getting ran, it wouldn't let me progress unless I added `npm install` into the `mautic-setup.sh` file. 

I'm happy to open a PR if more people are having this! :)

**Comment by RCheesley** [comment]
Weird, I've not had that issue to date and I've done a few installs recently. Please do make a PR if it's something that you're able to fix!
