### ISSUE TITLE
Campaign builder throws error for 'Update Contact Details' action when HTML type Custom Field is present for a contact

### ISSUE THREAD

**Issue by Galokh66** [mautic/mautic#13511]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Campaign builder throws error "html class does not exist" for 'Update Contact Details' action when HTML type Custom Field is present for a contact.

### How can we reproduce this issue?

1. Create a custom field of type html
2. Create a contact and verify that this html field is available for the contact
3. Create a campaign and proceed to campaign builder
4. Add any segment and click on select action
5. Select Update contact details action
6. An error is thrown stating "
<img width="1792" alt="Screenshot 2024-02-27 at 11 44 11 PM" src="https://github.com/mautic/mautic/assets/88474171/ddd5bae7-26b8-4730-9de9-4938a0a44976">
html class does not exist"

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi @Galokh66 I have just tried to reproduce this on Mautic 5.x but I am not having the same issue.

Can you maybe share what was in the field (I just popped a link in there using a tags)? Can you verify it still happens on the [5.x branch](https://gitpod.io/#https://github.com/mautic/mautic)?

**Comment by RCheesley** [comment]
Closing due to lack of response, feel free to request a re-open if it's still a bug.
