### ISSUE TITLE
Column "Alias" inserting as null when cloning forms from previous version.

### ISSUE THREAD

**Issue by duduric** [mautic/mautic#1352]
Hi,
Just updated from 1.2.1 to 1.2.3
When cloning one of the older forms, I get this error when saving:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'alias' cannot be null at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:91, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'alias' cannot be null at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:165)"}

**Comment by escopecz** [comment]
This is a known issue of 1.2.3 and the fix is here: https://github.com/mautic/mautic/pull/1278

An additional test from you would be great. It would speed up the release of 1.2.4.
