### ISSUE TITLE
Portainer: Mautic can't connect to server on localhost

### ISSUE THREAD

**Issue by F041** [mautic/mautic#13538]
### Mautic Version

5.0.x series

### Way of installing

Other (please specify if relevant in the bug report)

### PHP version

Na

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Details 
https://github.com/Lissy93/portainer-templates/issues/50#issuecomment-1987214302

### How can we reproduce this issue?

Step 1: use portainer 
Step 2: use app templates from the readme of the previous link
Step 3: install mautic 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
@F041 thanks for opening the issue, but you need to add more details or move it to a discussion in the forum. Do you know if its a recreatable bug or a setup issue requiring some support?

Are you raising the issue vs. the mautic docker image? Once you have all details together and also discussed with other portainer users in the forum, you should raise it here: https://github.com/mautic/docker-mautic
