### ISSUE TITLE
clicky analytics support

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#1353]
Is there support for clicky as a plugin?  https://clicky.com/help/api  .  They are supposed to be a competitor for google analytics. You can go to their plugins page to see who is already setup:  https://clicky.com/help/apps-plugins.

**Comment by escopecz** [comment]
So could you close the Clicky feature request and open another one for advanced tracking? Or edit this one so it is obvious what you really suggest? If I were a developer interested in implementing some feature request, I'd be confused what to do with this one.

**Comment by 4evermaat** [comment]
Agreed.  I edited this one.  And then I added a new request:  https://github.com/mautic/mautic/issues/1360  .  I'd rather see the new request of direct incorporation of advanced tracking integrated directly into mautic done first, as that would help more people without the need to pay for an additional service.
