### ISSUE TITLE
allow for setting lead update criteria (e.g. IP / location) for smart lists / campaigns / user groups / some other way

### ISSUE THREAD

**Issue by 750430** [mautic/mautic#1354]
Hi,

We are using Mautic to 'on-board' new users to a web service, the user signs up using an email address already qualified in the sign-up process, so we know it is valid and works.

As I understand it, IP/location/other details are set as follows:
"Mautic merges leads by email address"
"An anonymous lead is created every time a tracked page is loaded and there is no known IP address or cookie about the visitor."
"Mautic uses different identifiers. If email is known, it merges lead actions by email. If email is not known, it merges leads by cookie ID."

When we import our leads/users, we bring an IP address along too, I have mapped it either/both to the default 'ipaddress' and a custom 'ipaddress' to not really any increase in success.

So, I'd like to be able to specifically set an option (ideally a local option, so it only affects this particular campaign / users) to state that when an email is sent out, the recipient's email address is referenced/based on to build out all other personalised information.

hope that makes sense.

**Comment by escopecz** [comment]
I think the important sentence from your summary is

> when an email is sent out, the recipient's email address is referenced/based on to build out all other personalised information

But I don't see a connection with the rest of the summary. Could you explain it with other words? Because email address is used to build out all other personalized information as far as I know.

**Comment by 750430** [comment]
Hi.

Apologies for any confusion.

I think I understand how lead updating/tracking works, however, I'd like to be able to make some amendments to the criteria for lead tracking. Despite now using an API to feed Mautic our leads, we still see a massive proportion of anonymous leads; these anonymous leads align with the location of the known leads being imported.

I wondered if it could be possible to somehow specify what criteria is used for lead tracking/identity on a per-campaign basis.
e.g. if I receive a Mautic email with my email address in it, if I open the email or click a link within the email, I'd like Mautic to record the email has been read whether I don't open it but click a link or if I open it, and if I sign in to my email from some other random device with no other data on it, I'd like Mautic to acknowledge the read/open of that email.

I'll try and build some testing so that the issue can be replicated, however, I'd also like to learn whether what I'm asking is viable?

thanks,

**Comment by escopecz** [comment]
I thought Mautic's email links work as you describe. Make sure you don't test while logged in to Mautic as described at https://www.mautic.org/docs/emails/troubleshooting.html

**Comment by natansouza** [comment]
Hi, I have a similar problem. I want to use the system in the network where there are multiple users with the same Internet IP output . Ie the mautic is considering them as if they were one single lead that is wrong. Is there any way to disable the blending option for IP ?

tks.

Natan

**Comment by 750430** [comment]
Hi @escopecz 

Our system is live - so the leads being tracked will definitely not have any login functionality.

thanks.

**Comment by escopecz** [comment]
@natansouza right now there is only the **kiosk mode** in the Mautic form configuration which will create multiple leads submitting the form from one address.

@750430 Reports has the export feature.

**Comment by natansouza** [comment]
Hi @escopecz I found the solution for me, see here: https://github.com/mautic/mautic/pull/1030

**Comment by 750430** [comment]
![image](https://cloud.githubusercontent.com/assets/9106836/12858494/6590ddb2-cc48-11e5-96bf-414490844f14.png)

**Comment by 750430** [comment]
Closing as no longer relevant for me.
