### ISSUE TITLE
CampaignBuilder.Condition.EmailReceived

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#1355]
JTBD:
When receiving leads from sources such as generic service-related email addresses like support@, or sales@,
I want to push leads into a specific campaign and lead list,
So that I can properly funnel, up-sell, or cross-sell relevant services offered and further nurture the customer.

Thoughts:
- When receiving a lead via Email integration, a Email Received condition should check for email source, and route to an appropriate campaign or list.
- This feature could be further generalized to integrate with newsletter subscription services (MailChimp, ConstantContact), and route that contact information as a new lead.

**Comment by andrefilo** [comment]
Interesting feature!
+1
