### ISSUE TITLE
Not possible to add element(DWC, form...) in page builders by slot names

### ISSUE THREAD

**Issue by Syrgak-Alan** [mautic/mautic#13552]
### Mautic Version

5.0.x series

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8.2.15

### What browsers are you seeing the problem on?

Firefox

### What happened?

The way to add DWC or form in landing page by their slot name/id is not possible. After trying to save page, appears this issue:
![image](https://github.com/mautic/mautic/assets/96595532/0083d093-e628-4c34-aee9-e38295ca67c2)

### How can we reproduce this issue?

Step 1: create DWC/Form
Step 2: create page and try to add created component by {dwc=<slot_name>} or {form=<id>}
Step 3: press save

### Relevant log output

```shell
500 Internal Server Error - PHP Notice - iconv(): Detected an illegal character in input string
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi @Syrgak-Alan I have tested this with 5.x and I was able to insert my DWC slot name into the GrapesJS builder landing page using the editor token, and it rendered on the front-end as expected, as did a form.

Perhaps this might be related to using PHP 8.2? Have you had the same issue with 8.1? Also, which version of Mautic?

**Comment by RCheesley** [comment]
Closing due to lack of feedback. Feel free to request a re-open if it's still a bug.
