### ISSUE TITLE
Uncaught TypeError: Mautic.configDsnTestExecute is not a function

### ISSUE THREAD

**Issue by lordimac** [mautic/mautic#13563]
### Mautic Version

5.0.x series

### Way of installing

I'm using a Docker image from https://hub.docker.com/r/mautic/mautic

### PHP version

8.1.27

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### What happened?

Following Error shows up in Browser Console when trying to test E-Mail Server or Queue Settings.

Uncaught TypeError: Mautic.configDsnTestExecute is not a function
    onclick https://domain.tld/s/config/edit:1
3 edit:1:8
    onclick https://domain.tld/s/config/edit:1

### How can we reproduce this issue?

Test E-Mail Server Settings or Queue Settings

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by lordimac** [comment]
For your information, same problem in 5.0.4.

**Comment by escopecz** [comment]
Please run:
1) `npm ci`
2) `bin/console mautic:assets:generate`

Any change after that?

**Comment by lordimac** [comment]
Now nothing is working in my UI anymore.
I can login, but thats it. Statistics are spinning forever, drop down menus not working, what have I done?!

Console show now more errors then before.

```
Uncaught SyntaxError: Invalid regular expression flags (at libraries.js?vdeaa430f:1:1)
app.js?vdeaa430f:1  Uncaught ReferenceError: jQuery is not defined
    at app.js?vdeaa430f:1:30
(anonym) @ app.js?vdeaa430f:1
dashboard:86  Uncaught TypeError: Cannot set properties of undefined (setting 'getActiveBuilderName')
    at dashboard:86:37
(anonym) @ dashboard:86
builder.js:178  Uncaught TypeError: Cannot set properties of undefined (setting 'launchBuilder')
    at parcelRequire.RfSX../asset.service (builder.js:178:8)
    at f (builder.js?vdeaa430f:1:468)
    at parcelRequire.iHk9 (builder.js?vdeaa430f:1:771)
    at builder.js?vdeaa430f:1:1023
parcelRequire.RfSX../asset.service @ builder.js:178
f @ builder.js?vdeaa430f:1
parcelRequire.iHk9 @ builder.js?vdeaa430f:1
(anonym) @ builder.js?vdeaa430f:1
dashboard:1337  Uncaught TypeError: Cannot read properties of undefined (reading 'onPageLoad')
    at dashboard:1337:24
(anonym) @ dashboard:1337
dashboard:1  Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```



Got it working again by recreating my containers. And guess what, DSN Test is also working now. Topic can be closed.

**Comment by escopecz** [comment]
@lordimac what are outputs of the commands I sent you? Did one of them fail?

**Comment by lordimac** [comment]
No, nothing failed.

Please try the docker setup and running the command. For me it was reproducible. Running this command is breaking the UI until I recreate my docker containers from the image.

**Comment by escopecz** [comment]
I think that NPM isn't available in the docker container and I had a typo if the asset generation command (double ee). So how could it work for you? Did you install NPM and then run it? Did you see the typo and run the right command?

**Comment by lordimac** [comment]
I did see the typo and run the correct command. I can repeat this process, but I dont think its necessary, because its working now after recreating the containers. Dont know what was wrong before.
