### ISSUE TITLE
Campaignbuilder

### ISSUE THREAD

**Issue by OlafDammann** [mautic/mautic#1356]
(M1.2.3) I create a Campaign with some Send-Mail-Actions. Works. Later on I rename the Events from "Send mail" to something different.
Those changes never make it is the system, they will be gone oncee campaign builder will be closed :(

**Comment by escopecz** [comment]
This is a known issue. The fix is here:

https://github.com/mautic/mautic/pull/1284

will be fixed in 1.2.4.

**Comment by OlafDammann** [comment]
Awesome, applause, works! :)
Thanks a lot!
