### ISSUE TITLE
Permission to view Custom fields -> doesn't show custom fields menu / no access

### ISSUE THREAD

**Issue by jos0405** [mautic/mautic#13568]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0 / 8.1

### What happened?

I create a role where Custom Fields can be viewed.
The user logging in with this rule won't see the custom fields menu, nor have access to it:

Menu item missing from under the gear icon.

directly trying to access "URL/s/contacts/fields" produces:
![image](https://github.com/mautic/mautic/assets/4246909/08fc0429-7aac-4f7a-8663-53ec20fa68cb)

### How can we reproduce this issue?

Step 1: Set new role "Manager"
Setp 2: Set the following permissions:
![image](https://github.com/mautic/mautic/assets/4246909/0a9329f8-29d6-406a-9d8d-b0a151de8143)
Step 3: Login with a user with Manager role.
Step 4: Click on gear icon, check if Custom fields are visible

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for the report @jos0405 - it was also flagged up in https://github.com/mautic/mautic/issues/13602 and as that one is already a bit more active and has a cause identified, I'll close this report down and we can continue the conversation there.
