### ISSUE TITLE
Inconsistency in width display of "Map" module on Landing Pages in GrapeJS

### ISSUE THREAD

**Issue by code5rick** [mautic/mautic#13574]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

When utilizing the GrapeJS builder for landing pages, we've encountered an issue with the "Map" module. Despite appearing to have a 100% width when inserted onto the page, it is actually displaying with a fixed width of 350px upon saving.

This discrepancy between the displayed width and the actual width could potentially mislead users into believing that the module spans the full width of the page when, in fact, it does not.
![image](https://github.com/mautic/mautic/assets/131262825/1a44b825-39e1-4c23-b5a0-5a28e70ceb8d)

First reported on: https://github.com/mautic/mautic/pull/13283#issuecomment-2015462092

### How can we reproduce this issue?

Step 1: Go to Components > Landing Pages.
Step 2: Create a new landing page.
Step 3: Provide a title for the landing page.
Step 4: Choose the "Blank" theme, then click on "Builder."
Step 5: Add the "Map" module to the landing page. Notice that it initially appears to occupy the full width of the page.
![image](https://github.com/mautic/mautic/assets/131262825/773bcfc4-c75c-4769-a708-b26c10692fe3)

Step 6: Exit the builder by clicking on the close button, then select "Save & Close."
Step 7: Preview the page to visualise the actual width of the "Map" module.
![image](https://github.com/mautic/mautic/assets/131262825/412bde4f-3074-4d4d-a86c-516498ee95e2)

### Relevant log output

```shell
None.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
Hi @code5rick,
actually - step 5 is due to the missing column element? When I placed a column first, I didn't experience the full width in the editor window.

![image](https://github.com/mautic/mautic/assets/1241376/07454d62-29eb-46a4-9989-12b00e92ce61)

As a workaround, you could add the 100% for width and set the max width to the absolut width of your container.
Not sure if this is a Mautic or Grape-JS Bug.

**Comment by RCheesley** [comment]
@code5rick any thoughts on this?

**Comment by code5rick** [comment]
I didn't put the module inside of a column or a section. Maybe thats the problem?

**Comment by RCheesley** [comment]
OK, closing this PR then!
