### ISSUE TITLE
Incorrect Statistics Counting in Focus Items Chart

### ISSUE THREAD

**Issue by AlanWierzchonCA** [mautic/mautic#13583]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

After clicking on the link in a Focus Item, the view counter of this Focus Item on the chart in its preview increases.

### How can we reproduce this issue?

Steps to Reproduce:

1. Display the Landing page with Focus Item.
2. On the views chart: 1 (or increased by 1).
3. Click on a link in the focus item.
4. On the chart, both clicks and views are increased by 1 (clicks: 1, views: 2).
5. Click on the remaining 2 links.
6. On the chart, clicks: 3, views: 4.

Expected Outcome:
Clicking on a link in the focus item should not increase the number of views.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Closing as resolved by #13584
