### ISSUE TITLE
mautic:broadcasts:send failing with a query taking forever to run

### ISSUE THREAD

**Issue by chizuoka** [mautic/mautic#13592]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

PHP 7.4.30

### What browsers are you seeing the problem on?

Chrome

### What happened?

When cron is trying to run, it is failing with a "MySQL server has gone away" because of the following query taking too long to run.

SELECT l.* FROM pb_leads l WHERE (EXISTS (SELECT null FROM pb_lead_lists_leads ll WHERE (ll.lead_id = l.id) AND (ll.leadlist_id IN (3)) AND (ll.manually_removed = 0))) AND (NOT EXISTS (SELECT null FROM pb_lead_donotcontact dnc WHERE (dnc.lead_id = l.id) AND (dnc.channel = 'email'))) AND (NOT EXISTS (SELECT null FROM pb_email_stats stat WHERE (stat.lead_id = l.id) AND (stat.email_id IN (17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27)))) AND (NOT EXISTS (SELECT null FROM pb_message_queue mq WHERE (mq.lead_id = l.id) AND (mq.status <> 'sent') AND (mq.channel = 'email') AND (mq.channel_id IN (17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27)))) AND ((l.email IS NOT NULL) AND (l.email <> '')) LIMIT 1000 /* statement may be truncated */

It has gotten stuck with sending an email with these stats 
47472 Pending 
33000 Sent 
6815 Read 
20.65% Read

My guess there is too much recipients? How to solve this as the broadcast can no longer send. Even trying to open the contact page is failing now. 

Strangely memory is only using 11GB from 16GB available, CPU and disk are all near zero at the moment

xx_leads about 650k rows
xx_lead_lists_leads has about 1.1M rows
xx_email_stats about 690k rows
xx_message_queue about 200 rows

### How can we reproduce this issue?

Step 1: Sending a broadcast segment email to about 50k recipients. 
Step 2: Running cron
sudo php ../bin/console mautic:broadcasts:send --limit=1000 --bypass-locking

### Relevant log output

```shell
I get the server has gone away. Will add more logs later.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems and dealing with server-related issues :)
