### ISSUE TITLE
Advanced tracking of visitors on web page

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#1360]
like where in the page visitors are clicking, scrolling, viewing, mouseover for > xxx seconds or milliseconds.

It would be nice if this can be done live and updated to some sort of heatmap.  Then to take it up a notch, if the interaction can be tracked to a specific user, then you can update their actions in the campaigns, especially if they are known visitors. But even as unknown visitors, it is still nice to know what they are doing on webpages and give us insight into what to tweak on the page.

The problem with mautic is that, as a non-programmer, I do not know exactly how to automate these things.  I can insert some code into my site and edit arguments to customize pre-written scripts.

**Comment by 4evermaat** [comment]
@dbhurley 
Why was this closed?  It was pretty good suggestion, was it not?    Was something implemented to take its place?

**Comment by michacassola** [comment]
Yeah, please open this, as it is a Feature request.
I would include two points into visitor monitoring:
- Heatmaps
- Full Session Recording
