### ISSUE TITLE
Missing Custom fields view permission

### ISSUE THREAD

**Issue by patrykgruszka** [mautic/mautic#13602]
### Mautic Version

5.0.x series

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8.2.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

In recent 5.x version there is missing permission setting for contact custom fields.

5.x branch:
![image](https://github.com/mautic/mautic/assets/8580942/7d0c1fa8-c577-433e-b6df-314eb1744570)

5.0.3:
![image](https://github.com/mautic/mautic/assets/8580942/12edb7a7-debb-4949-ac4e-155785f11300)

In result of this change introduced in #13321 I can no longer get the custom field list from API. The `lead:fields:view` is still used in the controller.

Related files:
 https://github.com/mautic/mautic/pull/13321/files#diff-fc1c6863009fa9dbb412ad96ef474537d4e3d72c2ccc90f126e7bd808b0e45a7L64

### How can we reproduce this issue?

1. Go to the roles permission settings
2. Select the Contact Permissions
3. Check if the View permission is available

### Relevant log output

```shell
{"errors":[{"code":403,"message":"The response has unexpected status code (403).\n\nResponse: {\"errors\":[{\"code\":403,\"message\":\"Permission not found. 'lead:fields:view' given.\",\"details\":[]}]}"}]}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by patrykgruszka** [comment]
@aarohiprasad Could you please take a look at this issue? Was it removed intentionally or by mistake?

**Comment by RCheesley** [comment]
@aarohiprasad could you please take a look at this one? It seems [your PR](https://github.com/mautic/mautic/pull/13321) has resulted in some unexpected changes to custom field permissions.

**Comment by Ilona-Sot** [comment]
Is anyone working on solving this bug?

**Comment by RCheesley** [comment]
Not currently @Ilona-Sot - we've put out a few requests as it's blocking the 5.1 release.

**Comment by escopecz** [comment]
I'll take a look at this issue.

**Comment by escopecz** [comment]
The view permission got returned in https://github.com/mautic/mautic/pull/13741. Please test it.
