### ISSUE TITLE
Email setup

### ISSUE THREAD

**Issue by imraanw** [mautic/mautic#1361]
Hi
Cannot connect to email service

Connection could not be established with host smtp.sendgrid.net [Connection timed out #110] Log data: ++ Starting Mautic\EmailBundle\Swiftmailer\Transport\SendgridTransport !! Connection could not be established with host smtp.sendgrid.net [Connection timed out #110]
++ Starting Mautic\EmailBundle\Swiftmailer\Transport\SendgridTransport !! Connection could not be established with host smtp.sendgrid.net [Connection timed out #110]

**Comment by escopecz** [comment]
Any info about what credentials do you use to configure your email settings?

I think that the Sendgrid needs your email as the username and the API key as password. Maybe you inserted the password to your Sendgrid account instead.

**Comment by imraanw** [comment]
HI John

 

Found a solution didn’t test it yet though.

 

For those who have problem with SendGrid and API.

1 - "Service to send emails through" -> Other SMTP Server
2 - SMTP Host -> smtp.sendgrid.net  <http://smtp.sendgrid.net> 
3 - SMTP Port -> 465
4 - SMTP encryption type -> SSL
5 - SMTP authentication mode -> Login
6 - Username for the selected mail service -> Put your sendgrid username or email
7 - Password for the selected mail service -> Your Sendgrid Password

Done.
