### ISSUE TITLE
Emails get duplicated after saving changes on GrapeJS

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13635]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0.20

### What browsers are you seeing the problem on?

Not relevant

### What happened?

It seems like there's a bug when creating emails on Mautic 5.0.3 using GrapeJS
They get duplicated, already tested on 3 different instances (1 local dev and 2 prod)
It happens with Segment and Template emails

✅ composer install OK
✅ npm install OK

### How can we reproduce this issue?

Step 1: Copy the 5.0.3 release file to the hosting server root (or subdomain, where you want it to be installed)

2. Extract all files
3. Open a terminal with SSH and fill your credentials to get access 
4. Navigate to the extracted folder
5. Run composer install
6. Run npm install
7. Edit the .htaccess file to allow access to php files using http
8. Open the web address where Mautic was installed
9. Follow the installation process
10. Login
12. Go to Channels > Emails > New 
13. Choose any type, fill the name and subject then click to open the Builder
14. If the builder isn’t activated, go to Plugins > GrapeJS and activate it
15. Add any element to be able to save
16. Click on the Check symbol to save, it will start to spin infinitely
17. When you get tired of waiting, just click on the X to close the builder
18. Click to Save & Close
19. Go back to the emails list
20. See it duplicated

### Relevant log output

```shell
Hm, have to check
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
I was able to recreate it too. The log is empty. However - I have also created 2 mails instead of one.

**Comment by dsp76** [comment]
Same applies for landing pages: https://github.com/mautic/mautic/issues/12928

**Comment by dsp76** [comment]
Also related with this one: https://github.com/mautic/mautic/issues/13271

**Comment by dsp76** [comment]
I close this now in favor of that one: https://github.com/mautic/mautic/issues/13271 (it seems to be the same issue and has already more interaction). Please join there and add useful information if missing. Thanks a lot!

**Comment by weasam** [comment]
This happend in Landing page, campaign email, segment email creation, so far I JUST delete the duplicated one, I'm sure this not only happen on my installation.  "APPLY CHANGES" bottom always on loading stage
![image](https://github.com/mautic/mautic/assets/13821629/a01a6f6c-56b9-40bd-88ee-9c0898d9a8ce)
