### ISSUE TITLE
Update via composer to 4.4.12 is broken

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#13647]
### Mautic Version

4.4.x series

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Updating via composer fails due to some bugs in the files. More details listed here:
https://forum.mautic.org/t/issue-with-updating-4-4-11-to-4-4-12/31656

<img width="433" alt="image" src="https://github.com/mautic/mautic/assets/1241376/3112024c-afc9-4362-a274-6a44c72db851">

### How can we reproduce this issue?

Step 1: try to update to most current version of Mautic 4.4.12 with composer - will only bring you to 4.4.11

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
@escopecz could you please update the composer json file? Probably thats the reason for upgrade to 4.4.12 is failing with composer?

**Comment by escopecz** [comment]
Hey, what exactly shall I update? The recommended project was released with 4.4.12, or did I make a mistake somewhere?

https://github.com/mautic/recommended-project/releases/tag/4.4.12

**Comment by dsp76** [comment]
In a change made by you(?) - see screenshot above - the release level stated is often 4.4.4.12 instead of 4.4.12. Maybe that's the reason why composer updates to 4.4.12 won't work?

**Comment by escopecz** [comment]
I see it now. That's my dyslexia in action. I'll try to re-tag if it fixes it.

cc @RCheesley @mollux for visibility.

**Comment by escopecz** [comment]
PR for review: https://github.com/mautic/recommended-project/pull/72

**Comment by escopecz** [comment]
I re-tagged the recommended project. Can you please re-test if it's fixed?

**Comment by RCheesley** [comment]
@dsp76 I think we can close this now?
