### ISSUE TITLE
Emails are getting sent status before they are processed

### ISSUE THREAD

**Issue by ahansson89** [mautic/mautic#1364]
I don't think emails should be getting sent status before they are processed. I know have a list, where half of they emails failed to send for some reason, and I have no clue about which ones that were sent and which ones that failed.

**Comment by escopecz** [comment]
Could you provide a screenshot of where do you see the sent status?

**Comment by ahansson89** [comment]
https://www.dropbox.com/s/qoarzjkfw88kbnq/Screenshot%202016-01-21%2011.17.04.png?dl=0

**Comment by escopecz** [comment]
If you open the detail page for that email, do you see the errors there?

BTW, if you drag&drop the image to the comment textarea, the image will upload here.

**Comment by ahansson89** [comment]
No, there is no information about errors

**Comment by escopecz** [comment]
Hmm, I'm wondering if or how Mautic could know that the emails failed. Could you provide more information about that? How do you know? What email transport do you use? What was the reason the emails weren't send? Write any information which will let us recreate the issue so we could fix it.

**Comment by ahansson89** [comment]
When it is added to the queue, then it is getting the sent status before the queue has been processed. So if for some reason that queue gets invalidated, all emails will have the sent status even if the queue has never been processed.

IMO the sent status should be added when the queue are processing that queue item. 

Makes sense?

On January 21, 2016 at 11:54:19 AM, John Linhart (notifications@github.com) wrote:

Hmm, I'm wondering if or how Mautic could know that the emails failed. Could you provide more information about that? How do you know? What email transport do you use? What was the reason the emails weren't send? Write any information which will let us recreate the issue so we could fix it.

**Comment by mqueme** [comment]
I am closing this because in the new version stat entities aren’t created till the batch is completed (and emails sent)
