### ISSUE TITLE
Sometimes Right Problems if i delete the Cache

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#13641]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.27

### What browsers are you seeing the problem on?

Firefox

### What happened?

I use to delete the cache in that way:
```
cd /var/www/html/mautic/var/cache
rm -rf *  
```
Sometimes Mautic crashes completely and i have to:
```
chown -R www-data:www-data /var/www/html/mautic
chmod -R 755 /var/www/html/mautic
```

### How can we reproduce this issue?

As written above

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
Hi @stefan-franz this sounds more like an issue with your hosting setup? Why should your installed files don't have the correct rights? Usually this is not an issue of the installation, but incorrect settings of users and groups, especially related to the web server rights as well. Please move the discussion to the forum. Thanks a lot!

**Comment by stefan-franz** [comment]
I have a fresh installed virtual ubuntu 22.04 server at hetzner.com
Can you tell me, what rights do Mautic need to run? Moodle is also installed - it runs normal. So i think it can be only a little thing. 
Thanks in Advance for your help.

**Comment by dsp76** [comment]
As the discussion moved to the forum and is proceeding there, I will close the issue here.
