### ISSUE TITLE
Classes passed in form attributes are rendered with doubled quotation marks

### ISSUE THREAD

**Issue by Aleen95** [mautic/mautic#13645]
### Mautic Version

5.0.x series

### Way of installing

Other (please specify if relevant in the bug report)

### PHP version

8.1.2

### What browsers are you seeing the problem on?

Chromium

### What happened?

Version: 5.0.4
PHP version: 8.1.2
Installed in a self built docker-image

If you pass classes in the form attributes, they will be rendered in double quotes, breaking the styling.
Conversely, I need to pass the class without quotes (class=foobar instead of class="foobar"). However, this breaks the styling in the previous version of mautic (4.4), which is still in use.

![image](https://github.com/mautic/mautic/assets/120421770/f74257cd-a66a-4d3a-bea7-c9ae244ec1b3)

![image](https://github.com/mautic/mautic/assets/120421770/e3ba0c94-5d2d-4017-b567-207ac5c8f696)

### How can we reproduce this issue?

Step 1: pass a class with quotes like class="foobar" into the form attributes
Step 2: Check the output with the developer-tools

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
Confirmed - altough in my test its slightly different result - overall the same issue:
![image](https://github.com/mautic/mautic/assets/1241376/9a8dd3ea-0a8b-4471-a2f6-f4a2870d4421)

**Comment by escopecz** [comment]
The fix is to test: https://github.com/mautic/mautic/pull/13726. Please help us test this and get it into Mautic 5.1.0
