### ISSUE TITLE
e-Mail Builder - Apply Changes rotates after clicking on endless - Bug. 

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#13649]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.27

### What happened?

In the e-Mail Builder is agreat new feature: Apply changes. 
But after clicking it rotates endless. I think its only a bug in the icon - it seems that it works again if i click again to the rotating circle

### How can we reproduce this issue?

As described

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
@stefan-franz sorry I couldn't recreate it. Could you please move it to the forum first? Thanks!

**Comment by dsp76** [comment]
@stefan-franz if you can describe it a bit more in detail, so it can be recreated, I will reopen it.

**Comment by dsp76** [comment]
It seems to be a duplicate: https://github.com/mautic/mautic/issues/13566
