### ISSUE TITLE
Wrong value for custom field type of Select

### ISSUE THREAD

**Issue by maxitine** [mautic/mautic#1365]
I have a select type custom field named "status", with the value set of "closed", "followup" or "dropped". If no choice is made during the lead input the default value will be "closed".  Is this the right behavour? 

If I want the value to be empty or "undefined", should I add one more option as "undefined"? 

Thanks.

**Comment by escopecz** [comment]
Yes, if you want another/empty option, add one.

**Comment by eirua** [comment]
What if you use a campaign action to update the contact? 

I assume in most cases if the field is empty, Mautic will ignore the update of that field (ie not overwriting submitted names with blank fields). But what Is the default behavior for 'select' field types? 

EG: 
You have a values like selected-1, selected-2, and the 'empty'. When you use action > update contact mid-campaign, will it overwrite mixed select values (selected-1, selected-2,) with the default 'empty' select value? 

Is there a truly undefined value for select that does overwrite default values on action > contact update?

**Comment by escopecz** [comment]
The empty default option will be added in Mautic 2.2.0
