### ISSUE TITLE
Action taken by user could be confusing

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#13657]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8

### What happened?

When reviewing the changes to Mautic 5.1 I noticed a [UX change](https://github.com/mautic/mautic/pull/13495) which could be confusing.

In Mautic:

**User** = person logged into Mautic
**Contact** = visitor/customer who interacts with the output of Mautic.

In Points Actions we have changed the text to be:

**Action taken by user**

What we actually mean is

**Action taken by Contact**

I suggest that this should be changed per the second.

### How can we reproduce this issue?

Step 1: Create a point action and check the wording.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by andersonjeccel** [comment]
Totally makes sense
