### ISSUE TITLE
Content in email builder disappearing when adding image

### ISSUE THREAD

**Issue by zegmaarmanu** [mautic/mautic#13666]
### Mautic Version

5.0.x series

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

Whenever I add an image to a column in the email builder (Tested in all themes) and i save the email, all content that was already present below the inserted image in the column, gets hidden. The content is still there in the code but it's not shown in the builder.
See screen recording:
![chrome_YEMK2yWqPL](https://github.com/mautic/mautic/assets/12908447/c5d939ee-2a20-450c-a74e-4bc81fff9b65)

### How can we reproduce this issue?

Step 1: Select a theme (Brienz, confirm me, paprika) and launch the builder
Step 2: Ad an image element as first position in a column that already has some content in it
Step 3: Exit the builder and save the email
Step 4: Re-open the builder
Step 5: You will come to the conclusion that that only the image is still present in the column while the other content has disappeared.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by markusVJH** [comment]
Do you have the latest version of Mautic? [This bug was addressed](https://github.com/mautic/mautic/pull/13431) for [5.04](https://github.com/mautic/mautic/releases), released last week

https://github.com/mautic/mautic/assets/121946942/16862eda-0fac-49bf-bcdc-da2e6114e633

**Comment by zegmaarmanu** [comment]
Aaaah, thanks, that fixed it indeed. cheers
