### ISSUE TITLE
[UX] Social tab appears blank when there is not info on contact details

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13667]
When a contact does not have social information associated with them, a blank space is shown.
To improve the user experience, we could have a message of "Nothing found", or hide the tab.

How to get there:
1. Open Contacts
2. Create a new
3. Save & Close
4. Click on Details > Social

![Image](https://github.com/mautic/mautic/assets/116097999/f572d41c-ce55-4060-bd32-dfb61b876798)

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by escopecz** [comment]
I'm pretty sure this got fixed by https://github.com/mautic/mautic/pull/12778
![Screenshot 2024-04-19 at 11 04 50](https://github.com/mautic/mautic/assets/1235442/81fe4f1d-6b58-41b2-9d44-c2bd70fc4041)

**Comment by escopecz** [comment]
No, it didn't. I was looking at wrong place.

**Comment by andersonjeccel** [comment]
@nishant-s7 Would you like to fix this one too?

It’s similar to the last PR you did

**Comment by nishant-s7** [comment]
Sure 👍
I'll pick this up after completing the other one

**Comment by nishant-s7** [comment]
What would be better here? Hiding the tab or showing a message saying "Nothing found"?

**Comment by andersonjeccel** [comment]
@nishant-s7 I would hide it
Social tab probably shows something only when a feature like Social Monitoring is activated and generating data

**Comment by RCheesley** [comment]
I agree, as commented when I tested the other PR I found it confusing! https://github.com/mautic/mautic/pull/12778#pullrequestreview-1701763009

**Comment by shinde-rahul** [comment]
This is reproducible.
