### ISSUE TITLE
List filters apply to all leads and not to an existing list

### ISSUE THREAD

**Issue by JephMarketing** [mautic/mautic#1367]
Currently list filters use the entire DB to filter. The problem becomes when you want to apply a filter to a list that is only a segment of the leads DB. For example, a DB can have 10k leads, and 1k can be in a list. Now, one should be able to exclude any emails from the 1k person list that are on a bounce list or any other list. Right now, if I apply a filter to my 1k list, and say exclude emails on the bounce list I get 9k+ leads on the list rather than the original 1k less bounces. 

Essentially, the filter ignores that I am working with a subset of the DB and applies it globally and returns the results. If I had to guess there is a JOIN error. Any help would be greatly appreciated. 

This bug has been confirmed by another user @jt.

**Comment by escopecz** [comment]
Related with https://github.com/mautic/mautic/issues/1374

**Comment by JephMarketing** [comment]
Hi Guys, do I need to add any documentation of the issue, or is there anything I can do to work towards a solution?
