### ISSUE TITLE
Using a colon in an asset title truncates the title in the page builder token listYour bug title goes here!

### ISSUE THREAD

**Issue by solipsist** [mautic/mautic#13676]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.27

### What happened?

Using a colon in the title of an asset makes the token only show the string before that colon, truncating the rest.

![https://global.discourse-cdn.com/business7/uploads/mautic/original/2X/2/2c552adafc846340594d3d86b4db6fd1e108782d.png](https://global.discourse-cdn.com/business7/uploads/mautic/original/2X/2/2c552adafc846340594d3d86b4db6fd1e108782d.png)

![https://global.discourse-cdn.com/business7/uploads/mautic/original/2X/5/567a8ec224cbadc2b7540c6ebbb17398311c387f.png](https://global.discourse-cdn.com/business7/uploads/mautic/original/2X/5/567a8ec224cbadc2b7540c6ebbb17398311c387f.png)

### How can we reproduce this issue?

Step 1: Create an asset with a title containing a colon.
Step 2: Confirm that the token for that asset is truncated.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
Confirmed... is recreatable.

**Comment by RCheesley** [comment]
Please test the PR https://github.com/mautic/mautic/pull/13678 @solipsist @dsp76 as it should resolve this issue for you. Thanks!

Docs on how to test can be found at https://mau.tc/tester - you can do it in the browser.
