### ISSUE TITLE
Email Redirect In Email Message Defaults To http://localhost/r/UNIQUE_RANDOM_TOKEN

### ISSUE THREAD

**Issue by TK37** [mautic/mautic#1368]
For some reason when emails are delivered, all of the links in the email are being redirected to "localhost/r/UNIQUE_RANDOM_TOKEN". However, if I replace the site where mautic is hosted manually in place of "localhost" in the browser it works perfect. 

I know I am missing a setting or something somewhere where the site name can be placed automatically. Any help is appreciated.

**Comment by escopecz** [comment]
I guess you are the same person who asked this question in the Slack chat twice. The answer is, add the new site URL to the configuration, field called *Site URL*.

Again, please, ask your question only at one place. This is very impolite for people who answers the questions and take the precious time to you and me (or others who would answer the same question X times)
