### ISSUE TITLE
Upgrade using reinstall(composer install) broken - Uncaught TypeError: mQuery.FroalaEditor is undefined

### ISSUE THREAD

**Issue by ashishbhatiya18** [mautic/mautic#13682]
### Mautic Version

5.0.x series

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Firefox

### What happened?

I see this error on page load and dashboard is infinitely loading:
```
Uncaught TypeError: mQuery.FroalaEditor is undefined
    activateGlobalFroalaOptions https://c.citrusdental.in/media/js/app.js?v35dc57d8:388
    onPageLoad https://c.citrusdental.in/media/js/app.js?v35dc57d8:73
    <anonymous> https://c.citrusdental.in/s/dashboard line 1 > injectedScript:2
    activateScript https://c.citrusdental.in/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    n https://c.citrusdental.in/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    run https://c.citrusdental.in/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    n https://c.citrusdental.in/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    s https://c.citrusdental.in/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
```

### How can we reproduce this issue?

Step 1: execute `composer create-project mautic/recommended-project:^5 html-new --no-interaction --ignore-platform-req=ext-imap`
Step 2: Move local.php from old installation to docroot/app/config directory and set appropriate ownership
Step 3: Load UI after server restart and see this not progressing.
<img width="1468" alt="image" src="https://github.com/mautic/mautic/assets/986655/e2b426f1-ccc7-4176-9704-dcd5c867fe13">
Step 4: Open Inspect view and see this issue
<img width="1055" alt="image" src="https://github.com/mautic/mautic/assets/986655/7eda2b44-e7d7-4513-a5a0-b956874772c6">

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by ashishbhatiya18** [comment]
Migration was done prior to this execution.

**Comment by RCheesley** [comment]
Hi there, have you tried:

1. Clearing your cache 
2. Regenerating your assets with `bin/console m:a:g`

Please post issues like this at https://forum.mautic.org/c/support in the future, as that's where we help with troubleshooting install/update/config issues, whereas GitHub is for reporting bugs with Mautic. Thanks!
