### ISSUE TITLE
Segment not showing number of contacts (on list view)

### ISSUE THREAD

**Issue by RabeeBrahimi** [mautic/mautic#13691]
### Mautic Version

4.4.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

7.4

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

Segments not showing the number of contacts on the (# contacts) column on list view. Although the segment cron is working and segment with filter works fine, when i click on (No Contacts) i can see the list of the contacts related to the segment i have clicked on. Just the Ui not showing the number of contacts, and it only show the number of contacts for manually modified segment, e.g i have a retired list segment, when i receive an email from a lead saying they're retired i manually move them to this segment and this segment show the number of contacts on the list view properly - also works when importing contacts directly to a segment. 

### How can we reproduce this issue?

Step 1: Not really sure, may be install mautic version 4.4.10 and use php 7.4 (For your info i have tried php 8.0 and still same issue).
Step 2: Import contacts
Step 3: create a segment with filter and check if the contacts number is updated - also you check you can still see the filter works fine and contacts have been added to the segment but only contacts number on list is not shown. 

### Relevant log output

```shell
There is nothing in the log, everything works fine in the instance expect this part which is tricky.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems. I'm not able to reproduce this, maybe try clearing your cache in case something is cached?

**Comment by RabeeBrahimi** [comment]
Thanks @RCheesley 
I will try to clear cache.

**Comment by HN-PRO** [comment]
> Thanks @RCheesley I will try to clear cache.

I have the same problem, is there any progress?

**Comment by RCheesley** [comment]
> I have the same problem, is there any progress?

As above, please clear the Mautic cache. If it doesn't help, post on https://forum.mautic.org which is where support is provided and folks can help to troubleshoot with you and if necessary then raise a new bug as detailed above in the message about commenting on closed issues. Thanks
