### ISSUE TITLE
Recaptcha is not included for data capture forms in Focus Items

### ISSUE THREAD

**Issue by ablack-idg** [mautic/mautic#13694]
### Mautic Version

4.4.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

7.4.33

### What browsers are you seeing the problem on?

Not relevant

### What happened?

We noticed that a data capture focus item didnt work and captcha would fail. The mautic form itself would work when done on its own i.e not inside the Focus Item.  Looking at the code it appeared that the recaptcha plugin is removed from the form i.e no recaptcha js or token form field so basically the response from the server is always a failure.

When experimenting we noticed that if you dont do the focus item as data capture and inlude the js automatic script for the form in the html block it did sort of work with the caveats that a)  the background to the overlay doesnt display and b) oddly recaptcha only worked 50% of the time whereas for just the plain form it was 100%.

### How can we reproduce this issue?

Step 1: Add the recaptcha plugin
Step 2: Create a form with 1 field and a recaptcha field
Step 3: Create a Data Capture Focus Item ( we did animate and scroll to middle on every page) and specify the form created.
Step 4: Add the domain to the supported domains for the recaptcha.
Step 5: Create a landing page and test just the form using automatic js only - should work
Step5: Create a landing page and test the focus item only - recaptcha elements (js and form field) will be missing in the rendered source code when the focus item displays.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there,

As this relates to a third party plugin (as far as I can understand) could you please reach out to the maintainer of that plugin in the first instance? In this repo we only deal with core Mautic and the plugins that ship with it. 

If the maintainer finds it to be an issue with core Mautic, have them raise an issue and document their troubleshooting and we can pick it up from there. Thanks!
