### ISSUE TITLE
Custom image disappears after editing contact

### ISSUE THREAD

**Issue by igordisco** [mautic/mautic#13692]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When a lead fills out a form and it already exists in the database, their personalized avatar disappears and returns to Gravatar.

I have some contacts that I uploaded a customized image to be standardized with WhatsApp, but when the contact fills in another landing page, he loses the image.

### How can we reproduce this issue?

Step 1: Edit a contact and insert a custom image. As soon as this contact has a personalized and "custom" image in the database, he loses this image and returns to "custom" when filling out a new form.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi @igordisco I am trying to reproduce this on the 5.x branch but not getting the same results - for me the image is remaining as I'd expect it to.

Could you possibly share a screencast which demonstrates this in action?

I did the following:

1. Create a contact
2. Add a custom image
3. Fill out a form using the email address which matched the contact's email address
4. Image remains as uploaded after submission - not returning to what it was.

I tried with test@example.com and also my own address which has an image associated on Gravatar, and neither of them resulted in the image being reset.

**Comment by RCheesley** [comment]
Closing due to lack of response and inability to reproduce the issue. Feel free to request a re-open if this is still a problem.
