### ISSUE TITLE
Bug - New campaign created with already an history

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1370]
Hi guys,

**I just created a new campaign (today) and it used an "old" ID** (i mean already used by a deleted campaign). Until now, i have no issue with that.
*EDIT: Obviously it has erased a previous campaign :-1: That starts to create an issue for me :cry:*

But what i see:
* I just (few minutes ago) created this campaign
* There already is an **old history (lead qualified, created by another user...)**.

Check attached screenshot of the campaign.
![capture d ecran 2016-01-20 a 12 19 42](https://cloud.githubusercontent.com/assets/14075239/12447412/53348946-bf70-11e5-8d6c-bffb1160eb75.png)

N.

**Comment by escopecz** [comment]
This could be possibly fixed with https://github.com/mautic/mautic/pull/1566 . Could you confirm?
