### ISSUE TITLE
Mautic 504 error | emails not send | send only to some users

### ISSUE THREAD

**Issue by cremigerhonig** [mautic/mautic#13701]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.28

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Mautic v5.0.4

Not sending Segment emails
once I start sending the progress bar does not move
after some time "your request could not be processed" is shown

if I check the email I tried to send, it send some emails but not all. 
The number "pending" decreased, so some emails has been sent but not all of them

Also it shows "0 emails sent" which is not correct as it send some emails

I dont know what is going on.

Also the "auto create text version" of email is not working.

everything was working fine before mautic 5
not its a mess

also its not possible to set "email batch size" at all. there is no option. I have no Idea why. Is this the reason?

### How can we reproduce this issue?

update your mautic to 5

### Relevant log output

```shell
nothing found in logs
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems. If the issues are causing problems and you are using this instance of Mautic in production, please roll back to your backup of Mautic 4.
