### ISSUE TITLE
Broken tooltip

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#13703]
### Mautic Version

5.0.x series

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8

### What happened?

I noticed a broken tooltip on the landing page builder.

![screenshot-mautic ddev site-2024 04 29-16_25_10](https://github.com/mautic/mautic/assets/2930593/db76116f-c276-4949-8d10-241a96127f21)

### How can we reproduce this issue?

Step 1: Open a new landing page
Step 2: Check for the HTML which should be within the tooltip.

@andersonjeccel one of the UX improvements I think - does it make sense to include a link in a tooltip if it disappears when you move the mouse? Just a thought!

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by andersonjeccel** [comment]
I strongly believe my PRs haven’t caused this issue as they were always tested by me and others, working fine before merged 🤔

**Comment by andersonjeccel** [comment]
@RCheesley 
Had a look, nothing changed by me there
It's working fine

![image](https://github.com/mautic/mautic/assets/116097999/9315cd83-0964-4282-947b-91c2fb6ef18f)

**Comment by andersonjeccel** [comment]
And yeah, doesn't make sense to have a link in tooltips
We implemented a feature recently through Tim's pull request which allows us to add links or just extra anything below the fields

**Comment by andersonjeccel** [comment]
Seems fixed
