### ISSUE TITLE
Form action url should start with https://, but actually start with http://, it results in not secure and mixed content warning in wordpress page

### ISSUE THREAD

**Issue by jackpassgfw** [mautic/mautic#13717]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What happened?

A bug happened!
![image](https://github.com/mautic/mautic/assets/4837026/7d7e15c6-dc66-474c-ac76-b727ae067b8e)
![image](https://github.com/mautic/mautic/assets/4837026/4318f3f6-2d34-48f6-8012-7434236dad57)
![image](https://github.com/mautic/mautic/assets/4837026/70d9fff8-ba4d-44e7-93b7-ab9e0fbd7602)

### How can we reproduce this issue?

Step 1: Create a form in Mautic
Step 2: Add <script type="text/javascript" src="//mymauticsite.com/form/generate.js?id=yourformid"></script> in wordpress page
Step 3: Run the page in a browser

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems with your configuration :)
