### ISSUE TITLE
Feature request - Add "exclude contact list" from a campaign lead source

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1371]
Hi,

It's be great to be able **-from a list selected campaign- to exclude lists**.
Today, we can only select lists.
![capture d ecran 2016-01-20 a 16 21 46](https://cloud.githubusercontent.com/assets/14075239/12453139/28d7a918-bf92-11e5-9ae1-2bbb520f7a4c.png)

**The result would be:**
* Select your lead lists: *list_name*
* Exclude lead lists: *list_name*

It would help to do not create lists and lists and lists by simply being able to exclude contacts.

N.

**Comment by alanhartless** [comment]
The current way to do this is to build a segment that filters out contacts that belong to the excluded segment.

**Comment by npracht** [comment]
Hi @alanhartless,

I agree with you and this is what we're all doing today, but it is something not intuitive at all (this is what you'll find in any other marketing automation soft.).
It would be a great UX improvement, i would consider it better :-)

Have a nice day,

N.
