### ISSUE TITLE
EmailValidator.php - Argument #1 ($emailAddress) must be of type string, null given

### ISSUE THREAD

**Issue by wsarisslz** [mautic/mautic#13728]
### Mautic Version

5.0.x series

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.1.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

When creating a new campaign for a segment (which only has IP Addresses in this case) and you choose CONDITION: if email is valid

then you get the following error when executing mautic/bin/console mautic:campaigns:trigger

Triggering events for campaign 9
Triggering events for newly added contacts
2458 total events(s) to be processed in batches of 100 contacts
 2458/2458 [============================] 100%
In InvalidEmailException.php line 9:
                                                                                                                                                       
  Mautic\EmailBundle\Exception\InvalidEmailException::__construct(): Argument #1 ($emailAddress) must be of type string, null given, called in /var/w  
  ww/html/mautic/docroot/app/bundles/EmailBundle/Helper/EmailValidator.php on line 30                                                                  
                                                                                                    

### How can we reproduce this issue?

Step 1: create a segment with IP's without an email address
Step 2: create a campaign that has a condition if valid email

### Relevant log output

```shell
Triggering events for campaign 9
Triggering events for newly added contacts
2458 total events(s) to be processed in batches of 100 contacts
 2458/2458 [============================] 100%
In InvalidEmailException.php line 9:
                                                                                                                                                       
  Mautic\EmailBundle\Exception\InvalidEmailException::__construct(): Argument #1 ($emailAddress) must be of type string, null given, called in /var/w  
  ww/html/mautic/docroot/app/bundles/EmailBundle/Helper/EmailValidator.php on line 30
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for raising the bug @wsarisslz - hopefully we can get someone to take a look at it soon!
