### ISSUE TITLE
Error install mautic on Ubuntu "Unable to create the cache directory (/var/www/html/mautic/app/cache/prod)"

### ISSUE THREAD

**Issue by BaVanDuong** [mautic/mautic#1373]
I tried install mautic on Ubuntu 14.04 (apache 2.4, php 5.5.9) but it raise error below:
[Thu Jan 21 13:44:30.291012 2016] [:error] [pid 2600] [client ******:42478] exception 'RuntimeException' with message 'Unable to create the cache directory (/var/www/html/mautic/app/cache/prod)\n' in /var/www/html/mautic/app/AppKernel.php:520\nStack trace:\n#0 /var/www/html/mautic/app/AppKernel.php(488): AppKernel->buildContainer()\n#1 /var/www/html/mautic/app/AppKernel.php(252): AppKernel->initializeContainer()\n#2 /var/www/html/mautic/app/AppKernel.php(71): AppKernel->boot()\n#3 /var/www/html/mautic/index.php(56): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#4 {main}

Please help me fix this issuse.

**Comment by escopecz** [comment]
> Unable to create the cache director

Seems like a folder permission issue. Check the permission and the owner. The default owner should be www-data.
