### ISSUE TITLE
Update from Mautic 4.4.11 to 5.0.4 fails - memory exhausted

### ISSUE THREAD

**Issue by Thari0** [mautic/mautic#13738]
### Mautic Version

4.4.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0.30

### What browsers are you seeing the problem on?

Chrome

### What happened?

When updating in console to mautic 5.0.4 the apply --finish command fails with the memory exhausted.

Db: 10.5.17-MariaDB
Php: 8.0.30
memory_limit: 8192M
max_execution_time: 15000

I have quite old installation dating back to mautic 2, would really like to not loose all the data or be stuck on the old version of mautic. Its the first time i'm having such a hard time with an update.
Tried different php versions, with and without doctrine:migrations:migrate beforehand, but the update always breaks with php error.

### How can we reproduce this issue?

The mautic:update:apply works, but the second stage with the --finish throws such error:

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2461696 bytes) in /home/klient.dhosting.pl/thario/test/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1607

### Relevant log output

```shell
I dont see anything relevant in the log regarding this problem.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
