### ISSUE TITLE
I want integrate linkedin to mautic 

### ISSUE THREAD

**Issue by ijaobulammma** [mautic/mautic#13740]
### Mautic Version

4.4.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.0.30

### What happened?

My Mautic version is:v4.4.10
My PHP version is: 8.0.30
My Database type and version is: 8.0.35-0ubuntu0.22.04.1

Your problem
My problem is:

Hello Guys

I am new in mautic.

This is good tool for digital marketing.

I want to integrate social media in mautic.

I want to also integrate linkedin in mautic.

I got error in linkedin Authorization failed with the error message, ‘{“error”:“invalid_request”,“error_description”:“A required parameter "code" is missing”}’
Please anybody can help me
![Screenshot (109)](https://github.com/mautic/mautic/assets/118726803/d2326cc7-e2b1-4afa-9eeb-56115cfcf701)
![Screenshot (110)](https://github.com/mautic/mautic/assets/118726803/9e937fd4-a79c-4cc6-9062-fea7556a9180)

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
Hi @ijaobulammma - welcome to Mautic! 
Could you please start this as a support discussion in the Mautic forum? 
https://forum.mautic.org/

An issue should be a supported feature thats broken and can be recreated. This is more a support request.
