### ISSUE TITLE
Uncaught PHP exception when email links are converted

### ISSUE THREAD

**Issue by GrapeCityDan** [mautic/mautic#1375]
I started this conversation in the Mautic forums, but I think I confused the issue a little and it is looking like it is better for this channel anyway...

PHP 5.5.9
Ubuntu SErver 14.04.1
Apache 2.4.7
Mautic 1.2.3

* I built a new server and installed Mautic. The first thing I did was send a test email with a link to a random website in it to myself. 
* When I click on the link in the email I get a Mautic Error 500 page.  Error deatils are a the end of this post.
* The converted link is http://gcgo.to/mautic/index.php/r/6d00fb75effd10d47b03faaae?ct=YTo0OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6Mjt9czo1OiJlbWFpbCI7aToyO3M6NDoic3RhdCI7czoxMzoiNTY5ZmViOGQxMzBjYiI7czo0OiJsZWFkIjtpOjE7fQ%3D%3D 
* If I replace our domain, gcgo.to, with the server's local IP address, the link works. 

Here are the error details:

[2016-01-20 21:23:55] mautic.NOTICE: PHP Notice: unserialize(): Error at offset 261 of 265 bytes - in file /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php - at line 58 [] []
[2016-01-20 21:23:55] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Could not convert database value "a:11:{s:4:"city";s:0..." to Doctrine Type array" at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php line 46 {"exception":"[object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Could not convert database value \"a:11:{s:4:\"city\";s:0...\" to Doctrine Type array at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php:46)"} []

**Comment by escopecz** [comment]
Could you provide the steps to recreate the issue?

**Comment by GrapeCityDan** [comment]
Sure. 

I also left out a key piece of info. I am using PostGreSQL 9.3.10

* Create new list email - no theme
* Subject: Test  /  Content is just a link: http://www.google.com
* List is two emails (one Gmail and one Exchange)
* Send
* Click on link when email is received
* Get Mautic's 500 Internal Server Error page

Log:
[2016-01-22 14:48:43] mautic.NOTICE: PHP Notice: unserialize(): Error at offset 261 of 265 bytes - in file /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php - at line 58 [] []
[2016-01-22 14:48:43] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Could not convert database value "a:11:{s:4:"city";s:0..." to Doctrine Type array" at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php line 46 {"exception":"[object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Could not convert database value \"a:11:{s:4:\"city\";s:0...\" to Doctrine Type array at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php:46)"} []

**Comment by escopecz** [comment]
Tested by the provided steps. The link sent in the email works for me. I'm using PostgreSQL 9.4.5, PHP 5.6.4

**Comment by GrapeCityDan** [comment]
Thanks for looking. We are stumped. Will keep digging.

**Comment by GrapeCityDan** [comment]
We think this may be a problem with accessing PostgreSQL. Does anyone know of anything out of the ordinary that needs to be done in the pg_hba.conf file?

**Comment by escopecz** [comment]
I didn't edit anything in pg_hba.conf file, so it must be all default and it works for me.

**Comment by GrapeCityDan** [comment]
We figured out the problem by finding some of the text from the eror code (a:11:{s:4:"city";s:7) in the database. Turns out that the "MaxMind - GeoIP2 City Download" IP lookup service was the culprit. We disabled the service and deleted the data from the ip_addresses table and the links started working. 

Now we have to see if we can get one of the oither services working.

**Comment by GrapeCityDan** [comment]
Looks like we may have uncovered a separate, but related bug. Not sure if you want me to put this in new thread, but here goes. 

* We emptied the ip_adresses table
* Clicked a pre-existing link in an email that was created per the steps in this thread.
* Link worked, but a subsequent click by anybody results in the same internal server error this thread discusses.

The data that gets enetered into the ip_detailstext field of the ip_addresses table on that first click looks like this: a:14:{s:4:"city";s:7:"Raleigh";s:6:"region";s:14:"North Carolina";s:7:"zipcode";s:5:"27609";s:7:"country";s:13:"United States";s:8:"latitude";d:35.843000000000004;s:9:"longitude";d:-78.631100000000004;s:3:"isp";s:0:"";s:12:"organization";s:0:"";s:8:"timezone";s:16:"America/New_York";s:5:"extra";s:0:"";s:9:"connector";O:16:"Joomla\Http\Http":2:{s:10:"

And that is the data that the server error refers to. 

Once that data exists in the table, links no longer work.

Could this be a bug specific to PostgreSQL?

**Comment by fabiants** [comment]
I have the same problem but nessesarily connected to the emails but rather tracking in general.

**Comment by GrapeCityDan** [comment]
I found that the problem existed in all form of tracking that involved the IP lookup features.

The only thing that work is not disable IP Lookup

On Jan 29, 2016, at 2:16 PM, fabiants <notifications@github.com<mailto:notifications@github.com>> wrote:


I have the same problem but nessesarily connected to the emails but rather tracking in general.

-

**Comment by jkuchar** [comment]
I'm getting the same error when I've sent clear e-mail and now trying to access tracking pixel. (error 500)

It is basically fresh install. v1.2.4

```
PHP 5.6.18-1+deb.sury.org~trusty+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

PostgreSQL 9.5.1 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit
```

```
[2016-02-12 16:07:54] mautic.NOTICE: PHP Notice: unserialize(): Error at offset 328 of 332 bytes - in file /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php - at line 58 [] []
[2016-02-12 16:07:54] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Could not convert database value "a:11:{s:4:"city";s:4..." to Doctrine Type array" at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php line 46 {"exception":"[object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Could not convert database value \"a:11:{s:4:\"city\";s:4...\" to Doctrine Type array at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php:46)"} []
```

**Comment by jkuchar** [comment]
My geo data looks like this:
```
a:11:{s:4:"city";s:4:"Brno";s:6:"region";s:10:"Mesto Brno";s:7:"zipcode";N;s:7:"country";s:14:"Czech Republic";s:8:"latitude";d:49.200000000000003;s:9:"longitude";d:16.633299999999998;s:3:"isp";s:0:"";s:12:"organization";s:0:"";s:8:"timezone";s:13:"Europe/Prague";s:5:"extra";s:0:"";s:9:"connector";O:16:"Joomla\Http\Http":2:{s:10:"
```

It looks that there is something wrong with serializer which creates this broken output.

**Comment by GrapeCityDan** [comment]
That is what is causing the error. I fixed it by clearing that table and disabling IP location services

**Comment by jkuchar** [comment]
Yep, but that is not causing the problem. Interesting is that it is not happenning on my local instance running on PHP 5.5, Windows, Postgre 9.3

**Comment by GrapeCityDan** [comment]
Yeah, we haven’t found the root of the problem. We just know everything works if we do what I mentioned.

Our’s works when using a local IP address. It breaks when we use external IP address or public URL.

**Comment by jkuchar** [comment]
So I've set up XDebug remote session to server and found that full (non broken string looks like this)

```
a:11:{s:4:"city";s:4:"Brno";s:6:"region";s:10:"Mesto Brno";s:7:"zipcode";N;s:7:"country";s:14:"Czech Republic";s:8:"latitude";d:49.200000000000003;s:9:"longitude";d:16.633299999999998;s:3:"isp";s:0:"";s:12:"organization";s:0:"";s:8:"timezone";s:13:"Europe/Prague";s:5:"extra";s:0:"";s:9:"connector";O:16:"Joomla\Http\Http":2:{s:10:" * options";a:0:{}s:12:" * transport";O:26:"Joomla\Http\Transport\Curl":1:{s:10:" * options";a:0:{}}}}
```

Interesting is that if I "copy value as print_r" in XDebug i get:
```
a:11:{s:4:"city";s:4:"Brno";s:6:"region";s:10:"Mesto Brno";s:7:"zipcode";N;s:7:"country";s:14:"Czech Republic";s:8:"latitude";d:49.200000000000003;s:9:"longitude";d:16.633299999999998;s:3:"isp";s:0:"";s:12:"organization";s:0:"";s:8:"timezone";s:13:"Europe/Prague";s:5:"extra";s:0:"";s:9:"connector";O:16:"Joomla\Http\Http":2:{s:10:"
```

"copy value as var_export"
```
'a:11:{s:4:"city";s:4:"Brno";s:6:"region";s:10:"Mesto Brno";s:7:"zipcode";N;s:7:"country";s:14:"Czech Republic";s:8:"latitude";d:49.200000000000003;s:9:"longitude";d:16.633299999999998;s:3:"isp";s:0:"";s:12:"organization";s:0:"";s:8:"timezone";s:13:"Europe/Prague";s:5:"extra";s:0:"";s:9:"connector";O:16:"Joomla\\Http\\Http":2:{s:10:"' . "\0" . '*' . "\0" . 'options";a:0:{}s:12:"' . "\0" . '*' . "\0" . 'transport";O:26:"Joomla\\Http\\Transport\\Curl":1:{s:10:"' . "\0" . '*' . "\0" . 'options";a:0:{}}}}'
```

@escopecz Look at that there are \0 (null byte) characters! What, why?!

**Comment by mbabker** [comment]
When PHP serializes an object protected and private class member names are wrapped in null byte characters.  http://php.net/manual/en/function.serialize.php

**Comment by jkuchar** [comment]
Got it! Serialized private property. http://php.net/manual/en/function.serialize.php

```
Object's private members have the class name prepended to the member name; protected members have a '*' prepended to the member name. These prepended values have null bytes on either side.

Note that this is a binary string which may include null bytes, and needs to be stored and handled as such. For example, serialize() output should generally be stored in a BLOB field in a database, rather than a CHAR or TEXT field.
```

So two things comes out:
1) stored value in PostgreSQL must be BLOB to store serialized objects.
2) we need to encode values using base64 or such encoding

**Comment by jkuchar** [comment]
It looks like an bug in Doctrine.

PostgreSqlPlatform declares files in Postgres as Text
```php
    /**
     * {@inheritDoc}
     */
    public function getClobTypeDeclarationSQL(array $field)
    {
        return 'TEXT';
    }
```

but in Doctrine\DBAL\Types\ArrayType they are assuming that convertToDatabaseValue will be UTF-8 valid string.

```php
    /**
     * {@inheritdoc}
     */
    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        // @todo 3.0 - $value === null check to save real NULL in database
        return serialize($value);
    }
```

**Comment by jkuchar** [comment]
Root cause of the problem is that 
Mautic\CoreBundle\IpLookup\AbstractLookup::getDetails()
```php
$details = call_user_func('get_object_vars', $this); 
```

returns also private and protected members (tested on PHP5.6).

This unexpected behaviour is describers here. http://php.net/manual/en/function.get-object-vars.php#83078

Should I use reflection to fix this problem or create that function in namespace?

**Comment by jkuchar** [comment]
To be consistent across all supported PHP versions I've chosen to use Reflection. To prevent invalid data being saved into database I've added check into Doctrine ArrayType. Do you want to have regression tests for this? (I do not see Travis CI in this repo)

**Comment by escopecz** [comment]
There is no automated testing system configured for Mautic yet, but if you wish to provide a test for your PR (Thanks a lot BTW!), it would be welcome since tests are something the core developers want to focus on in the near future. Example tests are for example here: https://github.com/mautic/mautic/tree/staging/app/bundles/CoreBundle/Tests/IpLookup

**Comment by jkuchar** [comment]
1) Thanks a lot for developing Mautic!
2) I will post tests for this little bit later because I need to learn set up PHPUnit (we use Nette\Tester internally) (another PR?)
3) (Shouldn't ArrayType null-check go into Doctrine's codebase?)

This fix should go into production ASAP because original version 1.2.4 breaks data in database. Ideally there should be migration script that will remove all broken values from database. Or ArrayType should return empty array on serialization error + log exception. Any opinions?
