### ISSUE TITLE
When clicking save, save & close or cancel the screen is stuck on the same screen

### ISSUE THREAD

**Issue by andre-mha** [mautic/mautic#13760]
### Mautic Version

5.0.x series

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.1.27

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What happened?

When clicking "save & close" or "cancel" within certain parts of Mautic it saves the data/changes or cancels but gets stuck loading. Regardless of how long the page is left to process it won't move on to the next page. An error is produced in console, no errors are produced within Mautic and does not generate any logs. To go back I have to remove the "/edit/{id}" from the address bar.

[video-convert-1715941458619.webm](https://github.com/mautic/mautic/assets/170093169/3c19af36-b550-411d-b387-d587bc95c14c)

### How can we reproduce this issue?

Step 1: Click edit on a form/asset/campaign
Step 2: Make any change
Step 3: Click save/save & close/cancel

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'data-ck-expando')
    at emittermixin.js:226:12
    at Wn (emittermixin.js:232:14)
    at Ro._getProxyEmitter (emittermixin.js:58:48)
    at emittermixin.js:71:35
    at Array.map (<anonymous>)
    at Ro._getAllProxyEmitters (emittermixin.js:71:15)
    at Ro.stopListening (emittermixin.js:36:44)
    at Ro.destroy (focustracker.js:74:14)
    at Zg.destroy (editorui.js:83:27)
    at Zg.destroy (classiceditorui.js:77:15)
(anonymous)	@	emittermixin.js:226
Wn	@	emittermixin.js:232
_getProxyEmitter	@	emittermixin.js:58
(anonymous)	@	emittermixin.js:71
_getAllProxyEmitters	@	emittermixin.js:71
stopListening	@	emittermixin.js:36
destroy	@	focustracker.js:74
destroy	@	editorui.js:83
destroy	@	classiceditorui.js:77
destroy	@	classiceditor.js:82
(anonymous)	@	app.js?vd266018b&ve5d8ae6c:89
Mautic.onPageUnload	@	app.js?vd266018b&ve5d8ae6c:89
Mautic.processPageContent	@	app.js?vd266018b&ve5d8ae6c:54
(anonymous)	@	app.js?vd266018b&ve5d8ae6c:282
success	@	app.js?vd266018b&ve5d8ae6c:288
options.success	@	libraries.js?vd266018b&ve5d8ae6c:1626
fire	@	libraries.js?vd266018b&ve5d8ae6c:271
fireWith	@	libraries.js?vd266018b&ve5d8ae6c:276
done	@	libraries.js?vd266018b&ve5d8ae6c:667
(anonymous)	@	libraries.js?vd266018b&ve5d8ae6c:680
load (async)		
send	@	libraries.js?vd266018b&ve5d8ae6c:680
ajax	@	libraries.js?vd266018b&ve5d8ae6c:658
$.fn.ajaxSubmit	@	libraries.js?vd266018b&ve5d8ae6c:1628
Mautic.postForm	@	app.js?vd266018b&ve5d8ae6c:284
Mautic.postMauticForm	@	app.js?vd266018b&ve5d8ae6c:282
(anonymous)	@	app.js?vd266018b&ve5d8ae6c:281
dispatch	@	libraries.js?vd266018b&ve5d8ae6c:388
elemData.handle	@	libraries.js?vd266018b&ve5d8ae6c:374
trigger	@	libraries.js?vd266018b&ve5d8ae6c:608
(anonymous)	@	libraries.js?vd266018b&ve5d8ae6c:610
each	@	libraries.js?vd266018b&ve5d8ae6c:98
each	@	libraries.js?vd266018b&ve5d8ae6c:89
trigger	@	libraries.js?vd266018b&ve5d8ae6c:610
jQuery.fn.<computed>	@	libraries.js?vd266018b&ve5d8ae6c:711
buttonClick	@	app.js?vd266018b&ve5d8ae6c:71
dispatch	@	libraries.js?vd266018b&ve5d8ae6c:388
elemData.handle	@	libraries.js?vd266018b&ve5d8ae6c:374
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there,

This is most often resolved with the rebuilding of Mautic assets. Please try `bin/console m:a:g` and hopefully that will fix the issue. Also verify your permissions are set correctly. Please post on https://forum.mautic.org if you need any further help troubleshooting this issue.
