### ISSUE TITLE
"Send example" emails are added to the queue

### ISSUE THREAD

**Issue by arpesenti** [mautic/mautic#1376]
When I am preparing an email, I want to test how it would appear in an email client, I use "Send example" to do that. If mautic is configured to send email with a queue, example emails are queued and are not sent immediately. This is a problem when the queue is big... 
Could it be possible to send examples synchronously instead of queuing?
As a stopgap, is it possible to send a specific message in the queue with mautic:email:process?

**Comment by Running-On-Empty** [comment]
This would be a welcome feature.  When I make changes to emails I have to go edit my cron jobs to run every 15 minutes.  If there are emails sitting in the Queue they are sent out at that time.  Which is not ideal for me.

Sending example emails immediately would be an excellent feature.

**Comment by wittwerch** [comment]
It introduces another problem: If the sending of the example email fails you are not notified about that.

**Comment by escopecz** [comment]
Implemented in 2.5
