### ISSUE TITLE
new mails to existing campaign

### ISSUE THREAD

**Issue by OlafDammann** [mautic/mautic#1377]
hi all
I refer to this post: https://github.com/mautic/mautic/issues/842 and this Part:
>What happens if you make changes to actions at a point the future of where people are example, lead has been in campaign for 5 days, you add a "send email" to the campaign with a wait of 10 days)?

>>If the actions are connected into a decision the lead has not executed yet, they will receive the email in 10 days from the point of executing that decision. If the send email is at the root of the campaign, they will not receive the email as the system considers them as already passed that point in the drip flow. 

To me this looks a bit nogo for a Mail Automation tool (And mybe I yust didn't got the concept). I send a letter to my subscribers there and then. I thought I just add a new mail to an existing campaign being connected with my list. This is how I do it in ActiveCampaign today. 
How can I do this in Mautic? The existing descissions don't work for, maybe a new one called "mail send to Lead" would do it.
Thanks for any thoughts

You guys did an aswome job!
OLAF

**Comment by ivgalic** [comment]
I ran into the same issue and would also love for this to be supported (to be able to add emails to a campaign and have existing members of the campaign pick up on it).

But in the meantime, with what you're describing, if it's just "send a letter to your subscribers there and then", and it shouldn't be a part of a timed or decision-based campaign, you can simply send a one-off email. Maybe I just didn't get what you're trying to do though.

**Comment by OlafDammann** [comment]
Hi Ivan
yes, that would work, I think. Need to check this, because I was very focussed on campaigns. Not sure, if I can do the cool stuff with this like "If this link's been klicked, add the lead to that group and send him next time that mail". 
Even if this works: I do courses with my folks, those are supported by a mail every morning (-> campaign). Then I find out, that a Mail in the evening need to be added, maybe because some of their feedback or so. This then requires a second campaing or a Mail as you described. that breaks the picture and I don't have a full overview of the activities of the people. Makes more sense?
Thanks for your response!
OLAF

**Comment by ivgalic** [comment]
Definitely, for something like a course or any other kind of "living campaign" it can be very useful to be able to add emails.

I was just suggesting a simple fix for the situation where you want to send an ad-hoc email.

**Comment by tadinski** [comment]
adding emails to an existing campaign is still not possible, and a very much need feature
