### ISSUE TITLE
Duplicate Lead when importing CSV w/ no email and having a line break within a cell 

### ISSUE THREAD

**Issue by hansakoch** [mautic/mautic#1379]
line breaks in a CSV (exported Google sheet to csv) seems to create a duplicate lead from a lead without an email.
I manually removed all line breaks in all cells and this fixed the issue.

**Comment by escopecz** [comment]
Could you provide an example CSV file so we could test the issue?

**Comment by hansakoch** [comment]
[test additional lines mautic.zip](https://github.com/mautic/mautic/files/102950/test.additional.lines.mautic.zip)

**Comment by escopecz** [comment]
I see. Well, if I quote wikipedia:

> CSV is a delimited data format that has fields/columns separated by the comma character and records/rows terminated by newlines.

*https://en.wikipedia.org/wiki/Comma-separated_values#Basic_rules*

So basically, your CSV file has records on multiple rows. Not sure if we should declare your CSV as corrupted and leave it be or if we should fix it somehow. The line breaks are within double quotes so it should be OK. Any thoughts from others?
