### ISSUE TITLE
SAML login shows 'Unknown inResponseTo' error when logging in

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#13808]
Identified when testing #13742 (see instructions there for mocking a local SAML server for testing locally)

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.05.31-13_56_24.webm](https://github.com/mautic/mautic/assets/2930593/6ffeef98-29fc-406e-a9e2-b355b9ecee1e)

Here's a screencast. I get to the Mautic login screen with the error, then I use the back button (on my mouse) and it goes back to the SAML (URL is http://localhost:8080/simplesaml/saml2/idp/SSOService.php?spentityid=https%3A%2F%2Fmautic.ddev.site&cookieTime=1717160195) and then logs into Mautic.

_Originally posted by @RCheesley in https://github.com/mautic/mautic/issues/13742#issuecomment-2142079751_
            

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by jonathandhn** [comment]
Actually, this bug is still here in 5.1.1.

With Google workspace, init SAML request browsing mautic, fails, init SAML request from the Google workspace side, suceed.

**Comment by RCheesley** [comment]
Thanks @jonathandhn - it will remain until someone fixes it, unfortunately. Thus far, nobody has stepped up to tackle it.  Feel free to add some funds to the bounty pot if you'd like us to try to find a developer to work on it faster by funding them!

**Comment by iambigred** [comment]
I am running 5.1.1 and the same "Unknown InResponseTo..." error is also occurring when attempting to use MS Azure as the IDP. Clicking back button does not work. Is there an eta for this fix?

**Comment by RCheesley** [comment]
@iambigred it'll be fixed when someone steps up to fix it, currently we do not have an ETA. If you'd like to move it along faster please feel free to add a bounty and we can see if that helps to attract a developer to work on this task. 

There's a [big refactor for the authentication system](https://github.com/mautic/mautic/pull/14219) happening in Mautic 6 due to some code being deprecated, but it doesn't fix this problem either, so one way or another it's going to need to get some attention!

**Comment by daltonm-GEM** [comment]
I chased this same issue for two days now, and have found a workaround if you are using Cloudflare or a reverse proxy in front of Mautic.

The flow only breaks if Mautic initiates the SAML flow.  If you start the login flow from the IdP, then it logs in fine.  I set up a redirect in my reverse proxy (Traefik in my case) to intercept any requests to https://myweburl.com/saml/discovery and 302 redirect them to the login URL provided by my IdP (Entra), similar to this:

https://launcher.myapps.microsoft.com/api/signin/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx?tenantId=yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy

This drops the SAML flow initiated by Mautic when navigating to the root URL, and starts a new one initiated by the IdP.

**Comment by RCheesley** [comment]
Hey folks! Thanks to @biozshock for the PR #14367 - please test this so we can get it merged in the upcoming patch release! https://mau.tc/tester has everything you need to test PRs in the browser or locally with DDEV! 🚀

**Comment by biozshock** [comment]
@RCheesley Unfortunately this one can't be tested in DDEV in browser, not sure about local installation. The SAML server is not included in the DDEV, so there should be someone with a bit of docker knowledge, or a working SAML server to follow steps from the #13742 . 
That's why this PR contains an automated test, that follows the steps.

**Comment by gregharvey** [comment]
@RCheesley Hey, just tested this on our dev version of Mautic and it works. :partying_face:
