### ISSUE TITLE
Small bug with SMS character count layout

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#13800]
### Mautic Version

5.0.x series

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8

### What happened?

I came across a small bug with the layout when creating an SMS, the character count is in the wrong position.

![screenshot-mautic ddev site-2024 05 31-12_55_44](https://github.com/mautic/mautic/assets/2930593/f09b8d43-6afa-48dd-a8f6-518b5f352d3e)

cc @ux

### How can we reproduce this issue?

Step 1: Set up Twilio integration
Step 2: Check the layout of the character count when creating an SMS

It looks like `.characters-count` has a `top` value of 20px which is affecting the layout.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by escopecz** [comment]
Ready to test: https://github.com/mautic/mautic/pull/13804
