### ISSUE TITLE
Standalone form action incorrectly sending results

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#1380]
**Symptom**
Form results are not sent, variable names sent instead

**Versions**
Mautic v1.2.3
PHP 5.5.30
Hosted on GoDaddy Shared Linux Ultimate Plan

**Steps**
Created a new standalone form "Contact Us" with the following :

**Fields**
"First Name" (mandatory text, linked to lead field of same name)
"Last Name" (mandatory text, linked to lead field of same name)
"Email" (mandatory email, linked to lead field of same name)
"Subject" (optional text)
"Message" (mandatory textarea)

**Actions**
*Send form results*
Name: Notify info@
Send to lead:no
To:info@ email address
Message Text is default:

**First Name:** {formfield=first_name}
**Last Name:** {formfield=last_name}
**Your Email:** {formfield=your_email}
**Subject:** {formfield=subject}
**Message:** {formfield=message}

**Email actually received**
![screenshot from 2016-01-25 19 18 06](https://cloud.githubusercontent.com/assets/10385295/12545662/6b81b4f2-c398-11e5-9727-d3c4022e47b9.png)

**Comment by escopecz** [comment]
What email transfer do you use (SMTP, Mandrill, ...)? Maybe it is the same issue which is fixed here: https://github.com/mautic/mautic/pull/1277

**Comment by zstephen** [comment]
This issue was fixed in #1277
