### ISSUE TITLE
UI - Form creation on mobile

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#13826]
### Mautic Version

5.0.x series

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

8

### What happened?

I noticed a few issues when creating a form on a mobile device which might need a bit of TLC:

Headers aren't aligned to the middle of the box:

![screenshot-mautic ddev site-2024 06 11-17_23_22](https://github.com/mautic/mautic/assets/2930593/613ce798-2309-4b80-a3fe-eadfd294e0f3)

Tabs are going off the screen and there doesn't seem to be a way to drag them over:

![screenshot-mautic ddev site-2024 06 11-17_25_59](https://github.com/mautic/mautic/assets/2930593/d50aedd4-55b0-46cf-ac87-672e017456fb)

### How can we reproduce this issue?

Step 1: Open Mautic with a mobile resolution
Step 2: Create a form
Step 3: Try to add a field

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
(note: Sorry this relates to the PR #13819 - didn't realise I still had that checked out!

**Comment by andersonjeccel** [comment]
@RCheesley The second was already fixed on the PR https://github.com/mautic/mautic/pull/13819
The first will be when other PRs get merged
