### ISSUE TITLE
Wrong statistic overview vor mails Mautic 5.1.0

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#13832]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.29

### What browsers are you seeing the problem on?

Firefox

### What happened?

Wrong overview sending statistic: 
![Übersicht](https://github.com/mautic/mautic/assets/96744684/fac9f593-d195-423d-87e3-c74e20a21554)

Here is right:
![Statistik](https://github.com/mautic/mautic/assets/96744684/e5a6870a-2799-448a-8c38-40df5ec99fc8)

### How can we reproduce this issue?

Step 1: Send a e-mail and you see the wrong overview in the mail list

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by Lealuli** [comment]
Same problem using Google Chrome

**Comment by avara** [comment]
Hello,

I think your problem could be related with the [issue](https://github.com/mautic/mautic/issues/13806) I created some days ago where I describe also the solution. If you want you can check also another [issue](https://github.com/mautic/mautic/issues/13807) I created with the same problem in the statistics of a campaign.

Hope it could help you.

**Comment by mallezie** [comment]
I think here https://github.com/mautic/mautic/issues/13866 this is a duplicate. Although that one is newer, it might contain more info for a possible fix.

**Comment by RCheesley** [comment]
Hi folks, thanks for jumping in with the duplicate issue reports - I'm going to close this one in favour of #13866 which has a PR to fix.

**Comment by RCheesley** [comment]
(PS: If any of you would like to help form a triage team .... we'd very much appreciate the support! Drop us a line in #t-product on [Slack](https://mautic.org/slack)!)
