### ISSUE TITLE
Lead Information Resubmission Form

### ISSUE THREAD

**Issue by dbarrow1992** [mautic/mautic#1384]
Hi

I was encouraged by @escopecz to put a development request in for a feature i was discussing.

Please see the notes below.

"Hi,

I want to create a form which can resubmit lead information should a lead decide they want to provide more information about themselves. I am aware mautic is quite cleaver and will automatically merge leads if it identifies a lead to have similar content.

However, I was wondering if it is possible to input data from the existing lead into a form so a lead can see what exactly they have submitted in the past and alter it accordingly? For example when i create a double opt-in for an email address the landing page associated with this process could have another form which could allow a lead to resubmit there information if they choose to and have the option alter there existing email preferences on another landing page.

I feel i maybe going a bit beyond the capabilities of mautic but i would be interested to see if it was possible.

Thanks.
Dan"

https://www.mautic.org/community/index.php/1287-lead-information-resubmission-form/last

**Comment by escopecz** [comment]
@dbarrow1992 check if https://github.com/mautic/mautic/pull/1363 is what you need.

**Comment by dbarrow1992** [comment]
Exactly what I'm looking for @escopecz thanks!
