### ISSUE TITLE
Mandrill with apikey

### ISSUE THREAD

**Issue by paulocastellano** [mautic/mautic#1385]
Hi,

Maybe its good make integration with mandrill by apikey?

Ty

**Comment by escopecz** [comment]
Well, if you select the Mandrill service for outgoing emails, Mautic will ask for your Mandrill username and password. The password in this case is Mandrill API key. Is that OK? Can we close this issue?

**Comment by CedricH-BZH** [comment]
it works for me !

**Comment by paulocastellano** [comment]
Thanks, it work for me!
