### ISSUE TITLE
site_url wrongly created on installation

### ISSUE THREAD

**Issue by luismagr** [mautic/mautic#13864]
### Mautic Version

5.0.x series

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.1.29

### What browsers are you seeing the problem on?

Not relevant

### What happened?

After install the site through the interface the `site_url` variable in `local.php` set its value to `https://mydomain/index.php`. That makes the site to fail while referencing images on the markup. For example I can see this get on my local environment 
`GET | https://mydomain/index.php/themes/brienz/assets/your-logo-purple.png?v8393fb44=`

If you manually remove the last part of the value for `site_url` leaving it as `https://mydomain`, then everything works fine.

Seems to happen something similar at #13840 

### How can we reproduce this issue?

Step 1: Do a fresh install
Step 2: Follow the visual assistance to configure the database and admin
Step 3: Create an email and try to work with images.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there,

There is no need to add /index.php - this will cause things to break. Please remove it and in the future, you can get support at https://forum.mautic.org as that's where you can ask for support with installing/configuring/using Mautic, whereas GitHub is for reporting bugs with the application itself.
