### ISSUE TITLE
Smart List to catch all leads who are Unsubscribed - not populating

### ISSUE THREAD

**Issue by 750430** [mautic/mautic#1387]
Hi,

Our Mautic (1.2.3) instance does not appear to be populating a custom smart list with the only option being 'unsubscribed = yes'.

According to some preliminary investigation with "jeph" (Slack discussion) the db is populating with the 'do not email' setting, however, the Smart List isn't populating.

Any assistance would be very much appreciated.
thanks!

**Comment by escopecz** [comment]
Have you tried `unsubscribed = 1`?

**Comment by 750430** [comment]
![image](https://cloud.githubusercontent.com/assets/9106836/12858514/78e61076-cc48-11e5-8913-517ca14cea8b.png)

**Comment by 750430** [comment]
It's a drop-down box, no ability to set an numeric value... Sorry!

**Comment by escopecz** [comment]
Oh, right. I just tested this filter and got all unsubscribed leads into that list. Are you sure your cron jobs are working fine? Try to run

```
php app/console mautic:list:update
```

in the Mautic root folder.

**Comment by 750430** [comment]
Hi.
![image](https://cloud.githubusercontent.com/assets/9106836/12892130/8dd19faa-ce82-11e5-902a-2208ab28cb91.png)

Looking at the database itself, I see the above. There are no 1's in the 'unsubscribed' column, they're all in 'bounced', yet the text in 'comments' is User Unsubscribed.

**Comment by escopecz** [comment]
I was testing it on an old database and there were already some unsubscribed leads. That's why it worked for me. I looked at the code and found the problem. The fix is here: https://github.com/mautic/mautic/pull/1421

**Comment by 750430** [comment]
Confirmed functioning correctly. Also changed db for unsubscribed users prior to fix.
