### ISSUE TITLE
mj-attributes styling does not work

### ISSUE THREAD

**Issue by Aleen95** [mautic/mautic#13886]
### Mautic Version

5.0.x series

### Way of installing

Other (please specify if relevant in the bug report)

### PHP version

8.1.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

Version: 5.0.4
PHP version: 8.1.2
Installed in a self built docker-image

mj-attributes within an email template are used to define the general styling of MJML elements.
However, if you pass styling with valid mj-attributes (checked here [https://mjml.io/try-it-live,](https://mjml.io/try-it-live)) Mautic won't render it. It gets nested, which you can see in the mjml exporter. But even if I copy and paste the valid mjml code (without the nesting), it still doesn't render correctly.
For example, styling a button via the mj-attributes results in a button being displayed on top of the template:

the passed mjml-code:
![image](https://github.com/mautic/mautic/assets/120421770/ab3d042b-6dbc-48a8-a558-e323555cfc70)

the code in mautic:
![image](https://github.com/mautic/mautic/assets/120421770/4e70b0ea-5299-41fc-86d4-ef15c29ee012)

the outcome:
![image](https://github.com/mautic/mautic/assets/120421770/35915503-cd17-446a-b4be-d8b32d63ed19)

### How can we reproduce this issue?

Step 1: write valid mj-attributes inside the mj-head in a template
Step 2: deploy it to your Mautic
Step 3: choose your template for an e-mail
Step 4: open the grapes-builder
Step 5: check the result

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for the report!

Per the documentation I just checked here: https://docs.mautic.org/en/5.x/builders/creating_themes.html#head-components the `<mj-attributes>` don't run - as far as I know this hasn't changed, but it's entirely possible we might have missed an update on the docs. In case it hasn't changed, perhaps that explains the behaviour you're getting?

**Comment by ricfreire** [comment]
Hi @Aleen95,

It's normal to see attributes in the upper section of your email when using the builder. However, if you preview the email, you'll see that everything works as expected. The builder simply displays all elements defined within the `<mj-attributes>` tag.

If you're working for a client, explain that they should trust the email preview, not the builder's display. Margins and paddings may look incorrect in the builder but will appear fine in the preview.

**Comment by Aleen95** [comment]
Hi @RCheesley  and @ricfreire 
I see! Thank you so much for the answer! I have tested it and the result is indeed correct. I think this might cause a bit of irritation for some non-developers working with the grapes-js-builder, but as long as it works properly, we have to live with it. Checking the preview is a fair compromise, I guess! 😌
It might be a good idea to add this to the documentation to avoid the same kind of confusion that I had. 🤭

**Comment by RCheesley** [comment]
Thanks folks, we deffo do need to improve the docs, if you'd like to help with that the repository for the docs is https://github.com/mautic/user-documentation for users and https://github.com/mautic/developer-documentation-new for the dev docs!
