### ISSUE TITLE
The up arrow in the blue bar / e-mail editor doesn’t work.

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#13894]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2.29

### What browsers are you seeing the problem on?

Firefox

### What happened?

The up arrow in the blue bar / e-mail editor doesn’t work in Mautic V. 5.1
What should it do? (i mean it's a bug and expected, to move parts of the e-mail up (should not a down area also be here?)

### How can we reproduce this issue?

Click on the up arrow by creating an e-mail - nothing happens

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi @stefan-franz have you tried both clearing your cache, and rebuilding your Mautic assets using `bin/console m:a:g` after updating?

**Comment by stefan-franz** [comment]
Thanks for your support. I cleared the cache and tried your command (ubuntu 22.04). 
What is the right command in this case to install the 'node modules' - please see the below the console command lines.

```
root@mautic01:/# php /var/www/html/mautic/bin/console cache:clear

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

                                                                                
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  
                                                                                

root@mautic01:/# php /var/www/html/mautic/bin/console m:a:g
/var/www/html/mautic/node_modules does not exist. Execute `npm install` to generate it.
root@mautic01:/# 

```

**Comment by RCheesley** [comment]
You need to install it on your infra, like it says.  I think this isn't actually a bug, the up arrow relates to moving up and down between the blocks in the builder, and it's working as expected:

https://app.screencastify.com/v3/watch/3wVSzZnCpfS4mA8zQSvB

Therefore I'm going to close this issue as not able to be reproduced.
