### ISSUE TITLE
Not able to upload images in grapejs builder

### ISSUE THREAD

**Issue by BTxxx7274** [mautic/mautic#13907]
### Mautic Version

5.0.x series

### Way of installing

I'm using a Docker image from https://hub.docker.com/r/mautic/mautic

### PHP version

 8.1.29

### What browsers are you seeing the problem on?

Chrome

### What happened?

I am trying to build landing pages or HTML emails, but it doesn't let me upload images. I get the following error as shown in the image:

Reference I could find: [GitHub Issue #13510](https://github.com/mautic/mautic/issues/13510)

![screenshot](https://github.com/mautic/mautic/assets/93242680/d12d9578-99bc-4ec8-be14-7622afb1c18c)

### How can we reproduce this issue?

Step 1: Try to upload image while creating a landing page or html email.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there,

What version of Mautic are you on? that fix was pushed some time ago, so you shouldn't be getting that issue any more.

Please try to clear your cache, rebuild your assets using `bin/console m:a:g`, and make sure your file and folder permissions are correct (check your system info page).

If those don't help please post at https://forum.mautic.org for more support with troubleshooting.
