### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by graphicomputer** [mautic/mautic#1393]
Just downloaded Mautic (so latest version) - Navigate to the url and the offline error page is displayed (was expecting installer)

Log file says it's unable to create cache directory - I assume it's just permissions but can't see where the directory should be created.

Log file attached
[linesForView-.txt](https://github.com/mautic/mautic/files/109827/linesForView-.txt)

**Comment by alanhartless** [comment]
Hi!

Mautic needs app/cache and app/logs to be writable by your web user.

Thanks!
Alan
