### ISSUE TITLE
Repeated links not replaced in Email

### ISSUE THREAD

**Issue by ramezrafla** [mautic/mautic#1394]
In emails, only the first incidence of a URL gets replaced with the Mautic one (for tracking / redirect).

Our work-around was to add bogus GET variables: `&_debug=2`

My guess is that the RegExp is missing the `/g` flag or maybe a loop around the replace.

**Comment by escopecz** [comment]
Could you write steps to recreate? If I understand right, if I place 2 same links to email, only the first one is converted to trackable link, is that right? Just want to make sure before testing.

**Comment by ramezrafla** [comment]
Hi John, that's exactly right. If you duplicate the exact link in your email only the first one becomes trackable

**Comment by escopecz** [comment]
I tried to send this email to a lead list:
```
<html>
<head>
	<title></title>
</head>
<body>
<p><a href="https://github.com/mautic/mautic/issues/1394">https://github.com/mautic/mautic/issues/1394</a></p>

<p><a href="https://github.com/mautic/mautic/issues/1394">https://github.com/mautic/mautic/issues/1394</a></p>
</body>
</html>
```
Both links were converted to the trackables in the emails I've received:
```
<div><p><a href="http://[censored]/r/4eb61eff1e62e5d4dc9dc9076?ct=YTo0OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6OTc7fXM6NToiZW1haWwiO2k6OTc7czo0OiJzdGF0IjtzOjEzOiI1NmI0YmJmYmQ1MjJiIjtzOjQ6ImxlYWQiO2k6OTU7fQ%3D%3D" target="_blank">https://github.com/mautic/<wbr>mautic/issues/1394</a></p>

<p><a href="http://[censored]/r/4eb61eff1e62e5d4dc9dc9076?ct=YTo0OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6OTc7fXM6NToiZW1haWwiO2k6OTc7czo0OiJzdGF0IjtzOjEzOiI1NmI0YmJmYmQ1MjJiIjtzOjQ6ImxlYWQiO2k6OTU7fQ%3D%3D" target="_blank">https://github.com/mautic/<wbr>mautic/issues/1394</a></p>
</div>
```
Do you use the latest version of Mautic?

**Comment by ramezrafla** [comment]
I create a new email and re-tested and still get the same behavior. Note that my link has one GET argument. http://somehwere.com?param1=val1

I am trying to send you the link via PM or email - if I can find your email :)

**Comment by escopecz** [comment]
I'm afraid I didn't receive the email. Could you just please share the HTML source code of your email so we could test it?

**Comment by ramezrafla** [comment]
@escopecz, did you receive the email HTML I sent you via mautic.org community PM?

**Comment by escopecz** [comment]
Eh, I'm not sure. I tried to search for it, but it won't appear when I search by your name.

**Comment by escopecz** [comment]
Take a look at https://github.com/mautic/mautic/issues/1524 which contains also a possible fix at https://github.com/mautic/mautic/pull/1531. Please comment below https://github.com/mautic/mautic/pull/1531 if the fix works for you.
