### ISSUE TITLE
Error 500 when creating/duplicating a form

### ISSUE THREAD

**Issue by Frettyl** [mautic/mautic#13977]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.27

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Error 500. This only happened after update from 4.x or 5.0 to 5.1. I am not sure as those updates were installed closely after each other.

### How can we reproduce this issue?

Go to forms, try to create a new one or duplicate an existing one.

### Relevant log output

```shell
[2024-07-17T08:13:13.485786+00:00] mautic.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "typeOneDifferences" does not exist." at /var/www/app/bundles/CoreBundle/Resources/views/Helper/form_selecttype.html.twig line 38 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): Variable \"typeOneDifferences\" does not exist. at /var/www/app/bundles/CoreBundle/Resources/views/Helper/form_selecttype.html.twig:38)"} {"hostname":"<redacted>","pid":8698}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for the bug report, @Frettyl - can you clarify how you updated, and whether you followed all the steps? 

What kind of fields do you have when you're trying to save/clone the forms?

I've tried to reproduce locally but I don't see the error that you've experienced, so it might be that there's specific things on the form causing the issue?

**Comment by Frettyl** [comment]
Hi, I used the commnad line as the documentation suggests.
I doubt this would be related to any specific forms since when you create w new one, blank it doesn't work either.

I searched the templates and saw the `typeOneDifferences`  should be set everywhere, however, the error is still there. Any idea what that variable even is,, or where should I look next?

**Comment by RCheesley** [comment]
Hi @Frettyl is this still an issue for you with the latest versions? I'm not able to reproduce it which might suggest there's something funky going on with your instance/setup.

**Comment by RCheesley** [comment]
Closing due to lack of feedback, feel free to request a re-open.
