### ISSUE TITLE
HTML Entity displaying instead of special characters

### ISSUE THREAD

**Issue by andre-mha** [mautic/mautic#13985]
### Mautic Version

5.0.x series

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.1.27

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What happened?

This is a fresh install that was setup for running website transactional emails and starting marketing automation for the company.

When editing anything and looking at the "Save & close" button it is displaying html entity code instead of the ampersand, this also applies to over special characters within submitted data
![7fb2f4d1-f2f6-4424-9352-97d9dd7e9d5d](https://github.com/user-attachments/assets/e69408b8-d43d-4d38-a39e-e0e0239ed76e)
![8aecea17-1342-44fd-9f21-38c264087d6b](https://github.com/user-attachments/assets/9d744cfc-ce44-4084-95ae-0bac33d802f6)

### How can we reproduce this issue?

Step 1: Installed latest version via composer
Step 2: Set up custom fields
Step 3: Started building forms 
Step 4: HTML Entities displayed at this point on "Save & close

### Relevant log output

```shell
Not applicable, it doesn't generate any logs
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
This was resolved in 5.1 and was reported earlier, so I'm going to close this one down as a duplicate issue.
