### ISSUE TITLE
Stuck on 'Processing Database Updates'

### ISSUE THREAD

**Issue by drexelroth** [mautic/mautic#140]
First, this is great software! It is far better than the commercial marketing automation software I use.

I am trying to update to 1.0.0-rc3 and I am stuck on 'processing database updates' step. I'm not getting any errors in my log and it just keeps spinning on the page. 

Any suggestions?

**Comment by dbhurley** [comment]
Thanks for the compliments! :smile: 

When did you try the update? As in at the time of posting or earlier? We had a glitch in permissions on the update packages and had to change those before the updates would go through.

**Comment by drexelroth** [comment]
I tried around 9:15 this morning... is there a way I can roll it back and retry?

**Comment by alanhartless** [comment]
Hi. 

Sorry to hear this. 

What version of Mautic did you upgrading from and what database driver are you using?

If it is just spinning then it may have hit some error. Did you check both
app/logs/mautic_prod.php and your hosts error logs for any errors? I know you mentioned there was nothing in the logs so just wanted to make sure you checked both. 

If we can figure out the error, we can get your upgrade finished. Do you have access to ssh?

Thanks,
Alan

**Comment by drexelroth** [comment]
Hi Alan -

I was upgrading from rc2 to rc3. I'm using a MySQL database. 

I'm getting the following error: 
[07-Mar-2015 14:43:38 UTC] PHP Fatal error: Class 'Oneup\UploaderBundle\OneupUploaderBundle' not found in /home/.../app/AppKernel.php on line 120
Any ideas?
Thanks, Drexel

**Comment by alanhartless** [comment]
Hi Drexel,

It would seem that maybe not all the files copied over. If you use FTP to look at Mautic's root, is there an upgrade folder? And if so, what folders/files are left in it if any.  Also, is there an upgrade_errors.txt file and if so, what's in that?

Thanks,
Alan

**Comment by drexelroth** [comment]
I have an upgrade folder with: 
-builds
--process_devhead.php
--process_release.php
--processfiles.php

And no upgrade_errors.txt

**Comment by alanhartless** [comment]
Those aren't suppose to make it into the update package :-) But it wouldn't affect the issue that you're having.

Can you check /vendor/oneup/uploader-bundle to ensure it exists.

Then check vendor/composer/autoload_namespaces.php around line 50 to see if it has `'Oneup\\UploaderBundle' => array($vendorDir . '/oneup/uploader-bundle'),`

Thanks,
Alan

**Comment by drexelroth** [comment]
The line is listed in the autoloader_namespaces.php file.

Inside of the uploader-bundle folder I have another oneup/uploaderbundle/ then all of the files. Is this how it is supposed to be?

**Comment by alanhartless** [comment]
Yes that is how it's supposed to be.

Okay, delete the folder app/cache/prod.  Refresh the page.  Does it work now without the error?

If it doesn't work, we may have to connect via Slack (https://www.mautic.org/get-involved/group-chats) to get this sorted out.

Thanks,
Alan

**Comment by drexelroth** [comment]
It seems to be working fine. Thanks for helping me troubleshoot.

**Comment by alanhartless** [comment]
Okay; so it sounds like maybe the cache clear which is performed at the start of the database step failed for whatever reason. I'm going to close this for now but if it happens again with the next release, open a new issue and hopefully we can get to the bottom of it.
