### ISSUE TITLE
Email click - browser open issue

### ISSUE THREAD

**Issue by walltopski-makaron** [mautic/mautic#14025]
### Mautic Version

5.0.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.29

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

When I create a campaign and one of the steps is to check if a link is clicked in the email (it doesn't matter if you set a specific link or if you leave it to be open for any link, not does it matter if the link has or lacks UTM parameters) when you receive the email if you click it and you default browser is Edge Mautic won't consider the click to have happened, but if you open it in another borswer like Chrome or Opera the issue dissapears.

### How can we reproduce this issue?

Step 1: Create a campaign
Step 2: Set an email to be sent with a link inside it
Step 3: Set a decision that checks if an email is clicked
Step 4: Set an email to be sent if an email is clicked
Step 5: When you receive the first email open the link in MS Edge. If you open it in another browser you'll have to redo the steps above and start again
Step 6: When you open the email in Edge you'll see that nothing happens (wait for 15-30 seconds just in case)
Step 7: Open the link in another browser and within 15-30 seconds you should receive the email that confirms the click has happened

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by vinzent** [comment]
As a newbie i've stumbled upon this too.  Are you logged into Mautic when you clicked the link? No click will be recorded as long as you are logged in. Try using a private tab, another browser or logout of Mautic.

**Comment by walltopski-makaron** [comment]
I did and I also sent it to a number of people (who aren't logged in as they don't have an acc) to click around and it didn't work.

**Comment by vinzent** [comment]
I just tried to reproduce it on my installation (5.1.0). As soon as I sign-out of Mautic, the link click is recorded.

**Comment by vinzent** [comment]
@walltopski-makaron I used Firefox. not MS Edge. Maybe this is a Edge specific issue. Sorry for the noise.

**Comment by vinzent** [comment]
Retried with Microsoft Edge (on Linux):

![image](https://github.com/user-attachments/assets/1b8580f8-7ddf-47d3-934a-ff135d5cdaa5)


![image](https://github.com/user-attachments/assets/7aa31b48-fcfd-4ccd-aefa-5e4fd9e13a41)

works as expected.

**Comment by mauricoder** [comment]
@walltopski-makaron , thanks for reporting and @vinzent thanks for testing it. Looks like it's not an issue but a feature as Mautic is not tracking you when logged in.

Please, if it's still an issue tell us and we can reopen. Or if you need help using Mautic refer to the forums: https://forum.mautic.org/
