### ISSUE TITLE
Multiple Errors and Inconsistencies in Country and Region definitions

### ISSUE THREAD

**Issue by martin-neumann-gurus** [mautic/mautic#14050]
### Mautic Version

5.1.x series

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8

### What happened?

There are a few minor updates needed for the Country definitions and definitely some more updates for the Regions file.
There are fairly well defined for most Western countries, but it is getting messy for the rest of the world. Several countries have wrong or outdated information when it comes to the Regions file. There are also some inconsistencies like Brazilian states are without accents, when the rest of the world has accents on their state names. This causes problems because contacts are getting rejected by the API if they do not follow the wrong definitions of Mautic in their country and state fields. I guess it is also affecting the accuracy of geolocalization

I would propose:
1. To find an authoritative source like the CLDR charts and update the whole file countries.json and regions.json accordingly:
https://www.unicode.org/cldr/charts/45/by_type/index.html
I am not sure if CLDR is the best authoritative source, but it is surely a good option. If anybody can suggest something better, please comment. Probably there is a way to even extract this information programmatically. It would be interesting to also investigate, which standards the geolocalization services are using to deliver country and state information.
I am aware that updating this definitions will require a database update, but it is better to do that once well done then to have 100 pull requests, because somebody is accidentally stepping over a wrong definition that they happened to find.

2. To change those definitions to include a key/value pair, so that a two letter country code is associated to the country name, and the sames for the region definitions. Having this information, we could extend the API to accept in the country field the two letter code or the written out country name, and the same for the state definitions.

3. As a next step it can be even considered to save the two letter code instead of the name in the database. This would save some space, and would reduce also the number of database updates in case of name changes. I am not much familiar with Symphony, but I assume that such a change can be done just on the model layer, without the View and Logic being aware of any change in the database.

### How can we reproduce this issue?

Just look up the files here and check for the mentioned inconsistencies:
https://github.com/mautic/mautic/tree/5.x/app/bundles/CoreBundle/Assets/json

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
Hi @martin-neumann-gurus ... great suggestions for an improvement of Mautic. Have you checked, if they are discussed already in https://forum.mautic.org/c/ideas/14 ? 

Would you be able to drive this forward? Looks you already have an idea on how it can be improved.

So far this is however to broad for a bug report. It works as is today, if there are spelling errors, missing regions etc. this should be specific bug reports. Although I agree, that a general improvement would solve most issues at once, the change would require some effort for code change and migrations.

Please Martin, push this idea forward, even if I need to close the bug for the reasons stated.
