### ISSUE TITLE
Add visual warning if form fields are not mapped to lead fields

### ISSUE THREAD

**Issue by samtuke** [mautic/mautic#1407]
It's easy for users to forget to map form fields to lead fields, but if they do this the data stored won't be visible on the lead page and also won't be passed to any integrations if triggers are used.

Please add a visual indication (like a warning or error) if fields exist for a form but are not mapped to anything.

**Comment by escopecz** [comment]
Any chance you could provide a graphical design of your idea?

**Comment by escopecz** [comment]
The mapped contact fields are visible in the form field list for each field now, so it can be reviewed all in one place.
