### ISSUE TITLE
Custom field boolean label default label values not working in "Segments -> Filters"

### ISSUE THREAD

**Issue by AlbertMN** [mautic/mautic#14075]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.0

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.2

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What happened?

When creating a custom field with the "Boolean" type, the default button labels appear to be "No" and "Yes" in the UI;
![image](https://github.com/user-attachments/assets/0f4ee686-92cf-4daf-8a31-f4b1ac21e18a)

But, if you have no values in the "Boolean labels" fields, there's no way to filter on a boolean;
![image](https://github.com/user-attachments/assets/3cad22ca-77ce-42a6-83d3-0705a7384d93)

It simply shows no options.

But if you add labels;
![image](https://github.com/user-attachments/assets/223eb5f0-7343-4d71-9bfb-53d6637e7206)

They show up and are selectable in Segments;
![image](https://github.com/user-attachments/assets/5624c37e-e283-4cd7-adbc-7a9bd8b964a9)

I don't believe this was the case in Mautic 4. At least I don't recall having to put in button labels, or ever doing so for the "Boolean" custom field type. But I could be wrong.
Either way, I reckon the expected behavior would be to either not allow saving a custom field with no button labels, _or_ - preferably - to use the default "Yes" and "No" (like visualized in the custom field editor), when filtering for segments.

### How can we reproduce this issue?

1. Create a custom field with the "Boolean" type
2. Don't put in any button labels
3. Create a new segment or edit an existing one
4. Go to "Filters" in the segment
5. Try to filter a boolean custom field; no labels will show up, and you thereby can't filter on a boolean custom field type

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hey there,

Thanks for reporting this, could you explain what you mean when you say 

> the default button labels appear to be "No" and "Yes" in the UI;

As it seems to me that the label fields are both empty?

Do you mean that by your understanding, having the icons showing means that you assumed they were set to automatically use 'yes' and 'no'?

I agree that we should either make you enter something, or have something there. Probably the former is the best approach. cc @andersonjeccel I think this might be related to some of the recent changes, perhaps?

**Comment by andersonjeccel** [comment]
@RCheesley Hm, I didn't touch anything there, so no idea

**Comment by shinde-rahul** [comment]
I failed to reproduce this on 5.1.0.

The step **Don't put in any button labels**, it yields validation errors like `A 'negative' label is required. ` or `A 'positive' label is required. ` 

I have attached the video,
https://github.com/user-attachments/assets/1694e329-77b6-45ee-b556-db9709dab2ab

**Comment by putzwasser** [comment]
> I failed to reproduce this on 5.1.0.

Can confirm. M5.1 forces you to define values for no and yes.

My best guess is that

a) leaving these fields empty was possible in M4 and there is no migration
b) an API call created this field and it is possible to leave these values blank using the API  (didn't check if that is really the case, though)

I'm leaning towards a)

**Comment by AlbertMN** [comment]
In our case, we created the custom fields via the API, so that'd be why!

**Comment by RCheesley** [comment]
Thanks for making the PR to improve this situation @shinde-rahul - @AlbertMN could you please test #14112 and leave a review if it addresses this issue? One more test and we can get it merged! Testing instructions can be found at https://mau.tc/tester.

Thanks so much!

**Comment by RCheesley** [comment]
@all-contributors please add @AlbertMN for bugs
