### ISSUE TITLE
At one point the the Emails section stopped opening.

### ISSUE THREAD

**Issue by walltopski-makaron** [mautic/mautic#14091]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.0

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.29

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### What happened?

I was installing different themes in order to used them as templated for emails. At one point the Emails section stopped opening when I click on it. I can take a video recording if needed. 

### How can we reproduce this issue?

1) Click on the Emails section
2) That is it
3) video of the issue - https://share.vidyard.com/watch/r6JsVEomo7DitdzJ2U3j5y?
N.B. probably won't happen on someone else. IDK how to reproduce the rest. AS I said it happened after installing a few themes.

As it is visible the Dashboard opens, but the Email section doesn't want to open. Different users and browsers have been tried and the issue is always there.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by walltopski-makaron** [comment]
video of the issue is added to the issue description

**Comment by RCheesley** [comment]
Thanks @walltopski-makaron, please include the logs from your Mautic instance, found in var/logs within your Mautic directory. It sounds like you have some error happening but we can't help to troubleshoot without the error logs. 

Thanks!

**Comment by walltopski-makaron** [comment]
@RCheesley As I am in marketing, do I need my sys-admin to get them in order to share them? Where exactly can i find them?

**Comment by RCheesley** [comment]
Hi @walltopski-makaron you can access them in Mautic via the System Info tab, if your admin allows you access to that:

![screenshot-mautic_ddev_site-2024_10_14-17_56_16](https://github.com/user-attachments/assets/27bac3a8-0f1b-40dd-9e22-245c0ae87390)

Otherwise you'll need to ask your admin to check the logs at the time where you try to open the email section.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
