### ISSUE TITLE
[BUG] Campaign not sending triggered emails

### ISSUE THREAD

**Issue by alvinbenavides** [mautic/mautic#141]
I'm not experiencing any problem sending emails, other emails are sent without any problem, but the campaign is not sending a triggered email. (Using PHPMail)

I'm testing a scenario where if a lead downloads an asset, Mautic waits 10 minutes and send an email to that lead. I'm sure that after downloading the asset the email is scheduled because I can see it in "Upcoming e-mails".

After the 10 minutes I can't see the email any longer in Upcoming e-mails but email is never sent. No error in Mautic or server, no record in mail log and also there is no record on the lead history that the email was sent.

**Comment by alvinbenavides** [comment]
....running RC3

**Comment by alanhartless** [comment]
Hi Alvin,

Scheduled events and events that are based on the lead not doing something are triggered using the command

php /path/to/Mautic/app/console mautic:campaigns:trigger --env=prod

Set this as a cron job to run at intervals. 

Mautic doesn't fire the scheduled or "no" events while using Mautic as it could be a heavy hit to performance if you're trying to use the site while it's trying to process large campaigns. 

Let us know if that doesn't get your email sent out. 

Thanks!
Alan

**Comment by alvinbenavides** [comment]
You're correct, this was cron related...

Thanks.

**Comment by zachrdlapetr** [comment]
I think this doesn't work right. This works right just when I make a decision Open email (no => red halfpoint). Green point doesn't work and when I run the cron wrote down above I get the error below (last line).

RC4, Ubuntu 12.04 x64, PHP 5.4.18

php /var/www/app/console mautic:campaigns:trigger --env=prod 

PHP Notice:  Undefined index: SERVER_PORT in /var/www/app/bundles/AddonBundle/Integration/AbstractIntegration.php on line 940
PHP Notice:  Undefined index: HTTP_HOST in /var/www/app/bundles/AddonBundle/Integration/AbstractIntegration.php on line 940
PHP Notice:  Undefined index: REQUEST_URI in /var/www/app/bundles/AddonBundle/Integration/AbstractIntegration.php on line 940
PHP Notice:  Undefined index: SERVER_PORT in /var/www/app/bundles/AddonBundle/Integration/AbstractIntegration.php on line 940
PHP Notice:  Undefined index: HTTP_HOST in /var/www/app/bundles/AddonBundle/Integration/AbstractIntegration.php on line 940
PHP Notice:  Undefined index: REQUEST_URI in /var/www/app/bundles/AddonBundle/Integration/AbstractIntegration.php on line 940
PHP Notice:  Undefined index: SERVER_PORT in /var/www/app/bundles/AddonBundle/Integration/AbstractIntegration.php on line 940
PHP Notice:  Undefined index: HTTP_HOST in /var/www/app/bundles/AddonBundle/Integration/AbstractIntegration.php on line 940
PHP Notice:  Undefined index: REQUEST_URI in /var/www/app/bundles/AddonBundle/Integration/AbstractIntegration.php on line 940
PHP Notice:  Undefined index: SERVER_PORT in /var/www/app/bundles/AddonBundle/Integration/AbstractIntegration.php on line 940
PHP Notice:  Undefined index: HTTP_HOST in /var/www/app/bundles/AddonBundle/Integration/AbstractIntegration.php on line 940
PHP Notice:  Undefined index: REQUEST_URI in /var/www/app/bundles/AddonBundle/Integration/AbstractIntegration.php on line 940
PHP Catchable fatal error:  Argument 1 passed to Mautic\EmailBundle\Helper\PointEventHelper::sendEmail() must be an instance of Mautic\PointBundle\Entity\TriggerEvent, array given in /var/www/app/bundles/EmailBundle/Helper/PointEventHelper.php on line 45

**Comment by zachrdlapetr** [comment]
The change. The error above  is no longer there today. But I have another problem. When I send an email and set campaign - send "thanks" email after 5 min, based on "Opens email". Nothing is happen. Opens email is still 0% in campaign. I did try click on email, show image inside email, click on link inside email and nothing.

**Comment by alvinbenavides** [comment]
Hi @zachrdlapetr

As I understand you are opening the 'thank you' email but Mautic is not registering that you open it. If this is the case this might be related to this other issue about tracking gif on email: https://github.com/mautic/mautic/issues/149

Try to look at the source of the email and see if the tracking gif url has your Mautic url

**Comment by zachrdlapetr** [comment]
In Manage emails is written - read = 1  (gif works)

![image](https://cloud.githubusercontent.com/assets/11314068/6546173/b4c79be2-c5a9-11e4-90ca-c31d644805e5.png)

But in Manage campaign is written - Opened 0%

![image](https://cloud.githubusercontent.com/assets/11314068/6546179/24151f74-c5aa-11e4-8aba-4ecab277fe45.png)

**Comment by alanhartless** [comment]
@zachrdlapetr Does the email you scheduled show up in the lead's profile as a scheduled event on the right side?

Thanks,
Alan

**Comment by zachrdlapetr** [comment]
Alan, I owe you an appologize for delay. Too much work. I have tested the release 1.0.1 and all works great. Thank you so much for your support.

**Comment by alanhartless** [comment]
My turn to apologize! Glad it's working now. Thanks!

**Comment by Gustavo-Ruiz** [comment]
Hi Alan,
I am having the same issue, the campaign is not sending emails, i added the cron Job and nothing, the funny think is that I have to mautic installations and one does send and other does not. Both are in the same server. Any guides for this.
Thank you in advance.

Have a good day
