### ISSUE TITLE
Error downloading donotsell list with CLI command

### ISSUE THREAD

**Issue by castellinosviluppo** [mautic/mautic#14103]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.0

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.2.22

### What happened?

Trying to download “Do Not Sell” list (for maxmind databases) the CLI command mautic:donotsell:download return this error:
Automatically fetching Do Not Sell data failed.

I tried to a Mautic 4 version too, but same error.

I tried to download donotsell list via api from MaxMind api using my account (https://api.maxmind.com/privacy/exclusions) and it works

### How can we reproduce this issue?

Step 1: Configure in System Settings  > Miscellaneous Settings > IP lookup service authentication your autentication credentials for  maxmind account (user:password)
Step 2: Run in a shell CLI command: php /path_to_mautic/bin/console mautic:donotsell:download

### Relevant log output

```shell
Automatically fetching Do Not Sell data failed.
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by tobsowo** [comment]
I have difficulty downloading the MaxMind data too on the new Mautic 5.1 installations.

**Comment by RCheesley** [comment]
Hi there,

Firstly, please confirm that you're able to download from Maxmind normally with your credentials?

Secondly, have you made the necessary changes to your configuration file?

> Add to your local.php file the following to specify the file path: 'maxmind_do_not_sell_list_path' => './maxmind.json',

(I noticed this in the [PR introducing this](https://github.com/mautic/mautic/pull/8647) but I think it's missing in the docs - issue raised [here](https://github.com/mautic/user-documentation/issues/318))

**Comment by castellinosviluppo** [comment]
Thanks RCheesley. 
The problem was the maxmind_do_not_sell_list_path parameter
As you said is not documented, so i didn't know it.
Now all works!
Just a question, where do you recommend saving the maxmind.json file?
I put it in the mautic folder, but I don't know if it's the right choice  :)

**Comment by uhlhosting** [comment]
> Hi there,
> 
> Firstly, please confirm that you're able to download from Maxmind normally with your credentials?
> 
> Secondly, have you made the necessary changes to your configuration file?
> 
> > Add to your local.php file the following to specify the file path: 'maxmind_do_not_sell_list_path' => './maxmind.json',
> 
> (I noticed this in the [PR introducing this](https://github.com/mautic/mautic/pull/8647) but I think it's missing in the docs - issue raised [here](https://github.com/mautic/user-documentation/issues/318))

this works as solution, tested on composer deployed mautic 5.1.1

**Comment by escopecz** [comment]
Can someone please update the [docs](https://github.com/mautic/user-documentation/blob/5.x/docs/configuration/cron_jobs.rst?plain=1#L227) so others or us in the future would avoid this issue?
