### ISSUE TITLE
Support multiple BCC addresses (comma separated) in emails advanced tab

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#1410]
Currently, only a single address is supported as BCC when creating an email -> advanced tab. It's been requested to support multiple addresses here as CSV.

**Comment by maxSupermoney** [comment]
I'd just like to point out that this feature has been added
https://github.com/mautic/mautic/commit/8c9b1ea853a74338832d49ebcfc2a83326275e8d

**Comment by mauwiks** [comment]
Has this feature been accomplished?

**Comment by fuschini** [comment]
Yes @mauwiks 

You can use multiple BCC addresses separating them with commas like:

email1@gmail.com,email2@gmail.com

**Comment by mauwiks** [comment]
Thanks!

**Comment by iSaifee** [comment]
Just tried out the functionality. I can input multiple emails in BCC, however, the email is sent out to only the first email in the BCC list
