### ISSUE TITLE
Sorting by table headers in view report not Working

### ISSUE THREAD

**Issue by AlanWierzchonCA** [mautic/mautic#14102]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.0

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

Sorting by clicking on the table headers in the report data table is not functioning as expected. When clicking a column header to sort the data (either ascending or descending), the table does not reorder the data accordingly. This issue persists across multiple columns, regardless of the data type (e.g., numeric, date, or text fields).

![image](https://github.com/user-attachments/assets/7b293f6c-5181-47e4-8259-08c96952937e)

### How can we reproduce this issue?

Step 1: Navigate to the report data table.
Step 2: Click on any column header to sort the data by that column.
Step 3: Observe that the data remains unsorted or does not change as expected.

Expected Behavior: Clicking on the column header should sort the data in the table based on the selected column, either in ascending or descending order.

Current Behavior: Clicking the column header does not sort the data.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for the issue report and the PR to fix, @AlanWierzchonCA !
