### ISSUE TITLE
Delete Butten - German translation error

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#14126]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.30

### What browsers are you seeing the problem on?

Firefox

### What happened?

The delete button has a german display error. Right would be: "Löschen"
![Löschen Butten falsch](https://github.com/user-attachments/assets/27c82bb6-afcb-492a-8038-5d35f625ebaf)

### How can we reproduce this issue?

 Switch to German language, try delete a contact, an e-mail or a landing page

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there! Please take a look at https://transifex.com/mautic/mautic - that's where the translations happen. It's probably the case that it hasn't yet been updated.

**Comment by RCheesley** [comment]
This issue will be fixed on Transifex rather than in GitHub.

**Comment by stefan-franz** [comment]
Its not a wrong word - its a character problem! Right word is "löschen"
Mautic doen't display the "ö" right!

I checked this:

yxuser@server:/var/www/html/mautic/translations/de# grep -ri 'löschen'
CategoryBundle/messages.ini:mautic.category.form.confirmbatchdelete="Möchten Sie die ausgewählten Kategorien löschen? Verknüpfte Elemente werden NICHT gelöscht sondern als 'nicht kategorisiert' markiert."
CategoryBundle/messages.ini:mautic.category.form.confirmdelete="Möchten Sie die Kategorie %name% löschen? Verknüpfte Elemente werden NICHT gelöscht sondern als 'nicht kategorisiert' markiert."
CoreBundle/javascript.ini:mautic.core.builder.section_delete_warning="Sind Sie sicher, dass Sie den gesamten Bereich und den dazugehörigen Inhalt löschen möchten?"
CoreBundle/messages.ini:mautic.core.form.confirmbatchdelete="Löschen der gewählten Elemente?"
CoreBundle/messages.ini:mautic.core.form.delete="Löschen"
CoreBundle/messages.ini:mautic.core.form.delete_selected="Ausgewählte löschen"
CoreBundle/messages.ini:mautic.core.permissions.delete="Löschen"
CoreBundle/messages.ini:mautic.core.permissions.deleteother="Andere löschen"
CoreBundle/messages.ini:mautic.core.permissions.deleteown="Eigene löschen"
CoreBundle/messages.ini:mautic.core.update.archive_file_exists="Das Verzeichnis existiert bereits. Bitte kontrollieren Sie das Cache-Verzeichnis und löschen Sie alle Installationsverzeichnisse."
CoreBundle/messages.ini:mautic.core.update.archive_not_valid_zip="Das ist kein gültiges ZIP-Archiv. Bitte überprüfen Sie das Cache-Verzeichnis, löschen Sie das Paket und versuchen Sie es erneut."
CoreBundle/messages.ini:mautic.core.update.archive_zip_corrupt="Das ZIP-Archiv ist wahrscheinlich defekt. Bitte überprüfen Sie das Cache-Verzeichnis, löschen Sie das Paket und versuchen Sie es erneut."
CoreBundle/messages.ini:mautic.core.update.clear.cache="Cache löschen"
CoreBundle/messages.ini:mautic.core.theme.form.confirmdelete="Möchten Sie die Vorlage %theme% löschen?"
CoreBundle/messages.ini:mautic.core.theme.form.confirmbatchdelete="Die ausgewählten Vorlagen löschen?"
GrapesJsBuilderBundle/javascript.ini:grapesjsbuilder.deleteAssetConfirmText="Möchten Sie diese Datei wirklich löschen? "
PageBundle/messages.ini:mautic.page.form.confirmbatchdelete="Ausgewählte Seiten löschen? WARNUNG - Dadurch werden auch alle zugehörigen A / B-Tests und Übersetzungen gelöscht!"
PageBundle/messages.ini:mautic.page.form.confirmdelete="Seite löschen, %name%? WARNUNG - Dadurch werden auch alle zugehörigen A / B-Tests und Übersetzungen gelöscht!"
DynamicContentBundle/messages.ini:mautic.dynamicContent.form.confirmbatchdelete="Ausgewählte Objekte löschen? WARNUNG - alle assoziierten Übersetzungen werden auch gelöscht!"
DynamicContentBundle/messages.ini:mautic.dynamicContent.form.confirmdelete="Löschen Sie das Element mit dynamischem Inhalt, WARNUNG - dadurch werden auch alle zugehörigen Übersetzungen gelöscht!"
EmailBundle/messages.ini:mautic.email.form.confirmbatchdelete="Ausgewählte E-Mails löschen? Dadurch werden auch damit verbundenen A/B Tests und Übersetzungen gelöscht!"
EmailBundle/messages.ini:mautic.email.form.confirmdelete="Die E-Mail %name% löschen? WARNUNG - Dadurch werden auch alle damit verbundenen A/B Tests und Übersetzungen gelöscht!"
UserBundle/flashes.ini:mautic.user.user.error.cannotdeleteself="Sie können sich nicht selber löschen."
UserBundle/messages.ini:mautic.user.role.form.confirmbatchdelete="Ausgewählte Rolle löschen?"
UserBundle/messages.ini:mautic.user.role.form.confirmdelete="Die Rolle %name% löschen?"
UserBundle/messages.ini:mautic.user.user.form.confirmbatchdelete="Die ausgewählten Nutzer löschen?"
UserBundle/messages.ini:mautic.user.user.form.confirmdelete="Den Account %name% löschen?"
UserBundle/messages.ini:mautic.user.config.form.saml.idp.default_role.tooltip="Wählen Sie die Standardrolle, um neu erstellte Benutzer zuzuweisen. Um das Erstellen von Benutzern zu deaktivieren, löschen Sie die ausgewählte Rolle und lassen Sie das Feld leer."
ApiBundle/messages.ini:mautic.api.client.form.confirmdelete="API-Client  %name% löschen? Anwendungen, die diesen Client verwenden werden keinen Zugriff auf Mautics API mehr haben"
WebhookBundle/messages.ini:mautic.webhook.form.confirmbatchdelete="Ausgewählte Webhooks löschen?"
WebhookBundle/messages.ini:mautic.webhook.form.confirmdelete="Webhook %name% löschen?"
FormBundle/messages.ini:mautic.form.form.confirmbatchdelete="Ausgewählte Formulare löschen? Dadurch werden auch ALLE Ergebnisse dieser Formulare gelöscht!"
FormBundle/messages.ini:mautic.form.form.confirmdelete="Das Formular %name% löschen?  Dadurch werden auch ALLE Ergebnisse dieser Formulare gelöscht!"
FormBundle/messages.ini:mautic.form_results.form.confirmbatchdelete="Die ausgewählten Ergebnisse löschen?"
FormBundle/messages.ini:mautic.form.results.form.confirmdelete="Dieses Ergebnis löschen?"
LeadBundle/messages.ini:mautic.campaign.lead.deletecontact="Kontakt löschen"
LeadBundle/messages.ini:mautic.lead.field.form.confirmbatchdelete="Ausgewählte benutzerdefinierte Felder löschen? WARNUNG: Alle Werte dieser Felder in vorhandenen Kontakten werden ebenfalls gelöscht."
LeadBundle/messages.ini:mautic.lead.field.form.confirmdelete="Das benutzerdefinierte Feld %name% löschen? WARNUNG: Alle Werte dieses Felds in vorhandenen Kontakten werden ebenfalls gelöscht."
LeadBundle/messages.ini:mautic.lead.lead.events.delete="Kontakt löschen"
LeadBundle/messages.ini:mautic.lead.lead.form.confirmbatchdelete="Die ausgewählten Kontakte löschen?"
LeadBundle/messages.ini:mautic.lead.lead.form.confirmdelete="Diesen Kontakt löschen?"
LeadBundle/messages.ini:mautic.lead.lead.social.removecache="Die Netzwerkdaten von diesem Kontakt löschen."
LeadBundle/messages.ini:mautic.lead.list.form.confirmbatchdelete="Ausgewählte Segmente löschen?"
LeadBundle/messages.ini:mautic.lead.list.form.confirmdelete="Das Segment %name% löschen?"
LeadBundle/messages.ini:mautic.lead.note.confirmdelete="Diese Notiz löschen?"
LeadBundle/messages.ini:mautic.company.form.confirmdelete="Dieses Unternehmen löschen?"
LeadBundle/messages.ini:mautic.company.form.confirmbatchdelete="Diese Unternehmen löschen?"
LeadBundle/messages.ini:mautic.segment.form.confirmdelete="Das Segment %name% löschen?"
NotificationBundle/messages.ini:mautic.notification.form.confirmbatchdelete="Die ausgewählten Web-Benachrichtigungen löschen?"
NotificationBundle/messages.ini:mautic.notification.form.confirmdelete="Web-Benachrichtigung %name% löschen?"
AssetBundle/messages.ini:mautic.asset.asset.form.confirmbatchdelete="Die ausgewählten Assets löschen?"
AssetBundle/messages.ini:mautic.asset.asset.form.confirmdelete="Asset %name% löschen?"
CampaignBundle/messages.ini:mautic.campaign.form.confirmbatchdelete="Wollen Sie die ausgewählte Kampagne löschen?"
CampaignBundle/messages.ini:mautic.campaign.form.confirmdelete="Wollen Sie die Kampagne %name% löschen?"
SmsBundle/messages.ini:mautic.sms.form.confirmbatchdelete="Ausgewählte SMSen löschen?"
SmsBundle/messages.ini:mautic.sms.form.confirmdelete="SMS %name% löschen?"
PointBundle/messages.ini:mautic.point.form.confirmbatchdelete="Die ausgewählten Punkte Aktionen löschen?"
PointBundle/messages.ini:mautic.point.form.confirmdelete="Die Punkte-Aktion %name% löschen?"
PointBundle/messages.ini:mautic.point.trigger.form.confirmdelete="Den Trigger %name% löschen?"
PointBundle/messages.ini:mautic.point.group.form.confirmdelete="Die Punktgruppe %name% löschen?"
ChannelBundle/messages.ini:mautic.channel.message.form.confirmdelete="Diese Nachricht löschen?"
ChannelBundle/messages.ini:mautic.message.form.confirmdelete="Die Marketingnachricht löschen, %name%?"
MauticTagManagerBundle/messages.ini:mautic.tagmanager.tag.form.confirmdelete="Markierung löschen?"
MauticTagManagerBundle/messages.ini:mautic.tagmanager.form.confirmdelete="Markierung löschen?"
MauticSocialBundle/messages.ini:mautic.mautic.social.monitoring.form.confirmdelete="Überwachung löschen?"
MauticSocialBundle/messages.ini:mautic.integration.Twitter.form.confirmdelete="Tweet löschen?"
MauticSocialBundle/messages.ini:mautic.mautic.social.monitoring.form.confirmbatchdelete="Ausgewählte Überwachungen löschen?"
MauticSocialBundle/messages.ini:mautic.monitoring.form.confirmdelete="Wollen Sie das Social Monitoring %name% löschen?"
ReportBundle/messages.ini:mautic.report.report.form.confirmbatchdelete="Die ausgewählten Reports löschen?"
ReportBundle/messages.ini:mautic.report.report.form.confirmdelete="Den Report %name% löschen?"
MauticFocusBundle/messages.ini:mautic.focus.form.confirmbatchdelete = "Löschen der ausgewählten Focus Items?"
MauticFocusBundle/messages.ini:mautic.focus.form.confirmdelete="Focus Item löschen, %name%?"
DashboardBundle/messages.ini:mautic.dashboard.delete_layout="Dieses Layout löschen?"
DashboardBundle/messages.ini:mautic.dashboard.widget.header.delete="Widget löschen"
yxuser@server:/var/www/html/mautic/translations/de#
