### ISSUE TITLE
Typo in the code that prevent adding files/images  Froalaeditor

### ISSUE THREAD

**Issue by Nape** [mautic/mautic#14133]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.2.4

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Since commit: ed9a9bef2809d0fdab1b93de38dd2d9138c8f190

There is a typo in the builder.js code, line 1368. This prevent file/images integration.

Should be : typeof FroalaEditorForFileManager !== 'undefined' not **underfined**

```
window.document.fileManagerInsertImageCallback = function(selector, url) {
    if (Mautic.isCodeMode()) {
        Mautic.insertTextAtCMCursor(url);
    } else {
HERE  ====>>>     if (typeof FroalaEditorForFileManager !== 'underfined') { <<<==== HERE
            if (typeof FroalaEditorForFileManagerCurrentImage !== 'undefined') {
                FroalaEditorForFileManager.image.insert(url, false, {}, FroalaEditorForFileManagerCurrentImage);
            } else {
                FroalaEditorForFileManager.image.insert(url);
            }
        } else {
            if (typeof FroalaEditorForFileManagerCurrentImage !== 'undefined') {
                mQuery(selector).froalaEditor('image.insert', url, false, {}, FroalaEditorForFileManagerCurrentImage);
            } else {
                mQuery(selector).froalaEditor('image.insert', url);
            }
        }
    }
};
```

### How can we reproduce this issue?

Try uploading image/files Froalaeditor from Elfinder, Ex: Dynamic content.

### Relevant log output

<img width="1723" alt="Capture d’écran, le 2024-09-20 à 13 45 59" src="https://github.com/user-attachments/assets/5c536b68-ea60-4c58-a2b5-514ad3bddb16">

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for the bug report @Nape - would you like to make a PR to address this?

**Comment by TheMarvelFan** [comment]
Hi @RCheesley ,

I would like to take up this issue.

Thanks!

**Comment by imaabasiee** [comment]
@RCheesley can this issue be assigned to me?

**Comment by RCheesley** [comment]
Hi @TheMarvelFan as you were the first to request please feel free to work on this - you can make a PR against the 5.1 branch. Sorry for the long delay in getting back to you!

**Comment by TheMarvelFan** [comment]
Hi @RCheesley ,

Thanks for assigning this issue to me. I have created a PR to fix it. 
Please review the changes and let me know if any further modifications are required.

Thanks!

**Comment by RCheesley** [comment]
Great, you're already assigned and I've set the PR up so folks know it's open for testing!

**Comment by RCheesley** [comment]
Closing this issue as the fix is merged! Thanks @TheMarvelFan
