### ISSUE TITLE
Forms Listing - not color point at the categories

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#14136]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2.23

### What browsers are you seeing the problem on?

Firefox

### What happened?

not the big problem but: In all other listings the color column has a color point left of the category name. It's missing in the forms listing.

### How can we reproduce this issue?

Check out the forms listing

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for flagging this up @stefan-franz - I've assigned it to our UI/UX team who have been working on this.

**Comment by andersonjeccel** [comment]
@RCheesley 5.x

hm, it's fixed for the next version

![image](https://github.com/user-attachments/assets/7845c93d-496c-4549-8c6f-788ebd67f318)

**Comment by RCheesley** [comment]
Awesome, thanks @andersonjeccel - @stefan-franz I will close this one as it's already fixed.
