### ISSUE TITLE
Changing language in system settings doesn't affect system

### ISSUE THREAD

**Issue by marquesine** [mautic/mautic#14137]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.1.29

### What browsers are you seeing the problem on?

Chrome

### What happened?

A bug happened!

### How can we reproduce this issue?

Step 1: Fresh install Mautic 5.1.1 using Composer
Step 2: Go to Configuration -> System Settings
Step 3: Set default language to other than English*
Step 4: See that the system language actually didn't change and everything is still in English

*in my case I set it to Portuguese (Brazil)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there, did you clear your cache?

Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
