### ISSUE TITLE
Sugar CRM integration not working

### ISSUE THREAD

**Issue by eliasbaixas** [mautic/mautic#1413]
Hello, I've tried the SugarCRM integration in the **hosted** mautic version against my SugarCRM installation (v 6.x/community) and worked great.

Then I proceeded to integrate my own installed mautic (on my own server), using
 master (d2c640919fa27b814983f9b565122eb499c462ba) and tag 1.2.4,
but could not make any of them to work. Its always the same message: 

I completed all the fields (with the same values that do work in hosted mautic): 
sugar URL (with the url of my sugar installation),
client key: I put the username I use to enter my mautic installation (as hosted mautic does)
client secret: I put my mautic installation password (the same hosted mautic does)
sugarCRM username: I put my sugar installation name (the same for hosted mautic, which works)
sugar crm password: the password
sugarCRM version: 6.x/community,

then I get always the same error (tried everything, reinstalled several times DB, changed mautic versions...):

"Authorization failed with the error message, 'Keys are not available for this transaction to take place. Please verify your settings then try again.'"

this is the value for error message: "mautic.integration.missingkeys",

what makes me think that somehow mautic is not saving all the values passed from the form.
Another hint that makes me think this, is that if I fill in all the fields for the integration, then click "save" (instead of authorize app), then I open again the Sugar integration,

the some fields are blank, which does not happen in hosted mautic.

in the database, if I select from plugin_integration_settings, I see all the keys are in place:
{s:12:"sugarcrm_url";s:45:"redacted";s:9:"client_id";s:45:"redacted";s:13:"client_secret";s:45:"redacted";s:8:"username";s:45:"redacted";s:8:"password";s:45:"redacted";s:7:"version";s:45:"redacted";}

(of course I changed the real values for "redacted"), so it seems to be saved in the database....

I dont know what else to try :)

if anyone would help, I can provide access to the server, and credentials mautic installation and sugar.

**Comment by eliasbaixas** [comment]
by the way: I'm seeing this error in app/log:
mautic.WARNING: PHP Warning: mcrypt_decrypt(): Key of size 5 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported - in file /home/mautic/mautic/app/bundles/CoreBundle/Helper/EncryptionHelper.php - at line 82 [] []

could it have anything to do with the bug ?

**Comment by eliasbaixas** [comment]
Hi !

It's fixed: it was this same problem reported here:
https://github.com/mautic/mautic/pull/1396

I changed those 2 lines and it worked like a charm :dancer: 

thanks !

**Comment by dongilbert** [comment]
This has now been fixed in core and will be included in the next release. #1396

**Comment by hugovictor10** [comment]
Very well friends.
What I mean is that SuiteCRM died for everyone. It will only exist for the bastards who charge $ 120 a year to link to Mautic for linking free software! For all of us who love Mautic's free code, we have SuiteCRM, a junk that only serves the interest of these outcasts.
Run away from SuiteCRM, this shit has no integration with Mautic, it's just wasting precious time.

And please my friends, a simple solution.
