### ISSUE TITLE
Landingpage is not responsive ready

### ISSUE THREAD

**Issue by stefan-franz** [mautic/mautic#14135]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2.23

### What browsers are you seeing the problem on?

Firefox

### What happened?

The landingpage is not viewed right at a smartphone. 
Here for testing: 
https://info.stefan-franz.de/newsletter-anm-test

But the preview feature of the landing page shows also the error. Maybe the landingpage editor is under construction - i wanted only report this.

### How can we reproduce this issue?

You can test my link

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
