### ISSUE TITLE
ckeditor.js Failing to Load

### ISSUE THREAD

**Issue by josh-ht** [mautic/mautic#14156]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

Other (please specify if relevant in the bug report)

### PHP version

8.2.22

### What browsers are you seeing the problem on?

Microsoft Edge

### What happened?

Contact notes dialog will not close with save or cancel button. If save is clicked, and then the page refreshed the note does appear as saved. In the console ckeditor.js shows as 404 and then multiple uncaught reference errors appear as a result.

### How can we reproduce this issue?

Step 1: Click on contact
Step 2: Click notes
Step 3: Add Note
Step 4: Click save or cancel
Step 5: Refresh page

Troubleshooting:
Installed Mautic via CyberPanel.
Ensured that PHP is 8.2+ and Mautic is 5.1.1
No recommendations in System Info
Made sure node and npm are installed per [issue #1226](https://github.com/usmannasir/cyberpanel/issues/1226)

### Relevant log output

```shell
GET https://[mydomain.com]/media/libraries/ckeditor/ckeditor.js?v94732b26 net::ERR_ABORTED 404 (Not Found)

Uncaught ReferenceError: ClassicEditor is not defined
    at Mautic.InitCkEditor (app.js?v94732b26:406:48)
    at Mautic.ConvertFieldToCkeditor (app.js?v94732b26:401:65)
    at HTMLTextAreaElement.<anonymous> (app.js?v94732b26:75:8)
    at Function.each (libraries.js?v94732b26:98:212)
    at jQuery.each (libraries.js?v94732b26:89:190)
    at Object.onPageLoad (app.js?v94732b26:73:409)
    at Mautic.processModalContent (app.js?v94732b26:353:8)
    at Object.success (app.js?v94732b26:344:130)
    at fire (libraries.js?v94732b26:271:351)
    at Object.fireWith [as resolveWith] (libraries.js?v94732b26:276:179)
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by escopecz** [comment]
I cannot replicate on the latest 5.x branch (used for development) but even if I switch to 5.1 I can create the note and refresh the page without any issue:
![Screenshot 2024-10-02 at 16 19 17](https://github.com/user-attachments/assets/03048328-bc6d-4179-9e77-4f9d22115eb2)

Please run these commands:
1. `npm ci`
2. `bin/console mautic:assets:generate`
