### ISSUE TITLE
Custom Unsubscribe for individuals

### ISSUE THREAD

**Issue by ps92** [mautic/mautic#1415]
Mautic lacks one very important feature as a open source. Currently, there is no way such that every individual can have a separate unsubscribe link, that could be selected form the database.

**Comment by escopecz** [comment]
Not sure what you mean by "as a open source". Would the feature be less important if Mautic would be a closed source?

What exactly the "Unsubscribe for individuals" means?

**Comment by ps92** [comment]
I apologies about asking questions naively. 
Assume a case where I am sending a email to a group of people, each of which will have a link such as http://example.com/u/{hash_id}, where {hash_id} relates the unsub link with a user. So, the appropriate link (or the unsubscribe link for individuals: unique and permanent hash associated with a person} gets replaced in case of {unsubscribe_url}.
Even Mautic does that; though, Mautic generates that on its own, and redirects to its own custom pages. 
There is no direct way (which can be assumed a feature) is missing from it. 
As a !(open source), it would actually have been according to a customer's requirement.

**Comment by escopecz** [comment]
I'm sorry, but I still not get what you mean. Mautic generates the unsubscribe URL with a unique hash for each lead. The unsubscribe URL get's replaced for the `{unsubscribe_url}` token. So what is it you are suggesting?

I also still not get the open source part, but let's not focus on that since that is not probably related to the issue.

**Comment by ps92** [comment]
Sorry for the late reply. 
So, if I have a unsubscribe link that is example.com/u/woeinwoie where "woeinwoie" is a hash it is the unsubscribe link for user A. Similarly, for user B, it can be example.com/u/woeinwowerwefqeewr
Now, what I meant was, if I create a campaign and send it with unsubscribe link, it should be able to send it with custom link link example.com/u/woeinwoie for user A and example.com/u/woeinwowerwefqeewr for user B in every case in every campaign, instead of the link that mautic generates. 
Currently, I can only replace it with a single custom unsubscribe link for all users together as example.com/unsubscribe in the config page.

**Comment by escopecz** [comment]
I still don't get it. You want to add a custom unsubscribe URL to Mautic emails which goes somewhere else than back to Mautic? What's wrong with the unsubscribe URL Mautic generates? Is `example.com` in your example Mautic or some other website?

**Comment by ps92** [comment]
I am deep linking every user to different website. I want each of unsubscribe link to be replaced by my custom link.

**Comment by escopecz** [comment]
The unsubscribe link is custom for each lead.

**Comment by ps92** [comment]
Yes.

**Comment by ps92** [comment]
Though, we can always insert a lead field "unsubscribe", and replace the {unsubscribe_text} with `'<a contenteditable="false" style="line-height: 20.8px;" href="%7Bleadfield=unsubf%7D">Unsubscribe</a>'`. 
This solved my problem. Though, I don't think this is a good way.

**Comment by exsesx** [comment]
I vote for the same functionality...

I have my website and I want to redirect my customers to the custom page, get the unique hash or encrypted data, decrypt it if I have to and let users update their  notification settings.

So far I don't see how this can be done.

**Comment by exsesx** [comment]
Small update:

Possible solution was published [here](https://forum.mautic.org/t/embed-preference-center-and-unsubscribe-into-my-site-unique-user-identifier/17073).

Author suggested to use a custom field and populate it with some unique value that can be used later.

This may be a solution to the described issue 🤷🏼‍♂️

Perhaps this will be useful to someone.
