### ISSUE TITLE
break javascript and css files

### ISSUE THREAD

**Issue by alanbarcelos1998** [mautic/mautic#14150]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.0

### Way of installing

I'm using a Docker image from https://hub.docker.com/r/mautic/mautic

### PHP version

8.1.0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

After installing Mautic 5 via docker, when I access the domain it redirects to the installation page. On the installation page there are the following errors appearing in the browser console.

![erromauticv5](https://github.com/user-attachments/assets/36a16a7d-60ad-441b-b16e-67e031eb8c09)

I deleted line 62 from the Dockerfile, but it had no effect.

### How can we reproduce this issue?

installing mautic v5 via docker

### Relevant log output

```shell
<script src="/media/js/libraries.js?vcc1b855a" data-source="mautic"></script>
<script src="/media/js/app.js?vcc1b855a" data-source="mautic"></script>
<script src="/media/libraries/ckeditor/ckeditor.js?vcc1b855a" data-source="mautic"></script>

<script src="/app/bundles/InstallBundle/Assets/install/install.js?vcc1b855a" data-source="mautic"></script>
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by escopecz** [comment]
I do not have any issues with installing Mautic via Docker. Please create this issue with https://github.com/mautic/docker-mautic with concrete steps that you took to install Mautic so it can be reproduced. I'll close this issue as it's not related to Mautic but to the installation via Docker which is another repository.
