### ISSUE TITLE
Contacts Page | Date being displayed incorrectly

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#14163]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2

### What browsers are you seeing the problem on?

Chrome

### What happened?

I store a date time value as a custom field for contacts. 
The date time is rendered correctly on the contact's page: 
![image](https://github.com/user-attachments/assets/ad46d6dd-024f-4f7a-8479-6de2672874fd)

But the date time is wrong on the contacts list page: 
![image](https://github.com/user-attachments/assets/2d51f6fd-fe23-47f1-bca9-f432c9161119)

The timezone is set correctly for my region (Africa/Johannesburg)

### How can we reproduce this issue?

Step 1: Create a date time field for a contact and populate it. Mine works through the API. 
Step 2: Open the contact list and make note of the date time field. 
Step 3: Open the contact's details and make note of the date time field, the values will likely be different. 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by escopecz** [comment]
I cannot replicate. It shows the same time in the detail as well as in the list of contacts:
<img width="218" alt="Screenshot 2024-10-06 at 06 38 46" src="https://github.com/user-attachments/assets/e209a55e-5fc9-4faa-9d06-2252a6d6e08e">
<img width="424" alt="Screenshot 2024-10-06 at 06 38 33" src="https://github.com/user-attachments/assets/443b5cb1-8ccf-4c13-8426-8e774bc00b97">
Are you sure you are looking at the right value? The labels are different. "Created On" vs "Date Added"

**Comment by RCheesley** [comment]
@vexersa can you please respond to the follow up clarification point, so we can close the issue if it's no longer required? Thanks!

**Comment by RCheesley** [comment]
Closing due to lack of feedback, feel free to request a re-open.
