### ISSUE TITLE
Mailchimp integration does not work

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#1416]
Running Mautic 1.2.4, I select Mailchimp, enter my Mailchimp username and an API key generated for this Mautic instance, which is enabled.

Enable and save plugin.

Open plugin again, click on Features

**Expected behaviour:** Lists available for selection, fields available for mapping
**Actual behaviour:** No lists are shown, nothing appears to be synchronised.

Nothing appears to be showing in the logs at all, so it doesn't even seem to be throwing any errors - nothing to go on really!

**Comment by RCheesley** [comment]
Linking to PR which introduced API-based authorisation in case it's related to this - https://github.com/mautic/mautic/pull/1184 - I cleared out my Mailchimp settings manually from the database as previously it wasn't working with the old app settings for some time (see https://github.com/mautic/mautic/issues/1274)

**Comment by escopecz** [comment]
I'm really sorry it doesn't work for you. I tested it again and worked for me like a charm:
![mautic-mailchimp-list](https://cloud.githubusercontent.com/assets/1235442/13005934/d330755c-d185-11e5-951b-acaf7ff28488.png)

I followed this tutorial: https://www.mautic.org/docs/plugins/mailchimp.html

What do you add to the username field? It's not the email, but the Mailchimp username. To see the username, go to Mailchimp / Settings / Users:

![mailchimp-username](https://cloud.githubusercontent.com/assets/1235442/13006005/41d80f7e-d186-11e5-8f34-a0cee825c1fc.png)

**Comment by RCheesley** [comment]
I am using the username, and the API key generated by Mailchimp.  Happy to
give you access to verify/test.

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 12 February 2016 at 11:44, John Linhart <notifications@github.com> wrote:

> I'm really sorry it doesn't work for you. I tested it again and worked for
> me like a charm:
> [image: mautic-mailchimp-list]
> <https://cloud.githubusercontent.com/assets/1235442/13005934/d330755c-d185-11e5-951b-acaf7ff28488.png>
>
> I followed this tutorial:
> https://www.mautic.org/docs/plugins/mailchimp.html
>
> What do you add to the username field? It's not the email, but the
> Mailchimp username. To see the username, go to Mailchimp / Settings / Users:
>
> [image: mailchimp-username]
> <https://cloud.githubusercontent.com/assets/1235442/13006005/41d80f7e-d186-11e5-8f34-a0cee825c1fc.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/1416#issuecomment-183291191>.
>

-- 

Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by escopecz** [comment]
Public update: Ruth tried my Mailchimp credentials (which work in my Mautic instance) and recorded a screen grab which shows they doesn't work for her.

Ruth, could you try if https://github.com/mautic/mautic/pull/1396 will fix it? Otherwise we'll have to debug on your server to find the problem.

**Comment by RCheesley** [comment]
Thanks I tried to deploy that fix but still no joy unfortunately!

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 12 February 2016 at 17:29, John Linhart <notifications@github.com> wrote:

> Public update: Ruth tried my Mailchimp credentials (which work in my
> Mautic instance) and recorded a screen grab which shows they doesn't work
> for her.
>
> Ruth, could you try if #1396 <https://github.com/mautic/mautic/pull/1396>
> will fix it? Otherwise we'll have to debug on your server to find the
> problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/1416#issuecomment-183421641>.
>

-- 

Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by teamtmedia** [comment]
Sorry about this.  Hunting high and low for a solution.  Did you ever resolve this?  If so, how did you get it sorted?

**Comment by RCheesley** [comment]
No, did not get this sorted but haven't managed to test yet in latest
version.

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 13 May 2016 at 07:51, Justin Thomas <notifications@github.com> wrote:

> Sorry about this. Hunting high and low for a solution. Did you ever
> resolve this? If so, how did you get it sorted?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/1416#issuecomment-218965382>
>

-- 

Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by teamtmedia** [comment]
Thanks Ruth.  To let you know that I started this process this morning on 1.3.1 and have continued to 1.4.0 with no change.  I can find nothing that I'm not doing right and I must have tried 20 different iterations of username and API key.  I use the mailchimp API on the main site that this mautic instance is supporting and have no issues.

Naturally I have put my weight in the thread in the forum but nothing yet.

**Comment by maartenroelofs** [comment]
Hi All - did this issue ever got resolved? Same error here (1.4.1). Created APP in Mailchimp, but still 'invalid key' error.

**Comment by teamtmedia** [comment]
No, still no joy for me on 3 different installations (on 2 different servers).

**Comment by maartenroelofs** [comment]
Hi. I just suddenly got it to work. Not 100% sure if it is "THE" answer, but i did the following; 
in /plugins/Mautic/EmailMarketingBundle/Api/MailchimpApi.php 

     /*$apiUrl               = 'https://'.$dc.'.api.mailchimp.com'; */
            $apiUrl               = 'https://us8.api.mailchimp.com';

>> the us8 is the datacenter, for some reason the data center was not coming through. You can find it by logging in to mailchimp and see what is the url.

**Comment by teamtmedia** [comment]
Yep, confirmed working.  Take the glory and take this back to 
https://www.mautic.org/community/index.php/90-mailchimp-integration/p1#p10314

**Comment by maartenroelofs** [comment]
I mentioned it in the slack channel. Btw- since we seem to have a similar level of knowledge and try to accomplish same stuff, can we connect on chat? maarten.roelofs@gmail.com . Lists are showing, but users are not added to the list (yet).

**Comment by RCheesley** [comment]
As far as I am aware this is resolved now.
