### ISSUE TITLE
Remove Preference Center "I want to receive email"

### ISSUE THREAD

**Issue by DogByteMarketing** [mautic/mautic#14162]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1

### What browsers are you seeing the problem on?

Not relevant

### What happened?

![image](https://github.com/user-attachments/assets/cb5de307-0e28-4a42-a62d-b201297701eb)
Currently the "I want to receive email" checkbox simply disables the "Do not contact more than" and "messages each" fields and essentially just empties them on save. This may be confusing to contacts looking to unsubscribe, as when the contact clicks save, the "I want to receive email" checkbox is again checked.

With #14114 adding unsubscribe from all functionality, it may be better to remove this checkbox to avoid confusion.

### How can we reproduce this issue?

- Build a preference center page
- Build an email
- Assign the email your preference center page
- Assign email to a segment with only yourself in it
- Send the email
- Click unsubscribe
- Uncheck I want to receive email
- Click save

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by escopecz** [comment]
Mautic supports multiple channels. Like SMS, push notifications, emails. The checkbox is there so the contact could unsubscribe from a specific channel but be subscribed to others.

The other fields are there so the contact could configure that they want to receive emails but not more than 1 per week.

Does it make sense?

Is the bug that the checkbox value isn't being saved?

**Comment by DogByteMarketing** [comment]
> Mautic supports multiple channels. Like SMS, push notifications, emails. The checkbox is there so the contact could unsubscribe from a specific channel but be subscribed to others.
> 
> The other fields are there so the contact could configure that they want to receive emails but not more than 1 per week.
> 
> Does it make sense?
> 
> Is the bug that the checkbox value isn't being saved?

That makes sense. Our clients have other systems for SMS and push notifications, so if they were to use SMS within Mautic, there would be a checkbox to unsubscribe from SMS as well? If that's the case, then yes, saving the unchecked input does nothing. We even confirmed by checking the contact and they do not have the Do Not Contact flag on their profile. If it isn't supposed to set them as Do Not Contact, but just sets it so they receive no emails, this is fine as well, but the checkbox should remember their preference after they save, as we have received complaints from contacts trying to unsubscribe. We've had to disable the preference center so that they can unsubscribe.

**Comment by escopecz** [comment]
Thanks for confirming. I was able to replicate it and it is fixed here:

https://github.com/mautic/mautic/pull/14175

Please test that PR and approve it if you find it is fixing the issue. It will help greatly to get this fix into the next Mautic release.

**Comment by DogByteMarketing** [comment]
Tested and approved. Thank you!
