### ISSUE TITLE
Mautic is skipping the port number in the email tracking pixel URLs

### ISSUE THREAD

**Issue by girish1605** [mautic/mautic#1417]
Hey,

Looks like Mautic is skipping the port number in the tracking pixel (and unsubscribe) URLs when Mautic is configured on a non standard port.

In my case, I installed and configured Mautic to run on http://subdomain.mydomain.com:8080/mautic

The value of "Site Url" in Mautic configuration is also set to "http://subdomain.mydomain.com:8080/mautic"

However, the tracking pixel URL and the Unsubscribe URL's are missing the port number. For example, I got the following as the tracking pixel URL, in the email source:

Tracking pixel:	
```
<img src=3D"http://subdomain.mydomain.com/mautic/email/XXXXXXXXXX.gif" ... />

Email unsubscribe header:
List-Unsubscribe: <http://subdomain.mydomain.com/email/unsubscribe/56b496c777ffb>
```
Note that the port number 8080 is missing in both the above cases.

**Comment by dongilbert** [comment]
@girish1605, could you please test the following solution:

Remove the port from your site_url config value. The new value will be `http://subdomain.mydomain.com/mautic`

Create a new config entry with the key of `http_port` and a value of `8080`. You can add this to your local.php config, right below site_url
```php
...
'site_url' => 'http://subdomain.mydomain.com/mautic',
'http_port' => 8080
...
```
