### ISSUE TITLE
"Visible on quick add" should be disabled when creating a Custom Field for Company object

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#14178]
### Mautic Series

5.1.x series

### Mautic installed version

5.x

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

Not relevant

### What browsers are you seeing the problem on?

Chrome

### What happened?

When creating a custom field, you have some options like choosing whether your field will be available for contacts or companies. When you select the object Contact, it makes sense to provide the option "Visible on quick add", because contacts actually have the quick add functionality where you make this field available on a modal with some other few fields to avoid opening the screen where all contact fields are displayed.

But when you are creating a custom field for a company, you do not have the quick add functionality,  but this toggle keeps visible and interactive anyway. That's problematic and confusing for the user because no matter what you choose, absolutely nothing will happen.

To fix this, the `<div class="toggle">` element for the field "Visible on quick add" must receive the class `toggle--disabled` when Object is set to Company, so the final element becomes `<div class="toggle toggle--disabled">` to block user interaction and display the not-allowed cursor.

### How can we reproduce this issue?

1. Open Custom Fields
2. Create New
3. In the select field Object, choose Company
4. See that the toggle for Visible on quick add remains active and interactive

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for flagging up the bug @andersonjeccel and for the detailed bug report!

**Comment by laurielim** [comment]
Could you please assign this issue to me? I can create a PR for it.

**Comment by andersonjeccel** [comment]
@laurielim Done

Remember to check existing rules in the corresponding JS file, so your code get integrated in an easier way :wink:

Ping me if you need any help or guidance, I'm available in Mautic's Slack as `@aj` or in the #tt-ux_ui channel

---

Have a look at these 2 PRs I made recently as reference:

- https://github.com/mautic/mautic/pull/14004
- https://github.com/mautic/mautic/pull/14003

Have fun! 😄

**Comment by laurielim** [comment]
@andersonjeccel thanks, just created the PR, it's ready for review. Let me know if there's anything missing.
