### ISSUE TITLE
Appearance - When the "Cancel" button is clicked, the selected theme is still applied 

### ISSUE THREAD

**Issue by MojisolaaaO** [mautic/mautic#14171]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.0

### Way of installing
Other (please specify if relevant in the bug report)

### PHP version

8.3.8

### What browsers are you seeing the problem on?

Chrome

### What happened?

While testing this PR [#13767](https://github.com/mautic/mautic/pull/13767) on GitPod, I noticed that when the "Cancel" button is clicked, the selected theme is still applied rather than reverting to the previous state. 
[Video of the Bug](https://monosnap.com/file/OMEY1Qq3bJTCIUwGtANgLjCEqxgVfg)

**Suggested Fix:** Ensure the cancel action reverts the theme selection to the original theme before changes were applied.
 

### How can we reproduce this issue?

Step 1: Install Mautic
Step 2: Input valid credentials
Step 3: Click on the "Login" button
Step 4: Click on the Profile icon at the top right of the screen
Step 5: Click on Account
Step 6: Click on the Appearance
Step 7: Select a theme
Step 8: Click on the "Cancel" button

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
@MojisolaaaO looking back through the comments on the PR https://github.com/mautic/mautic/pull/13767 where you spotted this, it seems like it's resolved?
