### ISSUE TITLE
"Is Unique Identifier" should be disabled when creating a Custom Field for Company object

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#14179]
### Mautic Series

5.1.x series

### Mautic installed version

5.x

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

Not relevant

### What browsers are you seeing the problem on?

Chrome

### What happened?

When creating a custom field, you have the Object field to choose if your field will be available for contacts or companies. When you select the object Contact, it makes sense to provide the option "Is Unique Identifier" as we're talking about what information will be used to differentiate people when creating new contacts.

When you are creating a custom field for a company, the "Is Unique Identifier" does not apply as this configuration is available only for contacts, but this toggle keeps visible and interactive. That's problematic and confusing for the user because no matter what you choose, absolutely nothing will happen.

To fix this, the `<div class="toggle">` element for the field "Is Unique Identifier" must receive the class `toggle--disabled` when Object is set to Company, so the final element becomes `<div class="toggle toggle--disabled">` to block user interaction and display the not-allowed cursor.

### How can we reproduce this issue?

1. Open Custom Fields
2. Create New
3. In the select field Object, choose Company
4. See that the toggle for "Is Unique Identifier" remains active and interactive

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by laurielim** [comment]
Just realised this is similar to #14178 so depending on how it is fixed, I can create a PR for this one too.

**Comment by andersonjeccel** [comment]
@laurielim Would you like to solve this too? It'll use the same structure from your PR

**Comment by laurielim** [comment]
@andersonjeccel yes I can create a PR during the weekend for this

**Comment by andersonjeccel** [comment]
@laurielim just awesome, thanks!

**Comment by laurielim** [comment]
@andersonjeccel Ok, PR is up and ready for review.

**Comment by andersonjeccel** [comment]
Hi @laurielim, thank you! 😄

**Comment by alexhammerschmied** [comment]
I just found this and it makes it impossible to use other fields as unique identifiers for companies then a company name. But if i have a i.e. a customer number it makes absolute sense to flag the customer number as unique identifier instead of the name. Names are the worst to use as unique identifiers, because the are case sensitive, sometimes spelled wrong by even owners and empoloyees and more. I'd rather have the option instead of closing it down
