### ISSUE TITLE
Single Email per Lead is not tracking Links

### ISSUE THREAD

**Issue by timzuidgeest** [mautic/mautic#1418]
Hi guys!

So when I want to send an email to a lead individually, I go to the lead, 'edit' and then 'send email'. When I include a link in that email, it won't get a unique tracking link. I have to manually add the {externallink}. 

Guess it's a small bug?

**Comment by escopecz** [comment]
Could you please provide the exact steps to recreate the issue?

**Comment by timzuidgeest** [comment]
Sure.
Step 1.
Go to Leads > Manage Leads.
Step 2.
Click on a specific lead.
Step 3.
Click on the dropdown arrow at 'edit' and chose 'Send email'
Step 4. In 'Send custom email to...'
I write up my email. I use a link like I'd normally do (via the editor), I
only provide the link, and fill nothing in in the 'advanced' tab. I
wouldn't know what to fill in over there anyway.
Step 5. Send the email
And in the email, the url is the exact URL I've used in the email, and not
a 'tracked' url via Mautic. So there is no clue as to know if that URL was
clicked.

Only when I use {externallink=http://www.url.com} the URL gets changed to a
trackable URL.. But that shouldn't work anymore, according to the manual,
right? Otherwise, how should anybody know to use that specific parameter?

Cheers!

**Comment by escopecz** [comment]
Ah, I remember we spoke in the forum or in the chat about this issue. Yes, the link tracking works only for the actual emails. I mean that they must be related to a row in the emails DB table. If you send an email to a lead directly, they are not related to an email where you could then see (in an email detail) if the lead clicked some link. So yes, I'll mark this as a feature request even though I personally don't see a simple solution for this issue. Maybe someone else will.

**Comment by timzuidgeest** [comment]
Hi John,
It's a bit to specific for me, as non-db junky ;-). But I don't understand
why there should be a simple solution..? The way I see it, if I use the
{externallink} feature, it works.. So can't you just track all links? I
mean, in the whole lead timeline, I can see that they've clicked a link
inside an e-mail.. So it's valuable..
And for my understanding, I understood that when they click on that link in
the email, they also get tracked further on when they're on my website..
Not? (Because the cookie can relate the unique ID from the tracked Link to
the lead?).
Thank you for looking into this! All the best :)

**Comment by alanhartless** [comment]
This should be resolved in latest versions of Mautic.
