### ISSUE TITLE
"Field order" should display only fields for the same object when creating a Custom Field

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#14181]
### Mautic Series

5.1.x series

### Mautic installed version

5.x branch

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

Not relevant

### What browsers are you seeing the problem on?

Chrome

### What happened?

When creating a new custom field, no matter which object you select (contact or company), all fields for all objects keep visible for selection in "Field order".
"Field order" is responsible for placing the new custom field you're creating above the chosen. 

Example: Now I'm creating "X Place", but I already have "Beautiful input" created previously. If "Field order" is set to "Beautiful input", my new field will appear above the selected one.

I might be creating "X Place" for the object Company, but "Beautiful input" (created for Contacts), is still visible. Selecting it will do absolutely nothing.

To fix this issue, we need the "Field order" options to become updated with the relevant options depending on the value selected for "Object".

### How can we reproduce this issue?

1. Open Custom Fields
2. Create New
3. Set Object to Contact
4. Click on the "Field order" field and see that all fields are displayed
5. Now set Object to Company
6. See an incredible amount of 0 changes, all fields are still there

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by laurielim** [comment]
I can work on this issue and #14180

**Comment by laurielim** [comment]
To clarify, https://github.com/mautic/mautic/pull/14242 should also fix this issue.
