### ISSUE TITLE
"Field order" should display only other custom fields when creating a Custom Field

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#14180]
### Mautic Series

5.1.x series

### Mautic installed version

5.x branch

### Way of installing

I cloned the Mautic repo (not recommended or supported)

### PHP version

Not relevant

### What browsers are you seeing the problem on?

Chrome

### What happened?

Every time you create a new custom field, you have the option to select where to place it (you'd see it later when editing a Contact or Company). But the system doesn't take into account that the Core fields that come by default with Mautic cannot be sorted. 

This means that, if you select, for example, the option "Company name" to place your new custom field above this one, it will simply not happen.

The new custom field will be placed at the bottom of the editing page for the corresponding object, after all Core fields are rendered.

So, if these default fields are fixed, they must not appear as an option for the "Field order". When was select existing custom fields, you can successfully place the new field above the selected field, but that's the only possible situation. 

To fix, "Field order" must display only other existing custom fields, hiding the system default (Core) fields.

### How can we reproduce this issue?

1. Open Custom Fields
2. Create New
3. Click on the "Field order" field and see that Core (system defaults) fields are displayed and cause no changes when used

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by laurielim** [comment]
Hi, I had a look at this and found the property `isFixed` which seems to indicate if a field can be reordered. There are some fields that are installed by default that have it set to false, such as lead.website. Should these be displayed?

**Comment by andersonjeccel** [comment]
@laurielim Could you check if we can place a new custom field above your example?

If yes, then we can just hide all fields that have this fixed property

**Comment by laurielim** [comment]
Yes I was able to place the field website between custom fields.

**Comment by andersonjeccel** [comment]
Nice, I'm here when your PR is ready :)

**Comment by laurielim** [comment]
I've created a PR, if you can please review it when you have time @andersonjeccel

**Comment by andersonjeccel** [comment]
Hey @laurielim, thanks!

Always ping me when you release something, so I can review asap :)

It's great to have your fixes ready in time for the 5.2 release
