### ISSUE TITLE
Copyright symbol not working when sending emails.

### ISSUE THREAD

**Issue by MaKo999HaNa** [mautic/mautic#14187]
### Mautic Series

4.4.x series (not supported)

### Mautic installed version

4.4.12

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

 8.0.30

### What browsers are you seeing the problem on?

Chrome

### What happened?

Hello team!

I use Twig in my emails, and also Code Mode, not GrapeJS.
The problem is that when I want to send a copyright sign in an email, it changes to `:copyright:`
This happens if I send emails through a campaign or as sample.
If I send an email directly to a contact, the symbol works.
I tried to indicate the copyright in different ways:
```
©
&copy; 
&#169;
```
But they all turn into text.

### How can we reproduce this issue?

1. create some email via Code Mode
2. paste for example <p class="copyright">© Mautic </p>
3. save and close email
4. click "send example" button or send email via campaign 

Look at the screenshot to see how it looks:
![copy](https://github.com/user-attachments/assets/963b4fe8-5a25-4405-9307-1bbf99b9adc0)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi @MaKo999HaNa since we won't be doing bugfixes for the 4.x series any more, can you verify if this is still happening in 5.1.1? I believe we merged some PRs which related to similar issues over the last year (eg this PR: https://github.com/mautic/mautic/pull/13337), so it's likely this is already fixed.
