### ISSUE TITLE
No email for trial application being ready. 

### ISSUE THREAD

**Issue by imft-debug** [mautic/mautic#14184]
### Mautic Series

5.1.x series

### Mautic installed version

5.1

### Way of installing

Other (please specify if relevant in the bug report)

### PHP version

8.1

### What browsers are you seeing the problem on?

Not relevant

### What happened?

A trial was requested and its subsequent verification email was also received but no trial activation email was received . 
The trial email inbox doesnt exist as an email was sent to it as well . 

![image](https://github.com/user-attachments/assets/b112fb06-18ce-47fc-909a-91f96e873f4b)
![image](https://github.com/user-attachments/assets/c759a443-903d-4be4-a98c-235d3f1f7da9)

### How can we reproduce this issue?

Step 1:  Create a request for online trial 

### Relevant log output

```shell
N_A
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for raising this @imft-debug but this issue queue is for bugs with Mautic. I'll flag this up with the support team for the Trials and ask them to reach out to you directly. The support email is mautictrials@dropsolid.com - that's the place to reach them.

**Comment by RCheesley** [comment]
Hi @imft-debug I have asked the team to look into this and they said:

> Unless they send an email to our support desk with the email address they used I fear there is not much we can find. I'm definitely not seeing any errors on that day, or before.

So please drop them an email and they will be able to get into what's happened to prevent you getting the emails.

**Comment by imft-debug** [comment]
I registered for a online demo and it said the demo is being created and will get an email after its setup. 

I verified the email and no response since. 
Can you check the user happy flow at your end by registering for a trial 






---- On Tue, 15 Oct 2024 21:10:18 +0500 Ruth Cheesley ***@***.***> wrote ---





Hi https://github.com/imft-debug I have asked the team to look into this and they said:

Unless they send an email to our support desk with the email address they used I fear there is not much we can find. I'm definitely not seeing any errors on that day, or before.


So please drop them an email and they will be able to get into what's happened to prevent you getting the emails.

**Comment by nick-vanpraet** [comment]
Hey @imft-debug , could you send an email to [mautictrials@dropsolid.com](mailto:mautictrials@dropsolid.com) from the address you used so we can look into it. Be sure to reference this issue in your mail.

**Comment by imft-debug** [comment]
okay . I have sent the email 





---- On Tue, 29 Oct 2024 15:56:47 +0500 Nick Vanpraet ***@***.***> wrote ---





Hey https://github.com/imft-debug , could you send an email to ***@***.*** from the address you used so we can look into it. Be sure to reference this issue in your mail.
