### ISSUE TITLE
Email builder - Button containing p tag

### ISSUE THREAD

**Issue by david-gap** [mautic/mautic#14190]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.29

### What browsers are you seeing the problem on?

Not relevant

### What happened?

If I insert a button and then edit the text in CKEditor, a p tag is placed inside the button. It always happens when i am changing the text through the editor.

For example:
`<a href="#" target="_blank" id="i2zvl"><p>Button 2</p></a>`
![after](https://github.com/user-attachments/assets/fd4aace9-5d7e-4724-8caa-1a7b861571c4)

Should be:
`<a href="#" target="_blank" id="i2zvl">Button 2</a>`
![before](https://github.com/user-attachments/assets/e2d0807a-51e8-4870-a1ba-9a635f9b7317)

### How can we reproduce this issue?

Step 1: Create a new email and select a theme.
Step 2: Add a button or select an existing one, then change the text using the text editor.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there,

Thanks for raising the bug, but it's a good idea to search the issues beforehand. I searched for Button and found this earlier issue report: https://github.com/mautic/mautic/issues/14140 so I will close this as a duplicate. Let's centralise the discussion there (please also consider testing the new email themes!)
