### ISSUE TITLE
Unable to clone the emails in Mautic 5

### ISSUE THREAD

**Issue by sujeetthete-asmb** [mautic/mautic#14217]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.0

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

I am trying cloning the email in Mautic 5, but I am not able to do that, getting 500 error. But it's happening with specific email, other emails are cloning successfully, so able to identify the exact cause.  

![image](https://github.com/user-attachments/assets/5d944152-de13-44b2-b24d-e913e5c35bb6)
![daco_issue](https://github.com/user-attachments/assets/a3023431-6cd5-4e01-ba02-15f591655f3a)

### How can we reproduce this issue?

Step 1: 

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi @sujeetthete-asmb thanks for reporting the bug. I'm unable to reproduce this and the error you're showing doesn't seem to be related. Can you please check your Mautic logs (you'll usually find them in var/logs within your Mautic directory, or you can see them in the System Info in the right hand menu.

This will help to track down exactly what the issue might be with the email you're trying to clone.

**Comment by RCheesley** [comment]
@sujeetthete-asmb can you share the log files as requested please? Thanks!

**Comment by RCheesley** [comment]
Closing due to lack of feedback, feel free to request a re-open.
