### ISSUE TITLE
Mautic 5.1.1 | New Install | Field Max. Character Length set to 64 characters, despite DB reflecting 191 characters

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#14220]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.2

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Fresh install of Mautic 5.1.1, though this exists in some other instances, too, but only appears to occur on fresh installs. 

The field max character lengths are all limited to 64 characters despite the database indicating varchar(191). 

### How can we reproduce this issue?

1. Install Mautic 5.1.1 release
2. Check custom field max character length, it wil show 64. 
3. Check the leads table in the DB, it will show varchar(191), which should equate to 191 characters. 

This is an issue because importing contacts is impossible as character limits are hit as a guarantee.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Pretty sure this is probably relating to https://github.com/mautic/mautic/issues/13831 - let's continue the discussions there.
