### ISSUE TITLE
Bug - command "mautic:lists:update" not updating bounced email list

### ISSUE THREAD

**Issue by ybombale** [mautic/mautic#1422]
Hello,

I have followed the instructions [here](https://www.mautic.org/docs/emails/bounce_management.html) on how to create a list of leads with bounced emails... (I am using Sendgrid)

After I run the command **app/console mautic:fetch:email**, the email sent by Sendgrid is being fetched. However when I run **app/console mautic:lists:update**, no list is being updated.

In shortly... the smart list to catch all the bounced leads is not populating.

Any idea on why this could be happening?

Thanks in advance

**Comment by escopecz** [comment]
@ybombale is this still an issue in Mautic 2.1.0?

**Comment by alanhartless** [comment]
Due to lack of feedback, we're closing this issue. Please upgrade to 2.1.1 and if the issue persist, definitely let us know! Thanks!
