### ISSUE TITLE
having trouble getting OAuth 2 to work

### ISSUE THREAD

**Issue by girish1605** [mautic/mautic#1423]
We're having trouble getting OAuth 2 to work. We're using Mautic 1.2.4 on Windows.

We've set up the configuration in Mautic to use OAuth 2 and generated the client secret and tokens. Even though the documentation says There is a field on the API configuration field to choose the OAuth version, we dont see this field atall on the API configuration form.

We've set up Apache to use SSL with a self signed certificate.

When we visit https://subdomain.mydomain.com/ , We get the usual self signed SSL security error, and after accepting the error, we are able to use Mautic normally.

While trying to redirect the user for OAuth 2 token, I am able to redirect the user to https://subdomain.mydomain.com/oauth/v2/authorize?<more query params>

This redirects the user to https://subdomain.mydomain.com/oauth/v2/authorize_login

This presents the user with the login screen. After the user enters the username and password, the user is redirected back to the same url (as seen in the browser):
https://subdomain.mydomain.com/oauth/v2/authorize?<more query params>

And the use is presented with a 404 Not Found error. This error is displayed by Mauticbot and not Apache.

**Comment by pranavmehta** [comment]
@escopecz 

Any inputs pls?

**Comment by escopecz** [comment]
I just tested the OAuth2 with the [API Tester](https://github.com/mautic/api-library/tree/master/apitester) and it worked for me. The OAuth version switch was moved directly into the API credentials section.

**Comment by girish1605** [comment]
Thanks for the response @escopecz,

Can you please help me understand what is the issue issue with my request URL above? It seems to be in line with the Mautic documentation. After successful authentication, why is the user not being redirected to the redirect_uri ?

We are trying to use the Mautic REST api, but are not able to proceed because we are unable to obtain the OAuth 2 token. We need to use the REST api because we plan to call them from an external (non PHP based system).

We tried installing the API Tester, but that didnt go well as well.
1. While trying to install it with Compose, we got the error "Could not find package mautic/api-library at any version for your minimum-stability (stable)"
2. So I downloaded the zip and tried that way, but got stuck with the "Fatal error: Class 'Mautic\Auth\ApiAuth' not found". We somehow managed to get past this error by manually configuring the namespaces in symphony.

Finally we were able to see the API tester page load, and while trying to authorize, the user was directed to the login screen for authorizing the user got stuck with a 403 You do not have permission to access this page response.

Any help in this regards is really appreciated. Thanks for the help!
