### ISSUE TITLE
Uses incorrect password formatting in dsn settings

### ISSUE THREAD

**Issue by cajmorgan** [mautic/mautic#14248]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.0

### What happened?

Entering a password with special characters like *blankspace* yields wrong url-encoding

### How can we reproduce this issue?

Step 1:  enter a password in the DSN settings with special characters and inspect its result in local.php

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by dsp76** [comment]
Hi @cajmorgan, thanks for reporting the issue.
Good news, its already in work here: https://github.com/mautic/mautic/issues/13228

It was supposed to be fixed in 5.1.1 - but you seem to still experience it? Could you please join the discussion there?
