### ISSUE TITLE
Link is not visible in CK Editor email- and landingpage-builder

### ISSUE THREAD

**Issue by luke-42** [mautic/mautic#14243]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

When editing an email or a landing page in the new CKEditor, links within the text are not visually highlighted. This prevents users from identifying where the links are, making it impossible to edit or manage these links effectively.

Landingpage:
This text contains two links: 
![image](https://github.com/user-attachments/assets/ab2f2929-dba8-4d08-b949-1f83846011a7)

![image](https://github.com/user-attachments/assets/6789d787-f2a6-4e81-baba-9f58000cfcd3)

Email:
This text contains two links:
![image](https://github.com/user-attachments/assets/fd65ab92-7952-4a64-93dd-44211c1d7def)

![image](https://github.com/user-attachments/assets/c675d91c-777b-4697-8fe7-f4f0e1577e69)

### How can we reproduce this issue?

Steps to Reproduce:

1. Open the new CKEditor in the application to edit an email or landing page.
2. Insert one or more hyperlinks within the text.
3. Attempt to visually locate and highlight the inserted links for further editing.

Expected Result: Links should be highlighted or underlined within the editor, allowing the user to see where links are located and easily select them for editing.
<img width="1452" alt="image" src="https://github.com/user-attachments/assets/e0dc2593-fe43-4d49-a3c0-b9c17b273481">

Actual Result: Links are not visually highlighted or underlined, making it unclear where the links are within the text. As a result, users are unable to edit or manage the links effectively.

Impact: This affects usability by obscuring link positions within the text, leading to confusion and limiting users' ability to edit links directly.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
HI @luke-42 thanks for reporting this. I think this is not a bug, but rather that you've got an accessibility setting turned off.

In the user profile you can turn on underlining links:

![screenshot-mautic_ddev_site-2024_11_11-12_21_00](https://github.com/user-attachments/assets/89a97273-b4f4-49bb-ad51-552c69e4f89a)

With this setting turned on, I am seeing the links underlined in the editor.

![screenshot-mautic_ddev_site-2024_11_11-12_21_37](https://github.com/user-attachments/assets/d624c81f-8e38-4cc9-88c8-8965faa347cc)

Can you confirm this is the case? If not let me know and I'll re-open the issue.

**Comment by luke-42** [comment]
Hi @RCheesley 
Thank you. This will indeed resolve the issue. However, I believe that links should always be visible in the CKEditor for a better user experience. Without visible links, Admins get no feedback, which can be confusing. Imagine a text with 10 links — it would be quite challenging for Admins to locate them.

I think links should be highlighted **by default** in the CKEditor (without additional settings), either with a background color or underlining, to make them noticeable.

What do you think?

**Comment by RCheesley** [comment]
Something for @mautic/ux-ui-tiger-team to consider - I don't know if it's possible to maybe exclude CKEditor from those user settings?

**Comment by luke-42** [comment]
This is a brilliant idea @RCheesley to exclude the CKEditor from those user settings.

**Comment by andersonjeccel** [comment]
@RCheesley @luke-42 The "Call to action" text is a link in a Mautic 5.1.1 that doesn't have any accessibility features, also not showing

![image](https://github.com/user-attachments/assets/d6eb82cc-597c-4efe-9998-38bdf57a4878)

not having those underlines is an actual issue that new features are able to fix, not the cause

I'll check for a way to add these specifically in the CKEditor

**Comment by luke-42** [comment]
>I'll check for a way to add these specifically in the CKEditor

Thank you @andersonjeccel
