### ISSUE TITLE
Add Empty and Not Empty Conditions to Campaigns

### ISSUE THREAD

**Issue by indymike** [mautic/mautic#1424]
Give me a way to test a list or form field to see if it is empty so I can take appropriate action in my campaign.

**Comment by Mazzim** [comment]
+1 on "is empty", "is not empty" in field conditions.

[This](https://github.com/mautic/mautic/issues/1431) recurring feature request includes it.

**Comment by SDiot** [comment]
+1 on 'is empty', "is not empty" in field conditions also.

**Comment by medianicus** [comment]
+1

**Comment by Mazzim** [comment]
+1 Just to bump it up!
This is a long-needed feature: Condition - Contact field "is empty" / "is not empty"

**Comment by escopecz** [comment]
Please test https://github.com/mautic/mautic/pull/3084 if it solves this issue.
