### ISSUE TITLE
Error when saving a Landing page based upon a default template

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#1425]
Saving a landing page based upon a template gives me a 500 error.
I tried this with a custom template but also with the default Nature template.

The mautic log says gives me the following info
`[2016-02-10 13:53:32] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'CREATE TEMPORARY TABLE tmp_0 AS (SELECT b.tracking_id FROM ma_page_hits b LEFT JOIN ma_pages p ON b.page_id = p.id WHERE b.code = 200 GROUP BY b.tracking_id HAVING count(distinct(b.page_id)) = 1);':  SQLSTATE[HY000]: General error: 3 Error writing file '/tmp/MYLv9x9M' (Errcode: 28)" at /var/www/vhosts/example.com/httpdocs/marketing/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): An exception occurred while executing 'CREATE TEMPORARY TABLE tmp_0 AS (SELECT b.tracking_id FROM ma_page_hits b LEFT JOIN ma_pages p ON b.page_id = p.id WHERE b.code = 200 GROUP BY b.tracking_id HAVING count(distinct(b.page_id)) = 1);':\n\nSQLSTATE[HY000]: General error: 3 Error writing file '/tmp/MYLv9x9M' (Errcode: 28) at /var/www/vhosts/example/httpdocs/marketing/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:91, PDOException(code: HY000): SQLSTATE[HY000]: General error: 3 Error writing file '/tmp/MYLv9x9M' (Errcode: 28) at /var/www/vhosts/example/httpdocs/marketing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:165)"} []`

**Comment by escopecz** [comment]
It seems more like a permission issue than a Mautic issue:

> General error: 3 Error writing file  '/tmp/MYLv9x9M'

Please, consult it with your web hosting provider.

**Comment by wderuijter** [comment]
Hey John. I noticed that. Should there be a tmp folder in the mautic folder?

**Comment by wderuijter** [comment]
After saving and getting the 500 error, going to the expected public URL of the landing page does work.

**Comment by escopecz** [comment]
`/tmp` means it is the tmp directory in the root of your server. Please, contact your sys admin. There is not much we can do.

**Comment by wderuijter** [comment]
Thanks. I understand.

**Comment by wderuijter** [comment]
The problem is clear now and it has been resolved. 
In my situation there was 845MB of free space in the /tmp folder. 
The query for creating a landing page resulted in a table larger than 845MB. After freeing up some more space the problem has been resolved.

**Comment by alanhartless** [comment]
It seems a bit off that the landing page query would be that large unless you have a lot of in-line in svgs or something?

**Comment by wderuijter** [comment]
It was nog the page itself that was this big. 
As the provider told me 
`having count(distinct(b.page_id)) = 1 `
resulted in a tmp table larger than 845MB
