### ISSUE TITLE
Issue with connections between squares in campaigns

### ISSUE THREAD

**Issue by eddie477** [mautic/mautic#14266]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.0

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1.0

### What browsers are you seeing the problem on?

Chrome

### What happened?

The issue is in Mautic's campaign editor. Each of the boxes is connected by lines. Imagine we have an event flow 1 -> 2 -> 3 -> 4. The problem arises when we delete an event in the middle of the flow, such as event 2 or 3. The user can only delete event 2 by first deleting events 3 and 4. I believe the UX could be greatly improved if Mautic were clearer about what can and cannot be done.

### How can we reproduce this issue?

Step 1: Create a campaign with a flow of at least 3 events 
Step 2: Save it
Step 3: Load it again and delete event 2. You will see event 3 floating and disconnected. 

![image](https://github.com/user-attachments/assets/4f7ace6a-75e0-4fdc-9d85-048ed521bad2)

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by escopecz** [comment]
What would you expect should happen instead?

**Comment by eddie477** [comment]
I do not know if it would be easy for the library to create connections with other squares.... This would be ideal ... But some problems might arrise such as that the new connecting square is not compatible (maybe they are all compatible). 

The other alternative would be preventing from deleting squares in the middle of the flow. 

Not really sure.

**Comment by escopecz** [comment]
I think that the current implementation is the easiest and it's actually not that hard to understand for the users either. This way you can delete an event in the middle of the flow and replace it with some other. Restricting the deletion would lead to very time consuming edits. I've seen campaigns with hundreds of connected events. Imagine you want to replace the one in the middle. I will close this issue until there will be a better alternative to the current behaviour.
