### ISSUE TITLE
Add limit to the lead detail timeline

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#1428]
Right now the timeline events on lead detail doesn't have any limit. It causes problems to load the lead detail when there is many events.

**Comment by npracht** [comment]
Hi,

Good idea but do not delete it, a "load more logs" link/button would be smart.

N.

**Comment by escopecz** [comment]
I wasn't even thinking to delete them :D

We have to add there some hard-coded SQL limit at least to prevent a memory/time limit with leads who have thousands of events. The pagination thing is tricky in this case because the events are subscribed to the lead detail from each bundle so the lead bundle doesn't know how many and how old events it will get from each subscribed bundle.

**Comment by sambarnes90** [comment]
+1 on this - some of my contacts are taking an age to load now.

'Load More' link would make sense.

Or when loading the contact perhaps it could stop loading events if there are more than say 500 until search / click 'view all' / specify a timeframe?

**Comment by wittwerch** [comment]
Maybe "infinite scrolling" would be an option too..

**Comment by dbhurley** [comment]
Addressed in 2.1, will close after PR is merged.
