### ISSUE TITLE
Memory exhaustion while sending emails in Docker installation

### ISSUE THREAD

**Issue by aiac** [mautic/mautic#14293]
### Mautic Series

5.1.x series

### Mautic installed version

5.1.1

### Way of installing

I'm using a Docker image from https://hub.docker.com/r/mautic/mautic

### PHP version

8.1.29

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Emails fail to send due to memory exhaustion. The issue persists even with simple email templates and contacts without extra fields. It seems that PHP, especially when running via cron or shell session, does not have sufficient memory allocated.

### How can we reproduce this issue?

Step 1: add 10000 contacts, create simple mailing campaign and add contacts to campaign
Step 2: run `php /var/www/html/bin/console mautic:campaigns:trigger 2>&1` inside the container to send the emails
Step 3: wait for a couple of minutes

### Relevant log output

```shell
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 225280 bytes) in /var/www/html/vendor/symfony/mime/Encoder/QpContentEncoder.php on line 36

In QpContentEncoder.php line 36:

  Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 225280 bytes)

Other:
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 139264 bytes) in /var/www/html/docroot/app/bundles/EmailBundle/Event/EmailSendEvent.php on line 341

In EmailSendEvent.php line 341:

  Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 139264 bytes)
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
