### ISSUE TITLE
Feature request - Add operator on campaign lead field value condition

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1431]
Hi,

It would be great to add some operators to the campaign condition "Lead field value".
## Operators to add in campaign condition "Lead field value"
- Contain
- Does not contain
- Is empty
- Is not empty

![capture d ecran 2016-02-11 a 09 24 01](https://cloud.githubusercontent.com/assets/14075239/12971973/45ed9312-d0a1-11e5-8fd2-8bbdf00f0a58.png)

I don't know if you have any idea of any other operator.

**Comment by npracht** [comment]
## Add "Tag" as another Lead Field
I was thinking also to add **a missing Lead Field** for the campaign condition "Lead field value".
We should add the "**Tag**" to select!

![capture d ecran 2016-02-12 a 08 57 55](https://cloud.githubusercontent.com/assets/14075239/13001511/ece05536-d166-11e5-9e92-271abc525f96.png)

**Comment by Mazzim** [comment]
+1 on both. I personally ran into "empty" or "not empty" condition missing.
Tag-based condition would be great to have also, at present you have to create a custom lead field to be used as a flag that you can check inside a campaign, or a tag-based smart list but only as a source of a campaign.

**Comment by npracht** [comment]
Partially solved by https://github.com/mautic/mautic/pull/2095

**Comment by SDiot** [comment]
Hi, 
It would definitely be great to have access to all contact-related values like its stage or its points and +1 on the enpty/not empy operator :)
Thanks, you're doing an amazing job guys !
S.

**Comment by escopecz** [comment]
I'll close this issue in favor of https://github.com/mautic/mautic/issues/1424. Contains and does not contain operators already exists as like and not like
