### ISSUE TITLE
Broken ui after a migration from 5.1.1 to 5.2

### ISSUE THREAD

**Issue by mohamed-badaoui** [mautic/mautic#14324]
### Mautic Series

5.1.x series

### Mautic installed version

5.2.0

### Way of installing

I'm using a Docker image from https://hub.docker.com/r/mautic/mautic

### PHP version

8.2.26

### What browsers are you seeing the problem on?

Firefox, Chrome

### What happened?

I just test migration from 5.1.1 to 5.2, and ui is broken for all the pages with a list like contact, email, campaign ...

![image](https://github.com/user-attachments/assets/993cb897-f21c-4e15-9c15-ace95f7055ba)

### How can we reproduce this issue?

Install 5.1.2 mautic version and do upgrade:

```
composer update --with-dependencies
php bin/console cache:clear
php bin/console mautic:assets:cleanup
php bin/console mautic:assets:generate
php bin/console cache:clear
php bin/console mautic:update:apply --finish
php bin/console doctrine:migration:migrate --no-interaction
php bin/console doctrine:schema:update --no-interaction --force
php bin/console cache:clear
```

### Relevant log output

```shell
php -v
PHP 8.2.26 (cli) (built: Nov 21 2024 17:59:18) (NTS)
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Please clear your **browser** cache, that is probably the cause of this behaviour. Thanks!

**Comment by RCheesley** [comment]
In the future, please post your issue over at https://forum.mautic.org/c/support as the forums are your first port of call for getting help if you encounter problems :)

**Comment by mohamed-badaoui** [comment]
@RCheesley  I use a private session to avoid cache consideration
