### ISSUE TITLE
Bulk deleting mails actually deleted contacts with the corresponding contact IDs in 5.2

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#14323]
### Mautic Series

5.1.x series

### Mautic installed version

5.2.0

### Way of installing

I downloaded a release from https://www.mautic.org/mautic-releases

### PHP version

8.1

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Tried to delete some test mails. However, first I thought the confirmation message is wrong - "Delete the selected contacts?".  But indeed it deleted the contacts with the IDs from the selected Mails in the bulk delete.

![image](https://github.com/user-attachments/assets/983f170e-b2b2-4b89-91b8-4d1e87ef4fd5)

It doesn't happen when I delete the mail one by one without bulk menu.

### How can we reproduce this issue?

Step 1: Bulk select E-Mails to delete.
Step 2: See that contacts get deleted instead of the emails - if there are contacts with the same IDs.

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by escopecz** [comment]
@andersonjeccel could it be a copy-paste typo during the UI changes?

**Comment by LeonOltmanns** [comment]
Just tested and confirmed the bug. This should be worked on asap as unintentional deletion of contacts is a business critical error.

**Comment by andersonjeccel** [comment]
@escopecz Probably, I’ll check

**Comment by andersonjeccel** [comment]
@escopecz @RCheesley @oltmanns-leuchtfeuer Hmm, I didn't touch anything there that got merged

My PR #14306 refactors a lot of things related to these batch actions on the frontend, but it's still waiting for test fixes and isn't part of 5.x or the release...

it might be worth it to check the PR that added "Batch change category" for emails, from one of the new contributors

**Comment by mchojrin** [comment]
Hey, I just checked my changes and I can't see anything related to contacts. This are the changed files if anyone wants to have a look https://github.com/mautic/mautic/pull/14067/files

**Comment by andersonjeccel** [comment]
@mchojrin Thank you for checking, I thought it could be related as we're seeing this issue on the emails page

**Comment by mchojrin** [comment]
@andersonjeccel no problem! I hope it gets fixed soon. Glad to help if possible ;)

**Comment by andersonjeccel** [comment]
@mchojrin found the issue, the routeBase was being applied twice :)

**Comment by mchojrin** [comment]
@andersonjeccel was it in the code I submitted?

**Comment by andersonjeccel** [comment]
@mchojrin yep, see https://github.com/mautic/mautic/pull/14067#discussion_r1871777031 and https://github.com/mautic/mautic/pull/14335

do you understand why, looking at both references? ping me if you'd like an explanation

**Comment by mchojrin** [comment]
I'll take a look... sorry about the inconvenience :(

**Comment by andersonjeccel** [comment]
@mchojrin it's okay, not an inconvenience. you did a great job at making stuff easier for people that devs tend to ignore

and feel happy about it. many guys would have no knowledge to do something similar (including me). you made the entire code, I just removed 2 lines :)

btw, do you have any plans for next pull requests?

**Comment by mchojrin** [comment]
> @mchojrin it's okay, not an inconvenience. you did a great job at making stuff easier for people that devs tend to ignore
>
 
:)

> and feel happy about it. many guys would have no knowledge to do something similar (including me). you made the entire code, I just removed 2 lines :)

haha... linecount is not my favorite metric :p
> 
> btw, do you have any plans for next pull requests?

Not really. There are a couple of things I'd like to see improved in Mautic but I don't know wether I'll be able to work on them myself... New year is looking kind of busy

**Comment by andersonjeccel** [comment]
@mchojrin yeah, no problem

would you like to be added to the UX/UI team on GitHub?

at least you'd receive requests to review PRs (code review or testing), that's a great way to keep involved :)

**Comment by mchojrin** [comment]
@andersonjeccel I wouldn't really consider myself a UX/UI person but if you think I could make a contribution there sure, I can take a crack at it :)
