### ISSUE TITLE
Setting the email to 'queue' in 1.2.4 doesn't work

### ISSUE THREAD

**Issue by tanzaho** [mautic/mautic#1434]
I was playing with the cron jobs to be sure that everything was working on my installation, and faced a strange behavior.

- On the web panel, my emails should be sent via the queue
- However, in the `app/config/local.php`I have 'queue_mode' => 'immediate_process',
- when I run the cron job, I receive the following message : `Mautic is not set to queue email.`

I guess there is a problem with the web app that does not save the correct setting for the mail process.
I started directly with 1.2.4 and can't say if it was already the case on previous releases.

**Comment by tanzaho** [comment]
As a precision, I'm using the docker image.

**Comment by tanzaho** [comment]
Nevermind, I was using the wrong path to the app.

**Comment by escopecz** [comment]
So the setting the email to 'queue' does work in 1.2.4? I'll close this issue then.
