### ISSUE TITLE
Error 500 with Mautic Dashboard after upgrading from 4.4.x to 5.2.0

### ISSUE THREAD

**Issue by trianity** [mautic/mautic#14346]
### Mautic Series

5.2.x series

### Mautic installed version

5.2.0

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.2.26

### What browsers are you seeing the problem on?

Chrome

### What happened?

I upgraded my Mautic installation from 4.4.13 by installing version 5.2.0 with Composer, ran the necessary upgrade commands, and then attempted to log in. I received Error 500.

The error appeared in /mautic-path/docroot/app/bundles/EmailBundle/Stats/Helper/FilterTrait.php

```

    /**
     * @param int|null $segmentId
     * @param string   $fromAlias
     */
    protected function addSegmentFilter(QueryBuilder $q, $segmentId = null, $fromAlias = 't')
    {
        if (null !== $segmentId && intval($segmentId)) {
/*
            $sb = $this->connection->createQueryBuilder();

            $sb->select('null')
                ->from(MAUTIC_TABLE_PREFIX.'lead_lists_leads', 'lll')
                ->where(
                    $sb->expr()->and(
                        $sb->expr()->eq('lll.leadlist_id', ':segmentId'),
                        $sb->expr()->eq('lll.lead_id', $fromAlias.'.lead_id'),
                        $sb->expr()->eq('lll.manually_removed', 0)
                    )
                );

            $q->andWhere(
                sprintf('EXISTS (%s)', $sb->getSql())
            )->setParameter('segmentId', $segmentId);
*/
        }
    }

```

Commenting out the internal part of the addSegmentFilter() function, the Mautic can run without error 500, and I was able to login.

### How can we reproduce this issue?

Step 1: Run upgrade using composer: composer create-project mautic/recommended-project:^5 mautic-path --no-interaction
Step 2: Do all necessary action to finish upgrade
Step 3: Try to login

### Relevant log output

```shell
[2024-12-06T17:55:22.677007+00:00] mautic.CRITICAL: Uncaught PHP Exception Error: "Call to a member function createQueryBuilder() on null" at /mautic-path/docroot/app/bundles/EmailBundle/Stats/Helper/FilterTrait.php line 71 {"exception":"[object] (Error(code: 0): Call to a member function createQueryBuilder() on null at /mautic-path/docroot/app/bundles/EmailBundle/Stats/Helper/FilterTrait.php:71)"} {"hostname":"vps.example.com","pid":127744}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for reporting the bug @trianity, I've flagged this up as a regression.

**Comment by escopecz** [comment]
@trianity the login form redirects you to the dashboard where the bug is. It's in one of the widgets. You can change the URL to point to /contacts for example and it will load and lets you use your Mautic.

I have fixed the issue you reported here: https://github.com/mautic/mautic/pull/14356. Please test it so it would get into the 5.2.1 release.

**Comment by trianity** [comment]
@escopecz Thanks for the fixing. I tested it in my Mautic instance and the fix works.
