### ISSUE TITLE
When an asset is downloaded without an associated lead, an error is thrown in the logs

### ISSUE THREAD

**Issue by trianity** [mautic/mautic#14351]
### Mautic Series

5.2.x series

### Mautic installed version

5.2.0

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.2.26

### What browsers are you seeing the problem on?

Not relevant

### What happened?

My client, whose Mautic I run, often sends emails with downloadable content. And the error below keeps popping up again and again. 2-3, sometimes more, such logs appear in the PHP error log per day.

The error can be observed starting from version 2.14 in my case, and at v.4.4.x is also present, and now when upgrading to 5.2.0 the issue also appeared.
This bug report is a reopening of https://github.com/mautic/mautic/issues/6957 (closed issue).
This bug report is a reopening of https://github.com/mautic/mautic/issues/11340 (closed issue).

The most likely scenario is that the asset is sent to a lead (via email forwarding) who has not yet been identified by Mautic. And that's why it makes an exception.

### How can we reproduce this issue?

Step 1: Add asset to Mautic.
Step 2: Create link to asset on website or in email.
Step 3: Download asset from incognito browser. [Possibly—exact reproduction sequence unknown.]

### Relevant log output

```shell
[06-Dec-2024 20:48:50 UTC] Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'Mautic\AssetBundle\Entity\Download#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #0. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}). in /mautic-path/vendor/doctrine/orm/src/ORMInvalidArgumentException.php:103
Stack trace:
#0 /mautic-path/vendor/doctrine/orm/src/UnitOfWork.php(3854): Doctrine\ORM\ORMInvalidArgumentException::newEntitiesFoundThroughRelationships()
#1 /mautic-path/vendor/doctrine/orm/src/UnitOfWork.php(415): Doctrine\ORM\UnitOfWork->assertThatThereAreNoUnintentionallyNonPersistedAssociations()
#2 /mautic-path/vendor/doctrine/orm/src/EntityManager.php(414): Doctrine\ORM\UnitOfWork->commit()
#3 /mautic-path/docroot/app/bundles/AssetBundle/Model/AssetModel.php(273): Doctrine\ORM\EntityManager->flush()
#4 /mautic-path/docroot/app/bundles/AssetBundle/Controller/PublicController.php(49): Mautic\AssetBundle\Model\AssetModel->trackDownload()
#5 /mautic-path/vendor/symfony/http-kernel/HttpKernel.php(163): Mautic\AssetBundle\Controller\PublicController->downloadAction()
#6 /mautic-path/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#7 /mautic-path/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle()
#8 /mautic-path/docroot/app/AppKernel.php(109): Symfony\Component\HttpKernel\Kernel->handle()
#9 /mautic-path/docroot/app/middlewares/CORSMiddleware.php(76): AppKernel->handle()
#10 /mautic-path/docroot/app/middlewares/HSTSMiddleware.php(39): Mautic\Middleware\CORSMiddleware->handle()
#11 /mautic-path/docroot/app/middlewares/CatchExceptionMiddleware.php(28): Mautic\Middleware\HSTSMiddleware->handle()
#12 /mautic-path/docroot/app/middlewares/VersionCheckMiddleware.php(58): Mautic\Middleware\CatchExceptionMiddleware->handle()
#13 /mautic-path/docroot/app/middlewares/TrustMiddleware.php(42): Mautic\Middleware\VersionCheckMiddleware->handle()
#14 /mautic-path/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\TrustMiddleware->handle()
#15 /mautic-path/docroot/index.php(19): Stack\StackedHttpKernel->handle()
#16 {main}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Thanks for flagging this up @trianity - seems like it's a long running issue but we've not managed to keep it active to find a resolution. @tomekkowalczyk it seems in the older issue you were experiencing this too, did your team look into fixing it at all?

**Comment by RCheesley** [comment]
This was resolved in https://github.com/mautic/mautic/pull/14360 so closing this issue.
