### ISSUE TITLE
index.php/installer 404

### ISSUE THREAD

**Issue by lijom80** [mautic/mautic#14352]
### Mautic Series

5.2.x series

### Mautic installed version

5.2.0

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.1.0

### What browsers are you seeing the problem on?

Not relevant

### What happened?

> bin/console mautic:assets:generate
Production assets have been regenerated.

![image](https://github.com/user-attachments/assets/e9de701f-c8a4-489b-98d1-231293755549)

### How can we reproduce this issue?

wget https://github.com/mautic/mautic/releases/download/5.2.0/5.2.0.zip
sudo unzip 5.2.0.zip -d /var/www/html/
sudo chown -R administrator:www-data /var/www/html
composer update
composer install --no-dev --optimize-autoloader

### Relevant log output

```shell
2024/12/09 01:59:19 [error] 61820#61820: *46 FastCGI sent in stderr: "PHP message: PHP Warning - file_put_contents(/var/www/html/var/cache/prod/middlewares.cache.php): Failed to open stream: Permission denied - in file /var/www/html/app/bundles/CoreBundle/Cache/MiddlewareCacheWarmer.php - at line 70PHP message: PHP Warning:  file_put_contents(/var/www/html/var/cache/prod/middlewares.cache.php): Failed to open stream: Permission denied in /var/www/html/app/bundles/CoreBundle/Cache/MiddlewareCacheWarmer.php on line 70PHP message: PHP Warning - include(/var/www/html/var/cache/prod/middlewares.cache.php): Failed to open stream: No such file or directory - in file /var/www/html/app/middlewares/MiddlewareBuilder.php - at line 66PHP message: PHP Warning:  include(/var/www/html/var/cache/prod/middlewares.cache.php): Failed to open stream: No such file or directory in /var/www/html/app/middlewares/MiddlewareBuilder.php on line 66PHP message: PHP Warning - include(): Failed opening '/var/www/html/var/cache/prod/middlewares.cache.php' for inclusion (include_path='.:/usr/share/php') - in file /var/www/html/app/middlewares/MiddlewareBuilder.php - at line 66PHP message: PHP Warning:  include(): Failed opening '/var/www/html/var/cache/prod/middlewares.cache.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/app/middlewares/MiddlewareBuilder.php on line 66PHP message: PHP Warning - foreach() argument must be of type array|object, bool given - in file /var/www/html/app/middlewares/MiddlewareBuilder.php - at line 68PHP message: PHP Warning:  foreach() argument must be of type array|object, bool given in /var/www/html/app/middlewares/MiddlewareBuilder.php on line 68" while reading response header from upstream, client: 192.168.100.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "192.168.100.198"

administrator@mailserver:~$ ls -l /var/www/html/app/bundles/CoreBundle/Cache/MiddlewareCacheWarmer.php
-rw-r--r-- 1 administrator www-data 2808 Dec  2 19:52 /var/www/html/app/bundles/CoreBundle/Cache/MiddlewareCacheWarmer.php
administrator@mailserver:~$ ls -l /var/www/html/var/cache/prod/middlewares.cache.php
-rw-r--r-- 1 www-data www-data 267 Dec  9 02:06 /var/www/html/var/cache/prod/middlewares.cache.php
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
