### ISSUE TITLE
Map in the lead detail

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#1435]
I think it could be great and not so hard to do to place a map with the point where the lead is from into the lead detail page. This is an example how Intercom does it:
![mautic-lead-map](https://cloud.githubusercontent.com/assets/1235442/13010092/5b449fd0-d1a0-11e5-9e27-bdd6b7bc141a.png)

**Comment by dbhurley** [comment]
:+1: I am in agreement this is a nice feature. Intercom does have a nice layout to their lead profile header.

**Comment by dbhurley** [comment]
I am in agreement this is a nice feature. Intercom does have a nice layout to their lead profile header.

[--- Commented from Asana.com
#commenter David Hurley
---[aa]
