### ISSUE TITLE
Links in campaign email not all being made trackable

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#1438]
Mautic 1.2.4
PHP 5.5.30

Created 4 emails to be sent in a campaign.

Emails contain 2 links(one to main website, one to blog article), the View in Browser and Unsubscribe button.

Both links, were not parsed for Mautic tracking, it has the raw link to the website and the other to the blog.

If I view the email in my browser, after clicking the "view email in browser" button, the link to the website and blog article have been parsed for Mautic tracking.

I'm not strong enough on PHP to know if this is the same issue, but it looks quite similar to the symptoms I found. [https://www.mautic.org/community/index.php/1219-sometimes-mautic-seems-to-automatically-add-trackable-urls-to-t/0](https://www.mautic.org/community/index.php/1219-sometimes-mautic-seems-to-automatically-add-trackable-urls-to-t/0) It was reported by Mautic forum user Hexamon.

**Comment by escopecz** [comment]
I think that that issue was fixed already. Could you provide the HTML of your problematic email with us?

**Comment by ps92** [comment]
I got the same issue. But my issue was closed. So, I would post here. 
You can go through this link https://www.dropbox.com/s/1kh9o415nh1hpty/a.png?dl=0 if you need to understand the problem.

**Comment by ps92** [comment]
`<html>
<head>
	<title></title>
</head>
<body>
<p><a href="http://www.google.com">Internet </a><br />
<a href="http://www/faebook.com">facebook </a></p>
</body>
</html>
`

**Comment by ps92** [comment]
The link `href="http://www.google.com">Internet` should be replaced with `href="http://<myweb>/r/{camapign_and_email_hash}`.
Though, this is not happening. Please suggest.

**Comment by escopecz** [comment]
@ps92 I will re-open your issue https://github.com/mautic/mautic/issues/1439 if you think it was not solved. Also, if you post code samples, please, [format them](https://guides.github.com/features/mastering-markdown/) that way.

**Comment by rafas** [comment]
Apparently Mautic can replace the links only in the first e-mail that is in the campaign send queue.

The e-mail shots sent out campaign (send direct to the list) apparently have no problem.

I did a test, and direct submissions to the list replaced the links.
But shipments scheduled for the campaign, where a send queue with more than one e-mail is generated, the replacement does not.

Follow the link to more accurately test performed.
If anyone knows explain to Hexamon how to contribute to the correction, please help him to help us.

https://www.mautic.org/community/index.php/1219-sometimes-mautic-seems-to-automatically-add-trackable-urls-to-t/p2#p8149

Thank you.

**Comment by zstephen** [comment]
I have a campaign with 4 emails spaced 4 days apart. I launched this campaign before the upgrade to v1.3.0 and the links were tracked.

The last of the emails from this campaign just sent, and the links are not tracked.

**Comment by escopecz** [comment]
Take a look at https://github.com/mautic/mautic/issues/1524 which contains also a possible fix at https://github.com/mautic/mautic/pull/1531. Please comment below https://github.com/mautic/mautic/pull/1531 if the fix works for you.

**Comment by ps92** [comment]
@escopecz Yes, this is a issue fix for #1439 and #1438.

**Comment by nithinga** [comment]
@escopecz bug fix available in https://github.com/mautic/mautic/pull/1531

**Comment by daniloalba** [comment]
i am having the same problem, i am not able to track links in the emails sent in campaigns.
i have checked a few forum answers but dont seem to have found any solution.
any body can help?

**Comment by aovejas** [comment]
> i am having the same problem, i am not able to track links in the emails sent in campaigns.
> i have checked a few forum answers but dont seem to have found any solution.
> any body can help?

Me too!! v2.15.0 php 5.6.40
