### ISSUE TITLE
Updating from 5.1.1 to 5.2.1

### ISSUE THREAD

**Issue by neeleshsoftinator** [mautic/mautic#14394]
### Mautic Series

5.2.x series

### Mautic installed version

5.1.1

### Way of installing

I installed with composer using https://github.com/mautic/recommended-project

### PHP version

8.2.20

### What browsers are you seeing the problem on?

Chrome, Not relevant

### What happened?

When I attempt to update Mautic from version 5.1.1 to the latest version (5.2.1), I encounter an error during the update process.

### How can we reproduce this issue?

Step 1: Updating Mautic (Composer based installs) https://docs.mautic.org/en/5.x/getting_started/how_to_update_mautic.html#updating-mautic-composer-based-installs
Step 2:    sudo nano composer.json
   sudo composer update --with-dependencies

### Relevant log output

```shell
In CompanyModel.php line 66:

  Too few arguments to function Mautic\LeadBundle\Model\CompanyModel::__construct(), 11
  passed in /var/www/html/var/cache/prod/ContainerTBwLs1o/AppKernelProdContainer.php on
  line 4336 and exactly 12 expected


In CompanyModel.php line 66:

  Too few arguments to function Mautic\LeadBundle\Model\CompanyModel::__construct(), 11
  passed in /var/www/html/var/cache/prod/ContainerTBwLs1o/AppKernelProdContainer.php on
  line 4336 and exactly 12 expected


Production assets have been regenerated.
Found 9 security vulnerability advisories affecting 1 package.
Run "composer audit" for a full list of advisories.
Removal failed, sensio/framework-extra-bundle is still present, it may be required by another package. See `composer why sensio/framework-extra-bundle`.
In EventScheduler.php line 26:

  Mautic\CampaignBundle\Executioner\Scheduler\EventScheduler::__construct(): Argument #5
   ($optimizedScheduler) must be of type Mautic\CampaignBundle\Executioner\Scheduler\Mod
  e\Optimized, Mautic\CampaignBundle\EventCollector\EventCollector given, called in /var
  /www/html/var/cache/prod/ContainerTBwLs1o/getMautic_Campaign_SchedulerService.php on l
  ine 36


In EventScheduler.php line 26:

  Mautic\CampaignBundle\Executioner\Scheduler\EventScheduler::__construct(): Argument #5
   ($optimizedScheduler) must be of type Mautic\CampaignBundle\Executioner\Scheduler\Mod
  e\Optimized, Mautic\CampaignBundle\EventCollector\EventCollector given, called in /var
  /www/html/var/cache/prod/ContainerTBwLs1o/getMautic_Campaign_SchedulerService.php on l
  ine 36
```
please help me with i am stuck

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
