### ISSUE TITLE
Common leads in 2 or more lists. 

### ISSUE THREAD

**Issue by ps92** [mautic/mautic#1440]
This is a feature request. 

Currently, mautic has no way of finding if two people are in the same lead lists. 
So, I create 2 smart lists, with some matching criteria. So, say I have a 10k customer list. I am sending two campaigns. But I want that the leads of each campaign should be exclusive. 
I do not have any direct feature through which I can figure out if users belong to multiple groups.

**Comment by escopecz** [comment]
Implemented in https://github.com/mautic/mautic/pull/2599
