### ISSUE TITLE
calendar not updating

### ISSUE THREAD

**Issue by iambluestar** [mautic/mautic#1444]
I have been using mautic religiously for just over two weeks now. I have noticed that as of yesterday the calendar is not showing daily updates anymore  at all

**Comment by escopecz** [comment]
So the calendar was showing some events and suddenly it stopped? Do you see some errors in the server or Mautic logs? Can you check that if you create a lead note with a date that the note is not visible on that date in the calendar?

**Comment by iambluestar** [comment]
This is a very strange issue.
For the month of February it updated the calendar for most days, I was updating mon - friday.
It didn’t update at all on the 10th feb, it did a few updates to the calendar for the 11th, 12th, 13th, 14th, 16th  but not for every lead note. So the notes are under the lead but just not showing on the calendar.   

From the 17th until the end of feb (29th) there were zero updates on the calendar but lead notes were updated daily. 

So far for the month of March, it looks as though all notes are updating. 

I have tried two test notes amending the date of the note. One was amended to a day where the calendar was updating and the other to a day where the calendar was not updating. The result was no data being shown on the calendar for the dates I changed them to. 

I have checked the mautic logs by doing a search for the word "cal" however I don’t see anything which shows me the error with the calendar as such.

I do not see any errors on my server log.

**Comment by escopecz** [comment]
Could you sum up the steps to replicate the issue? Is it like this?:
1. Create a lead not for February 10.
2. Check the calendar. The note isn't there.
3. If you choose any other date the note will show up in the calendar.

**Comment by iambluestar** [comment]
It’s a little difficult to replicate the original issue, as for this month so far the calendar is updating. But it isn’t updating for a number of dates last month, I hope the below helps:

Issue on the 10th Feb
1)	On the 10th feb I made notes for about 10 leads.
2)	The lead note updated
3)	The calendar did not.
Issue after the 10th (from 11-16th) feb, 11th for example
1)	Made a lead note on the 11th feb at 12:43pm
2)	Lead note updated
3)	Calendar updated
4)	Lead notes up until 4:32 pm no longer updated on the calendar
5)	Lead notes from 4:49 until 6:45 updated on the calendar
Issue from 17th feb until end of feb
1)	Made lead notes
2)	Lead note updated
3)	Calendar did not
For the month of March
1)	Made lead note
2)	Lead note updated
3)	Calendar so far has been updating on every note for this month
Testing note 1 for a date which was not updating 
1)	Created a lead note for a date which was not previously updating eg 10th feb
2)	Lead note updated
3)	Note not showing on calendar

Testing note 2 for a date that was updating
1)	Created a lead note for a date which was updating
2)	Lead note updated
3)	Calendar did not update

**Comment by iambluestar** [comment]
FYI the issue is back for this month, it was fine for the first two weeks

**Comment by alanhartless** [comment]
Please try in the latest version of Mautic. If the issue persists, reopen/submit a new issue.

Thanks!

**Comment by adityanikhil007** [comment]
Hello,
I am using Mautic 2.2.1

There is an issue with calendar.

I have Notes about more than 164 for time interval 2016-10-30 to 2016-12-15

and when i open the calendar it shows me only upto 164 notes in November and discard the other notes.

I have also tried to visit this link to investigate:
http://xxxx.xxxxxxx.com/s/ajax?action=calendar:generateData&start=2016-10-30&end=2016-12-15&_=1480239093064&mauticUserLastActive=1&mauticLastNotificationId=

![capture](https://cloud.githubusercontent.com/assets/24205858/20648108/c7afeb5a-b4c3-11e6-8c04-efbd366dc8f9.PNG)

**Comment by Getron** [comment]
Today i see, my calendar is stoping showing anything. This is about 3 days, there is nothing in the last 3 days. I send emails every day to new customers, direct and over campaigns, but, in calendar is nothing showed. I don't known, if this has to do with error i have there:

mautic.NOTICE: PHP Notice: Undefined index: emails - in file .../app/bundles/EmailBundle/Helper/PointEventHelper.php - at line 31 [] []

**Comment by bizxl** [comment]
I am having the same issue. New notes are not visible on my calendar. I there a fix?

**Comment by DianaCruz16** [comment]
I have the same issue. Did you find any solution?

**Comment by iambluestar** [comment]
I haven't had this issue for a while, I solved it originally by installing mautic again. Sorry I couldn't be more helpful.
