### ISSUE TITLE
Lookup field impossible to update via API

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1448]
# Definition of the need
I wanna be able to update a **lookup** field via API.

## Issue
When I click on the button **publicly updatable** and i save, i have a message error asking to add values.
* The standard field `company` created by default in the app is in **lookup** format.
* I cannot save without adding a value to the option --> i need to save to be able to activate **publicly updatable**

## Suggestions
1. Activate **publicly updatable** by default for all the standard **lookup** fields ---> I think it's not a good idea.
2. Give the ability to save **without values** for the **lookup** format fields.

![capture d ecran 2016-02-18 a 11 13 49](https://cloud.githubusercontent.com/assets/14075239/13148538/170a447e-d65e-11e5-8b86-798fcf099bf0.png)
![capture d ecran 2016-02-18 a 11 13 58](https://cloud.githubusercontent.com/assets/14075239/13148539/170ad54c-d65e-11e5-9ed1-1936dc4607cf.png)

**Comment by escopecz** [comment]
I also noticed this. Thanks for reporting it. I should have done that a while ago.
