### ISSUE TITLE
Inserting a Google Analytics tracking string with dynamically assigned lead field data

### ISSUE THREAD

**Issue by 750430** [mautic/mautic#1451]
Open up code view in the email editor, insert the Google Analytics tracking pixel string, using {fieldset=xyz} and the {} are subsequently url encoded, resulting in non-functioning GA tracking.

As a 'work around', using the wysiwyg editor, inserting an image at the bottom of the email with the url being the GA tracking pixel url, 1x1 in size, once done, save and close. GA tracking now functions. However, if the email is opened in code view, the braces apear url encoded. Thus requiring the code to be deleted, save & close, back in to the email editor, insert new image with amended/updated url.

Cheers.

**Comment by escopecz** [comment]
@750430 could you please share the code you tried and what was delivered in the email? Is this still an issue with Mautic 2.1.0 where the editor was changed?

**Comment by alanhartless** [comment]
Due to lack of feedback, we're closing this issue. Please upgrade to 2.1.1 and if the issue persist, definitely let us know! Thanks!
