### ISSUE TITLE
Campaign decision not working for open email

### ISSUE THREAD

**Issue by nimesh-mittal** [mautic/mautic#1454]
Hi Team,

I am running below campaign where decision node(Open Email) always evaluates to NO path even after mail is read within 30 secs. I verified that mautic is able to detect email read in lead activities but still always takes NO path. 

![image](https://cloud.githubusercontent.com/assets/10060860/13197686/0c5f9a92-d81b-11e5-9898-299687255278.png)

![image](https://cloud.githubusercontent.com/assets/10060860/13197718/97f54eda-d81b-11e5-9cb7-7633d3d17d2c.png)

I have below crontab set to run every one min

php /var/www/html/1.2.0/app/console mautic:leadlists:update --env=prod 
php /var/www/html/1.2.0/app/console mautic:campaigns:update --env=prod -f
php /var/www/html/1.2.0/app/console mautic:campaigns:trigger --env=prod -f
php /var/www/html/1.2.0/app/console mautic:email:process --env=prod 

I try deleting cache, restart httpd, reinstall/install mautic(all versions 1.1.3, 1.2.0, 1.2.1, 1.2.2 as well) but nothing works. When I try the same campaign in cloud it works. Please help me find out the root cause?

Thanks,
Nimesh

**Comment by npracht** [comment]
Hi, i think it's something very close to #1432.

**Comment by nimesh-mittal** [comment]
This happens only if you manually add campaign from leads page. If you add to a lead list then campaign works just fine.

If you add lead to campaign using REST API then also it works. Problem is only when you add lead to campaign manually from leads profile page.

**Comment by dongilbert** [comment]
@nimesh-mittal Can you elaborate on this with steps to verify? How did you come up with this as the path to replicate? It's very interesting that you were able to track that down, I'm going to take a look tomorrow into this.

**Comment by mateusmh** [comment]
also I am with this issue, and I am using Pro matic online, someone could help me, since I contacted the support so far nothing more

**Comment by escopecz** [comment]
@mateusmh make sure it's not an issue of testing the email opens: https://www.mautic.org/docs/emails/troubleshooting.html

**Comment by harman83in** [comment]
I'm facing the same issue

**Comment by alanhartless** [comment]
@nimesh-mittal and @mateusmh, are you guys filtering the open emails decision? If so, custom emails are not considered in that. Custom emails simply copy the content from a given template email but is not associated with the original email ID and thus will not trigger a campaign decision.
