### ISSUE TITLE
Cloned Campaign Bug in Campaign builder

### ISSUE THREAD

**Issue by rodurma** [mautic/mautic#1455]
- Clone an exists campaign
- Click to edit this cloned capaign
- Open the campaign builder
- The fluxogram have a bug (parts of them isn't attached)

**Comment by rodurma** [comment]
https://www.youtube.com/watch?v=zE3Ze6eCokE

**Comment by kuzmany** [comment]
confirm

**Comment by fashionlearn** [comment]
Confirm

**Comment by escopecz** [comment]
This is duplicate of https://github.com/mautic/mautic/issues/1182
