### ISSUE TITLE
Compatible with PHP 7

### ISSUE THREAD

**Issue by comunidademautic** [mautic/mautic#1458]
Hello My Friends,

The Mautic is compatible with PHP 7?

Thanks!!!

**Comment by escopecz** [comment]
Hello! 

A quick google search gave me this:

https://www.mautic.org/community/index.php/2775-mautic-does-not-support-php-version-7-0-3-1/0
https://www.mautic.org/community/index.php/653-are-mautic-code-php7-compatible/0

The official current reuqirements:

https://www.mautic.org/download/requirements/

**Comment by BurlesonBrad** [comment]
@escopecz John, I hate it when folks start new tickets when there's already one that exists, so even though this is 'closed' hopefully I can jump in here.  
I primarily run WooCommerce sites. Hence, I only use php7.  

![mautic-php7](https://cloud.githubusercontent.com/assets/6208757/15155305/7f94e29a-16a7-11e6-9043-6e5fc2331129.png)
*....not gonna lie, I cried a bit as soon as I saw this screen :cry: *

I saw the requirements, but *(wrongly)* presumed that those were **minimum** php requirements. 

**What** & **How** would you like me to proceed to making the Magnificent Mautic compatible w/ php7?

**Comment by escopecz** [comment]
@BurlesonBrad You can always help us upgrade all libraries and the whole Mautic code base using it :) It is planed for Mautic 2.0 because in the same we'll have to drop support for PHP 5.3 and that will break BC. But something similar must be written in the links above.
