### ISSUE TITLE
Unsubscribe Link Error

### ISSUE THREAD

**Issue by moskoweb** [mautic/mautic#1460]
Hello

I am creating an email template, and is not working the unsubscribe link in html put as the picture 1 shows, and he even generates the link, but when clicked the link it goes to the page with error 500, as shown in the picture two.

Image 1
[http://prnt.sc/a4xxni](http://prnt.sc/a4xxni)

Image 2
[http://prnt.sc/a4xxwe](http://prnt.sc/a4xxwe)

I wonder what is wrong and how to solve because it is inconvenient for those trying to unsubscribe to this error.

(And the field to show the person's email is also not working)

Grateful

**Comment by escopecz** [comment]
1. What Mautic version are you using?
2. What error messages are in the Mautic (in the app/logs dir) and the server logs?

**Comment by moskoweb** [comment]
1. Version 1.2.4.
2. [2016-02-22 17:03:40] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Requested URL not found: /email/unsubscribe" at /var/www/em.maquinadelancamentos.com/htdocs/app/bundles/CoreBundle/Controller/CommonController.php line 352 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Requested URL not found: /email/unsubscribe at /var/www/em.maquinadelancamentos.com/htdocs/app/bundles/CoreBundle/Controller/CommonController.php:352)"} []

**Comment by moskoweb** [comment]
Solved the problem.

Grateful

**Comment by moskoweb** [comment]
I lacked the template messages on my theme

**Comment by viniciusaguiari** [comment]
Hi @moskoweb

Having the same problem here. How did you fix that?

thanks

**Comment by moskoweb** [comment]
Hello @viniciusaguiari, with the latest versions has been fixed, just make the file permissions adjustments and clear the cache.

And also to test, use an anonymous tab or just not be logged into Mautic during the test.
