### ISSUE TITLE
UI / Feature Request - Add display time for the validation message

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1469]
## The need

That the validation message does not stay eternally on the form on the webpage
## Suggestion

To add on the input form `validation` tab, the ability to display message `X seconds`

![capture d ecran 2016-02-25 a 09 57 12](https://cloud.githubusercontent.com/assets/14075239/13314810/58887d82-dba7-11e5-984a-0517cee003d3.png)

**Comment by dongilbert** [comment]
Would an acceptable fix be to remove the validation message once the field has been filled out?

**Comment by npracht** [comment]
Hi @dongilbert ,

The feedback i had from users/visitors was more about after `x seconds`it should disappear.
But your point is also interesting (not instead, but in more).

N.
