### ISSUE TITLE
PHP5.6 PHP Warning: mcrypt_encrypt(): Key of size 5 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported

### ISSUE THREAD

**Issue by jkuchar** [mautic/mautic#1480]
Hi! It looks like PHP5.6 is enforcing key length. Problem lies in [EncryptionHandler:80](https://github.com/mautic/mautic/blob/4686c8966240412f9f3a50f3d437d6a6006800c3/app/bundles/CoreBundle/Helper/EncryptionHelper.php#L60)

[The same problem in another project.](https://github.com/bemosior/PHPasswordPusher/issues/31)

I'm not really encryption expert so I do not have any idea how to fix this, however I can do some testing if needed.

PS: Can this have some relation to the fact that I cannot enable facebook integration. (missing app_id in OAuth application authorization?)

**Comment by escopecz** [comment]
Could you test if https://github.com/mautic/mautic/pull/1396 fixed it for you?

**Comment by dongilbert** [comment]
This has been addressed in the Mautic 1.3.0 release.
