### ISSUE TITLE
How to add 1 point per pageview ?

### ISSUE THREAD

**Issue by l2aelba** [mautic/mautic#1487]
![screen shot 2016-02-29 at 09 33 14](https://cloud.githubusercontent.com/assets/983458/13389358/85ddf352-dec7-11e5-84f3-a4bb70268e6b.png)

This is my current settings (Points -> Manage actions) , Seems like it does not work.

Any idea ? Thanks

**Comment by kuzmany** [comment]
I guess your page doesn't have https://, but http:// prefix.

**Comment by l2aelba** [comment]
@kuzmany But my site with `https://`

**Comment by escopecz** [comment]
@l2aelba Check https://www.mautic.org/docs/pages/troubleshooting.html and let us know if the problem wasn't in the tracking.

**Comment by l2aelba** [comment]
@escopecz Im pretty sure im following the https://www.mautic.org/docs/pages/troubleshooting.html 
But my point action just added +1 only once

**Comment by escopecz** [comment]
Ahh, so that's the problem. Yes, Mautic can trigger the point actions only once. There is already this feature request to allow trigger it multiple times: https://github.com/mautic/mautic/issues/929
