### ISSUE TITLE
[Bug] Tracking GIF of Scheduled Email

### ISSUE THREAD

**Issue by alvinbenavides** [mautic/mautic#149]
Emails sent by forms or manually have this tracking gif
http://mydomain.com/mautic/email/54fb8b40038e6.gif

Emails scheduled by campaigns have this tracking gif
http://localhost/email/54fb8676530d4.gif

**Comment by alanhartless** [comment]
Hi!

In your configuration, do have the site url filled in? That is required to correctly generate urls from cron jobs since it's not a web server processing the scripts. 

If you do have that set, then we definitely have a bug. 

Thanks,
Alan

**Comment by alvinbenavides** [comment]
Is set to my Mautic url (http://mydomain.com/mautic)

**Comment by alanhartless** [comment]
Ah. I think I know the issue. I think we applied the fix to landing page links, etc in the body but just not be doing the same for the pixel (obviously). Will get that fixed.

**Comment by alanhartless** [comment]
Hey Alvin,

Can you help me test something?

Open app/config/parameters.php and replace the very last line with 

```
// Set the router URI for CLI
if (isset($mauticParams['site_url'])) {
    $parts = parse_url($mauticParams['site_url']);

    $container->setParameter('router.request_context.host', $parts['host']);
    $container->setParameter('router.request_context.scheme', $parts['scheme']);
    $container->setParameter('router.request_context.base_url', $parts['path']);
}

unset($mauticParams, $replaceRootPlaceholder, $bundles);
```
Delete app/cache/prod and then retry.  Turns out Symfony has a built in feature for handling CLI routes so wanted to get a second person to try it out before I submit it.

Thanks!
Alan

**Comment by alvinbenavides** [comment]
Hi Alan.

Tracking gif is now generated correctly after that change. I can see the gif with Mautic URL and is tracking correctly in lead history.

On the other hand, I'm still having problems with leads and lists after opening emails, I sent you and email following last tests after rc3.

Thanks.

**Comment by pitus** [comment]
Here's a suggestion for the siteUrl config parameter, as it seems very sensitive to whether it includes a trailing forward slash `/` or not - perhaps you should check for that (when saving it on Admin page) and remove it if present (to avoid things like a double slash in the tracker `domain//email/...` ?
You could also show a warning on the Dashboard when it's not been configured (as a reminder) ?
