### ISSUE TITLE
Feature Request - Auto Map Leads Import Columns

### ISSUE THREAD

**Issue by OlafDammann** [mautic/mautic#1491]
An idea on the Leads-Import: today each field need to be manually mapped to the collumn in the CSV-File. Even if the header in the CSV-File has exactly the fieldname of Mautic, manual work is required. 
Maybe it would be a bit simpler, if the fields can be matched automaticaly?

**Comment by ipso** [comment]
It would be great if the last import settings could be saved and used the next time. In cases where you want to import the same file format each week for example.

**Comment by chandon** [comment]
This is already possible by naming your column with the field identifier
E.G. Field "My Field" => column name "my_field"

**Comment by ipso** [comment]
Unfortunately you don't always get to control the contents of the CSV file that is being imported, so having to change the column labels in the file kind of defeats the purpose of the feature request.
