### ISSUE TITLE
new install, index.php doesn't load

### ISSUE THREAD

**Issue by nvoi** [mautic/mautic#1493]
## Description
installing 1.3 on GoDaddy with PHP Version 5.4.43 on server, i can access all other files, e.g. dev_index.php and upgrade.php.

## Steps to reproduce
http://testing.snhotels.com/crm/index.php

**Comment by nvoi** [comment]
having the issue with another webhost (midphase) as well, there it returns an error 500 and when running site diagnosis it returns an error 403:

Windows received an HTTP error message: 403 (Forbidden) from "domain.com" Detected Detected 
 
Contact the owner of the remote site for permission Completed 
 
Windows can reach the site, but you do not have permission to access the content.

**Comment by escopecz** [comment]
It seems like your server is blocking the access (forbidden). It doesn't seem like a Mautic issue. What's in the server and Mautic logs?

**Comment by escopecz** [comment]
Closing for lack of feedback. Can be opened when the log information will be provided.
