### ISSUE TITLE
plugins page not working after update

### ISSUE THREAD

**Issue by filkuzmanovski** [mautic/mautic#1498]
## Description
As soon as I updated, the plugins page started to not respond. The dashboard and all components are working fine after the update, but I cant seem to get around fixing the plugins page problem. Here is a screenshot of the page when I manually try to get to the plugins page by entering the full url of its destination.
http://imgur.com/zArBkUm

**Comment by escopecz** [comment]
It says:

> Check server logs for errors

So what's in the logs?

**Comment by filkuzmanovski** [comment]
I will paste the server logs as soon as I check the issue again.

**Comment by zstephen** [comment]
are you getting similar symptoms to what I did in this issue?
https://github.com/mautic/mautic/issues/1514
Your symptom is one of the two I'm facing in this issue
