### ISSUE TITLE
Filemanager Error / mautic 1.3.0 regression.

### ISSUE THREAD

**Issue by echh** [mautic/mautic#1499]
When trying to open the Filemanager after i updated my mautic productive  version from 1.2.4 to 1.3.0
the Filemanager shows a forever spinning wheel. It used to work before. 

The server log says:

[error] 24861#0: *56100 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\InactiveScopeException' with message 'You cannot create a service ("templating.helper.assets") of an inactive scope ("request").' in /webroots/mautic/app/cache/prod/appProdProjectContainer.php:2765

**Comment by Salamek** [comment]
Same here, mautic is useles now... we cant add images to email template

**Comment by alanhartless** [comment]
We don't want to be useless ;) so give #1506 a shot and let us know how it works out. 

Thanks!

**Comment by Salamek** [comment]
@alanhartless yes #1506 fixes this

**Comment by echh** [comment]
You are far away from being useless! 
The patch fixes the problem here too.
Thank you very much.

**Comment by wamdam** [comment]
Fixes it for me too.
