### ISSUE TITLE
Listview: Arrow-Buttons

### ISSUE THREAD

**Issue by OlafDammann** [mautic/mautic#1500]
I have a List with 174 Leads. Go "Manage Lists", klick "View 174 Leads", selsect 10 Users in the selectbox below the "points" Collumn.
This results in those navigation buttons at the bottom left:
<< < 1 2 3 4 > >>
Klicking on >> should bring me to Page 18, the least one.
Instead it brings me to 4, it is always "current Page plus 4", if that makes sense.
Some "we'll fix this later" leftover?

**Comment by npracht** [comment]
Duplicate https://github.com/mautic/mautic/issues/1464
