### ISSUE TITLE
[Feature] Count selected leads on lists

### ISSUE THREAD

**Issue by alucmb** [mautic/mautic#1501]
I don't know if already has some way to see it but I couldn't find.. It would be great when we check leads in a list, Mautic show the number of leads selected.

 I'm not a developer  so don't know the complexity,  but something simple like on excel will certainly do the trick: selecting the checkbox of the lead the counting will appear on the end of the list, maybe next to the max number of exibition on page.

**Comment by ldrrp** [comment]
Also the overall total would be nice on the bottom of the tables.

**Comment by npracht** [comment]
Hi, i think that should be included with a feature request https://github.com/mautic/mautic/issues/1172

**Comment by forex4noobs** [comment]
This would be great, I am not sure how to see my total contacts without adding a segment called "all" and adding all contacts to that segment. I would never email to that segment, so having it there is redundant.
