### ISSUE TITLE
HTML content is appended to JSON response on error

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1504]
An ajax call running on the click of the sort for Manage leads table seems to not display the data. I did notice theres json mixed with html.

`curl 'https://track.techreanimate.com/s/leads?tmpl=list&name=lead&orderby=l.city%2C%20l.state&mauticUserLastActive=1&mauticLastNotificationId=179' -X POST -H 'Pragma: no-cache' -H 'Origin: https://track.techreanimate.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,es;q=0.6' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Cache-Control: no-cache' -H 'X-Requested-With: XMLHttpRequest' -H 'Cookie: mautic_lead_avatar_panel=expanded; mautic_session_name=' -H 'Connection: keep-alive' -H 'Referer: https://track.techreanimate.com/s/leads' -H 'Content-Length: 0' -H 'DNT: 1' --compressed`

Produces

`{"activeLink":"#mautic_lead_index","mauticContent":"lead","route":"\/s\/leads","flashes":"","notifications":{"content":"\n","lastId":"179","hasNewNotifications":false,"updateAvailable":true},"browserNotifications":[],"newContent":"\n\u003Cdiv class=\u0022table-responsive\u0022\u003E\n    \u003Ctable class=\u0022table table-hover table-striped table-bordered\u0022 id=\u0022leadTable\u0022\u003E\n        \u003Cthead\u003E\n            \u003Ctr\u003E\n                \u003Cth class=\u0022col-actions pl-20\u0022\u003E\n  ...... cut out due to size .......   "}<!DOCTYPE html>
<html lang="en">
<head>
    <title>Site is offline</title>
</head>
<body>
 <h2>The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.</h2>
<h4 class="mt-15">System administrators, check server logs for errors.
</body>
</html>`

**Comment by ldrrp** [comment]
Now that i notice everything else thats broken also does the same thing, json is returned with what seems to be the Site is offline html

**Comment by PatchRanger** [comment]
I confirm the bug. In my case it prevents closing modals.

How to reproduce (worked in my case):
- Open Contacts page
- Choose "Send email" from dropdown menu
- Cancel the modal

Expected: The modal closed.
Reality: The button became inactive - but the modal is still open.

System
- Mautic 1.4.1
- PHP Version 5.6.20
- Apache 2.4.10 (Unix)

I checked the result of AJAX request - yes, it looks like JSON, which is followed by HTML of Site offline page.

**Comment by PatchRanger** [comment]
@ldrrp Could you please verify that the suggested fix #1860 works for you?
