### ISSUE TITLE
After updating to 1.3 i cannot access mautic with oauth. Api calls are no longer working. 

### ISSUE THREAD

**Issue by stevenvdhout** [mautic/mautic#1505]
## Description
After updating to 1.3 i cannot access mautic with oauth. Api calls are no longer working. 

I get the following error in the mautic log
mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Client not found."

**Comment by escopecz** [comment]
Could you please check if the API credentials exists in Mautic? From what version were you upgrading? Clearing the cache won't help?
