### ISSUE TITLE
1.3.0 upgrade issues on bitnami mautic

### ISSUE THREAD

**Issue by ashishgurprit** [mautic/mautic#1509]
## upgraded to mautic 1.3.0 through bitnami on amazon. Site stopped working and gives the following message:

> The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator. System administrators, check server logs for errors.
>
I was told to delete cache folder. I did that. But the site is still not coming up. 
My landing pages, emails lists and every other asset is down. Please help in rectifying.

**Comment by escopecz** [comment]
What's in your logs as the error message says?

**Comment by escopecz** [comment]
Closing for lack of feedback. Can be opened again when the log information will be provided.
