### ISSUE TITLE
Allow embed images ? / Feature Request

### ISSUE THREAD

**Issue by Salamek** [mautic/mautic#1511]
## Description
Hi, one of my customers require send emails with embed images, correctly displayed email is no.1 for them and i totaly understand this request, traffic is not a issue.
But i was qite disappointed that mautic do not support this option ?! I was unable to find any configuration option or mention in docs....

For now i implemented this feature by adding:
```php
$matches = array();
if (preg_match_all('/<img\s+src="([^"]+)"/i', $content, $matches))
{
  $replaces = array();
  foreach($matches[1] AS $match)
  {
    $replaces[$match] = $this->message->embed(\Swift_Image::fromPath($match));
  }
  $content = strtr($content, $replaces);
}
```
to `app/bundles/EmailBundle/Helper/MailHelper.php:844` (start of `setBody` method, before tracking pixel is added)
But i'm not sure if this is correct place and way how to implement this + i had to comment out:
```php
public function decodeTokens(EmailSendEvent $event)
    {
        // Find and replace encoded tokens for trackable URL conversion
        /*$content = $event->getContent();
        $content = preg_replace('/(%7B)(.*?)(%7D)/i', '{$2}', $content, -1, $count);
        $event->setContent($content);

        if ($plainText = $event->getPlainText()) {
            $plainText = preg_replace('/(%7B)(.*?)(%7D)/i', '{$2}', $plainText);
            $event->setPlainText($plainText);
        }*/
    }
```
in file `app/bundles/EmailBundle/EventListener/TokenSubscriber.php` or i get:
```bash
Unable to open file for reading [cid:06cab7a7775d76d88eb4d4b42deae182@mautic...
```
I'm not a Symphony/Mautic guru, so i was unable to solve decodeTokens issue thats why i'm not sending a PR.

Would be great if someone could implement this feature (in better way then i did) and add it as option into configuration.

Thx
Adam

**Comment by escopecz** [comment]
I'm not sure what you mean by the image embed. But if you want to add a `<img/>` tag to the email with a link to remote image, there is a button for it in the editor:
![mautic-insert-image](https://cloud.githubusercontent.com/assets/1235442/13600914/69cf0cd0-e52c-11e5-8e98-20314469d314.png)

If you want to add the whole image in base 64 to the `<img/>` tag, just copy-paste it to the editor textarea. Or do you need something different?

**Comment by Salamek** [comment]
@escopecz I know all this! But:

* Remote images wont show by default in email clients cos "Do you want to show remote content ?"
* Adding base64 image into HTML template is BS, first it is not user friendly (it may be ~ok if "Insert image" had this function - something like "Insert as Base64", but that is still wrong), second working with lead image (~60KiB) in base64 is killing my browser
* Embed image into email means that software "on send" converts all images in email template to cid + base64 in message, it is described in RFC https://tools.ietf.org/html/rfc2110#page-13
* Lot of email libraries do this ^ by default or it can be configured for specified paths etc, swift is using $cid = $this->message->embed(\Swift_Image::fromPath())
* Convert images on send is better cos it is non destructive operation for email template and template HTML code is clean of big base64 mess

So what i need is option to enable this image conversion for whole mautic installation or single email

**Comment by escopecz** [comment]
That is much better description than you originally provided. I'll mark this as feature request.

**Comment by Salamek** [comment]
@escopecz THX
