### ISSUE TITLE
Unable to view lead history

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#1514]
## Description
Unable to view lead history

## Steps to reproduce
Upon clicking lead(Under Leads>Manage Leads), loading animation briefly shows then nothing loads.
If I manually visit the URL shown when mouseover the lead I want to view, I receive this error.
![screenshot from 2016-03-09 20 44 50](https://cloud.githubusercontent.com/assets/10385295/13631259/d63a60ca-e637-11e5-9d16-d8c848a6552f.png)
This behaviour has only happened since I upgraded to 1.3.0 from 1.2.4
I'm having trouble getting detail from the logs even after changing locations in "Path to the log directory"

**Comment by escopecz** [comment]
@zstephen thanks for the report. I'm not able to reproduce it and without the specific error message from the logs it's not possible to tell what's causing it. Please, try to get the message. Maybe check the permissions if Mautic have right to write them.

**Comment by zstephen** [comment]
thanks @escopecz I just found that when I clicked the lead, this line was put into the log when I watched with tail -f

> [2016-03-09 10:03:43] mautic.ERROR: Fatal: require(): Failed opening required '/home/user/public_html/sites/subdir/subsubdir/app/cache/prod/doctrine/orm/Proxies/__CG__MauticFormBundleEntityForm.php' (include_path='.:/opt/alt/php55/usr/share/pear:/opt/alt/php55/usr/share/php') - in file /home/cpsuper/public_html/sites/subdir/subsubdir/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 207 [] []

**Comment by zstephen** [comment]
I resolved this issue by deleting this folder "%kernel.root_dir%/cache" when I loaded the interface Mautic rebuilt it.

Is there a best practice to clear the cache in between updates or can this be scripted into the upgrade process?

The following issues seem related #1515 #1514 #1498

**Comment by hansakoch** [comment]
I'm having the same issue...

**Comment by zstephen** [comment]
@hansakoch go into your config and see if your cache directory is listed as 

> %kernel.root_dir%/cache

If it is, then you'll find it in this subdirectory of mautic's working directory "app/cache" rename(safest) or delete this cache folder, then reload the Mautic interface, you should see it has reappeared, does the issue continue for you then?

**Comment by hansakoch** [comment]
http://mautic.mycompany.com/s/config/edit
I get the same error when accessing the config page.
The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
System administrators, check server logs for errors.
