### ISSUE TITLE
Returning visit on specific URL wrong scored

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1518]
## Description
I have a the feeling that a **point action** has not the behavior it is expected to do.
A visitor of the page `http://www.domainname.com/*` should be scored when he revisits the same page.
![capture d ecran 2016-03-10 a 11 48 42](https://cloud.githubusercontent.com/assets/14075239/13668422/060e333c-e6bd-11e5-8214-2edda5b4e9bd.png)

### Issue
I think it scores if the lead visits the page `http://www.domainname.com/*` after having visited any tracked page before.
![capture d ecran 2016-03-10 a 11 48 59](https://cloud.githubusercontent.com/assets/14075239/13668430/1327ae86-e6bd-11e5-9b9b-45b5e1ba5597.png)

As you can see, the lead is scored for the first visit of the URL `http://www.docapost-rh.com/*` (there is nothing on this page before). But the lead respects the expected behavior to be scored for a previous visit on another tracked page the 23rd and 26th of February.

_____________

Did i wrongly understand the feature or is it an issue?

**Comment by blauerberg** [comment]
It seems to once the action has been apply, point does not change from next time.

https://github.com/mautic/mautic/blob/staging/app/bundles/PointBundle/Model/PointModel.php#L194

**Comment by dongilbert** [comment]
Fixed in #2296
