### ISSUE TITLE
Very slow editing of landing pages

### ISSUE THREAD

**Issue by duduric** [mautic/mautic#1522]
Opening Landing Pages on our installation is really slow. It takes almost 30 seconds to load when you click any of them. We have around 150 landing pages live, though I don't believe this is the reason.
Any ideas what could be causing that?
We notice the leads table gets huge very fast (almost 200.000 records), since we have many hits. Are they somehow loaded when you open a landing page?

**Comment by escopecz** [comment]
Leads or page hits shouldn't be loaded on landing page open. Are you talking about opening them as public pages or in the administration? Some statistics are loaded in administration, but it shouldn't make a problem with 200.000 records. What hardware is your Mautic running on?

**Comment by duduric** [comment]
Hello,
I isolated the problem to those pages:
http://<mautic>/s/pages/view/??
It seems the whole system is frozen for a long time (30 seconds) when loading the stats of this page. (it got a LOT faster when we wiped the data from page hits directly in the database, such as IP addresses, leads, etc)
Right now I just instructed everyone to access directly the edit page, thus skipping this one. Is there a quick hack to stop this page from calculating statistics? (or just disable hit tracking at all, since we are only interessed in form results)

We are using a a "t1.small" Amazon EC2 instance.

**Comment by escopecz** [comment]
The landing page stats will be changed in Mautic 2.0. You can [test](https://github.com/mautic/mautic#how-to-test-a-pull-request) https://github.com/mautic/mautic/pull/1713. It'd be very valuable if you could tell us whether the new stats are faster.

**Comment by vasco** [comment]
We've to wait several minutes for this page to load..

Then the number of db active connections start to increase, and everything stops working.. We have to restart the database and the Mautic instance.

We are running on top of Google Cloud (1 instance in Google Compute Engine) and the database uses Google Cloud SQL.

Mautic Version: 1.4.0
