### ISSUE TITLE
Queues of sending more than 2 lead are not tracking links

### ISSUE THREAD

**Issue by rafas** [mautic/mautic#1524]
## Description
When Mautic create **any queue** by sending **campaign**, only **the first** e-mail is replacing the **tracking links**.

**The error always happens for 2+ emails from the send queue.
The first email from the send queue is always saved.**

## Steps to reproduce
1. Create a new email template with some test text and a single web link to www.google.com 
2. Create a list with only TWO OR MORE leads in it
3. Create a very simple workflow for the list from #2 using the email template from #1 - a single "Lead Lists" source connected to a single "Send Email" action
4. Set the email send option to "Immediately" in the configuration. Note, this setting simply makes the test case more concise, the problem exists regardless of this setting (it's just a bit harder to debug)
5. Execute the following two actions from CLI and make sure they execute without any errors:
/path/to/mautic/app/console mautic:campaigns:update
/path/to/mautic/app/console mautic:campaigns:trigger

1. Wait for the emails to arrive to their desired destinations
2. Examine the emails closely, particularly the web link. In one of them it is pointing to www.google.com  while in the other one it is pointing to your Mautic deployment instance. The problem is that only one of the emails has its web link replaced by a traceable link. The other one doesn't.

Infos on this link
https://www.mautic.org/community/index.php/1219-sometimes-mautic-seems-to-automatically-add-trackable-urls-to-t/p2#p8149

**Comment by ps92** [comment]
Tested by me. It works.

**Comment by rafas** [comment]
@ps92 The bug it works?

**Comment by rafas** [comment]
I updated the mautic to Version 1.3.1 and the bug struck again.
URLs sent in the second+ lead on the submission queue are not being tracked.

**Comment by FarhadF** [comment]
Tested it , working fine.

**Comment by ps92** [comment]
@rafas  No, I meant it solves the problem. Thank you.

**Comment by wittwerch** [comment]
The bugfix is working. 
@rafas Can you please create a PR so we get a chance that this fix will be quickly released?
