### ISSUE TITLE
Quick add lead doesnt add the owner

### ISSUE THREAD

**Issue by vihuarar** [mautic/mautic#1529]
When a user that has a role that only he could view/edit his own leads and use the bottom "Quick add lead" the new lead doesn't not belong to the user that created, so the lead is not visible for the user that created that lead...

This problem only happen when the new lead is created using the "quick add lead", when you use "new" bottom, the lead by default is assigned to the user that created it..

## Steps to reproduce
1. Create a user and assign a role that only could see the leads that he own
2. Create a lead using the "Quick add lead"
You will see that the new lead is not visible to that user... because the lead is owned by anyone...

**Comment by escopecz** [comment]
Thanks for the report. Fixed in https://github.com/mautic/mautic/pull/1533. A test would be welcome.

**Comment by vihuarar** [comment]
It works! thank you very much!
