### ISSUE TITLE
Mautic File Manager, Browse Server Page Never Loads Up

### ISSUE THREAD

**Issue by StrategicDeveloper** [mautic/mautic#1532]
## Description
Stack trace:
#0 /home/.../app/bootstrap.php.cache(2125): appProdProjectContainer->getTemplating_Helper_AssetsService()
#1 /home/.../app/bundles/CoreBundle/Factory/MauticFactory.php(749): Symfony\Component\DependencyInjection\Container->get('templating.help...')
#2 /home/.../app/bundles/CoreBundle/Templating/Twig/Extension/AssetExtension.php(28): Mautic\CoreBundle\Factory\MauticFactory->getHelper('template.assets')
#3 /home/.../app/cache/prod/appProdProjectContainer.php(2824): Mautic\CoreBun in /home/.../app/cache/prod/appProdProjectContainer.php on line 2765
[15-Mar-2016 01:44:27 America/Chicago] PHP Fatal error:  Uncaught exception 'Symfony\Component\DependencyInjection\Exception\InactiveScopeException' with message 'You cannot create a service ("templating.helper.assets") of an inactive scope ("request").' in /home/.../app/cache/prod/appProdProjectContainer.php:2765
## Steps to reproduce
When I open the launch the landing page buildet, and click the image button, the filemanager never loads. 
![fm](https://cloud.githubusercontent.com/assets/13268405/13794310/51c217ac-eac9-11e5-827e-59d98a7f9d20.PNG)

Please Help...

**Comment by StrategicDeveloper** [comment]
My problem has been solved with the file manager from Fixes:#1499, which was a big help.

But can you please elaborate more on the error code for me please.

**Comment by escopecz** [comment]
Please continue your comments in #1499 to keep the conversation about one topic at one place.
