### ISSUE TITLE
Enhancement - Language for forms --> Different waiting form message

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1536]
## Description

When you submit a form, there is a **waiting message** on the button (time of the submission).
This message is in **ONE single language** no matter the language of the browser of the visitor or anything.

**It should be more flexible.**
## Language of the waiting message

It seems that the language is coming from the general settings default language.
![capture d ecran 2016-03-16 a 17 55 35](https://cloud.githubusercontent.com/assets/14075239/13821118/8aad5d42-eba0-11e5-9f09-96e6e1c1833b.png)
### 1. Choose the language of the form

It could be possible to set the language of the form in the form settings as it is on landing pages and emails.
![capture d ecran 2016-03-16 a 17 59 48](https://cloud.githubusercontent.com/assets/14075239/13821233/0a020a98-eba1-11e5-8f9d-198419c7841e.png)
### 2. Choose the language of the browser of the visitor

Nothing else to say than in the title of this section. The form could check the language of the browser of the visitor. It'd be smart.
### 3. Manually set the value of the message

In the setting of the form, as you set the validation (success) message, you could have the opportunity to set the waiting message
---> **This is the most flexible solution.**
![capture d ecran 2016-03-16 a 17 59 48](https://cloud.githubusercontent.com/assets/14075239/13821366/8f8715dc-eba1-11e5-954a-2b38c6a1893c.png)

**Comment by pacbrother** [comment]
Is there a temporary solution to translate this message?

**Comment by maisonbuga** [comment]
Is this topic still open? Or is a solution available?

**Comment by cremigerhonig** [comment]
same problem here... need a solution :/
