### ISSUE TITLE
mautic.com support?

### ISSUE THREAD

**Issue by ahansson89** [mautic/mautic#1537]
I have left two support messages, tried to call your phone number and have not received a reply about some issues that I am seeing on mautic.com for two weeks now. I am a paying customer.

Can the mautic.com team please respond to my messages?

I feel bad that I have to post this message in here as a lot of people will get a notification, but this seems to be the only way to reach Allyde.

**Comment by ahansson89** [comment]
Bump

**Comment by paulocastellano** [comment]
I had the same problem a few weeks ago...

**Comment by ahansson89** [comment]
Well, they still haven't replied. Sent 4 emails and called them 10 times. Getting ridiculous!

**Comment by escopecz** [comment]
Guys, I'm sorry to hear that. I hope they answer soon. But there is nothing the open source community can do with a commerce service so I'll close this issue.

**Comment by ahansson89** [comment]
Still havnt gotten a reply for almost 2 months now. Sent 5 emails and called probably 8 times. Dissapointing!

**Comment by escopecz** [comment]
I checked with Allyde. They have 3 support tickets from you. All are answered. They replied to the last one on March 25 and reached you again on March 30. Maybe the replies went to the spam folder?
