### ISSUE TITLE
Feature request - Add bounce/unsubscribe fields to the .csv import page

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1543]
## Context

When you start on marketing automation you often have already done a bit of newsletter via Mailchimp for instance.
By consequence, when you **import the first time your database** you already have some leads flagged as **bounced** or **unsubscribed**.
## Definition of the need

It would be great to have on the import page, a field to map **Bounced** and **Unsubscribed** leads.
### Existing `do not contact` field

On the import page, we have a field called `do not contact`.
1. Is it **Bounce management** or **Unsubscribe management** field?
2. Format to import is boolean `1` / `0`, it could be clearer.
## Recommandations, feature request definition
- Rename the existing field to `Bounced` or `Unsubscribed` depending on the answer to my previous question.
- Add a tool tip to explain:

> Import the value `0` (false) or `1` (true)
- Add a second field for `Bounced` or `Unsubscribed` depending on the missing one (depending on answer to question 1).

**Comment by vihuarar** [comment]
I'm confused too.. theres not documantation to import unsuscribe lists....

**Comment by escopecz** [comment]
I wrote the docs PR here: https://github.com/mautic/documentation/pull/151

I'll leave this issue open, because other types of do not contact should be added and also to support other channels.
