### ISSUE TITLE
New endpoint request - Get leads from a list ID

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1549]
## Need
Via API to get all the contacts from a list via list ID.
Something like « **Get leads from a list ID** »

### Option 1

1. API Call - Get leads list of list ID `X`
2. It returns lead IDs.

### Option 2 (more complete)

1. API Call - Get leads list of list ID `X` & all the lead `fields` you need.
2. It returns le lead IDs + lead `fields` requested (`email`, `firstname`, etc.).

**Comment by LAN-Laurene** [comment]
Hello,

FYI, you can filter lead request with list alias via API:

```
// ...
$leadApi  = MauticApi::getContext("leads", $auth, $apiUrl);
$leads = $leadApi->getList("list:list-alias");
```

Attention results will be paginated.
