### ISSUE TITLE
POST Request instead of tracking gif

### ISSUE THREAD

**Issue by ahansson89** [mautic/mautic#1550]
The tracking gif is slowing down my site and I wonder why you are not using a POST request instead of the tracking gif? Wouldnt we be able to send all the same information this way?

**Comment by escopecz** [comment]
Do you think that POST will be faster than GET?

**Comment by ahansson89** [comment]
Why is that relevant?

**Comment by drmmr763** [comment]
You said the tracking gif is slowing down your site, and then suggested using POST over GET. So the question is, why would POST be faster or solve your immediate issue?

**Comment by ahansson89** [comment]
With a POST request we could have a timeout in the amount of time we are willing to wait for a response.

**Comment by drmmr763** [comment]
Hmm. I accept that as a true fact, but I don't see how it actually helps to resolve your issue. 

1) If you use a timeout then the information never gets recorded in mautic, thereby you loose data. Not useful. 
2) Using POST would be pretty difficult in terms of usability. With GET the tracking gif is included as markup:
```
<img src="/tracking.gif"> 
```
How would you achieve this with POST? Only thing I can think is going down the route of some ajax to do a POST action on pageload or using FORM tags. All seem pretty ugly solutions.

**Comment by escopecz** [comment]
You can set a timeout with any request, can't you? Doesn't really matter whether it is GET or POST.

**Comment by ahansson89** [comment]
1. Just because it is timing out doesnt mean that the information posted is not being processed by the server.
2. You can just fire it up with AJAX, nothing difficult in that.

@escopecz how will you make a timeout with this: <img src="/tracking.gif">  ?

**Comment by escopecz** [comment]
You can load the `mtracking.gif` with all the data you need in the URL query as AJAX GET request. Or do you have some problem with it?

**Comment by drmmr763** [comment]
If you're going to fire it with ajax then you can do that perfectly well with ajax right now using GET. The "complexity" is that a majority of users aren't capable of rolling their own JS. Adding a tracking pixel is a lot easier than navigating the waters of writing out some jQuery or JS code. 

Also, the other issue with ajax is taht its entirely possible for a person to leave the page before the ajax is ever executed, again leading to loosing data. 

Also you can set the timeout for both get and post in your webserver config. 

Or, go even further and make the request as either GET or POST with Curl and set the timeout that way.

**Comment by escopecz** [comment]
Ehm, so what is the output of the communication above? That the current GET request can be used instead of POST? Can I close this issue? If someone thinks otherwise, comment bellow and we can re-open it.

**Comment by ahansson89** [comment]
Maybe someone can give an example of how this should be done?

**Comment by escopecz** [comment]
In what language?

**Comment by ahansson89** [comment]
javascript

**Comment by escopecz** [comment]
Ok, publish here what you have for the POST request and I'll try to modify it for GET request.

**Comment by ahansson89** [comment]
I don't have anything as I have no idea how this would be done.

**Comment by escopecz** [comment]
Hm, then probably take a look at [jQuery ajax method](http://api.jquery.com/jquery.ajax/). It's easier to use some well known library than the vanilla JS. It has good documentation with lots of examples.

**Comment by ahansson89** [comment]
I know how that works, but you cannot use $.get() on the tracking gif because of CORS on *.mautic.com

**Comment by escopecz** [comment]
You cannot use any AJAX request outside of your domain because of CORS. It doesn't matter if it is GET, POST, PUT or any other. You can use it if the server allows it in the response header. So you should probably ask the server administrator of your Mautic if he'd be so kind to add that header to Mautic requests. Or send a new issue or possibly the PR with this header being added to Mautic itself.

**Comment by ahansson89** [comment]
That is why I am suggesting a better way to track leads. Through a POST request to an API.

**Comment by escopecz** [comment]
I still don't understand what's the difference. You will still have to make a JS request to another domain and you will still have to deal with CORS.

**Comment by ahansson89** [comment]
I don't want to argue whether you see the difference or not.
Do you really think that sending data through a request to a gif file is the best way to do it in 2016? Come on. It may be the most simple way to implement it, but it gives you 0 control about a lot of factors including what kind of data that you want to send, dealing with CORS, timeout control etc.

**Comment by dbhurley** [comment]
You can just as easily send data to the same "GIF" endpoint as part of a javascript function and push any data you like (that's publicly updatable). There's no reason to think about it as just an img `src` I think there's some miscommunication happening here and a quick step back and clarity on what you want to accomplish might help to get this resolved fast.

**Comment by ahansson89** [comment]
I know it is not a static gif file. Anyways, I am over trying to convince you guys about this.

@dbhurley Do you work with mautic.com or only mautic.org ? I have requested support 3 times over the past month and have not yet gotten any response from them.

**Comment by escopecz** [comment]
So what you want is:
- Do the same as the tracking pixel does, but return a JSON response instead of the GIF image.
- And accept POST requests.

You want it because:
- GIF response is not technology for 2016.
- POST will let you send data as well.
- POST lets you set a timeout.
- CORS doesn't apply for POST.

What I'm saying (and I think the others as well):
- Take the gif image as a success message.
- Use GET the same way you'd use POST. GET also allows you to send data in the URL query.
- Any request can have timeout.
- CORS apply for any request from a browser to a server with different domain name than the browsed website.

That's why I don't see any benefit in implementing something different than what already is there.

I think we are in a loop so I'll rather exit from this discussion.

**Comment by dbhurley** [comment]
@ahansson89 I've responded to you directly. No sense feeling like you are having to convince people. 

In this thread I asked a simple question but you failed to respond to the question I asked or respond to the answer I gave. If you would like help then let's start with that. Further to the point I think @escopecz has outlined the ways to handle any asynchronous requests.
