### ISSUE TITLE
Disabling link tracking for in-house breaks URLs with lead fields

### ISSUE THREAD

**Issue by harman83in** [mautic/mautic#1553]
## Description
If lead fields are used in a link in an email like this:
`<a href="http://someurl.com.com?firstname={leadfield=firstname}">Click Me</a>`

These leadfields do not get populated for users logged into Mautic Admin. The disabling of link tracking happens right at top of `PageModel::hitPOage()` and bails out without converting the leadfields sent in the URL query. Recommend using a flag instead of bailing out

## Steps to reproduce

1. Create a link in email as above
2. Sent it to a lead (preferably yourself )
3. Open the email in the same browser in which you are logged into Mautic
4. The redirect URL will take you to `http://someurl.com.com?` instead of the above link

**Comment by escopecz** [comment]
> Recommend using a flag instead of bailing out

Could you describe this in more depth? What is the flag?

**Comment by harman83in** [comment]
Because of [line 341](https://github.com/mautic/mautic/blob/staging/app/bundles/PageBundle/Model/PageModel.php#L341) in `PageModel::hitPage()`, [line 445](https://github.com/mautic/mautic/blob/staging/app/bundles/PageBundle/Model/PageModel.php#L455) of the same function doesn't get executed.

So instead of returning the function at line 341, maybe use a Boolean flag like `$skipClickthroughStats = false` there. Then use this flag to track/not track the clickthrough, but still evaluate line 445 (update lead fields if some data were sent in the URL query)

**Comment by escopecz** [comment]
Do you think you could submit a pull request with your suggestions? I think that would make it 100% clear.
