### ISSUE TITLE
Ok, who broke Mautic's innerwebs?

### ISSUE THREAD

**Issue by BurlesonBrad** [mautic/mautic#1555]
![mautic-down](https://cloud.githubusercontent.com/assets/6208757/14021665/7e351cac-f1aa-11e5-8df6-2f37392ec18a.png)

I clicked the thing that went to the thing that makes the thing show up on the screen.  Then the thing with the innertubs on the facebook of the google didn't let me get to the innerwebs of Mautic, but the innertubes still worked.  Do I need to restart my router?

**Comment by alanhartless** [comment]
Hi!

Afraid our hosting provider did :) Keep an eye on https://status.digitalocean.com/ for the DNS issues they're having. Hopefully they fix it quick!

**Comment by dbhurley** [comment]
:) Best bug report all day. Please try turning it all off and back on again. ;) +100

**Comment by BurlesonBrad** [comment]
Closing: Router Restarted. Ocean Merged. Innerwebs back on. 
![kermit-typing](https://cloud.githubusercontent.com/assets/6208757/14035349/13b4cb06-f1fb-11e5-947b-8aad56ee0dfd.gif)
