### ISSUE TITLE
Add hour and days parameters to date filter for relative values

### ISSUE THREAD

**Issue by ukkokumpulainen** [mautic/mautic#1557]
## Description
For subcription based services, it would be ideal to have option to create smart lists based on relative dates.

For example, there is service which is going to expire within X days. This expiration date is stored in lead field and there would be smart list based on this expiration date, "where expiration date is less than +30 days"

Currently mautic allows only following relative values:
```
public static function getRelativeDateTranslationKeys()
    {
        return array(
            'mautic.lead.list.month_last',
            'mautic.lead.list.month_next',
            'mautic.lead.list.month_this',
            'mautic.lead.list.today',
            'mautic.lead.list.tomorrow',
            'mautic.lead.list.yesterday',
            'mautic.lead.list.week_last',
            'mautic.lead.list.week_next',
            'mautic.lead.list.week_this',
            'mautic.lead.list.year_last',
            'mautic.lead.list.year_next',
            'mautic.lead.list.year_this'
        );
    }
```

To improve this, I suggest to add there option to define relative values also by day count and by hours.

**Comment by iloris** [comment]
Like @ukkokumpulainen , I have this use case, when I need to trigger a campaign 40 days or 35 days fore the expiration date of a subscription of a specific list. 

`expiration date` `less than or equals` `today` works well to create a list with expired customers, but `expiration date` `less than` `+40 days` doesn't . 

Supporting php time would be great.

**Comment by ukkokumpulainen** [comment]
Been investigating this today and seems to work if you add following code into LeadListRepository.php
```
// check does this match php date params pattern?
if(stristr($string[0], '-') or stristr($string[0], '+')){
    $date = new \DateTime('now');
    $date->modify($string);
    $dateTime = $date->format('Y-m-d H:i:s');
    $dtHelper->setDateTime($dateTime, null);
    $isRelative = true;
}
```

**Comment by escopecz** [comment]
@ukkokumpulainen would you mind to send the code as a pull request?

**Comment by ukkokumpulainen** [comment]
There is now PR for this https://github.com/mautic/mautic/pull/1587
