### ISSUE TITLE
Mandrill issue: Replacement tags not processed correctly.

### ISSUE THREAD

**Issue by yyil** [mautic/mautic#1558]
## Description
When using Mandrill, the URLs, lead fields etc are not replaced properly.
Links are not clickable since they are not valid URLs.

## Steps to reproduce

Use Mandrill for email
Create new email
Insert a lead field such as `Hi {leadfield=firstname}`
Send to a list.

Received email says 
`Hi *|LEADFIELDFIRSTNAME|*`

I've used Mandrill before and this looks like replacement data is not passed in payload.

**Comment by alanhartless** [comment]
Is this still occurring in the latest versions of Mautic? Since Mandrill changed to require a Mailchimp account - I can no longer test.

**Comment by alanhartless** [comment]
Due to lack of feedback, we're closing this issue. Please upgrade to 2.1.1 and if the issue persist, definitely let us know! Thanks!
