### ISSUE TITLE
Support states outside of the USA

### ISSUE THREAD

**Issue by micoots** [mautic/mautic#1561]
## Description

Software doesn't seem to support states outside of the USA.
Am in Australia and can't find "NSW".
## Steps to reproduce

Leads -> Manage Leads -> click any "Name" -> Edit -> State

Only US states show up. What about Australian states?

You really need to think global.

**Comment by PatchRanger** [comment]
Confirming. Also when the data is got by IP lookup, it is correctly shown: I mean, State field displays correct part of the corresponding lead country. But if I click "Save & Close" this data disappears. I guess, there is some validation related to USA states only, it should be disabled.
