### ISSUE TITLE
Lead edit page html markup breaks if some lead field is unpublished

### ISSUE THREAD

**Issue by cmnstmntmn** [mautic/mautic#1562]
## Description
wrong html markup on lead edit page

## Steps to reproduce

1. go to leads / manage leads
2. click on one lead
3. then click **edit**
4. scroll down, and you'll see some messy divs, that should be placed inside `.tab-content .tab-pane` / `#core`

<img width="946" alt="screen shot 2016-03-30 at 14 04 11" src="https://cloud.githubusercontent.com/assets/2312755/14140362/290ea37a-f681-11e5-9b08-895676366034.png">
`

**Comment by escopecz** [comment]
I followed your steps, but I don't see the issue. Did you modify some Mautic code? Added some plugin? Isn't it a browser issue?
![mautic-edit-lead](https://cloud.githubusercontent.com/assets/1235442/14140525/b8a6a986-f679-11e5-878b-ca1b1a6649f2.png)

**Comment by cmnstmntmn** [comment]
facebook is enabled, and one custom field is created.
but same with them disabled. (version v1.3.1)


this is the markup.

https://gist.github.com/cmnstmntmn/25653f16914562b04ea07373c32a8620#file-markup-html-L272:L316

**Comment by escopecz** [comment]
Symfony would render [there](https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Views/Lead/form.html.php#L187) all form fields which weren't rendered to that point. Can you confirm that the overflowing fields are in a field group?

**Comment by cmnstmntmn** [comment]
in fact, **if the field is unpublished, it get's rendered outside**; even if is assigned to a group

<img width="1212" alt="screen shot 2016-03-30 at 16 17 41" src="https://cloud.githubusercontent.com/assets/2312755/14143281/16e0aaec-f693-11e5-8c76-d25042ad7626.png">

**Comment by escopecz** [comment]
Yes! That's it! I can replicate. I'll mark this issue as a bug.

**Comment by cmnstmntmn** [comment]
(;
