### ISSUE TITLE
"Mail is owner" not working in campaigns

### ISSUE THREAD

**Issue by ralstonandanthony** [mautic/mautic#1564]
## Description

Email sent from Campaigns is not sending from the Lead Owner, but instead sending from the default sender.

## Steps to Reproduce

1.) Create a Smart List
2.) Create new Leads, assign the Lead a Lead Owner and assign the Lead to the Smart List
3.) Create a Template Email for use in a campaign
4.) Create a Campaign adding the Smart List as the lead source and the Template Email as the first scheduled action to take palce at a specific date and time
5.) Publish the Campaign

Emails sent from the above campaign are not sending from the lead owner.

**Comment by hperk** [comment]
I have replicated this exact issue. Have you found any resolution?

**Comment by ralstonandanthony** [comment]
I have not yet found a solution to the issue.

**Comment by ToonGeneral** [comment]
This is a really big problem for us. Every email we send out has to be duplicated per employee. If we want to have something as simple as a 3x email campaign going from 3x staff, that's 9x email templates and 3x campaigns. That really doesn't scale! Is no one else using Mautic to this level that it isn't more of an issue?
