### ISSUE TITLE
mautic installation issue

### ISSUE THREAD

**Issue by noormcs** [mautic/mautic#1568]
## Description
I download your git mautic zip file upload it and then unzip on server after that step 2 run the following command
composer install
Error
-bash: composer: command not found

what I do? remember when ever provide a solution please provide full documentation and exact solution

**Comment by escopecz** [comment]
Please read the documentation for this repository and especially the Disclaimer part:

https://github.com/mautic/mautic#getting-started

**Comment by dbhurley** [comment]
_Original comment edited for content. _
