### ISSUE TITLE
Emails are not being sent out from mautic.org

### ISSUE THREAD

**Issue by vathuluri** [mautic/mautic#1569]
Hello, Im having an issue with emails not being sent out in a campaign. I added leads to a campaign which will send out emails. But it seems like none of the emails are being sent out. When I looked at the lead page all the events have been triggered and status says email has been sent out. It never made it to my inbox.  

I sent a support email a week ago no one ever responded.

**Comment by escopecz** [comment]
Hello, I think you mean mautic.com, not mautic.org, right? That is a commercial service which we cannot control from here. You'll have to wait till they answer your support ticket. But maybe it there is some issue in your campaign or email configuration. You can discuss it at https://www.mautic.org/community/. GitHub issues are more for reporting bugs or feature requests.
