### ISSUE TITLE
generate.js fails if form templates use CRLF or CR for line breaks

### ISSUE THREAD

**Issue by dmbhg** [mautic/mautic#1573]
My first couple days working on getting Mautic setup.  Found this out and figured it can save someone some time. 

## Description
After creating a custom form template for my theme under {theme name}/html/MaunticFormBundle/Builder/form.html.php on windows, loading any form would produce a "SyntaxError: unterminated string literal" error in firefox and not display.

## Steps to reproduce
Follow the instructions [here](https://developer.mautic.org/#form.html.php) to create a custom form view for your theme.  Change the newline format to CR and save, and clear db cache form.cached_html.  Revisiting the page will produce the error.

## Solution
FormModel::getAutomaticJavascript can be updated to support to support CR.

```php
      public function getAutomaticJavascript(Form $form)
    {
        $html = $this->getContent($form);

        //replace line breaks with literal symbol and escape quotations
        $search = array("\n", "\r", '"');
        $replace = array('\n', '\n', '\"');
        $html = str_replace($search, $replace, $html);

        return "document.write(\"" . $html . "\");";
    }
```

**Comment by escopecz** [comment]
@dmbhg Would it be possible to send a pull request with your suggestion?

**Comment by alanhartless** [comment]
Due to lack of feedback, we're closing this issue. If you'd like to see this added to the code, please submit a pull request. Thanks!
