### ISSUE TITLE
SQL error when running mautic:leadlists:update

### ISSUE THREAD

**Issue by n3o77** [mautic/mautic#1575]
## Description

When I run mautic:leadlists:update i'm getting the following MySQL error:

>   [Doctrine\DBAL\DBALException]
  An exception occurred while executing 'SELECT count(l.id) as lead_count, max(l.id) as max_id FROM leads l WHERE ()':
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at l
  ine 1

> Exception trace:
 () at /usr/www/users/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:91
 Doctrine\DBAL\DBALException::driverExceptionDuringQuery() at /usr/www/users/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:702
 Doctrine\DBAL\Connection->executeQuery() at /usr/www/users/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:204
 Doctrine\DBAL\Query\QueryBuilder->execute() at /usr/www/users/mautic/mautic/app/bundles/LeadBundle/Entity/LeadListRepository.php:382
 Mautic\LeadBundle\Entity\LeadListRepository->getLeadsByList() at /usr/www/users/mautic/mautic/app/bundles/LeadBundle/Model/ListModel.php:896
 Mautic\LeadBundle\Model\ListModel->getLeadsByList() at /usr/www/users/mautic/mautic/app/bundles/LeadBundle/Model/ListModel.php:429
 Mautic\LeadBundle\Model\ListModel->rebuildListLeads() at /usr/www/users/mautic/mautic/app/bundles/LeadBundle/Command/UpdateLeadListsCommand.php:90
 Mautic\LeadBundle\Command\UpdateLeadListsCommand->execute() at /usr/www/users/mautic/mautic/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /usr/www/users/mautic/mautic/vendor/symfony/console/Symfony/Component/Console/Application.php:882
 Symfony\Component\Console\Application->doRunCommand() at /usr/www/users/mautic/mautic/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /usr/www/users/mautic/mautic/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /usr/www/users/mautic/mautic/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /usr/www/users/mautic/mautic/app/console:34

>  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at l
  ine 1

> Exception trace:
 () at /usr/www/users/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:696
 PDOStatement->execute() at /usr/www/users/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:696
 Doctrine\DBAL\Connection->executeQuery() at /usr/www/users/mautic/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:204
 Doctrine\DBAL\Query\QueryBuilder->execute() at /usr/www/users/mautic/mautic/app/bundles/LeadBundle/Entity/LeadListRepository.php:382
 Mautic\LeadBundle\Entity\LeadListRepository->getLeadsByList() at /usr/www/users/mautic/mautic/app/bundles/LeadBundle/Model/ListModel.php:896
 Mautic\LeadBundle\Model\ListModel->getLeadsByList() at /usr/www/users/mautic/mautic/app/bundles/LeadBundle/Model/ListModel.php:429
 Mautic\LeadBundle\Model\ListModel->rebuildListLeads() at /usr/www/users/mautic/mautic/app/bundles/LeadBundle/Command/UpdateLeadListsCommand.php:90
 Mautic\LeadBundle\Command\UpdateLeadListsCommand->execute() at /usr/www/users/mautic/mautic/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /usr/www/users/mautic/mautic/vendor/symfony/console/Symfony/Component/Console/Application.php:882
 Symfony\Component\Console\Application->doRunCommand() at /usr/www/users/mautic/mautic/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /usr/www/users/mautic/mautic/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /usr/www/users/mautic/mautic/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /usr/www/users/mautic/mautic/app/console:34

I don't have any idea what exactly it's causing it. Any advise is appreciated. Thanks.

**Comment by LAN-Laurene** [comment]
Hello,

I think it is `WHERE ()` that causes the bug.
You should check `LeadListRepository->getLeadsByList()`.

**Comment by n3o77** [comment]
Problem was that we used an old PHP version in the cronjob.
