### ISSUE TITLE
getAssetUrl not working when sending e-mail trough campaigns

### ISSUE THREAD

**Issue by sandergo90** [mautic/mautic#1585]
I have setup a theme for a email we are sending out to our clients. When using the regular list emails nothing is wrong and the getAssetUrl() will return the correct image URL. When sending an email automatically trough a campaign, the getAssetUrl() does not return the schemeandhttphost when using it for an absolute URL. 

I think this problem occurs because the campaigns are being triggered by the cli and at that moment the schemeandhttphost can not be guessed ?

**Comment by escopecz** [comment]
Mautic has an option to set Mautic URL for CLI commands in its configuration. Please, check that the URL is entered in your case. Also, could you publish HTML code of the wrong link? I don't understand where `schemeandhttphost` shows up.
