### ISSUE TITLE
php console mautic:campaigns:trigger --env=prod stopping at 50% and quit

### ISSUE THREAD

**Issue by FarhadF** [mautic/mautic#1586]
## Description
php console mautic:campaigns:trigger --env=prod stopping at 50% and quit.
-------------------------------------------------
Triggering events for campaign 3
Triggering first level events
4762 total events(s) to be processed in batches of 100
 4762/**4762** [============================] 100%
**2400** event(s) executed

Triggering scheduled events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering 'non-action' events
0 event(s) executed

Next time that I run it , it will say 2362 events, and stops at 50% again...
## Steps to reproduce
Clean installation on Debian Jessie with today's updates.
sudo apt-get install apache2 php5 mariadb-server php5-mysql php5-gd php5-intl php5-imap php5-mcrypt
create database and user, extract 1.3.1.zip and import leads.

Thanks in advance
Farhad

**Comment by hadikalantari** [comment]
I have the same issue! any solution?

**Comment by escopecz** [comment]
What's written in the server and Mautic logs (app/logs dir)?

**Comment by FarhadF** [comment]
Hi escopecz and thanks for reply.

its the only file in app/logs, and its pretty small because I just finished installing.
[mautic_prod-2016-04-11.txt](https://github.com/mautic/mautic/files/212521/mautic_prod-2016-04-11.txt)

here is apache errorlog. that pdo exception happened after installation and fixed with a refresh I guess.
[error.txt](https://github.com/mautic/mautic/files/212527/error.txt)

Thanks
Farhad

**Comment by escopecz** [comment]
`Access denied for user 'www-data'@'localhost'`

There seems to be a problem to connect to the database server. Maybe the database server gets overloaded. If you write help message for that command:

`app/console mautic:campaigns:trigger -h`
You'll see these options:
```
Options:
 --campaign-id (-i)    Trigger events for a specific campaign.  Otherwise, all campaigns will be triggered.
 --scheduled-only      Trigger only scheduled events
 --negative-only       Trigger only negative events, i.e. with a "no" decision path.
 --batch-limit (-l)    Set batch size of leads to process per round. Defaults to 100. (default: 100)
 --max-events (-m)     Set max number of events to process per campaign for this script execution. Defaults to all. (default: 0)
 --force (-f)          Force execution even if another process is assumed running.
 --help (-h)           Display this help message
 --quiet (-q)          Do not output any message
 --verbose (-v|vv|vvv) Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
 --version (-V)        Display this application version
 --ansi                Force ANSI output
 --no-ansi             Disable ANSI output
 --no-interaction (-n) Do not ask any interactive question
 --shell (-s)          Launch the shell.
 --process-isolation   Launch commands from shell as a separate process.
 --env (-e)            The Environment name. (default: "prod")
 --no-debug            Switches off debug mode.
```
Maybe try to decrease the batch limit.

**Comment by FarhadF** [comment]
Thanks for reply,
I dont think that its overload problem. I reduced the batch size to 50, same problem at the exact 2400 events.
4762/4762 [============================] 100%
2400 event(s) executed
I even used -vvv for debug but not a useful output.

Anymore Ideas? 

Thanks in advance 
Farhad

**Comment by escopecz** [comment]
Maybe try 
```
sudo apt-get install php5-curl
sudo service apache2 restart
```

**Comment by FarhadF** [comment]
Thanks for reply,
installed php5-curl still quits at 2400 events.

**Comment by FarhadF** [comment]
Changed Email with something simple, Changed leads, Changed SMTP Server, Still no Luck.
Tried versions 1.2.4 , 1.3.0 , 1.3.1 ...

So your deployments working fine guys?

**Comment by escopecz** [comment]
Always check the logs when you're debugging something. Is there something new?

**Comment by FarhadF** [comment]
I dont have any errors :(

**Comment by FarhadF** [comment]
changed the email to a single "Hi" no links. Still same problem. When I rerun after each quit i get another 50% until I reach 100 remaining, Then it will do the whole 100 batch.

**Comment by FarhadF** [comment]
Installed via php composer and from clonning the git repository, still same problem. v1.3.2-dev
Starting to wonder if your guys installations are fine, because its hard to notice this issue. Any feed back would be great.

regards
Farhad

**Comment by FarhadF** [comment]
well I think its a bug, when I run sudo su www-data -s /bin/bash -c '/usr/bin/php /var/www/html/mautic/app/console mautic:campaigns:trigger --env=prod --batch-limit 10000' it works fine.
Notice the batch-limit is higher than total number of events.

**Comment by odises** [comment]
I have the same problem. any update?

**Comment by luizeof** [comment]
same here with 5 mautic servers

**Comment by escopecz** [comment]
Guys, could you please test https://github.com/mautic/mautic/pull/1609 and comment there how the test went?

**Comment by Bizcrony** [comment]
@escopecz Access denied for user 'www-data'@'localhost'

There seems to be a problem to connect to the database server. Maybe the database server gets overloaded. If you write help message for that command:

app/console mautic:campaigns:trigger -h
You'll see these options:

How i decrese the batch limit
