### ISSUE TITLE
FATAL: Database problem

### ISSUE THREAD

**Issue by richtera** [mautic/mautic#159]
When mautic loses the connection to the database (due to config settings or because mysql is down) it reverts to installation mode. From there the only choice is to reinstall which will erase all content.
It should not revert to installation mode, but rather notify that there are database problems. Then when those problems are fixed it should be able to resume normally. I keep on losing all my content, because my database connection in staging is over a ssh connection which might be down when I first go to the page. This is absolutely fatal.
Thanks
Andy

**Comment by richtera** [comment]
Also.... if the "installer" gave the option to either use an existing database or erase it, this problem could be solved in an alternate way.

**Comment by richtera** [comment]
Come to think of it, as well. I don't want the installer to come up in production if the database happens to be down. It would allow random people to mess around with my config file.

**Comment by dbhurley** [comment]
I like your second thought. That's a good suggestion to choose a database as an alternative.

**Comment by richtera** [comment]
Would it be possible to make "installed" a flag inside of config.php instead of just determining it by the database connection? Then a failed database connection would just be considered and error showing an error page. To get back to install mode the user would need to manually change the local.php file or remove the file altogether. I have not played with Symphony enough to make a pull request at this time, but I'll see if I can in the future.

**Comment by alanhartless** [comment]
Very, very good point. We can definitely add a flag to the config file to determine installation and throw a fail message is unable to connect to the db.

**Comment by alanhartless** [comment]
Fixed with 1.0
