### ISSUE TITLE
REST webhook subscription

### ISSUE THREAD

**Issue by zapur1** [mautic/mautic#1591]
Hi,

This is mainly to get the Zapier integration as a global integration and easily available to all.

Currently webhooks must be setup manually, here is proposed a method of setting up/subscribing to events https://zapier.com/developer/documentation/v2/rest-hooks/

If the Mautic API side, which simply receives a POST request with the necessary data, I can setup the Zapier side. I currently don't have the time to do it all so this is me reaching out to anyone who thinks that they might be able to get it sorted

**Comment by vexersa** [comment]
+1

**Comment by obay** [comment]
+1

**Comment by CarlVanderLaan** [comment]
+10
