### ISSUE TITLE
Small security issues in v1.3.1

### ISSUE THREAD

**Issue by Moongazer** [mautic/mautic#1600]
## Description
First of all: thank you all for this awesome piece of software, it looks optical and technical very well done!

I just made an update from v1.2.4 to 1.3.1 and found some smaller issues:

1) It would be great to clear the `app/cache/` folder after updating Mautic. Otherwise an exception is thrown after re-login which prevent the login (unfortunately I didn't saved the message to write it down here, but it was something with PHP require()). I've seen a `prod` and a `prod_` folder inside the cache after the update, so my guess was that the underscore folder was created because the otherone existed before and this leed to confusion. After deleting both, everything works fine again.

2) We have one user-role called viewer, where ONLY view permissions are set on all modules (It has all view permissions set which exists in Mautic, nothing else). If I login as user with this role, I've no permissions to create/edit/delete, except:

- Leads => Manage Leads: I can still use the functions "Batch edit the selected leads' lists", "Batch edit the selected leads' campaigns" and "Set selected leads as Do Not Contact" (Maybe that is fine and not an issue? I dont know which permissions you need for this actions)

- Leads => Manage Lists: I can create new Smart-List, which saves successful! (Without "create" permissions!?)

- Emails => Select an Email Template: The "Clone" button is visible, but the click results in "Apparently you don't have access to this area." which is fine (So, hide the button)

**Comment by escopecz** [comment]
The cache issue should be solved by now. I'll take a look at the permission issues.
