### ISSUE TITLE
Import fails to assign unsubscribe/donotemail

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1601]
I have imported a file with the fields

Email,Do Not Email
adfsadf@gluetools.com,TRUE
asdfasdfs@huaweisymantec.com,TRUE
asdfasf@mwmg.com,TRUE
asdfasdf.oishi@netgear.com,TRUE
afsdf@commandsoft.com,TRUE
aziz.asd@postmoderngroup.com,TRUE

It fails to assign the unsubscribe to the user. Not sure what is causing this.

**Comment by ldrrp** [comment]
i have also tried

Email,Do Not Email
adfsadf@gluetools.com,1
asdfasdfs@huaweisymantec.com,1
asdfasf@mwmg.com,1
asdfasdf.oishi@netgear.com,1
afsdf@commandsoft.com,1
aziz.asd@postmoderngroup.com,1

I looked at the code and the filter validate seems to be working used to parse my string.

**Comment by escopecz** [comment]
Please test https://github.com/mautic/mautic/pull/1627 and comment on it how the test went. Thanks for the bug report!

**Comment by ldrrp** [comment]
Im sorry I did not realize you wanted me to test it. I was under the impression you were asking those in #1627

**Comment by ldrrp** [comment]
Tested and working now.
