### ISSUE TITLE
List Filter fails to remove leads when there are both 'include' and 'exclude' tags

### ISSUE THREAD

**Issue by justinroffmarsh** [mautic/mautic#1605]
I have a list and leads are supposed to be added and subtracted according to two expressions.

1. Tags INCLUDING "Subscribed"
AND
2. Tags EXCLUDING "Subscription Ended"

Leads are added to this list when they have the "Subscribed" tag but they are not removed when they also have the "Subscription Ended" tag, even though the relationship between the two expressions is AND

**Comment by alanhartless** [comment]
I tried this just now in Mautic 2.1.1 and it worked. Could you please try in the latest version of Mautic and reopen this if you continue to encounter the issue?

Thanks!
