### ISSUE TITLE
View email in browser

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1610]
Feature to add.

"Unable to view this email, Click here to view it in your browser."

**Comment by kuzmany** [comment]
Use {webview_url}

**Comment by ldrrp** [comment]
Is there a giant list of all of these somewhere.

**Comment by escopecz** [comment]
Right now only in the Email Builder (the Builder is visible when you select an email theme). The tokens are dynamic (for example every lead list has one, every page, asset, form has one) so the list is different for each Mautic instance.

**Comment by ldrrp** [comment]
For those looking for a list other than waiting on type. Here is a general list.


![image](https://cloud.githubusercontent.com/assets/985837/14675711/50db8b18-06d8-11e6-8db9-d2bc3804482d.png)

**Comment by escopecz** [comment]
@ldrrp Thanks! That's awesome that you prepared it. Could you also publish it in a text format? It'd make the copy-paste workflow easier.

**Comment by ldrrp** [comment]
Sorry about that, yea copy and paste from a spreadsheet makes an image haha
