### ISSUE TITLE
Chinese Language

### ISSUE THREAD

**Issue by dannyec** [mautic/mautic#1611]
## Description

In language settings, there are two same chinese languages (chinese simplified and chinese mandarin) both of them are the same. 
- In China we always use Chinese Simplified [zh-Hans]
- In Taiwan / HongKong always use Chinese Traditional [zh-Hant]

## Steps to reproduce

1. Configuration
2. Language

<img width="430" alt="screen shot 2016-04-19 at 10 48 19 am" src="https://cloud.githubusercontent.com/assets/13312135/14626400/9e42ff96-061d-11e6-9db1-0822d017c4c7.png">

## How to fix

- In Mautic Core Language, remove "Chinese Mandarin"
- In Mautic Core Language, add "Chinese Traditional"

**Comment by escopecz** [comment]
Thanks for the report! I removed the Chinese - Mandarin from Transifex. A script should update the list of available languages over night and Mandarin option should disappear.

There is Chinese (Taivan) in the Mautic languages at Transifex already created so there is no need to create a new one I hope.

Take a look at:

https://www.transifex.com/mautic/mautic/

**Comment by dannyec** [comment]
Sorry for post again, but the languages "Chinese Mandarin and Chinese Simplified" still there together.

**Comment by alanhartless** [comment]
@escopecz Looks like if we delete from Transifex, it doesn't auto delete from the list of stored languages in our db. I've done that now - after deleting app/cache/prod, app/cache/languageList.txt and translations/cmn (if it exists), it's now gone from my lists.

**Comment by dannyec** [comment]
Thanks, now is fixed this problem 👍
