### ISSUE TITLE
Smart List filter: url visited

### ISSUE THREAD

**Issue by jjroelofs** [mautic/mautic#1612]
## Description

https://github.com/mautic/mautic/issues/1198 is a similar request but I thought it was too broad to be an actionable issue.

I just want to create smart lists based on visited urls. This should be easy to implement in comparison to the request in the other thread to completely match existing (expensive) marketing automation software.

I know you can use tags but the power of having urls at your disposal here is that you can analyze data and take action on existing patterns immediately. It's much more user friendly to analyze google analytics, notice that the combination "Pricing page"+"About us page" correlates high with subscription, and then immediately be able to craft a targeted email to existing leads who match this pattern.

Using tags would also require custom programming, which means marketing staff has to go through IT in order to create a new smart list and then have to wait for the list to fill. Not a great user experience.

similar requests in mautic community:
https://www.mautic.org/community/index.php/3211-how-can-i-create-a-list-with-people-visited-a-url

**Comment by npracht** [comment]
Hi,

Does this PR answers to your issue ?
https://github.com/mautic/mautic/pull/1567

N.

**Comment by jjroelofs** [comment]
Look good, do you have a set date for 1.4 to ship?
Is there a delay between shipping on m.o. and m.com?

Jurriaan
