### ISSUE TITLE
Mixing list - Important issue

### ISSUE THREAD

**Issue by vihuarar** [mautic/mautic#1617]
I dont know why my list are mixing up... 

I'm having the following issues...
1. List are decreasing the leads they had... for example, if I send an email to a list that has 1200 mails.... and after 5 hours I send another mails to the same list... in the email list shows that there is 1900 pending mails...
So the list are decreasing...  misteriously... (I checked if the users opted out, or unsuscribed from the list) 

2. Some mails are added automaticaly in the bounces list... but I have not configured the "Monitored Inbox Settings" so i dont know how Mautic is adding mails to the bounced list...
Mautic is adding emails mails that doesnt bounced to the bounced list... 

3. Today I checked a list that I created with 5 leads... and now they have more than 10 contacts...
Its like the system imported them in a wrong way... and added to a wrong list... or I dont know what happend

This is important, because my list are mixing up... and I dont want that my leads appers where they should not appear..

thanks!

**Comment by escopecz** [comment]
I hope you find out what is causing it because I cannot replicate it and never heard of such complain.

**Comment by vihuarar** [comment]
I already find what was the problem...
i previously found a table: email_donotemail which stores the leads that dont want to be contact, the unsubscribed or bounced...

I was using that table to set the BOUNCED attribute to 0... so the row was like:
![email_donotemail](https://cloud.githubusercontent.com/assets/1976384/14691560/8033b496-0717-11e6-9eaa-b2386a83bed7.png)

All three atributes: (contact, the unsubscribed or bounced...) was on 0 on that contact... but mautic still thought that the mails shouldn't be send it to that contact....

I solved the issue deleting the rows or registers in email_dontemail that has those atributes ((contact, the unsubscribed or bounced...) in 0.... and the problem solved....

My suggestion is that mautic should send emails to the register that has (contact, the unsubscribed or bounced...) in 0.... because when those atributes are in 0, they mean that the lead should be contact

**Comment by escopecz** [comment]
Do you know how it could happen? I can think of a scenario where the lead unsubscribes and then resubscribes again. Is this the case? We have to figure out how to test this issue.

**Comment by vihuarar** [comment]
My main problem is:
"Some mails are added automaticaly in the bounces list... but I have not configured the "Monitored Inbox Settings" so i dont know how Mautic is adding mails to the bounced list...
Mautic is adding emails mails that doesnt bounced to the bounced list..."

I dont know why contacts are marked as bounced.. I I have no configured "Monitored inbox"... its like randomly some leads are marked as "bounced"

Because bounced...  in email_donotcontact are not real bounced.... I have to set "bounced=0" via mysql... because I cant find how to do it masively (more than 1 lead at the same time)
(How change the bounced status to more than 1 lead, at the same time?) I cant figure out via the official documentation...

**Comment by escopecz** [comment]
I don't think you can manage bounces from Mautic administration. Leads should manage it from email links. But bounce can be also if the email is not valid for example. Check the bounced leads. There should be a note about why the lead is marked as bounced when you hover over the bounced tag.
