### ISSUE TITLE
Feature Request: CARDDAV Integration

### ISSUE THREAD

**Issue by skillz-xx** [mautic/mautic#1618]
Hello!

It would be great if contacts synchrinization via CARDDAV protocol could be implemented into Mautic!

Any plans on that yet?

thx

**Comment by n1trux** [comment]
Why was this closed? I'd also like to synchronise Mautic contacts with CardDAV contacts.

Given that nowadays many applications support CardDAV (Thunderbird, Nextcloud, Baikal, …) it'd be a logical step to integrate Mautic via that protocol.

**Comment by Braintelligence** [comment]
I'm also interested in this feature.

**Comment by Braintelligence** [comment]
Please elaborate on why this issue was closed.

**Comment by npracht** [comment]
Hello @Braintelligence !
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.

**Comment by Braintelligence** [comment]
I see, thanks for clearing this up. Was this discussed in Slack already? If yes, could you provide a link to the thread?
