### ISSUE TITLE
Mandrill failed to authenticate

### ISSUE THREAD

**Issue by sbrendtro** [mautic/mautic#1625]
## Description
When using Mandrill as the mail transport, if the "password" is incorrect, Mautic will throw the error "Mandrill failed to authenticate".  This is generated from app/bundles/EmailBundle/Swiftmailer/Transport/MandrillTransport.php (around line 290).  It seems that the response coming back from Mandrill's API is not the expected 'PONG', but rather an array containing the error message and code.  In my case, $response was an array:

array (   'status' => 'error',   'code' => -1,   'name' => 'Invalid_Key',   'message' => 'Invalid API key', )". Log data: !! Mandrill failed to authenticate.  Response was "array (   'status' => 'error',   'code' => -1,   'name' => 'Invalid_Key',   'message' => 'Invalid API key', )

FIX #1:  The MandrillTransport class should catch the error and pass that message to the logs for more clarity.

FIX #2:  The "password" field is not really a password at all, but is supposed to be a valid API Key created within the Mandrill account.  In my case, this misunderstanding is what had me enter an incorrect "password" in the first place.  The developers might consider relabeling "password" to "API Key" on the admin configuration page.

## Steps to reproduce
1.  Set Mandrill as the transport
2.  Set the username and an invalid "password" (anything that is not a valid API key)
3.  Use the configuration page's "Test Connection", or just try to send an email to a lead.
4.  Check log file.

**Comment by alanhartless** [comment]
Fixed in #2284
