### ISSUE TITLE
[Feature] option to add tags as well as points

### ISSUE THREAD

**Issue by MaxOnTheHill** [mautic/mautic#163]
all well and good adding points to a lead on trigger, but wondering if you have considered adding tags to leads on triggers/actions - would really enhance targeting  :)

**Comment by argentin** [comment]
I need this feature too.

**Comment by MaxOnTheHill** [comment]
ref discussion: https://mautic.slack.com/archives/general/p1426717691000346
... something to help target and filter leads against personas and profiles.

**Comment by argentin** [comment]
Like Ontraport: http://support.ontraport.com/entries/23528488-Contact-Tags.
Critical feature for Lead Magnets segmentation: http://blog.videofruit.com/how-to-build-upgrades/

**Comment by pitus** [comment]
+1 and make sure tags can also be removed on trigger, not just added

**Comment by alanhartless** [comment]
Tags was added in 1.2. Yay!
