### ISSUE TITLE
Feature request - Ability to run imports in the background/CLI

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1642]
| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? | Y |
## Description:

There should be a check box somewhere in the import process that will queue it in the background and email you when its done. Some very large lists seem too take forever and lockup the system. Im talking about email lists above 20k

**Comment by ldrrp** [comment]
I just noticed issue may be browser related too on the lockup, it says "waiting for available socket connection" if i try and do something in a diff tab while its running.

**Comment by MaxWebmecanik** [comment]
Would love to see something like that as well!
