### ISSUE TITLE
Bug - Tab page on Landing page forms list

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1649]
## Description
When you try to switch the page results of your forms on the landing page editor. If you try to click on the **next page button** or the **last page button** or **page 2 button**,
---> **it does not work.**

![landing_page_bug](https://cloud.githubusercontent.com/assets/14075239/14878841/598b7c56-0d26-11e6-9fba-0a2d4d6b64f8.png)

## Steps to reproduce

1. Create more than 5 forms
2. Create a landing page
3. Open the landing page builder
4. Click on one of the next button of the forms list

**Notice that it's not responding.**

**Comment by mqueme** [comment]
This has been removed in the new version.
