### ISSUE TITLE
Feature request - Lead qualify twice in a single campaign

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1650]
## Description

It would be great to have an option to enable to **qualify twice a lead in a campaign**.
1. For instance, you have a **birthday lead list**
2. You may have a promotional email when it's your birthday
3. It would qualify the lead to the lead list every year
4. Add the lead to a specific campaign

Your opinion ?

**Comment by Skrypton** [comment]
This one is similar to https://github.com/mautic/mautic/issues/1606.

**Comment by npracht** [comment]
Closing in favor of https://github.com/mautic/mautic/issues/1606
