### ISSUE TITLE
Feature request - Add point action for an email click

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1653]
## Description

It would be great to be able to score (add point to a lead) for an **`email click` in the point actions**.
Same configuration as `email open`.

![capture d ecran 2016-04-28 a 13 56 34](https://cloud.githubusercontent.com/assets/14075239/14885003/1577b854-0d49-11e6-95a3-e10fbfb0c786.png)
![capture d ecran 2016-04-28 a 13 56 45](https://cloud.githubusercontent.com/assets/14075239/14885002/1577b192-0d49-11e6-99dd-1dab30908ca8.png)

**Comment by bloodlynx** [comment]
+1 It would be a nice option for decisions in the campaign builder as well.

**Comment by sahidjeurissen** [comment]
+1

**Comment by gokhanerdogdu** [comment]
This is a standard function in every marketing automation tool. It should be in Mautic also.

**Comment by zora-li** [comment]
+1 It would help a lot!

**Comment by iannate** [comment]
+1 - Really would like this!
