### ISSUE TITLE
Recurring Point Action

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1654]
## Description

It would be great that a **lead can be scored more than once** by a `Point Action`.
## Example

I'd like my leads take points each download or each email open. Then I can **distinguish better a lead that opens all my emails vs. a lead that opened one of my email**.
## Suggestion

Add a enable/disable button for Point Actions

![capture d ecran 2016-04-28 a 14 00 59](https://cloud.githubusercontent.com/assets/14075239/14885433/a17bbbb4-0d4b-11e6-87de-9391e54c23b2.png)

**Comment by npracht** [comment]
Hi,
I think it's a duplicate of https://github.com/mautic/mautic/issues/929. I don't know which one you prefer to keep depending on the quality of the Feature Request Description.

N.

**Comment by npracht** [comment]
@escopecz there is a duplicate with #929, i let you see the best brief to keep.

**Comment by escopecz** [comment]
I'll leave the older one. Thanks for finding it and pointing it out!
