### ISSUE TITLE
Multiple race conditions and stale data usage in ModeratedCommand.php

### ISSUE THREAD

**Issue by ioncube** [mautic/mautic#1664]
## `script_executions.json` is not guarded against concurrent writes leading to stuck processing

The lack of a lock on updates to `script_executions.json` and the writing of potentially stale `executionTimes` data in `completeRun()` means that tasks may get stuck, with this almost guaranteed if the start or end point of cron tasks are coincident. The documented advice of not running multiple cron tasks at the same time will make a collision less likely but does guarantee avoidance, and the chance of a user selecting cron schedules that _do_ cause tasks to collide at least on occasion is high. 

## Steps to reproduce

Set tasks to start every minute.

I've not had time to make a pull request yet but due to the severity of the issue I'm not holding back on sharing a minimal solution. This also better tidies up the json, but I'd be inclined to evolve this slightly to store some post-run information as per the code comments. Passing the output stream to `completeRun()` for completeness also gives the opportunity for error reporting. Unless used elsewhere, `executionTimes` no longer needs to be a member variable so I'd be inclined to improve that.

Hope this is useful.

    protected function checkRunStatus(InputInterface $input, OutputInterface $output, $key)
    {
        $force     = $input->getOption('force');
        $timeout   = $this->getContainer()->hasParameter('mautic.command_timeout') ?
            $this->getContainer()->getParameter('mautic.command_timeout') : 1800;

        $checkFile = $this->checkfile = $this->getContainer()->getParameter('kernel.cache_dir').'/../script_executions.json';
        $command   = $this->getName();
        $this->key = $key;

        $fp = fopen($checkFile, 'c+');

        if (!flock($fp, LOCK_EX)) {
            $output->writeln("<error>checkRunStatus() - flock failed on {$checkFile} - taking our chances like we used to.</error>");
        }

        $this->executionTimes = json_decode(fgets($fp, 8192), true);
        if (!is_array($this->executionTimes)) {
            $this->executionTimes = array();
        }

        if ($force || empty($this->executionTimes['in_progress'][$command][$key])) {
            // Just started
            $this->executionTimes['in_progress'][$command][$key] = time();
        } else {
            // In progress
            $check = $this->executionTimes['in_progress'][$command][$key];

            if ($check + $timeout <= time()) {
                $this->executionTimes['in_progress'][$command][$key] = time();
            } else {
                $output->writeln('<error>Script in progress. Use -f or --force to force execution.</error>');

                flock($fp, LOCK_UN);
                fclose($fp);

                return false;
            }
        }

        ftruncate($fp, 0);
        rewind($fp);

        fputs($fp, json_encode($this->executionTimes));
        fflush($fp);

        flock($fp, LOCK_UN);
        fclose($fp);

        return true;
    }

    protected function completeRun($output = null)
    {
        $fp = fopen($this->checkfile, 'c+');

        flock($fp, LOCK_EX);

        $this->executionTimes = json_decode(fgets($fp, 8192), true);
        if (!is_array($this->executionTimes)) {
            if ($output) {
                $output->writeln('<error>completeRun() - We should have read an array of times</error>');
            }
        }
        else
        {
            // Our task has ended so remove the start time
            unset($this->executionTimes['in_progress'][$this->getName()][$this->key]);

            // If there's no other info stored for our task then we remove our task
            // key too, though storing the last time that we ran and how long it took
            // might be useful for audit / debugging purposes.
            if (empty($this->executionTimes['in_progress'][$this->getName()])) {
                unset($this->executionTimes['in_progress'][$this->getName()]);
            }

            ftruncate($fp, 0);
            rewind($fp);

            fputs($fp, json_encode($this->executionTimes));
            fflush($fp);
        }

        flock($fp, LOCK_UN);
        fclose($fp);
    }

**Comment by jkuchar** [comment]
Have you been modifying `app/bundles/CoreBundle/Command/ModeratedCommand.php`?

**Comment by jkuchar** [comment]
This perfectly fixed also my instance. (I was running cron jobs every minute too)

**Comment by ioncube** [comment]
Yes `app/bundles/CoreBundle/Command/ModeratedCommand.php`. I'm glad this worked for you. The changes ought to do more error logging but it should be solid as a start.

**Comment by jkuchar** [comment]
May it can be useful to use nette/safe-stream which implements optimistic file locking as php file protocol. https://doc.nette.org/en/2.3/atomicity

**Comment by nickion** [comment]
Possibly but would seem to be overkill. The exclusive file locks in PHP work on platforms including windows and are easy to understand. It doesn't need to be complicated but was just a little too under-complicated before :)  For consistency and I'd have been tempted to have a DB table of active jobs and store the information there with a SELECT FOR UPDATE as the test and set. Being in the DB would make it easy to then have a page showing active jobs if desired, but as the file method works and in the spirit of avoiding unnecessary changes and the bugs that can result, this could be considered as a change that could be made but held off until _actually_ needed and beneficial. As an aside, I want to add that the devs have done a great job so far on Mautic. Was exciting to discover the project.

**Comment by maxitromer** [comment]
I'm writing just to confirm that the solution proposed by @ioncube works perfect for me. I'm running a 1.3.1 version. Thanks.

**Comment by alanhartless** [comment]
A database driven "worker queue" with a "one cron job to rule them all" is something we'd love to see in Mautic and something that will eventually come to to fruition (any takers? :-) ).

Would love to see this in a PR so we can merge it into a release :-)

Thanks!

**Comment by wittwerch** [comment]
We tested the fix on our 1.3.1 test installation and we were not able to spot the problem again!

**Comment by PatchRanger** [comment]
I confirm that the problem persists in 1.4.1 and the proposed solution fixes it.

**Comment by maxitromer** [comment]
I fix this bug manually with the @ioncube solution and works perfect but when I update to 1.4.0 the fix was overwriten and the bug comesback again.

Please someone can make a pull request?

Thanks.

**Comment by jkuchar** [comment]
I propose 
- [ ] to fix this ASAP - this is blocker level -> you cannot use Mautic instance
- [ ] and later sometimes there can be done implementation of database driver workers. (btw. didn't you think about RabbitMQ?)

**Comment by nickion** [comment]
Thanks for merging the patch. I did notice that it's not quite as in the original and will give notice level warnings with `$output` being undefined. I added a line level comment in the code.

**Comment by PatchRanger** [comment]
@nickion Sorry, I didn't notice changing signature of the function. I mean, in your implementation `completeRun` accepts optional parameter and I didn't include it into the PR.
