### ISSUE TITLE
"No email with an id of 0 was found!"

### ISSUE THREAD

**Issue by ioncube** [mautic/mautic#1665]
## Description

Clicking an event in the calendar corresponding to a sent custom email appears to give an error.

## Steps to reproduce

Click "Manage Leads"
Select "Send email" from the dropdown for a lead.
Compose and send the email.

Click "Calendar"
The sending time and string "sent 1 times" (sic) should be visible for the day the email was sent.

Click the "sent 1 times" string.

**Comment by dongilbert** [comment]
Fixed by #1669
