### ISSUE TITLE
Javascript error "response is not defined"

### ISSUE THREAD

**Issue by ioncube** [mautic/mautic#1666]
## Description

If the chrome popup blocker blocks the creating new email dialog, a JS error occurs.
 
## Steps to reproduce

Ensure that the chrome popup blocker will block popups
Launch the campaign builder
Click "Send email"
Click "New email"
The loading spinner will remain indefinitely.

The debugger view is as follows:

![mautic-newemail-error](https://cloud.githubusercontent.com/assets/1902741/14943435/3b807466-0fd1-11e6-9816-41445b7d728a.png)

**Comment by alanhartless** [comment]
Fixed in #2326. Thanks!
