### ISSUE TITLE
Sorting leads by name gives incorrect results

### ISSUE THREAD

**Issue by ioncube** [mautic/mautic#1670]
## Description

Sorting several lead names in ascending order gave the following incorrect result: Bill, Fred, Nick, Nick, Mary instead of the expected order Bill, Fred, Mary, Nick, Nick. Sorting descending reversed and was therefore also incorrect. 

![mautic-lead-sorting-issue](https://cloud.githubusercontent.com/assets/1902741/14954040/d5e27ece-1066-11e6-9aa9-0c814f6cee53.PNG)

## Steps to reproduce

Leads with associated ID's are as follows. They all have only a first name. Nick/1, Mary/3, Bill/4, Nick/5, Fred/6.

**Comment by dbhurley** [comment]
Appears to be fixed in 2.0.1
