### ISSUE TITLE
Feature request - Cache stats on emails table

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1671]
| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
This page takes some time to load with 20 or more emails with thousands of leads in a database. About 5-10 seconds sometimes.

Perhaps some way to cache the stats so they are not loaded every refresh or load them on ajax separately after the page has loaded.

**Comment by ldrrp** [comment]
![image](https://cloud.githubusercontent.com/assets/985837/15119183/b170d01e-15dd-11e6-9afe-2466c3fe90fa.png)

**Comment by ldrrp** [comment]
Takes exactly 9.5 seconds to load. My team of 15-20 employees are really getting frustrated with this issue in particular. Ive upgrade the ram and cpu on the server to help it, but it did not make a difference.

![image](https://cloud.githubusercontent.com/assets/985837/16489112/efb00fce-3ea1-11e6-8d38-667de6e89585.png)

**Comment by ldrrp** [comment]
I honestly think this should be pushed for a 2.0.0 milestone. This is a huge performance issue.

**Comment by wittwerch** [comment]
We are experiencing the same performance degradation on a large instance. Specially one query takes more than 7s and resulted in a full table scan according to the MySQL slow log.

```
# Query_time: 7.305457  Lock_time: 0.000076 Rows_sent: 1  Rows_examined: 315668
SET timestamp=1471359567;
SELECT count(l.id) as count FROM leads l WHERE (NOT EXISTS (SELECT null FROM email_donotemail dne WHERE dne.lead_id = l.id)) AND (NOT EXISTS (SELECT null FROM email_stats stat WHERE (stat.lead_id = l.id) AND (stat.email_id IN (18, 22, 17)))) AND (EXISTS (SELECT null FROM lead_lists_leads ll WHERE (ll.leadlist_id IN (5, 14)) AND (ll.lead_id = l.id) AND (ll.manually_removed = 0))) AND ((l.email IS NOT NULL) AND (l.email <> ''));
``` 

I managed to optimise the query with a multiple-column index.

```
CREATE INDEX mailstats on email_stats (lead_id, email_id);
```

That brought the query time down to 0.34s and the performance in the web frontend improved. But honestly I'm not sure whether adding additional indexes is really the way to go..

**Comment by ldrrp** [comment]
Thanks for the index suggestion. I dont think its a permanent solution either, but at least itll get the other employees off my ....

**Comment by escopecz** [comment]
@wittwerch @ldrrp I wanted to create a PR with the index you suggested and found out that it already exist in the entity:

https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/Entity/Stat.php#L136

And also in migration:

https://github.com/mautic/mautic/blob/e0144b44a2380179acd93e122d83b80ee4f14534/app/migrations/Version20150829000000.php#L70

which is over a year old. Strange you didn't have it in your database applied already.

**Comment by wittwerch** [comment]
@escopecz The index is there, did not realise that. Anyway, the index is not used for that particular query.
I think it is the order of the columns that matters.

````
$this->addSql('CREATE INDEX ' . $this->prefix . 'stat_email_search ON ' . $this->prefix . 'email_stats (email_id, lead_id)');
````

`````
CREATE INDEX mailstats on email_stats (lead_id, email_id);
`````

**Comment by ldrrp** [comment]
I did have a failed upgrade once, My setup could be a little wonky. I will be exporting my data into a new database schema today just in case from a fresh install.

**Comment by PatchRanger** [comment]
@escopecz I've checked it, @wittwerch is right: the order does matter. I've added index

```
CREATE INDEX stat_email_search2 on email_stats (lead_id, email_id);
```
\- and it reduced the query time from 4 to 0.7 sec.

**Comment by escopecz** [comment]
Thanks guys! @alanhartless has concerns to modify the large tables because it takes a while and it is the reason why some Mautic updates fails. Alan, do you think we can add this index?

**Comment by ldrrp** [comment]
Is there a way to tell the user in the update process to manually run this query, Piwik does that sometimes for large changes that will crash an update.

**Comment by alanhartless** [comment]
I do cringe when I see something needing to be changed on these large tables because people tend to use the UI upgrader which will completely fail for large tables due to web request time limits. Mysql can take minutes and we even saw with 2.1, an hour for some instances with millions of page_hits because of the way mysql  handles adjusting table column schema. Indexes tend to not take as long but can still take minutes (more than most web requests allow) as Mysql populates the index. 

But on the flip side - we can't just ignore it if there's something that addresses performance that significantly. This is why I tend to push the CLI upgrade process.

@ldrrp on your manual query idea - usually that's not possible with Doctrine while keeping the instance up and running. If Doctrine finds a mismatch between schema columns and the entity definitions - it'll throw an exception. For indexes it doesn't matter so much but it's for this very reason we have the CLI upgrade processes in place.
