### ISSUE TITLE
webview_text not getting translated to email language

### ISSUE THREAD

**Issue by ayrad** [mautic/mautic#1673]
## Description

When using token {webview_text} on any template email, the text "Having trouble reading this email? Click here." is translated to Mautic language instead of Email language

IMO, this doesn't make sence... Because email language could be different from Mautic language

Let's imagine that I am Spanish, then I choose "Spanish" language in Mautic but I want to send an email to my German customers... The {webview_text) is translated to Spanish even if I choose German as Email language:

![email_language](https://cloud.githubusercontent.com/assets/10789928/14958496/55f9802a-108b-11e6-8e23-bb8f26605b25.JPG)
## Steps to reproduce
- Create an Email with token {webview_text} in content and choose any language different from the one you're working with in Mautic
- Send that email to someone
- Received email is translated to your Mautic language and not the language you've chosen when creating the Email

**Comment by escopecz** [comment]
The webview message can be modified in the configuration:
![mautic-webview-message](https://cloud.githubusercontent.com/assets/1235442/17736184/a91456aa-6486-11e6-9c1f-7b6d1cbb8f58.png)

To automatically translate the message to some language, you'd have to download all languages you use this feature and we'd also have to remove the option to customize the message form configuration. As it would require quite a lot of change and it would change the way it works now, I'll mark this as a feature request.
