### ISSUE TITLE
Reading an email for one lead shows as activity on a different lead - Update with an initial analysis.

### ISSUE THREAD

**Issue by ioncube** [mautic/mautic#1675]
## Description

I'm repeatedly seeing reading of an email sent to one lead showing as activity for a different lead. The web logs show a single access to the expected tracking pixel for the corresponding email and SQL logs show retrieving the expected lead ID, but this is followed by selects and an update to a different lead ID. Reading emails for other users similarly updates the incorrect lead. 

The SQL log:

`160502 17:49:25  6472 Connect   @localhost as anonymous on mautic`
`6472 Query     SELECT e0_.id AS id0,
e0_.email_address AS email_address1, e0_.date_sent AS date_sent2,
e0_.is_read AS is_read3, e0_.is_failed AS is_failed4,
e0_.viewed_in_browser AS viewed_in_browser5, e0_.date_read AS
date_read6, e0_.tracking_hash AS tracking_hash7, e0_.retry_count AS
retry_count8, e0_.source AS source9, e0_.source_id AS source_id10,
e0_.tokens AS tokens11, e0_.copy AS copy12, e0_.open_count AS
open_count13, e0_.last_opened AS last_opened14, e0_.open_details AS
open_details15, e0_.email_id AS email_id16, e0_.lead_id AS lead_id17,
e0_.list_id AS list_id18, e0_.ip_id AS ip_id19, e0_.copy_id AS
copy_id20 FROM email_stats e0_ LEFT JOIN leads l1_ ON e0_.lead_id =
l1_.id LEFT JOIN emails e2_ ON e0_.email_id = e2_.id WHERE
e0_.tracking_hash = '57272162efab5'`

Partial result:

    id0: 6
    lead_id17: 6

After 3 other queries we have the following with a join on leads where id is 4:

`SELECT l0_.is_published AS
is_published0, l0_.date_added AS date_added1, l0_.created_by AS
created_by2, l0_.created_by_user AS created_by_user3,
l0_.date_modified AS date_modified4, l0_.modified_by AS modified_by5,
l0_.modified_by_user AS modified_by_user6, l0_.checked_out AS
checked_out7, l0_.checked_out_by AS checked_out_by8,
l0_.checked_out_by_user AS checked_out_by_user9, l0_.id AS id10,
l0_.points AS points11, l0_.last_active AS last_active12, l0_.internal
AS internal13, l0_.social_cache AS social_cache14, l0_.date_identified
AS date_identified15, l0_.preferred_profile_image AS
preferred_profile_image16, i1_.id AS id17, i1_.ip_address AS
ip_address18, i1_.ip_details AS ip_details19, u2_.is_published AS
is_published20, u2_.date_added AS date_added21, u2_.created_by AS
created_by22, u2_.created_by_user AS created_by_user23,
u2_.date_modified AS date_modified24, u2_.modified_by AS
modified_by25, u2_.modified_by_user AS modified_by_user26,
u2_.checked_out AS checked_out27, u2_.checked_out_by AS
checked_out_by28, u2_.checked_out_by_user AS checked_out_by_user29,
u2_.id AS id30, u2_.username AS username31, u2_.password AS
password32, u2_.first_name AS first_name33, u2_.last_name AS
last_name34, u2_.email AS email35, u2_.position AS position36,
u2_.timezone AS timezone37, u2_.locale AS locale38, u2_.last_login AS
last_login39, u2_.last_active AS last_active40, u2_.online_status AS
online_status41, u2_.preferences AS preferences42, u2_.signature AS
signature43, l0_.owner_id AS owner_id44, u2_.role_id AS role_id45 FROM
leads l0_ LEFT JOIN lead_ips_xref l3_ ON l0_.id = l3_.lead_id LEFT
JOIN ip_addresses i1_ ON i1_.id = l3_.ip_id LEFT JOIN users u2_ ON
l0_.owner_id = u2_.id WHERE l0_.id = '4'`

and then:

`SELECT p0_.id AS id0, p0_.points AS
points1, p0_.color AS color2 FROM point_triggers p0_ WHERE
p0_.is_published = 1 AND (p0_.publish_up IS NULL OR p0_.publish_up <=
'2016-05-02 17:49:25') AND (p0_.publish_down IS NULL OR
p0_.publish_down >= '2016-05-02 17:49:25') ORDER BY p0_.points ASC`
`SELECT f.id, f.label, f.alias, f.type,
f.field_group as "group", f.field_order FROM lead_fields f WHERE
f.is_published = 1 ORDER BY f.field_order asc`
`SELECT * FROM leads l WHERE l.id = '4'`
`UPDATE leads SET last_active =
'2016-05-02 17:49:25' WHERE id = '4'`

## Steps to reproduce

Simply reading emails updates the incorrect lead as active. This is a new setup where all id's for resources are low numbered. Perhaps the incorrect ID 4 is not the ID for a user but some other resource?

Leads table showing that ID 4 was updated at 17:49 though the email viewed was fred's
![mautic-lead-ids](https://cloud.githubusercontent.com/assets/1902741/14963698/d259973e-109c-11e6-9e05-677fbff6d93b.PNG)

[mautic-sql.txt](https://github.com/mautic/mautic/files/245719/mautic-sql.txt)

**Comment by ioncube** [comment]
This relates to a side effect of `getCurrentLead()` being to update the last active time, `getCurrentLead()` being called during `setCurrentlead()` before the current lead has been set, and `getCurrentLead()` having no current lead and falling back to retrieving the leadId from cookies. Another behaviour I'd observed of two leads sometimes being shown as active when viewing one email starts to make sense too.

My immediate suggestion as a starting point is that `getCurrentLead()` should not be changing state and updating the last active time of anything, and that this behaviour is removed first of all. Following that, add explicit updating of last activity if it is needed anywhere else other than in `setCurrentLead()`.

**Comment by ioncube** [comment]
Having looked further, while `getCurrentLead()` should not be updating activity,  `FormSubmitHelper.php` calls `getCurrentLead()` without a `setCurrentLead()`, so perhaps such a change would break updating leads by form submission. I tried wget on a tracking pixel to avoid a cookie, and that updated a different wrong lead. I suspect this was from falling back to trying to find a lead by IP and picking the wrong one. 

`getCurrentLead()` seems to try too hard to find a matching lead rather than just accepting that there isn't one yet, and `setCurrentLead()` may not be called sufficiently.

I'd be inclined to have a simpler `getCurrentLead()` that requires `setCurrentLead()` to have been called, review to ensure that `setCurrentLead()` is called in all places where lead activity is explicitly identifiable by a tracking ID, and have a separate method to set a current lead by inference from cookie or IP.

My quick fix is to change `getCurrentLead` to:

`getCurrentLead($returnTracking = false, $updateLastActive = true)`

conditionally update the returned lead, and call with `false` during `setCurrentLead()`. This works and resolves, but I'm not fully confident that other places where `getCurrentLead()` is called will not update the wrong lead.

Hope this helps!

**Comment by alanhartless** [comment]
Just to verify this - is this happening when you're testing or seeing it across contacts not yourself? Asking because I just wanted to rule out that cookies in browser aren't casing this if you're reading the email in a web mail client while being tracked via cookie.

Some changes were made to get/set current lead in 2.1 - does this still happen?
