### ISSUE TITLE
Feature request - Possibility to send email example to someone else

### ISSUE THREAD

**Issue by ayrad** [mautic/mautic#1693]
## Current scenario
Now, when you want to show an example of email to someone else, you have to send the example to yourself and then forward or attach it on a new email and send it to that person

## Desired scenario
Add new button or change the behaviour of the current "Send example" button to allow user to select the desired destination lead/email (mainataining the no-pixel on examples policy)

**Comment by escopecz** [comment]
Thanks! Seems like duplicate of https://github.com/mautic/mautic/issues/1447 though.

**Comment by ayrad** [comment]
Ooops!
