### ISSUE TITLE
MailGun integration

### ISSUE THREAD

**Issue by Valentyn-Kubrak** [mautic/mautic#1694]
Hi team,
Do you have extension for MailGun integration? (https://mailgun.com)

**Comment by jeffbski** [comment]
+1

**Comment by storini** [comment]
+1

**Comment by lutek** [comment]
+1

**Comment by nelsontristao** [comment]
+1

**Comment by nelsontristao** [comment]
I'll try to add a pull request asap.

**Comment by ybombale** [comment]
+1

**Comment by staret** [comment]
+1

**Comment by afilp** [comment]
+1 Any news on this? Thanks!

**Comment by geochatz** [comment]
+1 Any news on this? Thanks!

**Comment by andrewvink** [comment]
+1 Would be awesome to have this

**Comment by mcneela86** [comment]
+1 This would be an awesome feature.

**Comment by vesper8** [comment]
This still isn't possible?

**Comment by brandner** [comment]
+1

**Comment by igisho** [comment]
+1

**Comment by igisho** [comment]
https://github.com/tehplague/swiftmailer-mailgun-bundle

**Comment by iwantaspeaker** [comment]
+1

**Comment by ericgcc** [comment]
+1

**Comment by calevans** [comment]
+1

**Comment by refschool** [comment]
Very wanted feature !

**Comment by vesper8** [comment]
any update on this? lots of us want some official mailgun plugin love!!

**Comment by iwantaspeaker** [comment]
Why has this issue been  closed. Is there an answer to the request. We still need a may to integrate Mautic and Mailgun.........

**Comment by mustafa-taheri** [comment]
We can use Mailgun by selecting the other SMTP option setting up the credentials and it's done.

**Comment by iwantaspeaker** [comment]
Yes we can, but what we cant do is get notifications of Bounces and Unsubscribes from Mailgun without a Webhook. Unless you know another way.

**Comment by therealkevinard** [comment]
Agreed: Other SMTP works great for sending, but bounce management is fairly critical. Is there (or could there be) a public webhook receiver on the mautic end for handling these posts?

**Comment by siccl** [comment]
+1

**Comment by directpromo** [comment]
+1 Very wanted feature!

**Comment by imihandstand** [comment]
Yes please, make Mailgun (especially API) possible

**Comment by jvitorr** [comment]
+1

**Comment by zlobec** [comment]
+1 validations

**Comment by rafagaseo** [comment]
+1

**Comment by Ennazk** [comment]
+1

**Comment by luigidon** [comment]
+1

**Comment by azamuddin** [comment]
+1

**Comment by azamuddin** [comment]
@here Hi, I finally managed to make mailgun plugin for mautic.
I have tested it in Mautic version 2.15.0 and it works perfectly.

You can test it yourself, and please give star if you like it.

https://github.com/azamuddin/mautic-mailgun-plugin

**Comment by travisaustin** [comment]
@azamuddin This is great, thank you!

I had to edit it to allow outbound mail on an alternate port (our AWS account blocks outbound port 25 by default). Otherwise, this is awesome.

**Comment by RafaelLVX** [comment]
> 
> 
> @here Hi, I finally managed to make mailgun plugin for mautic.
> I have tested it in Mautic version 2.15.0 and it works perfectly.
> 
> You can test it yourself, and please give star if you like it.
> 
> https://github.com/azamuddin/mautic-mailgun-plugin
 Working perfectly on 2.15.1, good job!

**Comment by mrwmartins** [comment]
hi guys, callback function does not work for manage bounce e-mails ... mautic 2.16 ... any tips ?

**Comment by dichvuhuuich** [comment]
Hope mailgun will in option to send email with mautic soon!
