### ISSUE TITLE
Discourse plugin

### ISSUE THREAD

**Issue by Mayeu** [mautic/mautic#1701]
Hello,

I have made a default install to fiddle with the features of Mautic, one of the things  that motivated me to test this tools was the presence of a discourse integration.

But by default I don't find any way to integrate with my Discourse instances. Did I overlooked something about this plugin?

Thank you for your help, and thank you for the great works!

**Comment by escopecz** [comment]
Hi, if you are talking about this list: https://www.mautic.org/integrations/ then the black&white plugins are planed, the full color plugins are implemented.

**Comment by Mayeu** [comment]
OK! Then I did not understand the page correctly :)

I'll do some manual/regular import in the mean time.

Related to that, where can I find the api details? (So I can automate the importation of the contacts). 

Thank you for your help.

**Comment by escopecz** [comment]
https://developer.mautic.org/

**Comment by Mayeu** [comment]
Thank you 👌

**Comment by blacksky86** [comment]
I would love to have Discourse be next, it's the best forum platform out there, IMO

**Comment by Mayeu** [comment]
Hello,
Has it be closed because it is now integrated? Or because it won't be?

**Comment by amagdy3** [comment]
Yes, I'm asking again. Is this planned sometime in the future?

**Comment by gpetrov** [comment]
Any plans @escopecz - Discourse is really popular now ...

**Comment by escopecz** [comment]
I don't have any need to build a Discourse plugin. I'm afraid that whoever wants it should initiate the development.
