### ISSUE TITLE
email Stats show incorrect data and urgent doubt

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#1703]
## Description

I have one email with these data:
![image](https://cloud.githubusercontent.com/assets/10166840/15108700/ac6a3994-15d7-11e6-98bf-0f2dcbd1fb71.png)  I only have 25.000 emails in the database. Previous mailing is sent to 6700 by the same campaign

Is one email in the horeca campaign that is send after 5 days.
![image](https://cloud.githubusercontent.com/assets/10166840/15108745/e3ebaee8-15d7-11e6-9be6-60d3fd7a9d0b.png)

The previous email (horeca1) sent correctly 
![image](https://cloud.githubusercontent.com/assets/10166840/15108764/0b6d4fe4-15d8-11e6-9321-746fd71f36c6.png)

But Horeca 3 is not sent I think just because by mandrill change of policies (but I has a paid plan in mandril.)
![image](https://cloud.githubusercontent.com/assets/10166840/15108902/e10e1778-15d8-11e6-9a92-c5d299a9d9c7.png) but not a mailchimp account
 

My problem is: if I change the sending system: what will happen with the pending emails... 

## Steps to reproduce

**Comment by miguelpascual** [comment]
Is not the only email that show incorrect data... all of campaings ended weeks ago show a extrange number of sendings 

![image](https://cloud.githubusercontent.com/assets/10166840/15152826/0ac1a59a-16d7-11e6-876c-a95c7778be32.png)

**Comment by miguelpascual** [comment]
it happend another time. 
The 27 of may a created a new step in the campaing. 
![image](https://cloud.githubusercontent.com/assets/10166840/15647125/02b79662-2662-11e6-83d8-794047ba20b3.png) (this capture is of the day I created the campaign)

to send the same email to a segment of global list (I use the same email to dont send twice to the same recipient even it are in some segments)

Today I see it envied the email before the date. 

![image](https://cloud.githubusercontent.com/assets/10166840/15647214/773e7672-2662-11e6-921f-5d7e1395cd26.png)

and some mails are sending now :S I don't understand why...

any idea?

**Comment by alanhartless** [comment]
Is this still happening in the latest version of Mautic? A lot has changed with email counts and processing.

**Comment by alanhartless** [comment]
Due to lack of feedback, we're closing this issue. Please upgrade to 2.1.1 and if the issue persist, definitely let us know! Thanks!
