### ISSUE TITLE
UX - Dropdown overflow hidden

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1706]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | Y

## Description:
The dropdowns on /leads/new is not visible due to overflow on the screen for lead owner.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 7.0.1

### Log errors: 
![image](https://cloud.githubusercontent.com/assets/985837/15117604/4ab1a256-15d6-11e6-91c5-ca850c9a01e9.png)

And under forms data

![image](https://cloud.githubusercontent.com/assets/985837/15117646/8272788c-15d6-11e6-958d-e9f3c598e4e2.png)

**Comment by ldrrp** [comment]
Just noting, still an issue in 2.0.0.

**Comment by alanhartless** [comment]
This is a long, long standing bug in Chosen. https://github.com/harvesthq/chosen/issues/86

And bootstrap isn't fixing the dropdown in table responsive layouts. https://github.com/twbs/bootstrap/issues/11037

So in both cases - however we fix them - we'll have to hack a fix.

**Comment by MaxWebmecanik** [comment]
#### Hi, checkout #2489! It should fix the /contacts/new page. :tada:

As for the form results, I think simply removing [this line](https://github.com/mautic/mautic/blob/e146b2eb2a2a153c0097e7ab8bdce201fb5f24ce/app/bundles/CoreBundle/Assets/css/app/less/components/table.less#L30) would lead to a better result to what we currently have... (Note that you'd have to run `mautic:assets:generate` after doing so)
