### ISSUE TITLE
UPLOAD IMAGE NEW VERSION 

### ISSUE THREAD

**Issue by robehdez** [mautic/mautic#1716]
Hello
When trying to upload images to modify a template does not work. It is locked.

## Steps to reproduce

step1

![image](https://cloud.githubusercontent.com/assets/18166723/15154099/42279e40-16dc-11e6-8d19-12891659bc31.png)

Step2 

![image](https://cloud.githubusercontent.com/assets/18166723/15153945/974d71fc-16db-11e6-800f-8ab8d25d295e.png)

**Comment by ayrad** [comment]
I personally couldn't reproduce this issue

Can you please verify that folders permissions are OK? go to Configuration (little cog icon on top right corner) > System info > Folder & File permissions and check that /media/images is writable:

![permissions](https://cloud.githubusercontent.com/assets/10789928/15157700/0a82486c-16ed-11e6-982e-6c4505f7e582.jpg)

I hope this helps buddy!

**Comment by robehdez** [comment]
Its ok

![image](https://cloud.githubusercontent.com/assets/18166723/15172368/f60401fa-1755-11e6-9122-c8c622cf78e9.png)

We have seen that this version 1.4 will see if it solves .

**Comment by robehdez** [comment]
With version 1.4 correct everything. Thank you!
