### ISSUE TITLE
Trackable links created for each unsubscribe/webview link

### ISSUE THREAD

**Issue by ayrad** [mautic/mautic#1718]
## Description
When sending email via campaign, a link (redirect trackable) is created for each unsubscribe / webview link. That makes (contacts * 2) links for each email...

## Steps to reproduce
- Create a template email with webview and/or unsubscribe text
- Create a segment
- Create a campaign to send email to segment
- Update contacts and trigger events
- Go back to "Channels" > "Emails", click on your email and check the trackable links shown under "Click counts" tab

**Comment by escopecz** [comment]
What Mautic version do you use?

**Comment by alanhartless** [comment]
Based on terminology, it's 1.4 code. Let's double test this before re-releasing 1.4 :-)

**Comment by alanhartless** [comment]
We couldn't reproduce this I'm afraid. Can you provide content that results in this happening?

**Comment by ayrad** [comment]
Sorry but right now I don't have full access to Mautic. All I can see is this:

![trackable_links](https://cloud.githubusercontent.com/assets/10789928/15161587/0faf5764-16ff-11e6-949a-cfc391863ce4.PNG)

Let me check this more in deep, because it could be caused by some magic done on a custom plugin (translated 

I report back anything I find ;)

**Comment by dongilbert** [comment]
Is this in self-hosted Mautic, or are you using mautic.com SaaS service?

**Comment by ayrad** [comment]
@dongilbert Self-hosted Mautic

**Comment by ayrad** [comment]
Sorry guys, forget about this...

The issue was on my own plugin because of not correctly adding custom {webview_text} and {unsubscribe_text} tokens...

``onEmailGenerate``, I was replacing the tokens directly inside the email content (which now I realise it's so bad idea, because those links were treated as trackable ones). Replaced that for ``$event->addToken($token, $value);`` so now they are treated as tokens to be replaced just before sending the email (as in standard tokens)

Sorry again for this false-positive
