### ISSUE TITLE
The campaigns:triggers doesnt work when your email settings are set to send emails in "Queue Mode"

### ISSUE THREAD

**Issue by maxitromer** [mautic/mautic#1722]
## Description

The campaigns:triggers cronjob doesnt work when your email settings are set to send emails in "Queue Mode"

## Steps to reproduce & test

1.- Config your email service (I'm using Amazon SES and running a 1.3.1 version of Mautic)
2.- Set the "How should email be handled?" option to "Queue"
3.- Create a Campaign to send one email an use the "Opens Email" desicion to send another email on open. (The "Set Action Timing" of the second email must be config as "When Triggered").
4.- Just add your email to pass trought this campaign and open the first email.

## Actual Solutions Without Coding

(This is for people who needs to make this works and cant wait for a change of code)

1.- Change the "timing" to all of your desicion triggers to "Wait", can be just 1 minute, but this schedule the action to perform later and works.

2.- Change the "How should email be handled?" option in your email settings from "Queue" to "Send inmediately"

Hope this help someone.

**Comment by ayrad** [comment]
@maxitromer I had same error here: https://github.com/mautic/mautic/issues/1672 but solved it by clearing the cache before and after changing "How should email be handled?" to Queue mode

Check the config file ``app/config/local.php`` and make sure you got the changes applied on "mailer spool" option inside this file

**Comment by maxitromer** [comment]
Thanks for your contribution @ayrad! I will test it.
