### ISSUE TITLE
Campaign builder steps are empty after clone

### ISSUE THREAD

**Issue by sageeki** [mautic/mautic#1726]
## Description
Campaign builder steps are empty after clone (even if I apply or Save and Close - which than causes mautic to disable the rest of the buttons, stay on page and not actually save)
## Steps to reproduce
Create a campaign using the campaign builder, save and clone - campaign builder flow is not saved.
After update to 1.4

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/1566
