### ISSUE TITLE
DAILY OPERATION - CLEARING CACHE

### ISSUE THREAD

**Issue by robehdez** [mautic/mautic#1727]
## Description

Sometimes we have to delete the app/cache folder to work properly. We know it is due. Do you have any idea what can be?

We currently have Version: 1.4

Thank you very much

**Comment by alanhartless** [comment]
What errors are leading you to have to clear the cache manually? In theory, you should only need to wipe the entire cache if it does not happen successfully during an update. Otherwise, the cache shouldn't change.

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to comment with answer to Alan's question and this issue will be re-opened.
