### ISSUE TITLE
Unable to see dashboard popover for stats.

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1729]
![image](https://cloud.githubusercontent.com/assets/985837/15195392/afa11d16-1795-11e6-8ed3-7ef73161814d.png)

**Comment by escopecz** [comment]
The dashboard was completely changed in 1.4.0 so this issue is a bit outdated.

**Comment by ldrrp** [comment]
Issue still stands on 1.4

![image](https://cloud.githubusercontent.com/assets/985837/15223359/124bf4ac-1842-11e6-83fd-aeefe6f34fd4.png)

**Comment by ldrrp** [comment]
Not as bad, but its still technically there.

**Comment by ldrrp** [comment]
Another page. 

![image](https://cloud.githubusercontent.com/assets/985837/15271653/a0ce62a6-1a21-11e6-9e4b-877fe9a3ffd8.png)

**Comment by ldrrp** [comment]
Another issues i just noticed, maybe bug this seperately. The search inputs dont have the same height as the "fa-filter" buttons

**Comment by escopecz** [comment]
Thanks for the report! It's not related to the tooltip issue. Could you please create a new GitHub issue for each issue?

**Comment by ldrrp** [comment]
Sounds good, ill bug that separately.

**Comment by ldrrp** [comment]
Fixed in 2.0.0

**Comment by ldrrp** [comment]
@escopecz please close
