### ISSUE TITLE
Bug - campaign condition based on select type field

### ISSUE THREAD

**Issue by SamWebmecanik** [mautic/mautic#1734]
## Description

We discovered a bug concerning campaigns creation via the campaign generator. When using the “equal” or “like” operator on a lead list, the condition systematically returns false.
Currently, a workaround for this is using the “greater than” which works just like the “equal” operator should.

## Steps to reproduce

From a campaign:
- Open the campaign builder
- Add a Lead Field condition
- Choose a select type lead field
- Set the condition to "equal"
- Observe how the condition is never fulfilled

## Question
We would appreciate your help on this problem, for instance, pointing us to where you suspect that bug may be.

**Comment by npracht** [comment]
Hi,

@SamWebmecanik has worked on it and corrected this bug. He'll prepare a pull request.
