### ISSUE TITLE
Installation of Mautic 1.4.0 on localhost:8080 at the Step#2 mautic throws the following error message 

### ISSUE THREAD

**Issue by ZeMaarij** [mautic/mautic#1743]
Operating System: Windows 10
Wamp version: Latest ( Last Updated 2016-03-24)
Mautic Version: 1.4.0 

Error message 1
"An error occured while attempting to connect to the database: SQLSTATE[HY000] [1045] Access denied for user 'mautic_db'@'localhost' (using password: YES)"

![error1](https://cloud.githubusercontent.com/assets/8540758/15271754/2e72cc6e-1a72-11e6-9d01-8edccba88a9b.jpg)

Error message 2

"An error occured while attempting to connect to the database: SQLSTATE[HY000] [2006] MySQL server has gone away"

![mautic error2](https://cloud.githubusercontent.com/assets/8540758/15271705/6f1bb73c-1a70-11e6-8858-71c390bcc098.jpg)

## Steps to reproduce
Install a Wamp server on Windows 10. My SKYPE was clashing with WAMP Apache port that is 80. so it was changed to 8080 in httpd.conf file. The WAMP icon turned green.
When Mautic is placed in the www folder for WAMP and http://localhost:8080/1.4.0/installer is run (first step). When Next is clicked and the form on http://localhost:8080/1.4.0/installer/step/1 is filled and Next Step is clicked Error message 1 is displayed and the installation does not proceed.
I have tried every thing, however it is noticeable that when in the same form on http://localhost:8080/1.4.0/installer/step/1 when the localhost is typed with port 8080 like localhost:8080 the Error message 2 is displayed. Please let me know the solution.
Please do let me know if you need more detail.

**Comment by escopecz** [comment]
Hi, it doesn't look like a Mautic issue. It will be more likely caused by wrong MySql credentials or MySql configuration. Please, consult your issue with some Windows system administrator.
