### ISSUE TITLE
Data forwarding forms

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1744]
On a registration form it would be nice if i could forward the data to a form handler on my server so i can create the contact. Right now im trying to curl request the data over which is kinda annoying.

**Comment by escopecz** [comment]
Could you please be more specific about the form handler? Is it something like creating a contact via API?

developer.mautic.org

**Comment by ldrrp** [comment]
NVM this bug was stupid the more i though about it. Its what pardot does but when i was thinking more about the mechanics behind it, it makes more sense to use the api.
