### ISSUE TITLE
CKEditor Still Strips Custom HTML from Landing Pages

### ISSUE THREAD

**Issue by mhalvorsen** [mautic/mautic#1746]
## Description

CKEditor is still stripping custom HTML from landing pages when inserted via the "Source Dialog" plugin.

Any code inserted into a Landing Page or Email should not be modified by the Advanced Content Filter in CKEditor.  When it is being modified, it's nearly impossible to diagnose issues or see them before you send out a campaign. 

## Steps to reproduce

Create a new landing page. Use empty tags like those used for Font Awesome's font icon library:

`<i class="fa fa-play-circle" style="color: rgb(255, 0, 0); font-size: 200px;"></i> `

Save the page. The `<i>` tag gets stripped from the page.

## How to Fix
The /app/bundles/CoreBundle/Assets/js/libraries/ckeditor/config.js file needs to have the following line of code inserted after line 16:

`config.allowedContent = true;`

From their official documentation:
http://docs.ckeditor.com/#!/guide/dev_advanced_content_filter

> If you want to disable Advanced Content Filter, set CKEDITOR.config.allowedContent to true. All available editor features will be activated and input data will not be filtered.

After you have modified the config.js file to test my proposed solution, do note that you need to clear your browser's cache or open it in an incognito window to test that it works. I spent a good 20 hours trying to get this figured out and the browser cache was the issue.

**Comment by escopecz** [comment]
Since CK editor has been replaced with Froala editor, I'll close this issue.
