### ISSUE TITLE
SMS - Ability to insert placeholder text into the body of Text Messages

### ISSUE THREAD

**Issue by bamzi** [mautic/mautic#1748]
## Description
Ability to insert placeholder text i.e. `{leadfield=firstname}` into the body of the text message.

Aside from general messages like `hi {firstname},....` which are more personal but in order to make the sms message even more relative and worthy we'd like to be able to insert user specific custom fields into text messages ... like "invite codes" or "discount codes" etc.. 

Currently we can only create  one size fit all "text message templates" through the campaign builder but unlike email wysiwyg editor which allow inserting placeholders like above, we cannot do the same in body of text messages. 

Even manually inserting something like `{leadfield=firstname}`, is processed raw and sent through the wire.

**Comment by MxyzptlkFishStix** [comment]
+1

**Comment by MxyzptlkFishStix** [comment]
+1

**Comment by kuzmany** [comment]
+1

**Comment by dongilbert** [comment]
Addressed in #2162
