### ISSUE TITLE
Not show leadfield parameter on "Send Example"

### ISSUE THREAD

**Issue by hideokamoto** [mautic/mautic#1749]
## Description

Email send example,I want to set leadfield parameter.
### Step1:Create Email using leadfield

![](https://s3.amazonaws.com/tmpfiles-for-dc/github-issues/step1.png)
### Step2:Send Example

![](https://s3.amazonaws.com/tmpfiles-for-dc/github-issues/step2.png)
### Step3:Check Email

![](https://s3.amazonaws.com/tmpfiles-for-dc/github-issues/step3.png)

I think it use logged in user's data.
thanks

**Comment by escopecz** [comment]
The test email is sent to the user, not to the contact. Mautic user doesn't have the same fields as the contacts do so it's not possible to replace them. Previous Mautic version took a random contact and used his information to prefill the email params. But then we got tons of questions like:

> Why the test email says 'Hello Steve'?

So it was changed to tags in `[]`.

How would you suggest to improve it?

**Comment by ayrad** [comment]
What about one of the following?:

- Allow the user to select destination contact (probably related to #1447)
- Link user to lead (each user may have his own related contact record)
