### ISSUE TITLE
[Feature request] Conditional multi contact sources for campaigns

### ISSUE THREAD

**Issue by ayrad** [mautic/mautic#1751]
## Introduction

Honestly, to handle big campaigns with Mautic it's a little bit tricky... Let's say we want to send a massive email campaign to 40k+ contacts by having a 'countries groups' based content

Right now the way I think it's possible to be done is by creating a segment for each 'countries group', create as much emails as different content (repetitive content can be moved to template, but sometimes it's almost all different) and then the most painful one IMO it's to create a campaign for each email-segement combination. This latest one can be partially automated by a plugin, but even with that we'll end up with +20 campaigns in "Campaigns" list for each real campaign we send
## Feature Request

How about allowing multiple contacts sources in campaign builder and conditional email send action?

I mean, if we have to send email A to segment 1, email B to segment 2, email C to segment 3... I think all 3 actions can be merged in same campaign by allowing to choose which email to be sent to what segment

**Comment by mitsurugi** [comment]
:+1:

**Comment by tadinski** [comment]
+1
