### ISSUE TITLE
PHP 5.4 required for 1.4.0 !

### ISSUE THREAD

**Issue by zachrdlapetr** [mautic/mautic#1754]
Please, change minimal requirements for Mautic. You write minimal requirements PHP 5.3.10 but you use ['....' => '.....'] notation for array. This notation is available in PHP 5.4.

**Comment by JuanLuisGarciaBorrego** [comment]
I have the same problem. The code PHP used is 5.5.

**Comment by escopecz** [comment]
The fix is here: https://github.com/mautic/mautic/pull/1732

**Comment by zachrdlapetr** [comment]
Unfortunately, many people find out this a bit late. I found out this when I updated to 1.4.
