### ISSUE TITLE
getting PHP error after updating to 1.4

### ISSUE THREAD

**Issue by mecyborg** [mautic/mautic#1755]
mautic.NOTICE: PHP Notice: Undefined index: emails - in file /var/www/mautic/app/bundles/EmailBundle/Helper/PointEventHelper.php - at line 30 [] []

Please can you help.

**Comment by escopecz** [comment]
Can you provide steps to replicate the issue? Or does it happen on every page view?

**Comment by mecyborg** [comment]
Hi @escopecz 
thanks for the quick response. It only happens when i click on channels>emails from sidebar. It take sometime and then it starts working.

When i checked the logs, i saw that error for everytime i clicked on channels>emails.

**Comment by dbhurley** [comment]
The error message you mention is a "notice" and not an error, is there any other messages in your log?

**Comment by mecyborg** [comment]
Yeah its a notice. But the application is hanging due to this i guess. 
Is there any fix for this ?

**Comment by escopecz** [comment]
I don't think the lag in the response and the notice are related. Your emails possibly have a lot of stat data, is that right? It might take a while to process them.

**Comment by mecyborg** [comment]
No the data is not much. The thing is the app just hangs for 5 mins or so after i click on emails. And when next time i click on email if works,

**Comment by alanhartless** [comment]
The notice in the log is completely unrelated to loading the email list - the PointEventHelper::validateEmail is only called when point actions are defined and an email is opened. Likely coincidence with opening the list.

The queries were updated for generating the stats on the email list page in recent versions. If this is still an issue - please let us know and we'll reopen.
