### ISSUE TITLE
segment Labels are not easily readable

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1758]
![image](https://cloud.githubusercontent.com/assets/985837/15399484/d1775cb8-1db5-11e6-9477-257838f207e0.png)

**Comment by escopecz** [comment]
The chart legend is fixed in https://github.com/mautic/mautic/pull/1713

**Comment by ldrrp** [comment]
Fixed, thanks

**Comment by ldrrp** [comment]
@escopecz please close
