### ISSUE TITLE
Campaign sends emails before the "wait until" date

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#1759]
I programed a campaign to send one email tomorrow morning

![image](https://cloud.githubusercontent.com/assets/10166840/15401393/acfef686-1def-11e6-92de-92e0175c3c9a.png)
![image](https://cloud.githubusercontent.com/assets/10166840/15401541/49bfbcc6-1df0-11e6-94e9-beccb60af19e.png)

but unexpectedly it send all emails when I activated the campaign :(

![image](https://cloud.githubusercontent.com/assets/10166840/15401430/dc0e7050-1def-11e6-8145-7278d93ab16e.png)

What have I done wrong?

## Steps to reproduce

**Comment by miguelpascual** [comment]
What have I done wrong?

**Comment by miguelpascual** [comment]
it happend another time. 
The 27 of may a created a new step in the campaing. 
![image](https://cloud.githubusercontent.com/assets/10166840/15647125/02b79662-2662-11e6-83d8-794047ba20b3.png) (this capture is of the day I created the campaign)

to send the same email to a segment of global list (I use the same email to dont send twice to the same recipient even it are in some segments)

Today I see it envied the email before the date. 

![image](https://cloud.githubusercontent.com/assets/10166840/15647214/773e7672-2662-11e6-921f-5d7e1395cd26.png)

and some mails are sending now :S I don't understand why...

any idea?

**Comment by escopecz** [comment]
Do you have the right timezone configured in your user's edit form or in the global configuration?

**Comment by alanhartless** [comment]
Due to lack of feedback, we're closing this issue. Please upgrade to 2.1.1 and if the issue persist, definitely let us know! Thanks!
