### ISSUE TITLE
CMS Plugins able to be Extended

### ISSUE THREAD

**Issue by MaxOnTheHill** [mautic/mautic#176]
wondering if the CMS plugins themselves are able to be extended on top of ... to offer extra features just added on top of the plugin ... in stead of completely replacing the core CMS plugins?

so instead of building a whole "Advanced Joomla Plugin" that is the core plugin and bits adde on ... we can just add a couple of hooks in a mini-plugin to add some extra on top - just wondering the approach to allow best functionality and minimum code

**Comment by escopecz** [comment]
Closing this since every CMS is different. It can be possible in some, but not in others.
