### ISSUE TITLE
Unable to Edit Webhook 

### ISSUE THREAD

**Issue by seanschroeder** [mautic/mautic#1762]
## Description
After adding a webhook in Mautic 1.4, I can no longer edit the webhook or access the following screens:

- Webhooks
- Plugins

## Steps to reproduce

1. Add a new webhook
1. Browse to another screen
1. Try to access Webhook admin screen

**Comment by escopecz** [comment]
I cannot replicate. Could you please see if there is some error recorded in the app/logs dir?

**Comment by seanschroeder** [comment]
Thanks for checking it out. There were some errors, but cleared the cache directory and that seemed to resolve it.
