### ISSUE TITLE
Email links mismatched

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#1764]
## Description
I have a 3 email drip campaign for a set of 3 blog posts
The second email has just been released according to schedule
When I click the link for the article in the second email, I am directed to the first blog post.
I made a mistake, so what can I do so my subscribers get sent to the right page? probably nothing, just be careful next time.

##Request
Can the link tracking be made capable of allowing the tracked links to be changed after the email is sent? This would be really valuable in the case of human error like what I just made.
This should be possible given that the tracked link comes back to the Mautic server for tracking before being redirected to the destination

**Comment by dongilbert** [comment]
In theory, as long as the tracked link is a different url, you should be able to change the destination. Of course, even if they are the same, you can go into the page_redirects table and manually edit the destination link, but that would break the links in your first email that already went out.

**Comment by jkuchar** [comment]
Sounds like a cool feature!

**Comment by zstephen** [comment]
thanks @dongilbert I'll check it out for when I'm in a position to get into the DB (better for when I'm in the office than out).

My thinking was more centred around something that the end user in marketing could use without having to "get under the bonnet" and make changes like that.
