### ISSUE TITLE
Notification & SMS Permissions Tabs/Headers Missing Translation Titles (Fix)

### ISSUE THREAD

**Issue by MxyzptlkFishStix** [mautic/mautic#1769]
![1](https://cloud.githubusercontent.com/assets/9151657/15426532/257d57a2-1e5d-11e6-85c0-0e9b751d4add.png)

Adding the following to /app/bundles/SmsBundle/Translations/en_US/messages.ini:

`mautic.sms.permissions.header="SMS Permissions"`
`mautic.sms.permissions.smses="SMS - User has access to"`

and to /app/bundles/NotificationBundle/Translations/en_US/messages.ini:

`mautic.notification.permissions.header="Notification Permissions"`
`mautic.notification.permissions.notifications="Notification - User has access to"`

fixes it.

**Comment by escopecz** [comment]
Fixed in Mautic 2.1.0.
