### ISSUE TITLE
Adding new email handlers

### ISSUE THREAD

**Issue by drmmr763** [mautic/mautic#1773]
## Description

Hey guys! Miss you all! 

I am looking into trying to add new email handlers into mautic. But I'm seeing that it doesn't look very intuitive to do from an addon approach. Here's what I thought of so far:

Idea 1 - New Config Options
Adding a new handler to the config form doesn't look possible since they are hardcoded here:
https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/Config/config.php#L212

There's no event to add in a new handler when the select lists are generated for the config area:
https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/EventListener/ConfigSubscriber.php#L37

Idea 2: OnEmailSend Event
I thought of possibly trying to use the OnSendEvent to swap out the selected mail handler:

https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/Helper/MailHelper.php#L373

This would be perfect since you could literally just hook into that event, getting the `$this` instance of the EmailHelper, update the $mailer object to one you custom-specify in your addon, and let it continue down the execution cycle. But since the $mailer property is protected and there's no setter, I don't see that as a viable option either. 

Idea 3 - OnFormBuild Event
The last idea I had was to hook into the onFormBuild event which could then get propagated into the mailer config. I didn't hunt this one down too much but right now it looks like the only possible option left. I just don't know if its flexible enough for what I'm going to try to do from a function standpoint. 

Am I missing a good way to do this sort of thing? If not should I investigate adding a PR to make one of the options I've already thought of a workable option?

Thanks for any tips!

**Comment by alanhartless** [comment]
Aww - so only months late!!! We miss you too! Sorry about this - obviously it got lost in the midst of the hundreds of open issues we have :-( Most being feature requests.

For # 1 - are there additional config fields you need besides the standard for configuring email? (an API key was recently added)

Thinking through this, maybe should do something similar to how we handle 3rd party IP Lookup plugins. https://github.com/mautic/mautic/blob/7541dbce0c7e50ba6955020f7144b6f49f7b5e60/app/bundles/CoreBundle/Config/config.php#L606-L606 to build the list of supported transports for the Configuration's Mailer Transport. We wouldn't need `class` just an array of `['service.name' => ['label' => 'Transport Label', 'display_settings' => []]`. Then we can simply collect them the same we do the ip lookups and save them to a parameter https://github.com/mautic/mautic/blob/500e50991ef7b1f96e1697c2c49c4420e75803c3/app/config/config.php#L6-L6 which can then be used as the choices along with some magic using 'display_settings' to generate the data-show/hide-on attributes appropriately.

The alternative is to use Symfony's built in service tagging system. Where the service can define a tag which can be leveraged with cache compiler to find all the tagged services and inject them into a parameter. But that may get tricky to support what to populate for the data-show/hide-on attributes.

Just some thoughts!
