### ISSUE TITLE
Mautic on internal IP over proxypass - Issue on Landingpage address

### ISSUE THREAD

**Issue by altmagalhaes** [mautic/mautic#1774]
Hello guys I just installed Mautic and found an issue that I do not known how to fix. The web address of the landing pages apear as the internal IP of the computer running the software.

The instalation is as follows:

Webserver with valid Ip address, numerous subdomains pass through here and this apache uses proxypass to send a specific subdomain to one of the multiple webservers running on private IPs like my mautic that is on the ip 192.168.10.66

The issue is when I´m accessing it remotely is works and all but the address of the landing pages that it shows is like http://192.168.10.66/nameofthepage and of course it does not work

I cannot seem to find a way to get Mautic that this machine is anwsering to that subdomain (it is even in its hosts.conf, if you ping its subdomain from inside it the IP 192.168.10.66 is reached). All my other systems runs well in this scenario, how could I change this parameter that Mautic get this base url from?

Here a screenshot: https://i.imgur.com/zBd0uEg.png

And to finish I have discovered that it works as it should if I access it from the local network that it is inside the subdomain of the Mautic instalation shows as it should. This network has its own DNS server that makes the subdomain point to the Mautic IP Adress.

**Comment by altmagalhaes** [comment]
please?

**Comment by andrewcurioso** [comment]
This is probably the same issue I'm seeing in https://github.com/mautic/mautic/issues/1845

**Comment by escopecz** [comment]
@altmagalhaes does it work for you with Mautic 2.1.0?

**Comment by alanhartless** [comment]
If you are using a proxy to Symfony as the IP address itself - Symfony will build it's URL from the request, meaning with the IP address. You'll probably need to proxy to the actual host/domain.

**Comment by dfranco** [comment]
I'm using 2.1.1 and still have the same problem with url of landing pages.

**Comment by nikoameer** [comment]
I am having similar issue in Mautic 2.11.0, on my landing pages and in my browser console of the website that is used with mautic also shows error: net::ERR_CONNECTION_REFUSED.

It is using local ip address to connect to js file.

![blank](https://user-images.githubusercontent.com/24823378/35393127-c09bac2e-01ec-11e8-95c3-486341c05f54.png)

Does anyone have any solution for this problem? Thank you!
