### ISSUE TITLE
Issue on exit intent

### ISSUE THREAD

**Issue by marziovit** [mautic/mautic#1778]
I'm trying to implement mPower focus. 

I set up the modal to collect data and to appear when a visitor intend to leave and it works fine when an user try to leave. Problem is that the modal is triggering also when an user clicks on a link on my site.

This is a mistake because if the user clicks on the "add to cart button" is presented with a free alternative to learn more instead of buying now.

Please remove the click trigger on the exit intent.

**Comment by escopecz** [comment]
Hi @marziovit,

mPower focus is not yet part of the open source Mautic which contains this GitHub repository. Therefore it cannot be fixed here. Please report this issue via the Help button in your Mautic instance.
