### ISSUE TITLE
Auto Generate txt

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1781]
I believe this is a little confusing to users. It appends to the text area instead of replacing like most Marketing automation tools used. Maybe two buttons one for replace and one for append. Unless you dont think it should be appending all the time. (end up with like 50 of the same text)

![image](https://cloud.githubusercontent.com/assets/985837/15474632/a066cfc0-20d3-11e6-948d-81cd406f4110.png)

**Comment by escopecz** [comment]
The whole CK editor will be replaced with Froala editor in https://github.com/mautic/mautic/pull/1779. This issue will have to be also re-written.

**Comment by ldrrp** [comment]
Sounds good, Can we keep this open so i do forget about it. I will rewrite the issue for the new editor.

**Comment by ldrrp** [comment]
Seems this issue is fixed in 2.0.0 please close
