### ISSUE TITLE
Feature Request - Ability to set communication pressure on contacts via email.

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1784]
# Context

On of the concerns of the marketer is the ability to adapt communication pressure on its contacts.
## 2 ways to set that up
1. First concern would be to have this ability to set something like **do not mail contact more than once a day/week/month/year/etc.** in fact it could be annoying for a contact to receive 2 emails in the same day if we have set a big amount of campaigns and if he is qualified in many of them.
2. Second topic would be more about, **adapt pressure depending on their profile**.
# Suggestions
1. For the first setting, it could be done in the email setting, or directly in the campaign options (i.e. for that campaign, dot not send an email to my contact if he received another email in the last X days).
2. For the second way, it could be done in the lead stage settings (extra feature of the PR XXXXXX), or also in the campaign settings that could bring flexibility (you can manage the way you want depending on the campaign.
## What happens to the email supposed to be sent?

It would be queued until the condition set is met and sent on the following CRON.

---

What do you think?

N.

**Comment by dbhurley** [comment]
The problem with queuing becomes the issue of priority. I'd be interested in your thoughts on how you would resolve that potential conflict?

**Comment by npracht** [comment]
Hi David,

Great question. I don't know how does competitors. Now i assume it's the role of the marketer that set the campaign to insure that there is not too much cross campaign qualification for a same contact to avoid this kinda problem.
We (mautic developers) cannot be responsible for all the problematic that are generated by a bad use of features.
ie: today you can spam your database with 1 email each 10mn for all of them ---> that's not our fault.

So i'd simply say: you queue, then the email will leave when the requirement will be met. And it's the role of the marketer to insure coherence in all marketing automation campaigns.

**Comment by escopecz** [comment]
I think this was implemented in https://github.com/mautic/mautic/pull/2114.
