### ISSUE TITLE
Feature Request - Add a company management view

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1785]
# Context
In most of B2B2C or B2B companies, the company approach is very important.
Even if in marketing automation we based on a H2H relation, for the salesman, it could be very interesting to have a view of the recent activity based on companies.

# Suggestion
### Add a `company management` submenu in the `contact` menu.
With the same view as `contact management` sorted by last active, but with a list of company names.

### Add a company profile page
If you click on the name of a company, it lists
- all leads with the the same company name
- contacts timeline activity grouped for all the contacts of the company (contact AAAA visited a webpage, contact ABBB received an email, etc.).
- some action activable for the company (the group of contacts): send an email, add to a list, send a SMS, edit contact field, etc.

________

Your opinion?

N.

**Comment by karpadiem** [comment]
I'd like to plus one this. Something similar to [intercom.io's new company grouping](https://docs.intercom.io/configure-intercom-for-your-product-or-site/customize-intercom-to-be-about-your-users/group-your-users-by-company).

Being able to modify rules based on all interaction within the company group would be amazing.

**Comment by alanhartless** [comment]
Coming in 2.2. #2403
