### ISSUE TITLE
Trackables > Friendly URLs leadfields not replaced

### ISSUE THREAD

**Issue by ayrad** [mautic/mautic#1787]
## Description
When a leadfield is supplied to a friendly URL (domain/leadfield1/leadfield2), the tokens are not replaced with fields values....

For example, the following links:
```
<!doctype html public "-//w3c//dtd html 4.01 transitional//en" "http://www.w3c.org/tr/1999/rec-html401-19991224/loose.dtd">
<html>
<head>
	<title></title>
</head>
<body>
<a href="https://domain-hope-doesnt-exist.com/{leadfield=countryisocode}/{leadfield=language}">Testing link 1</a><br>
<a href="https://domain-hope-doesnt-exist.com?country={leadfield=countryisocode}&lang={leadfield=language}">Testing link 2</a>
</body>
</html>
```

Are translated to this:
- Link 1: https://domain-hope-doesnt-exist.com/%7Bleadfield=countryisocode%7D/
- Link 2: https://domain-hope-doesnt-exist.com/?lang=de&country=DE

When the fields are put as query strings, they get replaced correctly, but when inside friendly URL, they don't.

## Steps to reproduce
- Copy and paste the supplied HTML inside an email (Template email in this case)
- Change the fields for yours, because you may not have "countryisocode" and "language" ones
- Send that email to yourself in a campaign (didn't test list email, but may be the same)
- See that leadfield tokens are not replaced with right content in both links

**Comment by escopecz** [comment]
There were already some fixes in this area. Could you please test if this still occur on Mautic 2.1.0?

**Comment by alanhartless** [comment]
Due to lack of feedback, we're closing this issue. Please upgrade to 2.1.1 and if the issue persist, definitely let us know! Thanks!

**Comment by Rixita** [comment]
This bug has raised from the dead ;).
