### ISSUE TITLE
Allow use html code in checkbox fields

### ISSUE THREAD

**Issue by RegisScaggiante** [mautic/mautic#1790]
## Description

One of the fields of my form is a checkbox "I accept the terms of the contract". But is not possible to insert a html code with link to the page of the contract.

in other fields is possible to use html code, but the checkbox field is not yet.
I want to use in the checkbox field a code like this:
`"I accept the <a href="http://exemple.com/contract" target="_blank">terms of the contract </a> "`

**Comment by coop2540** [comment]
Not working on 5.0.3 and 5.0.4

**Comment by MadlenF** [comment]
I can also also confirm that this is not working anymore in 5.1
