### ISSUE TITLE
Feature: Automatically add X-Mautic (or similar) to outgoing emails

### ISSUE THREAD

**Issue by amit777** [mautic/mautic#1792]
## Description

When emails are sent from Mautic, we route them through our corporate mail server and want to apply some policies to them based on this header. 

A simple setting in the email settings screen would work perfectly.

**Comment by mmmichael** [comment]
I would like to add some headers too. Mailjet support special Headers (https://www.mailjet.com/docs/emails_headers) to group Campaigns and I would be great, If I could add this headers.

**Comment by dev1Blayzer** [comment]
Would like to see this as well - what's the status of this? We would be willing to help add this to Mautic if a contributor could give us some direction.

**Comment by amit777** [comment]
I have a little time to help on this as well.   Is there any way we could sponsor the development of this feature?

**Comment by escopecz** [comment]
@kuzmany started a crowd funding Mautic development. Maybe you can ask him to add this feature to his road map.

https://mautic-fund.kuzmany.biz/
