### ISSUE TITLE
Filter leads based on Tags

### ISSUE THREAD

**Issue by Ashwin-Ram** [mautic/mautic#1794]
## Description
It will be great, if Mautic can filter leads by tags as it will play an important role in identifying leads in a granular level instead of re-creating lists again and again.

Although we can use tag:tag_name for filtering, Tag Name(Buttons) if clicked, or a new filter dropdown box with tags will make it more user-friendly.

Also option to add a tag based on a response selected by users when filling in the forms, can reduce manual tagging for every lead added via forms.
## Steps to reproduce

**Comment by escopecz** [comment]
Could you describe what's the goal you want to achieve? Why do you need to re-create lists/segments again and again? Maybe you should use the lists/segments instead of tags in the first place? You can also filter contacts by tags by typing `tags:` and the name of the tag.

**Comment by Ashwin-Ram** [comment]
Hi escopecz. Thanking you for immediate reply.

Consider this scenerio. Leads are filling course enrollment forms on a daily basis for a Training Company. We can get all the lead information from the users who fill the form,but we actually have to tag every lead manually.

1st request - Say a male fills the form, can we have the same form option as a tag.
2nd request - Having an Button with the tag name will make it more user-friendly to use.
3rd request -  Email forwarding with tags will be helpful, instead of filtering using tags, selecting them and sending an email or making a new llist and sending the mail through the list.

Kindly watch the video in the following link, to better understand the use feature request.
https://goo.gl/gIe11q
https://goo.gl/3MplLL

**Comment by alanhartless** [comment]
I think using a campaign to tag them as they are added will assist with this. Also, filtering by tags was added somewhere along the journey of Mautic releases so should be there now.
