### ISSUE TITLE
Builder issue

### ISSUE THREAD

**Issue by cristianoap** [mautic/mautic#1797]
## Description
Content disappears after close Builder. Issue occurs in upgraded installation and fresh installation.

## Steps to reproduce

1. Create/Clone a email/landing
2. Choose a theme (if is new email/landing)
3. Launch Builder
4. Edit content
5. Close Builder
6. Reopen Builder
7. Content, where are you??

The issue does not occurs if Apply is clicked before Reopen.

**Comment by escopecz** [comment]
Also reported in https://www.mautic.org/community/index.php/4052-email-builder-doesn-t-working/0#p11324 and I can replicate too.

**Comment by cristianoap** [comment]
The issue is gone. Closing.
