### ISSUE TITLE
Cannot create a new/edit Pages

### ISSUE THREAD

**Issue by dannyec** [mautic/mautic#1799]
## Description
Using another language (chinese in my case), It doesn't show the list of languages when create or edit new Pages, it is a empty list, when save it show: " This value is not valid. " due not languages load in the list. 

## Steps to reproduce

0. Using [chinese language]
1. Create / Edit Pages
2. Save
3. ** Failed load languages list **
4. Can not save it.

<img width="296" alt="screen shot 2016-05-26 at 10 31 45 am" src="https://cloud.githubusercontent.com/assets/13312135/15562022/160d88ca-232e-11e6-8819-77a854ad1585.png">
![screen shot 2016-05-26 at 10 39 42 am](https://cloud.githubusercontent.com/assets/13312135/15562113/ddab4da4-232e-11e6-8469-d2d9c285927a.jpg)

**Comment by alanhartless** [comment]
I'm not able to reproduce this with the latest version. Is it still an issue?

![](http://alan.direct/drop/2016-08-17_22-29-32.png)

**Comment by dannyec** [comment]
Yes, Still an issue, I am using last version and with chinese language, create new pages and save, the language list doesn't appear and cannot save because this issue.

<img width="520" alt="screen shot 2016-08-18 at 5 07 34 pm" src="https://cloud.githubusercontent.com/assets/13312135/17768402/6bcb0be6-6566-11e6-9ef3-97b74fb7556b.png">

**Comment by alanhartless** [comment]
Are you able to find the pattern for the exact steps required to reproduce this? We're missing something between our setups because I can't reproduce this at all.

**Comment by maxitine** [comment]
I've find the same issue with Simplified Chinese Translation. And if I copy the translation (all files in zh_Hans) to another folder named cn, and edit config.php accordingly to different, the issue will be gone. Guess this is an issue with language switcher.

**Comment by maxitine** [comment]
This issue is found with Wamp environment. My further testing with xampp 3.2.2 and bitnami wamp module install seem to be working fine. So this should not be a mautic bug.

**Comment by escopecz** [comment]
@dannyec do you use Wamp?

**Comment by dannyec** [comment]
@escopecz No, Issue on CentOS, also in my local OSX env. I still thinking is something about translations files cache.

**Comment by maxitine** [comment]
Test again with wamp and xampp. The issue is with php-intl extension. This issue happens when the extension is turned on. xampp default installation is off for php-intl.  

This is tested with wamp xampp and bitnami wampstack. Once the extension is off the problem disappears. 

However if the entension is off, Mautic is not able to recorganize the encoding of current page. In fact it will treat the locale of Chinese as English.

**Comment by maxitine** [comment]
Identify the cause of the issue is the language name: zh-Hans instead of zh_Hans. When change the translation folder and locale to zh_Hans, or zh_CN, the issue will go away. Tested with php_intl extension enabled.

**Comment by dongilbert** [comment]
I can confirm this issue. I'm experiencing it on my local. Will work on the fix.

**Comment by dongilbert** [comment]
@dannyec This has been fixed. To get the fix, please change the language back to English in the configuration, delete `app/cache/languageList.txt` and delete `translations/zh-Hans`. Then refresh your configuration page and switch it back to Chinese (Simplified) and you should be good to go!
