### ISSUE TITLE
MailerCallbackAction fails when configured to send messages from spool

### ISSUE THREAD

**Issue by bdentino** [mautic/mautic#1800]
## Description

Callback actions refuse to process when mautic is not configured to send emails immediately (as opposed to queuing them). This currently only applies to the mandrill sender, but I came across it because I'm trying to implement bounce/complaint handling for Amazon SES using similar webhook callback handling. The callback handling logic performs a check to see if the current mailer is an instance of InterfaceCallbackTransport, but when application is configured to queue messages, the mailer inspected is a `SpoolTransport` instance instead of the expected `MandrillTransport` and so the request is ignored.

## Steps to reproduce

Configure the application with a Mandrill sender, and set the email sending option to 'Queue'.
Verify that `/mailer/mandrill/callback` returns 404

**Comment by dongilbert** [comment]
Fixed in #2306
