### ISSUE TITLE
Error on the link within campaign email

### ISSUE THREAD

**Issue by beetosantos** [mautic/mautic#1804]
In a campaign e-mail I use a link to a page. The Mautic (version 1.4.0) changes to
http://automacao.clubedoempresariodesucesso.com.br/mautic/r/4fa7280a80efff38655eaa19f?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo4OiJjYW1wYWlnbiI7aToxO2k6Mzt9czo1OiJlbWFpbCI7aToxNjtzOjQ6InN0YXQiO3M6MTM6IjU3NDc4ZjJmNjZlYWQiO3M6NDoibGVhZCI7aToxMDYxO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYWlsIjtpOjE2O319

The problem is a "</ p>" is inserted improperly in the end.

Already have severed the link with a blank line before and after unsuccessful.

How do I resolve this?

**Comment by escopecz** [comment]
Could you please check if your original HTML link in the email isn't corrupted with the `</p>`?

**Comment by beetosantos** [comment]
Hi! Email excerpt is:

".......
Vamos então para o primeiro bloco, acesse:

http://www.clubedoempresariodesucesso.com.br/PalestraVisao2016/palestras/palestra1de3aki.html

Bom proveito e grande abraço!
........
"

**Comment by beetosantos** [comment]
the link was modified to:
http://automacao.clubedoempresariodesucesso.com.br/mautic/r/4fa7280a80efff38655eaa19f?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo4OiJjYW1wYWlnbiI7aToxO2k6Mzt9czo1OiJlbWFpbCI7aToxNjtzOjQ6InN0YXQiO3M6MTM6IjU3NDc4ZjJmNjZlYWQiO3M6NDoibGVhZCI7aToxMDYxO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYWlsIjtpOjE2O319

**Comment by beetosantos** [comment]
The HTML source is:


                        <div class="row">
                            <div class="col-md-12">
                                <div class="pull-left">
                                    <label class="control-label" for="emailform_plainText" data-toggle="tooltip" data-container="body" data-placement="top" title="Use o Construtor de Email para personalizar o HTML do email. Se voce quiser uma versão em texto, preencha a caixa abaixo.">Versão em texto simples <i class="fa fa-question-circle"></i></label>                                </div>
                                <div class="text-right pr-10">
                                    <i class="fa fa-spinner fa-spin ml-2 plaintext-spinner hide"></i>
                                    <a class="small" onclick="Mautic.autoGeneratePlaintext();">Gerar Automático</a>
                                </div>
                                <div class="clearfix"></div>
                                <textarea id="emailform_plainText" name="emailform[plainText]" class="form-control" rows="15" data-token-callback="email:getBuilderTokens" data-token-activator="{" data-token-visual="false" autocomplete="false">Olá {leadfield=firstname} obrigado por seu interesse em assistir a
minha palestra sobre &quot;Cenários de Negócios em 2016-2018&quot;. Isto para
quem trabalha ou quer trabalhar profissionalmente com flores e
plantas.  Você que verá que esta palestra foi a primeira que
apresentei nesta ano para meus clientes de um serviço pago chamado
&quot;Clube do Empresário de Sucesso&quot; e agora você terá acesso
gratuitamente. Dividi a palestra em 3(três) pequenos blocos, assim
você pode assistir, anotar e analisar a aplicação para a realidade
do seu negócio com toda a calma. Entre um bloco e outro vou te pedir
um favor: que compartilhe no Facebook um anúncio desta palestra
gratuita para que outros colegas seus com o mesmo nível de visão
também tenham a chance de assistir. É tudo muito simples e você
resolve com um click. Vamos então para o primeiro bloco, acesse:
http://www.clubedoempresariodesucesso.com.br/PalestraVisao2016/palestras/palestra1de3aki.html
Bom proveito e grande abraço! Augusto Aki</textarea>                            </div>
                        </div>
                    </div>

**Comment by escopecz** [comment]
The HTML code is part of Mautic's plaintext textarea. Could you please publish HTML of the email message?

**Comment by beetosantos** [comment]
Now I enter the "href" tag to test.
-----------

<html>
<head>
	<title></title>
</head>
<body>
<p>Ol&aacute; <strong contenteditable="false" data-token="{leadfield=firstname}">**First Name**</strong></p>

<p>obrigado por seu interesse em assistir a minha palestra sobre &quot;Cen&aacute;rios de Neg&oacute;cios em 2016-2018&quot;. Isto para quem trabalha ou quer trabalhar profissionalmente com flores e plantas.&nbsp;</p>

<p>Voc&ecirc; que ver&aacute; que esta palestra foi a primeira que apresentei nesta ano para meus clientes de um servi&ccedil;o pago chamado &quot;Clube do Empres&aacute;rio de Sucesso&quot; e agora voc&ecirc; ter&aacute; acesso gratuitamente.</p>

<p>Dividi a palestra em 3(tr&ecirc;s) pequenos blocos, assim voc&ecirc; pode assistir, anotar e&nbsp;analisar a aplica&ccedil;&atilde;o para a realidade do seu neg&oacute;cio com toda a calma.</p>

<p>Entre um bloco e outro vou te pedir um favor: que compartilhe no Facebook um an&uacute;ncio desta palestra gratuita para que outros colegas seus com o mesmo n&iacute;vel de vis&atilde;o tamb&eacute;m tenham a chance de assistir. &Eacute; tudo muito simples e voc&ecirc; resolve com um click.</p>

<p>Vamos ent&atilde;o para o primeiro bloco, acesse:</p>

<p></p>

<p><a href="http://www.clubedoempresariodesucesso.com.br/PalestraVisao2016/palestras/palestra1de3aki.html">http://www.clubedoempresariodesucesso.com.br/PalestraVisao2016/palestras/palestra1de3aki.html</a></p>

<p></p>

<p>Bom proveito e grande abra&ccedil;o!</p>

<p>Augusto Aki</p>

<p></p>
</body>
</html>

**Comment by beetosantos** [comment]
<body>
<p>Ol&aacute; <strong contenteditable="false" data-token="{leadfield=firstname}">**First Name**</strong></p>

<p>obrigado por seu interesse em assistir a minha palestra sobre &quot;Cen&aacute;rios de Neg&oacute;cios em 2016-2018&quot;. Isto para quem trabalha ou quer trabalhar profissionalmente com flores e plantas.&nbsp;</p>

<p>Voc&ecirc; que ver&aacute; que esta palestra foi a primeira que apresentei nesta ano para meus clientes de um servi&ccedil;o pago chamado &quot;Clube do Empres&aacute;rio de Sucesso&quot; e agora voc&ecirc; ter&aacute; acesso gratuitamente.</p>

<p>Dividi a palestra em 3(tr&ecirc;s) pequenos blocos, assim voc&ecirc; pode assistir, anotar e&nbsp;analisar a aplica&ccedil;&atilde;o para a realidade do seu neg&oacute;cio com toda a calma.</p>

<p>Entre um bloco e outro vou te pedir um favor: que compartilhe no Facebook um an&uacute;ncio desta palestra gratuita para que outros colegas seus com o mesmo n&iacute;vel de vis&atilde;o tamb&eacute;m tenham a chance de assistir. &Eacute; tudo muito simples e voc&ecirc; resolve com um click.</p>

<p>Vamos ent&atilde;o para o primeiro bloco, acesse:</p>

<p></p>

<p><a href="http://www.clubedoempresariodesucesso.com.br/PalestraVisao2016/palestras/palestra1de3aki.html">http://www.clubedoempresariodesucesso.com.br/PalestraVisao2016/palestras/palestra1de3aki.html</a></p>

<p></p>

**Comment by beetosantos** [comment]
GitHub processes HTML, so I insert the character "#"

<#p><#a href="http://www.clubedoempresariodesucesso.com.br/PalestraVisao2016/palestras/palestra1de3aki.html">http://www.clubedoempresariodesucesso.com.br/PalestraVisao2016/palestras/palestra1de3aki.html<#/a><#/p>

I'm testing to see if it solves.

**Comment by escopecz** [comment]
I updated the formatting of your comments so the HTML would be visible. You can read more about the markdown formatting at https://guides.github.com/features/mastering-markdown/

**Comment by beetosantos** [comment]
Thank escopecz, problem solved, it sufficed to include the "href" tag on the links and not only the URL
