### ISSUE TITLE
issue after upgrade

### ISSUE THREAD

**Issue by iclployalty** [mautic/mautic#1805]
## Description

I did the upgrade to 1.4 then found a issue which I fix using github, however this is the next one that has come up and can't find any references anywhere

Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /home/myhostname/public_html/ma/app/bundles/LeadBundle/Controller/LeadController.php on line 363

## Steps to reproduce
As mention this happened after the upgrade

**Comment by slio** [comment]
https://github.com/mautic/mautic/pull/1802

This solved it for me. Don't forget to update schema by going to https://yourdomain.net/mautic/s/update/schema and clicked the Update Schema link.
