### ISSUE TITLE
Email provider with bounce handling

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#1807]
I'm currently using Microsoft Exchange which is not supporting disposable plus email adresses. So exchange accepts server@example.com but not server+bounce_abc123@example.com. Thus I'm running into problems handling bounces. I do know services like postmark offer inbox monitoring bounce handling.

- Can anyone recommend an email provider which supports bounce handling in mautic through the send service?
- Does mautic support bounce handling through the email service and not the inbox?
- Is there any other way to setup bounce handling with exchange?

**Comment by altomarketing** [comment]
I suggest sendgrid or mailgun .

**Comment by afilp** [comment]
Does mautic support mailgun? From other posts I assume not?
