### ISSUE TITLE
Ability to pre-populate lead data in forms

### ISSUE THREAD

**Issue by piuskid** [mautic/mautic#181]
I want to default data into lead forms easily.  Ideally there would be a form field type called lead field where you can then pick a field from the lead including custom fields.

**Comment by alanhartless** [comment]
Hi!

We were just talking about that and have it high priority for 1.1 to improve that process to be pretty much as I interpret what you are asking for.  

The current process is to us the create/modify lead submit action where you can assign the form fields to the lead fields.

Thanks,
Alan

**Comment by dbhurley** [comment]
:+1:

**Comment by piuskid** [comment]
Thanks, however it seems to be broken on custom fields. I have a select list custom field for size - large, medium, small and replicated it on a form.  It is mapped but doesn't make the update.  Standard fields seemed to work.

**Comment by piuskid** [comment]
In a previous solution that i have used, we called them profile fields.  If you picked a profile field, you could determine if it is visible or not, editable or read only and if it was a dropdown (like country) you can display all or a subset.  Thanks!

**Comment by piuskid** [comment]
I was able to get custom field updates working.  I didn't check the update switch.
