### ISSUE TITLE
TypeError: f is not a function in mtc.js line 3

### ISSUE THREAD

**Issue by CrisIf** [mautic/mautic#1810]
Hi, we've upgraded to latest mautic version and trying to use the pagetracking code from Configurations. 
The request response is 200 ok and we get that 1 px image, but still no new Contact registered in the back-end.
I've seen a javascript TypeError: f is not a function in mtc.js, line 3.
Is there something we do wrong?

Thank you for your time, keep up the good job ;)

**Comment by escopecz** [comment]
Check if you don't make a mistake with the testing of the tracking. You have to use a different browser then the one you are logged in:

https://mautic.org/docs/en/pages/troubleshooting.html

**Comment by davidlinc1** [comment]
Hi @escopecz, thanks for popping into this issue. I just recently updated to 1.4.0 and have been attempting to test the Javascript tracking method by executing the tracking code in DevTools (in Incognito).

I'm getting the same error @CrisIf mentioned above, and when I review my Contacts list, I can see that the code does seem to generate a new Anonymous lead - a new lead is created every time I try it, as it seems the IP address isn't getting logged (and of course Mautic couldn't know that it's the same lead without an identifying piece of info).

Just wondering if you happened to have any suggestions offhand? Note that I am still on 1.4.0, not yet on 1.4.1, though I plan on updating it as soon as our sysadmin is back in the office to help me with any hiccups. The tracking pixel method is working great in the meantime.

Thanks! Loving the latest update by the way!

**Comment by chandon** [comment]
Perhaps linked to #1973

**Comment by chandon** [comment]
Check if #1974 correct it ?

**Comment by davidlinc1** [comment]
Unfortunately not, as this error occurred in Chrome for me.

**Comment by davidlinc1** [comment]
After some additional testing, it looks like this error is a direct result of trying to execute the code in the browser console. 

It works when I test via a Codepen, so presumably it will also work when I push it live to my homepage.
