### ISSUE TITLE
base.html.php  does not exist

### ISSUE THREAD

**Issue by adahox** [mautic/mautic#1812]
## Description
i've uploaded the theme but when i click on 'builder' it appers 500 internal error.
on log says: 

> [2016-05-30 17:53:20] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The template ":$template:base.html.php" does not exist." at /home/tutticapelli/www/mkt/app/cache/prod/classes.php line 1095 {"exception":"[object] (InvalidArgumentException(code: 0): The template \":$template: \":$template:base.html.php\" does not exist. at /home/tutticapelli/www/mkt/app/cache/prod/classes.php:1095)"} []

the file base.html.php is there on html folder. what can i do to solve this?

**Comment by escopecz** [comment]
Have you tried to clear the cache?

**Comment by adahox** [comment]
yes. but it still bring me the same problem
