### ISSUE TITLE
Bug:Lead overview doens't show the total points given in the chart. 

### ISSUE THREAD

**Issue by merlin0** [mautic/mautic#1813]
## Description
In the current version 1.4 of Mautic in the lead overview the points that are shown are based of the point tiggers, however these don't match the given points from the point action they just give one point.
Image of the new situation.

![image](https://cloud.githubusercontent.com/assets/12198056/15671093/4334d1e2-2729-11e6-913c-1ea7370db2ef.png)

In the old istance it showed the correct point, in this example in Feb the lead got 7 points and in April the lead got 10 points which are shown correctly in the chart.
![test](https://cloud.githubusercontent.com/assets/12198056/15672393/b24aa53c-2730-11e6-8bed-823413c1fe8a.png)

## Steps to reproduce
Run Mautic 1.4 istance, set a point action with a value more than 1 and let it trigger.
Then go to the lead overview and look at the chart, the chart doens't show the correct point that were given.

**Comment by escopecz** [comment]
This should be fixed in Mautic 2.1.0. Please, comment if not and I'll reopen this issue again.
