### ISSUE TITLE
Bug - Save lead with mandatory field not fulfilled

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1820]
## Description
When you edit a lead with a mandatory field that you leave empty, save, and here nothing happens.

## Steps to reproduce
1. Make as mandatory a field (eg: `title`)
2. Go to developer mode `index_dev.php` in the URL
3. Modify a lead and be sure to leave no value in the field (here `title`)
4. Click on Save and Close
5. Page does not close like if nothing happens. The error message is not displayed.

**To see the error, click on the first button of the symfony toolbar on the bottom of the page.**

![c2](https://cloud.githubusercontent.com/assets/14075239/15712350/50d57542-2812-11e6-9b1e-b13c2ee39f4a.PNG)
![c3](https://cloud.githubusercontent.com/assets/14075239/15712356/55edf0b8-2812-11e6-837f-41b8d223b70d.PNG)

**Comment by escopecz** [comment]
It works for me on Mautic 2.1.0 so I guess it was resolved in the mean time.
![mautic-required-field](https://cloud.githubusercontent.com/assets/1235442/17782290/116950b0-6573-11e6-9cba-051101267ced.png)
