### ISSUE TITLE
Cannot Access Contacts

### ISSUE THREAD

**Issue by tmathiba** [mautic/mautic#1828]

**Comment by escopecz** [comment]
Please post here what error messages do you have in the Mautic logs (app/logs dir) and the server logs.

**Comment by tmathiba** [comment]
I cleared my cache and it solved the problem. I just can't create new contacts from the back-end (although the front-end works) or edit them now.

**Comment by escopecz** [comment]
@tmathiba the error messages in the logs would really, really, really help us find what's wrong.

**Comment by tmathiba** [comment]
I haven't had a chance to look at my logs yet as I've been quite busy running around. One thing I have observed though is that my reports are showing wrong data - the Skype field is showing a date (a custom field I created). So I rushed to the database to check if this was so in the database as well, but not so. The database is showing the right data. On the same report, Owner ID, Owner First Name and Owner Last Name are incorrect. I will check the logs later today.
