### ISSUE TITLE
custom point fields eg. for tracking interest in an product category #featurerequest

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#1831]
Is it possible to add custom point fields?
anyone else thinks this is interesting?

We to have a total points field e.g. 500 which is increasable through tracking pics or campaigns. However I'd love to add custom point counters e.g. for product categories.

points_cars: 100
points_vans: 300
points_suv: 200
points: 600

**Comment by bloodlynx** [comment]
+1 This would be great esp if you have multiple campaigns running.

**Comment by that0n3guy** [comment]
I think this is a duplicate of: #581
