### ISSUE TITLE
can't creat email template

### ISSUE THREAD

**Issue by hamzahmidi** [mautic/mautic#1834]
## Description
fresh installation in http://mautic.smack7b.org/  i cannot creat email template
## Steps to reproduce
i goto channels > emails > new > segment template > i fill the necessary > save and close and it hangs in there and show me again the choos witch template type you want

**Comment by escopecz** [comment]
Please provide content of the Mautic (in app/logs dir) or the server log.

**Comment by hamzahmidi** [comment]
Mautic Logs :
 [2016-06-07 11:17:26] mautic.WARNING: IP LOOKUP: The file "/home/hmidi4042839/public_html/mautic/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []
[2016-06-07 12:06:04] mautic.ERROR: Fatal: Module 'intl' already loaded - in file Unknown - at line 0 [] []

**Comment by escopecz** [comment]
1. Go to Mautic configuration and under the IP lookup section click to download the IP lookup library.
2. Install intl PHP module. Contact your server provider if you don't know how to do so.
3. Let us know if 1. and 2. solved the problem.

**Comment by hamzahmidi** [comment]
1- my hosting planning have No cronJob and I didn's set them any alternative ?



2- lookupIP and intl didn't solve it and here is the LOG
[2016-06-13 08:27:54] mautic.ERROR: Fatal: Module 'intl' already loaded - in file Unknown - at line 0

**Comment by escopecz** [comment]
I'm not sure from your answers if
1. You've downloaded the IP lookup library. No cron jobs needs to be configured for it.
2. Is the intl module installed or not? If so, why the log still says it is missing?

**Comment by hamzahmidi** [comment]
You've downloaded the IP lookup library is downloaded and the intl is installed as the Hosting provider said and also the error don't say it's missing  Fatal: Module 'intl' already loaded

**Comment by escopecz** [comment]
Is this still an issue with 2.0.1?

**Comment by escopecz** [comment]
Closing for lack of feedback.
