### ISSUE TITLE
Problem uploading some images.... 

### ISSUE THREAD

**Issue by vihuarar** [mautic/mautic#1837]
Sometimes when we upload images via the WYSIWYG Mautic changes the width of the image... reducing the width

## Steps to reproduce
1. Create a newsletter... 
2. Upload the images that I attach in this ticket... (via WYSIWYG)
3. You will see that both images before upload them have a width of 600px 
4. but when you upload them.... mautic reduce the size of the image: Boletin-Externo-No_01.jpg

Size before upload them:
Boletin-Externo-No_01.jpg: 600x1184px
Boletin-Externo-No_02.jpg: 600x1048px

size after upload them:
Boletin-Externo-No_01.jpg: 519x1024px
Boletin-Externo-No_01.jpg: 586x 1024px

Like you can see... the size was changed... and now both images has a different width... why? we are just uploading images.... its nice that mautic optimized them... but I think is not good that mautic change is size...

![boletin-externo-no_01](https://cloud.githubusercontent.com/assets/1976384/15859377/8e98049a-2c8a-11e6-9daa-d96dddbdd5d0.jpg)
![boletin-externo-no_02](https://cloud.githubusercontent.com/assets/1976384/15859378/8e98fe4a-2c8a-11e6-94fc-8a4e4fe9097f.jpg)

**Comment by vihuarar** [comment]
this is a newsletter... we need that both images have the same width... but mautic changed it without asking us if we want to change the size....

**Comment by vihuarar** [comment]
Hi!
There is somebody there?
somebody help me please!

**Comment by escopecz** [comment]
@vihuarar the image width and height issue should be fixed by https://github.com/mautic/mautic/pull/2032
