### ISSUE TITLE
js tracking lib documentation?

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#1838]
Just being curious there the documentation for the new js tracking lib is located?

I'm trying to figure out how to set fields like email, name, ... through the lib but cannot find any documentation :(

**Comment by manuelfink** [comment]
Found it in only in release notes https://github.com/mautic/mautic/releases but not in documentation. May add this to documentation as well as developer docs @escopecz?

**Comment by kuzmany** [comment]
https://mautic.org/docs/en/contacts/contact_monitoring.html
