### ISSUE TITLE
UI - IP address in search bar

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1841]
## Description

You have a great and powerful search bar in the contact page.
Unfortunately you cannot search by IP address.
![capture d ecran 2016-06-08 a 11 20 30](https://cloud.githubusercontent.com/assets/14075239/15889315/0c8f0520-2d6b-11e6-9275-32388df4a52d.png)
## Steps to reproduce
1. Go to Contacts
2. Paste an IP Address from the Anonymous list
3. See that the result is not displayed.

![capture d ecran 2016-06-08 a 11 17 55](https://cloud.githubusercontent.com/assets/14075239/15889280/d3f640a2-2d6a-11e6-8607-99f1e6135025.png)
![capture d ecran 2016-06-08 a 11 20 17](https://cloud.githubusercontent.com/assets/14075239/15889353/32b2fa04-2d6b-11e6-92c2-7e5495208c65.png)
![capture d ecran 2016-06-08 a 11 18 08](https://cloud.githubusercontent.com/assets/14075239/15889278/d3f49266-2d6a-11e6-9644-cb168672a55d.png)
![capture d ecran 2016-06-08 a 11 18 19](https://cloud.githubusercontent.com/assets/14075239/15889279/d3f4ddca-2d6a-11e6-9f86-28228603d011.png)

**Comment by mtahiue** [comment]
@alanhartless it seems that this commit could solve this issue : https://github.com/alanhartless/mautic/commit/2a0e8936dd9652f9ca50712b1ac84692c3bb5261 would be great if it was merged in mautic 2.6 ? ;-)
