### ISSUE TITLE
List of required PHP modules

### ISSUE THREAD

**Issue by tomgoldsmith** [mautic/mautic#1844]
Would it be possible for someone to create a list of required PHP modules?

I just had to spend some time debugging a problem when trying to set up Mandrill as I did not have php5-curl installed. 

Thanks!

**Comment by MxyzptlkFishStix** [comment]
Look in app/bundles/InstallBundle/Configurator/Step/CheckStep.php.

**Comment by tomgoldsmith** [comment]
Thanks @MxyzptlkFishStix, I cant seem to spot php5-curl in there so looks like that is one that could be added.

**Comment by paulocoghi** [comment]
The requirements listed in [mautic.org/download/requirements](https://www.mautic.org/download/requirements/) don't mention PHP modules.

With PHP 7.0, for example, many servers don't come with `php7.0-xml`, `php7.0-mcrypt` and `php7.0-curl` installed (i.e. **fpm**).

Without them, Mautic doesn't work properly (in my case, without `php7.0-xml` I was completely unable to load it).

**Comment by StoppingBuck** [comment]
@RCheesley Perhaps this one should be re-opened and moved to the Documentation Team? When installing a new Mautic, the PHP modules are listed during the setup, but it would still be nice to have them mentioned somewhere in the documentation :)

**Comment by RCheesley** [comment]
Ok could you create an issue over there on the repo? https://github.com/mautic/mautic-documentation

**Comment by StoppingBuck** [comment]
@RCheesley [Done](https://github.com/mautic/mautic-documentation/issues/89) :)
