### ISSUE TITLE
X_FORWARDED_FOR logic is backwards

### ISSUE THREAD

**Issue by andrewcurioso** [mautic/mautic#1845]
## Description
The code grabs the last item in the list for the `X_FORWARDED_FOR` however in cases of multiple proxies, this value is actually the most recent proxy in the chain.

## Steps to reproduce
1. Put a Mautic install behind multiple proxies
2. Go to a page that has the tracking pixel
3. The Lead will have the IP of the last proxy in the chain instead of the customer

## See
https://en.wikipedia.org/wiki/X-Forwarded-For
```
X-Forwarded-For: client, proxy1, proxy2
```
Mautic will grab proxy2 which is not the actual customer.

**Comment by andrewcurioso** [comment]
@alanhartless  Thank you

**Comment by lvnilesh** [comment]
Using 2.11.0 and sitting behind traefik proxy which forwards `X_FORWARDED_FOR` but I notice Mautic will grab traefik_ip which is not the actual customer_ip. 

In our WordPress deployments, we handle it by adding this snippet to `wp-config.php`. 

     if ( isset( $_SERVER['HTTP_X_FORWARDED_FOR'] ) ) {
      $http_x_headers = explode( ',', $_SERVER['HTTP_X_FORWARDED_FOR'] );
      $_SERVER['REMOTE_ADDR'] = $http_x_headers[0];
     }

I am new to using Mautic. Appreciate if you can please advise how to handle `X_FORWARDED_FOR` so Mautic tracks the customer_ip not the traefik_proxy_ip

**Comment by MxyzptlkFishStix** [comment]
I think you have to add the IP address of the proxy in the Trusted Proxies field in the Configuration section.

**Comment by lvnilesh** [comment]
The Traefik proxy runs in another container so that IP is dynamic unfortunately.

**Comment by akarasulu** [comment]
@Ivnilesh ever get this sorted out? I need the same thing for mautic that I do here for wp:

```php
          if ( $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https' )
          {
                $_SERVER['HTTPS']       = 'on';  
                        $_SERVER['SERVER_PORT'] = '443';
                        define('FORCE_SSL_ADMIN', true);
          }
          if ( isset($_SERVER['HTTP_X_FORWARDED_HOST'])) {
                $_SERVER['HTTP_HOST'] = $_SERVER['HTTP_X_FORWARDED_HOST'];
          }
```
