### ISSUE TITLE
Bug - Save edition of select field not efficient

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1847]
## Description
When you edit a select contact field and save it. It does not correctly save and close (you stay on the page) and the change are not applied. If you comeback on the custom field list, the field still has the same name.

I don't know if it's linked to https://github.com/mautic/mautic/pull/1733 but this PR does not correct the bug.
 
## Steps to reproduce
1. Go to Custom field
2. Edit `Company` field
3. Rename it
4. Save and close
5. Notice the page does not close (bug 1)
6. Go back to custom fields list
7. Notice the fiels has not been renamed (bug 2)

![dcq8mc5k7y](https://cloud.githubusercontent.com/assets/14075239/15923365/28db0284-2e2d-11e6-9f15-3df666409edc.gif)

**Comment by escopecz** [comment]
Tested on Mautic 2.1.0 and the Company field got renamed without any error:
![mautic-company-renamed](https://cloud.githubusercontent.com/assets/1235442/17737679/703cd660-648e-11e6-8731-1c2a05fa0055.png)
