### ISSUE TITLE
Add validation to the Mautic Base URL field in the configuration

### ISSUE THREAD

**Issue by tomgoldsmith** [mautic/mautic#1848]
## Description

We noticed that emails send out via campaigns were being overwritten with the correct tracking token but the incorrect site url. On further investigation this was because the site url we added to the system settings page did not include `https://` . 

When this was corrected to a fully qualified site URL the problem was rectified. 
## Steps to reproduce
1. Edit system settings to include site url without `https://` 
2. Send email out via a campaign (not the test function as this does not reproduce the error)
3. View email links and see that they will be set to localhost/r/XXX

**Comment by escopecz** [comment]
I don't think if this is a bug, but the Site URL was just filled badly. I'll close it now, but if you consider it a bug, please suggest a solution how to solve it.

**Comment by tomgoldsmith** [comment]
The solution would be to either:
1. State that the field requires a fully qualified domain name.
2. Add validation to the form to check that it is set correctly. 
3. Add the https/https section if it is not present. 

My personal preference would be option 2. Hope that helps.
