### ISSUE TITLE
Issue creating API signature

### ISSUE THREAD

**Issue by squeral** [mautic/mautic#1849]
Your documentation suggests [here](https://developer.mautic.org/?json#generating-the-authorization-header) that _oauth_callback_ should be double encoded but that did not work for me.

I'm building a Python client and _oauth_callback_ could not be encoded when creating the signature although it should be when adding it to the _Authorization_ header.

I hope this info helps some else working with Mautic's API.

**Comment by escopecz** [comment]
Could you please send the fix to the dev docs yourself? If not, please, report this issue to the dev docs repository.

https://github.com/mautic/developer-documentation

I'll close this issue because it's in a wrong repository.
