### ISSUE TITLE
Bug - Rename segment filter "Email received" to "Email open"

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1851]
## Description
It would be great to be able to segment from **"did / did not" open an email**.
Same feature as it has been done here https://github.com/mautic/mautic/pull/1237 for email received.

**Comment by kuzmany** [comment]
Already added in 1.4 

See release notes

https://github.com/mautic/mautic/releases/tag/1.4.0

**Comment by npracht** [comment]
hi @kuzmany it's a mistake. You don't have the filter. The filter is about "email received" not opened.

**Comment by kuzmany** [comment]
It's the same, isn't it?

**Comment by npracht** [comment]
I hope no. There is different steps in email routing:

- Sent
- Received
- Opened
- Clicked
- Bounced
- Unsubscribed

**Comment by kuzmany** [comment]
This filter - Received = Opened

**Comment by tomgoldsmith** [comment]
Is this not the decision for open email in the campaign builder?

**Comment by kuzmany** [comment]
@tomgoldsmith No, we are talking about this PR  #1198

**Comment by npracht** [comment]
Then I'll simply rename the issue to bug to rename the filter.
Thanks,

N.

**Comment by patmifsud** [comment]
Experiencing this also.
