### ISSUE TITLE
Error 500 when trying to access import page

### ISSUE THREAD

**Issue by andrelug** [mautic/mautic#1854]
## Description
Hi,

I was importing a few lists and all was alright, but then I imported a 270 leads list exported from mailchimp and didn't import. I cancel and tried a few times. The last time I couldn't access the import page anymore.

I'm getting this error:

`[2016-06-11 01:33:08] mautic.WARNING: PHP Warning: require(/opt/bitnami/apps/mautic/cache/prod/doctrine/orm/Proxies/__CG__MauticLeadBundleEntityLead.php): failed to open stream: No such file or directory - in file /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 207 [] []
[2016-06-11 01:33:08] mautic.ERROR: Fatal: require(): Failed opening required '/opt/bitnami/apps/mautic/cache/prod/doctrine/orm/Proxies/__CG__MauticLeadBundleEntityLead.php' (include_path='.:/opt/bitnami/php/lib/php') - in file /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 207 [] []`

When I checked, 4 leads were added to the segment from this list. I deleted them. Then I tried to click on the import button again and no luck. I refreshed the page and the 4 exact leads were added again to the segment. I tried a few times this process with the same result. Then I deleted the segment and added it again and it stoped. But no luck with the import page.

System info:
php 5.6.18
mautic 1.4.1
Bitnami installation

**Comment by escopecz** [comment]
Try to clear the Mautic cache. (just delete the content of the app/cache directory)

**Comment by andrelug** [comment]
It Worked! Thank you.
