### ISSUE TITLE
Applying category filter in campaign search fails

### ISSUE THREAD

**Issue by SikhNerd** [mautic/mautic#1858]
## Description

Search fails with following error:

```[2016-06-10 23:45:46] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 98 near 'alias LIKE :isUdcIWx': Error: Class Mautic\CampaignBundle\Entity\Campaign has no field or association named alias” at /path/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 98 near 'alias LIKE :isUdcIWx': Error: Class Mautic\\CampaignBundle\\Entity\\Campaign has no field or association named alias at /path/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT c, cat FROM MauticCampaignBundle:Campaign c INDEX BY c.id LEFT JOIN c.category cat WHERE c.alias LIKE :isUdcIWx ORDER BY c.name ASC at /var/www/html/m/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []``` 

@alanhartless in slack:

>Based on that error, definitely a bug specific to campaigns and categories due to both campaigns and categories tables using the same column alias (`c`) for the category search. 

## Steps to reproduce

In Campaigns, attempt to search for "campaign: thing".

**Comment by alanhartless** [comment]
Fixed in #2310
