### ISSUE TITLE
Mautic Api redirect_uri_mismatch if the redirect uri contains &

### ISSUE THREAD

**Issue by nilay-automatesmb** [mautic/mautic#1859]
## Description

our redirect url has been stored as:

<domain>/index.php?module=Mautic&parent=Settings&operation=gettoken

the same is passed through the callback parameter when using Oauth.

But mautic keeps on throwing redirect_uri_mismatch exception. Upon logging the redirect uri foound out that the uri used for comparison (storeduri) is coming up as

index.php?module=Mautic& #38;parent=Settings& #38;operation=gettoken

**Comment by nilay-automatesmb** [comment]
On further investigation found out that the redirect_uri is stored as <domain>index.php?module=Mautic& #38;parent=Settings&#38;operation=gettoken& #38;action=Save in database.

all & are being stored as & #38;

**Comment by escopecz** [comment]
This should be fixed in Mautic 2.1.0. Please, comment if not. I'll open this issue again.

**Comment by naomicbush** [comment]
This is still occurring in 2.2.0

**Comment by hermesmarcom** [comment]
I installed mautic v2.8.2 on mautic.mydomain.com:8080, either using OAuth 1 or 2, I cannot connect the API with ThriveThemes Wordpress Plugin (ThriveThemes has built in API connection feature for Mautic). 
There are three parameters to fill for the connection:
> API URL
> Public key
> Secret key
I check my server error log and it addressed "redirect_uri_mismatch" error. I both tried "mautic.mydomain.com:8080" and "mautic.mydomain.com" for API URL but nothing worked. 
Any suggestion? Thanks in advance!
