### ISSUE TITLE
Tracking code will not work on single page web apps

### ISSUE THREAD

**Issue by tomgoldsmith** [mautic/mautic#1861]
## Description
I run a web site on Angular and consequently the pixel will not be reloaded when the user changes pages. I know Facebook also used to have this issue and subsequently upgraded their tracking code.

## Steps to reproduce

Load Mautic tracking to Angular based site, observer network tab to see that only one request is fired.

**Comment by dbhurley** [comment]
Thanks for pointing this out. We'll have to dig into how to fire that javascript on every request within a single page app.

**Comment by tomgoldsmith** [comment]
No problem, I have actually created an [angulartics](https://github.com/angulartics/angulartics) plugin for Mautic which is the tool of choice for most Angular users when working with analytics but I realised that because of the nature of the pixel tracking it would not work. 

If you can find a way to change this behaviour I would be happy to publish that plugin as well so that Angular users have a very easy way to get Mautic up and running.

**Comment by dbhurley** [comment]
Awesome! Thanks for the feedback. I'll let you know when we get a solution and then you can help us spread the goodness.

**Comment by alanhartless** [comment]
Does the Javascript tracking feature introduced in 2.0 help with this?

https://mautic.org/docs/en/contacts/contact_monitoring.html#javascript-js-tracking

**Comment by alanhartless** [comment]
Sorry - I'm assuming that the pixel was used directly rather than the JS tracking with `mt()`. I'm not that familiar with Angular. Let me know if my question is not applicable :-)

**Comment by alanhartless** [comment]
Any suggestions on how to address this?

**Comment by namratasaun** [comment]
So, I gave to call mt("send", "pageview") on every page
