### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ivintage** [mautic/mautic#1862]
## Description

when i excute the step 3: open localhost/mautic，then i get the error， localhost/mautic/index.php/installer 404 not found。is there missing some config？

**Comment by escopecz** [comment]
Make sure that .htaccess is enabled. If you are not sure about how to do that, contact your server provider/administrator. Mautic should not need to run in a `/index.php/` route. This is usually caused by disabled .htaccess file.

**Comment by ivintage** [comment]
o, The web server is Nginx. I will check .
