### ISSUE TITLE
Importing boolean values

### ISSUE THREAD

**Issue by tomgoldsmith** [mautic/mautic#1863]
## Description
When importing files with boolean values, what is the expected format in the csv data? I used "TRUE" but this appeared to overwrite the field with the string value "TRUE". 

## Steps to reproduce

1. Create boolean custom field 
2. Create csv file for import with boolean fields set to "TRUE" 
3. Import csv and match to new custom field
4. View in contact editor

**Comment by escopecz** [comment]
Have you tried 0 for false and 1 for true?

**Comment by tomgoldsmith** [comment]
Yes, I can confirm that works fine. The only further comment I have is that when you go into the additional details view it shows as 1 and then when you edit it says yes or no. It would be great if that got through to the additional details view as well. 

P.S Thank you very much for Mautic it's a fantastic tool, I would offer to help out with creating some pull requests if my php was not so bad!

**Comment by manuelfink** [comment]
I run yesterday into the same issue. Not yet sure how mautic fully behaves. I ended up using the custom lable for importing since neither 0 or true somehow worked. 

I'd suggest the importer to recognice all: true, TRUE,1,yes and also a custom lable for yes. Same for no
