### ISSUE TITLE
Invalid data should respond with some description

### ISSUE THREAD

**Issue by squeral** [mautic/mautic#1864]
## Description
I'm getting a bad request (400) when creating a lead through the API and the JSON response is empty.

## Steps to reproduce
A Python test request:
`requests.put('/api/leads/0/edit?access_token=abc...', data={
        'firstname': 'Fake1',
        'email': 'fake@gmail.com',
        'country': 'United Kingdom',
        'phone': '123456789',
        'referrer': '',
    })`

Because "referrer" is an empty string I get a Bad Request (400) with "{}" in the body.
It would be great to at least have a message saying something like "Invalid data".

Ref: https://github.com/mautic/api-library/issues/27

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/2142. Please retest with Mautic 2.1.0. If there is still a problem, let us know and I'll reopen the issue.
