### ISSUE TITLE
Contact list segement filtering not working

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#1871]
## Description
Contact list segment filtering is not working and instead showing all contacts

## Steps to reproduce
1. go to segements
2. click on x contacts of a list (eg. http://www.path-to-mautic/s/contacts?search=Segment%3Amyawsomesegment)
3. you end on contact lists which shows all contacs, instead of a filtered list

**Comment by escopecz** [comment]
Is this an issue still on Mautic 2.0.1? I cannot replicate it.
