### ISSUE TITLE
Contact segment doesn't update by the boolean value

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#1872]
## Description
I added a knew segments which is not assigning contacts thorugh mautic:segments:update. Not sure where the problem comes from though :(

1. added new custom field newsletter (Boolean) with default true/yes
2. changed some contacts manually to yes and others to no
3. added a new segment with rule newsletter equals yes
4. run cronjob manually php app/console mautic:segments:update just to be sure, which results in 0 added, 0 removed contacts, no error.

What do I have to do, that segements automatically update through filters?

**Comment by alanhartless** [comment]
I'm unable to replicate this in the latest version. If you're still able to replicate it, let us know and we'll investigate further. 

The default value doesn't affect existing contacts - so these wouldn't be included in the segment if they haven't been updated.

**Comment by chen-levkovich** [comment]
Still get this bug for boolean fields 2.6.1

**Comment by officialsuyogdixit** [comment]
Still getting the same problem on 4.1.1
