### ISSUE TITLE
Disable Link tracking in Text Message

### ISSUE THREAD

**Issue by davkap92** [mautic/mautic#1873]
Hi,
New text message feature is great thanks. Noticed that
links are automatically converted to tracking links, which in the case of an sms may not be ideal.
Is there a way to disable this for sms or some sort of inline argument?

Many thanks

**Comment by alanhartless** [comment]
I don't think there is but will add this as a feature request!

**Comment by j-ki** [comment]
Has there been any progress on this?

SMS costs per 160 characters. The Mautic tracking link is something like 300 characters, all by itself. This almost triples or quadruples the cost per text message.

**Comment by fashiontalent** [comment]
An automatic  URL shortener maybe instead of disabling link tracking?

**Comment by mandadimuralidharreddy** [comment]
I am not able to find any Link tracking in Text Message.Can anyone please tell me how to use this feature.

**Comment by itcig** [comment]
Was this feature ever added?  We're running into the same problem with Twilio, paying 2x for each text message b/c it is over the character limit.

**Comment by kuzmany** [comment]
Already PR exist https://github.com/mautic/mautic/pull/5728 
Just need unit test
Can you test?
