### ISSUE TITLE
Import not merging based on custom fields that have been set as unique identifiers

### ISSUE THREAD

**Issue by tomgoldsmith** [mautic/mautic#1875]
## Description

I am able to upload multiple contacts with the same custom field which has been set to a unique identifier and they do not merge. 

Not sure I have misunderstood this feature or there is a cron job that does it which I am not running, but I expected it to merge when the custom field has been set as a unique identifier. 

## Steps to reproduce

1. Create custom field and set unique identifier to true
2. Create contact with custom field set
3. Upload contact with custom field set to the identical to the contact you just created

**Comment by npracht** [comment]
Do you import at the same time another field which is unique identifier (like email for instance)? Any chance that in this one there is different values that would create a conflict with the other unique identifier?

**Comment by alanhartless** [comment]
Due to lack of feedback, we're closing this issue. Please upgrade to 2.1.1 and if the issue persist, definitely let us know! Thanks!
