### ISSUE TITLE
Bug - Wrong day stat on widget

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1878]
## Description
If you check your stats per day on the widgets, there is a time error of 1 day between what is displayed and what is really the case.
#### In the email stats
![capture d ecran 2016-06-15 a 12 21 59](https://cloud.githubusercontent.com/assets/14075239/16108420/4701fd28-33a3-11e6-8d8d-539fc3dff49e.png)
#### In the widget
![capture d ecran 2016-06-15 a 12 22 15](https://cloud.githubusercontent.com/assets/14075239/16108419/4700ad42-33a3-11e6-8b31-a0ba36df4ff3.png)

## Steps to reproduce

1. Send email
2. Check stats on email
3. Check stats on widget
4. Compare :-)

**Comment by escopecz** [comment]
Fixed in 2.1.0
