### ISSUE TITLE
No error message on empty required textareas in Mautic forms

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#1879]
## Description
We have a little problem with the Mautic forms.
If you set a text area to be mandatory, for some reason, the error message won't display if the user doesn't fill that field.
It appears to just stay in `display: none;`

## Steps to reproduce
1. Create a Mautic form with a required textarea and preview it
2. Submit the form without filling the textarea
3. See that the error message is still hidden

**Comment by MaxWebmecanik** [comment]
Ok, nevermind that.
It turns out that the validator wasn't working because the label was named "message" which is apparently used by the validators.

**Comment by npracht** [comment]
Hi @MaxWebmecanik,
Any commit to propose to avoid that issue ?

N.

**Comment by MaxWebmecanik** [comment]
Not so far no... We won't be focusing on that issue as of now, but we'll be happy to help anyone willing to fix this.
