### ISSUE TITLE
Feature request - Ability to view email contact clickers

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#1883]
## Description

On the email overview page, you have the list of link, for all of them you have:
- Clicks
- Unique clicks
  It would be great to add the ability to see all **contacts that are actually the unique clickers**.

\+ add a sum of all clicks
## Recommendation

I see 2 options:
1. Add **a link on the number of unique clicks** that'll bring the user to the contact list page with an adapted filter.
2. Add a new column on that email links tab: **View contacts**. That'd also bring to the contact list page.
![capture d ecran 2016-06-17 a 07 26 20](https://cloud.githubusercontent.com/assets/14075239/16141650/42facbea-345e-11e6-91b8-868e83594ca8.png)

**Comment by vaibhav306** [comment]
Hello
Please help for email external link, i have use custom source html and use social page link but it comes in mail with my mautic url and not redirect and give me 404 error.

**Comment by nickian** [comment]
I totally agree with this. The click stats are almost useless if you can't see who clicked what. It would be great if we could drill down into a specific link and see who clicked on it, as well as be able to see all of the links a specific contact clicked on a particular email campaign.

**Comment by nickian** [comment]
I tried piecing this together manually with an SQL query, but I can't make sense of the database structure between the email_stats, channel_url_trackables, and page_redirects tables. I might be wrong, but it appears the database structure would have to change to accomplish this. I was expecting to find a simple clicks table with Lead IDs and URL IDs to grab.

**Comment by sambarnes90** [comment]
+1 on this. 

I've been using campaigns to add a tag to users who hit a url with query strings (which I set in the email).

That at least helps me modify the campaign based on who has hit certain URLs after receiving an email but it's by no means foolproof. 

This would be a very useful addition.

**Comment by ctothill** [comment]
I am actually shocked that this doesn't already exist.  Seems like basic functionality that has been in EMS systems for a long time.

Please seriously consider adding this sooner rather than later.

Thanks!

**Comment by npracht** [comment]
# Up !
After this great PR https://github.com/mautic/mautic/pull/4576#event-1195570820 i think the work left is not that much...

It would be very great, we know that when it is left aside it often get forgotten :-)

And you also may know that clickers are the hottest leads and consenquently much mor important for a marketer than the sent 👼

**Comment by khaoua** [comment]
Feature request -Ability to have email stat on who replied to an email #4877

**Comment by LEAP-nishit** [comment]
@dbhurley we are looking to support development for this issue and noticed you had tagged it WIP. In the interest of avoiding duplication of work can you please let us know if this is be developed. Would allow us to fund other mautic feature requests that aligns with our more urgent requirements.

**Comment by kuzmany** [comment]
@dbhurley Can I work on it? Or somebody from your team already working on it?

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Lets test: https://github.com/mautic/mautic/pull/5849
