### ISSUE TITLE
php warning getting email - bad message number #bug

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#1885]
## Description
I'm using gmail for fetching undeliverable messages. The gmail account is only used for bounce handling, thus no emails are deleted. However mautic seems not to bea be able to fetch the mail:

```
PHP Warning:  imap_fetchheader(): Bad message number in /var/www/vhosts/example.com/httpdocs/ma/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 716
PHP Notice:  Undefined property: stdClass::$from in /var/www/vhosts/example.com/httpdocs/ma/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 724
PHP Notice:  Trying to get property of non-object in /var/www/vhosts/example.com/httpdocs/ma/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 724
PHP Notice:  Undefined property: stdClass::$from in /var/www/vhosts/example.com/httpdocs/ma/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 724
PHP Notice:  Trying to get property of non-object in /var/www/vhosts/example.com/httpdocs/ma/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 724
```

The warnings and follow up noticed may be avoided by handling the imap_fetchheaders more probably. 

However it seems to be weird that the message is not gettable?!

Is this a gmail issue?

**Comment by escopecz** [comment]
@manuelfink do you have this issue even with Mautic 2.1.0?

**Comment by alanhartless** [comment]
Due to lack of feedback, we are closing this issue. Please upgrade to 2.1.1 and if the issue persists, let us know! Thanks!
