### ISSUE TITLE
Error: "Segmentation fault (core dumped)" in cron #bug

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#1886]
## Description
My cronjobs updating segments ends with ends with the message:

```
Segmentation fault (core dumped)
```

No exception, no line number, nothing in error logs.

What does this message mean?

**Comment by TiagoRodrigues** [comment]
Got the same msg on my Campaing Trigger log
Segmentation fault (core dumped)

**Comment by escopecz** [comment]
> "Segmentation fault" means that you tried to access memory that you do not have access to.

_(http://stackoverflow.com/questions/19641597/what-is-segmentation-fault-core-dumped)_

The output was probably longer than some of your PHP limit allowe. Check this advice if it helps and let us know, please:
http://stackoverflow.com/questions/15714909/php-what-does-segmentation-fault-core-dumped-error-means

**Comment by alanhartless** [comment]
Due to lack of feedback, we are closing this issue. Please upgrade to 2.1.1 and if the issue persists, let us know! Thanks!
