### ISSUE TITLE
My External Link is not working in email.

### ISSUE THREAD

**Issue by vaibhav306** [mautic/mautic#1887]
## Description
I have use simple html and give link on facebook image to my facebook page but it not working the link is change and give me 404 error, please help me i want only working link not be trackable.

**Comment by escopecz** [comment]
Could you please insert the link as you pasted it to your email and how the link looks like when the email is delivered? Especially the URL of it.

**Comment by alanhartless** [comment]
Due to lack of feedback, we are closing this issue. Please upgrade to 2.1.1 and if the issue persists, let us know! Thanks!
