### ISSUE TITLE
Configurable transport for sending emails on behalf of Owner

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#1889]
## Description

Follow-up of https://github.com/mautic/mautic/pull/1319#issuecomment-224569388 and https://github.com/mautic/mautic/issues/1613#issuecomment-226851413 .
The problem is that emails are sent nominally from Owners but in fact using the same email transport. It could cause troubles with deliverability as these emails could be considered as spam because of failed DKIM and SPF verification.
## Proposed solution
- [ ] Create a role Owner
- [ ] Assign it to corresponding user at the moment when he/she is chosen as somebody's Owner
- [ ] For users of this role add a section to user settings, which is very much similar to Email settings (SMTP configuration; From, Bounce & FBL (Feedback Loop) email settings)
- [x] At the moment of sending emails to contacts of this Owner, use these settings, if none - default to system Email settings (fixed by #2039)

Or, probably, it would be better to introduce new entity Site (or Domain), which is intended to aggregate all of the site-wide settings (including Email settings). In this case Owner should be a Site instead of a user.

**Comment by geospatialmedia** [comment]
I would like to bring the example of the email marketing service elasticemail.com here. Here when we are sending emails from multiple domains, we create different sub-accounts.

I think this is a good feature - https://elasticemail.com/support/account-setup/sub-accounts
One Main account to manage sub accounts
Sub-accounts - as many as the domains from which you want to send emails. info@produc1.com, info@product2.com, info@support1.com are the multiple domains or even info@produc1.com, marketing@product1.com, support@product1.com are sub-accounts with different from and signature lines.

**Comment by PatchRanger** [comment]
These could help in progress: #2403 together with #2424.
