### ISSUE TITLE
Issue with Landing Page Branding

### ISSUE THREAD

**Issue by piuskid** [mautic/mautic#189]
Hi,
I entered this on the forum, but better to put into an issue so that you can track it back.  

In the landing page designer, I am using Mauve (Or any delivered theme) and I drag my logo into the header.  It shows fine in the page designer even when I come back to the design mode.  In runtime, it doesn't display the logo or doesn't seem to even try to load it (no missing images or references in the runtime html).

I performed similar designer tasks using your email builder and that works fine in runtime.  I would really like to use this product for our store launch, but this bug is a showstopper.  I could write html, but I am not very good at it.

Thanks for the great product btw.  I use Eloqua and have helped design some other professional Marketing Automation tools integrated with CRM and this is a great tool.  I'll log a couple of other low hanging feature requests as well.

**Comment by piuskid** [comment]
Looks like the page builder is having issues with images getting completely ignored.  Raw text seems to work fine but images do not even attempt to be loaded.

**Comment by alanhartless** [comment]
This should now be fixed with https://github.com/mautic/mautic/pull/224.

**Comment by piuskid** [comment]
thanks!  i already installed it.  it seems to work!
