### ISSUE TITLE
Issues with emails' unique identifier settings

### ISSUE THREAD

**Issue by andrelug** [mautic/mautic#1892]
## Description
Hi,

the default for e-mails on Mautic is to have the unique identifier setting enabled, but it's not quite working. I can set as many contacts with the same e-mail and it doesn't merge or prevent me from doing so. This leads to the issue that I can have someone leaving his or her e-mail on two different forms and when I'm about to send a newsletter, this person receives it twice.

The image bellow shows the issue:
http://prntscr.com/bij1qi

I'm running Bitnami's version of Mautic at version 1.4.1.

Thank you! This software is awesome

**Comment by npracht** [comment]
Hi,

From what I know there is only one way to go against this unique ID condition, it is to create manually a contact with an existing email address.
Importing via form, api, csv file, do not create multiples contacts with same email address.

Do you confirm you have created it manually?

N.

**Comment by andrelug** [comment]
Thanks for the response, npracht.

I have also created manually, but I checked as well sending the e-mail through a form created by mautic and it duplicated. I actually discover the problem after having a landing page send me 3 leads with the same e-mail.

**Comment by alanhartless** [comment]
1.4.1 is now quite outdated. Could you please upgrade to 2.1.1 and reopen/let us know if the issue persists?

Thanks,
Alan

**Comment by FarhadF** [comment]
2.1.1 and i can create contact with duplicate emails, I'm testing this in mautic web interface.(manual)
