### ISSUE TITLE
Can't setup / Create a user after update

### ISSUE THREAD

**Issue by sarahgregorio29** [mautic/mautic#1894]
## Description
After updating to c615cf0df47dc00bdd8eb7a418048d1bdc3b3c2c, I can't create a new user so I tried to reinstall everything. But after reinstalling, I'm still getting the same error:
![http://i.imgur.com/hHJLMUc.png](http://i.imgur.com/hHJLMUc.png)

**Comment by escopecz** [comment]
Have you cleared your cache?

I just want to make sure that you understand that you are usin a development version of Mautic. There might be issues like this one. If you want to use Mautic in production, download the production release from https://www.mautic.org/download/. But if you use the dev version to help us test Mautic, then thanks a lot!
