### ISSUE TITLE
Empty Segments

### ISSUE THREAD

**Issue by ramgouveia** [mautic/mautic#1896]
## Steps to reproduce

I have created two segments. Both of them have "No Contacts"

Can you help me solve this problem?

Watiting for your answer.

**Comment by escopecz** [comment]
Could you please be as much descriptive as possible? Have you used some filters in those segments or how do you send the contacts to those segments? Have you configured the cron jobs correctly?

**Comment by ramgouveia** [comment]
I used some filters in those segments.

"Have you configured the cron jobs correctly?" What is "cron jobs"? Can you explain this better? Thank you.

**Comment by escopecz** [comment]
The filters won't work without cron jobs. Read more at https://www.mautic.org/getting-started/.
