### ISSUE TITLE
Lead tags disappear when API runs to update anonymous to known lead

### ISSUE THREAD

**Issue by mackadamian** [mautic/mautic#1897]
On both self hosted and Mautic hosted installations, tagging is working perfectly, using the pixel to track and add a tag to the user when he visits a page in the website. But when the API runs to update a known lead, the tags are removed. Seems to have started after the upgrade to version 1.4.0. 

Same issue as:
https://www.mautic.org/community/index.php/969-issue-with-lead-tags/0#p12351

**Comment by escopecz** [comment]
I tested this and if I send the PUT request, all the fields which have a value but I don't send them in the request are removed. It basically wipes out the contact information and adds the information from the API request.

However, if I use the PATCH request, it overwrites only the field values I sent in the request. Even tags remains there. Does it solve your problem? I'll also update the dev docs to make it more clear.
