### ISSUE TITLE
Voluntary exception monitoring

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#1898]
## Description

Could we start using some service to monitor exceptions of all Mautic installations?
I mean something like [Rollbar](https://rollbar.com/features/) as they do have a free plan. We already use some services that do good for us for free (for example: Github, Codeclimate, Travis-CI) - so it is just another of such.
It could be a voluntary setting in configuration, which is turned off by default - so only those who really wants to support the project this way could opt in.
## Why
- It will help to fix bugs on-the-fly - or even before they ever reported, after the first occurrence. So it will increase the quality of the Mautic.
- It will give us a detailed overview of how the functionality of Mautic works in different environments - again, in real-time. So it could be useful addition for our test coverage.
- It will give an opportunity to get rid of and react in future on lots of annoying weird log messages, which otherwise would be unnoticed. So it will help keeping Mautic codebase stable & preventing serious bugs by monitoring small ones.

What do you think?

**Comment by dongilbert** [comment]
+1
