### ISSUE TITLE
Ability to track link clicks on landing pages and emails with re-opens, revisits, etc..

### ISSUE THREAD

**Issue by piuskid** [mautic/mautic#190]
Hi,

For better analytics and targeting, I want be able to track:
1) If I put a link in an email or landing page, i want to see a summary of the clicks on each link aggregated by page/email and at a lead detail on the page and email BI area and on the Lead as a tab or something.

2) I want to be able to trigger an a action and/or create lead lists based upon the lead clicking on a certain link (could be external link) or by re-opening the email or visiting the page several times.

Sugar CRM's email marketing has a nice feature where I can track the links clicked and how many times they clicked it.  I think I can get the number of times the lead re-opened the email as well.

Thanks!

**Comment by larsmagnusherland** [comment]
It seems that hubspot and infusionsoft also have link tracking and link triggered action.
So would be nice to have them in Mautic as well.
