### ISSUE TITLE
Webhook not getting data 

### ISSUE THREAD

**Issue by pramod1988** [mautic/mautic#1901]
Hello Team,
I am configured mautic web hook and selected event as new contact . But i am not getting any data to provided webhook url, when new contact is created.
Here is the sample code :-

```
 $file = 'people.txt';
// Open the file to get existing content
$current = file_get_contents($file);
// Append a new person to the file
foreach ($_POST as $key => $value)
{
 	$current .= "Field ".htmlspecialchars($key)." is ".htmlspecialchars($value)."<br>";
}
// Write the contents back to the file
file_put_contents($file, $current);
```
Is i am doing anything wrong ?

**Comment by escopecz** [comment]
I tested it not a long time ago and it worked. Try my testing script for logging the webhook requests:

https://gist.github.com/escopecz/0d9adba753300b88326d
