### ISSUE TITLE
Mautic Oauth2.0 doesn't works: Got 403 error

### ISSUE THREAD

**Issue by tigredonorte** [mautic/mautic#1903]
## Description
I trying integrate my sass (startinvestimentos.com) with my mautic instance (learn.startinvestimentos.com). The mautic installation works well, but the integration doesn't works...

## Steps to reproduce
I enter in apitester (https://startinvestimentos.com/vendor/mautic/api-library/apitester/index.php) for test my api:
apikey: 1_5m0dkvqugyw4o0k8c48w4ccw4kkwskss0gkwowkwww4cg04ogc
apisecret: 1g2dhq9806e8cso8ssc4gcsow4k4080o0c4wgwggow48o4wwwk
version: Oauth2
baseurl: http://learn.startinvestimentos.com
callback: https://startinvestimentos.com/vendor/mautic/api-library/apitester/index.php

when i click in "Autorize" i'm redirected to [this link](http://learn.startinvestimentos.com/oauth/v2/authorize?client_id=1_5m0dkvqugyw4o0k8c48w4ccw4kkwskss0gkwowkwww4cg04ogc&redirect_uri=https%3A%2F%2Fstartinvestimentos.com%3A443%2Fvendor%2Fmautic%2Fapi-library%2Fapitester%2Findex.php&state=a3b80123a52c8b44b02509456ec67e3f&scope=&response_type=code) and got 403 error.

I tryed reinstall mautic but found the same error.

**Comment by escopecz** [comment]
I cannot access either https://startinvestimentos.com/vendor/mautic/api-library/apitester/index.php nor http://learn.startinvestimentos.com/
