### ISSUE TITLE
Request for additional actions/features etc...

### ISSUE THREAD

**Issue by piuskid** [mautic/mautic#191]
A list of some features that would be great to see.  Pardon me if you already have these queued up.  I started with a couple, but then kept on going.

1) Forward to a friend
2) Subscribe, Unsubscribe
3) View time on page exceeds .... So, if they spent 2 minutes looking at a page, then trigger an action
4) Browser/Device detection.  If accessing from a mobile device, then take an action.  I might target people that are known to browse my store with a mobile device differently than those on a pc.
5) Action - write/read cookie values - configurable by the admin without code.  If person visits this page, then write a cookie including xyz value such as a profile attribute that I want to read the next time they come.  I may not know who they are, but when they decide to register, I can write all of this info to their lead record.  Therefore, I will need the ability to map cookie values to lead fields.
6) Dynamic profile read.  Let's say that I sent an offer a month ago and the customer bookmarked it.  I already know who they are and based on their last action, I have already updated their lead record.  Now, when they come back,  I can read their profile data that says that they responded already to this campaign and so I will redirect them to a different page that will target them with something personalized.
7) Dynamic content on page layouts.  I want to create a single page, but have logic in the pages (using Pagebuilder) to show different content based upon lead profile values.  If sex=male and >40 then change out bottom right offer from high heels to Nike running shoes for men unless you are Bruce Jenner, then leave the heels. :)  Filter might include specific attributes or based on lead lists. "If on this list and visited site in past 3 months then show this, else that"
8) Exlclusion lists
9) Scheduled re-generation of lists.  
10) Lead list types - Dynamic, Fixed, Test that could be used to drive behaviors on campaigns, landing pages, emails, etc...
11)  Ability to track and then clear test metrics

Thanks !

**Comment by escopecz** [comment]
I'll close this issue because some features are already implemented now, some are reported as other issues. Feel free to enter the rest as separate issues. It's hard to keep track of a list like this in one issue.
