### ISSUE TITLE
Improvement - Empty value in segment fiter

### ISSUE THREAD

**Issue by sixfingers76** [mautic/mautic#1912]
Hello,

If you create a segment by filtering contact fields, and you want to specify field "is empty" condition, Mautic only check if the field is null, so if the field has empty value (blank) Mautic says it is not empty.

It would be great Mautic to check if the field value is an empty string or is null, and in both cases return true.

Best regards.

Javier.

**Comment by escopecz** [comment]
Actually, it check for both:

```
                        case 'empty':
                            $groupExpr->add(
                                $q->expr()->orX(
                                    $q->expr()->isNull($field),
                                    $q->expr()->eq($field, $q->expr()->literal(''))
                                )
                            );
```

https://github.com/mautic/mautic/blob/957f16d36941bcf6bfb53e1702e8f8ee0c71ac8b/app/bundles/LeadBundle/Entity/LeadListRepository.php#L949
