### ISSUE TITLE
Working with "Manage Triggers" gave error 500 internal Server Error ..."

### ISSUE THREAD

**Issue by JacTrem** [mautic/mautic#1913]
## Steps to reproduce
When playing with Points - Manage Actions and Manage Triggers this error messages came up. First time ever, I meet an error message. Mayby I was a litle quick on the keyboard ....
But the systems wanted me to make this report so .....
Besides from this - A super piece of software - fantastic.
Thank you very much.
Best regards,
Jacob

Have a screen dump attached.

**Comment by JacTrem** [comment]
![mautic trigger error](https://cloud.githubusercontent.com/assets/20171386/16388677/78b4db7e-3c9a-11e6-9b13-d56b8b2a2ccc.png)

**Comment by JacTrem** [comment]
Sorry typed too many times ....

**Comment by escopecz** [comment]
Hey! Thanks for the report. Could you please also get the error message from the logs? You can find them in the right menu -> system information -> logs or in the app/logs directory.

**Comment by JacTrem** [comment]
Hi John,

Thanks for your very quick respons ….

Now I found my log - unfortunately it is quit big, but I guess you can find your way around …..

(If you are football interested & from England - sorry for this evenings results ….)

Best regards

Jacob

**Comment by escopecz** [comment]
Any news about the error message from the logs?

**Comment by escopecz** [comment]
If your log is too big, read https://mautic.org/docs/en/tips/troubleshooting.html. Let us know if you will be able to get some error message.
