### ISSUE TITLE
Inadequate logging of campaign event failures.

### ISSUE THREAD

**Issue by KrisShannon** [mautic/mautic#1914]
We had an email scheduled to be sent out in a published campaign.

Unfortunately the email itself was unpublished.

Forcing symfony debugging on while running mautic:campaigns:trigger did show:
`mautic.DEBUG: CAMPAIGN: Action ID# 370 for contact ID# 768 failed with a response of false`
but it took a couple of hours of adding extra debug to follow the control flow before we found the cause.

**Comment by escopecz** [comment]
Ready to test at https://github.com/mautic/mautic/pull/3247
