### ISSUE TITLE
Limit emails being sent per hour

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#1916]
Is there any way to limit number of emails being sent per hour?
It is important as most SMTP providers have their own limits - so we need a way to handle this.

**Comment by npracht** [comment]
Hi,

In your configuration panel (top right) in the submenu email settings, you have the ability to choose the volume of emails sent per hour.

If it answers to your question, then you can close your issue :-)

N.

**Comment by PatchRanger** [comment]
@npracht Hi Norman, thanks for your feedback. The option "Message limit for queue processing" in my views is responsible for limit the number of simultaneously sent messages. It doesn't have any mention about time frame either per hour or any else. I guess, this option is either badly worded or is not what is requested by this issue.

**Comment by PatchRanger** [comment]
Wait, knowing the frequency of cron job (in my case once in a minute) could make this option meaningful: this option could be used to set the limit the number of simultaneously sent messages once per cron trigger. So I could set, say, 50 to limit the number to 50*60 = 3000/hour.
@npracht Thank you for your suggestion! I've finally got the point))
