### ISSUE TITLE
AB Testing reset stats on email

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#1918]
## Description

Adding an AB testing variant on an existing email reset Sent/Open stats of the parent variant

## Steps to reproduce

1. Create an email
2. Send some emails
3. Add A/B variant
4. Check the parent variant : no stats anymore

**Comment by chandon** [comment]
Perhaps it's normal because it reset stats for the decision ?

**Comment by escopecz** [comment]
Yes, if some conditions of A/B test changes, the stats are cleared so the A/B test would be accurate.
