### ISSUE TITLE
CiviCRM integration

### ISSUE THREAD

**Issue by digiwizkid** [mautic/mautic#1920]
Any luck for CiviCRM?

**Comment by tomm** [comment]
I'm also interested in this feature, and may consider developing it if the deployment of Mautic I'm currently working on is successful

**Comment by twurts** [comment]
I'm also interested in CiviCRM-Mautic integration.

**Comment by eth4ever** [comment]
I'm also interested in Civi-CRM-Mautic integration.

**Comment by ddavidebor** [comment]
I'm interested as well.

**Comment by diegofcv** [comment]
+1 here
