### ISSUE TITLE
Campaign as state machine instead of scheduler

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#1930]
## Description

Let's turn campaign into state machine from scheduler (as it currently is). I mean, campaign will become a template for numerous state machines, each of which contains all of the steps & conditions its campaign has and also a concrete contact. Each time the campaign is triggered, it should force all of its state machines to check the conditions and determine whether it's time to change the state. "State" in this context is just on which action/decision/condition the evaluation of this campaign for concrete contact currently is. And if it decides to change the state, it involves triggering the actions attached to the corresponding state.
## Why

Because it is much more flexible than "schedule once and forget to ever change it" approach.
With such functionality we could change campaigns "on the fly" - so we could get rid of the "scary warning" about users currently in progress while editing a campaign.
This feature will fix such issues as #686, #838, #1377, #1868, #1869, #1935, will definitely force forward to fixing #561, #1606, #1914 and may help with #434, #539, #574, #1520.

**Comment by bobcolner** [comment]
great idea. makes a lot of sense. +1.

**Comment by PatchRanger** [comment]
Looks like I am a bit late with such a great idea as it's already implemented in Mautic 2.0.0 : https://github.com/mautic/mautic/pull/1770 :)

**Comment by PatchRanger** [comment]
After touching the Stages functionality, I am going to re-open the issue.
If I got it correct, Stages are a state machine for a contact itself - not in terms of one particular campaign.
So Stages don't solve the aforementioned issues while the suggestion of this issues - would.

**Comment by tadinski** [comment]
+1

**Comment by zenzozen** [comment]
+1
