### ISSUE TITLE
Clicking Apply multiple times when cloning a form creates multiple clones

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#1931]
## Description

When cloning a form, clicking the *Apply* button creates another clone and clicking *Apply* again after that creates yet another and more for every subsequent click.

I suspect this might have something to do with issue #1738 

## Steps to reproduce

1. Create a new form
2. Clone it
3. Click *Apply*
4. Click *Apply* x more times and watch as it makes x more clones

### Screencast
![gsat1riiql](https://cloud.githubusercontent.com/assets/18265735/16518499/6d701436-3f83-11e6-9272-6055b34ca328.gif)

**Comment by alanhartless** [comment]
Fixed in #2305
