### ISSUE TITLE
Feature request - Import does not filter out 100% blank rows

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#1932]
I noticed i had a list of 23 contacts in a csv spreadsheet, When i imported the segment it reported i had 39 leads in it.

I opened the csv in notepad++ and i noticed excel had created blank rows with no data at all.

it looked like this ",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"

This should not be imported to count as a contact

**Comment by alanhartless** [comment]
I believe this has been fixed in 2.1.1. Please let us know if not.
