### ISSUE TITLE
Facebook Ads & Google Adwords Integration

### ISSUE THREAD

**Issue by maxitromer** [mautic/mautic#1933]
## Description

When you work with PPC (Pay Per Click) you need to know how much are you spending and how much are you selling to know your ROI and optimize.

Example here: http://tinylittlebusinesses.com/images/campaigns/28-07.13-134.85.png

If you don't know your ROI you are blind to know what are the right ads, the right people, the right campaigns, etc to cut off or to maximize.

This is not just a way to grow up your company, ITS **THE ONLY WAY TO DOIT** without guessing.

For this you need to integrate with the biggest ads plattforms in the market (facebook ads and google adwords at least) and start tracking purchases from your payment processors.

This is one of the most important marketing elements to measure results and is missing in mautic.

Here you can see a good example on how this must work:

https://conversionfly.com/video-demo/

And here you have some software that has this tools working to take a look and make something amaizing inside mautic :-)

https://conversionfly.com/
http://cpvlab.com/
https://www.funnelflux.com/
https://www.infusionsoft.com/
https://ontraport.com/

I hope this can be done for Mautic.

I'm not a developer but I will glad to help with this.

**Comment by paulocastellano** [comment]
+1

**Comment by maxitromer** [comment]
Related to #497

**Comment by eastpeak** [comment]
+1

**Comment by danipolo** [comment]
+1

**Comment by hvcong** [comment]
I'm developer, hope we can talk something about this feature, @maxitromer

**Comment by maxitromer** [comment]
Thanks for been here @hvcong 

I will be glad to help you in what you need.

Whats your idea about this?

**Comment by maxitromer** [comment]
@dbhurley sorry but can I ask why this was closed?

**Comment by hvcong** [comment]
hi @maxitromer 
Pls add my skype: hvcong, we'll discuss more about this feature.

**Comment by danipolo** [comment]
why this is closed? :(

**Comment by dbhurley** [comment]
I'm sorry for not providing more details. I closed this issue because it's a feature that should be included through a third party plug-in not necessarily part of core Mautic.
