### ISSUE TITLE
Scheduling Option for Segmented Emails

### ISSUE THREAD

**Issue by CodeBradley** [mautic/mautic#1934]
## Description
I'm currently comparing Mautic to SalesForce Pardot and seeing if it's a viable replacement/option. The main thing that's persuading my decision to switch is that Pardot has a feature where you can schedule a one-time email while Mautic only lets you send a one-time email when you click the purple "Send" button, rather than providing you with an option to schedule the one-time email. Is this a feature that can be implemented? I'll even code it myself if given a bit of guidance on what areas of code to focus on. It seems like the feature already exists, but only through building a campaign. 

## Steps to reproduce
Channels -> Emails -> Create Select a Segmented Email -> Send -> No option for scheduling

**Comment by CodeBradley** [comment]
500th "issue", congrats guys ;)

**Comment by escopecz** [comment]
This seems to be duplicate of https://github.com/mautic/mautic/issues/574
