### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by chrisdutra** [mautic/mautic#1935]
## Description
It would be great be able to connect one "Send Email" action to another "Send Email" action in a campaign without need to add a decision. 

Today, I need to think about all emails before create a campaign if I don't wanna work with "decisions" because I just can connect "send emails" with the "conditions" or "decisions". But sometimes I just need to schedule the send of emails in a sequence based on the moment of optin in.

The point is that a campaign can be changed along the time. New emails can be add but the contacts that are already started the campaign will not receive the new information if I don't create an action, which demand a big tree that repeat actions..

**Comment by npracht** [comment]
Hi,

You can also construct it in parallel with 2 email actions starting from your segment with adidas rent waiting condition.

No need for a decision or condition here.

N.

**Comment by chrisdutra** [comment]
Sounds great, but I don't know if I understand what you mean. Can you be
more specific?

Your sugestion is for me to do something like this:

[image: Imagem inline 1]

Christiane Dutra
(31) 3667.0995

2016-07-01 3:06 GMT-03:00 Norman Pracht <notifications@github.com>:

> Hi,
>
> You can also construct it in parallel with 2 email actions starting from
> your segment with adidas rent waiting condition.
>
> No need for a decision or condition here.
>
> N.
>

**Comment by npracht** [comment]
![capture d ecran 2016-07-01 a 11 32 51](https://cloud.githubusercontent.com/assets/14075239/16517800/924f1620-3f7f-11e6-9431-a2b236b8c2bc.png)

**Comment by chrisdutra** [comment]
Thanks, Npacht

But this alternative isn't good for me because if I add another email, people who already receive some emails will not receive the new ones because the trigger is central which means that all the send scheduled is done when the contact start.

If one email is connected to the other I can add new emails and people will receive the last ones even if they already received the first ones.

I'm sorry about my english. I'm brazilian.

**Comment by escopecz** [comment]
@npracht's answer is correct. There is no logical reason why to connect email send action in a serial chain. It wouldn't make a difference even in the example you've provided. Mautic acts when a contact triggers some action. Modifying an active campaign is not a good idea. There other issues about it so I'll close this one.

**Comment by chrisdutra** [comment]
It is a good idea because give us more liberty to build campaings.

And it is how all the big email tools work, as Active Campaign and Infusion
Soft. But ok, Mautic is not them.

Thanks.

----------------
Christiane Dutra
Brasília/DF
Em 08/07/2016 06:12, "John Linhart" <notifications@github.com> escreveu:
