### ISSUE TITLE
Forms are not loading in CMS after Updating to 1.0

### ISSUE THREAD

**Issue by alvinbenavides** [mautic/mautic#194]
After updating to v1.0 forms are not loading using WP plugin. Apparently the same happens with Joomla according to @Nickske157 in mautic.org/community

[2015-03-10 20:25:34] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Sorry! The requested URL was not found." at /var/www/vhosts/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 151 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Sorry! The requested URL was not found. at /var/www/vhosts/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:151)"} []

**Comment by alanhartless** [comment]
Hey Alvin,

What URL is it trying to load that gives the 404 (you can mask the domain if you want)? 

Thanks,
Alan

**Comment by Nickske157** [comment]
This is the code in the joomla plugin

<script type="text/javascript" src="' . trim($this->params->get('base_url'), ' \t\n\r\0\x0B/') . '/form/generate.js?id=' . $formId . '"></script>

Kind Regards,

Nick Geoffroy
IT Professional

geoffroynick@network-it.be<mailto:geoffroynick@network-it.be>
Mobile: 0474/436.489

NETWORK-IT

[cid:D6F9B692-9C70-4CC5-9FDF-22F2F9A11263@telenet.be]<https://www.facebook.com/networkit.be>       [cid:4AF5ACDC-8855-40CB-B408-E533F9346FB7@telenet.be] <https://twitter.com/NetworkIT_be>         [cid:11F51F4B-14CE-4E0A-84A5-6CB6D89FF7D1@telenet.be] <http://www.youtube.com/user/networkitbelgie>

<http://www.youtube.com/users/networkitbelgie>www.network-it.be<http://www.network-it.be/> - info@network-it.be<mailto:info@network-it.be>
Hoofdkantoor: Kapelstraat 50/5, 2570 Duffel, België
Tel.: +32 15 63 90 32 BTW: BE 0553.500.113


"IT kan sneller, goedkoper en met beter resultaat!"
*************************************************************
Dit e-mail bericht inclusief eventuele ingesloten bestanden kan informatie bevatten die vertrouwelijk is en/of beschermd door intellectuele eigendomsrechten. Dit bericht is uitsluitend bestemd voor de geadresseerde(n). Elk gebruik van de informatie vervat in dit bericht (waaronder de volledige of gedeeltelijke reproductie of verspreiding onder elke vorm) door andere personen dan de geadresseerde(n) is verboden. Indien u dit bericht per vergissing heeft ontvangen, gelieve de afzender hiervan te verwittigen en dit bericht te verwijderen.
This e-mail and any attachment thereto may contain information which is confidential and/or protected by intellectual property rights and are intended for the sole use of the addressees. Any use of the information contained herein (including but not limited to total or partial reproduction or distribution in any form) by other persons than the addressees is prohibited. If you have received this e-mail in error, please notify the sender and delete its contents.
Ce courriel et les annexes eventuelles peuvent contenir des informations confidentielles et/ou protegees par des droits de propriete intellectuelle. Ce message est adresse exclusivement e son (ses) destinataire(s). Toute utilisation du contenu de ce message (y compris la reproduction ou diffusion partielle ou complete sous toute forme) par une autre personne que le(s) destinataire(s) est formellement interdite. Si vous avez recu ce message par erreur, veuillez prevenir l'expediteur du message et en detruire le contenu.
*************************************************************

Van: Alan Hartless [mailto:notifications@github.com]
Verzonden: dinsdag 10 maart 2015 21:45
Aan: mautic/mautic
CC: Nick Geoffroy
Onderwerp: Re: [mautic] Forms are not loading in CMS after Updating to 1.0 (#194)


Hey Alvin,

What URL is it trying to load that gives the 404 (you can mask the domain if you want)?

Thanks,
Alan

**Comment by alvinbenavides** [comment]
Hi Alan.

I'm using the plugin shortcode but the generated url is trying to lad http://mydomain.com/form/generate.js?id=3.

Mautic is on the root of this domain

**Comment by alanhartless** [comment]
Well,that's right.  I'm able to reproduce the 404 on one of my sites and not the other (both running same version).  Doing some digging.

**Comment by alanhartless** [comment]
@Nickske157 and @alvinbenavides It was a routing issue that slipped through us (obviously) so we just patched it and released 1.0.1.  Sorry!

**Comment by Nickske157** [comment]
Wauw, very quick! Thumbs up

**Comment by alanhartless** [comment]
Ha; thanks! Even though it hurt our pride a little to have to release a 1.0.1 so quick, we couldn't leave the community with broken websites! :-)
