### ISSUE TITLE
release-2.0.0 empty dashboard widgets (except recent activity)

### ISSUE THREAD

**Issue by jbmanos** [mautic/mautic#1943]
## Description
viewing dashboard in safari or firefox (mac) latest, all dashboard widgets are empty, except for the recent activity shows leads being generated or other activity (like user update).  Adding contact does not result in new data in the contacts widget.  site tracking appears active because of recent activity, so "visitors" and lead type comparison widgets should have data, too, but none.

**Comment by escopecz** [comment]
2.0.0 doesn't have a production package yet. How did you install/upgrade? Have you rebuild the Mautic assets?

**Comment by jbmanos** [comment]
I grabbed the "release-2-0-0" package off of here (GitHub).  It was a fresh install, no prior version.  

Then I ran composer install.  

Then I went through the set up by navigating to the install URL. (It's in a sub directory)

I can't get the endless redirect to stop, though (cloudflare full ssl + Apache 2.4.11) so I may just do it all again in a subdomain

**Comment by escopecz** [comment]
OK, the github version is only for developers. Please, use the https://mautic.org/download package for production.

**Comment by jbmanos** [comment]
Done.  wiped out dev install, tried production install as suggested.  Same error.

**Comment by escopecz** [comment]
It has to do something with your environment. There is no one else with this issue. Try to turn of cloudflare, try different browser to find out what is causing this issue.

I found out that some of the Report widgets causes problems. I fixed it at https://github.com/mautic/mautic/pull/1968, but it shouldn't be an issue on a fresh install.

**Comment by aquinate** [comment]
Same error here :(  
I was using Hostgator, change it to DigitalOcean, same issue happened. Can't remove a contact as well. Any help will be welcomed.

**Comment by escopecz** [comment]
@aquinate check https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by tiagosh** [comment]
I believe this was caused because of the js minification done by cloudflare: 
https://github.com/mautic/mautic/issues/1942#issuecomment-241848963
