### ISSUE TITLE
Segment filters on custom fields of type Select do not work if the options are numeric

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#1952]
## Description

Segment filters on custom fields of type Select do not work if the options are numeric.
After submitting the form once, an validation error will pop up in the filters.
At that point, the values of the option will be replaced with their index starting at one.
Upon submitting again, the index will be saved rather than the value.

I've tested this bug in **2.0.0** as well as in **1.4.1**.

## Steps to reproduce

- Create a custom field of type Select
- Add numeric options such as 7, 13 & 21 (but not 1, 2, 3, etc. in order)
- Create contacts using this field
- Create a segment with a filter on this field
- `mautic:segments:update`
- Observe that your segment is *probably* still empty.

**Comment by escopecz** [comment]
It works for me. I did this:

- Create a custom field of type Select
- Add options 1, 2 and 3 (just the numeric values)
- Create 2 contacts using this field and save the value 3 in the contact edit form for those 2 contacts
- Create a segment with a filter on this field (equals 3)
- mautic:segments:update
- Observe that your segment has 2 contacts in it

What do I have to do to replicate?

**Comment by MaxWebmecanik** [comment]
@escopecz If your options are 1, 2, 3, ...
It will work **because** of the bug.

For example:
- If your options were 7, 13 & 21
- After first saving your segment, you would get a validation error
- Then upon saving again, you will actually send the option's index rather than it's value. That is to say:
   - 1 for 7
   - 2 for 13
   - 3 for 21

Since 1 does not equal 7, etc. the condition will **never** be fulfilled.

**Comment by escopecz** [comment]
Thanks for clarification. Try to provide these nuances to the issue description next time, it will save time to both of us :)

This sucker was hard to find, but it's fixed in #2145

**Comment by MaxWebmecanik** [comment]
@escopecz Sorry, it was a bit hard to word this :sweat_smile:
Good job finding the problem! It really looks like a doozy!
