### ISSUE TITLE
release 2.0 - Segments not auto populating. 

### ISSUE THREAD

**Issue by drobotiks** [mautic/mautic#1954]
## Description

Before I updated from 1.4 to 2.0, I had to use the commands.php jobs to make things work in Mautic, (did not bother me), however, now with the 2.0 release, these jobs do not work. I'm currently trying to create a segment to send an email blast and the segment doesn't populate the contacts. 

## Steps to reproduce

Not sure if this applies to this issue but...

1. Create a new segment
2. Add filters
3. View contacts on segments (my case, "no contacts")

**Comment by ipso** [comment]
The cronjobs in v2.0 seem to have changed substantially, and I'm not seeing any documentation that mentions what the new cronjobs should look like. It would also be nice to get recommended timing internals that the jobs should be triggered on too.

A shot in the dark, you may want to try:
php /path/to/mautic/app/console mautic:segments:update --env=prod

or:

php /path/to/mautic/app/console mautic:campaigns:trigger --env=prod

See if either of those help?

**Comment by MaxWebmecanik** [comment]
Yes, it seams that the command `mautic:leadlist:update` has been replace by `mautic:segments:update`

**Comment by drobotiks** [comment]
I tried that... 

![image](https://cloud.githubusercontent.com/assets/8483151/16621794/199a6a72-435d-11e6-91f4-4e36df992a75.png)

didn't work for me.  Not sure what else to do. Thanks for the comments guys.

**Comment by drobotiks** [comment]
Thank you escopecz, is working now.
