### ISSUE TITLE
Can not Go to Landing Pages Listing under Components after Upgrading to the new Version

### ISSUE THREAD

**Issue by dioode** [mautic/mautic#1958]
## Description

After upgrading to the new version The Landing page components are not accessible.

**Comment by escopecz** [comment]
Please, provide the log from app/logs directory and your server error log. There is not much we can do without it.

**Comment by ldrrp** [comment]
Most of the time i have errors i delete the cache folder and it seems to work, other than that yea you will need a log. BTW @dioode you can get to some usefull logs in the /s/sysinfo page
