### ISSUE TITLE
Mautic API issues

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#196]
I'm implementing Mautic API to Joomla plugin and I discovered few issues along the way:

### 1 . Callback URL cannot have any HTTP query string

On authorization callback, Mautic adds to the callback URL ```'?access_token=...'```. But if the callback URL already has the ```?``` in it, it will cause problems. Example of problematic authorization callback URL:

```
http://somejoomla.com/?plugin=mautic?access_token=...
```

### 2. $leadApi->getOwners() error

```
array(1) {
  ["error"]=>
  string(739) "An exception occurred while executing 'SELECT m0_.id AS id0, m0_.first_name AS first_name1, m0_.last_name AS last_name2 FROM mau_users m0_ LEFT JOIN mau_roles m1_ ON m0_.role_id = m1_.id LEFT JOIN mau_permissions m2_ ON m1_.id = m2_.role_id WHERE (m1_.is_admin = 1 OR (m2_.bundle = 'lead' AND m2_.name = 'leads')) AND m0_.is_published = ? ORDER BY m0_.first_name ASC, m0_.last_name ASC' with params [1]:

SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
LINE 1: ...s m2_ ON m1_.id = m2_.role_id WHERE (m1_.is_admin = 1 OR (m2...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts."
}
```

### 3. $leadApi->getFieldList() doesn't return field list

it returns only empty array.

### 4. Possible duplicates

If I create a lead with email address which already exists in the Mautic lead database, it will create a new one instead of update of the existing lead. I couldn't find how to check if a lead with specified email exists via Mautic API, but I believe Mautic should validate it at its end. It's not a big issue in my use case since I will push new leads to Mautic only after successful registration so it is almost impossible to register one email address twice.

Other than those four issues the API seems so work quite good :)

Edit: Maybe it would be nice to show what source the lead was created from in the timeline.

**Comment by alanhartless** [comment]
For the callback URL issue, it's a vendor bug so I've submitted a PR to hopefully resolve this https://github.com/willdurand/BazingaOAuthServerBundle/pull/28

**Comment by alanhartless** [comment]
Just as a FYI, the vendor merged the PR (https://github.com/willdurand/BazingaOAuthServerBundle/commit/ed7afdb19c144fa18ad182907476d0b6af052eb6) so callbacks with a query appended should work with oauth1a after composer update.
