### ISSUE TITLE
release 2.0.0: 500 Internal Server Errors everywhere!

### ISSUE THREAD

**Issue by abooster** [mautic/mautic#1960]
It is NOT possible to either update from version 1.4.1 or to do a fresh install of version 2.0.0 
despite have all requirements perfectly and despite Mautic saying that the update went without any problems!

When trying to do a fresh install of version 2.0.0. (downloaded a few hours ago) it's not possible to even get to the installation page! Because the first and only thing you'll ever see when trying to do a fresh install of 2.0.0. is that page with **500 Internal Server Error**.

After checking and triple checking everything (and temporarily switching off ModSecurity) and still not being able to get past the Internal Server Error page when trying to do a fresh install of version 2.0.0 I tried this: 
1) Temporarily switched off ModSecurity (just in case)
2) Installed Mautic version 1.4.1 
3) Immediately after the fresh install of v.1.4.1 updated to v.2.0.0

When I now try to add a new asset, landing page, form or a new campaign, 
I'm always greeted with the well familiar 500 Internal Server Error page. 

So, technically, it is possible to update from 1.4.1 to 2.0.0 **but after this update Mautic stops working**. 
And a new installation of version 2.0.0 is completely impossible to begin with.

**Comment by abooster** [comment]
Just to clarify: 
I get this internal server error every time when I click the **"+ New" button** in any section such as forms, landing pages, assets, campaigns, contacts etc.

**Comment by escopecz** [comment]
Please, provide errors logged in the app/logs directory and the server error log.

**Comment by abooster** [comment]
Here are the logs from the app/logs directory: 
[2016-07-06 06:59:05] mautic.WARNING: Command `doctrine:migrations:version` exited with status code 255 [] []
[2016-07-06 06:59:05] mautic.ERROR: PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) (uncaught exception) at /home/REPLACED/public_html/e/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php line 40 while running console command `doctrine:migrations:version` [] []
[2016-07-06 07:00:25] mautic.ERROR: Deprecation: The alias option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is deprecated since version 2.8 and will be removed in 3.0. Use the extended_type option instead. - in file /home/REPLACED/public_html/e/vendor/symfony/framework-bundle/DependencyInjection/Compiler/FormPass.php - at line 67 [] []
[2016-07-06 07:00:52] mautic.CRITICAL: Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system" at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php line 185 {"exception":"[object] (Exception(code: 0): There is no suitable CSPRNG installed on your system at /home/REPLACED/public_html/e/vendor/paragonie/random_compat/lib/random.php:185)"} []

**Comment by escopecz** [comment]
Try to follow the steps from 

http://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

and contact your server administrator about 

`Uncaught PHP Exception Exception: "There is no suitable CSPRNG installed on your system"`

**Comment by abooster** [comment]
Here's the reply I got from the server administrator regarding CSPRNG:

> Because the developers removed support for OpenSSL, CSPRNG is not available on your server without voiding cPanel support and vastly limiting support, if not voiding all support you'll receive for Apache/PHP. 

In other words, I have OpenSSL installed on my VPS but CSPRNG doesn't support OpenSSL as you can see here: 
https://github.com/paragonie/random_compat/issues/99

**Comment by andersonid** [comment]
I just solved running on browser  .. mydomain.com/mautic/s/update/schema

**Comment by abooster** [comment]
@andersonid What do you mean?
What did you solve?

**Comment by Veiote** [comment]
@abooster 
Replace  the  /vendor/paragonie from V1.4.1 to the new V2.0.0.

**Comment by abooster** [comment]
@Veiote 
I'm not a developer. Just signed up here to report bugs.
So, can you explain how exactly can I do what you suggested?

**Comment by Veiote** [comment]
@abooster 
Just replace the directory /vendor/paragonie in the new installation V2.0.0 with older V.1.4.1 by the ftp.
Any problem with this new version of the paragonie/random_compat, Im using nGinx/PHP 5.6.23.

**Comment by abooster** [comment]
I confirm, overwriting (via FTP) the directory /vendor/paragonie in the new 2.0.0 installation with the same directory from the older V.1.4.1 installation does fix the problem of 500 Internal Server Errors I was getting everywhere. 
My PHP version is 5.6.22

Thank you, @Veiote !

**Comment by escopecz** [comment]
Here is another solution: https://github.com/mautic/mautic/issues/2034#issuecomment-232711927

**Comment by solanoepalacio** [comment]
Hi, im trying to install Mautic for the first time and the versión I got is 2.1.1.
I get the same Internal server error that you describe in your installation process. I'd like to know which would be the way to fix it if you don't have the 1.4.1 version previously installed.

**Comment by abooster** [comment]
@solanoepalacio Overwrite (via FTP) the directory /vendor/paragonie in the 2.1.1 installation with the same directory from the older V.1.4.1 installation.

**Comment by ciaranmg** [comment]
@abooster Where can we find version 1.4.1 if we have never installed it before? There is no copy on the website?

**Comment by AlexBooster** [comment]
Well, it isn't currently here: https://www.mautic.org/download/previous-releases/ 
So, I don't know.

**Comment by solanoepalacio** [comment]
I've looked arround the web for days and found an incomplete version (I
assume it's incomplete because it's half the average size of the other
versions and I can't find the Vendor/paragonie folder inside it.

Please if anybody finds a solution to this, let me know. I'll do so as
well...

**Comment by abooster** [comment]
I have this one in the vendor folder: 
http://www.mediafire.com/file/sa9acl5jpwacki2/paragonie.zip
It's from the Mautic version 1.4.1.

**Comment by solanoepalacio** [comment]
Thanks a lot abooster, I'll try to make it work with it :D

**Comment by aaronsmulktis** [comment]
I also solved right in the browser thnx to @andersonid's suggestion
