### ISSUE TITLE
[2.0.0] Cookies are always "http only" and "secure"

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#1969]
## Description

I've setup mautic 2.0.0 over HTTPS.

My configuration for cookien is :+1: 
Cookie Domain : .mydomain.com (top domain with a dot at the begining)
Set cookie as secure : NO
Set cookie as http only : NO

But when the tracking javascript is loaded (over my https server hosting mautic), it creates only HTTP and SECURE cookies.

Using the "developer tools" of my browser, i can see in response header of mtracking.gif : 

    Set-Cookie:837d07e3597e369af9436cbcd89722edc44d60=1; expires=Thu, 07-Jul-2016 10:19:03 GMT; Max-Age=1800; path=/; domain=.mydomain.com; secure; httponly
    Set-Cookie:mautic_referer_id=16; expires=Thu, 07-Jul-2016 10:19:04 GMT; Max-Age=1800; path=/; domain=.mydomain.com; secure; httponly
    Set-Cookie:mautic_session_id=837dc07e3597e369a1f9436cbcd89722edc44d60; expires=Thu, 07-Jul-2016 10:19:03 GMT; Max-Age=1800; path=/; domain=.mydomain.com; secure; httponly
 
As you can see, all cookies are "secure; httponly"

Note that i had the same issue with mautic 1.4.1

**Comment by MxyzptlkFishStix** [comment]
The httponly flag doesn't mean what you think it means.  It has nothing to do with a cookie being sent in cleartext.  It's to prevent XSS (cross-site scripting) attacks of the cookie by a third party i.e taking the cookie session from one browser and trying to use it in another.

**Comment by chandon** [comment]
I want to be able to access mautic cookie through javascript from my own website. With httponly, it really means i cant. More important, "secure" restrict the access from my non http website.

What is the purpose of the options ?

Set cookie as secure : NO
Set cookie as http only : NO

**Comment by MxyzptlkFishStix** [comment]
You can still access the cookie.

Those options mean that if your web server isn't configured* to pass those headers, you can get Mautic to do it.

Example Apache Header config:
...
Header edit Set-Cookie ^(.*)$ $1;Secure;HttpOnly
...

**Comment by alanhartless** [comment]
Fixed in #2311
