### ISSUE TITLE
Unsubscribed vs Do Not Contact

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#1970]
## Description

Both of these terms are used in the interface, what is the functional difference?

## Steps to reproduce
Smart lists can include Unsubscribed in conditions
Leads can be marked Do Not Contact
Leads can click unsubscribe and are then marked Do Not Contact

**Comment by npracht** [comment]
Closely linked to https://github.com/mautic/mautic/issues/1543

**Comment by mbrinson** [comment]
This page has good information on the differences between Bounced, Do Not Contact, and other responses based on applicable RFC's:
http://docs.aws.amazon.com/ses/latest/DeveloperGuide/mailbox-simulator.html

In my testing with the different email addresses provided I had the following outcomes:

bounce@simulator.amazonses.com - Mautic registers as "Email Bounced" in contact info
suppressionlist@simulator.amazonses.com - Mautic registers as "Email Bounced" in contact info
complaint@simulator.amazonses.com - Mautic registers as "Do Not Contact" in contact info
ooto@simulator.amazonses.com - Mautic does not seem to have any detection for Out Of Office msgs
