### ISSUE TITLE
mtc.js not compatible with IE9

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#1973]
## Description

When using the javascript with IE9, there is a javascript error generated (seems to be at MauticJS.documentReady, it expects a function and not a string...)

## Steps to reproduce

Just open a page with the script included on IE9, and watch errors on console. You can also emulate IE9 with IE Developer Tools

**Comment by alanhartless** [comment]
Hi! IE9 is an extremely old and outdated browser and no longer supported by even Microsoft (including ie 10). I don't think we will be providing specific support for it. 

If this same error is found in newer browsers, we can reopen this issue. 

Thanks!

**Comment by chandon** [comment]
Sorry, but i can't avoid people with older browser to come on my website. And if the script creates a JS error, stopping later js execution, it's not acceptable.

So i corrected this JS bug into PR #1974
