### ISSUE TITLE
Missing 'app/logs' folder in 2.0.0.zip install

### ISSUE THREAD

**Issue by paulocoghi** [mautic/mautic#1977]
## Description
The folder `app/logs` is missing in the [installation file for the 2.0 release](https://s3.amazonaws.com/mautic/releases/2.0.0.zip) and, in this moment, you need to manually create it to continue.

When you proceed to your respective URL of your Mautic install, an error message is returned informing that `app/logs` is unwritable (in fact, since it doesn't exist).

## Steps to reproduce
1. Download https://s3.amazonaws.com/mautic/releases/2.0.0.zip in the root folder of your project's/domain's webserver and extract it.

2. Proceed to the respective configured URL for your installation.

3. The message is there and you need to manually create the `app/logs` folder to continue.

**Comment by escopecz** [comment]
The `app/logs` folder will be automatically created if Mautic (server user, usually called www-data) has permission to create it. This is not a Mautic issue, but permission issue of the file system at your server.

**Comment by paulocoghi** [comment]
The folder owner, the php process owner (php-fpm in this case) and the webserver process owner are all the same.

**Comment by paulocoghi** [comment]
I will reproduce it again and post screenshots for more detail.
