### ISSUE TITLE
[BUG] v2.0 GET on /api/contacts/list/fields fails with a 500 response code

### ISSUE THREAD

**Issue by zapur1** [mautic/mautic#1982]
## Description

When listing the contact fields through the API by using the endpoint an error occurs

This started occurring after the v2.0 update

## Steps to reproduce
With valid API authentication do a GET on /api/contacts/list/fields 

The following is the error returned in the error logs
```
[2016-07-07 23:21:49] mautic.ERROR: Error: Call to undefined method Mautic\LeadBundle\Controller\Api\LeadApiController::getModel() - in file /home/mautic/public_html/app/bundles/LeadBundle/Controller/Api/LeadApiController.php - at line 30 [] []
```

**Comment by zapur1** [comment]
This is also occurring when doing a PUT on /api/contacts/

**Comment by escopecz** [comment]
This will fix it: https://github.com/mautic/mautic/pull/1961

**Comment by iadj** [comment]
Glad I read about this before upgrading. The API is the most important thing for me.

**Comment by zapur1** [comment]
Glad to hear that a fix already exists
