### ISSUE TITLE
Upgrading Mautic Bitnami installation?

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#1989]
I'm trying to upgrade to 2.0.0 using the provided `upgrade.php` file. I put the file in `/opt/bitnami/apps/mautic/htdocs` and try to run `php upgrade.php` and `sudo php upgrade.php`, both resulting in the following error:
```
{"complete":false,"error":true,"updateState":"eyJwbHVnaW5Db21wbGV0ZSI6ZmFsc2UsImJ1bmRsZUNvbXBsZXRlIjpmYWxzZSwiY2FjaGVDb21wbGV0ZSI6ZmFsc2UsImNvcmVDb21wbGV0ZSI6ZmFsc2UsInZlbmRvckNvbXBsZXRlIjpmYWxzZX0=","stepStatus":"Failed","message":"Invalid task"}
```

**Comment by dbhurley** [comment]
Handled on  Bitnami's side.
