### ISSUE TITLE
Can't update link with email editor popup toolbar

### ISSUE THREAD

**Issue by andersonid** [mautic/mautic#1991]
## Description

MAUTIC 2.0.0
Can't update link with email editor popup toolbar after created by main toolbar at top of editor.
The update button dont send the request.

## Steps to reproduce

1 - create a link for a simple text.
2 - try to update this link with popup toolbar right near the text you need to update the link.
3 - the Update button dont send the request, so wont update .

**Comment by escopecz** [comment]
Could you please provide a screen shot of that button?

**Comment by andersonid** [comment]
Sure, sorry....

http://look.andersonid.com/Dvwn

**Comment by escopecz** [comment]
Ah, this button. There is the __Save__ or __Apply__ button to save the content. The content isn't saved after every change. Aren't those buttons saving the content for you?
