### ISSUE TITLE
add new contact hangs

### ISSUE THREAD

**Issue by davetbo** [mautic/mautic#1994]
Hello,

I just installed Mautic 2.0.0.  When adding new contacts, the web page hangs and the spinner on "Save & Close" just spins indefinitely.  
## Steps to reproduce
Click contacts, then +New.  
Fill out first name, last name, and email.
Click Save & Close.

I'm using PHP 5.6.23 on OSX 10.10.5.

**Comment by martinstr** [comment]
This should fix it, It worked here after we applied it.
https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Views/Lead/form.html.php

**Comment by davetbo** [comment]
Thanks for the response.  That fixed it!

Best,
Dave


On Sun, Jul 10, 2016 at 10:32 AM, martinstr <notifications@github.com>
wrote:

> This should fix it, It worked here after we applied it.
>
> https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Views/Lead/form.html.php
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mautic/mautic/issues/1994#issuecomment-231600709>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAFCrEDpjem3YnLV1ICRbRTObqq3lkpdks5qUSymgaJpZM4JIZ-H>
> .
>



-- 
Best,
Dave
----------------------------------------------------
www.ThibaultFineArt.com
Painting the Places We Love
