### ISSUE TITLE
New 2.0.0 install doesn't work right from base URL

### ISSUE THREAD

**Issue by davetbo** [mautic/mautic#1996]
I just installed Mautic 2.0.0  I installed it on a local web server on my Mac.  After the install it sent me to the dashboard properly.  However, once I tried opening it again by typing mautic.artlauncher.online (which is pointed to 127.0.0.1 in my /etc/hosts file) it redirects to mautic.artlauncher.online/s/dashboard, and says "Not Found: the requested URL /s/dashboard was not found on this server."

If I manually type the path as mautic.artlauncher.online/index.php/s/dashboard it works fine.  I noticed this by looking in my browser history to see where it sent me after the install.

## Steps to reproduce
Install fresh copy of mautic.  After completing the install, type in just the host name in the address bar.  It will redirect you automatically to /s/dashboard and give you a page not found error.

**Comment by escopecz** [comment]
Enable .htaccess and mod_rewrite in your server settings

**Comment by davetbo** [comment]
They were enabled.  That was not the solution.  However, I have decided to
switch to a different solution for my email marketing needs, since mautic
seems to be too busy to have timely support responses, and I found the
software to be too buggy for my needs.  I was planning on integrating it
into my SaaS platform for hosted artist websites, but kept finding software
bugs and couldn't get a timely response from support, even when I asked if
I could do paid support.

Best,
Dave

**Comment by yyx100** [comment]
@davetbo 
rewrite module not only needs to be enabled, but also the directory need to have the permission for .htaccess to use it. 
 I bet somewhere in your apache2.conf has "AllowOverride None", which disabled the .htaccess's rewrite rules.  It is not fair to complaint about this software is buggy for your apache config issues.

**Comment by bitoutshop** [comment]
I am also having this issue. I have enabled mod_rewrite i think but where is the .htacccess file supposed to be?

I cant find it anywhere and what should be in the file?

**Comment by WhiteTiger-IT** [comment]
mod_rewrite is activated and there is also .htaccess.
What is missing is the "s" folder and all its contents.
The installation was done with Softaculous

**Comment by wlandgraf** [comment]
And what should be in "s" folder? Why it's not there in the first place? I'm having the same issue.

**Comment by escopecz** [comment]
Guys, this is a PHP application. Not a static file system structure. /s/ doesn't mean that there is actual physical folder with that name. It's a route that tells the app to request administrator login.

The problem you have seems to be with either .htaccess file or mod_rewrite being disabled.

**Comment by zachkinsey** [comment]
I'm also having this issue. 

By default, my domain goes to /s/dashboard/ , which doesn't work.
If I manually type /index.php/s/dashboard , it works.

I'm on Cloudways so I can't access the config file directly since they won't give me Sudo access. But, according to them (Cloudways), mod rewrite and .htaccess are enabled.

Additionally, the .htaccess file only has 'deny from all' within it.

**Comment by affanahmed70** [comment]
go to /etc/apache2/apache2.conf and change this 

from

<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride none
	Require all granted
</Directory>

to 

<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>

**Comment by wayneoutthere** [comment]
This last post was absolutely the solution,  Thanks much!  But don't forget your closing brackets, I believe (but I'm not highly skilled)

```
<Directory /var/www/>
             Options Indexes FollowSymLinks
             AllowOverride All
             Require all granted
        </Directory>
```
