### ISSUE TITLE
Email Opens Not Tracked Anymore

### ISSUE THREAD

**Issue by jimsimjim** [mautic/mautic#1999]
## Description

When sending an email via the contact record. 
The email opens are not tracked or registered.
Email sent via php mailer in email settings.

## Steps to reproduce

Set email to PHP Mail and enter details
Send an individual email via the contact record
Open the email in your email client using a different IP address
No open recorded in contact record / timeline

**Comment by escopecz** [comment]
Please, go through https://mautic.org/docs/en/emails/troubleshooting.html if there is and answer for you. If not, please, tell us what email client(s) did you test and if your Mautic runs on https.

**Comment by jimsimjim** [comment]
Thanks for getting back. The link didnt fix the issue. The mautic install is not running on https. I tried webclients (like roundcube), Apple Mail and Hotmail / Gmail and still the same issue (all from different email address, computers and ips).

**Comment by pritstift** [comment]
Same here. I had a look on the log file. After opening the mail i got:
`mautic.ERROR: Error: Call to a member function getId() on null - in file /var/www/mautic.my.domain/app/bundles/EmailBundle/EventListener/CampaignSubscriber.php - at line 99 [] []`

**Comment by pritstift** [comment]
I updated to Mautic 2.0.1 and the issue is gone.
