### ISSUE TITLE
Joomla Plugin Bug

### ISSUE THREAD

**Issue by gokhanerdogdu** [mautic/mautic#2000]
## Description
If your hosting for mautic contains further character after .com, for example, our address is ma.domain.com.tr, then Joomla Plugin can not insert forms from the mautic instance. Firebugging the website shows that the form seems to be located at "http://ma.domain.com./form/generate.js?id=1" although it should be "http://ma.domain.com.tr/form/generate.js?id=1"
## Steps to reproduce
In order to reproduce the problem, in the Joomla Plugin, configure the address with domain.com.tr, or domain.co.uk, with further charachter after .com.

**Comment by escopecz** [comment]
Please, try to apply this fix:

https://github.com/mautic/mautic-joomla/pull/20/files

And comment bellow the PR if it worked for you:

https://github.com/mautic/mautic-joomla/pull/20

**Comment by gokhanerdogdu** [comment]
It solved our problem. Thanks.
