### ISSUE TITLE
exception 'RuntimeException' with message 'Failed to write cache file

### ISSUE THREAD

**Issue by physicalit** [mautic/mautic#2002]
## Description
When i go to the webpage to start the installation process i get this 500 internal server error:
log: `[Sun Jul 10 14:16:59.847606 2016] [:error] [pid 3396] [client 10.0.0.4:34948] exception 'RuntimeException' with message 'Failed to write cache file "/home/admin/web/physicalit.ml/public_html/app/cache/prod/classes.php".' in /home/admin/web/physicalit.ml/public_html/vendor/symfony/class-loader/ClassCollectionLoader.php:248\nStack trace:\n#0 /home/admin/web/physicalit.ml/public_html/vendor/symfony/class-loader/ClassCollectionLoader.php(122): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::writeCacheFile('/home/admin/web...', '<?php \\nnamespac...')\n#1 /home/admin/web/physicalit.ml/public_html/app/bootstrap.php.cache(2642): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::load(Array, '/home/admin/web...', 'classes', false, false, '.php')\n#2 /home/admin/web/physicalit.ml/public_html/app/AppKernel.php(243): Symfony\\Component\\HttpKernel\\Kernel->doLoadClassCache('classes', '.php')\n#3 /home/admin/web/physicalit.ml/public_html/app/AppKernel.php(110): AppKernel->boot()\n#4 /home/admin/web/physicalit.ml/public_html/app/middlewares/CORSMiddleware.php(96): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/admin/web/physicalit.ml/public_html/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#6 /home/admin/web/physicalit.ml/public_html/app/middlewares/Prod/SetMauticHeaderMiddleware.php(41): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#7 /home/admin/web/physicalit.ml/public_html/app/middlewares/VersionCheckMiddleware.php(56): Mautic\\Middleware\\Prod\\SetMauticHeaderMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#8 /home/admin/web/physicalit.ml/public_html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#9 /home/admin/web/physicalit.ml/public_html/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#10 /home/admin/web/physicalit.ml/public_html/index.php(30): Stack\\run(Object(Stack\\StackedHttpKernel))\n#11 {main}`

**Comment by escopecz** [comment]
This should be a permission issue. Make sure the folders are writable. Contact your server admin for help.
