### ISSUE TITLE
Add "switch" to campaign builder

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#2003]
## Description

It would be great to have an analog of PHP `switch` statement in campaign builder.
I mean, choose a field which is going to be "switched" - and then add several "cases" with ability to provide default one.
This feature would replace a cascade of conditions, making campaign building a lot more pleasant.

**Comment by merlin0** [comment]
This would be great ! I think this feature with #2023 will set-up an campaign a lot easier indeed. +1

**Comment by escopecz** [comment]
I'll close this as a duplicate of https://github.com/mautic/mautic/issues/2023
