### ISSUE TITLE
Campaign Events Not Being Scheduled After A Certain Amount.

### ISSUE THREAD

**Issue by edutj** [mautic/mautic#2004]
## Description
I have a big campaign of around 2 years of scheduled content (more than 100 e-mails to be sent). After around 9 sent e-mails, the system simply stops sending the e-mails (if I look at the person's profile, i see that they are not even scheduled to be sent).

The campaign config rules is basically: every 7 days (for 2 years) an e-mail will be sent to a person as long as this person has a certain field containing "approved" in it.

My cron:
* * * * * php /path/to/mautic/app/console mautic:segments:update --env=prod >/dev/null 2>&1
* * * * * php /path/to/mautic/app/console mautic:campaigns:rebuild --env=prod >/dev/null 2>&1
*/2 * * * * php /path/to/mautic/app/console mautic:campaigns:trigger --env=prod >/dev/null 2>&1

**Comment by dbhurley** [comment]
Is the email of the 10th person valid? What does your error log show?

**Comment by alanhartless** [comment]
We determined this is a cron job overlap issue - will update the docs to reflect. Basically with all three main cron jobs running simultaneously - locks on the segment membership changed the membership of campaigns leading to contacts getting temporarily removed from the campaign which in turn deleted future scheduled events. Running the cron jobs sequentially fixed this so will update the docs to reflect this.
