### ISSUE TITLE
Removing, then adding back certain events breaks campaigns

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#2005]
## Description

When modifying a campaign, removing, then adding back certain events breaks things when saving.

## Steps to reproduce

- Create a simple campaign (Such as the one in the screencast below)
- Save
- Edit
- Open the campaign builder
- Remove some events
- Add them back
- Close the builder
- Save

### Screencast

![campaign_event](https://cloud.githubusercontent.com/assets/18265735/16723572/111b7720-474e-11e6-8cd0-992fb4458490.gif)

**Comment by MaxWebmecanik** [comment]
Bug confirmed in 2.0.0

**Comment by PatchRanger** [comment]
Well, I am able to reproduce the bug in even more weird manner: it fails even just for deleting events from campaign (without adding back).
Here is the content of the corresponding log message:

> [2016-07-16 15:31:29] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing 'DELETE FROM campaign_events WHERE id = ?' with params [216]:  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic`.`campaign_events`, CONSTRAINT `FK_8EC42EE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `campaign_events` (`id`))" at /public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): An exception occurred while executing 'DELETE FROM campaign_events WHERE id = ?' with params [216]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic`.`campaign_events`, CONSTRAINT `FK_8EC42EE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `campaign_events` (`id`)) at /public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:91, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic`.`campaign_events`, CONSTRAINT `FK_8EC42EE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `campaign_events` (`id`)) at /public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:855)"} []

**Comment by 3ruce** [comment]
Similar problem here...

>[2016-07-25 04:34:07] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'DELETE FROM campaign_events WHERE id = ?' with params [20]:  SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic`.`campaign_events`, CONSTRAINT `FK_8EC42EE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `campaign_events` (`id`))" at /home/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException(code: 0): An exception occurred while executing 'DELETE FROM campaign_events WHERE id = ?' with params [20]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic`.`campaign_events`, CONSTRAINT `FK_8EC42EE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `campaign_events` (`id`)) at /home/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic`.`campaign_events`, CONSTRAINT `FK_8EC42EE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `campaign_events` (`id`)) at /home/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic`.`campaign_events`, CONSTRAINT `FK_8EC42EE7727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `campaign_events` (`id`)) at /home/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

**Comment by alanhartless** [comment]
Fixed in #2343
