### ISSUE TITLE
Problem Campaign - email with attachment - "Call to a member function getId() on null"

### ISSUE THREAD

**Issue by jdecampos** [mautic/mautic#2007]
## Description
Since the update mautic in 2.0, I have a problem. In the campaigns where there is a sending mail with an attachment. I get an error that appears (see picture) [http://www.vendre-sur-amazon.fr//wp-content/uploads/capture.png](url)
<img width="1297" alt="capture" src="https://cloud.githubusercontent.com/assets/14194414/16725061/d245f608-4755-11e6-818a-3d7824c98a12.png">
## Steps to reproduce

- create a campaign with an email
- In the email, put an attachment
- Start cron campaign

PHP Version 5.6.23
no error in the logs ...

**Comment by escopecz** [comment]
That is interesting. Why is `trackDownload` method even triggered during the mautic:campaign:trigger execution? It could mess with the asset download stats. @alanhartless do you have a theory?

**Comment by escopecz** [comment]
Different error message, but the issue is in the same method: https://www.mautic.org/community/index.php/4914-maituc-2-0-not-send-email-to-segment/0#p13101

Might be related.

**Comment by jdecampos** [comment]
Indeed, the problem is what? we can fix it?

**Comment by escopecz** [comment]
@jdecampos please try #2017 if it fixes it for you.

**Comment by jdecampos** [comment]
I just tested it and it works for me :)

Thank you ! :+1:
