### ISSUE TITLE
Unsubscribe

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#2009]
## Description
Hi, guys, I was playing with Mautic this weekend and I find this interesting. If I create a segment list and send a segmented email to that segment and the contact make click in the Unsubscribe link the contact get  a Do Not Contact from the WHOLE Mautic system and not just for that segment if there a way to Unsubscribe just for that segment?
## Steps to reproduce

**Comment by escopecz** [comment]
This is probably duplicate of https://github.com/mautic/mautic/issues/822
