### ISSUE TITLE
Add segment activity to contact recent event timeline

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2015]
## Feature request definition

Add the **segment activity** logged in the tab `lead_lists_leads` to the timeline.
Then the marketer will be able to see when a lead is added to a segment.
## Description of today

On the contact timeline activity on the contact page, you have the activity of a lot of events like:
- Page Hit
- Campaign Action Triggered
- Contact Created
- Contact Identified
- Accessed from IP
- Asset Download
- Form Submitted
- Point Gained
- Email Sent
- Email Read

![capture d ecran 2016-07-12 a 10 45 20](https://cloud.githubusercontent.com/assets/14075239/16760926/422b89ba-481e-11e6-84ca-7a505a4d66b5.png)

**Comment by bloodlynx** [comment]
+1

**Comment by npracht** [comment]
# I complete by:

- add/remove from a segment
- specify reason (campaign/form/point trigger ID / manual)

**Comment by npracht** [comment]
@dbhurley i still think this important for a user today to know the reason why a contact has been added/removed from a segment.

**Comment by dbhurley** [comment]
Marketer can use notes for this functionality.

**Comment by npracht** [comment]
So that means that you expect a human action to add a note when a contact changes of segments from a form or campaign action? That cannot work that way..

**Comment by dbhurley** [comment]
Ah, I understand what you are suggesting. I'll leave it as is until there's a PR to address it.
