### ISSUE TITLE
Add form action: Update contact

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2016]
## Feature request definition

Add a new form action on contact form submission. The ability to **update contact field value (modify contact)**.
This feature would behave the same way as in the campaign builder.
![capture d ecran 2016-07-12 a 10 54 55](https://cloud.githubusercontent.com/assets/14075239/16761168/4478c7ea-481f-11e6-9a91-6a99412723be.png)
![capture d ecran 2016-07-12 a 10 54 49](https://cloud.githubusercontent.com/assets/14075239/16761167/44610506-481f-11e6-930a-0f984621728c.png)
## Description of today

In the `Action` tab of the form, it is possible to add several action when a contact submits the form.
- Adjust contact's points
- Modify contact's segments
- Modify contact's tags
- Download an asset
- Push contact to integration
- Send email to contact
- Send email to user
- Send form results
  ![capture d ecran 2016-07-12 a 10 52 53](https://cloud.githubusercontent.com/assets/14075239/16761097/fe72d132-481e-11e6-868a-f26af34eee37.png)

**Comment by bloodlynx** [comment]
If the contact uses the same email when submitting the form doesn't the contact field value the contact committed get updated anyway? Or would you want to update a field value that's not in the form?

**Comment by npracht** [comment]
2nd option, objective could be to update a field not existing in the form.

N.

**Comment by vdittgen** [comment]
+1

**Comment by escopecz** [comment]
@npracht how is this different than mapping the form fields to contact fields?

**Comment by npracht** [comment]
It is more about fields that are not offered to the visitor. But you're right, you could manage this feature by using hidden fields... :-)

**Comment by escopecz** [comment]
Alright. Thanks for confirmation! Since there is a workaround, I'll close this feature request so we could focus on those which are show stoppers.

**Comment by ivanvitorassi** [comment]
+1

**Comment by namratasaun** [comment]
Hello, how to hide a field. I have a similar issue
