### ISSUE TITLE
Add ability to make more conditions in one campaign condition block

### ISSUE THREAD

**Issue by merlin0** [mautic/mautic#2023]
## Description

Currently in the campaign builder there is the possibility to use the condition contact field value. 
This can be a powerful feature to filter leads from a certain company,country or have specific function.
However for each you need to create a different condition block to check the field value.
![image](https://cloud.githubusercontent.com/assets/12198056/16781639/7a8b606a-487c-11e6-8231-c9d18e961e82.png)

It would be great for example if was possible to check with one condition if a lead has one of the few required job functions to match the condition. Just like with a segment (see image) you can check if either of the values are true, for example either marketeer or ceo.  Another example would checking if a contact is from one of 4 countries. This feature would help a lot with keeping the overview in the campaign builder and making the conditions more efficient.
![image](https://cloud.githubusercontent.com/assets/12198056/16781583/422dd20c-487c-11e6-94bc-396fb37161fd.png)

**Comment by chandon** [comment]
It would be great if the condition worked like an "open mail" decision. If the NO branch wait for 7 days, it should be re-evaluated every time for 7 days. So, if a contact field is updated before the 7 days by an api call or something else, it could trigger a YES branch (Example : 3 days after entering the condition...)

**Comment by chandon** [comment]
duplicate #2014

**Comment by sahidjeurissen** [comment]
+1
