### ISSUE TITLE
Re enabeling users after bounce restriction

### ISSUE THREAD

**Issue by Harry5-5** [mautic/mautic#2025]
Can someone help me please I'm getting desperate.

I have been testing Mautic with a view of rolling it out across our business but im running into a bit of a problem.
During the testing of the system i got 3 bounced emails from one of my test users. I notice on users contact page these is a flag and an option to reset the user but when i click on it it just hangs (with the process icon spinning).

Has anyone else had this problem that can give me any advice on how to fix it?

Thank you

Roger

**Comment by nickian** [comment]
This is still an issue for me as well on 2.0.1. Console is showing 

`/s/ajax?action=lead:removeBounceStatus&mauticUserLastActive=1&mauticLastNotificationId=117 500 (Internal Server Error)  libraries.js?v2.0.1:670`

If I go directly to that URL, I see this result `{"success":0}`

**Comment by escopecz** [comment]
Could you guys check what is the PHP error message in the app/logs folder right when you try to replicate it?

**Comment by nickian** [comment]
Here's what I'm seeing:

`[2016-07-13 17:09:52] mautic.ERROR: Error: Call to undefined method Mautic\LeadBundle\Controller\AjaxController::getEntityManager() - in file /app/bundles/LeadBundle/Controller/AjaxController.php - at line 334 [] []`

**Comment by Harry5-5** [comment]
yes thats the same error i am seeing

[2016-07-13 17:22:48] mautic.ERROR: Error: Call to undefined method Mautic\LeadBundle\Controller\AjaxController::getEntityManager() - in file /var/www/campaign/app/bundles/LeadBundle/Controller/AjaxController.php - at line 334 [] []
