### ISSUE TITLE
HTML Code Stripping on Landing Page Builder v2.0.1

### ISSUE THREAD

**Issue by drobotiks** [mautic/mautic#2026]
## Description

I noticed that it was fixed on the email builder, and I now can place HTML code to build emails. However, when I try to build a landing page, the code gets stripped.

Is there something I need to do after the update? I have cleared cache already. 

## Steps to reproduce

1. Create Landing Page
2. Paste HTML Code
3. Hit "Apply"

Code disappears, just shows a white page.

**Comment by escopecz** [comment]
Related form thread: https://www.mautic.org/community/index.php//4923-landing-page-html-editor-doesn-t-work/p1

I'm working on a fix

**Comment by escopecz** [comment]
Here's the fix: https://github.com/mautic/mautic/pull/2032
