### ISSUE TITLE
Zendesk integration?

### ISSUE THREAD

**Issue by davidlinc1** [mautic/mautic#2028]
## Description
I can see that that there is a [Zendesk integration listed on the integrations page](https://www.mautic.org/integrations/), but that seems to be the only trace of a relationship between Mautic and Zendesk. It's not shown in my Mautic's "Plugins" section and I can't find any information on it.

Anyone know what the deal is? Did someone accidentally reference an integration on the website that doesn't exist in the software?

**Comment by davidlinc1** [comment]
I hate to bump, but I'm being pinged by our management to get to the bottom of whether or not our organization can utilize this integration. Anyone know why it's shown on the Mautic site, who put it there, or how I might be able to use it?

**Comment by escopecz** [comment]
The integrations in grey are planned, the integrations in color are finished.
