### ISSUE TITLE
facebook lead ads api integration for mautic

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#2031]
## Description

As discussed in the forum, I think its really interesting to have a tight integration for facebook lead ads, to get lead data automatically into mautic and trigger campaigns based on it.

The feature request can also be found in the forum thread [About Facebook Leads](https://www.mautic.org/community/index.php/2596-about-facebook-leads-hiring/)
## Steps to build integration
1. Check out and dive into facebook lead ads
2. Check whether an webhook api or form integration is better
3. Build an sample integration or api
4. ad documentation for endusers (since its gona be a tough multi step setup process)

**Comment by mrfossil** [comment]
i created a quick fix if you are interested https://github.com/mrfossil/Mautic-facebook

**Comment by vexersa** [comment]
Awesome!

Nothing happens when I click the "Login with Facebook" button :(

**Comment by vexersa** [comment]
I believe I've configured everything correctly, sadly not sure how to test
the integration. I'd love to help you build this by testing functionality
etc.

**Comment by nifunifatralara** [comment]
any news on this? does the fix work? Will it be officially added to Mautic? That'd be great..!

thanks!

**Comment by arikmeyer** [comment]
+1

**Comment by Luisfmarkes** [comment]
Hey guys,
it seems that this plugin will do the job
