### ISSUE TITLE
Google Contacts import and sync with mautic

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#2033]
## Description
I guess it would be really handy to have a google contacts sync

Features
- **Pull contacts from google contacts** and update/insert into mautic (one-way)
- **Push leads to google contacts** (one-way). Trigger on new lead (eg form) or through campaigns. (Google is really smart in merging contacts, thus I'd probably rather use pull and push than real synchronization since synchronization is dangerous)
- **Syncronize Contacts** (I think this feature is really handy but also really dangerous!!!  A contact may remove details ... We must discuss this strategy and how it may be implemented. Does anyone have experience on this?)

I guess same would be really handy for other address book providers e.g. Microsoft Outlook Exchange 365 or Outlook.com

Feature is also discussed in the forum on
- [Google Contact Sync](https://www.mautic.org/community/index.php/2825-google-contact-sync/0)
- [Importing from Google Contacts to Mautic](https://www.mautic.org/community/index.php/892-importing-from-google-contacts-to-mautic/0)

What you guys think about how to integrated address book integration with mautic?

**Comment by levor5** [comment]
Much needed feature. Having all Mautic contacts on my phone address book, really useful!

**Comment by BatchHeader** [comment]
This would be a great addition to Mautic. Currently using the integration to VTiger then syncing contacts to Google from there, but doing this just in Mautic would really simplify this for small biz / new users.

**Comment by Loanatik** [comment]
This would be a great plugin.

**Comment by CharmingSteve** [comment]
yes, I would love it too

**Comment by IADDIC** [comment]
Agree

**Comment by BatchHeader** [comment]
Guessing this isn't on the roadmap!

**Comment by dbhurley** [comment]
It's a fantastic suggestion but not part of core. As a plug-in it's something we definitely want to see.

**Comment by IADDIC** [comment]
The "little" challenge for this day in age is the consolidation of resources and assets.   Is it G-mail, Mautic, Cloze, FullContact, or something else?  Many are looking for that tool that makes this happen.  Without those integrations, it is akin to setting up an awesome well-running machine in the middle of a wheat field.  Unfortunately, we all own many wheat fields and awesome running machines.  Here's to hoping Mautic heads that way!

**Comment by manuelfink** [comment]
Anyone knows a plugin supporting mautic?
