### ISSUE TITLE
Focus feature: grab website snapshot not working

### ISSUE THREAD

**Issue by geospatialmedia** [mautic/mautic#2036]
## Description
Hello, I am trying to create a new focus at https://geosmartasia.mautic.net/s/focus/new

I entered my website url http://geosmartasia.org/ for Mautic to grab a screenshot of my website. The preview is not getting displayed.

## Steps to reproduce
1. Go to Channels > Focus
2. Click New
3. Go to Builder
4. Enter URL, Click Fetch

**Comment by randallsevery** [comment]
We are also getting this same issue, so I'm not sure why it was closed two years ago.  Some URLs generate snapshots correctly, others do not, with no apparent pattern.  In fact, for URls that work, if I request https://www.domain.com/ it works and https://www.domain.com/index.html, which returns the *exact* same content, it doesn't work.  From looking at the web server log files, whatever process on mautic.net that generates the snapshot isn't even requesting the URL to get the snapshot.

**Comment by Bellusterra** [comment]
Yes, this is still not functioning in the latest version 2.15.1. @alanhartless can we reopen this?

**Comment by shrinet** [comment]
hey, I am still getting snapshot issue, some time its working, some times not. I was trying to get snapshot for URL https://www.maxvisionsolutions.com and it responds with very old contents and if I change URL with https://www.maxvisionsolutions.com/magento-development it completely fails
