### ISSUE TITLE
Bug - Campaign builder action not triggered after form submission

### ISSUE THREAD

**Issue by sdobbelaere** [mautic/mautic#2037]
## Description
Running a campaign through the campaign builder, I have setup 6 steps of which the last one should change the contact's stage after successfully submitting a form.  

All the steps work fine, also the saving of the data from the form work fine.  But when mautic should bump the stage of the contact, nothing happens. 

Alternatively I tried to append 50 points instead of bumping the stage, but the result is no succesful either.  It would seem the issue is in the 'check if form is submitted'-block.

## Steps to reproduce
1. Create 2 stages
* Create a segment for each stage
* Create an intro email
* Create a campaign-form and make sure you can view it from an external page (not a mautic landingpage)
* Create campaign
  1. Use a segment as contact source
  * Auto-send an email to these contacts
  * Add a point if the email is opened
  * check if form is submitted (from link in email)
  * Update contact's stage
* Add a new contact and assign it to a stage

![screen shot 2016-07-15 at 14 00 29](https://cloud.githubusercontent.com/assets/16462709/16875031/e9dee242-4a94-11e6-8bb5-6f8dd1cf5a8b.png)

**Comment by escopecz** [comment]
I tried to replicate and it is acting differently every time I test it. The actions after the form submit decision are sometimes triggered, but the stage is never changed even though I can see the action triggered in the contact's timeline. I'll get back to this before 2.1.0 release. There were changes to the campaign algorithms.

**Comment by mqueme** [comment]
@sdobbelaere have you tested this in new version 2.1.0? I have just tested on a form not embedded in a Mautic page and it did add points and change stage. Can you please confirm.

**Comment by alanhartless** [comment]
Due to lack of feedback, we are closing this issue. Please upgrade to 2.1.1 and if the issue persists, let us know! Thanks!
