### ISSUE TITLE
mautic emails links are not trackable.

### ISSUE THREAD

**Issue by ttmubarak** [mautic/mautic#2044]
i can see open clicks rate and graphp, but didn't see link click tracking. 

## Description:
Hello mautic team,

          I can see open clicks and related graphical representation for that, but didn't see any link click tracking. When I click the link in email it will goes to correct website. But didn't see any link click record data in mautic.

I am using latest mautic version 1.4

and php version is php5.6

Pleae help me to correct the solution for this.

Thank you

**Comment by alexleobr** [comment]
I'm using Mautic 2.0.1 with PHP 5.6 and didn't see tracking links in emails, too! :(
The emails send with mautic link with unique key
Thank's

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/2060

**Comment by ttmubarak** [comment]
Thanks its working now
