### ISSUE TITLE
Lifetime Cycle widget contact count is wrong

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2045]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The graphs in the Lifetime Cycle widget do not show the right number of contacts. 
The problem might be due to the fact that I performed several imports of the same contacts, with each import adding more information, Mautic has thus merged contacts. 

The counts indicated in the widget actually seem to be the sum of the number of contact in each import, even if existing contacts were updated rather than new ones created.

Also notice that the counts indicated right below the segments' name are correct. 

See picture below: 

![capture d ecran 2016-07-18 a 11 08 42](https://cloud.githubusercontent.com/assets/7101583/16915595/ae5f0362-4cf8-11e6-9b6f-e47948cb9125.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Import a CSV list of contacts
2. Add more information (fields) to the CSV file and reimport
3. Check that Mautic tells you that contacts were merged when the import is done
4. Add the Lifetime Cycle widget to the dashboard
5. Notice that the number of contacts in the graphs is wrong. 

### Log errors: 

There does not seem to be any relevant log related to this error.

**Comment by mqueme** [comment]
Have you checked if your leads may be listed as anonymous?

**Comment by pierreavizou** [comment]
I have, my segment does not have any anonymous leads, if that was your question ;)

**Comment by pierreavizou** [comment]
Hi,

I see that this issue was referenced in PR #2059 which has been merged, however I still have the issue in Mautic 2.1, so I just wanted to report that :)

**Comment by mqueme** [comment]
Have you checked your anonymous leads? if they are in a segment that is included in your chart, they are counted as well.

**Comment by pierreavizou** [comment]
Yes I did, my segments are configured so that they do not contain any anonymous lead, I have just doubled check again right now :)

**Comment by mqueme** [comment]
The lyfecycle chart is dependant on the dates, so it looks at when the leads were added in time. unfortunately the contacts list page does not support date filters. So I can see how the list given can be misleading.

**Comment by pierreavizou** [comment]
Could you please elaborate a bit? I'm not sure I understand... 
What bugs me is that the chart reports my segments as containing even more leads than I have ever had. And those segments never contained anonymous leads. 

As I said in the original post, the issue could come from the fact that I successively imported my leads with CSV files.

**Comment by pierreavizou** [comment]
Here a a little screenshot to help me explain. 
You can see what happens, for the **same segment**, and for a time range including all of my contacts.

<img width="405" alt="capture d ecran 2016-08-15 a 12 50 57" src="https://cloud.githubusercontent.com/assets/7101583/17662683/ab81742c-62e7-11e6-8cdd-a05c66de2897.png">

**Comment by mqueme** [comment]
It could be that your list_leads table has additional information that was not deleted correctly. I have rechecked the code and followed the steps you have provided, I have not been able to replicate this bug in new version of Mautic. I will add another check for non existent leads in case some where deleted manually from the database or not deleted correctly from lists.

**Comment by mqueme** [comment]
Ok, that helps, I will look into this. Thank you.

**Comment by pierreavizou** [comment]
You're welcome, thanks for looking into this.
