### ISSUE TITLE
Bug - Dwell Times widget shows no graph

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2046]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The Dwell Times widget on the dashboard shows no graph, whereas it would be expected to show a circular graph. See screenshot below. 

![capture d ecran 2016-07-18 a 11 38 22](https://cloud.githubusercontent.com/assets/7101583/16911009/585b7e4e-4cdc-11e6-83e0-1980422f3741.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Have some contacts visit your site and spend time on pages
2. Notice that the dwell times widget shows no data
 
### Log errors: 

No related logs.

**Comment by dbhurley** [comment]
Fixed in https://github.com/mautic/mautic/pull/2191
