### ISSUE TITLE
Upgrading from 2.0.0 to 2.0.1

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2048]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I've got Mautic 2.0.0 installed, i want to upgrade to 2.0.1, but it fails when upgrading through command line

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.0
| PHP version | 5.6.19

### Steps to reproduce:
1. Go on server shell  console (SSH)
2. Type :

    php app/console mautic:update:find
    Great! You are running the current version of Mautic

**Comment by escopecz** [comment]
It doesn't seem to fail. It is telling you that you are already running 2.0.1. That isn't true? If you clear the Mautic cache and refresh the page, can you see 2.0.1 in the footer?

**Comment by chandon** [comment]
I think it's a problem on my side, i've downloaded it manually. Thanks
