### ISSUE TITLE
Add tweets to the contact timeline

### ISSUE THREAD

**Issue by wittwerch** [mautic/mautic#2050]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | yes
| Enhancement? | 

## Description:
The Twitter integration (using the MauticSocialBundle) provides the possibility to create/update leads from mentions or hashtags. It would be awesome if these tweets would also show up on the timeline of a contact, like a page hit or a triggered email.

**Comment by dbhurley** [comment]
Possibly done during a rewrite of the contact activity history layout.

**Comment by alanhartless** [comment]
We're not currently storing the exact tweets analyzed so it would take a bit more than just displaying the information in the timeline. This will probably have to go into the release cycle as it's own task rather as part of the timeline revamp as it'll require more than just displaying existing data (new table to store the gleaned history, etc).

**Comment by huntercarter** [comment]
@alanhartless , does Mautic currently store the tweets in the db? If so, where in the db?

**Comment by escopecz** [comment]
@huntercarter the tweet database structure will be updated with https://github.com/mautic/mautic/pull/3748
