### ISSUE TITLE
Bug - Mail builder won't close on certain cases

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2051]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
On certain circumstances (See steps to reproduce for exact details), the mail builder won't close, when clicking on the close button, the page backgrounds dims and the spinner is shown and nothing happens from this point on. 

In the console, there is the following message: 
libraries.js:145 Uncaught Error: Method destroy does not exist in Froala Editor.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Create a new email (type and theme do not matter)
2. Open the builder
3. Add an image slot _and choose an image from your server_
4. Close the builder
5. Open the builder again
6. Try to close the builder
7. The bug shoud occur and the builder should not close, instead displaying the spinner forever.
 
### Log errors: 

In the JS console : 
`libraries.js:145 Uncaught Error: Method destroy does not exist in Froala Editor.`

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/2032
