### ISSUE TITLE
Widgets and Calendar not updated with mass emails

### ISSUE THREAD

**Issue by janfranck** [mautic/mautic#2052]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | A |
| Feature request? |  |
| Enhancement? |  |
## Description:

In version 2.0.1 
Dashboard widgets and calendar are not updated when sending a mass email.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
| PHP version |  |
### Steps to reproduce:
1. Add new mass email
2. Send mass email - emails are send as indicated in the email view
3. No update on calendar or widgets on dashboard
### Log errors:

I do not know if the error in the log is connected to the issue at hand.

[2016-07-18 00:36:19] mautic.ERROR: Deprecation: The alias option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is deprecated since version 2.8 and will be removed in 3.0. Use the extended_type option instead. - in file /home/apache/mautic.janfranck.com/html/vendor/symfony/framework-bundle/DependencyInjection/Compiler/FormPass.php - at line 67 [] []

**Comment by alanhartless** [comment]
Does this still happen in 2.1.1?

**Comment by janfranck** [comment]
Hi Alan,

 

I am waiting to have 2.1.1 installed but I can say that in 2.1.0 NOTHING appears on the calendar when I send out 10 emails yesterday. All emails send and stats and reports are updated but not calendar and widgets in dashboard.

I will get back to you when we update.

 

Jan

**Comment by janfranck** [comment]
Hi Alan,

 

Just updated to 2.1.1 and problem still persists at least there is a conflict between calendar view and the e-mail sent / opened gadget on the dashboard – the latter is correct.

Here are the screenshots:



All these email are mass emails but only august 2 is in calendar.

August 16 should be 10 emails

August 17 should be 10 emails.



 

Hope that can be sorted.

 

Jan

**Comment by mqueme** [comment]
This is no longer happening in 2.6.1
