### ISSUE TITLE
Changing dashboard widget type causes error 500

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2054]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I added a 'top segments' widget to the dashboard, then I changed its type to 'added contacts', and then, when I try to refresh the page, I get an error 500 on the dashboard page. Other parts of Mautic are still accessible. 
I tried to clean the cache, with no result. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Add a widget (I added the top segments one) to the dashboard
2. Change its type (I changed to 'added contacts')
3. Try to access the dashboard page
4. You should get an error 500. 
 
### Log errors: 

`[2016-07-19 07:53:49] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Routing\Exception\RouteNotFoundException: "Unable to generate a URL for the named route "mautic_lead_action" as such route does not exist." at /var/www/html/app/cache/prod/appProdUrlGenerator.php line 215 {"exception":"[object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"mautic_lead_action\" as such route does not exist. at /var/www/html/app/cache/prod/appProdUrlGenerator.php:215)"} []`

**Comment by escopecz** [comment]
This was fixed in https://github.com/mautic/mautic/pull/2047 already. Ready to test.

**Comment by pierreavizou** [comment]
Thanks for pointing me to this PR @escopecz , I've just tested it and it works perfectly! Should I mention that in the PR comments?

**Comment by escopecz** [comment]
Yes, please. Every test speeds up the merging of that PR and therefore the new release.
