### ISSUE TITLE
Role page UI/translation issues

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#2055]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
![mautic-role-issues](https://cloud.githubusercontent.com/assets/1235442/16949434/141f12ec-4dbb-11e6-8060-03dc12bbc1a7.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.29

### Steps to reproduce:
1. Go to Permissions
2. Click New

**Comment by dongilbert** [comment]
Fixed in #2094
