### ISSUE TITLE
Username and Password for Virtual Machine Acess 

### ISSUE THREAD

**Issue by ramgouveia** [mautic/mautic#2057]
Question

I'm using Mautic via a virtual machine called VirtualBox. When Mautic opens it asks for username and password. It says that mine are correct. But it doesn't says where to register. Can you help me pelase?

**Comment by escopecz** [comment]
I don't really understand what the VirtualBox has to do with it. Do I understand it right you want to create a new user who could access the Mautic administration? If so, click the cog icon in the top right corner, then Users menu item, click New.
