### ISSUE TITLE
Form Autofill Using Manual Source

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#2058]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I make a couple of tests using creating a Standalone form and using the "Manual Copy" and paste the source in Mautic Builder but the autofill function don't work using Manual Copy.

Then i send  a email to a contact using {pagelink=8}&email={leadfield=email|true} to see if the stand alone form using "Manual Copy" filed the Email Field but don't work.

But if i use the "Automatic" option it works

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
I don't think there is an option to prefill field values when using only static HTML. This manual copy-paste option sadly doesn't allow to use all features of Mautic Forms. If you can, use the JS embed.
