### ISSUE TITLE
Check if a theme slot has any content in 2.0

### ISSUE THREAD

**Issue by feltoar** [mautic/mautic#2062]
Is the ability to hide/show a slot still available when developing themes for Mautic 2.0?

Previous to 2.0 you could use `$view['slots']->hasContent('slotname')` to determine if a slot had any content or not. It's possible to replace this with `{% if slotHasContent('slotname') %}` which is the Twig equivalent. Although this only works for old landing pages working in backwards compatibility mode. Not for new themes built for 2.0.

Has this feature been removed/lost? Is there an alternate method to allow theme users to switch on/off elements based on content?

I have tried working around this by using jQuery but the `<script>` tag causes most of the landing page HTML to disappear on save. Have also tried CSS with :not(:empty) but this does not work since the Froala editor puts `<br>` tags into slots that have no content. I am at a loss and wondering if this simply isn't possible any more.

**Comment by escopecz** [comment]
Good question! The 2.x.x builders use HTML slots instead of PHP/twig slots so there is no slot processing on server side in place now. It has some advantages like no need to define the slots in theme configuration, it's possible to move the slots around, create the new ones or delete those the user do not like. 

The script tags were enabled in 2.0.1, although there is still an issue with external scripts/styles fixed in https://github.com/mautic/mautic/pull/2032.

But any suggestions are welcome!

**Comment by feltoar** [comment]
Thanks for the reply. Good to know that jQuery could be a fall back if needed. I may also rethink my approach. The new system is certainly much nicer. Easier to develop for and easier to use with the builder and content tab.

Thing is I have a theme from 1.4 which took advantage of the ability to hide empty slots. In the theme are a pair of call to action boxes with a semi-transparent background, curved border, and box shadow. One on the left, one on the right. It allows the user to put content in call to action box they wanted and leave the other empty and hidden. I have a couple of people who have purchased this theme and want to use it on 2.0 but unfortunately I can only do it with a fraction of the flexibility the original theme provides.

It sounds like what I want to achieve may be a fringe case. After some thought I had an idea. 2.0 allows section background colours to be customised. It may be a better direction to expand on that. I noticed you MUST select a solid colour, perhaps the ability to define a more traditional CSS 'background' value instead would be better? This would allow Mautic users to not just do colour, but transparency, use images and even image positions.

Anyone interested in this as a new feature (eg: separate Github issue)?

And anyone else inconvenienced by the removal of not being able to check slots for content?

**Comment by escopecz** [comment]
We decided to remove the builder from Mautic 2.2.0 and only use the Froala editor because right now it duplicates 90% of the functionality.

**Comment by tathspts** [comment]
When is 2.2 coming out?
