### ISSUE TITLE
Upgrade to 2.0.0 or 2.0.1 causes search error

### ISSUE THREAD

**Issue by ToonGeneral** [mautic/mautic#2063]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
We are running 1.4.1. We have now tried three upgrades; two to 2.0.0 and one to 2.0.1. In all three cases the universal search no longer functions. There is a clear and reproducible error in the logs when trying to search (see below).

Our upgrade process is to snapshot the VM, run the upgrade and test. For each failed upgrade, we revert to the snapshot, so this can be easily tested / reproduced.

For the 2.0.x upgrade we have used the provided script, as our DB is now 10k+ contacts. There were no errors shown during the script execution.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.0 and higher
| PHP version | 5.6.23

### Steps to reproduce:

1. Run upgrade from 1.4.1 to 2.0.1
2. Load the dashboard
3. Attempt to search for anything
4. No results are displayed
5. Log errors appear

### Log errors: 
[2016-07-19 23:01:58] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 77 near 's.name LIKE :sncavYTu': Error: 's' is not defined." at <mautic path>/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 77 near 's.name LIKE :sncavYTu': Error: 's' is not defined. at <mautic path>/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT p FROM Mautic\\StageBundle\\Entity\\Stage p LEFT JOIN p.category c WHERE s.name LIKE :sncavYTu OR s.description LIKE :sncavYTu at <mautic path>/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []

**Comment by escopecz** [comment]
I'm not able to replicate it. Could you give an example what you search for?

**Comment by ToonGeneral** [comment]
Yes, I suspect it's either going to be a transient problem during upgrades, or something has happened to our specific install that the upgrade script wasn't expecting. We haven't done anything special, I'm just hypothesising :-) Otherwise I would have expected you'd have had more reports!

The searches were all very generic, just terms that should match existing contacts. So things like:
'laura'
'test'
'john'
etc

**Comment by escopecz** [comment]
It works for me. Maybe try some steps from http://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful to make sure the database schema is up to date.

**Comment by ToonGeneral** [comment]
OK, ran through some of the stages:

` [~/www]# php app/console mautic:update:find`
`Great! You are running the current version of Mautic.`
` [~/www]# php app/console doctrine:migration:status`

    >> Name:                                               Mautic Migrations
    >> Database Driver:                                    pdo_mysql
    >> Database Name:                                      <db_name>
    >> Configuration Source:                               manually configured
    >> Version Table Name:                                 migrations
    >> Version Column Name:                                version
    >> Migrations Namespace:                               Mautic\Migrations
    >> Migrations Directory:                               <mautic path>/app/migrations
    >> Previous Version:                                   2016-06-30 00:00:02 (20160630000002)
    >> Current Version:                                    2016-07-12 00:00:00 (20160712000000)
    >> Next Version:                                       Already at latest version
    >> Latest Version:                                     2016-07-12 00:00:00 (20160712000000)
    >> Executed Migrations:                                33
    >> Executed Unavailable Migrations:                    4
    >> Available Migrations:                               29
    >> New Migrations:                                     0

The unavailable migrations seemed strange and were also flagged up when running:
`[~/www]# php app/console doctrine:migration:migrate`
`WARNING! You have 4 previously executed migrations in the database that are not registered migrations.`
 `   >> 2015-02-01 00:00:00 (20150201000000)`
 `   >> 2015-02-25 00:00:00 (20150225000000)`
`    >> 2015-03-07 00:00:00 (20150307000000)`
`    >> 2015-03-10 00:00:00 (20150310000000)`
`Are you sure you wish to continue? (y/n)y`
`WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y`
`No migrations to execute.`

However, the output of:
`[~/www]# php app/console doctrine:schema:update --dump-sql`
had a lot of SQL statements that still needed to be executed.

I ran:
`[~/www]# php app/console doctrine:schema:update --force`
and it got as far as:
`CREATE INDEX current_provider_search ON leads (current_provider);`

current_provider is a text field that we added, back in Jan when this instance of Mautic was deployed. The error thrown was:
` [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'CREATE INDEX current_provider_search ON leads (current_provider)':
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'current_provider' used in key specification without a key length`

Pretty sure this is because you can't put an index or primary key on a text field. Is this something that should have been handled, but something has gone wrong, or wasn't a scenario that was intended to be handled? As far as I know the field was created via Mautic and nothing special was done (I didn't set it up).

**Comment by ToonGeneral** [comment]
In fact, I rolled back to 1.4.1 and re-ran:
`[~/www]# php app/console doctrine:schema:update --dump-sql`

There are 10 commands pending, but none of them are about creating the indexes for search, so I presume this was a 2.0.0 addition?

`DROP INDEX point_date_added ON lead_points_change_log;`
`DROP INDEX lead_date_added ON leads;`
`ALTER TABLE page_redirects DROP FOREIGN KEY FK_8C9F851AA832C1C9;`
`DROP INDEX IDX_8C9F851AA832C1C9 ON page_redirects;`
`DROP INDEX page_date_hit ON page_hits;`
`DROP INDEX campaign_date_triggered ON campaign_lead_event_log;`
`DROP INDEX campaign_leads_date_added ON campaign_leads;`
`DROP INDEX email_date_sent ON email_stats;`
`DROP INDEX asset_date_download ON asset_downloads;`
`DROP INDEX form_date_submitted ON form_submissions;'`

**Comment by alanhartless** [comment]
Ignore `doctrine:schema:update` for this case. 2.0 added better support for field types and indexing profile fields but did not retro apply on purpose. `doctrine:schema:update` will attempt to apply indexes to existing fields when it can't due to 1.x means of creating lead fields as longtext. If you really really want to make it to where you can run the `doctrine:schema:update` command, change the columns in the `leads` table from longtext to varchar or any field according to https://github.com/mautic/mautic/blob/1e0a4b1d236d33489b013e99abab0482191beec7/app/bundles/LeadBundle/Model/FieldModel.php#L517-L517. 

But  back to your search error, it's a bug where Stage's getTablePrefix() does not match what's used in addCatchAllWhereClause(). 
https://github.com/mautic/mautic/blob/c32a6d58c4a53d9bb04147fe3542df56bb29b053/app/bundles/StageBundle/Entity/StageRepository.php#L101-L101

https://github.com/mautic/mautic/blob/c32a6d58c4a53d9bb04147fe3542df56bb29b053/app/bundles/StageBundle/Entity/StageRepository.php#L40-L40

**Comment by alanhartless** [comment]
Actually, seems to be more than that (that was just one of the issues). PR coming.

**Comment by alanhartless** [comment]
PR submitted. See #2082

**Comment by edutj** [comment]
@alanhartless After I run "app/console doctrine:schema:update --force", I receive the following result:

Updating database schema...

                                                                                                                       
  [Doctrine\DBAL\Exception\DriverException]                                                                            
  An exception occurred while executing 'CREATE INDEX vip_search ON leads (vip)':                                      
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'vip' used in key specification without a   
  key length                                                                                                           
                                                                                                                       

                                                                                                                       
  [Doctrine\DBAL\Driver\PDOException]                                                                                  
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'vip' used in key specification without a   
  key length                                                                                                           
                                                                                                                       

                                                                                                                       
  [PDOException]                                                                                                       
  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'vip' used in key specification without a   
  key length        

I changed the column to varchar(255) and after I re-run the --force command, it puts back the "longtext" setting and returns the same error I just posted.
