### ISSUE TITLE
mtc.js: "pixel loaded" callback

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2065]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | N
| Enhancement? | Y

## Description:
When loading the pixel through mtc.js on a thid party page, as the process is asynchron, we've no way to know if the pixel was already loaded at the time we want to execute another action (like routing to another page).
So, if i do : 

    mt('send', 'pageview');
    window.location="anotherpage";

the pixel is not loaded. 
Event if i wait for documentReady, it's not loaded at this time. So we need an event for mt('send')

Something like:

    mt('send','pageview').onSent(function () { });

**Comment by escopecz** [comment]
Good idea! If you'd have time to implement it, here is the file with the mtc.js source: https://github.com/mautic/mautic/blob/staging/app/bundles/PageBundle/EventListener/BuildJsSubscriber.php#L44
