### ISSUE TITLE
Toggling the (un)published state of Dynamic Content fails with Error 500

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2067]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
On the page that list your dynamic contents, there are toggles to quickly publish / unpublish them. Using them causes the spinner to show forever. The JS console indicates that the server responded with an error 500. The error in question is provided in the appropriate section below. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Create a dynamic content
2. Go to the page that lists your dynamic contents (yourmautic/s/dwc)
3. Click on the switch to toggle the published state of your content
4. You should see the spinner showing forever
 
### Log errors: 

- In the JS console: 
`mymautic//s/ajax?action=commandList&model=dwc&_=1469019551668&mauticUserLastActive=1&mauticLastNotificationId=414 500 (Internal Server Error)`

- In the PHP Error logs: 
`[2016-07-20 12:57:19] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "mautic.dwc.model.dwc is not a registered container key." at /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php line 120 {"exception":"[object] (InvalidArgumentException(code: 0): mautic.dwc.model.dwc is not a registered container key. at /var/www/html/app/bundles/CoreBundle/Controller/CommonController.php:120)"} []`

**Comment by Mazzim** [comment]
I was getting the same error in the Current Error Log, I applied this PR but am still getting the error every time a dynamic content is being requested. The Dynamic Content itself works fine, it shows different content for a known contact and an unknown visitor. I use self-hosted Mautic 2.0.1, PHP 5.6.23 and request content from a WordPress site using Mautic WP plugin.

Here is the error I'm getting:
[2016-08-07 12:18:32] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "mautic.dwc.model.dwc is not a registered container key." at /var/www/api.five.pictures/public_html/app/bundles/CoreBundle/Controller/CommonController.php line 120 {"exception":"[object] (InvalidArgumentException(code: 0): mautic.dwc.model.dwc is not a registered container key. at /var/www/api.five.pictures/public_html/app/bundles/CoreBundle/Controller/CommonController.php:120)"} []

**Comment by escopecz** [comment]
@Mazzim are you getting this even with Mautic 2.1.0?

**Comment by Mazzim** [comment]
Sorry, @escopecz, missed this one somehow.
No, I do not see this error since version 2.1.0
