### ISSUE TITLE
Feature: Showing detailed device information in timeline

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2068]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
Currently, when a visitor accesses a page where you have the Mautic tracking pixel set up, if there are valid UTM tags in the page's URL, Mautic creates a 'UTM Tags' section in the contact's timeline, showing detailed information on the visitor's device. That can be i.e the screen resolution, the fingerprint, the timezone...

When there are no UTM tags in the URL, such information is not shown. However, I can see in the logs that the information is still sent with the tracking pixel querystring even when there are no utm tags. The tracking pixel also detects if the visitor is using adblock or sends the DNT signal, and this information seems to be shown nowhere in Mautic. 

So it could be nice to have all this data shown somewhere even if the page the contacts visists does not have UTM tags in its URL. 

One step further could also be to make such information filterable to create segments based on this data. 

I hope this post can initiate some discussion in the community to build an even better Mautic :)

**Comment by escopecz** [comment]
Might be related to https://github.com/mautic/mautic/pull/2059 and I think there will be also the contact history page redesigned in 2.1.0, so check the PR page from time to time to make sure the redesigned page will have all that :)

**Comment by pierreavizou** [comment]
Great, thanks! 
I'll be sure to monitor how this PR goes :) 
If you want, you can close this issue, I think I'll post my potential suggestions directly in the PR comments so that everything related to contact history is consistently kept in one place :)
