### ISSUE TITLE
Pixel in email got alt="Mautic is open source marketing automation" => spam detection

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2069]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | N
| Enhancement? | Y

## Description:
Magix pigel in email got : alt="Mautic is open source marketing automation"
This lead to some SPAM detection by Bayes algorithm (spamassassin...) because everybody using Mautic got this sentence.
Can we remove it ? (file app/bundles/EmailBundle/Helper/MailHelper.php )

**Comment by escopecz** [comment]
Sure, can you send the pull request with the change? I'd leave the alt attribute to keep the HTML valid, but left it empty.
