### ISSUE TITLE
Add the option to have lead list filters like "this week," "last week", "this year"

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#207]
Right now there is a date created filter for leads but it has to be a specific date. Being able to segment leads by relative timeframe would be helpful for campaigns.

**Comment by kithokit** [comment]
Hi , it looks like the date filter is only to be a specific date, but not relatively to today.

E.g. if I want leads's age > 30, the leads can't be changed everyday.
e.g. say set Date of Birth > 1980-01-01, the leads can't change relatively to today.

Any recommendation for that?

**Comment by alanhartless** [comment]
Relative time frame segmentation was added in 1.2.0.  Yay!

**Comment by lutek** [comment]
How can i use it? Just select "less than" = 3 for Date Added ? and will filter all leads last than 3 days?

**Comment by escopecz** [comment]
More details are in the PR which added the functionality: https://github.com/mautic/mautic/pull/808
