### ISSUE TITLE
Segment filters on custom fields of type Select do not work if the options contain special characters

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#2077]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | X

## Description:

If the options of a custom field of type select contain a special character such as single and double quotes, lesser than and greater than signs, etc. a segment filter using this option can't be validated.

### Screencast

![screencast](https://cloud.githubusercontent.com/assets/18265735/16684273/7e0e9534-4504-11e6-94cf-7b0242028a29.gif)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | `2.0.1`
| PHP version | `5.6.23`

### Steps to reproduce:
1. Create a custom field of type select
2. Give it options containing the special characters mentioned above
3. Create a segment filter using one of these options
4. Save & notice the validation going off

## Cause

The options are saved with the special characters escaped in the format &xxxx; but are then compared against the bare characters

```php
"aujourd'hui" !== "aujourd&#39;hui"
```

Thus Symfony consistently thinks you input an unauthorized value.

**Comment by alanhartless** [comment]
Fixed in #2342
