### ISSUE TITLE
Missing regions in country dropdown list

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2079]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
On the `country` field, we are missing the following country values:

| Name | Code | Code | Code
| --- | --- | --- | ---
| Guadeloupe | GP | GPL | 312
| Saint Pierre and Miquelon | PM | SPM | 666
| Democratic People's Republic of Korea | KP | PRK | 408

The last is North Korea but i can understand...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.0
| PHP version | 

### Steps to reproduce:
1. Check on a contact page, the country dropdown list
Linked to the uncomplete PR #1777

**Comment by MaxWebmecanik** [comment]
@npracht Well North Korea is in 2.0.1 :tada:
