### ISSUE TITLE
Running a campaign multiple times for a contact

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#2084]
I noticed that if a contact is part of a campaign and the campaign decisions/actions have all occurred for this contact, these automation rules will not re-run if you remove the contact from the campaign and re-add them. I'm not sure if this is an intentional feature or a bug, but is it possible to fully clear a campaign for a contact, assign them to the campaign again, and have the rules run through again as they did the first time?

It would also be great to see a campaign history/campaign influence tab to see what campaigns a contact has been part of at a glance (instead of sifting through a long timeline).

**Comment by Mazzim** [comment]
@nickian, I've actually filed a feature request on this quite a while ago. Please chime in [here](https://github.com/mautic/mautic/issues/1606) if you believe this is a much needed functionality that is missing.
