### ISSUE TITLE
Adding a second image from filemanager to an email doesn't work

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2086]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When you edit an email with the editor in the "content" tab, you can add an image. If you choose to add it from the filemanager, the first image is added when clicking on the "select" button, but if you try to add a second image, it doesn't work

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.19

### Steps to reproduce:
1. Edit an email
2. Got to the content tab, in the html editor part
3. Click on "Image" button, then on the "folder" button
4. Select an image in the filemanager
5. Click on "Select" button
6. Reproduce step 3 to 5 to add another image

**Comment by chandon** [comment]
not fixed by #2032 
Console log (in the fileditor popup window) : 

    filemanager.js:646 Uncaught TypeError: Cannot read property 'length' of null

**Comment by escopecz** [comment]
You are right, I re-run the steps. I'll fix it.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/2032/commits/3a7379da870d27ada946ee6fa0e0c301c6e75fc4
