### ISSUE TITLE
Campaign condition on contact fields : missing condition on tags

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2088]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

## Description:
In a campaign, when you add a condition on "contact field", it's not possible to do it on contact **tags**. It should be great to have the possibility to do it (you can begin a campaign, add tags to a lead during the campaign, and according to the presence of a tag or not, change the actions for this lead)

**Comment by alanhartless** [comment]
Going to merge this into one as it's related to #897 and #1613

**Comment by alanhartless** [comment]
Never mind - this is a condition - not updating fields.
