### ISSUE TITLE
JS tracking script instead of or in addition to the tracking pixel

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#209]
Leads are currently tracked via a tracking pixel which requires pertinent information to be added to the URL's query (the real url, title, etc). Using a javascript to handle this would be allow collecting more accurate results.

Not sure what the best route is for this, whether to jsonp results or dynamically create and append the information to a tracking pixel.

**Comment by amit777** [comment]
I'm not sure if this is helpful, but it may be possible to emulate what piwik does.  They already have implemented a nice and tested client-side javascript library here:
https://github.com/piwik/piwik/blob/master/js/piwik.js

**Comment by arditveliu** [comment]
Well, if you want to use javascript you can do so in Google Tag Manager

1. Add new user-defined variable (Custom Javascript) named "analytics-trigger" with the following function:
```javascript
    function mauticPixel() {
        var title = document.title;
        var url = window.location.href;
        var userLang = navigator.language || navigator.userLanguage; 
        var trackingPixel = "http://yoursite.com/m/mtracking.gif?url=" + encodeURIComponent(url) + "&title=" + encodeURIComponent(title)+ "&language=" + encodeURIComponent(userLang);
        return trackingPixel;
    }
```
2. Create a new, custom image tag and use {{analytics-trigger}} as the URL.
3. Publish

The only issue is that most ad and tracking blocker plugins recognize and block the tag manager, yet the mautic pixel usually goes unnoticed. By lumping it in with the tag manager, you make it super easy to block.

I've tested it with my install and it works perfectly.

**Comment by mm-blxsoft** [comment]
Yes using JS based tracking would open up huge possibilities for lead tracking:
Examples include:
Page Engagement Tracking (Scroll Percentage, Time Between Scrolls(i.e.. are they actually reading, or just skimming))
Video Engagement Tracking (play, pause, etc...)
Link Click Tracking (i.e.. Navigation to other linked sites, that would be otherwise untrackable, like social media sites)

**Comment by ptcc** [comment]
:+1: this would also make it easy to segment leads based on behavior :) 
please please make this a priority

**Comment by jordan8037310** [comment]
Mentioning slowplow's trackers here as there is a larger ecosystem of trackers besides just javascript based. Assuming the collectors would also be nice to leverage:

https://github.com/snowplow/snowplow/tree/master/1-trackers
https://github.com/snowplow/snowplow/tree/master/2-collectors

**Comment by alirobe** [comment]
Umm... if the tracking JS could _just_ do the same level of tracking the pixel does for now, the rest of the features in more complex trackers could be added to the overall mautic product _in due course_. Let's not turn a simple feature request into an attempt to re-architect the entire product. A simple JS-based tracking method (i.e. even just server-side request tracking with an empty JS file) for the moment - would enable the flexibility to add all these sorts of features and integrations and frameworks in the future...

**Comment by escopecz** [comment]
FYI, the PR about the JS tracking is here: https://github.com/mautic/mautic/pull/1582
