### ISSUE TITLE
Troubleshooting sending an email in Mautic 2.0

### ISSUE THREAD

**Issue by ramgouveia** [mautic/mautic#2092]
Hello when I tried to send an email in Mautic 2.0 I've received the following message.

Can you help me please?
 
### Log errors: 

Failed to send to silvinogouveia@gmail.com: Failed to authenticate on SMTP server with username "ramgouveia@gmail.com" using 1 possible authenticators Log data: ++ Starting Swift_Transport_EsmtpTransport << 220 smtp.gmail.com ESMTP gw4sm371307wjc.45 - gsmtp >> EHLO 10.7.4.26 << 250-smtp.gmail.com at your service, [79.169.129.11] 250-SIZE 35882577 250-8BITMIME 250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH 250-ENHANCEDSTATUSCODES 250-PIPELINING 250-CHUNKING 250 SMTPUTF8 >> AUTH LOGIN << 334 VXNlcm5hbWU6 >> cmFtZ291dmVpYUBnbWFpbC5jb20= << 334 UGFzc3dvcmQ6 >> TXVzZ3VlaXJhODhD << 534-5.7.14 Please log in via your web browser and 534-5.7.14 then try again. 534-5.7.14 Learn more at 534 5.7.14 https://support.google.com/mail/answer/78754 gw4sm371307wjc.45 - gsmtp !! Expected response code 235 but got code "534", with message "534-5.7.14 Please log in via your web browser and 534-5.7.14 then try again. 534-5.7.14 Learn more at 534 5.7.14 https://support.google.com/mail/answer/78754 gw4sm371307wjc.45 - gsmtp " (code: 534) >> RSET << 250 2.1.5 Flushed gw4sm371307wjc.45 - gsmtp

**Comment by sambarnes90** [comment]
You're not authenticated correctly by the looks of it.

There is some good advice in this thread on the Forum:

https://www.mautic.org/community/index.php/487-configuration-mail-settings/0

> Also, please check with your service provider, normally they block ports. Could be a possibility that your service providers has port 465 and 587 as blocked.

Please come back and let us know if that fixes things.
