### ISSUE TITLE
Inserting forms with <script> or manual copy does not include themes

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2096]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When embedding a Mautic form in a web page, using the recommended method (script tags) or the manual copy does not include the theme styling for the form. This results in displaying a plain, unstyled form to the user. 

Using the Iframe method works as expected. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Create a form
2. Choose a theme for your form
3. Embed it into a web page using script tags of manual copy
4. Open that web page
5. You should see the theme you chose is not applied to the form
4. You s
 
### Log errors: 

There seems to be no related logs.

**Comment by alanhartless** [comment]
The problem here is that themes haven't been updated to look different for forms - so they all look the same. We're planning to fix this in an upcoming release.
