### ISSUE TITLE
MisConception in Entity Setting of Permission for 3rdParty Plugins in File CorePermissions.php

### ISSUE THREAD

**Issue by peteratnsight** [mautic/mautic#2098]
Issue:

For Plugins of Name-Type "FeedManBundle" or "MycompanyhandleBundlesecondnamingBundle" the setting of the permision entity is inconsistent - as bundle name is always stored lower case.

In File
/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php
on line 220  the following needs to be changed:

OLD:                $entity->setBundle(strtolower($bundle)); 
NEW1:                $entity->setBundle($bundle); 
or at least
NEW2:                $entity->setBundle(lcfirst($bundle));

**Comment by dbhurley** [comment]
Is there a reason behind this? Is something broken? Making this change would cause a potential backwards compatibility issue meaning it shouldn't technically be changed until next major release. Is there a bug happening though that this fix would resolve?

**Comment by peteratnsight** [comment]
The bug is that permissions are stored as "feedman" bundle permissions and not as "feedMan" permissions. Therefore the permissions are not valid.

**Comment by escopecz** [comment]
@peteratnsight could you send us a link to the github repo with your plugin so we could test? Or at least the part of the code which cause the invalid permissions?

**Comment by alanhartless** [comment]
We have custom bundles that leverage camel case bundle names and seem to work. If you can provide us with reproducible code - we'll be glad to dig into this. Otherwise, closing for now. Feel free to reopen with code examples for us to test with. Thanks!
