### ISSUE TITLE
Lead reports: contact with most points table shows wrong data

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2099]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I have created a report with 'Contact points log' as source, and I added the 'contact with most points' table to the report in order to quickly find out my best customers. I know that my best ones, which are listed in the report, have 5 points. However, the 'contact with most points' seems to rather show my leads with the least points, as it lists a bunch of those who have three points, and others that only have one. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Give a bunch of points to several contacts
2. Create a custom report with 'Contact points log' as data source
3. Add a buch of contact attributes to the main report
4. In the 'Graph' tab, add the 'contact with most points' table
5. Save your report and access it
6. In the 'contact with most points' table, you should see that your contacts with the highest number of points are not shown.
 
### Log errors: 

No related logs.

**Comment by mqueme** [comment]
Can you provide more information, maybe a screenshot of how this report was created, including filters? I have just tried to replicate this and my report comes up with the correct info. Added order with field Points in descending order.

**Comment by pierreavizou** [comment]
Sure, here are the screenshots. 
The field called "nombre de commandes" is a custom field, but the problem is the same when I create a report with only Mautic's default fields. 

![capture d ecran 2016-08-16 a 13 21 51](https://cloud.githubusercontent.com/assets/7101583/17697374/ca2a91d8-63b4-11e6-88f5-02668dff3fe8.png)

![capture d ecran 2016-08-16 a 13 22 03](https://cloud.githubusercontent.com/assets/7101583/17697380/d386161c-63b4-11e6-9930-0144e9fc81e3.png)

Maybe the problem is coming from the PHP version, you are using PHP 7, and I'm using PHP 5.6.23.

Please don't hesitate to ask me if I can provide you with more details.

**Comment by pierreavizou** [comment]
Interestingly enough, the data is correct and complete when the data source is "contact point log". Hope this helps.

**Comment by mqueme** [comment]
whether you choose contact point log or just contacts you need to add this order : 
![screen shot 2016-08-16 at 12 30 40](https://cloud.githubusercontent.com/assets/1496976/17697559/677dd59c-63ad-11e6-8bf2-89d7c5df4626.png)
 with the log you will only get contacts with points > 0 with the contacts source you will get all of your contacts. Please confirm this works so I can close this issue.

**Comment by pierreavizou** [comment]
This issue seems to be gone in 2.1.0, even when not adding the filter :)

**Comment by pierreavizou** [comment]
Just a precision : 
I have like 10 contacts with 5 points, however the table "contacts with most points" shows only the first 4, and then shows the one with 4 points etc. 
This might be the intended behaviour, or not, pointing this out just in case ;)

**Comment by mqueme** [comment]
Have you checked the dates? logs look at the dates points were added.

**Comment by pierreavizou** [comment]
My bad. The data is correct, sorry about that, I thought I had more leads with 5 points but I didn't.

**Comment by mqueme** [comment]
np
