### ISSUE TITLE
Users - First and last name are required but are not labeled as such

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#2103]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
When creating a user, the first and last name are required but are not labeled as such.

![image](https://cloud.githubusercontent.com/assets/18265735/17095015/c75790dc-5252-11e6-8d8f-edf87530eeab.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | `2.0.1`
| PHP version | `5.6.24`

### Steps to reproduce:
1. Create a new user
2. Submit without having filled the first or last name.
 

### Possible solutions
- Simply add the `required` class to the label
- Use the Symfony form labels instead of this raw one (Which means having two labels rather than one)

The latter is the solution I would lean towards.

I would like some feedback before submitting a (very simple) pull request

**Comment by escopecz** [comment]
Yes, I also thing the second solution would be better
