### ISSUE TITLE
Allow the dashboard widget to be shared on a website

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#2104]
| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? | N |
## Description:

It might be helpful to add a new feature to the dashboard widget - share where the widget content could be embedded to a website. For example, the business owner could share a map of where his contacts come from.

It might look like embed from Google Trends.

**Comment by ldrrp** [comment]
Also useful for embedding into administrative control panels when my ceo doesnt want to login to mautic to see reports..... haha
