### ISSUE TITLE
HTTP API - SMS

### ISSUE THREAD

**Issue by rafaelppaulucci** [mautic/mautic#2110]
Hi guys,
 ill love if u provide an HTTP API based on curl to run with other/generic servers.
Here in Brazil all providers are based on HTTP API to send messages.

Something like that:

http://smsserver/index.php?user=$$$$$&password=$$$$$$&to="PhoneNumber"&msg="Hello World"
If we can control the variables and URL to do this, i think this ill resolve for everyone with any server.

Regards

**Comment by escopecz** [comment]
Hi, just to be sure we understand each other; Mautic does not send SMS by itself. It needs a service like Twilio to send it. Twilio provides such HTTP API as you wrote. Why don't you use API call Twilio directly?

**Comment by rafaelppaulucci** [comment]
Hi @escopecz . I know mautic doesnt send SMS's by itself.
I know Twilio use the same API, but, with TWILIO we only can change the username and password. 
Twilio has not as attractive prices for South America.
If we can select the main custom URL with variables, we can choose ANY server in the world, aways based on our region.

Regards.

**Comment by escopecz** [comment]
As I'm aware, Mautic supports only Twilio right now, so you cannot choose ANY server in the world. Or can you?

**Comment by rafaelppaulucci** [comment]
Correct, it does not support.
This is a feature Request.

**Comment by escopecz** [comment]
Ok, I wasn't sure you are aware it doesn't make much sense to develop such API when there is only one SMS provider supported by Mautic. Maybe some feature requests to implement another SMS providers should be submitted first. Anyway, I'll mark this as a feature request.

**Comment by rafaelppaulucci** [comment]
Maybe I'm not being very clear.
This would be a way to support any other provider Mautic beyond Twillio.

All providers use a POST via the url to send the messages.
If you could fill and customize according to your provider, everything would be easier. Today any software that is integrated with SMS send messages on this way.

Now you understand me?
Regards.

**Comment by escopecz** [comment]
Aha, it is the other way around then. You want some UI to configure your own SMS provider. That makes more sense to me. :+1:

**Comment by rafaelppaulucci** [comment]
Yes! Thanks bro!

**Comment by dalarworld** [comment]
Hi,

I have created a Simple Plug In to Integrate with HTTP Parameter based SMS integration, It just replicate Twilio file and works fine. 

My SMS Provider API Looks like following.

http://bulksms.mysmsmantra.com:8080/WebSMS/SMSAPI.jsp?username=XXXXXX&password=XXXXX&sendername=XXXXX&mobileno=xxxxxx&message=Hello%20Test%20message%20from%20Da

If has status check from api provider and updates contact log file only if message is delivered successfully.

**Comment by hansakoch** [comment]
Cool where is the plugin we can try and test

**Comment by dalarworld** [comment]
[SmsmantraApi.txt](https://github.com/mautic/mautic/files/385573/SmsmantraApi.txt)

At file location, mautic\app\bundles\SmsBundle\Api

Need to create new file. SmsmantraApi.php ( You can name as per your need)

Once you Drop in this file Need to change smsAPI to point to new API we have created. 
mautic\app\bundles\SmsBundle\Config\config.php file has this configured.

Around Line 61 , look for 'other' section. check out class => key value pair.


`  'other' => [
            'mautic.sms.api' => [
                'class'     => 'Mautic\SmsBundle\Api\SmsmantraApi',
                'arguments' => [
                    'mautic.factory',
                    'mautic.twilio.service',
                    'mautic.helper.phone_number',
                    '%mautic.sms_sending_phone_number%'
                ],
                'alias' => 'sms_api'
            `],``

 Only limitation is you need TWILIO working account in place configured as i have done limited changed. Sorry this is not good code but it is working.

**Comment by ldrrp** [comment]
See issue #1731

**Comment by dalarworld** [comment]
@ldrrp  Did you try code i have provided?

**Comment by scottybo** [comment]
@dalarworld this looks fantastic - I'm trying to get integration with 46Elks.

Just to clarify, just your code simply "overwrite" the Twilio function, so that when the SMS trigger happens your code kicks in and you send a webhook request to your service?

If that's the case, do you need to enter any values into the Twilio setup?

+1 for this issue, would love to see webhooks become a campaign action - it would open a huge range of possibilities, including Zapier integration.

**Comment by dalarworld** [comment]
Hi, Twilio Setup vales may be needed since Twilio api is refereed at multiple points. If you provide Twilio api and implement this code System Assume Twilio is configured properly and allows you to set-up campaign and messages. When you send it message it does not use Twilio as it uses new SMS API Class

**Comment by ldrrp** [comment]
I like the whole @scottybo webhook idea.

@dalarworld no i havent tried your code, i only have a live environment setup here and i dont wana mess with it (could get me fired). Not enough time to setup dev yet.

**Comment by zyzioziom** [comment]
@scottybo webhooks as campaign actions are mighty powerful, it enables dozens of integrations for advanced users. Looking forward to this!

**Comment by Julius2Excel** [comment]
@dalarworld  is it possible to fake the process to authenticate Twilio? I don't want to have to go ahead and setup a complete Twilio account and enter addresses to not end up using them. 

Is there a check somewhere I can bypass? or even a generic/demo set of details i could try, just to get it working?

Thanks
Julius

**Comment by sahiljethwani11** [comment]
@dalarworld  I have used your code and replaced twilio api with your's.But still my api is not being used for sending messages.It uses twilio's api,can you please help

**Comment by hachther** [comment]
> @dalarworld Hi, I managed to get it to work with an older version of mautic, but with the last version I get this error: `[2018-05-29 09:57:17] mautic.NOTICE: Exception: Primary SMS transport is not enabled. `
> 
> Do you have any clue on how to solve that?
> Thanks!!

Hi @Moyaga,

If you still have this issue juste make a change in you transport config used this:
`'tag'          => 'mautic.sms_transport',
                'tagArguments' => [
                    'integrationAlias' => 'SMSService'
                ]`

**Comment by sjjy123** [comment]
![image](https://user-images.githubusercontent.com/32361986/62348038-5aeb3d80-b52e-11e9-891a-64968118481c.png)who can tell me, what should I do.
