### ISSUE TITLE
Segments based on points wrong # Contacts view

### ISSUE THREAD

**Issue by luci78** [mautic/mautic#2111]
| Bug report? | 

## Description:
I made a segment based on points with "greater than or" filter. After chron job is executed when i watch # contacts I see much more contacts than I have in my list. For example, i have 365 contacts in my list and my segment filter see 861.

## If a bug:

| Mautic version |  2.0.1 
| PHP version | 5.6

### Steps to reproduce:
1. Go to Segments
2. Click New
3. Click on filters
4. Choose Points(+/-) from dropdown 
5. Select greather than or equal
6. Put 0 on cell value
7. Save and close
8. Waite to execute, or execute manual chron job 
9. Refresh the page and see on # contacts column

**Comment by escopecz** [comment]
Just a quick thought, the contact table shows only the identified contacts. Then there are hidden anonymous contacts. You can see the anonymous contacts by clicking this switch:
![mautic-anonymous-switch](https://cloud.githubusercontent.com/assets/1235442/17219144/98554a8c-54ea-11e6-9a48-229d69fd9168.png)
Does it answer the contact count inconsistency?

**Comment by luci78** [comment]
Yes. Now I have checked. I didn't know that . Thank you
