### ISSUE TITLE
Bug - Unable to see menu dropdown

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#2113]
![image](https://cloud.githubusercontent.com/assets/985837/17153860/9872dc86-534c-11e6-97bd-07b1e5c0d494.png)

Unable to see the dropdown menu on mautic v2.0.1

Browser - Chrome 51
Location /s/contacts/view/####

This also occurs in other places too like the events page you will notice its under the tables.

Must have menu collapsed.

**Comment by dbhurley** [comment]
I can replicate.

**Comment by escopecz** [comment]
I can replicate as well. I tried to remove all the z-indexes from other elements and added `z-index: 999999` to the submenu, but it is still the same :/

**Comment by dbhurley** [comment]
This did it:
https://github.com/mautic/mautic/commit/92896d17dbb4e3942cd9404c1270511d621f5dc7#diff-71e5f89053d68b98a8fe7ae666eb23d9
