### ISSUE TITLE
Edit a contact interface stuck, edit not done - v1.4.1

### ISSUE THREAD

**Issue by skaraliu** [mautic/mautic#2120]
When editing a contact, the save and apply options gets stuck, blocked, and the change doesn't apply to that contact. 
1 - Enter contact page
2 - Edit contact
3 - Make a change - tested several options
4- Save - the page gets stuck, buttons go to state not actionable
5 - Apply - the page gets stuck, buttons go to state not actionable
6 - The modifications is not done.
Cleared the cache, same results
Delete the contact works...

**Comment by escopecz** [comment]
I'm not quite sure someone will fix bugs on an old Mautic version, but could you provide the logs to get developers a clue what is breaking it?

**Comment by skaraliu** [comment]
First i didn't know i was on an older version, i watch carefully those notifications for upgrade. Is there a must do to have the Mautic up to date?

Second, in the log file of the specific day when tried those steps mentioned, in the log there where no entries to be connected to such a failure.

This would be one of them
[2016-07-28 16:48:18] mautic.NOTICE: PHP Notice: Undefined index: first_time - in file /home/myfolder-root/public_html/marketing/app/bundles/PageBundle/Helper/PointActionHelper.php - at line 73 [] []

And this would be the other log error
[2016-07-28 15:46:47] mautic.WARNING: IP LOOKUP: The file "/home/myfolder-root/public_html/marketing/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []

**Comment by dbhurley** [comment]
Due to this being on an outdated version I'm going to close this issue. The logs are notice/warning and not error so these should not be stopping the ajax actions from occurring. If this is still an issue in 2.0.1+ then please report again or reopen. 👍

**Comment by escopecz** [comment]
@skaraliu your server must meet the [minimal requirements](https://www.mautic.org/download/requirements/) for Mautic 2 to display the update notice. Also, read the [upgrade instructions](https://www.mautic.org/community/index.php/4823-2-0-0-released), because Mautic 2.0.0 broke some backward compatibility
