### ISSUE TITLE
Lead import only support UTF-8 CSV (but Excel not)

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2121]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Importing Leads form a CSV file generated by Excel doesn't works with special caracters.
Excel encode CSV files with local enconding and not UTF-8, and Mautic only uses UTF-8.
It could be great to have an option to "utf8_encode" on the first import step.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.19

### Steps to reproduce:
1. Generate a CSV file with some special caracters like é à ñ in the firstname from Excel
2. Import it in Mautic

**Comment by escopecz** [comment]
It is PITA to convert encoding from one to another in PHP. I would recommend to open the Excel sheet in Open Office Calc and export it to CSV from there. This program will allow you to export it in UTF-8.

**Comment by chandon** [comment]
Not that much, see #2129

**Comment by escopecz** [comment]
Yes, exactly. The hard part is to guess what encoding the file has. Then it is a piece of cake. I bet most users doesn't know what an encoding is and if they do, they will not know what encoding their CSV uses. But it's better then nothing I guess. Do you think you could write a docs which would guide them how to find out the encoding of their CSV file?

**Comment by chandon** [comment]
In fact, i don't really know how to guess encoding...

Php as got **mb_detect_encoding**, but for my quite usual encoding ISO-8859-1, it often find another encoding, leading to mistakes...

I really don't know how to determine the local encoding charset of a Windows System (it changes from one country to another...)

**Comment by escopecz** [comment]
Yes, that is the bottleneck of this improvement. We let users to set the encoding, but they don't have any way to know what encoding they should select. Even PHP cannot guess that in many cases. That's why I rather advice to use the Open Office Calc and export the CSV in UTF-8.

**Comment by chandon** [comment]
I think that 95% of the users will use Excel (and not Open Office Calc). If they manage to export a sheet as CSV, it'll be a pain to convert it to UTF-8...

For me, Open Office Calc is not a solution. It opens my 130MB file witinh 5 minutes, and excel only 10s...

**Comment by escopecz** [comment]
Yes, I know Excel is more used than OOC and it has better features than OOC, but it lacks the encoding choice when exporting the sheet to CSV. And that is what we are discussing here. So the question is, if you export a sheet to CSV, how can you find out what encoding it uses?

If there is no way how to find that out, I think it is better to use the tool which helps you with that. And I know that OOC can help you with that. Let me know how you do it, please.

**Comment by Salamek** [comment]
BTW Guys, Open Office is "deprecated" use Libre Office instead

**Comment by chandon** [comment]
To find the encoding of an CSV file, open Excel, go to the "data" tab, then import an external "text file", select your CSV file and test the encoding list (the preview of the CSV change when selecting another encoding). Check that the encoding is the good one for your CSV file, you're done ! 

Now you know your CSV files encoding

**Comment by DensetsuNo** [comment]
To solve the problem on Mac you can download Table Tool (https://github.com/jakob/TableTool) and follow these instructions:
1) Copy the rows and columns that you want to import in Mautic (including the headers);
2) Paste them in Table Tool;
3) Select UTF-8 at the bottom of the page as selected encoding (it is selected by default)
4) Save it and voilà, ready to be imported in Mautic.
