### ISSUE TITLE
Edit Contact -> 500 Internal Server Error. Only for contacts on certain campaign

### ISSUE THREAD

**Issue by dillis** [mautic/mautic#2122]
Bug report

## Description:
-When I go to a Contact page and click Edit, the system displays a 500 Internal Server Error (screenshot attached).
-This is only happening for 3350 contacts that were just added to a particular campaign. Not sure if this is relevant, but details about campaign below.
----In that campaign, the contact is checked to see whether textfield "StageX" = None. If NOT, then unsubscribes from campaign. It is currently erroneously unsubscribing contacts from this campaign. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version |    Mautic Pro (hosted)
| PHP version | 

### Steps to reproduce:
1. Go to a contact page, and then click Edit. Should be one of the 3350 contacts in the "New CFPB Contacts" segment. 

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

(Using hosted/pro version of Mautic - don't have access)

**Comment by dillis** [comment]
![screen shot 2016-07-27 at 9 54 18 am](https://cloud.githubusercontent.com/assets/16729413/17183803/2e7e37de-53f7-11e6-8d8b-ebce101f946e.png)

**Comment by dillis** [comment]
i'm also getting the same error when i try to edit the campaign...

**Comment by scottybo** [comment]
+1

**Comment by escopecz** [comment]
Guys, the logs are important to find out what is going on. If you don't have an access to the logs area, contact your hosting provider and ask if they could provide the logs.

**Comment by dillis** [comment]
Hi John! I'm actually using the hosted version of Mautic...

**Comment by escopecz** [comment]
@dillis would you mind contact the support of mautic.net and ask them to give you the logs? It's like any other hosting.

**Comment by luizeof** [comment]
Hi @escopecz  @dillis ... i have same problem ...

this is the log says:

mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "DOMDocument" from the global namespace. Did you forget a "use" statement?" at /var/www/html/marketing.orangeweb.com.br/vendor/symfony/config/Util/XmlUtils.php line 52 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"DOMDocument\" from the global namespace.\nDid you forget a \"use\" statement? at /var/www/html/marketing.orangeweb.com.br/vendor/symfony/config/Util/XmlUtils.php:52)"} []

**Comment by escopecz** [comment]
@luizeof you are missing the XML PHP module. Contact your hosting provider to install it for you or install it yourself if you have your own VPS.

**Comment by dillis** [comment]
@escopecz I've contacted mautic.net for the logs.
