### ISSUE TITLE
Email To: for a contact without name

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2131]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When a contact has an email but no firstname and no lastname, email is send to " " < the@email.com >.
When firstname and lastname are empty, the "To:" field should be email only, without " " and < >

#### Steps to test this PR:
1. Create a user without firstname and lastname
2. Send an email with mautic.
3. Check To header => To: " " < email@email.com > . It should be To: email@email.com to avoid display problem with most email clients

**Comment by escopecz** [comment]
@chandon could you please write steps to replicate this issue?

**Comment by chandon** [comment]
@escopecz sorry, i did it in the PR... initial comment updated...

**Comment by chandon** [comment]
My fix was incomplete
