### ISSUE TITLE
On unsub page, resubscribe gets a 500 page error

### ISSUE THREAD

**Issue by skaraliu** [mautic/mautic#2149]
Latest version.
On the unsubscribe page, when a user gets resubscribed, gets a 500 page classic Mautic error.
500 Internal Server Error

**Comment by dbhurley** [comment]
Hi! I'll take a look but if you remove all the questions from the issue template in the future you'll probably just get your issue closed. The issue template helps to explain the problem to everyone and make it easy for others to replicate.

**Comment by skaraliu** [comment]
sorry.
