### ISSUE TITLE
Segment Email - Errors Froala Editor

### ISSUE THREAD

**Issue by cerebrumbr** [mautic/mautic#2155]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Menu > Channels > Emails > New Segment Email > Select > Contact Segment

After "Saved" without select contact segment.

Presented this alert.

Object(Doctrine\Common\Collections\ArrayCollection): At least one contact segment is required.

![00](https://cloud.githubusercontent.com/assets/2263217/17279895/b06d9a2e-5757-11e6-85ec-6f5a9845c649.png)

And presented javacript errors in firebug console.

SyntaxError: missing ; after for-loop condition - /media/js/libraries.js?v2.0.1

Error: Method popups.hideAll does not exist in Froala Editor. - /media/js/libraries.js?v2.0.1

![01](https://cloud.githubusercontent.com/assets/2263217/17279898/b8ecae9c-5757-11e6-822f-159f369cbd1f.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6

### Steps to reproduce:
1. Menu > Channels > Emails > New Segment Email > Select > Contact Segment
2. After "Saved" without select contact segment.
3. Object(Doctrine\Common\Collections\ArrayCollection): At least one contact segment is required.
4. Close Mautic
5. Open Menu > Channels > Emails > Email Segment > Edit
6. See javascript errors in firebug console.

**Comment by escopecz** [comment]
The first issue, the odd error message is fixed in https://github.com/mautic/mautic/pull/2157
The second issue with Fire Fox is fixed in https://github.com/mautic/mautic/pull/2032

Please, next time create 2 separate issues.
