### ISSUE TITLE
Feature Request: Zurmo CRM integration

### ISSUE THREAD

**Issue by trevorhutt** [mautic/mautic#216]
Is it possible to have a plugin developed to integrate Campaigns (coming from Zurmo) and Leads (coming from Mautic)?

Can you point me to source code/documentation so I can look into adding this functionality myself.

**Comment by alanhartless** [comment]
Hi Trevor,

It's definitely possible but not on the roadmap yet. :-)  I've tagged this as a feature request.

Developer documentation is in the works. We'll post an announcement in the forum Announcement channel once it's ready.

Thanks!
Alan

**Comment by trevorhutt** [comment]
Thanks

**Comment by bobwol** [comment]
I'd love this feature too. Wordpress + Mautic + Zurmo = best tools ever

**Comment by rodrideme** [comment]
+1

**Comment by hansakoch** [comment]
+1

**Comment by benlauff** [comment]
+1

**Comment by damianatorrpm** [comment]
Hello people,

I can do this as a side job. If you're interested contact me via PM @damianatorrpm_at_gmail.com
and we can agree on it via freelancer / fiver / workup or else.
