### ISSUE TITLE
Problem with red leg of page visit check after e-mail send

### ISSUE THREAD

**Issue by cfern87** [mautic/mautic#2171]
Hey guys, not sure if this is a bug or an operator error.

I'm trying to create a campaign that sends an email. If a page hit to a particular page hasn't been made 7 days after the email sent, send a reminder. If it has, send e-mail 2 with the same logic (page hit via a different url, if they don't visit it within 7 days, send a reminder, etc). 

For this I have an e-mail send action, linked to a page hit, and an email send action configured - one to red and one to green. The red email action has a 7-day delay. 

My issue is that each of the emails that are sent send ALL of the 7-day delay e-mails at once. I've attached a screenshot of the chain so you can get an idea. 
I saw somewhere that this time is dependent on the time that they are added to the segment, but that seems ridiculous and I can't think of another way to structure this campaign (aside from MAYBE breaking it up into multiple campaigns/segments)

I'm using the Mautic hosting.

Just as a note: I changed the red delays to 1 day for testing.

Any ideas?

![screen shot 2016-07-30 at 01 15 34](https://cloud.githubusercontent.com/assets/11179641/17371140/d24e525c-596c-11e6-8fe0-617d6084b81a.png)

**Comment by dbhurley** [comment]
I'm closing this due to not following proper bug reporting template. GitHub isn't a support location as much as it is bug tracking/reporting. If you have a bug you'd like to report I'd encourage you to resubmit following the proper method.

**Comment by cfern87** [comment]
I can appreciate this not being closed for following the template, but what IS the template? This is most definitely a bug. I emailed support, they directed me here. How do I need to position this conversation so that this can be resolved?
