### ISSUE TITLE
E-Mails not sending in hosted Mautic Instance

### ISSUE THREAD

**Issue by cfern87** [mautic/mautic#2173]
This is most definitely a bug that seemed to start with the latest version of Mautic being installed on my hosted Mautic instance. 

I've got 3 contacts now that have e-mails queued to send from days ago and they're just not sending.

Not sending this e-mails is a dealbreaker for me. It's important that I can depend on my marketing tool.

It seems to happen randomly and when the e-mails are scheduled to send and time goes by like this it seems like they never do. I'm hosted w/ Mautic directly.

This photo was taken 8/3/16
![screen shot 2016-08-03 at 11 28 48](https://cloud.githubusercontent.com/assets/11179641/17371377/9c534526-596d-11e6-9370-1f876b929aaa.png)

**Comment by dbhurley** [comment]
Closing for same reason as other issue (#2171)

**Comment by cfern87** [comment]
I can appreciate this not being closed for following the template, but what IS the template? This is most definitely a bug. I emailed support, they directed me here. How do I need to position this conversation so that this can be resolved?

**Comment by escopecz** [comment]
@cfern87 when you open a GH issue, there is a pre-filled template of questions the dev team need you to answer so they could fix the bug. You removed all of it. That's why the issue was closed. Try to open a new one and follow the template.
