### ISSUE TITLE
Form duplicate submission control

### ISSUE THREAD

**Issue by paulofelixjunior** [mautic/mautic#2176]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? | Y |
## Description:

Forms in Mautic can be very useful to run specific surveys or getting information which you do not need the complexity and/or resources of a SurveyMonkey, Gizmo or tools like that.

However currently it is possible to a user submit the same form multiple times.

My suggestion is to create a parameter in form properties that allow admin to select if the form allows (or not) duplicate answers. The duplicate control will be based solely in the contact registry (IP and/or email).

**Comment by dbhurley** [comment]
Setting a form to "Kiosk Mode" will allow multiple submissions from the same IP address. Currently I believe it does still restrict on the email address though.

**Comment by paulofelixjunior** [comment]
OK, got it. My point is just the opposite: NOT allowing duplicate answers. I'm using several forms with Kiosk Mode = off - and using a not logged device I answered the same form multiple times.... and all of them were entered in the submission record. tks!

**Comment by dbhurley** [comment]
Ah! That's strange, I thought repeat submissions updated the existing one. I'm going to update this to `Bug` instead of feature. 👍

**Comment by nethunter** [comment]
This still happens to me - the same email/same form being submitted each time the form is submitted. I submit via Ajax, if that matters.
