### ISSUE TITLE
Add Email Responses as Notes for Contact

### ISSUE THREAD

**Issue by sambarnes90** [mautic/mautic#2178]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? | Y |
## Description:

One feature that I think could be very useful is the ability to add inbound emails to a monitored address as notes on a contact.

I realise that this is bordering on CRM functionality, and nobody wants Mautic to become a CRM!

However, in terms of analysing a particular campaign it would be useful to be able to see why an email didn't convert.

Say for example we're trying to move people from Stage 1 to Stage 2 in a campaign.

After a few weeks, we could come back to Mautic and check a few of the Stage 1 contacts who hadn't moved to the next stage and look at their responses to our emails.

Is there a particular reason that this email failed?

Maybe it's something as simple as a broken link?

Perhaps it looks incorrectly formatted on certain devices?

Perhaps our pricing is too high?

etc.

This data would be really effective, in our business at least, to help improve the effectiveness of our campaigns.

I don't have the technical skills (yet) to be able to create this. 

But from what I've read, perhaps integrating something like [PHP-Imap](https://github.com/barbushin/php-imap) into Mautic will help receive the emails?

From there it's just a case of cross referencing with the contact list? 

Or can the tracking pixel in the email detect when a return email is sent?

Perhaps we can create a bcc address to all responses that is then added to the relevant contact?

Just thoughts at this stage - just wondered whether or not anyone else would find this functionality useful?

**Comment by dbhurley** [comment]
Yes, this is something that's been discussed for a while. The ideal solution would involve listening to a mailbox and importing mail then attaching to the correct contact. I believe we can build on the bounce functionality previously written which also listens to an inbox. There are some limitations but I think they can be overcome. The biggest challenge is finding a dev with the time to write the code! 😄

**Comment by pravinuttarwar** [comment]
Any updates on this?
