### ISSUE TITLE
Error: Cannot use object of type Mautic\LeadBundle\Entity\UtmTag as array

### ISSUE THREAD

**Issue by ikolubr** [mautic/mautic#2182]
What type of report is this:

| Q  
| ---| ---
| Bug report? | 

## Description:
I'm getting this erros on Mautic log and error when I try to access a form:
mautic.ERROR: Error: Cannot use object of type Mautic\LeadBundle\Entity\UtmTag as array - in file /var/www/mail.oficinaderedacao.com/htdocs/app/bundles/LeadBundle/Helper/EventHelper.php - at line 82 [] []

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
2.0.1
| PHP version | 
5.6
### Steps to reproduce:
1. 
2. 
 
### Log errors: 

mautic.ERROR: Error: Cannot use object of type Mautic\LeadBundle\Entity\UtmTag as array - in file /var/www/mail.oficinaderedacao.com/htdocs/app/bundles/LeadBundle/Helper/EventHelper.php - at line 82 [] []

**Comment by escopecz** [comment]
Could you please provide steps to reproduce this error?

**Comment by ikolubr** [comment]
So, if I create a segment form and use the option Record UTM Tags and try to use the form, I get that error. As soon as I remove it, it works.

**Comment by mqueme** [comment]
Hi I've tried this in Mautic version 2.0.1 PHP version 7.0.0 and I am not getting any errors, UTM tags are recording correctly. Please look at the minimum requirements here https://www.mautic.org/download/requirements/

**Comment by mqueme** [comment]
I have not been able to replicate this error, closing due to lack of feedback.
