### ISSUE TITLE
Dynamic content in email with Json and Mustache

### ISSUE THREAD

**Issue by natansouza** [mautic/mautic#2185]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? | Y |
## Description:

A feature that would be extremely useful would be to allow mounting email dynamically obtained with json content through requests to another API. Like what is done in AgileCRM JSON IO , this link https://www.agilecrm.com/marketing-automation-software can see how it works. With this feature would be possible to trigger emails to automate many campaigns . I hope other people find useful and can develop such feature.

It would also be very useful to support mautic mustache to make the use of content obtained via request ( JSON )

Here sample like works in AgileCRM https://github.com/agilecrm/agile-crm-json-io-node

**Comment by natansouza** [comment]
@escopecz is possible create this feature?

**Comment by escopecz** [comment]
@natansouza sure it is. Although there is also a feature request about executing twig syntax in the email content. Maybe it's better to use twig since it is already used in the theme files.

**Comment by natansouza** [comment]
@escopecz ok! If It is possible to make calls broaden the JSON automation possibilities.

**Comment by dongilbert** [comment]
#2574 doesn't solve this in the way you've described, but it does create the groundwork that could be built on to create something similar to what you're describing.
