### ISSUE TITLE
Doctrine exception when long referer

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2187]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Sometimes it seems that the referer URI string is quite long and this causes an DB exception. See logs attached.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.23
 
### Log errors: 

`[2016-08-05 05:18:53] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO lead_utmtags (date_added, query, referer, remote_host, url, user_agent, utm_campaign, utm_content, utm_medium, utm_source, utm_term, lead_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["2016-08-05 05:18:53", "a:14:{s:10:\"page_title\";s:51:\"Billets L.E.J en concert \u00e0 l'olympia de Paris 2016\";s:13:\"page_language\";s:2:\"fr\";s:13:\"page_referrer\";s:0:\"\";s:8:\"page_url\";s:122:\"https:\/\/my-website.com\/fr\/tickets-de-concert\/variete-francaise\/tickets-lej\/tickets-lej-paris-318.html?utm_source=google\";s:10:\"utm_medium\";s:3:\"cpc\";s:8:\"utm_term\";s:11:\"+lej +paris\";s:12:\"utm_position\";s:3:\"1t1\";s:5:\"gclid\";s:88:\"CjwKEAjwz4u9BRCbioK3stnBznESJADA75xbUt4iUY5pYnYYLuKHkuYLxCkotNNlDbjtmDKwtuisKRoCO4zw_wcB\";s:11:\"fingerprint\";s:32:\"7ce71cb6ccc0d8e349c0ad638ec9023e\";s:10:\"resolution\";s:7:\"640x360\";s:15:\"timezone_offset\";s:4:\"-120\";s:8:\"platform\";s:12:\"Linux armv7l\";s:12:\"do_not_track\";s:7:\"unknown\";s:7:\"adblock\";s:5:\"false\";}", "https:\/\/my-website.com\/fr\/tickets-de-concert\/variete-francaise\/tickets-lej\/tickets-lej-paris-318.html?utm_source=google&utm_medium=cpc&utm_term=%2Blej%20%2Bparis&utm_position=1t1&gclid=CjwKEAjwz4u9BRCbioK3stnBznESJADA75xbUt4iUY5pYnYYLuKHkuYLxCkotNNlDbjtmDKwtuisKRoCO4zw_wcB", null, "https:\/\/my-website.com\/fr\/tickets-de-concert\/variete-francaise\/tickets-lej\/tickets-lej-paris-318.html?utm_source=google", "Mozilla\/5.0 (Linux; Android 5.0.1; ALE-L21 Build\/HuaweiALE-L21) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/51.0.2704.81 Mobile Safari\/537.36", null, null, "cpc", null, "+lej +paris", 18493]:  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'referer' at row 1" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO lead_utmtags (date_added, query, referer, remote_host, url, user_agent, utm_campaign, utm_content, utm_medium, utm_source, utm_term, lead_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"2016-08-05 05:18:53\", \"a:14:{s:10:\\\"page_title\\\";s:51:\\\"Billets L.E.J en concert \\u00e0 l'olympia de Paris 2016\\\";s:13:\\\"page_language\\\";s:2:\\\"fr\\\";s:13:\\\"page_referrer\\\";s:0:\\\"\\\";s:8:\\\"page_url\\\";s:122:\\\"https:\\/\\/my-website.com\\/fr\\/tickets-de-concert\\/variete-francaise\\/tickets-lej\\/tickets-lej-paris-318.html?utm_source=google\\\";s:10:\\\"utm_medium\\\";s:3:\\\"cpc\\\";s:8:\\\"utm_term\\\";s:11:\\\"+lej +paris\\\";s:12:\\\"utm_position\\\";s:3:\\\"1t1\\\";s:5:\\\"gclid\\\";s:88:\\\"CjwKEAjwz4u9BRCbioK3stnBznESJADA75xbUt4iUY5pYnYYLuKHkuYLxCkotNNlDbjtmDKwtuisKRoCO4zw_wcB\\\";s:11:\\\"fingerprint\\\";s:32:\\\"7ce71cb6ccc0d8e349c0ad638ec9023e\\\";s:10:\\\"resolution\\\";s:7:\\\"640x360\\\";s:15:\\\"timezone_offset\\\";s:4:\\\"-120\\\";s:8:\\\"platform\\\";s:12:\\\"Linux armv7l\\\";s:12:\\\"do_not_track\\\";s:7:\\\"unknown\\\";s:7:\\\"adblock\\\";s:5:\\\"false\\\";}\", \"https:\\/\\/my-website.com\\/fr\\/tickets-de-concert\\/variete-francaise\\/tickets-lej\\/tickets-lej-paris-318.html?utm_source=google&utm_medium=cpc&utm_term=%2Blej%20%2Bparis&utm_position=1t1&gclid=CjwKEAjwz4u9BRCbioK3stnBznESJADA75xbUt4iUY5pYnYYLuKHkuYLxCkotNNlDbjtmDKwtuisKRoCO4zw_wcB\", null, \"https:\\/\\/my-website.com\\/fr\\/tickets-de-concert\\/variete-francaise\\/tickets-lej\\/tickets-lej-paris-318.html?utm_source=google\", \"Mozilla\\/5.0 (Linux; Android 5.0.1; ALE-L21 Build\\/HuaweiALE-L21) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/51.0.2704.81 Mobile Safari\\/537.36\", null, null, \"cpc\", null, \"+lej +paris\", 18493]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'referer' at row 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'referer' at row 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'referer' at row 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []`

**Comment by escopecz** [comment]
@alanhartless do you think we'll have to update all occurrences of
`$builder->addNullableField('referer', 'string');`
to
`$builder->addNullableField('referer', 'text');`
or is there a better solution?

**Comment by alanhartless** [comment]
Ugh - I cringe at having to do another change to some of those huge tables. At least page hits already uses text. Form submissions, asset downloads, and utm tags look to still have it as a string and they have the potential to be big as well although probably not as big as page hits. 

Our only other option is to truncate the string to 255 in the entity which is probably not the best solution. :-/

**Comment by escopecz** [comment]
Yeah, truncating would kind of make the referrer information worthless. I think the schema update is the only option. Better to do it now than next year. The tables are still growing :)

**Comment by alanhartless** [comment]
True that

**Comment by martinstr** [comment]
I have the same problem.
