### ISSUE TITLE
E-mails hung up and not sending

### ISSUE THREAD

**Issue by cfern87** [mautic/mautic#2194]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |Yes
| Feature request? | No
| Enhancement? | No

## Description:
This is most definitely a bug that seemed to start with the latest version of Mautic being installed on my hosted Mautic instance.
I've got 3 contacts now that have e-mails queued to send from days ago and they're just not sending.
Not sending this e-mails is a dealbreaker for me. It's important that I can depend on my marketing tool.
It seems to happen randomly and when the e-mails are scheduled to send and time goes by like this it seems like they never do. I'm hosted w/ Mautic directly.

It *could* be because I'm making minor modifications to the campaign as I'm adjusting things, but I say no documentation that said that this would happen, and I was able to do it before the upgrade with no issues. I also am making the assumption that campaign items fire sequentially (that is, if I have the top node of a step chained to the bottom node of another, the latter step will not be executed until the former)

This photo was taken 8/3/16

![9c534526-596d-11e6-9370-1f876b929aaa](https://cloud.githubusercontent.com/assets/11179641/17442719/0ecee608-5b05-11e6-9fa9-9f02211023ea.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  
| PHP version | Unsure - this is a hosted instance

### Steps to reproduce:
This happens about 20% of the time, I have not found a reliable method to reproduce. I've seen this with stupid simple (join a list, send an email) campaigns to more complex ones. It happens most often with a send e-mail action configured after a page view action.
The best reproduceabe steps I can fathom are:
1. Create a campaign that activates from a segment addition
2. Add a page view filter as the next step
2. Send an email on the green side of the filter. 
 
### Log errors: 
Don't have access to these as this is a hosted instance at mautic.org

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by zyzioziom** [comment]
@cfern87 Shame you have no logs available, this is propably server-side problem.
You could try switch to Mailgun for e-mails - it gives you 10000 super reliable e-mails per month and detailed logs.

Example config in Mautic's Email settings: http://imgur.com/DzPHWyU

**Comment by cfern87** [comment]
The issue seems to be that the mail isn't actually sending the message. Almost like a cron job is hung up. I'm not sure that using an SMTP service would help if it can't even execute the task.

**Comment by escopecz** [comment]
@cfern87 please report his to the support of mautic.net service via the Help button in your Mautic instance. They have to go through your logs and discover the problem.

**Comment by cfern87** [comment]
I've done that SO many times and get absolutely 0 response. I've confirmed
it's not my email.

I'll try again and cite this github ticket.


-Chris Fern
CEO, Simple Business Solutions <http://simplebusinesssolutions.org/>
CTO, R3SET <http://www.whatisthereset.com/>
Founder, Mindful Money <http://practicemindfulmoney.com/>


To schedule a 30-minute appointment with me, visit bit.ly/chrisfern

**Comment by alanhartless** [comment]
Closing since this is not directly related to Mautic but the SaaS platform.
