### ISSUE TITLE
Segment filter does not work if one uses German language

### ISSUE THREAD

**Issue by morokel** [mautic/mautic#2197]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
The segment filter does not work if one has enabled the German language in Mautic. The filter shows all contacts and not just these who are part of a specific segment.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.0.1
| PHP version | PHP7

### Steps to reproduce:
1.  Change Mautic language to German
2.  Go to the segment section
3.  Choose a segment and click on "Kontakte anzeigen" ("view contacts")

**Comment by dongilbert** [comment]
Fixed in #2282
