### ISSUE TITLE
Save form referrer URL as hidden field

### ISSUE THREAD

**Issue by patrykkalinowski** [mautic/mautic#2200]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? |  |
| Enhancement? | X |
## Description:

In contact timeline form submissions have saved referrer URLs.

These URLs should be also saved as form field available to reuse later, for example you could find leads who submitted form X on URL Y.

I use this feature myself in Hubspot very often, it's also used in Intercom if I recall correctly. Don't know about other marketing automation systems. It's very helpful as you can reuse the same form on many pages (ex. product pages) instead of creating one form for each page.

**Comment by zyzioziom** [comment]
The easy way to do it would be just adding to form generation script something like this:

`document.getElementById("mauticform[referrer]").value = document.url;`

**Comment by michiellucas** [comment]
+1

**Comment by T1ro** [comment]
Waiting for this feature to be part of Mautic.. Any idea when this can be implemented?

**Comment by arikmeyer** [comment]
+1

**Comment by luizeof** [comment]
@kuzmany this is a great feature to known where leads came from across blog posts, websites widgets and even partners.

Do you have some time to get this done?

Thanks for your great work!

**Comment by kuzmany** [comment]
@luizeof 
No I don't have free time for you and your business.
I have to pay bills, please stop mention me without payment offer. 
Thank you.

**Comment by escopecz** [comment]
I fact, I'll close this feature request. There is a workaround provided by @patrykkalinowski if you need referer as a field.

The reason is that the referer information is already being saved to every submission. Not as a field, but as a special column in the form_submissions table. So all it needs is to add that field to the filters so you could work with it.

**Comment by luizeof** [comment]
@kuzmany Forgive me if you get that way. I've seen you working with forms and data entry lately and thought you might see this item. Sorry for the inconvenience.
