### ISSUE TITLE
Command progress bar goes to stderr instead of stdout

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#2202]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Getting a lot of emails after upgrading to mautic 2.0.1 from cron job, the output seems to be stdout. I have it setup to set up only when there is an stderr, so is the output not routed appropriately? Is anyone having the same issue?

`php /path/to/app/console mautic:campaigns:trigger --env=prod > /dev/null`

Email contents 
```0/6 [>---------------------------]   0%
6/6 [============================] 100% 0/6 [>---------------------------]   0%
6/6 [============================] 100% 0/8 [>---------------------------]   0%
1/8 [===>------------------------]  12%
2/8 [=======>--------------------]  25%
3/8 [==========>-----------------]  37%
4/8 [==============>-------------]  50%
5/8 [=================>----------]  62%
6/8 [=====================>------]  75%
8/8 [============================] 100%```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 7.0.9

### Steps to reproduce:
1. crontab -e
2. ```MAILTO="hosting@mycompany.com"
*/5     *       *       *       *       php /path/to/app/console mautic:campaigns:trigger --env=prod > /dev/null```
 
### Log errors: 
N/A

**Comment by escopecz** [comment]
The change happen in Symfony 2.8 actually. The solution is described here:

https://github.com/symfony/symfony/issues/18744

I'll try to implement it this week.

**Comment by escopecz** [comment]
@jordan8037310 would you be able to test https://github.com/mautic/mautic/pull/2255 and comment bellow that PR if it fixed your problem?

**Comment by jordan8037310** [comment]
Tested in #2255 @escopecz
