### ISSUE TITLE
Bounce problem

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2204]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/Helper/MessageHelper.php#L295

I don't know what you want to do here, but :  
1) stat["retry_count"] is a string ("0") so stat["retry_count"]++ will not change the value of this string (and it'll not be equals to 1...)
2) you want to update "retry_count" with is orignal value ? because if you set ++ after it, the "retry_count" field will be updated with the already existing value?.Perhaps you want to do ++stat["retry_count"] ? or even ++intval(stat["retry_count"]) ?

**Comment by escopecz** [comment]
What is the problem exactly?

1) is correct
```
$stringZero = '0';
$stringZero++;
var_dump($stringZero);
```
will output `int(1)`
You can run the code here: http://sandbox.onlinephpfunctions.com/code/14a672529fbf6be751c023d1fa4ff654438042f2

**Comment by chandon** [comment]
@escopecz yes you're right, i did a mistake with 1). But for 2), i don't understand the purpose or retry_count++. And it seems that soft bounces are not retried (or at least "unrecognized" bounces)

**Comment by alanhartless** [comment]
Thanks @chandon, yea it should be a pre-incrementation. Fixed in #2338
