### ISSUE TITLE
Failed email disappears from contact "Recent events"

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2206]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When sending an email, if the email is detected as failed (bounce), it disappears from the "Recent events" timeline of the contact

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.2-dev
| PHP version | 5.6

### Steps to reproduce:

1. Create a contact with a "hard bounce" email
2. Send an email to this contact
3. Check the timeline : "Email is sent"
4. Launch the **mautic:fetch:email** command to get the bounces back
5. Contact is now tagged as "bounced", but the email doesn't appears in the timeline anymore

**Comment by dongilbert** [comment]
Fixed in #2327
