### ISSUE TITLE
[Feature] Form Field for Attachments

### ISSUE THREAD

**Issue by MaxOnTheHill** [mautic/mautic#221]
Add form field type to add ability to upload attachments with form submissions.

Would need to have a couple of variables in the field settings, such as:
- file type to accept
- directory where it is saved
- send uploaded files with email actions:  email to lead | email to user | send form results

In v2+ could have available via the assets area (eg. option to be available and sorted by asset category when uploaded), have extended form fields add-on, etc ... but v1 just need to get the option available.

Seems most of the form stuff is here:
https://github.com/mautic/mautic/tree/41ced3a8454de4950c7da4c81291993737783930/app/bundles/FormBundle

**Comment by MaxOnTheHill** [comment]
@alanhartless we have developed this and tested as core enhancement ... finishing testing later today on our current implementation.
-> but maybe you want to keep separate as additional form fields add-on which can be extended further, or should we submit a pull request as part of core general functions?
- let me know your preference and we can do as per core team preferences.

**Comment by alanhartless** [comment]
Hey Max,

Congrats!

It's really up to you. If you would like to continue developing and maintaining it, then maybe packaging it up as an addon where you can manage distribution would be best.

But if you would like the Mautic team and community to help maintain it, then submit a PR with it integrated directly into core and we'll send it through the process. 

Thanks!
Alan

**Comment by alanhartless** [comment]
Just as a FYI, here's a link to the Governance page which goes over the PR process a bit. https://www.mautic.org/about/governance.

**Comment by MaxOnTheHill** [comment]
OK ... so from what you are saying is that it may be better to have as an add-on if people want it .... otherwise may burden core to maintain and if people prefer not to use it.

Will have a chat to team and get repackaged as an add-on .... hopefully, not too much extra work/reworking :(  

Are there similar rules around add-ons and do you guys know yet what the guidelines for a commercial/add-on directory/marketplace will be?

**Comment by dbhurley** [comment]
No, that's not the idea at all. Simply that just because a PR is submitted and tested does not mean it will be automatically merged. I think @alanhartless just wanted to make sure you were aware of it. By all means, submit the PR, we are all about adding things to core that improve the product for everyone!

**Comment by MaxOnTheHill** [comment]
OK ... will submit PR and if not accepted, we'll do as add-on ... at least for our own use if not in core.
Thx for guidance.

**Comment by alanhartless** [comment]
Hey Max!

Yea, that's definitely not what I meant. I apologize if "burden" is what came across in the explanation of options. It's quite the opposite of a "burden" as we want the community to contribute to core! It's kind of the whole reason we wanted this thing to be open sourced and community driven :-)

I was just laying out your options.  Not everyone will want their customizations/contributions absorbed into core as they may want to be able to work on it outside release cycles, sell it, have all the recognition, or whatever. But we are definitely all for enhancing core Mautic so please do submit the PR.

Thanks!
Alan

**Comment by MaxOnTheHill** [comment]
cool ... thanks guys.
I have a couple more tweaks I want on this first implementation, so back with our devs for a little bit ... but working pretty nicely ... just UI tweaks for now ... then will get the PR done when I'm happy.

We are going to have commercial add-ons and stuff as well ... but things like this I think should be part of core anyway ... so good to give back where we can :-)

**Comment by troelsfeodor** [comment]
Hi guys. Did this ever get released? I need the ability to let a visitor attach a file to a form he submits.

**Comment by studiospacedb** [comment]
Hi! Also following up to see if this add-on was ever released or a PR done as an option for people to add attachments would be a great and agree should be part of core!

**Comment by bricesanchez** [comment]
i'm interested too by this feature, is it released ?

**Comment by troelsfeodor** [comment]
@alanhartless what would it take to get this prioritized in the next release?

**Comment by IADDIC** [comment]
@MaxOnTheHill @alanhartless I have a use for this in collecting volunteerinformation for our non-profit.  Any ideas when/if this will be available as a plug in or in core?

Thanks,  Rich

**Comment by ldrrp** [comment]
+1

**Comment by Dollique** [comment]
No news on this?
This is a killer criteria for me. The tool is useless for contests (what I wanted to use it for) like this.

**Comment by rodrideme** [comment]
@Dollique the last contest I created using this plugin for wordpress https://wordpress.org/plugins/si-contact-form/, this plugin has an option to post the data to an url, then I used this script to insert in Mautic https://medium.com/@jan_linhart/the-simplest-way-how-to-submit-a-form-data-to-mautic-1454d3afd005

**Comment by inodecloud** [comment]
+1

**Comment by coudenysj** [comment]
@alanhartless @dbhurley @dongilbert I would like to add this functionality via a PR, but would like some guidelines from you guys as to where to store the uploaded files.

**Comment by qneyrat** [comment]
+1 If nobody started I do it

**Comment by VinCardoso** [comment]
+1

**Comment by coudenysj** [comment]
I'll push my code in PR tomorrow

**Comment by coudenysj** [comment]
11 days later I finally managed to push the code.

There are still some todos for this PR, feedback is welcome (see PR description).

**Comment by mzeiler** [comment]
+1

**Comment by gingerling** [comment]
+1 !!!

**Comment by gingerling** [comment]
What is the status of this? I would have assumed this was a functionality already, but surprised it isn't tbh :/ I am happy to test if someone can talk me through the process.

**Comment by escopecz** [comment]
Released in Mautic 2.11.0. PR: https://github.com/Maxell92/mautic/commit/767d6026acef289c9672c987f4c9fa11ae346e49
