### ISSUE TITLE
Decisions executing TRUE and FALSE simultaneously

### ISSUE THREAD

**Issue by paulofelixjunior** [mautic/mautic#2210]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Hi Guys,

I created a campaign based on a campaing form, as the image show below:

![http://salestalent.com.br/wp-content/uploads/2016/07/TEMP-mautic-support.png](http://salestalent.com.br/wp-content/uploads/2016/07/TEMP-mautic-support.png)

Basically the starting point is a form and the 3 decision steps are based in the same form field (função). This is a radio field (only one option can be choosen).

What happens is that when I filled a form as a test, I choose one option that could lead to "FALSE" in decision 1, "TRUE" in decision 2 and, obviously, not touching the decision 3.

I understand that decisions in campaigns work like an "IF" when your are programming - IF condition is TRUE, something happens, ELSE another thing happens.

However I received two different and opposite emails: "Envia obrigado gestor" from the TRUE result of decision 2 and I also received the "Envia obrigado outros", which only could be sent on FALSE of decision 3. When I went to the campaign to understand what happened, this was shown:

![http://salestalent.com.br/wp-content/uploads/2016/07/TEMP-mautic-support2.png](http://salestalent.com.br/wp-content/uploads/2016/07/TEMP-mautic-support2.png)

As all the decisions are based in the same field, and all of them evaluates a "equals to" condition, I cannot realize a reason to have this happening.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Mautic.com
| PHP version | 

### Steps to reproduce:
1. Create a form
2. Create a landing page in which form can be filled
3. Create a campaign using the creatd form as contact source
4. In the decision tree, include a "Visit Page" decision. The page to be checked is the landing page created in item 2.
5. To the green lane (TRUE), connect a send email action and select any e-mail to be sent to the contact
6. To the red lane (FALSE), connect a send email action and select any OTHER e-mail to be sent to the contact
7. In a not logged or anonymous section, visit the landing page, fill out and submit the form.
8. You should expect to receive emails from TRUE and FALSE lanes (items 5 and 6), which is not correct. Only TRUE (item 5) email should be sent.
9. Fill out the form (item 1) directly, using other contact (not visiting the landing page).
10. You should expect to receive only the FALSE lane email (item 6), which is correct.

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
You have to put some delay to the negative paths otherwise they will be triggered right away and your contacts won't have a chance to trigger the positive paths.

**Comment by paulofelixjunior** [comment]
Hi John, thank you.

However it doesn't make sense for me running both paths - true AND false. I understand that conditions should work like an IF in a programming code - a condition is true or false (else), never can be both.

By the way, in this use case, I'm evaluating the value of a field which have been already filled in the contract source form - so there's no room for contact make changes later....



On Wed, Aug 10, 2016 at 12:22 PM -0300, "John Linhart" <notifications@github.com<mailto:notifications@github.com>> wrote:


You have to put some delay to the negative paths otherwise they will be triggered right away and your contacts won't have a chance to trigger the positive paths.

-

**Comment by alanhartless** [comment]
It's not really true/false for decisions. It's more of "contact made the decision to take action (true/green)" or "contact made the decision to NOT take action (false/red)". So if they take action, Mautic executes the actions associated with the green anchor. If they didn't take action within the specified timeframe, Mautic executes the actions associated with the red anchor. 2.1 cleaned this up a bit.

**Comment by paulofelixjunior** [comment]
Hi Alan,

Understood. However my point is still the same: even with your explanation, which is clear, Mautic cannot understand that contact "did" AND "did not" the action.

That's the only final thought on this issue.

Thks



On Fri, Aug 19, 2016 at 1:11 AM -0300, "Alan Hartless" <notifications@github.com<mailto:notifications@github.com>> wrote:


It's not really true/false for decisions. It's more of "contact made the decision to take action (true/green)" or "contact made the decision to NOT take action (false/red)". So if they take action, Mautic executes the actions associated with the green anchor. If they didn't take action within the specified timeframe, Mautic executes the actions associated with the red anchor. 2.1 cleaned this up a bit.

-
