### ISSUE TITLE
Wait label not shown in campaign builder

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2213]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y (Regression)
| Feature request? | 
| Enhancement? | 

## Description:
When opening the "Campaign builder", "wait" labels are not shown 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.2-dev (2016-08-08)
| PHP version | 5.6.19

### Steps to reproduce:
1. Create a campaign go to the "Campaign Builder", add some action with "wait for 1 day"
2. Save it
3. Open it again with "Campaign Builder", "wait" labels are not here

**Comment by escopecz** [comment]
I can replicate

**Comment by chandon** [comment]
:+1:
