### ISSUE TITLE
Campaign builder is broken

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2218]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The campaign builder is broken, there is no menu on the right side anymore. Cannot add anything

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.2-dev
| PHP version | 5.6.19

### Steps to reproduce:
1. Go to the campaign builder

**Comment by alanhartless** [comment]
Likely you need to compile prod assets - remember this code from staging/pre-release so it will most often not out of the box in a production environment. And highly not recommended in production - unless you're just helping test. If testing, it's recommended that you use index_dev.php for the dev environment. 

The campaign builder is changing in 2.1.0. https://www.mautic.org/blog/21-campaign-builder/

**Comment by chandon** [comment]
yes of course, i did a 

    php app/console mautic:assets:generate

and a F5 in my browser (to reload CSS/JS) but it's broken !

**Comment by chandon** [comment]
and i'm using index_dev.php for developpment...

**Comment by escopecz** [comment]
It's works for the whole core team. It must be something on your end. Can you send a screenshot? Is there some error in the JS console?

**Comment by chandon** [comment]
Both on my dev and prod environment. No menu on the right side (and no wait label #2213 )

![image](https://cloud.githubusercontent.com/assets/4522557/17521834/202b04f6-5e55-11e6-8959-34cd76c73386.png)

**Comment by chandon** [comment]
no JS error in console...

**Comment by escopecz** [comment]
Ok, that's the new design. Check the link Alan posted. There is even the video you can watch.

**Comment by chandon** [comment]
whoah ! ok, not that much intuitive...

**Comment by escopecz** [comment]
It's actually more intuitive. Especially when you build a campaign from scratch. It will guide you and let you select only the options you can use. Also the canvas is bigger this way. Give it a shot and I'm sure you'll like it more after 2 minutes :)

**Comment by chandon** [comment]
Once you know it, it's ok... For people begining a new campaign, perfect, but for people migrating and opening existing campaign, there is no clue for "what to do now". Anyway, great job and thanks for the tip :)
