### ISSUE TITLE
500 Internal Server Error on 4 pages

### ISSUE THREAD

**Issue by RocketRaptor** [mautic/mautic#222]
Hey team!

I'm getting a 500 ISE on the following hosted pages:
http://fitness.mautic.com/s/leads (Manage Leads)
http://fitness.mautic.com/s/leads/lists (Manage List)
http://fitness.mautic.com/s/emails (Manage Email)
http://fitness.mautic.com/s/assets (Manage Assets)

I noticed this about a week ago, but thought it'd correct itself. No such luck! Any thoughts as to what the trouble is on your end?

(FYI: I think I'm supposed to use a "Report a Bug" feature for the hosted version, but I don't see the link. The link that appears when I hit the 500 page is a link to Github. Sorry about that!)

**Comment by drmmr763** [comment]
Hi @RocketRaptor 

Would you submit this as a support ticket from the mautic.com dashboard? That'll make sure support staff can handle it quickly!

**Comment by RocketRaptor** [comment]
Ahh, so that's where the site support is! I was wondering about that. Thank you.
