### ISSUE TITLE
Not able to get click data on Mautic

### ISSUE THREAD

**Issue by ravibjain** [mautic/mautic#2224]
What type of report is this:
| Bug report? | 

## Description:
I am using Mautic for email automation. While all the data is getting tracked at a user level (opens, click) but at an aggregate level, there is no option to see email - open - click ratios all at one place. Can you please help on how I could resolve this?

Even when I click on email, the click count table shows clicks only for links like "http://www.facebook.com/<Page name> but not on long parameterised URLs such as http://www.mydomainname.com/buy now?Source=Mautic-Stage1&NetworkID=S1E2-Bottom&utm_source=S1E2-Bottom&utm_medium=Mautic-Email

Is this a problem of using links with parameters?

## If a bug:

| Mautic version | 2.0.1
| PHP version | 5.6.24

**Comment by escopecz** [comment]
The issue with links containing `&` will be fixed in Mautic 2.1.0.
