### ISSUE TITLE
Cron jobs error

### ISSUE THREAD

**Issue by sarbjit-longia** [mautic/mautic#2226]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
The cron job for campaign trigger is giving parse error at line 18 in app/console script. Few other cron jobs are also failing.

I have scheduled the jobs as per online documentation. I am hosting mautic on blue host.

Because of this campaigns are not working.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.1
| PHP version | 5.6.24

### Steps to reproduce:
1. Install mautic
2. Cron jobs
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
The PHP running in CLI is probably lower than 5.6. You can check what version is there with command `php -v`. Consult it with your server/hosting provider.
