### ISSUE TITLE
Mautic.com breaks my mautic instance

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2235]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Can not access my mautic instance when mautic.com is down

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.0.2-dev
| PHP version | 5.6

### Steps to reproduce:
1. Crash mautic.com
2. Try to access "segments" or "campaigns" in the UI
 
### Log errors: 

mautic.CRITICAL: Exception thrown when handling an exception (Debril\RssAtomBundle\Exception\DriverUnreachableResourceException: Error accessing https://mautic.com/?feed=rss2&tag=notification : Operation timed out after 10001 milliseconds with 0 bytes received at /home/mautic/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Driver/HttpCurlDriver.php line 67) {"exception":"[object] (Debril\\RssAtomBundle\\Exception\\DriverUnreachableResourceException(code: 0): Error accessing https://mautic.com/?feed=rss2&tag=notification : Operation timed out after 10001 milliseconds with 0 bytes received at /home/mautic/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Driver/HttpCurlDriver.php:67)"} []

**Comment by chandon** [comment]
I think that, in case of failure 
- No critical exception should be thrown
- The rss feed should not be called more than once per day

**Comment by alanhartless** [comment]
Thanks - we've fixed this.
