### ISSUE TITLE
Support AlphaNumeric sender numbers for SMS

### ISSUE THREAD

**Issue by scottybo** [mautic/mautic#2240]
Twilio supports [Alphanumeric sender IDs](https://www.twilio.com/help/faq/sms/what-is-alphanumeric-sender-id-and-how-do-i-get-started) when sending an SMS.

If I enter BuyMeLocal into the "Sending Phone Number" it saves fine, but when an SMS is triggered a PHP error is thrown and logged stating that it doesn't think it doesn't think the sender phone number is correct.

In Messages.php, line 57 of the Twilio Vendor files (attached as [Messages.txt](https://github.com/mautic/mautic/files/413503/Messages.txt)) we have the function below. I've amended the 'From' to be 'BuyMeLocal' instead of $from. (which means I'm overriding the sender at the point the sms is triggered, avoiding all error checking).
## sendMessage function

```
public function sendMessage($from, $to, $body = null, $mediaUrls = null,
        $params = array()

    ) {

        $postParams = array(
            'From' => 'BuyMeLocal',
            'To' => $to,
        );

        // When the request is made, this will get serialized into MediaUrl=a&MediaUrl=b

        if (!is_null($mediaUrls)) {
            $postParams['MediaUrl'] = $mediaUrls;
        }

        if (!is_null($body)) {
            $postParams['Body'] = $body;
        }

        return self::create($postParams + $params);
    }
```

If I then put a valid phone number in the "Sending Phone Number" field and trigger an SMS, the sender shows as "BuyMeLocal" on my phone.

This means that the functionality to support Alphanumeric sender IDs is already available in Mautic, but it's not working because the error checking is forcing a phone number to be present.

I suggest that we change the error handling for the "Sending Phone Number" to also allow for Alphanumeric sender IDs.

**Comment by niklasfjeldberg** [comment]
Is this currently supported? Can't see any options for this or documentation.
