### ISSUE TITLE
Please verify Problem with Amazon SES in v2.0.2-dev before launch release 2.1.0

### ISSUE THREAD

**Issue by cerebrumbr** [mautic/mautic#2246]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I install version v2.0.2-dev, but not work Amazon SES with the same configuration and credentials used in version 2.0.1 and work perfectly in version 2.0.1

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.0.2-dev
| PHP version | 5.6

### Steps to reproduce:
1. Service to send mail through = Other SMTP Server
2. SMTP host = email-smtp.us-east-1.amazonaws.com
3. SMTP port = 587
4. SMTP encryption type = TLS
5. SMTP authentication mode = Login
6. Username for the selected mail service = SMTP Username obtained in Amazon SES
7. Password for the selected mail service = SMTP Password obtained in Amazon SES
8. Click in button "Send test email"

Presented this error.

Expected response code 250 but got code "530", with message "530 Authentication required " Log data: ++ Starting Swift_SmtpTransport << 220 email-smtp.amazonaws.com ESMTP SimpleEmailService-1579431261 8wG0ZlWLxGBMX9YgmWrs >> EHLO mautic202.cerebrum.com.br << 250-email-smtp.amazonaws.com 250-8BITMIME 250-SIZE 10485760 250-STARTTLS 250-AUTH PLAIN LOGIN 250 Ok >> STARTTLS << 220 Ready to start TLS >> EHLO mautic202.cerebrum.com.br << 250-email-smtp.amazonaws.com 250-8BITMIME 250-SIZE 10485760 250-STARTTLS 250-AUTH PLAIN LOGIN 250 Ok ++ Swift_SmtpTransport started >> MAIL FROM: << 530 Authentication required !! Expected response code 250 but got code "530", with message "530 Authentication required " (code: 530)
++ Starting Swift_SmtpTransport << 220 email-smtp.amazonaws.com ESMTP SimpleEmailService-1579431261 8wG0ZlWLxGBMX9YgmWrs >> EHLO mautic202.cerebrum.com.br << 250-email-smtp.amazonaws.com 250-8BITMIME 250-SIZE 10485760 250-STARTTLS 250-AUTH PLAIN LOGIN 250 Ok >> STARTTLS << 220 Ready to start TLS >> EHLO mautic202.cerebrum.com.br << 250-email-smtp.amazonaws.com 250-8BITMIME 250-SIZE 10485760 250-STARTTLS 250-AUTH PLAIN LOGIN 250 Ok ++ Swift_SmtpTransport started >> MAIL FROM: << 530 Authentication required !! Expected response code 250 but got code "530", with message "530 Authentication required " (code: 530)
 
### IMAGE CONFIGURATION AMAZON SES IN MAUTIC 2.0.1 (WORK PERFECTLY)

![mautic-201](https://cloud.githubusercontent.com/assets/2263217/17601080/c735ae4e-5fdc-11e6-838d-0e3e0a8788c7.png)

### IMAGE CONFIGURATION AMAZON SES IN MAUTIC 2.0.2-dev WITH THE SAME CONFIGURATION (NOT WORK)

![mautic-202-dev](https://cloud.githubusercontent.com/assets/2263217/17601076/c3a3c22a-5fdc-11e6-8832-fa8b05b4bbe6.png)

**Comment by alanhartless** [comment]
Just in the knick of time :-) https://github.com/mautic/mautic/commit/a94564f9ed20663abc998bc418fb484e5d99fced It only affected the tests but good catch. Thanks!
