### ISSUE TITLE
Ability to duplicate form fields

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#2247]
| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? | Y |
## Description:

Ability to duplicate a field/group in forms. This helps with surveys when having 1-5 questions like below.

![image](https://cloud.githubusercontent.com/assets/985837/17602312/14115efa-5fda-11e6-830d-3e7a7961e363.png)

**Comment by yrammos** [comment]
Is this feature on the radar? Many thanks.
