### ISSUE TITLE
Preload options in select form fields

### ISSUE THREAD

**Issue by paulofelixjunior** [mautic/mautic#2249]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
When creating a select/radio/checkbox field in a form and linking it to a Lookup field in the contact registry, preload the options list from the contact field instead of requiring user to type options list manually. Preloaded options can be changed or even deleted.

**Comment by MaxWebmecanik** [comment]
I would also really to see this implemented.

@escopecz Is there any technical reason that made this difficult to implement earlier on or is it just that it never was considered?

**Comment by escopecz** [comment]
It was never implemented. It was considered. Maybe this is a duplicate issue. The thing is, you can firstly create a form field with options. Then you link it with a lead field which has another options. Should the form field options be removed? What if the lead field adds or removes an option, should the form field reflect that? Those are the questions which has to be considered before the development.

**Comment by MaxWebmecanik** [comment]
I would think the best thing to do would be to let the user choose if he wants the options to be automatically populated or not. If so, I would imagine that the options would be updated as the custom field is modified. If not, then just retain the current behavior.
