### ISSUE TITLE
MailChimp Not Synching

### ISSUE THREAD

**Issue by dalethomas** [mautic/mautic#225]
Hi guys - 

Not sure what the total expectation is with the MailChimp.  Does Mautic just push to MC?  Or should I also expect leads to get pulled into MailChimp.  Either way I am not seeing the synch.  Is it immediate?

Repro:
1.  Add MailChimp add on
2.  Check "Published"
3. Add Client ID from MC
4. Add Client Secret from MC
5. Authorize APP
6. Goto Features 
7. Check "Push leads to this integration"
8. Choose list "WP-Mautic"
9. Click on Field Mapping
10.  Mapped Email, First Name, Last Name
11. Saved
12. Add new Lead to Mautic
13.  Log into MC and check "WP-Mautic"

Expectation:
1. The expectation would be that the new lead would be immediately added to MC.  
2. Once a new leads is added to MC. Expectation would be the lead would be visible in Mautic.

**Comment by alanhartless** [comment]
Hi Dale!

The MailChimp integration is currently a one way street from Mautic to MC.  It does not have the feature implemented to pull in leads from MC.

Pushing leads to MC can happen by configuring the "Push to Integration" form submit action, campaign action, and/or point trigger.

For manually added leads through a lead form, I realize we have a shortcoming. I was going to suggest that you could add a 0 point trigger but then realized that point triggers only happen on point changes.  We are looking into that for our next patch release to see how we can remedy that.

Thanks,
Alan

**Comment by dalethomas** [comment]
AH.  Ok.  Now I am tracking. 

Any thoughts of using a service like Zapier?  That would rock!

**Comment by alanhartless** [comment]
It's been requested via #41 so we will be looking into it!

**Comment by dalethomas** [comment]
AWESOME!  I Hope you do it.
