### ISSUE TITLE
Class 'Debril\RssAtomBundle\DebrilRssAtomBundle' not found

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#2250]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
After upgrading to mautic 2.1, the following errors were encountered

Errors encountered:

```bash-4.1$ /opt/plesk/php/7.0/bin/php app/console doctrine:migrations:migrate
PHP Fatal error:  Uncaught Error: Class 'Debril\RssAtomBundle\DebrilRssAtomBundle' not found in /httpdocs/app/AppKernel.php:156
Stack trace:
#0 /httpdocs/app/bootstrap.php.cache(2650): AppKernel->registerBundles()
#1 /httpdocs/app/AppKernel.php(248): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /httpdocs/vendor/symfony/framework-bundle/Console/Application.php(70): AppKernel->boot()
#3 /httpdocs/vendor/symfony/console/Application.php(123): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /httpdocs/app/console(36): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#5 {main}
  thrown in /httpdocs/app/AppKernel.php on line 156```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.0
| PHP version | 7.0.9

### Steps to reproduce:
1. `git merge -X theirs mautic/master`
2. `rm -rf app/cache/prod`
3. `/opt/plesk/php/7.0/bin/php app/console doctrine:migrations:migrate`

Note this was an upgrade from 2.0.1 
 
### Log errors:

**Comment by escopecz** [comment]
If you use git for upgrades, you have to also install new PHP dependencies yourself with `composer install` command.

**Comment by jordan8037310** [comment]
Thanks @escopecz - All fixed up now. Had some pains with Plesk 12.5 not having a decent version of PHP installed that tripped me up for a while.

For those who have the same issue:

Ran:
`/opt/plesk/php/7.0/bin/php /usr/local/bin/composer update` 
Then proceeded with `... doctrine:migrations:update`

Specifying the full path was required as re-aliasing php for the domain wasn't possible.

**Comment by escopecz** [comment]
Use `composer install`, not `composer update`. And yes, it must be executed in the Mautic root directory.

**Comment by jordan8037310** [comment]
Got it, thanks!
