### ISSUE TITLE
checkbox group, label's attribute "for", value generation error

### ISSUE THREAD

**Issue by lenghan1991** [mautic/mautic#2251]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The more details the better..

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 1.4.2 / 2.0
| PHP version | 5.6

### Steps to reproduce:
1. Construct a checkbox group and two of the items start with the same characters;
2. Analyze the element, we can find the label's _for_ attributes have the same value.
![image](https://cloud.githubusercontent.com/assets/1933236/17616292/5c471fc6-60a6-11e6-8c90-63f382d031f6.png)
3. Additionally, if the item is Chinese character, the _for_ value generation seems to work badly, leaving a blank after the **mauticform_checkboxgrp_checkbox_nrdsb_**

### Result:
click the black part, and another checkbox will be checked.
![image](https://cloud.githubusercontent.com/assets/1933236/17616313/7bdd76f0-60a6-11e6-8059-c1fe9417536f.png)
[demo link](https://100offer.mautic.net/testform)

**Comment by alanhartless** [comment]
Fixed in #2336. Also, this will fix support for Chinese characters in combination with #2333.
