### ISSUE TITLE
Stuck Upgrade from 2.0 to 2.1

### ISSUE THREAD

**Issue by gokhanerdogdu** [mautic/mautic#2252]
What type of report is this:
| Bug report? | 

## Description:
Hello,

When trying to upgrade from 2.0 to 2.1, the upgrade process stuck during "Moving Package Contents". Attached is the screenshot. 

![2016-08-12 11_06_34-mautic_upgrade](https://cloud.githubusercontent.com/assets/20369981/17616463/927c4e8c-607d-11e6-898f-2194997cb059.png)

## If a bug:

| Q   | A
| --- | ---
| 2.0 | 
| PHP Version 5.6.24 | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

The only error in logs is;
[2016-08-12 07:25:56] mautic.ERROR: Deprecation: The alias option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is deprecated since version 2.8 and will be removed in 3.0. Use the extended_type option instead. - in file /home/.../.../vendor/symfony/framework-bundle/DependencyInjection/Compiler/FormPass.php - at line 67 [] []

**Comment by escopecz** [comment]
Make sure that all Mautic files are writable by Mautic. That means the owner and group is the same as your web server user, usually called www-data and the permissions are correct.

**Comment by gokhanerdogdu** [comment]
When I check the permissions, everything seems to be green. Isn't this enough for permissions?

![2016-08-12 11_26_12-mautic](https://cloud.githubusercontent.com/assets/20369981/17616925/ca05f8d8-607f-11e6-990f-d8c5ec8f2fe3.png)

**Comment by escopecz** [comment]
Those are just the most important folders which has to be writable for basic Mautic functionality. The upgrade requires every file to be writable. The error you reported isn't related to the upgrade. Is there anything else? Or in the server log?

**Comment by gokhanerdogdu** [comment]
I changed the permissions of all the folder and subfolder directories and it has started upgrading. Now, when try to open the UI, getting the attached error after login. 

![2016-08-12 15_24_32-site is offline](https://cloud.githubusercontent.com/assets/20369981/17622108/01898f92-60a1-11e6-9856-51761aded932.png)

In the logs, there are below logs.
[2016-08-12 12:04:21] mautic.ERROR: Error: Trait 'Mautic\LeadBundle\Controller\EntityContactsTrait' not found - in file /home/.../.../plugins/MauticSocialBundle/Controller/MonitoringController.php - at line 23 [] []

**Comment by escopecz** [comment]
It seems your upgrade didn't add this file: app\bundles\LeadBundle\Controller\EntityContactsTrait.php. Or can you see it? Take a look at http://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

**Comment by alanhartless** [comment]
Due to lack of feedback, we are closing this issue. Please upgrade to 2.1.1 and if the issue persists, let us know! Thanks!
