### ISSUE TITLE
Error on PageModel::getVariants() when adding visited page decision to campaign

### ISSUE THREAD

**Issue by humbertooliveira** [mautic/mautic#2260]
What type of report is this:
| Bug report? | 

## Description:
When the user visited one of my landing pages that is included as a "visited page" decision the app returns a Fatal Error: Call to undefined method.

## If a bug:

| Mautic version | 2.1.0
| PHP version | 5.6.24

### Steps to reproduce:
1. Create a landing page
2. Use the landing page as a "visited page" decision
3. Visit the page with an email generated url
 
### Log errors: 

mautic.ERROR: Error: Call to undefined method Mautic\PageBundle\Model\PageModel::getVariants() - in file /home/mkmetacodigo/mk.metacodigo.com.br/app/bundles/PageBundle/EventListener/CampaignSubscriber.php - at line 119 [] []

**Comment by wlaurance** [comment]
I'm also getting this same error under the exact same steps to reproduce.

I migrated from 2.0.0 to 2.1.0 today. So I tried creating a new page to rule out any migrations issues. But no luck.

Any insight to this issue would be great.

Thanks Mautic team!

**Comment by wlaurance** [comment]
@humbertooliveira a temporary work around I found is to send your prospect to a page on your website with the tracing pixel. Then instead of using the Mautic landing page, write in the URL to your own landing page.

**Comment by alanhartless** [comment]
Hi guys - see #2269 for the fix.

**Comment by dongilbert** [comment]
Closed via #2269
