### ISSUE TITLE
Parse error when running upgrade.php

### ISSUE THREAD

**Issue by AndreaBarghigiani** [mautic/mautic#2263]
What type of report is this:
| Bug report? | 

## Description:
Hi there, this is my first time that I am trying to upgrade Mautic from CLI because I read the release note and I thought it could be the right time to do some CLI stuff. Anyway I get this kind of error that I am sure is because my hosting service does not understande the shorthand declaration of an array:

`syntax error, unexpected '[' in /mautic_folder/upgrade.php on line 65`

I am writing to understand if I can edit the delaration of the array or if there are other solutions. I am on a shared hosting and I do not think I'll be able to edit the `php.ini` file...

## If a bug:

| Mautic version | 2.0.1
| PHP version | PHP 5.6.24 
 
### Log errors: 

_Here are the errors of my **php_recordlog**_
[13-Aug-2016 05:32:18 CST6CDT] PHP Parse error:  syntax error, unexpected '[' in /mautic_folder/upgrade.php on line 65
[13-Aug-2016 05:34:14 CST6CDT] PHP Parse error:  syntax error, unexpected '[' in /mautic_folder/upgrade.php on line 65

Thanks in advance for all your help.

**Comment by escopecz** [comment]
The PHP version running in your CLI is older than Mautic requires. You can check it by running `php -v` command. Contact your host to fix that.
