### ISSUE TITLE
Issues using Sparkpost API

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#2264]
Bug report

## Description:
Emails with no subject will not send via SparkPost API and fail silently

Mautic 2.1.0
PHP 5.6.22

### Steps to reproduce:
1.  Configure valid SparkPost API key and configure in Mautic
2.  Create email, using Blank theme and no subject
3.  Save & Close
4.  Send Example
5. No email is received, or noted in SparkPost Console [Reports>Message Events]
 
### Log errors: 
mautic_prod log:
[2016-08-13 11:12:58] mautic.ERROR: [MAIL ERROR] Invalid header Log data: !! Invalid header (code: 0) [] []

### Notes
Using the email configuration to enter SparkPost API information, Test and Send Test Email are both successful.
Before trying to move to SparkPost, I was using Mandrill API for transmission, this symptom does not occur using Mandrill. Instead email sends correctly.

**Comment by zstephen** [comment]
Also sending custom email to a lead causes this error(not sure if it's related):

Failed to send to user@host.com: Message generation rejected Log data: !! Message generation rejected (code: 0)

**Comment by alanhartless** [comment]
@zstephen Does this only happen for emails without a subject? 

If I'm not mistaken, `Message generation rejected` means Sparkpost rejected the email address for whatever reason - for example, if they are on a suppression list.

**Comment by zstephen** [comment]
@alanhartless the above symptom only happens for emails without a subject.

Emails with a subject are sent, but they have another issue, they are stamped with "The message has no text content" by my mail client when I use sparkpost(but not with Mandrill)

I've attached a screenshot
![screenshot from 2016-08-16 07-00-18](https://cloud.githubusercontent.com/assets/10385295/17679578/5cc74ee0-637f-11e6-862f-5a871a10a32c.png)

My mail client is Zimbra 8.6 and this is how it handles emails with no text normally, I'm curious why the sparkpost connector is triggering that. I've never seen this before except for emails that actually have no text content.

**Comment by alanhartless** [comment]
It looks like Sparkpost requires a subject as per https://developers.sparkpost.com/api/transmissions#header-inline-content-attributes. Nothing we can really do about that short of forcing an error and/or auto-populating a generic subject which probably isn't desired. 

For the text - it could be because we're setting it in the API call whether it's empty or not. We've found Sparkpost has a few quirks like that - so we'll verify this and just not set if empty to see if that solves the issue.

**Comment by alanhartless** [comment]
I fixed these as part of https://github.com/mautic/mautic/pull/2248
