### ISSUE TITLE
Using lead fields in button text and links

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#2265]
What type of report is this: Bug or Enhancement

PHP 5.6.22
Mautic 2.1.0

## Description:
In the new email builder, it would be really good if we're able to utilise lead fields in the button text and links.

Text would allow us to really personalise them and make an impact on the lead
Links would let us make custom downloads available to leads like "your custom report"

The buttons make a great visual impression, it would be great if they had the same functionality as the rest of the email builder as far as lead fields are concerned.

## Notes:
I've tried pasting in the value of a custom field into the URL entry for the button, and it breaks the link by displaying the following in the body of the sent email.

`div data-param-button-size="0" data-param-float="1" data-param-href="http://mauticsite.com/asset/1:asset-name" data-slot="button" align="center">**CustomFieldName**%E2%80%8D" style="font-size: 14px; color: rgb(255, 255, 255); text-decoration: none; border-radius: 3px; padding: 10px 13px; background-color: rgb(78, 94, 158); display: inline-block;" target="_blank">I want this!`

If I use this code:
`<a href="{contactfield=001profeboost_report_url}">Here</a> is your action plan.`
I get this result in the email body:
`**001ProfeBoost Report URL**">Here is your action plan.`

GitHub Markdown Note: In both examples, there were double asterisks around the bold items, but github formatted them with Markdown so I had to quote them as code instead, they're not code, they're the text displayed in the email body.

**Comment by alanhartless** [comment]
@zstephen does this only happen when you send an example email? Asking to confirm because that's the only case I know of where the token is replaced with a visual since no contact is associated to replace with an actual value.

**Comment by zstephen** [comment]
@alanhartless this happens even if I target a lead directly.

Here's something else I noticed when I was formulating my answer to your question:
When I insert the link, if I'm specifying a URL either directly into the button(Button Link, as per picture of builder) or into the Insert Link function, I'm unable to just start typing the name of the field after a curly open bracket and rely on it to auto complete. I can do this properly in the section where I enter email text copy, so I use that to generate it for me then paste it into the respective areas. Is this a worthwhile feature request to implement?

Now your answer..

Here is the image of the email in the builder:
![builder](https://cloud.githubusercontent.com/assets/10385295/17696578/895c6e22-63f2-11e6-914f-dc1a6008e929.png)

Here is the code of that email from the edit email screen
`
<!DOCTYPE html>
<html>
	<head>
		<title>{subject}</title>
	</head>
	<body style="-webkit-font-smoothing: antialiased; height: 100%; color: rgb(103, 103, 103); font-family: Oxygen, ">
		<div align="center" class="content-padding" data-section-wrapper="" style="background-color: #f7f7f7;font-family: Helvetica, Arial, sans-serif;font-size: 14px;color: #777777;text-align: center;line-height: 21px;border-collapse: collapse;padding: 20px 0 30px;" valign="top" width="100%">
			<center>

				<table cellpadding="0" cellspacing="0" data-section="" style="border-collapse: collapse !important;" width="600" class="w320">
					<tbody>
						<tr style="-webkit-user-select: none;">
							<td data-slot-container="" style="font-family: Helvetica, Arial, sans-serif;font-size: 32px;color: #4d4d4d;text-align: center;line-height: normal;border-collapse: collapse;font-weight: 700;padding: 35px 0 0;" class="header-lg">
								<div data-slot="text">You've received an invitation!</div>
							</td>
						</tr>
						<tr style="-webkit-user-select: none;">
							<td data-slot-container="" style="font-family: Helvetica, Arial, sans-serif;font-size: 14px;color: #777777;text-align: center;line-height: 21px;border-collapse: collapse;padding: 10px 60px 0px;width: 100% !important;" class="free-text">
								<br>
							</td>
						</tr>
						<tr style="-webkit-user-select: none;">
							<td style="font-family: Helvetica, Arial, sans-serif;font-size: 14px;color: #777777;text-align: center;line-height: 21px;border-collapse: collapse;padding: 30px 50px;width: 500px;" class="mini-block-container">

								<table cellpadding="0" cellspacing="0" style="border-collapse:separate !important;" width="100%">
									<tbody>
										<tr style="-webkit-user-select: none;">
											<td data-slot-container="" style="font-family: Helvetica, Arial, sans-serif;font-size: 14px;color: #777777;text-align: center;line-height: 21px;border-collapse: collapse;background-color: #ffffff;width: 498px;border: 1px solid #cccccc;border-radius: 5px;padding: 45px 75px;" class="mini-block">
												<div data-param-href="{contactfield=001profeboost_report_url}‍ " data-slot="text">Here is your custom <a href="{contactfield=001profeboost_report_url}%E2%80%8D%20" style="-webkit-user-select: auto;">report</a>
													<br>
													<br>Here it is by itself
													<br><span class="atwho-inserted" data-fr-verified="true">{contactfield=001profeboost_report_url}</span>‍
													<br>
													<br>It's also in this button</div>
												<div class="button" data-param-background-color="#4e5e9e" data-param-button-size="1" data-param-color="ffffff" data-param-float="1" data-param-href="{contactfield=001profeboost_report_url}‍ " data-param-link-text="I want this" data-param-padding-top="5" data-slot="button"><a href="{contactfield=001profeboost_report_url}%E2%80%8D%20" style="font-size: 16px; color: #ffffff; text-decoration: none; text-decoration: none; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; padding: 12px 18px; background-color: #4e5e9e; display: inline-block;" target="_blank">I want this!</a>
													<div style="clear:both">
														<br>
													</div>
												</div>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody>
				</table>
			</center>
		</div>
		<div align="center" data-section-wrapper="" style="background-color: #ffffff;border-top: 1px solid #e5e5e5;border-bottom: 1px solid #e5e5e5;font-family: Helvetica, Arial, sans-serif;font-size: 14px;color: #777777;text-align: center;line-height: 21px;border-collapse: collapse;" valign="top" width="100%">
			<center>

				<table cellpadding="0" cellspacing="0" data-section="" style="border-collapse: collapse !important;" width="600" class="w320">
					<tbody>
						<tr style="-webkit-user-select: none;">
							<td data-slot-container="" style="font-family: Helvetica, Arial, sans-serif;font-size: 24px;color: #4d4d4d;text-align: center;line-height: normal;border-collapse: collapse;font-weight: 700;padding: 35px 0 0;" class="header-md">
								<br>
							</td>
						</tr>
						<tr style="-webkit-user-select: none;">
							<td data-slot-container="" style="font-family: Helvetica, Arial, sans-serif;font-size: 14px;color: #777777;text-align: center;line-height: 21px;border-collapse: collapse;padding: 25px 0 30px;" class="mini-imgs">
								<br>
							</td>
						</tr>
					</tbody>
				</table>
			</center>
		</div>
		<div align="center" data-section-wrapper="" style="background-color: #f7f7f7;font-family: Helvetica, Arial, sans-serif;font-size: 14px;color: #777777;text-align: center;line-height: 21px;border-collapse: collapse;" valign="top" width="100%">
			<center>

				<table cellpadding="0" cellspacing="0" data-section="" style="border-collapse: collapse !important;" width="600" class="w320">
					<tbody>
						<tr style="-webkit-user-select: none;">
							<td data-slot-container="" style="padding: 25px 0 25px;font-family: Helvetica, Arial, sans-serif;font-size: 14px;color: #777777;text-align: center;line-height: 21px;border-collapse: collapse;">
								<br>
							</td>
						</tr>
					</tbody>
				</table>
			</center>
		</div>
	</body>
</html>
`

Here is what I receive in my email client, happens both to my gmail and also my Zimbra email
![in email client](https://cloud.githubusercontent.com/assets/10385295/17696695/73ff260e-63f3-11e6-8203-005e09f0e217.png)

**Comment by alanhartless** [comment]
This should now be fixed in 2.1.1. Let us know if something is still not working right. Thanks!
