### ISSUE TITLE
Progressive profiling for all form fields

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#2266]
What type of report is this:   Feature request or bug

Mautic 2.1.0
PHP 5.6.22
## Description:

Can we make progressive profiling behaviour tab available for any validly mapped form field..

On some form fields(such as email), the behaviour tab isn't visible per the #2022 update.

If the user is being presented with a form and you wish to be certain about their identity, it is possible to map a hidden field to their email, but it will never display(I've tried using the various behaviour options, no visibility), so there is no way of showing the user their email address and giving them an opportunity to validate it's correct.

It's important to show them their email address because if it's wrong, it will prompt them to correct it or if they are a new lead, it will be blank and they can then be required to fill it out. If they don't have this opportunity, it makes it easier for lead data to become mixed up or data collection efforts to become incomplete. Like in a situation where a user manually revisits a  form embedded landing page URL from a browser with no tracking cookie set.

**Comment by escopecz** [comment]
The email field doesn't have the Behavior tab for a reason. The Mautic tracking can fail in some cases and so the contacts should always fill in their email address from scratch to confirm if the form submission belongs to the currently tracked contact or if it's someone else.

When the Mautic tracking gets more accurate, we allow to use the Progressive Profiling for the email field as well. I'll mark this as a feature request.
