### ISSUE TITLE
SuiteCRM integration with Mautic

### ISSUE THREAD

**Issue by rohanray** [mautic/mautic#227]
Hi Team,

Let me first thank you for all the hard work in bringing out such a polished product! Thank you is just not enough. We would like to see a Suitecrm integration with Mautic and as a way of thanking the team, I would love to make some contribution in this regard. Please can you tell me if there is any SuiteCRM integration planned in the near roadmap of Mautic? 

Kind Regards
Rohan

**Comment by alanhartless** [comment]
Hi Rohan,

Thanks!

Unfortunately, we do not currently have SuiteCRM on the road map but will tag this as a feature request for it to be considered for a future release of Mautic.

Thanks!
Alan

**Comment by rohanray** [comment]
Thank you Alan! 

Regards
Rohan

**Comment by jerime** [comment]
I would like to see this as well.  SuiteCRM is a SugarCRM Community edition fork.  So, although I haven't looked into it, the API's are probably mostly the same.

**Comment by pgorod** [comment]
I confirm at least part of the SugarCRM integration works with SuiteCRM (remember SuiteCRM 7.x is similar to SugarCRM version 6.x when selecting version). I just did some basic tests, nothing exhaustive.

**Comment by devincurrie** [comment]
+1 for this

**Comment by npracht** [comment]
Hi,

If someone wants to carry this project, i'm sure it is based on SugarCRM Community and consequently it can be done "easily" --> https://github.com/mautic/mautic/pull/3702

**Comment by ramezrafla** [comment]
I just tested PR #3702 with SuiteCRM and it works great (I only tested one-way Mautic -> SuiteCRM). It also fixes a bug where it complained that a required field is not connected (referring to Last Name even  if it's connected). Can't wait for it to go to production version.

**Comment by pgorod** [comment]
Excuse me if I am out of sync with the project, the last time I tried it (SuiteCRM + Mautic) was about a year ago. 

I remember there was a configuration selection between Sugar 6.5 and Sugar 7.x, or something similar. For SuiteCRM 7.x you had to select SugarCRM 6.5, which is a bit counter-intuitive.

It's just a cosmetic issue, but in order to reduce confusion, if it is possible to actually include there an option for SuiteCRM (even if it does the same as selecting Sugar 6.5), I think it would be useful. It also makes the SuiteCRM possibility more visible and known. Thanks!

**Comment by npracht** [comment]
With @canal-web we will PR sugar 7 soon. Until now it is working only with 6.5 community, that's why it should work with Suite :-)

N.

**Comment by ramezrafla** [comment]
@npracht
Do we have to wait for sugarcrm 7 integration to be complete before pushing this PR? It serves the need of many today. If you are using open source marketing automation you are also quite likely to be using open source crm

**Comment by npracht** [comment]
Hello @ramezrafla i don't think so, i think you can go ahead with a PR cloning this plugin and renaming it SuiteCRM :)

**Comment by devincurrie** [comment]
eVolpe recently [released](https://evolpe.com/sugarcrm-suitecrm-mautic-integrator/) an addon called [Mautic & SugarCRM Integrator](https://www.sugaroutfitters.com/addons/mautic-sugarcrm-integrator) and is compatible with the latest version of SuiteCRM running Sugar 6.5. If eVolpe was able to pull this off, then bi-directional support is possible between Mautic and SuiteCRM.

**Comment by ramezrafla** [comment]
This plugin works well including bidirectional. I'll go ahead and clone it as SuiteCRM so it goes into core.

**Comment by Reneeeee** [comment]
Hi @ramezrafla 

Do you perhaps know if the bidirectional syncing is included into the latest Mautic clone release (2.9.0)? 
If so, does it work with the most recent release of SuiteCRM (7.9.3)?

Thanks for your time.

**Comment by escopecz** [comment]
Closing since it's developed as a plugin.
