### ISSUE TITLE
When using sparkpost placeholders end up empty

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#2277]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | N
| Enhancement? | N

## Description:
After updating to 2.1 I've tried to switch to the Sparkpost API instead of the Sparkpost SMTP method.
This results on placeholders being replaced by nothing.

## If a bug:

| Q   | A
| Mautic version | 2.1
| PHP version | 7.0.8

### Steps to reproduce:
1. Get a mautic 2.1 install
2. Create a regular SMTP connection with your sparkpost account
3. Create a form with an action "send results" or create an email to send after form submission. Use some placeholders in this mail, like {leadfield:First name} for example
4. Fill in the form
5. See the resulting email works with the placeholders substituded correctly when sending through SMTP.
6. Change to use the sparkpost API instead of regular SMTP
7. Try the form again and conclude the placeholders are replaced by empties.
### Log errors: 
No errors in the log

**Comment by alanhartless** [comment]
I can reproduce this with the form results email where none of the form results are populated when sending through the Sparkpost transport. Although sending a templated email seems to work fine.

It seems that contact tokens ({leadfield=firstname} or preferably {contactfield=firstname}) are not converted at all in the form results email. Hopefully I can fix both this :-)

**Comment by alanhartless** [comment]
Should be fixed with #2284
