### ISSUE TITLE
Form fields labeled "message" don't show their validation messages

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#2279]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:

![image](https://cloud.githubusercontent.com/assets/18265735/17701409/051b50c4-63ca-11e6-89c9-e0738c725c67.png)
If a form field is labeled "message" then you end up with two elements with the same id.
![image](https://cloud.githubusercontent.com/assets/18265735/17701564/9ea35dae-63ca-11e6-8381-0f57321efbf2.png)
Therefore, the Javascript fails to select the error message (and thereafter turn it visible)

### Screencast

![message](https://cloud.githubusercontent.com/assets/18265735/17813964/e2e01c18-662d-11e6-81fd-57345ab5676e.gif)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.1.1-dev
| PHP version | PHP 5.6.23

### Steps to reproduce:
1. Make a form with a text field labeled message
2. Make it required and insert a validation message
3. Preview the form and validate it without filling in the field

**Comment by alanhartless** [comment]
Fixed in #2302
