### ISSUE TITLE
Progress bar keeps running

### ISSUE THREAD

**Issue by berndblume** [mautic/mautic#2286]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
After upgrading from mautic 1.3.1 to 2.1.0, the progress bar animation keeps running on just about every page. Same thing in latest Safari, Firefox, Opera on my Mac. Hitting the browser's refresh button solves the problem *for now*, clicking somewhere (e.g. a new mautic menu item) brings the problem back. The animation is very obtrusive and annoying, so this is a real problem.
I'm running mautic on apache 2.4 behind an nginx reverse proxy. I made sure my nginx reverse proxy is properly forwarding websocket call as well, even though I don't know whether you guys are using websocket.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.0
| PHP version | 5.6.24-0+deb8u1

### Steps to reproduce:
1. Open mautic start page
2. Hit any menu item, e.g. "Reports" in the left sidebar
3. Observe the progress bar animation forever :-)
4. Hot refresh in your browser - animation stops
5. Click on a different menu item
6. Go to 3.
 
### Log errors: 
```
[2016-08-17 00:06:07] mautic.ERROR: Deprecation: The alias option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is deprecated since version 2.8 and will be removed in 3.0. Use the extended_type option instead. - in file /var/www/html/mautic-master/vendor/symfony/framework-bundle/DependencyInjection/Compiler/FormPass.php - at line 67 [] []
[2016-08-17 01:00:02] mautic.ERROR: [MAIL ERROR] Address in mailbox given [Chip Hook&#13;&#10;chiphook@msn.com] does not comply with RFC 2822, 3.6.2. [] []
[2016-08-17 01:00:02] mautic.ERROR: [MAIL ERROR] Address in mailbox given [sladkfj@#lkdsjf.com&#13;&#10;] does not comply with RFC 2822, 3.6.2. [] []
```

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
Hi there,

We're not using websockets unfortunately due to the having to support shared hosts which don't have access to them. 

Can you look at your browser's developer javascript console when this is happening. Do you see any errors? If you check the network tab - does it show any pending ajax requests?

Usually this happens when 1 of 2 things happen:

1. An error occurred either server (that leads to a Javascript error due to a bad response) or Javascript side.
2. An ajax process is still going as the progress bar is supposed to stop when the last ajax query is made.

Thanks!

**Comment by berndblume** [comment]
I see a lot of errors in the Safari error console:
```
froala_editor.js:552SyntaxError: Unexpected string literal 'use strict'
(anonymous function) — froala_editor.js:552
align.js:3:88TypeError: undefined is not an object (evaluating '$.FE.PLUGINS')
code_beautifier.js:3:88TypeError: undefined is not an object (evaluating '$.FE.PLUGINS')
code_view.js:3:97TypeError: undefined is not an object (evaluating '$.FE.DEFAULTS')
colors.js:3:97TypeError: undefined is not an object (evaluating '$.FE.POPUP_TEMPLATES')
font_family.js:3:97TypeError: undefined is not an object (evaluating '$.FE.DEFAULTS')
font_size.js:3:97TypeError: undefined is not an object (evaluating '$.FE.DEFAULTS')
fullscreen.js:3:88TypeError: undefined is not an object (evaluating '$.FE.PLUGINS')
image.js:3:97TypeError: undefined is not an object (evaluating '$.FE.POPUP_TEMPLATES')
filemanager.js:6:88TypeError: undefined is not an object (evaluating '$.FE.PLUGINS')
inline_style.js:3:97TypeError: undefined is not an object (evaluating '$.FE.DEFAULTS')
line_breaker.js:3:97TypeError: undefined is not an object (evaluating '$.FE.DEFAULTS')
link.js:3:97TypeError: undefined is not an object (evaluating '$.FE.POPUP_TEMPLATES')
lists.js:3:88TypeError: undefined is not an object (evaluating '$.FE.PLUGINS')
paragraph_format.js:3:97TypeError: undefined is not an object (evaluating '$.FE.DEFAULTS')
paragraph_style.js:3:97TypeError: undefined is not an object (evaluating '$.FE.DEFAULTS')
quick_insert.js:3:97TypeError: undefined is not an object (evaluating '$.FE.DEFAULTS')
quote.js:3:88TypeError: undefined is not an object (evaluating '$.FE.PLUGINS')
table.js:3:97TypeError: undefined is not an object (evaluating '$.FE.POPUP_TEMPLATES')
url.js:3:97TypeError: undefined is not an object (evaluating '$.FE.DEFAULTS')
gatedvideo.js:3:97TypeError: undefined is not an object (evaluating '$.FE.POPUP_TEMPLATES')
token.js:3:88TypeError: undefined is not an object (evaluating '$.FE.PLUGINS')
activateGlobalFroalaOptions — app.js:13:946TypeError: undefined is not an object (evaluating 'mQuery.FroalaEditor.ENTER_BR')
activateGlobalFroalaOptions — app.js:13:946TypeError: undefined is not an object (evaluating 'mQuery.FroalaEditor.ENTER_BR')
```

**Comment by tiagosh** [comment]
If you are using cloudflare in your website, this might cause the issue:
https://github.com/mautic/mautic/issues/1942#issuecomment-241848963

**Comment by berndblume** [comment]
Thank you, tiagosh. I did what is mentioned in the comment to the issue you referenced: Commented out the two occurrences of `use strict;` in froala_editor.js. Cloudflare then restarted the minification process, and the problem is gone! Even though this is not a 'mautic problem', I strongly advise to update the mautic code in some way so that it will work with cloudflare out of the box, given the popularity of the latter. And it's kind of inconvenient to make manual changes in the code every time I'm upgrading mautic.

**Comment by tiagosh** [comment]
No worries, glad I could help.
As froala is a separate project I wonder if maybe it's best to have it fixed there, as other projects might be affected by this bug as well.

**Comment by alanhartless** [comment]
Hi guys. I've reported this upstream. Hopefully they'll reply/fix. https://github.com/froala/wysiwyg-editor/issues/1482
