### ISSUE TITLE
Can't delete uploaded theme without Title...

### ISSUE THREAD

**Issue by lightweight** [mautic/mautic#2288]
Bug report

## Description:
I uploaded a custom Mautic theme. It had a filename of oeru-mautic-theme.zip, and a theme name (in config.json) of "OERu". The theme received a title of (oerumautictheme) and not OERu(oerumautictheme), i.e. the "name" in the config.json was not used to construct the title. Subsequently, I was not able to delete it via any means I could find in the Themes interface (e.g. click to select, click rubbish bin icon; click dropdown next to selection checkbox for theme and select "delete") . 

## If a bug:
Mautic version: 2.1.0 (using mautic.net)

### Steps to reproduce:
1. by whatever means (possibly a bug in processing config.json in an uploaded theme zipfile or perhaps invalid json in that file) a custom Theme is installed with no title (just the filename in parens, stripped of "-" chars).  
2. attempt to delete the theme
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Could you please provide your theme zip package for testing?

**Comment by alanhartless** [comment]
Due to lack of feedback, closing this ticket. Upgrade to 2.1.1 and let us know if the issue persists. Thanks!
