### ISSUE TITLE
Submitting Mautic form results in "405 Not allowed" in Webkit-based browsers

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#2295]
| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | n
| Enhancement? | n

## Description:
Trying to submit Mautic form with Webkit-based browser (e.g., Chromium) results in no redirect, pending "Please wait" button and "405 Not allowed" error in browser console.
It relates only to Webkit-based browsers, Firefox works well.

I've contacted hosting support - but they failed to reproduce the bug, even via a proxy (to avoid hosting IP influence). While it occurs all the time at my machine - and our subscribers reported that they have the same problem.

## If a bug:

| Q   | A
| ---| ---
| Mautic version | 2.0.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Open the site http://goo.gl/ze9jf8 (shortened for search privacy) in Webkit-based browser.
2. Try to submit the form with any email (you can safely use `test@example.com` to avoid abusing any real person).
3. Check browser console: if you get "405 Not allowed error" - it means the bug is reproduced.
 
### Log errors:
It's weird but no related logs are present: I've failed to find any - Mautic and server logs don't contain the error.

Any suggestions? How it can be that the hoster can't reproduce - while I (and at least several subscribers) get this all the time? What could be the reason of the error? How to avoid it?

**Comment by escopecz** [comment]
It must be due to the nginx configuration because the full error message is
```
405 Not Allowed

nginx-reuseport/1.11.1
```
So the request is stopped by nginx before Mautic could process it. I also cannot replicate it in any of my Mautic installations on different browsers, only at the form you provided.

Closing as it is not related to Mautic.

**Comment by PatchRanger** [comment]
@escopecz Thank you for your time, John.
