### ISSUE TITLE
"Open Email" Decision is missing in new Campaign Builder

### ISSUE THREAD

**Issue by stanus74** [mautic/mautic#2299]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:

In the new Campaign Builder the Decision "Open Email" is missing.

I have test this with a update Version from 2.0 to 2.1 and with a fresh 2.1 Installation.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Create a new Campaign
2. Contact Source "Segments"
3. Select Decision
 
### Log errors: 

no Log Errors

**Comment by stanus74** [comment]
![mautic1](https://cloud.githubusercontent.com/assets/20380165/17742977/6d3f95b0-64a2-11e6-8622-f5ba8ceb53ae.png)

**Comment by escopecz** [comment]
The new builder will give you the right options for every action. When You add the send email action and look at what decisions you can use, the open email decision will be there.
