### ISSUE TITLE
Apply and Save/Close Duplicates

### ISSUE THREAD

**Issue by brianteeman** [mautic/mautic#23]
Create a new category (email or campaign)
Enter some details. Press save
Observe the notification in top right that the category has been created
Press save and close
Observe the notification in top right that the category has been created
You now have two categories with identical details

**Comment by alanhartless** [comment]
Hey Brian!

Yup, I can duplicate this. Working on a fix now.

Thanks!
Alan

**Comment by brianteeman** [comment]
I assume this code is global as its the same with creating a lead

On 28 January 2015 at 20:50, Alan Hartless <notifications@github.com> wrote:

> Closed #23 <https://github.com/mautic/mautic/issues/23> via b4ad50f
> <https://github.com/mautic/mautic/commit/b4ad50f6bd6f3fe54523f2934e22c302e437e4d0>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/23#event-226373456>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by alanhartless** [comment]
Not global for this issue.  Is it happening with the standard lead form or the quick add?

**Comment by brianteeman** [comment]
standard

Quick add only has save and close

Shall I create a new issue then

On 28 January 2015 at 20:57, Alan Hartless <notifications@github.com> wrote:

> Not global for this issue. Is it happening with the standard lead form or
> the quick add?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/23#issuecomment-71914295>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by alanhartless** [comment]
I tried creating a new lead, clicked apply, then save and close but the latter updates rather than duplicates. Are you able to reproduce it?

Thanks!
Alan

**Comment by brianteeman** [comment]
And now I cant - sorry
