### ISSUE TITLE
Campaign execution simulator

### ISSUE THREAD

**Issue by paulofelixjunior** [mautic/mautic#2307]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? | N |
## Description:

Create an engine which allows Mautic user to simulate campaign execution, specially the decision tree in terms of conditions, decisions and actions.

Idea is to "debug" campaign execution without running it with real contacts and preventing errors in relationship ruler caused by inadequate decision tree design and other logic mistakes.

**Comment by escopecz** [comment]
Do you have an idea how would that work?

**Comment by paulofelixjunior** [comment]
Hi @escopecz,

First of all, I understand that this is not an easy request to be built.

My suggestion is system to run decision tree using "ghost" contacts which perform the conditions and decisions specified in the decision tree.

I think in something like a "campaign pre-debugger" - like you have in programming IDEs. By running simulation, system would stop after the conditions ans decisions (like stopping into a programming code line) and show, in a modal or something like to show how the action will be made (specially send emails).

**Comment by merlin0** [comment]
This is a great idea,  I am really missing the this atm,  I can understand that this will take time to implement.  So maybe it's an idea to have a third option for a campaign and emails ect. You can either have it on published,  not published or test phase.  So at least you begin with a clean slate  as far as the stats from the campaign go.  Currently I always make a duplicate test campaign so the testing doesn't affect the campaign stats.

**Comment by PatchRanger** [comment]
That's a great idea! I guess it implies switching to event-based triggering state machine instead of scheduler: see #1930 for details.
