### ISSUE TITLE
Failed e-mail appears as sent in contact timeline

### ISSUE THREAD

**Issue by wittwerch** [mautic/mautic#2313]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | 
| Enhancement? | 

## Description:
Failed e-mails to a contact appear in the timeline as sent. I encountered that behaviour as I was sending a manual e-mail to a contact.
I made the test with Amazon SES where you have to configure your allowed sending domains. The SMTP was dropping my mails and I think Mautic does not handle that error correctly.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.0
| PHP version | 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1

### Steps to reproduce:
1. Configure a mail transport that will reject certain sending domains (like Amazon SES)
1. Send a manual e-mail to that contact from the contact detail page
1. Process the mail queue from the cli (php app/console mautic:emails:send)
1. Check the contact page. The lead is marked as bounced (which is wrong, because the sending domain was wrong, not the contact). The email sent to the customer shows up as "sent", which give you the feeling that the contact received it.

![screen shot 2016-08-18 at 09 46 09](https://cloud.githubusercontent.com/assets/1575445/17766098/aec454d0-6529-11e6-810e-b098b0dfa321.png)

 
### Log errors: 
The Swift_TransportException bubbles up from the mautic:emails:send command

````
root@web001:/var/www/playground# php app/console mautic:emails:send


  [Swift_TransportException]
  Expected response code 250 but got code "554", with message "554 Message rejected: Email address is not verified. The following identities failed the check in region EU-WEST-1:
   55hubs Administrator <me@nope.com>, me@nope.com
  "


mautic:emails:send [--message-limit [MESSAGE-LIMIT]] [--time-limit [TIME-LIMIT]] [--do-not-clear] [--recover-timeout [RECOVER-TIMEOUT]] [--clear-timeout [CLEAR-TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>
````

**Comment by dongilbert** [comment]
Fixed in #2327
