### ISSUE TITLE
Add support for multiple select for custom fields in contact area

### ISSUE THREAD

**Issue by alecslupu** [mautic/mautic#2324]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | Yes |
| Enhancement? | Yes |
## Description:

In my scenario i need to add a list of multiple items for each of my contacts. For example, i need to add a list of industries and departments to my contacts, and i would like to be able to select more values for each one of my contacts.  I think is related to #575
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | v2.1.0 |
| PHP version | 7.0 |

**Comment by escopecz** [comment]
Multi select was implemented in Mautic 2.2
