### ISSUE TITLE
Email not sending to contacts from Campaign

### ISSUE THREAD

**Issue by beefaaubee09** [mautic/mautic#2328]
I am unable to send emails to my campaign contacts via mautic. I've checked each and every log still can not find the problem where it is coming from

Here are my app logs : 

> [2016-08-16 03:08:25] mautic.ERROR: Fatal: Call to undefined method Mautic\EmailBundle\Controller\PublicController::getModel() - in file /var/www/html/username/app/bundles/EmailBundle/Controller/PublicController.php - at line 95 [] []

I've checked my cronjobs too and they're perfectly working. 

Mautic Version  : 1.4.1
PHP Version : 5.6.22
Hosting : AWS

**Comment by escopecz** [comment]
Should be fixed in Mautic 2.1.0.

**Comment by beefaaubee09** [comment]
Thank you for your guidance. Appreciated
