### ISSUE TITLE
Froala Editor removed styles sheets, open graph and other stuff

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#2334]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The Froala editor in the 2.1 removed stylesheet from a custom HTML Landing page also removed Open Graph and other stuffs

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.0
| PHP version | 

### Steps to reproduce:
1. This is the custom HTML landing page ORIGINAL SOURCE CODE use in Mautic 1.3 and 1.4 without a problem. [link edit]

2. This is the result after saved the landing page in Mautic 2.1
[link edit]
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Could you please test if this PR fix it for you? https://github.com/mautic/mautic/pull/2258

**Comment by paulofelixjunior** [comment]
@escopecz, I'm facing a variation of this issue... I'm trying to incorporate Facebook Social Plugin code into a page. Froala is including a <br> tag where I did not want it and seems to be exploding Plugin codes into my landing page code....

**Comment by escopecz** [comment]
@paulofelixjunior please provide steps I can follow to recreate the issue.

**Comment by paulofelixjunior** [comment]
Hi @escopecz, sure.

1. Create a landing page using BLANK THEME.
2. Using developers.facebook.com, create an application and get the code to embed Social Comments plugin. Facebook will provide two tags - one tag to be inserted right after opening the <body> and other to be inserted where the Facebook content should be.
3. Using landing page editor, include the facebook html codes into the landing page code.
4. Save the landing page.
5. Open the landing page again e show the code. In my case, I noticed things like:
- The code that you inserted right after <body> tag will be followed by a <br> (that you didn't put there)
- There will be a  lot of new CSS declarations (seems to be mashed up from facebook);
- The facebook code will be different than originally inserted by you
- There will be <div> tag with facebook-like content (seems to be mashed up from facebook) that you didn't put there.

That's it. In case you need it, I can paste here some examples of the original code and the "wrong" code, after froala changing it.

tks

**Comment by escopecz** [comment]
@paulofelixjunior could you please first test if https://github.com/mautic/mautic/pull/2258 fixes your issue or not?

**Comment by escopecz** [comment]
@paulofelixjunior the fix was released in Mautic 2.1.1. Let us know if you still have issues and I'll reopen this issue if so.
