### ISSUE TITLE
Editing dashboard widget that removes prior existing config fields results in validation error

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#2348]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
## Description:

When editing the type of a widget that had custom config fields for that widget, saving the form results in a "form cannot have extra fields" validation error. 

| Q | A |
| --- | --- |
| Mautic version | 2.1.0 |
| PHP version | 7.0.6 |
### Steps to reproduce:
1. Create a Lifetime Cycle widget and save
2. Edit the widget and change the type to Stages in Time
3. Notice the extra fields error
### Log errors:

No errors - has to do with dynamically modifying the form

**Comment by mqueme** [comment]
Retested this, no error in version 2.6.1
