### ISSUE TITLE
Form field cannot be deleted in some cases

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#2350]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
In some cases it's not possible to delete a form field.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1-dev (2016-08-19 20:57 central EU time)
| PHP version | 5.6.24

### Steps to reproduce:
1. Edit a form
2. Add a field
3. Apply
4. Remove the field you created
5. Apply
- The field is not deleted.

**Comment by alanhartless** [comment]
@escopecz Did this get addressed in final 2.2? I was thinking it was but I could be thinking of something else like actions.

**Comment by escopecz** [comment]
Yes, this was fixed in 2.2.0.
