### ISSUE TITLE
Access filtering to landing pages

### ISSUE THREAD

**Issue by paulofelixjunior** [mautic/mautic#2353]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? | N |
## Description:

Hi guys.

Imagine that I create a journey based on one (or some) landing pages and this campaign is intended to touch only contacts from a certain segment.

My suggestion is to allow page to be optionally configured to be seen by:
- certain segments. If a page is hit by a contact from a segment which is not authorized, system redirects user to the URL specified as 301/302 redirection;
- contacts who attend specified behavioral filters (like have previously visited a page or submitted a form)
- anonymous or identified contacts
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
| PHP version |  |
### Steps to reproduce:
1. 
2. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mrerich** [comment]
this would be VERY useful as it would raise usability of Mautic greatly
