### ISSUE TITLE
Social Monitoring fields not mapped correctly.

### ISSUE THREAD

**Issue by domparry** [mautic/mautic#2356]
What type of report is this:

| Bug report? | 

## Description:

Contacts resulting form Social Monitoring on twitter are being created with Name and Surname mapped incorrectly. The twitter name becomes the Mautic Contact Surname, the twitter surname is mapped to Mautic first name.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1
| PHP version | PHP 5.6.22 (cli) (built: May 27 2016 11:17:57)

### Steps to reproduce:
1. Set up social monitoring fow tweets to any twitter handle
2. execute the appropriate cron
 
### Log errors: 

No error found in the log for this.

**Comment by domparry** [comment]
It's been 5 days, so just checking in. Anyone know how to solve this?

**Comment by mproud** [comment]
Having this issue too. Did anyone find a solution?

**Comment by mproud** [comment]
Temporary solution - change around the firstname/lastname in the array here: plugins/MaticSocialBundle/Command/MonitorTwitterBaseCommand.php line 285

**Comment by domparry** [comment]
Thanks!

**Comment by domparry** [comment]
Just to report back. This suggested workaround fixes the issue. Now to get it back into the codebase!

**Comment by alanhartless** [comment]
Is someone willing to PR this change so we can fix it in the next release?

**Comment by jordan8037310** [comment]
I'm working on this issue.

**Comment by jordan8037310** [comment]
Pull request #2682 is up if someone can test and verify!
