### ISSUE TITLE
{formfield=*} get converted to HTML entities

### ISSUE THREAD

**Issue by izziaraffaele** [mautic/mautic#2360]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
No matter which editor I use (visual, builder or html code), after saving and closing the email every `{formfield=*}` tag gets converted to html entities. For example `{formfield=vendor_name}` gets converted to `%7Bformfield=vendor_name%7D`.

| Q   | A
| --- | ---
| Mautic version | 2.1.0
| PHP version | 7

### Steps to reproduce:
1. add multiple {formfield=*} tags in different places of the email
2. Save and close
3. Edit again 
4. All {formfield=*} tags where converted to html entities version (if not all, some of them)
 
### Log errors: 
Nothing relevant

**Comment by izziaraffaele** [comment]
I've tested in a fresh Mautic installation using  the Neopolitan theme.

- I added some tags in the title and the body of the email's content. 
![schermata 2016-08-22 alle 11 17 56](https://cloud.githubusercontent.com/assets/2734825/17849712/5dc539e4-685a-11e6-8eb8-90e9b1f780d8.png)


- hit save & close button and Click edit again, this is what I see
![schermata 2016-08-22 alle 11 18 27](https://cloud.githubusercontent.com/assets/2734825/17849723/6daa7a54-685a-11e6-95ca-65ffd4681770.png)


- Click Save & Close without doing any change. Click edit again and this is what I see
![schermata 2016-08-22 alle 11 18 40](https://cloud.githubusercontent.com/assets/2734825/17849739/85e91012-685a-11e6-8060-3fc0ccf1d4b6.png)


As you can see it gradually convert {formfield=*} tags every time I hit Save & Close

**Comment by escopecz** [comment]
Will be fixed in https://github.com/mautic/mautic/pull/2625
