### ISSUE TITLE
Sendgrid support for API and webhooks

### ISSUE THREAD

**Issue by ventouris** [mautic/mautic#2361]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? |  |
| Enhancement? |  |
## Description:

I have linked my selfhosted mautic with a sendgrid account. I sent a couple of test emails to a small segment with personal emails. I wasn't able to make bounce and click links stats to work. Sendgrid has found the bounced emails and also marked my clicks on links inside the emails, but on mautic, those values are still on zero.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.0 |
| PHP version | 5.6 and 7 |
### Steps to reproduce:
1. Create a new email and send it to a tested segment that you know that contains a couple of fake emails. Use a sendgrid account for this.
### Log errors:

No log errors

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
We do not currently support Sendgrid webhooks to be notified if an email is bounced. We do want to switch Sendgrid to using their web API for sending email rather than SMTP - as part of that transition, we'll get webhooks setup.

**Comment by Arjoni** [comment]
It would be great to have this.

**Comment by ybombale** [comment]
+1
This would be really nice.

**Comment by marziovit** [comment]
it would be awesome to have this +1:

**Comment by franciscojun** [comment]
+1 Sendgrid, Mailgun and other similar tools via API

**Comment by dtenter** [comment]
+1. I can't get my self-hosted Mautic to clean bounces off my list. I used Sendgrid.

**Comment by ATouhou** [comment]
+1

**Comment by PatrikNorrgard** [comment]
+1

**Comment by rafallo** [comment]
+1

**Comment by dirtroof** [comment]
+1
This would be great.

**Comment by vdrover** [comment]
Did this ever happen?

**Comment by alanhartless** [comment]
Yes in 2.12.1 just released.

**Comment by vdrover** [comment]
Any documentation available? I actually guessed at the callback URL for sendgrid, but found that unsubscribes (for example) work perfectly well with or without the webhook at sendgrid.

**Comment by alanhartless** [comment]
Sorry - looked like we didn't merge in some doc changes including sendgrid. The font is a little wonky at the moment but we're working to fix that. https://mautic.org/docs/en/emails/bounce_management.html

**Comment by a1exe1** [comment]
Is it possible to get Opens and Clicks?

**Comment by RCheesley** [comment]
I've got Sendgrid set up with Mautic via the API method following the rather scant documentation, but I'm not seeing open/clicks in Mautic. Perhaps I missed something!  

I set up an email, added myself to a test segment and fired a campaign using the segment. Received the email - I see in the contact log that the email has been sent - but having opened the email, don't see that reflected in the contact log.

@alanhartless if we're using the API method, does the web hook now need to have all options selected (e.g. opens, clicks etc) rather than just the ones demonstrated in the documentation screenshot?

**Comment by vdrover** [comment]
Are you loading the URL in an incognito window?

**Comment by RCheesley** [comment]
Just to be clear this is for emails rather than landing pages, I've opened
in different devices where I'm not logged into Mautic.

**Comment by cesarjr** [comment]
Hi! I've configured Sendgrid webhook to send bounce data to Mautic. But, unfortunately, it's not being register at contact history.

If I check the Mautic's blog I can see this:

172.17.0.4 - cezinha [08/Aug/2018:12:30:28 +0000] "POST /s/mailer/sendgrid_api/callback HTTP/1.1" 302 689 "-" "SendGrid Event API",

172.17.0.4 - cezinha [08/Aug/2018:12:30:28 +0000] "GET /s/login HTTP/1.1" 200 9652 "https://xxx.yyy.com.br/s/mailer/sendgrid_api/callback" "SendGrid Event API"

Do you have any idea what's going on?

**Comment by PatrikNorrgard** [comment]
Hi,

Seems like your POST request is getting redirected (the 302 status, means redirect) to the Login-page. I suspect there is an issue with the authentication of the api-request.

Patrik

**Comment by cesarjr** [comment]
Hi @PatrikNorrgard !

See what I did in Sendgrid's URL:

https://my-mautic-user:my-mautic-pwd@my-mautic-server.com.br/s/mailer/sendgrid_api/callback

Before I've tried:

https://my-mautic-server.com.br/s/mailer/sendgrid_api/callback

Both options generate the same output at Mautic's log.

FYI: The API is enabled in my Mautic.
