### ISSUE TITLE
Email variant publish option acts weird

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#2369]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

When creating an email variant, the publish option is set to NO. But when saved like this, the publish option is changed to YES.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.6.25 |
### Steps to reproduce:
1. Create a segment email variant (template emails works correctly)
2. Fill in the required fields
3. Notice that the publish option is set to NO - do not change it
4. Apply and check that the publish option was changed to YES

**Comment by alanhartless** [comment]
I can't replicate this in 2.2. Maybe it's fixed?

**Comment by escopecz** [comment]
Closing for lack of answer. Feel free to comment with a new update and the issue will be opened again.
