### ISSUE TITLE
Issues when running with PHP on fcgid mode

### ISSUE THREAD

**Issue by MarceloPedra** [mautic/mautic#2377]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | Y

## Description:
After migrating to a new server, I've noticed that when PHP is run on fcgid mode, the cron tasks are stall and never end, thus overlapping and causing campaigns to be incorrectly sent two and three times. When the PHP handler is switched to cgi, all comes back to normal.
These are cPanel servers where you can easily switch between PHP handlers.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.0
| PHP version | 5.6.24 in fcgid mode

### Steps to reproduce:
1. Switch your cPanel server to fcgi and wait for the next cronjobs to execute when you have a campaign scheduled to be sent to more than 30k users.
2. The cronjob running the app/console mautic:campaigns:trigger command will last forever and due to it never ending, when the next cronjobs trigger, the server will have several instances running concurrently with high load, thus impacting negatively and also sending the same email several times.
3. Switch back to cgi mode, kill the previous stall tasks, and see how the next cronjobs will run thoroughly and complete within seconds :(
 
### Log errors: 
The log at [mautic root]/app/log/ are filled with entries like this:

`[2016-08-24 06:32:06] mautic.ERROR: Deprecation: The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0. Use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead. - in file /home/USERNAME/public_html/mautic/vendor/symfony/security/Core/SecurityContext.php - at line 14 `

this:

`[2016-08-24 06:21:50] mautic.ERROR: Deprecation: The hardcoded value you are using for the $referenceType argument of the Symfony\Component\Routing\Generator\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. - in file /home/USERNAME/public_html/mautic/app/cache/prod/classes.php - at line 1277 `

and this:

`[2016-08-24 06:00:34] mautic.ERROR: Deprecation: Accessing type "submit" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\SubmitType" instead. - in file /home/USERNAME/public_html/mautic/vendor/symfony/form/FormRegistry.php - at line 100`

and guess what, this too:

`[2016-08-24 03:15:21] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO campaign_lead_event_log (date_triggered, is_scheduled, trigger_date, system_triggered, metadata, channel, channel_id, non_action_path_taken, event_id, lead_id, campaign_id, ip_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["2016-08-24 03:15:21", 0, null, 0, "a:0:{}", "email", 4, 0, 12, 52255, 4, 896]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '12-52255' for key 'PRIMARY'" at /home/USERNAME/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO campaign_lead_event_log (date_triggered, is_scheduled, trigger_date, system_triggered, metadata, channel, channel_id, non_action_path_taken, event_id, lead_id, campaign_id, ip_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"2016-08-24 03:15:21\", 0, null, 0, \"a:0:{}\", \"email\", 4, 0, 12, 52255, 4, 896]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '12-52255' for key 'PRIMARY' at /home/USERNAME/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '12-52255' for key 'PRIMARY' at /home/USERNAME/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '12-52255' for key 'PRIMARY' at /home/USERNAME/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} `

Ideas/fixes asap will be very welcomed.
Thanks in advance!

**Comment by alanhartless** [comment]
What happens if you run the command(s) manually from CLI using the fcgid PHP handler?
