### ISSUE TITLE
Can't built Campaign for all contacts.

### ISSUE THREAD

**Issue by beefaaubee09** [mautic/mautic#2381]
What type of report is this:

| Bug report? | Yes
| Feature request? | No 
| Enhancement? | No

## Description:
I've just installed a fresh copy of **Mautic 2.1.0** & added around **180k** contact to whom I'll send out emails. I've created 3 segments & distributed all of the contacts in three different segments. Segment **A** has **150k** email contacts, Segment **B** has **5k** & Segment **C** has **5k** respectively. 
While I ran the command to enable the campaign it added around **32k** contacts in total & left rest of all contacts 

## If a bug:

| Mautic version | 2.1.0
| PHP version | 5.6

### Steps to reproduce:
1. Created contacts in contact.
2. Ran this Command (php /var/www/html/mautic/app/console mautic:campaigns:rebuild) 
 
### Log errors: 

No logs have been recorded for this action at app level as well as for server level.

**Comment by alanhartless** [comment]
Hi, could you please share what filters you used in your segments?

Are the segments showing the correct number of contacts in each?

**Comment by beefaaubee09** [comment]
Hi alanhartless,

I got the issue & it was while uploading/importing bulk contacts/leads to mautic there was an empty column which was causing termination of script at 32k contacts for campaign. Interestingly, I was looking through logs on server end as well as on application end but nothing was logged until i searched for the campaign leads in database and cross-checked the leads list where a lead ID had empty column which i later on filled with dummy data so to re-process/update leads for campaign & rebuilt it. This went successful & i added around 180k leads to my contact. 

I'd like to know if there's any enhancement i can make myself or will be made in next update by mautic team.

**Comment by keerthixerago** [comment]
Hi,
I have installed mautic.org version in my windows system. can you help me to setup cron jobs for mautic.

**Comment by dongilbert** [comment]
@keerthixerago Please refer to the user documentation @ https://mautic.org/docs
