### ISSUE TITLE
500 Error on email tracking links

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#2382]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Same email tested twice:
http://www.mail-tester.com/web-CjLHSC
http://www.mail-tester.com/web-XbgCk1

http://www.mail-tester.com/web-4BdINw

All 3 emails are using the same template, the links that say are 500 error's are part of the template and have not changed. Sometimes they report good and sometimes they are bad. I cant seem to find any good logs but the one pasted below is the best i can find.

The timeouts may be due to the size of my instance, I have over 600,000 leads in my setup and about 100,000 emails going out a month.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.0
| PHP version | 5.6.21

 
### Log errors: 

[Tue Aug 09 19:11:49.619460 2016] [:error] [pid 7085] [client XXX.XXX.XXX.XXX:41577] PHP Fatal error:  Call to a member fun                                                        ction isPublished() on null in /var/www/html/app/bundles/EmailBundle/Controller/PublicController.php on line 332

**Comment by escopecz** [comment]
It should throw 404 instead of that error message so that must be fixed. But the problem might be in the preview link generation as well. Do you by chance can publish here what the generated email preview link looks like in the problematic emails?

**Comment by ldrrp** [comment]
https://www3.attotech.com/r/6625a8a8a3768753a37e6b092?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6MTYyO31zOjU6ImVtYWlsIjtpOjE2MjtzOjQ6InN0YXQiO3M6MTM6IjU3YmRhYzU1NGVjODciO3M6NDoibGVhZCI7aTozMjExNTg7czo3OiJjaGFubmVsIjthOjE6e3M6NToiZW1haWwiO2k6MTYyO319

This mautic links goes to -> https://www.linkedin.com/company/40057

**Comment by alanhartless** [comment]
When you browse to those URLs causing 500's - what is the error recorded in the log that corresponds with the page hit?

**Comment by martinstr** [comment]
I have the same problem, geting 500 Internal Server Error on links in emails I sent out as broadcasts. 
But the links works when I am signed into Mautic and click the links in the emails.  

this is the errors
`[2016-08-31 13:40:18] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Requested URL not found: /mautic/email/57c6dd50cbaec.gif" at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/CommonController.php line 430 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Requested URL not found: /mautic/email/57c6dd50cbaec.gif at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/CommonController.php:430)"} []
[2016-08-31 13:40:47] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The string  is not a serialized array." at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Model/AbstractCommonModel.php line 263 {"exception":"[object] (InvalidArgumentException(code: 0): The string  is not a serialized array. at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Model/AbstractCommonModel.php:263)"} []
[2016-08-31 13:40:49] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Requested URL not found: /mautic/email/57c6d9a500658.gif" at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/CommonController.php line 430 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Requested URL not found: /mautic/email/57c6d9a500658.gif at /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Controller/CommonController.php:430)"} []
`

**Comment by martinstr** [comment]
I am running v. 2.1.1

**Comment by martinstr** [comment]
Think I found the problem, I had activated a plugin on mautic that caused this [https://github.com/kuzmany/MauticAnalyticsTaggingBundle](url)

**Comment by escopecz** [comment]
@ldrrp do you use the same plugin? If so, it's not a Mautic issue.

**Comment by ldrrp** [comment]
No, pure stock :)

**Comment by ElMandrillo** [comment]
Hi i have same problem. 500 Error when I click on any link in the email. the only one to work is the unsubscript link. You as you have solved?
