### ISSUE TITLE
Meta tags removed from custom landing page

### ISSUE THREAD

**Issue by mauticpro** [mautic/mautic#2385]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Hello,

I made a customized landing page template and when i install the theme the meta tags are removed from the source code.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.0
| PHP version | 5.6.23

### Steps to reproduce:
1. Get this theme: `https://github.com/mauticpro/mautic-pro`
2. Install
3. Create a new landing page
4. See source code

**Comment by escopecz** [comment]
This is fixed in Mautic 2.1.1 which was just released. Try it there and let us know if you'll have this issue there.
