### ISSUE TITLE
Cannot edit Contact when Owner has been changed

### ISSUE THREAD

**Issue by ToonGeneral** [mautic/mautic#2387]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
We regularly move contacts between members of staff, depending on who is best placed to contact them. We recently upgraded from 1.4.1 to 2.1.0. We are now finding that Edit seems limited to the contact creator, not the owner. Can I check this is by design?

If it is, it introduces a break in our use case that I can't get around using the UI, because the user can change the owner, but they then can't edit the contact. In order to fix it, I need to arrange for a manual edit of the DB with some SQL, which I try to keep to a minimum ;-)

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.1.0
| PHP version |  5.6.25

### Steps to reproduce:
1. Create contact as User 1
2. Change owner to User 2
3. Unable to edit the contact as User 2.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
This looks like a UI issue. I can still edit the contact by browsing directly to /s/contacts/edit/ID.

**Comment by alanhartless** [comment]
Fixed in https://github.com/mautic/mautic/pull/2392

**Comment by ToonGeneral** [comment]
Hi Alan, thanks for such speedy response! Great to see a fix so quickly too. You're right that we can work around this using the direct URL, but a lot of our users aren't very tech savvy.

Was about to ask for a chance of a bump into 2.1.1, then saw you released it an hour ago :-(
