### ISSUE TITLE
500 error on 2.1.1 update

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#2390]
| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

Not really sure, I ussualy just delete the cache folder, but it doesnt seem to be the case this time.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 7.0.7 |
### Steps to reproduce:
1. Update to 2.1.1
### Log errors:

[2016-08-25 15:11:04] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function has() on null" at /var/www/clients/client2/web49/web/vendor/symfony/framework-bundle/Controller/Controller.php line 162 {"exception":"[object](Symfony\Component\Debug\Exception\FatalThrowableError%28code: 0%29: Call to a member function has%28%29 on null at /var/www/clients/client2/web49/web/vendor/symfony/framework-bundle/Controller/Controller.php:162)"} []

**Comment by alanhartless** [comment]
Does this happen on every Mautic URL?

**Comment by ldrrp** [comment]
it happened on the dashboard, i went to sysinfo page and that worked. which is where the log is from. But my session timed out so now i cant even get to the login page.

http://demo.techreanimate.com/s/login

**Comment by alanhartless** [comment]
After you login - browse to another page directly like /s/contacts. Does that load? If it only happens on the dashboard - what widgets do you have enabled?

**Comment by ldrrp** [comment]
Not sure if u wrote this before i wrote mine but, i cant login now. its a 500 error. see the link.

**Comment by ldrrp** [comment]
Here is the log on my system log file, since i cant see the mautic one anymore.

[Thu Aug 25 11:15:18.713863 2016] [fcgid:warn] [pid 10927] [client 208.69.85.34:28647] mod_fcgid: stderr: PHP Fatal error:  Call to a member function has() on null in /var/www/clients/client2/web49/web/vendor/symfony/framework-bundle/Controller/Controller.php on line 162, referer: http://demo.techreanimate.com/s/login

**Comment by ldrrp** [comment]
One thing i noticed is that this demo setup when i installed redirected me to an update page without the domain name which resulted in a chrome dns error.

My demo instance is a fresh install with only the basic setup to get it running. I dont think it has the domain name in the config.

**Comment by alanhartless** [comment]
I saw the link but it shows the login form for me and obviously I can't login :) 

If you already have a session active, it's going to auto direct you to the dashboard. I realize my instructions weren't clear now that I'm re-reading them. Type directly into your browser, http:/yoursite.com/s/contacts. Does Mautic load?

Unfortunately, that error doesn't give us much information since it doesn't reveal where in Mautic's code we're calling that.

**Comment by ldrrp** [comment]
HAHA yes im logged in, turns our my session is still active. the contacts link directly works.

Yea gotta love php errors :(

I have gone through every single page and listed those that dont work. Here they are:
/s/dashboard
/s/config/edit
/s/themes
/s/account
/s/roles/edit/1
/s/users/edit/1
/s/emails/new

I honestly have no idea what modules i had enabled, The defaults for everything. I never changed settings on anything in this test setup.


As i was writing this i soon realized what the issue seems to pertain, I hit the logout button and now the login page works.... Maybe old data inside of my session. I had the "keep me logged in" checked when i did that update.

**Comment by ldrrp** [comment]
At the same time i wish i had exported my session data before i just did that :(

**Comment by alanhartless** [comment]
ok looks like we're going to have to throw in some debug code to see what's going on.

Edit the file /var/www/clients/client2/web49/web/vendor/symfony/framework-bundle/Controller/Controller.php. Go to line 160 and modify that function to be like

```
    public function renderView($view, array $parameters = array())
    {
        if (null == $this->container) die("<pre>".print_r(debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS), true)."</pre>");
```

Then try to reproduce the issue. Copy and paste what it spits out here.

**Comment by medianicus** [comment]
Also having this same problem, and as I don't have an active session, I can't access any of the pages.

How many lines of the file should be modified? (Sorry  - not a programmer).

**Comment by medianicus** [comment]
Okay. Applied some lateral thinking and figured that as it was already broke I couldn't do much more harm. So I switched PHP to ver 7.0.9 and am now able to login.

Might be an option for some.

**Comment by alanhartless** [comment]
Odd PHP 7 resolved it. What version were you using before?

**Comment by medianicus** [comment]
5.6.24 (both being run as Fast-CGI)

**Comment by MarceloPedra** [comment]
Hi! Here in the same boat as @medianicus. PHP 5.6.25 running on fcgi or cgi will die when upgrading via url in the browser. Only way to update by now is via SSH console using the "php upgrade.php" script :( 

When upgrading from 2.1.0 to 2.1.1 I got the php error log filled with this:

`[26-Aug-2016 15:56:09 UTC] PHP Fatal error:  Class 'ComposerAutoloaderInit8c8a4df9012bd52e2a6be3d92a1594ae' not found in /home/username/public_html/mautic/vendor/autoload.php on line 7 `

And upgrade_errors.txt is filled with 1945 lines mentioning php files not found like this one:

`Could not move file /vendor/aws/aws-sdk-php/src/Aws/S3/S3Md5Listener.php to production. `

Any solution to this?

**Comment by alanhartless** [comment]
@MarceloPedra this reads like a different issue than the one originally reported in this issue. Can you open a new one for it so we don't get them mixed? But one thing to check is your file permissions/ownership. It sounds like the user running the script doesn't have access to Mautic's files.

**Comment by crystalenka** [comment]
Hey guys, I'm having the same (or similar) issues after updating to 2.1.1. Current PHP version is 5.6.25; I cannot access the configuration due to timeout errors.

I tried changing the PHP version to 7.0.10, and I'm now getting 500 internal server errors when trying to log in.

I had originally been on 7 on upgrade, but downgraded to 5.6 because of PHP fatal errors whenever I tried to save anything, anywhere, which eventually always resulted in 500 internal errors.

Reverting to 5.6.25 clears the 500 internal errors, but many pages still time out or don't load altogether.

If this is related, let me know and I'll include the error logs from both mautic and my server. (Otherwise I'll make a new issue - sorry, this sort of problem is not where my expertise lies.)

**Comment by escopecz** [comment]
@crystalenka hard to say if it is related without the error messages. If you won't see the error message posted in this issue, then create a new one.

**Comment by dpeatross** [comment]
I am getting the same error after updating to 2.2.1. I do not know how to pull the log.

**Comment by ldrrp** [comment]
I have since reinstalled and moved my contacts over. i havent had any issues with 2.3.0
