### ISSUE TITLE
Getting error 500 while installing Mautic 2.1.1 (and 2.1.0)

### ISSUE THREAD

**Issue by silviodelgado** [mautic/mautic#2394]
When I try to run a clean install of Mautic, I get this error:

Fatal error: Class **'Symfony\Bundle\WebProfilerBundle\WebProfilerBundle'** not found in /home/marketing/www/app/**AppKernel.php on line 208**

**Comment by alanhartless** [comment]
If you downloaded from Git and using index_dev.php, you need to install dev dependencies: https://github.com/mautic/mautic#getting-started

Otherwise download the distribution packaged from https://mautic.org/download.

Thanks!

**Comment by silviodelgado** [comment]
Thanks for advice, but I'm stilll getting error.

When I access the file http://url.to/mautic/installer: (index_dev.php - even renaming to index.php)
"You are not allowed to access this file."

When I change last line of code of this file:
From: Stack\run((new MiddlewareBuilder('**dev**'))->resolve($kernel));
To: Stack\run((new MiddlewareBuilder('**prod**'))->resolve($kernel));
I'm getting this new error: 

**"500 Internal Server Error - There is no suitable CSPRNG installed on your system"**

**Comment by silviodelgado** [comment]
In this link https://github.com/mautic/mautic/issues/1960 I've found that CSPRNG is uncompatiple with OpenSSL. Would that be the problem?

**Comment by leokovaski** [comment]
Hello friends. Was able to resolve by setting some folder permissions:

/mautic

find . -type d -exec chmod 755 {} \;
find . -type f -exec chmod 644 {} \;
chmod -R g+w app/cache/
chmod -R g+w app/logs/
chmod -R g+w app/config/
chmod -R g+w media/files/
chmod -R g+w media/images/
chmod -R g+w translations/
chown -R $USER:www-data
