### ISSUE TITLE
mtracking.gif getting blocked after switching to SSL

### ISSUE THREAD

**Issue by abooster** [mautic/mautic#2398]
What type of report is this:
| Enhancement? | yes
## Description:

After switching the entire site as well as Mautic installation (same domain) to SSL, 
Mautic's mtracking.gif is now getting blocked by uBlock Origin (on the client side) and probably by many other adblockers as well. 

Since Mautic isn't an ad delivery software but is used to track people who have opted in with their details (or at least have agreed to the privacy policy by continuing browsing the site), it is ethically and morally justifiable to hide Mautic from adblockers. 

All that needs to be done to achieve that is to **remove the word "tracking" from the mtracking.gif file** name and replace it with something innocent like "**mtinfo.gif**" for example. 

That will prevent adblockers from blocking the tracking gif. 
Simple but sweet. :-)

**Comment by zyzioziom** [comment]
No, it's a tracking software and adblockers will and should be blocking it.
Adblockers will update their filters in less than a week anyway.

**Comment by abooster** [comment]
@zyzioziom Wrong! Adblockers are specifically looking for the "tracking" keyword in file names. 
They can't "update their filters" to include all words of the dictionary of all languages of the world. 
And they will NOT update their filters to specifically target Mautic because Mautic is NOT an ad software. 
Mautic is legitimately tracking users *who have opted in with their email address* or at the very least have agreed to the privacy policy (by continuing browsing the website), the privacy policy that specifically states that by continuing browsing the website, the website visitor agrees with the use of cookies and the tracking implied by it. 
Ad blockers do NOT target such cases. This would put all legitimate businesses out of business, businesses who need to track their customers or people who want more information from these businesses.

**Comment by abooster** [comment]
Ideally, Mautic would give the user an option (in config settings) to rename the "mtracking" part of the gif file to whatever they want. 
That would make sure that ad blockers will NEVER be able to block the tracking gif in the future.

**Comment by abooster** [comment]
I just did this: 
searched for "mtracking" and found only 4 files containing it. One of those files was a translation file. So, only 3 relevant files: 
app\bundles\PageBundle\Model\PageModel.php
app\bundles\PageBundle\Config\config.php
app\bundles\CoreBundle\EventListener\BuildJsSubscriber.php

I replaced the word "tracking" in those files with an innocent little word, cleared Mautic's cache and voila: 
As expected uBlock Origin immediately stopped blocking the gif file after that.

**Comment by MxyzptlkFishStix** [comment]
That block is from the EasyPrivacy list.  The EasyPrivacy list is specifically designed to block tracking software, not ads.  It's blocking "/mtracking." specifically at line 1559.  I wouldn't worry about it.  I doubt you'd register a percentage point or two in desktop traffic that uses an adblocker or even less with EasyPrivacy enabled by default outside of uBlock users.  It'll be even less with mobile traffic.

**Comment by abooster** [comment]
I don't remember whether or not I had changed the default settings in uBlock Origin. 
If not, then that list is probably the default setting. 

uBlock Origin has over **5.6 million users across Chrome and Firefox** and I don't think it's right for this particular software to block Mautic by default. 
If my users opt-in (or even continue browsing the website) they agree to be tracked and to be cookied. 
(and in case they object, they need to leave my website)

Anyway, changing those 3 files manually is not a big deal for me. I can do that for my Mautic installation.

**Comment by Arjoni** [comment]
This needs to be done! I can confirm that changing the name works!

**Comment by npracht** [comment]
@escopecz i think since we moved to script that can be closed, don't you think ?

**Comment by MxyzptlkFishStix** [comment]
Heck, it didn't have much merit in the first place.  There's over 1 billion active Chrome and 250 million active Firefox monthly users.  We're talking sub one percentage point user share here with uBlock Origin enabled.  Beside, I think empty content and 1x1 pixels are flagged for inspection automatically when uBlock encounters web sites with that type of content.
