### ISSUE TITLE
Difference between doctrine schema and database

### ISSUE THREAD

**Issue by Dcoutelle** [mautic/mautic#2400]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Big difference between schema in database and the schema into doctrine entity.... that could lead to intermittent and not reproductible problems

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1, but exist on other version
| PHP version | 5.6.19

### Steps to reproduce:
1. install fresh install 2.0.1
2. mautic:update:install
3. mautic:doctrine:schema:update --dump-sql

![doctrine_schema](https://cloud.githubusercontent.com/assets/14074272/17997863/781a2772-6b71-11e6-8d16-cd2c49cd8cf4.PNG)

**Comment by alanhartless** [comment]
Since it's creating a table - my guess is that it hit some kind of error during the schema upgrade. What does `doctrine:migrations:status` show?

**Comment by alanhartless** [comment]
Anything in the log as it actually says it hit an "error while updating the database?"

**Comment by Dcoutelle** [comment]
You are right, i missed the error in log : 
`[2016-08-29 07:36:20] mautic.NOTICE: Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 1 passed to Mautic\LeadBundle\EventListener\DoctrineSubscriber::__construct() must be an instance of Monolog\Logger, none given, called in C:\wamp64\apps\wmk_mautic_public\app\cache\prod\appProdProjectContainer.php on line 6702 and defined (uncaught exception) at C:\wamp64\apps\wmk_mautic_public\app\bundles\LeadBundle\EventListener\DoctrineSubscriber.php line 34 while running console command `doctrine:migrations:migrate` [] []`

doctrine:migrations:status:
![image](https://cloud.githubusercontent.com/assets/14074272/18044366/cae06d14-6dcd-11e6-92c3-1f6b6e64cb54.png)

**Comment by Dcoutelle** [comment]
After doctrine:migration:migrate

![image](https://cloud.githubusercontent.com/assets/14074272/18045022/f6ba436c-6dd0-11e6-9084-07357ea31361.png)

**Comment by alanhartless** [comment]
After 2.2, I had no differences between a 2.1.1 and a 2.2 installation/upgrade.
