### ISSUE TITLE
Stats missing after upgrade

### ISSUE THREAD

**Issue by Arjoni** [mautic/mautic#2401]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? |  No 
| Enhancement? |  No

## Description:
I updated from 1.4.1 to 2.1.1 via the web application without any errors but all stats are gone and the loading bar never stops.  https://imgur.com/vnbxb8b

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.1.1
| PHP version |  5.6.23-1

### Steps to reproduce:
1. Upgrade from 1.4.1 to 2.1.1/
2. Go to dashboard
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

[2016-08-26 08:30:45] mautic.ERROR: Deprecation: The alias option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is deprecated since version 2.8 and will be removed in 3.0. Use the extended_type option instead. - in file /var/www/domain.com/vendor/symfony/framework-bundle/DependencyInjection/Compiler/FormPass.php - at line 67 [] []

Here is the console output: https://imgur.com/b9yLdAP

**Comment by MxyzptlkFishStix** [comment]
Have you tried clearing your cache?

**Comment by Arjoni** [comment]
@MxyzptlkFishStix Yes, no change.

**Comment by alanhartless** [comment]
Are there any other symptoms in Mautic/areas not working?

**Comment by Arjoni** [comment]
There is also this thing i have never seen before https://imgur.com/Pz0Edfx but after a refresh it disappears. I haven't yet tested the email sending but everything looks fine except some broken css like this https://imgur.com/vTyRF6o

What do you want me to test?

**Comment by Arjoni** [comment]
update: When i click on a lead, i get: Uh oh! I think I broke it. If I do it again, please report me to the system administrator!
500 Internal Server Error
Mautibot

**Comment by alanhartless** [comment]
Check your logs for what caused it.

**Comment by Arjoni** [comment]
Mautic logs or apache logs?

**Comment by alanhartless** [comment]
Mautic logs.

**Comment by Arjoni** [comment]
Here are mautic logs:

`[2016-08-26 18:43:24] mautic.ERROR: Deprecation: The alias option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is deprecated since version 2.8 and will be removed in 3.0. Use the extended_type option instead. - in file /var/www/marketing.domain.com/vendor/symfony/framework-bundle/DependencyInjection/Compiler/FormPass.php - at line 67 [] []

apache error log for mautic:

`
[Thu Aug 25 23:27:14.474413 2016] [:error] [pid 20576] [client 79.106.109.178:37421] exception 'RuntimeException' with message 'Failed to write cache file "/var/www/marketing.domain.com/app/cache/prod/classes.php".' in /var/www/marketing.domain.com/vendor/symfony/class-loader/ClassCollectionLoader.php:248\nStack trace:\n#0 /var/www/domain.com/vendor/symfony/class-loader/ClassCollectionLoader.php(122): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::writeCacheFile('/var/www/market...', '<?php \\nnamespac...')\n#1 /var/www/marketing.domain.com/app/bootstrap.php.cache(2642): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::load(Array, '/var/www/market...', 'classes', false, false, '.php')\n#2 /var/www/marketing.domain.com/app/AppKernel.php(244): Symfony\\Component\\HttpKernel\\Kernel->doLoadClassCache('classes', '.php')\n#3 /var/www/marketing.domain.com/app/AppKernel.php(110): AppKernel->boot()\n#4 /var/www/marketing.domain.com/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /var/www/marketing.domain.com/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#6 /var/www/marketing.domain.com/app/middlewares/VersionCheckMiddleware.php(56): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#7 /var/www/marketing.domain.com/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#8 /var/www/marketing.domain.com/vendor/stack/run/src/Stack/run.php(13): Stack\\Stacked
`

**Comment by Arjoni** [comment]
Firefox console: https://imgur.com/tvkvrWs

**Comment by Arjoni** [comment]
Update: stats in general don't work at all. https://imgur.com/i9x4jX1

Maybe you could give me a demo database and we can see if the database processing didn't work while the application was updating.

**Comment by Arjoni** [comment]
Sorry for too many updates but when i open the app, the loading bar never stops and clicking on other menus doesn't do anything.

**Comment by Arjoni** [comment]
Another annoying update: when i edit one email, the toolbar is missing.  There are no icons.

**Comment by MxyzptlkFishStix** [comment]
Try actually deleting the /app/cache/prod folder.  But, before doing so, either disable the cronjobs first or do a quick refresh (CTRL+R) of Mautic in your browser before the cronjobs have had a chance to run.  I have seen where the crons will fill the cache but with the wrong ownership/permission of the directory/files.

**Comment by Arjoni** [comment]
Nothing changed. Here is another mautic error:

`[2016-08-27 14:39:34] mautic.WARNING: PHP Warning: Invalid argument supplied for foreach() - in file /var/www/marketing.enterprise.com.al/app/bundles/PageBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 76 [] []`

**Comment by Arjoni** [comment]
Nothing changed. Here is another error:

`[2016-08-27 14:39:34] mautic.WARNING: PHP Warning: Invalid argument supplied for foreach() - in file /var/www/marketing.domain.com/app/bundles/PageBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 76 [] []`

**Comment by Arjoni** [comment]
one more hint: I reverted back to 1.4.1 with backups (files and database) and tried to update with ssh. 

It gave me this error while extracting: 
`PHP Fatal error:  Cannot redeclare class Mautic\AddonBundle\Entity\Addon in /var/www/marketing.enterprise.com.al/app/bundles/PluginBundle/Entity/Addon.php on line 22
`

I have installed one custom plugin. Could it be the problem?

**Comment by Arjoni** [comment]
UPDATE: Cloudflare Auto-minify feature seems to be breaking the site. it worked fine with 1.4.1. Sorry for all the trouble. Thanks to both of you for trying to help.

**Comment by alanhartless** [comment]
Apparently there is an issue with Froala, the new editor we're using and
Cloudflare. Others have reported it here as well so I reported it upstream.
https://github.com/froala/wysiwyg-editor/issues/1482

**Comment by Arjoni** [comment]
Thank you.

**Comment by alanhartless** [comment]
Closing this then since it's already been reported upstream. Hopefully they'll fix it!

**Comment by BurlesonBrad** [comment]
apparently, someone thinks my issue is related to this thread: https://www.mautic.org/community/index.php/5426-error-you-do-not-have-access-to-the-requested-area-action/p1#p15158 

I'm not quite sure if it does, but... on the slight _(or **slightly GOOD!**)_ chance that my issue does related to #2401 , I thought I'd swing by over here and connect-the-dots. :smile_cat:

**Comment by alanhartless** [comment]
Hi there. Disable JS minifying in your CloudFlare account which your domain looks to be using looking at your Mautic's source of the URL in that forum post. It's apparently not compatible with Froala editor.
