### ISSUE TITLE
self hosted mautic need a handy CDN setting block;

### ISSUE THREAD

**Issue by lenghan1991** [mautic/mautic#2402]
What type of report is this:

| Q  | A
| ---| ---
| Feature request? |  Y

## Description:
I have a self-hosted mautic and I want all the static assets can be delivered in CDN. Any handy way I can follow?

**Comment by alanhartless** [comment]
Hi! This type of thing is more appropriate for https://mautic.org/community or https://mautic.org/slack. 

Thanks!
