### ISSUE TITLE
Mautic not working after installation

### ISSUE THREAD

**Issue by serverfreak** [mautic/mautic#2408]
I've tried enabling open_base_dir with /dev/urandom. However, it is still showing the same error. Also tried manually installing using composer, however it didn't work. Gave the below error:

===
arning: Composer should be invoked via the CLI version of PHP, not the cgi-fcgi SAPI
<br />
<b>Notice</b>:  Undefined index: argv in <b>phar:///opt/cpanel/composer/bin/composer/vendor/symfony/console/Input/ArgvInput.php</b> on line <b>55</b><br />
===

Please help.

I've checked almost all related forums and am unfortunate. Please help.

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
What's in Mautic's logs?

**Comment by luizeof** [comment]
@serverfreak .. shared host or VPS? PHP version?

**Comment by serverfreak** [comment]
It is shared server. Php version 5.6 and mysql version 5.6.31. 

===
[27-Aug-2016 15:32:53 UTC] PHP Notice:  Constant PASSWORD_BCRYPT already defined in /home/travelkl/public_html/managestacy/update_pass.php on line 11
[27-Aug-2016 15:32:53 UTC] PHP Notice:  Constant PASSWORD_DEFAULT already defined in /home/travelkl/public_html/managestacy/update_pass.php on line 12
===

Above is the only thing showed in error logs.

**Comment by escopecz** [comment]
@serverfreak chec https://mautic.org/docs/en/tips/troubleshooting.html to see what logs to check. The one reported above doesn't belong to Mautic.
