### ISSUE TITLE
Themes thumbnails not appearing in 2.1.1

### ISSUE THREAD

**Issue by marckell** [mautic/mautic#2409]
For my recent upgrade from 1.4.1 to 2.1.1, the theme thumbnails were not appearing when selecting New Email.

I changed line 53 of the .htaccess file in the Mautic root directory to include themes in the list of directories (app|addons...etc.), and the thumbnails now appear, but I'm not sure that's the valid fix.

Without that addition to the .htaccess file, the images do not appear, and are redirected to the index.php file:

/themes/oxygen/thumbnail.png

would redirect to:

/index.php/themes/oxygen/thumbnail.png

**Comment by escopecz** [comment]
That's maybe because you should not have the /index.php/ in the Mautic's URL at all. The mod_rewrite is not probably installed/enabled?

**Comment by marckell** [comment]
You are correct. mod_rewrite was not enabled.
