### ISSUE TITLE
Hours Last Activity is different from hours system

### ISSUE THREAD

**Issue by cerebrumbr** [mautic/mautic#2414]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Contact > Column > Last Activity > Hours is differente form hours system

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 5.6

### Steps to reproduce:
1. Contact > Column > Last Activity
2. Difference hours of system
 
### IMAGES

![01](https://cloud.githubusercontent.com/assets/2263217/18052441/c5b6008a-6dd0-11e6-8d3c-e7e15e94caf7.png)

![02](https://cloud.githubusercontent.com/assets/2263217/18052446/c9eb6ece-6dd0-11e6-88a9-d3c3c69c56a3.png)

**Comment by alanhartless** [comment]
See https://github.com/mautic/mautic/pull/2397. We fixed the locale issue and introduced a timezone issue. But that pull request should fix it.
