### ISSUE TITLE
FBL-report processed but not resulted in unsubscribing

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#2418]
| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | n
| Enhancement? | n

## Description:
FBL-reports got processed - I've checked it by manually entering the mailbox: all of the mails were read.
But the email address from FBL-report was not marked as DoNotContact - it remains as usual, so any further mailing to it would be sent without any restriction, which is wrong.

## Reason
I've put debug code near the point of decision.
I've discovered that `dsnReport` and `dsnMessage` for unknown reason are empty - while they are important for correct processing.
I've searched https://github.com/barbushin/php-imap (as there are links to it) for related issues - nothing.
We have only one FBL configured (FBL from mail.ru) - so it could be provider-related.
I am ready to provide .eml-file of one of such FBL-reports for Mautic development team - if necessary.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Configure FBL for Mail.ru: https://postmaster.mail.ru/settings/ .
2. Make your email sendings as usual - until first FBL-report comes.
3. Either by cron job or manually run fetching command: `php app/console mautic:email:fetch --env=prod`.
4. Enter the mailbox and make sure all of the emails are read - it means that command successfully processed all of them.
5. Get the latest FBL-report for email of "unsubscriber".
6. Check Mautic's contacts for such email.

Expected result: The contact marked as DoNotContact.
Real result: The contact was not marked as DoNotContact.
 
### Log errors:
No related logs.

**Comment by rmalla** [comment]
Hello, has this been resolved? I'm woking on this issue at the moment. 

The parser seems to be working for some emails, but not for others. Any ideas?

Thanks, 

Ricardo Malla

**Comment by rmalla** [comment]
Some emails are parsed, while others are not. It depends on the format of the email. Here are some highlights:

Files of interest:



/app/bundles/EmailBundle/MonitoredEmail/Processor/Bounce/DsnParser.php

/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php:

/app/bundles/EmailBundle/MonitoredEmail/Processor/Bounce.php



The process as I understand it is the following:

On Mailbox.php you define what emails are considered for un-subscription:

public function searchMailbox($criteria = self::CRITERIA_UNSEEN)
{
$mailsIds = imap_search($this->getImapStream(), $criteria, SE_UID);

return $mailsIds ? $mailsIds : [];
}



I manually edited this code to have the program scan ALL the emails on the Inbox.

public function searchMailbox($criteria = self::ALL)
{
$mailsIds = imap_search($this->getImapStream(), 'ALL', SE_UID);
// malla

return $mailsIds ? $mailsIds : [];

}





Once you have the ids, it goes to Bounce.php, where it get to the following line of code.



$bounce = (new Parser($this->message))->parse();



This line sends the message texts to DsnParser.php to have them parsed and the relevant information resolved.



The problem arises on DsnParser.php on the following lines,

$dsnMessage = ($message->dsnMessage) ? $message->dsnMessage : $message->textPlain;
$dsnReport = $message->dsnReport;

Were for some reason, dsnReport comes back empty for some format of emails.



I'm stuck there, not sure how the dsnReport works...
