### ISSUE TITLE
Creating Category in New Email > Forwards to Category Page, Email Lost

### ISSUE THREAD

**Issue by jeffmilton** [mautic/mautic#242]
When you create a new category in the new email screen, it forwards you to the list of categories and even if you hit back, you've lost the email you were working on.

**Comment by alanhartless** [comment]
Hi Jeff,

I think I found the issue causing that and fixed in the references above. Just to confirm, I could only reproduce this if I clicked Apply first in the category modal then Save and Close.  Can you confirm that?

Thanks!
Alan
