### ISSUE TITLE
Mautic Not tracking Gmail 'email opens'

### ISSUE THREAD

**Issue by Augentia** [mautic/mautic#2420]
What type of report is this: Bug

| Q | A |
| --- | --- |
| Bug report? | Bug that mautic not tracking gmail email opens |
| Feature request? |  |
| Enhancement? |  |
## Description:

I triggered a test campaign yesterday - and covered major email domains viz., Yahoo, Gmail, Hotmail, Outlook et al. The email opens are tracked in email domains except Gmail. Please refer Contact ID 993 (my gmail account - sivkishor@gmail.com) or ID 10022 my colleagues gmail - where I received the first email and opened it. The Mautic still says the email not read. And it triggered a reminder email after 3 hours, which should be triggered only if the 1st email is not opened. I opened the reminder email too in Gmail - however it still not showing as opened. Please check this issue with Gmail domains. In my colleagues case it behaved very differently - it tracked the 1st email as open, however it failed to track 2nd and 3rd emails on different subject (though he had opened these emails). 
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | Mautic.com |
| PHP version |  |
### Steps to reproduce:
1. Intermittent issues with Gmail opens (you may need to send 2 or 3 gmail accounts and see in some cases - email open not getting tracked.
2. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by zyzioziom** [comment]
Gmail disables images by default - and Mautic tracks open using 1px gif image.
Were images displayed while reading your emails?

**Comment by Augentia** [comment]
Hi Patryk,

Gmail is configured in MS Outlook client – and sometimes it tracks, and other times it isn’t. It is an intermittent issue. If this logic is true, then it should not be tracking any gmail opens.

I also tried opening Gmail in browser, and there again the same happens of one email it tracks open, and the next email it isn’t.

**Comment by zyzioziom** [comment]
Let's try to investigate that.

Open Gmail interface in your browser and launch developer console (in Chrome: right mouse click -> inspect). Switch to NETWORK tab and open email (remember to enable images, too). You should look closely if your browser downloads the mautic tracking gif (it should be downloaded from your mautic domain)

**Comment by guizero** [comment]
Hello @patrykkalinowski 
I am getting the following:
```
https://ci5.googleusercontent.com/proxy/qWN459tvCPsfzBiG21dGKii-W_3mYd2k5ff…7kzWXrl32zw=s0-d-e1-ft#https://mautic.forky.com.br/email/58779f17750de.gif Failed to load resource: the server responded with a status of 404 ()```

If I go straight to the domain, it works.
