### ISSUE TITLE
Queued mails are shown as sent

### ISSUE THREAD

**Issue by wittwerch** [mautic/mautic#2425]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | yes |
## Description:

The status of emails sent during a campaign is misleading. If you are using queue mode, emails are spooled in the filesystem and sent later on. Depending on how frequent you ran the cronjob and how much emails you sent, it can take some time till these emails are sent (when they are at all!). 
Our customer look at these statistics and got the impression, that these 25'000 mails were sent immediately. This is wrong and should be reflected in the UI, mabye by showing these emails as queued.

The screenshot shows 100 emails I spooled to the filesystem but actually never sent out.
![screen shot 2016-08-31 at 09 59 06](https://cloud.githubusercontent.com/assets/1575445/18120788/98a7e4cc-6f61-11e6-9243-60ae3e7f98cd.png)
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 7.0.5-2+deb.sury.org~trusty+1 |
### Steps to reproduce:
1. Configure Mautic to queue emails
2. Disable the cronjob to process the queued emails
3. Create a campaign and send out some emails
4. Emails are shown as sent
5. Emails are still in the queue

**Comment by PatchRanger** [comment]
I guess we should add `is_queued`, `date_queued` and `is_sent` properties to Email entity - and fill them in at appropriate moments: both for immediate send and for scheduled. That should give enough data for charts.

**Comment by stevegrant1983** [comment]
While we're addressing email statuses, could this fix be extended to also fix the issue in #2976, whereby follow-up emails are always marked as opened when they're only either queued or sent? It would seem to be related...

**Comment by dyodji** [comment]
Any update on this issue? Doesn't appear to have made it into 2.7.1
