### ISSUE TITLE
Uploading image in New email > error

### ISSUE THREAD

**Issue by jeffmilton** [mautic/mautic#243]
![screen shot 2015-04-01 at 4 21 04 pm](https://cloud.githubusercontent.com/assets/2906312/6954119/c0bcd396-d88b-11e4-8381-f34e00a23112.png)

**Comment by jeffmilton** [comment]
Does not even gracefully allow you to retry or reset the upload procedure, you have to cancel out and try again  ... which gives the same result.

**Comment by alanhartless** [comment]
Hi Jeff,

Thanks for reporting this. Can you try using the "Browse Server" button on the Image Info tab.  That will give you a file manager where you can upload and select images.  We'll get that upload tab issue sorted out.
