### ISSUE TITLE
Add contact/user notification email or SMS

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2433]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | N |
| Feature request? | Y |
| Enhancement? | N |

**I create a new feature request that takes pieces of other to make it more complete.**
## Description

In the plateform, there is only one way to have a notification (an alert via email) which is addressed to someone else that the contact concerned. In the **form actions**, `Send form result`.
![capture d ecran 2016-08-31 a 15 16 55](https://cloud.githubusercontent.com/assets/14075239/18130277/a5ba152c-6f8e-11e6-9f8a-5f908d61d572.png)

This feature is very important to notify salesmen for instance when a contact has made a specific action!
## Where to add the feature?
- Forms ---> Already existing and named `form results`
- Campaign builder actions
- Lead scoring actions
### Campaign builder as an action

Requested here: https://github.com/mautic/mautic/issues/124

It would be very very great to have a "**Send notification to email address or user**".
Cause today you can do it from Froms actions. But **doing that from campaigns would allow much more situation where it could be relevant**.
Examples:
- You could notify people from a form submission but different people depending on the value selected when the form has been submitted.
- You could notify a salesman when a lead has visited a specific page (customer of product A visits page B).
- and much more...

![capture d ecran 2015-11-25 a 14 18 47](https://cloud.githubusercontent.com/assets/14075239/11398292/fbfa7b70-937f-11e5-927e-25d1c6e53a75.png)
### Lead scoring actions

Requested here: https://github.com/mautic/mautic/issues/1183

In the Point Triggers, add a new type of Event --> Email notification
Open a popin with different fields: `Title`, `Description`, `Subject`, `Message`, `To`, `CC`, `BCC` existing in the form action.
![capture d ecran 2016-08-31 a 15 21 06](https://cloud.githubusercontent.com/assets/14075239/18130267/a21ab142-6f8e-11e6-9c30-13e302cc0aa4.png)
Same as notification in forms requested here https://github.com/mautic/mautic/issues/1719 it should be great to set the recipient depending on some contact field values.
#### Content of message field

It would be great to have the right to add in the content of the message:
- Any {leadfield=alias}
- Points
- Point history
### 
## Don't forget the different channels !

It should be implemented knowing that you could should the channel used by the notification! That's also very powerful!
- Emails
- Text message (SMS)

**Comment by kuzmany** [comment]
Speed up developement  ;)
https://www.bountysource.com/issues/37448396-feature-request-add-contact-user-notification-email-or-sms

**Comment by Loanatik** [comment]
I still think that #3005 is a more elegant and flexible implementation of this concept.  Regardless of the implementation, the important functionality is that we can use {contactfield=SalesPersonEmail} as the TO: address.  There is a note above that indicates this functionality is already in Forms.  It is not.  The use in forms is to send the form to a Mautic User.  The functionality needed is to send the form to any email address stored in the contact's record.

**Comment by RCheesley** [comment]
With forms you can use a form action to send the form results to any email address @Loanatik - so that option is there already but it doesn't exist in other contexts such as during a campaign as a campaign action, for example.  It would be a handy feature to allow it to be there - or to allow you to set whether the email is going to the contact, or to a specific address etc.

**Comment by kvalade** [comment]
Would love to see this prioritized as it's a pretty big blocker to executing true sales and marketing automation.

**Comment by jordan8037310** [comment]
+1 for sending emails to third-party emails as a part of the campaign process. Use case for us is we want to use mautic drip campaigns to manage sales automation, and the campaign email would send to the Lead Owner so that they are reminded to call the contact and follow up.

**Comment by leonardoborlot** [comment]
+1
I have solicited this today, but was rejected because and the moderator tell me about this opened issue.
This is a very helpful tool.
This was on the milestones for which version?

**Comment by npracht** [comment]
Hello @leonardoborlot it is not milestoned yet. If you have the opportunity to contribute developing that i'm sure that @mautic team will milestone it asap :)
