### ISSUE TITLE
TypeError: request.responseText is undefined

### ISSUE THREAD

**Issue by katalysis** [mautic/mautic#2435]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? |  |
| Enhancement? |  |
## Description:

Clicking Save & Close or Apply in the email editor hangs intermittently.  
There is an error shown in Firebug:

TypeError: request.responseText is undefined
...esponse=request.responseJSON;}else{var errorStart=request.responseText.indexOf('...
app.js?vd54d5983 (line 152, col 87)
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.6.25 |
### Steps to reproduce:
1. create or modify and save email, this can be either with supplied (Oxygen) or our own custom template.
2. 
### Log errors:

Apache log gives following error:

2016-08-31 16:43:57 Error           .489 [INFO] [216.244.66.242:50030] connection to [/tmp/lshttpd/APVH_katalysisftp_Suphp56.sock.633] on request #1, confirmed, 1, associated process: 18210, running: 1, error: Connection reset by peer!             Apache error

Mautic log shows no associated error.

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Please check if it's not related to https://github.com/froala/wysiwyg-editor/issues/1482

**Comment by escopecz** [comment]
Closing for lack of answer. Feel free to comment with a new update and the issue will be opened again.
