### ISSUE TITLE
InvalidCharacterError: String contains an invalid character

### ISSUE THREAD

**Issue by katalysis** [mautic/mautic#2436]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
creating a new email in the editor and selecting the Oxygen template and saving works but then opening the email again results in Froala screen only partially loading and the following error in Firebug:

InvalidCharacterError: String contains an invalid character
...)!==null){return ret;}else{ret=jQuery.find.attr(elem,name);return ret==null?unde...
librari...54d5983 (line 571)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 5.6.25

### Steps to reproduce:
1. create new email
2. select oxygen template and add a character to the headline
3. Save and Close
4. open again for editing
 
### Log errors: 

Server log:

2016-08-31 17:12:17	Error			.409 [INFO] [95.211.217.68:50166] connection to [/tmp/lshttpd/APVH_katalysisftp_Suphp56.sock.473] on request #1, confirmed, 1, associated process: 22041, running: 1, error: Connection reset by peer!				Apache error

Nothing relevant in Mautic log.

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
I'm not able to replicate it. Please check https://github.com/mautic/mautic/issues/2401#issuecomment-242932315 if it is the same issue.

**Comment by katalysis** [comment]
Checked 2401 and we're not using Cloudflare.

**Comment by escopecz** [comment]
Tested one more time and I can see the problem. The error for me is

`2.jquery.js:6956 Uncaught InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '!important;' is not a valid attribute name.`

jQuery seems to have problem with some attribute values like `!important` (https://bugs.jquery.com/ticket/11173)

**Comment by katalysis** [comment]
OK, I stripped out all the !important values from the Oxygen template and I still get the error on saving after reopening the document.

Looking at the code quote marks etc. seem to be changed to html entities - not sure if that's an issue.

`	<body style="font-family: &quot;Oxygen&quot;,&quot;Helvetica Neue&quot;,&quot;Arial&quot;,&quot;sans-serif&quot;; height: 100%; color: rgb(103, 103, 103); width: 100%; margin: 0px; min-height: 300px;">
`
What are you using to see your error message? The only info I'm getting is 'InvalidCharacterError: String contains an invalid character '

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/2474

**Comment by lonevetad** [comment]
Similar issue: i acidentally added an unwanted character, like a "6" in HTML code, like "<div 6> ..." and that damned number were f***ing everything.
