### ISSUE TITLE
Personalised Attachments

### ISSUE THREAD

**Issue by Skrypton** [mautic/mautic#2437]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | Y |
| Enhancement? |  |
## Description:

How efficient would it be sending personalised PDF files for various transactional emails. Wouldn't it be fantastic sending emails with personalised attachments in a userfriendly way automatically?

Those personalised attachments could be event tickets, invoices, order confirmations, presentations, and many more. I believe it would be great having such a feature in Mautic. What do you think?

One way of implementing this could be adding a new lead field type (e.g., attachment) and an additional option to "send email" action in the campaign builder (e.g., personalised attachment) that allows setting the lead field type with the attachment.

For event tickets would this work perfectly, however, for transactional emails that are having frequently different attachments with same content every time the feature https://github.com/mautic/mautic/issues/1606 would be a must have.

Who else in our community thinks that personalised attachments would be an efficient feature in our Marketing Automation?

**Comment by arikmeyer** [comment]
We'd also be very interested in adding personalized PDFs to transactional emails (order confirmations, custom generated documents, etc.).

**Comment by ithieund** [comment]
Is there any solution for this now? I can't find any related document.

**Comment by guptavijay208** [comment]
Hi, Any update on above?
