### ISSUE TITLE
HTML editor reorders HTML xmlns attributes and replaces part of an HTML xmlns attribute with emoji

### ISSUE THREAD

**Issue by snowcoda** [mautic/mautic#2440]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No 
| Enhancement? | No

## Description:
When using an HTML template with xmlns attributes on the HTML specific to resolving some issues in Outlook email rendering, part of the attribute gets changes to what I assume is an emoji.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 7

### Steps to reproduce:
1. Create a new email campaign
2. Name te campagin and set a segment
3. Go to the content tab
4. Click the source code button
5. Add the following to the markup:
`<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">`
6. Save the email
7. Open the email
8. Click the source code button
9. The markup will have changed to:
`<html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com??office" xmlns:v="urn:schemas-microsoft-com:vml">`

NOTE: In the above, the order of the xmlns attributes has changed (probably not a big deal, but a change none the less). More critically however, one of the attributes has had part of its value replaced with an emoji symbol for 'office'.

I'm assuming the above is caused by the latest version of the Froala editor that is incorporated into Mautic.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by MohHeader** [comment]
I am not sure why, but we are having this issue once again, our Mautic version is 4.4.4 
the : office : is converted to 🏢 
<v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com🏢word">
