### ISSUE TITLE
Grey border in editor can break layouts

### ISSUE THREAD

**Issue by katalysis** [mautic/mautic#2441]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
The grey border added around all object by the Froala editor will in certain instances break the layout of the email.

![mautic-broken-layout](https://cloud.githubusercontent.com/assets/4235012/18162982/a682ea4a-7030-11e6-8ae7-769035e6e487.jpg)

While css border-box property seems to be applied to certain cells by the editor the layout remains broken.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6.25

### Steps to reproduce:
1. create layout with fixed width table cells allign tightly to containing table.
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Could you please provide the HTML of your template for testing? It doesn't happen on any table I tried. If you test it on mautic.net Mautic instance, does it happen there?

**Comment by escopecz** [comment]
Well, wait a moment, you mean while editing? Froala adds the border so the users could see the table cells and edit them. Do you think that's a bug? How would you do it then?

**Comment by katalysis** [comment]
@escopecz No real problem with the grey border just the fact that it breaks the layout.

**Comment by escopecz** [comment]
Yes, it can break the layout in the editor, but the border is filter out before save so the result is not broken. Is that right? Can you think of any suggestion how to do it better?

**Comment by katalysis** [comment]
I'd probably not show the border except on hover which may work but to be honest this issue is pretty small compared to the genaral pain I'm feeling after about 4 days trying to get my templates to work in Froala.

I've been through Mautic and Froala github and added various config changes to try and stop my code being altered and I'm still getting extra paragraphs, spans and br tags all over.  My code is quite complex I've got spans with styling etc. nested in paragraphs and tables cells also with styling and it's been tested carefully on upteen email clients in Litmus.  All worked well in 1.4 but just creating a new email now breaks the template.

I just can't see how this can work for email editing going forward, even if Froala can be made to stop adding and removing tags at will, giving this much editing power to users will result in emails being created that cannot possibly retain visual integrity across a range of email clients. 

There is surely a need for a system where the underlying code can be locked down and users can be given managed access to editable areas for text and images.  This worked well previously with builder.

Sorry this has gone off the point of the issue and is sounding like a whine.  I'm hugely appreciative of Mautic and have enjoyed starting to use it in our business but I'm frustrated that at the moment I can't find a way to continue using it.

**Comment by escopecz** [comment]
Please test https://github.com/mautic/mautic/pull/2454 if it will fix your issue.
