### ISSUE TITLE
Froala changes image size

### ISSUE THREAD

**Issue by katalysis** [mautic/mautic#2445]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
The width of my email template is 600px, I have a full width image that is 600px which fills the width of the containing table cell.
After editing Froala has set the width of the image to be 598px so now the image no longer exactly fits the layout and also appear pixelated as it no longer matches screen resolution.

Code prior to editing:

`<table style="width: 600px;" class="full-width" align="center" border="0" cellpadding="0" cellspacing="0">
                        <tbody>
                            <tr>
				                <td class="image-100-percent" valign="top" style="font-family: 'Droid Sans', 'Helvetica Neue', 'Arial', 'sans-serif' !important;font-weight: 400;text-align: center;" data-slot-container>
				                    <div data-slot="image">
				                        <img src="{{ getAssetUrl('themes/'~template~'/img/header-image.jpg', null, null, true) }}" width="600" height="340" alt="header image">
				                    </div>
				                </td>
                            </tr>
                        </tbody>
                    </table>
`

Code after editing:

`<table align="center" border="0" cellpadding="0" cellspacing="0" class="full-width" style="width: 600px;">
							<tbody>
								<tr>
									<td class="image-100-percent" data-slot-container="" style="font-family: 'Droid Sans', 'Helvetica Neue', 'Arial', 'sans-serif' !important;font-weight: 400;text-align: center;" valign="top">
										<div data-slot="image"><img class="fr-dib fr-draggable" style="width: 598px;" src="http://www.katalysis.net/pages/themes/katalysis-promo/img/header-image.jpg" alt="header image" height="0" width="598"></div>
									</td>
								</tr>
							</tbody>
						</table>`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 

### Steps to reproduce:
1. Insert an image into a table  exactly the same size.
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Pixman** [comment]
Hello,
Thanks to report this bug, i have the same problem on my mautic server.

I check my html code into notepad++, i copy paste into fraola editor on mautic. Save the page, and my pictures img are modified like you.

**Comment by escopecz** [comment]
This one was hard to figure out. I created JSBin with very similar Froala configuration as we have in the Email builder:

https://jsfiddle.net/r5c2rm3h/1/

It worked there. When I compared the CSS injected to the Froala's iframe, some parts were different from what Froala in Mautic injected. More on that in https://github.com/mautic/mautic/pull/2454. Please, test it if you can.
