### ISSUE TITLE
Froala changes {leadfield=firstname} to %7Bleadfield=firstname%7D

### ISSUE THREAD

**Issue by katalysis** [mautic/mautic#2447]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Bug
| Feature request? | 
| Enhancement? | 

## Description:
When fields are included in the Froala editor and saved the opening and closing curly bracket symbols are converted to  %7B and %7D

This doesn't seem to stop them working but is disconcerting for the user.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi,

I think i've met the same issue while opening an email created on old theme and opened since migration to 2.x.x on a theme not converted.
Any chance you had the same behavior ?

N.

**Comment by escopecz** [comment]
@katalysis I can't seem to replicate it. If I create new email, add some tokens to the email body and even as a `href` attribute of a link, save it and open it, the curly brackets stays the same.

**Comment by katalysis** [comment]
I've attached my email code:
[email-source.txt](https://github.com/mautic/mautic/files/505827/email-source.txt)

You'll see the top two leadfields have been changed to  %7B and %7D.

If you change these back to curly brackets, save and open again they will be  %7B and %7D again.

If you save once more without editing and reopen then the next two sets of curly barckets will also have been changed.

**Comment by escopecz** [comment]
Thanks, I can replicate it there! I'll try to fix it.
