### ISSUE TITLE
Lead Smart Lists > 

### ISSUE THREAD

**Issue by jeffmilton** [mautic/mautic#245]
Select List > Filters > Owner = Jeffrey Milton > Save or Apply = 500 Error

Nothing in apache log.

**Comment by alanhartless** [comment]
Hi Jeff,

That PR should fix this issue and will be included in our 1.0.2 release due out this week. 

As a FYI, when you run across future 500 errors, also check app/logs/mautic_prod.php as exceptions encountered within Mautic will be logged there.

Thanks!
Alan
