### ISSUE TITLE
BUG: Editor adds diffrent height and width values to images.

### ISSUE THREAD

**Issue by merlin0** [mautic/mautic#2455]
What type of report is this:

Bug 

Description:
We just upgraded to 2.1.1 because we had a issue where the editor would add random widht values to the images in the e-mail template. It seems that the problem still exist in 2.1.1.
An example would be the following 

    <td width="100%" height="10" style="color: #393939; padding: 0;"><img src="your_source/blank.gif" width="100%" height="10" style="display: block;"></td>
 
The editor changes this to: 

    <td height="10" style="color: #393939; padding: 0;" width="100%"><img src="img src="your_source/blank.gif" style="width: 560px;" class="fr-dib fr-draggable" width="560" height="560"></td>

 Mautic version 
2.1.1
PHP version 
5.6.24

### Steps to reproduce:
1. Upload a theme with a similar blank image as in the description
2. Check the code editor to see if the default height and width has been replaced with other values.
3. Preview the e-mail or send a test example to check.

**Comment by escopecz** [comment]
Please check https://github.com/mautic/mautic/pull/2459 if you could test it and if it works for you.

**Comment by merlin0** [comment]
Just tested it still the same issue for us, it keeps overwriting the default height we gave in the theme.  This didn't happen in 2.0.1 .  Thanks for the fast reponse!

**Comment by escopecz** [comment]
@merlin0 could you please read the description at #2459 and comment bellow it what you think about it? I mean if you want to ditch Outlook and not have the width and height parameters defined?
