### ISSUE TITLE
Tasks & Opportunities

### ISSUE THREAD

**Issue by Arjoni** [mautic/mautic#2457]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | x |
| Enhancement? |  |
## Description:

I would love to have a tasks module where you can add tasks for a lead. It could also have an option for opportunities. A small CRM.  Maybe an updated version of https://github.com/redmantech/Mautic_CRM which works for mautic versions < 2.x.

**Comment by BatchHeader** [comment]
I have installed the Mautic_CRM plugin on v2.2.1 and it does work but the project seems to have stalled. This seems to be a natural plugin for Mautic and would be great to see this part of core to get more developers working on it.

Is there a roadmap to add this kind of functionality?

**Comment by BatchHeader** [comment]
I'm guessing not then!
