### ISSUE TITLE
Delete button : Fix annoying overflow-hidden , (form result -> last result)

### ISSUE THREAD

**Issue by l2aelba** [mautic/mautic#2458]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | n/a
| Enhancement? | n/a

This is a bit annoying when I want to delete last result (Forum result)

**The last delete button is under their container**

![mnmnmu3zzd](https://cloud.githubusercontent.com/assets/983458/18204911/9706a65c-711f-11e6-839b-6d98e12a70c8.gif)

Seems like Mautic added wrong overflow values in `.table-responsive-force`, But if removed those properties :

![pdpwt4ttyj](https://cloud.githubusercontent.com/assets/983458/18204949/c1214b90-711f-11e6-8884-df6a0843d98b.gif)

So the button is visible now

![q2umpgniea](https://cloud.githubusercontent.com/assets/983458/18204969/d71d4fac-711f-11e6-8fdd-58a06b9c5168.gif)

But im not sure this changes make any affect on other elements or not.

**Comment by escopecz** [comment]
I'm using 2.2.0 codebase and I don't see the problem you nicely described:
![mautic-dropdown](https://cloud.githubusercontent.com/assets/1235442/18990375/b3291952-8711-11e6-9f37-0f6232cae48e.png)

If you'll be having it even with 2.2.0, let us know what browser is making the trouble and I'll reopen it.

**Comment by l2aelba** [comment]
@escopecz Yes, But no fixed in "Form results"

![stbrfdlnec](https://cloud.githubusercontent.com/assets/983458/19232616/0e0bdc02-8ee1-11e6-8739-25d4fd3e772f.gif)

**Comment by alanhartless** [comment]
This is a bug in Bootstrap with table responsive and drop downs that unless something has changed, they aren't fixing. https://github.com/twbs/bootstrap/issues/11037#issuecomment-29547489

We'll have to do some hack with JS probably to overcome this.

**Comment by alanhartless** [comment]
I found  a hack :-) Try #2711.
