### ISSUE TITLE
Froala translate &lt; inside <code>

### ISSUE THREAD

**Issue by AndreaBarghigiani** [mautic/mautic#2460]
What type of report is this: 

| Q | A |
| --- | --- |
| Bug report? | Froala translate &lt; inside my email. |
## Description:

I am usign the Campaign to send a free sample of my courses that are focused on coding. Most of the time I do not have any problem because I do not use the angular brakets but when I have to send some HTML or PHP code I have several issues...

I am trying to work with the text editor and until I do not hit _Apply_ or _Save_ I can switch back and forth between visual and text witout problems. But when I press one of the button above all my work is wasted. I get back on with the previous errors that will mix my text with `<code>` tags...

For big blocks of code I create and image, that's not the best solution but I am happy with it. The problem relies on the text where sometimes I need to explain how to open PHP or insert an HTML element to refeer to it.

Have someone found this kind of problem?
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.6.25 |
### Steps to reproduce:
1. Open the editor and write something like `<html>` or `<?php` 
2. move to the text editor and wrap `<html>` into `<code>`
3. Change to the visual editor and add other text after the `<html>`
4. Hit _Apply_ and see all the following text became wrapped in `<code>` tags
### Log errors:

In the log there are no errors about this, I think because it's primarly JavaScript related. But when I was testing to list the steps to reproduce **Froala cut half of my text**! At the moment it's not a problem because I can copy and paste the lesson, but I am sure can hurt someone else.

**Comment by escopecz** [comment]
It is a Froala issue. I created https://github.com/froala/wysiwyg-editor/issues/1546 about it.
