### ISSUE TITLE
Allow sending custom email from another sender name and address

### ISSUE THREAD

**Issue by nickion** [mautic/mautic#2468]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Seems like it |
## Description:

I created an email template with an associated sender address, however sending a custom email based on the template uses the logged in name and email address rather than that of the sender associated with the template. It's essential to be able to send from email addresses different to that of the logged in user and without manually having to adjust the sender address as that takes time and is error prone. Possibly other advanced tab fields do not take preference too.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.0 |
| PHP version | 5.5.34 |
### Steps to reproduce:
1. Login with an email address different to `foo@somedomain.com`
2. Create an email template with sender `foo@somedomain.com` on the advanced tab
3. Send a custom email to a contact using the template saved in step 1.
4. Observe that the sender is your email address rather than `foo@somedomain.com` as specified by the template.

**Comment by escopecz** [comment]
That's how it was designed. If you send a direct email from contact detail, it should be send as you, the Mautic user. You can select some predefined email to save time writing it over and over, but it copy only the content, not other meta data.

**Comment by nickion** [comment]
Users may need to have a different email address based on context. For example, there may be an email that is sent from "Fred" as part of the sales team, and where it's appropriate for anyone to deal with the reply and the email should come from "sales@...". However, in another situation, "Fred" may be interacting more personally with a contact, and want to email as "fred@...". 

There are almost always more use cases for ones software than can be imagined, and how the software is intended to be used may well not be how it needs to be used, The fewer arbitrary assumptions and limitations there are the better.
