### ISSUE TITLE
[Feature Request] Livehelperchat integration

### ISSUE THREAD

**Issue by Arjoni** [mautic/mautic#2469]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | x |
| Enhancement? |  |
## Description:

Livehelperchat (https://livehelperchat.com/ open course project) integration. Basically create leads for chat visitors.

**Comment by RCheesley** [comment]
+1, it's a useful open source system for online chat-based interaction.

How would you envisage this being used? Would the logs just be stored against the customer based on email address or would it be more complex (eg a campaign trigger etc)?

**Comment by Arjoni** [comment]
@RCheesley I would like basic integration. When a user starts a chat, he/she gets registered as a lead on mautic.

**Comment by 3ruce** [comment]
+1
