### ISSUE TITLE
Importing contacts with points is broken

### ISSUE THREAD

**Issue by pierreavizou** [mautic/mautic#2470]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

When importing contacts, the recap at the end of the process indicates that all contacts were ignored. There is a list below, with numbers in red, but no error message is assoiated with those numbers. See screenshot below.

<img width="571" alt="capture d ecran 2016-09-04 a 12 30 36" src="https://cloud.githubusercontent.com/assets/7101583/18230429/6d917284-729b-11e6-8b44-194b5b693c77.png">

I have made sure that my .csv file does not contain invalid values for the fields I map to in Mautic. 

It is to be noted that this file contains contacts that should be merged into existing ones (to add more data that Mautic captures with the tracking pixel). 
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.6.23 |
### Steps to reproduce:
1. Import a CSV file with contact details
2. Map to existing Mautic fields
3. The import should indicate that all contacts were ignored.
### Log errors:

There are no related errors in the logs.

**Comment by escopecz** [comment]
Please provide a CSV file or its content for testing. I cannot replicate it.

**Comment by pierreavizou** [comment]
Hi @escopecz , below is the content of a csv file that causes the bug to happen. 

```
id_produit;nom_produit;id_commande;id_client;firstname;lastname;email;address1;address2;zipcode;city;mobile;newsletter;nombre_de_commandes;country;ip_address;date_added;date_updated;birthday;attribution;
"528";"Tickets Red Hot Chili Peppers à Paris - Date : Mardi 18 octobre 2016, Catégorie : Fosse Or";"12341";"16095";"Caroline";"Janot";"janot.caroline2@gmail.com";"4 rue de jarente";"";"75004";"Paris";"0760609157";"1";"1";"France";"70.32.40.2";"2016-08-28";"2016-08-28";"1978-10-02";"258.000000";
"591";"Tickets Insus à Rennes - Date : Mercredi 9 novembre 2016, Catégorie : Fosse";"12316";"16069";"claudine";"HARDY";"clo.hardy@free.fr";"40 rue de Triquerville";"";"35400";"st MALO";"0679141026";"1";"1";"France";"66.249.69.206";"2016-08-27";"2016-08-27";"1960-01-19";"166.500000";
"426";"Tickets Justin Bieber à Paris - Date : Mercredi 21 Septembre 2016, Catégorie : Fosse Or";"12169";"15846";"Johanna";"Foolchand";"johanna.foolchand@hotmail.com";"30 avenue du Général de Gaulle";"deuxième étage porte droite";"94350";"Villiers sur Marne";"0695972756";"1";"1";"France";"207.46.13.39";"2016-07-30";"2016-08-27";"1997-02-22";"199.000000";
``` 

Also, I provide you with two screenshots of how I mapped the CSV fields to fields in Mautic. 

![capture d ecran 2016-09-05 a 12 30 51](https://cloud.githubusercontent.com/assets/7101583/18245356/0a60dfcc-7365-11e6-8ef5-70fdf3bce68c.png)
![capture d ecran 2016-09-05 a 12 30 58](https://cloud.githubusercontent.com/assets/7101583/18245357/0a63ca84-7365-11e6-988e-786f68e6b4ad.png)

I would also like to add that when I choose not to map the 'Nom Produit' field, the import seems to work fine. 
I suspect the problem comes from fields that contain values with accents. Hope this helps.

**Comment by escopecz** [comment]
Yes, I can replicate. The error message:

```
This form should not contain extra fields.
origin: lead
cause: Symfony\Component\Validator\ConstraintViolation
Object(Symfony\Component\Form\Form) = [points => 1]
```
suggests that it's caused by importing points. Please, try not to import the points and the import should be successful. I'll mark this as a bug.

**Comment by pierreavizou** [comment]
Thanks a lot for the feedback. Importing without points works indeed. 

I have another remark: When a field (i.e Country or birthday) contains an invalid value, the whole contact is ignored. Would it be possible to just have Mautic set the invalid value to NULL in its DB instead of ignoring the whole contact?

**Comment by stemoga** [comment]
Same problem here with a fresh install of Mautic 2.2.1 and PHP 5.6.27.
Importing contacts with points fail, without points works.

**Comment by JoaoPauloSouza** [comment]
any update or workaround on this?

**Comment by mqueme** [comment]
This is no longer a bug. Points are used only when a contact is a new contact. for existing contacts the csv file will not update points
