### ISSUE TITLE
Add Stages to API

### ISSUE THREAD

**Issue by ToonGeneral** [mautic/mautic#2472]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | Y |
| Enhancement? |  |
## Description:

Allow me to change a Contact's Stage via the API please!

I now have three Helper campaigns with one Action; change a Stage!

My external scripts using the API are needed to get more granular control over Contact's progress through campaigns. Stages really help with this and with tracking our process as a whole, but need API control!
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
| PHP version |  |
### Steps to reproduce:
1. 
2. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
It's currently in the development

**Comment by Loanatik** [comment]
+1 I need this functionality as well

**Comment by isleshocky77** [comment]
@escopecz Is there any issue already opened or planned that would handle the ability to map integration fields to the Stage? If not, I'll be opening a new issue for that with regards to the Salesforce integration. Not sure if it would already be handled with this Feature Request.

**Comment by escopecz** [comment]
Added to 2.3

**Comment by iuribrindeiro** [comment]
Hello, I`m using right now the api v2.3.0 and trying to use that method: "addContact" from "stages" context.
But it's not really changin the contact stage in mautic. After take a little look at the mautic code I realized that in the method "addToStages" from LeadModel, the changes aren't persisted in the database. Is that a bug or I'm doing something wrong?

**Comment by escopecz** [comment]
You might be right. I'm just checking the unit tests for that:

https://github.com/mautic/api-library/blob/master/tests/Api/StagesTest.php#L80-L109

It only check the success mark, not if the contact was really added to the stage. Please, create a new issue with your findings.

**Comment by tralljf** [comment]
Has bug been fixed? I am having the same problem in version v2.5.1

**Comment by escopecz** [comment]
> Please, create a new issue

**Comment by lucianojmf** [comment]
I am having the same problem too @tralljf @escopecz 
How can i resolve it? I need urgently use this endpoint.

**Comment by escopecz** [comment]
For the record: https://github.com/mautic/mautic/issues/3331
