### ISSUE TITLE
Time on Notes entered in UTC or local time?

### ISSUE THREAD

**Issue by ToonGeneral** [mautic/mautic#2475]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
I'm not sure if this is a bug, or just a question about expected behaviour. I couldn't find a relevant issue in GitHub, nor could I find references to times for Notes (or times in general) in the documentation.

If I create a note on a contact, then enter the time right now for me (16:07 BST), that's the time that gets entered in the DB.

If I load the contact in Mautic, the time displayed on the note is 17:07, I assume because it's treating the time in the DB as UTC/GMT.

Is this correct? I feel like it didn't do this before.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.1.1
| PHP version |  5.6.25

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Do you think it should be a timezone issue fixed by https://github.com/mautic/mautic/pull/2397?

**Comment by ToonGeneral** [comment]
Possibly and sorry for missing that, I searched for date, datetime, time, all sorts, not timezone!

It would make sense, if the UI is entering times into the DB as entered, not as entered-1 (BST) like it was, then adding an hour back on when displaying.

So does this mean everything entered via the UI since updating to 2.1.1 will be an hour out?

**Comment by escopecz** [comment]
Depends on your timezone. The problem will be fixed in Mautic 2.2.0. I'll close this issue since it was already reported and fixed.

**Comment by ToonGeneral** [comment]
How come you reopened @dbhurley?

**Comment by dbhurley** [comment]
Accidental, sorry!
