### ISSUE TITLE
Queued emails show time when they were queued, not actually sent

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#2482]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I'm reporting this issue on behalf of Jiri Bocek who sent it to me by email.

If a big bunch of queued emails is sent, it can take several hours to process. But the time when the email was sent is actually the time when the email was added to the queue. So when the email is sent several hours later, the email client displays it after the new emails he received that day.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 5.6.25

### Steps to reproduce:
1. If you don't have a contact segment with thousands of contacts, you can switch email sends to queue, send an email to your testing segment and trigger the send command after a hour.

**Comment by wittwerch** [comment]
Related to #2425
