### ISSUE TITLE
Segmenting by stage = none

### ISSUE THREAD

**Issue by yyil** [mautic/mautic#2485]
Feature request (testing on 2.1.1)

Original forum post here:
https://www.mautic.org/community/index.php/5488-how-to-segment-by-stage-none/
## Description:

My contacts are not assigned to a stage by default.
They get stages assigned either manually or through automation.

Segmenting filters available for stage is either:
- equals
- not equal

In attempt to leave behind contacts who don't have a stage value set, I've tried building a series of filters, such as:

Stage not equal to aaaa
AND
Stage not equal to bbbb
AND
Stage not equal to cccc
AND
Stage not equal to dddd

However this returns 0 contacts. How can I return all my contacts who don't have a stage value set? There's surely gotta be better filters available for stages e.g.
- is empty
- not empty
- including
- excluding

etc

It looks like ListModel.php (2.1.1) line 389 is where the code needs to be changed

**Comment by tachang** [comment]
This would be useful. I tried changing it around to regexp but didn;t work.

**Comment by yyil** [comment]
Is it possible to also add:

- including
- excluding

to the filter options?
