### ISSUE TITLE
Set stage to blank causes 500 error

### ISSUE THREAD

**Issue by ToonGeneral** [mautic/mautic#2490]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

Editing a contact, which had a stage value set, and setting stage to empty/Choose one... causes a 500 error, rather than a handled error message.

I know that the docs say somewhere that it shouldn't be possible to move to a stage of a lower value (it actually is, although I'm not raising the bug report about that!), however they don't say what should happen in this scenario. Whatever should happen, it probably shouldn't be a 500 :-)
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.6.25 |
### Steps to reproduce:
1. Create a contact
2. Set stage = x
3. Edit contact
4. Set stage = 'Choose one...'
5. Apply
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

`[2016-09-07 09:43:55] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\InvalidArgumentException: "Expected argument of type "Mautic\StageBundle\Entity\Stage", "NULL" given" at path-to-mautic/vendor/symfony/property-access/PropertyAccessor.php line 254 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\InvalidArgumentException(code: 0): Expected argument of type \"Mautic\\StageBundle\\Entity\\Stage\", \"NULL\" given at path-to-mautic/vendor/symfony/property-access/PropertyAccessor.php:254)"} []`

**Comment by escopecz** [comment]
This should be fixed in the Write API endpoints PR I and Alan are working on (not pushed yet, it's in progress).

**Comment by vexersa** [comment]
+1
Using Zapier to push contacts into Mautic I get the same error. V2.2

**Comment by maciekkus** [comment]
Probably the same bug/issue, but I get it when:

1. added new contact via API /contacts/new
(email = 'test@email.com', first name='John', last name = 'Doe')
2. set stage = x for test@email.com (in mautic admin panel)
3. edited contact via API /contacts/new (email="test@email.com", first name="John", last name="Smith"

result: 500 error

looking forward for the upcoming fix.

**Comment by escopecz** [comment]
Guys, feel free to test https://github.com/mautic/mautic/issues/2738 and write there how the test went. It'll help to get that PR merged.

@maciekkus check the logs to make sure it's the same error: https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by maciekkus** [comment]
@escopecz 
that's error message from mautic API after editing contact (no stage value provided, although contact has it set)

  "error": {
    "message": Expected argument of type "Mautic\StageBundle\Entity\Stage", "NULL" given",
    "code": 500
  }

**Comment by escopecz** [comment]
Fixed in 2.3
