### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2494]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

When setting a different timezone for a user, dates are still shown in UTC

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1

### Steps to reproduce:
1. Change timezone
2. Check date/time in a contact timeline

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/2397

**Comment by chandon** [comment]
it seems #2397 solves this issue
