### ISSUE TITLE
Trouble Upgrading 2.0.1 --> 2.1

### ISSUE THREAD

**Issue by kevingarman** [mautic/mautic#2495]
This is probably just my ignorance, but I can't seem to upgrade from 2.0.1.  I've try going to both 2.1.0 and 2.1.1....currently I'm try to go one step at a time start with 2.1.0.

PHP version is 7.0.9

Here's what I'm trying from the Mautic folder of my working 2.0.1 install (git cloned from github):

1)  git fetch --tags
2)  git checkout tags/2.1.0
3)  composer install

...at this point I get the follow error...

`Generating autoload files
 Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
 Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "AuditLogSubscriber" from namespace "Mautic\CoreBundle\EventListener".
Did you forget a "use" statement for another namespace? in /srv/http/site_mautic/public_html/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php:152
Stack trace:
#0 /srv/http/site_mautic/public_html/app/cache/prod/appProdProjectContainer.php(1241): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->addSubscriberService('mautic.core.aud...', 'Mautic\\CoreBund...')
#1 /srv/http/site_mautic/public_html/app/bootstrap.php.cache(2199): appProdProjectContainer->getEventDispatcherService()
#2 /srv/http/site_mautic/public_html/vendor/symfony/framework-bundle/Console/Application.php(80): Symfony\Component\DependencyInjection\Container->get('event_dispatche...')
#3 /srv/http/site_mautic/public_html/vendor/symfony/console/Application.php(123): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\I in /srv/http/site_mautic/public_html/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php on line 152
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

                                                                                                                                                                             
  [RuntimeException]                                                                                                                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                                  
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "AuditLogSubscriber" from namespace "Mautic\CoreBundle\Event  
  Listener".                                                                                                                                                                 
  Did you forget a "use" statement for another namespace? in /srv/http/site_mautic/public_html/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php:152         
  Stack trace:                                                                                                                                                               
  #0 /srv/http/site_mautic/public_html/app/cache/prod/appProdProjectContainer.php(1241): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->addSubscriberServ  
  ice('mautic.core.aud...', 'Mautic\\CoreBund...')                                                                                                                           
  #1 /srv/http/site_mautic/public_html/app/bootstrap.php.cache(2199): appProdProjectContainer->getEventDispatcherService()                                                   
  #2 /srv/http/site_mautic/public_html/vendor/symfony/framework-bundle/Console/Application.php(80): Symfony\Component\DependencyInjection\Container->get('event_dispatche..  
  .')                                                                                                                                                                        
  #3 /srv/http/site_mautic/public_html/vendor/symfony/console/Application.php(123): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Cons  
  ole\I in /srv/http/site_mautic/public_html/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php on line 152                                                   
`

**Comment by Arjoni** [comment]
You can upgrade to 2.1.1 directly. Here is a good article about it: http://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful 

You can also upgrade from terminal with php upgrade.php at the root folder of application.

**Comment by escopecz** [comment]
This seems like a cache error. Try to run `rm -rf app/cache.*` in the Mautic root directory to regenerate it. Let us know if your issue is solved.

**Comment by kevingarman** [comment]
@Arjoni ...Going to 2.1.0 and 2.1.1 both give the same error.  I looked over John's blog post but so far haven't had success.

@escopecz ...I have tried deleting the cache but still get the same error when trying to do the composer install.

**Comment by escopecz** [comment]
@kevingarman do you get the same error when using the production version? https://www.mautic.org/download/

**Comment by kevingarman** [comment]
@escopecz ...I'll give it a try.  Should I just overlay my current install or wipe out the Mautic folder contents first?

**Comment by escopecz** [comment]
would it be too much trouble to try it in a folder called "mautic2"?

**Comment by kevingarman** [comment]
fair enough...I'll try it later today.

**Comment by kevingarman** [comment]
So...I created a new public folder and installed from the zip and repeated with an install from a git clone.  In both cases the installer webpage was displayed when I hit the new site with a browser.

I guess that means something is messed up in my current install?  If so, I'll just reinstall, no big deal I guess.  One question though...when I go through the installer, will it create new tables or create new ones?  ...how do I preserver my data?

**Comment by escopecz** [comment]
I'd install a fresh Mautic, then edited the app/config/local.php file and updated the database credentials to the old database. Then you'll have to clear the cache to apply the changes in the local.php file.

**Comment by kevingarman** [comment]
Will do...thanks for your help!

**Comment by kevingarman** [comment]
Sorry, it's been a month...

I finally got back to this and did the fresh install with local.php copied from the old install.  Everything seems to work.

I assume I don't need to clear cache using this method, but I tried it just to be safe.  After clearing cache I get the following error:

```

2016/10/14 11:51:32 [error] 20637#20637: *12792 FastCGI sent in stderr: "PHP message: PDOException: SQLSTATE[HY000] [2002] Connection refused in /srv/http/site_mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /srv/http/site_mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=loca...', 'mauticuser', 'fakepassword', Array)
#1 /srv/http/site_mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(41): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=loca...', 'mauticuser', 'fakepassword', Array)
#2 /srv/http/site_mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'mauticuser', 'fakepassword', Array)
#3 /srv/http/site_mautic/public_html/app/AppKernel.php(117): Doctrine\DBAL\Connection->connect()
#4 /srv/http/site_mautic/public_html/app/middlewares/CORSMiddleware.php(96): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, tr" while reading response header from upstream, client: 69.25.204.186, server: marketing.mysite.com, request: "GET /mtc.js HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm-site_mautic.sock:", host: "marketing.mysite.com", referrer: "https://www.mysite.com/"

```

I rolled back my VM and did the upgrade again without clearing the cache and all seems well, but it seems like clearing the cache shouldn't break anything...I tried it twice with the same result.

**Comment by kevingarman** [comment]
Ok, actually it's a mixed bag of pages that work and don't work, I have no idea what's going on.  I'm going to roll back and try again later.

**Comment by kevingarman** [comment]
I can't figure it out...I just blew everything away and started over...fortunately we've only be testing it so far so we don't really have data to loose.
