### ISSUE TITLE
Tags selector drop-down are not wholly visible -- they are off-screen

### ISSUE THREAD

**Issue by yyil** [mautic/mautic#2496]
Enhancement request:

## Description:
When adding tags to a contact, the dropdown selector list spans off the visible area of the page. This is due to the form field being at the bottom of the page.

Perhaps relocate the tags field or add some padding to the bottom of the page?

Screenshot:
http://i67.tinypic.com/64ms6v.jpg

**Comment by npracht** [comment]
Hello,

Must be solves by https://github.com/mautic/mautic/pull/2489
Please have a test by installing this PR.

N.
