### ISSUE TITLE
Leaked contenteditable into e-mails when manually send to contact

### ISSUE THREAD

**Issue by jkuchar** [mautic/mautic#2501]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | y |
| Feature request? | n |
| Enhancement? | n |
## Description:

When e-mail is sent manually to contact there are content editable attributes leaked in e-mail. Thunderbird respects this attribute, e-mail then is editable in preview.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.6 |
### Steps to reproduce:
1. Create standard e-mail from any template.
2. Send it manually to any lead you have access to mailbox.
3. Open it in Thunderbird and you will be able to edit content of e-mail in preview.
### Log errors:

No errors.

**Comment by dakur** [comment]
Just to say - the main problem from user side is that the e-mail content is not scrollable then in Thunderbird.

**Comment by ddoonie** [comment]
This affects both iOS and Android mobile platforms as well as Mail.app when sending manual emails.

**Comment by dakur** [comment]
Is the fix planned for this issue, please? It should not be much work in my opinion and it would help our productions. Thanks for information.

**Comment by dakur** [comment]
@escopecz What was the purpose of this? https://github.com/mautic/mautic/commit/016b2e7e0a42340ca3d2ba3692f8c646eef9cb0d
Actually that code is responsible for this bug. I would fix it, but I don't know, what was its intention...

**Comment by escopecz** [comment]
@dakur Froala adds some styles to the content it edits. For example a border to all tables. We use table-based layouts mostly because it's still a standard for email layouts, so adding a border to the table breaks the layout style. The code in the linked commit removes the styles that Froala adds on save.

**Comment by dakur** [comment]
Oh, I found it here. https://github.com/froala/wysiwyg-editor/issues/1372

The main problem is that when you do:
```js
var emailHtml = mQuery('.fr-iframe').contents();
// ...
textarea.val(emailHtml.find('html').get(0).outerHTML);
```
then everything from Froala including `<body contenteditable>` is inserted to textarea and then sent. It is needed to do all the stuff on output from `mQuery(this).find('#lead_quickemail_body').froalaEditor('html.get', true)`, but the problem is that it's a string, not DOM list.

**Comment by escopecz** [comment]
I remember I played with it a lot that time. I think it also returns only the content of `<body/>` and we used Froala to edit the whole HTML document so we needed the `<head/>` tag too. We still use it for example in sending email directly to a contact so it should still contain the whole HTML document.

Wouldn't help to simply remove all `contenteditable` attributes from the HTML tags in the method you pointed out?

**Comment by dakur** [comment]
@escopecz I tried, but unfortunatelly that's not enough. The `contenteditable` is on `body` tag and there is `overflow: hidden` as well. Rewriting it with `emailHtml.find('body').css('overflow', 'initial !important')` does not work and doing some magic above CSS is not what you want especially when the `body`'s CSS can be user defined.

**Comment by dakur** [comment]
Sorry, I was wrong, `emailHtml.find('body').css('overflow', 'initial')` works. It's hack of hack. Not sure if it is worthy of pull request...

**Comment by escopecz** [comment]
Yes, the clearing of Froala styles and other attributes is hacky, but it's the only way how to make it work for Mautic needs. I'm surprised that Froala doesn't have some method to clean the content from its own mess. PR it, please. And also remove the contenteditable attr if possible.

**Comment by dakur** [comment]
Ok, I'll do it in the beginning of next week.

**Comment by dakur** [comment]
@escopecz I've made a PR.

**Comment by LucasFarley** [comment]
I applied the changes in my test environment, but is not working.

**Comment by dakur** [comment]
Have you tried to clear the cache?
`php app/console cache:clear`

**Comment by LucasFarley** [comment]
I performed now.  The content editable has been fixed.
However, the scroll is not working yet.

Follow the body tag generated.
<body class="ui-sortable fr-view" aria-disabled="false" style="margin: 0px; cursor: auto; min-height: 300px;" spellcheck="true" dir="auto">

<img width="1280" alt="html_code" src="https://cloud.githubusercontent.com/assets/22159940/26831802/cd44cb96-4aa3-11e7-8073-1f99a2b8ad7a.png">
<img width="745" alt="email" src="https://cloud.githubusercontent.com/assets/22159940/26831803/cd7efd70-4aa3-11e7-90b9-5e561efc574a.png">

**Comment by jkuchar** [comment]
@LucasFarley please could you check that scrolling issue is resolved for you?

**Comment by LucasFarley** [comment]
@jkuchar, I tested and the problem has been fixed.
