### ISSUE TITLE
New pagehit leads identified as my own lead account without any reason

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2503]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

With the mautic javascript code, i've plenty page_hit from different customers (with different IPs) which lead to be authentified as my own account.

I've never connected on this IPs, i can see in different tables in DB (audit_log, lead_ips_xref, page_hits) that all the actions/hit are merged on my one lead, but a new lead should be created instead.

Where can i investigate (in DB and in code) to see what's going on ?
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |

**Comment by alanhartless** [comment]
Check to make sure you do not have a custom field set as "unique identifier" when it really is not. For example, if "state" is selected as a unique identifier, then everyone from Texas would be merged as a single contact.

**Comment by chandon** [comment]
I don't have any custom field with "unique identifier". I've deleted my one account to stop the problem, not sure it's ok now (i should check if every "log" is really created by me)
