### ISSUE TITLE
New Feature Request: 

### ISSUE THREAD

**Issue by angelsguitar** [mautic/mautic#2506]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes
| Enhancement? | 

## Description:
Include the ability to add a fallback term when using personalized fields. For example, if I use "Hello {contactfield=firstname]" but there's no First Name registered for the contact, I'll be great to have Mautic display a specified generic text like "Hello there". The syntax could be something like {contactfield=firstname,fallback="text to show"}.

**Comment by npracht** [comment]
Hi,

Did you try `{contactfield=firstname}` --> `{contactfield=firstname|default-message}`. I've already used it some time ago.

N.

**Comment by angelsguitar** [comment]
Thanks @npracht . I didn't know about that feature.

Seems it's just what I was looking for. I tested it and it works.

In that case, this feature request could be closed or removed. I'd only suggest that this feature is added to the official documentation (if it's already there, then sorry that I didn't see it).

Thanks.
