### ISSUE TITLE
Campaign actions statistics exceeding 100% and breaking UI

### ISSUE THREAD

**Issue by benznarczyk** [mautic/mautic#2507]
What type of report is this: Bug

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

This is a campaign that runs once per month, each month using a new segment of contacts. There two initial actions: 1. add points and 2. send email. There is a decision branch out of the initial email, Y: add points and N: send a follow up email three days later.

After the initial run of the campaign. I unpublished, changed the segment, then ran the campaign again the next month.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 SaaS |
| PHP version |  |
### Steps to reproduce:
1. Create campaign
2. Add actions
3. Initiate campaign
4. See statistics error (image attachment)
5. Unpublish campaign after finished
6. Change contacts segment
7. Initiate the campaign again next month 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

![image](https://cloud.githubusercontent.com/assets/18532961/18391597/7100020c-767c-11e6-88b9-bafdd7f74d4e.png)

![image](https://cloud.githubusercontent.com/assets/18532961/18392018/2fd9ab14-767e-11e6-9c71-a639a6c3d8dc.png)

**Comment by PatchRanger** [comment]
Fixed by #3039.

**Comment by alanhartless** [comment]
Thanks PatchRanger!
