### ISSUE TITLE
Anonymous Contacts Showing up from Other Web Sites

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#2508]
I have a recent installation of Mautic (v2.1.2-dev). I haven't even tracked any pages yet, but I'm showing anonymous contacts (looks like a Google bot). When I click into the IP's profile page, it shows random URLs of other sites that I'm hosting on this same server. How is this possible? Any idea on how I can prevent this?

Thanks

**Comment by nickian** [comment]
It looks like the bot is trying to access https versions of my other sites (which don't exist), and Apache is redirecting them to Mautic (for some reason Apache makes this the fallback folder to land in). Since the URL doesn't match my Mautic config, it just lands on the "Site Offline" page.

Does anyone know if I can prevent this with a setting in Apache or in a robots.txt file, or anything else?

**Comment by nickian** [comment]
Sorry, spoke to soon here. This was just a quick fix in Apache. Anyone else having this problem, see this thread: http://stackoverflow.com/questions/39420098/apache-redirecting-undefined-domains-and-default-site/

**Comment by nickwild-999** [comment]
Hi, I am having this issue too, but there is no sites-enabled folder (I am using the bitnami install of mautic on ec2) should I just create one?

**Comment by nickian** [comment]
Sorry, I have no clue how Bitnami works. Maybe someone else will know.
