### ISSUE TITLE
Stripe Integration

### ISSUE THREAD

**Issue by eirua** [mautic/mautic#2509]
Hey guys just wondering if someone's already integrated stripe to accept payment through mautic forms? Is this even practical?

**Comment by karlmonson** [comment]
+1

**Comment by jdecampos** [comment]
+1

**Comment by stepcellwolf** [comment]
+1

**Comment by RCheesley** [comment]
It's already implemented via Chimpino: https://crafting.email/plugin/stripe-integration-for-mautic/
