### ISSUE TITLE
[Regression] Tag import does not work

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2513]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When importing contacts, it's possible to specify "tags" for the contact list. Tags are not added anymore when importing...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1

### Steps to reproduce:
1. Create a CSV file for contact
2. Import it, and on the import form, add a "TAG"
3. Finalize import
4. Check new created contact (or updated contacts) : no TAG are included

**Comment by reachadam** [comment]
Wow, crazy we discovered the on the same day essentially! It's pretty major because it is potential data corruption / destruction.

**Comment by chandon** [comment]
Yes it is !

**Comment by alanhartless** [comment]
Merged into 2.2
