### ISSUE TITLE
Testing to avoid regression

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2514]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | Y |
| Enhancement? |  |
## Description:

I'm using mautic for a couple of month now. Each new release comes with a lot of regression. Mautic should consider writing tests to avoid releasing versions with regression.
Tests are a real investment, but it makes a product (more) reliable.

**Comment by chandon** [comment]
@escopecz it's not a feature request, it's a part of development process...
i think i'll not download 2.2 version and later, because there is a high potentiel risk of regression (that's what happends when i went from 2.0 to 2.1)

**Comment by escopecz** [comment]
I marked it as a feature because you marked it as a feature request in the table above. I think you'll be happy with the work @dongilbert is working on right now ;) And I agree that unit tests or software stability are not a feature. It is must have. But we don't have such label.

**Comment by chandon** [comment]
Good to know that's @dongilbert is working on it.

**Comment by npracht** [comment]
@escopecz i think that issue does not bring anything more now knowing that you're working on with tests on every places of the app ?

**Comment by escopecz** [comment]
We are still at the beginning. Please also note (as one of the biggest contributor) that all new features and bug fixes should contain unit tests covering the new and updated code.
