### ISSUE TITLE
campaign rate and timerange limitation for "actions"

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2518]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | Y |
| Enhancement? |  |
## Description:

I've 10000 emails to send. In case of conversion, i'll have to call my lead. It's not possible for me to call everybody at the same time. So it would be great to specify additional parameter in "actions" (like "send email") :
- max action count / period (Eg: 100 / hour or 1000/day) : if the max has been reached, no more email is generated until the next period... (next sliding hour or next sliding day). This is also good to avoid spam detection
- date/timerange of action : i don't want my emails to be send on sunday, or at midnight... so we could specify date/timerange in each action :

![image](https://cloud.githubusercontent.com/assets/4522557/18449720/9f974164-7930-11e6-8fad-b0cb57df4ec7.png)

**Comment by ninjoan** [comment]
+
