### ISSUE TITLE
Contacts tags disappear when importing, and contact already exists

### ISSUE THREAD

**Issue by reachadam** [mautic/mautic#2519]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? | 

## Description:
Contacts with existing tags, after importing contacts where the contact already exists in Mautic, tags disappear. May just be a visual problem, because I have a segment based on tags, and they are unaffected. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 5.6.22

### Steps to reproduce:
1. Create a contact and give contact a tag
2. Import from csv with matching email address to prior created contact
3. View contact to see prior tags have disappeared
 
### Log errors: 
No errors

**Comment by chandon** [comment]
perhaps linked to #2513

**Comment by reachadam** [comment]
It's pretty major because it involves data destruction.
