### ISSUE TITLE
A/B tests do not send.

### ISSUE THREAD

**Issue by patmifsud** [mautic/mautic#2520]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✓
| Feature request? | 
| Enhancement? | 

## Description:
We're having some issues sending out AB tests at the moment. Using a typical batch amount (100, 50, 30 etc) the emails just fail to send, the progress bar sitting at 0/700 indefinitely. Using something really small such as 5 or 3 the emails trickle out and then fail, with only the first variant being sent out. We have paused our emails until this is resolved. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.0
| PHP version | 5.6.25

### Steps to reproduce:
1. Make an AB test **with 3 options**, weight can vary. Unable to test 2 way at this time unfortunatly. 
2. Select a segment with >100 leads
3. Send without a schedule if possible. If your version of mautic requires a schedule/ is on Allyde it appears to work correctly, although the 'A/B test stats' button appears to be wrong. 
 
### Log errors: 

The following PHP error was noticed:
[2016-09-09 01:08:07] mautic.ERROR: PHP Error: Argument 1 passed to Mautic\EmailBundle\Helper\MailHelper::setEmail() must be an instance of Mautic\EmailBundle\Entity\Email, null given, called in /var/www/html/app/bundles/EmailBundle/Model/EmailModel.php on line 1242 and defined - in file /var/www/html/app/bundles/EmailBundle/Helper/MailHelper.php - at line 1242 [] []

**Comment by alanhartless** [comment]
This should have been fixed in 2.1.1. If it persists after upgrading, let us know.
