### ISSUE TITLE
Enhancement - Stages Interface

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#2526]
| Enhancement? | 
## Description:

Stages at the moment is unusable for sales team to preview. Interface need simple revamp to show the stages withe easy switch between them and have an easy view at where the customer is. 

something similar to this would look great,. 
![image](https://cloud.githubusercontent.com/assets/22168697/18468119/6f9c5b74-799a-11e6-8660-08424ba37472.png)

**Comment by luizeof** [comment]
+1
