### ISSUE TITLE
Configuration takes a long time to load and server reports errors

### ISSUE THREAD

**Issue by LEAP-nishit** [mautic/mautic#2532]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | x |
| Feature request? |  |
| Enhancement? |  |
## Description:

When an user selects the Configuration page Mautic take a very long time to load (abut 5-6 min). The second the page loads errors are generated in the server logs.

I have tried clearing the cache using the console command including removing the prod directory altogether. 
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 7.0.8 |
### Steps to reproduce:
1. Follow Login > Settings > Configuration
2. Wait for 5-10min. 
### Log errors:

[Wed Sep 14 00:03:55.593952 2016] [:error] [pid 5584] [client x.x.x.x:57900] PHP Fatal error:  Uncaught TypeError: Argument 5 passed to Symfony\Component\Debug\ErrorHandler::handleError() must be of the type array, null given in /srv/mautic/html/app/cache/prod/classes.php:2313\nStack trace:\n#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError('notice', 'Unknown: [CLOSE...', 'Unknown', 0, NULL)\n#1 /srv/mautic/html/app/bundles/CoreBundle/EventListener/ErrorHandlingListener.php(123): call_user_func(Array, 'notice', 'Unknown: [CLOSE...', 'Unknown', 0, NULL)\n#2 [internal function]: Mautic\CoreBundle\EventListener\ErrorHandlingListener->handleError('notice', 'Unknown: [CLOSE...', 'Unknown', 0, NULL)\n#3 {main}\n  thrown in /srv/mautic/html/app/cache/prod/classes.php on line 2313, referer: https://mautic/s/categories
[Wed Sep 14 00:03:56.214511 2016] [:error] [pid 5584] [client x.x.x.x:57900] PHP Notice:  Undefined variable: _GET in /srv/mautic/html/app/bootstrap.php.cache on line 503
[Wed Sep 14 00:03:56.214643 2016] [:error] [pid 5584] [client x.x.x.x:57900] PHP Notice:  Undefined variable: _POST in /srv/mautic/html/app/bootstrap.php.cache on line 503
[Wed Sep 14 00:03:56.214696 2016] [:error] [pid 5584] [client x.x.x.x:57900] PHP Notice:  Undefined variable: _COOKIE in /srv/mautic/html/app/bootstrap.php.cache on line 503
[Wed Sep 14 00:03:56.214731 2016] [:error] [pid 5584] [client x.x.x.x:57900] PHP Notice:  Undefined variable: _FILES in /srv/mautic/html/app/bootstrap.php.cache on line 503
[Wed Sep 14 00:03:56.214802 2016] [:error] [pid 5584] [client x.x.x.x:57900] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\HttpFoundation\Request::createRequestFromFactory() must be of the type array, null given, called in /srv/mautic/html/app/bootstrap.php.cache on line 503 and defined in /srv/mautic/html/app/bootstrap.php.cache:1305\nStack trace:\n#0 /srv/mautic/html/app/bootstrap.php.cache(503): Symfony\Component\HttpFoundation\Request::createRequestFromFactory(NULL, NULL, Array, NULL, NULL, Array)\n#1 /srv/mautic/html/vendor/stack/run/src/Stack/run.php(11): Symfony\Component\HttpFoundation\Request::createFromGlobals()\n#2 /srv/mautic/html/index.php(30): Stack\run(Object(Stack\StackedHttpKernel))\n#3 {main}\n  thrown in /srv/mautic/html/app/bootstrap.php.cache on line 1305

**Comment by escopecz** [comment]
Closing this issue in favour of https://github.com/mautic/mautic/issues/3390
