### ISSUE TITLE
Sparkpost  - Email Setup

### ISSUE THREAD

**Issue by versadial** [mautic/mautic#2535]
Bug Report?

## Description:
Placing Sparkpost API KEY into  Mail Send Settings > Service to send mail through > SELECT SPARKPOST > place into API KEY and then > TEST CONNECTION button

I get this error:
Cannot create instance of \SparkPost\SparkPost while API key is NULL Log data: !! Cannot create instance of \SparkPost\SparkPost while API key is NULL (code: 0)
!! Cannot create instance of \SparkPost\SparkPost while API key is NULL (code: 0)

## If a bug:
Mautic verison 2.1.1
PHP 5.6.23

### Steps to reproduce:
Placing Sparkpost API KEY into  Mail Send Settings > Service to send mail through > SELECT SPARKPOST > paste in API KEY  > TEST CONNECTION button
 
### Log errors: 
Do not think this is related, only error in log file reported:
[2016-09-13 10:06:54] mautic.ERROR: Warning: Invalid argument supplied for foreach() - in file 
/mautic/app/bundles/PageBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 76 [] []

**Comment by nixon1333** [comment]
+1

**Comment by nixon1333** [comment]
Same problem is happening for me too.

**Comment by germanotm** [comment]
Me too. Exactly the same error.

**Comment by pvasilion** [comment]
Unable to replicate the issue, any more details that you guys can pass along?

**Environment:**
Mautic 2.2.0 with PHP 7.0.10 or PHP 5.6.25
Free Sparkpost Account
Local MAMP Environment

**Steps taken in attempt to replicate:**

1. Place Sparkpost API Key into Settings
2. TEST CONNECTION -> Results in Success Status
3. SEND TEST EMAIL -> Results in Success Status and Email Receipt

**Comment by nixon1333** [comment]
@pvasilion I did not try this on local environment. I tried on VPS( Centos ) with same configurations of yours.
And it did not worked. But If I just save the api key and send email a contact it works. I guess test email module is not working. But API based email is working when I tried to send a test email to a contact.
