### ISSUE TITLE
Unable to send tweets from a campaign

### ISSUE THREAD

**Issue by imransayyed** [mautic/mautic#2543]
## Description:
Hello,

Need help in sending tweets out from Mautic.
I have created a campaign from which i am sending a welcome email after the email is sent and its opened by the recipient. I am trying to send a thanks tweet to the contacts but tweets are not going out from mautic.

Thanks,

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1
| PHP version | 

### Steps to reproduce:
1. Create a campaign
2. Select tweet contact

**Comment by imransayyed** [comment]
Anyone ?

**Comment by escopecz** [comment]
Please provide as many information as you can about your twitter plugion configuration.

**Comment by fixmyinfo** [comment]
Similar issue here - I see no errors, but I see no tweets. Very simple test campaign - if a mention, then tweet. Plugin shows no errors. But - no tweets either, for positives. You can mention @fixmyinfo or #fixmyinfo and see - it will likely not work. It will add you as a contact, but not tweet to you.

**Comment by fixmyinfo** [comment]
Same issue here - no errors, and it even says it is tweeting - but - not tweets.

**Comment by fixmyinfo** [comment]
Anything to look at here? Any info I can add?
