### ISSUE TITLE
Store PHP session in DB

### ISSUE THREAD

**Issue by grzana12** [mautic/mautic#2546]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
I suggest to move storing PHP session to DB. I have problem to run it using Docker to be persistant loggedin.

**Comment by escopecz** [comment]
Actually, I made some searching and found this comment:

> handler_id set to null will use default session handler from php.ini

https://github.com/mautic/mautic/blob/6a87d789349ee6cc03ca9d90019d8e1f7882b157/app/config/config.php#L186

Mautic is built on Symfony2 framework so you can search for more details about how it handles session in its documentation.

Try it out. If it won't work, let us know and we'll re-open.

**Comment by rusuandreirobert** [comment]
I'm not sure if I should open a separate ticket for this same issue.

Is it okay to modify the config.php file, considering all data is stored in local.php, in case of an update from mautic, what are the chances you'll modify the config.php file.

I've found out that the latest Mautic version uses Symfony 2.8, and the related document that explains on setting this up is here : http://symfony.com/doc/2.8/doctrine/pdo_session_storage.html

Mautic will not work on my server, probably because of the way sessions are stored within the files, this is an issue from Symfony I suppose, but I don't want to "fix" it and then see that my code dissapeared from an update.

**Comment by rusuandreirobert** [comment]
Well, I've eventually switched to file stored sessions, I can login and view some pages, but anything else is unavailable, I'm affraid Mautic won't work with other session storage types, most likely.

I've already spent 2 hours trying to configure it, sessions are stored, front page is working, but all the other pages except Contacts & Custom Fields will not work, I can add contacts and manage them, same goes for custom fields, for a while I tought this is an Middleware issue, were the pages redirect back to the main page, in my case the dashboard.

Visiting for example : 
s/contacts/new - works
s/campaigns will redirect me to the login page.

Being logged in an clicking Campaigns in the left menu results in a chain of 3 Ajax requests, 1 to that page, 1 to the login page, and 1 to the dashboard page and displaying it again, but it's not like a refresh style request, like when pressing the left menu.

I hope someone that had this issue can shed some light, possibly the person that initially opened this issue, not sure how he handled the issue.

**Comment by groovenectar** [comment]
Did anyone make any headway on using database session storage?

Currently struggling with this as well...

Tried plugging in a custom session save handler in config.php to see if it would get picked up as default, but no luck there...

And I can't find where it's specifying which Symfony session handler to use (which would be files presumably, and maybe it can be changed to database)

**Comment by groovenectar** [comment]
Database session storage becomes helpful in load balanced situations where your filesystems might not end up with the same session data for AJAX calls...

**Comment by heathdutton** [comment]
@groovenectar we use Redis for all our session storage across nodes and it works splendidly. No need to change/configure the Mautic codebase at all. This scales better than using the DB in a load-balanced situation. Our config is public in the mautic-eb repo if helpful to you.

**Comment by groovenectar** [comment]
Thanks for the resource @heathdutton! We'll have to look into that...

I think I might have gotten working with PDO sessions too, btw...

By changing this line in `config.php`:

`'handler_id'    => null,`

to

`'handler_id'    => 'session.handler.pdo',`

Then after that array, adding this:

```
$container->register('session.handler.pdo', \Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler::class)
    ->setArguments(array(
        'mysql:dbname=[DBNAME]',
        array('db_table' => '[DBTABLE]', 'db_username' => '[USERNAME]', 'db_password' => '[PASSWORD]'),
    ));
```
