### ISSUE TITLE
Form report exports with incorrect times in all export formats

### ISSUE THREAD

**Issue by justinroffmarsh** [mautic/mautic#2553]
What type of report is this:
| Bug report? | 

## Description:
Form submission times display correctly in the report generated by clicking the submission count in the form table view. (e.g. "September 9, 2016 4:41 am UTC")

However when this report is exported to any format, the time exports as follows: "9/9/2016 04:09:53" (This is the submission time from the same record above.)

Furthermore ALL TIMES export as follows "x/x/xxxx 04:09:xx". In other words, the hour and minutes for all records in the report is "4:09"

Mautic version: 2.1.1 

### Steps to reproduce:
Described above

**Comment by escopecz** [comment]
Do you think it might be related to this?: https://github.com/mautic/mautic/pull/2397

**Comment by justinroffmarsh** [comment]
I don't think so.

All times export with "4:09" in place of correct time.

Justin
