### ISSUE TITLE
Dolibarr plugin or integration

### ISSUE THREAD

**Issue by Getron** [mautic/mautic#2554]
| Feature request? | 
| Enhancement? | 
## Description:

Hi i just searched about if it is possible to connect the Mautic with Dolibarr (www.dolibarr.org)

Dolibarr it is a great Open Source ERP & CRM, and has a lot of features. But, with an integration with Mautic, it will be great.

Thanks in advance, and hope, someone of dev would make this possible, it will be a great duo for having this to on the list of plugins.

**Comment by maurers** [comment]
I will love to have this integration

**Comment by vinding22** [comment]
i agree  .. this would be a awsome addtion to be able to use the awsome pproduct of Mautic in conjunction with Dolibarr !

**Comment by dolimik** [comment]
I will pray for this integration!!! Please develop this one, Mautic will win thousands of new members suddenly.. Thanks

**Comment by vinding22** [comment]
Any news on this ?  .. how can we make this happen ?

**Comment by gschratzer** [comment]
In case somewho is still interested in this topic, i did a interface for that for me as dolibarr module. Only it is not ready to share it as module in dolistore today. But I'm happy to discuss about it and the functions, maybe it is already that what your are looking for?!

**Comment by RCheesley** [comment]
Hi there! It would be best to post about this at https://forum.mautic.org - folks are more likely to find it there!
