### ISSUE TITLE
All emails are public?

### ISSUE THREAD

**Issue by amherdt** [mautic/mautic#2555]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | Y

## Description:
I can get all the emails that I sent **without** being authenticated. In addition, they may be indexed by google.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 7.0.1

### Steps to reproduce:
1. Go to contacts and click on one of them.
2. From the drop-down menu top right, select Send Mail
3. Come on, send an email.
4. Select the email in the table. Example: Custom Email: test
5. Go to private chrome windows and paste the url of the email.
6. No login required... Is public!

URL Example: https://example.com/email/view/57de7d2j421d5

=O

**Comment by luizeof** [comment]
yes all sent e-mails are public, this is used on "View on Web" links with the {webview_text} shortcode. You can disable google indexing on robots.txt

**Comment by amherdt** [comment]
Hi friend!
There is some reason to be public? 
A hacker first look is the robot.txt file.
There any way that private?

Tanks!

**Comment by escopecz** [comment]
If they weren't public, the "View the email in your browser" option would not work, right?
