### ISSUE TITLE
ecommerce tracking for actions after clicking an link?

### ISSUE THREAD

**Issue by mmmichael** [mautic/mautic#2557]
What type of report is this:

| Q  | A
| ---| ---
| Feature request? | Y

## Description:
I would like to have some kind of ecommerce tracking, to assign transactions to users. Is there currently a way to track this informations? Or is there an workaround using the api? Or could I use the Campaign-Logik to set an target Finish page?

**Comment by escopecz** [comment]
This seems like variation of https://github.com/mautic/mautic/issues/18

A workaround would be to use Mautic forms to track actions. This article should get you going: https://medium.com/@jan_linhart/the-simplest-way-how-to-submit-a-form-data-to-mautic-1454d3afd005
