### ISSUE TITLE
Show count unsubscribes and bounces in a segment 

### ISSUE THREAD

**Issue by geospatialmedia** [mautic/mautic#2568]
This Feature request to show count of unsubscribes and bounces in a segment, if some one goes into the segment.

The real problem is looking at the number of contacts in a segment, one does not get the true picture of how many active contacts are there in that segment. One only gets to know if a broadcast mail is scheduled, when the actual number of contacts to which mail is sent (removing unsubscribes and bounces.)

So, if this feature is included, the actual reason on the less number of emails sent will be know.

Here is a view of that:

Segment shows  2523 contacts
<img width="1042" alt="segment with 2523 contacts" src="https://cloud.githubusercontent.com/assets/15128190/18668144/6488b3a6-7f51-11e6-8c15-34774f0c5405.png">

The mail is however sent only to 1324 contacts
<img width="1030" alt="mails sent to 1324 contacts only" src="https://cloud.githubusercontent.com/assets/15128190/18668151/7663bea4-7f51-11e6-83f9-41c4392bf3f7.png">

So, its a guessing game currently on why the number of emails are less, how many are unsubscribed, how many are bounced.

**Comment by amagdy3** [comment]
I second that, sendy.co had a smart interface there. mautic is more advanced and I think it's a matter of time to have this feature and more. I would also add a request for more specific info in the Email view itself, I want to know who clicked on which link .etc

**Comment by zenzozen** [comment]
+1
