### ISSUE TITLE
Site is offline after applying PR, non-existent parameter mautic_rememberme.key

### ISSUE THREAD

**Issue by amagdy3** [mautic/mautic#2570]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

I modified some PHP files with PRs that caused errors with matuic. I restored the original / backup files and surprisingly, I got the site offline with the below error

[20-Sep-2016 15:17:31 UTC] exception 'Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException' with message 'You have requested a non-existent parameter "mautic.rememberme_key".' in /home/egyprene/public_html/mautic/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:84
Stack trace:
#0 /home/egyprene/public_html/mautic/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php(200): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('mautic.remember...')
#1 /home/egyprene/public_html/mautic/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php(171): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveString('%mautic.remembe...', Array)
#2 /home/egyprene/public_html/mautic/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php(161): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue('%mautic.remembe...', Array)
#3 /home/egyprene/public_html/mautic/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php(161): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->resolveValue(Array, Array)

Any advice on restoring mautic?

**Comment by escopecz** [comment]
Did you clear the Mautic cache?

**Comment by amagdy3** [comment]
Yes, I did.

**Comment by escopecz** [comment]
Hmm, then there is some code you didn't restore I guess. You can backup your Mautic, download fresh Mautic zip file, unzip it on your server, copy the app/config/local.php into it, clear the cache. You'll be sure the files are not corrupted. Don't forget to move also your images, assets, themes, plugins and whatever else you were using.

I'll close this issue since it's not a Mautic bug.

**Comment by amagdy3** [comment]
Thanks. I uploaded a fresh copy of mautic and uncompressed it and the site was recovered with data. What is the recommended policy for working out pull requests to avoid the site going offline again?

**Comment by escopecz** [comment]
The best would be if you could have a separate Mautic instance for testing and using Git for applying the PRs. Short tutorial is here: https://github.com/mautic/mautic#how-to-test-a-pull-request
