### ISSUE TITLE
Incorrect Fields mapped in emails

### ISSUE THREAD

**Issue by siparker** [mautic/mautic#2571]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

I have a single additional custom field called live url which i have under the Social part of a contacts details

I setup an email which said 

//////////////////////////
Hi we have your company - {contactfield=company} listed on our website ‍ 

Your listing is Live at {contactfield=listingurl}‍ 
//////////////////////////////////////

And for some unkown reason it has got this wrong. it has mixed up the cmpany and the listing url so 1800 emails have gone out with the wrong information in....................................................
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.4.45 |
### Steps to reproduce:
1. import users
2. send them an email with fields from their contact info
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by siparker** [comment]
anyone have any idea how this might have happened?

The data is all fine in the contacts themselves. its just when sendign an email it somehow messes this up.

Im wondering how that could possibly have happened. It finds the email correctly and it gets the name of the company but then the last field it has to get it grabs some alternative contacts info and sends that instead???

There is no rhyme or reason to the other contacts either its seems to eb totally random.

**Comment by siparker** [comment]
Has anyone else seent his behaviour ever or is it just me?

**Comment by siparker** [comment]
This only occurs when using a segment email. 
a email sent directly to a segment picks up a (seemingly random from my poitn of view) url from one of the ocntacts and uses this trackign code within all emails.

So even if there are 3 contacts with different url based custom fields it will send the email to all contacts with the first value it finds and makes a tracking url from.

Versus a campaign email which seems to correctly send the contacts custom field value to the contact.

**Comment by mqueme** [comment]
Can you please verify that this is happening in version 2.7.0  I have tried to replicate this issue on this version and the fields are mapping correctly.

**Comment by siparker** [comment]
Hi, I have just tested this again and the issue is still present.
Steps to replicate exactly.
Create a segment and add 3 or 4 users into it. change their email address to be emaisl you recieve.
add at least one field in the users profiles that is a url and is unique to that user
Create a new segment email.
include this field in the email
Send
check the recieved email all will ahve the field url value from a single contact not their own
