### ISSUE TITLE
Calendar Events Visible to All Users Regardless of Permission Settings

### ISSUE THREAD

**Issue by Kyle-Foley** [mautic/mautic#2577]
What type of report is this:

| Bug report | 
## Description:

Calendar events are visible to all users regardless of permission settings. If a permissioned user attempts to click through a protected Calendar event, they receive the 403 forbidden message. This shows us that the system correctly forbids these users from accessing the content _directly_, however it still remains publicly visible through the purple Calendar event previews.  

Enough information is visible from the event preview to be harmful if someone unintended views it.
## If a bug:

| Mautic version | v2.1.1
| PHP version | 5.6.21
### Steps to reproduce:
1. Create new user.
2. Assign user a role with no permissions.
3. Perform some action on a Mautic contact that results in the creation of a Calendar event.
4. View the calendar using the user account with no permissions.
### Log errors:

None.

**Comment by websmartit** [comment]
Hi

This issue still seems to be occurring on mautic v3.0.2

I have tested this with a fresh install.
