### ISSUE TITLE
Global Category to put all Assets, Pages, Emails, ... into

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#2579]
|Feature Request|

I did a decent amount of issue searching prior to posting, so apologies if this is a duplicate. 

One thing that I would love to see in Mautic is some sort of hierarchical folder structure. If you think about a marketing campaign (say, an eBook for example), there are multiple assets at play such as emails, landing pages, segments, campaigns, etc. Usually one would be bouncing back and forth between all of these items that pertain to the campaign in order to get dialed in before launching. In the current UI, you have to go to emails > find the ebook emails. Then click over to landing pages > find the eBook landing pages...etc etc. 

It would be nice to have a folder structure to see all Mautic assets that pertain to a particular marketing campaign all in one place. I know you can categorize items but from what I can tell, you can only filter tags from within the section you're in (i.e. emails); you cannot see **all** assets with a given category. Plus, that method would seem unscalable if you have categories for every single asset. 

Cheers!

**Comment by Kyle-Foley** [comment]
You can (sort of) accomplish this now by assigning categories to your assets, then performing a global search by category.

Example:

category:q1campaign

**Comment by ronnieduke** [comment]
@Kyle-Foley that's a good point; I didn't realize you could do that. However I think the point about scalability still stands having to use a category for each marketing campaign (eBook 1, eBook 2, whitepaper 1, etc).

**Comment by escopecz** [comment]
Implemented in 2.3

**Comment by ronnieduke** [comment]
Hey guys - wanted to give my initial feedback: I still think there is a need for a folder structure in addition to global categories. To me, categories are more like tags to identify content _type_ (i.e. 'Whitepaper'), not necessarily the individual content name (i.e. 'Top 10 reasons you should use Mautic'). I think the global categories is useful when you want to do something like "Show me all assets having to do with whitepapers".

As per my initial post though, I am really just looking for a way to pick a content name like 'Top 10 reasons you should use Mautic' and show me all assets (emails, forms, lists, campaigns, etc) that are related to that content piece. I mean, you _could_ use categories to label each individual content name, but it seems it would not be scalable. Pardot accomplishes this by having a "Folder" view, and then being able to apply assets to a specific folders as they are being created.

Maybe I'm missing something though or am just used to using MA in a different way than most :-)

**Comment by escopecz** [comment]
Could you clarify how are folders different than global categories, please?

**Comment by ronnieduke** [comment]
@escopecz sorry if I was unclear above...basically in my mind, categories would be used to tag content by **content type** where folders would be for **content name**. Here is an example folder structure in Pardot: 
![pardot_lover_level_folders](https://cloud.githubusercontent.com/assets/742579/20853750/06b28956-b8a3-11e6-861b-5842ed83fbac.png)

It's a matter of content organization...many companies do all kinds of content marketing such as eBooks, whitepapers, webinars, etc. It would be nice to organize by content name such as "Top 10 reasons to use Mautic (whitepaper)", and see all of the forms, landing pages, emails, campaigns etc that were used for that specific content piece. 

With global categories, while you can create and tag multiple assets with the same category, there is no method of "grouping" those assets in the UI. For example, if I add a "Whitepaper" category to a campaign and also to an email, I cannot search for 'Whitepaper' and see all of those assets together.

Hopefully that makes more sense...

**Comment by ronnieduke** [comment]
@escopecz Here is a folder structure in Marketo: 
![housekeep1](https://cloud.githubusercontent.com/assets/742579/20854024/2ed50da8-b8a5-11e6-8530-7ed332fe8f57.png)

Like I said, it really comes down to visual organization by content type. Right now, if you click on "Emails" for example, you'll see a list of all emails you've ever created. There's not a way to filter by 2015, 2016, tradeshows, blog posts, etc.

**Comment by escopecz** [comment]
Ok, I understand now. So the problem is the missing category filters and reports. I don't think we have to create all new grouping mechanism called folders, lets just use global categories and build the filters and reports and views you need.

**Comment by ronnieduke** [comment]
@escopecz that would technically solve the issue, but as I mentioned in the original post, that may not be the most elegant solution. While you can create content names as global categories, the list of categories would eventually get a bit unwieldy. By having a folder mechanism, that allows users to group their assets in a hierarchical way, which could also be used for archival purposes. For example (as illustrated in the Marketo example above), we are nearly at the end of 2016, a user might want to create a 2017 folder and start putting content for the current year there. Using the global categories, you can see how this might end up a bit chaotic over time:

![image](https://cloud.githubusercontent.com/assets/742579/20907822/87a62982-bb05-11e6-91bf-0940f2ea28c5.png)

Or, say you wanted to clone a landing page for a whitepaper download, and repurpose it for an eBook - If you had a folder structure, you could just clone the landing page to the eBook folder rather than having to go into the categories manager, add a global category for the name of that eBook, then go back to the cloned landing page and switch the category to the new eBook.
