### ISSUE TITLE
Points are decreased instead of increased

### ISSUE THREAD

**Issue by Arjoni** [mautic/mautic#2583]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
I have created one campaign where, if the lead opens the email, points will increase. 
What actually happens in that the points are decreased. This happens only when configured in campaign. When configured in action triggers, the points will increase fine. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 5.6

### Steps to reproduce:
1. Create one campaign where points will increase if lead opens the email.
2. Wait for it to trigger. 

Logs:
[2016-09-22 10:10:41] mautic.WARNING: PHP Warning: Invalid argument supplied for foreach() - in file /var/www/marketing.domain.com/app/bundles/PageBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 76 [] []

**Comment by escopecz** [comment]
I'm not able to replicate. First I tried to test just form submistion - add points. That went well. So I tried to like this:
![mautic-point-test-campaign](https://cloud.githubusercontent.com/assets/1235442/19071810/45fb9c46-8a32-11e6-821c-f32bc2b50a27.png)
And the contact gained 5 points:
![mautic-point-test-contact](https://cloud.githubusercontent.com/assets/1235442/19071821/5396d65e-8a32-11e6-8549-151c92b2d2ba.png)
Please double-check your campaign, test it again and provide more concrete steps to replicate if you'll be able to get the problem again, I'll reopen this issue.

**Comment by Arjoni** [comment]
What i tested was sending email from  segment and then waiting 10 days, then increase the points which were all decreased. I will wait for the new version and if that happens again, i will open another issue with as much possible details as i can. Thanks!
