### ISSUE TITLE
Importing Contacts Freezes

### ISSUE THREAD

**Issue by redcage** [mautic/mautic#2585]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? | No |
| Enhancement? | No |
## Description:

When I import contacts in a csv file (just firstname, lastname, email, company and a tag) it:
1. either doesn't import
2. starts the import and stops half way
3. seems to have completed the import but freezes there

I've cut up my list into 100 record files, still get the problem.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | Cloud mautic.net |
| PHP version |  |
### Steps to reproduce:
1. import csv 
2. match Full > Firstname; Name > Lastname: Company > Company; Email > Email; add bimtech tag
3. start the import
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

Attached is the file - this forum doesn't support csv, so changed it back to xlsx format.
[censored]

**Comment by escopecz** [comment]
Hi, thanks for the report!

I censored your description - removed the xslx file because it contained many real contacts which could get them all to spam lists. I have the file if any of the developers would like to get it for testing, contact me.

But I modified the first 2 contacts like this:
```
firstname,lastname,email,company
Candice,Doe,CandiceG@doe.ca ,4té inc. (formally Doe Lindsay)
Lindsay,Doe,lindsayp@doe.ca ,4té inc. (formally Doe Lindsay)
```
And the import was not successful:
```
(#2) Address in mailbox given [CandiceG@doe.ca ] does not comply with RFC 2822, 3.6.2.
(#3) Warning: explode() expects parameter 2 to be string, array given
```
So we can debug with the CSV snippet I posted above.

**Comment by escopecz** [comment]
When I think about it, the import didn't freeze for me. @redcage could you double check that you imported the CSV file in UTF8 encoding?

**Comment by redcage** [comment]
Hi @escopecz 
I'm not sure what you mean... Here are the steps I took:
1. saved my excel file as CSV (Comma Delimited)
2. then imported it into Mautic
3. mapped the fields

And then get those problems....

**Comment by escopecz** [comment]
@redcage you can set the encoding using Open/Libre office or here is a short tutorial on MS office: https://github.com/mautic/mautic/issues/2121#issuecomment-248617951

**Comment by victorkoopman** [comment]
Hello,

I am experiencing the same problems. 
1. saved my excel file as CSV (Comma Delimited)
2. then imported it into Mautic
3. mapped the fields

The screen keeps on showing "Import is in progress." [see screen capture]

Saved the file as UTF-8 in Libre Office.

What else can it be?

Hope someone comes to the rescue...
![mautic](https://cloud.githubusercontent.com/assets/22594679/19041323/dd552db0-8987-11e6-96d8-f7c9b7447b39.JPG)

**Comment by escopecz** [comment]
Hi! When the _"Saved the file as UTF-8 in Libre Office."_ step happened? It doesn't do much after the import.

Please check the logs (https://mautic.org/docs/en/tips/troubleshooting.html) for error messages.

**Comment by victorkoopman** [comment]
Hi escopecz,

After saving file as UTF-8 I did a new upload...

I have two log messages:
[2016-10-03 14:36:09] mautic.ERROR: Deprecation: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. - in file Unknown - at line 0 [] []

[2016-10-03 14:36:10] mautic.ERROR: Error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 23283 bytes) - in file /home/geenac1q/automation/vendor/symfony/form/ChoiceList/Factory/CachingFactoryDecorator.php - at line 65 [] []

Not sure if I can fix it; should I makes changes to the php files?

**Comment by escopecz** [comment]
Ok, both of these errors are explained in the documentation I linked above.

@redcage how about your errors?

**Comment by escopecz** [comment]
This might be fixed by https://github.com/mautic/mautic/pull/3201 in Mautic 2.6.0. If there will be some other troubles, comment bellow and we'll re-open this issue.

**Comment by orl99** [comment]
Thanks for the info. You can upload more than 100 (in my case 1000 rows) only if you use the libre Office, not excel. 
Best regards and thanks
Orlado Garcia
