### ISSUE TITLE
Call to undefined method FormApiController::getModel()

### ISSUE THREAD

**Issue by michiellucas** [mautic/mautic#2586]
When requesting a form from the mautic api i get the following error
I am using the mautic api connector: https://packagist.org/packages/mautic/api-library

`Call to undefined method Mautic\\FormBundle\\Controller\\Api\\FormApiController::getModel() in /var/web/vd4746/public_html/app/bundles/FormBundle/Controller/Api/FormApiController.php on line 27
`

`$api = new MauticApi();
        $formApi = $api->newApi('forms', $auth, 'URL');
        $form = $formApi->get(4);`

**Comment by escopecz** [comment]
What Mautic version do you use? It'd be very helpful if you followed the prefilled issue questions.

**Comment by michiellucas** [comment]
Hello, Mautic v2.0.0

**Comment by escopecz** [comment]
I thought so. This was fixed in 2.0.1. I recommend you to upgrade to latest version to avoid issues which were already fixed.
