### ISSUE TITLE
Decision tree with Mautic 2.1.1

### ISSUE THREAD

**Issue by paulcbrady** [mautic/mautic#2589]
![screen shot 2016-09-23 at 10 27 25 am](https://cloud.githubusercontent.com/assets/22416825/18809836/c0674358-8254-11e6-92a6-de7c93cd5546.jpg)
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | X |
| Feature request? |  |
| Enhancement? |  |
## Description:

I created a campaign with two decision points each containing positive and negative branches. When I execute a campaign by filling out a form and respond positively to the first decision point, the campaign will nonetheless send a bye email (skipping over the reminder entirely) and sending out a 'last chance' email even though they have already answered positively in the first decision point. Otherwise, the campaign runs properly (i.e., if I do not reply to first decision it send out a reminder and will either send a thank you or a bye depending on the second decision point.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 hosted version |
| PHP version | hosted version |
### Steps to reproduce:
1. Fill out form.
2. Receive welcome email.
3. Download Asset.
4. Receive Thank You email.
5. 10 Minutes later, Receive Bye (Last Chance) Email. (should not happen).
### Log errors:

hosted version so no log errors.

**Comment by escopecz** [comment]
Could you please retest if this happens on 2.9.2 too?
