### ISSUE TITLE
Reports: Export to CSV: missing first row

### ISSUE THREAD

**Issue by dakur** [mautic/mautic#2590]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When you choose Export to CSV feature in Reports, first row is missing in the exported file.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 5.6.20

### Steps to reproduce:
1. Create new report.
2. Go to created report and select Export to CSV.
 
### Log errors: 
-

**Comment by andersonid** [comment]
confirmed.
