### ISSUE TITLE
Reports: Export to Excel: does not work

### ISSUE THREAD

**Issue by dakur** [mautic/mautic#2591]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

When you choose Export to Excel feature in Reports, nothing happens.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.6.20 |
### Steps to reproduce:
1. Create new report.
2. Go to created report and select Export to Excel.
### Log errors:

None found.

**Comment by escopecz** [comment]
I cannot replicate this. It works for me. Is it not working for every report or one? Are there some errors in the log? https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by MaxWebmecanik** [comment]
I haven't had the opportunity to test this on the newest version of Mautic, but I've seen the export run out of memory with big reports, which in the UI looks like nothing happened. The loading bar stops. But in the background, there should be an out of memory error somewhere.

**Comment by dakur** [comment]
Ok, finally we have it and... sorry, it was my fault. There was a problem with saving php://output by PhpExcel_Writer because we had set bad permissions on temp dir. And first, I did not notice `app/logs` folder.
