### ISSUE TITLE
Sendgrid Sending Issue

### ISSUE THREAD

**Issue by edutj** [mautic/mautic#2594]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  YES
| Feature request? | 
| Enhancement? | 

## Description:

stream_socket_enable_crypto() wont allow connections using the port number 587

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.1.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Trigger Campaign Events though cron / Try to test the connection with Sendgrid
2. If through cron, the command will output the error and the e-mail won't be sent. If through the configuration area, it won't connect to Sendgrid.
 
### Log errors: 

Warning: stream_socket_enable_crypto(): Peer certificate CN=`server' did not match expected CN=`smtp.sendgrid.net' in /path/to/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 95

### Solution:

Edit /path/to/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/SendgridTransport.php from
parent::__construct('smtp.sendgrid.net', 587, 'tls'); to parent::__construct('smtp.sendgrid.net', 2525, 'tls');

**Comment by escopecz** [comment]
I was looking around and I think that the solution you suggested is not secure.

> The correct fix for this is to replace the invalid, misconfigured or self-signed certificate with a good one.

_[source](http://stackoverflow.com/questions/30371910/phpmailer-generates-php-warning-stream-socket-enable-crypto-peer-certificate)_

Take a look here how Sendgrid suggests to fix the certificate issue:

https://sendgrid.com/docs/Classroom/Troubleshooting/Authentication/certificate_verification_failed.html
