### ISSUE TITLE
No interaction follow up - trigger campaign if a user was not in touch within a period of time

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#2610]
### Idea

The basic idea is to catch up with the customer if the customer has not been in touch with my company in a specific period of time. E.g. if you have a direct sales business and the customer was not in touch with the company got any campaigns within the last 30 days, send him a follow up email if he needs anything. The follow up email may be selected randomly from 10 email templates.

If this is anyhow possible, I just oversaw the way to go.
### Use Cases

I guess the plugin would be really handy for e.g. 
- shop automatically sending coupons to reactivate the customer
- direct sales departments which want to know wether they can offer anything to the customer
- websites which want to bring back users to their blog, recommending them an article
- ...
### Mandatory Features:
- Add latest interaction field to contects and update accordingly (for fast filtering)
- Trigger campaign frequently
- Go a random path and select a random email to send.
- Trigger campaign multiple times and not only once (send multiple times)
### Complementary Features
- Track all interactions of the customer with my company (emails, phone calls, maybe connect to crm's).
- Scan mailboxes for incoming and outgoing emails and add them as interactions (multiples mail boxes)
- Allow adding additional interactions through api to be generic (phone calls, crm).
- Coupon Code creation for email
- Limit contact rate. E.g only use the next or random 100 contact  per day, which fit the campaign, to regulate incoming inquires  
### Campaign example
1. Frequently check campaign (once a day)
2. Check if user has not been active within the last period of time and update user profiles 
3. Select a specific group of contacts (no interaction within period of time eg. 30 days) and limit to a specific amount (eg. 100)
4. Randomly select an email to send (or random path)
5. Send email
   6 ... further interaction, e.g. if customer does not react trigger callcenter, add asana task, ... .

**Comment by zenzozen** [comment]
This is a very good feature.
