### ISSUE TITLE
[Bug] Alignment in stats

### ISSUE THREAD

**Issue by Nizzlay** [mautic/mautic#2614]
| Q | A |
| --- | --- |
| Bug report? | ?? |
| Feature request? |  |
| Enhancement? |  |
## Description:

If you send an email to multiple segments, and look at the stats the alignment of the labels in the graph isn't correct.

![Alt text](http://i68.tinypic.com/11hs6tt.png)

Making me think a lot of mails have failed, while actually they are read.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | v2.1.2-dev |
| PHP version | 7.0.8-0ubuntu0.16.04.2 |

**Comment by npracht** [comment]
@escopecz that was solved long time ago in https://github.com/mautic/mautic/pull/2731 i guess
