### ISSUE TITLE
Take owner from the CSV and not global on lead import

### ISSUE THREAD

**Issue by CedricH-BZH** [mautic/mautic#2615]
| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? |  |
| Enhancement? | x |
## Description:

Currently, we can only assign a global lead owner during the import. Therefore, when we import leads from various salespersons, we need to have separate imports.

My feature enhancement request would be to use an import field to affect the lead owner directly from the import and not globally.

We can already define the creator of the lead through the import ... thus we could use the same kind of function to affect the owner.

**Comment by npracht** [comment]
I agree and it should be based on leadowner email address.

**Comment by npracht** [comment]
@kuzmany here is one :)
