### ISSUE TITLE
Mautic integration with shopify?

### ISSUE THREAD

**Issue by tathspts** [mautic/mautic#2618]
Hi I am looking for a integration of mautic with shopify. Someone did a plugin for woo-commerce. I wonder if something like that exists for shopify as well? 

Providing more information on this.

The wordpress plugin I mentioned is https://wordpress.org/plugins/mauticommerce/ This auto tags everything along with pulling email data from orders as well as from abandon carts. Something like this for shopify will be amazing.

I found a script at this website https://pbwebdev.com/blog/mautic-integration-with-shopify Which I modified as below in order to capture order details and put it on checkout page under additional scripts but it seems to be not fetching data.

<script>
 jQuery(function($) { $('body').append('<img src="http://mauticurl/p/mtracking.gif?firstname=' + encodeURIComponent('{{order.customer.first_name}}') + '&lastname=' + encodeURIComponent('{{order.customer.last_name}}') + '&email=' + encodeURIComponent('{{order.customer.email}}') + '">'); });
</script>

**Comment by tathspts** [comment]
Providing more information on this.

The wordpress plugin I mentioned is https://wordpress.org/plugins/mauticommerce/ This auto tags everything along with pulling email data from orders as well as from abandon carts. Something like this for shopify will be amazing.

I found a script at this website https://pbwebdev.com/blog/mautic-integration-with-shopify Which I modified as below in order to capture order details and put it on checkout page under additional scripts but it seems to be not fetching data.

<script>
 jQuery(function($) { $('body').append('<img src="http://mauticurl/p/mtracking.gif?firstname=' + encodeURIComponent('{{order.customer.first_name}}') + '&lastname=' + encodeURIComponent('{{order.customer.last_name}}') + '&email=' + encodeURIComponent('{{order.customer.email}}') + '">'); });
</script>

**Comment by tathspts** [comment]
Providing more information on this.

The wordpress plugin I mentioned is https://wordpress.org/plugins/mauticommerce/ This auto tags everything along with pulling email data from orders as well as from abandon carts. Something like this for shopify will be amazing.

I found a script at this website https://pbwebdev.com/blog/mautic-integration-with-shopify Which I modified as below in order to capture order details and put it on checkout page under additional scripts but it seems to be not fetching data.

<script>
 jQuery(function($) { $('body').append('<img src="http://mauticurl/p/mtracking.gif?firstname=' + encodeURIComponent('{{order.customer.first_name}}') + '&lastname=' + encodeURIComponent('{{order.customer.last_name}}') + '&email=' + encodeURIComponent('{{order.customer.email}}') + '">'); });
</script>

**Comment by tathspts** [comment]
finally found an app that does the integration of Shopify and Mautic. Finally !!! https://apps.shopify.com/mautic-hooks

**Comment by escopecz** [comment]
Cool!

**Comment by devilmind81** [comment]
Hi,
the https://apps.shopify.com/mautic-hooks is not available, and seems at the moment there isn't a way to integrate Mautic with Shopify...
How it possible that Mautic is not providing this feature yet considering that shopify is most used for the ecommerce?
Any news on this?

Thanks a lot.

**Comment by wise-gorilla** [comment]
> Hi,
> the https://apps.shopify.com/mautic-hooks is not available, and seems at the moment there isn't a way to integrate Mautic with Shopify...
> How it possible that Mautic is not providing this feature yet considering that shopify is most used for the ecommerce?
> Any news on this?
> 
> Thanks a lot.

@devilmind81 Finally i finished devloping a Shopify to Mautic integration app, It’s called Mautify… this app can sync all Shopify checkout details like email, name, address etc. also it sync Shopify products, collections tags, vendors, types… also it sync the customer purchase activity which allow you to segment the customers based on the product they bought or the Shopify collection they bought from, it also apply tags if the customer abandoned checkouts so you can recover those abandoned checkouts using Mautic. Mautify also allow you to add points based on his purchase history. My app has a free trial and it’s already avilable on Shopify app store. Please let me know if you have any questions or you need any help to set-up the app.

https://apps.shopify.com/mautify

**Comment by devilmind81** [comment]
Hi @Wise-Gorilla, 
super, I can't wait to test it!

Thank you so much!

**Comment by wise-gorilla** [comment]
@devilmind81 You are welcome, let me know if you have any questions or help to set it up.
