### ISSUE TITLE
When a list drops down off the screen, the items outside the screen can't be reached - scroll bar doesn't update

### ISSUE THREAD

**Issue by levor5** [mautic/mautic#2619]
What type of report is this:
bug report

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
When editing a contact, and clicking a drop-down list which is at the bottom of the page, some items in the drop-down are outside of the screen, and can't be reached because the page's scroll-bar it at 100% and can't be scrolled further to reveal the newly popped items.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
2.1.1
| PHP version | 
7

### Steps to reproduce:
1.  edit a contact
2.  scroll to the bottom of the page
3. click a drop-down list at the bottom of the page [you might need to add a custom field with several choices before doing this]
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
I think it's corrected in 2.2 with this PR https://github.com/mautic/mautic/pull/2489
