### ISSUE TITLE
Email sending gets stuck

### ISSUE THREAD

**Issue by medianicus** [mautic/mautic#2620]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | YES |
| Feature request? |  |
| Enhancement? |  |
## Description:

When sending emails to a segment, the sending gets stuck periodically. Changing the batch size has no effect at all on this.

By exporting the sent emails report, I can see that the sending gets stuck immediately after sending to an email address that contains a subdomain, i.e. _someone@subdomain.domain.com_.

Canceling the send and restarting it continues to send without duplicates.

I am using SendGrid API to send email immediately - it is not known if this affects other transport methods.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 7.0.11 |
### Steps to reproduce:
1. Create contact with subdomain in the address, i.e. _someone@subdomain.domain.com_
2. Add contact to a segment with other email addresses
3. Send email
4. Email sending stops immediately after sending to the address containing a subdomain.
### Log errors:

No errors are shown in the Mautic logs or system logs

**Comment by alanhartless** [comment]
Hi,

I'm not able to reproduce this with standard PHP mailer. Are you using our SendGrid transport or something custom? We don't use SendGrid's API yet  as it's still SMTP based. 

Any errors in Sendgrid?

**Comment by medianicus** [comment]
Hi Alan

Sorry, yes I'm using SendGrid transport, not API. There were no errors in SendGrid.

I'll double check everything on the next mass mailing and get screenshots and log entries from before and after.

**Comment by alanhartless** [comment]
I'm still unable to reproduce this so if the problem persists in latest versions of Mautic, please open a new issue.

Thanks!
