### ISSUE TITLE
Last Active TimeZone Issue comes back after upgrade to v2.1.2-dev

### ISSUE THREAD

**Issue by amagdy3** [mautic/mautic#2626]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | 

## Description:
I used to have the "Last Active" column in the contacts list view having times according to UTC while everything is configured properly acording to my timezone. This had been fixed by upgraded #2397 I upgraded to the mautic:staging branch v2.1.2-dev where this should have been fixed and it was not fixed.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Install mautic v 2.1.1.
2. Apply Time Zone fix #2397
3. Upgrade to v2.1.2-dev (current staging branch)
4. Last active issue comes back
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
Thanks for catching this :-D!

**Comment by amagdy3** [comment]
Thanks for the fix. 

While applying the fix, I couldn't find the file mautic/app/bundles/LeadBundle/Entity/CustomFieldRepositoryTrait.php - so I created it.

That fixed the issue. Thanks
