### ISSUE TITLE
Posibility to create multiple contacts at once using Mautic API

### ISSUE THREAD

**Issue by anshul007aroras** [mautic/mautic#2627]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | YES |
| Feature request? |  |
| Enhancement? |  |
## Description:

I have been trying to Integrate Mautic with Salesforce, but i am facing an issue while POSTing multiple contacts data. If that has to be a single Contact then i get an error '{"error":{"code":400,"message":"#: This form should not contain extra fields.","details":{"#":["This form should not contain extra fields."]}}}'. Please let me know if Mautic does support a list of contacts to be inserted in one go. 
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
| PHP version |  |
### Steps to reproduce:
1. Send a List of contacts as a JSON {"contacts":[{"firstname":"abc","lastname":"xyz"},{"firstname":"abc2","lastname":"xyz2"}]}
2. We get an Error
### Log errors:

Already mentioned

**Comment by escopecz** [comment]
I don't think you can do that. Check the docs: https://developer.mautic.org/#create-contact

I think there is already a 2-way integration with Salesforce. Is it not doing everything you need?

I'll mark this issue as feature request to create multiple contacts via API.

**Comment by anshul007aroras** [comment]
Hi escopecz ,
We have been trying to do the 2 way integration where-in we could push the leads from salesforce to mautic. I have seen the documentation and accordingly setup the plugin and authenticated it as well but we realised that just by authentication we would not be able to push the records from salesforce to mautic and the documentation actually mentioned about a CLI command 'php app/console mautic:integration:fetchleads' which would kick start the process. Now i do have some questions for you over here, i will be glad if you could answer:
a) Do we need to use this command on where the database for mautic is setup?
b) Is there any trigger in mautic which could fire on and do the contact pulling from salesforce on regular instance.

Thanks

**Comment by mqueme** [comment]
@anshul007aroras To be able to pull leads from SF to Mautic, you do need to use the command line instruction on a cronjob to be able to sync both applications.  the CLI is `php /path/to/mautic/app/console mautic:integration:pushleadactivity --integration=Salesforce --time-interval="your desired timeframe"` (as long as your timeframe is not over "29 days") 

> Suggestion: your timeframe should be the same as your cronjob's timeframe, so if you set up your cron job to run every 15 minutes, you can use that same timeframe in your time-interval parameter

There is more info here that can help you [https://mautic.org/docs/en/plugins/salesforce.html](https://mautic.org/docs/en/plugins/salesforce.html)

Hope that answers your question.

**Comment by anshul007aroras** [comment]
@mqueme Thankyou for replying. I am pretty new to PHP and have no or little idea about it but by your answer I understood that I need to have a compiler that could understand PHP, so i have downloaded XAMPP into my system. Next i have also setup the environment variables so PHP as a command in CLI could be understood. Now about the code that would kick start the CRON job '/path/to/mautic/app/console mautic:integration:pushleadactivity --integration=Salesforce --time-interval="your desired timeframe"'. I did not really get this. The path/to/mautic/app/console ?? as we have installed it on our web hosting account with the help of cPanel and have not installed locally on our machine. 

Also I wanted to clear out weather we use the CRON job command in the CLI or should it be the CRON jobs in the CPanel. 
We will be really grateful if you could help us out of this.
Thanks
Anshul

**Comment by escopecz** [comment]
Batch actions will be added in 2.6.0 https://github.com/mautic/mautic/pull/3219
