### ISSUE TITLE
Set Encryption to None in configuration tab

### ISSUE THREAD

**Issue by fabiograz** [mautic/mautic#263]
Hi,
in configuration tab it isn't possible to set none in encryption field, only 'TLS' and 'SSL'.
Solution:
Add in message.ini: mautic.core.config.mailer_encryption.none="None"
change in file app/bundles/CoreBundle/Form/Type/ConfigType.php

       $builder->add('mailer_encryption', 'choice', array(
            'choices'     => array(
                'ssl' => 'mautic.core.config.mailer_encryption.ssl',
                'tls' => 'mautic.core.config.mailer_encryption.tls'
            ),
            'label'       => 'mautic.core.config.form.mailer.encryption',
            'required'    => false,
            'attr'        => array(
                'class'        => 'form-control',
                'data-show-on' => $smtpServiceShowConditions,
                'tooltip'      => 'mautic.core.config.form.mailer.encryption.tooltip'
            ),
            'empty_value' => false
        ));

to 

       $builder->add('mailer_encryption', 'choice', array(
            'choices'     => array(
                'ssl' => 'mautic.core.config.mailer_encryption.ssl',
                'tls' => 'mautic.core.config.mailer_encryption.tls'
            ),
            'label'       => 'mautic.core.config.form.mailer.encryption',
            'required'    => false,
            'attr'        => array(
                'class'        => 'form-control',
                'data-show-on' => $smtpServiceShowConditions,
                'tooltip'      => 'mautic.core.config.form.mailer.encryption.tooltip'
            ),
            'empty_value' => 'mautic.install.form.none'
        ));

**Comment by alanhartless** [comment]
Hi fabiograz!

Would you be willing to submit a PR with this fix?

Thanks!
Alan
