### ISSUE TITLE
Url shorten not working for sms

### ISSUE THREAD

**Issue by hiniesta** [mautic/mautic#2643]
URL shorten not working for SMS. Think is a bug.
In file app/bundle/SmsBundle/EventListener/SmsSuscriber.php you have to change line 144 to:
$tokens[$token] = $this->trackableModel->generateTrackableUrl($trackable, $clickthrough,true);

**Comment by escopecz** [comment]
Duplicate of https://github.com/mautic/mautic/issues/2575
