### ISSUE TITLE
 Uh oh! Eu acho que quebrei. Se eu fizer de novo, por favor comunique ao administrador do sistema!  500 Internal Server Error Mautibot Relatar um problema

### ISSUE THREAD

**Issue by Edabio** [mautic/mautic#2644]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? |  |
| Enhancement? |  |
## Description:

The more details the better...
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
| PHP version |  |
### Steps to reproduce:
1. 
2. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Please read https://mautic.org/docs/en/tips/troubleshooting.html and fill in all the predefined questions. There is nothing we can do to help you with the information you provided.

**Comment by escopecz** [comment]
Closing for the lack of answer. Feel free to comment with a new update and the issue will be opened again.
