### ISSUE TITLE
Mautic not pulling Social Profiles in contacts

### ISSUE THREAD

**Issue by imransayyed** [mautic/mautic#2645]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
Hello,

After importing contacts in Mautic. Contact is created but Mautic not pulling Social Profiles in contacts.
Select the contact created from the list and click on **Social** tab below **Engagements** graph. It shows :

![10-5-2016 7-14-25 pm](https://cloud.githubusercontent.com/assets/1199505/19115564/19653846-8b30-11e6-96c7-86c7d0d45867.png)

**No Social Profiles Found
Click here to search for social media profiles based on contact's available profile data. (Social networks must be configured in the Integration Manager).**

Can anyone please tell me what is the solution's for this.

Regards,

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2

### Steps to reproduce:
1. Create contact in Mautic
2. Select the contact created from the list.
3. Click on **Social** tab below **Engagements** graph.
4. Click on "Click here to search for social media profiles based on contact's available profile data."
5. Result : Mautic not searching Social Profiles.

**Comment by escopecz** [comment]
Did you configure the social plugins as the message says?

**Comment by imransayyed** [comment]
Thanks for you reply.
Yes i have configured social plugins from **Manage Plugins**:
Twitter
LinkedIn 
Google+
Facebook

Or do we have to configure anything else?

![image](https://cloud.githubusercontent.com/assets/1199505/19116499/5ed34a64-8b33-11e6-88d4-6f85a767f2c2.png)
![image](https://cloud.githubusercontent.com/assets/1199505/19116508/699daaca-8b33-11e6-94e2-6b890d557cbf.png)
![image](https://cloud.githubusercontent.com/assets/1199505/19116524/7439fd3a-8b33-11e6-9381-2f09bcb5def2.png)
![image](https://cloud.githubusercontent.com/assets/1199505/19116537/7fc1e92e-8b33-11e6-8e1d-2ad494ded3b4.png)

**Comment by escopecz** [comment]
Looks OK. Does the contact have all correct usernames for each social network filled in?
![mautic-social-usernames](https://cloud.githubusercontent.com/assets/1235442/19116766/e7dd8698-8b16-11e6-9f9f-257118ed755a.png)

**Comment by imransayyed** [comment]
Should it not pull this automatically based on gmail. I was under the impression that Mautic would link the social profiles based on email of the user.

**Comment by escopecz** [comment]
Sadly not. The social network APIs doesn't provide such functionality. I'll close this issue then.

**Comment by imransayyed** [comment]
Thanks.
