### ISSUE TITLE
Unable to install mautic

### ISSUE THREAD

**Issue by abhayasimha** [mautic/mautic#2648]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
Unable to install mautic. It is showing internal server error

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2
| PHP version | 5.6

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

[Sat Sep 24 17:54:14.303714 2016] [:error] [pid 31949] [client 122.171.93.224:51602] exception 'RuntimeException' with message 'Failed to write cache file "/var/www/html/buggy.com/public_html/mautic/app/cache/prod/classes.php".' in /var/www/html/buggy.com/public_html/mautic/vendor/symfony/class-loader/ClassCollectionLoader.php:248\nStack trace:\n#0 /var/www/html/buggy.com/public_html/mautic/vendor/symfony/class-loader/ClassCollectionLoader.php(122): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::writeCacheFile('/var/www/html/s...', '<?php \\nnamespac...')\n#1 /var/www/html/buggy.com/public_html/mautic/app/bootstrap.php.cache(2642): Symfony\\Component\\ClassLoader\\ClassCollectionLoader::load(Array, '/var/www/html/s...', 'classes', false, false, '.php')\n#2 /var/www/html/buggy.com/public_html/mautic/app/AppKernel.php(244): Symfony\\Component\\HttpKernel\\Kernel->doLoadClassCache('classes', '.php')\n#3 /var/www/html/buggy.com/public_html/mautic/app/AppKernel.php(110): AppKernel->boot()\n#4 /var/www/html/buggy.com/public_html/mautic/app/middlewares/CORSMiddleware.php(91): AppKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /var/www/html/buggy.com/public_html/mautic/app/middlewares/CatchExceptionMiddleware.php(43): Mautic\\Middleware\\CORSMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#6 /var/www/html/buggy.com/public_html/mautic/app/middlewares/VersionCheckMiddleware.php(56): Mautic\\Middleware\\CatchExceptionMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#7 /var/www/html/buggy.com/public_html/mautic/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\\Middleware\\VersionCheckMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#8 /var/www/html/buggy.com/public_html/mautic/vendor/stack/run/src/Stack/run.php(13): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#9 /var/www/html/buggy.com/public_html/mautic/index.php(30): Stack\\run(Object(Stack\\StackedHttpKernel))\n#10 {main}

**Comment by escopecz** [comment]
> Failed to write cache file

Check the file/folder permissions. Mautic doesn't have permission to write in them. Consult it with your server provider if you have questions.
