### ISSUE TITLE
Delay time labels in the Graph do not get updated until it's re-opened

### ISSUE THREAD

**Issue by pitus** [mautic/mautic#265]
Just a small inconvenience - when you configure any Delay Time on an Action, it shows it on the JOINT (link), but it doesn't get updated when it's values change until the design is saved and re-opened again.

**Comment by alanhartless** [comment]
Along with this, the non-action/red decision point labels should probably be something like "within x days" rather than "wait x days" to help clarify the delay.

**Comment by alanhartless** [comment]
@pitus Is this with 1.0.2? I tried to replicate this and the label updated each time I editing the delay of the connected action.

Thanks!
Alan

**Comment by pitus** [comment]
I think it's 1.0.2, a recent download from GIT ...

I just tested it again ... the thing is that the first time you change the `for Interval` delay value after launching the Builder, it will not get refreshed in the box over the link but any subsequent changes to it seem to be updating it now (although, I'm sure they didn't get updated even when changed multiple times in some previous, recent version, but I could be wrong as we may have tried to edit once but multiple Decisions - this is still an issue, the first time you edit each Decision, it doesn't get updated ... Multiple decisions on the page and each one needs to be edited multiple times to see a refresh or the builder must be closed, form saved and then reopened).

**Comment by alanhartless** [comment]
Found it and should be fixed with the PR referenced above.

Thanks!
Alan
