### ISSUE TITLE
Auto Populate "Select" Form Fields values from Contact Custom "Select" Field's values

### ISSUE THREAD

**Issue by amagdy3** [mautic/mautic#2650]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes
| Enhancement? | 

## Description:
I'm using mautic for a business network working with specific information such as job function and industry sector, some of these select fields contain 24 values. 

When I want to create a new form that includes select field with values matching to the Contact Custom select field. I have to insert the value as is one by one, which makes creating forms a headache. 

Couldn't it be made such that I can create a form select field that brings its option values from the options of a contact custom field. Something value "value source"? Or even inserting the custom field itself in the form to be updated?

Use case is: 

Subscribe: http://comm.egypreneur.com/subscribe
Update profile: http://comm.egypreneur.com/update-profile

![captureproperties](https://cloud.githubusercontent.com/assets/22257012/19147602/2d5d1740-8bb9-11e6-81b9-f1bcadd8eade.JPG)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Create a custom field with zillion values
2. Create a form to update user data including custom field
3. Create a select field with values matching to that of the custom field
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
Is this on 2.2? It looks like it based on the label/value pairs which was added in 2.2. But if so, if the contact field mapped is a list type field (select, radio, choice), an option to keep in sync should appear. 

![](http://alan.direct/drop/2016-10-06_11-49-33.png)

If that is not happening - what is the type of contact field the form field is mapped to?

**Comment by amagdy3** [comment]
Excellent. I'm confirming in 2.2 that I'm able to select "Use assigned contact field's list choices" - haven't seen this after I upgraded to dev version.

Do I need to change the Custom Select Fields for the contact record to allow multiple options to be selected or it's done automatically with the upgrade?

**Comment by alanhartless** [comment]
Unfortunately - the way multiselect type custom fields will require creating a new custom field as a "multiselect" because it was created as a unique type instead of with a property. We'll likely need to address this in a future version.

**Comment by amagdy3** [comment]
Ok. Will have to create another field then. Create a campaign to update new field with existing values before deleting old ones. Thanks @alanhartless 👍

**Comment by djmonzyk** [comment]
I do not see this option in 2.11 or 2.12.  Should we see this?
