### ISSUE TITLE
Custom Field Fallback Value in Email Body, Subject Line .etc (e.g. {contactfield=company, fallback="Your Company"}

### ISSUE THREAD

**Issue by amagdy3** [mautic/mautic#2652]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes
| Enhancement? | 

## Description:
While creating a campaign referencing variables such as {contactfield=company} - (e.g. "3X Sales for {contactfield=company} in 2017") I wanted to have a different headline for those who don't have the company field populated as for those the subject line will be sent as "3X Sales for in 2017" which is not good.

This got me thinking whether it would make sense to establish conditions for the subject line similar to the Dynamic Email Content feature recently introduced to matuic?

Or it would be better to do this filtration level in a campaign and create different emails to be sent depending on this condition.

In some cases I don't want to create a campaign and just send a broadcast email that's when the campaign idea is a lot more work than necessary.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by bolus** [comment]
Isn't it possible to specify a default value for contacts without the used contact field?

Like "3X Sales for {contactfield=company[your company]} in 2017" - if the contact has the contact field "company" then the value is used, otherwise the text "your company" is used.

This way the subject would still make sense if the contact doesn't have a "company" field:

"3X Sales for your company in 2017".

I haven't installed Mautic yet so I can't easily test if default values are supported

If default values are not supported then this should most likely be implemented - does anybody disagree?

**Comment by Kyle-Foley** [comment]
Yes. Dynamic content in the subject line is already a working feature. 

However, the automatic tag completion does not work in the subject line, therefor you must manually type the tag. 

Example subject line:

Invitation for {contactfield=firstname} at {contactfield=company}

**Comment by amagdy3** [comment]
@bolus do you mean default value in mautic's custom fields or specified as you set it in the tags? I haven't seen it before and not sure if it'd work.

@Kyle-Foley Yes, custom fields can be used in the headline but the point is having different content used in case a specific custom field has a blank value.

**Comment by Kyle-Foley** [comment]
@amagdy3 What you're talking about here is called a "Fallback" value. You can see this type of tag used in competing email programs.

Those tags usually look like this [Company, fallback=Your Company].

If that is what you're asking for, I would recommend a new feature request with the title "Fallback Tag Integration"

**Comment by amagdy3** [comment]
Thanks @Kyle-Foley - @escopecz john shall I create another request or I can change the title of this one and reopen it?

**Comment by escopecz** [comment]
Change the title, please.

**Comment by escopecz** [comment]
But this isn't really working? `{contactfield=company|Default text}`

**Comment by amagdy3** [comment]
Is this an existing feature? I'll try it and report back.

**Comment by bolus** [comment]
@amagdy3 I mean "Fallback" values as @Kyle-Foley did describe

**Comment by escopecz** [comment]
I just wrote some docs about this: https://github.com/mautic/documentation/pull/116

@amagdy3 let us know if it worked for you.

**Comment by amagdy3** [comment]
Thanks guys, this worked for me. Straight forward in the subject line.

Only that I couldn't get it to type or edit it in the body of the Email while using the WYSIWYG editor as it auto select it and doesn't allow adding more content inside the }. I had to switch to HTML view and edit it there and it worked.

**Comment by drimlike** [comment]
@escopecz is it possible to combine 2 custom fields by any chance?
{contactfield=company} would be the preferred variable, but if {contactfield=company} isn't available then fallback to {contactfield=firstname}.

Example: Collaboration ({contactfield=company},{contactfield=firstname}) x MyAwesomeProduct

This would make the subject line of the email still very personalised and not dependent of only one variable.

Thanks in advance for your feedback.
