### ISSUE TITLE
Error on /s/categories

### ISSUE THREAD

**Issue by devadattas** [mautic/mautic#2655]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y

## Description:
Navigating to /s/categories shows 500 error

## If a bug:

Details: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "X" of class "Doctrine\ORM\Query\Expr". Did you mean to call e.g. "andX" or "orX"?" at app/bundles/CoreBundle/Entity/CommonRepository.php line 460 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"X\" of class \"Doctrine\\ORM\\Query\\Expr\".\nDid you mean to call e.g. \"andX\" or \"orX\"? at app/bundles/CoreBundle/Entity/CommonRepository.php:460)"}

| Q   | A
| --- | ---
| Mautic version | v2.2.0 (staging)
| PHP version | 5.6.3

### Steps to reproduce:
1. Navigate to /s/categories
2. Error shows up
 
### Log errors: 

Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here.

**Comment by alanhartless** [comment]
👍

**Comment by escopecz** [comment]
Will be fixed in 2.2.0
