### ISSUE TITLE
All languages are set on Albanian

### ISSUE THREAD

**Issue by fgauttron** [mautic/mautic#2662]
In the configuration panel, all the languages for the translations are set on Albanian.

In my cache folder, there is a file languageList.txt.

{"checkedTime":1475825383,"languages":{"ar":{"id":"24","name":"Albanian","code":"ar"},"ca_ES":{"id":"25","name":"Albanian","code":"ca_ES"},"cs":{"id":"1","name":"Albanian","code":"cs"},"da":{"id":"32","name":"Albanian","code":"da"},"de":{"id":"2","name":"Albanian","code":"de"},"el":{"id":"23","name":"Albanian","code":"el"},"en_GB":{"id":"3","name":"Albanian","code":"en_GB"},"es":{"id":"4","name":"Albanian","code":"es"},"es_AR":{"id":"34","name":"Albanian","code":"es_AR"},"fa_IR":{"id":"28","name":"Albanian","code":"fa_IR"},"fi_FI":{"id":"16","name":"Albanian","code":"fi_FI"},"fil":{"id":"15","name":"Albanian","code":"fil"},"fr":{"id":"5","name":"Albanian","code":"fr"},"he_IL":{"id":"17","name":"Albanian","code":"he_IL"},"hu":{"id":"31","name":"Albanian","code":"hu"},"id_ID":{"id":"26","name":"Albanian","code":"id_ID"},"it_IT":{"id":"13","name":"Albanian","code":"it_IT"},"ja":{"id":"14","name":"Albanian","code":"ja"},"ko_KR":{"id":"27","name":"Albanian","code":"ko_KR"},"nb_NO":{"id":"12","name":"Albanian","code":"nb_NO"},"nl":{"id":"6","name":"Albanian","code":"nl"},"pl_PL":{"id":"11","name":"Albanian","code":"pl_PL"},"pt_BR":{"id":"7","name":"Albanian","code":"pt_BR"},"pt_PT":{"id":"20","name":"Albanian","code":"pt_PT"},"ru":{"id":"8","name":"Albanian","code":"ru"},"sk":{"id":"21","name":"Albanian","code":"sk"},"sl_SI":{"id":"30","name":"Albanian","code":"sl_SI"},"th":{"id":"9","name":"Albanian","code":"th"},"tr":{"id":"10","name":"Albanian","code":"tr"},"vi_VN":{"id":"22","name":"Albanian","code":"vi_VN"},"zh-Hans":{"id":"35","name":"Chinese Simplified","code":"zh-Hans"},"zh_CN":{"id":"33","name":"Albanian","code":"zh_CN"},"zh_Hans":{"id":"19","name":"Albanian","code":"zh_Hans"},"zh_TW":{"id":"29","name":"Albanian","code":"zh_TW"}}}

**Comment by escopecz** [comment]
I can replicate.
![mautic-albanian](https://cloud.githubusercontent.com/assets/1235442/19182393/3c38b25a-8c73-11e6-94f0-84046e151a9a.png)

**Comment by alanhartless** [comment]
This should be resolved. Delete app/cache/languageList.txt to refresh the list.
