### ISSUE TITLE
Cross Domain Tracking and Cookies vs IP Tracking - State of implementation

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#2665]
Hi Everybody,

I'd like to pick up the cookie vs ip tracking topic once again, since I do have several questions regarding this and could not find any answers here on git nor the docs.

### Questions:

1. Does mautic use ip4, ip6, fingerprinting cookie by default?
2. Is anywhere an option to solely use cookies or switch between cookie/ip tracking?
3a. How are cookies persisted? 
3b. Solely cookie or any combination of cookie, localstorage and others? 
3c. Is anything like evercookie used?
4. How does mautic behave in a cross domain tracking context? 
4b. Is there any strategy for cross domain user tracking this?

### Opinion towards cookie vs ip

Situation in Germany, in reason of privacy issues we do have changing IPs in Germany. Meaning every 24h or on every reconnection the ip addresses is changed. Thus, **IP based tracking does not make any sense here!**

On other countries with static IPs this may be different. However it is possible that multiple users in an office may do share one ip address. In this case IP based tracking is not the best either

HOWEVER: Cookie based tracking may be not the best solution in case of any cross domain tracking, since cookies are not set on an foreign origin (if the user never visited the origin bevor) in reason of CORS policies. Thus in this case, depending on your location, IP may be preferred.

Cross device tracking, ... huge issue it self. The big players use single sign on. http://venturebeat.com/2014/10/06/the-cookie-is-dead-heres-how-facebook-google-and-apple-are-tracking-you-now/ 

Thus it should be possible to switch cookie vs ip tracking depending on the needs. And there should be a strategy for cross domain cookie tracking and cross device tracking.

### legal considerations

Fingerprinting may be not allowed in some countries

Cookies laws may differ in different countries. EU is currently working on privacy laws and it is a grey area for analytics. For now it seems an opt-out possibility is enough. 

Thus it may be necessary to implement adjustability of tracking strategies within the mautic script / server.

### Other related issues:

- Switch tracking to JS https://github.com/mautic/mautic/pull/1582 #1582
- Docs on contact monitoring https://mautic.org/docs/en/contacts/contact_monitoring.html

**Comment by escopecz** [comment]
This PR seems very similar to https://github.com/mautic/mautic/issues/2406. Could you please copy your text there so we don't have multiple discussions about one topic on multiple places?
