### ISSUE TITLE
Contacts import fails v2.2.0

### ISSUE THREAD

**Issue by grunf1a** [mautic/mautic#2666]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | Maybe

## Description:

Contact import fails. Error message is written below.  From CSV is created ony first Contact and inserted 1 company.  I think there are also missing some fields (for precise mapping) that distinct contact from company (account).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.0
| PHP version | 

### Steps to reproduce:
1. Contacts -> Import
2.  Upload csv, match fields, Import.
 
### Log errors: 

A new entity was found through the relationship 'Mautic\LeadBundle\Entity\ListLead#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #1. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

**Comment by escopecz** [comment]
Could you share with us a couple lines from your CSV for testing? You can censor the real contact information in it.

**Comment by grunf1a** [comment]
[SLO_test.txt](https://github.com/mautic/mautic/files/516534/SLO_test.txt)
Sure, here it is. Tried to collect representative pattern. If you would like that i translate headers (now are thy in slovenian) just let me know. 
Email (posta) is key, present in every record.

**Comment by escopecz** [comment]
Thanks!

I removed the link to the CSV since it contained contact information for real people. This list could end up in bad hands. But if anyone from the dev team wants it for testing, I have it.

Here is censored, shortened version:
```
Zunanji ID;Naziv;Dolgi naziv;Naslov;Postna;Kraj;Drzava;Telefon;Faks;Posta;Spletna stran;Davcna;Zavezanec za DDV;Maticna;TRR;Tip;Skrbnik;Zadnja aktivnost;Datum zadnje akt.;Datum zadnje akt.;Dejavnost;SKD;Opombe;Zemljevid;Stage
account_000476951;Andreja Golc, s.p.;Aestetika, trgovina in storitve, SDSdfasdf, s.p.;Kolosdvdorska ulica 3r8;32430;Šmarje pri Jelšah;Slovenia;+386;;info@ssss.si;;57970114;Ne;34535353453;SI56 345345345345353 (HYPO BANK d.d.);;Jurij Pet;;;4444-01-01;fdfdgd;G46.190 - Nespecializirano posredništvo pri prodaji raznovrstnih izdelkov;;dfgsdfgsdfg ulica 44, Šmarje pri Jelšah;Mrzla stranka
account_34535353453;FDFDGDGD fffdd gfdgdfg s.p.;dfgdfgdgd, posredovanje modelov in organiziranje kuturnih prireditev, dgfdg dfgdgd s.p.;Ob gozdu 10;2000;Maribor;Slovenia;+386;;slo.sdfasdfasf@gmail.com;http://www.asfdsafasdf.si/;345345353;Ne;345345345353543;SI56 353453534535433 (sdfasfdsa d.d.);;Nina G. Krajnc;;;3453-01-01;asdfsadfas, sejmi, kongresi;N3453543 - asdfsafsa razstav, sejmov, srečanj;;Ob gozdu 10, Maribor;Mrzla stranka
```

**Comment by iwantaspeaker** [comment]
i too am having this problem

I can not import any contacts. I am getting error

> [2016-10-07 21:28:23] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Malformed UTF-8 characters, possibly incorrectly encoded" at /home/contactsiwantasp/public_html/vendor/symfony/http-foundation/JsonResponse.php line 156 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /home/contactsiwantasp/public_html/vendor/symfony/http-foundation/JsonResponse.php:156)"} []

in the logs, but at the end of an import attempt i get lots of occurances of

> "A new entity was found through the relationship 'Mautic\LeadBundle\Entity\ListLead#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #2166. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"})."

Any thoughts??

**Comment by escopecz** [comment]
The first error is because your CSV isn't in UTF8 encoding. Open/Libre Office will let you choose the encoding during export. MS Excel can do it too, but I don't use it so you'll have to google how to. The second error is the bug originally reported.
