### ISSUE TITLE
multi-client capability - multi-mandator - multi-tenant

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#2667]
Just being curious, how does mautic.com implement multi-client capability?

For me this is a really interessting feature to only have one mautic setup for several projects avoiding to have to maintain and update multiple installations. However I do not like to host in the mautic cloud in the us.

This results in two interessting feature requests:
- Multi-Client setup to have multiple clients on one installation.
- Re-recognize users on other website/project if user data is shared between projects.

btw, whats the proper term for this in english? multi-client? multi-mandator? multi-tenant?

**Comment by Khurram-Shahzad** [comment]
@manuelfink I've found a solution may be that will help you to achieve what are looking for.

For example you have two websites. **www.example1.com** & **www.example2.com**
To keep the data separate what you can do is 

Go to 'app/config/paths.php'
Add the following code at top. 

```
$host = $_SERVER['HTTP_HOST'];

if ( $host == 'www.example1.com') {
    $local_config = '%kernel.root_dir%/config/local_example1.php';
} else if ( $host == 'www.example2.com') {
    $local_config = '%kernel.root_dir%/config/local_example2.php';
} else {
    $local_config = '%kernel.root_dir%/config/local.php';
}
```

Now example1.com and example2.com will be sharing different configurations and there you can define different databases.

Make sure to update $paths array in path.php
`'local_config' => $local_config`

Hope so this will help you.

**Comment by 007ke** [comment]
how does the main admin console look? 
Do you the separate admins and permissions for example1 and example2 ?
can you please share some screen shots or links.
Thanks KC

**Comment by nsomaru** [comment]
Any follow up on this? via Google search.

**Comment by pwilhelm949** [comment]
I’m interested as well on this capability. I’ve been with Mautic since 2015 and still haven’t seen anything else similar that provides the end functionality like the suggestion made by Khurram.

**Comment by YosuCadilla** [comment]
Hey there,

If you need Mautic for multiple clients or departments, consider replication instead of multi-tenant / multitenancy, here’s why:

https://mauteam.org/infrastructure/which-is-the-best-way-to-run-mautic-for-agencies/

The basic advantages are security, scalability, portability and the ability to modify a specific customer’s code and/or settings individually.

Cheers!

**Comment by latranchee** [comment]
Hey guys! I have an online course platform and I would like to allow my teachers to own their own marketing lists and create their own landing pages. This feature would allow me to do just that so that's a big 👍 for me!

**Comment by YosuCadilla** [comment]
We build exactly the type of deployments you just described, if interested, please send me an email to yosu.cadilla@gmail.com

**Comment by npracht** [comment]
@YosuCadilla if you want to promote your commercial offer, please comment on the dedicated space here : https://forum.mautic.org/c/commercial/47
Thanks

**Comment by YosuCadilla** [comment]
Hi @latranchee, check my presentation on this Mautic meetup, I explain how to deploy multiple mautic instances in one server:
https://www.youtube.com/watch?v=mnej39I3Wx4
