### ISSUE TITLE
Trackables can't be found for email, which contains A/B-testing

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#2671]
| Q | A |
| --- | --- |
| Bug report? | y |
| Feature request? | n |
| Enhancement? | n |
## Description:

Trackables can't be found for email, which contains A/B-testing.
At `/s/emails/view/241` I just see empty "Clicks count" container with warning "No trackables found" (I could be wrong in exact spelling as in fact I see translated message).

I've visited the same page with dev-mode: `/index_dev.php/s/emails/view/241`. And then found the corresponding SQL:

```
SELECT r.redirect_id, r.url, r.hits, r.unique_hits FROM page_redirects r INNER JOIN channel_url_trackables t ON (r.id = t.redirect_id) AND (t.channel = :channel) AND (t.channel_id = 241) ORDER BY r.url ASC

Parameters: { channel: email } 
```

I've looked into `page_redirects` table: there is just no such data, corresponding to email 241.
Looks like variant scenario misses the piece with filling in `channel_url_trackables` table.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 5.6.23 |
### Steps to reproduce:
1. Create email with several variants and links inside it.
2. Make sure that "Clicks count" tab is always empty.
### Log errors:

No related log entries.

**Comment by escopecz** [comment]
@PatchRanger I think that the links appears after the email is sent. Could you test that?

**Comment by alanhartless** [comment]
That's correct - URLs are converted to trackables on first send. So I'll change this to a feature request to do this on email save instead of first send.
