### ISSUE TITLE
Can't save permissions for Focus.

### ISSUE THREAD

**Issue by buckhornmktg** [mautic/mautic#2674]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:

Can't save permissions for Focus.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2
| PHP version | 5.6

### Steps to reproduce:
1. Add or update permissions for a role.
2. Try to add permissions for Focus, then save or apply.
 
### Log errors: 

mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Permission class not found for focusBundle!" at /public_html/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php line 129 {"exception":"[object] (InvalidArgumentException(code: 0): Permission class not found for focusBundle! at /public_html/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php:129)"}

**Comment by jordan8037310** [comment]
Confirmed this bug also for PHP 7.0.9

**Comment by jordan8037310** [comment]
Pull request #2686 available for review on this issue. The issue was the FormBuilderInterface expected the bundle name `mauticFocusBundle` and instead received the incorrect value of `focusBundle`. Cleaned up related Class names and PHPDocs for clarity.

**Comment by buckhornmktg** [comment]
Wow guys, really impressive how quickly this was resolved.
