### ISSUE TITLE
Close Builder Button Broken on New Focus Item

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#2677]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
When creating a new Focus Item, if you hit the `Close Builder` button, the window does not close.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.0
| PHP version | 7.0.9

### Steps to reproduce:
1. New Focus Item
2. Hit Close Builder

**Comment by alanhartless** [comment]
It's because it's forcing the selection of a style and focus before allowing you to close the builder. We'll fix the UI for this.
