### ISSUE TITLE
Gmail Plugin - tracked emails sent are publicly accessible

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#2678]
| Bug? | 

## Description:
Its a security loophole at the moment. I noticed when accessing the new gmail plugin to track an email sent. The notification showing in mautic, has a link to that email. If pressed, you can view the full content of the email that was sent even when the user is signed out. The link looks like this:
http://[Domain-Name]/mautic/email/view/63xxxxxxxxb38
Its fine for marketing campaign perhaps. However for personal direct emails this is quite dangerous. 

Expected action - such page should only be accessible if the user is signed in to mautic or to have a settings to disable it.

**Comment by virlatinus** [comment]
@jordan8037310 I'm going to modify your fix and add a condition if it's a custom email

**Comment by jordan8037310** [comment]
I did some more work on this in #2689 and had some queries if someone wants to take a look!

**Comment by jordan8037310** [comment]
#2689 has been updated per Alan's feedback, if people can test that would be great!
