### ISSUE TITLE
No edit capabilities after new mautic version upgrade

### ISSUE THREAD

**Issue by galdazbiz** [mautic/mautic#2684]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
I created my account 5 months ago and I was able to edit contacts, now I've entered in the new mautic.net and after version the upgrade I wasn't able anymore. To be sure it was that I created a new account and I had no problem editing.
Additionally I wanted to back up the contacts with reports and the only ones I could backup were the ones I created with the new version but not the old ones

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Latest one in Mautic.net
| PHP version | No idea

### Steps to reproduce:
1. Go to mysite.maautic.net
2. Contacts
3. Edit

1. Go to mysite.maautic.net
2. Reports
3. Create with emails

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by jordan8037310** [comment]
I just tested this on my self-hosted Mautic and it is not reproducible.

@galdazbiz - You should open a support request with mautic.net as the community here can't support your hosted account.
