### ISSUE TITLE
[Bug] Can't change email subject in Form Action "Send form results"

### ISSUE THREAD

**Issue by alvinbenavides** [mautic/mautic#269]
I'm creating a form with an action of sending an email on submit. Is not "Send email to lead" or "Send email to user". Is "Send form results".

I can't change default email subject "Your form results".

**Comment by alanhartless** [comment]
Hi Alvin,

Are you running 1.0.2? This should have been fixed with that version. See https://github.com/mautic/mautic/pull/231.

Thanks,
Alan

**Comment by alvinbenavides** [comment]
Mautic test is 1.0.2 and production is still on 1.0.1. I'm configuring this on production.... 

Actually the email arrived with the correct subject but GUI still displays "Your form results". Later I'll test the same configuration in 1.0.2 and let you know.

Thanks!

**Comment by alanhartless** [comment]
Hey Alvin,

Just following up to see if you were able to confirm if this was fixed in 1.0.2?

Thanks!
Alan

**Comment by alvinbenavides** [comment]
Hi Alan.

Sorry for the delay, I've been working on content for my Muatic campaigns...  :)

You are correct, this is fixed in 1.0.2. In my test envirnoment is working fine and I just upgraded the production environment to 1.0.2 and its also working fine.

Thanks

**Comment by alanhartless** [comment]
Great! Closing this then.

Thanks!
Alan
