### ISSUE TITLE
Gmail plugin - Email is marked "read" right after send

### ISSUE THREAD

**Issue by SvetZitrka** [mautic/mautic#2690]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2 
| PHP version | 7

### Steps to reproduce:
1. Gmail Check "track email with Mautic"
2. email instantly in Mautic appear as read
3. when the reading does occur, the state ignores Mautic

It is further seen here https://drive.google.com/file/d/0B1b90NDTaPtgUDdLWUJsaVRtTkU/view?usp=sharing
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by virlatinus** [comment]
The tracking is done by inserting a tracking gif image in the body of the email. When the image is first displayed the email is created in the contact's timeline. Subsequent viewings are appended to the timeline as read events. If the same user who sent the email opens that email, it counts as a read event. That is the normal behavior of the plugin as of this moment.
