### ISSUE TITLE
Focus window will not close

### ISSUE THREAD

**Issue by SvetZitrka** [mautic/mautic#2691]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | X |
| Feature request? |  |
| Enhancement? |  |
## Description:

The more details the better...
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2 |
| PHP version | 7 |
### Steps to reproduce:
1. create any advice on the stands throughout plugin Fosuc
2. fill out and submit the form inserted
3. window closes wants
4. Likewise, when I click anywhere outside the window focus

Demonstration https://drive.google.com/file/d/0B1b90NDTaPtgeU16b3lZMEtyMWc/view?usp=sharing
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
This was actually reported already here: https://github.com/mautic/mautic/issues/2677

**Comment by escopecz** [comment]
This is a different issue. Reopening.

**Comment by SvetZitrka** [comment]
Sometimes you plan to address this problem? It would have helped us, and I'm surprised that it does not address one another.
