### ISSUE TITLE
Bug: Campaign not firing beyond first step

### ISSUE THREAD

**Issue by mackina** [mautic/mautic#2698]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

I'd reported an issue earlier today, part of the issue was covered here: https://github.com/mautic/mautic/issues/2692 (errors reported) but it doesn't seem to address the main part of the issue, which is that some steps in a Campaign aren't fired.

As the bug on 2692 was caused by campaigns that were created in older versions of Mautic, I created a new campaign to test out the issue. 

![untitled-1](https://cloud.githubusercontent.com/assets/22142941/19239048/35d7daf4-8efc-11e6-90bf-88cbc3d7ce0d.jpg)

The campaign above should send an email to a user that enters the segment, then wait one minute and check a field value. Send an email if value is equal, then check again, and send a third email. 

I ran campaigns:rebuild from CLI, which put two people in the campaign (correct), ran campaigns:trigger and two people got the email (correct). I waited for a couple of minutes, ran trigger again and nothing happened. I've re-ran trigger over the course of five minutes and the second and third emails have not gone out. No errors were reported in CLI, no errors in mautic log. 

I've been tackling this issue for a few days now, so took a different approach. I wondered if there was an issue with items placed after an email. I rebuilt the campaign to look like this:

![mautic-3](https://cloud.githubusercontent.com/assets/22142941/19240315/c05f4ab8-8f01-11e6-8bea-e991f4dc6ef1.jpg)

It tries to complete the same actions required of this campaign, but does not have any decisions or actions hanging off an email. 

The decisions fire at the correct times, but only the first email is sent out. If the "Are they a trial" decision is fired (and it's reported that it is) then at least one of those emails on the Yes/No branch would be sent out.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2 |
| PHP version | 7.0.8-3+deb.sury.org~trusty+1 |
### Steps to reproduce:
1. Recreate either of the two workflows above
2. Manually rebuild campaign, manually trigger campaign over a five minute period. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Could you please describe what the "Are they a trial" decision is? Is it a contact field condition? What type of the field the condition is? Boolean?

**Comment by mackina** [comment]
Of course - both of the decisions are the same field, a text field in the DB and field is classed as lookup in Mautic.

**Comment by mqueme** [comment]
Also see if the contacts are not meeting frequency rules applied, as of Mautic 2.2 these messages are scheduled in a queue and sent by a different cron job. Mentioned here: https://mautic.org/docs/en/contacts/message_queue.html

**Comment by mackina** [comment]
I did take a look at the frequency rules, ours is set as 500 per month (set high during this test) and the email volume is less than that.

I ran the messages:send cron to make sure, and there was nothing in the queue.

**Comment by mqueme** [comment]
if you can check your message_queue table to make sure they are not kept there.

**Comment by mackina** [comment]
Hmm, I don't have a message_queue table in our Mautic db.

**Comment by mqueme** [comment]
if you ran all your migrations correctly, this table should have been created.
[prefix]message_queue

**Comment by mackina** [comment]
Interesting. I ran a script earlier today to make sure that DB structure was in the right format. 

php app/console doctrine:schema:update --force

**Comment by mackina** [comment]
Most recent update (to 2.2) was fired from within web interface, and no issues were reported back during process

**Comment by mackina** [comment]
Hey @mqueme @escopecz - wondering if you'd seen my responses above. We migrated to Mautic a couple of months ago and this issue is stopping us communicating with our users.

**Comment by escopecz** [comment]
It's hard to tell. The table must exist if you are on 2.2.0. What is output of `php app/console doctrine:schema:update --dump-sql`? Do you run the the command for message queue in a cron job?

**Comment by mackina** [comment]
It turns out I was looking at the wrong DB - the instance that we're discussing does have mamessage_queue, it's empty and hasn't had any data in it.  I thought that this was only used if we had hit a frequency limit, and ours is set as 500. 

I've reran multiple test campaigns (from an early post you mentioned the type of field that was in the decision. I changed the second decision (the one that has both yes and no actions) to work off a number, and a bool, and I still can't get the emails to send. Note that the emails are not being marked as sent in the campaign, but the decisions are marked as being reached.

**Comment by mackina** [comment]
FYI the response to the command you listed is:

Nothing to update - your database is already in sync with the current entity metadata.

**Comment by mqueme** [comment]
Could you please update to the latest release 2.2.1 there are a couple of bug fixes regarding campaigns.

**Comment by mackina** [comment]
@mqueme No worries - when will it be released?

**Comment by mackina** [comment]
@mqueme @escopecz Hi guys, I updated to 2.2.1, created new campaigns in the same format as the originals and I'm still having some issues.

How could a condition that has an email action on both yes and no not send the email? It doesnt seem to be related to the mechanism of sending an email, on the campaign page neither email is marked as being sent.

**Comment by mrerich** [comment]
Hey, I probably have the same problem. The campaign makes first steps, then I have a decision which should fire e-mail regarding of the result. The decision is based on the value of a boolean field I added to a contact. 

I would say, that problem is somewhere there - probably no decision is made so no result or so.

**Comment by mrerich** [comment]
And no waiting e-mails in the queue.

**Comment by mrerich** [comment]
Mautic version 2.7.1

**Comment by mrerich** [comment]
Decisions stopped working in runníng campaign. **This is critical** as steps in campaign are dependent on the result of the test. Everything before decision is working. Please, check decision making as it is one of the core functions in Mautic.

**Comment by escopecz** [comment]
There must be some error. Please provide an error and detailed steps to replicate since we cannot reproduce. 

https://mautic.org/docs/en/tips/troubleshooting.html
