### ISSUE TITLE
Form Validation doesn't work with Auto insert method (generate.js script)

### ISSUE THREAD

**Issue by pitus** [mautic/mautic#270]
I'm trying to add a simple Form into an external page so I'm using the Auto mode:
`<script type="text/javascript" src="http://domain.name/form/generate.js?id=4"></script>`

This displays the form and submits it correctly when it's populated, but ... the form validation technique being used eludes me ;)

1) There's a `validateForm:` method in javascript generated with the form, yet that method is **NEVER called** - should I be calling it myself? When and why? Shouldn't it be automatically added to the form's `onSubmit` event as a handler?

2) Seems the validation is actually done on the Mautic server and if errors are detected the user is redirected to the same URL with additional url parameters called `mauticError` and `mauticMessage` - which is what happens when trying the *Form Preview* so I'm guessing that's why they're being used by the `checkMessages` method populating the two containers.
This method, however, has no way (I can think of) of working with an Auto included (script tag) form on a page and in fact, when I submit an empty form with a mandatory Email field on it, I'm redirected to `http://domain.name/form/message` page where the error message is shown at the top in large font, but the form is gone by then and I have to go back to the previous page to see it (which messes up other aspects of that page as the form is intended to be displayed only in a conditional pop-up eventually so reloading of that page will most likely cause additional grief)

**Comment by pitus** [comment]
When I remove that line from FormModel.php it doesn't fix the problem ... in fact, no matter what I do to that file, it seems to be ignored. Deleting app/cache doesn't help ... What am I missing? Where else is it cached? What do I need to do, after deleting this line, to get the form re-generated properly with the onsubmit?

**Comment by alanhartless** [comment]
Hi Pitus,

Re saving the form should generate the correct HTML. 

Thanks!
Alan

**Comment by pitus** [comment]
I just saw it with the onsubmit in the source and was about to tell you that finally it's picked up my change ... but I didn't realize that resaving the form definition did it (and yes, I just resaved it actually).

Could you explain where the old form was cached/stored and why my change wasn't picked up immediately? I did clear the /app/cache but that didn't help... so I'm curious (even though I know now how to regenerate it).

I'm similarly frustrated with other changes to the source not being picked up for example the previewAction but that's a separate issue I'll create later ... just not understanding something in general...

**Comment by alanhartless** [comment]
For forms, the cached html is stored in the database (forms table).  This so to prevent from having to dynamically rebuild it each time the form is called up. 

Thanks!
Alan
