### ISSUE TITLE
Companies proprietary Email Send Settings

### ISSUE THREAD

**Issue by adborges** [mautic/mautic#2700]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
It is understood that the new entity Companies can be used both for different companies or different departments within the same company.

Because it is primarily marketing by email, lead nutrition and automated campaigns, the new entity will have total utility only if the email sending and handling settings are individually assigned for each company or department.

There are many cases where different departments of companies have separate accounts on services like SendGrid, Amazon SES, etc. Often the same company may even have different domains for different purposes. Each with its DKIM configuration, and each headed by a department, with different send quotas and different cost centers.

The proposal is to associate the mail configuration by company and leave the existent configuration for fallback if not set anything separately.

Anyone can develop this?

**Comment by Getron** [comment]
+1
