### ISSUE TITLE
Problems with existing Leads

### ISSUE THREAD

**Issue by different-thinking** [mautic/mautic#272]
Hello,

I have a existing lead and when I enter this eMail adress into another form, I get:
Catchable fatal error: Argument 1 passed to Mautic\LeadBundle\Model\ListModel::regenerateListLeads() must be an instance of Mautic\LeadBundle\Entity\LeadList, array given, called in /www/htdocs/rsieber/mautic/app/bundles/LeadBundle/Model/LeadModel.php on line 557 and defined in /www/htdocs/rsieber/mautic/app/bundles/LeadBundle/Model/ListModel.php on line 121

With new mail addresses it's working fine.

Robert

**Comment by dbhurley** [comment]
Is this on version 1.0.1?

**Comment by different-thinking** [comment]
Good morning David,

it should be th latest: 1.0.2

Robert

**Comment by zapur1** [comment]
I seem to be having the same issue. I tried making the codes changes as are in the commit above but it doesn't seem to have fixed the issue. I did a cache clear and made some changes to the form incase anything was still cached.... It is the same error message in the Apache logs

Zac

**Comment by alanhartless** [comment]
Hi Zac,

Can you verify that the changes in all three files were made? I just tried reversing the changes and hit the error reported.  Then reapplied them which fixed the error. 

Thanks!
Alan

**Comment by zapur1** [comment]
Hi Alan,

Change that to a successful test! I managed to make half the changes to a backup file system instead.

Thanks for getting the fix together so quickly.
Zac

**Comment by zapur1** [comment]
It looks like there might still be another spot that the matching code changes need to be made. I am getting the following error under the same situation as above and also getting the exact same behaviour.

PHP Fatal error:  Cannot use object of type Mautic\\LeadBundle\\Entity\\Lead as array in /home/mautic/public_html/app/bundles/FormBundle/Model/SubmissionModel.php on line 281

I'm not real sure what is happening in that file, so I can't fix it up......

Zac

**Comment by different-thinking** [comment]
Hi Alan,

same situation here! I get this error even when a lead doesn't exist.

*Fatal error*: Cannot use object of type Mautic\LeadBundle\Entity\Lead as
array in
*/www/htdocs/rsieber/mautic/app/bundles/FormBundle/Model/SubmissionModel.php*
on
line *281*

*Robert*

2015-04-16 5:55 GMT+02:00 zapur1 <notifications@github.com>:
