### ISSUE TITLE
Events are pushing out column widths.

### ISSUE THREAD

**Issue by marett** [mautic/mautic#2726]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Emails with a long subject line are pushing out the column widths in responsive tables (ie: those on the Contact details page).

Tested in macOS chrome & safari (current versions) 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.0
| PHP version | 5.6.21

### Steps to reproduce:

1. Create email with long subject line (more than 110 characters)
2. Trigger the email send
3. View this even in the Contact Details screen

![example](http://i.imgur.com/fKsvgtn.gif)
 

### Possible solution:
mautic/app/bundles/CoreBundle/Assets/css/app.css:988

```.ellipsis {
  display: block;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}```

Adding a `max-width:` value to this class is a workaround. I've included `.ellipsis { max-width: 360px!important}` in this CSS file as a means to temporarily solve this issue. 


### Log errors: 

n/a

**Comment by escopecz** [comment]
Will be fixed in 2.2.1 (https://github.com/mautic/mautic/pull/2595)
