### ISSUE TITLE
Error 500 when savon Mail

### ISSUE THREAD

**Issue by OlafDammann** [mautic/mautic#2727]
What type of report is this:

| Bug report? | 

## Description:
I made a theme based on Oxygen, changed some things and now I get random Error 500 when I save mails using this theme.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.1.1
| PHP version | 7.0.6

### Steps to reproduce:
1. Install attached template
2. Create a Mail, klick save
[lf-leadersletter-v11ß4.zip](https://github.com/mautic/mautic/files/523557/lf-leadersletter-v11ss4.zip)

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
This was fixed in 2.2.0 (https://github.com/mautic/mautic/pull/2474)

**Comment by OlafDammann** [comment]
..well... not really: NOW I can create the mail, go click "html edit", do it all in ONE set, klick apply, click save&close. everything else gets error 500 :( 
I'm not saying, my changed Oxygen theme is perfect. but I miss a hint on what's freaking it up

**Comment by escopecz** [comment]
If you want to know what's going on, check the logs (https://mautic.org/docs/en/tips/troubleshooting.html)
