### ISSUE TITLE
New Permission Allowing Users to View Unassigned Companies

### ISSUE THREAD

**Issue by Kyle-Foley** [mautic/mautic#2734]
What type of report is this:

| Enhancement | 

## Description:
**Cutting to the chase**

A permission that allows users to see Companies that have no current user assigned.

**Longer Explanation**

In my particular application, I have multiple sales users with multiple territories, targeting multi-national corporations. In other words, someone in California may be targeting Exxon while someone in the U.K. may also be targeting Exxon. I would like for them to be able to search for "Exxon", see the company "Exxon", but upon click only see the contacts that they are assigned (similar to how public segments currently work). For now, I can work around this by creating "Exxon UK" and "Exxon California" and "Exxon New York" but that is tedious and creates a lot of unnecessary lead segmentation work on my end. 

A better solution would be a permission that allows users to see Companies that have no current user assigned.

This way:
- If I want a company to be only visible to a single sales agent, I can assign it to them.
- If I want a company to be visible to all sales agents, I can leave it unassigned.
- If I want a sales agent to be very restricted, I can remove the permission, and thus their ability to view unassigned companies.

**Comment by merlin0** [comment]
+1
