### ISSUE TITLE
Segment Contact Count is Incorrect for Permissioned Users

### ISSUE THREAD

**Issue by Kyle-Foley** [mautic/mautic#2735]
What type of report is this:

| Bug report |
## Description:

Users are seeing the total count of all contacts inside a segment, instead of the total amount of _their assigned_ contacts inside a particular segment.

This results in some confusion, as I will get calls from the sales agents such as "It says I have 300 contacts, but when I click it I only have 42".
## If a bug:

| Mautic version | 2.2
| PHP version | 5.6.21
### Steps to reproduce:
1. Log in as a user with no contact permissions.
2. View a public segment and note the contact count.
### Log errors:

None.

**Comment by escopecz** [comment]
This is questionable. For example if a user with lower permissions would want to know how many contacts will receive an email sent to a segment, it would give him wrong information. I suggest to remove the link for users with no contact permissions. Would that solve it?

**Comment by Kyle-Foley** [comment]
I see why this would be an issue.

The use case scenario here is for segments where the contact count system total allows the extrapolation of sensitive financial information that you do not want the local sales agent (users) to see. For example, a "purchases" or a "quotations" segment. If someone has access to a total count of the contacts in either of these segments, they can effectively do a reverse calculation and estimate the total revenue of the company.

The work-around I have implemented now involves a campaign that automatically removes contacts from the public "sensitive" segments after two months. The segments themselves have a naming convention that states "prev 2 month ________".

This still provides little financial obfuscation. 

Some solutions:

1.) The ability to add a new class of segments that users are restricted from adding to campaigns and emails, and from which they are able to see only their assigned Contact Counts. These segments would be marked as such by changing the color of the "Contacts X" button to red. This isn't ideal because it restricts non-admin users from sending these segments anything. 

or

2.) The ability of the system to automatically create sub-segments whenever segments contain contacts with multiple user assignments. When a permissioned user adds a segment to a campaign or email, it would only load their sub-segment. This would allow users to see and send email only to their assigned contacts. There are situations where this isn't desirable, so they could be toggle-able and called "Split Segments" or "Div Segments".

**Comment by Kyle-Foley** [comment]
To be clear regarding my second suggestion, this would all take place "under the hood" and would not be visible to any users. (Except perhaps admin when viewing the send totals for a campaign/email)

This has it's own challenges though, because it means also adding the ability to dynamically change the campaign/email report view based on permissions.
