### ISSUE TITLE
Hangs on Form Submission, Form Actions not triggered

### ISSUE THREAD

**Issue by justinroffmarsh** [mautic/mautic#2736]
Since upgrading to 2.2.0, about 50% of form submissions hang.

In some cases, a 500 Internal Server Error is displayed and in others, the pages simply hangs.

In all such cases, form actions are NOT triggered, but the contact IS added to the database.

This issue is also reported here (with a proposed fix that appears not to work for others!):

https://www.mautic.org/community/index.php//5798-form-actions-do-not-trigger

**Comment by merlin0** [comment]
Got the same Issue. If a contact is not know the information will be added to the lead profile, however it won't appear as a form submit. We're using the CURL methode to post the data to Mautic forms.

**Comment by escopecz** [comment]
Please look at the logs (https://mautic.org/docs/en/tips/troubleshooting.html) to see what the actual error is. Then search that error in the existing issues. I bet it was already fixed for Mautic 2.2.1. You can see for example this search: https://github.com/mautic/mautic/issues?utf8=%E2%9C%93&q=is%3Aissue%20submission%20error

And plese, next time do not delete the issue template and fill in the requested information.

I'll close this issue, but I gladly re-open it if you find an error not yet reported.
