### ISSUE TITLE
Froala breaks data slots and adds spurious <br> tags in 2.2

### ISSUE THREAD

**Issue by katalysis** [mautic/mautic#2737]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? |  |
| Enhancement? |  |
## Description:

When editing email text in a data slot in Froala adding a new line places the new text outside the data slot div.  A further unwanted `<br>` tag is then also added at the end of the new text.

For example using the Oxygen theme:
`
<td class="header-lg" data-slot-container="" style="font-family: Helvetica, Arial, sans-serif;font-size: 32px;color: #4d4d4d;text-align: center;line-height: normal;border-collapse: collapse;font-weight: 700;padding: 35px 0 0;">
    <div data-slot="text">You've received an invitation!</div>
</td>`

Becomes this when the extra text is added:

`<td class="header-lg" data-slot-container="" style="font-family: Helvetica, Arial, sans-serif;font-size: 32px;color: #4d4d4d;text-align: center;line-height: normal;border-collapse: collapse;font-weight: 700;padding: 35px 0 0;">
<div data-slot="text">You've received an invitation!</div>more words
    <br>
</td>`
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2 |
| PHP version | 7.0.10 |
### Steps to reproduce:
1. 
2. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
The Content tab will be removed in the future and the Code Mode Builder will be added so this problem will be gone. Here is the PR where the work is being done: https://github.com/mautic/mautic/pull/2653

**Comment by katalysis** [comment]
This is excellent news the Code Mode builder looks just the thing. Thank you.

**Comment by escopecz** [comment]
Fixed in 2.3
