### ISSUE TITLE
Focus doesn't write js file to server

### ISSUE THREAD

**Issue by katalysis** [mautic/mautic#2739]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
I've set up a Focus for the first time but it doesn't work when implemented on my site.  I've added the script tag but the file it references isn't on the server.

There was no folder /pages/focus initially, I created one and gave it 777 permissions in case that helped but it did not.

I have checked the Mautic and php logs and there are no errors.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2
| PHP version | 7.0.10

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
The JS file is generated dynamically. When you open the dev tools at you website (press F12), go to the Network tab and refresh the website. What is the response of that focus script?

**Comment by katalysis** [comment]
I see...  I get 200 OK with a file size of 0 bytes

http://www.katalysis.net/pages/focus/1.js

**Comment by katalysis** [comment]
Huge apologies, I'm an idiot, the Focus wasn't published.
