### ISSUE TITLE
Reordering form fields doesn't works

### ISSUE THREAD

**Issue by insetic** [mautic/mautic#2745]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? |  |
| Enhancement? |  |
## Description:

Try to reorder the fields in a created (or duplicated) form and save.
It does not work
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2 and 2.2.1 |
| PHP version |  |
### Steps to reproduce:
1. 
2. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Does it work after second save?

**Comment by insetic** [comment]
No, it doesn't.
I've tried first to Apply, or save many times, but each time I push the button Apply or Save, the field come back to its original position...

**Comment by wucherpfennig** [comment]
+1

**Comment by YannickBiet** [comment]
+1

**Comment by Tony-Gavin** [comment]
+1

**Comment by mellsaid** [comment]
+1

**Comment by ericgopak** [comment]
+1

**Comment by insetic** [comment]
applied #2882 and it works fine.
thanks!
