### ISSUE TITLE
Increase maximum pagination limit.

### ISSUE THREAD

**Issue by Mike-Benoit** [mautic/mautic#2746]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | Y |
| Enhancement? |  |
## Description:

When dealing with many contacts (ie: hundreds of thousands), it would be nice to have pages that display more than just 100 records at a time, especially for doing mass operations like editing contacts or assigning to segments. Increasing the limit to 1000-2000 range would be nice.

**Comment by escopecz** [comment]
Discussed in https://github.com/mautic/mautic/pull/3575. Please join the discussion there.
