### ISSUE TITLE
Syntax problem - froala_editor

### ISSUE THREAD

**Issue by mateusw3c** [mautic/mautic#2747]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? |  |
| Enhancement? |  |
## Description:

Syntax problem in js file: app/bundles/CoreBundle/Assets/js/libraries/froala/froala_editor.js
Line: 5104
Missing a comma before the 'use strict'
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 5.6.26 |

**Comment by escopecz** [comment]
I bet you are using Cloudflare. Could you switch it of for Mautic until it will be resolved? More info at https://github.com/froala/wysiwyg-editor/issues/1482

**Comment by escopecz** [comment]
Closing for the lack of answer. Feel free to comment with a new update and the issue will be opened again.
