### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by comunidademagento** [mautic/mautic#2749]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
When I send campaign generate error 502 and mentioned this javascript in Firebug and stoped send emails.
https://marketing.comunidademagento.com.br/media/js/libraries.js?vb7b19659

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.2
| PHP version | 7

### Steps to reproduce:
1. Channels > Emails > Send to list
2. 
 
### IMAGES FROM CHROME AND FIREFOX: 

![img01](https://cloud.githubusercontent.com/assets/7476455/19362226/3a6c8ba2-915c-11e6-85d7-d03bbac14a2f.jpg)

![img02](https://cloud.githubusercontent.com/assets/7476455/19362228/3f442220-915c-11e6-8fd1-b1734a118f48.jpg)

**Comment by escopecz** [comment]
Since the error message states that it was generated by Nginx, it doesn't seem as a Mautic issue. Please consult it with your server/hosting provider and in case you find the problem, let us know what it was.

**Comment by iadj** [comment]
Are you hosting on Google Compute Engine? They were having this exact issue with their Load Balancers last night for a few hours, effectively rendering all load balanced Google hosted apps useless.

**Comment by comunidademagento** [comment]
@iadj 

Hi,

Im hosting VULTR/Cloudways - cloudways.com

The Support Cloudways can't reproduce this erros for analyse this problem.

Any tips?

Cheers,

Marcelo Amorim
