### ISSUE TITLE
No image editor when clicking on image in builder

### ISSUE THREAD

**Issue by runeviem** [mautic/mautic#2756]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? | No |
| Enhancement? | No |
## Description:

When you drag in an image in builder (email, page..) and click on it, the image editor doesn't open. Customize slot only shows padding options
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 7 |
### Steps to reproduce:
1. Open email builder
2. Drag image type into content
3. Click on image
### Log errors:

No log errors

**Comment by azamuddin** [comment]
I'm still experiencing this bug on 2.15-beta, installed via Docker mautic/mautic

**Comment by azamuddin** [comment]
And I just upgrade to 2.15.0 the bug still persists, No image editor when I clicked on image
