### ISSUE TITLE
Autoresponders trigger DNC (Do not Contact)

### ISSUE THREAD

**Issue by Mike-Benoit** [mautic/mautic#2761]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

We noticed that when sending out emails, if the recipient has an vacation autoresponder enabled, it will reply to the bounce email address with "Out of the office until X Date", and Mautic records that action as: 

Contact unsubscribed from this channel.
Contact unsubscribed via email

Then marks the contact as Do Not Contact.

This seems a little aggressive to me. Should it not be checking emails for actual "unsubscribe" text or something?
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1 |
| PHP version | 7.0.X |
### Steps to reproduce:
1. Send email from Mautic.
2. Reply to email with vacation response.
3. Contact is marked as Do Not Contact (DNC)

**Comment by MaxWebmecanik** [comment]
Hi, anyone can confirm wether or not that is still the case?

**Comment by escopecz** [comment]
This has been improved over time and another improvements are coming in Mautic 2.10.0. Please retest.

**Comment by MaxWebmecanik** [comment]
@escopecz Can I imply from your closing of this issue that this issue does not occur anymore?

**Comment by escopecz** [comment]
I was waiting for confirmation, but it didn't come. I'll re-open f anyone notice it's happening.
