### ISSUE TITLE
[feature] Segment based on link click

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#2762]
What type of report is this:
| Feature request? | 
| Enhancement? | 
## Description:

It would be nice to create segments (or filter segments) based on clicking on links.

This is similar to https://github.com/mautic/mautic/issues/1126 (except that is on the campaign builder) and I think this comments is a good way to do it: https://github.com/mautic/mautic/issues/1126#issuecomment-250878637

**Comment by escopecz** [comment]
Should be solved in https://github.com/mautic/mautic/pull/2912
