### ISSUE TITLE
Cloned campaign failure

### ISSUE THREAD

**Issue by nlongo91** [mautic/mautic#2764]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
## Description:

When cloning a campaign & going to publish it, the "i broke it" error comes up.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
### Steps to reproduce:
1.  Create Campaign
2. Clone Campaign
3. Make Edits
4. Apply
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
What is the error? Is there some error in the logs? https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by escopecz** [comment]
Is it the same issue described at https://github.com/mautic/mautic/issues/2766?
