### ISSUE TITLE
Campaign Cloning: Breaks Campaign

### ISSUE THREAD

**Issue by mackina** [mautic/mautic#2766]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

Cloning a campaign breaks the new campaign.

Create Campaign 1 (image below). This campaign works successfully.

![mautic-1working](https://cloud.githubusercontent.com/assets/22142941/19408242/634f4776-92b0-11e6-86d1-706b40d21dd5.jpg)

Clone Campaign 1 using the following process: 
1. Click in to Campaign ("Campaign Statistics" at top of page.)
2. Click Clone in top right
3. Change name to campaign 2
4. Click "Save and close"
5. Go back to campaigns list, click in to Campaign 2, click edit, click Campaign Builder.

Campaign doesn't work.

See the subtle difference below, in original campaign the negative path on both conditions says "within 1 minute". On cloned it says "wait 1 minute".

![mautic-2notworking](https://cloud.githubusercontent.com/assets/22142941/19408301/7c805496-92b1-11e6-9ac7-fcf6e408c7da.jpg)

In the DB the cloned campaign is missing the "yes" and "no" in the decision path column.

![mautic-2db](https://cloud.githubusercontent.com/assets/22142941/19408303/848aefd4-92b1-11e6-87c3-10447c1c2354.jpg)

By adding in the correct yes/no's in the db (to properly clone from Campaign 1) it works again. 
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.11 |
| PHP version | PHP Version 7.0.8-3 |
### Steps to reproduce:
1. Create a campaign with conditions, and actions on both conditions. 
2. Clone Campaign using the following process: 
   a. Click in to Campaign ("Campaign Statistics" at top of page.)
   b. Click Clone in top right
   c. Change name to campaign 2
   d. Click "Save and close".
3. Run campaign (to see that it fails to execute actions properly)
4. View campaign events in macampaign_events. Compare decision path field in cloned campaign with original. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by MaxWebmecanik** [comment]
I've noticed similar breakage relating to cloning campaigns.

I think another problem is that if the new campaign is not that different from the original, that is to say no blocks were removed from the main path, rather, only some blocks were modified, and the entry segment is the same, the contacts will enter the campaign at the **same spot they were in the old one**. i.e. if they were already at the end of the old campaign, **they will not go through the new one**.

**Comment by escopecz** [comment]
It's working in 2.6.1
