### ISSUE TITLE
i am using a stand alone form added an action  'send form result' mautic crashes  on form submission without this action works fine 

### ISSUE THREAD

**Issue by Amandeepdubey** [mautic/mautic#2768]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? |  |
| Enhancement? |  |
## Description:

The more details the better...
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
| PHP version |  |
### Steps to reproduce:
1. 
2. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Could you please fill in the information requested in the issue description? Don't forget the error message from the logs (https://mautic.org/docs/en/tips/troubleshooting.html)

**Comment by escopecz** [comment]
Closing for the lack of answer. Feel free to comment with a new update and the issue will be opened again.
