### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by comunidademagento** [mautic/mautic#2769]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When I click in Configuration > Button Apply

Generate error 503

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.2.1
| PHP version | 7

### Steps to reproduce:
1. Configuration > Button Apply
 
### Log errors: 

See attached file general-logs.zip
[general-logs.zip](https://github.com/mautic/mautic/files/531400/general-logs.zip)

### IMAGE: 

![503](https://cloud.githubusercontent.com/assets/7476455/19413262/8c6689d2-92fe-11e6-8b99-540b4f12511a.png)

![nova](https://cloud.githubusercontent.com/assets/7476455/19413406/4778688c-9302-11e6-8568-08519a10de2f.png)

**Comment by escopecz** [comment]
This doesn't seem like a Mautic issue. The 503 error message is from Apache. That means it fails before it gets to Mautic. Consult this error with your server/hosting provider.
