### ISSUE TITLE
Mautic supported email tags.

### ISSUE THREAD

**Issue by lovebdsobuj** [mautic/mautic#2770]
Is there any documentation about **Mautic** supported email tags. 
Like, `{unsubscribe_text}`, `{unsubscribe_url}`, `{webview_text}`, `{webview_url}`?

**Comment by escopecz** [comment]
I just wrote one: https://github.com/mautic/documentation/pull/116/files

It should be merged to the official documentation soon. So I'll close this PR.

For the next time, the documentation has its own repository where you can create issues: https://github.com/mautic/documentation/issues
