### ISSUE TITLE
Bug| Mandrill API Key field not accepting API key 

### ISSUE THREAD

**Issue by merlin0** [mautic/mautic#2777]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | X |
| Feature request? |  |
| Enhancement? |  |
## Description:

We've been using Mandrill Mautic integration to deliver our emails. However on a new Mautic setup we've noticed that Mautic keeps giving an error when filling in the API key field with the API key. However when the same API key is added to local.php the connection works fine and mails can be send with Mandrill.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.1.1/2.2/2.2.1 |
| PHP version | 5.6.19 |
### Steps to reproduce:
1. Create a Mandrill Account.
2. Follow the steps in described in the [documentation ](https://mautic.org/docs/en/emails/bounce_management.html)
3. Select the Mandrill service in the Email settings configuration.
4. Try to add the API key.

**Comment by escopecz** [comment]
Could you check if your API key contains some special characters like `$` or `%` or `'` or '"`?

**Comment by merlin0** [comment]
The only special character I see is an _.

**Comment by escopecz** [comment]
Are you still having this issue? I should ask back then but you mentioned you receive an error. What the error message is?

**Comment by merlin0** [comment]
I no longer get the error message, If I remember correct it would give an error that invalid characters were used.
