### ISSUE TITLE
not able to access plugins after migrating mautic

### ISSUE THREAD

**Issue by kritisingh** [mautic/mautic#2779]
Hi,
I am not able to see installed plugins after migrating the site to a different server.
I get below mentioned error.
 Uh oh! I think I broke it. If I do it again, please report me to the system administrator! 
500 Internal Server Error
![screenshot from 2016-10-18 19 08 57](https://cloud.githubusercontent.com/assets/8470859/19479914/78449e84-9566-11e6-89d9-9dec2fcca19f.png)

**Comment by escopecz** [comment]
Please provide errors from the logs: https://mautic.org/docs/en/tips/troubleshooting.html

Next time, please do not delete the predefined text in the issue description and fill in all requested information.

**Comment by escopecz** [comment]
Closing for the lack of answer. Feel free to comment with a new update and the issue will be opened again.
