### ISSUE TITLE
Remote asset field 'readonly'

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#278]
I've been trying to add a remote asset to mautic but the Remote URL field is readonly. 

I've managed to fix it by using Chrome Devtools to remove the readonly attribute but that can't be as designed :-)

**Comment by alanhartless** [comment]
Thanks for reporting this.  The remote option was originally designed to go hand in hand with one of the cloud storage integrations and thus the URL is filled in by selecting the file via the modal file browser. But I can see that it would be useful to use the same field outside of the cloud storage integrations and simply allow the input of the remote URL directly.  I've marked this as a feature request as the remote URL is working as originally intended (by configuring one of the cloud storage integrations). But, super easy fix to allow manual manipulation of the remote URL as well so will hopefully get this taken care of quickly.

**Comment by wderuijter** [comment]
Hey Alan, it wasn't clear for me this field was related to storage integrations (I'm not using those). Thanks for clearing this up and making it a feature request.

**Comment by alanhartless** [comment]
Sorry; yes that was it's original intended purpose.  But I don't see any reason why to restrict it to just cloud storage integrations; especially since it's always available in the form regardless if a cloud storage is configured or not. I have a PR coming.
