### ISSUE TITLE
'Downloads asset' Campaign Event will not trigger

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#2787]
| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

I have a very simple campaign which does the following:
1. Take the contacts from a segment
2. Check if they have downloaded an asset
3. If they have, put them in another segment

![campaign](https://cloud.githubusercontent.com/assets/18265735/19513631/e188857e-95f0-11e6-8187-206ead2e3eff.jpg)

I manually added a contact (me) to this segment

![segment](https://cloud.githubusercontent.com/assets/18265735/19513705/359aa4b2-95f1-11e6-8f3b-956cb7d33ff6.jpg)

I downloaded the asset from an email

![history](https://cloud.githubusercontent.com/assets/18265735/19514247/2936d11c-95f3-11e6-8cc5-3968d209c13a.jpg)

Yet when I run `mautic:campaigns:update` & `mautic:campaigns:trigger`

![download](https://cloud.githubusercontent.com/assets/18265735/19514440/c4d530fa-95f3-11e6-905f-1ee782f3013f.jpg)

Nothing happens.

Am I doing something wrong?
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | `2.2.1` |
| PHP version | `5.6.27` |

**Comment by escopecz** [comment]
Try to change the order of your actions a little:
1. Add the contacts to the campaign with `mautic:campaigns:update`
2. Download the asset (in an anonymous browser window) and check if it is the contact added to the campaign who downloaded the asset.
3. Trigger the campaign.

**Comment by MaxWebmecanik** [comment]
Hi John,
I've retried from scratch, this time building the campaign before even downloading the asset for the first time.
Still no luck.

**Comment by MaxWebmecanik** [comment]
I've played with this a bit more.
It seems the asset download needs to be linked with an email send or a form submission in order to be taken into account.

My new campaign looks like this.

![new_campaign](https://cloud.githubusercontent.com/assets/18265735/19523782/dd2f3baa-961b-11e6-9cf8-d1c585dd38e9.jpg)

Is this the intended behavior?

If so, maybe it should be removed from the available options when an email hasn't been sent or a form hasn't been submitted beforehand it the same way that _Email Read_ it unavailable before placing a _Send Email_ block.

![decisions](https://cloud.githubusercontent.com/assets/18265735/19523936/6371f676-961c-11e6-9552-b739ae52c484.jpg)

**Comment by sherwood7vid** [comment]
Has this been confirmed if you need to send the email via the campaign for the download asset decision to work?

**Comment by fixmyinfo** [comment]
Same issue  here - on Mautic cloud, just added a number of assets. Trying to test the downloading of an asset - logged in with a test user, a form fill is logged - but that same user using that same test landing page and clicking on a download button with the asset as the download link, no history is kept for it.  [See test landing page and asset download here](https://shredders.mautic.net/test)

**Comment by alanhartless** [comment]
In 2.7.1, once I applied #3685, I was not able to reproduce this issue. Before #3685, the asset download was associated with an anonymous contact and thus didn't trigger the campaign. 

The steps I used to test were -

Create a campaign with downloads asset decision -> modify contacts.
Created a segment email with a token to that asset. 
Sent email to the segment.
Copied and opened the link in an anonymous browser. 
The campaign triggered for the contact.

**Comment by npracht** [comment]
@escopecz i think we can close that issue. We know that mautic does not trigger decision if the decision did not happen while the contact is within the campaign. So it seems logic that the decision does not work if the contact downloaded the asset before being in the campaign.

I think to be clearer for mautic users, having asset download as segment filter (https://github.com/mautic/mautic/issues/3259) would be less confusing because you would not try to add segment to campaign and then directly add a decision about asset download on it.
