### ISSUE TITLE
activeLink is not set for Focus Items plugin - no active page indicator

### ISSUE THREAD

**Issue by MarkLL** [mautic/mautic#2788]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

Focus Items active page indicator does not appear on the menu sidebar. yes I mean the little yellow dot that indicates which of the sub-menus is currently active.

I realize it's a little cosmetic bug, but I find bugs for a living so I'm a bit picky in some cases.

The good news was -- as I'm new to Mautic -- it allowed me to figure out how the activeLink feature works and it's a really easy fix.

Simply change https://github.com/mautic/mautic/blob/staging/plugins/MauticFocusBundle/Controller/FocusController.php#L31

from `null` to `'#mautic_focus_index'`

Sorry, haven't been down the PR track so thought this would be the quickest way. I hope to contribute more as I become more familiar with Mautic's workings :)
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.0+ |
| PHP version |  |
### Steps to reproduce:
1. Login and extend the **Channels** side menu.
2. Click on **Emails** and you will see the Active page indicator (the yellow dot)
3. Now click on the **Focus Items** menu and you will see that the active page indicator does not show.
### Log errors:

N/A

**Comment by FlamesRunner** [comment]
I'll take it.

**Comment by FlamesRunner** [comment]
Fixed in pull request #5108.
