### ISSUE TITLE
Wrong image size in email with Microsoft Outlook

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2791]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

On Microsoft Outlook, resized images in Froala are not displayed with the correct resized height/width, but with the original width/height of the image.
This is linked to #2459 : removing imageOutputSize comes with the height/width attributes to be removed on < img >. 
Outlook is not able use inline style width/height and need height/width as attribute
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2-dev |
| PHP version | 5.6 |
### Steps to reproduce:
1. Create an email
2. Insert a big image (1000px or more)
3. Resize the image to be 200px width or less
4. Save the email, then "send a text"
5. Get the email with Microsoft Outlook 2013 (or maybe any other version)
6. The inserted image has it's original size (>1000px) and not 200px

Because imageOutputSize was removed, another solution is to analyse DOM < img > tags server-side, to get the size from inline style if any. If set, add/replace width=""  and height="" attribute to < img > tag

**Comment by escopecz** [comment]
I personally don't know how to deal with this issue because as you probably know the imageOutputSize and [imageDefaultWidth](https://github.com/mautic/mautic/pull/2601) options were removed because of multiple community requests.

I'll mark it as a feature request because it was considered a bug when the width and height attributes were added to the img tags. We'll see how many people will vote for this.

As a workaround I'd suggest to change the actual image size to what you need which is considered a best practice anyway.

**Comment by chandon** [comment]
@escopecz Why was it considered as a bug ??? as a redondant information, why not, but it's doesn't break anything... and for Outlook, it's mandatory. You can't avoid people using Outlook

**Comment by escopecz** [comment]
The main reason against was that the images are not responsive that way. There was also a bug in Froala which was adding `height="0"` to the images in some cases and then they didn't show up at all. Another bug with Froala was when the image dimension was in percent.

Is it a big problem to use the actual image size in emails?

**Comment by chandon** [comment]
So we should disable the "resize image" command with froala, to force the use of original size. Because resizing leads to buggy emails

**Comment by chandon** [comment]
or even better (but more complicated) : keep the "resize image" from froala, but use event to resize the image on server-side, and include the new generated image instead of the original one. This can be done in froala with :  

      $('.selector').on('froalaEditor.image.resizeEnd', function (e, editor, $img) {
            // Call Ajax to resize the image server-side, and get the new image URL
            // Then remove any size argument in style and attributes, and replace src="" with the new image URL
      });

**Comment by robwent** [comment]
I've just run into the same issue with Outlook and it's not possible to get the users to resize the images.
Couldn't the size attribute be left off by default unless someone specifically uses the resize option?

Someone just adding an image and doing nothing more would get no size attributes and responsive images.

Someone uploading an extra wide image could specify the width as 600px and the image gets the width attribute.

**Comment by chriscalabro** [comment]
I think the suggestion from @robwent to have width and height fields in the slot editor would be a good option. Would definitely increase Outlook compatibility.

**Comment by escopecz** [comment]
Ready to test at https://github.com/mautic/mautic/pull/6845

**Comment by Woeler** [comment]
Merged https://github.com/mautic/mautic/pull/6845

**Comment by alex-bes** [comment]
@escopecz @Woeler hey guys! 

thanks for the work done on this. 

Having outlook support is very important for the project I'm currently working on, I would like to ask is there an ETA on when the release which includes the fix will be rolled out? any schedule?

Thanks in advance,
Alex

**Comment by Woeler** [comment]
@alex-bes Beta in 2 weeks, release probably mid december. We aim before christmas.

**Comment by kaipros** [comment]
Did the new upgrade resolve this issue?

**Comment by HarishSha** [comment]
Some outlook doesn't read style property. So we need to add attribute `width` and `height` specifically. 

**It won't work**
`<img src="...." style="width: 150px;" class="fr-fic fr-dib fr-draggable">`

**It will work**
`<img src="...." style="width: 150px;" width="150" class="fr-fic fr-dib fr-draggable">`
