### ISSUE TITLE
Upcoming Events showing UTC date/time instead of User.

### ISSUE THREAD

**Issue by mattknappchhj** [mautic/mautic#2792]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
## Description:

The Upcoming Events section of the contact view is showing the UTC date/time (but displaying as timezone?) instead of the user/selected time zone.

File: /app/bundles/LeadBundle/Views/Timeline/list.html.php
Line: 503
Content: <p class="fs-12 dark-sm"><?php echo $view['date']->toFull($event['trigger_date']); ?></p>

Suggested change:

<p class="fs-12 dark-sm"><?php echo $view['date']->toFull($event['trigger_date'], 'UTC', 'Y-m-d H:i:s', true); ?></p>

## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 7 |
### Steps to reproduce:
1. Run a campaign trigger with a "wait"
2. Navigate to contact with triggered action
3. View Upcoming Events (bottom-right corner) and notate time.

**Comment by PatchRanger** [comment]
Fixed in https://github.com/mautic/mautic/commit/71585faf9e98f2ff2fed612fb819651fb1621c7d .
