### ISSUE TITLE
API createContact not working

### ISSUE THREAD

**Issue by trops** [mautic/mautic#2794]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:

Before updating to 2.2.1 the API for createContact worked fine.

Now I am getting then following errors.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 7

### Steps to reproduce:
1. Use the following code to create a contact using the REST api.
In this example the $this->authMautic is the auth...and same for apiUrl which are working fine.
`
$params = array(
				'email' => 'my_email@me.com',
				'firstname' => 'John',
				'lastname' => 'last_name'
			);
$contactApi = \Mautic\MauticApi::getContext("contacts", $this->authMautic, $this->apiUrl);

// create a new Mautic contact
$contact = $contactApi->create($params);
`
 
### Log errors: 

Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\InvalidArgumentException: "Expected argument of type "Mautic\StageBundle\Entity\Stage", "NULL" given" at /opt/bitnami/apache2/htdocs/mautic/vendor/symfony/property-access/PropertyAccessor.php line 254 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\InvalidArgumentException(code: 0): Expected argument of type \"Mautic\\StageBundle\\Entity\\Stage\", \"NULL\" given at /opt/bitnami/apache2/htdocs/mautic/vendor/symfony/property-access/PropertyAccessor.php:254)"} []

**Comment by trops** [comment]
This seems to fail on a known contact. Im not sure why. And only a specific contact in my contacts list. So I am stumped. Will try and look into this further.

**Comment by escopecz** [comment]
Ah, this was reported before: https://github.com/mautic/mautic/issues/2490
