### ISSUE TITLE
Error when uploading a resource

### ISSUE THREAD

**Issue by WillDavidMitchell** [mautic/mautic#2795]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Bug |
| Feature request? |  |
| Enhancement? |  |
## Description:

The more details the better...
When I upload a resource, a 150 pg ebook, using my Windows server, 
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version |  |
### Steps to reproduce:
1. Upload a book as a resource.
2.  (Maybe I ran out of HD space??)
### Log errors: Uh oh! I think I broke it. If I do it again, please report me to the system administrator!

500 Internal Server Error

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Please provide the error messages form the logs: https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by WillDavidMitchell** [comment]
I don't find any logs in http://localhost:81/mautic/s/sysinfo


On 10/20/2016 12:38 AM, John Linhart wrote:
>
> Please provide the error messages form the logs: 
> https://mautic.org/docs/en/tips/troubleshooting.html
>
> —
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by escopecz** [comment]
Did you manage to find and fix the problem? Maybe in the server logs?
