### ISSUE TITLE
Contact Tracking: Contact ID & IP Address?

### ISSUE THREAD

**Issue by focalforest** [mautic/mautic#2796]
What type of report is this:

| Bug report | 
## Description:

I'm not 100% sure if the contact tracking is working as expected, done quite a bit of testing the last few days with some friends?

Here's what I'm seeing.

New contact submits a form, cookie is dropped and their 'contact ID' is assigned to the cookie.
New contact browses the website, which tracks just perfectly fine.

New contact (on the same device), changes IP Address due to new location, contact tracking is no longer attributed and written to the contact ID, instead an new anonymous entry is added, and assigned to the IP Address.

Tracking for the new contact stops, until they revert back to their original IP address.
I always assumed that the tracking was attributed to the Contact ID in the cookie and not Contact ID + IP Address?

Our site is setup using the Mautic WP plugin for tracking with the systems base url. As I mentioned tracking seems to be working fine, just not as I'd expect. I assumed all tracking info would be attributed via the cookie and contact ID in the system.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 7.0.12 |
| MySQL | 5.5.52 |
### Steps to reproduce:

1) Contact created via form on focalforest.com
2) Contact added to Mautic, ID assigned.
3) Contact browses main website tracking successful.
4) Contact ID assigned to cookie in browser.
5) Contact changes IP Address, (same device, browser and cookie allocated).
6) Mautic creates an anonymous contact and no longer assigns tracking information to original contact ID.
### Log errors:

The only error I see in the logs is:

[2016-10-19 03:02:16] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Requested URL 
not found: /web-console/ServerInfo.jsp" at [mautic root]/app/bundles/CoreBundle/Controller/CommonController.php
 line 465 {"exception":"[object](Symfony\Component\HttpKernel\Exception\NotFoundHttpException%28code: 0%29: Requested URL not found: /w
eb-console/ServerInfo.jsp at [mautic root]/app/bundles/CoreBundle/Controller/CommonController.php:465)"} []
[2016-10-19 16:48:21] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Requested URL 
not found: /admin/config.php" at [mautic root]/app/bundles/CoreBundle/Controller/CommonController.php line 465 
{"exception":"[object](Symfony\Component\HttpKernel\Exception\NotFoundHttpException%28code: 0%29: Requested URL not found: /admin/confi
g.php at [mautic root]/app/bundles/CoreBundle/Controller/CommonController.php:465)"} []

**Comment by lukasbisdorf** [comment]
In my opinion this is one of the major Bugs in Mautic. The Error in the Log does not seem to be related with this Issue because the Bundle responsible for the Tracking is the "LeadBundle".

There were some other Issues an PR open here:
- Issue: https://github.com/mautic/mautic/issues/2406 
- Issue: https://github.com/mautic/mautic/issues/2665
- Issue: https://github.com/mautic/mautic/issues/2406
- PR: https://github.com/mautic/mautic/pull/1030

Just applying the PR does not solve the Problem, there will be a new record for every user.

**Comment by manuelfink** [comment]
Same problem as I have. This is a dublicate of #2406. I added an in deal description what it causing the problem in the issue. @escopecz should the close our dublicates in rewards for the first issue?

**Comment by lukasbisdorf** [comment]
Yes, as I mentioned before, we should consider to discuss everything related to this bug in one ticket. 
In our case this bug is an show stopper for mautic as solution. 
We fixed it with this PR https://github.com/mautic/mautic/pull/2950
