### ISSUE TITLE
Can't access emails preview

### ISSUE THREAD

**Issue by andrecgro** [mautic/mautic#2797]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | X |
| Feature request? |  |
| Enhancement? |  |
## Description:

After upgrading Mautic from 2.1.1 to 2.2.1 we can't see the preview of our emails. 
In the browser debugger, when I try to see any preview using the link given, I receive a message telling there's missing a ' ; ' after a for-loop (following image)
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 5.6 |

![](https://puu.sh/rPn7n/cc25a14216.png)

**Comment by andrecgro** [comment]
Found a temporary solution here: https://github.com/mautic/mautic/issues/2289

**Comment by alanhartless** [comment]
If this is still an issue in the latest version of Mautic, please let us know and we'll reopen.
