### ISSUE TITLE
Dashboard widget - enhancement

### ISSUE THREAD

**Issue by stephenpaulraj** [mautic/mautic#2798]
What type of report is this:
Enhancement - Can you add a dashboard widget Where you can have a count of Contacts, count of contacts on each segments and count of form submitted on webform. It will be interactive to see everything on dashboard.

**Comment by escopecz** [comment]
You can have this now in 2 widgets. One line chart can show you number of contacts added in time totally, number of contacts added to best 6 segments and in another widget you can have number of form submissions in time. 

If that's not what you want, describe it in more detail, please.

**Comment by escopecz** [comment]
Closing for the lack of answer. Feel free to comment with a new update and the issue will be opened again.
