### ISSUE TITLE
I can't save a new email without a language selected

### ISSUE THREAD

**Issue by maxitromer** [mautic/mautic#2799]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |
## Description:

I can't save a new email without a language selected.

The emails could be `Template` or `Segment` emails. 

Maybe is related to #2760, I don't know exactly.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 5.6.22 |
### Steps to reproduce:
1. Go to Channels > Emails and click on `New`
2. Create a test email as normal but leave empty the `Language` option box.
3. Try to save
### Log errors:

There is no errors in the log for this issue.

**Comment by escopecz** [comment]
I'll close this in favour of https://github.com/mautic/mautic/issues/4617 which contains the error message and confirms it still exists on the latest version.
