### ISSUE TITLE
Add field for adding preheader to email.

### ISSUE THREAD

**Issue by merlin0** [mautic/mautic#2800]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | X |
| Enhancement? |  |
## Description:

It would be great if Mautic would allow user to adjust the preheader by adding a specific preheader field. This would be easier and less time consuming than adding the preheader with the code editor for every email. It would also be nice to have an option to make the preheader hidden.

The image should give an idea what it could look like.

![preheader example](https://cloud.githubusercontent.com/assets/12198056/19597737/ac35bade-9796-11e6-98bf-a7d463cf6435.png)

**Comment by xmontero** [comment]
So, was the "preheader" field finally implemented?

**Comment by RCheesley** [comment]
No - but please add a new feature request at https://forum.mautic.org/c/ideas if you would like to see it (or make the PR to add it to the GrapesJS builder!)

**Comment by xmontero** [comment]
There was an idea there already about this, and it was closed. https://forum.mautic.org/t/allowing-to-define-the-email-preheader-text/10604

Should we reopen that one?
