### ISSUE TITLE
Upstream timed out with nGinx

### ISSUE THREAD

**Issue by Veiote** [mautic/mautic#2807]
Mautic version 2.2.1
PHP version 5.6.23 
Nginx 1.2.1

Im trying import email contacts but I get a timeout in 60s.

I changed in php.ini:
max_execution_time = 300
max_input_time = 120
request_terminate_timeout = 300

And nginx:
keepalive_timeout 120;
location ~* .php$ {
    fastcgi_index   index.php;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_connect_timeout 300;
    }

Log:
upstream timed out (110: Connection timed out) while reading response header from upstream, client: ..., server: ..., request: "POST /s/ajax?action=updateUserStatus&mauticUserLastActive=61&mauticLastNotificationId= HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web209.sock:", host: "...", referrer: "http://.../s/contacts/import"

And mautic freezes in
![sem titulo](https://cloud.githubusercontent.com/assets/7726177/19626434/cb3cc2a8-9910-11e6-8578-51bc67fed208.png)

Any sugestion?
Thanks

**Comment by escopecz** [comment]
Hi! I'll close this issue because it's not a Mautic bug, but server configuration issue. Please, ask this question on an Nginx forum.
