### ISSUE TITLE
Partial match filter not working in 2.2.1

### ISSUE THREAD

**Issue by ToonGeneral** [mautic/mautic#2808]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
Whilst testing an upgrade from 2.1.1 to 2.2.1 I've noticed that I can no longer filter tables properly. I've checked this in Leads, Lists, Emails and Campaigns, so think it's all tables.

It seems to be that a search will only match from the start of the item.
E.g. when searching for leads, 'Wibble' would match 'Wibble Ltd', but not 'The Wibble Ltd'

It would also match for 'Joe Wibble', because it matches the start of the surname field, but wouldn't match 'Joe McWibbly'.

I'm not sure if it's all the same code, but I think I'm getting the same result from the main search bar.

Possibly a rogue ^ in the regex?!

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.2.1
| PHP version |  5.6.25

### Log errors: 

No errors in:
app/logs/
Apache error_log

And nothing revealed by:
https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

**Comment by chandon** [comment]
+1

**Comment by mbrinson** [comment]
I'm having this problem as well.

**Comment by chandon** [comment]
@mbrison just apply #2874 , it'll fix the problem

**Comment by mbrinson** [comment]
Thanks Chandon.  I'll just wait for the next release, assuming this will get merged.  #2874 says "At least one approved review is required by reviewers with write access."  Do you know if someone who has write access is planning on doing this?

**Comment by escopecz** [comment]
Discussed in https://github.com/mautic/mautic/pull/2874#issuecomment-285753039
