### ISSUE TITLE
Segment filter by owner broken in 2.2.1

### ISSUE THREAD

**Issue by ToonGeneral** [mautic/mautic#2809]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

This was originally raised as #1297, fixed in 2.1.1 and now broken again.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 5.6.25 |
### Steps to reproduce:
1. Create/edit a list
2. Add the contact owner filter
3. Can't select a user to filter by
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Loanatik** [comment]
This is an issue for me too.

**Comment by escopecz** [comment]
This seems to be the same bug report as https://github.com/mautic/mautic/issues/2892. I'll close this one since the other is more detailed.
