### ISSUE TITLE
Form checkbox field can have only one option if no values are filled

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#2811]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

Even if I create multiple options for a checkbox field, only the last one gets saved.

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | Hosted Mautic |
### Steps to reproduce:
1. Create a new form
2. Try to create a checkbox field with multiple options. Fill in the option names, no values.

**Comment by alanhartless** [comment]
Hey John,

This is on purpose since the values have to be unique and an empty value is allowed (think select, checkbox/radio groups where the values should be unique). So if you fill in all empty values - it'll merge them all into a single checkbox. To do what you want, fill in only the values leaving the labels blank. The values will then be used for the labels.

**Comment by escopecz** [comment]
Well, it took me a while to figure out that the values must be filled. The logic behind it is clear when you explain it, but when I was used to fill in the option names and close, it really took me several takes to figure out that I don't loose the options I filled in when I fill also the values. Maybe a validation that no option values can be equal would help me understand it before I loose the data. What do you think?

**Comment by alanhartless** [comment]
This is on purpose. Think of it as unique values as required for HTML
elements for select, checkbox or radios. Each empty value gets merged into
one. Fill in the values without labels to achieve what you are trying.

-- 
Alan Hartless

**Comment by alanhartless** [comment]
@escopecz sorry - that second reply was an email I replied with on the same day you posted this. When I checked the issue later, the reply never made it so I rewrote it. Not sure if Github was slow in processing or if my email delayed sending. But I'll reopen this as an enhancement.

**Comment by npracht** [comment]
It may be corrected here i think https://github.com/mautic/mautic/pull/4109 🛩
