### ISSUE TITLE
Add Trackings within JS Tracking

### ISSUE THREAD

**Issue by mmmichael** [mautic/mautic#2816]
Hello,

currently I use ...

> mt('send', 'pageview', {email: 'my@email.com', firstname: 'John'});

... to send Data to my Mautic Installation (Docu = https://mautic.org/docs/en/contacts/contact_monitoring.html). 

How Could I add Tags to the contact using the JS Tracking Version? If I would use the GIF Tracking I simple would add "mtracking.gif?tags=ProductA,-ProductB".

Thanks,
Michael

**Comment by escopecz** [comment]
It's similar to the JS tracking, just different syntax:

```
mt('send', 'pageview', {email: 'my@email.com', firstname: 'John', tags: 'ProductA,-ProductB'});
```
