### ISSUE TITLE
Tokens in dynamic content email are not replaced

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2818]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

dynamic content in email doesn't handle tokens. 
If you test it with swiftmailer, you could think it's working, but with other transport, it's not

Here is how it works now :
- on Email Send Event, dynamic content is added like any other token.
- because dynamic token is added BEFORE tokenization in SwiftMailer, later tokens (like contact tokens) are added later and interpreted later, so some tokens are replaced
- this is unsafe because other transport could not follow the "token" order or reccursion like SwiftMailer
- custom fields added in dynamic content are not replaced, because tokens are not "detected" in Mautic\LeadBundle\EventListener\EmailSubscriber::onEmailGenerate

see #2574 
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2-dev |
| PHP version |  |
### Steps to reproduce:
1. Create a custom contact field "custom_field"
2. Create a contact, set the value "ThisIsATest" in the custom field, and set the email of the contact to your mailbox
3. Create an email with dynamic content, and in dynamic content, add the custom contact field {contactfield=custom_field}
4. Create a campaign to send the email, and add the contact to the campaignn then send the campaign
5. Look at the received email : it contains the text {contactfield=custom_field} and not "ThisIsATest"

**Comment by escopecz** [comment]
Fixed for 2.3
