### ISSUE TITLE
Reports with company fields error with 500

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#2822]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:

When creating a report based on contacts - company fields added to the report cause a 500 because the all the company fields are assumed to be part of the `leads` table.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 7.0

### Steps to reproduce:
1. Create a report using Contacts as the data source
2. On the Data tab, add several Company fields to be included
3. Save and view - the error will be displayed.
 
### Log errors: 

vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.companyname' in 'field list'

**Comment by Rikk03** [comment]
This is already being investigated

**Comment by alanhartless** [comment]
Thanks. Duplicate #2784
