### ISSUE TITLE
Creating Contact Via API returns 500 Internal Server Error

### ISSUE THREAD

**Issue by bamzi** [mautic/mautic#2823]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? |
| Enhancement? | 

## Description:
When trying to `POST` new contacts [leads] to mautic instance via API call, the server returns `500 internal server error`. However, when trying to `GET [root url]/api/contacts?access_token=[access_token]` results are returned as normal. Thus the issue seems to be regarding the `contacts/new` controller/handler.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6.23

### Steps to reproduce:
1. POST `https://[root url]/api/contacts/new`
2. Params:
```
access_token = [access_token]
firstname = John
lastname = Doe
email = john.doe@example.com
```
 
### Log errors: 

no logs found

**Comment by escopecz** [comment]
I'm not 100% sure since the logs were not provided, but this seems to be the same as https://github.com/mautic/mautic/issues/2490

**Comment by bamzi** [comment]
Great. Thank you for the update. I look forward to the release.

**Comment by DiegoSolanoPr** [comment]
Hi. I have a problem when i try to save a contact via API in Mautic. Error 500.  Tahats works when i  do get contacts and geltlist. I do the next request : "Address = {https://test.com/mcontent/api/contacts/new}" (test.com is for this examle, in the real life i use a valid name), the methos is POST. 
I read many forums but i did'nt find the answer. I don't use Php. I use c#. Thanks you is somebody cna help me

**Comment by grinono** [comment]
i'm having the same 'Internal Server Error' on the /api/contacts/new POST request. it worked before, but some it stopped working. running the bitnami Mautic instance on AWS>
