### ISSUE TITLE
Wrong timezone scheduled on campaign action 

### ISSUE THREAD

**Issue by Devidia** [mautic/mautic#2824]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | x |
| Feature request? |  |
| Enhancement? |  |
## Description:

The more details the better...
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | Current on demand release at 24-10-2016 |
| PHP version | Current php version on demand at 24-10-2016 |
### Steps to reproduce:
1. Create a campaign with a action to change de stage like this http://screencast.com/t/cKeBVjxpHQ
### Log errors:

No log error because it's the on demand

**Comment by escopecz** [comment]
Could you please tell us what timezone is configured at your server configuration and what timezone you have configured at your Mautic user and at Mautic configuration?

**Comment by Devidia** [comment]
I setup Europe:Paris timezone on my account and it's the SaaS in demand last release.

I can't tell you about the on demand serveur, then.

- http://screencast.com/t/FZVOY8fOQVqb
- http://screencast.com/t/HCythNh3n43B
Cheers,

**Comment by escopecz** [comment]
Are you sure it's a timezone issue? Isn't it just that all emails are delayed? It can happen on the hosted Mautic because all emails are sent in a queue and some delay may happen if the queue is long after some big campaign was started.

**Comment by Devidia** [comment]
Actually, I'm pretty sure after some test.

When I trying to change the stage of contact [like this](http://content.screencast.com/users/eddy.devidia/folders/Jing/media/2d5588b4-299e-468b-85bd-3cf6e1ea66f2/2016-10-26_1759.png) as you can see [here](http://content.screencast.com/users/eddy.devidia/folders/Jing/media/5f0c2824-e879-4800-9edf-282739750797/2016-10-26_1750.png) in the timeline of the contact, the mail was sent today at 5:43pm and the changing stage seems to be schedule the same day but one hour after (6:13pm). 
Even when I wait one jour, the stage doesn't change automatically.

The same behavior [here](http://content.screencast.com/users/eddy.devidia/folders/Jing/media/b0373912-0101-4a58-b342-4321334e12a8/2016-10-26_1755.png) when I try to automate changing stage to "Cliked"

Many thanks for helping;

**Comment by mareksotak** [comment]
I was experiencing the same issue, which might be related.

Send events were shown that they will be executed with +1 hour

The problem in my case was that I was trying to send an email without subject defined (Mautic allows me to create an email without Subject)
So in fact this error prevented the action to be executed hence it applied the +1 hour rule in default settings - "Wait time before retrying a failed action" (Configure > Campaign Settings)

Adding the Subject to the email helped

**Comment by escopecz** [comment]
Hi Marek, thanks for the report!

I don't see how the email subject can affect the timezone. Emails can be sent without any subject, that's not an error. Or do you see some error in your logs?

**Comment by mareksotak** [comment]
Hi there,
yes, sorry, meant to include it

```
[2016-11-26 23:27:27] mautic.ERROR: [MAIL ERROR] A subject is required. Log data: !! A subject is required. (code: 0) [] []
[2016-11-26 23:27:27] mautic.ERROR: [MAIL ERROR] A subject is required. Log data: !! A subject is required. (code: 0) [] []
[2016-11-26 23:27:40] mautic.NOTICE: PHP Notice: Array to string conversion - in file www/vendor/symfony/translation/Translator.php - at line 209 [] []
```

**Comment by alanhartless** [comment]
This should be resolved in latest versions/releases. If not let us know and we'll reopen.

**Comment by virlatinus** [comment]
I tested in the current Mautic in SaaS using a different timezone (America/Guatemala), created a similar campaign and triggered the change segment events. Everything works fine.

**Comment by nitulsha** [comment]
PHP Notice - date_default_timezone_set(): Timezone ID '' is invalid - in file /var/www/html/mautic/app/bundles/CoreBundle/EventListener/EnvironmentSubscriber.php
