### ISSUE TITLE
Form's field names are not well ordered

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#2826]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? | No |
| Enhancement? | No |
## Description:

Create a stadnalone form
Add a field "text" labelled "Object"
Save the form
The field is created and in attributes you can see HTML name : objet
Create a second field TEXT "Object"
it is named object1

This is normal

But if you edit your form, delete the first field and try to recreate it immediatly after, the name will be changed automatically at object1 even if there's no field "object" anymore.

you have to edit, delete the field, _save_, and then re-edit, to replace the field and keep the original name (used in email template for example)
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 7.0.12 |

**Comment by YannickBiet** [comment]
Hi @dbhurley, has it been fixed or you only do cleanup and add backlog tag ?

**Comment by dbhurley** [comment]
Thanks for checking back in!
https://mautic.slack.com/archives/C02HV76BW/p1511798235000275
