### ISSUE TITLE
Manually Creating contact records duplicate events

### ISSUE THREAD

**Issue by Rikk03** [mautic/mautic#2828]
What type of report is this:

| Bug report? | 
## Description:

Just as the title describes, created contact, added stage and on the contact overview under the charts.
![duplicate](https://cloud.githubusercontent.com/assets/22887653/19685677/0f7118da-9abe-11e6-96a1-9bfa93456f12.png)
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 5.6.24 Fastcgi |
### Steps to reproduce:
1. Create contact adding a stage
2. View contact overview to see the duplicates

**Comment by escopecz** [comment]
I cannot replicate on Mautic 2.7.0, so it either got fixed or there is something more I have to do to reproduce it. If you still get this issue, write step by step how to achieve it and I will re-open this issue.
![screen shot 2017-03-10 at 15 14 06](https://cloud.githubusercontent.com/assets/1235442/23798324/6a341780-05a4-11e7-8868-c4dfc21a500b.png)
