### ISSUE TITLE
Mautic does not trigger the web push notification in the campaigns

### ISSUE THREAD

**Issue by martinstr** [mautic/mautic#2829]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

When setting up Onesignal.com for Mautic and then subscribe to get push notifications on the landing pages it shows up as a lead in onesignal and it is possible to trigger a notification from onesignal. But Mautic will not trigger the notifications from the campaigns. 
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 7.0.12 |
### Steps to reproduce:
1. Setup onesignal.com for Mautic and a campaign with a push notification in. 
2. Create a landing page in Mautic and click yes on the popup to subscribe for push notifications. 
### Log errors:

There is no errors in the log

**Comment by Paul979** [comment]
I also just encountered this, it would be immensely useful and powerful if push notifications could also be triggered in campaigns. But at the moment this doesn't seem possible

**Comment by escopecz** [comment]
It was working on 2.8.0 (https://github.com/mautic/mautic/pull/3274) so it should be fixed by now.
