### ISSUE TITLE
Add rights management for edition token

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2834]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? |  |
| Enhancement? | x |
## Description:

When someone leave the edition of an item (campaign, email, report, form, etc.) without leaving via `Cancel` or `Save and close` buttons, it leaves a token on it.
Then when someone else try to edit, he can kick that person out.
### It would be great to add this privilege on `user rights` management

Maybe you don't want certain role/type of user to be able to do so.

**Comment by escopecz** [comment]
I think that your team solved it with a timeout option a couple versions back.
