### ISSUE TITLE
Support for Custom Field BCC's in Emails

### ISSUE THREAD

**Issue by Kyle-Foley** [mautic/mautic#2837]
What type of report is this:

| Enhancement | 
## Description:

Allow BCC's of emails to go out to different addresses, depending on the contact.

With this feature, a user can also successfully utilize fallback tags so that there is a default BCC, and if detected, a custom BCC.
## Steps to Reproduce

Generate a custom email field (Something like "BCC")
Place the custom field tag within the BCC box under the "Advanced" tab
Send Out Emails Via Segment or Campaign

**Comment by Loanatik** [comment]
In addition to custom field tags, which, clearly should be added, it would be nice to allow dynamic field tags and multiple recipients i.e. 

bcc: x@y.com; {contactfield=mgr_email}; {dynamiccontent="AdditionalRecipientEmails"}

**Comment by Kyle-Foley** [comment]
For the use case of one particular client, there are regional salesmen throughout the globe who do not use the manufacturer's marketing software (Mautic). These salesmen need to be copied on all emails sent to customers in their territories.

As it currently stands, the only way to accomplish this is by creating separate emails with unique BCCs for each territory. 

With 80+ global salesmen, this is not really a feasible option. A dynamic BCC / CC would instantly solve this issue.

**Comment by Kyle-Foley** [comment]
@Loanatik I came up with a temporary solution for this until Mautic natively supports it. 

Here are the steps:

1.) Create a new dedicated email account for this project. "forwards@*******.com" for example.
2.) [Spin up a VPS](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-vnc-on-ubuntu-16-04) running Ubuntu 16.04 with desktop GUI and a VNC server.
3.) Remote in and [install](https://support.mozilla.org/t5/Install-Migrate-and-Update/Installing-Thunderbird-on-Linux/ta-p/14511) Mozilla Thunderbird.
4.) Add the step 1 email account to Thunderbird.
5.) In the Thunderbird account settings, select "[Message Filters](https://support.mozilla.org/t5/Read-send-and-organize-emails/Organize-Your-Messages-by-Using-Filters/ta-p/16488)".
6.) Select "New" and begin creating a series of incoming email filters. 
7.) In each filter's "trigger" section, select "Match all of the following", "Body", "Contains".
8.) In the final trigger field, input a particular word or ID. (I used salesperson full name, but depending on the complexity of your application you can vary this.)
9.) In the "Actions" half of each filter, select the "Forward Email" option and list an external email address you would like to associate with the trigger word / ID from step 8.
10.) Repeat 6 - 9 until you have all your email addresses mapped to keywords / IDs.
11.) Set Thunderbird to check for new emails every minute.
12.) In Mautic, create a new custom field and populate it with the trigger words / IDs.
13.) In the email BCC, put the address you created in step 1.
14.) Insert the custom field tag from step 12 somewhere into the email body. 

The end result BCCs the step 1 address on every Mautic email sent. These emails then get synced to Thunderbird, where the filter rules forward all the messages to unique contacts based on keywords/ID matches in the body.
