### ISSUE TITLE
Add to "do not contact" list

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2839]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | Y |
| Enhancement? |  |
## Description:

I don't see any way for an admin to add a specific contact to the "Do Not Contact" list. It's possible to remove a contact from the list, but not to add it to the liste.

**Comment by angela-d** [comment]
Search the contact -> Click the checkbox beside their name -> On the upper right-corner, click the circle with a line through it symbol -> a pop up prompt will ask you for details.

Only caveat when doing it this way is a channel_id isn't recorded, so if that's how you build your reports, you'll have to manually go into the database to add the channel_id number.

**Comment by chandon** [comment]
@angela-d thanks !
