### ISSUE TITLE
Shows Internal Server Error , when I click on Contact to view details

### ISSUE THREAD

**Issue by deepbot1** [mautic/mautic#2840]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? |  |
| Enhancement? |  |
## Description:

The more details the better...
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
| PHP version |  |
### Steps to reproduce:
1. 
2. 
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Please, fill in more details about the issue. See https://mautic.org/docs/en/tips/troubleshooting.html on where to find them.

**Comment by deepbot1** [comment]
John ,  you already solved the issue on Slack
