### ISSUE TITLE
Contacts displayed on a Google Map

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#2841]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

## Description:
This will require google maps integration as a plugin most likely.

Being able to select contacts from the contacts page, Then a option will be available to map them out. 

This could help identify where you dont have contacts so you can do some local marketing in those regions.

Plugins like this can help reduce rendering power needed.
https://github.com/googlemaps/js-marker-clusterer

**Comment by hilltopmediadesign** [comment]
+1

**Comment by awurman** [comment]
+1

**Comment by vargasbo** [comment]
+1 Has anyone started this already? Have no problem building it out if no one else has already started.

**Comment by awurman** [comment]
It would be better to make this with a free plugin like leaflets , google maps only show for free 2000 markers at a time

**Comment by awurman** [comment]
We started used leaflets , we have some kind of integration but not finished

**Comment by vargasbo** [comment]
Do you have a branch you're working from? Want to build something quickly for my use and can share this with community.
