### ISSUE TITLE
Server Configuration Guide

### ISSUE THREAD

**Issue by Tony-Gavin** [mautic/mautic#2843]
What type of report is this: 

| Q | A |
| --- | --- |
| Bug report? | No |
| Feature request? | Yes |
| Enhancement? | Yes |
## Description:

There does not appear to be a truly comprehensive guide on the correct server configuration for Mautic. I think that one is desperately needed.

I know from personal experience that the vast majority of problems we have encountered with Mautic have been related in some way - _or usually entirely down to_ - server configuration issues. A cursory read of Mautic Community Support tells the same story.

I am not sure if this is the right place to post this. I do know that a comprehensive guide to server configuration is needed.  I am sure that people are walking away from Mautic by the thousands out of the sheer frustration associated with making it work.

How do we go about getting something like this started? I am happy to assist in whatever way I can, although I'm not sure exactly how to go about it. I'm not a programmer, but I do have some understanding and do have programmers working for me on a full-time basis who are familiar with Mautic. 

Open to suggestions...

**Comment by Paul979** [comment]
I second this, the current server requirements (https://www.mautic.org/download/requirements/) paint the picture as if Mautic will run on any Random server, which is totally unrealistic.

**Comment by escopecz** [comment]
If anyone'd like to start the server configuration docs: https://github.com/mautic/documentation#how-to-contribute-to-the-docs

**Comment by Tony-Gavin** [comment]
Thanks @escopecz - that is AWESOME! I'll certainly be making some contributions to this. Just a question - is this an appropriate place to provide information about the various Cron jobs needed for Mautic, or should that perhaps be the subject of another guide? Let me know your thoughts on the matter.

**Comment by escopecz** [comment]
Cron jobs already have a documentation page: https://mautic.org/docs/en/setup/cron_jobs.html. But feel free to improve it.
