### ISSUE TITLE
Blank Title on Email Sending Progress Page

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#2845]
I noticed there are always empty quotes on the email send progress page. In the green title bar:

`<h4 class="panel-title">"" was sent out!</h4>`

Shouldn't the name of the email show up here? It's showing up fine in the top left:

`<h3 class="pull-left">Send "Test 2"</h3>`

**Comment by escopecz** [comment]
@nickian do you still see this issue? Can you take a screenshot of it? I cannot find it in the UI.
