### ISSUE TITLE
Bug - Stats differences between email overview and report view

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2846]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | x |
| Feature request? |  |
| Enhancement? |  |
## Description:

Most of the time, when you shoot an email you're glad to check your email statistics. You have 2 ways to do it:
1. Email overview
2. Create a report `email sent` type
### Report view

![capture d ecran 2016-10-28 a 08 16 20](https://cloud.githubusercontent.com/assets/14075239/19796956/3208b052-9ce8-11e6-83be-e9e4c4a59cce.png)
### Email stats on email page

![capture d ecran 2016-10-28 a 08 16 27](https://cloud.githubusercontent.com/assets/14075239/19796955/32085b20-9ce8-11e6-9104-ff496a0e192e.png)

As you can see, there is a difference between `email open` stats in the 2 reports. The amount of **openers** is different.
That happens most of the time!
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | - |
### Steps to reproduce:
1. Create an email
2. Send it to an enough large database to have great stats
3. Create a report based on `email opens` and add a filter on your specific email
   4 See the number differences between `report` and `email`.

**Comment by PatchRanger** [comment]
I think it could be related (at least partially) to timezone setting, there is a PR that addresses it: #2976 .
I have that PR applied - but nevertheless had to explicitly set `date.timezone` setting in `php.ini` to avoid similar issues with timezone conversion.

**Comment by npracht** [comment]
@dbhurley this bug is still existing. Statistiques are not the same depending on where you look at them.

**Comment by dbhurley** [comment]
Please update with more details so we can continue to track this appropriately.

**Comment by npracht** [comment]
It seems to be working. I couldn't reproduce.

Thanks !
