### ISSUE TITLE
Bug - Wrong number of sent email in report

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2849]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | x |
| Feature request? |  |
| Enhancement? |  |
## Description:

In the report `Email sent` type, the amount of **sent emails** displayed is the amount of **red emails**. This is confusing and i think this is mistaken.

![unnamed](https://cloud.githubusercontent.com/assets/14075239/19799002/7a37703c-9cf4-11e6-8715-228fccfc583e.png)
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | - |

I think it could be related to https://github.com/mautic/mautic/issues/2846, i mean it seems that there is several issues to check the corrects numbers.
### Steps to reproduce:
1. Sent an email
2. Create a report `email sent` type with a filter on the name of your email (or ID).
3. See that the amount of sent email displays the amount of opened emails.

**Comment by escopecz** [comment]
Did you check what date range filter you have selected? Maybe it's different count in total an for the last month.

**Comment by npracht** [comment]
Hello @escopecz yes. And in this case the number of "sent" is the exact number of "read emails". I think it is about the correct data fetched.
_See the number in blue in the pie, it is "Lu" --> Read_

**Comment by escopecz** [comment]
Aha, it's harder for me to understand what the numer means when it is in French.

**Comment by PatchRanger** [comment]
I've noticed the same thing.
Also it definitely looks similar: #2976 .

**Comment by virlatinus** [comment]
Tested on 2.7 and it displays the correct number.
