### ISSUE TITLE
SparkPost Transport not setting reply-to

### ISSUE THREAD

**Issue by runeviem** [mautic/mautic#2853]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Yes |
| Feature request? | No |
| Enhancement? | No |
## Description:

Reply-To is not set in mails sent with SparkPost Transport.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2 |
| PHP version | 7 |
### Steps to reproduce:
1. Configure Mautic to use Sparkpost as email transport
2. Set reply-to for a email message (e.g. a Segment Email)
3. Send email - using Send Example or Send

SparkPost API requires using reply-to field in content array and not setting Reply-To in headers, so this issue is easily fixed by adding the following right above defining $sparkPostMessage in app/bundles/EmailBundle/Swiftmailer/Transport/SparkpostTransport.php

```

        if (isset($message['replyTo'])) {
            $content['reply_to'] = (!empty($message['replyTo']['name']))
                ?
                sprintf('%s <%s>', $message['replyTo']['email'], $message['replyTo']['name'])
                :
                $message['replyTo']['email'];
        }

```
### Log errors:

No errors in log
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by medianicus** [comment]
I wonder if the from name is also affected in the same way.

When sending an email to a contact via SparkPost API, emails are always sent using **both** the from name and from address set in the email configuration in Mautic. This happens regardless of whether the Owner is mailer is set to Yes or No.

Changing the from name and from address in the email advanced settings has no effect - they still get sent from the default. Likewise sending using the email form that pops up after selecting a contact and clicking Send email.
