### ISSUE TITLE
Pop up boxes do not disappear after clicking re-enable contact in contact view.

### ISSUE THREAD

**Issue by SamMoore1** [mautic/mautic#2855]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | bug |
| Feature request? |  |
| Enhancement? |  |
## Description:

The more details the better...

Because of the way sparkpost and mautic webhook works, some addresses are marked as hard bounces when they are really relay refusals because of bad IP reputation. (this is not the bug)

As a result of this I occasionally need to re-enable a contact that has been marked as "Do not contact".
If you hover over the "do not contact" button in the contact view, two black pop up boxes appear  - one on top explaining the reason for not contact in first place and the other saying Re-enable contact. If you move the curser away, the boxes disappear as they should - but if you click to re-enable the contact, the boxes never go away and you need to close the browser window to get rid of them.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | V2.2.1 |
| PHP version | PHP 5.6.27 |
### Steps to reproduce:
1. Open contact view for contact that has been marked "Do not contact" as result of a bounce.
2. Click the button to re-enable the contact
3. The black pop-ups remain
### Log errors:

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Please re-test with latest Mautic version. I cannot replicate. If you still get the issue send a screenshot, please. I'll reopen.
