### ISSUE TITLE
Mautic is not sending emails for team members

### ISSUE THREAD

**Issue by andrecgro** [mautic/mautic#2859]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | X |
| Feature request? |  |
| Enhancement? |  |
## Description:

After updating Mautic for 2.2.1 the members of our team doesn't receive Mautic emails anymore. For example, let's assume I've installed the Mautic for an organization called 123FoundMe. When I try to send any kind of email to a user that has the following email type: johndoe@123foundme.anything,  the emails aren't being received, Mautic notify me, with a push notification, about the emails sent but it doesn't appear on reports for all emails sent either.
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2.1 |
| PHP version | 5.6 |
### Steps to reproduce:
1. Send any type of email to a member that have the organization's email slug.
2. Check if the email has arrived 

### Log errors:

There's no related log.

**Comment by escopecz** [comment]
I cannot reproduce it. It normally sends via different email send options in Mautic to various email addresses I tried. Is this still an issue for you?
