### ISSUE TITLE
Identify emails in email spool

### ISSUE THREAD

**Issue by Arjoni** [mautic/mautic#2861]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? |  |
| Feature request? | x |
| Enhancement? |  |
## Description:

Make emails at email spool identifiable. When you access files in email spool directory, their names are something like: 
cm6URpqflC.message  
kgXdPN4woT.message  
RWpCo5M69V.message  
ZTlhhYCA-x.message

Making them identifiable could help us remove the files manually when we delete a contact. This way we don't send emails to deleted contacts.

**Comment by magnific0** [comment]
grep -r "example@domain.com" .

Does the trick?
