### ISSUE TITLE
BUG - Companies name malformed when importing contacts

### ISSUE THREAD

**Issue by chandon** [mautic/mautic#2866]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

When importing a lead with a company name, the company name is converted with html entities
## If a bug:

| Q | A |
| --- | --- |
| Mautic version | 2.2-dev |
| PHP version |  |
### Steps to reproduce:
1. Create a CSV file with a new lead, and a company name "L'Aggapé" (with accent and apostrophe)
2. Importy the now lead
3. Check into your mysql DB in "companies" table : the company is created with "L&amp;#039;agap&amp;eacute;" as name

**Comment by kangulo** [comment]
in app\bundles\LeadBundle\Model\CompanyModel.php in line 331
`$companyName      = html_entity_decode($companyLeadAdd[$companyId]->getName(), ENT_QUOTES, 'UTF-8');`

in app\bundles\LeadBundle\Model\CompanyModel.php in line 347
`$companyName      = html_entity_decode($companyLeadAdd[$companyId]->getName(), ENT_QUOTES, 'UTF-8');`

**Comment by chandon** [comment]
@kangulo the problem is not companyName decoded, but encoded (or not decoded)... (see #2867) 

in app/bundles/LeadBundle/Helper/IdentifyCompanyHelper.php 

    $companyName = filter_var($parameters['company'], FILTER_SANITIZE_FULL_SPECIAL_CHARS);

**Comment by escopecz** [comment]
Fixed for 2.3
