### ISSUE TITLE
dynamic content in email, contact field causes error, can't edit email anymore

### ISSUE THREAD

**Issue by trops** [mautic/mautic#2868]
What type of report is this:

| Q | A |
| --- | --- |
| Bug report? | Y |
| Feature request? |  |
| Enhancement? |  |
## Description:

I created dynamic content in an email, and I tried using a contact field in the content. This did not auto-populate the contact field like it does in the regular content section, so I typed it in manually 

{contactfield=firstname}

I saved the email, and sent it, and it displayed {contactfield=firstname} in the email. 

When I realized this didn't work, I went back in to edit the email and remove that code, and I am no longer able to edit the email, the page just hangs with the loading bar. Refreshed the page, and still nothing. 

Checking the logs I see this error, (not sure if this is pertinent).

mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget() must be an instance of Symfony\Component\Form\FormView, null given, called in /opt/bitnami/apache2/htdocs/mautic/app/bundles/EmailBundle/Views/Email/form.html.php on line 213" at /opt/bitnami/apache2/htdocs/mautic/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php line 162 {"exception":"[object](Symfony\Component\Debug\Exception\FatalThrowableError%28code: 0%29: Type error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget%28%29 must be an instance of Symfony\Component\Form\FormView, null given, called in /opt/bitnami/apache2/htdocs/mautic/app/bundles/EmailBundle/Views/Email/form.html.php on line 213 at /opt/bitnami/apache2/htdocs/mautic/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php:162)"} []
[2016-10-30 18:08:27] mautic.ERROR: Notice: Trying to get property of non-object - in file /opt/bitnami/apache2/htdocs/mautic/app/bundles/EmailBundle/Views/Email/form.html.php - at line 15 [] []
## If a bug:

| Q | A |
| --- | --- |
| Mautic version |  |
| PHP version |  |
### Steps to reproduce:
1. Create Dynamic Content in email
2. Add {contactfield=firstname} in one of the dynamic content sections (content)
3. Save the Email
4. Try and edit the email again.
5. The page hands (for me)
### Log errors:

mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget() must be an instance of Symfony\Component\Form\FormView, null given, called in /opt/bitnami/apache2/htdocs/mautic/app/bundles/EmailBundle/Views/Email/form.html.php on line 213" at /opt/bitnami/apache2/htdocs/mautic/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php line 162 {"exception":"[object](Symfony\Component\Debug\Exception\FatalThrowableError%28code: 0%29: Type error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget%28%29 must be an instance of Symfony\Component\Form\FormView, null given, called in /opt/bitnami/apache2/htdocs/mautic/app/bundles/EmailBundle/Views/Email/form.html.php on line 213 at /opt/bitnami/apache2/htdocs/mautic/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php:162)"} []
[2016-10-30 18:08:27] mautic.ERROR: Notice: Trying to get property of non-object - in file /opt/bitnami/apache2/htdocs/mautic/app/bundles/EmailBundle/Views/Email/form.html.php - at line 15 [] []

**Comment by kuzmany** [comment]
#2813 this should fix it

**Comment by trops** [comment]
so that is saying when dynamic content is removed, but I have dynamic
content, but it has twig code inside to display a contactfield.

Is this fix for that as well?
