### ISSUE TITLE
Auto-complete stopped working

### ISSUE THREAD

**Issue by ToonGeneral** [mautic/mautic#2873]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
This morning our users noticed that the auto-complete for fields when adding a new contact has stopped working. I believe this has happened within the last 24 hours or it would have been noticed sooner.

As a front end experience issue, we've replicated it on admin and non-admin user accounts, plus across Chrome, Edge and Firefox.

I have tried to ascertain if this is a server environment issue. I can't see any OS/module updates or changes in this timeframe. I can't find anything in any server level logs. I've tried fully rebooting the whole server that Mautic sits on and that hasn't resolved it.

There is nothing in the Apache logs, nor the Mautic prod logs.

So I'm in a situation where some Mautic functionality isn't working, but I don't have any visual indication that it's erroring, just that it isn't returning any results, nor info in logs to troubleshoot it.

Any help much appreciated.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.1.1
| PHP version |  5.6.25

### Steps to reproduce:
1. Start creating a new contact
2. Try to fill in Last name, or Company, with values which should match existing records
3. Auto complete won't come up
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
I'm not aware of any autocomplete function on contact form. Only the email field will show if a contact with such email already exist. Maybe you mean the autocomplete feature of your browser?
