### ISSUE TITLE
MessageHelper.php not committing

### ISSUE THREAD

**Issue by guibamp** [mautic/mautic#2876]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I do not have much experience with PHP and I'm just starting with Mautic. 
I configured Amazon SNS to send me bounce notifications, then I'm calling 
`php <mautic_home>/app/console mautic:email:fetch`
so the message can be analyzed and the user saved in `lead_donotcontact` table.
I understand that this is done in `<mautic_home>/app/bundles/EmailBundle/Helper/MessageHelper.php` file, method `analyzeMessage(...)`. I've put some logs to see if the bounce message is analyzed correctly and it is. The problem is when inserting the user in `lead_donotcontact` table:

```
                // Create a DNC entry
                try {
                    $this->db->insert(
                        MAUTIC_TABLE_PREFIX.'lead_donotcontact',
                        [
                            'lead_id'    => $leadId,
                            'channel'    => 'email',
                            'channel_id' => $emailId,
                            'date_added' => $dtHelper->toUtcString(),
                            'reason'     => ($isUnsubscribe || $isFbl) ? DoNotContact::UNSUBSCRIBED : DoNotContact::BOUNCED,
                            'comments'   => $this->factory->getTranslator()->trans('mautic.email.bounce.reason.'.$messageDetails['rule_cat']),
                        ]
                    );
                } catch (\Exception $e) {
                    $this->logger->error($e->getMessage());
                }
```

I enabled logging in MySQL and I can see this being executed but the problem is that there is no `commit`. My MySQL has `autocommit` set to `OFF` so without commit this insert would not work. 

I have wrapped this code between:
```
$this->db->beginTransaction();
...
$this->db->commit();
```

and it worked, the record is committed successfully. Is this really a bug or am I missing something?

Thanks

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6.26

### Steps to reproduce:
1. Get a bounce message
2. Execute `php <mautic_home>/app/console mautic:email:fetch`
3. Check if user was saved in `lead_donotcontact` table

**Comment by angela-d** [comment]
Are you experiencing this for *all* bounces?
If not, what's the diagnostic line?  I've run into a few of these, too: https://github.com/mautic/mautic/pull/2835

**Comment by guibamp** [comment]
Hello Angela, I don't believe my issue is related to yours. So far it is not saving for all bounces. But I may be missing something, as I said I can see in MySQL logs the insert happening, only there is no commit happening. 

Should I configure something in mautic so commit always happen? Or is this a bug...

**Comment by guibamp** [comment]
@dbhurley was this fixed?
