### ISSUE TITLE
Impossible to Generate Reports of Contacts With NULL Creation Date

### ISSUE THREAD

**Issue by Kyle-Foley** [mautic/mautic#2877]
What type of report is this:

| Bug report | 

## Description:

This bug can affect contacts that are imported into Mautic via CSV file.

Reports currently force a date range onto all queries. 

If a contact has a creation date of NULL, the query will not include it, and thus the contact data will be excluded from all reports.

## If a bug:

| Mautic version | 2.2.1
| PHP version | 5.6.21

### Steps to reproduce:
1.  Import a contact into Mautic via CSV with a DateCreated value of NULL
2. Run a report with parameters to match that contact.
 
### Log errors: 

None.

**Comment by escopecz** [comment]
Is there a reason why to import contact with DateCreated with NULL value?

**Comment by Kyle-Foley** [comment]
From what I can remember, it was an import of another application's database (Suite/SugarCRM), which used null values for blank contact fields. The issue arose when I exported that Database into CSV format then imported into Mautic.

I manually fixed the problem in MySQL.

**Comment by Kyle-Foley** [comment]
I also this issue was fixed here.

https://github.com/mautic/mautic/commit/3b6ceb8021ad0cc3fd67baea8409bf3941bdf1a3
