### ISSUE TITLE
Disable position field to replace by a dropdown list

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#2887]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
The default text field for position is not suitable for us as we want to ask the user its position in the forms and then segment this data.
We want to provide our user a dropdown list of choices for his position.

He then need to select one.

We created the field "fonction" and imported it via the import feature using CSV files

We wanted to disable position core field and so went to custom field screen and disable the field

As soon as we disable it, we can't edit any contact anymore. The edit button is not working
as soon as we reactivate it, it is working again.

Is it possible to disable the position field ?

Question bis : how to display our field in edit mode like position field was, meaning near company's name on the same row

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 7.0.12

**Comment by escopecz** [comment]
This is working on Mautic 2.9.2. Just tested.
