### ISSUE TITLE
Company phone field doesn't show up anywhere

### ISSUE THREAD

**Issue by kevingarman** [mautic/mautic#2890]
Possible bug...

It seems that the 'company phone' field is somehow unusable.  It is listed on the field customization page, but it doesn't show up in the contact details or contact editor.

Mautic:  2.2.1
PHP: 7.0.9-1

Thanks,
Kevin

**Comment by mqueme** [comment]
Try looking in the company menu.
<img width="1050" alt="screen shot 2016-11-29 at 10 39 59" src="https://cloud.githubusercontent.com/assets/1496976/20706652/385ce774-b620-11e6-9316-128a37794fd4.png">

**Comment by kevingarman** [comment]
Thanks mqueme.

The reason I asked is that I have to open a contact to find their company and then go to the companies list to find the phone number...kind of cumbersome.  However, now I see there is a link to the contact's company over on the righthand side of the contact profile page.
