### ISSUE TITLE
Feature request - Push Form Notes / Text Area Into A Note For Each Event

### ISSUE THREAD

**Issue by seoptiks** [mautic/mautic#2891]
#Definition of the need

I am using Mautic as a more traditional CRM for collecting all Business web forms on the website.  Some forms they can download a brochure, others are a contact form which contains a textarea field.  Because a repeat potential or existing client may ask several questions at various different times we need a way to chronologically showcase each event and its information.  

## How it would look like

The idea is that every time a form is submitted by a contact a copy of it goes into the Notes Field.  This is useful for traditional websites where customers want to ask a quick question like can I buy or get a quote on XYZ.

Each inquiry would cumulatively collect inside this notes field.

![image](https://cloud.githubusercontent.com/assets/18560376/20006705/36511d20-a26f-11e6-820c-17bc6803803b.png)

**Comment by escopecz** [comment]
I don't think duplicating information from form submissions to notes is helpful anyhow. If you want to see only form submissions, filter only that event.
