### ISSUE TITLE
owner_id filter on segments not saving

### ISSUE THREAD

**Issue by evladutoiu** [mautic/mautic#2892]
| Q  | A
| ---| ---
| Bug report? | Yes

## Description:
When trying to filter a segment by owner, apart from the empty and not empty dropdown options, each option will error in "A value is required." for the filter field.
I've narrowed it down that the hidden input with the name="leadlist[filters][0][filter]" does not get populated with the owner id (or with anything else for that matter).
I have not found a way to capture the id from the json file that comes back from typeahead to put it in that field. Moreover, the typeahead function doesn't always load on the filter field input.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2
| PHP version | 5.6.22

### Steps to reproduce:
1. Create new segment
2. give name
3. go to filters
4. select owner as a filter
5. select "equals" from the dropdown
6. write something in the field, preferably a owner name (look it up in your contatcs)
7. save
8. pull hair out :))
 
### Log errors: 
No logs to show here
![leadlist](https://cloud.githubusercontent.com/assets/10630335/20010124/aa797b44-a2af-11e6-8960-fa9b05951f6b.PNG)

**Comment by evladutoiu** [comment]
@escopecz Hey I saw you checked out this ticket... do you know if anyone is working on it or if we can get a timeline for it? I appreciate you taking the time!

**Comment by dongilbert** [comment]
Fixed in #3643
