### ISSUE TITLE
HTML content in Focus Item

### ISSUE THREAD

**Issue by lsoldado** [mautic/mautic#2894]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
Ability to add custom html to Focus Item, especially to "Display a notice".
This could be achieved by changing the field "Tagline" to html.
In attach one example of what it could be done.
![captura de ecra 2016-11-04 as 22 47 02](https://cloud.githubusercontent.com/assets/22603486/20024803/bb2e23fa-a2e0-11e6-9bc7-876e6f3cf365.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 7

**Comment by kuzmany** [comment]
In progress https://github.com/mautic/mautic/pull/3460

**Comment by clementdes** [comment]
Hi guys,
can't wait to see that !
Thx for your work ;)
Rgds,
Clement

**Comment by taropaa** [comment]
Can't wait to see this. Right now the focus items are useful but have no chance of surviving in the wild, with the options that are currently available.
