### ISSUE TITLE
IP2Location Errors

### ISSUE THREAD

**Issue by healthstatus** [mautic/mautic#2896]
What type of report is this:

| Bug report? | 

## Description:
Won't update IP2Location database since 2.2 upgrade and throws same error message to log every hour or so.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.2
| PHP version |  7.0

### Steps to reproduce:
1. Configuration screen
2. Select IP2Location Local Bin File
 
### Log errors: 

Error: Call to undefined function IP2Location\bcadd() - in file /root_dir_stuff/vendor/ip2location/ip2location-php/IP2Location.php - at line 983 [] []

**Comment by escopecz** [comment]
I will close this PR in favor of your newer PR: https://github.com/mautic/mautic/issues/3179
