### ISSUE TITLE
Unable to save large campaigns with more than 100 actions

### ISSUE THREAD

**Issue by Tony-Gavin** [mautic/mautic#2899]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | Maybe

## Description:
I am unable to save campaigns with more than 100 decisions / actions. Once 100 is reached, the red / green lines linking decisions actions disappear upon save. Lines linking up to 100 decisions / actions remain. 
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6.27

### Steps to reproduce:
1. Create campaign with minimum of 100 linked decisions / actions.
2. Close campaign builder.
3. Save.
4. Return to campaign builder.
5. Create an additional decision / action.
6. Save.
7. Review saved item - red / green lines linking decision / action will be missing.
 
### Log errors: 

There are no log errors in either Mautic or PH.

**Comment by escopecz** [comment]
This is probably your server limiting POST payload size. Try to raise that limit and it should fix that.

**Comment by carloshenriquemercesmoreira** [comment]
@Tony-Gavin What solved this issue for me was to edit the _php.ini_ file located on _/etc/php/7.0/apache2/php.ini_ (Debian 9 in my case) and increase the value of  the _max_input_vars_ parameter, by default the value was 1000 on my system I increased it to 10000. After this I was able to connect more than 100 edges (actions).
