### ISSUE TITLE
Form checkbox or hidden field enhancement suggestion - don't generate SQL fields

### ISSUE THREAD

**Issue by pitus** [mautic/mautic#290]
I'd like to suggest a new option for a `Form Field`, if it's a **checkbox** and if it's **Required** then there's no point in saving it in the `form_results_###` sql table as it'll always have the same value in it - checked.
Either automatically detect such a scenario and don't bother saving it in SQL or let the user choose if they want to save that field in SQL ... which could also apply to hidden (and potentially other) fields.

We want to add a simple checkbox with a label explaining that the user has to agree to the terms before submitting the form (such as accepting that we will send them a newsletter occasionally)... There's no point in saving this info into SQL but we want that checkbox to be presented and validated (needs to be checked by the user not by default).

For example, I wanted to create a pop-up for the form (which works fine now, and you should consider adding pop-up manager too - I'll see if I can package mine as such and make available) but also show a Confirmation message in the same pop-up when the form is submitted. This can be somewhat done by choosing the **return to form** form action and detecting it in my popup js code...
(I just realized that I can check the appended `mauticMessage` URL parameter and show it so that's great ;)
 
While on the subject of the `checkbox group` - is it really necessary to use the value/label of each checkbox as part of its ID? These values/labels could be quite long so you may want to shorten it (while ensuring uniqueness in any case) or let the user define the value separately from the id and label (especially when we want a short value to be set while showing a long label).
There may also be a use for a checkbox with no label at all but with a value to be set when checked - currently there's no way to add such a checkbox as we're forced to define its label = value.

**Comment by alanhartless** [comment]
I think this was introduced in 1.1.3 or maybe earlier so closing this.
