### ISSUE TITLE
Bug - New Lead reports fail if Company fields selected as data to include

### ISSUE THREAD

**Issue by MarkLL** [mautic/mautic#2900]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Enhancement? |  Maybe

## Description:
The list of fields that are populated in the Data tab for Contacts data source include Company fields. Unfortunately the table prefix "l." is added instead of "comp." which result in a run-time error due to columns not existing.

I found 2 ways of preventing the error. 1st is to filter out all non Lead fields:
Add the following to bundles/LeadBundle/EventListener/ReportSubscriber.php before line 160 (https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/EventListener/ReportSubscriber.php#L160) 

```
if ('lead' !== $f->getObject()) {
    continue;
}
```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.21
| PHP version | 5.6.24

### Steps to reproduce:
1. Create a new report and select Contacts as the data source
2. Click on the data tab. You will see 2 address 1 fields. One is for the Lead/Contact the other is from the Company table. Pick both fields.
3. give it a name and try saving it.
 
### Log errors: 
`[2016-11-06 00:51:04] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT l.companycountry AS companycountry, l.companyaddress1 AS companyaddress1 FROM leads l WHERE l.date_added BETWEEN ? AND ? ORDER BY l.companyaddress1 ASC LIMIT 30 OFFSET 0' with params ["2016-09-01 00:00:00", "2016-11-06 00:51:04"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.companycountry' in 'field list'" at \vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT l.companycountry AS companycountry, l.companyaddress1 AS companyaddress1 FROM leads l WHERE l.date_added BETWEEN ? AND ? ORDER BY l.companyaddress1 ASC LIMIT 30 OFFSET 0' with params [\"2016-09-01 00:00:00\", \"2016-11-06 00:51:04\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.companycountry' in 'field list' at vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.companycountry' in 'field list' at vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.companycountry' in 'field list' at vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:91)"} []`

**Comment by escopecz** [comment]
I don't see contacts address fields in contact report source on Mautic 2.7.0.
