### ISSUE TITLE
FR - UTM source included in form submission

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2903]
| Q  | A
| ---| ---
| Bug report? | -
| Feature request? | -
| Enhancement? | X

## Description:
It would be great that automatically, a mautic form submission take the UTM existing in the current URL (source, medium, etc.). It could be stored in a automatic hidden field.

That way, you'd have the source of the contact in its timeline :-)

**Comment by lsoldado** [comment]
I have this working in 2.2.1
https://github.com/kuzmany/MauticAnalyticsTaggingBundle

But yes, it could be included in new official version :)

**Comment by npracht** [comment]
Hi @lsoldado i've just seen that https://github.com/mautic/mautic/pull/1739 that should answer my request. I guess we can close the issue :)
