### ISSUE TITLE
Internal server error if user deleted dynamic content or variation

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#2916]
What type of report is this:

| Bug report? | 

## Description:
Using latest mautic installed on our server. We had a user deleting the dynamic content default tab in an email. after saving, the user gets 500 internal page error. and can't edit the email again. 
Think its a null exception because you shouldn't be able to delete all dynamic content tab or variations

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
2.2
| PHP version | 
PHP Version 5.6.27

### Steps to reproduce:
1. Create new email
2. save it
3. edit email
4. open dynamic content 
5. delete the default dynamic content
6. Press save,.
7. try to edit, it won't open. try to edit in new tab, you'll see internal server error at the bottom of the page.

**Comment by mqueme** [comment]
This issue was addressed here: https://github.com/mautic/mautic/pull/2813
