### ISSUE TITLE
Modify contact campaign action issue with select fields

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2917]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | -
| Enhancement? | x

## Description:
When you modify contact fields via the related campaign action, you'll notice that is you have select custom fields on your contact, those will be automatically using the first available value of this select field.
**In this case, you cannot update a contact field without having an impact on all select custom contact field values.**

![modify contact field](https://cloud.githubusercontent.com/assets/14075239/20116463/931a3bdc-a5fc-11e6-9143-23825f303a8c.png)

### Steps to reproduce:
1. Create a custom contact (1) field with select type and value A and value B
2. Create a custom contact (2) field with text type format
3. Create a campaign and try to add the action `modify contact` in the view to add the value "test" in the field 2 (text).
4. Notice in the popin that it automatically take the value A in the custom contact field 1.

### Suggestions:
* Automatically an empty row in the top of the select field dropdown list

_or even better_
* Inject the default value of the select field as first row of the dropdown list

**Comment by npracht** [comment]
@escopecz i guess it is not existing nowadays knowing that there is a default value for the select field type now right ?

**Comment by dbhurley** [comment]
Is this still an open issue?

**Comment by dsp76** [comment]
@dbhurley at least the closed #3251which is linked here, but a bit different actually is still broken. 
The problem is even bigger: when I want to store a value "0" in e.g a radio field, the whole form can't be submitted mentioning that "this is a required field". 
Mautic doesn't accept a value "0" as a form field value. Thats a bug.
