### ISSUE TITLE
Custom fields value in detail of contact

### ISSUE THREAD

**Issue by onconcz** [mautic/mautic#2924]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
I create new custon fields type boolean. When I edit this coustom fieltds in detail of contacts, it don't save and I must set and save it more times. 

Video of this problem is here: https://www.youtube.com/watch?v=O3EJkf8Mdwo&feature=youtu.be

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.2.1
| PHP version |  PHP Version 7.0.10-1~dotdeb+8.1

### Steps to reproduce:
In Video
 
### Log errors: 
No error in logs.

**Comment by escopecz** [comment]
Various boolean field bug fixes are ready to test in https://github.com/mautic/mautic/pull/4609
