### ISSUE TITLE
Remove mail track

### ISSUE THREAD

**Issue by mateusw3c** [mautic/mautic#2927]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes
| Enhancement? | 

## Description:
Add option to not track all mail links

**Comment by kuzmany** [comment]
Dou you mean disable tracking links? 
You are able to disable tracking image pixel from configuration.

**Comment by mateusw3c** [comment]
@kuzmany Does not work. Keep going to Mautic before accessing the link.

**Comment by MxyzptlkFishStix** [comment]
I think you have to add the "mautic:disable-tracking" attribute to your links.
