### ISSUE TITLE
Form radio buttons didn't change

### ISSUE THREAD

**Issue by RC-pointfull** [mautic/mautic#2935]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  No
| Feature request? | No 
| Enhancement? |  No

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.2.1
| PHP version |  7

Hello! I'm with a problem customizing my form. I followed the steps here https://developer.mautic.org/#form.html.twig, so i created a folder called "MauticFormBundle" in my custom theme "[customName]/html/". Then i put two new folder inside, "Field" and "Builder".

Now i copied all files inside "app/bundles/FormBundle/Views/Builder/" to my custom theme folder "Builder" and the same for this folder "app/bundles/FormBundle/Views/Field/" to my custom theme folder "Field".

I tried change the file "form.html.php" inside my custom theme "Builder" and the changes reflected, so ok.
Then i tried to change "group.html.php" inside of my custom theme "Field" and the changes didn't reflected. And that is my problem.

When i tried to change the file in this folder "app/bundles/FormBundle/Views/Field/group.html.php" the changes refleced but in a future update this will be erased once this is a root folder of Mautic.

**Comment by karser** [comment]
I encountered the same issue. It's not a bug but undocumented feature. If you want to override `group.html.php` you need to prepend the path with your theme name, e.g: `<your-theme>|MauticFormBundle:Field:group.html.php`

Full example:
```php
echo $view->render(
    'custom-theme-1|MauticFormBundle:Field:group.html.php',
    [...]
);
```

**Comment by mayanktiwaridotcom** [comment]
Thank you @karser this saved me !
Also for everyone, file group.html.php includes another file called field_helper.php, please ensure to copy that one also else it won't work. However it may be obvious but sometimes we miss small things.
