### ISSUE TITLE
Cloning Email Destroys Dynamic Content

### ISSUE THREAD

**Issue by Loanatik** [mautic/mautic#2937]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## If a bug:
If you clone an email, any dynamic content will show up in the dynamic content tab as "[object Object]"

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
See #2813, test and report your tests to that PR.

**Comment by Loanatik** [comment]
We're not quite there yet.  If you create a new email and save it.  Then go back into the email and select dynamic content, put a field reference in variation 1 and save the email.  When you go back to dynamic content the default text is set to [object] [obeject].  If variation 1 is set to plain text it works fine.

**Comment by escopecz** [comment]
This should be fixed by now.
