### ISSUE TITLE
PluginController will never invoke onPluginInstall/Update

### ISSUE THREAD

**Issue by k127** [mautic/mautic#2938]
| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | no
| Enhancement? | no

CC: @alanhartless (2ef76b3d8e695f42bec628c990e807870bbf9b66)

### `$namespace`

[`PluginController`, L. 435](https://github.com/mautic/mautic/blob/2.8.1/app/bundles/PluginBundle/Controller/PluginController.php#L435) there's this call:

```php
$namespace = $meta->fullyQualifiedClassName('');
```
…which, for `doctrine/orm:v2.5.5`, **always** returns `''`:

```php
public function fullyQualifiedClassName($className)
    {
        if (empty($className)) {
            return $className;
        }
        // ...
    }
```
…therefore, the condition `strpos($namespace, 'MauticPlugin') !== false` always evaluates to _false_.

### `$bundleName`

Also, in [`PluginController`, L. 438](https://github.com/mautic/mautic/blob/2.8.1/app/bundles/PluginBundle/Controller/PluginController.php#L438), `$bundleName = str_replace('\Entity\\', '', $namespace);` needs to be reviewed.
Since `$namespace` ends with `'\Entity'` rather than `'\Entity\\'`, `str_replace()`'s 1st argument needs to be adjusted.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1 - app/prod
| PHP version | 5.6.26
| `doctrine/orm` version | v2.5.5

### Steps to reproduce:
1. choose a plugin that contains database entities and make sure it is not present in Mautic `plugins/` folder
1. clear Mautic DB
    1. `rm -rf app/cache/prod/`
    1. `./app/console doctrine:schema:drop --force`
    1. `./app/console doctrine:schema:create`
    1. `./app/console doctrine:fixtures:load`
1. at this point, there has already an error being logged, see below
1. copy your plugin to `plugins/`
1. update plugins by getting `/s/plugins/reload`
1. check if schema changes have been applied to the database (**they'll be missing**)
1. there has been no further log output so far
 
### Log errors: 

Output after following reproduction steps, but probably not directly related to this issue. Seems more of a fixtures ordering problem:

`mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_dev.lead_fields' doesn't exist [] []`

**Comment by vollossy** [comment]
Yeah, that's error affected me too.

**Comment by KJURKOWSKIHCS** [comment]
Hi @escopecz , I just experienced that error in 2.9.0 upon a fresh install, do you know if anyone else has as well?

Error same as above:

mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_dev.lead_fields' doesn't exist [] []

**Comment by escopecz** [comment]
See https://github.com/mautic/mautic/issues/3436
