### ISSUE TITLE
Project Management: Contacts/segments/etc belonging to Projects (Manage all Mautic attributes i.e. conacts/segments/etc. for separate marketing projects on one single Mautic installation)

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#2941]
| Q  | A
| ---| ---
| Bug report? | |
| Feature request? |  x |
| Enhancement? |   |

## Description:
Feature request:  Creating and displaying Projects on a single Mautic installation. Projects are a collection of specific contacts/segments/campaigns/etc (all items would belong to a specific Project).

This way you don't have to install multiple instances of Mautic on a new server & domain for every marketing project.

Administrators can create Users that only have access to manage particular Projects (with limited abilities, configurable in Roles).

When selecting a Project, you'd only get to view and manage the data for that particular project. 

**Example:**
I have a website called 'Site A', I want to view and manage only the contacts, segments, campaigns, reports etc. for Site A. I create a Project on my Mautic installation for `Site A`, allowing me access to only the contacts/campaigns etc. belonging to the Site A project.
I then create a new project called Site B. When I select Site B in Mautic, I can manage only the data regarding to Site B.
I then create a Mautic user account and assign it to Site B. When I log in to that user account, that user account only has access to Project `Site B`. All campaigns and segments created on that account would belong to `Site B`.

**Comment by escopecz** [comment]
There are similar feature requests: https://github.com/mautic/mautic/issues/4676, https://github.com/mautic/mautic/issues/4353 but they call your projects folders or global categories. I'll close this feature request as duplicate.
