### ISSUE TITLE
Configuration pages never load

### ISSUE THREAD

**Issue by DrakkenSaer** [mautic/mautic#2943]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? |  No
| Enhancement? |  No

## Description:
I am unable to load any configuration page. Originally I was getting the error mentioned in here: https://github.com/mautic/mautic/issues/2532

I used composer to update all dependencies. Now I'm getting the same problem, but there is no error message at all. Getting "502 Bad Gateway" as a response. Not sure if it matters, but I am using Cloud9 with a WordPress application.

## If a bug:
| Q   | A
| --- | ---
| Mautic version |  2.2.1
| PHP version |  7.0.12-1+deb.sury.org~trusty+1

### Steps to reproduce:
1. Install Mautic
2. Navigate to any configuration page

### Log errors: 
There are no error logs from either the server, or Mautic.

I'm not exactly sure where to start. Beyond updating dependencies, I have done no troubleshooting (it's a little difficult to figure out where to start with no error message). Is anyone else experiencing this problem?

**Comment by escopecz** [comment]
Try to look into all error logs described here: https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by DrakkenSaer** [comment]
I meant to close this a while ago. I reinstalled Mautic from a fresh installation, not sure what the problem was, but it is fixed now.
