### ISSUE TITLE
Twig not working in dynamic content

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#2944]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x|
| Feature request? | x|
| Enhancement? | |

## Description:
Using a twig tag i.e. `{contactfield=firstname}` in a Dynamic Content field in an Email, returns just plaintext `{contactfield=firstname}` rather than the actual user's first name.

I want to fall back to different saved names i.e. if `firstname` is empty, show `username`. This requires me to return data from twig tags inside dynamic content.

**Comment by kuzmany** [comment]
See #2819, test  and report If it works.
