### ISSUE TITLE
Customize unsubscribe page

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#2946]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | -
| Feature request? | -
| Enhancement? | indeed

## Description:
It would be great to be able to customize unsubscribe page in the view to make it more corporate that the default landing page.

## Recommendations:
1. Create a landing page in the landing page builder, let's use native features :-)
2. In the email setting panel, set instead of text, a custom landing via drop down list and select your created LP
2bis. Do it in the email edition page in the right hand part.

Could be manage at the same time as https://github.com/mautic/mautic/issues/873 ?

**Comment by kuzmany** [comment]
👍

**Comment by YosuCadilla** [comment]
Hi guys, sorry for bringing this old thread up, has there been any advancements regarding customizing the default unsubscribe page without using a preference center?

**Comment by npracht** [comment]
Yes it depends on your default theme. If you change it, it'll change that page.

**Comment by YosuCadilla** [comment]
OH! thanks a lot @npracht 
That makes a lot of sense!, let me test it out...

Just for reference, as this pops up in Google if you search for "mautic edit unsubscribe page"
This is the best alternative resource I found:

https://medium.com/@NinJoan/simplest-way-to-make-a-unsubscribe-system-for-mautic-4f307850cce2
