### ISSUE TITLE
SQL error when calling API on cloud

### ISSUE THREAD

**Issue by TiagoGouvea** [mautic/mautic#2953]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I called `$contactApi->getList('segment:lead-hangout-aprender-programacao',0,1000);` from cloud api and it give me:

`
array(1) { ["error"]=> array(2) { ["message"]=> string(617) "An exception occurred while executing 'SELECT COUNT(DISTINCT(l.id)) as count FROM mautic_leads l LEFT JOIN mautic_users u ON u.id = l.owner_id INNER JOIN mautic_lead_lists_leads list_lead ON l.id = list_lead.lead_id INNER JOIN mautic_lead_lists list ON list_lead.leadlist_id = list.id WHERE ((list_lead.manually_removed = 0) AND (list.alias LIKE ?)) AND (())' with params ["lead-hangout-aprender-programacao%"]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))' at line 1" ["code"]=> int(500) } } 
`

Cloud version

**Comment by beefaaubee09** [comment]
Did you execute this SQL Query in DB other than fetching it from API? Try it and it might would help you debug this issue

**Comment by TiagoGouvea** [comment]
No. I just call the API over the php library like that:

`$contactApi->getList('segment:lead-hangout-aprender-programacao',0,1000);`

And got that sql error as return.

When I call getList with another search, it work well. But when calling with that segment it fails.

**Comment by vollossy** [comment]
Agreed, faced same issue

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/3101
