### ISSUE TITLE
Campaign Conditions box uses Select field's label instead of value

### ISSUE THREAD

**Issue by deskstorm** [mautic/mautic#2956]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
In campaigns, using a Conditions box, the campaign doesnt work properly if your field is a "select" field. The condition will always be false. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6

### Steps to reproduce:
1. Campaign Builder
2. Add source
3. Use conditions box
4. choose a field that uses a "select" field type in the form
5. choose the select option (example: fieldname | equals |  Option1 )
6. add action : example: add 400 points
7. trigger campaign
8 campaign doesnt fail, but nothing happens

I spent 2 hours of trials...
On the conditons box, the box shows the label for the select field and sets the label as the expected value. To bypass the issue, i created a select field where the label and value were the same and the campaign ran fine!

So if the Create Conditions box can set the value of the select field relative to the Label it grabs, would be great

**Comment by alanhartless** [comment]
This is not reproducible in the latest version of Mautic so I think it's been resolved. Can you test and if not, let us know and we'll reopen.
