### ISSUE TITLE
More Documentation - Developer Documentation

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#2958]
I'd really appreciate some more documentation on mautic!

## User Documentation

I'm missing docs eg. on:

- how to update mautic
- which cronjobs are required
- How is mautic tracking #2406 

## Developer Documentation - Hard to get startet contributing to mautic!

I'd like to mention, in my humple opinion, I think the **code should get some more documentations,** since it is **really hard for a developer to get started and figure out which parts of code are doing what**. This makes it really hard contributing to this project.

eg. which modules are responsible for:

- some basic description on app design
- lead track (pixel) generating, merging, ...
- email sending

I really appreciate everyones work on this project! Sorry for not making any pull request. I'm still a little bit out of time since I'm working on a startup thus cannot dig deeply into the code for now.

**Comment by RCheesley** [comment]
Hi @manuelfink if you join the docs channel on Slack, there are a few of us who try to contribute to updating the docs.  Several sections need some attention that's for sure.  It's always helpful to have newcomers give input on what is missing, as it's easy for folk who have their head in Mautic to forget what it's like just coming into the project!  I'll try to put aside some time at the end of the week to write up the part about cron jobs and updating.

**Comment by isleshocky77** [comment]
I put in the following issue in as well #3281 I would say these two issues are closely related.

**Comment by escopecz** [comment]
Thanks for the input!

I'll close this issue since each documentation have its own repository. Please, create the suggestions to the right repository:

https://github.com/mautic/documentation
https://github.com/mautic/developer-documentation

**Comment by isleshocky77** [comment]
Nice. I had no idea developer.mautic.org existed. I'll see what I can add to help.
