### ISSUE TITLE
Allow social post with attached image/video

### ISSUE THREAD

**Issue by stevegrant1983** [mautic/mautic#2962]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
For campaigns which include a social post (I am using Twitter as the example, but could equally apply to others), it should be possible to attach an image (or video, I guess) to the post. Currently, the system allows a Mautic asset to be added, but this only adds a link to the asset, not fully embedded.

For Twitter, this should use the media/upload POST API method: https://dev.twitter.com/rest/reference/post/media/upload

**Comment by Mazzim** [comment]
+1
Tweets with a picture/video has a higher engagement
