### ISSUE TITLE
Documentation API "Company"

### ISSUE THREAD

**Issue by victorkoopman** [mautic/mautic#2965]
What type of report is this:

| Q  |
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Y

## Description:
Account Based Marketing is a big new feature within Mautic. We use a tool to identify companies which works very well and have asked the manufacturer to look into the possibility to connect it with Mautic through API. Seems that 'company' (according the api documentation) is not a field that can be accessed. 
My questions are: is it already possible to fill the company field dynamicaly through API request? Is there updated documentation on it?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors:

**Comment by zenzozen** [comment]
Hello! Seems that some people are working on that. ( @escopecz @LAN-Laurene @alanhartless @Dcoutelle ) . But dont know the release date.

See https://github.com/mautic/mautic/pull/2738

**Comment by escopecz** [comment]
Documentation for API companies endpoint: https://developer.mautic.org/#companies
