### ISSUE TITLE
Bad Message Number for IMAP Resource bounce processing

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#2966]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Errors reported when running fetch mail from an IMAP resource:

```
PHP Warning:  imap_fetchheader(): Bad message number in /var/www/html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 851
PHP Notice:  Undefined property: stdClass::$from in /var/www/html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 860
PHP Notice:  Trying to get property of non-object in /var/www/html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 860
PHP Notice:  Undefined property: stdClass::$from in /var/www/html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 860
PHP Notice:  Trying to get property of non-object in /var/www/html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 860
PHP Warning:  imap_fetchstructure(): Bad message number in /var/www/html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 891
PHP Warning:  imap_body(): Bad message number in /var/www/html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 936
PHP Notice:  Trying to get property of non-object in /var/www/html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 938
PHP Notice:  Trying to get property of non-object in /var/www/html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 940
PHP Notice:  Trying to get property of non-object in /var/www/html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 942
PHP Notice:  Trying to get property of non-object in /var/www/html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 944
PHP Notice:  Trying to get property of non-object in /var/www/html/mautic/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php on line 951
```

Possibly related to #1885 which has no resolution due to inactivity.

Upgraded to most recent Mautic version to address.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 7.0.9

### Steps to reproduce:
1. Configured to check for bounce messages on IMAP Resource
2. `php app/console mautic:email:fetch`
3. Get numerous errors when processing SNS Bounce notification emails for AWS SES.
 
### Log errors: 

* Nothing relevant in error logs besides direct output from what is posted above.

**Comment by jordan8037310** [comment]
Shortly followed after the above errors, these are returned to the screen on the cron job:

```PHP Notice:  Unknown: User is authenticated but not connected. (errflg=2) in Unknown on line 0
PHP Notice:  Unknown: IMAP protocol error: User is authenticated but not connected. (errflg=2) in Unknown on line 0```

I assume this is the script timing out on the IMAP connection, as we're processing a good number of bounces.

**Comment by jordan8037310** [comment]
Our current theory is that this issue is caused by a timeout with the IMAP provider. The connection is authenticated but Oauth probably times out after processing so many unreads.

**Comment by billybobilly** [comment]
I have been trying resolve this and have come to the conclusion that it is a PHP-IMAP extension problem.  I can write a python script and get the message id's, headers, etc and when I compare the message id's with the ones that mautic is trying to use when it calls imap_fetchheader(), they are the same.  I also replaced the mautic section that handles getting messages with a hard coded connection and imap_fetchheader() call and it causes the same error.  That leads me to believe it's a problem with imap extension.  

I'm using PHP 5.6 and IMAP 2007f on an Ubuntu 14.04LTS server.

**Comment by billybobilly** [comment]
so, in php5.6 ext/imap/php_imap.c  there is this code in each of the imap methods:

       if (!msg || msg < 1 || (unsigned) msg > imap_le_struct->imap_stream->nmsgs) {
                php_error_docref(NULL TSRMLS_CC, E_WARNING, "Bad message number");
                RETURN_FALSE;
        }

My email server assigns a sequential number as the message number, but it is a large number, such as 13126 even though there are only 100 messages in the mailbox.  So, this code seems to reject when the message id is larger than the number of messages in the box.  

I'm going to try to re-compile PHP5.6 from source and see what happens.  Stay tuned.

**Comment by billybobilly** [comment]
Confirmed that it was the problem.  My email server was keeping deleted messages laying around, so I had to purge deleted messages from the inbox.  That set the sequence to just the undeleted ones.  Solved.  No need to alter php, although I'm not sure that PHP should have that restriction in it.
