### ISSUE TITLE
Mautic Form submission emails sent automatically set customer email adr in reply-to

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#2967]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
We setup a basic form to let our use download a whitepaper
the results/actions of this form is to send an email to our internal mailing list leads@company.com

in this email we only printed "a new lead submitted the form to download the white paper" + the variables names + their values

Of course, this email is not sent to the customer and is just for internal purposes.

The sender of the mail is the one defined in Mautic Configuration > email settings, this is ok. But mautic adds the customer email address (defined in the form to download the white paper) as the reply-to email.

Thus when one of our sales team representative is reading the email from the mailing list he could want to quick answer to all the team "I deal with this one" but if he hits reply, the answer will be sent to the real customer not the team.

Why mautic is adding the customer email as reply-to ? how can we prevent that behavior (that really seems a bug for us)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 7.0.12

**Comment by RCheesley** [comment]
Hi @YannickBiet here's an option to set the reply-to when using a regular email, under the advanced section:

![reply-to-email](https://cloud.githubusercontent.com/assets/2930593/20479929/1eec31a8-afd8-11e6-8018-337f82372ae6.png)

I believe this would force the behaviour you are looking for - to reply to your internal mailing list. I don't believe we have the option on the send form results action, maybe a feature request is needed there?

**Comment by YannickBiet** [comment]
No i am talking about this section :
Components > Form > MyForm > Actions > Send an email popup window

There's no reply-to options here. We are sending the email to internal teams but the customer email is set on reply-to

![2967](https://cloud.githubusercontent.com/assets/930391/20480049/22ece474-afe1-11e6-87be-5335e5323fef.PNG)

**Comment by RCheesley** [comment]
@YannickBiet indeed, which is why I raised #2984 - currently there is no option to force the reply-to address.  As a workaround you can create an email (rather than use the send form results) with exactly the same info, and send to your mailing list, which would allow you to force the reply-to address.

**Comment by YannickBiet** [comment]
I don't know if it is a feature request more than a bug, why the customer email address should be added as reply to option inside a submission form's sent email ? (not sure of my english on the last sentence ;))

that's why I filled a bug issue more than a FR

**Comment by YannickBiet** [comment]
Ok we found out that this was directly hardwritten in code (with an explicit comment that this is convenient this way [sic])

we will fix and try to extend the functionnality by asking the user in the action if he wants to have the contact in reply to.

**Comment by escopecz** [comment]
Added to 2.13.0

**Comment by sayantannag** [comment]
I am facing the same issues from previously & searching the solutions eagerly. Can you guys please share any update on this.

**Comment by YannickBiet** [comment]
fixed in 2.13 if changelog is ok

**Comment by sayantannag** [comment]
Why mautic is adding the customer email as reply-to? How can we prevent that behavior from "Components > Form > MyForm > Actions > Send an email" popup window. I just don't want the customer email ID open like this way to the internal representative's team.
