### ISSUE TITLE
Incorrect form fields' mapping result in internal server error for the end customer

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#2968]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
We setup a form with fields name, first name, company's name, and number of employees
We decided to change the number of employees field on the form : from an integer we choosed a "select" field and defined the ranges 0-10 10-20 20+

Our admin has linked the select field to the core default number_employees of the contact module.

There's no check on the backoffice, nothing is checking if the setup is ok or has problems.

We then saved the form

As it was already in production we tried to check the form and fill in all the fields.
While pressing the submit button, the button turns to "please wait" and any execution breaks here.

the JS console show a 500 internal server error and we add errors in the mautic log (show below)

We think that mautic should check the settings and mapping in the form edit screen to minimize any risk of fatal errors in production environment.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 7.0.12

### Log errors: 

 mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'UPDATE leads SET fonction = ?, firstname = ?, lastname = ?, company = ?, email = ?, phone = ?, number_of_employee = ?, attribution_date = ? WHERE id = ?' with params ["Direction_director", "Test", "test", "test", "thibaut@test.fr", "38000", "1-50", null, 8688]:  SQLSTATE[01000]: Warning: 1265 Data truncated for column 'number_of_employee' at row 1" at /var/www/mautic/www_prod/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'UPDATE leads SET fonction = ?, firstname = ?, lastname = ?, company = ?, email = ?, phone = ?, number_of_employee = ?, attribution_date = ? WHERE id = ?' with params [\"Direction_director\", \"Test\", \"test\", \"test\", \"thibaut@test.fr\", \"38000\", \"1-50\", null, 8688]:\n\nSQLSTATE[01000]: Warning: 1265 Data truncated for column 'number_of_employee' at row 1 at /var/www/mautic/www_prod/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 01000): SQLSTATE[01000]: Warning: 1265 Data truncated for column 'number_of_employee' at row 1 at /var/www/mautic/www_prod/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 01000): SQLSTATE[01000]: Warning: 1265 Data truncated for column 'number_of_employee' at row 1 at /var/www/mautic/www_prod/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"}

**Comment by YannickBiet** [comment]
please note we understand of course that the product can't store any string "x-y" inside an integer column but shouldn't this be managed by the product directly ?

**Comment by dbhurley** [comment]
Is this still an open issue in the latest 2.11 release?
