### ISSUE TITLE
FR - Compare field values in Campaign Conditions

### ISSUE THREAD

**Issue by medianicus** [mautic/mautic#2972]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
When basing a condition upon a form field, the campaign conditions require you to enter a 'static' value for the Value. It would be very useful if the Value for comparison could actually be the value of another field.

For example, I have two custom fields, _Score Assigned_ and _Score Entered_. 
- _Score Assigned_ is a contact field that is entered manually by the Mautic admin and varies from contact to contact.
- _Score Entered_ is a form field that gets populated automagically when a contact takes a test. 

I want to be able to set a campaign condition of: _Score Assigned | is greater than | Score Entered_. If true, email 1 gets sent, if false, email 2 gets sent and the contact is transferred to another campaign.

Ideally, there would be multiple options available:
- Form Field | Operator | Contact Field **or** Form Field **or** Value

and the same comparison could be added for conditions based on a contact field:
- Contact Field | Operator | Contact Field **or** Form Field **or** Value

This would also allow a simple form of validation of data entered, for example on a form which asks for the same data twice (_Form Field 2_ | _Equals_ | _Form Field 1_) , or when a contact updates their information through a form (_Contact Field 1_ | _Is Not Equal To_ | _Form Field 1_).

**Comment by jstawski** [comment]
Was this implemented? This is a must have as I need to do the same thing by comparing two dates: when the user registered vs when they last came back. Both fields are stored as Contact Fields
