### ISSUE TITLE
Campaign chart mistakenly showing all follow-up sent emails as opened

### ISSUE THREAD

**Issue by stevegrant1983** [mautic/mautic#2976]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When a campaign is built to send a follow-up email, the follow-up emails are incorrectly charted as "opened" rather than "sent".

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 7.0.8-0ubuntu0.16.04.2

### Steps to reproduce:
1. Create a new campaign using the builder, with a conditional action to send a follow-up email if the original email has not been opened by a given date/time combination.
2. When that date/time passes, any user who has not opened the original email will receive a follow-up email. In the "Actions" tab on the campaign page, this is correctly listed as a "Send Email" action, but in the chart above they are displayed as "Email is Opened" actions.

![image](https://cloud.githubusercontent.com/assets/14789786/20429926/70a82c5a-ad89-11e6-98ff-c0d0bb2a7584.png)

**Comment by MaxWebmecanik** [comment]
+1 I noticed the same issue
