### ISSUE TITLE
Conditions in the Segment Filters fail when set using boolean fields.

### ISSUE THREAD

**Issue by blueflamexr** [mautic/mautic#2978]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Conditions in the Segment Filters fail when set using boolean fields.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6.22

### Steps to reproduce:
1. Create a new segment
2. Apply a segment filter using a contact field of type: boolean
3. Filter doesn't work. It doesn't recognize the boolean. This occurs even when there are no null values in the records for the boolean field.

For example, my contacts have a boolean field for "Current Customer." All records have either a 0 or 1 value in the database for the Current Customer field. I create a new segment. Here are the results of the filter when it is applied using the front-end UI:
- When I apply the segment filter so that if the "Current Customer" is equal to "yes," the logic fails.
- When I apply the segment filter so that if the "Current Customer" is equal to "no," the logic fails.
- When I apply the segment filter so that if the "Current Customer" is not equal to "yes," then all customers are added to the segment (regardless of the value of the "Current Customer" field).

**Comment by escopecz** [comment]
Will be fixed in 2.3
