### ISSUE TITLE
Browser specific "Email read" tracking pixel problems

### ISSUE THREAD

**Issue by Getron** [mautic/mautic#2989]
What type of report is this:

| Bug report | 

## Description:
I have tested my mautic 2.2.1 on several way, but, what i have see, that the tracking pixel has problems to work on firefox.

## If a bug:

For Example, i send an email to hotmail email. If i open the Chrome, go to hotmail (or Outlook.com), open email, the "Email was first read on..." is working, it shows the opening time, etc.

But, if i send an email, and go to hotmail with Firefox, open that email, the "Email probably had not been read yet." - the pixel is somehow not see that i have opened, or read the email.

Have tested on several PC's, the same problem. Seems that is somthing missed to tracking pixel, to work ok with firefox to.

This seems just for reading email problem to be. If i click on links on email, it shows me that i have clicked, shows the IP, all other tracking functions seems to work ok, just opening mails hjas this problem.

The same problem, if i test the pixel, for example, direct opening the url on chrome:
http://mautic.example.com/email/58355cee0b5f8.gif   - it works, it is just a blank page, but, on Mautic CP shows, that email was opened.

But, the same url in Firefox, it doesn't works, it shows the "Uh-Oh page, internal 500 error..."

| Mautic version 2.2.1 | 
| PHP version 7.0 | 

### Steps to reproduce:
1. Send email to hotmail or gmail
2. open it with chrome - it works, it shows that it was opened, or read.
3. Send the same email one more time
4. Open it with Firefox - doesn't shows that the email was opened or read, but, clicking on the links and IP it shows ok, just not showing that the email was read.
5. Test it on more than one PC, the same problem there.

**Comment by godfrey-obinchu** [comment]
This is definitely a bug, i have the exact same problem and was able to replicate, I am able to register the clicks  from Chrome, but not Firefox.

**Comment by millionleaves** [comment]
Just encountered this with the website tracking pixel in Firefox on 2.6.1. The pixel works fine in Chrome.
