### ISSUE TITLE
Exposing to the Internet only files / pages required for the application to work

### ISSUE THREAD

**Issue by diderich** [mautic/mautic#2990]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  Y
| Enhancement? | 

## Description:
It would be great if the software / files / directories could be restructured in such a way that only (a small)  part of it needs to have Internet access (callbacks, forms, ...), whereas the remainder of the application can be hidden from the outside world and only made accessible on the Intranet.

This could, for example, be made possible by moving all relevant files that need to be publicly accessible in a dedicated directory, e.g., public, such that only this directory is made available on the internet and the rest of the application is restricted to the intranet (e.g. through <Directory> configurations when using apache2).

**Comment by escopecz** [comment]
The current file structure was designed the way that Mautic could run on shared hosts. Suggested change would make that impossible.
