### ISSUE TITLE
Page break on forms is not allowing fields to be re-ordered above it

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#2991]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Hopefully a fairly simple one.  If I create a form with fields, and then I put a page break in, I can't re-order the page break to be in the middle of existing fields, it just sits at the bottom.

Likewise, if I have a page-break mid way through the form, and I need to add a heading or extra fields above the page break, it appears to allow you to do this but on save the fields are back at the bottom of the form again.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6.28

### Steps to reproduce:
1. Create a form with multiple fields, then add a page break and try to move it up into mid-way down the fields.  Apply, and the page break lands back at the bottom
2. With a page break already in place mid way through a form, add a new field and try to move it above the page break.  It does not allow the field to be positioned above the page break.

I did a screencast here https://www.youtube.com/watch?v=E2rINh9hAhI

**Comment by mqueme** [comment]
This was a bug addressed here: https://github.com/mautic/mautic/pull/2882
