### ISSUE TITLE
Focus items do not seem to support multi-page forms [$50]

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#2992]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | x
| Enhancement? | 

## Description:
I created a multipage form which I wanted to emulate the behaviour of a Hotjar poll - asking for quick feedback and an option to give contact details on second form.

When creating the form, it works fine in preview with two pages.  When used as a data capture form in the context of a focus, however, it does not - the contact details are rendered all in one display and not as a multi-page form.

![multi-page-form-mautic](https://cloud.githubusercontent.com/assets/2930593/20568941/25bce558-b196-11e6-83dd-9021a800a930.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6.28

### Steps to reproduce:
1. Create multi-page form
2. Create focus item for data capture, assign form
3. Form is displayed in one screen, rather than multiple pages

**Comment by infinite-l00p** [comment]
I'm getting this bug as well. I'll dig in the code to find a solution.
I think the problem lies in the fact that the focus bundle uses a different way to render form vs. the way the Form Bundle does

**Comment by RCheesley** [comment]
That moment when you find your old bug from 2016 is still a bug in 2019 😱 

Tested with 2.15.3 and it seems that this is still happening in focus items for multi-page forms.  Not clear how much work would be needed to refactor #5116 to bring it up to date.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.1.0 which is the latest version ? Thanks for your feedback.

**Comment by RCheesley** [comment]
Seems this is still an issue - maybe someone could take inspiration from the old closed PR #5116 to address this?

**Comment by RCheesley** [comment]
Still an active issue :)

**Comment by kuzmany** [comment]
I can take it. Any additional bounty welcome :)

**Comment by kuzmany** [comment]
Fixed https://github.com/mautic/mautic/pull/9737
Please test
