### ISSUE TITLE
Leads & Lists or Contacts & Segments?

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#2993]
What type of report is this: Bug report

## Description:
The more details the better...
![image](https://cloud.githubusercontent.com/assets/10385295/20575748/b69a5178-b20e-11e6-8651-5f401925b3ca.png)
In the interface of our Mautic install, it's always shown Leads and Lists, never Contacts and Segments. Everything works normally(I think), just the labels are old.

Why is this?

Mautic 2.2.1
PHP7.0
 
### Log errors: 
Nothing populates in the error log for Mautic or Apache about this issue

**Comment by escopecz** [comment]
What language do you use in the configuration?

**Comment by zstephen** [comment]
I use English (UK)

I just checked English (US) and the terms are correct.

**Comment by escopecz** [comment]
Ok, we found the problem. If you'd like to use correct terms, please, update them at https://www.transifex.com/mautic/mautic/dashboard/
