### ISSUE TITLE
Create New Segment causes 500 Internal Server Error and app/log has error similar to issue#1768

### ISSUE THREAD

**Issue by junaidfarooqi** [mautic/mautic#2994]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
User has been created and assigned to a ROLE with FULL permissions for CONTACT and SEGMENTS, however when logged on as the user and tried to create a NEW user the following error is logged. 
mautic.ERROR: Error: Call to a member function getId() on null - in file .../apps/mautic/htdocs/app/bundles/EmailBundle/Entity/EmailRepository.php - at line 324 [] []

NOTE: I am able to create Segments as a Super User/System Adiministrator

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2
| PHP version | [2016-11-23 15:42:39] mautic.ERROR: Error: Call to a member function getId() on null - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/Entity/EmailRepository.php - at line 324 [] []

### Steps to reproduce:
1. Create a ROLE
2. Assign Permissions FULL  to CONTACTS, SEGMENTS, and the MANAGE
3. Create User and Assign the created Role
4. Login as User and add contacts
5. Click on Segments and Click on NEW to create a Segment
6. Enable browser console/debugger and verify the following error 
"status 500, Internal Server Error"
7. SSH to mautic server and check logs under app/logs and verify the following error

mautic.ERROR: Error: Call to a member function getId() on null - in file .../apps/mautic/htdocs/app/bundles/EmailBundle/Entity/EmailRepository.php - at line 324 [] []

This error is similar to the one reported earlier in the issue below and I dont think it was closed with sufficient information
https://github.com/mautic/mautic/issues/1768
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

app/logs
[2016-11-23 15:42:39] mautic.ERROR: Error: Call to a member function getId() on null - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/Entity/EmailRepository.php - at line 324 [] []
Status: 500 Internal Server Error
Browser:
Connection: close
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Thu, 24 Nov 2016 01:17:57 GMT
Server: Apache
Vary: Cookie
X-Frame-Options: SAMEORIGIN
X-Mautic-System-Error: The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator. System administrators, check server logs for errors.
X-Powered-By: PHP/5.6.23

Server Log:

[Thu Nov 24 01:19:20.086428 2016] [proxy_fcgi:error] [pid 1541:tid 140649281931008] [client 73.202.62.241:50518] AH01071: Got error 'PHP message: PHP Fatal error:  Call
 to a member function getId() on null in /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/Entity/EmailRepository.php on line 324\n', referer: http://myserver_hosting/mautic/s/segments

**Comment by apuestaya** [comment]
Any fix for this? thanks for this great program

**Comment by escovici** [comment]
Confirm problem. When User role has any kind of permission on Segments, the user can access the Segments but the attept to create a new segment throws the PHP Fatal error

If no permission is granted on Segments, the user cannot access Segments and in logs a segfault is thrown:

> [pid 1832] AH00052: child pid 1840 exit signal Segmentation fault (11)

**Comment by dongilbert** [comment]
Fixed in #3627. Thanks @junaidfarooqi!
