### ISSUE TITLE
Emoji support in text editor

### ISSUE THREAD

**Issue by Nizzlay** [mautic/mautic#2996]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
Would be great if we could have an emoji picker in the text editor.

Found two open source Emoji sets
- https://github.com/Ranks/emojione
- https://github.com/twitter/twemoji

**Comment by Nizzlay** [comment]
By the looks of it froala already has support for emoticons. Any way we could enable that for Mautic?
https://www.froala.com/wysiwyg-editor/examples/custom-emoticons

**Comment by escopecz** [comment]
It's just about enabling the Emoji button. We discussed this when Froala was being implemented. We had to choose which editor buttons to use to make the editor bar short. Emoticons didn't make the cut. We couldn't find a good use case for it. Let's see how many Mauticans will want to add it.

The question is, if we add the Emoticons button, which button will we remove instead?

**Comment by Nizzlay** [comment]
Hm.. I personally have plenty of space left: https://postimg.org/image/r2tg6r559/
And in the builder the buttons are spread over 2 lines, so enough space there as well.

**Comment by Nizzlay** [comment]
Also: When I resize the window the buttons move to a 2nd row when there's not enough space.
