### ISSUE TITLE
Select Custom Fields with option values containing quotes cause bugs

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#2997]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | X

## Description:

![localhost-8002-s-contacts-fields-new](https://cloud.githubusercontent.com/assets/18265735/20594751/ab61ddde-b237-11e6-84f3-db9a2be8fcff.png)

If the user creates a custom field of type _select_ with quotes in an option's value, a lot of things will break around that value such as:
- Creating a new contact with that option selected (validation error)
- Segmenting on that option (will never evaluate as equal)

### Possible solutions

- Limit user input to alphanumeric for options' values
- Track down the cause of all the bugs caused by quotes in such cases (I suspect it would all come down to using the right escape function)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | `2.2.1`
| PHP version | `5.6.28`

### Steps to reproduce:
1. Create a custom field of type _select_
2. Give it an option where the value contains a quote
3. Segment on that option
4. Check that the segment is not properly populated

**Comment by npracht** [comment]
Just tested this morning, still not working.

**Comment by bnagaonkar** [comment]
Duplicate issue of https://github.com/mautic/mautic/pull/4191
