### ISSUE TITLE
Issue #22 still not totally resolved

### ISSUE THREAD

**Issue by julienmarie** [mautic/mautic#30]
There is still a bug left : when list saved and reopened, the saved filter is not selected

**Comment by alanhartless** [comment]
Ah sorry; missed that! Commit coming to fix.

**Comment by alanhartless** [comment]
Sorry; I put the wrong issue number in the commit log.  This should be fixed with https://github.com/mautic/mautic/commit/eebe814f1986b28842896235eab07426e73d1c4b.
