### ISSUE TITLE
Expose "Send To" and "CC" fields on the email editor advanced tab

### ISSUE THREAD

**Issue by Loanatik** [mautic/mautic#3005]
What type of report is this:

| Q  | A N
| ---| --- 
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
It would be very helpful to expose the “send to” and “cc” fields in the advanced tab of email editing.  The value of the send to field should default to {contactfield=email}, however, users should be able to add or delete that initial value and replace it with other fields stored in the contact record.  

This would enable us to set up campaigns that send notices to people other than the contact.  Potential uses might include:

•	Send a notice to a fulfillment house to send a physical item to a contact.
•	Alert customer service that a contact visits a specific page
•	Send messages to anyone related to the contact

Ideally, this would allow any email address stored in the contact’s record to be used as a send to or cc address.  The interface might look something like this:

![image](https://cloud.githubusercontent.com/assets/14249107/20644818/bc6d2130-b401-11e6-9aac-315b679904cd.png)

**Comment by kuzmany** [comment]
Maybe this is better idea:

https://github.com/mautic/mautic/issues/2433

**Comment by Loanatik** [comment]
#2433 is very similar in functionality and correctly points out that all of the channels should provide the capability of controlling who receives a specific notification.  Both requests ask for the ability to send a notification to someone other than the contact.  Both requests point out that this capability is very important to the flexibility and usability of the system.  The implementation of the feature is where the two requests differ.  

#2433 requests changes to the interface in campaign and point actions.  The author of #2433 created a sample form showing the "To" address being added to the point action, implying that the "To" address is stored along with the campaign or point action information.  I don't believe that is the correct place to store that information.  The data for the "To" address should be encapsulated within the email, sms or tweet itself.

By addressing the feature request at the lowest level (the notification) the functionality will automatically be provide the wherever you are able to send a notification including campaigns and point actions.

**Comment by patmifsud** [comment]
I think #2433 would be far more intuitive to new users. A user learn that mautic is able to send emails to other contacts mid campaign by just reading the list of available Actions.

**Comment by Loanatik** [comment]
I've assigned this request to one of my developers to complete.  If anyone has any suggestions or ideas for implementation please let us have them now.
