### ISSUE TITLE
Multiple Select custom fields don't save single selections.

### ISSUE THREAD

**Issue by actonsheep** [mautic/mautic#3008]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

Multiple select custom fields will not save if only one value is selected.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Current (Bug exists in hosted and on-premise install)
| PHP version | 5.6.27

### Steps to reproduce:
1. Create a custom multiple select field with multiple options.
2. Edit a contact, and select a single value from the multiple select field. 
3. Apply the change (or Save & Close)
4. The record now shows "Choose one or more.." for the multiple select field.
### Log errors: 
No errors appear in any logs.

**Comment by npracht** [comment]
Due to our last tests and bug fixes in https://github.com/mautic/mautic/pull/4097 & https://github.com/mautic/mautic/pull/4109 we didn't fall on this bug. I think we should consider it as corrected @escopecz
