### ISSUE TITLE
Add /leads/notes endpoint to API to pull notes from across all leads

### ISSUE THREAD

**Issue by zapur1** [mautic/mautic#301]
Hi,

Just noticed a case where having a /leads/notes type API endpoint which that just returns a list of all the recent notes would be good, I'm not sure how realistic this would be in terms of the current coding structure though.

Just another request, I thought I would mention it just incase it was easy to implement.

Thanks,
Zac

**Comment by alanhartless** [comment]
Hi Zac,

Are you thinking across all leads or for a particular lead?

You can get notes for a particular lead using /leads/{id}/notes.  It'll accept the same parameters as the /leads endpoint ('search', 'start', 'limit', 'orderBy', 'orderByDir')

Thanks!
Alan

**Comment by zapur1** [comment]
Hi Alan,

Yeah that is what I'm thinking, across all leads. I thought to post it here
thinking it might be easy to implement if not I will look into getting it
working myself later on.

Cheers,
Zac

**Comment by alanhartless** [comment]
Gotcha; yea that's not in the api endpoints yet so will tag this as a feature request.

Thanks!
Alan

**Comment by escopecz** [comment]
Added to 2.3
