### ISSUE TITLE
Froala adds/changes "img" tag class with "fr-dii fr-draggable" text causing issues with responsive image!

### ISSUE THREAD

**Issue by olimits7** [mautic/mautic#3013]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | N/A 
| Enhancement? |  N/A

## Description:
I'm using an image class that makes my image responsive for all devices; however, I notice when I save my email Froala changes my "class" or if an image doesn't have a "class" it adds it's own; which causes issues with the image showing responsive in my email client.

**Original IMG Tag:**
`<img src="https://www.domain.com/image.jpeg" height="800" style="outline: none; text-decoration: none; border: none; width: auto; height: auto;" class="col2img">`

**After Using Froala:**
`<img src="https://www.domain.com/image.jpeg" height="800" style="outline: none; text-decoration: none; border: none; width: auto; height: auto;" class="col2img fr-dii fr-draggable">`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6.28

### Steps to reproduce:
1. Go under "**Froala > Code View**", then copy/paste original image tag above into Froala editor.
2. Then click "**Code View**" button and then click "**Code View**" button again to view code and you will see Froala added the following "**fr-dii fr-draggable**" text to the <img> "class" tag.

**Comment by escopecz** [comment]
I recognize that adding 2 more classes to an image is not wanted behavior, but it should not cause any troubles. Could you please explain what issues does it cause with responsiveness of the image?

**Comment by olimits7** [comment]
@escopecz Thank you for the quick reply!

It makes the following CSS "class" that I have in my email not work because Froala changes the class to **class="col2img fr-dii fr-draggable"** in my <img> tag. 

```
@media only screen and (max-width: 480px) {
img[class=col2img] {
width: 280px!important;
height: auto!important;
  }
}
```

Thank you!

**Comment by escopecz** [comment]
I don't think it's because of the added classes. I tested it at http://codepen.io/anon/pen/xRXdKe?editors=1100#0 . Feel free to play there. The correct CSS code should be:
```
@media only screen and (max-width: 480px) {
    img.col2img {
        width: 280px !important;
        height: auto !important;
    }
}
```

**Comment by olimits7** [comment]
@escopecz Yes, thank you you are right!  

The issue is I was using "exact match" with **img[class=col2img]**, so when Froala added **class="col2img fr-dii fr-draggable"** it no longer applied the CSS.

However, I think Froala shouldn't be adding their own **fr-dii fr-draggable** classes in the email code but I guess this would be a Froala issue.

Thank you!
