### ISSUE TITLE
Calendar only returns maximum of 65 events

### ISSUE THREAD

**Issue by stevegrant1983** [mautic/mautic#3016]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The AJAX request to populate the calendar only seems to return a maximum of 65 events, with no apparent logic to the filter.

I have two separate installations of Mautic (for different client data which needs to be kept separate), and on both of them, the calendar has large gaps of days where no events are displayed, despite the knowledge that events have definitely been triggered on those days.

![image](https://cloud.githubusercontent.com/assets/14789786/20712304/62507350-b63b-11e6-8b73-6ab5f4ac2f48.png)

From that graphic, another email campaign with a large number of opens, clickthroughs, etc, was sent on the 17th, but no events are shown.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 7.0.8-0ubuntu0.16.04.2

### Log errors: 
None

**Comment by merlin0** [comment]
Same for me, first week of the month it shows everything like the example but then it stops.

**Comment by bizxl** [comment]
I am having the same issue. Is there a fix?

**Comment by DianaCruz16** [comment]
> I am having the same issue. Is there a fix?

It is not the same problem. My calendar returns 134 triggered actions and 160 manual actions

**Comment by martinshumberto** [comment]
I am having the same issue. Is there a fix?
