### ISSUE TITLE
FR - Subscription List Management

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3019]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes !
| Enhancement? | 

### Subscription List Management

Contacts can be interested by different type of content given by the company. Product A/B/C, more than one brand, newsletter, events, etc.

### How: create Subscription List

Like different categories and generate different unsubscribe tokens:

- Newsletter --> `{unsubscribe_url=newsletter}`
- Updates --> `{unsubscribe_url=updates}`
- Products --> `{unsubscribe_url=products}`
- Events --> `{unsubscribe_url=events}`
- Brand A --> `{unsubscribe_url=branda}`
- Brand B --> `{unsubscribe_url=brandb}`

### What then happens?

1. It'll unsubscribe the contact about the topic he clicked on. But not the others.
2. You'd still have the ability to insert global token if wished.
3. You can imagine also another token like `{unsubscribe_url=preferences}` that the contact can click on to see all the Subscription Lists available and where he is OFF/ON.

### How to use?
Imagine your email footer like that:
> If you don't want to receive mautic newsletter anymore, _click here_. You can also manage your mailing list subscription preference by _clicking here_. Please don't leave us. 
Which would be

`If you don't want to receive mautic newsletter anymore, <a href="{unsubscribe_url=newsletter}">click here</a>. You can also manage your mailing list subscription preference by <a href="{unsubscribe_url=preferences}">clicking here</a>. Please don't leave us. `

N.

**Comment by mqueme** [comment]
This is addressed in the new preference center in 2.3

**Comment by that0n3guy** [comment]
@mqueme Question, does the new preference center allow the emailed user to select which thing they are unsubscribing from (like provides them a list to uncheck categories when they click unsubscribe) 

Or does it allow the Mautic user (me) to define which category they are unsubscribed from when they click the unsubscribe button?

**Comment by mqueme** [comment]
you can edit contact's preferences at the contact record in Mautic, and the contact can also edit its own preferences through their unsubscribe page. (do not contact channels, prefered channel, pause communication between dates, frequency rules,  global categories, public segments)

the segments that are presented to the contact at the unsubscribed page are only the segments set as public. the ones you see at the contact record are all segments.

**Comment by that0n3guy** [comment]
Ok, then I agree with @npracht, I don't think this is included in the preference center.   His request is to be able to specify what categories they unsubscribe from with the single click (see number 1 under "what then happens" above).

Also, just for users later, this is like: https://github.com/mautic/mautic/issues/822#issuecomment-263606040

**Comment by olimits7** [comment]
I also agree with @npracht and @that0n3guy  , I think being able to include specific "**unsubscribe tokens** in the emails would be a great addition and is what most other email marketing platforms have integrated already.

It would be great if I could use a **{unsubscribe_url=segment_id}** or **{unsubscribe_url=campaign_id}** in the emails I send this way if the user decides to unsubscribe they are only removed from that specific campaign or segment and still gives me an opportunity to convert users to customers on other campaigns or segments.

**Comment by that0n3guy** [comment]
@mqueme Any thoughts on re-opening this issue based on the above comments?

**Comment by rctlopes** [comment]
I'm searching the documentation and google about a way to unsubscribe segments individually. My campaigns are linked to segments. If a subscriber clicked the unsubscribe link from one of the emails from a particular campaign (linked to a specific segment), the unsubscribe should target only that particular segment. Love the idea of {unsubscribe_url=segment_id} or {unsubscribe_url=campaign_id}.
Totally second that feature. Thanks @olimits7 and @npracht !

**Comment by backstageel** [comment]
Any update on this? This is a "must have" feature for me!

**Comment by juicerocket** [comment]
Me too! I want to use one Mautic install and list to send newsletters for several blogs and brands. When someone clicks "unsubscribe" it needs to unsubscribe them ONLY from the brand/blog that particular newsletter was about -- not from ALL of the brand/blog newsletters.

Is this available yet??

**Comment by ianmartorell** [comment]
This would be a great feature for people managing more than one brand, where unsubscribes should be handled separately, and it's currently not part of the Preference Center afaik.
