### ISSUE TITLE
Reminder Emails to Mautic User when Note Added

### ISSUE THREAD

**Issue by sambarnes90** [mautic/mautic#3025]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
Our sales team are really happy with Mautic - and we're continuing to learn about more and more functions.

However, a key feature we would like to see is the ability to check a 'reminder' checkbox when adding a note which would then send an email to that Mautic user after a defined input.

An example workflow may be:

1) Mautic user accesses contact page.
2) Mautic user clicks to add a note.
3) Checkbox to Set Reminder with a dropdown incorporating relevant options (3 days, 5 days, 7 days, 10 days, 14 days, 30 days etc.)

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/12860024/20751793/c05138e4-b6f5-11e6-8a22-899a2a5f4c03.png"></img>
</p>

4) If the user has checked the 'Reminder' box - an email is created to that Mautic user's email address along the lines of:

> You asked us to remind you about the note you've left on {contactemail}
> 
> Your Note: "Note Text"
> Delay Selected: "7 Days"
> 
> To access this contact please click here - {contactlink}

5) The email is then scheduled to be sent after the selected delay.

I'm presuming that we can use similar functionality to the "email delay" in the campaign bundle. 

In fact - it may be beneficial for future extension to be able to use certain campaign actions without them being part of a campaign. It sounds a bit idiosyncratic but these little snippets of functionality may well come in handy across different parts of the system as Mautic expands.

I'm still learning the ropes of Symfony (and PHP to be honest!?) so I'll keep chipping away at this to see if I can get something working.

But I thought it may be worth raising this feature request just to see if other members of the community would also like to see the functionality.

Thanks as ever to the whole Mautic community for the work you do - you're all awesome!

**Comment by BatchHeader** [comment]
This would be a great feature and would really help with lead nurturing.

**Comment by sambarnes90** [comment]
Just as a follow up - I've tried looking into how emails are created and sent, but because the 'delayed' part is all campaign actions, and we want to send emails based on the text from a note, to a user not a contact, I really am struggling to find a way to do this.

It's probably just my lack of PHP knowledge / Symfony experience though.

If anyone has any ideas on what kind of functions I might need to use to create something like this I'd really appreciate any pointers - even if it's just to tell me to look at a file and start digging!
