### ISSUE TITLE
Link with mautic leadfield values in email (sparkpost) brakes first query param

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#3035]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I've created an email with a link to my website with some mautic field values in the link. Like Alan's great example: https://www.mautic.org/community/index.php/307-using-mautic-for-event-registration/p1#p1222

I've done this before with success. I think this could have something to do with sending the email through the Sparkpost API instead of regular SMTP, but I'm not sure.

`https://www.example.com/page?form[location]=mylocation&form[email]={leadfield=email|true}&form[year]={leadfield=year}&form[level]={leadfield=level}&form[eventdate]=december-2016`

This mail outputs like this in the mail:

`https://www.example.com/page?form[location&form%5Bemail%5D=me%40mydomain.com&form%5Byear%5D=3&form%5Blevel%5D=level5&form%5Beventdate%5D=december-2016`

urldecoded it looks like this:
`https://www.example.com/page?form[location&form[email]=me@mydomain.com&form[year]=3&form[level]=level5&form[eventdate]=december-2016`

The problem is that the 'location' parameter get's messed up. The first [ is not encoded and the value has disappeared. 
All other values are correct.

Tested this in multiple browsers with several mails set up in mautic.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2
| PHP version | 7.0.13

### Steps to reproduce:
1. Create an email with in it a link with some mautic lead field values and static values in the url queryparameters as an array:
http://something.com/page.html?form[param1]=value1&form[param2]={leadfield=email|true}2&form[param3]=param3
2. Send the mail to a contact through the Sparkpost API
3. See the incorrect formatted url destination in the mail
 
### Log errors: 

No errors

**Comment by marett** [comment]
I have bumped into this bug a few times, going back as far as version 1.x. 

Today I noticed the issue was only affecting emails which also had (auto generated) plan text versions. Setting the plan_text cell in MySQL to either empty or Null has fixed the one instance of this issue I was able to test. 

Can anyone else w/ this issue try this solution and report back their findings?

**Comment by bunce69** [comment]
Hello guys,

I'd like to send by automatic emails :
https://www.mydomain.com/product/{liedfield=firstname}  but when I make the test, here is what is happening : https://www.mydomain.com/product/ 

The liedfield is not included.

Any idea? I'm using Sparkpost.

Thx

**Comment by wderuijter** [comment]
You should not use 'liedfield' but 'leadfield'.

On Apr 16, 2017 8:35 PM, "bunce69" <notifications@github.com> wrote:

Hello guys,

I'd like to send by automatic emails :
https://www.mydomain.com/product/{liedfield=firstname} but when I make the
test, here is what is happening : https://www.mydomain.com/product/

The liedfield is not included.

Any idea? I'm using Sparkpost.

Thx

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mautic/mautic/issues/3035#issuecomment-294366917>, or mute
the thread

**Comment by wderuijter** [comment]
Is this relared to https://github.com/mautic/mautic/issues/3552 ?

**Comment by bunce69** [comment]
Hello,

thanks for the following.

It is more related to this : https://github.com/mautic/mautic/issues/3035

But actually I don't understand so I gave up :(

2017-05-11 12:25 GMT+02:00 Wim de Ruijter <notifications@github.com>:
