### ISSUE TITLE
Can't access configuration page 

### ISSUE THREAD

**Issue by cesf** [mautic/mautic#3038]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
After the upgrade from 2.1.1 to 2.3, we can't access the configuration.

We checked the log and shows memory limit and maximum execution time exceeded hence, we've raised both. 

Memory limit error was gone in the logs after lifting to 256M. 
Maximum execution time was raised to 300 (5 minutes) but log error still says maximum execution time exceeded.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.3
| PHP version | 5.6.24

### Steps to reproduce:
1. Login to mautic installation
2. Click Settings > Configuration
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by sambarnes90** [comment]
Can you post the lines of the log around the memory / execution error so everyone can see what's actually causing it?

**Comment by cesf** [comment]
[2016-12-02 02:06:23] mautic.ERROR: Error: Maximum execution time of 300 seconds exceeded - in file /home/scmautic/cache/prod/classes.php - at line 900 [] []

**Comment by sambarnes90** [comment]
Have you tried clearing the cache completely?

I'm presuming you've tried [all the steps listed here](https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful).

**Comment by cesf** [comment]
Yes, I've cleared the cache after the upgrade.

We've also done reverting from and old copy then upgrade again, experimenting different  settings. 
We've noticed that the problem is when you have something defined in monitored inbox settings. 
We can confirm that the details in the monitored inbox are perfectly working before the upgrade to 2.3.

**Comment by sambarnes90** [comment]
Are you using any custom themes at all?

These are lines 899, 900 and 901 of that file:

```
$parameters = array_replace($this->getGlobals(), $parameters);
if (false === $content = $this->evaluate($storage, $parameters)) {
throw new \RuntimeException(sprintf('The template "%s" cannot be rendered.', $this->parser->parse($name)));
```

It looks like something to do with templates or those evaluate functions.

I'm by no means an expert but could be something going on there?

Template that isn't compatible with 2.3?

Permissions not set correctly on template folders?

**Comment by sambarnes90** [comment]
Presumably you've also tried upgrading using the script and command line?

> As always, if you are have access to SSH, we highly recommend that you use the update script.  Download it to the root of your Mautic installation and run it with php upgrade.php. Be sure to remove this file once the upgrade is complete.

**Comment by cesf** [comment]
Yes, we are using custom themes. Those themes were developed based on 2.1.1 structure. Do you think the 2.1.1 theme is not compatible with 2.3?

Yes, upgrade via ssh was also done but same thing happens.

**Comment by sambarnes90** [comment]
Possibly?

I can't be 100% sure but it might be worth double checking against one of the standard themes in the folder to ensure that the structure of your custom theme follows the same style as the default.

**Comment by cesf** [comment]
We've uninstalled all themes and the problem's still there unfortunately.

**Comment by escopecz** [comment]
Do you have some special characters in the app/config/local.php file? For example in passwords or signatures? Some characters like `&`, `%`, `$`?

**Comment by escopecz** [comment]
Closing this issue in favour of https://github.com/mautic/mautic/issues/3390
