### ISSUE TITLE
Shortcut tag leading to wrong email link

### ISSUE THREAD

**Issue by vamsiikrishna** [mautic/mautic#304]
As a logged in user when I visit s/users route, when I click on any user email , its not being interpreted by php .

![screenshot 2015-04-15 19 33 05](https://cloud.githubusercontent.com/assets/554887/7160476/e938adba-e3a6-11e4-8cc0-a4009678e8b3.png)

**Comment by dbhurley** [comment]
Thanks! We've got a PR to fix this.
