### ISSUE TITLE
No emails were sent when using a 'Campaign' (PHPMailer)

### ISSUE THREAD

**Issue by cpot** [mautic/mautic#3040]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Sending individual emails works but not with campaigns when configured with PHPMailer (or Mailjet but this is another issue

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.3.0
| PHP version | 5.6.28

### Steps to reproduce:
1. Create a basic campaign
2. Trigger the campaign (/usr/bin/php /var/www/html/mautic/app/console mautic:campaigns:trigger --env=prod)
 
### Log errors: 
`[2016-12-01 22:54:04] mautic.ERROR: Deprecation: Symfony\Component\DependencyInjection\Definition::setFactoryService(doctrine) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. - in file /var/www/html/mautic/vendor/symfony/dependency-injection/Definition.php - at line 204 [] []
`

**Comment by escopecz** [comment]
Campaigns need the commands to be executed periodically in a cron: https://www.mautic.org/getting-started/

The deprecation notice won't affect any functionality.

**Comment by cpot** [comment]
Of course that the commands are in the cron ! And when i say i trigger the command it is with "mautic:campaigns:trigger "

`0,15,30,45      *       *       *       *       root /usr/bin/php /var/www/html/mautic/app/console mautic:segments:update --env=prod
5,20,35,50      *       *       *       *       root /usr/bin/php /var/www/html/mautic/app/console mautic:campaigns:rebuild --env=prod
10,25,40,55     *       *       *       *       root /usr/bin/php /var/www/html/mautic/app/console mautic:campaigns:trigger --env=prod
10,25,40,55     *       *       *       *       root /usr/bin/php /var/www/html/mautic/app/console mautic:campaigns:update --env=prod
1               *       *       *       *       root /usr/bin/php /var/www/html/mautic/app/console mautic:email:send --env=prod
1               *       *       *       *       root /usr/bin/php /var/www/html/mautic/app/console mautic:email:fetch --env=prod
`

**Comment by escopecz** [comment]
If you execute `php /var/www/html/mautic/app/console mautic:campaigns:rebuild`, `php /var/www/html/mautic/app/console mautic:campaigns:trigger` and `php /var/www/html/mautic/app/console mautic:email:send` manually via SSH, what is the output?

**Comment by cpot** [comment]
[centos@srv04 ~]$ /usr/bin/php /var/www/html/mautic/app/console mautic:campaigns:rebuild

Redéfinir les contacts pour la campagne 1

Redéfinir les contacts pour la campagne %id%

0 contact(s) à retirer aux lots 300

0 contact(s) concerné(s)

[centos@srv04 ~]$ php /var/www/html/mautic/app/console mautic:campaigns:trigger

Événements déclencheurs pour la campagne 1

Événements déclencheurs de premier niveau

0 événement(s) à traiter pour les lots 100

0 événement(s) traité(s)

Événements déclencheurs programmés

0 événement(s) à traiter pour les lots 100

0 événement(s) traité(s)

Événements déclencheurs 'non-action'

0 événement(s) traité(s)

[centos@srv04 ~]$ php /var/www/html/mautic/app/console mautic:email:send

Mautic is not set to queue email.

**Comment by escopecz** [comment]
This seems to be OK. Can you share what your campaign looks like? You can drag&drop screenshots directly to the textarea.

**Comment by cpot** [comment]
![capture du 2016-12-02 10 10 37](https://cloud.githubusercontent.com/assets/3287514/20828425/d78d558c-b877-11e6-9a93-7dc95553619d.png)

![capture du 2016-12-02 10 13 24](https://cloud.githubusercontent.com/assets/3287514/20828473/fe7c96da-b877-11e6-8a6c-e475ecbd65b4.png)

**Comment by escopecz** [comment]
Ok, I'll re-open this issue if anyone else would have an idea what's wrong. I'm out of ideas.

**Comment by cpot** [comment]
IMPORTANT: If i remove the contacts of the campaign, then added them back **it works**

**Comment by cesf** [comment]
Mautic version	2.3
PHP version	5.6.24
Service to send mail through: PHP Mail
How should email be handled: Send immediately
CRON Jobs: Yes

We are also experiencing the same issue. I tried doing what cpot did to remove the contacts then add them back and still not working.

**Comment by cesf** [comment]
We've also updated our CLI command from 
/home/scmautic/public_html/app/console mautic:process:email to
/home/scmautic/public_html/app/console mautic:emails:send

After doing that, we are receiving mail delivery report saying 'Mautic is not set to queue email.'

**Comment by cesf** [comment]
We've rolled back to 2.1.1 and the same error occurs

**Comment by Jakub087** [comment]
Hey Mautic family :)

I have same problem
- email is sent if set-up as ACTION in the FORM
- email is not sent if its part of the CAMPAIGN (and it doesnt matter if CONTACT SOURCE is CONTACT SEGMENT or CAMPAIGN FORM)

Anybody same experience? Is there any progress about all questions above? 

Thanks, Jakub

**Comment by escopecz** [comment]
Just an idea to consider since I was wondering why segment email is sent only for the first time yesterday. I had the _Email Settings_ / _Default Frequency Rule_ configured to 1 day. So if I wanted to send more than 1 email per day to a lead (while testing stuff), it queued the email instead.
