### ISSUE TITLE
Add support of contactfield in form result email

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3041]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Y

## Description:
It would be great in the **form result email** to be able to add contact field tokens like `{contactfield=id}`. Then we could also add a link to the contact page in mautic :-)

**Comment by BaOlfa** [comment]
hi npracht , can u plzz explain to me how can i send URL link contact page  in mail like i send {contactfield=lastname}‍, {contactfield=firstname}‍ and https://####.mautic.net/s/contacts/view?????  in notification email 
Thanks

**Comment by AlbanL74fr** [comment]
@escopecz Hi John, is it implemented already? I have reported an issue [#5867](https://github.com/mautic/mautic/issues/5867) and I wondered if it's connected.
