### ISSUE TITLE
1 log errors - Module Calendar

### ISSUE THREAD

**Issue by BernardiSena** [mautic/mautic#3046]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...
Only one log error

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.3
| PHP version | 7

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

[2016-12-02 15:47:33] mautic.ERROR: Warning: Module 'calendar' already loaded - in file Unknown - at line 0 [] []

**Comment by escopecz** [comment]
Provide steps to replicate, please.

**Comment by BernardiSena** [comment]
Hello this case had no path simply appeared in a clean install. Without even being configured, but similarly disappeared in version 2.4

Thank you for your help!
