### ISSUE TITLE
Bug report : http missing in Automatic form generation

### ISSUE THREAD

**Issue by KleiDav** [mautic/mautic#3052]
Bug report

## Description / how to reproduce

when I go in the form to get the « Automatic » code to insert, here’s what I get :

<script type="text/javascript" src="//mydomain.mautic.net/form/generate.js?id=1"></script>

(replaced my real domain with "mydomain")

Notice it’s missing the « http: » in the src field. So nothing is working.

Using Cloud Version

**Comment by escopecz** [comment]
It's not a bug. It's called Protocol-Relative URL and can be used in case the developer doesn't know if your site (Mautic in this case) use http or https.

More: https://en.wikipedia.org/wiki/Wikipedia:Protocol-relative_URL
