### ISSUE TITLE
Bug report : issue with French caracters

### ISSUE THREAD

**Issue by KleiDav** [mautic/mautic#3053]
Bug report

Using Cloud version

## Description:

Created a form with 2 test fields. One called "Prénom" (Firstname in french) and one called Email.
I’ve put « Jérôme », in the Prénom field, which is a french first name (notice the usage of accents in the name)

Pressed Submit, and it stays on « Please wait… » forever.
Refreshed the screen, put Jerome instead (without accents) in the Prénom field and it’s working.

**Comment by escopecz** [comment]
I'm not able to replicate this. I tried to create a new contact custom field called "Jérôme" and I can save it, edit it and save values to it in the contact detail without any problem. I also tested a form field called "Jérôme" and the form works fine too. Is this still an issue? If so, what am I missing?

**Comment by escopecz** [comment]
I'll close this issue as the question hasn't been answered for a while. I'll re-open when it does.
