### ISSUE TITLE
Replace all 'fetchAll()' with cursors, iterators and generators

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#3055]
| Q  | A
| ---| ---
| Bug report? | n
| Feature request? | n
| Enhancement? | y

## Description:
As I could see, there are lots of `fetchAll()`. It means that all of the query results are being immediately loaded into the memory, grabing much memory.
It would be better to replace `fetchAll()` with cursors, iterators and generators in order to save memory.

**Comment by escopecz** [comment]
I was looking for some method which use `fetchAll` method where we don't need all rows at the time and I couldn't find any. It's always used to get aggregated results like counts and sums or with a limit so it won't load more rows than what we need. Or for example in case of `getCampaignListIds` we expect that no one will add thousands of segments as source of a campaign.

Do you have some example where we need to use something else?

**Comment by PatchRanger** [comment]
@escopecz Initially I reported this issue while debugging some console command in order to decrease its resource consumption and decided that `fetchAll` is part of the problem - but I can't remember which one it was.
Also looks like similar issue #2920 has at least single explicit example.

**Comment by escopecz** [comment]
Ok, I'll close this in favor of #2920. If you find another example, comment bellow and I'll re-open it.
