### ISSUE TITLE
[feature] Allow triggers based on date/time custom fields

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#306]
Sometimes I might have date/time fields in a custom field which I want to use to trigger - for example a birthday, spouse's birthday, date someone bought something, etc.

At present there doesn't seem to be a way to trigger on this kind of information - but it would be essential for imported data, as an example.

**Comment by pitus** [comment]
I vote for that as well as we're planning to have various custom dates in our data as well.

**Comment by MaxOnTheHill** [comment]
:+1: definitely needed for date/time fields !!!

- actually, you should be able to do a trigger off any custom field that has a "value" and the action be an offset of - or + to do something.  
- Your offsets/argument may include +, -, >, <, =, !=, INCLUDES ... can't think of any others

eg.
IF [my-date-field] - [5 days] THEN [my-action]    so it would do something 5 days before what is entered in the "my-date-field"
eg2.
IF [my-numeric-field] > [200] AND [text-field-value] INCLUDES [product-or-url] THEN [my-action]    so if purchase over $200 and is product X then send this email, etc

Hope that explains and gives extra use case for being able to actino/trigger off custom (any) fields ... I thought that was already in Mautic (but haven't tested properly yet) -> but if not, definitely need it.

**Comment by JSHaswell** [comment]
I too voteto have date/time field triggers.  Auto responder set to trigger on birthdays, anniversaries and et ceteria for a specific greeting email, fb post or tweet.

**Comment by rodfernand** [comment]
I would like to get started on this. @dbhurley What's the best approach? Plugin?

**Comment by dbhurley** [comment]
I think this would be a great pull request to core as many people are interested in this functionality.

**Comment by cauespadula** [comment]
this question has been solved ?? I need to develop an camapaign to send email in the client birthday...

please help... 

thanks!!!

**Comment by npracht** [comment]
## Development suggestion

Hi, actually i think the best would be to add in the **list filters** for **date format** `field` the following options in the dropdown list:
* Is today
* Is yesterday
* Is tomorrow
* Is this month
* Is last month
* Is next month
* Is this year
* Is last year
* Is next year
* **Is birthday** (today not taking into account the year)

**Those values must be variables** ---> By consequence it's an evolution of this PR https://github.com/mautic/mautic/pull/808, which frizzes the `today`'s value when you save the list.

**Comment by dnjusa** [comment]
Is this working yet, I'm looking to use it for birthday campaigns.

**Comment by Loanatik** [comment]
Here's another vote for getting date triggers pushed toward the top of the development stack.

**Comment by CedricH-BZH** [comment]
I'd also love to see that PR in a future version ... not too far away ... please ;-)

**Comment by nithinga** [comment]
Currently I am investigating on this PR and trying to build this feature.

**Comment by abooster** [comment]
@nithinga Have you made any progress?

**Comment by cittanet** [comment]
I vote for that! It would be a good idea to have a custom field that can be used to create custom actions in a campaign

**Comment by Melevis** [comment]
I vote for that! Actually i signed up to GitHub just to give this vote.

Really need that tool since all my campaigns will run based on birthdays.

**Comment by tpilet** [comment]
Somebody know a actual way to implement a birtday mail in Mautic?

**Comment by zenzozen** [comment]
This is a must for creating many Segment filters and Campaigns. 
I believe that Mautic needs more specific and User Friendly approach around dates, but thats another topic.

What i suggest is to have two more options in "operators", as we can´t remove the existing ones (equals, greater, not like, etc). Its 

---

**Date Range BETWEEN RELATIVE period** 
Ex: "9999" "days" from "today" and "60" "days" from "today".

Where 
- "9999" or "60" would be a number type (it is easy to input)
- "days" would have day(s), month(s) and year(s) drop down optins with days selected by default (used in most cases)
- "today":  I dont see many purpose to open options for the user in this matter (last month, next week, etc)

I personally use this filter in other e-mail marketing software to segment "Inactive Site Users" by last login date, but it can serve for many purposes.

--------

**Date Range BETWEEN ABSOLUTE dates**
Date "2015-01-01" and "2015-12-31" 

--------

By the way: im a UI/UX designer. 
I could help with some ideas for the Filters in Segments Interface.

Cheers!

**Comment by TechBravoTN** [comment]
YES please add birthday and anniversary campaigns!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Jo-Pitts** [comment]
Hi there.  Has there been any movement?  This sort of stuff is mandatory for re-activation and re-engagement campaigns among many things.

e.g. Automatically email all customers who haven't haven't purchased for 6 months, but is opening emails regularly.  (re-activation).

e.g. Automatically email all customers who haven't opened an email for 6 months with a super compelling subject line/offer. (re-engagement).

for both of these, date offsets are key.  I could create a custom field in the database, and populate it with a cron job, and then use it but that sort of defeats the purpose of a user friendly marketing automation platform.

Cheers

**Comment by escopecz** [comment]
This should be solved by https://github.com/mautic/mautic/pull/3180
