### ISSUE TITLE
When creating a segment, boolean filters don't work the first time you try to save

### ISSUE THREAD

**Issue by blueflamexr** [mautic/mautic#3062]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When creating a segment, some filters don't work the first time you try to save. It appears to be related to boolean fields. Below are steps to reproduce using the "Bounced - Email" field in a segment filter.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.3.0
| PHP version | 5.6

### Steps to reproduce:
1. Create a new segment
2. Add a name for your segment
3. Create a segment filter with this criteria: "Bounced - Email," "not equal," and "Yes" and click Apply
4. Notice it won't allow you to save the filter and gives an error icon on the filter.
5. Click Apply again. Notice it now saves okay the second time you click Apply. This seems to be the case with other boolean filters too.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
This has been fixed in recent versions of Mautic. Please upgrade if the problem persist.
