### ISSUE TITLE
Bad font in segment filter dropdown

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3066]
| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | X

#### Before with `font-family: FontAwesome;`
![segment-filter-ugly-font1](https://cloud.githubusercontent.com/assets/18265735/20969418/2616cab6-bc89-11e6-95fd-9c5e2c15200f.png)

#### After with `font-family: FontAwesome, sans-serif;`
![segment-filter-ugly-font2](https://cloud.githubusercontent.com/assets/18265735/20969421/28d652ee-bc89-11e6-9bc6-bdb52a868fa7.png)

In the segment filter drop down list, the whole list items are given the class `.fa` which gives them the font `FontAwesome` which isn't made for text. A quick hacky workaround I showcase in the above screenshots is to give a fallback font to the `.fa` class.

Wouldn't it be better to do something like this?

```html
<li>
  <i class="fa fa-user"></i> Actual label
</li>
```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | `2.3.0`
| PHP version | `7.0.13`

**Comment by mqueme** [comment]
@MaxWebmecanik your suggestion doesn't work because of symfony forms and because we use jquery chosen in our forms elements. I have made a PR for that fixes this through css.
