### ISSUE TITLE
[Feature Request] Ability to filter contacts on sent emails

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3067]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:

![image](https://cloud.githubusercontent.com/assets/18265735/20970644/d6b1e036-bc8e-11e6-8317-3e593e8829b6.png)

Today, the best way to insure a contact has received a certain email is to put him in a segment at the end of a campaign. This is an action that asks some foresight from the user, and if they forget to do this, they just end up frustrated.

I think adding this functionality would give less room for these kinds of frustrating situations to occur.

What do you guys think?

**Comment by PatchRanger** [comment]
I think it seems to be related to #2912 .

**Comment by MaxWebmecanik** [comment]
@PatchRanger Ok, I've started a dialog there as well!
