### ISSUE TITLE
Action Points + JS tracking method doesn't add any action points on page hit.

### ISSUE THREAD

**Issue by zenzozen** [mautic/mautic#3078]
| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
The JS tracking method doesnt trigger any action points. Using tracking pixel method works fine. When o use the JS, i get only the page hit. When i use tracking pixel, i get both of page hit and points added. 

It is supposed to work only with pixel? If so, pixel method isn't secondary, as it isn't 100% reliable? (https://mautic.org/docs/en/contacts/contact_monitoring.html)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.3
| PHP version | 5.6.27-1

### Steps to reproduce:
1. Create Action Point with specif URL
2. Place an external URL (outside domain)
3. Put the JS tracking method on this URL
4. Log out from mautic and test
5. I get the page hit, but the hit don't trigger the action point

**Comment by uberconversion** [comment]
would really like to know this as well, since I am pulling my hair out trying to get this to work with the JS tracking snippet.

**Comment by escopecz** [comment]
Wait for Mautic 2.6.1 to be released and then upgrade your Mautic. Mautic 2.6.0 has a bug in the tracking. Follow https://github.com/mautic/mautic/issues/3397. Reporting a bug on several months old version is not a good idea. It could be fixed in the newer versions.
