### ISSUE TITLE
Missing permissions

### ISSUE THREAD

**Issue by qneyrat** [mautic/mautic#3083]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | n
| Feature request? | y
| Enhancement? | n

## Description:
Add permissions on themes. Themes of mail or other to be used only by some users. 

The problem is that Config is in file and no in database. 

Create a database aspect for themes that stores the theme name and the role associated with it  that you can then query when fetching a list of available themes.

**Comment by npracht** [comment]
Hi @qneyrat,
Please note that there is other permissions missing and also a bug behind it.

## Missing permissions
* Companies

#### Today permissions
![capture d ecran 2016-12-13 a 12 19 48](https://cloud.githubusercontent.com/assets/14075239/21138486/93d05370-c12e-11e6-8151-ca4c509b2033.png)

## Bug seen recently and related
When you change permissions on role for Dynamic Web Content, it is not saved. Same issue on themes. Check issue https://github.com/mautic/mautic/issues/3088

**Comment by qneyrat** [comment]
Missing permissions for segments (it's very important for me),
@alanhartless I rename issue to "Missing permissions" ?

**Comment by qneyrat** [comment]
up

**Comment by qneyrat** [comment]
up @alanhartless
