### ISSUE TITLE
Email template editor disappeared

### ISSUE THREAD

**Issue by Rovel** [mautic/mautic#3085]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
The traditional email template editor, disappeared in this latest release leaving only the builder, that I cannot change the font type via UI

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4
| PHP version | bitnami-mautic-1.3.1-0-linux-ubuntu-14.04.3-x86_64-hvm-ebs-mp

### Steps to reproduce:
1. Create a new email: Channels -> emails -> new -> select the template -> search a way to edit the content other than the builder that do not allow me to change font type any other way than code editing

![captura de tela 2016-12-12 as 18 25 30](https://cloud.githubusercontent.com/assets/2469500/21115443/6d0322ae-c098-11e6-86b9-dba4cd694744.png)

**Comment by marziovit** [comment]
please continue here: https://github.com/mautic/mautic/issues/3032
