### ISSUE TITLE
Action and decisions triggers in Campaign won't run to automatic cron jobs

### ISSUE THREAD

**Issue by martinduplex** [mautic/mautic#3086]
What type of report is this:
Campaign trigger is not running automatically / responding based in command defined in cron jobs

| Bug report? |  Y
| Feature request? | N
| Enhancement? | N

## Description:
I have set up cron jobs under Cpanel with the following commands that I think should do the trigger for all events defined in the maps in the Campaign item.

php /home/user1/public_html/mautic/app/console mautic:campaigns:trigger (every minute)
php /home/user1/public_html/mautic/app/console mautic:segments:update (every minute)
php /home/user1/public_html/mautic/app/console mautic:campaigns:rebuild (once a day)
php /home/user1/public_html/mautic/app/console mautic:campaigns:update  (every minute)

In the campaign map, in the first level I have the following actions to:
- Add points
- Change contact's stage
- Add to segment

When I tested the form submission which is takes in the place of top level item (campaign form), and submitted the data, and waited for about 5 minutes, there is no change being made to the contact's stage and not having points added.

If I run campaign manually via SSH Shell command interface, the campaign runs successfully and displaying results for the events (first level, non-events, scheduled) such as showing 100% percentage for events completed.

Any assistance would be greatly appreciated.

| Mautic version | 2.20
| PHP version | 5.6.28

**Comment by escopecz** [comment]
The community cannot help you with cron configuration because it is different on every server, every hosting. Contact your server/hosting administrator for help.
