### ISSUE TITLE
Mautic forms redirect inside iframe

### ISSUE THREAD

**Issue by pavel-janicek** [mautic/mautic#3087]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
1. Go to Channels - Emails and create new email
2. Go to Components - Forms and create new form
2.1 . In Details tab of such form choose "Successful Submit Action" Redirect URL
2.2. As redirect url choose different URL than url where you will be including the form
2.3 In Actions tab choose the selected email to be sent to the user
3. Save and publish both Email and form
4. Go to Components - Forms and choose form created in step 2
5. In "Form HTML" box choose "Automatic" and "Via iFrame"
6. Paste the code on your page
7. Fill in form properly and click Submit

Expected result:
Browser navigates whole view to URL specified in step 2.2

Actual result:
URL chosen in step 2.2 is displayed inside iframe

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 7.0.8

**Comment by ninjoan** [comment]
Why you use iframe you can use the JS code and will work. Just select in Mautic Form redirect to and put the URL.

**Comment by pavel-janicek** [comment]
As software tester by profession, I have to answer you the QA obvious: Because the option was there.
Why is there insert option via iframe when it does not work properly? (As user would expect)
