### ISSUE TITLE
Bug - DWC permission inefficient & themes

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3088]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | -
| Enhancement? | -

## Description:
When you change permissions on role for `Dynamic Web Content`, it is not saved. Same issue on `themes`.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0 (and previous)
| PHP version | 5.6.24

### Steps to reproduce:
1. Create role with limited access
2. Click **Full** on `Themes` and `DWC`
3. Save and close
4. Edit and see that **Full** is not checked anymore.

**Comment by escopecz** [comment]
@npracht when you say that theme permissions have "same issue" as DWC permissions... well I don't see the Theme permissions in the list at all. Am I doing something wrong or do you mean you'd like the Themes to have permissions?
