### ISSUE TITLE
Better usage and display of IP data

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3089]
I'm using the MaxMind GeoIP2 Precision service in Mautic to identify IP locations and companies. I was hoping there could be a better way to display this data. Right now, a contact's profile just shows the IP on the timeline and I have to click on the not-so-intuitive "toggle details" button to see the company name identified.

Would it be possible to show the company name in place of the IP at the top of the page? Or something like "Company Name (127.0.0.1)" instead of just the IP? 

Also, on the contacts page (where all contacts are listed), would it be possible to display company name under the "name" column where IPs show up, or have an additional column on this list view to show company names, similar to location?

Finally, it might be cool to add the company identified to the "companies" section too.

Thanks!

**Comment by nickian** [comment]
Also, why once a contact has been identified does their IP address disappear from their profile? I should still be able to see what IP they were converted from in the timeline.

**Comment by hilltopmediadesign** [comment]
👍

**Comment by MarkLL** [comment]
Hi @nickian I can tell you from playing around with the API that a contact supports multiple IP addresses :) I agree that is would be useful for it to be visible somewhere. The same thing applies with contact devices - derived from the user agent.

**Comment by nickian** [comment]
What do you mean a contact supports multiple IP addresses, @MarkLL ? When I pull contacts from the API, I see that there's part of the object where IP data is supposed to be, but it's always an empty array for me. Also, when I go to "Reports" in Mautic, then go to the standard contact report, it has first name, last name, email, and IP as columns. However, when someone has been identified, their IP address value is empty.

Could this have something to do with using Kiosk mode? I'm processing some form submissions on the sever side, just doing a cURL post to the Mautic form URL. Is there a way to pass the user's IP data to the form this way? I assumed Mautic be able to associate everything that happens in that browser session with that user?

**Comment by MarkLL** [comment]
Hi @nickian I've been "fixing" some of the issues with the API, displaying IP data being one of those issues. I have been adding my contacts via the API along with their IP Address and noticed that multiple IP Addresses is supported. I was looking to see if anyone else noticed the IP details are not displaying correctly when I found your comments.
