### ISSUE TITLE
Calendar is stoped to work

### ISSUE THREAD

**Issue by Getron** [mautic/mautic#3092]
| Bug report | 

## Description:
Today i see, my calendar is stoping showing anything. This is about 3 days, there is nothing in the last 7 days. I send emails every day to new customers, direct and over campaigns, but, in calendar is nothing showed. I don't known, if this has to do with error i have there:

mautic.ERROR: Deprecation: Symfony\Component\DependencyInjection\Definition::setFactoryService(doctrine) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. - in file .../vendor/symfony/dependency-injection/Definition.php - at line 204 [] []

My versions are Mautic v2.4 and php7.0.x on Nginx and Root vServer.

Everithing else seems to work ok from now, mails are sended ok, just calendar has stoping working, or showing triggers, and so on. Nothing showed.

## If a bug:

| Mautic version 2.4 | 
| PHP version 7.0.x | 

### Steps to reproduce:
1. Not sure why it has stopped working, amd how to reproduce this.
 
### Log errors: 

Maybe is causing by this error?:

mautic.ERROR: Deprecation: Symfony\Component\DependencyInjection\Definition::setFactoryService(doctrine) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. - in file .../vendor/symfony/dependency-injection/Definition.php - at line 204 [] []

**Comment by DianaCruz16** [comment]
Hi, i have the **same problem**. 

| Mautic version 2.4.1 |
| PHP version 7.0.31 |

Did you find any solution?
