### ISSUE TITLE
When using API: Mautic should convert anonymous contact to known, instead of creating a new contact.

### ISSUE THREAD

**Issue by sujaypawar** [mautic/mautic#3094]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | Y

## Description:

User Visits my site
User Gets Cookied 
The User ID is 100 as I see it in the cookie

I've created a WordPress plugin that creates a contact with a custom form in Mautic

User submits the custom form on my website
But the new contact is created with ID 101 (Should not 100 be updated?)

The problem is I can not keep track of this user as cookie keeps reporting him as 100. So is there a better API available that would allow me to convert the anonymous contact to a known?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | 5.6.0

### Steps to reproduce:
1. Visit a website that has tracking enabled.
2. Create a contact using APIs as described here - https://developer.mautic.org/#create-contact

**Comment by sujaypawar** [comment]
**Few considerations -**

1. User might still be anonymous; but cookied
2. Known user might be on another device, so anonymous, cookied for now. But when he submits the form, he should be merged.

**My Questions -**

# Which API calls should be ideally used? Could I get some examples?
# Should new user be created? Or an existing anonymous user be updated, by tracking his ID from cookie?
# What if the user is already known, but is on another device? In this case, he will have a different ID in cookie.
# If user submits the form with same email address, will a duplicate contact be created in Mautic? (even if he submits the form using same email address)

I would appreciate some help from fellow developers.

**Comment by escopecz** [comment]
If you know the contact ID and you do the API request to add some more information to that contact, why do you create a new one and not edit the contact with the known ID? https://developer.mautic.org/?php#edit-contact

**Comment by sujaypawar** [comment]
Understood @escopecz 

The only problem I have now with this method is duplicate contacts are being created when the IDs are different (when same user is on different browsers / devices)

You may mark this issue as closed as I've opened independent issue here - #3108
