### ISSUE TITLE
Combination of Cookie and IP to track user / Progress on Fingerprint2 implementation

### ISSUE THREAD

**Issue by sujaypawar** [mautic/mautic#3095]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | N
| Enhancement? | Y

## Description:

Right now, it appears that cookies are used to track the user. Would it make sense to use the combination of Cookie and IP?

Furthermore, was any progress made for the decision on Fingerprint2 library?
https://mautic.org/docs/en/contacts/contact_monitoring.html#fingerprint-beta-feature

**Comment by escopecz** [comment]
It used to be combination of cookie and IP for from the beginning, but IP was removed recently. See https://github.com/mautic/mautic/pull/2950 and search issues for more discussions about this topic. If you have some idea how the combination should work better than before, give us some details.
