### ISSUE TITLE
GMail Plugin - Truncated emails on "-" character

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3098]
| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Email addresses collected by the GMail plugin will be truncated if they contain a dash (and maybe other special characters).

For instance, `j.doe@composed-domain.com` will turn into `j.doe@composed`...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2.1
| PHP version | 5.6.28

### Steps to reproduce:
1. Send an email using the GMail plugin with an address containing a dash.
2. Find the contact in Mautic

**Comment by npracht** [comment]
Hi @virlatinus did you have time to have a look on that ? That's very critical concerning this integration. There is several domain names containing `-`.

Thanks a lot !

**Comment by magician7** [comment]
Confirm this error.

**Comment by npracht** [comment]
Hi @virlatinus you know since the very beginning the plugin is not usable because of that ?
A pity for all mautic users. That integration was looking very great for most of the community members !

**Comment by npracht** [comment]
@escopecz @virlatinus shouldn't it be tagged as `bug` `P1` ?

**Comment by dbhurley** [comment]
Is this still occurring in the latest release?

**Comment by npracht** [comment]
As far as I know, I didn’t see any PR addressing this critical issue.

**Comment by dbhurley** [comment]
Closing here. If still an issue please re-post on the repo here as I think it's better related there: https://github.com/mautic/mautic-helper-chrome-extension

**Comment by dsp76** [comment]
Its there already: https://github.com/mautic/mautic-helper-chrome-extension/issues/3
