### ISSUE TITLE
Bug when trying to install/update plugin schema 

### ISSUE THREAD

**Issue by iuribrindeiro** [mautic/mautic#3107]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N 
| Enhancement? | N

## Description:

When trying to update a custom Plugin that have Entity who should be persisted in the database, the functionality to create or update the tables are not working correctly. You guys should take a look at line 379 and 382 from Mautic\PluginBundle\Controller\PluginController. I might had solve the problem. I'll be making a commit request for this. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.3 
| PHP version | 5.6

### Steps to reproduce:
1. Try to update entity schema from plugin

**Comment by escopecz** [comment]
Fix ready to test https://github.com/mautic/mautic/pull/3310
