### ISSUE TITLE
Purge old entries selectively 

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#3110]
| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
purge old entries from tables. I have over 5 tables that are over 1GB in size. I run a very large mautic instance for a large corporate company and the mautic interface has started to bog down alot. The following tables are super big

email_stats
page_hits
audit_log
leads
ip_addresses
campaign_lead_event_log

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | 7.0.0

## Attempts at fixing
Ran many optimizers on the mysql servers config files
Cache folder running under a tmpfs partition
PHP Session running under tmpfs
Optimized tables (many times)
upgraded server memory to 64GB
upgraded server cpu to new xeon processor

**Comment by escopecz** [comment]
How anout this? https://mautic.org/docs/en/setup/cron_jobs.html#cleanup-old-data

**Comment by ldrrp** [comment]
I don't think that cron is a good idea for me to run. I can have 365 days. But it wont really solve my problem since I haven't been using mautic that long yet. I dnt really wana delete page hits that are any newer. Is there a way to do this selectively


-------- Original Message --------

**Comment by escopecz** [comment]
Well, your request was "Purge old entries", which is exactly what the command does. What do you mean selectively?

**Comment by ldrrp** [comment]
separating the cron job by: 

mautic:maintenance:logentries
mautic:maintenance:visitors
mautic:maintenance:pagehits

**Comment by PatchRanger** [comment]
Actually I can't find a way to run the command by cron as it requires inputting "y".
Is there a way to pass "yes to all" option into the command?
I've tried passing "-y" - but it gives an exception about wrong input argument.

**Comment by PatchRanger** [comment]
Regarding "selectivity": I guess, it should be implemented via an option passed to the original command - by default (with empty argument) it should operate with all of the available entities and otherwise (getting non-empty list of entities) - purge old data only for listed entities.

**Comment by escopecz** [comment]
```
$ app/console mautic:maintenance:cleanup -h
Usage:
  mautic:maintenance:cleanup [options]

Options:
  -d, --days-old[=DAYS-OLD]  Purge records older than this number of days. Defaults to 365. [default: 365]
  -r, --dry-run              Do a dry run without actually deleting anything.
  -h, --help                 Display this help message
  -q, --quiet                Do not output any message
  -V, --version              Display this application version
      --ansi                 Force ANSI output
      --no-ansi              Disable ANSI output
  -n, --no-interaction       Do not ask any interactive question
  -s, --shell                Launch the shell.
      --process-isolation    Launch commands from shell as a separate process.
  -e, --env=ENV              The Environment name. [default: "prod"]
      --no-debug             Switches off debug mode.
  -v|vv|vvv, --verbose       Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
                  The mautic:maintenance:cleanup command dispatches the CoreEvents::MAINTENANCE_CLEANUP_DATA event in order to purge old data (data must be supported by event listeners as not all data is applicable to be purged).
  
  php app/console mautic:maintenance:cleanup
  
  Specify the number of days old data should be before purging.
  
  php app/console mautic:maintenance:cleanup --days-old=365
  
  You can also optionally specify a dry run without deleting any records:
  
  php app/console mautic:maintenance:cleanup --days-old=365 --dry-run
```
`-n, --no-interaction       Do not ask any interactive question`

**Comment by PatchRanger** [comment]
@escopecz Thank you for quick reply and sorry for such silly question) I was on my way of finding that while looking into the code of the command - your support works quicker than my mind power today)

**Comment by Rikk03** [comment]
Social monitoring data really accumulates fast,  Is there some way we can minimize the size of the db.  I ran 3 campaigns over 3 months and with 300,000 + contacts resulted in a db size in excess of 4GB.  We need to be able to prune this table or backup old data to txt document before purging or something.  Could we not selectively use noSQL for this task?

**Comment by andreab79** [comment]
> How anout this? https://mautic.org/docs/en/setup/cron_jobs.html#cleanup-old-data

Hi, i need to cleanup old data and after running
php /path/to/mautic/app/console mautic:maintenance:cleanup --days-old=365 --dry-run

i read in email

+---------------------+-----------------------+
| Tipo di record      | Contatti interessanti |
+---------------------+-----------------------+
| Notifiche utente    | 124062                |
| UTM tag storico     | 0                     |
| Visitatori          | 12813                 |
| Visite alla pagina  | 47157                 |
| Voci log d'ingresso | 61613                 |
+---------------------+-----------------------+

now how can really delete this?

maybe it's a banal question but tx for your help
