### ISSUE TITLE
Tracking Pixel giving a 403 error

### ISSUE THREAD

**Issue by BlackHazor** [mautic/mautic#3111]
What type of report is this: 

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:

My mautic pixel has returned a 403 error, however, I do not know the reason, could anyone give a light?

This seems to only happen in Google Chrome and in some email readers like Outlook.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4
| PHP version | 7.0

### Steps to reproduce:
1. Get the pixel code
2. Put on page
 
### Log errors: 
![sem titulo](https://cloud.githubusercontent.com/assets/22136013/21242999/1487eb10-c2fe-11e6-9b14-5275545ad631.png)

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by sujaypawar** [comment]
@BlackHazor - try disabling your COSR settings - 
https://cloudup.com/cRrReWD3Nkw

**Comment by BlackHazor** [comment]
Thanks for the reply, friend, but it's already disabled
![sem titulo](https://cloud.githubusercontent.com/assets/22136013/21265880/b1d45052-c38a-11e6-8580-62e5c2351d4c.png)

**Comment by escopecz** [comment]
And if you enable it and add your domain to the white list?

**Comment by BlackHazor** [comment]
The last time I did this the mautic gave 500 error and only resolved with a complete reinstallation. Losing all data

**Comment by escopecz** [comment]
It would help if you could provide steps to replicate and what the error was. https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by BlackHazor** [comment]
I was able to activate CORS and add the ip, but error 403 persists

**Comment by BernardiSena** [comment]
Hello friend, check if the security mode of your request is active if you are disconnected and take the test to see if it returns to normal.
