### ISSUE TITLE
Segments section not working for restricted roles

### ISSUE THREAD

**Issue by escovici** [mautic/mautic#3112]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? |N 
| Enhancement? | N

## Description:
When User role has any kind of permission on Segments, the user can access the Segments but the attempt to create a new segment throws an error:
Apache logs:
> PHP Fatal error:  Call to a member function getId() on null in /home/newsletter/www/newsletter/app/bundles/EmailBundle/Entity/EmailRepository.php on line 325, referer: https://www.******.eu/newsletter/s/segments

Mautic log:
> [2016-12-17 05:34:37] mautic.ERROR: Error: Call to a member function getId() on null - in file /home/newsletter/www/newsletter/app/bundles/EmailBundle/Entity/EmailRepository.php - at line 325 [] []

If no permission is granted on Segments, the user cannot access Segments from the leftside menu (page never loads) and in logs a segfault is thrown:
Apache logs (if memory_limit > 128M in php.ini):
> [pid 1832] AH00052: child pid 1840 exit signal Segmentation fault (11)

Mautic logs shows nothing if memory_limit is set higher than 128M in php.ini. If set to 128M, it shows this:

> [2016-12-17 13:13:22] mautic.ERROR: Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) - in file /home/newsletter/www/newsletter/app/bundles/CoreBundle/Helper/SearchStringHelper.php - at line 209 [] []

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.4.0
| PHP version |  5.6.28

### Steps to reproduce:
1. Create a role (I call mine user)
2. Grant no permission on Segments first
3. Create a new user and assign user role
4. Log in with the user
5. Try to access Segments
6. Segfault is thrown in logs and Segments page does not load
7. Log in as administrator and grant any or all permissions to user role (the same error is produced no matter what permissions are selected)
8. Login as user and access Segments - the page is accessed
9. Try to create a new segment - nothing happens, PHP Fatal error is thrown in logs.

**Comment by escopecz** [comment]
This is beautiful bug report. Love it! :heart: 

I'll fix this.

**Comment by escopecz** [comment]
Unfortunately, I cannot replicate either of the issues. Could you post a screenshot of the checked permissions? There must be some contact permission granted to even see the segments menu item. If I access `/s/segments` without permission, I get "access forbidden" message which is correct.

**Comment by apuestaya** [comment]
i'm facing same issue but it is when i try to create a new segment. 
error is on 328  EmailRepository.php
it does not identify current user $this->currentUser->getId()
i checked commonRepository.php and changed to public this attribute protected currrentUser; but not fix

**Comment by apuestaya** [comment]
Maybe this fix can help to fix this issue or for somebody that want a custom program with own permissions. 
I added extended permisions (own permissions) in **role > permissions** section logged as admin because it was standard permisions.
It was updated because i created a user role called Member and i need display their own segments or lead list.

![image1](https://cloud.githubusercontent.com/assets/11563358/21567443/26fbf2b4-ce7a-11e6-9061-72cb2a067267.PNG)
)
to do that i edited follow file 
**app/bundles/LeadBundle/Security/Permissions/LeadPermissions.php**
on line 35 replace this permissions  array

`$this->permissions = [
            'lists' => [
                'viewother'   => 2,
                'viewown'   => 3,
                'create'   => 4,
                'deleteown'   => 5,
                'editown'   => 6,
                'editother'   => 8,
                'deleteother' => 64,
                'full'        => 1024,
            ],
            'fields' => [
                'full' => 1024,
            ],
        ];`

In same file replace it on line 61

` $builder->add('lead:lists', 'permissionlist', [
            'choices' => [
                'viewown'   => 'mautic.core.permissions.viewown',
                'create'   => 'mautic.core.permissions.create',
                'viewother'   => 'mautic.core.permissions.viewother',
                'editother'   => 'mautic.core.permissions.editother',
                'editown'   => 'mautic.core.permissions.editown',
                'deleteother' => 'mautic.core.permissions.deleteother',
                'deleteown' => 'mautic.core.permissions.deleteown',
                'full'        => 'mautic.core.permissions.full',
            ],
            'label'  => 'mautic.lead.permissions.lists',
            'data'   => (!empty($data['lists']) ? $data['lists'] : []),
            'bundle' => 'lead',
            'level'  => 'lists',
        ]);`


In file **app/bundles/LeadBundle/Controller/ListController.php**
Replace code on line 38

`$permissions = $this->get('mautic.security')->isGranted([
            'lead:leads:viewown',
            'lead:leads:viewother',
            'lead:lists:viewother',
            'lead:lists:editother',
            'lead:lists:deleteother',
            'lead:lists:viewown',
            'lead:lists:editown',
            'lead:lists:deleteown',
        ], 'RETURN_ARRAY');`

Finally add filter if viewown was checked.
add this code around line 38 bellow if (!$permissions['lead:lists:viewother']) condition
`if ($permissions['lead:lists:viewown'])
       {
          $filter['force'] = "is:mine";
       }`


**If you have any questions just comment and i will help :)**

**Comment by escovici** [comment]
Hi and happy new year.
Unfortunately, gmail throws emails from this thread in Updates.
That installation of mautic was a separate VM with debian 8 and with only Mautic on it. Right now it is no longer available, but I will make a new VM for testing it, as I want to implement it as a permanent solution.

I have to mention this VM was accessed via another VM which is hosts the main webserver. In one of the virtual hosts, I have defined a virtual directory /newsletter with apache proxy.

I will try to replicate this again, try to access it both directly and through apache proxy and also test the proposed changes.

**Comment by alanhartless** [comment]
I cannot replicate this on 2.7. If this is still an issue, let us know and we'll reopen.
