### ISSUE TITLE
Landing pages should use relative paths for theme images

### ISSUE THREAD

**Issue by mingfang** [mautic/mautic#3114]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? |  Y

## Description:
I administer Mautic by accessing it using an internal url that is different from the public facing url.
We I create landing pages, the theme images referenced using a full url that includes the internal url.
As a result, user coming in from the public url can not see the images.
An easy solution would be to reference theme images without the host part of the url. 
e.g.  from ```http://localhost/themes/skyline/img/bg.gif``` to ```/themes/skyline/img/bg.gif```
It appears theme css are already working the same way.

**Comment by escopecz** [comment]
What would be the solution for images in emails?

**Comment by mingfang** [comment]
Yes, I see your point about emails needing the full url.
Can we at least use the ```site_url``` that was configured in ```local.php```?

**Comment by escopecz** [comment]
We could use that setting, but it could break Mautic instances which doesn't have Site URL filled correctly. In that case it would be breaking change and then it must be part of the next breaking compatibility release Mautic 3.0.0.
