### ISSUE TITLE
Bug when send e-mail to users

### ISSUE THREAD

**Issue by matsunaga** [mautic/mautic#3115]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y|
| Feature request? | N|
| Enhancement? | N|

## Description:
Delivering mail to users with templates created by e-mail in the channels Even if select a template when setting, the content of the template is not reflected in Javascript because of the error in Javascript.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0|
| PHP version | 5.6.28|

### Steps to reproduce:
1. Access https://domain.com/s/contacts
2. Select "Send mail".
3. Select "Import from an existing template" .
4. Select the template created.
5. Select a template, the content of the template you created in Body does not fit.
 
### Log errors: 

Javascript error occurred

```
VM610:2 Uncaught SyntaxError: Unexpected identifier
    at eval (<anonymous>)
    at Function.globalEval (libraries.js?v06c9a21c:149)
    at jQuery.fn.init.domManip (libraries.js?v06c9a21c:470)
    at jQuery.fn.init.append (libraries.js?v06c9a21c:458)
    at jQuery.fn.init.<anonymous> (libraries.js?v06c9a21c:465)
    at jQuery.access (libraries.js?v06c9a21c:343)
    at jQuery.fn.init.html (libraries.js?v06c9a21c:462)
    at FE.set (froala_editor.js?v06c9a21c:4062)
    at HTMLTextAreaElement.<anonymous> (froala_editor.js?v06c9a21c:328)
    at Function.each (libraries.js?v06c9a21c:149)
globalEval	@	libraries.js?v06c9a21c:149
domManip	@	libraries.js?v06c9a21c:470
append	@	libraries.js?v06c9a21c:458
(anonymous)	@	libraries.js?v06c9a21c:465
jQuery.access	@	libraries.js?v06c9a21c:343
html	@	libraries.js?v06c9a21c:462
set	@	froala_editor.js?v06c9a21c:4062
(anonymous)	@	froala_editor.js?v06c9a21c:328
each	@	libraries.js?v06c9a21c:149
each	@	libraries.js?v06c9a21c:139
$.fn.froalaEditor	@	froala_editor.js?v06c9a21c:304
(anonymous)	@	app.js?v06c9a21c:429
success	@	app.js?v06c9a21c:203
fire	@	libraries.js?v06c9a21c:328
fireWith	@	libraries.js?v06c9a21c:333
done	@	libraries.js?v06c9a21c:653
(anonymous)	@	libraries.js?v06c9a21c:670
```

**Comment by escopecz** [comment]
I cannot replicate this issue. Does it happen only for specific theme? Or in a specific browser? Could you provide a screenshot of what "Body does not fit" means?

**Comment by matsunaga** [comment]
@escopecz 
Thank you for your reply.

"Body does not fit" means is It is the text that created the template.
I will attach a screenshot.
If you select the template you created, an error will occur.
*Language is used in Japanese.

Please check the screenshot.
![0602e80c063c2e8cd41632dd60efc0b1](https://cloud.githubusercontent.com/assets/11531826/21669841/824caffa-d352-11e6-8038-e2e7e310e667.png)

**Comment by matsunaga** [comment]
@escopecz 
When creating a mail template the following HTML will be registered in the database.
I think that the cause of this bug is that this HTML is broken.
Please confirm the following HTML.

```
<html>
    <head /><script type="text/javascript">window.NREUM||(NREUM={}),__nr_require=function(e,t,n){function r(n){if(!t[n]){var o=t[n]={exports:{}};e[n][0].call(o.exports,function(t){var o=e[n][1][t];return r(o||t)},o,o.exports)}return t[n].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o
        <div>
            <center>
                <table style="width: 600;" width="600" cellpadding="0" cellspacing="0">
                    <tbody>
                        <tr>
                            <td>
                                <div style="min-height: 30px">
                                    <div data-slot="text">
                                        <br />
                                        <h2>Hello there!</h2>
                                        <br />
                                        We haven't heard from you for a while...
                                        <br />
                                        <br />
                                        {unsubscribe_text} | {webview_text}
                                        <br />
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </center>
        </div>
    <script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","licenseKey":"87b401510d","applicationID":"17239809","transactionName":"YgNWbBNTD0AEWxYNX1tJdVsVWw5dSlUDEURcBWtdDFMIXzpZARBZWgg=","queueTime":0,"applicationTime":650,"atts":"TkRVGltJHE4=","errorBeacon":"bam.nr-data.net","agent":""}</script></body>
</html>
```

**Comment by escopecz** [comment]
The JS on the second line is broken. Could you provide a valid HTML to test with?

**Comment by matsunaga** [comment]
@escopecz
Thank you for your reply.

I am aware that JS on the second line is broken.
This HTML becomes HTML saved in the database when creating with a new mail template from Channel - Emails, it becomes HTML generated by Mautic side.

There is no bug in the process of generating HTML when creating with a new mail template from Emails.
Please confirm the above.

**Comment by escopecz** [comment]
I will need a valid HTML to test with.

**Comment by matsunaga** [comment]
@escopecz
Thank you for your reply.

I do not customize Mautic.
Download ZIP from the official website and use it as it is.

Please create an Emails template from Channel - Emails - New Mail Template and check the database.
There is the above HTML in the database, and since that HTML is broken in the first place, it is not possible to check valid HTML.
I also want valid HTML.

**Comment by escopecz** [comment]
Ah, ok. That is the Blank Theme HTML. I thought it was your custom. 

Mautic does not add the `window.NREUM...` JS into the HTML. When you google it, it's JS from New Relic. Try to disable New Relic on the server or if it is a browser extension, remove it from your browser.

**Comment by matsunaga** [comment]
@escopecz
Thank you for your reply.

New Relic is not used.
Because we are manipulating Mautic in Chrome's incognito mode of the browser, we think that Chrome add-ons are also disabled.

Channel - Emails - New Mail Template - Edit and edit the builder in Blank, after adaptation, if you reopen the builder, the text you entered will not be displayed and you can not edit it.

Can not you reproduce the bug that will generate this invalid HTML in your environment?
Please confirm.

**Comment by escopecz** [comment]
I confirm that it works for me. No JS errors are thrown and the email is sent. HTML is not corrupted with New Relic JS. It must be issue in your environment.

**Comment by matsunaga** [comment]
@escopecz
Thank you for your reply.

After all, New Relic JS becomes an error in my environment.
Is there a way to stop New Relic JS that is inserted automatically?

**Comment by escopecz** [comment]
Thanks for confirmation it's not Mautic's issue. That's probably question to New Relic
