### ISSUE TITLE
JS error when updating

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#312]
When updating to 1.0.3 the updater hangs on "Downloading Package in Progress" and the page gives a rather general JS error: 
```update:1 Uncaught SyntaxError: Unexpected token }```

**Comment by alanhartless** [comment]
Hi,

Sorry about the delayed reply.  If it is hitting that during the downloading package step, it's possible that an error is being returned. Can you check your app/logs/mautic_prod.php log to see if anything was/is recorded?

Thanks,
Alan

**Comment by wderuijter** [comment]
Hi! The last line in the error log show this:
````[2015-04-23 05:59:16] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Sorry! The requested URL was not found." at /var/www/vhosts/example.com/httpdocs/example.com/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 151 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Sorry! The requested URL was not found. at /var/www/vhosts/example.com/httpdocs/example.com/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:151)"} []````

**Comment by alanhartless** [comment]
Was this still an issue with 1.0.4 and 1.0.5? The error logs doesn't indicate anything that would affect an upgrade.

**Comment by wderuijter** [comment]
Hey Alan, haven't got SSH access and I haven't been able to upgrade beyond 1.0.2.
Is there a way to manually update to 1.0.3 so I can try if it allows me to update properly?

**Comment by wderuijter** [comment]
The update from 1.0.2 to 1.0.5 went perfect now.
