### ISSUE TITLE
Hubspot plugin lead field mapping missing in 2.4.0 upgrade

### ISSUE THREAD

**Issue by abhayasimha** [mautic/mautic#3122]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No
## Description:
The hubspot plugin lead field mapping missing after 2.4.0 upgrade. Now the new contacts are not moving to Hubspot plugin which was working proper in 2.3 version.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version |

**Comment by escopecz** [comment]
This was fixed in some previous versions already.
