### ISSUE TITLE
Using segment:alias as a Contact Search in API

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3125]
I'm trying to pull contacts from the API and it works fine using other search parameters like like email address, but I get error when I try to search for contacts in a segment.

For example, this code works fine and pulls the contact I'm searching for:

    $url = $this->base_url.'/api/contacts?search='.urlencode('email:email@email.com').'&orderBy=date_identified&orderByDir=desc&limit=500';`

But this returns an error:

    $url = $this->base_url.'/api/contacts?search='.urlencode('segment:segment-alias').'&orderBy=date_identified&orderByDir=desc&limit=500';

This is the error:

**An exception occurred while executing 'SELECT COUNT(DISTINCT(l.id)) as count FROM leads l LEFT JOIN users u ON u.id = l.owner_id INNER JOIN lead_lists_leads list_lead ON l.id = list_lead.lead_id INNER JOIN lead_lists list ON list_lead.leadlist_id = list.id WHERE ((list_lead.manually_removed = 0) AND (list.alias LIKE ?)) AND (())' with params ["segment-alias%"]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))' at line 1**

If I try using the segment name, instead of it's alias, it just doesn't return anything, but also doesn't give an error:

    $url = $this->base_url.'/api/contacts?search='.urlencode('segment:List Name').'&orderBy=date_identified&orderByDir=desc&limit=500';

Am I doing something wrong here, or is there a bug that doesn't allow for searching for contacts that are members of a segment?

Thanks

**Comment by nickian** [comment]
Solved my own problem here. For anyone else wondering:

The query on segments should be the alias wrapped in quotes. So, this is what works:

    $url = $this->base_url.'/api/contacts?search='.urlencode('segment:"segment-alias"').'&orderBy=date_identified&orderByDir=desc&limit=500';

**Comment by dhirendradaffodil** [comment]
can you please let me know how I can pass date filter in below 

$url = $this->base_url.'/api/contacts?search='.urlencode('segment:"segment-alias"').'&orderBy=date_identified&orderByDir=desc&limit=500';

I want something like that 

 $search =$this->base_url.'/api/contacts'?search='.urlencode('segment:"dev-testlist"').'**&dateFrom='.$start_date.'&dateTo='.$end_date**.'&orderBy=date_identified&orderByDir=desc&limit=500';  

But its now working, need to filter by date range
