### ISSUE TITLE
Running Mautic inside an iframe

### ISSUE THREAD

**Issue by randallsevery** [mautic/mautic#3126]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
As part of integrating an installation of Mautic with other web applications, we are running Mautic inside an iframe.  For the most part this works without any problems, and worked flawlessly in older versions of Mautic.  But recent versions of Mautic, including version 2.4.0, have some issues with incorrect references to the "parent" element in calls to "parent.mQuery" in media/js/app.js.  Some of the calls are made from child windows and work fine, others are called from the top-level Mautic window and are trying to find an "mQuery" object in the parent window and fail.  When running Mautic outside of an iframe, the incorrect "parent" references refer to the current window (since the parent of the top window is the top window itself), but inside an iframe those incorrect references are, well, incorrect :-).  I have worked around the issue temporarily by inserting the following code before every reference to "parent.mQuery" in media/js/app.js and changing "parent.mQuery" to "parent_mQuery", but it's an ugly hack:

if (typeof(parent.mQuery) == 'function') var parent_mQuery = parent.mQuery; else parent_mQuery = mQuery;

It would be helpful if the code in media/js/app.js used parent.mQuery only when actually needed to refer to the parent window and not relying on the top window ignoring the incorrect parent reference.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | 7.0.11

### Steps to reproduce:
1. Load Mautic inside an iframe
2. Navigate around Mautic screens and look for JavaScript errors in the browser console

**Comment by mrinc** [comment]
Hey,

Have you tried setting the iframe using sandboxed mode?

I find that to be quite effective for every single iframe that has issues.

sandbox="allow-same-origin allow-scripts allow-popups allow-forms"

That should do it.

-M

**Comment by MaMuk** [comment]
sandboxing the iframe does not solve the problem for me. I still get this error when trying to laod the builder in an Iframe.
![mauitc-mquery-fehler](https://user-images.githubusercontent.com/11556112/28059250-dd2aa7d8-6623-11e7-9530-52df27d93f53.png)

**Comment by namratasaun** [comment]
Was anyone able to open it in an iframe?
