### ISSUE TITLE
Ability to disable cookies tracking by client

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3133]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
In some countries and especially in Europe the law has been updated and clients (visitors of a website) must have the ability to disable cookie tracking.
![10438939](https://cloud.githubusercontent.com/assets/14075239/21449987/11f3d4f4-c8f3-11e6-80ce-96b024514dc5.jpg)

Consequently, it would be great to have a feature that help to disable cookie tracking by the visitor via a click on a button, something like `{disable_cookie}` and `{enable_cookie}`.

**Comment by npracht** [comment]
Closed in favor of https://github.com/mautic/mautic/issues/2911

**Comment by dsp76** [comment]
@npracht however, #2911 unfortunately has been closed by @dbhurley without a reason...
Its really one of the few left things that would allow GDPR compliant use of Mautic from May 2018.

**Comment by rybskiryba** [comment]
Was there any update no that issue?
