### ISSUE TITLE
Ability to custom column displayed on contact view table

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3137]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
It would be great to be able to customize the contact field displayed on the contact menu overview. Maybe for some people, points, stages and location is not an important value and some other could be.

Think about the same flexibility for companies.

**Comment by escopecz** [comment]
This seems to be similar to https://github.com/mautic/mautic/issues/120
