### ISSUE TITLE
Get all tags list from Mautic via API

### ISSUE THREAD

**Issue by rahulwalunje** [mautic/mautic#3139]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | /
| Feature request? | Y
| Enhancement? | /

## Description:
One can get all tags created in Mautic. There should be some GET request which will return list of all tags.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Do you mean via API?

**Comment by rahulwalunje** [comment]
Yes. Some end point in API.

**Comment by moskoweb** [comment]
Any news on this feature?

**Comment by escopecz** [comment]
Tags API endpoints are ready to be tested in https://github.com/mautic/mautic/pull/5204
