### ISSUE TITLE
CronFig  - secret key 

### ISSUE THREAD

**Issue by apuestaya** [mautic/mautic#3140]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? N| 
| Enhancement? | N

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4
| PHP version | 5.6

### Steps to reproduce:
1. run cronjob with plugin 
2. error secret key

It was genereated in plugins/CronfigBundle/Controller/PublicController.php at line 37
`$secretKey = $this->request->query->get('secret_key');`

I checked  config file app/bundles/CoreBundle/Config/config.php
and there is a secret_key parameter empty. Is it causing this error?

Thank you for this great program.
 
![captura](https://cloud.githubusercontent.com/assets/11563358/21486641/fb56c8ec-cb85-11e6-9ccc-e50613bb0212.PNG)

### Log errors: 

there is nothing in my error log.

**Comment by escopecz** [comment]
Cronfig is a 3rd party plugin. Please subscribe to the issue report there: https://github.com/cronfig/mautic-cronfig/issues/2
