### ISSUE TITLE
Docs for adding Email Services

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#3141]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
I've been looking at the source code for the current email clients but haven't been able to properly use them to integrate Mailgun, Amazon SES or other services. It'd be great if there's a doc and boilerplate code that we could use to integrate other email APIs.

**Comment by franciscojun** [comment]
+1

**Comment by escopecz** [comment]
It would make more sense to open this issue in the developer documentation repository: https://github.com/mautic/developer-documentation
