### ISSUE TITLE
[Feature Request] Add console command to clear cache stored in database

### ISSUE THREAD

**Issue by hissy** [mautic/mautic#3144]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes 
| Enhancement? | Yes

## Description:
If you change domain of your mautic instance, generate.js provides forms with old domain, because scripts are stored in database (`forms.cached_html`). There is no way to clear these data.

**Comment by escopecz** [comment]
![mautic-clear-form-cache](https://cloud.githubusercontent.com/assets/1235442/21496582/df2b83b6-cc1f-11e6-90f5-44eda28888cb.png)

**Comment by hissy** [comment]
Wow. Sorry.
