### ISSUE TITLE
Outlook DPI settings are erased even in Code Mode

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3148]
| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:

The following Outlook DPI settings are altered upon saving an email even if that email is using the Code Mode.

```html
<!--[if gte mso 9]><xml>
 <o:OfficeDocumentSettings>
  <o:AllowPNG/>
  <o:PixelsPerInch>96</o:PixelsPerInch>
 </o:OfficeDocumentSettings>
</xml><![endif]-->
```

It is then replaced with the following which simply displays the number 96 when viewed in Outlook.

```html
<!--[if gte mso 9]>


  96

<![endif]-->
```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | 7.0.14

### Steps to reproduce:
1. Create an email containing the above snippet.
2. Save
3. Preview and view the source code

**Comment by escopecz** [comment]
The stripping is happening here: https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/Form/Type/EmailType.php#L75

Lets discuss how to disable stripping and does not allow any dangerous code to be saved.

**Comment by MaxWebmecanik** [comment]
@escopecz I don't understand why any stripping needs to be done.

As long as the code is properly escaped while being edited so as to not leak into the back office, it becomes the user's responsibility to produce _safe_ content.

What exactly are you picturing when you say _dangerous code_?

**Comment by mmmichael** [comment]
Hello, for me the (quick&dirty) solution is, to comment out https://github.com/mautic/mautic/blob/staging/app/bundles/CoreBundle/Helper/InputHelper.php#L393

**Comment by MaxWebmecanik** [comment]
Hi @escopecz, any feedback on this?

**Comment by MaxWebmecanik** [comment]
@mmmichael My solution was to delete this line https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/Form/Type/EmailType.php#L75
Why did you comment out the one you linked to?

**Comment by alanhartless** [comment]
There are lots of saas products based on this (obviously us included) so some level of sanitization is needed in order to protect against those that could potentially leverage these saas products to spread dangerous content. Maybe we can use a preg_match solution to catch and restore valid outlook XML as we do if comments, doctype, etc in InputHelper.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/3476, in this commit:https://github.com/mautic/mautic/pull/3476/commits/548d1aa982baeacbfaae32eba8fd34029e3a3aa1

Unit tests added to ensure it will won't break in the future.
