### ISSUE TITLE
Error Log Array to string conversion - in file /var/www/html/app/bundles/CoreBundle/Helper/InputHelper.php - at line 310 

### ISSUE THREAD

**Issue by Mirz** [mautic/mautic#3150]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
System error log is showing an array to string conversion error in file /var/www/html/app/bundles/CoreBundle/Helper/InputHelper.php - at line 310

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | 7.0.13

### Steps to reproduce:
1. Error notice is appearing in the System Info Log available in the admin dashboard. 
2. 
 
### Log errors: 

mautic.NOTICE: PHP Notice: Array to string conversion - in file /var/www/html/app/bundles/CoreBundle/Helper/InputHelper.php - at line 310

**Comment by rudwolf** [comment]
Any news about fixing this? I got the error too!

**Comment by escopecz** [comment]
@rudwolf it would help to get steps to reproduce. It's hard to fix something what I cannot experience myself.

**Comment by rudwolf** [comment]
I happens sometimes when I use a capture form to get data such as email adress, name and lastname... sometimes when the form is submitted i get this error.

**Comment by dbhurley** [comment]
Need more details about how to recreate the error.

**Comment by daniellord32** [comment]
I came across this when testing a form submission from a different url (using the form api to display a form on a webpage).

I noticed in the PublicController in App/bundles/FormBundle calls the inputhelper on line 46 which processes as expected.
Later in the same controller
`$result = $this->getModel('form.submission')->saveSubmission($post, $server, $form, $this->request, true);` 
In the saveSubmission() function the inputHelper is called again, what is happening to me currently is that $parts['scheme'] is expected to be a string but this time it is changed to an array with the following values
$parts [
     'scheme'[
           'mauticError',
           'mauticMessage'
]
This throws a 500 error array to string conversion when we get to the following line of code in the return of the fuction
`(!empty($parts['scheme']) ? $parts['scheme'].'://' : '').`

This happens in the SubmissionModel->saveSubmission() function on line 218
