### ISSUE TITLE
Error in submitting forms and updating GeoLite2-City.mmdb

### ISSUE THREAD

**Issue by andersonojope** [mautic/mautic#3162]
#What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:

After updating to version 2.4, an error message appears when updating the GeoLite2-City.mmdb database (either manually or via cron) and when the forms are submitted, they do not end (the sent message does not appear with Success or page redirection)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | 7.0

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

[2016-12-30 14:44:34] mautic.WARNING: IP LOOKUP: Error opening database file (/.../app/cache/prod/../ip_data/GeoLite2-City.mmdb). Is this a valid MaxMind DB file? [] []

[2016-12-30 14:42:32] mautic.WARNING: PHP Warning: gzdecode(): data error - in file /.../app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php - at line 87 [] []

**Comment by mqueme** [comment]
Did you try to delete your cache and refresh?

**Comment by andersonojope** [comment]
Yeah. I already did that.

I will always test some solution is the first thing I do.

**Comment by keithmautic** [comment]
Any update on this, this is definitely causing an issue

**Comment by andersonojope** [comment]
Does this have to be with the PHP configuration?

I ran a test and installed the same files and databases on another server and it worked correctly.

What do you think?

**Comment by mqueme** [comment]
If the file is there, and can't open seems to me like file permissions. If you say it runs on another server, then its definitely server related and not a Mautic issue.

**Comment by andersonojope** [comment]
I could not solve the problem with the hosting I used and I switched to a VPS.

In this new VPS the same installation did not show any errors and is working correctly.

I did not find out what it was, but the problem is solved.

**Comment by BernardiSena** [comment]
Apparently error disappeared after creating an external cron job.
