### ISSUE TITLE
Link to an asset without tracking?

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3166]
Is it possible to link to an asset (like an image) without tracking it? It seems unnecessary at times. For example, if I have an email with images embedded that are hosted in Mautic's asset manager, I don't want to show a bunch of asset downloads for each image in a user's timeline every time they open an email I sent.

Is it, or would it be possible to add a parameter to ignore tracking? For instance embedding an image with something like this:

http://mymautic.com/asset/1:my-imagejpg?stream=1&track=0

Thanks!

**Comment by escopecz** [comment]
Sure, use the image slot for images you don't want to track:
![mautic-image-slot](https://cloud.githubusercontent.com/assets/1235442/21602075/a5f56794-d190-11e6-9259-12fcc4549732.png)

**Comment by nickian** [comment]
Oh ok, I see you can do it in the builder, but I don't use the builder for emails. I use the code editor option and bring in custom code each time. Also, what if I want to not track an image unrelated to an email, like something that just goes in everyone's email signature, etc.?

Thanks

**Comment by escopecz** [comment]
![code-mode-media-manager](https://cloud.githubusercontent.com/assets/1235442/21636645/be10e924-d263-11e6-85f0-03ade4951dc9.png)


https://mautic.org/docs/en/themes/code_mode.html#media-manager

https://mautic.org/docs/en/emails/mailer_is_owner.html

Try to find the answers to your questions before asking someone else, please.

**Comment by nickian** [comment]
Oh, thanks! Not sure how I missed that one!
