### ISSUE TITLE
API Email Send Out Issue

### ISSUE THREAD

**Issue by htlPaul** [mautic/mautic#3168]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | Yes

## Description:
Hi,

Good day!

I'm Paul, a consultant at HTL Group, and we would like to report that your versions of Mautic 2.2.1 and 2.3 are having issues when calling the API base email send out. Currently, we are using a separate PHP script in which utilized the API base commands of Mautic and prior to 2.2.1 this script was working perfectly for us. We only notice this issue when we have adopted the new versions that you have released. And because we need the email API badly for the approach that we are using in our application is somewhat hard to reconstruct, we decided to give your team a message about the matter. But we have not yet received any response on our post on the forum so we decided to check the core files of Mautic. And upon checking, we discovered an error on EmailApiController.php under app/bundles/EmailBundle/Controller/Api, particularly on the class function sendLeadAction, where when the application calls this condition

if (MailHelper::applyFrequencyRules($lead)) {
...
}

an error occurs. When we try to force the contents of the error from the value returned by the API this is displayed:

<b>Fatal_error</b>:__Cannot_access_protected_property_Mautic\EmailBundle\Controller\Api\EmailApiController::$factory_in_<b> ../app/bundles/EmailBundle/Helper/MailHelper_php</b>_on_line_<b>1843</b><br_/>

We modified the template discussed on the error as the factory variable found under the MailHelper seems to be not defined on this function. However, after the modification, another variable seems to be lost as the frequencyRule is catching a Null value. And for this reason, we decided to skip the condition by commenting it in calling the class function applyFrequencyRules as we don't have the exact knowledge about the purpose of this helper which may bring more issue if we tried to amend it. Also, this is the main reason why the email is not functioning on the API side. With this in mind, we would like to notify your team about this matter so that adjustments maybe made on this end of Mautic for the next release.

We hope for an urgent response on that matter as this is connected with our application. Thank you and have a great day a head.

Thanks,

HTL Group team

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Mautic 2.2.1, 2.3 and 2.4 
| PHP version | Latest

### Steps to reproduce:
1. Create an API base file script connected with Mautic
2. Set all configuration including the ids of the need segments, campaign and/or email on a config file
3. Run the script
 
### Log errors: 

<b>Fatal_error</b>:__Cannot_access_protected_property_Mautic\EmailBundle\Controller\Api\EmailApiController::$factory_in_<b> ../app/bundles/EmailBundle/Helper/MailHelper_php</b>_on_line_<b>1843</b><br_/>

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mqueme** [comment]
This seems to have been fixed in version 2.4. can you please review that it's not happening in 2.4 ?

**Comment by htlPaul** [comment]
We will try again to test this using the latest 2.4 but on our initial screening of that version it seems that the the coding part of it is like 2.3 and we have test it several times and the findings were the same. Moreover, upon modifying it by overriding the factory declaration inside the applyFrequencyRules function with an added parameter being passed along the lead param of the function, another issue arises as inside the applyFrequencyRules the variable frequencyRule keeps on getting a null value from our test even though the lead is properly set. And for this, we have omitted the condition on the controller section used on this API call on our copies now to avoid further damage because don't have any background of the real purpose of applyFrequencyRules. We only assumed that this is really for the stats. Anyway, the action made is just temporary measure to make our app be up and running and personally, I could not passed this up on your end as the function applyFrequencyRules really has a purpose for if not you guys would not add it on your releases.

**Comment by escopecz** [comment]
It was really fixed a few weeks ago. I wrote a test for it so we'll be sure it's working in the future releases: https://github.com/mautic/api-library/blob/master/tests/Api/EmailsTest.php#L231

If you have problems with it on 2.4 or 2.5 which will be released soon, let us know what parameters are you using and if the contact have some special fields/values we need to replicate it.

**Comment by htlPaul** [comment]
Okay we will again check the matter. Anyway, a curious question is 2.4 your stable version?

**Comment by escopecz** [comment]
I don't see why not. Should be more stable than 2.3 ;)

**Comment by htlPaul** [comment]
Ah ok. The reason I ask it for my boss directed us not to use any latest version of Mautic until we are certain it is stable for it consume time on our end to update our app in each releases. Anyway, we will again check the matter. I just notice now that you have updated also your developer page.

**Comment by escopecz** [comment]
Fixed in 2.4
