### ISSUE TITLE
Feature Request - Honeypot Option / spam

### ISSUE THREAD

**Issue by versadial** [mautic/mautic#317]
For spam, I would suggest a honeypot option. The captcha and quiz option relies too much on human interaction. The honeypot trick is a nice feature. 

I also have reached out to a company who created cleantalk (plugin for wordpress and other CMS). Hopefully they can figure out a way to integrate as well.

**Comment by 4evermaat** [comment]
was this ever implemented?

**Comment by rcarloscalderon** [comment]
Chiming in to bump this feature request up. A honeypot field would be extremely helpful.

**Comment by Getron** [comment]
+1

Is this added ever?

**Comment by versadial** [comment]
According to the merge alan did..he added:
It adds support for honey pot captcha. Just leave the Captcha Answer blank to treat the captcha as a honeypot.

So..a blank answer goes through. I have not tested it...as I use my old setup currently with the manual captcha answer added in the database. I assume this method of blank form entry works the same? I remember before they required an answer in the captcha form field, my guess is they removed this requirement.
