### ISSUE TITLE
Add condition filter on zipcode "starts with"

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3171]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
When you start segmentation on the field `zipcode` you have the available conditions:
* Contains
* Not contains
* Empty
* Not empty
* Equal
* Different

### What we're missing
Zipcodes are built a way that you can understand what is the concerned departements and region in the country according to the numbers. But you cannot make selection with the **contains** but it should be **start with**.

Indeed, for the region of Paris (France) for instance all the zipcodes start with `75***` (eg. 75000, 75001, 75002, etc.). But you cannot make a filter like contain 75 because it exists some zipcode like `***75` or `**75*` or `*75**` (eg. 30075).

### conclusion of the requested filters on zipcode
* start with

**Comment by dbhurley** [comment]
Are you able to start coding on this? If not then I'd suggest posting here instead: https://www.mautic.org/forums/forum/ideas/

Once you have some code ready to propose or developers engaged in the idea it can then be placed on GitHub.
