### ISSUE TITLE
Social Login Error

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#3175]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:

Mautic Social Login does'n work. I found this message on javascript console:

SecurityError: Blocked a frame with origin "/" from accessing a cross-origin frame.
 /plugins/integrations/authstatus/Facebook:147

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5
| PHP version | 7.0

### Steps to reproduce:
1. Configure Social Login Plugin
2. Include Mautic Form Script on Wordpress
3. Click on Facebook Icon
4. After authorization, this message apper on javascript console: SecurityError: Blocked a frame with origin "/" from accessing a cross-origin frame.
 /plugins/integrations/authstatus/Facebook:147
 
### Log errors: 

SecurityError: Blocked a frame with origin "/" from accessing a cross-origin frame.
 /plugins/integrations/authstatus/Facebook:147

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by luizeof** [comment]
@alanhartless  @escopecz

**Comment by escopecz** [comment]
Try this:
1. Go to Mautic configuration
2. Enable CORS
3. White-list the domain of your website
4. Save
5. Test the social login again

**Comment by luizeof** [comment]
@escopecz it doesn't work too. :(

**Comment by escopecz** [comment]
I just tested social login several times while testing 2 pull requests for Mautic 2.8.2. It worked for me with or without them, but wait for the update and test if it's better for you. If not, let us know. I'll close this for now.
