### ISSUE TITLE
Gated Video Embeds issues with existing MediaElement.js objects

### ISSUE THREAD

**Issue by squeral** [mautic/mautic#3177]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I use MediaElement.js on my website and mtc.js (which includes a version of MediaElement.js) is preventing my videos from playing.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.0
| PHP version | 

### Steps to reproduce:
1. Place Mautic's tracking code on a html file that already has a video using MediaElement.js
2. Once the MauticJS is loaded you'll no longer be able to play the videos

**Comment by squeral** [comment]
Documentation says that:

> Any <video> tag found by the javascript that has a data-form-id and data-gate-time attribute will be treated as a gated video by the Mautic javascript.

So, my workaround was to change the way the video elements are found in: https://github.com/mautic/mautic/blob/master/app/bundles/PageBundle/EventListener/BuildJsSubscriber.php#L210

By changing `document.getElementsByTagName('video')` to `document.querySelectorAll('video[data-form-id][data-gate-time]')`

**Comment by luizeof** [comment]
+1

**Comment by lloyd678** [comment]
+1

**Comment by MarkLL** [comment]
@squeral unfortunately `document.querySelectorAll('video[data-form-id][data-gate-time]')` does not work because it does not return a HTMLCollection. I attempted an alternate fix in PR https://github.com/mautic/mautic/pull/3350. See if it works for you.
