### ISSUE TITLE
Monitored Email Address SAML Login?

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3183]
We are using SAML through Okta to log into Gmail accounts. I have a "bounce" gmail address with IMAP enabled, but I can't login through Mautic. I get this error:

"Error communicating with the IMAP server: Can not authenticate to IMAP server: [ALERT] Please log in via your web browser: https://support.google.com/mail/acco"

Is it possible to set up a monitored address that requires a SAML login? Is this feature possible? The alternative is to have a separate domain with MX records pointing to a different mail server for bounces.

Thanks

**Comment by dbhurley** [comment]
Currently this feature is not possible.
