### ISSUE TITLE
Last Active in Contacts view doesn't match contact events time-line

### ISSUE THREAD

**Issue by medianicus** [mautic/mautic#3184]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Since updating to 2.5.0, the Last Active date and time in the Contacts list don't always match the contacts time-line events.

![image](https://cloud.githubusercontent.com/assets/21250672/21665033/123068c8-d29f-11e6-8227-beb7fc900735.png)

![image](https://cloud.githubusercontent.com/assets/21250672/21665057/3fc5d3ea-d29f-11e6-9139-f1b3aeb5015a.png)

This is happening on two different installations, one v2.5.0 and one v2.5.1. 

If it's relevant, the 2.5.0 version uses JS tracking script and the 2.5.1 uses the most recent WPMautic plugin.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.0
| PHP version | 7.0.14

### Steps to reproduce:
1. View Contacts list
2. Click on Contact to view last event

**Comment by pageagency** [comment]
I am experiencing the same issue. Any progress on this?

**Comment by npracht** [comment]
Guys, if you open the email action, you'll see all open dates. The last much match to the last active date. be careful, if the email has been open several times, there is a little very little button on the bottom of the list that says `[+ more]` :-)

@escopecz it is not an issue :)
