### ISSUE TITLE
Campaign Statistics not Showing in Graph

### ISSUE THREAD

**Issue by medianicus** [mautic/mautic#3185]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Since update to 2.5.1, the graph in the Campaign Statistics shows 0 contacts added even though 4500 contacts were updated successfully.

![image](https://cloud.githubusercontent.com/assets/21250672/21665166/e8e85542-d29f-11e6-9f79-46c0185ae21b.png)

![image](https://cloud.githubusercontent.com/assets/21250672/21665237/43f8d20e-d2a0-11e6-99f3-52c57c9cc858.png)

****

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0.14

### Steps to reproduce:
1. Create and launch a campaign
2. Wait for cron job
3. View campaign
4. Graph not updated although campaign is successful
 
### Log errors: 
[2017-01-04 15:50:44] mautic.ERROR: Deprecation: Symfony\Component\DependencyInjection\Definition::setFactoryService(doctrine) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. - in file /var/www/vhosts/domain.tld/sub.domain.tld/vendor/symfony/dependency-injection/Definition.php - at line 204 [] []

**Comment by medianicus** [comment]
Update:

The graph is now showing the contacts as having been added today, even though the campaign was unpublished at 5:13pm PST yesterday.

![image](https://cloud.githubusercontent.com/assets/21250672/21701846/007ad064-d35d-11e6-9a70-d8e9d7967f64.png)


![image](https://cloud.githubusercontent.com/assets/21250672/21701777/8db6a4e0-d35c-11e6-80ec-2675da5d4cf3.png)


The campaign executed successfully yesterday but it seems like Mautic is assigning the date as the following day, not the current one.

**Comment by dbhurley** [comment]
Is this still an issue in 2.11?
