### ISSUE TITLE
Bug Report: can't save email settings (Call to undefined method setApiKey)

### ISSUE THREAD

**Issue by sagistrauss** [mautic/mautic#3188]
I'm trying to save new email settings, there are no visible errors but the new settings are not saved.

Mautic version 2.5.1.

### Steps to reproduce:
1. Settings -> Email Configuration
2. Save/Apply
 
### Log errors: 

[2017-01-05 05:37:10] mautic.ERROR: PHP Error: Call to undefined method setApiKey - in file /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php - at line 291 [] []

**Comment by IADDIC** [comment]
Be sure to fill in data for User/Authentication Settings.  It could be just placeholders at this point.  There is a bug that prevents saving configuration data until those fields are populated.  I think there is a fix for that issue.

**Comment by keetonet** [comment]
I'm having the same problem (with the same version of Mautic). It allowed me to save the values once on initial install, but after going back in to make adjustments for a new delivery service, I'm getting the same setApiKey error above.

I've attempted to fill in the entire page's worth of data (including user/auth settings as suggested) and nothing works.

**Comment by wucherpfennig** [comment]
+1

**Comment by CoolBlackFriend** [comment]
I'm running into this too. driving me nuts.

**Comment by RCheesley** [comment]
Same problem with setting up SES, either with the SMTP settings or with the in-built Amazon SES settings.

**Comment by Flemish** [comment]
+1 been trying all kind of edits and attempts in local.php, deleting cache, nothing helps. Can't change the email settings. Only the orginal one works, but thats not the one I want to use :/

**Comment by andersonid** [comment]
same here for sendgrid

**Comment by CoolBlackFriend** [comment]
The following worked for me on two separate servers; Both running VestaCP 0.9.8 on CentOS 7.3.1611 in Virtualbox 5.0.30: 

After increasing mariadb wait_timeout, I set the email variables in local.php and then renamed /path_to_mautic/app/cache to /path_to_mautic/app/cache.old, and restarted nginx and apache...now I can send email, and it doesn't goto SPAM! w00t! Hope this helps someone.

**Comment by Paul979** [comment]
This tweak fixed this issue for me: https://www.mautic.org/community/index.php/6558-email-builder-cannot-browse-for-uploaded-images/p1#p18555

I'm still getting the "Call to undefined method setApiKey" error though.

See also the big report and fix: https://github.com/mautic/mautic/pull/3182 (haven't tried that yet)
haven't tried that yet

**Comment by escopecz** [comment]
Please test https://github.com/mautic/mautic/pull/3440 and comment bellow it if it fixed the error you're getting.

**Comment by RCheesley** [comment]
#3440 fixed this issue for me - great work folks
