### ISSUE TITLE
Getting error after update

### ISSUE THREAD

**Issue by davidperezgar** [mautic/mautic#3192]
Hello, I get this error in mautic after update. How can i solve it?

I've got v2.2.

Thanks.
 
### Log errors: 
mautic.ERROR: Deprecation: The alias option of the form.type_extension tag of service "fos_rest.form.extension.csrf_disable" is deprecated since version 2.8 and will be removed in 3.0. Use the extended_type option instead. - in file /mk/vendor/symfony/framework-bundle/DependencyInjection/Compiler/FormPass.php - at line 67

**Comment by escopecz** [comment]
It's just a deprecation notice. It should not cause any troubles. Or is it? What are the steps to replicate?

**Comment by davidperezgar** [comment]
Thanks for your reply. The thing is that is keeping reading and is very slow. And I think is not due of server, something is missing or not working.

**Comment by davidperezgar** [comment]
Ok, I solved the problem. It was the open base dir not enabled.

Thanks and regards.

**Comment by davidperezgar** [comment]
Hello, after enable the Openbase dir, it was working somehow, but now it gives 505 errors in some pages and I cannot log in.

<img width="981" alt="captura de pantalla 2017-01-10 a las 17 47 00" src="https://cloud.githubusercontent.com/assets/10096360/21815425/da0c9de6-d75c-11e6-82cc-96ec5def84cd.png">

**Comment by escopecz** [comment]
Check https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by escopecz** [comment]
Closing for the lack of answer. Feel free to comment with a new update and the issue will be opened again.
