### ISSUE TITLE
mautic as ESP

### ISSUE THREAD

**Issue by peacemakr** [mautic/mautic#3194]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y?
| Enhancement? | 

## Description:
I want to use Mautic as an ESP software for my clients. So, I was thinking of removing the links for other options leaving emails, campaigns etc. Is it something thats possible and won't cause any issues? I am thinking of removing the links from menu.

Also, clients are not supposed to share contacts with each other, so do I need separate installations(PHP files)+databases for each client or there is a better way of handling this particular case? I can understand separate databases but copying the php files does not make sense. However, I don't know if there are any files that might be created locally.

**Comment by escopecz** [comment]
This doesn't seem like a feature request. As I understand what you want is to fork Mautic and remove some features. 

Then you want an advice on how to configure your server setup to host multiple Mautic instances. Discus it in the forum, please: https://www.mautic.org/community
