### ISSUE TITLE
Gmail Folders not able to save in Bounce Settings

### ISSUE THREAD

**Issue by jaschaio** [mautic/mautic#3195]
#What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
If I set up the IMAP Settings within the "Monitored Inbox Settings – Default Account" Section, and click on "test connection and fetch folders" everything seems to work. I can select the folders from within the Bounces and Complaints sections. But when I save the settings the folders get reseted and I get an error message that "This value is invalid". Now I only see the INBOX and TRASH folders within the dropdown fields. If I click again on "test connection and fetch folders" I can select the right folders again, but they get always resetted when saving the options.

Additionally if I navigate completely away from the page the whole IMAP Settings get reseted (empty).

This seems somehow related to issue #1472, but the code that solved the problem their doesn't exists anymore in my mautic version (2.5.1).

I have described the problem in detail with screenshots here: https://www.mautic.org/community/index.php/6551-smtp-settings-doesn-t-get-saved

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0.8

### Steps to reproduce:
1. Loginto Mautic
2. Go to Configuration
3. Go to Email Settings
4. Scroll down to Monitored Inbox Settings
5. Setup a Gmail IMAP Account
6. Click on "Test connection and fetch folders"
7. Select a specific Folder within the "Bounces" Section
8. Select a specific Folder within the "Unsubscribe Requests" Section
9. Save Options, error will be shown.
10. Navigate away from the Page, IMAP Settings get reseted.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by jordan8037310** [comment]
Also experiencing this issue in Mautic 2.4.0

**Comment by jordan8037310** [comment]
I have confirmed this issue's source with one of our Mautic instances last night.

Conditions for failure: 
* Using more than one email for monitoring, e.g. emailA@mysite.com, bounces@mysite.com
* In emailA@mysite.com, there is a subfolder that you are sorting unsubscribes into, e.g. `Unsubscribes`

What Happens
* When you try to save the Unsubscribe folder, it is validating against the wrong email addresses connection settings. It is checking for the existence of a `Unsubscribes` folder in bounces@mysite.com. 
* We're not sure why this is happening, but obviously something is mixed up here.
* We were able to confirm this theory by creating an `Unsubscribes` folder in bounces@mysite.com, and reselecting the `Unsubscribes` folder for the emailA@mysite.com, at which point it accepted the configuration and started processing emails in `emailA/Unsubscribes`.

**Comment by lucagitent** [comment]
Also experiencing this issue in Mautic 2.5, PHP 7.0.14

**Comment by sibben** [comment]
I also had the same issue and managed to solve it.  This problem does still exist in Mautic v2.6.1

The steps to reproduce as described above were exactly the same, I've tried lots of different ways, but no luck. What also was strange, every time I did a 'Test connection and fetch folders' I had to fill the password, while the placeholder says : 'Leave empty for no change' 

I decided to take a look in the logfile (app/logs/mautic_prod-2017-02-25.php ) and saw this message

`mautic.NOTICE: PHP Notice - Undefined variable: dsfBB6 - in file /home/mautic/mautic.sibben.nl/html/app/config/local.php - at line 122 `

So I took a look in the config file ( app/config/local.php ) and saw this 

` "password" => "$%gee$dsfBB6"
`

So it looks like Mautic can't handle $ signs in passwords. 
I changed my IMAP password and tried again, strange enough still no luck. I looks like Mautic cannot change the password in de config file if the current password contains an $ .  I edit the config file and changed the password in there and  YES!!

**Comment by ricardovf** [comment]
I also have this problem in the version 2.8 of mautic.

**Comment by raribeiro** [comment]
I also have this problem in the version 2.8.2

**Comment by MHZarei** [comment]
I have this bug in Mautic 2.8.2 and PHP 7.
But in php 5 it's ok.

**Comment by RCheesley** [comment]
Closing this old issue, feel free to request a re-open if it's still a problem!

**Comment by dhilst** [comment]
I had same problem, things to note

1. Do **NOT** use gmail as bounce will not work with since it rewrite the return path
2. I managed to be able to bypass this by overwriting in `app/config/local.php` file. Search for IMAP and rewrite the folders. Here is my configuration

<img width="597" alt="image" src="https://user-images.githubusercontent.com/392820/89858464-29f80c80-db75-11ea-8777-7dc1afdca0cc.png">

**Comment by yarimiz** [comment]
I'm facing this issue with Mautic 3.1.0 and PHP 7.2

**Comment by wgicio** [comment]
same with v4.2.0-rc1

**Comment by larbi-asmaoui** [comment]
> I had same problem, things to note
> 
>     1. Do **NOT** use gmail as bounce will not work with since it rewrite the return path
> 
>     2. I managed to be able to bypass this by overwriting in `app/config/local.php` file. Search for IMAP and rewrite the folders. Here is my configuration
> 
> 
> <img alt="image" width="597" src="https://user-images.githubusercontent.com/392820/89858464-29f80c80-db75-11ea-8777-7dc1afdca0cc.png">

This solution worked for me
