### ISSUE TITLE
Fonts in email/page builder

### ISSUE THREAD

**Issue by Augentia** [mautic/mautic#3197]
What type of report is this: BUG

| Q  | A
| ---| ---
| Bug report? | BUG
| Feature request? | 
| Enhancement? | 

## Description:
Font selection button not available in 'Builder' (either in Email or Landing Page creation)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.4
| PHP version | v5.6.29

### Steps to reproduce:
1. New Email / Page --> Pick a template --> Text box --> write content --> change font (there is no change font button)
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Font family selection was added in Mautic 2.5.0
