### ISSUE TITLE
OneSignal Web Push Notification Integration Require subdomain name

### ISSUE THREAD

**Issue by heanfig** [mautic/mautic#3198]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  y
| Feature request? | n  
| Enhancement? |  n

## Description:

When I made a landing page in the landing page option of mautic and set the app id and the rest api key In the landing page you need the subdomain url (assuming my site does not have HTTPS) You need to add an option in the configuration where the subdomain name

check OneSignal Documentation

https://documentation.onesignal.com/docs/web-push-http-vs-https

## Bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version |  5.6.24

### Steps to reproduce:

1. Configure application in onesignal (assuming it does not have HTTPS)
2.. Configure web notifications(onesignal) credentials in the mautic configuration panel
3. Create landing page in mautic
4. Error : http://i.imgur.com/wgDt8cK.png

![image](https://cloud.githubusercontent.com/assets/4906962/21708724/4b3e8626-d3a9-11e6-9368-20b67f12e2e2.png)

### Notes

![image](https://cloud.githubusercontent.com/assets/4906962/21708739/6e21e6b0-d3a9-11e6-89e7-c618472e17a1.png)

Currently I have a commit with the field added in the configuration panel and I have other changes that I have not committed, but I still have not wanted to make the request, but if they approve this problem as an error tomorrow would make the pull request

Https://github.com/heanfig/mautic/commit/80ea86e77a4cc1dc1873d0bed9b74721b51d7ba4

thank you very much 

=)

**Comment by dbhurley** [comment]
Is this still an issue? Does it exist in Mautic or is it an issue that OneSignal needs to address?
