### ISSUE TITLE
CK Page builder styling

### ISSUE THREAD

**Issue by brianteeman** [mautic/mautic#32]
There is no styling (that I could see) on data-placeholder="Click to add content"

It would be better if this was indented and in the same font as the rest of the site and have a little padding
### Before
![mautic](https://cloud.githubusercontent.com/assets/1296369/5958585/f9a55b50-a7bd-11e4-9f7f-9fdad7210be0.png)

### After
![ihr3](https://cloud.githubusercontent.com/assets/1296369/5958640/8e3322c0-a7be-11e4-8c36-9b3309d485e8.png)

**Comment by alanhartless** [comment]
Commit on the way to address this.  I've added a bit of padding to the "Click to add content."  The font should match that of whatever the template sets for that section.  (Better seen in the Mauve template http://cl.ly/image/0q2i3A2R2l1r). 

Thanks!
Alan
