### ISSUE TITLE
Error on Settings after update to 2.5.1

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#3200]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:

After update to 2.5.1 the Settings screen do not save preferences. The tab "User Autentication" goes red and it's tab content appear after "General" settings. See image.

![download](https://cloud.githubusercontent.com/assets/257004/21713028/f50af6aa-d3de-11e6-9753-9b2dcc09d0d2.jpg)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version |  7.0

### Steps to reproduce:

1. Update Mautic to 2.5 or 2.5.1 
2. Go to Settings Screen
3. Click on Save button
4. The tab "User Autentication" goes red and don't save
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by luizeof** [comment]
@escopecz @dongilbert @alanhartless

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/3182

**Comment by BernardiSena** [comment]
I had the same problem!
I followed the instructions and it worked!

Thank you!

**Comment by nachomazzara** [comment]
Hi! any news?

**Comment by Arjoni** [comment]
@nachomazzara https://github.com/mautic/mautic/pull/3182 It's fixed.
