### ISSUE TITLE
Multiselect New Custom Field 500 error if no fields aded

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#3208]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
When creating a new `Select - Multiple` custom field, if no fields are added, the site gives a 500 error. Instead it should catch the error and return a simple "You forgot the required field".

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Mautic 2.4.0
| PHP version | 7.0.9

### Steps to reproduce:
1. Create a custom `Select - Multiple` field.
2. Do not add a label / value pair.
3. Hit Save.

**Comment by jordan8037310** [comment]
@mqueme Any thoughts on this? How does mautic catch errors for unfilled fields elsewhere?

**Comment by dongilbert** [comment]
When testing this on latest staging, I cannot duplicate. If you don't add any fields, it does give the error message you'd expect. If you add a single value, but don't fill out the part of the form, it doesn't allow you to save it, but no 500 error is thrown. What version are you on?

![screen shot 2017-03-09 at 9 59 23 pm](https://cloud.githubusercontent.com/assets/718028/23780261/cc8dbe5e-0513-11e7-8a84-b8dcf2119722.png)

**Comment by dongilbert** [comment]
@jordan8037310 I just saw in the report that you're on 2.4.0. It seems it has been fixed since then.
