### ISSUE TITLE
Date doesn't respect locale

### ISSUE THREAD

**Issue by ondraknezour** [mautic/mautic#321]
I am getting "April" as name for the fourth month in dates displayed with both system and user locale set to the Czech, where correct name is "duben".

This citation from the PHP manual may reveal reason

> To format dates in other languages, you should use the setlocale() and strftime() functions instead of date().

http://php.net/manual/en/function.date.php

**Comment by dbhurley** [comment]
Sounds like you're a programmer ;) Want to submit a PR?

**Comment by ondraknezour** [comment]
It was long time ago :)

I didn't look into source, so it is just educated guest what may be going wrong. Moreover, I am not familiar with Github yet, created account only to follow Mautic, so if someone with knowledge both of the Mautic code and Github will step in, I would appreciate it.

And there may be another catch - compare formating strings for the date() and strftime() functions. Do you see those G vs. %G etc? And those formating strings are set up via the Mautic administration interface, so this wouldn't be only swap two functions and move on patch.

**Comment by alanhartless** [comment]
I believe that almost all date formatting is done via \DateTime::format which I didn't realize ignored locale. It may be quite an undertaking to refactor every date format usage throughout. Doctrine returns all its dates to us as \DateTime objects as well.  It will have to be looked into on how to best remedy this.
