### ISSUE TITLE
A XSS vulnerability in Forms

### ISSUE THREAD

**Issue by okajax** [mautic/mautic#3210]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
There is a XSS vulnerability in Forms.
Forms fields does not escape HTML tags.
Even <script> tag works in admin page.
Also we found this problem in v2.2.1 .

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1, 2.2.1
| PHP version | 5.6

### Steps to reproduce:
1. Make a Form.
2. Input HTML tags into fields.
![input](https://cloud.githubusercontent.com/assets/12215856/21791366/a365d49c-d725-11e6-809d-7d24824032b6.jpg)

3. Open the result page of Form.
![admin-page](https://cloud.githubusercontent.com/assets/12215856/21791381/adfaec9e-d725-11e6-827a-0b6f01778a38.jpg)

**Comment by luizeof** [comment]
AC
