### ISSUE TITLE
Lead with no emails stops list send

### ISSUE THREAD

**Issue by tkostenko** [mautic/mautic#322]
No idea if I am explaining  this right .Have a list where after hitting send there are are leads left pending .After investigation with Alan found some of the leads associated to that list  had nothing in their email field . 
Farther investigation show the lead visited a landing page with a form in it .

Actions for form
Create Lead
Send Email
Add to list

**Comment by tkostenko** [comment]
ok to try and narrow down problem - I turned off for list all that had empty email . It made the list size go down from 140 to 126 - I cloned a new email added the list again and its still seeing 140 and not sending

**Comment by alanhartless** [comment]
I think this is probably the same issue as #329 or very similar and also an issue with lead list building that is resolved in #337 (PR pending testing). Going to close this in favor of #329.
