### ISSUE TITLE
Search Needs to Escape Special Characters

### ISSUE THREAD

**Issue by j-ki** [mautic/mautic#3220]
What type of report is this: Bug Report / Feature Request (not sure which, maybe both)

## Description:
In order to use Twilio, the mobile number needs to be in E.164 formatting:

https://support.twilio.com/hc/en-us/articles/223183008-Formatting-International-Phone-Numbers

So the number needs to be formatted like: '+19995551212'

But when I search for this ('mobile:+19995551212'), I don't receive any results. I need to escape the '+' sign for the search to function properly ('mobile:\\+9995551212').

The average person wouldn't know to escape special character.

Perhaps going forward, the search can automatically escape special characters like parenthesis, single quotes (for names like O'Malley), etc.

## If a bug:

| Mautic version |
2.51
 
| PHP version | 
7.0.8

### Steps to reproduce:
1. Please see description
 
### Log errors:
N/A

---

EDIT: Needed to double escape the backslash for it to appear properly.

**Comment by dbhurley** [comment]
This can't be removed or escaped as suggested because '+' and other operators are special search functions. Instead, the Twilio integration now formats the number correctly prior to sending.
