### ISSUE TITLE
Adding filter by any date to email stats report leads to error 500

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#3221]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | n
| Enhancement? | n

## Description:
Adding date filter to report causes fatal error.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.29

### Steps to reproduce:
1. Create report based on `email_stats`.
2. Add any date field as filter (e.g., `date_sent`).
3. Click Save & Close.
=> Mautic mascot appears notifying about error 500.
 
### Log errors: 
> [2017-01-11 12:40:35] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "[date_sent]": Expected a \DateTime or \DateTimeInterface." at /vendor/symfony/form/Form.php line 1149 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unable to transform value for property path \"[date_sent]\": Expected a \\DateTime or \\DateTimeInterface. at /vendor/symfony/form/Form.php:1149, Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Expected a \\DateTime or \\DateTimeInterface. at /vendor/symfony/form/Extension/Core/DataTransformer/DateTimeToArrayTransformer.php:75)"} []

**Comment by alanhartless** [comment]
I can't replicate this in latest version of Mautic using the steps outlined. If this is still an issue in 2.7, let us know and we'll reopen.
