### ISSUE TITLE
Timeline History pagination has wrong order

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#3223]
| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | n
| Enhancement? | n

## Description:
Timeline History tab at Contact's page looks ordered by timestamp separately by page. The whole pager looks like consisting of separate list of items, each of which is ordered separately.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.29

### Steps to reproduce:
1. Open any contact page and refer to timeline History tab.
2. At first glance it looks good: all of the events are sorted by Event Timestamp date - despite the moment when you try to switch the page using the pager.
=> Each page of the pager gives ordered by Event Timestamp list of events - but the list is not ordered through the pages. I mean, the last item at the 1st page doesn't match the 1st item at the 2nd page and so on, they look unordered. For example, in my case:

| Number of page in pager  | Starts | Ends
| --- | --- | ---
| 1 | `Today, 11:11 am` (it means 11 of January) | `July 8, 2016 7:13 pm`
| 2 | `December 20, 2016 11:19 am` | `October 24, 2016 7:00 pm`
| 3 | `November 26, 2016 9:46 am` | `October 21, 2016 6:59 am`
| ... | ... | ...
| last | `August 17, 2016 6:18 pm` | `July 11, 2016 9:11 am`

As you could see, they look absolutely unordered page by page - though ordered in page.

### Log errors: 
No related items.

**Comment by fuschini** [comment]
Up. I have this problem too and it seems that mautic prioritizes campaigns events over page hits in the contact timeline ordination. For example, page 1 of a contact timeline shows a "Point gained" event from a campaign on July 1st and page 2 shows page hits on July 25th

**Comment by itcig** [comment]
This error continues on the latest version, it makes the history paging useless.  Any progress on this?

**Comment by npracht** [comment]
Hi @PatchRanger @fuschini @itcig, do you still have the issue. Does https://github.com/mautic/mautic/pull/7433 helps ?

**Comment by PatchRanger** [comment]
@npracht Sorry, can't help this way or another: I am currently out of Mautic context.

**Comment by quintmouthaan** [comment]
I'm seeing this problem as well. I'm running Mautic version 2.15.1
I cannot try #7433 as it seems that it is not integrated yet.

**Comment by moerazem** [comment]
This issue is still appearing in v2.15.2. Even with #7433 committed.

**Comment by RCheesley** [comment]
Is this possibly fixed by this PR: https://github.com/mautic/mautic/pull/7752 ?
