### ISSUE TITLE
Timeline History pager replaces page title with something unreadable by human

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#3224]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | n
| Enhancement? | n

## Description:
Timeline History pager replaces page title with something unreadable by human.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.29

### Steps to reproduce:
1. Open any contact page and refer to timeline History tab.
2. Click at any page link at the pager.
=> Page title becomes ugly. Here is the example of what becomes title:
> &lt;span class="pull-left img-wrapper img-rounded mr-10" style="width:33px"&gt;&lt;img src="{gravatar link}" alt=""&gt;&lt;/span&gt;&lt;div class="pull-left mt-5"&gt;&lt;span class="span-block"&gt;{user name}&lt;/span&gt;&lt;span class="span-block small ml-sm"&gt;&lt;/span&gt;&lt;/div&gt; | Mautic
 
### Log errors:
No related items.

**Comment by dbhurley** [comment]
Not seeing this. Still an issue in 2.11?
