### ISSUE TITLE
Send style email with form results

### ISSUE THREAD

**Issue by qneyrat** [mautic/mautic#3226]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
Add new field email.send.selectemails (in red) in ```Forms > Actions > Send form results``` for style result form mail.

Selected email must contains tokens {formfield=***}.

![Imgur](http://i.imgur.com/MWgnol3.png)

**Comment by npracht** [comment]
I'd rather go for a better WYSIWYG. Or a email builder by selecting themes, but it's a lot of work.

**Comment by qneyrat** [comment]
#
