### ISSUE TITLE
Points Triggers not working except on initial save

### ISSUE THREAD

**Issue by justinroffmarsh** [mautic/mautic#3235]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Points Triggers appear not to be triggered by any of the standard CRONS.

I have the following CRONS running, and working: segments:update; campaigns:rebuild; campaigns:trigger; emails:send; social:monitoring

A points trigger works if I set it to run on save. But subsequently it doesn't fire. 

I have created two triggers with different events (add Contact to Segment and add Tag to Contact). Neither are working.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.28

### Steps to reproduce:
1. Create Points Trigger, set points to 1, set event to Create Tag, save
2. Generate new Contact from form submission, ensure Points Action allocates >1 points
3. Check contact to see if Tag has been added
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by wucherpfennig** [comment]
+1
