### ISSUE TITLE
Let Campaigns Adjust Contact Owner

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3236]
| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

## Description:
I would really like to be able to change a contact's owner based on campaign rules. Is it possible to implement this? I see that I can "update a contact" in the campaign "actions," but the contact owner does not show up as an available field to update.

Thanks

**Comment by escopecz** [comment]
This seems to be a duplicate of https://github.com/mautic/mautic/issues/897
