### ISSUE TITLE
InvalidFieldNameException while trying to save a campaign with removed action, which is just added

### ISSUE THREAD

**Issue by PatchRanger** [mautic/mautic#3240]
| Q  | A
| ---| ---
| Bug report? | +
| Feature request? | -
| Enhancement? | -

## Description:
After removing an action which is just added, you can't save: error occurs. Log item is attached.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.29

### Steps to reproduce:
1. Add an action to existing campaign and do not save.
2. Remove the newly added action - and try to save.
=> Error occurs.
 
### Log errors: 
> [2017-01-13 13:50:41] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'UPDATE campaign_events SET parent_id = ? WHERE parent_id IN (816, newaad53226609313799c3e40da10d36d14dc59e2c5)' with params [null]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'newaad53226609313799c3e40da10d36d14dc59e2c5' in 'where clause'" at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'UPDATE campaign_events SET parent_id = ? WHERE parent_id IN (816, newaad53226609313799c3e40da10d36d14dc59e2c5)' with params [null]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'newaad53226609313799c3e40da10d36d14dc59e2c5' in 'where clause' at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'newaad53226609313799c3e40da10d36d14dc59e2c5' in 'where clause' at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'newaad53226609313799c3e40da10d36d14dc59e2c5' in 'where clause' at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

**Comment by escopecz** [comment]
Fixed in 2.9.2
