### ISSUE TITLE
Tags get flushed after getting hits

### ISSUE THREAD

**Issue by rahulwalunje** [mautic/mautic#3242]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N 
| Enhancement? | N

## Description:

When contact is created with tags, Tags are visible but as soon as contact gets new event ( say, new page hit on that id ) all tags are removed.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6

### Steps to reproduce:

Step 1 : Add tags to contact manually through admin or API.
Step 2: When contact browses site where tracking code is installed. The tags that we added are removed.

We have tested this by adding tracking code ( JS and gif ) manually as well as through Mautic WP plugin.

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by sujaypawar** [comment]
Could replicate. This one looks like major blocker and existing users must be losing tags.

Could we have some attention on this issue please?

**Comment by sujaypawar** [comment]
Hi @escopecz - since this bug is causing data loss, I would be really greatful if it could be set on higher priority.

Please do let me know in case if I'm missing something.

Thanks :)

**Comment by rahulwalunje** [comment]
@escopecz I am not able to reproduce this issue on Mautic 2.6.

Is it fixed in version 2.6?

Please let me know.

**Comment by escopecz** [comment]
I cannot replicate it either. Tags are there after page hit. Even if I test the [page hit fix](https://github.com/mautic/mautic/pull/3423). I'll close this issue as fixed.
