### ISSUE TITLE
Error after migration to 2.5.1

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#3249]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | 

## Description:
I upgrate from 2.2.0 to 2.5.1 using the upgrade.php and all is working the only thing i notice that is not working is when i visit a landing page inside mautic and try to submit a form the page stay freeze and open the console i get 
`https://mautic.domain.com/form/submit?formId=31 Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

And y my Mautic Syslog i get this
`[2017-01-14 22:33:05] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getId() on null" at /var/www/html/app/bundles/LeadBundle/Model/LeadModel.php line 469 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getId() on null at /var/www/html/app/bundles/LeadBundle/Model/LeadModel.php:469)"} []`
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.13

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ninjoan** [comment]
**Update** 

I upgrade another Mautic 2.2 to 2.5.1 and i have the same problem.

`[2017-01-14 18:46:21] mautic.ERROR: Error: Call to a member function getId() on null - in file /home/domain/public_html/mk/app/bundles/LeadBundle/Model/LeadModel.php - at line 469 [] []
`

**Comment by Aneta09** [comment]
I hope some one help us...

**Comment by Aneta09** [comment]
Can you change any setting in configurations?

**Comment by ninjoan** [comment]
yes; and i restore to the previous version.

**Comment by Aneta09** [comment]
But in versions 2.5.1. Can you changed any configurations?

**Comment by ninjoan** [comment]
Yes **PD:** this is not a chat room lets wait to see if the dev can help with this bug.

**Comment by ninjoan** [comment]
Any update?

**Comment by escopecz** [comment]
This should be fixed in 2.9.2.
