### ISSUE TITLE
Installer doesn't handle non-ASCII characters well

### ISSUE THREAD

**Issue by ondraknezour** [mautic/mautic#325]
Installer doesn't works right way with (at least some) non-ASCII characters. Spotted as problem with characters ě and ž in the admin user surname, but there may be others characters and fields, which are not handled correctly.

This is "copy" of the issue mautic/mautic-spi#2 which was filled to wrong repo on first try.

**Comment by alanhartless** [comment]
Is the issue that it is getting saved to the database incorrectly? Is your database UTF?

Thanks!
Alan

**Comment by ondraknezour** [comment]
It is default installation of the MySQL, so I would assume that it is swedish, if nothing has changed in years. I did only following to create database before starting installer
```sql
create database mautic;
grant all on mautic.* ...
```

And yes, characters are probably stored incorrectly, I assume that by their presentation in the user name in the admin section. After user update everything is fine.

**Comment by alanhartless** [comment]
I think I found the issue and resolved it in the PR listed above.  Can you please verify?

Thanks,
Alan
