### ISSUE TITLE
Form - Radio group with 0 as an option's value cannot be submitted

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3251]
| Q  | A
| ---| ---
| Bug report? |  :heavy_check_mark: 
| Feature request? | 
| Enhancement? | 

## Description:

In forms, if one of the options' value in a radio group is 0 and the radio group is marked as a mandatory field, the contact will not be able to submit the form with that option selected.

![image](https://cloud.githubusercontent.com/assets/18265735/21978220/f1cabf18-dbd9-11e6-897c-3aa9355c684f.png)

![image](https://cloud.githubusercontent.com/assets/18265735/21978249/0fbfe0ca-dbda-11e6-9ebc-26719a75fdd0.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0.14

### Steps to reproduce:
1. Create a form with a mandatory radio group containing an option with 0 as its value
2. Try to submit the form with that option selected.

**Comment by dsp76** [comment]
I can reproduce this with 2.8.2 and 2.9.2...

**Comment by dsp76** [comment]
I'm inclined to say this might be related to this bug: [https://github.com/mautic/mautic/issues/4751](https://github.com/mautic/mautic/issues/4751)

**Comment by dbhurley** [comment]
I'm going to say this is related to #2917 and close in favor of the older one.

**Comment by dsp76** [comment]
Sorry, just tested again: Its not saved, when the label is "0".

**Comment by dsp76** [comment]
Also mentioned in this bug: https://github.com/mautic/mautic/issues/4990

**Comment by dsp76** [comment]
Looks like a fix: https://github.com/mautic/mautic/pull/5189
