### ISSUE TITLE
Postgres install not working

### ISSUE THREAD

**Issue by carlessebastian** [mautic/mautic#3253]
Hi, after looking different threats, let's try again.

Postgres does not show on the installation process, under available PDO's because is disabled on public static function getDrivers() (DoctrineStep.php).

    public static function getDrivers()
    {
        $mauticSupported = [
            'pdo_mysql' => 'MySQL PDO (Recommended)',
            'mysqli'    => 'MySQLi',
            //'pdo_pgsql' => 'PostgreSQL',
            //'pdo_sqlite' => 'SQLite',
            //'pdo_sqlsrv' => 'SQL Server',
            //'pdo_oci'    => 'Oracle (PDO)',
            //'pdo_ibm'    => 'IBM DB2 (PDO)',
            //'oci8'       => 'Oracle (native)',
            //'ibm_db2'    => 'IBM DB2 (native)',
        ];

When enabling it, I can select it, but installation process fails.

My question is, Postgres support has been dropped? Same thing for other types of DB. Only mysql will be continued?

Thanks,
best regards,
Carles

**Comment by escopecz** [comment]
Yes, PostgreSQL was dropped. Current requirements: https://www.mautic.org/download/requirements/

**Comment by eximius313** [comment]
What were the reasons for dropping support for PostgreSQL?
Do you plan to support it again?

**Comment by RCheesley** [comment]
@eximius313 many reasons, there is a feature request coming about supporting multiple databases which might see postgres support. The main issue - so far as I am aware having been through posts in the past about this - was that very, very few people were ever testing with Postgres so things would break and nobody was interested in fixing them as they didn't run Postgres, combined with the fact that there was next to no effort to test before new releases were made in the community etc.
For info, feature requests go at https://forum.mautic.org/c/ideas - maybe make a feature request there for postgres support to be reinstated and/or other databases to be supported?

**Comment by eximius313** [comment]
Done: https://forum.mautic.org/t/support-for-postgresql/13643
