### ISSUE TITLE
Updated docker images

### ISSUE THREAD

**Issue by juanluisbaptiste** [mautic/mautic#3255]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  YES
| Feature request? | 
| Enhancement? | 

## Description:
Docker images on dockerhub are really outdated with version 1.2.x as the latest, and current version is 2.5.x. Could it be possible to have updated images ?

**Comment by escopecz** [comment]
Here is the Mautic - Docker repo: https://github.com/mautic/docker-mautic
