### ISSUE TITLE
Display contact with unique ID given in identified contacts

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3256]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | ✔️ 

## Description:
In the contacts overview, there is a distinction between:
* Identified contacts
* Anonymous contacts

We noticed that when you fill in **a phone number only**, the contact stays _Anonymous_.

## What are the conditions to be displayed in identified contacts?
* Must have a unique ID filled?
* Must have email filled?
* Must have company? Name?

## What I think is useful:
Make phone number field something that make the contact as identified.

Thanks a lot,

N.

**Comment by dbhurley** [comment]
This is interesting but without name makes the contact an unknown. Same as getting a phone call from an unknown number. The ability to contact is not the same as knowing. Just as an address would still be an anonymous house without some identifying information about the occupant.
