### ISSUE TITLE
Add segment filter for resources/assets

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3259]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
It'd be great to have a new segment filter based on who downloaded a resource/asset.
Much nice to manage than to add the generated URL (and it seems that it does not work properly).

N.

**Comment by wucherpfennig** [comment]
+1

**Comment by MaxWebmecanik** [comment]
It's a shame that today, all the data required to figure out which contact downloaded what asset is available in the database (in the `asset_downloads` table), but if it hasn't been caught by a campaign, the data cannot be used anymore :confused:
It would be nice if we had an asset download filter to get these leads back.

@kuzmany, I see you had already made some segment filters in #2912, do you think this would be hard to implement?

**Comment by kuzmany** [comment]
@MaxWebmecanik I think it's easy. But I need answer from Mautic team If PR will be integrated. I got a ready bunch of very usefule filters. For  example sessions (every visits between 30 min, similar to GA) or expression for redirect link.

**Comment by MaxWebmecanik** [comment]
@kuzmany Awesome!

**Comment by npracht** [comment]
Hi @kuzmany your PR has been merged but without that. You think you could add that quickly ? Just segmentation depending on asset downloaded.

**Comment by kuzmany** [comment]
@npracht no time/no money at the moment :(   somebody should fund this feature
