### ISSUE TITLE
Stop smart-lists from appearing to be added lead list actions

### ISSUE THREAD

**Issue by zapur1** [mautic/mautic#326]
When adding a form, campaign, trigger action, the smart-lists probably shouldn't be displayed as if a lead is added to the list and they don't meet the criteria of the list then they will be subsequently removed from the list automatically. If a user wanted to add someone to a list shouldn't they instead make the smart-list criteria true?

Basically smart-lists probably shouldn't be in the drop downs for actions or when manually adding a lead to a set (maybe just greyed out instead?).

It could be very easy for people to get stuck with this issue, I've only recently encountered it myself

Thanks,
Zac

**Comment by drmmr763** [comment]
Just to add some background about what this is about (and it's all theory at the moment I believe unless a full test has been done to confirm things):

Scenario is:
- Import csv of leads with an identifying custom field (eg: imported = yes)
- Create smart list which uses field to as a search parameter for the imported value
- Create a form which adds new leads to the list which don't match the filter criteria of the list

This creates an interesting situation where leads will be added to the list until something comes along that rebuilds the list from it's filter criteria (cron) and (theoretically unless there is some code in place to prevent it) resets the list back to just the filtered criteria. 

Before we go about specifics on the implementation I'm checking to make sure there isn't some code in place to already prevent this situation from occurring.

**Comment by drmmr763** [comment]
Hi Zac

So I kind of suspected this might be the case: I was a little off in my guess! 

Mautic is smart enough to track whether a lead added to a list is done automatically via filter or manually via some action like a form save. 

So - what that means is when rebuilding the list it won't remove leads who have been added manually. Basically what that means is you shouldn't have any issue with the potential scenario we discussed on the forum.

Can you test this out and open a bug report if you find that mautic isn't behaving that way? Thanks!

**Comment by zapur1** [comment]
I can confirm that the leads still remain in the smart lists when manually added and then the lists is updated. It is interesting because it kind of begs the question should it be possible to manually assign a lead to a list that should be automatic?

**Comment by pitus** [comment]
In the above scenario, it would make much more sense for the form to set the custom field used in the smart filter such as imported <= yes which would automatically add that lead to the smart list - so the insert into the list would be unnecessary and there would be no confusion as to what the list represents (is it really smart - in which case I'd expect all entries to satisfy the condition, or built manually).

Is there any live scenario where a mixed list like that would make sense that couldn't be done any other way, such as setting the custom field as I've mentioned above?

**Comment by drmmr763** [comment]
```
It is interesting because it kind of begs the question should it be possible to manually assign a lead to a list that should be automatic?
```

In reality Mautic supports either use case pending how you prefer to use it.

If you want to have a list of auto-only leads then its probably best to just be mindful of how you set up your campaigns and forms to use lists. If you want to exercise a bit of convention to help you just add some naming scheme to your lists like:

```
[Auto] - Imported Leads Lists
[Man] - Form Submissions 
```

```Is there any live scenario where a mixed list like that would make sense that couldn't be done any other way, such as setting the custom field as I've mentioned above?```

I suggested as much on the original forum post. That said I'm realizing that there's probably a scenario for everything - we just haven't thought of it yet ;)

**Comment by pitus** [comment]
How about a clean solution to any such scenario, and many more - here's a possible implementation:

1) Allow only either manual or automatic lists but never mixed ones (as they just ask for trouble)
2) Allow to define automatic lists as binary operations between other lists (AND, OR, XOR...)

Here's what one could do with that - manual list would be used to add Leads to it from forms, automatic #1 would be just a filter based on any criteria to get data from some other list or lists, automatic #2 would be a binary (OR) combination between the two and the result will be all filtered messages (auto) as well as any manually added (ORed the manual list).

One could then do all sorts of filters to find Leads that are on several lists but not on another... just make sure that you support grouping of directives (brackets) or else we might end up with unnecessarily many partial lists such as (A or B and C) not (D and E) would need to define precedence of not, and, or but without the brackets we'd need two additional lists (within brackets) and third to do a "not" between them...
