### ISSUE TITLE
Liberia - Maryland Address Bug

### ISSUE THREAD

**Issue by xtremewebsites** [mautic/mautic#3262]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
There is a bug on the address state field when entering a Maryland address. Even though the full address is in Maryland USA, the system chooses Liberia-maryland. See https://goo.gl/aJfDpE

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6

### Steps to reproduce:
1. Create a new contact with any address in Maryland USA.
 
### Log errors: 

No related errors

**Comment by dbhurley** [comment]
Should be fixed in the latest release.

**Comment by gentleShark** [comment]
still a problem in v2.14.1
