### ISSUE TITLE
Expand Trigger options to include contact fields

### ISSUE THREAD

**Issue by xtremewebsites** [mautic/mautic#3263]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes
| Enhancement? | 

## Description:
Expand triggers under "Points" to include contact fields. I want to assign points to the contact if certain fields are chosen or not. Ex: Give 10 points if the "years in business" dropdown field is "10+ years. Currently this is not available and to me this is the very basic way to assign points.

**Comment by dbhurley** [comment]
Interesting feature request.
