### ISSUE TITLE
Cannot add or edit a Contact

### ISSUE THREAD

**Issue by xtremewebsites** [mautic/mautic#3266]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
This is a nasty bug that is not letting me add or edit any contacts. I've spent hours reading related bug reports but none of these has fixed my issue. This is what I've tried so far:

- Activating all of the default and custom fields
- Activating only default fields and disabled custom fields
- Deleting all contacts and companies
- Cleared cache and tried from different browsers

It is good to mention that adding a contact using the web form works fine, however cannot edit once on Mautic. Also I am able to manually create and add company records.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6

### Steps to reproduce:
1. Simply try to create a new contact. The system looks like it added it however once you refresh the page no records were added. 
2. The same issue happens when trying to edit a contact. The system looks like it edited it however once you refresh the page no records were edited. No matter which field I try to edit.

Please help me fix this issue. Thanks for your help
 
### Log errors: 

[2017-01-18 16:43:32] mautic.ERROR: Deprecation: Symfony\Component\DependencyInjection\Definition::setFactoryService(doctrine) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. - in file /home/ugriincc/XTREME/mautic/vendor/symfony/dependency-injection/Definition.php - at line 204 [] []
[2017-01-18 17:44:49] mautic.ERROR: Deprecation: Symfony\Component\DependencyInjection\Definition::setFactoryService(doctrine) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. - in file /home/ugriincc/XTREME/mautic/vendor/symfony/dependency-injection/Definition.php - at line 204 [] []

**Comment by MxyzptlkFishStix** [comment]
Are you sure you're on 2.5.1?  I just want to be sure as I saw your post in the "[Can't edit or add new contacts after upgrade to 1.4](https://www.mautic.org/community/index.php/4070-can-t-edit-or-add-new-contacts-after-upgrade-to-1-4)" thread.

Those log "errors" are really notifications that aren't related to your problem.

**Comment by xtremewebsites** [comment]
Yes sorry, that was the first thing I found at the moment. I put that comment as it seemed the issue was fixed since the error screen stopped showing. I didn't realize it until now that the issue persists even with no error screen. Indeed I am running the latest version 2.5.1.

**Comment by MxyzptlkFishStix** [comment]
I can't replicate it.  Did you upgrade from an earlier version?

**Comment by xtremewebsites** [comment]
No I didn't. I just installed a week ago through Softaculous. I've tried everything as mentioned. What else can I do? Can u log into my environment?

**Comment by MxyzptlkFishStix** [comment]
PM the URL/auth details over @ Mautic forums.

**Comment by xtremewebsites** [comment]
Hi there. I decided to install Mautic on a different server, start fresh and take a full day to transfer everything manually. Thankfully the mentioned bug was gone so I'm good now. It will be great to see an easy way to export data between installations to avoid the pain of doing it manually. Thanks
