### ISSUE TITLE
Stages field not showing up with other contact fields

### ISSUE THREAD

**Issue by xtremewebsites** [mautic/mautic#3267]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | maybe
| Feature request? | 
| Enhancement? | Yes

## Description:
For some strange reason the "stage" field does not show up as an option under campaigns > Conditions > Contact field value > Contact Field. See https://goo.gl/ib74Xx
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6

### Steps to reproduce:
1. Go to campaigns > Campaign Builder > Conditions > Contact field value > Contact Field. See https://goo.gl/ib74Xx
 
Was this designed like this? - If so please make this field show just like the rest. 

Is this supposed to show? - What can the issue be? (no related error logs appear)

**Comment by MxyzptlkFishStix** [comment]
Stages isn't a contact field by default.

**Comment by xtremewebsites** [comment]
So is there a way to create a trigger from a stage?
