### ISSUE TITLE
FR - Integration to Eventbrite

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3273]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
When you're organizing event in a company, it's really hard to manage or then you can you third software as Eventbrite that works well (used for mautic meetup in London).

Then an integration with that soft is great to get the contact that subscribe to the event and make segmentation about it.

**Comment by awurman** [comment]
+1
