### ISSUE TITLE
Overridden values set in parameters_local.php are not reflected in the settings screens.

### ISSUE THREAD

**Issue by mingfang** [mautic/mautic#3277]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | Y 
| Enhancement? | Y

## Description:
I use parameters_local.php to enforce several configurations to prevent users from changing them.
e.g. ```'cache_path' => '/var/www/html/app/local/cache'```
This works.
But the value is not reflected by the settings/configuration screen. It still shows the default.
Ideally the settings screen should show the overridden value and also grey it out to indicate it's read only.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version |  7.0.13

### Steps to reproduce:
1. override a value using parameters_local.php 
2. go to the settings screen you'll see that value is not the same

**Comment by kuzmany** [comment]
Did you clear cache (app/cache/prod/ directory)?

**Comment by mingfang** [comment]
I'm doing this with Docker so everything comes up in a completely empty state.
It turns out parameters_local.php completely doesn't work at all.
For some reason with parameters_local.php in place, Mautic seems to completely ignore local.php.
I put some debug in the code and it clearly is merging the two arrays.
I don't know what the problem is, but anyway I'm giving up on using this and closing the issue.

**Comment by mingfang** [comment]
@kuzmany I cleared the cache and the problem persists.
To be clear, the values in parameters_local.php are working, but just not reflected in the settings screens.
