### ISSUE TITLE
3rd party website tracking code settings page has a type-o "<body/>"

### ISSUE THREAD

**Issue by isleshocky77** [mautic/mautic#3280]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The description paragraph on the 3rd party website tracking code settings page has a type-o. It currently reads as 

> Insert following code at the end of the web page before ending ```<body/>``` tag. Mautic Landing Pages are tracked automatically. Use this only to track 3rd party websites

It should read as 

> Insert following code at the end of the web page before ending ```</body>``` tag. Mautic Landing Pages are tracked automatically. Use this only to track 3rd party websites

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 1.5.2-dev
| PHP version | 5.6

### Steps to reproduce:
1. Log in as administrator
2. Navigate to Settings (cog) > Configuration > Landing Page Settings

![ending_body_tag](https://cloud.githubusercontent.com/assets/361586/22208328/7ed943c2-e150-11e6-86c3-b7abe72c5180.png)

**Comment by escopecz** [comment]
Thanks for the great issue description and the PR. As it is only about one character, I prepared a PR for it as soon as I saw the issue. Please next time, push the PR without creating an issue. Or make a comment on it that you are working on the fix. A lot of time was spent on fixing this typo :)
