### ISSUE TITLE
Little tiny misspelling inside the Dynamic Content documentation

### ISSUE THREAD

**Issue by italoborges** [mautic/mautic#3286]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
It's just a little tiny misspelling inside the Dynamic Content section.
The submenus inside the section "Dynamic content" are missing a "t" in the word content and the description of the section too.

### Steps to reproduce:
1. Access the documentation 
2. Go to the Dynamic Section
3. Check the words content inside the section and inside the submenus

**Comment by escopecz** [comment]
I don't see any "conten" at https://mautic.org/docs/en/dwc/index.html. Could you please provide a screenshot?

**Comment by italoborges** [comment]
Hey, of course. Actually is "Conent". Look the submenus inside Dynamic
Content and also the right infos.

[image: Inline image 1]


Abraços,

*Ítalo Borges*
Creative Technologist
UX Designer
Web Developer

Barcelona, Spain
+34 667 190 350
italoborges.com

**Comment by escopecz** [comment]
Could you share a screenshot? I cannot find it even if I search for `Conent` in the docs. I can see you tried to share an image in the email reply, but could you open the issue on GitHub and drag&drop the image to the comment text area.
