### ISSUE TITLE
Citrix sync. optimization

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3289]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
We noticed that the command launched by the CRON requests via API **all the past event for each sync. command**.
This is a really heavy work for data that never changes.

When the event is in the past, the information has to be fetch only once because they'll never update anymore (subscribers, participants, etc.).

## Suggestion:
* The command do not request passed event already requested
or
* The command add a date limit to the event checked in the passed (similar to Salesforce fetch command).

@virlatinus your opinion ?

**Comment by virlatinus** [comment]
Hi @npracht . Indeed, this is an optimization that can be done to the plugin. I'll look into it. Thanks.
