### ISSUE TITLE
Mailchimp integration bug - An email address must contain a single @ 

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#3290]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When using the Mailchimp integration, pushing an address from a standalone form, an error log entry reports: An email address must contain a single @ and the user is not added.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.29

### Steps to reproduce:
1. Set up Mailchimp integration
2. Create standalone form with first/last name and email
3. Add form action of push to mailchimp, choose list and match fields etc
4. Complete form
5. Note that form is submitted
6. Check error logs/mailchimp, no user added
 
### Log errors: 

[2017-01-24 14:28:10] mautic.ERROR: INTEGRATION ERROR: Mailchimp - An email address must contain a single @ [] []

Various searches yield people suggesting it's a problem with posting to the API e.g.

http://stackoverflow.com/questions/23827585/mailchimp-api-2-0-batch-subscription-php

**Comment by lukasfrei** [comment]
I have the exact same problem. Any updates on this?

**Comment by RCheesley** [comment]
Hi folks,

Still getting this error in 2.71.

Post here: https://www.mautic.org/community/index.php/154-mailchimp-integration-error/0 references a PR which has been merged, so guessing that isn't the problem.

Post here: https://www.mautic.org/community/index.php/7177-form-submissions-to-mailchimp/0 citing the same error, and here: https://www.mautic.org/community/index.php/90-mailchimp-integration/0.

Something here: https://github.com/drewm/mailchimp-api/issues/12 suggesting something to do with proper quoting of variables, unsure if this is a potential avenue to explore.

To confirm, the Mautic setup is fine - I see the lists and the fields - no problem with setting up field mapping.

Have a form which has a post lead to integration action.  When the form is completed, there is an error in the logs:

[2017-04-25 19:08:23] mautic.ERROR: INTEGRATION ERROR: Mailchimp - An email address must contain a single @ [] []

The lead is never pushed to Mailchimp.

Happy to help with debugging this!

Ruth

**Comment by RCheesley** [comment]
To confirm I think that #3629 is related to this issue - I have errors in the API calls log as per the OP on that issue.

**Comment by igorA53** [comment]
Yes Ruth, I guess it must be the same.

When I tested the Mailchimp-integration 2 months ago, it worked flawlessly. So I was confident to use it "live", but I never got it working again. I even switched to another Mailchimp-account and started from scratch, but it didn't work.

**Comment by dbhurley** [comment]
Is this still an issue?

**Comment by RCheesley** [comment]
I'm not sure, I can test and see if it is still happening but certainly in April it was still broken.

**Comment by igorA53** [comment]
works perfectly now. When I look at the logs in Mailchimp, it's probably fine since August.
Thanks David.

**Comment by dbhurley** [comment]
👍 My pleasure! Thanks for the quick response!
