### ISSUE TITLE
Add segment filter: downloaded asset

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3294]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
**Add the filter asset download:**
* any asset
* +list of assets

**Comment by wucherpfennig** [comment]
+1

**Comment by wucherpfennig** [comment]
duplicate #3259

**Comment by escopecz** [comment]
@npracht I get that some duplicated issues may happen, but it's rare from the same person :)
