### ISSUE TITLE
Mautic Mailchimp Plugin Unable to Authorize

### ISSUE THREAD

**Issue by Aolso004** [mautic/mautic#3298]
What type of report is this: Bug Report

When attempting to authorize the Mail Chimp plugin you are redirected to a 404 page.  

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Latest Mautic Hosted version as of jan 2017
| PHP version | 

### Steps to reproduce:
1. Click "Authorize App" button in the plugin's section of your mautic installation
2. enter your Mail Chimp login info
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
@Aolso004 if this is related to the hosted version, you need to reach out to the support team via the 'Help' button on your instance.  The issues here are for the self-hosted version, as far as I am aware.
