### ISSUE TITLE
CK Page builder data-attrib disappears

### ISSUE THREAD

**Issue by brianteeman** [mautic/mautic#33]
The data-attrib "click to add content" correctly disappears when you click in the block
But it should re-appear if you dont add any content and click elsewhere
![4hyc](https://cloud.githubusercontent.com/assets/1296369/5958661/d1f1d9de-a7be-11e4-8bcb-54ca67ade91f.png)

**Comment by alanhartless** [comment]
Sorry; put the wrong ticket  number in the commit log.

**Comment by alanhartless** [comment]
We are using a bit of CSS3 to handle the placeholder:

div[contentEditable=true]:empty:not(:focus):before {
    content: attr(data-placeholder);
}

It looks like when ckeditor activates, it adds a <p /> element which makes the container no longer empty and thus the placeholder doesn't show.  Will see if we can resolve that.

Thanks,
Alan
