### ISSUE TITLE
On new install, unable to save email settings until first contact created.

### ISSUE THREAD

**Issue by cStuartHardwick** [mautic/mautic#3304]
What type of report is this: Bug report

## Description:
When I first installed Mautic 2.5.1, any changes I made to email setting would be lost as soon as I left the screen. I was unable save any changes until (by chance) I went and created a test contact. Once I did that, the problem saving email settings vanished.

## If a bug:
Mautic version 1.5.1 
PHP version 7

### Steps to reproduce:
1. Log into a fresh install of Mautic 2.5.1 
2. Click the configuration gear and navigate to email settings
3. Set SMTP settings under mail send settings
4. Click "Save & Close"
5. Change to any other screen, then come back to the email settings screen. The changes you made are gone.
6. Go to the contacts view and add any view.
7. Repeat steps 1-5 and email settings will now be saved.

**Comment by corradofiore** [comment]
Not exactly the same, but possibly related to #3258 ?
