### ISSUE TITLE
ThriveLeads unable to retreive segment list until Mautic cache cleared.

### ISSUE THREAD

**Issue by cStuartHardwick** [mautic/mautic#3305]
What type of report is this: Bug report

## Description:
When I first installed Mautic 2.5.1, (clean install--first experience with Mautic) ThriveLeads could not retrieve list of segments after clicking "Connect with service." API connect was correctly set up and could be tested. Chrome inspector confirmed that AJAX call from Thrive to pull segments was made and returned an Http 200, but no segment data. Once I deleted the contents of [mautic install dir]/app/cache, the problem vanished and Thrive worked as expected.

## If a bug:
Mautic version 1.5.1 
PHP version 7

### Steps to reproduce:
1. New installation of Mautic 2.5.1 with 2,100 imported contacts, 5 segments, and a handful of email/form test records.
2. New installation of ThriveLeads plugin into Wordpress v4.7.1 site installed in root domain, where Mautic is installed in subdomain. ThriveLeads plugin v1.95.7 or previous (upgrade came out while debugging this issue)
3. Set up and test API connection between Thrive and Mautic. Connection should pass test.
4. Now, create a Thrive lead form, and when you click "Connect to Service" select the Mautic API. No segments are pulled in.
5. Use Chrome inspect function to observe AJAX call made when "Refresh" button is clicked. Note on "Network" tab that call is made and returns an HTTP 200, but no data is returned (Response appears to be an html snippet with no option values set).
6. Now, using cPanel File Manage, delete contents of [mautic install dir]/app/cache. 
7. Retry "Connect to service" refresh within Thrive and segment list is now retrieved.

This appears to be some edge condition that didn't get tested. Why would anything in the cache of a brand new install prevent the API from returning data?

Thanks.

**Comment by Bannerman** [comment]
Thanks. Same issue. 
Deleting /app/cache solved it.

**Comment by tathspts** [comment]
I think this issue has come back in version 2.13.1 of Mautic.

**Comment by wacordoba** [comment]
Thanks, problem solved!!

**Comment by seigomark** [comment]
Same issue exist in  2.15.1  - brand new install and Thrive Lightbox reloads the lost but 2 empty entries. Clear the cache to a new folder under /app and reloads without issue. Can someone add this to the list of bugs,. thanks!

**Comment by Pd08111997** [comment]
Thrive leads is not able to connect with mautic 2.15.1. I tried with all the possible combinations and It connected. But when I try to fill up the form the lead is not captured in mautic. In thrive leads error log it shows 401 error.

**Comment by seigomark** [comment]
> Thrive leads is not able to connect with mautic 2.15.1. I tried with all the possible combinations and It connected. But when I try to fill up the form the lead is not captured in mautic. In thrive leads error log it shows 401 error.
> 
> Can Anyone solve this is?
> 
> I am getting this message:
> 
> {"errors":[{"message":"API authorization denied.","code":401,"type":"access_denied"}],"error":"access_denied","error_description":"API authorization denied. (`error` and `error_description` are deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)"}

Hey there

I gave up using Mautic due to many bugs and issues with the Softaculous version but the error you see may be because you are using the old API, try the new one that needs to be renewed every few weeks, (v3 from memory).

Good luck!

**Comment by cStuartHardwick** [comment]
The response I got from Thrive is that they can't maintain the Mautic API because Mautic makes so frequent changes. I find that a bit dubious--especially given that Mautic is open source and they (Thrive) can easily participate and address the problem, but whatever.

My solution was to link Thrive to MailChimp, which I use as a front door to my Mautic installation. When users fill out a form, they get an instant confirmation and are added to a Mailchimp list. Periodically, I download the new leads from MailChimp and import into Mautic. If need be, you can specify a segment during import, triggering a campaign.

The Mailchimp account is free because I delete leads from it after import, so never hit the limits. Of course, I am limited to a few lists in MailChimp, but that's fine for my needs.

**Comment by seigomark** [comment]
> The response I got from Thrive is that they can't maintain the Mautic API because Mautic makes so frequent changes. I find that a bit dubious--especially given that Mautic is open source and they (Thrive) can easily participate and address the problem, but whatever.
> 
> My solution was to link Thrive to MailChimp, which I use as a front door to my Mautic installation. When users fill out a form, they get an instant confirmation and are added to a Mailchimp list. Periodically, I download the new leads from MailChimp and import into Mautic. If need be, you can specify a segment during import, triggering a campaign.
> 
> The Mailchimp account is free because I delete leads from it after import, so never hit the limits. Of course, I am limited to a few lists in MailChimp, but that's fine for my needs.

As i said, the issues were with Mautic not adding contacts consistently every time, whether this is resolved by sync from MC is another matter but i wasn't prepared to waste anymore time trying to get 'free' working when freed to paid is far easier and any issues are supported. 

Glad it works for you
