### ISSUE TITLE
Themes should support different preview images for emails and landing page

### ISSUE THREAD

**Issue by stevegrant1983** [mautic/mautic#3307]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
At the moment, themes only support the use of one preview thumbnail image - however, within a theme, the landing page and email layout may be significantly different (different hero images, one/two-column layouts, etc). The theme functionality should allow for the inclusion of two thumbnail images - perhaps titled thumbnail-email.png and thumbnail-page.png - which then get picked up by the "select a theme" grid on the relevant start page.

**Comment by RCheesley** [comment]
Adding my voice to this one as well, it's annoying to not be able to demonstrate the email visually but having to use the same thumbnail as the landing page!
