### ISSUE TITLE
403 Forbidden when submitting form

### ISSUE THREAD

**Issue by lankford** [mautic/mautic#3314]
Bug Report

I have a fresh install of Bitnami on EC2 (Image : bitnami-mautic-2.5.1-1-linux-ubuntu-14.04.3-x86_64-hvm-ebs )

Mautic : 2.5.1x
PHP : 5.6.29 (full output below)

The only things I have done, are change the user / pass and create a form that I have embedded in an external page.

This is a fresh install and I did another install and screwed it all up trying to track this down.

Each time I submit a form that is inside an external landing page I get a 403 Forbidden.

I am also seeing the submit button stay in the "Please Wait" state.

The javascript is failing to load the page and it is getting to the Mautic server saying " Tsk tsk. Apparently you don't have access to this area. "

### Steps to reproduce:
1. fresh install of EC2 image bitnami-mautic-2.5.1-1-linux-ubuntu-14.04.3-x86_64-hvm-ebs
2. create form with just an email field
3. embed form on external page
4. fill out form and hit submit
 
### Log errors: 

No error in the error logs exist... 

I am fairly handy in PHP / Linux / Mysql... if you can point me in a direction, I can usually grok it out.

Thanks
Matt

Full PHP info is in attached text file

[phpinfo.txt](https://github.com/mautic/mautic/files/737676/phpinfo.txt)

**Comment by lankford** [comment]
So I am getting this javascript error BTW :

Refused to display 'http://ec2-52-23-238-240.compute-1.amazonaws.com/form/submit?formId=1' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

I can get rid of that error by changing http.conf entry to disable X-Frame-Options like so :
<IfModule headers_module>
    <IfVersion >= 2.4.7 >
        # Header always setifempty X-Frame-Options SAMEORIGIN
    </IfVersion>
    <IfVersion < 2.4.7 >
        # Header always merge X-Frame-Options SAMEORIGIN
    </IfVersion>
    RequestHeader unset Proxy
</IfModule>

BUT the 403 and the "Please Wait" are still there

**Comment by lankford** [comment]
So... that formatting from the http.conf totally screwed up in that last comment... sorry about that... I am a VI kinda guy... ;)

But I thing you get the idea on what was commented out...

**Comment by lankford** [comment]
Sorry for the continued comments... just giving what I discover... so if I "Preview" the form, it will show the "Display Message"

**Comment by escopecz** [comment]
Try to configure CORS in the Mautic's config

**Comment by lankford** [comment]
Oddly enough... that is what I was working on when your email came in... and what I have discovered... is that I turn it off and hit Apply... and it reverts back to "on"... I tried "save and close" and the same thing happens...

Any thoughts on why that might be?

Thank you for the reply BTW

**Comment by lankford** [comment]
Well, now it has accepted the "Off" position... took about 5 tries... don't understand that..

**Comment by luizeof** [comment]
Mautic 2.5.1 has a bug with SAML fields on Configuration Screen and the #3182 fix this bug.

Did you configure CORS correctly?

**Comment by lankford** [comment]
I disabled CORS in the configuration screen so that "Restrict Domains" is
set to "No"... took a few tries before it stuck... not sure what would make
that happen...

I have applied the patch, sadly, no dice...

Thank you again for sticking with me this far... I am still probing.

_____________
Matt Lankford
770-778-7621
matt.lankford@gmail.com

**Comment by escopecz** [comment]
This is quite old issue, but if anyone has this problem, it is a CORS issue. Go to Mautic configuration, enable CORS and add the domain of your 3rd party landing page to the textarea next to it.

**Comment by ekkeguembel** [comment]
P.S. for the afterworld: I just had a 403 case that was caused by Mautic's "Site URL" (first item in **General Settings**) being set to http:// instead of https://

Also, the **form action** (on the CMS side; maybe caused by a Mautic snippet but I didn't check) pointed to http://, which needed to be changed too, or Mautic wouldn't accept the submission.
