### ISSUE TITLE
ElasticEmail how to use handleCallbackResponse?

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#3318]
I noticed ElasticEmail got added to the supported email providers. After investigating the code, I noticed there's a `handleCallbackResponse` function. Is this function already integrated with emails automatically, or are there still additional steps required to properly handle bounces & complaints using ElasticEemail with Mautic?

**Comment by MarkLL** [comment]
It certainly looks like its ready to go. The Notification URL, in ElasticMail should be set to [mautic-install]/mailer/elasticemail/callback as per [the doco](https://mautic.org/docs/en/emails/bounce_management.html).

**Comment by jaxxbo** [comment]
Hey everyone,  When I put the mautic url in elasticemail, it gives me an error:

Provided HTTP Web Notifications URL http://*****.com/mailer/elasticemail/callback doesn't return valid HTTP Status Code (200).

Do you know if anyone has tried this and working for them?

**Comment by RafaelLVX** [comment]
Same here.
