### ISSUE TITLE
Custom fields initial saving not working properly

### ISSUE THREAD

**Issue by TomRoethlisberger** [mautic/mautic#3319]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Initial saving of custom field is no working
<img width="1038" alt="screen shot 2017-01-31 at 09 11 52" src="https://cloud.githubusercontent.com/assets/9798301/22456984/c8b7105a-e795-11e6-8362-a7e1f4a49a7e.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | 7.0.8-0ubuntu0.16.04.3

### Steps to reproduce:
1. Create a new custom field
2. Give a random name
3. Set "Published" to "No"
4. Press apply
Result: The Published setting is set to "Yes" again. The defined value of "No" should be saved
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Is this still occurring in 2.11?
