### ISSUE TITLE
Problems using Apply in ACL Settings.

### ISSUE THREAD

**Issue by digitalgarage** [mautic/mautic#332]
Hi Folks,

Using Chrome 41 when making changes to ACL using the APPLY button it is not possible to expand permissions panels for subsequent changes.

### Steps to Reproduce ###

1. Create a new role.
2. Go to cog menu, Roles and then Edit Role
3. Select permissions tab
4. Select Lead Permissions
5. Make some changes to the lead permissions.
6. Click Apply.  Changes are applied and role page goes back to Roles - Edit Client Role Details tab.
7. Select Permissions tab
8. Try to select Email Permissions and permissions won't appear on right as per first time.

A full page refresh is needed to get them to appear.

![mautic-permissions-tabs-1](https://cloud.githubusercontent.com/assets/9042878/7221872/7edec76c-e741-11e4-8666-91b47223a1f3.png)

**Comment by alanhartless** [comment]
Thanks for reporting this.  I can confirm it is a bug.  So for now, save and close will have to be the work around until this gets resolved.
