### ISSUE TITLE
M2.5.1 - setting error

### ISSUE THREAD

**Issue by captivea** [mautic/mautic#3320]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Initial instal Mautic 2.1
then updated to 2.2 2.3 and now 2.5.1

When trying to edit configuration > system settings, I can't save the settings the tab "user/authentication settings" displays a red alert flag

Seems we can't save the settings without adding default values to authentication, even if we are not using SSO

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0.12

**Comment by captivea** [comment]
![3320](https://cloud.githubusercontent.com/assets/25105233/22460868/3647ac36-e7a7-11e6-9bb8-872cccc1b12b.PNG)

**Comment by luizeof** [comment]
This bug was reported on #3200 and fixed on #3182
