### ISSUE TITLE
Changes to configuration don't save

### ISSUE THREAD

**Issue by SamMoore1** [mautic/mautic#3322]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Changes to configuration don't save. Initially they appear to have been saved, but when you return to the configuration screen later, it has reverted to defaults.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.9

### Steps to reproduce:
1 - goto settings cog - top right

2 - goto configuration

3 - on system settings tab - scroll down to cors settings

4 - change cors setting to no

5 - apply or save and it appears to work.

6 - move away to e.g contacts page

7 - return to configuration screen and you will see that changes have not been saved.

doesn't have to be cors as no settings are saved - eg language or locattion

I have also been in touch with the support team at my hosting provider and they have replied with:

I checked and I cannot see any problems with mod_securtity that could cause this. Infact, there are no entries logged for any errors when the changes on the 'System Settings' page are saved or applied. I looked into the community article about this page, but the solutions there do not resolve the problem.

I looked into the server settings, but could not find anything that could cause the problem. I tried running the website on different PHP versions and attempting to save the CORS settings but to no avail.

It would appear that the problem is application related. 

I recommend getting in touch with Mautic's support as they most likely have encountered the problem and should have a solution for it.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

Only error message in logs:

[2017-01-31 14:28:09] mautic.ERROR: Deprecation: Symfony\Component\DependencyInjection\Definition::setFactoryService(doctrine) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. - in file /home/XXXXXX/public_html/qm_mautic/vendor/symfony/dependency-injection/Definition.php - at line 204 [] []

**Comment by Mostafa-Rawash** [comment]
How did you fix this issue?
