### ISSUE TITLE
Unable to use company field Mautic tokens in email template

### ISSUE THREAD

**Issue by manishbhatias** [mautic/mautic#3324]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I am unable to use company fields Mautic tokens in emails. If I use a company field token such as companywebsite, Mautic does not replace the token with the correct information. 

I think that the data for companies of the contact is not hydrated properly while preparing the email.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0

### Steps to reproduce:
1. Send an email containing a company field token such as {contactfield=companyemail}
2. Email is sent without the company field data
 
### Log errors: 
No errors related to email are available in the log

**Comment by luizeof** [comment]
+1

**Comment by luizeof** [comment]
@alanhartless  @escopecz

**Comment by mrerich** [comment]
+1

**Comment by eight84** [comment]
+1

**Comment by mrerich** [comment]
Thanks for labeling this item @escopecz but is it really a feature request? Isn't it a bug? :)

**Comment by escopecz** [comment]
It's something that hasn't been developed yet. It's not a bug in the current code. So I think that feature request is a correct label.

**Comment by manishbhatias** [comment]
@escopecz The fields are visible for use in the email editor autocomplete. So from a user's perspective, they should be replaced when sending the email

<img width="361" alt="screen shot 2017-03-15 at 3 18 08 pm" src="https://cloud.githubusercontent.com/assets/359189/23942552/a819023a-0992-11e7-9dc3-87703b2820b7.png">

**Comment by escopecz** [comment]
Alright, it looks like a bug then. I'll re-label.

**Comment by mrerich** [comment]
Thanks.

**Comment by plasticbrain** [comment]
Any updates on this yet? I'm trying to send industry-targeted emails, so being able to insert the company industry would be extremely useful.

**Comment by dbhurley** [comment]
Is this still an issue in 2.11?

**Comment by RCooLeR** [comment]
Yes. Its hUUUUge issue

**Comment by YosuCadilla** [comment]
Hello guys, you might want to try {leadfield=companyname}
This is because contacts used to be called leads some time ago and it shows in the code...

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/5800

**Comment by alanhartless** [comment]
Will be fixed in 2.13.0

**Comment by sachingk** [comment]
Is this issue fixed?
I am using 2.15.2 and still having the same issue. 

I am not able to add company fields to the email. The data don't get populated at all.

I see this when I send the test email.  I am not sure if this issue is with only test email or the same issue exists even with campaign send email ... 

Please help.

**Comment by YosuCadilla** [comment]
@sachingk Try 2.15.3 as Alan just recommended...

**Comment by qthanhfc** [comment]
Hello there,
I'm using Mautic version 4.0.0 and companyname field don't work again.
Please fix it
Thank you.

**Comment by qthanhfc** [comment]
> Hello there, I'm using Mautic version 4.0.0 and companyname field don't work again. Please fix it Thank you.

Oh, I try to use {contactfield=company} and it's work now.
Solution: Use {contactfield=company}, Not {contactfield=companyname}
Thanks
