### ISSUE TITLE
Integration with Sendy (self hosted email newsletter app)

### ISSUE THREAD

**Issue by pagelab** [mautic/mautic#333]
Sendy is a great and affordable solution for sending marketing emails, and would be really awesome if could be integrated with Mautic.

https://sendy.co/

**Comment by drmmr763** [comment]
Hmm looks cool. What would the integration actually do? Push leads back and forth? Or something else? Mautic already does campaigns and email lists.

**Comment by pagelab** [comment]
Yes, I think this would be the main integration point.

Sendy allows me to create customer accounts inside the system (they call it "brands"), which gives them the freedom to manage and send newsletters on their own at a fee specified by me – paid through Paypal.

But maybe would be easier if Mautic implements such a feature, I don't know.

**Comment by SamarSinghJain** [comment]
Hey Team,
Sendy is one of the very demanding self-hosted application and used by thousands of marketers. Sendy is supported by more than 500+ application. Even Zapier provide integration with various application with Sendy.

Sendy integration with Mautic will boost thousands of marketers. Hope to see your response on this.

Regards,

**Comment by TomaszAdamiec** [comment]
+1
