### ISSUE TITLE
Contact Field "Greater Than" Condition not working

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#3338]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
A "Greater Than" (or any other) condition (for a Text Field that holds a numeric value) considers all contacts in the segment valid, regardless of the text field's value. So a condition "larger than 10" considers a text field with value "5" as valid.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.2-dev
| PHP version | 7

### Steps to reproduce:
1. Add a 'Greater Than' condition in for your text field in a campaign. Try setting it to 5.
2. Have 2 contacts, one with the property set to 0, the other one 10.
Both users are considered valid for the condition.

**Comment by dbhurley** [comment]
Is this still an issue in 2.11?
