### ISSUE TITLE
404 Error on API call

### ISSUE THREAD

**Issue by xtremewebsites** [mautic/mautic#3341]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
I am trying to make this plugin https://gravityplus.pro/ integrate with gravity forms, however it is not pulling Gravity data. According to gravity log here: https://goo.gl/npP4NN and the plugin developer this is due to my Mautic installation returning with a 404 error:

2017-02-02 11:55:00.457993 - DEBUG --> GFP_Mautic_Addon::get_mautic_segment_choices 
2017-02-02 11:55:00.458072 - DEBUG --> GFP_Mautic_API::list_contact_segments 
2017-02-02 11:55:00.458425 - DEBUG --> Mautic\Auth\GFP_Mautic_OAuth2::makeRequest 
2017-02-02 11:55:00.458484 - DEBUG --> API URL: http://hub.xtremeplatform.com/api/segments 
2017-02-02 11:55:00.458545 - DEBUG --> Parameters:Array
(
)
 
2017-02-02 11:55:00.458595 - DEBUG --> Method: GET 
2017-02-02 11:55:00.458659 - DEBUG --> Arguments: Array
(
    [timeout] => 30
    [sslverify] => 
    [Content-Type] => application/json
    [body] => Array
        (
        )

    [headers] => Array
        (
            [Authorization] => Basic WmpNM09XVTROVGhoTm1Oak56Z3habU5qWkRabFlUSmtPVFppWkRrMlpEVmhPRFZpWkROaU1tVXpNelptWkRReU16aGtaV1l3TWpGalpqVTBaRFkyT1E6
        )

)
 
2017-02-02 11:55:00.950304 - DEBUG --> Success. Array
(
    [error] => Array
        (
            [message] => Requested URL not found: /api/segments?access_token=ZjM3OWU4NThhNmNjNzgxZmNjZDZlYTJkOTZiZDk2ZDVhODViZDNiMmUzMzZmZDQyMzhkZWYwMjFjZjU0ZDY2OQ
            [code] => 404
        )

)

I have API enabled and created Auth2 credentials. I've tried several times and always the same issue. Ironically by using a similar plugin https://wordpress.org/plugins/wp-mautic-form-integrator/ I was able to integrate without an issue. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | latest
| PHP version | 5.6

### Steps to reproduce:
1. Create an Auth2 API credential 
2. Installed https://gravityplus.pro/ and added credentials on settings
3. Authenticated credentials and callback URL comes back successful
4. When mapping the form fields, nothing shows on the mautic dropdowns https://goo.gl/uloAS9
 
### Log errors: 

[2017-02-03 12:47:41] mautic.ERROR: Deprecation: Symfony\Component\DependencyInjection\Definition::setFactoryService(doctrine) is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. - in file /home/xwmautic/public_html/vendor/symfony/dependency-injection/Definition.php - at line 204 [] []
[2017-02-03 17:49:15] mautic.WARNING: IP LOOKUP: The file "/home/--------/public_html/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []
[2017-02-03 17:49:29] mautic.WARNING: IP LOOKUP: The file "/home/--------/public_html/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []
[2017-02-03 12:51:49] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Client not found." at /home/--------/public_html/vendor/friendsofsymfony/oauth-server-bundle/Controller/AuthorizeController.php line 165 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Client not found. at /home/--------/public_html/vendor/friendsofsymfony/oauth-server-bundle/Controller/AuthorizeController.php:165)"} []

**Comment by escopecz** [comment]
Try to clear Mautic cache, but if one plugin is working and the second is not, it should be logically a problem in the plugin.

**Comment by xtremewebsites** [comment]
Hi there. Yes I did just deleted the Mautic cache problem and still no luck. Unfortunately had to deal with their developer which provides no real support.

**Comment by xtremewebsites** [comment]
After years of working with developers, I've never dealt with a more uncaring and arrogant developer. She's simple refused to provide any support and told me "good luck". Please don't support or recommend this plugin, many others have had similar bad experiences. https://goo.gl/YGpnvs I will simply stick to the other plugin that works.

**Comment by naomicbush** [comment]
Based on the evidence, I don't believe this is a Mautic bug, however @escopecz you're right on the first point

> Try to clear Mautic cache

but wrong on the second

> if one plugin is working and the second is not, it should be logically a problem in the plugin

as there's hardly enough information here to determine that one WordPress plugin has a problem compared to another.

1. If it's a problem with *this* particular WordPress plugin, how are other people using the _same_ WordPress plugin successfully?

2. Why are people experiencing the *same* problem using other WordPress plugins (or not even using a WordPress plugin)? And why were they *all* able to successfully solve the issue in the same way?

* https://www.mautic.org/community/index.php/6801-help-thriveleads-api-is-not-populating-contact-segments-list

* https://www.mautic.org/community/index.php/6583-api-call-returns-404/p1#p18700

* https://www.mautic.org/community/index.php/6687-mautic-api-error-requested-url-not-found/p1#p19115

* Mautic Slack

<img width="912" alt="mautic-slack-api-404" src="https://cloud.githubusercontent.com/assets/918242/22626934/e0fb06be-eb85-11e6-9649-faf94119846f.png">


The evidence here doesn't point to a problem with a specific plugin or a Mautic core bug, but something that the user has to solve with their Mautic install.

**Comment by escopecz** [comment]
@naomicbush in our Slack communication you wrote

> one plugin uses OAuth2 and the other uses OAuth1

I think this is the right way to discover steps to replicate the issue. Could you please tell us which OAuth version is your plugin using?

**Comment by naomicbush** [comment]
@escopecz after looking at it again, I found people using other WordPress plugins (including the one that the reporter has said they were able to get to work) or not even using a WordPress plugin having the same issue, and all solving it the same way.

FWIW, my plugin uses OAuth2. But, other customers are successfully using the plugin with their Mautic install with no issue.

**Comment by escopecz** [comment]
@xtremewebsites I tested the `/api/segments` endpoint which your Mautic cannot find with OAuth2 authentication and it worked without any issue:

![screen shot 2017-02-06 at 16 34 02](https://cloud.githubusercontent.com/assets/1235442/22654004/a78ccbd6-ec8b-11e6-8d27-c1ca49bff9a1.png)

Double-check if the cache was cleared. Here's how to do it properly: https://mautic.org/docs/en/tips/troubleshooting.html

Let us know if it helped.

**Comment by xtremewebsites** [comment]
@escopecz  I know OAuht2 authentications work on my install bc it is working fine with other plugin. I cleared the cache following this tutorial successfully and the issue persisted. Anyhow will not waste more time. I already uninstalled this plugin and requested a refund from developer. Thanks

**Comment by naomicbush** [comment]
@escopecz just tested the plugin with Mautic's official version (Mautic Cloud) and it works great. So, definitely not a general Mautic or plugin issue, but something with this user's Mautic install. 

![gravity forms mautic add-on successfully contacting mautic](https://cloud.githubusercontent.com/assets/918242/22659033/341e8c3c-ec6a-11e6-8f0f-b40221f70df5.png)

![gravity forms mautic contact fields](https://cloud.githubusercontent.com/assets/918242/22659061/44655a1c-ec6a-11e6-9a2a-5ac881bdd2f7.png)

I'd say this can be closed.
