### ISSUE TITLE
Request: Possibility to Add Default Alternative when Contactfield not Available

### ISSUE THREAD

**Issue by Paul979** [mautic/mautic#3345]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | V
| Enhancement? | 

## Description:
When I for example use {contactfield=firstname} nothing is inserted when that field isn't available.

My request is to add functionality for a default alternative when that field is not available...

For example: "Hey {contactfield=firstname | there}" would then result in "Hey there" if the firstname isn't available, with "there" being the default alternative.

Of course this is just a simple example. There are many more, and more useful possible applications of this functionality.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
As you mentioned it with the pipe in the token and without space, it is working. Please refer to the documentation :-)

N.

**Comment by Paul979** [comment]
Ah ok, I did read the docs but I guess I must have scanned over it then. Great, thanks
