### ISSUE TITLE
Removing Filters Doesn't Truly Remove Them

### ISSUE THREAD

**Issue by Paul979** [mautic/mautic#3347]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | V
| Feature request? | 
| Enhancement? | 

## Description:
When deleting filters applied to a report, the filters are visually deleted but in actuality they are still active and applying that deleted filter to the report.

To solve that I had to recreate the filters, remove the filter values, and delete the filters again to unfilter all previously filtered records. (this happened with several different filters, among which a regular "equals" filter).

This seems like recipy for confusion and frustration. It can become impossble to troubleshoot when a deleted filter is still filtering your report, and you don't realize why. I noticed this quickly, before I moved on, and so it was luckily relatively easy to debug.

Something similar also happened when I temporarily set up a Segment Filter...

Here's what happened:

1. I set up a segment filter that targeted only 1 specific contact.
2. The contact was added to that segment by the filter.
2. I'm not sure. I either :
A) removed the filter which then automatically removed the contact from the segment, or...
B) I manually removed that contact from the segment.
It was probably A, and I definitly removed that filter in any case.
4. Then in Contact Widgets>Top Segments that 1 contact was still showing in that temporary segment, even though it had been removed from that segment (checking the segment the segment menu, it showed No Contacts).
5. I then re-added the contact in question to the segment, and then right after removed it from the segment again. And then finally it was completely removed from the segment, and not showing up in the Top Segments widget anymore too.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0

### Steps to reproduce:
1. See description above
 
### Log errors: 

No errors

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
This should be fixed by https://github.com/mautic/mautic/pull/3635
