### ISSUE TITLE
contacts page is not loading | Bug report? | 

### ISSUE THREAD

**Issue by grinono** [mautic/mautic#3353]
What type of report is this:
| Bug report? | 

## Description:
My https://**.com/s/contacts page is not loading anymore. It returns a 500 server error. 
I added some custom profile fields and provisioned them via the REST API trough a browser extension. SQL is still good. But somehow the page breaks. could not find any usefull logs.
 rest of the pages are working just fine.

Mautic version | > 2.5.1
PHP version | > 5.6.28
i'm using an own hosted Bitnami version.

### Steps to reproduce:
It looked like it breaks after making some API calls. 
 
### Log errors: 
Apache2 logs >
172.31.18.253 - - [06/Feb/2017:19:57:19 +0000] "GET /s/contacts?_=1486410372844&mauticUserLastActive=1&mauticLastNotificationId= HTTP/1.1" 500 55116

**Comment by escopecz** [comment]
There must be something in the logs. Read https://mautic.org/docs/en/tips/troubleshooting.html to find the right one.

Do you have some custom field unpublished?

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to come with some updates anytime and I'll reopen this issue.
