### ISSUE TITLE
Inaccurate Split Testing Stats

### ISSUE THREAD

**Issue by Paul979** [mautic/mautic#3356]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | V
| Feature request? | 
| Enhancement? | 

## Description:
See screenshot:

![split](https://cloud.githubusercontent.com/assets/25543761/22683441/3e472f4e-ed18-11e6-81f5-3ef25d43c3fd.png)

As you can see there is one of 2 things going on, either:

A) The split test variation of the email is not being tracked/inserted into these statistics (probably this)
B) The split test variation of the email is not being sent

Either way, sent or not, not being able to see the statistical results of the split test makes the A/B feature completely useless.

I'm not the only one experiencing this problem too, see here: https://www.mautic.org/community/index.php/2689-a-b-split-test-not-working-on-all-emails/

In that forum thread, **this bug was reported exactly 1 year ago**. 

Like I said there, I hope this bug will be acknowledged and fixed soon.

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0

### Steps to reproduce:
1. Set up a split test
2. View the A/B test stats
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by funkolector** [comment]
+1

**Comment by dbhurley** [comment]
Is this still an ongoing issue in 2.11?
