### ISSUE TITLE
Cannot filter segment on "Select Multiple" field "including" an option

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3357]
| Q  | A
| ---| ---
| Bug report? | :heavy_check_mark: 
| Feature request? | 
| Enhancement? | 

## Description:

Filtering segments on "Select Multiple" field "including" an option does not yield contacts having more options given that the specified one

![image](https://cloud.githubusercontent.com/assets/18265735/22685119/63b37c22-ed1f-11e6-9ce7-3d4408af02fd.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0.15

### Steps to reproduce:

1. Create a _Select Multiple_ custom fields called "Known programming languages"
2. Give the options "PHP" and "Javascript" to that field
3. Create a contact "Alice" with "Known programming languages" set to "PHP"
4. Create a contact "Bob" with "Known programming languages" set to "PHP" & "Javascript"
5. Create a segment "PHP Developers" filtering on "Known programming languages" including "PHP"
6. Run `mautic:segments:update`
7. Only "Alice" got in the segment

**Comment by MxyzptlkFishStix** [comment]
% is your friend.

**Comment by MaxWebmecanik** [comment]
@MxyzptlkFishStix Are you implying that a % should be added somewhere in the interface (which I'm pretty sure is not the right answer) or somewhere in the code (which is probably right)

**Comment by MxyzptlkFishStix** [comment]
Disregard.  I though you were tagging them in a campaign. % is the Mautic wildcard function.

Just use excluding Javascript and both contacts will be placed in your segment.

**Comment by Apaflesk** [comment]
Hi @MxyzptlkFishStix,

I have been having the same problem as @MaxWebmecanik. 

But your suggestion does not solve the problem for me.

When you add a couple of more contacts to the equation you get this:

**Contacts - "Known Programming Languages"**
Alice = "PHP"
Bob = "PHP" & "Javascript"
Carl = Empty field
David = Empty field

**Segment - "People with PHP skills"**
Filter (Known Programming Languages) = Excluding "Javascript"

Segment Output = Alice, Bob, Carl & David

But Carl & David does not know any PHP....

How do we solve this?

**Comment by MxyzptlkFishStix** [comment]
Sorry about that.  Use "regexp" = "PHP".

**Comment by Apaflesk** [comment]
@MaxWebmecanik the only two available filter options for the "Select Multiple" field is "including" and "excluding" in 2.6.0 and 2.6.1 and none of them work properly for me.
