### ISSUE TITLE
Performance issues that causing users abandon mautic.

### ISSUE THREAD

**Issue by FarhadF** [mautic/mautic#3358]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
The Problem: Slow processing  for large lists. [link](https://www.mautic.org/community/index.php/5480-mautic-sending-speed)

Problem Definition: 

1. Getting 100% CPU usage on one core, Due to Single threaded PHP and using a single instance of `mautic:campaign:trigger`.
How to solve:
We need to implement multithreading, for this script, or split the lists of leads and send them to forks.
I personally prefer the second option because it doesnt require users to recompile php.

2. Emails/Campaigns need priority
Imagine the first problem is solved, and mautic is configured to use queue mode. having 3 campaigns to send 250k emails each, Users need Priority for a forth campaign that sending transnational emails. like sign up notifications an stuff.

Priorities: Issue number one is high priority at the moment in my opinion.

My configuration:

- Self Hosted
- 4vCPUs, Doesnt matter unfortunately :(
- 8GB RAM
- 230K Subscribers
- Using Queue
- 8Hours Send time 
- Using Postfix MTA with 128 Public Ips, Benchmarked for being able to send about 800,000 Emails/Hour

**Comment by AdrianMackenzieQlsso** [comment]
Same Issue with my Mautic

**Comment by zenzozen** [comment]
same here. horrible performance with 200k list

**Comment by ninjoan** [comment]
Any update?
I dont have the CPU usage problem but i have the speed problem when i try to go from one page to other sample  (Dashboard > Emails)

**Comment by howlinghuffy** [comment]
Same issue here. We are having terrible performance issues with a list of about 250,000.  Even opening the emails tab takes about 10 minutes to fully load, and trying to modify a campaign often times out completely.  Anyone know where these bottlenecks are coming from?

**Comment by SmittyTan** [comment]
it looks like I am going to abandon Mautic Now after spending 2 days on this!

**Comment by SmittyTan** [comment]
and your slack chat is DOWN!

**Comment by SmittyTan** [comment]
https://www.mautic.org/slack/  "service unavaialble"

**Comment by npracht** [comment]
then you have my email address on my Github profile, just drop me an email ;)

**Comment by SmittyTan** [comment]
Sent.

**Comment by Gp2mv3** [comment]
Is there a solution for those super slow requests ?
We are using Mautic for some month now and the interface is super super slow (20-30 sec per link click).

I also discovered that the server load is increasing with time (See CPU usage and load average).
![screenshot_2018-07-23 mautic datadog](https://user-images.githubusercontent.com/1221806/43082926-8cf282fe-8e95-11e8-805b-40b14ee8b9d1.png)
We upgraded our cloud instance on the 10th to a 2 CPUs at 2.3GHz with 7GB of RAM, which explains the sudden change.

We use apache2 with php fpm-7.0. We have op cache and all the setup requirements are met. We have around 100k contacts and 3 campaigns running with around 100 emails sent per day via Sendgrid, not that much I think.

What's wrong with that ? Is it normal that we need super servers to handle that few contacts ?

**Comment by escopecz** [comment]
@Gp2mv3 can you specify what requests are that slow? Dashboard, email list, tracking, ...?

**Comment by zenzozen** [comment]
@Gp2mv3 please let me know how you handle it, if possible. Im working with a very expensive server for 300k contacts too. Same problem with slow interfaces in general. And impossible Reports (i installed mysql workbench and made my own reports directely from database). I´ve already signup a contract with another company, but i want to keep using mautic too for some small things.

**Comment by escopecz** [comment]
Mautic can load some counts over stats on list pages, it can load some stats on detail pages, tracking requests might wait for some triggers like webhooks that can be slow, but even edit pages? Those doesn't load anything from stats tables which can be huge. There must be some bottleneck in your infrastructure. 

Could you trace it with a tool like https://blackfire.io to get more details on what's taking so long?

**Comment by Gp2mv3** [comment]
I've cachegrind profiling files. How can I send them to you ?

**Comment by escopecz** [comment]
Can you publish them here so we can think about solution as a community? There may be others that can spot the problem better than me alone.

**Comment by Gp2mv3** [comment]
Yep, I wasn't sure about the sensitivity of those files but it seems they don't contain any sensitive data.
Here they are (In a zip): [cachegrind-mautic.zip](https://github.com/mautic/mautic/files/2223423/cachegrind-mautic.zip)

**Comment by AlbanL74fr** [comment]
When my company started using Mautic, we discovered that we could not install the tracking code on all the pages of our website because the volume of https requests resulting of every page hit would really slow Mautic frontend and make it almost unusable... Slowness correlated with visit peeks... CPU was always 100%. Therefore, we started tracking only pages related to our marketing campaigns. We have about 1M monthly visits on this website.
Another thing that we did to mitigate with slow frontend was to ensure CRON jobs are not running at the same time.

**Comment by Gp2mv3** [comment]
@AlbanL74fr Our crons are running every 15m and none are at the same time. And we don't use tracking. Mautic is only used to send emails. Contacts are created via the API called from our servers (around 1k times a day).

**Comment by escopecz** [comment]
@Gp2mv3 I'm not able to find the bottleneck from the cachegrind reports. I don't see any database calls there. Only that the most costly operation is rendering of PHP templates. Could you try the Blackfire service and link the report of a long loading page here?

@AlbanL74fr take a look at https://github.com/mikegillis677/documentation/blob/5207b12813b897f73d6062b85e28627196789f2c/en/queue/README.md. The PR is missing new menu item so it's not showing up in the Mautic docs...

**Comment by Gp2mv3** [comment]
Email edit: https://blackfire.io/profiles/f3fe5d6e-9b60-4597-9cf8-4bf5d25cd4bd/graph
Contacts list: https://blackfire.io/profiles/69d06e2a-d75e-4372-beb6-bf04c3968b7f/graph

**Comment by escopecz** [comment]
It profiles only the backend processing. It will take browser some time to render it and run all the javascript.

So from what I see; SQL queries aren't the blocker. It takes 1/3 of the time for Symfony to send the actual content that the controller prepares to be sent. I tried to google around to find if this is a common problem, but did not find anything.

<img width="574" alt="screen shot 2018-07-25 at 09 42 29" src="https://user-images.githubusercontent.com/1235442/43186519-20d957b8-8fef-11e8-94b7-5b522f0cad39.png">

**Comment by Gp2mv3** [comment]
@escopecz Yes, I understand that. When I say "I don't understand why the pages loads faster in Blackfire than in my browser..." I refer to the timing graph I sent before, the "Waiting" line is mainly composed of the backend processing, which should be pretty similar to the timings in blackfire.

What I see is that the Waiting is around 2 - 5 seconds and blackfire is around 1s. That seems weird for me...

**Comment by Gp2mv3** [comment]
Ok, I think I found the issue. We now have a normal response time.

In Blackfire, it says xDebug is still enabled (which is not the case). I found a thread on stackoverflow referring to a "bug" in php that enables the extension even when it's loaded but not enabled.

So I had to remove the line `zend_extension = "/path/to/php_xdebug.so"` from my config files.

Here is the thread: https://stackoverflow.com/questions/8754826/how-to-disable-xdebug

**Comment by ston3o** [comment]
Hello @Gp2mv3, I use mautic:2.15.0-beta and I have always performance issue.
Here blackfire report :

![blackfire report](https://i.imgur.com/0adzgda.png)

Mautic takes **3.72s to start**

![](https://i.imgur.com/QNyvjDF.png)

**Comment by ston3o** [comment]
Sorry, it's a server error, I reduced loading time with opcache ;)

https://github.com/mautic/docker-mautic/pull/74

![](https://i.imgur.com/6IaaFBJ.png)

It's good but it can be better.

Combine and minify javascript files with defer loading ?

**Comment by roco5** [comment]
How did you use opcache to do reduce load time?  What is opcache?

**Comment by ston3o** [comment]
Hello @roco5,

It's a php module to improve performances, you can see how to install this module [on this documentation](https://www.php.net/manual/fr/opcache.installation.php).

Otherwise, you can check [docker-mautic repository](https://github.com/mautic/docker-mautic), opcache is installed by default ;)

**Comment by roco5** [comment]
Is there any other way to speed up the server response time on these focus elements?  opcache is not available on my server, and I am not too excited about using a forked branch.

**Comment by dl-lim** [comment]
@johackim
> Hello @roco5,
> 
> It's a php module to improve performances, you can see how to install this module [on this documentation](https://www.php.net/manual/fr/opcache.installation.php).
> 
> Otherwise, you can check [docker-mautic repository](https://github.com/mautic/docker-mautic), opcache is installed by default ;)

I'm using the docker-mautic image mautic:v3. So, I suppose opcache is installed by default? Hardware is overkill.

Sadly, am also getting significantly slow response times. Takes like 60 seconds to go from dashboard to configuration page, 10 seconds to click Add New whatever, etc.

And that's just the backend, which is fine and my staff and I can pace around the office while waiting, unfortunately..

However, I have tested the same link as a customer opening a link on their emails to the landing page of mautic, which takes up to 60 seconds just to parse that tracking ID. And this was on a blank install of Mautic!

I think there's a really awesome tool amidst the issues here, and it'd be a waste users don't get to make the most of it simply because of performance issues.

Any recommendations on what I can do right now to let it run more efficiently? :)

**Comment by escopecz** [comment]
The times you are describing are not what I'm experiencing with my Mautic instances. The truth is that the more data in the database (talking millions of rows here) the slower the response times. If you are getting this slowness on a fresh installation then there must be something else wrong. Use some PHP profiler like Tideways to find out what the bottlenecks are.
