### ISSUE TITLE
[Feature Request] Store landing page visit dates to make more comprehensive reports

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3365]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | :heavy_check_mark: 
| Enhancement? | 

## Description:
Today, if you make a report on landing page visits, for any given date after the LP's creation, you will always see the same number of visits.
This is because the LP visite date is not stored and thus cannot be compared to the report's date filter.

Could we make that possible?

**Mautic version**: 2.5.1

**Comment by escopecz** [comment]
Could you upload a screenshot? I don't know what you mean. LP visit dates are stored in the page_hits table for each hit.

**Comment by MaxWebmecanik** [comment]
Whoops sorry, I guess I was looking at the wrong table :joy:
I'll close the issue.
