### ISSUE TITLE
Multiple Subject line - Unopened Email Action 

### ISSUE THREAD

**Issue by pcswatertown** [mautic/mautic#3368]
I tend to send the same email with multiple subjects lines to see which subject lines gets the best open rate.
Also when I think I have an excellent email but the open rate is low I will resend that email with different subject lines .
I have to make a campaign with 
----Send Email Action Email1 Subject Line 1 - Then Open Email - Continues On Campaign Path -
If Not opened after 3x Days then I Repeat 
----Send Email Action Email1 Subject Line 2 -

Doing that I have to Create Duplicate Campaign Paths for Each Email ( Unless I am doing this incorrectly)

It would be really nice to have a Campaign Action 
Send  Email Subject Loop

Same as Current Send Email Action with extras
------------------------------------------
Send email
Send the selected email to the contact.
Name 
Execute this event...
immediately at a relative time period at a specific date/time
Email to send 
Choose one...

Email type 
Transactional Marketing
 New Email   Edit Email 

-----------------------------------------
New Actions 
Resend Email with Different Subject Line if Unopened after X Days

New Subject Line
Add New Subject Line
-------------------------------------------------------------
This would eliminate 50% of the actions I create on a campaign 

Not sure that I worded this the best I could .If anyone understands and can explain this better please do

**Comment by dbhurley** [comment]
Interesting idea but probably better for a plug-in than part of core. 🙂
