### ISSUE TITLE
Bug Report: HTTPS Site URL + Cleared Cache

### ISSUE THREAD

**Issue by flexmarkets** [mautic/mautic#3374]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:

So first of all. I tried everything for 8 hours 👍 ! So I'm 100% sure, that it is a bug. It doesn't matter if you clean the cache etc. I did everything and I will explain the bug now:

So, when you set the "Site URL" in the Configuration options to an HTTPS domain and you clear the Cache, which is located outside of the public web root (mine at least), there is the following error: "ERR_TOO_MANY_REDIRECTS", so the page does not load at all.

When you change the "Site URL" in the "/app/config/local.php" to the HTTP domain, it'll work again as before!

Please fix it!

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0.14

### Steps to reproduce:
1. Change the Site domain to a HTTPS domain instead of a HTTP domain.
2. Clear the Cache (mine was outside the public web root, but it has the right permissions, so don't even think about saying something about that.)
3. Reload the page!
 

### Log errors: 

There aren't any log errors.

**Comment by escopecz** [comment]
Please, try to consult it with some server administrator. My Mautic 2.5.1 runs on https without any problem: https://m.johnlinhart.com. It would be useful if you documented what server setup you use, what SSL service, what did you do to configure it. If it helps, I followed this tutorial to configure SSL: https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-14-04

**Comment by flexmarkets** [comment]
Hey, it does run without problems too here.

But you should clear your cache, which is outside of the web root folder and then tell me if it’s still working.

**Comment by thinkbigger** [comment]
I have the same error.
Everything was working fine with HTTPS, until I clean up the cache, which is outside the root folder.
I don't know if it helps, but I'm using NGINX.

**Comment by thinkbigger** [comment]
Just an update:
nginx/1.11.10
PHP 7.0.16
mautic 2.6.1

**Comment by flexmarkets** [comment]
Just an update:

The API is still NOT working with HTTPS.

**Comment by FabianTe** [comment]
I have the exact same problem.
@flexmarkets I changed my Site Url back to http via the config but It still does not work :sob:

**Comment by mvsaturno** [comment]
I'm still working on it. But I think I'm getting close.

My setup is:
Nginx 1.10.3
Digital Ocean Ubuntu 16.04.2 x64
Mautic 2.8.2 installed on a subdomain
I was using cloudflare for DNS, and installed their certificate with 'flexible ssl' option for https.

So the problem seems to be stated here:
"Cloudflare's flexible ssl means the connection between cloudflare and your server is always over http:"
"...It should be obvious why that results in a redirect loop, there are 2 solutions to force https connections using their flexible ssl solution."

On [this article](https://serverfault.com/questions/653976/redirect-loop-using-cloudflares-flexible-ssl), someone instruct to create a site rule, forcing https always on this domain., I tried that and didn't fix my problem.

The only solution, for now was to turn off all the Cloudflare SSL/TLS Https setup and get back to plain HTTP on my server.

But maybe, Cloudflare https solution is not the way to go. Letsencrypt should give less problems.

**Comment by FabianTe** [comment]
I checked in with my server provider. They used HTTP between a reverse proxy and the webserver. They changed it to HTTPS and i can delete the cache without problems.

**Comment by wittwerch** [comment]
https://github.com/mautic/mautic/blob/d3aebf3644ad423614f0e33093e5b4f2bacfce2d/app/bundles/CoreBundle/Loader/RouteLoader.php#L75

Mautic checks the url to see whether it needs to enforce https. If Cloudflare connects to your server using http even when the initial request was made over https, you get a redirect loop.
In such setups you typically use a X-Forwarded-Proto header [1] to signal the backend that the request was made over a secure connection. Of course Mautic needs to check that header too, but that should be a small change. 

[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto

**Comment by dbhurley** [comment]
Closing this in favor of #2778

**Comment by GiorgioRegni** [comment]
I had the same problem but setting:
`'trusted_proxies' => array(
                '0.0.0.0/0'
        ),` 
in app/config/local.php fixed the redirect loop.
You have to clear cache again to fix the issue after adding that trusted proxies line.

**Comment by AlbanL74fr** [comment]
Same problem. Adding load balancer ip to trusted proxies in Mautic config didn't help, unfortunately.

**Comment by ka4a** [comment]
adding this in index.php solve this issue
$_SERVER['HTTPS'] = 'on';

**Comment by TonyBogdanov** [comment]
2 years later and this has still no been fixed. Neither trusted proxies nor even `$_SERVER['HTTPS'] = 'on';` work for me.

How does one run Mautic behind a flexible CloudFlare SSL for example?

I am willing to spend some time, debug and look for a fix if someone can point me in the right direction.

**Comment by jordan8037310** [comment]
A useful article on setting up Mautic with Cloudflare SSL - https://autoize.com/why-cloudflares-flexible-ssl-setting-is-unsafe/
