### ISSUE TITLE
Bug Report: HTTPS + API Authorization not working!

### ISSUE THREAD

**Issue by flexmarkets** [mautic/mautic#3376]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:

Pretty simple: 

The API Authorization process doesn't work with HTTPS. It works perfectly with HTTP. 
Just try it yourself.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7

### Steps to reproduce:
1. Connect to the API for authorization and use HTTPS.
2. Error: "Incorrect access token parameters returned: Array" + the page never redirects to the login page.

**Comment by escopecz** [comment]
Did you update the callback URL in the API credentials? What Auth method do you use?

**Comment by flexmarkets** [comment]
I use oAuth1a and yes I updated it. Have you ever made it work with HTTPS ?

**Comment by escopecz** [comment]
Yes, I'm using API using HTTPS.

**Comment by flexmarkets** [comment]
Okay. That's great to hear. 

The problem was, that once I switched to HTTPS I couldn't make any request with the old access token anymore, so I thought I can just create new API credentials for the HTTPS URL and let it work again.

But when I try to authorize them, there comes up this error all the time: "Incorrect access token parameters returned: Array"

After I switched to HTTP again, it worked smoothly once again.

Do I have to change any different settings?

And by the way, thank for the support.

**Comment by flexmarkets** [comment]
This error appears, when I use HTTPS and try to authorize:

`Mautic\Exception\IncorrectParametersReturnedException: Incorrect access token parameters returned: Array in /var/www/domain-backend/vendor/mautic/api-library/lib/Auth/OAuth.php:519 Stack trace: #0 /var/www/domain-backend/vendor/mautic/api-library/lib/Auth/OAuth.php(422): Mautic\Auth\OAuth->requestToken() #1 /var/www/vhosts/domain.com/flow/add.php(52): Mautic\Auth\OAuth->validateAccessToken() #2 {main}`

**Comment by flexmarkets** [comment]
And this error appears, when I call the API over HTTPS with valid credentials created with the HTTP URL (since I can't create credentials with HTTPS):

This is a "var_dump" of the response.

`[]array(1) {
  ["error"]=>
  array(2) {
    ["message"]=>
    string(17) "signature_invalid"
    ["code"]=>
    int(401)
  }
}`

So the signature becomes invalid, when I request the API over HTTPS. 
When I request the API over HTTP it works.

**Comment by MarkLL** [comment]
Have you set up your environment correctly? cURL will need to be able to find it's cert bundle as it will try and verify the host. Make sure you have your php.ini setup with this correctly. Also, OAuth1a `signature_invalid` is a known issue. Try and use OAuth2 or BasicAuth. Also did you update the URL in Mautic and clear the cache after changing from / to https?
