### ISSUE TITLE
Contacts shows no records after switching to Turkish language

### ISSUE THREAD

**Issue by fatihbuyuktas** [mautic/mautic#3378]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
All records in Contacts page appear as usual when I use English (tried German, French, Spanish too). When I switch default system language to Turkish or user's language preference from Account page to Turkish, Contacts page shows no records. 
Companies works as expected.
When I switch back to English I can see and search all Contacts.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.0 and 2.5.1
| PHP version | PHP 7.0.13-0ubuntu0.16.04.1

### Steps to reproduce:
1. Create a couple of contacts
2. Click Contacts and see them listed
3. Change user or System language to Turkish
4. Click Contacts again
5. Contacts disappear
 
### Log errors: 
This bug produces nothing on app log and nginx log.

**Comment by enesimo** [comment]
İ have the same issue. How can i solve this?

**Comment by tozgan** [comment]
İ have the same issue. How can i solve this?

**Comment by thangsanps** [comment]
I also have the same error with Vietnamese. Anyone have a fix for this error?
