### ISSUE TITLE
Chart not showing

### ISSUE THREAD

**Issue by tachang** [mautic/mautic#3380]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | PHP 7.0.15-1+deb.sury.org~trusty+1 (cli) (built: Jan 20 2017 09:16:11) ( NTS )

### Steps to reproduce:
1.  Go to channels, emails
2. Notice there is no chart

<img width="424" alt="screen shot 2017-02-09 at 5 26 06 pm" src="https://cloud.githubusercontent.com/assets/85011/22810912/86f83a60-eef0-11e6-8990-c6e527e50af9.png">

**Comment by tachang** [comment]
Not sure if anyone else is running into this?

**Comment by escopecz** [comment]
Could it be that the chart will appear when there will be some statistical data available?

**Comment by IADDIC** [comment]
@tachang my charts were not updating after upgrade to 2.6.  I selected the three vertical dots for the chart, selected edit, then save and charts resumed functioning.

**Comment by tachang** [comment]
What vertical dots are you referring to?

**Comment by escopecz** [comment]
I'll close this issue as the question hasn't been answered for a while. I'll re-open when it does.
