### ISSUE TITLE
FileManager not work after update do 2.6.0

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#3381]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

The FileManager doesn't work after upgrade to 2.6.0

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.0
| PHP version | 7.0

### Steps to reproduce:

1. Update mautic to 2.6 by command line
2. Create a new email
3. Drag an image to email body and choose the filemanager option
4. FileManager shows an loop circle animation
 
### Log errors: 

PHP Fatal error: Call to a member function setLogger() on null in /home/***/public_html/app/bundles/CoreBundle/EventListener/ErrorHandlingListener.php on line 42

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by luizeof** [comment]
@alanhartless @escopecz

**Comment by AlanRezende** [comment]
Happens to me too on PHP 5.6.26

**Comment by alanhartless** [comment]
Can you guys try adding 
```
    \Mautic\CoreBundle\ErrorHandler\ErrorHandler::register('prod');
```
After the require_once lines in app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager/connectors/php/user.config.php. Does that fix it?

**Comment by AlanRezende** [comment]
PHP Fatal error:  Class 'Mautic\CoreBundle\ErrorHandler\ErrorHandler' not found in /home/***/public_html/app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager/connectors/php/user.config.php on line 26

**Comment by AlanRezende** [comment]
@alanhartless the line you suggested have fixed the problem

ignore my last message.

**Comment by Getron** [comment]
Same problems here.

**Comment by Correspondente-Express** [comment]
Hello, I was having the same problem and this @alanhartless  solution worked well for me. Thank you!
