### ISSUE TITLE
Firefox login redirects to undefined

### ISSUE THREAD

**Issue by damiike** [mautic/mautic#3384]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When logging in successfully I am redirected to /s/undefined showing a 404 error page. 

If I manually type in /s/dashboard I can get around this and use Mautic.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6 and 2.4
| PHP version | 7.0 and 5.5

### Steps to reproduce:
1. In Firefox go to Mautic login page
2. Enter correct login information
3. Be redirected to /s/undefined to reproduce.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
I'm not able to replicate this error with 51.0.1 (64-bit) on MacOS. Is there anything special I have to do? Do you access the login page directly or do you go there by clicking a link from another page?

**Comment by damiike** [comment]
Hi John,

Nothing special. I do use Win10.

It works fine on chrome.

The following steps in Firefox:

1. I view domain.com/mautic
2. I login
3. I'm redirected to domain.com/s/undefined

That's how the error shows up.

I then go to domain.com/s/dashboard to use mautic.

Thanks for the help!

Mike
