### ISSUE TITLE
Material Design theme

### ISSUE THREAD

**Issue by joshhopkins** [mautic/mautic#3386]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

## Description:

Anyone have a theme close to Material specs?

**Comment by RCheesley** [comment]
@joshhopkins do you mean something like a base template from which you could then build your own, or a ready-to-go template which is already designed/developed for a particular market?

**Comment by joshhopkins** [comment]
Either! Happy to build off a base template, but would of course consider a ready-to-go material template if one exists.

**Comment by RCheesley** [comment]
It's something we are considering building at @viryagroup 😁 Will keep you posted!

**Comment by joshhopkins** [comment]
Awesome! Thanks.

**Comment by joshhopkins** [comment]
Did you end up building this out @RCheesley?

**Comment by lazmo88** [comment]
@dbhurley @RCheesley issue was marked as closed, was there a update regarding this feature?
