### ISSUE TITLE
SugarCRM integration bi-directionnal sync

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3389]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
**Make a bi directionnal sync of companies and leads with SugarCRM 6.x and 7.**

We take that project in charge if @alanhartless you can assign that to me. The dev has started. Delivery planned for end-Feb/beg-March

**Comment by LEAP-nishit** [comment]
Hi npracht
I was hoping if you can comment, whether or not [SuiteCRM ](https://github.com/salesagility/SuiteCRM)(SugarCRM community edition fork that is maintained) can be included as a target, extension in SugarCRM 6.5 are compatible with SuiteCRM.

**Comment by npracht** [comment]
Hello, i cannot tell you now, but i guess modify the plugin afterward for SuiteCRM is not a big work. I mean, the main work will be already done :)

**Comment by npracht** [comment]
Duplicate https://github.com/mautic/mautic/issues/3517
