### ISSUE TITLE
Error in js tracking

### ISSUE THREAD

**Issue by mbernabeu** [mautic/mautic#3393]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | no
| Enhancement? | no

## Description:
I'm getting this error when add the tracking code in my website
![mautic_error](https://cloud.githubusercontent.com/assets/6458310/22827298/5c734bde-ef97-11e6-886f-b86699c40f44.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6
| PHP version | 5.6.28

### Steps to reproduce:
1. Install and configure clean mautic 2.6
2. Add the tracking code in my website
 
### Log errors: 

I am getting this in the apache access log

[10/Feb/2017:12:55:08 +0000] "GET /mtc.js HTTP/1.0" 200 38099 "https://mywebsite.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
[10/Feb/2017:12:55:10 +0000] "OPTIONS /mtc/event HTTP/1.0" 204 451 "https://mywebsite.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
[10/Feb/2017:12:55:11 +0000] "POST /mtc/event HTTP/1.0" 200 496 "https://mywebsite.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

**Comment by luizeof** [comment]
Same here

With this tracking:

![captura de tela 2017-02-10 16 32 49](https://cloud.githubusercontent.com/assets/257004/22838989/a99a8dd4-efae-11e6-87e6-96e2236d5a67.png)

**Comment by luizeof** [comment]
Mautic JS generate this tracking and returns error 500:

https://marketing.orangeweb.com.br/mtracking.gif?page_title=Luiz%20Eduardo%20%E2%80%93%20Consultor%20Mautic%2C%20Elementor%20e%20Wordpress&page_language=pt-BR&page_referrer=&page_url=https%3A%2F%2Fluizeof.com.br%2F&counter=0&resolution=1280x800&timezone_offset=120&platform=MacIntel&do_not_track=unknown&adblock=true&fingerprint=bbd90345faaa9f9e88cd43608307b1d1

**Comment by tannguyen04** [comment]
Same with me, anyone have solution ???

**Comment by escopecz** [comment]
The error 500 during the JS tracking is a different issue: https://github.com/mautic/mautic/issues/3397

@mbernabeu I cannot replicate the JS issue. Is it in some specific browser?

**Comment by mbernabeu** [comment]
Google Chrome 56.0.2924.87

**Comment by joazvsoares** [comment]
Hello, any thoughts on this?

**Comment by joazvsoares** [comment]
Hello, after debugging I found out that the issue was in following loop:

```
for (var i in MauticJS.postEventDeliveryQueue) {
     MauticJS.postEventDeliveryQueue[i](e.detail);
     delete MauticJS.postEventDeliveryQueue[i];
}
```

The use of "for in" for loops may not work as desired as you can see here:

> Use for-in correctly:
> You'll get people telling you to use for-in, but that's not what for-in is for. for-in loops through the enumerable properties of an object, not the indexes of an array. The order is not guaranteed, not even in ES2015 (ES6). ES2015 does define an order to object properties (via [[OwnPropertyKeys]], [[Enumerate]], and things that use them like Object.getOwnPropertyKeys), but it does not define that for-in will follow that order. (Details in this other answer.)

[https://stackoverflow.com/questions/9329446/for-each-over-an-array-in-javascript](https://stackoverflow.com/questions/9329446/for-each-over-an-array-in-javascript)

I changed the loop to `for(var i=0,len=MauticJS.postEventDeliveryQueue.length;i<len;i++)` and the error is gone.

@escopecz what do you think about this change?

**Comment by dbhurley** [comment]
Is this still an issue?
