### ISSUE TITLE
can't edit existing or newly created campaign after upgrade to 2.6

### ISSUE THREAD

**Issue by damiike** [mautic/mautic#3394]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N 
| Enhancement? | N

## Description:
I updated from v2.4 to v2.6.
Updated without any issues.
Went to edit my campaign.
All links between campaign elements were missing. e.g. the action existed, but did not show the workflow links between. 
When editing the action, the execution delay (.e.g. 5 days delay) still exited, but even if I saved, it did not show or restore the link / workflow.

This means I can't edit any existing campaigns, or in the future with this bug.

Appreciate the help as I love Mautic!!!!

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6
| PHP version | 5.6.30

### Steps to reproduce:
1. Go to an existing campaign
2. Edit campaign
3. Launch campaign builder

all links between elements are missing. e.g. send email exists, but the 5 day delay is missing.

Scenario 2:
1. Create a new campaign
2. Add a segment condition
3. Add action to send email
4. Save campaign
5. Open the campaign again
6. Launch campaign builder

all links between elements are missing. e.g. send email exists, but the 5 day delay is missing.

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by damiike** [comment]
forgot to mention, I tested this in both Firefox - latest v, and Chrome - latest v. Running windows 10.

Thanks

**Comment by alerto84** [comment]
Hi, i have the same issue, did you found a solution at the end?
