### ISSUE TITLE
Mautic update stuck on Moving Package Contents: in Progress

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#340]
While updating mautic from 1.0.2 to 1.0.3 the update is stuck on "Moving Package Contents: in Progress".

(this is different than https://github.com/mautic/mautic/issues/312. Different server, stuck on another step in the upgrade proces)

Meanwhile the page keeps sending thousands of http requests to urls like:
http://mautic.example.com/upgrade/upgrade.php?task=moveBundles&updateState=eyJhZGRvbkNvbXBsZXRlIjpmYWxzZSwiYnVuZGxlQ29tcGxldGUiOmZhbHNlLCJjYWNoZUNvbXBsZXRlIjpmYWxzZSwiY29yZUNvbXBsZXRlIjpmYWxzZSwidmVuZG9yQ29tcGxldGUiOmZhbHNlLCJjb21wbGV0ZWRCdW5kbGVzIjp7IlJlcG9ydEJ1bmRsZSI6dHJ1ZSwiQ2F0ZWdvcnlCdW5kbGUiOnRydWUsIkFzc2V0QnVuZGxlIjp0cnVlLCJBZGRvbkJ1bmRsZSI6dHJ1ZSwiQ2FtcGFpZ25CdW5kbGUiOnRydWUsIlBhZ2VCdW5kbGUiOnRydWUsIkRhc2hib2FyZEJ1bmRsZSI6dHJ1ZSwiTGVhZEJ1bmRsZSI6dHJ1ZSwiQ29yZUJ1bmRsZSI6dHJ1ZSwiRm9ybUJ1bmRsZSI6dHJ1ZSwiVXNlckJ1bmRsZSI6dHJ1ZSwiRW1haWxCdW5kbGUiOnRydWUsIkFwaUJ1bmRsZSI6dHJ1ZSwiSW5zdGFsbEJ1bmRsZSI6dHJ1ZSwiUG9pbnRCdW5kbGUiOnRydWV9fQ==&_=1429769497583&mauticUserLastActive=101&mauticLastNotificationId=61

Query params that are chaning each request are "mauticUserLastActive" and "_"

The server response is ````{"complete":false,"error":false,"updateState":"eyJhZGRvbkNvbXBsZXRlIjpmYWxzZSwiYnVuZGxlQ29tcGxldGUiOmZhbHNlLCJjYWNoZUNvbXBsZXRlIjpmYWxzZSwiY29yZUNvbXBsZXRlIjpmYWxzZSwidmVuZG9yQ29tcGxldGUiOmZhbHNlLCJjb21wbGV0ZWRCdW5kbGVzIjp7IlJlcG9ydEJ1bmRsZSI6dHJ1ZSwiQ2F0ZWdvcnlCdW5kbGUiOnRydWUsIkFzc2V0QnVuZGxlIjp0cnVlLCJBZGRvbkJ1bmRsZSI6dHJ1ZSwiQ2FtcGFpZ25CdW5kbGUiOnRydWUsIlBhZ2VCdW5kbGUiOnRydWUsIkRhc2hib2FyZEJ1bmRsZSI6dHJ1ZSwiTGVhZEJ1bmRsZSI6dHJ1ZSwiQ29yZUJ1bmRsZSI6dHJ1ZSwiRm9ybUJ1bmRsZSI6dHJ1ZSwiVXNlckJ1bmRsZSI6dHJ1ZSwiRW1haWxCdW5kbGUiOnRydWUsIkFwaUJ1bmRsZSI6dHJ1ZSwiSW5zdGFsbEJ1bmRsZSI6dHJ1ZSwiUG9pbnRCdW5kbGUiOnRydWV9fQ==","stepStatus":"In Progress"}````

Full http headers are
````Remote Address:195.211.74.22:80
Request URL:http://mautic.example.com/upgrade/upgrade.php?task=moveBundles&updateState=eyJhZGRvbkNvbXBsZXRlIjpmYWxzZSwiYnVuZGxlQ29tcGxldGUiOmZhbHNlLCJjYWNoZUNvbXBsZXRlIjpmYWxzZSwiY29yZUNvbXBsZXRlIjpmYWxzZSwidmVuZG9yQ29tcGxldGUiOmZhbHNlLCJjb21wbGV0ZWRCdW5kbGVzIjp7IlJlcG9ydEJ1bmRsZSI6dHJ1ZSwiQ2F0ZWdvcnlCdW5kbGUiOnRydWUsIkFzc2V0QnVuZGxlIjp0cnVlLCJBZGRvbkJ1bmRsZSI6dHJ1ZSwiQ2FtcGFpZ25CdW5kbGUiOnRydWUsIlBhZ2VCdW5kbGUiOnRydWUsIkRhc2hib2FyZEJ1bmRsZSI6dHJ1ZSwiTGVhZEJ1bmRsZSI6dHJ1ZSwiQ29yZUJ1bmRsZSI6dHJ1ZSwiRm9ybUJ1bmRsZSI6dHJ1ZSwiVXNlckJ1bmRsZSI6dHJ1ZSwiRW1haWxCdW5kbGUiOnRydWUsIkFwaUJ1bmRsZSI6dHJ1ZSwiSW5zdGFsbEJ1bmRsZSI6dHJ1ZSwiUG9pbnRCdW5kbGUiOnRydWV9fQ==&_=1429769500783&mauticUserLastActive=288&mauticLastNotificationId=61
Request Method:GET
Status Code:200 OK
Response Headers
view source
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:328
Content-Type:application/json; charset=utf-8
Date:Thu, 23 Apr 2015 06:29:15 GMT
Keep-Alive:timeout=1, max=87
Server:Apache
Vary:Accept-Encoding,User-Agent
Request Headers
view source
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-GB,nl-NL;q=0.8,nl;q=0.6,en-US;q=0.4,en;q=0.2
Connection:keep-alive
Cookie:6666cd76f96956469e7be39d750cc7d9=rsnsdg6aordi05j3vea0kgoeu7; mautic_session_name=6666cd76f96956469e7be39d750cc7d9; _ga=GA1.2.78942935.1416385051
Host:mautic.example.com
Referer:http://mautic.example.com/s/update
User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
X-Requested-With:XMLHttpRequest
Query String Parameters
view source
view URL encoded
task:moveBundles
updateState:eyJhZGRvbkNvbXBsZXRlIjpmYWxzZSwiYnVuZGxlQ29tcGxldGUiOmZhbHNlLCJjYWNoZUNvbXBsZXRlIjpmYWxzZSwiY29yZUNvbXBsZXRlIjpmYWxzZSwidmVuZG9yQ29tcGxldGUiOmZhbHNlLCJjb21wbGV0ZWRCdW5kbGVzIjp7IlJlcG9ydEJ1bmRsZSI6dHJ1ZSwiQ2F0ZWdvcnlCdW5kbGUiOnRydWUsIkFzc2V0QnVuZGxlIjp0cnVlLCJBZGRvbkJ1bmRsZSI6dHJ1ZSwiQ2FtcGFpZ25CdW5kbGUiOnRydWUsIlBhZ2VCdW5kbGUiOnRydWUsIkRhc2hib2FyZEJ1bmRsZSI6dHJ1ZSwiTGVhZEJ1bmRsZSI6dHJ1ZSwiQ29yZUJ1bmRsZSI6dHJ1ZSwiRm9ybUJ1bmRsZSI6dHJ1ZSwiVXNlckJ1bmRsZSI6dHJ1ZSwiRW1haWxCdW5kbGUiOnRydWUsIkFwaUJ1bmRsZSI6dHJ1ZSwiSW5zdGFsbEJ1bmRsZSI6dHJ1ZSwiUG9pbnRCdW5kbGUiOnRydWV9fQ==
_:1429769500783
mauticUserLastActive:288
mauticLastNotificationId:61````

The error log show this entry, not sure if it's related
````[2015-04-23 04:33:29] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Sorry! The requested URL was not found." at /home/example.com/domains/example.com/public_html/mautic/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 151 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Sorry! The requested URL was not found. at /home/example.com/domains/example.com/public_html/mautic/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:151)"} []````

**Comment by mbabker** [comment]
The decoded update state:

```
'{"addonComplete":false,"bundleComplete":false,"cacheComplete":false,"coreComplete":false,"vendorComplete":false,"completedBundles":{"ReportBundle":true,"CategoryBundle":true,"AssetBundle":true,"AddonBundle":true,"CampaignBundle":true,"PageBundle":true,"DashboardBundle":true,"LeadBundle":true,"CoreBundle":true,"FormBundle":true,"UserBundle":true,"EmailBundle":true,"ApiBundle":true,"InstallBundle":true,"PointBundle":true}}'
```

At a glance, the `upgrade.php` script may be hitting an edge case where the `$completed` variable never gets set to true and potentially could cause the step that extracts and moves bundles to never register as completed.

In the case with this update, as 15 bundles were included in the update package and we have an iteration at 5 completed bundles, it seems like it may have been possible for the iterator to reach the case where 5 bundles completed and we instructed the script to break out to repeat for the next batch (which doesn't exist).  For that next batch, the directory count would be 0, so the script never enters into the space where the `$completed` variable gets set (which in theory would cause undefined variable messages to show up in the system's PHP error log), so the system could in theory never match the `$completed` is true condition to move the updater into the next step.
