### ISSUE TITLE
Cannot view all table columns on smaller screen sizes

### ISSUE THREAD

**Issue by scottbuscemi** [mautic/mautic#3400]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When viewing any data tables via a mobile browser, most columns are not appearing. For example, going to Components > Forms only shows the columns for (1) checkbox, and (2) Name.

![screen shot 2017-02-11 at 9 59 24 am](https://cloud.githubusercontent.com/assets/4336848/22856153/cb6b31a6-f040-11e6-93b6-6e47c80d9c2e.png)

The columns are lost when the screen width is less than 992px.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6

### Steps to reproduce:
1. Open any dashboard screen with a datatable
2. Reduce screen size to below 992px

**Comment by Getron** [comment]
Same here, on my Android Samsung Note 3, i'm not able to see all tables, the tables are cutted, or hided, and therefore, it is very unconfortable to work from a mobile devices, included tabs to.

Please, check this and fix it for mobiles, to not hide the tables.

**Comment by escopecz** [comment]
This is actually on purpose. Some columns are removed because they wouldn't fit the small screen. If you want to see everything like on the desktop then turn on the desktop mode on your device.
