### ISSUE TITLE
Skype Chat Group

### ISSUE THREAD

**Issue by VcDesigns** [mautic/mautic#3401]
I just created a skype bot chat room for mautic 3rd party developers and other open source people who contribute, build and use Mautic.   Please click on link and add to contacts.  The more we can get others who are part of Mautic to join the better.

Paste the url around.    https://join.skype.com/bot/280a5069-c4a0-484e-88fb-a1f4d7af3dd3

**Comment by dongilbert** [comment]
@VcDesigns There is a dedicated Slack group for Mautic chat and discussion, which the community has greatly embraced. You can find more info here: https://www.mautic.org/

**Comment by VcDesigns** [comment]
slack you can't do with remote work together and share screen with slack, on the spot.  Slack is a great app for a lot of things, it doesn't do what skype can do, as well skype can connect you directly to development tools because it is linked to microsoft and other development platforms.

**Comment by MxyzptlkFishStix** [comment]
@dongilbert @VcDesigns Slack has Skype integration.
