### ISSUE TITLE
Trying to create a new custom field with existing Alias causes error

### ISSUE THREAD

**Issue by fatihbuyuktas** [mautic/mautic#3402]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Trying to create a new custom field with existing Alias causes below error:
The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
System administrators, check server logs for errors.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.0
| PHP version | 7.0.13-0ubuntu0.16.04.1

### Steps to reproduce:
1. Create a custom field with an alias "test"
2. Create another custom field and type "test" as alias.
 
### Log errors: 

[2017-02-11 21:39:04] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Symfony\
Bundle\FrameworkBundle\Templating\Helper\FormHelper::errors() must be an instance of Symfony\Component\Form\FormView, null given, ca
lled in /var/www/mautic/app/bundles/CoreBundle/Views/FormTheme/Custom/sortablelist_row.html.php on line 31 - in file /var/www/mautic
/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php - at line 205 [] []
ubuntu@ip-172-31-4-34:/var/www/mautic/app/logs$ > mautic_prod-2017-02-11.php

**Comment by escopecz** [comment]
I cannot reproduce it at Mautic 2.6.1. The alias automatically changes to `f_test1`
