### ISSUE TITLE
Segments and categories should not be a part of the "Preferences" menu item

### ISSUE THREAD

**Issue by scottbuscemi** [mautic/mautic#3405]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
A contact does not 'prefer' to be in a certain segment/category, so that option on the Contact view should not be within the "Preferences" menu item.

Instead, the editing of Categories and Segments should be done within the /s/contacts/edit/ view. Beside "Core" and "Social", there can be two new tabs for "Categories" and "Segments".

This change in UX will abide by the thinking that 'editing' a contact would include editing their segment. The current editing of segments and categories is not intuitively placed.

**Comment by isleshocky77** [comment]
I noticed a "third" UX is the "Campaigns" link under the Contacts drop-down. I would like to see one consistent UX for view/edit/delete for Segments, Categories, and Campaigns when available.
