### ISSUE TITLE
Dynamic Content fails to display in "web view" emails

### ISSUE THREAD

**Issue by stevegrant1983** [mautic/mautic#3414]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The {dynamiccontent="Content Title"} shortcode appears to not be translated within the web view of an email. It works correctly in the email itself, but if the "view in web browser" link is clicked within that email, the shortcode is displayed raw, rather than translated to the intended content.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.0
| PHP version | 5.6.23

### Steps to reproduce:
1. Create an email, adding a dynamic content block (can be an image, a block of text, whatever), and ensuring that the "View in web browser" link is included in the email body.
2. Set up a campaign to send the email
3. Send the email
4. Open the email in your mail client. Dynamic content appears as expected.
5. Click the "view in web browser" link - the dynamic content does not appear; instead, the {dynamiccontent="Dynamic Content Block Title"} shortcode is displayed instead.

**Comment by onconcz** [comment]
Same

**Comment by dbhurley** [comment]
Is this still an issue in 2.11?
