### ISSUE TITLE
Company not saving after 2.6 Update

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3425]
After updating to 2.6, I've noticed my forms break. When submitting, I saw this in the Chrome console: 

`Failed to load resource: the server responded with a status of 500 (Internal Server Error) /form/submit?formId=11`

The form actually does submit and the record is created in Mautic. However, it doesn't show up correctly. The "company" field always fails to save into a lead's profile now:

<img width="715" alt="screen shot 2017-02-13 at 11 29 09 am" src="https://cloud.githubusercontent.com/assets/590678/22897207/26fca248-f1e0-11e6-9a8c-b61903dda9f7.png">

Clearing Mautic's cache and Chrome's cache resolved the 500 error, but the company field is still not ever saved to a lead's profile. Everything is mapped correctly in the form and the company field does show up in the form results, just not on a lead's profile. This is also breaking our push to Salesforce in the campaign.

Any idea what could be happening here?

Thanks

**Comment by escopecz** [comment]
The error message would be very helpful. See https://mautic.org/docs/en/tips/troubleshooting.html about how to get it.

**Comment by nickian** [comment]
Assuming this is the same issue, this is only thing in the Mautic log:

`[2017-02-13 12:29:28] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "LIMIT argument offset=-25 is not valid" at /home/mautic/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php line 3318 {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): LIMIT argument offset=-25 is not valid at /home/mautic/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:3318)"} []`

**Comment by nickian** [comment]
Also, I have confirmed that this is not specific to that one installation. Same bug is occurring on a separate install on an entirely different server.

**Comment by escopecz** [comment]
Could you write step by step tutorial about how to replicate the issue? It'd be really nice if you could fill in the prefilled issue template next time. The questions I'm asking are there to answer.

**Comment by nickian** [comment]
Sorry, I will use that next time. It's as simple as create a test form with a company field mapped to the core company field. Go to preview and try to submit it. The company doesn't get added to a lead, but does save in the form results.

The only other info I left out was I'm running PHP 7.0.14 and MySQL 5.7.17.

**Comment by escopecz** [comment]
Thanks! I can replicate.
