### ISSUE TITLE
New installation to same database deletes data of current installation

### ISSUE THREAD

**Issue by pavel-janicek** [mautic/mautic#3431]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | Y 
| Enhancement? | N

## Description:
If you install new mautic by accidentally using database information to schema where is mautic already installed, the installation fails, but before that it will overwrite current data and delete some vital information

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.0

### Steps to reproduce:
1. Install mautic to clean database and set up admin user. We will call this installation **original**
2. Start new installation on different folder of your hosting.
3. When installing, use exactly same database credentials as you used when installing original installation
4. New installation will fail
5. Try to login to original installation - unable to login
6. Check database status. Tables exist but are empty. Namely table "users"
 
### Log errors: 

No log errors.

P.S.: Yes, I know that what I did is utterly stupid. Yes, I had backups, luckily. But still I think, that new installation should check first if data exist in database before trying to write anything.

**Comment by RCheesley** [comment]
From memory, isn't there an option in the installer to either nuke the tables or rename if found? Did you choose nuke or rename?

**Comment by pavel-janicek** [comment]
I forgot to mention that. While being stupid on putting same details as I did before, I left the "backup database automatically" untouched with option that table with prefix bak_ should be created.

1. Previously, there was no mautic-related table with prefix bak_
2. There was no other table starting with bak or bak_ in my database before install

After install, no table with bak_ prefix was created
