### ISSUE TITLE
2.6.0 - lead_fields table is missing on fresh install

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#3436]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Fresh instance of Mautic 2.6.0 results in errors in the log related to a missing table:

[2017-02-14 09:37:38] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM mau_lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'local-mautictest.mau_lead_fields' doesn't exist 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.0 vanilla install via download (not via Github)
| PHP version | 7.0.15

### Steps to reproduce:
1. Install Mautic
2. I made a couple of changes to email settings in config - not sure what triggered the error!
2. Check error logs
 
### Log errors: 

[2017-02-14 09:37:38] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM mau_lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'local-mautictest.mau_lead_fields' doesn't exist

**Comment by escopecz** [comment]
If you check the database, is the table `mau_lead_fields` there? Mautic would throw errors almost on every page if this table would not exist. Editing a contact works?

**Comment by RCheesley** [comment]
Hi @escopecz - table seems to be there now, but it wasn't previously as I checked and double checked ... weird! That error was in the log from when I just installed Mautic. Can try again if that would be helpful, still have the installer

**Comment by escopecz** [comment]
If you could check in what step this error occurs, it'd be very helpful.

**Comment by RCheesley** [comment]
@escopecz I ran a vanilla install from the 2.6.0 installer on my localhost, with an empty database and I see the error in the logs still.

Guess it might be a red herring as the table does seem to be getting created, but the log entry is definitely present, and it seems from the timing to be happening during installation (it was around a minute before I got to the log screen).

Screencast of the installation process here: https://youtu.be/ZcZ91UCqLKk

**Comment by kauelinden** [comment]
Hello. Just to notice..

I'm trying to install mautic 2.6.0 on my server that is php7 and the BD is  5.5.53-MariaDB during the install I got the same error message in my log.

[2017-02-16 15:45:52] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM mauticlead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'hostnetfranquia1.mauticlead_fields' doesn't exist [] []

it occours in the first step:
/mautic/installer/step/1

**Comment by isacsouza** [comment]
Problem to save settings

I installed the version of mautic 2.6.0 and when I do some configuration, for example change the language, after I click save the system prompts to wait and does not make the modifications. What can this be? Because I can not save any configuration on the system, in the log I have the same problem reported above, can anyone help me?

**Comment by RCheesley** [comment]
@isacsouza this is a different issue, did you try updating to 2.6.1 and clearing the cache?

**Comment by isacsouza** [comment]
Yes I changed it to version 2.6.1, now it is saving, but now the system is generating several errors and I am not able to create a new email and save.

**Comment by Gregy** [comment]
I can reproduce @RCheesley 's issue on clean install of 2.7.1. The error appears in the logs just after the db initialization installer step.

**Comment by ralfhug** [comment]
I can reproduce @RCheesley and @Gregy error with a 2.8.0 clean install as well. Also, lead_fields table was created. 

mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db498156_13.lead_fields' doesn't exist [] []

**Comment by Dude4Linux** [comment]
@kauelinden Which timeout did you remove to eliminate the error?  I'm seeing the problem on a fresh install of 2.8.1.  I doubt this error is related to the other issue(s) I'm seeing, but I would like to eliminate the possibility that something else didn't get installed properly.  Thanks

**Comment by kauelinden** [comment]
@Dude4Linux you have to check with your hosting if they have timeout by default. On my web hosting I am able set how long scripts can run before they are killed by the system. I did it on my control panel but my hosting is from Brasil ([Hostnet](https://www.hostnet.com.br)) and they provide their own panel.

**Comment by Dude4Linux** [comment]
@kauelinden I'm self-hosting on a TurnKey LAMP appliance (runs Debian Jessie). In php.ini I've bumped the memory_limit to 256M.  max_execution_time was set to 30 seconds, I increased it to 300 but still get this error on fresh install. After the install, I'm only seeing two plugins, OneSignal and Twilio. I don't think this error is related to my problem, so I'll open a new issue.  Thanks

**Comment by adrianogf** [comment]
Fresh instance of Mautic 2.0.10 results

[2017-09-13 23:06:14] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  Table 'mautic.lead_fields' doesn't exist [] []

System Ubuntu 14.04
Php 5.6.31
Mysql 5.6.33

**Comment by phil-davis** [comment]
This happens in a test environment in the sequence of creating the database and schema. e.g. do:
```
php app/console doctrine:database:create --env=test
Created database `mautictest` for connection named default
php app/console doctrine:schema:create --env=test
ATTENTION: This operation should not be executed in a production environment.

Creating database schema...
[2017-10-04 03:36:37] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautictest.lead_fields' doesn't exist  
Database schema created successfully!
php app/console doctrine:migrations:version --add --all --no-interaction --env=test
php app/console doctrine:fixtures:load --no-interaction --env=test
[2017-10-04 03:40:06]   > purging database
[2017-10-04 03:40:07]   > loading [1] Mautic\UserBundle\DataFixtures\ORM\LoadRoleData
[2017-10-04 03:40:07]   > loading [2] Mautic\UserBundle\DataFixtures\ORM\LoadUserData
[2017-10-04 03:40:10]   > loading [4] Mautic\LeadBundle\DataFixtures\ORM\LoadLeadFieldData
[2017-10-04 03:40:23]   > loading [5] Mautic\LeadBundle\DataFixtures\ORM\LoadLeadData
[2017-10-04 03:40:33]   > loading [5] Mautic\LeadBundle\DataFixtures\ORM\LoadLeadListData
[2017-10-04 03:40:37]   > loading [5] Mautic\ReportBundle\DataFixtures\ORM\LoadReportData
[2017-10-04 03:40:37]   > loading [6] Mautic\PageBundle\DataFixtures\ORM\LoadPageCategoryData
[2017-10-04 03:40:37]   > loading [7] Mautic\PageBundle\DataFixtures\ORM\LoadPageData
[2017-10-04 03:40:37]   > loading [8] Mautic\FormBundle\DataFixtures\ORM\LoadFormData
[2017-10-04 03:40:40]   > loading [8] Mautic\PageBundle\DataFixtures\ORM\LoadPageHitData
[2017-10-04 03:40:47]   > loading [9] Mautic\EmailBundle\DataFixtures\ORM\LoadEmailData
[2017-10-04 03:40:47]   > loading [9] Mautic\FormBundle\DataFixtures\ORM\LoadFormResultData
[2017-10-04 03:41:02]   > loading [10] Mautic\AssetBundle\DataFixtures\ORM\LoadAssetData
```
The issue seems to be in:
https://github.com/mautic/mautic/blob/14efc716ea83b6ad1d0085355e2a74cfd6121355/app/bundles/LeadBundle/EventListener/DoctrineSubscriber.php#L53
``postGenerateSchema()`` tries to look in the lead_fields table to see what fields are there and add some commonly-needed indexes for "fixed" known core fields. But at that point the schema has been generated in doctrine, but not (quite) yet actually implemented in the real database back-end.

Thus at:
https://github.com/mautic/mautic/blob/14efc716ea83b6ad1d0085355e2a74cfd6121355/app/bundles/LeadBundle/EventListener/DoctrineSubscriber.php#L58
``if (!$schema->hasTable(MAUTIC_TABLE_PREFIX.'lead_fields'))``
is false (i.e. ``hasTable`` is true because the schema does have the table, it just has not been created on the back-end database yet).
So the code carries on, thinking it will be able to do stuff on the real table. But it cannot, and gets the error when trying to execute the first SQL SELECT on the table.

Someone familiar with the whole order of creating the database, creating the schema, performing the migrations... should be able to move this code somewhere later in the process, so it will run after the table really exists.

**Comment by phil-davis** [comment]
There are plenty of forum posts reporting this, e.g.:
https://www.mautic.org/community/index.php/5327-issues-with-version-2-1
https://www.mautic.org/community/index.php/7839-issue-installing

**Comment by ahfauth** [comment]
Same thing here
Fresh install of Mautic v2.13.1
PHP Version 7.0.10
pdo_mysql 10.1.32-MariaDB

[2018-04-30 23:19:45] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lapa_mautic.lead_fields' doesn't exist [] []

But I can see the table "lead_fields" on DB

**Comment by galvani** [comment]
@dbhurley could You please reopen it unless you see any other issue describing it? This problem persists.

**Comment by dbhurley** [comment]
Sure! Are you working on it?

**Comment by galvani** [comment]
@dbhurley I should, I hate errors. I will consider it part of the testing I am doing now and resolve it.

**Comment by galvani** [comment]
is anyone else doing anything on this? if not, I will take it.

**Comment by AkkuFresh** [comment]
The fresh Mautic 2.15.0 install also creates the too same error message during the install process.

`[2018-12-23 19:10:05] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM <prefix>_lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table '<Table_name>.<prefix>_lead_fields' doesn't exist [] []`

Checking the SQL, the **named table is there**. May the schema looking for some missing views?

**Comment by phil-davis** [comment]
From memory, it is an order of operations problem. The table does get created later on in the initialization process. But you probably end up missing some indexes... that are attempted to be created before the table really exists - https://github.com/mautic/mautic/issues/3436#issuecomment-334062990

**Comment by YosuCadilla** [comment]
As @phil-davis pointed out, problem seems to be the creation order and/or the lack of proper checks in the installation script. At some point the installation script does not check if the table has been created and issues some commands that the system is unable to perform cause the table has not yet been created.

It happen twice to me, both times on quite fast servers, which would suggest the PHP script is getting ahead of itself, when the database tables take more time to be created than the execution of the script, this error occurs.

@galvani did you come up with a solution?

ITM time:  If you ignore the error it will disappear silently... However it might be a good idea to run:
php app/console doctrine:schema:update --dump-sql
to make sure everything is fine.

Anyway, "RCheesley opened this issue on Feb 14, 2017", 2 years have passed, let's find a solution!

**Comment by Pomazan-Bogdan** [comment]
you need to automatically create the necessary tables at the start of the docker.

Someone has a clean database dump?

**Comment by Dirk-Bbe** [comment]
If someone can export a working clean database, we can manually create the db and then import the clean db. Could that work? (as a work around)

**Comment by escopecz** [comment]
Why is there a need for a workaround? This issue didn't get any attention because it's not blocking anything. The installer will create the database structure correctly with all tables and data. The only issue is that it produces this error along the way.

**Comment by RCheesley** [comment]
Still seeing this error in 2.16 fresh installs 🤦‍♀

**Comment by alanhartless** [comment]
This error happens as the natural part of the installation process as Doctrine builds the initial schema. The exception is expected in that case but not others so we still log it. If the error itself is disturbing, then we could simply not log it during the installation process. Otherwise there’s nothing else to fix.

**Comment by afonseca08** [comment]
@alanhartless makes sense as you describe. If the exception if "expected" as part of the installation process, then it should be caught and handled in code and not output to the log.

Errors are and should remain disturbing indicators that something has gone wrong IMHO.

BTW, repro'd this in 3.x local test environment.

**Comment by alanhartless** [comment]
Just need someone to PR an if(defined('MAUTIC_INSTALLER')) return; in the DoctrineSubscriber before it's logged and the logged error will be prevented.

**Comment by npracht** [comment]
Hello there, please test #8765 !
