### ISSUE TITLE
email builder align image not working Mautic 2.6

### ISSUE THREAD

**Issue by martinstr** [mautic/mautic#3439]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When using the email builder and then add an image into the text area the alignment on the image does not work.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6
| PHP version | 7.0

### Steps to reproduce:
1. start email builder
2. add an image into the text area and try to align it to the right or middle and nothing will happen.
 
### Log errors: 

no log error 

![image](https://cloud.githubusercontent.com/assets/19844475/22927100/d6b3566c-f2af-11e6-8ec7-eb9eedc88063.png)

**Comment by martinstr** [comment]
Just noticed that I can't center an image slot either. Why is this not possible?
![image](https://cloud.githubusercontent.com/assets/19844475/22933213/205e2e02-f2cb-11e6-9820-23985dee276d.png)

**Comment by martinstr** [comment]
here is the code from the code view after I clicked on align right. 
```
<br>

<h2>Hello there!</h2>
<br><img class="fr-dib fr-draggable fr-fir" src="https://mysite/media/images/apple-touch-icon.png">
<br>We haven't heard from you for a while...
<br>
<br>{unsubscribe_text} | {webview_text}
```

Every time I have to fix it manually with adding `<img align="right"` in the code for it work.

**Comment by martinstr** [comment]
here I just added the code manually.
![image](https://cloud.githubusercontent.com/assets/19844475/22973421/e81cb0c8-f37d-11e6-80b7-d0f722e43a1b.png)

**Comment by vdrover** [comment]
You've closed this, linking to a PR for extra columns, but the issue still exists. The alignment button for images is non-functional.
