### ISSUE TITLE
Email builder breaks when copying the code view from one email to another

### ISSUE THREAD

**Issue by martinstr** [mautic/mautic#3447]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When creating an new email and then copy the code view from a other email to the new one then click save and close. If you then go into the newly created email again the slot is broken where you pasted the code and it says `div data-slot="text" data-param-undefined=".`
It do not work to edit it or delete the slot after that. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6
| PHP version | 7.0

### Steps to reproduce:
1. Create new email copy the code from one email slot to the new one, save and close
2. Open the email again and it will say `div data-slot="text" data-param-undefined="` and the slot is not editable and it dos not work to delete it. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

![image](https://cloud.githubusercontent.com/assets/19844475/22969882/560cb532-f370-11e6-97f0-fd775adcc8d6.png)
![image](https://cloud.githubusercontent.com/assets/19844475/22969987/bc896da0-f370-11e6-9cbb-131d3e152d21.png)

**Comment by Profitcore** [comment]
Same bug in 2.6.1 and 2.7.0, php 5.6.30
Copy from text editor and paste html in code view (theme "Blank") and you'll get `div data-slot="text"data-param-undefined="` in your email. Sometimes not from the first time, but if try 2-3 times - you'll get it. 
Test html:
`<br>
<br>test message
<br>
<br>
`

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/3638, will be released in Mautic 2.7.1
