### ISSUE TITLE
Send emails only on specific week days

### ISSUE THREAD

**Issue by martinstr** [mautic/mautic#3450]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
It would be awesome to have a feature to send emails on a specific week day in a campaign, not only a specific date. For ex. we have an pre-recorded webinar presentation that is ongoing every Tuesday and Thursday, it wold be great then to have an email that goes out that week day just before the webinar to remind new leads in that campaign on the webinar.
I know that some other email marketing tools like Aweber have this feature.

![image](https://cloud.githubusercontent.com/assets/19844475/22994141/109fcaf6-f3c6-11e6-81a9-3ab5de2a11d4.png)

**Comment by ninjoan** [comment]
i accomplish this using a Cron job attach to a campaign that only runs weekdays from 9:am to 5pm

**Comment by martinstr** [comment]
Hi thanks @ninjoan, but how did you point the cron job to a specific campaign? I didn't know that you could create one specific cron job only to one campaign could you post the command here?

**Comment by ninjoan** [comment]
@martinstr here is
`* 10-17 * * 1-5 /path/php /path/mautic/app/console mautic:campaigns:trigger --campaign-id=45 >/dev/null 2>&1`
45 is the ID of the campaign change by the one you use

**Comment by martinstr** [comment]
thanks 👍

**Comment by RCheesley** [comment]
Pretty sure this is an existing feature request from some time ago, will have a dig and see if I can find the original when I'm at my computer!

**Comment by robwent** [comment]
@ninjoan does that mean that you have crons set up for each campaign manually?
We have one cron that updates all campaigns at 15 minute intervals, so I'm guessing this would only work if we removed that and created a cron for each campaign and updated them as we add new ones?

**Comment by robwent** [comment]
The related issue might be this one: https://github.com/mautic/mautic/issues/539

Mentions a plugin that lets you add specific days or times of day to each event in a campaign - https://github.com/thirdset/ThirdSetMauticTimingBundle
