### ISSUE TITLE
Fresh install of release 2.6.1 from Github is missing the entire /vendor/ directory

### ISSUE THREAD

**Issue by corradofiore** [mautic/mautic#3457]
Hi All,

trying to install Mautic from the Github repo fails because the /vendor/ directory is empty.

Steps to reproduce:
````
$ wget https://github.com/mautic/mautic/archive/2.6.1.tar.gz
    [...bunch of output...]
$ tar xzf 2.6.1.tar.gz
$ ls -al mautic-2.6.1/vendor/
total 12
drwxrwxr-x  2 root root 4096 Feb 16 20:36 .
drwxrwxr-x 10 root root 4096 Feb 16 20:36 ..
-rw-rw-r--  1 root root   13 Feb 16 20:36 .htaccess
````

Of course, trying to launch the web installer fails with the following error:

````
2017/02/17 08:09:39 [error] 18824#18824: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/home/test/mautic-2.6.1/app/../vendor/autoload.php): failed to open stream: No such file or directory in /home/test/mautic-2.6.1/app/autoload.php on line 15
````

Thanks,
Corrado Fiore

**Comment by corradofiore** [comment]
Oh, and the `/bin/` directory is missing as well from the 2.6.1 release published on Github.

Thanks,
Corrado

**Comment by escopecz** [comment]
Please read https://github.com/mautic/mautic#disclaimer

GitHub version is for developers. Download production package from mautic.org.
