### ISSUE TITLE
404 when updating contact via API (only on edit)

### ISSUE THREAD

**Issue by martijnengler** [mautic/mautic#3463]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y 
| Feature request? | 
| Enhancement? | 

## Description:

When I try to update a contact via the API, a 404 error is returned. 

This does not happen when getting details, or creating a new contact. Only on update.

I've used a simple test script, using mostly code from the example on [the PHP Library page.](https://github.com/mautic/api-library)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 7.0.13
| NGINX version | 1.10.1

### Steps to reproduce:
1. Try to update a contact via the API
2. Expected behavior: contact gets updated. Actual behavior: 404 error
 
This is the script I'm using to test with (using basic auth, with the three constants filled with actual data of course):

```
<?php
define("AC_MAUTIC_URL", "https://mautic.example.org/");
define("AC_MAUTIC_USER", "myusername");
define("AC_MAUTIC_PASSWORD", "mypassword");

use Mautic\Auth\ApiAuth;
use Mautic\MauticApi;
require_once __DIR__ . '/vendor/autoload.php';

// ApiAuth->newAuth() will accept an array of Auth settings
$settings = array(
	'userName'   => AC_MAUTIC_USER,
	'password'   => AC_MAUTIC_PASSWORD
);

// Initiate the auth object specifying to use BasicAuth
$initAuth = new ApiAuth();
$auth = $initAuth->newAuth($settings, 'BasicAuth');
$api = new MauticApi();
$contactApi = $api->newApi('contacts', $auth, AC_MAUTIC_URL . "/api");

$fields = $contactApi->getFieldList();

// creating contact works fine:
$data = array('firstname' => 'API', 'companyemail' => 'mytest@example.org', 'ipAddress' => '127.0.0.1');
$response = $contactApi->create($data);
$new_contact = $response[$contactApi->itemName()];
var_dump($new_contact);

// read-only works fine:
$response = $contactApi->get($contactId);
var_dump($response);


// updating contact doesn't work:
// Requested URL not found: /api/contacts/74577/edit
$updatedData = array(
    'firstname' => 'Updated Name'
);

$response = $contactApi->edit($new_contact["id"], $updatedData);
var_dump($response);
```

### Log errors: 

Nothing in the logs, but this is the response from the API:

```
array (
  0 => 
  array (
    'message' => 'Requested URL not found: /api/contacts/74578/edit',
    'code' => 404,
    'type' => NULL,
  ),
)array(2) {
  ["errors"]=>
  array(1) {
    [0]=>
    array(3) {
      ["message"]=>
      string(49) "Requested URL not found: /api/contacts/74578/edit"
      ["code"]=>
      int(404)
      ["type"]=>
      NULL
    }
  }
  ["error"]=>
  array(2) {
    ["message"]=>
    string(145) "Requested URL not found: /api/contacts/74578/edit (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)"
    ["code"]=>
    int(404)
  }
}
```

**Comment by escopecz** [comment]
Check if it isn't the cache problem as here: https://github.com/mautic/api-library/issues/82#issuecomment-280995351

**Comment by martijnengler** [comment]
Sorry, should have mentioned that.

I've cleared the cache multiple ways, multiple times, to no avail. I've also tried to enter a "static" ID of an older contact, instead of trying to edit one that has just been created.

I don't understand enough of the Mautic source to know how the routing works. Is there a way to get a stacktrace or something? I think I might be able to provide more relevant information (or possibly even fix it myself) when we can get to the source of the problem.

**Comment by escopecz** [comment]
I tested your PHP script and it works. If you replace undefined `$contactId` with `$new_contact['id']`. The response of the edit endpoint is good for me:

```
/Users/jan/dev/mautic-api/test.php:42:
array (size=1)
  'contact' => 
    array (size=21)
      'isPublished' => boolean true
      'dateAdded' => string '2017-02-20T10:10:28+00:00' (length=25)
      'dateModified' => string '2017-02-20T10:10:31+00:00' (length=25)
      'createdBy' => int 1
...
```

**Comment by martijnengler** [comment]
The wrong var name ($contactID / $new_contact) was with the reading part. That works fine. (Okay, not if I use the wrong var name. Something went wrong when cleaning up the script.)

Thing is, even if I fix that (like in https://gist.github.com/martijnengler/1787237263653ed42fd7c9a16e863738) , the edit-endpoint still doesn't work with the same error.

And, like I said in my previous comment: when using a static ID of a known contact it also fails.

**Comment by escopecz** [comment]
There must be something wrong with your server. Maybe it doesn't allow PUT or PATCH HTTP methods. If you want to try it on other server, create a Mautic instance at mautic.net and test it there.

**Comment by martijnengler** [comment]
I've tested it with an instance we have running on another server. Works fine. So guess it *is* a server issue, and I just jumped to the wrong conclusion…

Thanks, I'll look into the server configuration

**Comment by martijnengler** [comment]
FWIW: it's fixed, and was some issue in the nginx config. If I knew the exact problem I'd post it here for people Googling and finding this issue, but I don't… So, future Googler: just know that it's probably something in your *server config*.

**Comment by FabianTe** [comment]
@martijnengler Do you have further information? I have the same issue and it works with a mautic instance at mautic.net. I looked into my configs but don't see anything specific that might cause a problem.

**Comment by martijnengler** [comment]
No, sorry. It's like I said in that last comment: it was *something*, *somewhere* in my nginx config.
But if it is at mautic.net I guess you should just go through their [support page](https://mautic.com/why-mautic/services-support/)

**Comment by laabidi21** [comment]
it is possible to change the Label of the standard Field in Mautic from API ?
I have Version 3.0.1
// Get contact field context:
$fieldApi = $api->newApi("contactFields", $auth, $apiUrl);
$id   = 1;
$data = array(
    'label' => 'API test field',
    'type' => 'text',
);

// Create new a field of ID 1 is not found?
$createIfNotFound = true;

$result = $fieldApi->edit($id, $data, $createIfNotFound);

I have a 500 type error. "message":"Looks like I encountered an error (error #500)
