### ISSUE TITLE
Next step for Mautic Focus installation unclear

### ISSUE THREAD

**Issue by scottbuscemi** [mautic/mautic#3465]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | x

## Description:

This may be a bug report or an enhancement request. After pressing on "Mautic Focus" within the main plugins menu, the next steps are quite unclear.

![screen shot 2017-02-19 at 10 21 43 am](https://cloud.githubusercontent.com/assets/4336848/23105014/579a3cf6-f68d-11e6-866f-c19dc11f70a2.png)

How can the user start taking advantage of this feature? How should they install it? Most other plugins have forms for entering in API data or signing up.

### Steps to reproduce:
1. To go the Plugins page 
2. Press on the title or image for Mautic Focus.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by scottbuscemi** [comment]
Even the Plugins that do have API integration forms need some sort of "intro". 

For example, what happens when I enter in my Instagram API data? What's the point of the integration there? Descriptions should supplement each plugin, like the WordPress plugin repo.

**Comment by RCheesley** [comment]
So far as I am aware, there is nothing that you actually need to configure in the plugin menu. Do you mean to actually state that nothing needs to be configured?

**Comment by scottbuscemi** [comment]
@RCheesley If there's nothing to be configured, there should be a link to the documentation at minimum so the user knows what to do next. It's unusual to view this modal and not have any prompt for a next step :)

**Comment by raymondkent** [comment]
There is nothing else you need to do.

I agree that is is not very clear how this works.

Once this plugin is activated under the Channels Menu  you will see the "Focus Items".

You use this to build your focus items. Like pop ups etc. that you can install on your website.

I have tried it, and although very basic (i.e not a lot of design options cant include images as an example. Text only.) Good for simple "modal pop ups", "hello" bars etc.

Let me know if you would like to see a simple tutorial and I'll set a couple up for you and screen flow the process.

**Comment by sogen** [comment]
Agreed, it's unclear the purpose of this plugin.

## SOLUTION:
Since it's already active (assumed by the aqua color), I'd suggest show a text inside the dialog, stating:

Mautic Focus is active! Learn how to use it at https://mautic.org/docs/en/focus/index.html
Or start using it: http://URL/s/focus


To be honest I'd just get rid of showing it in the plugins section, since there's no way to disable it.
Instead, I'd add a text box in the bottom left of Mautic, i.e. "New: Mautic Focus"
