### ISSUE TITLE
API endpoint for returning Mautic version number

### ISSUE THREAD

**Issue by scottbuscemi** [mautic/mautic#3466]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
An endpoint should be created that returns the current Mautic version number.

When creating applications that interact with Mautic, it's important to know the version number of the installation to ensure that all endpoints are available. In addition, new endpoints may be available to upcoming versions of Mautic that may not be accessible to installations that are not updated. Being able to notify users of applications that they should update their Mautic install to use all features would be helpful.

**Comment by nickian** [comment]
Good idea. In the mean time, there is a text file in the app folder called version.txt. You could simply put a php file somewhere with `echo file_get_contents('app/version.txt');`

**Comment by escopecz** [comment]
The API version is already sent in every response header. The API Library have a method to get it easily. The documentation for it wasn't merged yet, but here it is: https://github.com/mautic/developer-documentation/pull/42/files#diff-4554a1d82477db5bc4efc9f98a0bf4a5R31
