### ISSUE TITLE
Conditional Forms

### ISSUE THREAD

**Issue by Arjoni** [mautic/mautic#3467]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

It would be awesome to have conditional forms. For example, send different email for different checkbox. If the lead checked checkbox A, he would get email A.

**Comment by escopecz** [comment]
It can be done via campaigns. To build it to forms directly, we'd have to implement most of the campaigns functionality to forms. It makes more sense to use campaigns directly.
