### ISSUE TITLE
Exporting Reports to Excel skips first line

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3474]
| Q  | A
| ---| ---
| Bug report? | ✔️ 
| Feature request? | 
| Enhancement? | 

## Description:

Exporting Reports to Excel skips first line

![image](https://cloud.githubusercontent.com/assets/18265735/23128960/2a792a44-f781-11e6-8459-cca9e8772103.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 7.0.15

### Steps to reproduce:
1. Create 3 leads
2. Make a report on all contacts
3. Export to excel
4. Notice the first one is missing

**Comment by escopecz** [comment]
That's odd. I fixed that already here: https://github.com/mautic/mautic/pull/2628. It seems the bug returned 😫
