### ISSUE TITLE
Cannot create a segment filtering on the owner

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3475]
| Q  | A
| ---| ---
| Bug report? | ✔️ 
| Feature request? | 
| Enhancement? | 

## Description:

Cannot create a segment filtering on the owner.

![image](https://cloud.githubusercontent.com/assets/18265735/23129819/74d88500-f784-11e6-88bc-10e5ff18670f.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 7.0.15

### Steps to reproduce:
1. Try to create a segment filtering on the contact owner

**Comment by scottbuscemi** [comment]
It looks like this has been reported before: https://github.com/mautic/mautic/issues/2809. It's still an open issue here: https://github.com/mautic/mautic/issues/2892
