### ISSUE TITLE
Campaign emails not being sent in 2.6.1

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3481]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I have campaigns set up that include actions for sending out an email that were working fine in 2.5.1, but since upgrading to either 2.6.0 or 2.6.1, the send email action fails to execute or show up on user timelines. All of the other actions I have seem to be executing fine.

On one installation, it says the email sent on the timeline, but the email never actually went through. Normally, it says email not read, but it's showing up blank like this now when I toggle details:

<img width="835" alt="screen shot 2017-02-20 at 5 32 21 pm" src="https://cloud.githubusercontent.com/assets/590678/23146350/488394b8-f793-11e6-9419-8b77a3d3d498.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 7.0

### Steps to reproduce:
1. Create a campaign form that includes an email field
2. Create a campaign based on this form that has a send email action.
 
### Log errors: 

I don't have any errors logged in Mautic. I'm not seeing anything in Apache either.

**Comment by egyangel** [comment]
same issue

**Comment by nickian** [comment]
This seems to be an issue with existing campaigns breaking after the upgrade. When I did a fresh 2.6.1 install, created a campaign form and campaign email action, it worked fine.

I'm also getting this when trying to create a campaign form on the installation that broke:

![screen shot 2017-02-22 at 6 02 30 pm](https://cloud.githubusercontent.com/assets/590678/23240228/7f0fd6ee-f929-11e6-888a-0040fc9b589e.png)

Then, the name of the form that I just tried to show up appears in the "forms" list, but just gives a 500 error when you try to click on it.

![screen shot 2017-02-22 at 6 06 24 pm](https://cloud.githubusercontent.com/assets/590678/23240255/b10a4d3c-f929-11e6-8c3c-3aff4cdfd0e4.png)

**Comment by raymondkent** [comment]
Hi there,  I have the same issue.

The campaing starts sending emails, but then stops.

I have 5 campaigns running. One of them AFTER the upgrade. Its only two parts. 1 ) Select contact segment = [segment name]  then send campaign email = email no.8. immediately.

That's it. Nothing complicated at all. I do this to send out a blog update each week. I cant do as a broadcast email as the list is too large and I don't want to keep my screen open all day while emails are being sent.

This process worked fine in 2.5.1
The contact segment has 84,000 people - the same as when i ran it a week ago with V2.5.1
The campaign has executed, but then stopped after sending out 2,800 emails.

I cross checked with Amazon SES and the number of emails sent (more or less) match up.

The campaign segment update process seems to be working, but the campaign trigger seems to stop or is somehow broken.

cron job = [mautic url path]app/console mautic:campaigns:trigger -f --campaign-id=12

I also tried the generic one   [mautic url] app/console mautic:campaigns:trigger -f

It worked fine in 2.5.1 version.

**Comment by raymondkent** [comment]
What are you cron reports saying?

I set my cron in hostgator to email me a report after the commands run. 
I have recorded the error report in #3527 

Are you getting a similar error?

PS: I am manually running the cron jobs using the githib php script and it manages to send a few emails then it stops. 

very very painful at present. :-(

This is the main issue with my system at present. Campaign emails are just not being sent, yet in 2.5.1 they were. So it has to be something in 2.6.1 that is causing this issue.  All my cron commands stayed the same, but now don't seem to execute, and generate the error as reported in #3527 

manual email sends are working.

**Comment by raymondkent** [comment]
Hi Nick,

I found the issue with my systems settings and perhaps it might be the same with yours. It's worth checking out.

The web system seems that it can have several PHP versions running, and its easy to miss a setting. 

The one that runs the cron jobs needs to be set at PHP 5.6 Minimum and your CRON job needs to reference the 5.6 version.  My CRON jobs were set incorrectly and pointed to "55/bin" when they shold have been pointing to "56/bin".

before: 	/opt/php55/bin/php /home3/[mautic url path]/app/console mautic:campaigns:trigger --force

after:       /opt/php56/bin/php /home3/[mautic url path]/app/console mautic:campaigns:trigger --force

Check your websites PHP Selector and make sure it is set to 5.6

i.e in your control panel find the PHP Selector to go to the  "PHPConfig" screen.

then you will see a message something like...

"Note the following:

[-] The PHP System Default Version is 5.4
[-] Selecting "PHP Cur" will set the handler to latest stable PHP version available in our servers. This will be updated automatically in the future"

The “.php” file extension will be processed by  **this is where you select the PHP version [PHP 5.6]**   module_update"

NOTE: My PHP version was set correctly in the main system, but not in the cron jobs.
BOTH need to be set correctly for Mautic 2.6.1.

I hope this helps @escopecz pointed me in the right direction.

**Comment by nickian** [comment]
I'm not sure if you're referring to the same issue. It sounds like you use a shared hosting environment that can run different versions of PHP. That's not what I'm running. I'm just running it on an AWS EC2 instance with one version of PHP (7.0). I don't seem to be having any issues with cron jobs running.

**Comment by raymondkent** [comment]
Hi @nickian 

It was worth checking. 

You are correct. I was having cron execution issues, and I am on a shared hosting (hostgator - baby hatchling).

I had my system setup with the correct PHP version BUT my cron job path to the php/bin  was not pointing to the correct PHP version.

Sorry I can't offer any more help on this issue.

**Comment by amitkumarji** [comment]
I have created a campaign but It's not working.

Here is the error

[2017-02-28 08:24:49] mautic.WARNING: PHP Warning - fwrite() expects parameter 1 to be resource, boolean given - in file /home/www/mautic-master/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php - at line 98 [] []
[2017-02-28 08:24:49] mautic.WARNING: PHP Warning - fwrite() expects parameter 1 to be resource, boolean given - in file /home/www/mautic-master/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php - at line 98 [] []
[2017-02-28 08:24:49] mautic.WARNING: PHP Warning - fwrite() expects parameter 1 to be resource, boolean given - in file /home/www/mautic-master/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php - at line 98 [] []
[2017-02-28 08:24:49] mautic.WARNING: PHP Warning - fwrite() expects parameter 1 to be resource, boolean given - in file /home/www/mautic-master/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php - at line 98 [] []
[2017-02-28 08:24:49] mautic.WARNING: PHP Warning - fwrite() expects parameter 1 to be resource, boolean given - in file /home/www/mautic-master/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php - at line 98 [] []
[2017-02-28 08:24:49] mautic.WARNING: PHP Warning - fclose() expects parameter 1 to be resource, boolean given - in file /home/www/mautic-master/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php - at line 100 [] []

**Comment by amitkumarji** [comment]
If you need login detail.. then please do a comment and provide me your contact. I will send you the detail.

**Comment by raymondkent** [comment]
Hi @amitkumarji  

I don't know if it's the same type of issue I had, but have you checked your websites PHP version for your CRON jobs and is the path in your CRON jobs set to the correct PHP version?

**Comment by amitkumarji** [comment]
Yes, all are fine.

**Comment by raymondkent** [comment]
Sorry, I can't really offer any more advice. 

I hope someone can assist you.

**Comment by amitkumarji** [comment]
Thank you. @raymondkent

**Comment by amitkumarji** [comment]
Somehow it's working mautic 2.6.1  ....

**Comment by amitkumarji** [comment]
@nickian  Please use PHP 5.6 ,  Because in PHP 7 you will get more issues.

**Comment by escopecz** [comment]
Guys, is this still an issue with 2.9.2? I cannot replicate.
