### ISSUE TITLE
Conditions using contact field values as criteria are not saving select list input

### ISSUE THREAD

**Issue by JohnConnell** [mautic/mautic#3482]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:

When setting up conditions based on contact field values, select lists are not saving input. They are reverted to the first/top value in the select list after updating the condition. Input in regular text fields is stored correctly. [Related forum thread](https://www.mautic.org/community/index.php//6876-2-6-campaigns-conditions-disapear/0)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 7.0.13

### Steps to reproduce:

[.webm video w/ steps to reproduce](https://www.webmshare.com/KEO81) 

Written steps to reproduce:
1. Create new condition in a campaign
2. In the condition: set Contact Field to 'Country', set Operator to 'not equal', set Value to 'Afghanistan'
3. Click Update
4. Edit the condition again
5. Operator will have changed from 'not equal' to 'equal', Country will have changed from 'Afghanistan' to 'Abkhazia'

To further show that text field values are being stored correctly:

6. Change Contact Field from 'Country' to 'City', set Operator to 'not equal', set Value to '12345'
7. Click Update
8. Edit the condition again
9. Operator (select list) will have changed from 'not equal' to 'equal', but Value will remain '12345'
 
### Log errors: 

There are no log errors reported.

**Comment by kuzmany** [comment]
See https://github.com/mautic/mautic/pull/3473

**Comment by escopecz** [comment]
The bug fix moved to https://github.com/mautic/mautic/pull/3574
