### ISSUE TITLE
getAssetUrl in email template returns mautic directory twice in url path

### ISSUE THREAD

**Issue by katalysis** [mautic/mautic#3485]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
I have Mautic running in a directory /pages/.  Opening any email template e.g Oxygen in Builder fails to load the default images in the email template. The path generated for the images contains an additional /pages e.g. http://www.katalysis.net/pages/pages/themes/oxygen/img/bracelet.jpg

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 7.0.16

### Steps to reproduce:
1. open any email template
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by IADDIC** [comment]
I think there is a much broader cocondition with Mautic on a subdirectory.  I NOTICE that if the subdirectory is included in the site url on the configuration page then some things like icons do not work but if the url is not included then links in emails (unsubscribe for example) do notwork. 

I have not had the time to chase down all of the bugs related to this but I seem to have a large number of things not working:

Links in twitter messagesdo not work (bit.ly)
Fullcontact never populates although the connection seems to be made
Clearbit never populates although the connection seems to be made.
Linkedin never shows data even on my personal Al accounts which have linkedin profiles
No facebook integration (but that's a Facebook thing)
Chrome helper extenion stopped working (I think this is 3rd party)
Webhook / API fail and does not integrate on IFTTT

Believe me, I see where this is going and I think Mautic, even with these issues is the best opensource out there.  I respect the developers as It is apparent they need some help and I would do more but I am not a programmer.  All I can really do is give feedback.

**Comment by MarkKrauss** [comment]
Sounds similar to [MauticCommunityQuestion](https://www.mautic.org/community/index.php/6912-output-duplicate-directory-2-6), Maybe it works for you

**Comment by individual-it** [comment]
This happen to me after update from 2.5.1 to 2.7.1
Going to Configuration and removing the subfolder "mautic" from the Site-URL did solve the problem for me.
THX @MarkKrauss

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/4148

**Comment by YosuCadilla** [comment]
Having a similar problem with version 2.11.0
![mautic-page-builder-missing-images](https://user-images.githubusercontent.com/29537089/32770052-7d00ec60-c91e-11e7-868e-76ae1b811982.png)

**Comment by YosuCadilla** [comment]
Found the solution here:
https://www.mautic.org/community/index.php/6912-output-duplicate-directory-2-6
