### ISSUE TITLE
Campaign builder conditions do not handle Values according to Operator

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3494]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When you create a condition in a campaign on a **date field**, the operator you select does not match with the proposed values.
![capture d ecran 2017-02-21 a 15 03 56](https://cloud.githubusercontent.com/assets/14075239/23201256/0463cc70-f8d9-11e6-8188-7ed4e28d04ed.png)

I think very similar as  #3493

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6
| PHP version | 

### Steps to reproduce:
1. Create a date format contact field
2. Create a campaign
3. Add a condition on this field and selection empty as operator
4. See that you still have values which is not appropriated here

**Comment by escopecz** [comment]
Could you check if https://github.com/mautic/mautic/pull/3574 fixes this issue?

**Comment by isleshocky77** [comment]
@escopecz I'm on staging and have regenerated assets. Although the issue from #3574 is now fixed where the values weren't saving. There is now a bug which looks like this one where if you change the condition operator to "empty" or "not empty" the value input is still there and required which means you can't actually use the "empty" and "not empty" conditional operator.

**Comment by escopecz** [comment]
@isleshocky77 Please create a new issue

**Comment by isleshocky77** [comment]
@escopecz Isn't it this issue exactly? The value input box is not being handled by the conditional selector.

**Comment by escopecz** [comment]
Ah, you were just confirming that you can replicate. Got it.

**Comment by isleshocky77** [comment]
It appears this has to do with the data type of the field. In my case it's a select data type which means I can't use any of the conditionals because it will only show me choices for the values.
