### ISSUE TITLE
Campaign / Segments - Values on date format field improvement

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3495]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

# Description:
## Campaign
When you create a campaign, you can add condition on a date format contact field which is GREAT !
But when you select an operator like `less than` you have a list of available value which is totally frozen.
**You should have here the ability to select on 2 inputs:**

- Number
- Type --> Days, Weeks, Months, Years

Then you get much more flexibility.

![capture d ecran 2017-02-21 a 15 05 19](https://cloud.githubusercontent.com/assets/14075239/23201372/8816da44-f8d9-11e6-8c13-5b6d5a4ab95e.png)

## Segment
The same approach should be considered in segments knowing that today you can add text (with specific values) in the value of a date format knowing that this text is translated by the plateform so it is not the same values depending on the language!!!! This is crazy 👎 
The today's accepted conditions are: 

- Is today
- Is yesterday
- Is tomorrow
- Is this month
- Is last month
- Is next month
- Is this year
- Is last year
- Is next year

### Must have!!!
1. Do not write manually those values to avoid error and issues with translation.
2. Add anniversary
3. The same as explained for campaigns:

- Number input
- Type input --> Days, Weeks, Months, Years

To get more flexibility.

**Comment by YannickBiet** [comment]
+1 for the FR, date conditions are totally stucked as we can't create segments for birthday campaigns that would be dynamically sent to each contact which contains a birthdate + date is less than 5 days

**Comment by Berlira** [comment]
Hi - Under segments, if I want to segment by "age of new lead is less than 1 month", 
would I select/enter  "date added -->less than --> 30 days"

Thanks!

**Comment by FelixCoutinho** [comment]
+1

**Comment by jacdobro** [comment]
+1
