### ISSUE TITLE
Reimport of theme leads to stale cache

### ISSUE THREAD

**Issue by wittwerch** [mautic/mautic#3498]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes

## Description:
When you reimport a theme (delete and create) a stale copy of it remains in the cache.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | 7.0.13

### Steps to reproduce:
1. Import a theme
2. Create an email based on it
3. You spot a bug in the layout, so you fix that
4. Delete the theme and the email
5. Import the theme with the bugfix
6. Create an email based on it
7. The bug is still there

Workaround: You delete that cache between step 5 and 6.

**Comment by tpilet** [comment]
I'v the same problem
