### ISSUE TITLE
[Feature] Send a preview email

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#35]
It would be really helpful to be able to send a preview email when you're working on one, to check how it looks and to see how the fields will be populated.  Also useful to check how it appears in the email software/browser etc.

Ideally this would be either a button next to 'send' which said 'send preview' or have an intermediary when you press send that gives an option to send a test email, or send the email itself.

**Comment by dbhurley** [comment]
Definitely. This is very much a needed feature. Thanks for the suggestion!

**Comment by alanhartless** [comment]
This was implemented in RC1.
