### ISSUE TITLE
The config button on the builder for slidershow is not working

### ISSUE THREAD

**Issue by zhakid** [mautic/mautic#3505]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
when i press the configuration button on the left side of the screen to create new slide isn't working

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5
| PHP version |  7.0.8

### Steps to reproduce:
1.  Open the Mauve theme html folder inside the page.html.twig file
2. add this lines outside the <div class="container"> `{% if slotHasContent('slideshow') %}
        {{ slot('slideshow') }}
    {% endif %}`
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
The support for the slideshow slot was removed in Mautic 2.0. Sorry about that.

**Comment by zhakid** [comment]
Ok thax
