### ISSUE TITLE
Get a new Lead-Id

### ISSUE THREAD

**Issue by MarkKrauss** [mautic/mautic#3506]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
After a contact deletes the browser cache and then he sends a form with his (knowing) Email he get a new ID.
This behaviour is new since 2.6. We developed a plugin and services based on the Contact-ID and now they are worthless.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6
| PHP version | 7.0.14

### Steps to reproduce:
1. Contact submit a form with email-field
2. Contact delete browsercache
3. Contact submit a form with email-field again
4. Contact-ID (Lead-ID) is changing
 
### Log errors: 
None

**Comment by mqueme** [comment]
This was fixed in 2.6.1

**Comment by MarkKrauss** [comment]
not in my mautic 2.6.1 instance :(
i've made an upgrade from 2.2.1 to 2.6.1

**Comment by escopecz** [comment]
@MarkKrauss could you test if this fixes it for you? https://github.com/mautic/mautic/pull/3327

**Comment by MarkKrauss** [comment]
Unfortunately, no.

Normaly (mautic 2.2.1) the cookie value of mautic_session_id is the cookie name of the lead-id value. 
But there isn't:
  cookiename: mautic_session_id ,  value=foo_bar 
  cookiename: foo_bar ,  value=lead-Id

Better to upgrade from 2.5.1 as 2.2.1 or does it not matter

**Comment by MarkKrauss** [comment]
Tested with a new Mautic 2.6.1 instance and various browsers. Lead Id still counts +1 after sending a form with a known email adress. In my opinion it is a bug

**Comment by MarkKrauss** [comment]
Tested with a new Mautic 2.7.1. 
The ID of a contact counts +1 each time he submits a form. 
Can someone tell me this is a new behaviour (feature) or a bug? So I can adjust my plugin to it.

**Comment by filipelbc** [comment]
I'm also seeing this behavior.
