### ISSUE TITLE
PHP >= 5.6 is required - should be stated in the README

### ISSUE THREAD

**Issue by jessp01** [mautic/mautic#3510]
# Bug report

## Description:
In /var/www/html/mautic/app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php:582:
function debug_it($log, ...$context)
The '...' operator was introduced in PHP 5.6 so earlier PHP versions will produce a parse error.
I don't know if there are other places in the code that rely on features from 5.6 but if so, I recommend stating the minimum required PHP version in the README, if this is the only use of such features, I'd consider changing the code to use the func_num_args(), func_get_arg(), and func_get_args() functions instead.

## If a bug:
5.5.9 

### Steps to reproduce:
Try to run Mautic using PHP < 5.6
 
### Log errors: 
PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /var/www/html/mautic/app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php on line 582

**Comment by escopecz** [comment]
For the record, the requirements are listed here: https://www.mautic.org/download/requirements/

But you are right there should be link to that page from the readme.

**Comment by jessp01** [comment]
Hi @escopecz,
Adding a ref to www.mautic.org/download/requirements in the README should do it:)
I'd also mention additional needed PHP extensions, such as the XML one. Depending on the PHP packages you use, it may or may not be statically compiled into the main PHP binary [be it FCGI, Apache module, whatever] and you may need to install an additional package or add a directive under the PHP scandir. 
If you try to use the web installer without the XML extension loaded, you'll get:
```
Error: Class 'DOMDocument' not found - in file /var/www/html/mautic/vendor/symfony/config/Util/XmlUtils.php - at line 52
```
and a generic "The server is offline.." error on the page.

**Comment by jessp01** [comment]
Looks good to me:) Closing.
