### ISSUE TITLE
Send to integration stopped working (Hubspot plugin)

### ISSUE THREAD

**Issue by ahfauth** [mautic/mautic#3512]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | No
| Enhancement? | No

## Description:
After updating Mautic to 2.6.0 the Hubspot integration (sending contacts to Hubspot) stopped working. I think I had version 2.5.1 before and it was working fine. With the version 2.6.1 the problem persists. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.6.1
| PHP version | 5.6.27

### Steps to reproduce:
1. Setup Hubspot plugin with API etc
2. Create a campaign that saves contact to Hubspot.
3. Add new contact to the campaign.
 
### Log errors: 

[2017-02-23 12:33:03] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\DBALException: "LIMIT argument offset=-25 is not valid" at /home/user/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php line 3318 {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): LIMIT argument offset=-25 is not valid at /home/user/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:3318)"} []

**Comment by Psusi1** [comment]
I have same issue using Mautic Cloud - raised to support teams separately. Seems to remain an issue on 2.7.0.

In case this is useful - I've noticed the "Pull from integration" function works for me as contacts created/updated in Hubspot appear in Mautic. The "Push" is where it fails. I've tried with a separate clean Hubspot instance as well to check if at their end but still no success.

**Comment by escopecz** [comment]
@Psusi1 The Hubspot integration have only Push implemented. Pull is still waiting for implementation.

@ahfauth since Push is working for @Psusi1, could it be some problem in configuration? The error message you've posted was fixed in 2.7.0, but it was not related to Hubspot.

**Comment by Psusi1** [comment]
@escopecz Push isn't working for me.

**Comment by escopecz** [comment]
Ah, the other way around. Sorry. I honestly didn't know pull works. I'll mark this as a bug then.

**Comment by studiogt** [comment]
Hello @escopecz,
I'm new here and I'd like to know if someone found a way to pull the contacts to the hubspot.
Thanks in advance.

**Comment by rodrideme** [comment]
@studiogt For now I am sending the contact using the field BCC. Each hubspot account has a special email where hubspot insert automatically the email in contact

![screenshot_24](https://cloud.githubusercontent.com/assets/3418370/24061104/dbd3d930-0b34-11e7-9aea-c3330fc65f21.png)

![screenshot_23](https://cloud.githubusercontent.com/assets/3418370/24061060/af0b4b68-0b34-11e7-847b-d345e1078867.png)

**Comment by mcneela86** [comment]
This is still an issue in 2.7.1

Can we sue webhooks to send data to HubSpot?

@studiogt Can you explain more on how your method works? I have managed to create contacts but only get 'First Name, 'Last Name' and 'Email' passed to HubSpot.

**Comment by luizeof** [comment]
I have found this log:

[2017-04-27 11:00:10] mautic.NOTICE: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function mergeConfigToFeatureSettings() on boolean (uncaught exception) at /var/www/mkt.powertic.com.br/htdocs/app/bundles/PluginBundle/Command/FetchLeadsCommand.php line 98 while running console command `mautic:integration:fetchleads` [] []

@escopecz @kuzmany @alanhartless @mqueme

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/4184
