### ISSUE TITLE
Incorrect title set when paginating within contact history

### ISSUE THREAD

**Issue by scottbuscemi** [mautic/mautic#3513]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When viewing page 2+ within the history of a contact, the `<title>` is being set to an HTML string rather than the contact's information

![screen shot 2017-02-23 at 3 56 51 pm](https://cloud.githubusercontent.com/assets/4336848/23284486/b44ee8ec-f9e0-11e6-848c-120f60c1584e.png)

`<title>&lt;div class="pull-left mt-5"&gt;&lt;span class="span-block"&gt;IP ADDRESS&lt;/span&gt;&lt;span class="span-block small ml-sm"&gt;&lt;/span&gt;&lt;/div&gt; | Mautic</title>`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 7.0.16

### Steps to reproduce:
1. Go to a contact
2. Press the second (or higher) page of navigation

**Comment by npracht** [comment]
Please test https://github.com/mautic/mautic/pull/4623
