### ISSUE TITLE
UTM tag for all link sent from mautic

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3516]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | x

## Description
It would be awesome that all the links sent through channels (emails/sms/etc.) automatically include UTM, then you don't need to set it up manually each time.

### Suggestion
Add in the configuration panel UTM settings, one input by marketing channel where you can store UTMs.
When mautic send email for instances. It add automatically UTMs set in the configuration panel.

I think @mqueme that's not so far from what you already worked on :)

**Comment by merlin0** [comment]
I think kurzmany already made a plugin for this? 
Not sure if it still works.
https://github.com/kuzmany/MauticAnalyticsTaggingBundle

**Comment by npracht** [comment]
then @kuzmany would you consider PR your plugin to mautic ?

**Comment by kuzmany** [comment]
No. There is a feature request https://github.com/mautic/mautic/issues/3106 but should be donate by community :) 

https://www.bountysource.com/issues/40092771-google-analytics-support-for-emails?show_profile_modal=1
