### ISSUE TITLE
SugarCRM - Bi-directionnal sync

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3517]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | x

# Features in mautic plugin
## “Push contact to integration”
Ability to push contacts from Mautic to Sugar at the following events. This feature is existing in CRM bundle.
* Form action
* Trigger action
* Campaign action
That allow the user to choose when the contact should be synced to the CRM.

## “Full sync.” mode
Use a CRON to push all contacts created or modified since last CRON without any other condition.

## “Fetch from CRM”
Ability to fetch from multiple object in SugarCRM. This should be manageable from the plugin config.
* Leads
* Contacts
* Companies
* Segments
It fetches all the items based on last modify date and date of last fetch CRON

### First fetch
For the first fetch, it should take all data in the CRM for the selected CRM objects.

## Contact field mapping
Contact field mapping to match leads/contacts fields from CRM to mautic contact fields.

### Writing rules
It would be great to add some rights on the data sync. to be able to choose **for each field**.
* Mautic erase in CRM (by default)
* Mautic erase only if empty
* Mautic never erase

## Company field mapping
Company field mapping to match company from CRM to mautic company fields.

### Writing rules
Same as contact.

## SugarCRM plugin feature
Install on each contact a modal that displays the contact timeline from mautic.

____

@escopecz you can assign that to me please, we're almost done :)

**Comment by ninjoan** [comment]
cool!!!
