### ISSUE TITLE
A/B Test Stats not showing anything

### ISSUE THREAD

**Issue by rucksman** [mautic/mautic#3520]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
After setting up and sending out an A/B test there are no usable stats, neither for the email variants itself nor under "A/B Test Stats".

Graph for the parent version (the sample was 1.000, 50% for parent, 50% for variant):
![grafik](https://cloud.githubusercontent.com/assets/24551016/23309975/0b6ba1a8-fab1-11e6-80fb-8cfcead2dad6.png)

Graph for variant:
![grafik](https://cloud.githubusercontent.com/assets/24551016/23309994/262fb196-fab1-11e6-943f-5e6146ce9f81.png)

Graph "A/B Test Stats":
![grafik](https://cloud.githubusercontent.com/assets/24551016/23310145/c4a04f5c-fab1-11e6-856f-270f867a1ae4.png)

Counting read emails in the database directly shows plausible results.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 5.6.23

### Steps to reproduce:
1. Set up an A/B Test
2. Check stats

**Comment by iadj** [comment]
I noticed there's a character escaping bug where double parantheses `"` return a javascript error when trying to use A/B testing. This might be the issue.

**Comment by npracht** [comment]
Please test https://github.com/mautic/mautic/pull/4456
