### ISSUE TITLE
Often extremely slow response times in dashboard for URLs & API.

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#3523]
I'm having a recurring issue with Mautic, where loading the dashboard, or making an API call is often taking an exceptionally long time. Sometimes it loads quickly, other times it takes well over a minute.

 It takes such a long time that the API calls often time out in production. I have a feeling this could be because of a threading issue with Mautic. I'm using a standard Google Compute Engine server with plenty of CPU & RAM.

I currently have to make a workaround (a CRON job that works to add emails to Mautic), since direct API calls are currently too slow and unreliable.

**Comment by wittwerch** [comment]
The default dashboard has some widgets that results in some poorly optimised MySQL queries. If your dataset is large these queries can easily take up to >10s which results in timeouts.

Example:
# Query_time: 16.420835  Lock_time: 0.000068 Rows_sent: 3  Rows_examined: 2426566
SET timestamp=1487836937;
SELECT a0_.user_name AS user_name_0, a0_.user_id AS user_id_1, a0_.bundle AS bundle_2, a0_.object AS object_3, a0_.object_id AS object_id_4, a0_.action AS action_5, a0_.details AS details_6, a0_.date_added AS date_added_7, a0_.ip_address AS ip_address_8 FROM audit_log a0_ WHERE a0_.object <> 'category' ORDER BY a0_.date_added DESC LIMIT 3;

That's the query that loads the "Recent activity" widget. It needs to scan ~2.5 mio records to the last 3 activities. We are currently trying to optimise that and we will share the results of course with the community.

**Comment by escopecz** [comment]
@iadj could you be more specific about the API calls? For example what API call is so slow for you? How many rows do you have in the table you are requesting/updating/inserting records to? How many rows do do you request/updatge/insert per one call?

**Comment by escopecz** [comment]
@iadj please test if #3580 fixed your issue.
