### ISSUE TITLE
Forms don't allow for removed fields to be re-entered afterwards

### ISSUE THREAD

**Issue by igorA53** [mautic/mautic#3525]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Components > forms: if you make a form with pre-defined field values (select, radio group, checkbox group) and you make an error, so remove that particular field from the form, there is no way to add the field again afterwards.  It looks like there's a build-in check for duplicates, which is good. But it should clear the use after the field was removed from the form so you can add it again. 

I encountered the error a few times because I saw I made a typo in the name, which becomes the system alias.  So to fix this, I removed the filed and wanted to add it again at a later stage.  Then you get the error.

## If a bug:
| Q   | A
| --- | ---
| Mautic version | Cloud - free version
| PHP version | 

### Steps to reproduce:
1. inserted a core-contact-field with pre-filled values as radiogroup, checkboxgroup or select
2. removed the field
3. try to re-inserted the same core-field > **error**
 
### Log errors: 
there's no way to look at the logs in the Mautic Cloud version I suppose

**Comment by escopecz** [comment]
I cannot replicate. Adding and removing a select field with the same name and options, delete it, create it again creates the field and I can save the form without any error. I also tried the same with saving after creating the field and that worked too. Anything speciffic I have to do?

**Comment by igorA53** [comment]
John,

I've been testing it more extensively now and there still is an error, but for another reason.
1.) I made a new custom field as such:



2.) then I tried to add it to a new standalone form, but it gave me this error:



3.) but the reason is because I didn't make any choice in tab 'Properties': so not selecting the contact's field list choices nor manually added list items.

Sorry I made this mistake.
On the other hand I think it's best that the system tells my the "properties" are required in this case.

regards,
Igor

	 	igor Foerier
oude luikerbaan 53, 3500 hasselt, belgium
www.atelier53.be  .   www.linkedin.com/in/igorfoerier


Op 27 februari 2017 bij 17:06:13, John Linhart (notifications@github.com) schreef:

I cannot replicate. Adding and removing a select field with the same name and options, delete it, create it again creates the field and I can save the form without any error. I also tried the same with saving after creating the field and that worked too. Anything speciffic I have to do?

**Comment by escopecz** [comment]
Thanks for getting back to me. But could you please write a clear steps to recreate? I'm not sure I'm following.

**Comment by igorA53** [comment]
no problem: forget what I initially said about re-use of a field.  In fact it is much simpler then that.

Steps to reproduce:
1. create a standalone form (haven't tested with a campaign form)
2. add a field of type "select", "checkbox group", "radio group"  and link it to a core Contact field which has pre-populated values: I had the error with custom fields I made, but I see no that fi. the country field triggers the same error.
3. while adding the field do NOT assign the contact field list choices or manual values values in tab "properties".  Even though the optionlist has a red required wildcard-sign, it is not properly tested and this triggers the error.

**Comment by RCheesley** [comment]
Unable to replicate following instructions above in 2.16.1 so closing this issue down.
