### ISSUE TITLE
Links in emails should be auto converted to Mautic clickthroughs rather than requiring the {externallink} token

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#353]
Currently, in order to have a link converted into a clickthrough where Mautic can track what lead clicked a link from an email, you have to use the {externallink=URL} token.  That token will generate a Mautic redirect URL for the remote URL and append tracking information ensuring the lead associated with the email is given credit for clicking the link.  Otherwise, the link is just a raw URL and even with a tracking pixel, Mautic doesn't know who clicked the link unless the lead happened to be browsing from an IP address that is already associated with the lead in Mautic.  

External (non-Mautic) links should be auto converted so the user doesn't have to remember to use the external link token.

Also, clicks throughs should be displayed as stats per email and not just accumulative in the landing page stats.

**Comment by RCheesley** [comment]
Yes please, this will make it much easier for end-users!

**Comment by RCheesley** [comment]
Just noticed the external link button in email builder doesn't seem to work: https://github.com/mautic/mautic/issues/389
