### ISSUE TITLE
bug - cannot delete multiple result on form results

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3534]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When you display results of a form, you can remove (delete) submissions. Obviously, delete multiple results at once fails.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6
| PHP version | 

### Steps to reproduce:
1. Create a standalone form
2. Submit several times
3. Display results
4. Check more than one result
5. Click "delete results" (all at once)
6. Nothing happens.

**Comment by escopecz** [comment]
Works for me. 2.6.0 or 2.6.1? Any error anywere?

**Comment by npracht** [comment]
Hi @escopecz, my mistake it was a 2.5.0 but it seems corrected after new tests.
Thanks for that.

N.
