### ISSUE TITLE
Contact monitoring on non-Mautic landing page by following an email link

### ISSUE THREAD

**Issue by vkathirvel** [mautic/mautic#3535]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | V
| Enhancement? | 

## Description:
Currently in another bespoke CRM system I have a feature and I was wondering if Mautic had the same?

1) I tag all email links using the contact's identifier field - e.g. UUID or ID. This is usually added as a query string at the end of the link.
2) On the website (on all pages), I have a JS code that looks out for the query key and then picks the value and matches it up with the contact's ID.
3) This way, I know who the contact is and can reconnect their session even if they went on a totally different device.

Does Mautic automatically tag links inside emails to do something similar?

I have figured a way to do this in Mautic. I can tag links with the user's email address. On the website, I can catch the email address and append it to the mt send pageview call. I'm wondering if there's a graceful way to handle this?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by vkathirvel** [comment]
I can see someone explaining a hack that I am currently doing - https://www.mautic.org/community/index.php/1255-email-url-tracking/0

My concern is the revelation of email addresses in the URL. It could spook the recipient. Can there not be a UUID generated for each user and automatically used as part of the tracking code?

**Comment by kuzmany** [comment]
Maybe this help https://github.com/mautic/mautic/issues/3524#event-977952288

**Comment by vkathirvel** [comment]
@kuzmany Thanks for pointing me to the other thread. Exactly, I am using that hack! It is still a hack. I am hoping that tracking URLs can be introduced in emails as standard.

A sample concept would be this:
1) All links in the email are converted or tagged with a unique id for the recipient. This UUID shouldn't be their mautic contact id, but a more complex UUID - just to make it a lot more secure? You don't want spammers to start tampering with data by passing standard mautic contact ids that are incremental.

2) The JS code in landing pages to be modified to look out for the UUID and match up the contact. This way, when someone comes to the website through an email link, they are automatically tracked and matched up without using a workaround.

**Comment by mrerich** [comment]
Nice idea. Is it coming soon?

**Comment by dbhurley** [comment]
This is not something currently on the roadmap, but if a PR is submitted happy to reopen and link this.
