### ISSUE TITLE
Custom Focus content [CLOSE]

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#3537]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
The more details the better...

Hi i was thinking it will be great to have the option to insert custom content for Focus items. For sample create, you own Design using HTML, be displayed in the differents Focus option. To try to get a Focus popup that blends with the website design.

**Comment by npracht** [comment]
Is that answering your need ? https://github.com/mautic/mautic/pull/3460

**Comment by ninjoan** [comment]
Ohh yes!
https://github.com/mautic/mautic/pull/3460
