### ISSUE TITLE
[Feature] Email Reply Setting on Form Submission Email Notification

### ISSUE THREAD

**Issue by MaxOnTheHill** [mautic/mautic#354]
In the form settings:
"Currently we're using _Send form results_ in the _Actions_ tab to setup sending submission to admin email.
We could not find any where to configure the _reply-to address_” , 
so that when the client clicks _reply_ from a form submission notification email it will reply to the email of the form submitter.

Currently no setting for this in core, but would be great to have that there :)

**Comment by alanhartless** [comment]
This was fixed in 1.2 so that the client clicking reply would go to the lead that submitted.  But if a copy was sent to the lead, clicking reply would go back to Mautic's configured from address.
