### ISSUE TITLE
[Enhancement] Not Count Known Bots as Anonymous Visitors

### ISSUE THREAD

**Issue by j-ki** [mautic/mautic#3541]
What type of report is this: | Enhancement | 

## Description:
For some reason, the people at Automattic are hitting: /index.php/media/images/avatar.png

Every time they browse for this image, it creates an anonymous contact. I have hundreds of them.

Would it be possible to filter out known bot traffic and not create contacts for them?

Or maybe we can whitelist certain images (e.g. tracking pixels) and not count images as anonymous contacts?

### Steps to reproduce:
1. Install Mautic.
2. Leave it running for a few days.

**Comment by escopecz** [comment]
I think there is already a PR for this. Would you mind testing it?

https://github.com/mautic/mautic/pull/3501
