### ISSUE TITLE
[Enhancement] Fix URL Shortening Tooltip for Bitly.com

### ISSUE THREAD

**Issue by j-ki** [mautic/mautic#3542]
What type of report is this: | Enhancement |

## Description:
In the tooltip for URL shorteners, it gives an example of Bitly shortened link:

https://api-ssl.bitly.com/v3/shorten?access_token=[ACCESS_TOKEN]&format=txt&longurl=

However, that last parameter, 'longurl' is incorrect. It should be 'longUrl' (with a capital 'U').

It will not work, if it's not capitalize properly (at least in my testing).

Currently, the tooltip is the only source of documentation for URL shortening. Maybe someone can go in and correct the parameter.

**Comment by escopecz** [comment]
Thanks for pointing that out! Please see https://github.com/mautic/mautic/pull/3544 and comment on it if it's fixed there.

**Comment by j-ki** [comment]
It's a really easy fix. I saw the change, it was correct, and approved it. But I'm not an approved reviewer, =).
