### ISSUE TITLE
Unable to add contacts in Segments

### ISSUE THREAD

**Issue by amitkumarji** [mautic/mautic#3545]
What type of report is this:
@escopecz 
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I have created a segment "First segment" and then try to add contacts through, Quick add and New contact. None of the detail saved in the segment. But when I used the import option, then it's worked. Contact save in the segment.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 5.6

### Steps to reproduce:
1. Create a New Segment
2.  Add a contact in Segment and save.
 
No error logs.

**Comment by escopecz** [comment]
It's not possible to add a contact to a segment through "Quick add" nor "New contact" form. You can add them to contact via Preference center. Could you make a screenshot of how were you adding the contacts to the segment?

**Comment by amitkumarji** [comment]
Here is the image: https://image.ibb.co/eSM4aa/segment.jpg

**Comment by escopecz** [comment]
This will filter contacts which belong to a segment. It won't put all contact created to the segment when this segment is filtered.

To do that, you can either do it via the Preference center in the contact detail page or by selecting the contacts in the contacts table and adding them all to a segment via batch option.

**Comment by amitkumarji** [comment]
got it. thank you so much for the fast support :). and quick fixes .
