### ISSUE TITLE
Unable to Apply pre-defined Dashboard (SOLVED)

### ISSUE THREAD

**Issue by amitkumarji** [mautic/mautic#3548]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I have reinstalled the Mautic, now I am facing this issue.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 5.6

### Steps to reproduce:
1. 
2. 
 
### Log errors: 
Please check the image
https://image.ibb.co/gFrbov/dashboard.jpg
![dashboard](https://cloud.githubusercontent.com/assets/25746483/23405767/d4c5a37c-fde1-11e6-9c90-fe51e5916f21.jpg)

**Comment by escopecz** [comment]
I cannot replicate the issue. Works on my Mautic 2.6.1. Anything special to do to replicate?

**Comment by MxyzptlkFishStix** [comment]
Make sure media/dashboards and the files inside are writable by the web server user.

**Comment by amitkumarji** [comment]
Nope. I reinstalled the mautic. In the night and config it in the morning.
and then I notice this issue.

Is there anything, folder etc where i can give extra permission for this or any SQL query to fix this issue?

**Comment by amitkumarji** [comment]
Solved..

Revert back to 2.6.0 and then again upgrade the mautic to 2.6.1 version. I think few things were left behind.

**Comment by knowrick** [comment]
Here is the command to make the directory writable.

chmod -R g+w media/dashboards/

**Comment by davifo** [comment]
Perfect knowrick!
