### ISSUE TITLE
Cannot make Mautic work on SSL

### ISSUE THREAD

**Issue by munjalpatel** [mautic/mautic#355]
Hello,

I get this error when I try to access Mautic using https:

The requested URL /s/dashboard was not found on this server.

**Comment by munjalpatel** [comment]
I was missing .htaccess -- well, the downloaded .zip was missing .htaccess in it.

**Comment by superainovacoes** [comment]
Hi, i have the same problem, are you using this .htaccess https://raw.githubusercontent.com/mautic/mautic/staging/.htaccess ?
