### ISSUE TITLE
Focus Items in Campaign

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#3551]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | 

## Description:
The more details the better...
Hello guys what do you think about include Focus items in a campaign.
Here is the idea create a segment with only visitor to use Focus Items to appear only in visitor that don't fill any form in Mautic to try to convert that visitor into leads

**Comment by TomRoethlisberger** [comment]
I would propose a focus item action that can be used within the campaign.
