### ISSUE TITLE
URL Shortening Skipping Mautic Tokens

### ISSUE THREAD

**Issue by j-ki** [mautic/mautic#3552]
| Bug report | 

## Description:
When I have a URL in a text message that includes a token, the entire link isn't sent to the URL shortening service. For example, this text message:

'Hi, check this out: http://example.com/?id=23&utm=mautic&email={contactfield=email}.'

would look like:

'Hi, check this out: http://bit.ly/XXXX&email=foo@foo.com'.

(Plus, the link isn't genuinely shortened. Although the linking service returns a shortened URL, it doesn't work.)

I suspect the token is being parsed after the link is sent to the shortening service. Or something to that effect.

EDIT 1: There seems to be another bug that I think is related to this issue. I'll post this here but if it's a separate bug, please let me know and I'll open another issue.

When I end a sentence with a URL (e.g. "Check out this link: https://example.com/this-link/."), I found that the parsing tries to include the ending period and shortens the link to "https://example.com.", which raises all types of root domain/FQDN issues.

I had to make sure not to end sentences with the URL in SMS to make sure everything worked.

## If a bug:

| Mautic version 2.6.1 | 
| PHP version 7.0 | 

### Steps to reproduce:
1. Configure a URL shortening service.
2. Write a text message that includes a link that has a token (e.g. {contactfield=email}).
3. Create test campaign
4. Create test user
5. Send test SMS.
 
### Log errors: 

[2017-03-01 05:33:12] mautic.ERROR: Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "mautic__contacts" as such route does not exist. - in file /var/www/dev.xxxx.com/app/cache/prod/appProdProjectContainerUrlGenerator.php - at line 200 [] []

**Comment by j-ki** [comment]
There may be more to this issue. I tried putting a URL with just parameters (with no tokens) and similarly to above, although the link shortening service returns a value, the short link doesn't actually work.

When I manually URL encode the link and use their GET API, I receive a working link.

I don't know how Mautic sends the URL to the link shortening service but if it's not being URL encoded, it really needs to be before being sent to the linking service.

**Comment by j-ki** [comment]
Is there any chance this issue will make it to the 2.8.0 milestone?

**Comment by isleshocky77** [comment]
I haven't dug into this Bug to see it's cause; but is it possible that it's related to #3825?

**Comment by npracht** [comment]
Fixed by https://github.com/mautic/mautic/pull/6260
