### ISSUE TITLE
Issue after upgrade

### ISSUE THREAD

**Issue by first10dev** [mautic/mautic#3555]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | no 
| Enhancement? | no

## Description:
I've just tried upgrading to 2.6.1 from 2.4 using composer and I'm now getting the following error message when trying to clear the cache.
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  The child node "own" at path "light_saml_symfony_bridge" must be configured.
```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 5.6

### Steps to reproduce:
1. Copy files from 2.6.1 over the 2.4 installation
2. run composer 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
> Copy files from 2.6.1 over the 2.4 installation

That is not how the upgrades proccess should look like. Either use the Mautic's upgrade commands / upgrade.php script / upgrade web UI (for small databases) or use `git pull` if you want to take care of the composer updates yourself.

**Comment by escopecz** [comment]
Owerwriting the files is not the same as `git pull`. Overwriting doesn't care about moved or deleted files. I'd suggest to host Mautic at some decent hosting or even better, some VPS so you could use supported methods of upgrading Mautic.

**Comment by first10dev** [comment]
Thanks for the help
