### ISSUE TITLE
Modifications to Marketing Message channels don't commit after being first created

### ISSUE THREAD

**Issue by J-a-n-u-s** [mautic/mautic#3559]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When creating a marketing message I enable email and pick the mail message. After saving it, if I go back and try to change the email selection to send or disable email (using email as an example, but same for twitter and I imagine others), then save, the changes don't commit. Going back in, nothing has changed since instantiation. FYI the marketing message hasn't been linked to anything else e.g. a campaign.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | PHP Version 7.0.15-0ubuntu0.16.04.2

### Steps to reproduce:
1. Create a Marketing Message and save it
2. Open it up again, and toggle a method / change email to send or something
3. Save it
4. Reopen and see if change was saved
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dongilbert** [comment]
fixed in #3634 - thanks for the report!
