### ISSUE TITLE
Reports display html escaped characters

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3565]
| Q  | A
| ---| ---
| Bug report? | ✔️ 
| Feature request? | 
| Enhancement? | 

## Description:

Reports display escaped characters

![image](https://cloud.githubusercontent.com/assets/18265735/23548161/76c8fffe-0006-11e7-8cec-fd5d1abf1071.png)
![image](https://cloud.githubusercontent.com/assets/18265735/23548175/809cf846-0006-11e7-8337-63e2886b0bbf.png)
![image](https://cloud.githubusercontent.com/assets/18265735/23548200/9f22dc7c-0006-11e7-998a-8e00a9a3bb02.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 7.0.15

### Steps to reproduce:
1. Create a contact with the name `&`
2. Create a contact report with names displayed
3. Notice the escaped character
4. Export as a CSV
5. Notice the doubly escaped character

**Comment by escopecz** [comment]
Fixed by you at https://github.com/mautic/mautic/pull/4088 :)
