### ISSUE TITLE
[2.6.1] Translation - french language is not working

### ISSUE THREAD

**Issue by captivea** [mautic/mautic#3568]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Go in user profil and switch to Czech language > ok screens are now display with cezech language
Do the same with French language > strnigs are back in english

On file system there's a folder fr in translations but it seems not to be used by Mautic.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 7.0.12

### Steps to reproduce:
see at the top of the report

**Comment by escopecz** [comment]
I think it has something to do with `PHP Warning - syntax error, unexpected ')' in /Users/jan/dev/mautic/translations/fr/SmsBundle/messages.ini on line 29`. That file has missing `""` on many places. Can someone try to fix it at Transifex?

**Comment by captivea** [comment]
I asked for months that my transiflex account got reviewer rights as i can't edit already translated strings. can you help ?

My account : yannick.biet@captivea.fr

**Comment by escopecz** [comment]
Try now

**Comment by captivea** [comment]
Thanks a lot :)

I have to retranslate all strings with ' characters using \' like any other language we're right ? (to escape the ' character )

**Comment by captivea** [comment]
can we do that in mass ? (like download/replace and then reupload the file ?)

**Comment by escopecz** [comment]
No, the translation must be in double quotes (`"`) and you can use single quotes inside the translation as you want. The corrupted file doesn't have the double quotes at many rows, so that must be fixed.

**Comment by captivea** [comment]
oh you gave me rights only on the sms bunddle, but there's ' characters inside all modules, how can i fix that ? can you enable me the rights on the whole translation ?

**Comment by captivea** [comment]
ok sorry i have done that too quickly reverting.

**Comment by captivea** [comment]
revert done 

John, i don't see any double quotes inside the module translated.
can you point me out what kind of error it is ?

**Comment by escopecz** [comment]
Are you able to download the file for translation, fix the double quotes there and upload it again?
![screen shot 2017-03-03 at 17 54 24](https://cloud.githubusercontent.com/assets/1235442/23560387/8f795984-003a-11e7-9a22-3e1d23c02124.png)

**Comment by captivea** [comment]
so just to be sure as i alrady double check i download the messages from smsbundle ?
![capture](https://cloud.githubusercontent.com/assets/25105233/23560545/20e68fae-003b-11e7-8290-f6ab2c093d26.PNG)

**Comment by captivea** [comment]
I don't see any " missing in the .ini file
[for_translation_mautic_smsbundle-messages_fr.txt](https://github.com/mautic/mautic/files/817366/for_translation_mautic_smsbundle-messages_fr.txt)

**Comment by captivea** [comment]
John, line 29 is
mautic.sms.form.action.sendsms.admin="Envoyer un SMS à l'utilisateur"

I don't see any problem with " characters there

**Comment by escopecz** [comment]
I see. I saw the problem in my local, which could have some old version of the file.

**Comment by captivea** [comment]
i have deleted cache/prod and translations on my own
i don't have any log inside any stsem file nor in mautic log

**Comment by npracht** [comment]
@escopecz i think the issue is over. We corrected some time ago something together on Transifex + recently MaxWebmecanik changed some unescaped strings that generated issues.

**Comment by YannickBiet** [comment]
I confirm that 2.8.0 can display French language, but builder is still KO

**Comment by npracht** [comment]
@YannickBiet apply this PR and you'll see :) 
https://github.com/mautic/mautic/pull/3874

**Comment by YannickBiet** [comment]
Merci Norman, j'ai vu que tu avais fais la PR apres ma note

**Comment by Dt-Sodium** [comment]
Hello,
I can't get the system to translate in french on a fresh install from today.
Any other language i've tested seems to work. When i select french, it switches back to english.
The translation files seem to have been downloaded.
