### ISSUE TITLE
Not able to create Anonymous Contact with IP Address in Name field.

### ISSUE THREAD

**Issue by nishashah87** [mautic/mautic#3576]
My problem is when anonymous contact is created in mautic in name field it shows "Anonymous" as name rather than IP. i want to track IP for anonymous user. I have read in forum that default lead form should have ip address as name. but that's not case for me. Can someone tell me is there any setting or code i need to modify?

What i have done is taken script from mautic landing page setting and put in my page before </body? tag. I can not see any default form or option to change that.
![anonymous](https://cloud.githubusercontent.com/assets/21097095/23569148/c0f3dc64-0012-11e7-8a97-927f23a34f88.png)

Please check attached screenshot for more detail. Any help will be really appreciated.

**Comment by escopecz** [comment]
The IP is tracked, but it's not displayed anywhere in the UI. It is possible to search for contacts with specific IP though. So is your request to show the IP instead/before/after the "Anonymous" text in the name column? Or is it enough to show the IP(s) in the contact's detail?

**Comment by nishashah87** [comment]
yeah i want to show ip as name for anonymous user. our marketing people wants to know ip for anonymous user. We also have one other site on which we are using mautic for tracking, in that account it shows ip by default for anonymous users. i am not sure is there any setting or why it's different in both account? you can check attached screenshot from our other account for your reference.
![mautic](https://cloud.githubusercontent.com/assets/21097095/23618367/00497660-0245-11e7-86b6-6f0ce9302b09.png)

**Comment by nishashah87** [comment]
Anyone have solution for my above problem? If so please help me. We have to launch our site next week with mautic tracking and our marketing people wants to see IP Address for all anonymous leads. so it's really urgent and very important for us.
