### ISSUE TITLE
Contacts, Companies - 500 error

### ISSUE THREAD

**Issue by Ashwini0416** [mautic/mautic#3579]
After upgrading to 2.6.1 , opening contacts, companies it displays 500 error

**Comment by escopecz** [comment]
Please see https://mautic.org/docs/en/tips/troubleshooting.html and next time please fill in the issue template and answer all the questions. It'll help a lot to fix your issue faster.

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to come with some updates anytime and I'll reopen this issue.
