### ISSUE TITLE
Editing button after link in builder modifies both button and link

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3584]
| Q  | A
| ---| ---
| Bug report? | ✔️ 
| Feature request? | 
| Enhancement? | 

## Description:

Editing a button will also modify all the links of all zones that were previously selected since the last click outside of any slot

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 7.0.15

### Steps to reproduce:

[Watch screencast](https://youtu.be/HEeMQhGLcHk)
(I press enter just before the link changes)

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/3585, will be in 2.7.0
