### ISSUE TITLE
URL custom field runs through FILTER_SANITIZE_SPECIAL_CHARS filter in InputHelper, breaking links

### ISSUE THREAD

**Issue by maxSupermoney** [mautic/mautic#3599]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When a custom field is saved, InputHelper scrubs the data. If the field is a type text, the clean function filters using FILTER_SANITIZE_SPECIAL_CHARS. This is good for text, but bad for URLs. ampersands in URLs get converted to &amp;#38; eg
http://localhost/index.php?a=b&c=d becomes http://localhost/index.php?a=b&#38;c=d

If the URL is used in an email, the email uses the encoded link, which can cause problems at the destination.

The InputHelper url method uses the FILTER_SANITIZE_URL filter, which works without any unnecessary encoding, but the field runs through the clean function anyway so it encodes the URL regardless. I believe CleanFormSubscriber runs every field through the clean function regardless of the field type.

I've seen come code that converts &amp;amp; back to a regular ampersand, but &amp;#38; is not included

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.0
| PHP version | 7.0.14

### Steps to reproduce:
1. Create a custom field with type URL called customURL
2. Edit a user and add a URL containing an ampersand to customURL, like https://www.google.com/#q=mautic&*
3. Create an email with a link to the URL custom field in an anchor tag <a href="{contactfield=customURL}">{contactfield=customURL}</a>
4. Send the email to the user
5. Click on the link. It takes you to the encoded version of the URL instead of the unencoded
https://www.google.com/#q=mautic&#39;* instead of https://www.google.com/#q=mautic&*
 
### Log errors: 

None

**Comment by escopecz** [comment]
Would you be able to send a PR with the fix? It seems you're good with code.

**Comment by pardeepolicyx** [comment]
Same issue with me. I am sending a link in email is not working and it is adding #38; in the url

**Comment by maxSupermoney** [comment]
I wouldn't mind making a fix, I'm just not sure where is the most appropriate. What would you suggest? 

As a temporary fix, in the clean function I checked the string for the http protocol and didn't use the special chars filter, but that seems rather hacky. I'm not familiar enough with the Mautic code to make an upstream fix before or as it gets filtered. Adding a &amp;#39; to the &amp;amp; replacement would be easy.
