### ISSUE TITLE
Resubscribe link gives 500 Error when using an email with + in the mailaddress 

### ISSUE THREAD

**Issue by senoltapirdamaz** [mautic/mautic#3601]
What type of report is this:
| Bug report? | 

## Description:
When using the {unsubscribe_text} in an email. 

I've send an email to a gmail alias:  firstnamelastname+1234test@gmail.com
When I click the unsubscribe link the lead gets unsubscribed and sent to the resubscribe url
When this lead clicks the resubscribe link he gets a 500 Error. 

I've tested the same steps with an email not containing a + 
the unsubscribe-resubscribe works fine then. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1.  Set unsubscribe en resubscribe in email settings in Mautic
2. Create an email with {unsubscribe_text} in it
3. Create a lead with an gmail address with a + in the mail address
4. Send email to lead with an email address (preferably a gmail address with a + in it)
5. Let lead unsubscribe, the text in the webpage would appear with succesfull unsubscribed if this was a mistake click here.
6. Click that link (resubscribe)
7. 500 error appears. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
Closing due to lack of recent activity, if still a bug please request re-opening!
