### ISSUE TITLE
Allow to add cc Email in Send Email Action of a campaign

### ISSUE THREAD

**Issue by miguelaguero** [mautic/mautic#3609]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | n
| Feature request? | y
| Enhancement? | n

## Description:
Sometimes it is needed to add a C.C. Email when a Send Email action is trigered into a Campaign. 

A good example is that as an administrator, I want to receive a copy of the original Email received by the user that received the email. 

Another example is that I want to send a copy of the Email to our internal employees when is somebody birthday or anniversary.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Any
| PHP version | Any

### Steps to reproduce:
1. Login
2. Go go Campaigns
3. New Button (To create a New campaign
4. Open Campaign Builder (Click on Campaign Builder Button
5. Select any Contact source
6. Select Actions / Send Email Action

![campaign email](https://cloud.githubusercontent.com/assets/655910/23721288/36ceb2ce-040f-11e7-8e83-f1044575c91a.png)

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Can the CC and BCC in the configuration of the specific email be used instead?

**Comment by miguelaguero** [comment]
It is already implemented. BCC copy is implemented in the Email
