### ISSUE TITLE
Segments not Updating Based on Tags Filter

### ISSUE THREAD

**Issue by tathspts** [mautic/mautic#3610]
Hi I am trying to segment contacts based on tags I assigned to them. But every time I create a segments and set a tag filter to it, segment does not update with contacts in it. I have checked all contacts have tags that I am trying to use. I wonder why is this happening?

**Comment by escopecz** [comment]
Please provide all the information you can and next time, fill in all the answers to the issue template. What Mautic version are we talking about? What PHP version? What operators were not working?

**Comment by tathspts** [comment]
Sorry, Mautic version is 2.7 and I have tried it on both php 7 and 5.6.30, every time I create segment based on tag filter, segments says no contacts. I have tried it on mautic's cloud instance and it is working perfectly fine there. This issue seems to be coming only on self hosted version.

Basically I have imported some contacts those have a "prospects" tag on them. Now I got to segment section and create a segment named prospects and go to filters and select where tags contain "prospects". It just wont group them at all. Keeps saying 0 contacts.

**Comment by escopecz** [comment]
I know this is silly question, but I have to ask. The [cron jobs](https://mautic.org/docs/en/setup/getting_started.html) are configured correctly?

Are other segment filters working fine?

Do you see any errors in the [log](https://mautic.org/docs/en/tips/troubleshooting.html)?

**Comment by tathspts** [comment]
Hi Yes cron jobs are setup right. Please see the attached screenshot.

None of the segment filters seems to be working right.

There are no error logs in logs folder.

<img width="1216" alt="cron jobs" src="https://cloud.githubusercontent.com/assets/22551552/23807006/fa690f4e-0591-11e7-9f25-969b1f200beb.png">

**Comment by escopecz** [comment]
The `Too many arguments, expected arguments "command"` errors would suggest that your cron job commands are not executed. Try to search around why is that. For example try this:

http://stackoverflow.com/questions/41974922/laravel-too-many-arguments-expected-arguments-command-while-scheduling

I'll close this issue since it's related to your server/cron configuration.

**Comment by tathspts** [comment]
cron job is not the problem here, like I said other server doesn't even have any error logs.

**Comment by tathspts** [comment]
Hi Seems like cron job is running but I see this error in logs.

mautic.NOTICE: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: No such file or directory (uncaught exception) at /home/mauticte/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 while running console command `mautic:segments:update` []

Its always giving this output

Rebuilding contacts for segment 2
0 total contact(s) to be added in batches of 300
0 total contact(s) to be removed in batches of 300
0 contact(s) affected

X-Powered-By: PHP/5.6.30
Content-type: text/html; charset=UTF-8

**Comment by escopecz** [comment]
Try the suggestion in http://stackoverflow.com/questions/6259424/troubleshooting-no-such-file-or-directory-when-running-php-app-console-doctri

**Comment by suriite8** [comment]
@escopecz Yes, it seems to bug in mautic. I too tried with all possibilities. segment filter is not working on tag field.

**Comment by escopecz** [comment]
@suriite8 please create a new issue if you found a bug. Commenting on closed ones is not the right way to do it. You can link similar issues in your new one if they are relevant though.

**Comment by micaelomota** [comment]
I'm facing the same issue here on v4.4.11. But on my case it just don't work completely. 5 out of 93 contacts with the tag were included in the segment
