### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by logixbytes** [mautic/mautic#3612]
Dear Friends,

I am having serious problem installing Mautic 2.7.0 version on our Digital Ocean VPS server. Please find given below error message received when trying to install:

Can some help me here.

Warm Regards,

Venkatesha

unregister(); //$apcLoader->register(true); \Mautic\CoreBundle\ErrorHandler\ErrorHandler::register('prod'); $kernel = new AppKernel('prod', false); $kernel->loadClassCache(); Stack\run((new MiddlewareBuilder('prod'))->resolve($kernel));

Error Log:

[Thu Mar 09 05:19:35.801144 2017] [mpm_prefork:notice] [pid 17327] AH00170: caught SIGWINCH, shutting down gracefully
[Thu Mar 09 05:19:36.860966 2017] [suexec:notice] [pid 3727] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu Mar 09 05:19:36.861167 2017] [ssl:warn] [pid 3727] AH01916: Init: (www.coffeessories.com:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Thu Mar 09 05:19:36.884371 2017] [auth_digest:notice] [pid 3727] AH01757: generating secret for digest authentication ...
[Thu Mar 09 05:19:36.885096 2017] [lbmethod_heartbeat:notice] [pid 3727] AH02282: No slotmem from mod_heartmonitor
[Thu Mar 09 05:19:36.885343 2017] [ssl:warn] [pid 3727] AH01916: Init: (www.coffeessories.com:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Thu Mar 09 05:19:36.888725 2017] [mpm_prefork:notice] [pid 3727] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips configured -- resuming normal operations
[Thu Mar 09 05:19:36.888755 2017] [core:notice] [pid 3727] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu Mar 09 05:22:43.037280 2017] [mpm_prefork:notice] [pid 3727] AH00170: caught SIGWINCH, shutting down gracefully
[Thu Mar 09 05:22:44.095863 2017] [suexec:notice] [pid 3790] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu Mar 09 05:22:44.096034 2017] [ssl:warn] [pid 3790] AH01916: Init: (www.coffeessories.com:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Thu Mar 09 05:22:44.119417 2017] [auth_digest:notice] [pid 3790] AH01757: generating secret for digest authentication ...
[Thu Mar 09 05:22:44.120111 2017] [lbmethod_heartbeat:notice] [pid 3790] AH02282: No slotmem from mod_heartmonitor
[Thu Mar 09 05:22:44.120310 2017] [ssl:warn] [pid 3790] AH01916: Init: (www.coffeessories.com:443) You configured HTTP(80) on the standard HTTPS(443) port!
[Thu Mar 09 05:22:44.124305 2017] [mpm_prefork:notice] [pid 3790] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips configured -- resuming normal operations
[Thu Mar 09 05:22:44.124360 2017] [core:notice] [pid 3790] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

**Comment by escopecz** [comment]
All the errors seems to be related to bad server configuration, not Mautic. Consult them with Digital Ocean support or other server administrator, please.
