### ISSUE TITLE
Forms backward compatibility break (8)

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#3613]
| Q  | A
| ---| ---
| **Backward compatibility break?** | ✔️ 
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:

For the second time in Mautic 2.x now, upgrading has caused our forms to break.

To be more precise, it seems that with manually included forms, the `mautic-form.js` script expected the form to have a newer HTML structure than the old one that was already included in the website. Therefore, the form submission did not happen properly : the button kept displaying _Please wait..._ the form actions were not properly triggered and some unexpected problems varying from form to form.
This also happens with automatically included forms as cached copies of their rendered HTML are stored in the database.

When can we expect to have guaranteed backward compatibility ?

This is a great problem as we cannot expect Mautic users to systematically refresh all of their forms after an update. (Unless it was an update to Mautic 3.x)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.2 to 2.6
| PHP version | 5.6.29

### Steps to reproduce:
1. In Mautic 2.2 create a form
2. Include it manually on your website (easier to test)
3. Upgrade to 2.6
4. Compare form HTML
5. Note the different problems that may occur when submitting the old form

**Comment by escopecz** [comment]
Can you post here the both versions of the same form? I'm not aware anyone touched the generated HTML.

**Comment by escopecz** [comment]
I'll close this issue as the question hasn't been answered for a while. I'll re-open when it does.
