### ISSUE TITLE
CORS issue, Cannot get Dynamic Content to display.

### ISSUE THREAD

**Issue by mikeamcbrien** [mautic/mautic#3624]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
m.mysite.com is where Mautic is installed and hosted which is a subdomain of the site I am trying to display the Dynamic content, mysite.com

I am attempting to display dynamic content in an html page. My dynamic content div is 
```
<div class="mautic-slot" data-slot-name="mainlead"></div>
```

When loading the page, I am receiving the following error in my console
```
VM4047:2 OPTIONS https://m.mysite.com/dwc/mainlead? 404 ()
```
and
```
(index):1 XMLHttpRequest cannot load https://m.mysite.com/dwc/mainlead?. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mysite.com' is therefore not allowed access. The response had HTTP status code 404.
```
Recognizing that this is a CORS issue, I went to the setting to disable the CORS restriction to no avail. So I re-enabled the CORS restriction and added one, both and the other domain, it did not resolve the issue.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.0
| PHP version | 7.0.16

### Steps to reproduce:
1.  Insert Dynamic content code
2. Receive error.
3. Enable or Disable CORS setting.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

```
[2017-03-09 15:29:43] mautic.CRITICAL: Uncaught PHP Exception UnexpectedValueException: "Untrusted Host "m.mysite.com"" at /srv/users/serverpilot/apps/mysitemautic/public/app/bootstrap.php.cache line 957 {"exception":"[object] (UnexpectedValueException(code: 0): Untrusted Host \"m.mysite.com\" at /srv/users/serverpilot/apps/mysitemautic/public/app/bootstrap.php.cache:957)"} []
[2017-03-09 15:29:43] mautic.CRITICAL: Exception thrown when handling an exception (UnexpectedValueException: Untrusted Host "m.mysite.com" at /srv/users/serverpilot/apps/mysitemautic/public/app/bootstrap.php.cache line 957) {"exception":"[object] (UnexpectedValueException(code: 0): Untrusted Host \"m.mysite.com\" at /srv/users/serverpilot/apps/mysitemautic/public/app/bootstrap.php.cache:957)"} []
[2017-03-09 15:29:43] mautic.ERROR: UnexpectedValueException: Untrusted Host "m.mysite.com" - in file /srv/users/serverpilot/apps/mysitemautic/public/app/bootstrap.php.cache - at line 957 [] []
```

NGINX error log
```
[Thu Mar 09 16:14:17.294225 2017] [proxy_fcgi:error] [pid 17170:tid 140450186848000] [client 11.111.11.11:49337] AH01071: Got error 'Primary script unknown\n', referer: https://mysite.com/
```

**Comment by escopecz** [comment]
Do you have the domain where you use DWC added in the textarea in the CORS settings? Is your server accepting the OPTION requests? Maybe they are disabled.

**Comment by mikeamcbrien** [comment]
Thanks for the response, I did try adding the domain in the CORS setting, but it was not working.

However, after troubleshooting for 2 hours and then submitting this ticket, waiting overnight I came back to find that it is now working :/

How could this be? Was Mautic waiting for a cron to run? Is it something date specific? I literally changed nothing and it started working on it's own.

**Comment by escopecz** [comment]
I don't think it needs any cron. Hard to tell what was wrong and what fixed it. I'm glad it works today.

**Comment by mikeamcbrien** [comment]
On a side note, it appears the campaign condition of 'not empty' is failing to save properly. I'll do some more testing and submit another bug request.

**Comment by escopecz** [comment]
Before you do, try to search if it wasn't already reported or even [fixed](https://github.com/mautic/mautic/pull/3574)

**Comment by mikeamcbrien** [comment]
Thanks - I just replaced the file manually from that commit, then cleared my Mautic cache, it still misbehaves.

**Comment by escopecz** [comment]
See the command to regenerate production assets here: https://github.com/mautic/mautic#development-environement

**Comment by mikeamcbrien** [comment]
I did that and it is still not working 'mautic:assets:generate --env=prod' 

I dont know if if it differs or not, but I did a manual install over the git install, so even the index-dev does not exitis on my server.

**Comment by escopecz** [comment]
Then it may be cached in your browser. If you won't make it work, just wait till it get resolved in a future version. If you notice my comment in the linked PR, it fixes only half of the issue. No need to spend more time on it.

**Comment by mikeamcbrien** [comment]
Thanks for your help (I did note it only fixed half of the issue)  I appreciate your time and will let this issue die :)
