### ISSUE TITLE
mailchimp integration fails on lists/subscribe

### ISSUE THREAD

**Issue by igorA53** [mautic/mautic#3629]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
I've setup the Mailchimp integration a few months ago. At that time, the tests were successful. But Now, it deosn't work anymore although the Authorisation is still OK.  I even reauthorized a few times, without any problem.  My lists and the possible integration fields are imported. But the actual push of a contact fails. 

To make sure, it is not related to a wrong event structure in campaign, I added the mailchimp-push as an action to a standalone field. The form submit succeeds and it does the push, but with no succes. I found the API calls monitor in Mailchimp: see screenshot
![image](https://cloud.githubusercontent.com/assets/6865043/23788232/e2d72fb2-0575-11e7-9711-42f2e5ad66aa.png)

Is there a way to fond out what's wrong?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | hosted version
| PHP version |

**Comment by RCheesley** [comment]
Could be related to #3290 perhaps? are there errors in the logs?

**Comment by RCheesley** [comment]
I think it is. I checked my API logs, and I am also seeing the same response code and a failed call when I submit via a form:

![screenshot-us14 admin mailchimp com 2017-04-25 19-24-27](https://cloud.githubusercontent.com/assets/2930593/25401217/07daa3d4-29ed-11e7-9669-575aeafdd3a6.png)
