### ISSUE TITLE
Google Analytics not inserted for custom HTML pages

### ISSUE THREAD

**Issue by natselection** [mautic/mautic#364]
I may be doing something wrong here but I can't manage to get anything in the Analytics script (i.e. Google Analytics) field to show up on the front end.

I know a previous issue changed the field from just being the GA UA code to the full script but inserting either the script or just the UA code does not show up on the landing page.

**Comment by alanhartless** [comment]
Hey Matt,

Is this using a custom template, custom HTML, or a stock (or modified stock) template?

Thanks,
Alan

**Comment by alanhartless** [comment]
Looks like it's not getting inserted for custom HTML pages but works for templates.

**Comment by natselection** [comment]
Correct. I was only using the Custom HTML method.
