### ISSUE TITLE
In campaigns, when you Edit an send email condition, operator persists as 'equal'

### ISSUE THREAD

**Issue by miguelaguero** [mautic/mautic#3645]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | n
| Enhancement? | n

## Description:
When you edit the operator of the element contained in Condition Event, it shows always the operator 'Equals' and is not loading the previous selected Operator

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.0
| PHP version | 5.6.30

### Steps to reproduce:
1. Create a Campaign and add a new Condition: Send Email
2. Add any operator into the condition different than 'Equal'
3. Edit the campaign and open the Condition for edition
4. The operator appears as 'Equal' when should show the operator previously selected

![operator](https://cloud.githubusercontent.com/assets/655910/23806067/40235e4e-058e-11e7-8b69-556ba96630ea.PNG)
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Suggested fixed here: https://github.com/mautic/mautic/pull/3574
