### ISSUE TITLE
Reset custom return path (bounce) address when trigger campaign from cron

### ISSUE THREAD

**Issue by magician7** [mautic/mautic#3649]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  x
| Feature request? | 
| Enhancement? | 

## Description:
When I set PHP mail as transport in Mautic settings and trigger campaign, then return address in sending mail is change to "root@myservername.com" - no matter what I set in return path (bounce) address.

On the other hand when I send mail from channels/editmail/send example return-path is setting correctly - as I set in configuration.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.0
| PHP version | 7.016

### Steps to reproduce:
1. Set Service to send mail through: PHP Mail
2. Create new mail.
3. Add mail to campaign.
4. Add contact to campaign.
5. Trigger campaign by cron.
6. Check return-path in send mail.

2. 
 
### Log errors: 
Nothing in log (mautic & http server)

**Comment by magician7** [comment]
It's critical to get bounced mail and react to avoid drop in credibility in mail delivery. Any solutions?

**Comment by alanhartless** [comment]
This is not a Mautic issue but rather a server configuration issue. Likely in your PHP ini file for CLI has sendmail configured with the -f flag.

**Comment by magician7** [comment]
Hmm... Just check - same configuration php.ini loaded.
From Mautic system info: Loaded Configuration File 	/usr/local/php70/lib/php.ini 

From console:
php -i |grep php\.ini

Configuration File (php.ini) Path => /usr/local/php70/lib
Loaded Configuration File => /usr/local/php70/lib/php.ini

**Comment by magician7** [comment]
@alanhartless please re-open

**Comment by SlavekB** [comment]
This weekend I updated Mautic from 2.2.1 to 2.10.1. Before the update was bounces okay, after the update I have the same problem. Other system updates were not - only Mautic was updated.

This seems to be a Mautic problem rather than PHP.
How can this issue be re-openned?

Note: Debian 8.x (Jessie) with PHP 5.6.30+dfsg-0+deb8u1

**Comment by NickStallman** [comment]
Try using sendmail instead of PHP mail(). It's a Postfix quirk which means the Return-Path header is being overwritten by Postfix rather than letting Mautic control it.
Using sendmail will still go via Postfix, but it prevents Postfix from touching the header.

**Comment by SlavekB** [comment]
Yes, this way works correctly.
Thank you
