### ISSUE TITLE
Error when pushing leads to Zoho

### ISSUE THREAD

**Issue by davidnagtzaam** [mautic/mautic#3651]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N 
| Enhancement? | N

## Description:
The zoho plugin can not push contacts to zoho due to an incorrect function name

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.0, **2.7.1**
| PHP version | 5.6.24

### Steps to reproduce:
1. Authorize your zoho account with the mautic zoho module
2. Run "php app/console mautic:integration:fetchleads --integration=Exact" from the console
 
### Log errors: 

 [Symfony\Component\Debug\Exception\UndefinedMethodException]                                                                  
  Attempted to call an undefined method named "pushLeads" of class "MauticPlugin\MauticCrmBundle\Integration\ZohoIntegration".  
  Did you mean to call "pushLead"?

**Comment by npracht** [comment]
Also when i tried to use Zoho, i noticed you need to have Mautic in english otherwise it was not working. I don't know what is the status with that.
