### ISSUE TITLE
Identical duplicates of tag are generated

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#3652]
What type of report is this: Bug report

Description:
Identical duplicates of tag are generated:

- impossible to distinguish which one is the original
- unreliable list/segment membership
- unreliable use of conditions which rely on tags within campaign

![screenshot from 2017-03-13 11-26-19](https://cloud.githubusercontent.com/assets/10385295/23837686/16e8d190-07e0-11e7-87fd-39e25abfdeb6.png)

Without a user going into SQL, how else can this be fixed by them if this occurs?

| Mautic version |  2.7.0
| PHP version |  7.0.15-0ubuntu0.16.04.4

Steps to reproduce:
1. Creating a new tag while editing a lead/contact, identical duplicates of that tag were created. Difficult to define what causes this
2. When creating a list/segment which uses tag presence
3. Those identical duplicates of the tags were listed. When I picked one of those tags, only some of the users tagged show. Presumably this is because the tags have IDs at the back end, but because they are invisible to the user it causes inconsistency.

 
Log errors: No error logs generated

Associated Feature Request: #3653(duplicate closed) #2308(original)

**Comment by dbhurley** [comment]
Resolved in 2.12

**Comment by mburamorde** [comment]
I currently have this problem with 2.12 when adding tags via api that contains entities (& for example).
