### ISSUE TITLE
After upgrading  to mautic 2.7.0, excel export not working exactly

### ISSUE THREAD

**Issue by Ashwini04** [mautic/mautic#3654]
|Bug report 

## Description:
After upgrading from 2.0.1 to 2.7.0

When I am trying to export my segments contact in excel format, the result does not match with the contacts

For ex: there 6 segments in the segment "abc"

while opening the exported segment in excel it results 

6 rows (field name as 1st row and 5 contacts )

but actually it should export as 7 rows( 1st row as field name and 6 contacts)

**Comment by escopecz** [comment]
This seems like a duplicate of https://github.com/mautic/mautic/issues/3518 and it's fixed in https://github.com/mautic/mautic/pull/3536. The fix will be released in Mautic 2.7.1

**Comment by Ashwini04** [comment]
I have changed the code at line no. 453  in the \app\bundles\ReportBundle\Model\ReportModel.php

Previous code : else {
                                    $rowCount = $count + 1;
                                    $objPHPExcel->getActiveSheet()->fromArray($row, null, "A{$rowCount}");
                                }

Now :  I have removed the else statement and changed the $rowcount  = $count+2;  the code as like below

$rowCount = $count + 2;
 $objPHPExcel->getActiveSheet()->fromArray($row, null, "A{$rowCount}");

Now the exxport in excel format works fine

**Comment by escopecz** [comment]
Or upgrade to 2.7.1 where it is fixed already https://github.com/mautic/mautic/commit/110768369b43d7f78ddf68e44bb1de26a9bf1ba7

**Comment by Ashwini04** [comment]
Thanks dude
