### ISSUE TITLE
Add expire header to mtc.js

### ISSUE THREAD

**Issue by wittwerch** [mautic/mautic#3656]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes 
| Enhancement? | Yes

## Description:
The mtc.js is currently send to the browser without any expire header. We should probably add a expire header with a small TTL (2h) like Google Analytics does.
This would increase the performance and would not really harm the possibility to do upgrades.

**Comment by nextgens** [comment]
Browser-caching is a band-aid here... it seems to be (re)generated/minified for every request. The smart thing to do would be to generate it upon change and let the HTTPd handle it...

The speed at which it's served is critical to user experience!

**Comment by kuzmany** [comment]
@nextgens do you thinkg add mod_expires to htaccess?

https://www.google.sk/search?q=mod_expires+htaccess&oq=mod_expires&aqs=chrome.1.69i57j0l5.1968j0j1&sourceid=chrome&ie=UTF-8

**Comment by nextgens** [comment]
No, what I mean is regenerating it only when new CoreEvents::BUILD_MAUTIC_JS listeners are added to the dispatcher... and store it as a file the HTTPd could serve fast.

Here's the band-aid fix for the issue as suggested above:
https://gist.github.com/nextgens/ca501d3c1b149a62c09b0b409e0651a7

Here it helps a lot but I do believe that it's worth going further

**Comment by kuzmany** [comment]
@nextgens Now It's clear ;)

**Comment by nextgens** [comment]
A tradeoff would be to store it in the app-cache and serve it from there (in combination with browser caching)

**Comment by vkathirvel** [comment]
Was this feature ever implemented? I see that it was moved to Backlog and closed.
