### ISSUE TITLE
Allow campaign conditions to check contact segments

### ISSUE THREAD

**Issue by brandner** [mautic/mautic#3659]
What type of report is this:

| Q  | A
| ---| ---
| Feature request | y

## Description:
Campaign conditions include looking at 'form field values' and 'contact field values'. The contact field values include tags. However, there is no option to check a contact's segments.

The request is to add a condition type to check contact segments.

This functionality is generally possible using contact tags, but requires that tags duplicate data that is already known through segments.

### Steps to reproduce:
1. Create Segment A and Segment B
2. Create a contact that is part of 'Segment A' as well as 'Segment B'
3. Create a campaign for 'Segment A'
4. At some point in campaign, perform an action to contacts that are NOT also included in 'Segment B'

**Comment by escopecz** [comment]
This seems like a duplicate of https://github.com/mautic/mautic/issues/1095
