### ISSUE TITLE
Broadcast emails not sending when cron executes

### ISSUE THREAD

**Issue by brandner** [mautic/mautic#3660]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | n
| Enhancement? | n

## Description:

Unable to get segment/broadcast emails to send. My segment email shows as published, shows 1 pending email, and publish dates seem to be set as expected.

I run the cron by itself or with different combinations of --id=19 --channel=email. No change. Output is:

+---------------+--------+----------+
| Channel       | # sent | # failed |
+---------------+--------+----------+

Also see discussion on the Mautic Community forum here:
https://www.mautic.org/community/index.php/6553-scheduled-broadcasts-didn-t-send

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.0 or 2.7.1
| PHP version | 7.0.15-0ubuntu0.16.04.4

### Steps to reproduce:
1. Create new contact with email address
2. Add contact to a segment
3. Create new segment (broadcast) email
4. Select segment, enter past publish date, future publish end.
5. Complete email - Email list should show pending stat
6. Wait for cron to run or execute manually

$ php /PATH-TO-MAUTIC/web/app/console mautic:broadcasts:send
 
### Log errors: 

No log records. Syslog shows cron executing.
Attaching screenshot of the emails, the email details and a screenshot of executing the command manually.

![screenshot 67](https://cloud.githubusercontent.com/assets/533019/23876737/13be1590-07fc-11e7-85a2-9a50a9dc155b.png)
![screenshot 68](https://cloud.githubusercontent.com/assets/533019/23876739/1532f94a-07fc-11e7-973f-05db7237b3af.png)

**Comment by kuzmany** [comment]
Check these 2 direcotries: 
app/bundles/CoreBundle/Command/SendChannelBroadcastCommand.php 
app/bundles/ChannelBundle/Command/SendChannelBroadcastCommand.php

If you have both files remove app/bundles/CoreBundle/Command/SendChannelBroadcastCommand.php 

The file was moved to ChannelBundle but upgrade didn’t remove it from old directory. 
More info here: 
https://github.com/mautic/mautic/pull/3538

**Comment by brandner** [comment]
That was it, thanks. That file, along with a few others, are mode 644.
I've had consistent issues with permissions but it was originally quite a clean install.
Is there a guide to permissions or a recommended command that can ensure all the file permissions are correct?

**Comment by kszyniu** [comment]
I don't have SendChannelBroadcastCommand.php (fresh install) file in app/bundles/CoreBundle/Command/ and it still doesn't work.

tried to send by cli:
`php /var/www/mautic/public/app/console mautic:broadcasts:send`
and added to cronjob 
`*/1 * * * *  php /var/www/mautic/public/app/console mautic:broadcasts:send`

Sending by "Send" button does not work either but sending by "Send example" button works.

Any ideas?

**Comment by escopecz** [comment]
The file exists. You can check here: https://github.com/mautic/mautic/blob/2.7.1/app/bundles/ChannelBundle/Command/SendChannelBroadcastCommand.php

But it depends what version you installed.

**Comment by kszyniu** [comment]
@escopecz yeah - this files exists here:
`app/bundles/ChannelBundle/Command`
but not here
`app/bundles/CoreBundle/Command`
so I have nothing to delete
I'm using freshly installed  2.7.1 (downloaded today).

**Comment by escopecz** [comment]
I think I'm missing some piece from the communication. Why would it have to exist in the CoreBundle? Why would you delete something?

**Comment by escopecz** [comment]
Ah, Kuzmany was suggesting that. That example could happen for failed updates, not for fresh installation. If you have nothing to delete, that means there is no problem. What is the output when you execute the command manually?

**Comment by kszyniu** [comment]
@escopecz please look here:
https://github.com/mautic/mautic/issues/3660#issuecomment-286282000

and then here:
https://github.com/mautic/mautic/pull/3538

**Comment by kszyniu** [comment]
@escopecz it looks like this:

```
php /var/www/mautic/public/app/console mautic:broadcasts:send

+---------+--------+----------+
| Channel | # sent | # failed |
+---------+--------+----------+
```

**Comment by escopecz** [comment]
Looks good. There is nothing to send.

**Comment by kszyniu** [comment]
![screen shot 2017-04-19 at 14 42 44](https://cloud.githubusercontent.com/assets/357661/25180524/a0a99d38-250e-11e7-8a78-be6abde85a16.png)
there is something to send, I tried to schedule it 5 / 10 minutes before corn run and nothing happend

**Comment by escopecz** [comment]
Did you click on the Send button?

**Comment by escopecz** [comment]
Here is some more info about the command: https://mautic.org/docs/en/setup/cron_jobs.html

**Comment by kszyniu** [comment]
Yes :) I did, as I mentioned - tried to send by clicking on "Send" button - nothing happened, tried to send by cli - nothing happened. Tried to send by "Send example mail" - success, I've got mail.

**Comment by escopecz** [comment]
Do you have Email settings configured to "Immediately send" or "Queue"?

**Comment by kszyniu** [comment]
"Queue".

**Comment by escopecz** [comment]
What does `php /path/to/mautic/app/console mautic:emails:send` command output?

**Comment by kszyniu** [comment]
`rename(/var/www/mautic/public/app/spool/default/XLCNbcidGj.message,/var/www/mautic/public/app/spool/default/XLCNbcidGj.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/21xqb128BH.message,/var/www/mautic/public/app/spool/default/21xqb128BH.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/QDhEqXCVG7.message,/var/www/mautic/public/app/spool/default/QDhEqXCVG7.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/jKdOkXM6tf.message,/var/www/mautic/public/app/spool/default/jKdOkXM6tf.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/y78FlWuTCp.message,/var/www/mautic/public/app/spool/default/y78FlWuTCp.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/yEzD2-n-Uy.message,/var/www/mautic/public/app/spool/default/yEzD2-n-Uy.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/663zpf2gsZ.message,/var/www/mautic/public/app/spool/default/663zpf2gsZ.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/PlTWoshxjJ.message,/var/www/mautic/public/app/spool/default/PlTWoshxjJ.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/VSAlDL7LQ0.message,/var/www/mautic/public/app/spool/default/VSAlDL7LQ0.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/OMMZvdpibF.message,/var/www/mautic/public/app/spool/default/OMMZvdpibF.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/LZY6k0ETgR.message,/var/www/mautic/public/app/spool/default/LZY6k0ETgR.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/C2uywFjQmM.message,/var/www/mautic/public/app/spool/default/C2uywFjQmM.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/-zXU3HXmjT.message,/var/www/mautic/public/app/spool/default/-zXU3HXmjT.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/8lvUsIamYM.message,/var/www/mautic/public/app/spool/default/8lvUsIamYM.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/RH9pb44es2.message,/var/www/mautic/public/app/spool/default/RH9pb44es2.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/J4KNRe2PUW.message,/var/www/mautic/public/app/spool/default/J4KNRe2PUW.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/wJMJo4uU1A.message,/var/www/mautic/public/app/spool/default/wJMJo4uU1A.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/7PgYcv45Bk.message,/var/www/mautic/public/app/spool/default/7PgYcv45Bk.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/Nk0YQ9FUFX.message,/var/www/mautic/public/app/spool/default/Nk0YQ9FUFX.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/X0KF6PdA_f.message,/var/www/mautic/public/app/spool/default/X0KF6PdA_f.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/RM9Z30nYUQ.message,/var/www/mautic/public/app/spool/default/RM9Z30nYUQ.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/OYZ82iuyDy.message,/var/www/mautic/public/app/spool/default/OYZ82iuyDy.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/xwmr4g1J2a.message,/var/www/mautic/public/app/spool/default/xwmr4g1J2a.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/LVG361Sf29.message,/var/www/mautic/public/app/spool/default/LVG361Sf29.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/NlVDWduO7m.message,/var/www/mautic/public/app/spool/default/NlVDWduO7m.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/qu5P_iVLUe.message,/var/www/mautic/public/app/spool/default/qu5P_iVLUe.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/87sSR7XvG5.message,/var/www/mautic/public/app/spool/default/87sSR7XvG5.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/19d_rjZyCp.message,/var/www/mautic/public/app/spool/default/19d_rjZyCp.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/uShdLwi2Bi.message,/var/www/mautic/public/app/spool/default/uShdLwi2Bi.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/oCk1KBQ5Wj.message,/var/www/mautic/public/app/spool/default/oCk1KBQ5Wj.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/JKELT9WHFE.message,/var/www/mautic/public/app/spool/default/JKELT9WHFE.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/jtR-cMbPUl.message,/var/www/mautic/public/app/spool/default/jtR-cMbPUl.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166`

**Comment by escopecz** [comment]
You have some file system permission issue there. But you can see that the emails were waiting in the queue to be sent. More info about the second command is also in the link to docs I posted.

**Comment by escopecz** [comment]
This usually happens if you run cron as root. Run it as the web server user.

**Comment by kszyniu** [comment]
Thank you John for the tips, will look at that and let you know about the status.

**Comment by kszyniu** [comment]
Still nothing :(

First:
`sudo -u www-data crontab -e`

Then added:
```
0,15,30,45 * * * * php /var/www/mautic/public/app/console mautic:broadcasts:send >/dev/null 2>&1
1,16,31,46 * * * * php /var/www/mautic/public/app/console mautic:segments:update >/dev/null 2>&1
2,17,32,47 * * * * php /var/www/mautic/public/app/console mautic:campaigns:rebuild >/dev/null 2>&1
3,18,33,48 * * * * php /var/www/mautic/public/app/console mautic:campaigns:trigger >/dev/null 2>&1
4,19,34,49 * * * * php /var/www/mautic/public/app/console mautic:emails:send >/dev/null 2>&1
5,20,35,50 * * * * php /var/www/mautic/public/app/console mautic:emails:fetch >/dev/null 2>&1
6,21,36,51 * * * * php /var/www/mautic/public/app/console mautic:iplookup:download >/dev/null 2>&1
7,22,37,52 * * * * php /var/www/mautic/public/app/console mautic:integration:fetchleads --integration=Hubspot >/dev/null 2>&1
8,23,38,53 * * * * php /var/www/mautic/public/app/console mautic:integration:pushleadactivity --integration=Hubspot >/dev/null 2>&1
9,24,39,54 * * * * php /var/www/mautic/public/app/console mautic:social:monitoring >/dev/null 2>&1
```

Saved.

No crotab jobs for mautic using root account.

```
Then check:
php /var/www/mautic/public/app/console mautic:broadcasts:send


+---------+--------+----------+
| Channel | # sent | # failed |

```

Still 4 test e-mails are waiting:
![screen shot 2017-04-19 at 15 20 13](https://cloud.githubusercontent.com/assets/357661/25182059/c39fb46c-2513-11e7-98f9-6b6618c8ef87.png)


Then:
`php /var/www/mautic/public/app/console mautic:emails:send`

Got this:
PHP Warning:  ```
rename(/var/www/mautic/public/app/spool/default/XLCNbcidGj.message,/var/www/mautic/public/app/spool/default/XLCNbcidGj.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/YeIiO0Sx1r.message,/var/www/mautic/public/app/spool/default/YeIiO0Sx1r.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/21xqb128BH.message,/var/www/mautic/public/app/spool/default/21xqb128BH.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/QDhEqXCVG7.message,/var/www/mautic/public/app/spool/default/QDhEqXCVG7.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/jKdOkXM6tf.message,/var/www/mautic/public/app/spool/default/jKdOkXM6tf.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/y78FlWuTCp.message,/var/www/mautic/public/app/spool/default/y78FlWuTCp.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/yEzD2-n-Uy.message,/var/www/mautic/public/app/spool/default/yEzD2-n-Uy.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/663zpf2gsZ.message,/var/www/mautic/public/app/spool/default/663zpf2gsZ.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/PlTWoshxjJ.message,/var/www/mautic/public/app/spool/default/PlTWoshxjJ.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/VSAlDL7LQ0.message,/var/www/mautic/public/app/spool/default/VSAlDL7LQ0.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/OMMZvdpibF.message,/var/www/mautic/public/app/spool/default/OMMZvdpibF.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/LZY6k0ETgR.message,/var/www/mautic/public/app/spool/default/LZY6k0ETgR.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/C2uywFjQmM.message,/var/www/mautic/public/app/spool/default/C2uywFjQmM.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/-zXU3HXmjT.message,/var/www/mautic/public/app/spool/default/-zXU3HXmjT.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/m3vJsKVbLT.message,/var/www/mautic/public/app/spool/default/m3vJsKVbLT.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/8lvUsIamYM.message,/var/www/mautic/public/app/spool/default/8lvUsIamYM.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/RH9pb44es2.message,/var/www/mautic/public/app/spool/default/RH9pb44es2.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/J4KNRe2PUW.message,/var/www/mautic/public/app/spool/default/J4KNRe2PUW.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/lJghr6rJ4R.message,/var/www/mautic/public/app/spool/default/lJghr6rJ4R.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/wJMJo4uU1A.message,/var/www/mautic/public/app/spool/default/wJMJo4uU1A.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/7PgYcv45Bk.message,/var/www/mautic/public/app/spool/default/7PgYcv45Bk.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/Nk0YQ9FUFX.message,/var/www/mautic/public/app/spool/default/Nk0YQ9FUFX.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/X0KF6PdA_f.message,/var/www/mautic/public/app/spool/default/X0KF6PdA_f.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/RM9Z30nYUQ.message,/var/www/mautic/public/app/spool/default/RM9Z30nYUQ.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/OYZ82iuyDy.message,/var/www/mautic/public/app/spool/default/OYZ82iuyDy.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/xwmr4g1J2a.message,/var/www/mautic/public/app/spool/default/xwmr4g1J2a.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/LVG361Sf29.message,/var/www/mautic/public/app/spool/default/LVG361Sf29.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/NlVDWduO7m.message,/var/www/mautic/public/app/spool/default/NlVDWduO7m.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/qu5P_iVLUe.message,/var/www/mautic/public/app/spool/default/qu5P_iVLUe.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/87sSR7XvG5.message,/var/www/mautic/public/app/spool/default/87sSR7XvG5.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/19d_rjZyCp.message,/var/www/mautic/public/app/spool/default/19d_rjZyCp.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/uShdLwi2Bi.message,/var/www/mautic/public/app/spool/default/uShdLwi2Bi.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/oCk1KBQ5Wj.message,/var/www/mautic/public/app/spool/default/oCk1KBQ5Wj.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/k_qKaPWLYL.message,/var/www/mautic/public/app/spool/default/k_qKaPWLYL.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/JKELT9WHFE.message,/var/www/mautic/public/app/spool/default/JKELT9WHFE.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
PHP Warning:  rename(/var/www/mautic/public/app/spool/default/jtR-cMbPUl.message,/var/www/mautic/public/app/spool/default/jtR-cMbPUl.message.sending): Permission denied in /var/www/mautic/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166
```

**Comment by escopecz** [comment]
I don't think you fixed the permissions. Try something like [this](https://askubuntu.com/questions/162866/correct-permissions-for-var-www-and-wordpress) I don't know what OS you have.

**Comment by kszyniu** [comment]
OS: Ubuntu 16.04 LTS.

Folder is owned by www-data. Chmoded all files and folders to 777.
Looks like this.
![screen shot 2017-04-19 at 15 29 15](https://cloud.githubusercontent.com/assets/357661/25182536/3ba60b2c-2515-11e7-9f8c-91bdc0ba196f.png)

And then:
![screen shot 2017-04-19 at 15 30 49](https://cloud.githubusercontent.com/assets/357661/25182552/43595efa-2515-11e7-8fcf-01c7431e8b11.png)

**Comment by escopecz** [comment]
Use the `--force` param as the error says.

**Comment by architjoshihs** [comment]
I am facing this same issue. The send button in the view is sending emails. But any contact that gets added after this do not received any emails because i dont remember pressing the send button. The cron job does not get executed.

This has been a problem since long. There are many threads related to this issue. Other crons are executing just fine, so there is no permission issue.

Also i am not adding any parameter to send broadcast email. So there is no chance of error in command.

Thank you in advance to resolve this issue of broadcast cron.

**Comment by escopecz** [comment]
@architjoshihs this is probably just a confusion on how the segment emails should work. Segment emails are for sending newsletters. So one time send. If more contacts are added to the segment then those contacts will appear as pending in the segment email and you have to click the send button again to send the email to the pending contacts.

If you need to send emails to all contact that are being added to a segment automatically then use campaigns. Campaign actions are being executed once a new contact is added to the source segment.
