### ISSUE TITLE
app/logs Files Owned By root

### ISSUE THREAD

**Issue by j-ki** [mautic/mautic#3662]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y 
| Feature request? |  N
| Enhancement? |  N

## Description:
New Mautic log files are created and owned by root. However, the webserver runs under a different user. So when some Mautic process needs to write to them, in order to function properly, it fails.

In order to fix this, I need to change the log file ownership to the webserver owner and group.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0

### Steps to reproduce:
1. Wait for a new log file to be written.
2. Try to view a SMS message
3. See a blank screen
 
### Log errors: 

N/A. Mautic doesn't allow writing to log files, unless file permissions are changed.

**Comment by escopecz** [comment]
Mautic uses only the permission you give it. It doesn't have how to gain the root permissions by itself. My guess here is that you run the cron job commands as the root user.
