### ISSUE TITLE
PHP 7.1 error on installation

### ISSUE THREAD

**Issue by david-bettondesign** [mautic/mautic#3665]
What type of report is this:

| Bug report? | Yes

## Description:
Installing Mautic 2.7.1 gives a PHP error. The specific error is "Mautic does not support PHP version 7.1.2-4+deb.sury.org~xenial+1 at this time. To use Mautic, you will need to downgrade to an earlier version."
Normally I would leave it at that but the latest version of Mautic (2.7.1) is supposed to be compatible with PHP 7.1 isn't it?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.1.2

### Steps to reproduce:
1. Try to install mautic

**Comment by escopecz** [comment]
Sadly not. There was an attempt to support PHP 7.1, but there were some problems with the Mautic commands, so it was reversed: https://github.com/mautic/mautic/pull/3416

**Comment by david-bettondesign** [comment]
Ah, thanks for the info :)

**Comment by skynet** [comment]
I believe I have the same problem. Wish it was documented somewhere in the Mautic installation log.

**Comment by MxyzptlkFishStix** [comment]
https://www.mautic.org/download/requirements/

**Comment by andersonbraz** [comment]
I solved like this:

Changing

``php
const MAUTIC_MAXIMUM_PHP = '7.1.999';
``

on 

file /app/middlewares/VersionCheckMiddleware.php

to

``php
const MAUTIC_MAXIMUM_PHP = '7.3.999';
``

---
by [Anderson Braz](https://andersonbraz.com)
