### ISSUE TITLE
Error mautic segments update

### ISSUE THREAD

**Issue by pacbrother** [mautic/mautic#3668]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
When I execute the command to update segments:

/usr/bin/php-cli -q /home/myuser/my.subdomain/app/console mautic:segments:update

The proccess stops with an error and it does not continue to update all segments.

I checked for invalid characters in the segment but couldn't find anything. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 5.6.30

### Steps to reproduce:
1. Execute /usr/bin/php-cli -q /home/myuser/my.subdomain/app/console mautic:segments:update
2. The result is the log below
 
### Log errors: 
myuser@server [~]# /usr/bin/php-cli -q /home/myuser/my.subdomain/app/console mautic:segments:update
Rebuilding contacts for segment 1
0 total contact(s) to be added in batches of 300
total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 21
0 total contact(s) to be added in batches of 300
total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 2
0 total contact(s) to be added in batches of 300
total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 20
0 total contact(s) to be added in batches of 300
total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 3
0 total contact(s) to be added in batches of 300
0 total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 63
0 total contact(s) to be added in batches of 300
total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 65
0 total contact(s) to be added in batches of 300
0 total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 64
0 total contact(s) to be added in batches of 300
0 total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 76
0 total contact(s) to be added in batches of 300
0 total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 75
0 total contact(s) to be added in batches of 300
0 total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 77
0 total contact(s) to be added in batches of 300
0 total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 58
0 total contact(s) to be added in batches of 300
total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 72
0 total contact(s) to be added in batches of 300
total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 15

[Doctrine\DBAL\Exception\SyntaxErrorException] 
An exception occurred while executing 'SELECT count(l.id ) as lead_count, ma 
x(l.id ) as max_id FROM mautic_leads l LEFT JOIN mautic_lead_lists_leads ll 
ON (ll.leadlist_id = 15) AND (ll.lead_id = l.id ) AND (ll.date_added <= '201 
7-02-15 16:27:54') WHERE (()) AND (ll.lead_id IS NULL)': 
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i 
n your SQL syntax; check the manual that corresponds to your MariaDB server 
version for the right syntax to use near ')) AND (ll.lead_id IS NULL)' at 
line 1

[Doctrine\DBAL\Driver\PDOException] 
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i 
n your SQL syntax; check the manual that corresponds to your MariaDB server 
version for the right syntax to use near ')) AND (ll.lead_id IS NULL)' at 
line 1

[PDOException] 
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i 
n your SQL syntax; check the manual that corresponds to your MariaDB server 
version for the right syntax to use near ')) AND (ll.lead_id IS NULL)' at 
line 1

mautic:segments:update [-b|--batch-limit [BATCH-LIMIT]] [-m|--max-contacts [MAX-CONTACTS]] [-i|--list-id [LIST-ID]] [-f|--force] [-t|--timeout TIMEOUT] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Can you post here (Drag&drop the file to the comment textarea) a screenshot with the filters you have in segment 15?

**Comment by pacbrother** [comment]
There are no filters
![screenshot-filters-mautic](https://cloud.githubusercontent.com/assets/2260672/23906468/cadfac9c-08ac-11e7-89fa-64e1afd948e7.png)

**Comment by RegisScaggiante** [comment]
Any idea about what might be happening?

**Comment by MxyzptlkFishStix** [comment]
There's probably a reserved word that's causing a syntax error.  I'm just guessing.

https://dev.mysql.com/doc/refman/5.7/en/keywords.html

**Comment by escopecz** [comment]
This should be fixed in 2.9.2.
