### ISSUE TITLE
Email sent multiple times

### ISSUE THREAD

**Issue by lucasmoraes804** [mautic/mautic#3669]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? | 

## Description:
I have campa

## If a bug:
I have a campaign with an email marketing type. But he sent several times, as the picture shows
[https://drive.google.com/open?id=0B5vQepyPPlAoU1ZkX19OdjdiblE](url)
[https://drive.google.com/file/d/0B5vQepyPPlAobWFueTV1UDhtdmM/view?usp=sharing](url)
| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
This happened to the users who had all the cron commands started in the same time. Could you check if your cron jobs starts at the same time and if so, try to add a few minutes between them. Let us know if it helped.

**Comment by lucasmoraes804** [comment]
I have cron run in same time. The correctly is run in 5 minutes of difference?

**Comment by escopecz** [comment]
I think it may be 1 minute apart. The problem begins if it starts in the same second.

**Comment by nickian** [comment]
This is kind of a big deal. Why would something like this not be included in the release notes when it becomes necessary to change?

The documentation is also not very intuitive (https://mautic.org/docs/en/setup/cron_jobs.html).

For example, it says to do this:

0,15,30,45 <— mautic:segments:update
5,20,35,50 <— mautic:campaigns:update
10,25,40,55 <— mautic:campaigns:trigger

But then below, there is no mention of "mautic:campaigns:update" anywhere in the required cron jobs. Is this the same thing as "mautic:campaigns:rebuild"?

This seems overly complex. Why can't there be a simple, mostly standard cron example file that people can simply copy and paste? Then mention the additional options below.

Would this be a correct implementation?

0,15,30,45 * * * * /usr/bin/php /home/mautic/www/app/console mautic:segments:update
5,20,35,50 * * * * /usr/bin/php /home/mautic/www/app/console mautic:campaigns:update
*/5 * * * * /usr/bin/php /home/mautic/www/app/console mautic:campaigns:rebuild
10,25,40,55 * * * * /usr/bin/php /home/mautic/www/app/console mautic:campaigns:trigger
*/5 * * * * /usr/bin/php /home/mautic/www/app/console mautic:emails:send
*/5 * * * * /usr/bin/php /home/mautic/www/app/console mautic:email:fetch
*/5 * * * * /usr/bin/php /home/mautic/www/app/console mautic:social:monitoring
*/5 * * * * /usr/bin/php /home/mautic/www/app/console mautic:iplookup:download

**Comment by kuzmany** [comment]
These commands are same.

mautic:campaigns:rebuild
mautic:campaigns:update

Please let just mautic:campaigns:rebuild

You are able to improve documentation, a lot of people will appreciate that ;)

**Comment by lucasmoraes804** [comment]
I changed my cron to:
1,5,9,13,18,22,26,31,35,39,43,48,52,56 * * * *  php /app/console mautic:segments:update -f
2,6,10,14,19,23,27,32,36,40,44,49,53,57 * * * * php /app/console mautic:campaigns:rebuild -f
3,7,11,16,20,24,28,33,37,41,46,50,54,58 * * * * php /app/console mautic:campaigns:trigger -f
4,8,12,17,21,25,29,34,38,42,47,51,55,59 * * * * php /app/console mautic:emails:send -f

But the problem continue like show image
https://drive.google.com/open?id=0B5vQepyPPlAoSUt1YUlLdUtOY00

**Comment by kuzmany** [comment]
dont' use  -f param

**Comment by PeterTL** [comment]
@kuzmany and @lucasmoraes804 , what is your experience with @lucasmoraes804's cron settings? Is it OK or is there still a risk of overlapping?

**Comment by escopecz** [comment]
The warning

> It is HIGHLY recommended that you stagger the following required jobs so as to not run the exact same minute.

is in the [documentation](https://mautic.org/docs/en/setup/cron_jobs.html) for [over a year](https://github.com/mautic/documentation/commit/c6fdfb4af5e7fb6940230f5dd5707cbc4b4e18e6). Anyone can improve the documentation. There isn't any reason to complain that it is not intuitive if [you can improve it](https://github.com/mautic/documentation#how-to-contribute-to-the-docs) any time.

> Why would something like this not be included in the release notes when it becomes necessary to change?

It's that way from the beginning, but it started to appear when users started to use Mautic on bigger datasets.

**Comment by phuongncn** [comment]
I make a batch script, and make the cron to execute it every minute. I separated each mautic cron command by sleep 10. See if it helps.
`*/1 * * * * /root/mtcron.sh > /dev/null 2>&1`

`#!/bin/bash
php /home/mydomain.com/public_html/app/console mautic:campaigns:trigger > /dev/null 2>&1
sleep 10
php /home/mydomain.com/public_html/app/console mautic:segments:update > /dev/null 2>&1
sleep 10
php /home/mydomain.com/public_html/app/console mautic:campaigns:rebuild > /dev/null 2>&1
sleep 10
php /home/mydomain.com/public_html/app/console mautic:email:send > /dev/null 2>&1`
