### ISSUE TITLE
mandrill conection error

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#367]
I have a new instalation in my own server.
I configure mandrill mail sender
I test (in configuration page and they send the email) 
I create a email campain that is sended when someone send a form.
I push the "send example" to see the result and I receive and test email (they don't use mandrill or mandrill dont count this email as sended)
I complete the form and the email don't arrive (mautic report sended but not read)

in /App/config/local.php 
'db_path' => null,
	'mailer_from_name' => 'Interdigital',
	'mailer_from_email' => 'acc@interdigital.es',
	'mailer_transport' => 'mautic.transport.mandrill',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => 'secretuser',
	'mailer_password' => 'secretpass',
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',

![image](https://cloud.githubusercontent.com/assets/10166840/7469845/2b49e662-f318-11e4-8637-c0eee1c050d6.png)
![image](https://cloud.githubusercontent.com/assets/10166840/7469893/9a26bc4a-f318-11e4-9fe7-515618a3d81e.png)

**Comment by miguelpascual** [comment]
I get the same if use gmail account for send emails.
Test email in configuration page is send by gmail 
Test email in emails campains arrive but I dont know the way it use (php mail by default?)
Campain email is not send

**Comment by alanhartless** [comment]
Hi,

A few things to check. 

First, look in app/logs/mautic_prod.php to see if there are any mail errors. 

Second, in your configuration, what do you have configured for "how to handle mail;" is it send immediately or queue? 

Is the email shown as being sent when you view your lead details page? It'll be listed in the time line 

Also, how are you adding the leads to your campaign? Are you assigning them to a lead  list when they submit the form and that list is assigned to your campaign?

Thanks,
Alan

**Comment by miguelpascual** [comment]
The folder app/logs/ is empty

Send is set immediatly
![image](https://cloud.githubusercontent.com/assets/10166840/7474365/304f1c9e-f341-11e4-86a8-ff51e9b7ee30.png)

In https://www.mautic.org/community/index.php/308-smtp-connection-failed i added this new data:

I found new data. The email (in campaign) is send directly by the server by php mail. It don´t use the mandrill configuration to send the email.

Received: from 127.0.0.1 (EHLO xxxxxxx.yyyyyyyyyy.es ) (XX.XX.XX.XX) <--- This is the server when mautic is hosted
by mta1015.mail.bf1.yahoo.com  with SMTPS; Tue, 05 May 2015 11:26:00 +0000
Received: by xxxxxxx.yyyyyyyyyy.es  (Postfix, from userid 10057)
id 5AA905C5D2C; Tue, 5 May 2015 13:25:58 +0200 (CEST)

The problem now is Mautic is sending the email using phpmail not mandrill :S

**Comment by miguelpascual** [comment]
The problem were the configuration cache. 

https://www.mautic.org/community/index.php/308-smtp-connection-failed/p1#p1341

**Comment by alanhartless** [comment]
Are you using 1.0.4? There was an issue on some servers that saving the configuration wouldn't clear the cache which 1.0.4 should have fixed.

Thanks,
Alan

**Comment by miguelpascual** [comment]
I was installed the new instance of mautic this morning and the first action i did was update it to 1.0.4

**Comment by alanhartless** [comment]
Thanks Miguel.  

I believe this is related to an issue fixed in 1.0.4. If you continue to have issues, let us know!

Thanks,
Alan

**Comment by RCheesley** [comment]
I think I have this problem, or a related problem.

If I have Mandrill enabled with correct username/password, I get a 504 gateway error whenever submitting a form which has an email function, and the test connection/send test mail doesn't work.

If I switch this to PHPMail immediately the form submits fine, no more gateway error.

Unsure if this is the same issue or related.
