### ISSUE TITLE
Remove campaign forms in favor of standalone forms

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3673]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
It is very confusing to have 2 types of forms in mautic. I've never seen that in any marketing automation software yet.

## Suggestions:
I'd rather in terms of ease of use, create only one type of form that can be used as source in campaigns and having the Action tab.

- Is there any marketing reason to keep them separated?
- If it is only technical, mautic should consider optimize it to make it clearer by having only one type with all features.

**Comment by abooster** [comment]
Totally agree. There should be just **forms**. Plain and simple.
And I should be able to use the input coming from a form in whichever way I need to.

**Comment by kuzmany** [comment]
👍  I agree

**Comment by RCheesley** [comment]
Existing issue: https://github.com/mautic/mautic/issues/2979

**Comment by escopecz** [comment]
Thanks for the link, Ruth. Closing this issue in favour of https://github.com/mautic/mautic/issues/2979
