### ISSUE TITLE
While upgrading mautic from 2.5.0 to 2.7.1 mautic crashed

### ISSUE THREAD

**Issue by ahugh1** [mautic/mautic#3675]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Try to follow https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful
