### ISSUE TITLE
Company Name Disappeared from "Contacts" View - WHY???

### ISSUE THREAD

**Issue by abooster** [mautic/mautic#3676]
There was a nice feature in v2.5.1 showing the company name under the contact's name in contacts view. 
Now, in v2.7.1 this feature appears to be gone. 
WHY???

Or is it just hidden under some impossible to find setting somewhere?

Showing the company name (in smaller font under the name of the contact) in a contact view list was a pretty neat feature. I'd like to know how/where can I re-enable that in v2.7.1?

**Comment by escopecz** [comment]
Hi, I can see the companies like this:
![contact-company](https://cloud.githubusercontent.com/assets/1235442/23937693/19651f6c-0959-11e7-8370-a63ae44ae801.png)
You cannot see the contact's companies there?

**Comment by abooster** [comment]
This screenshot explains: 
(I was talking about the list view that you get in Mautic **v2.5.1** when you click on the "contacts" in the navigation menu on the left)
![mautic 2017-03-15_08-30-46](https://cloud.githubusercontent.com/assets/20304781/23938399/80244e6e-095c-11e7-9a99-5e155e57c6b7.jpg)

**Comment by escopecz** [comment]
Got it. Thanks for the screenshot.
