### ISSUE TITLE
Cant able to edit email template in 2.7.0

### ISSUE THREAD

**Issue by Ashwini04** [mautic/mautic#3677]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | YES
| PHP version | 

### Steps to reproduce:
1. While cloning my custom theme , and then when I open the builder I cant able to edit the builder.
In earlier version 2.1.0 , we have content as a separate tab there I can edit my builder content.

But in 2.7.0 instead of content tab I have dynamic content.

**Comment by escopecz** [comment]
I cannot replicate. What theme are you using? Is it a custom HTML? If so, you'll have to use the [Code Mode](https://mautic.org/docs/en/themes/code_mode.html) builder to edit it.

**Comment by escopecz** [comment]
Closing for lack of feedback. Please get back with answers and I'll re-open.
