### ISSUE TITLE
User cannot see owned contacts

### ISSUE THREAD

**Issue by mrerich** [mautic/mautic#3678]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I created a role for user who should see only leads he owns (through ownership field in lead details).
Role set: Lead permission -> see owned
When I log as a user, i see no contacts.
If I create a lead as that user, after saving I still cannot see any records

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.16

### Steps to reproduce:
1. create a role with permission to see only owned leads + permission to create new leads 
2. create a user with this role
3. create lead owned by this user
4. log as this user
5. try to list leads - empty list
6. create new lead as this user - save the record - list leads -> empty list
 
### Log errors: 
none

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by sambarnes90** [comment]
I wasn't able to reproduce this.

Just tested it and worked fine for me.

Could you provide a screenshot of the role, the user and the contact you assigned just so we're clear on exactly what permissions are set?

**Comment by mrerich** [comment]
Ok, so when taking screenshots I found out, that the bug is active when the system is in Czech language only. I set language to English for screenshot purposes and contact appeared. I tried several other languages, but it looks like only Czech language has this bug.

![mautic3](https://cloud.githubusercontent.com/assets/26136473/24022083/9d3afea0-0aa4-11e7-8778-883967c93a95.PNG)
![mautic4](https://cloud.githubusercontent.com/assets/26136473/24022085/9d3dbe1a-0aa4-11e7-9414-3f06e3530989.PNG)
![mautic2](https://cloud.githubusercontent.com/assets/26136473/24022082/9d399e0c-0aa4-11e7-99f2-66960fe46516.PNG)
![mautic1](https://cloud.githubusercontent.com/assets/26136473/24022084/9d3dca4a-0aa4-11e7-8558-40cdcb1c9bdd.PNG)

**Comment by mrerich** [comment]
any progress?

**Comment by escopecz** [comment]
Languages aren't part of this repository. Please fix this with Czech language at transifex.com/mautic/mautic
