### ISSUE TITLE
Given email in tracking code, Does not create as a lead

### ISSUE THREAD

**Issue by l2aelba** [mautic/mautic#3680]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | n/a
| Feature request? | n/a
| Enhancement? | n/a

## Description:

I have a tracking code like...
```
(function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)})(window,document,'script','http://domain.com/mautic/mtc.js','mt');
mt('send','pageview',{email:'hello@email.com',firstname:'Hello',lastname:'World',});
```
I have a Wordpress website, I need to track **logged in users**. Just that

But Mautic **does not create** visitors as **a lead**, it just as anonymous

**Whats happen ? What Im missing**

- Basic installation _(Doesnt edit setting or do something)_
- Newest version

**Comment by kuzmany** [comment]
Read documentation.
Go to  Custom fields and mark email field as public updatable.

**Comment by l2aelba** [comment]
@kuzmany That what im missing !!!! Cheer !
