### ISSUE TITLE
@dongilbert

### ISSUE THREAD

**Issue by abooster** [mautic/mautic#3683]
@dongilbert 
No, I never used Mautic in a production environment but I was certainly hoping to be able to use it some day in a production environment. 
As it stands, version 2.7.1 is STILL not fit for use in a production environment 
and it appears that you guys would rather keep adding new features every 4 weeks instead of creating at least one version that can actually be used in a production environment in business. 

I had already posted all information I had about the OAuth1 failure in that thread that you closed. 
It's right there in the screenshot I posted. 
It says in that screenshot: 
"The connection didn't work.
Error message: An unknown error has occurred"

That's all information I got about this problem. 
"An unknown error has occurred"

Also, Thrive Theme (the application I was trying to connect) doesn't recommend to use OAuth2 (because no one in their right mind would want to use OAuth2 for an email application). 
Anyway, there's no problem with the Thrive Theme application because it connects via OAuth1 to Mautic v2.5.1 without any problems. 
The problem must be with Mautic v2.7.1 because that's where the OAuth1 connection fails with an "unknown error" 

That "report template" isn't really applicable here because to replicate you would need to install the Thrive Theme and it's not a free theme. So, "report template" doesn't apply here. 

But my guess is that you might be able to replicate it with ANYTHING that attempts to connect via OAuth1. However, that's just a guess. Because I don't use anything else that connects via OAuth1. 

Which means: 
**I DID provide (in that thread) all possible information about the issue I could get even though I wasn't following your template.** 
You closing the thread just shows that you don't really care. 
You don't really want to fix the problem. 

It now appears to me that Mautic is much more of a **bug bounty GAME** than an application intended for use in a production environment in business. The fact that this last version fixed 30 bugs doesn't automatically mean that it's ready for business. It is NOT! 

**And that pattern repeats with every single version of Mautic that comes out.** 
Every single version of Mautic that's released as "stable" is actually a **bug bounty GAME** and NOT fit for use in a production environment in business. UNLESS someone gets lucky and the few features they happen to use aren't affected by bugs in an immediately obvious manner. 

**I wonder how many people have Mautic installed in their production environment without being aware that it's broken? Could well be the majority of users. Can you prove that it's not?**

But hey, you totally have the right to create a game. If that's what you want. 
I was under impression that at some point in time this was meant to become an application for use in a production environment in business, but I must be mistaken.

**Comment by dongilbert** [comment]
Please refrain from opening issues that have a ton of words but provide no actual content. Closing this as it is a completely useless "issue" report.
