### ISSUE TITLE
Can't delete form submits

### ISSUE THREAD

**Issue by Rikk03** [mautic/mautic#3691]
What type of report is this:
| Bug report? | 

## Description:
Form submits can be viewed but not deleted.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 5.6 Fastcgi

### Steps to reproduce:
1. Try to delete a form submission.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Works for me. Any error in the logs?

**Comment by Rikk03** [comment]
looks like im missing files from installation .... redownloading source and copying across.

**Comment by escopecz** [comment]
I'll close this issue as it seems it's not a Mautic bug, but file transfer issue.
