### ISSUE TITLE
mautic email

### ISSUE THREAD

**Issue by nesrine22** [mautic/mautic#3692]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

when i send email to my email adress i dont recive it

**Comment by escopecz** [comment]
Closing this issue for lack of information. Comment bellow when you fill in all information in the issue template and I'll reopen it.
