### ISSUE TITLE
Email Search Doesn't Support Wildcards

### ISSUE THREAD

**Issue by Kyle-Foley** [mautic/mautic#3694]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
The clarification of segment search was greatly appreciated.

To make Mautic even better, would it be possible to change email search to function in the same way as segment search? Currently, when searching for a specific email, search operators such as wildcard % do not work.

For example, an email titled Staff | BillyBob | Post Phone Call

%Phone
will not work.

name:%Phone
will not work.

This is a clone of issue https://github.com/mautic/mautic/issues/3646 but for email, and without the wildcard solution.

**Comment by RCheesley** [comment]
Closing this issue down as the wildcard works using %phrase% in 2.16.1
