### ISSUE TITLE
Cron campaign:triggers getting process OOM killed (RAM)

### ISSUE THREAD

**Issue by zenzozen** [mautic/mautic#3695]
| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

| Q   | A
| --- | ---
| Mautic version | 2.5.1 and 2.7.1 (we updated)
| PHP version | 5.6.27-1+deb.sury.org~precise+1

## Description:
Cron campaign:triggers was raising RAM usage unlimited (like a loop error) and getting process OOM killed when got to 9GB usage in one specific campaign. 

`Out of memory: Kill process 710 (php) score 563 or sacrifice child
Killed process 710 (php) total-vm:8903736kB, anon-rss:8623848kB, file-rss:0kB`

We use this campaign structure since December ( stil using it ) but somehow this campaign was causing this. 

Workaround: We delete the campaign, limited 1gb to php scripts,  and it got back to normal.

### Steps to reproduce:
1. Create segment
2. Imported 14.000 contatcs
3. It was taking too long, so i canceled import. It imported 7.200
4. Created a campaign with this segment, 100% similiar with the structure of my other campaigns
5. Made a wrong filter in the segment that raised contacts to 230.000, and consequentely to the campaign
6. Mautic sent 230.000 emails as expected (took more than 24h)
7. I realized the problem and corrected the filters, so it went back to 7.200
8. After the correction, campaigns triggers cron got killed every time in this specifc campaign by OOM kill (raising used ram anormaly from  +-400mb to 9gb)
9. Deleted the campaign
10. Limited 1gb ram limit to the php scripts
11. Run crons
12. Everything got back to normal

### Log errors: 
I will update the post with log errors. There are many errors in the log.

**Comment by dbhurley** [comment]
Resolved in 2.12
