### ISSUE TITLE
Chat disables settings

### ISSUE THREAD

**Issue by brianteeman** [mautic/mautic#37]
As soon as you enable the chat integration it is impossible to access the settings - the hamburger icon just opens the chat. So not it appears that there is no method to even disable chat

**Comment by alanhartless** [comment]
Hey Brian,

With the chat enabled, the settings are moved to the "left" canvas of the right bar.  There's a cog wheel to the left of "Communication" that will take you there. We probably need a tooltip or something eh?

http://cl.ly/image/330b2Z322b0W

**Comment by brianteeman** [comment]
I can see the problems
1. On Mautic.com the language strings are missing so I didnt even know the arrows were there
2. Blue on Black is a colour combination that is very hard to read

![w0sj](https://cloud.githubusercontent.com/assets/1296369/5973700/4b73b56c-a863-11e4-84a3-72cb68dc40e5.png)

**Comment by alanhartless** [comment]
Ah; gotcha.  We've decided to move the chat addon out of the right sidebar.  It won't make it for beta4 but will be part of RC.

Thanks!
Alan
