### ISSUE TITLE
Hi {leadfield=firstname} 

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#370]
if firstname is empty the mail is like:

Hi {leadfield=firstname}

if firstname is "Will" the mail is like:

Hi Will

They dont work correctly when firstname is empty

**Comment by alanhartless** [comment]
Thanks for reporting this.  We'll investigate and get it resolved.

Thanks,
Alan

**Comment by alanhartless** [comment]
This has been fixed as part of PR #429.
