### ISSUE TITLE
[Language] Filter tooltip incorrect

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#3700]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The help text in the tooltip for the Segments filter is incorrect. 

At least the filters "is:active" and "is:inactive" do not work

"is:published" works but is not mentioned in the tooltip. 

I think the text "is:active" in the tooltip should be replaced by "is:published".

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0

### Steps to reproduce:
1. Go to Segments
2. Filter by "is:active" like it is suggested in the tooltip
3. No effect.
2. Filter by "is:published" works like a charm

**Comment by RCheesley** [comment]
Closing as no longer relevant.
