### ISSUE TITLE
Mailjet connection 

### ISSUE THREAD

**Issue by nesrine22** [mautic/mautic#3703]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.7.1
| PHP version | 5.6.30-0+deb8u1

### Steps to reproduce:
1. Configuration 
2. 
 
### Log errors: 

Failed to authenticate on SMTP server with username "n.makni@sykio.fr" using 1 possible authenticators
++ Starting Mautic\EmailBundle\Swiftmailer\Transport\MailjetTransport << 220 leela-11.mailjet.com ESMTP Mailjet >> EHLO mautic.ogust.com << 250-smtpin-leela-11.mailjet.com 250-PIPELINING 250-SIZE 15728640 250-VRFY 250-ETRN 250-STARTTLS 250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5 250-AUTH=PLAIN LOGIN DIGEST-MD5 CRAM-MD5 250-ENHANCEDSTATUSCODES 250 8BITMIME >> STARTTLS << 220 2.0.0 Ready to start TLS >> EHLO mautic.ogust.com << 250-smtpin-leela-11.mailjet.com 250-PIPELINING 250-SIZE 15728640 250-VRFY 250-ETRN 250-AUTH PLAIN LOGIN DIGEST-MD5 CRAM-MD5 250-AUTH=PLAIN LOGIN DIGEST-MD5 CRAM-MD5 250-ENHANCEDSTATUSCODES 250 8BITMIME >> AUTH LOGIN << 334 VXNlcm5hbWU6 >> bi5tYWtuaUBzeWtpby5mcg== << 334 UGFzc3dvcmQ6 >> bmVzcmluZQ== << 435 4.7.8 Error: authentication failed: UGFzc3dvcmQ6 >> RSET << 250 2.0.0 Ok

**Comment by escopecz** [comment]
This seems more like a configuration error: `authentication failed`.

Try to double-check the MailJet configuration. If you won't find anything wrong with it, try to share a screenshot of the configuration with MailJet support and if they won't be able to help you, post it here and I'll reopen this issue.

**Comment by tannguyen04** [comment]
@nesrine22 
I think you config email settings in Mautic not correct.
You should login and go to https://www.mailjet.com/account/setup, get user name (API key) and Password (Secret key) then you enter them to Email settings mautic. It's worked for me

**Comment by nesrine22** [comment]
thanks it working for me now! 
have an idea about how can i integrate webinair on mautic ?
thanks a lot for help !

**Comment by cmdntd** [comment]
Hi, I test with mautic v2.13.1. But it doesn't work with Mailjet API key now.
