### ISSUE TITLE
Bug - Email settings with SES or Mailjet failed to authenticate

### ISSUE THREAD

**Issue by didierhumbert** [mautic/mautic#3704]
Hi,

I've got a error message when I want to configure mailjet or Amazon SES in Emails settings:
Failed to authenticate on SMTP server with username "dhumbert" using 1 possible authenticators
++ Starting Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport << 220 email-smtp.amazonaws.com ESMTP SimpleEmailService-1868680137 rgpk5uMlEb7VBtpdVluX >> EHLO mautic.ogust.com << 250-email-smtp.amazonaws.com 250-8BITMIME 250-SIZE 10485760 250-STARTTLS 250-AUTH PLAIN LOGIN 250 Ok >> STARTTLS << 220 Ready to start TLS >> EHLO mautic.ogust.com << 250-email-smtp.amazonaws.com 250-8BITMIME 250-SIZE 10485760 250-STARTTLS 250-AUTH PLAIN LOGIN 250 Ok >> AUTH LOGIN << 334 VXNlcm5hbWU6 >> ZGh1bWJlcnQ= << 334 UGFzc3dvcmQ6 >> a2FkaW1hamVQT0wyMzU= << 535 Authentication Credentials Invalid !! Expected response code 235 but got code "535", with message "535 Authentication Credentials Invalid " (code: 535) >> RSET << 250 Ok

Any idea what's wrong ?
Thanks
Didier

**Comment by escopecz** [comment]
`Authentication Credentials Invalid` seems like a configuration issue. This comment can be applied here too: https://github.com/mautic/mautic/issues/3703#issuecomment-287366876
