### ISSUE TITLE
Upgrade Mautic from 2.5.1 to 2.7.1 in AWS

### ISSUE THREAD

**Issue by lerg57** [mautic/mautic#3705]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
Dear Sirs,
I installed mautic in AWS Thru Bitnami.

Trying to upgrade to Mautic from 2.5.1 to 2.7.1 my plan was:

1. Rename upgrade.php to upgradebak.php in this directory. Please see Image in: http://bit.ly/2mTN41h 
2. upload upgrade.php thru SFTP
3. execute upgrade.php4. 

But when I tried to upload I receive this msg: "access denied". Please see this image in: http://bit.ly/2mTK8C4 

I see that upgrade.php belongs to root and daemon. Should I try to change the ownership of the upgrade.php file first?

Please advise what to do.

Thanks

Luis R

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
yes

**Comment by awurman** [comment]
maybe with sudo?

**Comment by lerg57** [comment]
I Change the ownership and could run upgrade.php and all was ok. 
At the end I received this msg: Aplying migrations...failed (See image http://bit.ly/2na9IQE)
But There is no update errors log.

I logged into Mautic, 2.7.1 was installed and ran ok, But I can not see the Contacts
Please help.
Thanks 
Luis R

**Comment by escopecz** [comment]
Can you share a screenshot of your administration with missing Contacts?

**Comment by lerg57** [comment]
I click in Contacts and nothing happens.
In the System Info / Current Error Log appears this:
[2017-03-27 01:27:49] mautic.NOTICE: Symfony\Component\Debug\Exception\ContextErrorException: Warning: mkdir(): No such file or directory (uncaught exception) at /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php line 193 while running console command `doctrine:migrations:migrate`

**Comment by escopecz** [comment]
It sounds like a file permission issue

**Comment by lerg57** [comment]
Thanks for your help. Looks like I resolved it the simplest way. I just click upgrade in Mautic Dashboard and all is working fine. Great product!!!
I tried uploading upgrade.php and execute it. In the way I learned a lot about linux, php, SSH and something else. 
I really appreciate your help.
Thanks
Luis R
