### ISSUE TITLE
Stats of email is different from Campaign

### ISSUE THREAD

**Issue by lucasmoraes804** [mautic/mautic#3706]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I've created an email that is linked to only one campaign, and the campaign is linked only to that email, but the shipping statistics are diferente, like show images:
https://drive.google.com/open?id=0B5vQepyPPlAodkxsQ2x5OUlUWW8tV190MWoydUc0QXZuZlY4
https://drive.google.com/open?id=0B5vQepyPPlAoM2IxSnhpS0pKWjRrdGdCUkxEbV9VUk5VUm5j
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Okay, try change date range in campaign. 
You have selected stats until 17. 3.

**Comment by lucasmoraes804** [comment]
I discovered the problem. It's the same of [https://github.com/mautic/mautic/issues/3669](url)

**Comment by escopecz** [comment]
Ok. Closing this issue in favour of #3669
