### ISSUE TITLE
Email Builder in french language doesnt work

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#3708]
What type of report is this:

| Q  | A
| Q | ---
| Bug report? | Y
| Feature request? |  N
| Enhancement? |  N

## Description:
If you use Mautic in french  instead of english (i've not tested in other language). When you are using the builder to edit the mail with a template you can't edit a block to make a modification. 

## If a bug:

| Q   | A
| Q | ---
| Mautic version |  Y
| PHP version |  

### Steps to reproduce:
1.  put mautic in french
2. make a new mail with a template
3. try to edit one part of the mail with the builder
4. you see it's inpossible
5. make the same in english works fine

**Comment by npracht** [comment]
You may have a look on that documentation that helps to escape caracters in javascript injection http://api.symfony.com/2.8/Symfony/Component/Templating/PhpEngine.html#method_escape

Here is the line that is not working properly https://github.com/mautic/mautic/blob/master/app/bundles/CoreBundle/Templating/Helper/TranslatorHelper.php#L71

@escopecz, we had a look with @MaxWebmecanik but we couldn't find the way to use Symfony and make it working.

**Comment by tpilet** [comment]
Hello tx for your help guys. We modifiy the descrpition of the text in the file and he works now. Couls you add this modification in the next release?

**Comment by eng-sarah** [comment]
which file did you update desecration of the text in?

**Comment by jdecampos** [comment]
Same problem ... Did you find the solution?

**Comment by tpilet** [comment]
Yes 

 

You must change the text in the database

See the post 

 

De : jdecampos <notifications@github.com>
Répondre à : mautic/mautic <reply@reply.github.com>
Date : samedi, 8 avril 2017 à 11:12
À : mautic/mautic <mautic@noreply.github.com>
Cc : tpilet <thierry.pilet@newcom4u.ch>, Mention <mention@noreply.github.com>
Objet : Re: [mautic/mautic] Email Builder in french language doesnt work (#3708)

 

Same problem ... Did you find the solution?

**Comment by jdecampos** [comment]
Bonjour,
Merci pour votre réponse. Mais vous parlez de quel texte ?
Bien à vous,
Jérémy

**Comment by npracht** [comment]
@escopecz i think you can close that issue :)
