### ISSUE TITLE
Contacts Created Dashboard Widget doesn't show All contacts created under sub user roles

### ISSUE THREAD

**Issue by cdbessig** [mautic/mautic#3713]
What type of report is this:
 Bug report

## Description:
I imported a bunch of contacts via the csv import. I created a user role called Client.  I created a user and assigned to this role.  I logged in as this user.  The "contacts created" dashboard widget shows 0 contacts created.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |   2.7.1
| PHP version |  7.0.16

### Steps to reproduce:
I imported a bunch of contacts via the csv import. I created a user role called Client.  I created a user and assigned to this role.  I logged in as this user.  The "contacts created" dashboard widget shows 0 contacts created.
 
### Log errors: 

No log errors.

**Comment by escopecz** [comment]
You forgot to mention what permission the Client role have.

**Comment by gingerling** [comment]
I also find my main dashboard contacts created is zero. I have 1645 contacts in total, most of them were imported, which would be as described in this bug, however an additional 40 were recently created via a form in kiosk mode at an event, and these are not showing on the main dash graph either. They are shown on the campaign page in blue on the graph as "contacts added". My mautic instance has one user, which is me, and I am an Admin. I use mautic.net service.

**Comment by escopecz** [comment]
Please check if the contacts weren't created before the date range filter.

**Comment by gingerling** [comment]
![screenshot from 2017-04-13 13-43-25](https://cloud.githubusercontent.com/assets/2853040/25005066/4471dbfc-204f-11e7-9268-d04c89672c29.png)

![screenshot from 2017-04-13 13-43-11](https://cloud.githubusercontent.com/assets/2853040/25005071/4aed2284-204f-11e7-9380-5be717aeefc8.png)

Here are the examples, date range okay. Actually so far I haven't got any contacts on my dash on either of my installs (both mautic.net)

**Comment by escopecz** [comment]
Based on the screenshots you shared, the contacts were added to the campaign on Apr 1 which is not in the date range filter in the Dashboard filter. And the contact created date can be different than contact added to a campaign date. Do you have some data somewhere in your Mautic which would confirm there were some contacts added during the date range in the dashboard? Maybe the reports show some data?

**Comment by gingerling** [comment]
Date range is March 14 to April 13 which covers April 1st. The rest of my contacts (excluding those new ones which may/may not have been added via the campaign, were created on March 27, 2017. My account is pretty new, all my contacts were added between 14 March and today.

**Comment by escopecz** [comment]
Yes, I can see Apr 1 in the chart where are some data, but not in the screenshot of dashboard which we are talking about here. Could you share a screenshot of the contact detail page which has written in the timeline that the contact was created in the date range in your dashboard screenshot?

**Comment by gingerling** [comment]
Oh, I see the issue now. The date range From: and To: at the top of the chart shows the past 30 days or so by default when I go to my dash, however it is not actually applied to the table. If you click the Apply button it shows the correct data as expected. I hadn't really noticed the numbers at the bottom of the chart, which I assume are the dates you were referring to? In piwik and google analytics and, well, I would say most apps I use, the from and to at the top of the page both match the data below (acting as a heading or summary) and also can be used to change what data shows in the table. Here it just does the second. I will make a separate bug report.

**Comment by cdbessig** [comment]
Hello,

Thank you for your email. Please note,I will be out of the office April 13th with limited to ZERO email access, As such responses may be delayed or possibly not responded to until after my return. If you require an immediate support team response during that time, please reach out to the below contact.

For all support issues, please contact: 

support@creatingdigital.com 
Phone 201-475-1288

For account management:
Damian Gonzalez
dgonzalez@creatingdigital.com
201-475-1288


Thank you for your understanding.

**Comment by gingerling** [comment]
Here is new bug https://github.com/mautic/mautic/issues/3856

**Comment by gingerling** [comment]
@escopecz - not sure if this should be closed, the guy who reported it is someone other than myself. It sounds like maybe the same issue, however, it is possible it's unrelated as he is talking about a second user I think?

**Comment by escopecz** [comment]
Thanks for the note, I can always reopen when the original author will provide the requested info.

**Comment by cdbessig** [comment]
Is there a php bin/mautic command for printing a users permissions, or a db table to grab them from?  It seems like a lot to screen grab the perms screens or retype them.  I can do that if that's the only way, but wondering if there is a better way!
