### ISSUE TITLE
Filter segments by select-multiple custom field

### ISSUE THREAD

**Issue by coffeverton** [mautic/mautic#3717]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
I have a custom field which is a select-multiple type. It is named "tipo_pessoa".
In this field, I have two options. In these options, the "label" is different from the "value":
Label | Value
Pessoa Fisica | PF
Pessoa Juridica | PJ

Then, I create a segment to separate these 2 types of leads, creating a filter based on this custom field. The type of the filter is "equals", and I select the "label" of one of the two options (Pessoa Fisica).

After this, i run the cronjob to update segments, but the segment shows 0 contacts.

But i found that if i update the leads table, manually setting the "tipo_pessoa" field to the label (instead of the value), then the segments filter works.
Example: I took one lead that has the "tipo_pessoa" field with the value "PF", and i change it to "Pessoa Fisica" (which is the label, not the value), then the segment filter works.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.30

### Steps to reproduce:
1. Create a custom field of select-multiple type. Use 2 (or more) different options, but setting the "label" different from "value".
2. Create a segment to filter one of these 2 types. The segment filter type is "equals", and the value is one of the ones from the custom-field created above.
3. Run the cronjob to update segments. No contact get updated.
4. Update manually the lead table, setting the custom-field value to the "label", instead of the "value".
5. Run again the cronjob to update segments. This contact is added to the segment.
 
### Log errors: 

There are no errors logged.

**Comment by alanhartless** [comment]
Fixed as part of #3719

**Comment by jordan8037310** [comment]
I still have this issue in 2.8.1. Can we reopen?

**Comment by escopecz** [comment]
Actually, could you retest with 2.8.2?

**Comment by jordan8037310** [comment]
I'll test that now

**Comment by jordan8037310** [comment]
Cannot upgrade to 2.8.2, there is an error on upgrade with composer install:

```
[RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Ar
  gument 1 passed to Mautic\PluginBundle\Helper\IntegrationHelper::__construct() must be an instan
  ce of Symfony\Component\HttpKernel\Kernel, instance of Mautic\CoreBundle\Factory\MauticFactory g
  iven, called in /var/www/vhosts/mydomain.com/httpdocs/cache/prod/appProdProjectContainer.php
   on line 10183 in /var/www/vhosts/mydomain.com/httpdocs/web/app/bundles/PluginBundle/Helper/
  IntegrationHelper.php:87
  Stack trace:
  #0 /var/www/vhosts/mydomain.com/httpdocs/cache/prod/appProdProjectContainer.php(10183): Maut
  ic\PluginBundle\Helper\IntegrationHelper->__construct(Object(Mautic\CoreBundle\Factory\MauticFac
  tory))
  #1 /var/www/vhosts/mydomain.com/httpdocs/web/vendor/symfony/dependency-injection/Container.p
  hp(314): appProdProjectContainer->getMautic_Helper_IntegrationService()
  #2 /var/www/vhosts/mydomain.com/httpdocs/web/plugins/MauticCitrixBundle/MauticCitrixBundle.p
  hp(26): Symfony\Component\DependencyInjection\Container->get( in /var/www/vhosts/obd.carcare.new
  s/httpdocs/web/app/bundles/PluginBundle/Helper/IntegrationHelper.php on line 87
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalErrorException: Error: Uncaugh
  t Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Mautic
  \PluginBundle\Helper\IntegrationHelper::__construct() must be an instance of Symfony\Component\H
  ttpKernel\Kernel, instance of Mautic\CoreBundle\Factory\MauticFactory given, called in /var/www/
  vhosts/mydomain.com/httpdocs/cache/prod/appProdProjectContainer.php on line 10183 in /var/ww
  w/vhosts/mydomain.com/httpdocs/web/app/bundles/PluginBundle/Helper/IntegrationHelper.php:87
  Stack trace:
  #0 /var/www/vhosts/mydomain.com/httpdocs/cache/prod/appProdProjectContainer.php(10183): Maut
  ic\PluginBundle\Helper\IntegrationHelper->__construct(Object(Mautic\CoreBundle\Factory\MauticFac
  tory))
  #1 /var/www/vhosts/mydomain.com/httpdocs/web/vendor/symfony/dependency-injection/Container.p
  hp(314): appProdProjectContainer->getMautic_Helper_IntegrationService()
  #2 /var/www/vhosts/mydomain.com/httpdocs/web/plugins/MauticCitrixBundle/MauticCitr in /var/w
  ww/vhosts/mydomain.com/httpdocs/web/app/bundles/PluginBundle/Helper/IntegrationHelper.php on
   line 87```

**Comment by jordan8037310** [comment]
Did anyone else successfully test the associated PR with mismatching Label/values?

**Comment by jordan8037310** [comment]
The ability to use multiselect filters was fixed for me by #4097 on 2.8.1

**Comment by nicola883** [comment]
I am running the 2.9.1 version. 
I'm still having the same problem. 
Everything works with the same string for Label and Value.
The contacts are not added in segments if Label and Value are different in the custom field definition.

**Comment by escopecz** [comment]
Please test it on 2.9.2 released today. It contains several segment fixes. If it still won't be working for you, I'll re-open.

**Comment by nicola883** [comment]
I have just upgraded to 2.9.2 version. I have still the same problem. Thank you.

**Comment by kuzmany** [comment]
Let's try test: https://github.com/mautic/mautic/pull/5533

**Comment by mleffler** [comment]
This will be part of 2.13
