### ISSUE TITLE
auto fill on progressive forms dones't fill email or select fields

### ISSUE THREAD

**Issue by Jo-Pitts** [mautic/mautic#3720]
What type of report is this:

| Q  | A
| Bug report? | 

Description:
When using a progressive form, email and select type fields aren't auto-filled.  This may extend to other field types.  As far as I can tell, only text fields are getting auto-filled.

If a bug:
| Q   | A
| Mautic version | 2.7.1
| PHP version | 5.6.28

**Comment by escopecz** [comment]
Email will be added to progressive profiling in 2.9.0. The select fields should be fixed by now.
