### ISSUE TITLE
SMS Do Not Contact ignored

### ISSUE THREAD

**Issue by serviantalend** [mautic/mautic#3721]
Bug report

## Description:
In a similar approach to email unsubscribe, we wanted to implement sms unsubscribe.

We have created a custom plugin to Mautic which adds leads to "lead_donotcontact" with channel set to "sms". This is triggered via a webhook callback from Twillio to the Mautic plugin when Twillio receives a message from a targeted mobile. It also tags leads with "SMS Unsubscribe".

| Mautic version | 2.7.1
| PHP version | 7.0.15-0 ubuntu 0.16.04.4

### Steps to reproduce without the custom plugin:
1. insert a record into lead_donotcontact with an active lead id, channel=sms and reason=1 (lead must have a valid mobile number)
2. create a campaign to target the "sms unsubscribed" lead with a text message
3. update/trigger campaign
4. observe how mautic appears to not check the do not contact table prior to attempting to deliver the text via Twillio
 
### Log errors: 
No log errors observed.

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
I'm not sure how to deal with this issue. Will you publish your plugin? Or send it as a pull request? Or do you want someone else to build the same functionality you have into core?

**Comment by nebev** [comment]
Hey.
The plugin in question is at: https://github.com/nebev/mautic-sms-reader
It's my first Mautic plugin, so it's entirely possible it's horrible and doing things the wrong way.

It's also possible I've misunderstood the idea of the `lead_donotcontact` table, but I've seen this line in `bundles/SmsBundle/Helper/SmsHelper.php` in the `unsubscribe` function (although for the life of me, I can't see where that function is called).

```
return $this->leadModel->addDncForLead($lead, 'sms', null, DoNotContact::UNSUBSCRIBED);
```

This ends up putting in a record in the `lead_donotcontact` table. An example is:

| id | lead_id | date_added          | reason | channel | channel_id | comments                         |
|----|---------|---------------------|--------|---------|------------|----------------------------------|
| 2  | 1       | 2017-03-21 13:15:25 | 1      | sms     | NULL       | Unsubscribed via Twillio Webhook |

However, when a campaign is triggered, the lead still gets contacted (an SMS is sent to them). I think the assumption was that an entry for the appropriate channel in the DNC tables means that the lead does not get contacted.

When I put in a similar record, but using `email` as the channel, leads do not appear to get emailed. Am I right in assuming SMS supposed to work in the same manner?

**Comment by escopecz** [comment]
Ok. The bug is clear to me now. Thanks for the explanation.

**Comment by mikerowe81** [comment]
I don't know if this is the same bug, but the subject seems to apply. Even after a contact is set to "Do Not Contact" for the "sms" channel they are still being sent SMS messages from campaigns. This is VERY BAD!

Steps to reproduce:
1. Uncheck the "Text Message" channel in a contact's preferences. (or via API: $contactApi->addDnc($id, 'sms');)
2. Create a campaign that includes that contact and sends a text message.
3. Contact gets text message.

Expected Result:
3. Contact does NOT get text message. 

I am running v2.11.0
Here's a screenshot showing the contact set to DNC and then getting the text message from a campaign that was created after they were set to DNC.

![smsdnc](https://user-images.githubusercontent.com/3849143/33103654-7f322642-cef1-11e7-8ffa-2605df36dca7.png)
