### ISSUE TITLE
Memory Limit Exceeded Error

### ISSUE THREAD

**Issue by devadattas** [mautic/mautic#3724]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Whenever I create a new role with access to viewown Leads and no access to viewothers on segments and visit "s/segments" using the new role it gives the following error in my php log:

    *938 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 201326592 bytes exhausted (tried to allocate 130968 bytes) in app/bundles/CoreBundle/Helper/SearchStringHelper.php on line 226" while reading response header from upstream, client: 0.0.0.0, server: example.com, request: "GET /s/segments HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5.sock:", host: "example.com"

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.3

### Steps to reproduce:
1. Create a new role named "User"
2. Setup the permissions with no Segment permissions checkboxes checked, but Contact Permissions with "View Own", Create and Delete.
3. Go to "s/segments"
 
### Log errors: 

    *938 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 201326592 bytes exhausted (tried to allocate 130968 bytes) in app/bundles/CoreBundle/Helper/SearchStringHelper.php on line 226" while reading response header from upstream, client: 0.0.0.0, server: example.com, request: "GET /s/segments HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5.sock:", host: "example.com"

**Comment by tcanani** [comment]
This resolved the segments visualization issue, but i've experienced a little problem after this. I have a campaign where i must have a segment as a condition for the automation to go forward, but as this segment can no longer be global, it doesn't appear in the campaign's decision option. Anybody has this problem also?
