### ISSUE TITLE
Error Shown when creating new Segment with users without viewother segments permissions

### ISSUE THREAD

**Issue by devadattas** [mautic/mautic#3727]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
We get an error when we are visiting "s/segments/new" using a new user who does not have "viewother" segment permissions.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.3

### Steps to reproduce:
1. Login using an user which does not have "viewother" segments permission
2. Go to "s/segments/new"
3. Gives a 500 Server Error
 
### Log errors: 

`PHP message: PHP Fatal error:  Call to a member function getUser() on null in app/bundles/EmailBundle/Entity/EmailRepository.php on line 325`

**Comment by escopecz** [comment]
Fixed in 2.7.1
