### ISSUE TITLE
Add ability to map company field to form field

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3729]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | x

## Description:
When you create you form fields, in the "contact field" tab, you don't have the ability to save the data in a company field. Which could be very useful for the industry, language, and many other company custom fields.

## Suggestion:

- Modify the tab name from `Contact field` --> `Field mapping`
- Keep the dropdown for `Contact fields list`
- Add a dropdown for `Company fields list`

**Comment by YannickBiet** [comment]
+1, currently we need to say customer to create any custom fields on the contact even for number of employees or industry dropdown as they wanted to keep that on the company screen. Else they will never be able to fill in the data "automatically"

**Comment by escopecz** [comment]
Implemented in https://github.com/mautic/mautic/pull/4660
