### ISSUE TITLE
Add option to delete form submissions

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#373]
Feature request. 

For clean results or remove duplicates etc.

![image](https://cloud.githubusercontent.com/assets/10166840/7488235/954ea872-f3c7-11e4-9e84-73eb064de98f.png)

**Comment by arcmedia-it** [comment]
Hi, how can this feature be used?
I don't see it as a campaign action. 
I'd like to reset al the submitions of a contact in a form. 
Is this the purpose of this feature or am I mixing things up?
Thanks in advance
