### ISSUE TITLE
Mautic mtc.js file is not found - 404 is thrown

### ISSUE THREAD

**Issue by VijayWilson** [mautic/mautic#3730]
We have placed the tracking js in our local site to check how it works.
                      ` 
                        (function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
				w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),
				m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)
			})(window,document,'script','http://localhost/mautic/mtc.js','mt');

			mt('send', 'pageview');`

When the local site runs "NetworkError: 404 Not found - http://localhost/mautic/mtc.js" is thrown in console.
Similarly there is no mtc.js file in mautic. We are new to mautic system. Do we need manually add the mtc.js file or will it be embedded during the run time. Kindly help us through this.

Server: Apache

**Comment by escopecz** [comment]
The mtc.js file is generated by PHP, so you won't find it in the filesystem. Since it's on your localhost, we cannot check where the problem could be. Try to put your Mautic to a public URL and we can tell you more. I'll close this issue since there is nothing we can do to help.

**Comment by VijayWilson** [comment]
Thank you for your immediate response. Like you said, We have updated the url to our development server and it did'nt throw the "404" error. But it throws    **Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://mautic.service.develag.com/mtc/event. (Reason: CORS header 'Access-Control-Allow-Origin' missing).** So I have added the localhost domain in mautic Configuration->CORS setting. But still **Cross-Origin Request Blocked** is being thrown. Is that because of **localhost** domain ?

**Comment by JohnConnell** [comment]
@VijayWilson Sounds like you have X-Frame-Options set to SAMEORIGIN on the server running Mautic.

In Nginx, look for this line: `add_header X-Frame-Options "SAMEORIGIN";`
In Apache, look for this line: `Header always append X-Frame-Options SAMEORIGIN`

Comment the line out, reload the web server, and try again.
