### ISSUE TITLE
Focus Items with forms

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#3736]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I prepare a simple forms just with email as a attribute.
I prepare a focus items (style is not relevant)

when is ready integrate the javascript code proposed in my website

## If a bug:
The focus come regarding the paramater i give.
You can capture the mail but when you validate the text of the button is remplaced by please wait....  
but you can wait hours.

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 

### Steps to reproduce:
1. already describe
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Please check if there is some PHP error (https://mautic.org/docs/en/tips/troubleshooting.html) and if there is some Javascript error. (Press F12 on Win/Unix or Option+Command+I on Mac, navigate to Console tab and then try to submit the form)

**Comment by escopecz** [comment]
I'll close this issue as the question hasn't been answered for a while. I'll re-open when it does.
