### ISSUE TITLE
Cant write url or edit html in "Download message"

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#374]
Version 1.0.5

steps to reproduce error:
1.- Create form
2.- add one action is: donwload asset
3.- edit Download message, select a text and trie to hiperlink it (or trie to edit html) 
 

![image](https://cloud.githubusercontent.com/assets/10166840/7491773/38a5b252-f3ed-11e4-9217-325dc7a1d52f.png)

**Comment by alanhartless** [comment]
Hi Miguel,

The fix is in the link above (#388) and will be part of the next release.

Thanks,
Alan
