### ISSUE TITLE
Store multi select values in contact field

### ISSUE THREAD

**Issue by publidex** [mautic/mautic#3741]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I created a multi select field and assign to an form, but i noticed that when you select more than one value, the Mautic does not store the data in the contact field and i can not see this in the contact view page.
I can only see on the form results page.

Now when i select only one value, i can see the data in the contact view page.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 5.6

### Steps to reproduce:
1. Create an multi select custom field 
2. Go to an form, create an checkbox field and mapping to custom field created
3. Try to send any data
 
### Log errors: 
Nothing in log file

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by legroen** [comment]
We have the same issue. Can somebody help me out here? We're waiting to send +20000 emails because of this bug. I tried myself but i'm lost in the code at some point.

**Comment by npracht** [comment]
Hi, we're currently working on it with @MaxWebmecanik from @webmecanik

**Comment by jordan8037310** [comment]
I just tested the associated PR in #4109 and looks good (for those of you who are waiting for a fix)

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Please, close. Merged https://github.com/mautic/mautic/pull/4109
