### ISSUE TITLE
select fields in segments - country

### ISSUE THREAD

**Issue by igisho** [mautic/mautic#3745]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | 
| Enhancement? | 

## Description:
When you creating segment and you pick Country filter there is option to create regex but the select field not changes to text field so you cant really use regex feature. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.15

### Steps to reproduce:
1. open segments
2. create new segment
3. in filters pick country
4 pick regex or not regex or like or any other option
 
### Log errors: 

none

**Comment by npracht** [comment]
Globally the matching of input depending on the filter type is often broken in Segments and in Campaigns.
## Example
In campaign, add a condition and if you select **empty (vide)** for a select type field, you still have a input value after??...

![campagnes](https://cloud.githubusercontent.com/assets/14075239/24284783/4c7a65c2-106d-11e7-9258-51e66b426710.PNG)

**Comment by mrerich** [comment]
The same bug in decisions in campaings - when you select for example country or preffered locale and the empty or not empty operator, it still shows the active value field and also save it to the database.

![screenshot 2017-04-26 10 27 29](https://cloud.githubusercontent.com/assets/26136473/25425098/0f7e6b74-2a6b-11e7-9b8c-351571944266.png)

**Comment by vexersa** [comment]
Any update on this bug? 
It would be very useful for GDPR segmentation?

**Comment by necobm** [comment]
Any update on this bug? I'm using 2.13.1 mautic version and can't filter leads by country field in campaings decitions, using regex, it doesn't work.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by namratasaun** [comment]
![image](https://user-images.githubusercontent.com/35791871/115230686-50257180-a132-11eb-8322-ab5293303a1b.png)

I have a field of type Number and when I try to use regex as a filter, I am not able to type a string as I am only able to type a number here.
