### ISSUE TITLE
regex feature in seegment field - Visited URL

### ISSUE THREAD

**Issue by igisho** [mautic/mautic#3746]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | 
| Enhancement? | 

## Description:
When you creating segment and you pick Visited URL filter there is option to create regex but regex is not working. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.15

### Steps to reproduce:
1. open segments
2. create new segment
3. in filters pick Visited URL
4. pick regex or not regex or like or any other option
5. vrite simple regex:  something | sometingelse
 
### Log errors: 

none

**Comment by dbhurley** [comment]
Works in 2.12
