### ISSUE TITLE
Dashboard charts incorrectly show 0 returning visitors

### ISSUE THREAD

**Issue by Section9Bateau** [mautic/mautic#3750]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Dashboard charts (and possibly others) in Mautic are not showing any returning visitors.  Looking at the SQL queries sent to our MySQL server and the code, it appears this is due to an error in the call to modifyCountQuery in app/bundles/CoreBundle/Helper/Chart/ChartQuery.php passing the wrong parameters (the documentation says it should be pased an array for options, but the call from getCountQuery above it is passing the $dateColumn instead of $options.)

I'm not much of a php programmer, but my quick attempts to fix it by changing the call to be $this->modifyCountQuery($query, $uniqueColumn, $options, $tablePrefix); result in errors such as:
mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT COUNT(t.lead_id) AS count FROM (SELECT t.lead_id FROM page_hits t GROUP BY t.lead_id HAVING COUNT(*) = 1) t WHERE t.date_hit BETWEEN ? AND ?' with params ["2017-01-13 00:00:00", "2017-02-08 23:59:59"]:  Unknown column 't.date_hit' in 'where clause'"

From a SQL perspective I would have expected the SQL to be SELECT COUNT(distinct t.lead_id) AS count FROM page_hits t WHERE t.date_hit BETWEEN :dateFrom AND :dateTo as it is structured by that function, allowing the SQL server to optimize it, instead of trying to do a groupby.  This may give better results while fixing it, but I'm unsure how to implement this to provide a patch.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.7.0
| PHP version |   5.6.29-0+deb8u1

### Steps to reproduce:
1. Have a contact visit a page tracked by Mautic more than once
2. Check the dashboard, this visit will show as unique, not repeat.

**Comment by escopecz** [comment]
The dashboard charts have a time cache. That means the new stats can appear after several minutes. Try to go to the configuration and set the dashboard cache to 0. This way you should get the latest results without using the cache (it can result in slower page load). Are the values still missing? Does some returning visit in the page_hits table for the time period you have filtered in the dashboard date range filter?

**Comment by igisho** [comment]
same for me here

**Comment by escopecz** [comment]
I'll close this issue as the question hasn't been answered for a while. I'll re-open when it does.

**Comment by Woolgoose** [comment]
Tried it with dashboard cache set to 0 and emptying cache but same result. No returning visitors visible.

I don't know if I understand this question:
Does some returning visit in the page_hits table for the time period you have filtered in the dashboard date range filter?

If you mean if page visits get tracked in the History tab of a contact the answer is yes.
