### ISSUE TITLE
Saving and closing on email settings messed up local.php

### ISSUE THREAD

**Issue by ulc** [mautic/mautic#3752]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:

Under configuration> email settings
I enabled Use Custom connection settings under bounces and configured it. When I clicked save and close I the web interface became non-responsive. (the loading gauge just continued to signal that it was loading)

After some digging I found out that the file app/config/local.php had been messed up.
Most notably "=> 'http://www.yyy.zzz.xxx:80/mautic/', had been injected in the end of maybe 10 lines through out the file.
also some lines had the closing " replaced with '.
and lastly some of my urls had .com replaced with _url.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.5.1
| PHP version | 5.6.29

### Steps to reproduce:
1. Set up Monitored Inbox Settings
2. Enable Use custom connection settings and use the same settings as in 1.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 
/opt/bitnami/apps/mautic/logs is empty

[local.php.txt](https://github.com/mautic/mautic/files/868089/local.php.txt)
[mautic.log.txt](https://github.com/mautic/mautic/files/868090/mautic.log.txt)

**Comment by dbhurley** [comment]
Resolved
