### ISSUE TITLE
Upgrading from 2.5.1 to 2.7.1

### ISSUE THREAD

**Issue by lerg57** [mautic/mautic#3754]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Upgrading
| Feature request? | 
| Enhancement? | 

## Description:
Dear Sirs,
I installed Mautic in AWS thru Bitnami. 
Trying to upgrade Mautic 2.5.1 to 2.7.1 thru SSH using php upgrade.php I received this msg: http: //bit.ly/2mZ1aLQ

This is the error file I get: http://bit.ly/2mZ3tOI 

I'll appreciatte if you let me know what I did wrong

Thanks

Luis R

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 

### Steps to reproduce:
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
It seems like a file system permission issue. Consult it with someone who knows AWS better or if it has some support, ask them. The error is not related to Mautic. But let us know how if you'll make some progress. I'll close the issue for now.
