### ISSUE TITLE
[bug] SQL for get the non-action log may be incomplete

### ISSUE THREAD

**Issue by kkoba964** [mautic/mautic#3758]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |X 
| Feature request? | 
| Enhancement? | 

## Description:

Share places where there is a possibility of mistakes.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |2.6.1 
| PHP version |5.6.30 

FileName is
 /app/bundles/CampaignBundle/Entity/EventRepository.php

Function Name is
 public function getEventLog($campaignId, $leads = [], $havingEvents = [], $excludeEvents = [], $excludeScheduledFromHavingEvents = false)

Line 469. Is there a bug?

I think
  $eventsQb->andHaving(...
is an error,
I think that 
  $q->andHaving(...
is correct,
How about that?
(Otherwise it will not be reflected in SQL)

**Comment by escopecz** [comment]
I think you're right. Could you send a pull request with your fix?

**Comment by kkoba964** [comment]
Thank you for your reply.

I'm sorry, I'm not used to github, I do not know how to use it.
It seems that it will take time for me to work.
(This time I downloaded the source code and watched it directly.)

I could not judge whether it was a bug,
SQL generated by this function,
In the SQL Exist clause seems to be referring not only to the campaign being processed but also to the log of irrelevant campaigns.
Is this a specification?
(If the amount of the whole log increases, SQL processing time will be longer.)

**Comment by RCheesley** [comment]
Closing this issue as it's super outdated and no longer present in the code.
