### ISSUE TITLE
Smart list filters not working on text custom field

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#376]
I've got a smart filter which is using a text-based custom field containing the source.

I imported a bunch of leads, copied the value from the source field, and created a smart list using = <copied value>.

This did not result in any leads being associated with the list.

When I then tried using 'LIKE' instead of '=' I have the same problem.  If I set it to 'Not Empty' then still nothing.

Guess something is broken!  Using 1.0.5 new install.

**Comment by drmmr763** [comment]
Hi Ruth

So with lists we actually have changed things to now require a cron to get leads up to date. Have you configured the cron to run? 

Check out the announcement for more info on what is necessary:
https://www.mautic.org/community/index.php/324-1-0-4-released

**Comment by RCheesley** [comment]
Thanks Chad, no indeed I had not seen this - I'm surprised there isn't anything about it when you create your first list - would that be a helpful thing to do, to alert folk that they need to set up the cron jobs (for those who don't read the documentation!) in order for them to work?

**Comment by RCheesley** [comment]
Thanks, this sorted it out once I added the cron jobs.
