### ISSUE TITLE
Cannot use > in Button Text

### ISSUE THREAD

**Issue by cdbessig** [mautic/mautic#3761]
What type of report is this:
 Bug report

## Description:
Use the Builder tool to create an email.  Enter "Learn more >" as the button text.  Close the builder and send a sample email.  You will see that the > is closing the container div and a bunch of extra data attributes have now become text inside the email.

## If a bug:

 Mautic version 2.5.1
7.0.12

### Steps to reproduce:
See above.

**Comment by dbhurley** [comment]
No longer an issue 2.12

**Comment by cdbessig** [comment]
Hello,

Thank you for your email. Please note, during the holidays I am traveling and have an extended OOO schedule.

Please see the below schedule:

12/29 - OOO
1/2 - OOO
1/3 - WORKING - book a time here: https://securedatatransit.youcanbook.me/ 
1/4 - OOO
1/5 - OOO

If you wish to book a call with me on 1/3, you can use the following link to schedule a time: https://securedatatransit.youcanbook.me/  If you are a sales rep hoping to do business with us, please do not book a time, please follow up with me upon my return.

During my days out of the office, I will have limited or ZERO access to email and phone.  If you require an immediate response, please reach out to the general support email.  Otherwise, I will answer your request as soon as possible.

General Support / Technical Issues
support@creatingdigital.com
Phone 201-475-1288

Thank you for your understanding.
