### ISSUE TITLE
Typo matuic instead of mautic

### ISSUE THREAD

**Issue by mtahiue** [mautic/mautic#3762]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
https://github.com/mautic/mautic/search?utf8=%E2%9C%93&q=matuic&type=

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.0
| PHP version | All

### Steps to reproduce:
1. 
```
www/app/bundles  # grep -ri matuic *

CampaignBundle/CampaignEvents.php:    const ON_EVENT_DECISION_TRIGGER = 'matuic.campaign_on_event_decision_trigger';
CampaignBundle/CampaignEvents.php:    const ON_EVENT_SCHEDULED = 'matuic.campaign_on_event_scheduled';
FormBundle/FormEvents.php:    const ON_EXECUTE_SUBMIT_ACTION = 'matuic.form.on_execute_submit_action';
```

2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by AndrassGray** [comment]
One more (at least in my 2.9.2 : 
`$ grep -ir "'m.....\.form" | grep -v mautic
bundles/FormBundle/Config/config.php:            'muatic.form.type.field_propertypagebreak' => [
`
