### ISSUE TITLE
Wrong info in Campaign Chart after 2nd send of emails

### ISSUE THREAD

**Issue by Getron** [mautic/mautic#3763]
| Bug report? |  Yes

## Description:
Please look at the images, i have set an Capaign. It works well with first email sending, but, on the 2nd emails sending, it shows wrong info in the chart, should showing "Email sended", and not "Email opened", like you see, it is just 11% of emails opened, but the chart show wrong color and wrong info point on the top of 2nd spike. I have about 128 contacts in total.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.7.1
| PHP version |  7.0.13-1~dotdeb+8.1

### Steps to reproduce:
1. Create a Campaign, like in my image, with 2 or more sendings to segments
2. Wait for sending the 2nd emails
3. The spike shows wrong color and wrong info of the 2nd sendings
 
![auswahl_394](https://cloud.githubusercontent.com/assets/5913218/24392230/364c7366-1393-11e7-8c87-87777c4112bf.png)
![auswahl_393](https://cloud.githubusercontent.com/assets/5913218/24392231/364cd2a2-1393-11e7-897d-70db771ec60e.png)

**Comment by npracht** [comment]
We noticed the same

**Comment by npracht** [comment]
Fixed in 2.8.1 with https://github.com/mautic/mautic/pull/4010
