### ISSUE TITLE
SQL for get the non-action log Refer to unrelated Campaign.

### ISSUE THREAD

**Issue by kkoba964** [mautic/mautic#3767]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |X 
| Feature request? | 
| Enhancement? | 

## Description:

Share places where there is a possibility of mistakes.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |2.6.1 
| PHP version |5.6.30

FileName is
/app/bundles/CampaignBundle/Entity/EventRepository.php

Function Name is
public function getEventLog($campaignId, $leads = [], $havingEvents = [], $excludeEvents = [], $excludeScheduledFromHavingEvents = false)

Because it took time to call this function, I dumped SQL.
Mautic was executing the following SQL.

The SELECT statement in the Exist clause, Not Exist clause
seems to refer to the data of unrelated all campaigns.
(In following SQL. This is the place where [BUG?] Is stated.)

For the SELECT of the subquery, I also need to add the Campaign ID to the WHERE clause.
What do you think?

---SQL begin---
```
SELECT
    e.lead_id,
    e.event_id,
    e.date_triggered,
    e.is_scheduled
FROM
    ma_campaign_lead_event_log e
WHERE
    (e.campaign_id = 1) AND
    (EXISTS (
            -- [BUG?] Need to restrict by Campaign ID??
            SELECT
                null
            FROM
                ma_campaign_lead_event_log include_leads
            WHERE
                (include_leads.lead_id = e.lead_id) AND
                (include_leads.lead_id IN (11, 12, 13, 14, 15, 16, 17, 18, 19, 20))
        )
    )
GROUP BY
    e.lead_id,
    e.event_id,
    e.date_triggered,
    e.is_scheduled
HAVING
    (EXISTS (
      -- [BUG?] Need to restrict by Campaign ID??
      SELECT null FROM ma_campaign_lead_event_log include_events WHERE (include_events.lead_id = e.lead_id) AND (include_events.event_id IN (2)) AND (include_events.is_scheduled = 0))
    ) AND
    (NOT EXISTS (
      -- [BUG?] Need to restrict by Campaign ID??
      SELECT null FROM ma_campaign_lead_event_log exclude_events WHERE (exclude_events.lead_id = e.lead_id) AND (exclude_events.event_id IN (14))
      )
    )
```
---SQL end---

**Comment by escopecz** [comment]
Since the event_id is unique across all campaigns, the campaign_id should not play any role in it. But will it be faster with campaign_id restriction? That I cannot tell without trying it out and measuring the time of execution before and after. Will you be able to measure the time improvement with your suggestion?

**Comment by kkoba964** [comment]
Thank you for your comment.
For the Exist clause of the Having clause, Your opinion is correct.

As a specification of mautic, I believe that it is correct not to refer to data from other campaigns.
However, In the first appearing WHERE clause

`            SELECT
                null
            FROM
                ma_campaign_lead_event_log include_leads
            WHERE
                (include_leads.lead_id = e.lead_id) AND
                (include_leads.lead_id IN (11, 12, 13, 14, 15, 16, 17, 18, 19, 20))`

This is a search that also includes data from other campaigns, 
and my performance has been degraded in my environment.

**Comment by escopecz** [comment]
Campagins were rewritten in 2.14.0. Please test with the latest version.
