### ISSUE TITLE
Condition values reset to default in campaign builder

### ISSUE THREAD

**Issue by ademenev** [mautic/mautic#3768]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
In campaign builder, when building a condition, condition value selected from list is reset to the first value from list when you later edit the condition.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.7.1, I guess 
| PHP version | not sure

(using demo site at mautic.net)

### Steps to reproduce:
1. In campaign builder, add a condition for contact field value.
2. Select a field that has a dropdown for its value, for example country
3. Select any value from dropdown, except the first one. I select "Canada" for country
4. Save the condition
5. Edit the condition. "Canada" flashes for a moment, then it is reset to "Abkhazia" (the first value in the list). Same issue with other fields, Timezone for example

### Log errors: 

Not available on mautic.net

**Comment by escopecz** [comment]
It's fixed in https://github.com/mautic/mautic/pull/3574
