### ISSUE TITLE
[UI] Field not required in smart lists when selecting 'not empty'

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#377]
Small UI/UX issue, I don't think this field should be displayed if you select 'not empty'?

http://nimb.ws/cJqPvY

**Comment by alanhartless** [comment]
Absolutely correct.  Every time I see it I think that then forget to get back to it! Thanks for suggesting it.  We'll get fixed.

Thanks,
Alan

**Comment by alanhartless** [comment]
Fixed in 1.2.0
