### ISSUE TITLE
SF Plugin: Company Name field in mapping list is missing

### ISSUE THREAD

**Issue by reindje** [mautic/mautic#3770]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X 
| Feature request? | 
| Enhancement? | 

## Description:
SF Plugin: Company Name field in mapping list is missing

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Pull request #3674
| PHP version | 7

### Steps to reproduce:
1. Go in UI to SF plugin
2. Check companies to pull from SF
3. Go to Company Mapping tab
4. All fields are available from SF except the Company Name (Name) standard field
 
### Log errors: 
There are no errors in system or Mautic log, i get the following notice when i run the integration:fetchlead command on the CLI:

PHP Warning: array_flip(): Can only flip STRING and INTEGER values! in /var/www/mautic_dev/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php on line 229

**Comment by escopecz** [comment]
![screen shot 2017-06-02 at 09 02 42](https://cloud.githubusercontent.com/assets/1235442/26714568/4c52df0c-4772-11e7-81b1-5b5594f6c0cf.png)
I can see it on Mautic 2.8.2
