### ISSUE TITLE
Czech Republic changed to Czechia

### ISSUE THREAD

**Issue by mrerich** [mautic/mautic#3772]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Couple of weeks ago Google adopted new name for "Czech Republic", which is referred now as "Czechia". Auto assigning contact to the country of Czech Republic does not work now.

More info:
https://en.wikipedia.org/wiki/Name_of_the_Czech_Republic#Adoption_of_Czechia

This is more a change request then bug.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1 but I believe it is version independent
| PHP version |  7.0.16

### Steps to reproduce:
1. Create new contact from within Czech Republic
2. Check the field Country in contact details, it's empty. Other countries work well
 
### Log errors: 
none

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mrerich** [comment]
is this a complicated issue? :)

**Comment by escopecz** [comment]
I don't see a point in renaming Czech Republic to Czechia. Both are correct names of the country. If the issue is that the flag doesn't appear in the list, https://github.com/mautic/mautic/pull/4153 fixes that.

**Comment by mrerich** [comment]
good
