### ISSUE TITLE
Dynamic content error: Can't edit an email

### ISSUE THREAD

**Issue by fgauttron** [mautic/mautic#3773]
What type of report is this: 

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I can not edit an email. On the other hand, I can edit all the others

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | PHP Version 5.6.30-0+deb8u1

### Steps to reproduce:
1. 
2. 
 
### Log errors: 
[2017-03-29 18:15:49] mautic.ERROR: PHP Error - Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::widget() must be an instance of Symfony\Component\Form\FormView, null given, called in /srv/data/web/vhosts/crm.cefim.eu/htdocs/app/bundles/EmailBundle/Views/Email/form.html.php on line 215 and defined - in file /srv/data/web/vhosts/crm.cefim.eu/htdocs/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php - at line 162 [] []

Errors on console : 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2froala_editor.js:321 Editor should be initialized before calling the destroy method.
(anonymous) @ froala_editor.js:321
/s/emails/edit/11?_=1490804129169&mauticUserLastActive=2&mauticLastNotificationId= Failed to load resource: the server responded with a status of 500 (Internal Server Error)

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
It's a problem with dynamic content. You probably deleted the default box for dynamic content and saved the email. It's a bug, but if you want to quick fix your email so you could edit it, go to the database, `emails` table. Find the problematic email there and replace the `dynamic_content` value with 
```
a:1:{i:0;a:3:{s:9:"tokenName";N;s:7:"content";N;s:7:"filters";a:1:{i:0;a:2:{s:7:"content";N;s:7:"filters";a:1:{i:0;a:7:{s:4:"glue";N;s:5:"field";N;s:6:"object";N;s:4:"type";N;s:8:"operator";N;s:7:"display";N;s:6:"filter";N;}}}}}}
```
Which is the default value. Be aware that it will remove all dynamic content configuration for that email, but you probably didn't have any.

**Comment by fgauttron** [comment]
Thank you, the problem is solved.

**Comment by escopecz** [comment]
Fixed permanently in https://github.com/mautic/mautic/pull/4271
