### ISSUE TITLE
The "Submit Form" desicion doesn't work in campaigns after upgrade to 2.7.1

### ISSUE THREAD

**Issue by maxitromer** [mautic/mautic#3777]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:

I been using a "Submit Form" desicion in my campaigns without problem after the upgrade to the 2.7.1

Now the campaigns just jump all the desicions without to test if the form was submited.

Here a test campaign:

![campaign](https://cloud.githubusercontent.com/assets/6311835/24514739/b599b48a-154b-11e7-9e81-55ed560f9e05.png)

Here the result of the campaign in events:

![events](https://cloud.githubusercontent.com/assets/6311835/24514740/b59cb9fa-154b-11e7-8ed8-a52a20cbd31f.png)

You can see how the campaign triggers the NEGATIVE option when the Test Form 2 was submited before in the flow.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 5.6.21

### Steps to reproduce:
1. Create a campaign like in the image.
2. Run first the Form 2 then the Form 1 and wait for the cron jobs.
 
### Log errors: 

Mautic error log is empty.

**Comment by escopecz** [comment]
Campaigns won't trigger decisions which happened before the contact was added to the campaign. So submitting the "second form" and then "form 01" which starts the campaign won't trigger the "second form" decision.

**Comment by maxitromer** [comment]
Thanks for your answer @escopecz . Please let me test this in a diferent way, I have a current campaign in a production enviroment with this problem. I'll write again.

**Comment by maxitromer** [comment]
My problem was that my decision happened before the contact was added as escopecz says. I will close this.

Thanks again and again John.
