### ISSUE TITLE
Failed to execute push to Salesforce notification

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#3779]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
I have one contact that a campaign failed to push to Salesforce (not sure why, maybe because it was an existing contact). I keep getting a notification about this every hour or so:

"Failed to execute campaign event for x x. Get Started Forms / Push to Salesforce"

When I go to his profile and click to cancel this rescheduled event, the red x doesn't do anything when I click on it.

<img width="527" alt="screen shot 2017-03-30 at 9 48 08 am" src="https://cloud.githubusercontent.com/assets/590678/24513292/1167de90-152e-11e7-827d-3c55651fe528.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 5.6

 
### Log errors: 

No log errors found in Mautic, Apache or browser console.

**Comment by dbhurley** [comment]
Resolved in 2.11
