### ISSUE TITLE
[UI] Boxes not equal height

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#378]
This is a small niggle but it makes me twitch every time I see it!

When you have the grey outlined box on the check boxes it doesn't line up with the box to the right with the small arrow:

http://nimb.ws/ZGdwEL

It looks untidy, they should be the same height in my opinion.

**Comment by alanhartless** [comment]
Ewww! Yea they should be equal heights and are in the browsers I've used. What browser are you using? Does it happen in another browser as well? Could it be an extension installed on the browser that's changing the input size? It looks a little bigger than it should be.

On my mac, here are screenshots of chrome, firefox, and safari:

![](http://dvkrd.co/drop/2015-05-09_13-54-16.png)

**Comment by RCheesley** [comment]
I'm using Firefox to take the screenshots, not using any extensions that
would affect this kind of thing (at least that I'm aware of).

Could be a non-mac thing?

Ruth
On 9 May 2015 8:03 pm, "Alan Hartless" <notifications@github.com> wrote:

> Ewww! Yea they should be equal heights and are in the browsers I've used.
> What browser are you using? Does it happen in another browser as well?
> Could it be an extension installed on the browser that's changing the input
> size? It looks a little bigger than it should be.
>
> On my mac, here are screenshots of chrome, firefox, and safari:
>
>
> <https://camo.githubusercontent.com/178817130a456148407fac0cbedf370762b910c9/687474703a2f2f64766b72642e636f2f64726f702f323031352d30352d30395f31332d35342d31362e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/378#issuecomment-100530405>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by alanhartless** [comment]
Looks like this is a problem on Linux machines.  We're trying to see if we can remedy and keep all OSes happy.

**Comment by RCheesley** [comment]
Ah, fun and games - thanks :)

**Comment by alanhartless** [comment]
@escopecz did we fix this? :) I remember talking about it with you way back when.

**Comment by escopecz** [comment]
I remember we did some modifications to fix it on Linux, but it's there still (or again).
![mautic-ui-1px-problem](https://cloud.githubusercontent.com/assets/1235442/9991863/1a6003fe-606e-11e5-8153-ed9dfae47e6d.png)

If that 1px issue is visible only for 5% of (linux) users who are used to these UI glitches anyway, I'd call it fine. I attended Jeremy Keith's talk yesterday where the main idea was answer to this question:

http://DoWebsitesNeedToLookExactlyTheSameInEveryBrowser.com

(don't tell David)

**Comment by RCheesley** [comment]
Hah :)  It was more of a minor irritation making me twitch when I saw it
than a mission critical UI issue :)

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 21 September 2015 at 13:44, John Linhart <notifications@github.com>
wrote:

> I remember we did some modifications to fix it on Linux, but it's there
> still (or again).
> [image: mautic-ui-1px-problem]
> <https://cloud.githubusercontent.com/assets/1235442/9991863/1a6003fe-606e-11e5-8153-ed9dfae47e6d.png>
>
> If that 1px issue is visible only for 5% of (linux) users who are used to
> these UI glitches anyway, I'd call it fine. I attended Jeremy Keith's talk
> yesterday where the main idea was answer to this question:
>
> http://DoWebsitesNeedToLookExactlyTheSameInEveryBrowser.com
>
> (don't tell David)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/378#issuecomment-141962721>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by alanhartless** [comment]
Ha! Yea David would not agree with that site at all; hehe.  TBH, it would bug me too seeing that every day.  :-D

I found our conversation on it and http://jsfiddle.net/Lma15ra5/ was referenced.  But seemed that FF still had a 1px difference. I was going to fire up Browserstack to look but of course they don't have a linux VM :-/
