### ISSUE TITLE
Publish role doesn't work (Assets / Dynamic Content / Emails / Landing Pages)

### ISSUE THREAD

**Issue by hrdyrk** [mautic/mautic#3781]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
I set "Publish (Own/Others)" role off in the below section. But  when I create ( or edit ) new contents in them by using a user of the role , I can edit Publish No/Yes button.

Assets
Dynamic Content
Emails
Landing Pages

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.0
| PHP version | 7.0

### Steps to reproduce:
1. Create a role which has no permission of publish contents in the below section. 
      Assets
      Dynamic Content
      Emails
      Landing Pages
2. Create a user which has the role created above.
3. Create or Edit new contents. Then the user can edit publish button, even it doesn't have the permission of editing publish status.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by bmdva** [comment]
Hi. Can you tell me when the bug gets fixed? We have many problems with anyone is being allowed to send mails. Thx, Dennis

**Comment by srdecny** [comment]
Bumping. I'm interested in solving this issue.

Would changing the code in appropriate `list.html.php` files as follows in the example below be okay? Example is taken from [here](https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/Views/Email/list.html.php#L121).
```php
if ($permissions['asset:assets:publishown'] || $permissions['asset:assets:publishother']) {
	echo $view->render(
    	'MauticCoreBundle:Helper:publishstatus_icon.html.php',
        ['item' => $item, 'model' => 'email']);
}
```
In the example above, a proper check of `publish own/other` rights would have to be implemented properly, although some contents doesn't have `publish own/other` permissions, only `publish`. Is this approach for fixing the issue correct, or is there another preferred way to fix this?

**Comment by npracht** [comment]
hello @hrdyrk @bmdva @srdecny still an issue ? I know this part has been enhanced and fixed several times now.
