### ISSUE TITLE
Mautic company look up with special characters

### ISSUE THREAD

**Issue by stratocentric** [mautic/mautic#3786]
What type of report is this:

| Bug Report? |

I entered a contact and then added a company which has an ampersand in their name... it starts with G&A.  I added a second contact and tried the lookup but it doesn't produce anything for the company name.  I haven't looked at the database yet but when I changed the company to start with GA instead of G&A it changed the company record but didn't update with the original record which leads me to believe that you are storing the company name instead of a unique record that would have been updated automatically... or the ampersand is not being dealt with properly in the database.

Now neither GA or G&A produces anything for the database search which could be a third issue with PHP and string length... but the full name doesn't produce anything either.. and the company record was not updated on the original contact input....maybe it is cached?

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by stratocentric** [comment]
Editor should be initialized before calling the destroy method.
(anonymous) @ froala_editor.js:321

**Comment by stratocentric** [comment]
php version:

PHP Version 7.0.16-2+deb.sury.org~trusty+1

Mautic is latest version

**Comment by escopecz** [comment]
Could you please re-test if this is still an issue with Mautic 2.15.0?
