### ISSUE TITLE
Form: make option value fields required

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3787]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y

## Description:
When I add more than one option to the checkbox optionlist on the properties tab, only the last one is saved. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Using mautic.net hosted version
| PHP version | 

### Steps to reproduce:
1. Make form
2. Click Fields
3. Click add field
4. Select checkbox group
4. Click properties
5. Add first option
6. Add more options using the plus icon
7. Save
Result: see only one box in the fields page, click the edit again, only one is visible there too.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by gingerling** [comment]
Actually, I found this is the same for all items. It seems to be a problem with the "Value" option, if you don't choose a value (and note that it does not that you must do this) it only saves one. If you put numbers in the value, then they are saved. I think this is how the order of the items is set? You can also drag and drop. Not clear if this is a bug or a usability/UX/UI issue.

**Comment by npracht** [comment]
Solved in 2.9.1 by https://github.com/mautic/mautic/pull/4355
