### ISSUE TITLE
Adding existing contact to segment using quick add creates duplicate contact

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3789]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y

## Description:
If I try to add a contact to a segment by navigating to segments and clicking quick add and pasting the email of an existing contact in to the email field, a new contact is created with the email (therefore a duplicate) adding the existing contact.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | mautic.net hosted

### Steps to reproduce:
1. go to segments
2. click view x contacts in segment
3. click quick add
4. put email of existing contact in the email box and save
5. a new contact with the same email is created

**Comment by gingerling** [comment]
To clarify, I am unsure if this is the method that is supposed to be used to add existing contacts manually to a segment, it's the only method I could find though

**Comment by gingerling** [comment]
Anything I can do to move this forward?

**Comment by github-grabaz** [comment]
I am finding there are other ways that Mautic can/does create duplicates.  My big question is why aren't uniqueness constraints kicking in to prevent this?  And why isn't enforcement of uniqueness a function of the database?  This is always something I have used since the database is much better/faster at doing this.

**Comment by github-grabaz** [comment]
@gingerling Sorry I hijacked your question but didn't answer it.  The correct way to add a contact to a segment is to open the contact and then click on the dropdown arrow next to the close button and choose preferences.
![image](https://cloud.githubusercontent.com/assets/1254378/25550505/78a5130e-2c2e-11e7-8b7d-1cc22e54943e.png)
  The Contact Preference Center will open.  Click on the Segments tab and start adding your segments.  
![image](https://cloud.githubusercontent.com/assets/1254378/25550534/be6e7038-2c2e-11e7-9b04-194b07e44de1.png)

**Comment by gingerling** [comment]
Yes, thanks it does.

I also find duplication issues, I suggest a separate bug. 

Here is this bug and my other duplication report for the start of a list list:

https://github.com/mautic/mautic/issues/3934
https://github.com/mautic/mautic/issues/3789#issuecomment-298043460

**Comment by YosuCadilla** [comment]
I'm experiencing this on Mautic 2.13.1 with Maria DB and PHP 7.0.30

**Comment by npracht** [comment]
Couldn't reproduce. Must be fixed.
