### ISSUE TITLE
Segment filter by Segment Membership does not update when new members are added to the filtering list

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3790]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y

## Description:
When set up one segment to filter out out members of a second segment, contacts do not get removed if they are subsequently added to the filtering segment. So:

Segment B = X criteria - members of segment A

Joanne Bloggs is initially in no segments
She are added to Segment B, for example via a file import
She is later added to segment A because she filled out a form

She should be then removed from segment B, however she is not.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | mautic.net hosting

### Steps to reproduce:
1. You would need to devise a testing scenario based on the above

**Comment by gingerling** [comment]
Anything I can do to help move this forward?

**Comment by escopecz** [comment]
It should be fixed by now. Let us know please if you are still experiencing this issue.

**Comment by gingerling** [comment]
Ok, thanks
