### ISSUE TITLE
Undefined index: properties when mapping the state form field to contact field

### ISSUE THREAD

**Issue by mahesh2010** [mautic/mautic#3796]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
I am facing a critical issue while designing form component. I have a field to enter 'State' in my Form. While selecting 'Matching Contact Value' for State field it shows error

"The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.

System administrators, check server logs for errors.".

Please do the needful to correct this as we are in urgent need for development of the form.

Error Log:

2017/03/24 04:59:58 [error] 3507#3507: *948 FastCGI sent in stderr: "PHP message: PHP Notice: Undefined index: properties in /var/www/mautic/app/bundles/CoreBundle/Views/FormTheme/Custom/sortablelist_row.html.php on line 6
PHP message: PHP Notice: Trying to get property of non-object in /var/www/mautic/app/bundles/CoreBundle/Views/FormTheme/Custom/sortablelist_row.html.php on line 9
PHP message: PHP Notice: Trying to get property of non-object in /var/www/mautic/app/bundles/CoreBundle/Views/FormTheme/Custom/sortablelist_row.html.php on line 27
PHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/mautic/app/bundles/CoreBundle/Views/FormTheme/Custom/sortablelist_row.html.php on line 27" while reading response header from upstream, client: 192.168.221.150, server: <our server name>, request: "POST /s/forms/field/new?mauticUserLastActive=1&mauticLastNotificationId= HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "<our domain name>", referrer: "http://<our domain name>/s/forms/new"

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 

Mautic 2.7

### Steps to reproduce:
Scenario I followed is =

Load the 'Component \ 'Form' Page
Click 'New'
Select 'New Standalone form'
Form name 'First Form'
In 'Fields' Tab click 'Add a Field' drop down and select 'select'
In the 'select' popup window label name 'State name'
In 'contact field' select 'Matching field' as 'Core state'
Press ' +Add'
Shows the specified Error message
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ATouhou** [comment]
Also Checkbox field with value.
Clean install of newest version.

PHP 7

[07-Apr-2017 22:25:01 Europe/Copenhagen] PHP Warning: Invalid argument supplied for foreach() in /home/adamtouh/public_html/perfectsolutions.dk/mautic/app/bundles/CoreBundle/Views/FormTheme/Custom/sortablelist_row.html.php on line 27

**Comment by RCheesley** [comment]
Closing as this relates to a very old version of Mautic and has no recent discussions.
