### ISSUE TITLE
Logs for logged in users

### ISSUE THREAD

**Issue by Ashwini04** [mautic/mautic#3797]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
I need a log about the logged in user's action in mautic.

For ex: If a user deletes a contact that log should be maintained in log.
Like wise whatever actions a logged in user doing inside mautic, I need to track it down.

The reason for the feature request is : I have faced an issue. Some user deleted contacts in mautic, I cant able to find out which user deleted the contact.

**Comment by escopecz** [comment]
Look into the `audit_log` table. All the user actions are recorded there including the contact delete actions.
