### ISSUE TITLE
Internal server error when trying to submit a form or landing page

### ISSUE THREAD

**Issue by amusik** [mautic/mautic#38]
![image](https://cloud.githubusercontent.com/assets/10809770/5999963/be9620e8-aacf-11e4-8b56-2d53d519f59f.png)

Hi guys,

My first time ever joining a Github discussion - I found mautic very interesting and worthy of joining the conversation here. I love the software immediately and deeply appreciate your work on this project!

I was trying to experiment with forms and landing pages but when I open the page and try to complete it I get this error message. You can see the URL in the picture - I'm using still the version that's hosted by Mautic but I'm planning to install it locally (I'm assuming this might fix the error).

**Comment by synologic** [comment]
Also, the mautic_prod.php shows:
[2015-02-03 11:33:37] mautic.CRITICAL: Uncaught PHP Exception Swift_RfcComplianceException: "Address in mailbox given [] does not comply with RFC 2822, 3.6.2." at /www/marketing/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader
.php line 348 {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [] does not comply with RFC 2822, 3.6.2. at /www/marketing/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:348)"} []

**Comment by alanhartless** [comment]
Hi guys,

This has been fixed and will be rolled out to mautic.com this week. 

But just to confirm it's the same issue, did you by chance have a "send email to admin" form submit action defined for the form? 

I apologize for the inconvenience!

Thanks,
Alan

**Comment by amusik** [comment]
Hi!

That's correct - I wanted to get an email notification about the new form submission.

Lassi

On tors, feb 05, 2015 at 3:18 fm, synologic <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi guys,

This has been fixed and will be rolled out to mautic.com this week.

But just to confirm it's the same issue, did you by chance have a "send email to admin" form submit action defined for the form?

I apologize for the inconvenience!

Thanks,
Alan

-

**Comment by alanhartless** [comment]
Okay; I'm going to close this then as it was fixed with https://github.com/mautic/mautic/commit/bc6ed157ef6c97d89721c8aba419db47f5474a68#diff-ca25c3d5ae42a898e6b89103a1acc8efR829. 

Thanks!
Alan
