### ISSUE TITLE
Mautic not recording page hit when click browser back button.

### ISSUE THREAD

**Issue by codertoon** [mautic/mautic#3804]
Bug report?

## Description:
When i click browser back button on a website containing mautic tracking pixel then it is not recording page hit when click browser back button.

 Mautic version  v2.7.1 
php v5.6

**Comment by escopecz** [comment]
That's common for all analytics trackers I would guess. If you click the back button, the page is loaded from the memory and no requests are being made to the server so the server doesn't have any clue that the page load have happened. So it rules out tracking pixel.

The JS tracking: From what I read, the browsers are acting differently on whether they emit the page loaded event on back button click. Some do, some don't. I'm not sure whether we can do something about it.
