### ISSUE TITLE
271 Systems settings - sending test email fails if password not re-entered

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#3806]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
I setup mailjet integration and entered login and password
I check connexion and saved
I go back to configuration > email settings and just wanted to send the test email

An error message is printed on screen with authentification failed.... until I re-enter manually the password in the password field (which is printed leave blank for no modification)

So the test email button is linked to the data input within the form displayed on screen, if the user does not re-enter the password this button will be totally useless (unless the smtp is not protected at all wich is hihly insecure )

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.14

**Comment by escopecz** [comment]
@YannickBiet do you still have this problem?
