### ISSUE TITLE
MailJet webhook integration broken

### ISSUE THREAD

**Issue by thomeudt** [mautic/mautic#3807]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
We have configured MailJet to report back bounce data to Mautic via webhook (as documented here https://mautic.org/docs/en/emails/bounce_management.html).

The connection test in Mailjet is successful (OK, Code 200).

However, contacts are not updated accordingly and e-mail statistics do not show any bounced messages in Mautic.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.15-0ubuntu0.16.04.4

### Steps to reproduce:
1. Connect MailJet via Webhook
2. Send e-mail to non-existing e-mail address to trigger bounce event
3. Monitor contact history and e-mail stats
 
### Log errors: 

The following line gets written to the error log whenever an e-mail bounces:

`mautic.NOTICE: PHP Notice - Undefined offset: 18 - in file /var/www/mautic-master/app/bundles/EmailBundle/Model/EmailModel.php - at line 1424 [] []
`

**Comment by YannickBiet** [comment]
I would advise to rename this issue as the title is not actually the whole integration that is KO but only the bounce via webhook, we are persoannly using mailjet to send emails and this is working (but we are not using bounce webhooks)

**Comment by thomeudt** [comment]
You are correct. We are also using MailJet via SMTP, and there is no issue with that. Changed the title accordingly.

**Comment by patrickvanl16** [comment]
I also still have the same problem. I've linked Mailjet with Mautic and it isn't updating contacts, and it isn't saying that a mail has bounced. Mailjet does say that it has bounced.

I can't find a fix for this.

**Comment by maltonite** [comment]
I have found the issue; for some reason the tracking hash against a contact/email is getting mixed up. In the JSON response from MailJet, I was getting something like: 

`{"event":"bounce","time":1508400950,"MessageID":16044074629384950,"email":"**abc@abc.com**","mj_campaign_id":25150054,"mj_contact_id":34683883,"customcampaign":"","blocked":false,"hard_bounce":false,"error_related_to":"","error":"","CustomID":"59e85f2b4d1d7-**xyz@xyz.com**","Payload":""}`

The key parts being the abc@abc.com being the email which has bounced, with the tracking hash being returned for the email xyz@xyz.com. In mautic/app/bundles/EmailBundle/Swiftmailer/Transport/MailjetTransport.php, line 118, it looks for the "CustomID", meaning that you can build a report showing the contacts which bounced against a specific email. I commented out the if loop, and just use the else portion, which has fixed the issue, but does mean that I only know that a contact has bounced, not against which email. I will look into this further to see if the problem occurs at the point of sending from Mautic.

**Comment by javjim-mautic** [comment]
What will happen with this? the PR has been removed from 2.13
@alanhartless

**Comment by mleffler** [comment]
I removed this also, thanks Javier!

**Comment by npracht** [comment]
Hello @thomeudt do you still meet this issue? We're using it everyday and it works properly.
Thanks

**Comment by thomeudt** [comment]
Seems to be working now.
