### ISSUE TITLE
[271] Mautic retrieve social information (twitter) is not working if twitter handdle already saved

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#3809]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |Yes 
| Feature request? | No
| Enhancement? | No

## Description:
We created some contacts within mautic
We added for each in the social tab the twitter handdle
We saved the data
There no social info (twitter integration has not been setup)
We setup the twitter integration
We are going back to the contact social tab and press the link 

![twitter](https://cloud.githubusercontent.com/assets/930391/24661014/7b31c6a2-1951-11e7-805d-2d25ea95b4a6.PNG)

Nothing happens

Expected behavior : the public profile of twitter should appear.

If we re-edit the contact data and simply change one char (delete last one for example), press save.
then re-edit and re-enter the last char. press save, mautic will finally retrieve and display the social information

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.14

### Log errors: 

[2017-04-04 13:52:18] mautic.NOTICE: Doctrine\ORM\ORMException: The EntityManager is closed. (uncaught exception) at /var/www/mautic/www_rec271/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php line 144 while running console command `mautic:social:monitoring` [] []

**Comment by RCheesley** [comment]
Confirm that this error is occurring in 2.8.0 also.

**Comment by RCheesley** [comment]
Closing this issue as it likely relates to incorrect database and table types causing problems with importing foreign characters.  Use UTF8mb4 Unicode! It's also a super old issue with no recent dialogue.
