### ISSUE TITLE
Install Errors on Step 3 - Administrative User

### ISSUE THREAD

**Issue by ampedpublishing** [mautic/mautic#3812]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When trying to setup on my LiquidWeb dedicated server on step 3 - Setting up Administrative User, I get generic error: https://screencast.com/t/oqtPeSQp.

How can I fix this?

Thanks!

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0

### Steps to reproduce:
1. Get to step 3 of the setup process (Mautic Installation - Administrative User). 
2. Enter credentials.
3. Gives generic error.
 
### Log errors: 

**Server Logs:**
[Sun Apr 02 20:10:01.939524 2017] [authz_core:error] [pid 13142:tid 139995171997440] [client 67.225.242.41:55080] AH01630: client denied by server configuration: /home/higherlevelsucce/public_html/php.ini

**Mautic Logs:**
[2017-04-04 17:34:00] mautic.WARNING: PHP Warning - require(/home/higherlevelsucce/public_html/hls/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php): failed to open stream: No such file or directory - in file /home/higherlevelsucce/public_html/hls/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []

[2017-04-04 17:34:00] mautic.ERROR: PHP Notice: require(): Failed opening required '/home/higherlevelsucce/public_html/hls/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') - in file /home/higherlevelsucce/public_html/hls/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []

[2017-04-04 17:34:00] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Notice: require(): Failed opening required '/home/higherlevelsucce/public_html/hls/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') - in file /home/higherlevelsucce/public_html/hls/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []

**Comment by MxyzptlkFishStix** [comment]
Are all directories/files under /home/higherlevelsucce/public_html/hls/ owned/writeable by the web server user?

**Comment by ampedpublishing** [comment]
Here is what LiquidWeb Support told me:

From the errors that you sent in, it appears that the installation process is trying to access the local php.ini file:

> Fri Mar 31 23:51:57.161305 2017] [authz_core:error] [pid 2053:tid 139995197175552] [client 66.249.75.39:36839] AH01630: client denied by server configuration: /home/higherlevelsucce/public_html/php.ini

I believe that a global protection is preventing this file from being written to. There is a standard directive in the Apache configuration file that is most likely causing the errors that you encountered:

```
# Required cPanel security policy: Disallow remote access to .htaccess, .htpasswd, .user.ini, and php.ini files

<FilesMatch "^(\.ht(access|passwds?)|\.user\.ini|php\.ini)$">
    Require all denied
</FilesMatch>
```
This is not something that we recommend bypassing.

Then they continued to troubleshoot and sent this:

I keep getting the same results for errors:

> [2017-04-05 21:48:19] mautic.WARNING: PHP Warning - require(/home/higherlevelsucce/public_html/hls/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php): failed to open stream: No such file or directory - in file /home/higherlevelsucce/public_html/hls/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []
> [2017-04-05 21:48:19] mautic.ERROR: PHP Notice: require(): Failed opening required '/home/higherlevelsucce/public_html/hls/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') - in file /home/higherlevelsucce/public_html/hls/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []
> [2017-04-05 21:48:19] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Notice: require(): Failed opening required '/home/higherlevelsucce/public_html/hls/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') - in file /home/higherlevelsucce/public_html/hls/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209 [] []

It seems that there is something wrong with the filename that is supposed to be generated prior to line 209 (in bold) that is causing the required filename to not be passed correctly:

[root@host public_html]# vim -M /home/higherlevelsucce/public_html/hls/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php +209

```
/**
     * Get a proxy definition for the given class name.
     *
     * @param string $className
     *
     * @return ProxyDefinition
     */

...
        if ( ! class_exists($proxyClassName, false)) {
            $fileName  = $this->proxyGenerator->getProxyFileName($className);

            switch ($this->autoGenerate) {
                case self::AUTOGENERATE_NEVER:
                    require $fileName;

                    break;
```

And that's where I am lol.. any suggestions?

Thank you

**Comment by 007ke** [comment]
I'm having exactly the same issue. Any solutions ? 

Thank You

**Comment by ampedpublishing** [comment]
Nothing yet. Seems if I cannot get past the setup stages this may not be the application for me. I cannot seem to find a detailed server/ext requirements list. Each step I take is just more errors.

**Comment by Dude4Linux** [comment]
Try uncommenting the following line in php.ini
always_populate_raw_post_data = -1

**Comment by eltonmorais** [comment]
Nothing about that yet?

**Comment by escopecz** [comment]
The errors seem to be related to file system permission issue. 

The response from the hosting support is... bad to put it nicely. Mautic does not try to modify php.ini files. Try to google "client denied by server configuration" to get more valid explanation of the error.

If the others are having similar issue, please give us some information we can work with. What PHP version are you on? What errors are recorded in the logs? Look at https://mautic.org/docs/en/tips/troubleshooting.html for more details about troubleshooting.

**Comment by MikeThinkable** [comment]
I get the same issue and have this error log. I checked, the **doctrine** folder in app/cache/prod doesn't exist...

[30-Jul-2017 10:24:18 UTC] PHP Warning:  require(/home/thinknet/public_html/crm/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php): failed to open stream: No such file or directory in /home/thinknet/public_html/crm/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209

[30-Jul-2017 10:24:18 UTC] PHP Fatal error:  require(): Failed opening required '/home/thinknet/public_html/crm/app/cache/prod/doctrine/orm/Proxies/__CG__MauticUserBundleEntityRole.php' (include_path='.:/opt/cpanel/ea-php56/root/usr/share/pear') in /home/thinknet/public_html/crm/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209

Any ideas?

**Comment by MikeThinkable** [comment]
Update - Fixed! - I cleared the cache in the folder as per the troubleshooting guide above and get this error when submitted the DB details on step 1:

An error occurred while attempting to add default data: MysqlPlatform::getDropIndexSQL() expects $table parameter to be string or \Doctrine\DBAL\Schema\Table.

So I then dropped all the Database tables and tried again - success.

**Comment by eliamarsu** [comment]
Thanks! I just fixed it clearing the "/app/cache" folder and now it work properly

**Comment by anton-vlasenko** [comment]
`php app/console cache:warmup --env=prod` worked for me.

**Comment by andrewjneumann** [comment]
> Thanks! I just fixed it clearing the "/app/cache" folder and now it work properly

This fixed for me.

**Comment by fagnerdireito** [comment]
> ```shell
> php app/console cache:warmup --env=prod
> ```
> 
> fixed the issue for me.

This fixed for me.

**Comment by KALA-Typo3** [comment]
Happened to me too when I installed mautic over composer with local php and tried to run it over ddev.

Deleting app/cache (whole folder, not only its content) helped.

**Comment by fianbiasa** [comment]
> ```shell
> php app/console cache:warmup --env=prod
> ```
> 
> fixed the issue for me.

**Best Solution** for me
