### ISSUE TITLE
Make form email instantaneous

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3828]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
Test email has been made instantaneous even if you use CRON jobs.
I think, it'd be great that `send email to contact`action on a form follow the same behavior. it is often use as autoresponder to download a documentation and it can be very frustrating for the user to wait 5/10min (depending on the CRON) to receive this email.

**Comment by kuzmany** [comment]
> Test email has been made instantaneous even if you use CRON jobs.

Do you mean Queue mode?

![image](https://user-images.githubusercontent.com/462477/32853399-7c941d60-ca3b-11e7-8709-8e39a3ab3fc0.png)

**Comment by npracht** [comment]
This is not about test email but email part of form action (send email to contact action).

Envoyé de mon iPhone

**Comment by kuzmany** [comment]
No I am just asking, If you mean CRON 

`php /path/to/mautic/app/console mautic:emails:send`

This CRON is apply when u are using Process Email Queue.
I think this Queue is for all emails in all Mautic  (broadcasts, campaigns, forms...)

**Comment by npracht** [comment]
Yes, this is what I mean. Taking auto responder out of the queue (same as test email) :)

Envoyé de mon iPhone

**Comment by kuzmany** [comment]
@escopecz  I can work on this request this week. Can you give me some hint for possible solution.
I know the code about the mailer and send  email and queue, but  I am not sure about solution.
If queue is enabled all emails (broadcast, campaigns, form..) are send via queue? 
I have little fear this change is not so easy (need core changes), isn't it?
Thank for your feedback.

**Comment by escopecz** [comment]
I think that test emails (the one you can send from configuration page or an email detail page) are not queued even if the queue is configured. Look at how it's done.

**Comment by kuzmany** [comment]
Ok. Guys pleas test https://github.com/mautic/mautic/pull/5414
