### ISSUE TITLE
Link tracking doesn't work in firefox. 

### ISSUE THREAD

**Issue by naveedpeerzade** [mautic/mautic#3830]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
Link tracking doesn't work in firefox. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.7.1
| PHP version | 7.0.17
| Firefox version | 52.0.2 (64-bit)

### Steps to reproduce:
https://mautic.domain.com/r/8d3f3d2eb1e207637b6df1bbe?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6Mjt9czo1OiJlbWFpbCI7aToyO3M6NDoic3RhdCI7czoxMzoiNThlOTVhYzk2ZWQ2MSI7czo0OiJsZWFkIjtzOjE6IjQiO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYWlsIjtpOjI7fX0%3D

The said link tracks perfectly fine in Chrome and IE and Microsoft Edge. But it doesn't get tracked in Firefox. And surprisingly when I removed the additional part, the link https://mautic.domain.com/r/8d3f3d2eb1e207637b6df1bbe gets tracked.. note sure what ct= variable for?

**Comment by escopecz** [comment]
Could it be that you are logged in to Mautic administration in Firefox?

**Comment by naveedpeerzade** [comment]
Yes... I was.. 
I will test it again without logging into admin.

**Comment by naveedpeerzade** [comment]
Thanks escopecz, it worked.. So that means if you are logged into Admin, the links will not be tracked... Another question... Does mautic cloak all the links, i.e. is there a way if we do not want any link to be tracked? so if use google.com it stay as is and doesnt get converted into a long link for tracking.

**Comment by escopecz** [comment]
Yes, as it's written in the [docs](https://mautic.org/docs/en/contacts/contact_monitoring.html)

There is this feature request on your second question https://github.com/mautic/mautic/issues/2927
