### ISSUE TITLE
Mautic not triggering push notifications in the campaigns

### ISSUE THREAD

**Issue by andreBabington** [mautic/mautic#3834]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I've setup OneSignal api in the configuration, enabled notifications on landing pages and allow notifications. OneSignal accepts the subscription and is visible in users but when a "send notification" is set within a campaign it now produces an error message

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.17

### Steps to reproduce:
1. Setup and configure One Signal to Mautic
2. Create campaign and set action of send notification
[error.txt](https://github.com/mautic/mautic/files/909645/error.txt)

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by andreBabington** [comment]
just to note, this is a fresh mautic install, I created custom fields within mautic and imported contact data from another installation. I've also mentioned on slack that notifications do not appear as a contact preference at all
![mautic-screenshot](https://cloud.githubusercontent.com/assets/27202510/24856353/6057b3a2-1ddc-11e7-8137-49c5a4570d52.png)

**Comment by andreBabington** [comment]
![screenshot-resources babington co uk-2017-04-10-11-07-02](https://cloud.githubusercontent.com/assets/27202510/24856803/dc119b56-1ddd-11e7-98b1-ad993ee3beb1.png)

**Comment by vincnetas** [comment]
Did you resolved this?
