### ISSUE TITLE
Enhanced email stats

### ISSUE THREAD

**Issue by naveedpeerzade** [mautic/mautic#3837]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  Y
| Enhancement? |  Y

## Description:
Would be great if we can have more tabs next to "Click Counts" So we can have more and required data for each email... The graph shows the figures but would be cool to have actual data.... more tabs such as 

- Unsubscribed 
- Clicked
- Bounced
- Failed
- Read

And then also unsubscribe numbers in the listing.. 

Please checked attached mockups

![mautic_mail_stats](https://cloud.githubusercontent.com/assets/27104582/24880429/0447a28a-1e58-11e7-9e87-8748b432a7e5.png)
![mautic_mail_stats1](https://cloud.githubusercontent.com/assets/27104582/24880556/818af0da-1e58-11e7-9244-e36eab2b6826.png)

**Comment by npracht** [comment]
Duplicate https://github.com/mautic/mautic/issues/3532 ?
