### ISSUE TITLE
Add HTML editor button to Dynamic Content editors

### ISSUE THREAD

**Issue by stevegrant1983** [mautic/mautic#3840]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
The HTML code editor is available on many of the instances of the WYSIWYG editor throughout the application, but it is not available on the Dynamic Content editors by default.

### Steps to fix:
In `/media/js/app.js...`
Add `'html'` to the array of button options on lines 65, 429 and 430

**Comment by escopecz** [comment]
Would you be able to send the pull request with the changes you suggested?

**Comment by stevegrant1983** [comment]
Sure, no problem

**Comment by stevegrant1983** [comment]
This has been fixed in 2.8.0
