### ISSUE TITLE
Template HTML email and landing page (problem builder)

### ISSUE THREAD

**Issue by jdecampos** [mautic/mautic#3842]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
When you select a template in the list of emails or landing pages, it works randomly.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 5.6.30

### Steps to reproduce:
1. Go to landing page or email
2. Select a template
3. Click on "builder"
4. go back
5. Select another template
6.Click on "builder"
7....

<img width="1680" alt="capture d ecran 2017-04-11 a 18 47 05" src="https://cloud.githubusercontent.com/assets/14194414/24920390/4e139a7e-1ee7-11e7-828d-b4181f2b6450.png">

 
### Log errors: 

No log error

**Comment by jdecampos** [comment]
This is not a bug ?

**Comment by escopecz** [comment]
I'm not able to reproduce. Anyone else is having this issue? Is it a specific browser. browser version? OS?

**Comment by ralphkretzschmar** [comment]
Same Bug and no logs :( firefox/chrome/vivaldi) (Win10)

**Comment by escopecz** [comment]
It must be a server issue or Win10 issue then. If you press F12 key while in the browser where the issue is happening. Any errors in the Console tab?

**Comment by ralphkretzschmar** [comment]
i found the solution:
after the upgrade the folder /var/www/mautic/app/cache/prod
was root not www-data 
after changing to www-data everything went well :)

**Comment by escopecz** [comment]
Make sure your cron jobs does not run as root but as www-data user.
