### ISSUE TITLE
404 error when clicking on 'view email online' link in emails sent to users via form submission

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#385]
I used the view online text macro to insert the view online notice on an email, but when I tried to click on that link I get a 404 - for reference, the URL is: http://mymauticinstall.com/email/view/554e3a238f405 running v1.0.5.

**Comment by alanhartless** [comment]
The URL looks right and I just did a quick local test and the URL generated worked for me. Did you by chance delete the lead or email after sending it? If so, the unique view ID will not be valid (it's associated with the specific lead and email sent).  Can you check your email_stats table and search for tracking_hash = 554e3a238f405 to see if it exists?

Thanks!
Alan

**Comment by RCheesley** [comment]
This was sent to someone who had an admin account on the system - i.e. I completed the form front-end using my email address which is associated with my admin account.

I therefore think that this email address is not added to the leads list, and hence breaks things?  Could also be the problem I reported with regards to the wrong name being used?

**Comment by alanhartless** [comment]
Ah; could be. We will have to look at that as users aren't tracked as leads.  I think there is a check in there to ensure the lead exists since emails pull in specific details for the lead (some that a user may not have).  But since we are allowing emails to be sent to users via form submissions, we'll have to add a work around for that.

Marking this as a bug then and we'll take a look at it.

Thanks!
Alan

**Comment by RCheesley** [comment]
Thanks Alan, I think the quirks I was seeing with the wrong name was also
from this mail - or it could have been from the 'send a test mail' feature.

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 11 May 2015 at 16:18, Alan Hartless <notifications@github.com> wrote:

> Ah; could be. We will have to look at that as users aren't tracked as
> leads. I think there is a check in there to ensure the lead exists since
> emails pull in specific details for the lead (some that a user may not
> have). But since we are allowing emails to be sent to users via form
> submissions, we'll have to add a work around for that.
>
> Marking this as a bug then and we'll take a look at it.
>
> Thanks!
> Alan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/385#issuecomment-100941190>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.
