### ISSUE TITLE
Text area label resets to do not display after setting to display

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3853]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y

## Description:
Text area on form will not show label, setting to show and saving just resets to do not display.

## If a bug:

| Q   | A
| --- | ---
mautic.net

### Steps to reproduce:
1. create form
2. add field text area
3. give label (eg "Comments" / "Description")
4. toggle display label from no to yes
5. save, see that is is showing
6. save form/apply, see that the label is no longer showing
7. check settings, it is toggled back to no, do not display.

**Comment by escopecz** [comment]
I cannot reproduce. The *Show label?* toggle saves both values. I switch yes/no several times and it always sticks. Also, at point 4. - it's yes by default. Is it possible you didn't save the form in between? Can you reproduce this behaviour on every form? On every browser? We have to find reproducible steps.

**Comment by gingerling** [comment]
I also can't reproduce this, though I spent a lot of time testing it initially, using new forms etc with several attempts for each form etc.  I was finding that even when creating a new text area display was toggled to off. When I do this today it is as you say, toggled to yes by default and saves fine. 

The browser was firefox (on fedora linux), so could perhaps have been some plugin interfering with the JS? I will keep my eye out and let you know if it happens again, but happy for you to close the bug in the mean time, unle
