### ISSUE TITLE
Tracking innner the website

### ISSUE THREAD

**Issue by potatoin** [mautic/mautic#3855]
What type of report is this: lead tracking troubleshooting

| Q  | A
| ---| ---
| Bug report? | no bug
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...
Hi, 
I have installed mautic in AWS ec2 ubuntu with php7 and apache2.
There is no domain name for my server since i have not yet to buy one. i am using the public ip (xxx.xxx.xxx.xxx) as my domain name.

I have sent a email with the link to a customer from mautic, this customer could click my link and access my landing page.
From mautic panel, i could see the first click from my customer , however,  it can not track this customer when he click other URL links from the landing page.

i have tried it by cloud mautic and found that it went very well.
could you tell me what i am missing?

Thanks

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7
| PHP version | php7

**Comment by escopecz** [comment]
Try to look at https://mautic.org/docs/en/pages/troubleshooting.html and let us know if it helped

**Comment by potatoin** [comment]
Hi escopecs,
Thank you for your help. i have already read this text what you sent to me. I think my work is correct. i have already inserted JavaScript tracking code for all pages but pixel. Do you mean that i need to insert pixel code as well as JavaScript for all pages? Thank you

**Comment by escopecz** [comment]
No, JS is fine. It could be a CORS issue. Open the dev tools in your browser on the tracked page and check the console errors. Or share the page where you have the JS tracking so we could look.

**Comment by potatoin** [comment]
Hi thanks.
Here is the URL link for a japanese page (for test).

https://www.cbre-propertysearch.jp/office/

and the js code:
(function(a,e,f,g,b,c,d){a.MauticTrackingObject=b;a[b]=a[b]||function(){(a[b].q=a[b].q||[]).push(arguments)};c=e.createElement(f);d=e.getElementsByTagName(f)[0];c.async=1;c.src=g;d.parentNode.insertBefore(c,d)})(window,document,"script","http://52.42.28.233/mtc.js","mt");mt("send","pageview");

**Comment by escopecz** [comment]
The error in the dev tools console:
`Mixed Content: The page at 'https://www.cbre-propertysearch.jp/office/' was loaded over HTTPS, but requested an insecure script 'http://52.42.28.233/mtc.js'. This request has been blocked; the content must be served over HTTPS.`

You cannot load http asset to https site. I'll close this PR since it's not a Mautic issue.

**Comment by robbenyam** [comment]
Hi escopecs,
Thank you for your help.
Could you delete the link what i inserted?

Thanks

**Comment by escopecz** [comment]
I don't see any link you inserted into this issue.
