### ISSUE TITLE
Pre-loaded date filter does not match date axe in dash (unless you click apply)

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3856]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y

## Description:
The From and To date showing at the top of, for example, the dashboard always show the last 30 days, however, this is not applied to the chart below unless you click Apply. 

This is contrary to how other tools, eg, GA, piwik, etc work and so may be confusing. I would expect the from and to dates to always match the table below and clicking apply would only be meeded if I have changed the dates myself.

I suggest that the dates match the chart below and can, of course, still be used to change what data is displaying. As it is in Piwik and GA, showing the last month by default is the best option.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Open mautic, go to dash
2. See dates at top of page, they should be defaulted to last 30 days.
3. check, do they match the dates in the chart below? 
4. If not, click apply, now data matches
5. Would expect data to match at step 2 - 3

**Comment by escopecz** [comment]
I've never noticed such inconsistency. My chart date axe is always the what the date filter shows. Anyone have the same issue?
![screen shot 2017-04-13 at 15 54 24](https://cloud.githubusercontent.com/assets/1235442/25007735/c48e5772-2061-11e7-8ba0-aa6808217d64.png)

**Comment by gingerling** [comment]
I am wondering if it is just when the account is new? Both of mine are fairly new. I will do a few tests and see if this continues now I have clicked "apply" the first time.

**Comment by gingerling** [comment]
I am still noticing this

![screenshot from 2017-04-25 13-42-43](https://cloud.githubusercontent.com/assets/2853040/25385864/3d462c9e-29bd-11e7-989c-d8de9fa05169.png)

That is my dash today just as it loaded by default, the date axe and date filter do not match

**Comment by gingerling** [comment]
Hi, noticed again today. I am now checking it isn't caused by any of my plugins etc, but I have to wait a few days for each test for it to get out of sync again.

**Comment by gingerling** [comment]
Same on my android using mobile browser

**Comment by gingerling** [comment]
I think I have pretty consistently shown this bug exists, so would like it to be marked as a bug please.

I agree it's odd that it does not replicate, is there any chance this is something specific to mautic.net? I have no idea how to contact them, they are just non-responsive for free account customers it seems.

**Comment by RCheesley** [comment]
Unable to replicate this in 2.16.1 so closing this issue down. Feel free to open a new issue and reference this one if it is a problem in the future.
