### ISSUE TITLE
Adding "Unidentified Users" as a possible campaign starting point

### ISSUE THREAD

**Issue by saint2016** [mautic/mautic#3859]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
At the moment a campaign can start either from a segment or from a form. In an ideal world, there would be a third option that starts with the user status, specifically for the unidentified users.

The main use case scenario for this would be to take actions to try to identify the unknown users. For example, a user came in, we don't know who she is, if browses to mid page --> show a focus form with "Do you like what you see? Leave your email." message.

We could do this for everyone but that would be annoying. API requests also would do this (get userid from cookie, ask the API if identified, then show something (or not) using a server side script) but that would be too resource intensive.

I might be missing an obvious way of doing this, if so pls comment. If not that sounds like a crucial feature to me in such a powerful marketing platform.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
It'đ possible now use Segments filter (propably also Campaign conditions):

 https://mautic.org/docs/en/contacts/manage_segments.html

**Comment by saint2016** [comment]
Thanks so much for the comment.

How would you suggest implementing this - create a segment with "Date Identified" empty? 

Also, wouldn't having a segment like this be too resource heavy with every segment cron update having to go through the majority of the contacts?

**Comment by escopecz** [comment]
I'd also recommend Kuzmany's advice. It's not that resource heavy and the same thing would have to be done when executing campaigns so you wouldn't save any resources. The selection have to be done either there or elsewhere.

The answer to your question is yes.
