### ISSUE TITLE
[UX] Hyphenation on 404 error text

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#386]
A little annoyance really but the word is split onto two lines without hyphenation - ideally would suggest it just drops onto two lines without splitting the word up, or at a minimum use a hyphen?

**Comment by alanhartless** [comment]
Are you referring to this hyphen?

![](http://dvkrd.co/drop/2015-05-09_14-54-47.png)

We're using CSS to do that so maybe the browser you're using doesn't support it? Although I thought we pretty much hit them all with:

```
.break-word {
    -ms-word-break: break-all;
    word-break: break-all;
    word-break: break-word;
    -webkit-hyphens: auto;
    -moz-hyphens: auto;
    hyphens: auto;
}
```

**Comment by RCheesley** [comment]
Yes - using Firefox no hyphen shows.  It looks a bit untidy with the hyphen
in my opinion but I guess if you've gone to the trouble of using CSS to
insert it you really want it there!

Ruth
On 9 May 2015 8:58 pm, "Alan Hartless" <notifications@github.com> wrote:

> Are you referring to this hyphen?
>
>
> <https://camo.githubusercontent.com/76fc0ab8884445b8e3980c40d33e983eaf4df5c5/687474703a2f2f64766b72642e636f2f64726f702f323031352d30352d30395f31342d35342d34372e706e67>
>
> We're using CSS to do that so maybe the browser you're using doesn't
> support it? Although I thought we pretty much hit them all with:
>
> .break-word {
>     -ms-word-break: break-all;
>     word-break: break-all;
>     word-break: break-word;
>     -webkit-hyphens: auto;
>     -moz-hyphens: auto;
>     hyphens: auto;
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/386#issuecomment-100539007>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by alanhartless** [comment]
Well, it's not that we necessarily really want it there as the css class was a helper we just utilized :-) But definitely open to suggestions.  So you would rather it just push the entire word to the next line and not split?

**Comment by RCheesley** [comment]
I think that would make it look a bit tidier, but then I'm a bit
old-fashioned when it comes to grammar ;)

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 11 May 2015 at 16:22, Alan Hartless <notifications@github.com> wrote:

> Well, it's not that we necessarily really want it there as the css class
> was a helper we just utilized :-) But definitely open to suggestions. So
> you would rather it just push the entire word to the next line and not
> split?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/386#issuecomment-100942038>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by dbhurley** [comment]
This has been fixed. (And completely agree, I despise hyphens in most use cases ;) - the full word next line is way better).
