### ISSUE TITLE
Contact time zone update

### ISSUE THREAD

**Issue by moltar** [mautic/mautic#3867]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | n
| Feature request? | y
| Enhancement? | y

## Description:
It'd be great to be able to update contact's time zone from GUI and API.

I see that there is a column `timezone` already on the `leads` table and some plugins are making use of that. But seems to be there is no way to change the value of that.

**Comment by escopecz** [comment]
> But seems to be there is no way to change the value of that.

It's being updated automatically from the contact's page hits, his browser settings. But if the timezone is not editable otherwise, it is a bug.

**Comment by moltar** [comment]
My current use case is to add contacts from API, for which I want to supply a timezone myself.

**Comment by escopecz** [comment]
Tested now and it works:
<img width="1153" alt="screen shot 2018-10-23 at 11 36 03" src="https://user-images.githubusercontent.com/1235442/47351256-e2f70980-d6b7-11e8-831f-19af89384b87.png">
