### ISSUE TITLE
Variants don't have unique preview URLs

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#387]
It seems that the unique preview URLs have been lost for variants, and it's not possible to view them without hard-coding the URL.

Secondly, it would be very useful to be able to view variants without a login if the specific URL is provided, so that in the case of agencies with clients who need to sign off, they can send the client the URL for the variants and they can view them separately without the need to log in.

**Comment by RCheesley** [comment]
No errors, but if I view the file it's trying to access if I switch between grid/list view I get this:

File accessed: http://mauticurl.com/app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager/connectors/php/filemanager.php?path=%2F&mode=getfolder&showThumbs=true&time=980&type=Images

I see a bunch of these errors being shown:

<b>Warning</b>:  date(): It is not safe to rely on the system's timezone settings. You are *required
* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any
 of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in <b>/mauticpath/app/bundles/CoreBundle/Assets/js/libraries/ckeditor/filemanager
/connectors/php/filemanager.class.php</b> on line <b>247</b>

**Comment by alanhartless** [comment]
@RCheesley I'm assuming that last reply was for #379?

**Comment by RCheesley** [comment]
No, this was the correct issue.  The only thing I can do when the file upload window is open is toggle between the grid and list view (top right in the image upload screen).

When I do that, I get the messages posted when I view the files being accessed in console.

**Comment by alanhartless** [comment]
This issue is for the landing page variant preview URLs. :-)

**Comment by RCheesley** [comment]
Oooh, yes my bad, how did that happen #blondemoment :panda_face:

**Comment by RCheesley** [comment]
Do you need folk to test these? If so, how do you want them reported etc?
