### ISSUE TITLE
Outlook two column issues when using email builder

### ISSUE THREAD

**Issue by YusufCA** [mautic/mautic#3871]
What type of report is this:

| Bug report? | 

## Description:
Two column layout in email builder does not work correctly in Outlook. The second column always appears underneath the first column.

Image example: 
![outlook](https://cloud.githubusercontent.com/assets/27734155/25141445/77571c2a-245b-11e7-992d-dd6623d65135.png)

## If a bug:
| Mautic version | 2.7.1
| PHP version |  5.6.24-0+deb8u1

### Steps to reproduce:
1. Select a template using the Email Builder
2. Select Two Column Layout
3. Send test email to Outlook
 
### Log errors: 

web/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []

**Comment by autoize** [comment]
We encountered this issue with a two-column email in 2.7.1 as well.

The email width is 600px wide, and each of the columns are 300px wide, with 10px cell padding and 10px cell spacing. The cell spacing is making the columns' width total larger than the parent element, thus dropping one of the elements down below.

We worked around this by reducing the width of the columns.

**Comment by npracht** [comment]
Maybe use https://innotiom.com/responsive-multi-column-sections-mautic/

**Comment by pstevens71** [comment]
I'm having this issue right now @autoize how did you solve it?

**Comment by autoize** [comment]
We changed to code mode and modified the width of the columns using style attributes.
Haven't run into it again recently.

**Comment by pstevens71** [comment]
Hey thanks for the input.  I used code mode, and then copied the code to a new template folder "my template" for example and then copied over the files from "blank" and then just copied the HTML into the HTML file, then edited the column width there.  I can now use my custom template for any two column emails.  Because it's a template, new emails generated from it already have the proper column width.

**Comment by pstevens71** [comment]
@autoize actually I just found a better solution.  I found the code that generates the 2 column.
app/bundles/CoreBundle/Views/Sections/two-column.html.php

Change line 17 (the 300 width) to:
 <table align="left" border="0" cellpadding="10" cellspacing="0" width="290" class="mobile-block">

Change Line 26 (the 300 width & the "align="right"") to:
<table align="left" border="0" cellpadding="10" cellspacing="0" width="290" class="mobile-block">

And it works great both in browser and in MS Outlook.  You have to change to align left, or in the browser at mobile width you see the space on the left.  I've tested in mobile and in Outlook and this change fixes it.
