### ISSUE TITLE
facebook pluagin for mautic  HTTP ERROR 500

### ISSUE THREAD

**Issue by ninem** [mautic/mautic#3875]
What type of report is this:

| Q  | A
| ---
-| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

hi :)

when i try to authorize  the facebook pluginin in mautic  i get a pop up window saying  :
HTTP ERROR 500 
any help please :)

**Comment by escopecz** [comment]
Please follow https://mautic.org/docs/en/tips/troubleshooting.html and let us know what the actual error message is.

**Comment by ninem** [comment]
hi 
thanks for the quick answer 
my [mautic_root]/app/logs is empty

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/issues/4008 in Mautic 2.8.2
