### ISSUE TITLE
Add a tag to every form conversion

### ISSUE THREAD

**Issue by tuliobbs** [mautic/mautic#3877]
I am used to use a simpler autoresponder and I guess many people who try mautic are too!
Therefore I leave my suggestion: 

I am used to choose who to send an e-mail to like this:
(segments to _send to_ on the left and segments to _exclude_ on the right)
<img width="987" alt="screen shot 2017-04-20 at 11 27 07" src="https://cloud.githubusercontent.com/assets/27643901/25235706/54a4df5c-25bc-11e7-867e-148ea2498d76.png">

In Mautic I can only send to an entire segment. It is a bit confusing to me.
It seems like one extra step (to create the specific segment before the e-mail itself instead of during it).

Also, another thing that would be a lot easier for me is to automatically add a tag to every form the user converts to or another easy way to track that conversion (even if I want to track that conversion _after_ the conversion has been done)

This way I can easily send an e-mail to:
all the people who converted on the "free homebrewing ebook" and "free video course on how to clarify beer" forms and remove all the people who have already converted on "I dont want to know how to brew, I only want to drink good beer". Note that the people I excluded from this e-mail still want to receive infos from me, but not about the topic of this e-mail (brewing beer).

I know this might not be the goal of Mautic, that focuses on more automated things, but I think it would increase the satisfaction of people who are giving a shot at mautic!

Thanks (:

**Comment by escopecz** [comment]
I think that you can configure both things with Mautic:
1. Create a segment which includes contacts from one segment and excludes contacts from other.
![screen shot 2017-04-20 at 16 51 09](https://cloud.githubusercontent.com/assets/1235442/25237095/021207fa-25ea-11e7-896c-036052b42383.png)
2. Create a form action which adds tags to contacts who fill out the form.
![screen shot 2017-04-20 at 16 53 49](https://cloud.githubusercontent.com/assets/1235442/25237097/044b4072-25ea-11e7-9707-dfc3336ddb23.png)

**Comment by tuliobbs** [comment]
Cool! Thanks!

What I said about the tags to whoever converts on forms was for it to be automated, like instead of a tag:A it would be form:A. So I don't need to create a tag for each form.

And for the segments, in this case I would have one segment for each campaign I send, right? If I could segment just for that campaign, I would have a much smaller number of segments created.

I just think it would be easier for those who come from other softwares...

But I see it works just fine! Thanks!

**Comment by tuliobbs** [comment]
@escopecz 
Cool! Thanks!

What I said about the tags to whoever converts on forms was for it to be automated, like instead of a tag:A it would be form:A. So I don't need to create a tag for each form.

And for the segments, in this case I would have one segment for each campaign I send, right? If I could segment just for that campaign, I would have a much smaller number of segments created.

I just think it would be easier for those who come from other softwares...

But I see it works just fine! Thanks!
