### ISSUE TITLE
FullContact plugin doesn't work unless a one line edit is made

### ISSUE THREAD

**Issue by LeapingDragon** [mautic/mautic#3878]
See this thread for more info https://www.mautic.org/community/index.php/6263-fullcontact-pluign-don-t-callback

**Comment by maxSupermoney** [comment]
I already submitted a patch before you created the issue. It looks like it will be fixed in the next release.
https://github.com/mautic/mautic/pull/3851

**Comment by ericseguin** [comment]
This edit that was made with the fullcontaact mautic plugin seems to be broken again, because I and a lot of other people are getting the callback errors again. Has something changed in the code?
