### ISSUE TITLE
Reset stage all Leads

### ISSUE THREAD

**Issue by lucasmoraes804** [mautic/mautic#3882]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
I want reset step all my Leads. If I no have options to do this, How can I clean in Data Base? 
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Remove stage and create new

**Comment by lucasmoraes804** [comment]
I got it. Thank you!
