### ISSUE TITLE
Need to check if OneSignal is loaded before making method calls

### ISSUE THREAD

**Issue by moltar** [mautic/mautic#3884]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:
Some ad blockers will block OneSignal from loading. Need to make sure that the it is checked if object has loaded (or has method)

Error in Chrome console:

> GET https://cdn.onesignal.com/sdks/OneSignalSDK.js net::ERR_BLOCKED_BY_CLIENT
> foo:40 Uncaught TypeError: OneSignal.getUserId is not a function
    at foo:40

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | N/A

### Steps to reproduce:
1. Install Ad Blocker
2. Visit landing page
3. Check console
 
### Log errors: 

> GET https://cdn.onesignal.com/sdks/OneSignalSDK.js net::ERR_BLOCKED_BY_CLIENT
> foo:40 Uncaught TypeError: OneSignal.getUserId is not a function
    at foo:40

**Comment by stevegrant1983** [comment]
I think it also need to check if notifications are enabled within Mautic - it shouldn't be loading a JavaScript library it has no intention of using.

**Comment by chrisknu** [comment]
Slightly related, It'd be helpful if Mautic tested if OneSignal is already init()'d on the page prior to loading the lib and initializing a second time.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
