### ISSUE TITLE
How to find contacts added in a month?

### ISSUE THREAD

**Issue by grahampople** [mautic/mautic#3886]
What type of report is this:

I'm trying to find a way of seeing how many contacts were added in April.  Every way I've tried to do it hasn't worked, so I guess this is a bug report.

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
My latest attempt is to setup a segment like this:

![image](https://cloud.githubusercontent.com/assets/795437/25306407/c2eb8bb8-27b6-11e7-8d2d-0f02a549c3f9.png)

But this shows zero contacts, even though there are around 30 new contacts added so far in April.  So I guess this is a bug?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | I'm using the free hosted version of Mautics.
| PHP version | 

### Steps to reproduce:
1. See above.
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

Don't think I have access to these on free hosted version, please correct me if I'm wrong.

**Comment by kuzmany** [comment]
set equals and this month

**Comment by grahampople** [comment]
Hi, thanks for the suggestion.  I went to give this a try, and found something odd - the segment I created above, which had 0 contacts yesterday, now has the expected number.  So I guess this is one of those things that's on a cron job?

**Comment by kuzmany** [comment]
segments are rebuild with cron 

https://mautic.org/docs/en/setup/cron_jobs.html

**Comment by kuzmany** [comment]
you can use relative dates like yesterday, this month, last monht or -10 days, +1 month etc

**Comment by grahampople** [comment]
Ok, that's pretty cool, will give that a try.

I'm going to close this as, while it's not particularly intuitive that the segments only update after a while (I use the free hosted version of Mautic and the cron thing isn't explained there, as far as I know), it does work as designed.
