### ISSUE TITLE
HTTP ERROR 500 with Mautic installation on https://mossmail.info/installer

### ISSUE THREAD

**Issue by mercebenz** [mautic/mautic#3889]
Dear Sir or Madam,

This is a | Q  | A 
I need help to troubleshoot a HTTP ERROR 500 on mautic installation at https://mossmail.info/installer.

I am on Mautic 2.7.1 and PHP 7.

Steps taken

I deleted the cache and the problem remains
There is no data in the log file

 I am at my wits end and need help. Thanks for your assistance.

Sincerely
Mercedes Moss

**Comment by escopecz** [comment]
My guess is that Mautic doesn't have permission to write files into the cache and logs directories.

**Comment by mercebenz** [comment]
Hello John

Thanks a lot. How do I fix this?

Thanks
Mercedes

Sincerely
Mercedes Moss


Facebook <http://facebook.com/fit.fabulous.secrets>

Vocal coach <http://freesingingcourse.wordpress.com>

Love the Bible <http://pppministries.wordpress.com>

Talk with Angels <http://thelordsangels.wordpress.com>

From Breakup To Makeup <http://from-break-up-to-makeup.blogspot.com/>

Online Promotions  SVG
<http://onlinepromotionssvg.blogspot.com/p/freebies-in-news.html>

Read my books on Amazon.com
<https://www.amazon.com/Mercedes-Moss/e/B01JOHHQSS>

How To Blog On Google Blogspot
<http://how-to-blog-on-google-blogspot.blogspot.com>

How To Build A List Of Subscribers
<https://youtu.be/daXdrRjtvK0?list=PLYj4M0YUYqfaUTBGgG86GNWnLrrK73HzE>

<https://trafficmonsoon.com/?ref=angel_lady>
Get Highly Responsive Website Traffic
<https://trafficmonsoon.com/?ref=angel_lady>

My favorite music <https://youtu.be/k_OBsm-cBZk>

**Comment by escopecz** [comment]
It depends on your server OS. Consult it with your server provider / administrator

**Comment by skynet** [comment]
@escopecz - tickets like this should be closed after a while, especially when feedback is very poor. You guys have 947 issues open and should rather focus on what's relevant to the core. I mean, seriously, I feel like I need to come work for you and get this great marketing platform ready for Enterprise. Just a thought :-)

**Comment by escopecz** [comment]
I think you should apply! I closed some issues today. The counter shows 881 now. Still many to go through though.

**Comment by skynet** [comment]
Absolutely! Mautic is the WordPress of Marketing Automation. No doubts. Just need enough support and faster bug fixing, faster releases.

**Comment by jcrick69** [comment]
escopez - so what is the solution please? 'guessing' is not really a good answer. Now I have the same issue as mercebenz...
Runing Mautic 2.14.2, with PHP 7.1 under IIS.
Gave Everyone read write access to logs and cache.
Makes no difference still getting a 500 with installer - the site finds favicon.ico just fine.
Thanks, Jerry

**Comment by escopecz** [comment]
@jcrick69 I wouldn't have to guess if some error message from the logs would be provided. Read https://www.mautic.org/docs/en/tips/troubleshooting.html, create new issue and fill in all requested info in it. That would make issue resolving very convenient.

**Comment by jcrick69** [comment]
OK, thanks, will do.

But, like mercebenz, there is nothing in the logs.

Thanks, Jerry

**Comment by Woeler** [comment]
500 errors are usually also not logged in the application log, but in the server log, e.g. Apache or NGINX.
