### ISSUE TITLE
External link doesn't do anything in email builder

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#389]
If I need to insert an external link into an email, I'd expect to press the 'external link' button beneath the landing pages that are available, however pressing this does nothing and there's no error being output in the browser console either - using Firefox with Mautic 1.0.5.

**Comment by alanhartless** [comment]
Hey Ruth,

Can you try to drag and drop the external link into an editor and see if the modal appears?  Otherwise, the builder doesn't know what editor instance to insert the token into.

Thanks,
Alan

**Comment by RCheesley** [comment]
Hi Alan,
I think this is a UX issue rather than it not working.  I was expecting that I could save a bunch of external links which I use all the time (e.g. links to social media) in a list - much like you do assets - which would then be available for future use.

I had no idea that you were supposed to drag/drop the external link onto the email - in fact unless you had said this, I would never have thought to try that.

Firstly, what a pain to have to re-enter the URL every time I need to use it!  Secondly, not very clear that you're supposed to do this drag/drop to create it, what if I want to use it as a href around an image in code, for example?  Could there be more clarity on this in the UI?

Ruth

**Comment by RCheesley** [comment]
Furthermore, this makes it impossible to copy code blocks containing links from one email to another, for example.  I would have to recreate the links in every campaign, so I may as well just start from scratch again!

**Comment by alanhartless** [comment]
Hey Ruth,

Would #353 null the drag/drop UX and image as a link issues?  If we went that route though (auto convert links), you would still have to manually insert your links so not sure that would help with "what a pain to have to re-enter the URL every time I need to use it."  We could provide a list of "recently used" URLs maybe? Or would you want a list of every external URL you've used?

I'm not sure I'm following the impossible to copy code blocks statement though, unless you're trying to copy directly from the editor.  It seems that ckeditor doesn't copy the code (or maybe it's a browser security restriction) but just the text so you would have to view the source, then copy the code block from there.

**Comment by RCheesley** [comment]
Yes, that would help enormously, I think.  It would also mean I could copy/paste blocks of code into different emails as well, without having to create the URLs.  For example if I have my social icons or similar styled nicely and linked up, I can go to code view, copy them, paste into another resource and the URLs would be tracked.  If I had to manually recreate each hyperlink using the external link feature, that would suck :)

Having a repository of snippets would be really great (already been requested) but for now we'll probably just store them somewhere internally.

**Comment by alanhartless** [comment]
Okay; I'm going to close this in favor of #353 then.
