### ISSUE TITLE
Reset tags all Leads

### ISSUE THREAD

**Issue by lucasmoraes804** [mautic/mautic#3892]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  X
| Enhancement? | 

## Description:
I want reset al tags ofl my Leads. If I no have options to do this, How can I clean in Data Base?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
1. Create a segment with filter that will match all contacts
2. Create a campaign
    2.1 Choose the segment from 1 as the source
    2.2 Add action to modify tags
        2.2.1 Select all tags in the remove tags select
3. Run the "campaign:update" and "campaign:trigger" commands or wait when your cron kicks those commands.
