### ISSUE TITLE
app.js:190 Uncaught DOMException: Blocked a frame with origin "https://resources.incarta.com.au" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by sureshsuthar2011** [mautic/mautic#3893]
What type of report is this:

| Q  | A
| ---| ---
I have use mautic newsletter embeded code for my site. Here is my js 
    `code: var MauticSDKLoaded = true;
      var head = document.getElementsByTagName('head')[0];
       var script = document.createElement('script');
       script.type = 'text/javascript';
        script.src = 'https://resources.incarta.com.au/media/js/mautic-form.js';
         script.onload = function() {
          MauticSDK.onLoad();
          };
         head.appendChild(script);
        var MauticDomain = 'https://resources.incarta.com.au';
        var MauticLang = {
         'submittingMessage': "Please wait..."

        }`

When I try to submit my form, the following error shows on console: 

> app.js:190 Uncaught DOMException: Blocked a frame with origin "https://resources.incarta.com.au" from accessing a cross-origin frame.

| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Hi, please provide steps which you've taken. Also I don't know what "mautic newsletter embeded code" is. From the code you posted it seems like it is Mautic form embed code.

Based on the error message "accessing a cross-origin frame", it seems like a CORS issue. Did you enamble CORS in Mautic configuration and white-listed your website domain?

**Comment by sureshsuthar2011** [comment]
Thanks for replay @escopecz , i have use mauticform snewsletter embed code , here is i not putted just putted js code.
this error showing on console  after form submit..
After error then form can not do anything.

**Comment by escopecz** [comment]
How about the CORS setting?

**Comment by sureshsuthar2011** [comment]
setting is 'yes' and valid domain name is incarta.com.au

**Comment by escopecz** [comment]
Try to add `resources.incarta.com.au` into the next line

**Comment by sureshsuthar2011** [comment]
i tried but not working
can you please tell me below screen shot data is right or not?
[https://nimbus.everhelper.me/client/notes/share/880294/dnwogp5tyu9ku2px1r9c](https://nimbus.everhelper.me/client/notes/share/880294/dnwogp5tyu9ku2px1r9c)

**Comment by escopecz** [comment]
That's not the CORS setting.

**Comment by sureshsuthar2011** [comment]
yes i know that but, i am new in mautic

**Comment by escopecz** [comment]
No problem. Could you share the link to the website where you have the problem?

**Comment by sureshsuthar2011** [comment]
[http://clics.saltandfuessel.com.au/test/](http://clics.saltandfuessel.com.au/test/)
here is two form 
one newsletter form and one is contact form

**Comment by escopecz** [comment]
Ok, this domain should be on the CORS white list: `clics.saltandfuessel.com.au`

**Comment by sureshsuthar2011** [comment]
ok now i updated

**Comment by sureshsuthar2011** [comment]
but it still can't work

**Comment by ronnieduke** [comment]
Hey there. I am also having this issue. Site is www.rampmetrics.com and it is my request demo form. I added 'rampmetrics.com' to my CORS setting and still no luck. Form does not appear to submit

**Comment by sureshsuthar2011** [comment]
hi @ronnieduke , if you get any solution of this problem then inform me please

**Comment by ronnieduke** [comment]
@escopecz - any update on this? I've tried every version of rampmetrics.com (http, https, www, etc) and even turned CORS off entirely and it's still having the same issue. Does Mautic have a bug with https sites? I've also tried the straght JS embed, as well as using the WP plugin and both behave the same way.

**Comment by ronnieduke** [comment]
@escopecz - nvm about the https thing. I just temporarily turned it off and having the same issue.

**Comment by jordan8037310** [comment]
#4287 might be related

**Comment by mackina** [comment]
Also experiencing this issue - worked fine until update to 2.9. Ran through similar tests to @ronnieduke but getting this error:

Uncaught DOMException: Blocked a frame with origin "https://info.formisimo.com" from accessing a cross-origin frame.
    at HTMLDocument.<anonymous> (https://info.formisimo.com/media/js/app.js?v57976ab6:219:67)
    at fire (https://info.formisimo.com/media/js/libraries.js?v57976ab6:328:299)
    at Object.fireWith [as resolveWith] (https://info.formisimo.com/media/js/libraries.js?v57976ab6:333:198)
    at Function.ready (https://info.formisimo.com/media/js/libraries.js?v57976ab6:340:11)
    at HTMLDocument.completed (https://info.formisimo.com/media/js/libraries.js?v57976ab6:340:291)

**Comment by escopecz** [comment]
Please check if it's not the misconfiguration described in https://mautic.org/docs/en/forms/index.html#form-error-messages-does-not-show-up-or-form-redirect-is-not-working

**Comment by mackina** [comment]
Thanks @escopecz - checked domain setting in config, was fine (pointing to https) and rebuilt forms but still have issue.

**Comment by mackina** [comment]
@escopecz You can see an example form here: https://www.formisimo.com/request-demo

On completion the user should be redirected to another page

**Comment by williamknn** [comment]
Same issue here. Even turning off the restricted domains setting.

**Comment by williamknn** [comment]
Have anyone solved this?

**Comment by rgamarra-navent** [comment]
¿Any further info about this?

**Comment by rgamarra-navent** [comment]
@mackina did you happen to solve this at last?

**Comment by rgamarra-navent** [comment]
@williamknn did you?

**Comment by williamknn** [comment]
@rgamarra-navent Sorry, I don't remember what I did to fix :/

**Comment by williamknn** [comment]
Are you using the Bitnami Mautic machine? Whats the Mautic version?

**Comment by rgamarra-navent** [comment]
@williamknn it's embeded in a wordpress page

**Comment by MyluckMomentum** [comment]
Same issue here. After update from 2.13.1 to 2.15.1

**Comment by RCheesley** [comment]
Closing due to being CORS issues rather than a bug. Please post support requests at https://forum.mautic.org
