### ISSUE TITLE
Dashbord showing non-existent contacts (bug or UX issue)

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3895]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y (or UX issue)
| Feature request? | N
| Enhancement? | N

## Description:

My dashboard is showing contacts created which I can't find in my system elsewhere. This is a new account with very little data.

![screenshot from 2017-04-24 11-36-31](https://cloud.githubusercontent.com/assets/2853040/25333796/ba73344e-28e3-11e7-8bc9-0cb51dbbc0e0.png)

You can see a large bump in data on April 1st and a steady stream of data after that with a few contacts each day.

When I look at my contacts there are 3 there, which are from a kiosk mode form at the last meeting I had, which is all I would expect to be in there just now.

![screenshot from 2017-04-24 11-36-17](https://cloud.githubusercontent.com/assets/2853040/25333725/579ed670-28e3-11e7-94e6-1deb9833b819.png)

Either this is a bug or a UX issue I think. ++ confused.

## If a bug:

Using mautic.net

**Comment by escopecz** [comment]
The Contacts table show only identified contacts by default. The anonymous contacts which are usually created by page hits are filtered out, but you can view them when you click the button with the icon of a man wearing a hat in the top-right corner of your second screenshot. Does this answer your question where are all those contacts in your system?

Also, if you edit the contact widget, you can specify whether you want to see only identified or anonymous.

**Comment by gingerling** [comment]
This is a bug for sure then, as mine is set to default (I didn't know you could change it, but I checked and it's set to "Created contacts in time" as you say it would be) and it's showing way more contacts than I have (as shown in images above)

![screenshot from 2017-04-24 12-13-17](https://cloud.githubusercontent.com/assets/2853040/25334712/ae68d2b8-28e7-11e7-8577-f967c1fbfac7.png)

**Comment by escopecz** [comment]
I don't follow. What happens when you change it to "Only identified"?

**Comment by gingerling** [comment]
Sorry, I see, so you are saying that anonymous contacts are filtered out of the contacts page list but not from the dash (by defaulr)? I though you meant they were filtered out of the dash by default. 

If I click the little man I see all of these:

![screenshot from 2017-04-25 13-13-05](https://cloud.githubusercontent.com/assets/2853040/25384654/12d1855c-29b9-11e7-887d-6e8612020edb.png)

In this case, why are there so many duplicated contacts with the same IP address?

For example in this image

![screenshot from 2017-04-25 13-15-21](https://cloud.githubusercontent.com/assets/2853040/25384730/4685f82e-29b9-11e7-9f89-840129cc1ebf.png)

They all have the same IP and location but are separate contacts

**Comment by grahampople** [comment]
Ok, this issue helped me understand why the first big widget on my default dashboard was telling me I was getting 40-60 new contacts a day - when I only get a few signups really.  So they're all unidentified IPs... bit confusing!  Especially as clicking Contacts in the sidebar only shows actual signed up users.

**Comment by gingerling** [comment]
Yes, can I suggest that some change in terminology or hover-over-info be considered for this issue?
