### ISSUE TITLE
BUG: Global category events don't get the correct colour in the calendar

### ISSUE THREAD

**Issue by merlin0** [mautic/mautic#3901]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? | 

## Description:
Events in the Calendar used to get the colour that corresponded with the colour of the category. However when using global categories the events don't get the colour from the category anymore and get the default blue colour. If  a campaign category is assigned to the campaign the scheduled events do get a different colour.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.7.1
| PHP version | 7.x

### Steps to reproduce:
1. Create a campaign with some actions, like sending a mail or rewarding a lead with points. 
2. Create a global category and assign a colour that is different from the default blue.
3. Assign the global category to the campaign.
4. Add a lead to the campaign.
5. Check the scheduled events in the calendar.

**Comment by RCheesley** [comment]
Able to reproduce this on 2.16.1. If i use a global category associated with the campaign, the default blue colour is used.

If I use a category which is associated with the Campaigns bundle, then this colour is used.

I'd expect as a user that if a category with a colour is assigned, that colour should show in the calendar.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.
