### ISSUE TITLE
Bug Report: for ProcessFetchEmailCommand.php - Plugin Injected Criteria is not being considered in execution!

### ISSUE THREAD

**Issue by peteratnsight** [mautic/mautic#3902]
Context:
/app/bundles/EmailBundle/Command/ProcessFetchEmailCommand.php

At line 106 only unread messages are considered for execution:
106: $mailIds = $imapHelper->fetchUnread();

IMHO - in order to execute criteria that is injected by an EmailSubscriber the code
needs to changed to:
106: $mailIds = $imapHelper->searchMailBox($criteria);

This makes sure that all criterias (that are injected by specific EmailSubscriber methods) are
executed. "All Unread" can thus been defined as default criteria.

**Comment by RCheesley** [comment]
Closing issue as no longer exists in code as detailed.
