### ISSUE TITLE
Mautic Gmail Tracking produces an PHP Error b/c of non-existing Stat-Object

### ISSUE THREAD

**Issue by peteratnsight** [mautic/mautic#3908]
Bug - when sending an email from Gmail with Mautic Tracking flagged - this error occurs in some cases: [2017-04-25 14:22:53] mautic.ERROR: PHP Error: Call to a member function setSource() on null - in file /mautic/app/bundles/EmailBundle/Controller/PublicController.php - at line 591 [] []
[2017-04-25 14:22:53] mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Error: Call to a member function setSource() on null - in file /mautic/app/bundles/EmailBundle/Controller/PublicController.php - at line 591 [] []

Checking source code brings up following:

app/bundles/EmailBundle/Controller/PublicController.php
Line 591 ff

            $stat->setSource('email.client');
            // stat doesn't exist, create one
            if ($stat === null) {
                $lead['email'] = $email; // needed for stat
                $this->addStat($lead, $email, $query, $idHash);
            }

Bug fixing IMHO is - going into the if-clause first and then setting the
source. For this the addStat method needs to return a stat object.

            // stat doesn't exist, create one
            if ($stat === null) {
                $lead['email'] = $email; // needed for stat
                $stat = $this->addStat($lead, $email, $query, $idHash);
            }
            $stat->setSource('email.client');

Additional change needed at 
Line 646 in addStat method - adding a return statement to the last line 
of the method

            return $mailer->createEmailStat();

**Comment by RCheesley** [comment]
Closing issue as no longer able to test due to Chrome/Gmail plugin being broken.
