### ISSUE TITLE
Focus not working / HTTP 500 viewpixel.gif

### ISSUE THREAD

**Issue by wucherpfennig** [mautic/mautic#3909]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
If you are using a focus item there is a cal to viewpixel.gif which results in a HTTP 500 and therefore the focus item is not working.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.7.1
| PHP version | PHP Version 5.6.30

### Steps to reproduce:
1. Use a focus item
2. GET /focus/5/viewpixel.gif 500 ()

**Comment by escopecz** [comment]
Please provide the error message from the logs. See https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by wucherpfennig** [comment]
`[2017-04-26 08:44:20] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'MauticPlugin\MauticFocusBundle\Entity\Stat#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at XYZ/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'MauticPlugin\\MauticFocusBundle\\Entity\\Stat#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at XYZ/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []`

**Comment by wucherpfennig** [comment]
note: Update to latest version 2.8 does not fix this issue

**Comment by dirtroof** [comment]
Can confirm this issue. Error Message is:
`[2017-07-07 08:57:42] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'MauticPlugin\MauticFocusBundle\Entity\Stat#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /path/to/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'MauticPlugin\\MauticFocusBundle\\Entity\\Stat#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /path/to/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []`

**Comment by wucherpfennig** [comment]
still preset on 2.9.1

**Comment by wucherpfennig** [comment]
still existing on 2.9.2

**Comment by escopecz** [comment]
This happens only if you visit the page with a Focus item when logged in to Mautic administration only. It works for your contacts. Fixed in https://github.com/mautic/mautic/pull/4663

**Comment by wucherpfennig** [comment]
Probably this will fix it but currently this behaviour can be reproduced on both my live systems even without being logged in...

**Comment by escopecz** [comment]
It cannot happen when you are logged out of Mautic. I tested that. Open the page in the incognito browser window and you'll see the tracking gif will load successfully.

If you want to speed up the release of this fix, please test the code change and comment on the PR if it fixed your problem or not.

**Comment by wucherpfennig** [comment]
This issue is still open. happening with mautic 2.13

**Comment by BillyHilly** [comment]
Any update on this? I'm still seeing it in v.2.14.0
```
[2020-04-01 16:52:23] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'MauticPlugin\MauticFocusBundle\Entity\Stat#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'MauticPlugin\\MauticFocusBundle\\Entity\\Stat#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /path/to/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []
```
