### ISSUE TITLE
Alow multiple conections in campain builder

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3911]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
I would like to do this:

![screenshot from 2017-04-25 18-45-19](https://cloud.githubusercontent.com/assets/2853040/25399578/bda0b6dc-29e7-11e7-8d60-a8288132d969.png)

I have an email with a CTA to fill in a form. The response to the form sets in motion a variety of things, points added, one of two messages sent etc. 

I then send a reminder to those who never completed the form after the first email. The reminder links to the same form again. If the form is filled in after this reminder I want that to set in motion the same things (points added, one of two messages sent etc).

Duplicating all the actions in the builder is a bit annoying. All my actions are for relative time periods so the risk of making a mess is low. Another method could be to allow cloning groups of actions/decisions etc in the builder.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by grahampople** [comment]
Could you split everything from 'Submits form' onwards off into a new "Campaign B", and then have both 'Send email invite' and 'Reminder email 1' move the user to Campaign B?

**Comment by gingerling** [comment]
Sounds like it could work, but looking at the builder I am unclear how to move the users to campaign b, is this documented anywhere. If that did work it would be really useful because I could have some standard, time relative campaigns and then when I repeat for the next months training I only need to replace the "campaign A part" which initially specifies a date

**Comment by grahampople** [comment]
Yeah it's there - Actions -> Change Campaigns.

**Comment by grahampople** [comment]
I'm currently using this approach myself and it seems to work.

Actually I'm also using this same idea for another thing - by breaking up any long campaign into multiple one-weekish long mini-campaigns, and moving users through them linearly.  It means I can add emails to one of the mini-campaigns and they'll actually get sent later to users currently on one of the earlier campaigns - if I just had one big long campaign then they wouldn't get it.

**Comment by gingerling** [comment]
Interesting, I will have a go and feed back!

**Comment by gingerling** [comment]
I am looking at this a little and while I can see how you move the data to the second campaign using change campaign action, I don't understand what to use as the start of the second campaign, I have to choose either a list or a form, and neither make sense in this case.. :/

**Comment by escopecz** [comment]
There is a third option to add a contact to a campaign manually or via the Change Campaign Action. Truth is that the Campaign Builder requires a source. Create an empty segment and use that in this case.

**Comment by gingerling** [comment]
So I could set "change campaign" action at the end of the first campaign, but I would still need a source for the second campaign (blank segment). Interesting. 

Seems like the change campaign feature needs a counterpart, so you would select a source eg. Form A in campaign 1, do other things in that campaign, send emails/tweets etc, and then some paths would end in Change campaign to campaign 2. Campaign two would start with a "from another campaign" for the source.

**Comment by gingerling** [comment]
Make a request https://github.com/mautic/mautic/issues/4428

**Comment by dbhurley** [comment]
Duplicate.
