### ISSUE TITLE
Campaign decision: lead stage 

### ISSUE THREAD

**Issue by wucherpfennig** [mautic/mautic#3912]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | y
| Enhancement? | 

## Description:
currently we are doing some automated lead scoring and therefore it would be nice to proceed with some actions only if the lead is really on a given stage. Therefore we would appreciate it if we would have a possibility to check a leads stage in a campaign.

https://www.mautic.org/community/index.php/7227-campaign-decision-lead-stage/0#p21418

**Comment by kuzmany** [comment]
You can fund this feature now https://mautic-fund.kuzmany.biz/campaign/4/campaign-contact-stages-condition
