### ISSUE TITLE
URL link changed to different URL Link

### ISSUE THREAD

**Issue by Subesrao** [mautic/mautic#3914]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | y
| Enhancement? | 

## Description:
 
Hi team,My URL link changed to different URL Link after blast the email and its not directing to my website. Its showing  **I'm sorry! I couldn't find the page you were looking for. 
404 Not Found**

**URL suppose should be this.**
![image](https://cloud.githubusercontent.com/assets/28031807/25416011/0a664654-2a6e-11e7-85c6-2f3169005ef9.png)

But then its changed different URL links.
![image](https://cloud.githubusercontent.com/assets/28031807/25415981/e4232c0a-2a6d-11e7-951d-c69e111a4ee6.png)

**Comment by escopecz** [comment]
What is the "Site URL" value in the Mautic configuration?

**Comment by Subesrao** [comment]
Problem solved,Thank a lot

**Comment by web30s** [comment]
i have the same issue, how can you fix it. please share your fixed that can help me. Thanks so much.
