### ISSUE TITLE
Change segments in contact details doesn't show any segments

### ISSUE THREAD

**Issue by mrerich** [mautic/mautic#3917]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
After update to 2.8.0 I found out, that when I try to check or modify contacts segments (Contact detail page -> Preferences -> Segments), there is just an empty field and when I try to type a segment name, the answer is No matches found.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.17

### Steps to reproduce:
1. create a segment
2. create a contact
3. in contact detail page click on Preferences -> Segments and try to type the segment name
 
### Log errors: 

error log is empty

![screenshot 2017-04-26 12 56 20](https://cloud.githubusercontent.com/assets/26136473/25431553/5bc6f86e-2a81-11e7-8097-c1f36f3be649.png)

**Comment by escopecz** [comment]
Cannot replicate and no one else is reporting this issue either. Please test with the latest version.
