### ISSUE TITLE
Email Dynamic content broken after upgrade to 2.8.0

### ISSUE THREAD

**Issue by mrerich** [mautic/mautic#3921]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

Hey guys, I am not sure how the dynamic content should work now. Before I used it to insert dynamic content in the body through tokens, directly inside the text, for example. Now I am not able to do it and all my old templates are broken at the moment I make a change and save them.

**Before:**

![obrazek](https://cloud.githubusercontent.com/assets/26136473/25432731/e61a45da-2a85-11e7-9e2e-18ac7f96fd98.png)

![obrazek](https://cloud.githubusercontent.com/assets/26136473/25432783/1e973030-2a86-11e7-9997-634473aded8a.png)

**After update:**

![obrazek](https://cloud.githubusercontent.com/assets/26136473/25432816/42df79ca-2a86-11e7-9fe0-ed50fca1b91b.png)

Also, I lost access to the Dynamic content tab as it was an easy way how to configure it. I used one token on several places in e-mail, how do I do it now? Etc.

I believe both ways (new and old) can coexist together, so we can decide which one is better for what purpose.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.17

### Steps to reproduce:

1. Edit e-mail with dynamic content token created in version 2.7.1 through Builder
2. Save it in 2.8.0 version
3, Edit e-mail again and check the code (pictures above)
 
### Log errors: 

no errors in log

**Comment by virlatinus** [comment]
When you send the email, is the dynamic content broken as well? Are the variations in your current emails working as they are supposed to when you send them?

**Comment by mrerich** [comment]
I apologize, I had to downgrade to 2.7.1 and fix the template, so I do not have an answer for you.

**Comment by mrerich** [comment]
I remember that when I created the dynamic content block, it was prefilled with the first set of vars. Second block was prefilled with second set, etc. So the information was not lost, probably just used different way.

The other problem I have is that I use one dynamic token repeatedly inside the text (for example for inflection or other grammar reasons). I have no idea how I will do the same by using blocks.

**Comment by mrerich** [comment]
Hello, any progress on this? I cannot upgrade to new versions of Mautic, because all dynamic content is then broken and uneditable.

**Comment by mrerich** [comment]
Any progress or idea, how to solve the problem? Thank you for any feedback.

**Comment by mrerich** [comment]
Is it possible to fix the problem in the next release? Because it force me to stay with version 2.7.1

**Comment by mrerich** [comment]
any progress?

**Comment by virlatinus** [comment]
Fixed in #5140
