### ISSUE TITLE
Select Field on Campaign Conditions not Working

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#3924]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N 
| Enhancement? | N

## Description:

When use an select field on Campaign Conditions, the Text / Value are set to [Object]

![download 1](https://cloud.githubusercontent.com/assets/257004/25445725/81dafa2e-2a85-11e7-843d-6b75100d3867.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Since 2.6.0
| PHP version | 7.0

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by luizeof** [comment]
@kuzmany @alanhartless @escopecz

**Comment by isleshocky77** [comment]
@luizeof #3494 is related to this.
