### ISSUE TITLE
Campaign event "decision_path" becomes NULL when saving the campaign without opening the builder

### ISSUE THREAD

**Issue by hrdyrk** [mautic/mautic#3927]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
campaign_events table "decision_path" column becomes NULL when saving or applying the campaign **_without opening the builder_**. But after opening the builder and re-saving the campaign, "decision_path" column is set "yes/no" again. 

Campaign trigger batch can not execute the campaign flow correctly, because decision_path became NULL.  

| id  | campaign_id | parent_id | name  | type | event_type | event_order | trigger_mode | decision_path
| --- | --- | --- | --- | --- | --- | --- | --- | ---
| 427 |          50 |      NULL | email is not null | lead.field_value | condition  |           1 | immediate    | NULL
| 453 |          50 |       427 | add tag(yes)      | lead.changetags  | action     |           2 | immediate    | **_NULL_**
| 454 |          50 |       427 | add tag(no)       | lead.changetags  | action     |           2 | immediate    | **_NULL_**

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.15

### Steps to reproduce:
1. Create a new campaign
2. Create a condition event and create action events after yes or no decision path
3. Apply the campaign
4. Without opening builder, re-save the campaign --> decision_path becomes NULL
 
### Log errors: 

No log errors.

**Comment by gingerling** [comment]
Is that what is causing this: https://www.mautic.org/community/index.php/7561-aspects-of-campaign-failing-trying-to-diagnose-why ? Can you tell me how to access the decision path info you display above and I will check it

**Comment by npracht** [comment]
Solved by https://github.com/mautic/mautic/pull/3993 @escopecz :)
