### ISSUE TITLE
unsubscribe

### ISSUE THREAD

**Issue by Subesrao** [mautic/mautic#3930]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | y
| Enhancement? | y

## Description:
Can any want explain how to create unsubscribe link in email blast. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | LATEST
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi,

https://mautic.org/docs/en/emails/index.html paragraph **Unsubscribing**.
I think it's not the right palce here to ask for documentation. Maybe on mautic forum after reading the documentation ?

Have a nice day,

N.

**Comment by npracht** [comment]
@escopecz i think it can be closed :)
