### ISSUE TITLE
Mautic Hubspot Integration

### ISSUE THREAD

**Issue by faizanayubi** [mautic/mautic#3931]
Bug report

## Description:
I am unable to fetch Leads from Hubspot. I have setup the extra CRON Job and also executed the Command Directly. See Logs Below

## If a bug:

Mautic Version Latest 2.8
PHP version - 7.0

### Log errors: 

php app/console mautic:integration:fetchleads --integration=Hubspot
Command to fetch contacts from integration
Fetch contacts command is starting
PHP Notice:  Undefined variable: processed in app/bundles/PluginBundle/Command/FetchLeadsCommand.php on line 121
Number of contacts fetched:

**Comment by luizeof** [comment]
Reported here #3512
