### ISSUE TITLE
Avatar lost when merging contact

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3935]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When merging contact where contact with avatar image is merged with contact that has no avatar image, image is not merged and so is lost.

Contacts merged after this bug: https://github.com/mautic/mautic/issues/3934

## If a bug:

| Q   | A
| --- | ---
| Mautic version | mautic.net
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
I think this is because the final email address you keep has no gravatar account related.
