### ISSUE TITLE
Tracking link that was sent via campaign has localhost instead of site domain

### ISSUE THREAD

**Issue by ServicedCloud** [mautic/mautic#3937]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
We are in a process of updating our website from mautic from 2.7.1 to 2.8.0 in a development site. We are testing campaign. Although the email campaign went through and has send emails, we've noticed in the emails we received from campaign the tracking link was incorrect. Link found was:
localhost/r/trackingcode... 
instead of
http://ourdevelopersite.com/r/trackingcode...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 5.6.24

### Steps to reproduce:
1. Create campaign
2. Check email sent by the campaign
3. Tracking links inside email is "localhost" instead of our domain.

**Comment by escopecz** [comment]
Check if https://github.com/mautic/mautic/issues/3914#issuecomment-297254647 helps and let us know, please.

**Comment by ServicedCloud** [comment]
Hi escopecz,

Thank you for your reply. The site url in the configuration is our test domain http://ourdevelopersite.com which is

**Comment by ServicedCloud** [comment]
Checked out the site url again and you're correct. I added http which solves the localhost issue. 

Thank you for your fast response on this.
