### ISSUE TITLE
Gmail extension - error when displaying the popup

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#3938]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
The plugin was just working fine at time of install (mautic 2.5)
After upgrade to 2.7.1 users reports errors when opening the popup of the gmail extension there's an error in the first part of the popup : 

> Displaying 25 events (0 new)
> Scheduled to execute at April 27, 2017 2:55 pm CEST
> 
> The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
> System administrators, check server logs for errors.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.12

### Steps to reproduce:
1. Install and setup gmail plugin
2. try to open the popup
 
### Log errors: 

[2017-04-28 09:40:53] mautic.NOTICE: PHP Notice - Undefined variable: lead - in file /app/bundles/CampaignBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 46 [] []
[2017-04-28 09:40:53] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getPermissionUser() on null - in file /app/bundles/CampaignBundle/Views/SubscribedEvents/Timeline/index.html.php - at line 46 [] []

**Comment by escopecz** [comment]
Is this still issue on 2.8.0? I know there were several bug fixes in this area.

**Comment by escopecz** [comment]
Oh, you just submitted a fix...

**Comment by YannickBiet** [comment]
Hi john strange as I made the PR on friday but i have submitted a PR in staging to fix the first error (i can't for sure know if the plugin is working as expected but at least it is adding a null variable test before using)

**Comment by YannickBiet** [comment]
I will test in 280 as soon as I updated my test instance (this week)

**Comment by YannickBiet** [comment]
still here in 2.8.0

**Comment by YannickBiet** [comment]
Looking for Chrome store extension images, it seems that 2.8.0 version still broke completely the plugin :

what it should looks like :
![unnamed](https://cloud.githubusercontent.com/assets/930391/25710123/94749688-30eb-11e7-836d-8d8677de1b8a.jpg)

what it is really looks like now in 280 :
![un](https://cloud.githubusercontent.com/assets/930391/25710169/c0d1ca2a-30eb-11e7-8f3e-ea2ddea4d452.PNG)

the detail button is not clickable, and the data width is just a copy of the WEB timeline. it is not looking specifically for emails read/sent ....

**Comment by YannickBiet** [comment]
my fix is only to check that a variable is not null but is not improving the plugin usability. seems the timeline view is useless for now.

**Comment by YannickBiet** [comment]
Hi don, are you sure the bug can be closed ? the feature is currently pretty useless as it does not display as designed (cf screenshoot on my last note)

I would love to have the timeline feature back in my gmail. did you sucessfully test it under 2.8.0 / 2.8.1 ? i don't pass to make this work!
