### ISSUE TITLE
Impossibility to remove token in email builder

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#3940]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When you add a token in email builder with autocompletion, then you cannot remove it.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7
| PHP version | 

### Steps to reproduce:
1. Create an email
2. Select a theme
3. Add a token (by autocompletion) in a text box
4. try to remove it, you cannot delete

**Comment by escopecz** [comment]
It's related to https://github.com/ichord/At.js/issues/463
