### ISSUE TITLE
Option to hide and unhide deactivated items

### ISSUE THREAD

**Issue by Harry5-5** [mautic/mautic#3941]
What type of report is this:

| Enhancement? | 

## Description:
UI - It would be really useful if there was an option to hide / Unhide deactivated items from the list of Segments, Campaigns, Emails and landing pages etc

**Comment by escopecz** [comment]
what is your idea of doing so? If you hide some items, how could you unhide them when you cannot see them?

**Comment by Harry5-5** [comment]
the idea is to be able to toggle on and off deactivated items so that when you working with active items you can hide the ones that are not in use. We have an ever increasing list of items and it would make life easier if the user could hind the ones they are not using at present

**Comment by escopecz** [comment]
I'll close this feature request in favour of https://github.com/mautic/mautic/issues/371. It's basically the same bug for more entities. Feel free to add a comment there that it can be system-wide option.
