### ISSUE TITLE
Campaign malfunctioning in several ways

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3945]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I am structuring this bug, which is complex, with this overall report which covers the whole scenario and some shorter reports which cover individual issues I have been able to discern contributing to the problem.

This is my campaign:

![screenshot from 2017-04-30 14-41-47](https://cloud.githubusercontent.com/assets/2853040/25565186/a3b3a244-2dba-11e7-9e4f-bc89d3da9471.png)

I used only 6 contacts, while it is a live campaign with real contacts, it is also a small test before I use mautic for bigger campaigns going to many contacts.

Here are the expected results compared with the actual results. It seems prettey random at first glance.

**Contact A**
![contact_a_path](https://cloud.githubusercontent.com/assets/2853040/25565191/c6100616-2dba-11e7-9003-057ebd329d72.png)

Contact A was sent the initial mail and did not complete the linked form. They should have been sent a reminder campaign but were not. (https://github.com/mautic/mautic/issues/3948)

This occurred for two other contacts. 

**Contact B**
![contact_b_path](https://cloud.githubusercontent.com/assets/2853040/25565192/c7ee06fe-2dba-11e7-87b4-25279cae3003.png)

Contact B was sent the initial mail and filled out the form to say if they could attend on a suggested date or if they could not. They were given 5 points for completing the form. They said they could attend on suggested dates, so should have then been sent a thank you message and be given 10 points but neither of those happened. (https://github.com/mautic/mautic/issues/3946)

![form-decision-6](https://cloud.githubusercontent.com/assets/2853040/25565234/67d93224-2dbb-11e7-8f7e-3f6dc86dbc19.png)

Also, their profile seems to suggest they chose both options (can come and can't) but I may be misreading that.

**Contact C**

![contact_c_path](https://cloud.githubusercontent.com/assets/2853040/25565193/c99f9300-2dba-11e7-81c5-a5831e399268.png)

Contact C faired a little better. Their form response was can't come, and they were sent the correct follow up email and given a flag for me to contact them to discuss alternative dates. 

However, they were also sent the reminder email as if they have not filled out the form, and, as above their profile seems to show they said both can and can't come. (https://github.com/mautic/mautic/issues/3947)

**Contact d**

![contact_d_path](https://cloud.githubusercontent.com/assets/2853040/25565194/cb1db04a-2dba-11e7-9b91-aa06e6fd305e.png)

This contact had no errors, ie. errors which have occurred on other contacts with similar decisions made did not occur on this contact.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Mautic.net
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Campaigns were refactored in 2.14.0. Please test with latest version.
