### ISSUE TITLE
Decision based on form choice does not trigger actions as expected in form

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3946]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
![Uploading form-decision-1.png…]()
This section of a campaign did not function as expected. 

The aim was to use the contacts decision about a form to trigger the next actions.

![form-decision-2](https://cloud.githubusercontent.com/assets/2853040/25565292/8f83c478-2dbc-11e7-82e6-429fbd63f87f.png)

This is the form, the options are two possible dates to attend or "none". The responses seemed to work fine:

![form-decision-5](https://cloud.githubusercontent.com/assets/2853040/25565296/a638aaf8-2dbc-11e7-8177-e7576a19122f.png)

In the campaign this is dealt with by using this for the I can attend on a date (not equal to none)

![form-decision-3](https://cloud.githubusercontent.com/assets/2853040/25565294/9f63a25a-2dbc-11e7-9e77-dd8d944279ef.png)

And this for I can't attend, so, equal to none.

![form-decision-4](https://cloud.githubusercontent.com/assets/2853040/25565303/c629e3ae-2dbc-11e7-8760-838cd8b5a8b0.png)

In my campaign I had only one person able to attend on the dates, she should therefore have gained 10 points and been send a thankyou message. This did not occur

![contact_b_path](https://cloud.githubusercontent.com/assets/2853040/25565314/e4f82354-2dbc-11e7-87d7-125044c7357b.png)

Additionally, all contacts who filled in the form have this in their profile:

![form-decision-6](https://cloud.githubusercontent.com/assets/2853040/25565319/f06aeff0-2dbc-11e7-8515-000663ecbd3d.png)

which looks as if both can and can't attend were deemed to have occurred by mautic.

Only 1 of the 5 who said they could not attend had the next actions as expected:
![contact_d_path](https://cloud.githubusercontent.com/assets/2853040/25565326/110a8464-2dbd-11e7-926b-9b84ae98bcab.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by gingerling** [comment]
Child of: https://github.com/mautic/mautic/issues/3945

**Comment by gingerling** [comment]
Hi, actually, I was rebuilding the campaign to test https://github.com/mautic/mautic/issues/3947 and it occurred to me that the method I used to identify if the contact is attending or not may be incorrect.

In the example above I have

Filled in the form:
a) available to attend does not equal none : send email 1
b) available to attend equals none : send email 2

Perhaps this should be

Filled in the form: available to attend equals none
Positive node action : send email 1
Negative node action : send email 2

There are clearly some issues caused by https://github.com/mautic/mautic/issues/3947 affecting this bug but issue in  green here:

![screenshot from 2017-05-02 14-01-04](https://cloud.githubusercontent.com/assets/2853040/25618752/107b123c-2f40-11e7-9589-abc1667a2f71.png)

where the form actions are both triggered is caused by my campaign design not a bug

**Comment by npracht** [comment]
https://github.com/mautic/mautic/pull/3993 solves it @escopecz right?
