### ISSUE TITLE
Actions triggerd by both positive and negative path (should have just been positive)

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#3947]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

Two contacts completed a form and were given points for doing so, as dictated in my campaign. However, contact both contacts were then sent a reminder email, an action attached to the negative node of the campaign.

![contact_b_path](https://cloud.githubusercontent.com/assets/2853040/25565433/57943186-2dbe-11e7-865c-1ba06c0d791f.png)

![contact_c_path](https://cloud.githubusercontent.com/assets/2853040/25565394/dc3b508c-2dbd-11e7-8a2a-781047ebd333.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by gingerling** [comment]
Child of https://github.com/mautic/mautic/issues/3945

**Comment by merlin0** [comment]
Got the same problem in 2.7.1. This only happens when the campaign is updated. Untouched campaigns from before 2.7.1. work fine.

**Comment by gingerling** [comment]
I wonder if cloning after editing would side step this issue?

**Comment by igisho** [comment]
same proble in 2.8.1

**Comment by igisho** [comment]
is there any temporary fix for this?

**Comment by npracht** [comment]
i think https://github.com/mautic/mautic/pull/3993 solves it @escopecz right?
