### ISSUE TITLE
error in italian translation on code builder section

### ISSUE THREAD

**Issue by digitall-it** [mautic/mautic#3949]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The builder with stock Mautic v2.8.0 doesn't initialize correctly if the language is not set to English. Everything appears but blocks cannot be dragged and dropped, nor clicked for personalization. Changing user to English and retrying makes it work.

The errors in the webpage inspector makes it look like the mistake has been done by a translator in Transifex:

- SyntaxError: Unexpected identifier 'intera'. Expected ';' after variable declaration.
- ReferenceError: Can't find variable: mauticLang
- ReferenceError: Can't find variable: mauticAjaxUrl

Trying the spanish language doesn't not trigger the error. This corroborates the hypothesis that the problem is only in the italian translation.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 5.6

### Steps to reproduce:
1. Download and install stock Mautic
2. Change default language to Italian
3. Try to create a landing page and change it using the Builder
4. Try to drag and drop or change blocks, it is not possible
4. Check out the Webpage inspector of the browser

**Comment by npracht** [comment]
@escopecz, It seems very close to https://github.com/mautic/mautic/pull/3874, i think it should be considered as part of 2.8.1 otherwise it make mautic builders unusable for many countries...
