### ISSUE TITLE
Miss company field on new lead creation webhook.

### ISSUE THREAD

**Issue by webalexstudio** [mautic/mautic#3950]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 1
| Feature request? | 
| Enhancement? | 

## Description:
Hi. When there is webhook on new lead creation, in post there is no compnay infromation. Basically company field in json array is there but it always empty.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7

### Steps to reproduce:
1. Cretae webhook on new lead creation.
2. Catch webhook event
3. Lead field is in json POST body, but this field is always emoty even if lead is linked to the company. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
