### ISSUE TITLE
Gotowebinar: token {webinar_button} is just a label without link

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#3953]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
In documentation, this is printed that tokens are available in email to send an email containg the meeting button : https://mautic.org/docs/en/plugins/citrix.html

Unfortunately I tried to create a new form email/ campaign email/ email from the form actions' screen but each time there's no token {meeting listed in there.

Is it still working as documented ?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.1

**Comment by YannickBiet** [comment]
Email received : 

![email](https://cloud.githubusercontent.com/assets/930391/25614646/220579d2-2f33-11e7-95aa-252acb570555.PNG)

no tokens replaced we can still real {meeting_button} ....

**Comment by escopecz** [comment]
Please test against 2.8.0. I think it was fixed there.

**Comment by YannickBiet** [comment]
in 280, the token is appearing in builder.
but there's notice in the cron :

 + yannick.biet@company.fr registered to test-integration-ave_#366898491.
PHP Notice:  Undefined index: username in /var/www/mautic/www_rec/app/bundles/SmsBundle/Api/TwilioApi.php on line 59
PHP Notice:  Undefined index: password in /var/www/mautic/www_rec/app/bundles/SmsBundle/Api/TwilioApi.php on line 59

Seems the 2.8.0 adds sms realted feature ?

I am testing the email to close this issue

**Comment by escopecz** [comment]
That error is fixed in https://github.com/mautic/mautic/pull/3923

**Comment by YannickBiet** [comment]
The email sent does not contain the link 
the label Join Webinar is here but no URL attached

The second token webinar_url is not displayed at all
I tired to add the token to the button my order but still no HREF link in the button

![email 280](https://cloud.githubusercontent.com/assets/930391/25615206/423bb0ce-2f36-11e7-9675-7e2e47b32156.PNG)

**Comment by YannickBiet** [comment]
John, twilio plugin is disabled here but still produce warnings, i am opening a second issue for that

![twilio](https://cloud.githubusercontent.com/assets/930391/25615279/9c283f3a-2f36-11e7-926c-62255cc99aae.PNG)

**Comment by escopecz** [comment]
The bug happens if the Twilio plugin is not configured.

**Comment by YannickBiet** [comment]
@escopecz you should remove the pending feedback as the token are displayed in 280 but still the email sent is not working as expected. How are you waiting more feedback from me ?

**Comment by escopecz** [comment]
> email sent is not working as expected

Is it because of the PHP notice `Undefined index: username`?

**Comment by YannickBiet** [comment]
Hi John,
For me the notices are another case as they are related to the cron launched by mautic to sync with gotowebinar.
The email is sent when a mautic form is submitted (actions tab) so this is not the same code part.

The email is sent to the right contact and the token {webinar_button} is replaced by a label "Join Webinar" BUT there's no HTML link and HREF within this label so this is just a label printed on an email nothing is clickable.

**Comment by RCheesley** [comment]
Closing as PR was merged some time ago.
