### ISSUE TITLE
Twilio notices even if disabled

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#3955]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
There was a bug fix in 2.8.0 regarding SMS : 
https://github.com/mautic/mautic/pull/3923

but this produces notice in php (cron, ...) when trying for example to sync contacts who attended webinars using citrix plugins :

Synchronizing: [366898491] test-integration-ave_#366898491
 + yannick.biet@company.fr registered to test-integration-ave_#366898491.
PHP Notice:  Undefined index: username in /var/www/mautic/www_rec/app/bundles/SmsBundle/Api/TwilioApi.php on line 59
PHP Notice:  Undefined index: password in /var/www/mautic/www_rec/app/bundles/SmsBundle/Api/TwilioApi.php on line 59

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.1

**Comment by YannickBiet** [comment]
Twilio plugin is disabled in our instance

![twilio](https://cloud.githubusercontent.com/assets/930391/25615358/00200504-2f37-11e7-9154-586652418f77.PNG)

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/3923
