### ISSUE TITLE
NotificationBundle Integration

### ISSUE THREAD

**Issue by miguelurtado** [mautic/mautic#3959]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
In `app/bundles/NotificationBundle/Helper/NotificationHelper.php`
Replace `$integration = $this->integrationHelper->getIntegrationObject('Twilio');`
Per `$integration = $this->integrationHelper->getIntegrationObject('OneSignal');`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 5.6.30
 
### Log errors: 

PHP Notice:  Undefined index: app_id in /app/bundles/NotificationBundle/Helper/NotificationHelper.php on line 116, referer: https://xxxxx
PHP Notice:  Undefined index: safari_web_id in /app/bundles/NotificationBundle/Helper/NotificationHelper.php on line 117, referer: https://xxxxx
PHP Notice:  Undefined index: subdomain_name in /app/bundles/NotificationBundle/Helper/NotificationHelper.php on line 119, referer: https://xxxxx

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/3965. It'd be very welcome if you could test that PR and comment on it if it worked for you.

**Comment by mackina** [comment]
Thanks @escopecz - I haven't tested a PR before, I assume I just make the changes referenced in that PR and response back in that review

**Comment by escopecz** [comment]
Yes, that is correct. You can just copy the [content of the file](https://raw.githubusercontent.com/escopecz/mautic/862e43e74498e58585190725e82f40d8a920d13e/app/bundles/NotificationBundle/Helper/NotificationHelper.php) and replace it at your server. It also helps if you clear the Mautic cache to be sure that the changes were applied. There is [this tutorial](https://github.com/mautic/mautic#test-a-pull-request-pr) about how to do it with Git, but that's if you'd like to test more PRs.

**Comment by mackina** [comment]
@escopecz Great, done (fix worked)
