### ISSUE TITLE
Form Creation error

### ISSUE THREAD

**Issue by tmorrison01** [mautic/mautic#396]
When creating a form i received the following error; Uh oh! I think I broke it. If I do it again, please report me to the system administrator!
500 Internal Server Error

**Comment by dbhurley** [comment]
Can you share what the error log outputs?

**Comment by alanhartless** [comment]
The error should be recorded in app/logs/mautic_prod.php. Grab that and post it back here and we can help diagnose the issue.

**Comment by tmorrison01** [comment]
Hey guys. Sorry for wasting your time. I did some research and came across the Mautic videos on Youtube. The issue was entering the wrong information in the form fields. Everything works great now.  This is really a great product. Keep up the work. Thanks.

**Comment by alanhartless** [comment]
No worries; glad you got it worked out! Is there something we can do to maybe prevent whatever the wrong information was that led to the error?

**Comment by tmorrison01** [comment]
Hey Alan,

The information should be accessible. I have a small web design and marketing company. While providing all of the latest  tools for my clients is great I found they were only as good as the people using them. I realized the need for my clients to have a way to market themselves online. I decided to provide an inbound marketing service. I got certified on hubspot which was great but quickly realized that their tools were basically a bundled set of applications. I have the seo tools but needed a great inexpensive marketing automation tool. It wasn’t until stumbling around on the internet and doing lots of research and testing many applications that I came across Mautic. This application is great and provides all of the necessary features needed to deploy online campaigns. The only immediate area that I see need for improvement is in providing  links on the website to the documentation and videos. This is important because it will help to decrease the number of support issues (like the one that I had.)  Any way that I can be of help in the future please let me know.

 

Thanks,

Tony Morrison

**Comment by tmorrison01** [comment]
The information should be accessible. I have a small web design and marketing company. While providing all of the latest  tools for my clients is great I found they were only as good as the people using them. I realized the need for my clients to have a way to market themselves online. I decided to provide an inbound marketing service. I got certified on hubspot which was great but quickly realized that their tools were basically a bundled set of applications. I have the seo tools but needed a great inexpensive marketing automation tool. It wasn’t until stumbling around on the internet and doing lots of research and testing many applications that I came across Mautic. This application is great and provides all of the necessary features needed to deploy online campaigns. The only immediate area that I see need for improvement is in providing  links on the website to the documentation and videos. This is important because it will help to decrease the number of support issues (like the one that I had.)  Any way that I can be of help in the future please let me know.

**Comment by alanhartless** [comment]
HI!

We have basic documentation at https://www.mautic.org/docs which we'll be building on. What we didn't catch is that it wasn't linked on the website so have now remedied that.

Thanks for your feedback and assistance to help!! If you want to join the community, checkout https://www.mautic.org/slack.

Alan
