### ISSUE TITLE
Unable to save Monitored Inbox settings "Folder to check" 

### ISSUE THREAD

**Issue by petebytes** [mautic/mautic#3962]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No 
| Enhancement? | No

## Description:
Trying to setup Monitored Inbox.  The inbox is a separate folder in gmail.
After configuring Monitored Inbox Settings, save fails indicating the "folder to check" has to be selected. (it was selected but save removed)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | Version 7.0.18-1+deb.sury.org~xenial+1

### Steps to reproduce:
1. Open Configuration
2. Select Email Settings
3. Fill in fields in "Monitored Inbox Settings"
4. Click "Test connection and fetch folders"
5. Select the appropriate folder from the "Folder to check dropdown"
6. Save or apply changes fails, indicating the folder has to be selected
7. Try to reselect the folder, but Only Inbox and Trash are visible
All the folders were visible before attempting to save.  
Retesting does not repopulate the Folder to check dropdown
Tried to configure using Custom Connection settings, save issue occured
 
### Log errors: 
[2017-05-03 03:35:39] mautic.NOTICE: PHP Notice - Undefined index: {imap.gmail.com:993/imap/ssl} - in file /var/www/mautic.site.com/htdocs/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php - at line 498

**Comment by M-o-T-a** [comment]
I can't configure this section, same problem
![captura de pantalla 2017-10-10 a las 12 14 57](https://user-images.githubusercontent.com/12897245/31381436-cb7ecb12-adb4-11e7-91d4-a87b06adc422.jpg)
When i save all settings go off
