### ISSUE TITLE
OneSignal JS loading (and failing) via Mautic JS

### ISSUE THREAD

**Issue by mackina** [mautic/mautic#3963]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:

We use the mtc on our website (www.formisimo.com). I noticed errors in the console and traced this back to Mautic MTC. The JS seems to be trying to load onesignal JS, although onesignal isn't activated as a plugin. 

Note that we do not want to use OneSignal, we haven't activated it or want to use it. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.8
| PHP version | 7.0.12-1

### Steps to reproduce:
1. Add the Mautic JS (mtc) to a website
2. Load the webpage in a browser and look at console errors
 
### Log errors: 

From Chrome console:

Failed to load resource: the server responded with a status of 404 ()
ServiceWorker registration TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
e.registerError @ cdn.onesignal.com/sdks/OneSignalSDK.js:1

**Comment by kuzmany** [comment]
Please try read docs https://github.com/mautic/documentation/pull/157/files 

This part:

Don't forget copy these files to root dir of your tracking page:

https://yourmauticurl.tld/manifest.json 
https://yourmauticurl.tld/OneSignalSDKWorker.js https://yourmauticurl.tld/OneSignalSDKUpdaterWorker.js

**Comment by mackina** [comment]
We don't use OneSignal or want to use it.

**Comment by kuzmany** [comment]
@mackina there is another bug, fix soon

**Comment by kuzmany** [comment]
https://github.com/mautic/mautic/issues/3959

**Comment by escopecz** [comment]
Probably fixed in https://github.com/mautic/mautic/pull/3965. It'd be very welcome if you could test that PR and comment on it if it worked for you.

**Comment by trnelson** [comment]
Is there any way to release a priority hotfix for this? I upgraded my Mautic installation and now had to completely remove mtc.js from my site because of JavaScript errors. :(

**Comment by kuzmany** [comment]
@trnelson https://github.com/mautic/mautic/pull/3965 https://github.com/mautic/mautic/pull/4002

**Comment by trnelson** [comment]
@kuzmany Ah excellent thank you! I somehow missed it. I will give it a shot and report back if I have issues, but seems like others have been successful with it.

**Comment by ronnieduke** [comment]
@escopecz looks like this issue is on Mautic cloud as well - is there an eta on when this can be pushed to the cloud version?
