### ISSUE TITLE
Notifications 5MB HTML file

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#3964]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
We ignored our notifications popup for a while, and the result was extremely slow Mautic!

The notifications list grew exceptionally long, I think a few hundred notifications. During this time we ignored the notifications because we were planning on not upgrading Mautic to 2.8 for some time.

Since the notifications grew so long via HTML, page load times in the admin grew to 5 to 10 seconds. There was no error associated with this, simply too much HTML content as found by some Inspection in the web browser.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Mautic 2.6
| PHP version | 7.0

### Steps to reproduce:
1. Trigger notifications for failed campaign events
2. Build up a good list and see how the site's performance is impacted.

If you want to test it faster as a developer, I'd recommend INSERTing some records for notifications.
 
I think solution here would be to cap the total number of notifications that are loaded at once.
Also there is a UX issue here because I want to be able to ignore the notifications for updates, and so I am trained to ignore that red dot, now you are piling more notifications behind it and adversely affecting admins for Mautic.

**Comment by jordan8037310** [comment]
Also, is there a way to turn off notifications from queueing at all? Feature is pretty useless, for us. I want to opt-out.

**Comment by escopecz** [comment]
This was fixed in 2.7.1 https://github.com/mautic/mautic/pull/3561
