### ISSUE TITLE
Can't insert image in the froala editor after several times using custom theme

### ISSUE THREAD

**Issue by ServicedCloud** [mautic/mautic#3966]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
We are using a custom theme. The design of our custom theme is it has upper slot which is the heading and bottom slot which we place marketing content. Upon inserting images several times, the drop/click image is not working therefore we can't insert any images anymore. We've checkout the JS console and found errors relating to froala editor. (Please see error log below)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 5.6.24

### Steps to reproduce:
1. Create new email (custom theme)
2. Insert image, then after 4 times the drop/click image is no longer working.
 
### Log errors: 

froala_editor.js:10122 DOMException: Failed to execute 'setEnd' on 'Range': The offset 21 is larger than or equal to the node's length (9).
    at _restoreRange (http://ourdomain.com/app/bundles/CoreBundle/Assets/js/libraries/froala/froala_editor.js?vf8b250f1:10117:15)
    at Object.restore (http://ourdomain.com/app/bundles/CoreBundle/Assets/js/libraries/froala/froala_editor.js?vf8b250f1:10144:9)
    at Object._do [as run] (http://ourdomain.com/app/bundles/CoreBundle/Assets/js/libraries/froala/froala_editor.js?vf8b250f1:10251:25)
    at FE.undo (http://ourdomain.com/app/bundles/CoreBundle/Assets/js/libraries/froala/froala_editor.js?vf8b250f1:9094:21)
    at Object.exec (http://ourdomain.com/app/bundles/CoreBundle/Assets/js/libraries/froala/froala_editor.js?vf8b250f1:9185:20)
    at Object.exec (http://ourdomain.com/app/bundles/CoreBundle/Assets/js/libraries/froala/froala_editor.js?vf8b250f1:10619:72)
    at FE.exec (http://ourdomain.com/app/bundles/CoreBundle/Assets/js/libraries/froala/froala_editor.js?vf8b250f1:9964:29)
    at trigger (http://ourdomain.com/app/bundles/CoreBundle/Assets/js/libraries/froala/froala_editor.js?vf8b250f1:1092:32)
    at HTMLDivElement.<anonymous> (http://ourdomain.com/app/bundles/CoreBundle/Assets/js/libraries/froala/froala_editor.js?vf8b250f1:777:9)
    at HTMLDivElement.dispatch (http://ourdomain.com/media/js/libraries.js?vf8b250f1:404:451)
_restoreRange @ froala_editor.js:10122
froala_editor.js:321 Editor should be initialized before calling the destroy method.
(anonymous) @ froala_editor.js:321
froala_editor.js:321 Editor should be initialized before calling the destroy method.
(anonymous) @ froala_editor.js:321
froala_editor.js:321 Editor should be initialized before calling the destroy method.
(anonymous) @ froala_editor.js:321
froala_editor.js:321 Editor should be initialized before calling the destroy method.
(anonymous) @ froala_editor.js:321
froala_editor.js:321 Editor should be initialized before calling the destroy method.
(anonymous) @ froala_editor.js:321
froala_editor.js:321 Editor should be initialized before calling the destroy method.
(anonymous) @ froala_editor.js:321

**Comment by escopecz** [comment]
Could you please test if the problem occurs only with your custom theme or if it occurs with stock themes as well? If it is only with your custom theme, then my guess is that the HTML of the theme is not valid.

**Comment by ServicedCloud** [comment]
It is not happening in the other stock themes. Maybe it is my HTML code. 

We also encountered this error in the JS console.

Editor should be initialized before calling the destroy method.
(anonymous) @ froala_editor.js:321

**Comment by ServicedCloud** [comment]
I double checked other themes and i was wrong, i wasn't able to insert image as well. This happens randomly though, sometimes it works sometimes it doesn't.

**Comment by escopecz** [comment]
Ok, open the JS console (press F12 on Windows or Option+Command+I on Mac, navigate to the Console tab). Try to insert the image. Do you see some error message in the console when the image fails? Or do you have some error recorded in the [logs](https://mautic.org/docs/en/tips/troubleshooting.html)? Is it happening in all browsers or just some?

**Comment by ServicedCloud** [comment]
In the console it says > Error in parsing value for ‘position’.  Declaration dropped.

Then nothing in the logs

**Comment by ServicedCloud** [comment]
Hi @escopecz , is there a chance that this will be included in the 2.8.2 fixes?

**Comment by escopecz** [comment]
I'm not able to reproduce it. Is there anyone else with this issue?

@ServicedCloud could you go once more through the questions I posted earlier and try to answer them?

**Comment by ServicedCloud** [comment]
We are using windows and google browser. We are encountering this randomly. Sometimes inserting an image works well and sometimes we cant. The workaround that we got are 
1. To use file folder directory instead of the drop image/click.
2. Clear browser cache.

**Comment by ServicedCloud** [comment]
Hi @escopecz,

In addition inserting by typing a link in an image is not working. The work around that we are doing is to copy the link. When we check in the JS console, it has warnings that says "froala_editor.js:321 Editor should be initialized before calling the destroy method. (anonymous) @ froala_editor.js:321"

Please see image below.
![untitled-1](https://cloud.githubusercontent.com/assets/18678691/26567533/96423b30-452e-11e7-9444-d634af2b5873.jpg)

**Comment by adrianready** [comment]
I am also having the same error that @ServicedCloud is reported

**Comment by RCheesley** [comment]
As this is a super old issue without any recent interaction I'm going to close the issue. If it remains a problem, please create a new issue and link to this one as a reference.
