### ISSUE TITLE
Can't Save Email, undefined index globalcategory

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#3967]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.9

### Steps to reproduce:
1. Create an email
2. Try to save.
 
### Log errors: 

mautic.NOTICE: PHP Notice - Undefined index: globalcategory - in file /httpdocs/app/bundles/LeadBundle/Form/Type/FilterTrait.php - at line 112 [] []

**Comment by escopecz** [comment]
I tried to replicate, but I don't see the PHP notice anywhere. I tried by creating segment email as well as template email. Is there some step missing in the steps to reproduce section?

**Comment by jordan8037310** [comment]
@escopecz honestly I was hoping you could tell me. I upgraded to 2.8.0 today and this started happening.

Here is the notice in the console. The PHP Notice may not be the issue, but instead this Froala bug:

![image](https://cloud.githubusercontent.com/assets/3300713/25655032/4d00f79a-2fa8-11e7-894f-71afa377d3d8.png)

**Comment by escopecz** [comment]
That is just a JS notice. It doesn't have anything to do with the functionality. Do you have some problem with the functionality? Really, the more details you can provide about the issue, the less time we both spend on it.

**Comment by jordan8037310** [comment]
Hi @escopecz, I think I discovered the steps that come close to reproducing the issue.

When I create a new Segment email, 
I select Blank Template,
Select Builder,
Close Builder
Select Code View
the HTML in the email form becomes malformed, and the javascript is cut off (screenshot attached)
![image](https://cloud.githubusercontent.com/assets/3300713/25655493/ddec1e8c-2fa9-11e7-8482-567e7ec6d1ba.png)
```
    <head><script type="text/javascript">window.NREUM||(NREUM={}),__nr_require=function(e,n,t){function r(t){if(!n[t]){var o=n[t]={exports:{}};e[t][0].call(o.exports,function(n){var o=e[t][1][n];return r(o||n)},o,o.exports)}return n[t].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o
            /* Mobile styles */
            @media only screen and (max-width: 480px) {

                [class="w320"] {
                    width: 320px !important;
                }

                [class="mobile-block"] {
                    width: 100% !important;
                    display: block !important;
                }
            }
        </style>
    </head>```
I edit the HTML and delete the above section. 
Then I save.


This process _worked_ however, in a previous email (not this test version) when I did these steps the following code is saved in Email:

```
    <head><script type="text/javascript">window.NREUM||(NREUM={}),__nr_require=function(e,n,t){function r(t){if(!n[t]){var o=n[t]={exports:{}};e[t][0].call(o.exports,function(n){var o=e[t][1][n];return r(o||n)},o,o.exports)}return n[t].exports}if("function"==typeof __nr_require)return __nr_require;for(var o=0;o
 ```

With no ending `</head>` tag.

I can't edit this email at all, but at this point I'm willing to chalk it up as a malformed email and delete it.

**Comment by escopecz** [comment]
Based on the JS injected to the template HTML code it's done by the __New Relic Browser monitoring__. Could you turn that off to see if the problem disappears? It won't fix the emails which have the HTML already broken, but when you try to create a new one, it should work.

**Comment by jordan8037310** [comment]
Ah, shit. Well I'll remove that plugin and see where I get.

**Comment by keanlaurens** [comment]
I'm having the same issue but I do not have that plugin installed.
I create an email, select a template, click save and then a dialogue pops up asking what email I would like to create and then displays no actions buttons (Save & Close, Apply etc)
