### ISSUE TITLE
Notifications for Bad Campaign Events

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#3968]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.9

### Steps to reproduce:
1. Receive notification in Mautic dashboard
2. The error messages are for campaign events that never complete. The campaign events are simple, e.g. Tag a lead. 
3. The campaign events have never finished for 4 or 5 leads and run over and over.
 
### Log errors: 

Console error is returned for each Mautic dashboard notification returned
Uncaught TypeError: Cannot read property 'contentDocument' of null
    at Object.Mautic.updateIframeContent (app.js?vc35e5eee:154)
    at app.js?vc35e5eee:150

This may also be related:

mod_fcgid: stderr: PHP Notice:  Undefined index: app_id in /app/bundles/NotificationBundle/Helper/NotificationHelper.php on line 116, referer: https://facetinteractive.com/
mod_fcgid: stderr: PHP Notice:  Undefined index: safari_web_id in /httpdocs/app/bundles/NotificationBundle/Helper/NotificationHelper.php on line 117, referer: https://facetinteractive.com/
mod_fcgid: stderr: PHP Notice:  Undefined variable: lead in /app/bundles/LeadBundle/Views/Timeline/plugin_list.html.php on line 83

**Comment by escopecz** [comment]
Could you please be more specific? What notification? Desktop notification? Or Mautic notification? How did you set up the plugin if Desktop notification? What steps you've taken to get the error message?

**Comment by jordan8037310** [comment]
@escopecz I added some more errors I found which may be related?

**Comment by escopecz** [comment]
Could you please test if https://github.com/mautic/mautic/pull/3965 solves the problem?

**Comment by jordan8037310** [comment]
@escopecz I decided to roll back. the Dynamic Content tab on our emails was completely missing and I couldn't leave this in limbo for the morning.

**Comment by escopecz** [comment]
The dynamic content tab was moved to the builder. There will be a video about it released soon. The  PHP notices reported are addressed by #3965, so I'll assume it's fixed by that PR.

**Comment by jordan8037310** [comment]
@escopecz how do you get to dynamic content from code mode in 2.8?
