### ISSUE TITLE
[2.8.0 and MySQL5.7] Using group by in reports may causes 500 errors

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#3969]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Upgraded from 2.7.1 to 2.8.0
Created a NEW report (not updating a old one)

Depending on the fields inside the COLUMNS part of Data tab, Mautic could crash in error 500

In deed, even if mautic is not dealing with group informations and then a sub level of group details rows, user can select to display contact's city plus last name in COLUMNS and want to GROUP using Country field.

As soon as we add a column for display that is not used to group : it renders error 500

This is a mysql server issue with change in default MySQL server configuration (see below)
Even if of course the functionnal need is weird/useless and results in a user manipulation error as there non sense to select data columns that will render partial values (why groupin on countries and ask to display city column) Mautic should not crash in error 500

Server 
OS : Debian 8
MySQL Server : 5.7.17 (default debian8 package)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.14

### Steps to reproduce:
1. Create a new report on contacts
2. Select to display lastname, firstname, city
3. Save -> it is ok
4. Edit -> Add group by on city (or country)
5. Save -> Error 500
 
### Log errors: 

An exception occurred while executing 'SELECT l.lastname AS lastname, l.points AS points, l.city AS city FROM leads l WHERE l.date_added BETWEEN ? AND ? GROUP BY l.city' with params ["2017-04-02 22:00:00", "2017-05-03 10:09:34"]:  SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mautic.l.lastname' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" at /var/www/mautic/www_prod/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT l.lastname AS lastname, l.points AS points, l.city AS city FROM leads l WHERE l.date_added BETWEEN ? AND ? GROUP BY l.city' with params [\"2017-04-02 22:00:00\", \"2017-05-03 10:09:34\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mautic.l.lastname' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/mautic/www_prod/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mautic.l.lastname' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/mautic/www_prod/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mautic.l.lastname' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/mautic/www_prod/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

**Comment by YannickBiet** [comment]
MySQL Documentation here :
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

**Comment by YannickBiet** [comment]
Workaround for users under MySQL 5.7.5+ :

Edit my.cnf and add line below in the section [mysqld]
`sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

please restart the server !

**Comment by YannickBiet** [comment]
Example of reports filters ok with default Debian8 / Mysql 5.7
![ok](https://cloud.githubusercontent.com/assets/930391/25657574/d1fab87c-2ffe-11e7-9d78-ad1b8068fc1f.PNG)

Example of reports filters NOT OK with default Debian8 / Mysql 5.7
![not ok](https://cloud.githubusercontent.com/assets/930391/25657549/bc533c60-2ffe-11e7-8636-1e06dbdc3b23.PNG)

**Comment by escopecz** [comment]
Working for me on 2.13.1

**Comment by namratasaun** [comment]
hello, In data I am using emails sent and in group by I am grouping by Campaign, but it gives 500 error.
