### ISSUE TITLE
Can't Access Dynamic Content when using Code Mode

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#3970]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
Who's doing the UI / UX for this? 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 

With 2.8.0 released, the Dynamic Content has been added to the Builder. That means you can _only_ access it from within an Email that contains a template. 

Our team almost exclusively uses Code Mode. This is the easiest template to work with, and also has the most stability as the Builder is intermittently buggy.

With this new update, our team cannot use Dynamic Content. The new UI design has made it cumbersome (and costly!) to use Dynamic Content. 

Now we must switch from Code Mode into a template in order to edit Dynamic Content. No bueno.

Proposed Solution: *Maintain Dynamic Content in both the old and new locations.*

(Edit: Cleaning this up for more structured comments, discussion. Apologies for initial frustration in my original post.)

**Comment by luizeof** [comment]
Dynamic Content now is a Slot on Builder.

**Comment by wittwerch** [comment]
Please move the Dynamic Content back to were it was. We are using another editor and this makes it impossible for us to use Dynamic Content.

**Comment by jordan8037310** [comment]
@luizeof My point is that Dynamic Content can no longer be accessed if you are using Code Mode.

My entire team uses Code Mode do the instability of other modes. We also write all of our emails in a format that is plain text, and personalized (no marketing templates).

Quite simply Dynamic Content is in the wrong place. It is not a "feature within" but a separate feature. If people want it inside of the Builder it should be in both places so I don't have to go into a templated Builder in order to access Dynamic Content.

This change will block myself and all of our Clients from upgrading to future versions of Mautic.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/4001
