### ISSUE TITLE
Embedded videos should allow for fluid/responsive dimensions

### ISSUE THREAD

**Issue by stevegrant1983** [mautic/mautic#3974]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | Y
| Enhancement? | Y

## Description:
At the moment, embedded videos in landing pages enforce a fixed height and width, which doesn't work particularly well if the design for the landing page is meant to be responsive.

The functionality should be flexible enough to allow for:
1. No specified height/width, allowing the design of the page itself to determine the size of the video, using CSS like this:
```.videoWrapper {
	position: relative;
	padding-bottom: 56.25%; /* 16:9 */
	padding-top: 25px;
	height: 0;
}
.videoWrapper iframe {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
}
```
and HTML:
```<div class="videoWrapper">
  <iframe src="https://www.youtube.com/embed/{video_id}" frameborder="0"></iframe>
</div>
```

2. A series of video options so the onus isn't on the person creating the landing page (may not be technically-minded) knowing how to autoplay the video, remove the header, etc. These options would then append the relevant options to the querystring of the video URL.
3. Not requiring a gated timeout or an associated form - quite often on a landing page, I just want to play a video with no strings attached :)

**Comment by RCheesley** [comment]
For part 1, you can use a percentage rather than a fixed width
For part 2, please add a feature request at https://forum.mautic.org/c/ideas if still relevant.
For part 3, see https://forum.mautic.org/t/allow-non-gated-video-embed-in-builders/11659
