### ISSUE TITLE
Report editing : operator not empty not listed !

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#3976]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
I created a report using Contacts catalog
I setup a filter on Date identified "not empty" and saved my report.
Re-edit the report and go to Data tab : the operator is "Equals" (not empty is not available)
You have to change the field filtered and then go back to the previous field (date identified) to have the operator not empty back.

There's a similar problem on the Dynamic switch that is set to Yes again and again.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.14

**Comment by YannickBiet** [comment]
Rediting : operator not listed

![a](https://cloud.githubusercontent.com/assets/930391/25665223/35fe95a0-301d-11e7-8055-0014b9e845fb.PNG)

Changing field, operator appeared

![b](https://cloud.githubusercontent.com/assets/930391/25665220/35b789d0-301d-11e7-8ff2-b25bc1eb4b2a.PNG)

Back to right field, operator still here !
![c](https://cloud.githubusercontent.com/assets/930391/25665221/35b8f428-301d-11e7-9dc7-58270a21505a.PNG)

**Comment by escopecz** [comment]
Works for me on 2.14.1
