### ISSUE TITLE
Campaign is doesn't work right (I think)

### ISSUE THREAD

**Issue by zachrdlapetr** [mautic/mautic#399]
Situation:
-add lead list 'l_xxxx'
-add lead '1' with email 1@ddd.dd
-add lead '2' with email 2@ddd.dd (I want to show you I did choose two different emails)
-add campaign 'c_xxxx' and choose lead list 'l_xxxx'
-edit campaign bulider 'c_xxxx' and add action 'send email' (add new email 'e_xxxx') with parameter 'send immediately' and relate to decision 'opens email' with limit to 'e_xxxx' and green relate to action 'send email' (add new email 'e_thanks') with parameter 'send immediately'
-close campaign bulider and set published and save

And now I add lead '1' and lead '2' to lead list 'l_xxxx', cron send two emails 'e_xxxx' to different email address, I open it in msoutlook and show hidden images.

Now I wait for 'e_thanks' email but 'e_thanks' email is received only on 1@ddd.dd email. I did test it with 2,5,10 emails but always is received the one email on first lead I added to lead list 'l_xxxx'.

Upgraded version 1.0.1 to 1.0.5. Tested on 1.0.5; Ubuntu 12.04LTS

**Comment by alanhartless** [comment]
Hi!

Okay; let's look at a few things.

First, go to Manage Campaigns and click on c_xxxx.  At the bottom you should see Decision, Actions, and Leads tabs.  
1) For Decisions, what percentage is your opens email decision at?  

Then click on the Actions tab.

2) What percentage is the second email (e_thanks) at?

Now go to Manage Leads and find the lead that did not receive the second email and click on them. 

3) In their timeline, does it indicate that the first email was read? 
4) Does it show that the second email was sent to them?

Finally, for this round of questions :-), if you look int app/logs/mautic_prod.php, do you see any errors that are **not** a "Sorry, this URL could not..."? 

Thanks!
Alan

**Comment by alanhartless** [comment]
Closing due to lack of a response.  If the problem persists in the latest version, let us know!

Thanks!
Alan

**Comment by zachrdlapetr** [comment]
Hi Alan,
I owe you an apologize again. A lot of work. I have tested a last release and campaign works great now. I just updated old version. Thank you so much. Best, Petr

**Comment by alanhartless** [comment]
No worries! Glad things are working! :-)
