### ISSUE TITLE
Emails view filters on deleted segment => no filters appear but no emails in list view

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#3994]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Create a test segment name it "test"
Under Chanels > Email > Create a new segment email "email test" linked to your test segment
save it (let default content message body)
under emails list view, use segment filter and enter "test"

your list view is filtered and your test email is shown
delete the email
Go to segments, delete the test segment.

Go back to emails

The filters are empty but your list is still empty, you think to have loose ALL your emails 

Enter a new segment name in the filter, delete the filter, and the list is now back !

Keep calm and Breathe smoothly!

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.18

**Comment by RCheesley** [comment]
Hah, nice catch! Was able to reproduce on 2.16.1!

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
