### ISSUE TITLE
auto connect

### ISSUE THREAD

**Issue by mokra** [mautic/mautic#3999]
What type of report is this:

| Q   
| **yes**
| Bug report? | **no**
| Feature request? | **yes**
| Enhancement? | **no**

## Description:
Does mautic somehow provide an option to auto login using OAuth for example? I have a dashboard from which my backend users are created (the creation of users, will also automatically create mautic-users). These dashboard-users already login in the dashboard. By clicking on the "mautic" button, I want to forward them to mautic, but without the need of logging in again.

**Comment by escopecz** [comment]
See https://mautic.org/docs/en/authentication/saml.html

**Comment by mokra** [comment]
thanks a lot!
