### ISSUE TITLE
[Feature] Allow custom stylesheets & JS files

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#40]
On many other platforms it is possible to add your own CSS/JS 'files' which enables template providers to provide bundles with this already set up and prevents in-line stuff being used - example from Unbounce:

Add your own stylesheets/JS: http://nimb.ws/Py9NLl

CSS file: http://nimb.ws/KhqeFJ
JS file: http://nimb.ws/56EVFl

This would be a very helpful feature to enable easy creation of templates, but also potentially allowing people who use other platforms to easily migrate over to using Mautic.

**Comment by dbhurley** [comment]
Yes, this is the plan for the Mautic Marketplace. I'm not sure if it's already been discussed here but the goal is to have an incredibly easy place for people to share and add templates (and even more things like workflow, campaigns and email funnels for various vertical markets) 

Because who wouldn't like a little help sometimes? :)

**Comment by RCheesley** [comment]
Yep, sounds great!  At the moment I can't create most of my landing pages in Mautic without being able to add a bunch of JS/CSS stuff, and I really don't want to do that in-line if at all possible :)

**Comment by alanhartless** [comment]
@RCheesley Curious if this one is still relevant in light of the custom template stuff you've done more recently? :-)

**Comment by RCheesley** [comment]
@alanhartless I think it would make life easier for the non-coders to be able to directly drop CSS/JS into the editor, rather than muck about with complicated exports and digging into the code.

**Comment by zahedkamal87** [comment]
Is this feature is added?

**Comment by asad50** [comment]
Is this feature added?

**Comment by tonypartridge** [comment]
@dbhurley I see you closed this? But was it ever added?

**Comment by RCheesley** [comment]
You can just add your own CSS/JS by bringing it in as a declaration in the
theme, there isn't a feature on the builder that allows you to do this (but
it would be neat if there was)
