### ISSUE TITLE
Form field editing fails once entered Code View

### ISSUE THREAD

**Issue by Loilo** [mautic/mautic#4000]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  ✗
| Feature request? | 
| Enhancement? | 
| Mautic version |  2.8.0
| PHP version | 5.6

## Description:
Submitting an editing form in Chrome does not work if it included the use of a *Code View*.

This is not a regression bug.

A screenshot is worth a thousand words:

![form-submission](https://cloud.githubusercontent.com/assets/1922624/25738218/1c1dec66-317c-11e7-98b5-4d0a5fd65a50.png)

### Steps to reproduce:
1. Open Mautic in Chrome/Opera/anything with Blink engine.
2. Create a *Description Area* form field in a form.
3. Edit the description in *Code View*.
4. Try to submit the form.
5. The submission will not take place, the submit button will spin forever.

*Note:* The Code View doesn't have to be active on submit attempt, the bug occurs whenever it has been initialized during the process.

### Cause of the bug:
This is caused by a fairly new restriction introduced by the Blink engine. In one of their latest release the Chromium team seems to have decided that form submissions with unclosed `<select>`/ `<textarea>` / ... elements are a security concern and thus will not be executed.

I don't know about Mautic's internal DOM manipulation structure, but in one of my projects this was caused by using jQuery to build the DOM like this:

```javascript
var $myTextarea = $('<textarea name="myname">')
```

Since using this generated DOM node always worked for me, I falsely assumed that jQuery would take care of closing the opened node.

Turns out it doesn't.

I had to fix all occurrences like this, it's sufficient to use a self-closing tag. The above example can be fixed like this:

```javascript
var $myTextarea = $('<textarea name="myname" />')
```

Hope this helps.

**Comment by escopecz** [comment]
I'm not able to reproduce the JS error on Chrome, MacOS with provided steps to reproduce. But based on provided explanation of the error message, I think the problem is in Froala's Code View plugin, because it [contains](https://github.com/froala/wysiwyg-editor/blob/master/js/plugins/code_view.min.js) unclosed textarea tag:

`k=a('<textarea class="fr-code" tabIndex="-1">')`

Would you mind to report it to [Froala's repository](https://github.com/froala/wysiwyg-editor/issues)?

**Comment by Loilo** [comment]
Of course, I'll do that.

I've got Chrome Version 58.0.3029.81 running on macOS (should've probably mentioned that before), but I'm not sure why this doesn't seem to happen to many people on current Chrome version. Googling the error message doesn't give much information either.

However, I've tried on multiple machines, in private browsing mode etc. The result's always the same.

**Comment by Loilo** [comment]
Okay, so this was apparently a weird issue with my Chrome installation that could only be resolved by completely purging my Chrome user data and then reinstall it.

Sorry, a bug in a library was just the more natural assumption. 😬
