### ISSUE TITLE
Facebook Integration does not return email field on social login

### ISSUE THREAD

**Issue by didorodrigo** [mautic/mautic#4007]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? |  N
| Enhancement? |  N

## Description:
I detect that the field email when I try to logged in with Facebook social login does not returned.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8
| PHP version | 5.6

### Steps to reproduce:
1. Add and configure the plugin Facebook Integration
2. Create a form with social login and the fields that you need to show, in this case email
3. Put this form in a Landing Page
4. Click in the social login button of Facebook
5. The email does not return in the callback response of Facebook
 
### Log errors: 
N/A

**Comment by alanhartless** [comment]
Looks like we need to define the scope to get permission: https://developers.facebook.com/docs/facebook-login/permissions#reference-email

**Comment by Aneta09** [comment]
+1
