### ISSUE TITLE
If a form is rendered, dynamic content does not show

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#4013]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
I think this is a bug, but it could be a design feature.

If I set up dynamic content such that there is both a Mautic form and dynamic content on the same page, the form shows but the dynamic content does not.

I found this with Mautic + Joomla, but others have reported with Wordpress.

Unsure if this is an implementation bug (e.g. to do with the plugins) or a Mautic bug. Can provide a screencast privately.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.15

### Steps to reproduce:
1. Create dynamic content, campaign which has a request
2. Create a form
3. Embed the form within content
4. Embed the dynamic content on the same article

The form will render, but the dynamic content does not (nor does the plain text after the form)
 
### Log errors: 

No errors experienced in log or console

**Comment by sarikas735** [comment]
Hello RCheesley,

I come across the same issue with Wordpress, Do you have any fixes for this issue?

**Comment by npracht** [comment]
Hi @RCheesley, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

If yes, can you check if https://github.com/mautic/mautic/pull/8935 solves the problem ?

**Comment by RCheesley** [comment]
Hahaha ..... I knew I would get one of these sooner or later!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
