### ISSUE TITLE
Infinite Redirect Loop on Setting

### ISSUE THREAD

**Issue by faizanayubi** [mautic/mautic#4016]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Bug
| Feature request? | 
| Enhancement? | 

## Description:
I am using vesta cpanel for running mautic which configures apache with nginx proxy.
When I have changed my mautic URL to https it alwats redirects to https://mymautic.com/s/login

Please help

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0

### Steps to reproduce:
1. Install mautic on Sub Domain with SSL
2. Change Mautic URL to https
3. Delete Cache
 
### Log errors: 
There is no error logs in

**Comment by escopecz** [comment]
I'm running Mautic with SSL on a subdomain and I don't have such problems. Could you double-check if it's not a server configuration issue?

**Comment by faizanayubi** [comment]
I think it may be Server issue, I am using vestaCP it uses nginx for frontend and apache for backend

see here for details - https://www.mautic.org/community/index.php/7620-error-too-many-redirects-after-deleting-app-cache-directory/p1#p22899

**Comment by escopecz** [comment]
Try to see if it even loads this method: https://github.com/mautic/mautic/blob/staging/app/bundles/UserBundle/Controller/SecurityController.php#L49

But the community won't be able to help if it is a server issue. Maybe ask support of the server.

**Comment by faizanayubi** [comment]
@escopecz how can i check if loginAction() method loads?

**Comment by faizanayubi** [comment]
I don't think It's a server configuration issue as api endpoints are working

**Comment by escopecz** [comment]
Add to the method `die('it loads');` and try to access the login page. If it writes the 'it loads' text, it means the method is loaded. You can move the die statement to the end of the method to see if the contents of that method is causing the redirect loop. This way you can find what line is causing it.

**Comment by faizanayubi** [comment]
Ok let me try this

Thanks

**Comment by faizanayubi** [comment]
<img width="766" alt="screen shot 2017-05-09 at 4 33 14 pm" src="https://cloud.githubusercontent.com/assets/4982023/25847824/5ca304fe-34d5-11e7-9c33-1264a0bd2067.png">
I added die statement still getting the redirect error
<img width="1280" alt="screen shot 2017-05-09 at 4 35 41 pm" src="https://cloud.githubusercontent.com/assets/4982023/25847915/b099da1a-34d5-11e7-9651-a3ed8fe223b5.png">

What you say, maybe the problem?

**Comment by faizanayubi** [comment]
@escopecz Today I edited index.php with die statement as shown in pic and page was working
<img width="567" alt="screen shot 2017-05-13 at 12 58 00 pm" src="https://cloud.githubusercontent.com/assets/4982023/26023587/180ac3a8-37dd-11e7-99d4-19cdc5519166.png">



Please help, I think the server configuration is okay as i was able to see "hello" text on web page as die was executing but when i have put die statement at last line, i see the error too many redirects

**Comment by escopecz** [comment]
Have you tried to clear the cache? Anything in the logs? 

See https://mautic.org/docs/en/index.html

When you say that the API calls are working, do you use http for that?

**Comment by faizanayubi** [comment]
Yes i cleared cache, when i am using mautic url as http everything works.

For mautic api call i am using https

Is there any problem with router or any headers that may be extra added in request?

**Comment by lvnilesh** [comment]
If I keep mautic url at http, no issues after clearing cache.
If I change mautic utl to https, clear cache, and I get 301 redirect loop.

**Comment by stschindler** [comment]
@lvnilesh I experience the exact same issue.

**Comment by lvnilesh** [comment]
@stschindler https://github.com/mautic/mautic/issues/5285 resolved for me.

**Comment by Pytlicek** [comment]
1) Open `/www/mautic/app/config/local.php`
2) Change `'site_url' => 'https://something.com'` to `'site_url' => 'http://something.com',`
(HTTPS>HTTP)
3) Delete cache: `rm -rf /www/mautic/app/cache/*`
4) Open site `https://something.com/`
5) Change back to https via : `https://something.com/s/config/edit` or `/www/mautic/app/config/local.php`

**Comment by YosuCadilla** [comment]
@Pytlicek works like a charm, however, how hard could it be to fix it in the code?

**Comment by jos0405** [comment]
adding this in index.php solve this issue
$_SERVER['HTTPS'] = 'on';

https://github.com/mautic/mautic/issues/5285

**Comment by ceefour** [comment]
My solution : ensure  to pass fastcgi_params HTTPS, see https://about.lovia.life/docs/infrastructure/mautic-engineering/installing-mautic-in-ubuntu-vm/

```
    if ($http_x_forwarded_proto = 'https') {
      set $my_https 'on';
    }
    fastcgi_param HTTPS $my_https; # set $_SERVER['HTTPS']
```

**Comment by tstauch** [comment]
> 1. Open `/www/mautic/app/config/local.php`
> 2. Change `'site_url' => 'https://something.com'` to `'site_url' => 'http://something.com',`
>    (HTTPS>HTTP)
> 3. Delete cache: `rm -rf /www/mautic/app/cache/*`
> 4. Open site `https://something.com/`
> 5. Change back to https via : `https://something.com/s/config/edit` or `/www/mautic/app/config/local.php`

Thank you @Pytlicek  I was really stuck until I found your solution.

**Comment by ivanmonteiro** [comment]
> My solution : ensure to pass fastcgi_params HTTPS, see https://about.lovia.life/docs/infrastructure/mautic-engineering/installing-mautic-in-ubuntu-vm/
> 
> ```
>     if ($http_x_forwarded_proto = 'https') {
>       set $my_https 'on';
>     }
>     fastcgi_param HTTPS $my_https; # set $_SERVER['HTTPS']
> ```

This did the trick for me using nginx as a reverse proxy. 
The mautic backend did not know that the proxy used https (but the backend was http) so it 301 redirected into infinite loop.
I had to pass `proxy_set_header X-Forwarded-Proto $scheme;` to the upstream server:
```
  location / {
    proxy_pass_request_headers on;
    proxy_set_header Host            $host;
    proxy_set_header X-Real-IP       $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://mautic_backend;
  }
```

**Comment by ricardopxlcl** [comment]
> adding this in index.php solve this issue $_SERVER['HTTPS'] = 'on';
> 
> [#5285](https://github.com/mautic/mautic/issues/5285)

Today 2025 this tip work to fix the error.
