### ISSUE TITLE
Contact Filed Country not saved

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#4018]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## If a bug:
Hi team i notice a bug in the campaign builder when you use the Contact Field > Country > Equals > and select any country. then you click Update and if you reopen the Contact Field Value the country reset to Abkhazia.

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
It was fixed in 2.8.0
