### ISSUE TITLE
[bug] External link uses the same link ID number?

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#402]
I'm not sure if this is a bug or if it's expected behaviour, but I just created a bunch of external links and they are all using the same link ID - shouldn't each link have an unique ID?

I've got a landing page linked earlier in the email, which I dragged in, and it's using `<a href="{pagelink=5}">`

Every link that which I dragged in to create thereafter used the same ID.

**Comment by alanhartless** [comment]
I think it is a bug although nothing devastating. Both the landing page and external link uses the same modal which is supposed to be cleared out after the drop.  But looks like that isn't happening.  So if you drag and drop the external link after already doing so either via another external link or landing page, just replace the contents left in the modal with whatever you want.  We'll get this fixed though.

**Comment by RCheesley** [comment]
Thanks @alanhartless - so my question is, how do I then know which link is being clicked, if they are all using the same pagelink ID?  Should I manually change them to be incremental numbers, so each link has a different ID? I'm not entirely clear how the pagelink ID's should work.  For example are they specific just to this one email, or are they incremental across all emails/campaigns etc?

**Comment by alanhartless** [comment]
Currently; links in emails are absorbed into the page stats. So if a Mautic landing page, it's all accumulative and displayed in the stats when viewing the landing page's details. But, we do need to make the stats available on a per email basis.  So with #353, we'll make sure that URLs used within an email will auto collect individual click stats per email and display that information in the email's details.
