### ISSUE TITLE
Update needed on GoTo plugin

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4023]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | x

## Description:
Citrix has been bought by LogMeIn. The developer center used by the GoTo plugins will not work anymore in the coming months.
Consequently, the plugin need to be updated to be compatible with LogMeIn GoTo version.

## Message from LogMeIn:

> Hello,
> 
> Thank you for using the GoTo Developer Center. We want to make sure you are aware of important changes that will impact use of the Center. Please note your action may be required.
> 
> New domain 
> On February 1, 2017 the GoTo business of Citrix separated from Citrix and merged with LogMeIn, Inc. https://blog.logmeininc.com/welcome-new-logmein/
> 
> New developer portal
> Starting June 5, 2017, please use the new developer portal at https://goto-developer.logmein.com. Please remember to select API Status on the menu and click Subscribe to Updates.
> 
> New certificates
> The certificates used by both the current and new domains will be changing. This should not affect most customers, but if your computers do not currently have root certificates of the Certificate Authorities (CAs) we use (Entrust, Inc. and Digicert Inc.), you may need to add them. Please do this before June 1, 2017. As certificates may need to be renewed or replaced without notice, organizations are encouraged to proactively support the most common CAs.
> 
> Reminder of new base URL for API requests
> Effective on June 5, 2017 the GoTo Developer Center will have a new base URL for all API requests:  https://api.getgo.com. Please note the updated deadline of December 4, 2017 to replace all instances of  https://api.citrixonline.com with  https://api.getgo.com. Your attention to the deadline is much appreciated as the old URLs will NOT be redirected.
> 
> Our number one priority is delivering great service and a best-in-class experience to you, our valued customer. Please contact our team with questions: developer-support@logmein.com.
> 
> We greatly value you as a customer and appreciate the opportunity to serve you!
> 
> Sincerely,
> 
> The team at LogMeIn

**Comment by mqueme** [comment]
This was fixed in #3817
