### ISSUE TITLE
Duplicated entries in History log

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4025]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
We noticed that actions in competitions are not managed in mautic. This is very critical because it means that an action on a contact can be recorded twice. Probably other impacts.
![sans titre](https://cloud.githubusercontent.com/assets/14075239/25867306/777dd032-34f9-11e7-9b39-4b5c883fed1c.png)

## Suggestions:
Why doesn't mautic use transactions in Symfony to avoid those kind of basic issues?

@alanhartless it is a big topic that @webmecanik cannot handle, we think it is very deep in the application here.

### Steps to reproduce:
It is very hard to reproduce, you have to action a second time an action while the first time is started but not enough advanced to notice that the second time should not happen.
1. Send an email
2. Prepare an action of scoring for email openers or webpage viewer
2. Open email or read page
3. Do it again insuring that the first record started but is not totally saved in DB

**Comment by RCheesley** [comment]
@npracht is this still a bug or has it been addressed?

**Comment by npracht** [comment]
I think yes, this is a structural issue we've been discussing with @alanhartless. The structure is still the same in mautic for that kind of thing, so the bug must be still there.

**Comment by YosuCadilla** [comment]
I have noticed this problem in a 2.15.3 instance a couple of weeks ago, didn't have the time to fix it at the moment... I came back to the issue just today and the duplicated entries where simply gone!
I am guessing this could be related to a caching issue? The data seems to be correct in the database, otherwise, we would have double entries live forever, if they show up and disappear, the issue is probably not duplicated entries, but duplicated data somewhere...
Did you solve your issue @npracht  or did it just vanish like mine??

**Comment by YosuCadilla** [comment]
BTW, this issue was really hard to find with a search. I suggest changing it to something like "Duplicated entries in History log"

**Comment by npracht** [comment]
No never. We conclude that it is very deep in mautic conception that competition event can happen.

**Comment by YosuCadilla** [comment]
Thank you @npracht , did you ever experience this again over time?

**Comment by RCheesley** [comment]
Hi folks, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
