### ISSUE TITLE
No way to reset facebook plugin or change api info

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4026]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | Y
| Enhancement? | Y

## Description:
There seems to be no way to reset or edit the facebook app to change the Client ID and secret

## If a bug:

| Q   | A
| --- | ---
| Mautic version | mautic.net
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Ah, you are talking about the mautic.net service. Yes, the FB app is configured for the whole service. If you want to replace it with your app, ask them about a higher plan which supports it. If they provide such option.
