### ISSUE TITLE
Interpretation of some characters

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#4027]
What type of report is this:

| Q  | A
| Q| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | 
No
## Description:
You prepare a email with this in the editor
https://aquaparc.newcom4u.ch/groups/join?group=AQUAVR_suisse

You send you e-mail as a campaign and you receive that... the ? is replace with a &

https://aquaparc.newcom4u.ch/groups/join&group=AQUAVR_suisse

## If a bug:

The link can not use

| Q   | A
| --- | ---
| Mautic version |   2.7.1
| PHP version |    7.0.13

### Steps to reproduce:
1. just put this on your e-mail

https://aquaparc.newcom4u.ch/groups/join?group=AQUAVR_suisse

and send with a campaign

 ps: 
but strange if this is in href it works.... (but i need to show to the customer the link too)
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
The page is not the correct one anymore. We cannot replicate. Could you share the HTML here ?
Thanks,

N.

**Comment by escopecz** [comment]
Closing for lack of response.
