### ISSUE TITLE
Connect a single action to multiple decisions

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#403]
I'm having some strange behaviour on the campaign builder which may or may not be intentional.

Scenario:

Customer receives email - opens -> +20 points -> visits landing page -> fills out form -> +50 points & send email -> continues down the chain
Customer receives email - doesn't open -> +7 days gets reminder -> Opens reminder -> *ideally drop them back in at the +20 points to continue the chain*

I'm not able to connect up the 'opens reminder email' with the '+20 points' action, the arrow won't connect.

Is this intentional?  It seems a bit daft to have to completely replicate half of the chain if I want them to follow the exact same process once the email is opened?

Ruth

**Comment by alanhartless** [comment]
It's intentional right now due to the way the underlying data is stored.  But we quickly realized after release what pain in the butt it is to have to duplicate the same actions for each path.  So it is on our todo list to restructure that to support multiple decisions connecting into the same action.

**Comment by RCheesley** [comment]
Gotcha, is there any ETA for that?  I'll spend the time duplicating if it's something that's a while off as these need to go live imminently :)

**Comment by nuttalla** [comment]
@alanhartless Hi Alan, I think this will be a major issue for any of the Campaigns that I build.  Any campaign with more than a couple of actions will always need the option to return to the original thread.  Imagine a 30 level campaign that will need to clone the main thread (plus children) each time... you will have 30(squared) columns at the bottom! :(

Perhaps a simple fix would be a "tool" box (separate to the Actions and Decisions) and add a "Joiner" object that allows 2 Decisions to join - and subsequently follow the original thread.

**Comment by RCheesley** [comment]
@alanhartless is the only way to achieve this at the moment to duplicate all the workflows?  I've got a campaign launching today, so would be very helpful to know what the best approach would be.

**Comment by alanhartless** [comment]
Merging this into #1414.
