### ISSUE TITLE
Allow non-gated video embed on page?

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4031]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I am testing using video on a landing page, but it seems if you don't use the gated settings the video does not appear in the page. Gated video is great but video on it's own is also useful.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
Raised as a feature request here: https://forum.mautic.org/t/allow-non-gated-video-embed-in-builders/11659

**Comment by namratasaun** [comment]
any update on this?
