### ISSUE TITLE
Landing pages not full width on mobile

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4032]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
None of my landing pages seem to be as wide as expected when viewed on mobile: ![screenshot_20170509-223627](https://cloud.githubusercontent.com/assets/2853040/25874513/d2a13c72-350a-11e7-8792-46917f918e3b.jpg) there is always quite a lot of space either side of the content (tied a few themes). I have a Galaxy Note 5, tired both firefox and chrome. Would be ideal if content showed as wide as the screen, which is how mobile sites usually work on my phone. While the image looks large here on my phone it's tiny and I have to zoom in to see the content.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
Closing due to old issue & likely resolved with new themes. If it's still a problem, do re-open the issue.
