### ISSUE TITLE
Padding of 20px causes small box to appear on landing page

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4033]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
This little blank button keeps showing under my embedded video on landing page:

![screenshot from 2017-05-09 23-33-36](https://cloud.githubusercontent.com/assets/2853040/25875615/598d40b4-3510-11e7-85a3-3b13148a0b4b.png)

Here is the page I am working on: https://ethicalpets.mautic.net/keepin-it-ethical

It wasn't there at first, then it turned up, so I started the page over and it was gone for a while, then it came back. Once it went big and pink...

![screenshot from 2017-05-09 23-34-18](https://cloud.githubusercontent.com/assets/2853040/25875574/2780834c-3510-11e7-959b-9cf639b24b34.png)

Inspect element says: 
<div data-slot-toolbar="true" style="top: -24px;"><a data-slot-action="delete" alt="delete" class="btn btn-delete btn-default"><i class="fa fa-lg fa-times"></i></a></div>
<a data-slot-action="delete" alt="delete" class="btn btn-delete btn-default"><i class="fa fa-lg fa-times"></i></a>
<i class="fa fa-lg fa-times"></i>

Please can you fix this, or help me fix it ASAP, it is holding up a large campaign.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | mautic.net
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by gingerling** [comment]
Also one popped up here now https://ethicalpets.mautic.net/keepin-it-ethical

**Comment by dbhurley** [comment]
This appears to be a CSS issue in your styling based on button styles and a space being included as part of the hyperlink.
