### ISSUE TITLE
Form Actions do not trigger in 2.8.0

### ISSUE THREAD

**Issue by niteshluharuka** [mautic/mautic#4044]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Bug
| Feature request? | 
| Enhancement? | 

## Description:
After upgrading to 2.8.0, none of the form actions are working. It was working before the upgrade. I have updated mautic using root user and believe that I messed with some permissions. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0

### Steps to reproduce:
1. Create a Form with just 1 textbox. Setup Actions to send form results
2. Fill the form. The contact is created but no email sent.

**Comment by dongilbert** [comment]
2.8.1 has not been released, how are you upgraded to 2.8.1?

**Comment by niteshluharuka** [comment]
My mistake, I edited the ticket :)

**Comment by escopecz** [comment]
I cannot replicate the issue. Could you test if there isn't problem in your email configuration or if the email isn't in the spam folder?

**Comment by niteshluharuka** [comment]
I tested the email configuration, it works well and sends me the test email. The email also doesn't land up in spam email. There are no error logs recorded.

The only thing that I can think of is user permissions. My installation runs using user 'X', but I updated mautic using the user 'root'. Can this be an issue?

**Comment by escopecz** [comment]
Could be

**Comment by niteshluharuka** [comment]
Any easy way via SSH to fix all user ownership issue for my installation to user 'X' from root or a handy list where I know ownership of which files needs to change and which to not?

**Comment by escopecz** [comment]
Yes, there is. Search the internet for it based on your server OS or ask your server provider. It's the same as for other PHP apps as Wordpress or Joomla.

**Comment by niteshluharuka** [comment]
I just did that. Made user X as owner of all the files & directories in the installation folder, still no luck :(

**Comment by escopecz** [comment]
Try to follow https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by niteshluharuka** [comment]
I checked that, nothing that sort of. I strongly feel this is some permissions related issue as my campaigns have also not been sending emails after the upgrade.  I have run the following commands on my root via SSH where X is the user- 

 find /home/X/public_html/ -type d -exec chown mcpmain:mcpmain * \;
 find /home/X/public_html/ -type f -exec chown mcpmain:mcpmain * \;

After doing this, I cleared the cache and to be double sure, I used this command - `rm -rf app/cache` as well. There are no migrations present.

The `mautic:campaigns:rebuild` cron returns an error **/usr/local/cpanel/bin/jailshell: /home/X/public_html/app/console: Permission denied** while `mautic.:emails:send` return **Content-type: text/html; charset=UTF-8** nothing much :(

Is there a way where I can revert back to the old version or I can make some tweaks in any file or db to allow mautic to re-upgrade my installation?

**Comment by escopecz** [comment]
It's not about a Mautic version, but file/folder permissions based on the error. The file owner might be correct, but how about the permissions itself?

Try to run these two commands in the Mautic root directory
```
find . -type d -exec chmod 755 {} \;  # Change directory permissions rwxr-xr-x
find . -type f -exec chmod 644 {} \;  # Change file permissions rw-r--r--
```

**Comment by niteshluharuka** [comment]
I have checked that and they seem to be correct. However, I ran these 2 commands again just now. I am also figuring out how to get rid of jailshell error. Will keep you posted. Thank you so very much for your time John helping me to fix this permission issue!

**Comment by niteshluharuka** [comment]
Finally, I managed to get the "Form Actions" working by setting the permissions well. I needed to remove my user X from jailed access to root access giving him higher privileges and this worked.
