### ISSUE TITLE
Required Cron Docs Issue

### ISSUE THREAD

**Issue by michaelgold** [mautic/mautic#405]
Noticed something in the docs that didn't seem right on this page https://www.mautic.org/docs/setup/index.html

To keep campaigns updated with applicable leads:
> php /path/to/mautic/app/console mautic:campaigns:update --env=prod

To execute campaigns events:
> php /path/to/mautic/app/console mautic:campaigns:update --env=prod

Should this be the same command?

**Comment by alanhartless** [comment]
Thanks for reporting this.  We just recently fixed it so it should be good now.

Thanks!
Alan
