### ISSUE TITLE
Sparkpost FBL Webhooks/API Integration

### ISSUE THREAD

**Issue by j-ki** [mautic/mautic#4055]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

## Description:
You can only access SparkPost bounce/spam complaint information via webhooks or API:

https://www.sparkpost.com/docs/faq/retrieve-bounce-info/

Currently, it seems Mautic's only way to access FBL information is if the mailer emails this information to an email address.

And SparkPost isn't the only one. Sendgrid also sends more detailed FBL information through similar methods.

Can we add non-email-address-based FBL methods?

**Comment by escopecz** [comment]
See https://mautic.org/docs/en/emails/bounce_management.html#sparkpost-webhook

**Comment by randhirshinde** [comment]
I have tried to integrate Sparkpost with Mautic. The web hook is generated, but it is not detecting the bounces. After detailed debugging, I found that the rcpt_meta does not contain the hashid. which is required. The sample payload is as follows. Am I missing something?

[
    {
        "msys": {
            "message_event": {
                "event_id": "12616740555912837",
                "rcpt_to": "xxxx@domain.com",
                "raw_reason": "550 [internal] [oob] The recipient is invalid.",
                "transmission_id": "66659943498282695",
                "ip_pool": "shared",
                "template_id": "template_66659943498282695",
                "error_code": "550",
                "bounce_class": "10",
                "timestamp": "1504635973",
                "customer_id": "183921",
                "msg_from": "msprvs1=1742115oZHoUW=bounces-183921@sparkpostmail1.com",
                "sending_ip": "xx.xx.xx.xx",
                "rcpt_meta": [],
                "rcpt_tags": [],
                "template_version": "0",
                "delv_method": "esmtp",
                "message_id": "00033becae592cf740a9",
                "friendly_from": "sales@domain.com",
                "type": "out_of_band",
                "reason": "550 [internal] [oob] The recipient is invalid.",
                "raw_rcpt_to": "xxxx@domain.com"
            }
        }
    }
]

**Comment by 3L1AS** [comment]
I have also similar/same problem: https://www.mautic.org/community/index.php//8464-mautic-is-not-processing-bounce-webhook-from-sparkpost Any idea what to do? Trying with another mail-service?
