### ISSUE TITLE
Builder adding link issue

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4058]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Sometimes (i don't know how to reproduce it 100% of the time, when it does not heppen i close builder and relaunch), when you add the link, the popin to add link in the builder disapear before clicking on close.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8
| PHP version | 

### Steps to reproduce:
Check out this screencast https://share.viewedit.com/rqY5Pxz4Je5zk5AiRs2CuA

**Comment by kuzmany** [comment]
@npracht I discuss this issue with @escopecz .   
Can you confirm If bug is executed on scroll? 
We both reproduce this issue like on scroll issue.

**Comment by npracht** [comment]
On our side we often meet the issue when we click on the pop in

Envoyé de mon iPhone

**Comment by kuzmany** [comment]
Work in progress

**Comment by kuzmany** [comment]
Hey Guys,  
try code review and  test https://github.com/mautic/mautic/pull/5489
