### ISSUE TITLE
Assets max size dont work 

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#406]
I change Assets max size in configuration but changes arent reflected at upload page.

![image](https://cloud.githubusercontent.com/assets/10166840/7625711/ab260372-f9fb-11e4-82f0-311ddd8af55a.png)

![image](https://cloud.githubusercontent.com/assets/10166840/7625705/8fd16166-f9fb-11e4-8fb5-d8fd592ae637.png)

**Comment by escopecz** [comment]
Sometimes the cache is not rewritten on first config save. Can you try to save configuration twice if it solves it?

**Comment by miguelpascual** [comment]
I saved more than 5 times the config. I have tried now and continue with limit at 6Mb

**Comment by escopecz** [comment]
I was not able to recreate this issue. If I save configuration twice then Asset file limit changes. Please, take a look what value do you have for asset file limit (max_size) at /app/Config/local.php. If the value is correct there, try to delete folder app/cache.

**Comment by dbhurley** [comment]
Is it possibly a limit placed by your hosting provider? Can you check to see what the PHP max filesize limit is? Maybe Mautic is unable to override or modify that setting.

**Comment by miguelpascual** [comment]
I probably have some permissions problems. Where I can see the list of minimum permission needed to work properly?

**Comment by alanhartless** [comment]
PHP itself has some hard limits on the file size that can be uploaded.  These are usually stored in your php.ini file on the server.  Depending on your host, that could be in different places and/or may have to contact them to adjust it.

The limit Mautic enforces is based on these settings:

app/config/local.php - max_size
php.ini - upload_max_filesize
php.ini - post_max_size
php.ini - memory_limit

If any of those are less than the size of the asset, it will not be allowed.

Thanks,
Alan

**Comment by alanhartless** [comment]
I believe this is related to #586 and should be fixed in 1.1.3.
