### ISSUE TITLE
Dynamic web content not being rendered

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#4061]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
I have dynamic content I wish to send to an article on my website.  I've set up a slot set up in my Joomla article called 'a'.  The plugin successfully renders the curly-braces into divs, and I see in console a request to grab the dynamic content - e.g. https://mymauticsite.com/dwc/a?mtc_id=842&mtc_sid=5fc050b78e965e1249d50c1b84bd7b008f245aee.

The content, however, is never rendered on the page.  There are no errors in the console, no errors in the Mautic log and no errors in Joomla either.

I have turned off caching for the site and the mautic sub-domain (we were using Cloudflare previously) to ensure this is not affecting the rendering of the javascript or causing problems with caching.  Cache has been purged since it was disabled.

Tested when logged into Mautic in the same browser, and when not.  Tested from more than one geographic location in both IPV4 & IPV6.

Campaign is being triggered and other actions at the same step as the request dynamic content are happening as expected.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.15

### Steps to reproduce:
1. Set up dynamic content
2. Set up segment
3. Set up form with action to add to segment
4. Set up campaign starting with segment from step 3
5. Add request dynamic content, set slot name to 'a', optionally add a tag (to verify campaign is triggering)
6. Create a slot on your website (note, I am using Joomla)
7. Complete form to add yourself to the campaign, in a separate browser to your logged-in admin session
8. After appropriate time delay, go to the relevant page with dynamic content, and check to see it being replaced
9. Check the 'network' tab of your console - look for the request to dynamic content which will be something like https://mymauticsite.com/dwc/a?mtc_id=842&mtc_sid=5fc050b78e965e1249d50c1b84bd7b008f245aee.

In my case, the dynamic content is requested, but nothing is rendered - I still see the default message on the page.
 
### Log errors: 

Nothing is being logged in Mautic, Joomla, or the server logs that I can tell.  No errors in console.

**Comment by RCheesley** [comment]
Possibly related to #3921

**Comment by RCheesley** [comment]
Still present in 2.8.1 for me - anybody got dynamic web content working?

**Comment by ninjoan** [comment]
I have the same problem in 2.8.1 run a lot of test without success.
Run the same test in 2.7.1 works like a champ

**Comment by RCheesley** [comment]
@dongilbert @escopecz anything we can do to provide further details? This is a huge problem for folk using web based DWC - happy to help but I have no clue what would be useful for debugging why the content isn't coming back from Mautic :|

**Comment by dongilbert** [comment]
@RCheesley Can you post the content of the response from Mautic? Or is it simply empty

**Comment by RCheesley** [comment]
Hi Don,

I see the request go off to Mautic for the content as posted. On the
dynamic content slot, nothing at all is rendered, the default content for
the slot is shown instead of what should be shown via the DWC.

Ruth

**Comment by dongilbert** [comment]
Right, I see that - but what is the content of the response returned from the dynamic content request to Mautic? What does Mautic return? I know that it's not replacing anything on the page, but I need to see the content of the JSON response to that request. It will help in debugging. You can PM it to me on Slack if you'd prefer.

**Comment by RCheesley** [comment]
Just to add this was shared on slack - no response coming from Mautic.

**Comment by Harry5-5** [comment]
We are having the same problem as well

**Comment by Aneta09** [comment]
The problem still is. I checked on Mautic Cloud and self-hosted installation (Mautic 2.8.2). Both cases don't work.

**Comment by DerekBuntin** [comment]
I can confirm this doesn't work for us either.

**Comment by dirtroof** [comment]
@dongilbert
I'm on 2.8.2 and can't get it to work.
Will test shortly and report back any error logs, along with JSON response you requested

**Comment by dsp76** [comment]
Didn't get it to work in 2.9.2 either.

**Comment by escopecz** [comment]
More details in https://github.com/mautic/mautic/issues/4607

**Comment by vukee** [comment]
Having the same issue with 2.11.0 here. I see that the slot is requested, but nothing is updated on the website.

**Comment by dongilbert** [comment]
@RCheesley As requested, please provide the response that you see on the Network tab. Dynamic Content is giving a response for me, so we can't really do anything with "it's not working"
<img width="1330" alt="screen shot 2017-11-21 at 6 16 23 pm" src="https://user-images.githubusercontent.com/718028/33101878-2a7d43e2-cee8-11e7-9d8e-4acd6ea44cd6.png">

**Comment by RCheesley** [comment]
I did go through this all, step by step, when I first reported the problem.
Do you need all that info again? I believe it was on DM in slack.

**Comment by arrfonseca** [comment]
@RCheesley 
I was able to solve similar issue by enabling CORS at Wordpress installation, changing my .htacess file. Maybe your problem is related?

**Comment by RCheesley** [comment]
CORS was already enabled and working on the domains

**Comment by dsp76** [comment]
Just a feedback - I got it working with Version 2.12.2 in WordPress as described.

**Comment by AndreaAvalos** [comment]
Hello. I'm also having issues with rendering the Dynamic Content. 

This is how I build up my landing page:
![zeal1](https://user-images.githubusercontent.com/40017996/41081935-83c16a8a-6a67-11e8-9ff5-6b80cdef16da.jpg)

I was expecting to get in return 2 fields from the Contact information
![zeal4](https://user-images.githubusercontent.com/40017996/41081934-839ceef8-6a67-11e8-94b5-ee3c1ccafff2.jpg)
![zeal5](https://user-images.githubusercontent.com/40017996/41081929-82ec1fec-6a67-11e8-9b15-25641e26016e.jpg)

However when running it, the Dynamic Content is not shown
![zeal3](https://user-images.githubusercontent.com/40017996/41081933-8377ee32-6a67-11e8-8eb1-326016c913d5.jpg)

Even when inspecting the object, it does not bring {dwc=slot2} as it was written on the Landing Page's Builder
![zeal2](https://user-images.githubusercontent.com/40017996/41081932-8353a9be-6a67-11e8-9214-90e695e0b5a0.jpg)

My form=6 requests one of the contact's field (the one that filters the Dynamic Content) in case it has not been previously registered, hence not rendering the Dynamic Content. But as you can see two pictures above, form=6 is not asking for the last field, meaning it was been previously registered successfully.
![zeal6](https://user-images.githubusercontent.com/40017996/41081931-832eaa60-6a67-11e8-911e-5ab057b21006.jpg)

Any comments on this would be highly appreciated.

**Comment by davebrener** [comment]
Followed this [video ](https://www.youtube.com/watch?v=eChzJm5yBUk&t=17s)from Mautic step-by-step and Landing Page still does not show Dynamic Web Content. 
Currently running Mautic version 2.15.0
Deleted and re-built cache and still nothing.
Any help incoming? Mautic's Documentation isn't helping with this issue.

**Comment by yonnath** [comment]
> Just a feedback - I got it working with Version 2.12.2 in WordPress as described.
> 
> This means: I receive back data from Mautic for the slot with "status 200 OK" - or - if the contact is unknown or doesn't fit the dynamic web content containg - I receive no answer with "status 204 no content".
> 

I get the same issue: if the contact is unknown, no content status 204 is returner whereas I want to display a form. If the page is refreshed then I get the form. Any idea anyone?

**Comment by yonnath** [comment]
Note that I found a possible workaround (I haven't tested enough but so far it seems to be working): in the Tracking parameters or Mautic, I activated the tracking by URL and also the tracking by browser fingerprinting.
It still takes 3 seconds to display the form but at least it appears and it's not too long so people would close their browser.

**Comment by dsp76** [comment]
strange - in real this shouldn't be related to both tracking mechanisms, although the tracking option settings currently look a bit strange anyway.

however, I think 3 seconds are still way too long for a dynamic content to appear.
