### ISSUE TITLE
Email clickthrough stats on dynamic content missing

### ISSUE THREAD

**Issue by stevegrant1983** [mautic/mautic#4062]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y

## Description:
The "Click Counts" statistics on the View Email page (`/s/email/view/{id}`) only include links that are always present within the email. Any links inserted via Dynamic Content are not included, so we don't get a true reflection of the actual clickthrough rate on an email when it has Dynamic Content included.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.15

### Steps to reproduce:
1. Create email with dynamic content (the dynamic content must contain external links that are not present in the rest of the email), and set up a campaign to send that email to a contact segment
2. Check clickthrough statistics once the campaign has been triggered. Links that aren't in dynamic content are shown, but links within dynamic content are missing.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/6229
