### ISSUE TITLE
Support remote asset URLs that are landing pages rather than the assets themselves

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#407]
I was configured a remote asset in drive

![image](https://cloud.githubusercontent.com/assets/10166840/7626122/c4e100bc-fa02-11e4-8c70-f8dea8625a5e.png)

Asset url: https://drive.google.com/file/d/0B_fg8g9zSSzceHROMmFTUWZwWFk/view

When I use then link provided by Mautic it launch the download but nothing is donwloaded
![image](https://cloud.githubusercontent.com/assets/10166840/7626150/6191a01a-fa03-11e4-9f67-c1e7c76af96c.png)
![image](https://cloud.githubusercontent.com/assets/10166840/7626152/6bc1ddac-fa03-11e4-9d11-59be8c00862d.png)

Is not a permission problem I checked it. With anonymous explorer I can download directly from drive but not through mautic

**Comment by alanhartless** [comment]
That URL is to Google Drive's web viewer page which doesn't actually serve the file.  Try changing the URL to be the direct download. Google how to get a direct download URL for Google Drive and you should find the solution.

Thanks!
Alan

**Comment by miguelpascual** [comment]
OK 
but I think most cases one asset is a url whitout download option. Why asset force to download? is not enough made one redirect to content or landing? (I have no requirements about this is only one think)
