### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS while installing

### ISSUE THREAD

**Issue by STdok** [mautic/mautic#4073]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | A
| Feature request? | 
| Enhancement? | 

## Description:
I'm trying to install mautic to my Linux server. After uploading mautic and going yo mydomain.com, I'm getting an error "ERR_TOO_MANY_REDIRECTS" 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.80
| PHP version | 7.0

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
I'm not able to replicate. And it seems that no one else is having this problem. My conclusion is that the problem is in the server configuration. Please consult it with your sys admin.
