### ISSUE TITLE
Bug when Segment/Filter custom "Select - Multiple" field values 

### ISSUE THREAD

**Issue by fiso85** [mautic/mautic#4075]
What type of report is this:
Bug Report

## Description:
I am trying to create a segment with values from a custom "Select - Multiple" field.

The values available in the "Select - Multiple" field are A, B, & C.

If i create a segment which should include contacts with the value A, I only get contacts with A in the segment. Contacts with A+B, A+C or A+B+C are excluded.

If i create a segment which should include contacts with the value A & B, I only get contacts with A or B in this segment. Contacts with A+B, A+C, B+C, & A+B+C are excluded.

How should I get contacts with multiple values in a "Select - Multiple" field into a segment? 

## If a bug:
| Mautic version | 2.8.0
| PHP version | 5.6.30

### Steps to reproduce:
1.  Create a custom "Select - Multiple" field with values A, B, C
2. Open Segments -> New
3. Select the field created on step 1 and filter one of the values
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Try this fix https://github.com/mautic/mautic/pull/4080 and don't forger regenerate assets
