### ISSUE TITLE
Missing settings in Onesignal integration

### ISSUE THREAD

**Issue by Arjoni** [mautic/mautic#4076]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
[This](https://github.com/mautic/mautic/pull/3274) is missing from the Onesignal integration settings

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 5.6

**Comment by escopecz** [comment]
It's probably solved in https://github.com/mautic/mautic/pull/4077

**Comment by Arjoni** [comment]
How do I apply the PR to test it?

**Comment by escopecz** [comment]
Either copy [the content of the modified files](https://github.com/mautic/mautic/pull/4077/files) or [use git](https://github.com/mautic/mautic#how-to-test-a-pull-request). Either way you'll have to clear the cache and rebuild production assets after the files are modified (described in the second link).
