### ISSUE TITLE
Feature request: Linktracking in Outlook plugin

### ISSUE THREAD

**Issue by arthurscholten** [mautic/mautic#4079]
could you add link tracking to the outlook plugin. I believe the link tracking is already in the campaign email builder but not the plugin.
In my case I send out emails to potential client and ask them how to be in contact. They can click on 4 links going to 4 different pages on my website
No contact
Contact me in 6 months
Contact me in 12 months
Schedule a meeting now.
 
In mailchimp this works perfectly because I can see for each link which email address clicked on it. Mailchimp changes the url for this.
 
Should it be in the mautic outlook plugin as well then, I will not only have linktracking but I will also know which IP address belongs to which emailaddress. This helps to see in webstats who viewed what on the website.

**Comment by winers1290** [comment]
+1 for this. The Outlook plugin is fantastic, since it's always going to be the best place to day to day emails from, but the inability to incorporate redirecting tracking URLs is a major limitation.
