### ISSUE TITLE
Segment Tags Filter Text Input Bug

### ISSUE THREAD

**Issue by MxyzptlkFishStix** [mautic/mautic#4082]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When using the Tags Filter Under Segment, the previous behavior where you could create tags on the fly no longer works.

Example:
![Segment Filter Tags Error](https://s14.postimg.org/epicu36r5/image.jpg)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0/2.8.1
| PHP version | 7.0.18

### Steps to reproduce:
1. Create a segment.
2. Navigate to Filter tab
3. Select Tags as a filter option.
4. Try to create a new tag.  No means to enter any text.
5. Click Save & Close.
6. Receive validation error on Filter tab for not having a tag for the Tags filter.
7. Navigate back to Filter tab.
8. The input area reverts to the correct text field for tag creation.

 ### Log errors: 

None

**Comment by kuzmany** [comment]
Maybe particularly this fix it https://github.com/mautic/mautic/pull/4080

**Comment by MxyzptlkFishStix** [comment]
I tried that patch earlier but missed the regeneration of assets part.  This fixed it and resulted in the expected outcome after I cleared the cache.

Thanks @kuzmany
