### ISSUE TITLE
FetchLeadsCommand.php on line 137 HubSpot Integration

### ISSUE THREAD

**Issue by fabiodallazen** [mautic/mautic#4085]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Hi all,

I need help, the following error occurs to me:

PHP Fatal error: Call to undefined method MauticPlugin\MauticCrmBundle\Integration\HubspotIntegration::pushLeads() in /opt/bitnami/apps/mautic/htdocs/app/bundles/PluginBundle/Command/FetchLeadsCommand.php on line 137

When I try to run the following command:
php /opt/bitnami/apps/mautic/htdocs/app/console mautic:integration:fetchleads --integration=Hubspot

The push command "mautic:integration:pushleadactivity --integration=Hubspot" is OK, the problem only happens with fetch.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 5.6.30

### Steps to reproduce:
1. su daemon -s /bin/sh -c "/opt/bitnami/php/bin/php -q /opt/bitnami/apps/mautic/htdocs/app/console mautic:integration:fetchleads --integration=Hubspot"

 
### Log errors: 

PHP Fatal error:  Call to undefined method MauticPlugin\MauticCrmBundle\Integration\HubspotIntegration::pushLeads() in /opt/bitnami/apps/mautic/htdocs/app/bundles/PluginBundle/Command/FetchLeadsCommand.php on line 137

**Comment by yakov116** [comment]
@escopecz I am having this issue too. For the past few months

**Comment by virlatinus** [comment]
This error is no longer occurring. It was fixed on 2.8.1

**Comment by yakov116** [comment]
Updating/creating leads from Mautic to Hubspot
PHP Fatal error:  Call to undefined method MauticPlugin\MauticCrmBundle\Integration\HubspotIntegration::pushLeads() in ..../mautic/app/bundles/PluginBundle/Command/FetchLeadsCommand.php on line 144

                                                                                                                                   
  [Symfony\Component\Debug\Exception\UndefinedMethodException]                                                                     
  Attempted to call an undefined method named "pushLeads" of class "MauticPlugin\MauticCrmBundle\Integration\HubspotIntegration".  
  Did you mean to call "pushLead"?        

Now the error is on 144

**Comment by yakov116** [comment]
@virlatinus 
Updating/creating leads from Mautic to Hubspot
PHP Fatal error:  Call to undefined method MauticPlugin\MauticCrmBundle\Integration\HubspotIntegration::pushLeads() in ..../mautic/app/bundles/PluginBundle/Command/FetchLeadsCommand.php on line 144

                                                                                                                                   
  [Symfony\Component\Debug\Exception\UndefinedMethodException]                                                                     
  Attempted to call an undefined method named "pushLeads" of class "MauticPlugin\MauticCrmBundle\Integration\HubspotIntegration".  
  Did you mean to call "pushLead"?        

Now the error is on 144

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/4184

**Comment by yakov116** [comment]
@virlatinus Wow thanks.

When would that get released?

**Comment by yakov116** [comment]
@escopecz when will this be released? in the next day or 2?

**Comment by yakov116** [comment]
@virlatinus now i get it on line 221
```
Updating/creating leads from Mautic to Hubspot
PHP Fatal error:  Call to undefined method MauticPlugin\MauticCrmBundle\Integration\HubspotIntegration::pushLeads() in .../mautic/app/bundles/PluginBundle/Command/FetchLeadsCommand.php on line 221

                                                                                                                                   
  [Symfony\Component\Debug\Exception\UndefinedMethodException]                                                                     
  Attempted to call an undefined method named "pushLeads" of class "MauticPlugin\MauticCrmBundle\Integration\HubspotIntegration".  
  Did you mean to call "pushLead"?  
```
Using 2.9.0 beta

**Comment by virlatinus** [comment]
Hi @yakov116 . This will be fixed in https://github.com/mautic/mautic/pull/4370.

**Comment by yakov116** [comment]
@virlatinus Thanks!

**Comment by yakov116** [comment]
@virlatinus I am having anoth thing don't know if its related. It maybe something else. When I dont get an error it says the following 
```Command to fetch contacts from integration
Fetch contacts command is starting

Fetching contacts...

7 contacts were updated and 0 contacts were created

Fetching companies
Fetch companies command is starting

0 companies were updated and 0 companies were created
```

Each time that number (the 7 ) never changes. It does not update (but at least there is no error)
