### ISSUE TITLE
Dynamic content e-mail canno´t add more variation.

### ISSUE THREAD

**Issue by leonardoborlot** [mautic/mautic#4089]
What type of report is this:

| Bug report? | 

## Description:
Hi. The 2.8.1 bring back the Dynamic Content panel outside to the e-mail code editor. But, it don´t have the option to add morte then one variation option

If yout try create a seconde dynamic content, this dont wiil show the button to add a new variation. 

Why you do not bring back the 2.7.1 version of dynamic contet, that works very well!

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 5.5

### Steps to reproduce:
1. Create a new e-mail, select mode code editor, go to Dynamic content label. Try to create a new variation
2. Try to creat a new dinaymic content. it havent the variation options. 
 
### Sugestion

1. Bring back the 2.7.1 dynamic content files, thats version was working very well!

**Comment by luizeof** [comment]
@virlatinus I can reproduce this bug with CD on Code Mode.

@escopecz @dongilbert @alanhartless

**Comment by a1exe1** [comment]
Same on 2.8.2

**Comment by npracht** [comment]
Same on 2.9.0

**Comment by escopecz** [comment]
The button is gone again (https://github.com/mautic/mautic/pull/4371#issuecomment-326278718)

**Comment by npracht** [comment]
@escopecz this has been fixed. The button is back and adding variation works properly today.
