### ISSUE TITLE
Update fails 2.8.0 to 2.8.1

### ISSUE THREAD

**Issue by ramezrafla** [mautic/mautic#4091]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Update from 2.8.0 to 2.8.1 fails - cannot locate Zip

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.0
| PHP version | 7.0.18-1

### Steps to reproduce:
1. Click on notifications, then update
2. In the update page click on 'Update Now'
3. It downloads the package
4. Then fails in 'Extracting Package' -- message is 'undefined'
 
### Log errors: 

[2017-05-18 11:56:38] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'ZipArchive' not found - in file /var/www/html/mautic/app/bundles/CoreBundle/Controller/AjaxController.php - at line 420

**Comment by escopecz** [comment]
Install  and enable `php-zip` extension on your server, restart the server, try again.

**Comment by ramezrafla** [comment]
Thank you! Sorry for the dumb bug, don't know the inner workings of PHP that well.

Here is what solved this for me (using php7.0):
`sudo apt-get install php7.0-zip`
