### ISSUE TITLE
Required params for tracking pixel

### ISSUE THREAD

**Issue by adawolfs** [mautic/mautic#4093]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Hello I'm implementing mautic to track the client behavior across my app but I've found the param tags is required because if it isn't in the request  its not tracked, additionally can you explain me how to fill this fields into contact tracking?

Name, Email, Location, Stage

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7

**Comment by escopecz** [comment]
I cannot replicate with the tags being required.

p[look at the docs](https://mautic.org/docs/en/contacts/contact_monitoring.html) for examples how to track the custom fields. I don't think that stage can be changed via tracking, but I may be just lack the info.
