### ISSUE TITLE
Segment filters doesn't remove contacts which does not fit the filters anymore

### ISSUE THREAD

**Issue by SvetZitrka** [mautic/mautic#4095]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1 
| PHP version | 7

### Steps to reproduce:
1. I create a segment with a condition that corresponds to 3 contacts
2. Cron creates a segment of three contacts
3. Change the segment condition to suit other 4 contacts
4. Cron adds 4 other contacts, but does not delete the original
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Please see if this will fix it for you and let us know.

https://github.com/mautic/mautic/pull/4110

**Comment by tadinski** [comment]
had the same issue #4110 fixes the issue with segments not removing contacts that do not fit the criteria
