### ISSUE TITLE
Contact's company disappears from the contact edit menu

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#4099]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✔️ 
| Feature request? | 
| Enhancement? | 

## Description:

Contact's company disappears from the contact edit menu if you select a company after the 100th alphabetically sorted company.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7.0.18

### Steps to reproduce:
1. Have a database with more than 100 companies
2. Create a new contact belonging to a company that is after the 100th alphabetically sorted company (i.e. does not appear in the initial company dropdown)
3. Save the contact
4. Company is properly assigned to contact
5. Modify the contact
6. Notice the company field is empty
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Fixed in 2.8.0
