### ISSUE TITLE
ZAPIER Integration

### ISSUE THREAD

**Issue by antoniojaco** [mautic/mautic#41]
We use Zapier to integrate our website with 3rd apps.

**Comment by antoniojaco** [comment]
We use Zapier to integrate our website with 3rd apps. 

I think It will be a good step foward

**Comment by renegademarketer** [comment]
+! for this integration. Will open Mautic up to so many platforms you won't have to code yourself.

**Comment by wderuijter** [comment]
Agreed, would be a nice feature.

**Comment by arditveliu** [comment]
I would love this.

**Comment by dalethomas** [comment]
Yes please please please do this!  The guys over at Zapier are fantastic!  And would certainly add more value and usability to Mautic!

**Comment by zapur1** [comment]
This is implemented, early stages
https://www.mautic.org/community/index.php/254-zapier-integration

**Comment by alanhartless** [comment]
Closing in favor of the community provided addon.
