### ISSUE TITLE
categories and segments not loading in contact preferences

### ISSUE THREAD

**Issue by snoek8** [mautic/mautic#4102]
What type of report is this:

 Bug report

## Description:
When clicking "Preferences" for a contact no categories or segments show

## If a bug:
 Mautic version 2.8.0 
PHP version 7.0

### Steps to reproduce:
1. Click on a contact
2. Click on Preferences
3. Click on Categories tab and type in text box
4. Click on Segments tab and type in text box

Expect to see the available categories and segments

**Comment by escopecz** [comment]
I cannot reproduce this. Could you check if there is something special one have to do to get this bug? Do you have some special characters like apostrophes in the category/segment name? Do you have some PHP errors in [the logs](https://mautic.org/docs/en/tips/troubleshooting.html)? Or in the JS console?

**Comment by snoek8** [comment]
No errors in the logs also no special characters in categories or segments
and no errors in the console. What should trigger those lists to load is it
a type-ahead that triggers an Ajax call or are they loaded the moment you
open the popup?

Stephan

**Comment by escopecz** [comment]
Can you test with latest Matuic version?
