### ISSUE TITLE
Point triggers bug

### ISSUE THREAD

**Issue by tadinski** [mautic/mautic#4103]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ☑️
| Feature request? | 
| Enhancement? | 

## Description:
Trying to create a point trigger with the option "Trigger for existing applicable contacts upon saving (if published)". The saving process takes a while and eventually fails (no banner confirmation and the buttons on the right become greyed out. See screenshot

<img width="1168" alt="trigger" src="https://cloud.githubusercontent.com/assets/6358371/26279294/f4b64052-3daf-11e7-8373-795109622dce.png">

----------------------------------------------------------------------------------------------------

<img width="1174" alt="trigger2" src="https://cloud.githubusercontent.com/assets/6358371/26279295/f9162298-3daf-11e7-9571-7d5ad32bf66a.png">

Setting the switch to off for the option "Trigger for existing applicable contacts upon saving.." does the trick, but this is not what I want. 

The log shows a memory exhausting error, I have allocated 512MB and even 1GB and set execution times to a larger number. Nothing works, the same problem.

- I have a relatively large contact list, ±80k.
- Not all of the contacts have points

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7.0

 
### Log errors: 

mautic.ERROR: Symfony\Component\Debug\Exception\OutOfMemoryException: Error: Out of memory (allocated 438304768) (tried to allocate 20480 bytes) - in file /home/******removed_for_privacy******/domains/******removed_for_privacy******/public_html/app/bundles/LeadBundle/Entity/CustomFieldRepositoryTrait.php - at line 86 [] []

**Comment by npracht** [comment]
Cannot reproduce
