### ISSUE TITLE
Custom field - Multiple choice - Not populated by form

### ISSUE THREAD

**Issue by gdledsan** [mautic/mautic#4105]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  yes

## Description:
Multiple choice filed data reaches the form but does not reach the contact.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version |  5.6.30

### Steps to reproduce:
1. Create custom field and set it as multiple choice
2. Create a form that sends data to that custom field.

### actual Behavior
Form has the data, contact does not.

## expected behavior
Contact should have the data on the given custom field
 
### Log errors: 
Nothing in the logs

**Comment by npracht** [comment]
Hi, we're currently working on it with @MaxWebmecanik

**Comment by npracht** [comment]
+ duplicate https://github.com/mautic/mautic/issues/3741
