### ISSUE TITLE
Missing DKIM in email sent

### ISSUE THREAD

**Issue by ServicedCloud** [mautic/mautic#4108]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
We are using self-hosted mautic and recently updated from 2.7.1 to 2.8.1. We have noticed that emails being sent out has no DKIM. Upon checking on the email headers, we've noticed that the value of enveloped-from was changed.  It is deciding to use the default email address instead of the email account that it is configured with. The default email address of the account/webspace is for example mauticemail@webspace.com which is incorrect because we have configured it as for example correctemail@webspace.com 
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 5.6.30

### Steps to reproduce:
1. Go to settings > Configuration > Email Settings > 
   - Custom return path (bounce) address : correctemail@webspace.com 
   - E-mail address to send mail from: correctemail@webspace.com 
2. Test out campaign, see email header (in this scenario, we used gmail) there is no DKIM, checked out enveloped-from and it has the default email address of the account/webspace instead of what we have configured > correctemail@webspace.com 
 
Then nothing in the logs.

**Comment by ServicedCloud** [comment]
Hi @escopecz, can i confirm that you have duplicated the results of the bug i mentioned above?

**Comment by ServicedCloud** [comment]
We did a few testing and figured out that if "sendmail" is used as "Service to send mail through" instead of PHPmail, the DKIM is working - the value of envelop-from address is correct.

Configuration > Email Settings > Service to send mail through : sendmail

Can i ask if this is an ideal settings? or any explanation as to why the envelop-from is correct using sendmail?

**Comment by MxyzptlkFishStix** [comment]
If you don't set up a custom "sendmail_path" in php.ini, it'll use the system default email or the email address assigned to the web server user.

https://secure.php.net/manual/en/mail.configuration.php#109375

**Comment by ServicedCloud** [comment]
Hi @escopecz >> Can we reopen this issue? Still the envelop-from value is incorrect using phpmail as the service to send mail through.

**Comment by escopecz** [comment]
It seems to be issue of your mail server configuration. I don't see Mautic setting "envelop-from" [anywhere in its code](https://github.com/mautic/mautic/search?utf8=%E2%9C%93&q=envelop-from&type=).

**Comment by ServicedCloud** [comment]
Hi @escopecz - we have talked to our hosting provider and they have conducted tests with PHP to determine if it is interacting with the server correctly.

They tested PHP Mail with script; and the result was success.

Then they checked to ensure that the from address was set correctly by checking the exim logs; and the result was correct.

From the tests i have mentioned above, they can confirm that as long as the script that is interacting with PHP Mail is coded correctly, the from address will be what we are expecting.

Can i ask if Mautic may have issues in phpmail?

**Comment by escopecz** [comment]
Ok, reopening.

**Comment by wpon** [comment]
Hi @ServicedCloud ,

We are using "Other SMTP Server" on "Service to send mail through",
envelop-from is correct but DKIM is missing too.

Have you find any way to enable DKIM?

Related reported issue:
https://github.com/mautic/mautic/issues/5190

**Comment by ServicedCloud** [comment]
hi @wpon,

we managed to resolve this by using "Sendmail"
