### ISSUE TITLE
Gravatar Break

### ISSUE THREAD

**Issue by rc125** [mautic/mautic#4114]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The avatar URL has a broken URL after change domain do Https

The url should load like 

https://www.gravatar.com/avatar/9c298bb2094164fd00889f8e558fb720?s=250&d=**domain**/media/images/avatar.png

Instead, It load like this:

https://www.gravatar.com/avatar/9c298bb2094164fd00889f8e558fb720?s=250&d=:///:/media/images/avatar.png

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7

### Steps to reproduce:
1. Install Https certificate
2. Change the mutic URL to https
 
### Log errors: 
[2017-05-22 08:59:30] mautic.WARNING: PHP Warning - extract() expects parameter 1 to be array, boolean given - in file /var/www/mautic/app/bundles/CoreBundle/Helper/UrlHelper.php - at line 118 [] []

**Comment by rc125** [comment]
Sorry for that, i just found the error: $_SERVER['SERVER_NAME'] was not reuturning any value. 

This because the the server_name was not set in my nginx https server configuration. 

`  server {
     listen 443 ssl http2;
     listen [::]:443 ssl http2;
     server_name 192.168.15.100;
...`

**Comment by escopecz** [comment]
Cool. Thanks for letting us know what the issue was!

**Comment by npracht** [comment]
Hi @rc125 can you test and confirm https://github.com/mautic/mautic/pull/6984 solves the issue ?
