### ISSUE TITLE
When send emails, adding "3D" and "= " inside HTML source code

### ISSUE THREAD

**Issue by RiusmaX** [mautic/mautic#4115]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:

I use Mautic on docker, my SMTP host is OVH.

I create a new email, I set all necessary things for the sending, and i put my own HTML code into it (same thing with a template).
When I preview the email, it displaying correctly, but when I send it (as a test or as a real mail), i have some "3D" and "= " inside the email source code (I tried on my own domain or on Gmail).

Result : some pictures not loading or some css/html isn't applied.

What can I do ?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7.0.18

### Steps to reproduce:
1. Create a new mail
2. Apply custom HTML code
3. Send it
4. Look at the source code sent by Mautic  
 
### Log errors: 

Unfortunatly, no logs on this :/

**Comment by escopecz** [comment]
> When you see something like =3D, what you’re seeing is a single character in what’s called “quoted-printable” encoding. “=3D” is, in fact, an equal sign. 

https://askleo.com/why_does_my_email_sometimes_show_up_with_funny_characters_like_0d_in_it/

**Comment by lhamaella** [comment]
Heya, did this issue was fixed? passing through the same and don't know what to do :/

**Comment by escopecz** [comment]
@lhamaella please follow the link I posted in the above comment. This is not an issue of Mautic. That's how emails source code looks like.

**Comment by lhamaella** [comment]
But is there a way to "fix" the email source.. because somehow is it adding a "=" to the URL from my tracking pixel, which is making it not to be able to track the opens and clicks.

Thanks for the response.

E
