### ISSUE TITLE
Error on remote asset download from form

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4116]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Sometimes the remote asset download from form does not work. Please check hereunder the way to reproduce.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 

### Steps to reproduce:
1. Be sure your general configuration is in HTTPS
1. Create a remote asset in HTTPS
2. Create a form
3. Add download asset action with this asset
4. Submit form and notice that it does not work

#### Few more details
* If application in HTTPS + Configuration HTTP ---> It works 👍 
* If application in HTTP + Configuration HTTP ---> It works 👍 
* If application in HTTPS + Configuration HTTPs ---> It does not work 👎  ⚔️

**Comment by kuzmany** [comment]
Confirmed

**Comment by alanhartless** [comment]
Reopening this since the suggested PR didn't get merged due to implementation and the issue still persists (confirmed in M3).

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Forms > Submit Action: Download asset (check remote and local assets)](https://trello.com/c/cG0qVQVl/204-forms-submit-action-download-asset-check-remote-and-local-assets)
