### ISSUE TITLE
Salesforce Error Provided external ID field does not exist or is not accessible: query

### ISSUE THREAD

**Issue by isleshocky77** [mautic/mautic#4118]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y |

## Description:

Mautic is sending a notification that the Salesforce integration had an error

```
Salesforce Error
Provided external ID field does not exist or is not accessible: query
```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.8.1
| PHP version | 5.6.30

### Steps to reproduce:
1. Enable Salesforce integration

**Comment by isleshocky77** [comment]
cc @mqueme

**Comment by alanhartless** [comment]
I think this has to do with a session issue as it disappears after the first run but comes back after some idle time.

**Comment by isleshocky77** [comment]
With the latest code base I got the following status output which doesn't make sense to me

```Updating/creating leads from Mautic to Salesforce
About 6 to update and about 0 to create/update
 6/6 [============================] 100%
Number of contacts pushed: 0 updated, 0 created, 0 had errors and 0 were ignored (likely duplicates)
```
