### ISSUE TITLE
[UX] Add the Campaign Name somewhere on the Campaign Builder screen

### ISSUE THREAD

**Issue by isleshocky77** [mautic/mautic#4119]
What type of report is this:

| Q  | A
| ---| --- 
| Enhancement? | Y

## Description:

Currently, once you enter the Campaign Builder you have no context of which Campaign you're editing. The page's title changes to "Edit Campaign" and the builder's workflow has no mention of the actual campaign.

If you're editing multiple campaign funnels at once it makes it very difficult to know which one you're actually on.

The page title should mention the current campaign name as well as putting somewhere on the page the campaign the workflow is for.

### Steps to reproduce:
1. Edit Campaign and open up Campaign Builder
2. Open second tab and Edit Campaign and open up Campaign Builder
3. Figure out which tab is for which campaign

**Comment by RCheesley** [comment]
+1 on this, I have found this repeatedly and had to exit out to check the campaign!
