### ISSUE TITLE
Mistake in identifying contact logic post email clicks

### ISSUE THREAD

**Issue by saint2016** [mautic/mautic#4121]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
If a contact:

1) has previous history of browsing in the tracked site with browser X (say mtc_id=1) AND 
2) if she's registered already through browser Y or API (say mtc_id=2) AND 
3) if she arrives to site through the link sent from a campaign email in browser X

mautic keeps the mtc_id 1, while it should merge mtc_id 1 to mtc_id 2.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7.0

### Steps to reproduce:
1. Open incognito browser.
2. Fill form to register, close the browser
3. Go to mautic, send email to the same email address
4. Open incognito browser and browse to the site (and thus get an initial mtc_id, unidentified)
5. Without closing the browser copy-paste the link from the email
6. Old (and unidentified) mtc_id is kept

If this is a feature, is there a way to disable it from settings so last click from email always wins?
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 
None, this is logic error (to me).

**Comment by kuzmany** [comment]
This should fix it https://github.com/mautic/mautic/pull/3685
