### ISSUE TITLE
Landing page nl_BE redirects to nl_NL

### ISSUE THREAD

**Issue by kevinvanhove** [mautic/mautic#4127]
What type of report is this:

| Bug report | 

## Description:
Creating a landing page in the language **nl_NL** and connecting it to a landing page in the language **nl_BE** (using **is a translation of**), will redirect all traffic from nl_BE to the nl_NL page. This happens all the time in safari and sometimes in chrome.

## If a bug:

| Mautic version | 2.8.1 (fresh install)
| PHP version | 7

### Steps to reproduce:
1. create landing page in nl_NL
2. create landing page in nl_BE
3. connect nl_NL with nl_BE using 'is a translation of'
4. preview the nl_BE landing page in safari
 
### Log errors: 
no errors...

**Comment by RCheesley** [comment]
Tested and unable to reproduce so closing issue.
