### ISSUE TITLE
500 if you edit contact with more than 255 car in Firstname

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4128]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
I think the title tells everything :)
Error 500 if you edit a contact with more than 255 characters in the Firstname contact field.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1 - It was not existing in 2.7 !
| PHP version | 

Maybe related to https://github.com/mautic/mautic/issues/4125 ?

**Comment by escopecz** [comment]
Closing in favour of https://github.com/mautic/mautic/issues/4125. No need to have special issue for each field with this error.
