### ISSUE TITLE
Bug: Clicking cancel sheduled event on lead has no effect

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#4131]
## Description:
Can't cancel or modify individual contact events

| Mautic  2.8.1
| PHP 7.0.15-0ubuntu0.16.04.4 

### Steps to reproduce:
*1 Upon opening a lead with a scheduled event:*
![image](https://cloud.githubusercontent.com/assets/10385295/26373346/85724f5a-4044-11e7-87a6-ef195b1bef03.png)
*2 Then clicking toggle details*
![image](https://cloud.githubusercontent.com/assets/10385295/26373376/a732af04-4044-11e7-85b7-eff80bcccfd7.png)
*3 no change*
 
### Log errors: 
No errors are logged

**Comment by mrerich** [comment]
yeah, got the same error

**Comment by MaxWebmecanik** [comment]
Hey, this PR should fix that problem https://github.com/mautic/mautic/pull/4509

**Comment by npracht** [comment]
@escopecz i think it can be closed :)
