### ISSUE TITLE
Report page is not working after I Upgrade to 1.8.1

### ISSUE THREAD

**Issue by ttmubarak** [mautic/mautic#4132]
Bug Report :+1: 

I can't able to load Reports in mautic latest version. 
Mautic version : 1.8.1 (latest)
php version: php7

Please tell me any reason behind this. or please solve this issue.

Thank you

**Comment by escopecz** [comment]
Please provide steps to reproduce the issue and you should be able to edit the problematic report, so share with us screenshot of how it is configured. Also an error message would help a lot (https://mautic.org/docs/en/tips/troubleshooting.html)
