### ISSUE TITLE
mautic.WARNING: PHP Warning - A non-numeric value encountered

### ISSUE THREAD

**Issue by ilearnbydoing** [mautic/mautic#4133]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes

## Description:
Getting this errors [2017-05-24 07:12:44] mautic.WARNING: PHP Warning - A non-numeric value encountered - in file /vendor/knplabs/knp-menu/src/Knp/Menu/Matcher/Matcher.php - at line 65 [] []
automatically in log.
## If a bug:

| Q   | A
| --- | ---
| Mautic version : | 2.8.1 
| PHP version: |  7.1

### Steps to reproduce:
1. 
2. 
 
### Log errors: 
[2017-05-24 07:12:44] mautic.WARNING: PHP Warning - A non-numeric value encountered - in file /vendor/knplabs/knp-menu/src/Knp/Menu/Matcher/Matcher.php - at line 65 [] []

This problem only coming in PHP v7.1

**Comment by skynet** [comment]
How did you get Mautic to install with php 7.1? I wasn't able to do so with php 7.1.20.
