### ISSUE TITLE
Email Dynamic Content not working on "Manual Send Email"

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4135]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When you manually send an email from the contact detail page. Contact token are well replaced but not the `Dynamic Content token`.

![automation4](https://cloud.githubusercontent.com/assets/14075239/26397067/63cafe34-4075-11e7-820c-fd4b54b4eb2c.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 

### Steps to reproduce:
1. Create an email with dynamic content (and contact token if you like to see)
2. Send manually the email to a contact (from contact detail page)
3. Notice that the dynamic content token is still there

**Comment by dakur** [comment]
I confirm it does not work for us as well.

**Comment by alexhammerschmied** [comment]
Is there a solution for that yet? One of my clients encountered the same problem on a fresh installation. (version 2.15.1)

**Comment by RCheesley** [comment]
Hi @npracht, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by lukafatur** [comment]
I seem to be having the same problem. 

I set up the dynamic content to be filtered according to some custom fields. I have then integrated that dynamic content into my HTML template for my email - and when I manually send it id does not fill up the dynamic content :( - btw I'm in love with Mautic 👍
