### ISSUE TITLE
Track Pages hit counts for each tracked URL

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4136]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | x

## Description:
In the page report, the values on `hit count` & `unique hit count` are not counted for pages which are not **mautic landing pages**.

### It would be great to also include data from tracked webpages.

![capture d ecran 2017-05-24 a 11 25 38](https://cloud.githubusercontent.com/assets/14075239/26397381/6505047e-4076-11e7-84e6-4324305c4c47.png)

**Comment by escopecz** [comment]
Yes, those count columns are for internal landing pages only

**Comment by npracht** [comment]
Then this is a feature request! I don't think it's hard to extend to all pages... it would drastically improve tracking analytics reporting experience!

**Comment by arthurscholten** [comment]
I guess the registration of the HIT URL should also be extented to all URLs tracked. Since the tracking code is added to all pages of the website, all pages should show up as HIT URLs in the HIT URL report.
