### ISSUE TITLE
Can't edit scheduled send mail dates in campaigns

### ISSUE THREAD

**Issue by appscaptain** [mautic/mautic#4144]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Send dates do not update if you update a scheduled send mail action in a campaign before it has triggered, which makes it impossible to do any edits. You basically have to be 100% sure of any send dates before you launch the campaign or you're screwed. And going forward the contact is just dead. You can't add any later scheduled send mail steps to the campaign the contact is in. Those scheduled e-mails never appear.

This means that you basically have to set up the campaign "perfectly" and 100% be sure that you set the dates correctly or you'll have a problem.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1 (upgraded from 2.1.1 - cache has been deleted)
| PHP version | 7.0

### Steps to reproduce:
1. Set up a campaign with a scheduled Send Mail action for a date (eg. tomorrow)
2. Add contacts to the campaign (the contacts shows a scheduled mail entry under Upcoming Events for the contact)
3. Before "tomorrow", postpone the send mail date (eg. push it 3 days forward).
4. Apply the changes to the current campaign
5. The change is NOT reflected in the Upcoming Events section for any contact part of the campaign.

P.S. Removing the contact from the campaign and adding it again just removes the scheduled mail send entry under Upcoming Events completely
### Log errors: 
[2017-05-24 15:09:32] mautic.WARNING: PHP Warning - mkdir(): Permission denied - in file /home/path/to/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php - at line 193

**Comment by escopecz** [comment]
The error is not related. Fix the filesystem permissions on your server.

**Comment by appscaptain** [comment]
Ok - what should the permissions be for this file and other? They are 644 root:root for Mailbox.php

**Comment by appscaptain** [comment]
And all of a sudden my installation provides me an error 500. Is there a script to set the permissions as required for Mautic or a general guideline for permissions and owner:group?

**Comment by escopecz** [comment]
See https://github.com/mautic/mautic/issues/4044#issuecomment-301152061. The user and group should be the same as what your server use.

**Comment by appscaptain** [comment]
Ok, thanks!
