### ISSUE TITLE
Mailchimp lists are limited to 25

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#415]
When integrating with Mailchimp, a max of 25 lists will show which is the default set by the Mailchimp API.  "limit" needs to be included in the parameters but even then, only 100 lists are allowed at once. There needs to be some sort of pagination/filtering in order to be able to search all lists.

**Comment by YosuCadilla** [comment]
Related to #6985 ?

**Comment by alecmyers** [comment]
Yes, related to #6985. The correct field for retrieving more than 10 records is 'count' not 'limit' - thus:
return $this->request('lists', ['count' => 100]);
