### ISSUE TITLE
Page hit feature .

### ISSUE THREAD

**Issue by ajmalsha** [mautic/mautic#4152]
hi i'm new in mautic so i dont have deep knowledge in it .

can you please ecplain the use of **Page Hit Event** which is found in **Webhook Events**.

Thanks

**Comment by escopecz** [comment]
Whenever Mautic tracks a page hit, the webhook can forward the data to the URL you specify in the webhook together with information about the contact. Please use GitHub issues for reporting bugs or new features next time. If you have a question, ask at https://www.mautic.org/community. Thanks!
