### ISSUE TITLE
Ability to view and change segments from the Contact Show screen

### ISSUE THREAD

**Issue by isleshocky77** [mautic/mautic#4154]
What type of report is this:

| Q  | A
| ---| ---
| Feature request? | Y

## Description:
Currently I believe it's impossible to figure out what **Segments** a user is in from the _Contact Show_ page. And it's also impossible to actually change which **Segments** a user is part of from the _Contact Show_ page.  In the _Contact Show_ page there is currently a link for _Campaigns_ which works nicely for allowing you to see what _Campaigns_ a _Contact_ is part of and changing that membership. Having the same thing for **Segments** would be really helpful.

## Individual Contact's Campaigns Workflow

This could be replicate for Segments

![view_contact_menu_campaigns](https://cloud.githubusercontent.com/assets/361586/26455552/95194e64-4138-11e7-9e82-38396f7fb091.png)

![view_contact_change_campaigns](https://cloud.githubusercontent.com/assets/361586/26455554/98413516-4138-11e7-8075-410d3df67129.png)

**Comment by mqueme** [comment]
Try the preferences button.

**Comment by isleshocky77** [comment]
@mqueme I just had this pointed out to me in the #support slace; however, I would say there should be consistency between Campaigns and Segments. Why is one different than the other? Maybe update this to a [UX] issue.

**Comment by mqueme** [comment]
Segments show in the preference center(through the unsubscribe page) for contacts when they are set as public.

**Comment by RCheesley** [comment]
@mqueme only if the Mautic instance is set up to allow that - not for all. So I do see the reasoning, but it is pretty confusing. I did not even think to look under user preferences to find segment info - I thought it was on this dropdown, realised it wasn't any more, and went looking for other ways. Never once thinking to look under preferences! Either monkeys need training, or the UX needs a bit more attention :monkey:
