### ISSUE TITLE
Erroneous data added after update applied via CLI.

### ISSUE THREAD

**Issue by MrKennie** [mautic/mautic#4157]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
After performing an update via console CLI erroneous data is added to the database leading to incorrect stats. Data is added to the following tables:

leads
audit_log
ip_addresess
page_hits
lead_ips_xref

This has happened for me since 2.7.0. Seems to be left over data from a developer.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7.0.15

### Steps to reproduce:
1. Simply perform an update freom a previous version via console using `php console mautic:update:apply`
 
### Log errors: 
No errors

**Comment by escopecz** [comment]
Please try to follow the official upgrade process with the upgrade script next time and let us know if you had some troubles with it https://www.mautic.org/community/index.php/7679-2-8-1-released

I'll mark this as a bug since the commands either shouldn't be available or be working correctly.

**Comment by MrKennie** [comment]
I've tried upgrading via the official upgrade process and remembered why I used cli instead. The upgrade process happens with no apparent error and right after finalising I get returned to the upgrade page asking me to upgrade from 2.8.1 to 2.8.2 again. No update has been performed at all from what I can tell.

This is from error logs.

`2017/06/02 11:20:43 [error] 1007#1007: *3912 FastCGI sent in stderr: "Unable to open primary script: /var/www/em/mautic//upgrade/upgrade.php (No such file or directory)" while reading response header from upstream, client: 212.*.*.*, server: somewhere.com, request: "GET /upgrade/upgrade.php?task=moveBundles&updateState=W10=&_=1496402323460&mauticUserLastActive=1&mauticLastNotificationId= HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "somewhere.com", referrer: "https://somewhere.com/s/update"`

I seem to remember getting this exact error before but since cli worked fine, apart from the extra data getting added, I never really looked back.

**Comment by MrKennie** [comment]
Just to add, during the process, the package contents are extracted to /upgrade and upgrade.php does exist.

**Comment by MrKennie** [comment]
I've performed the 2.8.2 update via console today and I did not get any additional data so has this been fixed in this version? It's strange that nobody else has reported it or they just haven't noticed.

**Comment by MrKennie** [comment]
Unfortunately updating via console still ends up with erroneous data with version 2.9.1. It's not a huge issue to clean it up but I'm not sure why it should be there at all. Updating via console is the only method that works for me and I really hope the feature remains. Personally I prefer updating via the cli but that's just me.

**Comment by npracht** [comment]
Very old version, no reason to try to fix updating by console for such a version.
