### ISSUE TITLE
Campaign opens email decision doesn't seem to work if the email is manually selected

### ISSUE THREAD

**Issue by tmorrison01** [mautic/mautic#416]
I have setup Mautic and have successfully implemented a campaign that sent out one email message to a lead when the lead was added to a lead list. I then created a second campaign and using the campaign builder and did the following: 1. send email 2. open email wait 2 min. 3. send follow up email. The first action (1. send email ) worked correctly, the second decision (open email wait 2 min.l) did not and the third action send follow up email also did not work. This is confirmed when view the campaign page. It shows the Actions 1. send email  50%, 3. send follow up email 0%, Decisions 0%.  It may be important to note that after the email is sent when i view the email stats in (email manager) it only shows the graph for the Total, there is no graph for Email sent or Email read however it does show on the main page of the email manager 1 as the # Sent  but again does not show #read. Also when the email is received in my email client it is clicked and read.

**Comment by alanhartless** [comment]
Hi,

Is image loading enabled for your email client? Images have to load as it is a tracking pixel that notifies Mautic that an email has been read.

**Comment by tmorrison01** [comment]
Ok that resolved part of the issue. Now in the email manager it shows the emails  # Sent and  #Read. The graph however still only shows for the Total  and not for Email sent or Email read.  More importantly the campaign page shows the Actions 1. send email is now 100%, 3. send follow up email 0%, Decisions 0%. So i am still not receiving the follow up email. I have the campaign builder set for the following:
1. Send initial Email (uses email New Test Email 3)
2. Open Email (Opens New Test Email 3)
3. Send Follow Up Email (waits 2 minutes then sends 2nd Follow Up Email)

**Comment by alanhartless** [comment]
The graph is confusing as it's associated when you send a mass email to a specific list and not the through the campaign.  We are going to remedy that for the next release.

For #2, do you have the email selected in the 'opens email' decision or left it blank? If you selected the email, can you try leaving it blank? Does that make any difference?

Thanks,
Alan

**Comment by tmorrison01** [comment]
I did catch that and made the changes. I also changed the interval time to 5 minutes for the follow up email (it was set to 2 minutes before.) I also removed the the follow up email from the lead list. Everything is working now. Important question. Which filter operation should be used to automatically add a lead to a lead list.  I am using the first name, last name and email fields.

**Comment by alanhartless** [comment]
Sounds like we have a bug when the opens email has a filter manually selected.  I'll change the title and mark this a bug so we can look into it further.
