### ISSUE TITLE
"Visited URL" segment filter throws a database error

### ISSUE THREAD

**Issue by Arjoni** [mautic/mautic#4160]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
I created a segment with filter "Visited URL". When the cronjob runs, it throws this error:

`[2017-05-27 23:07:27] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DISTINCT l.hiturl FROM em_leads l WHERE (l.hiturl <> '') AND (l.hiturl IS NOT NULL) ORDER BY l.hiturl ASC LIMIT 10 OFFSET 0':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list'" at /var/www/marketing.domain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DISTINCT l.hiturl FROM em_leads l WHERE (l.hiturl <> '') AND (l.hiturl IS NOT NULL) ORDER BY l.hiturl ASC LIMIT 10 OFFSET 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/marketing.domain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/marketing.domain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/marketing.domain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 5.6

### Steps to reproduce:
1. Create a segment
2. Apply "Visited URL" filter
 
### Log errors: 

`[2017-05-27 23:07:27] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DISTINCT l.hiturl FROM em_leads l WHERE (l.hiturl <> '') AND (l.hiturl IS NOT NULL) ORDER BY l.hiturl ASC LIMIT 10 OFFSET 0':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list'" at /var/www/marketing.domain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DISTINCT l.hiturl FROM em_leads l WHERE (l.hiturl <> '') AND (l.hiturl IS NOT NULL) ORDER BY l.hiturl ASC LIMIT 10 OFFSET 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/marketing.domain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/marketing.domain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/marketing.domain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []`

**Comment by soundgraphs** [comment]
Hi, i've got thesame bug here.

**Comment by MxyzptlkFishStix** [comment]
Did you run all your migrations/schema updates successfully?  I can't replicate.

**Comment by Arjoni** [comment]
doctrine:schema:update --dump-sql returns: 
`ALTER TABLE em_dynamic_content_lead_data DROP FOREIGN KEY FK_54218704D9D0CD7;
ALTER TABLE em_dynamic_content_lead_data ADD CONSTRAINT FK_54218704D9D0CD7 FOREIGN KEY (dynamic_content_id) REFERENCES em_dynamic_content (id) ON DELETE CASCADE;
DROP INDEX tweet_text_index ON em_tweets;
CREATE INDEX em_tweet_text_index ON em_tweets (text);
DROP INDEX sent_count_index ON em_tweets;
CREATE INDEX em_sent_count_index ON em_tweets (sent_count);
DROP INDEX favorite_count_index ON em_tweets;
CREATE INDEX em_favorite_count_index ON em_tweets (favorite_count);
DROP INDEX retweet_count_index ON em_tweets;
CREATE INDEX em_retweet_count_index ON em_tweets (retweet_count);
ALTER TABLE em_tweet_stats DROP FOREIGN KEY FK_7EFEECD755458D;
ALTER TABLE em_tweet_stats DROP FOREIGN KEY FK_7EFEECD71041E39B;
DROP INDEX stat_tweet_search ON em_tweet_stats;
CREATE INDEX em_stat_tweet_search ON em_tweet_stats (tweet_id, lead_id);
DROP INDEX stat_tweet_search2 ON em_tweet_stats;
CREATE INDEX em_stat_tweet_search2 ON em_tweet_stats (lead_id, tweet_id);
DROP INDEX stat_tweet_failed_search ON em_tweet_stats;
CREATE INDEX em_stat_tweet_failed_search ON em_tweet_stats (is_failed);
DROP INDEX stat_tweet_source_search ON em_tweet_stats;
CREATE INDEX em_stat_tweet_source_search ON em_tweet_stats (source, source_id);
DROP INDEX favorite_count_index ON em_tweet_stats;
CREATE INDEX em_favorite_count_index ON em_tweet_stats (favorite_count);
DROP INDEX retweet_count_index ON em_tweet_stats;
CREATE INDEX em_retweet_count_index ON em_tweet_stats (retweet_count);
DROP INDEX tweet_date_sent ON em_tweet_stats;
CREATE INDEX em_tweet_date_sent ON em_tweet_stats (date_sent);
DROP INDEX twitter_tweet_id_index ON em_tweet_stats;
CREATE INDEX em_twitter_tweet_id_index ON em_tweet_stats (twitter_tweet_id);
ALTER TABLE em_tweet_stats ADD CONSTRAINT FK_7EFEECD755458D FOREIGN KEY (lead_id) REFERENCES em_leads (id) ON DELETE SET NULL;
ALTER TABLE em_tweet_stats ADD CONSTRAINT FK_7EFEECD71041E39B FOREIGN KEY (tweet_id) REFERENCES em_tweets (id) ON DELETE SET NULL;`

php app/console doctrine:migration:status returns the following:

`== Configuration

   >> Name:                                               Mautic Migrations
    >> Database Driver:                                    pdo_mysql
    >> Database Name:                                      mauticmarket
    >> Configuration Source:                               manually configured
    >> Version Table Name:                                 em_migrations
    >> Version Column Name:                                version
    >> Migrations Namespace:                               Mautic\Migrations
    >> Migrations Directory:                               /var/www/marketing.enterprise.com.al/app/migrations
    >> Previous Version:                                   2017-05-03 14:36:50 (20170503143650)
    >> Current Version:                                    2017-05-06 14:46:49 (20170506144649)
    >> Next Version:                                       Already at latest version
    >> Latest Version:                                     2017-05-06 14:46:49 (20170506144649)
    >> Executed Migrations:                                81
    >> Executed Unavailable Migrations:                    4
    >> Available Migrations:                               77
    >> New Migrations:                                     0`

**Comment by soundgraphs** [comment]
Hi - This is the error i'm seeing in logs:

[2017-05-29 13:20:19] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DISTINCT l.hiturl FROM leads l WHERE (l.hiturl <> '') AND (l.hiturl IS NOT NULL) ORDER BY l.hiturl ASC LIMIT 10 OFFSET 0':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list'" at /var/www/vhosts/**SERVER/URL**/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DISTINCT l.hiturl FROM leads l WHERE (l.hiturl <> '') AND (l.hiturl IS NOT NULL) ORDER BY l.hiturl ASC LIMIT 10 OFFSET 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/vhosts/*SERVER/URL**/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/vhosts/*SERVER/URL**/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.hiturl' in 'field list' at /var/www/vhosts/*SERVER/URL**/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []

**Comment by MxyzptlkFishStix** [comment]
@Arjoni

Do you have something similar to this in the lead_lists table for hit_url?

`INSERT INTO `lead_lists` VALUES (1,1,'2017-05-28 16:37:10',1,'Mautic Administrator',NULL,NULL,NULL,NULL,NULL,NULL,'Test',NULL,'test','a:1:{i:0;a:7:{s:4:\"glue\";s:3:\"and\";s:5:\"field\";s:7:\"hit_url\";s:6:\"object\";s:4:\"lead\";s:4:\"type\";s:4:\"text\";s:6:\"filter\";s:22:\"https://www.google.com\";s:7:\"display\";N;s:8:\"operator\";s:1:\"=\";}}',1);`

**Comment by Arjoni** [comment]
@MxyzptlkFishStix I can't find "hit_url" at all.

**Comment by soundgraphs** [comment]
@Arjoni do you also have a 500 internal server when you check the console on the edit segment page? 
Is this where this bug can come from? 
libraries.js?ve7ac7d4f:673 GET https://crm.xxxx.xx/s/ajax?action=lead:fieldList&field=hit_url&_=1496084644996&mauticUserLastActive=2&mauticLastNotificationId= 500 (Internal Server Error)

**Comment by Arjoni** [comment]
@soundgraphs nope.

**Comment by soundgraphs** [comment]
@Arjoni @MxyzptlkFishStix well i had another install on another domain, i also updated it to 2,8,1. Segments worked like a charm on previous version, just tested it, updated it to 2,8,1. Now i have the same bug. 

Reproduce:
1. Go to 'segments'
2. Edit a segment
3. Go to filters
4. Right click + inspect + console
5. Add value to Visited URL filter, add '/' to the url
6. Console will display the 500 error
7. Value can't be passed correctly, hence sql error.

GET http://marketing.xxxxxx.xx/s/ajax?action=lead:fieldList&field=hit_url&filter…ppr.be%2F&_=1496086405816&mauticUserLastActive=1&mauticLastNotificationId= 500 (Internal Server Error)

**Comment by MxyzptlkFishStix** [comment]
# BACKUP YOUR DATABASE!

Run the following commands inside the parentheses:
Drop the Mautic migrations table (mysql **your-mautic-database** -u **mautic-mysql-user** -p -e "DROP TABLE migrations").
Run all the Mautic migrations (php app/console doctrine:migrations:migrate)
Run any schema updates (php app/console doctrine:schema:update --force)

**Comment by Arjoni** [comment]
@MxyzptlkFishStix I don't see a table named migrations on my Mautic database.

**Comment by Arjoni** [comment]
@MxyzptlkFishStix segment started working without making any change (what?!) but I run php app/console doctrine:schema:update --force just in case to fix any errors. Thank you!

**Comment by soundgraphs** [comment]
@MxyzptlkFishStix followed all suggested steps, cleared cache, still same 500 error when creating a segment with a visited url filter (other filters seem to work just fine). Any ideas/thoughts?

libraries.js?ve7ac7d4f:673 GET https://sub.domain.com/s/ajax?action=lead:fieldList&field=hit_url&_=1496124220664&mauticUserLastActive=1&mauticLastNotificationId= 500 (Internal Server Error)
send	@	libraries.js?ve7ac7d4f:673
ajax	@	libraries.js?ve7ac7d4f:649
loadPrefetch	@	libraries.js?ve7ac7d4f:4829
initialize	@	libraries.js?ve7ac7d4f:4831
initialize	@	libraries.js?ve7ac7d4f:4831
Mautic.activateTypeahead	@	app.js?ve7ac7d4f:137
Mautic.activateFieldTypeahead	@	app.js?ve7ac7d4f:99
(anonymous)	@	app.js?ve7ac7d4f:56
each	@	libraries.js?ve7ac7d4f:149
each	@	libraries.js?ve7ac7d4f:139
Mautic.onPageLoad	@	app.js?ve7ac7d4f:56
Mautic.processPageContent	@	app.js?ve7ac7d4f:56
success	@	app.js?ve7ac7d4f:40
fire	@	libraries.js?ve7ac7d4f:328
fireWith	@	libraries.js?ve7ac7d4f:333
done	@	libraries.js?ve7ac7d4f:656
(anonymous)	@	libraries.js?ve7ac7d4f:673

**Comment by npracht** [comment]
@escopecz close also ?
