### ISSUE TITLE
Email sent to contact when user is blank in "send to user" campaign form action

### ISSUE THREAD

**Issue by dawansv** [mautic/mautic#4161]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When using the "send email to user" action in a campaign form, if one leaves the user blank then the action unexpectedly send the email to the contact instead. When the user is specified then action works as expected and email is no longer sent to contact.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 5.6

### Steps to reproduce:
1. Create a test email
2. Create a campaign form with email field
3. Set action to "send email to user"; select the aforementioned email but leave user blank
4. On submitting the form, the email is sent to the contact email provided
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dawansv** [comment]
I want to add that this bug is really an hidden feature to makes up for the fact that the Send to Contact option is not available in campaign form. I have a use case where I need the email to be sent to contact from the form and not the campaign trigger, so if this bug gets fixed, it would be nice to add the Send to Contact option to campaign form actions.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
