### ISSUE TITLE
Having conditions on both sides of a campaign decision may cause the contact to follow both paths

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#4164]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✓
| Feature request? | 
| Enhancement? | 

## Description:

Having conditions on both sides of a campaign decision may cause the contact to follow both paths

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 5.6.30

### Steps to reproduce:
1. Make the following campaign ![image](https://cloud.githubusercontent.com/assets/18265735/26554118/f0309fc4-448e-11e7-9db8-fa9917138d8d.png)
2. Enter the campaign (say at 12:00)
3. Open the first email five minutes later (say at 12:05)
4. Five minutes later, you will receive the reminder email (say at 12:10)
5. Five minutes later, you will receive the thank you email (say at 12:15)
6. At this point, you are on two paths of the campaign at the same time

**Comment by MaxWebmecanik** [comment]
Hey, following up on this issue, first I'd like to report a bug that happens if your cronjobs run at a bigger interval that 10 minutes and you manage to open the first email in this campaign after the 10 minutes after receiving it, and the cronjob has not run since, you'll get a 500 with the following error message:
```
Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Proxies\__CG__\Mautic\LeadBundle\Entity\Lead with ID #2. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at .../mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Proxies\\__CG__\\Mautic\\LeadBundle\\Entity\\Lead with ID #2. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at .../mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []
```

The way we'd like to tackle this issue is create a new method independent from the rest of the campaign system that would allow to check on any event following a decision wether the other decision path has already been taken.

**Comment by Dcoutelle** [comment]
I took a look on this problem but it look like a bit complex without add a lots of database request.

When event is executed after a decision path, there is no check if the action was already triggered in an other branch of the decision path.

I think we should add this check in triggerEvent() function in EventModel arould L427.
To take this decision, we need the parent event, and all brother of this event... Xref this with eventsLog to check if a brother event had been already triggered.
We don't have all this data already loaded... it could be a heavy extra load to check this.

Why array type for event are used ? 
It could be simpler with Doctrine object without much database request

**Comment by escopecz** [comment]
Could you retest with the campaign refactoring made in 2.14.0?

**Comment by npracht** [comment]
@johbuch could you please that ?
