### ISSUE TITLE
Cannot Create Segment Filter by Multiselect Field on Lead Property

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#4165]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✔️ 
| Feature request? | ❌ 
| Enhancement? | ❌ 

## Description:
When creating a segment, if you try to build the segment by filtering on a Multiselect field, there is a JS error.

`Uncaught TypeError: Cannot use 'in' operator to search for '522' in {"\"Be Car Care Aware\" Campaign":""Be Car Care Aware" Campaign","Appearance":"Appearance","Car Care Tips":"Car Care Tips","Career Opportunities":"Career Opportunities","Check Engine Light":"Check Engine Light","Collision Repair":"Collision Repair","Crash Tests":"Crash Tests","Do It Yourself (DIY)":"Do It Yourself (DIY)","Education":"Education","Emergency Tips":"Emergency Tips","Environment":"Environment","Fall Car Care Month":"Fall Car Care Month","Fall\/Winter":"Fall\/Winter","Health":"Health","Holidays":"Holidays"}`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7.0.9

### Steps to reproduce:
1. Build a segment
2. Try to add the Multiselect field to smart filter
3. Multiselect options don't load into the UI.
![image](https://cloud.githubusercontent.com/assets/3300713/26557693/1cd2f45a-4458-11e7-8259-44e830235264.png)

 
### Log errors: 

Console error:
```
Uncaught TypeError: Cannot use 'in' operator to search for '522' in {"\"Be Car Care Aware\" Campaign":""Be Car Care Aware" Campaign","Appearance":"Appearance","Car Care Tips":"Car Care Tips","Career Opportunities":"Career Opportunities","Check Engine Light":"Check Engine Light","Collision Repair":"Collision Repair","Crash Tests":"Crash Tests","Do It Yourself (DIY)":"Do It Yourself (DIY)","Education":"Education","Emergency Tips":"Emergency Tips","Environment":"Environment","Fall Car Care Month":"Fall Car Care Month","Fall\/Winter":"Fall\/Winter","Health":"Health","Holidays":"Holidays"}
    at isArraylike (libraries.js:158)
    at Function.each (libraries.js:149)
    at Object.Mautic.addLeadListFilter (app.js:507)
    at HTMLSelectElement.<anonymous> (app.js:497)
    at HTMLSelectElement.dispatch (libraries.js:404)
    at HTMLSelectElement.elemData.handle (libraries.js:379)
    at Object.trigger (libraries.js:399)
    at HTMLSelectElement.<anonymous> (libraries.js:437)
    at Function.each (libraries.js:149)
    at jQuery.fn.init.each (libraries.js:139) 
```

**Comment by npracht** [comment]
Hi @jordan8037310 did you try to apply following PRs? https://github.com/mautic/mautic/pull/4097 https://github.com/mautic/mautic/pull/4080

**Comment by jordan8037310** [comment]
@npracht thanks for pointing these out. Those bug reports don't seem to reference my issue, which is that the Multiselect Segment Filter option completely doesn't load in the front-end.

I will try applying these anyways, and see where that gets me.

**Comment by jordan8037310** [comment]
Both #4097 and #4080 didn't fix this bug report.

**Comment by jordan8037310** [comment]
It seems that the JSON for the multiselect field is not parsed into the object for jQuery. I did not find any relevant bugs in jQuery's issue history, I looked there first because it seems like the libraries.js file is a minified version of jQuery.

I did find this issue might be relevant: https://github.com/jquery/jquery/issues/1953 which seems to imply that jQuery might not sense that the data returned is JSON if the file mimetype is not set properly.

I'll keep digging, my thought was to try upgrading the Jquery lib since the error is occurring there and it is quite an old version (2.1.1).

**Comment by jordan8037310** [comment]
We're taking on investigating / fixing this bug with a partner of ours. Consider this WIP.

**Comment by jordan8037310** [comment]
I have found the cause of this is the existed of a double quote in the name of the multi select field label. Removing it allows the segment property to work properly. Continuing with sponsoring a fix with one of our dev partners.

**Comment by jordan8037310** [comment]
Thanks @bnagaonkar, I will test this soon
