### ISSUE TITLE
Field order not respected on contacts/view page

### ISSUE THREAD

**Issue by dawansv** [mautic/mautic#4168]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When viewing a contact detail on the contacts/view page, the display order of fields seems to be by creation date and does not respect the order as set on contacts/fields page (and stored in the database in the lead_fields table, under field_order) 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 5.6

### Steps to reproduce:
1. Change order of field on contacts/fields page
2. New field order is not reflected when viewing details on contacts/view page
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by YannickBiet** [comment]
Here's the feedbacks of my Dev team 

two files/view  involved here :
- editing a contact : file /LeadBundle/Views/Lead/form.html.php form is defined to mix hardcoded fields order + a section to display custom fields (so the order defined in custom fields can't be strictly respected until Mautic really creates 100% dynamic template)
- viewing a contact : file /LeadBundle/Views/Lead/lead.html.php, a loop is including all defined fields
=> Fields are retrieved by controller LeadController (method viewAction). The method to retrieve fields is getFields. It loops unsing ID order and not the order defined in custom fields

**Comment by Baregon** [comment]
Is there a workaround for this yet?  I'd love to see my contacts in ascending order by name.

**Comment by christian-beckmann** [comment]
Would be nice if "order" will be fixed for view.

**Comment by rodrideme** [comment]
I hope version 3 comes with this feature

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Hi @dawansv @YannickBiet @Baregon @christian-beckmann @rodrideme, please hop over and test #8764 which should implement the fix for this issue!

**Comment by RCheesley** [comment]
Actually hold fire on that ... we have a new and improved PR coming soon hopefully which will supersede that one!
