### ISSUE TITLE
Lead List Filter Issue

### ISSUE THREAD

**Issue by tmorrison01** [mautic/mautic#417]
Which filter operation and value should be used to automatically add a lead to a lead list.  I am using the first name, last name and email fields.

**Comment by alanhartless** [comment]
Hi!

Do you have the currently required cronjob enabled to build the lists? Refer to https://www.mautic.org/docs/leads/manage_lists.html.

If you would, try to use Github for definite or assumed bugs but use https://www.mautic.org/community for general support requests. If you have the cronjob enabled but still not seeing the lists built properly, well then we may have a bug to look into.

Thanks!
Alan

**Comment by tmorrison01** [comment]
After viewing the documentation I did set the cronjob and everything works. With regard to the community. I'm just not finding the answers there. I will continue to give it a try. Thanks.
