### ISSUE TITLE
Outlook Plugin creates anonymous contact without emailaddress

### ISSUE THREAD

**Issue by arthurscholten** [mautic/mautic#4171]
I'm on cloud edition of Mautic (2.8.1 I guess). When i create an email in outlook2016 local install and activate tracking, I can see that a new contact is created the moment that the email is send. The tracked URL is also visible. 
Furthermore an event type "accessed from IP" is created. The IP added here is of the sender address.
An Event Timestamp is added that is the same as the timestamp of Contact created.
However the Email address is not added, thus the contact remains anonymous
Sofar I have not yet opened the email 

After opening the email from my mobile phone with wifi disabled (other IP address) i can see that an anonymous contact is created in mautic with a different IP address. A new timestamp is added. But still the emailaddress is not added to the contact. The tracked URL is:

https://business-developer.mautic.net/index.php/outlook/tracking.gif?d=H4sIAAAAAAAEAJVTS3eqMBD%2BNbiTE0h4uHBhbbmrrrq460AGSQ2EkwQ97a%2FvRCpXK721m8m8v3mlNrpd89BWjVYOuoCRcrCyA2uXAg6gdA8m7NQCWi7VtaOFznKlXVjpdmGH8hUqt3Zg3aLU4m0dxCQgjwHZfNJr8Rkcag5GQidAydc9oLgz2qu3yLbS22sDQyeUrBpoUfxjhmBLg1Ux%2BuxlJ%2FAxsONG2FFXYkIPhW4b4hkE0cOnUUGPtNfvwvDDf4rbGNcMBpUv524vjA%2Fn%2BTxezOeqNY1FqICessYPNMI3jVjEVkkcXzo%2B%2BZmOfj9vwCejWx%2FhNMbcEUCfvrT1F8oRrXGutycWJ1kcj8dwJkMp30fM%2B72LW8yX%2FVsPI%2BqZ%2FVf6XKJzp%2FZe7xvILVd4VNyMqJM004senNJ6H%2Bq6lhXQNPGn7PVHjrSaIotM0DhnqwpERnGRLC%2FzuiJJmjGe06hafb%2B0IgXKeMw4QJyxnJR5lDBaUh4TmpCERXm6ypAwmkeUMZIzfy8Tdti4dqZFvEsQg%2FJ%2FhvvPAuBkt0NOdwqr%2BO2WJ7ilrpf8dPzL6bx89C%2FP4Id0N%2B18FedMH4h5QdSpBAAA&sig=6ec5383c

**Comment by djeraseit** [comment]
Is this why the Outlook Plugin was pulled off the Mautic website?
