### ISSUE TITLE
Wild Dead contacts appeares in Segment

### ISSUE THREAD

**Issue by a1exe1** [mautic/mautic#4182]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N

## Description:
Deleted leads came to Segment

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1, 2.8.2
| PHP version | 7.0

### Steps to reproduce:
1. Some contacts process -deleting, creating, etc
2. After segmtents:update  2 leads appeares in Segment, but there is no any lead 
 
### Log errors: 

![1](https://cloud.githubusercontent.com/assets/6849980/26719531/9a3852d6-478d-11e7-8d84-f37f8b07f78e.png)
![2](https://cloud.githubusercontent.com/assets/6849980/26719536/9d882ae2-478d-11e7-927d-0131f7aa5d16.png)

**Comment by escopecz** [comment]
Please filter the anonymous contacts. It counts all contacts, but display only identified contacts by default.
![screen shot 2017-06-02 at 11 56 16](https://cloud.githubusercontent.com/assets/1235442/26721033/a403b5ce-478a-11e7-9a20-e1462f72c2ff.png)

**Comment by a1exe1** [comment]
OMG! It works. Have no Idea how they Came to me...
