### ISSUE TITLE
Validation error for multiselect field value containing quotes.

### ISSUE THREAD

**Issue by bnagaonkar** [mautic/mautic#4192]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Validation error is thrown while creating new Contact on the custom multiselect field when value containing quote is selected. For example: "sample" or ""sample""
![contact validation error](https://cloud.githubusercontent.com/assets/934486/26818755/960af798-4ab9-11e7-9c69-6ae3c4ad9482.png)
![mautic - custom muliple select button](https://cloud.githubusercontent.com/assets/934486/26818754/960b0ca6-4ab9-11e7-9c24-1be55890fa83.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.1
| PHP version | 7.0.19

### Steps to reproduce:
1.  Create Custom multiselect field with value containing quotes For, exampl;e "demo" or ""demo""
2.  Try to create new contact by selecting that quote value in multiselect field and submit contact submission form. Validation error is thrown for incorrect value.

**Comment by RCheesley** [comment]
Closing as unable to replicate in 2.15.3
