### ISSUE TITLE
custom field lost upon upgrading to latest version

### ISSUE THREAD

**Issue by yourdigitalclub** [mautic/mautic#4195]
What type of report is this: 

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | 
| Enhancement? | 

## Description:
When upgrading to the latest version of mautic I received a database update error on screen but when checking logs there were no errors in direct relation to what was on screen. When dealing with dynamic content for resource downloads the dynamic content does not load correctly within the builder, everything worked perfectly before upgrading directly from mautic. Seems as though during the process and the database error some items within the DB were lost.

Also the seems to be an issue with adding/removing tags via campaigns, after adding the action to add a tag, saving it and coming back to the campaign the action won't open and it outputs the error below

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.19

### Steps to reproduce:
1.  create custom field resourceid
2. upgraded from 2.8.0 to 2.8.2
3. create new email, add dynamic content, add variation, use resourceid as filter

 
### Log errors: 

//error for resourceid as filter
console in Chrome shows "Failed to load resource: the server responded with a status of 500 (internal server error)"

//error for adding/removing tags
"Unable to transform value for property path "[add_tags]": Tags for "Array" does not exist!"

error log from server attached

[error-log.txt](https://github.com/mautic/mautic/files/1055177/error-log.txt)

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
Closing as unable to replicate in 2.15.3
