### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by atikulhaider** [mautic/mautic#4196]
I'm trying to install Mautic v2.8.2 (Latest build) on RHEL 7, PHP 5.6.30, MariaDB and Apache with mod_rewrite enabled. But getting this error:

`RuntimeException: Unable to create the cache directory (/var/www/html/app/cache/prod)\n - in file /var/www/html/app/AppKernel.php - at line 531`

All of my folders permission set to: 755
All of my files permission set to: 644
Owner:Group = apache:apache

Please help me.

**Comment by escopecz** [comment]
It is a permission or owner issue. The community cannot do anything here since it's your server where we don't have access. Consult it with your server provider, please.

**Comment by atikulhaider** [comment]
I'm using VPS and I administer it. I have set all the permissions correctly. If you please tell me what permission to set & which folder?

**Comment by escopecz** [comment]
You can see what directory it cannot create in the error message: `/var/www/html/app/cache/prod`

**Comment by atikulhaider** [comment]
Hi,
I have tried all possible ways, chmod 777, 755, 775 to /var/www/html/app/cache directory. No luck.
Then I manually created the folder "prod" and "Unable to create the cache directory" - this error gone but new error generated "Unable to write to the cache directory".

What should I do?

**Comment by escopecz** [comment]
It's the same thing. First Mautic couldn't create the directory, now Mautic cannot create new files in that directory. You need to ask some dev ops guy to help you configure it correctly on your server.

**Comment by deivide** [comment]
Hi @atikulhaider, you resolved this?
I'm having the same problem using RHEL 7.5.

**Comment by deivide** [comment]
I solved the problem and I'll leave it here for documentation if anyone else goes through this problem. Just follow the steps of this site:  https://blog.lysender.com/2015/07/centos-7-selinux-php-apache-cannot-writeaccess-file-no-matter-what/

The following commands solved my problem:
```
sudo chcon -t httpd_sys_rw_content_t /var/www/html/mautic/app/logs -R
sudo chcon -t httpd_sys_rw_content_t /var/www/html/mautic/app/cache -R
sudo chcon -t httpd_sys_rw_content_t /var/www/html/mautic/app/config -R
