### ISSUE TITLE
[feature] integration with google spreadsheets

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#420]
We use a lot google forms to get information from costumers/partners/etc and we use the spreadsheets to integrate different services and data. I think that making push to a Google Drive spreadsheets could be easy to implement and this is the way to integrate mautic with anyother online service (Using Drive as a hub)

**Comment by zapur1** [comment]
Have a look at these two links, you can probably achieve what you want.

https://www.mautic.org/community/index.php/254-zapier-integration
https://zapier.com/zapbook/google-docs/

The Zapier app isn't on the global list yet so you will need to use this invite link https://zapier.com/developer/invite/20258/a80b6c807fc21607860af4b4283b07be/

Zac

**Comment by JoshFialkoff** [comment]
How can this be done without using Zapier?

**Comment by IADDIC** [comment]
This would be a huge benefit and a HUGE time saver
