### ISSUE TITLE
Add automatic sending date for Segment Emails

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4203]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
It would be great to be able to add an **automatic sending date** to Segment Emails. That way you can schedule your blast email from mautic.

**Comment by escopecz** [comment]
That's actually already there https://mautic.org/docs/en/setup/cron_jobs.html#send-scheduled-broadcasts-e-g-segment-emails

**Comment by npracht** [comment]
True... i missed it.
Thanks

N.
