### ISSUE TITLE
Creating/updating a contact through the API doesn't work when values contain an ampersand

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4204]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |

## Description:
Creating/updating a contact through Mautic's REST API doesn't seem to work when we send one of those values containing the ampersand. It always returns status code 400 with the error message "This value is not valid.". Removing that character (from both the field configuration as well as the API request) results in a successful request. Tested with application/x-www-form-urlencoded and application/json content types.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | MC
| PHP version | NA

### Steps to reproduce:
1. 
2.

**Comment by escopecz** [comment]
I wasn't able to get the error, but the problem I saw that the fields with `&` in it were returned as HTML encoded entity (`&#38;`) which is a bug. I made a little research around the internet and there is no point in encoding special chars when storing to database. But I cannot find a place what is doing it. Doctrine should not do it by itself.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/4361
