### ISSUE TITLE
Field 'score' doesn't have a default value - uncaught exception

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#4208]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
After updating from 2.7.1 to 2.8.1 the database update failed. Went to CLI to run upgrade script and it throws an error:

`[2017-06-02 12:52:53] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'insert into mau_companies (companyname, is_published) (SELECT DISTINCT TRIM(company), 1 from mau_leads l left join mau_companies c ON l.company = c.companyname where company IS NOT NULL and company <> '' and c.companyname is null)':  SQLSTATE[HY000]: General error: 1364 Field 'score' doesn't have a default value (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 while running console command `doctrine:migrations:migrate` [] []
`
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.7.2->2.8.1
| PHP version | 7.0.14

### Steps to reproduce:
1. Update from 2.7.1 to 2.8.1 via GUI, it failed
2. Went to CLI to run update script, following steps in John's article
3. When getting to the migration step it says there are outstanding migrations to carry out
4. When commencing the migration the error is thrown as detailed above
 
### Log errors: 

[2017-06-02 12:52:53] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'insert into mau_companies (companyname, is_published) (SELECT DISTINCT TRIM(company), 1 from mau_leads l left join mau_companies c ON l.company = c.companyname where company IS NOT NULL and company <> '' and c.companyname is null)':  SQLSTATE[HY000]: General error: 1364 Field 'score' doesn't have a default value (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 while running console command `doctrine:migrations:migrate`

**Comment by RCheesley** [comment]
Thread in Slack: https://mautic.slack.com/archives/C02GEN0SG/p1496408187795675

**Comment by escopecz** [comment]
You are right. The [score field](https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Entity/Company.php#L160) should be `->nullable()`

**Comment by RCheesley** [comment]
@escopecz is there a quick fix that could be applied in this case to allow the migrations to complete?

**Comment by escopecz** [comment]
Try to make the score column in the companies table nullable via PhpMyAdmin or something similar

**Comment by RCheesley** [comment]
OK will do, thanks!

**Comment by RCheesley** [comment]
Now getting this:

Migration 20160926182807 failed during Execution. Error An exception occurred while executing 'insert into mau_companies_leads (company_id, lead_id, date_added, manually_added, manually_removed) SELECT c.id, l.id, '2017-06-09 09:16:09', 0, 0 from mau_leads l join mau_companies c on c.companyname = l.company ON DUPLICATE KEY UPDATE company_id = c.id;':

SQLSTATE[HY000]: General error: 1364 Field 'is_primary' doesn't have a default value

**Comment by RCheesley** [comment]
When I set the is_primary field to 1 in mau_companies_leads the migration completes.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/4418

**Comment by PeterTL** [comment]
@escopecz I ran in the same error when updating from 2.8.2 to 2.10: https://www.mautic.org/community/index.php/8377-2-10-0-released/p1#p25675

Maybe this error has to be re-opened.

**Comment by escopecz** [comment]
Sadly the migration might not always run in the right order. So please run the query manually:

`ALTER TABLE [PREFIX]companies CHANGE score score INT(11) NULL`
_Replace `[PREFIX]` with the table prefix your Mautic use_

**Comment by PeterTL** [comment]
I removed the NULL constraint from the score field and configured a default value (on insert) according to fix #4418 yesterday (all before triggering the update). As described in the forum this did not work.

I restored my installation and did it again - this time manually with your SQL statement (which only removes the NULL constraint but does not add a default value. The result is the same. I found the following log messages:

```
[2017-09-12 10:33:56] doctrine.DEBUG: insert into companies_leads (company_id, lead_id, date_added, manually_added, manually_removed) SELECT c.id, l.id, '2017-09-12 10:33:56', 0, 0 from leads l join companies c on c.companyname = l.company ON DUPLICATE KEY UPDATE company_id = c.id; [] []

[2017-09-12 10:33:56] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'insert into companies_leads (company_id, lead_id, date_added, manually_added, manually_removed) SELECT c.id, l.id, '2017-09-12 10:33:56', 0, 0 from leads l join companies c on c.companyname = l.company ON DUPLICATE KEY UPDATE company_id = c.id;':
SQLSTATE[HY000]: General error: 1364 Field 'is_primary' doesn't have a default value (uncaught exception) at /.../mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 while running console command `doctrine:migrations:migrate
```

**Comment by PeterTL** [comment]
UPDATE:

I cleared the cache and the application **seems** up and running. I am able to create companies, edit and delete them. But when I try to go to a contact's details, nothing happens. The log says:

`[2017-09-12 12:56:38] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT * FROM lead_event_log lel WHERE (lel.bundle = ?) AND (lel.object = ?) AND (lel.lead_id = ?) ORDER BY lel.date_added DESC LIMIT 25' with params ["lead", "import", 2]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'data_base.lead_event_log' doesn't exist" at /.../mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 53 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM lead_event_log lel WHERE (lel.bundle = ?) AND (lel.object = ?) AND (lel.lead_id = ?) ORDER BY lel.date_added DESC LIMIT 25' with params [\"lead\", \"import\", 2]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'data_base.lead_event_log' doesn't exist at /.../mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:53, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'data_base.lead_event_log' doesn't exist at /.../mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'data_base.lead_event_log' doesn't exist at /.../mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []`

Seems like the database migration in fact was not successful.

**Comment by escopecz** [comment]
Try some tricks from https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

**Comment by PeterTL** [comment]
I did everything there (except "5. Try to update files manually"). I updated the application via GUI, via update script and via the instructions from your website. Error stays the same.

**Comment by escopecz** [comment]
How about output of `php app/console doctrine:schema:update --dump-sql`?

**Comment by PeterTL** [comment]
OK. I restored my system, removed the NULL constraint and added a default value of 0 (both in companies.score) and followed the manual update steps from your blogpost. Results (sorry in advance because of the long posting):

**1. Try to clear cache**
`[OK] Cache for the "prod" environment (debug=false) was successfully cleared.`

**2. Trigger update manually (part 1)**
```
Version 2.10.0 of Mautic is available for download. Please visit https://www.mautic.org/community/index.php/8377-2-10-0-released for more information.
To update, you can run 'php app/console mautic:update:apply' from the command line.
```

**2. Trigger update manually (part 2)**
```
Are you sure you wish to update Mautic to the latest version? yes
Step    8 [============================] Success! You are now running version 2.10.0 of Mautic.                  
An error occurred while updating the database. Check log for more details.
```

Strange that there is a positive and a negative message...

**3. Try to run database migrations (part 1)**
```
...
    >> Previous Version:                                   2016-09-26 00:00:00 (20160926000000)
    >> Current Version:                                    2016-09-26 00:00:01 (20160926000001)
    >> Next Version:                                       2016-09-26 18:28:07 (20160926182807)
    >> Latest Version:                                     2017-08-10 12:04:52 (20170810120452)
    >> Executed Migrations:                                46
    >> Executed Unavailable Migrations:                    0
    >> Available Migrations:                               90
    >> New Migrations:                                     44
```

**3. Try to run database migrations (part 2)**
```
WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y
Migrating up to 20170810120452 from 20160926000001

++ migrating 20160926182807

-> insert into companies (companyname, is_published) (SELECT DISTINCT TRIM(company), 1 from leads l left join companies c ON l.company = c.companyname where company IS NOT NULL and company <> '' and c.companyname is null)
 -> insert into companies_leads (company_id, lead_id, date_added, manually_added, manually_removed) SELECT c.id, l.id, '2017-09-12 12:08:25', 0, 0 from leads l join companies c on c.companyname = l.company ON DUPLICATE KEY UPDATE company_id = c.id;
Migration 20160926182807 failed during Execution. Error An exception occurred while executing 'insert into companies_leads (company_id, lead_id, date_added, manually_added, manually_removed) SELECT c.id, l.id, '2017-09-12 12:08:25', 0, 0 from leads l join companies c on c.companyname = l.company ON DUPLICATE KEY UPDATE company_id = c.id;':

SQLSTATE[HY000]: General error: 1364 Field 'is_primary' doesn't have a default value

[Doctrine\DBAL\Exception\DriverException] An exception occurred while executing 'insert into companies_leads (company_id, lead_id, date_added, manually_added, manually_removed) SELECT c.id, l.id, '2017-09-12 12:08:25', 0, 0 from leads l join companies c on c.companyname = l.company ON DUPLICATE KEY UPDATE company_id = c.id;': SQLSTATE[HY000]: General error: 1364 Field 'is_primary' doesn't have a default value                                                                                   
                                                                                                                                                                         
[Doctrine\DBAL\Driver\PDOException] SQLSTATE[HY000]: General error: 1364 Field 'is_primary' doesn't have a default value  
                                                                                        
[PDOException] SQLSTATE[HY000]: General error: 1364 Field 'is_primary' doesn't have a default value
```

**4. Try to update database schema (part 1)**
```
CREATE TABLE imports (id INT AUTO_INCREMENT NOT NULL, is_published TINYINT(1) NOT NULL, date_added DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', created_by INT DEFAULT NULL, created_by_user VARCHAR(255) DEFAULT NULL, date_modified DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', modified_by INT DEFAULT NULL, modified_by_user VARCHAR(255) DEFAULT NULL, checked_out DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', checked_out_by INT DEFAULT NULL, checked_out_by_user VARCHAR(255) DEFAULT NULL, dir VARCHAR(255) NOT NULL, file VARCHAR(255) NOT NULL, original_file VARCHAR(255) DEFAULT NULL, line_count INT NOT NULL, inserted_count INT NOT NULL, updated_count INT NOT NULL, ignored_count INT NOT NULL, priority INT NOT NULL, status INT NOT NULL, date_started DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', date_ended DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', object VARCHAR(255) NOT NULL, properties LONGTEXT DEFAULT NULL COMMENT '(DC2Type:json_array)', INDEX import_object (object), INDEX import_status (status), INDEX import_priority (priority), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE lead_event_log (id INT AUTO_INCREMENT NOT NULL, lead_id INT DEFAULT NULL, user_id INT DEFAULT NULL, user_name VARCHAR(255) DEFAULT NULL, bundle VARCHAR(255) DEFAULT NULL, object VARCHAR(255) DEFAULT NULL, action VARCHAR(255) DEFAULT NULL, object_id INT DEFAULT NULL, date_added DATETIME NOT NULL COMMENT '(DC2Type:datetime)', properties LONGTEXT DEFAULT NULL COMMENT '(DC2Type:json_array)', INDEX lead_id_index (lead_id), INDEX lead_object_index (object, object_id), INDEX lead_timeline_index (bundle, object, action, object_id), INDEX lead_date_added_index (date_added), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE plugin_crm_pipedrive_owners (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(255) NOT NULL, owner_id INT DEFAULT NULL, INDEX email (email), INDEX owner_id (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE lead_event_log ADD CONSTRAINT FK_753AF2E55458D FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE SET NULL;
ALTER TABLE emails ADD utm_tags LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)';
ALTER TABLE lead_fields CHANGE object object VARCHAR(255) DEFAULT NULL;
ALTER TABLE companies_leads CHANGE is_primary is_primary TINYINT(1) DEFAULT NULL;
ALTER TABLE companies CHANGE score score INT DEFAULT NULL;
ALTER TABLE push_notifications ADD utm_tags LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)';
ALTER TABLE webhook_logs ADD note VARCHAR(255) DEFAULT NULL, ADD runtime DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE webhooks ADD events_orderby_dir VARCHAR(255) DEFAULT NULL;
ALTER TABLE focus ADD utm_tags LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', ADD html_mode VARCHAR(255) DEFAULT NULL, ADD editor LONGTEXT DEFAULT NULL, ADD html LONGTEXT DEFAULT NULL;
```

**4. Try to update database schema (part 2)**
```
Updating database schema...
Database schema updated successfully! "12" queries were executed
```

**RESULT**: I am feeling like a complete idiot. I was sure that `doctrine:schema:update --dump-sql` in fact dumps the SQL code AND executes it (which it doesn't). Never mind.
