### ISSUE TITLE
Mautic trackingJS code not working

### ISSUE THREAD

**Issue by Siva-93** [mautic/mautic#4211]
What type of report is this:

| Bug report |

Description:
The contact tracking is not working as expected in mautic by using trackingJS code. I have inserted the mautic trackingJS code into my website. Also, I gave my domain name in the mautic CORS setting.

In my website whenever the user is logged into my site I want to track the user action in the mautic. So, whenever the user is logged in I get the user's email and send it to mautic using "mt('send', 'pageview', {email:loggedInEmail, firstname:loggedInName});".

But what happens is if any other is logged in, the previous user history is transferred to the current user and the previous user is getting deleted on the same browser instance.

If a bug:

Q	A
Mautic version	2.8.1
PHP version	5.6

Steps to reproduce:
1. Put trackingJS code into the website.
2. Try to send the user details on login action.
3. Let say user A logged in to the site mautic now have user A with some events
4. Now user A logs out and user B logs in from the same browser. 
5. Now the user A history is transferred to user B and user A is getting deleted.

Any idea?

**Comment by escopecz** [comment]
That is how the tracking works. Mautic doesn't expect that multiple contacts uses the same device, the same browser session. It merges them into one contact.

Please be aware that the tracking is not 100% accurate. You've described one edge scenario where Mautic cannot know if the contact uses 2 different email addresses or if there are 2 different contacts behind the same device. We have to choose one or another and right now Mautic expects 1 device = 1 contact.

**Comment by juanludlf** [comment]
Is there any workaround to solve this problem (2 users, 1 device)?
