### ISSUE TITLE
[REST API] Create asset

### ISSUE THREAD

**Issue by guillaumegarcia13** [mautic/mautic#4213]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I try to consume the API for asset creation so as to be able to send a mail with attachment.

## If a bug:
Tried multiple formats (including: multiform/data) but systematically got : 400 "File of the asset is required."

```
curl --request POST \
  --url https://mautic.company.com/api/assets/new \
  --header 'authorization: Basic xxxyyyzzzz===' \
  --header 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  --form 'title=Test GGAR' \
  --form storageLocation=local \
  --form 'file=@C:\attachment.pdf'
```

| Q   | A
| --- | ---
| Mautic version | 2.7.0
| PHP version | 5.6.29

### Steps to reproduce:
1. Cf curl
2. 
 
### Log errors: 
None

**Comment by escopecz** [comment]
Try to look around https://github.com/mautic/api-library/blob/master/lib/Auth/AbstractAuth.php#L147 if you will be able to build the CURL request from it.

**Comment by guillaumegarcia13** [comment]
Thanks for the tip.
Acutally, I simply export the request from Postman as cUrl request but I really would like to consume it from Java ultimately.

**Comment by guillaumegarcia13** [comment]
Just did the test, it works as expected with remote document, meaning that I can create an asset when storageLocation = remote with a valid remote file.

**Comment by escopecz** [comment]
Thanks for letting us know! I'll close this issue since it seem that you made it work.
