### ISSUE TITLE
Order drop-down selector shows "Contact" fields when creating Custom Field for "Company"

### ISSUE THREAD

**Issue by isleshocky77** [mautic/mautic#4216]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y

## Description:
When creating a Custom Field for the Company object the Order drop-down selector shows Contact fields.  This happens for the Creation where it doesn't know ahead of time that you'll be adding a Company Custom Field -  as well as on the Edit form when you've already saved a Custom Field for a Company

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9-dev
| PHP version | 5.6.22

### Steps to reproduce:
1. Configuration > Custom Fields > New
2. Change Object to `Company`
3. Click the `Order` drop-down
4. Click `Apply`
5. Click the `Order` drop-down

**Comment by RCheesley** [comment]
Confirm this in 2.15.3. 

From what I can understand it would be more desirable that, when a field is 'company', the order field only shows those fields which are relating to company. 

In other words, the dropdown should be filtered based on the contents of the object.

I do not believe this is a bug, but more of an enhancement, so I will remove the label accordingly.

**Comment by RCheesley** [comment]
Confirmed in Mautic 3.0.2.
