### ISSUE TITLE
Need API documentation

### ISSUE THREAD

**Issue by rwillmer** [mautic/mautic#422]
Apparently there's an API, but I don't see anywhere except in various tickets any description of how to use it

**Comment by alanhartless** [comment]
Hi,

Are you wanting to develop an addon to work from inside Mautic or integrate a 3rd party application with Mautic to create leads, etc?

We have a PHP API library at https://github.com/mautic/api-library if you want to integrate Mautic into a 3rd party application.  If the application is not PHP based, you may have to look at the source in https://github.com/mautic/api-library/tree/master/lib/Api to grab the endpoints to make requests against.  

Our developer docs are a "work in progress" and are temporarily published at https://mautic.github.io/developer-documentation. There's enough there to get started on an addon but we don't have the details on the API endpoints written yet, hence the need to look at the PHP library.

Hoping to get those dev docs wrapped up soon!

Thanks,
Alan

**Comment by rwillmer** [comment]
HI @alanhartless, great, that's just what I needed.

I want to hook my existing system up to keep track of user behaviour and leads. So I'm glad the leads are writable!

**Comment by alanhartless** [comment]
Great! If you have any problems with development, join the #dev channel in our Slack community (https://www.mautic.org/slack).
