### ISSUE TITLE
Disable trackable urls completely

### ISSUE THREAD

**Issue by ramezrafla** [mautic/mautic#4220]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
Gmail (ang GSuite) don't like redirecting urls (i.e. trackable ones). This is explicitly mentioned in the Gmail guidelines here: https://support.google.com/mail/answer/81126 under 'Format' (4th bullet).

How can we prevent trackable urls from being generated? I noticed in our tests that we get flagged as spam when we have trackable urls and goes to primary inbox when we don't. So this is a game changer (especially when you think that 1/3 of the world uses google mail one way or the other).

We don't mind contributing, but some guidance would be appreciated. Thanks

**Comment by kuzmany** [comment]
Please try test https://github.com/mautic/mautic/pull/4223/files
