### ISSUE TITLE
Error on the 2. step of installation process

### ISSUE THREAD

**Issue by skynet** [mautic/mautic#4224]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.1.4

### Steps to reproduce:
1. 
2. 
 
### Log errors: 
```
[2017-06-11 02:17:44] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Symfony\Component\HttpFoundation\Session\Flash\FlashBag::initialize() must be of the type array, object given, called in /var/www/mautic/app/cache/prod/classes.php on line 259 - in file /var/www/mautic/vendor/symfony/http-foundation/Session/Flash/FlashBag.php - at line 65 [] []
```

**Comment by escopecz** [comment]
Closing for lack of information. Please fill in at least steps to replicate so it could be replicated and fixed. Once you do so, I'll open this issue again.

**Comment by skynet** [comment]
Do you, at least, support php7? Otherwise not worth giving you what you asked for.

**Comment by skynet** [comment]
Ok, back to it, since I tried it with PHP 5.6.20 and I get exactly the same error.

Steps:

1. Download Mautic 2.8.2.zip
2. unzip 2.8.2.zip -d mautic
3. Run the installer. Step 1 - ok.
4. Step 2 - setting up the intial user returns 500.

Error in the log file is this: 
```PHP Catchable fatal error:  Argument 1 passed to Symfony\\Component\\HttpFoundation\\Session\\Flash\\FlashBag::initialize() must be of the type array, object given, called in /var/www/mautic/app/cache/prod/classes.php on line 259 and defined in /var/www/~mautic/vendor/symfony/http-foundation/Session/Flash/FlashBag.php on line 65, referer: http://mautic.example.com/index.php/installer/step/2```

**Comment by skynet** [comment]
Any luck with this? Prevents me from installing Mautic!

**Comment by escopecz** [comment]
I was able to install Mautic without any problem. It's odd that it's happening only to you. Does it happen after you fill in the database credentials? I'm not sure you take the system check as the step 1 or the database credentials as the step 1. If it is after you fill in the credentials, maybe the credentials are wrong somehow? Could you find out how so I could replicate that?

**Comment by skynet** [comment]
No, it happens after setting up the user name, at step 2. Please note that this is PHP 7. I'll try with another LAMP stack, on a different server.

**Comment by skynet** [comment]
But looking at the error, is there some indication onto which component is failing?

**Comment by escopecz** [comment]
I tested with PHP 7, but you wrote it happens on PHP 5.6 too, so I don't think that a specific PHP version is relevant to the issue. The error message doesn't say much about where the FlashBag is thrown.

**Comment by skynet** [comment]
The Mautic log is not useful at all, then. Is there a way to set the debug info to be more verbose? Thanks.

**Comment by skynet** [comment]
Same problem on a different server:
```
[2017-06-23 17:41:27] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Symfony\Component\HttpFoundation\Session\Flash\FlashBag::initialize() must be of the type array, object given, called in /var/www/mautic/app/cache/prod/classes.php on line 260 - in file /var/www/mautic/vendor/symfony/http-foundation/Session/Flash/FlashBag.php - at line 65 [] []
```
Can you please tell me what's on your Web Stack? I have nginx/1.11.8, Apache/2.4.25, PHP 7.1.6 and mysql  Ver 15.1 Distrib 10.1.24-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by skynet** [comment]
I installed a new LAMP stack and it actually worked. Now, I have to find out what's wrong with my custom-build stack. I'll post the findings in here soon. Cheers!

**Comment by skynet** [comment]
Back to my custom-built stack, getting a `AH00052: child pid 9138 exit signal Segmentation fault (11)` at `/index.php/installer/step/1.2`

**Comment by skynet** [comment]
Still working on it ...

**Comment by skynet** [comment]
Wow, after trying everything I downgraded php to 7.0.20 and ... it works. I don't think that Mautic runs with latest 7.1.6.

**Comment by escopecz** [comment]
Closing this issue as it seems you've created its successor: https://github.com/mautic/mautic/issues/4302
