### ISSUE TITLE
Add "change lead owner" to multiple contact modification

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4226]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
When you select multiple contact, it would be great to be able to modify for all at once their lead owner.
![capture d ecran 2017-06-12 a 09 13 45](https://user-images.githubusercontent.com/14075239/27022726-88d43856-4f4f-11e7-80d0-2b929b2df22b.png)

**Comment by aviboy2006** [comment]
Add me for this. I will try to do.

**Comment by aviboy2006** [comment]
I completed code for this request. Guide me how to push changes @escopecz

**Comment by escopecz** [comment]
Can you describe how much experience do you have with Git and GitHub?

**Comment by aviboy2006** [comment]
I have 7 years of git and GitHub experience. and  i have idea about branching model for environment wise. please staging etc. I just want to know about this feature request is not mine, so how to do this.

**Comment by escopecz** [comment]
Alright. It seems you know everything you need. Just create the new pull request and link this issue in the table of the pull request template.

**Comment by aviboy2006** [comment]
Mistakenly new changes for this request goes to existing open PR https://github.com/mautic/mautic/pull/4405/files. what to do ?

**Comment by escopecz** [comment]
The key is to create new branch for each feature/bug to separate the code changes.

**Comment by escopecz** [comment]
Use the staging branch to pull from the original repository only. Never push your commits directly to the staging or master branch. Always create new branch from the latest staging branch before you start working on new code.
