### ISSUE TITLE
[REST API] Create email with asset attachment

### ISSUE THREAD

**Issue by guillaumegarcia13** [mautic/mautic#4230]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
I can't find the syntax to have an attachment linked to the email when using the REST API.
When queried with GET, the assets are retrieved correctly like this:
```
"assetAttachments": [
      {
        "createdByUser": "Guillaume Garcia",
        "modifiedByUser": null,
        "id": 8,
        "title": "Livre blanc",
        "alias": "livreblanc",
        "category": {
          "createdByUser": "Cyril",
          "modifiedByUser": "Lucas",
          "id": 1,
          "title": "LB",
          "alias": "lb",
          "description": null,
          "color": "f7bb16"
        },
        "description": "livre blanc"
      }
    ],
```

I was expecting something similar when creating the email 
```
"assetAttachments": [
      {
        "id": 8,
        "title": "Livre blanc"
      }
    ],
```
but to no avail.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 5.6.29

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by migrivas** [comment]
Hi guys! Is there any update to assign the assetAttachments from the API ? :-)

**Comment by renjith341** [comment]
@guillaumegarcia13 @escopecz There is already an option to have an attachment linked to the email when using the REST API. While creating email, provide asset primary key values as array to _assetAttachments_ .

**Sample code**
```
$data = array(
   'name' => 'Email name here',
   'title' => 'Email A',
   'subject' => 'Subject here',
   'description' => 'This is my first email created via API.',
   'isPublished' => 1,
   'assetAttachments' => [1,2], //email attachment asset primary keys array
);

$email = $emailApi->create($data);
```

**Comment by renjith341** [comment]
Documentation provided for asset attachment option in create email.
[Documentation #PR](https://github.com/mautic/developer-documentation/pull/92)

**Comment by escopecz** [comment]
Amazing! Thanks!

**Comment by sourabhlk** [comment]
Hi.. Is there a way to change the name of attachment..
For ex: I am creating file using api which creates with {random id}.pdf 
But when i am sending it as attachment.. It is sent as is with the id name..
Is there a way to rename it..?
![image](https://user-images.githubusercontent.com/18000741/88659490-c391d980-d0f2-11ea-90b6-a9692b5e711b.png)
