### ISSUE TITLE
Mautic escapes contact data that when we update it over the API

### ISSUE THREAD

**Issue by wittwerch** [mautic/mautic#4234]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | no
| Enhancement? | no

## Description:
Mautic escapes contact data that when we update it over the API. 

Example:

Request
```
PATCH /api/contacts/20236/edit
{
  "cf_hotel_name": "Les Bains d'Ovronnaz"
}
```

Response:
```
...
{'id': '74', 'group': 'core', 'value': 'Les Bains d&#39;Ovronnaz', 'type': 'text', 'object': 'lead', 'alias': 'cf_hotel_name', 'field_order': '24', 'label': 'Custom Field Hotel Name'}
...
```

We later use that field in an email subject and it then displays the value escaped.

```
Your visit to Les Bains d&#39;Ovronnaz
```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0
| PHP version | PHP 7.0

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
