### ISSUE TITLE
Unable to create Segment with a filter "including" a value with "&" (ampersand)

### ISSUE THREAD

**Issue by isleshocky77** [mautic/mautic#4235]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y

## Description:

You cannot create a `Segment` composed a of a filter attempting to find `Contacts` with a field `Including` a value with a _&_ (ampersand).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9-dev
| PHP version | 5.6

### Steps to reproduce:
1. Create a custom field with choices, one with a value containing an ampersand (i.e. Bed & Breakfast)
2. Create a Segment with a filter which looks for Contacts _including_ the value "Bed & Breakfast"
3. Create a _Contact_ with this value
4. Rebuild _Segment_ and see that _Contact_ is not included

### Initial digging

It appears that the issue with this piece of code. It's cleaning the value in the filter expression which turns "&" to "`&#38;`"

```php
# app/bundles/LeadBundle/Entity/LeadListRepository.php:1387
                        case 'in':
                        case 'notIn':
                            foreach ($details['filter'] as &$value) {
                                $value = $q->expr()->literal(
                                    InputHelper::clean($value)
                                );
                            }
```

**Comment by Prodigitude** [comment]
This might be related to a similar problem that I am having where a segment will not rebuild that requires _including_ a field containing the character ")".

**Comment by isleshocky77** [comment]
Any update or movement on this bug? I currently apply the below patch; however, I don't know if it creates a security issue or has any other side effects

```patch
diff --git a/app/bundles/LeadBundle/Entity/LeadListRepository.php b/app/bundles/LeadBundle/Entity/LeadListRepository.php
index 1e8b668..840463e 100644
--- a/app/bundles/LeadBundle/Entity/LeadListRepository.php
+++ b/app/bundles/LeadBundle/Entity/LeadListRepository.php
@@ -21,7 +21,6 @@ use Mautic\CoreBundle\Doctrine\QueryFormatter\AbstractFormatter;
 use Mautic\CoreBundle\Doctrine\Type\UTCDateTimeType;
 use Mautic\CoreBundle\Entity\CommonRepository;
 use Mautic\CoreBundle\Helper\DateTimeHelper;
-use Mautic\CoreBundle\Helper\InputHelper;
 use Mautic\LeadBundle\Event\LeadListFilteringEvent;
 use Mautic\LeadBundle\Event\LeadListFiltersOperatorsEvent;
 use Mautic\LeadBundle\LeadEvents;
@@ -1667,7 +1666,7 @@ class LeadListRepository extends CommonRepository
                         case 'notIn':
                             foreach ($details['filter'] as &$value) {
                                 $value = $q->expr()->literal(
-                                    InputHelper::clean($value)
+                                    $value
                                 );
                             }
                             if ($details['type'] == 'multiselect') {
```

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
