### ISSUE TITLE
[feature] Allow plain text email to be rendered from existing html email

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#424]
It's a real pain to have to copy/paste every campaign email into the plain text field - suggest implementing a button to grab the text from the HTML email to save time.

**Comment by alanhartless** [comment]
Totally agree with this :-)

What are your thoughts on how to handle the content order? Slots aren't really stored in any particular order relying on the location in the template.  Without, forcing some sort of order configuration to the template, the best we could probably do is just insert the text content of each slot into the plain text textarea one after the other and then leave it up to the user to reorder it.
