### ISSUE TITLE
Using merge tag in subject with apostrophe is not rendering special characters correctly when emails are sent out.

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#4248]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
If a merge tag used in the subject line has merge tags, its being decoded incorrectly during sendout. 
i.e. Subject line: Welcome to {company field}
If company is called St Marry's
The email when sent is appearing as following:
Welcome to  St Mary&#39;s

## If a bug:

| Q   | A
| --- | ---
Mautic 2.8.2

### Steps to reproduce:
1. Add company mergetag in the subject email in a campaign
2. Add a contact to the company with an email that has an apostrophe (St. Marry's , George's, etc..)
3. When email is sent to user, the apostrophe is rendered incorrectly 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
