### ISSUE TITLE
Deleting variations in dynamic content by accident and saving is making the email inaccessible any more

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#4249]
What type of report is this:

| Q  | A
| Bug report? | 

## Description:
When a user deletes all the variation in the dynamic content tab in code mode by accident, and save the email, the user looses the ability to edit this email. If he press edit email, mautic loads and then nothing happens. The only way is to delete the email and create a new one and reprogram it in all the campaigns. 
The bug #4089 is also causing additional hindrance as there is no way for the user to add a variation if he deleted all variations by accident to avoid the problem. 

Expected behavior: user should not be able to delete variation. One variation should always be left as default. 

## If a bug:

| Q   | A
| --- | ---
mautic 2.8.2

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/4271
