### ISSUE TITLE
BIG BUG: Campaign emails picking up wrong data for autofill 

### ISSUE THREAD

**Issue by chizuoka** [mautic/mautic#4258]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y

## Description:
I have a custom field
listing_url

I have an auto campaign marketing email using
{listing_url}

And for example i have a user ID
1001 with listing_url: www.domain.com/url1001 
1002 with listing_url: www.domain.com/url1002 

When the email is triggered for UID 1002, the field {listing_url} is being filled with "www.domain.com/url1001" which is listing_url for the user before it!

This I believe is an extremely serious bug as I have been sending auto marketing emails with all the wrong links....

Im using mautic v2.5.1. Anyone knows why this happens and how to solve it. It isnt the first time. The same problem happens with mass one time emails using these dynamic tags too...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.5.1
| PHP version | PHP 5.6.26-1+deb.sury.org~trusty+1

### Steps to reproduce:
1. Auto email from campaign

 
### Log errors: 

No errors

**Comment by escopecz** [comment]
This has been fixed in Mautic 2.8.1. Please upgrade to the latest version before reporting a bug to make sure it hasn't been fixed already.

**Comment by escopecz** [comment]
For the reference: https://github.com/mautic/mautic/pull/4028
