### ISSUE TITLE
error 500 on Focus item

### ISSUE THREAD

**Issue by lutek** [mautic/mautic#4260]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Console and network error when saving focus item. Cant use Focus item domain/x.js JS returns also error 500 

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.8.2
| PHP version | PHP 5.6.30-0+deb8u1

### Steps to reproduce:
1. Create new focus item
2. Save
 
### Log errors: 

[2017-06-19 13:24:37] mautic.ERROR: PHP Error - Argument 1 passed to Mautic\PageBundle\Model\TrackableModel::generateTrackableUrl() must be an instance of Mautic\PageBundle\Entity\Trackable, null given, called in /srv/www/mautic/XXX/releases/20161106155210/plugins/MauticFocusBundle/Model/FocusModel.php on line 212 and defined - in file /srv/www/mautic/XXX/releases/20161106155210/app/bundles/PageBundle/Model/TrackableModel.php - at line 93 [] []

### Chrome console error:

POST http://XXXX/s/focus/edit/4?mauticUserLastActive=1&mauticLastNotificationId= 500 (Internal Server Error)
send @ libraries.js?v3a1a9b85:648
ajax @ libraries.js?v3a1a9b85:624
$.fn.ajaxSubmit @ libraries.js?v3a1a9b85:2144
Mautic.postForm @ app.js?v3a1a9b85:226
Mautic.postMauticForm @ app.js?v3a1a9b85:224
(anonymous) @ app.js?v3a1a9b85:223
dispatch @ libraries.js?v3a1a9b85:379
elemData.handle @ libraries.js?v3a1a9b85:354
trigger @ libraries.js?v3a1a9b85:377
(anonymous) @ libraries.js?v3a1a9b85:412
each @ libraries.js?v3a1a9b85:135
each @ libraries.js?v3a1a9b85:125
trigger @ libraries.js?v3a1a9b85:412
jQuery.fn.(anonymous function) @ libraries.js?v3a1a9b85:577
buttonClick @ app.js?v3a1a9b85:63
dispatch @ libraries.js?v3a1a9b85:379
elemData.handle @ libraries.js?v3a1a9b85:354

**Comment by escopecz** [comment]
I cannot replicate. Could you please describe step by step how did you configure your Focus item?

**Comment by lutek** [comment]
Found the problem, i used:
Emphasize a link / Modal and the content with link url was empty, that caused the problem.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/4900
