### ISSUE TITLE
Campaign updates crash on the first failed event to retry after 0mn

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#4262]
| Q  | A
| ---| ---
| Bug report? | ✓
| Feature request? | 
| Enhancement? | 

## Description:

![image](https://user-images.githubusercontent.com/18265735/27326845-e9dfa30c-55ac-11e7-87aa-eb1da34521b2.png)

Setting the time before retrying failed actions to "0 mn" crashes campaign updates on the first failed event to retry

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0-dev `f31a14f73`
| PHP version | 5.6.30

### Steps to reproduce:
1. Configure your instance as in the screenshot above
2. I guess you can add a row in the `campaign_lead_event_failed_log` table to fake a failed event
3. Update the campaign
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
What "crashes" means in this case? It just stops without any error message?

**Comment by MaxWebmecanik** [comment]
@escopecz Sorry, here is the message
```
$ app/console mautic:campaigns:trigger -vvv
Triggering events for campaign 1
Triggering first level events
1 total events(s) to be processed in batches of 100
 0/1 [>---------------------------]   0%
                                                             
  [Exception]                                                
  DateInterval::__construct(): Unknown or bad format (null)  
                                                             

Exception trace:
 () at /path/to/mautic/app/bundles/CampaignBundle/Model/EventModel.php:1694
 DateInterval->__construct() at /path/to/mautic/app/bundles/CampaignBundle/Model/EventModel.php:1694
 Mautic\CampaignBundle\Model\EventModel->executeEvent() at /path/to/mautic/app/bundles/CampaignBundle/Model/EventModel.php:705
 Mautic\CampaignBundle\Model\EventModel->triggerStartingEvents() at /path/to/mautic/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php:101
 Mautic\CampaignBundle\Command\TriggerCampaignCommand->execute() at /path/to/mautic/vendor/symfony/console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /path/to/mautic/vendor/symfony/console/Application.php:872
 Symfony\Component\Console\Application->doRunCommand() at /path/to/mautic/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /path/to/mautic/vendor/symfony/framework-bundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /path/to/mautic/vendor/symfony/console/Application.php:124
 Symfony\Component\Console\Application->run() at /path/to/mautic/app/console:41

mautic:campaigns:trigger [-i|--campaign-id [CAMPAIGN-ID]] [--scheduled-only] [--negative-only] [-l|--batch-limit [BATCH-LIMIT]] [-m|--max-events [MAX-EVENTS]] [-f|--force] [-t|--timeout TIMEOUT] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by HiveMindNet** [comment]
I get the same error when running a manual send on campaigns - it throws;

[Exception]
DateInterval::__construct(): Unknown or bad format (null)

I believe this only happens when sending to segments which contain contacts who have the 'Do Not Contact' flag set. I'm not sure but I reckon it happens for each do not contact contact.

**Comment by escopecz** [comment]
Is this still a problem after campaign refactoring made in 2.14.0?
