### ISSUE TITLE
Focus form submission not closing / returning user to page

### ISSUE THREAD

**Issue by david-strejc** [mautic/mautic#4263]
After successful submission of focus form and displaying right message user is not redirected back to page he was visiting. 

He needs to refresh page.

When I tried redirect URL option redirection URL is displayed only at small area of page, where user had form displayed.

Any solution?

**Comment by escopecz** [comment]
Hi David, what Mautic version are you talking about? What PHP version? Any JS or PHP errors logged anywhere? Those questions were asked in the issue template. Please fill them in next time.

**Comment by david-strejc** [comment]
Mautic version: 2.8.2

There is an error in javascript console - mautic is requesting http URL when both Mautic and my website are on https URLs.

```Blocked loading mixed active content “http://mautic.mamarketing.cz/media/js/mautic-form.js”```

I got https URL in Mautic settings.

Where is this option configured for forms?

Thank you.

**Comment by escopecz** [comment]
This should help you get going: https://mautic.com/help/forms-hanging/
