### ISSUE TITLE
Missing "No" option when configuring Twitter Plugin

### ISSUE THREAD

**Issue by rteijeiro** [mautic/mautic#4265]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When selecting "Large button" options, the "No" option is missing. See the following screenshot:

<img width="140" alt="manage_plugins___mautic" src="https://user-images.githubusercontent.com/1265384/27334925-23e75e1e-55cb-11e7-88c0-25aea39b7b30.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.9.0-dev
| PHP version | Not applicable

### Steps to reproduce:
1. Install Twitter Plugin
2. Go to "Features" tab and try to select "Large button" option

**Comment by dongilbert** [comment]
#4273 merged
