### ISSUE TITLE
Google+ Contact Mapping not saving mapped fields

### ISSUE THREAD

**Issue by itp69** [mautic/mautic#4284]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I've authorized an app to allow sign in with the Google+ plugin. After mapping the email, first name and last name fields and clicking Save & Close, the mapped fields aren't saved when I reopen the plugin and check the Contact Mapping tab.

I can't see anything in the logs and the Ajax calls as each field is mapped are returning success: 1.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0

### Steps to reproduce:
1. Open the Google+ plugin
2. Authorize the app
3. Go to Contact Mapping and map the Core Email field to the Integration Email field
4. Click the Close & Save button
5. Reopen the Google+ plugin and go to the Contact Mapping tab
6. The Mautic field for Email is empty
 
### Log errors: 

Nothing logged in Mautic log or error logs

**Comment by HiveMindNet** [comment]
I'm seeing exactly the same issue with SugarCRM integration.

**Comment by ga3003** [comment]
@itp69 Have you find any solution for this. I am also facing the same issue with google+ on mautic 2.9.2

**Comment by RCheesley** [comment]
I'm going to close this issue as it's old with no recent updates, and Google+ is deprecated for all but Enterprise users. This makes it super difficult for us to test.
