### ISSUE TITLE
Event origin and Mauticdomain not always the same if using javascript include, causing 'Please wait'

### ISSUE THREAD

**Issue by marcel-ambta** [mautic/mautic#4287]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
If using the javascript function for placing forms, the postback is not handled because there is a check if the event origin is the same as the mautic domain, which is not always the case.

mautic-form-src.js line: 623
if (event.origin !== MauticDomain) return;

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.8.2 >
| PHP version |  *

### Steps to reproduce:
1. Set-up Mautic envoirment
2. Make form, and copy javascript
3. Place form on other domain.

**Comment by escopecz** [comment]
That's why the CORS whitelist is there, isn't it? Try to put your domain there and it should work.

**Comment by marcel-ambta** [comment]
@escopecz The script is not comparing the origin with the CORS whitelist just with the MauticDomain which is always the Mautic URL. So adding it to the whitelist would not solve the issue. 

Could be a good solution for this problem though.

**Comment by jordan8037310** [comment]
Also have this issue

**Comment by mackina** [comment]
Also have this issue

**Comment by escopecz** [comment]
Isn't this issue just a misconfiguration? See https://mautic.org/docs/en/forms/index.html#form-error-messages-does-not-show-up-or-form-redirect-is-not-working

**Comment by marcel-ambta** [comment]
@jordan8037310 Your issue seems not connected with issue above, you just have to add the domain to the CORS list in the settings, but after that you will probably experience this issue. 

Case:
1. Hosting mautic on external domain (e.g. mautic.io)
2. loading form on other domain (e.g. anotherwebsite.org)

Explanation:
1. The form gets loaded and includes mautic-form-src.js
2. on submit the following code gets executed: (mautic-form-src.js line: 623)

Form.registerFormMessenger = function() {
            window.addEventListener('message', function(event) {
                if (Core.debug()) console.log(event);

                if (event.origin !== MauticDomain) return;

                try {
                    var response = JSON.parse(event.data);
                    if (response && response.formName) {
                        Core.getValidator(response.formName).parseFormResponse(response);
                    }
                } catch (err) {
                    if (Core.debug()) console.log(err);
                }
            }, false);

            if (Core.debug()) console.log('Messenger listener started.');
        };

Where mautic domain is alwast the mautic host (e.g. mautic.io), see https://github.com/mautic/mautic/blob/4497efd81b12bb665a2c907445b388ce05d6a4b2/app/bundles/DynamicContentBundle/EventListener/BuildJsSubscriber.php line 74

but event.origin is the domain the mautic form is on (e.g. anotherwebsite.org).

So the code to validate and submit the form won't be executed.

Posible solutions:
1. Remove the line, does it really add much to security since it is client side?
2. Compary event.origin with the CORS list.

@escopecz what do you think is the best solution?

**Comment by escopecz** [comment]
I don't understand why the line is there. But I did not write the code, so there may be some reasoning behind it. Could you send a pull request where the domain comparison will be removed? Lets see if it will make it through the review and test process.

**Comment by leonidr** [comment]
@escopecz , please be aware that removing this check may create issues with other embeds (like video, facebook etc.). Many of the embeds communicate with main page using post message, therefor mautic callback will start handing (and failing) messages from 3rd party embeds.
In my case ( #4588 ) I had issues with MauticDomain being a subfolder of main domain. So I solved it by substring check. Please be aware that specification of event.origin states that origin will not include subfolders - only host part. IMHO if mautic JS and the form are hosted on same domain it should work.

**Comment by escopecz** [comment]
@leonidr thanks for the info. Please comment on https://github.com/mautic/mautic/pull/4656 as that PR is suggesting to remove the line. Reviewers of the PR may overlook it here.

**Comment by escopecz** [comment]
New fix of this issue: https://github.com/mautic/mautic/issues/4287

**Comment by alanhartless** [comment]
Fixed in 2.12.2 beta
