### ISSUE TITLE
Mautic API

### ISSUE THREAD

**Issue by kg4kumargaurav** [mautic/mautic#4296]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
I have my own set of email db on my server.I want to send them a dynamic mail using mautic api.Please let me know how to do this. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Woeler** [comment]
I'm not sure what you mean, but for questions I'm sure you have more luck asking them on [Slack](https://mautic.slack.com/).
