### ISSUE TITLE
Select Field Option Errors in Lead Fields

### ISSUE THREAD

**Issue by freak3dot** [mautic/mautic#43]
___Steps to Reproduce:___
1. Login
2. Choose Leads > Manage Fields
3. Select a the new button.
4. Attempt to add a select field.

Label: Interests
Alias: interests
Data Type: Select
Default Value: [empty string]
Group: Core
Order: Website
Options: foo|bar|baz

___Actual Results:___
5. I always get the error on the options field:
"A list for the select box must be specified. Separate each option with a vertical bar. I.e. Green|Blue|Red"

___Expected Results:___
5. Select field should be created and added to lead fields.

___Additional Information___
Mautic is running on my server with latest code from last night.
Browser: Firefox.

**Comment by alanhartless** [comment]
Hey Ryan,

Give that patch a shot and let me know if it doesn't fix the issue.

Thanks!
Alan
