### ISSUE TITLE
2.8.2 eMails do not save ->.../path_mautic/app/bundles/DashboardBundle/Event/WidgetDetailEvent.php - at line 164

### ISSUE THREAD

**Issue by Gustavo-Ruiz** [mautic/mautic#4301]
| Q   | A
| --- | ---
|What type of report is this:| Bug report

## Description:
Good Day 
I cannot save emails with the new version, I am getting the error below.
I did all the recommended migrations and cleared cache

Thank you in advance

## If a bug:

| Q   | A
| --- | ---
| Mautic version| 2.8.2
| PHP version |7.0.20

### Steps to reproduce:
1. upgrade from 2.7 via command line
2. run migrations and clear cache
3. Create new email and click save
4. After clicking save, it goes back to the selection window

No emails can be saved

On the other hand I noticed this...

![mautic_2 8 2 email_error](https://user-images.githubusercontent.com/18648674/27564921-8641375e-5aa0-11e7-934c-46da4c004b7a.JPG)
 
### Log errors: 

mautic.NOTICE: PHP Notice - A non well formed numeric value encountered - in file [mautic root]/app/bundles/DashboardBundle/Event/WidgetDetailEvent.php - at line 164

**Comment by escopecz** [comment]
Your server is returning [403](https://httpstatuses.com/403). That means that your server thinks that the request is not authorised properly. The error from your logs is not related to email saving. Consult it with your server administrator, please. I'll close this issue for now, but comment on it with your findings, please. If you confirm it is a bug, I'll re-open it.

**Comment by Gustavo-Ruiz** [comment]
Thank you John! Appreciate your time.
I talked with my host (namecheap) and ends up that was the ModSecurity on the server. Long story short, rules were popping up, and after 5 iteration of whitelisting the rules, they decided to remove the Modsecurity or white list the full subdomain I am using, and after that, zero issues. However they recommended to activate it again, once all changes are made so the site remains secure.
Have a great day

**Comment by saulobr88** [comment]
Hi,
I'm install Mautic 2.8.2 with PHP 7.1.6 (From Ondrej repository), in my Dev Enviroment.
I'm getting the same error log (Apache log):
`[php7:notice] [pid 4530] [client 127.0.0.1:51920] PHP Notice:  A non well formed numeric value encountered in {Mautic Base Path }/Mautic/2.8.2/app/bundles/DashboardBundle/Event/WidgetDetailEvent.php on line 164, referer: http://{Mautic FQDN}/s/login
`
But when i use F5 (refresh) after login, the Dashboard page show normaly but the "error" log keeps. Its a frash install. I'm not using ModSecurity.

**Comment by Gustavo-Ruiz** [comment]
I got something similar when updated to the latest PHP, however I came back to 7.0 and worked fine, Try to use 7.0 using the parameters from the illustration. Hope this helps. Have a good day.


![php_7 0_conf](https://user-images.githubusercontent.com/18648674/28095765-edc38c4a-6669-11e7-96aa-eb6f206df797.JPG)
