### ISSUE TITLE
Error when save code mode without <body> tag

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4303]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Try to save an email in code mode without `<body>` tag. It generates an error --> the changes are not saved.

I think we should have an error message like "body tag is missing in your email" ?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version |

**Comment by dbhurley** [comment]
Cannot replicate in 2.12
