### ISSUE TITLE
Default dashboard can't be set

### ISSUE THREAD

**Issue by FabianTe** [mautic/mautic#4304]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I can't set my default dashboard. Every time I hit the `user` button it just reloads the dashboard selection list (see Picture below). All necessary folder permissions are set and mautic can write to them.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | PHP Version 7.0.18-0ubuntu0.16.04.1

### Steps to reproduce:
1. Install Mautic via the official downloaded package on a standard Ubuntu LAMP server
2. Log in and hit the button for setting a standard dashboard
 
### Log errors: 
**No Logs but a 302 GET Error**

![image](https://user-images.githubusercontent.com/7669818/27577034-8076c85a-5b1f-11e7-896a-12a056a98e83.png)

**Comment by skynet** [comment]
From what I noticed the dashboard selection doesn't even show up at installation. But it did for me once - when web server didn't have the permissions to write the config file. I was actually wondering how do you get to see the dashboard selection screen :-)

**Comment by FabianTe** [comment]
Well, the config folder + the contained files all belong to my apache user. File permissions are 644 for files and 755 for folders.

**Comment by escopecz** [comment]
What files are in the `media/dashboards` folder? And what permissions do they have? The output of `ls -all media/dashboards` from the Mautic root dir would be great.

**Comment by FabianTe** [comment]
They had this permission:

![image](https://user-images.githubusercontent.com/7669818/27786437-70e7af64-5fe1-11e7-9ffa-54748a4d2a9f.png)

They were owned my my admin user. I changed the owner to the apache user and the group user to my admin user, gave both `rw` privileges and the dashboard can finally be set.

Thank you!
