### ISSUE TITLE
ID of contact differs bettween form view and contacts view

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4318]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

These screenshots show the same contact viewed from the form they submitted which initially entered them into the system (kiosk mode, at event) and viwed from the contacts page. The id is different in each. 
![screenshot from 2017-06-28 13-57-10](https://user-images.githubusercontent.com/2853040/27638158-2eaf66d0-5c0a-11e7-90fa-64f93c2625d3.png)
![screenshot from 2017-06-28 13-57-02](https://user-images.githubusercontent.com/2853040/27638159-2eb1182c-5c0a-11e7-9c66-eefee203f9e0.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.8.2
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello,

This is not the ID of the contact display, but the ID on the result row of the form.

**Comment by gingerling** [comment]
In which case the tool tip on hover hovering over ID is missing - so that's translations I think? Above this tough, I think it could be a lot clearer what this id is, perhaps name it "Form entry" or something. To me ID will always mean "id of user" unless made clear otherwise :/

**Comment by escopecz** [comment]
Every entity has its own ID. If you open for example table of Landing Pages, and you see the ID column there, do you think it means ID of user too? I'll close this issue for now.

**Comment by gingerling** [comment]
Try, however, that ID is clearly about a page: both the form and user ID's are about the PERSON, multiple ID's for the same person is not something I have seen before. For example, in phpList, each click presumably has an ID of some kind but only the user ID is shown.

Asking for a clarifying tool tip on hover is not a big deal though right?

Please can you re open this and mark it for translation (or wherever hover tips are done here). It's not a big job I am sure, I can even have a go at it myself with some help :)

**Comment by escopecz** [comment]
Form submission is not equal to a contact. It doesn't have to be even related. Firemen can have form called "Help, fire!!!" with fields:

- Street
- City
- Country

They doesn't really care who reported it, but where the fire is.

Also a contact can submit the same form several times. So you'll have several IDs for one contact?

If you want to add the tooltip, please do! That would be awesome!

But I'll leave this closed because we have over 900 open issues and we have to be more strict about what is left open so devs would know what to focus on.

**Comment by gingerling** [comment]
Hi, I would like to add this tooltip myself then, I am not a developer though, can you give me a pointer. I have worked with translation systems before.

**Comment by escopecz** [comment]
Sure. The table header is here: https://github.com/mautic/mautic/blob/staging/app/bundles/FormBundle/Views/Result/list.html.php#L35
