### ISSUE TITLE
Clarification of capaign behaviour when setting campaign from results of form

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4319]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
When you  make a campaign and the source of contacts is a form, does the campaign only send to NEW submissions of the form? Or to everyone who filled out the form before hand?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Only to the new submissions.

**Comment by gingerling** [comment]
ok, thanks.

**Comment by gingerling** [comment]
When you use a segment, is it similar - so those newly added to the segment get the mail? I am trying to understand if, when I have issues sending emails from campaigns, it's actually me not understanding the way campaign sources work. I notice a lot of people saying "It's not sending" when it could actually be caused by confusions about the source.

**Comment by escopecz** [comment]
When the campaign source is a segment, it will take all contacts in that segment when you publish the campaign and process them through the campaign actions. Any new contact added to that source segment will immediately start the campaign actions too.

**Comment by gingerling** [comment]
Ok, so we unpuiblish the campaign to stop that happening right? It's all starting to make sense... :)
