### ISSUE TITLE
publicly updatable in custom fileds is not saved

### ISSUE THREAD

**Issue by bzctoons** [mautic/mautic#4321]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
In custom fields, when we set the publicly updatable option, it's not saved 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.9.0-dev
| PHP version | PHP 5.6.30

### Steps to reproduce:
1. config / custom fields
2. check publicly updatable
2. save and close => the little earth orange icon is here
2. refresh, the icon is missing and the flag is not set in the db
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
It's fixed by https://github.com/mautic/mautic/pull/4273

**Comment by dongilbert** [comment]
#4273 merged
