### ISSUE TITLE
Bug contacts Preferences

### ISSUE THREAD

**Issue by slaidel** [mautic/mautic#4322]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
On the contact view page
https://[mautic]/s/contacts/view/IDCONTACT

When you click the arrow to view contact preferences, the page loses its settings and you can not edit the information
https://[mautic]/s/contacts/contactFrequency/IDCONTACT

## If a bug:
Yes

| Q   | A
| --- | ---
| Mautic version | v2.8.2
| PHP version | 7.0.16-1

### Steps to reproduce:
Apple Macbook MacOSX 10.12.5
Bug in Google Chrome 59.0.3071.115 64 bits 

On the contact view page
https://[mautic]/s/contacts/view/IDCONTACT

When you click the arrow to view contact preferences, the page loses its settings and you can not edit the information
https://[mautic]/s/contacts/contactFrequency/IDCONTACT

**Comment by escopecz** [comment]
Could you please make a screenshot of what "the page loses its settings" looks like? I don't see any problem following the steps.

**Comment by slaidel** [comment]
![captura de tela 2017-07-03 as 11 07 27](https://user-images.githubusercontent.com/25859024/27796482-8445ff12-5fe0-11e7-94c5-eb4cb3b7651f.jpg)

@escopecz

**Comment by escopecz** [comment]
Thanks! No idea what could cause it though. Do you have any errors [in the logs](https://mautic.org/docs/en/tips/troubleshooting.html) or some JS error in the console when you open the Chrome dev tools?

**Comment by slaidel** [comment]
<img width="1440" alt="captura de tela 2017-08-02 as 12 08 10" src="https://user-images.githubusercontent.com/25859024/28880455-78c4a078-777b-11e7-81e4-def1dd7abdbb.png">

**Comment by slaidel** [comment]
Neither are the dashboard widgets appearing. (chrome , FF )
Only works with Safari

**Comment by escopecz** [comment]
My guess is cloudflare. Try to disable it somehow.

**Comment by slaidel** [comment]
Perfect . Tnks
