### ISSUE TITLE
[bug] Send Email does not alert when no list linked

### ISSUE THREAD

**Issue by nuttalla** [mautic/mautic#433]
When clicking on the SEND button on the Email I get the popup to say how many emails in the batch (default 100), and then I get the confirm box.

However, if there is no list attached to the email then clicking on SEND has no action - and no alert.

Eventually you choose the CANCEL option, but you don't know if any action has been taken.

It would be useful to get an alert instead of the SEND/CANCEL to advise there there is no list to send to.

**Comment by alanhartless** [comment]
Hey Adrian!

Congrats on the first bug report!  However, since this is related to a PR (see #429), let's keep the conversation in the PR thread until merged into the release. :-)

I'll copy it over for you.
