### ISSUE TITLE
Insert contact's select list's Label into Email

### ISSUE THREAD

**Issue by FabianTe** [mautic/mautic#4330]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description
I added a custom select field to my mautic contacts. The select's values differ from it's labels. Currently, when inserting said contact field via `{contactfield=myselectfield}` the fields value will be inserted into the mail, not the Label.

**Comment by escopecz** [comment]
Thanks for pointing that out! It's related to https://github.com/mautic/mautic/issues/3664

**Comment by FabianTe** [comment]
Just for clarity's sake: The commit and PR above didn't solve the problem and it's still an issue.

**Comment by hacker-cracker** [comment]
I'm also experiencing this bug in version v2.11.0

**Comment by npracht** [comment]
Is https://github.com/mautic/mautic/pull/8159 fixing the issue @FabianTe ?

**Comment by RCheesley** [comment]
Closing issue due to lack of recent feedback

**Comment by outrank-james** [comment]
Seems that this issue is still here - using Label > Value and putting the {contactfield=myselectfield} into an email, the actual value is returned and not the label. 

Propose something along the lines of {contactfield=myselectfield|label} which would output the label?
