### ISSUE TITLE
Different Sender Emails for each User | Feature request? | 

### ISSUE THREAD

**Issue by Schokolader** [mautic/mautic#4331]
| Feature request? | 

## Description:
It would be awesome to have different sender domains for each user.

Example: 
User 1  sends emails from email@abc.com domain 
User 2 sends emails from email@web.com domain
User 3 sends emails from email@mydomain.com

For that using only one mautic installation. Currently I'm only able to add only one email domain in the email configuration.

**Comment by Prodigitude** [comment]
You can put any domain you want to a user and the advanced tab allows for additional options. The configuration is for the system. You can't just randomly send emails from any domain that you want without setting up DNS records for every domain unless you want the domain of your mautic installation immediately blacklisted. Every domain needs to be validated that you can send mail on its behalf. Best to do this by relay to a mail service.
