### ISSUE TITLE
[feature] Be able to manually resend an individual email

### ISSUE THREAD

**Issue by nuttalla** [mautic/mautic#434]
Sometimes it will be useful to be able to resend an email...

For example, If 
- I have made a mistake in a campaign and I need to resend emails to get people back on track
- If I have changed the tracking pixel URL - ooops!
- If the email got bounced by an out of office - or mailbox exceeded quota message (when bounced messages are handled in Mautic... hint...hint...)

On the Lead, by navigating to the action in the history would be a good place to have the option to resend the email... or indeed "redo" any of the options.

**Comment by npracht** [comment]
Hello, you can do it by going on the contact detail page > top right menu > send message.
@escopecz i guess you can close that issue :)
