### ISSUE TITLE
Direct webhooks from campaigns

### ISSUE THREAD

**Issue by charirixenstrix** [mautic/mautic#4346]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
It would be useful if you could put webhooks into campaigns. 

For example if you would like to give personal timed discounts for your users. You could send the information to your webshop when mautic sends the first email to the user and you could ask your webshop to stop the discount within 1 day after the last letter. Or change the discount from 20% to 30% after the 3. email if mautic sees, that the user was intrested, but still not bought anything.

Another example is that if you sell online courses than give temporal permissions to the content of your material during a campaign so the user can try out your product.

Now you can do that trough the general webhook for contact update. But that can fires a lot for other reasons. I think it would be lot better with direct webhooks from the campaigns with just the required informations sent. And you also could separate the webhooks which calls your webshop or your LMS (or any other system you use).

**Comment by escopecz** [comment]
It's a good idea, but I think it's similar to https://github.com/mautic/mautic/issues/854, so closing this as a duplicate.
