### ISSUE TITLE
Webhooks with query parameters cause JSON data to be resubmitted

### ISSUE THREAD

**Issue by EdwinAldridgeAxolDev** [mautic/mautic#4347]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Using a query parameter in the webhook POST url causes the JSON sent to be a compilation of previous JSON requests. This also happens if the triggering action (e.g. form submit) has another webhook for a different URL which does have query parameters.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 5.6.30

### Steps to reproduce:
1. Create a webhook to a URL with a query parameter (RequestBin works fine for this) with a trigger.
2. Trigger the action to send the webhook sent
3. Trigger another webhook request

**Comment by Clement134** [comment]
Hi, @EdwinAldridgeAxolDev do you still have this issue?

I have tested with the latest version (2.15.0) and I have no problem with query parameters on webhooks whether I use immediate processing or not.

**Comment by EdwinAldridgeAxolDev** [comment]
I can't say for certain, since I found a workaround to resolve my immediate needs, and have not needed to modify the Mautic installation beyond updates since then. It might be a version-specific issue, in which case it's probably unimportant.
