### ISSUE TITLE
Error 500 upon Form Submission

### ISSUE THREAD

**Issue by FabianTe** [mautic/mautic#4349]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I always get an error 500 page when I submit a mautic form for the first time. When i revert to the form page and submit the form again, no error is shown and the redirect page appears. **The form is submitted and the campaign it is part of works flawlessly**.

This issue might be relevent to look at, but the logs are slightly different! So please be aware that this might be a different matter.

#2664:
```A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead```

vs this issue:
```A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead```

### Campaign A
![image](https://user-images.githubusercontent.com/7669818/27868596-8b7cb80c-619d-11e7-89ad-95c591f4e6af.png)
### Campaign B
![image](https://user-images.githubusercontent.com/7669818/27868598-8d490ff0-619d-11e7-965d-234d35b4ee29.png)

The two campaigns are split so that users, who have not received the initial mail linking to the form would also run through the whole campaign.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.18-0ubuntu0.16.04.1

### Steps to reproduce:
0. **This form is part of a landing page, which the user accesses via a link in a mail he receives as first action of a campaign.**
1. Create a form with a mandatory mail field, bound to the contacts mail.
2. Add a text field bound to the contact's company.
3. Submit the form once.

Now you will receive a 500 error page.

4. Remove the company field

The form still returns a 500 error page.
 
### Log error: 

mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "**A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #18809. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}).**" at /var/www/html/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #18809. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /var/www/html/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []

Edit: Added scenario screenshots

**Comment by FabianTe** [comment]
Small update:
I did following tests with 5 collegues. Each form contained a mail field bount to the contact's mail:

| Test                                                                                     | Result         |
|------------------------------------------------------------------------------|----------------|
| Form with no company field                                                   | Ok             |
| Form with a field labeled "company" but not bound to contact's company field | Ok             |
| Form with a field labeled "company" bound to contac'ts company field         | Everyone got the Error 500 page + The same log error |

I created a new form, never added a text field bound to the contacts company field. Instead I created a custom field "company-custom" and bound a form text field to it. Now I still get the error with the same log message.

I am starting to wonder if this has something to do with
1. My Campaign
2. Me clearing the mysql tables manually for testing:
```mysql
DELETE FROM campaign_leads;
DELETE FROM companies_leads;
DELETE FROM email_stats;
DELETE FROM email_copies;
DELETE FROM email_stats_devices;
DELETE FROM campaign_lead_event_log;
DELETE FROM campaign_lead_event_failed_log;
# Clear form results
DELETE FROM form_results_ ...
DELETE FROM form_submissions;
DELETE FROM lead_companies_change_log;
DELETE FROM lead_devices;
DELETE FROM lead_ips_xref;
DELETE FROM lead_lists_leads;
DELETE FROM lead_points_change_log;
DELETE FROM lead_stages_change_log;
DELETE FROM lead_tags_xref;
DELETE FROM leads;
DELETE FROM point_lead_action_log;
DELETE FROM point_lead_event_log;
DELETE FROM stage_lead_action_log;
DELETE FROM page_hits;
DELETE FROM page_redirects;
DELETE FROM companies;
UPDATE emails
SET
	read_count = 0,
	sent_count = 0;
```

**Comment by fernandolcardoso** [comment]
Same here: mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /.../vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\FormBundle\\Entity\\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /.../vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []

**Comment by escopecz** [comment]
This happens only when submitting a form when logged in to Mautic at the same time. Fixed in https://github.com/mautic/mautic/pull/4415#pullrequestreview-50275479

**Comment by stephenvoisey** [comment]
Hi @escopecz I'm getting this same error sadly.

I've tried logging out and different browsers, sadly to no avail.

A normal form works fine on submit, but the campaign form ends up with a 500 error from my implementation or a please wait that does nothing more on the native published address.

Interestingly, the email's in the campaign work and are sent—the logic part works—it just doesn't end well! :-|

Any help much appreciated.

Version 2.12.1

Error log:

```[2018-01-24 14:38:58] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #360. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /srv/users/serverpilot/apps/marketing/public/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #360. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /srv/users/serverpilot/apps/marketing/public/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []```

**Comment by escopecz** [comment]
Hi, please create a new issue and describe there steps to recreate. Link this issue there too.
