### ISSUE TITLE
ServiceNotFoundException - The service "mautic.dynamiccontent.subscriber" has a dependency on a non-existent service "mautic.focus.helper.token"

### ISSUE THREAD

**Issue by juangarias** [mautic/mautic#4351]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When I try to run segments:update via command line I get:

 [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                              
  The service "mautic.dynamiccontent.subscriber" has a dependency on a non-existent service "mautic.focus.helper.token". 

I deleted every folder in vendor/ folder and run composer update with the composer.json downloaded for Mautic specific version and I get the same error. Below is the full error message.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 5.6.24-1+deb.sury.org~wily+1

### Steps to reproduce:
1. Run composer update or composer install or php app/console mautic:segments:update
 
### Log errors: 

```
root@XXXX /var/www/mautic # composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)                   
  - Removing symfony/var-dumper (v3.2.4)
  - Removing phpunit/dbunit (2.0.3)
  - Removing symfony/cache (v3.2.10)
  - Removing psr/cache (1.0.1)
  - Removing egeloen/ordered-form-bundle (3.0.0)
  - Removing egeloen/ordered-form (3.0.0)
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Writing lock file
Generating autoload files

  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                              
  The service "mautic.dynamiccontent.subscriber" has a dependency on a non-existent service "mautic.focus.helper.token".  

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

  [RuntimeException]                                                                                                          
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                   

    [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                
    The service "mautic.dynamiccontent.subscriber" has a dependency on a non-existent service "mautic.focus.helper.token".    
 
update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--] [<packages>]...
```

**Comment by cklingsporn** [comment]
What happens when you rename(or delete) `app/cache/prod` and try again?

**Comment by juangarias** [comment]
Nothing changes, it throws the same Exception.

Thanks for the quick answer!

**Comment by escopecz** [comment]
1. Never use `composer update`, always use `composer install`.
2. Reporting a potential bug on old Mautic version as 2.5.1 doesn't make much sense. The bug could be changed in the meantime.
3. It does looks like a cache issue. But if clearing the cache by deleting the files doesn't work, then I'm out of ideas.

Try to upgrade to the latest version and see if it solves it. I'll close this issue, but please give use update on how it went.
