### ISSUE TITLE
Organizational features - folders and colour coding

### ISSUE THREAD

**Issue by benmautic** [mautic/mautic#4353]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
A few people have mentioned the need for a tag manager but further to this Mautic is in huge need of organizational features. The more I use Mautic, the more cluttered it gets.

It really needs the ability to organize things like campaigns and segments into folders with descriptions just like the campaign/segment/email itself.

With tags it would need to be a little different and this is where being able to break tags into sections where they are all displayed on the contact's page is useful. Colour coding and sectioning of tags with a label per section would be great.

Without this feature things can get pretty messy the more you make of Mautic.

**Comment by FabianTe** [comment]
I strongly argee with this. Mautic becomes really hard to organize.
The category system helps, but it can't keep up with the amount of content.

I'd suggestion the feature of grouping the mautic elements in the backend as a first, quick enhancement.

**Comment by ronnieduke** [comment]
@benmautic This is what I was trying to describe in my FR #2579 a while back...It was eventually closed in favor of global categories :-(

**Comment by escopecz** [comment]
The project proposal is getting its own pull request. Follow it for discussions and testing as it comes together: https://github.com/mautic/mautic/pull/15002
