### ISSUE TITLE
Campaign Events triggered before bounce or DNC still try to send

### ISSUE THREAD

**Issue by maxSupermoney** [mautic/mautic#4356]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
If a campaign email send event is triggered but not executed yet, and the email bounces or the contact sets the do not contact flag before the event is executed, the campaign attempts to execute but fails. It will re-attempt to execute the event during every cron job and the notification panel fills with failures for the same event.

If an event is executed against a bounced or DNC contact, that contact's event should be canceled rather than re-attempted. The is_scheduled flag in the campaign_lead_event_log table stays set to 1. I have to manually set it to 0 to stop execution.

I figured out that I can add filters to the segment to exclude bounces and unsubscribes, but this behavior should be implicit.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.16

### Steps to reproduce:
1. Create a campaign that sends an email to a new lead, waits a day, then sends another email.
2. Create a contact with a bad email and add it to the segment for the campaign created in step 1
3. When the first email is sent, the contact should be marked as a bounce
4. The 2nd email for the campaign in step 1 will be sent the next day, but it will fail due to the bounced contact, but but remain in the event queue. The event will be attempted during every campaign cron job and each failure will show up as a notification.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by calevans** [comment]
I had this same problem.  I marked a test contact DNC and every day I had new failures. It looks like it is fixed in 2.9. I upgraded to the beta yesterday and haven't seen any since. I have not tested to see if this is the case, but it does seem to be fixed.

Cheers!
=C=

**Comment by RCheesley** [comment]
Closing as seems to suggest it was fixed in 2.9
