### ISSUE TITLE
PHP Code Inside EMail

### ISSUE THREAD

**Issue by bzctoons** [mautic/mautic#4359]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | N
| Enhancement? | Y

## Description:
I have an ecommerce website which is able to get favorites products from a customer, and I would like to sent him email from campaign with the personnalized products. Also I would like to embbed pure PHP code inseide the template ex. getFavoritesProducts({leadfield:email}).
Does someone have an idea to achive this ?
Thanks

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Build a [Mautic Plugin](https://developer.mautic.org/#plugins) which will add the new `{favoriteProducts}` token similar to [this subscriber](https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/EventListener/BuilderSubscriber.php#L245).
