### ISSUE TITLE
Possible IP ignore list or search engine list

### ISSUE THREAD

**Issue by zapur1** [mautic/mautic#436]
Just a thought, having seen an obscure location and Googling the IP. Would it possible to integrate in a list of search engine bots, so they could be ignored? The simpler version would be to just have a simple comma separated IP ignore list in the Configuration section?

Thanks,
Zac

**Comment by miguelpascual** [comment]
Related, dont save the location of lead when it use gmail to read a email 

104.197.165.184  Mountain View, California

As above when the lead as a previous correct location, overwrite it that make us lose information.

**Comment by alanhartless** [comment]
This has been implemented in 1.1.3.  Go to Configuration and under Miscellaneous Settings on the Core tab, you can now specify a list of IP addresses or ranges that should not be associated with leads.
