### ISSUE TITLE
Dynamic email renders only default content if the field contains some characters

### ISSUE THREAD

**Issue by Prodigitude** [mautic/mautic#4364]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

When putting dynamic content into an email which should change based on a field value, the email fails to render anything except the default content. My preview of the email shows {dynamiccontent="Dynamic Content 2"}.  In my situation, I used a custom field that belongs to professional and have not checked if the dynamic content will function with other field types.

## Description:
I have some emails with dynamic content based on a custom field. The content only renders default values. 
I ran "doctrine:schema:validate". I got a failure in mapping and the following errors in my terminal. 
* The association Mautic\DynamicContentBundle\Entity\DynamicContentLeadData#dynamicContent refers to the inverse side field Mautic\DynamicContentBundle\Entity\DynamicContent#id which is not defined as association.
* The association Mautic\DynamicContentBundle\Entity\DynamicContentLeadData#dynamicContent refers to the inverse side field Mautic\DynamicContentBundle\Entity\DynamicContent#id which does not exist.
* The field 'Bazinga\OAuthServerBundle\Model\RequestToken#expiresAt' uses a non-existant type 'int'.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.20

### Steps to reproduce:
1. Create a custom field with data type "Select - Multiple" in Professional group. (EDITED WITH NEW INFORMATION) The field should contain a special character to reproduce bug.
2. Create two dynamic contents, in addition to the default content, with validation for if the above field contains one of the selectors.

 
### Log errors: 

[2017-07-05 18:52:03] mautic.WARNING: Command `doctrine:schema:validate` exited with status code 1 [] []

I know the error below is not specific to the email issue as the fieldname is different from the one requested in the dynamic content. The following field in the error message below does render it's information correctly within the email. This particular error was rendered in trying to updated segments. However, I suspect that it might be a related issue and I found a [Question about Doctrine\DBAL\DBALException](https://github.com/bjyoungblood/BjyAuthorize/issues/228) with a similar error of "Column not found" and what was done to correct the validation error in mapping. 

[2017-07-05 20:50:37] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT DISTINCT l.1fbosolicitationnumber FROM leads l WHERE (l.1fbosolicitationnumber <> '') AND (l.1fbosolicitationnumber IS NOT NULL) ORDER BY l.1fbosolicitationnumber ASC LIMIT 10 OFFSET 0':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.1fbosolicitationnumber' in 'field list'" at /home/theusername/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT DISTINCT l.1fbosolicitationnumber FROM leads l WHERE (l.1fbosolicitationnumber <> '') AND (l.1fbosolicitationnumber IS NOT NULL) ORDER BY l.1fbosolicitationnumber ASC LIMIT 10 OFFSET 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.1fbosolicitationnumber' in 'field list' at /home/theusername/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.1fbosolicitationnumber' in 'field list' at /home/theusername/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.1fbosolicitationnumber' in 'field list' at /home/theusername/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []

**Comment by escopecz** [comment]
According to the error message, the leads table is missing the `1fbosolicitationnumber` column which is some custom field. Try to delete the field (it cannot store any value anyway, but make a database backup just to be safe). Does it fix the issue?

There is a known issue that can cause this if you have hundreds of custom fields. How many custom fields do you have?

**Comment by Prodigitude** [comment]
I have 76 fields total. That includes the original, the ones added for the Mautic company upgrade, and the custom. 

I can't just delete the field... It can and does contain data. As stated in my comment _above_ the error message that you are referencing, it does render its content into the email. 

The field that is causing the problem in the dynamic email content is similar to the above field in that it contains a ")" character. They both had 1) in the label field. In going over other issues, I saw a post that seemed related where the "&" character was used in the field label. I have renamed all labels to contain only numbers or letters and will test further today.

**Comment by Prodigitude** [comment]
More information. After changing the field names, I still the following mapping errors within the terminal which I have copy and pasted in full.

[theusername@secure mautic]$ php app/console doctrine:schema:validate
[Mapping]  FAIL - The entity-class 'Mautic\DynamicContentBundle\Entity\DynamicCo                           ntentLeadData' mapping is invalid:
* The association Mautic\DynamicContentBundle\Entity\DynamicContentLeadData#dyna                           micContent refers to the inverse side field Mautic\DynamicContentBundle\Entity\D                           ynamicContent#id which is not defined as association.
* The association Mautic\DynamicContentBundle\Entity\DynamicContentLeadData#dyna                           micContent refers to the inverse side field Mautic\DynamicContentBundle\Entity\D                           ynamicContent#id which does not exist.

[Mapping]  FAIL - The entity-class 'Bazinga\OAuthServerBundle\Model\RequestToken                           ' mapping is invalid:
* The field 'Bazinga\OAuthServerBundle\Model\RequestToken#expiresAt' uses a non-                           existant type 'int'.

[Mapping]  FAIL - The entity-class 'Bazinga\OAuthServerBundle\Model\AccessToken'                            mapping is invalid:
* The field 'Bazinga\OAuthServerBundle\Model\AccessToken#expiresAt' uses a non-e                           xistant type 'int'.

The new label name had successfully populated into the email builder and I had tried creating a new dynamic slot but that still only rendered the default content. I tried bazinga:oauth-server:clean and there were no items to remove.

**Comment by Prodigitude** [comment]
I can confirm, it is the special character used during the creation of the field that is the problem. Simply changing the label will not correct the issue. I had to create new fields without special characters and import the data that was in the old field. Once that was done, then the dynamic content would function again.
