### ISSUE TITLE
Report an Issue is a broken link

### ISSUE THREAD

**Issue by calevans** [mautic/mautic#4366]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When Mautic hits an error, there is a link to "Report an Issue", it goes to http://mau.tc/report-issue. This is redirected to mautic.com where there is no place to report the issue.

## If a bug:
| Q   | A
| --- | ---
| Mautic version | 2.9 BETA 
| PHP version |  7.1.6

### Steps to reproduce:
1. Do anything in Mautic that creates an error
2. Click the "Report an issue" link

**Comment by escopecz** [comment]
Fixed

**Comment by RCheesley** [comment]
This somehow got broken again so I have fixed the mau.tc link to go to a forum search filtered by support, sorted by most recent. I'm hoping this encourages people to search the forums for their error message - if there was a way to grab the latest error from the logs and dump that into the URL string even better!
