### ISSUE TITLE
Edit existing form throws an error

### ISSUE THREAD

**Issue by calevans** [mautic/mautic#4367]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When I open an existing form and then either click "Apply" or "Save and Close" I get the mautic monster telling me an error has occurred. The one change I made did save.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.BETA
| PHP version | 7.1.6

### Steps to reproduce:
1. Open an existing form 
2. Save it. 
 
### Log errors: 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.utm_tags' in 'field list' at /public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.utm_tags' in 'field list' at /public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.utm_tags' in 'field list' at /public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mqueme** [comment]
Please apply migrations. Looks like you  are missing some columns.

**Comment by escopecz** [comment]
You can read here how to do that: https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

Let us know if you got it sorted, please.

**Comment by calevans** [comment]
YUP! That solved the problem. :)

I don't know why the upgrade script did not work, but the manual update seems to have cleared that up.

Thanks! :)

Cheers!
=C=
