### ISSUE TITLE
[feature] Be able to send ADMIN emails from a campaign

### ISSUE THREAD

**Issue by nuttalla** [mautic/mautic#437]
Imagine, if you will, a campaign step that sends an email to the lead with an offer (say 20% off a certain product).  We have no way to easily track that we have sent that to some customers - therefore we would use a general discount code on our web store.
The problem with the general code is they can tell their friends and they get the discount without us getting the lead information.
We can add a discount code to the store with an email address as the limiting factor - so only that customer can use it.
So, if we can send an email in the campaign to and ADMIN (i.e. ourselves, rather than the lead) then we can do the manual work outside of Mautic to support the step in the campaign.
We could use the lead fields to advise the admin what to do...

Example EMAIL:
To ADMIN <-- [This is the key part]
"Please add 20% discount code to webstore for {leadfield=email} that expires in 5 days"

**Comment by RCheesley** [comment]
Or, it could be possible to integrate Mautic with the store you use, and have a way to insert a token which generates a code just for that user #justathought :smile:
