### ISSUE TITLE
Campaign  Screens don't show correct information

### ISSUE THREAD

**Issue by iwantaspeaker** [mautic/mautic#4374]
What type of report is this:

Bur Report

## Description:
Campaign  Screens don't show correct information. Please look at attached image below.

![screenshot 2017-07-07 12 05 26](https://user-images.githubusercontent.com/6617005/27955467-d1a71e92-630c-11e7-8d3c-2801378e016b.png)

The curve shows that 4744 Assets were downloaded, however in the decisions, and Actions area below are all showing as 0%

## If a bug:

| Mautic version | v2.8.2
| PHP version | 5.6.30

### Steps to reproduce:
1. Log into our system (let me know if you need a login)
2. Goto campaign, Campaign - 10 Top Tips - by Segment Unqualified

**Comment by npracht** [comment]
That has been fixed.
