### ISSUE TITLE
Page view history

### ISSUE THREAD

**Issue by dgram** [mautic/mautic#4375]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | n
| Feature request? | y
| Enhancement? | n

## Description:
I have an question about page hits. We plan to integrate mautic on one of our sites.
At this time we don't know which segments we have to integrate all. So we want to start collecting data of users. My question is, does mautic collect the page view history? So that we can implement Segments at a later time on the collected data? So we can later add tags based on the data to the users etc.?

regards

**Comment by escopecz** [comment]
Hi, the GitHub issues are more for reporting bugs or feature requests. Please ask in the [forum](https://www.mautic.org/community) or [Slack chat](https://www.mautic.org/slack/).
