### ISSUE TITLE
Amazon S3 Plugin poorly documented

### ISSUE THREAD

**Issue by skynet** [mautic/mautic#4376]
| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | N
| Enhancement? | Y

## Description:
There's no documentation on how to set up AWS S3 Plugin, what does it do, and how to test it.

### Steps to reproduce:
1. Create S3 Bucket and credentials
2. Go to Mautic -> Plugins -> Amazon S3

### Log

```
mautic.CRITICAL: Uncaught PHP Exception Aws\S3\Exception\NoSuchBucketException: "The specified bucket does not exist"
```

**Comment by escopecz** [comment]
Please write this issue to the documentation repository: https://github.com/mautic/documentation
