### ISSUE TITLE
Stage Info Not Returned w/ Contact Data via API

### ISSUE THREAD

**Issue by atomdmac** [mautic/mautic#4378]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | x

## Description:
Is it possible to determine which Stage a Contact is currently assigned to from the API?  The data that is returned from the GET /contacts endpoints does seem to include a "stage" field but it only contains `createdByUser` and `modifiedByUser` properties.  At first glance this appears to be a bug but if there's a different/better way to accomplish this, I'm happy to be wrong 😄 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.18-0ubuntu0.16.04.1

### Steps to reproduce:
1. Ensure that you have at least one contact added to Mautic and that they belong to a Stage.
2. Hit the GET endpoint at `https://[YOUR_MAUTIC_URL]/api/contacts/[CONTACT_ID_FROM_STEP_1]`
3. JSON is returned that contains a `stages` key but it's value contains only `createdByUser` and `modifiedByUser` properties.  I would expect it to also contain the Stage ID, Stage name, etc.
```
...
    "stage": {
      "createdByUser": "Andrew Rachunok",
      "modifiedByUser": "Andrew Rachunok"
    },
...
``` 

### Log errors: 

No errors appear to be generated.

**Comment by atomdmac** [comment]
@escopecz Is it safe to assume that there isn't another way to determine which Stage a Contact is part of from the API?

**Comment by escopecz** [comment]
It seems so based on your description. It must be implemented. No one needed it till now.

**Comment by micschk** [comment]
@escopecz current status of this **bug** (not a new feature), just positively reviewed the PR which fixes it (see PR #5216 &  Issue #5214).
Would be great if this could still be merged into 2.12 @alanhartless?

**Comment by escopecz** [comment]
@micschk 2.12.0 is closed for new PRs unless beta testing stage will produce some ugly bugs. I added the PR to 2.12.1 milestone. 

Closing this issue in favor of https://github.com/mautic/mautic/issues/5214

**Comment by micschk** [comment]
Well, it actually IS a bit of an ugly bug :)
But we'll have to manually patch 2.12 then for now.

**Comment by micschk** [comment]
Great, thanks!

Just to be sure; manually patching for now is just fine by me, my 'ugly bug' comment wasn't meant very serious (sorry if it seemed to)
