### ISSUE TITLE
Amazon S3 Plugin set region

### ISSUE THREAD

**Issue by skynet** [mautic/mautic#4379]
| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | N
| Enhancement? | Y

## Description:
There's no way to set the region. It will take US-EAST-1 by default.

**Comment by robwent** [comment]
Can this be opened again?

At the moment I can't get S3 assets to work at all and get the error:

```mautic.CRITICAL: Uncaught PHP Exception Aws\S3\Exception\PermanentRedirectException: "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint: "my-bucket.amazonaws.com"." at /path/to/mautic/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/NamespaceExceptionFactory.php line 91 {"exception":"[object] (Aws\\S3\\Exception\\PermanentRedirectException(code: 0): The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint: \"my-bucket.s3.amazonaws.com\"```

The bucket is global and there doesn't seem to be any way to create ones in different regions anymore.
