### ISSUE TITLE
Are arbitrary tokens allowed when sending email via Mautic API endpoints?

### ISSUE THREAD

**Issue by atomdmac** [mautic/mautic#4380]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x?
| Feature request? | x?
| Enhancement? | x?

## Description:
The dev docs state that the `POST /emails/ID/contact/CONTACT_ID/send` endpoint accepts a `tokens` array as part of it's payload. Initially I had thought that this meant that arbitrary token+value pairs could be used as long as they matched a token in the email template. However, after some experimentation it appears that tokens are meant to expand to data that already exists within Mautic.

The documentation in question can be found here: https://developer.mautic.org/?json#send-email-to-contact

Can anyone confirm that this is the case? If so, what is the `tokens` array for?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.18-0ubuntu0.16.04.1

### Steps to reproduce:
1. Create a new Email in Mautic and add the text {custom_token} to it.
2. Send a POST request to `/emails/ID/contact/CONTACT_ID/send` endpoint, filling in the relevant email ID and contact ID.  Include the following JSON as a payload: `{ "tokens": [ { "custom_token": "This is custom token data" } ] }`
3. Check the appropriate email inbox to see the message that has been sent.  Assuming that it was, you should see that the email content contains the text `{custom_token}` instead of the expanded value from the payload.
 
### Log errors: 

No errors are generated.

**Comment by atomdmac** [comment]
After some more experimentation, it looks like the answer to my original question is "yes, arbitrary tokens can be passed in from the API".  The trick is to provide the data in the form that Mautic expects.  Here's a form that worked for me:

```
{
  "tokens": {
  	"{custom_token}": "This is my custom token value."
  }
}
```

For me, the confusion arose from the fact that the docs state that "`tokens` is "an ***array*** of tokens".  Since PHP defines associative arrays a bit differently than JSON, the "array" that you provide must be a JSON **object**.

**Comment by micheljung** [comment]
Thanks for sharing! And make sure you post `application/json`.

**Comment by yurtesen** [comment]
I can't get this to work using Mautic 2.12.1, Is it broken?

I have a simple email with content:

> 
> {token1}
> 
> HELLO THERE!
> 
> We haven't heard from you for a while...
> 
> {unsubscribe_text} | {webview_text}

I am using following code to POST the request

```

        $ch = curl_init();
        $headers[] = 'Accept: application/json';
        $headers[] = "Content-Type: application/json";
        //Set default CURL options
        $options = array(
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_HEADER         => true
        );
        $options[CURLOPT_HTTPHEADER] = $headers;
        $options[CURLOPT_URL] = 'https://mautic.mydomain.com/api/emails/11/contact/17161/send';
        $options[CURLOPT_USERPWD] =  $mauticUser.":".$mauticPassword;
        $options[CURLOPT_HTTPAUTH] = CURLAUTH_BASIC;

        $options[CURLOPT_CUSTOMREQUEST] = "POST";
        $options[CURLOPT_POST]       = true;
        $options[CURLOPT_POSTFIELDS] = '{ "tokens": { "{token1}": "This is my custom token value." } }';
        curl_setopt_array($ch, $options);

        $output = curl_exec($ch);
        $info = curl_getinfo($ch);
        curl_close($ch);
        print($output);
        print_r($info);
```

I get response printed

> HTTP/1.1 200 OK
> Date: Fri, 23 Feb 2018 12:06:55 GMT
> Server: Apache/2.4.18 (Ubuntu)
> Vary: Authorization
> Set-Cookie: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX; path=/; HttpOnly
> Mautic-Version: 2.12.1
> Cache-Control: no-cache
> Content-Length: 23
> Content-Type: application/json
> 
> {
>     "success": true
> }
> 
> Array
> (
>     [url] => https://mautic.myserver.com/api/emails/11/contact/17161/send
>     [content_type] => application/json
>     [http_code] => 200
>     [header_size] => 301
>     [request_size] => 261
>     [filetime] => -1
>     [ssl_verify_result] => 20
>     [redirect_count] => 0
>     [total_time] => 1.317593
>     [namelookup_time] => 0.036967
>     [connect_time] => 0.089692
>     [pretransfer_time] => 0.233062
>     [size_upload] => 62
>     [size_download] => 23
>     [speed_download] => 17
>     [speed_upload] => 47
>     [download_content_length] => 23
>     [upload_content_length] => 62
>     [starttransfer_time] => 1.317497
>     [redirect_time] => 0
>     [redirect_url] => 
>     [primary_ip] => X.X.X.X
>     [certinfo] => Array
>         (
>         )
> 
>     [primary_port] => 443
>     [local_ip] => X.X.X.X
>     [local_port] => 50680
> )

**Comment by micheljung** [comment]
I'm using v2.12.1 as well. Unfortunately, I can't find anything wrong with your code but then again, I'm not a PHP developer. I suggest you try Postman, if it works you know it's because of your code.

**Comment by yurtesen** [comment]
@ micheljung actually I think I solved the issue. I was writing my token to the plaintext editor. I clicked on Builder button and wrote it in there and now it works. Of course I have no idea what is point of that plaintext editor since I just installed mautic first time even. This needs better documentation :)

**Comment by rraulinio** [comment]
@atomdmac You said - "It may also be worth mentioning that HTML tags within token values will not be interpreted by the browser. While this makes sense, I figured I'd add it here for completeness." - do you know any way at all for putting HTML content via sending email API? Check [my issue](https://github.com/mautic/mautic/issues/5933) as well, thanks!
