### ISSUE TITLE
Error in campaign about stage action generates notifications that kill user access

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4386]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When you have a campaign action to change stage of contacts and that the actioned contact has a higher stage than the action, it generates an error.
This error is included in the notification center of the user (top left).

If too many errors (that can happens quick), the UI is not working anymore for the user.
![image001](https://user-images.githubusercontent.com/14075239/28021694-09d4c6c4-6589-11e7-804b-8a247c4055d0.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version |

**Comment by dbhurley** [comment]
Is this still an issue?

**Comment by npracht** [comment]
Hey @dbhurley on our side we have manage to auto delete notifications. I didn't see any PR addressing this issue.

Try to generate a lot of notification and it should significantly slow down the interface.
