### ISSUE TITLE
Installer does not verify that there is a valid DB extension loaded

### ISSUE THREAD

**Issue by calevans** [mautic/mautic#4390]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Mautic has a great installer that not only checks for a sane kit, but gives some helpful recommendations on things to do before you install Mautic. One thing it does NOT check for is a valid DB extension.
  
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9 BETA
| PHP version | 7.1

### Steps to reproduce:
1. My full Docker file is:
```
FROM php:7.1-apache
run apt-get update && apt-get install -y libmcrypt-dev zip libicu-dev libc-client-dev libkrb5-dev && rm -r /var/lib/apt/lists/* 
run docker-php-ext-configure imap --with-kerberos --with-imap-ssl && \
   docker-php-ext-install imap mcrypt intl zip 
Expose 80
```
Save this a Dockerfile somwhere.

2: Run the Build Command:
```
$ docker build --tag php7.1_apache .
```
Run this in the directory you saved the Dockerfile or replace the . with the full path and filename of the Dockerfile

3: Check out the Mautic Repo into a new directory
4: run composer install in your new Mautic directory
5: Run this docker command in your new Mautic directory.
```
$ docker run -ti -p 80:80 -v %cd%:/var/www/html php7.1_apache
```
(All of this is on Windows 10, adjust as necessary for Linux.)

6: You should get the green "Ready to Install" and one recommendation about setting the timezone. 
7: Click "Next Step"
8: You will see a dropdown combo box for the type of DB connection but there will be nothing in it. The default for php:7.1_apache is not to have MySQLi or PDO_MuSQL installed. 

Even though Mautic's installer gave it the green light, this cannot be installed because there is no DB.

The installer should check for a DB extension before it gives the all clear.

*This is an edge case* I realize that 99.99% of all computers or installs that people will install Mautic on will have a DB. However, since the Mautic installer is so awesome, I thought I would point hut how it could be a little more awesome. :)

Cheers!
=C=

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
