### ISSUE TITLE
Removing default select field option prevents any contact import

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#4391]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✓
| Feature request? | 
| Enhancement? | 

## Description:

![Screencast](http://g.recordit.co/sUMCJGXOzK.gif)

Removing the default select option from a custom field prevents any further contact import until the option is added back

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 5.6.30

### Steps to reproduce:
1. Create a csv file containing a single email (or anything more)
2. Follow screencast

**Comment by escopecz** [comment]
Amazing bug report. Thanks!

**Comment by MaxWebmecanik** [comment]
@escopecz No problem 🙂

**Comment by npracht** [comment]
There is a message saying error when saving now. Solved.
