### ISSUE TITLE
Send email for user at points trigger and campaings builder

### ISSUE THREAD

**Issue by leonardoborlot** [mautic/mautic#4394]
What type of report is this:

| Feature request? | 

## Description:
Hi, some people like me use the points to improve the engagement of the contacts on our campaigns, but, have no way to alert the user when the contact change your stages, or receive a good number of points, or the contact cross over all campaign.
I'm was requesting the feature "send email for user" at the campaigns and the points trigger.

![send email for user](https://user-images.githubusercontent.com/20361821/28069432-d1dd230a-661f-11e7-91eb-dff730edc3be.jpg)

**Comment by npracht** [comment]
duplicate https://github.com/mautic/mautic/issues/2433

**Comment by Loanatik** [comment]
Implemented in #4254.  Ready for testing.
