### ISSUE TITLE
Is there a way to change submitted form entries?

### ISSUE THREAD

**Issue by FabianTe** [mautic/mautic#4397]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 
| Question? | X

## Description:
As the title says, is there a way to change submitted form entries.

## Example
Event register form. User A want's to register for the event and checks these checkboxes

- [ x] I want to visit in the evening
- [ x] I want to visit in the afternoon

Later he realizes that he's busy in the evening and conacts me via mail, telling me so.
Can I change his form submission somehow?
**I can't introduce a new campaign mechanic or a "Change my event registration" formular**

**Comment by escopecz** [comment]
Hi, the GitHub issues are more for reporting bugs or feature requests. Please ask in the [forum](https://www.mautic.org/community) or [Slack chat](https://www.mautic.org/slack/).

But to your question, there is no way to alter form submissions nor there should be. One reason can be that a contact can submit multiple forms. Then you'd have to edit all of them?

You should map the subscription field to a contact profile field which you can edit. This way the field will have always the latest information and you will be able to edit it.
