### ISSUE TITLE
Different number of contacts in dashboard chart opposed to contacts page

### ISSUE THREAD

**Issue by tylerfoulkes** [mautic/mautic#4399]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I have a Mautic instance setup with a relatively low amount of traffic being feed into it. I just switched to finger print based tracking. In my Dashboard under the "contacts created" chart it's saying I have 13 contacts created for July 11th. However When I go to my contacts list and toggle to anonymous I only have 7 contacts for July 11th. I don't have a form capture setup so I don't have any known contacts being created. Is there something I'm missing? 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8
| PHP version | 7

**Comment by escopecz** [comment]
Could you share a screenshot of the table and the chart? The personal information can be blurred out.

**Comment by tylerfoulkes** [comment]
![screen shot 2017-07-11 at 11 16 39 am](https://user-images.githubusercontent.com/17162752/28081065-37dfef74-662b-11e7-8a11-4375073a5d6d.png)
![screen shot 2017-07-11 at 11 16 54 am](https://user-images.githubusercontent.com/17162752/28081072-45380080-662b-11e7-8880-c0d70272ba14.png)

The data has changed since I originally posted and it seems to be incrementing correctly now:
**13 -> 16 contacts in the dashboard view**
**3 more contacts added to the contact list since 10am**

However either way there are 6 unaccounted contacts that came in today.

I switched to the mtc.js tracking script (from pixel) and turned on fingerprint method (from cookie method) early evening yesterday. Would this cause discrepancies in some way?

**Comment by escopecz** [comment]
I don't think the tracking method is somehow affecting the chart.

Could you edit the widget, let it show anonymous and the identified contact lines instead of all contacts and share that screenshot to rule out it counts identified contacts to it?

**Comment by escopecz** [comment]
Also, if you select only today in the dashboard date range filter, it will zoom show the counts per hours of the day. It could also help us explain what contacts it sees for today.

**Comment by tylerfoulkes** [comment]
![screen shot 2017-07-11 at 11 41 12 am](https://user-images.githubusercontent.com/17162752/28081913-1e59560a-662e-11e7-8eb1-67f8b29ecbc1.png)

![screen shot 2017-07-11 at 11 42 09 am](https://user-images.githubusercontent.com/17162752/28081923-24ee572c-662e-11e7-98a6-24746fe37725.png)

With the new data coming in the hourly graph is showing correct data.

**Comment by tylerfoulkes** [comment]
This also extends to the "Total visits" chart as well.

When I view by day I get 54 total visits on July 11th which is incorrect but when I switch to hourly I get 22 total visits total for July 11th which is correct.

![screen shot 2017-07-11 at 11 56 59 am](https://user-images.githubusercontent.com/17162752/28082663-55123624-6630-11e7-8657-1ef561ef1523.png)

![screen shot 2017-07-11 at 11 56 42 am](https://user-images.githubusercontent.com/17162752/28082690-686fe7de-6630-11e7-8c89-d262ff011281.png)

**Comment by tadisa** [comment]
Hello,
I am having this issue too. 

My installation is less that one month on AWS. I just install tracking on my new website two days ago. 
I don't have any contact in my contact list except for one test contact.
I haven't started any campaign whatsoever.

How come is my dashboard showing this huge amount of visits and contacts created?

Kindly see the attached image.

![Mautic Dashboard Graphs](https://user-images.githubusercontent.com/20805136/56582704-c6d51600-65cf-11e9-98c4-a1a5982869bc.png)

I will appreciate any assistance to resolve this issue.

Thank you.
Cheers.

**Comment by escopecz** [comment]
@tadisa the original issue doesn't have much common to your issue. Mautic tracks even 404 pages so there may have been some traffic to your domain/IP address and Mautic is creating anonymous contacts out of it. Above the contact list table there is a button to show anonymous contacts. Mautic shows only identified contacts by default. If you'll see the anonymous contacts then click on one to see where it's coming from to understand more what is going on.

**Comment by tadisa** [comment]
I don't know the IP addresses. 

I think Mautic started capturing traffic to my site since I installed the tracking plugin yesterday.

I haven't created any campaign yet to warrant this type of visit from the IPs below

111.231.228.207
193.243.196.133
123.206.9.252
118.24.22.186 
etc...

They are up to 20 IPs like those.

80% from china. I could traced them to their website. Mostly Chinese business websites. Their traffic behavior looks suspicious to me. 

Each one above has about 1000 visits to my AWS Mautic instance.

One of them goes to my AWS instance database index page. 

1. Should I be bothered about these visits?
2. Should I block those IPs on Mautic IP Restriction Settings?
3. Are they trying to hack my Mautic instance on AWS?

Kindly see images below.

![Anonymous Contacts](https://user-images.githubusercontent.com/20805136/56583813-54b20080-65d2-11e9-84e4-05710e1763d3.png)

![IP](https://user-images.githubusercontent.com/20805136/56585831-8036ea00-65d6-11e9-98c6-6c646f06f918.png)

![111 231 228 207 resolved image](https://user-images.githubusercontent.com/20805136/56585851-85943480-65d6-11e9-9395-51735e9717fe.png)

Thank for your help.

Cheers.

**Comment by escopecz** [comment]
It looks like it's a bot that is discovering whether you have PhpMyAdmin installed on your server. You can block IP addresses coming from China if Chinese visitors aren't your audience. It's not a Mautic issue that it's tracking page hits though.

**Comment by tadisa** [comment]
Okay.

Thanks a lot. I appreciate your time.
I will go ahead and block the Chinese IPs since they are not my target location.

Regards.
Cheers.

**Comment by tadisa** [comment]
Please, how can I reset the counters on the dashboard?

I need to clear the stats and keep track afresh.

Thanks.

**Comment by RCheesley** [comment]
Closing due to the outdated issue with no recent updates.
