### ISSUE TITLE
Push to Integration results in 500 Error

### ISSUE THREAD

**Issue by dirtroof** [mautic/mautic#4402]
# Bug report

## Description:
When using the Push to Integration feature, pushing to MailChimp, it immediately throws a 500 Error.

## If a bug:
Mautic version: 2.8.2
7.0.2.1

### Steps to reproduce:
1. Edit any stand-alone form's action
2. Add Push to Integration (in this specific case, MailChimp)
3. Immediately throws a 500 error.
 
###### Mautic Error Log:
PHP Fatal error:  require(): Failed opening required '/path/to/mautic/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:/opt/sp/php7.0/lib/php') in /path/to/mautic/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209

**Comment by escopecz** [comment]
There have been fixes in 2.9.0 in the MailChimp integration. Please test with [2.9.0-beta](https://www.mautic.org/community/index.php/7982-mautic-2-9-0-beta-released) and let us know. I'll close this issue for now.
