### ISSUE TITLE
View not updated after deleting an anonymous contact

### ISSUE THREAD

**Issue by wittwerch** [mautic/mautic#4406]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | no 
| Enhancement? | no

## Description:
When I delete an anonymous contact the view does not update. If I refresh the browser the contact is gone.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0-beta
| PHP version | 7.0

### Steps to reproduce:
1. Let Mautic create an anonymous contact
2. Navigate to /s/contacts
3. Delete the contact
4. Contact does not disappear

**Comment by escopecz** [comment]
I cannot replicate. The contact is gone when I click the delete option. Do you see some errors anywhere? Maybe a JS error when you open the dev tools console in your browser?

**Comment by wittwerch** [comment]
My mistake, I was testing on our internal version. Maybe something got missed during the merge or we need to update views we have overwritten in our bundle.
