### ISSUE TITLE
Webhook and empty values

### ISSUE THREAD

**Issue by fgauttron** [mautic/mautic#4408]
Hello,

I'm trying to get the data from a mautic form to integrate them into odoo/openerp with webhooks (i tested also with sending a email)  I tested with the webhooks of zapier and flowxo, but with each all the values ​​of the form are empty.

There is any error logs.

Mautic 2.8
PHP Version 5.6.30-0+deb8u1

**Comment by escopecz** [comment]
Please look at https://github.com/mautic/mautic/issues/2838#issuecomment-309875567

If you'll still have problem with webhooks, please share the webhook payload.
