### ISSUE TITLE
Wrong value type for regex on select fields

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#4414]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When creating a segment, you cannot add a regex value to a select field

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2 (cloud)
| PHP version | 

### Steps to reproduce:
1. Create a new segment
2. Choose a filter that is a "Select" type of field
3. Change the filter operator to "regex" or "not regex"
4. The value field is still trying to populate a whole value from the select field instead of an open text field where you can input your regex.

![image](https://user-images.githubusercontent.com/742579/28192291-fa028d0e-67e9-11e7-88cb-3cc230edf6d9.png)

**Comment by namratasaun** [comment]
is this resolved?
Having a similar issue. in number field, you can only type number
