### ISSUE TITLE
Re-subscribe url for "opt in" list cleaning emails

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4425]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | Y

## Description:
A url to "opt (back) in" would be useful: for list cleaning emails where the un-engaged contact will be marked do-not-contact but is given a chance to opt back in again, there doesn't seem to be a url to use for this situation. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
The URL is the same as the unsubscribe URL.

**Comment by gingerling** [comment]
So it works like a switch? It's not really relevant / possible to test at the moment because you can't unsubscribe someone in a campaign. The workflow would need to be 

1) send opt-back-in email with unsubscribe link
2) unsubscribe them
3) if they click the unsubscribe link they get opted back in

but step two isn't possible in a campaign

**Comment by escopecz** [comment]
Yes, it's a switch. It shows content based on contact's state.

The only option how to unsubscribe multiple contacts is to import them as unsubscribed.

**Comment by gingerling** [comment]
great! Thats really good info thanks, I wrote a blog about this here http://www.gingerling.co.uk/list-cleaning-in-mautic/ :)
