### ISSUE TITLE
Tracking Code Injecting Video JS/CSS that Breaks UI Design

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#4431]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
After updating to 2.9.0, I noticed that our web site had some major visual glitches. We have HTML5 video elements that are used as backgrounds and demo videos, designed very specifically without controls shown.

Any page with the Mautic JS tracking code seems to inject unwanted CSS/JS that hijacks any video elements it can find. This completely ruins the UI, so I had to remove the tracking code altogether for now.

I believe it has something to do with this: https://github.com/mautic/mautic/pull/4134

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version | 5.6

### Steps to reproduce:
1. Update to 2.9.0.
2. Have tracking code on a page with custom HTML5 video elements.

**Comment by kuzmany** [comment]
Please test https://github.com/mautic/mautic/issues/4431 and add comments with your results there.

**Comment by nickian** [comment]
Thanks! That fix works for me.
