### ISSUE TITLE
Allow action after action in campaign

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4434]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | Y
| Enhancement? | Y

## Description:
When you make an action in a campaign, this can't currently be followed by a second action. For example, I have sorted people into three segments, cat, dog and cat and dog, but I can't continue with actions after that point, I am given only decision or condition. 

![screenshot from 2017-07-14 21-19-09](https://user-images.githubusercontent.com/2853040/28229331-35f0a4ea-68da-11e7-8a4a-ece03a82b638.png)

Seems like the only option is to start a new campaign for each segment right now.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by JohnConnell** [comment]
Just add the additional actions the same way you add the first action.
Using your example screenshot, click the green circle beneath the
conditions again to add the additional actions.

**Comment by gingerling** [comment]
Ah, so it's the node above rather than the node below? Interesting. So, in this instance I add the contacts to a segment, and then want to send a campaign to that segment. I would, I suppose need to add a delay into the send an email to the segment part? Because if they are off the same node but set to "immediately" and my send email cron runs before my adjust segment cron, they would miss the email? Or would the email send to every new person added to the segment as they are added (next time the send email cron runs)?

**Comment by JohnConnell** [comment]
I set delays between all email actions tied to the same decision/condition
personally. A really simple 30-day email sequence of mine looks like this:


​


I'm not totally clear on your use case RE: adjusting segments, but it
sounds like you would want to execute the segment change action immediately
and then the send email action after x mins (where x is equal to the timing
of your mautic:segments:update cronjob + 1 minute). The extra minute to
allow for execution time of the job. Everyone would move into the segment
and and be sent the email at the same time in that case unless the volume
of contacts exceeded your cron values.

I'd also recommend setting the email type to marketing (for most use cases)
and 'attempts' to 3 to be safe. If you're sending broadcast emails in
addition to campaign emails you might also want to set the campaign emails
to high priority as well.

​

**Comment by gingerling** [comment]
Hi, can't see the image, looks interesting though, can you add it again?
