### ISSUE TITLE
mtc.js error on IE11

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4442]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When you run a tracking script with `mtc.js` on IE 11 (about 5% of marketshare), you have an error (not existing on Chrome and Mozilla Firefox).
#### The object does not manage the property or method `setRequestHeader` in `mtc.js` (7, 327)

![image001](https://user-images.githubusercontent.com/14075239/28259294-d8adde76-6ad5-11e7-947f-d7c005815d34.jpg)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version | 
![image001 2](https://user-images.githubusercontent.com/14075239/28259286-cdc79f74-6ad5-11e7-9dfa-48883d9131ed.png)

**Comment by merlin0** [comment]
In IE there is also a problem with loading in the script, it causes a page flickering. https://github.com/mautic/mautic/issues/3000
