### ISSUE TITLE
Multiple choice custom field filter is not working properly in Segment creation

### ISSUE THREAD

**Issue by aviboy2006** [mautic/mautic#4444]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
While segment creation using filter - there option for custom field which is having multiple choice **including**.  That not working properly as per expectation.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version | 

### Steps to reproduce:
1.  Create one custom field as Source Database add there three four item ( Facebook, Twitter, JustDial, Offline)
2.  Assign some contact to source database.
3.  Create segment with filter having source database including "Facebook", "Offline" Database

My database having entry of source database like   '**facebook|offline|twitter**'  
if one record having this field value '**facebook|offline|twitter**'   and other record having '**facebook**' 
23  - segment ID 
if run sql its should return both rows i need inclusion of facebook and offline data also. But this sql will gives us only row because **AND** condition parse record only one row.

SELECT count(l.id) AS lead_count,
       max(l.id) AS max_id
FROM knableads l
LEFT JOIN knablead_lists_leads ll ON (ll.leadlist_id = 23)
AND (ll.lead_id = l.id)
AND (ll.date_added <= '2017-07-17 09:26:57')
WHERE   (l.knab_source_database REGEXP '\\|?facebook\\|?')
  AND (l.knab_source_database REGEXP '\\|?offline\\|?')  
  AND (ll.lead_id IS NULL)
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
Insufficient information to confirm whether this is still an issue, so closing this down. Feel free to re-open if it's still a problem.
