### ISSUE TITLE
Bug? Cron 500 Internal Server Error

### ISSUE THREAD

**Issue by tmorrison01** [mautic/mautic#445]
Setup cron and emails not sending campaigns not working lead list not updating. Getting the same error for the campaign and leadlist cron. Cron is sending via email the following error.

Status: 500 Internal Server Error
Cache-Control: no-cache
Date: Fri, 22 May 2015 03:30:01 GMT
Content-type: text/html

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>
            /* Copyright (c) 2010, Yahoo! Inc. All rights reserved. Code licensed under the BSD License: http://developer.yahoo.com/yui/license.html */
            html{color:#000;background:#FFF;}body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td{margin:0;padding:0;}table{border-collapse:collapse;border-spacing:0;}fieldset,img{border:0;}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal;}li{list-style:none;}caption,th{text-align:left;}h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal;}q:before,q:after{content:'';}abbr,acronym{border:0;font-variant:normal;}sup{vertical-align:text-top;}sub{vertical-align:text-bottom;}input,textarea,select{font-family:inherit;font-size:inherit;font-weight:inherit;}input,textarea,select{*font-size:100%;}legend{color:#000;}

            html { background: #eee; padding: 10px }
            img { border: 0; }
            #sf-resetcontent { width:970px; margin:0 auto; }
                        .sf-reset { font: 11px Verdana, Arial, sans-serif; color: #333 }
            .sf-reset .clear { clear:both; height:0; font-size:0; line-height:0; }
            .sf-reset .clear_fix:after { display:block; height:0; clear:both; visibility:hidden; }
            .sf-reset .clear_fix { display:inline-block; }
            .sf-reset * html .clear_fix { height:1%; }
            .sf-reset .clear_fix { display:block; }
            .sf-reset, .sf-reset .block { margin: auto }
            .sf-reset abbr { border-bottom: 1px dotted #000; cursor: help; }
            .sf-reset p { font-size:14px; line-height:20px; color:#868686; padding-bottom:20px }
            .sf-reset strong { font-weight:bold; }
            .sf-reset a { color:#6c6159; }
            .sf-reset a img { border:none; }
            .sf-reset a:hover { text-decoration:underline; }
            .sf-reset em { font-style:italic; }
            .sf-reset h1, .sf-reset h2 { font: 20px Georgia, "Times New Roman", Times, serif }
            .sf-reset h2 span { background-color: #fff; color: #333; padding: 6px; float: left; margin-right: 10px; }
            .sf-reset .traces li { font-size:12px; padding: 2px 4px; list-style-type:decimal; margin-left:20px; }
            .sf-reset .block { background-color:#FFFFFF; padding:10px 28px; margin-bottom:20px;
                -webkit-border-bottom-right-radius: 16px;
                -webkit-border-bottom-left-radius: 16px;
                -moz-border-radius-bottomright: 16px;
                -moz-border-radius-bottomleft: 16px;
                border-bottom-right-radius: 16px;
                border-bottom-left-radius: 16px;
                border-bottom:1px solid #ccc;
                border-right:1px solid #ccc;
                border-left:1px solid #ccc;
            }
            .sf-reset .block_exception { background-color:#ddd; color: #333; padding:20px;
                -webkit-border-top-left-radius: 16px;
                -webkit-border-top-right-radius: 16px;
                -moz-border-radius-topleft: 16px;
                -moz-border-radius-topright: 16px;
                border-top-left-radius: 16px;
                border-top-right-radius: 16px;
                border-top:1px solid #ccc;
                border-right:1px solid #ccc;
                border-left:1px solid #ccc;
                overflow: hidden;
                word-wrap: break-word;
            }
            .sf-reset li a { background:none; color:#868686; text-decoration:none; }
            .sf-reset li a:hover { background:none; color:#313131; text-decoration:underline; }
            .sf-reset ol { padding: 10px 0; }
            .sf-reset h1 { background-color:#FFFFFF; padding: 15px 28px; margin-bottom: 20px;
                -webkit-border-radius: 10px;
                -moz-border-radius: 10px;
                border-radius: 10px;
                border: 1px solid #ccc;
            }
        </style>
    </head>
    <body>
                    <div id="sf-resetcontent" class="sf-reset">
                <h1>Whoops, looks like something went wrong.</h1>
                                        <div class="block_exception clear_fix">
                            <h2><span>1/1</span> <abbr title="Symfony\Component\Debug\Exception\ContextErrorException">ContextErrorException</abbr>: Warning: Invalid argument supplied for foreach() in /home/sbisapps/public_html/marketing-manager/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php line 287</h2>
                        </div>
                        <div class="block">
                            <ol class="traces list_exception">
       <li> in /home/sbisapps/public_html/marketing-manager/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php line 287</li>
       <li>at <abbr title="Symfony\Component\Debug\ErrorHandler">ErrorHandler</abbr>->handle('2', 'Invalid argument supplied for foreach()', '/home/sbisapps/public_html/marketing-manager/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php', '287', <em>array</em>('values' => <em>array</em>('--ansi'))) in /home/sbisapps/public_html/marketing-manager/vendor/symfony/console/Symfony/Component/Console/Input/ArgvInput.php line 287</li>
       <li>at <abbr title="Symfony\Component\Console\Input\ArgvInput">ArgvInput</abbr>->hasParameterOption(<em>array</em>('--ansi')) in /home/sbisapps/public_html/marketing-manager/vendor/symfony/console/Symfony/Component/Console/Application.php line 838</li>
       <li>at <abbr title="Symfony\Component\Console\Application">Application</abbr>->configureIO(<em>object</em>(<abbr title="Symfony\Component\Console\Input\ArgvInput">ArgvInput</abbr>), <em>object</em>(<abbr title="Symfony\Component\Console\Output\ConsoleOutput">ConsoleOutput</abbr>)) in /home/sbisapps/public_html/marketing-manager/vendor/symfony/console/Symfony/Component/Console/Application.php line 121</li>
       <li>at <abbr title="Symfony\Component\Console\Application">Application</abbr>->run(<em>object</em>(<abbr title="Symfony\Component\Console\Input\ArgvInput">ArgvInput</abbr>)) in /home/sbisapps/public_html/marketing-manager/app/console line 28</li>
    </ol>
</div>

            </div>
    </body>
</html>

**Comment by alanhartless** [comment]
Hi!

Just recently ran across this myself.  Some hosts don't have 'register_argc_argv' on in CLI's php.ini.  If you can't edit the php.ini file to turn it on, try using `php -d register_argc_argv=On /path/to/mautic/app/console ...` Will get that into the docs.

Thanks!
Alan

**Comment by tmorrison01** [comment]
Got it. It worked. There was no need to add the additional code "register_argc_argv=On" to the path. This issue occured when using a Bluehost VPS  account.
