### ISSUE TITLE
Add support for a mobile preview when using the page/email builders

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#446]
If I use hidden-md etc on landing pages, I can't see them on the campaign builder until I resize the builder to the appropriate resolution, which could cause some issues going forward with template providers.

**Comment by alanhartless** [comment]
I'm not for sure how we can get around this.  Any suggestions or thoughts on it? 

If the builder window is the size of what bootstrap considers hidden-md, it's gonna hide the element as the page loaded is a live preview. 

Thanks,
Alan

**Comment by RCheesley** [comment]
I don't know - raising as an issue as requested for discussions!  It might be a non-issue entirely - I'm not sure how things like Unbounce get around it, they have a desktop preview and a mobile preview if I remember rightly?

**Comment by npracht** [comment]
Hi,

It would be great to have a mobile preview for the email & Landing Page on the webpage.

Competitor email preview
![competitor email preview](https://cloud.githubusercontent.com/assets/14075239/10449669/600d2be2-7195-11e5-8ec2-fffc656ebefb.png)

Mautic preview button
![mautic button preview](https://cloud.githubusercontent.com/assets/14075239/10449670/600ea9e0-7195-11e5-92ef-cda2288e5bb1.png)

Mautic email preview
![mautic email preview](https://cloud.githubusercontent.com/assets/14075239/10449671/6010e23c-7195-11e5-99b3-afd784289c40.png)
