### ISSUE TITLE
Notification - user association error while running mautic:campaigns:trigger

### ISSUE THREAD

**Issue by bodoschmidt** [mautic/mautic#4463]
I use Mautic 2.9

I get this Message from my Server per Email:

Cron <root@h1652875> /opt/plesk/php/7.0/bin/php -f '/var/www/vhosts/fw53.de/mautic.fw53.de/app/console' -- 'mautic:campaigns:trigger' > /dev/null

  [Doctrine\ORM\ORMInvalidArgumentException]
  A new entity was found through the relationship 'Mautic\CoreBundle\Entity\Notification#user' that was not configured to cascade persist operations for entity: Mautic\UserBundle\Entity\User with ID #1. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

mautic:campaigns:trigger [-i|--campaign-id [CAMPAIGN-ID]] [--scheduled-only] [--negative-only] [-l|--batch-limit [BATCH-LIMIT]] [-m|--max-events [MAX-EVENTS]] [-f|--force] [-t|--timeout TIMEOUT] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

What does it mean?

**Comment by escopecz** [comment]
Do you have any idea what campaign, what campaign event is causing this?

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/4498
