### ISSUE TITLE
PHP Mcrypt extension deprecated as of PHP 7.1.0 - what are plans for replacement?

### ISSUE THREAD

**Issue by void-gh** [mautic/mautic#4464]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Y

## Description:
The Mcrypt extension is currently required by Mautic's (up to v 2.9.0) installer; however, as of PHP 7.1.0 it is deprecated ([http://php.net/manual/en/intro.mcrypt.php](url) & [https://wiki.php.net/rfc/mcrypt-viking-funeral](url)) which isn't surprising as it been abandonware since 2007 ([https://sourceforge.net/projects/mcrypt/files/Libmcrypt/](url)). Is there a plan and timeline to replace Mcrypt with something else (e.g. OpenSSL/LibreSSL)?

**Comment by Woeler** [comment]
I think [openssl_encrypt](http://php.net/manual/en/function.openssl-encrypt.php) would be the only logical option as per PHP7.1.

**Comment by shulard** [comment]
Hello guys,

With the upcoming PHP7.2 release (which will be in GA before the end of the month...) the `mcrypt` extension in not part of the core anymore.
It seems to be usable from PECL but is there a plan to move away from `mcrypt` ?

**Comment by joebordes** [comment]
This issue has been very active this week here: #5300 and it looks like it is ready

**Comment by shulard** [comment]
Didn't see that PR, very nice addition. Maybe this issue can be closed now.
