### ISSUE TITLE
Bug: Error during auth for Instagram on mautic.net 

### ISSUE THREAD

**Issue by marbetschar** [mautic/mautic#4466]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I just signed up for a demo account on mautic.net and tried to connect it to my Instagram profile through the provided plugins. But as soon as I click on "Authorize App" it throws the following JSON response in the popup:

![bildschirmfoto 2017-07-19 um 09 54 29](https://user-images.githubusercontent.com/392542/28356522-aa396260-6c68-11e7-9628-cec74e47fac3.png)

**Comment by escopecz** [comment]
This is issue related to Mautic Could only. So the open source community cannot fix it. But I make sure this will get logged in the Cloud bug reporting system.

**Comment by marbetschar** [comment]
@escopecz Ok, thank you! Where shall I put such kind of issues next time? Wasn't sure where to put it so I tried my luck here :)
