### ISSUE TITLE
Failed to push contact to Dynamics CRM (Dynamics 365)

### ISSUE THREAD

**Issue by javiergas** [mautic/mautic#4467]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I updated to 2.9, configured the integration with my Dynamics 365 online and a campaign to Push contacts on read email. Now i'm getting this:
![image](https://user-images.githubusercontent.com/30293899/28371440-01d3886e-6c6b-11e7-8bba-c24f18f51cf7.png)

I'm synchronizing contacts only, mapping only email and last name:
![image](https://user-images.githubusercontent.com/30293899/28378465-3f601496-6c7e-11e7-9cef-f3e0980e0e09.png)

By excuting the command php app/console mautic:integration:fetchleads -i Dynamics
it Works fine:

app/console mautic:integration:fetchleads -i Dynamics
Command to fetch contacts from integration
Fetch contacts command is starting

0 contacts were updated and 0 contacts were created

Updating/creating leads from Mautic to Dynamics
About 0 to update and about 1 to create/update
This could take some time. Please wait until the process is completed
 1/1 [============================] 100%
Number of contacts pushed: 0 updated, 1 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria)
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9
| PHP version | 5.6.25

### Steps to reproduce:
1. Configure campaign
![image](https://user-images.githubusercontent.com/30293899/28378559-957e6990-6c7e-11e7-8b0c-ccac1c17dfcc.png)
2. Activate campaign
3. Let the contact open the email
4. Wait for errors in notification pane
 
### Log errors: 
[2017-07-18 17:58:40] mautic.NOTICE: PHP Notice - Undefined index: contacts - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PluginBundle/Integration/AbstractIntegration.php - at line 1795 [] []
[2017-07-18 17:58:40] mautic.WARNING: PHP Warning - Invalid argument supplied for foreach() - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PluginBundle/Integration/AbstractIntegration.php - at line 1801 [] []

**Comment by patrickrcdm** [comment]
Hi Javier,
I have the same problem here. Did you solve ?

![image](https://user-images.githubusercontent.com/25817274/28622107-b7986178-71e9-11e7-8d68-9d3ea9cf4a65.png)

In Forms - Actions - I don´t have the option to push to integration
![image](https://user-images.githubusercontent.com/25817274/28622146-dc041cc8-71e9-11e7-88f1-251d9f516217.png)

My integration is working:
![image](https://user-images.githubusercontent.com/25817274/28622186-046937c0-71ea-11e7-8ddf-c13597a22d6d.png)

**Comment by javiergas** [comment]
Hi Patrick, I didn't solve it.
I'm getting the same error with form actions.
I also tested it in a new Mautic server with PHP 7.0.18, with the same results.

**Comment by javiergas** [comment]
I updated to 2.9.2 and I'm still getting the same in the log:

[2017-08-15 15:04:31] mautic.NOTICE: PHP Notice - Undefined index: contacts - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PluginBundle/Integration/AbstractIntegration.php - at line 1797 [] []
[2017-08-15 15:04:31] mautic.WARNING: PHP Warning - Invalid argument supplied for foreach() - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PluginBundle/Integration/AbstractIntegration.php - at line 1803 [] []

**Comment by npracht** [comment]
We noticed that obvisouly your CRM must be an English language instance ! @virlatinus do you confirm ?

**Comment by javiergas** [comment]
I'm using a CRM with English base language

**Comment by javiergas** [comment]
I tried it again on Mautic v2.11.0 and it seems to be working fine.

**Comment by djeraseit** [comment]
This needs to be closed.

**Comment by BitSprocket** [comment]
Don't close - I'm getting this error also.  New install today Mautic V2.15.1-dev.  I created a simple form that captures only email, last name and first name.  The submit function sends several emails that all arrive but the contact does not get created in Dynamics365.  If I use the command line utility as mentioned above the contact does get added to Dynamics.

When the integration fails, I get an alert with the following:
`Dynamics Error
Dynamics CRM API error: {"code":400,"headers":{"Cache-Control":"no-cache","Content-Type":"application\/json; odata.metadata=minimal","Expires":"-1","Server":"","Set-Cookie":"ApplicationGatewayAffinity=e6b6b0ae79e9ede16c08e929ab1d35d7f04ebe6495efd99f9917b62678358e72;Path=\/;Domain=sandigitaltech.crm.dynamics.com","x-ms-service-request-id":"605bb6c7-984d-4db5-8d36-29bc8dfec6cc","REQ_ID":"605bb6c7-984d-4db5-8d36-29bc8dfec6cc","AuthActivityId":"31a0ab4a-8646-49d0-aa71-2edd32daaedd","x-ms-ratelimit-burst-remaining-xrm-requests":"59998","x-ms-ratelimit-time-remaining-xrm-requests":"11,999.99","OData-Version":"4.0","Date":"Thu, 07 Mar 2019 04:10:39 GMT","Content-Length":"9434"},"body":"{\"error\":{\"code\":\"0x0\",\"message\":\"An error occurred while validating input parameters: Microsoft.OData.ODataException: Cannot convert the literal '0' to the expected type 'Edm.Boolean'. ---> Microsoft.OData.ODataException: Cannot convert a value of type 'Edm.Int32' to the expected target type 'Edm.Boolean'.\\r\\n at Microsoft.OData.ODataPayloadValueConverter.ConvertInt32Value(Int32 intValue, Type targetType, IEdmPrimitiveTypeReference primitiveTypeReference)\\r\\n at Microsoft.OData.ODataPayloadValueConverter.ConvertFromPayloadValue(Object value, IEdmTypeReference edmTypeReference)\\r\\n --- End of inner exception stack trace ---\\r\\n at Microsoft.OData.ODataPayloadValueConverter.ConvertFromPayloadValue(Object value, IEdmTypeReference edmTypeReference)\\r\\n at Microsoft.Crm.Extensibility.ODataV4.CrmPrimitivePayloadValueConverter.ConvertFromPayloadValue(Object value, IEdmTypeReference edmTypeReference)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightReaderUtils.ConvertValue(Object value, IEdmPrimitiveTypeReference primitiveTypeReference, ODataMessageReaderSettings messageReaderSettings, Boolean validateNullValue, String propertyName, ODataPayloadValueConverter converter)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadPrimitiveValue(Boolean insideJsonObjectValue, IEdmPrimitiveTypeReference expectedValueTypeReference, Boolean validateNullValue, String propertyName)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String payloadTypeName, IEdmTypeReference expectedTypeReference, PropertyAndAnnotationCollector propertyAndAnnotationCollector, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideComplexValue, String propertyName, Nullable`1 isDynamicProperty)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadEntryDataProperty(IODataJsonLightReaderResourceState resourceState, IEdmProperty edmProperty, String propertyTypeName)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithValue(IODataJsonLightReaderResourceState resourceState, String propertyName)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.c__DisplayClass4_0.b__0(PropertyParsingResult propertyParsingResult, String propertyName)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceStart(PropertyAndAnnotationCollector propertyAndAnnotationCollector, SelectedPropertiesNode selectedProperties)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(PropertyAndAnnotationCollector propertyAndAnnotationCollector)\\r\\n at Microsoft.OData.ODataReaderCore.ReadImplementation()\\r\\n at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)\\r\\n at System.Web.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)\\r\\n at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)\\r\\n at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)\",\"innererror\":{\"message\":\"An error occurred while validating input parameters: Microsoft.OData.ODataException: Cannot convert the literal '0' to the expected type 'Edm.Boolean'. ---> Microsoft.OData.ODataException: Cannot convert a value of type 'Edm.Int32' to the expected target type 'Edm.Boolean'.\\r\\n at Microsoft.OData.ODataPayloadValueConverter.ConvertInt32Value(Int32 intValue, Type targetType, IEdmPrimitiveTypeReference primitiveTypeReference)\\r\\n at Microsoft.OData.ODataPayloadValueConverter.ConvertFromPayloadValue(Object value, IEdmTypeReference edmTypeReference)\\r\\n --- End of inner exception stack trace ---\\r\\n at Microsoft.OData.ODataPayloadValueConverter.ConvertFromPayloadValue(Object value, IEdmTypeReference edmTypeReference)\\r\\n at Microsoft.Crm.Extensibility.ODataV4.CrmPrimitivePayloadValueConverter.ConvertFromPayloadValue(Object value, IEdmTypeReference edmTypeReference)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightReaderUtils.ConvertValue(Object value, IEdmPrimitiveTypeReference primitiveTypeReference, ODataMessageReaderSettings messageReaderSettings, Boolean validateNullValue, String propertyName, ODataPayloadValueConverter converter)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadPrimitiveValue(Boolean insideJsonObjectValue, IEdmPrimitiveTypeReference expectedValueTypeReference, Boolean validateNullValue, String propertyName)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String payloadTypeName, IEdmTypeReference expectedTypeReference, PropertyAndAnnotationCollector propertyAndAnnotationCollector, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideComplexValue, String propertyName, Nullable`1 isDynamicProperty)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadEntryDataProperty(IODataJsonLightReaderResourceState resourceState, IEdmProperty edmProperty, String propertyTypeName)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadPropertyWithValue(IODataJsonLightReaderResourceState resourceState, String propertyName)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.c__DisplayClass4_0.b__0(PropertyParsingResult propertyParsingResult, String propertyName)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(PropertyAndAnnotationCollector propertyAndAnnotationCollector, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightResourceDeserializer.ReadResourceContent(IODataJsonLightReaderResourceState resourceState)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadResourceStart(PropertyAndAnnotationCollector propertyAndAnnotationCollector, SelectedPropertiesNode selectedProperties)\\r\\n at Microsoft.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(PropertyAndAnnotationCollector propertyAndAnnotationCollector)\\r\\n at Microsoft.OData.ODataReaderCore.ReadImplementation()\\r\\n at Microsoft.OData.ODataReaderCore.InterceptException[T](Func`1 action)\\r\\n at System.Web.OData.Formatter.Deserialization.ODataReaderExtensions.ReadResourceOrResourceSet(ODataReader reader)\\r\\n at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.Read(ODataMessageReader messageReader, Type type, ODataDeserializerContext readContext)\\r\\n at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)\",\"type\":\"Microsoft.Crm.CrmHttpException\",\"stacktrace\":\" at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.ValidateInputParameters(ModelStateDictionary controllerModelState)\\r\\n at Microsoft.Crm.Extensibility.OData.EntityController.PostEntitySetImplementation(String& entitySetName, EdmEntityObject entityObject)\\r\\n at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\\r\\n at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\\r\\n at lambda_method(Closure , Object , Object[] )\\r\\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.c__DisplayClass10.b__9(Object instance, Object[] methodParameters)\\r\\n at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n at System.Web.Http.Dispatcher.H`

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by dipakparmar** [comment]
Hi @npracht I'm having a similar issue and running mautic docker version `mautic/mautic:v3`
