### ISSUE TITLE
[feature] bounce management/tracking feature

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#447]
It would be really helpful if there was a bounce management system which would:
* identify emails which soft/hard bounce
* Flag the leads who are bouncing and why (e.g. holiday out of office, inbox full, address not known etc)
* Allow editing the email address if a typo has been made
* Allow re-starting the lead wherever they are in a process, by re-sending the email that just bounced (ref https://github.com/mautic/mautic/issues/434)
* Distinguish between failed and bounced mails (ref https://github.com/mautic/mautic/issues/435) in dashboards
* Have some kind of bounce management process which could be set globally and/or on a campaign basis that would allow you to:
 - Delete the lead
 - Remove lead from campaign
 - Unsubscribe the lead
 - Subscribe lead to another list
 - Carry out other actions (e.g. alert an admin)
 - Automatically follow up (in the case of the out of office)

**Comment by hisaltesse** [comment]
This feature is absolutely necessary and would be a key differentiator to mautic.

**Comment by hisaltesse** [comment]
In case this is useful for working on this feature: 
Bounce Handler: Parse bounced e-mail message reports
http://www.phpclasses.org/package/2691-PHP-Parse-bounced-e-mail-message-reports.html

**Comment by renangallo** [comment]
+1

**Comment by tmorello** [comment]
This is very necessary and would put Mautic ahead

**Comment by diogondim** [comment]
We <b>realy</b> need this.

**Comment by hisaltesse** [comment]
I agree. This is the reason why I stopped deploying Mautic and went back to PHPList. 
I love the features of Mautic but without bounce management it is too much of a pain to use it the way it is. When bounce management is released I would reconsider.

**Comment by tmorello** [comment]
You are right. I use Sendy and really wanna migrate to Mautic, but with this issue, its impossible. Its like walk backwards

**Comment by dbhurley** [comment]
So we're all a community, let's work together to get it coded :) Tell your dev friends! Let's identify talent that can help get this written. The process would not be a difficult one just takes time. The best part about open source and community driven is we can make this happen! So let's do it!

**Comment by escopecz** [comment]
Bounce management had been added in 1.2.0 (https://github.com/mautic/mautic/releases/tag/1.2.0).
