### ISSUE TITLE
Set flag is_read to 1 in email_stats when clicked by link in email

### ISSUE THREAD

**Issue by Nelex** [mautic/mautic#4472]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
hey guys! Some email clients and hosting can block loading image for tracking and then Read count will not increase, but click on this emails can be clicked and insert into DB for stats. As i can see now if link clicked email still not marked as read. I think this is logical bug

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 5.6

### Steps to reproduce:
1.  Send email with some link
2.  Use thunderbird client(block images from internet by default for unknown senders)
3. Click on the link
4. Profit

**Comment by escopecz** [comment]
This is actually how Mautic works. Here is the code which does this: https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/EventListener/PageSubscriber.php#L81

And it's working for me. Please test it again and make sure you are not logged into Mautic when testing.

**Comment by Nelex** [comment]
Thx.
So... this code will be in next update?

**Comment by kuzmany** [comment]
@Nelex maybe you're logged in to Mautic

https://mautic.org/docs/en/pages/troubleshooting.html

**Comment by Nelex** [comment]
@kuzmany nope. We sent emails and have clicks more than reads. This is strange...

**Comment by kuzmany** [comment]
@Nelex It's possible. You have 1 read just 1 for contact, but clicks you have more per contact.
Try look if your db is actual php app/console doctrine:schema:update --dump-sql
Try look to logs.
