### ISSUE TITLE
Filter in contact not working properly for quoted string- giving less number of counts

### ISSUE THREAD

**Issue by aviboy2006** [mautic/mautic#4474]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description: 
any one having idea about ;
```
protected function addCatchAllWhereClause($q, $filter)
    {
        $columns = array_merge(
            [
                'l.firstname',
                'l.lastname',
                'l.email',
                'l.company',
                'l.city',
                'l.state',
                'l.zipcode',
                'l.country',
            ],
            $this->availableSocialFields
        );

       return $this->addStandardCatchAllWhereClause($q, $filter, $columns);
    }
```
in `LeadRepository.php`
this function
when use search without quote it don't include this
when use with quote it include -- query seems to be wrong because of this 
when u search tag:"ABV ade" its not gave exact result some data missing 
because in query 
```
SELECT COUNT(DISTINCT(l.id)) AS COUNT
FROM knableads l
LEFT JOIN knabusers u ON u.id = l.owner_id
LEFT JOIN knabstages s ON s.id = l.stage_id
INNER JOIN knablead_tags_xref xtag ON l.id = xtag.lead_id
INNER JOIN knablead_tags tag ON xtag.tag_id = tag.id
WHERE (tag.tag LIKE 'not reachable%')
  AND ((l.date_identified IS NOT NULL)
       AND ((l.firstname LIKE '%')
            OR (l.lastname LIKE '%')
            OR (l.email LIKE '%')
            OR (l.company LIKE '%')
            OR (l.city LIKE '%')
            OR (l.state LIKE '%')
            OR (l.zipcode LIKE '%')
            OR (l.country LIKE '%'))) (edited)
 
AND condition before l.lastname should be OR
```

## If a bug:
```
| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
```
### Steps to reproduce:
1.  Search and tag using "Axd day" it will give 100 counts, ideally it should be 400 as per database query directly.
 
### Log errors:  No log error. Its query level mapping issue.

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
