### ISSUE TITLE
Custom select list sets label to value

### ISSUE THREAD

**Issue by FabianTe** [mautic/mautic#4476]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Basically this

![image](https://user-images.githubusercontent.com/7669818/28427737-7e608104-6d77-11e7-9fa5-b023e16c34f1.png)

becomes this

![image](https://user-images.githubusercontent.com/7669818/28427749-886f024c-6d77-11e7-9a1c-153ea0783696.png)

when I save the custom field.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version | 7.1.7 via XAMPP

### Steps to reproduce:
1. Add a custom field, type select and add a label-value-pair. Label != value!
2. Hit save
 
### Log errors: 

I am on a dev env and This is the sql INSERT when I save:

![image](https://user-images.githubusercontent.com/7669818/28428248-1c3d7188-6d79-11e7-9a60-d8de7077fb10.png)

**Looks like the sql query is okay**. Might this be related to #3664?

This is the INSERT query for the Audit log, looks even stranger:

![image](https://user-images.githubusercontent.com/7669818/28428358-7ba36466-6d79-11e7-8bd6-d22aa0561596.png)

The sql table itself holds the correct data:

```
a:1:{s:4:"list";a:1:{i:0;a:2:{s:5:"label";s:5:"Kunde";s:5:"value";s:8:"customer";}}}
```

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/4355

**Comment by FabianTe** [comment]
@escopecz Nice, was just about to comment on the pr that I tested the commit and it worked for me too but you already merged it. Thanks.
