### ISSUE TITLE
Top Lists on Dashboard severely out of date with actual Contact count in Segment

### ISSUE THREAD

**Issue by cougar2009** [mautic/mautic#4478]
These two numbers should be the same  

![discrepancy mautics lists](https://user-images.githubusercontent.com/19396480/28432909-07397638-6d47-11e7-8380-063a06a9c4ab.png)

**Comment by cougar2009** [comment]
When I change the dates at the top .... THEN it updates the numbers.  Refreshing the page should be all I need to do.

**Comment by escopecz** [comment]
Can you please provide some background? There is not enough data to declare this a bug. Some steps to replicate? Please next time fill in the issue template so we wouldn't have to ask the questions in the template again.

**Comment by cougar2009** [comment]
https://www.dropbox.com/s/eclorrwt22lci5o/mautic%20bug%201.mp4?dl=0

**Comment by cougar2009** [comment]
steps to reproduce
go to dashboard and note count of top segments under "Top Lists"
go to Contacts and add more contacts to those segments. 
Go back to dashboard and note that the count has not increased.

**Comment by escopecz** [comment]
Maybe it's because of the 10 min cache? Read https://mautic.org/docs/en/dashboard/index.html

**Comment by cougar2009** [comment]
Not likely as I can wait days and not have it refresh.

**Comment by escopecz** [comment]
What value for the cache do you have in your configuration?

**Comment by cougar2009** [comment]
Not sure how to check, but this is hosted on Mautic cloud not self install.

**Comment by escopecz** [comment]
That's quite an important information. It seems quite similar to https://github.com/mautic/mautic/issues/3856. I'll close this issue as duplicate then. It seems that it happens only on mautic.net so far.
