### ISSUE TITLE
Recent Activity Widget on Dashboard Not Updating 

### ISSUE THREAD

**Issue by cougar2009** [mautic/mautic#4479]
Certainly there has been more recent activity that from 5-6 days ago. 

![image](https://user-images.githubusercontent.com/19396480/28432986-58b71f38-6d47-11e7-8c14-9eb6af530329.png)

**Comment by cougar2009** [comment]
When I change the dates at the top .... THEN it updates the numbers.  Refreshing the page should be all I need to do.

**Comment by escopecz** [comment]
What was the date range filter set to?

**Comment by escopecz** [comment]
I'll close this issue in favour of https://github.com/mautic/mautic/issues/4478 since it seems you have problem with the date range filter there too.
