### ISSUE TITLE
Removing contacts from companies via the API call doesn't work

### ISSUE THREAD

**Issue by jweultjes** [mautic/mautic#4486]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |X |
| Feature request? | 
| Enhancement? | 

## Description:
When removing a contact from a company via the API call it always returns 
`success = 1` as long as the contact and company exist (even when the contact isn't related to the company) but it never actually removes the contact from the company. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2 |
| PHP version | 5.6.30 |

### Steps to reproduce:
1. Create a company
2. Create a contact and relate it to the company
3. Try to remove the link via api call `/companies/COMPANY_ID/contact/remove/CONTACT_ID`
4. server returns `success = 1` 
5. Check company and see the contact is still related there. 
 
### Log errors: 
No errors or messages in the logs.

**Comment by escopecz** [comment]
I cannot reproduce the issue. I executed the API call and the contact was removed from the company. Is there any other step to take? Like do you use admin user or some user with limited permissions for the API call? Maybe upgrade to Mautic 2.9.2 and try there if it was fixed there?
