### ISSUE TITLE
[feature] Add analytics tracking code for links

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#449]
In apps like Hootsuite there's a fairly simple option when you add a link, to add parameters using a template - for example the utm source, medium, campaign etc.

It would be super awesome if you could have this kind of option in Mautic, such that when I paste a URL into Mautic's external URL I could append the required parameters for this tracking.

**Comment by alanhartless** [comment]
So remember that external URL token is going away in favor of #353 and all links will be auto-converted to Mautic trackables. So with this feature request, maybe we need to keep the external URL drag and drop and expand it to include parameters? So you can easily build a URL and rename the external URL to something more appropriate.  Especially if integrated with a URL shortening service, which I like the idea of.

**Comment by RCheesley** [comment]
Either that or allow the appending of those variables to a Mautic URL somehow?  If you use a shortening service like Hootsuite's one, it creates the URL with the variables, and then shortens it - so the shortened URL points at the full length one with the tracking stuff.  Make sense?

**Comment by MaxOnTheHill** [comment]
Would be great if we could add UTM tracking variables for campaign tracking ...... adding these variables to any "in email" link variables ... as part of the link shortening?

This means that for each campaign there would be settings to enter variables like on this page http://gaconfig.com/google-analytics-url-builder/

This would mean that all emails sent out would then be tracked in campaign reports properly, being able to be reused without having to duplicate, re-edit, etc just to get reporting data - as it would be set per campaign, as opposed to hard coded in the emails.

**Comment by troelsfeodor** [comment]
+1 for UTM tracking variables on links

**Comment by kuzmany** [comment]
:+1:  UTM links are very important and now adding to emails it's not comfortable

**Comment by that0n3guy** [comment]
+1 

We do this on our current bulk emailing solution.  Ours are hard coded like:
Campaign Source: mautic (the word "mautic")
Campaign Medium: email (the word "email")
Campaign Content: The split test name
Campaign Name: Name of the campaign (or email if just sending an email)

Campaign Term: Don't use this.  Leaves it free for the user to add this manually per link if needed.

**Comment by kuzmany** [comment]
Guys @that0n3guy, @troelsfeodor, @MaxOnTheHill, @RCheesley 

This plugin can solve issue https://github.com/kuzmany/MauticAnalyticsTaggingBundle 

Any feedback would be great.

**Comment by npracht** [comment]
Hi @kuzmany,

I think you should make a PR with that feature which is a great feature for analysis for marketers !
Great job !

N.
