### ISSUE TITLE
Campaign Templates

### ISSUE THREAD

**Issue by dgram** [mautic/mautic#4491]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
It will be a nice feature, to define an campaign and save them as an template to copy it.
We build much campaigns from time to time which is pretty the same campaign procedure.

So campaign templates would make this process much faster and easier. Especially when you want to have multiple users which need an copy for their marketing campaigns

regards

**Comment by escopecz** [comment]
Cloning a campaign doesn't work for this purpose?
