### ISSUE TITLE
Mautic not resolving DNS name -> IP address even when host OS does

### ISSUE THREAD

**Issue by void-gh** [mautic/mautic#4492]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
On a clean install of Mautic 2.9.0 on OpenBSD 6.1 it appears that Mautic is unable to resolve DNS names even though the host operating system can successfully resolve the same address (as verified by dig examplehostname.com). When attempting to enter in the email settings fields under "Monitored Inbox Settings" when I click the "Test connection and fetch folders" button I receive the following error message:

`Error communicating with the IMAP server: No such host as examplehostname.com`

Additionally, under Configuration -> System Settings -> Miscellaneous Settings when clicking on the "Update IP Lookup Data Store" button we receive the following error:

`Automatically fetching the IP lookup data failed. Download [...]`

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.9.0
| PHP version | 7.0.16

### Steps to reproduce:
1. Navigate to Configuration -> System Settings -> Email Settings
2. Enter DNS name into either SMTP host or IMAP Host
3. Click on the corresponding "Test connection..." button
 
### Log errors: 
Looking into the mautic/app/logs/mautic_prod_2017-07-20.php file it shows the following error:

`[2017-07-20 09:43:11] mautic.NOTICE: PHP Notice - Unknown: No such host as examplehostname.com (errflg=2) - in file Unknown - at line 0 [] []`

`[2017-07-20 10:08:25] mautic.ERROR: Failed to fetch remote IP data: fsockopen(): unable to connect to geolite.maxmind.com:80 (php_network_getaddresses: getaddrinfo failed: no address associated with name) [] []`

**Comment by Gregy** [comment]
Hello. dig uses more sophisticated methods of name resolving then a typical program. Could you please verify that:
1. your OS can really resolve dns names (ping google.com)
2. your php installation can resolve dns names (create php file on your server with: `echo gethostbyname("www.google.com");`) and visit it

Thanks.

**Comment by void-gh** [comment]
Hi Gregy,

1. Ping test results
```
$ ping google.com  
PING google.com (216.58.193.78): 56 data bytes
64 bytes from 216.58.193.78: icmp_seq=0 ttl=53 time=36.777 ms
64 bytes from 216.58.193.78: icmp_seq=1 ttl=53 time=36.660 ms
64 bytes from 216.58.193.78: icmp_seq=2 ttl=53 time=36.543 ms
64 bytes from 216.58.193.78: icmp_seq=3 ttl=53 time=36.630 ms
64 bytes from 216.58.193.78: icmp_seq=4 ttl=53 time=36.701 ms
```

2. PHP Test
Created a test file with the following code:
```
<?php
$ip = gethostbyname('www.google.com');
echo $ip;
?>
```
Accessing the page through the web server results in a failure to lookup IP address from DNS name. gethostbyname simply returns the unmodified string which indicates a DNS lookup failure.

However; running the test file through the command line via
`php-7.0 testdns.php`
Results in the following output:
`74.125.28.104`

This led to the root cause discovery. When I'd setup the web server I'd forgotten to copy over the `/etc/resolv.conf` and `/etc/services` files into the `httpd` service's chroot jail of `/var/www/etc`. Copying these files over and restarting the `httpd` and `php70_fpm` services allowed Mautic to successfully complete DNS lookups.

Thanks for the assist,
Chris

**Comment by Gregy** [comment]
Great, glad it works for you.

**Comment by yrammos** [comment]
Facing the same issue here with a bare-bones setup (i.e. without a chroot jail).
