### ISSUE TITLE
Mautic attempts to execute scheduled events for bounced and unsubscribed contacts

### ISSUE THREAD

**Issue by tadinski** [mautic/mautic#4494]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✅
| Feature request? | 
| Enhancement? | 

## Description:
Mautic continues attempting to execute scheduled events for contacts that have bounced or unsubscribed. Notifications bell is is full of warnings about failed executions. Yesterday I found out my MySQL's db had over 4million rows in the "notifications" table.

<img width="307" alt="notifications" src="https://user-images.githubusercontent.com/6358371/28494582-03af2272-6f33-11e7-8091-2f173e0eefc4.png">

<img width="292" alt="unsubbed" src="https://user-images.githubusercontent.com/6358371/28494619-f7997806-6f33-11e7-9033-1befd9a7f675.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version | 7.0.5

### Steps to reproduce:
1. Create a campaign, schedule 2 emails 20 minutes each in between
2. Add yourself to this campaign
3. Either bounce the the first email you receive or unsubscribe
4. Mautic will attempt to execute the 2nd email sending event and put a warning in the notification's bar

**Comment by robwent** [comment]
This may possibly be related to using webhooks for bounce management and this issue https://github.com/mautic/mautic/issues/3173

**Comment by AkkuFresh** [comment]
This bug still exists in Mautic v. 2.12.1. 
I have found 2700+ unnecessary notification record in the table related to the above described issue.

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by mleffler** [comment]
Can you please test this along with the campaign refactoring?  TY!
