### ISSUE TITLE
Clearing notifications from Mautic doesn't work

### ISSUE THREAD

**Issue by tadinski** [mautic/mautic#4495]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✅
| Feature request? | 
| Enhancement? | 

## Description:
Clearning the notifications works on the front-end only. Refreshing the page, shows the same notifications. After checking the db's notifications table, I see notifications aren't being deleted from the database at all.

Frontend successfully clears notifications

<img width="358" alt="frontend cleared" src="https://user-images.githubusercontent.com/6358371/28494649-bd42e4f2-6f34-11e7-8d3b-865ab6acf2cc.png">

Database non affected

<img width="1121" alt="db" src="https://user-images.githubusercontent.com/6358371/28494650-bd495648-6f34-11e7-8252-ebff55c25816.png">

After refreshing Mautic all notifications are back

<img width="356" alt="back" src="https://user-images.githubusercontent.com/6358371/28494661-0eb95334-6f35-11e7-9a52-b325bccbc5a7.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version | 7.0.1

**Comment by escopecz** [comment]
I use clearing quite often and it does work. It should not delete the rows from the table, but set the is_read flag to 1.

**Comment by tadinski** [comment]
@escopecz you are right, the reason why I keep seeing the notification be filled up right after clearing is because there are just so many failed executions which Mautic tries to execute for the people who are unsubscribed or bounced. I opened another issue for that, I saw you labeled it as a "bug"

**Comment by andsat** [comment]
I had this same issue after a buggy update gave me a failed campaign for every user. clearing via the GUI was fruitless, so I did this:

> DELETE FROM `notifications` WHERE `notifications`.`is_read` = 0;

**Comment by fang-yu** [comment]
I have this problem too in 2.13.1, does this get fixed?

**Comment by SparkkiOLP** [comment]
For those that are using MySQL

```
use DataBaseName;
DELETE FROM notifications WHERE is_read = 0;
```

If you have some crazy number like `434775` you will have to wait for it to execute.  Mine took over 1 minute to process.

**Comment by zenzozen** [comment]
Same here. I truncated the notifications table because i couldn use mautic anymore - 150.000.000 entries!! 90% because DO NOT CONTACT failed email
