### ISSUE TITLE
SwiftMail can't find file and breaks mail sending

### ISSUE THREAD

**Issue by FabianTe** [mautic/mautic#4500]
What type of report is this:

| Q  | A
| ---| ---X
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
Somehow sending mails get's broken when I send mails with images. I am if this might be related to the image manager in the mail builder and someone renaming an image there without changing it in the mails.

I am only able to restart sending mails by deleting the spool folder's content. But I guess then I loose some mails along the way, that will never be sent, right?

*I suppose this is less a bug but more a misconfiguration*

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | PHP Version 7.0.18-0ubuntu0.16.04.1

### Steps to reproduce:
1. Send a mail with an image
2. Run ```mautic:emails:send```
 
### Log errors: 

```[2017-07-24 06:50:05] mautic.NOTICE: Swift_IoException: Unable to open file for reading [cid%3A98799b0823d6f90e58dce18b9b609a49@event.xsuite.com] (uncaught exception) at /var/www/html/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []```

**Comment by escopecz** [comment]
Yes, it seems like a file system permission issue. Make sure Mautic is able to read and write to all its files. Do not use root to run the Mautic cron commands.

**Comment by FabianTe** [comment]
Should I use the apache user for the commands then?

**Comment by escopecz** [comment]
Yes, Apache user is the best option.

**Comment by FabianTe** [comment]
Sorry, sadly I'm not involved in mautic related topics. Good luck!

**Comment by escopecz** [comment]
@YahiaBakour what's your error exactly?

**Comment by AlbanL74fr** [comment]
Looks the same as : https://github.com/mautic/mautic/issues/5493
