### ISSUE TITLE
Unable to reset Twitter credential (use another account)

### ISSUE THREAD

**Issue by HiveMindNet** [mautic/mautic#4512]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Got Twitter integration working using a test account. Now want to move to live account, no matter what I do it still posts responses using the first account. Even if I revoke access to the app on the first account, the plugin reactivates it at the authorise app point, (even though it's showing details of the new app- it authorises the old app with Twitter). This is a security risk in addition to a bug.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version | 7.0.19-1+deb.sury.org~trusty+1

### Steps to reproduce:
1. Set up twitter integration in normal way
2. change app credentials in plugin to new version of app under different Twitter account
3. Revoke access to app in first twitter account
4. Run twitter plugin using campaign to post a tweet
5. See the tweet comes from the first, since disabled Twitter account.
 
### Log errors: 

Not sure this is a relevant log entry but it's all I have

[2017-07-25 12:35:11] mautic.NOTICE: PHP Notice - SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13) - in file /var/www/mautic/app/cache/prod/classes.php - at line 428 [] []

**Comment by escopecz** [comment]
This seems like a cache issue based on the error message and that the configuration does not change no matter what you do. Try to delete contents of app/cache directory and test again. Is it  fixed?

**Comment by HiveMindNet** [comment]
I tried using console cache:clear and but is still present - I'll try clearing the cache directory and test again

**Comment by HiveMindNet** [comment]
I deleted the contents of the cache directory but somehow, even with the app credentials from the new account app, it's still authorising using the previous twitter account and showing in the twitter authorised apps. Very odd. Are the credentials in the DB?
