### ISSUE TITLE
Gotowebinar Forms Integration

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#4516]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | NO
| Enhancement? | NO

## Description:
When we try to integrate the list of the new Webinars come from GotoWebinar instead of the name of the webinar we have a list of number.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9
| PHP version | 7.0.11

### Steps to reproduce:
1.  Create a form with the mandatory field for a gotowebinar intergration
2.  Creat the correspondance in the Action Gotowebinar
3.  save the form, see the preview you see the list of the number but no name
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/4355 in Mautic 2.9.1
