### ISSUE TITLE
Base64 Image Size Restrictions?

### ISSUE THREAD

**Issue by ZigiBarrett** [mautic/mautic#4518]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  yes

## Description:
When enabling the 'convert embed images to Base64' option in email settings, it appears that there is a size restriction on the images used in emails.  When testing, emails would fail to send returning an error in the log file (see below) however when testing with a (very) small image, the email would be successful.

Is there an inbuilt size restriction on images that can be converted to Base64 and if so, a) what is the maximum allowed size and b) can this restriction be modified?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.9.0
| PHP version | 7.0.18

### Steps to reproduce:
1. create email and embed small image (with Base64 conversion switched on). - (email should send successfully)
2.  Repeat with reasonably large image (over 200KB) - (email should fail to send)
 
### Log errors: 
`[2017-07-26 13:42:36] mautic.ERROR: [MAIL ERROR] Unable to open file for reading [https://example.com.au/media/images/nishMultiPh.png] Log data: ++ Starting Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport << 220 email-smtp.amazonaws.com ESMTP SimpleEmailService-2108164273 094jfsdodpm9e4j0sd9 >> EHLO example.com.au  << 250-email-smtp.amazonaws.com 250-8BITMIME 250-SIZE 10485760 250-STARTTLS 250-AUTH PLAIN LOGIN 250 Ok  >> STARTTLS  << 220 Ready to start TLS  >> EHLO example.com.au  << 250-email-smtp.amazonaws.com 250-8BITMIME 250-SIZE 10485760 250-STARTTLS 250-AUTH PLAIN LOGIN 250 Ok  >> AUTH LOGIN  << 334 VXNlcm5hbWU6  >> 0[9dsfmn0w98m98fsmhe3=  << 334 opdsijmw9e8rm  >> csdpooc99dfjcd98jew0jcj9j0d9jd0w9jd09jw0cnubfe8bf=  << 235 Authentication successful.  ++ Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport started >> MAIL FROM:  << 250 Ok  >> RCPT TO:  << 250 Ok  >> DATA  << 354 End data with .  (send) [] []
[2017-07-26 04:15:05] mautic.NOTICE: Swift_IoException: Unable to open file for reading [cid%3A122d6cff87b97d0b9b2864fd871040c6@example.com.au] (uncaught exception) at /html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []`

**Comment by escopecz** [comment]
The restriction is not on Mautic's side, but email providers. Search Google for phrase "email size limit".

**Comment by LEAP-nishit** [comment]
@escopecz Not sure if its the email server that is causing this. We have successfully used the same images in the past.

The log shows a missing file. 

[2017-07-26 07:35:04] mautic.NOTICE: Swift_IoException: **Unable to open file for reading** [cid%3A122d6cff87b97d0b9b2864fd871040c6@example.com.au] (uncaught exception) at /html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []

All paths are writable by Mautic as shown here. 

Folder/File Path	Is writable
/html/app/config/local.php	Writable
/html/app/cache	Writable
/html/app/logs	Writable
/assets	Writable
/html/media/images	Writable
/html/translations	Writable
/spool	Writable

**Comment by escopecz** [comment]
The path check in the administration is just selecting the most important folders that have to be writable. But all files and folders of Mautic must be writable to Mautic.

Make sure you are not using the crontab under the root user.

**Comment by LEAP-nishit** [comment]
Crontab is under www-data user (the server is Ubuntu). We are able to send very small images with base64 encoding, so a file permission should fail always (I am guessing), but its not the case.
