### ISSUE TITLE
[Feature] Allow duplication of actions/decisions in campaign builder

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#452]
While waiting on #403 I'm creating duplicate flows to get things moving quickly, and there's no way to duplicate an action or decision.

It would be really handy to have a 'duplicate' button which would duplicate an existing action or decision within a campaign for use elsewhere - even better to be able to multi-select and duplicate a chain.

**Comment by 750430** [comment]
Definitely something I'd like to see in Mautic!

**Comment by alanhartless** [comment]
Merging this into #1414
