### ISSUE TITLE
Campaigns on new segments do not run...

### ISSUE THREAD

**Issue by Schokolader** [mautic/mautic#4525]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Contacts added to segments but the campaigns for that segments do not start. 

Using honeypot method: https://www.mautic.org/community-blog/eliminate-spambots-using-the-honeypot-method/

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.9
| PHP version | 7.0

### Steps to reproduce:
1. Create a form and add it to your website 
2. Create a campaign that modifies the segments of a contact 
3. Create a campaign for the new segments contacts for sending mails 
4. Fill out the form on your website
5. You see that the contact is in your "pending" segment but the email
    never went out. 
 
### Log errors: 

`[2017-07-26 15:18:29] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #270. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /home/meditati/public_html/info/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #270. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /home/meditati/public_html/info/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []
`

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/4498

**Comment by Schokolader** [comment]
No can't confirm this. Still not working...

**Comment by escopecz** [comment]
What Mautic version do you run? Please check if the error is any different or if it is still the same.

**Comment by Schokolader** [comment]
new updated to Mautic 2.9.2. I created an new issue with logs here: https://github.com/mautic/mautic/issues/4688

**Comment by escopecz** [comment]
Ok. I could have re-opened this one, but I leave this closed since you created a new one.
