### ISSUE TITLE
One click social network sign up for segments 

### ISSUE THREAD

**Issue by Schokolader** [mautic/mautic#4526]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
Sign up for an segment with social networks with one click. When contact is already logged in in social networks(facebook, linked, twitter, pinterest etc.) that mautic recognize this and contact can sign up for the specific newsletter segment with just one click.

**Comment by escopecz** [comment]
This functionality is already in Mautic: https://mautic.org/docs/en/plugins/social_login.html

Use the form action to change segment membership.
