### ISSUE TITLE
Chart says emails sent when they are not sent

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4527]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

Edited:

When emails are scheduled to send by a campaign, they are shown as "sent" in the actions tab, even if they are not due to send for several days. The chart does not show them as sent. (2.9.2)

![screenshot from 2017-08-09 13-17-15](https://user-images.githubusercontent.com/2853040/29121409-52cdc364-7d06-11e7-9f5b-8c4f6faa5489.png)

In a previous case I had them showing as sent in the chart but not in the actions tab. (in 2.8.x?)

![screenshot from 2017-07-26 16-55-02](https://user-images.githubusercontent.com/2853040/28630897-754f46a8-7223-11e7-91bf-856cc5191694.png)

Previously said:

My crons all broke some time about a week ago and I didn't realise. All my campaign charts show emails being sent but the actions bar below shows they were not sent.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 

### Steps to reproduce:
(partial)
1. Set up a  campaign with emails sheduled to send on a few days time
2. run the crons to add contacts to the campaign
3. the email will show as 100% sent
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
I don't get what's wrong on that screenshot. Could you add some arrows to what does not match and when your crons stopped working? Do you use email queue or immediate sending?

**Comment by gingerling** [comment]
Hi, please see the second green email sending bump in the chart, looks like it's on 25th July. In the Actions tab below the line is 55% red and 45% empty. 

That email was set to send on those who didn't open the first email, which you see in 18th July: 45% of those opend the email so the second email sent to the 55%. So it looks like that email failed.

However, I wasn't sure at the time as the chart clearly shows the emails having been sent.

The same failure instance caused this:

https://drive.google.com/file/d/0Bx8WzdZ2vdLjSFI4cEdOb2pmc00/view?usp=drivesdk

(Can't workout how to add images to github from my phone)

On that one you see the email is marked as sent in the grass, but on the actions tab below it's showing at 0%. Also, the contacts tab for that campaign was showing no contacts in, which I think must be a consequence of it not sending the email. Confusing though as well the graph for email send seems to know that 8 people were added to the campaign, they aren't showing as being added in purple which they usually are. 

Anyway the whole thing was so confusing that I didn't realise that the emails haven't actually sent until it became clear that no one had opened them and I open rate is usually quite high. The the large campaign going to hundreds of people was a list cleaning campaign so a low open rate is totally plausible and the other campaigns were only to a few people, so I am actually still not totally sure what happened. 

I use queue send and there may have been a permissions tissue causing my Cron jobs to fail, however, the only evidence I have that they failed is that these emails didn't send, and I can't be sure of that. Is guy went through my email config with me on the slack channel yesterday, and change the view settings be tested and it's working for sure now.

**Comment by gingerling** [comment]
I also resent all of the campaigns and have now got opens on them.

**Comment by escopecz** [comment]
Could you tell us what version of Mautic do you use? Or are you on Mautic Cloud? You didn't put anything in the issue description about that. I know there were some fixes around that recently.

**Comment by gingerling** [comment]
I updated to latest version yesterday using the automatic feature, but that was after the email for her of course, I am self hosting. Sorry I didn't fill out the information I usually do that I was just in a rush.

**Comment by gingerling** [comment]
Also, i have noticed this: 

![screenshot from 2017-08-09 13-17-15](https://user-images.githubusercontent.com/2853040/29121143-4281a1c0-7d05-11e7-8f6d-f66556450ee7.png)

This situation is a bit more clean cut: the email is scheduled to send in another 3 days from now, the chart shows all the people added to the campaign but the email status on the actions tab is showing as "100% sent" - these mails are of course not sent. I think it's showing items as "sheduled to send" not "sent"

**Comment by escopecz** [comment]
Yes, you are right. The campaign action "send email" was triggered for all contacts, but since the emails were queued for later, they weren't actually sent, so the email chart is not equal to champaign information. Renaming the campaign action to "Send or schedule email" should help with the current confusion.

**Comment by gingerling** [comment]
Yes, well, kind of. I would rather it show me when they are actually physically sent. 

I think that was what it used to do, as initially the bug was the other way round: the chart was wrong and the actions tab was right. The second image in the description (which was what I reported first) and the one https://drive.google.com/file/d/0Bx8WzdZ2vdLjSFI4cEdOb2pmc00/view?usp=drivesdk would say 100% sent in the Actions tab and 0 sent in the chart, but they show the opposite. 

Unless the Actions tab gets corrected during the actual send, then there must have been a change in the last 3 versions.

To clarify, I personally think the chart and the Actions tab should show the same numbers and they should be related to the actual sending rather than queuing or intention to send. So, if there are 100 potential contacts to email, it shows 0 sent until they are sent, and the Actions tab shows how many of the 100 are sent (say 90 sent 10 not sent, do not send etc) and the chart shows 90.

**Comment by RCheesley** [comment]
This was addressed with #4628 some time ago, so closing this issue down
