### ISSUE TITLE
Bug making editing with campaign builder a pain, can not add and remove event in one campaign edit session.

### ISSUE THREAD

**Issue by marcel-ambta** [mautic/mautic#4530]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
On editing a campaign you can not add and delete a decision/action or conditions without saving first, if you do that you will run into an arror, tested on 2.8.2 and 2.9.0. Tried on different servers/php versions and Mautic versions. Seems like the event does not get removed from the session while deleting it.

Will investigate futher tommorow if not solved. 

## Related threads/issues:
https://www.mautic.org/community/index.php/7488-mautic-critical-error/0
and issue #3240

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.8.2 >
| PHP version |  7 / 5.6

### Steps to reproduce:
1. Create new campaign/edit existing campaign
2. Open campaign builder
3. Add decision/action or condition and remove it
4. Save the campaign

## Error log

`mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'UPDATE cx_ax_campaign_events SET parent_id = ? WHERE parent_id IN (new7c2d80ec9d800b66f9802d7f14628386c2220dd7)' with params [null]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'new7c2d80ec9d800b66f9802d7f14628386c2220dd7' in 'where clause'" at /mnt/bigstorage/home/id24581/domains/cxma.nl/private_html/axians/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'UPDATE cx_ax_campaign_events SET parent_id = ? WHERE parent_id IN (new7c2d80ec9d800b66f9802d7f14628386c2220dd7)' with params [null]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'new7c2d80ec9d800b66f9802d7f14628386c2220dd7' in 'where clause' at /mnt/bigstorage/home/id24581/domains/cxma.nl/private_html/axians/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'new7c2d80ec9d800b66f9802d7f14628386c2220dd7' in 'where clause' at /mnt/bigstorage/home/id24581/domains/cxma.nl/private_html/axians/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'new7c2d80ec9d800b66f9802d7f14628386c2220dd7' in 'where clause' at /mnt/bigstorage/home/id24581/domains/cxma.nl/private_html/axians/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} [] `

**Comment by escopecz** [comment]
Please upgrade to the latest version and test again. There is a great chance it was fixed already. But maybe wait a day or two. 2.9.1 should be released in that time with even more bug fixes. Let us know if you still have this problem with the latest version, please.

**Comment by marcel-ambta** [comment]
@escopecz Tried the master branch without success, narrowed it down to the deleteEvents function in the EventModel, if a event that is not in the database yet gets into the deletedKeys array the nullEventRelationships function will throw an error. (Because of the query).

File: CampaignBundle/Model/EventModel.php, line 218

Temporary quikfix: change CampaignBundle/Entity/EventRepository.php function nullEventRelationships (line 511) to: 
`/**
     * Null event parents in preparation for deleting events from a campaign.
     *
     * @param $events
     */
    public function nullEventRelationships($events)
    {
        foreach($events as $key => $event) {
            if(substr($event, 0, 3) === "new") {
                $result = $this->findOneBy(['tempId' => $event]);

            } else {
                $result = $this->findOneBy(['id' => $event]);
            }

            if(empty($result)) { unset($events[$key]); }
        }

        if(!empty($events)) {
            $qb = $this->getEntityManager()->getConnection()->createQueryBuilder();
            $qb->update(MAUTIC_TABLE_PREFIX.'campaign_events')
                ->set('parent_id', ':null')
                ->setParameter('null', null)
                ->where(
                    $qb->expr()->in('parent_id', $events)
                )
                ->execute();
        }
    }
`

The best solution would be altering the querybuilder to only take events that exists in the datatabes 
@PH-Lars will look into that tommorow.

**Comment by marcel-ambta** [comment]
There also is a problem with editing events and then deleting them, the event won't be deleted but will be disconnected from the other campaigns. This all has to do with the events.deleted and events.modified list, i will submit a merge request.
