### ISSUE TITLE
Mautic Lookup empty with Fullcontact

### ISSUE THREAD

**Issue by HiveMindNet** [mautic/mautic#4531]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When trying to update lead information using the fullcontact (or other) integrations, no data is passed unless the lead has an email address, (which obviously most don't that come from twitter)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.0
| PHP version | 7.0.19-1+deb.sury.org~trusty+1

### Steps to reproduce:
1. Click lookup unload using fullcontact
2. See the popup box lacks any lead information
3. No data is returned even though fullcontact connection is successful and lookup is registered on their website dashboard
4. Lookup works fine with twitter handle using their API test on the website dashboard
 
### Log errors: 

This is all I see in the Mautic log
[2017-07-27 09:00:42] mautic.NOTICE: PHP Notice - unserialize(): Error at offset 174 of 255 bytes - in file /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php - at line 58 [] []

Syslog is empty

Apache log contains
[Thu Jul 27 08:41:09.932085 2017] [:error] [pid 16840] [client 86.165.26.221:52065] PHP Notice:  unserialize(): Error at offset 174 of 255 bytes in /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58, referer: http://MYDOMAIN.com/s/dashboard
[Thu Jul 27 08:59:37.693085 2017] [:error] [pid 17145] [client 86.165.26.221:56608] PHP Notice:  unserialize(): Error at offset 174 of 255 bytes in /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58, referer: http://MYDOMAIN.com/s/companies
[Thu Jul 27 09:00:42.402978 2017] [:error] [pid 17145] [client 86.165.26.221:56878] PHP Notice:  unserialize(): Error at offset 174 of 255 bytes in /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58, referer: http://MYDOMAIN.com/s/contacts/view/1630
root@LIVE:/var/log/apache2#

**Comment by npracht** [comment]
The plugin will be fully re-written with #8783 as far as API changed and the current plugin does not work anymore. I'll close the issue because it is not relevant anymore on the current version (not working at all).
