### ISSUE TITLE
landing pages with forms not working on 2.9.1

### ISSUE THREAD

**Issue by ecoitsolutions** [mautic/mautic#4533]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | 
| Enhancement? | 

## Description:
After updating to 2.9.1, landing pages containing a form are not working anymore
## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.9.1
| PHP version |  7.0

### Steps to reproduce:
1.  Update to latest version, checked migrations and everything
2.  Preview a landing page that contains a form will throw a 500 error.
 
### Log errors: 

[2017-07-27 23:04:33] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getFieldValue() on null - in file app/bundles/FormBundle/Model/FormModel.php - at line 765

**Comment by ecoitsolutions** [comment]
i forgot to mention, this error occurs only if logged-in. Preview as a guest (not logged-in) works without problems.

**Comment by escopecz** [comment]
I cannot replicate anyhow. I have a Mautic landing page with a form, but it loads without any problem when I preview it when logged in as a Mautic user. The error message would suggest that it should pre-fill the form value. So I configured a field in the form to "Auto fill data". But still no error. Can you please double check the steps needed to replicate the error?

**Comment by raribeiro** [comment]
@escopecz same error here after update to 2.9.1. After updating to 2.9.1, landing pages containing a form are not working with the user logged.

**Comment by escopecz** [comment]
How about 2.9.2? It contained one bug fix in this area.

**Comment by KJURKOWSKIHCS** [comment]
@escopecz I had the 500 error page problem upon form submit on 2.9.1, now upgraded to 2.9.2, no longer a 500 error when submitting, but now the form just hangs upon submit

**Comment by escopecz** [comment]
Take a look at the troubleshooting to rule out a configuration issue: https://mautic.org/docs/en/forms/index.html#form-troubleshooting

If it won't work for you after that either, there must be some error recorded somewhere. Either look at the dev tools console or to Mautic or server logs.

**Comment by escopecz** [comment]
I'll close this issue since it was fixed in 2.9.2

**Comment by gingerling** [comment]
May be related to https://github.com/mautic/mautic/issues/4652

**Comment by gingerling** [comment]
I guess someone called toto is testing right now :)
