### ISSUE TITLE
Cannot log into Mautic

### ISSUE THREAD

**Issue by Subesrao** [mautic/mautic#4534]
![image](https://user-images.githubusercontent.com/28031807/28699432-3370d652-737c-11e7-837b-03971efdd12a.png)
its showing this message after i update to 2.9.1 version. How to solve this issue

**Comment by aviboy2006** [comment]
Clear your cache and check apache log for this.

**Comment by escopecz** [comment]
Please read https://mautic.org/docs/en/tips/troubleshooting.html before creating a new issue.

I'll close this one since it doesn't provide any information asked in the issue template.
