### ISSUE TITLE
2.9.1 Migration fails due to is_primary column

### ISSUE THREAD

**Issue by FabianTe** [mautic/mautic#4539]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I tried updating mautic from version 2.8.2 to 2.9.1. This might be two errors actually:

## is_primary column missing
A table is missing the column ```is_primary```This error was also reported by slack users *frubio* and *kedar*:

- https://mautic.slack.com/archives/C02HU8BUT/p1501234620002786
- https://mautic.slack.com/archives/C02HU8BUT/p1501214585062446

The error message
```
[2017-07-27 20:51:47] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'insert into companies_leads (company_id, lead_id, date_added, manually_added, manually_removed) SELECT c.id, l.id, '2017-07-28 03:51:47', 0, 0 from leads l join companies c on c.companyname = l.company ON DUPLICATE KEY UPDATE company_id = c.id;': Field 'is_primary' doesn't have a default value (uncaught exception) at /home/nthwav8/public_html/email.9thwave.surf/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 while running console command `doctrine:migrations:migrate` [] []
```

Because of this error I tried to migrate doctrine

## Doctrine Migration 

I followed John's guide: https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

```php app/console doctrine:schema:update --dump-sql``` and ```php app/console doctrine:migrations:migrate``` produced this error:

```
PHP Warning: require_once(/var/www/html/mautic/app): failed to open stream: No such file or directory in /var/www/html/mautic/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/StaticPHPDriver.php on line 115 PHP Fatal error: require_once(): Failed opening required '' (include_path='.:/usr/share/php') in /var/www/html/mautic/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/StaticPHPDriver.php on line 115
```

... accompanied by the error ```Failed opening required '' ``` -> Why is ```''``` empty?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.18-0ubuntu0.16.04.1

### Steps to reproduce:
1. Run ```mautic:update:apply```
2. Couldn't open contacts. Got some SQL error in mautic.
3. Run ```doctrine:migrations:status``` -> I need to migrate
4. Run ```doctrine:migrations:migrate```

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/4538
