### ISSUE TITLE
Colour code/assign icons to campaign actions and decisions

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#454]
When viewing a complex campaign it's difficult to distinguish between the different types of actions and decisions.  It would be very helpful to be able to set colour coding for those different aspects of a campaign to aid easy identification.

**Comment by RCheesley** [comment]
And/or - have an icon?  Might be an alternative but that has space implications I guess

**Comment by that0n3guy** [comment]
Per my previous feature request #841, I think we should have labels b/c the name field is limited to how many characters actually display.

Something like (red arrow points to the label): 
![image](https://cloud.githubusercontent.com/assets/113870/10046590/31b8308c-61cf-11e5-849e-b7fc9953abf2.png)
