### ISSUE TITLE
Feature Request: Unpublish form after X submits

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#4549]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:

Will be great Mautic has a ability to expire or hide an form after X submissions. Works great with events, cupons, etc.

**Comment by escopecz** [comment]
This is actually duplicate of https://github.com/mautic/mautic/issues/1775
