### ISSUE TITLE
[bug] Site URL is using https:// but landing page preview is http://

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#455]
It looks as though there might be a hard-coding somewhere, as my landing page previews are all using http:// instead of https:// - which is set in global configuration as the site URL.

**Comment by alanhartless** [comment]
Are you accessing Mautic via https? Symfony generates the URLs based on the current request. We'll be adding a check to redirect to https if the site url includes it.  Right now the site url really only affects URLs generated through a CLI command (since CLI isn't running through a web server).

**Comment by RCheesley** [comment]
Yes, that seemed to be the problem.  If the site is set to https why wouldn't you want to log in as https?  Can it be something that has an option to be forced in the admin area?

**Comment by alanhartless** [comment]
The plan is to force https if the site URL is set to be https in configuration.  That setting is currently only used when generating links in emails via a cron job (for example, kicking off campaigns).
