### ISSUE TITLE
Unable to delete saved Dashboard - need to separate user dashboard files from default

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4550]
| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | Yes

## Description:
It is easy to save a dashboard/homepage using the save button.
Mautic only ask for a name

Saved dashboards are then listed within the Import section of the module
It seems it is impossible to delete them ?

Is there a way for the user who created the template (or an admin) to have a UI link to easily delete the template ?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.12

**Comment by alanhartless** [comment]
I changed this to a bug. The feature exists but it is not activated unless dashboard user files are configured to be stored separately from the default dashboard files. If `dashboard_import_user_dir` is configured in the app/config/local.php and is something different than `dashboard_import_dir`, then Mautic will detect the files as `user` and thus allow them to be deleted. 

To fix the bug, we should separate user dashboard files by default.
