### ISSUE TITLE
Segment Filter not working properly. 2.9.1

### ISSUE THREAD

**Issue by a1exe1** [mautic/mautic#4551]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
Created Segment with filtering is not working.
Notice that in the Stage points there where zeros by mistake. 
After creating new with the same filters - wvrthing is ok

Filter is by Stage field. 
![noble filter not create new](https://user-images.githubusercontent.com/6849980/28824636-9cea9e22-76cb-11e7-9471-e0319f89e97d.jpg)
![noble filter not working](https://user-images.githubusercontent.com/6849980/28824635-9ce8ad42-76cb-11e7-8beb-865c9b159133.jpg)
![noble filter](https://user-images.githubusercontent.com/6849980/28824637-9cecd76e-76cb-11e7-86cf-2107748ffcbb.jpg)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Could you test https://github.com/mautic/mautic/pull/4544 if it fixes your problem? It fixes several segment bugs.

**Comment by escopecz** [comment]
Is it working on 2.9.2 for you?
