### ISSUE TITLE
[bug] information being sent over a non-encrypted connection?

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#456]
When submitting a form on an https:// landing page, it throws a warning about submitting over a non secure connection and then when it directs to the asset, it's back on a non-https:// connection again.

**Comment by alanhartless** [comment]
I think this is related to #455.  Right now, you have to be accessing Mautic via https when you save the form to force it to have an action with https as well.

**Comment by RCheesley** [comment]
Logged in as https and saved form - session had reverted to non-https - thank you
