### ISSUE TITLE
Import crashes when one or more lines in the CSV contain non-ASCII characters

### ISSUE THREAD

**Issue by corradofiore** [mautic/mautic#4561]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |   O
| Feature request? | 
| Enhancement? | 

## Description:
When trying to import a CSV that contains non-ASCII characters like the one I'm attaching, Mautic import crashes:

````
/usr/bin/php  /home/webmaster/htdocs/mautic/app/console  mautic:import
Import 1 with 15 is rows starting.
  1/15 [=>--------------------------]   6%

  [Doctrine\ORM\ORMException]   
  The EntityManager is closed.  
````

SAMPLE FILE that triggers the crash:  [crasher.csv.txt](https://github.com/mautic/mautic/files/1192702/crasher.csv.txt)

The encoding of the file, as per BBEdit, is "Mac OS Roman".  I received it from a client who supposedly used Excel on Mac to produce the CSV.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.1
| PHP version | 7.0.16

### Steps to reproduce:
1. Import the CSV file attached above in Mautic contacts.

### Log errors: 
````
[2017-08-02 04:54:15] mautic.NOTICE: Doctrine\ORM\ORMException: The EntityManager is closed. (uncaught exception) at /home/webmaster/htdocs/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php line 144 while running console command `mautic:import` [] []
````

**Comment by npracht** [comment]
Also noticed here !

Envoyé de mon iPhone

**Comment by escopecz** [comment]
Well, we have [in the docs](https://mautic.org/docs/en/contacts/import.html) that only UTF8 encoded files can be imported. But I'll leave this open if any dev would like to take a look at converting different encodings. I've been there. PHP is terrible in guessing a file encoding.

**Comment by corradofiore** [comment]
Thanks for chiming in.  Let me explain a bit more in detail the rationale behind this issue.  What I meant were really two things:

1.  Usability - it's often non-technical people (e.g. secretaries) who do the import, so it's difficult for them to even understand what a character set is.  It's a programmer concept.  So, when importing fails, the problem requires the intervention of the agency - clients cannot figure it out themselves.  Agencies who are trying to push Mautic to their client base might be scared by such a perspective.

1.  Engineering - I agree that file encodings can be problematic when you work in PHP.  However, Mautic shouldn't crash like that when the uploaded file is unparseable.  At the very least, there should be a message saying "this file cannot be read" or something similar.

HTH

**Comment by corradofiore** [comment]
This class is written in 100% PHP and seems to adopt an interesting approach:  https://github.com/neitanod/forceutf8

**Comment by RCheesley** [comment]
Closing as this is no longer reproduced in 2.15.3 - an error is displayed: The file is not encoded correctly into UTF-8.
