### ISSUE TITLE
Dynamic content request blocks campaign process

### ISSUE THREAD

**Issue by FabianTe** [mautic/mautic#4562]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I can't create a campaign for testing dynamic content. I followed the [documentation's guide](https://mautic.org/docs/en/dwc/index.html). My campaign has the wanted contacts but doesn not execute the dynamic content request action.

Removing the dynamic content request works, my campaigns and segments also work fine. Issue has to be related to the dynamic content usage.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.18-0ubuntu0.16.04.1

### Steps to reproduce:
1. Create basic dynamic content. May contain an asset link / text / contact field (neither work)
2. Create a landing page with a dynamic content shortcode
3. Create an email which holds a link to the new landing page
4. Create the following campaign:

```
Test Segment -> Request dynamic web content -> Send the new Mail
```
 
### Log errors: 
*None*

**Comment by escopecz** [comment]
We would need exact steps you use for testing. Also the screenshot of your campaign flow would be useful. Any JS or PHP error when the contact should execute the dynamic content? Do you test in a browser where you are not logged in to Mautic?

**Comment by FabianTe** [comment]
### Errors?
> Any JS or PHP error when the contact should execute the dynamic content? Do you test in a browser where you are not logged in to Mautic?

There are no PHP errors on the server. I do not receive a mail from the system, so I am not even at that stage yet.

I could add more pictures but that's just useless clutter. I can ensure you that my contact is added to the campaign but neither the mail send action nor the dynamic web content request decision is executed.

### Campaign
![image](https://user-images.githubusercontent.com/7669818/28864217-1de86518-776c-11e7-86ed-f6d1c895b007.png)

### Dynamic Content Text
```
{assetlink=1}
```

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by Sharmadivya1** [comment]
How to integrate the shortcode if the content is like this 
**Hi {leadfield=firstname}, This is the checklist designed especially for {leadfield=companyname}. Fill out the form and get the content.**

The landing page is not hosted in mautic. How will they replace the first name and other fields? Need help with this.
