### ISSUE TITLE
Notes creation on contact : False count

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4563]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Go on a contact with 0 Notes
Create a note (choose any type and date)
Save

The note is created but the count on the tab is false (it displays 2 instead of one)
Refresh screen : the count is now ok (one)

Each time a new note is entered the counter is incremented of two until the screen is refreshed

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.12

**Comment by escopecz** [comment]
Fixed in 2.9.1

**Comment by YannickBiet** [comment]
sorry i searched for that in the repo before submitting :(

**Comment by escopecz** [comment]
For the reference: https://github.com/mautic/mautic/issues/4469
