### ISSUE TITLE
Contact's Notes filter ?

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4564]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
We entered multiples notes on a contact
We can use the type checkboxes to filter the list of notes
but as soon as we try to type any text in the filter all notes vanishes.
I am not sure the filter is working as expected.

Example of notes recorded, focus on the call i want to search all notes with texte "call"

![1](https://user-images.githubusercontent.com/930391/28867491-96dbe4f4-7776-11e7-84a7-f70b3c5a0bf5.PNG)

But no results : 
![2](https://user-images.githubusercontent.com/930391/28867492-96e344c4-7776-11e7-8163-751174e78ce3.PNG)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.12

**Comment by escopecz** [comment]
It searches only for the text from its beginning. If you'd search for `I`, it would find your note. If you'd want to search for any word in the notes like `call`, use the wildcards like this: `%call%`. This is a speed optimisation. The discussion whether to have a fast search or easier to use search are discussed in https://github.com/mautic/mautic/issues/2808.
