### ISSUE TITLE
Campaign may not work when using a campaign form as a "contact sources" on the campaign builder.

### ISSUE THREAD

**Issue by kolinz** [mautic/mautic#4565]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description & Steps to reproduce:
campaign may not work when using a campaign form as a "contact sources".
In the case of contact is already registered.  
create campaign by campaign builder
1. Contact Sources : campaign form.
1. Add Condition : Form Filed Value , use custom filed (text type).
1. Add Action : Add contact to segments & wait 1 hour Remove contact from segment.
1. Some people post to  campaign form.

But, "Campaign action triggered" is not displayed on the contact screen. Probably , campaign seems not be working.

![campaign_builder_capture](https://user-images.githubusercontent.com/16685896/28900671-e318e42c-782d-11e7-8511-42ee94e7c6eb.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.1 & Mautic Cloud Free
| PHP version | PHP 7.1.7 (Mautic 2.9.1)
 

### Log errors: 
In the case of Mautic Cloud Free
Mautic Cloud Free can not see the error because there is no System Info menu.

In the case of Mautic 2.9.1
mautic.NOTICE: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT count(l.id) as lead_count, max(l.id) as max_id FROM leads l LEFT JOIN lead_lists_leads ll ON (ll.leadlist_id = 8) AND (ll.lead_id = l.id) AND (ll.date_added <= '2017-08-03 00:15:03') WHERE ((l.email NOT LIKE :dOySElmC) OR (l.email IS NULL)) AND (ll.lead_id IS NULL)':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':dOySElmC) OR (l.email IS NULL)) AND (ll.lead_id IS NULL)' at line 1 (uncaught exception) at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 while running console command `mautic:segments:update` [] []

**Comment by escopecz** [comment]
This should be fixed in Mautic 2.9.2. Can you test and confirm?
