### ISSUE TITLE
getAssetUrl not working when sending e-mail

### ISSUE THREAD

**Issue by zhakid** [mautic/mautic#4568]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
{{ getAssetUrl('path', null, null, true) }} doesn't work when sending emails the images is broken and on the builder too

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.1
| PHP version | 7.1.5

### Steps to reproduce:
1. Campaings -> Email
2. Create a email and send it to you( as example i use Oxygen)
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
1. Do you have the Site URL field in the Mautic configuration filled in correctly?
2. What URL does it produce and what URL do you expect?

**Comment by viryagroupdev** [comment]
1. Do you have the Site URL field in the Mautic configuration filled in correctly?
http://mautic.dev/index.php

2. What URL does it produce and what URL do you expect?
http://mautic.dev/index.php/theme/img.ext
i don't what to expect when i try to enter to the url of the image give a page no found mautic message

**Comment by escopecz** [comment]
The problem here is the `/index.php` part. It should not be there. If it is there it means that either mod_rewrite or .htaccess are not enabled on your server. Doublecheck that it is and then Mautic should work without the `/index.php` part in the URL. Don't forget to update Site URL afterwards.

**Comment by viryagroupdev** [comment]
Thanks!!! that was the problem!
