### ISSUE TITLE
Config flag to prevent mautic notification for updates

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4569]
| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
Currently the "new version available notification" is displayed for every admin user + all users having permission 'has full system access'

For technical reasons (like stability, functionnal limit even to power users like mautic administrators) upgrading an IT software should be reserved to IT personns given a certain schedule, ....

We would love to be able to disable this notification whatever the role (admin / simple user with full system access) by adding a flag in the config file of mautic like "disable_newversion_notification"

What do you think about that ?
Good idea ?

**Comment by escopecz** [comment]
I went through the code and it seems there is such parameter already: https://github.com/mautic/mautic/blob/staging/app/config/security.php#L241

What I understand from the code, it should work like this:
1. Copy the app/config/security.php to app/config/security_local.php. This way your change will not be overwritten during the upgrades.
2. Change the last row from `$container->setParameter('mautic.security.disableUpdates', false);` to `$container->setParameter('mautic.security.disableUpdates', true);`.
3. Clear the cache.
