### ISSUE TITLE
Use Contact's Send Email button does not send attachments linked to the template

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4570]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | Yes
| Enhancement? | No

## Description:
In Mautic 2.8.2 if you want to send a direct email using "send mail" button on contact detail view, a popup weill appear
User is invited to enter the subject and body OR select an existing defined email template (it is only Template Email and not Segment Template email). 

Selecting a template replace the WYSIWYG editor content with template one
You can then send the email

Problem is that if you're using a template in which an attachment (or many) have been added to advanced tab, the sent email will only have the template's body without any attachment.

Of course my template email works fine if i am pressing "send example" button from the email detailview .

For me and user's point of view, it is a bug, but I think that mautic's send email popup simply does not support attchment (so it could be a FR as well)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.12

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
