### ISSUE TITLE
Sugar/Suite Integration doesn't push; it only pulls

### ISSUE THREAD

**Issue by HiveMindNet** [mautic/mautic#4571]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When issuing the console command './console mautic:integration:synccontacts --integration=Sugarcrm' the integration with SuiteCRM successfully pulls new/changed contacts from the CRM. HOWEVER, when new contacts are created in Mautic, nothing is pushed to CRM, (although the options to pull and push are selected in the integration). All appropriate fields are mapped.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.1  (also doesn't work in 2.9.0)
| PHP version | 7.0.19-1+deb.sury.org~trusty+1

### Steps to reproduce:
1. Set up the SugarCRM integration for Suite (using Sugar 6 options)
2. Add/edit contact in Suite to test
3. Add new contact to Mautic
4. run console mautic:integration:synccontacts --integration=Sugarcrm
5. Sync from crm to Mautic works, from Mautic to CRM does not 
 
### Log errors: 

No applicable log entries.
Feedback from console command when run is;

Push activity timeline to Sugarcrm mautic object
Number of contacts processed: 0

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/4445

**Comment by HiveMindNet** [comment]
I tried the mods in #4445 and it throws the following on a contact sync

PHP Notice:  Undefined variable: RECORDS_LIST_NAME in /path/to/mautic/plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php on line 854

**Comment by escopecz** [comment]
It's still Work In Progress. But if you find some problem testing a pull request, it would help a lot to comment directly to that pull request so the author would know about it.

**Comment by HiveMindNet** [comment]
Thanks @escopecz - I'm still new to github so will go work that out.

**Comment by HiveMindNet** [comment]
@escopecz - apologies if I'm off track here but I'm not convinced that the issues with SuiteCRM in this bug are related to 4445. Having worked through it the symptoms are not really the same. For example, when a contact is sync'd from CRM to Mautic, even though the sync is done in the feedback from the console run it still suggests that it's pulling the sync contact each time (even though it's not changed). It's like after the sync it's not being marked as sync'd somehow.

On the fetch it says as below every time even without change on the CRM

Command to fetch contacts from integration
Fetch contacts command is starting
Fetching contacts...
Number of leads/contacts fetched: 1
