### ISSUE TITLE
Companies Merge : not working like Contact's merge

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4572]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | Yes

## Description:
If you want to merge Contact2 on Contact1 :
- non empty fields of contact 2 will always replace Contact 1 fields
- Resulting Points are the sum of Contact1 + Contact2

If you want to merge Company2 on Company1 :
- **only Empty fields** of company1 are replaced by non empty field of company 2
- Score of companies 1 and 2 are not summed up
- Score of company 2 is lost

Merging company2 over company1 results in loosing most of the data information of company2 

This is not so logicall isn't it ?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2 and reproduced in 2.9.0
| PHP version | 7.0.12

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
