### ISSUE TITLE
Issue in campaign Trigger

### ISSUE THREAD

**Issue by aviboy2006** [mautic/mautic#4575]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
We are facing some issue while running campaign on lead for stages/ or any other activity. Our business requirement is that that we have a offer going on for one month. A customer comes clicks on the offer, which triggers a campaign in mautic where the customer is moved to a "hot" customer. But if customer doesnt do any action for 2 days we move the customer back to "cold" customer. Now the customer comes back after 7 days and again clicks on the offer. The business expects that the campaign should run again and it should move the customer to "hot" again. This doesnt happen currently in mautic.

Reason : campaign_lead_event_log checks worked based on event_id and lead_id. whenever same campaign running on same lead its doesn't work because on same lead campaign ran first time while converting cold to hot stage. Ideally as campaign manager same lead can come multiple times campaign should trigger multiple times. But this is not working.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Create two segment for "To-Hot"  include all cold/warm lead based on some condition
2. Create two segment for "To-Cold"  include all Hot lead based on some conditon ( like 30 days old lead)
3. Run two campaign, one is one "To-Hot" and another on "To-Cold" segment and change stage respectively.
4. First time campaign will run to convert cold/warm lead to hot.
5. Second after 30days or any other condition will move that lead to again cold.
6.Then it should convert to hot once get another communication from customer. But this is not working 
because that same lead already triggered by campaign. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
That's not a bug. Currently a contact can go through campaign events only once to make sure he doesn't get the same email several times for example. The feature request for recurring campaigns is here: https://github.com/mautic/mautic/issues/1606
