### ISSUE TITLE
Campaign Builder > Send email to someone else than the contact

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4584]
| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | Yes

## Description:
Campaign builder action list allow user to send an email to the contact

But how can we send a notification to contact's owner, or to someone else (maybe even hardcoded email address) in order to let them know about the contact's workflow progress ?

Seems impossible today in 2.9.

**Comment by escopecz** [comment]
See https://github.com/mautic/mautic/pull/4458

**Comment by FabianTe** [comment]
What about sending the mail to a mail address defined by a contact field? This might have limited purposes  though.

**Comment by YannickBiet** [comment]
Seems this is the aim of #4458

**Comment by FabianTe** [comment]
> Or maybe you're talking about embedding a second email address inside the contact data.... in deed we could create another custom field of type email to store an extra info

That's what I meant. Imagine the contact has a custom select field with your companies employees mail addresses. This would enabling sending a mail like "This contact needs your attention" to someone other that the contact's owner.

**Comment by YannickBiet** [comment]
This one could be slightly different as using a custom email address for that is not really beautiful

For our Customers CRM implementation we usually duplicate the relation to the Users module : one for the sales rep, one for the project manager, one for Administrative stuff and so on....

This way we have clear and proper fields to select Software's users and then we use the email address defined on the user's card directly

Not sure Mautic allows us currently to create new fields that list Mautic Users to do the same
