### ISSUE TITLE
500 / Out of memory error on form submission

### ISSUE THREAD

**Issue by mackina** [mautic/mautic#4585]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

When submitting a form a 500 error appears in console and form is not submitted.  Looking at apache logs this is thrown on submission:

 [client 10.0.3.73:42886] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/nudgr.io/vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1, referer: https://www.formisimo.com/request-demo

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.12

### Steps to reproduce:
1.  Add a form to a web page
2.  Submit the form
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Please increase the memory limit configuration at your server setting to at least 500 MB. 268 MB is too small limit for Mautic. If you still have problems with 500 MB limit. I'll reopen.

**Comment by mackina** [comment]
Upgraded server, increased limit to 512 and now works. 512MB is a lot to suck up from one thread!
