### ISSUE TITLE
Segments > User with now edit rights still has the publish icon in list view

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4597]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
I have created a limited role profile and only gave the view others rights for Segments
I can then list the segments but can't access them to see the filters and so on...

The problem is that I still have the publish icon in list view and if i am cliking it of course i can't unpublish the segments

But as i have no rights, the shortcut icon should either not be present or not allow to click on it
Currently an Ajax call is made and the lading circle will be displayed until we refresh the page (the ajax call is return success :0 but UI is not updated)

Maybe the system is a system-wide problem where the publish icons are not conditonned to the rights of the user ?

## If a bug:

| Q   | A
| --- | ---
| Mautic version |2.9.0
| PHP version | 7.0.12

**Comment by npracht** [comment]
I know it has been fixed in the past
