### ISSUE TITLE
Upcoming email widget with admin is empty

### ISSUE THREAD

**Issue by captivea-ylb** [mautic/mautic#4602]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Upcoming Email widget in dashboard return just mail where owner is current user (and nothing if user have not mail), and this even if user is Administrator has full system access.

After search in code i find a bug in function getUpcomingMail (file app/bundle/CampaignBundle/Entity/LeadEventLogRepository.php). The condition test just if variable canViewOther not exist but not if canViewOther is false. 
`        if (!empty($options['canViewOthers']) && isset($this->currentUser)) {
            $query->andWhere('c.created_by = :userId')
                ->setParameter('userId', $this->currentUser->getId());
        }`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.20-1

### Steps to reproduce:
1. Connect with user full granted and without mail with owner is this user, 
2. Go to dashboard, add widget "Upcoming email" and see.
 
### Log errors: 
No errors logs

**Comment by YannickBiet** [comment]
Please note DarkSark73 is member of @captivea

Captivea made the pull request to mautic repository yesterday : https://github.com/mautic/mautic/pull/4603

Waiting for review and inclusion in a firther release of Mautic
