### ISSUE TITLE
[bug] clone form fail

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#461]
When I clone a form, I expect to clone all actions. 

I cloned a form and the "create/update lead action" don't copy the "Mapping of the form fields to the lead fields". It was empty after clone the form. 

More information:
Simple Form to subscribe mailing list.
When I push clone before save the new form the assignment is in the create/update action. But when I save the new form without changes it loses all assignments.

**Comment by alanhartless** [comment]
Is this still an issue in the latest release?

Thanks,
Alan

**Comment by miguelpascual** [comment]
I tested and It Works well
