### ISSUE TITLE
Twitter generic error on tweet send

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4614]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | no
| Enhancement? | no

## Description:
Fresh install of 2.9.2
Enable the twitter integration / authorized my twitter app
Created a tweet message names "tweet1" body "this is a sample tweet message"
Created a dummy public segment - no filters
Created a campaign based on segment - used segment 1
added an action "tweet contact" and selected "tweet1"
published the campaign
Created a contact with twitter nickhandle
Manually trigger the campaign thanks to campaign popup on the contact
Run the cronjob to launch the triggers (no errors/warning)
Got the tweet in activity line BUT in error (Generic error) and of course no tweet really sent

![capture](https://user-images.githubusercontent.com/930391/29069166-095e89f6-7c3a-11e7-8360-0d7d848641fd.PNG)

No error in log files

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.12

**Comment by vexersa** [comment]
Are there any updates on this? I'm getting the same error.

**Comment by vexersa** [comment]
UPDATE: 
When using the cloud version (mautic.com) of this setup it works as expected.

**Comment by vexersa** [comment]
Received error when manually running "app/console mautic:social:monitoring":

An exception occurred while executing 'INSERT INTO leads (is_published, date_added, created_by, created_by_user, date_modified, modified_by, modified_by_user, checked_out, checked_out_by, checked_out_by_user, points, last_active, internal, social_cache, date_identified, preferred_profile_image, title, firstname, lastname, company, position, email, phone, mobile, address1, address2, city, state, zipcode, timezone, country, owner_id, stage_id) 

AND

SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x90\x9D";...' for column 'social_cache' at row 1

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Comment by drptiago** [comment]
This error still in Mautic 3
I believe is related to emojis


An exception occurred while executing 'INSERT INTO ma_audit_log (user_id, user_name, bundle, object, object_id, action, details, date_added, ip_address) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [0, "System", "lead", "lead", 21732, "create", "a:3:{s:6:\"fields\";a:4:{s:3:\"elo\";a:2:{i:0;N;i:1;s:15:\"thinkgrowrichs2\";}s:8:\"lastname\";a:2:{i:0;N;i:1;s:132:\"\u1d0d\u1d27\u1d0d\u1d27\u2729\u22c6\u00a8\u1d2f\u1d49\u1d43\u1d58\u1d57\u02b8\u2734\ufe0e\u1d33\u1d43\u02e2\u1d57\u02b3\u1d52\u207f\u1d52\u1d50\u2071\u02e2\u1d57\u263d\ud83c\udf4b\u1d39\u1d52\u207f\u1d49\u02b8\u02e1\u1d52\u1d5b\u1d49\u02e2\u1d50\u1d49\ud83c\udfdd\ud83d\udcb5\ud83d\udcb0\ud83d\udcb3\";}s:6:\"comcob\";a:2:{i:0;N;i:1;s:5:\"False\";}s:6:\"temcob\";a:2:{i:0;N;i:1;b:0;}}s:8:\"lastname\";a:2:{i:0;N;i:1;s:132:\"\u1d0d\u1d27\u1d0d\u1d27\u2729\u22c6\u00a8\u1d2f\u1d49\u1d43\u1d58\u1d57\u02b8\u2734\ufe0e\u1d33\u1d43\u02e2\u1d57\u02b3\u1d52\u207f\u1d52\u1d50\u2071\u02e2\u1d57\u263d\ud83c\udf4b\u1d39\u1d52\u207f\u1d49\u02b8\u02e1\u1d52\u1d5b\u1d49\u02e2\u1d50\u1d49\ud83c\udfdd\ud83d\udcb5\ud83d\udcb0\ud83d\udcb3\";}s:14:\"dateIdentified\";a:2:{i:0;N;i:1;s:25:\"2020-08-08T06:25:29-07:00\";}}", "2020-08-08 13:25:29", "127.0.0.1"]:

SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x8D\x8B\xE1\xB4...' for column 'details' at row 1
