### ISSUE TITLE
email data inconsistent

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#462]
I have created an email 
![image](https://cloud.githubusercontent.com/assets/10166840/7799238/e486d9be-0303-11e5-93a4-f3ed27947b87.png)
probably pendent emails is due by one mistake but when i enter in to detailed information it show nos mails was send:
![image](https://cloud.githubusercontent.com/assets/10166840/7799253/0c15bdd8-0304-11e5-833f-1dcbcf8f8ab3.png)

In general it show 4 mails send and in detail 0 email sended.

**Comment by Blejzer** [comment]
I have a same problem!
![screen shot 2015-05-29 at 10 48 12](https://cloud.githubusercontent.com/assets/4067326/7879473/ffb3d12a-05f0-11e5-8788-a60bc1eb8d90.png)
And when I go into email view, I get same response:
![screen shot 2015-05-29 at 10 48 40](https://cloud.githubusercontent.com/assets/4067326/7879492/16f9586e-05f1-11e5-985f-d2b547335efd.png)

**Comment by alanhartless** [comment]
Hi guys,

This should be resolved in 1.1 now as the stats, graphs, etc should match up with the purpose of the email (list vs template).

Thanks!
Alan
