### ISSUE TITLE
Clear notifications not persisting

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#4620]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When clicking "clear all notifications", the notifications temporarily go away until a new admin page is loaded and then they appear again.

![image](https://user-images.githubusercontent.com/742579/29086831-b91dc5bc-7c28-11e7-83c9-6faec05b6abc.png)

Steps to reproduce:
1. Create an error somehow (in my case, it was a bunch of SFDC sync errors)
2. Click the notifications icon in the admin and click "Clear all notifications". The notifications will disappear.
3. Reload the page or navigate to another admin page. The notifications will re-appear. 

This is on the latest Mautic cloud.

**Comment by escopecz** [comment]
See https://github.com/mautic/mautic/issues/4495#issuecomment-317341568

**Comment by ronnieduke** [comment]
@escopecz - apologies for the duplicate. I tried searching before I posted and must have missed it. Thanks
