### ISSUE TITLE
UTM error variable

### ISSUE THREAD

**Issue by natansouza** [mautic/mautic#4622]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y 
| Feature request? | 
| Enhancement? | 

## Description:
I create on email with mautic and set the utm variables at section "Google Analytics UTM tags". 
When the url is generated the utm_campaign field is being generated as utm_name. This is a mistake because google analytics does not take this value. Is anyone experiencing this problem?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.9.2
| PHP version | 5.6.31-2+ubuntu16.04.1+deb.sury.org+1

### Steps to reproduce:
1. Create a email
2. Set UTM at Google Analytics UTM tags
 
### Log errors: 

I don't receive log error

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/4605. Ready to test.
