### ISSUE TITLE
Bounce recognition problem in bundles/EmailBundle/Helper/MessageHelper.php

### ISSUE THREAD

**Issue by AndrassGray** [mautic/mautic#4624]
What type of report is this:

| Bug report? | X

## Description:
The rule n° 234 in function parseBody() which is supposed to catch "No such user" has two problems, as far as I am concerned. My return text for a hard bounce is

```
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  nowhere@domain.com
    No Such User Here

```

The original (line 705)

```preg_match("/\s(\S+@\S+\w).*No such.*(?:alias|account|recipient|address|email|mailbox|user)>/i", $body, $match)```

1/ has a ">" to much (probably a leftover)
2/ does not catch the newline between the email address and the text.

I think this should be

```preg_match("/\s(\S+@\S+\w).*[\r\n]*.*No such.*?:alias|account|recipient|address|email|mailbox|user)/i", $body, $match)```

## If a bug:

| Mautic version | 2.9.2
| PHP version | 5.6

**Comment by AndrassGray** [comment]
Just saw that unknown domains are not caught on my system neither. I get this message `<nowhere@hsgaods45qsd5.com>: Host or domain name not found.`  which isn't covered in parseDsn().

**Comment by escopecz** [comment]
Do you think you could push your suggested code change as a pull request? This is also a good candidate for new unit tests.

**Comment by AndrassGray** [comment]
Ok. I have hacked my solution up directly on the server so far, but why not do it right. Be back as soon as ready.

**Comment by AndrassGray** [comment]
Sorted with PR here : https://github.com/mautic/mautic/pull/4638
