### ISSUE TITLE
Form doesn't hide fields if value exist using Manual Copy option

### ISSUE THREAD

**Issue by giampyart** [mautic/mautic#4625]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
If you use Manual Copy option to embed a form into an html page, it doesn't hide a field if value exist.
It works only using Automatic option and paste script into the html page.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.22

### Steps to reproduce:
1. Create a form with fields that have set on "NO" the behavior: "Show when value exists"
2. Add form into a tracked html page with the "Manual copy" option, fill it and submit
3. Check contact's info and refresh the page.
4. Form doesn't hide the fields set in step 1.

repeat step 2. using "Automatic" option and form works.
 
### Log errors: 

No logs appear

**Comment by escopecz** [comment]
That is limitation of static HTML embed: https://mautic.org/docs/en/forms/progressive_profiling.html#the-embed-type-limit
