### ISSUE TITLE
Email open stats in report not changing depending on timeframe

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4630]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

### Email detail stats
As you can see the open rate each month is variable
<img width="745" alt="capture d ecran 2017-08-09 a 16 16 53" src="https://user-images.githubusercontent.com/14075239/29126544-f333ea00-7d1e-11e7-9b54-b7ab6040c6b7.png">

### Global open rate on the email ±51% !
<img width="928" alt="capture d ecran 2017-08-09 a 16 16 34" src="https://user-images.githubusercontent.com/14075239/29126546-f4c3455a-7d1e-11e7-86b2-3a664c64ef76.png">

### Email report
As you can see, the rate is 51% no matter the time frame you set, it stays like that.
<img width="506" alt="capture d ecran 2017-08-09 a 16 16 16" src="https://user-images.githubusercontent.com/14075239/29126550-f68778de-7d1e-11e7-83ac-52836bf65f92.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version |

**Comment by escopecz** [comment]
I'm not quite sure where the last screenshot is from. Is it a dashboard widget?

**Comment by npracht** [comment]
Nope, all emails report !
