### ISSUE TITLE
Timestamp for event entries in contacts view does not use time/date-format from configuration

### ISSUE THREAD

**Issue by mobile-marketing-system** [mautic/mautic#4634]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y

## Description:
The timestamp for event entries in contact view is hard coded to "g:i a" in line 174 in file /app/bundles/CoreBundle/Templating/Helper/DateHelper.php and does not use the time/date format from the mautic config.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.22

### Steps to resolve:
Change line 174 in app/bundles/CoreBundle/Templating/Helper/DateHelper.php from

return $this->translator->trans('mautic.core.date.'.$textDate, ['%time%' => $dt->format('g:i a')]); 

to

return $this->translator->trans('mautic.core.date.'.$textDate, ['%time%' => $dt->format(**$this->formats['time']**)]);

**Comment by escopecz** [comment]
Would you mind sending a pull request with your suggestion?

**Comment by mobile-marketing-system** [comment]
Ok i just did id: https://github.com/mautic/mautic/pull/4636

P.S: I never used github bevor, so i hope my request is ok in this format :-)
