### ISSUE TITLE
Last active segment filter does not work for contact never active

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4635]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Try to make a segment for inactive people over 01/07/2017 for instance.
You'll see only people in the segment that has an activity defined. People that has never been active are not added (the value in DB is `null`).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version |

**Comment by escopecz** [comment]
The question is whether the contacts that haven't been active (for example they were imported) should be in that filter. Because I don't think so. Let's talk about use case which doesn't work for you.

**Comment by npracht** [comment]
I think in my opinion it should match. You send email to them, they never open --> they are inactive...

**Comment by escopecz** [comment]
Technically, last active and inactive is not the same thing. If you want all inactive, set the filter to Last active date: empty. I wouldn't merge inactive and active at some point in time together.

If you want both, use the active date as you need and add OR filter with empty active date.

**Comment by javiergas** [comment]
Hi @escopecz, I'm trying to create a segment including imported contacts that where never active (last_active = null in DB).

Using this filter 
![image](https://user-images.githubusercontent.com/30293899/141690150-43aa465d-0ff3-436c-be0c-8fe9fb7aa65b.png)

I get this error:
  An exception occurred while executing 'SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINC
  T l.id as leadIdPrimary, parsw.lead_id AS parsw_lead_id FROM leads l LEFT JOIN lead_lists_leads parsw ON parsw.lead_id = l.id and (parsw.leadlist
  _id = 131) WHERE ((l.last_active IS NULL) OR (l.last_active = '')) AND (parsw.lead_id IS NULL)) sss':

  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: ''


Also, if you try to set a filter using a Regexp the interfase always changes the Regexp for a date.

Using Mautic 4.0.1

**Comment by escopecz** [comment]
@javiergas it is related to MySql 8. I searched quickly and found for example https://github.com/mautic/mautic/pull/9876 which should have fix similar issue. I remember there were other similar PRs. Always make sure you run the latest Mautic version.
