### ISSUE TITLE
Data loss while Merging Contacts with multiple companies

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4641]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | no
| Enhancement? | No

## Description:
Create a contact (first name / last name) 
Assign to multiples companies (Company 1 / Company 2)

Create a second contact (first name / last name) 
Assign to multiple companies (Company 3 / Company 4)

Open Contact 1
Merge it with contact 2

Result contact only have 3 companies : Company1 Company3 Company4
Company2 is lost during merge

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.12

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
