### ISSUE TITLE
Contact Direct Email feature : Can't use Body editor (locked)

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4642]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Create a contact (firstname + email address)
Save
Press Send Email button
(Note that you can enter a body right now)
enter email's subject
Try to focus the body editor
It is locked

The Rich editor is locked as soon as you give the focus to any of the text fields that are displayed before the editor (from name / from email / subject)

You can't enter any email's body !

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.12

**Comment by escopecz** [comment]
Reported also here: https://github.com/mautic/mautic/issues/4639 a few minutes earlier.

**Comment by YannickBiet** [comment]
Ok for me, you can maybe close this one, maybe my description is a lot more accurate as it concerns not only subject but all text fields that are on the popup.

Anyway, I reported enough bugs for today :)
