### ISSUE TITLE
City/Country Form's value overwritten by IP Geocoded database 

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4643]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Feedback / Business case from one of our customer

Created a form where he wants to ask the country.
So we added a country list to our form (there's a special data type for that)
The forms displayed as usual. No problem about that

We submitted the form from France using Switzerland country
Problem is that instead of using user's submitted value, mautic permits itself to overwrite the value based on revert lookup in IP Geocode database

So even if our user (that can travel in Paris but lives in Switzerland) set its right country, we will loose the data and any campaign triggered by a segment using country will be false !

How can we change that ? (for me city/country lookup in Geocode database should be applied only if the cities / country fields are EMPTY)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.12

**Comment by YannickBiet** [comment]
Installed another instance of 2.9.2 and try to recreate the same problem. seems to have gone

The country sent by mautic form's overwrite the country information.
(and the country seems to remain even if we navigate after and after)

**Comment by stevedrobinson** [comment]
I spotted this again today using 2.15.3. Could this be back?
