### ISSUE TITLE
Contact Timeline Search not working on all activities type

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4644]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Consider the following timeline of one of our contacts
(please note this is a dummy/sample contact so the list of activities is not so logical)

![image](https://user-images.githubusercontent.com/930391/29207572-f25825ba-7e86-11e7-8bc7-9eee4d063da1.png)

We want to see only Page hits, so we selected this in the Include filter :

![image](https://user-images.githubusercontent.com/930391/29207605-1a882b0c-7e87-11e7-8a70-dd4af43065f0.png)

We wanted to refine the results by only showing when this contact visited the "page principale" webpage

We type the name of the page (as activity in timeline seems to start by the label)  but there's no results !

![image](https://user-images.githubusercontent.com/930391/29207645-4907dba8-7e87-11e7-8b04-2ead9bd85535.png)
 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.12

**Comment by RCheesley** [comment]
This seems to still be an issue in 2.15.3. If I filter by the type of activity as 'page hit' and then try to use the filter to search for either the page title or contents of the URL, it does not return any results. Other types of activity - e.g. I tested segment changes - seems to work.

https://youtu.be/qdM3TfnfbOo - testing this in a slightly older version of Mautic to see if I could reproduce

https://youtu.be/kAyNjo368Vs - testing with latest version, also checked to see if it was just page hit filtering that was a problem - it seemed that segment filtering worked OK.
