### ISSUE TITLE
Typing too fast company's name in company field results in typo errors

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4647]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
You want to add a contact to "yourcompany"

depending of user's input speed rate, the field will display other entry
problem is that a search is occured at every key stroke without any "delay" and it seems the input field is modified by the searched string data instead of not modifying it

Realworld sample using my natural keystroke speed :
![image](https://user-images.githubusercontent.com/930391/29208908-454d388c-7e8c-11e7-8d0f-15193b50dba0.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.12

**Comment by escopecz** [comment]
I cannot read what's on the image. Can you provide steps to replicate? I don't think I get what the problem is.

**Comment by YannickBiet** [comment]
Hi John,

Simply try to type really fast "YourCompany"
I type quite fast and mautic is not able to deal that : you will only get yourcmpny for example ?

letters could be overwritten and deleted

try on a base instance and enter a "quite long" company name

if you press your keyboard as fast as I am, you will not miss it :) 

Please note I am not using a local instance, so there's network access, and remote data exchange (maybe in localhost it would work perfectly ?)
