### ISSUE TITLE
Mautic Website specific base URL (User's setting to add)

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4648]
| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
Our customer is an international company
He deployed mautic and want only one (global) instance where he will create users for each subsidiaries.

For example we deploy on mautic.company.com

all assets, LP, Forms, tracker code, .... will then be related to mautic.company.com

Depending on the subsidiaries, they wanted to have the possibility to have additional URLS like :
mautic.company.com
marketing.company.fr
kampagne.company.de
yourpathtosuccess.company.co.uk

And having mautic generates all the URLs and so on based on the domain name of the current logged in user

Our idea is so quite simple :
- Keep the current mautic URL setting and consider it as ROOT.
- Add a setting like "Additional URLs available for this Mautic instance"
- And add a setting for each USER, to set which base URL to use : the system one or a "country" specific one

Thus mautic screens will be able to generate and display specific URL ready to be copied pasted into the country specific website.

**Comment by escopecz** [comment]
I'm not sure what to do with this request. Isn't it about server/DNS configuration rather than a Mautic modification?

**Comment by YannickBiet** [comment]
@escopecz if you think so you missed the idea 

let me explain myself better
Of course you can change DNS and modify the vhost to add an alias

Mautic will then answers from multiple URLS
but the problem is more on the user point of view 

take for example the Landing page URLs generated :
![image](https://user-images.githubusercontent.com/930391/29211827-99f72dac-7e9b-11e7-8bd7-da89a22d1091.png)

Mautic only generates the links using base/system URL configured

if our user is the German one, using kampagne.company.de, it will never see this link automatically generated and will have to manually change the link before pasting it to the website

I know this is quite simple to think about it and do it manually but my users requested to have the links generated automatically to the right "subsidiarie website"

**Comment by escopecz** [comment]
Aha, ok. Your example would actually work right now. It will display the URL of the website you are viewing. The URL from configuration is used for background scripts where Mautic doesn't know the URL otherwise. But it would still be configurable per user.

This is very edge feature and I wouldn't recommend it even if the URL could be configured per user. Imagine you edit a landing page as one user with one URL defined. Then you colleague which is accessing it from another URL edits it - it would change the URL of the landing page? Thant's going to cause many problems. And I'm sure I cannot even imagine most of them right now.

**Comment by YannickBiet** [comment]
perfect if it is already working as expected ! But i didn't wanted to save the url of the landing page, for me it was just dynamically displayed to the current logged-in user depending of the URL configured inside the user's profile

If it is already dyanmic without using the base setting, it is perfect and I will let my customer know this !
