### ISSUE TITLE
Time stamp in report (Date Identified)

### ISSUE THREAD

**Issue by martinstr** [mautic/mautic#4650]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
After upgrading the Mautic the Date identified is not showing the whole time stamp as it did before only date. 
And on some of the leads the date in the report is not equal to the Contact identified on the leads timeline.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version |  7.0.22

### Steps to reproduce:
1. Create a report over contacts and add the Date identified field. 
2. have a look at it 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

![mautic-timestamp](https://user-images.githubusercontent.com/19844475/29210619-a5b8303e-7e94-11e7-9497-d92de9e281aa.JPG)

**Comment by martinstr** [comment]
What's the status on this ? Still not fixed in latest release

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
