### ISSUE TITLE
Changing language (eg English USA to English UK) breaks urls

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4651]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | Y
| Enhancement? | 

## Description:
I noticed the setting the other day to change to English UK, I don't recall being offered this setting in install process etc, but was glad to change it to UK. However, today I realised that a competition I had set up in a campaign a few weeks ago had no entrants and should have. I checked the url of the competition page / form that I had linked to in the email and it was no longer working. The URL of the page / form had changed from http://ethical-pets.co.uk/m/uncategoriZed/becothings-1 to http://ethical-pets.co.uk/m/uncategoriSed/becothings-1 retrospectively. 

This really is not cool, there should be big ass warning. I am assuming now ALL places linking to Mautic pages will be incorrect, so I ether have to change it back to US or find them all and correct them.  

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 

### Steps to reproduce:
1. Make a page and copy down the URL
2. Change language to US or UK (whichever you are not using)
3. Check the original URL and find it it shows an error
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by gingerling** [comment]
Changing back has issues too - I changed back and the URLS are now live again with the Z and not the S but the links given on the landing page edit page (eg http://ethical-pets.co.uk/m/s/pages/view/8) to the page url are incorrect still.

**Comment by escopecz** [comment]
Thanks for the bug report! That is unpleasant issue. To fix the edited page, re-save it again.

**Comment by gingerling** [comment]
So to clarify, for now I put it back into USA language mode. If I put it in UK mode and then re-save each page, it will fix the issue? (I guess it creates a redirect?)

Thankyou for taking this seriously, it is reassuring :)

**Comment by escopecz** [comment]
It won't create redirects. Use USA English for now, please.

**Comment by gingerling** [comment]
Yes, ok done 😊

**Comment by gingerling** [comment]
Why is it closed? Is there a fix?

**Comment by escopecz** [comment]
Oh, I must have clicked a wrong button. Thanks for asking.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
