### ISSUE TITLE
Upcoming emails "stuck" - showing previous emails

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4654]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The upcoming emails feed on my dash is "stuck" on emails from several weeks ago and is not showing new emails. The emails it is referring were already sent, though there may have been some issues with them. The related campaigns have since been switched off. I have sent maybe 10 or 15 more emails since.
 
![screenshot from 2017-08-11 18-29-33](https://user-images.githubusercontent.com/2853040/29224770-9a4f352e-7ec3-11e7-8aa1-a6a7546ecf11.png)

It's an important thing to fix as I use it as a basis to check links are working etc in ongoing campaigns, where it may have been weeks or months since I last manually checked them. I had a major bug which broke a lot of URLS today (reported) and it would have been noticed before any issues were caused if this section was working :)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
Closing due to lack of recent activity
