### ISSUE TITLE
Segment updates based on tags (at least) does not work

### ISSUE THREAD

**Issue by cpot** [mautic/mautic#4657]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y 
| Feature request? | 
| Enhancement? | 

## Description:
Since v2.9.2 segment updates based on tags does not work anymore

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version |  5.6.29

### Steps to reproduce:
1. Create a segment based on a tag rule
2. Add the tag (or remove it) and the segment is not updated (even if cron segment update runned manually)
 
### Log errors: 

no errors in the logs

**Comment by escopecz** [comment]
I cannot replicate. I followed the steps and the correct contacts were added to the segment based on a tag rule. Can you try to create a new segment with a tag rule and try again? Maybe the problem is something else with the current segment you test with.

**Comment by cpot** [comment]
Recreating a new segment with the same tag rule solved the issue. But I had no way for the old segment to work.

However still, the "View Contact" numbers are wrong. In our case it should be '10' (can be confirmed by a contact search tag:MYTAG) and it writes '1296'. I will try to find if this bug has been recorded.

**Comment by martinstr** [comment]
It is probably your anonym contacts that is also displayd. Add filter that exclude contacts if email field is empty.

**Comment by martinstr** [comment]
I can probably confirm that the segment based tag filter not working 100%.
I have Included tag A and excluded tag B if one contact has both tags it will still be in the segment.

**Comment by cpot** [comment]
thank you very much @martinstr it worked ! (excluding empty emails)
