### ISSUE TITLE
Translate Please wait … message when submitting a form

### ISSUE THREAD

**Issue by cdevogt** [mautic/mautic#4658]
| Feature request? | 

## Description:
When submitting a Mautic form, the text in the buttons says ´Please wait …´. We use Mautic for our Dutch clients and would like to see that the text in the button is translated is the language the Mautic instance is set up. So a Dutch message in Dutch language, a German in German language and so on...

**Comment by npracht** [comment]
Related to https://github.com/mautic/mautic/issues/1536?

**Comment by escopecz** [comment]
I knew I saw it before, but couldn't find it. Thanks Norman!

**Comment by dsp76** [comment]
@escopecz the current implementation isn't working. Even for systems set to German, the English waiting message will be shown. There is a translation string available: https://www.transifex.com/mautic/mautic/translate/#de/formbundle-messages/52361781?q=text%3A'please+wait'
but it will not be applied? 

Could you please reopen it? Its not a duplicate, as the referred issue has been closed as feature request unfortunately. This is a bug however, I guess.

**Comment by dsp76** [comment]
@escopecz same is with "Choose a file" in the file picker form field. Could you please remove the "duplicate" tag. As its not a duplicate? Thanks a lot!

![chooseafile](https://user-images.githubusercontent.com/1241376/53321995-55802c00-38da-11e9-8021-7ce963ee71bb.png)

**Comment by seitzmichael** [comment]
Is there still no solution for this issue? We use our Mautic predominant in german speaking countries. And it´s not really cool to show our clients always the english waiting message.

**Comment by enguerr** [comment]
Hi, i've pushed a new pull request with language support on form creation. 
#8751
![Mautic](https://github.com/enguerr/PRDOC/blob/master/PR-1.JPG?raw=true "Mautic Open Source Marketing Automation")
