### ISSUE TITLE
Shim for Firefox date input

### ISSUE THREAD

**Issue by robwent** [mautic/mautic#4662]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? |  X

## Description:
When you use a date field in a form, Chrome, Edge and other browsers will add a date selector, but firefox just shows a text field and it's not clear which format is required.

I found a shim on SO here which works well https://stackoverflow.com/a/22987203/931438

Would this be better in the landing page template or in the actual form js so that it works when embedded anywhere?

### Steps to reproduce:
1.  Create a form with a date field and then test it in different browsers

**Comment by npracht** [comment]
Related to https://github.com/mautic/mautic/issues/1217?
