### ISSUE TITLE
Filter contacts in report by tags

### ISSUE THREAD

**Issue by martinstr** [mautic/mautic#4665]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
A feature I really miss is to create a report for contacts and directly in the report filter contacts on tags
else we have to create a lot of segments.

**Comment by kuzmany** [comment]
not finished https://github.com/mautic/mautic/pull/3134

**Comment by escopecz** [comment]
Duplicate of https://github.com/mautic/mautic/issues/995
