### ISSUE TITLE
Update to 2.9.2 using php 7.0.22 cannot view contact

### ISSUE THREAD

**Issue by robwent** [mautic/mautic#4667]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I just updated a site in siteground cloud hosting from 2.8.0 to 2.9.2.
After updating, I get a 500 error when trying to view a contact.

    mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Error: Class 'Doctrine\ORM\Query\AST\Node' not found - in file /home/blah/blah/vendor/doctrine/orm/lib/Doctrine/ORM/Query/AST/UpdateStatement.php - at line 31 [] []

and

    [2017-08-15 23:52:06] mautic.CRITICAL: Uncaught PHP Exception BadMethodCallException: "Undefined method 'u'. The method name must start with either findBy or findOneBy!" at /home/blah/blah/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php line 226 {"exception":"[object] (BadMethodCallException(code: 0): Undefined method 'u'. The method name must start with either findBy or findOneBy! at /home/blah/blah/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php:226)"} []

If I switch php to 5.6.31 then I am able to view the contact again.

After updating, I checked manually if there were any migrations waiting and they were up to date, but checking the schema, it was out of date and showed the following:

    CREATE INDEX mut_points_search ON mut_leads (points);
    ALTER TABLE mut_lead_fields CHANGE object object VARCHAR(255) DEFAULT NULL;

There was no change in viewing a contact or the errors after forcing these updates whilst using php 7.

There was another similar issue mentioned on slack where crons weren't working when php-cli was set to 7.1 - https://mautic.slack.com/archives/C02HU8BUT/p1502006390619886

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.22

**Comment by escopecz** [comment]
I'm running PHP 7.0.17 and cannot see such problem either. The errors are too generic to guess what can cause it. I'm afraid you'll have to provide some more details.

**Comment by robwent** [comment]
I'll close this for now and open it up if I run into it again.

Those were the only errors in the log so I don't really have much more info other than php configuration.
