### ISSUE TITLE
My Instance in aws not working after certain time after uploadig mautic project 

### ISSUE THREAD

**Issue by trinath503** [mautic/mautic#4673]
i created an new fresh instance of aws free tier, added security groups like ssh,http,https, mysql and storagge size i added 10GB,

i am connecting to the instance using bitwise ssh after installing the lamp on aws , copying the mautic project on aws server in html folder given permission to the folder
sudo chmod -R 777 /var/www/html
i am able to login , everything working fine  but  unfortunately after some time i am not able to see the page , when i type ip address in browser  it loading for long time displaying nothing when i am  trying to log with bitwise its showing error like 

flow socket reader error receiving bytes ,an existing connection was forcibly closed by remote host

### Log errors: 

Some time 500 Error

flow socket reader error receiving bytes ,an existing connection was forcibly closed by remote host

**Comment by escopecz** [comment]
This doesn't seem like a Mautic issue. Please contact AWS support.
