### ISSUE TITLE
Tracking links return forbidden when opening urls in email dynamic content - Note mautic installed in subdirectory

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#4675]
What type of report is this:

| Bug report? | 

## Description:
Mautic is returning a Forbidden 403 message when we are using dynamic content in a campaign. Note that we campaigns are using UTM tags and the mautic setup in a subdirectory.. Links in the email body outside the dynamic content are working find. Links inside the dynamic content aren't. 

We noticed alot of urls are returning forbidden for all the emails sent after the update (old ones urls worked fine). After alot of digging, email links in the email body started working after we have changed the site url in the configuration General settings from https://domain.com/directory to https://domain.com/directory/ . But now urls in dynamic content having the same issue. 

Note - this is in regards to email dynamic content

Can you please advise

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.9.2
| PHP version |  7.0.20

 
### Log errors: 
403 Forbidden

**Comment by escopecz** [comment]
If you open the dev tools console (press F12 on Windows or Linux or opt+cmd+i on Mac). What is the full error message there?

**Comment by mellsaid** [comment]
We are getting the following @escopecz 

Failed to load resource: the server responded with a status of 403 (Forbidden)

I attached the tracking url here from the dynamic content: http://urlgone.com/7a4e41/ (will expire in 5 days)

**Comment by mellsaid** [comment]
URL for example email here:

http://urlgone.com/882766/ (expires in 5 days)

first two links are generated from dynamic content. 

bottom links are in the email body. 

All dynamic content is being pulled correctly and gets sent. But the URLs are the ones causing problems:
Note - email is built using the code editor.

**Comment by escopecz** [comment]
The full error message I can see is 
```
Forbidden

You don't have permission to access /vp/r/00446d50e9d2f2c5f2967583e on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```
where `/vp` is the folder where your Mautic lives. It seems more like a server configuration issue than a Mautic issue. See for example https://stackoverflow.com/questions/20752140/500-internal-server-error-when-trying-to-use-errordocument-to-handle-request. Consult it with your server admin, please. And let others know if you find some solution.

**Comment by mellsaid** [comment]
@escopecz It would make sense if its server configuration then all trackable urls would give the same error. But in this case,  this error only happen for the urls that are generated from the dynamic content parts? So same email, links generated in dynamic content have this error, but the rest of the links in the email all work fine.  (i.e. the url http://urlgone.com/882766/ ) first two links are putin the dynamic content and thus they dont work. Seecond two links are in the email of the same exact email - they do work. 

We think it could be an error how urls in dynamic content get generated for instances that has subdirectories. Which ends the redirect to a wrong url on the instance that is forbidden?


Noting that this was working alright when used on (v2.7 and 2.8). Seems to happen after updating to to 2.9.1/2 . We haven't changed any of the server configuration

**Comment by escopecz** [comment]
I still think it's a server issue for these reasons:

1. If Mautic doesn't find a tracking URL, it will throw 404, not 403.
2. The error message says it cannot access `/vp/...`. That is one folder level up from Mautic so I don't think Mautic gets even triggered and the error is thrown by the server before.
3. The error message doesn't exist in Mautic. You can check [here](https://github.com/mautic/mautic/search?utf8=%E2%9C%93&q=%22on+this+server%22&type=).

**Comment by mellsaid** [comment]
@escopecz intersting. Okay I'll check with our server admin. 

For my reference so I can give them complete information. Can you shed some light how and the logic behind trackable urls are being generated inside dynamic content, and difference between them and in standard email content?  In particular : 
> How the trackable links are formulated, and at which stage (when email gets created, or during send out / when being scheduled for send out). 
> They want to understand if email or links resulted with an error for a contact once. Does the contact itself play part so needs deleting content and readding. Does the email itself play part, so they need to delete email and recreate it. Or is it just the campaign, so just need to reset new campaign and test. Or all the above. 
> If instance is in subdirectory, where exactly does this gets pulled so they can trace if the trackable url is built /redirected correctly, and which area they need to change if it isn't. 

That would be very much appreciated. I can get our developer to work with server admin if I can provide them with the logic behind that happens behind the scene and post results here.

**Comment by escopecz** [comment]
The problematic URL should trigger [this controller method](https://github.com/mautic/mautic/blob/staging/app/bundles/PageBundle/Controller/PublicController.php#L396). They can put `die('this line was triggered');` statement inside it and see if the message shows up. But my guess is that it won't show even if it put in the index.php file.

**Comment by mellsaid** [comment]
I have sent this to the developers and server admins. 

The developer responded with an interesting insight. Can you provide any feedback @escopecz ? 

issue is =================> 
%3D%3D or %3F et..
last characters in ct param

380eb2a9c174da070f38cfa0a?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6Mjc7fXM6NToiZW1haWwiO2k6Mjc7czo0OiJzdGF0IjtzOjEzOiI1OTk1ODI2MTNmY2Y2IjtzOjQ6ImxlYWQiO3M6MzoiMTA0IjtzOjc6ImNoYW5uZWwiO2E6MTp7czo1OiJlbWFpbCI7aToyNzt9fQ%3D%3D&utm_source=MTC&utm_medium=Mautic&utm_name=Email&utm_content=Aug-17A

If replaced to 
380eb2a9c174da070f38cfa0a?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6Mjc7fXM6NToiZW1haWwiO2k6Mjc7czo0OiJzdGF0IjtzOjEzOiI1OTk1ODI2MTNmY2Y2IjtzOjQ6ImxlYWQiO3M6MzoiMTA0IjtzOjc6ImNoYW5uZWwiO2E6MTp7czo1OiJlbWFpbCI7aToyNzt9fQ&utm_source=MTC&utm_medium=Mautic&utm_name=Email&utm_content=Aug-17A

> Same email will work and track just fine once these chracaters are removed. Any reason this is not encoded as "="? also when we remove it, it doesn't seem to do any difference and everything works fine. Can this be removed from the encoding logic? Any pointers to where we can do that in the code please / any thoughts on the above?

>admin responses:  URLS that have the %3D %2d %3F in the request sometimes with apache and mostly will cause problem with modsecurity rules. Modsecurity must be modified at an apache server level to allow this as an exception rather than at .htaccess. However if these are emitted from the encoding or encoded differently, then this wont be a problem. This needs authorisation..

**Comment by escopecz** [comment]
The reasons are:
1. The ct param is encoded in base64. Base64 can add none, 1 or 2 equals signs at the and as a [padding](https://en.wikipedia.org/wiki/Base64#Output_padding). I'm not an expert on encoding, but wouldn't want to get in trouble by removing it:

> In theory, the padding character is not needed for decoding, since the number of missing bytes can be calculated from the number of Base64 digits. In some implementations, the padding character is mandatory, while for others it is not used. One case in which padding characters are required is concatenating multiple Base64 encoded files.

2. Equals signs have to be URL-encoded when used in a URL query value since plain text equals signs have special meaning. They separate URL query param from its value.

I could not find any mention about mod_security having trouble with URL-encoded equals signs. Can your server admins point me to it?

**Comment by mellsaid** [comment]
@escopecz They closed the ticket unfortunately but they sorted it! They got an authorisation to add the domain as an exception to be bypassed from mod_security. they said it cannot be disabled from .htaccess. Once they added the exception, all the same links work now. 

They added a disclaimer saying that mod_security detects this as a threat and blocks it by default and that the domain will not be protected for the mean time recommending to find a solution on an application level in the future.  

If you try the links above, you will find them all working now.
