### ISSUE TITLE
New view to show all items in the global category.

### ISSUE THREAD

**Issue by yourdigitalclub** [mautic/mautic#4676]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |  Y
| Enhancement? | 

## Description:
After discussing having a form of folder hierarchy within assets for better organisation, I thought it may be easier to sort through if it was possible to switch the views from standard to displaying category list first then the asset list filtered to that category. If that is not possible then making categories clickable globally to easier filter displayed items would do the trick. This could filter through across to most aspects of Mautic.

An example would be how segments immediately filter contacts when you click on view X contacts

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
It's related to https://github.com/mautic/mautic/issues/4353. I'll update the title a bit to make it a different feature request which you mention in the description.
