### ISSUE TITLE
Sparkpost API for bounces produced 500 error.

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#4678]
What type of report is this:

| Bug report? | 

## Description:
We are having an issue with sparkpost API. All the settings are entered correctly, however when the test payload is sent, the server returns a 500 server error. 

![image](https://user-images.githubusercontent.com/22168697/29409214-29a42d82-8343-11e7-9702-736992f2671b.png)

Target URL used in sparkpost is : https://domain/directory/mailer/sparkpost/callback

We are using 1.0 auth aswell. 

We tried adding a / at the end of the url so to be: https://domain/directory/mailer/sparkpost/callback/
We are getting a 404 error below:
HTTP/1.1 200
Date: Thu, 17 Aug 2017 10:58:23 GMT
Server: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
Cache-Control: no-cache
Set-Cookie: de32b5c5c027c2241d8a5a25ae716297=jm6u469stcai6rq7a1qhfpj1k0; path=/; secure; HttpOnly,mautic_session_id=1c58aea597db8af4e8f5aeb4329116db2a71d0d6; expires=Fri, 17-Aug-2018 10:58:24 GMT; Max-Age=31536000; path=/; secure,1c58aea597db8af4e8f5aeb4329116db2a71d0d6=746; expires=Fri, 17-Aug-2018 10:58:25 GMT; Max-Age=31536000; path=/; secure,mautic_referer_id=115; expires=Thu, 17-Aug-2017 11:28:25 GMT; Max-Age=1800; path=/; secure
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json

{"errors":[{"message":"Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!","code":404,"type":null}],"error":{"message":"Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)","code":404}}

Mautic instance v2.9.2
Apache - PHP Version 7.0.20
--

**Comment by escopecz** [comment]
Please provide also error message from the logs (https://mautic.org/docs/en/tips/troubleshooting.html)

**Comment by escopecz** [comment]
But 404 error means not found. I don't think there will be anything related in the logs. Are you providing `https://domain/directory/mailer/sparkpost/callback` as an example URL or is that the one you are actually using?

**Comment by mellsaid** [comment]
@escopecz Thats an example. We are using the actual instance. 

we get 404 if we add a trailing slash at the end of the url. 

If we use it without the trailing slash, which is the correct format as per the guide, we get the 500 error. And we get the below in logs:

Checked the logs and this is whats there atm:
[2017-08-17 11:29:02] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "swiftmailer.mailer.transport.smtp"." at /home/lamasa/public_html/vp/vendor/symfony/dependency-injection/Container.php line 305 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"swiftmailer.mailer.transport.smtp\". at /home/lamasa/public_html/vp/vendor/symfony/dependency-injection/Container.php:305)"} []

**Comment by escopecz** [comment]
Try to remove content of `app/cache/dev` and `app/cache/prod` directories. Then test again.

**Comment by mellsaid** [comment]
@escopecz Same error:

HTTP/1.1 500
Date: Thu, 17 Aug 2017 13:37:49 GMT
Server: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
Cache-Control: no-cache
Set-Cookie: de32b5c5c027c2241d8a5a25ae716297=eb23b9ft2kokf6f1lks2eepsr6; path=/; secure; HttpOnly
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json

[2017-08-17 13:37:50] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "swiftmailer.mailer.transport.smtp"." at /home/ll/public_html/vv/vendor/symfony/dependency-injection/Container.php line 305 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"swiftmailer.mailer.transport.smtp\". at /home/ll/public_html/vv/vendor/symfony/dependency-injection/Container.php:305)"} []

**Comment by namankumar** [comment]
Try changing the "Service to send mail through" config to "Sparkpost" from "Other".

**Comment by mellsaid** [comment]
@namankumar it is set as other. We are using SMTP rather than the API due to a known issue in Sparkpost API

**Comment by vdrover** [comment]
Adding the extra trailing slash worked here to solve this error: 

https://domain/directory/mailer/sparkpost/callback/

**Comment by vdrover** [comment]
Adding the extra trailing slash gave the same 404 as above:

https://domain/directory/mailer/sparkpost/callback/

Without the trailing slash, we simply can not add the webhook to sparkpost at all:
https://domain/directory/mailer/sparkpost/callback

**Comment by mellsaid** [comment]
Hi All, 

Sparkpost API seems to work fine now. 

Changing the sending method in configuration to sparkpost instead of other does seem to get the webhooks from sparkpost to work correctly.

**Comment by vdrover** [comment]
@mellsaid  Phenomenal tip! I had the Mail Send Settings set to SMTP. Switching that to API worked wonders.

**Comment by 3L1AS** [comment]
Does the bounce management work for you guys with Sparkpost? Mautic does not process the data send from Sparkpost it seems or something else is not right here. Any idea? https://www.mautic.org/community/index.php//8464-mautic-is-not-processing-bounce-webhook-from-sparkpost

**Comment by mellsaid** [comment]
Make sure you have the webhook cron @3L1AS 
i.e. 0,15,30,45 * * * * root /usr/bin/php /var/www/html/app/console mautic:webhooks:process

**Comment by 3L1AS** [comment]
@mellsaid I thought I only need this webhook cronjob when sending something from Mautic to another service/app? But good idea to check it out...

**Comment by 3L1AS** [comment]
Even with the cronjob mentioned above, it's not working. Any other idea how to fix this?

**Comment by tuliobbs** [comment]
> Try changing the "Service to send mail through" config to "Sparkpost" from "Other".

This was my problem :)
