### ISSUE TITLE
[feature] Allow tag manager instead of Analytics (and change location inserted)

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#468]
At the moment it is only possibly to easily insert analytics code via the in-built system, but this inserts whatever is put in the tag in the head.

While it's possible to load the Google Tag Manager code in the head, documentation suggests it should be loaded inside the body: https://support.google.com/tagmanager/answer/2574370?hl=en&topic=2574303&ctx=topic and http://www.lunametrics.com/blog/2014/12/12/google-tag-manager-snippet-placement/

I'd suggest there be an option to add analytics OR tag manager, and if it's tag manager then to render the block in the body.

While tag manager _does_ load in the head, it's not optimal and a significant amount of marketers will expect tag manager to be properly supported.

**Comment by miguelpascual** [comment]
I think, you can edit the template of your landing page to include the tag manager code. 

In /themes/Mauve/html you have base.html.php Wtih head section of html

![image](https://cloud.githubusercontent.com/assets/10166840/7854736/809cae18-051c-11e5-9379-692b22546a2c.png)

**Comment by RCheesley** [comment]
Yes, of course, but many people won't want to get into that and given
there's a field already in Mautic, it makes sense to allow both I think?

Ruth
On 28 May 2015 9:33 am, "miguelpascual" <notifications@github.com> wrote:

> I think, you can edit the template of your landing page to include the tag
> manager code.
>
> In /themes/Mauve/html you have base.html.php Wtih head section of html
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/10166840/7854736/809cae18-051c-11e5-9379-692b22546a2c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/468#issuecomment-106209998>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by MaxOnTheHill** [comment]
I think just have a field to insert tracking/analytics scripts … then it gives the most flexibility … as there’s heaps of tracking scripts that people use.

**Comment by RCheesley** [comment]
Sure, but some need to go in the head, some need to go in the body.  So
maybe an option to set that?

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 1 June 2015 at 01:35, Max <notifications@github.com> wrote:

> I think just have a field to insert tracking/analytics scripts … then it
> gives the most flexibility … as there’s heaps of tracking scripts that
> people use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/468#issuecomment-107257249>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by jmmedina93** [comment]
Hi! I open the topic again, I have a problem with Tag Manager. It is duplicating me as many times as landings I have created.
I do not know how to do it so that I only get one by landing.

This is my code

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','$codeTag');</script>

**Comment by juliencarlier** [comment]
> Hi! I open the topic again, I have a problem with Tag Manager. It is duplicating me as many times as landings I have created.
> I do not know how to do it so that I only get one by landing.
> 
> This is my code
> 
> <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','$codeTag');</script>

Same here :-/

**Comment by GiuseppeIuculano** [comment]
> 
> I'd suggest there be an option to add analytics OR tag manager, and if it's tag manager then to render the block in the body.
> 
> While tag manager _does_ load in the head, it's not optimal and a significant amount of marketers will expect tag manager to be properly supported.

HI @RCheesley , 

We'd like to implement this feature, but it's not clear to me why this issue was closed.

**Comment by RCheesley** [comment]
@GiuseppeIuculano it was likely closed because feature requests were moved over to the forums from Github.

Nowadays, they should be made on the forum at https://forum.mautic.org/c/ideas.

You can just dump the GTM code on your landing page theme. I used to use that all the time with my landing pages. Pretty easy to implement.

Actually we have this feature: https://forum.mautic.org/t/create-a-google-tag-manager-template-for-mautic/11568 which I think is really needed due to the issues folks are having with Mautic tracking code being flagged as malicious by GTM. 

I think it would be nice to have a feature where you could drop in your GTM container ID and have it properly rendered in landing pages as well though - maybe create a post in the ideas forum?
