### ISSUE TITLE
Campaigns should drop DNCs

### ISSUE THREAD

**Issue by calevans** [mautic/mautic#4681]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Y

## Description:
Right not, if somone is in a campaign and they mark themselves as DNC while there is an event scheduled for them, the system keeps looping through the event, seeing that it can't send, and throwing a Notice. The first time the system sees that an event can't happen because of DNC, it should cancel the event. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
I don't think it is possilbe to just remove the contacts which unsubscribe from email channel from the campaign. (if that's what you are saying) Mautic supports multiple channels. What if the event after that is send SMS and the contact did not unsubscribe from that channel?
