### ISSUE TITLE
Add Option like "Go To" for Campaigns Actions After Decisions

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#4682]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Y

## Description:

Would be nice if an Campaign Action send the Campaign Workflow to another point. See image for better explanation.

![mautic go to](https://user-images.githubusercontent.com/257004/29420917-d338a67e-8349-11e7-9838-11c78553c491.jpeg)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by luizeof** [comment]
@escopecz @alanhartless @dbhurley @virlatinus @kuzmany @mqueme This is a must have feature ;)

**Comment by escopecz** [comment]
Good idea, but also a duplicate: https://github.com/mautic/mautic/issues/1414

Please do not tag everyone. I get the notification about every issue, so I don't care. But it's also pointless to tag me. I can imagine it may get some of the tagged people angry.
