### ISSUE TITLE
Remove Lead from Campaign and also his History (to make an Campaign Loop)

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#4683]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:

Sometimes we want to our Lead pass multiple times in the same campaign. Very useful if Leads pass the campaign today and do not convert but enters again in 6 months.

How about an Action to Completely remove an lead of an campaign?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
1. I don't think that's the solution. Removing all info you have about a lead is high price to pay to make [recurring campaings](https://github.com/mautic/mautic/issues/1606). There are already 3rd party plugins which removes just the campaign event log for that one contact. That is also a data loss, but much less destructive. I wouldn't use that either but it's much better than your idea.
2. There is a campaign action to delete a lead: https://mautic.org/docs/en/campaigns/campaign_events.html#delete-contact. Please read the docs before creating a new issue.

**Comment by luizeof** [comment]
hi @escopecz thanks for your reply. But I Read the docs ;)

But if the Lead has another campaign I don't want to delete it. For this reason i suggest to remove only current campaign log (or allow leads to run the campaign again)

**Comment by escopecz** [comment]
Then I misunderstood the title of this issue. But both of my points still stands.

**Comment by yourdigitalclub** [comment]
The third party plugin works on the basis you want, you have to specify the campaign ID within a tag and it will search for the data of that campaign only and remove it

[https://github.com/thirdset/ThirdSetMauticResetBundle]
