### ISSUE TITLE
Adding unsubscribe columns breaking email reports

### ISSUE THREAD

**Issue by JohnConnell** [mautic/mautic#4684]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
Reports using the 'Unsubscribed' or 'Unsubscribed ratio' columns within the Emails data source are broken after upgrading from 2.8.2 -> 2.9.2.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0

### Steps to reproduce:
1. Create New Report
2. Set Data Source to 'Emails'
3. Add the column(s) 'Unsubscribed' or 'Unsubscribed ratio' to the report
4. Save & Close (error thrown)
 
### Log errors: 

mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT e.id AS e_id, e.name AS e_name, c.title AS category_title, e.subject AS subject, e.sent_count AS sent_count, e.read_count AS read_count, cut.hits AS hits, CONCAT(ROUND((e.read_count/e.sent_count)*100, 1),'%') AS read_ratio, CONCAT(ROUND(cut.hits/(e.sent_count)*100, 1),'%') AS hits_ratio, CONCAT(ROUND((COUNT(DISTINCT dnc.id)/e.sent_count)*100, 1),'%') AS unsubscribed_ratio FROM emails e LEFT JOIN emails vp ON vp.id = e.variant_parent_id LEFT JOIN categories c ON c.id = e.category_id LEFT JOIN (SELECT COUNT(cut2.channel_id) AS trackable_count, SUM(cut2.hits) AS hits, SUM(cut2.unique_hits) AS unique_hits, cut2.channel_id FROM channel_url_trackables cut2 WHERE cut2.channel = 'email' GROUP BY cut2.channel_id) cut ON e.id = cut.channel_id GROUP BY e.id ORDER BY e.name ASC LIMIT 30 OFFSET 0':  SQLSTATE[42S22]: **Column not found: 1054 Unknown column 'dnc.id'** in 'field list'" at /mymauticroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT e.id AS e_id, e.name AS e_name, c.title AS category_title, e.subject AS subject, e.sent_count AS sent_count, e.read_count AS read_count, cut.hits AS hits, CONCAT(ROUND((e.read_count/e.sent_count)*100, 1),'%') AS read_ratio, CONCAT(ROUND(cut.hits/(e.sent_count)*100, 1),'%') AS hits_ratio, CONCAT(ROUND((COUNT(DISTINCT dnc.id)/e.sent_count)*100, 1),'%') AS unsubscribed_ratio FROM emails e LEFT JOIN emails vp ON vp.id = e.variant_parent_id LEFT JOIN categories c ON c.id = e.category_id LEFT JOIN (SELECT COUNT(cut2.channel_id) AS trackable_count, SUM(cut2.hits) AS hits, SUM(cut2.unique_hits) AS unique_hits, cut2.channel_id FROM channel_url_trackables cut2 WHERE cut2.channel = 'email' GROUP BY cut2.channel_id) cut ON e.id = cut.channel_id GROUP BY e.id ORDER BY e.name ASC LIMIT 30 OFFSET 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'dnc.id' in 'field list' at /mymauticroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dnc.id' in 'field list' at /mymauticroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dnc.id' in 'field list' at /mymauticroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []

**Comment by escopecz** [comment]
It seems like your SQL schema is out of date. Please try to go through steps in https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful to update it.

**Comment by JohnConnell** [comment]
I've confirmed my schema is updated (_"Nothing to update - your database is already in sync with the current entity metadata."_) but this issue persists.

#4704 is related.
