### ISSUE TITLE
Fetching social profiles throws error 

### ISSUE THREAD

**Issue by namankumar** [mautic/mautic#4685]
What type of report is this:

| Q  | A
| ---| --- |
| Bug report? | Y |
| Feature request? | N |
| Enhancement? | N |

## Description:
Social Tab on the Contact page throws an error when I request it to fetch profiles for the user.  
The error msg displayed is 

> The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
> System administrators, check server logs for errors.

Mautic is successfully connected to all social networks except Google Plus.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.16

### Steps to reproduce:
1. go to "/s/contacts/view/xxxx" for a contact
2. click "Social" tab 
4. Make sure there are no existing profiles. 
5. Make sure you are connected to social networks.
5. Click the box that says "Click here to search for social media profiles based on contact's available profile data"
 
### Log errors: 

```

[2017-08-18 00:27:03] mautic.NOTICE: PHP Notice - Undefined index: lastRefresh - in file /var/app/current/app/bundles/LeadBundle/Views/Social/index.html.php\
 - at line 27 [] []
[2017-08-18 00:27:03] mautic.NOTICE: PHP Notice - Undefined index: social_profile_template - in file /var/app/current/app/bundles/LeadBundle/Views/Social/in\
dex.html.php - at line 39 [] []

[2017-08-18 00:27:03] mautic.ERROR: InvalidArgumentException: Template name "" is not valid (format is "bundle:section:template.format.engine"). - in file /\
var/app/current/app/bundles/CoreBundle/Templating/TemplateNameParser.php - at line 80 [] []
```

**Comment by vdrover** [comment]
Was this ever fixed?

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
