### ISSUE TITLE
Import in Background

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#4686]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
The more details the better...
I imprt 
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 9.2
| PHP version | 7.x

### Steps to reproduce:
1.  Import a File in csv and tell Mautic to import in Background
2.  Go In Import History
3. The file stay blocked in the mode Queued

<img width="1039" alt="capture d ecran 2017-08-18 08 02 14" src="https://user-images.githubusercontent.com/20974155/29446274-96cf7e2c-83eb-11e7-8733-e95dce292dd2.png">

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Did you configure the import command to your cron configuration? Can you see any errors in the logs?

**Comment by tpilet** [comment]
Ok we do it and we find the issue 

 

But it’s not clear that we need to add a new chron.

 

Thanks for your help

 

 

De : John Linhart <notifications@github.com>
Répondre à : mautic/mautic <reply@reply.github.com>
Date : vendredi, 18 août 2017 à 08:58
À : mautic/mautic <mautic@noreply.github.com>
Cc : tpilet <thierry.pilet@newcom4u.ch>, Author <author@noreply.github.com>
Objet : Re: [mautic/mautic] Import in Background (#4686)

 

Did you configure the import command to your cron configuration? Can you see any errors in the logs?

**Comment by escopecz** [comment]
It's better to look at the documentation before creating a new issue.

**Comment by djeraseit** [comment]
You have to hunt for this cron command. Documentation isn't clear on cron commands nor are all cron commands centralized in the documentation.

Here is the command:
php /path/to/mautic/app/console mautic:import

Reference:
https://www.mautic.org/docs/en/contacts/import.html

I set mine to run every 30 minutes.

**Comment by fullofcaffeine** [comment]
Thanks @djeraseit, if it weren't for you, this issue wouldn't be useful at all ;)

**Comment by escopecz** [comment]
Anyone can improve the docs if you guys feel like it's missing something https://github.com/mautic/documentation#contributing-to-the-mautic-documentation
