### ISSUE TITLE
Missing Tracked Videos Widget on Landing Page Builder

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#4695]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:

On Landing Pages Builder that are only Gated Video Widget, but not the new Tracked Videos (Gate Videos Variation).

If we add the Widget the data-form-id and data-gate-time attributes are required.

![download](https://user-images.githubusercontent.com/257004/29530793-cebe8fac-867b-11e7-8ee6-045d486137a1.jpeg)

The documentation says that an Tracked Video don't need the data-form-id and data-gate-time attributes, but the data-mautic-video="true" is required.

https://mautic.org/docs/en/video/index.html#tracked-videos-mautic-2-9-1-and-above

PS: This is not related to #4031 .

Thanks for your hard Work!

**Comment by RCheesley** [comment]
Closing this issue, as the documentation states that to track, but not gate, then you use a <video> tag.

I've raised a feature request about having the ability to do this via the builder here:  https://forum.mautic.org/t/allow-non-gated-video-embed-in-builders/11659
