### ISSUE TITLE
"#contacts" count shows anonymous + identified

### ISSUE THREAD

**Issue by namankumar** [mautic/mautic#4696]
#4695 What type of report is this:

| Q  | A|
| ---| ---|
| Bug report? | |
| Feature request? | |
| Enhancement? | x |

## Description:
The “#contacts” column on the segments page shows the added count of anonymous and identified contacts. From my perspective, it is better to only show count of identified ones - it is more valuable than anonymous count or the added count.

Not sure what other users think, this is my perspective.

**Comment by escopecz** [comment]
Then add the filter "Date Identified not empty" to your segments.
