### ISSUE TITLE
Dutch Translation

### ISSUE THREAD

**Issue by Nizzlay** [mautic/mautic#4698]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

## Description:
I've been searching for how to update the Dutch language (need it for a client), turns out Mautic uses transifex for that. So I've signed up to check it out.

Problem seems to be that transifex has translated a lot more strings than mautic displays. How come?

I can see there are a lot of strings that are translated, but now reviewed. Do unreviewed strings not show up in mautic? Can I do some setting to force them? Some have been translated months (or years!) ago, and are still not marked as reviewed..

**Comment by escopecz** [comment]
The docs should answer how to update a language on your Mautic instance:

https://mautic.org/docs/en/translations/index.html

Unreviewed strings are also used to build a translation.
