### ISSUE TITLE
Clearing mautic cache via console not working

### ISSUE THREAD

**Issue by FabianTe** [mautic/mautic#4699]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When I try to clear mautic's cache via ```sudo -u www-data php console cache:clear``` I get this error:

![image](https://user-images.githubusercontent.com/7669818/29557011-0c290758-8728-11e7-9703-e5e5f132dd85.png)

```
Compile Error: require_once(): Failed opening required '' (include_path='.:/usr/share/php')
```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7.0.22-0ubuntu0.16.04.1

### Steps to reproduce:
1. ```sudo -u www-data php console cache:clear```
 
### Log errors: 

See Image above

**Comment by escopecz** [comment]
Clearing the cache with this command can sometimes fail because that command is using Symfony framework and that uses the cache itself. So if the cache is corrupted too much, the command itself will stop working. Remove the cache with `rm -rf app/cache/*`.

**Comment by FabianTe** [comment]
Oh, thank you! I didn't know about the possibility of using the ```*``` wildcard when using ```rm```.
Previously I deleted the folder itself and had to recreate it. Nice!
