### ISSUE TITLE
New mautic more problems with mail (mandrill)

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#470]
I'm trying to send to a small ddbb (3 leads) a mailing through mandrillapp (when this work I plans send to 1000)

![image](https://cloud.githubusercontent.com/assets/10166840/7838157/a6d2e02a-048b-11e5-92f7-a79bf1abf8fe.png)

I tested by "test connection" button --> Success!
I made the configuration, I clear cache directory (erase all files in app/cache) 

When I create one email and push the send button:
![image](https://cloud.githubusercontent.com/assets/10166840/7838232/19c54a28-048c-11e5-91fe-371f9ea28bc7.png)
The mails appear pending...

the directory  /app/spool/default is empty.

I have the cron php /path/to/mautic/app/console mautic:email:process --env=prod every 10 minutes but it show error:
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  You have requested a non-existent service "swiftmailer.transport.real".

Questions:
Is normal that the queue directory is empty?
What is swiftmailer.transport.real? 
I forgot something to do?

thaks a lot

**Comment by RCheesley** [comment]
Not sure if this might be the same issue I was having in #384 which necessitated the hosting provider opening a port .. the next release uses their API rather than SMTP relay which should fix a lot of the connection errors apparently!

**Comment by miguelpascual** [comment]
Thanks but I think is not the same problem. I has another mautic runing in the same machine with mandrill. I think the problem is related to I was configured send the emails with queue and the queue system give me one error.

**Comment by alanhartless** [comment]
I've only seen the  `You have requested a non-existent service "swiftmailer.transport.real".` error when the system is not set to use the queue.  But it does look like you have it set. 

I happened to add a catch in https://github.com/mautic/mautic/pull/532 to ensure the system is using the queue before running the command.  Can you apply that to see if you still get the error?

Thanks,
Alan

**Comment by alanhartless** [comment]
Closing this due to lack  of feedback.  Some changes were made in recent versions that may have resolved this.  If it continues to be an error, let us know!
