### ISSUE TITLE
Mautic does not send attachments in the email example for Sparkpost

### ISSUE THREAD

**Issue by pavel-janicek** [mautic/mautic#4703]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Mautic does not send e-mail wit attachment

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0

### Steps to reproduce:
1. Create e-mail
2. In "advanced" tab assign attachment
3. Send e-mail example
4. Such e-mail does not contain any attachment
 
### Log errors: 

No errors in log

**Comment by pavel-janicek** [comment]
Additional info: Seems that this happens only when SparkPost is used. If I use PHP Mail functionality, then attachment is sent

**Comment by pavel-janicek** [comment]
Quick fix:
Set up sending through SparkPost as via "Other SMTP service"
SMTP host: smtp.sparkpostmail.com
SMTP port: 587
Encryption method: TLS
SMTP Auth type: LOGIN
User name: SMTP_Injection
Password: <Your_API_Key>

Using this method Mautic delivers mail with attachment

**Comment by luizeof** [comment]
Sparkpost Docs says:

Attachments are supported with inline templates only. A future enhancement will include support for attachments with stored templates.

https://www.sparkpost.com/docs/user-guide/sending-attachments/

**Comment by pavel-janicek** [comment]
@luizeof Thing is, this worked fine on previous versions of Mautic. I am not quite sure what "inline templates only" means for me, however if I am destined to use Sparkpost as SMTP server only, so be it. Still bit better than PHP Mail option :)
