### ISSUE TITLE
Mautic tracking script in footer caused "invisible" 500 errors on Prestashop store blocking google crawls

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#4706]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Three quick qualifiers: I am not very technical and may have made an obvious mistake, this mistake has probably cost my business thousands of pounds. Three, I am being open about this to hopefully prevent anyone else making the same error. So - please be kind, I am shocked and upset at the damage this has cause my business and embarrassed I didn't spot it sooner. 

**Cause:** I added the tacking script to our prestashop theme footer "footer.tpl" in May this year. It did not cause any obvious issues with out store, pages looked fine, orders continued etc. 

**Effect:** From May we had had a noticeable decline in total number of orders, but I thought this was to do with the political uncertainty since the election here, as many businesses I know had noted the same issue.

Today I was working on another issue and trying to get https://www.xml-sitemaps.com to generate a list of all the urls on our store, but it kept flagging an error. I had also noticed a change in our site visitors in piwik analytics. I started to feel concerned so I drilled down and found that though direct entry visits had continued to grow well, search traffic was down to about 1/4 of what it should be. I worked with a sys-admin at our hosting company and found:

**Error example**
[Tue Aug 22 15:45:11.381644 2017] [:error] [pid 15036] [client
195.248.116.49:52346] PHP Fatal error:  Uncaught exception
'SmartyCompilerException' with message 'Syntax Error in template
&quot;/var/www/ethical-pets.co.uk/web/themes/ethicalpets/footer.tpl&quot;
 on line 40
&quot;(function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;&quot;  -
Unexpected &quot;[&quot;, expected one of: &quot;}&quot; , &quot; &quot;
, ATTR' in
/var/www/ethical-pets.co.uk/web/tools/smarty/sysplugins/smarty_internal_templatecompilerbase.php:665\nStack
trace:\n#0
/var/www/ethical-pets.co.uk/web/tools/smarty/sysplugins/smarty_internal_templateparser.php(3144):
Smarty_Internal_TemplateCompilerBase->trigger_template_error()\n#1
/var/www/ethical-pets.co.uk/web/tools/smarty/sysplugins/smarty_internal_templateparser.php(3209):
Smarty_Internal_Templateparser->yy_syntax_error(64, '[')\n#2
/var/www/ethical-pets.co.uk/web/tools/smarty/sysplugins/smarty_internal_smartytemplatecompiler.php(105):
Smarty_Internal_Templateparser->doParse(64, '[')\n#3
/var/www/ethical-pets.co.uk/web/tools/smarty/sysplugins/smarty_internal_templatecompilerbase.php(200):
Sm in
/var/www/ethical-pets.co.uk/web/tools/smarty/sysplugins/smarty_internal_templatecompilerbase.php
on line 665

Along with a ton of "500" errors in Google search console. 

I realised that this was caused by the Mautic tracking code in our footer.

I don't know if I was not supposed to put this code in a tpl file, if this is just wrong and I didn't know this, or if this is not an expected error. Anyway, basically 90% of our sites pages had been throwing 500 errors to google for months, causing a very large drop in our site trafic from search. but because they looked fine we didn't know. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Can you share the relevant code of foolter.tpl where you pasted the tracking code? With 2 lines above and 2 lines bellow?

**Comment by gingerling** [comment]
This is the whole of the footer:

`		{if !$content_only}
				</div>


				
			</div>


			<div id="footer">{$HOOK_FOOTER}</div>
		</div>
	{/if}
	</body>
<script>
    (function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
        w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),
        m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)
    })(window,document,'script','http://ethical-pets.co.uk/m/mtc.js','mt');

    mt('send', 'pageview');
</script>
</html>`

**Comment by gingerling** [comment]
Can't seem to get it to paste right - here is as image
![screenshot from 2017-08-22 16-54-38](https://user-images.githubusercontent.com/2853040/29574853-afb324da-875a-11e7-971e-c4d21afb7998.png)

**Comment by escopecz** [comment]
I looked into your issue. The problem is that Prestashop use Smarty to generate the HTML. Smarty use tokens starting with `{` and ending with `}`. The problem is that Javascript use those brackets to define objects. You can google phrase "Prestashop SmartyCompilerException" and you'll find you are not alone. Javascript code in the Prestashop themes must be escaped somehow. Please ask in the Prestashop forums.

**Comment by gingerling** [comment]
Hi, ok, I will look into a solution to this and see if it can be documented

**Comment by kuzmany** [comment]
Solution:

{literal}
mautic tracking `code`
{/literal}

https://www.smarty.net/docsv2/en/language.function.literal

**Comment by gingerling** [comment]
😊 thanks friend!
