### ISSUE TITLE
data loss updating contact via api

### ISSUE THREAD

**Issue by tomdavidson** [mautic/mautic#4710]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x |
| Feature request? | 
| Enhancement? | 

## Description:

A PUT request to edit an existing Contact and without setting the header results in all field values of the Contact being cleared.  Setting the header to "Content-Type: application/json" results in the expected behavior.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Cloud Pro |
| PHP version |  Cloud Pro |

### Steps to reproduce:

1. PUT to the contact/ID/edit endpoint without setting the header. This appears to happen on new contacts or existing.
2. GET the contact or view the contact in the webgui and observe the lost data.
3. Repeat, this time with the set header.

**Comment by escopecz** [comment]
Could you please share examples of HTTP requests and responses? I'm not sure where you have to set the header. It's working for me without setting any header.

Also note this sentence from [the docs](https://developer.mautic.org/#edit-contact):
> **PUT** creates a contact if the given ID does not exist and clears all the contact information, adds the information from the request.

**Comment by tomdavidson** [comment]
https://baseURL/api/contacts/949/edit?field=stuff

In this case Contact ID 949 does in fact exist and has data prior to the put. After the put 949 is empty - as observed both in the web console and in the put response.

**Comment by escopecz** [comment]
Once again, isn't it what the documentation says as well?

*PUT ... clears all the contact information, adds the information from the request.*

Use PATCH if you want to preserve other field values.

**Comment by SpencerTuft** [comment]
Found the fix: In the documentation, it indicates that the aliases can be supplied as post parameters which would mean in the query string. Instead, I supplied them as body parameters and all the data was accepted correctly. No bug after all, just a misunderstanding while reading the documentation.

**Comment by tomdavidson** [comment]
@escopecz 

IMHO anything that results in unexpected data loss is a bug, maybe in the docs, but a bug none-the-less.  Even with the context of this issue the info that that editing an existing contact with PUT will cause data loss still has to be derived.

Another user had a similar issue a few months ago: https://www.mautic.org/community/index.php/6719-rest-api-payload-to-create-a-new-contact/0

**Comment by escopecz** [comment]
I'm not sure what is wrong with the docs. It states how PUT works even though it works as HTTP PUT should:

> The HTTP PUT request method creates a new resource or **replaces** a representation of the target resource with the request payload.

Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT

> PUT replaces an existing entity. If only a subset of data elements are provided, the rest will be replaced with empty or null.

Source: https://spring.io/understanding/REST#put

Maybe I don't understand your problem clearly. If the bug is in the documentation, [please correct it](https://github.com/mautic/developer-documentation). It's also open source and anyone can send a pull request.

I'll close this issue for now as I understand it's not a Mautic bug.

**Comment by SpencerTuft** [comment]
To clarify: Under [Edit Contact](https://developer.mautic.org/#edit-contact) the documentation says
> ** Post Parameters **
> *  - Any contact field alias can be posted as a parameter. For example, firstname, lastname, email, etc.
This indicates to me that one must include the all edits to a contact **in the query string**. The correct way (at least when using NodeJS) is to include the parameters in the body/payload and not in the query string.
For example (using NPM's request module):
```
let options = {
    method: 'PUT',
    url: `${host}/api/contacts/ID/edit`,
    headers: {
      "authorization": basicAuth,
      "content-type": "application/json",
    },
    body: {
      "field": "stuff"
    },
    json: true
  };

  request(options, function (err, res, body) {
    if (err) return callback(err); // Handle Error
    return callback(null, body); // Handle Body
  });
```

**Comment by escopecz** [comment]
TBH I didn't know the JSON body params work. Symfony framework must convert it automatically for Mautic. That's why it's not documented. But using NPM's request module isn't need for finding hidden/undocumented paths. This would work as well:

```
let options = {
    method: 'PUT',
    url: `${host}/api/contacts/ID/edit`,
    headers: {
      "authorization": basicAuth
    },
    form: {
      "field": "stuff"
    }
  };

  request(options, function (err, res, body) {
    if (err) return callback(err); // Handle Error
    return callback(null, body); // Handle Body
  });
```

**Comment by skiod** [comment]
> Once again, isn't it what the documentation says as well?
> 
> _PUT ... clears all the contact information, adds the information from the request._
> 
> Use PATCH if you want to preserve other field values.

Please highlight this one.

**Comment by escopecz** [comment]
@skiod you can do it yourself. The dev docs are on GH too: https://github.com/mautic/developer-documentation

**Comment by Prosp3r** [comment]
This issue still persists on the /api/contacts/ID/edit endpoint. PATCH is ineffective on softaculous installation of Mautic and PUT wipes out data without creating anything new.  :(

**Comment by mutagatifu** [comment]
dear Team, i need your help, am using mautic rest apis, but the one to edit contact is not working with PATCH and erase data with PUT
