### ISSUE TITLE
Ability to configure multilingual unsubscribe message

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4711]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
For international companies, it would be great to have the ability to configure multilingual unsubscribe message on the unsubscribe page.

**Comment by escopecz** [comment]
Probably duplicate of https://github.com/mautic/mautic/issues/873

**Comment by npracht** [comment]
Indeed, i didn't find it. Thanks !
