### ISSUE TITLE
Add "Owner" as a column in Reports

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#4714]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Y

## Description:
When looking at contacts in a report, we would like to view by Owner as well.

**Comment by escopecz** [comment]
Ok, just add them:
<img width="440" alt="screen shot 2017-08-24 at 08 14 13" src="https://user-images.githubusercontent.com/1235442/29652121-538cdf3e-88a4-11e7-8f16-02d5f1095fdd.png">

**Comment by ronnieduke** [comment]
@escopecz - Apparenty the column is available on some reports and not others. When doing a "Form Submissions" report, I am not able to add the column:

![image](https://user-images.githubusercontent.com/742579/29652494-807c62b6-885a-11e7-931f-808cbd03ea85.png)

**Comment by escopecz** [comment]
Well, that's understandable. Form submissions doesn't have owners. Only contacts does. Also you specified you want it for contact reports:

> When looking at contacts in a report...

**Comment by ronnieduke** [comment]
@escopecz - I did an audit of all report types, and here are the ones that do not support adding "owner" as a column (excluding reports that are not contact-centric, such as forms, and assets):

- Campaign Events
- Emails Sent
- Form Submissions
- Page Hits

In fact, the "contacts" report type you referred to seems to be the only report that does.

**Comment by ronnieduke** [comment]
@escopecz - Form submissions don't have owners, but when you're looking at a Form Submissions report type, you're looking at contacts. I would expect to be able to view owner, just as I can view First Name, Last Name, Email, etc. 

My apologies for not being specific in the original post....I was looking at contacts in a Form Submissions report, and assumed all report types that refer to contacts would have the same column options.

**Comment by ronnieduke** [comment]
By "owner" I mean "Contact Owner"..just like "Contact First Name", "Contact Email", etc

**Comment by ronnieduke** [comment]
@kuzmany - when referencing this issue on your PR #4995  are you referring to the ability to show Contact Owner as a column, or are you referring to the owner of the report itself? The description of the PR seems to indicate the latter, which is not what I was requesting in this issue.
