### ISSUE TITLE
mts.js leaks MediaElements player CSS to page DOM (still)

### ISSUE THREAD

**Issue by treehousetim** [mautic/mautic#4715]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Related
#4443, #4431, #4480

## Description:
Just upgraded to 2.9.2 today and now a video on the home page of my site shows up for a moment then disappears.  Watching the inspector in chrome reveals that /media/css/mediaelementplayer.css is loading from our mautic server at the moment the video disappears.  It appears that the wordpress theme the main web site is using utilizes the media element player itself.

I've reviewed the other bug reports related to the media element bug and it shows that it should be fixed in 2.9.1 - I'm not sure anyone had this exact edge case that I do.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.22

### Steps to reproduce:
1. have a webpage using mediaelement and a mautic 2.9.2 pixel
2. load that page, see the player disappear.
 
### Log errors: 

none

**Comment by escopecz** [comment]
I'm afraid it is an edge case on your website with specific CSS or JS. You may have to provide a link to it so someone could try to debug.

**Comment by treehousetim** [comment]
Unfortunately we were forced to change the design of the home page for our site since it was so ugly broken.  I'm super curious why the JS pixel would need to inject CSS when we're not tracking video events.
