### ISSUE TITLE
Cannot delete Contacts / Segments / Campaign etc. error 403

### ISSUE THREAD

**Issue by wucherpfennig** [mautic/mautic#4716]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:
I cannot delete any resources like contacts / segements / campaigns... I always get a server response 403 - forbidden.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.9.2
| PHP version | PHP Version 7.0.22

### Steps to reproduce:
1. Login as Admin
2. Try to delete something

Notice:
* All DB updates ran successfully
* Cache was cleared
 
### Log errors: 

No logs available! Everything seems ok

**Comment by escopecz** [comment]
This is not a Mautic issue since it works for everyone else. It must be a server configuration issue. Please report this to your server admin.

**Comment by wucherpfennig** [comment]
@escopecz it worked till v.2.9.1...

since it is my server please tell me where to start looking? 

since those are ajax request to route `/s/resource/delete` I cannot think of a server misconfiguration...

**Comment by escopecz** [comment]
I'd tell you my guess if I had one. Try some advises you google. For example https://stackoverflow.com/questions/17244646/jquery-ajax-delete-request-throws-403-access-denied-error

**Comment by wucherpfennig** [comment]
Thank you for your guess... I started to dig deeper on this issue and it seems that my hoster was somehow updating his services and it suddenly started to work again...
