### ISSUE TITLE
Ideas from an internal enterprise implementation 

### ISSUE THREAD

**Issue by tomdavidson** [mautic/mautic#4725]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x |
| Enhancement? |  x |

## Description:
I have been working on an implementation of Mautic at BYU for on-boarding and to influence work culture. It has been fun but with some snags. I have a few ideas from the experience that I wanted to share:

1. I'm not satisfied with the unexpected data loss when editing existing Contacts via the API. This is a user experience issue and not just an inexperienced user.
2. OpenAPI specs for the API would be very helpful in facilitating SDK generation and integrations. We are OpenAPI everywhere and have come to expect it with all enterprise RESTfull APIs. I would also appreciate a GraphQL interface but this was not an issue at BYU because it is not near as prevalent as  OpenAPI for us.
3. Merging campaign branches is a big deal. I losted lots of time dealing with this and ended up with four separate Mautic campaigns to satisfy our one on-boarding campaign. I understand this is in the pipes already.
4. I would also like to see an option for Contacts to go through a campaign more than once. Perhaps a setting in the campaign root to allow repeats.
5. Support for multiple email providers and selecting per campaign or maybe even per email would be nice. Some of our campaigns would use local exchange while others could use SES or Mautic.
6. Variables in the campaign would be nice too. One example use is setting a default execution delay. When I test, I can set it to one minute but when I publish I can set it to one day.
7. Default meaning for names for actions, decisions, and conditions based on how they are configured.
8. Form submit action that maps form fields to tags to add or remove and allowing the use of tags in dynamic content filters. This will help avoid contact filled bloat when adding custom field for specific campaigns.
9. Simple webhook message transformer would allow us to ingest Muatic events in our enterprise without creating and operating a message mediator. 
10. Everything a plug-in, that can be disabled. For example, the Company features did not translate to our internal use and clutter up the interfaces with all the extra fields (even when disabled) and menus.
11. There is an organizational decision that limits SMSing employees, but we do use DevOps chat quite a bit. Direct messages to chat and maybe focus items in channels would be a big win.
12. I was quite disappointed that SSO only supports authentication and not authorization and provisioning. Enterprise needs a more complete federation.
13. Testing campaigns is a pain. Quite a few other systems have spec files. I would love to have a campaign spec'd in YAML where I can use YAML's native anchors and templates and also keep the campaign in git. The API can provide a current linter too. GitLab does this and I am able to have a git hook that calls the lint API to keep me from ever pushing spec'd file syntax or interpolation error.

**Comment by escopecz** [comment]
Tanks for taking time and write your ideas down! 

But our experience is that feature requests containing multiple unrelated sub-requests are going to sit here open for years. Some sub-requests will get implemented. Some sub-requests will be duplicated in other feature requests. I think that more than half of your list already exists as separate feature requests. It's a nightmare to keep track of state-of-implementation of such request. So I'll close this one and please create separate feature requests for ideas that doesn't exist already.

I like the GraphQL one. I was thinking about it too. Or using more plugin approach than core features. Love it. Although I don't think it will happen for already built-in features.

**Comment by tomdavidson** [comment]
I thought the feedback from a paying customer that is a major university with over 200 developers might be worth more than that, but OK.
