### ISSUE TITLE
Links in mails sent with campaigns not working

### ISSUE THREAD

**Issue by Schokolader** [mautic/mautic#4727]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I've installed mautic on domain a 
My website is on a different domain. Using wordpress with the mautic plugin.

Now I created an email and a campaign using the honeypot method of the documentation. 
If someone signs up for the newsletter than he receives an email to visit a page on my website for newsletter sign up. 
But if this email is sent within the campaign it changes the link in the email. And the link is not showing my website it shows the domain where mautic is installed. When you click it, it causes this error: 
"Not Found

The requested URL /r/427e8c9f1e00bc648dbfab277 was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request."

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0

### Steps to reproduce:
1. Create a form and add it to your website
2. Create an email
3. Create a campaign that modifies the segments of a contact
4. Create a campaign for the new segments contacts for sending mails
5. Fill out the form on your website
6. You get an email. Open it. 
7. Click on the link to visit the page. Here you see the link changed. It is not the link which you created it in mautic. It changed to something like: www.domain.com/r/427e8c9f1e00bc648dbfab277?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czoxNDoiY2FtcGFpZ24uZXZlbnQiO2k6MTtpOjUzO31zOjU6ImVtYWlsIjtpOjI7czo0OiJzdGF0IjtzOjEzOiI1OTlmZGRiM2Q1YjgyIjtzOjQ6ImxlYWQiO2k6NDgxO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYWlsIjtpOjI7fX0%3D&
8. Open it and you get "Not Found

The requested URL /r/427e8c9f1e00bc648dbfab277 was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request." 

 
### Log errors: 

[2017-08-25 10:16:32] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #481. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /home/meditati/public_html/info/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #481. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /home/meditati/public_html/info/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []

**Comment by escopecz** [comment]
What value do you have in Mautic configuration in the **Site URL** field?

**Comment by Schokolader** [comment]
The domain where mautic is installed. https://mydomain.com/

**Comment by escopecz** [comment]
That should be correct. Or is the Mautic installed in a subfolder or subdomain? Could you send or forward me an email from the campaign to john.linhartATmautic.org?

**Comment by Schokolader** [comment]
yes it's installed in a subfolder mydomain.com/info.

**Comment by escopecz** [comment]
Thanks for the email. Yes, so add the `/info` to the **Site URL** field and the links will start working in newly sent emails.

I tested the link in your email and I got 404. But When I added the `/info` part into it, it worked.

**Comment by Schokolader** [comment]
ok thank you very much for your help. But now when you hit the button "submit" to send the form the button stays on "Please wait" forever... It does not load the thank you page.  
But the campaigns are working. That is great.

**Comment by escopecz** [comment]
You'll have to rebuild HTML cache of your forms which were also generated with the wrong URL. See https://mautic.org/docs/en/forms/index.html#form-troubleshooting

**Comment by Schokolader** [comment]
Ok, I've rebuild the form, but that doesn't help. It causes this error in the chrome console: 
"checksiteuser.js:42 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document."

**Comment by escopecz** [comment]
Do you have such option configured in your browser? https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

**Comment by Schokolader** [comment]
ok yes this solved the chrome error, but the mautic form error is still the same. Showing "Please wait..." forever.

**Comment by escopecz** [comment]
If it's not a configuration issue (the troubleshooting link above) and it's not a CORS (https://mautic.com/help/getting-started-mautic-cloud/#5) issue either, then you'll have to find some error message either in the Chrome Dev Tools console or in Mautic logs.

**Comment by Schokolader** [comment]
Ok, yes the error message in the mautic logs shows this: 

`[2017-08-25 17:39:13] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #497. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /home/meditati/public_html/info/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #497. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /home/meditati/public_html/info/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []
`

**Comment by Schokolader** [comment]
can it be that this is solved with the next release? https://github.com/mautic/mautic/issues/4652

**Comment by escopecz** [comment]
It's related to https://github.com/mautic/mautic/issues/4726. Let's discus it there. I'm trying to replicate, but so far no luck.
