### ISSUE TITLE
CORS not used in the forms

### ISSUE THREAD

**Issue by drimlike** [mautic/mautic#4731]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | Y

## Description:
We are using the forms created to link the data that an user enters in our actual site forms. For this we are using AJAX, to post the data to Mautic and merge the user logs to this newly created contact. This works fine now, even though we don't use the Mautic form response, we have this error in our logs:
`XMLHttpRequest cannot load https://mautic.mydomain.com/form/submit?formId=X. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://myotherdomain.com' is therefore not allowed access.`

It looks like the forms are not adding any CORS header, I was wondering if we could use the same function that is managed from the option of Mautic?
## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.9.2
| PHP version | 5.6.3

### Steps to reproduce:
1. Connect a third party form data and send the correct data via Ajax POST type data to a mautic form
2. Looking in the log, the Cors error is shown
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Did you configure the domain in Mautic's CORS settings?

**Comment by drimlike** [comment]
@escopecz ,

yes and it's opened for https://myotherdomain.com, but I realised that there is no CORS header in the forms.

Cheers,

**Comment by drimlike** [comment]
@escopecz ,

why did you close this ticket? The issue is still remaining, is it not possible to add the CORS header to the forms? 

Thanks,

**Comment by escopecz** [comment]
I thought that

> but I realised that there is no CORS header in the forms.

meant you found the problem.

Anyway, try to find the solution here: https://www.google.com/search?q=ajax+set+cors. It doesn't seem to be a Mautic bug.

**Comment by drimlike** [comment]
Ohh sorry I see, I meant I activated the option, even with it activated, I realise that the cors header was not adde to the forms.

Hope it makes sense.

Thanks,

**Comment by drimlike** [comment]
@escopecz ,

the issue is that the ajax call to the form is made from a different domain, the only way to add these headers to the form response once validated is to set it at the form level. If we change anything to the CORS header via the htaccess this is making issues with the tracking. So the best is to let the application (Mautic) take care of the header. This is added correctly to the mtc/event file, it would be great to have it added to the form too. 

```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:Origin, X-Requested-With, Content-Type
Access-Control-Allow-Methods:PUT, GET, POST, DELETE, OPTIONS
```
Thanks =)

**Comment by escopecz** [comment]
I don't understand. All those headers are set by Mautic when you enable CORS in the configuration: https://github.com/mautic/mautic/blob/staging/app/middlewares/CORSMiddleware.php#L27-L32

**Comment by drimlike** [comment]
@escopecz ,

We saw this, but those headers are not used when the forms are submitted. We just tested again and there is no trace of those headers in https://mautic.mydomain.com/form/submit?formId=4, which brings the CORS error from the AJAX that submitted data to it. 

We played with the CORS option in the application and htaccess but realised that it needs to be manage by Mautic to make sure it's using the one defined everywhere. 

Let me know if I can PM you and send you links for you to test it on your side, which might make more sense than me trying to explain it. 

Cheers,

**Comment by escopecz** [comment]
Mautic uses AJAX to save the form too. [Look at how it's done](https://github.com/mautic/mautic/blob/staging/media/js/mautic-form-src.js). Or re-send the submission from your server via CURL. I wrote a [PHP library](https://github.com/escopecz/mautic-form-submit) for it.

**Comment by drimlike** [comment]
@escopecz ,

Man I don't know why but we missed that librairie and coded our own ajax hack to pass on info from our forms. 

We will try to integrate that librairie to our scripts and remove our ajax hack.

Thanks for your help, will open a new ticket if we are having any other issues.

Cheers,

**Comment by williamknn** [comment]
I'm with the same issue. My Node.js server have CORS enabled and I still can't send an Ajax request for Mautic's server.

**Comment by coreyworrell** [comment]
I think this should be reopened, as there is currently no way to submit a form via JavaScript API only. Above method requires PHP, or requires setting up an iFrame and sending messages back and forth. Simply adding the CORS headers would solve this. The current setting for CORS has no effect on the `/form/submit?formId=` endpoint.

**Comment by bindermuehle** [comment]
I was able to get the CORS headers to work when adding following header to the POST Request:
X-Requested-With: XMLHttpRequest
I found this in following example: https://gist.github.com/escopecz/136f62b66d526bc32006f0d2358a8e15
as a note for people struggling to get the mautic form to work with XHR requests
