### ISSUE TITLE
Graphs do not show data for today unless I manually type in tomorrow's date in the date range widget

### ISSUE THREAD

**Issue by treehousetim** [mautic/mautic#4733]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
After upgrading to 2.9.2 I noticed that graph data wouldn't load for "today" unless I manually enter tomorrow's date as the end of the date range and click apply.  I have to type it in because the date picker won't allow me to pick tomorrow's date.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | PHP Version 7.0.22-0ubuntu0.16.04.1
--

### Steps to reproduce:
1. upgrade 2.8.2 to 2.9.2 (not sure if it's related to upgrades but that's the path we're on)
2. visit any page with a graph (asset detail page with the graph at the top) that you know has activity on it
3. notice zero activity for "today"
4. manually type in tomorrow's date because the widget won't let you select a date in the future.
5. click the apply button.
6. enjoy seeing your stats for today.
7. get annoyed that you have to do this on every single graph you want to look at.
 
### Log errors: 
no errors in the log.

**Comment by escopecz** [comment]
Thanks for the report. I believe it is the same issue reported in https://github.com/mautic/mautic/issues/4709, but with different timezone. I'll close this issue as a duplicate.
