### ISSUE TITLE
Feature Request - Netlify Integration and Incoming Webhook Lead Submission

### ISSUE THREAD

**Issue by ilearnbydoing** [mautic/mautic#4735]
Hi,

You can integrate https://www.netlify.com/ a free static website hosting and CDN service provider you might integrate with landing page.

Also Netlify has 'Form' submission feature as well which you might can integrate with it's outgoing Post Webhooks.

Thanks

**Comment by escopecz** [comment]
I don't see what needs to be done on Mautic side for that service to integrate to Mautic. Feel free to use it for your custom landing pages.
