### ISSUE TITLE
Hard to work in the builder with small screen like 13"

### ISSUE THREAD

**Issue by viryagroupdev** [mautic/mautic#4739]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? |
| Enhancement? |  Y

## Description:
On small screen like 13" laptops the builder is really hard to work with please change builder section width from static to dynamic right now the builder has 2 classes one on the panel: 
1.
`.builder-panel{ width:525; }`
change that to
`.builder-panel{ width:30%; }`

2.
`.builder-content{position:fixed; left:0; top:0; right:525px; height:100%}`
change that to
`.builder-content{position:fixed; left:0; top:0; width :70%; height:100%}`
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
You can ensure this changes will be made in the next release if you send the pull request with your changes.

**Comment by zhakid** [comment]
damm wrong account!!! i'll make the pull request! thanks alot!

**Comment by npracht** [comment]
Hello @escopecz it can be closed :)
