### ISSUE TITLE
Save form issue when "http://" is contained

### ISSUE THREAD

**Issue by and-ors** [mautic/mautic#4740]
What type of report is this:
| Bug report? | (possible)

## Description:
Errors in form editing and saving under certain conditions

## If a bug:

| Mautic version | 2.9.2
| PHP version | 5.6

### Steps to reproduce:

I'm creating a form
If I enter"www.disney.it" as exit URL, it is correctly saved but it does not work because the link is composed like this (example)
www.mysite.com/form/www.disney.it 
so it's chained creating an error.

If I enter "http://www.disney.it" and click on apply or save/exit, nothing happens, the changes are not saved and the buttons become unresponsive

This happens at first form creation and in any following edit.

 
### Log errors: 
google dev console says: Failed to load resource: the server responded with a status of 403 (Forbidden)

Similar to:
https://www.mautic.org/community/index.php/836-save-and-close-apply-not-working/0?search=scheduled+email

About this, I already asked to the host provider to "whitelist" the entire development site and I believe that this has been done because other similar issues (such as changing language) now work correctly.
but this still happens.

Please help.
Thanks
Andrea

**Comment by dbhurley** [comment]
Resolved in later releases.
