### ISSUE TITLE
SugarCRM Plugin Blank Fields

### ISSUE THREAD

**Issue by StevenMJones** [mautic/mautic#4746]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Our company is currently using SuiteCRM / sugarCRM version 6.5 and Mautic 2.9.2. We have authorized the SugarCRM plugin and found issues with SugarCRM "Integration fields" not properly syncing with Mautic fields. We discovered pull request #4445 for a similar issue (https://github.com/mautic/mautic/pull/4445) and took those changes. We found that the fix covers most blank fields, but there are two we are still having issues with:

1. Company Mapping > SugarCRM Integration Field "Billing State" to Mautic Field "Core State"
 - For this mapping, we have a value entered in each of our SugarCRM's accounts.billing_address_state fields, but the field appears as blank in Mautic after running the cron job to update all contacts. 
2. Contact Mapping > No SugarCRM "Contacts - Account Name" Available to Map to Mautic Field "Contacts - Core Company" 
- For this mapping, there is no SugarCRM Integration Field for "Contacts - Account Name", which should link the SugarCRM accounts.name db field to the Mautic Field "Contacts - Core Company". After testing, we have found that a SugarCRM Integration Field for "Leads - Account Name" mapping field is availble, but nothing for "Contacts - Account Name". We also attempted to map all three of the SugarCRM Integration Fields listed as "Contacts - Name"with no success. Completing each of the mappings seemed to display the Mautic Field "Contacts - Core Company" as some concatenation of the contact's first and last name. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 

### Steps to reproduce:
Issue # 1. Company Mapping > SugarCRM Integration Field "Billing State" to Mautic Field "Core State"
1. Open the SugarCRM plugin modal window
2. Click the "Company Mapping" tab
3. Map the  SugarCRM Integration Field "Billing State" to the Mautic Field "Core State" along with all other billing address fields to Mautic core address fields
4. Execute the cron job to update all Companies
5. Open a company profile and see all fields are present, but the "State" field

Issue # 2. 2. Contact Mapping > No SugarCRM "Contacts - Account Name" Available to Map to Mautic Field "Contacts - Core Company"
1. Open the SugarCRM plugin modal window
2. Click the "Contact Mapping" tab
3. Browse all four pages to see there is no No SugarCRM "Contacts - Account Name" field
4. Navigate to page 3 to see the  SugarCRM "Leads - Account Name" field
5. Complete all applicable contact mappings 
6. Execute the cron job to update all Contacts
7. Open a contact to see there is no company name assigned 
 
### Log errors: 

No errors were produced, the results appear as blank in the UI.

**Comment by stancel** [comment]
This issue is not working in the latest 2.10.0-beta release / tagged commit as well.

**Comment by stancel** [comment]
Hi @mqueme, could you please take a look at this one when you get a chance?

**Comment by KaKite** [comment]
Still not working in v2.12.1

**Comment by stancel** [comment]
Hi @KaKite, please test pull request #5610 for the fix. If you are setting up any custom fields you will also pull to pull in the code and test pull request #5616. If those work for you like they have worked for us and at least one other, please update the issues for both so the Mautic team knows that they have passed there as well and will hopefully be included in one of the upcoming releases. Thanks.

**Comment by npracht** [comment]
Solved in 2.14.1 according to last @stancel's message
