### ISSUE TITLE
Contacts: No Results Found when filtering by multiple segments

### ISSUE THREAD

**Issue by Vrutin** [mautic/mautic#4749]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Tried filtering contacts with multiple segments but it doesn't seem to be working:

**Tried**
`segment:{alias} AND {alias}`
`segment:{alias} AND segment:{alias}`

Only the first expression is being evaluated anything after the `AND` is being ignored.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.9.2
| PHP version | 7.1

**Comment by RCheesley** [comment]
I can replicate this in 2.15.3.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
