### ISSUE TITLE
Dashboard Map Widgetcontact/lead not showing colors

### ISSUE THREAD

**Issue by khaoua** [mautic/mautic#4753]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | 
| Enhancement? | 

## Description:
Map dashboard widget does not put colors for countries where visitors/leads are tracked with IP, even when anonymous lead is recorded, nothing shows up in term of country to be colored. Leads number shows up well, so only color is the issue

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Could you share a screenshot? The color should be related to percent of contact in the country.

**Comment by khaoua** [comment]
oh, ok, what percent of contact in country? is it a fixed setting? or can it be changed? image is attached
![mautic dashboard map widget](https://user-images.githubusercontent.com/25910708/29921329-7c2ae03c-8e51-11e7-9086-6488148d0b98.JPG)

**Comment by escopecz** [comment]
It's characteristic of the JS library rendering the map. How many leads are in the green countries? The pure green countries are those which has the most visits from. Then the green color fades to grey which is 0 or close to 0.

**Comment by khaoua** [comment]
ok. But the weird thing is that country where having more leads (France) shows 5 leads. Which are actually 2 different IP addresses, with one showing up 4 times. Even when this IP is recorded as a contact (it's my phone IP) it does not gather all the other with it.

Any rules that I missed for color and this contact IP record behaviour of mautic?

**Comment by escopecz** [comment]
I don't know how IP addresses are related, but you can see how the SQL query is generated for the map here: https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Model/LeadModel.php#L2406. Does it answer your question?

**Comment by khaoua** [comment]
:-( not really, I'll make some more test regarding this IP addresses relation

so map lead widget color is active from which number of lead? cause 1 in Italy does not seem enough :-)

**Comment by escopecz** [comment]
I don't know. See how the map looks like for Mautic tracking a live project:
![screen shot 2017-08-31 at 14 24 09](https://user-images.githubusercontent.com/1235442/29923006-2f91ee8a-8e58-11e7-82e3-62bc5c729b32.png)
Since I think the whole issue is in small data set, I'll close this issue.

**Comment by khaoua** [comment]
well, in previous mautic versions I had correct widget color, even with small number of leads. what does it mean, issue is in small data set, anyway to make sure the root cause is known and have a way to correct it?

**Comment by khaoua** [comment]
@escopecz can you give me the number of leads for the countries that are in clear-green color? just to understand better the rule of this widget. As well, if you identify grey countries with only 1 lead, maybe that will confirm that it is normal behaviour, that would be very much appreciated

**Comment by escopecz** [comment]
You can find everything about the map's behavior here: http://jvectormap.com

**Comment by khaoua** [comment]
ok, thanks
