### ISSUE TITLE
Radio group fields (linked to preferred local) ignore user selection and use standard value instead

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#4754]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Radio group fields in forms (linked to "preferred local") ignore user selection and set the standard selection of the form (either set or not) in the contacts "preferred local" field.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.9.2
| PHP version | 7.0.22

### Steps to reproduce:

I created a form with a radio group, allowing the user to select from a language choice "German" or "English" as value.
The field is correctly linked with the core contact field "Preferred Locale".
The standard value of the field in "German" for my German form and "English" for my English form.
I did not set "Use assigned contact field's list choices" as I only wanted them to decide between the two. 
The "Prefered Locale" field has no default value in my system.

My Tests:
1.) Selected the German Form, changed Radio Group manually to "English". The form results table shows correctly "English" for the language selection. However - the "Preferred Local" field in the created contact for the German form shows "German" - the standard value. 
2.) Selected the English Form, changed Radio Group manually to "German". The form results table shows correctly "German" for the language selection. However - the "Preferred Local" field in the created contact for the English form shows "English" - the standard value.
3.) Removed the standard value in the English form, selected Radio Group manually to "German". The form results table shows correctly "German" for the language selection. However - the "Preferred Local" field in the created contact for the English form is empty  - the standard value.

**Comment by dsp76** [comment]
Even more strange. I now send a hidden field for "preferred locale" along with the form, removing the option to select one. It works fine for "German" -> shows up as "Deutsch" in the field for the contact.
It doesn't work for "English" nor "Englisch" -> field remains empty.

As the preferred local shows up translated within the field according to the user interface selection: whats the correct value of this field independently from the user interface setting for Englisch?

**Comment by dsp76** [comment]
Additionally Campaign actions still seem not to allow to set preferred local. 

Version 2.14.

**Comment by escopecz** [comment]
Please test https://github.com/mautic/mautic/pull/6404 if it fixes your issue

**Comment by dsp76** [comment]
@escopecz seems to work now yeah! I can now use the correct locale codes "en", "de" or "de_DE" etc. as field value and submit it to the "preferred locale" field.

Whilst testing it I discovered a different issue. **@escopecz Please let me know your comment, if this might be related to the fix or is already a problem in the master**: I had a custom field "language" defined as mandatory. The form submit filled the "preferred local" value into the custom "language" field, as long as it was mandatory. When I disabled the mandatory option, it mapped the field value correctly as assigned in the form field.

**Comment by escopecz** [comment]
Thanks for testing and confirmation that your issue has a fix!

There shouldn't be any difference whether the fields is required or not. Please create new issue with detailed steps to reproduce.

**Comment by npracht** [comment]
Fixed when #6404 merged.
