### ISSUE TITLE
SugarCRM plugin creates empty leads.

### ISSUE THREAD

**Issue by AndrassGray** [mautic/mautic#4757]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:

I am importing Sugar leads/contacts using the Sugarcrm plugin. In Sugar, some contacts don't have names and/or email addresses. This apparently generates duplicates in Mautic: 

`
mysql> SELECT `email`, `lastname`, count(*) as rows FROM `leads` GROUP BY `email`, `lastname` HAVING count(rows) > 1;

+-------+----------+------+
| email | lastname | rows |
+-------+----------+------+
| NULL  | NULL     |  170 |
| NULL  | Bonesi   |    3 |
| NULL  | Hanaoka  |    3 |
| NULL  | Pentik   |    3 |
+-------+----------+------+
4 rows in set (0.01 sec)
`

My interpretation is that the SugarCRM plugin does not skip lead creation where the email-field is empty. IMO, lastname should be allowed to be empty/null, although a must-fill-field in field-matching.

And while I can create a segment with "empty email" as criteria, this only catches those contacts that have a name, so I can not even delete those combos that have both email and name empty.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| SuiteCRM version | Sugar Version 6.5.24 (Suite Version 7.9.4)
| PHP version | 7.0

### Log errors: 

No corresponding error in Mautic or Apache logs.

**Comment by dbhurley** [comment]
I think this has been addressed. Can you verify if this is still an issue in 2.11?
