### ISSUE TITLE
Automatically merge contacts with the same email when created via batch API

### ISSUE THREAD

**Issue by rorymadden** [mautic/mautic#4759]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | n
| Enhancement? | n

## Description:
I am using the API to batch create contacts. If I try to load in the same contact twice it is being duplicated instead of being merged. My contacts are getting multiple emails. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 5.6.30

### Steps to reproduce:
1. Use the contacts/batch/new api to create a set of contacts (e.g. 100)
2. Use the contacts/batch/new api to create the same set of contacts
3. Expected behaviour: the mautic DB only contains 100 contacts. The contacts are merged on creation.
4. Actual behaviour: the mautic DB has 200 contacts - each contact appears twice

**Comment by zuznow** [comment]
Is there a way to bypass the bug?

**Comment by escopecz** [comment]
This is working properly for some time and it's covered by functional tests in Mautic 2.13.1 so it won't easily break.
