### ISSUE TITLE
Contact Detail Page bug with Video Events (Class 'InputHelper' not found)

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#4760]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

Mautic 2.10.0-beta throws error on open contact detail page with Gated Video Events

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

[2017-08-31 17:42:07] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'InputHelper' not found - in file /var/www/mkt.mydomain.com/htdocs/app/bundles/PageBundle/Views/SubscribedEvents/Timeline/videohit.html.php - at line 55 [] []

**Comment by escopecz** [comment]
Are you sure you are on 2.10.0-beta? There is no occurrence of the InputHelper class in the videohit.html.php file nor on line 55: https://github.com/mautic/mautic/blob/staging/app/bundles/PageBundle/Views/SubscribedEvents/Timeline/videohit.html.php#L55

I also tried to replicate viewing a contact with a videohit event, but it loads just fine.
![screen shot 2017-09-01 at 08 56 30](https://user-images.githubusercontent.com/1235442/29958539-825c1da2-8ef3-11e7-8f0d-3e8cc2355520.png)

**Comment by luizeof** [comment]
@escopecz yes .. I 'm testing 2.10.0-beta.

There are another way to find or test why the contact page do not open?

**Comment by escopecz** [comment]
What do you have on that line?

**Comment by luizeof** [comment]
@escopecz when I open an Contact Detail Page ... I get this an error 500 and this is added to my log

[2017-09-01 08:27:50] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'InputHelper' not found - in file /var/www/mkt.powertic.com.br/htdocs/app/bundles/PageBundle/Views/SubscribedEvents/Timeline/videohit.html.php - at line 55 [] []

**Comment by luizeof** [comment]
But only contacts that has Video Events ... new contacts or contacts that not has video events do not throw errors

If Open the Page on a New Tab ... I get this

![download](https://user-images.githubusercontent.com/257004/29967996-f9a54b30-8eef-11e7-8505-7692ceff6c2a.jpeg)

**Comment by escopecz** [comment]
Ok, but what do you have in file app/bundles/PageBundle/Views/SubscribedEvents/Timeline/videohit.html.php on line 55?

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/4873

**Comment by npracht** [comment]
Hello @escopecz it can be closed :)
