### ISSUE TITLE
Since 2.9.2, Vtiger Plugin dialog is hanging

### ISSUE THREAD

**Issue by justinroffmarsh** [mautic/mautic#4762]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
After upgrading to 2.9.2 the Vtiger plugin has stopped working. Additionally, if I attempt to open the plugin the dialog hangs with the word "loading".

This is my vtiger URL: https://ballistix.ballistixcrm.com
It was running SSL prior to the upgrade and working fine.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.9.2
| PHP version |  5.6.31

### Steps to reproduce:
1. Start with Mautic 2.9.1, authenticate Vtiger plugin with Vtiger instance, map fields and ensure that Push to integration works
2. Upgrade Mautic to 2.9.2, test Push to Integration and try to open plugin dialog.
 
### Log errors: 

No relevant errors

**Comment by escopecz** [comment]
Please provide the errors from your log.

**Comment by justinroffmarsh** [comment]
Here they are.

http://ballistix-mautic.ballistixmail.com/error-2017-08.txt

**Comment by npracht** [comment]
Hello @escopecz it can be closed :)

**Comment by sensalot** [comment]
Keep in mind that a popup will show while authenticating the plugin. Make sure the popup isn't blocked
