### ISSUE TITLE
Use a Worker Queue for jobs

### ISSUE THREAD

**Issue by gopi-ar** [mautic/mautic#4766]
What type of report is this:

| Q  | A
| ---| ---
| Enhancement | Yes

## Description:

Judging from the spaced out timings on crontab, it's likely mautic want's to prevent race-conditions / cron overruns. We use PHP internally with our APIs and we use the following measures to prevent issues with minutely crons:

1. Use `run-one` that ensures that only one instance of a cron is running
2. Use a worker queue like `beanstalkd` for things like campaign updates, and more importantly, sending emails.

This way updates happen more frequently and there's no chance of an email being sent twice unintentionally. We don't have spare resources otherwise would have loved to contribute features. Also end users don't have to wonder why their segments / campaigns haven't fired yet (they have to wait ~15 minutes for changes to show).

**Comment by luizeof** [comment]
@gopi-ar Mautic 2.10 introduces an lock file on #4337 pull
