### ISSUE TITLE
2.9.2 Twitter Social Monitoring not working

### ISSUE THREAD

**Issue by khaoua** [mautic/mautic#4767]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | **yes**
| Feature request? | 
| Enhancement? | 

## Description:
Twitter app set up correctly, though it asked to map email field to validate app authorisation, so core email is selected; Plugin installed, published, twitter authorisations fully granted. 
I then set up a segment for twitter mentions/htags, 2 twitter social monitoring (htag, and mentions)
cron's in cpanel run ok but keeps going with result below : 

Executing Monitor Item 1
No new tweets
Result Code: 0
Executing Monitor Item 2
No new tweets
Result Code: 0
Content-type: text/html; charset=UTF-8

Htag created on twitter did not trigger anything when htag monitoring was tested
Twitter mention @...  did trigger a creation of a contact twice at the same time (named with twitter account name) when twitter mention monitoring was tested

mention segment was not updated, although "Add contact to selected segment(s)" is active with specific segment into it

update 04/09/2017
tried with cron /app/console social:monitor:twitter:hashtags
got this:
--mid option cannot be empty
Content-type: text/html; charset=UTF-8

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by khaoua** [comment]
if it's normal behaviour for non recorded contacts, I will delete this issue. Just recorded a contact, and htag worked this way

**Comment by khaoua** [comment]
as shown below hashtag monitoring, it is the only social monitoring showing figures out of 3 (2 hashtags and 1 mention), contact is recorded, contact social tab shows twitter but the monitoring is acting weird, as we have counts but not the contact
![image](https://user-images.githubusercontent.com/25910708/30027850-e752a03c-9182-11e7-8bf9-00c4931ad95c.png)

**Comment by khaoua** [comment]
cron mautic:social:monitoring give the following result

Executing Monitor Item 1
Updating existing lead ID #13 (xxxxx) Result Code: 0 Executing Monitor Item 2 Updating existing lead ID #12 (xxxxxxx) Result Code: 0 Executing Monitor Item 3 No new tweets Result Code: 0
Content-type: text/html; charset=UTF-8

item 1 is hashtag, social monitoring is the one that get counts and no contact in contact tab
item 2 is mentions, social monitoring shows no counts and no contact in contact tab
item 3 is hashtag, social monitoring shows no counts and no contact in contact tab

beware that all is done for an existing contact recorded, with a twitter existing in contact social tab, when clicking on update icon, all tweets are shown
![image](https://user-images.githubusercontent.com/25910708/30028828-e8917df2-9186-11e7-8f4c-11a9beee1178.png)

**Comment by dbhurley** [comment]
Is this still an issue in 2.11 or 2.12?
