### ISSUE TITLE
Focus not show predefined field values for Select Custom Field

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#4768]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

When create an custom field type Select with predefined values, this values appear normally on forms included via script or HTML but not shown on Focus Modal or Popup.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0

### Steps to reproduce:
1. Create an custom field (Select type) and populate with sample values
2. Create an form including this Field and use Yes on Properties Tab for import field default values
3. Create an Focus popup or modal and use this form
4. The select field is shown empty on your website
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by johbuch** [comment]
i just got this bug in 2.12.2
if clicking on YES on properties tab, it does not show values on the focus.
But clicking on NO and filling you the different values, it will show it on the focus

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/5922 
Label: Ready to test

**Comment by npracht** [comment]
@luizeof i tested and it works. Maybe you can also test ?

**Comment by npracht** [comment]
Label: Pending test confirmation

**Comment by npracht** [comment]
Fixed in #5922 and merged
