### ISSUE TITLE
Import of multiple contact lists in background stops

### ISSUE THREAD

**Issue by YFilus** [mautic/mautic#4769]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I added some contact lists for import in background:

- 1st cronjob - one small list imported just fine
- 2nd - imported big list partially - status 'In Progress'
- 3rd - imported another big list partially - status 'In Progress'
- 4th - another list - status 'Delayed'
- No more changes after that

![import](https://user-images.githubusercontent.com/6909420/30042025-eb7492f0-91c4-11e7-80f3-ce7e96d4f86f.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.1.7

### Steps to reproduce:
1. Import some big contact lists in background
 
### Log errors: 

Cronjob always return:

Import 19 with 3283 is rows starting.
mautic.lead.import.delayed
Import failed. Reason: Import was delayed because the parallel import limit of 1 has been hit.

**Comment by escopecz** [comment]
It should not fail, but set itself to the Delayed state as I can see on your screenshot. There is a limit on how many imports can run in parallel to prevent server running out of memory or other resources. Are you saying that all imports stopped and never finished? Do you run the import command manually or is it run periodically as a cron job?

**Comment by YFilus** [comment]
Periodically as a cron job, each 15 minutes. All imports stopped.

After some hours those 2 'In Progress' imports changed status to Failed, with Status info - "The import hasn't been updated in 2 hours by the background job. It's considered failed".

And the process of partially import and then go to status Failed happened again with some of the lists imported. All fails with the same Status info.

![imports mautic](https://user-images.githubusercontent.com/6909420/30072131-bcef48be-923f-11e7-9d43-06195647947d.png)

**Comment by escopecz** [comment]
I was trying to replicate your issues and found 2, fixed here: https://github.com/mautic/mautic/pull/4797. But it didn't fail for me. Do you get some error messages in the Mautic error log?

**Comment by YFilus** [comment]
Nice!
Sorry, I deleted the logs in the meantime =/
Only one import only goes fine.

**Comment by npracht** [comment]
Hello @escopecz it can be closed :)
