### ISSUE TITLE
Custom HTML emails do not trigger open events in campaign

### ISSUE THREAD

**Issue by LunarDevelopment** [mautic/mautic#4771]
| Bug report | 

## Description:
Campaigns do not show opens in their report & don't trigger events on is/isn't opened if using the Code Mode email feature. 

My campaign Open events only trigger if the email body sent is one of your pre-defined theme emails (note that the Blank theme doesn't work either). 

I've looked through the twig.html files in a theme that does track opens and can't see any special mark up for tracking opens - meaning it's server side logic based on tracking GIF. 

How can I get campaign events to trigger via opens on campaign builder if I'm using a custom html email ? 

-- 
Opens are registered against the messages sent in DB, just not in a campaign. 

The database shows an email as read and opened: 
DB table `email_stats`
shows 
`open_count` = 14 
`is_read` = 1 

The email html shows a valid and working tracking pixel as 
`<img height=3D"1" width=3D"1" src=3D"http://DOMAINISHERE/email/59ae56775b6a7.gif" alt=3D"" />`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.9.2
| --- | ---
| PHP version | 7.0 

### Log errors: 
No Errors in mautic or server error logs but in Mautic's notifications drop down I'm getting: 
```
Failed to execute campaign event for COMPANYNAMEOMITED.
YET ANOTHER TEST CAMPAIGN/ open
Today, 11:48 am
```

**Comment by LunarDevelopment** [comment]
I've worked it out: 

Custom HTML emails do not count as opens in a campaign structure. 

Is there a work around or something for this as this behavior not covered in your docs that I've been able to find and it renders the campaign builder moot unless I want to send boilerplate off brand templates..

**Comment by jqvanet** [comment]
Hi, 
Did you find a solution?
Got the same problem.

**Comment by jowa4014** [comment]
@LunarDevelopment Did you find a solution? We have the same problem as well.

**Comment by Lewom** [comment]
@LunarDevelopment Did you find a solution? We have the same problem as well.

**Comment by elliott-io** [comment]
Having the same problem. With a custom "Code Mode" html email, I am seeing opens, but link clicks are not being tracked. Any ideas?
