### ISSUE TITLE
Enable passing cookie value to Mautic when using a non Mautic form

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4775]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a Mautic user I want to be able to pass a cookie value to Mautic when using a non Mautic form so that I can merge activity for unknown contacts that become known contacts and enable all activity to be tracked on the same contact

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
In 2.11

**Comment by sergiybond** [comment]
Are there instructions or at least a general overview as to how this can be done? It's great that this was enabled, but some documentation would be greatly appreciated. Thank you in advance 😃

**Comment by joonasy** [comment]
Are there any documentation about this somewhere? Thanks!

**Comment by spsinghats** [comment]
I am using 2.15.2, and could not make this work. I have a website with the tracking pixel set, I do login using my own form and on the server side send the mautic contact id from the cookies to the form submission after login to mautic. The cookie in the website does not update and keeps showing the old mautic contact id. Please provide guidance on how to make this work properly.
