### ISSUE TITLE
Enable customizing the design for the preference center page

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4776]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a Mautic admin user I want the ability to edit text labels and format and apply themes to Preference center landing page using a WSYWYG interface

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Related to https://github.com/mautic/mautic/issues/2946 ?

**Comment by virlatinus** [comment]
Solved in #4779
