### ISSUE TITLE
Dynamic content for unknown visitors

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4783]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a Mautic user I want to serve up dynamic content on my website to anonymous visitors based on their IP so that I can show relevant content and improve conversion of unknown visitors to known contacts

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ninjoan** [comment]
But you can do this with previous version (in my case i use DWC base on location of the unknown content to show content base in that country)

**Comment by matishaladiwala** [comment]
You are correct and this needs to be made available outside of campaigns too.

**Comment by virlatinus** [comment]
Solved in #5038
