### ISSUE TITLE
Messaging on LinkedIn

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4785]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a Mautic user I want to create and schedule broadcast campaigns on LinkedIn so that I can send messages to all my connections in their feed

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by spsinghats** [comment]
@dbhurley I cannot find this feature, but the issue is closed. Please point me to the repo.

**Comment by npracht** [comment]
Hi @spsinghats this feature is not existing yet. But we don't manage feature request on Github (bugs here). Feature request will be manage on the website (the new website is gonna be launched very soon).

**Comment by evgu** [comment]
@npracht do you have the website where we can post this as a feature request? LinkedIn messaging and tracking of contacts on Mautic is somewhat paramount for B2B marketing these days. Many Thanks!!

**Comment by npracht** [comment]
--> https://forum.mautic.org/c/ideas/14
