### ISSUE TITLE
Click through to details on reports

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4792]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a user I would like to be able to click through from a summary email report to a detail report so that I can better analyze and action my results
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ronnieduke** [comment]
I would add that it would be great to click on items displayed in the report to go to the detail of that item. For example, if the report shows the contact name, have it hyperlinked to view details of that contact. If it's a form, link to the form details, etc.
