### ISSUE TITLE
Summary report for key metrics

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4795]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a user I would like an out-of-the-box email report that shows me a summary of key metrics for my emails so that I can easily see sent, open and click rates for all emails I have sent"
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ankitpr89** [comment]
This should be user account based analytics, which actually should not be limited only to emails, this should include all the channels.
