### ISSUE TITLE
Direct to last page when auto logged out

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4804]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a user when I am logged out of the product I would like to be taken back to the page I was on to save me the time of navigating back to the page I was working on

**Comment by alanhartless** [comment]
This needs to be validated that it's a problem. By default Symfony stores the last page in the session and returns to it on login. Maybe there's a scenario somewhere that this does not happen.
