### ISSUE TITLE
Preview campaigns without opening builder

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4806]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a user I want to give certain user roles the ability to preview campaigns so that I can manage access to these and also so that Ic an quickly see what is in the campaign without having to edit it

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
https://github.com/mautic/mautic/pull/4912
