### ISSUE TITLE
Undo/redo button on builder

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4807]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
 As a Mautic user I want to be able to undo/redo from the builder (campaign, email, page) so that I can revert to different versions to make me more efficient

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by saschafoerster** [comment]
@dbhurley I just wanted to ask for this feature. What was the reason to close the issue? @matishaladiwala Do you know maybe?
