### ISSUE TITLE
Search Improvements

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4809]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
As a user I want to be able to easily search items in the list view without having to use the "%" sign as this is not intuitive
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ronnieduke** [comment]
@dbhurley - are these features no longer on the roadmap? I was really looking forward to this one....

**Comment by dbhurley** [comment]
Definitely making improvements to search, just not closing this until someone decides to work on it! Happy to reopen if there's interest but an old feature request that has no comments doesn't get to sit around forever. 😉

**Comment by ronnieduke** [comment]
@dbhurley gotcha - I was under the impression that these were added to the milestones based on customer requests. I know I've talked to my CS manager about many of these.
