### ISSUE TITLE
Segment Detail Page

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4828]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
As a Mautic user, when I click on a Segment on the summary page, I want to see a detail page that shows me contacts in the segment and the activities that the segment is a part of
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
this was done in 2.12
