### ISSUE TITLE
Unable to download mautic

### ISSUE THREAD

**Issue by datlarv** [mautic/mautic#483]
Hi 
I am unable to download the Mautic from www.mautic.org website. I am attaching here with error screenshot.
![mauticdownloaderror](https://cloud.githubusercontent.com/assets/12659811/7883110/9e19d50e-0631-11e5-827b-72839d93e0c0.png)

**Comment by dbhurley** [comment]
Thanks for letting us know! We're working on it right now :+1:

**Comment by dbhurley** [comment]
Should be fixed now!
