### ISSUE TITLE
Segment detail page

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4839]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
As a Mautic user, when I click on a segment on the summary page, I should be able to get to a detail page (and not the edit page) that shows me campaigns leveraging the segment and contacts (filterable) that are part of the segment, so that I can better understand how the segment is being used.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
duplicate
