### ISSUE TITLE
Custom objects in Mautic

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4857]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a Mautic user, I want to create custom objects in Mautic that are 1, 2 or 3 levels away from the standard objects in Mautic so that I can further customize Mautic to align with my marketing process and so that I can sync these to custom objects in my CRM tool.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by intellisense** [comment]
This is the only reason I am still not able to use Mautic, we need to have facility to build relationships from contact to its many associated objects (one to many relationships), and use it for:
- Custom object data for segments
- Triggers on custom objects for campaigns
- Tokens for qualified custom object to be used in email creation.
- and much more..

Is there any ETA on [2.14.0](https://github.com/mautic/mautic/milestone/40)? If i knew php I would be happy to help in this feature.

P.S I see there are lots of external tools integrations tasks in [2.14.0](https://github.com/mautic/mautic/milestone/40) milestone, if this task has higher importance and could be implemented in its own milestone without being delayed on other tasks that will be great.

**Comment by luxuryrealtygroup** [comment]
Nice feature request
