### ISSUE TITLE
Enhance Salesforce Integration to include Opportunities

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4858]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a Mautic user I want to bring data from Salesforce Opportunities onto the contact and company objects in Mautic so that I can trigger campaigns based on this data
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ronnieduke** [comment]
I couldn't add more than one "hooray" reaction, so I'll just say it again here ;-)

**Comment by ronnieduke** [comment]
@dbhurley - closed because it's added already, or accounted for somewhere else?

**Comment by dbhurley** [comment]
Relevant message here: https://mautic.slack.com/archives/C02HV76BW/p1511798235000275
Also, FWIW, this is one that is definitely in the works already.
