### ISSUE TITLE
Bring in data from LinkedIn to enhance contact info

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4860]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a marketing user I want to bring in data from Linkedin to enhance my contacts profile in Mautic
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
I might be missing something, but this is achieved with fullcontact integration, would this become something available in core?
