### ISSUE TITLE
Integration to Magento for eCommerce

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4861]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a user I want to leverage data from Magento in Mautic so that I can use this to trigger campaigns

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Valentyn-Kubrak** [comment]
Hi @matishaladiwala ,
We created custom extensions for Magento (currentyl for v.1.9) that you can use for uploading customer from Magento to Mautic. 

Please check: 
https://magedirect.co/solutions/magento-mautic/
https://github.com/MageDirect/magento-mautic-integration

**Comment by comunidademagento** [comment]
Hi,

We try install this extension with composer.

https://github.com/MageDirect/magento-mautic-integration

See composer.json

http://magento-48796-343999.cloudwaysapps.com/composer.json

{
   "minimum-stability": "dev",
   "prefer-stable": true,
    "license": [
        "proprietary"
    ],
    "repositories":[
     {
        "type": "vcs",
        "url": "git@github.com:MageDirect/magento-mautic-integration.git"
    }
    ],
    "require": {
	"MageDirect/magento-mautic-integration": "1.0.0"
     }
}

![captura de tela de 2017-10-08 12-29-52](https://user-images.githubusercontent.com/7476455/31318189-6f0cc582-ac24-11e7-8fa5-d9387b2888a9.png)

**Comment by magefan** [comment]
For Magento 2 you can use [Magento 2 Mautic Extension](https://magefan.com/magento-2-mautic-integration-extension) by [Magefan](https://magefan.com/magento2-extensions). With this extension you can send this data to Mautic: 
 - customers
 - orders (including guest orders)
 - subscribers
 - customer revies

All API calls to Mautic are running asynchronously by cron to do not slowdown Magento store.

It also implements Mautic Js Tracking on the website and has fields mapping to map magento2 - Mauitc contact fields.

Here is a[ Magento 2 Mautic Module Demo](https://mautic.demo.magefan.top/admin/).
