### ISSUE TITLE
Integration to Stripe

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4862]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a user I want to leverage data from Stripe in Mautic so that I can use this to trigger campaigns.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ankitpr89** [comment]
And PayPal?

**Comment by RCheesley** [comment]
Good to see!
