### ISSUE TITLE
Integration with Survey tool

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4864]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a Mautic user I would like Mautic to integrate with a survey tool such as survey monkey so that Ic an send out surveys as part of campaigns 
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ankitpr89** [comment]
Having Integrations with these would be a great combination:

- Polldaddy
- Survey Nuts
- SurveyPlanet
- SurveyLegend
- SurveyMethods
- Survs
- FreeOnlineSurveys
- SurveyMonkey
- QuestionPro
- SmartSurvey
- Surveypal
- FluidSurveys
- QuickTapSurvey
- Obsurvey
- Survmetrics
- PopSurvey
- SurveyGizmo
- LoopSurvey
- Client Heartbeat
- LimeSurvey

**Comment by awurman** [comment]
SurveyMonkey is one of the best i think

**Comment by derektruffle** [comment]
In the spirit of open source, perhaps LimeSurvey should be the priority, although I've heard of few of these so maybe some of the others are also open source.
