### ISSUE TITLE
Integration with Slack

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4865]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
Slack: As a Mautic user I would like to send notifications to users on Slack as part of a campaign so that this is an additional communication channel for me
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by yourdigitalclub** [comment]
currently possible with webhooks and zapier but would be great to have native to mautic
