### ISSUE TITLE
Custom field mapping missing after update

### ISSUE THREAD

**Issue by rc125** [mautic/mautic#4870]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
After the update I am unable to select "Use assigned contact field's list choices" when creating a form with custom field.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.0
| PHP version | 7.0

### Steps to reproduce:
1. Update
2. Try to create a form with a custom field
 
### Log errors: 
![Image of Yaktocat](https://even3storage.blob.core.windows.net/assets/Captura%20de%20Tela%202017-09-06%20a%CC%80s%2022.33.12.png)

**Comment by dbhurley** [comment]
Not replicable (2.12)
