### ISSUE TITLE
Cloning a mail with an angle bracket inside of an HTML attribute breaks the clone's html

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#4872]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✓
| Feature request? | 
| Enhancement? | 

## Description:

Cloning a mail with an angle bracket inside of an HTML attribute breaks the clone's html

![Screencast](http://g.recordit.co/oQ6lTiPGM5.gif)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 5.6

### Steps to reproduce:
1. Create an email
2. Add a button
3. Edit the button's text so it starts with a `>`
4. Clone that email
5. Save and preview the clone

### Log errors: 

> N/A

**Comment by npracht** [comment]
@kuzmany can you tell if still relevant please ?

**Comment by kuzmany** [comment]
Not reproduce on M3
