### ISSUE TITLE
#Bug - When you choose a campaign sending date

### ISSUE THREAD

**Issue by jdecampos** [mautic/mautic#4876]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 
| Language | French

### Steps to reproduce:
1. Create campagne
2.  Actions : send an email
3. choose a date of sending
4. Message error : "Cette valeur n'est pas valide."

See attachement

### Log errors: 

<img width="587" alt="capture d ecran 2017-09-08 a 11 12 20" src="https://user-images.githubusercontent.com/14194414/30204700-ad6ea968-9486-11e7-8206-d6c34e9afa37.png">

**Comment by johbuch** [comment]
Hello I also get this issue.
I erased the last 2 numbers (the seconds) and then I was able to validate.

**Comment by kuzmany** [comment]
Can' reproduce.  
Tested windows, linux Mautic 2.10.1 and actual staging
Do you have som Mautic where issue is affected?

Did you try run:
rm -r app/cache/prod/* (clear cache)
php app/console m:a:g (regenerate assets)
php app/console doctrine:schema:update --force (update db schema if not actual)

**Comment by jdecampos** [comment]
Hi @johbuch, @kuzmany ,

@kuzmany : Did you get into French?
@johbuch : Your solution works, thank 👍

**Comment by jdecampos** [comment]
@kuzmany After testing the lines of code, I still have the problem

**Comment by nethunter** [comment]
I'm still experiencing this issue on 2.14.0

**Comment by johbuch** [comment]
indeed I just tested and I can see the same bug.
To avoid it, we have to erase seconds

**Comment by npracht** [comment]
Please test https://github.com/mautic/mautic/pull/5374

**Comment by alanhartless** [comment]
Seems this was fixed in 2.14.2.
