### ISSUE TITLE
Updating overwrites htaccess file

### ISSUE THREAD

**Issue by robwent** [mautic/mautic#4879]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
When updating to the latest 2.10, the .htaccess file is overwritten which wipes out custom configuration.

I have one install in a siteground account where the default php version is 5.3 and changing the version in cpanel adds an `AddHandler` line to the bottom of the file to switch versions.
The only way to update in this case without an error is to use cli as unpacking the update zip prevents any further php commands from working through a browser.

If any updates to the htaccess file are non-critical for the operation of Mautic, could the changes be logged as a notification rather than wiping out the whole file?

Or maybe something similar to Wordpress where all the mautic specific rules are contained within a block which can be updated without touching other custom rules?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | various

**Comment by dbhurley** [comment]
Fixed in 2.11
