### ISSUE TITLE
class="mauticform-label"" <= extra quotes

### ISSUE THREAD

**Issue by pitus** [mautic/mautic#488]
Just noticed that the form generator outputs extra double-quotes after the class="mauticform-label" - just add a couple of text fields to the form to see it in the source code generated (using manual copy for example)

Although, this is rather harmless - the form seems to work still as the browser ignores the extra quote, it may be worth fixing.

P.S. using 1.0.5 but I think the problem has been there even before 1.0.3

**Comment by escopecz** [comment]
Thank for this bug report! I can confirm I also had 2 double-quotes in the generated form HTML. But when running the latest development code and re-saving the older form, there are only 1 double-quotes.

The code creating label classes had been rewritten in these commits 11-12 days ago:
https://github.com/mautic/mautic/commits/staging/app/bundles/FormBundle/Views/Field/field_helper.php

Therefore this will be solved in the next version 1.0.6. Closing this issue.
