### ISSUE TITLE
Social Login (Facebook) pre-fill fields bug when "name" in Field HTML name

### ISSUE THREAD

**Issue by Rixita** [mautic/mautic#4891]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
When the "Field HTML name" for the firstname and / or lastname field has the word "name" in it, the field is pre-filled (when using social / facebook login) with the full name instead of just the first and / or last name.
I have to name the "Field HTML name" just "first" for the first name and "last" for the last name.
That way the fields are filled the correct way.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.0
| PHP version | 5.6.31

### Steps to reproduce:
1. Install and configure Facebook plugin
2. Setup a form with fields for the first name and last name
3. Call the field "First name" and / or "Last Name"
4. Match with the appropriate lead field
5. Rebuild cache for the form
6. Visit form and try to login with the social (facebook) login.
7. Each field (first name, last name) will be filled with the complete name. For ex. the first name field is filled with "John West" instead of just with "John".
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
