### ISSUE TITLE
BUG: Hubspot Mautic Plugin can create duplicate contacts in Mautic resulting in angry subscribers!

### ISSUE THREAD

**Issue by PauloMcGuinee** [mautic/mautic#4895]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
I have confirmed this within the Mautic forums with other users. Because the Hubspot Plugin uses the email address as a identifier key, if you update an email address in Hubspot - once synced to Mautic Mautic creates a new contact record for the amended email address whilst retaining the contact record with the old email address. 

In a live environment this means that if someone replies by email to a campaign to unsubscribe or to express some interest - but uses a different email address. (It could be the prospects company name changed and the old address is being forwarded to a new domain) if you then update the primary email in the Hubspot and mark as unsubscribed or change the sales stage the old record in Mautic remains unchanged and therefore is likely to be re-marketed to making for an awkward or damaging situation. 

It feels to me that a better solution would be to attach the Hubspot contact ID to the Mautic Contact in some way so that it can be used to check Mautic contacts that have already synced and keep them synced with corresponding Hubspot record - rather than relying on the email address which can be changed and therefore not a reliable "key"
 
## If a bug:

| Q   | A
| --- | ---
| 2.9 and 2.10BETA | 
| 5.1 & 7.01 | 

### Steps to reproduce:
1. Setup Hubspot CRM and install Mautic Hubspot Plugin (2 way sync) and CRONs
2. Create a contact in Hubspot CRM i.e Mr Joe Bloggs   -   jbloggs@company.com
3. Wait for it to Sync to Mautic
4. Update the Hubspot contact's email address  -  joe.bloggs@company.com
5. Wait to Sync with Mautic
6. 2 Duplicate Records will now exist in Mautic for each of  jbloggs@company.com and joe.bloggs@company.com

So even if you manually unsubscribed or changed the sale stage for joe.bloggs@company.com you will still have a record in Mautic that will be included in future campaigns and cause you problems.

**Comment by dbhurley** [comment]
Duplicate
