### ISSUE TITLE
Campagins: false information when campaign is proceeded with unpublished e-mail

### ISSUE THREAD

**Issue by dakur** [mautic/mautic#4897]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When a campaign with unpublished e-mail is proceeded, everything looks like it proceeded well, but no e-mail were sent. Even more, the graph is saying, that e-mails **were** sent!  
![snimek z 2017-09-11 16-15-47](https://user-images.githubusercontent.com/9862581/30279130-a4ba5ee2-970c-11e7-9b29-7c3a764c8dd7.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.1
| PHP version | 5.6.30

### Steps to reproduce:
1. Create an e-mail and publish it.
2. Create a campaign and add action `Send e-mail` with the created e-mail and publish it.
3. Unpublish the previously created e-mail.
4. Process the campaign.
 
### Log errors: 

I found no logs.

**Comment by dakur** [comment]
Related to #2375

**Comment by dbhurley** [comment]
Duplicate.

**Comment by dakur** [comment]
@dbhurley Duplicate of what? I was searching for it and did not find any issue.
