### ISSUE TITLE
Feature request - Ability in the builder to copy/paste block elements (slot types, section types or more)

### ISSUE THREAD

**Issue by khaoua** [mautic/mautic#4901]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | yes
| Enhancement? | 

## Description:
When using the builder, sometimes, it gets more productive to copy an existing block element than making a drag and drop all the time. It would be greate to have a copy function, for example with a copy icon next the "close element icon" represented by the X. Like this, it would be like some existing functions in wordpress themes, and make the builder more efficient, to avoid zooming out, drag and drop slowly at the right place. Building is repetitive but losing time in repetitive actions makes it even longer. 
When user copy a slot/section element, it would switch to paste mode with ability to choose the layout place where to paste like when droping the element. 
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 

### Steps to reproduce:
1. Copy element
2. Paste smoothly in any section
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by phuongncn** [comment]
Voted!

**Comment by khaoua** [comment]
thanks, hope it will be considered
@escopecz what do you think, feasible?

**Comment by funkizer** [comment]
Any news? I'd love this (or our copywriters and company bottom line would)!

**Comment by escopecz** [comment]
Section cloning was added in #5036

**Comment by funkizer** [comment]
Grreat, thank you sir!

**Comment by npracht** [comment]
Hello @escopecz it can be closed :)
