### ISSUE TITLE
bug - Form Email to user are stored in contact timeline

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#4902]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When you add an email to user on the form action, the email sent to user is stored in the contact (the one who submitted the form) timeline. One email for each user emailed.

It is very weird and confusing as far as we understand that the contact himself received the "notification".

![capture d ecran 2017-09-12 a 15 29 58](https://user-images.githubusercontent.com/14075239/30328455-aea25662-97cf-11e7-91d3-982fa83c9849.png)
![capture d ecran 2017-09-12 a 15 29 44](https://user-images.githubusercontent.com/14075239/30328456-aeaa3044-97cf-11e7-928b-a0849c69e675.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/5529
