### ISSUE TITLE
Error when trying to configure Company mapping in Zoho CRM

### ISSUE THREAD

**Issue by starcher26** [mautic/mautic#4903]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
When I try to configure "Company Mapping" in Zoho CRM Plugin, I still have the error "At least one required field is not mapped.", even if the only required field "Account Name" is already set (with "Company Name" mautic field)

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.10.0
| PHP version |  7.1.7

### Steps to reproduce:
1. Authorize your zoho account with the mautic Zoho CRM module
2. In "Features" tab, check all the enabled features
3. Then check all the Zoho Object Contacts, Leads and Accounts.
4. Apply.
5. In "Company Mapping" tab, map "Account Name" with "Company Name". Then "Apply" and "Save & Close".

The error message, in "Company Mapping" tab, should still be there...
 
### Log errors: 

Unfortunately, there is no error in app/log/*.log.

**Comment by virlatinus** [comment]
I just configured Zoho and I was able to complete Company mapping using only Account Name. I did not get the error. 

The log files are app/log/*.php

If you are able to use dev mode (index_dev.php), then in the log file `app/logs/mautic_dev-YYYY-MM-DD.php` you will find the request and response messages between Zoho and Mautic. It will help you debug.

**Comment by starcher26** [comment]
Thanks for your answer ! I followed what you mentioned this morning. I didn't find much in the log files. So I completely reset Zoho CRM plugin settings by modifying directly the database (absolutely not a good practice, I guess...). Then, I reconfigured the plugin and did some integration tests. Everything is working fine now.
I don't know what happened...
Anyway, thanks for your help !
