### ISSUE TITLE
Changing date in dashboard causes 500 error

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#4906]
What type of report is this: | Bug report

## Description:
When changing the start date in the dashboard to 3 months prior to today, 500 internal server error occurs.

Mautic is unusable, I cannot reset the dashboard settings to regain access.

## If a bug:
| Mautic version |  2.10.0
| PHP version | 7.0.22-0ubuntu0.16.04.1

### Steps to reproduce:
1. Open mautic dashboard change the start date to a month earlier, click apply then view
2. Repeat until error occurs, it happened when I went 3 months back
3. Dashboard is completely inaccessible, other pages work if accessed directly via their URL
 
### Log errors: 

mautic_prod log file

>[2017-09-13 08:46:52] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT DATE_FORMAT(t.date_hit, '%Y %U') AS date, COUNT(distinct(t.lead_id)) AS count FROM sdpage_hits t WHERE t.date_hit BETWEEN ? AND ? GROUP BY DATE_FORMAT(t.date_hit, '%Y-%m-%d') ORDER BY DATE_FORMAT(t.date_hit, '%Y %U') ASC LIMIT 10' with params ["2017-07-14 00:00:00", "2017-09-13 08:46:52"]:  SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sd_domain_name_mt.t.date_hit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" at /var/www/sites/domain/sd-domain-name/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT DATE_FORMAT(t.date_hit, '%Y %U') AS date, COUNT(distinct(t.lead_id)) AS count FROM sdpage_hits t WHERE t.date_hit BETWEEN ? AND ? GROUP BY DATE_FORMAT(t.date_hit, '%Y-%m-%d') ORDER BY DATE_FORMAT(t.date_hit, '%Y %U') ASC LIMIT 10' with params [\"2017-07-14 00:00:00\", \"2017-09-13 08:46:52\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sd_domain_name_mt.t.date_hit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/sites/domain/sd-domain-name/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sd_domain_name_mt.t.date_hit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/sites/domain/sd-domain-name/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sd_domain_name_mt.t.date_hit' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/sites/domain/sd-domain-name/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []

**Comment by dbhurley** [comment]
Cannot replicate.
