### ISSUE TITLE
Campaign schedule being rejected when using date/time picker

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#4907]
What type of report is this: Bug report?

## Description:

When creating a new campaign(or cloning an existing one) I've entered the publish at and unpublish at dates and they are being rejected. The date/time picker generates a hh:mm:ss timestamp rather than hh:mm

![image](https://user-images.githubusercontent.com/10385295/30357604-e10bd408-9882-11e7-9e0a-674505f9ff41.png)

| Mautic version |  2.10.0
| PHP version |  7.0.22-0ubuntu0.16.04.1

### Steps to reproduce:
1. Create or clone a campaign
2. Select a publish date with a future value
3. Select an unpublish date with a future value that is also after the publish date
4. Note the rejection of the date/time

Manually removing the :ss block overcomes this issue
![image](https://user-images.githubusercontent.com/10385295/30357819-1a17b14e-9884-11e7-97fd-7906e1c74e1e.png)

![image](https://user-images.githubusercontent.com/10385295/30357941-d79af564-9884-11e7-86e2-1b3c8f03b8c2.png)

### Log errors: 

There were no error logs produced during this bug reproduction. Are there any browser console logs I should view?

**Comment by pavel-janicek** [comment]
Can be reproduced when planning to publish e-mail in 2.10.1
Steps to reproduce:
1. Create an e-mail
2. Fill in "Publish at" using included date picker
3. Try to save such e-mail
![date-picker](https://user-images.githubusercontent.com/13867730/31091660-07d142c0-a7ac-11e7-866c-5810f0510b36.png)
