### ISSUE TITLE
import fails

### ISSUE THREAD

**Issue by jonathanasbell** [mautic/mautic#4909]
What type of report is this:

| Bug report? | 

## Description:
I have imported 3 times and gave up because it never completed
## If a bug:

| Q   | A
| --- | ---
| Mautic version | cloud @ https://fsire.mautic.net/s/contacts

### Steps to reproduce:
1. import my file
 
### Log errors: 
cloud has no log
![mautic1](https://user-images.githubusercontent.com/31919933/30369796-ac812e52-9843-11e7-909f-f647a4e5bb52.png)
![mautic2](https://user-images.githubusercontent.com/31919933/30369804-b146620e-9843-11e7-96b8-399130c805ff.png)
![mautic3](https://user-images.githubusercontent.com/31919933/30369810-b4effbe0-9843-11e7-96c9-2405367329c4.png)
![mautic4](https://user-images.githubusercontent.com/31919933/30369819-b84f9afc-9843-11e7-96a8-093a8e014ca5.png)

**Comment by Bizcrony** [comment]
are you using CSV file to import the contacts?
