### ISSUE TITLE
[Bug] v 2.10 - Gated Video - Contact Creation - PHP Fatal Error - InputHelper Not Found 

### ISSUE THREAD

**Issue by luxuryrealtygroup** [mautic/mautic#4914]
What type of report is this:

| Q  | A
| -Q-| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
When a new contact is created as a result of a gated video, am getting this error using Mautic 2.10. When I click on a newly created Contact to see their details. I can edit the contact via the drop down but not click on the contact name itself in the Contact area without generating an error. The error message I'm getting is "PHP Fatal error: Class 'InputHelper' not found in /home/mydirectory /public_html/crm/app/bundles/PageBundle/Views/SubscribedEvents/Timeline/videohit.html.php on line 55".

We discovered if we save the newly created contact the error doesn't occur. However, a newly created contact record does result in the error when you click on it under Contacts.

My php version is 5.6.31. Clearing cache doesn't fix it either. Our site is SSL.
Do cron settings or certain server settings also cause this error to occur or is it simply a gated video contact creation bug?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 5.6.31

### Steps to reproduce:
1. See description
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Resolved in 2.12
