### ISSUE TITLE
 how can i customize the mautic without losing the updates ?

### ISSUE THREAD

**Issue by heanfig** [mautic/mautic#4916]
What type of report is this: Question

| Q  | A
| Y  | ---
| Bug report? | N
| Feature request? | N
| Enhancement? | N

## Description:
Hi everyone, it happens that we need to install 3 mautic but they ask for a punctual personalization in each one, like changing the logo and changing the presentation of some parts of the software, as I can modify each of these mautic without losing the constant updates that make, to work directly with the repository and do pull every time there is an update.

thank you very good software

**Comment by wittwerch** [comment]
I would recommend that you fork the project on Github. This gives you the opportunity to do the customisation and track them in Git and later still merge in new releases. Once parts of your customisation are subject to change by an upgrade, the merge will fail and you can manually resolve these conflicts.
