### ISSUE TITLE
Images in forms

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4922]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
As a user I want the ability to upload an image as a form field so that I can collect and store documents from a contact easily
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Related to https://github.com/mautic/mautic/pull/3054 ?
