### ISSUE TITLE
Ability to update emails queued due to frequency rule

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4923]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
As a user I want the ability to cancel an email if the email is queued up due to the frequency rule so that I can cancel the email if it is no longer relevant
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
In 2.11
