### ISSUE TITLE
[bug] A/B Test Stats doesn't show any graph

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#493]
I'm not sure if this is due to the long titles of the pages or due to the data not showing, but there seems to be a problem with the A/B Test Stats: http://nimb.ws/goHbOn

No graph seems to be showing.

**Comment by escopecz** [comment]
Yes, this is caused by long titles. I'll take care of it.

**Comment by alanhartless** [comment]
Fixed with 1.1.3.
