### ISSUE TITLE
Mautic "Apply" button unable to save email

### ISSUE THREAD

**Issue by linuskom** [mautic/mautic#4938]
What type of report is this: Bug with Mautic Apply Button when trying to saving email 

| ---| ---
| Bug report? | 
 

## Description:
Version 2.10.0 Apply button does not save email in "Builder". The "Apply Button keeps spinning endlessly spinning."

## If a bug:

| Q   | A
| --- | ---
| Mautic 2.10.0 | 
| PHP version  7.0.23 | 

### Steps to reproduce:
1. Saving email in Channel > Campaign 
2. Click apply
 
### Log errors: 

[2017-09-18 01:14:58] mautic.ERROR: An error occurred while attempting to fetch updates: Couldn't resolve host 'updates.mautic.org' [] []

**Comment by virlatinus** [comment]
This issue was fixed on https://github.com/mautic/mautic/pull/4764

**Comment by linuskom** [comment]
Thanks for your reply.  The actual issue I tracked down to be on the 32 bit firefox browser on my 64 bit machine. This seems to have generated Java issue, I uninstalled the browsers and updated to a 64 bit version.

Now I can save email in Mautic

Thanks again for your reply.
