### ISSUE TITLE
[feature] Allow setting number of rows displayed in a report

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#494]
It would be helpful to be able to set the number of rows being displayed - for example if I'm listing referral sources I may want to have all referrers listed, but if I'm looking at something else I might only want the default 10.  Could not see anywhere that I could set this.

**Comment by alanhartless** [comment]
Is this request for when viewing a report or exporting a report? If viewing, there's pagination at the bottom of the table.  But I don't think pagination affects the report export so just wanted to confirm.

**Comment by RCheesley** [comment]
I think it was viewing a report and exporting - to control what is actually
shown on the page (before pagination) and on the report to control how many
rows are shown.
On 6 Jun 2015 3:38 am, "Alan Hartless" <notifications@github.com> wrote:

> Is this request for when viewing a report or exporting a report? If
> viewing, there's pagination at the bottom of the table. But I don't think
> pagination affects the report export so just wanted to confirm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/494#issuecomment-109506233>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by npracht** [comment]
@escopecz with export segment feature you have all contact fields, i think this is obsolete.

**Comment by escopecz** [comment]
I think that Ruth wants to choose the columns in the table in the UI, not in the export.
