### ISSUE TITLE
re-order Form's action 

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4940]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Create a form
add 3 actions (example)
1) send email
2) push to integration
3) Add 75 points
Save

Edit the form actions list
change the order
1) send email
2) Add 75 points
3) push to integration

Save

Reedit, your new order was not saved and the initial one is still displayed

You have to delete / re-create the actions if you want to change the order

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.12

**Comment by dbhurley** [comment]
Great catch. Definitely a bug.

**Comment by YannickBiet** [comment]
@dbhurley  you're welcome, i have quite tested a lot in the software and reported ann bugs encountered the past 6 months. Hope to be able to work with you and your team to fix them

**Comment by dbhurley** [comment]
I've noticed! And yes!!! I'd love to see you working with Mautic more. Keep up the awesomeness. 😎

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
