### ISSUE TITLE
Form's action change point not taken into account when pushing to integration

### ISSUE THREAD

**Issue by YannickBiet** [mautic/mautic#4941]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Create a simple form
In actions
1/ add 100 points
2/ push to integration (i have setup the integration to push leads into SugarCRM 7.x)

In the integration i mapped of course contacts points in mautic with a custom field in Sugar (tpe integer)

Submit the form
the lead sent to sugar is OK but points are equal to 0

I submitted a second time the form : 
My mautic contact has 200 points
Sugar one has only 100 points

Seems the contact points is modified (whatever the position of the modify point action in the form action tab) AFTER having sent the contact to mautic

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0.12

**Comment by npracht** [comment]
This has been fixed in the past
