### ISSUE TITLE
Time units do not show when cloning a points action

### ISSUE THREAD

**Issue by Sabroson** [mautic/mautic#4945]
What type of report is this: Bug report

## Description:
When cloning a points action, if you don't reset the the "When a contact..." field, then you don't see the time units for fields "Returns Within", "Returns After", "Total time spent"

## If a bug:
Mautic version: v2.10
PHP version: 5.6

### Steps to reproduce:
1. Create new points action:
- When a contact = LandingPageActions - Visits Specific URL
2. Clone the previous Points Action
- No time units for fields "Returns Within", "Returns After", "Total time spent"
3. If you reselect When a contact = LandingPageActions - Visits Specific URL within the cloned Action then you see  the time units for fields "Returns Within", "Returns After", "Total time spent"

### Problem: 

The whole point of cloning is not having to reset fields that do not need to change, but as it works now if you don't reset "When a contact" then you don't get the time units for fields "Returns Within", "Returns After", "Total time spent"

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
