### ISSUE TITLE
Focus not working after 2.10.1

### ISSUE THREAD

**Issue by rc125** [mautic/mautic#4947]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
After 2.10.1, focus still not working. Now I get the message below in my console.
It was working after I applied the PR https://github.com/mautic/mautic/pull/4734 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 7.0

### Steps to reproduce:
1. Create a focus and save it whith Html and CSS content.
2. 
 
### Log errors: 

`[2017-09-18 16:33:48] mautic.NOTICE: PHP Notice - Undefined variable: form - in file /var/www/mautic/plugins/MauticFocusBundle/Views/Builder/Notification/index.html.php - at line 17 [] []
[2017-09-18 16:33:48] mautic.NOTICE: PHP Notice - Undefined variable: htmlMode - in file /var/www/mautic/plugins/MauticFocusBundle/Views/Builder/Modal/index.html.php - at line 29 [] []`

**Comment by rc125** [comment]
If I put this code on HTML editor 

`<style>
.center-modal {
    background-image: url('https://www.mautic.org/wp-content/uploads/2014/08/iTunesArtwork.png');
}
</style>`

When it render on the page, all the code changes to:

`.mf-modal {
    background-image: url(https://MAUTIC-URL/r/1a50315d8b33aa27c38535f5b?ct=YTozOntzOjg6ImZvY3VzX2lkIjtpOjM7czo0OiJsZWFkIjtpOjE5MTcyNjtzOjc6ImNoYW5uZWwiO2E6MTp7czoxMDoiZm9jdXNJdGVtcyI7aTozO319& };
}`

And break all things

**Comment by luizeof** [comment]
Same here

**Comment by HermanMonteiro** [comment]
This error also happens here, I already cleared the cache and updated the schema. I checked the log and have no error messages.

**Comment by jrmarins** [comment]
I'm having the same problem, I updated the schema and nothing, I deleted the form, the focus, the field, the cache and then updated the shema and nothing worked either. The form appears only in Focus when I select the Bar style.

**Comment by robwent** [comment]
I'm seeing issues as well.

The positioning has changed and the form is no longer shown but I get no error messages in console.

I'm using a notification in the bottom left, but it is showing top left. .mf-notification seems to be missing a bottom: 0 value.

![should-be-a-form-here](https://user-images.githubusercontent.com/411678/30614840-c3fac944-9d84-11e7-9ff2-97b0038c8fa2.PNG)

**Comment by rc125** [comment]
The forms are missing in all my focus.

The position problem was reversed by this PR https://github.com/mautic/mautic/pull/4950

**Comment by robwent** [comment]
I've replaced the /plugins/MauticFocusBundle folder from the last version and it has fixed my issues.
Just stepping through it now to see if I can pinpoint the issue

**Comment by robwent** [comment]
@rc125 do you forms now show on the website with the embedded item as well as in the builder?

**Comment by rc125** [comment]
Form does not appear in builder or page. It only shows me a blank space instead the form.

**Comment by robwent** [comment]
@rc125 I thought you fixed it by reversing #4950 ?

When I looked at it, that seemed to only affect the builder, so I replaced the whole focus plugin folder with the 2.10 version and cleared mautic cache and it started working again (after a few hiccups as you see above)

**Comment by rc125** [comment]
Only the position problem was reversed by this PR #4950. The missing forms still there.

**Comment by robwent** [comment]
@rc125 try replacing the whole plugins/MauticFocusBundle folder and the forms should come back

**Comment by jimspillane** [comment]
@rc125 changing the quote from single to double produces a valid URL.  Hope this helps to track it down.

`<style> 
.mf-modal { 
	background-image: url("https://www.mautic.org/wp-content/uploads/2014/08/iTunesArtwork.png"); 
} 
</style>`

**Comment by alanhartless** [comment]
Please test #4950

**Comment by FelixCoutinho** [comment]
I did all changes and the focus persist without the forms...
![screenshot-mkt esmenialima com br-2017-09-25-16-01-35-112](https://user-images.githubusercontent.com/840285/30826037-5eaf3efe-a20b-11e7-83e9-3ca264ae09c0.png)

**Comment by npracht** [comment]
same issue as @FelixCoutinho on my side on HTML focus item, the selected form in the dropdown is not shown in the focus item.

**Comment by npracht** [comment]
Hello @escopecz it can be closed :)
