### ISSUE TITLE
BCC - Emails are blank instead of pulling proper data fields - using Sparkpost API

### ISSUE THREAD

**Issue by versadial** [mautic/mautic#4948]
What type of report is this: A possible Bug

| Q  | A
Bug

## Description:
Using Sparkpost API (could be all API or SMTP), but under my conditions, using the current new API for sparkpost. When sending a BCC email (previously would not work with sparkpost api, but version 2.10 fixed this.) However, the BCC email is stripping the data field. So if the email says. 
Hi {contactfield=firstname}, 

The regular email fills it in as: "Hi Bob,"
However, the BCC email fills it in as: "Hi ,"
So completely blank for some reason. 

## If a bug:

| Q   | A
| --- | ---
Mautic 2.10 (allows BCC of Sparkpost API for email)

### Steps to reproduce:
1. Have Sparkpost API setup as sending your email.  (same bug may appear for other API or email configurations)
2. Have email with general datafields. ie {contactfield=firstname} 
3. Set email to send regular one to end user....then configure a BCC within the email to get a copy. 
4. Launch campaign or trigger email.
5. Email sent to end user (regular one) has the {contactfield=firstname} properly filled out from the database. However, the BCC version is blank. Thus, no data from the contact database are filled in at all for the BCC email. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
