### ISSUE TITLE
Visibility into manually added contacts vs those added via a filter in a segment

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4949]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:
 As a user I want to be able to know for a segment which contacts were added manually vs through a filter, so that I can understand why a contact is part of a segment
## If a bug:

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A

### Steps to reproduce:
1. N/A
2. N/A
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dongilbert** [comment]
Addressed in the Segment Reports PR #4789
