### ISSUE TITLE
Sync 'Contacts' from Sugar/SuiteCRM no longer working

### ISSUE THREAD

**Issue by HiveMindNet** [mautic/mautic#4956]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Since upgrading from 2.9 the sync of 'Contacts' from Suite/SugarCRM to Mautic no longer works. No errors are thrown in PHP/Apache/Mysql logs that relate to this. 'Leads' however do sync (although I don't use them).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 7.0.19-1+deb.sury.org~trusty+1

### Steps to reproduce:
1. Set up mautic / CRM contact sync, (enter auth keys from and login credentials crm to Mautic, map fields, set up settings) 
2. Change some Contact record in CRM
3. Run ./console mautic:integration:synccontacts --integration=Sugarcrm --env=prod
4. See as below (nothing pulls)

Command to fetch contacts from integration
Fetch contacts command is starting
Fetching contacts...
0 contacts were updated and 0 contacts were created
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by fwtag** [comment]
Same here.

**Comment by adonisd** [comment]
Ditto as well. I also chose to pull data from contacts but in contact mapping it is showing me "Leads" as well. Is that normal?

**Comment by isleshocky77** [comment]
I'm having the same issue. The error message popping out is 

```
user@server:~$ /usr/bin/php /srv/current/app/console mautic:integration:synccontacts --integration="SugarCrm" --time-interval="-2 hours"
PHP Fatal error:  Call to a member function isAuthorized() on boolean in /srv/releases/20171006163009/app/bundles/PluginBundle/Command/FetchLeadsCommand.php on line 103

                                                              
  [Symfony\Component\Debug\Exception\FatalErrorException]     
  Error: Call to a member function isAuthorized() on boolean  
```

This is only for the synccontacts cli command. The push functionality of Mautic to Suite works for me.

Mautic: v2.10.1
SuiteCrm: Version 7.9.4 [Sugar Version 6.5.24 (Build 509)]

**Comment by stevedrobinson** [comment]
Same here.

**Comment by giampyart** [comment]
+1

**Comment by isleshocky77** [comment]
Alright, the first issue on my side was the integration name. That error should be caught and handled better, but if you change the integration to "Sugarcrm" it works.

```
user@server:~$ /usr/bin/php /srv/current/app/console mautic:integration:synccontacts --integration="Sugarcrm" --time-interval="-2 hours"
```

**Comment by isleshocky77** [comment]
I guess I spoke too soon. Although it no longer throws errors; it's also not actually grabbing any data. From the verbose output, it looks like it's grabbing data from the "Users" module instead of the "Leads" and "Contacts" module.

**Comment by stevedrobinson** [comment]
The issue on my side was that I hadn't actually checked the boxes in the plugin configuration to fetch leads, contacts and accounts. when I checked those boxes, the integration started working again. Doh!

**Comment by stevedrobinson** [comment]
I did also have to additionally patch the code per pull request #5244, but once I did that, data seemed to come through provided I didn't go too far back in time.

**Comment by isleshocky77** [comment]
@stevedrobinson Yes, it looks like @mqueme 's #5244 or sugar-bugs branch is working correctly with SuiteCrm.  One thing I may recommend is that the help on the `mautic:integration:synccontacts` command give `--time-interval="-2 hours"` as an example; however, in practice I found that this option actually looks forward into the future and does so in a way which is impossible making the criteria being less than today and greater than 2 hours from now.

Running `mautic:integration:synccontacts --time-interval="2 hours"` did work as expected. I'm guessing the help docs should be corrected.

**Comment by MyBpoConsultant** [comment]
I have integrated the Sync. However, there is one MAJOR problem that people are not talking about. It will sync only ONCE. A typical scenario --> Mautic gives 5 points and then pushes lead to Sugar --> Telemarketer calls this lead and then marks call status as Not available..... Not available then syncs from Sugar to Mautic. Ok all systems checked ---- except here is where the big flaw is --> next time the telemarketer calls that lead and updates Call Status to "Declined" --> this will not push from Sugar CRM to Mautic because it already pulled it last time as "Not Available" ---> it is very important to overwrite data in the sync as data is constantly changing. In this scenario we are wanting to sync the Call Statuses in our CRM to Mautic and then assign Segments based on that to various campaigns...

**Comment by pstevens71** [comment]
I know this is an old thread but the Sugar/SuiteCRM works perfectly and it sync's more than once.   What it will not do is sync both ways.  You must choose either SuiteCRM or Mautic as the primary on a field by field basis.  The primary ALWAYS over writes.  Except, there is an option if one side is Null, it will over write with the side that has a value.  Hope that helps anyone reading this thread.
