### ISSUE TITLE
SugarCRM Plugin: No contacts from SugarCRM to Mautic 

### ISSUE THREAD

**Issue by PeterTL** [mautic/mautic#4957]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I am trying to connect Mautic with SuiteCRM. To do this, I have setup the SugarCRM plugin and I am experiencing some problems: contacts created in SugarCRM are not transferred to Mautic (the other direction works). Here is what I did:

- Connected Mautic to SugarCRM via oAuth
- Features: pull + push
- SugarCRM objects: leads + contacts
- Contact mapping: Lead email, last name and first name (Mautic wins) + Contact email, last name and first name (SugarCRM wins)
- Activated CRON for mautic:integration:fetchleads + mautic:integration:pushleadactivity (both with --integration=Sugarcrm)
- Activated the plugin

Behavior:

- Create a lead in Mautic: Gets transferred to SugarCRM automatically
- Create a lead in SugarCRM: Gets transferred to Mautic automatically
- Create a contact in SugarCRM: Nothing happens

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 7.0.22
| SuiteCRM version | 7.9.4

### Steps to reproduce:
=> see above
 
### Log errors: 
No log entries in Linux, SuiteCRM and Mautic logs

**Comment by fwtag** [comment]
Same here.

**Comment by stevedrobinson** [comment]
I believe this is fixed in pull request #5244.
