### ISSUE TITLE
form builder working with bootstrap 

### ISSUE THREAD

**Issue by astrocycles** [mautic/mautic#4958]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | x

## Description:
The more details the better...
Form builder :
1-It would be awesome to have designing options and prebuilt template for forms. BT4 offers a lot of prebuilt forms 
2-to be able to add simple Bootstrap 4 component easily (maybe with a custom html field ) such as form group which is too complicated by the form attributs.
```<form>
  <div class="form-group row">
    <label for="staticEmail" class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="email@example.com">
    </div>
  </div>
  <div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword" placeholder="Password">
    </div>
  </div>
</form>
```

3- Modal options with different effects 
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Good suggestions for UI improvements in future releases.
