### ISSUE TITLE
[bug] Analytics code not present on post-completion message page

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#496]
On the message page displayed after form completion (which is a requirement if you have an immediate download, as you can't redirect to another page) there is no analytics tracking being triggered.

This means that it's impossible to track goal completions being a form submission - and also impossible to use Tag Manager to fire off a conversion pixel when the form is submitted.

I think maybe it's just that the analytics code isn't being included?

**Comment by alanhartless** [comment]
Fixed with #516
