### ISSUE TITLE
Can not authorize Joomla plugin

### ISSUE THREAD

**Issue by matishaladiwala** [mautic/mautic#4961]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Getting "Error
The response returned is in an unexpected format."

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Have set up API credentials using OAuth1 according to the directions here: https://github.com/mautic/mautic-joomla#mautic-joomla-plugin
2. Have set up the Joomla plugin
3. Getting "Error
The response returned is in an unexpected format."

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
This was fixed in https://github.com/mautic/mautic-joomla already I believe.
