### ISSUE TITLE
BUG: "Sent count" and "read count" does not update in reports after adjusting date range

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4965]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
I believe this is the way Sent Count and read count were originally created, but customers are noticing that when they adjust a timeframe in the date filter, the send count and read count does not increase or decrease. The report always shows the total amount of sends/reads from start date to present

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Build report from April 23, 2017 to May 23, 2017 
2. Build a report from May 21, 2017 to May 23, 2017 and see that the sent count and read count have not updated.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by justinfortes** [comment]
Moved to mautic-internal/mautic-internal#7
