### ISSUE TITLE
990When adding 2 companies at the same time, it is adding both as primary

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4966]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Bug #990 (When adding 2 companies at the same time, it is adding both as primary). 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mleffler** [comment]
@cceruti Not sure what this means, and the link goes to something else - closing, feel free to re-open with more details, thx.
