### ISSUE TITLE
Custom field values not populating in form builder for "select" fields

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4968]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Add a custom field
2. check if customer field created has populated in form builder under "select" fields.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Rixita** [comment]
Duplicate #4890 - I guess.

**Comment by mleffler** [comment]
This was fixed.
