### ISSUE TITLE
if contact is unsubscribed from email bounce back, they're not added into segment with filter of "unsubscribed email = yes"

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4969]
What type of report is this: bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
If you have a segment with a filter of "unsubscribed email = yes" and you have contacts that have been unsubscribed from emails via bounces then they're not automatically added into the segment

There isn't a way to put on advanced filters either that would group these two filters today, i.e. (unsubscribed email = yes OR bounced email = yes) AND segment membership = A so I can't come up with any other solid workarounds here

Using a segment filter of `(Unsubscribed email = yes AND segment membership = A) OR (Bounced email = yes AND segment membership = A)` is NOT a valid workaround.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
