### ISSUE TITLE
[feature] Push conversion data to AdWords

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#497]
It would be super cool if you could push lead/conversion data into AdWords and hook it up with the GCLID from the referral URL?

Could also be used to track folk who convert by phone, for example?

Guess it would involve storing the GCLID somewhere but it's part of the referring URL so should be possible?

**Comment by julienmarie** [comment]
It would be awesome. Being able to add a conversion event in a campaign, linked to one of the conversions tags of adwords would be pretty great.

**Comment by maxitromer** [comment]
Related to #1933
