### ISSUE TITLE
Adding Dynamic Content via TAB on email main page is broken

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4971]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
If you're building an email in Code Mode, you can create the various dynamic content elements on the email builder main page.  You can build one, but when you try and build more than one, the Variation button/link is missing.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
![dctab](https://user-images.githubusercontent.com/32133519/30659349-80488f7e-9e0b-11e7-8711-9061e713bfdf.jpg)

 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by virlatinus** [comment]
Fixed in #5140
