### ISSUE TITLE
Bug - Multi, first and last touch attribution reports not working

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4975]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
The reports don't generate any information.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mleffler** [comment]
Please re-open if this is still an issue.
