### ISSUE TITLE
Form results email coming in as Spanish

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4978]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Every other form result email is coming in as Spanish. The contact is testing which is why there are multiple results, but the users have not changed their language settings away from English.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mleffler** [comment]
@cceruti Assuming we can close this.
