### ISSUE TITLE
Upload Packaged Landing Page Themes

### ISSUE THREAD

**Issue by drmmr763** [mautic/mautic#498]
It would be a nice feature to be able to upload packaged landing page themes.

https://www.mautic.org/community/index.php/402-option-to-upload-landing-page-code/0#p1658

**Comment by RCheesley** [comment]
+1 from me, at the moment it's not easy for vendors to make their templates available or for users to easily upload/install without FTP knowledge

**Comment by dbhurley** [comment]
Definitely, this will be included as part of the Mautic Marketplace :+1:

**Comment by rodrideme** [comment]
+1

**Comment by spaceonline** [comment]
+1

**Comment by nickwild-999** [comment]
+1
