### ISSUE TITLE
Downloading asset gives 500 error unless logged into Mautic

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4980]
What type of report is this:Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When downloading assets, Mautic stopped without notice.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by cklingsporn** [comment]
Tested this with local and remote assets. 
Published assets downloaded successfully, unpublished assets failed when not logged in (403) as expected.

Can you provide any more information, maybe the server error logs? Were the assets published that you were trying to download when not logged in?
