### ISSUE TITLE
"Reports" data incorrect

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4982]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Reports are not showing correct data
One asset shows 23 downloads on the asset, but when I look at the report for assets, it only shows 18 downloads. Anyone know what the issue could be here?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mqueme** [comment]
This seems to have been fixed by https://github.com/mautic/mautic/pull/4239
