### ISSUE TITLE
mPower Social is not syncing Twitter mapped fields

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4983]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
It seems that only the Twitter handle and name is getting mapped to the lead when the monitoring tool auto-creates a lead. It may be that the lead fields mapped in the Twitter  plugin configuration are not accounted for. Any ideas?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
