### ISSUE TITLE
Uploading image to Media Manager changes image size unexpected

### ISSUE THREAD

**Issue by lostmist** [mautic/mautic#4984]
## What type of report is this

Bug report

## Description
I want to upload a jpg image which size is 600 × 1519, but when uploaded, the image size turns out to be 404x1024 in Media Manager.

I've searched in Google and found some methods, but they were all not worked for me.

## If a bug

Mautic version: 2.10.0
PHP version: 5.6.31

### Steps to reproduce
1. create an email in code mode, open Media Manager, drag an image to upload
2. find the uploaded image, and check its size

**Comment by dbhurley** [comment]
Duplicate post.

**Comment by SterlingAr** [comment]
Duplicate of what? I'm having this issue now, i'd like to know which post should I read.

**Comment by bitplaio** [comment]
found any info on this @SterlingAr?
