### ISSUE TITLE
View in email Browser link broken in Dynamic Content Variants

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4989]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
The View in a Web Browser token is pasted into each variant.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Create one email and have the entire email made up of one dynamic content with 4 variants.
2. View the email URL.

This is the message we are seeing 
![screen shot 2017-09-21 at 2 10 01 pm](https://user-images.githubusercontent.com/32133519/30711553-1a9d2938-9ed7-11e7-95fd-921a9974ea3b.png)

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
