### ISSUE TITLE
Boolean not showing when creating label and value of "0" (zero) in Forms

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#4990]
What type of report is this: bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When creating a boolean for the numbers 0 and 1, ONLY the boolean for 1 is shown. Creating a boolean that is labeled 0 (zero) and has a value of 0 (zero), it is not showing up when we hit update. Only number 1 is showing up. This is a P2 so it is only being added in GitHub.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Create a new form (standalone or campaign form) - name it Boolean (or whatever else you would like)
2. Under "Fields", select dropdown to "Add a new field".
3. Select "Checkbox Group" and under "Properties" select "Add a value" twice to have two sets of boxes to create Boolean.
4. In first set of boxes type "0" (zero) for label and value, in second set of boxes type "1" for label and value. 
5. Click add and see that only the number "1" boolean shows up. 
<img width="881" alt="screen shot 2017-09-21 at 1 40 08 pm" src="https://user-images.githubusercontent.com/32133519/30712362-ca558eae-9ed9-11e7-85a9-921022aa3016.png">

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dsp76** [comment]
Also when this is a required field, a selected 0 option would lead the form to think this field has not been filled.

**Comment by dsp76** [comment]
Maybe fixed with this? https://github.com/mautic/mautic/pull/5189

**Comment by dsp76** [comment]
Thats still unfixed in 2.15.3

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
