### ISSUE TITLE
Import Contact CSV not working after 2.10.0 update

### ISSUE THREAD

**Issue by namankumar** [mautic/mautic#4991]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y |
| Feature request? | |
| Enhancement? | |

## Description:
Please help. This is urgent.

Importing a contact is not working. The page first throws a "cannot read this CSV" error. Trying again, it throws 500; i.e. the Mautic mascot with the message "Uh Oh! I think I broke it..." message comes up.

I've tried it with two different files on two different days, same results.

I'm sure my CSVs are valid.

Was working fine in 2.9.2. The problems started after updating to 2.10.0. Upgrading to 2.10.1 hasn't helped either.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.0
| PHP version | 2

### Steps to reproduce:
1. Import a file
 
### Log errors: 

[2017-09-21 14:32:13] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\LogicException: "A form with an empty name cannot have a parent form." at /var/app/current/vendor/symfony/form/Fo\
rm.php line 273 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\LogicException(code: 0): A form with an empty name cannot have a parent form. at /var/app/current/vendor/symfony/form/Form.php:273)\
"} []

**Comment by namankumar** [comment]
This is working after re-installing the codebase. Tried for for two instances. 

Closing now.

**Comment by goldpromotion** [comment]
Having the same problem :(

**Comment by MrKennie** [comment]
I'm have the same problem after updating to 2.12.2. Checking the Chrome console, I noticed that /s/contacts/import/new?importbatch=1&_=1519736682886&mauticUserLastActive=1&mauticLastNotificationId=  was returning Server Error 500. After checking the logs I get the following:

`[2018-02-27 13:20:24] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMException: "The EntityManager is closed." at /var/www/em/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php line 144 {"exception":"[object] (Doctrine\\ORM\\ORMException(code: 0): The EntityManager is closed. at /var/www/em/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php:144)"} []`

This is a small list of 70 contacts. Is there a way to get more output for debugging? I can probably get more information to you.

**Comment by oriolherrera** [comment]
Someone have resolved this issue?

**Comment by cofundhub** [comment]
I have the same problem here. There is no log reporting error related to this..
