### ISSUE TITLE
Please move configuration to the database

### ISSUE THREAD

**Issue by emspoars** [mautic/mautic#4993]
What type of report is this: Feature request

## Description:
Please move all configuration currently located in local.php, except the ones that differ between deployment stages (such as database configuration), to the database. This will make deploying Mautic with containers MUCH more viable than it is now.

There's already an excellent argument for this inside another request in docker-mautic (https://github.com/mautic/docker-mautic/issues/2), but it'll be clearer if I make a separate request for it here, since the original one is about the docker image and not Mautic itself.
Here's the relevant part of the original request:

"local.php
The configuration file is updated every time you change settings in the web UI. That means that you write state into your container, unless you somehow mount it using a volume.
I think that the local.php should only contain configurations that differ between stages (see http://12factor.net/config) and are necessary to run/start the application (like database settings). These settings should be read from environment variables. All other configuration should be stored in the database, so it's still changeable through the web UI but persists image redeploys."

Thank you.

**Comment by paulocastellano** [comment]
+1

**Comment by namankumar** [comment]
Even for non-container purposes, it would be very useful to move local.php to the DB.

Mautic would be able to connect to the database and check whether it's a new install or an upgrade to an existing installation.

**Comment by pbrandao12** [comment]
+1

**Comment by gcoli6** [comment]
+1

**Comment by PeterTL** [comment]
-1

- Configuration files are easier accessible and readable
- Configuration files can (and should) be under revision control
- Different sets of configuration parameters (for different systems like DEV, QS, PROD) are easier handled with configuration files
- Any conventional staging (don't know much about containers) is easier with configuration files

**Comment by rc125** [comment]
+1

**Comment by dbhurley** [comment]
This will be a debate with pro's and con's for both sides. Not something to be changed at the present time.

**Comment by mogul** [comment]
The dependence on local filesystem for app config (rather than just environment-specific info like DB and filesystem location) makes Mautic unsuitable to being run in platforms where the local filesystem is ephemeral, eg Heroku and any of the many Cloud Foundry deployments in existence. Please reconsider making it easier to run Mautic in a stateless manner!

**Comment by dbhurley** [comment]
Thanks for the update and request. I believe there is planning for this for Mautic 3.

**Comment by mogul** [comment]
> I believe there is planning for this for Mautic 3.

Glad to hear it! Where can I find information about Mautic 3's scope/progress? This [roadmap page](https://www.mautic.org/about/roadmap/) leaves a little to be desired. :)

I need this change sooner rather than later... If I submit a PR against the current codebase, leaving existing behavior intact unless the new behavior is explicitly configured (eg via environment variable), do you think it would be merged?

**Comment by boriscougar** [comment]
+1

**Comment by alessandroniciforo** [comment]
This is still an actual and needed feature on v2 since v3 is nowhere to be seen.
@mogul did you by any chance worked on a PR? Or maybe solved otherwise?

**Comment by mogul** [comment]
Sorry, no, we never had time to work on it.

**Comment by xeroc** [comment]
Can we have this now? Or at least allow *everything* to be configured from environment variables. If i spin up mautic without local config.php file, it will ask me for database access credentials even though they are provided as environment vars.
