### ISSUE TITLE
HTML Mode Focus else than Modal not working

### ISSUE THREAD

**Issue by wucherpfennig** [mautic/mautic#4996]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  y
| Feature request? | 
| Enhancement? | 

## Description:
You can choose "HTML Mode" in Editor but nothing changes

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 7

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

No logs (console + php)

**Comment by dbhurley** [comment]
Cannot replicate.
