### ISSUE TITLE
Feature - Decisions based on time spent on page

### ISSUE THREAD

**Issue by alvinbenavides** [mautic/mautic#50]
There are Point Actions and Campaign Decisions based on visits to landing page. If a lead visits a landing page but immediately close it, the event would be logged as accomplished but the content was never actually consumed.

The pop-up where the landing page is selected could have a minimum spent time to avoid this.

**Comment by MaxOnTheHill** [comment]
+1 for this ... time on page measurement for trigger/workflow/actions (like pop-up) would be a good thing to have :)

**Comment by mikeamcbrien** [comment]
I agree!
