### ISSUE TITLE
Contacts filter not works

### ISSUE THREAD

**Issue by IgorGromada** [mautic/mautic#5003]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Contact filter on mautic.../s/contacts not works. Page refreshes before I finish enter search query.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.10.1
| PHP version | 7.0.22-0ubuntu0.16.04.1

### Steps to reproduce:
1. Go to mautic.../s/contacts
2. Try to use filter field. Filter not works. Page refreshes before I finish enter search query.
3. Filter field duplicated after page refreshes
<img width="681" alt="cont-filt" src="https://user-images.githubusercontent.com/32206434/30761380-b6294548-9fe6-11e7-8935-919a68ad0617.png">
.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by IgorGromada** [comment]
No web server's or Mautic logs found.

**Comment by dbhurley** [comment]
Can't replicate.
