### ISSUE TITLE
Campaign condition ignored

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#5005]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When a condition is set in campaign it is being ignored 
The way I had it set = to wait 14 days before checking the condition that was added which would trigger an email, but instead it executed immediately.

I tried to replicate the issue in my instance, but could not get the same result - the email after the 14 day condition in my instance has not yet fired.

Is this enough information to go on and will their logs tell the story?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by HermanMonteiro** [comment]
Have you activated the campaign and waited 14 days to simulate the error?

**Comment by cceruti** [comment]
Yes

**Comment by HermanMonteiro** [comment]
Hello I ran several tests using version 2.10.0 and in all of them the email was triggered correctly, I activated the condition to start the campaign from a list, and then I waited a few days and included the email sending action ... All ran as expected.

What version are you using? I believe this is not a Mautic bug, but something related only to your environment
