### ISSUE TITLE
Receiving Salesforce Error ConcurrentPerOrgLongTxn Limit exceeded

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#5006]
What type of report is this: bug 

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When trying to import a contact list, I receive the above error.  
After some research, it looks like that error is the same as REQUEST_LIMIT_EXCEEDED: ConcurrentPerOrgApex Limit (https://salesforce.stackexchange.com/questions/149335/first-error-unknown-exception-concurrentperorglongtxn-limit-exceeded)

This error is typically caused when someone hits their SF API request limit, but I am getting 40,000 every 24 hours, and I only imported 1,000 leads.  

I don't have any other major integrations that would consume the rest of the API requests.

Checked again this morning and the Limit Exceed looks like it might be a text length issue, but I am not sure.

Thoughts? 
I cannot import leads from SFDC.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
I'll close this, this is a salesforce limit and limit should be raised by salesforce support.
