### ISSUE TITLE
Can't send form via AJAX request

### ISSUE THREAD

**Issue by williamknn** [mautic/mautic#5007]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I've installed a Bitnami AMI for Mautic. Imported my leads and created two forms, but I can't send info to the forms. Here is how I'm sending my user's information (AngularJS 1.4.9):
```javascript
var saveMauticSignupEmail = $scope.saveMauticSignupEmail = function()
        {
            var p1 = { ok: 1 };
            $http.post('http://mautic.xxxx.com.br/form/submit?formId=2', 
                {
                    data: 'mauticform[email]=' + $scope.info.email + '&mauticform[utm_source]=' + mautic.utm_source + '&mauticform[utm_medium]=' + mautic.utm_medium + '&mauticform[utm_campaign]=' + mautic.utm_campaign + '&mauticform[utm_term]=' + mautic.utm_term + '&mauticform[utm_content]=' + mautic.utm_content + '&mauticform[formId]=2&mauticform[return]=' + p1 + '&mauticform[submit]=' + 1 + '&mauticform[formName]=cadastrosoemaillandingpageprincipal',
                    dataType: 'json',
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'application/x-www-form-urlencoded'
                    }
                }).success(function(response)
                {
                   registerInfo($scope.info);
                }).error(function(response)
                {
                    registerInfo($scope.info);
                });
        };
```

## Response of the request:
`mauticError:This form is no longer available.`
Note: All my forms are PUBLISHED.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 7.0.23

### Steps to reproduce:
1. Fill email field and click Register. The click event will trigger the function above.
 
### Log errors: 
Apache access.log file:
`200.148.3.15 - - [23/Sep/2017:21:05:43 +0000] "OPTIONS /form/submit?formId=2 HTTP/1.1" 204 -`
`200.148.3.15 - - [23/Sep/2017:21:05:43 +0000] "POST /form/submit?formId=2 HTTP/1.1" 302 608`

Mautic Log:
`[2017-09-23 17:28:42] mautic.WARNING: IP LOOKUP: The file "/opt/bitnami/apps/mautic/htdocs/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []`

**Comment by dongilbert** [comment]
Have you set the sending domain as an allowed domain in your CORS settings under the main configuration page?

**Comment by williamknn** [comment]
Yes! And I know this is working because the Apache logs is showing my request:
I was receiving CORS error before but now this is fixed.

Apache access.log file:
`200.148.3.15 - - [23/Sep/2017:21:05:43 +0000] "OPTIONS /form/submit?formId=2 HTTP/1.1" 204 -`
`200.148.3.15 - - [23/Sep/2017:21:05:43 +0000] "POST /form/submit?formId=2 HTTP/1.1" 302 608`

**Comment by cklingsporn** [comment]
If it helps, this error (This form is no longer available.) comes around in only 3 cases.

- If mauticform[formId] is not set on the submission
- If when looking up the form by id from mauticform[formId] no form was found
- If the selected form status is not in [pending, expired, published]

I'd suggest looking at/showing us the actual values which are being sent to the server, see what that 'data:' string is actually generating when being sent, otherwise double checking the status of the form.

**Comment by williamknn** [comment]
Ok, let's go:

**- If mauticform[formId] is not set on the submission**
This information are being sent, as shown above in post description.

**- If when looking up the form by id from mauticform[formId] no form was found**
I don't know how to test this, but I know that the forms with his correspondent `formId` really exists.

**- If the selected form status is not in [pending, expired, published]**
All my forms are published.
![screenshot from 2017-09-25 09 44 05](https://user-images.githubusercontent.com/3988151/30808858-2064bcf8-a1d6-11e7-9710-a09afc85340c.png)

**Comment by williamknn** [comment]
I'll test the `data` string and edit this comment to show.

**Comment by williamknn** [comment]
Like I said before, this request was working in my old Mautic installation (v1.2). For some reason, this don't work in the last version (v2.10.1) without serializing the data.

If is there someone with the same problem, try using **$httpParamSerializerJQLike** before send data:
```javascript
var data = $httpParamSerializerJQLike({
                    'mauticform[email]': $scope.info.email,
                    'mauticform[utm_source]': mautic.utm_source,
                    'mauticform[utm_medium]': mautic.utm_medium
                    'mauticform[utm_campaign]': mautic.utm_campaign,
                    'mauticform[utm_term]': mautic.utm_term,
                    'mauticform[utm_content]': mautic.utm_content,
                    'mauticform[formId]': '2',
                    'mauticform[return]': p1,
                    'mauticform[submit]' : '1',
                    'mauticform[formName]': 'cadastrosoemaillandingpageprincipal'
                });

                var config = {
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'application/x-www-form-urlencoded'
                    }
                }

                $http.post('http://54.233.XXX.XXX/form/submit?formId=2', data, config)
                    .success(function(response) {
                        registerInfo($scope.info);
                    }).error(function(response) {
                        registerInfo($scope.info);
                    });
            };

        });
```

This worked for me, so I'll close the thread. Hope this helps someone in the future.
