### ISSUE TITLE
Be Able to SMS Text Message to Others In Addition to a Contact - Feature Request

### ISSUE THREAD

**Issue by luxuryrealtygroup** [mautic/mautic#5015]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? |Yes 
| Enhancement? | x

## Description:
FEATURE REQUEST - Currently the Twilio SMS text messaging integration with Mautic is very limited.  We want to be able to SMS Text message 1 to many people at the same time a new contract record is created.  For example, a Mautic form on a WP website that is used for prospects to register would be a trigger when they submit for SMS text messages. We want to trigger SMS text messages to go to our internal sales staff since its a prospect and to the new prospect contact too.  The existing text message function doesn't allow us to specify the target mobile number, save it and therefore when creating campaign steps we can't have various text messages saved by mobile to use in a serious of workflow steps.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Expand the text messaging function to save mobile numbers and save specific text messages per number.  Much like a form, these would be text message "forms" with one to several mobile phone numbers stored in the text message form.
2. Twilio or another SMS Text Messaging Plugin to Mautic would have to handle multiple text message requests per mobile phone number stored in the Mautic text messaging form,  Reporting would be needed to track successful SMS Text messages to recipients.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by luxuryrealtygroup** [comment]
Why was this feature request closed? Has it been included in a future Mautic release ?

**Comment by dbhurley** [comment]
Sure! For reference: this should be suggested in the Ideas forum of the Mautic forums.
