### ISSUE TITLE
Make Tag Editable & Deletable

### ISSUE THREAD

**Issue by katzueno** [mautic/mautic#5016]
What type of report is this:

| Q  | A
| ---| ---
| Feature request? | yes

## Description:

I would like to have a features that

- shows the list of tags
- Ability to rename existing tags
- Ability of delete existing tags

Currently, you can do nothing but to add new tags.

The more I started to maintain several Mautic instances, it started to be a problem.

### Main Problem: Misspelled tags are being left

The most concern is the misspelled tags are also being left in the available list.
There are people who mistakenly added those misspelled tags and those contacts won't be in the results.

### Problem 2: Select options gets longer easily

Although tags are meant to allow many entries, as an admin, they don't want to be too much to be in-control. It would be nice for admin to be able clean up the tags.

Therefore additional delete and rename function could solve the issue.

Currently, I'm editing MySQL table directly to delete or rename those tags.

Thanks.

**Comment by merlin0** [comment]
+1 this would be great and much needed feature.  Think it's a duplicated of https://github.com/mautic/mautic/issues/2308 but your desciption in better!

**Comment by katzueno** [comment]
Opps, sorry... I thought I did thoughtful search on issue... I don't mind this issue to be merged onto #2308 Tag Manager

**Comment by miamicityman** [comment]
Hello Katzueno,
Would you advise which MySQL table you are editing?
Thanks,

**Comment by miamicityman** [comment]
Nevermind ... just found it ... "mktng_lead_tags"
