### ISSUE TITLE
Web Notifications not working in WP environment

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#5019]
What type of report is this: bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Web notifications do not work when enabled through the Mautic Tracking Script.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
No reproducable, no how to
