### ISSUE TITLE
User role - not showing config in settings

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#5020]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
I created a custom role that had all permissions except for user management. The users who have this role are unable to access to the Configuration tab anymore. Some users regularly need to change stuff on here. Is there a reason they would no longer have access if their role had all permissions except user management?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
No mautic version reported.
As we are only providing fixes for Mautic 3.x going forward, i'll close it. If you can confirm this continues in Mautic 3.0.1 i'll reopen the issue.
Thanks!
