### ISSUE TITLE
Switching to code mode - cannot save changes unless code mode is disabled 

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#5021]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
When switching to code mode in the text slot, changes don't save unless you disable the code mode view 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by gregharvey** [comment]
Just to confirm we can reproduce this, it's still an issue in 2.16.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by gregharvey** [comment]
I can confirm this still happens in 3.x - I tried it here and the behaviour is the same:

* https://mautibox.com/staging/s/pages/new

**Comment by npracht** [comment]
Hello @gregharvey i am pretty sure that https://github.com/mautic/mautic/pull/9143 fixes your issue. Can you test it please and share your feedback ?

**Comment by RCheesley** [comment]
Closing due to probable resolution and no recent response.
