### ISSUE TITLE
I'm unable to create email - error 'select' in console

### ISSUE THREAD

**Issue by Yoshuwa** [mautic/mautic#5025]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:

I'm trying to create an email under 
Chanel > Marketing message & Email > New > [modal]

Create new email template After Save and Close modal doesn't close
and buttons grey out.

## If a bug:
Uncaught TypeError: Cannot set property 'selected' of undefined
    at Chosen.result_select (libraries.js?v26390eb6:1619)
    at Chosen.search_results_mouseup (libraries.js?v26390eb6:1615)
    at HTMLUListElement.<anonymous> (libraries.js?v26390eb6:1603)
    at HTMLUListElement.dispatch (libraries.js?v26390eb6:404)
    at HTMLUListElement.elemData.handle (libraries.js?v26390eb6:379)

| Q   | A
| --- | ---
| Mautic version | Latest
| PHP version | 7

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Yoshuwa** [comment]
libraries.js?v26390eb6:673

POST http://www.SITE.com/s/emails/new?mauticUserLastActive=1 403 (Forbidden)

**Comment by Yoshuwa** [comment]
Issue reported here as well https://www.mautic.org/community/index.php/4661-please-wait-and-nothing-happens-unable-to-save-settings

**Comment by alandolsi** [comment]
I have the same Problem here, is there a solution?

**Comment by Gremza** [comment]
Same problem
