### ISSUE TITLE
Push contact to integration from contact page

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#5034]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | x

## Description:
It would be very awesome to be able to manually push contact to integration without going through a campaign/form/trigger action.
So on the contact overview page, have an action in the dropdown menu `push contact to integration`.

**Comment by mqueme** [comment]
duplicate of https://github.com/mautic/mautic/issues/1086. so closing this.
