### ISSUE TITLE
Missing button on the dashboard

### ISSUE THREAD

**Issue by ruda-almeida** [mautic/mautic#5040]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 
| Other | x

## Description:

The [official documentation](https://mautic.org/docs/en/contacts/managing_contacts.html) states:

> (...) by default the list view is enabled, but you can also choose to switch to the card view (also known as grid view) which uses avatars to depict the contacts visually using cards. Clicking the appropriate button on the top right will allow you to switch between the two views.

I can change the view mode by pressing "t" or "c", but there is no button on the top right.

I'm using v2.10.0 on Firefox 55.0.3 with adblock turned off.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.10.0
| PHP version | 7.0.23

### Steps to reproduce:
1. Log in
2. Click on "contacts" on the left sidebar
 
### Log errors: 

N/A

**Comment by ruda-almeida** [comment]
Why was it closed with no coments?

**Comment by dbhurley** [comment]
Sorry for not offering more clarity. In a recent release the toolbars have been improved, the toggle button was one that was removed. The documentation should be updated to reflect this. The keyboard shortcut was intentionally left as an "easter egg" or "pro" feature.
