### ISSUE TITLE
Creating a custom text field named `Tags` causes error

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#5042]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Creating a custom text field named `Tags` causes `Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members.` error. Creating custom field called 'tags' messes with the core 'tags' field.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
May be fixed by #7192

**Comment by npracht** [comment]
Fixed when #7192 merged.
