### ISSUE TITLE
Points null when creating a new contact with a new company

### ISSUE THREAD

**Issue by javjim** [mautic/mautic#5045]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
When creating a new contact and adding a new company after save it gives error for having points null

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Go  to new contact page
2. Add FirstName, LastName and Email
3. On company field, select "new company..."
4. Add companyname, companyemail
5. Save & close company
6. Save & close Contact.
7. Should get error that points cant be null
 
### Log errors: 

 500 Internal Server Error - An exception occurred while executing 'UPDATE leads SET title = ?, firstname = ?, lastname = ?, position = ?, email = ?, mobile = ?, phone = ?, points = ?, fax = ?, address1 = ?, address2 = ?, city = ?, state = ?, zipcode = ?, country = ?, preferred_locale = ?, attribution_date = ?, attribution = ?, website = ?, facebook = ?, foursquare = ?, googleplus = ?, instagram = ?, linkedin = ?, skype = ?, twitter = ? WHERE id = ?' with params [null, "asdfa", "dfada", null, "dfa@mm.com", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 3]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'points' cannot be null

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
