### ISSUE TITLE
Feature request - Custom field: Date format output in emails depending on language

### ISSUE THREAD

**Issue by Rixita** [mautic/mautic#5048]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
When you have a custom field for a date, this is saved in the in the format YYYY-MM-DD

Now if you want to send the customer an email, after form submission with the details it sends the date in the above format.

But for some countries you may want to use a different format. For ex. DD-MM-YYYY or DD.MM.YYYY

Would be great if the date output would be depending on chosen language in the email template.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Not something on the roadmap but definitely a feature request. I've attached the label but closed the issue. If someone would like to submit a PR for this it can certainly be reopened.
