### ISSUE TITLE
Focus: "When to Engage" does not update the preview

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#5056]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
In the Focus Item builder, "When to Engage" does not update the preview after making a change, even after clicking Apply, then Save & Close, then re-opening.  

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by morettic2015** [comment]
Have a ISSUE also... When i put a form inside FOcus item it disappear....

**Comment by morettic2015** [comment]
also Focus items already working stopped after Mautic Update 2.10.1

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
