### ISSUE TITLE
Feature request - Focus Item ability to "engage" CTA or any clickable element (add "when to engage" option)

### ISSUE THREAD

**Issue by khaoua** [mautic/mautic#5058]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | YES
| Enhancement? | 

## Description:
Below, we can see the different focus item "when to engage" triggering elements. As we already can include forms in Focus Items, it could more powerful, if focus item could be enabled by a specific click on an specific element (CTA, or else). It would add the option to use focus item a direct contact generator and make the CTA or clickable element more productive
![image](https://user-images.githubusercontent.com/25910708/31009862-2714b9f0-a509-11e7-8144-f6aea4e0eefd.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by khaoua** [comment]
@kuzmany in case you are interest :-) lol

**Comment by dbhurley** [comment]
At this time I'm going to close this. But I've marked it as a feature request so it will still be tracked. Happy to reopen if someone is interested in taking it on and providing a PR.

**Comment by khaoua** [comment]
Thanks for marking it as a Feature Request David, much appreciated!
