### ISSUE TITLE
Unit test testGetRunTimeSeconds sometimes fails

### ISSUE THREAD

**Issue by phil-davis** [mautic/mautic#5059]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Sometimes the unit tests fail with:
```
There was 1 failure:
1) Mautic\LeadBundle\Tests\Entity\ImportTest::testGetRunTimeSeconds
Failed asserting that 601 is identical to 600.
```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | current clone from GitHub of staging branch
| PHP version | 5.6

### Steps to reproduce:
1. run the unit tests lots of times
2. sometimes get the above test fail

**Comment by dbhurley** [comment]
@phil-davis Your PR's and issue reporting are on point. Thank you.

**Comment by phil-davis** [comment]
No problem - nice to see that some catch-up is happening on GitHub issues and outstanding PRs.

**Comment by npracht** [comment]
Hello @escopecz it can be closed :)
