### ISSUE TITLE
Blank fields in a CSV cause anonymous contacts to be added to segment if a custom field has a default value defined

### ISSUE THREAD

**Issue by sarahwernik** [mautic/mautic#5063]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | no
| Enhancement? | no

## Description:
When a user uploads a CSV file to a pre-determined segment and that file has empty rows then it causes anonymous contacts to be added into the segment. Because all of the empty fields are considered visitors, it will bring in anonymous contacts for each empty field. This happens when there is a custom field that has a default value. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | yes?
| PHP version | yes?

### Steps to reproduce:
1. Create a custom field with a default value
2. Upload a CSV file into a segment with empty fields
3. Click into the segment
4. Click on the anonymous contacts toggle within that segment and you'll see all those that were added
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by sarahwernik** [comment]
@cceruti - could you please add a Bug P1 label to this? Thanks!

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/1571
