### ISSUE TITLE
Changing timezone to UTC changes dates/times in contact history

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#5065]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
After I change the account timezone after contacts have been added to the platform then it messes up the dates/times an event took place within the contact's timeline.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
I don't understand the problem. Dates are always stored in the database in UTC and if loaded to the UI the dates are displayed in the timezone you request in the global configuration or in the user configuration. So if you change the timezone then all dates will be in that new timezone. Can you please elaborate on the issue?

**Comment by cceruti** [comment]
This issue was logged a while back (I was still new!), it has been resolved so I am closing the ticket.

Thank you!
