### ISSUE TITLE
Wrong "Contact created" date showing in contact events

### ISSUE THREAD

**Issue by AndrassGray** [mautic/mautic#5067]
[What](url) type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The Contact created date shows Today when it actually was Yesterday.

![m-wrong-date](https://user-images.githubusercontent.com/30862808/31043442-ff24f83e-a5bb-11e7-8956-d1e69bf54d26.jpg)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 7.0

**Comment by dbhurley** [comment]
This is related to when contact becomes "known". Not Anonymous visitor "created".
