### ISSUE TITLE
Wrong module name for Contacts in SugarcrmApi::getLeads()

### ISSUE THREAD

**Issue by johnmillis** [mautic/mautic#5073]
What type of report is this:

Bug report

## Description:
Pulling existing contacts from SugarCRM integration fails using SugarCRM version 6.5.16.

I believe the error is in file /plugins/MauticCrmBundle/Api/SugarcrmApi.php, function getLeads().

Line #584:
                $object      = ($object == 'Contact') ? 'Contacts' : 'Leads';

If getLeads() is called with $object already correctly set to "Contacts", then the above line changes it to the incorrect module name "Leads".

getLeads() is called from FetchLeadsCommand.php using $contactObjectName which is "Contacts" which is already correct for SugarCRM.

I suspect line #584 of SugarcrmApi.php needs to be replaced with these two lines:

                if ($object == 'Contact') $object = 'Contacts';
                elseif ($object == 'Lead') $object = 'Leads';

The above proposed fix appears to work.

## If a bug:

Mautic version: 2.10.1
PHP version: 7.1.18

### Steps to reproduce:

1. Pull contacts from SugarCRM integration using this command:
php app/console mautic:integration:fetchleads --integration=Sugarcrm --fetch-all

2. Check if contacts are pulled into Mautic.
 
### Log errors: 

The console output shows zero contacts are fetched.

**Comment by stevedrobinson** [comment]
This is fixed in pull request #5244 thanks to @mqueme
