### ISSUE TITLE
Campaign is not executing all tasks

### ISSUE THREAD

**Issue by Kedaranatha** [mautic/mautic#5079]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? | 

## Description:
Im having a problem with Campaign tasks execution.
camping is not triggering all tasks and  Campaign camping info displays 0s for all tasks.

nginx/1.10.3
Nginx configuration mysql basic (enabled)
PHP Version 5.6 (also tested on 7.0)
HHVM disabled
SSL enabled
----
tested on LAMP as well with php 5.6 and 7.0 same problem

For simplicity let's use this example/test plan: 
Double Opt-In Email Campaign

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
2.10.0 and 2.10.1
| PHP version | 
tested 5.6X and 7.0X

### Steps to reproduce:
For simplicity let's use this example/test plan: 
Double Opt-In Email Campaign

1. create lead and move it to {segment1}
2. create {confirm_landing} landing page
3. create email with url to {confirm_landing page}
4. create {segment1}, {segment2}, {segment3}
5. create {Campaign}
     Contact Source: segment1
          - move a contact to segment2
          - send email
                 --- Visit a page {confirm_landing page}
                 -----------if true: move a contact to segment3
                  and
                  add 10 points

!cron was run via SSH manually. no errors for cron.   
0,15,30,45 * * * *  php /var/www/folder_name/htdocs/app/console mautic:segments:update
5,20,35,50 * * * *  php /var/www/folder_name/htdocs/app/console mautic:campaigns:rebuild
*/5 * * * *  php /var/www/folder_name/htdocs/app/console mautic:campaigns:trigger

### Log errors: 
result:
1. receiving email ! i'm using a separate browser to open URL from the email.
2. contact moved to segment2
3. All other tasks are not executing.
4. Campaigns page /Decisions /actions all 0s

![30-09-2017-02-04-31](https://user-images.githubusercontent.com/20333234/31089304-64a3ac3a-a758-11e7-8eac-2748765b800d.png)
![30-09-2017-02-03-59](https://user-images.githubusercontent.com/20333234/31089306-64a80e92-a758-11e7-8480-d3d4cb9ecdb9.png)
![30-09-2017-02-00-55](https://user-images.githubusercontent.com/20333234/31089305-64a6d63a-a758-11e7-87bf-72c9f0d944b9.png)

no errors
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Can't replicate. If this still exists on 2.11 then please re-open and let's try to figure out why nothing is in logging.
