### ISSUE TITLE
Pipedrive contact sync. error when accent on character

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#5080]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Try to sync. contacts with accented characters in the firstname, lastname, position and you'll see it brake the sync. --> The value synced is stopped at the accented characters.

### Example:
Jérôme Bell ---> J Bell

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10

**Comment by npracht** [comment]
@mauticdevelopers & @thcodeine your support would be appreciated.

**Comment by kuzmany** [comment]
@npracht 
I tried Jérôme Bell  as firstname syn via from pipedrive integration and works.
Can you  re-test with last version?

![image](https://user-images.githubusercontent.com/462477/32231082-f8138612-be54-11e7-9f8f-a2e371f28261.png)
