### ISSUE TITLE
Focus Item loaded in iframe interfering with tracking

### ISSUE THREAD

**Issue by rowlandhill** [mautic/mautic#5083]
What type of report is this:Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Issue is with tracking due to the Focus Items being loaded in an iframe vs. regular HTML/CSS.  The form isn’t being recognized because it’s not in the same url as the actual landing page.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Yes
| PHP version | 

### Steps to reproduce:
1. Create Focus Item using HTML
2. Check tracking after interacting with Focus Item
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

@cceruti

**Comment by maltonite** [comment]
What do you mean by tracking? As in tracking in Google Analytics? Or just in Mautic?
