### ISSUE TITLE
Form Preview throws error with Mautic V4 Theme

### ISSUE THREAD

**Issue by rowlandhill** [mautic/mautic#5086]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
Forms that use Theme "Mautic V4" will not show in a preview - instead, and error is thrown.  All other form themes render the preview. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Yes
| PHP version | 

### Steps to reproduce:
1. Build Form
2. Select "Mautic V4" Theme
3. Click "Save % Close"
4. Select "Preview"
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

@cceruti

**Comment by dbhurley** [comment]
No Mautic V4 Theme available.
