### ISSUE TITLE
Feature Request:Dynamic Form

### ISSUE THREAD

**Issue by kolinz** [mautic/mautic#5088]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? |Y 
| Enhancement? | N

## Description:
Automatically insert last name and first name, email address, other contact data when "mautic" existing customers are using form.
It will be easier to answer the forms more than ever.

**Comment by wittwerch** [comment]
I think that feature already has landed in Mautic: https://mautic.org/docs/en/forms/progressive_profiling.html
