### ISSUE TITLE
Contact Monitoring: mtc_id ignored in mtc.js

### ISSUE THREAD

**Issue by hiniesta** [mautic/mautic#5093]
| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
mtc_id is ignoring in contact monitoring. As described here https://mautic.org/docs/en/contacts/contact_monitoring.html I have a 3º party web where my users can login. I have a service that return the user mautic_id. When user login, I destroy de current cookie, and set the mtc_id cookie as the real user id, but the response return other mautic_id and ignore the one is sent.

| Mautic version | v2.8.2
| PHP version | 5.6.30

**Comment by dbhurley** [comment]
Not replicable.

**Comment by UlTriX** [comment]
I am trying to do the exact same thing.

@hiniesta did you find any workaround?

My use case is that I need to correctly track multiple different users that use the same browser in an app users login into. 

I tried setting mtc_id  the  from the server to the id of the contact in mautic
at login but then using mt('send'... Mautic overrides the cookie with the contact id of the first user that first used the app.

Pedro
