### ISSUE TITLE
Dynamic email content DEC does not show appropriate options for some filters

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#5094]
| Q  | A
| ---| ---
| Bug report? | ⚠️ 
| Feature request? | 
| Enhancement? | 

## Description:
For few filters it seems that the filters options are not shown in the DEC options. For instance **email sent**.

![capture d ecran 2017-10-05 a 11 54 23](https://user-images.githubusercontent.com/14075239/31221503-2a81ff5c-a9c4-11e7-83f1-bf2589780e4c.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1

### Steps to reproduce:
1. Create and email
2. Add a DEC
3. Create a variant with the filter `email sent`

Simply notice that the drop down list of the sent email is missing !
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Fixed in 2.11
