### ISSUE TITLE
Landing Page Builder

### ISSUE THREAD

**Issue by dgram** [mautic/mautic#5095]
What type of report is this:

| Q  | A
| ---| ---
| Feature request? | Y
| Enhancement? | Y

## Description:
Hey, first of all, thanks for your hard work building mautic.
Last days i've found this open source landing page builder, which looks pretty powerful and looks pretty extendable, so i've thought eventually it makes sense to integrate them into mautic, or replace them with actually integration. It also has an newsletter builder integrated.

The builder can be found here and is also open source, [grapejs](http://grapesjs.com/).
I'ts not my project, so this should'nt be an advertising for this project, i hope it's ok to post it here.

regards, daniel

**Comment by YannickBiet** [comment]
Whaou it looks pretty gorgeous and far beyond actual capacities of the internal builder 
Text are editable right in their final destination !
You can preview the responsive version within a click tool

And there's an UNDO REDO button action available whatever the action done (deleting a block, changing a text) !!

Maybe it will be too complex for basic usage but when we want more control, it would be great to have this engine embedded ! I find it a lot more professionnal than the current builder !

Thanks for sharing !

**Comment by wucherpfennig** [comment]
This would be totally awesome if we could integrate this kind of solution into mautic! big +1 from my side.

**Comment by dbhurley** [comment]
Excellent find. Not something that's on the roadmap to replace at the moment so going to mark this as a `Backlog` issue (but definitely interesting).

**Comment by renannobile** [comment]
Any follow up on this?
