### ISSUE TITLE
Feature request: Images depending on custom leadfield with fallback option

### ISSUE THREAD

**Issue by Rixita** [mautic/mautic#5096]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes
| Enhancement? | 

## Description:
Custom field could be for ex. hotel.
When someone submits a form with the following data for ex.:
- Hotel: Bella Panorama

It would be nice to show an image of that particular hotel (depending on the submission) in the email send to the submitter.

Therefore to use something like: 
- `<img src="{{ getAssetUrl('media/images/{leadfield=hotel|fallback}.jpg', null, null, true) }}" />`
- The images per hotel have to be saved to the server of course.

This will work, but there are one issue:
What happens when there is a failure in the hotel name. There will not be an image on the server with the name spelled incorrectly. For ex. Bella Panirami instead of Bella Panorama.

In that case it would be great if the |fallback image would apply. At the moment the fallback option will only apply if the custom field value is empty.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by YannickBiet** [comment]
Did you try to use a dynamic content section in your email that includes a specific image ?

**Comment by Rixita** [comment]
Hi @YannickBiet,

If there would only be eg. 10 hotels, this would be no problem of course.
But if there are eg. 100, 500 or 1000+ hotels than the dynamic content section is not useful I think.

Kind regards,

**Comment by YannickBiet** [comment]
Yes that's true, but I was trying to give you a workaround with current version than waiting months for a solution :)
