### ISSUE TITLE
Track links in emails...

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#510]
I was surprised when the links in the email are not send to mautic to track the click and identify the user.

I think a lot of users use outlook or other mail clients that we cannot identify the open the mail with one cookie. I wish all links in the mail send by mautic will track the click and asociate the email with one cookie. By this we can identify the email-leads with the web-unidentified-leads

**Comment by alanhartless** [comment]
Hi Miguel,

This is a feature that is going to be in the next release. All links will be auto tracked.

Thanks!
Alan

**Comment by miguelpascual** [comment]
Great!!!

Miguel
