### ISSUE TITLE
WP Mautic 2.2.1 has bad path /mautic//mtc.js

### ISSUE THREAD

**Issue by ericross** [mautic/mautic#5100]
What type of report is this:

| Bug report? | 

## Description:
There bad path in the Mautic Wordpress plugin.

[my_user_site]/public_html/wp-content/plugins/wp-mautic
wpmautic.php on line 141 is:
	})(window,document,'script','<?php echo esc_url( $base_url ); ?>/mtc.js','mt');
Which generates this bad request:
        GET http://my_mautic_site/mautic//mtc.js net::ERR_ABORTED

## Work Around:
Edit [my_user_site]/public_html/wp-content/plugins/wp-mautic
wpmautic.php on line 141 to remove / at >mtc.js so new line is:
	})(window,document,'script','<?php echo esc_url( $base_url ); ?>mtc.js','mt');

Now, history shows page hit results expected:
    page name  - my_user_site name

## If a bug:

| Mautic version | 
2.10.1
| PHP version | 
5.6.30
| WP Mautic version |
2.2.1

### Steps to reproduce:
1. Embed a Mautic contact form as a widget in My Wordpress User Site using:
<p style="font-size: xsmall;"><script type="text/javascript" src="//my_mautic_site/mautic/form/generate.js?id=3"></script></p>

2. Load the main page http://[my_user_site/ and Chrome Developer Tools shows error:
        GET http://my_mautic_site/mautic//mtc.js net::ERR_ABORTED

3. Mautic history for Contact shows page hit: 
         http://my_mautic_site/mautic//mtc.js

### Log errors: 
No log errors found.

**Comment by AndrassGray** [comment]
Does not happen for me. Actually, if I enter a trailing slash at the Mautic URL in the WP-Mautic settings, it gets deleted when saving the form.

Try resaving the WP-Mautic settings (and then undo your fix).

**Comment by ericross** [comment]
I found this comment that suggests the Wordpress plugin url should not have a / at the end. Mine doesn't, and I still had ../mautic//mtc.js

buckhornmktg 15 Aug 2015 Edited 2 years ago by buckhornmktg 
I think Chad has your solution.

I haven't used the WP plugin, but I just ran into some issues with the Concrete5 plugin. It wasn't clear to me whether the URL was to include the tracking pixel or not. If WP is the same, your Mautic URL should be:
http://www.maindomainname.com/mautic  (or http://username.mautic.com  or http://www.maindomainname.com )

Not:
http://www.maindomainname.com/mautic/mtracking.gif 

I'm not sure if you need a trailing slash or not. If the tracking pixel looks like this with two slahes, then you don't need the slash (example above is w/o the slash). http://www.maindomainname.com/mautic//mtracking.gif

**Comment by dbhurley** [comment]
Unable to reproduce. Doesn't appear to be Mautic-specific.
