### ISSUE TITLE
How do batches work when sending a Segment Broadcast?

### ISSUE THREAD

**Issue by iadj** [mautic/mautic#5106]
I have a sending limit of 70 emails per second with Amazon SES. When I send a broadcast email with Mautic, it asks me for the amount of contacts to process per batch. How often does this batch happen? How is this calculated? Is there anything I should be configuring to make sure I don't go over my 70 emails per second sending limit?

**Comment by kuzmany** [comment]
There is no batch limit for  mautic:broadcasts:send command
You can use  global Queued Delivery settings for email channel. 
More https://mautic.org/docs/en/emails/index.html
