### ISSUE TITLE
Redirect URL does not work as it is connected to ID

### ISSUE THREAD

**Issue by qroft** [mautic/mautic#5109]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? |N 
| Enhancement? | N

## Description:
I am implementing a form inside a page on a subdomain.
If i fill out the form, the data is saved inside my contacts but the redirect does not work.
If i within HTML remove the form ID the data is saved AND the redirect works.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | Latest

### Steps to reproduce:
1. Copy the "manual form" codes into a website.
2. Submit form, redirect does not work.
3. Remove the ID attribut of the form
4. Data is saved and redirect works BUT chrome console says: 
Cannot read property 'getAttribute' of null

### Log errors: 
none.

**Comment by dbhurley** [comment]
This sounds like you may have a conflict with something else on the page and thus the javascript is failing (which halts the redirect). This is why removing the ID would allow it to work.
