### ISSUE TITLE
Languages in the language dropdown are always in English

### ISSUE THREAD

**Issue by phil-davis** [mautic/mautic#5110]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | N
| Enhancement? | Y

### Steps to reproduce:
1. Login and go to the Account" page where you can select your language.
2. Choose a language other than English (e.g. French)
3. Apply and refresh the page.

The "Language" title says "Langue" - good.
The language selected says "French". It should say "Francais".
Look for "Allemand" in the dropdown list - it is not there. "German" is there.

Seems a bit English-centric.

**Comment by phil-davis** [comment]
And even if I set the system language to, for example, "French", the list of language names in the "Langue" dropdown are all in English. I would have hoped that the language names would be in French - "Anglais", "Allemand", "Turc"...

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by phil-davis** [comment]
Yes, this is still the same.

Similar happens, for example, when adding a contact. When filling the address there is a "Country" field with a dropdown list. It always contains the English names of the countries.

But "Preferred Locale" correctly has the values in the language that the user has selected. e.g. when I set my account to French, then locales include "allemand", when in German it has "Deutsch" and when in English it has "German". So it is possible to translate the values in a dropdown like this so that the language names are as they are known by the currently selected language of the logged-in account.

**Comment by RCheesley** [comment]
@phil-davis would you consider looking at making a PR to add this functionality?
