### ISSUE TITLE
form : problem with bolean field : value "NO" does not submit

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5113]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
The bolean field is not pre-selectionned and does not submit when the answer is no. 
It is a required field to submit the form.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9 and 2.10
| PHP version | 

### Steps to reproduce:
1. Create a form
2. Create a bolean field, and map it to your custom field.
3. Take the values already created in your custom field
4. Select required = YES for this field
5. Fill the form and answer NO to the bolean field
6. Submit the form
7. Error message 

#### Error on 2.9
![image](https://user-images.githubusercontent.com/31535432/31328974-1820d326-acd8-11e7-8449-288f339ea079.png)

#### Error on 2.10
The form submit well but the value is not registered
![capture d ecran 2017-10-09 a 10 04 00](https://user-images.githubusercontent.com/31535432/31329207-4469d0a8-acd9-11e7-8044-d2b97548c3d9.png)

**Comment by kuzmany** [comment]
Hi, what type of form field is in step 2. I didn't see boolean type field in form.

![image](https://user-images.githubusercontent.com/462477/31881753-d356d2d2-b7e4-11e7-8c8d-83ba8dd9f8df.png)

**Comment by npracht** [comment]
Radio type !
Then in the values you add Yes / No (label and value) or 1 / 0

![capture d ecran 2017-10-23 a 11 41 58](https://user-images.githubusercontent.com/14075239/31882483-3b4bee2a-b7e7-11e7-9892-e268756e67e0.png)
