### ISSUE TITLE
Feature request : do not save campaign when bloc is not linked

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5115]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
If a bloc is not linked in the builder of a campaign, it should not be possible to save to avoid mistakes in the scenario.

| Q   | A
| --- | ---
| Mautic version | 2.9
| PHP version | 

### Steps to reproduce:
1. Create a new campaign and go in the builder
2. Add different blocs and unlink a bloc
3. Save and quit

**Comment by merlin0** [comment]
I don't think this is a good Idea, since you can actually send mails without a link. And sometimes this is intentional.
