### ISSUE TITLE
Editing a contact sets core fields to empty string

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#5117]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✓
| Feature request? | 
| Enhancement? | 

## Description:
Editing a contact sets its unset core fields to the empty string (`''`)
This can be problematic if there are any checks on `NULL` values

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 5.6

### Steps to reproduce:
1. Create a new contact setting a field like _First Name_ to any value
2. Check the database to see the contact's unset core fields (e.g. `firstname`, `lastname`, `email`) set to `NULL`
3. Update a lead setting a field like _Last Name_ to any value
4. Check the database to see the contact's unset text core fields (e.g. `firstname`, `lastname`, `email`) set to `''`
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Please test: https://github.com/mautic/mautic/pull/5259
