### ISSUE TITLE
Dynamic Content in Code Mode in the email builder broken

### ISSUE THREAD

**Issue by rowlandhill** [mautic/mautic#5120]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
Dynamic Content in Code Mode in the email builder does not work.  Once you're in Code Mode and the Dynamic Content tab appears, you click over to DC, but you cannot add variants, and when you click "+ New", it only creates a new "Default" section, but there's no way to add filters or another variant (please see attached video).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Yes
| PHP version | 

### Steps to reproduce:
1. Create new email
2. Click "Code Mode"
3. Navigate to Dynamic Content tab
4. There's no "add variant" button
5. See attached video

[DC Test for Agentology.zip](https://github.com/mautic/mautic/files/1369406/DC.Test.for.Agentology.zip)
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

@cceruti

**Comment by virlatinus** [comment]
Fixed in #5140
