### ISSUE TITLE
Bug - Segment Filter Contacts not updating, after changing filters

### ISSUE THREAD

**Issue by Rixita** [mautic/mautic#5123]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
When you have a segment set with a filter it works. The segment will show you the number of related contacts.

The cron jobs setting are correct.

**The problem:**
If you change the filter settings for the segment. The list of contacts will not update.

This pretty much makes the segments involved useless, cause it will not populate the correct contacts anymore.

**Dirty solution:**
If you go into phpMyAdmin you will see the table "lead_lists_leads" is not updating correctly.
The old contacts (according to the previous filter settings for the segment) are still in the list.

Of course you could do something like `DELETE FROM lead_lists_leads;` in phpMyAdmin.
... but this is not the way the go ;)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2.

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Make sure cron jobs are configured.

**Comment by Rixita** [comment]
Hi @dbhurley,

Thank you for your suggestion.

But as you can see I wrote "The cron jobs setting are correct.". -> therefore configured properly (according to the Mautic documentation).

Kind regards,

**Comment by joanmooreban** [comment]
It doesn't work for me neither. Using versión 2.14.2 with PHP 7.1. Logs don't show any error.

So, if I add a filter to the segment, and update the segments, several contacts should be removed but they won't. 

Any ideas?

**Comment by joanmooreban** [comment]
It does not work for me either. I'm using version 2.15.0 with PHP 7.1. 

Is this bug already in pipeline to be solve?

**Comment by ItDoBeNord** [comment]
Any update on this issue?
