### ISSUE TITLE
campaign builder : text apply and close the builder is not displayed well

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5128]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
In the builder of the campaign, text "apply" and "close the builder" is not well display
<img width="227" alt="apply and builder" src="https://user-images.githubusercontent.com/31535432/31439902-356148fa-ae8e-11e7-9f10-edba5571bda5.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 

### Steps to reproduce:
1. Create a new campaign
2. Launch the builder
3. Check the words "apply" and "close the builder" in the top left corner

**Comment by johbuch** [comment]
Hi David, this problem is still on.
Actually I did some test, it appears that the problem is about the lenght of the words.
In english it is ok as the words are short. But if you change the language for french for example, it will be displayed like mentionned in the issue.

**Comment by npracht** [comment]
@kuzmany did you have time to have a look ?

**Comment by kuzmany** [comment]
work in progress ;)

**Comment by kuzmany** [comment]
Fixed: https://github.com/mautic/mautic/pull/5434
