### ISSUE TITLE
campaign builder wrong error message

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5129]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
In the campaign builder, if you just add a segment to start the campaign and then click on apply there is an error message that says : at least one source of contact is required"
Even if there is already a segment added.
<img width="1255" alt="second error message" src="https://user-images.githubusercontent.com/31535432/31440205-5cca0282-ae8f-11e7-8bde-4ba899e91c26.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 

### Steps to reproduce:
1. Create a new campaign
2. Add the name of the campaign
3. Launch the builder
4. Add a segment
5. Click on "Apply"

**Comment by dbhurley** [comment]
Fixed, error now correctly states the need for an event.
