### ISSUE TITLE
focus item : problem with forms

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5130]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
In the creation of the focus item, when adding the form it does not appear in the focus item. But it appears in the header.
<img width="534" alt="focus item" src="https://user-images.githubusercontent.com/31535432/31440729-2def95d8-ae91-11e7-9f25-8b490be4119b.png">
<img width="415" alt="forms" src="https://user-images.githubusercontent.com/31535432/31440765-50222094-ae91-11e7-924c-edcc1cfd7518.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 

### Steps to reproduce:
1. Create a new focus item
2. Add the url of the Internet page
3. Type of the focus : collect data
4. Style : any style
5. Content : mode basic, fill the title and slogan and choose the form

**Comment by npracht** [comment]
@alanhartless you think that is corrected by https://github.com/mautic/mautic/pull/5000 ?

**Comment by dbhurley** [comment]
Corrected as mentioned.
