### ISSUE TITLE
Dynamic Content in Email showing {leadfield=firstname} AND {contactfield=firstname}

### ISSUE THREAD

**Issue by cceruti** [mautic/mautic#5133]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When editing Dynamic Content in email and adding "Hi {firstname}", it is showing this as a leadfield but this should be contactfield NOT leadfield. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. In an email, add dynamic content.
2. Use token "first name" and see leadfield and contactfield....should only be contactfield
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Both will work, this is a deprecated token/variable name and must remain until the next major release (3.x)
