### ISSUE TITLE
Mautic does not include all contact information if export exceeds a certain size

### ISSUE THREAD

**Issue by sarahwernik** [mautic/mautic#5139]
What type of report is this: Bug report, enhancement

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | Yes

## Description:
If a user tries to download a segment list and if it's above a certain limit (limit unknown) then the file does not include all contacts that were in the segment.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Yes
| PHP version | 

### Steps to reproduce:
1. Create a segment of over 50,000 contacts (not sure of the max limit here)
2. Export the file to CSV
3. The file takes a long time to download. 
4. When you open the file, only about 40,000 contacts will show in the file even though the segment count was 50,000.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
I believe this had been fixed since then. And if not then this PR will: https://github.com/mautic/mautic/pull/7432
