### ISSUE TITLE
Add PHP CURL extension check to the first installation step

### ISSUE THREAD

**Issue by robwent** [mautic/mautic#5145]
This is based on 2 reports from slack about issues with the dashboard on first load.

On the first load the dashboard shows a 500 error but the left menu loads.

Refreshing the browser loads the dashboard without issues.

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? |  X

## Description:
People starting a server with ubuntu don't have php-curl installed by default and the dashboard can show a 500 error on the first load but be fine when reloading.

@escopecz  found the problem/fix here https://mautic.slack.com/archives/C02HV76BW/p1507820618000842

The install script that checks php extensions doesn't check for curl that causes the error.

**Comment by YosuCadilla** [comment]
I was one of the 2 people having this problem, just installing the php-curl package solved the issue.

No idea if it's important but I had curl installed on the server, but not the php-curl package, maybe that is why the pre-install check didn't think it was missing?

This was my setup in case it can be of help: apache 2.4.xx / php 7.0.xx / mariadb 10 / ubuntu 16.04.xx

**Comment by Maxell92** [comment]
This seems that Mautic does not check for `curl` PHP extension.

**Comment by heathdutton** [comment]
Related: #4390

While adding composer dependency checking is great, these issues request the installer does a check as well. Need PRs.

**Comment by Aerendir** [comment]
I was opening an issue for the exact same problem, then searched for an already opened one and came to this.

A check about cURL is really helpful: I fully configured the server following the directives of the installation step, but it didn't alert me about cURL.

The result is that after login, I get a 500 error on the dashboard.

The logs all reference cURL constants that doesn't exist.

**Comment by Aerendir** [comment]
Which branch should have I to use to submit a PR?

**Comment by escopecz** [comment]
Staging. The default one.

**Comment by Aerendir** [comment]
I will submit a new PR using the default `staging` branch.

**Comment by Aerendir** [comment]
@escopecz , here the new PR against the `staging` branch: https://github.com/mautic/mautic/pull/7657

**Comment by tmdpny** [comment]
> I was one of the 2 people having this problem, just installing the php-curl package solved the issue.
> 
> No idea if it's important but I had curl installed on the server, but not the php-curl package, maybe that is why the pre-install check didn't think it was missing?
> 
> This was my setup in case it can be of help: apache 2.4.xx / php 7.0.xx / mariadb 10 / ubuntu 16.04.xx

I just want to say this WAS important. I've been pulling my hair out this morning on this - curl is installed but not detected... but tried php-curl and voila - fixed. THANK YOU
