### ISSUE TITLE
Could not update 2.9.2 to 2.10.1

### ISSUE THREAD

**Issue by hideokamoto** [mautic/mautic#5146]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes|
| Feature request? |no| 
| Enhancement? | not|

## Description:

I try to update core by cli but it does not works.

```
$ cd /PATH/TO/MAUTIC
$ php upgrade.php
Checking for new updates...updating to 2.10.1!
Extracting the update package...failed. Package could not be found!
```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2|
| PHP version | 5.6.31|
| OS| Amazon Linux 2017.09 |

### Steps to reproduce:

Run these command in cli.

```
$ cd /PATH/TO/MAUTIC
$ php upgrade.php
Checking for new updates...updating to 2.10.1!
Extracting the update package...failed. Package could not be found!
```

I try to get upgrade.php from GitHub.But I saw same error.

```
$ cd /PATH/TO/MAUTIC
$ wget https://raw.githubusercontent.com/mautic/mautic/master/upgrade.php
$ sudo chown apache:apache upgrade.php
$ php upgrade.php
Checking for new updates...updating to 2.10.1!
Extracting the update package...failed. Package could not be found!
```

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

```
$ tail app/logs/mautic_prod-2017-10-13.php 
```

**Comment by williamhrs** [comment]
I also have this problem

**Comment by GharTok** [comment]
Same issue - workaround:
manually download 2.10.1, then rename the zip file to 2.10.1-update.zip
then you should be able to run upgrade.php

wget https://github.com/mautic/mautic/releases/download/2.10.1/2.10.1.zip
