### ISSUE TITLE
Export/Import Mautic Form Structure

### ISSUE THREAD

**Issue by sobujbd** [mautic/mautic#5147]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | Yes

## Description:
If is there an option for export / import form structure then it would be very good I think.

**Comment by groovenectar** [comment]
Yes this would be super useful.. That way a data migration can be avoided that could potentially overwrite submissions.. Even if the only way to import is to create a new form to avoid conflicts with existing data mapping...
