### ISSUE TITLE
Unable to un-publish a plugin when the plugin is erroring

### ISSUE THREAD

**Issue by isleshocky77** [mautic/mautic#5148]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y 

## Description:

When a integration has an error it shows up in the integration plugin settings dialog as a form error which means you can disable (unpublish) the plugin if you'd like to do that.

In this case when a Salesforce account is closed Mautic adds an integration error "inactive organization, Session expired or invalid" to the settings form. If the organization is closed, you obviously can't just update the credentials or anything like that. So the correct thing to do would be to "UnPublish" the plugin to disable it.

The form won't allow you to submit the form with the setting changed.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.10.1
| PHP version | 5.6

### Steps to reproduce:
1. Setup Salesforce integration
2. Disrupt the Salesforce servce
3. Attempt to mark the plugin as "Published: No"

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
