### ISSUE TITLE
Mautic doesn't update tracking settings code after editing "System Settgins" > "Site URL"

### ISSUE THREAD

**Issue by dmelo** [mautic/mautic#5151]
| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I have installed Mautic without providing the Site URL, and it defaulted to http://mautic/. Then I went to Configuration > System Settings and changed the site URL to the URL Mautic is residing. I have applied the changed. Some hours afterwards, when I go to Configuration > Trackin Settings, I still see the code snippet as if I had the old URL:

```
<script>
    (function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
        w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),
        m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)
    })(window,document,'script','http://mautic/mtc.js','mt');

    mt('send', 'pageview');
</script>
```

I can edit the http://mautic/mtc.js to point to the actual URL, but when loaded on a web page, the script is still making requests to http://mautic/, instead of the new address.

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 7.0.23

### Steps to reproduce:
1. Install Mautic as described in https://github.com/dmelo/docker-mautic-letsencrypt
2. Go to Configuration > Tracking Settings and check that the code snippet is pointing to 'http://mautic/mtc.js'
3. Go to Configuration > System Settings and change the Site URL
4. Click on Save & Close
5. Go again to Configuration > Tracking Settings and check that the URL on the code snippet is still pointing to http://mautic.mtc.js, instead of the new URL.

**Comment by MxyzptlkFishStix** [comment]
Clear your cache.

**Comment by dmelo** [comment]
After clearing the cache I have the following:

```
dmelo@merov2:~$ curl https://mautic.diogomelo.net
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=https://mautic/" />

        <title>Redirecting to https://mautic/</title>
    </head>
    <body>
        Redirecting to <a href="https://mautic/">https://mautic/</a>.
    </body>
</html>dmelo@merov2:~$ 
```

I'm using reverse proxy. I think the name used on the reverse proxy `http://mautic` is superseding the `site_url` configuration, which is set to the right URL.

**Comment by dmelo** [comment]
I have tried again with a clean installation and got the same result. Behind a reverse proxy, if I fix the Site URL and clear the cache, Mautic will redirect me to `http://mautic.com`. Any help?

**Comment by lexvansonderen** [comment]
I'm having the same issue. It also affects the form submit url resulting in mixed content forms and submit being blocked by the browser:
> Mixed Content: The page at 'https://www.domain.com/contact/' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://mautic.domain.com/form/submit?formId=1'. This endpoint should be made available over a secure connection.
> (index):1 Mixed Content: The page at 'https://www.domain.com/contact/' was loaded over HTTPS, but requested an insecure form action 'http://mautic.domain.com/form/submit?formId=1'. This request has been blocked; the content must be served over HTTPS.

**Comment by jonathascarrijo** [comment]
Same here. Couldn't find a way to work around this, and Mautic usage as an analytics tool gets severely limited as a consequence. I would assign a 'breaking' sort of label to this issue.

**Comment by AlbanL74fr** [comment]
Yes this problem prevents me to use Mautic as well on our website. When can it be fixed?

**Comment by MxyzptlkFishStix** [comment]
This is an old post, but if the OP would have initially stated he was behind a proxy, this could have easily been resolved. If you're behind a proxy, put the proxy IP in "Trusted proxies" under Configuration in the Miscellaneous section.

**Comment by AlbanL74fr** [comment]
I am using SSL terminating proxy (Amazon Load Balancer). I used to struggle a lot to find how to remove the mixed content warning and have my Mautic's forms, landing pages and dynamic web content work in this configuration.
I finally figured it out. Here's what worked for me: 
1) Make sure you tracking pixel code contains HTTPS urls only. Check in GTM if you use this as your tag manager.
2) In Mautic, make sure your site_url is in HTTP, then clear the cache.
3) Then, change your site_url to HTTPS, and at the same time fill your proxy IP in "Trusted proxies" under Configuration in the Miscellaneous section.. Only using 0.0.0.0/0 worked for me, by the way.
4) Hit "Save" and clear the cache again.
5) Finally, go to your forms and rebuild your forms cache. It's important if you integrated some forms in your website using script.
Hope it helps.

**Comment by andjules** [comment]
I am having similar problems.
- both main site (example.com) and mautic (mautic.example.com) have valid SSL certs and calling a page at `https://example.com` throws a mixed warning that it is trying to load `https://mautic.example.com/mtc.js` even though the tracking code in head explicitly calls https://mautic.example.com/index.php/mtc.js. I see inside mtc.js ~line 75 is a spot where it calls itself (without the '/index.php/') using this for the protocol `(l.protocol=='https:'?'https:':'https:')`
- both are hosted on the same Digital Ocean server (under Cloudways management system)
- I think this started after upgrading to 2.14

**Comment by cusspvz** [comment]
@andjules it has to do with LB / reverse proxy. Make sure to add the IP of the loadbalancer or `0.0.0.0/0` to the trusted proxies list on settings.

**Comment by npracht** [comment]
I cannot reproduce
