### ISSUE TITLE
Add some context info for Webhook payload

### ISSUE THREAD

**Issue by rctlopes** [mautic/mautic#5152]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

#### Some background info:
 
My business partner is a guitar teacher, and he has few online guitar courses. Currently we advertise his courses and collect leads (subscribers) into MailChimp, and the subscribers are added to different lists (groups), based on the product that they are interested. We have one single list and identify subscribers by groups, that works like different lists.

One of these courses is a free course, and as soon as the lead's double optin is confirmed, MailChimp adds to the proper group, and a webhook message is sent to the configured endpoint. In our application, we filter the webhook messages by the message type (only subscribers added to a group), so we create a free account to the course and send an email with access information to the subscriber.

A friend of mine told me about Mautic and it seems amazing what was accomplished on this product, and I decided to try it out. Implementing the double optin isn't as straight forward as MailChimp, but I managed to make it happen. However, when I tried the webhook messages for the "Contact Updated Event", I noticed few things:

- The payload is huge, and I can't customize it (unless I code an extension myself, but unfortunately I don't know how). For us, just the email and some context would be enough, for example.
- Multiple similar messages are sent for the same subscriber, when the subscriber is created. I guess that it is because of the actions performed in the campaign (double optin confirmation sent, pending tag added, add subscriber to the confirmed list after confirming the double optin, change the tag from pending to confirmed, etc)
- No context. There is no identification of who triggered the event. I don't know if was a campaign, if it was a manual change, what segment it belongs to, tags (I see tags in the payload, but comes empty)... No information. Since I have multiple segments, I don't know what segment it is coming from

#### Enhancement suggestion:

1. Add some context to the payload. I mean, what campaign triggered the event; the segment that the subscriber belongs to (now); The tags that the subscriber has (now)
2. If possible, allow us to say what info has to be part of the payload.

### Steps to reproduce:
1. Configure a webhook with the "Contact Updated Event" checked
2. Create two segments (pending and confirmed)
3. Create a landing page as a thank you page for confirming subscription
4. Create an email with a link to the landing page, asking the subscriber to confirm the subscription
5. Create a form that would add the subscriber to the pending segment; add a "pending" tag and send a confirmation email
6. Create a campaign linked to the Pending segment, with a "Visit a Page" decision, if yes, move the subscriber from the pending segment to the confirmed segment; add the subscriber to the "Confirmed" tag; remove the "Pending" tag
7. If you check the webhook messages received, you'll notice that you should receive around 5 messages, and all of them are very similar, and no context information provided. No segment, tag or campaign information.

This is my first time asking for an enhancement or reporting a bug. I hope I did it right.

Many thanks!
Rob

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
