### ISSUE TITLE
Duplicate Open Email points

### ISSUE THREAD

**Issue by bossanyit** [mautic/mautic#5155]
What type of report is this:

| Bug report | 

## Description:
Tested with a segment with more than 3000 subscribers.
Open email points: 7
Click to a specific URL: 3 points

The normal behaviour is 10 points if somebody clicks to an URL.
However somebody, who does not load the pictures will get 17 points.
If the subscriber loads the pictures (open email) the he will receive 10 points.

So the hippotesis: clicking to the email without downloading the email tracking pixel will duplicate the "open email" points.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 5.6

### Steps to reproduce:
1. Create an email "Email A"
2. Create a segment S1
3. Create a campain C1 source S1 which sends the Email A after 10 mins in relative time
4. Create the Manage Actions: open an email 7 points, click to an URL 3 points
5. Create 2 subscribers SUB1, SUB2
6. Wait until the email is received for SUB1 and SUB2
7. Download the pictures for SUB1 (receives 7 points) click to the URL (receives 3 points) - this is the good case
8.Click to the URL without downloading the pictures in the email (receives 17 instead of 10 points) - email client: Thunderbird

Extension: this behavior has been tested with email clients Thunderbird, Outlook 2003 and on gmail web.

Attached the Audit log and the Manage Actions for the points definition.

![mautic_points2](https://user-images.githubusercontent.com/5592437/31610073-fbb1190e-b276-11e7-9d69-1d144001fc54.PNG)

![mautic_points1](https://user-images.githubusercontent.com/5592437/31610069-f7e61982-b276-11e7-8f02-e9525e636aee.PNG)

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
