### ISSUE TITLE
500 Internal Server Error when creating report (with Columns: "unsubscribed" and group by function)

### ISSUE THREAD

**Issue by avaladejosh** [mautic/mautic#5161]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
When creating a report using "Email" as Data Source, if include "Unsubscribed" as one of the columns, it shows 500 internal server error every time. Moreover, the same issue occurs when using "Group by" function on the bottom. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.10.1
| PHP version | 7.0.22-0ubuntu0.16.04.1

### Steps to reproduce:
When choosing "Unsubscribed" under Columns
1. Go to Reports ->"+ New"
2. Data Sources" Emails"
3. Go to "Data" tab -> Columns-> choose "Unsubscribed"
4. Press "Save & Close" -> Error message should appear
 
When using "Group by" function
1. Go to Reports ->"+ New"
2. Data Sources" Emails"
3. Go to "Data" tab -> Group by -> choose anything
4. Press "Save & Close" -> Error message should appear

### Log errors: 
"Unsubscribed issue"
<pre><code>[2017-10-17 11:50:29] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT e.name AS e_name, e.sent_count AS sent_count, e.read_count AS read_count, CONCAT(ROUND((e.read_count/e.sent_count)*100, 1),'%') AS read_ratio, cut.unique_hits AS unique_hits, cut.hits AS hits, COUNT(DISTINCT dnc.id) AS unsubscribed FROM emails e LEFT JOIN emails vp ON vp.id = e.variant_parent_id LEFT JOIN categories c ON c.id = e.category_id LEFT JOIN (SELECT COUNT(cut2.channel_id) AS trackable_count, SUM(cut2.hits) AS hits, SUM(cut2.unique_hits) AS unique_hits, cut2.channel_id FROM channel_url_trackables cut2 WHERE cut2.channel = 'email' GROUP BY cut2.channel_id) cut ON e.id = cut.channel_id WHERE e.name = ? GROUP BY e.id LIMIT 30 OFFSET 0' with params ["testing"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dnc.id' in 'field list'" at /var/www/clients/client1/web2/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT e.name AS e_name, e.sent_count AS sent_count, e.read_count AS read_count, CONCAT(ROUND((e.read_count/e.sent_count)*100, 1),'%') AS read_ratio, cut.unique_hits AS unique_hits, cut.hits AS hits, COUNT(DISTINCT dnc.id) AS unsubscribed FROM emails e LEFT JOIN emails vp ON vp.id = e.variant_parent_id LEFT JOIN categories c ON c.id = e.category_id LEFT JOIN (SELECT COUNT(cut2.channel_id) AS trackable_count, SUM(cut2.hits) AS hits, SUM(cut2.unique_hits) AS unique_hits, cut2.channel_id FROM channel_url_trackables cut2 WHERE cut2.channel = 'email' GROUP BY cut2.channel_id) cut ON e.id = cut.channel_id WHERE e.name = ? GROUP BY e.id LIMIT 30 OFFSET 0' with params [\"testing\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'dnc.id' in 'field list' at /var/www/clients/client1/web2/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dnc.id' in 'field list' at /var/www/clients/client1/web2/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dnc.id' in 'field list' at /var/www/clients/client1/web2/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91)"} []
</code></pre>
"Grouping issue"
<pre><code>[2017-10-17 11:52:48] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT e.name AS e_name FROM emails e LEFT JOIN emails vp ON vp.id = e.variant_parent_id LEFT JOIN categories c ON c.id = e.category_id GROUP BY cmp.name':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cmp.name' in 'group statement'" at /var/www/clients/client1/web2/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT e.name AS e_name FROM emails e LEFT JOIN emails vp ON vp.id = e.variant_parent_id LEFT JOIN categories c ON c.id = e.category_id GROUP BY cmp.name':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'cmp.name' in 'group statement' at /var/www/clients/client1/web2/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cmp.name' in 'group statement' at /var/www/clients/client1/web2/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cmp.name' in 'group statement' at /var/www/clients/client1/web2/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"}  []
</code></pre>
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
I can confirm I am getting a 500 error when using 'group by' and 'Campaign':

`[2018-01-24 12:18:24] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT e.id AS e_id, e.subject AS subject, DATE(es.date_sent) AS date_sent, es.email_address AS email_address, IF(dnc.id IS NOT NULL AND dnc.reason=2, 1, 0) AS bounced, IF(dnc.id IS NOT NULL AND dnc.reason=1, 1, 0) AS unsubscribed, es.retry_count AS retry_count FROM mauxj_email_stats es LEFT JOIN mauxj_emails e ON e.id = es.email_id LEFT JOIN mauxj_leads l ON l.id = es.lead_id LEFT JOIN mauxj_ip_addresses i ON i.id = es.ip_id LEFT JOIN mauxj_emails vp ON vp.id = e.variant_parent_id LEFT JOIN mauxj_categories c ON c.id = e.category_id LEFT JOIN mauxj_lead_donotcontact dnc ON e.id = dnc.channel_id AND dnc.channel='email' AND es.lead_id = dnc.lead_id WHERE (es.date_sent IS NULL OR (es.date_sent BETWEEN ? AND ?)) AND ((IF(dnc.id IS NOT NULL AND dnc.reason=2, 1, 0) = ?) OR (IF(dnc.id IS NOT NULL AND dnc.reason=1, 1, 0) = ?)) GROUP BY cmp.name' with params ["2017-12-25 00:00:00", "2018-01-24 12:18:24", "1", "1"]:  Unknown column 'cmp.name' in 'group statement'" at /home/mysite/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT e.id AS e_id, e.subject AS subject, DATE(es.date_sent) AS date_sent, es.email_address AS email_address, IF(dnc.id IS NOT NULL AND dnc.reason=2, 1, 0) AS bounced, IF(dnc.id IS NOT NULL AND dnc.reason=1, 1, 0) AS unsubscribed, es.retry_count AS retry_count FROM mauxj_email_stats es LEFT JOIN mauxj_emails e ON e.id = es.email_id LEFT JOIN mauxj_leads l ON l.id = es.lead_id LEFT JOIN mauxj_ip_addresses i ON i.id = es.ip_id LEFT JOIN mauxj_emails vp ON vp.id = e.variant_parent_id LEFT JOIN mauxj_categories c ON c.id = e.category_id LEFT JOIN mauxj_lead_donotcontact dnc ON e.id = dnc.channel_id AND dnc.channel='email' AND es.lead_id = dnc.lead_id WHERE (es.date_sent IS NULL OR (es.date_sent BETWEEN ? AND ?)) AND ((IF(dnc.id IS NOT NULL AND dnc.reason=2, 1, 0) = ?) OR (IF(dnc.id IS NOT NULL AND dnc.reason=1, 1, 0) = ?)) GROUP BY cmp.name' with params [\"2017-12-25 00:00:00\", \"2018-01-24 12:18:24\", \"1\", \"1\"]:\n\nUnknown column 'cmp.name' in 'group statement' at /home/mysite/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\Mysqli\\MysqliException(code: 0): Unknown column 'cmp.name' in 'group statement' at /home/mysite/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:101)"} []`

I think this is directly related to #4908

**Comment by escopecz** [comment]
Cannot replicate either of the 2 scenarios. Can you please retest with latest Mautic version? Closing for now.

**Comment by namratasaun** [comment]
hello, I got a 500 error when i selected email sent as the data source and used group by name. without group by it is working fine.
My mautic version - 3.2
