### ISSUE TITLE
Pipedrive select type field does not sync. data

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#5163]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When you try to sync. a select type field, the fields are mapped but not synced.

### Configuration in Pipedrive
![capture d ecran 2017-10-17 a 11 00 31](https://user-images.githubusercontent.com/14075239/31655892-8fba0c56-b32a-11e7-88ab-c4bdac9766f3.png)

### Configuration in Mautic
![capture d ecran 2017-10-17 a 11 00 57](https://user-images.githubusercontent.com/14075239/31655925-9edcd97a-b32a-11e7-9c7b-c0733a2b24d8.png)
![capture d ecran 2017-10-17 a 11 01 03](https://user-images.githubusercontent.com/14075239/31655938-a48e84ae-b32a-11e7-9726-32aa5242033d.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1

**Comment by kuzmany** [comment]
@npracht 
Try 
https://github.com/mautic/mautic/pull/5258 

But need set  labels and values like  on screenshost (value have to be ID of custom value from your Pipedrive)

![image](https://user-images.githubusercontent.com/462477/32236462-76bc979e-be62-11e7-8fcc-89f76c3f92cf.png)

**Comment by javjim-mautic** [comment]
Already merged
