### ISSUE TITLE
BR: Incorrect Form Post URL Generation After Migrating Database from Older Mautic Version with Different Root URL | Cache Clear Doesn't Fix

### ISSUE THREAD

**Issue by Kyle-Foley** [mautic/mautic#5171]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
When migrating a Mautic database from an older version with a different root URL to the latest stable version, the HTML embed code generated by the Mautic form will retain the legacy root URL. 

This bug only affects forms carried over from the previous Mautic installation. New forms or duplications of old forms do not have the issue, but this is not an ideal fix as you lose the form submission history. 

This bug does not affect the "preview form" action. It does prevent form submission via the "Manual" form insertion, the "Automatic" form insertion and form insertion via the Wordpress Plugin.

While my particular issue came from migrating an old version of Mautic to a new version, it is possible that this bug exists when migrating databases between identical versions with different root URL settings.

Clearing the application cache does not fix the issue. All steps from the [suggested steps](https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful) were followed.

This bug presents itself as both a CORS error and a 404 error in the console, so this may be responsible for a number of the unsolved CORS bug reports.

A temporary fix can be achieved by copying the HTML code from the "Manual" form submission option and replacing the old root URL with the new root URL. Example below.

ORIGINAL POST REQUEST
`<form autocomplete="false" role="form" method="post" action="https://exampledomain.com/old-mautic-url/form/submit?formId=24" id="mauticform_quoterequestform" data-mautic-form="quoterequestform">`

REPLACEMENT POST REQUEST
`<form autocomplete="false" role="form" method="post" action="https://exampledomain.com/new-mautic-url/form/submit?formId=24" id="mauticform_quoterequestform" data-mautic-form="quoterequestform">`

**UPDATE WITH BETTER FIX**

In MySQL, the bad legacy URLs are located in table "ma_forms", column "cached_html". 

This is strange because I repeatedly cleared the cache and the issue did not resolve, however, the issue **did** resolve when I ran a query to replace the legacy URLs with the updated URLs in the cached_html column of every row.

## If a bug:

Pre-Migration
| Q   | A
| --- | ---
| Mautic version | v2.9.0
| PHP version | 5.6.30

Post-Migration
| Q   | A
| --- | ---
| Mautic version | v2.10.1
| PHP version | 7.0.24

### Steps to reproduce:
1. Backup the MySQL database from an instance of Mautic that has forms.
2. Migrate that database to a Mautic instance that has a different root URL setting.
3. Embed the form in a web-page.
4. Attempt to submit the form.
5. Check the console for errors.

**Comment by escopecz** [comment]
The form HTML cache must be rebuilt. Check https://www.mautic.org/docs/en/forms/index.html.
