### ISSUE TITLE
Focus Item Submission Stats are wrong

### ISSUE THREAD

**Issue by maltonite** [mautic/mautic#5175]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When reviewing submission stats on focus items, the system is showing the same submission count (but not views). Submission stats are being shown for focus items which aren't live. I do realise that there is an issue with focus items in 2.10.1.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 7.1.5

### Steps to reproduce:
1. Create at least two focus items with a form
2. Generate views and submissions for both
3. The stats for the submissions will be wrong.
 
### Log errors: 

N/A

### Query that might need updating
[mautic/plugins/MauticFocusBundle/Model/FocusModel.php](https://github.com/mautic/mautic/blob/master/plugins/MauticFocusBundle/Model/FocusModel.php) lines 404 and 411. At the moment the query doesn't look for rows which are only applicable for that focus item. I think the lines should be:

404
`$q = $query->prepareTimeDataQuery('focus_stats', 'date_added', ['type' => Stat::TYPE_CLICK,'focus_id' => $focus->getId()]);`

411
`$q = $query->prepareTimeDataQuery('focus_stats', 'date_added', ['type' => Stat::TYPE_FORM,'focus_id' => $focus->getId()]);`

**Comment by maltonite** [comment]
I have made a pull request #5257 to fix the above. Currently failing one of the tests under PHP 7.1 (I have tested under php 7.1 locally and don't have any issues).

**Comment by npracht** [comment]
#5257 merged far far ago
