### ISSUE TITLE
[Feature request] Form: POST to URL

### ISSUE THREAD

**Issue by hmaesta** [mautic/mautic#5182]
## Description

Right now there are 3 possible actions after a form submit:

- Stay _(do nothing after submit)_
- Redirect to URL
- Show message

Would be very useful a new option: **POST to URL.** 

When form data was successful posted to Mautic, it would do a POST to some other page, where the developer could do something with data provided. 

## Usage example
The form code would be the same: _(below just to exemplify)_
```html
<form id="mautic-form">
   <input name="mautic-name" type="text" placeholder="Whats your name?" />
   <input name="mautic-email" type="text" placeholder="Whats your e-mail?" />
   <button type="submit">Submit</button>
</form>
```

And them my page, configured as "POST to URL", could be:
```php
<?php
   $user_name = $_POST["mautic-name"];
   $user_email = $_POST["mautic-email"];
?>
<h1>Welcome, <?php echo $user_name; ?>!</h1>
```

## Why
Right now Mautic is absolutely incredible for the average user, but is kind of limited for developers that want to do something else with data. This would be a way to fix that.

### Today
Today to accomplish a submit to another page is necessary a Javascript like `$('#mautic-form').submit(...)` and set form to do nothing after submit (on Mautic).

Ps: changing form action URL does nothing when Mautic javascript is loaded.

**Comment by kuzmany** [comment]
We're using API for that  https://developer.mautic.org/#get-contact

**Comment by hmaesta** [comment]
Just figured that this is already on Mautic. 

`Form > Actions > Post results to another form > URL post`

**Comment by ilearnbydoing** [comment]
I tried form action "Post results to another form" but it did not worked in my case.
(I am trying to import form result in external CRM via CRM lean form feature)
how does it works for you?
thanks

**Comment by ilearnbydoing** [comment]
Hi,

I got it fixed after analyzing the Mautic post raw result via https://requestb.in.

Thanks
