### ISSUE TITLE
Multiple select field not showing single selected option

### ISSUE THREAD

**Issue by lukascellar** [mautic/mautic#5184]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? |No 
| Enhancement? | No

## Description:
Multiple select field in contact editor is not showing single selected value. If multiple values are selected, everything works fine.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.10.1
| PHP version | 7.1.10

### Steps to reproduce:
1. Create custom field with "Select - multiple" type, define available options
2. Assign 1 value for this field in contact editor and submit form
3. You will see empty value field

If you select 2 or more options, everything works fine.

**Comment by mqueme** [comment]
https://github.com/mautic/mautic/pull/5178

**Comment by dbhurley** [comment]
Resolved
