### ISSUE TITLE
Mautic Helper Extension: E-Mails with a dash inside brake

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#5187]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N 
| Enhancement? | N

## Description:

If I want to track a Gmail sent so an email with a dash in it, e.g. user@domain-name.com, it will save as a new contact with user@domain instead of the full domain name.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.10.1
| PHP version |  7.1.1

... and already since at least Mautic 2.9

### Steps to reproduce:
1. send a gmail to an email address with a dash inside
2. track it with the mautic helper
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by be-mohand** [comment]
+1 

I have the same problem

**Comment by Tony-Gavin** [comment]
Having the same issue. Also, when I edit the email and the user opens the email again, a new record is created in Mautic, which effectively replicates what I've just gotten rid of by editing out the incorrect email.
