### ISSUE TITLE
Duplicate Points on Form Action where Company field present

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#5188]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✓
| Feature request? | 
| Enhancement? | 

## Description:

If a form has an _Adjust Contact's Points_ action and a _Company_ field, the points are added twice.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 5.6

### Steps to reproduce:
1. Create a form with an Email and Company field, both mapped to the respective contact fields
2. Add an _Adjust Contact's Points_ form action, let's say +5 points
3. Submit the form
4. Check out the contact's sheet
5. Notice the contact has twice the expected amount of points (10 if you used 5 points)
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by MaxWebmecanik** [comment]
This only happens if the contact is new.

**Comment by kuzmany** [comment]
This works for If I go back to and Re-test step 1. 
Zapier  recommend it as last option. See screenshot

![image](https://user-images.githubusercontent.com/462477/31897316-41902150-b816-11e7-8bc7-1c8d3dd34379.png)

**Comment by kuzmany** [comment]
Fixed https://github.com/mautic/mautic/pull/5191
Please test

**Comment by YannickBiet** [comment]
In our case the difference of point is 4 times the number of points earned in the form maybe this is related to the number of FIELDS that appears just after the company field in the form (we have 6 fields with 4 fields after the company one)

**Comment by kuzmany** [comment]
Maybe should be close favor to already merged https://github.com/mautic/mautic/pull/5314  based on https://github.com/mautic/mautic/pull/5191
