### ISSUE TITLE
Missing DKIM in email sent using "Other SMTP server" option

### ISSUE THREAD

**Issue by wpon** [mautic/mautic#5190]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Missing DKIM in email sent using "Other SMTP server" option on "Service to send mail through".

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.1
| PHP version | 5.6.30

### Steps to reproduce:
1. (After DKIM properly set) Use SMTP to send a email without Mautic (sending using SMTP). Result: DKIM=pass
2. Use same SMTP server on Mautic, using "Other SMTP server" option on: Configuration » Email Settings » Mail Send Settings » Service to send mail through
Result: DKIM-signature is missing
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
That might be a server and domain configuration issue.
