### ISSUE TITLE
Add "Mailer Is Owner" token within emails/campaigns

### ISSUE THREAD

**Issue by rowlandhill** [mautic/mautic#5192]
What type of report is this: Feature Request

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Yes
| Enhancement? | 

## Description:
As a user, I want the "Mailer Is Owner" feature to stop being a global feature and instead become a local feature.  I would like a "Mailer Is Owner" token available within a campaign (within the send email action?) and also available within emails.
The reason I want this feature, is soI don't have to toggle the feature on and off, and can have some campaigns use the feature, and others use the default.
As a substitute for the global feature being removed, we can have a default mailer.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Yes
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Moved to mautic-internal/mautic-internal#1
