### ISSUE TITLE
Can not update the Japanese language

### ISSUE THREAD

**Issue by kolinz** [mautic/mautic#5193]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y|
| Feature request? | 
| Enhancement? | 

## Description:
While manually updating mautic from v2.10.0 to v2.10.1 .  I got the following error message. Mautic looks like is working.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.0
| PHP version |  PHP 7.0.24

### Steps to reproduce:
1. Move Mautic install directory
2. cd app
3. php console mautic:update:find -e prod
4. php console mautic:update:apply -e prod

Step    7 [------->--------------------] mautic.core.command.update.step.update_languages                  PHP Warning:  file_put_contents(/var/www/html/mautic/app/cache/prod/ja.zip): failed to open stream: No such file or directory in /var/www/html/mautic/app/bundles/CoreBundle/Helper/LanguageHelper.php on line 264

'Japanese' 言語をアップデートできませんでした。
Step    8 [-------->-------------------] mautic.core.update.migrating.database.schema               Step    9 [============================] 成功! Mauticのバージョン 2.10.1 が動いています。

**Comment by hideokamoto** [comment]
Have you try following command ?

```
$ php console  mautic:transifex:pull
```

You can check this page (written in Japanese)
https://concrete5.co.jp/blog/mautic-pull-translation
