### ISSUE TITLE
Mautic created custom fields do not synchronise with Pipedrive

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5195]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | X
| Enhancement? | 

## Description:
Native mautic custom fields synchronise well with Pipedrive but custom fields created do not sync.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 

### Steps to reproduce:
1. Create a custom field
2. Set the pipedrive <> mautic integration
3. Create or update a contact in Pipedrive (using created custom fields)
4. Infos in the created custom field in Mautic do not sync

**Comment by johbuch** [comment]
@thecodeine do you know about it ?

**Comment by kuzmany** [comment]
Works for me.

Created  cutom text field in Pipedrive
Create custom text fiied in Mautic
Match hte fields in Pipedrive integration.
Create form with custom text field and sync works well

@npracht

**Comment by johbuch** [comment]
@kuzmany 
Can you try in this way: pipedrive to mautic
Create a contact in pipedrive. This contact should be created automatically in mautic. But the custom fields created does not update.

**Comment by kuzmany** [comment]
@johbuch yeah, soon

**Comment by npracht** [comment]
@kuzmany any update ?

**Comment by kuzmany** [comment]
No yet.

**Comment by kuzmany** [comment]
This should fix it https://github.com/mautic/mautic/pull/5350

**Comment by alanhartless** [comment]
Fixed in https://github.com/mautic/mautic/pull/5350
