### ISSUE TITLE
PluginBundle/EventListener/IntegrationSubscriber.php - var_export requires huge amount of memory for Hubspot integration scenario

### ISSUE THREAD

**Issue by leonidr** [mautic/mautic#5199]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | No
| Enhancement? |  No

## Description:
PluginBundle/EventListener/IntegrationSubscriber.php var_export requires huge amount of memory for Hubspot integration
Probably the object supplied to var_export is root of huge object graph spanning entire symphony container

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.10.1
| PHP version |  7.1

### Steps to reproduce:
1. Configure hubspot integration 
2. Create campaign that triggers push to integration for hubspot
3. Run mautic console command mautic:campaigns:trigger 

BTW, when unrolling the file to version without var_export - everything works as expected
 
### Log errors: 

PHP Warning:  var_export does not handle circular references in /opt/bitnami/apps/bahina/htdocs/mau/app/bundles/PluginBundle/EventListener/IntegrationSubscriber.php on line 47

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 3001024512) (tried to allocate 2950696960 bytes) in /opt/bitnami/apps/bahina/htdocs/mau/app/bundles/PluginBundle/EventListener/IntegrationSubscriber.php on line 47

PHP Warning:  proc_open(): fork failed - Cannot allocate memory in /opt/bitnami/apps/bahina/htdocs/mau/vendor/symfony/console/Application.php on line 973

  [Symfony\Component\Debug\Exception\OutOfMemoryException]
  Error: Out of memory (allocated 3001024512) (tried to allocate 2950696960 bytes)

mautic:campaigns:trigger [-i|--campaign-id [CAMPAIGN-ID]] [--scheduled-only] [--negative-only] [-l|--batch-limit [BATCH-LIMIT]] [-m|--max-events [MAX-EVENTS]] [-f|--force] [-t|--timeout TIMEOUT] [-x|--lock_mode LOCK_MODE] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
