### ISSUE TITLE
Feature - Social Media interactions to add points to leads

### ISSUE THREAD

**Issue by alvinbenavides** [mautic/mautic#52]
If there is a known lead with social media info in his/her profile, to be able to add points if the lead Likes or Share a page.

**Comment by RCheesley** [comment]
+1 but also if they interact with your company's social profile?  So, if they favourite, retweet or reply to a tweet, like or reshare a Facebook post, and so forth.  These are all significant engagement events.

**Comment by renegademarketer** [comment]
+1 for this feature request, especially tracking engagement on a company's social media channels, such as replying and retweeting.
