### ISSUE TITLE
Segment DATE by number of days (not just by specific date)

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#5202]
What type of report is this:

| Q  | A
| ---| ---
|| Feature request | 

## Description:
Hi, I noticed that when creating filters in the segmentation for date fields there is only and option to pick a specific date. Why not allow to make the segment dynamic? I want to be able to pick something like DATE LAST OPENED in last 30 DAYS. Understand?

**Comment by omert37** [comment]
AND also BETWEEN X AND Y DAYS

**Comment by escopecz** [comment]
It's not documented, but according to https://github.com/mautic/mautic/pull/1587 this feature should be implemented already. Could you give it a try?
