### ISSUE TITLE
Segmentation Request: "IS ONE OF" COMMA DELIMITED LIST - OPERATOR

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#5206]
What type of report is this:

| Q  | A
| ---| ---
|| Feature request? | 

## Description:
Another feature request for segmentation:
Instead of having to enter in a long list of COUNTRY names, could there be an option to enter in a long list of comma delimited COUNTRY NAMES?
(e.g. COUNTRY "is one of" United States, France, Spain, Italy, Germany)

**Comment by dbhurley** [comment]
At the moment we don't have this as an operator. I'm going to close the issue, but if someone is interested in submitting a PR we can reopen.
