### ISSUE TITLE
Scoring contacts with URLs

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5213]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I have two different ction to score a lead with "visited URL".
Example: 
Visite 1 time this URL =>  https://www.example.com/fr/*   = 1 point
Visite 3 times this URL => https://www.example.com/fr/* . = 5 points

I only won 1 points even if i visited more than 3 times this URL. I should have 6 points

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 

### Steps to reproduce:
1. Go to manage actions
2. Add an action: when contact visits a specific URL: https://www.yoururl.com/* = 1 points
3. Add a second action: when contact visits a specific URL: https://www.yoururl.com/* > page hits: 3times .  = 5 points
4. Visit few times the URL
5. Check the points in the contact

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Okay, If I've added later another action with 2 visits and 2 potins. 
This action wasn't executed. 
Action doesn't count page visit until action is created but from page_hits table history. 
Do you mean add option count page visits until action was created?

**Comment by johbuch** [comment]
@kuzmany 
I could get 4 points this time but I had to visit more than 3 times a page to get the 3 points action (cf screen)
![image](https://user-images.githubusercontent.com/31535432/32717338-994bf06a-c859-11e7-8296-b6b13b847c92.png)

I added both actions (1 visit =1pts and 3 visits = 3pts) before doing the test. Then I went on the website.

**Comment by kuzmany** [comment]
@johbuch What I said that page visits points action count  visits from all page hits history. That means if yorur contact already had 3 visits before, Can't execute in 4th visits action with 3 visit condition. Do you understand? 
Solution is add new option "Until action was created" and action will count visits after date was created.
That means If I create action with 2 visits and 2 points and enable this option, this action should count visits from this created date (not from all page hits history)

**Comment by johbuch** [comment]
@kuzmany the test we ran was with a new contact without any history (the point action was set **before** the visits starts).

So how we proceeded:

1. Create point action for 3 visits with wildcard URL
2. Incognito mode visit 3 pages
3. Notice that the action for 3 pages is not working

For the only one visit it is working, for the 3 visits it is not.

[page_hits (1).csv.txt](https://github.com/mautic/mautic/files/1475068/page_hits.1.csv.txt)
<img width="840" alt="capture d ecran 2017-11-15 a 15 22 41" src="https://user-images.githubusercontent.com/31535432/32841442-9d395de4-ca1a-11e7-8983-88ff42eec870.png">
<img width="1012" alt="capture d ecran 2017-11-15 a 15 20 37" src="https://user-images.githubusercontent.com/31535432/32841443-9d52bb4a-ca1a-11e7-87cf-b863ae2e30cf.png">

**Comment by kuzmany** [comment]
Ok, I'll re-test.

**Comment by kuzmany** [comment]
I just did test and works. 
See my test workflow on video: http://youtu.be/7bu-5-FIii0?hd=1 
I guees you did test on 2.10.1? 
Can you try same test also on Mautic 2.11?

**Comment by kuzmany** [comment]
Just did test on 2.10.1 works.
