### ISSUE TITLE
Contacts API doesn't return stage metadata for contact

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#5214]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | PHP 7.0

### Steps to reproduce:
1. Add stage to Contact
2. create API call $contactsApi->get($contactID)
3. dump result and see stage metadata wasn't loaded (ID, NAME)

![image](https://user-images.githubusercontent.com/462477/32045519-c88304f8-ba40-11e7-821c-0d6642591400.png) 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @escopecz it can be closed :)
