### ISSUE TITLE
Database Problem on 2.11.0 Fresh Install

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#5221]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I can update installations fine to 2.11.0, but when trying to do a fresh install from the release ZIP file, this is what happens:

![Screenshot](https://i.imgur.com/wzR23lf.png)

No errors in Apache log or browser console. The database is populated with tables, but the installer just gets stuck here.

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7

**Comment by nickian** [comment]
Nothing on this? Is anyone else experiencing this on fresh installs?

**Comment by dbhurley** [comment]
Doesn't seem to be a replicated problem. Please update if you continue to experience issues with 2.12 coming soon.
