### ISSUE TITLE
Stored XSS in Company Name

### ISSUE THREAD

**Issue by ProDigySML** [mautic/mautic#5222]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✓
| Feature request? | 
| Enhancement? | 

## Description:
Stored Cross-site scripting in the Company's name. This allows a person to gain arbitrary execution of JS code on anyone who views the Company's name within their browser. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.0

### Steps to reproduce:
1. Create a new company
2. Set the company name to `<img src=x onerror=alert(1)>`
3. Navigate to a place where the company name is reflected and observe an alert box pop up
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

None

**Comment by dbhurley** [comment]
Good catch, fields will need to be sanitized on company.

**Comment by escopecz** [comment]
Already fixed.
