### ISSUE TITLE
Users with restricted permissions cannot create landing pages

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#5225]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
I have an instance set up with a demo user, who has the following permissions on the landing page bundle:

![demo-user-restricted-permissions](https://user-images.githubusercontent.com/2930593/32099671-14face9c-bb09-11e7-9056-60dfd109fe2a.png)

Note specifically the create permission.

When the user logs in, they are not able to create a landing page - the blue flash across the top of the screen indicates something starts, but nothing completes - video explanation here https://youtu.be/AFrowWrIUoA.

As an administrator, I can complete the action as expected.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.0.15

### Steps to reproduce:
1. Create a role with restricted permissions on landing pages
2. Log in and try to create the landing page
 
### Log errors: 

No logs reported in error log

**Comment by RCheesley** [comment]
Further looking into this - if I assign full permissions on the landing page bundle, the user can view other people's landing pages, but still, if they go to edit, they are not able to do so.

**Comment by RCheesley** [comment]
A bit of digging suggests this could possibly related to something to do with dynamic content permissions:

[2017-10-27 15:34:35] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Permission class not found for dynamicContent in permissions classes" at /var/www/html/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php line 128 {"exception":"[object] (InvalidArgumentException(code: 0): Permission class not found for dynamicContent in permissions classes at /var/www/html/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php:128)"} []

**Comment by dongilbert** [comment]
Thanks for the report. Fixed in #5361
