### ISSUE TITLE
17/16 permissions assigned

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#5226]
Seems like a slight miscalculation :)

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Minor bug, when working with permissions there's 17/16 permissions assigned on the contacts bundle:

![mautic-miscalculation](https://user-images.githubusercontent.com/2930593/32099882-0dad50e6-bb0a-11e7-9fab-ebc77fab2183.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.0.15

### Steps to reproduce:
1. assign all available permissions on contacts
2. notice the numbers don't add up ;)

**Comment by RCheesley** [comment]
This persists in 2.15.3 if you select each option individually and if selecting 'full'.  Minor but hopefully easy to fix!

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
