### ISSUE TITLE
Permission on app/console after updating to 2.11.0

### ISSUE THREAD

**Issue by be-mohand** [mautic/mautic#5228]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
I've used the update funct. from the back-office to update to 2.11.0 version.

Everything worked fine, but my cron jobs were not working anymore. I had a permission issue on app/console file.

My solution was to change the chmod:
```
chmod +x app/console
```
It could be interesting to execute this command after the update.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.1

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

```
[~/mautic] > app/console mautic:import 2>&1 >> /tmp/mautic/mautic.import.txt
-bash: app/console: Permission denied
```

**Comment by dbhurley** [comment]
Not something to be done code-side. Due to permissions and ownership claimed during update.

**Comment by MichaelGreco** [comment]
I had to add ->   PubkeyAcceptedKeyTypes=+ssh-dss
