### ISSUE TITLE
An error occurred while attempting to add default data: MysqlPlatform::getDropIndexSQL() expects $table parameter to be string or \Doctrine\DBAL\Schema\Table.

### ISSUE THREAD

**Issue by lvnilesh** [mautic/mautic#5230]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
The more details the better...
An error occurred while attempting to add default data: MysqlPlatform::getDropIndexSQL() expects $table parameter to be string or \Doctrine\DBAL\Schema\Table.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.1

### Steps to reproduce:
1. installer/step/1
2. See modal pop up
 
### Log errors: 

An error occurred while attempting to add default data: MysqlPlatform::getDropIndexSQL() expects $table parameter to be string or \Doctrine\DBAL\Schema\Table.

**Comment by dbhurley** [comment]
Is this still an issue in 2.12?
