### ISSUE TITLE
Virality creation - integrate it or build it?

### ISSUE THREAD

**Issue by namankumar** [mautic/mautic#5238]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | | 
| Feature request? |x | 
| Enhancement? | | 

## Description:
Tools like Buffer allow you to schedule and post to social media. They also give analytics about the users reached. I propose to build a plugin that either integrates with Buffer and imports analytics into mautic OR to build our own auto-posting scheduler and integrate with each social platform's API to have the analytics.

Why? 

If we can overlay social media impressions with site visits, you've got a very powerful tool that you can use to create virality again and again. You know exactly which piece of content brought contact to your site. Bonus points - based on this, you can assign them points and target them with the next relevant content.

Future benefit of building your own auto-posting scheduler - it allows you to track how your link spreads through social media by using utm codes etc.

Much as I'd love to, I can't commit the time to build this right now.

**Comment by dbhurley** [comment]
At the moment this is not a feature to be implemented in Mautic, a better solution would be plugin integration with existing tools...Unless someone wants to contribute a pull request including this functionality. 😄
