### ISSUE TITLE
Dynamic Content - Re-usable footer

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#5240]
What type of report is this:

| Q  | A
| ---| --- 
|| Feature request? | 

## Description:
If I create, for example a static footer as a Dynamic Content component, how do I display it in my email?
I can't seem to find a solution to this.

It would be good to have this option because my footers change on a regular basis and it would be good to be able to change them in one place and have that single change ripple across all of my templates.

**Comment by dbhurley** [comment]
If I understand correctly Dynamic Content will do this. Questions regarding the usage or implementation should be stuck in the forums or Slack channels.

**Comment by omert37** [comment]
What I'm looking for is a convenient way to display header/footer content for Emails. I want a system to pre-configure these headers/footers and be able to update them and have the change ripple across all of the email templates which make use of these headers/footers. I currently don't see a solution for this on MAUTIC.
