### ISSUE TITLE
Campaign with form field radio condition doesn't trigger

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#5241]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | 
| Enhancement? | 

## Description:
Make a campaign form Velo
add in this form a radio box with three values (velo1, velo2, velo 3)
and the e-mail
Make 3 emails velo 1, velo 2, velo 3
Make a campaign with the form Velo as start
Make 3 conditions with a form fiel value
<img width="620" alt="capture d ecran 2017-10-29 13 06 03" src="https://user-images.githubusercontent.com/20974155/32143473-fadb3216-bca9-11e7-84fa-71d8adfecb4d.png">

<img width="868" alt="capture d ecran 2017-10-29 13 07 21" src="https://user-images.githubusercontent.com/20974155/32143486-3d73b404-bcaa-11e7-88e6-969590dabf2a.png">

## If a bug:
Just populate the forms  no mails are sends 
The conditions in the form have a bug

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.0.11

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
