### ISSUE TITLE
Campaign with Contact field value

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#5242]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
1) Make a custom field with a select multiple  Type
<img width="1045" alt="capture d ecran 2017-10-29 13 19 48" src="https://user-images.githubusercontent.com/20974155/32143589-0286ba56-bcac-11e7-8a26-df0d1f82149d.png">
2) Make a campaign with a trigger on a contactfield 
<img width="656" alt="capture d ecran 2017-10-29 13 21 55" src="https://user-images.githubusercontent.com/20974155/32143601-2abe10c8-bcac-11e7-9e1a-d98a52935df2.png">
3) make a campaign with a different e-mail for each case
<img width="805" alt="capture d ecran 2017-10-29 13 23 02" src="https://user-images.githubusercontent.com/20974155/32143609-50d6d416-bcac-11e7-8754-944ae12d156e.png">

## If a bug:

The conditions stay to false in the campaign

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.0.11

### Steps to reproduce:
1. as describe
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
