### ISSUE TITLE
On import, keeps creating new contact even when email already exists

### ISSUE THREAD

**Issue by namankumar** [mautic/mautic#5245]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x |
| Feature request? | |
| Enhancement? | |

## Description:
I made a CSV for about 480 contacts on my local machine, and then I imported them into mautic via the Import drop down on the Contacts page. 

Instead of merging this with existing contacts, Mautic is creating new ones! All 480 are already contacts in my installation.

I don't understand why this is happening? In custom field, Email and Company Emails are the only fields marked as Unique Identifier. So shouldn't Mautic merge them? 

Please help.

## If a bug:
1. upload a csv file with contacts that already exist in mautic. 

| Q   | A
| --- | ---
| Mautic version | 2.11

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by namankumar** [comment]
@escopecz @kuzmany @dongilbert - please help. This is an urgent issue on my installation. 
Please help me debug. I am trying to update bounced emails via a CSV and mautic keeps adding new contacts instead of updating with existing ones.

I am also on slack as @naman.

**Comment by robwent** [comment]
Other issue: https://github.com/mautic/mautic/issues/5149
