### ISSUE TITLE
Allow campaign to run for new members of a segment only

### ISSUE THREAD

**Issue by brandner** [mautic/mautic#5246]
What type of report is this:

| Q  | A
| ---| ---
| Feature request | 

## Description:
Contacts may be placed into segments either from segment forms or through advanced filters. Campaigns and emails can target these segments. When a campaign is created and associated with a segment, it immediately runs for all contacts already in the segment, and is triggered for any new contacts that are added to that segment.

We would like to suggest that a method be added to allow campaigns to ONLY execute for new contacts. One way might be to add a checkbox on the 'New Campaign - Contact Source' modal that reads 'Ignore contacts that are already in the segment, trigger for new segment members only'.

### Steps to reproduce:
The current workaround for this is:
1. Create a new campaign for the target segment that adds a tag to all current segment members. Select the segment as the contact source and use an 'Action' step to add the tag.
2. Wait until the campaign runs. After it is completed, disable it.
3. Create a new campaign for the target segment. After selecting the contact source, add a 'Condition' step that looks for the tag mentioned above. If the tag does NOT exist, continue with the other campaign actions.
 
The proposed workflow would be:
1. Create a new campaign for the target segment. After selecting the contact source, check the 'new members' checkbox. This would cause the campaign to be executed only for members newly added to the segment, not for contacts currently in the segment.

![image](https://user-images.githubusercontent.com/533019/32181871-a9675e88-bd52-11e7-8cc9-0f124c3b15c4.png)

**Comment by calevans** [comment]
While it is not a answer to your question of whether it can be implemented as a feature, this can in effect  be accomplished in the existing system.

1: Export all members of a segment
2: Re-import them (just the email address is fine) and add the tag ALREADY_SEEN_CAMPAIGN_X
3: When setting up the campaign, add a condition that ignores anyone with the tag ALREADY_SEEN_CAMPAIGN_X
4: The last step in the campaign should be to add the tag ALREADY_SEEN_CAMPAIGN_X

Cheers! 😄
=C=

**Comment by brandner** [comment]
Thanks @calevans - that's similar what I indicated in the 'steps to reproduce' workaround notes. Do you prefer the export/import compared to just running a campaign to set the tags?

**Comment by calevans** [comment]
Depends. If it's a one-off then yes, I do the import/export. However, if it's going to be an ongoing issue, automating it with a Campaign would be easier. Also, would depend on number of contacts. My lists are all less than 10k ATM so it's not difficult for me to do this. If one of them were 100k, the campaign would be the easiest way all around.

Cheers!
=C=

**Comment by kuzmany** [comment]
This condition should resolve it. 
You can make condition for current or another campaigns based on date added to campaign https://github.com/mautic/mautic/pull/4800

**Comment by Tabish911** [comment]
@brandner thank you so much mate, I was really pissed off searching it everywhere
