### ISSUE TITLE
UI: tooltips for email stats being cut off

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#5247]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

![image](https://user-images.githubusercontent.com/742579/32186242-caf1be48-bd5e-11e7-90ce-3f50a83f6412.png)

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
