### ISSUE TITLE
Campaign ID as dynamic TOKEN

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#5250]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Yes|

## Description:
Hi, it would be very helpful if the campaign/or email ID was available as a dynamic token which I could place in the HTML content of an email.

**Comment by dbhurley** [comment]
Not sure the purpose for this token? I'll re-open if you can make a good use case :wink:

**Comment by omert37** [comment]
I'm looking for something like the Dynamic Content solution but more like a convenient way to display header/footer content for Emails. I'm looking for a system to pre-configure header/footer HTML content and easily update them when needed and have the change ripple across all of my templates which use these headers/footers. I currently don't see that in MAUTIC.

**Comment by tompon** [comment]
More similar dynamic tokens would be needed in Mautic, not even Campaign-id
