### ISSUE TITLE
Pipedrive push returns error "Name must be given"

### ISSUE THREAD

**Issue by sineau** [mautic/mautic#5254]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | NO
| Enhancement? | NO

## Description:
I set up my Pipedrive integration as described in docs. I have a point trigger to push contacts to Pipedrive. Also I set up the webhook. When I create a new contact in Pipedrive, it will show up in Mautic. However Mautic contacts won't show up in Pipedrive when they reach that specific point.
When I try `mautic:integration:pipedrive:push`, following error shows up Mautic's log:
```mautic.ERROR: INTEGRATION ERROR: Pipedrive - Client error: `POST https://{ommited}.pipedrive.com/v1/persons?api_token={ommited}` resulted in a `400 Bad Request` response: {"success":false,"error":"Name must be given.","error_info":"Please check developers.pipedrive.com for more information  (truncated...)  [] []```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.0
| PHP version | 7.0.22

### Steps to reproduce:
1. Setup Pipedrive integration, with only Email, First Name, Last Name (I disabled company for now).
2. call `app/console mautic:integration:pipedrive:push` on ssh terminal.
 
### Log errors: 
```mautic.ERROR: INTEGRATION ERROR: Pipedrive - Client error: `POST https://{ommited}.pipedrive.com/v1/persons?api_token={ommited}` resulted in a `400 Bad Request` response: {"success":false,"error":"Name must be given.","error_info":"Please check developers.pipedrive.com for more information  (truncated...)  [] []```

I checked mautic.net with the same settings and it works perfectly. So there might be something wrong with my installation. Unfortunately I can't find what the issue is.

**Comment by dbhurley** [comment]
Make sure you have the necessary API with Pipedrive setup. Cannot replicate the issue.

**Comment by AlbanL74fr** [comment]
I have the same issue, have you found out what went wrong?

**Comment by stollz** [comment]
same issue here. Name field is mapped in both contact and company

**Comment by npracht** [comment]
Hello guys, do you have the latest version with huge Pipedrive integration improvements?

**Comment by stollz** [comment]
Hi Norman, I just updated Mautic to 2.14.1.
and used the builtin Pipedrive Plugin which comes with MauticCRMBundle I suppose

**Comment by stollz** [comment]
I solved the issue:
contact fields first_name and last_name must be filled, I think because the plugins needs those fields to construct the "name" field of Pipedrive.
