### ISSUE TITLE
Multi-touch, last touch and first touch attribution reports don't generate values

### ISSUE THREAD

**Issue by sarahwernik** [mautic/mautic#5256]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When I generate a multi, last or first touch attribution report, no matter what columns I pull into the report, no data generates. I'm not sure how this report is supposed to work since I've never been able to show data.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Yes
| PHP version | 

### Steps to reproduce:
1. Create a new report
2. Select the data source of either "multi-touch", "first touch" or "last touch"
3. Add columns - contact ID, campaign, campaign ID, attribution, etc.
4. Save and close
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
I think we can close this one as we deteremined it was an education issue on how attribution works in Mautic.
