### ISSUE TITLE
void mail sent

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#526]
I created one mail with the builder. 

1º The send test option doesn't work, (no email arrives)

2º I go to the lead with my email address and I send the mail manually (the new feature). Now the email arrives to me but it's empty:
If I go to the "Preview/Online URL" before or after I send the email. I see the correct email.
If I go to the "Lead Events" (of my email address) and I try to see the email sent, the email I get is empty.
I had configured the queue and the mail before it went out (in app/spool/default it's not empty. The mail has all the text) 
In the mail client the email is absolutely empty (the source code doesn't have any word of the original text)
At /app/logs doesn't have new errors

I need to send this campaign tomorrow. Any ideas?

**Comment by alanhartless** [comment]
Just to confirm that I'm following the issue correctly:

You have Mautic configured to queue the emails.  Before you run the CLI command/cron job, the file contains the body of the message.  But, once sent, it arrives empty?

What mail transport are you using? Mandrill, PHP mail, smtp, etc?

We'll get to the bottom of this before your campaign.

**Comment by alanhartless** [comment]
@miguelpascual Also, can you check your server's log (not Mautic's; can be in different places depending on the host) for any PHP warnings or notices?

And are you using tokens, if so, which ones?

**Comment by miguelpascual** [comment]
You have Mautic configured to queue the emails. Before you run the CLI command/cron job, the file contains the body of the message. But, once sent, it arrives empty?
Yes

What mail transport are you using? Mandrill, PHP mail, smtp, etc?
PHP mail 

I search logs but i don't find any related error.

The only token I use is the unsusbscribe (I'll try to send without it)

**Comment by alanhartless** [comment]
Are you using a theme?

**Comment by miguelpascual** [comment]
Coffe theme

Now I clonned the email 
I add the test list and I sent it (whitout unsuscribe)

Now I had in the spool directory one source code without the builder content (but it has the text only message) :S It is strange because I still has open the old .message with builder content...

The .message with builder content:
![image](https://cloud.githubusercontent.com/assets/10166840/8061808/e7ca9de8-0ecc-11e5-8df8-88d8830f1b26.png)

The .message without

![image](https://cloud.githubusercontent.com/assets/10166840/8061835/0526ff1c-0ecd-11e5-8f80-346d2407d546.png)

**Comment by miguelpascual** [comment]
I created a new mail (list). I use coffe them to launch the Builder. I add some text in builder (and unsubscribe token). I have a list with 4 leads. I add these list to the new email. I sent the mail.

In spool I has 4 .message. And now I haven't content in the mail (from email builder) :Confused:

![image](https://cloud.githubusercontent.com/assets/10166840/8062034/f4e867ca-0ecd-11e5-93b3-c783c317f021.png)

**Comment by alanhartless** [comment]
I think I've found the issue.  I will post back here in a few minutes with a package and instructions for you to test if you're wiling.

**Comment by wderuijter** [comment]
Think I've got the same issue. Willing to test.

**Comment by miguelpascual** [comment]
I going to test tomorrow. Thx for all!!

**Comment by alanhartless** [comment]
@wderuijter Are you still around? If so, can you jump on Slack?

**Comment by wderuijter** [comment]
@alanhartless yeah. 1 sec. Things seem to have changed a bit since I last logged in the mautic slack channel.

**Comment by miguelpascual** [comment]
Now works fine!

Thx a lot!!!

**Comment by alanhartless** [comment]
Fixed 1.1.2.

**Comment by bluekheng** [comment]
Hi there, we are experiencing the same issue. Email arrives if you test the mail connection and by going to a lead then sending the email.  However, if we use the send example button in the email campaign, email does not arrive. 

We are using Mautic 1.2.0.
