### ISSUE TITLE
Missing break condition for switch case

### ISSUE THREAD

**Issue by mandadimuralidharreddy** [mautic/mautic#5269]
https://github.com/mautic/mautic/blob/584b242454cc54427b3121dfcc5addc392ee7f9d/app/bundles/CoreBundle/Entity/CommonRepository.php#L1618

**Comment by escopecz** [comment]
Could you please provide some info around it? Switch case doesn't have to end with break. Do you experience some issues around this code?

**Comment by mandadimuralidharreddy** [comment]
In our case both default  and condition are getting executed. And it causing unexpected behaviour in app.

**Comment by dbhurley** [comment]
Improper test reporting. No way to replicate. Closing this issue unless proper report filled out.
