### ISSUE TITLE
conditional logic in campaign workflow

### ISSUE THREAD

**Issue by balanj** [mautic/mautic#527]
Would be nice if it is possible to set up a workflow with multiple forms before deciding on an action.  For example: When the user submits form1, I want to present him with form2 and so on until a certain condition is met say for instance until option B in the form2 is selected after which he should be led to form4 rather than form3. I hope the idea is clear.

Basically, it should be possible to implement workflows using Conditional logic

**Comment by RCheesley** [comment]
I think a more useful feature might be conditional logic of fields within a form, rather than form to form.  Perhaps that would allow you to do what you want, but within one form instead of multiple?  What's the use case?

**Comment by balanj** [comment]
Conditional logic within form is good, but what I wanted here is conditional logic to show different forms based on the user's answer for previous forms.
Consider if i want to run a campaign (in financial domain) in which my end goal is to present the customer with a more suitable product (like an insurance product or a mortgage product), I would need to walk him through a series of questions. So having conditional logic here would be really useful.
I hope it is atleast a little more clear now.

**Comment by dobesv** [comment]
I think there are a few different areas where conditionals can be useful.

Did this person buy from us before?  Did they previously attend a webinar?  Do they have > N points? Are they already on our list?

The places where we want conditionals - when someone clicks a link or submits a form, we want to select a landing/thank-you page conditionally.

Also when sending emails we want to select emails or even a whole sub-branch of the funnel based on conditions.

For example, if we have a double opt-in system in place, it would be create to have a condition where if they are already subscribed we just drop them on the lead magnet without making them opt-in again.

**Comment by that0n3guy** [comment]
Conditionals should also be able to compare/check lead fields.  Examples:

* is lead a female?
* is birthday field not empty?
* is lead "type" not "client"
* etc...

**Comment by dbhurley** [comment]
Fixed in 1.2.1
