### ISSUE TITLE
Cant update mautic from 2.9.2 to 2.11.0

### ISSUE THREAD

**Issue by ServicedCloud** [mautic/mautic#5270]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
We are using self-hosted mautic for our website. Upon trial testing from 2.9.2 to 2.11.0 via browser update, it stops/hangs at "clearing application cache". Please note that we cleared cached folder before updating. We are hoping that in the next release, it would be fixed and then we can update to the latest version. Can we ask when is the possible release of 2.11.1 ?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | 5.6.31

### Steps to reproduce:
1. Updating mautic via browser
2. Mautic update stops at "clearing application cache"

**Comment by escopecz** [comment]
Please use the recommended way to upgrade Mautic. Even more so if you skip some versions and there is a lot to upgrade. https://www.mautic.org/community/index.php/8695-2-11-0-released

Also provide logs next time. See https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by dorseycoe** [comment]
Where can I leave feedback about Mautic?
Your link in the comment, "https://www.mautic.org/community/index.php/8695-2-11-0-released"
no longer works (whoops!). The update now button in my install doesn't work (hangs, never finishes), and the "please visit this announcement" link in the update drop down goes to a dead link too.

Please provide a GOOD link to the recommended way to upgrade Mautic!

thanks

![mautic2](https://user-images.githubusercontent.com/11246738/37854204-7f2edcc6-2eaf-11e8-982e-098d2c44b02e.jpg)

**Comment by escopecz** [comment]
The link in the notification should go to https://github.com/mautic/mautic/releases/tag/2.12.2 which loads correctly for me. Where does it take you?

The new release announcements with suggested update process are here: https://www.mautic.org/forums/forum/announcements/

**Comment by dorseycoe** [comment]
Moot now, I tried the command line upgrade as none of the other upgrade processes worked, and it broke my install (test install so no big deal), but we need a reliable solution - we’ll pay for a commercial product, just to have it work correctly.

I’ll check back with Mautic in a couple of versions (years?)

Best regards,

Dorsey Coe
 <https://mozaictech.com/>Lead Developer
Mozaic Technology
300 Main Street Suite 201
Grand Junction CO 81501
Sales: 970-462-7770
“The online marketing solution
for Agencies, Designers, and you."
 <https://mozaictech.com/>

**Comment by escopecz** [comment]
It depends on what was the reason. If it was for example file system permission then no amount of years waiting will help

**Comment by dorseycoe** [comment]
We install Mautic through Softaculous, through cPanel on a centos box. We checked everything per your “troubleshooting guide” including permissions, php versions, etc.

But your right, thinking your potential user is the problem instead of your broken links and scripts then you’re right, no amount of waiting will solve it

Good day, 


Dorsey Coe
 <https://mozaictech.com/>Lead Developer
Mozaic Technology
300 Main Street Suite 201
Grand Junction CO 81501
Sales: 970-462-7770
“The online marketing solution
for Agencies, Designers, and you."
 <https://mozaictech.com/>

**Comment by escopecz** [comment]
I've sent you new links and asked where the broken link from the notification lead to. It works for me. If you won't help me debug your issues I won't be able to solve them. 

In the troubleshooting guide is described that the error messages are logged and that you should provide those error messages in your issue description. Again, I can't help only based on "it broke my install". It could be thousands of reasons without the error message.

**Comment by dorseycoe** [comment]
It’s all good John, we blew away the install and started fresh from softaculous.

We are on 2.12.2 now.

If I have any trouble I’ll follow proper protocol and channels.

Best regards,

Dorsey Coe
 <https://mozaictech.com/>Lead Developer
Mozaic Technology
300 Main Street Suite 201
Grand Junction CO 81501
Sales: 970-462-7770
“The online marketing solution
for Agencies, Designers, and you."
 <https://mozaictech.com/>
