### ISSUE TITLE
Campaign preview does not show execution time delays

### ISSUE THREAD

**Issue by benznarczyk** [mautic/mautic#5272]
What type of report is this: bug/UI update

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Yes

## Description:
In the new campaign preview (2.11) the campaign action execution time delays are not shown. Picture 1 is from the campaign builder and picture 2 is from the campaign preview.
![pic 1](https://user-images.githubusercontent.com/18532961/32336188-04962de2-bfc5-11e7-8ce8-528c086d8ecd.png)
![pic 2](https://user-images.githubusercontent.com/18532961/32336194-07a1b9de-bfc5-11e7-860b-a6c43c897455.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Create campaign
2. Add an action with an execution delay
3. Save and Close
4. Check the campaign preview, no delays shown in the image
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
