### ISSUE TITLE
Mautic graphs started to show the info date like it was one day before 

### ISSUE THREAD

**Issue by kauelinden** [mautic/mautic#5274]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:
Hello,

First: Mautic is a fantastic tool and you guys are doing an amazing work.

I´m running Mautic 2.11 Since we had last timezone change in Brazil (we call time of summer - with consist in advance +1 hour) Mautic graphs started to show the info date like it was one day before.

For example today is 25/10 but Mautic understand that today is 24/10

![image](https://user-images.githubusercontent.com/25824537/32342814-ba5850c4-bfe8-11e7-990f-50b10d1b62c8.png)

If I check php.info  I can see that PHP understand correctly what day is today.
https://mkt.hostnet.com.br/info.php 

I already tried to clear cache, reboot system and change and then re change the timezone.

Others Mautic users here from brazil, running on others servers are reporting same issue.

Could you have any advice or clue about how to fix that?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. open mautic
2. see the dashboad graph
 
### Log errors: 

No erros on logs

**Comment by dbhurley** [comment]
What time does your server maintain? Is it possible it's related to server UTC?
