### ISSUE TITLE
bug: tracker links send to home 

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#528]
Hi 

I have a link in the email and when I click the link inside the email it sends me to mautic but the redirection doesn't take me to the correct page. It sends me to the home page of the web site.

Example: I add this link (http://www.mydomain.com/somepath/page.html) In the email and it sends me to mautic and redirects me to http://www.mydomain.com without the path.

![image](https://cloud.githubusercontent.com/assets/10166840/8068912/6b74c798-0ef7-11e5-83ae-fd03cc28f87d.png)

Tracker link: http://gui.ww1.es/r/0cb22812dc4084c088d9baca1?ct=YTozOntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6MjE7fXM6NToiZW1haWwiO2k6MjE7czo0OiJsZWFkIjtzOjE6IjIiO30%3Dpastores-electricos/pastores-electricos-red-electrica/pastores-electricos-gallinas.html

If you click the link you arrive to the home page, not to the page.

![image](https://cloud.githubusercontent.com/assets/10166840/8069001/de43f726-0ef7-11e5-9042-2db13f53d09f.png)

**Comment by alanhartless** [comment]
@miguelpascual 
Found the issue.  I'm assuming you have http://www.mydomain.com somewhere earlier in the email resulting in the URL with the path being immaturely replaced. Can you test #530? Just overwrite  app/bundles/PageBundle/EventListener/BuilderSubscriber.php with  https://raw.githubusercontent.com/alanhartless/mautic/link-order-fix/app/bundles/PageBundle/EventListener/BuilderSubscriber.php

**Comment by miguelpascual** [comment]
Yes, the first link in the email is to the root domain. 

I'll try to replace the BuilderSubscriber.php and I'll tell the result

**Comment by miguelpascual** [comment]
https://www.youtube.com/watch?v=LdrvIOcAB-A

**Comment by miguelpascual** [comment]
With the Update the BuilderSubscriber it works already

**Comment by miguelpascual** [comment]
Perfect

Now it works.

thank you!
