### ISSUE TITLE
Imports create Duplicates when Email is publicly updatable

### ISSUE THREAD

**Issue by MaxWebmecanik** [mautic/mautic#5281]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✓
| Feature request? | 
| Enhancement? | 

## Description:

Imports create Duplicates when Email is publicly updatable

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 5.6

### Steps to reproduce:
1. Make the email field publicly updatable
2. Import a CSV file as simple as the following:
    ```csv
    email
    test@example.com
    ```
3. Import that same file again
4. You should have two identical leads
 
### Log errors: 

> None...

**Comment by mghardy** [comment]
Likely same issue referenced here: https://github.com/mautic/mautic/issues/5149

**Comment by escopecz** [comment]
I'll close this issue in favor of https://github.com/mautic/mautic/issues/5149. Thanks guys for taking care of it!
