### ISSUE TITLE
Tracking hash in unsubscribe email address.

### ISSUE THREAD

**Issue by migrivas** [mautic/mautic#5290]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | x
| Enhancement? | 

## Description:
It would be great to also add the tracking_hash into the unsubscribe email address.
Sometimes people are subscribed using an email alias and not their main email address, and when they unsubscribe via email (sometimes using directly the email client) the email is not recognized by the system.

So the idea would be:

- add the tracking hash in the email address (xxxx+unsubscribe_hash@yourdomain) in the list-unsubscribe header.
_/app/bundles/EmailBundle/EventListener/EmailSubscriber.php_

- and process it (same process used for bounces) on unsubscribe event if the from address is not recognized.
_/app/bundles/EmailBundle/Helper/MessageHelper.php_

What do you think ? 😄

**Comment by migrivas** [comment]
Actually the system seems ready to process the hash. So you only would have to add it to the list-unsubscribe header, modifying app/bundles/EmailBundle/EventListener/EmailSubscriber.php

```
      public function onEmailSend(Events\EmailSendEvent $event)
      {
        $helper = $event->getHelper();

        if ($helper && $unsubscribeEmail = $helper->generateUnsubscribeEmail()) {
            $headers          = $event->getTextHeaders();
            $existing         = (isset($headers['List-Unsubscribe'])) ? $headers['List-Unsubscribe'] : '';

          /* Added by migrivas*/
          if ($helper->getIdHash() !== null) { $unsubscribeEmail = str_replace("+unsubscribe", "+unsubscribe_".$helper->getIdHash(), $unsubscribeEmail); }
          $unsubscribeEmail = $unsubscribeEmail . "?subject=Unsubscribe";
          /* END: Added by migrivas */

            $unsubscribeEmail = "<mailto:$unsubscribeEmail>";
            $updatedHeader    = ($existing) ? $unsubscribeEmail.', '.$existing : $unsubscribeEmail;

            $event->addTextHeader('List-Unsubscribe', $updatedHeader);
        }
      }
```

**Comment by npracht** [comment]
Hi @migrivas would you propose your feature under PR ?

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
