### ISSUE TITLE
Wildcard URL + Total time spent point action: exact URL instead of Wildcard used for counting TTS

### ISSUE THREAD

**Issue by micschk** [mautic/mautic#5295]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y

## Description:
When a point action is set up with a wildcard URL + Total time spent, the total time spent is calculated based on the current exact URL instead of all pagehits within the wildcard URL.

Problem is caused by using the (current request) URL from ```$eventDetails->getUrl()``` instead of the (wildcard) URL from ```$action['properties']['page_url']``` in ```Mautic\PageBundle\Helper\PointActionHelper::validateUrlHit()```

```php
    public static function validateUrlHit($factory, $eventDetails, $action)
    {
        // ...
        $url          = $eventDetails->getUrl();
        $limitToUrl   = html_entity_decode(trim($action['properties']['page_url']));
        // ...
        // Currently: 
        $urlWithSqlWC  = str_replace('*', '%', $url);
        // Should be:
        $urlWithSqlWC  = str_replace('*', '%', $limitToUrl);

        // ... so the below test (and others) use the correct urlWithSqlWC
        if ($action['properties']['accumulative_time']) {
            // ...
            if (isset($hitStats['sum'])) {
                if ($action['properties']['accumulative_time'] <= $hitStats['sum']) {
                    $changePoints['accumulative_time'] = true;
                } else {
                    $changePoints['accumulative_time'] = false;
                }
            } else {
                $changePoints['accumulative_time'] = false;
            }
        }

        // ...
```

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0

### Steps to reproduce:
1. Create a willdcard URL point action, eg 
    - http://site.tld/section/*
    - Page hits: 3
    - Total Time Spent: 2 minutes
2. Visit five subpages of the (wildcard) site-section (eg section/page-1, section/page-2, etc) over the course of more than 2 minutes: the point action is not triggered
3. Visit the same page 3 times over the course of more than 2 minutes: the point action is triggered

**Comment by dbhurley** [comment]
Excellent catch. Thank you @micschk
