### ISSUE TITLE
form reset custom field with value per default

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5297]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Submitting a form reset custom field of a contact with value per default

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 

### Steps to reproduce:
1. Create custom field "text" type and fill a default value
2. Create a contact and fill this new custom field with a value (not the default one)
3. Create a form (but do not add this new custom field in the form). For example email and lastname only
4. Submit the form
5. Check the contact 
6. The new value of this custom field above has been updating with the default value
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Just tested.
I think It works properly.
Default value is default for new contacts.
If you send form and new contact is created, then default values are sets. 
That's natural behaviour for me.

**Comment by npracht** [comment]
Yes but create first a contact with the not default value.
Submit the form with the same ID (email), and notice that the default value erase the set value !

**Comment by kuzmany** [comment]
Uh okay yes, this is another issue with empty/default value lead if update it.
I will look on it.

**Comment by npracht** [comment]
@kuzmany you tried on which version ?
Because we can reproduce that again on 2.10.1 on our servers but obviously not on 2.11 on localhost.

**Comment by kuzmany** [comment]
Last staging:
I did test but nothing hapend
Maybe this https://github.com/mautic/mautic/pull/5259 could  affect it? Are you using this PR on your Mautic?

My reproduce tests:
- create form with email field
- send form with kuzmany+custom2@domain.com 
- new contact was created with custom field and default value
- I remove default value in contact profile
- send form again kuzmany+custom2@domain.com
- custom lead field still empty (no default value on contact edit)

**Comment by npracht** [comment]
We already have in it on our staging... :(

**Comment by npracht** [comment]
So you mean the fact that we cherrypicked it maybe cause a problem ?

**Comment by kuzmany** [comment]
Sorry I am confused?  That steps above works for you or not?

**Comment by npracht** [comment]
With the PR on 2.10.1 we have the issue

Envoyé de mon iPhone

**Comment by kuzmany** [comment]
Ok. I will test it.

**Comment by kuzmany** [comment]
Tested and confirmed on 2.11 also.
Strange behaviour. I am gonna fixed it.

**Comment by kuzmany** [comment]
But bug is not related to https://github.com/mautic/mautic/pull/5259

**Comment by kuzmany** [comment]
This is steps to reproduce:
1. Create custom field with custom default value
2. Create contact in Mautic (quick add or regular add) and modify custom fielddefault value
3. Create form without custom field value (email  field for example)  and send form with same email like your created contact above
.4. Custom field  value was change to default even you edit it in step 2
5. Repeat again: modify custom field  on contat edit and send form again
6. Now custom field wasn't  changed do default value and works 

Strange

**Comment by kuzmany** [comment]
Please try test: https://github.com/mautic/mautic/pull/5380
