### ISSUE TITLE
Feature suggestion: split testing forms

### ISSUE THREAD

**Issue by nateritter** [mautic/mautic#53]
Split testing pages is great, but since you're giving the ability to add forms into pre-implemented pages dynamically, it would be great if we could split test the forms themselves too.

The workaround suggested by creating two landing pages and including a different form on each wouldn't work because the page is already out there, in a system.

> Would you want to test different fields inputs, the field labels, a mix of field labels and non-input type fields?

Of course, yes to all of those. :)  It might be easiest and best to just let a user create two forms and assign them to a test, which also gives us the ability to deal with A/B/C/etc tests.  That way you don't have to track much other than that final action(s) as it really just comes down to that.  However, it may make multivariate split tests a little harder in the future, if that's on the roadmap.

> Would the two forms feed into the same table for results (which means the fields themselves couldn't be changed) or would having the results going into two different locations be okay?

I guess that would be up to the person (so both would be possible).  I don't see why they would be forced to go to different places.  My personal preference is they go to the same place, and I can't see why someone might want them to go to different places, but I suppose it's possible.

**Comment by sherwood7vid** [comment]
+1
