### ISSUE TITLE
Type error: must be an instance of DateTime, string given

### ISSUE THREAD

**Issue by lvnilesh** [mautic/mautic#5305]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  yes
| Feature request? | 
| Enhancement? | 

## Description:

Social monitoring seems to generate type error

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version |  7

### Steps to reproduce:

    php /var/www/html/app/console mautic:social:monitoring
 
### Log errors: 

Executing Monitor Item 1
Creating new lead

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to JMS\Serializer\Handler\DateHandler::serializeDateTime() must be an instance of DateTime, string given

mautic:social:monitoring [--mid [MID]] [--batch-size BATCH-SIZE] [--query-count [QUERY-COUNT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Comment by drptiago** [comment]
I have the same problem in Mautic 3.02

mautic.NOTICE: 

Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to JMS\Serializer\Handler\DateHandler::serializeDateTime() must be an instance of DateTime, string given, called in /var/www/html/mautic/vendor/jms/serializer/src/GraphNavigator/SerializationGraphNavigator.php on line 197 (uncaught exception) at /var/www/html/mautic/vendor/jms/serializer/src/Handler/DateHandler.php line 95 while running console command `mautic:social:monitoring`
