### ISSUE TITLE
Feature Request: Points Action based on Email Clicks

### ISSUE THREAD

**Issue by khaoua** [mautic/mautic#5308]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | yes
| Enhancement? | 

## Description:
Points actions regarding emails are only based on mail read, and mail sent (mail sent for me is non sense as we hope at least that the mail has been sent, which is not a basis of point action for emails)

Workaround today is to link specific landing pages to those links (or website pages for multipage website). This allow to add points for the visit of those page which are in fact the "real clicks" of the emails. But hey... We need to decrease data maintenance, and track properly mail clicks based on mails, as the behavior of the visitor/reader is totally different when this click comes from an email than from a direct access to website page.

It is a "must to have" and with all those upgrades, it would save time to analyse if that clicks to the specific link comes from a direct access, or straight after the email read so that it generate point based on this visitor/reader behavior

## If a bug:

| Q   | A
| --- | ---
| Mautic version | next updgrade after 2.11
| PHP version | 

### Steps to reproduce:
1. email with link sent and red
2. points action creation on email click
3. points added to lead profile
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Wouldn't an email "click" be registered as a "page hit" and therefore be something you could currently assign a point value to?

**Comment by khaoua** [comment]
sorry for the delay, somehow, this didn't show up directly in my mailbox but in spam. To answer your question, I think like in other tools, direct mail cliks should be tracked differently to have an instantly point added to this basis; In my opinion, the process you suggest would make a confusion between page hit and email link hit, which is totally different in the result as an action to track from a visitor/prospect. How to differential a same link url from an email link, or a page visit, or same link used elsewhere?

Is there a technical way to make it?

**Comment by imihandstand** [comment]
Any updates on this? It would be really useful - the "getting points for email-opens" is useless, as for example Gmail downloads the tracking-image so all Emails sent to Gmail are marked immediately after sending as "opened".

**Comment by vettloffah** [comment]
I vote for this feature as well. Add link click as action we can track for points.

**Comment by backstageel** [comment]
Voting for this feature too
