### ISSUE TITLE
editing with builder: token unsubscribe do unexpeted results

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#531]
Hi 

Sorry but I found another bug :D

1º I think you prefer me to open a new issue for each one (if not, tell me)

The bug:
I have a correct email. And I save it. After saving it, if I reedit the token unsubscribe is not correct

Original: 

![image](https://cloud.githubusercontent.com/assets/10166840/8077059/b1b20152-0f52-11e5-894a-004727708880.png)

After saving when I start a new edit with Builder:
![image](https://cloud.githubusercontent.com/assets/10166840/8076999/1e6b6668-0f52-11e5-8c8f-6a4297e80a6a.png)

Source HTML
```
<p style="text-align: center;"><a false="" href="&lt;strong contenteditable=">**Unsubscribe URL**&quot;&gt;No deseo recibir m&aacute;s ofertas de pastorelectrico.com</a></p>

<p style="text-align: center;"><strong contenteditable="&gt;**Unsubscribe URL**"><img alt="" src="http://gui.ww1.es/media/images/verde-500x10.png" style="line-height: 1.5em; width: 500px; height: 10px;" /></strong></p>
```

**Comment by miguelpascual** [comment]
I think the problem is that The token is not replaced when I close the builder and I save.

**Comment by alanhartless** [comment]
Looks like the visual token is getting corrupted either when first inserted or during the save and reload.  

Try to clear out the editor and retry. Does it happen each time? A problem with using WYSIWYG editors sometimes is they corrupt the HTML and do things not expected.

**Comment by miguelpascual** [comment]
you are rigth!

cleaning the html source code it works correct.
