### ISSUE TITLE
Form action "Remove From Do Not Contact" does not remove "Do not contact" Flag.

### ISSUE THREAD

**Issue by alanpy** [mautic/mautic#5313]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
If a contact clic on "Unsuscribe link" in the email he is tagged as "Do not contact".

In the forms exist an action called "Remove From Do Not Contact List", but this not remove the "Do not Contact" flag.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.11.0
| PHP version | 7.0.22-0ubuntu0.16.04.1

### Steps to reproduce:
1. Crear a suscribe form (with action "Remove From do not contact").
2. Suscribe to the form.
3. Send a mail.
4. Clic on "Unsuscribe" in the mail. User now is tagged as "Do not Contact".
5. Resubmit the form with same email address.
6. User continues with "Do not contact" Flag.

***Expected that this actions cleans the "Do not Contact" after resubmit.

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by TheLostAk47** [comment]
I have the same problem. But in the logs I can not find anything.

**Comment by dleczynski** [comment]
Can you go back to repair this bug again?
Version 2.14.0 still has a problem.

**Comment by Mike-Benoit** [comment]
We're experiencing this issue as well, effectively making it impossible for a user to re-subscribe to a list with a form. :(

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
