### ISSUE TITLE
Campaign box pushed out of sight after created

### ISSUE THREAD

**Issue by rowlandhill** [mautic/mautic#5315]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | NO
| Enhancement? | NO

## Description:
When adding a step (condition, action, or decision) sometimes the box, once create, is automatically sent across to the other side of the builder and out of sight.  Users with smaller screens are frustrated when the box seemingly disappears and they have to follow the line and scroll all the way over to retrieve each box, edit it, and put it where it belongs in the flow.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | YES
| PHP version | NO

### Steps to reproduce:
1. Launch campaign builder using a laptop with a small screen
2. Select a step
3. After selecting step, see that the box has been pushed out of sight
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

@cceruti

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
