### ISSUE TITLE
Campaign: Unable to select multiple values when adding a condition

### ISSUE THREAD

**Issue by rowlandhill** [mautic/mautic#5316]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | NO 
| Enhancement? | NO

## Description: (this may be a feature request, but logging as bug initially)
Unable to select multiple values when adding a condition: it shows the "excluding" and "including" options - similar to segment filtering allowing user to select multiple values for one condition - but in the campaign builder, users are unable to select multiple values on one step and forced to set up additional, repetitive steps based on each individual condition that they need in order to filter contacts out (created 2-3 additional steps, instead of just selecting multiple values in one condition window/box)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | YES
| PHP version | NO

### Steps to reproduce:
1. Launch campaign builder
2. Add a condition
3. Attempt to add multiple values for one condition, as you would within the segment builder - this is not possible
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

@cceruti

**Comment by dbhurley** [comment]
Moved to mautic-internal/mautic-internal#5

**Comment by dirtroof** [comment]
+100 for this. Not sure why the Campaign Decision operators list is different than everywhere else in Mautic. Plus there's no option to add multiple filter options in one go, which can make a campaign tree explode with all the little one-offs you have to create. A RegEx would be so much more elegant.
