### ISSUE TITLE
User's Can't Create Notes

### ISSUE THREAD

**Issue by dantearaujo** [mautic/mautic#5321]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:

I have created a non admin user for my client being able to view it's contacts inside of Mautic. 

I the custom permission settings for the role, I have enabled only some of Contact Permissions (All but Delete Contacts).

When the user try to view a contact and create a Note, it get's 500 error when loading the Popup Note Builder..

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.11.0
| PHP version | PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

### Steps to reproduce:
1. Create a user with only Contact permissions enabled
2. Click a contact and try to create a note
 
### Log errors: 
[2017-11-10 16:49:02] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Permission class not found for dynamicContent in permissions classes" at /home/admin/web/autoeste.metodoleads.com/public_html/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php line 128 {"exception":"[object] (InvalidArgumentException(code: 0): Permission class not found for dynamicContent in permissions classes at /home/admin/web/autoeste.metodoleads.com/public_html/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php:128)"} []

**Comment by brandner** [comment]
Also seeing this error when a non-admin user attempts to edit a landing page.

1. Create a user with non-admin role, including full permissions to landing pages and dynamic content
2. Log in as the new user
3. Go to Components - Landing Pages
4. Open a landing page
5. Click to edit the landing page
6. The Edit screen is not opened, no visible error. Check logs.

**Comment by Julius2Excel** [comment]
Also seeing this issue across multiple Mautic Installs, but only when updated to 2.11.0.
Seeing this across administrators accounts as well.

**Comment by YannickBiet** [comment]
@dbhurley currently the 2.11 is not usable in production for users who are not Admins.
Is this bug a Priority 0 bug that will be handdled in 2.12 ?

We need to communicate about the resolution to our customer base.

(we spent 2 hours this morning seeing that this is related to "dynamicContent" string that is the only permission with an uppercase letter within the name. It requires both Filesystem fixes + Database upgrade to change the permission records to each user

**Comment by YannickBiet** [comment]
@dbhurley @escopecz we ffixed the issue in PR 5421
can you please add it in 2.12 release ?

https://github.com/mautic/mautic/pull/5421

**Comment by alanhartless** [comment]
Closing as it was fixed in #5361
