### ISSUE TITLE
Tracking Pixel opened mail - Error 500

### ISSUE THREAD

**Issue by alberto464** [mautic/mautic#5322]
Hi, mautic and mailjet use, mautic sends mail but then does not collect email opening data, how come? On the program I see written "probably did not read the mail"

**Comment by npracht** [comment]
The open stats are generated by the mautic pixel. Nothing related to mailjet. We're using mailjet and stats work correctly into mautic.

Could you describe a bit more?

N.

**Comment by alberto464** [comment]
I see that the software understands when the client opens the mail:

https://prnt.sc/h9dxcv

but does not process it.

https://prnt.sc/h9dxxy

A second problem is that direct mail (with the subject "Ciao") is not sent. Campaigns but not reading the opening freezes in proceeding with automation.

**Comment by alberto464** [comment]
I found that my pixel tracking returns 500 error when pointing to it. How can I do? My server logs this error:

```
500	GET /email/5a077666aa99f.gif HTTP/1.0
AH01071: Got error 'PHP message: PHP Warning: PDOStatement::execute(): MySQL server has gone away in /var/www/vhosts/site/subdomain/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91\nPHP message: PHP Warning: PDOStatement::execute(): Error reading result set's header in /var/www/vhosts/site/subdomain/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91\n'
```

**Comment by npracht** [comment]
I think this is not related to mailjet then. You may rename your issue for a better understanding by the mautic core team.

**Comment by alberto464** [comment]
Yes, thank you!

**Comment by dbhurley** [comment]
Looks to be an issue with your database connection and not related to Mautic's code directly. Closing this issue. I'd recommend asking in the Slack channels or forums for specific help.

**Comment by DavideDave** [comment]
@alberto464 can you text me at dmarcon977@gmail.com? I have the same problem and i don't know how to solve it (i'm italian, by the way)
