### ISSUE TITLE
Signature token is incorrectly saved to Email Stats and thus displays wrong for Email WebView

### ISSUE THREAD

**Issue by isleshocky77** [mautic/mautic#5323]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

The email `{signature}` token is not correctly saved to the Email Stats object. The symptom of this is that if you click on a sent email in timeline or if a recipient clicks on "Having trouble reading this email? Click here." to view in the web, they'll see the wrong signature.

The actual email sent out contains the correct signature.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 5.6

### Steps to reproduce:

1. Create a default signature
2. Create a custom user signature
3. Create an email with a `{signature}` token in it
4. Create a new Lead
5. Assign Lead to User with custom signature
6. Send email to lead as part of a campaign
7. Check Email received and notice User's custom signature
8. Click on email from timeline view or from the Webview link in the email and notice that the Company's default signature is shown

## Cause

The webview actually pulls the tokens from the `email_stats` table. If you inspect that table you'll see the wrong `token` for `signature` is being saved.

**Comment by isleshocky77** [comment]
It looks like #3783 removed it from `BuilderSubscriber` which is where it would then be saved, and put it in `MailHelper` which only changes it for the actual sent mail. 

I'm not sure why @alanhartless did this in order to say it shouldn't be done this way; but I'm guessing this was a bug introduced.

**Comment by isleshocky77** [comment]
@dbhurley when was this addressed? I don't believe i was answered in the pr I tagged.

**Comment by dbhurley** [comment]
My fault! I am working through hundreds of issues, saw the merge and went with it - shame on me. Reopened.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
