### ISSUE TITLE
Full contact social integration throw exception 

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#5324]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Full Contact API is being called and the data is being returned correctly but the they do not render well as an exception is thrown.
![image](https://user-images.githubusercontent.com/12627658/32700680-0e7e2b52-c7d1-11e7-9f10-7eafd97a7fea.png)

## If a bug:
This is the details of the error
https://pastebin.com/rGkiEUEw

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.0.23

### Steps to reproduce:
1.  Integrate with full contact API
2. Lookup a single contact.
3. Go to the social tab 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Bizcrony** [comment]
You should talk to your Hosting.. It all about php version and Php extensions

**Comment by mabumusa1** [comment]
@bizcrony please check the logs it has a critical error. I don't think it is an extension or php version thing
