### ISSUE TITLE
Getting error when running console command mautic:campaigns:trigger

### ISSUE THREAD

**Issue by hurrycaner** [mautic/mautic#5329]
I was getting this error:
```
mautic.NOTICE: Exception: DateInterval::__construct(): Unknown or bad format (null) (uncaught exception) at /opt/bitnami/apps/mautic/htdocs/app/bundles/CampaignBundle/Model/EventModel.php line 1705 while running console command `mautic:campaigns:trigger` [] []
```
I took a look at https://github.com/mautic/mautic/blob/8879b117894648859e1ad4c90e9eaa5958a6ac5d/app/bundles/CampaignBundle/Model/EventModel.php#L1705 and found out that line https://github.com/mautic/mautic/blob/8879b117894648859e1ad4c90e9eaa5958a6ac5d/app/bundles/CampaignBundle/Model/EventModel.php#L1703 was `if ($wasScheduled || !empty($this->scheduleTimeForFailedEvents)) {` shouldn't it be `if ($wasScheduled && !empty($this->scheduleTimeForFailedEvents)) {` instead?

**Comment by hurrycaner** [comment]
Well, that didn't fixed all the bugs, it fixed one error, but new errors ocurred after... need more time cheking...

**Comment by tyweb2** [comment]
Is there a status on this bug? I commented  
// if ($wasScheduled || !empty($this->scheduleTimeForFailedEvents)) { 
and added
if ($wasScheduled && !empty($this->scheduleTimeForFailedEvents)) {

Now running mautic:campaign:trigger throws
 23194/23195 [===========================>]  99%PHP Notice:  Undefined variable: log in /var/www/html/mautic/app/bundles/CampaignBundle/Model/EventModel.php on line 1803 

But doesn't stop the process.

**Comment by amagdy3** [comment]
Still experiencing this. Error below:

[2018-08-22 03:45:07] mautic.NOTICE: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory (uncaught exception) at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 while running console command `mautic:social:monitoring` [] []

**Comment by StoppingBuck** [comment]
I have a sneaking suspicion this has been fixed, but I have not tested enough to know for sure

**Comment by StoppingBuck** [comment]
I am fairly certain now that this is fixed. We no longer get the error. I think we can close this one
( @RCheesley )
