### ISSUE TITLE
mautic:broadcasts:send does not send mail

### ISSUE THREAD

**Issue by pavel-janicek** [mautic/mautic#5330]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
1. Set up a segment
2. Put one contact to this segment
3. Create email:
3a: Segment email (blue one)
3b: Assigned to segment from step 1
3c: Published and never unpublish
4. Run php path/to/mautic/app/console mautic:broadcasts:send
5. Nothing happens. Mautic does not send out anything. If you look at given email, you can see one pending contact.

Only thing to trigger such mail is to send it manually, but I would like to do it automatically - for instance on given date and time. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.11.0
| PHP version | Version 7.0.18-0ubuntu0.16.04.1

### Steps to reproduce:
See description. To answer common questions:
- no, nothing in log. I checked both Mautic log and php log
- no, adding channel or id to the command does not help
- yes, I tried only with ID of email, did not help
- yes I tried only with adding channel to the command, did not help
- Yes, I tried to clear Mautic cache, did not help
- Yes, I run it also adding -vvv to the command and nothing changed.
- Last working version for me seems to be 2.9.1 
This is how it looks when running the command
<img width="973" alt="bin_ _janipav_clevermarketing___var_www_html_paveljanicek_cz_public_html_mautic_app_ _ssh_janipav_linode_ _204x59" src="https://user-images.githubusercontent.com/13867730/32784370-f258aae0-c94e-11e7-93ae-b630a7f7868f.png">

 
### Log errors: 

Nothing in logs, if you have any ideas how to make Mautic print at least SOMETHING to the logs, it would be highly appreciated. I have full sudo access to the machine, so I can change log levels, or so. I just need to help with how to do it.

I am planning to do full server restart, so if server restart will help, I will keep you posted

**Comment by MxyzptlkFishStix** [comment]
Do you have "app/bundles/CoreBundle/Command/SendChannelBroadcastCommand.php" in your installation? If yes, remove it.

**Comment by pavel-janicek** [comment]
That file does not exist in the installation :(
<img width="844" alt="bin_ _janipav_clevermarketing___var_www_html_esoteria_cz_public_html_mautic_app_bundles_corebundle_command_ _ssh_janipav_linode_ _204x62" src="https://user-images.githubusercontent.com/13867730/32842093-7ce95b78-ca1c-11e7-8022-401139ba8d40.png">

**Comment by IADDIC** [comment]
@dbhurley   you marked this as closed but I was looking for a solution to this same issue.  The problem we are starting to have is information scatter.  a piece here and there, try this or that.  

For me, I have the file that @MxyzptlkFishStix mentioned in my installation --- i.e:  SendChannelBroadcastCommand.php

should it be deleted?  Should it stay?  I am on version 2.12.0

**Comment by IADDIC** [comment]
Update:  Do not delete this file.  When the cron initiates the send functions this file is needed somewhere along the way.  cron output:  [ReflectionException]                                                           
  Class Mautic\CoreBundle\Command\SendChannelBroadcastCommand does not exist

**Comment by mayconmano** [comment]
Coloquem uma data de publicação que funciona
