### ISSUE TITLE
Autofill problem with (Phone, Company fields)

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#5339]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? |N 
| Enhancement? | 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 7

### Steps to reproduce:
1. Create a new Form to collect initial data (Firstname, Lastname, Phone, Email, Company)
2. Create another form and enable the **Autofill** option in all the field created.
3. The only field has been populated automatically by Mautic are Firstname, Lastname, Email and the Company and Phone are not been populated.
 
### Log errors: 
no log errors

**Comment by dbhurley** [comment]
Can't replicate in version 2.12

**Comment by npracht** [comment]
Close this in favor of https://github.com/mautic/mautic/issues/6286
