### ISSUE TITLE
Removed form fields stays in the HTML cache

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#534]
Steps to recreate:
1. Create a form with 2 fields.
2. Save the form.
3. Open the form at public URL (like mymautic.com/form/ID)
4. Remove one of the fields.
5. Save the form.

Result is that in edit form you cannot see the removed field, but at the public HTML the field still exists.

What I tried:
- Field is removed from the database.
- Field exists only in the HTML cache field of the Forms table.
- If I clear the HTML cache field and save the form, the form cache is recreated correctly - the removed field is gone.

**Comment by miguelpascual** [comment]
I have the same problem but I solve it turning ]Published] off, apply and turning on and apply.

**Comment by alanhartless** [comment]
Fixed with 1.1.3
