### ISSUE TITLE
Webhook action at the campaign editor does not save correctly header params if the value is repeated

### ISSUE THREAD

**Issue by aitor-hernandez** [mautic/mautic#5340]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
If you try to configure a webhook action in a campaign, and you add 2 header parameters with different names but the same value, Mautic only saves one of them.

Only one param appears saved at the associated properties field at the campaign_events table.

The image below is an example of a configuration that does not work.

![mautic_webhook_x_params_same_value_bug](https://user-images.githubusercontent.com/3840349/32899067-39070670-caea-11e7-9c52-a3d3b0e15b63.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.0.22

### Steps to reproduce:
1. Create a campaign
2. Create a webhook action
3. Configure 2 headers params with the same value.
3. Save editor -> Save campaign
4. Open campaign -> Edir campaign -> Open costructor campaign
5. Open webhook action
6. Check just one params was saved
 
### Log errors: 

No errors in mautic log
No errrors in web server log

**Comment by mikerowe81** [comment]
The same also occurs for "Data" items.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
