### ISSUE TITLE
Campaign Email Link Click Decision

### ISSUE THREAD

**Issue by nickian** [mautic/mautic#5343]
Does the campaign decision that looks for a link click in an email that is sent determine that the link has been clicked by looking for when the Mautic-encoded URL is processed and forwarded, or does it look for a hit on the page that the link is going to through the Mautic tracking JS or pixel?

I'm trying to use this feature to have users confirm their email address when subscribing. It doesn't seem to be working, but the landing page I'm using isn't actually live yet.

**Comment by nickian** [comment]
I answered my own question, but I have an additional one. It appears that the Mautic-encoded link does trigger the decision, regardless of whether or not there's a page hit on the page that Mautic forwards to (this is a good thing and preferable).

First, on the decision dialog, the option "Limit to Urls contains" is confusing to me. Does this mean if I put a full URL in there, it will limit the click decision to only links that go to that URL? Can I simply put words in there like "about-page" that refer to part of the URL? The decision only seemed to work when I removed all entries from this.

Second, the timeline on my profile (user who clicked the email link) shows a "Page Hit" after clicking this link. Except it's not a page hit because the page doesn't exist. Shouldn't this say "Link Clicked" instead of "Page Hit." Page hits should be triggered by the Mautic tracking code that is on the actual landing page.

Thanks

**Comment by kuzmany** [comment]
Decision work just for links converted to  Mautic tracking url (for example https://yourmautic.tld/r/somehashwithrandomchars). Decison is trigger when redirect  to your page.

Limit to Urls contains
- you can put whatever you want (part of url, string, whole url), the condition check this strings with redirect url.

**Comment by nickian** [comment]
Oh, I see. Thanks! So if you add a condition, then it depends on the Mautic tracking pixel, but without conditions it works even if the tracking page isn't set up.

I wonder if this could be changed to analyze the condition when the Mautic-encoded link is interpreted. Because what if I'm linking to a page that isn't on my site? Like if I want a decision when someone clicks on a link to my Twitter or something? Just a thought. Thanks!

**Comment by kuzmany** [comment]
Decision sholdn't depends on Mautic tracking pixel.  That means you can linked everywhere even to twitter, Mautic should recongize it.

**Comment by nickian** [comment]
Oh ok, good! Sorry I didn't understand at first. Thanks.

**Comment by ak47thakore** [comment]
Thank you @kuzmany
