### ISSUE TITLE
form issue with checkbox group and boollean custom field

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5348]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When I submit a form with one checkbox to fill, I don't get the info in the contact field.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10 and 2.11
| PHP version | 

### Steps to reproduce:
1. Create a boolean contact custom field with YES and NO
![image](https://user-images.githubusercontent.com/31535432/32950288-197e391a-cba6-11e7-9764-3e28211c246b.png)
2. Create a form
3. In this form add a checkox group field and map it to the previous custom field created.
4. In properties tab, add a value (in the value, I fill the value that equals to Yes) I tried Yes, 1 and True.
![image](https://user-images.githubusercontent.com/31535432/32950327-3ef4b174-cba6-11e7-85a2-36115f4b7f85.png)
5. Save and close
6. Fill the form and clic on the box.
![image](https://user-images.githubusercontent.com/31535432/32950878-4228810c-cba8-11e7-80c4-2948e9523114.png)
7. Go to contact sheet and check the value for the the custom field create before. There is no value. It should be Yes
![image](https://user-images.githubusercontent.com/31535432/32950861-31ffe914-cba8-11e7-81ca-1e778985fb54.png)

**Comment by kuzmany** [comment]
Labels doesn't mean values.
That means Bool contact custom fiedl Yes = label, value = 1, No = label, value = 0

**Comment by npracht** [comment]
@kuzmany this is clear for us.
But label is "i want the newsletter" and the value is "Yes" in this example.

We tried with `1` or `true` but it does no change anything. As you can see in the screenshot there is nothing stored in the boolean contact field.

**Comment by kuzmany** [comment]
Because boolean expect 1 or 0.  But on screenshot you sent Yes value. 
But I could re-test it, no problem.

**Comment by npracht** [comment]
We have a new example where we send with checkbox
- [x] true
- [ ] false

We also tried with `1` and `0`

### In the form result
We have true
### In the contact detail page
We have 0

**Comment by kuzmany** [comment]
Confirmed. 
Working on it.

**Comment by kuzmany** [comment]
Solution: https://github.com/mautic/mautic/pull/5366
