### ISSUE TITLE
Landing Page Google Analytics Script don't Update

### ISSUE THREAD

**Issue by morettic2015** [mautic/mautic#5351]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  YES
| Feature request? | NO 
| Enhancement? |  NO

## Description:
Can´t update Script from Analytics at Landing page. 

go to **Configuration >Landing page Settings > Analytics script** (i.e. Google Analytics) 

Remove alter does not make changes. Apply or Save and close either. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.11.0
| PHP version |  7.0.22

### Steps to reproduce:
1. Configuration 
2. Landing Page Settings
3. Alter google analytics script
4. Save and Close or Apply
 
### Log errors: 

`[2017-11-19 15:39:06] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Malformed UTF-8 characters, possibly incorrectly encoded" at /home/hiltza5/public_html/mautic/vendor/symfony/http-foundation/JsonResponse.php line 164 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /home/hiltza5/public_html/mautic/vendor/symfony/http-foundation/JsonResponse.php:164)"} []
`

**Comment by morettic2015** [comment]
Where does this script is stored at? So i can manual remove it to fix my problem.

**Comment by mabumusa1** [comment]
I confirm this bug, I tried it on two machines with the same versions mentioned above. `local.php` gets changed successfully (to remove any  file permission suspicion)  and the data is sent correctly to the server (I checked the post data in both Chrome and server side's php).

for an unknown reason the files of `config[pageconfig][google_analytics]` and `config[pageconfig][cat_in_page_url]` does not get updated at all.

@morettic2015: temporraly to solve your sure you can manaually change the file localted in `app/config/local.php` to add the script that you want

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Comment by morettic2015** [comment]
Fixed on release.
