### ISSUE TITLE
Hubspot is missing link to Mautic timeline

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#5354]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Mautic/Hubspot bidirectional sync is set up, contacts pushed into Hubspot but the mautic timeline field seems to be empty

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.0.25

### Steps to reproduce:
1. Set up Mautic/Hubspot integration
2. Push leads into Hubspot
3. Check the Mautic Timeline field (may be hidden, so you may need to view all properties or selectively add it to 'About' - field is named mautic_timeline on my instance of Hubspot
4. Notice if the link to the mautic profile for that user is present in the field
 
### Log errors: 

No errors are present in the Mautic log.

**Comment by vivasc2017** [comment]
Hi. We have same issue with our integration to Hubspot. Any news or update?

**Comment by ChuckRenner** [comment]
Does anyone have any further info on this?
