### ISSUE TITLE
Required Checkbox Form Element Doesn't Pass Validation 

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#536]
The original issue was #363 and is marked solved.

But I continue with the same problem:

When a checkbox field is mandatory it doesn't pass validation.

![image](https://cloud.githubusercontent.com/assets/10166840/8103659/700de12a-102a-11e5-8314-9c841da82c50.png)

![image](https://cloud.githubusercontent.com/assets/10166840/8103683/99b6ddc4-102a-11e5-835d-f4193309bc83.png)

**Comment by michaelgold** [comment]
I also am getting this issue with required checkboxes.
In addition, checkbox submissions on non-required checkboxes aren't working for me. 
When users fill out a form, the data from the checked boxes is not saved in the database. (All of the other fields are saved).
[Sreencast of issue](https://www.dropbox.com/s/54xw3sh0rifmcri/mautic-checkbox-error.mp4?dl=0)

**Comment by alanhartless** [comment]
Fixed with 1.1.3
