### ISSUE TITLE
Cannot save HTML in Contact Fields

### ISSUE THREAD

**Issue by pawneetdev** [mautic/mautic#5362]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Y

## Description:
HTML tags are removed when HTML content is added to a contact field. Mautic does not support twigs either, so it makes it difficult to add large dynamic content to emails. For instance, you need to add 5 orders for a customer in an email, neither can you store HTML in a field nor you can separate them using a delimiter in Mautic.

**Comment by kuzmany** [comment]
We use base64encode/decode for that purpose  and custom tag in email {base64decode=contactfieldalias}

**Comment by pawneetdev** [comment]
Not working

![image](https://user-images.githubusercontent.com/12933022/33159269-6cfb5eac-d037-11e7-8120-b979722acb20.png)

**Comment by pawneetdev** [comment]
NOT WORKING

![image](https://user-images.githubusercontent.com/12933022/33159279-8530eeb0-d037-11e7-945d-6991c9ef3532.png)

**Comment by kuzmany** [comment]
Man, base64decode is our ouwn tag via custom plugin, not core.

**Comment by pawneetdev** [comment]
Ok thanks

**Comment by kuzmany** [comment]
Small hint how to resolve it for programmers in my custom plugin: https://github.com/kuzmany/mautic/blob/plugin-extended-conditions/plugins/MauticExtendedConditionsBundle/EventListener/EmailSubscriber.php#L58
