### ISSUE TITLE
clone form and abort clone 

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#537]
This is a semi bug, 

When I start to clone a form if I close the form type selector (clicking the X) 
![image](https://cloud.githubusercontent.com/assets/10166840/8105371/0ad9348a-1039-11e5-91be-1eeacb5ce465.png)

it clones the form anyway

**Comment by dbhurley** [comment]
What's the status on this issue?

**Comment by escopecz** [comment]
This is related to the PR #683 and all related (other than Email Bundle). Can be closed with next release.
