### ISSUE TITLE
email groups/sequences

### ISSUE THREAD

**Issue by ivanbruno10** [mautic/mautic#5371]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Yes 

## Description:
When we create a campaign where we send out email streams, we have to create hundreds of emails, which gets confusing and time-consuming to add every email within a campaign.

An excellent way to organize emails would be to have an option to create a group / email sequence, so in a campaign we can select a certain sequence to be sent to the user, which would make it much more organized and require less time to set up a particular campaign.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
This is something we will consider in the future possibly so I'll mark it as a feature request. Currently not on the roadmap though. Happy to re-open if we get a PR for it! 🙂
