### ISSUE TITLE
Mail Settings

### ISSUE THREAD

**Issue by danfletcher1** [mautic/mautic#5376]
What type of report is this:

Bug

## Description:
The more details the better...

## If a bug:

5.6.30-0+deb8u1
v2.11.1-dev

### Steps to reproduce:
1. Fresh install
2. On install set the mail server settings to other smtp server / localhost / port 25 / no authentication / no encryption
3. Go straight to send a test mail. 
4. Fails with 
Failed to authenticate on SMTP server with username "blah" using 2 possible authenticators
++ Starting Swift_SmtpTransport << 220 mail.cheapgrass.co.uk ESMTP Postfix (Debian/GNU) >> EHLO perfumehub.co.uk << 250-mail.cheapgrass.co.uk 250-PIPELINING 250-SIZE 52428800 250-VRFY 250-ETRN 250-STARTTLS 250-AUTH PLAIN LOGIN 250-AUTH=PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN >> AUTH LOGIN << 334 VXNlcm5hbWU6 >> ZGFu << 334 UGFzc3dvcmQ6 >> SG90am90YmFuMQ== << 535 5.7.8 Error: authentication failed: authentication failure !! Expected response code 235 but got code "535", with message "535 5.7.8 Error: authentication failed: authentication failure " (code: 535) >> RSET << 250 2.0.0 Ok >> AUTH PLAIN ZGFuAGRhbgBIb3Rqb3RiYW4x << 535 5.7.8 Error: authentication failed: authentication failure !! Expected response code 235 but got code "535", with message "535 5.7.8 Error: authentication failed: authentication failure " (code: 535) >> RSET << 250 2.0.0 Ok

5. Resolved by enabling authentication, removing the login name and putting back to not authenticated. 

I can work around the issue but it took me a while to work out.

There is then a second issue I would like to report that I haven't managed to resolve. I can't say its not my fault but as your having a look at that section. 

I can't use IMAP or SSL as my certificates are self sign. I can't seem to use the options of no authentication as it always reports its got a problem with the certificate, even when I choose no encryption. In a similar manor to the above. I can't be completely sure I set my mail-server up correctly too. But I was able to repeat the issue with a fresh install then its possible there may be something similar going on here.

Kind regards,
 
### Log errors: 

mautic.ERROR: [MAIL ERROR] Failed to authenticate on SMTP server with username "blah" using 2 possible authenticators Log data: ++ Starting Swift_Transport_EsmtpTransport << 220 mail.cheapgrass.co.uk ESMTP Postfix (Debian/GNU)  >> EHLO perfumehub.co.uk  << 250-mail.cheapgrass.co.uk 250-PIPELINING 250-SIZE 52428800 250-VRFY 250-ETRN 250-STARTTLS 250-AUTH PLAIN LOGIN 250-AUTH=PLAIN LOGIN 250-ENHANCEDSTATUSCODES 250-8BITMIME 250 DSN  >> AUTH LOGIN  << 334 VXNlcm5hbWU6  >> ZGFu  << 334 UGFzc3dvcmQ6  >> SG90am90YmFuMQ==  << 535 5.7.8 Error: authentication failed: authentication failure  !! Expected response code 235 but got code "535", with message "535 5.7.8 Error: authentication failed: authentication failure " (code: 535) >> RSET  << 250 2.0.0 Ok  >> AUTH PLAIN ZGFuAGRhbgBIb3Rqb3RiYW4x  << 535 5.7.8 Error: authentication failed: authentication failure  !! Expected response code 235 but got code "535", with message "535 5.7.8 Error: authentication failed: authentication failure " (code: 535) >> RSET  << 250 2.0.0 Ok  (send); something@googlemail.com [] []

**Comment by Bizcrony** [comment]
@danfletcher1 what about cron jobs before sending an email ?
did you set it up before?
