### ISSUE TITLE
social media marketing automation / social people search / contact completer [feature]

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#5377]
I'm just looking at marketing automation from a personal perspective. Features I'm looking for are:

1. search for (known) person on several social networks like linkedin, xing, twitter. If multiple found, select the right one, request friendship, grep contact details from social network, as soon as connection is established, trigger marketing automation: "Helloe XY, nice to meet you yestertday on Z. This is what I can do for you
2. Update and aggregate contact details from social media profiles and add to adressbook
3. Show me a persons feed and summary, when I'm in contact with him
4. Send messages through social platforms
5. ...

Anything like this planned for mautic or already available? Do you know any other tools for this?

**Comment by dbhurley** [comment]
Hi! Not an issue, more suitable for Slack (https://mautic.slack.com) or the forums (https://www.mautic.org/community)
