### ISSUE TITLE
Add Responsible Disclosure pages to websites

### ISSUE THREAD

**Issue by micschk** [mautic/mautic#5385]
Security vulnerabilities should be sent to security@mautic.com and **NOT be published as an issue on Github** (for obvious reasons).

Responsible Disclosure instructions should probably be added to both Mautic websites, including a link eg in the footer. (#5364)

**Comment by dbhurley** [comment]
Sorry, meant to comment at the same time. Yes, there will be improvements to disclosure links. Not a tracker item but a good point you made.

**Comment by micschk** [comment]
NP; why not re-open & leave as a temporary reference? Then close when the pages/instructions have actually been added?

@dbhurley is the address correct (was my e-mail from 90 mins ago received)?

**Comment by alanhartless** [comment]
We've made updates to the readme and the issue template that'll be merged with a security patch that will be part of the 2.12 release. It's ok to leave this closed.
