### ISSUE TITLE
OAuth user callback restriction helptext: 'leave empty to NOT restrict'

### ISSUE THREAD

**Issue by micschk** [mautic/mautic#5387]
The current help text when creating a new API user, says to leave the callback mask empty to restrict callbacks. The code only checks the restriction if not empty, so the helptext should say 'leave empty to NOT restrict callbacks'.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
