### ISSUE TITLE
Re-usable & updatable headers/footers

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#5389]
What type of report is this:

| Q  | A
| ---| ---

| Feature request? | Yes

## Description:
What I'm looking for is a convenient way to display header/footer content for Emails. I want a system to pre-configure these headers/footers and be able to update them and have the change ripple across all of the email templates which make use of these headers/footers. I currently don't see a solution for this on MAUTIC.

**Comment by dbhurley** [comment]
Good suggestion. Not currently on the roadmap, but will mark as a feature request.
