### ISSUE TITLE
two contacts in Mautic that have a same email address

### ISSUE THREAD

**Issue by nesrine22** [mautic/mautic#5392]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
I just noticed, I have two contacts in Mautic that have a same email address. I thought, contacts would be merged automatically if their email address is same.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.10.1
| PHP version | 5.6.30-0+deb8u1

### Steps to reproduce:
1. Contact already exists
2.  when i add a new contact with the same adress email, I have two contacts in Mautic that have a same email address.
 
### Log errors: 

no log errors

**Comment by npracht** [comment]
Hello,

This known. The only way to create 2 contacts with the same email address is to create manually the contact from the interface.

This is not a bug.

**Comment by nesrine22** [comment]
even when i import a list of contacts(csv)  the contacts are not merged, and all the infos are the same.

**Comment by npracht** [comment]
This is not expected.
Do you have another unique ID as contact field ?

**Comment by nesrine22** [comment]
yes, i have the same contactwith the same email adress  with two ID different.

**Comment by npracht** [comment]
My question is, did you set another unique ID in custom field settings ?
![capture d ecran 2017-11-29 a 16 09 59](https://user-images.githubusercontent.com/14075239/33381985-d1c5d50a-d51f-11e7-9a1a-5a94ec914d7c.png)

**Comment by nesrine22** [comment]
yes, 
![image](https://user-images.githubusercontent.com/26248308/33382070-083e7470-d520-11e7-94be-dc2aefc5fc18.png)

**Comment by npracht** [comment]
I'm not talking about the email address which is natively an unique ID.
Do you have **another** custom fiels ?

**Comment by nesrine22** [comment]
No

**Comment by npracht** [comment]
Then it can be considered as a bug. Please provide steps to reproduce. If from csv. import maybe you can share your test file ?

**Comment by nesrine22** [comment]
Sorry i can't share my test file :( 

1. when i import a new contact file ( a csv file )  with existing email adress in my contact list in mautic 
2. I have two contacts in Mautic that have a same email address (no eurrer message )
3. habitually the contacts are merged automatically if their email address is same, **but now** i have a double contacts

**Comment by maciekkus** [comment]
@npracht 
Hi, I've also found this happening when importing contacts.
and I found this post: 
https://www.mautic.org/community/index.php/8531-duplicating-on-import-update
- if you set email field to being "not publicly updatable" import merges contacts, otherwise it duplicates.

strange, isn't it?

**Comment by npracht** [comment]
This problem has been addressed with the PR https://github.com/mautic/mautic/pull/5282

@escopecz you can close

**Comment by sheetal-mandyal** [comment]
I am having the same issue while contacts are created via form input. Form is not even showing the duplicate error neither the mautic-contacts

**Comment by ShareBtech** [comment]
wWe are seeing the same issue on Mautic 4.0.2 when a contact is imported or via API.
We have two unique identifiers setup here one for email and one for mobile.
Forum Post: https://forum.mautic.org/t/unique-identifier-duplicates-how-does-this-work/22037
