### ISSUE TITLE
segment filter on select fields does not work

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5398]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I have a custom field that is a select type. I have different values.
I want to have a segment and apply a filter on that field.
I create my segment: this select field > equals > a value of the list
The segment does not update. There are no contacts inside while I have many contacts with that value.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11
| PHP version | 

### Steps to reproduce:
1. Create a new custom field. Choose a select type and fill the label and value
2. Create a new contact and fill this new field that you just created.
3. Create a segment and add a filter on this new field like: new field > equals > choose the value that you filled on the contact previously created
4. Update the segment
5. There are no contacts entering in this segment

**Comment by dbhurley** [comment]
This doesn't sound like a bug but rather that your Cron jobs aren't setup or you don't have them running/configured quite right. Double check them and if you're still facing a problem re-open the issue.

**Comment by kuzmany** [comment]
Works for me on last staging.

**Comment by npracht** [comment]
@dbhurley & @kuzmany 
We have noticed that if you name your custom field a certain way it crashes some features.
![pasted image at 2017_12_05 09_37 am](https://user-images.githubusercontent.com/14075239/33597543-06af1e78-d9a0-11e7-8ca8-0677676db846.png)

## Conclusion
This is definitely a bug.

## Suggestion
Add a control on the naming to forbid the use of some names OR insure that this use does not crash anything.
