### ISSUE TITLE
Set "From:" Address on a per email campaign basis

### ISSUE THREAD

**Issue by amit777** [mautic/mautic#540]
When composing an Email, it would be good to allow the From: email address to default to the email address of the logged in user. This could be a system setting to allow this default.

**Comment by RCheesley** [comment]
I'm not sure how well this would work - if you were to create the email originally and it was all set up, then I edited it, wouldn't the email address on the 'From' field change to be mine?

That might not be desired behaviour, I'm guessing.  What would the use case be for this kind of scenario?

**Comment by amit777** [comment]
So for example, I have 3 users on my system, and each one wants to send out a mini campaign that looks like it came from them.  It's sort of a hybrid sales/marketing role.  Or maybe as simpler solution, each user could optionally configure their own SMTP settings that override the system settings.

**Comment by alanhartless** [comment]
If they are each creating their own campaign; can they create their own emails that has their email address as the custom from under the Advanced tab?

**Comment by alanhartless** [comment]
I think the best solution here is for each user to have their own template emails that have their email address set as the custom from under the Advanced tab. If you're running "mini campaigns" per user, I'm assuming that each user has their own campaign anyway. 

Thanks!
Alan
