### ISSUE TITLE
incorrect Content-Type of image file

### ISSUE THREAD

**Issue by kskmt** [mautic/mautic#5406]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
On email preview, Content-Type header of the image file is set to 'text/plain' so image can't display on some browser.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 7.1.7

### Steps to reproduce:
1. Go to Channel > Email > new email
2. make email with image embed
3. open preview URL
4. identify image URL (right click on image and open new tab, or something else)
5. check Content-Type header of this image URL (Postman, wget, etc.)

### Log errors: 

none.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by kskmt** [comment]
I'm not sure when, but it doesn't reproduce in 2.6.12, so it seems to have been fixed.
