### ISSUE TITLE
[feature] Allow forms to be imported with no styling

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#541]
Often I want to style forms myself, without any additional styling from Mautic.

Mailchimp has an option to embed the form with minimal/no styling, which would be much more slick for the designers/developers wanting to embed into an existing design.

**Comment by pitus** [comment]
I vote for this feature, although one could just duplicate the same set of mautic styles and override them - however, I agree that this unnecessarily creates clutter, extra css data being transferred and the necessity of overriding many css rules - hence my vote.

**Comment by that0n3guy** [comment]
As an additional idea.  You could use something like http://www.alpacajs.org/ to render the form output.  This would allow the user to choose what type of output you want (unstyled, bootstrap, jqueryUI, jquery mobile, etc..  see http://www.alpacajs.org/examples.html).

**Comment by troelsfeodor** [comment]
We need this option as well

**Comment by mbabker** [comment]
This was completed as part of #777 and included in 1.2.0.  Forms now have a `Render Style` option in the new/edit view.
