### ISSUE TITLE
UTM URL links conflict with hash tag anchor links

### ISSUE THREAD

**Issue by justjoolz** [mautic/mautic#5417]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? |  

## Description:

Using hash tags anchor links to a part of a page do not function correctly when UTM Campaign tags are appended to the URL. 

This is due to incorrectly adding the ?utm to the end of the url rather than before the #hash

ie.

Incorrect format:
https://example.org/url/path#pagehashlink?utm_source=Mautic&utm_medium=Email&utm_campaign=website&utm_content=test+-+hash+utm+link

Correct Format:
https://example.org/url/path/?utm_source=Mautic&utm_medium=Email&utm_campaign=website&utm_content=test+-+hash+utm+link#pagehaslink

Solution: Links should be checked for any hash links, if found UTM tags should be inserted before the hash.

### Steps to reproduce:
1.  Add link with hash to email 
2.  Set UTM Campaign Data on email 
3.  Send email (preview omits UTM Campaign links)
4.  Check if #links work or not

**Comment by mdgmichael** [comment]
Here 26 months later. No fix yet, I'm afraid. We're getting around this with 301 redirects on our sites.

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/8467

**Comment by dennisameling** [comment]
Fix landed in 3.0.1 which is scheduled for release on June 29 🚀
