### ISSUE TITLE
Strange increase in the CPU usage of my server due a cronjob

### ISSUE THREAD

**Issue by maxitromer** [mautic/mautic#5423]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

In the las months with the increase of the lead in my mautic instance I was noticing an increase in the time of the event triggering in Mautic.

Today I try to run the `campaigns:trigger` cronjob manually and I have to wait for 40 mins beacause 1 campaign needs to trigger more than 50.000 scheduled events.

Something really strange but I looking to see if that was a one time error I run the `campaigns:trigger` again and I have to wait 40 mins again because the same campaign needs to trigger the same 50.000 events.

![image](https://user-images.githubusercontent.com/6311835/33745543-35ce5dac-db96-11e7-8283-ed2a1e62bdbe.png)

This happend 2 more times, then I find that this campaign have 102.000 subscribers (yes, I have a big list)

You have to know that this subscribers go for a 10 day campaing months ago and I never remove but the level of resources was requiered until today.

Then I try to replace the campaign tinking that the problem was in the number or suscribers and I was right, after I clone the campaign and unpublish the oldone the CPU Usage of my server dropped about 60% and the disk operations too.

![image](https://user-images.githubusercontent.com/6311835/33745284-a1314ffc-db94-11e7-9e93-b53b87b5f59c.png)

Then I run the cronjob again and was finish in about 2 mins.

An incredible change, but I dont know exactly why.

And my questions are ...

Why the cronjob runs the same 50.000 events several times and not once?

Why this amount of events in an old campaign that runs a few months ago?

I'm doing something wrong here?

Why my mautic is using this level of resources and how I can solve it?

Of corse the idea is to find the problem here and solve it before I have a big problem wwith this.

Thanks in advance for your words and ideas.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 5.6.22

### Log errors: 

[2017-12-07 19:49:28] mautic.NOTICE: PHP Notice - Array to string conversion - in file /vendor/symfony/translation/Translator.php - at line 209 [] []

This error appears again and again.

**Comment by maxitromer** [comment]
UPDATE: When I run the cronjobs manually several times the same events was triggers several times too in the subscribers profiles, I know because I was tracking in contacts some profiles and they have the same events repeated in their history.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by maxitromer** [comment]
Hi @npracht 

This is related to #8113 

This still happens in my 2.15.3 instance but I can't reproduce the tests 3.0.1 because I'm not using that version in production.

**Comment by npracht** [comment]
closed in favor of #8113
