### ISSUE TITLE
email are always considered as open sent from Outlook plugin

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#5432]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When you end an email fom Outlook with the mautic plugin enabled, all the email sent are considered as opened.

### My understanding of the issue
My opinion is that the email include the tacking pixel directly in outlook (in the sent email).
That would mean that if the sender has a preview of the sent email in its window, the pixel is called and email directly considered as opened.

#### Source code of the sent email in outlook
![capture d ecran 2017-12-11 a 17 18 37](https://user-images.githubusercontent.com/14075239/33841254-8425a038-de97-11e7-8808-84c7af31bc98.png)

### Suggestion
**Do not include the email pixel in the sent email preview in the the sender mailbox.**

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 

### Steps to reproduce:
1. Set up Outlook plugin
2. Send email from Outlook
3. Go on the contact page and see the email set as opened.

**Comment by dbhurley** [comment]
There's no way to not include the pixel in the sent email as the very nature of "sent email" is a static copy of the email that was sent.

**Comment by npracht** [comment]
Then why can I see the pixel when I inspect the code of the email send in outlook in my outlook client?!!!

**Comment by dbhurley** [comment]
If you'll re-read my message (highlighted here for emphasis):

>There's no way to *not* include the pixel

**Comment by npracht** [comment]
Roger that.

Ok then this feature does not track opens but only the fact of sending email to a contact.

- Maybe that could be better explained in https://mautic.org/docs/en/plugins/outlook.html ?
- Maybe the UI could be a little modified to mention that this email is sent from email client (outlook/gmail) without mentioning the fact that it is opened or not ?

**Comment by dbhurley** [comment]
Understood, here's a PR for it. (See how easy that was? Next one I'll let you do! 😉)

https://github.com/mautic/documentation/pull/245
