### ISSUE TITLE
problem with segment membership filter on segments

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5433]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I create a new segment. I add the filter "segment membership" including and I choose 2 segments to include
![image](https://user-images.githubusercontent.com/31535432/33841486-27119004-de98-11e7-97e9-e78a446b6b3f.png)
Then I save.
I go back to check the filter of the segment.
And I see that I only have one segment included (not 2)
![image](https://user-images.githubusercontent.com/31535432/33841545-590ba658-de98-11e7-856a-8188cb05737c.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11
| PHP version | 

### Steps to reproduce:
1. Create new segment
2. Add filter "segment membership" and include and choose two segments to include
3. Save
4. Go again in the segment to check the filter
5. See that there only one segment included
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
I can't replicate. 
Do you have published segment source lp1?  Cause unpublished segments don't display in this filter.
Share please all your segmetns setup.

![image](https://user-images.githubusercontent.com/462477/33857071-931a310c-deca-11e7-92f9-fe91729136ef.png)

**Comment by dbhurley** [comment]
I can't reproduce either. Closing for now. Please re-open if you find some reproducible method for seeing this error.
