### ISSUE TITLE
Documentation inconsistencies CRON jobs

### ISSUE THREAD

**Issue by inetbiz** [mautic/mautic#5436]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
https://mautic.org/docs/en/setup/getting_started.html **Step 2** `php /path/to/mautic/app/console mautic:campaigns:rebuild` versus https://mautic.org/docs/en/setup/cron_jobs.html `5,20,35,50 <— mautic:campaigns:update`

Which is it? Both? `rebuild or update`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Both.

_Side Note: In the future, ask these types of questions in Slack (https://mautic.org/slack) or in the forums (https://mautic.org/community)._

**Comment by inetbiz** [comment]
It's a gitbook generated document. I assumed github is the place. Sorry.

**Comment by dbhurley** [comment]
No problem! Didn't realize you were addressing a docs bug. 

Just for future and your own knowledge: https://github.com/mautic/documentation is home for those files...

**Comment by dbhurley** [comment]
And PR created: https://github.com/mautic/documentation/pull/244

**Comment by doliver3** [comment]
Hi @dbhurley This is still inconsistently documented. This pull request only addresses just one of the places in the documentation it is documented as rebuild.  

When you reply in this issue that the answer is 'both', what does that mean?  Does that mean that both mautic:campaigns:update and mautic:campaigns:update should be in the cron job?  Do both do exactly the same thing so only one is needed?

From the pull request, it suggests it should only be one in the cron jobs not both, it suggest it should only be mautic:campaigns:update
Can you confirm that is what it should be and that mautic:campaigns:rebuild should not be used?

Are the required cron jobs:
mautic:segments:update
mautic:campaigns:rebuild
mautic:campaigns:trigger

or are they ?
mautic:segments:update
mautic:campaigns:update
mautic:campaigns:trigger

This current documentation url still has them both ways:
https://www.mautic.org/docs/en/setup/cron_jobs.html
mautic:campaigns:update  in the shorthand at the top then
mautic:campaigns:rebuild in the Campaigns detail section below

The main getting started page:
https://www.mautic.org/docs/en/setup/getting_started.html
has them as update only
mautic:campaigns:update

Would you be able to update the documentation to clarify?

Thanks

**Comment by patrykgruszka** [comment]
@doliver3 I've just checked this command code and noticed that `mautic:campaigns:update` is just alias of `mautic:campaigns:rebuild` task. So I think you don't need them both to run. That should be described in the docs.

```
// app/bundles/CampaignBundle/Command/UpdateLeadCampaignsCommand.php:95
$this
    ->setName('mautic:campaigns:rebuild')
    ->setAliases(['mautic:campaigns:update'])
    ->setDescription('Rebuild campaigns based on contact segments.')
```

**Comment by virgilwashere** [comment]
I've just recently posted on the forum about this...and will submit a PR to docs.

https://forum.mautic.org/t/cron-jobs-whats-the-difference/11177/3?u=virgilwashere
