### ISSUE TITLE
Email trigger cron crashes after first send

### ISSUE THREAD

**Issue by amit777** [mautic/mautic#544]
Below is the log for output of manually running the cron job.  I did a very basic test of setting up a campaign to send an email to 4 leads in a list. I have also setup a couple point scores.  The first email seems to go out, however I have to rerun the symfony task with the --force option, otherwise I get this error: "Script in progress. Use -f or --force to force execution."

```
php app/console mautic:campaigns:trigger --env=prod

Triggering events for campaign 1
Triggering first level events
4 total events(s) to be processed in batches of 100
 0/4 [>---------------------------]   0% 
PHP Notice:  Undefined index: emails in /www/docs/mautic/app/bundles/EmailBundle/Helper/PointEventHelper.php on line 30
 1/4 [=======>--------------------]  25%


  [Doctrine\ORM\ORMInvalidArgumentException]
  A new entity was found through the relationship 'Mautic\PointBundle\Entity\LeadPointLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #1. To solve this issue: Either explicitly call EntityManager#persist() on this unknown
   entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

```

**Comment by amit777** [comment]
This very well be due to the fact that I'm running off a cloned git repo and not off a tagged version.

**Comment by alanhartless** [comment]
Hi @amit777 

Do you have any Point Actions configured under Manage Points? If so, can you get me as screenshot or at least describe it's setup?

Thanks!
Alan

**Comment by alanhartless** [comment]
Hi @amit777,
Just following up on this to see if you can provide some feedback to my last question?

Thanks!
Alan

**Comment by amit777** [comment]
Hi Alan, sorry, I don't have the instance setup any more. However if I remember correctly, there were point actions configured.

**Comment by ptcc** [comment]
I have something similar to this!
the job also stops after the first lead event 
>sudo php /var/crm/app/console --force mautic:campaigns:trigger --env=prod
...
Triggering events for campaign 4
Triggering first level events
108 total events(s) to be processed in batches of 100
   1/108 [>---------------------------]   0%
[Doctrine\ORM\ORMInvalidArgumentException]
  A new entity was found through the relationship 'Mautic\AssetBundle\Entity\Download#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #1964. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

**Comment by ptcc** [comment]
I'm creating a new issue since this one is closed...
