### ISSUE TITLE
Edits to contacts do not get written to DB - See MysqliException

### ISSUE THREAD

**Issue by IADDIC** [mautic/mautic#5443]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

Bug

| Bug report? | 

## Description:
When changing a contacts fields, the data appears to be written to the DB.  However, if you leave the edit session and return, the edits did not stick.  The same applies to adding a new contact.

Other features of mautic work except for the contact fields.  I.E I can change or create an email.  I can send new contacts through the API, I can edit configuration settings... 

-----------------  UPDATE  ---------------------------------------
While reading and searching for a solution I ran the following command:

Updates the database schema:
php app/console doctrine:schema:update --force

which produced 2 error messages -- 

 [Doctrine\DBAL\Driver\Mysqli\MysqliException]
Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

[Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'ALTER TABLE maujd_leads CHANGE title title VARCHAR(255) DEFAULT NULL, CHANG
  E firstname firstname VARCHAR(255) DEFAULT NULL, CHANGE lastname lastname VARCHAR(255) DEFAULT NULL, CHANGE compan
  y company VARCHAR(255) DEFAULT NULL, CHANGE position position VARCHAR(255) DEFAULT NULL, CHANGE phone phone VARCHA
  R(255) DEFAULT NULL, CHANGE mobile mobile VARCHAR(255) DEFAULT NULL, CHANGE fax fax VARCHAR(255) DEFAULT NULL, CHA
  NGE address1 address1 VARCHAR(255) DEFAULT NULL, CHANGE address2 address2 VARCHAR(255) DEFAULT NULL, CHANGE city c
  ity VARCHAR(255) DEFAULT NULL, CHANGE state state VARCHAR(255) DEFAULT NULL, CHANGE zipcode zipcode VARCHAR(255) D
  EFAULT NULL, CHANGE twitter twitter VARCHAR(255) DEFAULT NULL, CHANGE facebook facebook VARCHAR(255) DEFAULT NULL,
   CHANGE googleplus googleplus VARCHAR(255) DEFAULT NULL, CHANGE skype skype VARCHAR(255) DEFAULT NULL, CHANGE inst
  agram instagram VARCHAR(255) DEFAULT NULL, CHANGE foursquare foursquare VARCHAR(255) DEFAULT NULL, CHANGE wthstw w
  thstw VARCHAR(255) DEFAULT NULL, CHANGE ureason ureason VARCHAR(255) DEFAULT NULL, CHANGE blt blt VARCHAR(255) DEF
  AULT NULL, CHANGE dffm dffm VARCHAR(255) DEFAULT NULL, CHANGE link link VARCHAR(255) DEFAULT NULL, CHANGE wsd wsd
  VARCHAR(255) DEFAULT NULL, CHANGE printsrv printsrv VARCHAR(255) DEFAULT NULL, CHANGE phtocreative phtocreative VA
  RCHAR(255) DEFAULT NULL, CHANGE donatehelp donatehelp VARCHAR(255) DEFAULT NULL, CHANGE cli cli VARCHAR(255) DEFAU
  LT NULL, CHANGE lang lang VARCHAR(255) DEFAULT NULL, CHANGE storename storename VARCHAR(255) DEFAULT NULL, CHANGE
  website_user_name website_user_name VARCHAR(255) DEFAULT NULL, CHANGE charity_name charity_name VARCHAR(255) DEFAU
  LT NULL, CHANGE ein_or_registration_no ein_or_registration_no VARCHAR(255) DEFAULT NULL, CHANGE certify certify VA
  RCHAR(255) DEFAULT NULL, CHANGE linkedin linkedin VARCHAR(255) DEFAULT NULL, CHANGE vkontakte vkontakte VARCHAR(25
  5) DEFAULT NULL, CHANGE youtube youtube VARCHAR(255) DEFAULT NULL, CHANGE governmental__usa governmental__usa VARC
  HAR(255) DEFAULT NULL, CHANGE governmental__intl governmental__intl VARCHAR(255) DEFAULT NULL, CHANGE faith_relati
  onships faith_relationships VARCHAR(255) DEFAULT NULL, CHANGE family_and_friends family_and_friends VARCHAR(255) D
  EFAULT NULL, CHANGE hits_on_website hits_on_website VARCHAR(255) DEFAULT NULL, CHANGE affordable_housing affordabl
  e_housing VARCHAR(255) DEFAULT NULL, CHANGE event_planner event_planner VARCHAR(255) DEFAULT NULL, CHANGE executiv
  ve executivve VARCHAR(255) DEFAULT NULL, CHANGE construction construction VARCHAR(255) DEFAULT NULL, CHANGE consul
  tant consultant VARCHAR(255) DEFAULT NULL, CHANGE architect architect VARCHAR(255) DEFAULT NULL, CHANGE academia_a
  nd_technical academia_and_technical VARCHAR(255) DEFAULT NULL, CHANGE investors investors VARCHAR(255) DEFAULT NUL
  L, CHANGE laakeland laakeland VARCHAR(255) DEFAULT NULL, CHANGE linkedin_rmg linkedin_rmg VARCHAR(255) DEFAULT NUL
  L, CHANGE linkedin_sag linkedin_sag VARCHAR(255) DEFAULT NULL, CHANGE medical medical VARCHAR(255) DEFAULT NULL, C
  HANGE military military VARCHAR(255) DEFAULT NULL, CHANGE networking_general networking_general VARCHAR(255) DEFAU
  LT NULL, CHANGE ngo__non_governmental_org ngo__non_governmental_org VARCHAR(255) DEFAULT NULL, CHANGE nonprofit_or
  ganization nonprofit_organization VARCHAR(255) DEFAULT NULL, CHANGE pre__2005_past_work_relat pre__2005_past_work_
  relat VARCHAR(255) DEFAULT NULL, CHANGE real_estate real_estate VARCHAR(255) DEFAULT NULL, CHANGE shelters shelter
  s VARCHAR(255) DEFAULT NULL, CHANGE sip39s sip39s VARCHAR(255) DEFAULT NULL, CHANGE urban_development urban_develo
  pment VARCHAR(255) DEFAULT NULL, CHANGE valley_creek valley_creek VARCHAR(255) DEFAULT NULL, CHANGE raymund_king_e
  vents raymund_king_events VARCHAR(255) DEFAULT NULL, CHANGE 2004_lane_kramer__ceo_ins 2004_lane_kramer__ceo_ins VA
  RCHAR(255) DEFAULT NULL, CHANGE 2006_usaid_shelter_worksh 2006_usaid_shelter_worksh VARCHAR(255) DEFAULT NULL, CHA
  NGE 2007_april__second_trip_t 2007_april__second_trip_t VARCHAR(255) DEFAULT NULL, CHANGE 2007_march__first_trip_t
  o 2007_march__first_trip_to VARCHAR(255) DEFAULT NULL, CHANGE 2008_january__trade_show 2008_january__trade_show VA
  RCHAR(255) DEFAULT NULL, CHANGE 2011_africa_economic_foru 2011_africa_economic_foru VARCHAR(255) DEFAULT NULL, CHA
  NGE 2011_topping_out_event 2011_topping_out_event VARCHAR(255) DEFAULT NULL, CHANGE 2012_economic_commission 2012_
  economic_commission VARCHAR(255) DEFAULT NULL, CHANGE 2012_smu 2012_smu VARCHAR(255) DEFAULT NULL, CHANGE 2012_rio
  20_in_rio 2012_rio20_in_rio VARCHAR(255) DEFAULT NULL, CHANGE 2012_rio20_nyc 2012_rio20_nyc VARCHAR(255) DEFAULT N
  ULL, CHANGE 2012_rio20_the_hague 2012_rio20_the_hague VARCHAR(255) DEFAULT NULL, CHANGE individual individual VARC
  HAR(255) DEFAULT NULL, CHANGE funded funded VARCHAR(255) DEFAULT NULL, CHANGE tgs_username tgs_username VARCHAR(25
  5) DEFAULT NULL, CHANGE tgs_billing_first_name tgs_billing_first_name VARCHAR(255) DEFAULT NULL, CHANGE tgs_billin
  g_last_name tgs_billing_last_name VARCHAR(255) DEFAULT NULL, CHANGE tgs_billing_company tgs_billing_company VARCHA
  R(255) DEFAULT NULL, CHANGE tgs_billing_email tgs_billing_email VARCHAR(255) DEFAULT NULL, CHANGE tgs_billing_phon
  e tgs_billing_phone VARCHAR(255) DEFAULT NULL, CHANGE tgs_billing_country tgs_billing_country VARCHAR(255) DEFAULT
   NULL, CHANGE tgs_billing_address_1 tgs_billing_address_1 VARCHAR(255) DEFAULT NULL, CHANGE tgs_billing_address_2
  tgs_billing_address_2 VARCHAR(255) DEFAULT NULL, CHANGE tgs_billing_city tgs_billing_city VARCHAR(255) DEFAULT NUL
  L, CHANGE tgs_billing_state tgs_billing_state VARCHAR(255) DEFAULT NULL, CHANGE tgs_billing_postcode tgs_billing_p
  ostcode VARCHAR(255) DEFAULT NULL, CHANGE tgs_account_status tgs_account_status VARCHAR(255) DEFAULT NULL, CHANGE
  tgs_role tgs_role VARCHAR(255) DEFAULT NULL, CHANGE sustainabledevelopment sustainabledevelopment VARCHAR(255) DEF
  AULT NULL, CHANGE stwnewsletter stwnewsletter VARCHAR(255) DEFAULT NULL, CHANGE personalfriends personalfriends VA
  RCHAR(255) DEFAULT NULL, CHANGE numberofhousesorshelters numberofhousesorshelters VARCHAR(255) DEFAULT NULL, CHANG
  E mgoorosb mgoorosb VARCHAR(255) DEFAULT NULL, CHANGE iaddiccountry1 iaddiccountry1 VARCHAR(255) DEFAULT NULL, CHA
  NGE iaddiccountry2 iaddiccountry2 VARCHAR(255) DEFAULT NULL, CHANGE iaddicrfqformsubmitted iaddicrfqformsubmitted
  VARCHAR(255) DEFAULT NULL, CHANGE iaddichowmanystories iaddichowmanystories VARCHAR(255) DEFAULT NULL, CHANGE iadd
  icfirstfloorheight iaddicfirstfloorheight VARCHAR(255) DEFAULT NULL, CHANGE iaddicsuppliedskins iaddicsuppliedskin
  s VARCHAR(255) DEFAULT NULL, CHANGE iaddicaveragesize iaddicaveragesize DOUBLE PRECISION DEFAULT NULL, CHANGE fami
  ly__no_kids family__no_kids VARCHAR(255) DEFAULT NULL, CHANGE family__kids_only family__kids_only VARCHAR(255) DEF
  AULT NULL, CHANGE personal_friends_only personal_friends_only VARCHAR(255) DEFAULT NULL, CHANGE stw_translator stw
  _translator VARCHAR(255) DEFAULT NULL, CHANGE stw_unsubscribe stw_unsubscribe VARCHAR(255) DEFAULT NULL, CHANGE pm
  o_unsubscribe pmo_unsubscribe VARCHAR(255) DEFAULT NULL, CHANGE iaddic_unsubscribe iaddic_unsubscribe VARCHAR(255)
   DEFAULT NULL, CHANGE tgs_unsubscribe tgs_unsubscribe VARCHAR(255) DEFAULT NULL, CHANGE em_unsubscribe em_unsubscr
  ibe VARCHAR(255) DEFAULT NULL, CHANGE are_you_sure_you_want_to are_you_sure_you_want_to VARCHAR(255) DEFAULT NULL,
   CHANGE stw_quitter stw_quitter VARCHAR(255) DEFAULT NULL, CHANGE stw_quitting_reason stw_quitting_reason VARCHAR(
  255) DEFAULT NULL, CHANGE stw_virtual_volunteer stw_virtual_volunteer VARCHAR(255) DEFAULT NULL, CHANGE iaddic_sub
  scribe_to_our_n iaddic_subscribe_to_our_n VARCHAR(255) DEFAULT NULL, CHANGE em_master_newsletter em_master_newslet
  ter VARCHAR(255) DEFAULT NULL, CHANGE pmo_master_newsletter pmo_master_newsletter VARCHAR(255) DEFAULT NULL, CHANG
  E seo seo VARCHAR(255) DEFAULT NULL, CHANGE personal_executive_relati personal_executive_relati VARCHAR(255) DEFAU
  LT NULL, CHANGE iaddic_3d_model_download iaddic_3d_model_download VARCHAR(255) DEFAULT NULL, CHANGE em_start_from_
  website em_start_from_website VARCHAR(255) DEFAULT NULL, CHANGE stw_start_from_web stw_start_from_web VARCHAR(255)
   DEFAULT NULL, CHANGE stw_update_contact_inform stw_update_contact_inform VARCHAR(255) DEFAULT NULL, CHANGE pmo_st
  art pmo_start VARCHAR(255) DEFAULT NULL, CHANGE iaddic_master_newsletter iaddic_master_newsletter VARCHAR(255) DEF
  AULT NULL, CHANGE stw_real_estate stw_real_estate VARCHAR(255) DEFAULT NULL, CHANGE brick_fundraiser brick_fundrai
  ser VARCHAR(255) DEFAULT NULL, CHANGE personal_unsubscribe personal_unsubscribe VARCHAR(255) DEFAULT NULL, CHANGE
  tester tester VARCHAR(255) DEFAULT NULL, CHANGE iaddic_date_rfq_form_subm iaddic_date_rfq_form_subm DATE DEFAULT N
  ULL, CHANGE personal_high_value personal_high_value VARCHAR(255) DEFAULT NULL':

  Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes stor
  age overhead, check the manual. You have to change some columns to TEXT or BLOBs

## If a bug:
| Mautic version | 2.12
| PHP version | 7.0

### Steps to reproduce:
1. select a contact
select details
select edit
edit a field
save and exit
go to the tab that holds the field you changed and notice the field state is whatever the previous state was.

 
### Log errors: 

see above

**Comment by dbhurley** [comment]
Problem seems to be unique? Going to close unless others respond with similar issues.
