### ISSUE TITLE
Outlook Plugin root folder (bug?)

### ISSUE THREAD

**Issue by wrhiltz** [mautic/mautic#5445]
This is my first post to GitHub, and I'm not a developer. :-(

I've encountered an issue in with the Outlook plug-in, the discussions are on the forum, so being lazy I won't reproduce all of the text here.

The issues are described in these two posts:

https://www.mautic.org/community/index.php/8837-outlook-plug-in-mautic-url-issue/p1#p27761
https://www.mautic.org/community/index.php/6087-add-tracking-pixel-in-email-signature/p1#p27731

I hope this helps.

Bill

**Comment by dbhurley** [comment]
Closing due to incomplete report. Must have "Steps to Replicate" so others can fix test and fix this bug. Will reopen if these steps are added.
