### ISSUE TITLE
Social monitoring once enabled clicking produces error 500

### ISSUE THREAD

**Issue by ecoitsolutions** [mautic/mautic#5448]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
Once a twitter hastag or mention is enabled, it is impossible to open for stats, in logs there is a database insert error

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  Latest
| PHP version |  7.0

### Steps to reproduce:
1.  Add a new Twitter hashtag or mention monitoring 
2.  Click on the monitoring item
 
### Log errors: 

[2017-12-13 11:18:25] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT DATE_FORMAT(t.post_date, '%Y-%m-%d') AS date, post_count AS count FROM monitor_post_count t WHERE (t.monitor_id = ?) AND (t.post_date BETWEEN ? AND ?) AND (t.monitor_id = 5) GROUP BY DATE_FORMAT(t.post_date, '%Y-%m-%d') ORDER BY DATE_FORMAT(t.post_date, '%Y-%m-%d') ASC LIMIT 31' with params [5, "2017-11-13 00:00:00", "2017-12-13 11:18:25"]:  SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'lead_soteha_it.t.post_count' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" at 
 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT DATE_FORMAT(t.post_date, '%Y-%m-%d') AS date, post_count AS count FROM monitor_post_count t WHERE (t.monitor_id = ?) AND (t.post_date BETWEEN ? AND ?) AND (t.monitor_id = 5) GROUP BY DATE_FORMAT(t.post_date, '%Y-%m-%d') ORDER BY DATE_FORMAT(t.post_date, '%Y-%m-%d') ASC LIMIT 31' with params [5, \"2017-11-13 00:00:00\", \"2017-12-13 11:18:25\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'lead_soteha_it.t.post_count' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at  /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'lead_soteha_it.t.post_count' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at  /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'lead_soteha_it.t.post_count' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at  /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

**Comment by rene-hermenau** [comment]
MySQL 5.7.5+ changed the way GROUP BY behaved in order to be SQL99 compliant (where in previous versions it was not).

Until this is fixed here you can bypass the issue by removing  `only_full_group_by` from the my.cnf

```[mysqld]
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION```

**Comment by lalitnandandiwakar** [comment]
after punting this 
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION```

mysql not restart 
@dbhurley
Job for mysql.service failed because the control process exited with error code. See "systemctl status mysql.service" and "journalctl -xe" for details.

**Comment by adrianogf** [comment]
The sintax is wrong... 
Try
sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

**Comment by escopecz** [comment]
Duplicate of https://github.com/mautic/mautic/issues/4021

The quick fix is to set SQL mode only_full_group_by in your database.
