### ISSUE TITLE
Form names starting with a number generate invalid javascript MauticValidation. name!

### ISSUE THREAD

**Issue by pitus** [mautic/mautic#545]
We just upgraded to v1.1.2 (somehow ending up with v1.1.3dev instead) and forms stopped working for us. After some investigation, I've noticed a javascript error (ILLEGAL) where the form validation function is being generated. Our form names started with numbers (so they sort properly on the list) and got translated into javascript function name that starts with a number as well - which is illegal in javascript.

Perhaps you could detect such a case (function / form name starting with a number - you're already removing any non number, non letters) and pre-pend the name with some letter such as 'f' for form? or 'v' for validation ?

For now I've renamed all our forms prepending F in front of the number and it seems to work.

**Comment by alanhartless** [comment]
Hi Pitus!

I've marked this as a bug so we can fix that.

I have no clue how you got to 1.1.3dev though.  Do you have some upgrade scripts that are based on the repository rather than going through the built in updater?  I double checked the packages, and they have 1.1.2 as the version.

Thanks!
Alan

**Comment by pitus** [comment]
No idea how, someone else is upgrading Mautic and they may have pulled them from repository. As far as I know, there's no harm done as 1.1.3dev is pretty much identical to 1.1.2 so we'll be OK ... but that bug is worth fixing ;)

**Comment by alanhartless** [comment]
Fixed with 1.1.3
