### ISSUE TITLE
Feauture: Do not send to multiple leads on a same company the same day 

### ISSUE THREAD

**Issue by rmalla** [mautic/mautic#5456]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
This may be kind of a tricky one, not.sure if its possible with the current implementation. 

I have companies with lets say 10 leads (all of the purchasing department). I would like to send them follow-up emails but not to all on the same day. 

I would like to send maybe to one or two contacts per day. Is this possible? 

Any idea how to implememt?

| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
This is not something that can be included. It would require segmentation within segments I believe.
