### ISSUE TITLE
Leads get Duplicated occasionally (same email) by Mautic (cron?)

### ISSUE THREAD

**Issue by pitus** [mautic/mautic#546]
I've already mentioned it in https://github.com/mautic/mautic/pull/152 as:
>Is it possible that chron, coming in on localhost IP, would cause duplicate Leads with the same IP?
We're using 1.0.5 and we've noticed several Leads suddenly get duplicated when a person visits the site that has a tracking image. The strange thing is that logs show the person coming in from the same static IP - in the past and just now when the duplicate was created. Now there are two Leads in the database with the same IP and email for some reason.

**Updated 2015/06/15 - we've upgraded to 1.1.3dev** and Leads are still being duplicated, mostly around 12 AM and/or 12 PM (haven't noticed any duplicates at other times so this may be a clue as to where the duplication happens - **possibly crone**, may be related to time zone (we're UTC+2)
I suspect Cron as some SQL entries for these Leads show localhost IP that belongs to Cron job.

Note, this doesn't happen often, only a fraction of **Confirmed Leads** result with duplicates on a smart list (and Lead Manager page - so this is not just a list issue). I'll keep watching this in hope of finding some clue as to when/why this is happening - can't just reproduce it at the moment, but I may be able to provide details from SQL if someone could point me as to which tables to extract data for them (I've found and analyzed refs in `campaign_leads, campaign_lead_event_log, form_results_ID_NAME by email, form_submissions, leads, lead_ips_xref, lead_lists_leads - irrelevant, lead_points_change_log, page_hits, point_lead_action_log`).

**Comment by alanhartless** [comment]
What commands/scripts are running via cron? Does it look like these leads are getting created by the cron job?  For the duplicated leads, do a query against audit_log where object = lead and the object_id = the ID of the leads in quest.  Hopefully that'll give us a general idea of what Mautic did with the leads.

Thanks!
Alan

**Comment by pitus** [comment]
Here's a set of cron jobs we execute every 5 minutes (for now, may consider lower frequency in the future)

`* * * * * /usr/bin/php /www_dev/httpdocs/mautic/app/console mautic:campaigns:trigger --env=prod`
`* * * * * /usr/bin/php /www_dev/httpdocs/mautic/app/console mautic:leadlists:update --env=prod`
`* * * * * /usr/bin/php /www_dev/httpdocs/mautic/app/console mautic:email:process --env=prod`

As for the `audit_log` here's the results for one of the Leads that has 3 entries now in Mautic.
**query**: SELECT  `id`,  `date_added`,  `user_id`,  `object_id`,  `action`,  `details`,  `ip_address` FROM `mautic`.`audit_log` WHERE object = 'lead' and object_id in (18041,22781,22804) order by date_added, id
**results**: (changed the email address and domain name so we don't reveal personal data here, I can send you a .csv or any other format if this is unusable formatted like that, I can also extract similar info for other duplicate leads if this doesn't reveal anything useful)
1.`"id","date_added","user_id","object_id","action","details","ip_address"`
2.`"72900","2015-04-25 19:12:34","0","18041","create","a:1:{s:11:""ipAddresses"";a:2:{i:0;s:0:"""";i:1;s:14:""79.186.193.232"";}}","79.186.193.232"`
3.`"72901","2015-04-25 19:12:34","0","18041","ipadded","s:14:""79.186.193.232"";","172.16.0.31"`
4.`"72917","2015-04-25 19:25:23","0","18041","update","a:2:{s:6:""fields"";a:5:{s:9:""firstname"";a:2:{i:0;N;i:1;s:6:""halina"";}s:5:""email"";a:2:{i:0;N;i:1;s:24:""halina.xxxxxxxxx30@wp.pl"";}s:16:""pochodzenieleada"";a:2:{i:0;N;i:1;s:11:""domainzz.tv"";}s:13:""grupadocelowa"";a:2:{i:0;N;i:1;s:2:""KK"";}s:11:""abtypepopap"";a:2:{i:0;N;i:1;s:1:""A"";}}s:14:""dateIdentified"";a:2:{i:0;s:0:"""";i:1;O:8:""DateTime"":3:{s:4:""date"";s:26:""2015-04-25 19:25:23.000000"";s:13:""timezone_type"";i:3;s:8:""timezone"";s:3:""UTC"";}}}","79.186.193.232"`
5.`"72918","2015-04-25 19:25:23","0","18041","identified","a:0:{}","79.186.193.232"`
6.`"72919","2015-04-25 19:26:01","0","18041","update","a:1:{s:6:""points"";a:2:{i:0;i:0;i:1;i:1;}}","127.0.0.1"`
7.`"72926","2015-04-25 19:30:19","0","18041","update","a:1:{s:6:""points"";a:2:{i:0;i:1;i:1;i:2;}}","79.186.193.232"`
8.`"72932","2015-04-25 19:34:21","3","18041","update","a:1:{s:6:""fields"";a:23:{s:5:""title"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""lastname"";a:2:{i:0;N;i:1;s:0:"""";}s:7:""company"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""position"";a:2:{i:0;N;i:1;s:0:"""";}s:5:""phone"";a:2:{i:0;N;i:1;s:0:"""";}s:6:""mobile"";a:2:{i:0;N;i:1;s:0:"""";}s:3:""fax"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""address1"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""address2"";a:2:{i:0;N;i:1;s:0:"""";}s:4:""city"";a:2:{i:0;N;i:1;s:0:"""";}s:5:""state"";a:2:{i:0;N;i:1;s:0:"""";}s:7:""zipcode"";a:2:{i:0;N;i:1;s:0:"""";}s:7:""country"";a:2:{i:0;N;i:1;s:0:"""";}s:7:""website"";a:2:{i:0;N;i:1;s:0:"""";}s:16:""zgodanawysylanie"";a:2:{i:0;N;i:1;s:1:""0"";}s:7:""twitter"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""facebook"";a:2:{i:0;N;i:1;s:0:"""";}s:10:""googleplus"";a:2:{i:0;N;i:1;s:0:"""";}s:5:""skype"";a:2:{i:0;N;i:1;s:0:"""";}s:9:""instagram"";a:2:{i:0;N;i:1;s:0:"""";}s:10:""foursquare"";a:2:{i:0;N;i:1;s:0:"""";}s:13:""specjalizacja"";a:2:{i:0;N;i:1;s:4:""brak"";}s:4:""plec"";a:2:{i:0;N;i:1;s:1:""k"";}}}","109.207.56.123"`
9.`"72943","2015-04-25 19:40:01","0","18041","update","a:1:{s:6:""points"";a:2:{i:0;i:3;i:1;i:4;}}","79.186.193.232"`
10.`"90506","2015-05-01 19:48:27","0","22781","create","a:1:{s:11:""ipAddresses"";a:2:{i:0;s:0:"""";i:1;s:12:""83.20.82.118"";}}","83.20.82.118"`
11.`"90507","2015-05-01 19:48:27","0","22781","ipadded","s:12:""83.20.82.118"";","172.16.0.31"`
12.`"90508","2015-05-01 19:48:27","0","22781","update","a:2:{s:11:""ipAddresses"";a:2:{i:0;s:0:"""";i:1;s:12:""83.20.82.118"";}s:6:""points"";a:2:{i:0;i:0;i:1;i:1;}}","83.20.82.118"`
13.`"90509","2015-05-01 19:48:27","0","22781","ipadded","s:12:""83.20.82.118"";","172.16.0.31"`
14.`"90510","2015-05-01 19:49:24","0","22781","update","a:2:{s:6:""fields"";a:5:{s:9:""firstname"";a:2:{i:0;N;i:1;s:6:""halina"";}s:5:""email"";a:2:{i:0;N;i:1;s:24:""halina.xxxxxxxxx30@wp.lp"";}s:16:""pochodzenieleada"";a:2:{i:0;N;i:1;s:11:""domainzz.tv"";}s:13:""grupadocelowa"";a:2:{i:0;N;i:1;s:2:""KK"";}s:11:""abtypepopap"";a:2:{i:0;N;i:1;s:1:""B"";}}s:14:""dateIdentified"";a:2:{i:0;s:0:"""";i:1;O:8:""DateTime"":3:{s:4:""date"";s:26:""2015-05-01 19:49:24.000000"";s:13:""timezone_type"";i:3;s:8:""timezone"";s:3:""UTC"";}}}","83.20.82.118"`
15.`"90511","2015-05-01 19:49:24","0","22781","identified","a:0:{}","83.20.82.118"`
16.`"90524","2015-05-01 19:52:01","0","22781","update","a:1:{s:6:""points"";a:2:{i:0;i:1;i:1;i:2;}}","127.0.0.1"`
17.`"90586","2015-05-01 20:05:15","0","18041","update","a:3:{s:11:""ipAddresses"";a:2:{i:0;s:0:"""";i:1;s:12:""83.20.82.118"";}s:6:""fields"";a:5:{s:9:""firstname"";a:2:{i:0;s:0:"""";i:1;s:6:""halina"";}s:5:""email"";a:2:{i:0;s:0:"""";i:1;s:24:""halina.xxxxxxxxx30@wp.pl"";}s:16:""pochodzenieleada"";a:2:{i:0;s:0:"""";i:1;s:11:""domainzz.tv"";}s:13:""grupadocelowa"";a:2:{i:0;s:0:"""";i:1;s:2:""KK"";}s:11:""abtypepopap"";a:2:{i:0;s:0:"""";i:1;s:1:""B"";}}s:6:""points"";a:2:{i:0;i:4;i:1;i:6;}}","83.20.82.118"`
18.`"90587","2015-05-01 20:05:15","0","18041","ipadded","s:12:""83.20.82.118"";","172.16.0.31"`
19.`"90596","2015-05-01 20:07:17","0","22804","create","a:4:{s:6:""points"";a:2:{i:0;i:0;i:1;d:3;}s:11:""ipAddresses"";a:2:{i:0;s:0:"""";i:1;s:12:""83.20.82.118"";}s:6:""fields"";a:5:{s:11:""abtypepopap"";a:2:{i:0;N;i:1;s:1:""B"";}s:13:""grupadocelowa"";a:2:{i:0;N;i:1;s:2:""KK"";}s:16:""pochodzenieleada"";a:2:{i:0;N;i:1;s:11:""domainzz.tv"";}s:9:""firstname"";a:2:{i:0;N;i:1;s:6:""halina"";}s:5:""email"";a:2:{i:0;N;i:1;s:24:""halina.xxxxxxxxx30@wp.pl"";}}s:14:""dateIdentified"";a:2:{i:0;s:0:"""";i:1;O:8:""DateTime"":3:{s:4:""date"";s:26:""2015-05-01 22:07:16.000000"";s:13:""timezone_type"";i:3;s:8:""timezone"";s:13:""Europe/Warsaw"";}}}","83.20.82.118"`
20.`"90597","2015-05-01 20:07:17","0","22804","identified","a:0:{}","83.20.82.118"`
21.`"90598","2015-05-01 20:07:17","0","22804","ipadded","s:12:""83.20.82.118"";","172.16.0.31"`
22.`"90619","2015-05-01 20:10:02","0","22804","update","a:1:{s:6:""points"";a:2:{i:0;i:3;i:1;i:4;}}","127.0.0.1"`
23.`"92342","2015-05-02 16:37:00","3","22804","update","a:1:{s:6:""fields"";a:23:{s:5:""title"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""lastname"";a:2:{i:0;N;i:1;s:0:"""";}s:7:""company"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""position"";a:2:{i:0;N;i:1;s:0:"""";}s:5:""phone"";a:2:{i:0;N;i:1;s:0:"""";}s:6:""mobile"";a:2:{i:0;N;i:1;s:0:"""";}s:3:""fax"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""address1"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""address2"";a:2:{i:0;N;i:1;s:0:"""";}s:4:""city"";a:2:{i:0;N;i:1;s:0:"""";}s:5:""state"";a:2:{i:0;N;i:1;s:0:"""";}s:7:""zipcode"";a:2:{i:0;N;i:1;s:0:"""";}s:7:""country"";a:2:{i:0;N;i:1;s:0:"""";}s:7:""website"";a:2:{i:0;N;i:1;s:0:"""";}s:16:""zgodanawysylanie"";a:2:{i:0;N;i:1;s:1:""0"";}s:7:""twitter"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""facebook"";a:2:{i:0;N;i:1;s:0:"""";}s:10:""googleplus"";a:2:{i:0;N;i:1;s:0:"""";}s:5:""skype"";a:2:{i:0;N;i:1;s:0:"""";}s:9:""instagram"";a:2:{i:0;N;i:1;s:0:"""";}s:10:""foursquare"";a:2:{i:0;N;i:1;s:0:"""";}s:13:""specjalizacja"";a:2:{i:0;N;i:1;s:4:""brak"";}s:4:""plec"";a:2:{i:0;N;i:1;s:1:""k"";}}}","109.207.56.123"`
24.`"92343","2015-05-02 16:37:21","3","22781","update","a:1:{s:6:""fields"";a:23:{s:5:""title"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""lastname"";a:2:{i:0;N;i:1;s:0:"""";}s:7:""company"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""position"";a:2:{i:0;N;i:1;s:0:"""";}s:5:""phone"";a:2:{i:0;N;i:1;s:0:"""";}s:6:""mobile"";a:2:{i:0;N;i:1;s:0:"""";}s:3:""fax"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""address1"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""address2"";a:2:{i:0;N;i:1;s:0:"""";}s:4:""city"";a:2:{i:0;N;i:1;s:0:"""";}s:5:""state"";a:2:{i:0;N;i:1;s:0:"""";}s:7:""zipcode"";a:2:{i:0;N;i:1;s:0:"""";}s:7:""country"";a:2:{i:0;N;i:1;s:0:"""";}s:7:""website"";a:2:{i:0;N;i:1;s:0:"""";}s:16:""zgodanawysylanie"";a:2:{i:0;N;i:1;s:1:""0"";}s:7:""twitter"";a:2:{i:0;N;i:1;s:0:"""";}s:8:""facebook"";a:2:{i:0;N;i:1;s:0:"""";}s:10:""googleplus"";a:2:{i:0;N;i:1;s:0:"""";}s:5:""skype"";a:2:{i:0;N;i:1;s:0:"""";}s:9:""instagram"";a:2:{i:0;N;i:1;s:0:"""";}s:10:""foursquare"";a:2:{i:0;N;i:1;s:0:"""";}s:13:""specjalizacja"";a:2:{i:0;N;i:1;s:4:""brak"";}s:4:""plec"";a:2:{i:0;N;i:1;s:1:""k"";}}}","109.207.56.123"`

**Comment by pitus** [comment]
I just realized that lead_id (object_id) 22804 has a slightly different email address ending with .pl while the other two end with .lp (typo of the user) ... so ignore the 22804 lead above.

**Comment by pitus** [comment]
Any chance that someone will look into this "Lead Duplication" issue soon?
We keep getting more and more duplicates and soon it'll be a nightmare to merge them or deal with the duplicates. Hoping you will be able to find a solution after all - I can supply you with any additional information you might need... just tell me what to check, where, and what to send you?

**Comment by pitus** [comment]
Are there any plans to look into this issue further?
At this point we have a database full of almost all leads duplicated and it's so annoying, we will be forced soon to look into another solution, unless this can be identified and fixed soon.

**Comment by pitus** [comment]
The status still shows "Pending Feedback" but I've already sent the requested info 15 days ago.

**Comment by alanhartless** [comment]
Hi @pitus,

Sorry about the delay.  Can you grab me a screenshot of your lead field list? Thinking through this, I'm wondering is if the email field is not marked as a "unique identifier" which is what Mautic uses to determine duplicates. There should be a key icon for the Email field.  Or, are there any keys for any of the other fields?

![](http://dvkrd.co/drop/2015-07-16_18-21-07.png)

If that turns out to be the case, how are you upgrading your Mautic installations? I remember reading that you weren't sure how Mautic hit 1.1.3dev which makes me think you're might be using a script hooked into Github to do it. In 1.0.4, we introduced the unique identifier and there was a migration file that should have auto-marked the email as being a unique identifier. So wondering if that got bypassed.

If email _is_ marked as a unique identifier, I couldn't really glean anything revealing from the log. What are the sources for your leads? I.e., form submissions, API, tracking pixel (using a CMS plugin or something custom)?

Thanks,
Alan

**Comment by alanhartless** [comment]
Sorry; just went back and reread everything and caught that the tracking pixel is used.  Check the unique identifier setting then I guess we'll go from there.  Tracking pixel created leads does use the unique identifier fields to determine if a lead already exists. If that is not set, that could very well be how the duplicates are getting created.
