### ISSUE TITLE
Contact import not working. 

### ISSUE THREAD

**Issue by leadtomarket** [mautic/mautic#5461]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Tried importing a list of 1893 contacts, but freezed and status changed to Manual.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.0-0
| PHP version | 7.0.23

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Bizcrony** [comment]
are you trying to import via CSV ?

**Comment by leadtomarket** [comment]
Yes, I found the error. There was a special character in the company column. Thanks.
