### ISSUE TITLE
Why use cron jobs and not use message queues to handle tasks

### ISSUE THREAD

**Issue by williamespindola** [mautic/mautic#5462]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
First of all, congratulations for the amazing job.
Why existis this cron jobs to handle maintenance tasks? Maybe this tasks could be queued and handled using some consumers. Ok, I know, to keep consumers running it must use some a cron job thing, but I think that keep some thing like this can be a more automated process instead run cron jobs for each task.

**Comment by dbhurley** [comment]
Cron jobs were chosen for core due to their ubiquity and ease of setup. I know of many larger companies and teams that are using queues to process their jobs instead of the crons.
