### ISSUE TITLE
Builder button displays DB name in settings

### ISSUE THREAD

**Issue by justinfortes** [mautic/mautic#5465]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | N/A

### Steps to reproduce:
1. Create a new email
2. Go to email builder
3. Add a button to the email
4. Click the button to edit its settings on the right panel
5. In the customize panel a field is displayed as "mautic.core.button.text"

FIx
Replace "mautic.core.button.text" with "Button Text"
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
Fixed with #5474
