### ISSUE TITLE
Rename company and contact keeps old company name on contact details

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#5466]
| Q  | A
| ---| ---
| Bug report? | 🔴 
| Feature request? | 
| Enhancement? | 

## Description:
When you rename a company, the company affected to the assigned contact keeps the old name.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 

### Steps to reproduce:
1. Create a company
2. Create a contact an assign it to the company
3. Edit the company and change the name of it
4. Check the contact and notice that in the side bar the company name label is ok.
5. Click on detail to see all contact fields and notice that the company fields still have the old name

![capture d ecran 2017-12-20 a 10 45 00](https://user-images.githubusercontent.com/14075239/34200977-500a40fa-e573-11e7-9097-42520152386b.png)

**Comment by npracht** [comment]
@kuzmany can you tell if on your M3 installation this is still an issue or not please ?

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
