### ISSUE TITLE
impossible to unsubscribe if email unread

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#5467]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
If your email is considered as unread, the user cannot unsubscribe from it even if he clicks on the unsubscribe link.

That can happen if you don't load images on the email which happens often in B2B with some email client (outlook for instance natively disables images).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 

### Steps to reproduce:
1. Send an email to user
2. Does not open it (call the tracking pixel)
3. Click on the unsubscribe link (from the email link in the contact timeline for instance, or get the hash in DB)
4. Notice that it does not unsubscribe the contact

**Comment by dbhurley** [comment]
Your description states that the *user* cannot unsubscribe *even if he clicks on the unsubscribe link* however your steps to reproduce don't offer any path whereby the *user* clicks a link to unsubscribe and is not allowed. Manipulating the DB to retrieve the hash, or the company/business owner/marketer clicking a link within Mautic. 

And I'm not sure I completely agree with the logic of unsubscribing without clicking the link within the email.

**Comment by npracht** [comment]
Hello @dbhurley !

You're right, i wanted to help to reproduce easier but then let me give steps for a standard case:

1. Send an email to a contact (yourself, you'll need to access to the email)
2. Open it with a client email that blocks images (consequently will not track the email pixel and will still consider the email as unread).
3. Click on the unsubscribe link
4. Notice that it does not unsubscribe your contact

**Comment by dbhurley** [comment]
Perfect, thank you.

**Comment by AndrassGray** [comment]
Clicking a link in an email should mark the email opened/read as well (in addition to the tracking pixel). Which isn't the case currently.

If Mautic would register a click as email-opened, then this issue here would disappear.

**Comment by npracht** [comment]
@kuzmany could you check if this is still relevant please ?

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
