### ISSUE TITLE
Abandoned cart campaign: can't see which contacts sucusessfully placed order

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#5468]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | y
| Enhancement? | y

## Description:
An interesting logic loop I have bumped into with abandoned cart campaigns: I have mautic hooked into prestashop, abandoned carts (with or without email) get added into "abandoned cart" segment and orders placed get added into "order placed" segment and removed from abandoned cart segment. A campaign with emails etc runs off the abandoned cart segment.

If an email is sent via the campaign to someone in abandoned cart segment, and they go on to place an order, there is no way to see who was the successful customer as they are removed from the segment and then the campaign right away. 

I can see in my email list that x% of people opened the email and x% of them clicked the link to go back to the cart, but mautic (unlike many traditional mailing list apps) does not tell you WHO those people were. Usually I would check in the segment, or campaign, but this dosn't work for this abandoned cart set up as they are removed.

I have been trying to work out a solution for this - maybe I can create a third list of something, but havn't figured it out yet. I think having specific details under the list of contacts who opened/clicked etc would be best :)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Closing due to incomplete report. Must have "Steps to Replicate" so others can fix test and fix this bug. Will reopen if these steps are added.

**Comment by gingerling** [comment]
Ok, I will fill this now

**Comment by gingerling** [comment]
Done @dbhurley please open, and note that this is an important feature request - it's part of the basic purpose of mautic that this kind of campaign is possible.
