### ISSUE TITLE
Update Bitnami Mautic from 2.10 to 2.12 on AWS EC2

### ISSUE THREAD

**Issue by leadtomarket** [mautic/mautic#5469]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
On the dashboard I clicked on update now. Steps: Downloading Package - Success; Extracting Package - Success; **Moving Package Contents - undefined** (why is this error?) I don't see updated version on  AWS marketplace either.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 7.0.23

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
I'm not sure this is a problem with core. I think you might be having a problem with Bitnami's version and I'd recommend checking with them to see if they have updated their package to the latest release.
