### ISSUE TITLE
OneSignal

### ISSUE THREAD

**Issue by skynet** [mautic/mautic#5471]
What is "Shared key for push notifications" in the OneSignal plugin setup?

**Comment by dbhurley** [comment]
Not trying to be rude, but not an issue. Please post in the forums (https://www.mautic.org/community) or ask in our Slack channels.

**Comment by skynet** [comment]
Only if someone actually responded. Maybe documentation needs to be updated?

**Comment by jsimoes** [comment]
Here you go @skynet 

482941778795

**Comment by heathdutton** [comment]
A tooltip would be good... Had no idea what this field meant or where to find the value. This thread was the first result.

**Comment by team6-crewnew** [comment]
@jsimoes what? just enter "482941778795" there? can't also find elsewhere information about it.

**Comment by e-stonia** [comment]
@jsimoes what? just enter "482941778795" there? can't also find elsewhere information about it.
