### ISSUE TITLE
Lead not syncing fields to SuiteCRM after being pushed

### ISSUE THREAD

**Issue by mfvetter** [mautic/mautic#5473]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | Y

## Description:
The current plugin shipped in Mautic is not fully syncing updated fields from Mautic to SuiteCRM. When selecting Mautic to be the system of record, updates on leads in Mautic should sync to SuiteCRM. Currently Mautic is only sending a new contact with the fields configured to be synced. Apparently there's no errors in there. But then if a field is updated in Mautic, let’s say the phone number from 123 to 456, it doesn’t sync that change to SuiteCRM. SuiteCRM keeps 123 and Mautic keeps 456. The way around (SuiteCRM to Mautic) seems to be updating the fields to Mautic, but Mautic to SuiteCRM is not.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 7.1
| SuiteCRM version | 7.9.8 

### Steps to reproduce:
1. Configuring the plugin SugarCRM.
2. Set fields to update SugarCRM < Mautic. (Mautic to SugarCRM)
3. Create a new lead and sync it to SuiteCRM.
4. Update one or more fields of the new lead in Mautic and try syncing it to SuiteCRM.
5. The updated field(s) in Mautic don't sync to SuiteCRM.

[This was also mentioned here.](https://github.com/mautic/mautic/pull/5244/#issuecomment-350087445)

Below is my config:
![screen shot 2017-12-07 at 12 11 30 pm](https://user-images.githubusercontent.com/7863521/34242272-21e5cfa6-e5e0-11e7-8b1d-7f867e9fedd9.png)
![screen shot 2017-12-07 at 12 11 30 pm](https://user-images.githubusercontent.com/7863521/34242287-2da99c46-e5e0-11e7-9494-15547b127b4b.png)
![screen shot 2017-12-07 at 12 12 30 pm](https://user-images.githubusercontent.com/7863521/34242289-3505b31c-e5e0-11e7-9b0c-878b362e911d.png)
The same setup of contacts I made for Leads as well.

**Comment by ChuckRenner** [comment]
I've been dealing with the same issue in 2.11.0
  
We currently do a points-based trigger to push to SuiteCRM.  There are times when this happens and Mautic has no actionable information.  If that user later does something that gives us info (i.e. fills out a form), subsequent triggered pushes do not update the fields inside of Suite.  The modification timestamp in Suite updates, but everything else remains unchanged. 

We are very eager to have a fix for this, so if you need further details, debug info, etc. let me know.

**Comment by ChuckRenner** [comment]
I've done some sniffing to see what is taking place between Mautic and SuiteCRM.  A new push to CRM sends the following:

`{"id":"78354169-2c6f-2fbd-4970-5a5fb5bfcbbf","entry_list":{"first_name":{"name":"first_name","value":"Fred"},"last_name":{"name":"last_name","value":"Flintstone"},"email1":{"name":"email1","value":"Unknown"},"lead_source":{"name":"lead_source","value":"Public Relations"}}}`

If I update the record in Mautic, and then trigger another push, I only see the following being sent:

`{"id":"78354169-2c6f-2fbd-4970-5a5fb5bfcbbf","entry_list":{"id":{"name":"id","value":"78354169-2c6f-2fbd-4970-5a5fb5bfcbbf"}}}`

Something in Mautic's logic is deciding that the updated fields don't need to be updated, so it isn't sending them.

**Comment by npracht** [comment]
Must be fixed by https://github.com/mautic/mautic/pull/6185
Merged in 2.14.1. Can you try ?
