### ISSUE TITLE
Send example isn't working

### ISSUE THREAD

**Issue by leadtomarket** [mautic/mautic#5475]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
My registered & verified email ID is info@leadtomarket.net, whenever I want to send example mail; the mail wont trigger but I get to see "info@leadtomarket.net: " on top corner. Any help

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10
| PHP version | 7.0

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
I'm not sure there is enough here for others to replicate your issue. Maybe you can reopen this issue if you can provide more specific details for how someone else could replicate the problem.
