### ISSUE TITLE
Error submitting form

### ISSUE THREAD

**Issue by aimran50** [mautic/mautic#5478]
What type of report is this:
Q
| ---| ---
| Bug report? | Bug

## Description:
Submitting a form shows an error. I have mautic and wordpress on two different servers.
## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.8.2
| PHP version | 

### Steps to reproduce:
1. Open this in IE: https://baltimore.binfer.com/download/
2. Fill the form and submit. Instead of showing a thank you message, the frame error is show,
 
### Log errors: 
This content can’t be shown in a frameThere is supposed to be some content here, but the publisher doesn’t allow it to be displayed in a frame. This is to help protect the security of any information you might enter into this site.Try thisOpen this in a new window

I also noticed an error in console log when the form loads up:
Loading failed for the <script> with source “https://miami.binfer.com/mautic/mautic/media/js/mautic-form.js”
It appears an extra 'mautic' keyword is being added in the url.

**Comment by Bizcrony** [comment]
What mautic version ? and where you integrate that form?

**Comment by aimran50** [comment]
I added the version in the description: Mautic version | 2.8.2
I also mentioned that mautic and wordpres are on two different servers. 

I used the wordpress plugin to setup Mautic. As you can see the form loads on the site but fails on submit.

Do you need any other details?

**Comment by aimran50** [comment]
Is Mautic production ready? I just started testing it few days ago and am finding problems with basic functions like integrating a sign-up form. Is this the right place to ask questions? I was unable to find a forum sign-up place on the mautic website.

**Comment by dbhurley** [comment]
You're using a version of Mautic that is extremely outdated. If you just started testing you should be using 2.12. There's absolutely no way you can be testing software properly by using a severely outdated version!

**Comment by aimran50** [comment]
I installed it from the bitnami using the WAMP stack module and that was version available. I thought it was the latest. 
Is it not recommended to install from Bitnami? 
If it yes, then how do I keep up with updates? From Bitnami website or Mautic website?

Thanks.
