### ISSUE TITLE
Forum broken, threads gone?

### ISSUE THREAD

**Issue by wucherpfennig** [mautic/mautic#5479]
Hi everyone

Grats to the new page. It is looking good!

(I know maybe this is the wrong place to write this but since the forum is not available...)

Sadly I just discovered that presumably half of the forum is gone and maybe some user accounts too???

For example my account "wucherpfennig" is now called https://www.mautic.org/mauticians/thiagovalentim/

In the news you said something about login & reset the password. Where should we do that? I am not able to find the link.

Any feedback is highly appreciated!

**Comment by Bizcrony** [comment]
[Register](http://mauticsupport.com/mautc.png)

If you already registered then you need to recover your password . Else sign up there a new one.

-Happy Automating

**Comment by wucherpfennig** [comment]
Login works, but still the threads are a mess. eg my threads are located here https://www.mautic.org/mauticians/thiagovalentim/forums/

**Comment by wucherpfennig** [comment]
And some replies are missing too. eg. there were at least 3 more replies on this thread https://www.mautic.org/topic/how-to-redirect-subdomain-keep-url-to-mautic-landingpage-url/

**Comment by wucherpfennig** [comment]
@dbhurley ?

**Comment by dbhurley** [comment]
Sorry, wrong place, not related to code. Slack would be better probably...but there is a fix on the forums coming too.
