### ISSUE TITLE
Push to Zoho error

### ISSUE THREAD

**Issue by robwent** [mautic/mautic#5485]
| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I have enabled the Zoho integration, authorised and mapped fields.

In a double opt-in campaign, I add a push to integration action and then test the form.

When running `mautic:campaigns:trigger` this error is reported in the console:

    [Symfony\Component\Debug\Exception\FatalThrowableError]
    Cannot use object of type Mautic\LeadBundle\Entity\Lead as array

In the logs:

    mautic.NOTICE: Symfony\Component\Debug\Exception\FatalThrowableError: Cannot use object of 
    type Mautic\LeadBundle\Entity\Lead as array (uncaught exception) at 
    /path/plugins/MauticCrmBundle/Integration/ZohoIntegration.php line 865 while running console 
    command `mautic:campaigns:trigger` [] []`

If I change this line https://github.com/mautic/mautic/blob/staging/plugins/MauticCrmBundle/Integration/ZohoIntegration.php#L865
to:

    $row              = $writer->row($lead->id);

Then the campaign action will successfully push the contact to Zoho leads.

I can create a pull request but I'm not sure how to write a test for something like this.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 5.6.32 / 7.0.26

### Steps to reproduce:
1.  Connect Zoho plugin
2.  Add push to integration action to a campaign
3. Test the campaign. Contact won't get pushed and an error message will be in the logs.

**Comment by dbhurley** [comment]
Write the PR. 👍

**Comment by robwent** [comment]
Closing this as it's fixed in https://github.com/mautic/mautic/pull/5291
