### ISSUE TITLE
Beginners bad luck or really badly developed/poorly tested product!

### ISSUE THREAD

**Issue by aimran50** [mautic/mautic#5487]
Sorry to be critical but its Friday and we had set high hopes on Mautic. 

So, I have reported three issues so far. Some were happily closed without waiting for verification. After upgrading to the latest version, as advised, the form issue has not been fixed. The forms fail to submit and shows error. You can easily reproduce the problem by going to https://baltimore.binfer.com/download and filling the form and watching the console log.

Read in issue #4005 that it could be CORS issue, so decided to add baltimore.binfer.com into whitelist domain in Configuration. Moment I clicked save this message showed. 
"The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator."

After posting this, am going to restart the server. If this crappiness continues, will just move to something else. May I advice that release fewer but solidly working/tested product. I understand this is opensource and is really awesome list of features but the quality is just sad.

**Comment by aimran50** [comment]
Update. I tried restarting the server but the Mautic server is dead! https://miami.binfer.com/mautic/

No idea where to look or what to fix.

**Comment by aimran50** [comment]
You removed the wrong part of the the title :-). Will not resolve the problem will it.
Being a software developer, you don't believe in bad luck do you? Some part of code has caused this problem not some act of supernatural.  We have spent over a week on trying to set things up and now Mautic has died. Any tips how to bring back the server up? What logs to look at what to change?

**Comment by aimran50** [comment]
Why do you keep closing the issues I raise? This seems very immature behavior. Instead of investigating or offering to help resolve you are just burying the issues. Don't you want to improve your product?

**Comment by aimran50** [comment]
Please don't censor my expression and defeat the purpose of openness. If you cannot take open criticism, then stop claiming to be open. The title is apt. The number of bugs and issues are clear indications of a badly developed/poorly tested this product. is Either help resolve the issues or set exceptions that this product is alpha class and not ready for serious production use. I change one setting and the app dies. How bad does it have to be?

**Comment by dbhurley** [comment]
We can take this offline if you like. Your issues do not conform to the proper reporting. They are not replicable. You have questions which would be better served asked elsewhere. Others have sought to help you as well.
