### ISSUE TITLE
Automatically sort emails by ID (Or creation date) not name

### ISSUE THREAD

**Issue by gingerling** [mautic/mautic#5490]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | n
| Feature request? | y
| Enhancement? | y

## Description:
Emails (etc) are sorted by name, alphabetically, rather than showing the most recent first - it would be more helpful and sensible to be ordered by ID, which would be generally most recent first, or some other similar thing like creation date going back or send date going back. This would mean that the emails that are most likely to require checking on are at the top of the list. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Closing in favor of #5248 - but please update the comments there if some element of this feature is not included in that issue.
