### ISSUE TITLE
mautic problem with ssl https

### ISSUE THREAD

**Issue by emyabdel** [mautic/mautic#5491]
What type of report is this:

| Q  | A
| y| ---
| Bug report? |  y
| Feature request? | 
| Enhancement? | 

## Description:
hi

mautic worked well for me until I installed cloudflare SSL (https) on my website, so the site works only with https now. After that mautic doesn't work.
I removed it and reinstall it with https protocol but I have the same problem and I can't log in even if user and pass are correct.

I think that there's a problem with mautic and https and I think the solution is to use SSL / HTTPS only on mautic. So I want to know how to force mautic to work only using SSL/https? or any other solution

before I used let's encrypt SSL for my site and mautic worked well. but when i moved to Cloudflare DNS and installed their certificate with 'full SSL' option for https the problem seems to be stated here

ps: I'm a newbie so if there's something to do I need steps

thanks a lot

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.12.0 
| PHP version |  7.0

### Steps to reproduce:
1. 
2.

**Comment by emyabdel** [comment]
any solution?

**Comment by dbhurley** [comment]
Unfortunately this isn’t a problem with Mautic but with your server configuration. I’d recommend asking this type of question in the forums or slack channel instead of reporting it as an issue here.
