### ISSUE TITLE
Unable to sent scheduled Reports

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#5493]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

Mautic sucessful schedule an report with mautic:reports:scheduler command, but this e-mail fail on mautic:emails:send

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 7.0

### Steps to reproduce:
1.  Schedule an Report on Mautic 2.12.0
2. See Log File
 
### Log errors: 

[2017-12-26 11:35:04] mautic.NOTICE: Swift_IoException: Unable to open file for reading [/var/www/html/app/../media/files/temp/2017-12-21_Alunos-o-Curso-de-Elementor-Essencial.csv] (uncaught exception) at /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []

**Comment by IADDIC** [comment]
Has there been any progress on this issue?  I have reports that will not email.  version 2.12.1

**Comment by npracht** [comment]
Also error here with mailjet queued

**Comment by Prodigitude** [comment]
When running "php app/console mautic:reports:scheduler" from the command line, I get the response "Scheduler has finished".  I think the uncaught exception from luizeof's error log is probably the same issue that is stated more specifically in my error.

**Comment by AlbanL74fr** [comment]
I get the same problem, with this error in my log
```
[2018-08-28 04:24:04] mautic.NOTICE: Swift_IoException: Unable to open file for reading [/var/www/web-mautic/app/../media/files/temp/2018-04-21_PajakPay-Abandoners-campaigns---All-Events.csv] (uncaught exception) at /var/www/web-mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php line 144 while running console command `mautic:emails:send` [] []
```

**Comment by AlbanL74fr** [comment]
I tried again with permission "777" and with the apache user, the problem persists. The report when exported is only 12ko so it's probably not a size issue as well.
Any one else knows how to fix this issue?

**Comment by Maxell92** [comment]
Can you check, if the path `/media/files/temp/` exists in you system? Mautic should create it, but maybe a permission issue?

**Comment by AlbanL74fr** [comment]
Hi @Maxell92 the folder `/media/files/temp/` already exists and the permissions are "777". I checked this folder and it's actually empty. Shouldn't the csv file be there, instead? 
Any suggestions of what else could be wrong?

**Comment by Maxell92** [comment]
I think it will be necessary to debug the code - if report is correctly saved to this path.

**Comment by arashsoheili** [comment]
We are seeing the same issue on 2.15 as well. Everyday the email:send is failing due to trying to find a report in files temp folder. The folder is writable.
`mautic.NOTICE: Swift_IoException: Unable to open file for reading [/var/www/html/nashotah/app/../media/files/temp/2019-05-30_All-Emails.csv]`

**Comment by 3ruce** [comment]
Same problem here...

**Comment by escopecz** [comment]
There are several different causes of this issue in the comments. 

- `Unable to open file for reading` looks like a file permission issue. Not a Mautic issue. At least I cannot reproduce it. The server user doesn't have permission to open the file.

- `The attachment filename parameter is required` is a bug and I found out it happens for the **Sendgrid - API** email transport. I'm working on a fix.

**Comment by 3ruce** [comment]
>Unable to open file for reading looks like a file permission issue. Not a Mautic issue. At least I cannot reproduce it. The server user doesn't have permission to open the file.

This was a problem with a plugin... all sorted on my sire...

**Comment by arashsoheili** [comment]
@escopecz You are right as file permissions was the issue but the correct permissions is not explained in the docs. Finally I set the entire web directory as ubuntu owner and www-data group. But then the log files, cache, spool and what's listed in UI for folder/file permission to group writable. Also then had to run the cron jobs as www-data user. That's finally what seemed to work well. But I think folder permission seem a bit tricky and I would suggest a section in docs. Thanks.

**Comment by escopecz** [comment]
@arashsoheili I totally agree. Although it's not actually a Mautic issue but server management issue. Someone would have to write docs for each OS, and each version. It's not an easy task. Feel free to [improve the docs](https://github.com/mautic/documentation#contributing-to-the-mautic-documentation). I don't consider myself a skilled sys admin so I could write docs on that topic.

I always use Google to find tutorials as the Mautic community is amazing :)  https://www.google.com/search?&q=mautic+ubuntu

I will leave this issue open because of the Sendgrid bug although the original report is just a server misconfiguration.

**Comment by escopecz** [comment]
Please test if https://github.com/mautic/mautic/pull/7720 solves this issue.

**Comment by npracht** [comment]
@luizeof could you please test #7720 ?
cc @IADDIC @Prodigitude !
