### ISSUE TITLE
Update issue from 2.11.0 to 2.12.0

### ISSUE THREAD

**Issue by AkkuFresh** [mautic/mautic#5496]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes|
| Feature request? | 
| Enhancement? | 

## Description:
The built in GUI update process is running more then a hour generating more then 20.000 AJAX request and finally is not finishing. The earlier GUI update process from 2.9 or 2.10 finished within a few seconds. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0|
| PHP version | 7.0.26|

### Steps to reproduce:
1. Install Mautic 2.11.0 (fresh install to the PHP 7.0 instance)
2. Run the GUI update process
3. Check AJAX requests with the developer tools in the Chrome Browser
 
### Log errors: 
There was empty server log and empty Mautic log, the screenshot show the issue
![2017-12-26_2107](https://user-images.githubusercontent.com/6353141/34364243-357e93ce-ea84-11e7-9655-f1d910ae13b6.png)

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by linuskom** [comment]
I get "Exactly Identical" issue when updating from 2.11.0 to 2.12.0.

Any solution found?

**Comment by AkkuFresh** [comment]
Possible workaround the issue by using this article:
[https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful](https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful)
from John Linart's blog in the following sequences, because of the issue is in the changing files area:

Do point **5. Try to update files manually** (using all, step 1 - 7), and
Do point **3. Try to run database migrations** (both item in sequence)
Do point **4. Try to update database schema** (both item in sequence).

The problem is, if you are in the shared hosting server, you can not use the console commands.
But, the most shared server can run cron jobs, and using usual cron commands, you can run commands on the PHP-CLI (Command line) interface, so in this way you can use the Mautic CLI also.
The syntax of using PHP-CLI from the cron job may be different from server to server, but it can be found in the hosting cron job description or you can ask your hosting provider.

Of course Mautic update can be much more easy and fast without this issue, so I would be happy if this bug would be handled. But, the above described method can temporary help.

**Comment by linuskom** [comment]
Thanks for your reply,

I am just wondering if we should wait for 2.12.1 release with a possible fix !!!
Because they have a beta release : 2.12.1-beta 
when you go to:  https://github.com/mautic/mautic/releases

**Comment by AkkuFresh** [comment]
The bug still exist on the update from 2.12.0 to 2.12.1 release.
And even the console type update fails also.
From CLI, following the article: [https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful](https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful)
CLI output:
Version 2.12.1 of Mautic is available for download. Please visit https://www.mautic.org/topic/2-12-1-released/ for more information.
To update, you can run 'php app/console mautic:update:apply' from the command line.
and running the 'php app/console mautic:update:apply' the output is a simple 'update abort'.

**Comment by Rikk03** [comment]
I have the same problem and have the following in server log.

[05/Jan/2018:22:00:44 +0000] "GET /upgrade/upgrade.php?task=moveBundles&updateState=undefined&_=1515189610212&mauticUserLastActive=19&mauticLastNotif$
xx.xxx.xxx.xx - - [05/Jan/2018:22:00:44 +0000] "GET /upgrade/installer HTTP/2.0" 200 689 "https://xx.xxxxx.com/s/update" "Mozilla/5.0 (Windows NT 10.0; Win64; x6$ (edited)

**Comment by Rikk03** [comment]
when trying to update from command line I get the following message, please note that there is no permission error via the mautic error log.

The Mautic update could not complete successfully because of the following error            : Could not extract the contents of the ZIP archive to the filesystem.


  [UnexpectedValueException]
  The stream or file "/srv/users/serverpilot/apps/data/public/app/logs/mautic
  _prod-2018-01-07.php" could not be opened: failed to open stream: Permissio
  n denied

**Comment by Bizcrony** [comment]
Have you tried with upgrade.php

**Comment by fgauttron** [comment]
When I upgrade to version 2.12.1, I have an error on the email_states table. I tried to force the update but the error is still present.

[2018-01-08 08:42:30] mautic.NOTICE: Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE email_stat_replies (     id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)',      stat_id INT NOT NULL,      date_replied DATETIME NOT NULL COMMENT '(DC2Type:datetime)',      message_id VARCHAR(255) NOT NULL,      INDEX IDX_11E9F6E09502F0B (stat_id),      INDEX email_replies (stat_id, message_id),      INDEX date_email_replied (date_replied),      PRIMARY KEY(id) ) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;':  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'email_stat_replies' already exists (uncaught exception) at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 49 while running console command `doctrine:migrations:migrate` [] []

**Comment by digitall-it** [comment]
Got same problem while updating to 2.12.1 in browser. on CLI, app console didn't find cached update data, resetting cached data didn't help, upgrade.php script resolved.

**Comment by ServicedCloud** [comment]
We are having the same problem, after update from 2.12.0 to 2.12.1 via ssh update, it says check logs for error. Then we see this "CREATE TABLE email_stat_replies ( id CHAR(36) NOT NULL COMMENT..."

**Comment by Bizcrony** [comment]
Its database migration issue in fact.

**Comment by ServicedCloud** [comment]
We have tried fresh installation on 2.12.0 then a new release comes up. We then update it to the latest version. The error occurred after the update (i have mentioned in my first post.)

**Comment by gladxjane** [comment]
I mean how to upgrade mautic automatically. 
I badly need your help guys.
thanks much
