### ISSUE TITLE
Can't update company fields by {send, pageviews}

### ISSUE THREAD

**Issue by chendwww** [mautic/mautic#5499]
Hi 

I'm need to Mautic, I tried to creating contacts and companies by {send, pageview} here is my code:

![company-field-missing3](https://user-images.githubusercontent.com/25785677/34379332-bc4679a6-eb35-11e7-90a7-8dac2c987770.png)

here is the setting the "d10" can be updated

![company-field-missing2](https://user-images.githubusercontent.com/25785677/34379704-83b83b0e-eb37-11e7-9381-bbc0a1b02be2.png)

and the info was sent to Muatic 

![company-field-missing4](https://user-images.githubusercontent.com/25785677/34379800-150c615c-eb38-11e7-9cde-8e6526eb470a.png)

However, In the company fields all the fields are empty except the company names was created successfully.

![company-field-missing5](https://user-images.githubusercontent.com/25785677/34379808-24646136-eb38-11e7-8b49-0cfffcdfcb17.png)

Can anyone help?

**Comment by kuzmany** [comment]
Working on it

**Comment by kuzmany** [comment]
Please let's test https://github.com/mautic/mautic/issues/5499

**Comment by mburamorde** [comment]
Does this also removes the problem that form submission with form-fields matched to an public updateable company field aren't correctly saved?

**Comment by escopecz** [comment]
Will be fixed in 2.13.0
