### ISSUE TITLE
Feature Suggestion: Social Media Management Integration

### ISSUE THREAD

**Issue by SolacetechInformationServices** [mautic/mautic#55]
So I'm promoting this platform as a great Open Source Social Media Manager. Problem is Mautic incorporates Social Media API's but doesn't push and measure. I think adding a feature that allows us to share Posts via Social Media would be key in this Social Media driven marketing world. If this diverges from Mautic's core beliefs, sorry but how great would it be If I could make Landing pages, forms, Email Campaigns AND Twitter campaigns. Please let me know if Mautic already does this and I just didn't see it yet, lol...

**Comment by MaxOnTheHill** [comment]
nice direction ... maturing into a complete publishing and lead management platform would indeed be pretty awesome.
Maybe build something like co-schedule

**Comment by RCheesley** [comment]
+1 from me, to be able to send out your social campaigns & track within Mautic, whether core or as a 3rd party add-on, would be really great.

**Comment by MaxOnTheHill** [comment]
and also re-introduce/implement matching of social media profiles to lead information (like email or other details) like @ https://websiteadvantage.com.au/Social-Profile-Search-Tool

**Comment by jordan8037310** [comment]
For those interested, it may be worthwhile to start with something like https://github.com/julien-c/Circular/ and integrate it as a plugin.
