### ISSUE TITLE
Error with SalesForce Integration Fetching Contatcs

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#5502]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

Salesforce integration do not fetch contacts

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 7.0

### Steps to reproduce:
1. Configure Salesforce Integration
2. Run: php /var/www/html/app/console mautic:integration:fetchleads --integration=Salesforce
 
### Log errors: 

Warning: array_intersect_key(): Argument #1 is not an array in /var/www/html/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php on line 2802
About 0 to update and about 3 to create/update

  [Doctrine\DBAL\Exception\SyntaxErrorException]
  An exception occurred while executing 'SELECT i.integration_entity_id, i.integration_entity, i.id, i.internal_entity_id,l. FROM integration_entity i INNER JOIN companies l ON l.id = i.
  internal_entity_id WHERE (i.integration = ?) AND (i.integration_entity = ?) AND (i.internal_entity = ?) AND ((i.integration_entity_id IS NOT NULL) AND (((i.last_sync_date IS NOT NULL)
  AND (l.date_modified > i.last_sync_date)) OR ((i.last_sync_date IS NULL) AND (l.date_modified IS NOT NULL) AND (l.date_modified > l.date_added)))) AND (l.companyname IS NOT NULL) AND (
  l.date_modified BETWEEN ? and ?) LIMIT 100' with params ["Salesforce", "Account", "company", "2017-12-28 13:31:18", "2017-12-28 13:46:18"]:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to u
  se near 'FROM integration_entity i INNER JOIN companies l ON l.id = i.internal_entity_id ' at line 1

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to u
  se near 'FROM integration_entity i INNER JOIN companies l ON l.id = i.internal_entity_id ' at line 1

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to u
  se near 'FROM integration_entity i INNER JOIN companies l ON l.id = i.internal_entity_id ' at line 1

**Comment by luizeof** [comment]
Running command with -vvv param:

Exception trace:
 () at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:90
 Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException() at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:128
 Doctrine\DBAL\DBALException::driverExceptionDuringQuery() at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:855
 Doctrine\DBAL\Connection->executeQuery() at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206
 Doctrine\DBAL\Query\QueryBuilder->execute() at /var/www/html/app/bundles/PluginBundle/Entity/IntegrationEntityRepository.php:286
 Mautic\PluginBundle\Entity\IntegrationEntityRepository->findLeadsToUpdate() at /var/www/html/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php:3138
 MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->getMauticRecordsToUpdate() at /var/www/html/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php:2876
 MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->pushCompanies() at /var/www/html/app/bundles/PluginBundle/Command/FetchLeadsCommand.php:260
 Mautic\PluginBundle\Command\FetchLeadsCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:891
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:202
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /var/www/html/app/console:41


  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to u
  se near 'FROM integration_entity i INNER JOIN companies l ON l.id = i.internal_entity_id ' at line 1

**Comment by npracht** [comment]
We face the same issue here

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Can you test https://github.com/mautic/mautic/pull/5763 ?

**Comment by kuzmany** [comment]
Label: Pending feedback

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by npracht** [comment]
The error is still here with the PR:
>[2018-03-19 10:09:04] mautic.NOTICE: Mautic\PluginBundle\Exception\ApiErrorException:  select Id,  from Account where isDeleted =            ^ ERROR at Row:1:Column:12 unexpected token: 'from' (uncaught exception) at /path/plugins/MauticCrmBundle/Api/SalesforceApi.php line 511 while running console command `mautic:integration:fetchleads` [] []

**Comment by kuzmany** [comment]
@npracht but this is different bug as reported above, how can I reproduce it? can you share your settings?

**Comment by npracht** [comment]
![capture d ecran 2018-03-19 a 11 30 59](https://user-images.githubusercontent.com/14075239/37590646-3f833214-2b69-11e8-9a17-6e5eaf79624d.png)
![capture d ecran 2018-03-19 a 11 31 06](https://user-images.githubusercontent.com/14075239/37590647-3f9bf150-2b69-11e8-8ac2-41bcc65b6e9b.png)
![capture d ecran 2018-03-19 a 11 31 14](https://user-images.githubusercontent.com/14075239/37590649-3fb2f9c2-2b69-11e8-934f-db0f84cedda5.png)

**Comment by npracht** [comment]
The error in the terminal:
```php
Updating/creating companies from Mautic to Salesforce


  [Mautic\PluginBundle\Exception\ApiErrorException]
  select Id,  from Account where isDeleted =
             ^
  ERROR at Row:1:Column:12
  unexpected token: 'from'


Exception trace:
 () at /path/plugins/MauticCrmBundle/Api/SalesforceApi.php:511
 MauticPlugin\MauticCrmBundle\Api\SalesforceApi->analyzeResponse() at /path/plugins/MauticCrmBundle/Api/SalesforceApi.php:66
 MauticPlugin\MauticCrmBundle\Api\SalesforceApi->request() at /path/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php:3160
 MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->getSalesforceAccountsByName() at /path/plugins/MauticCrmBundle/Integration/SalesforceIntegration.php:2836
 MauticPlugin\MauticCrmBundle\Integration\SalesforceIntegration->pushCompanies() at /path/app/bundles/PluginBundle/Command/FetchLeadsCommand.php:281
 Mautic\PluginBundle\Command\FetchLeadsCommand->execute() at /path/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /path/vendor/symfony/console/Application.php:891
 Symfony\Component\Console\Application->doRunCommand() at /path/vendor/symfony/console/Application.php:202
 Symfony\Component\Console\Application->doRun() at /path/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /path/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /home/atmt_docapost/docapost.automation.webmecanik.com/atmt_admin/mautic_command_CLI.php:62

mautic:integration:fetchleads [-i|--integration INTEGRATION] [-d|--start-date START-DATE] [-t|--end-date END-DATE] [--fetch-all] [-a|--time-interval [TIME-INTERVAL]] [-l|--limit [LIMIT]] [-f|--force] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>


 $fullCommand: Array
 $command: mautic:integration:fetchleads
 $arg: console mautic:integration:fetchleads --time-interval=120minutes --integration=Salesforce -vvv
 $ciblecallback: prod_fr_sig140
 $id:41
```

**Comment by kuzmany** [comment]
@npracht Can you retest without company matching field?
![image](https://user-images.githubusercontent.com/462477/38456054-55babb1c-3a80-11e8-8f5d-ce0ad3d856a5.png)

You have unchecked Account object, but Mautic try sync companies.
Send me to Slack also SalesForce access I would like reproduce that issue and fixed it.

**Comment by escopecz** [comment]
@npracht why was this added to 2.14.2? I can't see any link to a 2.14.2 PR.

**Comment by npracht** [comment]
Hm.. must be a mistake but I cannot explain why..sry

N.

**Comment by YosuCadilla** [comment]
Hi guys, what is the status of this issue?
I see it has WIP and BUG and it was added to 2.14.2 but then removed?

**Comment by npracht** [comment]
@YosuCadilla you still have the issue in 2.15.0 ?

**Comment by npracht** [comment]
Same question for @luizeof

**Comment by YosuCadilla** [comment]
We didn't dare to try, sorry.

**Comment by Anjana637** [comment]
Hi,
I have tried integration of Mautic with salesforce and i am not getting any error logs while testing manually(through standalone form). I am creating contact record in salesforce through mautic. I am successfully able to create the contact in mautic but it does not create any record in salesforce. For this, I am using sandbox account for enterprise edition. For the integration process, I have used these steps mentioned in the link below:

https://www.mautic.org/docs/en/plugins/salesforce.html

Also, I checked the system logs in mautic platform but no logs have been generated for the process.

Please let me know what is the issue and how to get the integration errors in the logs?
