### ISSUE TITLE
Mautic keep merging users without any Unique Identifier override

### ISSUE THREAD

**Issue by chendwww** [mautic/mautic#5504]
Hi, I'm new to Mautic, I just installed the contact tracking code in my website and send user info by send pageview code.

The contacts and companies are created in Mautic without any problem, but I found the contacts are keeping merging. I only use "user id" as the Unique Identifier and I check the system info, the merged contacts do have different "user ids" (the only Unique Identifier I set), the fingerprints are also different, so I don't know why Mautic keep merging my contacts.

Here is the screenshot, please check.

The First one, you can see the contact's old vaules was override by new values, but the only Unique Identifier userid is different, so why Mautic merged this contact? and you can see the device fingerprints are also different, so it were two different users. 

![merge3](https://user-images.githubusercontent.com/25785677/34436139-b9335d4e-eccd-11e7-92d8-16be287e23b6.png)

The second one is my Custom Field setting, you can see the only unqie identifer is "userid"

![merge5](https://user-images.githubusercontent.com/25785677/34436206-677ee206-ecce-11e7-86f6-2fcf3ab9ecee.png)

The 3rd one is my tracking settings, I only user device fingerprints when no cookies exsit, and the users have two different fingerprints, so they should not by merged 

![merge4](https://user-images.githubusercontent.com/25785677/34436228-94a18acc-ecce-11e7-9b11-3c8093264e4a.png)

Anyone can tell me what happend and how to fix it?

**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
I'm going to close this because it doesn't follow the right format for a bug report. It's listed more as a support ticket. If you want to list steps for someone else to reproduce then we can reopen and list as a bug.
