### ISSUE TITLE
Fields missing in Campaign Events Filter

### ISSUE THREAD

**Issue by toddviau** [mautic/mautic#5515]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | *
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...
Only Company fields appear on the drop-down list of the filter in a Campaign Events report. All other fields are missing. Columns and Group by lists are fine.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 5.6

### Steps to reproduce:
1. Go to Reports
2. Click +New
3. Change Data Source to Campaign Events
4. Click the Data tab
5. Click Add Filters
6. Click the drop-down under Column and only Company fields are present
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by johbuch** [comment]
I got the same issue in 2.12 with campaign event filters in report. But also if you choose another data type like emails.

**Comment by kuzmany** [comment]
Lets tests https://github.com/mautic/mautic/pull/5580
