### ISSUE TITLE
Campaign Conditions Not working correctly

### ISSUE THREAD

**Issue by rohit-techbit** [mautic/mautic#5523]
Hi,
![img_05012018_170626_0](https://user-images.githubusercontent.com/26213644/34608341-e39256b0-f23d-11e7-9c54-3b068a497f0f.png)

FLOW:
I have created one campaign and selected "Test-only" segment
in this segment there are two users only.
one is having transactiondate today
and another one is in past
I applied condition in campaign as posted in screenshot that transactiondate matches today
Now when campaign runs, it send the email to the contact that is having transaction date in past. but the contact having transaction date is today receives no email.
is this an issue in mautic or I am doing it wrong? Please look into this.

Thanks,
Rohit

**Comment by dbhurley** [comment]
This is a support request (otherwise, please fill out the bug report properly).
