### ISSUE TITLE
unsubscribe link on mautic

### ISSUE THREAD

**Issue by emyabdel** [mautic/mautic#5528]
hi

I made my email to send with mautic but I didn't find how to add unsubscribe to the email bottom. I found Unsubscribe Settings on preferences (be sure to use url placeholder where the unsubscribe url is set to be injected) but I don't understand which url I should put there and how to add this unsubscribe link to my emails. It could be stupid but I didn't find how. thanks

update:
I added {unsubscribe_text} | {webview_text} at the email bottom and now there's a unsubscribe link but when I click on it I got an empty page: Record not found.
perhaps I should change something on email preferences:
<a   href=   '| URL|'    >Unsubscribe   </a>    to no longer receive emails from us.
what should I put on Unsubscribe URL? 
(be sure to use url placeholder where the unsubscribe url is set to be injected)

**Comment by dbhurley** [comment]
Closing this issue as it's more of a support ticket (check out the [forums](https://www.mautic.org/forums) or [Slack](https://mautic.slack.com) for help). If you feel this is an issue with the actual code, please resubmit as a proper bug report.
