### ISSUE TITLE
Impossible to make a segment with a filter on customer field type select-multiple

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#5530]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Impossible to create a segment based on a value on a customer field select-multiple
No contacts appears.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.11

### Steps to reproduce:
To redo this problem

1) create a new custom field type select multiple
<img width="940" alt="capture d ecran 2018-01-05 a 19 06 54" src="https://user-images.githubusercontent.com/20974155/34637730-b03d4bc4-f2bc-11e7-9ca4-5acf7ff6341d.png">

2) Import a file to populate the database
<img width="541" alt="capture d ecran 2018-01-06 a 08 39 02" src="https://user-images.githubusercontent.com/20974155/34637750-1cf35eb6-f2bd-11e7-9fa3-edef790de29e.png">
 
3) The data are upload correct and a contact have the right info
<img width="585" alt="capture d ecran 2018-01-06 a 08 40 23" src="https://user-images.githubusercontent.com/20974155/34637776-75f57de6-f2bd-11e7-96ac-97f711a073ba.png">

 4) Make a segment with the criteria based on a select multiple
<img width="797" alt="capture d ecran 2018-01-06 a 08 41 31" src="https://user-images.githubusercontent.com/20974155/34637796-f0db85c8-f2bd-11e7-8029-73ced1c78ce1.png">

5) the results is no contacts but clear we have contacts accordind the criteria
<img width="999" alt="capture d ecran 2018-01-06 a 08 42 47" src="https://user-images.githubusercontent.com/20974155/34637799-0a3715c8-f2be-11e7-87b4-66e5efe8e181.png">

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by AndrassGray** [comment]
Seems to be the same as #3717 ?

**Comment by dbhurley** [comment]
Good catch. Closing as duplicate.
