### ISSUE TITLE
S3 plugin authentication method V4

### ISSUE THREAD

**Issue by robwent** [mautic/mautic#5531]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
New S3 regions only accept V4 authentication.

If your bucket is in one of the newer regions it doesn't work as the plugin seems to use the older V3 authentication to try and connect to it.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 5.6

### Steps to reproduce:
1. Create a new bucket in the London Region and then try and connect to it.
 
### Log errors: 

    [2018-01-08 10:46:07] mautic.CRITICAL: Uncaught PHP Exception 
    Aws\S3\Exception\InvalidRequestException: "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256." at /path/to/mautic/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/NamespaceExceptionFactory.php line 91 {"exception":"[object] (Aws\\S3\\Exception\\InvalidRequestException(code: 0): The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. at /path/to/mautic/vendor/aws/aws-sdk-php/src/Aws/Common/Exception/NamespaceExceptionFactory.php:91)"} []

**Comment by kurkowskik** [comment]
Same situation here, region: EU (Frankfurt).

**Comment by MohHeader** [comment]
So the current work around here is to create a bucket on old region ?
my question is,,, which region should I select ?

Thanks

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
