### ISSUE TITLE
Campaign with a Contact field value (field is type multi-liste) doesnt work

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#5537]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The campaign doesn^t work correctly if the field contains more than one elements in the list

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.11

### Steps to reproduce:
1. Create a multi-liste custom field
<img width="940" alt="capture d ecran 2018-01-05 a 19 06 54" src="https://user-images.githubusercontent.com/20974155/34693983-c8704e7a-f4c5-11e7-9083-503dd253b096.png">

2. create a csv file to populate the database
<img width="541" alt="capture d ecran 2018-01-06 a 08 39 02" src="https://user-images.githubusercontent.com/20974155/34694012-e56ba588-f4c5-11e7-9fd7-ff9548a84d7b.png">

3. Import this data in a segment

4. all the data are correct imported
<img width="654" alt="capture d ecran 2018-01-05 a 19 07 33" src="https://user-images.githubusercontent.com/20974155/34694069-18ada4e6-f4c6-11e7-9aee-566d37c98d44.png">

 5. Make a campaign with the segment imported and make a condition
<img width="555" alt="capture d ecran 2018-01-08 a 22 49 33" src="https://user-images.githubusercontent.com/20974155/34694139-4ffcf866-f4c6-11e7-872f-e7a61de3e0b1.png">

<img width="669" alt="capture d ecran 2018-01-08 a 22 49 42" src="https://user-images.githubusercontent.com/20974155/34694150-5630b416-f4c6-11e7-8411-367003cc422c.png">

6. Run the campaign and see just on contacts have change the stage. Is the one have one value.

<img width="1036" alt="capture d ecran 2018-01-08 a 22 51 23" src="https://user-images.githubusercontent.com/20974155/34694235-a260eab8-f4c6-11e7-95b2-94b415fd5278.png">

<img width="1028" alt="capture d ecran 2018-01-08 a 22 51 42" src="https://user-images.githubusercontent.com/20974155/34694247-a9e24b60-f4c6-11e7-9f46-b02eae1392c1.png">
<img width="1041" alt="capture d ecran 2018-01-08 a 22 52 07" src="https://user-images.githubusercontent.com/20974155/34694248-aa085e90-f4c6-11e7-87f2-f8f162388e74.png">

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/5551
