### ISSUE TITLE
OneSignal Error

### ISSUE THREAD

**Issue by miguelurtado** [mautic/mautic#5538]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version |  5.6.30

### Steps to reproduce:
1. Enable OneSignal
2. Acesses any tracking page
 
### Log errors: 

Undefined index: app_id in /app/bundles/NotificationBundle/Helper/NotificationHelper.php on line 116, referer: Any Landing Page

**Comment by dbhurley** [comment]
Did you add your API keys for OneSignal into your config?

**Comment by miguelurtado** [comment]
Yes, I added. But when I reload the OneSignal configuration page the settings are not shown.

**Comment by miguelurtado** [comment]
Acredito que esse erro log tenha relação com o Bug

`PHP Warning:  hash_equals(): Expected known_string to be a string, boolean given in /app/bundles/CoreBundle/Security/Cryptography/Cipher/Symmetric/OpenSSLCipher.php on line 59`

**Comment by miguelurtado** [comment]
Some information?

The Facebook plugin also does not save the data, from the same error in the file OpenSSLCipher.php on line 59

Thanks

**Comment by miguelurtado** [comment]
Helllo,

I update to PHP 7.0 and it Work.

Thanks
