### ISSUE TITLE
GDPR Preparation / Upgrade Guide

### ISSUE THREAD

**Issue by KonstantinCodes** [mautic/mautic#5539]
The GDPR will be enforced in a few months. Reference: https://www.eugdpr.org/

For EU users of mautic or users with websites available within the EU, it would be highly important to review the new regulation.

Is somebody looking into the task to make mautic compliant? And if so, is it possible to compile an upgrade guide?

**Comment by dbhurley** [comment]
This is a question for the Slack channels or the forums, not a bug report.

**Comment by KonstantinCodes** [comment]
@dbhurley It's not a bug report but a feature request

**Comment by gingerling** [comment]
Also very keen to know how mautic will meet this law, the ip tracking may be a bit illigal, not sure, anxiety making!

**Comment by vazo0810** [comment]
Very important feature request!

**Comment by iwantaspeaker** [comment]
+1 - Can someone confirm whether Mautic is GDPR compliant, or not. We in the EU cant take a chance on non compliant systems anymore. Not with fines of 20Million Euros or 4% of revenue, whichever is greater, being threatened.
BTW those fines are not just for us as the Data Controllers, but also for companies like yours (the Processors), who are non compliant after May 25th 2018.

**Comment by dbhurley** [comment]
:) What company are you referring to with "companies like yours"? I think you've missed something.

**Comment by dbhurley** [comment]
By May 25, Mautic code will be GDPR, it's up to you to use it correctly.

**Comment by dbhurley** [comment]
@gingerling It's not illegal unless you've received a "right to be forgotten" request and/or request for information from a contact that you fail to comply with. Or, if "the powers that be" deem your data storage to be too long, however, that's subjective to each business use-case.

**Comment by iwantaspeaker** [comment]
Thanks for getting back so quick.
I meant by "companies like yours", the owners of the Mautic software.

**Comment by dbhurley** [comment]
Then you should read the license agreement here: https://github.com/mautic/mautic/blob/staging/LICENSE.txt specifically look at line 3.

**Comment by iwantaspeaker** [comment]
Fair enough, I had wrongly assumed that Mautic was a privately owned company.

**Comment by dbhurley** [comment]
No problem, it's a confusing point for sure. ;)

**Comment by iwantaspeaker** [comment]
As far as I am aware, one of the key things with GDPR is giving the Data Owner the right to request for their data to be removed from the DB. However we need to keep basic name & Email for the purposes of making sure we dont contact these people in the future. Has this been considered and can you elaborate if so as to how we can delete the persons data but still keep the basics in some sort of Unsubscribe Group. ?

**Comment by dbhurley** [comment]
Good thoughts and part of the discussion. You should move it to Slack where we are having these discussions ongoing.

**Comment by gingerling** [comment]
Hi @dbhurley I am reading more about this and it is not the case, IP address counts as identifying personal information and consent must be gained before collecting and storing this. Piwik/Matomo allows for anonymisingt the IP address data but mautic dosn't offer this. Also turning off IP address tracking in Mautic dosn't stop it collecting the IP of every visitor to the site and do not track is ignored. Additionally, because the cookie leads to the user being identified in mautic, this also requires consent. I am currently 100% certain that Mautic is not GDPR compliant. I am writing all this up into a blog at the moment, but basically, I think my options are currently delete mautic or break the law.

**Comment by acheloos-m** [comment]
@gingerling well, if you just use the tracking function - so no asset downloads or MT landingpages which would track the IP - you could implement a solution, where the mautic js file and the js snippets for forms etc. respectively are only loaded, if the user has given consent. 

This would make Forms etc. unusable unless the user gives consent but that's the "some functionality can be limited" part of the most privacy declarations...

**Comment by gingerling** [comment]
Or mautic could simply anonymise IP address like other solutions, then consent for everything else can simply be built into the form itself. 

I don't feel like mautic user should be expected to do anything custom for this, all of the other software I'm using without exception has either finished a compliance module or is actively working on it with help from community.

**Comment by npracht** [comment]
@gingerling you can test that https://github.com/mautic/mautic/pull/6121
