### ISSUE TITLE
Unable to edit Email Templates

### ISSUE THREAD

**Issue by khrazy5150** [mautic/mautic#5541]
Mautic v.2.12.0
PHP 7.0.22

When attempting to create a new email using the Email Builder, the browser loads a blank page with an error 500 (unable to find resource): s/emails/builder/1?template=goldstar&_=1515575926810&mauticUserLastActive=1&mauticLastNotificationId=

**Comment by dbhurley** [comment]
Closing this due to improper bug report structure. Please include specific steps to replicate.

**Comment by khrazy5150** [comment]
To replicate:

Open the chrome developer tools and make sure the "Console" tab is selected. 
Log in to Mautic. On the side menu, click on Channels then Emails.
On the Emails Page, click "New" button.

You will notice an error 500 in the Chrome developer console like this:

https://mydomain/s/emails/builder/new_17cc0718d7b7c707ef3f748c9ce6c40564bfd0a5?template=blank&_=1515608170074&mauticUserLastActive=2&mauticLastNotificationId= 500 ()

However, the page still opens and you can make a selection. In my case I chose "New Template Email"

In the template page, I clicked "Goldstar" to highlight it and then clicked on "Select" button. When I did that, I got the EXACT SAME error as above.

Then when I clicked the "Builder" button, I get a blank page on the left page and control buttons on the right that do not work.

**Comment by datmt** [comment]
I have this problem too. Please help
