### ISSUE TITLE
Email Template and Builder Images Not Showing Up (302 Found --> 404)

### ISSUE THREAD

**Issue by stancel** [mautic/mautic#5549]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | No
| Enhancement? | No

## Description:
When trying to setup a new email template (Campaign or Segment) none of the images for any of the themes are loading. This is first evident with the thumbnails of each of the themes not loading, but if you click on the builder these images are not appearing there either.

 At first I thought this might be a permissions or incorrect ownership problem, but I checked and it was not. Upon opening Chrome's Developer Tools I could see that the initial request was correctly finding the image at https://mymauticinstall.com/themes/<THEME_NAME>/thumbnail.png, but that requesting was returning a HTTP 302 Found Redirect response to this https://mymauticinstall.com/index.php/themes/<THEME_NAME>/thumbnail.png which then returns a 404 response and the images do not display.

I double checked my Apache config to make sure nothing had changed there and it did not. I then took a look in the Mautic Git Repo to see if any of the .htaccess files had changed and maybe mine did not get changed as part of the update, but unfortunately that was not it either. I also double checked the Settings --> Configuration --> Site URL (in the UI and in the local.php file) to make sure that the URL was correct and did not have /index.php appended to the end, but it was just https://mymauticinstall.com. Any help would greatly be appreciated.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | PHP 7.0.22

### Steps to reproduce:
1. Navigate to Channels --> Emails --> Click New
2. Choose either option (Template or Segment Email) 
3) Observe that the Theme thumbnails are blank and do not load any images
4) Choose one (besides Blank) and click the 'Builder' button
5) Notice that the images are not being loaded there either
6) Open Developer Tools in your browser and do a hard refresh
7) Notice that the images are being found then redirected to a URL that returns a 404
 
### Log errors: 

# Mautic Log
[2018-01-11 16:18:47] mautic.WARNING: IP LOOKUP: Error opening database file (/var/www/html/app/cache/prod/../ip_data/GeoLite2-City.mmdb). Is this a valid MaxMind DB file? [] []

# Apache Errors
None

# Apache Access Log Snippet
IP REMOVED - - [11/Jan/2018:16:30:15 +0000] "GET /themes/aurora/thumbnail.png HTTP/1.1" 302 700 "https://mymauticinstall.com/index.php/s/emails/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
IP REMOVED - - [11/Jan/2018:16:30:15 +0000] "GET /index.php/themes/aurora/thumbnail.png HTTP/1.1" 404 61157 "https://mymauticinstall.com/index.php/s/emails/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

**Comment by dbhurley** [comment]
Did you update to 2.11 and this was not a problem until you upgraded?

**Comment by dbhurley** [comment]
Did any configuration changes occur on your webhost? Normally you are correct, your .htaccess should be removing the /index.php/ from your URL.

**Comment by stancel** [comment]
Hi @dbhurley, 

I did upgrade from 2.10 to to 2.11 but did not check the emails themes in 2.11. More recently I upgraded to 2.12.1 and noticed the issue then. This was working in 2.10 and no other configuration changes were made to the server. Running on DigitalOcean droplet and I am the only one with server access.

**Comment by stancel** [comment]
I commented out the below line in the .htaccess file that was rewriting the image URL and it worked again.

`RedirectMatch 302 ^(?!/(index\.php|index_dev\.php|app|addons|plugins|media|upgrade))(/(.*))$ /index.php$2`

I then uncommented that line, disabled and re-enabled the Apache Mod Rewrite module, checked again and the images were loading correctly. Just to be sure, I cleared the prod cache and checked with Chrome's Developer Tools that all is well. 

Not sure what was the root cause of the issue but all seems to be working well now. Going to close this issue. Thanks for your time and response @dbhurley.

**Comment by MagnusTapping** [comment]
I've just fixed it by adding |themes| into the .htaccess RedirectMatch as above.

How it was supposed to work without that I don't know.

**Comment by eddiecsilva** [comment]
I had this problem on a clean installation of the latest version of Mautic. 
I solved my problem using the @MagnusTapping tip just above.

**Comment by myster-t** [comment]
i think the issue here was not having the apache2 rewrite mod enabled. for future ppl who stumble across this thread, try `sudo a2enmod rewrite` and `sudo systemctl restart apache2`

**Comment by aaronesteban1** [comment]
I've tried your guy's steps, but I'm actually using NGINX which is faster loading than Apache. So I'm not sure what is causing this. I've tried to edit the .htaccess file as mentioned above to no avail. It could be an issue in my NGINX server block.

**Comment by mreall** [comment]
@aaronesteban1 I had the same issue on nginx. When I looked at Settings > Configuration > System Settings > General Settings > Site URL, I noticed that "/index.php" had been added to the end of my URL.  I removed that and the images started appearing.  So far the site is still working for me, but I don't know if that will have other repercussions.

**Comment by aaronesteban1** [comment]
> @aaronesteban1 I had the same issue on nginx. When I looked at Settings > Configuration > System Settings > General Settings > Site URL, I noticed that "/index.php" had been added to the end of my URL. I removed that and the images started appearing. So far the site is still working for me, but I don't know if that will have other repercussions.

YES! YOU WERE ABSOLUTELY RIGHT! THANK YOU SO MUCH BROTHER!
