### ISSUE TITLE
site visit are not recorded (even with private browsing)

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#5550]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  yes
| Feature request? |  no
| Enhancement? | no

## Description:
fresh install of mautic 2.12.1 with new database will not record any visits using tracking pixel or javascript.  I can visit the tracking pixel in incognito/private browswer, but it will not log any visits when I refresh the campaign dashboard.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.27

### Steps to reproduce:
1. install fresh copy of mautic 2.12.1
2. open Chrome incognito or Firefox Private window and browse to .../mautic/mtracking.gif Tracking gif exists and shows in browser with no 404 error.
3. mautic dashboard does not show any visitors, even after manually refreshing the dashboard.
 
### Log errors: 

nothing specifically after tracking pixel is accessed.  But maybe some entries from another bug #5544 can help

**Comment by 4evermaat** [comment]
@dbhurley or anyone, can you elaborate on why this bug exists?  This is a pretty basic feature of mautic.

**Comment by 4evermaat** [comment]
Ok.  I don't know if this is an independent bug or related.  I noticed that mautic loads the dashboard only to the date of installation (10 Jan 2018).  It does not refresh to the current date (15 Jan 2018).  When I did this, I started to see several anonymous visits from a few days ago.  So the dashboard needs to refresh to the current date + 29/30/31 days prior.

Also, is the dashboard supposed to refresh every xx minutes?  Or does the user have to refresh the dashboard manually?  Should there be a button on the dashboard to refresh, or do I just do a browser refresh?

**Comment by AndrassGray** [comment]
@4evermaat : The "Apply" button on top of your dashboard triggers the refresh.

**Comment by RCheesley** [comment]
I can confirm this issue - the dashboard data is not refreshing until I manually hit 'apply'.  

As an end user I would expect this data to refresh at least on log in, or when I hard-refresh the page (and maybe even periodically with a cron or if I set it to refresh every 30 minutes, once a day etc in the UI?)

**Comment by afonseca08** [comment]
I can confirm this bug as a new user to Mautic with a fresh install from Softaculous. Mautic 2.12.1, PHP 5.6.33. I am using the Mautic WordPress plugin to insert the js tracking code onto the site pages with the gif as fallback option enabled.

I also tested with incognito in two different browsers and can confirm the js script appears on the page. I tried both header and footer positions and show no js errors in the console. I also tried manually loading the gif image and it loads without error. I also see Mautic cookies are created in the browser.

However, the dashboard Visits widget does not show any visits. The date range has been set to this week and refreshed several times with no data showing for today.

Interestingly, in the Recent Activity widget I do see a new lead was added, created, and updated with my IP address. So some of the code must be working but this is definitely an open issue that hopefully can get prioritized for timely review.

**Comment by afonseca08** [comment]
It turns out I was wrong, the tracking is working but wasn't showing up for me due to issue #4709. I have added the details there in case someone stumbles across this as well as it was a bit tricky to figure out.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
