### ISSUE TITLE
Not able to install Mautic on swisscom server

### ISSUE THREAD

**Issue by rizwanmindcrew** [mautic/mautic#5554]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
I am Installing mautic on swisscom server but its not installing and giving me some error. Can you please help me for this.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Bizcrony** [comment]
what error given ,, can you screenshot please

**Comment by rizwanmindcrew** [comment]
its giving database connection error while I tried to check connection directly at the root of the app so its getting connect but not in mautic. Mautic is working fine on my local machine. I changed db credentials under app/config/local.php file and pushed my code onto the server. 
Can you please let me know where to put db credentials in mautic. I am very newbie to mautic. 
Which file is responsible for database connection?

**Comment by escopecz** [comment]
The DB credentials are in app/config/local.php. Clear the app/cache every time you change some value there though. 

I'll close this issue since database connection error is not a Mautic bug.
