### ISSUE TITLE
issue with company field in forms

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5556]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When creating a form with a select company field, 
![image](https://user-images.githubusercontent.com/31535432/34866866-550c6476-f77e-11e7-9eb8-47908692d734.png)
then filling the form, the values of the select company field don't appear.
![image](https://user-images.githubusercontent.com/31535432/34866923-8e96d33e-f77e-11e7-83a3-523791c116f1.png)
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 

### Steps to reproduce:
1. Create a new company custom field and choose select as type
2. Create a new form
3. Add this new company field previously created (a select type)
4. Fill the form
5. You'll see that for the company field, there are no values displayed
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Confirmed. 
Work in progress.

**Comment by kuzmany** [comment]
Let's test https://github.com/mautic/mautic/pull/5567

**Comment by alanhartless** [comment]
Fixed in 2.12.2 beta
