### ISSUE TITLE
Analytics script code is not saved (landing page settings)

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#5559]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
I try to enter some analytics scripts from different providers (e.g. google analytics, statcounter, clicky, etc) and it is not saved.  No error messages in mautic error log or server error logs.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.27

### Steps to reproduce:
1. Login to mautic and go to configuration >> Landing Page settings
2. enter in any text into the Analytics script textarea box.
![mautic cannot save landing page analytics](https://user-images.githubusercontent.com/830306/34874121-5a5430c0-f7ca-11e7-9420-9090af4b78d4.png)

3. Attempt to apply the settings.   The box will be empty when you go back to revisit the Landing page settings.
 
### Log errors: 

[none]

**Comment by 4evermaat** [comment]
@escopecz could you elaborate what was causing the error?

Also, I noticed that after pressing apply, it will return to the configuration home page.   But actually i would like to see it just remain on the same page (just refresh that same page/tab) so that I can verify that the changes were actually saved on the last thing I was attempting to update.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/5577

I can imagine you'd prefer to have the last config tab open. Me too. But it would require to rewrite the whole config form code. Which will come. Just a matter of priorities.

**Comment by alanhartless** [comment]
Fixed in 2.12.2 beta

**Comment by 4evermaat** [comment]
Is there a list of changes for 2.12.2 beta?
