### ISSUE TITLE
Sparkpost Bounce Webook generate error

### ISSUE THREAD

**Issue by namankumar** [mautic/mautic#5561]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
I can send email using Sparkpost successfully however the Bounce callback is not working. I know I've setup the bounce hook correctly because I can successfully send a test packed from Sparkpost to Mautic. Below is the error response returned by Mautic. Is the error "`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead" ?

Thanks.

```

HTTP/1.1 200
Cache-Control: no-cache
Content-Type: application/json
Date: Fri, 12 Jan 2018 17:36:09 GMT
Server: Apache
Set-Cookie: 6a80bb98c1c323d2be7eff9b86d393db=1p52vnghrm65u38rqn6uq69h40; path=/; secure; HttpOnly
Vary: User-Agent
Content-Length: 402
Connection: Close

{"errors":[{"message":"Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!","code":404,"type":null}],"error":{"message":"Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)","code":404}}

```

| Q   | A
| --- | ---
| Mautic version | 2.12.1

### Steps to reproduce:
1. Send test packet from Sparkpost to Mautic www.eee.com/mailer/sparkpost/callback.

**Comment by npracht** [comment]
Hello @namankumar can you test https://github.com/mautic/mautic/pull/7015 and say if it solves your issue ?
Thanks !

**Comment by namankumar** [comment]
Sparkpost transport was fixed a few months ago. It has been working fine for me for a few months. Definitely since 2.13, maybe even before that as well. 

Amazon SES bounce back never worked for me but I don't use it anymore and don't have an environment to test it.

**Comment by dsp76** [comment]
@npracht  with that patch applied, my Sparkpost API Callback is working.
