### ISSUE TITLE
Bounces doesn't work

### ISSUE THREAD

**Issue by emyabdel** [mautic/mautic#5563]
hi

I created a segment: bounced email and I give it this filter: bounced emails equals yes
I also have the mautic:email:fetch cron job running
and Custom return path (bounce) address: bounces@mydomaine.com

I have 2 problems:
I receive bounces on the E-mail address that i send emails from and not on the bounces email that I've created: Custom return path (bounce) address: bounces@mydomaine.com

The second problem is that the bounced email segment that I've created is always empty even if I receive bounces (I run also a cron job to update segments and it works because my  Unsubscribed segment is always updated.

thanks

**Comment by dbhurley** [comment]
Please submit issues in the proper format. Alternatively, get support for specific issues in the forums or slack channels.
