### ISSUE TITLE
How to send pending mails via CLI?

### ISSUE THREAD

**Issue by leowebguy** [mautic/mautic#5564]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
I had a segment with 313 emails (already sent);
I imported 28 new emails into this same segment (screen shot, https://cl.ly/oo3P)
I can't figure out how to send those pending emails using mautic console;
Already tried app/console mautic:emails:send and app/console mautic:queue:process none of these seems to send the remaining contacts nor change the pending number from 28;

> Mautic is set to queue and I'm using Amazon SES;
> Works fine when I go to Channels > Emails > Send;

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.12.2-dev
| PHP version | PHP 7.1.12

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mMuck** [comment]
If I didn't misunderstood something, the email queue (the commands you mentioned refer to this) has nothing to do with the pending state of a segment mail. The email queue is a queued transport at the email sending system. Right?
Could someone please clarify this.
If I'm right, this is no bug. Your question remains: How to send pending mails via CLI? Why do you need this? Automated contact imports?

**Comment by leowebguy** [comment]
@mMuck you're right. 
The right questions would be ... How to send pending mails via CLI?
I have an automated contact import process that add contacts to a segment that is also set with a channel>email so I'd like to have a CLI command to trigger the channel>email and send those pending leads to queue.

**Comment by npracht** [comment]
Hello @leowebguy 
If you want to send segment email via CLI, you must:

1. set the publish date of the email (date where you want your pending emails to be sent)
2. set the command `php /path/to/mautic/app/console mautic:broadcasts:send [--id=ID] [--channel=CHANNEL]` (see https://mautic.org/docs/en/setup/cron_jobs.html)

The emails will be automatically sent after the published date set.

**Comment by dbhurley** [comment]
Support not bug :) Closing this issue.
