### ISSUE TITLE
tawk.to integration

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#5568]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | NO
| Feature request? | YES
| Enhancement? | NO

## Description:
Request integration with [tawk.to](https://tawk.to) live chat and support app.  It is a free live chat software and also includes ticketing system and unlimited agents. One of their paid option to have live help (human assist) for $1/hr. 

I've requested this on their side as well:  https://tawk.uservoice.com/forums/228427-feedback/suggestions/32882143-allow-integration-with-mautic

**Comment by dbhurley** [comment]
Currently we're not handling 3rd party integration feature requests through GitHub. Better to post in the #marketplace channel on Slack or in the forums.

**Comment by 4evermaat** [comment]
ok.  Can you link to the #marketplace or the forum that you speak of?
