### ISSUE TITLE
Campaign with more one Condition based on a contact field value. (multi-liste) doesn't work

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#5569]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | NO
| Enhancement? | NO

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Create a multi-liste custom field
<img width="940" alt="capture d ecran 2018-01-05 a 19 06 54" src="https://user-images.githubusercontent.com/20974155/34693983-c8704e7a-f4c5-11e7-9083-503dd253b096.png">

2. create a csv file to populate the database
<img width="541" alt="capture d ecran 2018-01-06 a 08 39 02" src="https://user-images.githubusercontent.com/20974155/34694012-e56ba588-f4c5-11e7-9fd7-ff9548a84d7b.png">

3. Import this data in a segment

4. all the data are correct imported
<img width="654" alt="capture d ecran 2018-01-05 a 19 07 33" src="https://user-images.githubusercontent.com/20974155/34694069-18ada4e6-f4c6-11e7-9aee-566d37c98d44.png">

5. make new stage items

<img width="1047" alt="capture d ecran 2018-01-15 a 08 34 44" src="https://user-images.githubusercontent.com/20974155/34931412-f8cb89c8-f9ce-11e7-908b-2f60ecdbd73d.png">

 5. Make a campaign with the segment imported and make a condition
<img width="1081" alt="capture d ecran 2018-01-15 a 08 33 14" src="https://user-images.githubusercontent.com/20974155/34931439-19ba9b7e-f9cf-11e7-94e8-36426bf6e3f3.png">

<img width="669" alt="capture d ecran 2018-01-08 a 22 49 42" src="https://user-images.githubusercontent.com/20974155/34694150-5630b416-f4c6-11e7-8411-367003cc422c.png">

6. Run the campaign and see just the contacts With Velo=3 have change. 

<img width="1048" alt="capture d ecran 2018-01-15 a 08 36 51" src="https://user-images.githubusercontent.com/20974155/34931502-74010866-f9cf-11e7-9d14-b27d7bc177a1.png">

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Unsure how this differs from the other issue you've also listed. If its different than #5570 please include a proper description and reopen the issue
