### ISSUE TITLE
When sending an email to user from an action, the template tags are not being replaced

### ISSUE THREAD

**Issue by terzano** [mautic/mautic#557]
After upgrading from 1.0.5 -> 1.1.2, the template tags from an action to a user are not being replaced 
(email.send.user). The email to the lead is fine but the one to the user is incorrect. 

The email I receive has the template tags: ie. 
Hello { FirstName }, ......

**Comment by alanhartless** [comment]
What mail transport are you using? I.e. PHP Mail, Mandrill, etc?

**Comment by terzano** [comment]
Amazon SES
