### ISSUE TITLE
500 Internal server error inside bundles folder

### ISSUE THREAD

**Issue by rizwanmindcrew** [mautic/mautic#5571]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
I have installed fresh mautic 2.12.1 on swisscom server. Setup installed successfully but i am getting multiple 500 Internal Server Error under bundle folder. I think this is due to .htaccess to I make it "allow from all". Please suggest what type of error is this. I am also not getting any favi icons.
Please help me for this. 
![screenshot_19](https://user-images.githubusercontent.com/25545748/34936435-5c790760-fa07-11e7-9143-e3c8a2e93115.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Not replicable, but usually this comes from improper permissions, double check ownership on the files on the server.
