### ISSUE TITLE
Mautic AWS Serverless Support #FeatureRequest

### ISSUE THREAD

**Issue by manuelfink** [mautic/mautic#5573]
Hello Mautic Team,

Have you ever considered making a serverless version of mautic? Eg. hosted on AWS using api gateway, lambda, ses, ...? Especially for private users or smaller businesses this would allow: 

* Scalability
* Low Budget / Pay as you go
* Easier maintenance while not being forced to run on shared environment or paying for additional servers.

**Comment by ortegoncarlos** [comment]
this would be awsome
