### ISSUE TITLE
Dynamic content based on campaigns not displaying

### ISSUE THREAD

**Issue by RPalmer157** [mautic/mautic#5584]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | n
| Enhancement? | n

## Description:
When trying to use dynamic content, tied to a campaign based on a segment, on a landing page, MauticJS.replaceDynamicContent never fires so the content never gets updated. The only way I could get it to work is if I added the following script to the bottom of the landing page(hacked from the tracking object )
`    (function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
        w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)}
    })(window,document,'','','mt');
    mt('send','pageview');`
Then the content displays as expected but then the contact record gets dinged twice with a page hit .
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11.0
| PHP version | 7.0.26

### Steps to reproduce:
1. Set up a campaign based on a segment add a piece of dynamic content
2. Setup a landing page with a dwc slot using the same slotname as the campaign.
3. With a contact that is setup to be part of that segment, visit the page. 
4. Wait for nothing to happen.
5. Add the script to the bottom of the landing page.
6. Reload the landing page, wait... and tada! the the content is updated.
7. Look at the contact in the admin panel and the page hit registers twice.  

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi,

Are you logged into the application at the same time as your tests ? The traking is not working the same way if you are logged.
I just tested and it is working properly.
