### ISSUE TITLE
Dashboard stats date not refreshing properly.....

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#5585]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | NO 
| Enhancement? |  NO

## Description:
Mautic Dashboard does not refresh stats to current timestamp at time of refresh.  The dashboard is stuck on stale dashboard info.  **Possibly related to #5550**.  In fact, it could be mautic is "seeing" the visit, but it is not refreshing to the dashboard or recording it properly.

![mautic dashboard not refreshing to current refresh date](https://user-images.githubusercontent.com/830306/34975895-8b3ba9a8-fac6-11e7-9881-abf13d3f512b.png)

## If a bug: 

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.27

### Steps to reproduce:
1. login to mautic or refresh dashboard page.
2. take screenshot or notice of the date range next to `Apply` button and the date range of the stats on the page.
3. wait until later the same day or a day or two.
4. refresh the dashboard (or logout-login)
5. The dashboard stats will not update to reflect the most recent stats as of last refresh.
 
### Log errors: 
[none]

---
I think I've narrowed down to 4 possibilities:
1. the JS code or `mtracking.gif` is not loading properly.   [Unlikely because the tracking pixel loads with no 404 error.  the js code is unchanged since earlier mautic versions]
2. tracking is served correctly, mautic is not storing the visitor info properly.  
3. mautic is storing visitor info, but dashboard is not updating to latest browser/ajax refresh timestamp
4. possible sync issue between browser computer time vs server time vs mautic time preferences.  My mautic time preferences and local computer time are both on UTC +7.

**Comment by KonstantinCodes** [comment]
This still applies

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
