### ISSUE TITLE
[Feature] Option to change Region for Amazon SES

### ISSUE THREAD

**Issue by onlineth** [mautic/mautic#559]
It would be nice if in the "Service to send mail through" section under Mail Settings, for the Amazon SES service, being able to change it's region from either US West, US East, or EU. The only thing that differs each region apart is its SMTP Host,
US West: email-smtp.us-west-2.amazonaws.com
US East: email-smtp.us-east-1.amazonaws.com
EU: email-smtp.eu-west-1.amazonaws.com

**Comment by alanhartless** [comment]
Until we can provide this option, the work around would be to use the Other SMTP as the mailer and fill in the details manually using the desired region as the host.

Thanks!
Alan

**Comment by nithinga** [comment]
@onlineth and @alanhartless PR for this feature request https://github.com/mautic/mautic/pull/1619

**Comment by onlineth** [comment]
@nithinga Sweet, I'll close this issue when the PR is approved

**Comment by onlineth** [comment]
Great, PR went through, thanks again guys!
