### ISSUE TITLE
Create a/b test link without create page permissions

### ISSUE THREAD

**Issue by jsolam** [mautic/mautic#5590]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0

### Steps to reproduce:
1. Create a profile without create page permissions
2. Enter into page created view page and note that "Create A/B Test" appears and it not appears in actions selector.
3. When click in the link, my network returns a 403 error but any message appears in the screen.
 
### Possible solution:

app/bundles/PageBundle/Views/Page/details.html.php -> line 213
"**elseif ($allowAbTest  && $permissions['page:pages:create'] ):**" instead "**elseif ($allowAbTest):**"

It's the same condition that is written in actions selector.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
