### ISSUE TITLE
Mautic landing page not registering visit

### ISSUE THREAD

**Issue by fbsoft** [mautic/mautic#5593]
Hello, 
I'm having an issue with mautic, and the double opt-in tutorial. I had followed it to the letter, but i can't seem to make it work. I got as far as getting the user in the pending list, receiving the email sent automatically, but visiting the landing page, although the link is properly formatted to say so, and it gets me to that page, mautic does not register the visit. The stats on landing page are empty, and the removal from one segment to another it does not register.

Am i doing something wrong ? Or is this a bug ?
I am using mauti version 2.11, PHP version 7.0.25-0ubuntu0.16.04.1

There aren't any log errors on app log file

**Comment by dbhurley** [comment]
Sorry, not trying to be rude at all since you just posted this, but this is not a bug report for Mautic. Instead it seems to be a bit more of a support request. I'd recommend checking out the [forums](https://www.mautic.org/forums) or even the [Slack channels](https://mautic.slack.com) for help.
