### ISSUE TITLE
IP Lookup last updated timestamp incorrect.

### ISSUE THREAD

**Issue by 4evermaat** [mautic/mautic#5595]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | NO 
| Enhancement? | NO

## Description:
When a user updates the GeoIP database either manually via GUI or `mautic:iplookup:download`, the timestamp is incorrect.  It is temporarily correct as of that day, but as soon as the next day appears, it should say "yesterday" or the day before.

![mautic ip lookup datastore last updated timestamp incorrect](https://user-images.githubusercontent.com/830306/35049474-b817cab2-fbd2-11e7-9b64-8dd1a4640139.png)

In fact, even if it is "today", it should still have the full date timestamp `dd-mm-yyyy HH:MM` there (whatever format is specified in the configuration as default full date setting).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.27

### Steps to reproduce:
1. update MaxMind GeoIP database manually via GUI or via cli `mautic:iplookup:download` 
2. Don't update again for next several days.
3. refresh System Settings tab under configuration page  
4. check the last updated date under. Does it still say Last updated on **Today**, x:xx am/pm
`Last updated on Today, xx:xx`??
 
### Log errors: 

[none]

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
