### ISSUE TITLE
email report : data duplicate in mail sent report

### ISSUE THREAD

**Issue by SalvoEng83** [mautic/mautic#5598]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  x
| Feature request? | 
| Enhancement? | 

## Description:
when you create a report to view email-sent data, and filter it by email_id, everything works fine if the email has been used in a single campaign. But if you create a new campaign, and use on it an email already used in another campaign, the report show data duplicated.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.12.1
| PHP version |  PHP 7.0.27-0+deb9u1 

### Steps to reproduce:
1.  create a template mail.
2.  create a campaign with action send-email, and specify the email just created.
3.  launch the campaign.
4.  create a report that show email sent, and filter by email-id, specifying email-id of the email just created.
5. create a new campaign with action send-email. Use the email used in the previous campaign.
6. refresh the page of report created and you can see that the real number of email send is exactly twice.
 
### Log errors: 
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Well, you've sent the email twice, so what's wrong with the reports showing it?

**Comment by SalvoEng83** [comment]
I was not clear in exposing the problem. Example. I have an email template, email_id=14. 
I create two distinct campaigns (campaign_id 5 and campaign__id 6)  each with one single lead that send the email with id 14. I execute both campaigns and receive correctly the emails.
Than i want to view the report of email sent on a campaigns, so i create two distinct report:
Report_1 filtering by email_id=14 and campaign_id=5.
Report_2 filtering by email_id=14 and campaign_id=6.
I expect to see report_1 graph with one single email sent on campaign_id 5, instead i see two emails sent both with email_id 14 on same campaign. The same result on report_2.

**Comment by SalvoEng83** [comment]
Debugging source code, i found that the problem is the query by which data is retrieved from the database. In the method  app/bundles/ReportBundle/Model/ReportModel::getReportData(); 
if you try to add on the query a "DISTINCT" clause, the data on table are show correctly, but it solve only the duplicated data on table, instead the graph continue to show duplicated data.

**Comment by npracht** [comment]
@SalvoEng83 is that still an issue in current version ?

**Comment by npracht** [comment]
Without extra information and being an old issue, let close it.

**Comment by BillPackard** [comment]
I send a email. In first 2 hours come in the reading statistic and one time stopd and froozen. Lot of hours gone but statistic not refreshed. Lot of errors the system. I try do, but soon delete everything. Lot of time setup and lot of errors.

**Comment by BillPackard** [comment]
I deleted the system. I gave up. Lot of problem: slowly, read statistic only a bit time works after froozen, unreliable and inaccurate. I sincerely regret working with him for 3 days, day and night. Thanks.

**Comment by BillPackard** [comment]
I don't recommend it to anyone. Detection of endless bugs, bug fixes, prolems. In the end, a slow and inaccurate system is the result.

**Comment by namratasaun** [comment]
> @SalvoEng83 is that still an issue in current version ?

yes having a similar issue
I filtered emails sent data based on a single contact and single campaign.
I can confirm that only 3 emails are sent to the contact but the report is showing 6.

<img width="1181" alt="Screenshot 2021-04-30 at 2 01 11 PM" src="https://user-images.githubusercontent.com/35791871/116670184-0ef85180-a9bd-11eb-92e6-b4c8bef253b7.png">

**Comment by npracht** [comment]
Fixed by https://github.com/mautic/mautic/pull/10102, please review the PR !
