### ISSUE TITLE
Push lead to Integration Meaning

### ISSUE THREAD

**Issue by SolacetechInformationServices** [mautic/mautic#56]
"Push lead to Integration.." Sounds exciting. What does it do?
![push lead to inegration](https://cloud.githubusercontent.com/assets/11036921/6237588/2ab094e0-b6c2-11e4-8f8a-c8b5f10cc33c.png)

**Comment by alanhartless** [comment]
Hi!

This is better suited for the community forum at mautic.org/community.

Thanks,
Alan
