### ISSUE TITLE
Campaign actions being noted in history, but not executed

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#5600]
| Bug report? | 
 

## Description:
- Contacts are in a mailing list segment for mailouts (B2C_Mailing).
- Filter based segment is generated based on contact inactivity after 6 months(Inactive For Last 6 Months)
![image](https://user-images.githubusercontent.com/10385295/35096430-4cbf8d3a-fca0-11e7-841a-2bdb7bb3a471.png)
- Campaign to perform the following is active
![image](https://user-images.githubusercontent.com/10385295/35095858-34f20428-fc9e-11e7-891e-c09378dee9d3.png)
- Contacts show action from campaign against their history, but segment membership is not changed. i.e. contact is not actually removed from segment
![image](https://user-images.githubusercontent.com/10385295/35096510-948d5dfe-fca0-11e7-96c5-3eefa28aef26.png)
![image](https://user-images.githubusercontent.com/10385295/35096560-bf0f54e2-fca0-11e7-9d0f-ab55fa477a54.png)
![image](https://user-images.githubusercontent.com/10385295/35096590-d9626a32-fca0-11e7-8786-3f0ee621be84.png)

## If a bug:

| Mautic version | 2.12.1
| PHP version |  7.0.22-0ubuntu0.16.04.1

### Steps to reproduce:
1. Put a contact in both a mailing list segment and a "pruning" segment
2. Create and activate a campaign for members of the mailing list segment whereby if they are in the pruning segment, they are removed from the mailing list segment.
 
### Log errors: 
mautic-campaigns-rebuild.log

> Thu Jan 18 11:07:01 UTC 2018
> Rebuilding contacts for campaign 1
> 607 total contact(s) to be added in batches of 300
>    0/607 [>---------------------------]   0%
>   60/607 [==>-------------------------]   9%
>  120/607 [=====>----------------------]  19%
>  180/607 [========>-------------------]  29%
>  240/607 [===========>----------------]  39%
>  300/607 [=============>--------------]  49%
>  360/607 [================>-----------]  59%
>  420/607 [===================>--------]  69%
>  480/607 [======================>-----]  79%
>  540/607 [========================>---]  88%
>  600/607 [===========================>]  98%
>  607/607 [============================] 100%
> 0 total contact(s) to be removed in batches of 300
> 607 contact(s) affected

> Thu Jan 18 11:08:01 UTC 2018
> Rebuilding contacts for campaign 1
> 0 total contact(s) to be added in batches of 300
> 108 total contact(s) to be removed in batches of 300
>    0/108 [>---------------------------]   0%
>   10/108 [==>-------------------------]   9%
>   20/108 [=====>----------------------]  18%
>   30/108 [=======>--------------------]  27%
>   40/108 [==========>-----------------]  37%
>   50/108 [============>---------------]  46%
>   60/108 [===============>------------]  55%
>   70/108 [==================>---------]  64%
>   80/108 [====================>-------]  74%
>   90/108 [=======================>----]  83%
>  100/108 [=========================>--]  92%
>  108/108 [============================] 100%
> 108 contact(s) affected

mautic-campaigns-trigger.log (from cron task similarly named)
> Thu Jan 18 11:07:05 UTC 2018
> Triggering events for campaign 1
> Triggering first level events
> 607 total events(s) to be processed in batches of 100
>    0/607 [>---------------------------]   0%
>   60/607 [==>-------------------------]   9%
>  120/607 [=====>----------------------]  19%
>  180/607 [========>-------------------]  29%
>  240/607 [===========>----------------]  39%
>  300/607 [=============>--------------]  49%
>  360/607 [================>-----------]  59%
>  420/607 [===================>--------]  69%
>  480/607 [======================>-----]  79%
>  540/607 [========================>---]  88%
>  600/607 [===========================>]  98%
>  607/607 [============================] 100%
> 715 event(s) executed

mautic-segments-update.log (from cron task similarly named)
> Thu Jan 18 11:09:04 UTC 2018
> Rebuilding contacts for segment 4
> 0 total contact(s) to be added in batches of 300
>  total contact(s) to be removed in batches of 300
> 0 contact(s) affected

No errors in web server (nginx) log

**Comment by npracht** [comment]
They are planned in the history even if event is not triggered yet.
