### ISSUE TITLE
Mautic Tracking pixel is not working after 2.12.1 update

### ISSUE THREAD

**Issue by appscaptain** [mautic/mautic#5602]
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Just upgraded to newest Mautic as of jan 19 2018, and now Contacts are not tracked when they move around on my Wordpress site. Also I don’t get any IP and no page visits are tracked (which breaks all my +20 campaigns). I have checked that the Mautic Wordpress plugin is enabled and upgraded. It worked perfectly before the Mautic upgrade, so this seems to be a bug.

I have followed all the troubleshooting steps for Contact tracking (different browser, private mode, check url etc. - and the pixel is loaded just fine (eg. Status 200 in the browser web tools) with all the parameters like page_title etc. all filled out correctly. I have also tried to manually install the tracking code from the "Mautic tracking settings". So the tracking pixel is definately activated but, Mautic for some reason doesn’t receive it properly.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.27

### Steps to reproduce:
1.  Sign up with a Mautic form (eg. abc@gmail.com)
2. Visit different webpages that has the Mautic tracking pixel installed.
3. Check Mautic contacts and go into the specific contact (abc@gmail.com)

You won't see neither the IP or the visited page.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

Have checked app/logs as well. The only thing I have there is [2018-01-18 13:03:34] mautic.WARNING: IP LOOKUP: The file "/home/my.domain.com/public_html/app/cache/prod/../ip_data/GeoLite2-City.mmdb" does not exist or is not readable. [] []

**Comment by dbhurley** [comment]
Can't replicate. Will leave open temporarily to see if anyone else is able to reproduce this.

**Comment by appscaptain** [comment]
Ok, weird that it can't be reproduced. It happened just after the upgrade and everything else works. I've tried everything in your troubleshooting guides. Any ideas on how to fix it? My email system with +20 campaigns are broken so would really like to find a solution.

Hope you can help. I could share wordpress login and Mautic login?

**Comment by appscaptain** [comment]
An update. 
Despite the values being read correctly. I noticed in the console that I get a “Failed to load http://mymauticdomain.com/mtc/event: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mywebsite.com' is therefore not allowed access.” So maybe that’s why it’s it not being sent to Mautic?

This worked fine before the update. Maybe Mautic’s security was tightened further causing this issue?

I then tried to add “add_header Access-Control-Allow-Origin *;” to my location block in NGinx for my mymauticdomain.com.conf in conf.d, and now I get:
“Failed to load http://mymauticdomain.com/mtc/event: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://mywebsite.com' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.”

Any ideas on how to fix that?

**Comment by appscaptain** [comment]
Turning "restrict domains" off in Configuration removes the "No 'Access-Control-Allow-Origin' header" error, but the tracking still doesn't work.

**Comment by appscaptain** [comment]
Another update. @dbhurley After having reinstalled my server from scratch a few times and setting up test installation I discovered what's causing the issue. The newest version of Mautic seem to break WP Mautic Form Integrator here: https://wordpress.org/support/plugin/wp-mautic-form-integrator/

If leads are entered through the WP Mautic Form Integrator plugin (through Contact Form 7 for instance on Wordpress sites) they are not tracked. If they are added through a normal Mautic form, however they are tracked everytime.

So there is some kind of a change in Mautic, that kills the WP Mautic Form Integrator plugin. It can be reproduced every time, with a clean install of Mautic.
