### ISSUE TITLE
Clone Segments

### ISSUE THREAD

**Issue by justinfortes** [mautic/mautic#5604]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:

Provide the ability to clone segments similar to cloning campaigns.

Spec
https://docs.google.com/document/d/1UJAM_6usLrFsyEWuii_9WWPgYAP2eFWbt8ccHGH2ZK0/

**Comment by dbhurley** [comment]
Moved to mautic-internal/mautic-internal#2
