### ISSUE TITLE
Notify user that an email is published/not published in a campaign 

### ISSUE THREAD

**Issue by justinfortes** [mautic/mautic#5605]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Yes

## Description:

As a user, I would like to know if an email in my campaign is not published before I publish the campaign, this will prevent contacts from going through my campaign and Mautic would fail to send them the email.  Since contacts can only go through a campaign once, I would then need to create a Segment to find those contacts to whom the email was never sent, and send them through a cloned campaign.

spec - https://docs.google.com/document/d/1AbkhmYNOjb5m0KUiTpk_azFisz90RvRWr2_Cq2KYNzc/

**Comment by dbhurley** [comment]
Moved to mautic-internal/mautic-internal#4
