### ISSUE TITLE
Update company fields in a campaign

### ISSUE THREAD

**Issue by justinfortes** [mautic/mautic#5606]
Give the customer the ability to update a company field and company owner within a campaign. This would also allow a user to do bulk company updates.

No spec needed for this one. 

During a campaign, under actions, add the ability to Update company. 
Same UI and functionality as Update Contact. 

After selecting "update company" display the update company fields page. 

--- Update company fields page ---
Update company
Update the current company fields with the defined values from this action

Field: Name 

Execute this even... *help topic icon* 

Help topic content
This even will be executed for newly added companies to the campaign even if the scheduled date is in the past. 

Fields to display for editing
Company Name
Company Email
Company Address
- Company Address 1
- Company Address 2
- Company City
- Company State
- Company Zip
- Company Country
Company Website
Company Phone
Annual Revenue 
Company Fax
Number of Employees
Industry
Description
--- Any other company custom fields 

--- Update company owner page ---
See screenshot below
![Edit_Campaign___Mautic.png](https://codetreeusercontent.s3.amazonaws.com/uploads/0172397f-bb6e-43fa-8e01-3294cad758d4/Edit_Campaign___Mautic.png)
![Screen Shot 2018-01-18 at 12.21.00 PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/0172397f-bb6e-43fa-8e01-3294cad758d4/Screen+Shot+2018-01-18+at+12.21.00+PM.png)
![Pasted_Image_1_18_18__12_08_PM.png](https://codetreeusercontent.s3.amazonaws.com/uploads/0172397f-bb6e-43fa-8e01-3294cad758d4/Pasted_Image_1_18_18__12_08_PM.png)

**Comment by dbhurley** [comment]
Moved to mautic-internal/mautic-internal#3
