### ISSUE TITLE
mautic:import silently fails after memory exhaustion in previous run

### ISSUE THREAD

**Issue by digitall-it** [mautic/mautic#5608]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
If an import operation exceeds the allowed memory size, the entire import hangs. No feedback is given to the user (for example to reduce the number of contacts to import on each batch). Operation is restarted by switching on and off the import switch.

When executing the console command from CLI

`/opt/plesk/php/5.6/bin/php app/console mautic:import`

I receive the message
`2034/136353 [>---------------------------]   1%PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8208 bytes) in  [...]`

however, if the import switch is not turned off and on, no further error appears: the import scripts aborts istantaneously, making finding out the condition more difficult for the administrator.

The script is clever to not hog the server resources once it goes in error: however, it should at least report it has hang up if run manually, for debug purposes. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6.3.3

### Steps to reproduce:
1. Start a batch import with an abnormally high batch number of contacts at once, like 1000 instead of the usual 100
2. Run the script from CLI in an environment where the memory is limited, for example using a command like `php -d memory_limit=16M app/console mautic:import`
3. State the error that appears on screen
4. Repeat step 2: the process is hang
5. Go to your import, switch it off and on
6. Repeat step 2: the process restarts now, giving an error (as expected)

### Log errors: 

Didn't find a trace of the memory problem in the logs.

**Comment by luizeof** [comment]
+1

**Comment by kuzmany** [comment]
Confirmed. 
We use import in batch 1000 , but with 25000 wors of import got memory exhaustion error and import not continue

**Comment by digitall-it** [comment]
@kuzmany turn import off and on and use the -d flag on command line to allocate more memory to the process. But #4700 will mitigate this, but sometimes CLI processes have very low memory defaults and there’s little you can do about it.

**Comment by kuzmany** [comment]
@digitall-it thanks, nice catch. 
I am doing same during the php unit tests.
