### ISSUE TITLE
mautic:import doesn't respect batch limit

### ISSUE THREAD

**Issue by digitall-it** [mautic/mautic#5609]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
After double checking in the database, table imports, that the batch limit is set to 100

`{"fields":{"cap":"companyzipcode","catmerceologica":"companyindustry","comune":"companycity","email":"companyemail","fax":"companyfax","indirizzo":"companyaddress1","provincia":"companyprovince","rag_sociale":"companyname","regione":"companystate","tel":"companyphone"},"defaults":{"owner":null,"list":2,"tags":["aziende-2","lombardia","verzeri"]},"headers":["Regione","Provincia","Comune","Rag Sociale","Indirizzo","Cap","Tel","Fax","Email","CatMerceologica"],"parser":{"delimiter":";","enclosure":"\"","escape":"\\","batchlimit":100},"line":11901}`

running

`/opt/plesk/php/5.6/bin/php -d memory_limit=4096M app/console mautic:import`

doesn't stop after 100 rows. Instead it goes on until the memory is depleted or the operation is completed.

Found out while investigating #5608.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6.33

### Steps to reproduce:
1. Batch import a very large CSV file with only a batch limit of 100 rows
2. run the batch import script
3. note that the batch import doesn't stop after the imposed limit
 
### Log errors: 

No errors are logged.

### Important: 

A big **thank you** to the developers and the rest of the community for creating this fantastic software, is surely in order.

**Comment by maltonite** [comment]
This might be related to #4700

**Comment by digitall-it** [comment]
It seems to be tangential, but not coincident. Let me explain. Usually the loops memory consumptions can be reduced by optimizing the loop so that each operation doesn't add up memory (although each compiler and script inevitably leads to leaks over time and thus uses all the available memory) and by breaking up larger loops into smaller ones. #4700 relates to the first approach, thus optimizing the import loop. This bug relates to an already implemented directive that is not respected, the batch limit. This means that on each invocation of the script, only a portion of the rows should be processed. Scope of #4700 is related to optimizing memory consumption alone, while respecting the batch limit directive would distribute the processing effort over time, thus reducing load and preventing server paralysis when no other limits are imposed by the environment. However, allow me to thank you for taking the time to investigate the problem, and sorry for being verbose.

**Comment by maltonite** [comment]
From further digging, I believe the issue was caused by #5518 Thanks @digitall-it for explaining further.

**Comment by digitall-it** [comment]
It indeed talks about pagination, but I'm not really sure.

I suggest creating an automated test that assumes that no more than the batch limit gets imported. This would also prevent regressions.

**Comment by escopecz** [comment]
I think there is a problem with terms. The batch limit of 100 means that the import script will take 100 rows, process them, clear the memory (as good as possible) and take another 100 rows, process them ... and so on until the end of the CSV file.

What I suggest to test is the `--limit=100` parameter of the import command. Here is the help text:
```
$ app/console mautic:import --help
Usage:
  mautic:import [options]

Options:
  -i, --id[=ID]            Specific ID to import. Defaults to next in the queue. [default: false]
  -l, --limit[=LIMIT]      Maximum number of records to import for this script execution. [default: 0]
  -h, --help               Display this help message
  -q, --quiet              Do not output any message
  -V, --version            Display this application version
      --ansi               Force ANSI output
      --no-ansi            Disable ANSI output
  -n, --no-interaction     Do not ask any interactive question
  -s, --shell              Launch the shell.
      --process-isolation  Launch commands from shell as a separate process.
  -e, --env=ENV            The Environment name. [default: "prod"]
      --no-debug           Switches off debug mode.
  -v|vv|vvv, --verbose     Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  The mautic:import command starts to import CSV files when some are created.

  php app/console mautic:import
```

**Comment by escopecz** [comment]
Thanks for the suggestions!

1. Please consider updating the docs. It's quite simple. https://github.com/mautic/documentation#how-to-contribute-to-the-docs
2. `0` means unlimited. People usually want to import the whole file at once. Or at least I'd be surprised if the command suddenly stopped.
3. I've started this PHP library that can get insights like that here: https://github.com/cronfig/sysinfo The problem is that the native PHP function that are in use there work only on some OS and there is no alternative for Windows for example. Which makes it hard to deploy to a project like Mautic. Also I have nowhere to test that library on Windows. Help would be appreciated.
4. The state and process is being saved to a database table. So if the import is stuck in the `in progress` state on the same percentage for a while, check the logs for error messages with details.
