### ISSUE TITLE
Report data empty with Custom Field Filter

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#5613]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

REPORT data is empty If Filter by Custom Field with "not empty" option

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0

### Steps to reproduce:
1. Creste a report with an text Custom Field 
2. Use the operator "not empty" with this Field
3. Report data is empty 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
