### ISSUE TITLE
Mautic Landing page hit not registering

### ISSUE THREAD

**Issue by fbsoft** [mautic/mautic#5618]
Hello, 
I posted a few days ago, a bug report for the double opt in procedure that didn't work, and i had submitted it as a bug. I was thrown to a forum, to ask there, but it wasn't much help. I had started to dig into the problem, and the first statement was partial true. Further investigating resulted that the landing page didn't register the clicks from the email

In short to reproduce the error, you need to do the following
Install Mautic, lateste version 2.12.1, and have a PHP version 7
Next follow the procedure for the double opt-in email sending.
The bug is : After the email is sent to the user, if you are the user that is testing if and how it works, the click on the link in the email will or not will be registered. 

The not registered part is in Chrome, Version 63.0.3239.132 (Official Build) (64-bit):

1) Log in with your account, add your test Email address ( a secondary email address ) via the interface, or via the form created in the double opt-in
if it is added in the contacts page, add it to the double opt-in campaign.
After the campaign trigger is done and email is sent, you will receive the email. 
You open it. 
Everything till here will be noted in the users log, from contact. 

While still logged, in your admin account, click on the link for confirming the subscription for the secondary email address. The landing page will load but the click will not be registered.

I had turned to chrome and used in incognito mode the link provided by the email, and i got a 503 error.

If i log out of the admin account and i click on the link provided , landing page is hit but not registered.

If i remain logged in Chrome but use Firefox, in which i haven't logged in ever, to mautic to have a cookie present, the landing page hit is registered

If i delete all the cookies in chrome, and try, with log in and log out, it still doesn't work

If i delete all the cookies in chrome, log in via incognito mode, and load the submit link in normal mode, the landing page hit is registered

This is done with several tests and several links generated/sent to see if and where does it fail to register, and how if and when mautic should work

Note: this was tested on 2 different systems. The issue is the same, on the second one though i hadn't got the 503 error, but the landing page not hitting was present on all the tests done above, with mautic logged in the admin account, and the cookie present.

**Comment by dbhurley** [comment]
I am not trying to be difficult, but if you insist that the problem exists in the code and needs to be addressed by bug fixes then please resubmit in a proper bug report format.

**Comment by MayaMathura** [comment]
Was this opened as a bug report? We are experiencing this still.
