### ISSUE TITLE
Match database column types with field types

### ISSUE THREAD

**Issue by kithokit** [mautic/mautic#562]
From the mange field,

I add custom field, Type is Number, 

the outcome type  in mysql is longtext.

Thus I can't do correct filtering by number

**Comment by alanhartless** [comment]
Right now, the form field types affect the input type in HTML but not the underlying column in the database.  I'll mark this as a feature request/enhancement though so we can look at making the column type match for that reason.  As a temporary work around, you may be able to use something like MySQL's CONVERT() and aliases in the query?

Thanks!
Alan

**Comment by infocrea** [comment]
Alan, I think that your temporary work around is a good way to have a quick solution. As we are waiting for this, I am interested to have an idea of the delay for this request added ?

**Comment by alanhartless** [comment]
Fixed in 2.0 - new fields added now use the proper DB type.
