### ISSUE TITLE
Do not update number of contacts in contact list

### ISSUE THREAD

**Issue by Rogerfava** [mautic/mautic#5634]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Mautic v2.12.0 is not updating the amount of contacts in contact list. It only shows the new contacts addeds in Dashboard. May i need to reboot the server?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
@Rogerfava could you please give more information about how to reproduce ? Do you have a message error when the segment command runs ?

Thanks.

**Comment by AndrassGray** [comment]
The magic word of this issue report is "dashboard", I believe. The number of contacts shown on the "Top Lists" widget on the dashboard (widget type Contact widgets > Top segments) do not match the numbers shown on the Segments page.

At least I notice this on my 2.9.2 installation.

**Comment by Rogerfava** [comment]
@npracht the problem is in the contacts list as you can see in the attachment. 
I usually upload contacts in mautic but is not updating the number of contacts at list's bellow. May it happens due memory? Do i need to reboot the server?
![mautic_print_contacts](https://user-images.githubusercontent.com/35769121/35566047-1b98ac4a-05a7-11e8-8e36-fccd80e2e69c.png)
