### ISSUE TITLE
site url - email link and form messages 

### ISSUE THREAD

**Issue by dme-me** [mautic/mautic#5638]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
If the site-url is with "index.php" at the end the emaillinks works fine but the required message and the page breaks doesn't work. When I remove the "index.php" (site-url) the required message und the page breaks works but the email links just work in the test-mails.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | PHP 7.0.1

### Steps to reproduce:
1. leave "index.php" in the site-url as set in the installation. Message: Required or pagebrake at the forms doesn't work
2. remove "index.php" in the site-url. Email Links just work in testmails but the leads get the link without the site-url
 
### Log errors: 

non

**Comment by dbhurley** [comment]
This is an htaccess problem related to your server install it sounds like. I would recommend reviewing how you configure your server setup and the way you handle mod_rewrites possibly.
