### ISSUE TITLE
500 Error when campaign includes condition / logic based on form input

### ISSUE THREAD

**Issue by stephenvoisey** [mautic/mautic#5639]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

Error looks similar to #4349 but different route to get it and tried logging out and submitting from multiple devices. Also sounds like a similar issue (probably same issue) happening from #5391.

Any campaign which includes a decision / logic causes Mautic to return a 500 error when externally submitting a form or times out with a 'please wait' when using the same form at the Mautic URL /form/#id

Despite this, Mautic sends the emails, adds the form details and creates a new contact. It does not redirect to the URL after the form is submitted as requested, instead just ended up with the 500 error.

Mautic does not show the decision on form submit as increasing in percentage (Should be 100% I'm guessing?) But does show the outcome of the condition percentages. 

For reference I did a new install of 2.12 before updating to 2.12.1 and running migration.

Many thanks!

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.1.13

### Steps to reproduce:
1. Create a Campaign Form with a radio group that can simply be 1 or 0 as values and email address (also connect it to the relevant contact field) and first name (connect to contact field also).
1b. Create a URL redirect in the Campaign Form settings.
2. Create two different emails to be sent which include twig field contact first name
3. Create a new Campaign
4. Select the new Campaign Form as source
5. Add a decision based on Contact Submitting the form
6. Below that add a condition that works immediately and looks for an equal value to 1 in the radio group of the form you initially created
7. For success add an action to send the user one of the emails
8. For failure add an action to send the user one of the other emails
9. Submit the form externally or at the ID url on the mautic install (provides time out and error in log)

Right Emails will send, contact is created, but 500 error or time out occurs.

### Log errors: 

```[2018-01-24 14:38:58] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #360. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /srv/users/serverpilot/apps/marketing/public/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #360. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /srv/users/serverpilot/apps/marketing/public/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []```

**Comment by dbhurley** [comment]
Label: Bug

**Comment by dbhurley** [comment]
Label: Bug

**Comment by Woeler** [comment]
Same error when testing the new version of the TYPO3 extension, which also uses external post on forms. Getting the same error, submitted form data is lost.

**Comment by Uebix** [comment]
There are updates?

**Comment by Uebix** [comment]
Updates? We have the same problem...

**Comment by stephenvoisey** [comment]
This issue has successfully been resolved for me in the new 2.14 release. Yay! Thanks all.
