### ISSUE TITLE
Submitting form externally rejects data

### ISSUE THREAD

**Issue by Woeler** [mautic/mautic#5645]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When submitting a form via HTTP POST over https://yourmautic.com/form/submit?formId=1 all data sent via the request is lost. No form result is saved. This was working on earlier releases. I found this out when I updated Mautic today and started working on the TYPO3 extension, which heavily relies on this external posting.

I have tested with complex forms, and simple forms with just one text field. Also I have tried posting with a super simple script, rather than the TYPO3 extension, to rule out that TYPO3 might be the problem. All results are the same, post data is discarded.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.1.3

### Steps to reproduce:
1. Create a form in Mautic
2. Post results to the form via POST using the url https://[yourmautic.com]/form/submit?formId=[form id]
3. See no results being added in the backend
 
### Log errors: 

```[2018-01-26 13:43:40] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /var/www/vhosts/vmd19295.contaboserver.net/mautic.woeler.eu/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\FormBundle\\Entity\\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /var/www/vhosts/vmd19295.contaboserver.net/mautic.woeler.eu/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []```

**Comment by brandner** [comment]
Same error. New form, one field (textarea), no action; just saves results.
Posting throws 500 error and the log reads as above in the issue.

**Comment by escopecz** [comment]
I'm not able to replicate. Tested on 2.12.2-beta with standalone and campaign form, email field and textarea field. I used https://github.com/escopecz/mautic-form-submit which contains an example code to test with. 

So what's the catch?

**Comment by Woeler** [comment]
I'm really not sure what is happening here. The error message is extremely abstract (at least to me). Was hoping someone could shed some light on what it actually means.

**Comment by brandner** [comment]
@escopecz - did you try a form without an email field?

**Comment by escopecz** [comment]
Just did. With only a textarea field. @brandner can you? No error thrown or reported. It would really help if someone provide detailed steps to replicate.

**Comment by escopecz** [comment]
Still cannot reproduce. Can someone else with the ability to reproduce this error debug it and fix it?

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/6131
