### ISSUE TITLE
Adding a chart or table to a report causes a 500 error

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#5649]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Adding a chart or table on a report causes a 500 error - probably related to #4908 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Create a report, add columns and filters
2. Try to add a data table or chart
 
### Log errors: 

Also, if I try to add a chart (e.g. showing unsubscribes) when I have already declared columns or filters for the report, I get a 500 error:

`[2018-01-27 16:51:26] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Query\QueryException: "The given alias 'dnc' is not unique in FROM and JOIN clause table. The currently registered aliases are: es, e, l, i, vp, c, dnc, clel." at /home/mysite/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryException.php line 50 {"exception":"[object] (Doctrine\\DBAL\\Query\\QueryException(code: 0): The given alias 'dnc' is not unique in FROM and JOIN clause table. The currently registered aliases are: es, e, l, i, vp, c, dnc, clel. at /home/mysite/public_html/m/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryException.php:50)"} []`

**Comment by Shaileshpx** [comment]
+1

**Comment by escopecz** [comment]
Cannot replicate. Is it for special data source? I tested with email sends.

**Comment by RCheesley** [comment]
This was back in March so I suspect it has likely been fixed by now.
