### ISSUE TITLE
Unsubscribe report widget contains no numerical data

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#5650]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When adding a Dashboard widget to represent the unsubscribes, there is no numerical data (e.g. ID, number of unsubscribes) displayed.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6.23

### Steps to reproduce:
1. On an instance which has data to report on, create a dashboard widget using Report Widgets>Report Graph
2. Choose 'Unsubscribes: Most emails unsubscribed
3. A list is populated but there is no data in the first or last columns.  The title is populated in the list but nothing else.
 
### Log errors: 

No errors produced

**Comment by npracht** [comment]
@RCheesley ? :D

**Comment by RCheesley** [comment]
No longer relevant! Closing :)
