### ISSUE TITLE
Error 500 message on the first visit of a Double-Opt-In confirm page

### ISSUE THREAD

**Issue by AkkuFresh** [mautic/mautic#5653]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes|
| Feature request? | 
| Enhancement? | 

## Description:
The visitor clicked on the confirm link in the opt-in campaign (template) email, and arrived to the error 500 message instead of the Opt-In confirm (Mautic Landing) page.
The second attempt to click on the link in the email is already good, without any issue the contact will arrive to the confirm page.

The tracking setting was only "Identify visitor by tracking url" = Yes

This is an easily reproducible issue. You should use the fresh install, or truncate all Mautic tables used for the tracking and measuring.

In the Double opt-in process we were using an external landing page tracked by Mautic, with a sign-up form. It is filled on the desktop PC.
The campaign puts the signed up visitor to the pending list, and sends an opt-in email.

The visitor open this email from the web based Gmail account, and after clicking to the url of the opt-in confirm page (created as Mautic Landing page), the visitor is arriving to the error 500 page. Of course no tracking, no history an no action triggers in the campaign. 

Clicking second time to the same url in the email - the visitor will arrive to the opt-in confirm page without any error, with normal tracking history and triggering all campaign action.

The issue is critical because on the test campaign about 25% of signed-up visitor was hanged up on this issue, Mautic not detecting the page hit did not move these contacts from the pending list to the confirmed list. And in not all the cases appeared the error message provided below.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1 |
| PHP version | 7.0.27 |

### Steps to reproduce:
1. Fresh Mautic install or clear all logs table in the database
2. Use the standard double-opt-in process from this site 
[Double Opt-In](https://www.mautic.org/blog/integrator/creating-a-double-opt-in-email-campaign/)
 
### Log errors: 

Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: 
"A new entity was found through the relationship 'Mautic\CampaignBundle\Entity\LeadEventLog#lead' 
that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID xxxx. 
To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /--mautic_path--/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 
{"exception":"[object] 
	(Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): 
	A new entity was found through the relationship 
	'Mautic\\CampaignBundle\\Entity\\LeadEventLog#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID xxxx. 
	To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). 
	at /--mautic_path--/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []

**Comment by escopecz** [comment]
Did you test this within an incognito browser window or in the same browser you are logged in to Mautic administration?

**Comment by galvani** [comment]
This might be related? https://github.com/mautic/mautic/issues/5645

**Comment by SteveHey** [comment]
We also have this issue and have found that it seems to work fine with non tracked links, but as soon as you use tracking links which we need for our email campaigns the system crashes giving the error 500 message. Below the error we get.

[2018-02-14 10:52:47] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Malformed UTF-8 characters, possibly incorrectly encoded" at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 163 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:163)"} []

Looking at it for the last few days we think we have narrowed it down to when the tracked link is clicked, as seems to work fine without tracked links. Seems to something to do with how Mautic see these links.

For information tracked links are working well in email newsletters and we have no problems when sent through Mautic, this is a campaign email that is causing the issues, so maybe campaign related only. We started with an Assets Download Condition and then changed to Link Click Condition, finishing my putting a page in the way that added the Mautic tracking code and then auto forwarded to our pdf file on aws. 

The stand alone file worked fine and tracked well when accessed through a browser, however when used to initiate a Link Click Condition the campaign triggers using this method but the browser still generates a 500 error for the user and the above error message is recorded in logs.

So problem looks like how Mautic is Decoding this Campaign Tracked Link.

Hope that this helps.....

**Comment by SteveHey** [comment]
The form data is saved fine in the results for the form, the form works fine. This is a campaign form that triggers a campaign. Mautic takes form data OK, campaign triggers fine and completes every step OK.

However on clicking the link in the email we get 500 error first time, it even records a page hit for the page we are trying to get them to for the right user even thou we have 500 error. If we click the link a second time the link will work fine and we will get the page hit for the right user, so second click seem to work OK.

Everything is working except that first click from campaign sent emails.

We send loads of emails with tracked links just as emails to segments for our newsletter and these all work fine, so just seems to be campaign emails.

Any ideas.

We are going to boot a new server on AWS, to check it is not an IP Issue, we are tracking by IP & Fingerprint, so new server, new browser, new IP, is there any reason when we delete an account that has triggered the campaign and then been removed that it should not fire again for the same data entered in the form?

**Comment by AkkuFresh** [comment]
I am sorry, I was out from the net few days.
The all tests with this issue was done with admin logged out state from Mautic, and with cleared Mautic related cookies from the Google Chrome browser.
In this way the visitor totally independent from the admin user.
In our case the issue was detected only that time when the visitor clicked to the confirm email link from the web based Gmail account. On Thunderbird desktop email clicking was done without any issue.

**Comment by SteveHey** [comment]
Just booted up a brand new Windows Server in AWS with Chrome Not Logged in so should be No Cookies except from this Remote Visit to Website on this IP, Never Logged in as Admin on this Remote PC and IP.

Tracked as we completed form and stored data for form, tracked the pages visited after form submission, Triggered Campaign and Sent the Email OK, Clicked the Link and 500 Error Displayed on Screen, triggered our campaign clicks link condition OK and Gives a Page Hit for The Page that is supposed to be displayed. Triggers the Rest of The Campaign Thread OK sending out a welcome email with tracked links that work when they are clicked on, so this Second Email in Campaign Flow Works OK with Tracked Links. It seems it is only that first click on the first email when put in a campaign that is the cause of error above.

Everything in Mautic Admin seems to work & tracks campaign fine for remote user, all steps recorded and triggered OK. User removed from campaign as required at end of our campaign.

We are using v2.12.1 Stable.

This is a Client integration & they do not want us using beta software on thier live environment so not tried beta versions, however if a fix is available we have permission to integrate to solve this issue.

**Comment by escopecz** [comment]
Here is my attempt for the fix: https://github.com/mautic/mautic/pull/5678

**Comment by SteveHey** [comment]
What does this actually do in app/bundles/CampaignBundle/Model/EventModel.php?

437:         // if (count($logs)) {
438:         //     $this->getLeadEventLogRepository()->saveEntities($logs);
439:         // }

We have found that by commenting this out we have solved the 500 error issues above, checked all campaign steps and everything has been triggered OK, all seems to have worked fine with this commented out, therefore is this just storing info a log file somewhere..???? if so happy to lose that info....

Be grateful of advice on commenting this out, any bad results as a consequence..????

Just checked database table and only thing we can notice is decision step of clicking link is not logged, Should this be logged?.... or does it just check it from other steps etc......

**Comment by escopecz** [comment]
- It's quite important to store what events each contact went through. Otherwise the contact will start from scratch next time instead of continuing from the step he has left before.
- In the contact detail you can then see what campaign events each contact triggered and what time. 
- In the campaign detail you can see how many contacts went through each event.

Feel free to comment that out if the points above doesn't matter to you. But from my point of view, that's crucial part of campaign functionality.

**Comment by SteveHey** [comment]
Problem is that crucial part of campaign functionality is causing 500 errors, so not working anyway, the fix recommended creates duplicates so totally corrupts lead data....

If this is a crucial part of campaign, whilst a bug would mean currently Mautic is very broken as far as campaigns are concerned and not really viable for campaign production services......

We are seeing this error reported in many posts on here and think we really need to get this sorted, is there any news on the big campaign updates that are being done...?????

Server logs show no errors on this when we get 500 error so definitely a Mautic bug.

You would think that if this bug is a crucial part of campaign functionality that it would be escalated and a fix chased as bug of an urgent nature....

**Comment by escopecz** [comment]
Please check if https://github.com/mautic/mautic/pull/5599 won't fix the issue.
