### ISSUE TITLE
Mautic Update failed 2.12.1 to 2.12.2 Beta

### ISSUE THREAD

**Issue by kolinz** [mautic/mautic#5656]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I cleared cache folder before update.
It was displayed download error of 2.12.2 Beta during run the update. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.24
| Apache | 2.4.6
| OS | CentOS 7.4 64bit

### Steps to reproduce:
1. cd /var/www/html/mautic
2. /usr/bin/php app/console cache:clear
3. /usr/bin/php app/console mautic:update:find
4. /usr/bin/php app/console mautic:update:apply
5. press the y key
 
### Log errors: 
[2018-01-30 02:40:40] mautic.WARNING: Command `mautic:update:apply` exited with status code 1 [] []

**Comment by escopecz** [comment]
Please use the upgrade script linked in each [release notes](https://www.mautic.org/topic/2-12-1-released/). Let us know if it helped. I'll close this issue for now.

**Comment by kolinz** [comment]
@escopecz -san
Thank you for your reply.
I tried upgrade script but could not upgrade. 
displayed error message.

```
# cd /var/www/html/mautic
# wget https://raw.githubusercontent.com/mautic/mautic/master/upgrade.php
# /usr/bin/php app/console cache:clear
# chown -R apache:apache /var/www/html/mautic
# /usr/bin/php upgrade.php
Checking for new updates...updating to 2.12.2 beta!
Extracting the update package...failed. Could not open or read update package.
```
Best Regards

**Comment by escopecz** [comment]
There is some issue with permissions. Is apache the right user:group? Try also
```
find . -type d -exec chmod 755 {} \;
find . -type f -exec chmod 644 {} \;
```

**Comment by kolinz** [comment]
@escopecz -san
Thank you for your reply.
I could not upgrade. 

```
# cd /var/www/html/mautic/
# find . -type d -exec chmod 755 {} \;
# find . -type f -exec chmod 644 {} \;
# /usr/bin/php upgrade.php
Checking for new updates...updating to 2.12.2 beta!
Extracting the update package...failed. Could not open or read update package.
```
but , I had update successful until 2.12.1.
Is there anything else need to do for the upgrade script ?

Best Regards.

**Comment by escopecz** [comment]
PHP-ZIP extension is installed? That's the last thing I can think of.

**Comment by kolinz** [comment]
@escopecz -san

Thank you for you reply.
update PHP-ZIP extension but could not upgrade.

```
# /usr/bin/php upgrade.php
Checking for new updates...updating to 2.12.2 beta!
Extracting the update package...failed. Could not open or read update package.
```

There may be a problem with the file name obtained by the upgrade script.
Now, The File name is "2.12.2 beta-update.zip". I think 2.12.2 beta-update.zip is 2.12.2-beta-update.zip.
What do you think ?

```
# cd /var/www/html/mautic/
# ls -la
-rw-r--r--  1 apache apache    182 10月 27 09:25 .env.dist
drwxr-xr-x  2 apache apache     86  9月  7 01:27 .github
-rw-r--r--  1 apache apache   1694  9月  7 01:27 .gitignore
-rw-r--r--  1 apache apache   4835  1月  5 11:38 .htaccess
-rw-r--r--  1 apache apache    476  9月  7 01:27 .php_cs
-rw-r--r--  1 apache apache   1086  9月  7 01:27 .travis.yml
drwxr-xr-x  2 apache apache      6  2月  1 01:00 .well-known
-rw-r--r--  1 apache apache    302  2月  4 13:43 2.12.2 beta-update.zip
-rw-r--r--  1 apache apache   1859  9月  7 01:27 Gruntfile.js
-rw-r--r--  1 apache apache  38407  1月  5 11:38 LICENSE.txt
-rw-r--r--  1 apache apache  17009 10月 27 09:25 README.md
drwxr-xr-x 10 apache apache    315 10月 27 09:25 app
drwxr-xr-x  2 apache apache    149 10月 24 19:39 bin
drwxr-xr-x  4 apache apache    137  9月  7 01:27 build
-rw-r--r--  1 apache apache    382 10月 27 09:25 codeception.yml
-rw-r--r--  1 apache apache   5351  9月  7 01:27 composer.json
-rw-r--r--  1 apache apache 318862  9月  7 01:27 composer.lock
-rw-r--r--  1 apache apache     18  1月  5 11:38 critical_migrations.txt
-rw-r--r--  1 apache apache  12862  1月  5 11:38 favicon.ico
-rw-r--r--  1 apache apache    992  1月  5 11:38 index.php
-rw-r--r--  1 apache apache    817  9月  7 01:27 index_dev.php
drwxr-xr-x  7 apache apache     72 10月 25 12:21 media
-rw-r--r--  1 apache apache   4043  1月  5 11:38 offline.php
-rw-r--r--  1 apache apache  10487  1月  5 11:38 package-lock.json
-rw-r--r--  1 apache apache    394  9月  7 01:27 package.json
drwxr-xr-x 12 apache apache    301  9月  7 01:27 plugins
-rw-r--r--  1 apache apache    224  1月  5 11:38 robots.txt
drwxr-xr-x 22 apache apache   4096 12月 26 14:50 themes
drwxr-xr-x  3 apache apache     33 10月 27 09:25 translations
drwxr-xr-x  8 apache apache    233 12月  6 09:08 upgrade
-rw-r--r--  1 apache apache  43606  2月  4 13:41 upgrade.php
drwxr-xr-x 61 apache apache   4096 12月 28 15:21 vendor
```
Upgrade via web browser, it displayed download error message.

**Comment by escopecz** [comment]
I think that this was fixed here: https://github.com/mautic/mautic/pull/5422

Do you use the latest version of the upgrade script?

**Comment by kolinz** [comment]
@escopecz -san

Thank you for your reply.
I used the following upgrade script. Is not this the latest version ?
https://raw.githubusercontent.com/mautic/mautic/master/upgrade.php

Best Regards.

**Comment by escopecz** [comment]
It seems to contain all the latest changes. I'm out of ideas then.

**Comment by dongilbert** [comment]
There was an error on our side that prevented the update from being able to be downloaded correctly. Can you try again @kolinz? We addressed it

**Comment by kolinz** [comment]
@dongilbert -san

Thank you for your reply.
I could update successful to Mautic 2.12.2 Beta.
I am grateful for your support.

Best Regards.

```
# /usr/bin/php upgrade.php
Checking for new updates...updating to 2.12.2-beta!
Extracting the update package...done!
Moving files...done!
Clearing the cache...done!
Rebuilding the cache...done!
Applying migrations...done!
Cleaning up...done!
```
