### ISSUE TITLE
Sparkpost Log data: !! (code: 0) Error

### ISSUE THREAD

**Issue by ninjoan** [mautic/mautic#5657]
| Q   | A
| --- | ---
| Mautic version | Serverals
| PHP version | 

### Steps to reproduce:
1. when you press test connection using Sparkpost Email services you get this response from Mautic 
2. Log data: !! (code: 0)
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by bunce69** [comment]
+1

**Comment by bunce69** [comment]
already has more than 'max_user_connections' active connections (uncaught exception)

**Comment by kuzmany** [comment]
This help https://github.com/mautic/mautic/pull/5057 in our Mautic 2.9.2 instances
