### ISSUE TITLE
segment not public is not available in campaign condition

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5658]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
If a segment is public
![image](https://user-images.githubusercontent.com/31535432/35577654-51d19426-05e2-11e8-97b1-6d54a621ecec.png)
I can find it on the segments list when I add a condition on contact segment in campaign
![image](https://user-images.githubusercontent.com/31535432/35577757-8da85ff2-05e2-11e8-8e31-f0c9519fca98.png)

But if the segment is not public I cannot find it on the segments list on contact segment condition in campaign.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 

### Steps to reproduce:
1. Create a segment and make it public
2. Create a campaign, start with a segment and add a condition on contact segments.
3. Find your segment on the list
4. Go back on the edition of the segment you created and make it not public
5. Go back on the contact segment condition and find your segment on the list > it is not displayed anymore
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Ready to test

**Comment by escopecz** [comment]
It's working correctly. A user can select global or own private segments. A user cannot select private segments of other users.

One question. Do you mean public or published? Because unpublished segments will not show in the select box.

**Comment by npracht** [comment]
Hello @escopecz,

The issue is that for the preference center you have to disable public if you don't want to show the segment on it. But that has nothing related to private (owned by someone).

So according to what you say is that mautic mixes 2 features here:
- owning a segment: then just the owner can see it
- making the segment visible or not on preference center ----> then you don't see the segments you want to see in the campaign builder (this is the issue here)

But unfortunately those 2 features are based on the same button.
_______________

I think then #5660 is a quick fix and we should consider having as a feature request another button on the interface of segments like:
![capture d ecran 2018-03-22 a 11 26 23](https://user-images.githubusercontent.com/14075239/37765208-e7f6d05c-2dc3-11e8-9c2c-d71de588d262.png)

What do you think ?

**Comment by escopecz** [comment]
As far as I know the Public switch is telling whether the segment will be visible for other users since Mautic 1.0.0. The preference center was added later. I agree with your suggestion for the new switch.

I'd like @alanhartless to give his input before we decide what to do with #5660.

**Comment by alanhartless** [comment]
Non public segments are meant to be used by the user to organize their contacts however they want. Public segments are meant for anyone in the organization and the preference center. I can definitely see the use case for separating organization only visible segments and those on the preference center. 

I recognize the confusion that we allow private segments in campaigns which don't have extended permissions (view own, view other, etc). Maybe we need to add those extended permissions. Only other option is to restrict campaigns to global only segments but that's going to cause a big BC issue.

**Comment by alanhartless** [comment]
Cross posting this here: 
```
Adding a toggle to differentiate for the preference center is a good idea. The UX would need to be, the toggle only shows up if showing segments on the preference center is enabled in the configuration (otherwise defaults to false) and the database migration will set to true for any already set to global/public.
```

**Comment by npracht** [comment]
Label: Ready to test

**Comment by escopecz** [comment]
@johbuch can you get some info on if you mean public/private for another user then you or if you mean published? Because it works the way you described it should.

**Comment by johbuch** [comment]
@escopecz in my issue, I was talking about public segment. If a segment was set as no public, it was not displayed in the segment condition in campaign?

It works now as it has been solved.

**Comment by npracht** [comment]
@escopecz

He meant public. Johan is from my team.

What I’ve been explaining in the previous comments is the issue:
Preference center segment view uses private segment feature which is meant for user rights.
We should have another button on the segment configuration to choose if the segment should be displayed or not on the preference center.

N.

**Comment by npracht** [comment]
@kuzmany with the Alan's comments here above you have everything you need?

**Comment by kuzmany** [comment]
@npracht Looks like the same solution like what I wrote here https://github.com/mautic/mautic/pull/6312#issuecomment-404409287 :)

**Comment by npracht** [comment]
So let's go ?

**Comment by kuzmany** [comment]
@npracht as Webmecaniktask? :)

**Comment by npracht** [comment]
Yes

**Comment by kuzmany** [comment]
Please let's test: https://github.com/mautic/mautic/pull/6410

**Comment by Woeler** [comment]
Merged
