### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by fgauttron** [mautic/mautic#5664]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
We can no longer validate any form. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | PHP Version 5.6.33-0+deb8u1

### Steps to reproduce:
1. 
2. 
 
### Log errors: 
mautic.NOTICE: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT COUNT(l.id) as count FROM leads l LEFT JOIN users u ON u.id = l.owner_id WHERE (l.firstname IN ()) AND (l.lastname IN ()) AND (l.twitter IS NULL)':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) AND (l.lastname IN ()) AND (l.twitter IS NULL)' at line 1 (uncaught exception) at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 while running console command `mautic:social:monitoring` [] []

**Comment by escopecz** [comment]
Closing this because of missing steps to reproduce. The error itself is not enough to fix it. Engineers must reproduce the error so they could understand what's wrong and confirm it was fixed.
