### ISSUE TITLE
Campaign inserting double dots in campaign generated link and causing 404 on click

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#5670]
Bug report

## Description:
Created an email with some copy and a link button which goes to our website.
Created campaign which sends that email to a segment
Link button has double . in the index.php so rather than the link being 
> https://domainname.com/index.php/r/ad2864b237a25c0aabe3a75a6?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czoxNDoiY2FtcGFpZ24uZXZlbnQiO2k6MTtpOjY7fXM6NToiZW1haWwiO2k6NztzOjQ6InN0YXQiO3M6MTM6IjVhNzM5YThiNWI1OTYiO3M6NDoibGVhZCI7aToyO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYWlsIjtpOjc7fX0%3D&
it is
> https://domainname.com/index..php/r/ad2864b237a25c0aabe3a75a6?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czoxNDoiY2FtcGFpZ24uZXZlbnQiO2k6MTtpOjY7fXM6NToiZW1haWwiO2k6NztzOjQ6InN0YXQiO3M6MTM6IjVhNzM5YThiNWI1OTYiO3M6NDoibGVhZCI7aToyO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYWlsIjtpOjc7fX0%3D&

then mautibot throws a 404 error

## If a bug:

| Mautic version | v2.12.1
| PHP version | PHP Version 7.0.22-0ubuntu0.16.04.1

### Steps to reproduce:
1. Create an email with a link button
2. Create a campaign that sends to a segment
3. Open the campaign sent email and click the link button
 
Last week we used the exact same process and this issue did not happen. There have been no changes on the server that runs mautic that I can account for.

### Log errors: 

No log errors are generated.

**Comment by dbhurley** [comment]
Can't replicate.

**Comment by zstephen** [comment]
@dbhurley I understand that it's necessary to replicate the issue in order to diagnose it properly.

The practical outcome of this issue is that it has effectively stopped my mautic instance from being useful at all. I just tested it and still received the double dot in the .php filename.

Can I activate debugging mode for the program which generates the link tracking URLS or something?

I need a bit of help, as the user in providing the needed error information, in order to help the developers understand and identify the core issue. This is something I enjoy about using and contributing to open source software.

Can you please give me suggestions about where might I look in my setup to see if I can gather more useful troubleshooting information in order to report back to this issue?

**Comment by zstephen** [comment]
Hi @dbhurley 

I've done more testing on this issue.

I have noticed that this double .. only gets created when I use a button link.

If I use a hyperlink in the text body the link is parsed correctly into a functioning trackable link.

Additionally, if I create a second button link, it is parsed correctly and there are no double .. in the .php link

Hopefully this helps give a bit more focus to the location of the issue, let me what other testing I can do to help further pinpoint the cause of this.

**Comment by meixger** [comment]
(just for reference and because i found this issue from google)

On a new installation v2.16.2 a link with it's href set to `{pagelink=1}` gets rendered with two dots:
`http://mautic..example.org/r/abc123`

Then i deleted and recreated the link and it works correctly:
`http://mautic.example.org/r/abc123`
