### ISSUE TITLE
Even if a user fails a Captcha test, a contact is created

### ISSUE THREAD

**Issue by ldrolez** [mautic/mautic#5671]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Even if a user fails a Captcha test, a contact is created. A bot could fill the database and disks quickly.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.27

### Steps to reproduce:
1. Create a form with a captcha field
2. Tweak the html to send a non empty captcha field value
3. Submit the form
4. Mautic replies that the answer to the captcha is incorrect
5. BUT a contact is created

**Comment by gingerling** [comment]
I can't even filter these our from a campaign anymore because "not empty" has been removed from campaign actions

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
