### ISSUE TITLE
pipedrive issue when contacts synchronized a second time after been deleted in pipedrive

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5672]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
Contacts that have been synchronized to pipedrive through campaigns, then deleted in pipedrive and pushed a second time to pipedrive through a second campaign are not synchronized anymore.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 

### Steps to reproduce:
1. Create a campaign that push contact to pipedrive
2. Add a contact to the campaign that will be synchronized to pipedrive
3. Check the contact in Pipedrive
4. In pipedrive delete this contact
5. In mautic, create a new campaign that push contact to pipedrive
6. Add the same contact to this new campaign
7. Check the campaign and check pipedrive > contact have not been synchronized a second time
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
@johbuch I think you have wrong webhook url setup in integrations.
I did tests and works properly for me. After delete in Pipedrive, contact is also deleted from Mautic and non exists contact cannot be added to campaign.
Please try retest

**Comment by kuzmany** [comment]
Label: Pending Feedback

**Comment by kuzmany** [comment]
I think in current staging 2.12.2 beta working because this improvement https://github.com/mautic/mautic/pull/5565

**Comment by johbuch** [comment]
@kuzmany I just tried again with 2.12.2 and i still have the problem

**Comment by kuzmany** [comment]
I will test again

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
@johbuch let me explain this issue. Because If you delete contact in Pipedrive, your contact is deleted also in Mautic. You cannot re-ad contact If not exist? 
Or I Something did't catch?

**Comment by npracht** [comment]
Now fixed in #5401

**Comment by alanhartless** [comment]
SEems this was fixed in 2.15.0
