### ISSUE TITLE
Updating Contact via mtc.js does not work

### ISSUE THREAD

**Issue by abomadi** [mautic/mautic#5679]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
i am adding the tracking script to my js app, however first time user is initialized as anonymous, after he login i send pageview even with user properties such as email , name etc ..
However  i found these changes under Contact > History > Event Type : Page Hit  the new information is there but the main record information does not update and the contact still as it's without any properties 

is there any other events i have to send to update the contact via mtc.js btw i have turned off fingerprint and ip tracking to enable trace the issue
## If a bug:

| Q   | A
| --- | ---
| Mautic version | Cloud Version
| PHP version | 

### Steps to reproduce:
1.  On script initialize i send mt('send', 'pageview');
2. Then i update the user mt('send', 'pageview', {Email: 'test@test.com', firstname: 'ab',lastname:"test"}, {onload: function() { alert("Tracking request is loaded"); }});

**Comment by escopecz** [comment]
"Email" must be all lowercase: "email". But firstname and lastname should work. Can you Drag&drop here a screenshot of what you can see in the contact detail?

**Comment by abomadi** [comment]
@escopecz i have tried email and both properties in different cases with no success
![image](https://user-images.githubusercontent.com/5151487/35927433-5c3212fe-0c33-11e8-9297-59467ae7d232.png)

The contact still in the above image as an anonymous visitor with no name or email the name is the IP instead.

AS you can see here in the below image the properties are updated but not reflected on the main contact information to be defined as a standard contact
![image](https://user-images.githubusercontent.com/5151487/35927538-ac41e7e2-0c33-11e8-955c-2589b189da55.png)

**Comment by escopecz** [comment]
Uh, I know what it is. You have to make the fields "publicly updatable". It's mentioned in the docs. Go to each field you are updating with the tracking code and mark it as such. It's disabled by default because it may be a security issue you should be aware about. Anyone can then update this value.

**Comment by abomadi** [comment]
Anyone who is domain enabled in the cors field right ?

**Comment by escopecz** [comment]
Anyone. The CORS restriction is integrated only to browsers. Standalone scripts does not have such restriction as far as I know.

**Comment by abomadi** [comment]
Many Thanks indeed it did work, however i will be checking the CORS restriction and update here for more information
