### ISSUE TITLE
Additional spaces while generating the text version of an email

### ISSUE THREAD

**Issue by different-thinking** [mautic/mautic#568]
When I insert text (it doesn't matter if it is copied or written) into the Body of the eMail editor and I generate the plain text version I get for every new line a additional space at the beginning of the new line in the plain version:

![image](https://cloud.githubusercontent.com/assets/10116611/8269149/fb1170fa-179d-11e5-86fd-88cfa5790405.png)

**Comment by escopecz** [comment]
I made a test and the plain text version is without spaces:
![mautictextemailgeneration](https://cloud.githubusercontent.com/assets/1235442/8454576/b0ae906a-1ffe-11e5-8f7d-95c857fb00c8.png)
Could you test that once more? Do you use the latest version?

**Comment by alanhartless** [comment]
I've tried to duplicate this one was well and can't.  Wondering if it's something with the content being used? Would you be able to copy a snippet that reproduces this issue and place it between code tags (three backticks). 

    ```
    Content here
    ```

Thanks!
Alan

**Comment by alanhartless** [comment]
Should have been fixed in 1.2 with #737.
