### ISSUE TITLE
Email Template Thumbnails are blank.

### ISSUE THREAD

**Issue by MagnusTapping** [mautic/mautic#5681]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Email Template Thumbnails are blank.

I suspect that they weren't created or installed properly during installation.  I installed Mautic on a Linode virtual server running Debian, and the installation instructions do not say which directories to chmod to what, so the first time I ran mautic I just got loads of errors before chmodding everything to be writeable by the apache user.

It could also be that a PHP function is missing, or some thumbnail-generation scripts that are not on my server or mentioned in the installation.

![screenshot 2018-02-06 10 00 37](https://user-images.githubusercontent.com/36190846/35854512-6f6909ce-0b28-11e8-93b3-4ab5f4941fff.png)

There doesn't seem to be a way to fix these template thumbnails.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.12.1
| PHP version |  7.0.27

### Steps to reproduce:
1. Install a fresh 64-bit Debian Linode
2. Install a LAMP stack
3. Run the Mautic Installer
4. Install the minimum packages to get the installation to complete
5. When you see errors, chmod the mautic install to be writeable
6. Go to create a new email

 
### Log errors: 

None that looked relevant.

**Comment by MagnusTapping** [comment]
I've just fixed this by adding |themes| into the RedirectMatch in .htaccess:

`        RedirectMatch 302 ^(?!/(index\.php|index_dev\.php|app|addons|plugins|themes|media|upgrade))(/(.*))$ /index.php$2
`

Presumably this is not how it is supposed to work though?

**Comment by dbhurley** [comment]
This has to do with your server permissions and ownership. (Hence your htaccess hack worked). Check your web service and file owner. Not a Mautic bug.

**Comment by MagnusTapping** [comment]
But what are the server permissions and ownership supposed to be?

I have the whole folder structure 777 at the moment so it seems unlikely this is stopping files from being read.

Unless the problem was on installation, when I did have the file permissions wrong at first.

It would be nice if the install threw up a warning and gave the correct permissions to be set.  I haven't find instructions for this anywhere.

**Comment by cgrover123** [comment]
I had this same issue.  It turned out to be that mod_rewrite was not enabled in Apache.
Without it on, Mautic still seemed to work normally, but I had issues with thumbnails and images in emails.
Try removing that from .htaccess and ensure that mod_rewrite is on.
1) a2enmod rewrite
2) service apache2 restart
