### ISSUE TITLE
got a segment error when campaign cloned

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5682]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Segments disapeared from the builder after cloning campaigns and updating segment. When I go back on the builder, there are not there anymore
![image](https://user-images.githubusercontent.com/31535432/35863426-e951cae8-0b4e-11e8-8539-4973f0e306d8.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 

### Steps to reproduce:
1. Clone a campaign that starts with a segment
2. Go on the builder
3. Click on the segment, do not change it (keep the same segment) but just click on update
4. Close the builder, save and close the campaign.
5. Go back on the campaign and go back on the builder,
6. You will see that there are no segments anymore
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by kuzmany** [comment]
Workaraund lets discuss https://github.com/mautic/mautic/pull/5737
I cannot find better solution at now.

**Comment by npracht** [comment]
UX has been reviexed by campaign refactoring for that issue.

**Comment by johbuch** [comment]
I still have the issue with 2.14

**Comment by kuzmany** [comment]
Try test https://github.com/mautic/mautic/pull/6818
