### ISSUE TITLE
[Enhancement] Convert attribution from a double to a decimal (support money).

### ISSUE THREAD

**Issue by heathdutton** [mautic/mautic#5684]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Yes

## Description:
The `attribution` column on the leads table is currently stored as a double floating point value. This is fine for approximate values, but since the field is intended for use as currency it could make the field a considerable headache for a finance department. In general, doubles/floats are good for science, but bad for currency.

It would be better if this were a precise decimal column instead so that rounding errors do not occur in the future. The GAAP typically recommends `DECIMAL(19, 4)` for currency which would be more than sufficient.

**Comment by npracht** [comment]
Label: Enhancement

**Comment by RCheesley** [comment]
@heathdutton looks like it is a super simple fix for the conflicts on your PR - are you able to fix it or should we ask someone in the community to take it on?
