### ISSUE TITLE
【 2.12.1】Automatic form reply mail settings are missing

### ISSUE THREAD

**Issue by tomomink** [mautic/mautic#5686]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:

When I set automatic reply mail of the form installed in ver 2.12.1, there is no item of automatic reply mail setting in the action setting. Where should I set up auto mail reply settings?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6.30

### Steps to reproduce:
1. 
Form creation
2. 
Action setting
****
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
@tomomink sorry but the message is not very clear. What do you try to do, what are you missing. Could you also describe a bit more the steps to reproduce ?

Thanks !

**Comment by npracht** [comment]
Label: Pending Feedback
