### ISSUE TITLE
Mautic Breaks WP Form Integrator

### ISSUE THREAD

**Issue by appscaptain** [mautic/mautic#5688]
What type of report is this:
| Bug report? | Y

## Description:
Some update of Mautic 2.12.1, or earlier, breaks the Wordpress plugin WP Mautic Form Integrator, that enables Wordpress users to integrate Contact Form 7, Fast Secure Forms, Ninja Forms, Formidable Forms and Gravity Forms. It’s here: https://wordpress.org/plugins/wp-mautic-form-integrator/. 

After a form submission through Contact Form 7, contacts are not tracked when they move around on the Wordpress site. No IPs or page visits are tracked.

This worked perfectly fine on at least Mautic 2.8.1 and earlier (maybe it also works on some newer versions - but not 2.12.1), so some change or bug appeared between those versions causing this.

I have followed all the troubleshooting steps for Contact tracking (different browser, private mode, check url etc. - and the pixel is loaded just fine (eg. Status 200 in the browser web tools) with all the parameters like page_title etc. all filled out correctly. I have also tried to manually install the tracking code from the "Mautic tracking settings". So the tracking pixel is definately activated but, Mautic for some reason doesn’t receive it properly.

## If a bug:
| Mautic version | 2.12.1 (maybe earlier)
| PHP version | 7.0.27

### Steps to reproduce:
This can be reproduced consistently on a clean installation of Wordpress and Mautic: 
1. Link a Contact Form 7 form to Mautic in Wordpress using WP Mautic Form Integrator
2. Submit the form (for instance with an e-mail of abc@gmail.com)
3. Visit different webpages that has the Mautic tracking pixel installed.
4. Check the Mautic Contacts section and go into the specific contact (abc@gmail.com)
You won't see neither the IP or any visited page for that contact. Only the form submission itself is tracked - nothing else. The tracking works fine with the built-in Mautic forms.

### Log errors: 

No errors in the webserver or Mautic logs.

**Comment by fspestana** [comment]
@dbhurley Did you find a solution? I'm in a similar situation, but with gravity forms where mapping is not working. (/wp-admin/admin.php?page=haw-mautic-integration-add-new)

If someone has some news, please, let us know.

**Comment by igordisco** [comment]
I managed to find a solution
