### ISSUE TITLE
Mautic Forms Don't Work With Campaign Enabled 500 Error

### ISSUE THREAD

**Issue by bon8699** [mautic/mautic#5689]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
My Mautic forms work perfectly fine when I create them and test the HTML. My Mautic is also sending my autoresponder message just fine. The problem is when I enable the campaign and test the HTML I get a 500 error saying "Uh oh! I think I broke it. If I do it again, please report me to the system administrator!" It doesn't matter what options I choose in the campaign, just enabling it will disable the form and pretty much makes Mautic useless to me as this is the core feature I plan to use. 

I know nothing about coding but do know how to get into files and change stuff if needed. I have been chasing this issue for over a week now. Error log below happens as soon as I visit and submit the form.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 

### Steps to reproduce:
1. Enable Campaign
 
### Log errors: 

MySQL server has gone away in /home/myusername/web/mysite.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105

Error reading result set's header in /home/myusername/web/mysite.com/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 105

**Comment by dbhurley** [comment]
Support should be looked for in the forums or Slack channel, not GitHub...probably why you didn't get any replies. Hope this helps point you in a better direction!
