### ISSUE TITLE
Theme changes on Landing Page

### ISSUE THREAD

**Issue by Captivea-CBO** [mautic/mautic#5690]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | No 
| Enhancement? | No

## Description:
When a theme is updated on administration, existing landing pages using this theme are not updated. A new landing page need to be create to see the update

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.19-1

### Steps to reproduce:
1.  Create a Landing page 'test LP' with theme 'test_theme'
2.  Download this theme and make some modification
3. Upload this theme
4.  View the landing page 'test LP' ==> Changes are not shown
5. A new Landing page using theme 'test_theme' works fine

**Comment by npracht** [comment]
@Captivea-CBO the theme is not retroactively applied because the HTML is stored in DB for each Landing Page created. The theme is not an external dynamic resource.

Consequently i wouldn't say it is a bug. Just something to know that it is working that way.

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by Captivea-CBO** [comment]
@npracht Thanks for your answer. Would it be possible to add a feature to force the theme update for a Landing Page ? A button for example ?

**Comment by npracht** [comment]
Hello @Captivea-CBO 
Yes it could, most everything is possible. But what do you do of already existing content and HTML. Everything will be erased? If yes you can simply today edit you LP, change theme to blank, take back you favorite theme, launch builder and then you'll notice your HTML is virgin with new HTML version of your updated theme.
