### ISSUE TITLE
issue in emails dynamic content with filter on contact owner

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5691]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When I want to add a filter on the contact owner on a dynamic content in emails, I do not have the select list of users. So I cannot choose an owner.
![image](https://user-images.githubusercontent.com/31535432/35924186-9cb38e68-0c22-11e8-9c4e-db80d1a1c5a2.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 

### Steps to reproduce:
1. Create an email
2. Go on the builder and add a dynamic content bloc
3. Add a variation
4. Add a filter and choose contact owner
5. The list of users does not appear
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by justinfortes** [comment]
@johbuch if you add a persons name can you still achieve the same result?

**Comment by johbuch** [comment]
hello @justinfortes 
I tried to copy this from the users tab
![image](https://user-images.githubusercontent.com/31535432/36090680-93c3d462-0fe1-11e8-89b9-03c0fa19f54e.png)
and paste it to filter
![image](https://user-images.githubusercontent.com/31535432/36090715-b59cc904-0fe1-11e8-9120-4511d92f09d9.png)
But then I got a bug I cannot save the email.
I also tried to start writing but there is no owner appears.

**Comment by kuzmany** [comment]
Label: Ready to test

**Comment by kuzmany** [comment]
Lets test https://github.com/mautic/mautic/pull/5741
