### ISSUE TITLE
Object of class Closure could not be converted to int

### ISSUE THREAD

**Issue by mtahiue** [mautic/mautic#5693]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I've created a dynamic content
I've added a translation
I could not edit the translated content anymore

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.24

### Steps to reproduce:
1. Create a Dynamic Content with a focus inside ( for example {focus=2} ) : the parent
2. Clone this Dynamic Content and set this new one as a translation of the previous : the child
3. Edit the parent and clic on the translations: pickup the child
4. Clic on modify > nothing append

 
### Log errors: 

mautic.NOTICE: PHP Notice - Object of class Closure could not be converted to int - in file /var/www/html/app/bundles/CoreBundle/Form/ChoiceLoader/EntityLookupChoiceLoader.php - at line 154 [] []
mautic.NOTICE: PHP Notice - Object of class Closure could not be converted to int - in file /var/www/html/app/bundles/CoreBundle/Form/ChoiceLoader/EntityLookupChoiceLoader.php - at line 154 [] []
mautic.NOTICE: PHP Notice - Undefined offset: 37 - in file /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/SQLParserUtils.php - at line 131 [] []
mautic.NOTICE: PHP Notice - Undefined offset: 37 - in file /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/SQLParserUtils.php - at line 135 [] []
mautic.WARNING: PHP Warning - array_merge(): Argument #2 is not an array - in file /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/SQLParserUtils.php - at line 136 [] []
mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Doctrine\DBAL\Connection::_bindTypedValues() must be of the type array, null given, called in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 846 - in file /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - at line 1477 [] []

**Comment by wucherpfennig** [comment]
#6133

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by RCheesley** [comment]
Just came across this testing for Mautic 5 so it's still an issue 😳
