### ISSUE TITLE
clone campaign kills the date of an action

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#5696]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When you clone a campaign that has an action (email for instance) set for a specific date (not relative), the new campaign has the same date stored in DB event if you modify it from the interface.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 

### Steps to reproduce:
1. Create a campaign > action email > specific date `2018-12-12 00:00:00` > save and close
2. Clone campaign
3. Modify the clone and set the specific date to `2018-12-30 00:00:00` > save and close
4. Check in DB for the setting of the campaign event of the clone > see that this is the OLD date still saved

**--> the consequence is that when the campaign will run, the email will be sent at the OLD date instead of the modified one.**

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
@justinfortes why in the patch of 2.13 and not directly targeted in 2.13.0 as far as it is a bug ?

**Comment by dbhurley** [comment]
Probably because there's no one assigned to it and no one working on it yet. We need WIP before we can pick a milestone for it.

**Comment by npracht** [comment]
@dbhurley as you saw it has been tagged before my comment ---> that's why i asked this question.
