### ISSUE TITLE
api contact endpoint error

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#5698]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
When you use `/api/contacts?limit=5&start=0&orderBy=lastActive&orderByDir=desc` according to the API documentation, you get a 500 error.

Then i tried `/api/contacts?limit=5&start=0&orderBy=last_active&orderByDir=desc` and it works. I don't know if the issue is the documentation or the software. I have the feeling that the first query was working in the past.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version |

**Comment by npracht** [comment]
Label: Bug

**Comment by Woeler** [comment]
Can confirm. In the response the field is called 'lastActive', as is in the documentation. However, the api query only works if you use the database column name.

**Comment by dbhurley** [comment]
Agreed - dev docs should be updated.

**Comment by Woeler** [comment]
https://github.com/mautic/developer-documentation/pull/95
