### ISSUE TITLE
Campaign Lists

### ISSUE THREAD

**Issue by lance-spurgeon** [mautic/mautic#57]
When you save and close a campaign and click on the link it doesn't open the campaign you have to click on the edit button in the dropdown list.
If you clone a campaign and keep the "Smart List" the same ... when you go to build your campaign all the connection are disconnect "They all get bunched up on top of each other in the top left corner"

**Comment by alanhartless** [comment]
https://github.com/mautic/mautic/commit/a79c1c21449c1e3f77d8446e56d3331f867c1fea fixes the campaign cloning issue. 

I can't reproduce the link issue though.  I'm assuming you are referring to the link in the flash message? 

Thanks,
Alan

**Comment by alanhartless** [comment]
I believe we resolved this today.  If not, let me know.

Thanks,
Alan
