### ISSUE TITLE
Mandrill error on send test mail

### ISSUE THREAD

**Issue by sfahrenkrog** [mautic/mautic#570]
If I hit the "Send Test mail" button there is an error on the php log: 

```
<b>Fatal error</b>:  Call to a member function getTranslator() on null in <b>/html/mautic/app/bundles/CoreBundle/Swiftmailer/Transport/MandrillTransport.php</b> on line <b>74</b><br />
```

Mautic v1.1.2 on PHP 5.6.5

**Comment by alanhartless** [comment]
Hi and thanks for reporting this. It's been fixed with https://github.com/mautic/mautic/pull/564 and will be part of the next release. 

Thanks!
Alan

**Comment by sfahrenkrog** [comment]
Same issue in Class ProcessEmailQueueCommand using Mautic v1.2.1

```
sudo --user=www-data /usr/bin/php app/console mautic:email:process --env=prod
```

PHP Fatal error:  Call to a member function getTranslator() on a non-object in /var/www/vast-landingpage/htdocs/app/bundles/CoreBundle/Swiftmailer/Transport/MandrillTransport.php on line 74

Fixed it locally with adding 

```
        $factory = $container->get('mautic.factory');
        if (method_exists($transport, 'setMauticFactory')) {
                        $transport->setMauticFactory($factory);
        } 
```
to  app/bundles/CoreBundle/Command/ProcessEmailQueueCommand.php
