### ISSUE TITLE
mautic:integration:fetchleads is single threaded

### ISSUE THREAD

**Issue by YosuCadilla** [mautic/mautic#5703]
| Bug report? | 
| Feature request? | 
| Enhancement? | 

NOT SURE

## Description:
I am importing a large amount of leads from SF into Mautic using mautic:integration:fetchleads.
I have noticed that this script is using only 1 CPU on my server (AWS instance with 4 VCPUs), which makes the import job 4 times slower than it could be in my case, but could be making it 8, 16 or 32 times slower than it could be on bigger servers.

| Mautic version: 2.12.1 
| PHP version: 7.0.25
Database: MariaDB  10.0.33
OS Ubuntu 16.04
Platform AWS-EC2 m4.xlarge

### Steps to reproduce:
1. Connect Mautic to Salesforce Using the SF plugin. (guess the behavior should be the same for any other CRM integration) 
2. Import (fetch) leads from Salesforce using mautic:integration:fetchleads
 
### Log errors: 

There are no errors.

**Comment by dbhurley** [comment]
Not necessarily a Mautic bug.

**Comment by YosuCadilla** [comment]
Really @dbhurley ? And what if it is?

**Comment by escopecz** [comment]
Multithreaded implementation of the import is a feature that has never be added. So it's not broken, not a bug. Feature requests are tracked here: https://www.mautic.org/forums/forum/ideas/

**Comment by YosuCadilla** [comment]
It's not the import alone, all of the symphony based scripts using the composer API system are single threaded, that menas leads import yes, but also updates, fetches, pushes... and it also means all the rest of commands for segments, campaigns and what not... everything that goes in the crontab!

**Comment by escopecz** [comment]
Yep, I didn't say other commands are multithreaded either. I don't understand what Symfony or Composer has to do with it. It's not a trivial task to do. The threads must know what part of the CSV file to import so they wouldn't import the same contacts.

**Comment by YosuCadilla** [comment]
CSV? I was talking about mautic:integration:fetchleads

**Comment by escopecz** [comment]
Aha, I came here by a link from a Slack discussion about slow imports. Fetchleads would be even more tricky.

**Comment by YosuCadilla** [comment]
Well, the OP on the slack thread was talking about csv import I believe...
