### ISSUE TITLE
Campaign trigger causes PT1D error

### ISSUE THREAD

**Issue by tadinski** [mautic/mautic#5705]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | ✅
| Feature request? | 
| Enhancement? | 

## Description:
Running a cron command **mautic:campaigns:trigger** results in `mautic.NOTICE: Exception: DateInterval::__construct(): Unknown or bad format (PT1D) (uncaught exception) at /x/x/domains/xxxx/public_html/app/bundles/CampaignBundle/Model/EventModel.php line 1703 while running console command mautic:campaigns:trigger [] []`

Tried running the cron command with php version 5.6 and 7.0, same error.

Tried running command **mautic:campaigns:trigger -vv** this is what I get:

`Exception trace:
 () at /home/xxx/domains/xxx/public_html/app/bundles/CampaignBundle/Model/EventModel.php:1703
 DateInterval->__construct() at /home/xxx/domains/xxx/public_html/app/bundles/CampaignBundle/Model/EventModel.php:1703
 Mautic\CampaignBundle\Model\EventModel->executeEvent() at /home/xxx/domains/xxx/public_html/app/bundles/CampaignBundle/Model/EventModel.php:939
 Mautic\CampaignBundle\Model\EventModel->triggerScheduledEvents() at /home/xxx/domains/xxx/public_html/app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php:163
 Mautic\CampaignBundle\Command\TriggerCampaignCommand->execute() at /home/xxx/domains/xxx/public_html/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /home/xxx/domains/xxx/public_html/vendor/symfony/console/Application.php:891
 Symfony\Component\Console\Application->doRunCommand() at /home/xxx/domains/xxx/public_html/vendor/symfony/console/Application.php:202
 Symfony\Component\Console\Application->doRun() at /home/xxx/domains/xxx/public_html/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/xxx/domains/xxx/public_html/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at /home/xxx/domains/xxx/public_html/app/console:41`

**The specific campaign that causes this error has 14 relative period actions, none of them are specific dates.**

<img width="588" alt="screen shot 2018-02-10 at 17 02 32" src="https://user-images.githubusercontent.com/6358371/36063982-7b895222-0e84-11e8-9b97-7335afed7c5b.png">

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 7.0

### Steps to reproduce:
Don't know
 
### Log errors: 

`mautic.NOTICE: Exception: DateInterval::__construct(): Unknown or bad format (PT1D) (uncaught exception) at /x/x/domains/xxxx/public_html/app/bundles/CampaignBundle/Model/EventModel.php line 1703 while running console command mautic:campaigns:trigger [] []`

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by tadinski** [comment]
Sorry, can’t confirm, I have ceased using Mautic for the time being.

**Comment by npracht** [comment]
Then i'll close it and reopen if someone meets this issue.
