### ISSUE TITLE
SparkPost API Changes

### ISSUE THREAD

**Issue by PeterTL** [mautic/mautic#5707]
Hi,

Per today SparkPost changed its email API. I found this information regarding the change:

> Summary of the current and future behavior
> The following is a summary of the current and future behavior for when a recipient is suppressed
> 
> **SMTP**
> 
> - Current: return a ‘250 Ok’ and ‘policy rejection’ event (no injection event)
> - Future: return a ‘250 Ok’ with ‘injection’ event followed by a ‘bounce’ event
> REST API
> 
> **Single recipient transmission**
> 
> - Current: return a 400 with special error message, followed by a ‘generation rejection’ event
> - Future: return a 200 with an ‘injection’ event followed by a ‘bounce’ event
> Multiple recipient transmission
> 
> - Current: return a 200 followed by a ‘generation rejection’ event (no injection event)
> - Future: return a 200 with an ‘injection’ event followed by a ‘bounce’ event
> 
> When a bounce is generated due to suppression the webhook will have bounce_class of “25” and an error_code of “554” and reason of “Recipient address was suppressed due to customer policy” or “Recipient address was suppressed due to system policy”

Source: https://www.sparkpost.com/blog/upcoming-api-transmission-endpoint-changes/

I want to encourage anyone with the appropriate technical skill to take a look and evaluate if the changes affect the way Mautic works with SparkPost or even breaks it.

All the best,

Peter

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by PeterTL** [comment]
@npracht, "Pending Feedback" indicated that you need feedback from me. How can I help? :-)

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
