### ISSUE TITLE
Forms included in website do not redirect when Mautic is installed in a subfolder

### ISSUE THREAD

**Issue by xavierpaz** [mautic/mautic#5710]
What type of report is this:

| Bug report? | 

## Description:
I have Mautic installed in a folder: https://www.xavierpaz.com/m/. 

I have created a form with a redirection. I include the form in the website using this code:

<script type="text/javascript" src="//www.xavierpaz.com/m/form/generate.js?id=2"></script>

And this JS file includes this declaration:

var MauticDomain = 'https://www.xavierpaz.com/m';

However, this variable is checked against the site domain in media/jsmautic-form.js before the response is parsed and the redirection is made:

if (event.origin !== MauticDomain) return;

In my case, the value of event.origin is 'https://www.xavierpaz.com'.

## If a bug:

| Mautic version | Seen in 2.12.1
| PHP version | Seen in 5.6.31

### Steps to reproduce:
1. Install Mautic in a subfolder
2. Create a form with a final redirection
3. Paste the JS code in a page in the site, and submit
 
### Log errors: 

There are no error logs.

**Comment by MaMuk** [comment]
Hello, I currently have the same problem. I digged through the closed Issues and it seems that there will be a fix for this issue with 2.12.2 accordingt to @alanhartless in https://github.com/mautic/mautic/issues/4287

**Comment by xavierpaz** [comment]
I agree, it is the same issue, and is fixed in next release.

**Comment by npracht** [comment]
Label: Bug

**Comment by RCheesley** [comment]
Is this still a bug @xavierpaz @MaMuk ?

**Comment by npracht** [comment]
Fixed in 2.12.2
