### ISSUE TITLE
Dynamic Content not working on v2.12.1

### ISSUE THREAD

**Issue by heanfig** [mautic/mautic#5711]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The dynamic content does not work, I use the HTML markup and it does not render on the website, I was reviewing records of similar past errors, and they said that it would review the network tab but it does not generate any response

test in website : [https://zopp.co/demositio/](https://zopp.co/demositio/)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.12.1
| PHP version | 5.6

### Steps to reproduce:
1. Create Dinamic Content (with campaign or single) and asociate to website using HTML markup 
`<div class="mautic-slot" data-slot-name="contenido-dinamico-exploracion">&nbsp;</div>`
2. See Website and lookup the network Tab 

![captura de pantalla 2018-02-13 a las 6 24 07 p m](https://user-images.githubusercontent.com/4906962/36179818-ebf38fbe-10eb-11e8-86a1-8dac1c0a205e.png)

![captura de pantalla 2018-02-13 a las 6 23 05 p m](https://user-images.githubusercontent.com/4906962/36179617-fdd492a6-10ea-11e8-80c3-1d1c118205f6.png)

not response

![captura de pantalla 2018-02-13 a las 6 23 16 p m](https://user-images.githubusercontent.com/4906962/36179626-098bd47e-10eb-11e8-9e06-c671427e5f79.png)

### Log errors: 
Not Log Errors

test in website : [https://zopp.co/demositio/](https://zopp.co/demositio/)

Thanks 👍

**Comment by dbhurley** [comment]
Not replicable. I'd recommend asking in the forums or Slack channels.
