### ISSUE TITLE
Hubspot plugin creates duplicate contacts on email change

### ISSUE THREAD

**Issue by afonseca08** [mautic/mautic#5712]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When updating the email address of a contact in Hubspot that already exists in Mautic, a duplicate contact is created in Mautic with the new e-mail address. The expected behavior of the sync plugin is that the Mautic contact would have it's email address updated to the newly changed e-mail address in Hubspot.

This bug can result in the contact being subscribed to email campaigns which they no longer want to be receiving at the old email address as well as new campaigns being started at the new email address. This can create a bad customer experience and is not behavior Mautic Hubspot plugin users would know about until they receive customer complaints.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6.33

### Steps to reproduce:
1. Create a contact in Hubspot 'John Doe' with an email address, 'john@mydomain.com'
2. Verify the 'John Doe' contact has sync'd and is now created in Mautic.
3. In Hubspot, update the email address of 'John Doe' to 'johndoe@mydomain.com'
4. In Mautic, after sync, observe a duplicate contact 'John Doe' is created with the email 'johndoe@mydomain.com'.

### Log errors: 
No errors reported.

**Comment by npracht** [comment]
Label: Bug

**Comment by billm950** [comment]
this is still happening.

**Comment by jordan8037310** [comment]
If you want to fix this you can create a HubSpot Contact ID field in Mautic and make it a Unique field. That way when the new contact gets created, based on the new email address, it will collapse into the other contact (deduplicate) due to the HubSpot Contact ID. I suspect this strategy would work for sync of any third-party ID, but be careful with the setup.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by ksoekhram** [comment]
Hi, I can confirm this is still an issue as I am testing my setup right now. Please note I am probably not that tech savy like most here, but I will help where possible. 

I am running Mautic 3.1. So far everthing else works, except:

- The duplicate contact creation upon email change
- And there is no bidirectional updating going on: only Mautic is updated

Br,
Karan
