### ISSUE TITLE
Error when I try to send a broadcast email (DB broken)

### ISSUE THREAD

**Issue by maxitromer** [mautic/mautic#5716]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

I'm having this issue for the last week.

Every time I want to send and email (as inmediate send or scheduled broadcast) mautic gives me the same error:

`[Symfony\Component\Debug\Exception\ContextErrorException]
  Catchable Fatal Error: Argument 1 passed to Swift_Transport_AbstractSmtpTransport::send() must implement interface
  Swift_Mime_Message, boolean given, called in /var/sentora/hostdata/zadmin/public_html/mautic_oleo/vendor/swiftmaile
  r/swiftmailer/lib/classes/Swift/FileSpool.php on line 169 and defined`

As I sayd, I was trying to send as inmediate or scheduled and I was trying to send via the console as well with `mautic:emails:send` and I have the same result.

And when I try this for many times the DB brokens.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 5.16

### Log errors: 

mautic.NOTICE: Symfony\Component\Debug\Exception\ContextErrorException: Catchable Fatal Error: Argument 1 passed to Swift_Transport_AbstractSmtpTransport::send() must implement interface Swift_Mime_Message, boolean given, called in /vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 169 and defined (uncaught exception) at /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 149 while running console command `mautic:emails:send`

**Comment by dbhurley** [comment]
Sounds like you have enabled a mail type without having the proper config setup for it? Can you check your settings? Did you happen to change anything or has it never worked for you? I can't replicate so I'm tempted to redirect to a support channel, but will leave this open temporarily.

**Comment by maxitromer** [comment]
Thanks for your answer @dbhurley 

The problem was that the hard drive in my server was out of space.

I upgrade my hosting account and all was solved.
