### ISSUE TITLE
Campaign scheduled Time and Dashboard Upcoming Emails show different time value

### ISSUE THREAD

**Issue by void-gh** [mautic/mautic#5719]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? | 

## Description:
Created a simple campaign for testing purposes. Configured an email to be sent at noon in local timezone. The campaign builder UI displays the correct time and timezone.

![01_campaign_builder_cropped](https://user-images.githubusercontent.com/30275401/36280913-542e1c18-1248-11e8-9c00-d05e5f05d1ae.png)

Save all settings, publish the campaign, and save and close. Click on the _Dashboard_ link. Wait for cron jobs to process then scroll down to _Upcoming Email_. There are entries corresponding to people in the target segment; however, the timestamp associated with when the emails are to be sent are displayed as 9 hours later in the same timezone.

![02_dashboard_upcoming_cropped](https://user-images.githubusercontent.com/30275401/36280924-5b4802ca-1248-11e8-95ef-3d1feaaf85e9.png)

The emails do appear to actually be sent at the correct time, only the UI appears to be providing inconsistent information.

I have checked and the host server, Mautic's default timezone, and the specific user that is signed in are all set to the same timezone.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.1.11

### Steps to reproduce:
1. Create a campaign and open campaign builder
2. From Contact Sources, select Contact Segment then select desired segment, click Add.
3. Add an Action, select Send email.
4. Complete Send email form and select at a specific date/time, set date & time, select transactional email type. Click Add.
5. Click Apply
6. Click Close Builder.
7. Publish the campaign.
8. Set the publish at and unpublish at values.
9. Click Apply
10. Click Save & Close
11. Wait for cron jobs to run and then check Dashboard values.
 
### Log errors: 

No relevant errors appear in the Mautic log file.

**Comment by npracht** [comment]
Label: Bug

**Comment by void-gh** [comment]
After updating Mautic to version 2.13.1 this issue still exists.

**Comment by void-gh** [comment]
Mautic version 2.14.1 still has this issue.  If there is any specific info that would be useful let me know and I'll dig it up.

**Comment by petebytes** [comment]
I am running 2.15.2 and seem to have the same issue.

![image](https://user-images.githubusercontent.com/676739/63035048-4c2a5200-be6f-11e9-96a4-0acc9bdef30d.png)

Email is sent at correct time and Upcoming Events on Contact page show UTC
![image](https://user-images.githubusercontent.com/676739/63036699-6ca7db80-be72-11e9-8b87-dbe2aceac0ff.png)

**Comment by jadersilvabr** [comment]
Hello everybody,

I'm using Mautic 2.16.0 and I have the same issue.

**Comment by RCheesley** [comment]
Closing as this relates to 2.x and there have been a bunch of timezone-related fixes since then.
