### ISSUE TITLE
Cannot re-send an email to the contact

### ISSUE THREAD

**Issue by robov** [mautic/mautic#5722]
Cannot re-send an email to the contact
Would be nice and easy

**Comment by npracht** [comment]
Hello,

You can go to the contact overview page and send manually to the targeted contact.
![capture d ecran 2018-02-21 a 14 21 30](https://user-images.githubusercontent.com/14075239/36482140-89b4e492-1712-11e8-850b-2ee6334f83f4.png)

**Comment by robov** [comment]
Yes... that is a workaround... would be nice to have a button next to emails... send again... with a confirmation are you really want to...
Many times people throw an email away and simply being able to resend it is valuable
