### ISSUE TITLE
Bounced emails become bounced contact

### ISSUE THREAD

**Issue by robov** [mautic/mautic#5723]
When I create a contact, send an email to them and the email bounces, I cannot change the contacts email to resend. When I change the contact email, the send manual email reports "bounced", while in essence it was the previous email address that bounced, not the current one

**Comment by dbhurley** [comment]
It won't reset until you send an email to the new address.

**Comment by robov** [comment]
... ok... but I cannot send a new email... the contact is marked as 'bounched' so creating a new email fails..
