### ISSUE TITLE
Could not saved part of contact data from Mautic Forms in case of RFC violation email address.

### ISSUE THREAD

**Issue by kolinz** [mautic/mautic#5725]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
It was not saved part of contact data from Mautic forms. These data uses custom field in Mautic.
but was saved basic data. (First name, last name, email address, phone number, country, zip-code, state, city, address 1)
And, these data include email address of RFC violation.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6.32

### Steps to reproduce:
For example:common patterns of Japanese telecom carrier mail addresss 
abc..de@xxx.ne.jp
abcde.@xxx.ne.jp
abc..def.@xxx.ne.jp

The Mautic Forms was able to receive data from WordPress.
But These data was not able to save part of data in Mautic Contacts from Mautic forms.
These data uses custom fileds in Mautic.

![capture_20180219](https://user-images.githubusercontent.com/16685896/36360446-4b5ed010-1567-11e8-8642-a752bdab6e32.png)
 
### Log errors: 

none

**Comment by kolinz** [comment]
I also confirmed that this issue occurs even if it is a normal e-mail address.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
