### ISSUE TITLE
Allow a Message sending to be Delayed

### ISSUE THREAD

**Issue by r-martins** [mautic/mautic#5726]
What type of report is this: Feature request

## Description:
Allow us to delay the email sending for a X hours or Z minutes.
It could be placed on the send page or in the email creation.

![image](https://user-images.githubusercontent.com/191149/36414519-aa754d44-1676-11e8-84cb-b19ee2aaaeef.png)

**Comment by npracht** [comment]
Hello @r-martins,

What is the objective of that feature ?

N.

**Comment by npracht** [comment]
Label: Pending Feedback
