### ISSUE TITLE
Contact monitoring is not compatible with Content Security Policy header

### ISSUE THREAD

**Issue by Flavien** [mautic/mautic#5727]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When implementing contact monitoring on a website that has a Content Security Policy header, the following error prevents the script from running properly:

> Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'"

## Expected behaviour
The tracking script should not rely on ``eval`` as this is insecure.

## Versions

| Q   | A
| --- | ---
| Mautic version | 2.9.2
| PHP version | PHP 7.0.22-0

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Label: Ready to test
