### ISSUE TITLE
Problem when I tried to launch a campaign (Email Delivery Status)

### ISSUE THREAD

**Issue by orl99** [mautic/mautic#5729]
Hello guys
I huge problem with the campaign. I build all the strategy and all the configurations, but when I launched the campaing, in mautic shows me that all the emails had been sent successfully, but in my email inbox sunddenly it is full of "Email Delivery Status" I sent arround 2000 emails. Can you help me what really happend.
Best Regards 
Orlando Garcia
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
You probably set your email address as reply to address. And many of your contacts are bounce contacts ---> you have an answer from the server saying that the email does not existe.
