### ISSUE TITLE
Who leads have read an email

### ISSUE THREAD

**Issue by viaro-vinicio** [mautic/mautic#573]
Hi All!

I want to know if there is a way to know who leads have read the email (but not the lead details view). I need something similar to the lead history in the email view.

![mautic 1](https://cloud.githubusercontent.com/assets/7935070/8288998/ea26feba-18d6-11e5-972a-6e5fb231d7fd.png)

The other thing to I need to know is if there is a way to know the times that a lead has read the email.

**Comment by npracht** [comment]
Hi, you can create a segment with a filter "email read" = your email.
Also, the stats on emails is better details here: https://github.com/mautic/mautic/issues/3532

@escopecz i think you can close the issue :)
