### ISSUE TITLE
Updating mautic from 2.12.1 to 2.12.2

### ISSUE THREAD

**Issue by ServicedCloud** [mautic/mautic#5731]
Our current mautic version is 2.12.1. We checked that mautic pre-released 2.12.2 beta. Then we checked out our mautic for update via ssh it says "you are running the current version of mautic".  Is it possible to update mautic from 2.12.1 to 2.12.2? or are we going to wait the 2.13.0 version instead?

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | N
| Enhancement? | N

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6.33

**Comment by npracht** [comment]
Hello,

Check your version configuration to select the type of version you expect.
![capture d ecran 2018-02-21 a 14 25 33](https://user-images.githubusercontent.com/14075239/36482292-1c55318a-1713-11e8-8551-78107d640f0c.png)

**Comment by ServicedCloud** [comment]
Hi nparcht,
Thank you for your response. I now find the available update of our mautic.

**Comment by npracht** [comment]
@ServicedCloud my pleasure. Then you can maybe close this issue ?
Thanks :)
