### ISSUE TITLE
Wrong behavior with "Count URL" filter in Segments 

### ISSUE THREAD

**Issue by Lologam** [mautic/mautic#5732]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Hello,

In Segments i understand it's possible to combine “Visited URL” filter with "Visited URL Count" filter to segment only contacts who visited X time a “Visited URL” (confirmed yesterday by @kuzmany on Slack)

In fact, it doesn’t work. When i test this segment:
Visited URL = “http://www.my-url-test.com”
AND
Visited URL Count greater or egal 6

Mautic returns all contacts with minimum 1 visit of the URL “http://www.my-url-test.com” and with minimum 6 URL visited (**any** URL). I’m expecting to obtain contacts with 6 visits only for URL “http://www.my-url-test.com”.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6

### Steps to reproduce:
1. Create new segment
2. Add filter "Visited URL" and choose an URL
3. Add filter "Count Visited URL" and choose a condition
4. Inspect history of each contact added to the segment, you'll see the bug

**Comment by pawneetdev** [comment]
This works for me but I am facing a different issue. **It does not always add a contact to the segment.**

**Comment by Lologam** [comment]
Hi pawneetdev,

Can you describe the filters combination, with the type of operation to perform (equals, contains, regexp...), you are using to get right result ?

Thanks.

**Comment by pawneetdev** [comment]
I am using **Visited URL with contains** and **Visited URL Count greater than or equal to 2**

**Comment by Lologam** [comment]
Thanks pawneetdev. I just tested with your filters an I obtain contacts with:
- total of 2 or more "Visited URL" -> normal behavior 
- total of 2 or more **any** Visited URL **but only 1** "Visited URL" -> not normal behavior (I join a screenshot: only the first event match the "contains" filter, not the third)

<img width="587" alt="capture d ecran 2018-02-28 a 15 29 08" src="https://user-images.githubusercontent.com/15182052/36793095-c0e45efe-1c9c-11e8-8762-71bbab0a3516.png">

**Comment by cesarjr** [comment]
Hi @Lologam I'm having the same issue. Have you found any workaround?

I'm still have the same problem with the visit date of an URL.

The impression that I have is that to both cases Mautic is ignoring the URL and using a global counter in the contact to do this filter.

What do you think about that?

**Comment by luizeof** [comment]
Tested and this is fixed on 2.15.0 using the **contains** operator

**Comment by kuzmany** [comment]
Hi guys,

let's test: https://github.com/mautic/mautic/pull/7424

**Comment by npracht** [comment]
closed by https://github.com/mautic/mautic/pull/7424

**Comment by kuzmany** [comment]
@npracht that PR was reverted from 2.16.2 due some conflicts

**Comment by RCheesley** [comment]
@kuzmany will you make a new PR for this? Does it persist in Mautic 3.x ?

**Comment by kuzmany** [comment]
@RCheesley there are two PR which handles same thing

https://github.com/mautic/mautic/pull/7424
https://github.com/mautic/mautic/pull/7874

I didn't test @pety-dc PR, but we need decide to what PRs is more relevant and resolve it

**Comment by RCheesley** [comment]
Thanks - #7424 had issues so it had to be reverted - did not see any recent fixes on that PR to address those issues. It looks like #7874 has a :+1: from two folk using in high load situations so I would be inclined to favour that approach, providing we can get the conflicts addressed and tests written.

**Comment by kuzmany** [comment]
https://github.com/mautic/mautic/pull/7424 is more complex, use sub queries for each table, that means there is less effort to resource. Also code is more clear, more ready to write unit tests. We used it on production. But we need re-submit it.
https://github.com/mautic/mautic/pull/7874 - need tested in any cases (tags, segments, page hit data...)
