### ISSUE TITLE
company select fields in forms do not update

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5733]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I submit a form with a select company field, but the value does not update when I check the company sheet.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Create a select company field custom field with some values
![image](https://user-images.githubusercontent.com/31535432/36471698-b8e0ecca-16ef-11e8-9dd5-4ee2702bada6.png)
2. Create a form, add contact email, contact company field and the company custom field previously created.
![image](https://user-images.githubusercontent.com/31535432/36471798-0e953efa-16f0-11e8-9982-09bc23878617.png)
3. Submit the form
4. Go check the company sheet that has been created (or updated with this new select custom field).
5. Company has been created but this field is still empty.
6. See my form result below
![image](https://user-images.githubusercontent.com/31535432/36472035-c44405ce-16f0-11e8-8f91-37f6d0fd2989.png)
7. See my company field below (empty)
![image](https://user-images.githubusercontent.com/31535432/36472112-0f3f786a-16f1-11e8-84a3-93e44dae387a.png)

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by mburamorde** [comment]
I can confirm this bug. Maybe there are parallels with #5499

**Comment by kuzmany** [comment]
@mburamorde Did you try https://github.com/mautic/mautic/pull/5611 ? Can you confirmed this issue after apply that PR?

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
This not resolve it? https://github.com/mautic/mautic/pull/5567

**Comment by kuzmany** [comment]
Label: Pending Feedback

**Comment by npracht** [comment]
Label: Pending feedback

**Comment by kuzmany** [comment]
Hope this fixed it https://github.com/mautic/mautic/pull/5915

**Comment by johbuch** [comment]
just tested PR [#5915](https://github.com/mautic/mautic/pull/5915) it didn't work for me

**Comment by npracht** [comment]
Fixed in #5915 and merged
