### ISSUE TITLE
A/B test stats disappear after any modification (inc. unpublish)

### ISSUE THREAD

**Issue by maxitromer** [mautic/mautic#5734]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:

When a broadcast email is automatically unpublished and expired the A/B Tests Stats disapear.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 5.6

### Steps to reproduce:
1. Create a new email with a variant to test.
2. Add a published and unpublished date to send it as a broadcast.
3. Wait until the unpublished date and try to open the test stats.

**Comment by npracht** [comment]
Label: Bug

**Comment by afonseca08** [comment]
I can confirm this bug is still present in v2.13.1 which renders A/B testing non-functional for send to segment e-mails. In addition to test stats not being available, there is no A/B test winner indicated.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
