### ISSUE TITLE
Pipedrive : Webhook not working (401 error)

### ISSUE THREAD

**Issue by bligneri** [mautic/mautic#5745]
| Q  | A
| ---| ---
| Bug report? | Pipedrive : Webhook not working (401 error)

## Description:
I can synchronize with Pipedrive but the webhook does not work. I have a 401 error.
I have the following error in the mautic log
g:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | PHP 7.0.27 (cgi-fcgi) (built: Jan 24 2018 19:16:03)

### Steps to reproduce:
1.  Add the mautic plugin
2. Configure the webhook for a person
3. Change a person
4. Status is "401" in Pipedrive->settings->webhook
5. I tried numerous combination of HTTP or HTTPS (the link in the Pipedrive plugin only display HTTP) and user - password including simple ones
6. I have added a var_dump for the $request variable and it seems quite fine
 
### Log errors: 
[2018-02-24 13:21:15] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\UnauthorizedHttpException: "" at /home2/mauticaxialdev/public_html/plugins/MauticCrmBundle/Controller/PipedriveController.php line 54 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\UnauthorizedHttpException(code: 0):  at /home2/mauticaxialdev/public_html/plugins/MauticCrmBundle/Controller/PipedriveController.php:54)"} []
##

No error logs in apache but the following : 
```
xxx.yyy.zzz.ttt - - [23/Feb/2018:23:11:10 -0500] "POST /plugin/pipedrive/webhook HTTP/1.1" 401 402 "-" "Pipedrive Webhooks"
```

So a 401 error but I am certain and did several double check that the user and pass are the same (cut & paste)...

**Comment by bligneri** [comment]
I use Cloudflare as a CDN and proxy. I will remove it to make sure this is not the problem cause...

**Comment by bligneri** [comment]
No change. Obviously if I comment the throw exception, everything work as expected.

Could it be linked to the PHP module used to do the Basic Auth ?

**Comment by dbhurley** [comment]
Hey! So it appears something is wrong with your credentials. You're getting a not-authorized error. Ask in the forums or Slack channel to get some help. It's not a bug it doesn't appear. If others replicate and comment here we can re-open the issue.

**Comment by socmov** [comment]
HI - I can replicate the issue. The plugin is swapping the API token and the Webhook Password fields. It is trying to use the password instead of the token for authentication.

**Comment by k16101997** [comment]
same issue @socmov , any update on this?

**Comment by socmov** [comment]
I stopped the webhook. It was too unstable
