### ISSUE TITLE
bug with default content in email dynamic content bloc

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5749]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I add a dynamic content bloc in email builder.
![image](https://user-images.githubusercontent.com/31535432/36719614-d02414e2-1ba5-11e8-8b42-924965a80232.png)
Then I add a text in the default content.
![image](https://user-images.githubusercontent.com/31535432/36719650-eec35a0c-1ba5-11e8-882f-cf4b9efd7124.png)
![image](https://user-images.githubusercontent.com/31535432/36719660-f78839be-1ba5-11e8-93dd-c5f035e99761.png)
Then I delete the text in the default content and the dynamic content bloc disappear.
![image](https://user-images.githubusercontent.com/31535432/36719723-34e31e1e-1ba6-11e8-9b5f-de327aaf31b2.png)
If then you select another bloc and want to select back the dynamic content bloc you could not. Even if there were few variations added. It means they are lost.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 

### Steps to reproduce:
1. Create an email
2. Add a dynamic bloc content
3. Write something in the default content
4. Add a variation
5. Remove what you wrote in the default content
6. See that the bloc disappeared
7. Select another bloc in the email
8. Try to go back on the dynamic content bloc you created > impossible because it is not here anymore
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Agreed, something as simple as placeholder text would make the Dynamic Content fields "findable" in the future.

**Comment by AlbanL74fr** [comment]
It happened to me as well. That extremely annoying.

**Comment by johbuch** [comment]
I have some news about this issue.
It is more complicated that it seems. 
So as I said, the dynamic content disappeared. But in the preview of the email, if you added a variant you can still see the variant even if you don't see anymore the bloc on the builder.

**Comment by npracht** [comment]
@johbuch i think that has been solved. Please add the link to the related PR and close :)

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/6810

**Comment by Woeler** [comment]
https://github.com/mautic/mautic/pull/6810
