### ISSUE TITLE
Add Multi-Select Type to Lead Custom Fields

### ISSUE THREAD

**Issue by hisaltesse** [mautic/mautic#575]
Add multi-select field type to lead custom fields with lookup option as well. 

Here is a use case: 
I want to create an "interests" field to my leads so I can record their interests and target them by that. 

I would need the field to be able to accept multiple values e.g. movies, sports, games
And I would want to not have to predefine them all because new unknown interests could be recorded depending on where the data is pulled from, therefore the lookup mode is preferred. 

I should then be able to target or filter by one of more values included in the interests field. This is why we need: 
- lookup field supporting multiple values and where we can select multiple values as well. In other words a multi-select field where I don't have to predefine all the values.

**Comment by escopecz** [comment]
Do you mean this?
![mauticmultiselect](https://cloud.githubusercontent.com/assets/1235442/8454197/f0eb9cc0-1ffb-11e5-84f6-678de48e4520.png)
About the lookup option. What data should it be able to lookup? Anything from Mautic database or from some 3rd party API as well?

**Comment by escopecz** [comment]
Sorry, take that back. You were asking about Lead fields, not Form fields. So yes, it doesn't have multiple option.

But could you clarify the lookup? Because there is lookup field type in lead fields.

**Comment by hisaltesse** [comment]
I just updated the description with a use case to clarify.

**Comment by wderuijter** [comment]
I too would like this feature.

**Comment by alanhartless** [comment]
Just noting here while I thinking about it.  When we do make this feature available, we need to also adjust the list filters to support building lists based on this as well.  Not sure what that looks like since the values for form fields are saved as a comma delimitated list.  Not sure if that means the query would need to use something like Mysql's find_in_set (which postgreSql does not have so we'd have to do something different for it) or if we simply use LIKE '%value%'.

**Comment by escopecz** [comment]
Implemented in Mautic 2.2.0

**Comment by amagdy3** [comment]
This is great guys. You are awesome.

**Comment by moses5407** [comment]
But how do I use it? I created a select-multiple custom field and included it on a form. I also created matching segments for each select option. It does capture all of the selections ... but I see no way to use each selection to add the respodent to the corresponding segment..?

**Comment by namratasaun** [comment]
Hey, I think it was only partially solved. I can add multiple values in a field. But they are not dynamic (impromptu), means I have to predefine all the possible value/options, and the options can't be added on the go.

**Comment by namratasaun** [comment]
Also, I tried lookup field and neither can it add options on the go, nor can it select multiple options.
So what is the difference between select field and lookup field?
