### ISSUE TITLE
Error on upgrade to 2.12.2

### ISSUE THREAD

**Issue by iwantaspeaker** [mautic/mautic#5751]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
Getting 500 Internal Server Error on web page after upgrade to version 2.12.2 completed.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | upgrading to 2.12.2
Apache Version | 2.4.29
PHP Version | 5.6.33
MySQL Version | 5.6.38

### Steps to reproduce:
1. tried to go to mautic website https://contacts.iwantaspeaker.com
2. 
 
### Log errors: 

Getting report in CPanel Error log:
[Tue Feb 27 17:35:19.408957 2018] [:error] [pid 72131:tid 140159251080960] [client 81.133.162.160:36827] SoftException in Application.cpp:388: UID of script "/home/contactsiwantasp/public_html/index.php" is smaller than min_uid

also getting error in error_log in Mautic folder.
[27-Feb-2018 16:32:28 UTC] PHP Fatal error:  Class 'ComposerAutoloaderInit4d4b3b5917b8ff5d60c612b4037e6432' not found in /home/contactsiwantasp/public_html/vendor/autoload.php on line 7

**Comment by iwantaspeaker** [comment]
Trying to fix the issue using suggestions from https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

Got following results:

[root@vps2-105 /home/contactsiwantasp/public_html]# php app/console mautic:update:find
Great! You are running the current version of Mautic.
[root@vps2-105 /home/contactsiwantasp/public_html]# php app/console doctrine:migration:status

 == Configuration

    >> Name:                                               Mautic Migrations
    >> Database Driver:                                    pdo_mysql
    >> Database Name:                                      contacts_mautic
    >> Configuration Source:                               manually configured
    >> Version Table Name:                                 migrations
    >> Version Column Name:                                version
    >> Migrations Namespace:                               Mautic\Migrations
    >> Migrations Directory:                               /home/contactsiwantasp/public_html/app/migrations
    >> Previous Version:                                   2018-01-05 09:00:00 (20180105090000)
    >> Current Version:                                    2018-01-17 14:16:13 (20180117141613)
    >> Next Version:                                       Already at latest version
    >> Latest Version:                                     2018-01-17 14:16:13 (20180117141613)
    >> Executed Migrations:                                100
    >> Executed Unavailable Migrations:                    0
    >> Available Migrations:                               100
    >> New Migrations:                                     0

[root@vps2-105 /home/contactsiwantasp/public_html]# php app/console doctrine:schema:update --dump-sql
CREATE INDEX attribution_search ON leads (attribution);
CREATE INDEX iwas_createdate_search ON leads (iwas_createdate);
CREATE INDEX iwas_user_account_active1_search ON leads (iwas_user_account_active1);
CREATE INDEX iwas_admin_locked_search ON leads (iwas_admin_locked);
CREATE INDEX iwas_last_login_search ON leads (iwas_last_login);
CREATE INDEX iwas_last_updated_search ON leads (iwas_last_updated);
CREATE INDEX iwas_speaker_verified_search ON leads (iwas_speaker_verified);
CREATE INDEX iwas_speaker_visible_search ON leads (iwas_speaker_visible);
CREATE INDEX iwas_user_active_search ON leads (iwas_user_active);
CREATE INDEX unique_identifier_search ON leads (email, iwas_speaker_id, iwas_user_id);
CREATE INDEX contact_attribution ON leads (attribution, attribution_date);
ALTER TABLE reports_schedulers DROP FOREIGN KEY FK_1B66478A4BD2A4C0;
DROP INDEX idx_1b66478a4bd2a4c0 ON reports_schedulers;
CREATE INDEX IDX_C74CA6B84BD2A4C0 ON reports_schedulers (report_id);
ALTER TABLE reports_schedulers ADD CONSTRAINT FK_1B66478A4BD2A4C0 FOREIGN KEY (report_id) REFERENCES reports (id) ON DELETE CASCADE;
[root@vps2-105 /home/contactsiwantasp/public_html]# php app/console doctrine:schema:update --force
Updating database schema...

  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'CREATE INDEX attribution_search ON leads (attribution)':

  SQLSTATE[42000]: Syntax error or access violation: 1069 Too many keys specified; max 64 keys allowed

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1069 Too many keys specified; max 64 keys allowed

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1069 Too many keys specified; max 64 keys allowed

**Comment by Bizcrony** [comment]
Wait at least 10-20 days don't be hurry to upgrade

**Comment by iwantaspeaker** [comment]
Thanks, But not useful.

**Comment by iwantaspeaker** [comment]
Fixed it by changing the owner of indedx.php from root back to user. As per https://www.inmotionhosting.com/support/website/general-server-setup/uid-smaller-than-min-uid

**Comment by iwantaspeaker** [comment]
However NOW I cant access ANY contact records under page /s/contacts. You can see the working bar trying to do something, but nothing happens.
Any thoughts?

**Comment by iwantaspeaker** [comment]
Seems like on Upgrade all files and folders had their ownership changed to 'root'. 
Do all files and folders need to be owned by the user or doesnt it matter if they are owned by 'root'.
Had an error saying "[2018-02-28 10:05:36] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The directory "/home/contactsiwantasp/public_html/app/cache/prod/annotations" is not writable." at /home/contactsiwantasp/public_html/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php line 92 {"exception":"[object] (InvalidArgumentException(code: 0): The directory \"/home/contactsiwantasp/public_html/app/cache/prod/annotations\" is not writable. at /home/contactsiwantasp/public_html/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php:92)"} []"
Fix it by doing a "chown <user>:<user> /public_html/app/cache/prod/annotations/"

**Comment by sambarnes90** [comment]
**Full Disclosure** - This could make things worse...

Tried changing the version back to the old one in /app/version.txt

Then re-running the upgrade script from the command line [as suggested here](https://www.mautic.org/topic/2-12-2-released/):

`If you are have access to SSH, we highly recommend that you use the update script. Download it to the root of your Mautic installation and run it from SSH/CLI with php upgrade.php. If you are on a VPS, be aware of the user used to execute that command as you may have to fix the owner to be that of your web user. Be sure to remove this file once the upgrade is complete.`

**Comment by iwantaspeaker** [comment]
Had to restore from backup as doing `chown -R <user>:<user> /public_html/` broke the web site.

**Comment by iwantaspeaker** [comment]
I am back on previous version  now, and wont upgrade till I know this wont happen again.
Devs - Any thoughts?

**Comment by amagdy3** [comment]
I'm =unable to send Emails neither through segments nor campaigns.  since I upgraded to 2.12.2, I changed permission of all files and folders to the webserver "apache:apache" and still no emails being sent.

2018-03-12 16:40:35] mautic.WARNING: PHP Warning - mkdir(): Permission denied - in file /var/www/html/comm/app/bundles/EmailBundle/MonitoredEmail/Mailbox.php - at line 198 [] []
[2018-03-12 16:46:49] mautic.WARNING: PHP Warning - unlink(/var/www/html/comm/app/cache/prod/appProdProjectContainer.php): Permission denied - in file /var/www/html/comm/app/bundles/CoreBundle/Helper/CacheHelper.php - at line 102 [] []
[2018-03-12 15:18:53] mautic.NOTICE: Exception: DateInterval::__construct(): Unknown or bad format (null) (uncaught exception) at /var/www/html/comm/app/bundles/CampaignBundle/Model/EventModel.php line 1705 while running console command `mautic:campaigns:trigger` [] []

**Comment by MxyzptlkFishStix** [comment]
How many custom fields do you have? Looks like MySQL/MariaDB needs to be recompiled with --with-max-indexes=256/-DMAX_INDEXES=128 option.

https://github.com/mautic/mautic/issues/5751
https://github.com/mautic/mautic/issues/4372
https://github.com/mautic/mautic/issues/4465

**Comment by AkkuFresh** [comment]
@iwantaspeaker  please check this issue, may your issue is the too same behind the scenes : https://github.com/mautic/mautic/issues/6693

**Comment by npracht** [comment]
I think we can close this knowing how old is the version.
