### ISSUE TITLE
REST API getList doesnt work without viewOther permission and FIX

### ISSUE THREAD

**Issue by enguerr** [mautic/mautic#5759]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
test on the last release with REST API 
/api/emails
/api/contacts

it doesnt work. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.0.2

### Steps to reproduce:
1. Connect to the api with OAUTH 1 or 2 with a user without viewOther permission
2. try to get your contacts or emails with /api/emails or /api/contacts
3. you are unable to get any result
 
### Log errors: 

No errors.

### How to Fix:
edit the file app/bundles/ApiBundle/Controller/CommonApiController.php
#line 375
--  $this->listFilters = 
++  $this->listFilters[] =

**Comment by npracht** [comment]
Solved in 2.14.0
