### ISSUE TITLE
Setup Database Using Environment Variable

### ISSUE THREAD

**Issue by berjaya101** [mautic/mautic#576]
Hi!

How to setup database using environment variable?
I have tried change it in config file but it not working.
Mautic will still ask for the database information.

I want to try install selfhost mautic using OpenShift (openshift.com).

Thank you.

**Comment by escopecz** [comment]
You have to always clear cache after changing app/config/local.php config file. Have you clear the cache?

**Comment by berjaya101** [comment]
I haven't tried that yet.

I manage to install self-hosted Mautic now. But I am not using the environment variable.

Thank you for your reply.

**Comment by escopecz** [comment]
You have to always clear the cache after config modification. If you don't have ssl access to the server to run `cache:clear` command, simply delete content of app/cache folder.

I don't get what you mean by environment variables. Can you give us an example?

**Comment by berjaya101** [comment]
Sorry. I cannot explain about the environment variable much.

From what I understand when we used environment variable, if we change the setting for example the password, there is no need to change it manually in our application setting. It will change automatically.

https://developers.openshift.com/en/managing-environment-variables.html

Thank you.

**Comment by escopecz** [comment]
I think this is question for OpenShift support. If you get the configuration right, It would be great if you could write an article about it and make it easier for other Mautic community members. I'm going to close this issue now, but please let us know how it went.

**Comment by shaulid** [comment]
I'm having the same problem with openshift. Would love to hear how to do it without the environment variables.

**Comment by forevertga** [comment]
Please I have a self hosted mautic on EC2, and created AWS RDS database instance for it but I don't know how to config Mautic HOST to read from RDS instead of the mysql container ENVs that came with it. Any help?

**Comment by coolsagar005** [comment]
@forevertga I am also facing the same issue.

**Comment by forevertga** [comment]
oh @coolsagar005, have you been able to resolve it?. Seems Mautic create new database for every new installations. So what I did as a temporarily is to create two databases, one I use when am installing new instance of Mautic and second which contain the real data. So I switch after each successful installation, am not sure if that is the best approach.
