### ISSUE TITLE
Page break in forms is not working

### ISSUE THREAD

**Issue by Nirind** [mautic/mautic#5760]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by andreab79** [comment]
hi, why closed this item? this is still a bug for mautic version v2.14.1
it happens not in form preview or in landing builded by mautic but when form is integrated with wordpress website

**Comment by npracht** [comment]
Hello @andreab79, i don't want to talk on David's name but as you can see there is a template to report issue, but no information has been given. We cannot consider it as a bug and even more help if there is nothing explained to reproduce the issue and confirm it is a bug.

**Comment by andreab79** [comment]
hi dear, this is just a reply to an existent bug report, it is not a new one. anyway i will open a new one but please after don't reply saying "why don't search an existent bug report"? :)

**Comment by npracht** [comment]
If it is clean report and there is no other open related issue, we'll be happy to keep it open :) :) :)

**Comment by andreab79** [comment]
@npracht please take a look, i didn't open this report bug, i just added a reply :) :) :)
