### ISSUE TITLE
bug: ip lookup log filled with php errors and subsequently filled HD of server

### ISSUE THREAD

**Issue by zstephen** [mautic/mautic#5764]
## Description:
Crontab runs the following job and logs to file
```
php console mautic:iplookup:download
````
Log file for ip lookup contains multiple gigabytes of these two lines repeated.

```
PHP Warning:  gzread() expects parameter 1 to be resource, boolean given in /var/www/sites/name/sitename/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php on line 98
PHP Warning:  gzeof() expects parameter 1 to be resource, boolean given in /var/www/sites/name/sitename/app/bundles/CoreBundle/IpLookup/AbstractLocalDataLookup.php on line 97
```

Maxmind Geolite2 City Download IP service was selected in configuration.

| Mautic version | 1.12.1
| PHP version | 7.0.22-0ubuntu0.16.04.1

### Steps to reproduce:
I don't know what provoked this, I just woke up and checked mautic and it was offline because the lack of HD space caused the mysql service to stop.

After blanking the log file and restarting mysql, I noticed via top that the php7-fpm and php processes were causing a massive amount of CPU usage. Restarting nginx, php-fpm had no effect. This CPU saturation continued until I rebooted the server. 
 
### Log errors: 

Nothing was in mautic's log file, just the output from the crontab job

**Comment by npracht** [comment]
We had the same issue here

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Label: WIP

**Comment by npracht** [comment]
In:
https://github.com/mautic/mautic/blob/staging/app/bundles/CoreBundle/Config/config.php#L991
You have to unselect this value to leave blank as default.

**Comment by npracht** [comment]
I don't why it has been set as ip lookup service by default. If you don't have an account there it makes your instance very slow. I'm preparing a PR to remove this default value.

**Comment by npracht** [comment]
Please test https://github.com/mautic/mautic/pull/5765

**Comment by npracht** [comment]
Label: Ready to test

**Comment by npracht** [comment]
Label: WIP

**Comment by npracht** [comment]
Maxmind is out now out of the game right? Let's close it.
