### ISSUE TITLE
REST API Cant add a contact who already exists for antoher user. AND FIX

### ISSUE THREAD

**Issue by enguerr** [mautic/mautic#5766]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
A user sync a lead who already exists in another list from another user. 
This user doesnt have the role viewOther. 
You'll get a 403 forbidden

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.0.2

### Steps to reproduce:
1. Connect to the REST API with a simple user credential without the viewOther Role. 
2. try to add a contact that already exists in antoher list (invisible for this user.)
3. you'll get a 403 forbidden and you are unable to add this user. 
 
### Log errors: 
no error

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

###THE FIX
file app/bundles/LeadBundle/Controller/Api/LeadApiController.php 
158--            $leads = $this->get('doctrine.orm.entity_manager')->getRepository(
159--                'MauticLeadBundle:Lead'
160--            )->getLeadsByUniqueFields($uniqueLeadFieldData, $id, 1);
158++            $leadRepo = $this->get('doctrine.orm.entity_manager')->getRepository(
159++                  'MauticLeadBundle:Lead'
160++                );
161++            $leadRepo->setCurrentUser($this->get('security.context')->getToken()->getUser());
162++            $leads = $leadRepo->getLeadsByUniqueFields($uniqueLeadFieldData, $id, 1,$this->security-++>isGranted('lead:leads:viewother'));

file  app/bundles/LeadBundle/Entity/LeadRepository.php
201++         if (!$viewOther) {
202++             $q->andWhere('l.created_by = '.$this->currentUser->getId());
203++         }

**Comment by Owchzzz** [comment]
Please request for a pull request on this. also was a problem of mine, and I bet a lot more people as well 👍

**Comment by npracht** [comment]
@enguerr @Owchzzz we are about to close the PR https://github.com/mautic/mautic/pull/6130 because none seem to matter about it.
Could you test and finish the work ? Otherwise we close the PR and problem keeps being like that.

Thanks !

**Comment by npracht** [comment]
Obviously solved in current release.
