### ISSUE TITLE
Upgrade on 3/1 breaks form actions

### ISSUE THREAD

**Issue by shoelessjoe51** [mautic/mautic#5768]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Bug report? | 

## Description:
Forms that were previously created in Mautic no longer work after I performed the upgrade to newest version last night. When I click on the submit button of a form the text changes on the button and then it hangs without ever completing the form action. If I clone the form in Mautic and insert the new form ID into Wordpress it works just fine.

## If a bug:
| Mautic version | 
v2.12.2

| PHP version | 
7.0.27

### Steps to reproduce:
1. See above
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Did you try rebuild form cache?

![image](https://user-images.githubusercontent.com/462477/36920320-a993b450-1e60-11e8-812e-df37ca9f4eef.png)
