### ISSUE TITLE
PHP 7.2.3 support

### ISSUE THREAD

**Issue by panchtatvam** [mautic/mautic#5769]
| Q  | A
| ---| ---
| Enhancement? | Support for PHP 7.2.3

## Description:
PHP 7.2.3 not supported by Mautic.

| Q   | A
| --- | ---
| Mautic version | 2.12.2 | 
| PHP version | 7.2.3 | 

### Steps to reproduce:
1. Fresh install on PHP 7.2.3
 
### Log errors: 
This package requires php >=5.6.19 <7.2 but your PHP version (7.2.3) does not satisfy that requirement.

Which version intends to support PHP 7.2 ?

**Comment by dbhurley** [comment]
This will come in a future release, not yet defined.

**Comment by nickian** [comment]
I upgraded a server with the newest version of Mautic installed to PHP 7.2.3. Still seems to work. What exactly is going to break when running on this version?

**Comment by insign** [comment]
@dbhurley there is something that currently don't works in 7.2?

**Comment by qroft** [comment]
@nickian i did the same but do get the information that i must downgrade to a lower version.
So the question is, what is different between my server and yours?
Or have you downloaded a nightly build?

**Comment by nickian** [comment]
My fault. I didn't realize I was getting a different version on the command line vs Apache. I have 7.2.3 on the command line and 7.1.15 running with Apache, so that's why it's working normal.

**Comment by andersonbraz** [comment]
I solved like this:

On file: mautic/app/middlewares/VersionCheckMiddleware.php

I changing:

``php
const MAUTIC_MAXIMUM_PHP = '7.1.999';
``

to

``php
const MAUTIC_MAXIMUM_PHP = '7.2.999';
``

Best Regards!

by [Anderson Braz](https://andersonbraz.com)

**Comment by imadamtoo** [comment]
I'm just confirming that @andersonbraz' fix worked. Thank you! Will that cause any problems with my instance of Mautic?

Thank you

**Comment by cmcintosh** [comment]
There is a use of mcrypt in mautic, was that corrected.

**Comment by YosuCadilla** [comment]
It was @cmcintosh, you need to enable ssl tho.
