### ISSUE TITLE
Points value not syncing through Vtiger integration when integration executes based on a Contact's point value

### ISSUE THREAD

**Issue by irooskov** [mautic/mautic#5771]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When pushing a contact to Vtiger based on a contact's points value, and via the Mautic plugin, if you are syncing the points across to Vtiger, the value will not come across. 

I believe the issue is that the "push to integration" action is executed before Mautic completes writing the contact's point value back to the point field in the contact's record.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 7.0.25-0ubuntu0.16.04.1

### Steps to reproduce:
1. Setup Mautic integration sync to Vtiger to execute based on a contact reaching 100 points. Ensure the Mautic points value field is to be synced into Vtiger.
2. Add a form that gives 100 points when submitted by a contact
3. Submit the form, triggering the integration push based on contact's point value
4. Check in Vtiger that the points value did not make it into the Vtiger Leads record, however it does appear in Mautic. All other Contact data that was setup to be synced, did come across from Mautic to Vtiger.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by ReZarrected** [comment]
Wow!! This has been open for over a year already and no updates?

**Comment by npracht** [comment]
Hi @ReZarrected !
Are you able to reproduce with staging version ? If yes, feel free to contribute !

**Comment by ReZarrected** [comment]
Contribute what exactly? The current docs show an updated version yet the
code hasn't been updated in over a year. Think about that for a while

**Comment by npracht** [comment]
I've been looking at the issue. I can explain now why it is working like that.
When you push contact to integration (the issue exists with other integrations), the contact is posted to the integration before the point action on the form update the contact points. So, somehow, the contact is pushed with the score before the form submission.

I think that issue could be reviewed when **form** or the **plugin** bundles of mautic are refactored in **Mautic 3**.
______

Concerning my suggestion, the mautic open source doc shows an integration and the integration is existing. There is some enhancement to imagine and sometimes bugs to fix. I was suggesting that if you care about this feature, you can help by yourself the community by contributing to the code and fixing issues. **We would appreciate your help** to enhance the quality of this open source project.

**Comment by ReZarrected** [comment]
Norman you sound like a stand-up guy and I don't mean to be rude but this
issue is fixed on the hosted version and it hasn't been updated in the
open-source for months, perhaps intentionally. I just joined the slack team
and it appears that, just as you say, this isn't only a vTiger issue.

**Comment by npracht** [comment]
You are rude, i am not. Please keep calm. Here we talk about the non hosted version open source project. I am not aware of what people/companies do with their hosted version. The only thing i could advise is that if you have an hosted version somewhere, ask kindly those people to share their bugfixes and enhancement with the community...

**Comment by ReZarrected** [comment]
Dude you ARE rude, excuse yourself! This bug is over a year old and
although it's been resolved and the feature upgraded, it is still open with
no explanation... The hosted version is not by a 3rd party, it's by the
core team.

**Comment by npracht** [comment]
The hosted version of mautic is owned by mautic.com. Mautic Inc. (mautic.com) is a different company than mautic.org (an association, community).
**It is not owned by the same people and it is not the same live version.**

Here we are on the open source project. It means a community contribute and carry a project together. Unfortunately in none had time, need, energy or whatever to contribute fixing this bug, you cannot complain about it. But on your side you can contribute to the community also and not simply use the software without contributing to enhance it.
**You cannot blame someone particular here (me or anyone else), you can only blame the whole community to do not carry this issue. Or you can blame yourself to do not contribute to the community.**

If this is very important for you, you can also hire some freelancer that are expert in mautic development, you can find some on the slack/discord mautic chat.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
