### ISSUE TITLE
"do not contact" option is not available in contact list in mobile version

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5773]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | X
| Enhancement? | 

## Description:
In the mobile version it is not possible to add a contact as "DO NOT CONTACT" when selecting a contact in the contact list.
![mobile version](https://user-images.githubusercontent.com/31535432/36970541-40e4286c-2069-11e8-81d5-e6adb1fd9acf.jpg)
The option is not displayed.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 

### Steps to reproduce:
1. Connect to Mautic in mobile version
2. Go to contact list
3. Select a contact by checking the box
4. Click on the green arrow
5. Check that there is not the option to add the contact as DO NOT CONTACT
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: UI

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Solved in 2.14.0 by https://github.com/mautic/mautic/pull/5844
