### ISSUE TITLE
Question about adding points to lead in every form submission

### ISSUE THREAD

**Issue by ServicedCloud** [mautic/mautic#5774]
What type of report is this:

If a lead fillup form, should it be adding points in every form submission? We have set up Points at Manage Actions to add 40 points. However, if a lead fillup and submit form twice or more, then we checked the lead history, only 40 points was being added instead of 80 points or more. Can i ask if we are missing something?

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | N
| Enhancement? | N

## Description:
| Mautic version | 2.12.2
| PHP version | 5.6.33

### Steps to reproduce:
1. Points > Manage Actions 
2. Create new action > 
 - When a contact... = "Form Actions Submits a form"
 - Change Points = "40"

**Comment by npracht** [comment]
Hello,

- From Points > Manage action ---> every action will happen only ONCE per lead.
- From the form action tab, that will happen for every submission.

Have a nice day,

N.
