### ISSUE TITLE
Custom preference center won't work without {channelfrequency} markup

### ISSUE THREAD

**Issue by spka** [mautic/mautic#5775]
| Q  | A
| ---| ---
| Bug report? | y

## Description:
If  {channelfrequency} isn't included in the Custom Preference Center, it will not load and fall back to the system default.

| Q   | A
| --- | ---
| Mautic version | v2.12.2 
| PHP version | v7.1.11

### Steps to reproduce:
1. Create a custom landingpage, turn _is preference center_ on
2. Select a template (blank) and open the builder
3. Place _Segment List_, _Channel Frequency_, _Save Preferences_ into the builder, close builder and save page
4. Send yourself an email with the created pref. center link, open the page
5. You should now see the correct custom preference center
6. Go back to the pref. center builder, remove the _Channel Frequency_ block, and apply the change
7. Refresh the custom pref. center page. Now the system default loads instead of the custom one

**Comment by spka** [comment]
Code fix included in PR: #5782

**Comment by micheljung** [comment]
I'm facing the same issue. As a workaround, I added a code block:

```
&nbsp;
<script>
  document.querySelectorAll('[data-slot=channelfrequency]')[0].style.display = 'none';
</script>
```

The `&nbsp;` prevents the code block from becoming "unselectable" in the builder, the script hides the channel frequency block.

**Comment by npracht** [comment]
Hi, i'll mark it as an enhancement.
Today it has been thought like it is necessary to have the ability to be totally unsubscribable.

**BUT !**
If you manage some kind of transactionnel email, this is not a good use. You should use only segment management and still keep being able to send emails to your customers for instance about you bills, product updates, maintenance, etc.

## Request
Load the designed preference center even if the channel frequency block is not included in the page builder.

**Comment by kuzmany** [comment]
@npracht before start working on it, this PR doesn't fix it? https://github.com/mautic/mautic/pull/5782

**Comment by npracht** [comment]
@kuzmany it should!! :)

Could you test it and review the code please?

**Comment by kuzmany** [comment]
Let's test https://github.com/mautic/mautic/pull/6265

**Comment by cStuartHardwick** [comment]
I've not been able to get the custom pref. center to work at all. I'm doing nothing complex. I've tried several times to create a preference center type landing page using different email template. I always add ALL the contact fields and save the form. But the unsubscribe link on sent emails still pulls up the ugly, generated preference center form--never the custom preference center form.

**Comment by DomCTA** [comment]
> # I've not been able to get the custom pref. center to work at all. I'm doing nothing complex. I've tried several times to create a preference center type landing page using different email template. I always add ALL the contact fields and save the form. But the unsubscribe link on sent emails still pulls up the ugly, generated preference center form--never the custom preference center form.
> EDIT: The solution is, the email channel must ALSO be configured to use the preference center. The instructions I was following left that bit out. Does anyone know if there is a way to set a default pref center page so I don't have to remember to set it for every email I create?
> 
> Also, I have no idea what the original post test is so large.

Having the same issue, could you give me a run through of how you solved it?
