### ISSUE TITLE
Salesforce integration - Allow WHERE clause for accounts, contacts

### ISSUE THREAD

**Issue by greendesigned** [mautic/mautic#5779]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
It would be helpful to narrow the query results returned by the Salesforce integration import by allowing a WHERE clause to be added to the Salesforce integration. This would allow us to include or exclude specific record types or records that contain specific values.

**Comment by jwall-adwerx** [comment]
+1. This would be an enormous help for us, as we're starting our implementation with a relatively small subset of our Salesforce database and planning to scale up from there.

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
