### ISSUE TITLE
Format lead tokens in emails

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#578]
Hello,

This issue is 2-fold:

1) When creating an HTML email from scratch, I do not see a way to add lead fields. Is it possible to add a button to CK Editor, or drag and drop from the sidebar like in the builder?

2) When adding lead variable from the builder, I notice the markup produces
 `<strong contenteditable="false" data-token="{leadfield=firstname}">**First Name**</strong>` 
however CK Editor does not seem to allow me to format the text, make it not bold, etc. Is the data-token attribute the only way to dynamically bring in lead variables? If so, would a `<span>` be more appropriate?

Thanks!

**Comment by ronnieduke** [comment]
I did find the blog post about inserting lead attributes in the email (https://www.mautic.org/blog/tip-of-the-week-insert-fields). I really like the auto-hinting!

However, I still have the same issue with it requiring a <strong> tag around the element. Is there any way to just have {leadfield=firstname} live by itself in the text without having to associate it with a tag?

**Comment by escopecz** [comment]
Contact tokens are not surrounded in the `<strong/>` tag since Mautic 2.0.0.
