### ISSUE TITLE
Delivery status notification failed not marked as failed

### ISSUE THREAD

**Issue by captivea-bou** [mautic/mautic#5780]
What type of report is this:

Bug Report

## Description:
On some smtp servers, the answer provided in case of a failure of delivery the Delivery Status Notification is matching with one of the regular expressions but the lead is not marked as bounced

The DSN : 

> Original-Recipient: // MY CLIENT EMAIL
> Final-Recipient: rfc822; // MY CLIENT EMAIL
> Action: failed
> Status: 5.1.1
> Diagnostic-Code: smtp;550 5.1.1 RESOLVER.ADR.RecipNotFound; not found
> X-Display-Name: =?iso-8859-1?Q? // MY CLIENT EMAIL>?=

The regexps found an email they can keep to re-use in parseBody function, but if there are no x-failed-recipients header email is set to null (Why?)

In the parseBody function the soft matches with "RecipNotFound" but can't find the lead because of the lost of the email

` $bouncedEmail = (isset($message->xHeaders['x-failed-recipients'])) ? $message->xHeaders['x-failed-recipients'] : null;`

That line is the problem, so if we simply replace the "null" by the email we took upper. The problem may be solved and the lead can be marked as bounced!

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1 
| PHP version | 7.0.26

### Steps to reproduce:
1. Get a delivery notification that don't send x-failed-recipients header
2. The lead is not marked as bounced, but he should be?
 
### Log errors: 

No error log btw

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
