### ISSUE TITLE
SOCIAL MONITORING | Any social monitor not at top of hierarchical order does not work

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#5785]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:
| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
If multiple social monitors have been setup, the only one that functions is the highest in the hierarchy that is enabled. 

Live example:
I have four hashtag monitors configured. When I enable all of them, only social monitor ID 1 works. If I disable ID 1, ID 2 starts working, etc. Notes, there are some intricacies here that I don't have test cases for. For example, it seems that the ID does not have much of an effect on which social listener works, only that there is some sort of hierarchy being adhered to. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.12.2
| PHP version | 5.6

### Steps to reproduce:
1. Create multiple social monitors for different hashtags and link them to appropriate, unique segments. 
2. Allow the CRON to run and look at the amount of contacts created. You will notice that only one counter is increasing. 

 
### Log errors: 

[2018-03-07 09:09:20] mautic.NOTICE: Doctrine\ORM\ORMException: The EntityManager is closed. (uncaught exception) at /usr/share/nginx/html/mautic_condriac/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php line 144 while running console command `mautic:social:monitoring` [] []

**Comment by vexersa** [comment]
Have I logged this in the right place?

**Comment by vexersa** [comment]
I believe this may be related to #4614

**Comment by dbhurley** [comment]
Duplicate of #4614
