### ISSUE TITLE
Campaign - Comparison in a Condition for a form field value typed as "Number" is performed lexicographically (i.e. 500000 < 6000 < 90), rather than as "integers"/numerically (i.e. 500000 > 6000 > 90)

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#5786]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:

I am using Mixpanel to track user activity on my application and send some Mixpanel events to Mautic, by mapping them into "form" components with the proper form fields. It's convenient because simple page hits are not enough to capture more sophisticated user actions. 

One of the fields of the form I created is labelled as "Amount" and is set as "Number" data type in Mautic. For information, we currently send the data structured as "Integer" to Mautic.

Using condition box in the campaign builder, I try to compare this "Amount" value with a threshold value, because I want to trigger a particular action (email to myself) when the amount equals or exceeds this threshold value. 

**The problem :** 

The comparison is performed "lexicographically" rather than "numerically". Even though it would makes sense to lexicographically compare "Text" values, It seems right to compare "Number" data types numerically, instead.

**Extension of this issue :** 

I observed that in the "Form" results, when I try to sort the values of the "Amount" column, the sort is lexicographical.

It's very counter-intuitive that even though the field is set as "Number" type, it's basically treated as a text, both in the sorting in the form's result table, and, when performing numeric comparisons.

**Screeshots:** 

![image](https://user-images.githubusercontent.com/23435414/37153196-7b15e190-230e-11e8-8869-dde82fbb4b8a.png)
![image](https://user-images.githubusercontent.com/23435414/37152881-62bc342e-230d-11e8-965a-6d42eb972439.png)
![image](https://user-images.githubusercontent.com/23435414/37152860-4f73e1c8-230d-11e8-8ce8-d9320fe96e41.png)
![image](https://user-images.githubusercontent.com/23435414/37153073-204b739c-230e-11e8-901d-66cc1e831830.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 5.6.32

### Steps to reproduce:

1. Use the condition box and select "form field value" in the dropdown
2. Select an existing form with at least one field with type number and a value of 600
3. Set the field ("Amount", in my case, which is defined as "Number" in the form field definition)
4. Set the comparison operator as "Greater than or equal"
5. Set the "Value" as 50000000)
6. Run the campaign

Actual result : the condition is true (because 600 is lexicographically superior to 50000000), therefore the action path is trigger

Expected result : it should be false, and the non action path should be triggered

 
### Log errors: 

This issue doesn't log any error.

**Comment by heathdutton** [comment]
Wow... this explains a bug we were just trying to understand today.

**Comment by RCheesley** [comment]
This was resolved with #7705 so closing the issue :tada:
