### ISSUE TITLE
[Bug] Plugin content locking (referrer POST) causes 500.

### ISSUE THREAD

**Issue by heathdutton** [mautic/mautic#5787]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When two users attempt to edit a Focus at the same time, one will receive a 500 error due to content locking. This is a core bug within `mautic/app/bundles/CoreBundle/Controller/AbstractFormController.php` which is not currently cognizant of plugins.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | all

### Steps to reproduce:
1. Edit a Focus
2. Ask your friend to try to edit the same Focus while you have it checked out.
 
### Log errors: 
```
 mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The "MauticPluginMauticFocusBundle" (from the _controller value "MauticPluginMauticFocusBundle:MauticFocus:view") does not exist or is not enabled in your kernel!" at /var/app/current/mautic/app/cache/prod/classes.php line 2888 {"exception":"[object] (InvalidArgumentException(code: 0): The \"MauticPluginMauticFocusBundle\" (from the _controller value \"MauticPluginMauticFocusBundle:MauticFocus:view\") does not exist or is not enabled in your kernel! at /var/app/current/mautic/app/cache/prod/classes.php:2888, InvalidArgumentException(code: 0): Bundle \"MauticPluginMauticFocusBundle\" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your AppKernel.php file? at /var/app/current/vendor/symfony/http-kernel/Kernel.php:228)"} []
```

**Comment by npracht** [comment]
According to https://github.com/mautic/mautic/pull/5789#issuecomment-429590824 we can close it
