### ISSUE TITLE
I am tracked after lead reply to email

### ISSUE THREAD

**Issue by dantahoua** [mautic/mautic#5788]
| Q  | A

## Description:
I dont understand but when I send an email via a campaign or just via "send email" in the contact, if the contact reply to the email, I'm becoming the one who is tracked... Is it a bug or a mis-configuration?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.12.2
| PHP version | 7.0.28

### Steps to reproduce:
1. Go to contact, choose a contact, press send email, choose existing template, send email
2. The user receive the email. If the user click on link in email, everything works fine.
3. The user who received the email click on reply to contact me. As soos as I open the reply, I'm the one being tracked...
 
### Log errors: 

No error...

**Comment by lvnilesh** [comment]
I notice same erroneous behavior using v2.12.2. @dbhurley closed this issue which may mean that it is resolved. Appreciate if you can please shed some light on this issue closure.

**Comment by dantahoua** [comment]
Hello.
Any light on this issue?
Thanks.
