### ISSUE TITLE
Assets In HTML Landing Pages

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#579]
It would be great to be able to drag & drop or at least easily select URLs of Assets and Forms to integrate into HTML landing pages when creating them.

Maybe something like this?

![image](https://cloud.githubusercontent.com/assets/742579/8371777/a5768dc8-1b90-11e5-89be-8209dd0ee5d0.png)

**Comment by escopecz** [comment]
Could you recast your description? Because you can drag&drop or select an Asset. When you do, this popup shows up:
![mauticassetlink](https://cloud.githubusercontent.com/assets/1235442/8454043/8c39c4b0-1ffa-11e5-8424-bd868cb238f5.png)
You can select the text of the link.

**Comment by ronnieduke** [comment]
Sorry for the confusion - the screenshot was taken and modified from the builder, and I was using that to describe functionality I'd like to see in regular HTML mode for emails and landing pages. 




--------------------------------------

Ronnie Duke




On Wednesday, Jul 1, 2015 at 5:08 AM, John Linhart <notifications@github.com>, wrote:

Could you recast your description? Because you can drag&drop or select an Asset. When you do, this popup shows up:

 You can select the text of the link.
