### ISSUE TITLE
Contacts Import Not Working

### ISSUE THREAD

**Issue by siccl** [mautic/mautic#5791]
Bug report

## Description:
Contacts Import Not Working, uploading a csv file stay loop loading 

Mautic version v2.12.2
PHP version 5.6.33

### Steps to reproduce:
1. Import CSV File
 
### Log errors: 
Undefined index: batchlimit in /mautic/app/bundles/LeadBundle/Model/ImportModel.php on line 324
Undefined index: batchlimit in /mautic/app/bundles/LeadBundle/Model/ImportModel.php on line 324
Undefined index: batchlimit in /mautic/app/bundles/LeadBundle/Model/ImportModel.php on line 324

**Comment by vrMarc** [comment]
How many records are you trying to import?

**Comment by siccl** [comment]
only 64

**Comment by siccl** [comment]
we try contact and company, this fail, only contact alone works

**Comment by pedrouva** [comment]
I have the same issue

Import 4 with 20062 rows is starting.
     0/20062 [>---------------------------]   0%PHP Notice:  Undefined index: batchlimit in /var/www/marketing/htdocs/app/bundles/LeadBundle/Model/ImportModel.php on line 324

Can u help me pls? I'm not expert in mautic, but in Linux yes.

**Comment by vrMarc** [comment]
Have you tried a completely different CSV file? Can you attach a file with sample data? If so, I'll test it on my end.

**Comment by rikcooo** [comment]
same problem...

mautic.NOTICE: PHP Notice - Undefined index: batchlimit - in file /var/www/html/app/bundles/LeadBundle/Model/ImportModel.php - at line 346 [] []

**Comment by B-HEATH** [comment]
vrMark your solution worked for me. I copied my data from excel csv into google sheets. Downloaded the google sheets as csv and imported it with no problem. Thank you
