### ISSUE TITLE
Links in Campaign email do not redirect unless logged in

### ISSUE THREAD

**Issue by mandreus** [mautic/mautic#5796]
What type of report is this:

Question

## Description:
When I create a campaign automation track and send an email, the links in the email do not redirect unless I am logged in. If I am logged in, or send an email as a segment email, the links work fine.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6

### Steps to reproduce:
1. Create an email template with a link to a website
2. Create a campaign and add the email template as an action.
3. Send the email while you are logged into Mautic on the same default browser that clicking on the email link will open.
4. Link redirects correct.
5. log out of Mautic.
6. Click on same email link again from email client. Mautic delivers 500 error. URL is:
"http://domain.com/folder//r/107fbbc26353443d0b09661f0?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czoxNDoiY2FtcGFpZ24uZXZlbnQiO2k6MTtpOjEyO31zOjU6ImVtYWlsIjtpOjIxO3M6NDoic3RhdCI7czoxMzoiNWFhMzNjZDhlMDk5MiI7czo0OiJsZWFkIjtpOjExO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYWlsIjtpOjIxO319&
 
### Log errors: 
Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT c0_.id AS id_0, c0_.name AS name_1, c0_.description AS description_2, c0_.type AS type_3, c0_.event_type AS event_type_4, c0_.event_order AS event_order_5, c0_.properties AS properties_6, c0_.trigger_date AS trigger_date_7, c0_.trigger_interval AS trigger_interval_8, c0_.trigger_interval_unit AS trigger_interval_unit_9, c0_.trigger_mode AS trigger_mode_10, c0_.decision_path AS decision_path_11, c0_.temp_id AS temp_id_12, c0_.channel AS channel_13, c0_.channel_id AS channel_id_14, c1_.is_published AS is_published_15, c1_.date_added AS date_added_16, c1_.created_by AS created_by_17, c1_.created_by_user AS created_by_user_18, c1_.date_modified AS date_modified_19, c1_.modified_by AS modified_by_20, c1_.modified_by_user AS modified_by_user_21, c1_.checked_out AS checked_out_22, c1_.checked_out_by AS checked_out_by_23, c1_.checked_out_by_user AS checked_out_by_user_24, c1_.id AS id_25, c1_.name AS name_26, c1_.description AS description_27, c1_.publish_up AS publish_up_28, c1_.publish_down AS publish_down_29, c1_.canvas_settings AS canvas_settings_30, c2_.id AS id_31, c2_.name AS name_32, c2_.description AS description_33, c2_.type AS type_34, c2_.event_type AS event_type_35, c2_.event_order AS event_order_36, c2_.properties AS properties_37, c2_.trigger_date AS trigger_date_38, c2_.trigger_interval AS trigger_interval_39, c2_.trigger_interval_unit AS trigger_interval_unit_40, c2_.trigger_mode AS trigger_mode_41, c2_.decision_path AS decision_path_42, c2_.temp_id AS temp_id_43, c2_.channel AS channel_44, c2_.channel_id AS channel_id_45, c3_.id AS id_46, c3_.name AS name_47, c3_.description AS description_48, c3_.type AS type_49, c3_.event_type AS event_type_50, c3_.event_order AS event_order_51, c3_.properties AS properties_52, c3_.trigger_date AS trigger_date_53, c3_.trigger_interval AS trigger_interval_54, c3_.trigger_interval_unit AS trigger_interval_unit_55, c3_.trigger_mode AS trigger_mode_56, c3_.decision_path AS decision_path_57, c3_.temp_id AS temp_id_58, c3_.channel AS channel_59, c3_.channel_id AS channel_id_60, c4_.is_published AS is_published_61, c4_.date_added AS date_added_62, c4_.created_by AS created_by_63, c4_.created_by_user AS created_by_user_64, c4_.date_modified AS date_modified_65, c4_.modified_by AS modified_by_66, c4_.modified_by_user AS modified_by_user_67, c4_.checked_out AS checked_out_68, c4_.checked_out_by AS checked_out_by_69, c4_.checked_out_by_user AS checked_out_by_user_70, c4_.id AS id_71, c4_.name AS name_72, c4_.description AS description_73, c4_.publish_up AS publish_up_74, c4_.publish_down AS publish_down_75, c4_.canvas_settings AS canvas_settings_76 FROM campaign_events c0_ INNER JOIN campaigns c1_ ON c0_.campaign_id = c1_.id LEFT JOIN campaign_events c2_ ON c0_.id = c2_.parent_id LEFT JOIN campaign_events c3_ ON c0_.parent_id = c3_.id LEFT JOIN campaigns c4_ ON c2_.campaign_id = c4_.id WHERE c1_.is_published = ? AND (c1_.publish_down IS NULL OR c1_.publish_down >= ?) AND (c1_.publish_up IS NULL OR c1_.publish_up <= ?) AND c0_.type = ? AND c1_.id IN (?) AND (c0_.id NOT IN (SELECT c5_.id FROM campaign_lead_event_log c6_ LEFT JOIN campaign_events c5_ ON c6_.event_id = c5_.id LEFT JOIN leads l7_ ON c6_.lead_id = l7_.id WHERE c5_.id = c0_.id AND l7_.id = ?)) AND (c0_.decision_path <> 'no' OR c0_.decision_path IS NULL) ORDER BY c0_.event_order ASC, c2_.event_order ASC' with params [1, "2018-03-10 03:11:54", "2018-03-10 03:11:54", "email.click", 8, 11]:  SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query" at /home/www/html/default/autotest/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT c0_.id AS id_0, c0_.name AS name_1, c0_.description AS description_2, c0_.type AS type_3, c0_.event_type AS event_type_4, c0_.event_order AS event_order_5, c0_.properties AS properties_6, c0_.trigger_date AS trigger_date_7, c0_.trigger_interval AS trigger_interval_8, c0_.trigger_interval_unit AS trigger_interval_unit_9, c0_.trigger_mode AS trigger_mode_10, c0_.decision_path AS decision_path_11, c0_.temp_id AS temp_id_12, c0_.channel AS channel_13, c0_.channel_id AS channel_id_14, c1_.is_published AS is_published_15, c1_.date_added AS date_added_16, c1_.created_by AS created_by_17, c1_.created_by_user AS created_by_user_18, c1_.date_modified AS date_modified_19, c1_.modified_by AS modified_by_20, c1_.modified_by_user AS modified_by_user_21, c1_.checked_out AS checked_out_22, c1_.checked_out_by AS checked_out_by_23, c1_.checked_out_by_user AS checked_out_by_user_24, c1_.id AS id_25, c1_.name AS name_26, c1_.description AS description_27, c1_.publish_up AS publish_up_28, c1_.publish_down AS publish_down_29, c1_.canvas_settings AS canvas_settings_30, c2_.id AS id_31, c2_.name AS name_32, c2_.description AS description_33, c2_.type AS type_34, c2_.event_type AS event_type_35, c2_.event_order AS event_order_36, c2_.properties AS properties_37, c2_.trigger_date AS trigger_date_38, c2_.trigger_interval AS trigger_interval_39, c2_.trigger_interval_unit AS trigger_interval_unit_40, c2_.trigger_mode AS trigger_mode_41, c2_.decision_path AS decision_path_42, c2_.temp_id AS temp_id_43, c2_.channel AS channel_44, c2_.channel_id AS channel_id_45, c3_.id AS id_46, c3_.name AS name_47, c3_.description AS description_48, c3_.type AS type_49, c3_.event_type AS event_type_50, c3_.event_order AS event_order_51, c3_.properties AS properties_52, c3_.trigger_date AS trigger_date_53, c3_.trigger_interval AS trigger_interval_54, c3_.trigger_interval_unit AS trigger_interval_unit_55, c3_.trigger_mode AS trigger_mode_56, c3_.decision_path AS decision_path_57, c3_.temp_id AS temp_id_58, c3_.channel AS channel_59, c3_.channel_id AS channel_id_60, c4_.is_published AS is_published_61, c4_.date_added AS date_added_62, c4_.created_by AS created_by_63, c4_.created_by_user AS created_by_user_64, c4_.date_modified AS date_modified_65, c4_.modified_by AS modified_by_66, c4_.modified_by_user AS modified_by_user_67, c4_.checked_out AS checked_out_68, c4_.checked_out_by AS checked_out_by_69, c4_.checked_out_by_user AS checked_out_by_user_70, c4_.id AS id_71, c4_.name AS name_72, c4_.description AS description_73, c4_.publish_up AS publish_up_74, c4_.publish_down AS publish_down_75, c4_.canvas_settings AS canvas_settings_76 FROM campaign_events c0_ INNER JOIN campaigns c1_ ON c0_.campaign_id = c1_.id LEFT JOIN campaign_events c2_ ON c0_.id = c2_.parent_id LEFT JOIN campaign_events c3_ ON c0_.parent_id = c3_.id LEFT JOIN campaigns c4_ ON c2_.campaign_id = c4_.id WHERE c1_.is_published = ? AND (c1_.publish_down IS NULL OR c1_.publish_down >= ?) AND (c1_.publish_up IS NULL OR c1_.publish_up <= ?) AND c0_.type = ? AND c1_.id IN (?) AND (c0_.id NOT IN (SELECT c5_.id FROM campaign_lead_event_log c6_ LEFT JOIN campaign_events c5_ ON c6_.event_id = c5_.id LEFT JOIN leads l7_ ON c6_.lead_id = l7_.id WHERE c5_.id = c0_.id AND l7_.id = ?)) AND (c0_.decision_path <> 'no' OR c0_.decision_path IS NULL) ORDER BY c0_.event_order ASC, c2_.event_order ASC' with params [1, \"2018-03-10 03:11:54\", \"2018-03-10 03:11:54\", \"email.click\", 8, 11]:\n\nSQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query at /home/www/html/default/autotest/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query at /home/www/html/default/autotest/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: HY000): SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query at /home/www/html/default/autotest/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)

**Comment by dbhurley** [comment]
Please ask questions in the forum or Slack channels. It looks like a server related issue with your MySQL connection.
