### ISSUE TITLE
Additional properties on form fields return error

### ISSUE THREAD

**Issue by josuavogel** [mautic/mautic#5798]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | maybe
| Enhancement? | 

## Description:
If I post new form fields to the mautic API, everything is fine. I can add any atrribute to the properties array, e.g. in my case "typo3identifier".
If I save after inital creation (put), the data is rejected, I cannot update my typo3identifier as property.

2 options: Prevent adding additional properties on `create` calls or remove the check on `update` calls.

Note that I don´t ask to add any TYPO3 properties to the core, I only want a clean solution when I work with the REST API.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11
| PHP version | 7.1

### Steps to reproduce:
1. Push form field with unknown property -> creating form successful
2. Put form field with the sam property and corresponding mautic id -> error
 
### Log errors: 

`{"errors":[{"code":400,"message":"properties: This form should not contain extra fields.","details":[]}],"error":{"message":"properties: This form should not contain extra fields. (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)","code":400,"details":[]}}`

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
