### ISSUE TITLE
Self Hosted - Internal Server Error when submitting form on website

### ISSUE THREAD

**Issue by detroitwebdevelopers** [mautic/mautic#58]
Added form to sidebar on http://joomlaresources.com. When submitting, form goes to http://inbound.joomlaresources.com/p/form/submit?formId=1 but throws a 500 internal server error.
Img: http://i.imgur.com/aHdN1X4.png

Not sure what is needed to figure out why it's throwing the error, but just thought that I'd inform you that this was happening.

**Comment by alanhartless** [comment]
Hi!

If this is still an issue, reproduce the error then look in app/logs/mautic_prod.log for the error that's causing that and post it here.

Thanks!
Alan

**Comment by alanhartless** [comment]
Hi!

Closing due to a lack of feedback.  If this is still an issue with RC4 (the symptoms sound related to #96 which was fixed), post back or open a new issue.

Thanks!
Alan
