### ISSUE TITLE
[Feature Request] Alerts For Unsaved Changes

### ISSUE THREAD

**Issue by ronnieduke** [mautic/mautic#580]
Currently, it's easy to be in the middle of editing a landing page or email (or anything for that matter), and click on another link in the admin which loses all of your edits. It would be great if there was an alert that prompted you of any unsaved changes.

![image](https://cloud.githubusercontent.com/assets/742579/8372011/deb5b412-1b93-11e5-9e63-c54e8e4aa392.png)

**Comment by zapur1** [comment]
As an extension to this, from the closed issue #686.



When editing a campaign it would be good if when closing the campaign builder it shows a pop-over with information about what the changes to the campaign will do to existing leads in the campaign.

At its simplest it could just show the message only when it would specifically affect leads currently in the campaign (e.g. it only shows the message if leads will be affected), the extension would be to say what actions would be taken and against what leads for each.

It would make the questions around what changes to a campaign in progress affect non-existent as well.
Thanks,
Zac
