### ISSUE TITLE
refresh Button for theme updates, without loosing page content

### ISSUE THREAD

**Issue by olissongs** [mautic/mautic#5802]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | Yes
| Enhancement? | 

## Description:
When creating a new theme and using it for a Landingpage, every Theme Update will be ignored by Mautic.

Process:
changeing theme files local
update theme package by install the theme again remote
theme files in theme folder are uptodate remote

pages emails and forms are not updated.

## If a bug:
Theme updates are ignored, by Mautic, no update in DB pages down, only select an other theme, will update the theme, but all Page Data get lost.

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.0.28

### Steps to reproduce:
1. make a copy of a theme, rename it and change names fully
2. create zip, upload it
3. create a page with the new theme, save it
4. update your theme a little, google fonts or a style in css
5. upload the modified theme again.
6. no change happens :-(

no update without loosing data possible.
 
### Log errors: 
no errors. its in Application Logic, Customer Feature.

**Comment by mayanktiwaridotcom** [comment]
+1

**Comment by RCheesley** [comment]
Closing as very old and likely due to caching
