### ISSUE TITLE
Internal server error 500

### ISSUE THREAD

**Issue by Moyaga** [mautic/mautic#5811]
## Description:
I've been trying to duplicate the twilio bundle to see if I could use a different service, but now that I have removed everything and aparently everything is as it was before I get this error when I click for example to see contact's details.
```
libraries.js?va4c3f10b:673 GET http://83.36.141.151/index.php/s/dwc?_=1521109416699&mauticUserLastActive=1&mauticLastNotificationId= 500 (Internal Server Error)
           send @ libraries.js?va4c3f10b:673
           ajax @ libraries.js?va4c3f10b:649
           Mautic.loadContent @ app.js?va4c3f10b:39
           Mautic.ajaxifyLink @ app.js?va4c3f10b:98
           (anonymous) @ app.js?va4c3f10b:83
           dispatch @ libraries.js?va4c3f10b:404
           elemData.handle @ libraries.js?va4c3f10b:379
```

**Comment by Moyaga** [comment]
It was just permission's issue

**Comment by captivea-mla** [comment]
Hello, 
How did you solve the issue please ?

**Comment by chauminhtuan1988** [comment]
I have set full permission but it is still show this error.
How i can fix it?
