### ISSUE TITLE
[Tests] Switch from precise to trusty

### ISSUE THREAD

**Issue by heathdutton** [mautic/mautic#5815]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
Precise is being deprecated on April 1st (no joke).
So let's switch to the new default (trusty) and see how it goes.

**Comment by npracht** [comment]
Hi @heathdutton, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
