### ISSUE TITLE
Contact is being marked as DNC when send some email

### ISSUE THREAD

**Issue by williamespindola** [mautic/mautic#5816]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  yes
| Feature request? | 
| Enhancement? | 

## Description:
I'm sending a email to contact via api: `/api/emails/10/contact/49689/send` but the request return `{ "success": false, "failed": [] }` and the contact is marked as DNC with reason 0 and comments 2 on database. And the only way to remove this DNC is on database, because the red button on contact profile is not showing in this cases.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.12.1
| PHP version | 7.0.27

### Steps to reproduce:
1. Add some contact
2. Send email via api
3. On database and contact list will have DNC mark but on contact profile not.
 
### Log errors: 

No log error

**Comment by williamespindola** [comment]
I try to remove this DNC on contact preferences but not work.

**Comment by williamespindola** [comment]
I found the problem: `Unable to create a file for enqueuing Message in "/var/www/html/app/spool/default".`

**Comment by GrayTzar** [comment]
I'm experiencing this issue too, and a big chunk of my newsletter subs are now falsely flagged as 'Do Not Contact'. Is there a way to undo the damage?

**Comment by williamespindola** [comment]
This address two problems:
1. The directory permission and information about this permission it self on installation manual;
2. Error handler, this not "explodes" for the user or in some dev visual place.

**Comment by GrayTzar** [comment]
Sorry, is this fixed in the newest version of Mautic? Or still waiting?

**Comment by AlbanL74fr** [comment]
I have same issue with Mautic 2.12.2 ! This kind of DNC can be removed by API, but not with the frontend.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
