### ISSUE TITLE
Add SSL/TLS with novalidate-cert to eMail Config to Mail Send Settings

### ISSUE THREAD

**Issue by olissongs** [mautic/mautic#5817]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | yes
| Enhancement? | 

## Description:
Under eMail-Settings > Monitored Inbox Settings > Encryption 
There is in the select-list the non-validate-cert option for tls and ssl available.

Under eMail-Settings > Mail Send Settings > SMTP encryption type 
There is the two options missing, so i can only use "none"
So please add this, because is necessary for selfsigned or lets encrypt servers

## If a bug:

| Q   | A
| --- | ---
| Mautic version | actual 2.12.x stable
| PHP version | 7.0.28

### Steps to reproduce:
1. open settings > configuration | email config
2. check the select list for encryption in Mail Send Settings and Monitored Inbox Settings

### Log Message
[2018-03-16 11:14:33] mautic.WARNING: PHP Warning - stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed - in file /path/to/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php - at line 94 [] []

**Comment by MxyzptlkFishStix** [comment]
I don't think that's your problem. Either you don't have a certificate bundle installed (doubtful), PHP can't find/read it (possible), it's old and needs to be updated (possible) or you need to try port 587 instead of 25 as STARTSSL isn't running on that port (possible).

I've setup plenty of MTAs with self-signed or Let's Encrypt certs and usually when that error appears it's either a PHP config or certificate bundle problem.

**Comment by olissongs** [comment]
![mautic_mail_noencryption](https://user-images.githubusercontent.com/1310153/37963852-d496a118-31bf-11e8-8105-cbaa36fa5851.png)
![mautic_mail](https://user-images.githubusercontent.com/1310153/37963854-d7a60880-31bf-11e8-98a9-7c11d875a8c7.png)

here is an inconsistent Values in Encryption DropDown list.

i checked all of my mail configs (using Plesk-onyx), it seems all to be ok, checked some ssl issues. with this commands: openssl s_client -starttls smtp -crlf -connect 1.2.3.4:25
no errors.
changed 25 to 587, no possitiv result.

In Mautic Install docs i found nothing which is missing in my installation.

you can be proud of your work doing in setting up such things. I can't find any concret hint, to solve this problem. 

so how to evaluate to get the right point to change it, in most stackoverflow posts with this swiftmail issue, are not validating ca. 

so give a conret point to check the php thing, i can do this. And o think it should be documented in mautic install requirements, because without mailing, no fun in marketing.

**Comment by olissongs** [comment]
so going in deep inspecting mode:
Used Tools (may be add to documentation, als link to check eMail Problems):
https://mxtoolbox.com/domain
https://www.checktls.com/perl/TestReceiver.pl

i found the problem a Plesk Postfix Problem, it would be the host-server-ca instead of the domain-ca, so a hostname mismatch was the problem.

in most szenarios, i think the most user have no access to the it-infrastructure like dns, root, plesk-admin, or other systems. i know that swift mailer has the option to set ssl with ca errors.

`'streamOptions' => [
                    'ssl' => [
                        'verify_peer' => false,
                        'verify_peer_name' => false,
                    ],
                ],`

something like this.

so its better to have perfect working mailserver. but it would be nice to to get a encrypted mailbox connection.

so an additional encryption option like in the monitored inbox settings would be good to get an encrypted connection. may some hints "where to find the mail config mistake" would be good in the ducs

**Comment by MaxHayman** [comment]
No fix?

**Comment by AkkuFresh** [comment]
One of my server uses Postfix 2.10.0 with CentOS Webpanel for email transport and the named issue is appeared also. 
The Mautic email is running only on the plain "NO SSL" smtp service on the port 25.
In this server there are some admin alert email function that can be run on SSL with the following settings:
This mail function uses not Swiftmail but PHPMailer 6 for PHP 7.2. 

```
$mail->SMTPSecure = 'ssl';
$mail->SMTPOptions = array(
  'ssl' => array(
    'verify_peer' => false,
    'verify_peer_name' => false,
    'allow_self_signed' => true,
   )
);
$mail->Port = 465;
```
It means that would be necessary the option of "No validate SSL" on the SMTP settings also.
