### ISSUE TITLE
Mautic Form Error Messages not Translated when embedded 

### ISSUE THREAD

**Issue by Servalll** [mautic/mautic#5818]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | 
| Enhancement? | 

## Description:

When you create a form and you want to embed it into a webpage, error messages are not translated. There is no way to select a language for a form : it uses apparently the user's preferred lang in the settings

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.12.2
| PHP version | 

### Steps to reproduce:
1.  Create a form and add required fields
2.  Copy the HTML using the "Manual copy" in a web page 
3. Check if the required error messages are translated in French for example
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
