### ISSUE TITLE
Pending emails after send ( 25k emails )

### ISSUE THREAD

**Issue by jhrocha** [mautic/mautic#582]
Hi, guys. 
I had, pending emails after sending over 25k emails. 
Every sending email, more than half the emails are as outstanding.
Someone else with the problem or solution.
I've done everything I could, but the error continues

**Comment by alanhartless** [comment]
Hi!

Is this while sending through mautic installed on your own server? If so, what mailer are you using to send email (PHP mail, smtp, mandrill, etc)?

Thanks!
Alan

**Comment by jhrocha** [comment]
Hi, Alan. The Mautic was installed on my server and my email service is sendgrid.
Its a bug ?

**Comment by alanhartless** [comment]
Does sendgrid limit email sends?

**Comment by jhrocha** [comment]
My sendgrid account limit is 100.000 emails for send, but i used 25.000

**Comment by alanhartless** [comment]
Is there anything logged in app/logs/mautic_prod.php? Try searching for MAIL ERROR.

**Comment by jhrocha** [comment]
I found the file. 
The error ->  "mautic.ERROR Address in mailbox given [desplugado.@gmail.com] does not comply with RFC 2822, 3.6.2."

**Comment by jhrocha** [comment]
But, the history show the email activity.
![captura de tela 2015-06-27 as 01 25 48](https://cloud.githubusercontent.com/assets/5194011/8390439/824e58d6-1c6b-11e5-9698-267eb9cd1c32.png)

**Comment by jhrocha** [comment]
The error occurs when an e-mail tries to be sent to an invalid address, after that, the platform does not send emails to others, including the valid addresses

**Comment by alanhartless** [comment]
Hmm, what version of Mautic are you using? I thought we had fixed that issue.  The invalid RFC 2822, 3.6.2 error is caught and logged for the offending email but shouldn't hold up the process.

**Comment by jhrocha** [comment]
I saw on early commits the your fix. This stranger, because my version is 1.1.2

**Comment by jhrocha** [comment]
Hey, Alan. How are you ?
In the next version, the error will fixed ?
