### ISSUE TITLE
campaign doesn't update categories

### ISSUE THREAD

**Issue by gnunicorn** [mautic/mautic#5823]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | n 
| Enhancement? |  n

## Description:

I have a campaign trying to migrate from segments to the global categories (so we can allow users to unsubscribe from newsletters via their preferences page) as well as one for a double-opt-in via an email-link-click. Both have a "Update Contact"-Action at the end, where their Newsletter Subscription is supposed to be updated with the given Categories ("Allgemeiner Newsletter"), and yet, though I can see the action is being triggered (according to the campaign log) the contacts are still not subscribed to the newsletter. Here the configuration screen for the double-opt-in:

![screenshot sun mar 18 2018 19 46 23 gmt 0100 cet 2122x1088](https://user-images.githubusercontent.com/40496/37569615-61f263da-2ae5-11e8-9e29-490c176a738c.png)
![screenshot sun mar 18 2018 19 46 34 gmt 0100 cet 1968x909](https://user-images.githubusercontent.com/40496/37569614-61d7f694-2ae5-11e8-881c-e45cd2ca0372.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Mautic version 2.12.2 - app/prod
| PHP version |  7.0.27
| Docker Image | "mautic/mautic"

### Steps to reproduce:
1. Create a campaign with an update-contact action and add a newsletter category there
2. trigger campaign for user
3. the user's category isn't updates (altough it should have been)
 
### Log errors: 

```
cat app/logs/mautic_prod-2018-03-18.php 
[2018-03-18 18:09:09] mautic.WARNING: Command `mautic:update:apply` exited with status code 1 [] []
[2018-03-18 18:09:34] mautic.WARNING: Command `mautic:update:apply` exited with status code 1 [] []
```

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
