### ISSUE TITLE
HTML not rendering when sending EMAIL using REST endpoint where token contains HTML 

### ISSUE THREAD

**Issue by sawanCD** [mautic/mautic#5826]
| Q  | A | Feature request? 

### Steps to reproduce:
1.Create a new EMAIL Template in code mode 
2. Make a variable say {xyz}
3. Everything works file until i send xyz as "html" `("<li></li>")`
4. The token is printed as it is and not rendered. Is there a way to do this.

**Comment by rraulinio** [comment]
Posted this as well, any answer at all?

**Comment by sawanCD** [comment]
@rraulinio Changed in Email controller. It worked fine

**Comment by rraulinio** [comment]
What did you change, exactly?

**Comment by rraulinio** [comment]
Cheers! (y)
