### ISSUE TITLE
Errors on Login

### ISSUE THREAD

**Issue by drexelroth** [mautic/mautic#583]
Hello - 

I installed and have been using Mautic and this week I encountered a series of errors when I logged in. I have copy and pasted the errors below. I'm not sure where I should begin troubleshooting. I have only one entry in my log also below. I would greatly appreciate any direction on how I can troubleshoot this. I'm not sure if it is a caching issue or something else?

Thanks in advance, 
Drexel 

Log Entry:
mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Sorry! The requested URL was not found." at /home/site/public/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Controller/Controller.php line 151 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Sorry! The requested URL was not found. at /public/vendor/symfony/framework-bundle/Symfony/Bundle/FrameworkBundle/Controller/Controller.php:151)"} []

Call Stack
	Time 	Memory	Function	Location
1	0.0000	236512	{main}( )	.../index.php:0
2	0.0029	2108608	AppKernel->handle( )	.../index.php:38
3	0.0505	6666720	Symfony\Component\HttpKernel\Kernel->handle( )	.../AppKernel.php:115
4	0.0507	6668864	Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle( )	.../bootstrap.php.cache:2361
5	0.0507	6670288	Symfony\Component\HttpKernel\HttpKernel->handle( )	.../bootstrap.php.cache:3112
6	0.0507	6670688	Symfony\Component\HttpKernel\HttpKernel->handleRaw( )	.../bootstrap.php.cache:2963
7	0.1099	8541576	call_user_func_array:{/public/app/bootstrap.php.cache:3001} ( )	.../bootstrap.php.cache:3001
8	0.1099	8542664	Mautic\DashboardBundle\Controller\DefaultController->indexAction( )	.../bootstrap.php.cache:3001

**Comment by escopecz** [comment]
Have you tried clear the cache? Delete content of folder app/cache/prod.
It that doesn't help, can you confirm that mod_rewrite is allowed?

**Comment by drexelroth** [comment]
I cleared cache/prod folder and am still getting error when I login. I am using nginx and my location block looks like this: 

 location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

Could this be causing error? I didn't get this error for about two weeks or so of use, it just recently started.

I appreciate the help!

**Comment by drexelroth** [comment]
UPDATE: I deleted the only landing page I had created and the errors disappeared.

**Comment by escopecz** [comment]
I don't know much about nginx, but this might help you: https://gist.github.com/drmmr763/747b9dc984faa58b6986

**Comment by drexelroth** [comment]
I have nginx setup the same as the posted link and I am still running into the same error. It seemed have started when I turn the API Oauth 2.0 on. However, I tried turning on and off and clearing cache and I still receive the same error.  

It worked error free for about a week when I first installed it. Should I try reinstalling and restoring database or is there something else I should try? 

Thanks! Drexel

**Comment by alanhartless** [comment]
Hi @drexelroth,

Can you give some more info on the series of errors you receive on logging in? Are you getting the 404 each time you try to login or something else?

Thanks,
Alan

**Comment by drexelroth** [comment]
Here are the errors:

( ! ) Warning: Division by zero in /home/site/public/app/bundles/DashboardBundle/Controller/DefaultController.php on line 55
Call Stack
#	Time	Memory	Function	Location
1	0.0000	236376	{main}( )	.../index.php:0
2	0.0028	2108392	AppKernel->handle( )	.../index.php:38
3	0.0502	6664200	Symfony\Component\HttpKernel\Kernel->handle( )	.../AppKernel.php:115
4	0.0503	6666344	Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle( )	.../bootstrap.php.cache:2361
5	0.0504	6667768	Symfony\Component\HttpKernel\HttpKernel->handle( )	.../bootstrap.php.cache:3112
6	0.0504	6668168	Symfony\Component\HttpKernel\HttpKernel->handleRaw( )	.../bootstrap.php.cache:2963
7	0.1282	8539184	call_user_func_array:{/home/site/public/app/bootstrap.php.cache:3001} ( )	.../bootstrap.php.cache:3001
8	0.1282	8540272	Mautic\DashboardBundle\Controller\DefaultController->indexAction( )	.../bootstrap.php.cache:3001

**Comment by escopecz** [comment]
This error should be fixed by https://github.com/mautic/mautic/pull/714. Could you test it and confirm?

**Comment by drexelroth** [comment]
Fixed! Thank you
