### ISSUE TITLE
Elasticemail alternative server and port to add

### ISSUE THREAD

**Issue by khaoua** [mautic/mautic#5832]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | 
| Enhancement? | yes

## Description:
Elasticemail settings are set only based on server smtp.elasticemail.com with port 2525. Issue is that many hosts act differently, as per example in europe (e.g France, Switzerland, Germany) port 2525 can be considered as non standard and opened only for defined whitelisted IP's. In Mautic, that leads to configurate email settings on "othersmtp" with server smtp.elasticemail.com and working opened port (e.g 465)
However, Elasticemail "notifications" setting for bounces, unsubscribed, complaints ect... get error message when trying to set url for callback
Working solution is to change file in app\bundles\EmailBundle\Swiftmailer\Transport\ElasticemailTransport.php with altarnative server and port given by elasticmail SMTP/API settings docs

server would be: smtp25.elasticemail.com and port: 25
It is set on my mautic instance, and elasticemail notification settings could be saved without errors.

Of course, working default server and port should not be impacted, this is a request to add the "compatibility" with alternative server and port working with elasticemail (alternative set by elasticemail itself)

would be good to integrate it to next 2.13 version to avoid requirement of changing the file after each upgrade while campaigns are running

FYI, I've put a pull request by mistake on this, feel free to use it for this issue, or create a new one
https://github.com/mautic/mautic/pull/5830
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. email config set with elasticemail account based on file with both smtp options (usual one 
that is: smtp.elasticemail.com and port: 2525; and alternative one smtp25.elasticemail.com and port: 25)
hosting server port 2525 locked (as it is considered non-standard by some hosters)

2. url notification saved and enabled successfully on elasticemail account for bounces, unsubscribe etc...
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by robwent** [comment]
In my `app/config/local.php` file, I have:

    'mailer_transport' => 'mautic.transport.elasticemail',
    'mailer_host' => 'smtp25.elasticemail.com',
    'mailer_port' => '25',

No idea if I set that manually but I think I'm sending out through port 25

**Comment by robwent** [comment]
@dbhurley I know it's a pain, but explaining why it's closed would help in the long run.

**Comment by dbhurley** [comment]
Fair enough, thank you for the reminder. It's overwhelming dealing with 400+ open issues and trying to respond to each. 😉

This particular issue is more of an enhancement that should be added to the Ideas forum on Mautic.org, it sounds as though it can be set via the config based on the response by @robwent

Hope this helps!

**Comment by robwent** [comment]
I get that

**Comment by khaoua** [comment]
@robwent you had probably changed your file manually, cause the default values are not those ones, and I had to change them as well manually to make it work correctly with alignment of elasticemail notifications

@dbhurley sad that is straighfully closed. As Elasticemail integratin is only partially done in mautic, it would be in my view necessary to include what Elasticemail defined as "alternative server and port" to associate with any apps connecting to Elasticemail. For me it is not an ehancement or "nice to have" somewhere in a Forum
