### ISSUE TITLE
Form submit action: Option "Send a webhook" is missing

### ISSUE THREAD

**Issue by AlbanL74fr** [mautic/mautic#5839]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
When creating a new form (standalone, or not), the form action "Send a webhook" is missing from the list of available actions.

**Comment by kuzmany** [comment]
But Send a webhook is campaign action, not form

**Comment by AlbanL74fr** [comment]
Hi Kuzmany, thx for replying. It would be useful to be able to send a webhook (to add a new lead in pipedrive when certain forms are submitted). Today I am looking for this option into form submit action, due to the non recurence of campaigns (same user can't go through the campaign twice, which is a serious limitation IMO).
Why wouldn't it be a form submit action too? It's already possible to push an integration whenever a form is submitted, why not sending a webhook? Thx

**Comment by kuzmany** [comment]
@AlbanL74fr I understand you, I code that feature and It was donated. I just think this is not bug, just feature request. And as @dbhurley  announced https://www.mautic.org/community-blog/moving-feature-requests/,  feature requests were moved to another place. Anyway If you are budget I can create this feature.
