### ISSUE TITLE
The entity-class 'Mautic\DynamicContentBundle\Entity\DynamicContentLeadData' mapping is invalid

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#5847]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

When running php app/console doctrine:schema:validate the console says:

[Mapping]  FAIL - The entity-class 'Mautic\DynamicContentBundle\Entity\DynamicContentLeadData' mapping is invalid

Almost same that #4364 but we don't have any custom field with special characters

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2 / 2.11.0 / 2.10.0
| PHP version | 7.0.28

### Steps to reproduce:
1. Open Console
2. run app/console doctrine:schema:validate

 
### Log errors: 

[Mapping]  FAIL - The entity-class 'Mautic\DynamicContentBundle\Entity\DynamicContentLeadData' mapping is invalid:
* The association Mautic\DynamicContentBundle\Entity\DynamicContentLeadData#dynamicContent refers to the inverse side field Mautic\DynamicContentBundle\Entity\DynamicContent#id which is not defined as association.
* The association Mautic\DynamicContentBundle\Entity\DynamicContentLeadData#dynamicContent refers to the inverse side field Mautic\DynamicContentBundle\Entity\DynamicContent#id which does not exist.
[Database] OK - The database schema is in sync with the mapping files.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Comment by bsmolyanov** [comment]
I had the same issue and managed to resolve it by replacing 'id' with 'stats' on line 68 of mautic/app/bundles/DynamicContentBundle/Entity/DynamicContentLeadData.php
like this:
instead of ->inversedBy('id')
it became ->inversedBy('stats')
