### ISSUE TITLE
Fix for 'Bazinga\OAuthServerBundle\Model\RequestToken' mapping is invalid

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#5848]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

Running **php app/console doctrine:schema:validate** we have an error about Bazinga\OAuthServerBundle.

Inspecting vendor directory, I found that the files **AccessToken.orm.xml** and **RequestToken.orm.xml** on directory **vendor/willdurand/oauth-server-bundle/Resources/config/model** has an mapping with field expires_at like this:

`<field name="expiresAt" column="expiresAt" type="int" />`

Changing  to:

`<field name="expiresAt" column="expiresAt" type="integer" />`

Solves the problem.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.9+
| PHP version | 7.0.28

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

[Mapping]  FAIL - The entity-class 'Bazinga\OAuthServerBundle\Model\AccessToken' mapping is invalid:
* The field 'Bazinga\OAuthServerBundle\Model\AccessToken#expiresAt' uses a non-existant type 'int'.

[Mapping]  FAIL - The entity-class 'Bazinga\OAuthServerBundle\Model\RequestToken' mapping is invalid:
* The field 'Bazinga\OAuthServerBundle\Model\RequestToken#expiresAt' uses a non-existant type 'int'.

**Comment by virgilwashere** [comment]
Submitted [PR #4](/mautic/BazingaOAuthServerBundle/pull/4) to the [forked repo](/mautic/BazingaOAuthServerBundle)

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
