### ISSUE TITLE
issue with radio field in form mapped to a select custom field

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5852]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is a problem in form when you map a radio field with a select custom field.
In the properties tab, if you select YES (mean you don't need to re-create the values), these values won"t be displayed in the form.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Create a select custom field
![image](https://user-images.githubusercontent.com/31535432/37765876-accb4b14-2dc5-11e8-9763-3d5c2269a1c8.png)
2. Create a form and add a radio group field
3. Map it with the select field previously created
4. In the property tab, click on YES
![image](https://user-images.githubusercontent.com/31535432/37765938-db3d45ec-2dc5-11e8-8ae4-6bf8087357bb.png)
5. Save, close and check your form. See that the values are not displayed
![image](https://user-images.githubusercontent.com/31535432/37766037-12f1416e-2dc6-11e8-968d-aad6f56e080e.png)
6. Go back in the form in the properties tab, this time click on NO and add the same values as the custom field
![image](https://user-images.githubusercontent.com/31535432/37766109-3adfe996-2dc6-11e8-9089-13a94b9d31b6.png)
7. Save, close and check the form. This time values are displayed
![image](https://user-images.githubusercontent.com/31535432/37766130-4ab6d7da-2dc6-11e8-82b5-8139db2fafdb.png)

So there is a bug when you click on YES. There are not displayed.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Label: Ready to test

https://github.com/mautic/mautic/pull/6061

**Comment by johbuch** [comment]
I think we can close this issue as it seems to be solved in the 2.13.1
