### ISSUE TITLE
issue with select field with pipedrive sync to mautic

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5861]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is an issue with the pipedrive sync when you map a select field (in pipedrive) with a select field (in mautic) from Pipedrive to Mautic.
After using the webhook to sync contacts from pipedrive to mautic, the select field in mautic will be filled with numbers (whereas the real value).

## If a bug:
| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Create a select field in Pipedrive
![image](https://user-images.githubusercontent.com/31535432/37895241-fd66321e-30e0-11e8-9d7d-528a919cd696.png)
2. Create a multiselect field in mautic
![image](https://user-images.githubusercontent.com/31535432/37895278-196f05da-30e1-11e8-9b22-4a7a8936c2be.png)
3. Set the pipedrive plugin (map the 2 previous field created together) and add a webhook in pipedrive to sync contacts from pipedrive to mautic
4. Create a new contact in pipedrive and fill with both values the select field. (my filed is totomation)
![image](https://user-images.githubusercontent.com/31535432/37895469-a619e496-30e1-11e8-8dfd-f0ae9a0dd568.png)
5. The contact is automatically synced thanks to the webhook.
6. Go check the contact in mautic.
7. FIRST BUG: I've got a duplicate contact because in pipedrive I added both values in the select field
![image](https://user-images.githubusercontent.com/31535432/37895560-f7783a04-30e1-11e8-9035-6834f897fa8d.png)
8. SECOND BUG: Values on the field are not the good one, its some numbers (and not the values that I filled when creating my field which is test1 and test2)
![image](https://user-images.githubusercontent.com/31535432/37895628-2a4e9860-30e2-11e8-980f-f27e67d0b131.png)

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
@kuzmany do you think it is corrected by https://github.com/mautic/mautic/pull/5258 ?

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by npracht** [comment]
Label: Bug

**Comment by kuzmany** [comment]
@npracht maybe. need re-test with patches

**Comment by heathdutton** [comment]
@johbuch  #5258 will ship with 2.14.1 and is in staging. Please test if possible. If that does not entirely solve the problem please test #5401 as well and report your findings, that will ship in 2.15.0 most likely.
