### ISSUE TITLE
issue with bitly when sending sms with link inside

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5862]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When sending a sms with a bit.ly link inside, even if the contact does not click on the link (so visits the page), it will be written in his history sheet that he visited the page.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Set the twilio plugin
2. Set the url shortener with bit.ly
3. Create a sms with a link inside
4. Create a campaign and send the sms
5. Do not open the sms (so don't click on the link)
6. Go check the contacy sheet
7. See that you visited the page (even if you did not click on the link)
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Cannot reproduce. Please more information

**Comment by kuzmany** [comment]
Remove WIP because can't reproduce.
Postponed

**Comment by npracht** [comment]
test https://github.com/mautic/mautic/pull/6591

**Comment by johbuch** [comment]
@kuzmany I tested again and I still have this issue on 2.15
can you try again ?
thanks

**Comment by kuzmany** [comment]
@johbuch Did you add bitlybot to configuration to do_not_track_bots list?
Like was mentioned in that PR? https://github.com/mautic/mautic/pull/6591

**Comment by johbuch** [comment]
@kuzmany indeed it works with that. I was not aware of this one.
Thanks a lot !!!!!
