### ISSUE TITLE
Grid for Campaign, Lines Type and Auto Organizer

### ISSUE THREAD

**Issue by moskoweb** [mautic/mautic#5863]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
It would be interesting a [grid](https://jsplumbtoolkit.com/community/doc/dragging.html#grid) to organize the construction of campaigns, because in the loose mode, can not always adjust for easy viewing the entire campaigns run. Especially when it involves big campaigns.

Or maybe an option of automatic organizer, would be nice too, could be a nice alternative.

Or maybe an option to use straight lines instead of loose curves, as in this [example](https://jsplumbtoolkit.com/demos/toolkit/flowchart-builder/index.html)

It could be an option in the settings for the type and defaults used in the Campaign Builder.

**Comment by MauriceW2** [comment]
Adding a grid is fairly simple. Just add this to the bottom of your /media/css/app.css file:

`#CampaignCanvas {
	background-color: #eee;
    background-size: 40px 40px;
    background-image: linear-gradient(to right, #fafafa 1px, transparent 1px), linear-gradient(to bottom, #fafafa 1px, transparent 1px);
}
`
