### ISSUE TITLE
issue with form token when sending results

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5866]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is an encoding issue when sending the form result by using {formfield} token in the subject.
The symbol ' is translated with &#39;
Step to reproduce below

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Create a form with email and contact company
![image](https://user-images.githubusercontent.com/31535432/37973045-eaefb69c-31d9-11e8-8486-0cbee25b2376.png)
2. Add action: send form results
3. Add the token {formfield=company} in the subject
![image](https://user-images.githubusercontent.com/31535432/37973082-0460bf2c-31da-11e8-9399-def6f60aa658.png)
4. Add an email address to send the results
5. Save and close
6. Fill the form. In the company field, write a company name with this symbol ' like: test'test
7. Wait for the form result and check.
8. See that in the subject it is written test&#39;test
9. See that in the content of the email, the company name is well written.
![image](https://user-images.githubusercontent.com/31535432/37973446-d0d95302-31da-11e8-930f-e40a28dcc00f.png)

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/6048

**Comment by kuzmany** [comment]
Label: Ready to test
