### ISSUE TITLE
Dynamic content in email is not rendered when using the form submit action "Send form results"

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#5867]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I have a form where a formfield value "Bank & Topup Method" is mapped to a custom contact field name "Latest Topup Instrument" because I would like to display different "Topup instructions", depending of what was the bank selected by the contact.

The results are received correctly when the form is submitted.

![image](https://user-images.githubusercontent.com/23435414/37982325-7af323d8-321a-11e8-8b96-cca433c4ba1c.png)

I created a custom contact field named "Latest Topup Instrument" to pilot the dynamic content, and, it's updated accordingly to what has been passed in the form result as the value of "Bank & Topup Method". 

![image](https://user-images.githubusercontent.com/23435414/37982380-9e0be198-321a-11e8-9ba7-49a26eeb5164.png)

Now, when I add to this form the following "form submit" actions : 
- "Send to user" : (To myself) With dynamic content/instructions in the email depending of the value of the contact field "Latest Topup Instrument".
- "Send form result" : (To the contact/lead) With dynamic content/instructions in the email depending of the value of the contact field "Latest Topup Instrument".

![image](https://user-images.githubusercontent.com/23435414/37980693-e6321398-3215-11e8-860b-883eb5650e98.png)

The following issue occurs : 

- In the email received by myself (from the "Send to user" action), the dynamic content is rendered, as in the example below : 

![image](https://user-images.githubusercontent.com/23435414/37981798-d7f9555e-3218-11e8-9099-7708b0af0903.png)

- However, in the email received by the lead (from the "Send form results" action), **the dynamic content is not rendered**, as you can see below:

![image](https://user-images.githubusercontent.com/23435414/37981809-dfcf706a-3218-11e8-8420-21ec81d682cf.png)

Btw, I have already tried to switch the vertical order in which both form submit actions are displayed (or triggered??), but it didn't change anything. Is there something I am doing wrong?

The dynamic content, and variants in both email templates are exactly the same.

Note : It seems that I can not use formfields, but only contact fields to control variation in the dynamic content. Therefore I created a custom contact field named "Latest Topup Instrument".

![image](https://user-images.githubusercontent.com/23435414/37982191-0e6feeda-321a-11e8-9c43-1232264727c1.png)

Thanks for your help, Mautic friends.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 5.6.32

### Steps to reproduce:

For the sake of simplicity, let's use the same template in both form submit actions. I have tested and replicated it that way too. Same result/bug.

1. Create a form with a field "Bank & Topup Method"
2. In the "Bank & Topup Method" form field parameter, make sure it will update a custom (contact) field "Latest Topup Instrument"
3. Create a template of email
4. Add a dynamic content using "Latest Topup Instrument" and providing different variants of contents for different values of "Latest Topup Instrument"
5. Create two form submit actions : "Send form result" and "Send to user" and use the template created
6. Submit the form, and check both your (user) email, and (control) contact email.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
