### ISSUE TITLE
[Enhancement] Allow filtering contacts by UTM data within campaigns.

### ISSUE THREAD

**Issue by heathdutton** [mautic/mautic#5868]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Yes

## Description:
We will often have a campaign (in other systems) that diverts based upon incoming UTM Source (or other UTM properties).  

However, the "Contact field value" condition does not include UTM fields, making our typical business    workflow impractical in Mautic. The only alternative is to set up hundreds of segments... not ideal.

We wish to filter by the most recent UTM fields to divert contacts left or right within the campaign, just as we can do for all other "lead fields".

PR incoming...

**Comment by Maxell92** [comment]
Hello @heathdutton,

you might be interested in https://github.com/mautic/mautic/pull/5974.

**Comment by Maxell92** [comment]
Hello @heathdutton,

PR was merged, so I closed this issue too.
