### ISSUE TITLE
Extra new line in every (email) dynamic content

### ISSUE THREAD

**Issue by individual-it** [mautic/mautic#5872]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Dynamic content in Emails have always an new line at the end.
I'm crating "Dynamic content" for emails to personalize them, but every one has a `<br>` at the end. Switching to 'code-view' in the dynamic content WYSIWYG editor I can delete that new line, switching back or saving brings them back

my dynamic_content in emails table looks like
```
a:2:{i:0;a:3:{s:9:"tokenName";s:17:"Dynamic Content 1";s:7:"content";s:23:"Default Dynamic Content";s:7:"filters";a:1:{i:0;a:2:{s:7:"content";s:10:"variation1";s:7:"filters";a:0:{}}}}i:1;a:3:{s:9:"tokenName";s:17:"Dynamic Content 2";s:7:"content";s:8:"Du<br />";s:7:"filters";a:1:{i:0;a:2:{s:7:"content";s:9:"Ihr<br />";s:7:"filters";a:2:{i:0;a:7:{s:4:"glue";s:3:"and";s:5:"field";s:3:"sex";s:6:"object";s:4:"lead";s:4:"type";s:6:"lookup";s:6:"filter";s:1:"p";s:7:"display";N;s:8:"operator";s:1:"=";}i:1;a:7:{s:4:"glue";s:2:"or";s:5:"field";s:3:"sex";s:6:"object";s:4:"lead";s:4:"type";s:6:"lookup";s:6:"filter";N;s:7:"display";N;s:8:"operator";s:5:"empty";}}}}}}
```

did not happen in 2.11

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.12.2
| PHP version | 7.0.28

### Steps to reproduce:
1.  create multiple dynamic contents for Emails
2.  use them in the email
3.  save and exit the email
4. edit the email again, check the preview

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
