### ISSUE TITLE
Click count records only on first link in newsletter 

### ISSUE THREAD

**Issue by sofocle80** [mautic/mautic#5879]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| --| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | Y

Not sure if a bug, perhaps is just my lack of knowledge

## Description:
_When sending an email newsletter, I get click count only for the first link in email. 
.......................
For the rest of the links I get no redirect trough mautic it jumps opens the site, so I do not get the confirmation in mautic if the button (link) was used.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.12.2
| PHP version |  PHP Version 7.0.28-0ubuntu0.16.04.1

### Steps to reproduce:
1.          
2.     
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dbhurley** [comment]
Can't replicate, will re-open if others experience. Otherwise, check the forums or Slack for support.
