### ISSUE TITLE
[Enhancement] Allow filtering contacts by UTM data for segments.

### ISSUE THREAD

**Issue by heathdutton** [mautic/mautic#5885]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Yes

## Description:
Continuing from #5868 we sometimes need to cut a new segment based on inbound UTM data.
For example, we may want to perform a report on all Google traffic. Or create a new campaign to retarget customers from paid ads which share a few UTM Sources.

PR incoming...

**Comment by Maxell92** [comment]
Hello @heathdutton,

are you working on this feature? There is a complete segment's refactoring planned for 2.14: https://github.com/mautic/mautic/pull/5755

This PR is waiting for testing (need to be tested really heavily as it is a crucial function of Mautic), but once it will be merged, old code is going to be deprecated and not used anymore.

Thanks!

**Comment by heathdutton** [comment]
This PR works in production for us (we deploy as a patch) with 2.12.2 so I'm not working on this feature any more... Obviously it'll have to be re-done or integrated into your PR if we want to continue using this feature with 2.14.x. For us this is an essential feature.

Same goes for #5911

**Comment by Maxell92** [comment]
Hi @heathdutton,

Sorry I missed your PR somehow. I think I will rewrite https://github.com/mautic/mautic/pull/5886 for new segments, so this will be included in 2.14 with new release.

But you need to rewrite https://github.com/mautic/mautic/pull/5911 after we merge the refactoring.

**Comment by heathdutton** [comment]
@Maxell92 np. I assume I'll need to rewrite #5885 (this PR) as well?

**Comment by Maxell92** [comment]
Are you sure you have linked correct PR? Last link is going to this issue (this page). Try to click on it :)

**Comment by heathdutton** [comment]
Yes. You said you'd rewrite #5886, I was asking about this one... The PR we're looking at right now. What about it? lol

**Comment by heathdutton** [comment]
Duh, yea you're right. Sorry.

**Comment by npracht** [comment]
Fixed in #5886 and merged
