### ISSUE TITLE
404 on API call

### ISSUE THREAD

**Issue by dennisgon** [mautic/mautic#5889]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
 I try to use Rest API using basic Auth using postman my endpoint is http://localhost/index.php/api/ and i try another endpoint http://localhost/api/ but still the same error. i already traced the log files but there isn't error in there and i already try to traced the log files of server and there is no error how can i traced the error 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 5.6.34

### Steps to reproduce:
1.  I try to use Rest API using basic Auth using postman my endpoint is http://localhost/index.php/api/ and i try another endpoint http://localhost/api/ but still the same error
 
### Log errors: 
these the json error i get from postman

` {
    "errors": [
        {
            "message": "Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!",
            "code": 404,
            "type": null
        }
    ],
    "error": {
        "message": "Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)",
        "code": 404
    }
} `

**Comment by dbhurley** [comment]
I don't believe this is a bug as others can't replicate. If there are additional reports we can re-open it.

**Comment by gugacavalieri** [comment]
It happened to me after activating Mautic's API on the panel. 

Looks like you have to clear the cache after activating API.

Maybe we could suggest this as a feature? (Many people might have this problem after activating the API and they don't know they have to clear the cache to make it work ...)
