### ISSUE TITLE
Escaping removed in code mode block

### ISSUE THREAD

**Issue by jbransen** [mautic/mautic#5891]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Mautic is somehow undoing escaping on my custom html data. When I enter some escaped data inside a HTML comment in a custom HTML block in the e-mail builder and I press apply, the custom HTML gets changed.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 5.6.34

### Steps to reproduce:
1. Create a new e-mail
2. Add a "Code mode" block
3. Enter:
```
   <p>Place your content here</p>
   <!-- {"test": "this is json with embedded html <div id=\"test\"></div>"} -->
```
4. Press Apply
5. Observe that it has changed to:
```
   <p>Place your content here</p>
   <!-- {"test": "this is json with embedded html <div id="test"></div>"} -->
```
e.g. the escape backslashes have gone and data is now not valid JSON anymore.

**Comment by dbhurley** [comment]
I believe this is an editor related issue.

**Comment by jbransen** [comment]
No, I don't think so.

I found this when implementing a different editor, and when I set the underlying textarea to this value, the value that ends up in the database is the unescaped version. It can also be seen in the network inspector that the value sent to the server is still escaped.

**Comment by aspiers** [comment]
I also see this happening with HTML entities like `&lt;` and `&gt;`

**Comment by aspiers** [comment]
Can anyone give some hints for where to start looking on this?  If so maybe I can take a stab at it.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
