### ISSUE TITLE
Hubspot Plugin Integration Error Reported

### ISSUE THREAD

**Issue by afonseca08** [mautic/mautic#5894]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
I have been getting a notification in Mautic UI regarding the Hubspot integration plugin:
![screenshot 2018-04-03 16 26 58](https://user-images.githubusercontent.com/863419/38280743-df0f63fe-375b-11e8-8c2d-2ed36dd69850.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6.33

### Steps to reproduce:
1. Open Mautic dashboard
2. Observe error notification in UI
3. View app/logs/ for matching timestamp of error message
 
### Log errors: 

Looking into the logs in app/logs I see the following associated error:
```
[2018-04-03 18:45:05] mautic.ERROR: INTEGRATION ERROR: Hubspot - internal error [] []
```

I don't see any related errors in error_log.

**Comment by afonseca08** [comment]
@dbhurley, would you please share the reason for closing this?

**Comment by lasram** [comment]
I got the same error and the plugin popup doesn't show anything (loading).
I just commented out the line 166 in the function getAvailableLeadFields of the file HubspotIntegration.php
return $fields;
and now the popup works again.
Hope this helps.

**Comment by HermanMonteiro** [comment]
Does anyone have any updates about this bug? I have the same problem
