### ISSUE TITLE
Hubspot Integration PHP Warnings/Notices

### ISSUE THREAD

**Issue by afonseca08** [mautic/mautic#5895]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Reviewing Mautic's error_log I see warnings/notices related to the Hubspot integration:

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6.33

### Steps to reproduce:
1. Review error_log and observe PHP warning/notice messages related to Hubspot integration

 
### Log errors: 

```
[24-Mar-2018 19:40:18 UTC] PHP Notice:  Undefined index: results in public_html/mautic/plugins/MauticCrmBundle/Integration/HubspotIntegration.php on line 389
[24-Mar-2018 19:40:18 UTC] PHP Warning:  array_merge(): Argument #2 is not an array in public_html/mautic/plugins/MauticCrmBundle/Integration/HubspotIntegration.php on line 389
```

**Comment by mundadashri** [comment]
I am also seeing these error in the log file -
Mautic version: 2.16.2
PHP version: 7.2.24-0ubuntu0.18.04.4

Log errors:
`PHP Notice:  Undefined index: results in /var/www/mautic/plugins/MauticCrmBundle/Integration/HubspotIntegration.php on line 415
PHP Warning:  array_merge(): Argument #2 is not an array in /var/www/mautic/plugins/MauticCrmBundle/Integration/HubspotIntegration.php on line 415`

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
