### ISSUE TITLE
mautic keep tagging emails as bounced 

### ISSUE THREAD

**Issue by khalidelmerrah** [mautic/mautic#5897]
hello mautic support,

i have just uploaded a test list with 30 gmail and hotmail accounts, that my friends have access to and the emails are legit and working just fine, but mautic keeps tagging them as email bounced under the name of incorrectly formatted email address.
what went wrong ? tell me what to check please thank you

**Comment by dbhurley** [comment]
Thanks for the question, but you'll have better luck posting this in the community forums or Slack instead of on GitHub as an issue.
