### ISSUE TITLE
Internal Server Error - Manage Integrations

### ISSUE THREAD

**Issue by detroitwebdevelopers** [mautic/mautic#59]
Also getting an internal server error when accessing the "Manage Integrations" page.
![mautic_dashboard-error](https://cloud.githubusercontent.com/assets/6193465/6268039/64984648-b817-11e4-8ddf-26400ebf8ee3.png)

**Comment by alanhartless** [comment]
Hi again,

Same thing here.  Whenever you a page like that, take a peak at your log app/logs/mautic_prod.php which will tell us exactly what's going on.

Thanks!
Alan

**Comment by alanhartless** [comment]
Hi!

Closing due to lack of feedback.  If you continue to get the error with the latest releases, please open a new issue.

Thanks!
Alan
