### ISSUE TITLE
Randomizer and limit sends option on segment emails

### ISSUE THREAD

**Issue by justinfortes** [mautic/mautic#5903]
Customer: Samples.com
Due Date: 6/30/18

The randomizer feature is specific to this Samples.com use case. 

Description:
Samples has partners and customers that request for a specific amount of outreach to the Samples.com user base. 

Segments only
Limit setting on total send
Randomized selection of the segment

Only for total users to be sent
Does not include limits on opens, clicks, etc. 

More details coming soon...

**Comment by mleffler** [comment]
Moved to mautic-internal/mautic-internal#124
