### ISSUE TITLE
Errors in campaign and some dynamic fields not populated

### ISSUE THREAD

**Issue by socmov** [mautic/mautic#5904]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:
I have a simple campaign to send out an email with a number of dynamic content pieces which rely on different filter properties.

I get errors in the logs when the campaign runs. The emails are received but about 50% of the email used the default variation for dynamic content and field tags (e.g. {contactfield=firstname}) remaining in the email instead of being replaced. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.0
| PHP version | 5.6.30

### Steps to reproduce:
1. Create an email with a field tag in the first paragraph (e.g. Hi {contactfield=firstname},)
2. Create a dynamic content paragraph and use a filter based on two contact field properties (!A!B, A!B, !AB, AB)
3. Create another dynamic content paragraph and use a filter based on a number of values from a select list field
4. Create a third dynamic content paragraph and use a filter based on an exact match for a text field
5. Create a simple campaign to send the emails
6. Some emails received without problem. Some emails did not populate the tags. Some emails left every dynamic content on the default value. 
 
### Log errors: 
PHP Warning:  Invalid argument supplied for foreach() in /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/EventListener/MatchFilterForLeadTrait.php on line 154
PHP Warning:  Invalid argument supplied for foreach() in /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/EventListener/MatchFilterForLeadTrait.php on line 154
PHP Warning:  Invalid argument supplied for foreach() in /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/EventListener/MatchFilterForLeadTrait.php on line 154
PHP Warning:  Invalid argument supplied for foreach() in /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/EventListener/MatchFilterForLeadTrait.php on line 154
PHP Notice:  Undefined variable: utm_content in /opt/bitnami/apps/mautic/htdocs/plugins/MauticAnalyticsTaggingBundle/EventListener/EmailSubscriber.php on line 115

**Comment by socmov** [comment]
I'm wondering if there is a problem with my data. I am also seeing the problem with bug https://github.com/mautic/mautic/issues/5901

Is there any way to check if there is an issue with the data?

**Comment by socmov** [comment]
I found the problem in the EmailBundle. PR submitted: https://github.com/mautic/mautic/issues/5916

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
