### ISSUE TITLE
[Enhancement] Allow filtering contacts by Campaign Membership for segments.

### ISSUE THREAD

**Issue by heathdutton** [mautic/mautic#5909]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Yes

## Description:
Continuing from #5868, #5886 we sometimes need to cut a new segment (or make a report) based on the campaign/s of certain leads after ingestion.

For example, we may want to create a campaign that directly affects leads that were pumped through campaigns A & B without worrying about how the leads got there (through any segment, form, import, etc).

This should work exactly like Segment Membership, and exclude leads that are manually removed from a campaign. Once a lead is "in" a campaign, they should always have that membership till manually removed (to stay forward compatible with rotations).

PR incoming...

**Comment by Woeler** [comment]
https://github.com/mautic/mautic/pull/5911
