### ISSUE TITLE
Segments filter by Multiple Select fields don't work

### ISSUE THREAD

**Issue by coutogomes** [mautic/mautic#5912]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When you filter a multiselect field on a segment, the contacts are not displayed.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.12.2
| PHP version | 7.0.16

### Steps to reproduce:
0. Clean Cache

1. Create a multiselect field with at least 2 options
![captura de tela 2018-04-06 18 58 01](https://user-images.githubusercontent.com/38143814/38446092-a3151100-39cc-11e8-9bf9-72f9a17d4cef.png)

2. Create a contact which have option 1 selected
![captura de tela 2018-04-06 18 58 09](https://user-images.githubusercontent.com/38143814/38446100-af6588e0-39cc-11e8-9f47-1514f6430839.png)

3. Create segment which have filter based on that multiselect field where the option 1 is included
![captura de tela 2018-04-06 18 58 33](https://user-images.githubusercontent.com/38143814/38446106-b4478232-39cc-11e8-9bf9-c8e1c2ba8d8f.png)

4. Run cron mautic:segments:update
![captura de tela 2018-04-06 19 00 58](https://user-images.githubusercontent.com/38143814/38446153-fa15dea8-39cc-11e8-96f1-c8d0ebc65d62.png)

5. Observe de segment list not included the contact
![captura de tela 2018-04-06 19 03 33](https://user-images.githubusercontent.com/38143814/38446225-4a7a1558-39cd-11e8-899f-591e489ea306.png)

### Log errors: 
No erros on log

**Comment by Maxell92** [comment]
Hello @coutogomes,

this issue is fixed in refactored segment:
https://github.com/mautic/mautic/pull/5755
