### ISSUE TITLE
Custom field Date and time always displays time as 23:00:00 when viewing contact

### ISSUE THREAD

**Issue by J-a-n-u-s** [mautic/mautic#5913]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
Added Date/Time custom field to contact.
Updated the field using a hidden input on a form.
The date shows correctly but the time is always showing as four hours ahead

I thought I was crazy and that the problem was on the input end, so I tried formatting the input with various date/time formats, and got the same result.

To test further, I created a form field specifically for Date/Time figuring that must work (type datetime-local that shows the little calendar etc). Same problem. Date is correct but time shows as four hours ahead.

Then I tried to edit the value from the contact directly and voila! Both the date and time are correct when the contact is editable. It's only the wrong time when the you're viewing the contact. The correct date and time get posted to the database.

It's notworthy for debugging purposes that the server's timezone is:
Time zone: America/Toronto (EDT, -0400)

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.12.2
| PHP version |  7.0.28-0ubuntu0.16.04.1

### Steps to reproduce:
1. Add custom field of type Date/Time to a contact to appear in the Core group (leave toggle switches to the right at their default settings)
2. Create a form with an email input that maps to the contacts email and a Date/Time input that maps to the custom field you made in step 1
3. Load the form on a page and enter an email and a date and time and submit it
4. View the contact in Mautic (without pressing "Edit") and the time should always show four ahead in my case (or the UTC-0 offset of the time in general)
5. Then click "Edit" and the time should be correct
6. Also if you toggle the details of the form submission in the event list under the contact you should also see the correct date and time there
 
### Log errors: 
No errors are reported re: Mautic, apache, php.

**Comment by J-a-n-u-s** [comment]
The only configuration server-side is setting or not setting the timezone. I imagine (without having worked on Mautic source code) that the date/time is stored in the database at GMT (i.e. UTC-0), and then timezone is only applied when that data is retrieved.

When the date/time is retrieved for editing, the timezone is applied. But when it's retrieved for display only, the timezone is not applied.

The intermediary step that applies the timezone for editing is not being called for display purposes.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
