### ISSUE TITLE
Performance issue when looking up by email

### ISSUE THREAD

**Issue by maltonite** [mautic/mautic#5917]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this: Bug/performance increase

| Q  | A
| ---| ---
| Bug report? | In mautic/app/bundles/LeadBundle/Entity/LeadRepository.php line 113 `$col   = "LOWER($col)";` means that an index isn't used on the Lead table when looking up by email, resulting in very poor performance. Also line 282 `->where('LOWER(email) = :search')` 
| Feature request? | 
| Enhancement? | 

## Description:

I propose the following solution.

1. Remove line 113 `$col   = "LOWER($col)";` and change line 282 `->where('LOWER(email) = :search')`. MySql will need to be run in non-strict mode in case emails have been stored not in lower case. 
2. Change mautic/app/bundles/LeadBundle/Entity/Lead.php function setEmail 
`public function setEmail($email)
    {
        $this->isChanged('email', $email);
        $this->email = $email;
        return $this;
    }`
 to:
`public function setEmail($email)
    {
        $this->isChanged('email', $email);
        $this->email = strtolower($email);
        return $this;
    }`
3. Finally a migration will need to be run to update all emails to be lower. 

Can anyone see any issues with this approach?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
Fixed in 2.14.2 with https://github.com/mautic/mautic/pull/6603
