### ISSUE TITLE
[Feature request] Archive old emails/segments/campaigns/focus items/...

### ISSUE THREAD

**Issue by denispavliha** [mautic/mautic#5918]
What type of report is this:

| Q  | A
| ---| ---
| Feature request | 

## Description:
The idea here is that, normally, I tend to have a lot of campaigns, emails, etc. Many are **permanent** (e.g. form handling campaigns from website forms that generate autoresponder emails) while some of those are **temporary** (e.g. sending a newsletter to a segment - a one-time event).

This is why I would suggest the ability to **archive old items** in Mautic. By doing so, I could remove them from my views and they would not steal my focus. See e.g. Metabase how they're doing this.

My current workaround is to disable (unpublish) such items with the switch on the listing (moving it from green to red) and, then, putting is:published into filter, which takes too much time. I'd love to archive obsolete emails/segments/campaigns/focus items/...

**Comment by denispavliha** [comment]
Sorry, must have missed the duplicated issue... my bad.

**Comment by cStuartHardwick** [comment]
I've added a similar request under the new "Ideas" forum, which cannot be searched by any means I can see. If someone has already moved this request, merging is in order. If not, you all might want to vote for/comment on the one I added. https://www.mautic.org/topic/archive-old-emails/

**Comment by RCheesley** [comment]
https://forum.mautic.org/t/archive-old-emails/10628 feature request here, please add your voice :) Closing this issue down in favour of the forum thread.
