### ISSUE TITLE
Email edit "PHP Notice - Undefined offset: 1"

### ISSUE THREAD

**Issue by teemuparkkinen** [mautic/mautic#5919]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | no
| Enhancement? | no

## Description:
When you edit an email it locks it to that user. If someone else try to edit that email, it shows error 500.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.13.0
| PHP version | 7.0.19-1

### Steps to reproduce:
1. User 1 edit email
2. User 2 edit that same email
 
### Log errors: 

mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "PHP Notice - Undefined offset: 1" at /var/www/ ... /app/bundles/CoreBundle/Controller/AbstractFormController.php line 256 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): PHP Notice - Undefined offset: 1 at /var/www/ ... /app/bundles/CoreBundle/Controller/AbstractFormController.php:256)

**Comment by zaharovrd** [comment]
some notice

> [2019-10-13 22:16:22] mautic.NOTICE: PHP Notice - Undefined offset: 0 - in file /app/bundles/LeadBundle/Views/Auditlog/details.html.php - at line 62 {"mauticTemplateVars":{"app":"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\GlobalVariables: {})","event":{"eventType":"update","eventLabel":"Система","timestamp":"2019-10-01 19:06:39","details":{"tags":{"added":["Status: Active"],"removed":["Pending Email Confirmation"]}},"contentTemplate":"MauticLeadBundle:Auditlog:details.html.php"},"lead":"[object] (Mautic\\LeadBundle\\Entity\\Lead: Mautic\\LeadBundle\\Entity\\Lead with ID #197627)","mauticContent":"lead","mauticTemplate":"MauticLeadBundle:Auditlog:details.html.php","view":"[object] (Mautic\\CoreBundle\\Templating\\Engine\\PhpEngine: {})"},"app":"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\GlobalVariables: {})","event":{"eventType":"update","eventLabel":"Система","timestamp":"2019-10-01 19:06:39","details":{"tags":{"added":["Status: Active"],"removed":["Pending Email Confirmation"]}},"contentTemplate":"MauticLeadBundle:Auditlog:details.html.php"},"lead":"[object] (Mautic\\LeadBundle\\Entity\\Lead: Mautic\\LeadBundle\\Entity\\Lead with ID #197627)","mauticContent":"lead","mauticTemplate":"MauticLeadBundle:Auditlog:details.html.php","view":"[object] (Mautic\\CoreBundle\\Templating\\Engine\\PhpEngine: {})","details":{"tags":{"added":["Status: Active"],"removed":["Pending Email Confirmation"]}},"type":"update","text":"
Field/Object	New Value	Old Value

**Comment by zaharovrd** [comment]
sume notice

`[2019-11-07 18:26:12] mautic.NOTICE: PHP Notice - Undefined offset: 0 - in file /home/master/m.everest-dom.com/app/bundles/LeadBundle/Views/Auditlog/details.html.php - at line 62 {"mauticTemplateVars":{"app":"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\GlobalVariables: {})","event":{"eventType":"update","eventLabel":"System","timestamp":"2019-11-06 16:59:51","details":{"tags":{"added":["Status: Active"],"removed":["Pending Email Confirmation"]}},"contentTemplate":"MauticLeadBundle:Auditlog:details.html.php"},"lead":"[object] (Mautic\\LeadBundle\\Entity\\Lead: Mautic\\LeadBundle\\Entity\\Lead with ID #245763)","mauticContent":"lead","mauticTemplate":"MauticLeadBundle:Auditlog:details.html.php","view":"[object] (Mautic\\CoreBundle\\Templating\\Engine\\PhpEngine: {})"},"app":"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\GlobalVariables: {})","event":{"eventType":"update","eventLabel":"System","timestamp":"2019-11-06 16:59:51","details":{"tags":{"added":["Status: Active"],"removed":["Pending Email Confirmation"]}},"contentTemplate":"MauticLeadBundle:Auditlog:details.html.php"},"lead":"[object] (Mautic\\LeadBundle\\Entity\\Lead: Mautic\\LeadBundle\\Entity\\Lead with ID #245763)","mauticContent":"lead","mauticTemplate":"MauticLeadBundle:Auditlog:details.html.php","view":"[object] (Mautic\\CoreBundle\\Templating\\Engine\\PhpEngine: {})","details":{"tags":{"added":["Status: Active"],"removed":["Pending Email Confirmation"]}},"type":"update","text":"`

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by lucky-naty** [comment]
mautic 4
I'm getting same in my logs
mautic.NOTICE: PHP Notice - Undefined offset: 0 - in file /var/www/www-root/data/www/mautic/app/bundles/LeadBundle/Views/Auditlog/details.html.php - at line 62 {"mauticTemplateVars":{"app":"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\GlobalVariables: {})","event":{"eventType":"update","eventLabel":"Admin","timestamp":"2022-02-17 19:46:49","details":{"tags":{"added":["new","purchased_mini","purchased"],"removed":["Abandoned Cart"]}},"contentTemplate":"MauticLeadBundle:Auditlog:details.html.php"},"lead":"[object] (Mautic\\LeadBundle\\Entity\\Lead: Mautic\\LeadBundle\\Entity\\Lead with ID #46076)","mauticContent":"lead","mauticTemplate":"MauticLeadBundle:Auditlog:details.html.php","view":"[object] (Mautic\\CoreBundle\\Templating\\Engine\\PhpEngine: {})"},"app":"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\GlobalVariables: {})","event":{"eventType":"update","eventLabel":"Admin","timestamp":"2022-02-17 19:46:49","details":{"tags":{"added":["new","purchased_mini","purchased"],"removed":["Abandoned Cart"]}},"contentTemplate":"MauticLeadBundle:Auditlog:details.html.php"},"lead":"[object] (Mautic\\LeadBundle\\Entity\\Lead: Mautic\\LeadBundle\\Entity\\Lead with ID #46076)","mauticContent":"lead","mauticTemplate":"MauticLeadBundle:Auditlog:details.html.php","view":"[object] (Mautic\\CoreBundle\\Templating\\Engine\\PhpEngine: {})","details":{"tags":{"added":["new","purchased_mini","purchased"],"removed":["Abandoned Cart"]}},"type":"update","text":"
Field/Object	New Value	Old Value
","objects":{"tags":{"added":["new","purchased_mini","purchased"],"removed":["Abandoned Cart"]}},"value":{"added":["new","purchased_mini","purchased"],"removed":["Abandoned Cart"]},"key":"tags","values":{"added":["new","purchased_mini","purchased"],"removed":["Abandoned Cart"]},"field":"tags"} []
