### ISSUE TITLE
missing country in country select field

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5920]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
In the contact field "country", a native field, the country Ivory Coast is missing
![image](https://user-images.githubusercontent.com/31535432/38499588-62acf5e0-3c08-11e8-99c1-873949813ac6.png)

## If a bug:
| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Create a new contact and search Ivory coast in the country field.
2. It is missing
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug
