### ISSUE TITLE
[Enhancement] Support includes/excludes with text fields for bulk filtering.

### ISSUE THREAD

**Issue by heathdutton** [mautic/mautic#5924]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Yes

## Description:
Filtering by state is good, but sometimes we have to filter our campaigns by a BIG whitelist or blacklist of postal codes. We're talking ~6000 zipcodes. Doing that currently would be a monstrous task, of manually entering all of those as filters. 

We'd like to be able to use includes/excludes (in/!in) filters for segments and field filters with a delimited text array. Typically we'll have a spreadsheet with thousands of zipcodes, and it'd be convenient to be able to copy that column and just paste it right into the text box.

We should delimit by newline (future-proofing), comma or space (in that order) for these in/!in statements.

![](https://i.imgur.com/8qHv4k5.png)

![](https://i.imgur.com/gZ5Z0E3.png)

PR incoming...

**Comment by npracht** [comment]
Label: Enhancement

**Comment by npracht** [comment]
Label: Ready to test

**Comment by RCheesley** [comment]
Closing as the PR was closed some time ago!
