### ISSUE TITLE
Contact updates in Mautic not pushed to SugarCRM v6

### ISSUE THREAD

**Issue by johnmillis** [mautic/mautic#5931]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
We have Mautic intergrated with SugarCRM v6.5.16.

The SugarCRM plugin feature settings are:
Push leads to this integration: No
Pull contacts from integration: Yes
Push contacts to this integration: Yes

Choose SugarCRM objects to pull contacts from:
Leads: No
Contacts: Yes
Accounts: No

Most of our field mappings are set to pull field data from SugarCRM to Mautic, except one which pushes data from Mautic to SugarCRM.

When a contact is updated in Mautic and fetchLeads is executed (tested by command as follows), Mautic pulls new/updated contacts from Sugar successfully, but then fails on pushing updates to Sugar. The PHP notice and warnings pasted below are shown in the console.

php console mautic:integration:fetchleads --integration=Sugarcrm

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.1.8

### Steps to reproduce:
1. Update a contact in Mautic
2. Execute "php console mautic:integration:fetchleads --integration=Sugarcrm"
 
### Log errors: 

PHP Notice:  Undefined index: Leads in /var/www/html/plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php on line 1276
PHP Warning:  array_keys() expects parameter 1 to be array, null given in /var/www/html/plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php on line 1319
PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php on line 1278
Number of contacts pushed: 0 updated, 0 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria)

**Comment by npracht** [comment]
Hello,

We are using it and we don't have the issue on 2.12.2.

I don't understand you feature settings.
>Push leads to this integration: No
Pull contacts from integration: Yes
Push contacts to this integration: Yes

Here is what i have:
![capture d ecran 2018-04-13 a 11 03 35](https://user-images.githubusercontent.com/14075239/38726425-6c0d797a-3f0a-11e8-806f-7fcd42b6c6c7.png)

Also, when i see the notice message i have the feeling that in your field mapping you not sending a correct value to Sugar.
Don't you have a notification on the interface that gives you more information (close to the menu where it tells you about version update)?

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by johnmillis** [comment]
Hi Norman,

Thank you for studying my error report.

My Mautic system definitely shows the features as described in the report. It does not show option "Triggered action push contacts to integration". Could this be a difference between the support for Sugar version 6.x compared with version 7.x?

I have studied SugarcrmIntegration.php and there are some differences in functionality between the major versions of Sugar.

I believe my field mappings are correct. We are just updating one field from Mautic to Sugar and it's a simple text field.

**Comment by johnmillis** [comment]
Hi,

Please does anyone know why the SugarCRM integration is different between versions 6.x and 7.x?

Thank you,
John

**Comment by npracht** [comment]
Hi @johnmillis You can readt the code here https://github.com/mautic/mautic/blob/staging/plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php

I think the authentification system is not the same and maybe APIs have some differences.
