### ISSUE TITLE
CSV with Multibyte header couldn't be imported

### ISSUE THREAD

**Issue by katzueno** [mautic/mautic#5934]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? |  N
| Enhancement? |  N

## Description:

Checked on multiple servers. CSV with Multibyte header couldn't be imported. It could possibly break Mautic import page.

## If a bug:

Tried three different envieonment

| Q   | Instance 1 (MAMP)   |  Instance 2 (Dev)  | Instance 3 (Cloud9 Legacy)
| --- | ---|---|---
| Mautic version | 2.12.1 | 2.12.1 | 2.12.2
| PHP version | 7.0.15 | 7.0.10 | 7.0.26
| Web server | Apache | Apache | Nginx

### Steps to reproduce:

1. Make a CSV file with Japanese text in header

```=sample1.csv
名前FirstName,姓LastName,郵便番号ZIP,メールアドレスEmail
コンクリート,こんくりーと,155-0000,concrete5@example.com
```

2. Import the CSV. (Sometime, 1st time works)

3. Import the CSV 2nd time.

4. The Mautic returns 500 error

5. You no longer able to visit Contact Import section.

I get the following JSON error

```
{"errors":[{"message":"Looks like I encountered an error (error #500). If I do it again, please report me to the system administrator!","code":500,"type":null}],"error":{"message":"Looks like I encountered an error (error #500). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)","code":500}}
```

 
#### [mautic root]/app/log/

```
[2018-04-11 03:33:02] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\LogicException: "A form with an empty name cannot have a parent form." at /XXXXX/vendor/symfony/form/Form.php line 273 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\LogicException(code: 0): A form with an empty name cannot have a parent form. at /XXXXXX/vendor/symfony/form/Form.php:273)"} []
```

**Comment by Bizcrony** [comment]
Any solutions?

**Comment by katzueno** [comment]
FYI, current work-around is to clear the cache, then you will be able to go back to import page.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
