### ISSUE TITLE
Click events get triggered only in private window even if not logged in

### ISSUE THREAD

**Issue by inkas** [mautic/mautic#5935]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
The click events do not get triggered in Firefox. I am not logged in to mautic, and when I open and click an email, only the open event gets triggered. I need to open it in a private window to get the click working.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.0

**Comment by npracht** [comment]
Did you ever login mautic within the same session ? Because if you're not currently logged but the cookie has been logged i think it has an impact on the behavior :)
