### ISSUE TITLE
PHP Warning - Cookie names must not be empty (2.13.0-beta)

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#5939]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

It's a PHP Warning this message appears on a fresh mautic install with 2.13.0-beta

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Install Mautic
2. See Logs
 
### Log errors: 

[2018-04-11 14:51:50] mautic.WARNING: PHP Warning - Cookie names must not be empty - in file /var/www/html/app/bundles/CoreBundle/Helper/CookieHelper.php - at line 86 [] []

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by RCheesley** [comment]
I believe this is resolved, so closing this issue.
