### ISSUE TITLE
Email Opened Tracking Not Working for RabbitMQ

### ISSUE THREAD

**Issue by dennisgon** [mautic/mautic#5943]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I want to try to track open and readed email. and i try to send email to me and my friend 
and we got a tracking image like this http://mydomain/email/5acdc9e4ec941.gif. But mautic doesn't track any open and readed email when i open it. I already try to open in incognito windows and i already try to clear the cache but there is no result. 
![image](https://user-images.githubusercontent.com/6257311/38655980-b7a1decc-3e41-11e8-9f81-9a7ca7e4296d.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1
| PHP version | 5.6.34

### Steps to reproduce:
1. Create campaign send to the segments
2. Open the email 
 
### Log errors: 

No Log errors

**Comment by dennisgon** [comment]
I already check and the problem is in my rabbitmq if i disabled the rabbitmq the tracker is working, but is there anyone can help me solved the problem?

**Comment by roberthgodoy** [comment]
I am having the same problem in version 2.12.2 :(

**Comment by npracht** [comment]
Label: Bug

**Comment by dennisgon** [comment]
@roberthgodoy are you used the https for mautic to solved the problem?

**Comment by roberthgodoy** [comment]
@dennisgon Yes :+1: now the read receipt is working!

**Comment by KennedyTedesco** [comment]
Same issue here even using https. =( I've tried a lot of things, nothing work.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
