### ISSUE TITLE
"Send test email" button does not work correctly for Sendgrid API

### ISSUE THREAD

**Issue by Maxell92** [mautic/mautic#5946]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
"Send test email" button does not work correctly for Sendgrid API. You will get an error `The provided authorization grant is invalid, expired, or revoked` if you hit this button unless you save a settings.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Save configuration with any email provider except Sendgrid API.
2. Change config to Sendgrid API, fill in API key and hit test button. You will get an error.
3. Save config with your key and hit the button again. You will get a success message now.

The problem likely be in the passing API argument to SendGrid service. If it has to be in the container instead of a setter method, then that could be why since it won't be in the container till after the config is saved.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by cesarjr** [comment]
+1

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
