### ISSUE TITLE
issue with duplicate contact set as Do not contact

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5949]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is an issue with a contact set as DNC and a duplicate contact (same email address).
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Create a contact
2. Send email to this contact and unsubscribe from email
3. Create a new contact with same email address (a duplicate)
4. See in the contact list that first contact is set DNC with logo but duplicate one is not
![image](https://user-images.githubusercontent.com/31535432/38725380-7a0cd8b6-3f07-11e8-86a7-1b3e80ca9caa.png)
5. Go on the duplicate contact and see that tag DNC is displayed
![image](https://user-images.githubusercontent.com/31535432/38725416-8ef795cc-3f07-11e8-9b1e-6d0cfc7835cf.png)
6. Display contact preferences and see that email is checked
![image](https://user-images.githubusercontent.com/31535432/38725446-a3d9e01c-3f07-11e8-9ee3-98a5d5afcac0.png)

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
The **Do Not Contact** label is probably checking in the DNC tables if a same **email address** is existing. But it should be looking at the `lead_id`.

**Comment by npracht** [comment]
Label: Bug

**Comment by kuzmany** [comment]
Lets test https://github.com/mautic/mautic/pull/6297
