### ISSUE TITLE
issue with with shorter tag

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5950]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
It is not possible to create a shorter tag.
Example: i created the tag `thisisatest`
I cannot create a shorter tag from this one like `thisis`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Create a contact and create the tag `thisisatest`
![image](https://user-images.githubusercontent.com/31535432/38726238-e4abf182-3f09-11e8-8818-8ccae4f04b27.png)
![image](https://user-images.githubusercontent.com/31535432/38726250-eab86ff6-3f09-11e8-88a4-4c7d9b9731b3.png)
2. Save and close and create a new contact
3. Try to create the tag `thisis`
![image](https://user-images.githubusercontent.com/31535432/38726309-1590106c-3f0a-11e8-9487-79afcb79f9f5.png)
If you press enter it will add the existing tag. It is not possible to create the shorter one.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by RCheesley** [comment]
Unable to replicate so closing this issue.
