### ISSUE TITLE
Search by email

### ISSUE THREAD

**Issue by adrianoGaspar** [mautic/mautic#5953]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

I get a single user using his id. This is ok.
$ this -> _ contactApi-> get(id)
If I want to receive the contact through your email I use
$ this -> _ contactApi-> getList ("email: email@gmail.com"); OK
But in this case I get an array with a list and the contact is unique. In this case I have to make a foreach even having a single result.
My question is: can I do an email search and return a single contact instead of an array?

**Comment by npracht** [comment]
Label: Enhancement

**Comment by npracht** [comment]
Label: Pending Feedback
