### ISSUE TITLE
"Mailer is Owner" overrides "Send eMail as..." = Counterintuitive

### ISSUE THREAD

**Issue by dscotese** [mautic/mautic#5954]
I'd call this a 
| Bug report? | 

## Description: (You can tell from our conversation, between me ("2719" and "n"):
2719: Contact Owner is known, so it's forcing the use of your info as the sender...
2719: which is gmail.com.
2719: Let;s try it with that setting off.
n: Where do you see that?
2719: Configuration email settings, "Mailer is owner"
2719: I just changed it to NO and selected Apply. It's ready to test.
n: Configuration settings in Mautic?
2719: Yes. https://mautic.libertopia.org/s/config/edit
2719: But then you have to select Email Settings.
n: That's really frustrating if that's the issue.  If you look in the advanced settings of the email editor, I have the sending email as webmaster@libertopia.org, which SHOULD override the owner setting and DOES when you send an 'example email'.

## If a bug:

| v2.12.2 | 
| I can't tell the PHP version | 

### Steps to reproduce:
1. Send an email as an existing contact with the "Mailer is Owner" setting ON and with a setting in "Send email as."
2. Note that the email does NOT come from the setting you specified in "Send email as"
 
### Log errors: 
mautic.ERROR: [MAIL ERROR] { "errors": [ { "message": "Invalid domain", "description": "Unconfigured Sending Domain  ", "code": "7001" } ] } Log data: !! { "errors": [ { "message": "Invalid domain", "description": "Unconfigured Sending Domain  ", "code": "7001" } ] } (code: 0) (send); **[email addresses]**

**Comment by npracht** [comment]
I close this one on favor of https://github.com/mautic/mautic/issues/6425 which is clearer to understand IMO.
