### ISSUE TITLE
Mautic Listing Themes on Form Editing without Form Theme Support causing Error 500

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#5959]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.0.26

### Steps to reproduce:
1. Create an Form
2. Choose a Theme (Whitout Form Support)
 
### Log errors: 

[2018-04-16 14:21:10] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The template ":fresh-center:form.html.php" does not exist." at /var/www/html/app/cache/prod/classes.php line 464 {"exception":"[object] (InvalidArgumentException(code: 0): The template \":fresh-center:form.html.php\" does not exist. at /var/www/html/app/cache/prod/classes.php:464)"} []

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
The themes without form feature should not appear in the theme list when creating a form.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
