### ISSUE TITLE
Form or lead fields with SQL protected words or numbers as the column name fail

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#596]
**Description**
Using SQL protected words or numbers as a field name results in bad queries that cause either form creation to fail or form submissions to fail. 

**How to duplicate**
Create a form with fields names like select, count or just a number and save.  The select and count will save and the columns created.  But when you go to post the form, a SQL error will occur.

For fields with numbers as the name, the form will fail to create the column.

Maybe the columns created in the tables should be prefaced with something to prevent these types of issues since it seems that Doctrine does not auto-quote column names.

**Comment by drmmr763** [comment]
Perhaps a simple way to do this is to force the use of the prefix. Joomla does this with an auto-random generated prefix.
