### ISSUE TITLE
Mutic 2.13.0 - 500 error on form submit

### ISSUE THREAD

**Issue by kurkowskik** [mautic/mautic#5960]
When submit form with new company name and existing contact email there is 500 error.
Second submission of the form (with the same data) works.

Mautic version - 2.1.2
PHP version: 7.1.16-1

### Steps to reproduce:
1. Create new form (Components -> Forms -> New -> Standalone form)
2. Add required Text Field CompanyName assigned to Contact Field: Company > Company Name
2. Add required Text Field Email assigned to Contact Field: Contact > Email
3. Save
4. Choose "Preview"
5. Enter CompanyName  (new one - company with that name don't exists), enter Email (of contact which exists)
6. Submit
7. "Failed to load resource: the server responded with a status of 500 (Internal Server Error)"
 
### Log errors: 

[2018-04-17 10:12:28] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\InvalidPropertyPathException: "The property path should not be empty." at /var/www/mautic/vendor/symfony/property-access/PropertyPath.php line 91 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\InvalidPropertyPathException(code: 0): The property path should not be empty. at /var/www/mautic/vendor/symfony/property-access/PropertyPath.php:91)"} []

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Hey @dbhurley, how do we manage issues from such old version?
@kurkowskik i would recommend that you update some time your mautic. You know the running version is 2.13.0 and since 2.1.2 there are many new features, bug fixes, tests included, etc.

**Comment by kurkowskik** [comment]
@npracht upgraded to 2.13.0, same error:

[2018-04-19 13:44:24] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\InvalidPropertyPathException: "The property path should not be empty." at /var/www/mautic/vendor/symfony/property-access/PropertyPath.php line 89 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\InvalidPropertyPathException(code: 0): The property path should not be empty. at /var/www/mautic/vendor/symfony/property-access/PropertyPath.php:89)"} []

**Comment by BioSehnsucht** [comment]
We may have a similar issue, not sure if it is actually related or just has similar symptoms. It just started occurring today.

In our case, when logged in as Mautic user, either (but not both) "Page URL" and "Public Preview URL" can be loaded and form submitted once, and afterwards further submission attempts on either URL for that user will give the Mautic error 500 page.

However, we can submit to both URLs any number of times when using incognito mode to ensure we're not logged into Mautic (so possibly, the URLs will work fine when we email them out).

Others who have this issue, did you test when logged out or incognito mode whether the problem persisted ?

**Comment by fionndaly** [comment]
Has anyone found a solution to this? 

Having the same issue when the form is placed on a public page. I've tried the form in automatic JS, and Manual modes with the

**Comment by mauwiks** [comment]
Same here!

**Comment by corycast** [comment]
Is there any update on this bug?  We are experiencing the same issue but now its not even sending us to the 

![system log error](https://user-images.githubusercontent.com/40242903/57236530-47920a00-6ff3-11e9-962a-a377ec7e2424.PNG)

![cast form error](https://user-images.githubusercontent.com/40242903/57236564-62fd1500-6ff3-11e9-90bb-d01f343d3805.PNG)

**Comment by gio00** [comment]
Had same problem. Reinstalled the version 2.15.2-beta by cloning the repo, `composer install`, and it's now working.

**Comment by RCheesley** [comment]
I'm going to close this down due to lack of recent updates, however if there is still a problem please request to re-open the issue.
