### ISSUE TITLE
Contact in CC does not get form results with SendGrid, Sparkpost & SMTP transport

### ISSUE THREAD

**Issue by jonasstinkens** [mautic/mautic#5967]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When sending a form result, there is the option to send this to multiple contacts in CC, seperated by a comma. But the results aren't sent to the email addresses after the comma (tried it with and without a space between the comma and email address).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.12.2
| PHP version | 7.0.28-1~dotdeb+8.1

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by npracht** [comment]
Hello @jonasstinkens i've just tested to reproduce in 2.12. and it is working as expected. I cannot reproduce the bug.

### Form config
![capture d ecran 2018-04-19 a 08 54 33](https://user-images.githubusercontent.com/14075239/38975833-9fed1080-43af-11e8-9130-e0650a14f922.png)
### Email in my mailbox
![capture d ecran 2018-04-19 a 08 56 06](https://user-images.githubusercontent.com/14075239/38975834-a0065946-43af-11e8-9b12-14b597c2d675.png)

**Comment by fphunzz** [comment]
Got the same Bug also on the BCC or even "To" with multiple emails, some settings I'm using: 

Send Immediately
Email sender: Sendgrid API
Emails separated by comma
Custom template (template working fine)

Looking at some source-code I've found out sending to multiple "To" isn't processed by code, but the Mautic UI shows its possible to. Is that correct? Need me to point out the file?

**Comment by escopecz** [comment]
What email transport do you use? Each handles this differently.

**Comment by fphunzz** [comment]
Send form result with Sendgrid API. Delivery set to Send Immediately.

**Comment by jonasstinkens** [comment]
Same here, also Sendgrid.

**Comment by npracht** [comment]
Same issue with Sparkpost as mentioned in #7662

**Comment by enableit** [comment]
Please can the description be updated to remove the reference to the email transport? This affects normal SMTP transport too.

**Comment by RCheesley** [comment]
@enableit your wish is my command 🧙

**Comment by enableit** [comment]
> @enableit your wish is my command 🧙

Haha thanks, but given there are now three transports affected I'd hazard the transport is not particularly relevant :)

**Comment by RCheesley** [comment]
Maybe not! Side note, I mentioned you in a SugarCRM issue we need a second test on to merge for 2.16.1 - could you take a look at your notifications please :)

**Comment by enableit** [comment]
Hello,

Do we have any update on this current issue?

- Nord

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi, I am also having the same issue.

Step to Produce the issue:-

- Email sender:- Sendgrid API
- Create a standalone form and add emails like 

![image](https://user-images.githubusercontent.com/44962124/80449595-31383900-893d-11ea-9875-ec27a726b106.png)

- Then publish the form and submit the form with test data.
- Then I am getting form result in test@01.com,test@02.com and test@03.com
- but no mails for test@04.com 
- And for test@05.com, The mail looks like this 

![image](https://user-images.githubusercontent.com/44962124/80449552-0d74f300-893d-11ea-99d6-8eb0a16444c4.png)

So **Issue**:

1.  I am not getting email with comma separated in CC.
2.  I am getting emails but not the form result for emails in BCC.

Please let me known if Any one have any solution.

**Comment by fphunzz** [comment]
This issue is being fixed by #8768 ?

**Comment by escopecz** [comment]
Might be. Can someone test it?

**Comment by ayusopatricia** [comment]
Hello! Maybe this is related or not.

**Q** | **A**
-- | --
Mautic version | v2.12.1
PHP version | 7.0.33-0ubuntu0.16.04.15
Email provider | Sengrid

We have a "birthday" campaign since May that has a BCC. 
It was working great and, from last week, the BCC stopped working. 
I can see that it didn't arrive at Sendgrid and there are no errors in Mautic's log.

**BCC**
![image](https://user-images.githubusercontent.com/4871789/90540503-4dabeb80-e14f-11ea-8358-4078e9edeca3.png)

**Last time delivered (Sengrid)**
![image](https://user-images.githubusercontent.com/4871789/90540630-78963f80-e14f-11ea-9677-05aac3627efc.png)

**Comment by RCheesley** [comment]
Hi folks, can we check if this persists in the current 3.x release please?
