### ISSUE TITLE
Push contact to salesforce integration setup window doesn't mark campaign member status field required

### ISSUE THREAD

**Issue by Gregy** [mautic/mautic#5968]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | n
| Enhancement? | 

## Description:
Push contact to salesforce integration setup window doesn't mark campaign member status field required even when it is and the action doesn't work correctly without it.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13
| PHP version | 7.1

### Steps to reproduce:
1. Setup sf integration
2. Try to configure mautic campaign with push to sf campaign action
3. select only campaign and not the member status field
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
