### ISSUE TITLE
[Bug] Symfony Master/Slave support is broken

### ISSUE THREAD

**Issue by heathdutton** [mautic/mautic#5969]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
2 Databases are better than one!

Symfony2 supports MasterSlaveConnection out of the box, but trying to use it in production with Mautic I found that the slave was NEVER getting any love...

Turns out the invocation of createSchemaConfig causes an unnecessary `query` (when MasterSlaveConnection is in use) to discern the `dbname`. When that occurs, DBAL chains the poor session to the `master` db instance. The slave is never allowed to be free, and to produce valuable queries. Sad.

In our case it's pretty simple to avoid that query by providing the `dbname` from the master and avoiding the problematic createSchemaConfig method.  :)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.0
| PHP version | 7.1

### Steps to reproduce:
1. Try using master/slave DB connections and watch the slave query/connection count never go above 1. There are no errors. The slave is never connected to, even though it shows up within parameters and as a dbal connection option.

Example:
![A dead slave](https://i.imgur.com/biTuuIH.png)

PR Incoming.

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Label: WIP

**Comment by alanhartless** [comment]
Seems this was merged in 2.15.0
