### ISSUE TITLE
Add option to filter a leads based report by lead list

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#597]
Right now there is no way to export leads based on lists.  If reports could be filtered based on list membership, I think this issue would be resolved.

Or come up with an export option directly from the leads list.

**Comment by ankitpr89** [comment]
Important feature for doing operations on lead.

**Comment by escopecz** [comment]
+ filter by tags

**Comment by wderuijter** [comment]
Both reporting on lead list as well as tags would be awesome!

**Comment by 750430** [comment]
+1 from me please!

**Comment by jderuette** [comment]
Hi,

We are currently working on this feature.

**Goals :** 
- export lead with current filter/ordering
- export lead list.

**How :**
Adding a buttton on the lead view to export current view in CSV.

Sample : 
A- To export a list : 
1. In menu click on "manage list"
2. Click on a lis click in celle "view _x_ lead"
3. Click on export as CSV

B- to export all leads by points from company "Webmecanik"
1. In menu go to "Manage leads"
2. Click on the table header "Points" to order the table
3. In the "search" box, type "company:Webmecanik"
4. Click on export as CSV


Take a look about dev environnement
![ihm_export_leads](https://cloud.githubusercontent.com/assets/14073284/14177799/45eeffd0-f758-11e5-8258-591b5b1b4915.JPG)
![ihm_export_leads_when_clicked](https://cloud.githubusercontent.com/assets/14073284/14177798/45ec3048-f758-11e5-9b6c-dc69a2863749.JPG)

**Have you some FeedBack ?**

**Comment by npracht** [comment]
Hi,

I'd better add the button "export" close to the button "import" on the line above.

Great job :)

**Comment by dantearaujo** [comment]
Any news on this feature?

**Comment by wheresmylunch** [comment]
This would be really useful - any update?

**Comment by alanhartless** [comment]
Option was added in 2.0 to filter contacts by segment in reports.
