### ISSUE TITLE
API contact batch create route (POST /contacts/batch/new) ignore contact tags

### ISSUE THREAD

**Issue by davidbnk** [mautic/mautic#5971]
What type of report is this:
Bug report

## Description:
If you pass tags on a contact to the route `POST /contacts/batch/new` the tags get ignored and the contact is created without tags. If you create a single contact instead, using the route `POST /contacts/new`, the tags are correctly created.

## Version
Mautic version: v2.10.1
PHP version: 7.0.23

### Steps to reproduce:
1. `POST /contacts/batch/new`
```
[{
  "firstname": "John",
  "lastname": "Doe",
  "email": "johndoe1@mail.com",
  "tags": ["Tag1"]
}]
```

See that the contact is created without tags.

2. `POST /contacts/new`
```
{
  "firstname": "John",
  "lastname": "Doe",
  "email": "johndoe2@mail.com",
  "tags": ["Tag1"]
}
```

Now this contact is created with tag

**Comment by npracht** [comment]
Label: Bug

**Comment by escopecz** [comment]
This is working in 2.13.1 and it's also covered by a [functional test](https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Tests/Controller/Api/LeadApiControllerFunctionalTest.php#L69) so closing this issue.
