### ISSUE TITLE
Clicking SysInfo throws 500 after upgrade to 2.13.0

### ISSUE THREAD

**Issue by namankumar** [mautic/mautic#5973]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x |
| Feature request? | |
| Enhancement? | |

## Description:
Hitting https://www.xxxxx.com/s/sysinfo gives the 500 mautic bot "uh oh i think i broke it" error. This has only started happening after upgrading to 2.13.0

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.0
| PHP version | 7.0

### Steps to reproduce:
1. Login to Dashboard. 
2. Click wheel at the top right.
3. Click "System Info"

### Log errors: 

`[2018-04-18 18:34:17] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Malformed UTF-8 characters, possibly incorrectly encoded" at /var/app/current/vendor/symfony/http-foundation/JsonResponse.php line 163 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/app/current/vendor/symfony/http-foundation/JsonResponse.php:163)"} []
`

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Label: P1

**Comment by sambarnes90** [comment]
I got this to work by looking at line 85 in JsonResponse.php

```$pattern = '/^[$_\p{L}][$_\p{L}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\x{200C}\x{200D}]*(?:\[(?:"(?:\\\.|[^"\\\])*"|\'(?:\\\.|[^\'\\\])*\'|\d+)\])*?$/u';```

I don't even know PHP, but working in Sublimetext told me there was clearly an issue somewhere with a tag being closed incorrectly / not being closed at all.

Then I just looked for any rogue `'` characters and found the `'\\\` towards the end of the line.

Removing one `\` from that sequence of three made it work again?

Don't know if that's a Mautic issue or not but there's a comment just above it so I'm guessing it's been changed at some point?

**Comment by namankumar** [comment]
@sambarnes90 good call. Going directly to the url works just fine.

**Comment by brandner** [comment]
Seeing the same issue. Reloading at that URL works, but clicking the link fails.

[2018-05-08 13:44:13] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Malformed UTF-8 characters, possibly incorrectly encoded" at /var/www/clients/client0/web2/web/vendor/symfony/http-foundation/JsonResponse.php line 163 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/clients/client0/web2/web/vendor/symfony/http-foundation/JsonResponse.php:163)"} []

**Comment by reetakoshik** [comment]
I am also facing this problem many time 
[2018-09-26 20:20:17] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Malformed UTF-8 characters, possibly incorrectly encoded" at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php line 164 {"exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /var/www/html/vendor/symfony/http-foundation/JsonResponse.php:164)"} []

But if I do ctrl+R in browser - dashboard will be loaded. I think that did wrong shortening words for widget. From cache.

Is this a Bug or It is resolved?

**Comment by mundadashri** [comment]
Same issue for me in v2.15.3
It is critical now as I am not able to send emails. It just shows pending.

**Comment by martinstr** [comment]
Same issue here too on v2.15.3

**Comment by kamikazebr** [comment]
Same 2.15.1, i just change language from email and broke.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
