### ISSUE TITLE
issue when segments are excluding each others

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5975]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is an issue when 2 segments are excluding each others.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Create 2 segments : A and B
2. Add filters : 
   Segment A excluding Segment B
   Segment B excluding Segment A
3. Run `php app/console mautic:segments:update`
4. See the errors
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /Users/johanbuchert/Sites/2.12.2-beta/app/bundles/LeadBundle/Entity/LeadListRepository.php on line 663

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /Users/johanbuchert/Sites/2.12.2-beta/app/bundles/LeadBundle/Entity/LeadListRepository.php on line 663
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

```
Remove limit memory size and run the CRON again.
It never ends.

So if there are others next (after the one that failed) to be updated, they won't be.
It could be nice maybe to have a message or something when creating segment that says it is not valid.
Or maybe that the cron stop for this segment but keep running for the next segments.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Solved with segment refactoring
