### ISSUE TITLE
Spool folder gets too big

### ISSUE THREAD

**Issue by davidbnk** [mautic/mautic#5981]
Don't know if this is intended behaviour or not, but I just tried to send an email to 400k+ contacts and my template file is about 300KB. The process is really slow and more than 24h later I found out that my disk was full, because mautic created a copy of the html template for each contact, resulting in more than 70gb of disk used. Am I doing something wrong or is this expected?

**Comment by npracht** [comment]
Hello,

No this is the way it is working. I have no recommendation about it. @dbhurley anything else or we can close ?

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by davidbnk** [comment]
Thank you for the response. We have reduced the size of our html template and now the folder size is more manageable.
