### ISSUE TITLE
Option to do not execute some campaigns on m:c:t

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#5986]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | Y

## Description:

Mautic has an option to use m:c:t -i to run one campaign ... this is great to run near real time opt-in campaigns .. but sometimes we have to execute bigger campaings on midnight and mautic do not have an option to exclude an campaign from regular cron schedule 

I Hope passing negative values Will be great 

### regular campaigns trigger (ALL campaigns every 15 minutes )
`*/15 * * * * m:c:t`

### opt-in only campaign (eg campaign id 23)
`* * * * * m:c:t --i 23`

### run bigger campaigns with ALL leads 
`1 1 * * * m:c:t --i 12`

on example above I can run campaigns on specific schedule but the bigger campaign cannot be removed from regular cron schedule 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by luizeof** [comment]
@dbhurley this is a simple feature but help a lot scale Mautic With Docker

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.

**Comment by namratasaun** [comment]
Hello, I also want this feature, I tend to schedule bigger campaigns during night, so I can use

php /var/www/html/mautic/bin/console mautic:campaigns:trigger --campaign-id=291

but in

php /var/www/html/mautic/bin/console mautic:campaigns:trigger

all campaigns are triggered including the big campaign which doesn't allow the other campaigns to run on time.
Is there an open issue regarding this on forum or slack as I wasn't able to find it @npracht  @luizeof  ?

**Comment by badcrc** [comment]
Is it commented it on the forums/slack? I was in need of this feature and have made the changes locally and would love to make a PR but I'm new to mautic.

The change is easy in `app/bundles/CampaignBundle/Command/TriggerCampaignCommand.php` for anyone interested.
