### ISSUE TITLE
S3 pre-signed URLS

### ISSUE THREAD

**Issue by calevans** [mautic/mautic#5987]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Feature request? | 

## Description:
It would be nice if the S3 plugin supported pre-signed URLs. Ideally I should be able to:

1: Create an asset with a remote url whose permissions are locked to owner only. 
2: Add a "Download" button to a landing page or email that is attached to the assett
3: When the user clicks the button, it then creates a pre-signed URL good for 2-10 seconds. 
4: Mautic uses readfile() to pass the file through Mautic to the user's browser thus never exposing the url of the original assett.

Cheers! :)
=C=

**Comment by npracht** [comment]
Label: Enhancement

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
