### ISSUE TITLE
Form problems after upgrading

### ISSUE THREAD

**Issue by wwhbtp** [mautic/mautic#5989]
Hi All,

So i had a nice unsubscribe form, and a campaign what checks if the user is real.
Today i upgraded the mautic version to 2.13. (previously i was using 2.12.1). Since the upgrade if someone submit on unsubscribe form nothing happens. (simply generate a contact into my All Contacts segment.) I'd say that the problem is with Standalone form because i added an action to it: It should modify the segment of the contact to unsubscribe segment. It does not happen so my campaign not able to recognize the related contacts.
The intresting part that the first contact who uses unsubscribe form will be handled correctly and in all the other cases nothing happens.
So i rollback the upgrade and the previous one was working fine. I put back the newest version again and same happened: The first contact could unsubscribe correctly but nothing happens with the others…

Please be so kind and check this issue.

**Comment by npracht** [comment]
Hello @wwhbtp !
To better understand could you please use the form when you create an issue ?

> ## Description:
> The more details the better...
> 
> ## If a bug:
> 
> | Q   | A
> | --- | ---
> | Mautic version | 
> | PHP version | 
> 
> ### Steps to reproduce:
> 1. 
> 2.

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by wwhbtp** [comment]
What type of report is this?

Q | A
-- | --
Bug report? | y
Feature request? |  
Enhancement?



# Description:

Hi All,

So i had a nice unsubscribe form, and a campaign what checks if the user is real.
Today i upgraded the mautic version to 2.13. (previously i was using 2.12.1). Since the upgrade if someone submit on unsubscribe form nothing happens. (simply generate a contact into my All Contacts segment.) I'd say that the problem is with Standalone form because i added an action to it: It should modify the segment of the contact to unsubscribe segment. It does not happen so my campaign not able to recognize the related contacts.
The intresting part that the first contact who uses unsubscribe form will be handled correctly and in all the other cases nothing happens.
So i rollback the upgrade and the previous one was working fine. I put back the newest version again and same happened: The first contact could unsubscribe correctly but nothing happens with the others…

Please be so kind and check this issue.


Q | A
-- | --
Mautic version |  2.13
PHP version | 7.0.28



Previous mautic version: 2.12.1

# Step to reproduce:
1.) Upgrade mautic form 2.12.1 to 2.13 version
2.) Create a Standalone form with an action (modify contact's segment)
3.) Create a landing page to te form (where contact can unsubscribe)
4.) Make a submission in the page

**Comment by wwhbtp** [comment]
Sry i closed this one accidentaly. It was reopened as #6031
