### ISSUE TITLE
email sending issue

### ISSUE THREAD

**Issue by charleshugo** [mautic/mautic#5991]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
when I 
1. log into my account
2. settings --> configuration --> email settings --> mail send settings (I set the gmail as SMTP with my own username and password of a specific gmail account)
3. Test connecting, success. Send test email, received in my email associated with my account
4. enter Contacts --> a specific contact, send email, failed. error msg: Failed to send to xxxx@gmail.com: Connection could not be established with host smtp.gmail.com [ #0]

I have changed the SMTP to another provider, office 365 SMTP provided by godaddy, and I encountered the same issue.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Configuration issue, see on your server rights side please.
