### ISSUE TITLE
issue when usin group by email in reports

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#5997]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is an issue if you create a report and use the group by function to group by contact's email.
If the reports contains a lots if lines, it won't display and the log indicates a probleme due to memory size.
Why the reports won't display, it is because the report will try to display all lines directly. It will ignore the selector of number of lines. 
Usually it is only the first 30 lines that are displayed. By adding the group by, it will display all lines directly. 
So if the reports contains lots of line, then it won't display.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Create a report and choose emails sent. (It must be a report with a lots of line, I think at leat 10 000)
2. Add some columns and group by emails
![image](https://user-images.githubusercontent.com/31535432/39190638-48eb6424-47d5-11e8-89c6-05b314940588.png)
3. Save and close.
4. Check if you can display the reports. If so, check that all the lines are displayed directly.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by escopecz** [comment]
Cannot replicate. Isn't it caused by another report configuration?

**Comment by johbuch** [comment]
i just tested again.
I choose email sent as data source.
column i added: ID, firstname, lastname, contact email, company name
group by: contact email
save and close
report displays directly all the lines.
![image](https://user-images.githubusercontent.com/31535432/41044612-ecd1bfa0-69a6-11e8-8302-2ff539d17d33.png)

**Comment by npracht** [comment]
@johbuch is that now fixed ?

**Comment by npracht** [comment]
@escopecz maybe https://github.com/mautic/mautic/pull/7085 fixed it ?

**Comment by escopecz** [comment]
Probably not. I was fixing an SQL error.

**Comment by npracht** [comment]
We cannot reproduce ;)
