### ISSUE TITLE
mtc.js error after last update

### ISSUE THREAD

**Issue by rraulinio** [mautic/mautic#5998]
I just updated the platform to the latest version and mtc.js is not functional anymore, as it gets error 500 on it. First, I cleared all cache and database statistics and it started working again. Now, three hours later, it is not working again. The only thing happening that is implying mtc.js is it being called on a website, for tracking, that's all, nothing else. Is this issue related to the latest update? Of course, the Mautic platform is working fine, everything as expected. Looking forward for your answer!

**CONSOLE where mtc.js is called**
GET https://*website*/mtc.js net::ERR_ABORTED
Refused to execute script from 'https://*website*/mtc.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**SCREENSHOT of https://*website*/mtc.js opened in browser**
![internal server error](https://user-images.githubusercontent.com/3612132/39201250-5acfc9c6-47e6-11e8-9b0b-98667c204038.png)

**Comment by malitov** [comment]
I have a similar error (500 internal server error), when I added new contact

**Comment by sawanCD** [comment]
Had the same issue, 
Running 

> php app/console doctrine:migrations:migrate


solved this for me

**Comment by rraulinio** [comment]
`root@application:/usr/local/docker/mautic/data/mautic# php app/console doctrine:migrations:migrate
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Mautic\LeadBundle\Model\FieldModel::__construct() must be an instance of Mautic\CoreBundle\Doctrine\Helper\IndexSchemaHelper, instance of Mautic\CoreBundle\Doctrine\Helper\SchemaHelperFactory given, called in /var/www/html/app/cache/prod/appProdProjectContainer.php on line 11839 in /usr/local/docker/mautic/data/mautic/app/bundles/LeadBundle/Model/FieldModel.php:286
Stack trace:
#0 /var/www/html/app/cache/prod/appProdProjectContainer.php(11839): Mautic\LeadBundle\Model\FieldModel->__construct(Object(Mautic\CoreBundle\Doctrine\Helper\SchemaHelperFactory))
#1 /usr/local/docker/mautic/data/mautic/vendor/symfony/dependency-injection/Container.php(297): appProdProjectContainer->getMautic_Lead_Model_FieldService()
#2 /var/www/html/app/cache/prod/appProdProjectContainer.php(13310): Symfony\Component\DependencyInjection\Container->get('mautic.lead.mod...')
#3 /usr/local/docker/mautic/data/mautic/vendor/symfony/dependency-i in /usr/local/docker/mautic/data/mautic/app/bundles/LeadBundle/Model/FieldModel.php on line 286
`

**Comment by sawanCD** [comment]
How did you update?
Try running these commands and then migrate
> php app/console cache:clear
> php app/console mautic:update:find
> php app/console mautic:update:apply (Follow the prompts)
> php app/console cache:warmup

**Comment by rraulinio** [comment]
Getting the same Fatal Error even on cache:clear, that is strange. I will get a backup from before the update and then try with the above commands, I will edit this post after I manage to solve it, thanks a lot!

**Comment by rraulinio** [comment]
root@application:/usr/local/docker/mautic/data/mautic# php app/console mautic:update:apply
Are you sure you wish to update Mautic to the latest version? y
Step    1 [->--------------------------] Loading update information...          Step    2 [-->-------------------------] Downloading update package...          Step    3 [--->------------------------] Validating update package...                  PHP Notice:  Use of undefined constant PHPEXCEL_ROOT - assumed 'PHPEXCEL_ROOT' in /usr/local/docker/mautic/data/mautic/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php on line 31
PHP Warning:  require_once(PHPEXCEL_ROOTPHPExcel/Shared/PCLZip/pclzip.lib.php): failed to open stream: No such file or directory in /usr/local/docker/mautic/data/mautic/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php on line 31
PHP Fatal error:  require_once(): Failed opening required 'PHPEXCEL_ROOTPHPExcel/Shared/PCLZip/pclzip.lib.php' (include_path='.:/usr/share/php') in /usr/local/docker/mautic/data/mautic/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php on line 31

                                                                               
  [Symfony\Component\Debug\Exception\FatalErrorException]                      
  Compile Error: require_once(): Failed opening required 'PHPEXCEL_ROOTPHPExc  
  el/Shared/PCLZip/pclzip.lib.php' (include_path='.:/usr/share/php')

**Comment by rraulinio** [comment]
I mention that I've put the backup from before the update, that means from 23rd of April, and tried what @sawanCD said, that is the result. Zip extension for PHP 7.1.5 is installed as well.

**Comment by mfvetter** [comment]
Are your folders writable by the Apache user? 
Did you clear the cache like below?

> `php app/console cache:clear --no-warmup`

Every time I upgrade Mautic via command line, I have to clear the caches. Sometimes I restart Apache or PHP FPM in my case. 

If people are accessing your mtc.js file while clearing the cache, sometimes I have to disable the Vhost in Apache (and reload Apache) so no one will call the mtc.js file while upgrading Mautic. 

Then I restart PHP FPM (in my case), clear the cache without warming up, enable the vhost and try again. It's always a hassle.

I had a similar issue like yours when upgrading from 2.12 to 2.13.1. But mine seems to be working fine now.

**Comment by ricardovf** [comment]
```
php app/console doctrine:migrations:migrate
php app/console cache:clear --no-warmup
```

Fixed here!
