### ISSUE TITLE
Mautic Stopped Working after update

### ISSUE THREAD

**Issue by sudo-shubham** [mautic/mautic#6003]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | -
| Enhancement? | -

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.0
| PHP version | 7.0.28

### Steps to reproduce:
1. Update to 2.13.0 from Update button in top navigation bar
 
### Log errors: 

[2018-04-25 11:58:03] mautic.NOTICE: InvalidArgumentException: The target directory "web" does not exist. (uncaught exception)

**Comment by rraulinio** [comment]
Yep, as I got some problems as well after I've updated with that button press, I would suggest to put a backup online, from before the update, and then try what @sawanCD said [here](https://github.com/mautic/mautic/issues/5998), in his last comment.
