### ISSUE TITLE
Bitrix24 integration

### ISSUE THREAD

**Issue by helbertqueiroz** [mautic/mautic#6006]
Has anyone done integrate Mautic with Bitrix24?
I need a two-way integration solution for passing leads between the two tools.

Can someone help me?

**Comment by npracht** [comment]
Hello @helbertqueiroz ! The feature requests and integration requests must be addressed on the mautic forum. You can also ask on #marketplace channel of Slack.
By the way you can contact me in PM on slack, i can maybe help you on that point.

**Comment by npracht** [comment]
Label: Feature request

**Comment by helbertqueiroz** [comment]
Hello @npracht have you the address for the Mautic Slack?

**Comment by dbhurley** [comment]
https://mautic.slack.com (or signup here: https://www.mautic.org/slack)

**Comment by helbertqueiroz** [comment]
Thanks @dbhurley
