### ISSUE TITLE
Trackable URL in emails breaking dynamic fields in href links

### ISSUE THREAD

**Issue by mfvetter** [mautic/mautic#6011]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When Tracking URLs are enabled and I try to create a link with a dynamic field in it, the trackable URL doesn't render dynamic fields like this `{formfield=name}` properly inside HTML A tags.

If I disable the trackable links in `Configuration > Email Settings > Disable trackable links > Yes`, then the dynamic content in an HREF link works. 

**Example WITHOUT trackable links enabled:**
`<a href="https://example.com/?name={formfield=name}">{formfield=name}</a>`
Converts to:
`<a href="https://example.com/?name=John">John</a>` 😀 

**Example WITH trackable links enabled:**
`<a href="https://example.com/?name={formfield=name}">{formfield=name}</a>`
Converts to:
`<a href="https://example.com/?name=%7Bformfield=name%7D">John</a>` 😞 

The issue might be in this file:

> `/app/bundles/EmailBundle/EventListener/BuilderSubscriber.php`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.1.16

This might be related to this issue as well: #3825

**Comment by npracht** [comment]
Label: Bug

**Comment by vincnetas** [comment]
Can confirm this bug in 2.15.0 . This also happens with emails. When email has a link with placeholders:

https://www.surveymonkey.com/r/Y5P2KH8?user={contactfield=externalid}&reason=2&email={contactfield=email}

If tracking is enabled (Configuration > Email Settings > Disable trackable links > No)

After clicking link, redirect (tracks click) and redirects to URL with not replaced placeholders.
Ir tracking is disabled email contains URL with replaced placeholders, but tracking functionality is lost.

I assume this happens when creating tracking links. Target URL's are used without first replacing placeholders.

**Comment by npracht** [comment]
Hi guys, i just tested it but i cannot reproduce... I used: `https://google.com?{contactfield=id}` and it has been properly replaced.

Can you share the shortest piece of HTML of your email ? and a screenshot of the URL given (and broken) ?
Also something in your logs ?

**Comment by vincnetas** [comment]
Example from #7133 

https://www.surveymonkey.com/r/XXXXX?user={contactfield=externalid}&reason=2&email={contactfield=email}

**Comment by npracht** [comment]
and what it looks in your final email (real not test) and in your browser ?

**Comment by vincnetas** [comment]
In email link is replaced with mautic tracking URL, but that tracking URL resolves to link where all placeholders are not replaced. Same as original.

https://www.surveymonkey.com/r/XXXXX?user={contactfield=externalid}&reason=2&email={contactfield=email}

**Comment by npracht** [comment]
@johbuch can you reproduce ?

**Comment by ArtemDzhafarov** [comment]
Have the same issue

**Comment by jinugeorge7** [comment]
I am facing the same issue here

Trying to tack the URL with placeholders from campaign sent - but they are not tracked. After testing links the clicks are showing as 0.
Email template = 

Dear {contactfield=firstname},<br /><br />
How do you seize this opportunity?  With Infrascale, you get a revolutionary DR solution that can be sold for the cost of backup.<br /><br />
 <br /><br />
  <a href="https://try.infrascale.com/nurture-banking-case-study?email={contactfield=email}">Infrascale web link</a>
    <br /><br />
  <br /><br />
  Thanks,<br />
  James

**Comment by kuzmany** [comment]
Some of issues should fix this PR https://github.com/mautic/mautic/pull/7548

**Comment by npracht** [comment]
Please @mfvetter @vincnetas @ArtemDzhafarov @jinugeorge7 test #7548

**Comment by MattBred** [comment]
Does your guys click tracking work?

I noticed my click tracking wasn't being increased (and my contact wasn't getting the "page hit" actions). I was also experiencing this issue with the placeholders not updating correctly.

I fixed my issue with the click tracking (https://github.com/mautic/mautic/issues/7756) and that also seemed to fix my placeholder issue.

If you guys are running an nginx reverse proxy, make sure you have it setup correctly (and your site_url has an https:// prefix).

**Comment by omert37** [comment]
I am having the same issue.
It seems like this issue has dragged on for ages.
It would be great if this thing was resolved and we could have contact field tokens in links rendered before rendering the trackable links.
I think that's the problem; simple priority.
contact field tokens should be rendered BEFORE rendering the final trackable url.

**Comment by RCheesley** [comment]
@omert37 the best thing you can do to help is to test the PR #7548 one the failing test is fixed, so that we can get it merged.

**Comment by omert37** [comment]
I have already informed @npracht that this issue was resolved after I updated to 3.2.0.
You can regard this issue as closed.

**Comment by tompon** [comment]
We still have exactly this problem in 3.2.4. Just wrote @kuzmany and asked for help with it..

**Comment by omert37** [comment]
**@tompon works perfectly fine in 3.2.5**

**Comment by jos0405** [comment]
Hello @tompon, are you using special language specific characters in the link?

**Comment by tompon** [comment]
We are able to upload it by API to the email, but not to show it in the button

Email:
![image](https://user-images.githubusercontent.com/20039182/106174320-e87b0e00-6162-11eb-8a59-be00f98d834c.png)

Token: {new_password_token} in text works great, but not in the CTA button https://xxxxx.com/password-reset/?token={new_password_token}

**Comment by npracht** [comment]
@tompon can you test https://github.com/mautic/mautic/pull/7548 and confirm it solves your issue ?
