### ISSUE TITLE
UTM does not apply when using a url on a contact field

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6013]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Google UTM do not apply on URL inserted into contact field (in token within an email)
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Create a custom field (text or url)
2. Create a contact and add a url into this new field.
3. Create an email and insert the token of this new contact field
4. On the email edition, add UTM
5. Send email and click on the link that have been generated via the token.
6. See on the contact's timeline that the UTM have not been recorded.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Fixed in https://github.com/mautic/mautic/pull/6043 and merged.
