### ISSUE TITLE
Webhook Queue Mode not working correctly

### ISSUE THREAD

**Issue by rc125** [mautic/mautic#6019]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? | 

## Description:
Form webhook not working when we use the Queue Mode. The raw body is aways 
{"mautic.form_on_submit":[0]}

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 

### Steps to reproduce:
1. In Configuration > Webhook Settings set Queue Mode to "Queue Events Only"
2. In Webhooks create a webhook and check "Form Submit Event"
3. Submit a form
4. The URL set in "Webhook POST Url" recieves {"mautic.form_on_submit":[0]}
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by coffeverton** [comment]
Hi, I just got this same problem, and found the bug.

In the line 62 the file mautic/app/bundles/WebhookBundle/Entity/WebhookQueue.php, change this:
`$builder->addField('payload', Type::INTEGER);`
To this:
`$builder->addField('payload', Type::TEXT);`

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/6083

**Comment by npracht** [comment]
Fixed in https://github.com/mautic/mautic/pull/6083 and merged.
