### ISSUE TITLE
Remove reply-to option for Mautic send form results action.

### ISSUE THREAD

**Issue by sayantannag** [mautic/mautic#6020]
Previously I've configured the Mautic setup from my Linux hosting server & also set up the "**e-mail address to send mail from**" option with my server email id like "**info@companyname.com**" from the Mautic setting page. So, Now all the Mautic submission emails results coming to my email address, which I've used to set up for each Mautic forms configuration from "**Components > Form > MyForm > Actions > Send an email**" popup window & all the email coming to my email address from my setup "_info@companyname.com ID via Linux hosting server_". **Reference screenshot attached.**

Now my concern is "**How can I prevent that behavior from "Components > Form > MyForm > Actions > Send an email**" popup window, to not to display the "**reply-to**" option in email details from each submission results. Or Can I remove the static code from PHP page where the static "**reply-to**" option visible?

I just don't want the **customer email ID visible like this way to the internal representative's team**. **Only want when my internal representative team's member going to reply each email submission, it's going to my server email ID like "info@companyname.com" & the final email to the client send from the same info@companyname.com email ID, which handled by me.** I am facing this issue from previously & searching the solutions eagerly. Can you guys please share any update on this.

![mautic-issue](https://user-images.githubusercontent.com/4394075/39419273-bb334eba-4c7c-11e8-9853-b10eb060d0a9.png)

**Comment by alanhartless** [comment]
Hi!

Gmail will typically add this to any message if the from address is not the same as the server sending it. If you are managing your own mail server and have access to the email domain's DNS records, you should consider signing outgoing messages with a DKIM signature which will remove the `via...`. See https://support.google.com/mail/answer/1311182?hl=en.
