### ISSUE TITLE
Sendgrid API batch failures do not bubble up to the broadcast email UI

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#6025]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:
When using the Sendgrid API to send a broadcast email, mass failures are not bubbled up to the UI as failures. So the UI will show that only 1 per batch failed and not all within the batch. Checking the logs show that all the email addresses failed. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.1

### Steps to reproduce:
1. Choose Sendgrid API as Mautic's transport
2. Leave the API key blank
3. Send a segment email with a bunch of contacts
4. Notice the UI said all were sent except a few (1 per batch)
5. Go back to the Emails list page and notice that it still has them all as pending

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
