### ISSUE TITLE
Include visitors by default in the contact list page when filtering by a segment

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#6026]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | y 

## Description:
When creating a segment that includes visitors, the "View X Contacts" buttons in the segments list (/s/segments) includes those visitors. But if you click on the button and are taken to the contact list filtered by the segment, visitors are hidden by default making it look like numbers mismatch. The suggestion is to not auto-filter out visitors when filtering by a segment so that the total number of contacts matches the segment contact total badge.

**Comment by RCheesley** [comment]
@alanhartless was this addressed/is it still an issue?

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
