### ISSUE TITLE
Add a "filtered" badge to the email list view to see the number of contacts not included in the stats due to being DNC or have no email address

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#6027]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | y

## Description:
When viewing the email detail page (/s/emails), we have badges for "pending," "sent," "queued," "read," etc. If the email is assigned to a segment (broadcast email), pending may be a completely different number than the total number of contacts in the segment. This is because the pending count does not include contacts without an email address or who are marked as do not contact. However, it can be confusing as to why the pending is different than the segment. The suggestion is to add somewhere in the UI a count for those filtered out (not included in pending). Maybe another badge will suffice. That way one can add up "pending + filtered = segment total"

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
