### ISSUE TITLE
Counts on the broadcast results page have discrepancies (Sendgrid API)

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#6028]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:
When sending through at least Sendgrid API, the results page has wonky numbers. We know that the failed count is related #6025. But the pending count on the email was 11574 but the over said 11988 were sent, then has a fraction of 12000/11581. None of those numbers match up. 

![](http://alan.direct//drop/Image%202018-05-01%20at%208.50.58%20AM.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.1

### Steps to reproduce:
1. Send a large email through Sendgrid API (it's ok if they all fail so you don't necessarily need an API key but recognize that failures will not be counted until #6025 is fixed)
2. Notice the sent and fraction discrepancies.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
