### ISSUE TITLE
´please wait´ message after submitting a form with radio or check buttons

### ISSUE THREAD

**Issue by Rosco4Mautic** [mautic/mautic#6029]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Bug Report |

## Description:
Using mautic 2.13.1 in a subdomain with forms containing fields with radio or check-buttons occur a ´please wait´ message after submitting such form.
Forms without these field characteristic are working.

## If a bug:
| Mautic version 2.13.1 | 
| PHP version 7.0.29 and also 5.6.14 | 

### Steps to reproduce:
1.  Create a form with some fields and a field with radio or check button 
2. After submitting this form a ´please wait´ message occurs
3. Deleting the radio or check button field - the form will be submitted.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Hi @Rosco4Mautic i've noticed that if you use the form integration script on the subdomain but use the app (and save the form) on another domain, then something is broken, the form stays frozen on "Please Wait".
If you edit the form on the subdomain (just edit > save and close) and re-do the form submission, it works properly.

Something like if there is a cache/relative links or whatever that make the page not receiving from the app a correct response to finish the form submission.

Do you confirm ?

**Comment by npracht** [comment]
My advice + that fix will solve the issue: https://github.com/mautic/mautic/pull/6752

**Comment by ravinayag** [comment]
Hello,  I have encountered the same problem, and did further research on this. 
1, my setup 2.14.1  upgraded to 2.15.1,  >>>>> No luck, the form still sucks with please wait.
2, Did a fresh install with 2.15.1  >>>>>>> NO ISSUE, All GOOD. 
3, Fresh install 2.15.1, and redirect the DB to 2.14.1 >>>>>>> No luck, the form still sucks with please wait.
which puts me to further do deep dive into the issue,  thought of related to Database issue so i redirect db (2.15.1) to 2.14.1 app.  Still no luck, the issue remains.

Concluded: Fresh install of 2.15.1 works well, But my question how to migrate ...?  i,e, take all my data like segments, email templates, forms, ......... and migrate to 2.15.1. .?????
