### ISSUE TITLE
Product feed/items recommendation feature request

### ISSUE THREAD

**Issue by mbitokhov** [mautic/mautic#6030]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | y
| Enhancement? | 

## Description:
We're slowly starting to integrate Mautic with our ecommerce site. But the one feature we've used on other marketing platforms isn't available. We were wondering if there were any plans on being able to load in item data on Mautic, and if aren't, would you accept a pull request from us that implements it?

Just a general overview on the feature itself. Someone would either manually upload a csv with all of the products, or Mautic would download a csv from a url, that matches up similar to the following
```csv
product_id,category,name,brand,sku,upc,image_url,price,handle,
123456,Phone Accessories > Cases,Black case,Company,ABCDEF,123456789,https://example.com/example.jpg?ref=mautic,9.99,https://example.com/example?ref=mautic
```
It loads all of the items into the databases and can be used in page builders (like product recommendations in sales), segments (filtering by category), on the dashboard (popular items), campaigns

It seems like a really crucial feature. And my managers said I could work on making a pull request (I'm not sure how long they'll let me work on it though. Historically if a project didn't get done immediately it was abandoned). I'm just making sure a feature like this would be accepted

**Comment by npracht** [comment]
Label: Feature request

**Comment by dbhurley** [comment]
Please post in the forums Ideas channel instead of here. :) Thanks!

**Comment by eschiendorfer** [comment]
@mbkv have you worked on this?

**Comment by mbkv** [comment]
Sorry, no. We stopped using mautic a little while after this post
