### ISSUE TITLE
issue with the mapping in the zoho plugin

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6033]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is an issue with the zoho plugin.
You set the plugin, authorise app and map the fields.
Then if you add or remove fields in Zoho it won't appear on the plugin mapping.
To make it appear, you need to empty the table cache_items in the database.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Set the zoho plugin, authorized the app and map the fields.
2. Go to Zoho and create a new field (or remove a field)
3. Go back in the plugin setting and check the mapping.
4. The new field you add in zoho is not visible in the mapping. (or the one you removed is still visible).
5. Try to authorise app again and go to the mapping field. Still not the new field (or the field removed still displayed)
6. I tried reseting the plugin but still the same issue.
7. The only thing that made this works was when I deleted the zoho cache in the database table cache_items.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by RCheesley** [comment]
I am closing this as I believe it's by design (fields being cached) but if that is not the case please feel free to request a re-open!
