### ISSUE TITLE
distinguish web tracking from forms

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#6034]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | x

## Description:
When you add a form via script on you website and remove the standard tracking script, it seems that the form tracks your IP anyway even if not submitted.

I consider that as a bug because if you give the ability to the visitor to manage the cookies and disable the tracking (the script) - as requested by GDPR 🍾 - you are tracked anyway by the form on the page.

### Suggestion:
Totally remove the tracking from the script of the form assuming that it is part of the job of mtc.js.
@alanhartless & @dbhurley your opinion ?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1

### Steps to reproduce:
1. call `mauticinstance/form/generate.js?id=xx`
2. go on contacts > anonymous
3. see your contact here with your IP

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Label: Need feedback

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by kuzmany** [comment]
Form me, just form doesn't create anonymous contact until submit form. 
Form JS code doesn't generate mtc.js code.

**Comment by npracht** [comment]
Hello @kuzmany,

I could reproduce it...

1. Add the form on a page without tracking script
2. You’ll see the lead is created in anonymous without page hit
3. To test just load in your browser the form script url
4. You’ll see you’ll have a anonymous lead

**Comment by npracht** [comment]
Label: Pending feedback

**Comment by npracht** [comment]
Label: WIP
