### ISSUE TITLE
Mautic cookies not / path

### ISSUE THREAD

**Issue by shershennm** [mautic/mautic#6035]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
Mautic set cookies on current page path. If you want to make ajax request on the user first page (different from `/`), the browser will not send Mautic cookies (`mtc_id`, `mtc_sid`) with this request
I found this bug, but it was ignored #3496

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.1.16

### Steps to reproduce:
1. Go to the page different from `/` with Mautic tracking code without cookies
2. Wait until Mautic identify the user
3. Make ajax request to app backend

**Comment by npracht** [comment]
Merged in 2.15.2
