### ISSUE TITLE
Fields not Available While Creating Forms

### ISSUE THREAD

**Issue by tathspts** [mautic/mautic#6037]
I am using mautic 2.13.1 on php 7.0.

I have weird problem where I am unable to see fields while creating the forms.

I have checked for the particular field and it is set to be visible on forms.

For example I am unable to add First Name field because it does not pop up in search filed. I tried manually scrolling down, the field is simply not available to add to form.

**Comment by npracht** [comment]
Hello, which type of form field are you using ?
Le list of field available in depending on the form field type selected before.

Thanks.

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by npracht** [comment]
Also if you can better complete the issue template with steps to reproduce simply. Thanks !

**Comment by tathspts** [comment]
When You goto components --> Forms --> +New

it gives you option to create two type of forms.
1. New Campaign Form
2. New Standalone Form

Fields are not available in any type of form.

I see there is no option to select "type" of form fields while creating the form. Please check this snapshot. http://prntscr.com/jd9bem

**Comment by npracht** [comment]
Did you click on the drop down list ?
![capture d ecran 2018-05-03 a 17 16 58](https://user-images.githubusercontent.com/14075239/39585781-d1a63ccc-4ef5-11e8-9d1a-738e1f43980c.png)

**Comment by tathspts** [comment]
Hi yes, I have clicked on dropdown, and field I want to add to the form is not available.  
Check here, http://prntscr.com/jd9qzo

basically 20 out 42 custom fields are available to add. 

One other thing I noticed. I see a field named 'file' in that dropdown but I dont see that field anywhere in the custom fields.

**Comment by npracht** [comment]
Hello,

I think there is a misunderstanding here.
First you select your form input type (like Text for instance), then you set up this field to be mapped (to Firstname for instance).

Did you read https://www.mautic.org/docs/en/forms/manage_forms.html ?

**Comment by tathspts** [comment]
AH.... I feel so dumb now. Thanks a lot for your help with this.

Merci beacoupe pour Aidez-moi avec ca, mes ami :)

**Comment by npracht** [comment]
Ok cool :)
Then please close this issue :)

**Comment by npracht** [comment]
Label: Pending feedback

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by tathspts** [comment]
#
