### ISSUE TITLE
Deploy on Cloudron: Questions to finalize packaging

### ISSUE THREAD

**Issue by marbetschar** [mautic/mautic#6038]
We'd love to see an easy to deploy Mautic package for [Cloudron](https://cloudron.io). Cloudron runs it's apps within Docker containers, that said packaging Mautic for Cloudron contains basically in creating a Docker image.

However, we run into some troubles which prevents us from publishing Mautic to the Cloudron Crowd on it's One-Click-Deployment App Store: https://cloudron.io/store/index.html

**How to skip the setup form?**
After Mautic is installed, it requests information about database connection and SMTP server. Cloudron sets this information in env vars, so it can be derived automatically - and we do not need to prompt the user for this info. How to tell Mautic to skip the setup form?

**How/where to update config when needed?**
Please note, database credentials may change across container restarts - so where/how should this information be updated?

**Login via LDAP?**
Additionally, it'll be awesome to integrate Mautic with the user management of Cloudron via LDAP. How can this be achieved?

For details and further information please see the following links:
- https://forum.cloudron.io/topic/1236/mautic-marketing-automation/5
- https://staging.mautic.org/forums/topic/pregenerated-mautic-configuration/

**Comment by npracht** [comment]
Hello, maybe that discuss should happen on the Slack or Forum !

**Comment by marbetschar** [comment]
@npracht thanks for the hint. Closing this issue...
