### ISSUE TITLE
Issue with Customize Preference Center

### ISSUE THREAD

**Issue by andreiaugustin** [mautic/mautic#6039]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I have followed the Mautic documentation on how to customise the Preference Center, however when clicking on unsubscribe from the email, I get the default page.
I made sure the language is set to English on the System, the Preferebce Center landing page and as well on the Email.
The email has got the "Preference center page" select correctly.
I tested this on two different systems of which the second was fresh and still won't work.
Also when I send the email, I am using the "Send email" button from the Contact.
I also tried to click on the Unsubscribe from both Outlook and Gmail but it still won't work.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.12.0
| PHP version | 7.0.27

### Steps to reproduce:
1. Follow the Mautic's documentation on how to customize preference center (page 42).
2. Send the email with the customized preference center from the Contact.
 
### Log errors: 

No error logs on both systems I have tested.

**Comment by npracht** [comment]
Hello,

If you send the email standardly from campaign or segment email, you have the same issue or not? Because in that case i cannot reproduce. It would be it is located on the Send manually to a contact action.
If you also have an issue, then it should be more an configuration issue.

Thanks.

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by andreiaugustin** [comment]
Hello Norman,

I have tested and sending the email from a campaign and it worked fine. I
really appreciate your time to help me on this.

Thanks!

2018-05-03 11:04 GMT+01:00 Norman Pracht - Webmecanik <
notifications@github.com>:

**Comment by npracht** [comment]
# Steps to reproduce (based on last reply)
1- Create an email related to a preference center (follow documentation guide)
2- Send this email to the contact via the contact profile page (a manual email)
3- Click on unsubscribe link
**4- See default page instead of preference center**

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by spka** [comment]
Possibly same issue as #5782

**Comment by johbuch** [comment]
@andreiaugustin @npracht I reproduced it. It is the issue #5782 you must include the channel frequency bloc otherwise you will get the default pref center.
I think it is because only this bloc allows contacts to unsubscribe definitely from instances.
But in the configuration > email settings if you choose to not display frequency and pauses preference, even if you added this bloc on the builder it won't be displayed. What will be displayed is contact me through by email (contact can check or uncheck the box).

**Comment by sbolinches** [comment]
The same problem. Any solution?

**Comment by johbuch** [comment]
i am not sure it is a bug. You must add the bloc channel frequency in the pref center. If you dont add it, you will land on the default page. Because this bloc allows contacts to unsubscribe (to be tagged as Do not contact). If you don't add this bloc, you don't give the possibility to the contacts to really unsubscribed, that's why then you land on the default pref center.

**Comment by sbolinches** [comment]
Hi Johbuch

I have added the bloc channel frequency in the pref center from Preferences (Email Preferences)

My version of Mautic is 2.13.1

**Comment by yrammos** [comment]
Reproducing this bug on my end, also on 2.13.1.

**Comment by sbolinches** [comment]
Any solution?

**Comment by cStuartHardwick** [comment]
Ditto. I have all options turned on an added to landing page set as preference center and it simply is not displayed. Two hours wasted.

**Comment by npracht** [comment]
Solved by https://github.com/mautic/mautic/pull/7006

**Comment by yarimiz** [comment]
This issue is reproducing in version 3.2.0, with the exact steps you've mentioned here 

> # Steps to reproduce (based on last reply)
> 1- Create an email related to a preference center (follow documentation guide)
> 2- Send this email to the contact via the contact profile page (a manual email)
> 3- Click on unsubscribe link
> **4- See default page instead of preference center**

@npracht
