### ISSUE TITLE
Unable to delete companies and contacts in bulk via API

### ISSUE THREAD

**Issue by Flavio1998** [mautic/mautic#6040]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Although this feature is not documented, it would be a great help if it worked. As the title says, I'm unable to delete one or many companies/contacts with the bulk API request. The request I send look like this: 
`curl -H "Content-Type: application/json" -i -XDELETE admin:password@127.0.0.1/api/contacts/batch/delete -d'[{"id":533},{"id":534}]'`

The ressults I get from Mautic allways looks like this: 
```
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: c848bb80e848d99d8fc9753ebb7687d0=psosqg9susfvi03qls76294704; path=/; HttpOnly
Mautic-Version: 2.12.2
Cache-Control: no-cache
Date: Thu, 03 May 2018 07:48:35 GMT

{
    "contacts": []
}
```

It may also could be my fault, as I haven't found any documentation about this feature and just derived the usage from `api/companies/batch/new` and `api/companies/batch/edit`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.0.25-0

### Steps to reproduce:
1. Create one or multiple companies or contacts in Mautic
2. Try to delete the companies/contacts via the bulk API request
3. See how the companies/contacts don't get deleted
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by dennisameling** [comment]
Documentation added in https://github.com/mautic/developer-documentation/pull/177, changes going live today or tomorrow 👍🏼  thanks for reporting @Flavio1998
