### ISSUE TITLE
Paragraph Field in Mautic

### ISSUE THREAD

**Issue by tathspts** [mautic/mautic#6042]
Hey guys,

is there a way to add a paragraph field in Mautic forms.
Please check this image

![para](https://user-images.githubusercontent.com/22551552/39597280-e529fd3c-4ee2-11e8-88ee-85730da373e9.png)

**Comment by npracht** [comment]
Hello,

I think you would better ask this kind of questions on slack or forum.
**About your question, you can select "text area" form input type.**

**Comment by escopecz** [comment]
You can add `<p>text here</p>` in the HTML field.
