### ISSUE TITLE
form issue with sending form result with link

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6044]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I found a issue when sending the form result that contain a url field.
When receiving the email, the url field result is not the link I filled in the form but looks like a tracking link > https://myinstance.com/r/2023c38588287052fab99bc0e?ct=YTo0OntzOjY6InNvdXJjZSI7YTowOnt9czo1OiJlbWFpbCI7TjtzOjQ6InN0YXQiO047czo0OiJsZWFkIjtpOjE3Mzc7fQ%3D%3D

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Create a url custom field
2. Create a form 
3. Add email field and add a url field mapped with the url custom field previously created
4. Add action "send form result"
5. Submit the form and wait for the form result
6. See on the mail (token {formfield} have been transformed as real values) that the url field is a tracking link.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
I guess the tracking on links should not be enabled for "Send results" form action !

**Comment by npracht** [comment]
Label: Bug

**Comment by kuzmany** [comment]
I just tested. My results to email was correct, still the same if I used the email template

How can I reproduce it?

![image](https://user-images.githubusercontent.com/462477/41651365-b59b6312-7480-11e8-9431-e2afed5c708f.png)

![image](https://user-images.githubusercontent.com/462477/41651602-3232085e-7481-11e8-9c34-054cff53c4a1.png)

**Comment by npracht** [comment]
Now that we are in latest version i cannot reproduce anymore. Something may have fixed it.

Thanks !
