### ISSUE TITLE
Upgrade to 2.13.1 - DB Schema errors for Debian/Ubuntu servers and MySQL/MariaDB?

### ISSUE THREAD

**Issue by lightweight** [mautic/mautic#6050]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
I've struck errors (running MariaDB Ver 15.1 Distrib 10.0.34-MariaDB) when doing the upgrade. Had to run `app/console doctrine:schema:update --force --dump-sql` which has fixed visible problems of not being able to load the Landing Pages or Assets pages in the admin interface (or show any Landing Pages to users), but there were 3 schema update errors:
```
[Doctrine\DBAL\Exception\DriverException]  An exception occurred while executing 'ALTER TABLE tweets CHANGE text text VARCHAR(280) NOT NULL':  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.    
[Doctrine\DBAL\Driver\PDOException]  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.  
[PDOException]  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.  
```           
 I previously had collation utf8mb4 on the database for my Mautic instances, but have recreated the database of one of them (to test the process) with utf8 instead (and have reinstated the db having replaced all mentions of mb4 in the sql)... and I still cannot get `php app/console doctrine:migration:migrate` to work without that same error.

I assume this will affect a lot of people - anybody using a recent Linux based on Debian - given that their default collation is now uf8mb4 for both client and server... They also have `innodb_large_prefix` defined... any other thoughts on what I can to do make these schema updates work, ideally without changing the default settings for MySQL/MariaDB on Debian-based distros... 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.19
| DB | Ver 15.1 Distrib 10.0.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### Steps to reproduce:
1. Upgrade from previous version of Mautic to 2.13.1 via `php app/console mautic:update:apply` which results in errors including ```
[Doctrine\DBAL\Exception\DriverException]  An exception occurred while executing 'ALTER TABLE tweets CHANGE text text VARCHAR(280) NOT NULL':  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.    
[Doctrine\DBAL\Driver\PDOException]  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.  
[PDOException]  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. 
```
and a "failed" message, but at the same time, the script says "site now running 2.13.1" (or similar)
2. Then run a manual migration to get more information `php app/console doctrine:migration:migrate` to see the above errors again. 
3. Then run `php app/console doctrine:migration:status` which for me gives

``` 
...
   >> Latest Version:                                     2018-04-19 14:59:34 (20180419145934)
    >> Executed Migrations:                                100
    >> Executed Unavailable Migrations:                    0
    >> Available Migrations:                               109
    >> New Migrations:                                     9

```
showing there're 9 pending schema updates. 

### Log errors: 
'''
[2018-05-07 01:52:59] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE tweets CHANGE text text VARCHAR(280) NOT NULL':  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 while running console command `doctrine:migrations:migrate` [] []
[2018-05-07 02:55:37] mautic.WARNING: Command `doctrine:schema:update` exited with status code 1 [] []
[2018-05-07 02:59:59] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE tweets CHANGE text text VARCHAR(280) NOT NULL':  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes. (uncaught exception) at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 while running console command `doctrine:migrations:migrate` [] []
'''

**Comment by lightweight** [comment]
I have found, in the case of one of the failed migrations: `ALTER TABLE tweets CHANGE text text VARCHAR(280) NOT NULL;` that if I first run `ALTER TABLE tweets ROW_FORMAT=DYNAMIC;`, I can then run the CHANGE query successfully...

**Comment by heathdutton** [comment]
Mautic is an InnoDB application, ROW_FORMAT should always be DYNAMIC by default. Perhaps we should mention this in the documentation to avoid future issues.

**Comment by AkkuFresh** [comment]
I am sorry, did not check this issue, and write an other with similar issue here: https://github.com/mautic/mautic/issues/6693
There is a more detailed analyse.

**Comment by AkkuFresh** [comment]
> I have found, in the case of one of the failed migrations: `ALTER TABLE tweets CHANGE text text VARCHAR(280) NOT NULL;` that if I first run `ALTER TABLE tweets ROW_FORMAT=DYNAMIC;`, I can then run the CHANGE query successfully...
> 
> And apparently, according to this: https://discuss.pivotal.io/hc/en-us/articles/115004086747-Apps-are-down-due-to-the-Maximum-Column-Size-is-767-bytes-Constraint-in-MySQL it should also be possible to use ROW_FORMAT=COMPRESSED rather than the default ROW_FORMAT=COMPACT to avoid these problems. I'm just testing this theory...
> 
> In fact, running the following two queries:
> 
> ```
> ALTER TABLE lead_fields ROW_FORMAT=DYNAMIC;
> ALTER TABLE tweets ROW_FORMAT=DYNAMIC;
> ```
> subsequently allowed the `php app/console doctrine:migration:migrate` without error.

@lightweight How to change the full migration system to check what InnoDB row format is set?
I faced with this issue using Laravel and Mautic also.
Ref: https://github.com/mautic/mautic/issues/6693

**Comment by npracht** [comment]
@heathdutton would you kindly propose a PR to enhance documentation with your comment https://github.com/mautic/mautic/issues/6050#issuecomment-419531436 ?
