### ISSUE TITLE
Widgets not showing data

### ISSUE THREAD

**Issue by jonasstinkens** [mautic/mautic#6052]
| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
Problem with adding new widgets in the dashboard.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.12.2
| PHP version | 7.0.28-1~dotdeb+8.1

### Steps to reproduce:
In the dashboard I want to create 3 new widgets, type 'report graph':
All emails, 'Emails sent'.
All emails, 'Most emails sent'.
All emails, 'Most emails read'.

I tested this on 3 of our Mautics. 
Attachment 'test 1' and 'test 2' show missing data, while the report is available and working (otherwise all 3 of the widgets should be empty as well).

Attachment 'test 3' is how it should look like. This is done in a Mautic version v2.11.0.

![test 1](https://user-images.githubusercontent.com/38032971/39700648-408ce9aa-51fe-11e8-9375-efe74a8d3212.png)
![test 2](https://user-images.githubusercontent.com/38032971/39700653-42d76dca-51fe-11e8-99f7-3a669f033fea.png)
![test 3](https://user-images.githubusercontent.com/38032971/39700640-384433ac-51fe-11e8-80c7-4b2bf0f25404.png)

**Comment by npracht** [comment]
Fixed in https://github.com/mautic/mautic/pull/6069
