### ISSUE TITLE
message/redirection after submitting preference center

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6053]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
In the preference center, when we save preferences nothing more happens.
It could be nice to display a message that say thanks it is validated (something like this) or to add a URL redirection to the save preferences button.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version |

**Comment by kuzmany** [comment]
Label: WIP

**Comment by kuzmany** [comment]
Do you mean default preferences center or customized preferences center (https://www.mautic.org/docs/en/contacts/customize_preference_center.html)?

**Comment by johbuch** [comment]
yes I mean the customized pref center. The one we create as a landing page and set YES to be the preference center.

**Comment by kuzmany** [comment]
Clear, thanks. I will test

**Comment by npracht** [comment]
Label: Enhancement

**Comment by alanhartless** [comment]
Looks like this was fixed in 2.15.0

**Comment by miteshgala** [comment]
I am running 2.16.0 and the problem persists
