### ISSUE TITLE
[Bug] Contacts are re-processed by a campaign from a segment if events are deleted.

### ISSUE THREAD

**Issue by heathdutton** [mautic/mautic#6054]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
A marketer has a campaign that has been active for some time. This campaign is based on a segment. Then the marketer decided to replace the events in the campaign for new contacts coming in. They didn't want to create a new campaign, because they only wanted to change the workflow for the latest contacts.

By deleting/replacing the events, all contacts that have gone through the campaign before will be *re-processed* by the campaign. This is not at all expected behavior, and it can be rather costly. 

### Explanation:
The foreign key constraint on campaign_lead_event_log is to blame...

Firstly, when an event is deleted, all the logs for that event are deleted also. If you have 100s of thousands that will cause your system to hang and crash while deleting all those rows. This causes the campaign builder to flake out pretty spectacularly, duplicating events and shoving them all to the top left of the editor. This isn't the real bug this issue is for though...

Secondly, campaigns that are based on a segment no longer have data to join against to discern if a contact has gone into the campaign or not... This means on the next `mautic:campaign:update` call, every lead already having gone through that campaign will be pushed into it anew. This results in someone (me) spending 8+ hours cleaning up the mess and making apologies to a call center that received a massive amount of duplicate leads. ¯\\_(ツ)_/¯

### Questions for the core team
Should we drop this foreign key constraint? Can we? What are the implications of doing so?
I'd rather err on the side of keeping these logs, even if it causes a bit of data bloat.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.1

### Steps to reproduce:
1. Create a campaign based on a segment with one (simple) action of any kind.
2. Wait for the cron tasks `mautic:campaign:update` and `mautic:campaign:trigger` to complete all leads through that action.
3. Delete the action from the campaign, and replace it with another.
4. Watch `mautic:campaign:update` and `mautic:campaign:trigger` re-process the segment again with the new action.
 
### Log errors: 
Various memory exceeded errors occur, because the campaign in question had 375k leads at the time.

**Comment by npracht** [comment]
Label: Bug

**Comment by RCheesley** [comment]
@heathdutton is this still a bug or has it been addressed since you reported this?

**Comment by heathdutton** [comment]
@RCheesley this would be mitigated by #6247

**Comment by RCheesley** [comment]
As the PR has been closed due to lack of activity I'm also going to close down this issue. If folk wish to resurrect the PR in the future then that would be great if the issue persists.
