### ISSUE TITLE
Dashboard: Cancelling "Add Widget" window adds widget nevertheless

### ISSUE THREAD

**Issue by silsha** [mautic/mautic#6058]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Cancelling the „Add Widget“ modal window, which appears when clicking the menu item „Add widget“ in the dropdown menu, the widget is created nevertheless.

This only happens when you select a widget type in the modal window.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.27-0+deb9u1

### Steps to reproduce:
1. Login to Mautic
2. Open the dashboard view
3. Click the arrow near the „Save“ button to expand the drop down menu
4. Click „Add widget“
5. In the modal window, select a widget type
6. Click „Cancel“

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by silsha** [comment]
Hi, I can confirm that the problem still exists in 3.0.1 and can be reproduced by following the above steps.
