### ISSUE TITLE
Campaign with multiple date-based conditions triggering all at once when user added to segment

### ISSUE THREAD

**Issue by Gruncher** [mautic/mautic#6062]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
I have a campaign where contacts all have an expiry date (date field value) where the user needs to take action and update their profile. However, this is a variable date, different for everyone -- sometimes in days, weeks or months.

In the campaign, I have setup multiple condition triggers based on this date.

As a _test_ of this campaign, I have set up the triggers as such:

-3 days before expiry date
-2 days before expiry date
-1 days before expiry date

My problem is this: if the user joins the segment -1 days before the expiry date, they are instantly sent all 3 emails at the same time. Clearly, this is not what I want.

Is this actually a bug? Am I doing something incorrectly?

Here is an example of a trigger I've setup:
![image](https://user-images.githubusercontent.com/15200268/39764135-7a4bb880-52ce-11e8-9481-e25ba323b369.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.30-1

### Steps to reproduce:
1. Setup campaign with multiple date-based triggers that lead up to a date. For example, -1 days before, -2 days before, -3 days before.
2. Have user join the segment/campaign -1 days before the date. They will instantly be sent all of the emails in the campaign leading up to this date.

**Comment by npracht** [comment]
Label: Bug

**Comment by Gruncher** [comment]
This problem still seems to exist. Is there anything I can do about it, or some type of workaround that might work? I really need this functionality.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
