### ISSUE TITLE
Error during the installation process. SQLSTATE[HY000]: General error: 1709 Index column size too large.

### ISSUE THREAD

**Issue by SamvelG** [mautic/mautic#6064]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Error during the installation process.
An error occurred while attempting to install the data:... SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
Screenshot: https://ibb.co/gYYUjS

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.13.2-dev
| PHP version | PHP 7.1.16
| MySQL version | 5.5.56-MariaDB

### Steps to reproduce:
1. Open the `app/config/config.php` configuration file and find **//Doctrine Configuration** section
2. Add the following settings after `'charset'  => 'utf8',`:
```
'default_table_options' => [
        'charset'    => 'utf8',
        'collate'    => 'utf8_unicode_ci',
        'row_format' => 'DYNAMIC',
    ],
```
 
### Log errors: 

An error occurred while attempting to install the data:... SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Label: Ready to test

**Comment by jinformatique** [comment]
Hello, I got the same error installing Mautic 2.13.1 today. I'll wait for next release to reinstall. By curiosity, is there a release date planned?

**Comment by neerajsinghsonu** [comment]
Hi All,

I had 'mautic' v-2.15.3, but none of the solution worked during installation. Gotta same issue during the setup on "macOS High Sierra" with MySQL@5.6.43. So I had executed below query to solve the issue.

> Error:  MySQL column size too large issue

1. Run below query before run install on database

```mysql
set global innodb_file_format = `BARRACUDA`;
set global innodb_large_prefix = 1;
set global innodb_file_per_table = `ON`;
```
Now, start the setup of 'mautic' and everything will work fine.
