### ISSUE TITLE
Cannot create New Segment Emails

### ISSUE THREAD

**Issue by gmproch** [mautic/mautic#6065]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| Yes | ---
| Bug report? | Yes 
| Feature request? | 
| Enhancement? | 

## Description:
Cannot create new segment emails
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 5.4.45

### Steps to reproduce:
1. Click "Channels"
2. Click "Emails"
3. Click "New"
4. Select "New Segment Email"
5. Fill out required info on form
6. Click on "Apply" System goes back to the "New Segment Email..." screen

Also Running http://[Mautic location]/s/update/schema produces error:
"An error occurred while updating the database. Check log for more details." 

### Log errors: 
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

[error log.txt](https://github.com/mautic/mautic/files/1986835/error.log.txt)

**Comment by npracht** [comment]
I guess this is an installation issue. Your logs does not mention the fatal error you seem mentioning.

**Comment by cStuartHardwick** [comment]
This seems like the same problem I've having in which I've suddenly lost the ability to create or edit any emails. On attempting to save a new email, it returns to the "segments or template" selection. On attempting to save updates to an existing email, changes just vanish. No error messages are written anywhere I've been able to locate.

This isn't an install problem. It was working till Friday, and no updates have been applied, but if I can't find a solution withing a few days, I will be forced to find a replacement for Mautic.
