### ISSUE TITLE
Cant update mautic from 2.12.2 to 2.13.1

### ISSUE THREAD

**Issue by ServicedCloud** [mautic/mautic#6067]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N 
| Enhancement? | N 

## Description:
We have a self-hosted mautic that is version 2.12.2 and we are trying to update 2.13.1 via ssh.
But the update says "Error Allowed memory size of ...... bytes exhausted.....". We did try fixing this by increasing the memory_limit in our php.ini, however this error still exists. (Please note that we did cleared cache)

Another one that we did try is to update manually, this works but a landpages, email, campaigns are not working (This is our initial findings). What we did was extract the 2.13.1 zip files then uploaded local.php and our custom themes, images, etc..

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 5.6.35

**Comment by npracht** [comment]
1. I'd say it is a server configuration issue (timeout)
2. I'd say that you still have to update your schema, clean cache and generate assets ?

**Comment by npracht** [comment]
Label: Pending Feedback
