### ISSUE TITLE
i have replaced twilio api with my api but still twilio is sending the sms. Can someone help please.

### ISSUE THREAD

**Issue by sahiljethwani11** [mautic/mautic#6068]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello,

You have a cache in your app, maybe you need to clean it. Also there is a integration cache tab in your DB, maybe you can empty it?
Waiting for your feedback !

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by sahiljethwani11** [comment]
Hey, thanks for replying.My server logs error are as follows.
[Mon May 14 12:37:20.368675 2018] [:error] [pid 3185] [client 127.0.0.1:37952] Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException: The service "mautic.sms.api" has a dependency on a non-existent service "mautic.twilio.service". - in file /var/www/html/mautic/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php - at line 58, referer: http://local.mautic.com/s/contacts/view/11
 And i am getting a generic error when my capaign is triggered.

**Comment by sahiljethwani11** [comment]
Can you guide me on how to set up our own sms api instead of twilio

**Comment by dbhurley** [comment]
I'd recommend carrying this discussion on in the Slack channels or forums. You''ll probably get better responses and conversation there.
