### ISSUE TITLE
issue in campaign builder with action update contact

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6080]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
In the campaign builder, you add the action "update contact" to update a "date" contact field, there is an issue if you use the word "today" on this date field. All contacts will have this field updated with the date the day you set and saved this option. (not the actual today date).

For example, when I added this action on the campaign, I filled the date filed with "today" (when I did that it was 2018-05-11.
I go through the campaign today (2018-05-14). When the campaign is done, this field has been updated for my contact with the date of 2018-05-11 and not 2018-05-14.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Create a date field
2. Create a campaign and add the action "update contact".
3. Update this date field with "today"
![image](https://user-images.githubusercontent.com/31535432/39989862-6334e206-576b-11e8-91ed-418036e8248e.png)
4. Click on update.
5. Go back on this action to check it. It is not filled with "today" but with the date of today
![image](https://user-images.githubusercontent.com/31535432/39989938-a31404f6-576b-11e8-91c5-49a2e8604e4c.png)
6. That means if 2 weeks later, a contact goes through this campaign, this field will be updated with the date 2018-05-14 and not with the date in 2 weeks.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by johbuch** [comment]
@kuzmany 
I found this https://github.com/mautic/documentation/pull/262/files?short_path=4408195#diff-44081953730b38fc2f796040f927f316
so I tested it in a campaign action but it does not work.

**Comment by kuzmany** [comment]
But you linked docs for segments and docs is for upcoming 2.14 
You can use relative dates but just in segments filter at the moment

**Comment by merlin0** [comment]
Still you can use today in the campaign builder, but it's a static date. Which doesn’t make sense really since you can manually select it. So it's logical to me it supposed to be the current date.

**Comment by kuzmany** [comment]
As I sad, campaign action - update contact doesn't support relative dates. @alanhartless can you confirm it?

We can add relative dates, similar like here date operate in contact field/form field condition  (added  https://github.com/mautic/mautic/pull/5709 )

![image](https://user-images.githubusercontent.com/462477/40099975-95c0db30-58e2-11e8-9c03-5acfc1e84df7.png)

But It's feature request and need more time 👍

**Comment by kuzmany** [comment]
Label: WIP

**Comment by Shirkit** [comment]
I just tested this in 2.14.1 @kuzmany and it didn't work. After I input the word "today" in the Joined promotion. When I save and click to edit back the field, that is what appear (the current date, when it should be "today").

![1111](https://user-images.githubusercontent.com/829823/45984006-7d224e00-c035-11e8-984a-cb9be1f400ef.jpg)

**Comment by kuzmany** [comment]
@Shirkit  As you can see https://github.com/mautic/mautic/pull/6126 , feature is not merged and is marked for 2.15.0. You can test it and write comment for speed up merge it to official release

**Comment by Shirkit** [comment]
I'm really sorry, I didn't notice it was pushed to 2.15, I thought it was on 2.14

I'm running on production env here, I'll try to setup a testing version for it. Thanks for the follow-up and sorry for the notification.

**Comment by RCheesley** [comment]
@johbuch @merlin0 @Shirkit can you please test #6126 so that we can get this merged into 3.1? This needs two tests by the 16th August to be considered.
