### ISSUE TITLE
Preference page Landing not working

### ISSUE THREAD

**Issue by lucianlazar1983** [mautic/mautic#6081]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
When selecting an existing landing page as Preference Page for a given email, user still see the default blank page with his contact preferences. It is impossible to show the landing page set as preference page instead.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | latest stable available
| PHP version |  7.0
<img width="1434" alt="screen shot 2018-05-14 at 13 22 00" src="https://user-images.githubusercontent.com/3727896/39992481-9c1b1738-577b-11e8-9180-913fd7476952.png">
<img width="1434" alt="screen shot 2018-05-14 at 13 22 39" src="https://user-images.githubusercontent.com/3727896/39992482-9c400264-577b-11e8-9194-c842c09fec41.png">
<img width="1434" alt="screen shot 2018-05-14 at 13 22 54" src="https://user-images.githubusercontent.com/3727896/39992483-9c60a866-577b-11e8-8ca3-0c6dec9c5350.png">

### Steps to reproduce:
1. Enabled in Email Setting preferences for Segments, Categories, Frequency, etc..
2. Add a new landing page, selecting Skyline template
3. Enabled option to set as a contact preference page
4. Put all the sections and the update preference button correctly
5. Create a new email and from options selected the landing page as preference page
6. Send email to contact
7. From the received email, clicking on the Unsubscribed/Preferences link pointed to the default non-skinned page.
 
### Log errors: 

No relevant errors in logs

What can i do?
Thanks

**Comment by npracht** [comment]
Can you test #7006 ?
