### ISSUE TITLE
Bug: boolean field gets overitten by empty value and resets to 0

### ISSUE THREAD

**Issue by merlin0** [mautic/mautic#6087]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? | 

## Description:
For syncing a specific opt-in for the newsletter I've created a boolean field which is opt-in. Default we've set the value to 0 because the contacts didn't give their consent of course. However we've got a couple of forms that have the option to subscribe to the newsletter. The problem start occurring when a contact has filled out the opt-in. So to boolean is set to 1, when they resubmit their another form with the checkbox and don't check the checkbox which isn't required it resets to 0. The default value is empty so this should not overwrite the 1 to empty which results in the 0.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.x

### Steps to reproduce:
1. Create a boolean field with default value 1 or set it to 1
2. Make form with a checkbox that is not required and has no default value
3. Submit te form without checking the checkbox so the value is empty

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Label: Bug

**Comment by Lologam** [comment]
Same (big) problem for us !

**Comment by kuzmany** [comment]
Confirmed

**Comment by npracht** [comment]
Hi @merlin0 could you please test PR ?
Thanks !

**Comment by kuzmany** [comment]
Also please test what happend If you use more checkbox  and defaultValue
