### ISSUE TITLE
Mautic v2.13.1

### ISSUE THREAD

**Issue by nituls** [mautic/mautic#6088]
I have updated mautic to latest v2.13.1 , after update I am getting issue with theme download.

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
I have installed my own theme package in mautic. But when I try to download it then mautic is showing we error that theme not found

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.13.1
| PHP version | 7.0.29

### Steps to reproduce:
1. Download any theme from mautic.

**Comment by alanhartless** [comment]
Fixed in https://github.com/mautic/mautic/pull/6010 and will be part of the next release.

**Comment by nituls** [comment]
thanks for confirming......................when will new release available..??
