### ISSUE TITLE
Timezone Issue

### ISSUE THREAD

**Issue by nituls** [mautic/mautic#6095]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this: Whenever I install mautic in my server, it is showing timezone -12 hours

| Q  | A
| ---| ---
| Bug report? | 

## Description:
Actually I have installed mautic on my server and start campaign and every thing but every time when I launch campaign I need to select timezone -12 hours to actual time . For eg. : If I need to set campaign publish time to 16/02/2018 6:00 UTC , then it need to set it to 15/02/2018 18:00 UTC so it can go on time. My server mautic both are on UTC Timezone.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.30

### Steps to reproduce:
1. Install Mautic and you will set it every action entry.
2. If you create something you will see its timing which is wrong i.e. 12 hours before.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @nituls what is your configuration on the mautic interface? Because you can set the timezone of the app (configuration top right of your window).

![capture d ecran 2018-05-18 a 09 37 47](https://user-images.githubusercontent.com/14075239/40222234-29fcdc66-5a7f-11e8-9da4-ba426a9bc2ab.png)

**Comment by npracht** [comment]
Label: Pending feedback

**Comment by nituls** [comment]
Hi @npracht 

Mautic is configured with UTC Timezone .

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by nituls** [comment]
@mautibot  @npracht any idea how to solve it

**Comment by npracht** [comment]
Nope sorry. I don't see it on my instances. The issue seem being a question of configuration.
What about your server configuration?

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/6520
