### ISSUE TITLE
UTM Tags - Google Analytics Traffic way less than Clicks registered in campaign emails

### ISSUE THREAD

**Issue by matijamikovic** [mautic/mautic#6097]
| Bug report? | 

## Description:
I set up UTM Tags (Source/Campaign/Medium/Content) on the sidebar when I build an email within Mautic. The relevant fields show up in Google Analytics it's just the traffic registered in GA when I look at the behaviour flow is significantly less (about 20%) than the clicks registered on the email in question and it's relevant landing page.

Any idea what is going on?

## If a bug:
Matuic Version: 1.12.1

**Comment by silsha** [comment]
AFAIR The URLs in are generated for every single mail, so mautic is able to track your click and redirect you afterwards.
For GA the javascript code is used, so visitors with an ad blocker or the the [Opt-Out Extension](https://chrome.google.com/webstore/detail/google-analytics-opt-out/fllaojicojecljbmefodhfapmkghcbnh?hl=en) will not be tracked.

**Comment by npracht** [comment]
Hello @matijamikovic ! I'd say that @silsha comment seems correct.
You may keep in mind that Google algorithm are different that Mautic one. So you'll also see on your analytics a difference in terms of page view on your webpages.
