### ISSUE TITLE
Mautic tool How do I set it up that points are added  E mail  website url clickl?

### ISSUE THREAD

**Issue by ganeshsoftee** [mautic/mautic#6099]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello,
This is not a forum/chat here, please go on mautic forum or slack with a bit more of context.
Could you please close your issue here ?

Thanks,

N.

**Comment by ganeshsoftee** [comment]
Thanks
