### ISSUE TITLE
issue/feature date format

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6101]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | X
| Enhancement? | 

## Description:
When I have a date custom field and send a email with the token, the date will be YYYY-MM-DD.
![image](https://user-images.githubusercontent.com/31535432/40222141-deff3de4-5a7e-11e8-9972-f4f30fa54090.png)

In the setting I can find this:
![image](https://user-images.githubusercontent.com/31535432/40222135-d50841e6-5a7e-11e8-9ff6-512d45ba382e.png)

But all these don't correspond to this format YYYY-MM-DD so it is not possible to modify it.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13
| PHP version |

**Comment by npracht** [comment]
Label: Enhancement

**Comment by npracht** [comment]
@kuzmany i'd suggest adding a fifth input with the token format expected.
Could you please work on it?

Thanks !

**Comment by kuzmany** [comment]
Label: WIP

**Comment by luizeof** [comment]
+1

**Comment by npracht** [comment]
Enhanced in #6237 merged in
