### ISSUE TITLE
Basic Auth getting a 404 on new build

### ISSUE THREAD

**Issue by vpl-webteam** [mautic/mautic#6102]
What type of report is this:
| Q   | A
| --- | ---
| Bug report? |  Yes

## Description:
I have installed mautic using docker on a server with Digital Ocean. I want to use the rest API, but I am unable to get any returns. All requests come back with the "Looks like I encountered an error (error #404)" I changed the configurations to test that it is connecting. Toggled the basic auth and got back "Basic Auth disabled". Everything should be working.  I have left the settings the same as the docker example. Maybe the port is not correct or I need HTTPS?

Url: http://104.236.7.135:8080/
No data is on the server so I am not concerned about having others look

What am I missing? 

## If a bug:
| Q   | A
| --- | ---
| Mautic version |  7.1.16
| PHP version | v2.13.1

### Steps to reproduce:
1. Installed via docker
2. Setup normally.
3. Attempt API call via curl.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by sirtimbly** [comment]
I can confirm that I am seeing this same problem. I'm using a docker image meant to replicate the environment that Laravel homestead uses: `image: shincoder/homestead:php7.1` (because I have a laravel app on the same server)

I cannot get anything but 404 from every API endpoint with basic auth from a fresh brand new installation.

**Comment by vpl-webteam** [comment]
Tried installing it on Bitnami (suggested in #6124) and that didn't work. I guess my best choice is to go to previous versions since there is no support for developers....

**Comment by luizeof** [comment]
@sirtimbly do you check your reverse proxy?

**Comment by sirtimbly** [comment]
I don't think that's the problem because I'm actually getting the 404 json response from the Mautic application.

**Comment by liamzdenek** [comment]
I'm experiencing this as well. PHP 7.0.30 and Mautic 2.13.1.

This is a fresh install of Mautic, but I'm not using the docker image. I enabled basic auth, then created a new user. Then, I run the following curl statement: `curl -X GET 'https://API_USER:password@example.com/api/contacts'`

My Mautic instance is set up with a domain name and is using HTTPS.

I always receive this response:

```json
{
    "error": {
        "code": 404,
        "message": "Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)"
    },
    "errors": [
        {
            "code": 404,
            "message": "Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!",
            "type": null
        }
    ]
}
```

If I disable basic auth, I receive this response:

```json
{
    "error": "access_denied",
    "error_description": "Basic Auth disabled. You need to enable HTTP basic auth in the API settings page of your Mautic account. (`error` and `error_description` are deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)",
    "errors": [
        {
            "code": 401,
            "message": "Basic Auth disabled. You need to enable HTTP basic auth in the API settings page of your Mautic account.",                                    
            "type": "access_denied"
        }
    ]
}
```

This makes me believe this is not a problem with the reverse proxy, as the API response is aware that the request is using basic auth. Additionally, failing to send the username:password produces a 401 "API authorization denied" error.

My suspicion is that this is a regression, but I don't have the time to install progressively older versions of Mautic to find one that works.

**Comment by vpl-webteam** [comment]
@liamzdenek thank you. I had given up on this, but delete the cache in docker worked.

Leaving a note for me and others in the future when this pops up.

Find docker id
```docker ps```

Open filesystem for docker
```docker exec -it {name-of-container} bash```

Remove cache (should be the same folder structure)
``` rm -rf app/cache/*```

**Comment by prosenjitsarkar** [comment]
Hi John , 

I have installed in my local machine , so no cache 
i didnt use "//" but still have 404 while trying to get contacts

Please help
