### ISSUE TITLE
Email builder's media manager : Link not copied to clipboard when clicking "Copy Link" icon

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#6105]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:

I click on the icon on the right, but no link is copier

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 

### Steps to reproduce:
1. Open email builder
2. Open Media manager
3. Upload an image
4. Click the icon copy link
5. CTRL + V somewhere to test

Result : the link wasn't copied into the clipboard.
 
### Log errors: 

N/A

**Comment by RCheesley** [comment]
I was able to reproduce this but it was a little unclear how, so I made a quick vid: https://youtu.be/LLu1f2-Kzrk

You can see that I clicked the 'copy url' of the image, but the URL is not actually copied to my clipboard despite the fact that it says it has been.

I think that's a bug with the editor maybe?

**Comment by stevedrobinson** [comment]
Here's my PR to fix this: https://github.com/mautic/mautic/pull/8519

**Comment by RCheesley** [comment]
Closing as no longer relevant with the new file manager!
