### ISSUE TITLE
Mautic tool how to track clicked url points 

### ISSUE THREAD

**Issue by ganeshsoftee** [mautic/mautic#6106]
Mautic tool how set the  the track clicked url points 

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by namankumar** [comment]
@npracht, this sounds similar to an issue I am having - how do you assign points to links clicked in emails and on landing pages? How do you do this for links where mautic tracking pixel is not installed? 

For example, I want to assign 4 points to a lead that clicks on my twitter icon on my mautic landing pages. How can I do this?
