### ISSUE TITLE
How to change current contact?

### ISSUE THREAD

**Issue by bookin** [mautic/mautic#6108]
Hello,

No one can't help me with it, perhaps someone here knows.

When user open site, Mutic create new contact, set new mtc_id and etc, but if I know who is it and I have mtc_id for this user, how I can refresh Mautic session and say Mautic mtc_id to save some data to the contact?

I will be glad any ideas, thanks.

**Comment by npracht** [comment]
Hello,

I think you can use the tracking script to pass some custom parameter. Please refer to the documentation: https://www.mautic.org/docs/en/contacts/contact_monitoring.html on chapter **Tracking of custom parameters**.

Enjoy !
