### ISSUE TITLE
Position field values not shown in contacts list page

### ISSUE THREAD

**Issue by andreab79** [mautic/mautic#6109]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
Position field values in contacts list page are not shown

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.13.1 
| PHP version | 7.0.30

### Steps to reproduce:
1. add text value to position contact field
2. save contact and show contacts list
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @andreab79 ,

I don't think it is a bug as far as this column is not shown on the contacts list. You confirm that you don't have an empty column that should be filled in?

**Comment by andreab79** [comment]
hi, tx for reply, i confirm that if i compile position field in contact edit page, and save, and show contact list page, position column is empty for modified contact. please test the same, works by your hand?

**Comment by npracht** [comment]
Hello @andreab79 i am very sorry but this column is not visible on my side and as far as i know this is not configurable.
![capture d ecran 2018-06-03 a 16 02 50](https://user-images.githubusercontent.com/14075239/40887340-ac396ef4-6747-11e8-9fb8-e473c85e7e83.png)

Could you share a screenshot ?

Thanks,

N.

**Comment by andreab79** [comment]
@npracht sorry it was a trivial mistake, i confused location with position in italian transalation. tx for your time

**Comment by npracht** [comment]
No problem !
Best
