### ISSUE TITLE
Segments issue for user role

### ISSUE THREAD

**Issue by andreab79** [mautic/mautic#6110]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | 
| Enhancement? | 

## Description:
user with a role with access to own contacts, is not able to see, create, modify or delete own segments

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.13.1 
| PHP version | 7.0.30

### Steps to reproduce:
1. create a user role with access to only own contacts
2. login with this user and click on segments menu link
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by andreab79** [comment]
@npracht tx for your work

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
