### ISSUE TITLE
Segment Issue - For Tag Filter

### ISSUE THREAD

**Issue by tathspts** [mautic/mautic#6112]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | 
A Question

## Description:
I have contacts added to my self hosted mautic instance and each contact is tagged with different tags. Now when I try to create a segment and filter it based on a particular tag, segment gets created but it says it has no contacts in it. When clearly I have over 1000 contacts that are tagged that value.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.27

**Comment by tathspts** [comment]
just bumping it up. Is it a known issue?

**Comment by tathspts** [comment]
how to do you launch a command to update segments? I do have cron jobs setup if thats what you mean.

Steps to reproduce

Segments --> New --> Filters --> Tags --> Including --> Chose Tag

After choosing the tag and saving the segment, segment still shows "0 Contacts" in it. Even though I have many contacts with that tag.

**Comment by npracht** [comment]
Hi @tathspts i am very sorry but i cannot reproduce.
![capture d ecran 2018-06-03 a 15 59 38](https://user-images.githubusercontent.com/14075239/40887314-68ac4e4a-6747-11e8-9cbc-c3d45b7d44cc.png)
![capture d ecran 2018-06-03 a 16 01 09](https://user-images.githubusercontent.com/14075239/40887315-68c539c8-6747-11e8-8f94-669e0b36719e.png)

Do you have an error in the logs after the CRON jobs execution?
Thanks,

N.

**Comment by tathspts** [comment]
will those logs be found under app folder?

I am trying to solve this problem for more than a year now and every attempt is unsuccessful.

**Comment by tathspts** [comment]
nevermind its solved.

**Comment by verygoodplugins** [comment]
@tathspts Can you please post what you did to solve this? I'm having the same issue.

**Comment by tathspts** [comment]
I had cron jobs setup wrong.
