### ISSUE TITLE
Twitter Hashtag Not Working In self-hosted Server 

### ISSUE THREAD

**Issue by lalitnandandiwakar** [mautic/mautic#6114]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Click On Social  Monitoring
![image](https://user-images.githubusercontent.com/11966970/40405902-133034b4-5e7c-11e8-8e39-2e6a45baa001.png)
 
2. Save And Close 
And i Generate Error   
![image](https://user-images.githubusercontent.com/11966970/40405944-4c3c5e54-5e7c-11e8-8849-5ef8e4be1617.png)

 
### Log errors: 
![image](https://user-images.githubusercontent.com/11966970/40405833-cad06946-5e7b-11e8-8ec4-961ea3b2ee69.png)
 Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT DATE_FORMAT(t.post_date, '%Y-%m-%d') AS date, post_count AS count FROM monitor_post_count t WHERE (t.monitor_id = ?) AND (t.post_date BETWEEN ? AND ?) AND (t.monitor_id = 7) GROUP BY DATE_FORMAT(t.post_date, '%Y-%m-%d') ORDER BY DATE_FORMAT(t.post_date, '%Y-%m-%d') ASC LIMIT 31' with params [7, "2018-04-23 00:00:00", "2018-05-23 16:10:10"]:  SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'MauticAutomation.t.post_count' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT DATE_FORMAT(t.post_date, '%Y-%m-%d') AS date, post_count AS count FROM monitor_post_count t WHERE (t.monitor_id = ?) AND (t.post_date BETWEEN ? AND ?) AND (t.monitor_id = 7) GROUP BY DATE_FORMAT(t.post_date, '%Y-%m-%d') ORDER BY DATE_FORMAT(t.post_date, '%Y-%m-%d') ASC LIMIT 31' with params [7, \"2018-04-23 00:00:00\", \"2018-05-23 16:10:10\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'MauticAutomation.t.post_count' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'MauticAutomation.t.post_count' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'MauticAutomation.t.post_count' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Duplicate of https://github.com/mautic/mautic/issues/4021

The quick fix is to set SQL mode only_full_group_by in your database.
