### ISSUE TITLE
issue with outlook plugin if you do not track email

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6119]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is an issue with the outlook plugin.
If you set up the outlook plugin, then send an email from Outlook but do not click on "track email", the contact is still created in Mautic (it should not)
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13
| PHP version | 

### Steps to reproduce:
1. set up the outlook plugin
2. Send an email from outlook and click on track email
3. Check on mautic if the contact has been created (it should be created)
4. Then go back to outlook and send a new email to another contact (that is does not exist in mautic) but this DO NOT click on track email
5. Check in Mautic, contact has been created (it should NOT)
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Reported here 1 year ago: https://github.com/virlatinus/MauticOutlookPlugin/issues/1

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
@dbhurley how do we manage that. The code is only on Werner's repo ?
Can we clone it in Mautic repos ?

**Comment by alanhartless** [comment]
@npracht https://github.com/mautic/MauticOutlookPlugin

**Comment by npracht** [comment]
Thanks @alanhartless i didn't search the correct keyword...
Should we open the issue there ?

**Comment by alanhartless** [comment]
You're good. I had just forked it. Yes, it can be opened there. Although, we no longer have any devs with a windows machine. Do you guys?

**Comment by npracht** [comment]
It is not possible to open issues on the forked repo. Maybe you could copy the code and create a new repo ?

No windows dev... I've just hired 2 new devs that arrives in few days, i'll ask them maybe we're lucky :D

**Comment by npracht** [comment]
Label: Bug

**Comment by npracht** [comment]
@alanhartless the last commit seems to be on a related topic.
I am not dev as you know, but this is quite explicit here with the comment right?
https://github.com/mautic/MauticOutlookPlugin/commit/14bb7da1e2eca55b39f5082cdb94f35014a8a905#diff-3c5b5973fc5b17e844680b1aa448a74dR79

**Comment by npracht** [comment]
@kuzmany i know it is complicated because quite different tech, but are you able to give a look ?

**Comment by npracht** [comment]
Currently working on it with a freelancer

**Comment by npracht** [comment]
Hi @alanhartless i've hired a guy for C#.
See PR https://github.com/mautic/MauticOutlookPlugin/pull/1

I confirm you when I have finished my tests :)

**Comment by npracht** [comment]
Hi Alan,

I confirm that the new version works after testing 👍 
Find attached the new install file.

### To do

1. Merge PR - you'll notice that i asked the freelancer to add some more documentation
2. Update the documentation where the link to download the package is existing. You'll notice that the link is broken today. I don't know where you want to how the install file to keep it working.

![capture d ecran 2018-05-31 a 14 17 15](https://user-images.githubusercontent.com/14075239/40784194-38f4a544-64e5-11e8-9864-ae645ae4ddb8.png)

[Find attached the new installer.zip](https://github.com/mautic/mautic/files/2069132/installer_060418.zip) the guy included a readme.mp inside the sources. I don't know on which repo you want to add it.

**Comment by djeraseit** [comment]
this is the only place to find the Outlook Plugin

**Comment by autoize** [comment]
We tested the installer provided by @npracht and had success using the Outlook add-in / plugin.
In fact, we documented the process [how to configure and install it](https://autoize.com/mautic-outlook-integration-plugin/). 

The contacts **were not created** if **Track Email** was not selected in Outlook (no tracking pixel was appended to the body of the message) - so I think this issue seems fixed, and can probably be closed. 

Thank you to the **Webmecanik** team for their efforts on this (and many other things). :-)

**Comment by npracht** [comment]
@autoize could you PR the documentation on the readme.md here https://github.com/mautic/MauticOutlookPlugin and/or on the mautic documentation https://github.com/mautic/documentation ?

**Comment by RCheesley** [comment]
Apparently the fixes to the plugin [no longer work](https://github.com/mautic/MauticOutlookPlugin/pull/1#issuecomment-561505253) so we need to decide how to approach this - do we find someone to bring it up to date?

**Comment by RCheesley** [comment]
Closing this issue due to a lack of recent activity.
