### ISSUE TITLE
php 7.2 compatibility

### ISSUE THREAD

**Issue by nephaste** [mautic/mautic#6128]
Hi Mautic Team, i am an application integrator for Qnap NAS, 

I would like to integrate Mautic as QPKG for our community, 
but our Apache is currently running under php 7.2.x

once Mautic is launched 

Mautic does not support PHP version 7.2.6 at this time. To use Mautic, you will need to downgrade to an earlier version.

Any chance you make it php 7.2 compliant ?

thanks for all

**Comment by nephaste** [comment]
no answer :(

**Comment by dbhurley** [comment]
Wrong spot for questions, that's probably the reason you didn't get an answer. :) Ask in Slack support or in the forums and you'll most likely have better success.

**Comment by nephaste** [comment]
seems related to https://github.com/mautic/mautic/pull/5936

**Comment by andersonbraz** [comment]
I solved like this:

On file: mautic/app/middlewares/VersionCheckMiddleware.php

I changing:

``php
const MAUTIC_MAXIMUM_PHP = '7.1.999';
``

to

``php
const MAUTIC_MAXIMUM_PHP = '7.2.999';
``

Best Regards!

by [Anderson Braz](https://andersonbraz.com)
