### ISSUE TITLE
Campaign not triggering from forms contact source after sometime

### ISSUE THREAD

**Issue by mnfjorge** [mautic/mautic#6129]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
I've just installed mautic in a AWS EC2 server running Ubuntu 16.04.4 LTS (xenial).
Created a form, landing page and campaing.
The campaign triggers ok for sometime, when I submit the form. After a while, it stops triggering.
I can see the contacts are being added to the form's results, but not being triggered by the campaign.
Even running the php app/console mautic:campaing:trigger results in 0 events executed

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.1

### Steps to reproduce:
1. Created a form
2. Created a landing page with the form in it
3. Created a campaign
4. Defined the form as the campaign's contact source
5. Defined an action to send an email to my user.
 
### Log errors: 
No error logs where generated in my tests.

**Comment by alanhartless** [comment]
Do you mean it stops working for different contacts or for the same contact that submits the form multiple times?

**Comment by mnfjorge** [comment]
Hi @alanhartless !
It happens for every contact: new and repeated.

**Comment by luizeof** [comment]
any custom field required that is not present at form.?

**Comment by mnfjorge** [comment]
no, we don't have any custom fields

**Comment by RCheesley** [comment]
Is this still a problem @mnfjorge ?
