### ISSUE TITLE
Possibility of text breaking in button slot type

### ISSUE THREAD

**Issue by dakur** [mautic/mautic#6136]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | -
| Feature request? | ✔️
| Enhancement? | -

## Description:
When I make a button using Button slot type in E-mail GUI Builder and I add quite a long label for the button, it results in long button with last word on a new line:  
![image](https://user-images.githubusercontent.com/9862581/40646703-3fab9af8-632a-11e8-9512-3a7b3bb4eb04.png)

I would appreciate a possibility of something like allowing `\n` in button label (which would internally parse to `<br>` or something) or setting a `max-width`. So the result would be:  
![image](https://user-images.githubusercontent.com/9862581/40646773-7a6c1d34-632a-11e8-99bb-fddb1d9e9642.png)

**Comment by RCheesley** [comment]
Hi there, as we are only providing updates for Mautic 3.x going forward, can you confirm if this is still missing in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
