### ISSUE TITLE
Plugin/Extension Manager

### ISSUE THREAD

**Issue by dgram** [mautic/mautic#6137]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

## Description:
I want to ask if its planned in future to integrate something like an GUI based extension/plugin manager.
Something like [typo3 extension manager](https://docs.typo3.org/typo3cms/GettingStartedTutorial/ExtensionManager/Index.html), i think this could be an game changer.

Why?
I think if theres an extension manager with an global entry point to upload extension (such as packagist.org or anything like this), this could drive the development forward enormously.

More developers can see extensions which will be developed, mautic would be get bigger faster.
I also think this makes the mautic core more generally and easier to update.

It can also enlarge the mautic community.

I got the idea because of the comment in the [New Channel: Messenger](https://github.com/mautic/mautic/pull/4449#issuecomment-351486883) comment from @alanhartless which means that you are no longer accept new integrations/plugins in the core.

regards, daniel

**Comment by RCheesley** [comment]
Closing this down as it is being worked on (see https://forum.mautic.org/t/mautic-marketplace/12108 for discussion!)
