### ISSUE TITLE
How to connect the Mautic Rest Api with a Java Application

### ISSUE THREAD

**Issue by william1795** [mautic/mautic#6138]
## Description:
Hello Everyone,

I would like to connect the Mautic Rest API with a java application.

Would someone have a simpler and more effective way?

I’m trying JMAUTIC right now but I’m having a lot of problems.

Some body can help me?

Thanks

**Comment by henriquewinchester** [comment]
I had a hard time trying to use JMuatic and Outh2. So I am using de Mautic Rest API this way:

`
import okhttp3.Credentials;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

import java.io.IOException;

public class Main {

    public static void main(String[] args) {

        String endpoint = "[URL TO YOUR MAUTIC]/api/contacts";

        try {

            String credential = Credentials.basic("[USER]", "[PASS]");
            OkHttpClient client = new OkHttpClient();
            Request request = new Request.Builder()
                    .url(endpoint)
                    .header("Authorization", credential)
                    .build();
            Response response = client.newCall(request).execute();
            System.out.println(response.body().string());

        } catch (IOException e) {

            e.printStackTrace();

        }

    }

}
`

**Comment by npracht** [comment]
I think you could have this discussion on forum or slack as far as it is not a code issue.
Thanks !

**Comment by william1795** [comment]
Hello @henriquewinchester  thank you for your advise. I had try and that walk good on tomcat but not with liferay or jboss. Is there an another alternative?

Hello @npracht  okay i just posted that on slack.

Thanks you all!!
