### ISSUE TITLE
Suite / SugarCRM contacts not syncing

### ISSUE THREAD

**Issue by YosuCadilla** [mautic/mautic#6139]
What type of report is this: Bug report

## Description:
Using the Sugar plugin with SuiteCRM (theoretically 100% compliant) Leads sync works but contacts sync does not.

Providing that there exist some un-synced contacts, run:
php /var/www/.../app/console mautic:integration:synccontacts -i Sugarcrm

Result:
_Command to fetch contacts from integration
Fetch contacts command is starting

Fetching contacts...

0 contacts were updated and 0 contacts were created

Fetching companies
Fetch companies command is starting

0 companies were updated and 0 companies were created

Updating/creating leads from Mautic to Sugarcrm
Number of contacts pushed: 0 updated, 0 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria)_

## If a bug:
Mautic version: 2.13.1
PHP version: 7.0.x
SuiteCRM version: 7.10.1 -  Sugar Version 6.5.25 (Build 344)

### Steps to reproduce:
1. Install Sugar plugin (and SuiteCRM) and establish a working link.
2. Add at least one contact to Sugar/Suite.
3. Tick the "contacts" checkbox under "Choose SugarCRM objects to pull contacts from" in the plugin 
3.1 Optional: Reset cache
4. Run the sync command:   php /var/www/.../app/console mautic:integration:synccontacts -i Sugarcrm

### Log errors: 
Mautic log is empty
No errors in Apache log.

**Comment by YosuCadilla** [comment]
Tested in 2.12.2 first, then upgraded to 2.13.1, same results

**Comment by npracht** [comment]
What is the creation date of your contacts ?
Because it does not take all the contact from very far in the past. You have this parameter to play with in the command: `--time-interval=20minutes`
eg: `mautic:integration:fetchleads --time-interval=20minutes --integration=Sugarcrm`
You can also try `--fetch-all`

Also your command does not sound familiar to me. I cannot find `mautic:integration:synccontacts ` in the documentation but `mautic:integration:fetchleads`.

**Comment by npracht** [comment]
Label: Pending Feedback

**Comment by YosuCadilla** [comment]
I ran an extensive battery of tests, all done with leads created "last minute"

NOTE: In my experience (just an observation, not scientifically tested) while --fetch-all works for Salesforce Integration, it seems to have no effect with the sugar integration.

**Comment by YosuCadilla** [comment]
Could be interesting to know what the default "timing" value is when not set.

**Comment by YosuCadilla** [comment]
It is my understanding that mautic:integration:synccontacts seems to be equivalent to mautic:integration:fetchleads.

fetchleads is supposed to do what it says and used in conjunction with the push pushleadactivity command.
mautic:integration:synccontacts is supposed to do both?

I started using fetchleads, as I also was familiar with the command, then found that Sugar should use the synccontacts instead so I switched.

Anyway, I just ran "/app/console mautic:integration:fetchleads -i Sugarcrm --fetch-all"
right now in the same machine all tests were conducted, just in case...

Result:
Command to fetch contacts from integration
Fetch contacts command is starting

Fetching contacts...

0 contacts were updated and 0 contacts were created

Fetching companies
Fetch companies command is starting

0 companies were updated and 0 companies were created

Updating/creating leads from Mautic to Sugarcrm
Number of contacts pushed: 0 updated, 0 created, 0 had errors and 0 were ignored (likely duplicates or didn't match field criteria)

**Comment by YosuCadilla** [comment]
app/console mautic:integration:fetchleads -h

Usage:
  mautic:integration:fetchleads [options]
  mautic:integration:synccontacts

Options:
  -i, --integration=INTEGRATION        Fetch leads from integration. Integration must be enabled and authorised.
  -d, --start-date=START-DATE          Set start date for updated values.
  -t, --end-date=END-DATE              Set end date for updated values.
      --fetch-all                      Get all CRM contacts whatever the date is. Should be used at instance initialization only
  -a, --time-interval[=TIME-INTERVAL]  Send time interval to check updates on Salesforce, it should be a correct php formatted time interval in the past eg:(10 minutes)
  -l, --limit[=LIMIT]                  Number of records to process when syncing objects [default: 100]
  -f, --force                          Force execution even if another process is assumed running.
  -h, --help                           Display this help message
  -q, --quiet                          Do not output any message
  -V, --version                        Display this application version
      --ansi                           Force ANSI output
      --no-ansi                        Disable ANSI output
  -n, --no-interaction                 Do not ask any interactive question
  -s, --shell                          Launch the shell.
      --process-isolation              Launch commands from shell as a separate process.
  -e, --env=ENV                        The Environment name. [default: "prod"]
      --no-debug                       Switches off debug mode.
  -v|vv|vvv, --verbose                 Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Fetch leads from integration.

**Comment by YosuCadilla** [comment]
app/console mautic:integration:synccontacts -h

Usage:
  mautic:integration:fetchleads [options]
  mautic:integration:synccontacts

Options:
  -i, --integration=INTEGRATION        Fetch leads from integration. Integration must be enabled and authorised.
  -d, --start-date=START-DATE          Set start date for updated values.
  -t, --end-date=END-DATE              Set end date for updated values.
      --fetch-all                      Get all CRM contacts whatever the date is. Should be used at instance initialization only
  -a, --time-interval[=TIME-INTERVAL]  Send time interval to check updates on Salesforce, it should be a correct php formatted time interval in the past eg:(10 minutes)
  -l, --limit[=LIMIT]                  Number of records to process when syncing objects [default: 100]
  -f, --force                          Force execution even if another process is assumed running.
  -h, --help                           Display this help message
  -q, --quiet                          Do not output any message
  -V, --version                        Display this application version
      --ansi                           Force ANSI output
      --no-ansi                        Disable ANSI output
  -n, --no-interaction                 Do not ask any interactive question
  -s, --shell                          Launch the shell.
      --process-isolation              Launch commands from shell as a separate process.
  -e, --env=ENV                        The Environment name. [default: "prod"]
      --no-debug                       Switches off debug mode.
  -v|vv|vvv, --verbose                 Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Fetch leads from integration.

**Comment by YosuCadilla** [comment]
Guess it's just 2 ways to execute the very same command...

**Comment by itsluy** [comment]
Seeing the exact same behavior with the ConnectWise plugin.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by YosuCadilla** [comment]
Sorry @npracht, I can't confirm at this time. As soon as I start migrating clients to M3 I will have more information.

**Comment by npracht** [comment]
Then i close it and i let you comment if you still have the issue then we can re-open it.

**Comment by rashaqqel** [comment]
This is still not working..
php 7.2
centos 7
latest mautic 3.1.1 .... 0 contacts are syncing

**Comment by eojedapilchik** [comment]
Not working only fetches leads, not contacts, and some leads are not fetched also.
Tried with: Suitecrm 7.11.18 and Sugarcrm 8 Professional
php 7.2
Mautic 3.1.1

**Comment by YosuCadilla** [comment]
Probably not very helpful, but you should be running Mautic 3.x with PHP 7.3
Also pay attention to the DB version (see Mautic requirements).
