### ISSUE TITLE
Mautic Points not syncing as expected using SugarCRM Plugin

### ISSUE THREAD

**Issue by YosuCadilla** [mautic/mautic#6140]
What type of report is this: Bug report

## Description:
Using the Sugar plugin with SuiteCRM (theoretically 100% compliant) the Points field does not sync according to what would be expected.

The field currently syncs, just doesn't respect direction of updates:

Result:

   Action     | Action performed on |   Used field  | Syncing | expected | Sync direction 
Edit Points |           Mautic              |     Points      |    NO     |      Yes      | Mautic to Suite
Edit Points |           Mautic              |     Points      |    Yes     |      NO      | Suite to Mautic

## If a bug:
Mautic version: 2.13.1
PHP version: 7.0.x
SuiteCRM version: 7.10.1 -  Sugar Version 6.5.25 (Build 344)

### Steps to reproduce:

TEST 1 - Direction Suite to Mautic (default)
1. Install Sugar plugin (and SuiteCRM) and establish a working link.
2. Add a custom field in sugar for "Mautic Points" and map on Mautic's sugar plugin to "Points"
4. Run the sync command:   php /var/www/.../app/console mautic:integration:synccontacts -i Sugarcrm

TEST 2 - Direction Mautic to Suite
1. Change sync direction in sugar plugin for "Mautic Points" 
2. Run the sync command:   php /var/www/.../app/console mautic:integration:synccontacts -i Sugarcrm

### Log errors: 
Mautic log is empty
No errors in Apache log.

**Comment by YosuCadilla** [comment]
Just found out this will get fixed by #5610

**Comment by sguilly** [comment]
Same issue :

Direction Suite to Mautic : point in suitecrm overwrite point in mautic
Direction Mautic to Suite : nothing append

**Comment by npracht** [comment]
Hi @YosuCadilla @sguilly please test https://github.com/mautic/mautic/pull/7401

**Comment by npracht** [comment]
Fixed when #7401 merged.
