### ISSUE TITLE
Clearing a field's contents in Suite / SugarCRM does not sync (clear) the field in Mautic and vice versa.

### ISSUE THREAD

**Issue by YosuCadilla** [mautic/mautic#6141]
What type of report is this: Bug report

Description:
Using the Sugar plugin with SuiteCRM (theoretically 100% compliant) clearing a field's content does not sync according to what would be expected.

Result:

   Action     | Action performed on | Used field | Syncing | Expected | Sync direction
Clear Field |             Mautic            |   Mobile    |     NO    |      Yes     | Mautic to Suite
Clear Field |              Suite              |   Mobile    |     NO    |      Yes     | Suite to Mautic

If a bug:
Mautic version: 2.13.1
PHP version: 7.0.x
SuiteCRM version: 7.10.1 - Sugar Version 6.5.25 (Build 344)

Steps to reproduce:
TEST 1 - Direction Suite to Mautic (default)
1. Install Sugar plugin (and SuiteCRM) and establish a working link.
2. Map any 2 fields (non numeric, numeric has its own issues) on Mautic's sugar plugin.
3. Run the sync command: php /var/www/.../app/console mautic:integration:synccontacts -i Sugarcrm

TEST 2 - Direction Mautic to Suite
1. Map any 2 (other) fields (non numeric, numeric has its own issues) on Mautic's sugar plugin.
2. Change sync direction in sugar plugin for the selected (mapped) field.
3. Run the sync command: php /var/www/.../app/console mautic:integration:synccontacts -i Sugarcrm

Log errors:
Mautic log is empty
No errors in Apache log.

**Comment by YosuCadilla** [comment]
Just found out this will get fixed by #5610

**Comment by RCheesley** [comment]
Closing as fixed by #5610 some time ago!
