### ISSUE TITLE
remove tag in campaign action does not work

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6144]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Remove a tag by using the campaign action "modify contact's tag" and remove does not work.
Contact still have the tag after going through the campaign.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13
| PHP version | 

### Steps to reproduce:
1. Create a contact and manually add it a tag.
![image](https://user-images.githubusercontent.com/31535432/40724269-f9844140-6420-11e8-904b-c1127c3677ef.png)
2. Add this contact to a segment
3. Create a campaign, start from this segment and add action "modify contact's tag"
4. In the field, remove tag, choose the tag you added to the contact
![image](https://user-images.githubusercontent.com/31535432/40724566-9fee7816-6421-11e8-9ad7-a0f6f8c10119.png)
5. Lauch campaign.
6. Check contact and see that he still has the tag. 
My contact after going through this campaign
![image](https://user-images.githubusercontent.com/31535432/40724659-d54f4b70-6421-11e8-9254-61d74b269bb4.png)
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by xtjoeywx** [comment]
This is very true! Campaigns are not removing tags on v2.13.1.

**Comment by afonseca08** [comment]
I can verify this as a regression. It was working in 2.12.1 and no longer working after upgrading to 2.13.1.

**Comment by kgroveshok** [comment]
Any movement on resolving this? I would say its a pretty crucial part of Mautic and I'm now going to have to work around externally this fault on a number of campaigns .
Thanks

**Comment by kgroveshok** [comment]
There may be a regression on 'set contact' too. Investigating. :-(

**Comment by kgroveshok** [comment]
OK turns out that's the usual segment count not being correct. Panic over. :-)

**Comment by kuzmany** [comment]
Fixed.
Please test and comment  in PR https://github.com/mautic/mautic/pull/6239

**Comment by npracht** [comment]
@xtjoeywx @afonseca08 @kgroveshok could you test #6239 please ?

**Comment by kgroveshok** [comment]
Looks like its been approved... Still want to test? Suppose not?

**Comment by npracht** [comment]
Nope thanks !
