### ISSUE TITLE
Enhance zoho integration to be able to include opportunities or deals 

### ISSUE THREAD

**Issue by vivasc2017** [mautic/mautic#6145]
Q | A | --
Mautic version | N/A
PHP version

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No 
| Feature request? |  Yes
| Enhancement? | NO

## Description:
As a Mautic user I want to bring data from ZOHO Opportunities onto the contact and company objects in Mautic so that I can trigger campaigns based on this data. Also be able to create a opportunity from a mautic campaign or form.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
N/A
 
### Log errors: 

N/A

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
