### ISSUE TITLE
Can't Create Emails - Email Save Dialogue Doesn't Work

### ISSUE THREAD

**Issue by keanlaurens** [mautic/mautic#6146]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When I create an email, it asks what type of email I'd like to select, I select either 'New Template Email' or 'New Segment Email', I select a template add all details needed - when I click 'Save & Close' or 'Apply' it brings up the dialogue again asking what type of email I want to create and when I go through that process again, there are no action buttons ('Save & Close' or 'Apply'  etc).

See video below to see how it plays out:
https://youtu.be/Hy0caXzTzIA

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 5.6.36

### Steps to reproduce:
1. Create Email
2. Click Apply OR Save & Close
 
### Log errors: 

[2018-05-29 08:04:07] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'iam_Mautic.lead_fields' doesn't exist [] []

**Comment by npracht** [comment]
Hello @keanlaurens nothing in the logs ?

**Comment by keanlaurens** [comment]
@npracht I've updated the ticket

**Comment by npracht** [comment]
Did you try to update DB schema ?

**Comment by keanlaurens** [comment]
How do I go about doing that?

**Comment by npracht** [comment]
You're on a open source version or free saas version?

- If self hosted you may read the documentation https://github.com/mautic/mautic#database-schema
- If saas version of mautic, contact the support of mautic

**Comment by keanlaurens** [comment]
It is self hosted. I have run the DB Schema update and am still having the same issue. It worked for one email and now I'm back to the initial issues again.

**Comment by keanlaurens** [comment]
There was actually a security issue, I will send an email to the team shortly.
Thanks for your support Norman (:

**Comment by keanlaurens** [comment]
@npracht just so you know, you have to disable ModSecurity in C-Panel and then all is good!
Helped out @mktg01 on this & it worked for him too.

**Comment by christian-krieg** [comment]
Is there any insight on the root cause of the problem? Disabling the web application firewall doesn't seem to be the most appropriate long-term solution.
