### ISSUE TITLE
Error trying to update via Terminal on Mac

### ISSUE THREAD

**Issue by Fastebiz** [mautic/mautic#6147]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | *

Hi, I've done the first installation of Mautic on MAMP.
Everything has gone well but when I tried to schedule the cron jobs via Terminal of my iMac i notice that the updates were not working. So, i tried to do it manually typing this command line into Terminal:

/applications/mampstack-7.1.17-0/apps/mautic/htdocs/app/console mautic:segments:update

 I got the following errors:

  [Doctrine\DBAL\Exception\ConnectionException]                                     
  An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory  
                                                                                                                                
  [Doctrine\DBAL\Driver\PDOException]               
  SQLSTATE[HY000] [2002] No such file or directory  
                                                                                                        
  [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory

I have not idea of what can I do.... 

Thanks in advance!

**Comment by Fastebiz** [comment]
A little update: I've seen I forgot to put php before the string so I did it today. 

php /applications/mautic/apps/mautic/htdocs/app/console mautic:segments:update

A new error is showing:

[Symfony\Component\Config\Exception\FileLoaderLoadException]                                                                                       
  You have requested a non-existent parameter "mautic.saml_idp_metadata". Did you mean this: "mautic.saml_idp_entity_id"? in /applications/mautic/a  
  pps/mautic/htdocs/app/config/security.php (which is loaded in resource "/applications/mautic/apps/mautic/htdocs/app/config/security.php").         
                                                                                                                                                     
 [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                             
  You have requested a non-existent parameter "mautic.saml_idp_metadata". Did you mean this: "mautic.saml_idp_entity_id"?

I really cannot understand... in security.php file there's written: 

// If SAML is disabled, remove it from the firewall so that Symfony doesn't default to it

I'm almost sure that I'm not behind a firewall.....

**Comment by escopecz** [comment]
This is a configuration issue. The first link when googling the error should help configure database connection correctly:

https://stackoverflow.com/questions/6259424/troubleshooting-no-such-file-or-directory-when-running-php-app-console-doctri

Btw, the database connection config is in app/config/local.php and you'll have to clear the cache to apply the changes in the config.
