### ISSUE TITLE
Html malformed for preference center

### ISSUE THREAD

**Issue by mtahiue** [mautic/mautic#6150]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
The HTML rendered for a preference page is invalid

the code of a preference center begin by :

```
<!DOCTYPE html>
<html>
    <head>
                <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" type="text/css" />
            
    </head>
    <body>
        <form novalidate autocomplete="false" data-toggle="ajax" role="form" name="lead_contact_frequency_rules" method="post" action="/email/unsubscribe/5b0ffeba88a08">

            <div>
        <!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" style="" class=" js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients no-cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths js csstransforms csstransforms3d csstransitions responsejs "><head>
```

they are 2 declarations of the doctype and the `<form>`  opened just after the body tag is :
- conflicting with the rest of the html
- not being closed

they are 2 `</body>` tags at the bottom of the page

```
</body></html>

            </div>
        
    </body>
</html>
```
It seem that the render of the preference center is in conflic somewhere in the corebundle

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.1 and above
| PHP version | 7.0

### Steps to reproduce:
1. create a preference center landing page
2. configure an email with this preference page
3. open the preference page by clicking on the unsubscribe link in the email
4. look at the html source of the page
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
