### ISSUE TITLE
Hubspot Plugin Internal Error 

### ISSUE THREAD

**Issue by afonseca08** [mautic/mautic#6153]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The following appears in the notification UI in Mautic indicating an internal error with the Hubspot integration. I am seeing this appear daily as well as corresponding messages in the logs (see below).

![screenshot 2018-05-31 15 38 06](https://user-images.githubusercontent.com/863419/40812450-ca0a23ba-64ea-11e8-8114-7462de79ba78.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 5.6.33

### Steps to reproduce:
1. Open Mautic dashboard and observe notification UI
2. View app/logs/ for matching error message
 
### Log errors: 

This same error keeps appearing in the log corresponding with the notification in the UI.

See in [mautic root]/app/log/
`[2018-05-31 22:25:07] mautic.ERROR: INTEGRATION ERROR: Hubspot - internal error [] []`

**Comment by lasram** [comment]
I commented the line 166 of file plugins/MauticCrmBundle/Integration/HubspotIntegration.php :
return $fields;
and the error message disappeared.

**Comment by vexersa** [comment]
I'm getting this error too. 

Would @lasram solution not break/halt some functionality of the integration?

**Comment by npracht** [comment]
Hi guys, we're using it for our customers and i've never seen that.
Could you test https://github.com/mautic/mautic/pull/7887 even if i believe this doesn't help for this issue, but at least https://github.com/mautic/mautic/pull/7887 could be merged faster with your help.
Thanks !

**Comment by mundadashri** [comment]
We also see this error intermittently.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by mjml1982** [comment]
Hi,
@npracht  We have also seen this error in Mautic 3.0.2, we are using PHP7.3.

Any help would be highly appreciated.

Thanks.

**Comment by RCheesley** [comment]
@mjml1982 can you confirm if this persists in 3.2.1? If so, is it happening on any specific action at all?

**Comment by HermanMonteiro** [comment]
Does anyone have any updates about this bug? I have the same problem
