### ISSUE TITLE
Social Login Issue with manual copy of form to landing page

### ISSUE THREAD

**Issue by architjoshihs** [mautic/mautic#6154]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
When we are using social login with manual copy of form on a landing page, popup of login does not appear.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 7.0

### Steps to reproduce:
1. Create a simple social login form after integrating facebook plugin
2. copy this form using manual copy and add to landing page and save the landing page
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @architjoshihs !
It seems it is fixed in 2.13.0 thanks to https://github.com/mautic/mautic/pull/5758

Could you try applying this PR or simply update your mautic version to current version (2.13.1) ?

Thanks !

**Comment by architjoshihs** [comment]
Its still not working.

1. Create a normal form with social login, let say facebook
2. Copy this form to landing page. Here the social login does not function even in latest mautic version.

**Comment by architjoshihs** [comment]
When adding a form manually using html code to any landing page or integrating in 3rd party website, it doesn't work.

**Comment by npracht** [comment]
@kuzmany do you have an idea why that happens ?

**Comment by kuzmany** [comment]
I think It's related to @Enc3phale changes https://github.com/mautic/mautic/pull/6665 and another one. This change move logic JS to head and all js in head waiting for loading all html stuff. I got same issue with one my plugin, I have to add window.load condition. 
But I don't tested, just quick review.

@Enc3phale Can you look on it?

**Comment by npracht** [comment]
The issue was opened before @Enc3phale PR. But if @Enc3phale you have an opinion :)

**Comment by kuzmany** [comment]
I think It's too less information. 
Any logs, browser console?
Somebody need re-test, because can be anything (form cache?...)

This issue report is incomplete.
