### ISSUE TITLE
Contact engagements chart incorrect data when not UTC

### ISSUE THREAD

**Issue by mebeingken** [mautic/mautic#6157]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The Engagements chart on the contact page does not reflect the true points and engagements unless UTC timezone is set on the user account profile as demonstrated in the screenshots below:

UTC set:
![screen shot 2018-06-03 at 11 43 49 am](https://user-images.githubusercontent.com/19980603/40890004-7b5d9fb2-6724-11e8-9f63-a70086a1ff57.png)
Los Angeles set:
![screen shot 2018-06-03 at 11 44 14 am](https://user-images.githubusercontent.com/19980603/40890009-7e984678-6724-11e8-95c6-349adf0bdeff.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.27

### Steps to reproduce:
1. Using a Points Action of some kind, increment a contacts point value
2. Set User Account Timezone to UTC
3. View the contact (https://bigtiny.world/m/s/contacts/view/[ID] and note the chart data
4. Set User Account Timezone to Los Angeles
5. View the contact (https://bigtiny.world/m/s/contacts/view/[ID] and note the chart data
 
### Log errors: 

None

**Comment by dsp76** [comment]
Still in 2.16.1

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
