### ISSUE TITLE
Hover help doesn't disappear

### ISSUE THREAD

**Issue by mebeingken** [mautic/mautic#6158]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
In specific circumstances, the hover help (black box with white text) for Action options when building a campaign, do not disappear as show below.  

![screen shot 2018-06-03 at 2 13 49 pm](https://user-images.githubusercontent.com/19980603/40891408-ca3834e8-6739-11e8-839c-3e4bd6d941f7.png)

![screen shot 2018-06-03 at 2 14 03 pm](https://user-images.githubusercontent.com/19980603/40891410-ce951d9e-6739-11e8-95e3-8076fce1b307.png)

![screen shot 2018-06-03 at 2 14 13 pm](https://user-images.githubusercontent.com/19980603/40891412-d32c138a-6739-11e8-94dd-177f8edbd4f0.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.27

### Steps to reproduce:
1. Create a new campaign and open the campaign builder
2. Select any source ( I used a segment )
3. Hover of the bottom icon and click the plus symbol to add a new Decision/Action/Condition
4. Click the Select button on Action, clicking near the center of that button -- after clicking, do not move the mouse.
5. This presents a dropdown of options, and the fifth item will be highlighted by the mouse
6. Still without moving the mouse, start typing to narrow the selections ( eg: "se" to send an email)
7. Now move the mouse away from the fifth item, to select Send an email.  The hover help from the fifth item will still be present, along with the newly selected item.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
