### ISSUE TITLE
OneSignal integration - disabling 'init' js on specified pages

### ISSUE THREAD

**Issue by demondehellis** [mautic/mautic#6164]
| Q  | A
| ---| ---
| Bug report? | no
| Feature request? | no
| Enhancement? | yes

## Description:
In some cases, we don't want disturbing users with the OneSignal popup on every page. Also, in some cases we want users subscribed to notifications from their authorized accounts only, not from every site page. 

For that, we currently use own OneSignal init snippet with GTM in order to show subscription popup on selected pages only.

But there is no ability in OneSignal integration to disable initialization script that fire with mtc.js and popup is displaying on every page. 

## Possible solutions:

1. Creating a text field in OneSignal integration where mautic user able to add excluded/included path.

2. Adding a middleware in order to have the ability to control js added by plugins/bundles/integrations.

3. Moving OneSignal integration outside of the core notification bundle. This way the notification bundle should work with OneSignal using mautic api/events interfaces and we'll be able to disable it and write a similar one for custom needs. It'll add flexibility to the system.

**Comment by digitall-it** [comment]
There's another possible, more broad solution in issue #7633.

**Comment by digitall-it** [comment]
If I would happen to code this feature, would you accept it?

**Comment by RCheesley** [comment]
@digitall-it please do make a PR if this is still relevant in Mautic 3.x !

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
