### ISSUE TITLE
Message Cronjob error to terminal

### ISSUE THREAD

**Issue by deyvsonaguiar** [mautic/mautic#6165]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

Please, why this messages in my log? And How solve?

## Description:
I send command manually on terminal for send emails. 

## If a bug:

see the log

| Q   | A
| --- | ---
| Mautic version |  2.13
| PHP version | 

### Log errors: 

PHP Notice: Undefined index: substitution_data in /var/www/clients/client1/web3 /web/app/bundles/EmailBundle/Swiftmailer/Transport/SparkpostTransport.php on lin e 217
PHP Notice: Undefined index: substitution_data in /var/www/clients/client1/web3 /web/app/bundles/EmailBundle/Swiftmailer/Transport/SparkpostTransport.php on lin e 217
PHP Notice: Undefined index: substitution_data in /var/www/clients/client1/web3 /web/app/bundles/EmailBundle/Swiftmailer/Transport/SparkpostTransport.php on lin e 217
PHP Notice: Undefined index: substitution_data in /var/www/clients/client1/web3 /web/app/bundles/EmailBundle/Swiftmailer/Transport/SparkpostTransport.php on lin e 217

**Comment by luizeof** [comment]
Hi @deyvsonaguiar please provide more information about your error.

PHP version? Did you configure an SMTP server?

**Comment by deyvsonaguiar** [comment]
PHP Version 7.0.27-0+deb9u1
--

**Comment by nethunter** [comment]
Having the same error, with Sparkpost. Any idea what it is?
