### ISSUE TITLE
Not able to provide role based access permission to campaigns

### ISSUE THREAD

**Issue by architjoshihs** [mautic/mautic#6166]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this: 

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
Not able to provide role based access permission to campaigns. Currently all campaign are visible to all user. Role based permission does not include view own, edit own, publish own etc permissions. How could we add this.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13
| PHP version | 7.0

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by MayaMathura** [comment]
+1

**Comment by Noa83** [comment]
@architjoshihs and @MayaMathura , check this PR and see if it fills your needs.  [#6240](https://github.com/mautic/mautic/pull/6240)
