### ISSUE TITLE
Hubspot Contacts Search API Error

### ISSUE THREAD

**Issue by afonseca08** [mautic/mautic#6171]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The following appears in the notification UI in Mautic indicating an "Unknown Contacts Search API failure". I've seen this a couple of days in a row now along with the corresponding messages in the log (see below). 
![screenshot 2018-06-05 11 31 20](https://user-images.githubusercontent.com/863419/40995869-3ab0e0e0-68b5-11e8-9339-64a148101506.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 5.6.33

### Steps to reproduce:
1. Open Mautic dashboard and observe notification UI
2. View app/logs/ for matching error message
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

This same error keeps appearing in the log corresponding with the notification in the UI.

See in [mautic root]/app/log/mautic_prod-2018-06-05.php

`[2018-06-05 13:45:46] mautic.ERROR: INTEGRATION ERROR: Hubspot - Unknown Contacts Search API failure: [500] {"status":"error","message":"internal error","correlationId":"85308f70-68ab-4cd4-998a-f3e3324c99e9","requestId":"74da77af-81cd-407c-8f8a-46b201767c74"} [] []
`

**Comment by npracht** [comment]
We have brought several fixes to Hubspot plugin since 2018. I'll close it and feel free to comment if you can still reproduce it on 3.0.1.
