### ISSUE TITLE
Can not create fields via API

### ISSUE THREAD

**Issue by Flavio1998** [mautic/mautic#6172]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When I send this request `curl -i -H"Content-Type: application/x-www-urlencoded" -XPOST admin:password@192.168.5.186/api/fields/contact/new -d"label=Nummer&type=text&group=core&alias=nummer&isRequired=false&object=contact"` I get the this response: `{
    "errors": [
        {
            "code": 400,
            "message": "label: A label is required.",
            "details": {
                "label": [
                    "A label is required."
                ]
            }
        }
    ],
 . . . .`.
I don't know why because I send a value for a label. 
Furthermore I only get the error message when using cURL on the windows cmd, in the Ubuntu shell everything works fine. This is still a problem because I need to send these commands over a windows cmd. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.0

### Steps to reproduce:
1. Open cmd
2. Type in `curl -i -H"Content-Type: application/x-www-urlencoded" -XPOST admin:password@192.168.5.186/api/fields/contact/new -d"label=Nummer&type=text&group=core&alias=nummer&isRequired=false&object=contact"`
3. Get an error message

### Log errors: 
There are no relevant data in the log, only some email errors. Which is too much effort to anonymize, to post it here. 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi @Flavio1998 is it still an issue in latest version ? Thanks.
