### ISSUE TITLE
Unable to save segment emails / landing pages

### ISSUE THREAD

**Issue by sunshinetainted** [mautic/mautic#6178]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When I try to create a 'New Segment Email' or 'New Template Email', after filling in all the required fields if I click on 'Save & Close' or 'Apply', the action buttons go 'grey'/inactive and nothing happens after. Here is a screen shot. 

![image](https://user-images.githubusercontent.com/31520928/41094193-ba444b82-6a4d-11e8-9943-e47a2651acd7.png)

I see the following error message in the console log: 

`new?mauticUserLastActive=1&mauticLastNotificationId=:1 Failed to load resource: the server responded with a status of 403 (Forbidden)`

I am unable to find a solution to this, any help would be greatly appreciated. Thanks
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.30

### Steps to reproduce:
1. Create New Segment Email
2. Save & Close / Apply
 
### Log errors: 
I dont have any errors in Mautic Error logs. 
I am not certain if these are relevant, but the Web server's logs show this: 

```
[***] - - [07/Jun/2018:12:17:54 +0200] "GET /crm.***/s/ajax?action=email:getBuilderTokens&_=1528366673689&mauticUserLastActive=1&mauticLastNotificationId= HTTP/1.0" 200 2145 "https://crm.***.com/crm.***/s/emails/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36"
[***] - - [07/Jun/2018:12:17:54 +0200] "GET /crm.***/s/ajax?action=email:getBuilderTokens&_=1528366673688&mauticUserLastActive=1&mauticLastNotificationId= HTTP/1.0" 200 2145 "https://crm.***.com/crm.***/s/emails/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36"

```
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by sunshinetainted** [comment]
I am closing this issue, as it was a server issue and not Mautic related. Apologies for the inconvenience.

**Comment by mark2creative** [comment]
Hi sunshinetainted - can you tell me what server error was causing this please? I have exactly the same issue and cannot work it out.

**Comment by sunshinetainted** [comment]
Hi @mark2creative, the problem came from ModSecurity installed on the server, which was generating 403 errors. Disabling it solved the problem. Also on slack : https://mautic.slack.com/archives/C03BVAZB0/p1532724032000297

**Comment by sparora29** [comment]
I am also same issue on shared hosting,how can i solve.

**Comment by cleomarbrdias** [comment]
> Olá @ mark2creative , o problema veio do ModSecurity instalado no servidor, que estava gerando 403 erros. Desativá-lo resolveu o problema. Também disponível: https://mautic.slack.com/archives/C03BVAZB0/p1532724032000297

não conseguir visualizar essa pagina, porém não tenho ModSecurity ativado e obtive o mesmo erro.

**Comment by MarkerB** [comment]
Disabling mod_security had no affect for me.  I found that I had to disable Cloudflare's PHP **Web Application Firewall** for Mautic, or I'd get the 403 errors when trying to save an Email.

**Comment by christian-krieg** [comment]
For the records: I also asked this in #6146

Is there any insight on the root cause of this problem? Particularly, it would be interesting which web application firewall (WAF) rules are violated, and why. Then, it would be interesting how to avoid the WAF being triggered. Disabling the WAF does not seem to be the way to go for me...
