### ISSUE TITLE
Can't download/ delete theme in mautic 2.13.1

### ISSUE THREAD

**Issue by mbasheer** [mautic/mautic#6189]
### Steps to reproduce:
1.  go to theme 
2.  downlaod/ delete existing  theme or newly uploaded theme.
3. gets an error like 'Theme is not found'. 

I can install new theme without any issue but some problem in downlaod/ delete the theme. I can't

this is the config.json file. 
{
  "name": "test",
  "author": "Mautic team based on a theme by Sendwithus",
  "authorUrl": "https://www.sendwithus.com/resources/templates/oxygen",
  "features": [
    "page",
    "email",
    "form"
  ]
}

**Comment by alanhartless** [comment]
Hi!

This is already fixed in https://github.com/mautic/mautic/pull/6010 and will be part of the next release.
