### ISSUE TITLE
Send webhook doesn't properly encode email address with '+' symbol

### ISSUE THREAD

**Issue by afonseca08** [mautic/mautic#6197]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When a webhook action is sent from a campaign that includes the contact's e-mail address token, if the e-mail address contains a '+ symbol, the symbol comes across as a space instead.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 5.6.33

### Steps to reproduce:
1. Create a contact with an e-mail address that includes a '+' symbol. ie. 'me+1@home.net'
2. Create a segment and add this contact so we can include in a new campaign.
3. Create a campaign for that segment that includes a "Send a webhook" action, method set to GET.
4. In the data, include the contact's e-mail address using the token {leadfield=email}
5. On the server side, check the e-mail address that is received, 'me 1@home.net' does not match the contact's e-mail address, 'me+1@home.net'.
 
### Log errors: 
N/A

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi @afonseca08 can you test https://github.com/mautic/mautic/pull/7616 please ?

**Comment by npracht** [comment]
Closed by #7616
