### ISSUE TITLE
form submission report shows twice the contact if more than 1 company

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#6198]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

## Description:
The Form Submissions Report shows a table with all the submission. If you have a contact with 2 companies attached submitting the form, then the contact is shown twice even if he has submitted only once the form.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13
| PHP version | NA

### Steps to reproduce:
1. Create a contact with 2 companies
2. Submit a form with this contact (use same email address)
3. Create a form submissions report with table > see that the contact is displayed twice. Each time with a different company

**Comment by kuzmany** [comment]
Maybe something missing, but I cannot reproduce.
I have one result and one report line. Tested on last staging.
Can you share screen of you form and report settings?

**Comment by npracht** [comment]
![capture d ecran 2018-07-03 a 13 03 08](https://user-images.githubusercontent.com/14075239/42216392-f75dda46-7ec1-11e8-98ab-94cceb55dd8b.png)
![capture d ecran 2018-07-03 a 13 04 47](https://user-images.githubusercontent.com/14075239/42216393-f779bb9e-7ec1-11e8-9a92-c4b4807b7587.png)
![capture d ecran 2018-07-03 a 13 05 19](https://user-images.githubusercontent.com/14075239/42216394-f8a29e5a-7ec1-11e8-866d-fed7257b26c3.png)

**Comment by kuzmany** [comment]
Still cannot reproduce
Please share your report setting

![image](https://user-images.githubusercontent.com/462477/42233410-c8d0c2e4-7ef1-11e8-9b2f-22c37b2e21ee.png)

**Comment by npracht** [comment]
![capture d ecran 2018-07-04 a 09 17 11](https://user-images.githubusercontent.com/14075239/42262262-12e2179c-7f6b-11e8-98bb-a02a74111df7.png)

**Comment by kuzmany** [comment]
Confirmed.

**Comment by kuzmany** [comment]
This is form submission report, but you choose you want see submission with leads and his company info.
Then I think the results it 's correct.

Your query means:  Select form submission with contact info and his company info.  
What do you expect from that table? What kind of info?

**Comment by kuzmany** [comment]
Working on new Calculated columns by group_concat which allow in this case display as you expect in one line

**Comment by npracht** [comment]
True that !
Thanks :)
