### ISSUE TITLE
Getting Error creating Database for Installation

### ISSUE THREAD

**Issue by wptechprodigy** [mautic/mautic#6213]
I need some guide installing mautic manually.

I can't find it on my Softacoulous app installer, so I opted for manual installation.

I get a big error report which I have attached a screenshot. Here's the error report:

An error occurred while attempting to install the data: An exception occurred while executing 'CREATE TABLE newsltweets (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, page_id INT DEFAULT NULL, asset_id INT DEFAULT NULL, is_published TINYINT(1) NOT NULL, date_added DATETIME DEFAULT NULL, created_by INT DEFAULT NULL, created_by_user VARCHAR(255) DEFAULT NULL, date_modified DATETIME DEFAULT NULL, modified_by INT DEFAULT NULL, modified_by_user VARCHAR(255) DEFAULT NULL, checked_out DATETIME DEFAULT NULL, checked_out_by INT DEFAULT NULL, checked_out_by_user VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, media_id VARCHAR(255) DEFAULT NULL, media_path VARCHAR(255) DEFAULT NULL, text VARCHAR(280) NOT NULL, sent_count INT DEFAULT NULL, favorite_count INT DEFAULT NULL, retweet_count INT DEFAULT NULL, lang VARCHAR(255) DEFAULT NULL, INDEX IDX_BF1A3C9E12469DE2 (category_id), INDEX IDX_BF1A3C9EC4663E4 (page_id), INDEX IDX_BF1A3C9E5DA1941 (asset_id), INDEX newsltweet_text_index (text), INDEX newslsent_count_index (sent_count), INDEX newslfavorite_count_index (favorite_count), INDEX newslretweet_count_index (retweet_count), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB': Index column size too large. The maximum column size is 767 bytes.

Perhaps someone could help me out.

**Comment by AkkuFresh** [comment]
Here is the solution to your problem: https://github.com/mautic/mautic/issues/6693
