### ISSUE TITLE
Clone an e-mail to a segment - error

### ISSUE THREAD

**Issue by andrerocha4freemarketing** [mautic/mautic#6216]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

**## Description:**
Hello, guys! I'm new here and I searched before reporting this issue and I didn't find anything. So, here it is:
I already have an email (template email - not for segment) and I want to clone it and choose "new segment email" but when I save the new email it returns me a error 500.
Every email returns me the same error

Sorry for my English.
Thanks,
André Rocha

**## If a bug:**

| Q   | A
| --- | ---
| Mautic version | Last version
| PHP version | Last php 7.

**### Steps to reproduce:**
1. Email > Clone > Save >> erro
2. 
 
**### Log errors:** 
None
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
@andrerocha4freemarketing I'm guessing this issue is no longer a problem but if it is please feel free to re-open.
