### ISSUE TITLE
Import data stopped working in new version - throws PHP Exception

### ISSUE THREAD

**Issue by mellsaid** [mautic/mautic#6217]
What type of report is this:

| Bug report? | 

## Description:
When importing data, data doesn't get imported - progress stay at 0 and I receive a php exception  on the latest mautic release. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v 2.13.1
| PHP version | 7.0.28

### Steps to reproduce:
1. Import data in csv
2. Run in background or browser
3. Counter will always be 0% and won't update
 
### Log errors: 
[2018-06-14 09:59:33] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getId() on null" at /home/x/public_html/x/app/bundles/LeadBundle/Model/LeadModel.php line 607 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getId() on null at /home/x/public_html/x/app/bundles/LeadBundle/Model/LeadModel.php:607)"} []

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mellsaid** [comment]
We have tried the same on another instance which was recently upgraded - and have received the same error. 

Older versions didn't have this issue - Seems to be related to new one

**Comment by mellsaid** [comment]
Any thoughts on this?

**Comment by mellsaid** [comment]
@npracht @alanhartless any thoughts on this one? Currently stuck as can't add any data.

**Comment by npracht** [comment]
Can you share a your file?
Cause i cannot reproduce....

**Comment by christian-fries** [comment]
I had the exact same issue. The problem was, I tried to map the property stage but instead of having the id of the stage in the csv, I had the name of the stage in the file. After replacing the name with the id, the import worked.
