### ISSUE TITLE
CheckBox in SugarCRM not mapping in Mautic

### ISSUE THREAD

**Issue by corycast** [mautic/mautic#6223]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | Yes
| Enhancement? | 

## Description:
We currently have checkbox options inside Sugar that was created on the lead level.  We are choosing checkbox option for optins.  

![screen shot 2018-06-12 at 3 15 36 pm](https://user-images.githubusercontent.com/40242903/41476528-cd4006ca-708f-11e8-9f59-2655c1a48bf3.png)
![screen shot 2018-06-12 at 3 08 18 pm](https://user-images.githubusercontent.com/40242903/41476529-cd58e262-708f-11e8-88ea-c63e4e32004f.png)

After going into Mautic and going to contact mapping.  None of the checkboxes that we created are available to be mapped. Mautic offeres a boolean as a checkbox alternative.  I have also gone into sugar and created the same boolean field.  

Still not available for mapping.

Please help.
Thanks

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13
| PHP version | 7.0.3

### Steps to reproduce:
1. Create checkbox field inside sugar and apply to layout
2. Create custom field inside mautic with same parameters
3. Go to Sugar plugin inside mautic and go to contact mapping
4. The checkbox field will not be available for mapping.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @corycast !
This thing has already been pointed out.
Please test PR https://github.com/mautic/mautic/pull/5896 that solved this issue (i've already tested it, a second test would be appreciated).

Thanks !

**Comment by corycast** [comment]
Hello @npracht,

I hope all is well.  We will run this testing today or tomorrow. 

However, will this allow us to map any custom checkbox field or only the unsubscribes?
We need to be able to map custom checkbox fields.

Thanks again,
Cory

**Comment by npracht** [comment]
All boolean fields ;)

**Comment by corycast** [comment]
Hello @npracht 

Thanks.  We tried to run the test but our intergation doesnt have the same fields as the test.  What we need to know is how do we install the latest or the beta version of the integration that already has the updates that need to be tested. Right now our plugin doesn't show the option that need to be tested, so we need to either download the beta, or upload some new code... we need to find out how and what.

Can you please help? thanks again

Cory

![screen shot 2018-06-18 at 11 36 14 am](https://user-images.githubusercontent.com/40242903/41547172-744fcf04-72ed-11e8-9d96-2b88fbc83d39.png)

**Comment by npracht** [comment]
You need to apply the existing code of the PR on your open source version.

**Comment by npracht** [comment]
Please contact on slack if you need more information on how to do.

**Comment by corycast** [comment]
@npracht  which code@ apply the existing code of the PR on your open source version.

**Comment by corycast** [comment]
Hello we did the update but are still experiencing the same problem.
________________________________
