### ISSUE TITLE
add date display configuration for tokens

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#6225]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
It would be awesome that in the configuration you can manage the way you want to display dates in the email using tokens with date for instance.

eg: Then we would prefer this format in the PHP notation: l, F j, Y

**Comment by kuzmany** [comment]
Do you wanna add  for just for contactfield tokens?

`{contactfield=customdate}`

**Comment by npracht** [comment]
Yes, and company token ?

Do you think about something else ?

**Comment by kuzmany** [comment]
Nope. Working on it ;)

**Comment by kuzmany** [comment]
Let's test

https://github.com/mautic/mautic/pull/6237
