### ISSUE TITLE
Tracking pixel do not load on email, conflict with Queue Settings-beanstalkd 

### ISSUE THREAD

**Issue by elwininc** [mautic/mautic#6227]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
when you open  queue settings- beanstalked, the tracking pixel can not be load on sent email.the tracking do not work

logs display
[2018-06-16 14:45:15] mautic.CRITICAL: Uncaught PHP Exception Pheanstalk\Exception\ConnectionException: "Socket error 111: Connection refused (connecting to localhost:11300)"

the beanstalkd do not work
after disable  quene setting, the tracking pixel fine

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
