### ISSUE TITLE
Error - Filters Segments update it does not work.

### ISSUE THREAD

**Issue by GetLoGiN** [mautic/mautic#6228]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
When adding segments within the "filters" tab, once you click on Apply or Save and close, the segments are not saved, it is as if the filter did not work correctly.

What makes it necessary to add segments again and still does not allow adding multiple segments within the filter.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 5.6.36

### Steps to reproduce:
1. Go Mautic - Segments - Edit Segment
2. Now go Tab - Filters - Segment Membership - Including
3. Now add you all Segments and click on Apply or Save and close.
 
### Example procedure error:
Video: https://streamable.com/s/w0rtd/gdquas

**Comment by npracht** [comment]
Hello @GetLoGiN do you have error message in your logs ?

**Comment by orangeattitude** [comment]
Hi  @npracht, 
I work together whit @GetLoGiN 

The Mautic error Log are empty.

When I add many segments into Filters - Segments and click Apply the page made 2 conections to libraries.js?v9fb672d5  

You can look this at [http://nimb.ws/4OSRd9]()

**First Conection**

Name: **6?mauticUserLastActive=1&mauticLastNotificationId=** (my segment ID are 6)
Status: 200
Response: [https://gist.github.com/orangeattitude/4022243986e119358801419a370dc2dc#file-gistfile1-txt]()

**Second Conection**

Name: **ajax?action=page:getBuilderTokens&_=1529596959647&mauticUserLastActive=3&mauticLastNotificationId=**
Status: 200
Response: [https://gist.github.com/orangeattitude/463ebeebe3a1450ad9eb4853e5f5722d#file-gistfile1-txt]()

those are the only messages that we can identify
I hope it helps to solve the problem

Thanks in adance!

**Comment by GetLoGiN** [comment]
Hi @npracht,
The Mautic error Log are empty.

When I add many segments into Filters - Segments and click Apply the page made 2 conections to libraries.js?v9fb672d5

You can look this at http://nimb.ws/4OSRd9

First Conection

Name: 6?mauticUserLastActive=1&mauticLastNotificationId= (my segment ID are 6)
Status: 200
Response: https://gist.github.com/orangeattitude/4022243986e119358801419a370dc2dc#file-gistfile1-txt

Second Conection

Name: ajax?action=page:getBuilderTokens&_=1529596959647&mauticUserLastActive=3&mauticLastNotificationId=
Status: 200
Response: https://gist.github.com/orangeattitude/463ebeebe3a1450ad9eb4853e5f5722d#file-gistfile1-txt

those are the only messages that we can identify
I hope it helps to solve the problem

Thanks in advance!

**Comment by npracht** [comment]
Closed in favor of https://github.com/mautic/mautic/issues/5026 (duplicate)

**Comment by GetLoGiN** [comment]
Hello! any update for this bug?

**Comment by ayofalo** [comment]
Hello everyone. Please, does anyone know how to automatically load contacts into your  mautic segments from opt-in forms. My mautic segment doesnt receive contacts from my opt-in (Thrive leads). I have already made the API connection. But the segments dont upload.
