### ISSUE TITLE
Internal IP in sent E-Mails

### ISSUE THREAD

**Issue by Flavio1998** [mautic/mautic#6230]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When I place an image in an e-mail, the path to the image leads to my local IP where Mautic is installed. 
But I have a Domain configured. When I open the e-mail on my phone, I can't see the images. Also the link isn't secured with https.
![grafik](https://user-images.githubusercontent.com/35522459/41596049-4f0ab48e-73c9-11e8-99a1-3ca1fa484b99.png)

The domain is fully set up and works.
![tempsnip](https://user-images.githubusercontent.com/35522459/41596273-16de03c6-73ca-11e8-97f9-4411445f1531.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.13.1 
| PHP version | 7.0.30-0

### Steps to reproduce:
1. Mautic installation with domain
2. Send e-mail with images
3. Look at e-mail via phone
4. Images can't be displayed

**Comment by dongilbert** [comment]
Thanks for the bug report.

Is this when sending the email through the command line? Or when sending it while you're logged into Mautic and processing the email directly? Through a Campaign or through a Segment email?

If it's through the console (or a Campaign being processed by the `mautic:campaign:trigger` cron task), the URL is taken from the `site_url` configuration option in your `app/config/local.php` file. 

If it's through the browser (such as a Segment email or one off test email), the domain to prefix to those links is taken from the actual URL you have in your browser's location bar. So if you're logged in to `http://192.168.5.186`, then that will be the URL used.

As for "not secured with HTTPS", it's the same issue. It will only use HTTPS based on those same two scenarios.

Can you provide some more information if none of that answers your question?

**Comment by Flavio1998** [comment]
Thanks for your feedback. I was sending the emails through the browser. 
After changing the `site_url `in the configuration and restarting the webserver it worked perfectly.
