### ISSUE TITLE
Filter contacts by tags in reports

### ISSUE THREAD

**Issue by FranSanchezOria** [mautic/mautic#6231]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| Bug report? |  No
| Feature request? | Yes
| Enhancement? | 

## Description:
This will help to filter contacts with tags.

This feature has been requested several times and all issues where closed without explanation. I would like to re-open the discussion.

### Steps to reproduce:

1. Create new Report in Reports page
2. Select Contacts in "Data Source" drop down in Details tab
3. Click Add filter button to add new filter
4. Select Tags in "Column" select box and add required options
5. Save the report

**Comment by RCheesley** [comment]
@FranSanchezOria we do not seem to have a PR associated with this issue, so I am going to close the issue down. If you wish to make a PR there is guidance here: https://contribute.mautic.org/contributing-to-mautic/developer
