### ISSUE TITLE
I have error when install database

### ISSUE THREAD

**Issue by cmdntd** [mautic/mautic#6232]
An error occurred while attempting to install the data: An exception occurred while executing 
>'CREATE TABLE tweets (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, page_id INT DEFAULT NULL, asset_id INT DEFAULT NULL, is_published TINYINT(1) NOT NULL, date_added DATETIME DEFAULT NULL, created_by INT DEFAULT NULL, created_by_user VARCHAR(255) DEFAULT NULL, date_modified DATETIME DEFAULT NULL, modified_by INT DEFAULT NULL, modified_by_user VARCHAR(255) DEFAULT NULL, checked_out DATETIME DEFAULT NULL, checked_out_by INT DEFAULT NULL, checked_out_by_user VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, media_id VARCHAR(255) DEFAULT NULL, media_path VARCHAR(255) DEFAULT NULL, text VARCHAR(280) NOT NULL, sent_count INT DEFAULT NULL, favorite_count INT DEFAULT NULL, retweet_count INT DEFAULT NULL, lang VARCHAR(255) DEFAULT NULL, INDEX IDX_AA38402512469DE2 (category_id), INDEX IDX_AA384025C4663E4 (page_id), INDEX IDX_AA3840255DA1941 (asset_id), INDEX tweet_text_index (text), INDEX sent_count_index (sent_count), INDEX favorite_count_index (favorite_count), INDEX retweet_count_index (retweet_count), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by mikejon-es** [comment]
See this issue https://github.com/mautic/mautic/issues/5647

**Comment by npracht** [comment]
I'll close it in favor of #5647
