### ISSUE TITLE
Connect Mautic to Thrivethemes through API brings error

### ISSUE THREAD

**Issue by Danicoco** [mautic/mautic#6235]
Good day,

I tried to connect Mautic to Thrivethemes for wordpress but after inputing both the secret key and public key and API URL. Mautic loads a 404 page.

Please help me with this

**Comment by npracht** [comment]
Hello @Danicoco i think you tried to connect Thrivethemes to mautic right? Because there is not plugin about that in mautic.
If yes, i think you should contact support of Thrivethemes.

**Comment by escopecz** [comment]
Also try clearing Mautic's cache.
