### ISSUE TITLE
Email click thru data not being saved

### ISSUE THREAD

**Issue by KaKite** [mautic/mautic#6236]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | 
| Enhancement? | 

## Description:
When I create a campaign that has an email that includes links to URL's the tracking data is NOT saved in Mautic when one of those links is clicked. The URL's appear to be formatted correctly by the underlying Mautic code (that is URL's are replaced with mautic URL's and a tracking hash) AND the redirection from my Mautic site to the correct URL works correctly, however there is NO record of the URL having been clicked in the Channels -> Emails -> (select the email) -> Click Counts tab

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.13.1
| PHP version |  7.0.30

### Steps to reproduce:
1. Create a Campaign with an email that has links to various URL's. 
2.  Send the Campaign
3. Open the email you receive. Check that the URL's within the email are formatted correctly, they should contain your Mautic instance URL and a tracking hash
4. Click on any/all of the links in the email - ensure that you are redirected to the correct URL
5.  In Mautic go to Channels -> Emails -> (select the email) -> Click Counts tab and see if any/all of your clicks have been recorded correctly
 
### Log errors: 

No relevant/related errors in the log file

**Comment by KaKite** [comment]
Hey npracht, thanks for the heads up on #6229, will apply and comment on those PRs success/failure. If those fixes work will close this issue

Cheers

**Comment by gacott** [comment]
We are seeing this issue as well, tested in both PHP 7.0 and 7.1. 100% reproducible.

**Comment by escopecz** [comment]
Closing as there was no follow up for several months.

**Comment by escopecz** [comment]
Closing as there was no follow up for several months.
