### ISSUE TITLE
Force https with .htaccess?

### ISSUE THREAD

**Issue by andjules** [mautic/mautic#6249]
Q | A
-- | --
Bug report? | Yes
Feature request? | No
Enhancement? | No

## Description:
SSL installed and https://mymautic.example.com in site url configuration.
If I type https://mymautic.example.com everything works
**HOWEVER**, if simply type mymautic.example.com in my browser, it loads /s/login insecurely (http://), without forcing https://
Interestingly, it won't log me in when loaded insecurely (http://), which is good, but ultimately, the best UX would be to simply force https:// if the site url (in config) is https://

Tried adding rules to force https:// in _.htaccess_ but no luck.
Advice? Anyone?

Q  | A
-- | --
Mautic | 2.13.1  
PHP | 7.0.30

**Comment by GetLoGiN** [comment]
Hello, make sure you have the https protocol configured in the configuration, then clear the directory **./public_html/app/cache**

**Comment by andjules** [comment]
Worked, thank you.
