### ISSUE TITLE
Mautic self hosted takes forever to run a simple campaign

### ISSUE THREAD

**Issue by SmittyTan** [mautic/mautic#6251]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
It is taking forever just to run simple campaign to add a tag to contacts

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Yes
| PHP version | No

I am not sure what is mautic version vs php version

### Steps to reproduce:
1. Setup a campaign to add a tag to all the existing contact
2. Publish the campaign
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by SmittyTan** [comment]
btw, I hosted using bitnami in azure

**Comment by fphunzz** [comment]
I've used Bitnami in a VM from Azure, had lots of performance issues like sending broadcasts and even page loading speed. Now trying to migrate to another install.

Some users said Bitnami install isn't optimized and doesnt look like a good option to go. In my opinion, its not a bug but a bad configuration by Bitnami.

**Comment by npracht** [comment]
Hi @SmittyTan it is a configuration issue more than a real issue.
Please come and chat on slack.

Thanks !
