### ISSUE TITLE
Contact not updating

### ISSUE THREAD

**Issue by RashmiSingla9** [mautic/mautic#6253]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 1
| Feature request? | 
| Enhancement? | 

## Description:
I am trying to update a contact using mautic REST API with HTTP PATCH method and getting old contact details in response with updates reflected. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0

### Steps to reproduce:
1. <mautic installation path>/api/contacts/ID/edit
2.  patch request parameters 
city:Cary1
firstname:Bjorn
 
### Log errors: 

No errors

**Comment by npracht** [comment]
Hello @RashmiSingla9 what is issue? This is too short to help.
If it is more about questions, advices, please refer to the forum or slack.

Thanks!
