### ISSUE TITLE
MysqliStatement.php on line 179 - memory exhausted

### ISSUE THREAD

**Issue by StarAle** [mautic/mautic#6255]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | No
| Enhancement? | Maybe

## Description:
New installation from Softaculous. 
Installation completed without errors, but in the Mautic home page I can read only "_Uh oh! I think I broke it._" etc. I've tried to install, unistall and reinstall for... 5 times (I think) under a sub folder and a subdomain. All times, same problem :-(
PHP configuration seemed correct:
- 512 of memory_limit
- all needed PHP extensions installed (as you can read here: https://github.com/mautic/mautic#mautic-requirements).

Reality is that, for some reasons, in some Hosting Provider you need to check these PHP extensions:
- apcu
- mcrypt
- memcached
- nd_mysqli
- nd_pdo_mysql
- pdo
- pdo_dblib
- pdo_firebird
- xmlreader
- xmlrpc
- xmlwriter
- zip

IMHO, **it's very important to ADD this information in requirements link.**

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.1

### Steps to reproduce:
1. Simply install from Softaculous
2. 
 
### Log errors: 
If nd_* extensions are not installed, you can find this message in error_log:
`[23-Jun-2018 21:15:46 UTC] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 796026264 bytes) in /[my_personal_data_removed]/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php on line 179`

**Comment by galvani** [comment]
Could you please post the complete backtrace instead of single line?

**Comment by StarAle** [comment]
Hi, @galvani,
with a new installation of Nautic (from Softaculous) without nd_mysqli and nd_pdo_mysql PHP extensions, that was the only one line inside my error_log file. 
When I have installed both nd_mysqli and nd_pdo_mysql Nautic is finally started.

**Comment by RCheesley** [comment]
I'm closing this issue down as these extensions are flagged in the pre-flight check, and it's a hosting config issue rather than a Mautic bug.
