### ISSUE TITLE
Anonymous contact is created twice for when visiting secondary site

### ISSUE THREAD

**Issue by andjules** [mautic/mautic#6258]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes(?)
| Feature request? | 
| Enhancement? | 

## Description:
Maybe I'm missing something as I learn mautic, but:
I have a website, example1.com
I have a related site, example2.com that helps to promote/complement/generate leads for the main business at example1.com
(And my mautic installation is at mautic.example1.com, if that makes a difference).
So, I add my tracking script (which loads js from mautic.example1.com) to both sites.
When a visitor lands at example2.com, mautic cookies are created in their browser for both mautic.example1.com and example2.com. Fine if that's how it supposed to work. 
**However**, in mautic > contacts > is:anonymous **I see two separate contacts with the same IP address**, same activity time, etc. 
a) I suspect, given the fingerprinting functions in the tracking scripts, this should not be happening.
b) given that it is happening, it would be nice to be able to merge these contacts, even if they are anonymous.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.30

### Steps to reproduce:
1. Add tracking script for domain x to to domain y. Send an anonymous visitor to domain y.
2. I believe I've tried it with both CORS on (for both domains) and (currently) off.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello,

An identified cookie is used only for one single domain. If you change domain it is a new cookie and then it generates a second anonymous contact.
Maybe you can try to go over that by using the Fingerprint feature ?

Good luck !
