### ISSUE TITLE
APC error on Custom Form Field Validation

### ISSUE THREAD

**Issue by scottshipman** [mautic/mautic#6259]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...
When apcu is enabled, an error is returned
`mautic.CRITICAL: Uncaught PHP Exception Exception: "Serialization of 'Closure' is not allowed" at /var/app/current/vendor/symfony/validator/Mapping/Cache/ApcCache.php line 55 {"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at /var/app/current/vendor/symfony/validator/Mapping/Cache/ApcCache.php:55)"}`

## If a bug:
Looks like the closure was introduced in 
https://github.com/mautic/mautic/pull/5838/files

But this follows Symfony documentation as described : http://symfony.com/doc/2.8/reference/constraints/Callback.html

| Q   | A
| --- | ---
| Mautic version | >=  2.1.13
| PHP version | 7.1.x

### Steps to reproduce:
1. Enable APC / APCu
2. create a new Custom field
2b. create a new custom field that has the same alias as an existing field ('address2' for example)
 
### Log errors: 

`mautic.CRITICAL: Uncaught PHP Exception Exception: "Serialization of 'Closure' is not allowed" at /var/app/current/vendor/symfony/validator/Mapping/Cache/ApcCache.php line 55 {"exception":"[object] (Exception(code: 0): Serialization of 'Closure' is not allowed at /var/app/current/vendor/symfony/validator/Mapping/Cache/ApcCache.php:55)"}`

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by namankumar** [comment]
Just to be clear, why is this a bug? Shouldn't Step 2b produce an error anyway since aliases are intended to be unique?

Or is the bug that this error is not handled properly and should fail more gracefully?

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
