### ISSUE TITLE
Queued Messages Stuck

### ISSUE THREAD

**Issue by cStuartHardwick** [mautic/mautic#6261]
I thought I had a bug, but I think I know why my issue occured, I just need to know how to fix it.

## Description:
I have emails stuck in "queued" that are not being sent. (I think I know why)

| Mautic version | v2.13.1 
| PHP version |  PHP 7.0.30 (cli) (built: May 11 2018 12:33:05) ( NTS )

### Steps to reproduce:

1. I was working on a test email, trying to send subscriber data to a custom preferences page via querysting, when I accidentally sent it to a segment containing 240 subscribers.
2. So okay, I created another email explaining that subscribers should ignore the previous message and sent it.
3. A few minutes later, though, I noticed that the "recall" message said "238 queued" not sent. Weird, but I figure the chron job hasn't run yet. So I log in through SSH and issue /usr/local/bin/php /home/cstukfps/email/app/console mautic:emails:send , but it says "Messages sent: 0"
4. It's now been over an hour. I tried making and sending a copy of the "recall" email, and it did the same thing--queued, not sent. So since it wasn only 240 people, I manually sent an email from gmail. But I still have the problem with the queued messages.

Okay, so I believe the reason these are queued is because I have my contact settings to allow no more than one contact per day. I don't really need that since I don't use the campaign featured in Mautic, but I thought it a good protecting against accidents--but in this case, since I wanted to send a "never mind" message to the exactly people I had just emailed, it queued them. I assume that's right, right?

Okay, so now my question is: How to I kill those queued messages? I already sent the "never mind" another way, and I have Two emails with the same queued messages. I have edited my chron jobs to put the word STOP at the start of the email job scrip path, which I assume will cause it to fail instead of sending these once the time is up.

So now I need to delete these queued messages so they will never be delivered. How do I do that? I've searched, but I'm not found anything about where these are stored. I don't want to just delete the "never mind" emails and then find that messages are still waiting to be delivered, or worse, stuck forever taking up storage.

Thanks.

 
### Log errors: 
The only log error are related to the /GeoLite2-City.mmdb file download, which has never worked.

**Comment by npracht** [comment]
Hello @cStuartHardwick,

I think if you go into spool (i don't know if there are already standing here) or if you unpublish this email, it should kill that?

**Comment by cStuartHardwick** [comment]
There was nothing in the spool directory, so I suppose the "Queued messages" count may have just been off. I didn't think to go check stats in Amazon SES to see if anything had really been sent.

I ended up deleting the affected messages (which were both just "Please disregard an earlier message sent in error." My only concern was that A) That might not select the queued messages, which might the be sent later, or B) it might orphan the queued messages, in which case it would waste storage.

It was only 230 messages, and I gather the queue is physical files in the spool directory, so if it was just a bug with the count, deleting the email resolves the problem. 

Thanks.

**Comment by cStuartHardwick** [comment]
You can close this. I think my answer was that if there had really been any queued messages, they'd have appeared under "spool." They didn't, to the queued count must have been in error. Anyway, I deleted the emails and moved on, so can no longer investigate or reproduce.
