### ISSUE TITLE
Forms are not validated

### ISSUE THREAD

**Issue by fgauttron** [mautic/mautic#6262]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I have several forms on my site and since a few days I have errors of validation of these forms, either they remain with the status "patient" or I had error 500. I emptied the cache and it works again but the error comes back regularly.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 5.6.33-0+deb8u1

### Steps to reproduce:
1.
2.
 
### Log errors: 
>[2018-06-26 09:08:21] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Proxies\__CG__\Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /var/www/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\FormBundle\\Entity\\Submission#lead' that was not configured to cascade persist operations for entity: Proxies\\__CG__\\Mautic\\LeadBundle\\Entity\\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /var/www/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []

**Comment by fgauttron** [comment]
This time I emptied the cache but the error remains.

**Comment by npracht** [comment]
Hello @fgauttron did you try to submit the form on a private browser? Probably it is "just" an issue when you're logged to mautic as a user.
