### ISSUE TITLE
link in email based on token not working

### ISSUE THREAD

**Issue by GabriGreese** [mautic/mautic#6268]
Bug report

## Description:
Click on contact -> select a contact clicking on name -> click on "send e-mail" -> fill with subject and in the body add a token of type asset (the button "token" on the WYSIWYG toolbar).

When i send the single e-mail (to me in this test) and I receive it, clicking the link generated by the token IN PRIVACY MODE (not logged in Mautic) results in a 500 Internal Server Error.

The error:

mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getId() on null" at /app/bundles/LeadBundle/Helper/ContactRequestHelper.php line 204

At line 204...
`        if ((int) $stat->getEmail()->getId() !== (int) $clickthrough['channel']['email']) {
            // Email ID mismatch - fishy so use tracked lead
            throw new ContactNotFoundException();
        }`

The $stat->getEmail() Object is null!

I suggest this patch until the problem is resolved:

`        if ( !is_null($stat->getEmail()) )
        {
            if ((int) $stat->getEmail()->getId() !== (int) $clickthrough['channel']['email']) {
                // Email ID mismatch - fishy so use tracked lead
                throw new ContactNotFoundException();
            }
        }
        `

Mautic version: v2.13.1
PHP Version: 7.0.30-1+0~20180505045929.18+jessie~1.gbpcfecb9

**Comment by npracht** [comment]
Please test https://github.com/mautic/mautic/pull/6260 that must fix your issue.

**Comment by GabriGreese** [comment]
Dear all,

the error is similar to one in 2.13.

I correct the error like this.

    /**
     * @param Lead $foundContact
     *
     * @return Lead
     */
    private function mergeWithTrackedContact(Lead $foundContact)
    {
		if (!is_null($this->trackedContact))
		{
			if ($this->trackedContact->getId() && $this->trackedContact->isAnonymous()) {
				return $this->leadModel->mergeLeads($this->trackedContact, $foundContact, false);
			}
		}
		
        return $foundContact;
    }
