### ISSUE TITLE
Open email can not be trigger in campaign

### ISSUE THREAD

**Issue by FaustoTu3w** [mautic/mautic#6270]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? |  No
| Enhancement? |  No

## Description:
I create a new campaign and I execute it, everything work fine but the open email trigger not work, my clients open emails and mautic show 0 mails opened. I try with different mails accounts, gmail, hotmail...

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.13.1
| PHP version | 7.0.30

### Steps to reproduce:
1. Create new campaign with open mail trigger
2. Execute
 
### Log errors: 

Not show log error.

**Comment by npracht** [comment]
Hello,

When you inspect the email, the tracking pixel is there ?
Are the images displayed in the email (if not, the pixel cannot work) ?
In your configuration > email settings > message settings > is your pixel tracking enabled ?

**Comment by FaustoTu3w** [comment]
Hello @npracht, 

1) I was searching in the email but I did not get the pixel code, how is it shown or what is the code for the tracking pixel in the email?

2) Yes, actually the images are shown in the email.

3) Yes. 

However in the decisions of the campaign shown several pending actions about opened mail.

**Comment by levrykurniawan** [comment]
I'm having the same issue after updating Mautic to version 2.13.1.

I found the pixel tracking in the email body, but it was direct to 404 page not found.

This issue does not only occur in emails used in campaigns, but in all emails sent from Mautic.
