### ISSUE TITLE
Gmail Plugin Not working

### ISSUE THREAD

**Issue by architjoshihs** [mautic/mautic#6271]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Gmail Plugin which we can use to track emails, create new contacts and event tracking or contact. This is not working. 

I installed mautic helper chrome extension and enabled the event tracking button and add required parameters. Similarly i configured gmail plugin in mautic.

When i sent an email from google after enabling the email tracking button, there was no event created, no contact created and also no contact updated.

even i checked the email, there was no tracking code added to the mail. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.0
| PHP version | 7.1
 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by briansuthoff** [comment]
I toggled between the new and old Gmail interface and confirmed that the plugin still works with the old version of Gmail and NOT with the new version.

**Comment by RCheesley** [comment]
Closing as this relates to a third-party plugin - https://github.com/mautic/mautic-helper-chrome-extension which already has open issues on this topic: https://github.com/mautic/mautic-helper-chrome-extension/issues
