### ISSUE TITLE
E-mail sent manually from within mautic includes invalid pagelink expansions ("server error") 

### ISSUE THREAD

**Issue by yrammos** [mautic/mautic#6272]
| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | –
| Enhancement? | –

## Description:
* `pagelink` expansions within an email produce valid redirects only when the email is generated by a landing page or form, not when it is manually sent by the Mautic admin from the Mautic UI.**

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.30-0ubuntu0.16.04.1

### Steps to reproduce:
1. Create a landing page.
2. Create an email within Mautic; include a `<a href="{pagelink=10}&email={contactfield=email|true}">...</a>` link within the email to point to an existing Mautic landing page (not necessarily the one created in Step 1).
3. Create a Mautic form to collect contact information.
4. Embed this contact form within the landing page using the form's token (`{...}`).
5. Add an action to the form so that it sends the previously created email to the contact. Upon submitting the form, the contact will now receive an email which will include a link back to the landing page with her/his email filled out.
6. **Within Mautic**, go to Contacts and **manually** send the same type of email to the contact (using the "Send email" button in the upper-right corner of the window).
7. **RESULT:** The contact will receive the email but the `{pagelink}` expansion will be invalid (server error").

This is a serious problem in my use case because I have an old set of contacts with partial information, and I need to redirect them to fill them out completely. (I might be able to achieve this with a campaign but I don't see why it shouldn't be possible manually, as well.)
 
### Log errors: 

``
[2018-06-29 11:15:43] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getId() on null" at /var/www/html/rammos.co/public_html/mautic/app/bundles/LeadBundle/Helper/ContactRequestHelper.php line 205 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getId() on null at /var/www/html/rammos.co/public_html/mautic/app/bundles/LeadBundle/Helper/ContactRequestHelper.php:205)"} []
``

Thanks.

**Comment by npracht** [comment]
Hello,

Did you try https://github.com/mautic/mautic/pull/6260 ?

**Comment by yrammos** [comment]
No, even though it looks encouraging. I am reluctant to patch my installation because I rely on it for urgent day-to-day work. Is this part of a beta/pre-release update channel already? Thanks!

**Comment by npracht** [comment]
No it is on the staging branch. Could you clone your local instance and make the test on local?
Or then simply wait for 2.14.0 version and update :)

**Comment by yrammos** [comment]
I wish I could contribute by validating but unfortunately these days it is impossible. I will be (im)patiently waiting for the next version. Many thanks indeed.
