### ISSUE TITLE
Campaign Action "Do Not Contact"

### ISSUE THREAD

**Issue by moskoweb** [mautic/mautic#6275]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:

It would be interesting if you had a Campaign Action, so you can mark the contact as "Do Not Contact", in addition to the "Delete" option.

Because if a contact is deleted, and this contact has an invalid email address, they can re-register, and eventually enter some sequence of emails and damage the reputation of the domain due to being invalid.

And with the "Do Not Contact" option, the contact is blocked from receiving emails, even if they sign up at other times, which helps a lot in a proper list cleaning process.

**Comment by merlin0** [comment]
Wouldn't it be more usefull to have this as form finisher option?

**Comment by moskoweb** [comment]
You could also have, but think about the situation that you are doing a campaign of engagement of leads, and for those who do not engage, you want to mark as No Contact, therefore you will not lose his history, if in the future he re-engages with you again.

Basically that's my idea, stop contacting the lead, but keep track of it for a while.

**Comment by npracht** [comment]
Hi @moskoweb, please test https://github.com/mautic/mautic/pull/7567

**Comment by RCheesley** [comment]
Closing this issue down as it is merged in 2.16
