### ISSUE TITLE
Website Hits Are Not Tracking

### ISSUE THREAD

**Issue by keanlaurens** [mautic/mautic#6276]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When users go to my website, mautic does not track the visits at all.
Also when I send an email to my contacts, and they click on the website link, it shows they clicked the link but does not show where they have gone on the website either.
Google analytics & Jetpack show hits and pages but mautic doesn't show at all.

I have installed WP Mautic plugin and have set it up. I have tried disabling plugin and starting setup again but nothing changes.

I have tried using other devices that are not logged in with different browsers too.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 5.6.36

### Steps to reproduce:
1. Go to website
2. Hits are not recorded
 
### Log errors: 

There is nothing in the Logs.

**Comment by dbhurley** [comment]
This seems to be not a bug but more of a support request, I'd recommend asking in the forums or the Slack channels to get some help.

**Comment by keanlaurens** [comment]
if you could invite me to the slack channel or provide a link, that would be great. It isn't on the website anymore.
