### ISSUE TITLE
Email marked as sent even when the cronjob fails

### ISSUE THREAD

**Issue by wittwerch** [mautic/mautic#6280]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | no
| Enhancement? | no

## Description:
We had a memory issue with one of our Mautic server. The system was actually overbooked and the cron for sending emails failed because of that.

```
mmap() failed: [12] Cannot allocate memory
mmap() failed: [12] Cannot allocate memory
mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 25165824) (tried to allocate 65536 bytes) in /var/www/foo/app/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php on line 510
mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 25165824) (tried to allocate 65536 bytes) in Unknown on line 0
mmap() failed: [12] Cannot allocate memory
```

However the emails are marked as sent in Mautic. 

![image](https://user-images.githubusercontent.com/1575445/42212003-2ff4f4d2-7eb5-11e8-915d-cc6b548e13dd.png)

We are using `Queue mode` and I think the way Mautic handles this should be inversed. Maybe emails being written to the spool folder should be considered pending and only be marked as sent if the mail transport acknowledged them?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 1e2dcf62e2740c64e69a87a86319fb9a5062b319
| PHP version | 7.0.30-0ubuntu0.16.04.1

### Steps to reproduce:
Actually couldn't reproduce the memory problem, but it is easy to see that this approach can be improved.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
I feel that this is as expected, rather than a bug, so perhaps it should be an enhancement or feature request?

**Comment by wittwerch** [comment]
I'm not sure that behaviour is expected: Mails are marked as sent before they are actually sent. As suggested this should be reversed. A mail should be marked as sent, if it has been sent :)

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
