### ISSUE TITLE
custom redirection link on form submit with query parameters ?

### ISSUE THREAD

**Issue by amitsquare** [mautic/mautic#6281]
Hey ,

I have one scenarios where i am passing query parameter for different products replacing content as per the query parameter using mautic form to create contact .
But i would like to redirect user to next page having same query parameter which being  passed on first page .
So how can i achieve the same ?
Any suggestion will help .

E.g  if user lands on page A having url https://website.com/page1?pre=test . Then post form submission , it should be redirecting to submit form url with same query parameter.
redirection url :: https://website.com/page2?pre=test .

-Thanks

**Comment by npracht** [comment]
Hello @amitsquare !
Please ask questions and advices on Slack or Forum. Github is used for bug reports and PRs.

Thanks!
