### ISSUE TITLE
email report :  Filtering by campaign_id and email_id not works. data duplicated.

### ISSUE THREAD

**Issue by SalvoEng83** [mautic/mautic#6284]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
when you create a report to view email-sent data, and filter it by email_id, everything works fine if the email has been used in a single campaign. But if you create a new campaign, and use on it an email already used in another campaign, the report show data duplicated.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.12.1
| PHP version | PHP 7.0.27-0+deb9u1

### Steps to reproduce:

1.   create a template mail. 
2.   create a campaign with action send-email, and specify the email just created.
3.   launch the campaign.
4.   create a report that show email sent, and filtering by email-id and campaign_id ( specifying email-id of the email just created and campaign_id of campaign just launched). the graph is correct.
5.   create a new campaign with action send-email, using the same email used in the previous campaign.
6.  refresh the page of the report previously created and you can see that the real number of email send is exactly twice.

Example. I have an email template, email_id=14.
I create two distinct campaigns (campaign_id 5 and campaign_id 6) each with one single lead to whom send the email with id 14. Executing both campaigns i will receive correctly the emails.
Than i want to view the report of email sent on a campaigns, so i create two distinct report:
Report_1 filtering by email_id=14 and campaign_id=5.
Report_2 filtering by email_id=14 and campaign_id=6.
I expect to see report_1 graph with one single email sent on campaign_id 5, instead i see two emails sent both with email_id 14 on same campaign, and the same result on report_2. This is the bug. The filter by email_id and campaign_id not work correctly.

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by SalvoEng83** [comment]
Hi npracht, on report view, the table that list email sent,  show two row with same identical data.  For example Report_1 show two row with campaign_id 5 and email_id 14, when i sent one single email in that campaign. 
if in addition to the filter i add the group by  grouping by campaign_id, the table show the correct data, but the graph show always two mail sent.  Debugging source code, i found that the problem is the query by which data is retrieved from the database.
In the method  app/bundles/ReportBundle/Model/ReportModel::getReportData(); 
if you try to add on the query a "DISTINCT" clause, the data on table are show correctly, but it solve only the duplicated data on table, instead the graph continue to show duplicated data.

**Comment by escopecz** [comment]
@SalvoEng83 would you mind sending PR with your changes?

**Comment by npracht** [comment]
@escopecz do you think you could have a look at it ? I have the feeling @SalvoEng83 is not active anymore.

**Comment by Enc3phale** [comment]
Request don't work because it's based on email_stats :
```
SELECT e.id AS e_id1, e.name AS e_name1, clel.campaign_id AS campaign_id1
FROM email_stats es
LEFT JOIN emails e ON e.id = es.email_id
LEFT JOIN leads l ON l.id = es.lead_id
LEFT JOIN ip_addresses i ON i.id = es.ip_id
LEFT JOIN emails vp ON vp.id = e.variant_parent_id
LEFT JOIN categories c ON c.id = e.category_id
LEFT JOIN campaign_lead_event_log clel ON clel.channel="email" AND e.id = clel.channel_id AND clel.lead_id = l.id
LEFT JOIN campaigns cmp ON cmp.id = clel.campaign_id
WHERE (es.date_sent IS NULL OR (es.date_sent BETWEEN "2018-06-25 22:00:00" AND "2019-07-26 09:00:00")) AND ((clel.campaign_id = 5) AND (e.id = 14))
LIMIT 30 OFFSET 0
```

There is two lines one for send by campaign n°5 and one for send by campaign n°6 because there is no direct link between email_stats and campaign for filter. Maybe for email_stats with campaign filter join is needed with campaign_events on source_id instead of campaign_lead_event_log ?
If someone have an idea to make this.

**Comment by npracht** [comment]
Without extra information and being an old issue, let close this issue.
