### ISSUE TITLE
phone field is not getting autofilled form database while getting values on page

### ISSUE THREAD

**Issue by nituls** [mautic/mautic#6286]
What type of report is this:
I am having issue with mautic autofill. I am not able to access phone field's autofill value on my Landing Page.
| Q  | A
| ---| ---
| Bug report? | Y 
| Feature request? | 
| Enhancement? | 

## Description:
I am using a form in my landing page. I turned on autofill feature for every field that I am using in that form. But the autofill for phone field in not working.

## If a bug: Autofill for phone not working

| Mautic version | v2.13.1 
| PHP version | 7.0.30

### Steps to reproduce:
1. Open any form with leads details
2. Check values for phone

**Comment by denispavliha** [comment]
I think this autofill issue affects 
- phone
- mobile
- zip code
fields.

**Comment by dichvuhuuich** [comment]
This bug still in version 2.15.1, is there anything news?

**Comment by zietbukuel** [comment]
I can confirm this bug on 2.16.0.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Maybe fixed by https://github.com/mautic/mautic/pull/8976
