### ISSUE TITLE
E-mail tokens not rendering

### ISSUE THREAD

**Issue by exactsameproblem** [mautic/mautic#6288]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Hello,
I set up a test contact, with a first name (and an e-mail of course). Then I send a test e-mail to the contact containing :
`Hello {contactfield=firstname}`

But once the e-mail received, it contains : 
`Hello [First Name]`

The first name is obviously set, I can reproduce this for all the contact, and even when I send a "normal" e-mail.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | Latest (2.13.*)
| PHP version | 5.6

### Steps to reproduce:
1. Create a test user, with a given firstname.
2. Create a test e-mail having {contactfield=firstname} in the body.
3. Check the e-mail and see that it's not rendered.

No error show up, same with other fields, except some like {unsubscribe}.
Thank you.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @exactsameproblem,

Contact tokens are not rendered in test email. Send a real email and you'll notice it works properly.

Best !
