### ISSUE TITLE
500 Error while creating report with filter condition e.g Like , Contains !!

### ISSUE THREAD

**Issue by amitsquare** [mautic/mautic#6290]
Hi ,

When i tried to create report with filter column value "HIT URL" & condition "contains" along with some "value" . When i hit Save & Close , this leads to 500 error page .

Checking on logs further shows this given error .

`mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "contains" of class "Doctrine\DBAL\Query\Expression\ExpressionBuilder"." at /var/www/html/mautic/app/bundles/ReportBundle/Builder/MauticReportBuilder.php line 486 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"contains\" of class \"Doctrine\\DBAL\\Query\\Expression\\ExpressionBuilder\". at /var/www/html/mautic/app/bundles/ReportBundle/Builder/MauticReportBuilder.php:486)"} []`

Anyone Faced this problem , Any direction would be appreciated .

**Comment by npracht** [comment]
Hello @amitsquare could you please fill the standard issue template (how to reproduce, mautic version, etc.).
Also could we have screenshot of your report settings?

Thanks
