### ISSUE TITLE
Disabled admin access.

### ISSUE THREAD

**Issue by dotjss** [mautic/mautic#6296]
I disabled full admin access by mistake, I can't revert as I can access roles, is there a way to do it via the db or enable this permission?

**Comment by npracht** [comment]
Hello @dotjss i think you can do it in the DB in the `role` table:
![capture d ecran 2018-07-11 a 09 37 50](https://user-images.githubusercontent.com/14075239/42557192-1e18c40c-84ee-11e8-97e0-56a032c6fe8e.png)

Please ask this type of question on slack or forum.
Thanks !
