### ISSUE TITLE
Showing domainname/index.php/s/login in URL 

### ISSUE THREAD

**Issue by BharadwajMvd** [mautic/mautic#6298]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 

### Steps to reproduce:
1. Download and install the new mautic version from the website, after installation when I try to open domainname.com/s/login its showing 404 error.
2. But if I try with domainname.com/index.php/s/login it is working. But now how to remove this index.php?
 
### Log errors: 
in logs I am getting this : 

[2018-07-06 07:39:12] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'deepak.lead_fields' doesn't exist [] []

**Comment by levrykurniawan** [comment]
Are you using Nginx? Try adding **rewrite ^/index.php/(.*) /$1  permanent;** on your virtual host configuration.

**Comment by npracht** [comment]
You should check your htacces file.

**Comment by BharadwajMvd** [comment]
@levrykurniawan hi thank you, If I open my .htaccess file I have many rewrites where I shall paste this?

**Comment by BharadwajMvd** [comment]
When I do not give index.php in URL:
[Without index.php](http://prntscr.com/k52btk)
When I give index.php in URL:
[With index.php](http://prntscr.com/k52cut)

**Comment by escopecz** [comment]
You must have support for mod_rewrite and and .htaccess enabled by the server. Contact your server admins for help. It's not a Mautic bug but server configuration issue.
