### ISSUE TITLE
issue with campaign condition form value

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6299]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is an issue with the condition form value in campaign linked to select-multiple field.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13
| PHP version | 

### Steps to reproduce:
1. Create a new select multiple custom fields
2. Create a new campaign form, add a checkbox group and map it to field previously created
3. Create a campaign, start from the campaign form just created
4. Add a condition based on form values
5. Choose the form just created and choose the select multiple form
![image](https://user-images.githubusercontent.com/31535432/42368671-f2de0a0c-8107-11e8-9bbc-28bf222d6dfb.png)
6. In the value it should be possible to click to display the different values but it does not appear.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by johbuch** [comment]
@kuzmany 
where you are here
![image](https://user-images.githubusercontent.com/31535432/42520115-ca1b556e-8465-11e8-9ce7-d32fcd6b0ec8.png)
can you click on update, then save campaign and go back to check this condition to see if values still display as a list ?

**Comment by johbuch** [comment]
@kuzmany so you reproduce it ?
Yes also for the second one

**Comment by kuzmany** [comment]
Yes, I got it. I will fix it tomorrow ;)

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/6314
