### ISSUE TITLE
Can't create a new email

### ISSUE THREAD

**Issue by pikamoo** [mautic/mautic#6300]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | 
| Enhancement? | 

## Description:
I can't create a new email.  After I click save or apply I get taken back to the option to select the type of email to create.  No email gets created.  I checked the logs for errors and there are no errors.  I've cleared the cache.  I used Softaculous to install Mautic.  I've tried installing a few times and its always the same problem.  I have no problem with any of the other Mautic features.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.30

### Steps to reproduce:
1. Select the type of email to create
2. Click save or apply
 
### Log errors: 
Today's Mautic error log is empty. Check server error log for error messages Mautic didn't have a chance to catch.

**Comment by npracht** [comment]
Hello @pikamoo i cannot reproduce. Are you sure there is no logs just after that happens? Also, no JS error in your browser console ?

Thanks

**Comment by pikamoo** [comment]
Hi.  @npracht i contacted my host server.  There was a security plugin blocking it.  After they made some changes I was able to create new emails.  This is now resolved.

**Comment by GrooveDevops** [comment]
If it fixed for anyone please let me know
