### ISSUE TITLE
Email Lead is always sent to the first contacts added to mautic standalone form

### ISSUE THREAD

**Issue by handita** [mautic/mautic#6301]
| Q  | A
I don't know this is bug or not, But when I first created standalone form to capture email leads, and then set an action to send email with "**Send to contact**" action, it only keeps sending email to the first email.

For example I add leads form email in the following order :
1. a@b.com
2. b@b.com
3. c@b.com

But when I checked the email is only sent to a@b.com in three times. The other two email don't get any email yet. Am I doing wrong?

| Mautic version 2. 13.1 | 
| PHP version 7.0.30 |

**Comment by npracht** [comment]
Hi @handita i don't understand your configuration.
Is it possible to have screenshots of your form action config?

Thanks
