### ISSUE TITLE
issue with the default value of a select field when creating contact through forms

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6302]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is an issue with default value of a select field. 
When a contact submits a form (that not contain the select field with a default value), this field does not update with this default value.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13
| PHP version | 

### Steps to reproduce:
1. Create a select field with some value and add a default value
2. Create a form with only email
3. Submit the form to create a new contact
4. Check if the select field previously created has been updated with the default value. See that it has not.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by johbuch** [comment]
mistake, I close this issue

**Comment by johbuch** [comment]
I reopen this issue because I reproduced it on the 2.14

**Comment by kuzmany** [comment]
I tried reproduce, but works for me. See video, please re-test

http://somup.com/cFiTQFVLDe

**Comment by johbuch** [comment]
just to make sure, you tested it with the latest version 2.14 ?

**Comment by johbuch** [comment]
@kuzmany I can see on your video that you are submitted form with the preview url. so i tried as you did and indeed it works.
But if I submit the form with the real URL, it does not update the custom field with the default value.
So 
-> *.com/s/forms/preview/88  --> works
-> *.com/form/88 --> does not work

Can you try ?

**Comment by kuzmany** [comment]
Ok, I will try. Thanks

**Comment by kuzmany** [comment]
Hope this fixed it https://github.com/mautic/mautic/pull/6402
