### ISSUE TITLE
Pagination in "Contact" tab of email view page doesn't work. Only first page is rendered.

### ISSUE THREAD

**Issue by AlbanL74fr** [mautic/mautic#6304]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
In email view, tab "Contact", it's not possible to change page to view all the contacts. Only the contacts on the first page are visible.

![image](https://user-images.githubusercontent.com/23435414/42463448-5bcfd598-83d0-11e8-93cb-d917684e8ce2.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 5.6.32

### Steps to reproduce:
1. Go to https://mautic.yourdomain.com/s/emails/view/{EMAIL_ID}
2. Click "Contact" tab
3. Click "2" or any other page number, or click ">" or click ">>" to see more contacts that were sent your email

Result : Nothing happens. Only first page is rendered
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/6666
