### ISSUE TITLE
Mautic-Channels-Emails-Read persentage not showing (In Sengrid, it is showing up)

### ISSUE THREAD

**Issue by ramakrishnapurini** [mautic/mautic#6308]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
We installed Mautic version 2.13.1 and integrated with Sendgrid-API. We are able to see campaigns email flow: Requests, Delivered, Opened in app.sendgrid.com, but we are unable to see in Mautic -> Channels -> Emails as Read & Read percentage.

![image](https://user-images.githubusercontent.com/16356027/42508624-26cf9f94-8417-11e8-891d-f10d0146d202.png)

![image](https://user-images.githubusercontent.com/16356027/42508636-31907e94-8417-11e8-8ac2-cf5e7767ae54.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.27

### Steps to reproduce:
1. I have followed through this URL: https://www.mautic.org/docs/en/emails/bounce_management.html and enabled Monitoring Mail Box. 
2. We Activated "Event Notification" option also at sendgrid end:
http://My-mautic-server.com/index.php/mailer/sendgrid_api/callback
(My-mautic-server.com= This is my server URL)

![image](https://user-images.githubusercontent.com/16356027/42508646-3938a0fe-8417-11e8-9fd7-d92d5f2caa8a.png)

 
Result: Still not showing the emails read percentage status on my Mautic server, further reference please check the attached images please help on this.

### Log errors: 
[2018-07-09 16:04:16] mautic.CRITICAL: Uncaught PHP Exception Pheanstalk\Exception\ConnectionException: "Socket error 111: Connection refused (connecting to localhost:11300)" at /var/www/html/vendor/pda/pheanstalk/src/Socket/NativeSocket.php line 45 {"exception":"[object] (Pheanstalk\\Exception\\ConnectionException(code: 0): Socket error 111: Connection refused (connecting to localhost:11300) at /var/www/html/vendor/pda/pheanstalk/src/Socket/NativeSocket.php:45)"} []

[2018-07-10 06:34:50] mautic.WARNING: PHP Warning - unlink(/var/www/html/app/cache/prod/appProdProjectContainer.php): Permission denied - in file /var/www/html/app/bundles/CoreBundle/Helper/CacheHelper.php - at line 102 [] []
[2018-07-10 06:34:55] mautic.WARNING: PHP Warning - unlink(/var/www/html/app/cache/prod/appProdProjectContainer.php): Permission denied - in file /var/www/html/app/bundles/CoreBundle/Helper/CacheHelper.php - at line 102 [] []

[2018-07-10 06:25:48] mautic.WARNING: Error accessing https://mautic.com/?feed=rss2&tag=notification : Operation timed out after 10000 milliseconds with 0 out of 0 bytes received [] []

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
This is not managed by the Sendgrid API as far as i think. Could you show your email configuration settings in mautic configuration? Is the email tracking enabled?

**Comment by ramakrishnapurini** [comment]
Hi @npracht : 
Below screen shot is my Mautic Email settings:
![image](https://user-images.githubusercontent.com/16356027/42566413-7f6e8bf2-84d4-11e8-8a57-d4bbc6ef69d0.png)

Tracking Enabled:
![image](https://user-images.githubusercontent.com/16356027/42566480-be302eae-84d4-11e8-85b4-232c5bc2cfe7.png)

Please check and give the solution to track emails as Read/Read Percentage.

Thanks,
Rama

**Comment by npracht** [comment]
The tracking pixel is appended it should work.

Could you send to yourself an email (a real one, not a test email) > open it > see if stats is working and if not check logs ?

**Comment by ramakrishnapurini** [comment]
Configured one Segment and configured Campaigns, Campaign is working fine. I got a mail, but not showing it on Channels->Emails->Read Percentage:
Tested Campaign: 
![image](https://user-images.githubusercontent.com/16356027/42567972-859c65f8-84d9-11e8-84b9-a227d98e4884.png)

In Channels->Emails->
![image](https://user-images.githubusercontent.com/16356027/42568054-c2e7fd6e-84d9-11e8-9a8d-dd58da24f6ac.png)

Logs:
Which logs: Mautic (/var/www/html/app/logs/mautic_prod-2018-07-10.php) or /var/log/maillog ?

**Comment by npracht** [comment]
Don't know, anything that would tell us that there is an issue on the email pixel :D
You're sure also that you preview the images in your emails ? (outlook for instance does not show image by default).

**Comment by ramakrishnapurini** [comment]
My Campaign email:
![image](https://user-images.githubusercontent.com/16356027/42570031-8df4a0ba-84e0-11e8-8723-cd82027efdb2.png)

**Comment by killboard** [comment]
I'm having an issue with email pixel too. The path for .gif file is responding 404.

This is the `<img>` tag that mautic added to email sent by a campaign.

```
<img height="1" width="1" src="https://ci4.googleusercontent.com/proxy/kug6R2iOixugA4GYuSZDSJF5tGkp5uN1UMWQH7jnTguF-ZSRcatKJFsdOhFc-vN07fmPLfGnl1KqnE_Je5sHpU6C8Rc7_pWkcf4PcDSYuTF50_vFo00pAZA2=s0-d-e1-ft#https://mymauticserver.com/email/5b4dffd848a0f.gif" alt="" class="CToWUd">
```

The result is 404. I checked on mautic file folders structure and the emails folder not exists with file `5b4dffd848a0f.gif` so I thing that isn't a problem with my Web server.

**Comment by shridharkr** [comment]
i have configured mautic and looking for Emails Stats in eh Channels-> EMails 
1. Send Stats is working
2. Read Stats is not working.

![image](https://user-images.githubusercontent.com/22319270/42877621-4e41350a-8a58-11e8-8490-1aba44d021c5.png)

**Comment by killboard** [comment]
Hi, I solve the issue yesterday. My solution was to add a redirect at my nginx server for all requests coming from `/email/*.gif` as below.

```
    # Solve email tracking pixel not found
    location ~ email/(.*).gif {
        try_files $uri /index.php?$args;
    }
```
After it the email read back to work.

**Comment by shridharkr** [comment]
Hi Killboard,  Thanks for your reply.
We are using httpd service, could you please tell me where should i make the following changes as you mentioned .
   # Solve email tracking pixel not found
    location ~ email/(.*).gif {
        try_files $uri /index.php?$args;
    }

**Comment by killboard** [comment]
Maybe it can help you -> https://httpd.apache.org/docs/trunk/da/vhosts/examples.html

Take a look on the `Using the ServerPath directive` session

**Comment by escopecz** [comment]
Will close this as there was no response for several months. So I expect this is resolved.
