### ISSUE TITLE
Cant' create Webhook via API

### ISSUE THREAD

**Issue by Flavio1998** [mautic/mautic#6317]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When I send a cUrl command to create a new Webhook I get the errors
`{
    "errors": [
        {
            "code": 400,
            "message": "name: A name is required., webhookUrl: A valid URL is required.",
            "details": {
                "name": [
                    "A name is required."
                ],
                "webhookUrl": [
                    "A valid URL is required."
                ]
            }
        }
    ]
}`
My cUrl requests looks like this: 
`curl -i -XPOST user:password@192.168.5.186:7357/api/hooks/new -d'{"name":"test","webhookUrl":"http://192.168.5.104:9903/update","triggers":["mautic.lead_channel_subscription_changed"]}'`

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.13.1
| PHP version | 7.0.30-0

### Steps to reproduce:
1. Create new webhook via API
2. Get errors
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
The API expects data in `application/x-www-form-urlencoded` format. If you're sending JSON you have to specify it in the header.
