### ISSUE TITLE
Pipedrive Error

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#6320]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:

When send an lead to pipedrive, mautic re-schedule the event and do not sync 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.1

### Steps to reproduce:
1. Setup Pipedrive Integration
2. Send and Lead to Pipedrive over campaign
 
### Log errors: 

[2018-07-13 15:10:30] mautic.ERROR: INTEGRATION ERROR: Pipedrive - Lead already have integration [] []
[2018-07-13 15:10:30] mautic.ERROR: INTEGRATION ERROR: Pipedrive - Lead already have integration [] []
[2018-07-13 15:10:30] mautic.ERROR: INTEGRATION ERROR: Pipedrive - Lead already have integration [] []

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello,

Please test : https://github.com/mautic/mautic/pull/5401

**Comment by heathdutton** [comment]
@luizeof would you be willing to test this at https://mautibox.com/5401 ?

**Comment by alanhartless** [comment]
Fixed in 2.15.0

**Comment by janwinkler** [comment]
Im using 2.15.2, still seeing the same errors in my logfile

**Comment by fguimara** [comment]
Same error for me. Using 2.15.2
