### ISSUE TITLE
Outlook plugin does not send DNC to mautic

### ISSUE THREAD

**Issue by architjoshihs** [mautic/mautic#6325]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 💚 
| Enhancement? |

## Description:
When we are integrating outlook with mautic, we are not getting the bounced email to be added to DNC. Instead the contact remains as a lead and also shows that it has been opened. Could we have a solution implemented for this.

| Mautic version | 2.13
| PHP version | 7.0

**Comment by npracht** [comment]
Hello @architjoshihs !
Actually it is not a bug. Mautic is not sending the email so that's why it is not tracked. It is not a support feature. It should be considered as a feature request.

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
