### ISSUE TITLE
Multiple Monitored email Settings

### ISSUE THREAD

**Issue by architjoshihs** [mautic/mautic#6327]
What type of report is this: Feature

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
Currently it is possible to only integrate one user account to email monitoring. We can have per user monitoring, where each user can integrate his own email account or there can be multiple account of single user integrated.

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
