### ISSUE TITLE
add Asset attachment option when sending email from contact page

### ISSUE THREAD

**Issue by architjoshihs** [mautic/mautic#6332]
What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | Y
| Enhancement? | Y

## Description:
When we send email directly from contact list, we are not having any option to add attachment. Please help me out.

| Mautic version | 2.13
| PHP version | 7.0

**Comment by ridjy** [comment]
I'm facing the same problem, is there any solution to send email with attachment from a contact page? 
I import from an existing template but the attachment doesn't go with it 

 Please help me out.

| Mautic version | 2.15
| PHP version | 7.1

**Comment by RCheesley** [comment]
Hi folks, if someone would like to work on this (we also have a request in #6392 to add in the ability to use BCC from this screen) please do go ahead and make a pull request. The Product Team would be happy to support you!
