### ISSUE TITLE
Cannot create landing pages.

### ISSUE THREAD

**Issue by MrBird77** [mautic/mautic#6334]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | y
| Enhancement? | n

## Description:
When Creating landing page using template, 'apply' and 'save & close' both reset the page and no new page is created. 
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 5.6.30

### Steps to reproduce:
1. Create stand alone form
2. Attempt to create landing page
 
![capture](https://user-images.githubusercontent.com/35977427/42850441-a2c5eee4-89f5-11e8-8db8-f7a60dc58a77.JPG)

**Comment by Bizcrony** [comment]
Its an server issue ... same issue we are getting so talking to hosting

**Comment by MrBird77** [comment]
So it's on mautics end and I can stop digging? the error i get from console points to my own domain so I'm not sure.

**Comment by MrBird77** [comment]
@Bizcrony I spoke with my hosting service and we determined the issue was being caused by a back end apache firewall service they added for security. Than can disable and enable it on request via chat (Namecheap).

**Comment by MrBird77** [comment]
@Bizcrony  Yes this was the solution. However they were unable to white list and strongly advised against leaving Mod Security disabled

**Comment by sumandahal** [comment]
I have the same issue, I assumed it was a Mautic issue and was gonna be resolved at some point, is the only solution talking to your host or is there anything that can be done from Mautic's side?

**Comment by sumandahal** [comment]
@Bizcrozy great, I am not using landing pages right now so I will wait on the update from Mautic team because ideally you shouldn't have to disable security on your server to make something like a landing page update work.

**Comment by npracht** [comment]
@Gregy relying on your expertise, would you have a comment to add before closing this issue ?
Thanks a lot

**Comment by Gregy** [comment]
Could some of you please request server-side logs of the issue? What exact rule in mod_security ruleset does mautic break?

**Comment by sumandahal** [comment]
I see a bit of activity here, I just tested this on v2.14.1 and have the same issue. @npracht @Gregy please let me know if you need any error codes etc from my side. I am on a shared hosting environment / cpanel so keeping in mind that I might not have access to all security settings.

**Comment by Gregy** [comment]
We need server side logs of this issue to see what exactly causes the problem. mod_security is a ruleset and we need to identify the specific rule in it that mautic breaks to evaluate what to do next.

**Comment by sumandahal** [comment]
@Gregy so php error logs? I have access to those

**Comment by Gregy** [comment]
If it is caused by apache mod_security you need apache error and access logs.
