### ISSUE TITLE
issue with unsubscribe link integrated in dynamic content

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6335]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
If you add the unsubscribe link into a dynamic content, it won't work because it will generate the same link for all contacts. Link that land in error.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13
| PHP version | 

### Steps to reproduce:
1. I created a select field
2. I create a new email and add a dynamic content bloc
3. In the first variation, I add a filter on my select field equal val1
![image](https://user-images.githubusercontent.com/31535432/42866906-411f8d20-8a6e-11e8-944a-3693f7653a5e.png)
In the content, I just added a space
4. I created a second variation and added the same filter but a different operator which is not equal
In the content I integrated the token {unsubscribe_text}
![image](https://user-images.githubusercontent.com/31535432/42866983-7b0b5c94-8a6e-11e8-818c-98117f1909ba.png)
5. Then I display the email preview and check the unsubscribe link, I can see that it is already generated. 
![image](https://user-images.githubusercontent.com/31535432/42867039-a5360f3c-8a6e-11e8-84bb-15ac690d5e9e.png)
But it should be `email/unsubscribe/xxxxxxxxxxxx`
6. If I shoot the email, all contact will have the same previous link if they click on the unsubscribe link
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Can you test it on 2.14?  Do you send segment or campaign email?
I can't reproduce. Works for me:

My preview:

![image](https://user-images.githubusercontent.com/462477/43504987-b7127914-9565-11e8-990d-03862b595b50.png)

And different unsubscribe link receive to email (segment email)

![image](https://user-images.githubusercontent.com/462477/43505007-c8e68a4a-9565-11e8-8ca2-cc0d013d7851.png)

**Comment by kuzmany** [comment]
Close. Works 2.14
