### ISSUE TITLE
Import "Custom Fields" settings for bulk creation of Custom Fields

### ISSUE THREAD

**Issue by dmnabti** [mautic/mautic#6337]
What type of report is this:
| Feature request | 

## Description:
I have 200+ custom fields in our hubspot account (I'm sure many others also have a lot of custom fields in whatever system they may have used previously to Mautic, or a backup of Mautic), and I'd love to import all that data into our new Mautic installation ... but doing that manually could take several days, and is more prone to errors. Better would be an automated way to import Custom Fields. Maybe just have that as an option on the import contacts form, to add new fields that don't already exist in your Mautic. 

Maybe? 

Thanks much to the amazing Mautic dev crew! 🌟

**Comment by dongilbert** [comment]
Have you considered doing this over the API? https://developer.mautic.org/?php#fields

**Comment by npracht** [comment]
Hello @dmnabti, agree with @dongilbert !
If they are several, write a script and do it via API ;)
