### ISSUE TITLE
Cannot save any changes to any emails.

### ISSUE THREAD

**Issue by cStuartHardwick** [mautic/mautic#6340]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

 Bug report

## Description:
This issue has returned, except now I can no longer save ANY changes to ANY emails. I'm dead in the water, and neither deleting cache nor restarting the browser makes any difference.

I've seen this problem before where after editing an email and trying to save, it pop the dialogue back up asking you to choose between template and segment. This does that if I'm trying to create a new email, but if editing an old one, when I press save or apply, my changes just vanish. I opened an older segment type email to test, and after trying to save, the "segment" field changes to all possible values of segments and is no longer editable.
## If a bug:

| Q   | A
Mautic version : Unsure, it doesn't seem to display anymore.
PHP version : 7.0.30 

### Steps to reproduce:
1. Create any new email. Try to save or apply. Watch changes vanish and return to the "template or segment" dialogue.
2. Edit any old email. Try so save or apply. Watch changes vanish.
 
### Log errors: 
Log are empty.

**Comment by npracht** [comment]
Hello @cStuartHardwick without mautic version we cannot test and reproduce. It seems you have some issues with your mautic installation if it is not displaying the version.

Did you try to generate assets, clear cache, etc ?

**Comment by cStuartHardwick** [comment]
This was resolved by having mod security disabled. Thanks.
