### ISSUE TITLE
Using same email templates in multiple campaign with overlapping contacts.

### ISSUE THREAD

**Issue by healthlynked** [mautic/mautic#6341]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
I am not able to use same email template in 2 separate campaigns having the same user segment.  If the user has received an email from a different campaign he/she doesn't get an email if the same email template is attached to another campaign. To explain it with an example consider the following scenario.

- Create an Email template X

- Create a Segment S with user A, B and S' with user A, C

- Create a Campaign C1 with template X and segment S (Works Fine Both A&B gets an email)

- Create a Campaign C2 with template X and Segment S'( Works fine but only C gets an email, not A)

According to me check should be at Campaign as well Email level not only at Email Level for template emails

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.11
| PHP version | 7.1

### Steps to reproduce:
- Create an Email template X

- Create a Segment S with user A, B and S' with user A, C

- Create a Campaign C1 with template X and segment S (Works Fine Both A&B gets an email)

- Create a Campaign C2 with template X and Segment S'( Works fine but only C gets an email, not A)

According to me check should be at Campaign as well Email level not only at Email Level for template emails 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
See @AlbanL74fr comment please he is right.

**Comment by healthlynked** [comment]
Cool, I think it does make sense to me now. No one would be using the same email template for the same set of people twice.
