### ISSUE TITLE
I have a issue with Chanel Email Tracking message

### ISSUE THREAD

**Issue by himel2017** [mautic/mautic#6342]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | 
| Enhancement? | 

## Description:
I am using mautic and now i am facing a problem, i just send Email Example to my contact via  from Chanel->Email-> Send Example but  i didn't 'see the all  Engagements data, how many clicks on raw link, how many page hit, etc, when i go Chanel -> Email- i saw this error : http://prntscr.com/k9fizt   i think it can be problem.  also how to use external url in email template ? and how it will track ? i mean how many contacted visited that external url. anyone help me to fix it.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello,

As it is said in its name, it is a test email. So tracking links, tokens, etc. are not working. Send a real email and you'll see it works :)
