### ISSUE TITLE
I have a problem with sending email to people who have already expired at today in campaign.

### ISSUE THREAD

**Issue by TaKO8Ki** [mautic/mautic#6343]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  y
| Feature request? | 
| Enhancement? | 

## Description:
What I want to do is confirm whether registered person's expires_date is before today or after today and then send email to people who have already expired at today. However, in following way, all people who have registered ever since get emails. Please tell me how to solve this problem.
I'm sorry that my English is bad.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.13.1
| PHP version | 

### Steps to reproduce:
1.  Create new campaign.
2.  Create new condition of contact field.
3.  And I did like this.
![image](https://user-images.githubusercontent.com/41065217/43043299-877c8cf4-8dcb-11e8-942a-c69289bb5694.png)

"コンタクトフィールド" means "contact field".
"演算子" means "operator".
"値" means "value".
"未満" means "less than".
"すぐに実行" means "immediately".
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by AlbanL74fr** [comment]
Would the approach described here (https://navigatetomorrow.com/tutorials/how-to-create-a-birthday-campaign-in-mautic) work for you?

**Comment by TaKO8Ki** [comment]
Thank you, AlbanL74fr !!! 
I can solve one problem thanks to you.
However, I have another problem, so if you like, please answer my issue.
I created new issue.

**Comment by npracht** [comment]
Hello this feature is not supported in campaign (relative dates). See PR that proposes that change: https://github.com/mautic/mautic/pull/6126
Please test it and send feedback.

**Comment by npracht** [comment]
Closed in favor of https://github.com/mautic/mautic/issues/6080 that already reported this issue.
