### ISSUE TITLE
I have problem with sending email to people whose period of registration is one year in campaign.

### ISSUE THREAD

**Issue by TaKO8Ki** [mautic/mautic#6345]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  y
| Feature request? | 
| Enhancement? | 

## Description:
What I want to do is confirm whether there is a one year or not between "start_at" and "expire_at" and then send email to people whose period of registration is one year. However, in following way, I cannot do. Please tell me how to solve this problem.
I'm sorry that my English is bad.

"start_at" means the date when people registered.
"expire_at" means the date when people expired or will expire.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.13.1
| PHP version | 

### Steps to reproduce:
1.  Create new campaign.
2.  Create new condition of contact field.
3.  And I did like this.
![image](https://user-images.githubusercontent.com/41065217/43044268-1c2ecefe-8dde-11e8-9f18-f6de1d7d1a3c.png)

Now value is "start_at + 1 year", operator is "equal", contact field is "expire_at"
 
"コンタクトフィールド" means "contact field".
"演算子" means "operator".
"値" means "value".
"すぐに実行" means "immediately".

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Please switch your Mautic to english before taking screenshots. I don't understand what's going on there even with the dictionary bellow it.
