### ISSUE TITLE
Segment Test in a campaign

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#6349]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | Y

## Description:
When you edit a campaign you can add a condition to know if the contact is or not in a segment.
You can choos the segement but this one must to be public.

I think it's nothing to do with public or not. 

Could we authorize all the segment to pbe pickable to make the test.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.xxx

### Steps to reproduce:
1.  Create a segment TEST non public
2.  Create a campaign 
3. use The condition SEGMENT
4. try to use the segment TEST
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Discussion (solution) about it here 
https://github.com/mautic/mautic/pull/6312

**Comment by npracht** [comment]
Closed in favor of https://github.com/mautic/mautic/issues/5658
