### ISSUE TITLE
SugarCRM Sync Error

### ISSUE THREAD

**Issue by agentscript** [mautic/mautic#6350]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Activity sync from Mautic to SugarCRM/SuiteCRM causes error 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.13.1 
| PHP version | 5.4.45

### Steps to reproduce:
1. Enable SugarCRM plugin
2. Allow Acitivity Integration. Though the Contacts, Leads are being pushed and pulled fine. The activity stream produces an error
 
### Log errors: 

Mautic Log 
mautic.ERROR: INTEGRATION ERROR: Sugarcrm - Module Does Not Exist mtc_WebActivities set_entries POST [] []

SugarCRM Log
[ERROR] SoapHelperWebServices->checkSessionAndModuleAccess - module does not exists - mtc_WebActivities
[ERROR] 20: Module Does Not Exist<br>This module is not available on this server

**Comment by npracht** [comment]
Hi @agentscript as you can read the module `mtc_WebActivities` does not exist in your Sugar.

**Comment by agentscript** [comment]
For anyone else struggling with this the module was released later after the version and is available to download from Sugar Git. Its called WEB Activities.

Many people migrate from migrated from SugarCRM to suite and miss out on this module.

**Comment by pstevens71** [comment]
Hey can you provide a link for the Sugar Web Activities Module?

**Comment by tsummerer** [comment]
@agentscript  - Where can we find the Web Activities module? I can't find it in [SugarCRM's github](https://github.com/sugarcrm). Is there somewhere else we should look?

**Comment by pstevens71** [comment]
So I kind of mostly figured this out.  Just create a Package called "MauticActivities" or whatever you want, then a module called "WebActivities" with the key "mtc" just select a basic module and then add a relation to the contact and the lead, you get most of the activities.  Still working out what the field names of the other data should be.  "url" is the URL and "contact_id__c" (double underscore) is the contact to relate to.  Haven't figured out the lead ID yet, but I'm experimenting, it doesn't seem to be "lead_id__c"

**Comment by pstevens71** [comment]
![web activities](https://user-images.githubusercontent.com/29544935/76795018-a3462b80-679e-11ea-83a2-ccb59c3cb855.png)

So I pretty much got it working, if anyone want you can pm me and I can export the module.  It works pretty good!
