### ISSUE TITLE
Restrict selected days/hours to send failed emails

### ISSUE THREAD

**Issue by umakantsharmacedcoss** [mautic/mautic#6352]
| Feature request | 
| Enhancement | 

## Description:
Some conversion mails should be send on weekdays ( monday - friday ) that too with specific time like ( 9am - 7pm ), so if a feature in the campaign we can globally set when we have to send the mail ( this will override the default wait time ) would be great to have.

Thanks!

**Comment by xtjoeywx** [comment]
I agree. This would be a great feature to have.

**Comment by npracht** [comment]
Addressed
