### ISSUE TITLE
AWS SES Integration Shows Error 

### ISSUE THREAD

**Issue by BharadwajMvd** [mautic/mautic#6353]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 

### Steps to reproduce:
1. Go to "config" > Email Settings > Try giving Amazon Ses > click on test connection.
2. The error will be displayed 
 
### Log errors: 

Displayed Error will be like following:

**"Connection could not be established with host email-smtp.us-west-2.amazonaws.com [Connection refused #111] Log data: ++ Starting Swift_SmtpTransport !! Connection could not be established with host email-smtp.us-west-2.amazonaws.com [Connection refused #111] (code: 0)
++ Starting Swift_SmtpTransport !! Connection could not be established with host email-smtp.us-west-2.amazonaws.com [Connection refused #111] (code: 0)"**

Please, someone, help in solving this.

**Comment by stevemautic** [comment]
@BharadwajMvd  I have the same problem. What did you do to solve this?
