### ISSUE TITLE
Error in Install

### ISSUE THREAD

**Issue by himel2017** [mautic/mautic#6355]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
i m trying to isntall mautic on my server , i have created database, and now in step one i have filled all database necessary info but and click next , i got below error :

An error occurred while attempting to install the data: An exception occurred while executing 'CREATE TABLE newwtweets (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, page_id INT DEFAULT NULL, asset_id INT DEFAULT NULL, is_published TINYINT(1) NOT NULL, date_added DATETIME DEFAULT NULL, created_by INT DEFAULT NULL, created_by_user VARCHAR(255) DEFAULT NULL, date_modified DATETIME DEFAULT NULL, modified_by INT DEFAULT NULL, modified_by_user VARCHAR(255) DEFAULT NULL, checked_out DATETIME DEFAULT NULL, checked_out_by INT DEFAULT NULL, checked_out_by_user VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, media_id VARCHAR(255) DEFAULT NULL, media_path VARCHAR(255) DEFAULT NULL, text VARCHAR(280) NOT NULL, sent_count INT DEFAULT NULL, favorite_count INT DEFAULT NULL, retweet_count INT DEFAULT NULL, lang VARCHAR(255) DEFAULT NULL, INDEX IDX_AEF00FF412469DE2 (category_id), INDEX IDX_AEF00FF4C4663E4 (page_id), INDEX IDX_AEF00FF45DA1941 (asset_id), INDEX newwtweet_text_index (text), INDEX newwsent_count_index (sent_count), INDEX newwfavorite_count_index (favorite_count), INDEX newwretweet_count_index (retweet_count), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.   

But i already setup on my php admin (collation_server=utf8_unicode_ci
character_set_server=utf8  ) still i saw the error.

I m not getting 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @himel2017 !
We don't know anything about your version, etc. Please chat on Slack for installation issues and report bugs here.

Thanks !
