### ISSUE TITLE
Bug with special chars in custom multi select field

### ISSUE THREAD

**Issue by Enc3phale** [mautic/mautic#6356]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Inside contact edit view, if you submit a multi select field with selected value wich contain specials chars

![screenshot_2018-07-25 edit 1](https://user-images.githubusercontent.com/27768270/43187293-4fc9a36e-8ff1-11e8-8cca-58a81f56df4b.png)

because of CleanFormSubscriber event

LeadType.php L.202  
`$builder->addEventSubscriber(new CleanFormSubscriber(['clean', 'raw', 'email' => 'email']));`

who clean all input before Symfony validation, Symfony can't compare send values with original values and validation fail.

![screenshot_2018-07-25 edit](https://user-images.githubusercontent.com/27768270/43187569-08a501ee-8ff2-11e8-98ad-96c62d0aeb06.png)

If anyone has an idea to fix this bug without impacting security and other Mautic components , because this cleaning event is called in many place of Mautic.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 

### Steps to reproduce:
1. Create a custom field with `Select - Multiple` type and `Contact` object
2. Add one value `it does`, second value `it doesn't` and third value `love <3`
3. Create a contact and try to apply this custom value
4. When you save with second or third value, error appear
 
### Log errors: 

![screenshot_2018-07-25 symfony profiler](https://user-images.githubusercontent.com/27768270/43187998-5e2760a2-8ff3-11e8-851b-cf3c4abfebad.png)

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi @alanhartless & @escopecz we'd need help to work on it please :)
Thanks for your advices :)

**Comment by escopecz** [comment]
How about to validate if the value has a special char and throw a form validation error that option values cannot have such characters?

**Comment by npracht** [comment]
@escopecz this is not acceptable from a user perspective. We should be able to use special chars!!

**Comment by Enc3phale** [comment]
Yes it work with special chars in label.
So we need to update UI to prevent customers to insert special chars in Value, because a lot do that.
