### ISSUE TITLE
No Emails or Campaigns after Upgrade to version 2.14

### ISSUE THREAD

**Issue by Kingston1212** [mautic/mautic#6359]
Hello - after upgrading today to version 2.14 - I can open Mautic, it appears to be working fine, except when I click on Campaigns on the sidebar - nothing happens. I stay in the current screen and don't see my campaign list. Similar to when I go into Channel and click Emails -nothing happens. I should see my previous email templates? Any help would be much appreciated. 

<img width="318" alt="screen shot 2018-07-25 at 6 42 37 pm" src="https://user-images.githubusercontent.com/41712002/43236560-9f455dae-903a-11e8-9a21-e7f9c5d49322.png">

**Comment by alanhartless** [comment]
Reads like your database didn't upgrade successfully. Keeping the issue template and filling it in would have walked you through checking your logs to confirm this. 

Please check app/logs for the latest log to see what's there after trying to clicking on email or campaigns. 

If your database didn't migrate successfully, then ssh into the server, cd into your Mautic installation and run `php app/console doctrine:migrations:migrate` and follow the prompts.

**Comment by Kingston1212** [comment]
@alanhartless thanks so much for your reply. I am not a tech person and trying to get this to work on my own. I checked the log - thank you. This was the first line and they are all about the same errors. Any help would be much appreciated. Thanks.



 `[2018-07-26 00:00:05] mautic.NOTICE: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT m0_.is_published AS is_published_0, m0_.date_added AS date_added_1, m0_.created_by AS created_by_2, m0_.created_by_user AS created_by_user_3, m0_.date_modified AS date_modified_4, m0_.modified_by AS modified_by_5, m0_.modified_by_user AS modified_by_user_6, m0_.checked_out AS checked_out_7, m0_.checked_out_by AS checked_out_by_8, m0_.checked_out_by_user AS checked_out_by_user_9, m0_.id AS id_10, m0_.name AS name_11, m0_.description AS description_12, m0_.publish_up AS publish_up_13, m0_.publish_down AS publish_down_14, m0_.canvas_settings AS canvas_settings_15, m0_.allow_restart AS allow_restart_16, m1_.is_published AS is_published_17, m1_.date_added AS date_added_18, m1_.created_by AS created_by_19, m1_.created_by_user AS created_by_user_20, m1_.date_modified AS date_modified_21, m1_.modified_by AS modified_by_22, m1_.modified_by_user AS modified_by_user_23, m1_.checked_out AS checked_out_24, m1_.checked_out_by AS checked_out_by_25, m1_.checked_out_by_user AS checked_out_by_user_26, m1_.id AS id_27, m1_.title AS title_28, m1_.description AS description_29, m1_.alias AS alias_30, m1_.color AS color_31, m1_.bundle AS bundle_32, m0_.category_id AS category_id_33 FROM maudm_campaigns m0_ LEFT JOIN maudm_categories m1_ ON m0_.category_id = m1_.id':  Unknown column 'm0_.allow_restart' in 'field list' (uncaught exception) at /home/******/contact.*****.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 while running console command `mautic:campaigns:rebuild` [] []`
