### ISSUE TITLE
Send form results with HTTP link turns into tracking

### ISSUE THREAD

**Issue by fphunzz** [mautic/mautic#6362]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When a form field is filled with a link with HTTP or HTTPS (http://www.google.com), Mautic will add a tracking code into it. This happened while using "Send form results" within Form > Actions

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.0.27

### Steps to reproduce:
1. Create a form with a Send form result action, fill a email to receive and the following options: Send immediately, do not send to contact, do not send to owner
2. Add it to a external website page
3. Fill the form with a HTTP or HTTPS link like https://google.com.br
4. Open the email and the link will be a Mautic url with tracking into it
 
### Log errors: 

No error.

![capturar](https://user-images.githubusercontent.com/38570471/43259578-1260204a-90ad-11e8-9759-bcaf650a45e9.JPG)

**Comment by npracht** [comment]
Hello @fphunzz;
Reported here https://github.com/mautic/mautic/issues/6044 and it has been fixed in 2.13.0. Please update !

Best
