### ISSUE TITLE
after update 2.14 I can't access campaign and emails section

### ISSUE THREAD

**Issue by carlo1s** [mautic/mautic#6364]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
Hi!

Again, please fill in the complete information requested by the issue template otherwise we cannot help you. 

This is a duplicate of https://github.com/mautic/mautic/issues/6359.
