### ISSUE TITLE
Email Stats went crazy after update to 2.14.0

### ISSUE THREAD

**Issue by FranSanchezOria** [mautic/mautic#6367]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
Hi there,

After updating yesterday, I opened one of my emails. It took way longer than usual to open it, about 30 seconds or so. Once the page loaded, I saw the stats here attached, which are totally inaccurate. This email is sent about 60-80 times per day, in a campaign that contains this single email, not recurring. There is no way the email was clicked 900,000 times (I wish though!).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.1.13-1+ubuntu14.04.1+deb.sury.org+1

### Steps to reproduce:
1. Click on an email to see the stats
![screen shot 2018-07-26 at 4 49 24 pm](https://user-images.githubusercontent.com/12048223/43297067-9874f06e-9181-11e8-90e3-e4abd3731246.png)

2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mareksotak** [comment]
I can confirm this issue, just a note, that the table below the Email stats showing the links clicks is displaying correct values.

**Comment by heathdutton** [comment]
Could you provide the steps to reproduce, given a stock Mautic installation?

That would help get the ball rolling for a fix.

**Comment by FranSanchezOria** [comment]
Hi heathdutton,

To be honest I am not too sure how to reproduce this problem. It happened in my production environment, I have been using it for over a year. All email stats are out of whack, just for click counts. I could provide you access.

**Comment by YosuCadilla** [comment]
@FranSanchezOria  @mareksotak  Please guys provide more information so we can help you.
With no steps to reproduce and no error msgs it's just not possible.

**Comment by YosuCadilla** [comment]
Curious behavior, I bet it has something to do with date format

**Comment by jbransen** [comment]
I also experience this bug (both in production and a development environment), and looked into it a bit. The query that is constructed for an e-mail with some translations is (in `EmailBundle/Model/EmailModel.php:1895`):

```
SELECT DATE_FORMAT(t.date_hit, '%Y-%m') AS date, COUNT(*) AS count
FROM page_hits t
LEFT JOIN email_stats es ON t.source_id = es.email_id AND t.source = "email"
WHERE (t.date_hit BETWEEN :dateFrom AND :dateTo)
AND (t.source_id IN (:email_ids))
GROUP BY DATE_FORMAT(t.date_hit, '%Y-%m')
ORDER BY DATE_FORMAT(t.date_hit, '%Y-%m') ASC
LIMIT 4
```
The reason why the numbers are too high is that there is a LEFT JOIN on `email_stats`, but per row in `page_hits` there are many matching rows in `email_stats`. Note that the `ON` clause is also weird, as the second expression doesn't refer to the `email_stats` table and thus doesn't belong in the clause (I'd call this invalid SQL, even though the DB happily accepts it). Maybe it should be `em.source`, but even then I am not sure why the join is there in the first place, as `em` is not used in the rest of the query.

Maybe this helps to solve the issue? Changing the `t` to `em` seems to resolved it, but as I don't understand the intention of the join I am not just committing that.

**Comment by bmd-cthayer** [comment]
Hi I eliminates the left join all together. It didn't seem to have any particular purpose. Afterwards the numbers are reporting correctly.

**Comment by heathdutton** [comment]
Thanks @jbransen for finding a workaround! Would you be willing to put together a PR?
