### ISSUE TITLE
Pending emails

### ISSUE THREAD

**Issue by FranSanchezOria** [mautic/mautic#6368]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
I have pending emails in one of my campaigns and I am not sure how to send those pending ones. I tried: /app/console mautic:campaigns:trigger --campaign-id 28

Result

Triggering events for campaign 28
Triggering events for newly added contacts
144 total events(s) to be processed in batches of 100 contacts
  32/144 [======>---------------------]  22%PHP Warning:  Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256' (this will throw an Error in a future version of PHP) in /home/n/domains/crm.n.et/public_html/app/cache/prod/appProdProjectContainer.php on line 6413
PHP Warning:  Use of undefined constant MCRYPT_MODE_CBC - assumed 'MCRYPT_MODE_CBC' (this will throw an Error in a future version of PHP) in /home/n/domains/crm.n.et/public_html/app/cache/prod/appProdProjectContainer.php on line 6413
 144/144 [============================] 100%

16 total events were executed
128 total events were scheduled

Triggering scheduled events
82 total events(s) to be processed in batches of 100 contacts
 48/82 [================>-----------]  58%PHP Warning:  preg_match_all(): Unknown modifier 'c' in /home/n/domains/crm.n.et/public_html/app/bundles/CoreBundle/Helper/UrlHelper.php on line 179
 82/82 [============================] 100%

82 total events were executed
0 total events were scheduled

Triggering events for inactive contacts
0 total events were executed
0 total events were scheduled

Some emails were sent, but majority still pending. Can someone help me understand what's going on and how to clear all pending emails?

![screen shot 2018-07-27 at 9 58 57 am](https://user-images.githubusercontent.com/12048223/43297420-d56584d2-9183-11e8-88b6-046468b15c79.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.1.13-1+ubuntu14.04.1+deb.sury.org+1

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by FMSGiganti** [comment]
I get the same problem... Anyone more?!

**Comment by gcoli6** [comment]
Same problem here.

**Comment by mbrinson** [comment]
Same problem here as well.

**Comment by YosuCadilla** [comment]
I tested with 2.14.1-beta and it seems NOT to solve the issue, here's a complete list of possibly related issues: #6515 #5546 #6482 #6419 #6211 #6433 #6460 #6156 #6321 #6368 #63

#63 as seen here: mautic/docker-mautic#63

On #6156 I posted a workaround that might help some of you.

**Comment by Carlos-mb** [comment]
2.14.2 is failing to me

I'm really desperate with this software :(

![image](https://user-images.githubusercontent.com/39302320/45980801-4824f400-c053-11e8-9b3d-55e879736896.png)

**Comment by Carlos-mb** [comment]
@YosuCadilla, I hope will not be a problem if I ask you directly. I'm absolutly desperate with this software. I have been using it for 10 days and I have had to fix two or three internal 500 errors and now this.

You had this issue to.. in this campaign there is NO contact segment change... so... 

It's just a drip campaign with some conditions if email clicked for changing contact tags. If I clone it and I deactivate the current campaign... Could it work? I guess that emails will not be send egain because all of then are marked as "marketing"

I'll thank ANY help.

**Comment by Carlos-mb** [comment]
I have deleted all conditions and tag modifications in campaign and it still fails.

**Comment by Carlos-mb** [comment]
What sense does this have? 

I would love this software if it did what it's supposed it does. But It fails over and over. 

The big problem is that i don't know any alternative. EasyMail7 is also selfhosted but it has an horrible interface and it also failed during basic installation. 

Mailchimp is becaming a real alternative because it maybe worth if I think of I've been 50 hours in 10 days fixing Mautic errors. 

I really want to make this work, but maybe it makes no sense to keep trying it. 

Please, I'm desperate. 

Does any one has an working installation? 

Does this really works? Should I keep trying?

**Comment by Carlos-mb** [comment]
Did you change the trigger date or emails?

I'm thiking about this as the origin of the issue in my case.

**Comment by YosuCadilla** [comment]
Please be patient @Carlos-mb, the campaigns engine was rebuilt from scratch not long ago and while it works fine for most people, a few of us are encountering problems. 

The bug is being debunked right now and will probably be solved with 2.14.2

**Comment by Carlos-mb** [comment]
Thank you @YosuCadilla

**Comment by jqvanet** [comment]
Same problem here. 
Any solution?

**Comment by yrammos** [comment]
Facing the same issue under 2.14.2 with major business disruption as a consequence.

Any updates!?

**Comment by yrammos** [comment]
#6943

**Comment by escopecz** [comment]
Is this still an issue with 2.15.1?

BTW, Mcrypt is an encryption library that hasn't be maintained for several years. Newer PHP versions removed its support. Use/install OpenSSL instead.

**Comment by pstevens71** [comment]
I don't know if this is your issue, but I've been troubleshooting this myself.  Seems everything is working as intended.  I had the campaign set up with a "SEGMENT" type email.  You can only send segment emails to a contact ONCE!  Therefore if you try to do it again, it fails and goes into pending status.  If you want to send the same email to a contact more than once, it needs to be a "TEMPLATE" type email.

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
