### ISSUE TITLE
Email replies are not tracked

### ISSUE THREAD

**Issue by levrykurniawan** [mautic/mautic#6369]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
In previous versions (2.13.1), email replies were well-tracked so decisions taken based on email replies in campaigns worked properly.

But on Mautic 2.14.0, the reply email can no longer be tracked, except for the first time only.

I've done an investigation to check this issue, and I found there is one row created in the **cache_items** table when there is email reply tracked after executing command `mautic:email:fetch`, which I did not find in the previous version.

![](https://user-images.githubusercontent.com/40631294/43299741-bac27ae8-9185-11e8-8faa-c5929cdc5146.png)

If I delete that row, tracking can worked properly. But that row will re-create so the next tracking will not work again.

The temporary solution that can be done is to rename or delete the **cache_items** table, or it could be by changing the **item_lifetime** column property to _not null_ so that no rows are created in the table.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 5.6.36

**Comment by alanhartless** [comment]
This is the reason for #5793 so it's the same issue so closing this as a duplicate. The PR that fixes this is coming today.
