### ISSUE TITLE
Test Email

### ISSUE THREAD

**Issue by Intertext1** [mautic/mautic#6371]
Hi everyone,

we started using Mautic after a while. We will use some triggers and emails whose will go to our costumers. When I go inside "channels" on "emails" area, I try to send a "Test Email" but i don't receive nothing (in spam neither).

I tried 10 times, with my business email and personal email as well, but I don't receive nothing.

What are we doing wrong?

Thanks.

**Comment by acheloos-m** [comment]
Do you set up email cronjob correctly?

when calling 
```shell
sudo crontab -e -u webserver-user
```
you should have line like 

```shell
*/10 * * * * /path/to/php /path/to/mautic/root/app/console mautic:emails:send
```

you could also try so send them manually to check, if email setup is configured correctly:

```shell
sudo -u webserver-user php /path/to/mautic/root/app/console mautic:emails:send
```

**Comment by npracht** [comment]
From where are you sending emails ? What is the email configuration within your mautic ?
