### ISSUE TITLE
 Contact Preferences Logging on contact activity page

### ISSUE THREAD

**Issue by spka** [mautic/mautic#6373]
| Q  | A
| ---| ---
| Feature request | x
| Enhancement | x

## Description:
To my knowledge it's not easily visible when a contact changes preferences. It would be cool if the contact log showed these changes.

**Suggestion mock-up:**

![preflog](https://user-images.githubusercontent.com/13484241/43311736-82b8746c-918b-11e8-8bac-93283ee226b6.jpg)

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
