### ISSUE TITLE
Duplicate point when change contact segment

### ISSUE THREAD

**Issue by tamdvms** [mautic/mautic#6387]
| Q   | A
| --- | ---
| Mautic Version 2.14.0 | 
|  PHP Version 7.0.30| 

Description:
Point inscrese double when change contact segment

Steps to reproduce the bug:
1. Create segment A
2. Create segment B
3. Add contact to segmnet A
4. Create email 001
5. Create segment compaign -> select segment A-> Add action send email -> send email 001 -> add action "Open email" 
6 On action Open email add 2 action: 
+ "Adjust contact points" add 5poin if email open
+ "Modify contact's segments" -> add to Segmeng B and Remove form sesgment A

### Log errors: 
Compaing builder
![bug](https://user-images.githubusercontent.com/34687143/43383130-3d46bdaa-9404-11e8-8f91-8def6a6bb5f5.png)

Contact Log:
![log_1](https://user-images.githubusercontent.com/34687143/43383394-1199057c-9405-11e8-9197-880fb1759cd1.png)
![log_2](https://user-images.githubusercontent.com/34687143/43383403-174af3cc-9405-11e8-84f5-7139ca6d463a.png)

I also remove contact from current campaign but still error.

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
