### ISSUE TITLE
Site offline after automatic upgrade

### ISSUE THREAD

**Issue by himel2017** [mautic/mautic#6390]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
My Mautic Website was good but today i saw  there was a automatic upgrade done on my server, after that my site not working (Site offline) : https://crm.akij.net/Digitalmarketing/

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @himel2017 !
Did you try to use the standard command on your mautic instance ?
- Schema update
- Asset Generate
- Clear cache

Then tell us if you have error message there.
Thanks

**Comment by himel2017** [comment]
@npracht  
i didn't done anything, it was auto upgraded and when is saw i just deleted the cache folder.. pls help me to fix this issue.

**Comment by himel2017** [comment]
Here is the error

 👍 Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "mautic.emailtoken.subscriber" has a dependency on a non-existent service "mautic.lead.helper.primary_company". - in file /home/crmakij/public_html/Digitalmarketing/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php - at line 58

**Comment by himel2017** [comment]
also this script is problem: 

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                   
  The service "mautic.emailtoken.subscriber" has a dependency on a non-existent service "mautic.lead.helper.primary_company".  
                                                                                                                               

Content-type: text/html; charset=UTF-8

**Comment by escopecz** [comment]
There is no thing as automatic update. What do you mean by that?

See https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful to fix your instance
