### ISSUE TITLE
"Monitored Inbox" does not return old status for email which was not bounced

### ISSUE THREAD

**Issue by filchakov** [mautic/mautic#6391]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:
I use Mautic with integration to my general mailbox, which I use every day. 
If I enable monitoring inbox tool, Mautic will open all my new emails and try to find something for catching bounces emails. This is ok, but Mautic doesn't return status "New" for emails which were checked and was not identify as "bounce" email.
This is very not convenient because I can lose important email, didn't get an important reply which needs my reaction.
Can we fix it? Will be good, if Mautic will return status to email which was before checking "bounce".

| Q   | A
| --- | ---
| Mautic version | v2.14.0
| PHP version | 7.1

### Steps to reproduce:
1. Setting Monitored Inbox Settings
2. Create a campaign
3. Send an email to contacts
4. Get a reply from some contact
5. Mautic reading all my emails in my mailbox. And does not return status "not opened" for these emails.

**Comment by Bizcrony** [comment]
have you set up Monitored Inbox?

**Comment by filchakov** [comment]
sure. Monitored Inbox - working. a problem is that monitors not return status "not opened" after scanning all emails.
![screenshot from 2018-07-30 13-26-27](https://user-images.githubusercontent.com/2973867/43392526-9c3c9990-93fc-11e8-9f37-18583aff992b.png)

**Comment by escopecz** [comment]
I don't understand the expected behaviour. Why would monitoring should check "not opened" status?
