### ISSUE TITLE
ability to enable/disable URL tracking on Tweets

### ISSUE THREAD

**Issue by rogerwilks** [mautic/mautic#6394]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

| Bug report? | 

## Description:
MAutic is replacing URL that have been added to twitter messages. See example below: I am getting the same issue with asset and page links

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14

### Steps to reproduce:
1. Paste URL into twitter message 
2. send through a campaign
 
URL is replaced in the meaasge sent - Example
URL in tweet = https://www.bbc.co.uk/
URL in tweet received = http://77.68.95.164/r/ef54485d435d2d6f0cd8cbbb9?ct=YToyOntzOjY6InNvdXJjZSI7YToyOntpOjA7czo4OiJjYW1wYWlnbiI7aToxO2k6MzY7fXM6NzoiY2hhbm5lbCI7YToxOntzOjE0OiJzb2NpYWxfdHdpdHRlciI7aToxODt9fQ%3D%3D

### Log errors: 
No error showing up in the logs

**Comment by Woeler** [comment]
I'm pretty sure this is because you of course want to track your repsonse rate to your tweet and the clicks. So what mautic does is it creates a URL that goes to your mautic install, mautic logs that someone clicked the link in the tweet and then redirects the user to the actual site you want them to go to. It's a tracking feature, not a bug.

**Comment by rogerwilks** [comment]
no i think there is a bug for these reasons:

1. The link when it appears in Twitter appears as text, not a clickable link.
2. the link it creates is not the correct destination - as stated above when i create the tweet with the following URL in https://www.bbc.co.uk/ it sends the tweet out the tweet with http://77.68.95.164/r/ef54485d435d2d6f0cd8cbbb9?ct=YToyOntzOjY6InNvdXJjZSI7YToyOntpOjA7czo4OiJjYW1wYWlnbiI7aToxO2k6MzY7fXM6NzoiY2hhbm5lbCI7YToxOntzOjE0OiJzb2NpYWxfdHdpdHRlciI7aToxODt9fQ%3D%3D (as text). If i copy and paste that address into a browser it is not the same destination.

i may have done something wrong in the config but i don't think i have.

**Comment by Woeler** [comment]
When I click that link I'm sent to the website of the BBC. I'd have to check out why it's not posted as a link. Never had this issue. Might be because your mautic is not actually on a domain, but on an IP as the URI.

**Comment by npracht** [comment]
Then it is more about a feature request to have the ability to disable tracking links on tweets.
Maybe you can hire @kuzmany for that if you need knowing that he did the same for SMS.

**Comment by rogerwilks** [comment]
No i don't believe its an enhancement and its not the case that i wish to disable tracking. I am happy with tracking its just the link in the tweet (once received) is not a clickable link so people can't go to the link without copying and pasting it into a browser.

Woeler - i have found out why it was not directing me to the correct address. it was the same issue as #6400 where you get a 500 error if logged in to mautic.

**Comment by npracht** [comment]
This is an issue on Twitter side @rogerwilks. I guess that the link is too long of some chars are not supported like % for instance?

**Comment by rogerwilks** [comment]
really - its used to work but has stopped? is there any workaround?

**Comment by kuzmany** [comment]
Try the same link Mautic tracking link copy Twitter? Works? 
Maybe It's bug, during the sent message to Twitter API (encoding) or Twitter API changes (https://twitter.com/TweetenApp/status/1023731222466490370)
