### ISSUE TITLE
Multi language support in campaigns when sending emails to different preferred locale contacts

### ISSUE THREAD

**Issue by drimlike** [mautic/mautic#6395]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | Yes

## Description:
As I noticed there is “Translations” for emails. When I'm sending a campaign, I was expecting that if a user has a preferred locale, the email will be automatically sent in that locale language if it is available. But it seems it doesn't and I would like to avoid duplicating all campaigns in all the languages. Is there a better way I am missing out? 
## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.14.0
| PHP version | 

### Steps to reproduce:
1. Put an ENGLISH (locale EN) user and a FRENCH (locale FR) user in a test segment
2. Have an email template available in both EN and FR and linked together
3. Set up a test campaign to send the multilingual email to the multilingual segment
4. It's not possible to select an email master, you have to choose either the EN or the FR version of that email
5. Select the EN version assuming it could be the master
6. Publish and run the campaign to send the emails to the 2 multilingual users
7. Both users receive the EN email when one of them is FRENCH and should have received the FR version of the email

**Comment by dsp76** [comment]
Maybe a general problem with the "preferred local" field? See also https://github.com/mautic/mautic/issues/4754

Is seems to mix up the value of the field with the (translated) label...

**Comment by drimlike** [comment]
It works now after some more tests.
Issue resolved. Thanks!

**Comment by vdavid** [comment]
Any info on what solved it @drimlike ? I'm just setting up Mautic for many locales and I'm trying to avoid mistakes.

**Comment by drimlike** [comment]
@vdavid nothing special, just map the email translations together and it should work as expected.
