### ISSUE TITLE
form integrated into preference center does not submit

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6397]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
A form that is integrated into a landing page set as a preference center does not submit.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 

### Steps to reproduce:
1. Create a form
2. Create a landing page, set it as the preference center. In the builder add some bloc form the pref center and add the form previously created with the token {form=ID}
3. Create an email, assign the pref center to this email.
4. Shoot the email
5. When you received the email, click on the unsubscribe link. You should land on the pref center.
6. Submit the form you integrated.
7. Check the form result and see that there is no submission.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Merged in 2.15.2
