### ISSUE TITLE
Error 500 when opening tracked links on email when logged in to Mautic

### ISSUE THREAD

**Issue by guizero** [mautic/mautic#6400]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  x
| Feature request? | 
| Enhancement? | 

## Description:
When creating an email for a campaign with links AND testing it while logged in to Mautic it breaks into a 500 error. 

This only happens if the user is logged in to Mautic.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.30-0ubuntu0.16.04.1

### Steps to reproduce:
1. Create an email for a campaign
2. Create a campaign to send the link
3. Add UTM tags for the links
4. Create a contact and add to campaign
5. Open the sent email and click on any link
6. Mautic will raise a 500 error
 
### Log errors: 

[2018-07-30 14:16:15] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getId() on null" at /var/www/html/mautic/app/bundles/LeadBundle/Helper/ContactRequestHelper.php line 307 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getId() on null at /var/www/html/mautic/app/bundles/LeadBundle/Helper/ContactRequestHelper.php:307)"} []

**Comment by omarf13** [comment]
I get the same issue (i just closed #6401 because it's a duplicate issue).  Identical behaviour logging out  of mautic and then clicking the email link to the landing page works.

**Comment by FranSanchezOria** [comment]
I noticed the same problem, I didn't know it was because I'm logged in.

**Comment by dubsaru** [comment]
I am experiencing a similar issue. However, it doesn't matter if the user is logged in or not. I have cleared the cache and reset permissions but the issue persists.

I am on the same version of Mautic and PHP.

**Comment by morettic2015** [comment]
Same issue here. But only for logged in users. Any fix?

**Comment by npracht** [comment]
Please test #6441
