### ISSUE TITLE
Email Tracking link not opening on Safari browsers

### ISSUE THREAD

**Issue by himel2017** [mautic/mautic#6409]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
I am using mautic latest version and i have send a email campaign with link in email body to my users, but few peoples try to open link in safari browser it not working.. (showing site is offline)...  how can i fix that issue ?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by rogerwilks** [comment]
are you logged into Mautic at the same time in safari? i had this issue with chrome but if you clear your cache and make sure you are logged out and try again. it worked for me

**Comment by himel2017** [comment]
i m using latest version and if i click link with login , then it not working and if logged out, then link working...

**Comment by npracht** [comment]
Then closing in favor of https://github.com/mautic/mautic/issues/6400 where it is already reported ;)
