### ISSUE TITLE
Campaign don't adjust lead score points

### ISSUE THREAD

**Issue by jhrocha** [mautic/mautic#641]
Hi, guys. After created my campaign flow, on campaing builder, my leads dont adjusts points.
The other actions are executed, but the points don't.

My log --> 

mautic.DEBUG: CAMPAIGN: Campaign triggered for event type form.submit(form.submit17) [] []
mautic.DEBUG: CAMPAIGN: lead not anonymous; abort [] []

<img width="1440" alt="captura de tela 2015-07-10 as 14 18 23" src="https://cloud.githubusercontent.com/assets/5194011/8624487/8ec3521c-270e-11e5-81c7-3079b6d84139.png">

**Comment by jhrocha** [comment]
But, in the mautic, a event was triggered. 
<img width="794" alt="captura de tela 2015-07-10 as 14 47 06" src="https://cloud.githubusercontent.com/assets/5194011/8625135/277d4f54-2713-11e5-829a-638779b458f6.png">

**Comment by alanhartless** [comment]
Hi,

I can't reproduce this.  I setup a campaign exactly as your screenshot, submitted the form in an anonymous browser session (not logged into Mautic), ran the campaign trigger command (via cron) and the points were added to the lead and he was moved into the list.

Just to rule out the obvious, in your adjust lead points action, points has something greater than 0 right?

Thanks,
Alan

**Comment by alanhartless** [comment]
Hi @jhrocha,

Just checking in for an update to see if you are still reproducing this or have some advice on how I can reproduce it?

Looking to release 1.1.3 this week so if there is a problem, we definitely want to include the fix!

Thanks,
Alan

**Comment by alanhartless** [comment]
this has been fixed.
