### ISSUE TITLE
Redo Do Not Contact Not Working

### ISSUE THREAD

**Issue by dev-love** [mautic/mautic#6411]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Setting the status of Do Not Contact to Contact (again) isn't working.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.27

### Steps to reproduce:
1. Open a contact
2. Go to Preferences
3. Unselect all channels (--> Do Not Contact status)
4. Go to Preferences again
5. Select one or more channels (like email)
6. Nothing happens; Do Not Contact status still set
 
### Log errors: 

No log errors

**Comment by npracht** [comment]
This has been addressed
