### ISSUE TITLE
Add Additional Channels to Preference Center

### ISSUE THREAD

**Issue by dev-love** [mautic/mautic#6412]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
Right now there are only two channels in the Preference Center (emails & text messages). However, in most cases people might want to select their communication preferences for other channels as well, like calls or postal mailings.

These settings would also be important history or log entries to be fully GDPR compliant.

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
