### ISSUE TITLE
Buttons not displaying as expected

### ISSUE THREAD

**Issue by EnableITmike** [mautic/mautic#6414]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? | 

## Description:
button on the landing page appears different live than in the builder (see screenshot).

Right Button:
![right button](https://user-images.githubusercontent.com/42002909/43528682-709de932-95a1-11e8-9746-77a96a42e45a.png)

Wrong Button:
![wrong button](https://user-images.githubusercontent.com/42002909/43528683-70b5db5a-95a1-11e8-9295-07197ee92949.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by alanhartless** [comment]
Please fill in the "If a bug" section.

**Comment by npracht** [comment]
Fixed in https://github.com/mautic/mautic/pull/6455
