### ISSUE TITLE
"From name" not including text inside parentheses ()

### ISSUE THREAD

**Issue by MRG95** [mautic/mautic#6415]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
If your "From name" for your emails contains parentheses, for example **Matt G (oPryzeLP)** the **(oPryzeLP)** gets removed.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.31

### Steps to reproduce:
1. Add text wrapped in parentheses to an email's "From name" paremeter
2. Send the email and view the recipient

(Tested with Gmail)
 
### Log errors: 

No errors

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
