### ISSUE TITLE
(BUG) After 30th variation of a dynamic email content, filter's conditional operators ("equal", "less than", etc...) are not displayed in 31st variation

### ISSUE THREAD

**Issue by AlbanL74fr** [mautic/mautic#6417]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I am not sure that the number 30 is a coincidence or not, but the conditional operator doesn't not appear after I select a custom field which I know is correct. I used the same (contact) custom field in previous variations of this dynamic email content.

![image](https://user-images.githubusercontent.com/23435414/43563566-edb2de9a-964c-11e8-8716-b5c8bbc0b791.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 5.6.32

### Steps to reproduce:
1. Create an email template
2. Create a dynamic content with 30 variations with content and one and same particular custom field for each
3. Create a 31st variation for this dynamic content using the same custom field

Actual result : After selecting the custom field, the input drop down for the conditional operator is empty.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by AlbanL74fr** [comment]
Hi @npracht, I will, as soon as we install 2.14 on our staging env. I will update the issue accordingly.

**Comment by npracht** [comment]
Hi @AlbanL74fr any update ?
