### ISSUE TITLE
Mautic Mail error on campaign trigger

### ISSUE THREAD

**Issue by opb** [mautic/mautic#642]
Hi there

I'm seeing a mail error when triggering campaigns. The message which appears in the middle of the text below is the same message that I get emailed from our cron system, and the same as the message that shows up in the mautic app log. Is there any way to get more details?

```
www-data@production:~$ php /var/www/mautic/app/console mautic:campaigns:trigger --env=prod
Triggering events for campaign 1
Triggering first level events
3 total events(s) to be processed in batches of 100
 3/3 [============================] 100%
0 event(s) executed

Triggering scheduled events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering 'non-action' events
0 event(s) executed

Triggering events for campaign 2
Triggering first level events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering scheduled events
16 total events(s) to be processed in batches of 100
  0/16 [>---------------------------]   0%[2015-07-11 08:44:39] mautic.ERROR: [MAIL ERROR]  [] []
 16/16 [============================] 100%
0 event(s) executed

Triggering 'non-action' events
0 event(s) executed

Triggering events for campaign 3
Triggering first level events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering scheduled events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering 'non-action' events
0 event(s) executed

Triggering events for campaign 4
Triggering first level events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering scheduled events
51 total events(s) to be processed in batches of 100
 51/51 [============================] 100%
0 event(s) executed

Triggering 'non-action' events
0 event(s) executed

Triggering events for campaign 6
Triggering first level events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering scheduled events
6 total events(s) to be processed in batches of 100
 6/6 [============================] 100%
0 event(s) executed

Triggering 'non-action' events
0 event(s) executed

Triggering events for campaign 7
Triggering first level events
0 total events(s) to be processed in batches of 100
0 event(s) executed

Triggering scheduled events
6 total events(s) to be processed in batches of 100
 6/6 [============================] 100%
0 event(s) executed

Triggering 'non-action' events
0 event(s) executed

www-data@production:~$
```

Also, I would appreciate if anyone has any input on whether the output looks OK apart from that error. Seeing things like:

```
6 total events(s) to be processed in batches of 100
 6/6 [============================] 100%
0 event(s) executed
```

makes me wonder if all is OK.

Many thanks!!

EDIT: forgot to say, those mail errors just started appearing a couple of hours ago, with no interaction on our end.

**Comment by sfahrenkrog** [comment]
I got the same mail error when I was using an email with a soft bounce. This email address was rejected from an mail server. 

If you use mandrill as email sender you could see the specific reason in the outbound messages log.

**Comment by alanhartless** [comment]
@opb What mail transport service are you using?

**Comment by opb** [comment]
Sorry for the delay in getting back to you. This was Mandrill, and cleared up approx 18hrs after it first started. Not something to do with Mautic, clearly! The error line in the code comes from `MailHelper` with the actual line as follows:
```php
$this->factory->getLogger()->log('error', '[MAIL ERROR] ' . $error);
```
The `$error` appears to be blank. If I was more familiar with the codebase I'd have a look into it!

**Comment by alanhartless** [comment]
Thanks for the feedback.  It's likely that there was a temporary communication issue with Mandrill and Mautic just didn't record it.  I've added a PR that should make it into 1.1.3 that should handle logging the Mandrill API transport a bit better to assist with that.
