### ISSUE TITLE
Mautic 2.14 Forces extended bounce address as from address. Fails to send.

### ISSUE THREAD

**Issue by nelem** [mautic/mautic#6420]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
In app/bundles/EmailBundle/Helper/Mailhelp.php:370 it looks like a typo that forces the return address to be name+bounce@domain.com.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14 Prod upgraded from 12.13.1
| PHP version | PHP 7.0.30-0ubuntu0.16.04.1

### Steps to reproduce:
1. Try to send a test email from the EmailConfig screen. Outlook gives error 
550 5.7.60 SMTP; Client does not have permissions to send as this sender

becuase the from address is name+bounce@domain.com rather than name@domain.com

Possible typo?
`	if (!$isQueueFlush && ($bounceEmail = $this->generateBounceEmail())) {
			$this->message->setReturnPath($bounceEmail);
		} elseif (!empty($this->returnPath)) {
			$this->message->setReturnPath($this->returnPath);
		}
`
should be????
`	if (!$isQueueFlush && ($bounceEmail == $this->generateBounceEmail())) {
			$this->message->setReturnPath($bounceEmail);
		} elseif (!empty($this->returnPath)) {
			$this->message->setReturnPath($this->returnPath);
		}
`
At least, fixing the typo allows the test mail to send.
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Enc3phale** [comment]
Hi,
generateBounceEmail return `an email` or `false`, so it's not a typo this should be `$bounceEmail = $this->generateBounceEmail()`.
You say that `from address` is false, have you checked your email configuration?

**Comment by nelem** [comment]
I had a bounce mailbox configured to be the same as the outgoing mailbox. This causes the Return-Path to be re-written as name+bounce. 

So, without monitored inbox setting, will Mautic not monitor for bounces at all? How can we make Mautic monitor the same mailbox that the outgoing messages were sent from?

**Comment by npracht** [comment]
If you use a email router like shown here: https://www.mautic.org/docs/en/emails/bounce_management.html you can manage the bounces better.
