### ISSUE TITLE
Feature Request: oAuth2 Token Extension

### ISSUE THREAD

**Issue by digitall-it** [mautic/mautic#6421]
| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
The Mautic API allows authentication via oAuth2. However, after a token has been issued, this is valid for 14 days only. The user will need to reauthenticate when the token expires, by manually reissuing another token in their browser. It would be better if there was a function to automatically extend the validation period by issuing another token.

As the API is used for server to server communications, it seems overcomplicated to have to access the website periodically to issue a new token. Ideally using the token extension mechanism (is this possible by spec?) if a valid token is found, then the token extender could return a new token that is valid for 14 days. It would be enough for the software to make this api call periodically to refresh the authorization and prevent expiration.

I kindly ask to
1. Create a token extension REST point and corresponding API Library function to extend the token
or
2. Amend the documentation to specify what to do in that situation.

**Comment by Woeler** [comment]
While I do think this makes sense, I would like to point out to anyone reading this that you can configure the token lifetime yourself under Configuration -> API settings -> Refresh token lifetime (in days).

**Comment by digitall-it** [comment]
Thanks @Woeler, but even if you set the lifetime to a very long period (four months, for example), you would have to relogin sooner or later, even if you use the API everyday. That’s because there’s no way for the system to ask for a newer token. Everyone I’ve chatted about says to just use Basic Auth, but it doesn’t even have an API login, you need to memorize your actual login and password. I love Mautic and I hope one day Basic Auth gets deprecated, because the PHP library makes so easy to use OAuth it’s a shame not to actually use it.

**Comment by Woeler** [comment]
Totally agree.

**Comment by escopecz** [comment]
AFAIK, this is Oauth2 standard workflow.

**Comment by digitall-it** [comment]
@escopecz Thank you for checking out this enhancement request. Would you please check out the [Refreshing Access Tokens](https://www.oauth.com/oauth2-servers/access-tokens/refreshing-access-tokens/) oAuth 2.0 documentation page? If the request falls within the spec, can the issue be reopened?

**Comment by RCheesley** [comment]
Hi there, as we are only providing features for Mautic 3.x going forward, can you confirm if this continues to be an issue in Mautic 3.0.1? Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
