### ISSUE TITLE
Form action URL not updated in the cached_html column (form table) for all mautic forms after change of base URL for mautic from subdir to subdomain URL

### ISSUE THREAD

**Issue by anarchist912** [mautic/mautic#6424]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
After Upgrade to mautic 2.14.0 and changing the mautic instance URL form a subfolder URL to a subdomain URL in the mautic configuration — cache cleared, form cache rebuilt — the embedded form (in Wordpress) still did not work. ("Please wait forever..") Of course I changed the settings in the WP mautic plugin accordingly, also.

The mozilla console told me that when clicking the submit button of the form, the form/generate.js - File was still trying to be accessed via the old base URL. So the bug seems to be that the according line (action="" URL) in the HTML form template does not get updated  with the new base URL of the mautic instance.

I changed it manually via phpmyadmin in the forms table, column "cached_html". Had to change it for 4 forms. So actually some of my forms got updated with the new base URL. But 4 didn't.

After that it worked again.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | PHP Version 7.0.31-1+ubuntu16.04.1

### Steps to reproduce:
1. change mautic base URL in the config
2. Check column `cached_html` in MySQL table `forms` for occurrence of the old baseURL.
 
### Log errors: 

No error logs found.

**Comment by escopecz** [comment]
See https://www.mautic.org/docs/en/forms/index.html
