### ISSUE TITLE
Tracking urls | Campaign | Html

### ISSUE THREAD

**Issue by felipeoliveiravorance** [mautic/mautic#6426]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  X
| Feature request? | 
| Enhancement? |  X

## Description:

I create campaign with email marketing with custom html, when carried out the test, it sends with the links "hrefs" configured correctly in the html,

See: ahref="https://spasorocaba.com.br/promocoes" style="color: rgb(255,255,255);">

However, when I run a campaign, the link "href" is completely modified and when clicked, goes to a page that does not exist, including where the mautic is installed, see how it goes:

A h ref = "https://atendimento.spasorocaba.co m.br/r/f7573bf04191cbbc5952a6f74ct=YTo1On tzOjY6InNvdXJjZSI7YToyOntpOjA7czoxNDoiY2FtcGFpZ24uZXZlbnQiO2k6MTtpOjQ4O31zOjU6ImVtYWlsIjtpOjY7czo0OiJzdGF0IjtzOjIyOiI1YjY3Yz hiMjI5M mU0NjM3NjA3NDU0IjtzOjQ6ImxlYWQiO2k6 MzI4Nzk7czo3OiJjaGFubmVsIjthOjE6e3M 6NToiZW1haWwiO2k6Njt9fQ%3D%3D&utm_source=Test-03444&utm_medium=email" style = "color:  rgb (255, 255, 255); ">

url site: spasorocaba.com.br
url instalation mautic: atendimento.spasorocaba.com.br

| Q   | A
| --- | ---
| Mautic version | v2.14.0
| PHP version | 7.0

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello, i think it is reported here: https://github.com/mautic/mautic/issues/6400
