### ISSUE TITLE
mautic:campaigns:rebuild not work after update to 2.14

### ISSUE THREAD

**Issue by miguelurtado** [mautic/mautic#6428]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 7.0.31

### Steps to reproduce:
1. php app/console mautic:campaigns:rebuild

2.
![image](https://user-images.githubusercontent.com/3810528/43726882-c0694780-9976-11e8-88db-932d42fef753.png)

Campaign 15:
![image](https://user-images.githubusercontent.com/3810528/43727293-e87d83e8-9977-11e8-8897-746ea57dfa4d.png)

After update to Mautic 14.0 the command hangs on that part.

### Log errors: 
Null

**Comment by heathdutton** [comment]
You have no entries in your logs, but `mautic:campaigns:rebuild` hangs when removing contacts from the campaign? Do I have that right?

**Comment by miguelurtado** [comment]
Right!

**Comment by miguelurtado** [comment]
This is just an example. All Segments that use thread are in error.

**Comment by jsimoes** [comment]
Just try to enable the campaign to allow re-runs.. it fixed the issue for us

**Comment by miguelurtado** [comment]
Hello @jsimoes 
Do you say enable "Allow contacts to restart the campaign"? This not work!

**Comment by miguelurtado** [comment]
If execute php app/console doctrine:schema:update --force

This error return:

`An exception occurred while executing 'ALTER TABLE campaign_leads ADD CONSTRAINT FK_5995213D55458D FOREIGN KEY (lead_id) REFERENCES leads (id) ON DELETE CASCADE':

  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mautic_db`.`#sql-b87_36f97`, CONSTRAINT `FK_5995213D55458D` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`)
   ON DELETE CASCADE)`

**Comment by YosuCadilla** [comment]
It would seem the problem is with the relationship between FOREIGN KEY (`lead_id`)  and  `leads` (`id`)
Can you please check your custom fields settings for those fields and report back?

**Comment by miguelurtado** [comment]
Hello,

Actually for some reason in my database, they had some obsolete data calling a foreign key did not exist. To resolve this I have removed all obsolete data manually:

This was very useful.

`SELECT * FROM Table1 WHERE id NOT IN (SELECT id FROM Table2)`

Thanks...!

**Comment by carloscaro** [comment]
We are having a similar issue after executing "mautic:campaigns:rebuild"; it gets into a infinite loop showing a message like:
...
 74272/74272 [============================] 100%
...
