### ISSUE TITLE
issue with save button preference center

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6429]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Customizing the text of the preference center button does not work.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 

### Steps to reproduce:
1. Create a preference center
2. Add the saveprefbutton bloc and customize the text button
![image](https://user-images.githubusercontent.com/31535432/43763362-e16ed6e8-9a2a-11e8-9cbe-2e8b87429370.png)
3. Create an email, assign this pref center and shoot the email.
4. Click on the unsubscribe link to land to the pref center. 
5. Check the text of the save pref button.
![image](https://user-images.githubusercontent.com/31535432/43763514-33ad7c2a-9a2b-11e8-919d-4e547459c62f.png)
This is a default text.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/6455
