### ISSUE TITLE
Dynamic Link Parameter in E-Mail 

### ISSUE THREAD

**Issue by sfahrenkrog** [mautic/mautic#643]
If I try to send an email with an dynamic parameter like 

http://domain.com/landing-page?email={leadfield=email}

the link got converted like this: 

http://domain.com/r/cccf1270c4c07ba41f7683bfa?ct=YTozOntzOjY6InNvdXJjZSI7YTowOnt9czo1OiJlbWFpbCI7TjtzOjQ6ImxlYWQiO2k6MjM7fQ%3D%3D=email@test.de

this redirects to a link like: 

http://example.com/landing-page?email   

So it seems as if only the part http://domain.com/landing-page?email= get converted into a link and after that the leadfield got replaced. 

Maybe a good solution would be to first replace all leadfields in the email and then convert the links? 

Seen with Mautic v1.1.2

**Comment by ptcc** [comment]
I need this use case too
:+1:

**Comment by alanhartless** [comment]
I believe this is likely related to #530.  Would you be wiling to apply that patch and test?

Thanks,
Alan

**Comment by sfahrenkrog** [comment]
Thank you very much! Will test it and give feedback! 

Greetings,
Sebastian

**Comment by sfahrenkrog** [comment]
Tested it! 

Now the link just got the leadfield replaced. So the result is: 

This:
http://example.com/landing-page?{leadfield=email}

got converted into this: 
http://example.com/landing-page?email=email@test.de

But no more link tracking! So this is a solution but the link click got no longer recorded right? 

Would be nice to have both: a tracked link and a dynamic link parameter. 

Thank you very much for your help! 

Greetings 
Sebastian

**Comment by sfahrenkrog** [comment]
If I use a link like that: 

{pagelink=1}&email={leadfield=email|true}

it got converted to: 

http://example.com/r/5742d0aaedb5fca494c7910d4?ct=YTozOntzOjY6InNvdXJjZSI7YTowOnt9czo1OiJlbWFpbCI7TjtzOjQ6ImxlYWQiO2k6MjM7fQ%3D%3D&email=test@test.de

but the redirect don't forward the parameter to the final page. I think it would be an option to forward all other get parameters in the redirect call?

**Comment by alanhartless** [comment]
Hi @sfahrenkrog 

Would you mind help testing #671?

Thanks!
Alan

**Comment by sfahrenkrog** [comment]
Amazing! Of course! Will check it!
Am 17.07.2015 00:42 schrieb "Alan Hartless" <notifications@github.com>:

**Comment by sfahrenkrog** [comment]
Sorry, a little late. Worked for me too.
