### ISSUE TITLE
Allow to pass a token {contactfield=whatever} in the URL endpoint field of the "Send a webhook" campaign action

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#6430]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:

This feature includes PUT as one of the available HTTP request methods, but without any dynamic insert like a token, in the URL field, possibilities appear very limited (or inexistent in my use case with Pipedrive, that will not even consider an ID passed in the body of the request).

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
