### ISSUE TITLE
Problem sending bulk e-mails (in campaigns) with Amazon SES after upgrading to Mautic 2.14

### ISSUE THREAD

**Issue by jsimoes** [mautic/mautic#6433]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:

After upgrading to 2.14 for some reason campaigns that trigger lots of e-mails (e.g., such as sending a newsletter) no longer work. Lets say the campaign is triggered out of a segment of 500 people (I was able to reproduce the issue from 50 onwards). No problem with the rebuild. However, when we run the command mautic:campaigns:trigger the issue arises (when sending e-mails). From the list, only the first 16 users (or so) receive e-mails.

We are current using Amazon SES to send e-mails. We have the configuration to "send e-mail immediately". We also tried "Queue" and the problem persisted as only a few messages were generated inside the spool folder. In general simple transactional e-mails are working. It seems that when we need to send several e-mails at once the problem occurs. 

Also, before the upgrade we never had issues send e-mails so I don't think it is an Amazon SES issue.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 7.0

### Steps to reproduce:
1.  Have a segment with +50 people
2. Create a campaign that uses this segment
3. The campaign should trigger a transactional email
4. Run the cron jobs
5. The error occurs
 
### Log errors: 

[mautic root]/app/log/ 

[2018-08-07 19:18:19] mautic.ERROR: [MAIL ERROR] Expected response code 250 but got code "421", with message "421 Timeout waiting for data from client. " Log data: >> MAIL FROM:<info+bounce_5b69f07b1ba0f454630594@mydomain.com>  << 421 Timeout waiting for data from client.  !! Expected response code 250 but got code "421", with message "421 Timeout waiting for data from client. " (code: 421) (send); janXXX@hotmail.com [] []
[2018-08-07 19:18:19] mautic.ERROR: [MAIL ERROR] Expected response code 250 but got code "", with message "" Log data: >> MAIL FROM:<info+bounce_5b69f07b2153d349430551@mydomain.com>  <<  !! Expected response code 250 but got code "", with message "" (code: 0) (send); tatiaXXXX@hotmail.com [] []
[2018-08-07 19:18:19] mautic.ERROR: [MAIL ERROR] Expected response code 250 but got code "", with message "" Log data: >> MAIL FROM:<info+bounce_5b69f07b23dfe595878147@mydomain.com>  <<  !! Expected response code 250 but got code "", with message "" (code: 0) (send); eluXXX@gmail.com [] []
.....

When running the command manually I also see the following error:

PHP Warning:  fwrite(): SSL: Broken pipe in /var/www/html/mautic-master/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 231
PHP Warning:  fwrite(): SSL: Broken pipe in /var/www/html/mautic-master/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 231
PHP Warning:  fwrite(): SSL: Broken pipe in /var/www/html/mautic-master/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 231
PHP Warning:  fwrite(): SSL: Broken pipe in /var/www/html/mautic-master/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 231
PHP Warning:  fwrite(): SSL: Broken pipe in /var/www/html/mautic-master/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 231
PHP Warning:  fwrite(): SSL: Broken pipe in /var/www/html/mautic-master/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 231
PHP Warning:  fwrite(): SSL: Broken pipe in /var/www/html/mautic-master/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 231

**Comment by luukvr** [comment]
We got the same problem since the update.

Our test segment of 10 works fine but when we try our normal +- 30k some crons seem to hang (tried immediatly and queue mode). We are also using SES.

The campagne shows as all the mails were sent, but they werent.

**Comment by luukvr** [comment]
Update... we quadrupled our server memory (2.14 seems to require alot more) and set our campagine:trigger cron to batchlimit 5, this seem to resolve the problem for now!

**Comment by jsimoes** [comment]
But this would require you to run the cron very frequently in order to send 35.000 emails, right?

**Comment by luukvr** [comment]
nah, its just a setting how many tasks it does in parallel is seems. Still have to run the task only once.

**Comment by jsimoes** [comment]
You are right! Also worked for me.. but this seems like a workaround. BTW: did you have to fine tune our PHP config? How much memory are you using?

**Comment by luukvr** [comment]
I'm running without a memory limit (-1), it's often going to like 1.5gb for me, also extremely heavy sql traffic, seems like 2.14 has major performance issues.

**Comment by pstevens71** [comment]
I'm having the same issue in 2.14.  Can you share the cron job line you used to set the bacth limit to 5 (I'm assuming that's where you did it).

**Comment by ericwhite406** [comment]
Hi @pstevens71 , I'm having this same issue. I think this is the cron job in question that we currently have running: mautic:campaigns:trigger > /dev/null 2>&1
Is that the correct cron job to update to mautic:campaigns:trigger --batch-limit=5 ?

**Comment by pstevens71** [comment]
Yes, that worked for me, change your cron job to add the --batch-limit=5  you can also try increasing your PHP memory limit if that doesn't work.

**Comment by ericwhite406** [comment]
@pstevens71 Thank you! What did you increase your PHP memory limit to? We current have ours at 1024M and our hosting service is InMotion.

**Comment by pstevens71** [comment]
I have 1024 too.  If you're on a VPS make sure the php limit of the sever is also 1024 not just Mautic.  Cron runs on the server default limits not the Mautic install limits

**Comment by KalleVuorjoki** [comment]
Can you check what size of your `.message` files are in `/spool` directory? We had also problem sending emails with Mautic 2.14. + Amazon SES, it turned out that `List-Unsubscribe` header was multiplied and each `.message` was 1-2M size even with very simple emails. https://github.com/mautic/mautic/issues/6339#issuecomment-412295187

**Comment by tstanczyk** [comment]
We have the same issue.
We found that the number of events that are beeing processed is acctually a remaider of division of the nubmer of events to be processed by 20.
Example:
   0/454 [>---------------------------]   0%
 100/454 [======>---------------------]  22%
 200/454 [============>---------------]  44%
 300/454 [==================>---------]  66%
 400/454 [========================>---]  88%
 454/454 [============================] 100%

454 divided by 20 gives the remainder of 14 and exactly 14 messages were send.
So we have set up the --batch-limit=19 and campaign is going out.
However so far I have not found a setting in a system of 20 which would influence this behaviour.
Maybe this comment will help resolve the issue.

**Comment by yarokifor** [comment]
@tstanczyk Someone give this man a metal! I had email 2869 contacts in a email list and I had 8 emails go out. Now 2896 mod 20 is 9, but one of the first 9 users on that segment was set to do not contact. I have an email going out on Monday, so I'll for sure if it works then.

**Comment by yarokifor** [comment]
So setting up my cron jobs with a batch-limit of19 over come this issue for me. I sent out over 2000 emails with this. Thanks @tstanczyk!

**Comment by heathdutton** [comment]
Thanks all, I believe the issue in question will be solved by #6482

Reopen if the issue persists after 2.14.1

**Comment by YosuCadilla** [comment]
I tested with 2.14.1-beta and it seems NOT to solve the issue, here's a complete list of possibly related issues: #6515 #5546 #6482 #6419 #6211 #6433 #6460 #63 

Seems Github has issues to solve too: #63 as seen here: mautic/docker-mautic#63

**Comment by dirtroof** [comment]
@luukvr You are my new hero. Incredible work everyone to figure out this fix. Just tried it, and it works like a charm. I had 1024MB already allocated to PHP Memory, so I didn't touch that and just added `--batch-limit=10` to my CRON. Works perfectly.
@yarokifor I had noticed the 19 limit myself, and your post lead me to believe this thread cited the problem and answer correctly. I decided to go with a `batch-limit=10` instead of `19` b/c I'm not 100% sure what's happening behind the scenes, but b/c I have multiple campaigns running I wanted to leave the potential for 9 open threads if something else needed them. Not sure it matters. 
Thanks all, working like a charm!

**Comment by pstevens71** [comment]
I can confirm issues still with 4.1.1.  Did a bunch of testing today.

Here' s what works and what doesn't:

New lead in Mautic -> Suite CRM Works!
New lead in SuiteCRM -> Matuic Works!
Change in SuiteCRM -> Mautic Works!
Change in Mautic -> SutieCRM BROKEN.

I have the field in Mautic set to be the master and to update SuiteCRM.  However, it does not update the SuiteCRM record.

Also, tried to schedule a "push" via campaign and any "push" ends in "generic error".  No other information is available in the logs.
