### ISSUE TITLE
Default input value's don't get saved / loaded

### ISSUE THREAD

**Issue by spka** [mautic/mautic#6435]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x

## Description:
Default input value's don't get saved / loaded.

## If a bug:
| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 7.1

### Steps to reproduce:
1. Create a form
2. Create an input field
3. Set it's default value
4. Check the html source and confirm the default value
5. Fill in the form, but leave the field with the default value untouched
6. View the results, the field column is empty

Hidden fields don't render a default value at all.

**Comment by npracht** [comment]
Could you share a screenshot of your form field configuration please?
Thanks

**Comment by luizeof** [comment]
could you test #6402 please ?

**Comment by spka** [comment]
Yes this seems to solve it!
