### ISSUE TITLE
Contact is removed from the middle of a running campaign when segment conditions doesn't match anymore.

### ISSUE THREAD

**Issue by carloshmm** [mautic/mautic#6439]
| Bug report? |  Yes? I don't know exactly if this is a default behavior or not.
| Feature request? |  No
| Enhancement? |  No

## Description:
![mautic](https://user-images.githubusercontent.com/31554436/43870211-c4195f8c-9b4c-11e8-8b5e-1f02223aa431.PNG)
Translation (Esperar 2 dias = Wait 2 days)

The image above shows one example of an anniversary campaign that has one segment associated with the filter:
birthday = today

When the campaign starts it immediately sends a push notification to the contact (right action) and waits 2 days to execute the left action branch that will send him an email. The problem is: The left branch is never executed because after 1 day the segment condition is not true anymore (the birthday has already gone).

Is it an expected behavior?

Should I create a segment associated with the anniversary campaign that will keep the true state while the contact is executing the campaign?

P.S.: This anniversary campaign is only one example, I have a bunch of campaigns that are tied to segments that have filters like (date attribute = today). If this is the default behavior I'll have to rethink all my work basically =).

## If a bug:
| Mautic version |  2.14.0
| PHP version |  7.0.30

**Comment by luizeof** [comment]
@carloshmm this is the expected behavior

**Comment by carloshmm** [comment]
@luizeof
Thank you.
