### ISSUE TITLE
issue with code mode bloc added in the builder

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6442]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When adding a code mode bloc in the builde with a script inside, and save the email or landing page, if you go back on the builder you won't be able to find the code mode bloc. If for example you'd like to apply some changes.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 

### Steps to reproduce:
1. Create an email or LP
2. Choose a theme (not the code mode)
3. Drag and drop the code mode bloc
4. Insert a script inside
5. Save the email or LP
6. Go back on the builder and see that you won't be able to the code mode bloc anymore in the builder.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/6454
