### ISSUE TITLE
"Allow contacts to restart the campaign" feature does not send the first email in campaign.

### ISSUE THREAD

**Issue by YosuCadilla** [mautic/mautic#6447]
What type of report is this:
| Bug report | 

## Description:
After removing contacts from a segment and adding them back, the campaign sends the second and subsequent emails but not the first one.
The only difference being that the first is set to be sent immediately and the rest have some delay.

## If a bug:
| Mautic version | 2.14
| PHP version |  7.0.30

### Steps to reproduce:

1. Create a campaign which sends 2 or more emails. Do NOT activate "Allow contacts to restart the campaign", yet. Set the first email to be sent immediately and the second to be sent after some delay (I used 3 mins).
2. Let the campaign send the emails. (wait for crons)
3. After receiving the emails, enable "Allow contacts to restart the campaign" in the campaign
2. Remove one or more contacts from the segment feeding the campaign.
3. Wait whatever time your cron jobs need to run again and update the segment.
4. Add the users back to the segment.
5. Check your email. The first email would not have arrived but the second should.

 
### Log errors: 

No errors in Mautic log.

**Comment by RCheesley** [comment]
Hi @YosuCadilla was this still an issue for you in 2.15.3 / 2.16 or can it be closed down?
