### ISSUE TITLE
Api call for "Send Email" not completing under User authenticated against

### ISSUE THREAD

**Issue by rbagley0310** [mautic/mautic#6448]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  N
| Feature request? |  N
| Enhancement? |  N
| Question? |  Y

## Description:
When using the API to send an email, we find that the email is sent with the defaults in Email Settings and not with the Email and Name of the User that was used in the API call. Is there something we may be doing wrong in the configuration or another way we can achieve this?

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.14.0
| PHP version |  7.0.31

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @rbagley0310 !
Please share the API query you're sending to be able to reproduce.

Thanks.

**Comment by rbagley0310** [comment]
I anticipated it would send as the user making the request. However, it is defaulting to the general setting defined in the mautic configuration. I have removed the authentication but the following the general request I make. 

POST http://mautic.bodylogicmd.com/api/emails/1/contact/753/send
Authorization: Basic 
Content-Type: application/json

**Comment by escopecz** [comment]
Even when you send email with user who has different email than is defined in the Mautic configuration it won't send from the user's email but from the email in the configuration. You can overwrite the default sender email per email. But not per send. Unless the contact has an owner and the "owner is sender" feature is turned on.
