### ISSUE TITLE
Sendgrid Api Callback - returning 404

### ISSUE THREAD

**Issue by drimlike** [mautic/mautic#6449]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Not Sure
| Feature request? | N
| Enhancement? | N
| Support? | Y

## Description:
Hello, we have a clean re-install of Mautic (2.14) but we just realise that we are getting an error that we were not used to have before , mailer/sendgrid_api/callback return 404 and we are not sure how to fix this. Everything else seems to be working fine (Website tracking, email send via Sendgrid). But the Sendgrid webhook is not working because of this error. Not sure how to fix this issue, any help will be much appreciated.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 7.1.20 FPM served by Nginx 

### Steps to reproduce:
1. Fresh Install of Mautic 2.14
2. Follow step to connect sendgrid : https://www.mautic.org/docs/en/emails/bounce_management.html#sendgrid-webhook
 
### Log errors: 

`2018-08-10 12:37:14	Error	167.89.125.215	404	POST /mailer/sendgrid_api/callback HTTP/1.0`

**Comment by cesarjr** [comment]
I have a similar trouble in 2.13 version. In my case, the Mautic is returning a 302.

**Comment by mehernosh** [comment]
Just installed mautic, I'm facing the same issue. I entered dev mode and found some stuff out 

Stacktrace:

`/app/bundles/CoreBundle/Controller/CommonController.php:523 at
/app/bundles/PageBundle/Controller/PublicController.php:290 at Mautic\CoreBundle\Controller\CommonController -> notFound ( )
Mautic\PageBundle\Controller\PublicController -> indexAction ( 'mailer/sendgrid_api/calback', object(Request) )
/vendor/symfony/http-kernel/HttpKernel.php:142 at call_user_func_array ( array(object(PublicController), 'indexAction'), array('mailer/sendgrid_api/calback', object(Request)) )
/vendor/symfony/http-kernel/HttpKernel.php:62 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php:67 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
/vendor/symfony/http-kernel/Kernel.php:183 at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '1', true )
/app/AppKernel.php:133 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
/app/middlewares/CORSMiddleware.php:93 at AppKernel -> handle ( object(Request), '1', true )
/app/middlewares/CatchExceptionMiddleware.php:45 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/Dev/IpRestrictMiddleware.php:65 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/VersionCheckMiddleware.php:57 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/run/src/Stack/run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request) )
/index_dev.php:28 at Stack\run ( object(StackedHttpKernel) )`

I've verified that the relevant controller is not even getting called.

The controller `MauticEmailBundle:Public:mailerCallback` is the one that is supposed to be handling the request, specifically `mailerCallbackAction($transport)` should be invoked . However, I found that there is a catchall that gives control to `MauticPageBundle:Public:index` and calls the `indexAction($slug, Request $request)` which checks a lot of conditions and finally ends in a 404.

**Comment by npracht** [comment]
Hello @drimlike can you test https://github.com/mautic/mautic/pull/7015 and say if it solves your issue ?

**Comment by ninjadrupal** [comment]
i have the same issue -_-'

**Comment by npracht** [comment]
@ninjadrupal did you try #7015 ??

**Comment by npracht** [comment]
I'll mark as closed because solved by #7015 and i'll reopen if you say it does not work.

**Comment by autoize** [comment]
@npracht We are experiencing this issue on some instances running on 2.15.1 even though #7015 was merged in 2.15.1. Running Apache 2.4.6/PHP-FPM 7.2.18 on CentOS 7.6 x64. There is nothing in the Mautic error log. 

Here is the 404 from the Apache access log:
````167.89.117.61 - - [15/May/2019:10:39:52 -0400] "POST /mailer/sendgrid_api/callback HTTP/1.1" 404 60660 "-" "Go-http-client/1.1"````

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
