### ISSUE TITLE
Cron Job to publish/unpublish import

### ISSUE THREAD

**Issue by cavewebs** [mautic/mautic#6458]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
I am trying to upload contacts (1000) and I get the error `"Import failed. Reason: There was a database error: The EntityManager is closed.. The import was set to delayed state and will be imported later." `
I understand that is (might be) due to the file not being in UTF-8, I noticed however that when I unpublish and re-publish the cron job, it starts the import again (strange) and when it stops I do repeat the process. One things is also confusing - if I use the browser option to upload, it does not stop, just takes long and I have to be connected and all. I have about 500k contacts I need to upload that I splited using linux split tool to 1000 each. It is overly cumbersome to manually upload this contacts.

What am looking for is the possibility to set a cron job that unpublishes and re-publishes the cron job at intervals so the import operation resumes without me having to do that manually. Kind of automate the manual process am doing.

Or is there another way for me to achieve this.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.14.0
PHP Version | 7.1.20
-- | --

### Steps to reproduce:
1. Upload CSV with about 1000 records
2. choose import in background
3. import list shows in progress and hooks at a certain percent
4. click on toggle under source file (status changes to stopped)
5. click on toggle again, status changes to queued
6. run cron in terminal or wait for cron job to start. 
7. status changes to inprogress and remains fixed at a certain percent again
 
### Log errors: 
[2018-08-13 14:39:40] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMException: "The EntityManager is closed." at /home/path/to/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php line 144 {"exception":"[object] (Doctrine\\ORM\\ORMException(code: 0): The EntityManager is closed. at /home/path/to/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php:144)"} []
[2018-08-13 14:45:45] mautic.WARNING: Command `mautic:import` exited with status code 1 [] []
[2018-08-13 14:51:01] mautic.WARNING: Command `mautic:import` exited with status code 1 [] []

**Comment by Bizcrony** [comment]
Clear cache and try

**Comment by Bizcrony** [comment]
Or increase the memory please

**Comment by kuzmany** [comment]
https://github.com/mautic/mautic/pull/6382
