### ISSUE TITLE
Leadpages integration

### ISSUE THREAD

**Issue by BrunoSette** [mautic/mautic#646]
Is there a Leadpages integration?

**Comment by alanhartless** [comment]
Right now there is not.  But I've tagged this as a feature request to look at for a future version.

Thanks!

**Comment by ankitpr89** [comment]
Yes, this is one of the most required feature, which much be in Mautic.
Leadpages and instapages integration are most required.

**Comment by dobesv** [comment]
I don't think Mautic can actually integrate with LeadPages; instead LeadPages has to integrate with Mautic.  Which unfortunately is a lot less likely to happen.
