### ISSUE TITLE
Unable to save email or landing page

### ISSUE THREAD

**Issue by 3Kells** [mautic/mautic#6461]
This looks to be similar to an older error but the solutions there have not worked for my installation

**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N 
| Enhancement? | M

## Description:
Attempting to save an email or landing page results in the apply or save and close just spinning in place. The error in the javascript console is 

-Failed to load resource: Origin https://www.3kells.com is not allowed by Access-Control-Allow-Origin.
-XMLHttpRequest cannot load https://3kells.com/mau/s/pages/new?  mauticUserLastActive=1&mauticLastNotificationId=. Origin https://www.3kells.com is not allowed by Access-Control-Allow-Origin.
-TypeError: undefined is not an object (evaluating 'request.responseText.indexOf')

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version |  7.1.20

### Steps to reproduce:
1. Create a landing page or email using a template 
2. Save and sit till eternity passes
 
Normally I don't mind chasing stuff down and coding but as I just got out of sinus surgery a few days ago I'm a bit to muddle headed to do much more than beg.

Thanks!

**Comment by npracht** [comment]
Hello @3Kells,

Mautic 2.15 does not exist. Could you tell us more about the version you have?
Also, could you please share your mautic configuration --->
![capture d ecran 2018-08-21 a 11 37 29](https://user-images.githubusercontent.com/14075239/44394089-a0d60e00-a536-11e8-8b89-a346dcf48c86.png)
![capture d ecran 2018-08-21 a 11 37 37](https://user-images.githubusercontent.com/14075239/44394091-a0d60e00-a536-11e8-85ec-eee10c67396f.png)
