### ISSUE TITLE
Error loading dashboard (CRITICAL: Uncaught PHP Exception)

### ISSUE THREAD

**Issue by llbster** [mautic/mautic#6462]
Bug report

## Description:
Error when attempting to load dashboard.
Dashboard does not render (load).
From the logs it looks like an SQL exception is the cause, probably due to an error with the query which populated the Sent / Read Email widget.
## If a bug:

| Mautic version | 2.14.0
| PHP version | PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

### Steps to reproduce:
I am not sure how to reproduce this error, but here is how it occured:
The mails sent / read widget was not showing any activity.
I removed the widget and re-added.
I set the filter to my single campaign.
I recieved an "Oops I broke it error".
The dashboard now nolonger loads, although the other functionalities still seem to work.
It appears to have something to do with the the SQL query that is populating the widget. See error below.
 
### Log errors: 
>[2018-08-14 19:30:46] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT s.id, s.lead_id, s.email_address, s.is_read, s.email_id, e.name AS email_name, COUNT(ph.id) AS link_hits, c.id AS company_id, c.companyname AS company_name, campaign.id AS campaign_id, campaign.name AS campaign_name, ll.id AS segment_id, ll.name AS segment_name FROM email_stats s LEFT JOIN emails e ON s.email_id = e.id LEFT JOIN page_hits ph ON s.email_id = ph.email_id AND s.lead_id = ph.lead_id LEFT JOIN companies_leads cl ON s.lead_id = cl.lead_id LEFT JOIN companies c ON cl.company_id = c.id LEFT JOIN campaign_events ce ON s.source_id = ce.id AND s.source = "campaign.event" LEFT JOIN lead_lists ll ON s.list_id = ll.id LEFT JOIN campaigns campaign ON ce.campaign_id = campaign.id WHERE (e.created_by = ?) AND (s.date_sent BETWEEN ? AND ?) GROUP BY s.id ORDER BY s.id DESC LIMIT 6' with params [1, "2018-07-15 00:00:00", "2018-08-14 19:30:46"]:  SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mauticdb.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT s.id, s.lead_id, s.email_address, s.is_read, s.email_id, e.name AS email_name, COUNT(ph.id) AS link_hits, c.id AS company_id, c.companyname AS company_name, campaign.id AS campaign_id, campaign.name AS campaign_name, ll.id AS segment_id, ll.name AS segment_name FROM email_stats s LEFT JOIN emails e ON s.email_id = e.id LEFT JOIN page_hits ph ON s.email_id = ph.email_id AND s.lead_id = ph.lead_id LEFT JOIN companies_leads cl ON s.lead_id = cl.lead_id LEFT JOIN companies c ON cl.company_id = c.id LEFT JOIN campaign_events ce ON s.source_id = ce.id AND s.source = \"campaign.event\" LEFT JOIN lead_lists ll ON s.list_id = ll.id LEFT JOIN campaigns campaign ON ce.campaign_id = campaign.id WHERE (e.created_by = ?) AND (s.date_sent BETWEEN ? AND ?) GROUP BY s.id ORDER BY s.id DESC LIMIT 6' with params [1, \"2018-07-15 00:00:00\", \"2018-08-14 19:30:46\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mauticdb.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mauticdb.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #8 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'mauticdb.c.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

**Comment by llbster** [comment]
By the way... As a stop gap, is it possible to delete all widgets from the dashboard with SQL or by editing a config file? This may enable me to create a new one.

**Comment by llbster** [comment]
I have fixed this by disabling "ONLY_FULL_GROUP_BY" on the MySQL server. The SQL error is now gone and the Dashboard loads...

However, I am not sure if this will have any adverse effects? Or if the SQL that built the DB needs to set this at install?

**Comment by npracht** [comment]
Then this is a configuration issue.
@escopecz do you think that should be mentioned in the mautic documentation (maybe it is already)?

**Comment by escopecz** [comment]
Mautic should generate queries that does not fail on this, but it's somewhere at the bottom of the queue right now because it can be configured on database.

It should be mentioned in the docs.

**Comment by npracht** [comment]
@escopecz if you tell me where i'm ok to PR few doc lines about that :)

**Comment by escopecz** [comment]
I'm not sure where the best place is. Maybe https://github.com/mautic/mautic#requirements?
