### ISSUE TITLE
separate contacts that only open email or click emails

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6466]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
At the moment, it is not possible in a campaign to separate contacts that just open emails and contacts that click.
Loo at this below
![image](https://user-images.githubusercontent.com/31535432/44268872-1ab68080-a233-11e8-9498-5b6377cb37d7.png)
Contacts that clicked on the email will follow the decision click emails but will obviously follow the decision open email (if a contact clicked on an email, he obviously opened it).

What could a nice feature would be to separate these two decisions. 
If a contact clicked on a email, having the possibility that contacts just follow decision click email (and not open email)

**Comment by kuzmany** [comment]
But this not make sense. Normally user cannot click until open email. I understand this situation mean click If tracking pixel  in email is not loaded? Do you want catch this type of situation?

**Comment by AlbanL74fr** [comment]
The use case is not clear. Why would you do that for? Because why not pluging the "click email" decision in the action path of the "open email" decision? Then you will separate those who open + clicked, and those who open vut didn't click? Would it work?

**Comment by npracht** [comment]
Use case :
You want to send an email to openers and a different one to clickers.

If managed like on the screenshot, I guess that clickers will also be on the positive branch of openers right?
How can you divide in 2 branches the openers on one side (excluding clickers) and the clickers on another one?

N.

**Comment by johbuch** [comment]
So the goal would be to add a condition after the decision "opens email" ?
Would be ok for me

**Comment by kuzmany** [comment]
Opens email mean every email with loaded tracking pixel or clicked the link (even If pixel wasn't loaded). Then should work for me for you user case

Maybe we could create Has clicked channel  condition with support for emails, sms, notifcations etc.

**Comment by kuzmany** [comment]
@johbuch You can do it without new condition

You can tag your contact open - after open, clicked after clicker, on day later you can make condition based on tags and then you can remove these tags from contact. It's little ugly, but should works either.

**Comment by johbuch** [comment]
Let's go for the smoother solution, please handle that :)

**Comment by kuzmany** [comment]
Let's test

https://github.com/mautic/mautic/pull/6488

**Comment by dsp76** [comment]
would that also fix email statistics? once a person clicked a link in an email, it should also implicitely count as email opened...
