### ISSUE TITLE
Contact Field Not Being Translated

### ISSUE THREAD

**Issue by drimlike** [mautic/mautic#6468]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
We have translated our emails from French to English. Mautic is now sending this emails to the users that have En as preferred locale. If we use the new translated templates and send them via the user profile the `{contactfield=firstname}` is translated. But the same email template sent as part of a campaign keeps `{contactfield=firstname}` as is in the email. We don't have the same issue with the initial template that are in French. We don't see why Mautic doesn't translate the contact field in the English campaigns. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 7.1.20 FPM served by Nginx

### Steps to reproduce:
1. Translate one of your email in a new language, make sure to use {contactfield=firstname} in the email template
2. Make sure that the new template is used in test campaign, that the person linked to that camapaign has a firstname available
3. Let Mautic send automatically that test campaign
4. Compare this email with the same one sent via one of the user profile
5. The field should be translated only in the second email sent.

**Comment by npracht** [comment]
Hello @drimlike could you share screenshots ? I don't understand in what a token should be translated.
Thanks a lot :)

**Comment by drimlike** [comment]
@npracht ,

sure , send via mautic automatically I get this : 

![image](https://user-images.githubusercontent.com/4152261/44393957-e8a46780-a52d-11e8-99e4-0e55efe11230.png)

When send from the user profile I get this: 

![image](https://user-images.githubusercontent.com/4152261/44394890-3de17880-a530-11e8-8130-f84b405e1d48.png)

Does it make sense?

Thanks,

**Comment by npracht** [comment]
Hi, i don't understand where the translation is the subject here. Tokens are not translated? The contact alias stays the same?

**Comment by escopecz** [comment]
Se experienced this issue recently. There was HTML inside the token string and therefor the token replacement was not working for that token. I'm pretty sure it's this reason. View the source code of that slot. Remove the HTML from it. Let us know if it worked. It's a Froala (the wysiwyg editor) bug, so nothing we can do now.

Will close this for now. If you won't be able to fix the token then reply and I'll reopen.
