### ISSUE TITLE
Where is Database setup document?

### ISSUE THREAD

**Issue by sohamnavadiya** [mautic/mautic#6472]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @sohamnavadiya !
I'd say https://github.com/mautic/mautic#requirements
Please ask this type of question on the chat on slack :)

Thanks for your contributions.
