### ISSUE TITLE
error 500 internal server error on email and campaign page

### ISSUE THREAD

**Issue by ServicedCloud** [mautic/mautic#6473]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
We have manually updated our mautic from 2.13.1 to 2.14.0. Please note that we have tried updating mautic via ssh and auto-update via backend of mautic - both step results a failed update.

After the manual update, all pages seems to be working except the email and campaign pages. 
http://ourdomain.com/s/campaigns
http://ourdomain.com/s/emails

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 5.6.37

### Steps to reproduce:
1. Update mautic manually from 2.13.1 to 2.14.0
 
### Log errors: 

 mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_10 FROM (SELECT e0_.is_published AS is_published_0, e0_.date_added AS date_added_1, e0_.created_by AS created_by_2, e0_.created_by_user AS created_by_user_3, e0_.date_modified AS date_modified_4, e0_.modified_by AS modified_by_5, e0_.modified_by_user AS modified_by_user_6, e0_.checked_out AS checked_out_7, e0_.checked_out_by AS checked_out_by_8, e0_.checked_out_by_user AS checked_out_by_user_9, e0_.id AS id_10, e0_.name AS name_11, e0_.description AS description_12, e0_.subject AS subject_13, e0_.from_address AS from_address_14, e0_.from_name AS from_name_15, e0_.reply_to_address AS reply_to_address_16, e0_.bcc_address AS bcc_address_17, e0_.template AS template_18, e0_.content AS content_19, e0_.utm_tags AS utm_tags_20, e0_.plain_text AS plain_text_21, e0_.custom_html AS custom_html_22, e0_.email_type AS email_type_23, e0_.publish_up AS publish_up_24, e0_.publish_down AS publish_down_25, e0_.read_count AS read_count_26, e0_.sent_count AS sent_count_27, e0_.variant_sent_count AS variant_sent_count_28, e0_.variant_read_count AS variant_read_count_29, e0_.revision AS revision_30, e0_.lang AS lang_31, e0_.variant_settings AS variant_settings_32, e0_.variant_start_date AS variant_start_date_33, e0_.dynamic_content AS dynamic_content_34, e0_.headers AS headers_35 FROM emails e0_ LEFT JOIN categories c1_ ON e0_.category_id = c1_.id WHERE e0_.variant_parent_id IS NULL AND e0_.translation_parent_id IS NULL ORDER BY e0_.subject DESC) dctrn_result) dctrn_table':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e0_.headers' in 'field list'" at .......

Please note that we can provide complete logs file but for security purposes we have cut it off.

**Comment by npracht** [comment]
Hello @ServicedCloud did you update your DB schema ?

**Comment by vacabernardo** [comment]
Same problem

**Comment by ServicedCloud** [comment]
Hello @npracht. We tried DB schema update but still having Internal Server Error on both email and campaign pages. We also tried @heathdutton suggestion but still the same.

**Comment by dgtlchurch** [comment]
I'm having a similar issue. Installed on SiteGround cloud server.

**Comment by npracht** [comment]
Hi guys, as mentioned by @heathdutton this is a configuration / update issue.
i'd recommend you to move to Mautic Slack #Support channel to get help and discuss with the community.

As far as it is "working", i'll close this issue (there are thousands instances running on 2.14.0 after update).
