### ISSUE TITLE
Mautic 2.14.0: mautic:campaigns:rebuild infinite loop

### ISSUE THREAD

**Issue by jbransen** [mautic/mautic#6475]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
When I run `mautic:campaigns:rebuild` after updating to 2.14.0, I get an infinite loop. The console displays:
> Rebuilding contacts for campaign 3
> 4 total contact(s) to be added in batches of 300
>  254928/254928 [============================] 100%

and the number keeps increasing (most likely until it runs out of memory at some point). I have less than 254928 contacts in total.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.28

### Steps to reproduce:
1. Upgrade from 2.13.1 to 2.14.0, which contacts in segments and campaigns
2. Run `php app/console mautic:campaigns:rebuild`
 
### Log errors: 

No logs.

**Comment by npracht** [comment]
Hello, please this already existing issue https://github.com/mautic/mautic/issues/6393 and test https://github.com/mautic/mautic/pull/6463.
Thanks !

**Comment by jbransen** [comment]
Missed that, sorry!
