### ISSUE TITLE
Report contact log points and graphic

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6476]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is something weird with reports data type contact log points
![image](https://user-images.githubusercontent.com/31535432/44463167-2e892a80-a617-11e8-8f05-c5e27b4b0f94.png)
If you display the graphic contact with most points
![image](https://user-images.githubusercontent.com/31535432/44463203-48c30880-a617-11e8-8a67-48554f025b4f.png)
When checking the graphic, I can see that the contact with most points have 30 points
![image](https://user-images.githubusercontent.com/31535432/44463252-6d1ee500-a617-11e8-9952-cb266049daf0.png)
But when I on his contact sheet, I can see that he only have 13 points.

So maybe, first of all we should check what the graphic request to display points.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13
| PHP version | 

### Steps to reproduce:
1. Create report contact points log
2. Display graphic that show contacts with most points
3 Save and close, check the graphic and check contact sheet as well.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Confirmed.

If you use just graph table, then works
If you use data table too with company colum then quiery join to company table an then show wrong points number

**Comment by kuzmany** [comment]
Solution: Use just graphs without data table

**Comment by kuzmany** [comment]
Let's test https://github.com/mautic/mautic/pull/6479
