### ISSUE TITLE
Single Contact Email Sending having no entry to Email Template Stats

### ISSUE THREAD

**Issue by architjoshihs** [mautic/mautic#6480]
What type of report is this: Bug / Feature

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | Y
| Enhancement? | Y

## Description:
When we send an email to single contact from the contact listing using sendemail option and add a template, the stats of email template do not get updated. I checked the code and database and found that in stats table the email that is sent does not have email_id entry, similarly there is no source column entry.

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.1

**Comment by escopecz** [comment]
That's correct. "Send to contact" emails aren't tracked. Use segment emails to have the tracking.
