### ISSUE TITLE
Contacts added to non-published campaign

### ISSUE THREAD

**Issue by jbransen** [mautic/mautic#6484]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I have a Campaign with a form submission as trigger. The form is published, the campaign is not. Still, contacts are added to the campaign (but don't seem to progress), so when I now publish the campaign all these contacts get the messages. Instead, I expect only contacts that submitted the form _after_ the campaign was published to retrieve the messages.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.14.0
| PHP version | 7.0.30

### Steps to reproduce:
1. Create a form and publish
2. Create a campaign with the form as trigger, but don't publish
3. Submit the form
4. See that the user is added to the campaign

**Comment by escopecz** [comment]
I would expect this exact behavior. I wouldn't want to lose all contacts when the campaign was unpublished. So it depends on the use case.

For your use case simply clone the campaign and start fresh.
