### ISSUE TITLE
Sender within API call

### ISSUE THREAD

**Issue by rbagley0310** [mautic/mautic#6485]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | N 
| Enhancement? | Y

## Description:
Additional submission values that would allow the api request to defined the sender name and email to override the settings tied to the email configured in Mautic.

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.31

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
