### ISSUE TITLE
Theme Updates do not affect emails already assigned

### ISSUE THREAD

**Issue by rbagley0310** [mautic/mautic#6486]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When updating my Themes, I have noticed that the changes are not pushed to Emails that are currently assigned. Is this intentional or a bug in the the Theme update process?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.31

### Steps to reproduce:
1. Import updated Theme into Mautic.
2. Got to builder for Email assigned to Theme and see no changes were passed on.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @rbagley0310 ,

If this is HTML modification it cannot change retro-actively. If it is CSS (from a 3rd file) then it works.
Best !

**Comment by dsp76** [comment]
@rbagley0310 whenever you create a new email, it is kind of a snapshot of the template at the time of creation :/ not sure whether and how other mail services do it. this may be a problem for larger installations, when changes need to be made...
