### ISSUE TITLE
Sender id taken of Contact Owner and not of the one set in the campaign

### ISSUE THREAD

**Issue by artinsane** [mautic/mautic#6487]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | A
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | A
| PHP version | 

### Steps to reproduce:
1. I've imporated user from my admin account
2. When i send out a campaign, i've selected a different sender for that specific campaign both when building the campaign.
3. I am using sendgrid API as a sender
4. When the campaign actually send the email, the from ID is taken from the owner of the contact and not from the one mentioned in the email.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Owner has precedence over "from" configuration. If you don't want this then turn off the "Owner is sender" feature in the configuration.
