### ISSUE TITLE
I don't know how yo put new contacts on my segments

### ISSUE THREAD

**Issue by admindaya** [mautic/mautic#6489]
What type of report is this:

| Q  | A

## Description:
Hi, i just started using Mautic but I don't know how to enter new contacts on my suscribers list. I need to create some triggers. 

When I try to go to "segments", select my segment and ""no contacts" I see there is an option that is "add fast" I add the contact but this one doesn't appear on my segment. But it's created on "contacts" area. 

How can I have the contacts I want on the segment? Another question is, if put some contacts on the segment, and segment is in one of my campaigns, all contacts will receive automatically emails with the frequency I put on campaign builder?

Thank you.

**Comment by npracht** [comment]
Hello @admindaya i'd suggest you to chat on Mautic Slack. This are user questions and if the documentation is not enough please ask people on slack. You should report bugs here :)

Thanks a lot for your understanding.
