### ISSUE TITLE
Title (Mr, Mrs) vs Page-Title

### ISSUE THREAD

**Issue by cr-solutions** [mautic/mautic#649]
Page-Title and Title for Salutation bite's the tracking.
For more please see: https://www.mautic.org/community/index.php/492-title-mr-mrs-vs-page-title/

**Comment by alanhartless** [comment]
Hi,

Thanks for reporting that.  We've implemented a fix that will be part of 1.1.3.  You can test it through the link above if you would like.

Thanks,
Alan

**Comment by cr-solutions** [comment]
Tested, works great. Thanks!
