### ISSUE TITLE
Enhancement - programatic import of CSV files from FTP

### ISSUE THREAD

**Issue by OmerGafny** [mautic/mautic#6493]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | NO
| Feature request? | NO
| Enhancement? | Yes

## Description:

It would be really cool if we can have the ability to schedule csv file/list of contacts imports via Mautic UI. The idea is to check the server's FTP for files on a predefined schedule (determined by the user in the import interface).

This can be a solution for users who want to import contacts from a contact source which is not supported by one of the plugins (like CRM plugins) ot Zapier.

The flow should go something like this:

Select contact source (local or FTP)
If from FTP - determine when to execute - immediate or scheduled (Plus FTP URI and username, password etc)
If scheduled - select intervals (daily, weekly, monthly,)
Define file name (can add wildcard with %)

Thanks!

**Comment by HNJAMeindersma** [comment]
Would be really handy indeed! I would find it much easier to export a custom csv and upload it automatically then writing an API script for synchronizing a 3th party database.

**Comment by evgu** [comment]
Thumbs up. This feature will be really handy.

**Comment by heathdutton** [comment]
You know, since this would necessitate a new cron anyway, you could set up an import that imports a file from a predetermined location, then replace that file (by a cron script that fetches from FTP or wherever) and then reset the import so that it begins again... Very little "code" but would do what you wish.

**Comment by evgu** [comment]
Has anyone tried this project? Looking at description it seems to do the job. 
https://github.com/mtcextendee/mautic-custom-import-bundle
https://mtcextendee.com/our-works/mautic-plugins/custom-import-for-mautic/

**Comment by evgu** [comment]
> You know, since this would necessitate a new cron anyway, you could set up an import that imports a file from a predetermined location, then replace that file (by a cron script that fetches from FTP or wherever) and then reset the import so that it begins again... Very little "code" but would do what you wish.

@heathdutton Im slightly against such implementations at least on our servers and next upgrade and something gets broken.

**Comment by RCheesley** [comment]
I'm going to close this down as there are third party jobs to do this. If you want it as a core feature, please post up in the forum here: https://forum.mautic.org/c/ideas/14 for discussion & voting!

**Comment by evgu** [comment]
@OmerGafny could you post to forum link pls as original post was yours?
