### ISSUE TITLE
Form Result Date Submitted Field Timezone Mismatch 

### ISSUE THREAD

**Issue by yarokifor** [mautic/mautic#6496]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When viewing results of a form results the "Date Submitted" field always shows in UTC and appends user's timezone. So in the user's perspective all submissions times are off by user's timezone offset. Note that if a user checks the individual contacts the event timestamp is shown properly. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | PHP 7.0.30

### Steps to reproduce:
1. Set timezone to anything other than UTC
2. Submit a form
3. Check the Date submitted field
 
### Log errors: 
Nothing applicable...

**Comment by npracht** [comment]
The time is depending on your server configuration. Not sure using the local time would be a good thing, it'd make crazy the app. A 2nd guy submitting later than a 1st guy could have a date earlier than him.. not a good idea ?

But for instance, you can add a hidden field in your form that is automatically set up with the date of today's browser in JS ? That would answer your need.

**Comment by yarokifor** [comment]
In this case the server configuration use the same timezone as the user. I don't think I fully understand what are saying in your second sentence. As far as the hidden date field goes, I don't think it would be a good idea to add code to the front end to fix a back end bug especially because the time is being recorded correctly just not displayed correctly.

I've attached images that better describe what the issues is:

![mautic_timezone_issue1](https://user-images.githubusercontent.com/1300073/44810454-bafb9600-ab9f-11e8-8750-c8922b737da9.png)
![mautic_timezone_issue2](https://user-images.githubusercontent.com/1300073/44810478-cc44a280-ab9f-11e8-9bf9-4fdbb2671236.png)

**Comment by escopecz** [comment]
Ready to test in https://github.com/mautic/mautic/pull/6727

**Comment by Woeler** [comment]
Merged https://github.com/mautic/mautic/pull/6727

**Comment by AlbanL74fr** [comment]
I noticed the same issue. Good to see it's been fixed. Thanks all.
