### ISSUE TITLE
Landing Page Redirection not Work

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#6498]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

Landing Page with redirection data do not redirect (301 or 302)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13 or 2.14
| PHP version | 7.0

### Steps to reproduce:
1. Create a Landing Page and fill redirect options (301 or 302)
2. Save Landing Page
3. Open Landing Page Public URL
4. Redirection not Work
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
@luizeof as far as i remember, the redirect is used when you publish down the page. Would you check?

**Comment by luizeof** [comment]
@npracht yes .... even unpublished and/or expired not work

**Comment by edtaaffe** [comment]
Any progress with ths

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Comment by micheljung** [comment]
If you're logged into Mautic, redirects don't work. Open the URL in a private tab and it will work.
