### ISSUE TITLE
Add tooltip to inform that assets in attachment are not tracked

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#6499]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:

Asset Downloaded campaign decision would only trigger when the asset is linked in email content, but not when the asset is added as an attachment to the email, which creates some false positives in my campaign.

It looks like a bug because a user in Mautic would expect that assets downloaded are tracked no matter how they are included in an email. One can choose to add an attachment to the email to make it more visible in the mailbox, while in another case it would make more sense to simply link to it in the content.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 5.6.32

### Steps to reproduce:
1. Create an asset (PDF or whatever). Let's assume ID is 1.
2. Create a template of email and add a link to the asset in the content (i.e {asset=1})
3. Also, add the same asset as attachment in this template
4. Create a new campaign w/ source a segment that contains your valid test email and add :
  -> A "Send Email" campaign action, to send the email created above
  -> An "Asset Downloaded" campaign decision and select the asset 1
5. Make sure asset, email, campaign are published.
6. Check your mailbox, you will receive the email
7. Open contact profile page of test contact
8. Open the email received and click the link to the asset in the email content 
9. Refresh contact profile, you will see that the asset download was tracked, and the campaign decision was triggered.
10. Open email again and click the attachment
11. Refresh the contact profile, you will NOT see the asset downloaded again.

**Comment by luizeof** [comment]
The Attachment itself cannot be tracked ... because .. is "embedded" to e-mail body ...

**Comment by AlbanL74fr** [comment]
@luizeof, I don't really get it... How does it differ from assets linked from the template editor?

**Comment by npracht** [comment]
@luizeof is right. The tracking of the asset is done by a browser link navigation. If the asset is attached, there is no link anymore = no tracking. There is no way to add tracking in a PDF. But you can track the fact of going to a link (tracked) that redirects to an asset.

This is not a bug, just a technical limitation !

**Comment by AlbanL74fr** [comment]
Thx @npracht. It's clear now. I think it would be great that this information be available as a tooltip in the attachment field, in email templates. So marketers, Mautic users are not supposed to know how tracking works, technically, and what limitation it has.

**Comment by RCheesley** [comment]
I think this is more of a documentation issue than relating to the code itself, but it can't hurt to add a tooltip to explain this (especially as every other field has a tooltip on that screen!)

**Comment by escopecz** [comment]
Implemented by https://github.com/mautic/mautic/pull/9344
