### ISSUE TITLE
Support to use a single Mautic instance for multiple companies with access to only their stuff

### ISSUE THREAD

**Issue by SolacetechInformationServices** [mautic/mautic#65]
I would like to use Mautic to host various companies' SMM Teams. It looks like at present One user can see another user's items if they are public. I would like separate companies to be able to add users for their team, share items and not be aware of the other companies also using Mautic on my hosted version of Mautic... Is that possible?

**Comment by alanhartless** [comment]
Right now it is not short of hosting a different instance of Mautic per company.  However, we do plan to explore options for this model in the future.

**Comment by SolacetechInformationServices** [comment]
NP. Keep up the good work.

**Comment by hemsinfotech** [comment]
any update for below request

*********************
I would like to use Mautic to host various companies' SMM Teams. It looks like at present One user can see another user's items if they are public. I would like separate companies to be able to add users for their team, share items and not be aware of the other companies also using Mautic on my hosted version of Mautic... Is that possible?

**Comment by zoppim** [comment]
I'm also interested in this functionality :) as at the moment is quite difficult to support multiple instances.

**Comment by alanhartless** [comment]
Sorry guys, we've decided this is outside the scope of Mautic's goals and not really applicable to most consumers of Mautic.
