### ISSUE TITLE
Field with CSS Class Attribute set can't be deleted from form editor

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#6501]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
After adding certain attributes to form fields, they can't be deleted anymore from form.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.30

### Steps to reproduce:
1. Add class="col-md-12" as attribute to Field container attributes 
2. Try to delete that field
 
### Log errors: 

Mautic Log is empty, but Browser console says:

libraries.js?vc94f211d:381 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

Not sure if this is related.

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
I was able to replicate this in 2.16 beta - no errors in console, delete icon does nothing but I can edit the field.

When I hit delete, there is no action, and also editing the field requires a double-click on the edit button where it's normally a single click.

Short walk through: https://youtu.be/q6uGpzc259g

As soon as I removed the class, it allowed me to delete.

**Comment by dsp76** [comment]
Still there in 3.0.1.

Underlying problem might be, that the **Mautic backend applies styling also in backend**. Adding style="display: none" to a form field in order not to appear in the form itself - it also almost goes missing in the backend:

![image](https://user-images.githubusercontent.com/1241376/88484106-9a474100-cf6c-11ea-846b-31ccc6f67950.png)

Backend should not apply field styling except when generating the form itself!

**Comment by RCheesley** [comment]
Ah, that's a frustrating one! Thanks for checking it's still around in Mautic 3.x!
