### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by yrammos** [mautic/mautic#6508]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | N
| Enhancement? | N

## Description:

I have my Mautic instance running on `m.domain1.com` and a Mautic form in a webpage hosted on a different domain (`domain2.com`). Both domains are physically on the same server.

Unfortunately, I get the dreaded "something's broken" server error message upon submitting the form. The log indicates that mautic is attempting to create access a `mautic/app/cache` directory on `domain2`, i.e. the domain in which form resides (!). The exact log message is: 

``
`mautic.CRITICAL: Uncaught PHP Exception RuntimeException: "Unable to create the cache directory (/var/www/html/domain2.com/public_html/mautic/app/cache/prod/twig/ac)." at /var/www/html/domain1.com/vendor/twig/twig/lib/Twig/Cache/Filesystem.php line 57`
``

If I proceed to create that directory manually and grant to the `www-data` user the permission to write in it, things do appear to work (as mentioned, the two domains are on the same physical server).

Yet I am reluctant to accept such a wacky hack as normal; it cannot be normal for mautic to need two separate cache locations. Please note that CORS is enabled and all the relevant domains allowed. I also have all the domain settings correct in Mautic. Any ideas? Thank you. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.30-0ubuntu0.16.04.1

### Steps to reproduce:
1. Embed an published Mautic form in a webpage that is hosted on an other server.
2. Visit this webpage and attempt to post data. Unless a `mautic/app/cache` folder on the form-hosting server exists, submission fails.
 
### Log errors: 

See above.

**Comment by yrammos** [comment]
I suppose two relevant questions are:

1. Is Mautic **supposed** to support forms on different root from its own?
2. Is Mautic supposed to need a cache store on every server that serves a Mautic form?

Thanks.

**Comment by npracht** [comment]
Hello @yrammos !
I guess most everything is settable in the configuration page of your instance (instance, root, etc.) and maybe that has been forgotten to be modified right?

**Comment by yrammos** [comment]
Yes, `tmp_path` is perhaps accidentally left out of the GUI.
