### ISSUE TITLE
Cant Create eMails With My Mautic App

### ISSUE THREAD

**Issue by tallestman** [mautic/mautic#6513]
What type of report is this:

When I create an email, it asks what type of email I'd like to select,

Then I select either 'New Template Email' or 'New Segment Email', 

I then select a template add all details needed - when I click 'Save & Close' or 'Apply' it brings up the dialogue again asking what type of email I want to create and when I go through that process again, there are no action buttons ('Save & Close' or 'Apply' etc).

My hosting has also done the ModSecurity whitelisting, but i still have the same problem

I even sent a mail to security@mautic.com but no response till now

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Bizcrony** [comment]
@tallestman server issue

**Comment by npracht** [comment]
Hi @tallestman ! Thanks for your message. Unfortunately i cannot reproduce. As mentioned @Bizcrony it should be more of a server configuration issue or installation issue.
It would be much easier to ask your question on the Slack chat to discuss with people.
