### ISSUE TITLE
Form E-Mail Action ignores "Do not contact"

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#6514]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | N
| Enhancement? | N

## Description:
A user thats set as "do not contact" will still receive a mail based on a form action.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0

### Steps to reproduce:
1. set a user "to do not contact"
2. add an "send email to contact" action to a form
3. fill the form with the user e-mail from 1.
4. user will receive the email despite still being set on "do not contact"

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @dsp76 !
IMO this is a normal behavior. In fact this is a transactional email that should not take into account if the person is DNC. What do you think ?

**Comment by dsp76** [comment]
@npracht DNC means DNC, doesn't it? Why should a form submission / a transactional email be handled differently? Actually bad behaving people could use this to create a privacy case. If they set themself as DNC and then submit a form, this would be breaking the DNC request IMHO.

We use form actions often as step one of a campaign (even if not sent by the real campaign). This makes sure, people receive a response from a form action immediately instead of waiting until the next cron job happen to run...

**Comment by dsp76** [comment]
Interesting point of view... will discuss with our lawyer next time I meet him.

**Comment by escopecz** [comment]
@npracht is correct. If you want to obey DNC for this case too then use the form as the source of a campaign and send emails from the campaign instead of the form action.
