### ISSUE TITLE
Emails not all triggered/queued

### ISSUE THREAD

**Issue by dsukhin** [mautic/mautic#6515]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
It appears that if `mautic:campaigns:trigger` is run with too many items to trigger, it just drops things without queueing or sending them.

The spool directory only gets a random subset of messages from the ones that are set to be triggered. The log of the command properly reports the subset number. This number is different every time and depends on the batch that is being processed. If I make a smaller batch, the number of events to trigger is also the number executed. If the batch is too big, it doesn't execute them all.

If I check the DB, 
```
select * from campaign_lead_event_log c 
left join email_stats s
on s.lead_id=c.lead_id
and s.source_id=c.event_id
where s.email_address is null
```
i can see the exact number that is missing like this. The item is logged in the lead event log but since no email is prepared, its not added to email stats.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 7.1.21

### Steps to reproduce:
1. Create campaign with lots of emails to send
2. Run `mautic:campaigns:trigger` to spool messages
3. See something like:
```
Triggering events for campaign 2
Triggering events for newly added contacts
88 total events(s) to be processed in batches of 100 contacts
 88/88 [============================] 100%

8 total events were executed
0 total events were scheduled
```
 4. Notice that **8 != 88**. Events are processed but not all executed. If batches are made smaller (using max-contact-id or similar) all the processed events that are triggered are also executed.

### Log errors: 
No error log for today

**Comment by dsukhin** [comment]
I have queued sending on for emails. I see the subset of messages added to app/spool/default/ folder. But only the subset of messages. Do you mean set the email in the campaign to "send in one minute" so it gets scheduled instead of triggered?

Right now, I'm running trigger on 100 users at a time and it seems to be working as a temp work around. Would love to get to the bottom of this!

**Comment by dsukhin** [comment]
Possibly related to #5546

**Comment by lucianojmf** [comment]
I'm experiencing the SAME thing too...
Also, I noticed a very large performance drop in the cron commands ... I do not know if they are associated.

**Comment by dsukhin** [comment]
Can confirm @rwrz's solution to set the email to *send after 1 minute* WORKS. Thank you!
This is a decent workaround for now and should be clearly communicated to others. 

Let me know how I can help get to the bottom of this problem

**Comment by dsukhin** [comment]
One new update:
```
1 total decisions(s) to be analyzed for inactivity for approximately 5250 contacts in batches of 100
0/5250 [>---------------------------]   0%
600/5250 [===>------------------------]  11%
1100/5250 [=====>----------------------]  20%
1600/5250 [========>-------------------]  30%
2100/5250 [===========>----------------]  40%
2700/5250 [==============>-------------]  51%
3200/5250 [=================>----------]  60%
3700/5250 [===================>--------]  70%
4200/5250 [======================>-----]  80%
4800/5250 [=========================>--]  91%
5250/5250 [============================] 100%
 
10 total events were executed
0 total events were scheduled
```

All the contacts failed the condition and 5250 events should have been triggered. This appears to be the same bug and no work around (since the event is being triggered after condition failure, no way to set a delay per the work around above)

This is a high priority issue! It means I can't do any complex campaigns at all. What can we do here to figure this out? How can i help. 
@lucianojmf/@rwrz any suggestions for a workaround for conditional emails? What are you guys doing to use mautic with this issue?

**Comment by dsukhin** [comment]
Diving into the code... I suspect this has to do with the limiter objects in the executioner. It seems that it perhaps keeps its state from the analyze phase to the execute phase.
`app/bundles/CampaignBundle/Executioner/InactiveExecutioner.php`

Does anyone know how to put mautic in a proper debug mode so i can see the debug level messages and print some variables?

**Comment by YosuCadilla** [comment]
Also #6321 #6368

**Comment by dsukhin** [comment]
@YosuCadilla has this issue been resolved for you?

**Comment by Shunshifu** [comment]
This was not resolved for us on the new release. The workaround, switching to using fields rather than modify segments did not work either.

**Comment by dsukhin** [comment]
Hey all (and the @mautic team). Has anyone made any headway on this? It seems to still be broken for me and a lot of others. This is super high impact since we can't schedule any complex campaigns and it's very hard to see when emails don't send. Any insight into this? Let me know how I can help!

**Comment by npracht** [comment]
Hi @dsukhin you're saying that 2.14.2 still run the same issue?
