### ISSUE TITLE
contact report issue with contact ID and company ID column

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6517]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is a bug with contacts report if you add contact ID and company ID column. In the report, the contact ID changes to the company ID.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 

### Steps to reproduce:
1. Create a report and take contacts as data source
2. First add email and contact ID
3. Save and close and check a contact
![image](https://user-images.githubusercontent.com/31535432/44973990-9a945880-af5e-11e8-92cc-72714c69d9f3.png)
4. Now add a new column which is company ID then save and close and check the report.
5. You can see that the contact ID is now the same as the company ID
![image](https://user-images.githubusercontent.com/31535432/44974034-c283bc00-af5e-11e8-9052-f234645f86ac.png)

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/6585
