### ISSUE TITLE
mautic:segments:update bug

### ISSUE THREAD

**Issue by goroakimoto** [mautic/mautic#6518]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When segment has company's & date type filter, mautic:segments:update make error.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.14.0
| PHP version | 7.0.30

### Bug ...?
mautic/app/bundles/LeadBundle/Segment/Decorator/DecoratorFactory.php

`

    public function getDecoratorForFilter(ContactSegmentFilterCrate $contactSegmentFilterCrate)
    {
        if ($contactSegmentFilterCrate->isDateType()) {
           // !! here even if isCompanyType() is true. so every filter like l.xxxxx (means leads.xxxx)
            return $this->dateOptionFactory->getDateOption($contactSegmentFilterCrate);
        }
        $originalField = $contactSegmentFilterCrate->getField();
        if (empty($this->contactSegmentFilterDictionary[$originalField])) {
            if ($contactSegmentFilterCrate->isCompanyType()) {
                return $this->companyDecorator;
            }
            return $this->baseDecorator;
        }
        return $this->customMappedDecorator;
    }

`

**Comment by escopecz** [comment]
Can you copy-paste the error message? You just wrote what file and method throws something, but not what the error is.

**Comment by npracht** [comment]
Please test https://github.com/mautic/mautic/pull/6675 it must solve your issue ;)

**Comment by goroakimoto** [comment]
Thank  you for your reply! I will try it.

**Comment by goroakimoto** [comment]
After update to 2.14.2, this bug fixed already. Thank you so much.
