### ISSUE TITLE
[contacts] save contact results in error 500

### ISSUE THREAD

**Issue by raramuridesign** [mautic/mautic#6522]
Bug

## Description:
When we edit a contact add/update fields for the contact and save, it results in the error listed below.

## If a bug:

| Q   | A
| --- | ---
The latest version of mautic 2.14.0
PHP Version 7.1.21

### Steps to reproduce:
1. Open contact, edit
2. Hit save results in an error

https://my247apps.tinytake.com/sf/Mjg5Mjc0Nl84NjgxODYy
 
### Log errors: 

[2018-09-05 11:35:42] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members." at /srv/users/projects/apps/XXXXXXX/public/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php line 46 {"exception":"[object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members. at /srv/users/projects/apps/bulkmail-my247apps-com/public/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php:46)"} []

**Comment by mbrinson** [comment]
I get the same behavior and same error message in logs.

**Comment by raramuridesign** [comment]
Is there any chance of some sort of feedback on this?

**Comment by npracht** [comment]
Hi guys,

I'm not able to reproduce. It seems you're saving a char which is not supported in the DB. Could you share your contact info screen before saving ?
Are you sure you're not using an browser autofill feature that add an expected char in the contact form information?

**Comment by npracht** [comment]
Hi @raramuridesign !
It can be anywhere in the contact table DB. Could you look for a null-byte anywhere in your leads table?

**Comment by sensalot** [comment]
I have the same thing. I open an existing Contact to edit it. I change nothing. Click apply -> Internal server error. The behaviour is identical when clicking the save button. Changing something in the contacts information does not change the behaviour.

Log message: [2019-03-27 13:48:33] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members." at /var/www/html/mautic/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php line 46 {"exception":"[object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members. at /var/www/html/mautic/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php:46)"} []

PHP 5.6.40 Mautic 2.15.0

**Comment by mbrinson** [comment]
> Hi @raramuridesign !
> It can be anywhere in the contact table DB. Could you look for a null-byte anywhere in your leads table?

Sorry to resurrect this, but could you elaborate on this a little?

Particuarlly, are you saying that if ANY field in a leads table contains a null-byte, then this error will be triggered?
I checked in my campaign_leads table, and there is a column called "date_last_exited" that contains "null" for every record.
![null-1](https://user-images.githubusercontent.com/532564/88968000-75e8ae80-d263-11ea-8d5e-e9845e7eb2e0.jpg)

**Comment by mbrinson** [comment]
For anyone else who is running into this, I shared my fix over here:

https://github.com/mautic/mautic/issues/7117
