### ISSUE TITLE
Exit intent on mobile

### ISSUE THREAD

**Issue by ldrolez** [mautic/mautic#6524]
| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | No

## Description:
I've seen Shopify apps that can detect the exit intent on mobile. 
It seems that they detect this with scrolling.
Could we implement this on Mautic too?

**Comment by npracht** [comment]
Hello @ldrolez !
This is already implemented in Focus item management (that allows you to send kind of a notification on the website). If you think about something more precise, please complete the brief and i'll re-open the issue.

**Comment by ldrolez** [comment]
Hi! In fact I should have opened this as a bug report... The problem is that Exit Intent does not work on mobile.

**Comment by alireza2281** [comment]
Hello @npracht 
I cant find any source on configuring focus item intend to exit fire on mobile. would you please send any link of doc on how to implement this?

**Comment by npracht** [comment]
Hi there,

As far as there is no mouse on mobile, i don't think the exit intent is a catchable behaviour. So I'd say this intent is not relevant for mobile users.
