### ISSUE TITLE
All email sending stopped after move from mailgun to SES

### ISSUE THREAD

**Issue by mehernosh** [mautic/mautic#6525]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
I moved from a generic SMTP sender (mailgun) to SES and all mails stopped working. I have since tried sendgrid and also tried to move back to mailgun. The funniest thing is that it shows success for sending test mails, for emails sent individually to contacts as well as actions in campaigns.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7 (7.0.30-0ubuntu0.16.04.1)

 
### Log errors: 
There is nothing in the logs out of the ordinary. The

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
