### ISSUE TITLE
Social tab in contact does not work

### ISSUE THREAD

**Issue by FaustoTu3w** [mautic/mautic#6528]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
when I click on the "social" tab of a contact (which already has the facebook field with the user) it shows this:

![mautic1](https://user-images.githubusercontent.com/29781568/45116787-7761d880-b119-11e8-94f0-2c49f27d8f2b.jpg)

The facebook user field:

![mautic2](https://user-images.githubusercontent.com/29781568/45116974-f3f4b700-b119-11e8-92be-40f1f62a4615.jpg)

No Social Profiles Found
Click here to search for social media profiles based on contact's available profile data. (Social networks must be configured in the Integration Manager).

the facebook social network is already configured in the integration manager:

![imagen](https://user-images.githubusercontent.com/29781568/45117034-269eaf80-b11a-11e8-80d6-072c0ee022f4.png)

what needs to be done to make it work correctly?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Select contact.
2. Select social tab.
 
### Log errors: 

No error log.

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Woeler** [comment]
Is there actually any activity that you are not seeing, or is the activity empty?

**Comment by OmerGafny** [comment]
Hi @FaustoTu3w , i think that social media profile appear only if the user did a social login through Mautic's LP. Just adding the the profile URL won't do it.
