### ISSUE TITLE
Categories - not possible to edit when it was unpublished once

### ISSUE THREAD

**Issue by captivea-jra** [mautic/mautic#6529]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | 
| Enhancement? | 

## Description:
Hi,

Sometimes, it is not possible to edit a category on the application, there is an alert message : "You do not have access to the requested area/action.". 
And When you click "ok", the pop-up of edition is endlessly loading.

This is due to technical fields :
- checked_out which is a date
- checked_out_by which is a user

When a categorie is unpublished (Edit > Published : No > Apply), these fields are saved with information of the user who did the update. 
So, the category is modifiable only by this user. 
But when the category is published again after, these values are not cleared, so the category remains not accessible by other users.

The checkd_out fileds should be cleared when the category is published once again.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1 / 2.13.1
| PHP version | 7.0.26 / 7.0.27

### Steps to reproduce:
1. A user 1 goes on a category
2. Edits to unpublished and apply
3. A user 2 try to edit the same category (even an admin)
4. He can't and have the error message

**Comment by JustineRadice** [comment]
The error message on a pop-up is : "You do not have access to the requested area/action." 
And then, the edition view is undefinitively loading.

**Comment by ShagunParikh** [comment]
Same issue

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by captivea-jra** [comment]
Hi Norman,

Thank you for your information and the monitoring.
Our customer who was impacted by the issue does not use Mautic anymore and
we don't have any instance on version 3.0.2.
So I think we can close this issue, except if you want to manage this issue
for the community.

Cordialement,

**Comment by npracht** [comment]
Bonjour Justine !
Thanks for your feedback. I'll close this issue and re-open in case someone meet the issue again.
