### ISSUE TITLE
Duplicate contacts created by Pipedrive integration

### ISSUE THREAD

**Issue by jsalvata** [mautic/mautic#6532]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:

We're testing Mautic and its Pipedrive integration and mostly every new contact created in Pipedrive is being replicated with multiple copies in Mautic.

This seems to be caused by an added.person and multiple updated.person webhook requests being issued mostly concurrently by Pipedrive.

The problem goes away if we disable the updated.person webhooks, but of course we then loose synchronization.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.14.0
| PHP version | 5.6.37

### Steps to reproduce:

1. Follow documentation of the Pipedrive Plugin to configure webhooks in Pipedrive to send added.person and updated.person events to Mautic
2. Create a contact in Pipedrive
3. Check the list of contacts

Expected result: the newly created contact should appear once in the ist.

Actual result: the newly created contact appears two or three times in the list, with different ids

In our installation, these steps are effective at reproducing the bug about 10% of the time. You may need to repeat the steps a few times to observe it.

### Log errors: 

None

### Likely cause:

It looks like Pipedrive launches one added.person and multiple updated.person webhook requests concurrently.

Method `update` in `plugins/MauticCrmBundle/Integration/Pipedrive/Import/LeadImport.php` first looks for the contact's Pipedrive id in the `IntegrationEntity` repository. If it is not found, it calls the `create` method.

If multiple webhook requests are running concurrently, it is possible that they all go through that check and they all turn into "create" before any of them creates the first `IntegrationEntity` in the database.

**Comment by kuzmany** [comment]
Did you try? https://github.com/mautic/mautic/pull/5401

Please test and write comments, you should speed up release in next Mautic version

**Comment by npracht** [comment]
Hi @jsalvata ! Thanks a lot for your contribution. I'll mark this issue as duplicate because it has been mentioned in some other issues and my last tests proved that the PR #5401 solves the issue.
Please test and confirm !

**Comment by jsalvata** [comment]
Oh, I understood #5401 was about synchronization in the opposite direction. I'll try now (will take a while, will be my first install from source).

**Comment by jsalvata** [comment]
We've run a few tests and it works. We'll stick to this branch and upgrade once the PR has been merged.

Thanks a lot for your help.

**Comment by jsalvata** [comment]
Bad news: after having it running in production for a few days, we encounter about 4% of contacts have been duplicated -- same behaviour: created within the same minute.

We no longer have issues of triplicate or quadruplicate contacts as we used to with the released Mautic version.

I'll try to edit the description and reopen.
