### ISSUE TITLE
Triggers - existing applicable contacts

### ISSUE THREAD

**Issue by captivea-jra** [mautic/mautic#6535]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
Hi,

When you create a trigger and you activate the field "Trigger for existing applicable contacts upon saving (if published)?", it has no effect. 
It should run the trigger's actions on all existing contacts who have the conditions of the triggers (number of points), but it does not do anything for existing contacts, even though the trigger is functional for new contacts. So, the trigger is correct but not the setting for existing contacts.

Thanks for your help and your actions.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.10.1
| PHP version | 7.0.26

### Steps to reproduce:
1. Create a trigger with a condition on points which match with some existing contacts (for example minimum 50 points)
2. Add an event to this trigger, for exemple "modify the contact's segment"
3. Activate the field "Trigger for existing applicable contacts upon saving (if published)?" and publish the trigger
4. Wait and see not any existing contact has his segment modified thanks to the trigger. 
5. Create a new contact with 60 points and check the segment is added by the trigger's event.

**Comment by npracht** [comment]
Hello @JustineRadice !
Would you try to update to 2.14.1 and confirm it is still not functional ?

**Comment by JustineRadice** [comment]
Hello @npracht 
We have scheduled to upgrade with the last version so we can wait till this upgrade and tell you if the bug is fixed.
It was mainly to alert you, we used a workaround for the moment.
