### ISSUE TITLE
Mailgun Integration (2nd Attempt)

### ISSUE THREAD

**Issue by iwantaspeaker** [mautic/mautic#6536]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | YES
| Enhancement? | 

## Description:
MailGun integration (Webhook or Plugin) for Mautic, to allow for Unsubscribe and bounces of emails, etc.
This is a reopening of https://github.com/mautic/mautic/issues/1694 as NO answer has ever been given, and ALOT of people are requesting a solution.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Shirkit** [comment]
I also would love to see this. I'm using MailGun and Mautic and I do a monthly check to see if someone has reported me to unsubscribe them.

**Comment by martinstr** [comment]
would also love to see this...

**Comment by heathdutton** [comment]
I think the reason this hasn't been attacked is the fact that Mailgun works *OK* with SMTP support out of the box.

Willing to post a bounty to add an incentive? https://www.bountysource.com/issues/63130974-mailgun-integration-2nd-attempt

**Comment by klesti** [comment]
This would be really helpful

**Comment by luigidon** [comment]
I also hope for Mailgun integration....

**Comment by azamuddin** [comment]
+1

**Comment by azamuddin** [comment]
@here Hi, I finally managed to make mailgun plugin for mautic. 
I have tested it in Mautic version 2.15.0 and it works perfectly. 

https://github.com/azamuddin/mautic-mailgun-plugin

**Comment by Shirkit** [comment]
I'm installing it on my smaller business server and will report back after some testing.

**Comment by Shirkit** [comment]
Ok, so I broke my other Mautic installation (not cauased by this plugin) but I could test some steps.

Unsubscribe works (but don't know who would want to use it since Mautic has one), as well as Bounces/Fails.

Spam report didn't make it through from Gmail as of this moment, so I cannot comment on that.

There's no Integration with Mailgun's "Click Trakcing" and "Open Tracking", but since Mautic already does this very well, I don't think that's an issue. Probably is worth noting on the readme that.

I give this a 10/10 for testing. Now I need to fix my install, and maybe start using this on my 100k contacts server. I'm tired of manually dealing with bounces!

**Comment by azamuddin** [comment]
@Shirkit based on official mail transport I observed, I believe `Click Tracking` and `Open Tracking` are handled by mautic. While those integration should only handle 3 types of event, `Bounced / Failed`, `Unsubscribe` and `Spam`. Well yes, I should state this in README.

**Comment by Shirkit** [comment]
Actually, if you enable Mailgun's "Click tracking" and "Open Tracking" it will do two things:

-  add Mailgun's pixel on the email body. There's Mautic's pixel already if you have enabled tracking (which you most likely should have).

- replace any links in emails with Mailgun's link tracking. If you have tracking enabled on Mautic, then it's going to do this: Any URL <- Mautic's Redirection <- Mailgun's Redirection.

So, actually, having tracking enabled in Mautic and enabling in Mailgun is bad, unless you REALLY need the data at Mailgun's server.

Mailgun's Webhook API can return both Click and Open events. But I can't think of a use case for using Mailgun's tracking and not Mautic's. I don't know if Mautic can accept input from Webhooks to register Open and Click events (I imagine it can), but I can't think of a reason to implement this.

**Comment by quadcom** [comment]
Just thought I'd chime in saying I have Mailgun working fine with SMTP login. Not using MG's tracking or bounce. Sends emails just fine this way.

**Comment by stars05** [comment]
Hi all, here’s I’ve created new plugin for mailgun, now you can send messages with mailgun api. 

https://github.com/stars05/mautic-mailgun-mailer-plugin

Hope you like it)

**Comment by mabumusa1** [comment]
@stars05 I am writing mailgun transport to be part of Mautic core, would like to work with me on this? We can integrate many parts of your code with what I already wrote

Take a look at the code here

https://github.com/mautic/mautic/pull/9310

**Comment by stars05** [comment]
@mabumusa1 hello, yes we could work together on current integrated plugin. Let’s discuss details, how can I help you?

**Comment by mabumusa1** [comment]
@stars05 I think you wrote many important parts, we need to automated tests for them and make them as core components. I can add you to my Mautic fork and work on one branch together to make it happen

**Comment by imihandstand** [comment]
(I wrote this to a Mautic-Forum's post, but thought people here would need it too)

Tip: For handling Mailgun’s **“Spam Complaints”** and **“Permanent Failure”**, I use Integromat (automatization, like Zapier).
Mailgun’s webhook fires the “scenario” in Integromat and than that spam/failed contact gets deleted from Mautic.
You can use of course Mailgun’s other webooks, like “Temporary Failure”, “Unsubscribes”, etc.
