### ISSUE TITLE
Issues with installing on local machine

### ISSUE THREAD

**Issue by BenSegni** [mautic/mautic#6546]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | How do I run mautic locally? Instructions are not working. 
| Bug report? | Doesn't install based on instructions from documentation

## Description:
I have been tasked with drawing up some email templates for a client and for the first time, looked to install mautic locally. Following the process: 
1. clone mautic from git (cloned from master) - OK
2. ran composer install - OK
3. Create local Mysql using phpmyadmin - OK
4. navigate to http://localhost/mautic (which takes me to: http://localhost/mautic/installer - presents me with this error: 

"The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator."

checked the console: 

Error: Failed to load resource: the server responded with a status of 500 (Internal Server Error)

So basically, nothing coming or going. 

I'm using PHP 7.1.16 - any ideas or things I could look at to why I can't run locally, would be much appreciated. Thank you. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version  | - whatever is currently at staging and master, as I've tried both
| PHP version  | 7.1.16

### Steps to reproduce:
1. clone from github 
2. cd into mautic and run composer install
3. navigate to localhost/mautic
 
### Log errors: 

no log files generated. 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by BenSegni** [comment]
found this in the readme file: http://localhost/mautic/index_dev.php/s/

it showed a log of errors and turned out to be a permissions issue. chmod -R 755 mautic at root level of the server fixed it.

**Comment by knitish23** [comment]
When I install mautic on local machine it shows 403 forbidden error. pls help
