### ISSUE TITLE
500 Internal Server Error - PHP Notice - Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256'

### ISSUE THREAD

**Issue by BenSegni** [mautic/mautic#6548]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| how do I get around this?|

## Description:
I'm getting this error after installation. This is my first play with Mautic, so this may be a system setup issue on my part.

Any suggestions would be greatly appreciated. 

Thank you. 

## If a bug:

| Q   | A
| Not sure if it is. | 
| Mautic version | Current version from master
| PHP version | 7.1

### Steps to reproduce:
1. Entered sign up details 
2. pressed submit, got the above error and logs. 
 
### Log errors: 

/app/cache/dev/appDevDebugProjectContainer.php:6537 at
/app/cache/dev/appDevDebugProjectContainer.php:6537 at Mautic\CoreBundle\ErrorHandler\ErrorHandler -> handleError ( '8', 'PHP Notice - Use of undefined constant MCRYPT_RIJNDAEL_256 - assumed 'MCRYPT_RIJNDAEL_256'', '/Users/bensegni/Sites/mautic/app/cache/dev/appDevDebugProjectContainer.php', '6537', array() )
/vendor/symfony/dependency-injection/Container.php:297 at appDevDebugProjectContainer -> getMautic_Cipher_McryptService ( )
/app/cache/dev/appDevDebugProjectContainer.php:10939 at Symfony\Component\DependencyInjection\Container -> get ( 'mautic.cipher.mcrypt' )
/vendor/symfony/dependency-injection/Container.php:297 at appDevDebugProjectContainer -> getMautic_Helper_EncryptionService ( )
/app/cache/dev/appDevDebugProjectContainer.php:11975 at Symfony\Component\DependencyInjection\Container -> get ( 'mautic.helper.encryption' )
/vendor/symfony/dependency-injection/Container.php:297 at appDevDebugProjectContainer -> getMautic_Integration_OnesignalService ( )
/app/bundles/PluginBundle/Helper/IntegrationHelper.php:257 at Symfony\Component\DependencyInjection\Container -> get ( 'mautic.integration.onesignal' )
/app/bundles/UserBundle/Controller/SecurityController.php:105 at Mautic\PluginBundle\Helper\IntegrationHelper -> getIntegrationObjects ( null, array('sso_service'), true, null, true )
/vendor/symfony/http-kernel/HttpKernel.php:135 at Mautic\UserBundle\Controller\SecurityController -> loginAction ( )
/vendor/symfony/http-kernel/HttpKernel.php:57 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php:67 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
/vendor/symfony/http-kernel/Kernel.php:183 at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel -> handle ( object(Request), '1', true )
/app/AppKernel.php:133 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
/app/middlewares/CORSMiddleware.php:93 at AppKernel -> handle ( object(Request), '1', true )
/app/middlewares/CatchExceptionMiddleware.php:45 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/Dev/IpRestrictMiddleware.php:66 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/VersionCheckMiddleware.php:57 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/run/src/Stack/run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request) )
/index_dev.php:34 at Stack\run ( object(StackedHttpKernel) )

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Woeler** [comment]
Seems like you do not have the Mcrypt PHP module installed on your environment.

**Comment by BenSegni** [comment]
Hi @Woeler, yep, just installed it with homebrew, cleared the cache and it's still showing the same error. This is the right path to login, right?

http://localhost/mautic/index_dev.php/s/login

**Comment by Woeler** [comment]
Make sure you clear the mautic cache. Also, not sure why you are including a php file in the url. You should simply navigate to the root url. Which I am assuming is `localhost/mautic` for you.

**Comment by BenSegni** [comment]
Just what it's saying in the readme file from the repo - http://localhost/mautic/index_dev.php/s/. navigating to there, brings up a different error: 

navigating to: localhost/mautic - i get this...

"The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator." - and there are no logs created for this. 

I have cleared the cache before I replied to your message. Still the same issue. :/

**Comment by Woeler** [comment]
Very strange. That there are no logs seems obvious as it is a 500 error. Do you apache/nginx logs say anything?

**Comment by BenSegni** [comment]
checked and found this: 

RuntimeException: Cache directory "/Users/bensegni/Sites/mautic/app/cache/prod" is not writable. So might be a permissions issue. I'll see if that lifts the lid on this, otherwise, I'm going to try and install a version in a live environment on a sub directory on my server and see if that works.

**Comment by Woeler** [comment]
That does seem like a permission issue. Let us know if that fixes it or not.

**Comment by BenSegni** [comment]
Thanks will do - just setting perms on cache/prod now. The fact it's trying to clear the cache for production possibly be an issue? Where do we define what environment we are working in?

**Comment by Woeler** [comment]
From the dev docs:

There are three environments in Mautic: prod, dev, and test.

prod is used when accessing the site through index.php.

dev is used when accessing the site through index_dev.php. Using Mautic in the dev environment will activate Symfony’s profiler toolbar, has more strict error handling, will display information about exceptions, and will not cache as much (see below). Note that steps should be taken to ensure index_dev.php is not accessible to the public as it could potentially reveal sensitive information. It is restricted to localhost by default. However, there are two ways to allow access to index_dev.php from a non-localhost. The first option is to set a header from the web-server with the IP addresses assigned to MAUTIC_DEV_HOSTS. The second and easier option is to add an array to your installation’s app/config/local.php file as 'dev_hosts' = ['123.123.123.123', '124.124.124.124'], then clear the cache.

test is used mainly for PHP Unit Tests.

https://developer.mautic.org/#development-environment

**Comment by BenSegni** [comment]
thanks for this. Yes, think accessing the UI via localhost/mautic was the correct approach, so no need to alter any of the config, but it's still not running. I'm setting up a sandbox on my own server and see if it will run with an install via ftp and some live db credentials.

**Comment by BenSegni** [comment]
The purpose is simply to have an instance running to develop up some email templates for a client, so I don't really want to touch the codebase in any way. I just need an instance running to upload theme templates and test that they work.

**Comment by npracht** [comment]
Hello @BenSegni !
Please ask this type of server configuration questions on the Slack #dev or #general channel.
You can also run a test instance on https://mautic.com/offers/mautic-cloud-free/

Best !
