### ISSUE TITLE
Campaign decision based on checkbox group form field checks lable, not value

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#6550]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | N 
| Enhancement? |  N

## Description:
Campaign builder helps you to set up a decision based on a form field. However - its saving the field lable to check, not the field value.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2

### Steps to reproduce:
1. add a campaign form
2. make a checkbox group field

![form](https://user-images.githubusercontent.com/1241376/55433566-e1e6d400-5595-11e9-8d4b-c94a1fbbce68.png)

![webfrontend form](https://user-images.githubusercontent.com/1241376/55433611-f75bfe00-5595-11e9-905a-70557d2b80cc.png)

3. give the field a value with a lable (e.g. "Marketing Automation") and a value (e.g. "ma"),
4. have a campaign check for this fields value,

![checkslabelnotvalue](https://user-images.githubusercontent.com/1241376/55433620-fc20b200-5595-11e9-98d3-c30954d245c8.png)

5. editor supports you with the selection of the field and lets you set a e.g. a boolean operation (e.g. "equals") to check for the field value, 
6. while helping you with the potential value lable by showing "Marketing Automation", it should check for the value "ma"

The condition can't be saved, as of course the "value is not valid" - because its the label.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dsp76** [comment]
Still in 2.15.0

**Comment by dsp76** [comment]
@npracht Workaround doesn't work anymore. Can't save the condition anymore to edit it in a second try. So analyzing a submited form field of type selection doesn't work anymore in a campaign.

**Comment by dsp76** [comment]
Added some screenshots and edited the issue to make it a bit clearer.

**Comment by dsp76** [comment]
Actually testet it again and it works. Its only that this error message comes up, but saving it a second time brings it back to work. Campaign works fine afterwards!

![checkslabelnotvalue](https://user-images.githubusercontent.com/1241376/55435617-89660580-559a-11e9-9e31-67360acc1b35.png)

@npracht should this become a new bug and this initial one should be closed?

**Comment by RCheesley** [comment]
Closing as this was resolved with recent releases
