### ISSUE TITLE
features - campaign update contacts

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6553]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
In a campaign, there is the possiblity to update contact field with the action
![image](https://user-images.githubusercontent.com/31535432/45351465-8bdd1f80-b5b6-11e8-9ecc-c081d4a79927.png)

Currently if you let fields blank, nothing happens which is good. 
But another opportunity would be to choose to remove values of select or select multiple fields.

**Comment by kuzmany** [comment]
WIP https://github.com/mautic/mautic/pull/6587

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/6587
In future we can add this option also to https://github.com/mautic/mautic/pull/5628

**Comment by kuzmany** [comment]
Added the same option to Update contact's primary company  action.

**Comment by johbuch** [comment]
tested on mautixbox --> works

**Comment by npracht** [comment]
Would it be possible to think about something where you can remove a specific value from a multiselect field ?
>eg:
>Norman has in field multi select the value `A` and `B`
>Campaign action *remove B from multiselect*

**Comment by kuzmany** [comment]
@npracht working on it

**Comment by kuzmany** [comment]
New pull request for test with new UX: https://github.com/mautic/mautic/pull/6805
