### ISSUE TITLE
how to cleanup lead_event_log entries  generated by import from csv...

### ISSUE THREAD

**Issue by giorgiopaolucci** [mautic/mautic#6555]
Feature request:
Hello,
I have a mautic 2.13 installation and I perform a daily import of 80K users from a csv. My cvs file can have small variations in user base.

My lead_event_log table gets full of rows containing events like:
|  4 |       8 |       1 | Automatic feed | lead   | import | updated |         2 | 2018-04-19 14:53:22 | {"line":6,"file":"users.20180419164500.csv"}  |

Every day the table size increases by 80K rows.
Can I safely delete all rows regarding the import without compromising the db consistency ?
Is there any cli command to perform such a clean up? 

Thanks in advance.
Giorgio Paolucci

**Comment by npracht** [comment]
Hello @giorgiopaolucci !
Thanks for your message. I guess you can have a look at https://github.com/mautic/mautic/pull/2024. Also for technical advices you'll have better chances to get answer using our chat on Slack.

Thanks for your understanding !
