### ISSUE TITLE
Remote database server with SSL connection

### ISSUE THREAD

**Issue by tylerfoulkes** [mautic/mautic#6556]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
I am looking to implement Mautic using separate app and database servers. The connection needs to run over SSL as well. I already have the app and database servers setup and running over SSL without Mautic installed. It looks like you can just add the following array to the $dbalSettings array that gets passed to Doctrine in the app/config/config.php file in order to support an SSL connection with the database server when using Mautic. 
```
'options' => [
        'PDO:MYSQL_ATTR_SSL_CA' => '/path/to/cert',
        'PDO:MYSQL_ATTR_SSL_CERT' => '/path/to/cert',
        'PDO:MYSQL_ATTR_SSL_KEY' => '/path/to/key'
]
```
Has anybody looked into this at all?

**Comment by npracht** [comment]
Hello @tylerfoulkes !
Thanks for your message. I guess you'll have better chances to get an answer if you move your question to the chat on Slack. You have a #dev channel or even #general and people may help you better that here where we are supposed to manage issues and bugs.

Thanks for your understanding.
Best !
