### ISSUE TITLE
Lead created with just email (via javascript) not showing email in segment contacts

### ISSUE THREAD

**Issue by taewookim** [mautic/mautic#6557]
| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | No 
| Enhancement? |  No

## Description:

Not sure if bug or if I am taking the wrong steps

I am using WP Mautic  with woocommerce. 
1) when page loads, mautic's pageview pixel is fired 
2) user fills out a form with JUST email
3) i use mautics contact monitoring (as [described here](https://www.mautic.org/docs/en/contacts/contact_monitoring.html))

```
<script type="text/javascript">
console.log("Check functions.php for optin spin");
jQuery(document).ready(function(e){
    jQuery('.form').change(function(){
      	var email = jQuery(".email").val(); 
				console.log("Changed to "+ email);
				var mautic_json = {"email" : email};
				console.log(mautic_json);
				mt('send', 'pageview', mautic_json);
    });
});
</script>

```

I have a segment that takes ALL that were created since 2010. So this naturally creates a contact in this default segment.

However, there's NO email there

Here's the firebug POST: https://s22.postimg.cc/kyi0u6vxd/image.png

Firebug response: 

` {"success":1,"id":20,"sid":"nmzrlbpyyuqsadzoyu20jam","device_id":"nmzrlbpyyuqsadzoyu20jam","events":[false]}
`

However, 

https://s22.postimg.cc/gpdas52zl/image.png

Is this a bug or am I misunderstanding something?

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  Latest, as of 9/11/2018
| PHP version |  7.0.9

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello,

Is your field email "publicly updatable" in custom field settings ?

**Comment by taewookim** [comment]
AH... my apologies for that. I feel like a complete numb nut. Didnt realize such field even existed (mautic user < 3 days)

Took your advice.. set email to "publicly editable".. hit apply... then , i noticed the progress bar doesn't end.

Fired up firebug and saw this error:
 
https://s22.postimg.cc/v6esuyild/image.png

But the field did seem to save.  Is this something I need to worry about?

**Comment by npracht** [comment]
I'm not a dev, even less a javascript dev haha. But if the contact is created with the email in your mautic, i'd say you can be happy? :D
