### ISSUE TITLE
Social Profile Instagram not fetching data to social tabs

### ISSUE THREAD

**Issue by architjoshihs** [mautic/mautic#6558]
Social Profile Instagram not fetching data to social tabs. Will it not work in sandbox mode?

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

| Q   | A
| --- | ---
| Mautic version | 2.13
| PHP version | 7.0

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
