### ISSUE TITLE
Click on link in email results in 500 error

### ISSUE THREAD

**Issue by phenixiim** [mautic/mautic#6559]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N 
| Enhancement? | N

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

### Steps to reproduce:
1. make a link in an e-mail, send it
2. click through e-mail to some link
 
### Log errors: 
[2018-09-12 10:48:24] mautic.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getId() on null - in file /opt/mautic/app/bundles/LeadBundle/Helper/ContactRequestHelper.php - at line 173 [] []

**Comment by npracht** [comment]
Hello @phenixiim i think it has been reported already and fixed by https://github.com/mautic/mautic/pull/6441 in 2.14.1.
Could you test and confirm (+close your issue if confirmed) ?
Thanks !

**Comment by phenixiim** [comment]
Sorry, I have missed this update. Is there some shortcut to upgrade?
because:
sudo app/console mautic:update:find
results in
Great! You are running the current version of Mautic.
Thanks!

**Comment by Carlos-mb** [comment]
Still failing for me after apply modificacions in 2.14.0

**Comment by phenixiim** [comment]
Sorry gyus, but that's probably not best practic to update to failing version. What is the correct process to update to minor version? I have tried to find it but I was not successful. Thanks

**Comment by npracht** [comment]
Hi @phenixiim & @Carlos-mb if you wait now for few hours/days, the final `2.14.1` version including this patch will be out. You'll be able to update your mautic instance directly from the interface.

**Comment by phenixiim** [comment]
Great! Thanks!

**Comment by Carlos-mb** [comment]
Great. 

Thank you
