### ISSUE TITLE
Salesforce Integration: Lead conversion in Salesforce

### ISSUE THREAD

**Issue by GinoVdh78** [mautic/mautic#6560]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

Hi All,

We are facing some issues with the integration between Mautic and Salesforce.

**_Scenario:_**
1. Lead ‘X’ is entered in Mautic and gets pushed to Salesforce
2. In Salesforce you convert this new lead to a contact ‘X’.
3. In Mautic an update gets triggered for this Lead ‘X’ and gets pushed to Salesforce.
4.  Following Error is returned: “cannot reference converted lead”

This is normal behavior.  When you convert a lead to a contact in Salesforce, the lead record itself stays in the database but it becomes read only (and invisible via ui searches).

**_Issue:_**

When a lead is converted in Salesforce, there must be a push to Mautic to change the lead id into the contact Id.

**_Our Idea:_**
1.	Create webservice that’s called by Salesforce
2.	Each time a lead gets converted in Salesforce the webservice gets called and will do the following 
        database update:

       update integration_entity
       set integration_entity = Param1,
       integration_entity_id = Param2
       where integration_entity_id = Param3

       Param1: ‘Lead’ or ‘Contact’ (varchar)
       Param2: Salesforce Contact Id (varchar)
       Param3: Salesforce Lead Id (varchar)

**_Question:_**

A nicer way would probably be to do this via API calls.  Is this possible? Or this there another way to accomplish this?

Kind Regards

Gino

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
