### ISSUE TITLE
Mautic sync with Salesforce: Limit number of retries 

### ISSUE THREAD

**Issue by GinoVdh78** [mautic/mautic#6561]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
Hi All,

Scenario:

1.	Lead is created in Mautic and has been pushed to Salesforce
2.	Salesforce returns an error (like missing field, invalid email, etc…, so no connection errors)
3.	Mautic keeps repushing this lead to Salesforce, even when nothing has been updated to the lead 
       record in Mautic.

Question:

For the moment we don’t know how to limit these number of retries or how to cancel them.  This is causing a huge amount of notification errors.  Is there a way to limit these number of retries?

Kind Regards

Gino

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
