### ISSUE TITLE
Company Tokens do not populate when sending manually from Mautic

### ISSUE THREAD

**Issue by rbagley0310** [mautic/mautic#6564]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N 
| Enhancement? |  N

## Description:
None of the Company tokens are replacing when I insert them into Email content.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.31

### Steps to reproduce:
1. Create Company.
2. Create Contact and assign it to Company.
3. Insert {contactfield=companyname}  into Email created with the Blank Theme.
4. Use Send Email function inside of dropdown for Contact listing.
5. Fill in form using the modal popup by selecting the template.
6. Submit.
 
### Log errors: 
None.
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mclendening** [comment]
I tested it per the steps to reproduced and found the problem is the same in 2.14-1 Beta. Additionally - none of the contactfield tokens worked in the email when using the {contactfield=companyname}. However, I found that if you use the {contactfield=company} token all works fine.

**Comment by rbagley0310** [comment]
I understand but the replacement in the autocomplete in the HTML form supplies the one I put in the message. Should any token that are listed there populate with the expected value?

**Comment by npracht** [comment]
Hello @rbagley0310 , can you test https://github.com/mautic/mautic/pull/7406 ?

**Comment by npracht** [comment]
Fixed when #7406 merged.
