### ISSUE TITLE
Amazon SES 62k free mail benefits with remote hosted mautic

### ISSUE THREAD

**Issue by lixaotec** [mautic/mautic#6571]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | no
| Feature request? | no
| Enhancement? | no

## Description:
The more details the better...

Dear friends

This is not an issue but a question on how-to.

I wish to get Amazon SES free tier benefits of 50k /month mail using mautic. However I wish not no host my mautic instance at Amazon tier (the meaning of remote).

How could I accomplish that?
Is there any middleware smtp api to receive mautic queue being hosted at amazon and then enabling thoso benefits?

Does mautic supports something like that?

Thank you

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by benpoulson** [comment]
You can host Mautic anywhere, and still use SES. You are not tied into using their infrastructure.
