### ISSUE TITLE
Page Builder Breaking tag

### ISSUE THREAD

**Issue by MrBird77** [mautic/mautic#6575]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| 1| ---
| Bug report? | 1
| Feature request? | 
| Enhancement? | 

## Description:
After modifying a theme to include google analytics and Drift tags in the header, It was found that while loading initially, as soon as you hit apply in the builder area it corrupts the code in the header notably the && being turned into 'amp' and a piece of code from the GA tag injected into the top of the Drift tag. 

## If a bug:

| Q   | A
| - | ---
| Mautic version | 2.14.0
| PHP version | 7.1.21

### Steps to reproduce:
1. Stick tags in header and upload
2. hit apply in builder and see if it breaks drift bot.
 
### Log errors: 

[08-Sep-2018 17:40:02 UTC] PHP Warning:  Creating default object from empty value in /home/***/***.org/wp-content/themes/flat-responsive/inc/customizer.php on line 174

**Comment by escopecz** [comment]
Use this instead:
![screen shot 2018-10-18 at 13 17 24](https://user-images.githubusercontent.com/1235442/47150843-37754000-d2d8-11e8-8ca9-e0360939f257.png)
