### ISSUE TITLE
Pipedrive integration

### ISSUE THREAD

**Issue by troelsfeodor** [mautic/mautic#659]
I'd love to see an integration with https://www.pipedrive.com sales CRM. It would be great to be able to push leads to Pipedrive after reaching x points and pass on the lead details like sources and campaigns. It should auto sync both ways, so the sales people working in Pipedrive would be able to see which emails the lead is receiving etc.

**Comment by paulocastellano** [comment]
+1

**Comment by williamsdb** [comment]
+1

**Comment by seidatpaulus** [comment]
+1

**Comment by VinCardoso** [comment]
+1

**Comment by rodrigoscotti** [comment]
A must!!!

**Comment by erikpixel** [comment]
+1 Pleaseeee

**Comment by vdittgen** [comment]
+1

**Comment by waldemiro** [comment]
+1 Please!!

**Comment by arthurlluiz** [comment]
+1

**Comment by jayquest** [comment]
+1

**Comment by arthurfarache** [comment]
+1

**Comment by T1ro** [comment]
+1

**Comment by nickbuc1** [comment]
+1

**Comment by stollz** [comment]
Please take a look at https://github.com/stollz/MauticPipedrive

**Comment by npracht** [comment]
Hi @stollz could you make a Pull Request with that code in the view that all the community could benefit from it when it'll be merged into mautic core code ?

**Comment by stollz** [comment]
@npracht Can you please guide me through steps account how Can I do it and it is to Master branch or some sub branch?
"My first open source contribution" don't have much ideas on pull request and submission of code.
or may be just check if I did fine in above mentioned reference.

**Comment by npracht** [comment]
@escopecz we will work @thecodeine & @webmecanik on that. Maybe you can assign that to us ?

**Comment by escopecz** [comment]
@npracht I'd like to, but https://github.com/mautic/mautic/issues/3461#issuecomment-285751063

**Comment by npracht** [comment]
true that...

Dear community, we work on it! :)

**Comment by zora-li** [comment]
Hello ! I updated to Mautic 2.9.0 and Pipedrive Integration is avaiable in plugins.

I notice that the emails are duplicated instead merging to existing contats. 

Is threre something wrong I did ?

tks

**Comment by MauticDevelopers** [comment]
Hi @zora-li 

We are authors of this integration. Please contact us at hello@mauticdevelopers.com and we will help you.

Regards

**Comment by escopecz** [comment]
Closing as it was implemented in 2.9.0
