### ISSUE TITLE
Scroll on top of the form if validation returns errors

### ISSUE THREAD

**Issue by wiprich** [mautic/mautic#6595]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
The Mautic Form Validation Script is not working properly on terms ou usability.
I'm using WP-Mautic and when i test the form, the required fields are marked and popup, but they are not focusing on the item who are required.

If you are on mobile and click to send the form and are unfilled itens, the page just don't scroll up or show anything on mobile. The noob user with think the page is broken, unless they scroll up.

There are no many options for customizations or error customizations/control.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.30-0ubuntu0.16.04.1

### Steps to reproduce:
1. Access from mobile: https://pluginenergia.com/orcamento/
2. Try to send the form without fill the fields
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by andrekutianski** [comment]
I have a similar problem. My Mautic is integrated with WordPress through _WP Mautic_ Plugin. When I try submit a form with no information, the validation process insert into the URL the error messages:

> ?mauticError=Errors%3A<br%20%2F><ol><li>Por%20favor%2C%20insira%20seu%20primeiro%20nome%21<%2Fli><li>Por%20favor%2C%20insira%20seu%20sobrenome%21<%2Fli><li>Por%20favor%2C%20informe%20seu%20e-mail%21<%2Fli><%2Fol>

**Comment by andrekutianski** [comment]
I beleave the is related to https://github.com/mautic/mautic-wordpress/issues/83

**Comment by npracht** [comment]
I'll close it, debate is on wordpress plugin repository
