### ISSUE TITLE
 The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator. System administrators, check server logs for errors.

### ISSUE THREAD

**Issue by Carlos-mb** [mautic/mautic#6597]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
After add Facebook and Google Analytics IDs my site is down. 

This is so frustrating.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.31
### Steps to reproduce:
1. Add facebook pixel ID and activate tracking
2. Add google Analytics ID and activate tracking
3. Try to access Mautic
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

No logs recorded for this error.

**Comment by Carlos-mb** [comment]
If you edit a file in /...mautic/app/bundles/CampaignBundle/Entity and leave there a backup of original file calle "*.ori" the system tries to load it as an entity and fails. 

The file had been there for one day, I don't know why it fails right now. Was it because I changed the configuration? Maybe... 

Anyway, I have deleted the file and site is working again.

**Comment by vbezruchkin** [comment]
Hi,

I have the same issue. I use docker container for Mautic. It was working fine until I added Google Analytics ID. Once saved, the only thing I can see is the error you posted above.

So weird to see it after the config changes...

**Comment by Khaled4** [comment]
You can check your error log. It will mention where the problem is, in most cases.
Meanwhile, check if you have recently (last couple of days!) added any file "not known" to Mautic.

**Comment by vbezruchkin** [comment]
Yes, thanks. Working on this.

**Comment by Bizcrony** [comment]
https://www.mautic.org/docs/en/tips/troubleshooting.html

**Comment by techzotezo** [comment]
The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
System administrators, check server logs for errors.

Log is not showing nothing.Restarted the server...Permission has been set.. still not opening...What to check please suggest...

**Comment by RafaelFariaFerreira** [comment]
Same error here using php 7.0 and OpenLiteSpeed web server. I'v just unzipped the file at my server and saw this issue when i accessed in the browser

**Comment by AKr0nizz** [comment]
Same issue for me. 

Can't even understand the starting point to make an investigation. 

Are there any updates?

**Comment by ruyherrod** [comment]
chown -R www-data /var/www/html/mautic/ solve the problem.
systemctl restart apache2.service or /etc/init.d/apache2 restart

**Comment by AKr0nizz** [comment]
Thanks for the @ruyherrod 
For all OpenLightSpeed & Cyberpanel users. 

**Run this:**
chown -R your_mautic_user /home/your_mautic_durectory/public_html
reboot openlightspeed

**Comment by Interacthink** [comment]
@konstantin-lebejko  Where do I put this code?

**Comment by DigitalFreelancing** [comment]
You just need to clean your Mautic cache for fix the problem. It's located in /var/cache 

Just delete everything inside that folder. It worked for me :)

**Comment by beto2l** [comment]
> chown -R www-data /var/www/html/mautic/ solve the problem. systemctl restart apache2.service or /etc/init.d/apache2 restart

if you work with Nginx, you should do: **systemctl restart nginx** instead of apache2.

**Comment by edmundciego** [comment]
Still nothing on my end. anybody tried something else?
