### ISSUE TITLE
Unlink contact tracking

### ISSUE THREAD

**Issue by fphunzz** [mautic/mautic#6602]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | N

## Description:
Got a contact that is being tracked by the wrong person. If I recreate the contact, the tracking would be removed, but it could be done faster with a "Release tracking" button. Then next mail to that contact would get the right person.

Also, options to clear history or not would be great.

Thank you!

**Comment by escopecz** [comment]
Tracking is not 100% accurate. Make sure you have the IP and fingerprint tracking turned off to avoid most of these problems.

Creating new email and sending that contact an email with a link to a Mautic-tracked page would restore the session tracking.
