### ISSUE TITLE
Uncaught ReferenceError: Mautic is not defined at dashboard:1023

### ISSUE THREAD

**Issue by PauloNevesF** [mautic/mautic#6604]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y

| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0.30-0

### Steps to reproduce:
1. When accessing any page of Mautic.
 
### Log errors: 
![screen shot 2018-09-18 at 16 12 36](https://user-images.githubusercontent.com/21362019/45710716-cec26880-bb5d-11e8-80e4-dd9ca5bf7027.png)

![screen shot 2018-09-18 at 16 16 13](https://user-images.githubusercontent.com/21362019/45710848-34aef000-bb5e-11e8-9a78-cf379f37fe92.png)

**Comment by julio899** [comment]
Ummmm...  similar  I'm Making a plugin  but  get the same error.
![image](https://user-images.githubusercontent.com/2575745/76152752-c9324880-6099-11ea-8153-75abd7a09917.png)
