### ISSUE TITLE
issue with importing a select multiple field that has a default value set

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6607]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is a problem if you import a select multiple field that has a default value set.
Means if a contact already has one or more value in this field and you make an import with this contact (without mapping this field), this field will be reseted with the default value. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 

### Steps to reproduce:
1. Create a select multiple field and assign a default value
![image](https://user-images.githubusercontent.com/31535432/45746674-17ccf800-bc04-11e8-8680-15b570930944.png)
2. Create a contact and add 2 values for example.
![image](https://user-images.githubusercontent.com/31535432/45746890-9aee4e00-bc04-11e8-8e2e-2fcc3c56c897.png)
![image](https://user-images.githubusercontent.com/31535432/45746797-59f63980-bc04-11e8-957b-e2e5bcd2d8f9.png)
3. Then import this contact with email and address1 for example
![image](https://user-images.githubusercontent.com/31535432/45746914-b22d3b80-bc04-11e8-94b2-89d7f3fb4488.png)
4. After the import, check the contact and see that the select multiple field has been reseted with the default value.
![image](https://user-images.githubusercontent.com/31535432/45746993-e4d73400-bc04-11e8-8030-099dcbaa595e.png)

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/6616

**Comment by johbuch** [comment]
works with #6616

**Comment by npracht** [comment]
Merged in 2.14.2
