### ISSUE TITLE
error 500 when a contact unsubscribes

### ISSUE THREAD

**Issue by fgauttron** [mautic/mautic#6609]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
when a contact wants to update or delete his channels, it generates an error 500. It is also impossible to modify channels with the adminstration interface.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 5.6.37-0+deb8u1

### Steps to reproduce:
1. 
2. 
 
### Log errors: 
mautic.ERROR: PHP Error - Argument 1 passed to Mautic\LeadBundle\Model\DoNotContact::__construct() must be an instance of Mautic\LeadBundle\Model\LeadModel, none given, called in /var/www/mautic/app/bundles/LeadBundle/Model/LeadModel.php on line 2558 and defined - in file /var/www/mautic/app/bundles/LeadBundle/Model/DoNotContact.php - at line 36

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi @fgauttron did you try to apply this PR which is included in 2.14.1 ?
https://github.com/mautic/mautic/pull/6441

Thanks !

**Comment by fgauttron** [comment]
Not yet. Is it a stable version ?

**Comment by npracht** [comment]
2.14.1 is gonna be release very very soon. The PR itself you can test it ;)

**Comment by fgauttron** [comment]
We updated with the version 2.14.1, but the problem remains. Any unsubscribing action generates an error 500.

Logs error : mautic.ERROR: PHP Error - Argument 1 passed to Mautic\LeadBundle\Model\DoNotContact::__construct() must be an instance of Mautic\LeadBundle\Model\LeadModel, none given, called in /var/www/mautic/app/bundles/LeadBundle/Model/LeadModel.php on line 2225 and defined - in file /var/www/mautic/app/bundles/LeadBundle/Model/DoNotContact.php - at line 36

**Comment by fgauttron** [comment]
We upgrade https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Model/LeadModel.php and fix the problem
