### ISSUE TITLE
New channel > email. 403 error

### ISSUE THREAD

**Issue by CodersBrothers** [mautic/mautic#6611]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  YES
| Feature request? | 
| Enhancement? | 

## Description:
Backend is sending a 403 error only when I try to create a email channel. Nothing is created, any alert of error in the frontend. Error visible only with console debug.

1. Phantom error. Bad UI/UX feedback. Bad experience.
2. Seems that this feature do something different from others features, that create a 403 error.

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.14.0
| PHP version | 5.4

### Steps to reproduce:
1. In Left menu, press in channels
2. Press in emails
3. Press in new
4. Fill the form
5. Press "Apply"

Nothing will be saved. All others featured works fine, this not.

### Log errors: 
Request URL: http://localhost/mautic/s/emails/new?mauticUserLastActive=1&mauticLastNotificationId=
Request Method: POST
Status Code: 403

**Comment by escopecz** [comment]
This must be a server configuration issue. Working for everyone else.

**Comment by biyadiayman** [comment]
I have this problem aswell did you manage to fix it ? @CodersBrothers

**Comment by mangumr** [comment]
I get this error when I try to add the save preferences button to the preference center.

**Comment by jalvarez2000** [comment]
I got the same error... Did you manage it on some way?

**Comment by Sourcefli** [comment]
same error here...

**Comment by Sourcefli** [comment]
Just fixed mine...note to all who swing through here...
Check your mod_security settings on your server, or have your hosting company whitelist the URI...which is /s/emails/new?mauticUserLastActive= ....
Initally it failed again after I ran the test. But, as with most Mautic issues, I cleared the cache (I tend to just delete the whole app/cache folder). Then rerun these commands from root dir...

php app/console cache:warmup --env=prod
php app/console cache:clear --env=prod 
php app/console mautic:assets:generate --env=prod

If you visit in browser right after running these and it gives an error, give it a min. Then do a hard refresh.
Hopefully you can login from there, create a new email, and it'll save&close it as normal.
