### ISSUE TITLE
Contacts is not updating immediately

### ISSUE THREAD

**Issue by cibyac** [mautic/mautic#6614]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
When i update new contacts in the 'Contacts', it takes 2 to 3 hrs for the contact to be available in 'Segments' and the 'Campaingns' are also triggered only after the above said 2 to 3 hrs. Has anyone come across the same issue? If yes, what can we do to get the contacts updated immediately?
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.29

### Log errors:

**Comment by YahiaBakour** [comment]
Check how often Cron Jobs are running. I have mine running every 5 min so my segments update after 5 min and my campaigns update after another 5 min.
