### ISSUE TITLE
Amazon SES Test Connection not working, it keeps loading instead of showing success!

### ISSUE THREAD

**Issue by Willwill90** [mautic/mautic#6618]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Enter Amazon SES info
2. Click Test Connection
 
### Log errors: 
 [Swift_TransportException]                                                                                                
 Connection could not be established with host email-smtp.us-east-1.amazonaws.com [Connection timed out #110]               
 Log data:                                                                                                                  
 ++ Starting Swift_Transport_EsmtpTransport                                                                    
 !! Connection could not be established with host email-smtp.us-east-1.amazonaws.com [Connection timed out #110] (code: 0)  

mautic:emails:send [--message-limit [MESSAGE-LIMIT]] [--time-limit [TIME-LIMIT]] [--do-not-clear] [--recover-timeout [RECOVER-TIMEOUT]] [--clear-timeout [CLEAR-TIMEOUT]] [-f|--force] [--bypass-locking] [-t|--timeout TIMEOUT] [-x|--lock_mode LOCK_MODE] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by taewookim** [comment]
i seem to have same issue

**Comment by yuanwei92** [comment]
Same issue here. I tried changing the default port to 587 from 2587 but still not working

http://staging.mautic.org/forum/topic/service-to-send-mail-through-amazon-ses-fixed-for-me

Log data:
Connection could not be established with host email-smtp.eu-west-1.amazonaws.com [Connection timed out #110] (code: 0)

**Comment by foxmedo** [comment]
any solution ?

**Comment by roco5** [comment]
I have this problem as well?  Any resolution?


```
Connection could not be established with host email-smtp.us-east-1.amazonaws.com [Connection refused #111] Log data: ++ Starting Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport !! Connection could not be established with host email-smtp.us-east-1.amazonaws.com [Connection refused #111] (code: 0)
++ Starting Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport !! Connection could not be established with host email-smtp.us-east-1.amazonaws.com [Connection refused #111] (code: 0)
```

**Comment by roco5** [comment]
In my case I have reverted to using the Other SMTP Server with SES and can get manual test emails to send through SES and land correctly.  

The problem I have is that campaign generated emails and the TEST EMAIL in the email configuration do not work.  My campaigns show that the emails have been sent, but they don't show up in SES or their destination.

Any Ideas?

**Comment by Dipranil** [comment]
@roco5 : The issue you have im facing too.please let me know if you find any solution

**Comment by Dipranil** [comment]
@roco5 : Below are the solution, It worked for me

go to > app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php
line 71 > parent::__construct($host, 2587, 'tls');

change it to > parent::__construct($host, 25, 'tls');

**Comment by verioussmith** [comment]
> @roco5 : Below are the solution, It worked for me
> 
> go to > app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php
> line 71 > parent::__construct($host, 2587, 'tls');
> 
> change it to > parent::__construct($host, 25, 'tls');

Is this just a stop gap measure?  I have tried to change the port from 2587 to 25  but I still do not get a positive result when testing the  connection.  I also don't feel comfortable editing a core file.

**Comment by alinkdaniel** [comment]
> In my case I have reverted to using the Other SMTP Server with SES 

I think this solution is actually fine. I got it to work using port 587.

**Comment by verioussmith** [comment]
> > In my case I have reverted to using the Other SMTP Server with SES
> 
> I think this solution is actually fine. I got it to work using port 587.

I ended up getting to work by opening an outgoing port 2587 on my server. From the Amazon Documentation for troubleshooting they say that sometimes it is a server Firewall.  In my case it definitely was the firewall blocking the outgoing port 2587

**Comment by kjwin** [comment]
> > In my case I have reverted to using the Other SMTP Server with SES
> 
> I think this solution is actually fine. I got it to work using port 587.

Using port 587 worked for me too. Thanks.

**Comment by Carlos-mb** [comment]
In my case it's working cofigured as Other SMTP provider connected to SES server. 

I'd like to know whats the benefit of configure it as SES. 

Thank you!

**Comment by kjwin** [comment]
> In my case it's working cofigured as Other SMTP provider connected to SES server.
> 
> I'd like to know whats the benefit of configure it as SES.
> 
> Thank you!

Check out this article [https://mauteam.org/mautic/mautic-users/mautic-email-which-email-provider-is-best-for-mautic](url)

**Comment by smbfission** [comment]
> 2587

how do i do that?

**Comment by virgilwashere** [comment]
@smbfission 

Edit file `app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php`

around line 71  `parent::__construct($host, 2587, 'tls');`

Then `console cache:clear`

**Comment by npracht** [comment]
Duplicate of https://github.com/mautic/mautic/issues/5873

**Comment by amireds** [comment]
> > > In my case I have reverted to using the Other SMTP Server with SES
> > 
> > 
> > I think this solution is actually fine. I got it to work using port 587.
> 
> I ended up getting to work by opening an outgoing port 2587 on my server. From the Amazon Documentation for troubleshooting they say that sometimes it is a server Firewall. In my case it definitely was the firewall blocking the outgoing port 2587

Hi, I already configured it, and the mail is going to my SES account, but I'm not getting the test emails in my verified email address.. Please what could be wrong?

**Comment by ramphy** [comment]
**PORT 2587 by default in AMAZON SES API** Check your Firewall

**Comment by michetk** [comment]
> @ roco5 : Abaixo está a solução, funcionou para mim
> 
> vá para> app / bundles / EmailBundle / Swiftmailer / Transport / AmazonTransport.php
> linha 71> parent :: __ construct ($ host, 2587, 'tls');
> 
> mude para> parent :: __ construct ($ host, 25, 'tls');

c é o cara vlw

**Comment by Abdullah-Ali-Abbasi** [comment]
I have tried everything and it still gives the same error:

Connection could not be established with host email-smtp.eu-west-1.amazonaws.com [Connection refused #111] Log data: ++ Starting Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport !! Connection could not be established with host email-smtp.eu-west-1.amazonaws.com [Connection refused #111] (code: 0)
++ Starting Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport

Even Changing the ports didnt work for me. 

Have taken the host on-board, for if they are blocking ports 25,467, 587, or 2587. But, there is still no clue.
Also, the firewall appears blocking the connection. 

I am wondering if its Amazon who is blocking the connection from these ports?  
Although, they say that port 2587 is open by default.

**Comment by gokhanaygun** [comment]
It's working. If your encryption=ssl and port 2465. Try that.

**Comment by rauldeheer** [comment]
@gokhanaygun Thanks. I highly suggest people to do what you suggested since that fixed it for me.
