### ISSUE TITLE
Mautic showing others landing pages

### ISSUE THREAD

**Issue by varunmarothia** [mautic/mautic#6619]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 

## Description:
Login as user-1.
User 1 has only permission to view/ edit/ create own landing pages
create landing Page
save and logout

Log in as user 2, with same permission as above.
go to landing page
you will see user-1 landing page also. 
Ideally user 2 can only view his/ her landing page, but how are they able to see others?

## If a bug:

| Q   | A
| --- | ---
| Mautic version - 2.14
| PHP version | 5.7

### Steps to reproduce:
Login as user-1.
User 1 has only permission to view/ edit/ create own landing pages
create landing Page
save and logout

Log in as user 2, with same permission as above.
go to landing page
you will see user-1 landing page also. 
Ideally user 2 can only view his/ her landing page, but how are they able to see others?

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by maycodiaz** [comment]
Hi, the issue is still in Mautic 3.x
