### ISSUE TITLE
Newly Created custom fields w/ Default not populating

### ISSUE THREAD

**Issue by rbagley0310** [mautic/mautic#6621]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N 
| Enhancement? | N

## Description:
I created a new custom field with a default value attached and when I sent and email to see how it would populate the value it failed to do so on an existing company. After saving the Company, it applied the value though.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.31

### Steps to reproduce:
1. Create a Contact.
2. Add a Custom field with default value.
3. Add Custom field to Email.
4. Send Email.

**Comment by escopecz** [comment]
This is a bit philosophical topic. It's default value of the field, so I'd think that when I create/edit a company it will fill in the default value if none exists. That's how it works now. I don't think it should add the default value to all existing companies.

Let's wait for other community members to see what makes more sense or if someone even see this as a problem.

**Comment by npracht** [comment]
Hi guys, IMO if a newly created custom field has a default value, it should be added to all the existing contact, because the default value by definition is not `NULL`, so no reason to keep it like that.

I'd suggestion to keep that for Mautic 3 @escopecz knowing that it is a behavioral change. It is not a BC break but "kinda" for the user habits.

**Comment by escopecz** [comment]
Another point of view to consider is technical. This would run an UPDATE query on all contacts. Identified and anonymous. It can be hundreds of millions of rows. Such query can take a while. So this will require to be processed on background.

**Comment by npracht** [comment]
One more reason to consider that for M3 ? :)

**Comment by RCheesley** [comment]
Not sure if we want to keep this one open or not @escopecz @npracht - any thoughts?

**Comment by npracht** [comment]
For me the way it is handled today is not clean. So it must stay an open topic for the day we work on data table structure (especially if we consider changing the way custom fields are managed one day).

**Comment by RCheesley** [comment]
I did see a PR which implemented updating custom fields in the background so hopefully when we merge that one we will be able to look into this, if it's still required!
