### ISSUE TITLE
Campaign keeps sending email even with VALID EMAIL filter

### ISSUE THREAD

**Issue by taewookim** [mautic/mautic#6625]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | 
| Enhancement? | 

## Description:
I have a campaign setup where i'm sending emails to a segment, but makes sure email is valid, like so

https://i.postimg.cc/C5Sdxssc/image.png

But i see mautic constantly trying to send scheduled drips

https://i.postimg.cc/XqsN7SJv/image.png

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.14
| PHP version |  7.03

### Steps to reproduce:
1. Create contact with no info (no email, nothing) using JS pageview
2. Add to segment with scheduled email drips
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Please test if https://github.com/mautic/mautic/pull/7413 fix this issue as well

**Comment by npracht** [comment]
Fixed when #7413 merged.
