### ISSUE TITLE
Custom Mautic Tokens

### ISSUE THREAD

**Issue by jrean** [mautic/mautic#6627]
What type of report is this:

| Q  | A

## Description:
Hi,
Is it possible to add custom Tokens to Mautic via a plugin?
I would like to add some extra logic while editing a page or an e-mail in "Code Mode".
I could not find anything helping or talking about it.

Can someone point me some resources/content to read?

Thanks for the help,

Best,

J.

**Comment by nethunter** [comment]
@jrean see the example on the right side of this page: https://developer.mautic.org/#extending-emails
It shows you how to do exactly this :)
