### ISSUE TITLE
SQL error when segment filters a new date company field

### ISSUE THREAD

**Issue by toledomarcela** [mautic/mautic#6628]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | y
| Feature request? | 
| Enhancement? | 

## Description:
When creating a new date company field and using it in a segment occurs a SQL error. It doesn't find the field even if the field was create at the right table in the DB.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.1.20

### Steps to reproduce:
1. Create a new Date company field
2. Create a segment wich filters this field
 
### Log errors: 

[Doctrine\DBAL\Exception\InvalidFieldNameException]
  An exception occurred while executing 'SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, GxOKULAw.lead_
  id AS GxOKULAw_lead_id FROM leads l LEFT JOIN companies_leads abZhqdvr ON abZhqdvr.lead_id = l.id LEFT JOIN lead_lists_leads GxOKULAw ON GxOKULAw.lead_id = l.id and (GxOKULAw.leadlist_
  id = 30) LEFT JOIN companies zQWoOjYM ON zQWoOjYM.id = abZhqdvr.company_id WHERE ((zQWoOjYM.companyemail IS NOT NULL) AND (zQWoOjYM.companyemail <> '')) AND (l.certificateexpiration <=
   ?) AND (GxOKULAw.lead_id IS NULL)) sss' with params ["2018-10-06"]:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.certificateexpiration' in 'where clause'

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.certificateexpiration' in 'where clause'

  [PDOException]
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'l.certificateexpiration' in 'where clause'

mautic:segments:update [-b|--batch-limit [BATCH-LIMIT]] [-m|--max-contacts [MAX-CONTACTS]] [-i|--list-id [LIST-ID]] [-f|--force] [--bypass-locking] [-t|--timeout TIMEOUT] [-x|--lock_mode LOCK_MODE] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
