### ISSUE TITLE
Dashboard / Top Lists is not keeping in time with the Segments.

### ISSUE THREAD

**Issue by iwantaspeaker** [mautic/mautic#6630]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | 
| Enhancement? | 

## Description:
Dashboard / Top Lists is not keeping in time with the Segments.

This is the image of the 'Top Lists' Page: https://www.dropbox.com/s/q3spslt14s1hwe8/Screenshot%20%2861%29.png?dl=0

This is the Images of the Segments Page:
https://www.dropbox.com/s/8qupc39o2nlo2mz/Screenshot%20%2863%29.png?dl=0

As you can see the numbers are different.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 5.6.37
--

### Steps to reproduce:
1. 
2. 
 
### Log errors: 
NO ERRORS
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
There may be 2 reasons:
1. The results of the dashboard widgets are cached. 10 minutes by default. You can turn that off in the Mautic's configuration.
2. The dashboard widgets show only data for certain date range.

Can you confirm it's not caused by those?
