### ISSUE TITLE
After entering the contacts, pagination does not appear

### ISSUE THREAD

**Issue by davemil** [mautic/mautic#6631]
Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | yes
| Feature request? | 
| Enhancement? | 

## Description:
After entering the contacts, pagination does not appear. Only message: The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.4.0, 2.4.1
| PHP version | 7.2.9

### Steps to reproduce:
1. Login to Mautic
2. Open Contacts
 
### Log errors: 

 mautic.ERROR: InvalidArgumentException: Unable to choose a translation for "one: %count% element|some: %count% elementy" with locale "pl_PL" for value "111". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples"). - in file /vendor/symfony/translation/MessageSelector.php - at line 81

**Comment by escopecz** [comment]
This sounds like a bug in the PL language. Could you switch to English and see if the pagination works there for you?

**Comment by escopecz** [comment]
Thanks for the check. Languages are not part of this repository. They are managed by the community at https://www.transifex.com/mautic/mautic/.

Please raise the issue there. Or even fix it yourself as anyone can translate.
