### ISSUE TITLE
Mautic Latest version - embedded forms won't work anymore

### ISSUE THREAD

**Issue by ecoitsolutions** [mautic/mautic#6632]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
After upgrading to lateststable version, forms are not working anymore. Once you submit an embedded form, you will get an error message like this appended to the URL and nothing happens:
"?mauticError=Errors%3A<br%20%2F><ol><li>Array<%2Fli><%2Fol>#proiect_no"

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.14.1
| PHP version | 7.0.30

### Steps to reproduce:
1.  Update to latest version, ccheck database migrations and so on
2.  Use existing or new forms embedded into website, checked both with automatic code or manually.
3.  No form will ever work either way. Previewing form inside mautic works as expected, the problems is only when embedded.
4. Before updating, all forms worked correctly for months.
 
### Log errors: 

[2018-09-23 17:34:57] mautic.NOTICE: PHP Notice - Array to string conversion - in file /app/bundles/FormBundle/Controller/PublicController.php - at line 111 [] []

**Comment by dhmusman** [comment]
Same issue forms and API sync are not working anymore after update the mautic.

**Comment by dsp76** [comment]
it seems to be related to forms with phone number fields. when I enter them with correct international formatting like +4935100000000 submit works, but if I enter the national way 035100000000 it breaks with the mentioned errors.

**Comment by jpilarzeck** [comment]
I have this problem, too. But only first name, last name and email and a checkbox as fields. No errors in browser console.

**Comment by kuzmany** [comment]
I don't think this issue is related to https://github.com/mautic/mautic/pull/6645

**Comment by jpilarzeck** [comment]
more information: think this is maybe related to https://github.com/mautic/mautic-wordpress/issues/83
If we use the automatic version of the form integration, then no validation errors are shown. If we use the manual version everything is working fine.

**Comment by dsp76** [comment]
> 
> 
> I don't think this issue is related to #6645

At least it solved my form submission issue. It had the same symptoms, like described here. After applying the changes from the PR, I was able to submit my embedded forms again.

**Comment by scottybo** [comment]
No doubt I'm going to come across this issue again in the future and need my own help to solve the problem.

It's likely a CORS issue and possibly a site URL configuration issue.

In the Mautic configuration, make sure your site URL doesn't have `index.php` at the end, and also make sure that (further on down the page) if you have CORS enabled you've added your website URL as an allowed domain.

**Comment by imankitshah** [comment]
Hi Guys,
If the error code 500 then this small video might help you solve the problem.

[**Cannot Create a New Form in Mautic | Problem Solved**](https://youtu.be/L0aY5PP1WAk)
