### ISSUE TITLE
Error, NO Validate as internationally-standardized format 

### ISSUE THREAD

**Issue by slaidel** [mautic/mautic#6633]
What type of report is this: 
A form that has a telephone or mobile field.
Even setting as NO Validate as internationally-standardized format.
The form shows the warning

_The phone number is not in internationally-standardized E.164 format. E.164 numbers can have a maximum of fifteen digits and are usually written as follows: [+] [country code] [subscriber number including area code]._

Even without me wanting to try to validate

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.14.1
| PHP version | 7.0.16

### Steps to reproduce:
Any form with telephone or mobile.
Even though NO Validate as internationally-standardized format
The mautic tries to validate.

**Comment by johbuch** [comment]
i have the same issue. The CONTACT field is a text type but the FORM field is phone type

**Comment by kuzmany** [comment]
What about this fix? https://github.com/mautic/mautic/issues/6633
