### ISSUE TITLE
Can't access campaign and open chanel emails, even already update to the latest version

### ISSUE THREAD

**Issue by Arifady** [mautic/mautic#6634]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes, i think is bug. i can't open my chanel email and access campaign
| Feature request? | 
| Enhancement? | 

## Description:
i Can't access campaign and open chanel emails, even already update to the latest version. There no action when i click email or campaign, the page won't to open. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Britt0404** [comment]
Hi Arifady 

I am having the same problem after the update, were you able to fix it?

**Comment by ekatronik** [comment]
Yes me too
i can open campaign page and email page after update from 2.13.0 to 14.1
anybody have fix it ..?

**Comment by Britt0404** [comment]
I just restored my back up, sorry I can't be of anymore help

**Comment by escopecz** [comment]
It's impossible to help without the error message. Please follow https://www.mautic.org/docs/en/tips/troubleshooting.html and provide it.

**Comment by escopecz** [comment]
It looks like this issue is abandoned. Will close it. If you manage to get the error logs please post them as a new comment. Will re-open after.
