### ISSUE TITLE
Errors for mysqli DB driver

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#6635]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

[//]: # ( Invisible comment: Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead. )

[//]: # ( asdf
IIIIIIIIIIIIIIIIII
sfds
sfds
)

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
This issue is result of PR https://github.com/mautic/mautic/pull/6574 where I thought the fix is simple, but it turned out to be broken query for `mysqli` DB driver. Quick fix is to use recommended `pdo_mysql` driver. So I can see 2 solutions for this:

1. Do not support `mysqli` driver anymore. Which will be a BC break for Mautic 2.
2. Fix the queries using `bindParam` and `bindValue` methods which work only for PDO.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0

### Steps to reproduce:
1. Not sure, but this method is causing the trouble: https://github.com/mautic/mautic/blob/master/app/bundles/CampaignBundle/Entity/LeadEventLogRepository.php#L545
 
### Log errors: 

```
Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'REPLACE INTO mau8g_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mau8g_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mau8g_campaign_lead_event_log ' at line 2 (uncaught exception) at /home/clientsiwanta/public_html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 90 while running console command `mautic:segments:update` [] []
```

**Comment by manolomontiel** [comment]
Hello, I have this error:  Can you tell me how to solve it?

[2019-05-29 05:04:04] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO maudzv7_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from maudzv7_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':dateAdded as date_added, :message as reason from maudzv7_campaign_lead_event_lo' at line 2 [] []

**Comment by pierrederuel** [comment]
Hi @manolomontiel , I got the same error. Did you find something? Thanks

**Comment by miamicityman** [comment]
I'm seeing similar error regarding Mysql syntax.

>mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO mktng_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from mktng_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':dateAdded as date_added, :message as reason from mktng_campaign_lead_event_log ' 

Is the fix changing the 'db_driver' => 'mysqli', to pdo_mysql ?

**Comment by RCheesley** [comment]
Closing as I believe this has been addressed with Mautic 3.x
