### ISSUE TITLE
Does Mautic work?

### ISSUE THREAD

**Issue by Carlos-mb** [mautic/mautic#6640]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No 
| Feature request? | 
| Enhancement? | 

## Description:
I have installed Mautic 12 days ago. 

In this time I have been +50 hours resolving internal errors, fixing updating errors, manually repaiding databases, asking for help in github, reading documentation...

I really thank all the support here and I have a last question: Does Mautic work?

Now, there is a bug that prevent email to be sent in campaings... so... This is an email marketing software that can't send emails in a campaign. 

What sense does it have?

I loved the idea and I'd be happy paying for this software but.. should I keep trying to make it work?

Does anyone have a real mautinc instance working? Sending emails without internal errors, according to a workflow and tracking emails? 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hello @Carlos-mb we run >300 instances for our customers. Mautic inc. probably over thousands free or paying.
**Mautic is working**.

Best,

**Comment by Carlos-mb** [comment]
Maybe I'm lokking very critical but **I really want to make this work for me** and I'm very frustrated.

Using the stable version: 

Until yesterday, users got an internal error 500 when try to confirm subscription. And it was a known bug. This is part of the core funcionality, it's not a secundary funcionality. I can't say an email marketing software is working if it has this issue.

If you do a fresh install it fails to update because upgrade proccess try to delete a unexistent FK, all the next proccesses are not executed and database became out of date. Have I to say how important is this?

There is a SQL syntax error if you don't change the SQL driver. I had to read a lot to find a person giving the solution. 

People is reporting that emails are not beind send in their campaings whith no reason. That's also my case. An email marketing tool is not working if it's not sending emails.

So, What does someone need to have or to do to make this work?

Should I have a crew of programers?

I'd like your help to understand. 

For instance... Are this issues fixed in hosted solutions? It could work for me, Does mautic.com offer a hosted solution without these issues?

**Comment by spencerthayer** [comment]
@Carlos-mb did you ever get Mautic working? Seems like it's just not a viable solution for enterprise.

**Comment by Carlos-mb** [comment]
I'm using the v2.16.3 because the update failed and I don't want to touch anything. 

Current version es 3.3.2

According to my experience, it's too buggy. I have expend a lot of time to make it work and I prefer to don't modify anything in order to keep it working.. until it stops working. 

Probably I'll do a fresh installation sometime... because it's free and selfhosted. 

I don't recommend it but...It is the least bad option.

Regards,
Carlos.
