### ISSUE TITLE
Number of events returned greater than the limit /contacts/activity API endpoint

### ISSUE THREAD

**Issue by tylerfoulkes** [mautic/mautic#6643]
| Q  | A
| ---| ---
| Bug report? | x
| Feature request? | 
| Enhancement? | 

When querying the /contacts/activity endpoint in Mautic with a specified limit I seem to get back 3 times as many events than the limit specified.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.1

### Steps to reproduce:
1. Query the following API endpoint /contacts/activity?limit=100 using Postman or whatever REST client you want.
2. 300 events are returned but the limit says 100.
 
### Log errors: 
No log errors.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
