### ISSUE TITLE
I can't open my pending emails and access campaign on new version

### ISSUE THREAD

**Issue by Britt0404** [mautic/mautic#6646]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  

I can't open my email and access my campaigns
--

| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Closing this ticket for lack of information. There is no way anyone could help you without filling in the issue template. Also look at https://www.mautic.org/docs/en/tips/troubleshooting.html
