### ISSUE TITLE
New install, cannot apply new settings, make new landing pages or new emails.  The Cancel, Save and Close and Apply buttons become inactive and I get a 403 forbidden error.  I'm getting ready to give up on Mautic.

### ISSUE THREAD

**Issue by markertim** [mautic/mautic#6648]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dsp76** [comment]
Hi @markertim you might want to put a little more effort into this bug description. It has no details at all. How should anyone be able to understand your installation, or even be able to recreate it?

It might be an installation with incorrect ownership / group / file access settings and rather be a support case which can be better handled in Slacks Mautic Channel. You might also look into inofficial Mautic support groups with many professionals out there helping you out with getting your initial installation setup correctly.

**Comment by escopecz** [comment]
Yep, sounds like bad file permissions. Since there is no additional info I'm closing this.
