### ISSUE TITLE
MQL :  A better way of creating segment filters

### ISSUE THREAD

**Issue by sibben** [mautic/mautic#6653]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | Y
| Enhancement? | 

## Description:
I think we need a better way to create filters for segments. Now it's too hard to create multiple AND and OR statements.
Let's say you want to filter this
```
Points > 10 AND (CustomField >20   OR  CustomField = Empty)  
```

As far as I know,  in Mautic this works like
```
Points > 10  AND CustomField >20  
OR
Points > 10  AND CustomField = Empty
```

This is a simple example but it would be great if we could make filters like this example below
```
Points > 10 AND (CustomField >20   OR  CustomField = Empty)  AND ((OtherField=Yes OR OtherField=Empty) OR SomeField=yes)
```

It would be great if we had MQL(Mautic Query Language)  something like JQL  in Jira 
![jqlautocomplete](https://user-images.githubusercontent.com/4610714/46200518-2a38e700-c312-11e8-8dfa-4998b0e17ec2.gif)

**Comment by RCheesley** [comment]
I'm going to close this down as it seems to be suggesting a feature that is already there in the search queries already available.
