### ISSUE TITLE
(Enhancement) Email transport - Support external queue protocol (i.e RabbitMQ) in addition to internal filesystem queue

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#6658]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:

When large volumes of emails are to be sent, it's recommended to not use "immediate delivery", but to use a queue where email are processed asynchronously. Mautic handles that with a "queue" in an internal "spool" folder and a cron `php /path/to/mautic/app/console mautic:emails:send` set to run at regular intervals.

Adding to that the possibility to use an external queue protocol such as RabbitMQ would offer several advantages:

- Decoupling of hardware resources since the message queue/consumer(s) are on different servers.
- Possibility to have queue consumers "listen" incoming queued messages and process them as they comes, rather than relying on scheduled processing with cron job.
- Possibility to multiply and parallelize queue workers to ramp up email delivery speed rate. 1 queue, several consumers.
- Possibility to monitor the queue more precisely

Mautic currently supports RabbitMQ, but only for email hits and page hits.

**Comment by clp56** [comment]
This features will also help for docker deployment, for now, data need to persist on an external filesystem.

**Comment by oytuntez** [comment]
Wow, so this RabbitMQ integration on docs is quite misleading. I would never imagine email sending is not actually using RabbitMQ.

**Comment by oytuntez** [comment]
If you can write up a quick guide for more comprehensive RQM integration, we can start working on this.

We are definitely going to use ONLY RabbitMQ to process email sends, so that Mautic can behave as a service listening to our central RabbitMQ structure.

Can you lead us on this?

**Comment by AlbanL74fr** [comment]
Hi @oytuntez, I am glad to see this feature request is having some traction. I also think it would be great to have it in Mautic, for better scalability and reliability. 
Have you obtained the information you needed from the Mautic core team regarding how to make it work?

**Comment by RCheesley** [comment]
@oytuntez did you get anywhere with this? Can we close the issue down if it's resolved with a plugin?

**Comment by jordan8037310** [comment]
@oytuntez - would love to see that plugin if you can open source it?

@RCheesley - I think this is still a valid feature request for Mautic Core and something we may consider taking up if there isn't an open source plugin solution.

**Comment by mabumusa1** [comment]
@jordan8037310 I wrote a plug-in for AWS SQS, do you want to work on this to bring it as a Mautic core feature?

**Comment by jordan8037310** [comment]
@mabumusa1 - A Plugin for Mautic 2 or 3? I'd love to take a look at it. I'm not sure about bringing *it* into Mautic core. Instead I think there should be an effort to support _any_ queue service and designate SQS, RabbitMQ, etc.

**Comment by sanchand** [comment]
Is anyone able to use  RabbitMQ queue to Mautic 3.x? If yes then can someone share steps or configurations?

**Comment by magician7** [comment]
I'm also looking for solution for sending mails thru RabbitMQ mailer transport. Any suggestions?

**Comment by truong-hua** [comment]
@oytuntez can you share the plugin?
