### ISSUE TITLE
Form validation FAILED

### ISSUE THREAD

**Issue by phenixiim** [mautic/mautic#6659]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

Bug report

## Description:
Form error not shown after submitting the form and the form is reseted back to default state.
<img width="744" alt="image" src="https://user-images.githubusercontent.com/17194496/46249210-96f0d600-c425-11e8-8877-ac5548d61d87.png">

## If a bug:

| Q   | A
| --- | ---
mautic 2.14.1
php 7.0.32

### Steps to reproduce:
1. create a form and save with at least one required input with a fail message
2. try to submit form without filling any field

**Comment by npracht** [comment]
Please try https://github.com/mautic/mautic/pull/6665
