### ISSUE TITLE
mautic-form.js not loaded by generate.js with insertAdjacentHTMLScript 

### ISSUE THREAD

**Issue by Kuuak** [mautic/mautic#6660]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | x
| Feature request? |  
| Enhancement? | 

## Description:
Fix #6432 makes the **mautic-form.js** not load.

When performing a `document.write` the script tag written is directly intepreted by the browser. 
In the other end, `insertAdjacentHTML` does not execute any _<script>_.

This difference make the **mautic-form.js** not being loaded.

A little demonstration of the script inserted by `insertAdjacentHTML` not being executed https://jsfiddle.net/c3nyudkL/3/

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | PHP 7.1.22 (cli) (built: Sep 15 2018 03:35:24)

### Steps to reproduce:
1. Create a form
2. Embed the Form HTML with the automatic option 
3. Render the HTML page where the form should be rendered
 
### Log errors: 

No error on a fresh install with Docker

**Comment by npracht** [comment]
Please try https://github.com/mautic/mautic/pull/6665

**Comment by zaharovrd** [comment]
please reopen in  v4.1.2
