### ISSUE TITLE
Purge Twig Cache option for Theme Building...

### ISSUE THREAD

**Issue by dirtroof** [mautic/mautic#6661]
What type of report is this:

| Enhancement? | 

## Description:
I really like to develop in-browser as much as possible. However, this is like going east to get west in Mautic as I develop a custom theme. I've tried every trick I know of and that google search revealed, and have found it impossible to empty TWIG cache efficiently.  The only method I've found to work is to switch themes (and loose all content in the process), then switch back to the theme I'm developing. This works, but is really less than ideal. I can deal with it as I'm making a theme, but lets say 6 months down the road after the theme has been in use, we find a bug or need to reformat our code in the page.html.twig file. For any Landing Pages I've made in Mautic that use that theme, I've basically got to go back and redo every one of them for the update to apply to them b/c I'd have to apply a new theme, loose all content, apply custom theme again. At that point, the theme updates will apply but at the cost of loosing all my content. There has to be a better way than this.
I'm recommending a "Purge Twig Cache" option for all Landing Page and Email pages—maybe a button in the builder?
Something that can purge that Twig cache and make Theme Updates take effect without having to loose all content to do so.
I'm baffled by how it's working now anyway b/c I cannot figure out any other way to purge the Twig cache. I deleted the app/cache folder, still it doesn't update. Even went directly into the database Pages table and deleted the contents of the 'custom_html' column. That did nothing.
So I propose the option to "Purge Twig Cache" so theme changes can take effect without losing content.

**Comment by dirtroof** [comment]
Ok, I managed to get theme updates to apply by directly updating in the Database—>Pages Table—>custom_html column. Then clearing the cache via SSH. Less than ideal. A button in the builder that could force Mautic to recompile the HTML in the custom_html field would be ideal.

**Comment by escopecz** [comment]
The problem is not the Twig cache. Here is how the email/page builder works:
1. When you create a page you can select a theme.
2. Once you select a theme the HTML code is generated from the theme. Since then it lives only as static HTML code.

The reason is that the builder allows users to move blocks around, add new and delete others. If it would be still based on a twig template this wouldn't be possible.

If you clear the custom_html column you'll lose the content of the pages/emails. Do not try this on a production Mautic!
