### ISSUE TITLE
Form page breaks behaving erratically unless form code is inlined in HTML

### ISSUE THREAD

**Issue by yrammos** [mautic/mautic#6662]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:

Context: I have a long form which carries three __page breaks__ and is written directly in code mode. Most of the fields are not to be stored in the Mautic DB but a few of them are. Likewise, a small number of them are allowed to be auto-filled for return visitors, others not. A subset of these auto-filled fields are requested to be hidden from the form, others not. 

The problem: Unfortunately, on every browser that I've tested (mac and iOS, Safari, Firefox, Chrome, ...) the form often rendered without page breaks and with some of the inter-break sections entirely missing. Whenever that happens, the submit button fails to post data. Inspecting the code in the browser shows an erratic combination of `display: none` and `display: block` CSS in the relevant code lines. It "feels" a little bit like a JavaScript mounting issue, but there are no errors in the browser console whatsoever.

Refreshing the page (both "soft" and "hard" cache-deleting) refresh typically results in a different section missing each time, or none at all, but in any case I very rarely get to see all the page breaks and buttons as they should be rendered...

... UNLESS...

1. What did help (not entirely) was placing the form in a Mautic landing page with a `{form=1}`-type token and reloading the form in incognito mode, whereby the page breaks worked, but only the first time I loaded the page (reloading it _in the same browser session_ reproduced the error thereafter). It makes some but not much difference whether I am logged on to Mautic or not: if I am _not_ logged in, then the probability of the error is lower, but still very high. The same landing page, which contains the form token, displays the same error (no page breaks) consistently if I am logged on to Mautic.

2. The second and most reliable way to avoid the error is striking. Here's the sequence:

- "View Source" on any browser rendering the form-containing landing page.
- Copy-paste the landing page code (which obviously does not contain `{form=1}` but actual JavaScript and HTML, into a new `.html` file.
- Place that new `html` file onto any server.
- Load that file from my browser.

My gut feelings is that this is a cookie or caching issue, but as I said, it is cross-browser, so we cannot blame it on them.

Bingo — everything then seem to work.

__UPDATE:__ Actually, not quite everything works, as it turns out: refreshes of that page still fails to render the page breaks consistently, but the frequency of failure is significantly lower.

Among the most puzzling bugs(?) I've ever encountered.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | PHP Version 7.0.32-0ubuntu0.16.04.1

 
### Log errors: 

None.

**Comment by escopecz** [comment]
Fixed by https://github.com/mautic/mautic/pull/6665. Ready to test.

**Comment by yrammos** [comment]
I rushed to rejoice, unfortunately. The issue appears only partially solved. Refreshing the browser page, especially, presents the same problems as described above (elided page breaks).

**Comment by escopecz** [comment]
Can you please post screenshots?

**Comment by yrammos** [comment]
Sorry for the late response. Here are two relevant screenshots (necessarily narrow-view for confidentiality reasons, but you'll get the idea).

The top image shows the page break appropriately rendered.

<img width="332" alt="screen shot 2018-10-21 at 11 55 10 pm" src="https://user-images.githubusercontent.com/1519337/47272353-05d8cf00-d58d-11e8-9d0d-8868c5c68833.png">

Refreshing the page (command-R) elides the page break and merges the form segments:

<img width="476" alt="screen shot 2018-10-21 at 11 55 23 pm" src="https://user-images.githubusercontent.com/1519337/47272352-05d8cf00-d58d-11e8-960f-b2bc6ce47e03.png">

Refreshing is one of several ways to reproduce the error (albeit the most probably one, in my experience). Sometimes I get the broken page straight away on the first page serve. I am not able to discern a cause-effect pattern otherwise.

**Comment by yrammos** [comment]
Update: the bug is *not* reproducible if I reload the page "from the origin" (i.e. reloading all resources and circumnavigating any cached content). Reloading the page ordinarily reproduces the error with 100% certainty, at least on my browsers. Judging by the looks (never a good idea), this looks like a possible script timing issue. No errors are reported on the browser side.

**Comment by yrammos** [comment]
It's getting worse, actually: in the absence of any "next page" buttons, clicking on the submit button transmits no data and _disables the button entirely_, rendering the form useless and the effectively blocking the lead's progression through the campaign.

**Comment by yrammos** [comment]
Yes, the reproduction scenarios could well be identical.

**Comment by yrammos** [comment]
Will look for a chance to try out the PR but no earlier than Friday or Saturday, I’m afraid.

**Comment by yrammos** [comment]
@alanhartless I tested this, finally, by a patching a 2.14.2 installation. Unfortunately the issue persists. Reloading the form elides one or more of the page breaks unpredictably. Hard-reloading (Cmd-Alt-R on Safari, Cmd-Shift-R on Chrome) increases the likelihood of correct rendering but not significantly. 

I think the "ready to test” tag should be removed.

**Comment by RCheesley** [comment]
@yrammos do you continue to experience a problem with this on your forms using 2.15.3?

**Comment by yrammos** [comment]
@RCheesley, my most recent post above reflects my last experience before deleting the form from my server. I have nothing more to add, I am afraid.
