### ISSUE TITLE
MariaDB 10.2.18 on PHP7 memory leak

### ISSUE THREAD

**Issue by tonypartridge** [mautic/mautic#6663]
When using Mautic 2.14.1 (And prior) it will not run full stop if using Litespeed web server with MariaDB  10.2.18 on PHP7. 

It has constant error on all pages, with a memory limit hit php error;
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 2957696056 bytes) in /home/user_account/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php on line 179

**Comment by dongilbert** [comment]
Does this _only_ happen when using the exact setup of MariaDB on a Lightspeed web server? What happens if you use Nginx or Apache?

**Comment by tonypartridge** [comment]
Yep, I’ve got two servers. Originally I assumed it was just lack of PHP7 support. But the only difference on these two servers is the MariaDB version.

**Comment by dongilbert** [comment]
Ok, thanks.

Some preliminary research looks like this is a problem specifically with MariaDB 10.2.x - https://jira.mariadb.org/browse/MDEV-15344?focusedCommentId=116179&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-116179

This doesn't seem to be a Mautic specific issue.

**Comment by tonypartridge** [comment]
Interesting, however there is 16GB of Ram with 6gb in use on this server so it’s not exceeding the limit of ram available. And it’s a fresh Mautic install exceeding 128MB of ram 🧐.

I’ll try and find time to setup a container and emulate it locally and debug Mautic since I have around 100 Joomla/Wordpress sites working without issue on the same server.

Many thanks

**Comment by tonypartridge** [comment]
Why has this been closed?

**Comment by dongilbert** [comment]
If you can replicate the environment in Docker it would make it easier to debug.

**Comment by dongilbert** [comment]
@tonypartridge Can't speak for @npracht (he's the one who closed it), but I would say it's likely because it doesn't seem to be a Mautic issue given that MariaDB has stated that there are memory leak issues in 10.2.x, and you have the exact same setup (except for MariaDB version) running fine on another server.
