### ISSUE TITLE
(BUG) "Submit" spinner loads endlessly after submission of form integrated in third-party page, even though Mautic saves the form results

### ISSUE THREAD

**Issue by AlbanL74fr** [mautic/mautic#6664]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:

Forms submission doesn't end properly. This behaviour doesn't happen when the submission happens from the form preview page, only if the integration code is used.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.1.22

### Steps to reproduce:
1. Create a form with few fields (contact mapping, or not)
2. Use the integration code ```<script type="text/javascript" src="//your-mautic.com/form/generate.js?id={YOUR_FORM_ID_HERE}"></script>``` to insert the form in a third-party page
3. Try complete and submit the form

Actual result: Spinner never stops loading, even though the results have been submitted and can be viewed in the form results. Rebuilding form cache didn't help solve the issue.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dongilbert** [comment]
This is generally caused by bad CORS settings. Check your console for errors about CORS or `Access-Control-Allow-Origin`. If you have that error, add the domain where the form is embedded into your Allowed Domains in the `Configuration > System Settings > CORS Settings`

**Comment by AlbanL74fr** [comment]
Hi @dongilbert , thanks for replying. I have checked the settings CORS, and all is already set properly, exactly like it was before updating to 2.14.1, when this issue didn't exist.

**Comment by escopecz** [comment]
Check if https://github.com/mautic/mautic/pull/6665 resolves the issue.
