### ISSUE TITLE
ability to disable public link to email preview

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#6668]
| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

## Description:
The public link of an email is publicly accessible and is not possible to disable.
It would be great to have a public link accessible only if logged to mautic. And a public link accessible to everyone but that you can enable/disable.

**Comment by dongilbert** [comment]
Context: https://github.com/mautic/mautic/commit/e1739a753023b85c0ddb108a67fb32328c6fa1aa

Was moved to publicly accessible in 2015, but in my opinion you're right in that it should be able to be toggled on a per email basis.

**Comment by dongilbert** [comment]
May want to bring it up for discussion in #dev slack
