### ISSUE TITLE
Unable to Push contact to Integration (SugarCRM)

### ISSUE THREAD

**Issue by LEAP-nishit** [mautic/mautic#6672]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? |  N
| Enhancement? |  N

## Description:
Mautic is setup to push/pull contacts with SugarCRM, The plugin appears to work when using the command line `mautic:integration:fetchleads --integration=Sugarcrm`. However, when trying to add _Push contact to integration_ to a Form action, the popup does not have the option to select the Integration, though we know it is setup and working. The pop is shown here

![untitled](https://user-images.githubusercontent.com/9854372/46387334-9dbf6780-c709-11e8-833a-a9e07e00291c.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.14.1 
| PHP version | PHP 7.0.32

### Steps to reproduce:
1. Setup SugarCRM Integration as per documentation
2. Verify leads sync
3. Create a form with action to push to integration
 
### Log errors: 
No errors seen. 

Issue seem to be php version specific.

**Comment by npracht** [comment]
Hello,

I cannot reproduce. Could you share a screenshot of your plugin config ?
Also when you open that empty drop down list, did you open the browser console to see if there is a JS error or anything ?

Thanks !

**Comment by LEAP-nishit** [comment]
@npracht Just checked the Browser Console. No JS errors/warnings/ etc. 

Also regarding the reproducibility, when I clone the database and html folder to another computer it works. The only difference is OS, the production server (on that is not working) is  Ubuntu 16.04 LTS and the test environment (where it is working) is Ubuntu 18.04 LTS. 

The screenshorts as requested. The contact and account mapping are truncated because they are long. 

![1](https://user-images.githubusercontent.com/9854372/46400243-46d38580-c73d-11e8-9725-2ca0cda681ff.png)
![2](https://user-images.githubusercontent.com/9854372/46400245-46d38580-c73d-11e8-81f2-e4764e212ab0.png)
![3](https://user-images.githubusercontent.com/9854372/46400246-476c1c00-c73d-11e8-96b4-18c64f87dbe4.png)
![4](https://user-images.githubusercontent.com/9854372/46400248-476c1c00-c73d-11e8-9903-2dea97713e66.png)

**Comment by npracht** [comment]
In the feature tab, the "Trigger action push contact to integration" must be enabled !

**Comment by LEAP-nishit** [comment]
@npracht , yes that addressed it. I was sure I tired it without. One of the reason we unticked it was we only want Form Submission Leads to be pushed to CRM, but having only Forms in the _Events to Include_ also pushes web activity etc.

**Comment by npracht** [comment]
Not sure to understand the conclusion ---> once checked, it works?
