### ISSUE TITLE
Automatic CSS inliner

### ISSUE THREAD

**Issue by Flavio1998** [mautic/mautic#6676]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | X
| Enhancement? | 

## Description:
It would be nice to have a function which takes the CSS rules from the <style> block and rewrites them inline with the elements. To avoid having styling issues with MS Outlook on Windows. 

Original description:
If you create an email with the builder and then send it, it will not display correctly in MS Outlook on Windows. Images are not correctly scaled according to the CSS rules.
The problem is that MS Outlook ignores the <style> block. If the style instructions are written inline within the elements, the scaling of images works. A tool that does this automatically is available here: https://templates.mailchimp.com/resources/inline-css/.
The new email is displayed correctly in MS Outlook.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0.32-0ubuntu0.16.04.1

### Steps to reproduce:
1. Create an email with the builder
2. Put in some images and scale them with the options of the builder
3. Send the email
4. Open the email in Microsoft Outlook on Windows
5. Look at the missaligned and unscaled images 
--------------------------------
1. Create an email with the builder
2. Put in some images and scale them with the options of the builder
3. Go to "code mode" and replace the content with the transformed code from https://templates.mailchimp.com/resources/inline-css/
4. Send the email
5. Open the email in Microsoft Outlook on Windows
6. Look at the correctly aligned an scaled images
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Shirkit** [comment]
I think that depends on the Theme you are using. I created a theme myself that uses no <style> blocks, only inline styles.

**Comment by Flavio1998** [comment]
Yes, that is a good point. Then this bug report should be a feature request for automatically setting style rules inline.

**Comment by dsp76** [comment]
Mautic E-Mail Editor is based on Froala afaik. 
You would probably need to open this feature request here: https://github.com/froala/wysiwyg-editor/issues

**Comment by Flavio1998** [comment]
Not necessarily. To have a workaround for my issue, I wrote a simple python script which takes the content of the custom_html field from an email in the database and pass that to the transform function of this project: [premailer - Github](https://github.com/peterbe/premailer). After that I save the new inlined html as an other email. 
I think it would be possible for Mautic to have such a function too. Although I think it would be better if it's written in PHP.

**Comment by escopecz** [comment]
There were already discussions about this. We've decided to modify the HTML source as little as possible as it always leads to confusion.
