### ISSUE TITLE
Some customers are not being added to segment

### ISSUE THREAD

**Issue by Carlos-mb** [mautic/mautic#6677]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
There are a few customers that are not being added to segments when they should. 
If I chang the segments manually in the "preferences" tab of customer, the customer is correctly proccesed after update.

(Free free to correct my English if needed)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0.32

### Steps to reproduce:
Create a segment and check that some customers are not being added. I don't know how to reproduce the bug in other instances.  

I attach a PDF with screen captures. You can see how the customer "test@fb.com" should be added to segment but segment is empty. 

This happens with other 5 customers more, but it works with +600 customers. 
[mautic_Segmentbug.pdf](https://github.com/mautic/mautic/files/2446612/mautic_Segmentbug.pdf)

 
### Log errors: 

This is the last log entry, it's older than the test and I guess it's not related to the bug. 

[2018-10-04 15:22:27] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Query\QueryException: "The given alias 'list' is not unique in FROM and JOIN clause table. The currently registered aliases are: l, u, list_lead, list." at /home/---mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryException.php line 50 {"exception":"[object] (Doctrine\\DBAL\\Query\\QueryException(code: 0): The given alias 'list' is not unique in FROM and JOIN clause table. The currently registered aliases are: l, u, list_lead, list. at /home/---mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryException.php:50)"} []

**Comment by npracht** [comment]
Hi @Carlos-mb any chance that your 5 contacts has been removed from the segment manually ? Starting from there they cannot be added anymore dynamically.
Please check your SQL table: `lead_lists_leads` if you see your contacts manually_removed ;)

**Comment by Carlos-mb** [comment]
Good to know!

Thank you. 

But there si no "Manually removed" records. 

Anyway, I deteced it when creating a new segment. 

Thanks for your idea.

**Comment by npracht** [comment]
@Carlos-mb thanks for that feedback. The issue is that we're not able to reproduce... So it is almost impossible to help.

For your example above, on the empty for last active there is a date anyway on right. This is weird. Are you able to recreate the segment and leave that empty ?

**Comment by Carlos-mb** [comment]
I did. 
I delete the filters one by one to check which was the failing one... Then I created again and it still failed.
I understand that if you can't reproduce it it's hard to fix.

**Comment by RCheesley** [comment]
Closing the issue as it was not possible to reproduce
