### ISSUE TITLE
Preference center pages ignores styling and button content

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#6680]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
Individual preference page content can be edited and styled. Looks correctly in builder and in preview - but completely different in the final rendered page.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1 and probably earlier
| PHP version | 7.0

### Steps to reproduce:
1. create a landing page
2. define it as preference center page
3. add "save preferences" button
4. give it different content, color etc.
5. save and watch preview
6. create an email 
7. create a test segment
8. define the above landing page as the individual preference page for this email
9. send the email to the test segment and look at the unsubscribe link

Whilst other elements of the landing page can be styled using a custom theme, at least the button fails completely. It has element styles inline and also uses the standard english "save preferences" - event if differently saved within page editor.

As a comparison look at the attached screenshots. Please fokus on the button mainly. Totally different style and content (seems to be hard coded).

Version based on the productive unsubscribe link:
![screenshot-2018 10 04-19-17-45](https://user-images.githubusercontent.com/1241376/46491176-46ed8700-c80a-11e8-98fd-c40b0ded9d15.png)

Version based on builder and preview:
![screenshot-2018 10 04-19-17-31](https://user-images.githubusercontent.com/1241376/46491177-46ed8700-c80a-11e8-8ff2-abe64dc5d270.png)

 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Ready to test in https://github.com/mautic/mautic/pull/6455
