### ISSUE TITLE
Page break in forms is not working

### ISSUE THREAD

**Issue by andreab79** [mautic/mautic#6681]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The page break feature in form is not working if form is displayed in a wordpress website.
This happens in wordpress website if mautic is integrated usign wp plugin or just adding js code.
Instead page break works correctly if form is displayed in a mautic landing page

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0.32

### Steps to reproduce:
1. Create a form using page break festure
2. integrate the form in a wordpress website
 
### Log errors: 
no logs presents

**Comment by wucherpfennig** [comment]
This is really an issue. We have several large forms which now are not "pageable" anymore

**Comment by escopecz** [comment]
Could you test if https://github.com/mautic/mautic/pull/6665 fixes the issue?

**Comment by wucherpfennig** [comment]
@escopecz Quick and dirty test showed that it seems to resolve the problem (on "non" landingpages). Keep up your great work!

**Comment by andreab79** [comment]
@wucherpfennig waiting this fix i solved the issue passing information from a form to another using email field like key

simply add this code to redirect page of first form ?email={leadfield=email|true}

and in second form add an email hide field (for autofill) so information of both forms will be related to the same contact

hope this help

**Comment by wucherpfennig** [comment]
@andreab79 thank you for this suggestion, didn't think about that... But in our scenario we "implemented" the fix now manually since there are too many references where we needed to update the code.

**Comment by sbolinches** [comment]
Hi, I can not use two forms on the same page because the page break does not work correctly. (There are some problems with js makes two forms on the same page not work correctly) I use 2.15.1 version. :(
