### ISSUE TITLE
Phone field type creates error

### ISSUE THREAD

**Issue by andreab79** [mautic/mautic#6682]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
The phone field type in form, creates error after submit, if form is displayed in a wordpress website.
This happens in wordpress website if mautic is integrated using wp plugin or just adding js code.
Instead phone field type works correctly if form is displayed in a mautic landing page

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0.32

### Steps to reproduce:
1. Create a form using phone field type
2. integrate the form in a wordpress website
3. submit the form
 
### Log errors: 
no logs presents

**Comment by npracht** [comment]
Hello @andreab79 can you try https://github.com/mautic/mautic/pull/6645 ?

**Comment by andreab79** [comment]
@npracht tx, for now i solved using a standard text field
