### ISSUE TITLE
Segments - view own

### ISSUE THREAD

**Issue by adrianwaler** [mautic/mautic#6688]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
User with access only to view own contacts is not able to see own segments (he see them on list but cannot see single), but he is able to edit, clone and delete.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. Create new role with access only to view own contacts
2. Add user to this role
3. Log in as this user
4. Create new segment
5. You can see this segment on list
6. Try to open segment
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by adrianwaler** [comment]
Testable only after fix for #6687

**Comment by npracht** [comment]
Merged in 2.15.1 https://github.com/mautic/mautic/pull/6689
