### ISSUE TITLE
Event trigger counts are inaccurate when new events are added.

### ISSUE THREAD

**Issue by heathdutton** [mautic/mautic#6691]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | 
| Enhancement? | 

## Description:
getCountsForPendingContacts (which gets the counts) and getPendingContactIds (which gets the leads to work on) use slightly different logic.
getCountsForPendingContacts will be bloated if leads enter a campaign and new events are added to the campaign after that fact.

This may result in people complaining that events aren't being triggered when it's actually just a miss-count.  Luckily getPendingContactIds is still accurate and will not re-process those leads with the new event.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.x
| PHP version | 7.1

### Steps to reproduce:
1. Create a Campaign with one event.
2. Add a lead to the campaign manually.
3. Run mautic:campaigns:trigger on the campaign. 
4. Add another event to the campaign.
5. Run mautic:campaigns:trigger again. 
Note "Triggering events for newly added contacts" will show a count that is higher than expected, and the issue will remain forever.
 
### Log errors: 

none.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
