### ISSUE TITLE
Forms doesn't shown suddenly

### ISSUE THREAD

**Issue by Carlos-mb** [mautic/mautic#6692]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:

Forms are not shown using automatic javascript or WPmautic plugin, but they are shown using "Manual Copy"

I have had a form working wirh wpmautic plugin for several weeks and now it as stopped working.

In the page source code now appears: <script type="text/javascript" src="https://mautic.coachingrealista.com/mautic/form/generate.js?id=3"></script>

And in the webpage appears nothing. 

I works fine if I use the "Manual copy" option and I add script and html manually. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0.32

### Steps to reproduce:
1. Create a form
2. Add it in a web page using "Automatic Javascrip"
 
### Log errors: 

No log entries

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Share the link to the problematic website, please. Cannot help without it.

**Comment by Carlos-mb** [comment]
Hi
If you try https://coachingrealista.com/el-metodo-de-coaching-realista/ you will se the form working. 

I have used the HTML copy - paste alternative. 

In the botton of the page you can see "--", that's because the code there is: "-[mautic type="form" id="3"]-"  and the form returns no content. 

We have cheched that 

https://mautic.coachingrealista.com/mautic/form/generate.js?id=3

returns also an empty string.

**Comment by escopecz** [comment]
Can you try to clear cache? I have no ideas what else to try. Did you change some server configuration lately?

**Comment by Carlos-mb** [comment]
Cache cleared using "console cache:clear"

It still fails...

I'm not sure if it was in the same date, but I have upgrade the hosting service. They changed the server and the IP in DNS... 

Do you think it could be the reason?

**Comment by Carlos-mb** [comment]
This is in the error_log file: 

PHP Warning:  dns_get_record(): A temporary server error occurred. in /home/carlosm1/mautic.coachingrealista.com/mautic/app/bundles/LeadBundle/Helper/IdentifyCompanyHelper.php on line 138

**Comment by escopecz** [comment]
I don't think the PHP warning is related. Try to re-save the form if it helps.

**Comment by Carlos-mb** [comment]
Re-saved.. doens't work

**Comment by escopecz** [comment]
Last tip I can think of is regenerating the assets with `app/console mautic:assets:generate` command.

**Comment by escopecz** [comment]
I'm afraid this is not something we can control from Mautic side. It seems more like a server configuration issue. I will close this for now but please keep us updated if you find out more info.

**Comment by escopecz** [comment]
The reason I closed it is because I'm convinced this is not a Mautic issue but a server configuration issue. We cannot have issues opened for this reason as there is nothing we can do from our end to resolve them. If you find some information that we can do something to resolve it I will gladly reopen this issue.

**Comment by Carlos-mb** [comment]
I have fixed it dissabling "Cache Wall" in hosting service for mautic subdomain.
