### ISSUE TITLE
Database error Index column size too large on fresh Mautic install at ver. 2.14.1

### ISSUE THREAD

**Issue by AkkuFresh** [mautic/mautic#6693]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Yes
| Feature request? | 
| Enhancement? | 

## Description:
The database creation during install failed with error: **Index column size too large. The maximum column size is 767 bytes.**
This type of problem occurs because there was using an older mysql. Unfortunately the WHM/C-Panel does not support yet the MySQL 5.7 only 5.6 and 5.5.
The bug can occur in a newer MySQL (5.7) with wrong settings also. 
If you do not have the innodb_default_row_format setting (introduced in MySQL 5.7.9) this bug will occur and brake the new install and the upgrade also.
The bug can appear in the MariaDB versions also.

The bug hangs up the database creation at the Version20170323111702.php migration file.

## Suggestion:
I suggest to change the bug report template to include MySQL server type (MySQL, MariaDB) and version also, because all database schema or migration related bugs depends from the sql server type of version.
And for the correct analysis we also should know the environment, e.g. it is WHM/C-Panel or other. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  2.14.1
| PHP version |  7.1.22
| MySQL server |  MySQL 5.6.41
| Server environment | WHM/C-Panel v. 74.0 (build 9)

### Steps to reproduce:
1. Start a fresh standard install on a server with MySQL version 5.6
2. You will see the error on the step 2. database creation

## Method to immediate handle this install error:
1. Start a fresh install in a local server with MySQL 5.7. For example I have a special modified XAMPP with MySQL 5.7.23 and different PHP versions.
2. Export the installed fresh Mautic database from this system with PHPMyAdmin.
3. With your favorite editor (Notepad++) change in the saved SQL file the following for every table:
from 
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
to
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC;
it means you should change the default row format from COMPACT to DYNAMIC in the InnoDB system.
4. Import the modified SQL file to your webserver (WHM/C-Panel) with PHPMyAdmin
5. Upload to the server the Mautic source files.
6. Change the content of the .../app/config/local.php with your database credentials and real site_url data.
7. Delete Mautic cache
8. Follow JOHN LINHART advice at [https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful](https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful ) with point 3 and 4, and check the database statuses.
9. If you do not have SSH access to your server (it is typical on the WHM/C-Panel) you can use Cron job to run any Matuic console command. You will set an exact time to run the cron and it will do its job.  
10. Example Cron command on C-Panel to check Mauitc:
/usr/local/bin/php -c /home/--your_path--/php.ini /home/--your_path--/app/console mautic:update:find >/home/--your_path--/mautic_update_log.txt 2>&1
11. Check the content of the mautic_update_log.txt and find what to do.

This method will help to resolve this issue also: https://github.com/mautic/mautic/issues/6213 

## Suggested global solutions:
Change the migration files to check the MySQL database engine settings and set the proper row format if it is not the default.
Set innodb_file_format=Barracuda
Set innodb_large_prefix=1
Set innodb_default_row_format=dynamic

This bug is also related to Laravel or other doctrine based database install.
[https://github.com/laravel/framework/issues/22660](https://github.com/laravel/framework/issues/22660)
Thanks Sisve to face the real problem and suggest a proper solution.
 
### Log errors: 
The tweets table the first with this type of errors:
CREATE TABLE IF NOT EXISTS #prefix_tweets (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, page_id INT DEFAULT NULL, asset_id INT DEFAULT NULL, is_published TINYINT(1) NOT NULL, date_added DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', created_by INT DEFAULT NULL, created_by_user VARCHAR(255) DEFAULT NULL, date_modified DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', modified_by INT DEFAULT NULL, modified_by_user VARCHAR(255) DEFAULT NULL, checked_out DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', checked_out_by INT DEFAULT NULL, checked_out_by_user VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, media_id VARCHAR(255) DEFAULT NULL, media_path VARCHAR(255) DEFAULT NULL, text VARCHAR(255) NOT NULL, sent_count INT DEFAULT NULL, favorite_count INT DEFAULT NULL, retweet_count INT DEFAULT NULL, lang VARCHAR(255) DEFAULT NULL, INDEX tweet_text_index (text), INDEX favorite_count_index (favorite_count), INDEX sent_count_index (sent_count), INDEX retweet_count_index (retweet_count), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB; Index column size too large. The maximum column size is 767 bytes.

**Comment by escopecz** [comment]
Closing as duplicate of https://github.com/mautic/mautic/issues/5647
