### ISSUE TITLE
Traduction problem

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#6696]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When you go in the condition with a form field you have to times in french contains...
![capture d ecran 2018-10-09 a 07 40 55](https://user-images.githubusercontent.com/20974155/46648757-c676af80-cb96-11e8-8089-cfbaa22d44a8.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.x.x

### Steps to reproduce:
1. See the image
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Please feel free to join Mautic Transifex and suggest a better translation.

**Comment by escopecz** [comment]
The French translation is not part of this repository. The community is translating it here: https://www.transifex.com/mautic/mautic/

Please join the community and suggest your changes there.
