### ISSUE TITLE
Campaign with Form Field Value with a list doesn't work

### ISSUE THREAD

**Issue by tpilet** [mautic/mautic#6697]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | Yes

## Description:
Just mak a personal field with a list of value
![capture d ecran 2018-10-09 a 07 45 26](https://user-images.githubusercontent.com/20974155/46649009-b6130480-cb97-11e8-9e80-f9e9de5e8734.png)

Make a form with a field is a checkbox list and use the data of the personnal field to poulate and use
![capture d ecran 2018-10-09 a 07 46 01](https://user-images.githubusercontent.com/20974155/46649040-d347d300-cb97-11e8-8836-af3749084df4.png)

Make a campaign and try to use this field as a condition
![capture d ecran 2018-10-09 a 07 47 09](https://user-images.githubusercontent.com/20974155/46649061-e35fb280-cb97-11e8-9f10-dd81fec68a7f.png)

You can't select the value of the field.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.x.x

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
This issue looks abandoned. Closing.
