### ISSUE TITLE
cronjobs work on unpublished segment

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6698]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
It appears that the command `php app/console mautic:segments:update` work on unpublished segments.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 

### Steps to reproduce:
1. Unpublish some segments and launch command `php app/console mautic:segments:update`
2. See in the console that it works on unpublished segments too
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by Woeler** [comment]
Merged https://github.com/mautic/mautic/pull/6717
