### ISSUE TITLE
segment issue with url visited and character &

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6699]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
There is a issue with segment filter URL visited and special character &
If you add a character after & on the URL visited filter, segment does not work.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 

### Steps to reproduce:
1. Create an email and add a link like this
https://www.google.fr/?utm_source=toto&utm_medium=tutu&utm_campaign=tata&utm_content=titi
![image](https://user-images.githubusercontent.com/31535432/46657060-b8815880-cbaf-11e8-894e-b18d19e26b5b.png)
2. Send you email, click on the link.
3. Create a first segment, take URL visited filter and take the like operator
![image](https://user-images.githubusercontent.com/31535432/46657233-19a92c00-cbb0-11e8-9064-3da999cd4c86.png)
and the value `%utm_source=toto&%`
![image](https://user-images.githubusercontent.com/31535432/46657360-5ffe8b00-cbb0-11e8-9647-feabc6b246fd.png)
4. Create a 2nd segment, same filter, same operator but this time modify the value with `%utm_source=toto&u%` . (just added a "u" after the &)
![image](https://user-images.githubusercontent.com/31535432/46657419-858b9480-cbb0-11e8-89d9-21f2db34cbe2.png)
5. Run php app/console mautic:segments:update and see that 1st segment works (contact inside) and second segment does not work (no contacts)

That means if there is a character after the 1, it does not work
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
This PR should fixed it: https://github.com/mautic/mautic/pull/6046
