### ISSUE TITLE
Misleading production package info in README.md

### ISSUE THREAD

**Issue by mawomerc** [mautic/mautic#6705]
In README.md :
"Production package ready for install with all the libraries is at https://www.mautic.org/download."

That's not true. After I gave my e-mail address and other details I got the same version as on Github.

fc3d478c8c48816f9292aa0959a3f56ef928ee75fc92f852b366c7a4520ee28e  Github-2.14.1 .zip
fc3d478c8c48816f9292aa0959a3f56ef928ee75fc92f852b366c7a4520ee28e  Mautic.org-2.14.1.zip

**Comment by Woeler** [comment]
How is it not true? The version on Mautic.org definitely does contain all libraries.

![mautichaslibs](https://i.imgur.com/u0pteQy.png)

**Comment by mawomerc** [comment]
"The GitHub version is recommended for development or testing. Production package ready for install with all the libraries is at https://www.mautic.org/download."
Sounds for me like different versions are advertised and this is not true.

**Comment by Woeler** [comment]
You are confusing github release package with github branch zips.
