### ISSUE TITLE
Problem with DoNotContact

### ISSUE THREAD

**Issue by fgauttron** [mautic/mautic#6708]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
We can no longer assign the DoNotContact parameter for a contact. 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 5.6.38-0+deb8u1

### Steps to reproduce:
1. Modify contact's preferences
2. Uncheck email and sms channels
3. Mautic does not record changes
 
### Log errors: 
mautic.ERROR: PHP Error - Argument 1 passed to Mautic\LeadBundle\Model\DoNotContact::__construct() must be an instance of Mautic\LeadBundle\Model\LeadModel, none given, called in /var/www/mautic/app/bundles/LeadBundle/Model/LeadModel.php on line 2225 and defined - in file /var/www/mautic/app/bundles/LeadBundle/Model/DoNotContact.php - at line 36

**Comment by Woeler** [comment]
Are you sure this is everything needed to reproduce the bug? Because I am unable to reproduce.

**Comment by fgauttron** [comment]
Yes. We have the same error with the monitoring of the mailbox where we receive unsubscribe requests.

**Comment by fgauttron** [comment]
Possible merge with issue [6609](https://github.com/mautic/mautic/issues/6609)

**Comment by fgauttron** [comment]
We upgrade https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Model/LeadModel.php and fix the problem
