### ISSUE TITLE
Monitoring inbox for unsubscribe requests do not work

### ISSUE THREAD

**Issue by cefimadmin** [mautic/mautic#6713]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
We have set up the monitoring of a mailbox for unsubscribe requests. 
The cron task php /app/console mautic:email:fetch works but unsubscribe requests do not go back to the contact level in Mautic. The contacts do not have the DNC parameter. 

The cron task indicates that 0 emails have the status UID 372:*

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 5.6.38-0+deb8u1

### Steps to reproduce:
1. Configure monitoring mailbox for unsubscribe request
2. Apply cron task php app/console mautic:email:fetch
3. Verify DNC parameter for contact that was maked unsubscribe in inbox
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by fgauttron** [comment]
Hello,
The mailbox is a gmail box and we use amazon ses for sending emails
Thanks

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
