### ISSUE TITLE
mmap() failed: [12] Cannot allocate memory

### ISSUE THREAD

**Issue by tyweb2** [mautic/mautic#6714]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
mmap() failed: [12] Cannot allocate memory

# php /var/www/html/mysite/app/console mautic:campaigns:rebuild
Rebuilding contacts for campaign 3
130335 total contact(s) to be added in batches of 300
      0/130335 [>---------------------------]   0%
mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 1533030400) (tried to allocate 20480 bytes) in /var/www/html/mysite/app/bundles/LeadBundle/Entity/CustomFieldRepositoryTrait.php on line 92

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 1533030400) (tried to allocate 20480 bytes) in /var/www/html/mysite/vendor/symfony/debug/ErrorHandler.php on line 650

This is running on an AWS t2.large instance

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.14.1
| PHP version | PHP Version 7.1.22-1

### Steps to reproduce:
1.php /var/www/html/mysite/app/console mautic:campaigns:rebuild
2. 
 
### Log errors: 
[Wed Oct 10 01:01:40.690017 2018] [php7:error] [pid 1493] [client] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/mysite/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58, referer: http://mysite/s/campaigns/edit/2
[Wed Oct 10 01:01:40.698798 2018] [php7:error] [pid 1493] [client] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 73728 bytes) in /var/www/html/mysite/vendor/composer/ClassLoader.php on line 444, referer: http://mysite/s/campaigns/edit/2
[Wed Oct 10 01:08:50.520888 2018] [php7:error] [pid 1695] [client ] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/mysite/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58, referer: http://mysite/s/campaigns/edit/2
[Wed Oct 10 01:08:50.526074 2018] [php7:error] [pid 1695] [client ] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 73728 bytes) in /var/www/html/mysite/vendor/composer/ClassLoader.php on line 444, referer: http://mysite/s/campaigns/edit/2
[Wed Oct 10 01:10:32.947496 2018] [php7:error] [pid 1764] [client ] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/mysite/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58, referer: http://mysite/s/campaigns/edit/2
[Wed Oct 10 01:10:32.952092 2018] [php7:error] [pid 1764] [client] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/mysite/vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1, referer: http://mysite/s/campaigns/edit/2
[Wed Oct 10 15:04:50.320788 2018] [php7:error] [pid 5505] [client] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 12288 bytes) in /var/www/html/mysite/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php on line 58, referer: http://mysite/s/campaigns/edit/2
[Wed Oct 10 15:04:50.328352 2018] [php7:error] [pid 5505] [client ] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/mysite/vendor/symfony/debug/Exception/OutOfMemoryException.php on line 1, referer: http://mysite/s/campaigns/edit/2
[Wed Oct 10 15:38:11.641220 2018] [php7:notice] [pid 5871] [client ] PHP Notice:  Array to string conversion in /var/www/html/mysite/app/bundles/LeadBundle/Form/DataTransformer/TagEntityModelTransformer.php on line 136, referer: http://mysite/s/campaigns/edit/2
[Wed Oct 10 15:40:20.128059 2018] [php7:notice] [pid 6015] [client ] PHP Notice:  Array to string conversion in /var/www/html/mysite/app/bundles/LeadBundle/Form/DataTransformer/TagEntityModelTransformer.php on line 136, referer: http://mysite/s/campaigns/edit/2

**Comment by escopecz** [comment]
This issue looks abandoned. Closing.
