### ISSUE TITLE
Language set to german has no effect

### ISSUE THREAD

**Issue by JeffryMills** [mautic/mautic#6715]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  YES
| Feature request? | NO
| Enhancement? | NO

## Description:
Set correct directory permissions on server. But when i select german language in configuration, german files get downloaded. Inside the languages folder i see a "de" folder and the .ini files inside.
But still the Mautic Gui and everything stays english. There is no error in log file

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.2.10-0ubuntu0.18.04.1

### Steps to reproduce:
1. Settings -> Configuration -> System Defaults
2. Set language to german and save
3. Mautic is still english

**Comment by npracht** [comment]
Hi,

Did you change the language of your user?
Also, you can add translations on https://www.transifex.com/mautic/mautic/dashboard/ because it is not all translated:
>German (de) 960 strings to translate 3,568 strings to review

**Comment by JeffryMills** [comment]
thanks for answer
yes both user and general language are set to german but i dont see a single german word.
already registered there  ,)

**Comment by npracht** [comment]
Did you try to logout/login and clear cache ?

**Comment by JeffryMills** [comment]
bingo ! after clearing cash i see the german translation !
thank you very much ... to point me at that

**Comment by TMInnovations** [comment]
I'm facing the same problem. Even clearing the cache/logginig in and out doesn't really change the language. What I did: 

- Configuration => System Settings => Default Language => German => Save & Close => "Configuration successfully updated"
- Account => Language => German => Apply => "Account has been updated"

Logout => Clear Browser Cache => Login


Any Ideas? Thank you very much!!

**Comment by florent427** [comment]
Hi it's very simple just clear the Cache  on the server , go to the /app/cache folder and delete its content.
