### ISSUE TITLE
Campaign email click trigger not working

### ISSUE THREAD

**Issue by wonderful123** [mautic/mautic#6718]
Question:

Does the campaign trigger for email clicks work? I have tried all different scenarios I can think of. Different template, different "Urls contains" or none. Nothing is triggering.

The email open trigger works fine.

I can't see any recent log errors in mautic or apache. I've tried with php 5.6 and 7.1. Using latest mautic 2.14.1 on Centos 7.

How can I go about fixing this?

**Comment by wonderful123** [comment]
This was all because I was logged into mautic. Clicked the link through another browser and it works. Many hours wasted. At minimum there needs to be a note in the docs.

**Comment by escopecz** [comment]
Then we are lucky that the note is there https://www.mautic.org/docs/en/emails/troubleshooting.html
