### ISSUE TITLE
BUG: Email Preview - Links Broken

### ISSUE THREAD

**Issue by MaxOnTheHill** [mautic/mautic#672]
In the online email preview all the links appear to be broken.

Easy replication, is when viewing an email, click on preview ... links don't work.

**Comment by escopecz** [comment]
There has been few fixes about email links in upcoming version 1.1.3. What version are you referring to? If you have the skills (I can see you are active on GitHub), could you apply the changes in the staging branch and tell us if the bug is fixed?

**Comment by alanhartless** [comment]
I can replicate this.  He's referring to the "Preview/Online URL." It's not sending the content through the token generator.  Easy fix.  One will be coming up today.

**Comment by MaxOnTheHill** [comment]
Awesome ... thanks for fast response guys .... and yes @alanhartless it is the "Preview/Online URL".

Thought it should be an easy fix for someone embedded in the code .... the online preview is a great feature, but if using it as a "View Online" and sending clients through would be very embarrassing ;)

Thanks again.

**Comment by alanhartless** [comment]
@MaxOnTheHill As a FYI, the online preview link is behind the secure firewall so requires a user to be logged in to preview it.  But I can see the benefit of opening that up to send to clients.

**Comment by MaxOnTheHill** [comment]
@alanhartless  wow ... would have been an even bigger fauxpa if I'd used that as a preview in the link for emails ... worked beautifully for me, but of course I was logged in.
-> having open for "View Online" would be a big bonus,as is reasonably standard functionality and a lot of people do this to view properly (text/antiquated email readers).
-> if the online preview also loaded the system analytics (currently set as landing page analytics in settings) that'd be a big bonus if it was public.

thanks

**Comment by alanhartless** [comment]
There is already a view online feature.  Just include the {webview_text} (text with a link embedded) or the {webview_url} (just the url to be used in a custom link/text) in your email. But those links are generated specific to the Mautic email/lead.

**Comment by alanhartless** [comment]
Forgot to mention those links also already include the analytics tracking code

**Comment by MaxOnTheHill** [comment]
Do you mean the the "Web View URL" preview includes the analytics tracking code, like a landing page .... or something else?

I have not had email link reporting within mautic working (in slack chat https://mautic.slack.com/archives/issues/p1437167458000074).

**Comment by MaxOnTheHill** [comment]
There is a problem here .... the {webview_url} variables do NOT work in custom emails ... only in the email "themes" .... so having working public view of the online preview would be very handy.

.... thinking perhaps NO email variables will work in html emails -> only when using the themes?  Also, could this be the similar for links not being tracked in custom html emails?

**Comment by alanhartless** [comment]
Are you referring to when editing an email that has {webview_url} in it? If so, see #566.

**Comment by MaxOnTheHill** [comment]
yep ... #566 looks like what I experienced ... think that'd be solving that issue - thanks.

.. is there an "email variables" reference guide/doc somewhere ... or refer to "email themes UI" ?

**Comment by MaxOnTheHill** [comment]
or are they all in a reference file of the repo?

**Comment by MaxOnTheHill** [comment]
also ... doesn't seem to set an option for "Unpublish" status in edit/list for a "list type" email.

would be great if you could set EITHER ... no list option (not required) or have a status for "Unpublish" ... as on first save I already have a queued email, because I have to set a list for the email - and no possibility to set as unpublish so it doesn't already assign to lists :(
