### ISSUE TITLE
frequency rule does not apply on campaign

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6729]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
If you set up frequency rule in the general configuration, emails are still sent from campaigns.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 

### Steps to reproduce:
1. Set up frequency rules (for example: 2 emails per week)
2. create a contact
3. Create 2 segment emails and send it to the contact
4. Create a campaign email then create a campaign and send this third email to the contact
5. See that contact received the email (it should not as we set up in the general configuration not more than 2 emails per week)
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/issues/6729

**Comment by Woeler** [comment]
Merged https://github.com/mautic/mautic/pull/6760

**Comment by kuzmany** [comment]
This should works properly, I hope https://github.com/mautic/mautic/pull/6896

**Comment by kuzmany** [comment]
Closed based on discuss https://github.com/mautic/mautic/pull/6896
