### ISSUE TITLE
<object> tags removed from twig template

### ISSUE THREAD

**Issue by BillyHilly** [mautic/mautic#6733]
What type of report is this:

| Bug report? | 

## Description:
I created a custom mautic theme, based off the `blank` theme that ships with mautic. In the custom theme's `.twig` files, I added an `<object>` tag in both the header and footer, which contained SVG logos—this way, I get the benefits of caching the SVG while also allowing me to do CSS manipulations to the SVG.

When I tested my theme out the first time, I noticed the logos were not showing. On further inspection, the `<object>` tags had been completely removed!

I got to googling for answers/solutions. At first I thought I'd just need to add `object` to the `htmlAllowTags` found in `/app/bundles/CoreBundle/Assets/js/libraries/froala/froala_editor.js`. On further inspection, I realized it already has the `object` tag listed.

Next thought was maybe the `<object>`'s attributes were the issue and would need to be added to `htmlAllowedAttrs` in the `froala_editor.js` file. Nope. It already had the only two attributes my `<object>` tags had: `type` and `data`. So neither one of those seem to be causing the issue—and I'm at a loss as to why the WYSIWIG is allowed to mess with `.twig` template code anyway.

## If a bug:

| Mautic version | 2.14.2
| PHP version | 7.1.8

### Steps to reproduce:
1. Create a new theme or edit an existing theme.
2. Add an object tag that calls an .svg resource (not sure if it does this with anything other than .svg, didn't check). Something like this: `<object type="image/svg+xml" data="https://s.cdpn.io/3/kiwi.svg"></object>`
3. Save the template file, then login to mautic and create a new landing page using the theme you added the `<object>` tag to.
4. You'll see in both the builder and preview page that the `<object>` tag gets striped out.
 
### Log errors: 
None

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by BillyHilly** [comment]
Thanks @npracht 
However, this post is almost 2 years old. I'd forgotten about it honestly.
And I'm on Mautic PRO now so not sure I could even test accurately there.
I believe I just threw in the towel on this one, and went with SVG's embedded directly in CSS as backgrounds and just forgot about all the fanciness I was trying to do.
An object tag with an svg that contains css animations is great to have though for alot of cases.
I just don't have a use case at the moment, nor a local instance to test on.
Maybe someone else can give it a whirl for you...
