### ISSUE TITLE
Webhook authenticity verification

### ISSUE THREAD

**Issue by Clement134** [mautic/mautic#6734]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No |
| Feature request? | Yes |
| Enhancement? |  Yes |

## Description:
Currently it is not possible for systems using mautic webhooks to verify if a webhook call comes from mautic, and if its payload hasn't been modified.

A common solution for this problem (used for example by [github](https://developer.github.com/webhooks/securing/), [shopify](https://help.shopify.com/en/api/getting-started/webhooks#verify-webhook) and [wooCommerce](http://woocommerce.github.io/woocommerce-rest-api-docs/#webhook-properties)) is to provide a digital signature in the headers of each webhook calls.

In order to do this, mautic has to:
- generate a secret which will be shared with the application receiving the webhooks
- calculate a signature, using this secret on each payload data
- send this signature on webhook calls headers'

This solution didn't introduce breaking changes because each application could implement signature verification or not.

**Comment by RCheesley** [comment]
Closing as this was fixed with #8397
