### ISSUE TITLE
Segment emails don't send if the "From address" field in the advanced tab is used

### ISSUE THREAD

**Issue by Lewom** [mautic/mautic#6738]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
If I enter an email in the "From address" field in the advanced tab the email won't be sent. It works to enter a "From name" but for some reason any information in the "From adress" field will prevent the email from sending. 

The "Owner is mailer" setting is disabled.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.1.17

### Steps to reproduce:
1. Create an segment email and make sure to fill in the "From address" in the advanced tab.
2. The email will fail to send.

**Comment by npracht** [comment]
Hi @Lewom !

What is your email configuration ? In certain case, you need to setup a validated domain name (or even email address) and if you use one which is not validated then the email is not sent by the router.
It sounds like a configuration issue of that type.

**Comment by Lewom** [comment]
That did the trick. Thank you very much for the help, @npracht!
