### ISSUE TITLE
Mautic giving error while form submission after upgrading

### ISSUE THREAD

**Issue by ZeeshiEli92** [mautic/mautic#6739]
What type of report is this:

Mautic giving error while form submission
cached clear but still not working
www.mysite.com/?mauticError=Errors%3A<br%20%2F><ol><li>Array<%2Fli><%2Fol>#Form_Name

on all forms.

This error comes after upgrading

**Comment by escopecz** [comment]
Duplicate of https://github.com/mautic/mautic/issues/6632
