### ISSUE TITLE
SMS click tracking and contact merge inefficient

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#6747]
## Bug Description
It seems that tracking hash is not linked to the contact for SMS. That makes the anonymous contact created not merged to initially shooted contact.
bit.ly is enable.

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create an SMS with a link
2. Create a contact with a phone number and an email
3. Send the SMS to contact via a campaign
4. Click on link and see your contacts --> An anonymous is created instead of adding the visit page to the targeted contact.

#### I have the feeling that the hash is not correctly linked between tables?

![capture d ecran 2018-10-16 a 15 57 25](https://user-images.githubusercontent.com/14075239/47022132-1c31f580-d15d-11e8-9063-cf8dd30b9bdd.png)
![capture d ecran 2018-10-16 a 15 58 41](https://user-images.githubusercontent.com/14075239/47022133-1c31f580-d15d-11e8-863b-06fcc5429897.png)
![capture d ecran 2018-10-16 a 15 58 58](https://user-images.githubusercontent.com/14075239/47022134-1cca8c00-d15d-11e8-8c46-8e178259ab77.png)
 
### Log errors
None

**Comment by kuzmany** [comment]
Didn't related to https://github.com/mautic/mautic/pull/6591 ?

**Comment by npracht** [comment]
I don't think as far as the click here is recorded but not related to the recipient knowing that the URL is re-written with the hash, i don't understand why.

**Comment by kuzmany** [comment]
@npracht  Just question: Do you have marked Email as Publicly updatable? I bet, not :)

**Comment by kuzmany** [comment]
@johbuch because it's the same like 

`mt('send', 'pageview', {email: 'my@email.com'});`

There is a info in docs about it: 
https://www.mautic.org/docs/en/contacts/contact_monitoring.html

**Comment by npracht** [comment]
I don't get why the web tracking is related to an email/sms click.
The URL is re-written, the re-written email is tracked. What type of parameter is sent to the web tracking script?

**Comment by npracht** [comment]
Please test https://github.com/mautic/mautic/pull/6829

**Comment by Woeler** [comment]
Merged https://github.com/mautic/mautic/pull/6829
