### ISSUE TITLE
Every setting on Email Settings page disappears every few days.

### ISSUE THREAD

**Issue by DanGoodSoftware** [mautic/mautic#6756]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Bug Report
| Feature request? | 
| Enhancement? | 

## Description:
Every setting in Configuration -> Email Settings is lost every few days.  So every time we send an email blast, we first have to go to Configuration -> Email Settings and re-enter all settings, including Email Frequency rule etc.  No marketing data is lost, just Configuration settings.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.1.23

### Steps to reproduce:
1. Log in to Mautic
2. Try to send email blast
3. Email blast fails
4. Check Configuration -> Email Settings and find all settings completely wrong
 
### Log errors: 
The only error relates to an exception occurring while executing 'INSERT INTO mauun_point_lead_action_log.
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Hi @DanGoodSoftware ! Thanks for sharing that information.
Unfortunately i don't experience the same problem and i don't know how to reproduce.

Is there any chance that your local.php file is cached or updated or replaced by any process?

**Comment by DanGoodSoftware** [comment]
Hi @npracht.  I looked at local.php and saw that it did contain all the incorrect information, even though I had set all that same information just before I first posted.  So I again corrected all Email settings and then Apply, and Save and Close.  I looked at local.php again I saw the correct settings there.  I took a screenshot so I can monitor if the Modified information changes.

In Plesk, the php settings indicate that opcache is enabled.  I don't have any ideas about how I would check if any process was updating or replacing the file, beyond watching to see if the local.php Modified information changes.  

There is very little running on the VPS.

Thanks for giving me something to start looking at.

**Comment by DanGoodSoftware** [comment]
@npracht Only 19 minutes later, every file in the Apps/Config folder was overwritten.  Looking at the logs in Plesk, one of my development computers was using Git at the time the overwrite happened.  So that is the issue, apparently.  Again, thank you for pointing me in the correct direction to figure this out!
