### ISSUE TITLE
Empty leads/contacts with null values

### ISSUE THREAD

**Issue by Carlos-mb** [mautic/mautic#6757]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have a report that shows these columns from contacts: 

Contact ID, Email, Date identified and Country

It was working until today that it's showing many empty records. 

Those contacts do not appear in "Contacts"
They do exist in database, but with all fields with NULL values. 
They are editable when clic in the "id" field from the report. 

I have created a new report and these records appear again. 

When edditing them, in the top left appears: 

EDIT xxx,xxx,xxx.xxx 

Where "xxx.xxx.xxx.xxx" is an IP address. 

I thing Mautic is creating a new contact for every IP used to access the site when the User is not idenficable. Could it be possible? 

There are records with new and old IDs. So I guess they have been created from the begining. 

Yesterday these records where not shown in the report but now they are. 

I attach a PDF with screen captures. 

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0.32
| Browser | Chrome

### Steps to reproduce
1. Create a report showing data from contacts
2. See he report and find those empty records
3. Clic on ID field to edit it and check that ther are empty but with creation date. 
4. From "Contacts" page use "ids:" filter to check they are not found.
 
### Log errors
No errors related to this issue
[ghostrecords.pdf](https://github.com/mautic/mautic/files/2489636/ghostrecords.pdf)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hello @Carlos-mb !

For me it is just about anonymous contacts created with the tracking script. So it is "normal" that they exist.
That being said and going back to your report, I'd simply suggest you to add a filter "email is not empty" and then those anonymous won't be shown anymore.

Best !

**Comment by Carlos-mb** [comment]
Thank you for the solution. 

But... Why these contacts didn't appears before now?

and

If it was usual, Woudn't be happening in every installation? Is this happening to others?

**Comment by npracht** [comment]
Obviously if you say that before it was not here, somehow the report was excluding them automatically. But they are existing really so i'd say the good practice is to display them and add the filter.

**Comment by Carlos-mb** [comment]
Ok 

It's fixed for me. 

I was just trying to get more information and comment with the community to find out if this is normal and happens in all instances.

**Comment by kaustubhn** [comment]
Is there a way to stop the creation of null contacts? I am using the API and I am getting a new value of contacts every minute where as I am not creating any contacts.

**Comment by obsicn** [comment]
I meet this same problem. When will trigger to add null contacts and how to disable this? Thanks  a lot.

Below is the version information.
[root@vm10-0-0-215 mautic]# bin/console -V
Mautic 3.0.2 - app/prod (kernel: app, env: prod, debug: false)
[root@vm10-0-0-215 mautic]#
