### ISSUE TITLE
Infinite redirects after upgrade from 2.14.0 -> 2.14.1

### ISSUE THREAD

**Issue by jesseshieh** [mautic/mautic#6759]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
First of all, thanks for an awesome project! I'm running docker-mautic which was on version 2.14.0. I don't think this has anything to do with docker, but thought I'd mention that. 

Everything was working great on mautic.mydomain.com and I saw a notification to upgrade to 2.14.1. I clicked it and all seemed to go well until I was redirected to https:///s/update (notice that there is no host). I went back to mautic.mydomain.com manually and got into an infinite redirect. I cleared my cookies, no help. See some logs below.

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.1.23
| Browser | Chrome 68.0.3440.106 on OS X

### Steps to reproduce
1. Run docker-mautic
2. Go through upgrade process in web UI to go from 2.14.0 -> 2.14.1
 
### Log errors
```
10.1.24.13 - - [18/Oct/2018:14:18:42 +0000] "GET /upgrade/upgrade.php?task=finish&standalone=0 HTTP/1.1" 200 590 "https://mautic.mydomain.com/s/update" "Mozilla/5.0 (Macintosh; Int
el Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
10.1.24.13 - - [18/Oct/2018:14:18:42 +0000] "GET /s/ajax?action=core:updateDatabaseMigration&finalize=1&_=1539871824011&mauticUserLastActive=24&mauticLastNotificationId= HTTP/1.1" 3
01 1508 "https://mautic.mydomain.com/s/update" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
10.1.24.13 - - [18/Oct/2018:14:18:44 +0000] "GET /s/ajax?_=1539871824011&action=core%3AupdateDatabaseMigration&finalize=1&mauticLastNotificationId=&mauticUserLastActive=24 HTTP/1.1"
 301 1508 "https://mautic.mydomain.com/s/update" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
10.1.24.13 - - [18/Oct/2018:14:18:45 +0000] "GET /s/ajax?_=1539871824011&action=core%3AupdateDatabaseMigration&finalize=1&mauticLastNotificationId=&mauticUserLastActive=24 HTTP/1.1"
 301 1508 "https://mautic.mydomain.com/s/update" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
10.1.24.13 - - [18/Oct/2018:14:18:45 +0000] "GET /s/ajax?_=1539871824011&action=core%3AupdateDatabaseMigration&finalize=1&mauticLastNotificationId=&mauticUserLastActive=24 HTTP/1.1"
 301 1508 "https://mautic.mydomain.com/s/update" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
10.1.24.13 - - [18/Oct/2018:14:21:34 +0000] "GET / HTTP/1.1" 301 635 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106
 Safari/537.36"
10.1.24.13 - - [18/Oct/2018:14:21:35 +0000] "GET / HTTP/1.1" 301 635 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106
 Safari/537.36"
10.1.24.13 - - [18/Oct/2018:14:21:36 +0000] "GET / HTTP/1.1" 301 635 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106
 Safari/537.36"
10.1.24.13 - - [18/Oct/2018:14:21:36 +0000] "GET / HTTP/1.1" 301 635 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106
 Safari/537.36"
10.1.24.13 - - [18/Oct/2018:14:21:37 +0000] "GET / HTTP/1.1" 301 635 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106
 Safari/537.36"
10.1.24.13 - - [18/Oct/2018:14:21:37 +0000] "GET / HTTP/1.1" 301 635 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106
 Safari/537.36"
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hello @jesseshieh !
What is the instance URL in your configuration.
Did you try to clear the cache of the app ?

**Comment by jesseshieh** [comment]
Hey @npracht, thanks for the reply! I think I tracked it down to the "site URL" setting and not the upgrade. I think the reason it showed up after the upgrade is because the upgrade cleared my cache.
