### ISSUE TITLE
Custom Lookup field is broken

### ISSUE THREAD

**Issue by robov** [mautic/mautic#6763]
I want to send emails in the language of the contact.

I just noticed on the hosted trial version (mydomain.mautic.net)
When I add a custom lookup field (preferred language) as a lookup field with 2 options (ENG NLD)
When I then go to the actual contact, the preferred language is not set as a lookup field, but as a plain text field

**Comment by escopecz** [comment]
Mautic already has that translation functionality and it's connected to the **Preferred Locale** core field.

**Comment by robov** [comment]
The preferred locale is more for the country and has to many options (hence too many possibilities for errors in my use case). But besides how I want to use the lookup... when I would use the lookup for selecting their favorite color.... the lookup itself is not working,

**Comment by npracht** [comment]
closing in favor of https://github.com/mautic/mautic/issues/8331
