### ISSUE TITLE
Impossible to overwrite boolean values through form request.

### ISSUE THREAD

**Issue by yrammos** [mautic/mautic#6764]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

I am following the excellent gist by @escopecz at https://gist.github.com/escopecz/136f62b66d526bc32006f0d2358a8e15 to upload form data via POST request.

Among the key-value pairs that I am uploading in a single request are a few boolean fields. Curiously, it seems impossible to turn boolean fields off to 'false' (or '0' or 'no') if they are already set to 'true' (or '1' or 'yes').

As a result I now have to use an ordinary text field for those values, which is semantically not elegant at all.

This might be related to #6087.

| Q   | A
| --- | ---
| Mautic version | 2.14.2-beta
| PHP version | 7.0.32
| Browser | Any

### Steps to reproduce
1. Create a form with one or more boolean fields in Mautic.
2. Set at least one of these boolean fields to true for a contact.
3. Place a POST request to set the boolean field(s) of step 2 back to false for the said contact. Result: the operation fails and the field stays true.
 
### Log errors

None.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
We actually have test for this scenario. I've run them yesterday several times and this test does not fail.

https://github.com/mautic/api-library/blob/048737f9f82a79cdea8004b6cb9e2bdd970bb4a8/tests/Api/ContactFieldsTest.php#L91

Could you find out whether the test is returning false positive or if the problem is in your code?

**Comment by yrammos** [comment]
@escopecz I'd be happy to try this out but, unless this is a 15-minute affair or something, I cannot prioritize this right now because I'm in the midst of finalizing a production system. Could you outline the testing process or point me to an instructions page? I suppose I need to obtain auth1/auth2 API credentials and make a POST request to a specific endpoint?

**Comment by escopecz** [comment]
I don't think you have to run the test. It takes a little time and some swearing to configure it. I know it passes. I meant rather to look at the code because it has all the accepted boolean values listed in it:

`$possibleValues = array(1 => 1, 0 => 0, 'yes' => 1, 'no' => 0, 'true' => 1, 'false' => 0);`

The array key is the possible value you can use via API and the array value is how Mautic will translate it.

If you find out that there is no flaw in your code compared to the test then we should explore whether the test is correct.

Here is a short tutorial on how to make the tests work: https://github.com/mautic/api-library#unit-tests

**Comment by escopecz** [comment]
BTW what auth method do you use?

**Comment by yrammos** [comment]
@escopecz currently I use none, but I've played around with auth1.

Thanks for the clarification — will retrieve the relevant commit from the history and take a look, hopefully during the day.

**Comment by escopecz** [comment]
I'm not following now.

How did you test it without authentication? Maybe you used Basic Auth?

No need for a commit. I linked to the file with the test in the comment above. Latest version is fine.

**Comment by yrammos** [comment]
Apologies if I was unclear, @escopecz. I was referring to the history of my app's repo, no Mautic's. I need to retrieve an older commit to test this because the app logic has changed. This won't be a problem anyway.

I tested this via an ordinary POST request to a Mautic form, without the API. I am well aware of the weaknesses of this approach but for all intents and purposes it is currently adequate. Your gist at https://gist.github.com/escopecz/136f62b66d526bc32006f0d2358a8e15 served as template.

**Comment by escopecz** [comment]
Ah, right. As I'm involved in more issues my mind get messed up. Form submit POST. Gotcha. There may be a bug in that. We don't have tests for it.

**Comment by yrammos** [comment]
No problem, @escopecz  :) Yes, a bug is most likely because it all worked as soon as I changed the Mautic field type from boolean to text, with no need for changes on the app side.

**Comment by yrammos** [comment]
@escopecz there is more insight into the problem: I am now confident that the issue is linked to erratic POST requests (or to be precise, erratic Mautic behavior to POST requests).

Following the methodology of your gist, the POST request sometimes goes through, sometimes goes through (i.e. the contact is updated in the database) but fails to trigger the expected form action (e.g. email dispatch), and sometimes fails to go through entirely.

This may be linked to CORS, although my CORS settings in Mautic are correct (i.e. enabled and with all relevant domains declared).

This may be linked to the "302 error" that is triggered on every single POST request to the Mautic server:  apparently all Mautic forms issue a redirect, which is unacceptable in cross-domain POST requests. Is there a way to resolve this behavior? I don't see why a redirect is necessary when, for example, the desired form action is to just stay on the same page.

**Comment by escopecz** [comment]
I re-tested and had to add 2 new hidden fields. See my comment bellow the gist:

https://gist.github.com/escopecz/136f62b66d526bc32006f0d2358a8e15#gistcomment-2742206

Let me know if it helped.

**Comment by yrammos** [comment]
I replied on your gist page, @escopecz, but neglected to update this one. My apologies. As explained under your gist, your revision did solve the problem (with the tiny proviso that the `q_` prefixes to the form input names are nowhere to be found in my setup; this however seems unimportant so far). Thank you!

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by yrammos** [comment]
@npracht, for entirely unrelated reasons, I'm not longer using the webpage linked to this issue. Sorry for not being able to help.
