### ISSUE TITLE
Dynamic Content editor broken on 2.14.2-beta.

### ISSUE THREAD

**Issue by yrammos** [mautic/mautic#6766]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.14.2-beta
| PHP version | 7.0.32
| Browser | Safari, Chrome, Firefox

### Steps to reproduce
1. Create new Dynamic Content (**non-campaign** based).
2. Type in the Internal Name and Requested Slot Name, per standard procedure.
3. Click on "Filters".
4. Select any field from the drop-down menu.
5. Result: nothing happens. I **do not** get the expected row of criteria and logical operators to create a filter.

**Actual result**
<img width="1295" alt="screen shot 2018-10-22 at 12 04 59 am" src="https://user-images.githubusercontent.com/1519337/47272421-2b1a0d00-d58e-11e8-9ff6-0641afd51725.png">

**Expected result** (culled from the Mautic website)
<img width="911" alt="fake-at-fake" src="https://user-images.githubusercontent.com/1519337/47272448-906dfe00-d58e-11e8-8d91-f1807bc81eba.png">
 
### Log errors

None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by yrammos** [comment]
Just to add that the browser console produces an error as soon as I select a filter in the dropdown menu:

<img width="1671" alt="screen shot 2018-10-22 at 12 11 30 am" src="https://user-images.githubusercontent.com/1519337/47272489-2a35ab00-d58f-11e8-88e6-b636c6045192.png">

**Comment by Woeler** [comment]
@escopecz Seems this needs some eyes before release.

**Comment by escopecz** [comment]
Was able to reproduce, find PR which caused it and the fix is coming...

**Comment by escopecz** [comment]
I made a fix and created PR but it shows 404 now: https://github.com/mautic/mautic/issues/6767

I cannot create it again as if I try so GH says that it already exists. Let's see if GH wakes up and heals itself. I can understand. Monday morning, right?

**Comment by npracht** [comment]
https://status.github.com/messages ;)

**Comment by yrammos** [comment]
> I made a fix and created PR but it shows 404 now: #6767
> 
> ... if I try so GH says that it already exists. Let's see if GH wakes up and heals itself. I can understand. Monday morning, right?

The essence of 'dynamic web content'. ;)

**Comment by Woeler** [comment]
Yea seems like github ripped
