### ISSUE TITLE
Image inside email content are being included in the attachment section of Gmail

### ISSUE THREAD

**Issue by kamaroolkarim** [mautic/mautic#6768]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The image in the email content is being included in as an attachment part. How can I avoid that? Not all image are included in the attachment section, some of it is not. Little confusing.

![image](https://user-images.githubusercontent.com/6109672/47284109-a7593280-d618-11e8-9603-435c07625a26.png)

![image](https://user-images.githubusercontent.com/6109672/47284065-7416a380-d618-11e8-886c-e39af06e3b79.png)

[](url)

| Q   | A
| --- | ---
| Mautic version | v2.14.1
| PHP version | 7.0
| Browser | Any
| Email Service Provider | Gmail

### Steps to reproduce
1. Create an email
2. Send it to user
3. Open it up using Gmail
4. And the images in the email content, are in attachment section
 
### Log errors
- no errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hello,

This is related to gmail not to any email router. I can also see that with standard sent emails.

**Comment by kamaroolkarim** [comment]
@npracht ok, how do you explain some of the images in the email content, are not included in the attachment section? 

as you can see, these social icons are not included in the attachment section. 

![image](https://user-images.githubusercontent.com/6109672/47406644-f83c6880-d789-11e8-9390-dd54bfc51b9d.png)

**Comment by npracht** [comment]
Hello,

I guess a question of size ? You would better ask your gmail support.
Best !

**Comment by omriasta** [comment]
I am seeing the same behaviour using docker. It seems odd as the same images previously emailed did not get attached and all appeared inline. I think this may be new to version 7. I will test later today with version 6 to see if the issue is present there with the same images....

**Comment by omriasta** [comment]
Still haven't nailed this down...it is also happening in version 6. If I send the email to my personal gmail account and a gmail workspace account, it will display the images in one and not the other interchangably though (1 email shows in workspace but not in personal, and 1 email will show in personal but not in workspace). Very odd behaviour given the emails are identical......

**Comment by omriasta** [comment]
OK, so I was able to get it to work by uploading the images to "assets" and then using the urls from there. But I have to manually paste the urls into the code and not using the builder. I think something may be broken in the way the builder builds urls for images that are uploaded in the builder.
