### ISSUE TITLE
Version 2.14.2 incorrectly reports 2.14.1

### ISSUE THREAD

**Issue by yrammos** [mautic/mautic#6772]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.14.2 (presumably)
| PHP version | 7.0.32
| Browser | Any

### Steps to reproduce
1. Updated self-hosted Mautic from 2.14.1 to 2.14.2 using the UI with no errors reported.
2. Version indication in lower-right corner of the viewport shows 2.14.1
3. Updated via the command line (`sudo -u www-data php app/console mautic:update:apply`) with no errors reported.
4. As before, version shown is still 2.14.1.

In the absence, as far as I know, of an alternative way to retrieve the version number of the installed instance, my only reason for believing the update was at least partially installed is that one of the expected bug fixes seems to be in place.

### Log errors

None.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Helmi** [comment]
yeah it's a known issue. Discussed it with @escopecz on Slack already. Not sure what they're going to do though.

**Comment by yrammos** [comment]
Not a biggie as long as it doesn't signify any silent installation errors... @helmi, could you please confirm that I understood you correctly? Thank you.

**Comment by escopecz** [comment]
Will post my response from Slack:

> It was caused by a bad merge to master. Can't explain it otherwise. It is correct in the release-2.14.2 branch, in the staging (before there was bump to 2.14.3-dev). Only master's AppKernel had bad version. The version.txt file had correct one.

> Anyway, you have the latest 2.14.2 version but it thinks it is on 2.14.1. So you can run the upgrade script once more to fix that.

72 Mautic instances were upgraded with this bug, but it doesn't cause any harm. Sorry that I did not catch this before the release.
