### ISSUE TITLE
email queue spooolfile compression

### ISSUE THREAD

**Issue by pety-dc** [mautic/mautic#6776]
I switched to queued delivery. The emails were generated into the app/spool dir. (>10k)
However with each spoolfile being more than 50k it took almost 1GB of space.
I plan to send even larger segments. With that the amount of space required to temporarily store spool files can go up to multiple of 10GBs

A simple gzip compression would not use much cpu, while it would lower the needed space significantly.

**Comment by kuzmany** [comment]
50k for each file is bug
Look here https://github.com/mautic/mautic/pull/7110

**Comment by pety-dc** [comment]
@kuzmany We are not using `Monitored Inbox feature` and we are not experiencing abnormally large messages like https://github.com/mautic/mautic/pull/7110 describes.

50k for size of an e-mail is rather normal. But 100000 of them takes up many GB of storage. 
And would take less space if compressed. (probably less IO too)

**Comment by RCheesley** [comment]
Closing this issue due to lack of recent engagement and it being a feature request without associated PR.
