### ISSUE TITLE
parallel email sending

### ISSUE THREAD

**Issue by pety-dc** [mautic/mautic#6777]
I currently use "mautic:emails:send" comand to send emails. 
I use queued send (not immediate)
I use custom smtp server
The performance is not too great. So I tried to run this command parallelized with "-f" option. 
In this case however the processes interlap each other and I'm not sure whether mautic sends az email twice or none by mistake.

Is it possible to implement --thead-id and --max-threads options to "mautic:emails:send" command as they are present in "mautic:campaigns:trigger"?

**Comment by RCheesley** [comment]
@pety-dc would you consider making a PR to implement your suggestion, assuming that it is not already there in Mautic 3.x?

**Comment by RCheesley** [comment]
Closing due to lack of response.

**Comment by rashaqqel** [comment]
Any plans for multithread? in this day and age, why not?
