### ISSUE TITLE
Form not redirecting in fresh installation

### ISSUE THREAD

**Issue by ServicedCloud** [mautic/mautic#6779]
| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
We are using self-hosted mautic 2.14.1. Please note that this is also a fresh installation. Upon testing, we noticed that the forms are not redirecting to defined URL that we declared for the form. We are using this form inside Joomla. Then we tried updating to 2.14.2 and the form does not do anything after submission. Any ideas?

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version |  5.6.38

### Steps to reproduce:
1. Mautic 2.14.1 > go to forms
2. on Successful Submit Action > Redirect URL
 
### Log errors: 
Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

**Comment by escopecz** [comment]
Please provide logs. Forms had some troubles on 2.14.1 and the fixes introduced another issue with LIBXML version older than 2.7.8. See https://github.com/mautic/mautic/issues/6783 for more details.

Now you have to tell us what problem it is you are having or if it is something different. If you can provide logs then do so. Otherwise there is nothing we can do to help.

**Comment by ServicedCloud** [comment]
Hi @escopecz, apologies. We have updated our post and pasted the log.

**Comment by escopecz** [comment]
Your error message is explained here:

https://www.mautic.org/docs/en/tips/troubleshooting.html

Let us know if it fixes your issue or if there is something else. Because this problem was not introduced with 2.14.1 nor with 2.14.2. There are [issues about it since 2015](https://github.com/mautic/mautic/issues?q=is%3Aissue+%22%24HTTP_RAW_POST_DATA+is+deprecated%22+is%3Aclosed).

**Comment by ServicedCloud** [comment]
We have applied the solution > always_populate_raw_post_data' to '-1'   but still the form does not redirect. We have also done some research, updated php to version 7. Still redirection does not work.

**Comment by escopecz** [comment]
Upgrade to Mautic 2.14.2 did not help either?

**Comment by ServicedCloud** [comment]
Unfortunately, updating to 2.14.2 does not help either. Please note that we have manually update mautic as updating via ssh stops in "step 2 - extracting package". 

Here are the log that we have after updating to 2.14.2

--------------------

mautic.WARNING: PHP Warning - require_once(PHPEXCEL_ROOTPHPExcel/Shared/PCLZip/pclzip.lib.php): failed to open stream: No such file or directory - in file /vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php - at line 31 [] []
mautic.ERROR: PHP Notice: require_once(): Failed opening required 'PHPEXCEL_ROOTPHPExcel/Shared/PCLZip/pclzip.lib.php' (include_path='.:/opt/cpanel/ea-php70/share/pear') - in file ///vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php - at line 31 [] []
mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Notice: require_once(): Failed opening required 'PHPEXCEL_ROOTPHPExcel/Shared/PCLZip/pclzip.lib.php' (include_path='.:/opt/cpanel/ea-php70/share/pear') - in file ///vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php - at line 31 [] []
mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: require_once(): Failed opening required 'PHPEXCEL_ROOTPHPExcel/Shared/PCLZip/pclzip.lib.php' (include_path='.:/opt/cpanel/ea-php70/share/pear')" at ///vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php line 31 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: require_once(): Failed opening required 'PHPEXCEL_ROOTPHPExcel/Shared/PCLZip/pclzip.lib.php' (include_path='.:/opt/cpanel/ea-php70/share/pear') at ///vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php:31)"} []
mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT c0_.id AS id_0, c0_.name AS name_1, c0_.description AS description_2, c0_.type AS type_3, c0_.event_type AS event_type_4, c0_.event_order AS event_order_5, c0_.properties AS properties_6, c0_.trigger_date AS trigger_date_7, c0_.trigger_interval AS trigger_interval_8, c0_.trigger_interval_unit AS trigger_interval_unit_9, c0_.trigger_hour AS trigger_hour_10, c0_.trigger_restricted_start_hour AS trigger_restricted_start_hour_11, c0_.trigger_restricted_stop_hour AS trigger_restricted_stop_hour_12, c0_.trigger_restricted_dow AS trigger_restricted_dow_13, c0_.trigger_mode AS trigger_mode_14, c0_.decision_path AS decision_path_15, c0_.temp_id AS temp_id_16, c0_.channel AS channel_17, c0_.channel_id AS channel_id_18, c1_.is_published AS is_published_19, c1_.date_added AS date_added_20, c1_.created_by AS created_by_21, c1_.created_by_user AS created_by_user_22, c1_.date_modified AS date_modified_23, c1_.modified_by AS modified_by_24, c1_.modified_by_user AS modified_by_user_25, c1_.checked_out AS checked_out_26, c1_.checked_out_by AS checked_out_by_27, c1_.checked_out_by_user AS checked_out_by_user_28, c1_.id AS id_29, c1_.name AS name_30, c1_.description AS description_31, c1_.publish_up AS publish_up_32, c1_.publish_down AS publish_down_33, c1_.canvas_settings AS canvas_settings_34, c1_.allow_restart AS allow_restart_35, c0_.campaign_id AS campaign_id_36, c0_.parent_id AS parent_id_37, c1_.category_id AS category_id_38 FROM campaign_events c0_ INNER JOIN campaigns c1_ ON c0_.campaign_id = c1_.id INNER JOIN campaign_leads c2_ ON c1_.id = c2_.campaign_id WHERE c1_.is_published = 1 AND c0_.type = ? AND c2_.lead_id = ? AND c2_.manually_removed = 0 AND (c0_.id NOT IN (SELECT c3_.event_id AS sclr_39 FROM campaign_lead_event_log c3_ WHERE c3_.event_id = c0_.id AND c3_.lead_id = c2_.lead_id AND c3_.rotation = c2_.rotation)) AND (c0_.parent_id IS NULL OR (EXISTS (SELECT c4_.id FROM campaign_lead_event_log c4_ WHERE c4_.event_id = c0_.parent_id AND c4_.lead_id = c2_.lead_id AND c4_.rotation = c2_.rotation)))' with params ["form.submit", 12]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.trigger_hour' in 'field list'" at ///vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT c0_.id AS id_0, c0_.name AS name_1, c0_.description AS description_2, c0_.type AS type_3, c0_.event_type AS event_type_4, c0_.event_order AS event_order_5, c0_.properties AS properties_6, c0_.trigger_date AS trigger_date_7, c0_.trigger_interval AS trigger_interval_8, c0_.trigger_interval_unit AS trigger_interval_unit_9, c0_.trigger_hour AS trigger_hour_10, c0_.trigger_restricted_start_hour AS trigger_restricted_start_hour_11, c0_.trigger_restricted_stop_hour AS trigger_restricted_stop_hour_12, c0_.trigger_restricted_dow AS trigger_restricted_dow_13, c0_.trigger_mode AS trigger_mode_14, c0_.decision_path AS decision_path_15, c0_.temp_id AS temp_id_16, c0_.channel AS channel_17, c0_.channel_id AS channel_id_18, c1_.is_published AS is_published_19, c1_.date_added AS date_added_20, c1_.created_by AS created_by_21, c1_.created_by_user AS created_by_user_22, c1_.date_modified AS date_modified_23, c1_.modified_by AS modified_by_24, c1_.modified_by_user AS modified_by_user_25, c1_.checked_out AS checked_out_26, c1_.checked_out_by AS checked_out_by_27, c1_.checked_out_by_user AS checked_out_by_user_28, c1_.id AS id_29, c1_.name AS name_30, c1_.description AS description_31, c1_.publish_up AS publish_up_32, c1_.publish_down AS publish_down_33, c1_.canvas_settings AS canvas_settings_34, c1_.allow_restart AS allow_restart_35, c0_.campaign_id AS campaign_id_36, c0_.parent_id AS parent_id_37, c1_.category_id AS category_id_38 FROM campaign_events c0_ INNER JOIN campaigns c1_ ON c0_.campaign_id = c1_.id INNER JOIN campaign_leads c2_ ON c1_.id = c2_.campaign_id WHERE c1_.is_published = 1 AND c0_.type = ? AND c2_.lead_id = ? AND c2_.manually_removed = 0 AND (c0_.id NOT IN (SELECT c3_.event_id AS sclr_39 FROM campaign_lead_event_log c3_ WHERE c3_.event_id = c0_.id AND c3_.lead_id = c2_.lead_id AND c3_.rotation = c2_.rotation)) AND (c0_.parent_id IS NULL OR (EXISTS (SELECT c4_.id FROM campaign_lead_event_log c4_ WHERE c4_.event_id = c0_.parent_id AND c4_.lead_id = c2_.lead_id AND c4_.rotation = c2_.rotation)))' with params [\"form.submit\", 12]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.trigger_hour' in 'field list' at ///vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.trigger_hour' in 'field list' at ///vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.trigger_hour' in 'field list' at ///vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

**Comment by escopecz** [comment]
This is also explained in https://www.mautic.org/docs/en/tips/troubleshooting.html

Your server is missing the PHP-ZIP extension. Install it, restart server and try again.

**Comment by ServicedCloud** [comment]
Hi again. We enabled php-zip extension. Tried the manual update. Still form redirection is not working.

Here is the log:
---

mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT c0_.id AS id_0, c0_.name AS name_1, c0_.description AS description_2, c0_.type AS type_3, c0_.event_type AS event_type_4, c0_.event_order AS event_order_5, c0_.properties AS properties_6, c0_.trigger_date AS trigger_date_7, c0_.trigger_interval AS trigger_interval_8, c0_.trigger_interval_unit AS trigger_interval_unit_9, c0_.trigger_hour AS trigger_hour_10, c0_.trigger_restricted_start_hour AS trigger_restricted_start_hour_11, c0_.trigger_restricted_stop_hour AS trigger_restricted_stop_hour_12, c0_.trigger_restricted_dow AS trigger_restricted_dow_13, c0_.trigger_mode AS trigger_mode_14, c0_.decision_path AS decision_path_15, c0_.temp_id AS temp_id_16, c0_.channel AS channel_17, c0_.channel_id AS channel_id_18, c1_.is_published AS is_published_19, c1_.date_added AS date_added_20, c1_.created_by AS created_by_21, c1_.created_by_user AS created_by_user_22, c1_.date_modified AS date_modified_23, c1_.modified_by AS modified_by_24, c1_.modified_by_user AS modified_by_user_25, c1_.checked_out AS checked_out_26, c1_.checked_out_by AS checked_out_by_27, c1_.checked_out_by_user AS checked_out_by_user_28, c1_.id AS id_29, c1_.name AS name_30, c1_.description AS description_31, c1_.publish_up AS publish_up_32, c1_.publish_down AS publish_down_33, c1_.canvas_settings AS canvas_settings_34, c1_.allow_restart AS allow_restart_35, c0_.campaign_id AS campaign_id_36, c0_.parent_id AS parent_id_37, c1_.category_id AS category_id_38 FROM campaign_events c0_ INNER JOIN campaigns c1_ ON c0_.campaign_id = c1_.id INNER JOIN campaign_leads c2_ ON c1_.id = c2_.campaign_id WHERE c1_.is_published = 1 AND c0_.type = ? AND c2_.lead_id = ? AND c2_.manually_removed = 0 AND (c0_.id NOT IN (SELECT c3_.event_id AS sclr_39 FROM campaign_lead_event_log c3_ WHERE c3_.event_id = c0_.id AND c3_.lead_id = c2_.lead_id AND c3_.rotation = c2_.rotation)) AND (c0_.parent_id IS NULL OR (EXISTS (SELECT c4_.id FROM campaign_lead_event_log c4_ WHERE c4_.event_id = c0_.parent_id AND c4_.lead_id = //vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT c0_.id AS id_0, c0_.name AS name_1, c0_.description AS description_2, c0_.type AS type_3, c0_.event_type AS event_type_4, c0_.event_order AS event_order_5, c0_.properties AS properties_6, c0_.trigger_date AS trigger_date_7, c0_.trigger_interval AS trigger_interval_8, c0_.trigger_interval_unit AS trigger_interval_unit_9, c0_.trigger_hour AS trigger_hour_10, c0_.trigger_restricted_start_hour AS trigger_restricted_start_hour_11, c0_.trigger_restricted_stop_hour AS trigger_restricted_stop_hour_12, c0_.trigger_restricted_dow AS trigger_restricted_dow_13, c0_.trigger_mode AS trigger_mode_14, c0_.decision_path AS decision_path_15, c0_.temp_id AS temp_id_16, c0_.channel AS channel_17, c0_.channel_id AS channel_id_18, c1_.is_published AS is_published_19, c1_.date_added AS date_added_20, c1_.created_by AS created_by_21, c1_.created_by_user AS created_by_user_22, c1_.date_modified AS date_modified_23, c1_.modified_by AS modified_by_24, c1_.modified_by_user AS modified_by_user_25, c1_.checked_out AS checked_out_26, c1_.checked_out_by AS checked_out_by_27, c1_.checked_out_by_user AS checked_out_by_user_28, c1_.id AS id_29, c1_.name AS name_30, c1_.description AS description_31, c1_.publish_up AS publish_up_32, c1_.publish_down AS publish_down_33, c1_.canvas_settings AS canvas_settings_34, c1_.allow_restart AS allow_restart_35, c0_.campaign_id AS campaign_id_36, c0_.parent_id AS parent_id_37, c1_.category_id AS category_id_38 FROM campaign_events c0_ INNER JOIN campaigns c1_ ON c0_.campaign_id = c1_.id INNER JOIN campaign_leads c2_ ON c1_.id = c2_.campaign_id WHERE c1_.is_published = 1 AND c0_.type = ? AND c2_.lead_id = ? AND c2_.manually_removed = 0 AND (c0_.id NOT IN (SELECT c3_.event_id AS sclr_39 FROM campaign_lead_event_log c3_ WHERE c3_.event_id = c0_.id AND c3_.lead_id = c2_.lead_id AND c3_.rotation = c2_.rotation)) AND (c0_.parent_id IS NULL OR (EXISTS (SELECT c4_.id FROM campaign_lead_event_log c4_ WHERE c4_.event_id = c0_.parent_id AND c4_.lead_id = c2_.lead_id AND c4_.rotation = c2_.rotation)))' with params [\"form.submit\", 12]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.trigger_hour' in 'field list' at //vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.trigger_hour' in 'field list' at //vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c0_.trigger_hour' in 'field list' at //vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []

**Comment by escopecz** [comment]
The database schema is not up to date. See https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful on how to fix it.

**Comment by ServicedCloud** [comment]
Ahh finally it works. Before and after update to 2.14.2, we updated database schema and does fixed the form redirection. For future reference, we updated php to version 7, enabled php-fileinfo and php-zip extension in our server.

Appreciated your help on this, many thanks @escopecz.
