### ISSUE TITLE
Javascript tracking and $request->query->all()

### ISSUE THREAD

**Issue by jrpub** [mautic/mautic#6788]
Hi,

I think I found a bug in the code, but I am not sure (sorry!). 

PHP version: 

`php -v
PHP 5.6.38-0+deb8u1 (cli) (built: Sep 20 2018 02:32:02) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies`

Mautic version: 2.14.2

Symptoms: 

`mt('send', 'pageview', {email: 'toto@test.com'});`

not working.

Potential solution in file PageModel.php, line 792: 
```
/**
     * @param Request            $request
     * @param null|Redirect|Page $page
     *
     * @return array
     */
    public function getHitQuery(Request $request, $page = null)
    {
        if (!isset($query)) {
            // $query = $request->query->all(); // <-------------- Empty array  
            $query = $request->request->all(); // OK
        }
        
        // Set generated page url
        $query['page_url'] = $this->getPageUrl($request, $page);
        
        // Process clickthrough if applicable
        if (!empty($query['ct'])) {
            $query['ct'] = $this->decodeArrayFromUrl($query['ct']);
        }
        
        return $query;
    }
```

I don't know enough the code of Mautic to see if I missed something. But I don't know how $request->query->all() can work as the mt function is POSTing data, could you confirm?

Many thanks

**Comment by escopecz** [comment]
The default Mautic tracking JS is using GET. This is CURL equivalent of the request that my browser is making from the tracking JS:
```
curl 'http://mautic.test/mtc.js' -H 'Referer: http://[censored]' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36' --compressed
```

How did you get to POST?

**Comment by escopecz** [comment]
Good point! I looked into the related code and it hasn't changed for 2 years. I has to use GET params as well because the page hit can come from tracking image. But JS sends POST so I can confirm that I get empty array as you. It should check what HTTP method is used and get the params from the right property. But I can't get my head around how nobody noticed so far.

**Comment by escopecz** [comment]
Well, actually the tracking params work for me. So Mautic must be getting them from the POST request somewhere later on.
![screen shot 2018-10-29 at 11 03 36](https://user-images.githubusercontent.com/1235442/47642954-555d6300-db6a-11e8-92df-82b8f4077cec.png)

Can you double-check that you maybe forgot to set the fields as publicly updatable?

**Comment by jrpub** [comment]
Thank you for these elements. I am also surprised, such a bug would have been seen since a long time I guess! 

However, I retried, and I confirm that I have no information without my custom patch:

![capture](https://user-images.githubusercontent.com/26855134/47660540-843dfe00-db97-11e8-8116-d05f50354dec.png)

Here is the JS command typed and the POST requests sent by the browser: 

![console](https://user-images.githubusercontent.com/26855134/47661010-82c10580-db98-11e8-8a1f-4a3e6b8c89e5.png)

![console2](https://user-images.githubusercontent.com/26855134/47661017-8785b980-db98-11e8-8829-9d619111185c.png)

Also, I confirm that I set the email field as publicly updatable (I checked at least 30 times since yesterday :p). 

I reviewed the code, following the code from the route /mtc/event to the storage (persist/flush of $hit), and i don't see another function where the data is grabbed from the $request. Could you try with your installation with the browser console and see if your mtc.js is sending also the data with a POST request with the same format?  Just to ensure the issue is well on the server-side.

**Comment by escopecz** [comment]
Ok, so I tested once more and cannot make it work again. It's creating new anonymous contact without any param from the request added to it. So I think it's safe to say this is a bug.

Can you send a pull request with your suggestion?

**Comment by Woeler** [comment]
Merged https://github.com/mautic/mautic/pull/6802

**Comment by Woeler** [comment]
I have used this before. Honestly I was just as surprised and confused as you to find out it was broken.

**Comment by YahiaBakour** [comment]
I nominate @jrpub for medal of best bug discovered.

**Comment by jrpub** [comment]
LOL, thanks @YahiaBakour and @escopecz
So proud of it!
