### ISSUE TITLE
Actionevents are not triggered

### ISSUE THREAD

**Issue by MarkKrauss** [mautic/mautic#6789]
What type of report is this:

| Q  | A
| --- | ---
| Bug report? | Yes

## Description:
Through the Mautic API, contacts come into my campaign. About 600 every day. They will receive an email and will be running in other campaigns. They are also waiting for a trigger in this campaign.
The problem: Of the 600, around 30 contacts are **not** directed into the following campaigns and do not receive an email (no action-event is triggerd). Only the (decision-)trigger is still triggered. The decision-trigger sets a tag.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.2 , 2.11
| PHP version | 7.0.32

### Steps to reproduce:
_update_: I could reproduce the problem in our test system. Here a closer description to reproduce:

1. Build a Campain with actionevents and/or conditionevents. As well as a random decisionevent on the same level.
2. Put contact (via API) in campaign
3. Trigger the decisionevent before the cron do the job to trigger action or conditionevent.
4. Let the Cronjob do the job
5. Check contact history. In my case there are no action or conditionevents. Only decisions.
6. Check Database
 6.1. campaign_lead_event_log: Trigger-Event (Decision) is deposited. Action-Event **not**
 6.2. campaign_leads: Contact is deposited

### Log errors: 
Thats the Point. No errors in Logs.

How can I find out why the action events are not triggered?

**Comment by npracht** [comment]
It must be working now
