### ISSUE TITLE
Cannot Open Emails Tab

### ISSUE THREAD

**Issue by CitySearchLocal** [mautic/mautic#6794]
| Bug report? | 

Cannot Open Emails Tab from menubar. Below is error received in log:

## If a bug:

| Q   | A
| --- | ---
| 2.14.2| 
| PHP 7 | 

### Steps to reproduce:
1.  After logging into system I click "Channels" in menubar.
2. Then click "Emails", no visible action occurs.
 
### Log errors: 

"[2018-10-30 10:17:18] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_10 FROM (SELECT m0_.is_published AS is_published_0, m0_.date_added AS date_added_1, m0_.created_by AS created_by_2, m0_.created_by_user AS created_by_user_3, m0_.date_modified AS date_modified_4, m0_.modified_by AS modified_by_5, m0_.modified_by_user AS modified_by_user_6, m0_.checked_out AS checked_out_7, m0_.checked_out_by AS checked_out_by_8, m0_.checked_out_by_user AS checked_out_by_user_9, m0_.id AS id_10, m0_.name AS name_11, m0_.description AS description_12, m0_.subject AS subject_13, m0_.from_address AS from_address_14, m0_.from_name AS from_name_15, m0_.reply_to_address AS reply_to_address_16, m0_.bcc_address AS bcc_address_17, m0_.template AS template_18, m0_.content AS content_19, m0_.utm_tags AS utm_tags_20, m0_.plain_text AS plain_text_21, m0_.custom_html AS custom_html_22, m0_.email_type AS email_type_23, m0_.publish_up AS publish_up_24, m0_.publish_down AS publish_down_25, m0_.read_count AS read_count_26, m0_.sent_count AS sent_count_27, m0_.variant_sent_count AS variant_sent_count_28, m0_.variant_read_count AS variant_read_count_29, m0_.revision AS revision_30, m0_.lang AS lang_31, m0_.variant_settings AS variant_settings_32, m0_.variant_start_date AS variant_start_date_33, m0_.dynamic_content AS dynamic_content_34, m0_.headers AS headers_35 FROM maulx_emails m0_ LEFT JOIN maulx_categories m1_ ON m0_.category_id = m1_.id WHERE m0_.variant_parent_id IS NULL AND m0_.translation_parent_id IS NULL ORDER BY m0_.subject DESC) dctrn_result) dctrn_table':  Unknown column 'm0_.headers' in 'field list'" at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT COUNT(*) AS dctrn_count FROM (SELECT DISTINCT id_10 FROM (SELECT m0_.is_published AS is_published_0, m0_.date_added AS date_added_1, m0_.created_by AS created_by_2, m0_.created_by_user AS created_by_user_3, m0_.date_modified AS date_modified_4, m0_.modified_by AS modified_by_5, m0_.modified_by_user AS modified_by_user_6, m0_.checked_out AS checked_out_7, m0_.checked_out_by AS checked_out_by_8, m0_.checked_out_by_user AS checked_out_by_user_9, m0_.id AS id_10, m0_.name AS name_11, m0_.description AS description_12, m0_.subject AS subject_13, m0_.from_address AS from_address_14, m0_.from_name AS from_name_15, m0_.reply_to_address AS reply_to_address_16, m0_.bcc_address AS bcc_address_17, m0_.template AS template_18, m0_.content AS content_19, m0_.utm_tags AS utm_tags_20, m0_.plain_text AS plain_text_21, m0_.custom_html AS custom_html_22, m0_.email_type AS email_type_23, m0_.publish_up AS publish_up_24, m0_.publish_down AS publish_down_25, m0_.read_count AS read_count_26, m0_.sent_count AS sent_count_27, m0_.variant_sent_count AS variant_sent_count_28, m0_.variant_read_count AS variant_read_count_29, m0_.revision AS revision_30, m0_.lang AS lang_31, m0_.variant_settings AS variant_settings_32, m0_.variant_start_date AS variant_start_date_33, m0_.dynamic_content AS dynamic_content_34, m0_.headers AS headers_35 FROM maulx_emails m0_ LEFT JOIN maulx_categories m1_ ON m0_.category_id = m1_.id WHERE m0_.variant_parent_id IS NULL AND m0_.translation_parent_id IS NULL ORDER BY m0_.subject DESC) dctrn_result) dctrn_table':\n\nUnknown column 'm0_.headers' in 'field list' at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\Mysqli\\MysqliException(code: 0): Unknown column 'm0_.headers' in 'field list' at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:101)"} []"

**Comment by escopecz** [comment]
Your database schema is outdated. See https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful on how to fix that.
