### ISSUE TITLE
Getting activity including specific event also include other events

### ISSUE THREAD

**Issue by scorsi** [mautic/mautic#6795]
## Bug Description

| Q | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.29

When I try to curl on this: `https://my-mautic/api/contacts/activity?filters%5BincludeEvents%5D%5B%5D=email.read`.

I got a lot of `lead.source.identified` and `lead.source.created` events in my result.

I so tried to curl specifying to exclude those `lead.*` events: `https://my-mautic/api/contacts/activity?filters[excludeEvents][]=lead.source.created&filters[excludeEvents][]=lead.source.identified&filters[includeEvents][]=email.read`.

### Steps to reproduce
Simply do a HTTP GET with BasicAuthentication on `https://your-mautic/api/contacts/activity?filters%5BincludeEvents%5D%5B%5D=email.read`.

### Log errors
There's no error strictly speaking. But here is some (censored) data that we obtain by requesting with or without exclude filters: [show in Gist](https://gist.github.com/scorsi/824f18bfe6148fbe4fbb71592cf0df6f).

### One more thing :)
Consequently, we have to directly request the database to get reliable results. We found out where to request to get email.read and email.sent events. But do you know where are stored page.hit events ?

**Comment by escopecz** [comment]
Fixed by https://github.com/mautic/mautic/pull/6149 in 2.14.1.

Please upgrade your Mautic to latest version before posting a bug report.
