### ISSUE TITLE
Calendar stopped working

### ISSUE THREAD

**Issue by DianaCruz16** [mautic/mautic#6796]
Bug Description:
 I have realised that my Calendar have stop updating. A few weeks ago it was working.
![calendar-issue-mautic](https://user-images.githubusercontent.com/44612832/47728241-f2340500-dc2b-11e8-97a4-8b89c612c4cd.PNG)

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0.31

### Steps to reproduce
1. Create a user note
2. Go to Calendar
3. The calendar is empty

I have the same problem with triggered campaigns. Nothing is shown on the calendar.

**Comment by escopecz** [comment]
Could you check if it's related to https://github.com/mautic/mautic/issues/3016?

**Comment by DianaCruz16** [comment]
It is not the same problem. My calendar returns 134 triggered actions and 160 manual actions

**Comment by RCheesley** [comment]
Hi @DianaCruz16 I'm going to close this issue down as we haven't heard anything in some time. If it's still an issue please do add a comment and we'll re-open it.
