### ISSUE TITLE
Email (new and old) 'Apply' and 'Save&Close' is not working

### ISSUE THREAD

**Issue by neshfx** [mautic/mautic#6799]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )
![mautic-screenshot-bug](https://user-images.githubusercontent.com/44573394/47649236-e9d0c100-db7c-11e8-925e-f5393efc9d5d.png)

## Bug Description
I can't edit nor create new email. When I click 'Apply' (or Save & Close), all buttons (Builder, Cancel, Save&Close, Apply) are disabled, and email is not saved. Also through email Builder, when I click 'Apply', every button is disabled until I refresh the page. There are no error messages or logs. 
I found similar issue in earlier Mautic versions, but that was fixed (and probably applied in latest version)?

Mautic is installed through Softaculous.
I've also went through general troubleshooting:
- cleared cache
- permissions checked (all writable)

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 5.6.38
| Browser | Chrome v70.0.3538.77 (Official Build) (64-bit), 

### Steps to reproduce
1. Channels > Emails > New (or Edit existing email) > 
2. Apply (or Save & Close)
or
1. Channels >Emails > New (or Edit existing email) > Builder > Apply 

Same loop happens and email is not saved
 
### Log errors
No error logs on reproducing bug

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by mallegrini** [comment]
Problem solved. Turned out that the hosting provider performed a mod_security update and that caused the problem. Disabling mod_security (for now) fixed the problem. 
Maybe this can help the OP

**Comment by escopecz** [comment]
@neshfx could you check if it isn't the same problem as @mallegrini had? What's the HTTP response code for you?

**Comment by neshfx** [comment]
That was it! Thank you @mallegrini and @escopecz !
