### ISSUE TITLE
Link parsing breaks when <a> tag has line breaks

### ISSUE THREAD

**Issue by Helmi** [mautic/mautic#6800]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
It seems like mautic is unable to recognize a link within the HTML of a message (in this case inserted through code mode) when the <a> tag has line breaks.

Example:
```html
<a
               href="https://example.com/confirmation" style="background:#FFC463;color:#222;font-family:Lato, Arial;font-size:15px;font-weight:700;line-height:1.6;Margin:0;text-decoration:none;text-transform:none;" target="_blank"
            >
              confirm subscription
            </a>
```

this is not being parsed and the mail is sent out without the link being replaced while this works fine:

```html
<a href="https://example.com/confirmation" style="background:#FFC463;color:#222;font-family:Lato, Arial;font-size:15px;font-weight:700;line-height:1.6;Margin:0;text-decoration:none;text-transform:none;" target="_blank">confirm subscription</a>
```

| Q   | A
| --- | ---
| Mautic version | 1.14.2
| PHP version | 7.1.20
| Browser | Chrome 71.0.3578.20 (macOS)

**Comment by escopecz** [comment]
Is this really something that needs fixing? Why do you have a line break after `<a` in the first place?

**Comment by Helmi** [comment]
In this case it's coming out of MJML that way but apart from that it's valid HTML so I guess it needs fixing.

The email looks good in preview, is being sent out without visible distractions so I would say it should also be parsed correctly, don't you think?

**Comment by escopecz** [comment]
I hate MJML then.

It's true that it's valid HTML.

I'll leave it open then, but I'm afraid you'll have to be the one who fix it otherwise it will stay here forever.

**Comment by Helmi** [comment]
ok, don't want to be the idiot that didn't even try to help fixing it. Any hint on where that parsing is happening? Maybe it's just a regex that can be fixed relatively easily. Need to see how I can setup some testing for it and all the stuff, but definitely want to be helpful here.

**Comment by escopecz** [comment]
That's the spirit! I think it's here https://github.com/mautic/mautic/blob/839d619a7ff36a11b5683c6b8f0a7cd6086e3f5e/app/bundles/PageBundle/Model/TrackableModel.php#L329

**Comment by Helmi** [comment]
Sidenote for other people finding this issue: This happens in MJML when copying the generated HTML from the desktop app WITHOUT selecting "Beautify HTML output" in the settings. When the option is selected the HTML code looks just fine and works in Mautic.

**Comment by npracht** [comment]
I'll close this, we have the solution.
