### ISSUE TITLE
Dynamic Content token not fully inserted in email builder

### ISSUE THREAD

**Issue by fuschini** [mautic/mautic#6801]
## Bug Description
When trying to use a Dynamic Content token in a text field using the email builder, the token inserted is only '{dynamiccontent='. The rest of the token that contains the Dynamic Content internal name is ommited.

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.1.23
| Browser | Chrome

### Steps to reproduce
1. Create a new email with any theme that is editable with the email builder (i.e. except the Code one).
2. Add at least a text box and a Dynamic Content. Set the Dynamic Content default value and one variation with its condition.
3. Start editing the text box and try to insert a token from the text editor as below:
![screenshot 5](https://user-images.githubusercontent.com/15579341/47812874-3f959c80-dd28-11e8-8298-aa865c411530.png)
4. Click in the Dynamic Content N (N is the dynamic content number) and the result inserted in the text will be '{dynamiccontent=' only instead of '{dynamiccontent="Dynamic Content N"} '

### Plus info
If you start typing '{dynami...' and click the options in the drop-down shown below, it works and the content inserted is the full dynamic content token '{dynamiccontent="Dynamic Content 3"}'.
![screenshot 6](https://user-images.githubusercontent.com/15579341/47812863-360c3480-dd28-11e8-98c6-09496ad3a41b.png)

 
### Log errors
None.

**Comment by dichvuhuuich** [comment]
Seem this bug is still on mautic 2.15.1, I still can't insert token Dynamic Content I've create in Components> Dynamic content, too.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by JCrangles** [comment]
Hi, I am currently using Mautic 3.2.1 and I am still experiencing this bug. Is there a fix in place for this yet?
