### ISSUE TITLE
In India festivals do not repeat on the same date every year... hence campaign become obsolete.

### ISSUE THREAD

**Issue by Nirind** [mautic/mautic#6803]
Hi,
First of I will like to appreciate the beautiful application that you have developed.
In India we have festivals every year which do not repeat on the same date, hence if we make any campaign to send greetings, the campaign is needed to be edited every year once. 
So can we have a campaign triggered based on an **event calendar list** so that if we change the **event calendar** automatically all the campaigns based on that get corrected.
I don't know if there is any method to cater to this issue for now hence making this a feature request.
Thanks

**Comment by escopecz** [comment]
Are you sending the same messages every year? I think in this case the personal touch once a year is necessary.

And you can always clone the campaigns 10 times and adjust the dates for each year. Then you won't have to configure Mautic for 10 years.

**Comment by Nirind** [comment]
@escopecz thanks for the reply... Cloning 10 different campaigns are highly possible.... but its still manual... campaign triggered by a calender constant would have been better if possible...

**Comment by Woeler** [comment]
But wouldnt that mean we would have to implement constants for every festival in every culture on Earth?

**Comment by npracht** [comment]
Solved with recurring campaigns.
