### ISSUE TITLE
Mautic css problem and send email  to contact problem 

### ISSUE THREAD

**Issue by prakharmonga** [mautic/mautic#6812]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have latest version of mautic and when i go to contacts and try to send e mail it shows the page in a json format (pic attached).
and another thing is when i go to plugins like facebook it shows the page with no css (pic attached)
what could be the problem.
thanks in advance
![mautic error](https://user-images.githubusercontent.com/33699606/47967100-de4f2f80-e07f-11e8-8562-18b9bcb13eea.png)
![mautic error2](https://user-images.githubusercontent.com/33699606/47967102-e5763d80-e07f-11e8-8f71-3c45baec69de.png)

| Q   | A
| OS | Ubuntu 16.04.4 LTS 
| Mautic version | 2.14.2
| PHP version | PHP 7.0.29 
| Browser | chrome

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Please provide proper steps to reproduce. Also create 1 bug report per issue.
