### ISSUE TITLE
remove contact manually from campaign does not work

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6815]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you remove a contact manually from a campaign (by manually I mean, you go to the contact sheet, click on campaign and remove the contact from a campaign), contact will still keep going on the campaign.

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 
| Browser | 

### Steps to reproduce
1. create a campaign like this
![image](https://user-images.githubusercontent.com/31535432/48009131-53bc0e00-e11b-11e8-9a89-67c7296fb91c.png)

2. Publish it and wait for email 1.
3. Open email 1 then wait for email 2.
4. As soon as you received email 2, do not open it, go on your contact sheet.
5. click on campaign
![image](https://user-images.githubusercontent.com/31535432/48009463-11df9780-e11c-11e8-8c9a-58449b40c4ae.png)
6. Remove your contact from this campaign.
![image](https://user-images.githubusercontent.com/31535432/48009520-2facfc80-e11c-11e8-86ff-2bbb6bd044fd.png)
7. Still do not open email 2
8. Wait and see that you will receive email email 3

So the contact should not receive email 3 because he has been removed from the campaign.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
@johbuch could you test it on last mautic staging? because I cannot reproduce it :(

**Comment by johbuch** [comment]
@kuzmany sorry for my late reply, just tested on last staging, I still have the bug

**Comment by johbuch** [comment]
@kuzmany seems to be working with 2.15
