### ISSUE TITLE
Fewer contacts listed in a campaign than it should be (the segment which is used contains 15x more contacts)

### ISSUE THREAD

**Issue by Lewom** [mautic/mautic#6816]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have a segment 'A' with 16692 contacts. I have created a campaign which uses segment 'A' but to date only has 1213 contacts in it (when I tested Mautic with small test segments it didn't work this way, back then all contacts in the segment were added to the campaign). I believe the cause for the issue might be one of the following but I could be wrong: 

- Mautic only adds contacts to the campaign if they've been added to segment A **after** the campaign was created. 

- Since there was over 15000 contacts in the segment when the campaign was published and every contact is scheduled for 30+ events Mautic could've timed out when trying to process the cron job. And  Mautic now believes these contacts have been processed even though they haven't.

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.1.17

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
@Lewom thanks for your message.
I am not sure to understand. All the contacts from a segment get into the campaign, even if added to the segment before the creation of the campaign.

Are you able to reproduce your issue and share a step by step instruction to help us to reproduce also ?

Thanks

**Comment by Lewom** [comment]
Hi @npracht! Thank you for helping me.

What I mean is that all contacts in the used segment are **not** added into the campaign. It seems like only contacts which have been added into the segment **after** the campaign was published has been added into the campaign.

Look here: 
![campaign](https://user-images.githubusercontent.com/39857933/48305652-0f6faa00-e52f-11e8-9b27-453f1604ff15.png)
I published the campaign the 23rd of October and at that time there was about 20000 contacts in the used segment. The first time the cron job updates the campign all these contacts should have had emails scheduled to be sent to them (about 40 events). But as you can see none where scheduled. On October the 30th I realized something was wrong and paused the campaign. The next day a resumed it and as you can see about 700 new contacts are added to the campaign daily, however all the 20000 contacts which already where in the segment when the campaign was published aren't being sent any emails.

To reproduce the issue I suppose you could create a large segment with many events being scheduled. If too many contacts need to be processed by Mautic maybe the server times out, this is only a guess of mine though.

**Comment by npracht** [comment]
Hey, as i told you when i try it works. I'd need clear steps to reproduce. Are you even able to reproduce it yourself in a new campaign ?

**Comment by Lewom** [comment]
@npracht Sorry. I'll do my homework and get back to you with more info :-)
