### ISSUE TITLE
test script to insure a good working caching system

### ISSUE THREAD

**Issue by shulard** [mautic/mautic#6817]
| Q   | A
| --- | ---
| Mautic version | Latest
| PHP version | n/a
| Browser | n/a

The problem was described in 2 issues inside the mautic-wordpress project : 

* https://github.com/mautic/mautic-wordpress/issues/84
* https://github.com/mautic/mautic-wordpress/issues/78

It seems that using Cachewall (or xVarnish) block the forms to load dynamically using the script tag. After some tests, when the script is loaded using the cache system, it's returned with an empty content.

Do you think there is some issue when using Mautic with that kind of system ?

**Comment by npracht** [comment]
@Gregy do you have an opinion ? I'm scared it is only a question of configuration ?

**Comment by shulard** [comment]
I think too, but maybe we can add some warning in the WordPress plugin based on some test that we can execute (trying to load a specific JS file, identify headers, ...) ? This will help the users a lot identifying those non Mautic issues...

**Comment by Gregy** [comment]
This is definitely a configuration issue. We are running mautic behind caching proxy without a problem (not varnish based but I cannot imagine why varnish would not work with proper configuration).

But I think a test script that will detect those problems would definitely be a nice feature.

**Comment by npracht** [comment]
I'll mark that as a feature request then

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
