### ISSUE TITLE
API requires values for required custom select fields even in cases where it should use the default or existing values

### ISSUE THREAD

**Issue by maxSupermoney** [mautic/mautic#6819]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I have a custom field that is required but also has a default value. If I use the API to create or update a contact, it requires a value for that field, otherwise it throws an error "This field is required." If it's a new contact, Mautic should use the default value. If it's an existing contact, Mautic should use the existing value.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0.32

### Steps to reproduce:
1. Create a custom field with data type of select. Make it required and give it a default value
2. Create or update a contact using the API, but do not pass in a value for the new select custom field. You will get a "This field is required" error
 
### Log errors: 
N/A
_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
