### ISSUE TITLE
Migration from 2.12.1 to 2.14.2 fails

### ISSUE THREAD

**Issue by YosuCadilla** [mautic/mautic#6830]
## Bug Description

Launched a migration from within Mautic UI, wen't perfectly through all the steps, including DB migration but got stuck at "finalizing upgrade"

Server become unresponsive.

Deleted cache, no effect.

Apply update manually on CMD returned, Mautic is up to date
Database migrations: Nothing to migrate

doctrine:schema:update --force ended with the following error:

-# php /var/www/html/app/console doctrine:schema:update --force

Updating database schema...

  [Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException]
  An exception occurred while executing 'ALTER TABLE campaign_events_timing ADD CONSTRAINT FK_3002A471F7E88B FOREIGN KEY (event_id) REFERENCES campaign_events (id) ON DELETE CASCADE':

  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`MauticDB`.`#sql-ec5_2db`, CONSTRAINT `FK_3002A471F7E88B` FOREIGN KEY (`
  event_id`) REFERENCES `campaign_events` (`id`) ON DELETE CASCADE)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`MauticDB`.`#sql-ec5_2db`, CONSTRAINT `FK_3002A471F7E88B` FOREIGN KEY (`
  event_id`) REFERENCES `campaign_events` (`id`) ON DELETE CASCADE)

  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`MauticDB`.`#sql-ec5_2db`, CONSTRAINT `FK_3002A471F7E88B` FOREIGN KEY (`
  event_id`) REFERENCES `campaign_events` (`id`) ON DELETE CASCADE)

| PHP version | 
7.0

**Comment by YosuCadilla** [comment]
OH! In case it's useful, this is the output of
# php /var/www/html/app/console doctrine:schema:update --dump-sql

ALTER TABLE assets CHANGE disallow disallow TINYINT(1) DEFAULT NULL;
ALTER TABLE campaigns CHANGE allow_restart allow_restart INT NOT NULL;
CREATE INDEX enroll_date_search ON leads (enroll_date);
CREATE INDEX last_approved_transaction_search ON leads (last_approved_transaction);
CREATE INDEX last_modified_search ON leads (last_modified);
CREATE INDEX starting_credit_score_search ON leads (starting_credit_score);
CREATE INDEX revolving_credit_card_bal_search ON leads (revolving_credit_card_bal);
CREATE INDEX number_of_taxlien_with_ba_search ON leads (number_of_taxlien_with_ba);
CREATE INDEX net_balance_due_search ON leads (net_balance_due);
CREATE INDEX mortgage_accounts_search ON leads (mortgage_accounts);
CREATE INDEX age_of_cancellation_search ON leads (age_of_cancellation);
CREATE INDEX aging_score_search ON leads (aging_score);
DROP INDEX tracking_id ON lead_devices;
CREATE UNIQUE INDEX UNIQ_48C912F47D05ABBE ON lead_devices (tracking_id);
ALTER TABLE user_tokens DROP FOREIGN KEY user_tokens_ibfk_1;
ALTER TABLE user_tokens CHANGE id id INT AUTO_INCREMENT NOT NULL;
DROP INDEX secret ON user_tokens;
CREATE UNIQUE INDEX UNIQ_CF080AB35CA2E8E5 ON user_tokens (secret);
DROP INDEX user_id ON user_tokens;
CREATE INDEX IDX_CF080AB3A76ED395 ON user_tokens (user_id);
ALTER TABLE user_tokens ADD CONSTRAINT user_tokens_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE campaign_events_timing ADD CONSTRAINT FK_3002A471F7E88B FOREIGN KEY (event_id) REFERENCES campaign_events (id) ON DELETE CASCADE;

**Comment by RCheesley** [comment]
Closing this issue as it relates to an outdated migration and the problems mentioned are already reported in other issues.
