### ISSUE TITLE
Input Placeholder is missing for many form fields types

### ISSUE THREAD

**Issue by aymericfrancois** [mautic/mautic#6835]
Hello everyone !

I noticed that many "Input Placeholder" were missing for form fields.

These fields are : 

- Date/Time
- Password
- ~~Phone~~
- Textarea

I already saw the issue from Sept. 2015 for textarea, but maybe there is something to add for the othey types of fields.

**Comment by kuzmany** [comment]
Phone is fixed in 2.14.2 https://github.com/mautic/mautic/pull/6685

**Comment by aymericfrancois** [comment]
What about the other fields ?

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
