### ISSUE TITLE
Mautic deletes .woff2 fonts on theme .zip upload

### ISSUE THREAD

**Issue by AntoniyaM** [mautic/mautic#6838]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
First of all, thank you for your hard work! We're really looking forward to the new release of Mautic.

I'm currently developing a Mautic theme locally. I've set up symfony-encore so I can write SCSS and compile all of my assets. I have a few font-face declarations and all fonts come in 4 different formats: *.eot*, *.ttf*, *.woff* and *.woff2*. We're self-hosting Mautic so as soon as I'm done developing the theme, I zip it up and import it into our Mautic instance. While testing, I noticed that my fonts are being loaded and rendered in all browsers, yet landing pages show 404s on all .woff2 fonts.

So I went back to /themes and downloaded the theme from the UI. When I unzipped it, I discovered that the build folder contained ALL font files EXCEPT all the .woff2s. So it turns out that Mautic deletes these files for whatever reason (maybe while unzipping?), yet the import is always followed by a success message saying that the theme has been imported successfully. Therefore, the user has no idea that files are in fact being ignored.

All Mautic themes I've seen so far were using Google fonts. It seems like no one is serving their own fonts which is why this issue hasn't been reported yet, I suppose.

#### Workaround
I was able to log into the server via SFTP and add the missing files to the build folder. Errors are now gone and all seems to be working fine as usual.

On a side note: have there been any changes in the development timeline of version 3? We would like to fork the new release and start contributing 🙂

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.0.30
| Browser | all

### Steps to reproduce
1. Develop your theme and include the custom fonts you need.
2. Zip your theme up and import it in Mautic.
3. Check your assets folder: all .woff2 files are gone.

**Comment by Woeler** [comment]
Hey, can you test this pr and see if that solves your issues? https://github.com/mautic/mautic/pull/6436

**Comment by AntoniyaM** [comment]
@Woeler thanks for your response! We'll set up a test instance and check out the pr. I'll let you know if it solves our issue and then close this bug report.

**Comment by npracht** [comment]
I am sure it does

**Comment by npracht** [comment]
Merged in 2.15.0

**Comment by dsp76** [comment]
@npracht this seems not to be working. I run 2.15.0 and uploaded a theme via Mautic Backend. The folder /assets/fonts/ was empty - despite being uploaded with the ZIP file.

**Comment by npracht** [comment]
Did you configure in your mautic configuration in asset settings, adding those file extension?
