### ISSUE TITLE
Emails with custom html: empty td elements get a space inside

### ISSUE THREAD

**Issue by ptcc** [mautic/mautic#684]
```html
<td></td>
```
becomes
```html
<td> </td>
```

this changes the way the email is rendered potentially messing the layout

**Comment by alanhartless** [comment]
I found a configuration for the editor we're using that is doing this and will get it into 1.1.3 that I'm working on packaging up now.  It'll be released here soon.

**Comment by alanhartless** [comment]
Fixed with 1.1.3
