### ISSUE TITLE
campaign stats when contacts delete or remove from campaign

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6847]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Campaigns statistic are related to contact that still exist in the instance and that are still in the campaign. If a contact is deleted or removed from the campaign, statistics will be wrong because it will substract from contact that are deleted or removed.

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a campaign like this
![image](https://user-images.githubusercontent.com/31535432/48199013-147c0000-e35b-11e8-924b-b7e0922239e7.png)
2. Add 3 contacts in the segment that starts the campaign.
3. Run the campaign
4. Check the statistics
You can see that graphic as well as the action and decision tab show stats for 3 contacts
![image](https://user-images.githubusercontent.com/31535432/48199151-82c0c280-e35b-11e8-927d-37bdd6c71c4d.png)
![image](https://user-images.githubusercontent.com/31535432/48199157-8b18fd80-e35b-11e8-9e62-38c6565e1c1b.png)
![image](https://user-images.githubusercontent.com/31535432/48199164-91a77500-e35b-11e8-985c-854ba114892b.png)

5. Now delete one contact and refresh the statistic of the campaign.
Graphic shows now only statistics for 2 contacts. Not 3 anymore
![image](https://user-images.githubusercontent.com/31535432/48199406-3924a780-e35c-11e8-9c36-d923ff5e5518.png)
Same thing for the action and decision tab
![image](https://user-images.githubusercontent.com/31535432/48199443-4fcafe80-e35c-11e8-975a-06af8c846059.png)
![image](https://user-images.githubusercontent.com/31535432/48199467-5c4f5700-e35c-11e8-8acd-48c84d517797.png)

6. Now remove manually a contact from the campaign (through contact sheet > campaigns > unpublish to remove the contact) and refresh the campaign stats
See that the graphic did not move (still shows stats for 2 contacts).
But action and decision tab have changed. It now shows stats for only one contact.
![image](https://user-images.githubusercontent.com/31535432/48199629-fadbb800-e35c-11e8-9207-f39d3cb4acc6.png)
![image](https://user-images.githubusercontent.com/31535432/48199641-029b5c80-e35d-11e8-9c70-c7f878ed3883.png)

7. Now for the last contact, remove it from the segment that starts the campaign then refresh again the stats of the campaign.
See that the graphic did not change (still shows stats for 2 contacts).
But see that action and decision tab have changed.
Now, there are no stats.
![image](https://user-images.githubusercontent.com/31535432/48199759-645bc680-e35d-11e8-96dd-dcdce28df78b.png)
![image](https://user-images.githubusercontent.com/31535432/48199768-6a51a780-e35d-11e8-8545-7d657a04a8c3.png)

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
Let's test:  https://github.com/mautic/mautic/pull/6907
It's little complicated, I hope, we are now on good way
