### ISSUE TITLE
click on URL overwrite custom field by default value

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6855]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you have a select field with a default value, then a contact that has a value on this custom field (not default value), when he will click on a link from an email, it will reset this field with the default value.

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a select field with some value. Add a default value to this field
![image](https://user-images.githubusercontent.com/31535432/48256859-26b87580-e411-11e8-9672-f30c56d2a5fb.png)
2. Create a contact and add a value to this field (not the default one).
3. Create a segment email, add a link and send it to this contact
4. When received the email, open it.
5. Refresh the contact sheet, see the line email opened. See that nothing changed in the audit log tab.
6. Now go back in the email and click on the link.
7. Refresh the contact sheet. See the page visit and check the audit log tab. See that the custom field has been overwritten with default value.
![image](https://user-images.githubusercontent.com/31535432/48257252-48fec300-e412-11e8-86bd-fc8d6b47e9ca.png)
![image](https://user-images.githubusercontent.com/31535432/48257268-587e0c00-e412-11e8-975f-9ef7fc25c255.png)

I can see that the bug is also for a text field that has a default value

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
@johbuch I guess this should fix it https://github.com/mautic/mautic/pull/6829 
Can you test it with that PR?

**Comment by Woeler** [comment]
Merged https://github.com/mautic/mautic/pull/6829
