### ISSUE TITLE
Bug: Weekday scheduling Campaign new feature v2.14.2

### ISSUE THREAD

**Issue by Marketpedia** [mautic/mautic#6857]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The new feature "Schedule Weekdays" in campaigns is not working.  It fires all the campaigns at once even if they were scheduled for later dates.

| Q   | A
| --- | ---
| Mautic version |   v2.14.2
| PHP version |    7.0.32
| Browser |   Chrome

### Steps to reproduce
1.   This campaign is a 10-Day drip campaign (see screenshot below).  One email should fire per day.  The Weekday feature is turned on for M-F.  But as the screenshots below show, they are firing every 1 minute instead
SCHEDULED:  https://marketpedia.net/BingAdsCampaign.png
TRIGGERED ALL AT ONCE:  https://marketpedia.net/BingAdsCampaignTrigger.png
ARRIVED IN INBOX 1 MINUTE APART:  https://marketpedia.net/BingAdsCampaignInbox.png

2.  On the other hand, this is a different 10-day drip campaign but it is not using the "Weekday" feature.  As you can see, it fires correctly as expected:  https://marketpedia.net/ScheduleFB.png
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hello @Marketpedia could you please try https://github.com/mautic/mautic/pull/6822 and see if it fixes your issue ?

Thanks !

**Comment by npracht** [comment]
I'm pretty sure Alan's fixes solve the issue. I'll reopen if you say that it does not after your tests.
