### ISSUE TITLE
THERE APPEARS TO BE AN ERROR WITH THE CONFIGURATION

### ISSUE THREAD

**Issue by publiko** [mautic/mautic#6858]
Hello,
I just had the fresh Installed. I have also connected the Mautic with this using the API as mentioned in the Doc. Everything seems to be well configured.

Now I am looking for adding the my contacts (who register on WordPress) to Mautic. I tried adding the rule as below.

Trigger – User Register on WordPress
Action – Add to Segment

But when I click on Add to segment it show the error “THERE APPEARS TO BE AN ERROR WITH THE CONFIGURATION”. But i couldn’t find out what is wrong with confriguration

Can you let me know what i am doing wrong?

**Comment by escopecz** [comment]
Can you make a screenshot and drop it here? Do you have any error in the logs? See https://www.mautic.org/docs/en/tips/troubleshooting.html for basic troubleshooting.

**Comment by publiko** [comment]
SOLVED!

The solution is to go in:
> Configuration
> API Settings
> DISABLE Basic HTTP Authentication

Thanks!!
