### ISSUE TITLE
[Feature] Changes to campaigns notification

### ISSUE THREAD

**Issue by zapur1** [mautic/mautic#686]
When editing a campaign it would be good if when closing the campaign builder it shows a pop-over with information about what the changes to the campaign will do to existing leads in the campaign.

At its simplest it could just show the message only when it would specifically affect leads currently in the campaign (e.g. it only shows the message if leads will be affected), the extension would be to say what actions would be taken and against what leads for each.

It would make the questions around what changes to a campaign in progress affect non-existent as well.
Thanks,
Zac

**Comment by alanhartless** [comment]
I think we can merge this one into #580.

**Comment by zapur1** [comment]
#580 doesn't really capture what I'm meaning. I'm thinking more along the lines of "This save will affect x many leads", x wouldn't just be the number of leads in the campaign it would be the number that would have an action acted upon. It is basically to meant to make it harder to make changes that might break or reemail all leads in a campaign

**Comment by alanhartless** [comment]
Ah gotcha. I would consider this different then so reopened.
