### ISSUE TITLE
Cannot edit default neither add a new variant to a dynamic content block in email builder

### ISSUE THREAD

**Issue by soyfifu** [mautic/mautic#6866]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Cannot edit the default variant neither add a new variant to a Dynamic Content block in the email builder.

I add a Dynamic Content block on the builder. When I click on it, I cannot customize the slot because the slot content/editor is missing. If I click on Add Variant, nothing happens.

![imagen](https://user-images.githubusercontent.com/35385706/48368375-8ddc6100-e681-11e8-83d9-47df341c530c.png)

And after I close the builder and reopen it, the dynamic content block is replaced by this: {dynamiccontent="undefined"}

![imagen](https://user-images.githubusercontent.com/35385706/48368195-173f6380-e681-11e8-873a-b38e522b9423.png)

And the weird Dynamic Content tag merges with the existing blocks above.

| Q   | A
| --- | ---
| Mautic version | v2.14.2 
| PHP version | 7
| Browser | Chrome, Firefox

### Steps to reproduce
1. Create a new template email
2. Drag a Dynamic Content block
3. Click on the recently added Dynamic Content block
4. Try to add a new variant
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by urbunuk** [comment]
Exact same here - Chrome

Mautic Version v 2.15.14

Was this supposedly resolved?

**Comment by mxeise** [comment]
Same here

Chrome
Mautic v2.15.1
PHP Version 7.0.33

Is there a workaround?

**Comment by marcchristopher** [comment]
Very similar problem here: In my case, I'm in **code mode** and not only the slot content (as shown in the screenshot above) is missing, but that whole tab doesn't show up, which means that the button `Add Variant` doesn't even exist.
I remember that this worked without problems in an older version, so I'm guessing a recent update must have caused this. Not sure, which one, though

Browser: Chrome and Firefox
Mautic Version 2.15.3
PHP Version 7.2.27

Any help would be much appreciated.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
