### ISSUE TITLE
campaign does not detect any contact

### ISSUE THREAD

**Issue by neurohost** [mautic/mautic#6868]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

I am creating a segment with contacts that do not have any activity and contacts that your last email reading was 2 months ago

this with the aim of keeping my bd clean

then I create a campaign to send emails to confirm that they are still active and wish to receive our newsletters

but when trying to run the campaign, I do not load any contact of the created segment, the segment if it detects my contacts, but the campaign does not

| Q   | A
| --- | ---
| Mautic version | 2.14.0
| PHP version | 7.0.32
| Browser |  chrome

### Steps to reproduce
1. create new segment
1.1- date last active less than or equal -2 months
           --and email not empty
or

      date last active empty
           --and email not empty

2. create new campaign to send email to the previous segment created

Error

the campaign does not detect any contact, although the segment does detect them perfectly

Abrir en Google Traductor | Comentarios
-- | --

 
### Log errors
[2018-11-12 14:37:35] mautic.WARNING: PHP Warning - array_flip() expects parameter 1 to be array, null given - in file /home/***/***********/app/bundles/CampaignBundle/Controller/SourceController.php - at line 142 [] []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Can you make sure that your cron jobs are working properly? Other campaigns are working for you? What happens if you run the `app/console mautic:campaigns:update` command yourself?

**Comment by neurohost** [comment]
> Can you make sure that your cron jobs are working properly? Other campaigns are working for you? What happens if you run the `app/console mautic:campaigns:update` command yourself?

Sorry for the delay, cron jobs work, but running those campaigns with mautic: campaigns: update does not detect contacts

the segment with which I work, I am filtering it with

date last active empty
and email not empty

after executing the campaign I get the following error

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 81 bytes) in /home/name/name/app/bundles/LeadBundle/Entity/CustomFieldRepositoryTrait.php on line 92

**Comment by escopecz** [comment]
Increase PHP memory limit at least to 500MB. 134MB is too low for Mautic.
