### ISSUE TITLE
PHP Fatal error in 1.1.3 version installing

### ISSUE THREAD

**Issue by BrunoSette** [mautic/mautic#687]
Tried to install the new version but got an error: 

PHP Fatal error:  require(): Failed opening required '/var/www/html/mautic/app/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/mautic/app/autoload.php on line 9

**Comment by alanhartless** [comment]
Is this on an upgrade or a fresh install? 

If on an upgrade, can you check the upgrade folder to see what's left in it? Also look to see if there is an upgrade_errors.txt file.  It sounds like maybe file permissions didn't allow the upgrade scripts to copy all the files.

**Comment by BrunoSette** [comment]
It is a new install.

**Comment by alanhartless** [comment]
Does /var/www/html/mautic/vendor/autoload.php exist and if so, does it have readable file permissions for the web user?

**Comment by BrunoSette** [comment]
it doesn't exists

**Comment by alanhartless** [comment]
K; then it sounds like maybe not all the files were uploaded as I've verified the file does exist in the package.  Can you try reuploading/extracting? You can also try using our Single Page Installer option https://github.com/mautic/mautic-spi.  Just upload start.php to your web server, hit it up in the browser, and it'll fetch and extract the package for you.

**Comment by BrunoSette** [comment]
I think is some kind of folder permission problems... what are the folders that I need to chmod?

**Comment by BrunoSette** [comment]
I did reinstall and it worked, thank you very much!

**Comment by alanhartless** [comment]
Great! Thanks!

**Comment by escopecz** [comment]
Maybe read https://github.com/mautic/mautic#getting-started
