### ISSUE TITLE
RabbitMQ Click Counts Not Working

### ISSUE THREAD

**Issue by mtasuandi** [mautic/mautic#6874]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hi!

I use RabbitMQ on the queue protocol, and I use the one provided by cloudamqp.com for testing. I also run these command:

* php app/console mautic:queue:process -e prod -i page_hit
* php app/console mautic:queue:process -e prod -i email_hit

The email read counts work perfectly but the click counts is not tracked if I look at the data on the Email Segment Dashboard (https://site.co/s/emails/view/1). No matter how many times I clicked the link when I open the email, the click counts will always zero.

But the weird part is, if I look the history of my account (https://site.co/s/contacts/view/1), I can see some record if I clicked the link already.

When I look at the database, if I disabled the queue protocol, on table page_hits, the redirect_id is NOT NULL. But if I use RabbitMQ, the redirect_id will always NULL.

I'm using incognito mode when opening the email and clicking the link, I also try to use different browser and ask my friend to check on her side, but still, the click counts only increased if I disabled the queue protocol.

I see quite similar issue #6718 but it didn't mention RabbitMQ.

So, to make it clear, the click counts was recorded on contact history (https://site.co/s/contacts/view/1), but its not increased on the email segment dashboard (https://site.co/s/emails/view/1).

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | PHP 7.1.24
| Browser | Google Chrome

### Steps to reproduce
1. Create New Email Segment
2. Send Email
3. Open Email
4. Click Link
 
### Log errors
No error log.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by mtasuandi** [comment]
This is the click counts on my email segment dashboard.

![5](https://user-images.githubusercontent.com/2455314/48411131-37e7e600-e773-11e8-95d1-68809d3aaf20.png)

As you can see here, the click counts is recorded.

![6](https://user-images.githubusercontent.com/2455314/48411166-56e67800-e773-11e8-9ac0-f9d43a6dc411.png)

Note:
I already cleaned up the cookie and I'm not using admin email to test the click counts.

**Comment by mtasuandi** [comment]
It seems like it also happens for Beanstalkd, I try to use Beanstalkd instead of RabbitMQ but the click counts still not increased.

**Comment by mtasuandi** [comment]
Update:

I try to debug isUniquePageHit in Mautic\PageBundle\Entity\HitRepository, it return true if I disable the Message Queue but it return false if I use RabbitMQ or Beanstalkd.

**Comment by mtasuandi** [comment]
Update:

This code:

`$pageRepo               = $this->em->getRepository('MauticPageBundle:Page');`
`$pageRepo->find((int) $pageId)`

at `app/bundles/PageBundle/EventListener/PageSubscriber.php` (line 192 & 195, staging branch) return null if I use Message Queue. I have no idea why.

The `$pageId` has a value.

**Comment by mtasuandi** [comment]
Update:

So, the problem with this issue is because mautic try to send `$page` that only comes from Page Entity, it didn't look for Redirect Entity.

My solution is to update file `app/bundles/PageBundle/EventListener/PageSubscriber.php` to:

```
use Mautic\PageBundle\Entity\Page;
```

On function `onPageHit`:

```
$redirectRepo           = $this->em->getRepository('MauticPageBundle:Redirect');

$page = null;
if ($pageId) {
    $foundPage = $pageRepo->find((int) $pageId);

    if ($foundPage instanceof Page) {
        $page = $foundPage;
    } else {
        $page = $redirectRepo->find((int) $pageId);
    }
}
```

**Comment by kuongknight** [comment]
I found same issue!

**Comment by mtasuandi** [comment]
@djeraseit Which version did you use?

You can try to compare with this `https://github.com/mautic/mautic/blob/2.14.2/app/bundles/PageBundle/EventListener/PageSubscriber.php`.

**Comment by kuongknight** [comment]
I found something new: @mtasuandi you should logout mautic when try click link in email...

**Comment by mtasuandi** [comment]
I always open my link in separate Incognito browser. What was the issue?

**Comment by gabfr** [comment]
> Update:
> 
> So, the problem with this issue is because mautic try to send `$page` that only comes from Page Entity, it didn't look for Redirect Entity.
> 
> My solution is to update file `app/bundles/PageBundle/EventListener/PageSubscriber.php` to:
> 
> ```
> use Mautic\PageBundle\Entity\Page;
> ```
> On function `onPageHit`:
> 
> ```
> $redirectRepo           = $this->em->getRepository('MauticPageBundle:Redirect');
> 
> $page = null;
> if ($pageId) {
>     $foundPage = $pageRepo->find((int) $pageId);
> 
>     if ($foundPage instanceof Page) {
>         $page = $foundPage;
>     } else {
>         $page = $redirectRepo->find((int) $pageId);
>     }
> }
> ```

It worked like a charm. You should drop that snippet into a PR!

Thanks!

**Comment by mtasuandi** [comment]
@gabfr You can send PR based on my snippet if you want. :smile_cat:

**Comment by kuongknight** [comment]
was fixed this issue in 2.15?

**Comment by remorozadarrel** [comment]
i do have same issue when upgrade to 2.14. Is this fixed?

**Comment by gabfr** [comment]
@kuongknight @remorozadarrel I don't think it's fixed. At least I didn't sent any PR about the fix up above.

Anyway, the quick workaround is in this reply:

> So, the problem with this issue is because mautic try to send $page that only comes from Page Entity, it didn't look for Redirect Entity.
> 
> My solution is to update file `app/bundles/PageBundle/EventListener/PageSubscriber.php` to:

```php
use Mautic\PageBundle\Entity\Page;
```

> On function `onPageHit`:

```php
$redirectRepo           = $this->em->getRepository('MauticPageBundle:Redirect');

$page = null;
if ($pageId) {
    $foundPage = $pageRepo->find((int) $pageId);

    if ($foundPage instanceof Page) {
        $page = $foundPage;
    } else {
        $page = $redirectRepo->find((int) $pageId);
    }
}
```

**Comment by remorozadarrel** [comment]
@gabfr tried it but still the click count not working. is this correct?

`   public function onPageHit(QueueConsumerEvent $event)
    {
        $payload                = $event->getPayload();
        $request                = $payload['request'];
        $trackingNewlyGenerated = $payload['isNew'];
        $pageId                 = $payload['pageId'];
        $leadId                 = $payload['leadId'];
        $hitRepo                = $this->em->getRepository('MauticPageBundle:Hit');
        $pageRepo               = $this->em->getRepository('MauticPageBundle:Page');
        $leadRepo               = $this->em->getRepository('MauticLeadBundle:Lead');
        $hit                    = $hitRepo->find((int) $payload['hitId']);
        $page                   = $pageId ? $pageRepo->find((int) $pageId) : null;
        $lead                   = $leadId ? $leadRepo->find((int) $leadId) : null;

        $redirectRepo           = $this->em->getRepository('MauticPageBundle:Redirect');

        $page = null;
        if ($pageId) {
            $foundPage = $pageRepo->find((int) $pageId);
        
            if ($foundPage instanceof Page) {
                $page = $foundPage;
            } else {
                $page = $redirectRepo->find((int) $pageId);
            }
        }

        $this->pageModel->processPageHit($hit, $page, $request, $lead, $trackingNewlyGenerated, false);
        $event->setResult(QueueConsumerResults::ACKNOWLEDGE);
    }`

**Comment by mtasuandi** [comment]
@remorozadarrel Can you copy paste the whole file here?

**Comment by remorozadarrel** [comment]
@mtasuandi 

`<?php

/*
 * @copyright   2014 Mautic Contributors. All rights reserved
 * @author      Mautic
 *
 * @link        http://mautic.org
 *
 * @license     GNU/GPLv3 http://www.gnu.org/licenses/gpl-3.0.html
 */

namespace Mautic\PageBundle\EventListener;

use Mautic\CoreBundle\EventListener\CommonSubscriber;
use Mautic\CoreBundle\Helper\IpLookupHelper;
use Mautic\CoreBundle\Model\AuditLogModel;
use Mautic\CoreBundle\Templating\Helper\AssetsHelper;
use Mautic\PageBundle\Event as Events;
use Mautic\PageBundle\Model\PageModel;
use Mautic\PageBundle\PageEvents;
use Mautic\QueueBundle\Event\QueueConsumerEvent;
use Mautic\QueueBundle\Queue\QueueConsumerResults;
use Mautic\QueueBundle\QueueEvents;
use Mautic\PageBundle\Entity\Page;

/**
 * Class PageSubscriber.
 */
class PageSubscriber extends CommonSubscriber
{
    /**
     * @var AssetsHelper
     */
    protected $assetsHelper;

    /**
     * @var AuditLogModel
     */
    protected $auditLogModel;

    /**
     * @var IpLookupHelper
     */
    protected $ipLookupHelper;

    /**
     * @var PageModel
     */
    protected $pageModel;

    /**
     * PageSubscriber constructor.
     *
     * @param AssetsHelper   $assetsHelper
     * @param IpLookupHelper $ipLookupHelper
     * @param AuditLogModel  $auditLogModel
     * @param PageModel      $pageModel
     */
    public function __construct(
        AssetsHelper $assetsHelper,
        IpLookupHelper $ipLookupHelper,
        AuditLogModel $auditLogModel,
        PageModel $pageModel
    ) {
        $this->assetsHelper   = $assetsHelper;
        $this->ipLookupHelper = $ipLookupHelper;
        $this->auditLogModel  = $auditLogModel;
        $this->pageModel      = $pageModel;
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents()
    {
        return [
            PageEvents::PAGE_POST_SAVE   => ['onPagePostSave', 0],
            PageEvents::PAGE_POST_DELETE => ['onPageDelete', 0],
            PageEvents::PAGE_ON_DISPLAY  => ['onPageDisplay', -255], // We want this to run last
            QueueEvents::PAGE_HIT        => ['onPageHit', 0],
        ];
    }

    /**
     * Add an entry to the audit log.
     *
     * @param Events\PageEvent $event
     */
    public function onPagePostSave(Events\PageEvent $event)
    {
        $page = $event->getPage();
        if ($details = $event->getChanges()) {
            $log = [
                'bundle'    => 'page',
                'object'    => 'page',
                'objectId'  => $page->getId(),
                'action'    => ($event->isNew()) ? 'create' : 'update',
                'details'   => $details,
                'ipAddress' => $this->ipLookupHelper->getIpAddressFromRequest(),
            ];
            $this->auditLogModel->writeToLog($log);
        }
    }

    /**
     * Add a delete entry to the audit log.
     *
     * @param Events\PageEvent $event
     */
    public function onPageDelete(Events\PageEvent $event)
    {
        $page = $event->getPage();
        $log  = [
            'bundle'    => 'page',
            'object'    => 'page',
            'objectId'  => $page->deletedId,
            'action'    => 'delete',
            'details'   => ['name' => $page->getTitle()],
            'ipAddress' => $this->ipLookupHelper->getIpAddressFromRequest(),
        ];
        $this->auditLogModel->writeToLog($log);
    }

    /**
     * Allow event listeners to add scripts to
     * - </head> : onPageDisplay_headClose
     * - <body>  : onPageDisplay_bodyOpen
     * - </body> : onPageDisplay_bodyClose.
     *
     * @param Events\PageDisplayEvent $event
     */
    public function onPageDisplay(Events\PageDisplayEvent $event)
    {
        $content = $event->getContent();

        // Get scripts to insert before </head>
        ob_start();
        $this->assetsHelper->outputScripts('onPageDisplay_headClose');
        $headCloseScripts = ob_get_clean();

        if ($headCloseScripts) {
            $content = str_ireplace('</head>', $headCloseScripts."\n</head>", $content);
        }

        // Get scripts to insert after <body>
        ob_start();
        $this->assetsHelper->outputScripts('onPageDisplay_bodyOpen');
        $bodyOpenScripts = ob_get_clean();

        if ($bodyOpenScripts) {
            preg_match('/(<body[a-z=\s\-_:"\']*>)/i', $content, $matches);

            $content = str_ireplace($matches[0], $matches[0]."\n".$bodyOpenScripts, $content);
        }

        // Get scripts to insert before </body>
        ob_start();
        $this->assetsHelper->outputScripts('onPageDisplay_bodyClose');
        $bodyCloseScripts = ob_get_clean();

        if ($bodyCloseScripts) {
            $content = str_ireplace('</body>', $bodyCloseScripts."\n</body>", $content);
        }

        // Get scripts to insert before a custom tag
        $params = $event->getParams();
        if (count($params) > 0) {
            if (isset($params['custom_tag']) && $customTag = $params['custom_tag']) {
                ob_start();
                $this->assetsHelper->outputScripts('customTag');
                $bodyCustomTag = ob_get_clean();

                if ($bodyCustomTag) {
                    $content = str_ireplace($customTag, $bodyCustomTag."\n".$customTag, $content);
                }
            }
        }

        $event->setContent($content);
    }

    /**
     * @param QueueConsumerEvent $event
     */
    public function onPageHit(QueueConsumerEvent $event)
    {
        $payload                = $event->getPayload();
        $request                = $payload['request'];
        $trackingNewlyGenerated = $payload['isNew'];
        $pageId                 = $payload['pageId'];
        $leadId                 = $payload['leadId'];
        $hitRepo                = $this->em->getRepository('MauticPageBundle:Hit');
        $pageRepo               = $this->em->getRepository('MauticPageBundle:Page');
        $leadRepo               = $this->em->getRepository('MauticLeadBundle:Lead');
        $hit                    = $hitRepo->find((int) $payload['hitId']);
        $page                   = $pageId ? $pageRepo->find((int) $pageId) : null;
        $lead                   = $leadId ? $leadRepo->find((int) $leadId) : null;

        $redirectRepo           = $this->em->getRepository('MauticPageBundle:Redirect');

        $page = null;
        if ($pageId) {
            $foundPage = $pageRepo->find((int) $pageId);
        
            if ($foundPage instanceof Page) {
                $page = $foundPage;
            } else {
                $page = $redirectRepo->find((int) $pageId);
            }
        }

        $this->pageModel->processPageHit($hit, $page, $request, $lead, $trackingNewlyGenerated, false);
        $event->setResult(QueueConsumerResults::ACKNOWLEDGE);
    }
}
`

**Comment by mtasuandi** [comment]
Maybe it was cached, you can try to remove the cache.

**Comment by remorozadarrel** [comment]
@mtasuandi will try to clear cache will keep you posted.

**Comment by remorozadarrel** [comment]
@mtasuandi @gabfr i click the link on incognito browser that solve the problem, with the code change you propose. 

https://www.mautic.org/docs/en/pages/troubleshooting.html

**Comment by KennedyTedesco** [comment]
Same issue here. :( It doesn't work with queues.

**Comment by mtasuandi** [comment]
@KennedyTedesco Have you tried the solution above?

**Comment by mtasuandi** [comment]
@KennedyTedesco Did you open the email from Incognito? Your issue might be the same as @phwebdeveloper.

**Comment by KennedyTedesco** [comment]
@mtasuandi I'll give a try soon. Thanks! This issue is really annoying. Wish I could fix it, but just started using Mautic recently. Maybe someone else does. 🙏

**Comment by dennisgon** [comment]
i also found this issue. i already clear di cache and nothing happens 
can someone please help me thanks

**Comment by mtasuandi** [comment]
@dennisgon Did you open the email from incognito browser?

**Comment by dennisgon** [comment]
> @dennisgon Did you open the email from incognito browser?

nope i opened through my browser

**Comment by mtasuandi** [comment]
@dennisgon Mautic will not record read counts and click counts if you open the link at the same browser where you logged in. See https://www.mautic.org/docs/en/pages/troubleshooting.html

**Comment by iurisilvio** [comment]
The workaround worked for me too. Thanks!

**Comment by w4mana** [comment]
JFY, there is another issue related to the same method, with an existing PR:
https://github.com/mautic/mautic/pull/6983/files/618b350e023635627a7419d3dfa4630b0dee2698

**Comment by Lipdk** [comment]
JFY, there is another issue related to the same method, with an existing PR:
https://github.com/mautic/mautic/pull/6983/files/618b350e023635627a7419d3dfa4630b0dee2698

**Comment by RCheesley** [comment]
Would someone mind making a PR for this if it's not covered by the one shared above, as it seems to have resolved the problem for quite a few people?

**Comment by RCheesley** [comment]
@mtasuandi could you possibly make a PR with the fix you mentioned if it's still relevant in Mautic 3.x ?

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
