### ISSUE TITLE
file manager issue with picture link button

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6879]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
There is a problem in the file manager (where all pictures are stored). 
When you clik on the link button to copy the link of the picture, then you paste it: 
- on Mac: there is nothing to paste
- on windows: only the relative link is pasted

| Q   | A
| --- | ---
| Mautic version | 2.12
| PHP version | 
| Browser | 

### Steps to reproduce
1. create or edit an email or landing page
2. go in the file manager to see all picture you have stored
3. choose your picture and click on the link button to copy the URL of the picture
![image](https://user-images.githubusercontent.com/31535432/48471705-cc465d00-e7f4-11e8-8e09-0c051bb75e86.png)
4. Try to paste it
As said previously, if you're on mac, it won't paste anything, if you're on windows it will paste only the relative link.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
I believe this will be addressed if not already fixed with the new file manager so closing it down.
