### ISSUE TITLE
Unexpected field alias reset when updating form data through REST API

### ISSUE THREAD

**Issue by patryk-gruszka-ca** [mautic/mautic#6887]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When form is updated through `PUT` `/forms/{id}/edit` all fields should be overrided with new data. 
Sumbiting form fields with existing aliases causes unexpected behavior - resetting them to some random values. 

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.0.32
| Browser | None

### Steps to reproduce
1. Create new form using `POST` `/forms/new` endpoint with data:
```
{
    "name": "Test",
    "formType": "standalone",
    "description": "API test",
    "fields": [
        {
            "label": "field name",
            "alias": "custom_alias",
            "type": "text"
        }
    ],
    "actions": []
}
```
2. Update created form using `PUT` `/forms/{id}/edit` with same data
3. Field alias is resetted to some random value
4. Updating form again will change field alias again to correct value

 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Woeler** [comment]
I have written a very extensive integration with Mautic forms and this issue bugged me at some point as well. This is however, not a bug. The alias is not the UID of the form field. You must supply the form field ID in your request. If you do so, the field will be updated. If you don't a new field will be created and the old field will be regarded as removed.
```
{
    "name": "Test",
    "formType": "standalone",
    "description": "API test",
    "fields": [
        {
            "id": 1,
            "label": "field name",
            "alias": "custom_alias",
            "type": "text"
        }
    ],
    "actions": []
}
```
