### ISSUE TITLE
Changing form name through REST API makes its submissions inaccessible

### ISSUE THREAD

**Issue by patryk-gruszka-ca** [mautic/mautic#6890]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Changing form name through REST API generates new form alias which is used in database table name with submission results. When generated alias is not the same as before then new database table is created and previous sumbissions are not available in API and Mautic panel.

Note: form alias in request body is ignored. There is no way to set this property through REST API.

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.0.32
| Browser | none

### Steps to reproduce
1. Create new form in Mautic panel or using `POST` `/forms/new` with data:
```
{
    "name": "Test",
    "formType": "standalone",
    "fields": [
        {
            "label": "field name",
            "type": "text"
        }
    ],
    "actions": []
}
```
2. Add some form submissions
4. Change form name through REST API using `PUT` or `PATCH` `/forms/{id}/edit`. Important: change first 10 characters. Example request data for `PATCH`:
```
{
    "name": "Changed test"
}
```
5. New form results table is created. Previous submissions are not available.
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Woeler** [comment]
Confirmed, we should not update the alias unless specifically in the request.

**Comment by Woeler** [comment]
https://github.com/mautic/mautic/blob/staging/app/bundles/FormBundle/Controller/FormController.php#L578

**Comment by Woeler** [comment]
I'll have a look at it tonight. Ideally this parameter should never be changed.

**Comment by Woeler** [comment]
@patryk-gruszka-ca Please test https://github.com/mautic/mautic/pull/6894

**Comment by Woeler** [comment]
Okay, now it's ready to test https://github.com/mautic/mautic/pull/6894
