### ISSUE TITLE
Page Hit events missing Page URL & other critical fields

### ISSUE THREAD

**Issue by azupancich** [mautic/mautic#6897]
What type of report is this: Bug report

## Description:
Mautic event receiving detailed data, not storing it in database; leaving necessary fields such as Page URL, blank.

Here's a pic of the creation of a contact
https://i.imgur.com/6YoRIkR.png
Notes:
Contact is created from data placed in an outgoing email including:
UTM Campaign:
UTM Medium:
UTM Source:
Email address
Firstname:
Lastname:
Omsid (custom field)
These are all populated correctly in the contact record in the db.

Subsequent page hits come up like this:
https://i.imgur.com/ZmCon93.png

Time on page: **Unknown**
Referrer: **Unknown**
Page URL: **Unknown**
Device Name: smartphone
Device OS: iOS
Device Brand: AP
Device Model: iPhone
Email: ########
Firstname: #######
Lastname: #######
Omsid: #####
Utm Source: OMS
Utm Medium: email

The data about page URL, referrer, etc is being sent to the /mtc/event so this is definitely an issue with the mautic installation, not the client or tracking code.

NO users have any of the above 'unknown' data saved into the database.

I confirmed the /mtc/event is receiving the requests (also obvious because the customer & device data is getting stored into the page hit event)
https://i.imgur.com/jDvdK81.png

And I can see that on the pages, the appropriate data is being sent in the post to the mautic event handler:
https://i.imgur.com/d9HbSn9.png
Form data being sent:
page_title: Declaration from the Dean of JDMIS
page_language: en-GB
page_referrer: 
page_url: http://jdmis.edu.sg/our-commitment-to-quality/declaration-from-the-dean.html
counter: 0
mautic_device_id: null
resolution: 2560x1440
timezone_offset: -480
platform: Win32
do_not_track: 1
adblock: false
fingerprint: 2e8a41dd4838a5026cfb26d8bc5e0edd

## If a bug:
| Mautic version 2.14.2| 
| PHP version 7.0.32 | 

### Steps to reproduce:
Look at *ANY* contact - all page hits are missing critical data
 
### Log errors: 
No Log errors (log contains errors from update due to memory limit set too low - but fixed after setting memory limit to 512MB)

**Comment by escopecz** [comment]
Can you test if https://github.com/mautic/mautic/pull/6802 fixes your issue?

**Comment by azupancich** [comment]
Hi John!
Thanks for the suggestion. I was SO hopeful this would get it working...

I updated the PageModel.php file
(code now reads as follows:

```
public function getHitQuery(Request $request, $page = null)
    {
        $get  = $request->query->all();
        $post = $request->request->all();
        $query = array_merge($get, $post);

        // Set generated page url
        $query['page_url'] = $this->getPageUrl($request, $page);

        // Process clickthrough if applicable
        if (!empty($query['ct'])) {
            $query['ct'] = $this->decodeArrayFromUrl($query['ct']);
        }

        return $query;
    }
```


This did NOT solve the problem - but now seems to have introduced a NEW problem
I am still not getting any data about the page url or other critical information
PLUS
The data that used to be saved in the correct fields is now being saved in the wrong field:
https://i.imgur.com/UxvJtAP.png

ie: DeviceOS field contains EMAIL
Email field contains FirstName
FirstName contains LastName
etc...

**Comment by azupancich** [comment]
Just an update

It seems like the transposed fields is not an issue related the the change from #6802 
I found other records were the fields are correct but there is still no recording of the page url and other information that makes the hit record actually useful...
https://i.imgur.com/T0H8vIn.png

**Comment by escopecz** [comment]
The issue that values and labels are swapped may be just a view issue. I bet it's correct in the database. We just need to find out in what case this happens so we could fix it. If you could find the problematic page hit in your database and provide it as INSERT query that would help a developer to fix it.

The original issue is that **Page Hit URL** is not recorded. Is that correct? I don't understand how the rest of the values is being stored without the fix in #6802.

Do you test tracking in a incognito browser? Not in the browser you are logged in to Mautic?

**Comment by azupancich** [comment]
Hi escopecz.

I looked back at the post data from the beginning of this issue and realize it was NOT from an incognito window - but I had been doing my tests before writing the issue in an incognito window.

Just to clarify, since I mentioned the post from the beginning of the issue, I thought I would submit the post data made from an incognito window with a proper fingerprint....  maybe something was missing or mis-configured that more adept techs such as yourself might notice:

```
Content-Type: application/x-www-form-urlencoded
DNT: 1
Origin: http://jdmis.edu.sg
Referer: http://jdmis.edu.sg/jewellery-education/jdmis-location.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
X-Requested-With: XMLHttpRequest
page_title: JDMIS Location
page_language: en-GB
page_referrer: jdmis.edu.sg
page_url: http://jdmis.edu.sg/jewellery-education/jdmis-location.html
counter: 0
mautic_device_id: kdpiesij5kubfl6qj8ksyxk
resolution: 2560x1440
timezone_offset: -480
platform: Win32
do_not_track: 1
adblock: false
fingerprint: 2e8a41dd4838a5026cfb26d8bc5e0edd
```


Thanks again!

**Comment by azupancich** [comment]
Reposting this issue with more relevant information in #6909 in an effort to make issue more readable.
Also consolidating with issue #6904 which I believe is related.
