### ISSUE TITLE
Form edit or creation does not generate the form HTML code properly

### ISSUE THREAD

**Issue by CGREFF** [mautic/mautic#6903]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.14.2 | 
| PHP version | 5.6.30 | 

### Steps to reproduce
1. Access Mautic menu path Components -> Forms
2. Edit a form (standalone or campaign)
3. Clique on the button "Save & Close"
4. In the next screen clique on the button "Manual Copy" in the frame named Form HTML
5. The form "Manual Copy" shows only the javascript frame, no HTML frame, according to screenshot below.

Important: No error message is displayed.

![mautic](https://user-images.githubusercontent.com/45183858/48738407-10dc5900-ec38-11e8-86a1-ef2e53c8e013.png)

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Woeler** [comment]
This fix has already been merged for the next version https://github.com/mautic/mautic/pull/6785
