### ISSUE TITLE
A question regarding re-adding contacts to campaigns with the "Allow contacts to restart the campaign" setting set to "No"

### ISSUE THREAD

**Issue by Lewom** [mautic/mautic#6906]
Hi!

I tried to find the answer to this question in the docs but could'nt find them.

If the "Allow contacts to restart the campaign" is set to "No". What happens if a contact is re-added to a campaign that they never completed? Let's say that the segment which the contact is in was removed from the campaign and then re-added a few days later. Will the contact, when re-added to the campaign, continue where he/she left off? Or will this particular contact not take part in the campaign?

**Comment by escopecz** [comment]
Such contact will continue where he left off. Please ask questions in [other channels](https://www.mautic.org/support/) this is for bug tracking.
