### ISSUE TITLE
Page Hit Data Missing Page URL & Other critical fields for Identified users, but recording data for anonymous users

### ISSUE THREAD

**Issue by azupancich** [mautic/mautic#6909]
## Bug Description
This was previously referenced in issues #6897  and #6904 

After reading more about other user's activities I noticed that the two above issues seem to be the same. I am therefore closing those issues and opening a new one with up-to-date information.

Situation:
Mautic **CORRECTLY** records page hit data for ANONYMOUS visitors.
![capture1](https://user-images.githubusercontent.com/17508411/48816121-e2679680-ed7b-11e8-9f60-88f3f3ec414a.JPG)

**BUT**, when we include a tracking image with customer data in an email, and the user is 'identified' then ALL subsequent page hits are MISSING data about the page URL and other valuable/critical information.
![capture2](https://user-images.githubusercontent.com/17508411/48816132-eabfd180-ed7b-11e8-9d1d-1ede668770c4.JPG)
![capture3](https://user-images.githubusercontent.com/17508411/48816135-ed222b80-ed7b-11e8-9529-81d7216dd460.JPG)

We record user data when we send an email to a known user:
`http://ma.mydomain.com/mtracking.gif?email=an@email.com&firstname=bob&lastname=smith&omsid=123`
OMS ID is a custom field referencing our CRM system

I updated the PageModel.php file as per issue #6802 but we still have the **SAME** issue - new visits from identified/able users contain 'unknown' page hit data.
PageModel.php code now reads as follows:
```
public function getHitQuery(Request $request, $page = null)
    {
        $get  = $request->query->all();
        $post = $request->request->all();
        $query = array_merge($get, $post);

        // Set generated page url
        $query['page_url'] = $this->getPageUrl($request, $page);

        // Process clickthrough if applicable
        if (!empty($query['ct'])) {
            $query['ct'] = $this->decodeArrayFromUrl($query['ct']);
        }
        return $query;
    }
```
I can confirm page hits are being fired from client with relevant post data
```
Content-Type: application/x-www-form-urlencoded
DNT: 1
Origin: http://jdmis.edu.sg
Referer: http://jdmis.edu.sg/jewellery-education/jdmis-location.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
X-Requested-With: XMLHttpRequest
page_title: JDMIS Location
page_language: en-GB
page_referrer: jdmis.edu.sg
page_url: http://jdmis.edu.sg/jewellery-education/jdmis-location.html
counter: 0
mautic_device_id: kdpiesij5kubfl6qj8ksyxk
resolution: 2560x1440
timezone_offset: -480
platform: Win32
do_not_track: 1
adblock: false
fingerprint: 2e8a41dd4838a5026cfb26d8bc5e0edd
```

I can confirm post data is being received by server in logs
![jdvdk81](https://user-images.githubusercontent.com/17508411/48767033-b8b55d80-ecf0-11e8-9936-a22ddae30765.png)

(both the above points are self-evident since anonymous records have the page data properly recorded.)

Possibly related to this issue is issue #6904 where, sometimes, in subsequent 'identified' users there is a transposition of the labels or fields such that the DeviceOS label shows the identified email, the email label shows the contacts first name, etc. This does not happen consistently for all identified users and all users have the correct label/field mappings at the time of identification - it is only in some subsequent page hit events that the transposition occurrs, and only on some occasions: here is an example of a user where the transposition occurs for SOME page hits and not for others (NOTE: the page hit is still ALWAYS recorded as 'unknown' making the data being collected much much much less useful.
![capture5](https://user-images.githubusercontent.com/17508411/48817782-12fefe80-ed83-11e8-9f31-6c5f22a517b9.JPG)
![capture6](https://user-images.githubusercontent.com/17508411/48817787-1abea300-ed83-11e8-927b-42c7b87bde04.JPG)
![capture7](https://user-images.githubusercontent.com/17508411/48817793-201bed80-ed83-11e8-8d0e-00408440cae4.JPG)

| Q   | A
| --- | ---
| Mautic version | Previous Versions and 2.14.2
| PHP version | 7.0.32
| Browser | All (NO user, once identified via tracking pixel, gets any data

### Log errors
No relevant log errors (ie: no errors recurring with the same frequency as the lack of data of page hits.):
`[2018-11-18 15:37:25] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO lead_ips_xref (lead_id, ip_id) VALUES (?, ?)' with params [40035, 13048]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '40035-13048' for key 'PRIMARY'" at /home/xxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO lead_ips_xref (lead_id, ip_id) VALUES (?, ?)' with params [40035, 13048]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '40035-13048' for key 'PRIMARY' at /home/xxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '40035-13048' for key 'PRIMARY' at /home/xxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '40035-13048' for key 'PRIMARY' at /home/xxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
`

**Comment by azupancich** [comment]
Hi, I would love to help to get this to work... unfortunately I am not familiar with how to start debugging the issue. If someone needs more data, or can guide me on how to dig deeper I am ready to help!
Thanks!

In the meantime, I can confirm 2 things:

1. Data is NOT being stored in the database for page hits:
![onpaste 20181129-183018](https://user-images.githubusercontent.com/17508411/49215956-e98a4680-f404-11e8-913f-67f6b54544b0.png)
![onpaste 20181129-183312](https://user-images.githubusercontent.com/17508411/49216123-3d952b00-f405-11e8-860b-30044555a615.png)

2. Transcribed data described is being stored properly in the lead table... 
![image](https://user-images.githubusercontent.com/17508411/49216287-abd9ed80-f405-11e8-9f18-713e3054f253.png)

**Comment by azupancich** [comment]
I am not sure if this helps - but I have set up webhooks for the hit event, and the webhooks are also returning the same data; ie: page url info for anonymous users and MISSING page data for identified users.
It appears wherever the bug is, it is BEFORE the webhook is being fired.

**Comment by azupancich** [comment]
> The error mentioned in this PR should be fixed by #6836, but I don't think that's the cause of the described problem.

Thanks for remembering this issue!

I just updated the 8 files identified in #6836, deleted the cache and restarted the server.
It appears that the above changes do not have an impact of the storing of data on identified contacts.
![onpaste 20181201-140039](https://user-images.githubusercontent.com/17508411/49324855-82d66b80-f571-11e8-9b8d-b425eb198e58.png)
(Before and after change, hit data still missing important data such as page...)

**Comment by escopecz** [comment]
Could you please re-test with the latest Mautic version? I cannot replicate and I don't see anyone else reporting such issue.

**Comment by Talbatz** [comment]
@escopecz i'm experiencing the same issue. i'd be happy to provide more info , and i'll be happy for any help. In our case, the same code is embeded in few websites, one of them is a react app - in which case page hits get **time on page: unknown**

**Comment by YosuCadilla** [comment]
@Talbatz Are you on a bitnami install too?
I've seeing the same problem on a bitnami install too...
@azupancich Did you find a solution for your issue?
