### ISSUE TITLE
Date translatable filters are being converted to fixed dates when the report is saved.

### ISSUE THREAD

**Issue by cesarjr** [mautic/mautic#6912]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you create a report having date filters using translatable expressions, when you save the report, Mautic is converting to a fixed date.

See the example before saving the report.

![image](https://user-images.githubusercontent.com/824198/48860345-d0035200-eda7-11e8-8eaf-f849770e60aa.png)

Now when I edit the report again.

![image](https://user-images.githubusercontent.com/824198/48860359-d7c2f680-eda7-11e8-9631-b491789a2aec.png)

This behavior is not consistent with the segment filters.

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.1.20
| Browser | Chrome

### Steps to reproduce
1. Create a new report using "Form submissions" as Data source.
2. Select some columns.
3. Add a filter using the "Date submitted" column.
4. Select the condition "equals".
5. In the value field, fill with "today" (do not use quotes).
6. Save the report.
7. Edit the report again.
8. Inspect the value field of filter. You will see a date instead of the expression "Today". 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by luizeof** [comment]
I believe Reports don't use same filters that segments for date and datetime fields.

Segments has some extra logic with date and datetime fields. [Here](https://github.com/mautic/mautic/blob/2642e21c0da8049f3e183d0566d1bca9a14ffab9/app/bundles/LeadBundle/Entity/LeadListRepository.php#L811)

Reports don't have same login with any specific date types [Here](https://github.com/mautic/mautic/blob/master/app/bundles/ReportBundle/Builder/MauticReportBuilder.php#L394)

**Comment by luizeof** [comment]
@npracht @heathdutton this could be a feature on 2.15.0 or 2.16.0?

**Comment by npracht** [comment]
This is not a bug, just a feature not developed for reports.

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
