### ISSUE TITLE
Emails can be sent even with Viewer permissions only.

### ISSUE THREAD

**Issue by srdecny** [mautic/mautic#6915]
## Bug Description
When having an user account with permissions only for View, that user account can still send example emails and emails to contact. With Viewer permissions only, user shouldn't be able to interact with the system in any way.

| Q   | A
| --- | ---
| Mautic version | 2.14.12 (but shows up on staging branch too)
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a new contact and new email.
2. Create new test user account with permissions only to View emails and users.
3. Log in with this new account.
4. The new contact can be sent emails to.
5. The new email can be sent as an example.
 
### Steps to fix the bug
In case this issue turns out to be a bug and not an intended behaviour, I'm actively interested in fixing it and creating a PR eventually.

One possible solution is to create new permission option named "Send" for Contacts and Emails. Another one might be to "reuse" some current permission setting, such as "Edit". Or perhaps there's another, more suitable way?

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
