### ISSUE TITLE
dashboard issue when clicking on cancel

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#6916]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
In the dashboard, if you edit a widget then you don't want to save it, you click on cancel, it will save and not cancel.

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 
| Browser | 

### Steps to reproduce
1. Go to the dashboard
2. Edit a widget
![image](https://user-images.githubusercontent.com/31535432/48899261-6c346400-ee4f-11e8-843b-942ab677fe8e.png)
3. Here is my widget. It is the map
![image](https://user-images.githubusercontent.com/31535432/48899276-75bdcc00-ee4f-11e8-8216-bf368416ccc7.png)
4. I changed to another type of widget. Top submission referrer for example
![image](https://user-images.githubusercontent.com/31535432/48899298-84a47e80-ee4f-11e8-8318-b29339118962.png)
5. I click on cancel
![image](https://user-images.githubusercontent.com/31535432/48899316-94bc5e00-ee4f-11e8-9b35-9307af801293.png)
See that it has been saved because I have not anymore the map (even if I clicked on cancel).
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
I am unable to reproduce this in 2.16 beta - please feel free to add further details if this is still an issue for you.
