### ISSUE TITLE
Users see checkboxes and dropdown arrow in lists even though they can't do anything with them..

### ISSUE THREAD

**Issue by srdecny** [mautic/mautic#6917]
## Bug Description
Users with insufficient permissions can still see the mass action checkbox and dropdown menu, even though they can't do anything with them. See attached image for illustration.
![example](https://user-images.githubusercontent.com/7964806/48899989-6b9ccd00-ee51-11e8-9574-b2d639104106.gif)

| Q   | A
| --- | ---
| Mautic version | 2.14.2 (but issue shows up on staging too)
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a new user account with Campaign permissions set to View own/others only.
2. Create a new campaign.
3. Log in with the new user account.
4. The checkbox for mass actions and dropdown arrow still shows up, even though the avaliable actions are empty.

This bug also shows up for practically every Mautic item, such as Contacts, Marketing Messages.

In case this issue turns out to be a bug and not an intended behaviour, I'm actively interested in fixing it and creating a PR eventually.

**Comment by Woeler** [comment]
I can't see how this would not be a bug.

**Comment by cyanstar** [comment]
I've recently had a similar issue. It turned out to be a JS error. Deleting the following files and letting mautic reproduce them resolved the issue for me. (backup the files before deleting these just in case this isn't the issue)

media/js/app.js
media/js/libraries.js
media/js/mautic-form.js
media/js/mautic-form-src.js

**Comment by srdecny** [comment]
@cyanstar Unfortunately, that didn't solve my issue. I'll try to make a PR soon.

**Comment by cyanstar** [comment]
@srdecny It might help if i read the steps for reproducing this error. This actually is working as it's supposed to right now.

```
Suggested fix:
When a user does not have edit, clone, delete, publish or full permissions either:
A. Inject 'hidden' class into the list_accounts.html.php views
OR 
B. Inject a 'nopermissions' class into the <table> and add a the following to the below CSS.

.table-responsive .nopermissions td .input-group {display:none;}
```

I don't have a copy of Mautic on a dev server at the moment to see which files need updating. Sorry >_<.

**Comment by srdecny** [comment]
@cyanstar I was thinking about not rendering the buttons at all, when there aren't any. Something like:

```php
<?php
	$templateButtons = [
	'edit'   => $permissions['campaign:campaigns:edit'],
	'clone'  => $permissions['campaign:campaigns:create'],
	'delete' => $permissions['campaign:campaigns:delete'],
	];
?>
<tr>
   <?php if (!empty(array_search(true, $templateButtons))): ?>
	    <td>
		<?php
		echo $view->render(
		    'MauticCoreBundle:Helper:list_actions.html.php',
		    [
		        'item'            => $item,
		        'templateButtons' => $templateButtons,
		        'routeBase' => 'campaign',
		    ]
		);
		?>
	    </td>
    <?php endif; ?>
(...)
</tr>
```
But your version will work too. I guess it's up to the core team to decide what solution they prefer. I do have the list of files that need to change, so don't worry about that.

**Comment by cyanstar** [comment]
@srdecny I'd use your option. Cleaner and doesn't output a bunch of useless CSS into the front end. PHP isn't my strong suite but slowly learning :).

As for your code, i'd change it slightly. As it stands that would hide the buttons for everyone even if they had permissions. I'd also place the PHP IF statement inside the table cells as not to break the front end UI.

The below works for the most part, but does throw an error if the role doesn't have the view permission. Not really sure how to get around it, as the view permission should be mandatory if they can edit, create or delete something, no? Not really should how you can edit something if you can't view it!

```
 <td>
    <?php if ($permissions['campaign:campaigns:view'] = 0 ):

    elseif ($permissions['campaign:campaigns:full'] || $permissions['campaign:campaigns:edit'] || $permissions['campaign:campaigns:create'] || $permissions['campaign:campaigns:delete']):
        echo $view->render(
            'MauticCoreBundle:Helper:list_actions.html.php',
            [
                'item'            => $item,
                'templateButtons' => [
                    'edit'   => $permissions['campaign:campaigns:edit'],
                    'clone'  => $permissions['campaign:campaigns:create'],
                    'delete' => $permissions['campaign:campaigns:delete'],
                ],
                'routeBase' => 'campaign',
            ]
        );

    endif;
    ?>

</td>
```

**Comment by srdecny** [comment]
@cyanstar That code would display the Edit/Clone/Delete buttons even though the user actually has permissions only for one or more of these actions.

Hiding the column containing the dropdown menu/checkboxes is not always possible, since some Mautic entities have separate Edit Own/Edit Others permissions, so it's possible to have the dropdown menu only next to some entitites.

I'm not sure what you mean by the 403 issue - when a user doesn't have View permissions for an entity, the entity menu is not displayed in the left menu at all. If the user tries to access the entity menu directly, he gets a 403, which is IMHO a correct behavior.

Your point about Edit/etc. permissons not granting View permission automatically is an interesting one. While it definitely makes sense from user perspective, I believe it's correct to not "automatically" alter permissions, since then you can't fully trust the system that it will do what you want - you'll lose transparency.
I can imagine a warning popping up when attempting to save a role with Edit/etc. permissions without View permissions, but that's a separate issue/PR :)

**Comment by cyanstar** [comment]
@srdecny The code i placed above does work. Mautic already hides the separate options depending on the permissions given via 'edit'  "$permissions['campaign:campaigns:edit']" etc. All I've done is hide the entire drop-down if the user doesn't have any permissions. The IF statement i added looks for the permissions a user can have, 'Full/Edit/View/Clone/Delete' and if none are true it displays nothing. If any of them are true it outputs the drop-down list, and Mautic automatically filters the options depending on the users permissions.

That's why i moved the code around the button specifically. You're previous code hid the table column which lead to front end issues.

The 403 is correct, but i do think the view option should be linked to the other options. IE you can have the view only options, but if you grant edit permissions it should automatically check the view one. After all, it's already impossible to edit it if you can't view it as it gives you the 403 error. But yes, that's a separate PR.

**Comment by RCheesley** [comment]
Did we get anywhere with making a PR to resolve this issue @cyanstar @srdecny ?

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
