### ISSUE TITLE
FatalThrowableError (Mautic 2.14.2 & SuiteCRM 7.10.10)

### ISSUE THREAD

**Issue by bbnes66** [mautic/mautic#6922]
## Bug Description
The connection plugin gives an error (see at the end for the exact error) when trying to sync an updated contact from Mautic to SuiteCRM. 

| Mautic 2.14.2  
| SuiteCRM 7.10.10 |
| PHP 7.0 | 
|Google Chrome | 

### Steps to reproduce
1. activate the plugin and choose:
- Triggered action push contacts to integration
- Pull contacts and/or companies from integration
- Push contacts and/or companies to this integration
2. choose also to pool at least "leads"
3. map (at least) email address and last name
4. create a lead in Mautic
5. give the following command through the console:
    php -f console mautic:integration:synccontacts --integration="Sugarcrm" --time-interval="2 hours"
6. go to SuiteCRM and you'll see that the contact has been created
7. update the contact created in Mautic
8. give again the command:
    php -f console mautic:integration:synccontacts --integration="Sugarcrm" --time-interval="2 hours"
9. you'll see the error in the console output
 
I want to add that the proble is in the line 897:
"$this->fetchDncToMautic($entity, $data);"

If I substitute this line with the following:
"if ($entity != null) ($this->fetchDncToMautic($entity, $data));"

the error desappears but then SuiteCRM DUPLICATES the lead insetad of simply updating it.
So it keeps on creating/duplicating leads, every time a lead is updated in Mautic.

### Log error:
[Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                         Type error: Argument 1 passed to MauticPlugin\MauticCrmBundle\Integration\SugarcrmIntegration::fetchDncToMautic() must be an instance of Mautic\LeadBundle\Entity\Lead, null given, called in /home/caldaiaa/public_html/mktautom2.brandandclients.it/plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php on line 897

**Comment by ebogaard** [comment]
To expand on the description:
* when a Contact is matched by e-mail address, this error happens
* if there is no e-mail address, so a Contact can't be matched, no error is show, but contact is duplicated.

**Comment by ebogaard** [comment]
Just figured out why this is happening:
1. In the plug-in config, configure a number of fields.
1. Make the arrows of those fields all point in the direction of the CRM, none to Mautic
1. Run the sync-command, and you'll see that if there are changed Contacts in the CRM, the fatal error is thrown.
1. Change (at least) one of the arrows and let it point to Mautic.
1. Run the sync-command again and it will succesfully finish.

It seems that if there are no fields configured to have priority over Mautic, the array "$fieldsToUpdateInMautic" stays empty, and, in the end, a fatal error is thrown.

You'll find this variable at: https://github.com/mautic/mautic/blob/ff43f35e74523312182b13dfd81c1e6faefb2784/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php#L431

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
