### ISSUE TITLE
email swtiching

### ISSUE THREAD

**Issue by ibeliever** [mautic/mautic#6924]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description
Is there any possible way of switching between ESP depending upon the email domain.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
There isn't. Please use [other channels](https://www.mautic.org/support/) to ask questions. This is for bug reports only.
