### ISSUE TITLE
API error getSubmissions and orderBy

### ISSUE THREAD

**Issue by purplizer** [mautic/mautic#6926]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When you use the form api, and try to order by a field, the server throws an error because the $orderBy value is changed: fs. gets added to the front. If this doesn't happen, the sql query would execute normally

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 
| Browser | 

### Steps to reproduce
1.  Call $formApi->getSubmissions -> no problem, works as expected
2.  Call $formApi->getSubmissions and set $orderBy to a field of the results. In my case r.naam, and it changes this to fs.r.naam
 
### Log errors
`[2018-11-26 14:04:53] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT r.submission_id, s.date_submitted as dateSubmitted, s.lead_id as leadId, s.referer, i.ip_address as ipAddress, voornaam,r.naam,r.emailadres,r.uit_welke_provincie_ben_j,r.land,r.voor_welke_infosessie_wen,r.met_hoeveel_personen_kom,r.hoe_heb_je_ons_leren_kenn,r.nieuwsbrief_kandidaatstud,r.nieuwsbrief_overzicht,r.in_welke_opleidingen_ben1,r.mailakkoord FROM form_results_1_infodag_nl r INNER JOIN form_submissions s ON r.submission_id = s.id LEFT JOIN ip_addresses i ON s.ip_id = i.id WHERE r.form_id = 1 ORDER BY fs.r.naam asc LIMIT 500 OFFSET 0': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fs.r.naam' in 'order clause'" at /var/www/mautic.ap.be/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT r.submission_id, s.date_submitted as dateSubmitted, s.lead_id as leadId, s.referer, i.ip_address as ipAddress, voornaam,r.naam,r.emailadres,r.uit_welke_provincie_ben_j,r.land,r.voor_welke_infosessie_wen,r.met_hoeveel_personen_kom,r.hoe_heb_je_ons_leren_kenn,r.nieuwsbrief_kandidaatstud,r.nieuwsbrief_overzicht,r.in_welke_opleidingen_ben1,r.mailakkoord FROM form_results_1_infodag_nl r INNER JOIN form_submissions s ON r.submission_id = s.id LEFT JOIN ip_addresses i ON s.ip_id = i.id WHERE r.form_id = 1 ORDER BY fs.r.naam asc LIMIT 500 OFFSET 0':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'fs.r.naam' in 'order clause' at /var/www/mautic.ap.be/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fs.r.naam' in 'order clause' at /var/www/mautic.ap.be/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fs.r.naam' in 'order clause' at /var/www/mautic.ap.be/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Woeler** [comment]
I am pretty sure you can only order it by properties of the submission object such as `date_submitted` and not by the actually submitted values.

**Comment by purplizer** [comment]
> I am pretty sure you can only order it by properties of the submission object such as `date_submitted` and not by the actually submitted values.

That doesn't work either. That changes the query to fs.date_submitted while it should be s.date_submitted

**Comment by Woeler** [comment]
That is indeed a bug. I'll see if I can fix that this weekend.

**Comment by Woeler** [comment]
The docs are correct, response columns are the non-nested response values.

**Comment by purplizer** [comment]
> The docs are correct, response columns are the non-nested response values.

Ok, thanks for the reply! Would've been a great feature though if I could order by nested values :)

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
