### ISSUE TITLE
Campaign finishes in error

### ISSUE THREAD

**Issue by Shirkit** [mautic/mautic#6930]
## Bug Description
I have a campaign that, when the contact reaches the end, the campaign keeps throwing non-stop errors for all contacts that reaches it.

I have now 5000 notifications that I can't clear, and I don't know what's causing it.

"Tabela de Valores" is both a campaign name and a form name. The goal is when a user submits the form, I send an email with an attachment to them. If they download, 2 days later I send them a follow up email, and that's it.

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.1.12
| Browser | Firefox
 
### Log errors

The notification panels shows this for all contacts

> Failed to execute campaign event for ***EMAIL***.
> Tabela de Valores / Tabela vista
> Today, 6:20 pm

Log files are empty about this.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

![mautic](https://user-images.githubusercontent.com/829823/49043424-c9128000-f1a9-11e8-83d4-9045c36e4927.jpg)

**Comment by luizeof** [comment]
if you run php app/console m:c:t manually ... what's the output?

**Comment by escopecz** [comment]
Is Mautic sending the emails? Can you test it with a contact that has your email address?

**Comment by Shirkit** [comment]
Yes it does send the emails and process them, but the ongoing notifications never stops, and the contact gets "stuck" on that part of the campaign, running the same check and throwing errors every hour.

**Comment by escopecz** [comment]
```
mautic.ERROR: PHP Notice: require(): Failed opening required '/home/nginx/domains/mautic.DOMAIN.com/public/app/cache/prod/doctrine/orm/Proxies/__CG__MauticStageBundleEntityStage.php' (include_path='.:/usr/local/lib/php') - in file /home/nginx/domains/mautic.DOMAIN.com/public/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php - at line 209
```

This is quite serious. Looks like a file system permission issue. Make sure all Mautic folders and files have the right permission and owner.

**Comment by Shirkit** [comment]
That was right after I cleared the cache with `rm`. All files and folders have the correct permissions.

I'm pretty sure it was due to a cache miss, since it has not happened again and the file is there with right permissions, and triggering again the update does not throw the error.

**Comment by alanhartless** [comment]
Find the contact that is having the issue and check their profile page. Is there anything recorded as a "last execution error" in the timeline? 

Try running the trigger command for just the single contact `php app/console mautic:campaigns:trigger --contact-id=ID` (replace ID with the contact's ID). Anything revealed?

**Comment by npracht** [comment]
@Shirkit any update ?

**Comment by Shirkit** [comment]
Actually yes, it's being caused due to the user already having received the e-mail tagged as "Marketing E-mail" in the campaign. It was a bad setup of my campaigns, but still, it shouldn't warn forever and ever without being able to just dismiss the notification.

**Comment by abhi-ux** [comment]
i am still facing problem when i set it to transcational e-mail
