### ISSUE TITLE
Field smsFrequencyNumber declared dynamically in SmsHelper class

### ISSUE THREAD

**Issue by avionwd** [mautic/mautic#6931]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.1
| Browser | 

### Steps to reproduce
1. Open class `Mautic\SmsBundle\Helper\SmsHelper`
2. View `__construct` method
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
@kuzmany could you define the property, please?

https://github.com/mautic/mautic/blame/staging/app/bundles/SmsBundle/Helper/SmsHelper.php#L72

**Comment by avionwd** [comment]
Also, I discovered that this helper works only for Twilio service. And if I want to create adapter/plugin for another service to send text messages, this will generate an error, because the event handler specified in SmsBundle config expects this helper as a parameter.
Or, maybe this question must be as another issue?

**Comment by escopecz** [comment]
@avionwd I don't know much about the SMS plugin development, but I know my colleagues were working on some. Maybe you find inspiration in https://github.com/mautic-inc/plugin-slooce

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
