### ISSUE TITLE
Campaign Error

### ISSUE THREAD

**Issue by nickwild-999** [mautic/mautic#6932]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.0.27
| Browser | Chrome 70.0.3538.110

### Steps to reproduce
1.  Add a contact to a segment named  "twitter-test"
2. Set up a campaign driven by the "twitter-test" segment with an action that sends a tweet.

After 5 minutes the tweet is sent, but it generates an error 
 
### Log errors
`[2018-11-27 22:25:02] mautic.NOTICE: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 3 passed to Mautic\ChannelBundle\EventListener\CampaignSubscriber::sendChannelMessage() must be of the type array, null given, called in /opt/bitnami/apps/mautic/htdocs/app/bundles/ChannelBundle/EventListener/CampaignSubscriber.php on line 198 (uncaught exception) at /opt/bitnami/apps/mautic/htdocs/app/bundles/ChannelBundle/EventListener/CampaignSubscriber.php line 219 while running console command `mautic:campaigns:trigger` [] []`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by TiagoRodrigues** [comment]
The same is happening to me, but while i'm using Twilio. I've tested with an US based number and it worked, but with numbers from Brazil it wont work.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
