### ISSUE TITLE
Tracking with the tracking pixel using the PHP code from the documentation is not working

### ISSUE THREAD

**Issue by kumgabor** [mautic/mautic#6934]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
Tracking with the tracking pixel using the PHP code from the documentation is not working.
https://www.mautic.org/docs/en/contacts/contact_monitoring.html

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.0.30

### Steps to reproduce:

After an upgrade from 2.10, tracking with the generated tracking pixel URL from PHP is not working the way as documented here: https://www.mautic.org/docs/en/contacts/contact_monitoring.html

This URL works: mtracking.gif?page_url=...&page_referrer=...
This URL does not work: mtracking.gif?d=...

> $d = urlencode(base64_encode(serialize(array(
>     'page_url'   => 'http://' . $_SERVER[HTTP_HOST] . $_SERVER['REQUEST_URI'],
>     'page_title' => $pageTitle,    // Use your website's means of retrieving the title or manually insert it
>     'email' => $loggedInUsersEmail // Use your website's means of user management to retrieve the email
> ))));
> 
>echo '< img src="http://your-mautic.com/mtracking.gif?d=' . $d . '" style="display: none;" / >';

You should make these URL-s working again for compatibility or change the documentation.
 
### Log errors: 

none

**Comment by kumgabor** [comment]
I have already tried this. It didn't help.

**Comment by kuzmany** [comment]
What's your log? 
I checked the code and that part exist https://github.com/kuzmany/mautic/blob/c76d1b58b8be11165af9f86c9d032e78e5eedf11/app/bundles/PageBundle/Model/PageModel.php#L1143 
I didn't test it. But from code perspective should works.

**Comment by kumgabor** [comment]
Which log should I check?

Gábor

2018. 11. 29. 12:18 keltezéssel, Zdeno Kuzmany írta:

**Comment by kuzmany** [comment]
![image](https://user-images.githubusercontent.com/462477/49221277-f729d700-f3d8-11e8-967f-17bf659af5f4.png)

**Comment by escopecz** [comment]
So none of the info you send like this will be stored in the Mautic page hit action? Or only some? Can you describe what exactly are you sending and what Mautic shows after that?

**Comment by npracht** [comment]
@kumgabor any update ?
