### ISSUE TITLE
Mautic tracking broken

### ISSUE THREAD

**Issue by exactsameproblem** [mautic/mautic#6947]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hell there,
I was randomly viewing some members inside my mautic dashboard when I discovered that all the tracking parameters completely messed up together and mixed between contatcs.
I'm not sure what I did wrong, or what happened exactly, but in the screenshot below you will see that the contact's event "accessed by IP" belongs to visitors coming from random countries in the world and NOT from the contact himself. Also, the contact's Country is not at all related to the original City of the contact. The names are also messed up like everything else.
Not sure if it's a caching problem? a tracking problem or something else. Can someone help me?
![brokenmautic](https://user-images.githubusercontent.com/32123387/49328325-017dd980-f56f-11e8-9f99-7c5ba07ee71b.png)
Contacts are getting angry about us and asking why are we calling them "Hey GhostRider567" when they filled their real name inside the form... But this is because the nickname of other people replaced their original name...
Please help!!!

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 5.6
| Browser | Firefox

### Steps to reproduce
1. Not sure how to reproduce it... I activated tracking by browser fingerprint and tracking links in the e-mail (but NOT by IP addresses)
I'm using Wordpress with the Mautic plugin adding the tracking script to each page/post.
 
### Log errors
No errors in the log files except some rare " PHP Warning:  Invalid argument supplied for foreach() in /mautic/app/bundles/PageBundle/Model/PageModel.php on line 1237"
 PHP Notice:  Undefined index: ct in /mautic/app/bundles/PageBundle/Controller/PublicController.php on line 452

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Woeler** [comment]
Do you have a special usecase for tracking with fingerprint? Because if not, I would recommend turning it off. Cookies should be enough. fingerprint tracking can cause problems if not administered very carefully.

**Comment by exactsameproblem** [comment]
Hi Woeler and thank you for your answer.
I disabled the fingerprint tracking. I thought it would help to track visitors more reliably... But I'm not sure it was the source of the problem. Most of the contacts I checked had many IP addresses associated to their profile. I can understand that one or two "collisions" can happen, but not hundreds of IP that would have the same fingerprints... Either the fingerprint tracking technology is not working properly, or something else messed everything. Sorry, I'm not technical enough to dig deeper, but all my contacts are now broken as well as the entire automation platform.

**Comment by exactsameproblem** [comment]
After searching all day, I found someone asked about a feature I would find useful too: https://github.com/mautic/mautic/issues/5495
The problem in my case is that now random contacts are MERGED, so for example when someone bought something and then was merged to another contact, the latter one received a "thank you for your purchase" message without even knowing why!! That's a huge problem, and even a big privacy and credibility problem!!!!!

**Comment by Woeler** [comment]
Alright, I am pretty sure this is a configuration option. Contacts only merge because of things that are configured as unique identifiers (like email address) or tracking settings. What might even be happening is that someone is manipulating their cookies, though I doubt this unlikely.

If we want to find the issue please stop writing so hysterically, and provide some system and configuration information.

**Comment by exactsameproblem** [comment]
Thank you again Woeler.
I guess the same problem could occur when this "jack@mail.com" guy subscribe through a form. And another dude, john@mail.com, subscribe the same form, with the same fingerprint. John would merge his mail/settings (country, city...etc) to jack's. 
I have no way to get the initial stats and e-mails back, but at least we found the problem. I use cookie tracking only now as per your recommendations. The issue with cookies would be the one I mentioned before (#5495) when someone would use the same computer (and cookies) as someone else. 

Not sure how to close this issue now.

**Comment by oytuntez** [comment]
Very good insights, everyone, thank you! This saved me a bunch of possible cases.
