### ISSUE TITLE
Custom Fields 'Visible on forms' (is visible) does not do anything.

### ISSUE THREAD

**Issue by AlanMcC** [mautic/mautic#6949]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
There is an option for the custom fields to make them not 'Visible on forms'. I would expect the behaviour of this to hide these custom fields from the object that they are attached too (such as a contacts edit/new form). Or to hide them from being used in mautics form builder, but it looks like this option does nothing. I had a quick look through the code base but it looks like the 'isVisible' function is not used anywhere for custom fields.

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.0
| Browser | Any

### Steps to reproduce
1. Create a custom field
2. Select 'No' for the 'Visible on forms' option
3. The custom field will still appear in the form builder and mautics contacts/company forms.
 
[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
I tested this on 2.16 beta and found the following:

- If Short Form is set to no, then the field is hidden
- If the Full Form is set to no, then the field *is not* hidden

Screencast here: https://youtu.be/x6kXjDWnamw

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
