### ISSUE TITLE
Using the same public IP, leads are tracked as single one.

### ISSUE THREAD

**Issue by fones** [mautic/mautic#695]
Version 1.1.2
Have 2 computers in internal network, with the same public IP.
W access the same site, and there is only one lead assigned to both of us, with public IP as a name.
Should be fixed in #9

**Comment by alanhartless** [comment]
Hi @fones,

Mautic considers multiple _anonymous_ leads coming from the same public IP as the same lead. Their activity is tracked individually using a cookie with a unique session ID so if one of the leads makes themselves known via a form submit, etc, then the activity for that session is merged into the now known lead's profile. 

The bug report you mentioned was an issue where two _identified_ leads from the same IP address were merged.  

Thanks!
Alan

**Comment by fones** [comment]
Wow! It's nice! Ok, so you can close issue, sorry for the mess :-)

**Comment by alanhartless** [comment]
No apology needed :-) Enjoy Mautic!

Thanks,
Alan
