### ISSUE TITLE
Parent translation is missing

### ISSUE THREAD

**Issue by Gnenart** [mautic/mautic#6952]
I created an email and added up translations to it (20 languages including English (United States), English (United Kingdom, Polish (Poland), French (France) and etc. After I launched the campaign the parent translation was ignored and people who supposed to receive email in one language received it in another. 

I thought that this might be due to that I have edited the parent email, switched from one language to another on that parent email. 

But I have noticed as well, that one campaign which had a parent email working just well one day switched off, and instead of English (United Kingdom) translation people started getting English (United States). 

| Mautic version | - 2.14.1
| PHP version | PHP 7.1.16
| Browser | Chrome
 
I can't see any log errors due to this. Any help is appreciated. Thank you

**Comment by RCheesley** [comment]
I'm closing this down as there has been no recent discussion and it's from a very old version of Mautic. If it is still a bug, please feel free to re-open with further details on how to reproduce.
