### ISSUE TITLE
(BUG) Contact's history timeline : Item w/ type "Email Opened" is created in addition to "Email Sent" instead of replacing it after the same email is opened

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#6954]
## Bug Description

I noticed this behaviour as soon as I updated to 2.14.2, from 2.12.2. I am pretty sure it is not expected because it contra-intuitively suggests that two emails were sent, when actually, only one. Besides, some information are wrong.

![image](https://user-images.githubusercontent.com/23435414/49389965-326e3200-f75a-11e8-9a13-79647d6ea047.png)

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.1.17
| Browser | Chrome

### Steps to reproduce
1. Create a campaign that sends an email to a contact.
2. After email has been sent, don't open the email just yet, but go to the contact's profile
3. Notice the item with type "Email Sent" in the History timeline
4. Now, go and open the email in your mailbox.
5. Go back to the contact profile or refresh the page.
6. Notice that a new item is created with type "Email Opened"
7. Notice that the item "Email Sent" is still present.
8. Notice the information when unfolding the item "Email Sent" are wrong. It says the email was read at the time it was sent.
 
Expected behavior : "Email Sent" item should not be visible anymore but only "Email Opened" and the send stats (time, etc...) should be under "Email Opened" item (each email is sent one time, can be opened several times)

### Log errors

No error

**Comment by luizeof** [comment]
Tested and Reproduced ..

![download-1](https://user-images.githubusercontent.com/257004/49411383-d1416100-f74f-11e8-9bdb-c27b8e9511b9.png)

But on email_stats there are only one record about this e-mail ... I believe that is the expected behavior and not a bug ... but is really very confused ;)

Remove email sent and leave only email read makes more sense.

**Comment by AlbanL74fr** [comment]
And if you open the item Email Sent, you will see that some things are odd. And the content repeats through both items

**Comment by RCheesley** [comment]
As this is a super old issue and talks about expected behaviour rather than a bug (you should be able to see when the email was sent, and when it was opened, in the activity feed) I'm going to close the issue down.
