### ISSUE TITLE
New Mautic Campaign Fails using restart This Campaign

### ISSUE THREAD

**Issue by IADDIC** [mautic/mautic#6956]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Problem related to a campaign.  

I create an email and campaign and a test user.  I edit the user to select a custom field that attached that contact to a segment. 

I verify the contact is attached to the segment.  
However, the campaign does not send.  

Chrons are working.  

This is a new problem affecting new campaign only.  

The campaign uses change campaign:  (restart this campaign). 

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.1.24
| Browser | chrome

### Steps to reproduce
1. Create Email
2. Create the segment if not exiting (in my case test segment)
3. Create a Campaign using - restart this campaign - Publish it.
3. Open Contact
3. Modify a field to attach the contact to a Segment 

5.) No emails are sent.  - AGAIN THIS IS ONLY FOR NEW CAMPAIGNS

Log error:

### Log errors
[2018-12-04 00:58:02] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO maujd_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from maujd_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':dateAdded as date_added, :message as reason from maujd_campaign_lead_event_log ' at line 2 [] []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by imihandstand** [comment]
I have exactly the same error in my Log-file every 5 minutes:

`[2018-12-11 02:10:02] mautic.ERROR: CAMPAIGN: An exception occurred while executing 'REPLACE INTO maut1l_campaign_lead_event_failed_log( `log_id`, `date_added`, `reason`) SELECT id, :dateAdded as date_added, :message as reason from maut1l_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation':  You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':dateAdded as date_added, :message as reason from maut1l_campaign_lead_event_log' at line 2 [] []`

Mautic Version: 2.14.2
PHP Version: 7.0.32
Managed VPS from A2Hosting

What does this error mean? How to solve it? Please help!

**Comment by imihandstand** [comment]
@IADDIC Hey, check this solution out:
https://github.com/mautic/mautic/pull/6574#issuecomment-421299563
For me that "pdo_mysql"-solution stopped these errors!

**Comment by IADDIC** [comment]
@imihandstand I have made the change and will monitor the results.  I manually rebuilt segments and updated campaigns and did not have the error in my log.  I will review the logs tomorrow and then comment back with my findings.

**Comment by RCheesley** [comment]
Closing this issue due to lack of recent updates, please feel free to re-open if it's still an issue!
