### ISSUE TITLE
Link Permissions - View to Edit

### ISSUE THREAD

**Issue by cyanstar** [mautic/mautic#6959]
If a person has 'edit' permissions it should automatically toggle the 'view' permission as well. Right now if a person has 'edit' but not 'view' they're presented a 403 error when trying to edit, in my testing case, a campaign.

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
