### ISSUE TITLE
MCrypt is a suggestion during installation but required somewhere when managing addons

### ISSUE THREAD

**Issue by vmajor** [mautic/mautic#696]
Clicking on any addon category results in Server Error 500.

**Comment by alanhartless** [comment]
Hi @vmajor,

Can you please check your server's error log and Mautic's app/logs/mautic_prod.php for any related error to the 500?  Once we know what the error is, we can go about solving it.

Thanks!
Alan

**Comment by vmajor** [comment]
Hi Alan,

thank you for the super fast reply, and for the log file location. Mcrypt. It was not enabled. It showed as a "suggestion" during installation, but not a requirement so I rushed through it. I suggest in return that you make it into a requirement so that people who rush through installations do not in fact do so.

Cheers,

V.

**Comment by alanhartless** [comment]
Thanks for giving the feedback.  We'll either figure out what's using it and find an alternative or just make it a requirement.

Thanks!
Alan

**Comment by vmajor** [comment]
This may help:

[2015-07-21 13:27:20] mautic.CRITICAL: Uncaught PHP Exception RuntimeException: "The mcrypt extension is not enabled on this server." at /home/mautic/app/bundles/CoreBundle/HelptionHelper.php line 31 {"exception":"[object] (RuntimeException(code: 0): The mcrypt extension is not enabled on this server. at /home/mautic/app/bundles/CoreBundle/Helper/Enclper.php:31)"} []

**Comment by KorvinSzanto** [comment]
Teehee https://github.com/mautic/mautic/blob/staging/app/bundles/CoreBundle/Helper/EncryptionHelper.php#L29-L32

**Comment by alanhartless** [comment]
Fixed in 1.2.0
