### ISSUE TITLE
email type custom field supports default values that it should not (and generate side effects)

### ISSUE THREAD

**Issue by IADDIC** [mautic/mautic#6960]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )
## Bug Description
Scenario

I have a Contact Custom Field  = "STW Shipping Emai," 

It has the following attributes: Published, Visible on Forms, Available for Segment, NOT Is Unique, **NOT REQUIRED**, Visible on Short Forn, NOT Publically Updatable.

Label: STW Billing Email
Object: Contact
Data Type: Email,
**Default Value "-"**

When A contact is created the default value for the contact is "-"

When I attempt to edit the contact through the Mautic interface, I cannot save the contact.  The reason is the "Required" Email custom fields are saying the contact filed "STW Shipping Email" is REQUIRED.

If I enter an email, all is well.
 
When the field is set to **NOT required** the contact edit session should not force an email address to be entered. The reason this is set up this way is the field is reserved to contact who may purchase from our charity shop but have only registered at this point.  Sometime in the future they may or may not enter a valid email address.

Thanks 
| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.1.24
| Browser | chrome

### Steps to reproduce
1.  Create A new Field Type = Contact
2.  Use default value = "-" (not email)
3. Be sure to select NOT REQUIRED
4. Save

OPEN A CONTACT 
1. edit a field but NOT the custom email field you just created.
2. Select save and close

Result 

The session will not end, and dialog requires an email to be entered into the NOT Required Email Field.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
The value `-` cannot be supported in an `email` contact field. So it creates a mess when you try to edit the contact because if you don't edit it, when you try to save, the forms has an error (which is logic).

So the real bug is ---> you can add a defaut value in email type field even if it is not an email format
Your quickfix solution ---> Leave the default value empty

**Comment by npracht** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
