### ISSUE TITLE
Request-URI Too Long when edit Contact - Preferences

### ISSUE THREAD

**Issue by AkkuFresh** [mautic/mautic#6964]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Request-URI Too Long when edit Contact - Preferences

| Q   | A
| --- | ---
| Mautic version | v.2.14.2
| PHP version | 7.1
| Browser | Google Chrome

### Steps to reproduce
1. Create a Contact that is member of several (more then 10-15) segments
2. Change the Contact Preferences as it shown in the screen shot
![2018-12-04_2127](https://user-images.githubusercontent.com/6353141/49471020-1034ec80-f80c-11e8-8517-04a805cc7b28.png)
3. During the save the Mautic will hang up. In my case there was created a 8730 char length URL started with: <Mautic_URL>/s/contacts/view/2023?leadsLists%5B2%5D%5Bid%5D=2&leadsLists%5B2%5D%5Bname%5D=......
 
### Log errors in the browser 
Request-URI Too Long
The requested URL's length exceeds the capacity limit for this server.
Additionally, a 414 Request-URI Too Long error was encountered while trying to use an ErrorDocument to handle the request.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Woeler** [comment]
This will be fixed in 2.15. https://github.com/mautic/mautic/pull/6786
