### ISSUE TITLE
Mautic form Validation message not showing

### ISSUE THREAD

**Issue by symixdev** [mautic/mautic#6968]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

| Mautic version | 2.14.0
| PHP version |  7.0.32
| Browser | Google Chrome, Mozilla, IE etc. - regardless

### Steps to reproduce
1. Create form with mautic
2. Set some fields to be required and set validation message
3. Submit the form with empty required fields - **both** when it is previewed in Mautic and when it is embedded in the website with the Automatic embed option (JS)
4. Page reloads; No error messages are shown; The link is now with 

`http://example.com?mauticError=Errors%3A<br%20%2F><ol><li>%27Select%20%28required%29%27%20is%20required.<%2Fli><%2Fol>#form_subsc
` 
[This](https://github.com/mautic/mautic/issues/4362) is basically the same problem. I did all that is suggested there, yet no results. The domain set in Mautic is correct (https://subdomain.domain.com/mautic/index.php). I also did the Mautic troubleshooting and rebuilt the forms cache. The issue persists

### Log errors
No related logs

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
What are your fields' names ?

**Comment by symixdev** [comment]
> What are your fields' names ?

The required fields are as follows:
1. E-mail (required) / Field HTML name: email
2. Select (required) / Field HTML name: choose
3. Select (required) / Field HTML name: select_required

But I've tried creating a new form having just two fields with basic names - Test 1 and Test 2, where Test 1 is required. Same problem.

**Comment by npracht** [comment]
Hi @symixdev can we see your URL where the form is ? Maybe the browser consol would help :)
