### ISSUE TITLE
M3 Work group - API

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#6975]
# Description
This group is meant to define guidelines for the API (💪) of Mautic 3. These guidelines will be presented to the mautic community and completed with the given feedbacks.

## Teammates leaders
@dongilbert, @escopecz, @woeler

**Of course, this group is open to any contributor with a constructive opinion.**

## Topics
REST? GraphQL?

**Comment by marqpdx** [comment]
Does one comment here: I vote for GraphQL if it's between that and REST. Beyond that i don't know enough about Mautic to contribute much presently, so simply +1 forGraphQL.

PS - beefing up the REST layer is good too!
