### ISSUE TITLE
M3 Work group - DB schema of M3 core

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#6976]
# Description
This group is meant to define guidelines for the DB schema of Mautic 3. These guidelines will be presented to the mautic community and completed with the given feedbacks.

## Teammates leaders
@dcoutelle, @gregy, @heathdutton

**Of course, this group is open to any contributor with a constructive opinion.**

### Contact (or any entity like companies, products, etc.) custom fields
**Contacts, Custom fields (:warning: field type, number limit, etc.).**

#### EAV model
2 biggest problems with Mautic 2 are fixable by doing the following with schema:
1- EAV structure (by data type) MUST be supported (custom lead fields should not be appended to the lead table, we should find another solution that prevents potential future migration breaks)
2- Every stat table should have at least one summary table (summarized by hour or greater interval).

#### 1 table per field
The other option is to create a table for EVERY field. And I'm ok with that approach too, tbh. There are potential benefits in the long-term.
The advantage  there is when you create the field you can say "This will be available for segments" and it'll create it with an index, otherwise no index is needed on the value, just the lead_id FK.
It's efficient for storage if you don't store default value, and it's efficient for indexing.
Also when you create or drop a new custom field, it's nearly instant because you create an empty table or drop a table

### Multitable management
Ready for a multitable management (products, etc.)?

### Events management
**From @escopecz:**
> Would you consider interesting idea to have one simple table for all events? Right now when we compose the contact timeline events we have to fire an event and each bundle subscribes its own events from multiple tables. This makes it slow and impossible to order and paginate properly. I know that each event needs special columns, but those could be created in a joined table.
>I'm even playing with the idea of "Event Sourcing" which all cool kids are talking about these days, but maybe that's too big of a change.

**Comment by virgilwashere** [comment]
@npracht the Description paragraph is boilerplate for Front-end/UX/UI

**Comment by npracht** [comment]
> M3 should have a UUID identifier from the start to avoid auto-incremented, and thus easily guessable, IDs.
