### ISSUE TITLE
M3 Work group - Core features definition

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#6981]
# Description
This group is meant to define the guidelines of the core features we want to include in Mautic 3. Mautic 3 philosophy is to make Mautic the lightest as possible and then manage features that are not core as "plugins" easily installable for any user.
These guidelines will be presented to the mautic community and completed with the given feedbacks.

## Teammates leaders
@dbhurley, @npracht

**Of course, this group is open to any contributor with a constructive opinion.**

### Features needed
What is so core that it should be in any case installed in the lightest version of Mautic3?

#### Basic core features suggestions
- Contacts Management
- Custom fields management
- Segments
- Campaign management

#### Basic features suggestions to be delivered in Mautic 3.0.0 as "plugin"
- Email
- Companies
- Forms
- Pages
- and all in 2.x ?

#### Feature benchmark and brief
For each of the selected feature, we would have to deliver a guideline, create a group and design a co-leadership between a marketing guy and a dev guy.

**Comment by hrouissi** [comment]
I hope this is the right topic. 
One important feature that should be implemented in next releases would be related to digital advertising and audiences/segments. 

The feature would allow us through "Cookie matching" protocol to sync segments with third party advertising platforms. 
This would make Mautic as a viable DMP (Data management platform) and would allow it to attract more users. 

Here are some examples : 
http://www.mediamath.com/audience/connectedid/
https://developers.google.com/authorized-buyers/rtb/cookie-guide

Free to discuss the idea with whomever interested.
