### ISSUE TITLE
Mailchimp integration only shows 10 lists

### ISSUE THREAD

**Issue by YosuCadilla** [mautic/mautic#6985]
## Bug Description
The Mailchimp integration asks, at configuration time, for the mailchimp list you want to connect to, the list is automatically populated but only shows 10 entries, if the list you want to use is #11 you won't be able to see it in the drop down.

### Steps to reproduce
1.  Enable Mailchimp integration
2.  Go to the plugin's configuration and connect to an account with more than 10 lists on it.
3. In configuration click on the dropdown to choose the list you want to use.
 
### Log errors
No errors

**Comment by YosuCadilla** [comment]
Related to #415 ?

**Comment by alecmyers** [comment]
MailchimpApi.php line 64, change to:
return $this->request('lists', ['count' => 100]);

**Comment by RCheesley** [comment]
I'm going to close this as it was addressed in the PR mentioned in #415 which raises the limit to 100.
