### ISSUE TITLE
Unnaturally low open rates after upgrading from 2.14.1 to 2.14.2

### ISSUE THREAD

**Issue by StoppingBuck** [mautic/mautic#6988]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
After updating Mautic 2.14.1 to 2.14.2 we have experienced a dramatic drop in our open rate.

As an example, one of the segments that used to have an open rate of 30% dropped to 1.07% after sending through 2.14.2. These are segments that have had consistently the same open rate for years, so the drop is unnatural.

We have sent several segment emails using 2.14.2, and all result in an artificially low open rate compared to previous versions of Mautic.

Recently, we set up a separate installation of Mautic 2.13 and tried sending the same emails to the same segments through that, and the one with a 1.07% open rate on 2.14.2 got a normal (~30%) open rate on 2.13 so this definitely smells like a regression.

We use Amazon SES for sending the actual emails, and it reports the correct number of emails being sent out. We have a Healthy bounce rate of 0.44% and a Healthy complaint rate of 0.02%

Our emails are handled by queue.

We are using the same email domain to send from. Literally, the only change that has happened has been the upgrade from 2.14.1 to 2.14.2.

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.1.20
| Browser | (irrelevant)

### Steps to reproduce
1. Send segment email
2. Notice low open rate even efter several days.
 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by StoppingBuck** [comment]
Here is the raw text of one of the emails that was sent out first in 2.14.2 (to the tune of 1.07% open rate) and subsequently re-sent - to the same segment - from 2.13 (resulting in 30% open rate). The same template was used for both (although obviously from separate Mautic installations).

[Email sent through 2.14.2.txt](https://github.com/mautic/mautic/files/2663109/Email.sent.through.2.14.2.txt)
[Email sent through 2.14.2.txt](https://github.com/mautic/mautic/files/2663110/Email.sent.through.2.14.2.txt)

**Comment by npracht** [comment]
Weird, none reported that, and never noticed.
Could you please try update to 2.15.0-beta **not in production environment!!!! Just for testing** to see if you have a difference?

Did you try updating assets and clearing cache ?

Thanks

**Comment by StoppingBuck** [comment]
@npracht Clearing cache is part of the upgrading process, isn't it? So yes, we did that. I don't understand what you mean by 'updating assets', though.

Anyway, we've set up the beta on a testing server, but are unsure of how to test it. After all, the only way to do so is to send out to our regular segments to see if we get the regular open rate?

**Comment by npracht** [comment]
Hello @StoppingBuck did you have the opportunity to make it working correctly again ?

**Comment by hrouissi** [comment]
I have the same issue, I believe since 2.14.2 update. 
I'm using Campaign monitor as a SMTP server. 

Here's an example of 2 campaigns with huge discrepancies between Mautic and Campaign Monitor :
Campaign 1 : 
Mautic Open rate  = 4.18%
Campaign Monitor Open rate = 11.3%

Campaign 2 : 
Mautic Open rate  = 3.53%
Campaign Monitor Open rate = 10.8%

I'm using emails built with "Code mode".

**Comment by StoppingBuck** [comment]
@npracht As far as I can tell, the problem is gone in 2.15. Although we're still not sure what caused it. But for the moment, all is fine :)
