### ISSUE TITLE
Segments not correctly catching DNC

### ISSUE THREAD

**Issue by AndrassGray** [mautic/mautic#6989]
## Bug Description
Segments contain or are missing contacts that should be there.

I have a segment called "House-keeping" where I collect all sort of unsubscribes and bounces. I had noticed that I had some unsubscribes, but the number of contacts in this segment does no longer change. It looks as if this segment gets no longer updated.

While trying to figure out what's going on, I created a new segment that (should) only contain unsubscribed contacts. It catches (correctly) the missing contacts from above, but equally shows contacts that are NOT unsubscribed.

The contact lists of the below screenshots are sorted by contact ID. Note that ID 6310 is not present in the "house-keeping" segment, although it should, but correctly present in the "a list apart" (test) segment.

| Q   | A
| --- | ---
| Mautic version |  2.14.2
| PHP version | 7.0.33 on Ubuntu LTS
| Browser | Chrome

### Steps to reproduce
1. create segments as shown
2. notice missing or too many contacts
 
### Log errors

The error logs are empty.

![b-hk-0](https://user-images.githubusercontent.com/30862808/49750582-a1441180-fcab-11e8-99b6-48cfbbe7a042.png)

![b-hk-1](https://user-images.githubusercontent.com/30862808/49750604-b02ac400-fcab-11e8-8fb1-4bd5993fd694.png)

![b-ala-0](https://user-images.githubusercontent.com/30862808/49750614-b6b93b80-fcab-11e8-8f08-e9bdb9d3911b.png)

![b-ala-1](https://user-images.githubusercontent.com/30862808/49750629-bcaf1c80-fcab-11e8-9381-9528238b3cc3.png)

**Comment by AndrassGray** [comment]
I guess I should close this issue for the moment.

I had installed a PR that catches 'manual unsubscribes', and after some more playing around, I noticed that it makes a difference if I use it or not in the house-keeping segment.

It shouldn't have an influence on the 'a list apart' segment, but I will revert the 'manual unsubscribe' patch and dig a little deeper.

**Comment by AndrassGray** [comment]
Ok. I reverted the patch, so I am clean, code-wise.

I recreated the segment that should only contain email unsubscribes. It contains far too few contacts, and it contains contacts that are not unsubscribed. So this is wrong on both sides.

I am open to further diagnosis if someone tells me what to test. As of now, testing like this goes wrong on my installation : 
1. modify existing segment : delete all conditions, then add "unsubscribed email" == Yes
2. rebuild segment

**Comment by AndrassGray** [comment]
Bug is still there with Mautic 2.15.2

I have a new Mautic install that has two contacts set DNC:
![image](https://user-images.githubusercontent.com/30862808/64078760-02e75880-ccdf-11e9-9cd9-a84813ece29c.png)

I create a segment that should catch all unsubscribes:
![image](https://user-images.githubusercontent.com/30862808/64078769-25797180-ccdf-11e9-8f56-e83d14a98960.png)

After running mautic:segments:update on the console:
![image](https://user-images.githubusercontent.com/30862808/64078780-4a6de480-ccdf-11e9-8d41-1d7df7235f01.png)

**Comment by RCheesley** [comment]
@AndrassGray is this still an issue with 2.15.3 do you know?

**Comment by AndrassGray** [comment]
No idea, @RCheesley. I abandoned using Mautic.
