### ISSUE TITLE
Prepopulating forms with url parameters not working on 2.14.2 and 2.15.0-beta

### ISSUE THREAD

**Issue by jamiemurray** [mautic/mautic#6990]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have a form which was largely populated by url parameters but since updating, this no longer works.  I have tried on both 2.14.2 and 2.15.0-beta

Eg: https://<<MAUTICFQDN>>/form/1?html_field_alias=prepopulated+value

| Q   | A
| --- | ---
| Mautic version | 2.15.0-beta
| PHP version | 7.2
| Browser | Firefox 63.0.3

### Steps to reproduce
1. Create a form
2. Pass values to prefil it on the url. 
 
### Log errors
Haven't found any errors relating to this issue

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by heathdutton** [comment]
I didn't even know this feature was supported when the lead is unknown. I've seen people using JS to make it happen though, which leads me to believe this isn't a given for anonymous users.  
Example:  https://gist.github.com/shawncarr/56c2484cb50bc923107f210310366ad0

https://www.mautic.org/docs/en/forms/manage_forms.html seems to suggest this is for emails where the lead is predetermined (ct parameter is provided). That being said, I think it'd be a good feature... 

My question, is is this recently broken? If so where is it documented?

**Comment by kuzmany** [comment]
Try this fix https://github.com/mautic/mautic/pull/6882/files

**Comment by heathdutton** [comment]
Not sure if #6882 resolves this. Example: https://mautibox.com/6882/s/forms/preview/1?email=test.testerson@gmail.com

**Comment by jamiemurray** [comment]
#6882 does not resolve the issue.

**Comment by kuzmany** [comment]
Of course, https://github.com/mautic/mautic/pull/6882/files resolved lot of issues with pre-populate.  `$form->getFields();` return empty array even If form fields exist. I didn't  test that PR, but I got similar issue with plugin where we use pre-populate method.

**Comment by diegodorgam** [comment]
So this is still broken on 2.15.0, any updates?

**Comment by andreaedsel** [comment]
Hi all,
we are using Mautic 2.15 with the last version of FormModel.php and the issue persists.

As reported by @heathdutton , the #6882 doesn't resolves this issue and you have to use a script like that:  https://gist.github.com/shawncarr/56c2484cb50bc923107f210310366ad0

In my web page I used a script like that and it works fine:

I created a form (myform) with email field with "Auto fill data" property setting to Yes.
I placed the myform inside a my webpage which contains a script like that: https://gist.github.com/shawncarr/56c2484cb50bc923107f210310366ad0

I open my webpage address passing email as url parameter, like this:
www.mywebpage.com/?email=myemail@test.com
The email field on myform pre-populate with the url parameter value.
It works fine.


But now I've got another problem.
If I put the myform inside a Focus Item, it doesn't work.

The steps:
I created a Focus Items (myfocusitem) to Collect Data.
The style used is Notification from Left.
In the Content section (Content mode: Basic ) I select myform in the field "Select the form to insert".
Then I installed myfocusitem in my website, as described in the Mautic guideline: 
<script src="//mywebsite.com/focus/1.js" type="text/javascript" charset="utf-8" async="async"></script>
I'm using a script like that in my webpage:  https://gist.github.com/shawncarr/56c2484cb50bc923107f210310366ad0
I open my webpage address passing email as url parameter, like this:
www.mywebpage.com/?email=myemail@test.com
The email field on myform doesn't pre-populate with the url parameter value.

thanks in advance

**Comment by ctingwai** [comment]
Hello all,

I am facing a similar issue with Mautic version 2.15.1, I am able to workaround the issue by adding the following code to `app/bundles/PageBundle/Controller/PublicController.php` below `$content = $event->getContent();` at line 286:

```
foreach ($this->request->query->all() as $k => $v) {
    if (preg_match("/name=\"mauticform\[$k\]\"/", $content)) {
        $content = preg_replace("/name=\"mauticform\[$k\]\" value=\".*\"/", "name=\"mauticform[$k]\" value=\"$v\"", $content);
    }
}
```

**Comment by AlbanL74fr** [comment]
I have the same issue in 2.14.2. Hopefully this can be solved in 2.15.3. Prepopulating forms from info passed as URI parameter is a very useful feature.

**Comment by dennisameling** [comment]
Having the same issue in 2.15.3. @ctingwai's answer indeed works as a workaround for this issue, and the fields get populated. Not sure if it's completely safe, as this might need some sanitization before simply inserting it into the form fields.

**Comment by online-expert** [comment]
Having the same issue in 2.15.3 with Mautic form on Wordpress website. @heathdutton's js works as a workaround but @ctingwai's answer does not seem to pre-populate the form fields.

**Comment by RCheesley** [comment]
If this is still an issue and it seems @ctingwai 's proposal is the start of a potential workaround/solution, is anybody working on a PR to address it?

**Comment by stevedrobinson** [comment]
Still an issue in 2.16. Using shawncarr's gist as posted by @heathdutton above while I wait to have time to dig in.

This did work in a previous version of Mautic.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
