### ISSUE TITLE
 pass segment id in contact query

### ISSUE THREAD

**Issue by dhirendradaffodil** [mautic/mautic#6992]
How I can pass segment id in below query

GET api/contacts?where%5B0%5D%5Bexpr%5D=gte&where%5B0%5D%5Bcol%5D=dateAdded&where%5B0%5D%5Bval%5D=2018-03-01%2000:00:00&where%5B1%5D%5Bexpr%5D=lte&where%5B1%5D%5Bcol%5D=dateAdded&where%5B1%5D%5Bval%5D=2018-04-01%2000:00:00

**Comment by npracht** [comment]
Hello,
Please use github for bug report and move to Slack chat to this type of question.
Thanks for your understanding.
