### ISSUE TITLE
Custom labelling

### ISSUE THREAD

**Issue by Jayanthbm** [mautic/mautic#6995]
I am trying to add custom labels for the builder, which is in focus items tab but I couldn't locate the piece of code.
please help me finding 
![mautic](https://user-images.githubusercontent.com/14847969/49861384-b93da180-fe21-11e8-89ce-78b64881b829.PNG)
it

**Comment by npracht** [comment]
Hello,
Please use github for bug report and move to Slack chat to this type of question.
Thanks for your understanding.
