### ISSUE TITLE
Add a new way to schedule a decision campaign event.

### ISSUE THREAD

**Issue by carloshmm** [mautic/mautic#6998]
Currently there are 3 ways to schedule a decision campaign event:
"immediately", "at a relative period of time" and "at a specif date/time".

What I want to propose is a new mechanism where a decision can be constantly evaluated during a relative period of time, something like a fourth option called:
"periodically check during a period of time".

The difference between this new option and the old one: "at a relative period of time" is that the cronjob "mautic:campaigns:trigger" will **constantly** try to evaluate a decision during a period of time instead of only evaluating **after** a period of time. This way we can postpone the "red path/negative evaluation" until the period of time is consumed and follow the "green path/positive evaluation" as soon as the decision is evaluated as true.

Currently I see no way to do this. At least not with the current set of scheduling mechanisms.

**Comment by heathdutton** [comment]
Could you build a workaround by by umping from one event to a previous one after a delay (effectively creating a loop)?

**Comment by carloshmm** [comment]
@heathdutton

Actually there is already a feature that can simulate a loop: https://mautic.com/help/august-2018-update/#jump-to-event

The problem is that this loop is based only on the evaluation of the decision and not on a specified period of time as I was proposing.
