### ISSUE TITLE
Campaign does delayed actions twice as late as set up

### ISSUE THREAD

**Issue by imihandstand** [mautic/mautic#6999]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I made a campaign which should send out an email every day. So the delays are:
- Email 1: 1 day
- Email 2: 2 days
- Email 3: 3 days
etc.

However, they are sent out in the double amount of time. So Email 1 is sent out after 2 days. Email 2 is after 4 days, Email 3 after 6 days, etc. This is of course a huge problem.

I made a screenshot which shows that between the emails there is always 2 days instead of 1 day:
https://screencast.com/t/JqlGam2p

And here is a screenshot from the campaign-builder from that campaign:
https://screencast.com/t/NaIqawHA
As you see they should be just 1 day between the emails.

BTW, the last action ("_Die Master-Kampagne starten und diese Kampagne stoppen_") is not a "send email", it's stopping this campaign and starting the next campaign. So the delay-problem is not just with email-sending, it's with every action with a delay (as that campaign-stopping-action should be after the day from the last email, but as you see it's somehow 2 days after the last email).

| Q   | A
| --- | ---
| Mautic version | v2.14.2 
| PHP version | 7.0.33
| Browser | Firefox 63 Mac

### Steps to reproduce
1. Create a campaign and set up a few emails which should be sent out after 1, 2, 3, etc. days
2. Assign a contact to that campaign
3. Check the "Upcoming Events" from that contact
 
### Log errors
No errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Woeler** [comment]
This is fixed in 2.15

**Comment by imihandstand** [comment]
@Woeler When will be the update available? At the moment it doesn't help me to much that it's fixed in a version which is not available. How could I solve this bug for v2.14.2?

**Comment by imihandstand** [comment]
@Woeler (or somebody else) PLEASE tell me how to fix this! I pay $90 a month for Sendgrid and I can't start my email-campaigns because of this error!
