### ISSUE TITLE
issue with pending contacts badge in segment emails

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#7003]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When creating a segment email, a new pending badge is added in the list of emails with the number of contact that will receive the email.
Then after sending the email, the badge should disappear. But now, the badge still there showing the same number of pending contacts

| Q   | A
| --- | ---
| Mautic version | 2.15.0-beta
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a segment email
2. See the pending badge
3. Send the email
4. Go back on the list of email and see that the pending badge is still showed even if it has been sent.
![image](https://user-images.githubusercontent.com/31535432/49931928-3f142800-fec8-11e8-9d69-715502a56982.png)

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
@dongilbert i would suggest that it is a side effect of https://github.com/mautic/mautic/pull/6444 ?

**Comment by npracht** [comment]
Hi @dongilbert, any thoughts or suggestions? Thanks :)

**Comment by npracht** [comment]
@johbuch please test https://github.com/mautic/mautic/pull/7079

**Comment by StoppingBuck** [comment]
This problem persists even after clearing `app/cache` folder. @npracht AFAICS from the comments in that PR, it's not related to this?

**Comment by npracht** [comment]
It is not ;)

**Comment by autoize** [comment]
Also experiencing this bug on 2.15.0 instances deployed in production.
It is highly confusing to novice users who may be mistaken that their Segment Email has not went out yet, even though they can see that no contacts are still "pending" when they click on the "Pending XXX" badge. +1 for this to be fixed in 2.15.1.

**Comment by lcmps** [comment]
Experienced this bug in v2.15.1, this fix worked flawlessly. Thank you very much
