### ISSUE TITLE
filtering contacts by campaign membership

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#7004]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
See this PR https://github.com/mautic/mautic/pull/5911
Eveything works except for the point 7 --> For bonus points, manually remove the contact from the campaign, and the segment will drop this contact on the next segment update.

--> the contact is not removed from the segment

| Q   | A
| --- | ---
| Mautic version | 2.15.0-beta
| PHP version | 
| Browser | 

### Steps to reproduce
1. repeat steps of this PR https://github.com/mautic/mautic/pull/5911
2. Point 7: when removing the contact manually from the campaign, when crons segment:update has been runned, the contact has not been removed from the segment.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by heathdutton** [comment]
Looking into this now.

**Comment by heathdutton** [comment]
Thanks for the deep testing @johbuch! Please follow #7018 for resolution.
