### ISSUE TITLE
【2.14.2】Configuration page can not be saved

### ISSUE THREAD

**Issue by tomomink** [mautic/mautic#7008]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.1
| Browser | Chrome

### Steps to reproduce
1. Open Configuration page.
2. Select "Apply" or "Save and Close" on the upper right of the screen.
3."Please wait" appears and does not move.
 
### Log errors
It is not in System Info

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Woeler** [comment]
This is a file permissions issue
