### ISSUE TITLE
Contact dont update

### ISSUE THREAD

**Issue by dgram** [mautic/mautic#7009]
## Bug Description
Hi, i want to update our contacts with mt() js api. (https://www.mautic.org/docs/en/contacts/contact_monitoring.html)

I have added some billing fields like billing_email.

Then i call the following code in js:
``js
mt('send', 'pageview', {billing_email: 'my@email.com'});
``

At the backend i have the following options on the field:
![mautic](https://user-images.githubusercontent.com/1048231/49992239-6677fd00-ff7b-11e8-8cad-fc7f1031a9ee.png)

The data will be tracked, take a look here:
![mautic mail](https://user-images.githubusercontent.com/1048231/49992421-f322bb00-ff7b-11e8-9415-efcaeddd1acd.png)

If you look at the image here you see no updated data:
![mautic data](https://user-images.githubusercontent.com/1048231/49992539-439a1880-ff7c-11e8-9dc5-bcbc87b98a54.png)

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.1
| Browser | *

**Comment by escopecz** [comment]
Please retest with 2.15.0. I think it's fixed there.
