### ISSUE TITLE
When using queues, the e-mail link click tracking don't work properly

### ISSUE THREAD

**Issue by gabfr** [mautic/mautic#7012]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When using queues, the e-mail link click tracking don't work properly. It records a page hit for the user, but don't sum up in the e-mail and/or campaign metrics.

I will add some screenshots to make it easier to understand what is going on:

### With queues settings configurated and active

I made a campaign with a simple decision of e-mail click/no click (*with no specific URL on the decision step*):

<img width="1440" alt="screen shot 2018-12-14 at 11 15 34" src="https://user-images.githubusercontent.com/1237163/50005913-1f960180-ff93-11e8-889d-391d06f06cff.png">

Then I added a test contact to the campaign, as you can see, it marked the email opening, the page hit (with source from the e-mail):

<img width="1440" alt="screen shot 2018-12-14 at 11 22 50" src="https://user-images.githubusercontent.com/1237163/50005897-160c9980-ff93-11e8-8f1b-fdd31468da38.png">

But when I go to the campaign to analyze the statistics, it's a big fat zero :(

<img width="1440" alt="screen shot 2018-12-14 at 11 23 36" src="https://user-images.githubusercontent.com/1237163/50006019-7f8ca800-ff93-11e8-8177-4bc246639443.png">

Causing the wrong decision of **"no click"** triggering:

<img width="1440" alt="screen shot 2018-12-14 at 11 24 43" src="https://user-images.githubusercontent.com/1237163/50006052-94693b80-ff93-11e8-8bbd-be51fbe87d16.png">

And after 5 minutes, triggered the no click decision:

<img width="1440" alt="screen shot 2018-12-14 at 11 33 28" src="https://user-images.githubusercontent.com/1237163/50006234-3a1caa80-ff94-11e8-8ed5-500df3a350b9.png">

### With queues disabled & email send immediately

Within the same campaign above, but with queues disabled, I added another test contact to the segment so it starts from the beginning in this campaign:

<img width="1440" alt="screen shot 2018-12-14 at 11 35 39" src="https://user-images.githubusercontent.com/1237163/50006293-6d5f3980-ff94-11e8-8170-5a3ccd9fbbce.png">

Then, the e-mail was sent and clicked. Everything recorded as expected in the contact history:

<img width="1440" alt="screen shot 2018-12-14 at 11 37 07" src="https://user-images.githubusercontent.com/1237163/50006373-b7e0b600-ff94-11e8-9956-d49bde149d37.png">

And also in the campaign:

<img width="1440" alt="screen shot 2018-12-14 at 11 37 20" src="https://user-images.githubusercontent.com/1237163/50006409-d3e45780-ff94-11e8-8795-df8cb0689fb7.png">

<img width="1440" alt="screen shot 2018-12-14 at 11 37 27" src="https://user-images.githubusercontent.com/1237163/50006420-dcd52900-ff94-11e8-9d90-f7ba2e348cc2.png">

| Q   | A
| --- | ---
| Mautic version | v2.15.0-dev
| PHP version | 7.0.32-4
| Browser | Google Chrome 71.0.3578.98

### Steps to reproduce
0. Configure your queue settings with beanstalk or rabbitmq
1. Create a Campaign with a decision process of e-mail click and then, if not click, send a specific e-mail and if clicked send another specific e-mail.

Example of campaign:
<img width="1440" alt="screen shot 2018-12-14 at 10 58 05" src="https://user-images.githubusercontent.com/1237163/50004723-39354a00-ff8f-11e8-9e0d-fb5952596f29.png">

**Remember to put a link to click on the first email of the campaign flow.**

2. Create a segment and add it in the campaign
3. With queue settings activated and properly configurated, test adding a contact in the segment.
4. You will receive the first e-mail on your inbox, click on the link you put on the e-mail.

Then, you will see that the link will record a page hit for the specific contact you added, but will not sum up in the e-mail nor in the campaign metrics.
 
### Log errors

There is no logged errors. Just a unexpected behaviour.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by mtasuandi** [comment]
@gabfr You can try solution from this #6874

**Comment by gabfr** [comment]
Thanks @mtasuandi. Resolved here:
https://github.com/mautic/mautic/issues/6874#issuecomment-439167233
