### ISSUE TITLE
Enter key defaults to cancel in contacts list' segment change dialog

### ISSUE THREAD

**Issue by mMuck** [mautic/mautic#7014]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If I batch-edit the segments of selected contacts in the contacts view (mark -> change segment), the enter key closes the window but cancels the edit. The default action should be "Save".
After pressing the save button, a hover message shows the affected entries. This message is missing using the enter key.
Perhaps this is an issue with more dialogs.

Related to #3121 - I don't understand why this was closed. @jordan8037310 is right. Unexpected behavior. Bad user experience. :disappointed:

| Q   | A
| --- | ---
| Mautic version | 2.13.1 (but should affect newer versions)
| PHP version | not related
| Browser | Firefox 62

### Steps to reproduce
1. Mark contacts
2. Change the segment
3. Choose a new segment
4. Press enter key, the window closes
5. Check the contact and its segment attribute to verify

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by CyberMarsl** [comment]
The same behaviour happens fi you enter the details of a condition in the campaign. 

Steps to reproduce:

1. Add a Condition (may apply to decition too)
2. Enter the details
3. Dont save with the safe button, but instead safe by hitting enter key

-> Closes but does not saves the decition

**Comment by RCheesley** [comment]
Thanks for reporting this folks, anybody open to looking at fixing this?
