### ISSUE TITLE
Cannot add additional variant to dynamic content.

### ISSUE THREAD

**Issue by otsang** [mautic/mautic#7024]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.14.2
| PHP version |  PHP Version 7.1.23
| Browser | Google Chrome Version 70.0.3538.110

### Steps to reproduce
1. Channel -> Email -> Published Template Email
2. Edit Published Template Email
3. Dynamic Content
4. Unable to add new variant to dynamic content

![dynamic content can t add](https://user-images.githubusercontent.com/45982673/50190389-e7b5f380-02dd-11e9-93f1-d1f139f8c557.png)

 
### Log errors

[//]: # ( Invisible comment:

**Comment by escopecz** [comment]
Please check the Mautic logs and also open the browser dev tools and check the error message in the console tab.

**Comment by robiasto** [comment]
I get this js console warning:
Editor should be initialized before calling the destroy method.

**Comment by RCheesley** [comment]
@otsang were you able to provide any further detail on this? I will close the issue down in a week if we don't have sufficient information to troubleshoot/debug the issue.
