### ISSUE TITLE
Meta description is not injected in page HTML code

### ISSUE THREAD

**Issue by vadimnai** [mautic/mautic#703]
Changing the meta description in the page editor in Mautic does not make the meta tag appear in the page HTML. This is valid both for the built-in templates and custom ones built with them as the base.

P.S.

For those who absolutely need this working before the issue is fixed, here's a simple workaround the devs shared in Slack:

Add the meta tag to your base.html.php like this:
```
<meta name="description" content="<?php echo $page->getMetaDescription(); ?>">
```

**Comment by dbhurley** [comment]
Thanks! This was fixed with #704
