### ISSUE TITLE
Email handled by Queue

### ISSUE THREAD

**Issue by DianaCruz16** [mautic/mautic#7031]
## Bug Description
How to configure the Email Queue in Email Settings?

| Q   | A
| --- | ---
| Mautic Version | 2.14.1
| PHP version  | 7.0.31
| Chrome | 

I must send 300 emails. My maximum server allows me to send 100 emails per hour. How should I configure the post queue?

With the current configuration, it sent all emails at the time exceeding the server's capacity.

My Cron task running: 1 minute
![email-settings](https://user-images.githubusercontent.com/44612832/50224742-a4ef2c80-036c-11e9-82f5-3b1f8f1a6a65.PNG)

**Comment by heathdutton** [comment]
It depends on how often you have the `mautic:emails:send` cron task running. The "Message Limit" is how many emails will be allowed to be sent per execution of the cron task.

For example, if you have the cron task running every 6 minutes, then you need to set the message limit to 10. That would send 10 emails every 6 minutes as a maximum.

If you set your cron task like this it'll lock you to that maximum :)
`*/6 * * * * root php /path/to/mautic/app/console mautic:emails:send --message-limit=10`

**Comment by mauwiks** [comment]
What's the difference between [mautic:emails:send] and [mautic:email:process] for Crob Job command? I've searched everywhere. What I can understand is it says the same as queue function

Please let me know how to set it up in the Email Settings Config and Cron Jobs

**Comment by virgilwashere** [comment]
https://mautic.slack.com/archives/C02HU8BUT/p1547647160380000?thread_ts=1547480505.314300&cid=C02HU8BUT

They are aliases.

**Comment by npracht** [comment]
Please chat on Slack ;)
