### ISSUE TITLE
Type error: SparkpostTransport::processCallbackRequest()

### ISSUE THREAD

**Issue by bookin** [mautic/mautic#7035]
## Bug Description
After update Mautic from v2.14.2 to v2.15.0 I am getting error - 
`[2018-12-19 17:21:02] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Mautic\EmailBundle\Swiftmailer\Transport\SparkpostTransport::processCallbackRequest() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in /var/www/mautic/app/bundles/EmailBundle/EventListener/EmailSubscriber.php on line 172" at /var/www/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/SparkpostTransport.php line 338 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Mautic\\EmailBundle\\Swiftmailer\\Transport\\SparkpostTransport::processCallbackRequest() must be an instance of Symfony\\Component\\HttpFoundation\\Request, null given, called in /var/www/mautic/app/bundles/EmailBundle/EventListener/EmailSubscriber.php on line 172 at /var/www/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/SparkpostTransport.php:338)"} []
`

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0

**Comment by heathdutton** [comment]
Fixed by #7015 

A short term fix is to go in your /mautic folder and run `curl -L https://github.com/mautic/mautic/pull/7015.diff | git apply -v`
