### ISSUE TITLE
404 Images in Email Webview when 'Convert embed images to Base64' is ON

### ISSUE THREAD

**Issue by katzueno** [mautic/mautic#7037]
## Bug Description

Email Preview {webview_url} doesn't show images if you enabed BASE64 image embedded mode.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 5.6.38 & 7.1.23
| Browser | Chrome & Firefox

### Steps to reproduce
1. Turn `Convert embed images to Base64`ON from Email Setting of Configuration Menu
2. Create an HTML Email with embedded image and make sure to add {webview_url} to the email body.
3. Send actual email to the actual contact ( {webview_url} doesn't work for sample email)
4. Click {webview_url}
5. All embedded images' src=""` are still output `cid:XXXXXX@[mauticurl]` which is the same as email body. The images links of *webview* are still trying to link them to email attachments. URL was not converted back to actual asset URL on mautic instance.
 
## Problem of `Convert embed images to Base64`OFF

If you turn `Convert embed images to Base64`OFF, email preview images returns URL on mautic instance.

However, some email clients, which restrict to display images outside email, will stop showing those embedded images.

**Comment by katzueno** [comment]
Mautic 2.12.1 doesn't have this problem. So somehwere between 2.12.1 & 2.15.0 started to have this problem.

**Comment by hrouissi** [comment]
Same issue on 2.14.2.

**Comment by regevbr** [comment]
Same issue on v2.15.1

**Comment by visualmovement** [comment]
Problem still exists on v2.16.2. Any News on this matter? Would it be possible to somehow set a switch in the template using Base64 for Mails while using basic image path on webview?

**Comment by npracht** [comment]
Hello @katzueno @regevbr can you try in 2.16.2 ? Some fixes about base64 where applied.

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Comment by onlineexpert** [comment]
We are using v3.2.4 and also have this issue when 'Convert embed images to Base64' is ON.
It is not a big issue for us so we just disabled this option without creating a new issue.
Mentioning it here though because it is on top in search results for Mautic Base64 problem.
If you also experience this issue on latest release first check issues #9069 #9003 #8995 #9124.
Thanks!
