### ISSUE TITLE
Mautic.org site documentation UX scroll case (incorect scroll position).

### ISSUE THREAD

**Issue by Techmind** [mautic/mautic#7038]
Not sure, that this is the right place for this sort of issue.

Loom video explaining: https://www.useloom.com/share/207dd7c3cbde4f1d8f3e560698e57455

## Bug Description
Text description: 
Trying to read the documentation on site is irritating because then you click on the link at the side menu  (table of contents) scroll stays at the same height.

Browser: Chromium Version 67.0.3396.99
OS: Ubuntu 16.04

### Steps to reproduce
1. Go to https://www.mautic.org/docs/en/index.html
2. Click '6.1.2. Bounce Management'
3. A page opens with scroll position at the middle of the page

Expected:
3. A page opens with scroll position at the top of the page

**Comment by npracht** [comment]
@escopecz with beta of github you might be able to move the issue to mautic/documentation repo. Could you ? :)

**Comment by escopecz** [comment]
Issue moved to [mautic/documentation #300](https://github.com/mautic/documentation/issues/300) via [**ZenHub**](https://www.zenhub.com/)
