### ISSUE TITLE
Abnormal number of IPs added to Leads

### ISSUE THREAD

**Issue by pety-dc** [mautic/mautic#7039]
## Bug Description
I experianced ever growing cpu usage when using mautic tracking service. I tried to optimize mautic as much as I could, but processes with 100% cpu usage for seconds still remained. I tried to debug it with symfony profiler, but that could not tell which function was taking too long (cpu)

Then I started to debug how "mtracking.gif" is served and from block to block I discovered that it was the loading of a Lead entitiy that made the cpu work for seconds.

I found that there are around 100 leads (in a 100k contact pool) that has more than 30000 IP addresses connected to it in `lead_ips_xref` table. The many IP address connections were there in that table, yet in the contact data page under the Audit log tab there were no trace of this many. So I figured this must be a bug.

After deleting these records from the `lead_ips_xref` table the server load went back to normal.

I have no idea how to reproduce it. 

Mautic instance is behind proxy, the proxy is set as trusted proxy.

| Q   | A
| --- | ---
| Mautic version | 2.14.1
| PHP version | 7.0.23
| Browser | FF60

### Steps to reproduce
I have no idea how to reproduce it. 
 
### Log errors
-

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Do you have the IP and/or fingerprint tracking turned on?

**Comment by pety-dc** [comment]
Sure, I have all three (identify by IP, identify by device fingerprint, identify by tracking url) turned on in _Mautic tracking settings_

**Comment by escopecz** [comment]
Ok, then turn the IP and fingerprint off. The iPhone devices can have all the same fingerprint and so Mautic thinks it's the same contact.

**Comment by pety-dc** [comment]
I dug into it and noticed that there is also a very high number of contact merges for users having abnormal number of IP address linked to.

`SELECT lead_id, count(*) cnt FROM `lead_ips_xref` GROUP BY lead_id ORDER BY cnt DESC `
results:

`lead_id | cnt   1 |  
-- | -- | --
85691 | 10317
313293 | 3088
217272 | 778
374256 | 706
378346 | 518
377564 | 439
320553 | 407
376823 | 373
343437 | 279`




`SELECT contact_id, count(distinct(merged_id)) cnt FROM `contact_merge_records` GROUP BY contact_id ORDER BY cnt DESC `
results:
`contact_id | cnt   1 |  
-- | -- | --
85691 | 193001
313293 | 2928
55005 | 1549
217272 | 777
374256 | 658
309925 | 638
227395 | 621
252036 | 605
165582 | 575
253857 | 535
378346 | 482
`

The mautic tracker code is inserted in the host webpage. How is mautic supposed to identify anonymous contacts if both IP and fingerprint is turned off?

**Comment by escopecz** [comment]
Mautic use cookie ID tracking by default.

**Comment by pety-dc** [comment]
Ok, thanks

I thought these features are to mitigate the effect of browser that forbid using of third party / tracking cookies by default. But they seem to be useless currently as they have less benefit than the confusion they create via needless merges
Will there be a better version of these features in the future?

**Comment by escopecz** [comment]
These types of tracking proved to be inaccurate in some cases and therefore they are disabled by default. We cannot remove them in Mautic 2 because it would be a BC break.
