### ISSUE TITLE
Mautic with hyphen hostname send Emails with broken image if 'Convert embed images to Base64' is off

### ISSUE THREAD

**Issue by katzueno** [mautic/mautic#7040]
## Bug Description

This bug only happens with Mautic which is installed on the site which hostname include hyphen.
You turn `Convert embed images to Base64` off in Configuration menu. Send out HTML email with image embed.

Gmail shows broken images.

![broken image](https://user-images.githubusercontent.com/485751/50328167-7a9c9b00-0535-11e9-8534-9241484233db.png)

If you turn `Convert embed images to Base64` back on, the image shows up properly.
(We were able to re-produce at two different environment client's Mautic with main hostname with hyphen & our own test environment which subdomain include hyphen.)

| Q   | A
| --- | ---
| Mautic version | 2.14.2 & 2.15.0
| PHP version | 7.1.18 & 7.1.22
| Browser | Chrome

### Steps to reproduce
1. Install mautic with hostname with hyphen (e.g., `mautic-demo.example.com`, `mautic-example.com`)
1. Create an email with embed image
2. Set `Convert embed images to Base64` as off in Configuration menu
3. Send an sample email to anywhere
4. You get 404 image emails
 
### Log errors

Email source where it's 404.

```
                                    </div><div data-slot=3D"image">
<img src=3D"http://XXXXX-XXXXX.XXX.XX/media/images/52091eee46c12cc656f933f5=
c76afa45.jpeg" alt=3D"An image" class=3D"fr-view" style=3D"" /><br />
<div style=3D"clear:both"></div>
```

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
