### ISSUE TITLE
Out of memory while running mautic:campaigns:rebuild console command

### ISSUE THREAD

**Issue by tuananh-oralius** [mautic/mautic#7041]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | YES
| Feature request? | NO
| Enhancement? | NO

## Description:
Get out of memory error when run mautic:campaigns:rebuild

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1

**Memory Limit**
File: php.ini
memory_limit = 4095M
 ** Total Contacts**
4,855,925
** RAM **
8GB

### Steps to reproduce:
1. Run PHP console command to rebuild campaigns /usr/bin/php /var/www/html/mautic/app/console mautic:campaigns:rebuild
 
### Log errors: 

vnapps_feedback@instance-1:~$ sudo /usr/bin/php /var/www/html/mautic/app/console                                                                                                                                    mautic:campaigns:rebuild --force
Rebuilding contacts for campaign 1
0 total contact(s) to be added in batches of 300
4223567 total contact(s) to be removed in batches of 300
       0/4223567 [>---------------------------]   0%PHP Fatal error:  Allowed me                                                                                                                                   mory size of 4293918720 bytes exhausted (tried to allocate 3446430672 bytes) in                                                                                                                                    /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection                                                                                                                                   .php on line 104

  [Symfony\Component\Debug\Exception\OutOfMemoryException]
  Error: Allowed memory size of 4293918720 bytes exhausted (tried to allocate
   3446430672 bytes)

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by heathdutton** [comment]
This isn't an issue I'm currently able to reproduce. We have campaigns with tens of millions of leads. It odd that it's trying to load 3.4 Gb of data from only 300 contacts. Something funny is going on there. Maybe you have some mega-huge fields?

Here's somethings to try:
* Using `--batch-limit=100` to get only 100 leads at once.
* Using `---env=dev -vvv` to debug the output and see where the memory limit exception is happening.

Other concerns:
* Don't use `--force` unless you absolutely have to, as it will result in SQL errors and increased overhead in the long run.
* Try not to run as sudo, this means your log files may be generated as root, and your web app may be running as ec2-user or webapp and may not be able to open/append them causing exceptions.

**Comment by tuananh-oralius** [comment]
These contacts are very simple. They only contains emails, no mega-huge fields?
I tried use **--batch-limit=100** but the error is the same
**Log:**
 /usr/bin/php /var/www/html/mautic/app/console mautic:campaigns:rebuild --batch-limit=100 -vvv
Rebuilding contacts for campaign 1
0 total contact(s) to be added in batches of 100
4223567 total contact(s) to be removed in batches of 100
       0/4223567 [>---------------------------]   0%PHP Fatal error:  Allowed memory size of 4293918720 bytes exhausted (tried to allocate 3446430672 bytes) in /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 104


  [Symfony\Component\Debug\Exception\OutOfMemoryException]
  Error: Allowed memory size of 4293918720 bytes exhausted (tried to allocate 3446430672 bytes)


Exception trace:
 () at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104

I tried this command: **/usr/bin/php /var/www/html/mautic/app/console mautic:campaigns:rebuild --batch-limit=100 --env=dev**

New error is showed:
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "WebProfilerBundle" from namespace "Symfony\Bundle\WebProfilerBundle".
Did you forget a "use" statement for another namespace? in /var/www/html/mautic/app/AppKernel.php:233
Stack trace:
#0 /var/www/html/mautic/vendor/symfony/http-kernel/Kernel.php(431): AppKernel->registerBundles()
#1 /var/www/html/mautic/app/AppKernel.php(272): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/html/mautic/vendor/symfony/framework-bundle/Console/Application.php(62): AppKernel->boot()
#3 /var/www/html/mautic/vendor/symfony/console/Application.php(117): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/mautic/app/console(41): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}
  throw in /var/www/html/mautic/app/AppKernel.php on line 233

I don't use --force and sudo anymore but the error is not fixed

**Comment by tuananh-oralius** [comment]
I don't install any third-party plugin. I tried to delele all PHP source code and download newest source code package 2.15.0 to replace but the error still showed. Finally, I deleted the campaign which cause the error, everything is ok now.
