### ISSUE TITLE
Amazon SNS subscription never get confirmed

### ISSUE THREAD

**Issue by TiagoGouvea** [mautic/mautic#7043]
## Bug Description
I created a new topic on Amazon SNS and I'm trying to confirm a subscription. I entered the callback url there like "http://mymauticsite.com/mailer/amazon/callback" and it stuck on "PendingConfirmation".
Looking to system log I saw last lines saying that `AmazonTransport::processCallbackRequest()` must receive a callback.

By this way, it never got confirmed on amazon.

I followed the [documentation](https://www.mautic.org/docs/en/emails/bounce_management.html) to do this.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 5.6.30
| Browser | Chrome

### Steps to reproduce
1. Create a new topic on Amazon SNS
2. Create a subscription with amazon/callback url
 
### Log errors

`[2018-12-22 09:56:28] mautic.ERROR: PHP Error - Argument 1 passed to Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport::processCallbackRequest() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in /home/../mautic/app/bundles/EmailBundle/EventListener/EmailSubscriber.php on line 172 and defined - in file /home/../mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php - at line 97 [] []`

**Comment by Woeler** [comment]
A fix for this is already available https://github.com/mautic/mautic/pull/7015

**Comment by Woeler** [comment]
Nice @TiagoGouvea

**Comment by dbritopt** [comment]
@TiagoGouvea and @Woeler life saver, thank you guys very much
