### ISSUE TITLE
Report Graph Widget gives error when added to dashboard in 2.15.0

### ISSUE THREAD

**Issue by gpetrov** [mautic/mautic#7044]
## Bug Description
When a report is created using visitors hits graph type, it works all well from the ports section, but when added to the dashboard an error is displayed.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.33
| Browser | Chrome 71

### Steps to reproduce
1. Create a report of with data sources: Pages Page Hits
2. Run the report so it shows data fine
3. Add the reports to the dashboard as graph widget
4. The above error will be displayed

![image](https://user-images.githubusercontent.com/504730/50376908-67143180-0614-11e9-9282-c532943a826f.png)
 
### Log errors
No errors are shown in the log

**Comment by RCheesley** [comment]
@gpetrov sorry for the very late response to your bug report! I am able to replicate this on 2.15.3.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing as unable to reproduce in Mautic 3.x
