### ISSUE TITLE
v2.5.0: URI-encoded lead email addresses are not decoded prior to updating field

### ISSUE THREAD

**Issue by yrammos** [mautic/mautic#7047]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Lead email addresses updated via the `mt` script contain a URI-encoded rather than literal ampersand (i.e. contain `%40` in lieu of a literal `@` character). The lead’s email field thereafter contains corrupt data and all emails to that lead bounce.

It is possible that the same issue applies to addresses updated via the tracking pixel (unfortunately I have already downgraded to 2.14.2 and can no longer test).

| Q   | A
| --- | ---
| Mautic version | 2.5.0
| PHP version | 7.2
| Browser | Any

### Steps to reproduce
1. Create a web page including the standard Mautic tracking code.
2. Assign a valid email address to `$.email`.
3. In the HTML body insert the following:

```
<script>
mt('send', 'pageview', {email: $.email}, {
   onload: function() {},
   onerror: function() {}
});
</script>
 ```
Result: The the lead’s email address is updated with a URI-encoded email address.

Please note that exactly the same web page works as expected under Mautic 2.14.2/PHP7.0.

### Log errors

None.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Woeler** [comment]
Are you passing uri encoded data to mt? Because you should not post pre-encoded data to mt.

**Comment by yrammos** [comment]
Yes, I am. I take your point, thank you, but why is the behavior changed in 2.15.0?
