### ISSUE TITLE
v2.5.0: Email builder failing to parse and save specific HTML

### ISSUE THREAD

**Issue by yrammos** [mautic/mautic#7048]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.5.0
| PHP version | 7.2
| Browser | Any

### Steps to reproduce
1. Create a new email in the Mautic email builder.
2. Selecting the code mode instead of a template, use the HTML at https://gist.github.com/yrammos/3394aefd8fe388846f5f97c09a895f1b (FWIW, this HTML was generated by MJML).
3. Click on “apply”.
4. The progress wheel keeps on spinning indefinitely.
5. In an effort to circumnavigate the problem and still save the email, click on “close”.
6. Click on “Save”.
7. Reopen the builder and look at the preview of the rendered email.
8. The email does not have the intended appearance because the builder has apparently altered the HTML.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
fixed in last version https://github.com/mautic/mautic/pull/6938

**Comment by yrammos** [comment]
Actually I am referring to that last version (2.15.0 stable).

**Comment by kuzmany** [comment]
And works before or not? 
Cause I am using MJML and this fix works for me.
Although I am not using code mode, just regular templates

**Comment by yrammos** [comment]
It worked on the previous stable version (2.14.2, I believe). I don’t use test builds so I can’t tell in which pre-2.15.0 commit the bug was introduced.

**Comment by kuzmany** [comment]
This PR fixed MJML in 2.15.0
https://github.com/mautic/mautic/pull/6938

I will test your template later

**Comment by yrammos** [comment]
Thanks for testing, @kuzmany. 

The “template” worked on 2.14.2, so #6938 is either incomplete or irrelevant to this issue.

**Comment by luizeof** [comment]
Outlook tags has errors

![mautic-error-tags](https://user-images.githubusercontent.com/257004/50495882-3e74a900-0a13-11e9-90ac-80743250b1d6.png)

**Comment by kuzmany** [comment]
@luizeof please try and test https://github.com/mautic/mautic/pull/7071

**Comment by luizeof** [comment]
@kuzmany same error :(

![captura de tela 2018-12-30 as 12 35 04](https://user-images.githubusercontent.com/257004/50548194-8bcd6200-0c2f-11e9-8023-39d448886c9e.png)

**Comment by kuzmany** [comment]
@luizeof please send me copy of your html code

**Comment by luizeof** [comment]
I'm using topol.io to Generate HTML

[S1t_DUibV.zip](https://github.com/mautic/mautic/files/2723211/S1t_DUibV.zip)

**Comment by kuzmany** [comment]
@luizeof can you re-test?

**Comment by kuzmany** [comment]
Guys, works this https://github.com/mautic/mautic/pull/7071 or on?

**Comment by raribeiro** [comment]
I had this problem. I upgraded to version 2.15.0 from the command line.

For some reason the file below was not updated during the process.

**/app/bundles/CoreBundle/Helper/InputHelper.php**

I downloaded the file in the master and updated it manually, problem solved for me.
