### ISSUE TITLE
Sendgrid API not working with pipe character “|” in email content

### ISSUE THREAD

**Issue by dichvuhuuich** [mautic/mautic#7052]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1.25
| Browser | Chrome Version 71.0.3578.98 (Official Build) (64-bit)

### Steps to reproduce
1. Configure using Sendgrid API in Email Settings
2. Create New Template Email using pipe character “|” in email content and title example like this
Dear {contactfield=title|Ms} {contactfield=firstname}
3. Go into a contact and send example email.

User received email with title normally but in email content, code {contactfield=title|Ms} will show, not user's title or Ms.
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!
