### ISSUE TITLE
REST APIs - Get all the different messages sent in campaign, their open count and clicks?

### ISSUE THREAD

**Issue by dhirendradaffodil** [mautic/mautic#7053]
Hello,
I am using REST apis in my website. I want to get all the different emails that were sent under a campaign. Also how can i get all the counts/list of users who had clicked on and opened the emails using rest?

**Comment by escopecz** [comment]
Check data accessible through https://developer.mautic.org/#get-available-stat-tables

**Comment by dhirendradaffodil** [comment]
@escopecz  , there is no column in table to get count of click. How can i get the clicks counts? And what will be the search query to get opens and clicks for a campaign.

**Comment by escopecz** [comment]
You can check the source code of the SQL queries in Mautic returning this data. But I think that you'll need to join like 3 tables to get that so it will be almost impossible to get via API. You'd have to download the tables via API and query them afterwards. The email clicks are in the page_hits table with source of the email you are interested in. Maybe a custom plugin could serve such data for you.

**Comment by dhirendradaffodil** [comment]
@escopecz  
Here is the requirement

- I have done to add specific subscribers to a list using API.
- Now we need to fetch all campaign list details.
- Drops email list details(Email template details as in Campaign) with respect to campaign id.
- After that, we need to know **open**, **click** status of specific email id with respect to Email template id(email subject id).

Hope this makes sense.

Thanks
