### ISSUE TITLE
Cannot apply change to campaign

### ISSUE THREAD

**Issue by otsang** [mautic/mautic#7055]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.14.2
| PHP version |  PHP Version 7.1.23
| Browser | Chrome

### Steps to reproduce
1. Go into campaign
2. Click into a campaign
3. Edit Campaign
4. Launch Campaign Builder
5. Add one contact field value change
6. Apply change
7. Change will not apply, grey button (see below)
![apply change](https://user-images.githubusercontent.com/45982673/50452902-d24e5400-08f1-11e9-8278-b8fa47fc6237.png)

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Please provide error messages from logs.

**Comment by otsang** [comment]
This has been resolved.
