### ISSUE TITLE
Re-schedule sent email over and over

### ISSUE THREAD

**Issue by Carlos-mb** [mautic/mautic#7057]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

When Mautic tries to send a marketing email already sent to the contact, the event is rescheduled over and over and add many records to notifications table reporting that the email couldn't be sent.  

EDIT: mautic:campaigns:trigger has no end and generates hundreds records per second. 

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.33
| Browser | Chrome

### Steps to reproduce
1. Create two campaigns
2. Create a Template email
3. Create events in both campaign to send the email. Mark it as "Marketing" email. 
4. Once the email is sent by one campaign, the other doesn't send the email and notifies the error, but reschedule the event over and over and (again) notifies the error. 

I have to truncate the notifications table because it has tens of thousand records every day.
 
### Log errors

No errors in log file

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Carlos-mb** [comment]
I have seen that 

app/console mautic:campaigns:trigger 

Is creating infinite events...

This is a capture of terminal screen: 

Triggering scheduled events
2123 total events(s) to be processed in batches of 100 contacts
 14100/14100 [============================] 100%^C

I have to stop it because it never ends. 

I guess this is new. I don't know what have I done while trying to fix the original issue but now it's a bigger problem :(

**Comment by Carlos-mb** [comment]
I have cloned the two campaings and it appears to work. 

Why?

I don't know.

**Comment by andrekutianski** [comment]
perhaps this issue is not the same as #6971 ?

**Comment by Carlos-mb** [comment]
> perhaps this issue is not the same as #6971 ?

I guess it's the same although the behavior I describe is a bit different. 

In my case, it works fine until is fails and I have to clone the campaign. And when it fails, it never stops trying, I have to kill the process. 

But I think it's the same issue.
