### ISSUE TITLE
Menus and Form After Update

### ISSUE THREAD

**Issue by jacosky** [mautic/mautic#7059]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Since I updated my mautic app to the latest version, some menus like Forms, Emails stopped working. Also, the form integrated on my site through Focus Items stopped displaying.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.15.0
| PHP version | 5.6.39

### Steps to reproduce:
1. Update from v2.13.1 to the latest v2.15.0
2. 
 
### Log errors: 

[26-Dec-2018 22:41:28 UTC] exception 'Doctrine\DBAL\Driver\Mysqli\MysqliException' with message 'Unknown column 't0.headers' in 'field list'' in .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:101
Stack trace:
#0 .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php(120): Doctrine\DBAL\Driver\Mysqli\MysqliStatement->__construct(Object(mysqli), 'SELECT t0.is_pu...')
#1 .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(844): Doctrine\DBAL\Driver\Mysqli\MysqliConnection->prepare('SELECT t0.is_pu...')
#2 .../vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(712): Doctrine\DBAL\Connection->executeQuery('SELECT t0.is_pu...', Array, Array)
#3 .../vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(730): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, Object(Proxies\__CG__\Mautic\EmailBundle\Entity\Email))
#4 .../vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php(189): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadById(Array, Object(Proxies\__CG__\Mautic\EmailBundle\Entity\Email))
#5 .../app/cache/prod/doctrine/orm/Proxies/__CG__MauticEmailBundleEntityEmail.php(1366): Doctrine\ORM\Proxy\ProxyFactory->Doctrine\ORM\Proxy\{closure}(Object(Proxies\__CG__\Mautic\EmailBundle\Entity\Email), 'isVariant', Array)
#6 .../app/cache/prod/doctrine/orm/Proxies/__CG__MauticEmailBundleEntityEmail.php(1366): Closure->__invoke(Object(Proxies\__CG__\Mautic\EmailBundle\Entity\Email), 'isVariant', Array)
#7 .../app/bundles/EmailBundle/Model/EmailModel.php(510): Proxies\__CG__\Mautic\EmailBundle\Entity\Email->isVariant()
#8 .../app/bundles/EmailBundle/Controller/PublicController.php(112): Mautic\EmailBundle\Model\EmailModel->hitEmail('5c23f2ea26cee', Object(Symfony\Component\HttpFoundation\Request))
#9 [internal function]: Mautic\EmailBundle\Controller\PublicController->trackingImageAction('5c23f2ea26cee')
#10 .../vendor/symfony/http-kernel/HttpKernel.php(135): call_user_func_array(Array, Array)
#11 .../vendor/symfony/http-kernel/HttpKernel.php(57): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#12 .../vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 .../vendor/symfony/http-kernel/Kernel.php(183): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 .../app/AppKernel.php(141): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 .../app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 .../app/middlewares/CatchExceptionMiddleware.php(45): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 .../app/middlewares/VersionCheckMiddleware.php(57): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 .../vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 .../vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#20 .../index.php(37): Stack\run(Object(Stack\StackedHttpKernel))
#21 {main}

Next exception 'Doctrine\DBAL\Exception\InvalidFieldNameException' with message 'An exception occurred while executing 'SELECT t0.is_published AS is_published_1, t0.date_added AS date_added_2, t0.created_by AS created_by_3, t0.created_by_user AS created_by_user_4, t0.date_modified AS date_modified_5, t0.modified_by AS modified_by_6, t0.modified_by_user AS modified_by_user_7, t0.checked_out AS checked_out_8, t0.checked_out_by AS checked_out_by_9, t0.checked_out_by_user AS checked_out_by_user_10, t0.id AS id_11, t0.name AS name_12, t0.description AS description_13, t0.subject AS subject_14, t0.from_address AS from_address_15, t0.from_name AS from_name_16, t0.reply_to_address AS reply_to_address_17, t0.bcc_address AS bcc_address_18, t0.template AS template_19, t0.content AS content_20, t0.utm_tags AS utm_tags_21, t0.plain_text AS plain_text_22, t0.custom_html AS custom_html_23, t0.email_type AS email_type_24, t0.publish_up AS publish_up_25, t0.publish_down AS publish_down_26, t0.read_count AS read_count_27, t0.sent_count AS sent_count_28, t0.variant_sent_count AS variant_sent_count_29, t0.variant_read_count AS variant_read_count_30, t0.revision AS revision_31, t0.lang AS lang_32, t0.variant_settings AS variant_settings_33, t0.variant_start_date AS variant_start_date_34, t0.dynamic_content AS dynamic_content_35, t0.headers AS headers_36, t0.public_preview AS public_preview_37, t0.category_id AS category_id_38, t0.translation_parent_id AS translation_parent_id_39, t0.variant_parent_id AS variant_parent_id_40, t0.unsubscribeform_id AS unsubscribeform_id_41, t0.preference_center_id AS preference_center_id_42 FROM mauw5_emails t0 WHERE t0.id = ?' with params [5]:

Unknown column 't0.headers' in 'field list'' in .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71
Stack trace:
#0 .../vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\Mysqli\MysqliException))
#1 .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\Mysqli\Driver), Object(Doctrine\DBAL\Driver\Mysqli\MysqliException), 'SELECT t0.is_pu...', Array)
#2 .../vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(712): Doctrine\DBAL\Connection->executeQuery('SELECT t0.is_pu...', Array, Array)
#3 .../vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(730): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load(Array, Object(Proxies\__CG__\Mautic\EmailBundle\Entity\Email))
#4 .../vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php(189): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadById(Array, Object(Proxies\__CG__\Mautic\EmailBundle\Entity\Email))
#5 .../app/cache/prod/doctrine/orm/Proxies/__CG__MauticEmailBundleEntityEmail.php(1366): Doctrine\ORM\Proxy\ProxyFactory->Doctrine\ORM\Proxy\{closure}(Object(Proxies\__CG__\Mautic\EmailBundle\Entity\Email), 'isVariant', Array)
#6 .../app/cache/prod/doctrine/orm/Proxies/__CG__MauticEmailBundleEntityEmail.php(1366): Closure->__invoke(Object(Proxies\__CG__\Mautic\EmailBundle\Entity\Email), 'isVariant', Array)
#7 .../app/bundles/EmailBundle/Model/EmailModel.php(510): Proxies\__CG__\Mautic\EmailBundle\Entity\Email->isVariant()
#8 .../app/bundles/EmailBundle/Controller/PublicController.php(112): Mautic\EmailBundle\Model\EmailModel->hitEmail('5c23f2ea26cee', Object(Symfony\Component\HttpFoundation\Request))
#9 [internal function]: Mautic\EmailBundle\Controller\PublicController->trackingImageAction('5c23f2ea26cee')
#10 .../vendor/symfony/http-kernel/HttpKernel.php(135): call_user_func_array(Array, Array)
#11 .../vendor/symfony/http-kernel/HttpKernel.php(57): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#12 .../vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php(67): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 .../vendor/symfony/http-kernel/Kernel.php(183): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 .../app/AppKernel.php(141): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 .../app/middlewares/CORSMiddleware.php(93): AppKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 .../app/middlewares/CatchExceptionMiddleware.php(45): Mautic\Middleware\CORSMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 .../app/middlewares/VersionCheckMiddleware.php(57): Mautic\Middleware\CatchExceptionMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 .../vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Mautic\Middleware\VersionCheckMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 .../vendor/stack/run/src/Stack/run.php(13): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#20 .../index.php(37): Stack\run(Object(Stack\StackedHttpKernel))
#21 {main}

**Comment by kuzmany** [comment]
Your db schema wasnt update. 
Please read https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

**Comment by jacosky** [comment]
I'm sorry about the late response. The schema update was the issue. I has been updated and Mautic is running fine.

**Comment by npracht** [comment]
Thanks !
