### ISSUE TITLE
$contactApi->edit() adds stage change to contact history

### ISSUE THREAD

**Issue by eschiendorfer** [mautic/mautic#7064]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When I edit a contact trough API, which has a stage, the edit method will add an unwanted (?) stage change to the contacts history.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.33
| Browser | Chrome

### Steps to reproduce
Just update a contact, which has a stage set. Here is a simple example:

```
$data = array(
     'email' => $customer->email.'_test',
     'firstname' => $customer->firstname,
     'lastname' => $customer->lastname,
 );

$contactApi->edit($id_contact, $data);
```
 
### Log errors
The edit code itself works fine (data is updated). But the result for contact history is on the screenshot:
![stages](https://user-images.githubusercontent.com/15154932/50485602-4114d580-09f6-11e9-90f3-e3cd1118ce1c.JPG)
There is no stage change at all. But the entries are added automatically.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Closing ass resolved according to #7183
