### ISSUE TITLE
Update from 2.13.1 to 2.15.0 fails due to db migration

### ISSUE THREAD

**Issue by afonseca08** [mautic/mautic#7067]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I attempted an update from version 2.13.1 to 2.15.0 using the command line and the update failed due to a database migration. Specifically, it looks like the lead_devices table does not contain the tracking_id column which the migration is trying to set as unique. I have verified the column does not exist in the lead_devices table.

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.1.4
| Browser | Chrome Version 71.0.3578.98 (Official Build) (64-bit)

### Steps to reproduce
1. Open command line to Mautic root directory
2. Run 'php app/console mautic:update:find' and note that 2.15.0 is available
3. Run 'php app/console mautic:update:apply'
4. Observe the following output in the console with error notification in red:
![screenshot 2018-12-27 23 43 56](https://user-images.githubusercontent.com/863419/50507579-ec438000-0a32-11e9-8153-8462ef11bb65.png)

5. Open the log file in app/logs and see the output.
6. Attempt to navigate to the Mautic dashboard in the browser and get a too many redirects error. The site is now broken:
![screenshot 2018-12-27 23 51 43](https://user-images.githubusercontent.com/863419/50507426-67f0fd00-0a32-11e9-8cca-3c8ade37beb5.png)

 
### Log errors
`[2018-12-28 07:25:20] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `lead_devices` ADD UNIQUE `tracking_id` (`tracking_id`);':  SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'tracking_id' doesn't exist in table (uncaught exception) at /app/public/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 while running console command `doctrine:migrations:migrate` [] []
`

See lead_devices table structure:
![screenshot 2018-12-27 23 56 40](https://user-images.githubusercontent.com/863419/50507631-2876e080-0a33-11e9-9d55-702263cdf5ca.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Follow https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful to fix your database schema.

**Comment by mauwiks** [comment]
The commands aren't working no more
