### ISSUE TITLE
Extra properties in pageview event not being recognized

### ISSUE THREAD

**Issue by quintmouthaan** [mautic/mautic#7068]
## Bug Description
| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.1.23
| Browser | Safari 12.0.2

### Steps to reproduce
1. Add the tracking code to a custom webpage
2. Send a pageview event with custom parameters, like this: 
`mt('send', 'pageview', { email: "some@email.com", firstname: "Firstname", lastname: "Lastname" });`
3. In the network tab of the browser developer tools I can see that the event is being send to mautic with the correct parameters
![image](https://user-images.githubusercontent.com/39469362/50515725-a32d1380-0aa6-11e9-838e-7bfc2ad0843e.png)
4. In Mautic the event is registered at the previously known Visitor without the additional information. While I was expecting a new Contact to be created with the given email and first and last name.
![image](https://user-images.githubusercontent.com/39469362/50515784-f4d59e00-0aa6-11e9-82ce-30026e714ef7.png)

There are no errors and the request is returning 200. This is basically preventing me from using Mautic because the contact is never recognized. I tried using the tracking pixel and if I use the tracking pixel, the contact is getting recognized and the email and name fields do get populated, but then it seems a lot of other functionality is not working as expected.

### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by quintmouthaan** [comment]
Update for others encountering a similar issue: a reinstall of the bitnami Azure mautic package has solved the problem. Still no idea why it didn't work on the other environment...

**Comment by npracht** [comment]
Are your custom fields publicly updatable?

**Comment by quintmouthaan** [comment]
yes, I made them publicly updatable and I do see that they are updated if I pass the values using the tracking pixel
