### ISSUE TITLE
Statistics show pending email after sending

### ISSUE THREAD

**Issue by sidneydevelop** [mautic/mautic#7069]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
A basic question in this new version v2.15.0 I am validating and after sending the statistics continues informing that it is pending, but clicking on it does not have email pending, is only counted.

| Q   | A
| --- | ---
| Mautic | 2.15.0
| PHP | 7.2.12
| Nginx | 1.15.6
| Chrome | 71

### Steps to reproduce
1. I created the thread with only my test contact
2. Add my contact in the created test thread.
3. I created a new segment email and triggered the email.
4. Email sent successfully, in statistics it continues to appear that the email is still pending, but it already appears that was sent and read.

![screenshot_1](https://user-images.githubusercontent.com/10811621/50517063-7b817f80-0a95-11e9-9845-881b6f4bea57.png)

 
### Log errors
My logs are empty.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by johbuch** [comment]
related to this one https://github.com/mautic/mautic/issues/7003

**Comment by sidneydevelop** [comment]
@johbuch thank you for the warning.

**Comment by npracht** [comment]
Closing in favor of #7003.

**Comment by npracht** [comment]
Hi @sidneydevelop please test https://github.com/mautic/mautic/pull/7079 ! :)
