### ISSUE TITLE
Mysql table empty for lead_fields and no ip data being issued.

### ISSUE THREAD

**Issue by bulgin** [mautic/mautic#7077]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.2.13 but persists with downgrade to 5
| Browser | Firefix Quantum 64 bit as well as Chrome Version 71.0.3578.98 (Official Build) (64-bit)
| OS | Centos 7
### Steps to reproduce
1. Make new install, preferably in above system.
2. tail -f mautic_prod-2019-01-02.php
 3. Issue: Mautic not reporting geographic city/country etc. in reports or map with either ip2.location or MaxMind and seeing the following errors in logs.

### Log errors
[2019-01-02 20:45:46] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bla_table.lead_fields' doesn't exist [] []

But the field does exist see:

![lead](https://user-images.githubusercontent.com/16614115/50617251-2e991100-0eba-11e9-845e-707ff43e8fbd.jpg)

Another bug report identical to this was reported under the title of PHP Warning - preg_match(): Compilation failed: nothing to repeat at offset 14,#7063 

but I wanted to report this as a MySql issue.  

Feel free to merge if you think appropriate.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Please search for the error messages before you create a new issue or spend time on an investigation. The missing lead_fields table error is [a known issue](https://github.com/mautic/mautic/issues/3436) but it doesn't harm so no one invested time to fix it so far.
