### ISSUE TITLE
Improve phone validation

### ISSUE THREAD

**Issue by icetique** [mautic/mautic#7078]
Forcing the user to use E164 format is one of possible solutions to use libphonenumber. I think the most user-friendly way is to allow user to specify the phone number in any format he wants and then convert it to E164 format using libphonenumber. This is actually done in the first example in the libphonenumber-php docs:
https://github.com/giggsey/libphonenumber-for-php#quick-examples

This way we could show error only if the number is non-convertable to E164 istead of showing error if user does not type the phone number in E164 format (which isn't expected by users).

However this would require to assume user's country or add a new field "Phone country" before performing validation.

**Comment by kuzmany** [comment]
If you are interest, for small budget I can resolve it.

https://www.bountysource.com/issues/68196644-improve-phone-validation

**Comment by icetique** [comment]
Also, you can actually specify the phone in a non-E164 format and it will let it through. Such as +48 555 555 555. By changing the way libphonenumber is used (always with Phone Country field), you can always check the validity of the phone for the selected country and always get number in a E164 format. Right now it doesn't seem you always store number in a E164 format.

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
