### ISSUE TITLE
bug with email reports and the date range filter

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#7096]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
There is a problem with email reports (data source emails).
Once the report is created, if you modify the date range, emails, that were created before the date you set on the report, won't display.

For example, you want to see the monthly evolution of email 1.
Email 1 was created in 06/2018 but is still sent within a campaign.
In the report you chose the date range 2018/10.
--> so this email 1 won't be displayed in the report. 
--> means it is not possible to follow up monthly statistic.

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 
| Browser | 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
PR : https://github.com/mautic/mautic/pull/7214
