### ISSUE TITLE
Mautic not functioning with GeoLocation after upgrade 2.15.0

### ISSUE THREAD

**Issue by bulgin** [mautic/mautic#7098]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.33
| Browser | All
| Server | Generic Hosting service. CENTOS 7.6 kvm.
| System PHP | PHP-FPM Status: On
| Other Server Attributes | allow_url_fopen is on, EasyApache4, Apache 2.4. Generic Install

### Steps to reproduce
1. Do generic (repeat, generic) install on Centos 7/ WHM/Cpanel with php version 7.0.33 (standard virtual hosting package (see above attributes).
2. GeoLocation on maps and Country City does not report.
3. I strongly recommend that engineers do a generic install as per above before dismissing this report for lack of logs, error reports, etc. of which there are none to be found in the Mautic log or system log files.
 
### Log errors
None other than those included in previous issue (#7077) which was dismissed as insignificant.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

![mautic version issues](https://user-images.githubusercontent.com/16614115/50649670-8718ee80-0f4c-11e9-8712-20b6244fe605.jpg)

**Comment by RCheesley** [comment]
@bulgin following up on this rather old issue - is it still a problem? Did you make sure you had pulled down the data from the maxmind database? Let us know if this is still an issue with 2.15.3 and if so please give some more details so we can help troubleshoot. If I don't hear back in a week I'll close down the issue.

**Comment by altomarketing** [comment]
Detect the problem here:
Mautic tries to download http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz  but this file does not exist anymore from December 30, 2019 
Check https://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by npracht** [comment]
Isn't it fixed in 2.16.0 with https://github.com/mautic/mautic/pull/8337
@bulgin can you please test your instance on 2.16.0 and confirm it works then ?

**Comment by bulgin** [comment]
Yes, the Mautic instance is not downloading from that url because Maxmind no longer allows it.  I can manually login into my maxmind account and download geolite Country or geolite City, but of course that's not an automated process.  Or, maybe it is downloading but I have no idea where in Mautic this file should exist - if someone wants to direct me to the directory I'll check it out.  FYI I moved away from maxmind because of this and instead use the ip2location webservice which works fine although the free service has a limit on requests.

**Comment by bulgin** [comment]
From Maxmind:

Hello, 

Thank you for contacting support. It's correct that on 2019-12-30, we started requiring GeoLite2 databases to be downloaded through an account, rather than a public URL. Detailed information about this change is available at https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/. 

For a replacement URL, in our account portal, we provide permalinks at https://www.maxmind.com/en/accounts/current/geoip/downloads (login required) that can be used to download the databases. More information about using the permalinks is available in our Support Center at https://support.maxmind.com/geoip-faq/geoip2-and-geoip-legacy-databases/ive-completed-my-geoip2-site-license-purchase-how-do-i-download-the-database/. 

Please note that the permalinks would include you account's license key for authentication, so these links should be treated securely and never shared.

**Comment by altomarketing** [comment]
For those administering their Mautic instance from the command line, the best way to transfer the GeoLite2-City.mmdb file to the app/cache/ip_data/ folder is using the scp command line utility.
 

Then, simply upload the .tar.gz file downloaded from your MaxMind account to your home directory (e.g. /home/ubuntu/GeoLite2-City_20200107.tar.gz) then using the tar -xvzf command, extract the archive. Inside the extracted folder, you will find the GeoLite2-City.mmdb which you should cp to /path/to/mautic/app/cache/ip_data/. If asked to overwrite, type y to indicate “yes.”

Finally, change ownership of the file to the web server user (e.g. apache or www-data) for good measure. chown -R www-data:www-data /path/to/mautic/app/cache/ip_data/GeoLite2-City.mmdb

**Comment by RCheesley** [comment]
Closing as issue was addressed with #8337
