### ISSUE TITLE
[Improvement] Test connection should show state

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#71]
When using test connection (e.g. when setting up Mandrill) under configuration, there is no indicator that cogs are whirring and the connection is indeed being tested, until there is a response back.  

There should be some kind of visual indicator (maybe a spinner or a state change of the button/text string) to say that the test is is in progress (so be patient!).

**Comment by alanhartless** [comment]
The fix to this got snuck into d8a156526b268b1c2b2d6cb2ef2d42ca58bfe319. 

Thanks!
Alan
