### ISSUE TITLE
Cannot set phone field as optional and E164 formatted in the same time

### ISSUE THREAD

**Issue by icetique** [mautic/mautic#7107]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? | N
| Enhancement? | N

## Description:
When phone field is set as optional and E164 format validation is on, the user cannot leave the field empty.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.2.10

### Steps to reproduce:
1. Add form with Phone field
2. Set up Required to Off
3. Set up Validate as international format to On
4. Submit a form without phone number

**Comment by icetique** [comment]
Here is my fix to this. Sorry, but I am not specialist in Git flow, so somebody would need to make it a pull request?

FormValidationSubscriber.php
```
    /**
     * Custom validation     *.
     *
     *@param Events\ValidationEvent $event
     */
    public function onFormValidate(Events\ValidationEvent $event)
    {
        $field = $event->getField();
        $value = $event->getValue();
        if (!$field->getIsRequired() && empty($value)) {
            return;
        }
        if ($field->getType() === 'tel' && !empty($field->getValidation()['international'])) {
            $phoneUtil = PhoneNumberUtil::getInstance();
            try {
                $phoneUtil->parse($value, PhoneNumberUtil::UNKNOWN_REGION);
            } catch (NumberParseException $e) {
                if (!empty($field->getValidation()['international_validationmsg'])) {
                    $event->failedValidation($field->getValidation()['international_validationmsg']);
                } else {
                    $event->failedValidation($this->translator->trans('mautic.form.submission.phone.invalid', [], 'validators'));
                }
            }
        }
    }
```

**Comment by npracht** [comment]
@kuzmany maybe you could carry that quickly ?

**Comment by icetique** [comment]
It seems that you ignored the $field->getIsRequired() condition (by checking the commit's code).

**Comment by kuzmany** [comment]
@icetique  not needed, required validation is on another place.  This just validate If you enable Int phone number format validation. 
Try test on mautibox https://mautibox.com/7130

**Comment by icetique** [comment]
I can confirm the issue is resolved.
