### ISSUE TITLE
Cann't send email with Sparkpost with Mautic 2.15.0 and get error PHP Notice:  Undefined index: substitution_data in SparkpostTransport.php on line 217

### ISSUE THREAD

**Issue by akkarawat2000** [mautic/mautic#7109]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version |    v2.15.0
| PHP version |       Php 5.6.38
| Browser |    Chrome

### Steps to reproduce
1. I use service sparkpost . and send test email it's work fine. but if I create email and send email not 
    working
2.  I run manual cronjob command and check log files it's error 
php /home/lulasala/domains/lulasala.com/public_html/responder/app/console mautic:emails:send > /home/lulasala/domains/lulasala.com/public_html/responder/cron_logs/emails_sends.log 2>&1

PHP Notice:  Undefined index: substitution_data in /home/lulasala/domains/lulasala.com/public_html/responder/app/bundles/EmailBundle/Swiftmailer/Transport/SparkpostTransport.php on line 217

 
### Log errors

This is Log error in my cronjob

PHP Notice:  Undefined index: substitution_data in /home/lulasala/domains/lulasala.com/public_html/responder/app/bundles/EmailBundle/Swiftmailer/Transport/SparkpostTransport.php on line 217

please check from my image below
![cronjob mautic mautic](https://user-images.githubusercontent.com/11753920/50760563-bad07d00-129a-11e9-806d-b8efc5c34473.jpg)

![cronjob mautic mautic-2](https://user-images.githubusercontent.com/11753920/50760611-d3409780-129a-11e9-969d-d180a8165da8.jpg)

![bug-3](https://user-images.githubusercontent.com/11753920/50760709-17339c80-129b-11e9-91de-c55fe36761f8.jpg)

![bug-4](https://user-images.githubusercontent.com/11753920/50760827-624daf80-129b-11e9-9ea1-7f4e1bee1c93.jpg)

![bug-5](https://user-images.githubusercontent.com/11753920/50761038-f28bf480-129b-11e9-9e1b-fc8b3f01997d.jpg)

![bug-6](https://user-images.githubusercontent.com/11753920/50761067-05062e00-129c-11e9-91a0-f0f4ef163545.jpg)

![bug-7](https://user-images.githubusercontent.com/11753920/50761329-b016e780-129c-11e9-8756-a970341d4133.jpg)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by wholanda2** [comment]
Hey,
Did you solve that problem?

**Comment by akkarawat2000** [comment]
No, I still have problem .
Can you slove this problem ?

**Comment by wholanda2** [comment]
I still can't fix it. 
Is your CORS enabled? 

Is your domain already approved in Sparkpost?

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
