### ISSUE TITLE
Mautic hangs at 300 when sending emails

### ISSUE THREAD

**Issue by cuberoot** [mautic/mautic#711]
Thank you for creating Mautic. I think it is very promising!

I am trying to send an email to a list with about 3000 leads with Mautic v1.1.3 on a locally hosted server. The browser always hangs at about 300 emails.

  * I have tried with queuing (plus cron job) and without. 
  * I have tried using mailgun.com over SMTP and using Mandrill
  * I have sending in blocks of 50 and 100
 
I repeated hit the issue that the slider advances to around 300 and then hangs there until I cancel and try again. The very last time I tried, it managed to send the last 680 emails in one go.

**Comment by alanhartless** [comment]
This should have been fixed in 1.2 so closing this for now.  If it's still an issue in 1.2, we'll reopen.

Thanks!
Alan
