### ISSUE TITLE
User with administrator access cannot modify categories created by other users

### ISSUE THREAD

**Issue by guizero** [mautic/mautic#7115]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Even though I am the administrator of my mautic team and there is only one role with full system access, I cannot see or edit categories created by other users.

![image](https://user-images.githubusercontent.com/1275814/50826288-56f19700-1322-11e9-89b4-44f2b5fc1052.png)

![image](https://user-images.githubusercontent.com/1275814/50826331-78eb1980-1322-11e9-8490-98fcb57dea0d.png)

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.32-0ubuntu0.16.04.1
| Browser | Chrome

### Steps to reproduce
1. Create another user (admin)
2. Create a category with that user
3. Change back to the main admin user
4. Try to access/edit the created category
 
### Log errors
No log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!
