### ISSUE TITLE
500 error from custom fields

### ISSUE THREAD

**Issue by billybobilly** [mautic/mautic#7117]
## Bug Description
After adding a custom field for contacts, saving the contact results in a 500 error.  Removing the custom field(s) restores to normal operation.

| Q   | A
| --- | ---
| mautic version | 2.15.1-dev 
| PHP version  | 7.0
| Browser | Chrome

### Steps to reproduce
1. Add a custom field
2. Edit a contact 
 
### Log errors
[2019-01-08 09:12:01] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members." at /var/www/inn-mautic/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php line 46 {"exception":"[object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members. at /var/www/inn-mautic/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php:46)"} []

**Comment by Valentyn-Kubrak** [comment]
@billybobilly , I had the same issue.

try to find a field which causes an error.
edit file: app/bundles/CoreBundle/Doctrine/Type/ArrayType.php
at line 46 you will find exception handling.

Add into this block debug: \Doctrine\Common\Util\Debug::dump($value);
or add log to any file.

something like this:
`if (strpos($serialized, chr(0)) !== false) {
          
        **\Doctrine\Common\Util\Debug::dump($value);**
            
            throw new \Doctrine\DBAL\Types\ConversionException(
                'Serialized array includes null-byte. This cannot be saved as a text. Please check if you not provided object with protected or private members. value:' .print_r($value)
            );
        }
`

In response, I see that I have an issue with custom text area field.
the output will look like:

array(1) {
  ["fields"]=>
  array(1) {
    ["notes"]=>
    string(8) "Array(2)"
  }
}

my problem with the field "notes"
so I removed it or added value to this field. After that contact save successfully.
Maybe it's Mautic core issue.

**Comment by billybobilly** [comment]
The debug code is helpful.  I tried to add a textarea for notes too.  I also have a problem with a date field.

**Comment by escopecz** [comment]
May be fixed by https://github.com/mautic/mautic/pull/7192

**Comment by npracht** [comment]
Fixed when #7492 merged.

**Comment by virgilwashere** [comment]
> Fixed when #7492 merged.

Norman, I don;t think that's the right number.

**Comment by bsmolyanov** [comment]
Hi, with me it was also related to the Notes text-area field. When I unpublished this filed, the issue was gone.

**Comment by mbrinson** [comment]
> Hi, with me it was also related to the Notes text-area field. When I unpublished this filed, the issue was gone.

Yep, same for me.  It looks like Mautic can't handle text-area data type for custom fields.  I tested with Mautic release 3.0.1

**Comment by mbrinson** [comment]
> > Hi, with me it was also related to the Notes text-area field. When I unpublished this filed, the issue was gone.
> 
> Yep, same for me. It looks like Mautic can't handle text-area data type for custom fields. I tested with Mautic release 3.0.1

Wait, it's finally fixed!  I guess this must be a problem with how the custom fields were stored in previous versions of Mautic that is incompatible with the way it is currently generated.

Anyway, I deleted the textarea custom field, which fixed the problem.  But then I created a new textarea custom field and tested to see if I still got the error, and it's fixed.  So, if you're facing this problem, you'll need to delete the textarea, and then re-create it.

You should be able to backup any existing notes you have in phpmyadmin (or your sql manager of choice) and then re-import after re-creating the textarea custom field.
