### ISSUE TITLE
Failed to execute campaign event

### ISSUE THREAD

**Issue by poespas** [mautic/mautic#7118]
## Bug Description
When I try to trigger a campaign, it simply doesn't do it, I dont get to see any error, and in the console it just skips to the next one without mentioning any problems. However, a notification gets shown on the dashboard; 
![image](https://user-images.githubusercontent.com/10142882/50911132-1fb8de00-1427-11e9-896e-0458e147e309.png)
Note, it did work arround 3 weeks ago, although settings and/or the mail couldve been changed.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.2 (both web and cli)
| Browser | Opera

### Steps to reproduce
1. Create campaign
2. Publish campaign
3. php /app/console mautic:campaigns:update
3. php /app/console mautic:campaigns:trigger
 
### Log errors
I checked both /app/log , and the server logs, and there was nothing, also on the console there was nothing.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by poespas** [comment]
Turns out I forgot to publish the mail

**Comment by vishaltps** [comment]
@poespas Can you please tell me how to publish the mail? i am facing same error

**Comment by abhi-ux** [comment]
i am still facing the error even through i published

**Comment by jiteshdhamaniya** [comment]
I have published and still facing same issue.

**Comment by abhi-ux** [comment]
i am getting  Last execution error: Email not found or published error for this issue

**Comment by fchienvuhoang** [comment]
I get same error, turns out i getting 401 from sendGrid because i missing key record!!!
