### ISSUE TITLE
(BUG) Validation is missing in the form when import contact file not selected and an error page is shown instead

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#7119]
| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Presence of a file to import is not checked and an error page appears, it's a UX flaw that could easily be fixed.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 

### Steps to reproduce:

Bug report Mautic
1. Go to "Contacts" menu
2. On top right of the screen, click the arrow and select "Import"
3. Click directly on the button "Import" without browsing and selecting a file.

Current result : An error page appears, and it feels so wrong.

Expected result : When the button "Import" is clicked, the input field should show a red border, and an error message should appear in the form and say "Please pick a file first to continue."
 
### Log errors:

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!
