### ISSUE TITLE
Cron job for email producing errors

### ISSUE THREAD

**Issue by cuberoot** [mautic/mautic#712]
The cronjob that sends emails is repeatedly giving me this error after sending out 3000 emails (I had to cancel sending a few times because of a hang):

	Warning: rename(/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/B7Km5702X1.message.sending.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry,/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/B7Km5702X1.message.sending.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry): File name too long in /home/healingjourney/mautic.journeytohealingandjoy.com/app/bundles/CoreBundle/Command/ProcessEmailQueueCommand.php on line 105

	Warning: file_get_contents(/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/B7Km5702X1.message.sending.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry.finalretry): failed to open stream: File name too long in /home/healingjourney/mautic.journeytohealingandjoy.com/app/bundles/CoreBundle/Command/ProcessEmailQueueCommand.php on line 107

	Catchable fatal error: Argument 1 passed to Mautic\CoreBundle\Event\EmailEvent::__construct() must be an instance of Swift_Message, boolean given, called in /home/healingjourney/mautic.journeytohealingandjoy.com/app/bundles/CoreBundle/Command/ProcessEmailQueueCommand.php on line 111 and defined in /home/healingjourney/mautic.journeytohealingandjoy.com/app/bundles/CoreBundle/Event/EmailEvent.php on line 33

**Comment by escopecz** [comment]
Can you confirm you use Mautic 1.1.3?

**Comment by cuberoot** [comment]
I confirm that I was running 1.1.3. I had upgraded from v1.1.2 earlier that day.

**Comment by cuberoot** [comment]
I am still experiencing hangs and errors when sending list emails. I'm on v1.1.3 self hosted using Mandrill as my email sending provider.

Here's more example output from my email cron job:

	Warning: unlink(/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/KqyxRnYunJ.message.sending): No such file or directory in /home/healingjourney/mautic.journeytohealingandjoy.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 171

	Warning: rename(/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/bh-8ceVNus.message,/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/bh-8ceVNus.message.sending): No such file or directory in /home/healingjourney/mautic.journeytohealingandjoy.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166

	Warning: rename(/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/9cW-XrPtCm.message,/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/9cW-XrPtCm.message.sending): No such file or directory in /home/healingjourney/mautic.journeytohealingandjoy.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166

	Warning: rename(/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/CD20wF56T7.message,/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/CD20wF56T7.message.sending): No such file or directory in /home/healingjourney/mautic.journeytohealingandjoy.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166

	Warning: rename(/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/ZmelSxywuQ.message,/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/ZmelSxywuQ.message.sending): No such file or directory in /home/healingjourney/mautic.journeytohealingandjoy.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 166

	Warning: unlink(/home/healingjourney/mautic.journeytohealingandjoy.com/app/spool/default/vmkVFQ8qbj.message.sending): No such file or directory in /home/healingjourney/mautic.journeytohealingandjoy.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 171

**Comment by alanhartless** [comment]
Is this still an issue in 1.2.0?

**Comment by ptcc** [comment]
yes, it is still a problem in 1.2, at least for me

**Comment by ptcc** [comment]
$ sudo php /var/mautic/app/console mautic:email:process --env=prod
PHP Warning:  unlink(/var/mautic/app/spool/default/9mjFfAZrjl.message.sending): No such file or directory in /var/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 171
PHP Warning:  unlink(/var/mautic/app/spool/default/K0z6gDhGXJ.message.sending): No such file or directory in /var/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php on line 171

**Comment by ptcc** [comment]
might this be a long email queue, and then the cron job is fired before the previous ended, and so there is a race on the processing of an email on the queue?

**Comment by cuberoot** [comment]
That sounds like a good theory. I haven't sent an email since I upgraded to v1.2. I hit issues in the migration of my database, so v1.2 slowed me down.

**Comment by cuberoot** [comment]
I am not seeing any cron job errors anymore when sending emails with v1.2. However it still hangs when sending and I have to cancel and try again.

**Comment by alanhartless** [comment]
When you say it still hangs, is that when executing the cron job? Is that behavior consistent or intermittent? Anything logged when this behavior occurs?

**Comment by cuberoot** [comment]
Actually, the hang in is the Mautic UI. Say I am sending 3000 emails, the progress bar will advance some amount (sometimes 300, sometimes 2000) and then stop. I am using the cron job + Mandrill setup. It I monitor Mandrill, the emails stop being sent at the amount the bar hung at minus one. So, if the bar says 300, Mandrill will say I sent 299 emails and then nothing else will happen. I have to cancel the send in Mautic and then try again.

My main list is about 3000 emails and I don't think I've ever been able to send it in one go.

I don't get any output from the cron job when this fails. I don't see anything in app/logs either

**Comment by escopecz** [comment]
@cuberoot what about in the server/PHP error log? My guess is it fails because of hitting a time or memory limit.

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to comment with an update and we'll open this issue again.
