### ISSUE TITLE
Adding custom contact field with type select/multiselect trough API 

### ISSUE THREAD

**Issue by eschiendorfer** [mautic/mautic#7132]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
It doesn't seem to be possible, to add a select or multiselect field trough API. The issue could be related to this one: https://github.com/mautic/mautic/issues/3553

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.33

### Steps to reproduce
```
$data = array(
   'label'                 => 'Shops (TB)',
   'alias'                 => 'shops',
   'type'                  => 'multiselect',
   'isPubliclyUpdatable'   => true,
   'isUniqueIdentifier'    => false,
   'properties'            => array(
   'list' => implode("|", array('Option 1', 'Option 2'))
)

$error = $fieldApi->create($data)
```
 
### Log errors
$error returns this: "list: This value is not valid."

I tried it also without the implode. It doesn't work either. 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by umakantsharmacedcoss** [comment]
in list if you send array( 'label' => 'label name', 'value' => 'value name' ) of list it will wokr @eschiendorfer 

so it will be like this 

`$data = array(
   'label'                 => 'Shops (TB)',
   'alias'                 => 'shops',
   'type'                  => 'multiselect',
   'isPubliclyUpdatable'   => true,
   'isUniqueIdentifier'    => false,
   'properties'            => array(
   'list' =>array( array( 'label' => 'label 1', 'value' => 'value 1' ), array( 'label' => 'label 2', 'value' => 'value 2' ) )
)

$error = $fieldApi->create($data)`

**Comment by eschiendorfer** [comment]
@umakantsharmacedcoss I can confirm, that it works like you said. Thanks a lot! I will close this issue.

**Comment by laabidi21** [comment]
@umakantsharmacedcoss 
I tried that. as you wrote, but I have an error
                $data = array(
                    'label' => 'Shops (TB)',
                    'alias' => 'shops',
                    'type' => 'multiselect',
                    'isPubliclyUpdatable' => true,
                    'isUniqueIdentifier' => false,
                    'properties' => array(
                        'list' =>array( array( 'label' => 'label1', 'value' => 'value1' ),
                                              array( 'label' => 'label2', 'value' => 'value2' )
                        )
                    )
                );
    $fieldApi = $api->newApi("contactFields", $auth, $apiUrl);
    $response = $fieldApi->create($data);


The response has unexpected status code (401).

Response: {"errors": [{"message": "It looks like we encountered an error (error # 401). Please report this to the administrator if it happens again.", "Code ": 401," type ": null}]}
