### ISSUE TITLE
Placeholders do not get replaced in URL's when email tracking is enabled.

### ISSUE THREAD

**Issue by vincnetas** [mautic/mautic#7133]
## Bug Description

When email has a link with placeholders:

https://www.surveymonkey.com/r/XXXXX?user={contactfield=externalid}&reason=2&email={contactfield=email}

If tracking is enabled (Configuration > Email Settings > Disable trackable links > No)

After clicking link, redirect (tracks click) and redirects to URL with not replaced placeholders.
If tracking is disabled email contains URL with replaced placeholders, but tracking functionality is lost.

I assume this happens when creating tracking links. Target URL's are used without first replacing placeholders.

Similar issue from long time ago #6011 

Note: In 2.14.0 version this functionality was working. Placeholders in URL's were being replaced when sending emails. Could this be a regression?

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1.16
| Browser | Safari

### Steps to reproduce
1. Create email with URL containing place holders
2. Enable email link tracking
3. Send email to user

**Comment by npracht** [comment]
Then i close it in favor of #7147, let's discuss there.

**Comment by icetique** [comment]
Note: This bug is slightly different than #7147 as here the placeholders are not replaced at all and in #7147 the placeholders are replaced but not with trackable URLs.
