### ISSUE TITLE
Delete Tag trough API

### ISSUE THREAD

**Issue by eschiendorfer** [mautic/mautic#7136]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
It's not possible to delete Tag trough API. 

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.33

### Steps to reproduce
Just establish a connection (working for me) and dthen try to delete the tag: $tagApi->delete(8);
It's just not working. I tried the same thing with a segment and there it worked perfect. Also $tagApi->get(8) works as expected...
 
### Log errors
The response has unexpected status code (500)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!
