### ISSUE TITLE
Cannot access Forms after upgrading from 2.14 to 2.15

### ISSUE THREAD

**Issue by sushinger** [mautic/mautic#7140]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

I have logged in my mautic-dashboard and fired the upgrade from there. A short error-message appeared, but other than that the upgrade did finish.

But I cannot access my Forms in dashboard anymore. I have checked logs and found this:

`[2019-01-16 19:49:40] mautic.ERROR: [UPGRADE ERROR] Exit code 1; Mautic Migrations \ Migrating up to 20181011150000 from 20180220212444 \ ++ migrating 20180329185634 \ -> ALTER TABLE maudj_lead_event_log DROP FOREIGN KEY FK_C69A34DA55458D Migration 20180329185634 failed during Execution. Error An exception occurred while executing 'ALTER TABLE maudj_lead_event_log DROP FOREIGN KEY FK_C69A34DA55458D': \ Can't DROP 'FK_C69A34DA55458D'; check that column/key exists \ [Doctrine\DBAL\Exception\DriverException] An exception occurred while executing 'ALTER TABLE maudj_lead_event_log DROP FOREIGN KEY FK_C69A34DA55458D': \ Can't DROP 'FK_C69A34DA55458D'; check that column/key exists \ [Doctrine\DBAL\Driver\Mysqli\MysqliException] Can't DROP 'FK_C69A34DA55458D'; check that column/key exists \ doctrine:migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--]  [] \ [] []`

I have installed mautic via Softaculous on my cPanel Account. I have root-access to the server, which is operated by a friend.

I have already restored from backup and ran the upgrade again from mautic-dashboard, but again I coulnd't access forms.

I have also downloaded 2.15.0-update.zip from https://github.com/mautic/mautic/releases/tag/2.15.0, but didn't find a proper manual about how to upgrade manually. Really no instructions for this on mautic docs?

I hope you can help me with upgrading :-)

Thank you and kind regards,
Sascha
I wonder if someone could help me to perform 

| Mautic version 2.15 | 
| PHP version 7.1 | 
| Browser |

**Comment by escopecz** [comment]
Try some tricks from https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful and let us know how it went.

**Comment by sushinger** [comment]
Thank you for your response! I have followed step 1 and then the backend showed:
"The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator." Then I tried Step 2 with this result on my shell:
"[Symfony\Component\Debug\Exception\OutOfMemoryException]
  Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 48165563 bytes)"
I checked memory_limit and it's set to 256M.
In case I need to reinstall from scratch, how can I extract my contacts, segments, forms, campaigns etc. from my backup?

**Comment by escopecz** [comment]
Your PHP memory limit is only 135 MB. Increase to at least 500 MB.
