### ISSUE TITLE
Sugar CRM integration not working

### ISSUE THREAD

**Issue by nipunreddy123** [mautic/mautic#7141]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hello, I've tried the SugarCRM integration in the hosted mautic version 2.8.2 against my SuiteCRM installation (v 6.x/community) and is not working and throwing the below Error.
Error:
-----
 mautic.ERROR: INTEGRATION ERROR: Sugarcrm - There was an unknown error encountered when trying to obtain the access token. [] []

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7+
| Browser | Firefox, chrome

### Steps to reproduce
I completed all the below fields in SUGARCRM plugin:
1. sugar URL (with the url of my sugar installation),
2. client key: I put the key got in Authkeys in Suitecrm (as hosted mautic does)
3. client secret: I put passowrd got in Authkeys in Suitecrm (the same hosted mautic does)
4. suite username: I put my suite installation name 
5. suite crm password: the password
6. sugarCRM version: 6.x/community,
7. Finally click on Authorize
 
### Log errors
mautic.ERROR: INTEGRATION ERROR: Sugarcrm - There was an unknown error encountered when trying to obtain the access token. [] []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
I can make it working on my side. Did you check your user rights or API key rights ?
