### ISSUE TITLE
Missing broadcast:send segment-ID= option

### ISSUE THREAD

**Issue by ArtemDzhafarov** [mautic/mautic#7143]
Hi there.
According to the Official Documentation provided here -https://www.mautic.org/docs/en/setup/cron_jobs.html#send-scheduled-broadcasts-e-g-segment-emails 
since version 2.2.0 we have an opportunity to separate broadcast sending by `--segment-ID=X` option. However, it seems that `mautic:broadcasts:send` doesn't have this feature. Could you clarify this issue? Having same issue on both 2.14 and 2.15 versions. Thank you in advance.

**Comment by RCheesley** [comment]
Closing as this is a question rather than a bug
