### ISSUE TITLE
How do I unistall Mautic self hosted?

### ISSUE THREAD

**Issue by dudabueno** [mautic/mautic#7144]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I don't want to use Mautic anymore but i'm not sure how do I have to proceed to unistall Mautic from my server. 
Can I simply delete te Mautic folder?

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by eschiendorfer** [comment]
I believe for such question it's better to use the slack channels: https://mautic.slack.com

But in general if you don't want to use a websoftware you do normally this:
1. Delete Folders
2. Delete Database
3. Remove Cronjobs

**Comment by npracht** [comment]
Please move discussions to slack and keep using github to report issues.
Thanks a lot for your interest in Mautic !
