### ISSUE TITLE
Translation Files are not available

### ISSUE THREAD

**Issue by TomKnox** [mautic/mautic#7146]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Translation Files are not available
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.2.10
| Browser |  doesn't matter

### Steps to reproduce
1.  Go to configuration System-Settings
2.  Select Default Language others than en_US
3. Click Apply

Also the following url is not available:
https://updates.mautic.org/index.php?option=com_mauticdownload&task=downloadLanguagePackage&langCode=de.zip is not available
 
### Log errors
This errorstring is displayed: mautic.core.language.helper.error.on.language.server.side

If i access the url directly an s3 error message is displayed:
`
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>30C5B5213DF52CB5</RequestId>
</Error>`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
@escopecz any idea of what is wrong here?

**Comment by phpedinei** [comment]
I have some problem

**Comment by escopecz** [comment]
@npracht thanks for pointing this out. We are woking on resolving this.

**Comment by escopecz** [comment]
You'd need dev dependencies to do so. But it'll probably fail later on authorization because you might not have admin account for Mautic's Transifex. We have to fix the AWS account to get it working again. Please be patient.

**Comment by escopecz** [comment]
Verified with https://updates.mautic.org/index.php?option=com_mauticdownload&task=downloadLanguagePackage&langCode=de (without .zip)

**Comment by luizeof** [comment]
@escopecz Thanks for your support ;)

**Comment by morettic2015** [comment]
@escopecz I have an issue with Hebrew Language. After update to 2.15.1, Tracking URL is not storing original page title but a different not hebrew not english. Gibrish. 

Take a look at the screenshot. The original page been tracked is in Hebrew. Before update it worked fine. Now we have this strange behavior.  Any idea? 

<img width="960" alt="hebrew error" src="https://user-images.githubusercontent.com/11476006/57651920-d7f8bd80-75a4-11e9-91d3-d2bef877c8ab.png">

**Comment by escopecz** [comment]
@morettic2015 your issue is very different from the original description. Please start a new issue or find a better one. This is the change that causes troubles: https://github.com/mautic/mautic/pull/7080

So far we are not which is better. If it fails completely in some cases or if the transliteration is more problematic.
