### ISSUE TITLE
Placeholders don't get replaced with trackable link in text version of e-mail

### ISSUE THREAD

**Issue by icetique** [mautic/mautic#7147]
## Bug Description
I noticed when I insert placeholder {pagelink=1} into text version of the e-mail it doesn't get replaced with trackable version of the link unlike in HTML version. I have to replace the {pagelink=1} with the URL hidden under this placeholder to make it replaced by trackable version of the link.

E.g.: {pagelink=1} in HTML version gets replaced with:
https://m.domain.com/r/xxx?ct=yyy%3D%3D&utm_source=newsletter&utm_medium=email&utm_campaign=splash_optin

In text version it gets replaced with:
https://m.domain.com/opt-in

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.2.10-0ubuntu0.18.04.1
| Browser | Chrome

### Steps to reproduce
1. Create landing page
2. Create e-mail as part of the campaign with link to the landing page (I personally used it to create double opt-in process) as {pagelink=ID}.
3. Create text version of the e-mail with {pagelink=ID}
4. Create campaign that uses this e-mail and landing page.
5. Observe that {pagelink=ID} don't get replaced with trackable link within text version.

This might be related to #7133.

**Comment by ArtemDzhafarov** [comment]
Please provide with the update, as it's key-feature for email marketing.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!
