### ISSUE TITLE
mtc.js file is not found - 404 error

### ISSUE THREAD

**Issue by lpienia** [mautic/mautic#7148]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**
I get a 404 error to get the mtc.js file

the URL is https://mautic.zeva.com.ar/mtc.js

WebServer is NGINX
    # more_set_headers "X-Frame-Options : SAMEORIGIN";
the settings was disabled already

php v7
mautic v2.15

**Comment by npracht** [comment]
Hello @lpienia !
What did you disable in the settings ?

**Comment by npracht** [comment]
In your instance configuration, do you have the CORS enabled ? If yes, just disable it ;)

**Comment by lpienia** [comment]
mmm, I don't exactly now. Where I supposed to looking for?

REgards,

**Comment by npracht** [comment]
![capture d ecran 2019-01-18 a 17 05 38](https://user-images.githubusercontent.com/14075239/51398287-8a62cb80-1b43-11e9-88a0-7d399a915b13.png)

**Comment by lpienia** [comment]
Is disabled already....

**Comment by npracht** [comment]
Can you share the link whee you have the tracking script ?

**Comment by FABBRj** [comment]
I have the same problem, in my backend the configuration is disabled, but in the site the script is not loaded

**Comment by npracht** [comment]
Please share a link where the tracking script is to be able to check what happens.

**Comment by joeyparis** [comment]
> Please share a link where the tracking script is to be able to check what happens.

I believe his link is in his original post. https://mautic.zeva.com.ar/mtc.js

I am having the same issue and have CORS disabled. I am running mautic behind nginx, is there a certain configuration I need to put in place to access `mtc.js` and `mtracking.gif`?

**Comment by joeyparis** [comment]
I was able to solve this problem by forcing nginx to send `mtc.js` and `mtracking.gif` through fastcgi since they are not real files and needed to be interpreted by Symfony rather than displaying a real file.
```
  location ~* /(mtc.js|mtracking.gif)$ {
    proxy_pass <address_for_php_server>;
    include fastcgi_params;
    fastcgi_pass <address_for_php_server>;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files $uri $uri/ /index.php$is_args$args;
  }
```

**Comment by anguschang007** [comment]
> I was able to solve this problem by forcing nginx to send `mtc.js` and `mtracking.gif` through fastcgi since they are not real files and needed to be interpreted by Symfony rather than displaying a real file.
> 
> ```
>   location ~* /(mtc.js|mtracking.gif)$ {
>     proxy_pass <address_for_php_server>;
>     include fastcgi_params;
>     fastcgi_pass <address_for_php_server>;
>     fastcgi_index index.php;
>     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
>     try_files $uri $uri/ /index.php$is_args$args;
>   }
> ```

I am trying to use your block, but it is still not working! Here, my version:
`location ~* /(mtc.js|mtracking.gif)$ {
                proxy_pass https://myMauticSite.com;
                include fastcgi_params;
                fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                try_files $uri $uri/ /index.php$is_args$args;
        }`

**Comment by joeyparis** [comment]
Wouldn't nginx be behind https://myMauticSite.com? I think you'll need the direct server IP or address to pass to `proxy_pass`. Nginx config is a little over my head though so I could be very off

**Comment by anguschang007** [comment]
> Wouldn't nginx be behind https://myMauticSite.com? I think you'll need the direct server IP or address to pass to `proxy_pass`. Nginx config is a little over my head though so I could be very off

I solved the problem by using the following configuration file:
https://github.com/stevedrobinson/better-mautic-nginx/blob/master/mautic.conf
