### ISSUE TITLE
Firebase Dynamic links integration 

### ISSUE THREAD

**Issue by hrouissi** [mautic/mautic#7150]
Firebase Dynamic links offers an advanced link shortner tool with useful features. 
The implementation of a plugin dedicated to this could provide a major help for the community. 

The limits for using a tool such as bit.ly is mainly the costs. 
We are running campaigns with databases going up to a 100k subscribers and we can't afford paying 1k $ as a subscription fee to bit.ly.

**Comment by RCheesley** [comment]
Please either submit a PR or pop this on the ideas forum at https://forum.mautic.org/c/ideas!
