### ISSUE TITLE
Deleting email while in campaign - deletion protection mechanism

### ISSUE THREAD

**Issue by hrouissi** [mautic/mautic#7151]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 5.6.37
| Browser | Chrome

### Steps to reproduce
1. Create email
2. create a campaign with an action to send the email
3. publish both campaign and email
4. delete email from email list
 
### Log errors
-

Email should not be deleted. A prompt should indicate that the email is attached to a campaign.
Unless the email is deleted form the campaign the deletion action should not be allowed.

**Comment by RCheesley** [comment]
Hi there, if this is still an issue in Mautic 3.x can you submit a PR to add the suggested functionality?
