### ISSUE TITLE
List of IPs to not track contacts with - still tracking

### ISSUE THREAD

**Issue by mmixchris** [mautic/mautic#7154]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
We are trying to eliminate reports of our own statoc IP addresses from Mautic. When we enter our IP address range, we are still getting results in Contacts (Anonymous Contacts toggled). We've tried entering IP addresses individually as well as using the "/" range modifier. 

| Q   | A
| --- | ---
| Mautic version | 2.7.1
| PHP version | 7.0.32
| Browser | Chrome 71.0.3578.98 (Official Build) (64-bit)

### Steps to reproduce
1. IP addresses entered into "List of IPs to not track contacts with (one per line)".
2. Checked Contacts and see that by clicking "Toggle Anonymous Contacts" we are still receiving hits from the IP address range entered. 
 
### Log errors
No errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @mmixchris would you try to update your version ? You are far from the latest version and it may have been evolved a lot ;)
