### ISSUE TITLE
Make Amazon SES/Other Mail Service Ports configurable

### ISSUE THREAD

**Issue by MaMuk** [mautic/mautic#7160]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | no
| Feature request? | yes 
| Enhancement? | no

## Description:
Currtently the ports through which Mautic Connects to Amazon SES or other Mail services are hard-coded. For example in app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php as 2587.

Our company policy does not allow to open arbitrary ports, but allows us to use a defined limited set of known ports, Amazon SES for example supports the standard SMTP Port just as well. So it would be convenient to be able to set that port in the configuration of the Email Service instead of having to edit that file whenever we update Mautic.

**Comment by hrouissi** [comment]
Up

**Comment by kuzmany** [comment]
This is cool feature to donate by create with community. 
Let me know If you're interest

**Comment by hrouissi** [comment]
Being able to add multiple email senders/settings would be an amazing feature. 
Most of email platforms requires you to authenticate a sender at a time (reference to AWS SES).

The ideal would be :
1 - add multiple senders in email configuration tab
2- add the option to select between authenticated senders in the From to field (in channel > email)

**Comment by kuzmany** [comment]
@hrouissi create new issue / feature request, this discussion is about another issue
Anyway Mautic could be extended for multiple email providers. In this PR is little hint how to do it  https://github.com/mautic/mautic/pull/5836 . 
But multiple email providers need a lot of improvements in the code, need hire devs for it and cute budget :)

**Comment by virgilwashere** [comment]
⚠️ I am not a PHP programmer.

I have here a potential Pull Request to allow the SMTP port for AWS SES to be configured in the System / Email configuration.

https://github.com/virgilwashere/mautic/tree/feature/aws-ses-port-config

From what I can see, the logic around the amazon_transport assumes no empty values, which is what someone loading this config page and saving without entering a port will get.

I'm not sure that this code provides a default value for `$port` or just overwrites it.

```php
public function __construct($host, $port = 2587, Http $httpClient, LoggerInterface $logger, TranslatorInterface $translator, TransportCallback $transportCallback)
     {
         parent::__construct($host, $port, 'tls');
```

But it exposes the port, and the value is saved to `local.php`

![image](https://user-images.githubusercontent.com/4347038/68208311-9fe6aa80-001c-11ea-838a-c51847fcb101.png)

`amazon_region` is read from the `messages.ini` and pushed into `$host`, so it's never populated in the config screen as far as I can tell.

Ideally, this could be as simple as selecting Amazon SES (SMTP) transport just sets a hostname to a `choices` field, puts 2587 as default port and treats it as another SMTP type...at least until there is a AWS SES API transport.

Maybe someone with some real PHP experience could take it across the line?

**Comment by RCheesley** [comment]
@kuzmany @virgilwashere @hrouissi @MaMuk is anybody open to creating a PR. for this issue? It sounds like it could be a useful configuration option!

**Comment by wise-gorilla** [comment]
@RCheesley 
I think i can do that as a part of #9005 since i made a refactoring for AmazonTransport on that PR so if anyone made a PR for that issue then it will cause a conflict.

**Comment by wise-gorilla** [comment]
@RCheesley This issue can be closed
