### ISSUE TITLE
Contact replies not being parsed correctly

### ISSUE THREAD

**Issue by coreyworrell** [mautic/mautic#7165]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
After setting *Email Settings* > *Monitored Inbox Settings* > *Contact Replies*, replies do not show up in contact activity, and do not count towards the reply count for campaigns. Bounces *do* work fine. Same account and inbox are being used.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1.26
| Browser | NA

### Steps to reproduce
1. Enable contact replies
2. Reply to campaign email
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Can you show your configuration, what is the type of mailbox you're configuring ? etc.
