### ISSUE TITLE
Edit Contact - System 500

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#7167]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I'm having a bit of a weird issue and would love some suggestions to fixes. I've already do the schema updates etc and it's still not resolved. Any idea's would be greatly appreciated!

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Upgrade to v2.15.0
2. Go to a contact and click save and close 
 
### Log errors

`[2019-01-24 12:28:24] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'UPDATE ma_leads SET attribution_date = ?, website = ?, job_title = ?, contact_type = ?, facebook = ?, foursquare = ?, googleplus = ?, instagram = ?, linkedin = ?, skype = ?, twitter = ? WHERE id = ?' with params ["2019-01-24", "http:\/\/17", "25", null, "18", "19", "20", "21", "22", "23", "24", 29647]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'attribution_date' in 'field list'" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'UPDATE ma_leads SET attribution_date = ?, website = ?, job_title = ?, contact_type = ?, facebook = ?, foursquare = ?, googleplus = ?, instagram = ?, linkedin = ?, skype = ?, twitter = ? WHERE id = ?' with params [\"2019-01-24\", \"http:\\/\\/17\", \"25\", null, \"18\", \"19\", \"20\", \"21\", \"22\", \"23\", \"24\", 29647]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'attribution_date' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'attribution_date' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'attribution_date' in 'field list' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
> Column not found: 1054 Unknown column 'attribution_date' in 'field list'
Really seems being an issue with the DB schema.

**Comment by colourfulowl** [comment]
I was able to resolve this by manually adding back into the database the missing columns. However, they aren't within the Schema. So the next time i update the system it'll bug it out again. Can someone point me in the direction of how to add these options back into the schema?

Below are the columns that are missing from the leads table:

facebook
foursquare
googleplus
preferred_locale
skype
twitter
website
attribution
attribution_date
instagram
linkedin
job_title
contact_type

When dumping the SQL it already wants to drop this new columns.

I installed a new version of mautic on v2.15.0 and it was also missing these columns from the tables.

![leads-db](https://user-images.githubusercontent.com/41902603/51696000-4f0d4480-1ffc-11e9-9e99-d0b808a46741.PNG)

**Comment by kuzmany** [comment]
Comment this line https://github.com/mautic/mautic/pull/6279/files#diff-be217df1af18b9cc3099f966ea3718d9R298

`->addIndex(['last_active'], 'last_active_search');`

We need take  a look on already merged https://github.com/mautic/mautic/pull/6279 
Seems like addIndex broke something. As I the migration already create index and this is reason why entity index fail, but shouldn't skip it?

@escopecz any idea?

**Comment by colourfulowl** [comment]
@kuzmany Neither the code highlighted in the pull request or the code you placed are within my FieldModel.php file :/

**Comment by npracht** [comment]
Solved by #7343 merged in 2.15.1
