### ISSUE TITLE
Install on Synology NAS The site is currently offline due to encountering an error.

### ISSUE THREAD

**Issue by sensalot** [mautic/mautic#7170]
Hi,

I downloaded the lastest Mautic CE, uploaded it to the web folder of my synology NAS, and unzipped it. On the NAS I already have a working Wordpress Site.
PHP version installed are 5.6, 7,0 (default) 7,2
Appache HTTP server 2.0 and 2.2 (default)

I opened Chrome and went to the folder with the Mautic intall to start the setup.
The URL changed to http://nas/mautic/installer
And the error is shown:"The site is currently offline due to encountering an error."
The file permissions of all in the mautic install folder are 0777

The log files are empty. The cash folder is empty
Inspecting element doesn't help
Index.php only contains a verification of php 7.0

I enabled PHP services 
mailparse
mcrypt
pdo_dblib 
xmlrpc
zip

I tested with IE
Disabling all other PHP versions and thrying one by one
Same for Mysql.

Not a clue of what it could be. Any ideas?

**Comment by escopecz** [comment]
Follow https://www.mautic.org/docs/en/tips/troubleshooting.html

Let us know the error from the logs

**Comment by sensalot** [comment]
I moved to a different hosting solution
