### ISSUE TITLE
Unsubscribe Settings Not Reflected

### ISSUE THREAD

**Issue by lonemountain** [mautic/mautic#7172]
## Bug Description
Unsubscribe Settings are not reflected on the unsubscribe link, and the styling is awful.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.2.13
| Browser | Chrome

### Here are my Unsubscribe Settings:
![unsubscribe_settings](https://user-images.githubusercontent.com/20927602/51753372-33974d80-207f-11e9-9a45-a47f597a5f84.png)

### Steps to reproduce
1. Set the "Unsubscribe Settings" as shown in the picture above.
2. Create a custom field: active_lease
3. Create a category: LMTL
4. Create a customer with active_lease = 1
5. Create an email using Channels > Emails > New Segment Email 
6. Email settings: "Blank" (untouched) template, Segment = Active Lease, Category = LMTL
7. Send the email.

Once email is received, click on the unsubscribe link and you will see that even though I ONLY had "Show contact preference settings" and "Show contact's categories" set to Yes, you still see all the other options. On top of that, the page's styling looks awful. Also note that this is just the default User Preferences page. I didn't do any customization.

![untitled](https://user-images.githubusercontent.com/20927602/51753699-1ca52b00-2080-11e9-8ced-e12fb62e6aab.png)

### More Info

If I set ALL options to YES under Unsubscribe Settings:
![unsubscribe_settings2](https://user-images.githubusercontent.com/20927602/51754766-c5ed2080-2082-11e9-91e5-b2fa8ab68531.png)

 I get a 505 Error when access the unsubscribe link, and the logs show the following:

`
[Fri Jan 25 09:19:11.175323 2019] [php7:notice] [pid 5644] [client X.X.X.X:64345] PHP Notice:  Undefined index: objectName in /var/www/mautic/app/bundles/DashboardBundle/Views/Dashboard/recentactivity.html.php on line 44, referer: https://xxx.xxx.com/s/config/edit
[Fri Jan 25 09:19:24.965836 2019] [php7:notice] [pid 5683] [client X.X.X.X:64372] PHP Notice:  Undefined index: subscribed_channels in /var/www/mautic/vendor/symfony/form/FormView.php on line 113
[Fri Jan 25 09:19:24.965883 2019] [php7:notice] [pid 5683] [client X.X.X.X:64372] PHP Notice:  Trying to get property 'vars' of non-object in /var/www/mautic/app/bundles/EmailBundle/Views/Lead/preference_options.html.php on line 48
[Fri Jan 25 09:19:24.965923 2019] [php7:warn] [pid 5683] [client X.X.X.X:64372] PHP Warning:  Invalid argument supplied for foreach() in /var/www/mautic/app/bundles/EmailBundle/Views/Lead/preference_options.html.php on line 48
[Fri Jan 25 09:19:24.965980 2019] [php7:notice] [pid 5683] [client X.X.X.X:64372] PHP Notice:  Undefined index: preferred_channel in /var/www/mautic/vendor/symfony/form/FormView.php on line 113
`

**Comment by kuzmany** [comment]
This should fixed it

https://github.com/mautic/mautic/pull/7006
