### ISSUE TITLE
Email Overview Stats Don't Match Send Stats

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#7174]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The stats that are in the overview don't actually match what was sent. The data shown in the graphs are correct, but the overview stats are not. Could this be a caching issue?

I've cleared the cache and the issue still remains. Any ideas?

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1. Send out an email campaign.
2. View the send stats and compare to the detail stats. 

The images below are from a campaign that went out to 33,885 contacts. As you can see below the email send stats are way out of whack, nor are they consistent.

Email Overview stats: - The reads is  correct, but obviously the read rate is wrong.
![stats2](https://user-images.githubusercontent.com/41902603/51827122-8c195580-22e0-11e9-9cc9-75d76936666b.PNG)

Email sent records:
![stats3](https://user-images.githubusercontent.com/41902603/51827131-90457300-22e0-11e9-8216-ae1d255fe9e2.PNG)

Email Stats:
![stats](https://user-images.githubusercontent.com/41902603/51826920-1ca36600-22e0-11e9-95d3-63e1ca637a35.PNG)
 
### Log errors

`[2019-01-28 09:20:16] mautic.NOTICE: PHP Notice - Undefined index: ct - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Controller/PublicController.php - at line 452 [] []
[2019-01-28 09:20:56] mautic.NOTICE: PHP Notice - Undefined index: preferred_locale - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/LeadBundle/Deduplicate/ContactMerger.php - at line 201 [] []
[2019-01-28 09:24:16] mautic.NOTICE: PHP Notice - Undefined index: ct - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Controller/PublicController.php - at line 452 [] []
[2019-01-28 09:24:19] mautic.NOTICE: PHP Notice - Undefined index: ct - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Controller/PublicController.php - at line 452 [] []`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by AkkuFresh** [comment]
I had also received similar messages:
```
[13-Feb-2019 11:08:47 UTC] PHP Notice:  Undefined index: ct in /home/--mautic_path--/app/bundles/PageBundle/Controller/PublicController.php on line 452
```
The related code is:
```
        // Get query string
        $query = $this->request->query->all();

        // Unset the clickthrough from the URL query
        $ct = $query['ct']; //This is the line 452 in app/bundles/PageBundle/Controller/PublicController.php
        unset($query['ct']);
```
?? What wast the original intent with this part of the code?

**Comment by colourfulowl** [comment]
Following on with this. I've noticed that the Email Widgets on the dashboard don't have any form of data in them now either. This is happening on all installation of Mautic 2.15+. I'm not getting an error log at all related to this, so i don't really know where to bug fix it :/ Any suggestions? It's making Mautic extremely time consuming when it comes to analysis the email campaigns.

![no-email-overview](https://user-images.githubusercontent.com/41902603/53000590-aac2c600-3420-11e9-8997-85631055528d.PNG)

**Comment by colourfulowl** [comment]
Regarding the dashboard error. If i revert the dashboard back it's standard, or any of the predefinded ones the data is shown. However, the moment i move a widget or resize any of the widget's it wipes all data from the Emails sent / open widget. I've cleared the cache on the server and locally and the data still does not return. My best guess, there's an issue with passing the data into custom dashboards? - No error logs produced.

![mautic-stats](https://user-images.githubusercontent.com/41902603/53822199-2a937900-3f67-11e9-9e6a-2f043c759c62.PNG)

**Comment by techzotezo** [comment]
Showing this error and admin panel not opening...
[2019-04-11 05:30:22] mautic.NOTICE: PHP Notice - Undefined index: ct - in file app/bundles/PageBundle/Controller/PublicController.php - at line 452 [] []
[2019-04-11 05:30:39] mautic.NOTICE: PHP Notice - Undefined index: ct - in file app/bundles/PageBundle/Controller/PublicController.php - at line 452 [] []
[2019-04-11 05:30:39] mautic.NOTICE: PHP Notice - Undefined index: ct - in file app/bundles/PageBundle/Controller/PublicController.php - at line 452 [] []
[2019-04-11 05:31:57] mautic.NOTICE: PHP Notice - Undefined index: ct - in file app/bundles/PageBundle/Controller/PublicController.php - at line 452 [] []

**Comment by mabumusa1** [comment]
I get this error as well in version `2.15.1`, here is the error log 

`[2019-07-15 15:28:38] mautic.NOTICE: PHP Notice - Undefined index: ct - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/PageBundle/Controller/PublicController.php - at line 452 [] []`

**Comment by chalsek8** [comment]
I have encountered the same issue and modified the code. I have added this line and solves the issue.

        // Unset the clickthrough from the URL query
        //$ct = $query['ct'];

        if (isset($query['ct']))
        {
                $ct = $query['ct'];
        } else {
                $ct = null;
        }

        unset($query['ct']);

**Comment by virgilwashere** [comment]
> I have encountered the same issue and modified the code. I have added this line and solves the issue.

Here's the code as a diff patch.

```diff
diff --git a/app/bundles/PageBundle/Controller/PublicController.php b/app/bundles/PageBundle/Controller/PublicController.php
index 350e8a9a4..bbe69d977 100644
--- a/app/bundles/PageBundle/Controller/PublicController.php
+++ b/app/bundles/PageBundle/Controller/PublicController.php
@@ -449,7 +449,11 @@ class PublicController extends CommonFormController
         $query = $this->request->query->all();

         // Unset the clickthrough from the URL query
-        $ct = $query['ct'];
+        if (isset($query['ct'])) {
+            $ct = $query['ct'];
+        } else {
+            $ct = null;
+        }
         unset($query['ct']);

         // Tak on anything left to the URL
```

```console
$ cat > /tmp/ct_unset.diff
<PASTE>
<CTRL D>
$ cd /var/www/mautic
$ git apply -v /tmp/ct_unset.diff
Checking patch app/bundles/PageBundle/Controller/PublicController.php...
Applied patch app/bundles/PageBundle/Controller/PublicController.php cleanly.
```

Virgil

**Comment by virgilwashere** [comment]
Actually, #7337 is the symptoms I'm seeing..

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by rivael** [comment]
I came across this bug today in 3.3.1

I used https://github.com/chalsek8 code above to fix the error message.
