### ISSUE TITLE
Click count not working

### ISSUE THREAD

**Issue by remorozadarrel** [mautic/mautic#7175]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
We have upgrade the version from 1.9 to 2.14 but when we tried to click the url the click count not updated

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 7.0
| Browser | Chome

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Aren't you opening the email link in the same browser you are logged into? https://www.mautic.org/docs/en/emails/troubleshooting.html

**Comment by remorozadarrel** [comment]
@escopecz that solve the problem i open on incognito browser. Thanks man!
