### ISSUE TITLE
Crashing when searching contacts 

### ISSUE THREAD

**Issue by LunarDevelopment** [mautic/mautic#7176]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.14.2
| PHP version | PHP Version 7.1.17-1+ubuntu16.04.1+deb.sury.org+1
| Browser | Chrome

### Steps to reproduce
1.  search on contacts page for (email_read:1) OR (email_read:2) 
2. 500 server error or query never completes
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Cannot reproduce. Please provide the error message from the logs. See https://www.mautic.org/docs/en/tips/troubleshooting.html

Will close until the error message is provided.
