### ISSUE TITLE
SQL Select error while querying for leads

### ISSUE THREAD

**Issue by GosuTeacher** [mautic/mautic#7177]
## Bug Description
SQL Select query crashes when searching leads by email.
`Mautic\LeadBundle\Entity\LeadRepository:115`
This was observed when trying to sync with Citrix GoToWebinar.
The values for the where in statement is not parameter bound and it fails due to generating a `SELECT * FROM leads WHERE IN (asd@as, asdas@df)` like query. The quotes on strings are missing.

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 7
| Browser | CLI

### Steps to reproduce
1. Try to sync leads.

**Comment by Noa83** [comment]
Got the same issue @GosuTeacher and solved it, check this PR and test it please:  https://github.com/mautic/mautic/pull/7430

**Comment by npracht** [comment]
Fixed when #7430 merged.
