### ISSUE TITLE
Error viewing Reports

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#7178]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hmm, odd one. I can't make heads or tales of the error log below. I'm hoping someone with more expertise can help :). 

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1. Try to view a none default report.
 
### Log errors

`[2019-01-29 16:37:56] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT count(es.id) as sent, count(CASE WHEN es.is_read THEN 1 ELSE null END) as "read", count(CASE WHEN es.is_failed THEN 1 ELSE null END) as failed FROM ma_email_stats es LEFT JOIN ma_emails e ON e.id = es.email_id LEFT JOIN ma_leads l ON l.id = es.lead_id LEFT JOIN ma_ip_addresses i ON i.id = es.ip_id LEFT JOIN ma_emails vp ON vp.id = e.variant_parent_id LEFT JOIN ma_categories c ON c.id = e.category_id WHERE (es.date_sent IS NULL OR (es.date_sent BETWEEN ? AND ?)) AND (e.is_published = ?) GROUP BY cut.hits' with params ["2018-05-27 23:00:00", "2019-01-28 23:59:59", "1"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cut.hits' in 'group statement'" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT count(es.id) as sent, count(CASE WHEN es.is_read THEN 1 ELSE null END) as \"read\", count(CASE WHEN es.is_failed THEN 1 ELSE null END) as failed FROM ma_email_stats es LEFT JOIN ma_emails e ON e.id = es.email_id LEFT JOIN ma_leads l ON l.id = es.lead_id LEFT JOIN ma_ip_addresses i ON i.id = es.ip_id LEFT JOIN ma_emails vp ON vp.id = e.variant_parent_id LEFT JOIN ma_categories c ON c.id = e.category_id WHERE (es.date_sent IS NULL OR (es.date_sent BETWEEN ? AND ?)) AND (e.is_published = ?) GROUP BY cut.hits' with params [\"2018-05-27 23:00:00\", \"2019-01-28 23:59:59\", \"1\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'cut.hits' in 'group statement' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cut.hits' in 'group statement' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'cut.hits' in 'group statement' at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} [`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Should be fixed by https://github.com/mautic/mautic/pull/7085
