### ISSUE TITLE
How can we send Lead Email ? What kind of cron job to set?

### ISSUE THREAD

**Issue by kithokit** [mautic/mautic#718]
I found that we can directly send Email to target lead list without using a campaign. 

But how can we achieve this? What kind of cron job to be set? Thanks!

**Comment by escopecz** [comment]
Hi, you need cron job to send email only if you use the Queue (configuration option). If you use Send Immediately option, no cron job is needed. However, if you want to send mass email to hundreds or more leads, I'd recommend to use the Queue.

Here you have list of all available cron jobs:
https://www.mautic.org/docs/setup/index.html
