### ISSUE TITLE
Can't add category to email message

### ISSUE THREAD

**Issue by shockalotti** [mautic/mautic#7181]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I'm attempting to add a category, I've already created, to an email message. But the system won't let me.

Is this a bug, or am I trying to use categories the wrong way?

Here's a video showing what I mean:
https://cl.ly/18efff136413

| Q   | A
| --- | ---
| Mautic version 2.15.0 | 
| PHP version 7.0.33| 
| Chrome browser on PC | 
 
### Log errors
None that I can find.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by colourfulowl** [comment]
Can you please check to see if there are any errors in your logs and add them here? The categories in the drop down should match those you add into the category section.

**Comment by escopecz** [comment]
In your video you can clearly see that the category you've created is type of Stage. So you can use it for stages only. Maybe you'd be interested in the **Global** category type which was added later and can be used everywhere.
