### ISSUE TITLE
Duplicate stages change log when editing contact through API

### ISSUE THREAD

**Issue by DanielCiochiu** [mautic/mautic#7183]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When editing a contact through Mautic API, the stages change log is increased with the same stage identifier even tough no stage was modified for this contact.

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 7.0
| Browser | -

### Steps to reproduce
1. Create a stage in Mautic backend
2. Create a contact and add previous created stage to this contact
3. Make patch request to {your.mautic.domain}/api/contacts/{id}/edit using the following body request {"firstname": "Test Name"}
4. Check contact information in backend

### Expected
Only one stage change event should be visible in history tab

### Actual
Another stage change change event is visible even though no new stage was assigned to this contact

### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by eschiendorfer** [comment]
Isnt it the same as my report? https://github.com/mautic/mautic/issues/7064

**Comment by npracht** [comment]
Merged in 2.15.1
