### ISSUE TITLE
Disable Javascript permit to submit form without required fields

### ISSUE THREAD

**Issue by Lolowe** [mautic/mautic#7185]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When I disable javascript on Chrome, I'm able to submit a form without fill required fields. Even with captcha, even with google reCaptcha plugin. There are only client side security and no server side security.
I observed that because a kind of robot is adding hundreds contacts in my Mautic, without filling the form.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 5.6
| Browser | Chrome

### Steps to reproduce
1. Create a form with required fields
2. Disable Javascript in Chrome parameters
3. Submit the form without fill all required fields.
4. Check that a new contact is created without required fields.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!
