### ISSUE TITLE
Scheduled segment email date/time on the list view

### ISSUE THREAD

**Issue by trianity** [mautic/mautic#7188]
In the Mautic 2.15.0 only **Name**, **Category** **Stats**, and **ID** columns are in the list view of Channels/Emails function.

For the scheduled segment emails there would be very useful an one column more **to show what date/time was scheduled** the listed email.

![2019-01-30_1736](https://user-images.githubusercontent.com/6353141/51997405-f552c180-24b6-11e9-8cea-5337c7fa4ba2.png)

I am running a Matuc instance with hundreds of segment emails (most of them scheduled on the creation moment) and when we are running a biggest campaign, would be very useful to look at it at a glance all scheduling data in the list.
Now, you should click the Edit, to see the scheduling data, and two clicks more to close, and see the next email.

**Comment by RCheesley** [comment]
Hi there, if this is still an issue in Mautic 3.x would you be able to submit a PR to implement the functionality?
