### ISSUE TITLE
CSV file import frozen on browser and background

### ISSUE THREAD

**Issue by mdeotti** [mautic/mautic#7190]
I'm trying to import a CSV file of 19k contacts, set up a limit to 1000 per batch.

The import freezes on the browser (not a single contact is imported) and also doesn't work if I leave to run on the background. Cron job is set up correctly.

Log error:

`mautic.NOTICE: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) (uncaught exception) at /home/xxxxx/marketing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 while running console command `mautic:import` [] []`

I can import with **no problem** files with fewer contacts.

| Mautic version | v2.15.0
| PHP version | 7.0.25
| Browser | Chrome

**Comment by raghav111jain** [comment]
same thing happened if upload csv don't process ij front and background also. if click background not process only show in q  and if click import on browser both are condition not processing then if import on browser and refresh the page import same contact . i don't understand what type issue Please help ASAP  
Mautic version |3.0
| PHP version | 7.2
| Browser | Chrome

**Comment by RCheesley** [comment]
This error suggests that the connection to the database is having problems with larger imports. This can happen if you are running low on resources on the server. Please contact your server admin or hosting provider to troubleshoot as it is probably an issue there rather than with Mautic.
