### ISSUE TITLE
Bounce Management - Amazon SNS

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#7199]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I've been trying to connect Mautic to the SNS service from Amazon for my Bounce Management. However, it's been giving my the below error causing the Topic to hand as 'PendingConfirmation'. Any ideas?

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.30
| Browser | Chrome

### Steps to reproduce
1. Follow the instructions here: https://www.mautic.org/docs/en/emails/bounce_management.html
 
### Log errors

`[2019-01-31 10:05:26] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport::processCallbackRequest() must be an instance of Symfony\Component\HttpFoundation\Request, null given, called in /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/EventListener/EmailSubscriber.php on line 172" at /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php line 97 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Mautic\\EmailBundle\\Swiftmailer\\Transport\\AmazonTransport::processCallbackRequest() must be an instance of Symfony\\Component\\HttpFoundation\\Request, null given, called in /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/EventListener/EmailSubscriber.php on line 172 at /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php:97)"} []
[2019-01-31 10:05:53] mautic.NOTICE: PHP Notice - Undefined variable: request - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/EmailBundle/Event/TransportWebhookEvent.php - at line 56 [] []`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by virgilwashere** [comment]
fixed in a post 2.15.0 update.

here: #7015

**Comment by npracht** [comment]
Please test and install #7015 or wait for 2.15.1 as mentioned by @virgilwashere
