### ISSUE TITLE
Emails with invalid From address can be created/saved

### ISSUE THREAD

**Issue by vshulev** [mautic/mautic#7202]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Someone from our team had accidentally updated an email with an invalid From field of the form someemail@example.comsomeotheremail@example.com (i.e. they just appended the new address to the old one instead of clearing the field). As a result the cron job started crashing because of invalid email format.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1.26
| Browser | Chrome 71.0.3578.98

### Steps to reproduce
1. Create an email or edit an existing one with an invalid email address such as the one show above
2. Run mautic:campaigns:trigger
 
#### Output of cron command
(I've skipped some of the output)
```
Triggering scheduled events
127 total events(s) to be processed in batches of 100 contacts
  40/127 [========>-------------------]  31%
Warning: preg_match_all(): Unknown modifier '/' in /var/www/html/app/bundles/CoreBundle/Helper/UrlHelper.php on line 182

Warning: preg_match_all(): Unknown modifier '/' in /var/www/html/app/bundles/CoreBundle/Helper/UrlHelper.php on line 182
 127/127 [============================] 100%
                                                                                                                                                     
  [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                            
  Wrong parameters for Mautic\EmailBundle\Exception\FailedToSendToContactException([string $message [, long $code [, Throwable $previous = NULL]]])  
                                                                                                                                                     

mautic:campaigns:trigger [-i|--campaign-id [CAMPAIGN-ID]] [--campaign-limit [CAMPAIGN-LIMIT]] [--contact-id [CONTACT-ID]] [--contact-ids [CONTACT-IDS]] [--min-contact-id [MIN-CONTACT-ID]] [--max-contact-id [MAX-CONTACT-ID]] [--thread-id [THREAD-ID]] [--max-threads [MAX-THREADS]] [--kickoff-only] [--scheduled-only] [--inactive-only] [-l|--batch-limit [BATCH-LIMIT]] [--negative-only] [-f|--force] [--bypass-locking] [-t|--timeout TIMEOUT] [-x|--lock_mode LOCK_MODE] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>
```

### From log file
```
[2019-01-31 16:32:19] mautic.ERROR: [MAIL ERROR] Address in mailbox given [someemail@example.comsomeotheremail@example.com] does not comply with RFC 2822, 3.6.2. (from) [] []
[2019-01-31 16:32:19] mautic.NOTICE: Symfony\Component\Debug\Exception\FatalThrowableError: Wrong parameters for Mautic\EmailBundle\Exception\FailedToSendToContactException([string $message [, long $code [, Throwable $previous = NULL]]]) (uncaught exception) at /var/www/html/app/bundles/EmailBundle/Model/SendEmailToContact.php line 343 while running console command `mautic:campaigns:trigger` [] []
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
I'd mark it as an enhancement as far as your solution is simply to use a valid email.

## Enhancement suggestion
Add a email format validator on email from input.

**Comment by vshulev** [comment]
@npracht I described it as a bug because of the consequences it has on the cron job. If one email is invalid it prevents all campaign actions across all campaigns from triggering.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
