### ISSUE TITLE
Segmentation by email address not being an option anymore

### ISSUE THREAD

**Issue by alafa** [mautic/mautic#7203]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I am not sure if this falls into the "bug" category. The thing is that in previous versions this was working and I do not know if it is a bug or got deprecated on purpose. 

When defining the filters of a segment, the option of "Email" is not there anymore.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 5.6.40
| Browser | Chrome

### Steps to reproduce
1. Go to "Segments".
2. Create new (or edit existing one).
3. Click on "Filters".
4. Try to choose "Email".
 
### Log errors

None.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### Images of evidence

[In previous versions](https://cdn1.imggmi.com/uploads/2019/2/1/410e7db68188f7a790d00645835eec88-full.png)
[In version 2.15.0](https://cdn1.imggmi.com/uploads/2019/2/1/b8de9b3de793d4f9ca5a94b554a0ae60-full.png)

**Comment by acs-ferreira** [comment]
Not having that option missing in **v2.15.0** ...

![image](https://user-images.githubusercontent.com/12234510/52129674-67064900-2638-11e9-80d1-e5aacf4ded30.png)

**Comment by npracht** [comment]
Not reproducing. Please check your update (schema update, asset generate, clear cache).
