### ISSUE TITLE
mautic database encryption

### ISSUE THREAD

**Issue by sourabhde18** [mautic/mautic#7207]
Hello guys,can you please help me I want encryption and decryption of mautic database. is there any solution available

**Comment by sourabhde18** [comment]
HI thanks for link i need table level encryption .
example:- if someone hack our database than there is only encrypted data .

**Comment by acs-ferreira** [comment]
This is exactly that.

Read more at https://dzone.com/articles/mysql-data-at-rest-encryption

**Comment by sourabhde18** [comment]
Hi i done this one but when i login in php my admin it still show data .key ring plugin is use for make ldb file encrypted.

**Comment by npracht** [comment]
Hi guys, thanks a lot. Please move chatting to Slack.
Thanks.
