### ISSUE TITLE
Contact Segment Membership report duplicate emails

### ISSUE THREAD

**Issue by inspiremedia01** [mautic/mautic#7216]
When i run a Contact Segment Membership report, and export to csv, it is showing lots of duplicate emails (I have seen 10 or more of the same email). All duplicate emails have the same Mautic unique ID.

If I search in Mautic Contacts interface for the duplicate email(s), it only returns 1 record for that email.

If I go into phpmyadmin and search in the leads object, the duplicate email will only show 1 record for that email.

It seems like this is a bug in the reporting?

Can anyone assist or shed light?

| Q   | A
| --- | ---
| 2.15.0 | 
| 7.1.26 | 
| Firefox Developer Edition | 

### Steps to reproduce
1. Create a Contact Segment Membership Report
2. Set a Filter in the report for 1 segment only
3. Export the report to csv
4. Filter emails a-z and look for duplicates.

**Comment by escopecz** [comment]
Fix it by adding group by option set to email field.
