### ISSUE TITLE
[API] Contact update is neither ignoring empty nor null values

### ISSUE THREAD

**Issue by mabdelfattah** [mautic/mautic#7225]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The following request, is updating custom_field with *0*, creates a new *tag*, assign it to the user, and mark the user as *do not contact*.
```
PATCH: /api/contacts/ID/edit
{"body"=> 
  {"id"=>ID,
   "custom_field"=>null,
   "tags"=>[],
   "doNotContact"=>[]
}
```
I think this should reset the values, and not create new ones!

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.33
| Browser | API

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hello @mabdelfattah this is not very clear.
What did you expect as a result and what exactly happened?

**Comment by mabdelfattah** [comment]
@npracht I'm expecting nothing to happens to those fields or reset them. But I do not expect Mautic to create a Tag and assign it to that user. Also, I don't expect Mautic to mark/flag this user as DNC user.

**Comment by npracht** [comment]
Can you show the contact information before and after please ?

**Comment by DevelopMan** [comment]
The issue is there `app/bundles/ApiBundle/Controller/CommonApiController.php`
`processForm` method, the line `$form->submit($submitParams, 'PATCH' !== $method);`. The second parameter of the method 'submit' is `clearMissing`, so, if we use `PATCH` method - all nullable parameters will be skipped. We can use `PUT` method to clear some contact fields but there is another problem: it will create a new contact if it does not exist.
Is it possible to fix this bug?

**Comment by SanderVanKeer** [comment]
Is there any news on this matter? I'm facing the same issue.
Thanks in advance

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
I am also facing the same issue.
My Case:-
I am creating leads from my Mautic's plugin by using the below code

```
// Set the lead's data
$leadModel->setFieldValues($lead, $leadFields);

// Save the entity
$leadModel->saveEntity($lead);

// Set the updated lead
$leadModel->setCurrentLead($lead);
```

This is ignoring the empty and null values, 
so that I am not able to update the null values in contact fields.
Reference [https://developer.mautic.org/#manipulating-contacts-(leads)](https://developer.mautic.org/#manipulating-contacts-(leads)) 

Any one have any solution for this ?

**Comment by RCheesley** [comment]
@DevelopMan would you be up for creating a PR to address this issue as it still seems to be a problem for folk.  It would be good to double check if it is still a problem in Mautic 3.x but I suspect it probably is!

**Comment by DevelopMan** [comment]
> @DevelopMan would you be up for creating a PR to address this issue as it still seems to be a problem for folk. It would be good to double check if it is still a problem in Mautic 3.x but I suspect it probably is!

Can confirm that this issue still presents on Mautic 3.0.2. I have no solution for this neither PR, sorry. We just update our fields with "-" (or similar").

**Comment by RCheesley** [comment]
@DevelopMan thanks for taking the time to check and ged back to us! I'll mark it an to be fixed. and hopefully we can get it addressed soon!

**Comment by DevelopMan** [comment]
We still waiting for a solution.

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Not fixed yet.

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi Guys,
I have found the solution and it is very easy also.
To make update with blank values in contacts, you have to just pass `true` as third parameter in the `setFieldValues` function.
Like this :
 `$leadModel->setFieldValues($lead, $leadFields,true);` 
 This will solve your problem.

**Comment by DevelopMan** [comment]
@Bibhudatta-Sahoo-ASMB But this is the solution for what? :) The issue is with the endpoint PATCH: /api/contacts/ID/edit
The solution will be to add this parameter to the endpoint.

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
I have issue with plugin edit contact so for that it is the solution, and just like this for API also there will be parameter to specify overwrite blank values in contact edit.
It solved my issue, may be it can help you to find your solution.
