### ISSUE TITLE
Duplicate emails sent on campaigns when aes send as rejection occurs

### ISSUE THREAD

**Issue by jnewton001** [mautic/mautic#7226]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Issue happens on any campaign when campaign trigger job runs.  If a contact owner in the list of scheduled emails has a code 554 is will not resister the other contacts in that job as the send email event did occur and will simply just keep sending them over and over again. I understand that all should be authorized but human error seems to always find a way to sneak one in before ASES is updated. Thinking the error that happens should be captured and the other records still updated as sent to prevent duplication. 

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.33
| Browser | Chrome

### Steps to reproduce
1. Create 2 contacts on with a verified owner one attached to a non verified owner.
2. Trigger a send email on a campaign with both users on that campaign with the email scheduled within the same job run.
3. Verified contact owner  will receive the email endlessly until you stop the campaign.
 
### Log errors

mautic.ERROR: [MAIL ERROR] Expected response code 250 but got code "554", with message "554 Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: Michael Estrada , mestrada@nathomelending.com " Log data: >> MAIL FROM:  << 250 Ok  >> RCPT TO:  << 250 Ok  >> DATA  << 354 End data with .  >>  .  << 554 Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: Michael Estrada , mestrada@nathomelending.com  !! Expected response code 250 but got code "554", with message "554 Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: Michael Estrada , mestrada@nathomelending.com " (code: 554) (send); jnewton@gsfmail.com [] 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Please confirm your version of mautic.

**Comment by jnewton001** [comment]
2.9.2

**Comment by jnewton001** [comment]
Actually scratch that we have upgraded 2.15.0 to latest stable

**Comment by npracht** [comment]
In 2.15.0 issue is still happening ?

**Comment by jnewton001** [comment]
Yes issue is still happening in 2.15.0.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/7413

**Comment by npracht** [comment]
Fixed when #7413 merged.

**Comment by carotenuto88** [comment]
Guys, I'm having the same problem here with some contacts, emails are send over an over, non-stop. I'm using v2.15.1.

Someone can help me?
Thanks
