### ISSUE TITLE
Empty Asset Download on Contact History

### ISSUE THREAD

**Issue by eVolpeConsultingGroup** [mautic/mautic#7227]
## Bug Description

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1
| Browser | Chrome (not important)

### Steps to reproduce
1. Create an Asset (for example PDF file)
2. Create Template Email
2.1. In Advanced tab in Attachments field add your Asset
3. Create example Contact with email address and example Segment and add this Contact to this Segment
4. Create Campaign for above Segment with Action:
4.1. Send Email (from point 2.)
5. Execute this Campaign (by cron jobs)
6. In a few minutes your example Contact should get Asset Download activity - without Asset data:
![empty_asset](https://user-images.githubusercontent.com/47445836/52469853-e9d55980-2b8c-11e9-9b16-9ef31cfaed18.PNG)

In database, in table `asset_downloads`, field in `asset_id` is NULL in row entry:
![empty_asset_db](https://user-images.githubusercontent.com/47445836/52470114-93b4e600-2b8d-11e9-9290-b4ca7f691c3c.PNG)
 
### Log errors
There are no errors in [mautic root]/app/log/... and no errors in server's logs.

**Comment by KaKite** [comment]
I have the same problem with the same Mautic/PHP versions

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!
