### ISSUE TITLE
RuntimeException at mautic:campaigns:trigger with --max-events option

### ISSUE THREAD

**Issue by AndreD23** [mautic/mautic#7229]
Hi!
Anyone having issue doing mautic:campaigns:trigger with --max-events option? Has this option been removed at 2.15 version? If yes, there is an alternative for that?

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 7.2.14

### Steps to reproduce
1. Run php app/console mautic:campaigns:trigger --batch-limit=50 --max-events=50
2. Get a message:
[Symfony\Component\Console\Exception\RuntimeException]  
  The "--max-events" option does not exist.

![screenshot_1](https://user-images.githubusercontent.com/36412489/52508709-ac002180-2bdc-11e9-9757-3693253d1a6f.png)

**Comment by escopecz** [comment]
I didn't know such option existed. But you are right. I don't see it in the command help:
```
$ app/console mautic:campaigns:trigger --help
Usage:
  mautic:campaigns:trigger [options]

Options:
  -i, --campaign-id[=CAMPAIGN-ID]        Trigger events for a specific campaign.  Otherwise, all campaigns will be triggered.
      --contact-id[=CONTACT-ID]          Trigger events for a specific contact.
      --contact-ids[=CONTACT-IDS]        CSV of contact IDs to evaluate.
      --min-contact-id[=MIN-CONTACT-ID]  Trigger events starting at a specific contact ID.
      --max-contact-id[=MAX-CONTACT-ID]  Trigger events starting up to a specific contact ID.
      --thread-id[=THREAD-ID]            The number of this current process if running multiple in parallel.
      --max-threads[=MAX-THREADS]        The maximum number of processes you intend to run in parallel.
      --kickoff-only                     Just kickoff the campaign
      --scheduled-only                   Just execute scheduled events
      --inactive-only                    Just execute scheduled events
  -l, --batch-limit[=BATCH-LIMIT]        Set batch size of contacts to process per round. Defaults to 100. [default: 100]
      --negative-only                    Just execute the inactive events
  -f, --force                            Force execution even if another process is assumed running.
      --bypass-locking                   Bypass locking.
  -t, --timeout=TIMEOUT                  If getmypid() is disabled on this system, lock files will be used. This option will assume the process is dead afer the specified number of seconds and will execute anyway. This is disabled by default. [default: false]
  -x, --lock_mode=LOCK_MODE              Force use of PID or FILE LOCK for semaphore. Allowed value are "pid" or "file_lock". By default, lock will try with pid, if not available will use file system [default: "pid"]
  -h, --help                             Display this help message
  -q, --quiet                            Do not output any message
  -V, --version                          Display this application version
      --ansi                             Force ANSI output
      --no-ansi                          Disable ANSI output
  -n, --no-interaction                   Do not ask any interactive question
  -s, --shell                            Launch the shell.
      --process-isolation                Launch commands from shell as a separate process.
  -e, --env=ENV                          The Environment name. [default: "prod"]
      --no-debug                         Switches off debug mode.
  -v|vv|vvv, --verbose                   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Trigger timed events for published campaigns.
```
And I can see it existed in the past by doing this search: 

https://github.com/mautic/mautic/search?q=%22max-events%22&type=Issues

So there has been a BC break at some point. I guess it was during the campaign redesign where it wasn't needed anymore. Maybe it was just an alias for `--batch-limit`?

The question is whether you need that parameter for something?

**Comment by AndreD23** [comment]
Yep, that option is usefull for my campaign build, because, like --max-contacts of segments:update, that interacts from campaign to campaign by firing a specific number of events.

This option still appears in the link documentation https://www.mautic.org/docs/en/setup/cron_jobs.html

Is it possible to reactivate the option? Helps a lot for huge campaigns.

**Comment by AndreD23** [comment]
Any update about it?

**Comment by PetrusHenrique** [comment]
Any alternative?

**Comment by elliott-io** [comment]
Really need this functionality. What is the workaround?

From the docs at https://www.mautic.org/docs/en/setup/cron_jobs.html

"By default, the script will process events in batches of 100. If this is too many for your server's resources, use the option --batch-limit=X replacing X with the a number of events to process each batch.

"You can also limit the number of contacts to process per script execution using --max-events to further limit resources used."

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by AndreD23** [comment]
Hello! What a coincidence, I went back to this issue to see if there were any updates.

This morning I downloaded version 3.0.2 of Mautic to check this issue. The problem still remains.

**Comment by npracht** [comment]
Thanks a lot for your helpful feedback 👍
