### ISSUE TITLE
syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING

### ISSUE THREAD

**Issue by luizdevoper** [mautic/mautic#7232]
<b>Parse error</b>:  syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in <b>/public_html/mautic/app/console</b> on line <b>22</b><br />

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1

Error executing cron
mautic/app/console mautic:segments:update --force --batch-limit=300
mautic/app/console mautic:campaigns:rebuild --force --batch-limit=300
mautic/app/console mautic:campaigns:trigger --force --batch-limit=100
mautic/app/console mautic:emails:send
mautic/app/console mautic:email:fetch
mautic/app/console mautic:webhooks:process
mautic/app/console mautic:iplookup:download

**Comment by npracht** [comment]
Hi @luizdevoper. Please explain how to reproduce the issue.
Thanks.

**Comment by luizdevoper** [comment]
When I created the campaign inside the Mautic I realized that the emails were not being sent. The error log has no error information.

Then I realized that in the CronJob log of the server is experiencing this error.

It is displayed every time the cronjob is executed.

**Comment by escopecz** [comment]
I'm pretty sure that your CLI use an old PHP version. Execute `php -v` to see what version it uses. HTTP server and CLI can use different PHP versions. Consult with Google or your server admin how to upgrade PHP for CLI.
