### ISSUE TITLE
Apply button breaks the layout of my email

### ISSUE THREAD

**Issue by alfonsocala** [mautic/mautic#7234]
Hi! I have an email ready for sending, it was built in another tool andworks perfect in every html tester i haved tried. This one for example: https://htmledit.squarefree.com/

However, when i paste the html into a blank email in Mautic and push Apply to finish and send it the email is totally broken. The only message the console shows me is "Editor should be initialized before calling the destroy method." 

Could you help me?

Thanks in advance

Alfonso

**Comment by escopecz** [comment]
Do you use really the Blank theme for it? Why don't you use the Code Mode which was built for this?

**Comment by alfonsocala** [comment]
Thanks for the answer :).

Sorry, mistake while writing. I used the code mode not the blank one, and the error occurs.

**Comment by escopecz** [comment]
In that case you'll have to provide the problematic HTML for testing. No one can help you without it.

**Comment by alfonsocala** [comment]
Ok, this is the mail:

http://works.innn.es/innn/mail.html

Then paste the code code in Mautic code mode email template and when i push the apply button the email is totally broken.

**Comment by escopecz** [comment]
Try to [make the HTML valid](https://validator.w3.org/check) and then try again.

![screenshot 2019-02-14 at 10 12 10](https://user-images.githubusercontent.com/1235442/52775940-12ec6300-3041-11e9-9527-844acd69714a.png)

I bet that's the reason behind it.
