### ISSUE TITLE
BUG! Oauth1.0 invalid_signature bug still happening on version 2.15.0.

### ISSUE THREAD

**Issue by diegodorgam** [mautic/mautic#7237]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The Oauth1.0 invalid_signature bug  is still happening on version 2.15.0.
I have created the API Credential in Mautic for Oauth1.0a and enabled the HTTP basic authentication also in Configuration / API Settings.

When I try to call the `POST /oauth/v1/request_token` with the specified parameters, like this:
```shell
curl -X POST \
  https://my.mautic.domain/oauth/v1/request_token \
  -H 'Authorization: OAuth oauth_consumer_key="67ukpmljv2oso5wck08g0wwokcsc0gsc0k8w0owc8s08kow4o8",
oauth_signature_method="HMAC-SHA1",
oauth_timestamp="1549977818",
oauth_nonce="S1MKLimByEN",
oauth_version="1.0",
oauth_signature="PCQoiBanSWh6CotBuf%2F%2BtL46VV0%3D"'
```
it returns me the following message:
```json
{
    "errors": [
        {
            "message": "Looks like I encountered an error (error #401). If I do it again, please report me to the system administrator!",
            "code": 401,
            "type": null
        }
    ],
    "error": {
        "message": "Looks like I encountered an error (error #401). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)",
        "code": 401
    }
}
```
and at the `app/logs/mautic-production...php` i get the error:
```
mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "signature_invalid" at /var/www/html/vendor/willdurand/oauth-server-bundle/Service/OAuthServerService.php line 174 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\HttpException(code: 0): signature_invalid at /var/www/html/vendor/willdurand/oauth-server-bundle/Service/OAuthServerService.php:174)"} []
```

seems that it's something that have (happened before)[https://github.com/mautic/mautic/issues/5748], and it was supposed to be fixed by (PR#166)[https://github.com/mautic/api-library/pull/166] in version 2.14.2, but is still happening on 2.15.0

any ideas?

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | Docker latest image version with apache2
| Browser | API problem not browser related

### Steps to reproduce
1. Create API Credentials for Oauth1.0
2. Use it to call for resquest_token as in the docs
```
curl -X POST \
  https://my.mautic.domain/oauth/v1/request_token \
  -H 'Authorization: OAuth oauth_consumer_key="67ukpmljv2oso5wck08g0wwokcsc0gsc0k8w0owc8s08kow4o8",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1549977818",oauth_nonce="S1MKLimByEN",oauth_version="1.0",oauth_signature="PCQoiBanSWh6CotBuf%2F%2BtL46VV0%3D"'
```
 
### Log errors
```json
{
    "errors": [
        {
            "message": "Looks like I encountered an error (error #401). If I do it again, please report me to the system administrator!",
            "code": 401,
            "type": null
        }
    ],
    "error": {
        "message": "Looks like I encountered an error (error #401). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)",
        "code": 401
    }
}
```
and at the `app/logs/mautic-production...php` i get the error:
```
mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "signature_invalid" at /var/www/html/vendor/willdurand/oauth-server-bundle/Service/OAuthServerService.php line 174 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\HttpException(code: 0): signature_invalid at /var/www/html/vendor/willdurand/oauth-server-bundle/Service/OAuthServerService.php:174)"} []
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
@Woeler or @IchHabRecht any opinion on that ?

**Comment by Woeler** [comment]
Well, I use this endpoint every day, so it is definitely not broken. You're also missing a callback url. I'm not sure how you are generating the signature, but the way it is done in the api library package works. https://github.com/mautic/api-library/blob/master/lib/Auth/OAuth.php#L616

**Comment by diegodorgam** [comment]
I understood that the callback URL was optional, and that the signature generation algorithm was kind of a industry standard. When I make the call using Postman, it generates the signature automatically, and when I try to do it using python's requests_oauth lib it's also auto generated, so...
thanks anyway, I'll settle with basic http auth..

**Comment by trampos** [comment]
Hello, i figured out why i was getting this error. 

Its happening when in my feed there is any of these values: null, "", "0" or 0. 

I'll keep debugging my code, once there is a chance of the problem being in my application.

sry about my bad english.

**Comment by Urano-Gonzalez** [comment]
I have the same issue. Version 2.15.0. I tried to explain to mautic that this is not a bug and this issue is closed, but the buis alive, still.
