### ISSUE TITLE
Why form actions are restricted to landing pages in the same domain as Mautic?

### ISSUE THREAD

**Issue by fullofcaffeine** [mautic/mautic#7241]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | Can't find, but downloaded Dic 2018 |
| PHP version | PHP Version 7.2.10  |
| Browser |  Chrome |

### Steps to reproduce
1. Create a new campaign form, set action to redirect to a URL.
2. Post to this form using mautic_form.js from an external custom landing page hosted in a domain that's different from the domain Mautic is hosted at.
3. The data is submitted, but the action doesn't run (parent.postMessage fails or doesn't run).
 
__Why does Mautic restrict form posts only to landing pages hosted @ the same domain as Mautic?__ I have several landing pages I built myself that are hosted outisde Mautic, hence, at different domains. 

Even though it does look great, I don't plan on using Mautic's landing pages funcionality at the moment. This then severely restricts my use of Mautic.

__I did manage to make it work by removing the following code in `media/mautic_form.js`:__

```js
if(MauticDomain.indexOf(event.origin)!==0)return;
```

But I'm a bit confused right now:

1) Is it a viable workaround?
2) Why is this hard-coded restriction even there in the first place? I actually thought it was related to the "Domain restriction" setting in Mautic, but disabling it doesn't seem to solve the problem. Only removing that piece of code made the postMessage to work as expected and the redirection to take place.
3) This should actually be configurable, no? I mean, I shouldn't need to edit and remove a piece of code in Mautic to make it work. Or did I miss something?

Thanks in advance!

**Comment by npracht** [comment]
Hi, this restriction is not existing. It should work (it work on my side, using that everyday).
When you submit the form, what do you have in the browser console ?
Also, are you in private browser ?

Thanks

**Comment by fullofcaffeine** [comment]
Hi @npracht, thanks a lot for replying!

> When you submit the form, what do you have in the browser console ?
No errors. The `parent.postMessage` just fails to run (or doesn't run at all).

> Also, are you in private browser ?
No, regular Chrome session.

 I'm pretty sure it has to do with the piece code I mentioned above. If you check it out, it makes sense: it returns if the origin url doesn't contain the Mautic domain. As I said above, I removed it (from the minified js file, that's why it looks a bit funny) __and it started to work__, but it feels hacky. I just want to understand why it didn't work because clearly, that code was preventing it from working, and removing it feels a bit hacky. 4) Maybe I have an outdated Mautic version?

5) I'm curious on why Mautic uses the postMessage strategy. I actually didn't know about this, it's strange but interesting. Why doesn't Mautic redirect from the server side?

Cheers!

**Comment by npracht** [comment]
I'm using it everyday. So i don't think a piece of code has to be changed.
The version of your mautic instance is written on the very bottom right of your dashboard page.

Please confirm.

**Comment by fullofcaffeine** [comment]
@npracht `v2.15.0`

**Comment by npracht** [comment]
Are the CORS enabled in your configuration ? Settings > Configuration ?

**Comment by escopecz** [comment]
Closing as the question hasn't been answered for a wile. Hopefully it's resolved now.

**Comment by fullofcaffeine** [comment]
Hi @escopecz,

It's working, but I'm still running the version of Mautic I modified, as described in the original post above. I haven't tried more recent versions.
