### ISSUE TITLE
Update without replacing existing values in multi-selection field

### ISSUE THREAD

**Issue by guiloviu** [mautic/mautic#7242]
Hi all!

I just installed Mautic and I am very happy with its features. It practically solves all the problems of organization and data management in my company. But I lack a functionality that I think is not active: the possibility of having a multi-select field that will "grow" instead of replacing it with the most current value.

For example: the contact registers in a form for the first time that he is interested in 'cinema' and 'music'. The contact registers in another form later that he is interested in 'theater' and 'sports'. Our goal is that in the multi-select field it is kept that the contact is interested in 'cinema', 'music', 'theater' and 'sports' (and not that it replaces 'cinema' and 'music' with 'theater' and 'sports')

Would it be possible nowadays with the latest version of Mautic or would it require some type of programming?

Thank you!

**Comment by escopecz** [comment]
Try to use the checkbox field instead.

**Comment by guiloviu** [comment]
In Mautic, it only leaves two types of fields: Select and Select - Multiple. The checkboxes are only enabled in forms. This option has already been tested and does the same as with a select: replace the previous value with the new one instead of adding the new value next to the old one.

**Comment by kuzmany** [comment]
Already exists https://github.com/mautic/mautic/pull/6805

**Comment by guiloviu** [comment]
but in post #6805 , they talk about this functionality, but in campaigns. I need this functionality ALWAYS: either in campaigns, in campaign forms, in independent forms, etc ...

**Comment by RCheesley** [comment]
Hi folks, given the PR's that are already open and a lack of recent interaction on this issue I'm going to close it down.
