### ISSUE TITLE
Dynamic content/conditional for email subjects not working

### ISSUE THREAD

**Issue by fullofcaffeine** [mautic/mautic#7247]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.15.0 |
| PHP version | PHP Version 7.2.10  |
| Browser |  Chrome |

### Steps to reproduce
1. Create a new email
2. Try to use dynamic contents in the subject

This might not be a bug, but I tried to create a forum post but registrations are closed (?). Also tried contacting the @mautic-community twitter account but got no replies, I was forced to just post here.

Some of my emails need to use a different word depending on the gender of the contact. It's in Spanish. If sex == F, then word is "bienvenida" (notice the a), if == M, then "bienvenido" (notice the o). Want that logic/interpolation to happen in the email subject (for the body dynamic content works for now). Why would dynamic content not work for the subject of the email?

How do I go about solving that?  Is there a way to use some conditional templating logic in the subject, maybe through plugins? Or maybe this is part of a planned feature?

Thanks in advance!

**Comment by fullofcaffeine** [comment]
I got it working by modifying the twig plugin mentioned in the attached issue (#849). It'd be nice to have this as a core feature in Mautic though.

**Comment by juanlugodegouveia** [comment]
Hi @fullofcaffeine I hope you're well.

Did you manage to put conditional subject line in Mautic? 

Kind regards,
Juan

**Comment by yangenmanuel** [comment]
Any updates on this?
