### ISSUE TITLE
Why are new registrations closed @ mautic.org's community forums? 

### ISSUE THREAD

**Issue by fullofcaffeine** [mautic/mautic#7249]
There's currently no place to discuss features or ask general non-bug-related questions. Why are new registrations closed?

**Comment by dbhurley** [comment]
We've had some challenges identifying spam, while moving to a new platform. Sorry for the delays. The good news is they are being activity fixed now and should be back very soon!

**Comment by michacassola** [comment]
You should't close this issue unless it is fixed. Nobody searches in closed issues for a current issue!

**Comment by dbhurley** [comment]
:) This is a code repo, not a question and answer about the website

**Comment by michacassola** [comment]
The website where the questions and answers would be placed is down. So should we make smoke signs? 😄

**Comment by fullofcaffeine** [comment]
@dbhurley Thanks for replying. Any ETAs on when it'll be back? I have several questions to ask there.
