### ISSUE TITLE
Remoate assets as email attachment not working

### ISSUE THREAD

**Issue by Drukmistrz** [mautic/mautic#7250]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Local, uploaded to mautic attachments are send in email, but remote attachments with link to file are not attached to emails.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.29
| Browser | Chrome

### Steps to reproduce
1. Add remote asset by url
2. Add attachment to email, send email
 
### Log errors
No error logs on apache or mautic, just not working

![mautic-error](https://user-images.githubusercontent.com/46747718/52852263-65e51980-3118-11e9-97fb-d9afbbd6d39c.jpg)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Fixed when #7332 merged.
