### ISSUE TITLE
make mandatory UTMs as required when UTM tracking is toggled to ON

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#7252]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:

In the email edit page, I propose to modify how utm are set, and the validation at save. 

As of today, 2.15, there is no validation whatsoever regarding utm parameters.

The issie is that marketers are seldom aware that 3 of the 5 utm are required if you want UTM tracking in Google Analytics to work.

Therefore I propose to add a toggle to activate UTM tracking in this page. Only when toggled on, the utm fields would appear. But most importantly, when marketer clicks "Apply", there is validation for the following UTM:
- utm_source
- utm_campaign
- utm_medium

As recommended in Google Analytics doc, they must be passed or no utm will be recorded as the pageview is sent. The other one are optional.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1? If so, would you be able to submit a PR for this feature?
