### ISSUE TITLE
email sent only to the first email ID in the bcc: list

### ISSUE THREAD

**Issue by iSaifee** [mautic/mautic#7256]
Mautic version : v2.15.0
PHP version : 7.1.18
Browser : Chrome

### Steps to reproduce
1. Input multiple email addresses separated by comma in BCC field of email
2. email will be received by only first email ID in the BCC list.

**Comment by npracht** [comment]
Hello,

Do you have a message in your logs ?
What is your email sender ?

**Comment by iSaifee** [comment]
which log file?

I am using sendgrid with apikey for outgoing emails.

**Comment by npracht** [comment]
Your mautic logs just after sending an email, maybe something is written here;

**Comment by iSaifee** [comment]
nothing in error_log file

**Comment by fphunzz** [comment]
This is the same bug from #5967. I hope they come out with a fix soon.

**Comment by npracht** [comment]
Ok i'm closing this issue in favor of #5967 because it is the same issue and both are "because of" `Sendgrid`
