### ISSUE TITLE
Contact detail view show related segments

### ISSUE THREAD

**Issue by christian-beckmann** [mautic/mautic#7259]
If you look at a contact, there are no related segments lists. Currently you have to switch to segments list and look in every segment if the contacts is added.

It would be nice to have an opportunity to list all segements by a contact. Like a tab or list.

**Comment by Khaled4** [comment]
This would indeed be an excellent feature. Thank you Christian-Bechmann

**Comment by christian-beckmann** [comment]
Ok, thereby I found it aside in a dropdown "Preferences" and there in a tab "Segments". That was I'm looking for. But it would be easier to find direct in the detailed view.

**Comment by Khaled4** [comment]
Great. Can you kindly include a screen shot?

**Comment by christian-beckmann** [comment]
![2019-02-19 11_52_51-window](https://user-images.githubusercontent.com/7237548/53010022-12870a00-343d-11e9-83b4-debd91d4b32b.png)
![2019-02-19 11_53_10-window](https://user-images.githubusercontent.com/7237548/53010023-12870a00-343d-11e9-9d13-410f065d36b7.png)

**Comment by christian-beckmann** [comment]
Goto contact detail, look for the dropdown at top right side, and click on "Preferences", then switch to "Segments". Our CRM is german language / english mixed.

**Comment by npracht** [comment]
Top right drop down shows this information in preferences
