### ISSUE TITLE
Contact field 'segment' doesn't work when used on contact filter expression.

### ISSUE THREAD

**Issue by carloshmm** [mautic/mautic#7261]
I'm trying to filter my contacts by using the contact field 'segment', using the syntax:
segment:'value'

It returns nothing. 

All the other contact fields works, so I guess the name 'segment' is reserved internally and should not be used as a custom field (what I'm doing now), is it true? Or is this actually a bug?

**Comment by npracht** [comment]
Hello @carloshmm, sorry this is not clear.
Could you please:

- clearly explain how to reproduce (screenshots ?)
- tell the version of mautic you're using.

**Comment by carloshmm** [comment]
> Hello @carloshmm, sorry this is not clear.
> Could you please:
> 
> * clearly explain how to reproduce (screenshots ?)

**I have one contact with these attribute values (segment attribute has value 1):**

![dados](https://user-images.githubusercontent.com/31554436/53346734-63dc4100-38f6-11e9-95bb-508906e4ad94.PNG)

**This is the attribute I'm talking about (segment):**
![attribute](https://user-images.githubusercontent.com/31554436/53346869-ae5dbd80-38f6-11e9-9d75-abca8753b329.PNG)

**This is what happens when I search for contacts with segment attribute value equal 1:**
![result](https://user-images.githubusercontent.com/31554436/53346947-d51bf400-38f6-11e9-8794-95f17993ba78.PNG)

**The same thing doesn't happen when I search for contacts using other attributes, for example, using birthday it works:**

![birthday](https://user-images.githubusercontent.com/31554436/53347495-f3ceba80-38f7-11e9-98de-bf6fab39b486.PNG)


> * tell the version of mautic you're using.

v2.15.0

**Comment by carloshmm** [comment]
No feedback, closing.
