### ISSUE TITLE
REST-API: Add multiple Segments to Contact (by create or edit)

### ISSUE THREAD

**Issue by christian-beckmann** [mautic/mautic#7263]
For https://developer.mautic.org/#add-contact-to-a-segment you can add one segment to a contact.

How to add multiple segments (ids or aliases array) at once by creating or editing a contact?
This could save a request, when creating a user from a formular with checkboxes for multiple segment.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by christian-beckmann** [comment]
This means you are not able to do it by your own?

**Comment by npracht** [comment]
I didn't test myself, as Ruth mentioned the 30th of July, did you have the opportunity to check if the problem persists on 3.1.0 ?
Thanks !

**Comment by christian-beckmann** [comment]
So this was a feature request not a bug.
