### ISSUE TITLE
mautic.ERROR: [MAIL ERROR] Unable to open file for reading

### ISSUE THREAD

**Issue by Githopp192** [mautic/mautic#7265]
### Steps to reproduce
 
1. i want to send emails with embedded images, not linked images.

2. Changed Email Settings -> "convert embedded images to Base64" ON

3. Then --> Channels --> emails --> Create new Template --> choose one template i.e. Oxygen;

4. Trying to send emails for testing purpose -->

[2019-02-19 18:36:57] mautic.ERROR: [MAIL ERROR] Unable to open file for reading [http://xxxxxxs:xxxxx/themes/oxygen/img/profile_pic.jpg] Log data

When i do the same with "Email Settings -> "convert embedded images to Base64" OFF; then the 
email can be sent properly

| Q   | A
| --- | ---
| Mautic version | 
latest: Pulling from docker.io/mautic/mautic
Digest: sha256:4712ecc650014cbdfb753ad7ba6bcfacb30b13c150d511d1adf681cb039054bb
Status: Image is up to date for docker.io/mautic/mautic:latest

| PHP version | PHP Version 7.1.26
Apache/2.4.25 (Debian)
 
### Log errors
[2019-02-19 18:36:57] mautic.ERROR: [MAIL ERROR] Unable to open file for reading [http://xxxxx:xxxxxx/themes/oxygen/img/profile_pic.jpg] Log data

**Comment by RCheesley** [comment]
@Githopp192 is this still an issue with 2.15.3?

**Comment by atulcj** [comment]
@RCheesley, I had encountered this bug earlier and hence had subscribed to the notifications on this issue. I had turned **OFF** "convert embedded images to Base64" as an interim fix. 

Today, after reading your comment I checked (on 2 separate installations of Mautic) and found that the issue seems to be resolved with **2.15.3**. I checked the mail source to be doubly sure and found the images to be Base64 encoded.

Just my 2 bits, if it helps!!

**Comment by RCheesley** [comment]
Ah fantastic, let's close this down as being resolved in 2.15.3 then - thanks for taking the time to report back @atulcj !

**Comment by fianbiasa** [comment]
it happend in Mautic 2.16.0

`[2020-06-15 15:46:40] mautic.ERROR: [MAIL ERROR] Unable to open file for reading [{tracking_pixel}] (send); rihlah******per@gmail.com {"exception":"[object] (Swift_IoException(code: 0): Unable to open file for reading [{tracking_pixel}] at /home/rihlahtu/email.ri******ahwisata.co.id/vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/FileByteStream.php:144)"} []`
