### ISSUE TITLE
Tracking URL not replaces correctly

### ISSUE THREAD

**Issue by ArtemDzhafarov** [mautic/mautic#7268]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Redirect URL replacing goes wrong
Currently using Mautic REST API to send emails to the contacts. In these emails, I need to build a link with the token, that I'm sending as a {token}. So the link looks like `<a href="https://{contactfield=loweredcompany}/endpoint-name/{token}">` . `{contactfield=loweredcompany}` represents some string "example.org" . This link acting absolutely fine when the "trackable URLs" feature in Email Settings is disabled. So that's how we getting correct `<a href="https://example.org/endpoint-name/token">`. When redirect trackable URL is enabled, I'm getting ASCII value of '{' and '}', so it breaks the link (it looks like `endpoint-name/%7Btoken%7D` ). Could you advise anything regarding this issue? I've been looking for some twig features like |join modifier to concatenate link but failed to find any information about it.

| Q   | A
| --- | ---
| Mautic version | v2.15.0
| PHP version | 7.1.22

### Steps to reproduce
1. Create Email with {token} as part of a=href link
2. Send email (POST api/emails/ID/contact/ID/send) when tracking urls enabled
` {
    "tokens": {
        "token":"sometoken"
    }
}`
 
### Log errors
no errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by ston3o** [comment]
I have this problem too when I try to put contactfield in tracking url..

@npracht, for get the token in your email, try this post data : `{ "tokens": { "{token}":"sometoken" } }`

**Comment by ston3o** [comment]
I have this problem too when I try to put contactfield in tracking url..

@ArtemDzhafarov , for get the token in your email, try this post data : `{ "tokens": { "{token}":"sometoken" } }`

**Comment by ArtemDzhafarov** [comment]
Any update on this issue? 

ston3o
Unfortunately, this solution not works for me and still token is not replaced in <a href="somestring/{token}">

**Comment by ayrad** [comment]
This is happening to us also. Is there any fix? (I'd like to check it out, but I am a bit busy these days).

The following link: http://whatever.eu/web/site/{token_countryisocode}/{token_language}
Gets tracked as: http://whatever.eu/web/site/%7Btoken_countryisocode%7D/%7Btoken_language%7D
Instead of (for example): http://whatever.eu/web/site/GB/en

We use custom EmailSubscriber (EmailEvents::EMAIL_ON_SEND & EmailEvents::EMAIL_ON_DISPLAY) to inject custom tokens. On display the link is OK because there is no trackable, but on send the issue above happens.

**Comment by nsaloski** [comment]
Hi, did anyone find a solution to this bug? 

Thanks

**Comment by RCheesley** [comment]
Hi folks, closing this in favour of #8446 which now has a PR to test (#7548 ) - please test the PR if you can @nsaloski @ayrad @ArtemDzhafarov @ston3o !
