### ISSUE TITLE
Support form submission result tokens in "send email" campaign action

### ISSUE THREAD

**Issue by vmtv** [mautic/mautic#7270]
Hey guys, i'd realized that there is no form submission result tokens in campaign "send email" action. Is it common behaviour or maybe some plugin can be installed?
Thanks)

**Comment by Khaled4** [comment]
what do you mean? can you include a screen shot of the problem?

**Comment by vmtv** [comment]
Please find the screenshots attached:
![edit_campaign_mautic_-_2019-02-21_17 29 05](https://user-images.githubusercontent.com/19403376/53180531-67be4980-35fe-11e9-8a0b-0246678c89c6.png)
![edit_email_-_test_mautic_-_2019-02-21_17 29 27](https://user-images.githubusercontent.com/19403376/53180557-7147b180-35fe-11e9-834f-2ede042be236.png)

**Comment by ArtemDzhafarov** [comment]
I may be wrong, but it looks like the thing you need is under this green "Action" tab as a decision 
![screen shot 2019-02-22 at 3 11 35 pm](https://user-images.githubusercontent.com/36130513/53244720-651e2b80-36b4-11e9-8568-b1b3aacdc71e.png)

**Comment by vmtv** [comment]
Same behaviour with a "Decision" added before "Send email" action.
No form field tokens on campaign level.

**Comment by npracht** [comment]
Hello @vmtv, you have 2 ways to do that:

1. Use form action "send email result"
2. Save those values in contact fields and use contact tokens.

Best!

**Comment by vmtv** [comment]
Hey @npracht 
1. Well, that could work for one or two forms.
2. But in case if you gonna have different forms and different fields then you will get a "tons" of contact fields + data will be saved in two places.
Regards.
