### ISSUE TITLE
[REST API] get file from form submissions

### ISSUE THREAD

**Issue by rokbani-wael** [mautic/mautic#7273]
Hi, I'm using the REST API to automatically get data in my system.
I wanted to know if there any ressource in the API to get the file submitted in forms by a contact ?

I can't find anything in the documentation.
Thank you

**Comment by npracht** [comment]
Did you try using routes like:
- https://developer.mautic.org/#list-form-submissions
- https://developer.mautic.org/#list-form-submissions-for-a-contact
- https://developer.mautic.org/#get-form-submission

?

**Comment by rokbani-wael** [comment]
Yes, I can get the file name linked to a specific form for a contact with these rssources. But I'm looking for a way to get the file content so I can save it elsewhere

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
