### ISSUE TITLE
AB test stats not available anymore

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#7276]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
After sending AB test emails, if you unpusblish emails, AB test Stats won't be available anymore

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create AB test emails
2. Send AB test
3. Check stats by clicking on AB tests stats
![image](https://user-images.githubusercontent.com/31535432/53250829-820a2d00-36bb-11e9-8572-99461feb07a6.png)
4. Now unpublish both all emails (parent + variation)
5. Click again on AB Test stats
6. See that stats are not available anymore
![image](https://user-images.githubusercontent.com/31535432/53250906-abc35400-36bb-11e9-87a4-5bd82d212aed.png)
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by colourfulowl** [comment]
Did Mautic produce any error logs?

**Comment by yanncharlou** [comment]
Same problem here. Stats not available even if mails published again.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by RCheesley** [comment]
Per @colourfulowl's comment in #9047 this persists in Mautic 3.
