### ISSUE TITLE
UX Improvement - Allow setting position of validation message below Submit button and make it default behaviour

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#7279]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
Today, when auto-integrating a form into a webpage with code provided within script tags, the validation message after submit is systematically on top of the form, which is not user friendly for for forms that have more than 2 or 3 fields because the user will not see the message unless she scrolls up.

I propose that we allow a setting to choose the position of the validation message with two options : top or bottom(default). IMO the default position should be bottom.

I personally see people resubmitting several times the form because they don't see the green validation message directly

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Would you be up for creating a PR to implement this if so?
