### ISSUE TITLE
[feature] Scheduled Send Time for List Email

### ISSUE THREAD

**Issue by MaxOnTheHill** [mautic/mautic#728]
Would be great to be able to set future send time for “Email Send” for a LIST email.

Basically this is to have the option to set a send date and time in advance 
ie. send on 5 August at 2pm
... this is just like pre-scheduling social posts, blog posts, etc ... but for our email campaigns ;)

**Comment by luxint66** [comment]
Great suggestion and it's suprising it's not already part of Mautic. 

Just testing it out now and so far, it's awesome! :)

Lux

**Comment by escopecz** [comment]
This seems to be duplicate of https://github.com/mautic/mautic/issues/574

**Comment by alanhartless** [comment]
Closing as a duplicate.

**Comment by rodrideme** [comment]
mautic.com is possible, mautic.org is not?
