### ISSUE TITLE
Form Autofill does not work on landing pages with custom domain

### ISSUE THREAD

**Issue by wucherpfennig** [mautic/mautic#7281]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 7
| Browser | 

### Steps to reproduce
1. Create a form with autofill
2. create a landing page including this form
3. test the landing page + form = works
4. if you use now a custom subdomain for the landing page
  eg. mautic.example.com/landing1 will be accessible via landing1.example.com/landing1
5. the autofill function for the form does not work anymore

Note: strangely the whole functionality (autofill form) works 100% if I include the form into a thirdparty page...
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by colourfulowl** [comment]
Are there any error logs produced on the subdomain page? Via the console editor.

**Comment by johbuch** [comment]
How did you integrate the form ? with the token or the script ?

**Comment by wucherpfennig** [comment]
With the token... The script breaks the whole builder

**Comment by npracht** [comment]
What is your theme ? Maybe a bug there ?

**Comment by wucherpfennig** [comment]
Independent of the theme. Currently we run the fresh themes.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.
