### ISSUE TITLE
Max admissible date is 2038-01-01 for date fields

### ISSUE THREAD

**Issue by lapoisse** [mautic/mautic#7289]
## Bug Description
As a user, I have some undefined date in the future that are used to filter contact. The max I can put on dates are between the 2038-01-01 and the 2038-12-31. I would prefer to put an arbitrary date like 9999-12-31, that let no possible ambiguous interpretation. 

By the way, this notation is currently well supported into my database used to populate Mautic. So it forced me to change to the admissible date. 
 
| Mautic version |  2.14.2

### Steps to reproduce
1. Create a custom datetime field.
2. Enter 9999-12-31> declared as a wrong data input. Even the calendar authorize to introduce a 2050 date.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!
