### ISSUE TITLE
The API route contacts/batch/edit does not include the duplicate removal but batch/new does/ no doc on it

### ISSUE THREAD

**Issue by lapoisse** [mautic/mautic#7290]
similar to #6210.

The route always create a new contact IF you do not provide an id. I was expected that the unicity of a contact will be respected (two contacts with the same email address merged). In fact, the route contacts/batch/new does the trick like a charm. 

Maybe something I do not understand. Bug or doc missing ?

| Mautic version | 2.14.2 

### Steps to reproduce
1. Create a request to create a contact on route PUT contacts/batch/edit.
2. Relaunch it.
Result : Two identical contacts are created.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by Ajtak** [comment]
This problem still not solved, same problem, in mautic version 3.3.3. Please fix it.
