### ISSUE TITLE
Mautic query cause mysql server to be totally locked

### ISSUE THREAD

**Issue by dsonnet** [mautic/mautic#7291]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Mautic is binging mysql server to its knees with extremely long queries.

The query start like this
////////////////////
SELECT (CASE WHEN m0_.id = 5 THEN 0 WHEN m0_.id =
////////////////////
Then there is a list of 302.668 when / then 
////////////////////
END) AS sclr_0, m0_.is_published AS is_published_1, m0_.date_added AS date_added_2, m0_.created_by AS created_by_3, m0_.created_by_user AS created_by_user_4, m0_.date_modified AS date_modified_5, m0_.modified_by AS modified_by_6, m0_.modified_by_user AS modified_by_user_7, m0_.checked_out AS checked_out_8, m0_.checked_out_by AS checked_out_by_9, m0_.checked_out_by_user AS checked_out_by_user_10, m0_.id AS id_11, m0_.points AS points_12, m0_.last_active AS last_active_13, m0_.internal AS internal_14, m0_.social_cache AS social_cache_15, m0_.date_identified AS date_identified_16, m0_.preferred_profile_image AS preferred_profile_image_17, m0_.title AS title_18, m0_.firstname AS firstname_19, m0_.lastname AS lastname_20, m0_.company AS company_21, m0_.position AS position_22, m0_.email AS email_23, m0_.phone AS phone_24, m0_.mobile AS mobile_25, m0_.address1 AS address1_26, m0_.address2 AS address2_27, m0_.city AS city_28, m0_.state AS state_29, m0_.zipcode AS zipcode_30, m0_.timezone AS timezone_31, m0_.country AS country_32, m1_.id AS id_33, m1_.ip_address AS ip_address_34, m1_.ip_details AS ip_details_35, m2_.is_published AS is_published_36, m2_.date_added AS date_added_37, m2_.created_by AS created_by_38, m2_.created_by_user AS created_by_user_39, m2_.date_modified AS date_modified_40, m2_.modified_by AS modified_by_41, m2_.modified_by_user AS modified_by_user_42, m2_.checked_out AS checked_out_43, m2_.checked_out_by AS checked_out_by_44, m2_.checked_out_by_user AS checked_out_by_user_45, m2_.id AS id_46, m2_.username AS username_47, m2_.password AS password_48, m2_.first_name AS first_name_49, m2_.last_name AS last_name_50, m2_.email AS email_51, m2_.position AS position_52, m2_.timezone AS timezone_53, m2_.locale AS locale_54, m2_.last_login AS last_login_55, m2_.last_active AS last_active_56, m2_.online_status AS online_status_57, m2_.preferences AS preferences_58, m2_.signature AS signature_59, m0_.owner_id AS owner_id_60, m0_.stage_id AS stage_id_61, m2_.role_id AS role_id_62 FROM mautic_leads m0_ LEFT JOIN mautic_lead_ips_xref m3_ ON m0_.id = m3_.lead_id LEFT JOIN mautic_ip_addresses m1_ ON m1_.id = m3_.ip_id LEFT JOIN mautic_users m2_ ON m0_.owner_id = m2_.id WHERE m0_.id IN (
//////////////
Then another list 300 thousand  ids

Any idea what is causing this query ? Can this be rewritten in a more scalable way ?

| Q   | A
| --- | ---
| Mautic version |  2.14.2
| PHP version |  7.0.33-0+deb9u1
| Browser | 

### Steps to reproduce
This must be trigered by cron since the query gets executed regularly
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
What about this fix? 

https://github.com/mautic/mautic/pull/6973

**Comment by dsonnet** [comment]
> What about this fix?
> 
> #6973

Thanks it seems related, will wait until this gets into a release
