### ISSUE TITLE
HTTP 500 error when previewin a form

### ISSUE THREAD

**Issue by loganaden** [mautic/mautic#7292]
## Bug Description
HTTP 500 error on form preview
| Q   | A
| --- | ---
| Mautic version | 
Latest stable
| PHP version | 
PHP 5
| Browser | 
Chrome
### Steps to reproduce
1. Go to a form
2. Select preview
 
### Log errors
![image](https://user-images.githubusercontent.com/1688420/53640144-cf9b1280-3c44-11e9-8792-ae827fe8b26c.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by johbuch** [comment]
check if the form has a theme assigned (in the edition)
If yes try to remove it and check the preview again

**Comment by npracht** [comment]
@loganaden any feedback ?
