### ISSUE TITLE
Unable to Upload SAML Files - Serialization of 'Symfony\Component\HttpFoundation\File\UploadedFile' is not allowed

### ISSUE THREAD

**Issue by joeyparis** [mautic/mautic#7294]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Uploading SAML configuration files leads to a **500 Internal Server Error - Serialization of 'Symfony\Component\HttpFoundation\File\UploadedFile' is not allowed**. This does seem to prevent the files from actually being saved, however Mautic still seems to think the files were saved because the "Remove" and "Download" links become present on the SAML configuration page. I am unsure if this file upload issue is specific to just the SAML configuration files or other file uploads as well.

I believe these two articles on the Symfony github are relevant:
https://github.com/symfony/symfony/issues/19572
https://github.com/symfony/symfony-docs/pull/8180

I am creating this issue on the Mautic github instead of the Symfony github because those two articles seem to indicate this isn't necessarily a bug with Symfony but instead a limitation of PHP and thus the change to account for this limitation would need to happen on the Mautic side.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1.19
| Browser | Google Chrome Version 72.0.3626.119 (Official Build) (64-bit)

### Steps to reproduce
1. Navigate to **Configuration -> User/Authentication Settings**
2. Upload the `metdata file`, `X.509 certificate`, and `Private key` files
3. Receive: **500 Internal Server Error - Serialization of 'Symfony\Component\HttpFoundation\File\UploadedFile' is not allowed**

 
### Log errors

When uploading the files:
```
500 Internal Server Error - Serialization of 'Symfony\Component\HttpFoundation\File\UploadedFile' is not allowed
```

After the file is uploaded but when Mautic thinks SAML is configured correctly:

Mautic Error Log:
```
[2019-03-01 20:35:48] mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "EntityDescriptor must have entityId set" at /Users/Joey/Sites/mautic/vendor/lightsaml/lightsaml/src/LightSaml/Store/EntityDescriptor/FixedEntityDescriptorStore.php line 34 {"exception":"[object] (InvalidArgumentException(code: 0): EntityDescriptor must have entityId set at /Users/Joey/Sites/mautic/vendor/lightsaml/lightsaml/src/LightSaml/Store/EntityDescriptor/FixedEntityDescriptorStore.php:34)"} []
```

PHP Error Log:
```
[Fri Mar 01 14:10:37.746940 2019] [php7:notice] [pid 15249] [client ::1:60405] PHP Deprecation - Symfony\\Component\\DependencyInjection\\Definition::setFactoryMethod(getManager) is deprecated since Symfony 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. - in file /Users/Joey/Sites/mautic/vendor/symfony/dependency-injection/Definition.php - at line 135, referer: http://localhost/mautic/mautic/index_dev.php/s/config/edit
[Fri Mar 01 14:10:37.747038 2019] [php7:notice] [pid 15249] [client ::1:60405] PHP Deprecation - The "factory-service" attribute of service "bazinga.oauth.entity_manager" in file "/Users/Joey/Sites/mautic/vendor/willdurand/oauth-server-bundle/DependencyInjection/../Resources/config/orm.xml" is deprecated since Symfony 2.6 and will be removed in 3.0. Use the "factory" element instead. - in file /Users/Joey/Sites/mautic/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php - at line 154, referer: http://localhost/mautic/mautic/index_dev.php/s/config/edit
[Fri Mar 01 14:10:37.747105 2019] [php7:notice] [pid 15249] [client ::1:60405] PHP Deprecation - Symfony\\Component\\DependencyInjection\\Definition::setFactoryService(doctrine) is deprecated since Symfony 2.6 and will be removed in 3.0. Use Definition::setFactory() instead. - in file /Users/Joey/Sites/mautic/vendor/symfony/dependency-injection/Definition.php - at line 206, referer: http://localhost/mautic/mautic/index_dev.php/s/config/edit
[Fri Mar 01 14:10:37.858531 2019] [php7:notice] [pid 15249] [client ::1:60405] PHP Deprecation - The alias option of the form.type_extension tag of service "mautic.form.extension.custom" is deprecated since Symfony 2.8 and will be removed in 3.0. Use the extended_type option instead. - in file /Users/Joey/Sites/mautic/vendor/symfony/framework-bundle/DependencyInjection/Compiler/FormPass.php - at line 67, referer: http://localhost/mautic/mautic/index_dev.php/s/config/edit
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by TonyBogdanov** [comment]
I am experiencing this bug as well on PHP 7.2.

@joeyparis Did you find a workaround for the time being? Does uploading the files manually help or are there any additional modifications that need to be done?

**Comment by joeyparis** [comment]
I have not found a consistent workaround as of yet. I tried uploading the 3 files several times and although I did get the error every time eventually the files did actually get uploaded. I'm really not sure what was different the times it succeeded but I have successfully repeated this a handful of times.

I haven't thought about manually uploading the files but I could potentially see that working! My understanding of Mautic's inner workings is fairly limited though.

**Comment by dolpox** [comment]
encode your XML file [here](https://www.samltool.com/base64.php) and paste the result in your config/local.php

**Comment by TonyBogdanov** [comment]
@dolpox Yes, that's the way to go as a workaround. To further clarify, base64-encoded values should be (in the config) under keys `saml_idp_metadata` (the XML metadata file), `saml_idp_own_certificate` (the x.509 certificate) and `saml_idp_own_private_key` (the private key).

**Comment by breimers** [comment]
I am having the same problem getting the file uploaded. 

`mautic.CRITICAL: Uncaught PHP Exception Exception: "Serialization of 'Symfony\Component\HttpFoundation\File\UploadedFile...`

This also prevents my Mautic app from defaulting to the SAML page, I assume because it doesn't know that it is configured. The upload box does show the 'remove' and 'download' options. But I get a `file not found` error when attempting to download.

I checked my _config/local.php_ and  `saml_idp_own_private_key` shows the correct base64 encoded file.

Really strange, I'll update this if I find a workaround.

**Comment by breimers** [comment]
Copying the file modified by @TonyBogdanov works great! 

Script to do it for you if you're lazy like me :)

https://github.com/breimers/Mautic-tweaks
