### ISSUE TITLE
add contact manuall as DNC does not work

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#7296]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When I want to set a contact as DNC manually it does not work.
By manually, I mean I go to contact sheet then on the preference, I uncheck "email" and save. But it does not save.

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 
| Browser | 

### Steps to reproduce
1. Go to a contact sheet
2. Click on preference
3. Uncheck email
![image](https://user-images.githubusercontent.com/31535432/53743134-6b718c00-3e9a-11e9-843d-8922caab582c.png)
4. Save
5. See that contact is not in "do not contact".
 
### Log errors
no logs

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Merged in 2.15.2
