### ISSUE TITLE
Customer Headers not reflecting in emails sent via Campaign Emails or Segment Emails

### ISSUE THREAD

**Issue by techzotezo** [mautic/mautic#7298]
Hi @npracht,
I have recently started using Mautic 2.14.2 on my own servers and testing it before sending bulk emails I found (apart from https://github.com/mautic/mautic/issues/6339) that my custom headers are not posted in emails, also surprisingly getting "Precedence: Bulk" as an additional header when sending emails using Campaign Emails or Segment Emails. Can anyone suggest a fix for this so that I can successfully deliver emails in users' inbox with custom headers?

**Comment by npracht** [comment]
From that simple message i have no idea of how we can help. We need to be able to reproduce that and there is no clear way to do so...

**Comment by techzotezo** [comment]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hi @npracht I have updated the details of the issue with how to reproduce.

No Custom Headers are found in emails. Out of my surprise getting "Precedence: Bulk" as an additional header when sending emails using Campaign Emails or Segment Emails. 
Header Precedence: Bulk is always taken as bulk emails sent to non-verified leads (purchased email data) by clients like Gmail, Outlook etc resulting in emails in Spam and eventually my sender id or ip will get the tag of SPAMMER!

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 7.0.32
|Email Transporter| Amazon SES

### Steps to reproduce
1. Add Custom Headers to Email Config or Individual Emails
2. Send Emails using Campaign or Segment
3. Look for headers in Delivered Emails
 
### Log errors
Nothing Found

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Closed in favor of #6339
