### ISSUE TITLE
Connection could not be established with smtp.mailgun.org (code #111)

### ISSUE THREAD

**Issue by alancvs** [mautic/mautic#7300]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | 7.1.26
| Browser | Chrome

### Steps to reproduce
1. Configure Email settings to send mail through Other SMTP Server
2.Host is smtp.mailgun.org
3. TLS and Login are the encryption type and authentication mode
4.Send Email
 
### Log errors

[2019-03-05 19:18:39] mautic.ERROR: [MAIL ERROR] Connection could not be established with host smtp.mailgun.org [Connection refused #111] Log data: ++ Starting Swift_Transport_EsmtpTransport !! Connection could not be established with host smtp.mailgun.org [Connection refused #111] (code: 0) (send); *email@domain.com* [] []

**Comment by npracht** [comment]
Hello @alancvs can you say what version of mautic you are using? If we ask for it in the template, it is because it is very useful ;)
