### ISSUE TITLE
Outlookplugin not working in Mautic 2.15

### ISSUE THREAD

**Issue by sensalot** [mautic/mautic#7302]
I have tried both the original Outlook plugin and the updated one of 2018. In Mautic Log I get these errors
Outlook integration not found
query variables are not found 
I have Mautic installed in a subdirectory, and it is on its own subdomain mautic.mydomain.com
I can see that the tracking pixel is added in Outlook. When visiting the url of the tracking pixel, a visit is registered, however a contact, including its emailaddress, is not created

Steps to reproduce.
Install the outlook plugin
setup the integration
send email with tracking enabled
View sourcecode of the send email
visit the url of the pixel / open email
check if contact is created in Mautic

Mautic 2.15
Outlook office 365 business (local client not the online version)

**Comment by andrekutianski** [comment]
all plugins of Mautic stopped working with the version 2.15.x

**Comment by sensalot** [comment]
2.15.1 still present

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!
