### ISSUE TITLE
Unable to create email

### ISSUE THREAD

**Issue by datmt** [mautic/mautic#7304]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.2.15 on Ubuntu 18.04
| Browser | Chrome, Firefox

### Steps to reproduce
1. Open Channels->Emails->New 
2. Select a template and click builder
I've created a video so you can see the problem easier:
https://youtu.be/-IbCuZmwke4
 
### Log errors
On chrome console:
https://mail.openexl.com/index.php/s/emails/builder/new_6a0b6eafacc6ae40aabba7a49fb808e11e1512d5?template=blank&_=1551885580858&mauticUserLastActive=1&mauticLastNotificationId= (500 Internal server error)

In mautic log:
[2019-03-06 15:21:50] mautic.CRITICAL: Uncaught PHP Exception Mautic\CoreBundle\Exception\BadC    onfigurationException: " is missing a required config file" at /var/www/mail.openexl.com/html/    app/bundles/CoreBundle/Templating/Helper/ThemeHelper.php line 71 {"exception":"[object] (Mauti    c\\CoreBundle\\Exception\\BadConfigurationException(code: 0):  is missing a required config fi    le at /var/www/mail.openexl.com/html/app/bundles/CoreBundle/Templating/Helper/ThemeHelper.php:    71)"} []

I run nginx and there is no error in nginx log

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by glaucomonteiro** [comment]
Same issue here, on a fresh install.

From what I have seen in the code, the problem is that the constructor is called on the mautic/themes folder before calling the mautic/themes/{my_theme}, but I dont know how or where to fix it

**Comment by glaucomonteiro** [comment]
Looking more into it, the nginx config had some problems, this problem is similar to #3942 and is also solved using the config posted there.

**Comment by datmt** [comment]
Thank you very much @glaucomonteiro. Changing nginx config according to the post you  gave works!

**Comment by virgilwashere** [comment]
> Looking more into it, the nginx config had some problems, this problem is similar to #3942 and is also solved using the config posted there.

@glaucomonteiro was it the regex used for `fastcgi_split_path_info`?

Also, I think you and @datmt are going to run into trouble with line 49 of that nginx config.  
Add `^` :

```nginx
# Add ^ to anchor regex
 location ~ ^/(addons|plugins)/ { deny all; }
```

Look [here for my nginx configs](http://bit.ly/nginx_fastcgi_buffers), which evolved from that original gist in #3942: http://bit.ly/nginx_fastcgi_buffers
