### ISSUE TITLE
Time/Day in graph of email template view does not account for timezone set in configuration

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#7306]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
I am on UTC+7h timezone. An email went out this morning at 6am.
When checking the contact profile, the email send time is 6am, which is correct.
But when I go to the template view of the email I sent, then the graph shows that the email was sent yesterday at 11pm
It's obviously unconsistent.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 

### Steps to reproduce:
1. Set timezone UTC+7
2. Send email at a time early in morning, before 7am, like 5 or 6am.
3. Check contact profile to see send time, and notice it's as expected
4. Check template email graph and see that the email appears as sent the previous day.

**Comment by npracht** [comment]
Must be fixed by https://github.com/mautic/mautic/pull/7752 and/or https://github.com/mautic/mautic/pull/7617. Please test and confirm !

**Comment by dennisameling** [comment]
#7617 is merged for the 2.16.1 release, please test if that release (scheduled for March 25) fixes the issue :)

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
