### ISSUE TITLE
Callback URL for OAUTH is required & validated, but not always relevant

### ISSUE THREAD

**Issue by cathalgarvey** [mautic/mautic#731]
I'm trying to authenticate with Python using OAuth1 so I can write a Mautic API in Py3. It asks me to define a callback URI, but I'm not going to be using one. I set it to `http://localhost` but when I tried to authorise it said it was invalid. I changed it to `http://localhost.me`, and it's still 'invalid'.

How do I side-step this, and can it be removed in future so that manual authentication with a terminal app can be done more easily?

**Comment by escopecz** [comment]
Callback URL is required for oAuth1 (http://oauth.net/core/1.0a/#rfc.section.6.1.1). The user will be redirected to callback URL (back to your app) after successful authentication with tokens you need to store in your app so you could do API requests.

**Comment by cathalgarvey** [comment]
But I'm the only user, and I am not running an "app", I'm running a terminal script. I'd like to follow [this workflow](https://requests-oauthlib.readthedocs.org/en/latest/oauth1_workflow.html) and just paste the callback URI's parameters into my script, which is why I set localhost, but the validation is preventing me from doing this manually.

**Comment by alanhartless** [comment]
Is the issue that the callback is validated when creating new consumer keys or when actually making the API call to authenticate?

**Comment by alanhartless** [comment]
Just following up on https://github.com/mautic/mautic/issues/731#issuecomment-141583261

Thanks!

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to re-open if you still experience the issue.

**Comment by kisaanOfficial** [comment]
Im using pycharm to connect to mautic using the api call, but since i don't have any call back URL, it gives me access denied. Can someone help?
