### ISSUE TITLE
HTML Email Issues Using Mail Chimp Code

### ISSUE THREAD

**Issue by corycast** [mautic/mautic#7314]
"Hello there,

Whenever we tried to update our customized code from mailchimp, mautic keeps giving back a problem with this message. The email template was the exact one we pasted in previously. How do we resolve this bug?

Message we get: "There are some form validation errors (name: A name is required., subject: A subject is required.) Please close the builder and fix them.""

[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | Newest Version
| PHP version | 7.1.26
| Browser | chrome

### Steps to reproduce
1.  create email in mail chimp and export code
2.  create code email in mautic and hit apply
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Is the validation message not clear to what you have to do?

1. Close the builder
2. Fill in the email name
3. Fill in the email subject
4. Save the email
