### ISSUE TITLE
Request: Enumerable / Comparable / Sortable Select List Items

### ISSUE THREAD

**Issue by cathalgarvey** [mautic/mautic#732]
Hi,
I'd like to make a smart list that can select people below a certain position in a select-list. 

e.g., for a community project, I have a Select List to describe the person's awareness of or involvement with the project:

    Unaware|Interested|Invited|Applied|Provisional|Member|Rejected|Declined

I'd like to select people who might be interested in joining in, so I'd like to say "involvement < Invited" and get anyone who's Unaware or Interested.

Similarly in this case, it'd be nice to have a filter for people who have previously either rejected involvement, or who were declined involvement, so I might filter out anyone whose involvement > Member.

I could hack this up with extra filters for each category/selection, but it's not clear what precedence boolean operators take in filtering, and I can't group selectors. Rather than make Select List items enumerable, it would also be possible to achieve this if you could use other lists as filters when making new lists; e.g. a list composed of `filtered people in list1 AND filtered people in list2`, or `filtered people in list1 NOT filtered people in list2`.

**Comment by alanhartless** [comment]
I think 1.2 solved this by adding an "includes" option for select lists.  If not, let us know what is missing and we'll reopen this issue.
