### ISSUE TITLE
Site goes down after clearing cache

### ISSUE THREAD

**Issue by xfumihiro** [mautic/mautic#7321]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Site goes down immediately after clearing cache

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.33-5+ubuntu18.04.1+deb.sury.org+1
| Browser | chrome 72.0.3626.121

### Steps to reproduce
1. php /var/www/mautic/app/console cache:clear
2. access the site
 
### Log errors
mautic.ERROR: InvalidArgumentException: The directory "/var/www/mautic/app/cache/prod/doctrine/cache/file_system" does not exist and could not be created. - in file /var/www/mautic/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php - at line 85

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by xfumihiro** [comment]
https://github.com/symfony/symfony/issues/28360

**Comment by escopecz** [comment]
Then do not run the clear cache command with the root user. It warms up cache as well so it will create all folders and files under the root user.

Use this instead: `rm -rf app/cache/*`

**Comment by aiac** [comment]
Same issue after runing console cache:clear inside docker container made from latest official Mautic image.
