### ISSUE TITLE
Granting all Contact permissions to a role produces incorrect total for granted permissions

### ISSUE THREAD

**Issue by ronindesign** [mautic/mautic#7322]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
On the _Permissions_ tab of the _Roles Editor_ view, the row labeled _Contact Permissions_ shows incorrect amount for _granted_ permissions when all permissions have been selected.

I've checked _Full_ in three of the four sections, those labeled _Contacts_, _Segments_, and _Imports_, but when checking _Manage_ in the third section labeled _Custom Fields_ the result is one extra added to the _granted" permissions count.

Specifically, when checking the _Manage_ permission, the granted / total count goes from _(15/16)_ to _(17/16)_.

I tried to track down the source of the issue, at first glance it seems `CoreBundle/Security/Permissions/AbstractPermissions::getPermissionRatio(array $data)` is not correctly counting the number of permissions for the _Custom Fields_ permission category.

| Q   | A
| --- | ---
| Mautic version | v2.15.0
| PHP version | v7.2.14
| Browser | Chrome, FireFox

### Steps to reproduce
1. Settings > Roles > New > _Permissions_ tab
2. Click _Contact Permissions_ and check the _Manage_ permission under _Custom Fields_ and click _Apply_ button to save.
3. Now see that the row labeled _Contact Permissions_ will have increased from _(0/16)_ to _(2/16)_.
4. Also, note that selecting _Full_ in other sections under _Contact Permissions_ results in _granted_ / _available_ ratio of _(17/16)_

<img width="980" alt="Screen Shot 2019-03-12 at 1 58 15 AM" src="https://user-images.githubusercontent.com/1414401/54187276-65ffdd00-446a-11e9-87b7-6ba3df82c166.png">
 
### Log errors

None.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!
