### ISSUE TITLE
Issue with re-sending email if initial email is not opened 

### ISSUE THREAD

**Issue by cellsmktng** [mautic/mautic#7323]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
We are using Mautic for an email drip campaign. The campaign is set up to send an email, and then to send another of the same email if the initial email is not opened after 3 days. However, we are finding that the initial email is sending and being read, and yet the second email is also sending within the same day. 

| Q   | A
| --- | ---
| Mautic version | 3.10.0-693.2.2.el7.x86_64
| PHP version | 7.1.8
| Browser | 

### Steps to reproduce
1. Create a campaign
2. Set-up an email to send immediately
3. Set-up a negative condition 'Opens email'
4. Set-up re-send email within 2 days if not opened
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Latest Mautic version is 2.15.0. What is the actual Mautic version? Do you set some specific time restriction in the actions/decisions? Like send only in working days or similar?

**Comment by cellsmktng** [comment]
It’s Mautic 2.12.2 

We don’t set any other restrictions, simply ask for it to send however many days later 

Michael

**Comment by escopecz** [comment]
Could you share a screen shot of your campaign tree graph?
