### ISSUE TITLE
Doctrine exception when long url

### ISSUE THREAD

**Issue by maxencedcx** [mautic/mautic#7324]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Related to #2187.
Sometimes it seems that the url string is quite long and this causes an DB exception. See logs attached. 
I guess the fix should be as simple as the one for #2187, which is turning the 'url' field into 'text' instead of 'string'.
(The reason I use such a long url is to prefill form inputs.)

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.0.29

### Log errors
`[2019-03-12 14:16:02] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'INSERT INTO ma_lead_utmtags (date_added, query, referer, remote_host, url, user_agent, utm_campaign, utm_content, utm_medium, utm_source, utm_term, lead_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["2019-03-12 13:16:02", "a:0:{}", null, null, "\/trends-2019---inscription?email=xxxxxxx.xxxxxxxxx%40xxxxxx-xxxxxxxx.xx&civilite=Monsieur&prenom=xxxxxxx&votre_nom=xxxxxxxxx&company=xxxxxx+xxxxxxxxxxxxx+xxxxxxxxx+xxxxxxxxx+xxxxxxxx+xxxxxxxxxx&utm_content=CTA-HEADER&utm_source=invitation&utm_medium=email&utm_campaign=trends2019", "Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0", "trends2019", "CTA-HEADER", "email", "invitation", null, 1432]:  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'INSERT INTO ma_lead_utmtags (date_added, query, referer, remote_host, url, user_agent, utm_campaign, utm_content, utm_medium, utm_source, utm_term, lead_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"2019-03-12 13:16:02\", \"a:0:{}\", null, null, \"\\/trends-2019---inscription?email=xxxxxxx.xxxxxxxxx%40xxxxxx-xxxxxxxx.xx&civilite=Monsieur&prenom=xxxxxxx&votre_nom=xxxxxxxxx&company=xxxxxx+xxxxxxxxxxxxx+xxxxxxxxx+xxxxxxxxx+xxxxxxxx+xxxxxxxxxx&utm_content=CTA-HEADER&utm_source=invitation&utm_medium=email&utm_campaign=trends2019\", \"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko\\/20100101 Firefox\\/65.0\", \"trends2019\", \"CTA-HEADER\", \"email\", \"invitation\", null, 1432]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1 at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1 at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1 at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by rikuto-bigarms** [comment]
Hi, I'm encountering the same issue. Here is my log.

```
[2019-04-22 10:53:44] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO ma_campaign_form_xref (campaign_id, form_id) VALUES (?, ?)' with params [2, 1]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-1' for key 'PRIMARY'" at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO ma_campaign_form_xref (campaign_id, form_id) VALUES (?, ?)' with params [2, 1]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-1' for key 'PRIMARY' at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-1' for key 'PRIMARY' at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-1' for key 'PRIMARY' at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
```

**Comment by zaharovrd** [comment]
Hi, I'm encountering the same issue. Here is my log.
`[2019-11-18 08:20:58] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO point_lead_action_log (date_fired, point_id, lead_id, ip_id) VALUES (?, ?, ?, ?)' with params ["2019-11-18 08:20:58", 3, 40403, 425214]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-40403' for key 'PRIMARY'" at /home/master/m.everest-dom.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO point_lead_action_log (date_fired, point_id, lead_id, ip_id) VALUES (?, ?, ?, ?)' with params [\"2019-11-18 08:20:58\", 3, 40403, 425214]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-40403' for key 'PRIMARY' at /home/master/m.everest-dom.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-40403' for key 'PRIMARY' at /home/master/m.everest-dom.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-40403' for key 'PRIMARY' at /home/master/m.everest-dom.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []`

**Comment by RCheesley** [comment]
Closing as an old issue referencing a solved issue, and without recent engagement.
