### ISSUE TITLE
irrational empty tag filtering in the contact and dynamic segments

### ISSUE THREAD

**Issue by lapoisse** [mautic/mautic#7325]
As a user, I want to be able to isolate contact without any tag. Maybe two bugs here : 
1- If I filter directly into contact with "!tag:%", only a contact created by the interface without tag appears; contact created without tag by the API, are never shown. 
2- Create a segment with a empty tag filter will never catch any contact, created by the API or manually. 

Mautic version 2.14.12 

### Steps to reproduce
1. Create a contact without tag manually.
2. Create a contact by the API.
3. Create a contact with a tag as a control set. 
3. Try to filter the contact on the contact page. 
4. Build a dynamic segment by filtering a empty tag.
5. As a result, no way to filter contact 1 and 2.
6. As a result, no way to get a full segment.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
