### ISSUE TITLE
Ability to set time of email which should go to each users local geographical timezone!

### ISSUE THREAD

**Issue by sayantannag** [mautic/mautic#7327]
As a user, I would like the ability to choose or set a time and the email should go to each individuals as per the uploaded contacts CSV file from Mautic, based on their geographic timezone. If I set 2PM and schedule. A German email ID should get it at 2PM their local time, a person from Australia should get the email at 2PM Australian timezone etc.

So, I just want that my all emails deliver based on time Zones is a feature that allows my emails to be delivered at the same exact time in all time zones. For example: if I set the email to be delivered for 11:45, the email will arrive at 11:45 of the local time in Tokyo, London, NY etc. Attached screenshot is my demo idea for the requirement.

![examples](https://user-images.githubusercontent.com/4394075/54257654-0991e000-4586-11e9-9967-6cda23f13f87.jpg)

**Comment by kuzmany** [comment]
Exists for campaigns https://github.com/mautic/mautic/pull/6520

**Comment by heathdutton** [comment]
We've been using this in production for some time within campaigns.

**Comment by sayantannag** [comment]
Hi Guys,

Any update regarding the same issue of mine?

**Comment by escopecz** [comment]
As others pointed out this already exists in Mautic. You don't have to import anything. Mautic knows the timezones form the contact's page hits. And the campaigns allow you will schedule emails to specific date and time. The emails will be scheduled for each contact based on their local time. If you wish for something different please describe it in more detail. 

And for the next time use the issue template, please.

**Comment by AbundanceHQ** [comment]
I have sent out an email (not via a campaign setup). The delivery was triggered at publishing time in the Mautic system timezone not based on the contact's preferred timezone.

So if I want to send out a weekly newsletter based on contact's timezone, do I have to set it up via Campaign?

**Comment by abdulhaq** [comment]
> the campaigns allow you will schedule emails to specific date and time. The emails will be scheduled for each contact based on their local time.

@escopecz are you sure about this statement? Because everywhere else I read that email are not sent according to contacts local time.

**Comment by escopecz** [comment]
Ah, 4 years ago. I'm not certain and I even think that I was wrong about that. We also have completely different way how we schedule email sends in our fork of Mautic then the community has so I should keep my mouth shut :)
