### ISSUE TITLE
Google Chrome Autofill

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#7329]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This is more of a UI bug then anything else. Since Googles update with it's autofill policy, whenever you go to selected a time to send an email, change a data filter etc etc within the Mautic backend, the autofill data annoying pops up blocking your ability to select the inputs (say the calender for the publishing time of emails). 

![mautic-autofill](https://user-images.githubusercontent.com/41902603/54299975-e4b46180-45b3-11e9-9045-03fd3393d18c.PNG)

I believe the fix is to add 'autocomplete="off"' to all of the major inputs, however, i'm not sure of an easy way to role this out across all the of the different views. Any ideas?

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1. Be signed into a google account. 
2. Click on any of the inputs.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by jmdunsing** [comment]
This is still a problem using version 4.4.2
