### ISSUE TITLE
Prevent events not coming from tracking library

### ISSUE THREAD

**Issue by zero-one-devteam** [mautic/mautic#7333]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When a user or bot accesses a non-mautic resource on the mautic server, mautic tracks a page hit in the database (contact ip is shown in "contacts"). This leads to a lot of garbage contacts when robots or spammers try to access non-available paths on the server. We are using RabbitMQ which logs all such events and Mautic imports them. As there is no filter in RabbitMQ we need a change to filter theses in Mautic (otherwise we can only use quite complex firewall rules ...)

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 7.2
| Browser | all

### Steps to reproduce
1. Open https://mymauticdomain/.well-known/security.txt (or any other non mautic url)
2. See tracked page hit in contact category
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
@zero-one-devteam is this still an issue for you? Appreciate it's a bit old, so let us know if it's still happening with the latest version of Mautic.
