### ISSUE TITLE
Include focus items in Mautic reports

### ISSUE THREAD

**Issue by Strubbel94** [mautic/mautic#7336]
Q | A
------------ | -------------
Mautic version | 2.15.0
Bug report? | No
Feature request? | Yes

Hey,
we're currently using multiple focus items in a campaign and we would like to monitor their performance. Mautic already tracks the clicks and views, but only shows them on the focus item detail page. However, focus items are not available as data source to use them in Mautic reports.

This would be a nice feature, because keeping track of all focus items at once is a huge timesaver instead of manually collecting the data from every single focus item.

**Comment by AlbanL74fr** [comment]
Completely agree, that would be really useful

**Comment by topicflux** [comment]
Any news? I think it is very important to have a report on the performance of focus items...

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/ideas as Github is for reporting bugs with Mautic whereas the ideas forum is where we discuss ideas for features and improvements :)
