### ISSUE TITLE
Errror 404 when click in link in email

### ISSUE THREAD

**Issue by Carlos-mb** [mautic/mautic#7337]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.15.0
| PHP version |  7.0.33
| Browser | Chrome, Edge (I gues.. any)

### Steps to reproduce
1. Add a link to a PDF in email
2. Clic in the link when receive the email
3. Get a 404 error
 
### Log errors

I have not seen error logs updated when this 404 error appears. 

There is nothing in App/logs

This is the last line in error_log

[18-Mar-2019 19:40:30 UTC] PHP Notice:  Undefined index: ct in /home/carlosm1/mautic.coachingrealista.com/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 452

The 404 Error is happening right now and it's not generating new lines in logs. 

The link doesn't work when clicking from web version view of the email. 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Carlos-mb** [comment]
I have seen than the PDF has the character "á".

It could be the problem. I can't check it because when I send a test email it doesn't include the tracking url.

**Comment by virgilwashere** [comment]
The `Undefined index: ct` error has gone away with this [patch](https://github.com/mautic/mautic/issues/7174#issuecomment-545464571)

Here's the code as a diff patch.

```diff
diff --git a/app/bundles/PageBundle/Controller/PublicController.php b/app/bundles/PageBundle/Controller/PublicController.php
index 350e8a9a4..bbe69d977 100644
--- a/app/bundles/PageBundle/Controller/PublicController.php
+++ b/app/bundles/PageBundle/Controller/PublicController.php
@@ -449,7 +449,11 @@ class PublicController extends CommonFormController
         $query = $this->request->query->all();

         // Unset the clickthrough from the URL query
-        $ct = $query['ct'];
+        if (isset($query['ct'])) {
+            $ct = $query['ct'];
+        } else {
+            $ct = null;
+        }
         unset($query['ct']);

         // Tak on anything left to the URL
```

```console
$ cat > /tmp/ct_unset.diff
<PASTE>
<CTRL D>
$ cd /var/www/mautic
$ git apply -v /tmp/ct_unset.diff
Checking patch app/bundles/PageBundle/Controller/PublicController.php...
Applied patch app/bundles/PageBundle/Controller/PublicController.php cleanly.
```


And a new email (also had a new asset link, so I cannot be sure which bit fixed it) has working links in it after this patch.


Virgil

**Comment by npracht** [comment]
@Carlos-mb can you test https://github.com/mautic/mautic/pull/8253 ?
