### ISSUE TITLE
Campaign Action Webhooks removing POST properties with duplicated values.

### ISSUE THREAD

**Issue by carlos-moreira** [mautic/mautic#7341]
This is a very strange bug:

If you create a webhook with two properties, for example:

```
POST http://domain-example.com/
propertyA: 1
propertyB: 1
```

And save, only one of these properties will keep saved, one will disappear.

But if you save the same POST request with different values, it will work, for example, this request saves without problems:

```
POST http://domain-example.com/
propertyA: 1
propertyB: 2
```

I'm using Mautic v2.15.0. This is a very simple bug to test out, can someone here please confirm?

--EDIT
Video showing the problem:

[mautic_webhook_bug.zip](https://github.com/mautic/mautic/files/2989424/mautic_webhook_bug.zip)

**Comment by AlbanL74fr** [comment]
I have the same issue

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
