### ISSUE TITLE
Focus items - Customisation

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#7342]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have implemented some focus items into my wordpress website. But, i'm having some conflicts with the design of my site and focus items. Where can i update the CSS that the focus items output in the iframe? I can't for the life of me find it >_< 

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by AlbanL74fr** [comment]
Need more informations about what type of focus you used, the code sample if possible, and the nature of the conflict

**Comment by colourfulowl** [comment]
@AlbanL74fr I'm using the Modal version of the Focus Item. What i'm trying to update is the CSS that is embedded into the head of the iframe. I'm basically wanting to update some of the existing stuff in there, as well as add some new stuff. I just can't find in mautic's backend code where this style coding is being generated from :/

![focus-iframe](https://user-images.githubusercontent.com/41902603/54997389-82039280-4fc3-11e9-89c0-2b78f801e5da.PNG)

![focus-iframe2](https://user-images.githubusercontent.com/41902603/54997398-86c84680-4fc3-11e9-8a4e-9e30ecf30e14.PNG)

**Comment by AlbanL74fr** [comment]
I ever encounter a similar case where I needed to change the default width of the focus container.
I was using notification focus but what I did was to use code editor for the content of the focus and add on top css in <style> tags, call for the css class, and use !important marker... have you tried?

**Comment by RCheesley** [comment]
Please post this on the forums as it is a support request rather than a bug. https://forum.mautic.org.
