### ISSUE TITLE
Contacts page broken after searching for contacts with a specific tag

### ISSUE THREAD

**Issue by quintmouthaan** [mautic/mautic#7348]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.15.0
| PHP version | 
| Browser | Chrome Version 72.0.3626.121

### Steps to reproduce
1. Search for specific tag in Contacts
2. Navigate to some other screens
3. Reopen the contacts page
4. The error screen appears because a 500 internal server error occurred

I navigated to some other screens in between searching with a specific tag and reopening the contacts page. Restarting the server does not resolve the problem. There was already something strange happening before I got the 500 error as I can see that around 30 contacts have the tag that I'm looking for, but only 11 appeared in the search results when the contacts page was still working. Seemed that the search was already not working properly. Might be that there was already something wrong with the indexes before I got the internal server error.

### Log errors
The following error is reported in the logs:
mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Query\QueryException: "The given alias 'tag' is not unique in FROM
 and JOIN clause table. The currently registered aliases are: l, u, xtag, tag." at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Do
ctrine/DBAL/Query/QueryException.php line 50 {"exception":"[object] (Doctrine\\DBAL\\Query\\QueryException(code: 0): The given alias 'tag' is 
not unique in FROM and JOIN clause table. The currently registered aliases are: l, u, xtag, tag. at /opt/bitnami/apps/mautic/htdocs/vendor/doc
trine/dbal/lib/Doctrine/DBAL/Query/QueryException.php:50)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by quintmouthaan** [comment]
Update: opening the contact page in another browser (Safari) works without errors. The tag search still returns a smaller set of contacts than expected though

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
