### ISSUE TITLE
Gmail authentication in "Mail Settings" fails due to Google error 535-5.7.8

### ISSUE THREAD

**Issue by vmajor** [mautic/mautic#735]
When performing "Test connection" within Mautic configuration, a large message in red text appears with the following as the opening statements:

`Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/answer/14257... `

additionally I receive an email from Google with the following heading and message: 

"Google Account: sign-in attempt blocked

We recently blocked a sign-in attempt to your Google Account [my.account@gmail.com]. 

Sign in attempt details
Date & Time: Saturday, August 1, 2:35 PM GMT+8 
Location: My City, My Country

If this wasn't you
Please review your Account Activity page at https://security.google.com/settings/security/activity to see if anything looks suspicious. Whoever tried to sign in to your account knows your password; we recommend that you change it right away. 

If this was you
You can switch to an app made by Google such as Gmail to access your account (recommended) or change your settings at https://www.google.com/settings/security/lesssecureapps so that your account is no longer protected by modern security standards. 

To learn more, see https://support.google.com/accounts/answer/6010255. 

Sincerely,
The Google Accounts team"

V.

**Comment by alanhartless** [comment]
To login with standard SMTP, you have to enable "less secure apps" in your Google account. There's nothing we can do about this. https://www.google.com/settings/security/lesssecureapps
