### ISSUE TITLE
(Enhancement) Email A/B testing : Show statistical relevancy as option that can be set (with default 95%) when starting an experiment, to declare a winner

### ISSUE THREAD

**Issue by AlbanL74fr** [mautic/mautic#7351]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | X

## Description:
Today, it's not really transparent how Mautic declares a winner when an A/B test is conducted.

Having more transparency on that and allowing user to select a relevancy threshold would help adopt this feature with more confidence that it's working properly.

**Comment by npracht** [comment]
Closing this in favor of https://github.com/mautic/mautic/issues/1752 where there is already a long debate.
