### ISSUE TITLE
mautic.NOTICE: Exception: DateTime::__construct(): Failed to parse time string

### ISSUE THREAD

**Issue by carloshmm** [mautic/mautic#7352]
I'm getting this error message after upgrading to Mautic version 2.15.1:

`[2019-03-26 14:15:02] mautic.NOTICE: Exception: DateTime::__construct(): Failed to parse time string (aniversário) at position 0 (a): The timezone could not be found in the database (uncaught exception) at /opt/mautic-2.15.1/app/bundles/CoreBundle/Helper/DateTimeHelper.php line 89 while running console command `mautic:segments:update` [] []`

I don't know if this is related: https://github.com/mautic/mautic/pull/6993

~It seems not to have any side effect on my environment~ but I'll register this issue anyway.

I'm using PHP 7.0.33.

-----
EDIT

Actually this is breaking the cronjob 'mautic:segments:update' exactly when it updates a segment that deals with birthday.

-----
EDIT 2

To temporarily fix this problem I disabled my anniversary segment (and consequently my anniversary campaign). Is someone else getting this problem?

-----
EDIT 3

As I needed this campaign working I just downgraded my Mautic to the previous stable version 2.15.0. All is working properly again. So my guess is that this problem appeared on the version 2.15.1.

**Comment by npracht** [comment]
Your string should be in english instead of `aniversário` (portugal ?). Can you try and confirm ?

**Comment by carloshmm** [comment]
@npracht 
I can't update to version 2.15.1 again right now because just yesterday I put Mautic in production usage on my company. What we are going to do here is to create a development Mautic environment where we will try out upgrades and other tests, when we get this done I will test your suggestion again.

What I can tell you know is that using localized names, Brazilian Portuguese in this case, is working without any issues on version 2.15.0.

**Comment by npracht** [comment]
Let me know when you have done the test in english with 2.15.1 ;)

**Comment by carloshmm** [comment]
> Let me know when you have done the test in english with 2.15.1 ;)

I just tested it on a development Mautic environment and using the string "birthday" in place of "aniversário" solved the problem. I just upgraded to version 2.15.1 on production now :)

P.S.: Why does the localized name for birthday stopped working on this version? Is it a problem?

**Comment by npracht** [comment]
Code has been changed. That's why :)
