### ISSUE TITLE
Segment - "Public Segment" should be set as false by default

### ISSUE THREAD

**Issue by AlbanL74fr** [mautic/mautic#7354]
## Bug Description
When creating a new segment, the default setting of "Public Segment" is true which, IMO is not appropriate. 
Have such default behaviour can mislead Mautic users to have undesired segments to be visible on preference center page, if they don't pay attention.
My suggestion is to have default setting to false instead.

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 
| Browser |

**Comment by npracht** [comment]
In 2.15.0 [this PR](https://github.com/mautic/mautic/pull/6410) changes the behavior --> public segment is now different from available in preference center.
Please use this PR or upgrade your mautic version.

**Comment by namratasaun** [comment]
It still is true. what is the solution?
