### ISSUE TITLE
Forms don't work anymore after 2.15.1

### ISSUE THREAD

**Issue by leadsmania** [mautic/mautic#7356]
I just upgraded to 2.15.1.

The forms do not integrate with mautic anymore. Im using the native form created in mautic and just pasting the js code into a page where the site has mautic tracking code installed.

Ive made several test both using manual and automatic code, I also created a new form, and tested with and without validation to see if it was validation related according to the error below.

The repeated error in mautic is this:

`[2019-03-27 12:41:30] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Validator\Exception\UnexpectedTypeException: "Expected argument of type "string", "array" given" at public_html/alerts/vendor/symfony/validator/Constraints/LengthValidator.php line 38 {"exception":"[object] (Symfony\\Component\\Validator\\Exception\\UnexpectedTypeException(code: 0): Expected argument of type \"string\", \"array\" given at /public_html/alerts/vendor/symfony/validator/Constraints/LengthValidator.php:38)"} []`

**Comment by leadsmania** [comment]
I had an example url with the new form on it, but I had to restore from backup because this is a live site so I could not stay on a non working version. I know there is not much information here. Please believe I have performed many tests to try to get the form to work. Later today when I have time I will clone the droplet and provide all of the information I can. Im sure this is effecting several other people as well.

**Comment by vivasc2017** [comment]
We are having same issue after migration. Right now trying to revert it to 2.15

**Comment by leadsmania** [comment]
While Im here is there a more solid form integration method Im not sure of? Ive tried using thrive leads and other 3rd party solutions that use oauth authorization but with the changes in the oauth code in mautic those have stopped working. Thats when I decided to use mautics native form thinking there will be no way it would not integrate. Can anybody suggest a method thats mautic update proof?

**Comment by fastflowapps** [comment]
same problem here, although we had the same issue in 2.15 disabling the mautic-form-src.js

**Comment by fastflowapps** [comment]
I've reverted back to 2.15 with the form js files disabled. I have no idea what will be affected from this but at least my forms are working, but I really would like to have this working properly

**Comment by fastflowapps** [comment]
I have solved the problem within 2.15 It was an issue with X-Frame Options

https://github.com/mautic/mautic/issues/4005

My fix was as simple as disabling Clickjacking in Runcloud

https://www.elftronix.com/runcloud-tip-how-to-configure-x-frame-options-sameorigin/

This may help for others using 2.15....but I have not yet updated to 2.15.1 again as the issues there seemed much more complex

**Comment by leadsmania** [comment]
You know Ive been researching this issue looking for solutions. There is no plugin that integrates with mautic anymore after version 2.14 (after they made the change to the oauth code). Not thrive leads, WP Mautic Form Integrator, CF7 Mautic Extension, AR hive which claims to integrate wp cf7 to mautic, and NINJA FORMS PLUGIN a plugin that claims to integrate ninja forms to mautic. I just spoke with them on chat and they said only mautic 2.14 works with their plugin, nothing else. I personally have tested every single one of these and I can tell you none of them work. I've also was not successful getting zapier to work with my mautic, maybe Im doing something wrong but I have a feeling Im not.

The only option is using mautics native forms which is broken if you upgrade to mautic 2.15.1. So this is kind of a big deal. If you're somebody using mautic. No matter what you do, you have no way of getting contacts into mautic 2.15.1 using mautic's own form functionality.

Am I missing something here? Does anybody else have this problem or has a workaround for it? There is nothing unless you have someone develop it for you.

**Comment by kuzmany** [comment]
https://github.com/mautic/mautic/issues/7344#issuecomment-477668898

**Comment by fastflowapps** [comment]
@leadsmania what kind of integrations are you needing? We will shortly be looking at a Mautic plugin for our WordPress marketing integration system @ https://fastflow.io so that we can add users who get tagged in WordPress straight into Mautic. I'm interested to know what requirements other people have so we could look at covering those too

**Comment by leadsmania** [comment]
@fastflowapps all I need is the form to work regularly, when somebody fills it out, the contact is created in mautic. Whether thats through a third party plugin that uses oauth, or through mautics own methods for adding the form to the site. For me both methods break after any kind of mautic update. Sometimes you don't find out for days and are losing people, they fill out the form and nothing happens. Again Ive tried everything thats out there. 

Right now Im using mautics own methods, the js code in the page and styling it myself. Im embedding the the code in a popup but there is also issues with the mautics code itself. When you submit it creates an undefined message in the button - https://take.ms/j6niw. When I inspect it, I see an jquery error - https://take.ms/wXd5a

I had somebody else look at the error and they said it was something on mautic end, but I am not sure. 

I would take any method that allows me to make a nice looking, good working form on my site, that when somebody fills out they become a contact in mautic, just like mautics form is supposed to work or other plugins claim to do. Also something that doesn't break after updates.

**Comment by amasselin** [comment]
We have the same error that @leadsmania after upgrade to 2.15.1, but on a mautic landing page that embbed a mautic form. All our forms are break, even those who have only one email field.

`[2019-03-31 11:58:11] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Validator\Exception\UnexpectedTypeException: "Expected argument of type "string", "array" given" at /opt/bitnami/apps/mautic/htdocs/vendor/symfony/validator/Constraints/LengthValidator.php line 38 {"exception":"[object] (Symfony\\Component\\Validator\\Exception\\UnexpectedTypeException(code: 0): Expected argument of type \"string\", \"array\" given at /opt/bitnami/apps/mautic/htdocs/vendor/symfony/validator/Constraints/LengthValidator.php:38)"} []`

**Comment by amasselin** [comment]
I think it's a problem associate to contact update or create in the form process. If field isn't associate to a contact field, there is no  mautic.CRITICAL error.

**Comment by amasselin** [comment]
#7372

**Comment by npracht** [comment]
Closed in favor of #7344

**Comment by leadsmania** [comment]
Has anybody tested the zapier / mautic integration? I've been trying every way possible to take a form submission and create a contact in mautic using the zapier webhook mautic method but it does not create contacts at all. Is this method abandoned?

**Comment by cristianethiel** [comment]
Has anybody found out a solution for sending form in version 2.15.1?

**Comment by imankitshah** [comment]
Hi Guys,
If the error code 500 then this small video might help you solve the problem.

[Cannot Create a New Form in Mautic | Problem Solved](https://youtu.be/L0aY5PP1WAk)
