### ISSUE TITLE
Global Unsubscribe option missing in  2.15.1 version.

### ISSUE THREAD

**Issue by Bibhudatta-Sahoo-ASMB** [mautic/mautic#7359]
Newest release 2.15.1 fixed some issues with Preferences Center (Unsubscribe Page) however we are now missing the Global Unsubscribe option "I would like to receive emails from XX" with a tick box - SEPARATE from the My Segments list below (it was formerly at the top).
 
Please refer the Screen shot below
[http://prntscr.com/n4gxek](url)

**Comment by npracht** [comment]
Hi @Bibhudatta-Sahoo-ASMB please fulfill the issue template with all the missing informations. Thanks.

**Comment by escopecz** [comment]
Please create new issue where you'll follow the issue template, post screen shots of before and after. Use the drag&drop feature of this issue tracker. The link to your screenshot is wrong.
