### ISSUE TITLE
Unable to Setup Gmail / Any Smtp

### ISSUE THREAD

**Issue by Dipranil** [mautic/mautic#7363]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I tried to setup Gmail and other SMTP, but every time getting an error while submiting test connection after username and paasword fillup.

| Q   | A
| --- | ---
| Mautic version | 2.5.0
| PHP version | 7.0.33
| Browser | 

**Error Response:**
Connection could not be established with host smtp.gmail.com [Network is unreachable #101] Log data: ++ Starting Swift_SmtpTransport !! Connection could not be established with host smtp.gmail.com [Network is unreachable #101] (code: 0)
++ Starting Swift_SmtpTransport !! Connection could not be established with host smtp.gmail.com [Network is unreachable #101] (code: 0)

 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by amankapoor** [comment]
Try changing mode to TLS if its SSL.

Play around with SSL, TLS and None and Cram_MD5, Plain etc.

I had a similar situation and it was fixed when I changed to TLS from SSL.

**Comment by Dipranil** [comment]
Getting This error if i set TLS with

**Comment by RCheesley** [comment]
Closing this issue as it's most likely due to hosting provider restrictions (ask them about SMTP port blocking) or username/password failures.

**Comment by KiransHub** [comment]
I'm currently running this inside of a container on my localhost machine and I'm seeing the same issue. Can we please have a bit more guidance on how to get this working?

**Comment by RCheesley** [comment]
Hi @KiransHub, according to the comments, you probably need to expose the ports you require in the container. Please move this to https://forum.mautic.org as that's where we deal with support requests, Github is for issues with Mautic rather than how to configure it :)

**Comment by aiac** [comment]
Hello! It took couple of hours to investigate that, but finally I found issue. In my case it was TLS version constant with PHP 7.1. It changed on versions 5.6 above.

Try changing `STREAM_CRYPTO_METHOD_TLS_CLIENT` to `STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT` (or other version) in _/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php_

_Originally posted by @aiac in https://github.com/mautic/docker-mautic/issues/59#issuecomment-625853815_
