### ISSUE TITLE
Report Numeric Links Error 0.0.0.xx

### ISSUE THREAD

**Issue by TR687** [mautic/mautic#7366]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When clicking on the numeric value link in a report - e.g. Reports/All Emails/Most emails read (box on report dashboard)  we receive the following page error:  This site can’t be reached http://0.0.0.xx/ is unreachable.   xx = the number in the 'Opens' column. See attached screenshot

| Q   | A
| --- | ---
| Mautic version | V.2.15.0
| PHP version | 7.0.33
| Browser | Any Browser - currently testing on Chrome Version 73.0.3683.86 (Official Build) (64-bit)

### Steps to reproduce
1. Click Reports
2. Click All Emails report
3. Scroll to 'Most Emails Read' widget (or any showing title and number of contacts)
4. Click on number in right column (opens, sent, ratio, etc.)

URL = 0.0.0.xx   (where xx is the number in the column)  See attached screenshot - red outline with arrow

![Mautic Error](https://user-images.githubusercontent.com/48954574/55240560-0870dc00-5231-11e9-96c6-8126c7477534.png)

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Reproduced. It should show a link like `url/s/contacts?search=email_read%3A57` where 57 is the email ID.
Only issue with that simple query is that it does not take into account the timeframe of the report in the contacts list view.

**Comment by Woolgoose** [comment]
Can confirm the issue on Mautic 2.15.1, PHP version 7.2.20

**Comment by RCheesley** [comment]
Closing as these fields are no longer linked so this is not relevant any more.
