### ISSUE TITLE
Error inserting page hit because url title is too long

### ISSUE THREAD

**Issue by iurisilvio** [mautic/mautic#7367]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Column `hit.url_title` is a string (`varchar(255)`), but title is unlimited.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2
| Browser | 

### Steps to reproduce
1. Add mautic tracking to a page with long title
2. Visit it
 
### Log errors

> (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'UPDATE page_hits SET country = ?, region = ?, city = ?, isp = ?, organization = ?, referer = ?, url = ?, url_title = ?, user_agent = ?, page_language = ?, browser_languages = ?, lead_id = ? WHERE id = ?' with params [\"Brazil\", \"Bahia\", \"Salvador\", \"\", \"\", \"www.example.com\", \"https:\\/\\/www.example.com\", \"Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title Long Title\", \"Mozilla\\/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Version\\/12.0.2 Safari\\/605.1.15\", \"pt-BR\", \"a:1:{i:0;s:5:\\\"pt-br\\\";}\", 117777, 278905]:\n\nSQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url_title' at row 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url_title' at row 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url_title' at row 1 at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
If anyone will have free 10 minutes, this needs migration similar to https://github.com/mautic/mautic/pull/7084/files#diff-81db40d632306b1192d8ae153669f126R18

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Comment by iurisilvio** [comment]
This is still a minor bug.
