### ISSUE TITLE
Won't save Configuration Changes - Please Wait...

### ISSUE THREAD

**Issue by mediamix-NJ** [mautic/mautic#7368]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I host my own sites on an Ubuntu 16.04 server.
I have 3 websites with the latest version of Mautic - V 2.15.1 - running on each. All worked until I needed to change the IP address on the server.
Now 2 of the Mautic installs still work but the third has an issue. When I enter Configuration and then click either apply or Save and exit, I get Please Wait…
Nothing happens until I click the back button on the browser.
Changes are not saved. On the working Mautics, when I exit and save a box appears at the bottom of the browser that displays “waiting for http://www.xxxxxx.com ”On the non-working Mautic, that box does not appear. Any idea how to fix this?

Thanks

| Q   | A
| --- | ---
| Mautic version 2.15.1 | 
| PHP version | 
| Chrome | 

### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hello @mediamix-NJ. Did you clear your cache ?
Also, are your CORS enabled ?

**Comment by mediamix-NJ** [comment]
Thanks for your reply.  Yes, I did clear the cache.  I am not familiar with enabling CORS.  Might I asks how would I check on an Ubuntu 16.04 server running ISP Config?

Given that Mautic is working properly on 2 other domains being hosted on the same server, can I assume that CORS is enabled?

**Comment by npracht** [comment]
it is on your mautic interface > configuration > a little bottom there.

**Comment by mediamix-NJ** [comment]
CORS Setting is set to no on the Mautic installation where I can't save the configuration settings and one of the working Mautic installations.  The other working Mautic installation has CORS set to Yes

**Comment by npracht** [comment]
Do you have a message in your logs ?

**Comment by mediamix-NJ** [comment]
I opened config and attempted to apply and save.  I get the "Please wait..." I clicked the back button on the browser to go back to Mautic.  There is no log entry when I go to System Info - Log

**Comment by escopecz** [comment]
Please check https://www.mautic.org/docs/en/tips/troubleshooting.html on on what else to try. It usually is a timeout limit. But the error must be recorded somewhere.

**Comment by mediamix-NJ** [comment]
Found the problem.  It had to do with Wordfence.  Once disabled on the site all works fine.

**Comment by escopecz** [comment]
Thanks for the update!

**Comment by marioguima** [comment]
> Found the problem. It had to do with Wordfence. Once disabled on the site all works fine.

mediamix-NJ your comment saved me hours of work

and thinking of helping ...
I went to research how to keep wordfence running in parallel to mautic ...

I found an elegant way to do this

just set wordfence in learning mode
then it will log the calls to the urls whitelist

ps. I navigated the configuration, even without modifying anything, and saved a few times for him to register the requests

then I enabled wordfence and everything worked normally

**Comment by altomarketing** [comment]
same to me in other panel, Mod_security was blocking.. fixed.

**Comment by Doom666** [comment]
Im having the same problem and I got no Idea what Mod_security or wordfence is, I have it installed in bluehost if that is of any help
does anyone knows how to fix this?

**Comment by Doom666** [comment]
I dont seem to have mod_security in my CPanel nor wordfence in any of the wp pages I have...
