### ISSUE TITLE
Mautic bounce

### ISSUE THREAD

**Issue by cellsmktng** [mautic/mautic#7369]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
About 6% of our contacts are returning a 'bounced email' error, despite the fact that we know their emails work. This has been going on for some time and is an issue because all contacts are listed as 'do not contact'. 

| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 7.1.8
| Browser | All browsers (mainly Chrome)

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @cellsmktng i don't think this is a bug.

1. They are really bounce at a certain moment
2. Your email router has an issue
3. Your configuration is wrong

How do you send your emails ? How can we reproduce.

**Comment by cellsmktng** [comment]
Hi @npracht 

This is definitely a bug - it has only been happening recently, and only to certain contacts who we know the emails already work.

Is there a way to turn off the auto do not contact when an email bounces?

**Comment by npracht** [comment]
This is not automatic, this is depending on your email router.
Could you please answer my questions? Otherwise i cannot help more.
Thanks

**Comment by escopecz** [comment]
There is no point of having this issue when it's lacking the details. We cannot do anything without it.
