### ISSUE TITLE
ARUBA email setup

### ISSUE THREAD

**Issue by Arkango** [mautic/mautic#7371]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | latest
| PHP version | 7.2
| Browser | firefox/chrome

### Steps to reproduce
1. try to configure email following this link https://guide.hosting.aruba.it/email-aruba/configurazione-email-aruba/utilizzo-email-aruba-client-posta-aruba.aspx
2. apply changes
3. click test connection: success!
4. send test email: success!
5. mail never recieved 
 
###Debug 
How i can debug that ?
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @Arkango this is an issue with Aruba, not mautic. Please contact their support.
Are you sure you validated the usage of the domain name bu this router ? Most of the time you need to configure your DNS to authorize the router to send emails on your behalf. If this is not done, the router blocks the emails.
