### ISSUE TITLE
Configuration tab 504 error

### ISSUE THREAD

**Issue by Arkango** [mautic/mautic#7374]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 7.1
| Browser | chrome/firefox

### Steps to reproduce
1. login to mautic
2. go to tab configuration
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )
![Screenshot from 2019-04-01 11-41-42](https://user-images.githubusercontent.com/23188987/55318505-3c3b4400-5473-11e9-801c-0193ab1e62ea.png)

**Comment by npracht** [comment]
Hi @Arkango this is a server configuration issue i guess. This is not happening on my side.
What can you find on your mautic logs or server logs ?
Did you clear your cache ?

**Comment by Arkango** [comment]
Ok I'll send the logs, I cleared the cache. But I solved only editing the local.php file, I delete some lines of config and it charge correctly. I think was the timeout of Php the problem but I cannot modify that

**Comment by npracht** [comment]
You can configure your server for a longer time before timeout.
So issue is solved?

**Comment by Arkango** [comment]
Yes Is solved but I don't know if the problem Is that

**Comment by HN-PRO** [comment]
> Ok I'll send the logs, I cleared the cache. But I solved only editing the local.php file, I delete some lines of config and it charge correctly. I think was the timeout of Php the problem but I cannot modify that

I have the same problem, can you share which configurations need to be removed?

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
