### ISSUE TITLE
How get a count times user opened email by date interval?

### ISSUE THREAD

**Issue by bookin** [mautic/mautic#7378]
For example I need information how many time user opened email today, here some problem, user could open emails yesterday or before and in the `open_count` I see only sum of opens, in the `date_read` - first time when it was read, `last_opened` - last date, but I don't see way how to get information for any day or date range.

In the code I didn't find where it could be. Only `open_count`
any idea how to do it?

**Comment by npracht** [comment]
Hi @bookin please chat on Slack or Discord.
GitHub is used to report bugs.

Thanks.
