### ISSUE TITLE
The page tag title began to be recorded in transliteration

### ISSUE THREAD

**Issue by directpromo** [mautic/mautic#7381]
After updating Mautic to the 2.15.1 version.
The page tag title began to be recorded in transliteration. If not in English.
https://imgur.com/9m3bRSr

it's not right

For example. 

Previously, the page tag title "Трикотаж оптом и в розницу поштучно" was recorded as "Трикотаж оптом и в розницу поштучно"
Now the same tag is written to Mautic as "Trikotazh optom i v roznicu poshtuchno"

This can be seen in the contact history. 

Mautic version 2.15.1
PHP version 7.1

**Comment by escopecz** [comment]
Sadly, this is intentional and we cannot change it back until Mautic will 

The PR that introduced it: https://github.com/mautic/mautic/pull/7080
This would fix the problem without transliteration, but it's considered a BC break: https://github.com/mautic/mautic/pull/6554
