### ISSUE TITLE
Uh oh! I think I broke it. If I do it again, please report me to the system administrator! 

### ISSUE THREAD

**Issue by jaganibrijesh** [mautic/mautic#7382]
Whenever I try to send Test email its Give me this error "Uh oh! I think I broke it. If I do it again, please report me to the system administrator! "

I am using Other SMTP Server of Hostgator. Connection is done Right and its Says Success. But when i try to send test Email It give me Above Error. 

Please Help me to Solve this error

**Comment by jaganibrijesh** [comment]
![image](https://user-images.githubusercontent.com/18239899/55489315-55005100-564f-11e9-9ee7-8b14206e0a7f.png)

**Comment by npracht** [comment]
Hello,

Did you try https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful ?
Also, please share the error you have on your logs.

Thanks.

**Comment by escopecz** [comment]
Closing this issue as the issue template was deleted and the error message reported is too vague. Please follow https://www.mautic.org/docs/en/tips/troubleshooting.html next time.

**Comment by GrooveDevops** [comment]
Try fixing your database schema. Go to http://[your-mautic-url]/s/update/schema. It will update your database schema if there are some known updates to be applied.

I had the same problem, and it works fine now.

If it still fails, try looking at the general troubleshooting in the docs https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by DEVENDRA-MAHOUR** [comment]
please provode me solution in window user
