### ISSUE TITLE
Add ability to select the type of asset. ie: download or display in browser

### ISSUE THREAD

**Issue by omero3** [mautic/mautic#7387]
When trying to open an image that uploaded as an asset, the image is forced download.

I believe most users would prefer viewing an image directly in their browser instead of downloading it.

After investigating the issue I found that the file PublicController.php calls the assets with a Content-Disposition of 'attachment', which forces the download.

I changed it to 'inline' and now it works great.
Perhaps in some other file types it will be undesired, so it is also possible to add an 'if' and check the file type, or even adding a field in the asset save form to the way it will be opened.

**Comment by npracht** [comment]
Hi @omero3 !
Then best way would be to add a toggle on the asset edition to chose if it is as `attachment` or as `inline` ? That would be the proper approach and you could propose a PR to the community with that enhancement :)

**Comment by omero3** [comment]
Thanks for the feedback :-) I'll try and do that

**Comment by idea-2** [comment]
I would be interested in this functionality too. Did you start? Can I contribute?

**Comment by omero3** [comment]
I will be very happy if can contribute :-)
I only know how to fix it locally (hard coded), I have no idea how to add the toggle and allow the user to select in the the Asset creation page

**Comment by idea-2** [comment]
I just checked, there is a (hidden) feature in the code (PublicController.php) that allows you to control if the asset should be downloaded or displayed in the browser. Just add the parameter 'stream' to the url.

Download (default)
/asset/1:asset-name

Show in browser
/asset/1:asset-name?stream=1

**Comment by RCheesley** [comment]
Closing this issue, thanks for the detective work @adiwegs :policeman:
