### ISSUE TITLE
Install command

### ISSUE THREAD

**Issue by madmath03** [mautic/mautic#7389]
Since I cannot register to mautic.org, I will share this feature idea here.

It would be great to have commands added to the `InstallBundle`. This would be particularly useful with Docker images of Mautic as one could build a Docker image and automatically install Mautic and setup its plugins.

For the install command, I think we should :

- [ ] rewrite the `InstallController.php` and export all _actual_ install process to a Service
- [ ] add an `InstallCommand` that could use the previous service the same way the controller does

I will try to write a PR for this if I find the time.

**Comment by RCheesley** [comment]
@madmath03 tagged the issue for the 3.1 milestone based on the discussion in the PR!
