### ISSUE TITLE
Not registered Migrations

### ISSUE THREAD

**Issue by IADDIC** [mautic/mautic#7390]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Flush unregistered migrations
I seem to have unregistered migrations from previous installs that I can not seem to clear.  

When I check the schema from the command prompt ~~

php app/console doctrine:migration:migrate

Mautic Migrations

I get this warning

WARNING! You have 4 previously executed migrations in the database that are not registered migrations.
    >> 2015-02-01 00:00:00 (20150201000000)
    >> 2015-02-25 00:00:00 (20150225000000)
    >> 2015-03-07 00:00:00 (20150307000000)
    >> 2015-03-10 00:00:00 (20150310000000)
Are you sure you wish to continue? (y/n)y

WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)yes

No migrations to execute.

When I try to delete unregistered migrations, as follows: 

php app/console doctrine:migrations:version 20150201000000 --delete

WARNING! You are about to add, delete or synchronize migration versions from the version table that could result in data lost. Are you sure you wish to continue? (y/n)y

I get the following message

[Doctrine\DBAL\Migrations\MigrationException]
Could not find migration version 20150201000000

| Q   | A
| --- | ---
| Mautic version 2.15.1 | 
| PHP version 7.2 | 
| Browser | 

### Steps to reproduce
1.  see above
2. 
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Did you install any third plugin ?
Did you try to make a dump and then run the migration files to see what's happen ?

**Comment by escopecz** [comment]
Go to your `migrations` database table, find the 4 rows that contain the unregistered migrations and delete them.

**Comment by IADDIC** [comment]
@escopecz  - perfect.  thanks.

**Comment by pjrobertson** [comment]
A few years late, but I also had this issue.

Here are the SQL commands I ran:

```sql
delete from migrations where version = '20150201000000';
delete from migrations where version = '20150225000000';
delete from migrations where version = '20150307000000';
delete from migrations where version = '20150310000000';
```

Thanks!
