### ISSUE TITLE
Pulling a report to show our stats

### ISSUE THREAD

**Issue by dhmusman** [mautic/mautic#7392]
When pulling a report to show our stats for emails, the columns bounced, bounced ratio, unsubscribed and unsubscribed ratio are showing the same results for every single email no matter how far back we pull the report for.

Mautic version | 2.15.1
PHP version | 7.1

![mautic-report-stats-issue-20190408](https://user-images.githubusercontent.com/12247463/55707326-c6982080-59fc-11e9-99e5-d8590dbe1f16.jpg)

**Comment by npracht** [comment]
Please test https://github.com/mautic/mautic/pull/7214

**Comment by dhmusman** [comment]
We have a report that pulls all of our emails and we filter by date range we need to see. When pulling the report, the bounced and unsubscribed are the same for every single email and they are high numbers.
![report with high bounced and unsubs](https://user-images.githubusercontent.com/12247463/62345016-f1f1ce80-b509-11e9-9f0b-9e60a5e19ced.jpg)

**Comment by RCheesley** [comment]
Closing as this was resolved by https://github.com/mautic/mautic/pull/8478
