### ISSUE TITLE
channel id not updating on cloned campaign action

### ISSUE THREAD

**Issue by flashfireopal** [mautic/mautic#7396]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
When updating the `email to send` for a cloned campaign workflow action, the new email id is not set in the `km_campaign_events.channel_id` column. Instead, only showing the old copied channel_id.

This may lead to old emails that have been unpublished preventing new campaigns from being sent.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.33

### Steps to reproduce:
1. clone a campaign with a `Send Email` action
2. go to the cloned campaign and edit the `Email to Send` value to a different email
3. look at the action row in the `km_campaign_events` table and see that the value in `channel_id` is the old email id

**Comment by escopecz** [comment]
Do you save the campaign after the event change?

**Comment by flashfireopal** [comment]
Yes, here is what I do:

1. open campaign
2. go to campaign builder
3. edit the action and choose the new email to send.
4. press the `Update` button
5. press the campaign builder `Apply` button
6. press the `Close Builder` button
7. press the `Save & Close` campaign button

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
