### ISSUE TITLE
Mail Getting Bounced While Sending Email(Amazon SES)

### ISSUE THREAD

**Issue by Dipranil** [mautic/mautic#7400]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.15.0 
| PHP version | 7.0.33
| Browser | 

### Steps to reproduce
1. I have setup mautic with Amazon SES,i have checked that test mail is working for me. Test mail receiving in the mailbox.But when i added an email from contact section and tried to send mail it's getting bounced.But this emails are correct emails.Also Currently Im using Amazon SES Sandbox which 200emails perday.

![image](https://user-images.githubusercontent.com/16509827/55827455-d5c7bd00-5b27-11e9-9545-768227f32075.png)

**Comment by Bellusterra** [comment]
@Dipranil are you sure it’s not your Amazon SES setup? while in sandbox mode you can only send emails to email addresses that you verified within the amazon console.
