### ISSUE TITLE
company field token don't work with email to users

### ISSUE THREAD

**Issue by johbuch** [mautic/mautic#7405]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When sending an email to users that has company field tokens, the company field tokens won't be displayed.

| Q   | A
| --- | ---
| Mautic version | 2.15.0 / 2.15.1
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a company and fill the company city field
2. Create a contact with a firstname and assign this company then put this contact in a segment.
3. Create a campaign email, add tokens {contactfield=firstname} and {contactfield=companycity}
![image](https://user-images.githubusercontent.com/31535432/55876798-c765b980-5b98-11e9-825b-49df8edf15b8.png)
4. Create a campaign, add action send email to user.
5. See that when the user receive the email, the company field token is not displayed.
![image](https://user-images.githubusercontent.com/31535432/55877105-730f0980-5b99-11e9-95cb-cbabee898641.png)

PS: if an email is sent to a contact (with company field tokens) -> it works
So it is only with email to user
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/7406

**Comment by npracht** [comment]
Fixed when #7406 merged.

**Comment by simcen** [comment]
Crosslinking https://github.com/mautic/mautic/pull/9270 for reference. Issue being resolved by this PR is that only a few company fields (Name, City Country) were replaced. Now all of company fields can be used in "Send email to user" action
