### ISSUE TITLE
List mail brocken after update to 1.1.3?

### ISSUE THREAD

**Issue by different-thinking** [mautic/mautic#741]
Hello,

I just created a new list mail and when I hit "Send" I get the message "There are no pending leads."

That's not true because this is a new message and there are some leads in the selected list.
I tried also another list - same issue.

Robert

**Comment by alanhartless** [comment]
See if #722 fixes the issue.

**Comment by different-thinking** [comment]
Jep! Fixed the issue. Thanks Alan,

Robert
