### ISSUE TITLE
Email changes not saving

### ISSUE THREAD

**Issue by sainionmikko** [mautic/mautic#7417]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Pretty close to https://github.com/mautic/mautic/issues/6799 but the same cure didn't work.
So changes to emails can't be saved. I can create and save a new email with any template. Saving that again either with Save&Close or Apply doesn't save changes. Nothing in any of the logs I could locate. My host checked for ModSecurity errors and found none.
This appeared first on my previous version (2.15.0?) but didn't get any better by updating to 2.15.1. Self hosted on a commercial hosting service.
I have cleared cache, updated schema, regenerated assets and looked for log entries, found none.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2
| Browser | Chrome 73.0.3683.103 64-bit (Also tried with Edge and Firefox to no avail.)

### Steps to reproduce
1. Create a new email (any type, any template).
2. Save&Close or Apply. The new email is created succesfully.
3. Open for editing and hit Save&Close or Apply again.
4. Buttons in the right top are grayed out, progress bar isn't showing up, changes aren't saved.
 
### Log errors
Nothing to be found

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hello @sainionmikko do you have a message in your browser console ?
Did you try: https://github.com/mautic/mautic/pull/7346 ?

**Comment by sainionmikko** [comment]
![image](https://user-images.githubusercontent.com/49557301/56037039-12b5ce80-5d37-11e9-9424-76fdb9d3b6c3.png)
Hi @npracht, the console was new to me, but here's what it says. I can't make anything out of that but the red icon doesn't look good.
I didn't try #7346, will have a look. In my case however it doesn't matter if the builder was loaded or not.

**Comment by sainionmikko** [comment]
Here's another console feedback for an email opened for editing, then opened in builder and changes Applied in the builder.
![image](https://user-images.githubusercontent.com/49557301/56037990-6e815700-5d39-11e9-837c-fbbfb492f820.png)
![image](https://user-images.githubusercontent.com/49557301/56038045-9b356e80-5d39-11e9-8121-89c039750fb9.png)

**Comment by sainionmikko** [comment]
@npracht hmm, sorry, I'm very green in this. I found some (updated?) code in #7346 but not sure what and how should I do with it. Delete and replace these lines in the .js file in question in my installation of Mautic?
Thanks in advance!

**Comment by npracht** [comment]
Yes you can apply the code changes and re-generate assets of you instance.

**Comment by sainionmikko** [comment]
Ok, I've applied the changed code, regenerated assets and cleared cache. No change in behaviour. The console tells me now: 
Failed to load resource: the server responded with a status of 403 ()
https://mysite/mautic/s/emails/edit/8?mauticUserLastActive=1&mauticLastNotificationId=

Any further advice please? I'm soon going to have to turn to a tool that I can make work.

**Comment by sainionmikko** [comment]
I still don't know what worked, but I ended up replacing all files in my Mautic instance, that I had changed since the installation, with the originals. This made it work again.
