### ISSUE TITLE
track user

### ISSUE THREAD

**Issue by sharmasourabh18** [mautic/mautic#7422]
so once a user clicks on a email from mautic and goes to the website and closes the tab and again comes back to the website organically, i want to track the user on mautic. I want to see that he came back to the website organically

i have already installed the mautic code on the website but i is not tracking beyoned the first click from the email to the website

**Comment by escopecz** [comment]
Please use the issue template.
Please provide steps to test.
Please use the right terminology as you talk about users but from the context it seems you mean contacts. There is quite big difference between the two in Mautic.

I think that https://www.mautic.org/docs/en/pages/troubleshooting.html could help with tracking tests.
