### ISSUE TITLE
/oauth/v2/authorize redirects to /oauth/v2/authroize_login

### ISSUE THREAD

**Issue by sirpy** [mautic/mautic#7429]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
issuing a GET query trying to do oauth the reply redirects to /oauth/v2/authorize_login which doesnt respond to oauth protocol and always shows html page for regular login

**Comment by escopecz** [comment]
As this ticket doesn't contain any details, doesn't follow the issue template and only states what the [docs say](https://developer.mautic.org/#oauth-2) I will close it.

> Redirect the user to the authorize endpoint `oauth/v2/authorize`

**Comment by koudicz** [comment]
I have the same problem. Oauth2 redirect me on clasic login page.

**Comment by escopecz** [comment]
Please explain why it is an issue.

**Comment by sirpy** [comment]
@koudicz its not an issue. This is ment as a UI flow for authorizing 3rd parties. What is missing is to be able to use the user api secret directly via server side, when the user is the mautic instance owner and not a 3rd party.

What you have to do is to make the first request to /authorize in the browser then authorize the app it will then redirect you to the url you specified in the mautic api key as redirect. but to use it programatically you just need to copy the token form the browser url.
