### ISSUE TITLE
add in setting "enable/disable FingerPrint2" to avoid loading the library

### ISSUE THREAD

**Issue by dungbx** [mautic/mautic#7431]
## Bug Description
FingerPrint2 inside mtc.js is still initialized even I disabled it.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1-apache
| Browser | Mobile iOS Safari

### Steps to reproduce
1. Turn on FingerPrint
2. Turn off FingerPrint 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
There is no Turn on FingerPrint button.
It's just switch to enable identify contacts by fingerprint. It's two different things.
Fingerprint is loaded in core. Can't disable it.

**Comment by dungbx** [comment]
@kuzmany 
Well, that's the problem. Fingerprint is loaded in core, which will slow down PageLoad in mobile quite significant.

**Comment by kuzmany** [comment]
@dungbx similar request already exists. 
There are two options
- wait until Mautic team or another company create this feature (optional js library load)
- or hire somebody to bring it to Mautic (https://mtcextendee.com/mautic-developement/)

**Comment by RCheesley** [comment]
Closing as fingerprint was deprecated in Mautic 3.x
