### ISSUE TITLE
Issue with boolean field in email dynamic content

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#7451]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The dynamique content in email seems to have different tules than in segment for the booleans.
In Segment if you use a filter not equal to No, all the contacts with a blank field for this boolean will be add to the segment.
In dynamic content in email it's not the case. blank value for boolean is equal to None.

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a boolean custom field leave the default value to blank
2. Create an email with a dynamic content using the filter not equal to No
![image](https://user-images.githubusercontent.com/49391402/56424819-21116680-62b2-11e9-862e-e402130a697b.png)
3. Send the email to the contact, he will receive the default variant and not the one with the filter

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
Let's test guys: https://github.com/mautic/mautic/pull/7468

**Comment by npracht** [comment]
Fixed when #7468 merged.
