### ISSUE TITLE
mautic 2.15.1 scheduled actions not working

### ISSUE THREAD

**Issue by JossyMall** [mautic/mautic#7453]
Mautic is great. Really great, the best i have ever seen. But after upgrade to 2.15.1 all sheduled actions from change segment to points to emails are not working! I am pretty sure cron jobs are set up correctly...here is an example **/var/www/www-root/data/php-bin-isp-php70/php  /var/www/www-root/data/www.jossymall.com/m/app/console mautic:campaigns:rebuild** my php path is also correct. This issue is very frustrating...infact i dnt mind giving out my server details to anyone who might want to look into it for me...aiish i feel like cutting myself! i have tried everything but still nothing works...makes me squirm!

**Comment by escopecz** [comment]
1. Check the logs (https://www.mautic.org/docs/en/tips/troubleshooting.html)
2. Do you have logs for your cron jobs? 
    2.a. Check them
    2.b Execute the command from the cron job yourself via SSH. What is the output?
