### ISSUE TITLE
Site is Offline: Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) (uncaught exception)

### ISSUE THREAD

**Issue by sushilkedia** [mautic/mautic#7455]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
I did some changes in the configuration section of Mautic and then hit the Apply Button. I was greeted with the usual "Site is Offline..." error message box. Referred to the bugifxing articles and cleared everything in the /app/cache folder. No improvement. Ran to the url /s/update/schema. No use. 

SO went to next step of checking the error log in mautic installation and found this 5 times: 

Doctrine\DBAL\Exception\ConnectionException: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) (uncaught exception) 

I then rechecked if the database user password is matching with the one inputted in the local.php file in mautic install. It is. 

So at a loss what to do now? 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.5.1
| PHP version | 7.1 (in the mautic folder) otherwise 7.3 on my WP site. 

### Steps to reproduce:
1. Go to Mautic Dashboard. 
2. Click open the configuraiton tab. Make few changes. Hit apply button. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Try this:
1. Open `app/config/local.php`
2. Replace the line `'db_host' => 'localhost',` with `'db_host' => '127.0.0.1',`
3. Save the file.
4. Delete the contents of the `app/cache/` directory. Use this command if you can: `rm -rf app/cache/*` from Mautic root directory.
