### ISSUE TITLE
I need to send 10 emails each minute 

### ISSUE THREAD

**Issue by foxmedo** [mautic/mautic#7456]
Hello i need to send 10 or 5 email each minute i have a database with 100K emails and im using shared hosting so i want to send email with specific quote to keep the mail queue every time clean 

right now if i want to send a compaign mautic will put all emails 100k in the queue, how can i limit this by minutes 

B.R

**Comment by escopecz** [comment]
Try to turn the email queue ON in Mautic configuration page. Then configure cron to run this command every minute: 

`app/console mautic:emails:send --message-limit=10`

BTW I haven't try it but it should do the trick.
