### ISSUE TITLE
Campaign action "Send email to contact" does not respect weekday restriction when in "transactional" mode

### ISSUE THREAD

**Issue by AlbanL74fr** [mautic/mautic#7458]
## Bug Description
 
Email is sent on saturday even though it's not checked.

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 
| Browser | 

### Steps to reproduce
1. We are tuesday, set Send email to send in 5 days
2. Select only weekdays (Monday to Friday)
3. Set Transactional mode

Normally I would expect the email to be re scheduled on Monday, but it's sent on Saturday.
 
### Log errors
Nothing found

**Comment by escopecz** [comment]
Please upgrade your Mautic to the latest version. It contains several bug fixes in this area.

**Comment by AlbanL74fr** [comment]
Thanks @escopez, I will update to 2.15.2 when available, and see if it resolves the problem I reported here
