### ISSUE TITLE
Mautic on DIGITALOCEAN

### ISSUE THREAD

**Issue by fredroo** [mautic/mautic#7459]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.15.1
| PHP version | 7.2.15-0 on ubuntu 0.18.04.2
| Browser | Google Chrome

### Steps to reproduce
1. Log in and try to connect to SMTP or AMAZON SES (DIGITALOCEAN using port 587, this port is now open and tested by telnet on terminal)
2. Don't return any message, no errors, and no success
 
### Log errors
Empty

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Any errors in the logs? https://www.mautic.org/docs/en/tips/troubleshooting.html

**Comment by fredroo** [comment]
@escopecz 

about General troubleshooting, nothing solves my problem

Mautic error logs are empty and 
Nginx error logs are empty

**Comment by escopecz** [comment]
It could be a sign that file system permissions or folder owner is wrong. I host my Mautic instances on DO and have no problem to send emails through SMTP, so I don't think it's a Mautic issue.

**Comment by fredroo** [comment]
Solved, thanks @escopecz 
I followed this guide below in step 6 (replaced my config file)
https://websiteforstudents.com/setup-mautic-on-ubuntu-16-04-18-04-with-nginx-mariadb-and-php-7-1-fpm/
