### ISSUE TITLE
Problems after upgrade

### ISSUE THREAD

**Issue by BigChrons** [mautic/mautic#7461]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
X | Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:

I was running Mautic 2.1.1 using Bitnami on Windows Server 2012. After running the upgrade to version 2.15, scheduled jobs like console mautic:segments:update just sit there and show "Rebuilding contacts for segment 1. 0 total contact(s) to be added in batches of 300", console mautic:campaigns:rebuild runs without error and console mautic:campaigns:trigger errors out with "Error: __clone method called on non-object" on \Scheduler\Mode\Interval.php:108. Any help getting these scheduled tasks up and running again would be greatly appreciated.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version |  5.6.31

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by escopecz** [comment]
Do you have the whole error message? If that's all, could you run the command with `-vvv --env=dev` attributes to see if you get more details?

`mautic:campaigns:rebuild -vvv --env=dev`
