### ISSUE TITLE
 Mautic sends webhook delete event when it merges a form submission with the contact having the same email address

### ISSUE THREAD

**Issue by mihaicirstea** [mautic/mautic#7466]
## Bug Description
When an identified contact logs-in our site from a new IP address & new browser, Mautic sends a webhook event "function": "mautic_lead_post_delete_entry" even though the contact already exists in Mautic and retains the same ID...therefore it's not deleted.

Why is this hook sent by Mautic in this scenario?  Problem is we have a CRM that listens to webhooks and this delete event is unexpected.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1.28
| Browser | Firefox 66.0.3
 
### Log errors

[2019-04-21 15:07:56] local.DEBUG: Lead::delete(48197) : [
    {
        "file": "\/home\/admin\/web\/deploys\/crm\/20170405T115400\/admin\/web\/crm\/app\/Jobs\/WebHookJob.php",
        "line": 119,
        "function": "delete",
        "class": "App\\Lead",
        "object": {
            "id": 48197,
            "first_name": "Chris",
            "last_name": "Walls",
            "email": "edited5@yahoo.com",
            "phone": "6474039888",
            "score": 12,
            "max_score": 12,
            "status_id": 8,
            "agent_id": 104,
            "assigned_at": "2019-03-17 12:01:14",
            "mautic_lead_id": 481576,
            "dashboard_display": 0,
            "lead_activity_type": 1,
            "lead_activity_date": "2019-04-16 09:45:59",
            "last_activity": "2019-03-17 12:04:19",
            "last_activity_title": "Call: Answered",
            "dead_reason": "spoke to lead doesn't want any contact",
            "updated_at": "2019-04-16 09:45:59",
            "last_inquiry_date": null
        },
        "type": "->",
        "args": []
    },
    {
        "file": "\/home\/admin\/web\/deploys\/crm\/20170405T115400\/admin\/web\/crm\/app\/Jobs\/WebHookJob.php",
        "line": 44,
        "function": "mautic_lead_post_delete_entry",
        "class": "App\\Jobs\\WebHookJob",
        "object": {
            "connection": null,
            "queue": null,
            "delay": null
        },
        "type": "->",
        "args": [
            {
                "id": 4738412,
                "lead": {
                    "isPublished": true,
                    "dateAdded": "2019-04-17T01:16:31-04:00",
                    "dateModified": "2019-04-21T11:07:14-04:00",
                    "createdBy": null,
                    "createdByUser": null,
                    "modifiedBy": null,
                    "modifiedByUser": " ",
                    "id": null,
                    "points": 6,
                    "color": null,
                    "fields": {
                        "core": {
                            "firstname": {
                                "id": "2",
                                "label": "First Name",
                                "alias": "firstname",
                                "type": "text",
                                "group": "core",
                                "object": "lead",
                                "is_fixed": "1",
                                "value": null
                            },
                            "lastname": {
                                "id": "3",
                                "label": "Last Name",
                                "alias": "lastname",
                                "type": "text",
                                "group": "core",
                                "object": "lead",
                                "is_fixed": "1",
                                "value": null
                            },
                            "email": {
                                "id": "6",
                                "label": "Email",
                                "alias": "email",
                                "type": "email",
                                "group": "core",
                                "object": "lead",
                                "is_fixed": "1",
                                "value": "edited@yahoo.com"
                            },
                            "phone": {
                                "id": "8",
                                "label": "Phone",
                                "alias": "phone",
                                "type": "tel",
                                "group": "core",
                                "object": "lead",
                                "is_fixed": "1",
                                "value": null
                            },
                            "address1": {
                                "id": "10",
                                "label": "Address Line 1",
                                "alias": "address1",
                                "type": "text",
                                "group": "core",
                                "object": "lead",
                                "is_fixed": "1",
                                "value": null
                            },

**Comment by mihaicirstea** [comment]
@escopecz 

I'm now thinking that the mautic.lead_post_delete webhook fired is normal because:

When a Mautic form is submitted with the same email address, that is already associated with another contact ID. I assume Mautic performs sort of a "merge procedure" where contact_id=02 is merged with contact_id=01... to retain the initial Mautic ID?

Therefore contact_id=02 is deleted and contact_id=01 is updated. As such also 2 web hooks are also fired:

a. for contact_id=02:

{
"mautic.lead_post_delete": [
{
"id": 02,
"lead": {
"isPublished": true,
"dateAdded": "2019-04-24T05:34:49-04:00",
"dateModified": "2019-04-24T05:37:43-04:00",
"createdBy": null,
"createdByUser": null,
"modifiedBy": null,
"modifiedByUser": " ",
"id": null,
"points": 6,
"color": null,
"fields": {

b. for contact_id=01:

{
"mautic.lead_post_save_update": [
{
"lead": {
"isPublished": true,
"dateAdded": "2018-03-11T18:47:55-04:00",
"dateModified": "2019-04-24T05:38:10-04:00",
"createdBy": null,
"createdByUser": " ",
"modifiedBy": null,
"modifiedByUser": " ",
"id": 01,
"points": 187,
"color": null,
"fields": {

Can you confirm this is correct and part of the normal functionality of Mautic and not a bug?

**Comment by escopecz** [comment]
Sounds like it. Thanks for the self-explanation :)
