### ISSUE TITLE
Contacts coming from other users forms are being assigned only to the main user.

### ISSUE THREAD

**Issue by arymaynart** [mautic/mautic#7467]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

I did the search and found nothing.

## Bug Description

I have a self hosted mautic installation and i create a role called GlobalUsers and I set the permissions has the follow:

Total access: No
Basically, I have set all permissions possible as the follow:
See Own
Edit Own
Create
Delete Own

For other kind of options, i have set:
See
Create
Publish

My objective with this is forbid the user to edit things that does not belong to him. Besides that, i want him to be capable to use some functions that i consider global (Segments, Categories, Points, Stages, etc...), or be, he can use, set it on his contacts but can't edit or delete.

Besides my admin user, i have created a new user called User1 and it to GlobalUsers role.

With this new user, I create a new campaign form and put it on a wordpress landing page using the form javascript.

When a lead fills and submit this form, a contact is created, but it does not appear on contacts of these new user.
So, i loged in with my admin user to see if there was a missconfiguration on GlobalUsers role, and when i goes to Contacts, that lead that fills the form was there, with my admin user like the owner of the contact.

So, i try to create another administrative user and repeat the proccess.
I've got the same results.

| Q   | A
| --- | ---
| Mautic version |
v2.15.1
| PHP version | 
PHP Version 7.2.16
| Browser | 
Chrome
Edge
Firefox
Opera

### Steps to reproduce

The easy way
0. Log in on Mautic with Admin user.
1. Create a new user.
2. Log out.
3. Clear Browser cache
4. Log in with the new user.
5. Create a simple campaign form
6. Copy the javascript of the new form (automatic option)
7. Log out Mautic and clear Browser cache.
8. Paste the javascript code on a landing page of a CMS (I use wordpress for this test)
9. Fills the form and submit it.
10. Log in on Mautic with the user who create the form.
11. Go to Contacts
12. Search for the contact that fills the form. (just type is:my and search for it). You won't find it.
13. Log out Mautic.
14. Log in with admin user.
15. Go to Contacts
16. Look for the contact. You will find it.
 
### Log errors
[2019-04-23 23:36:37] mautic.NOTICE: PHP Notice - SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/lib/php/sessions) failed: Permission denied (13) - in file /var/www/mautic/public_html/vendor/symfony/http-foundation/Session/Storage/Proxy/SessionHandlerProxy.php - at line 86 [] []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Could you use the "Update contact owner" campaign action to assign the user you need?

**Comment by arymaynart** [comment]
Hi.
I do not undertood the meaning of your question, so i will assuming that you are telling me to leave this like it is and work arround another way.
Yes I can.
I can do it manually too.

But I am openning this bug report because for my perspective, something is worng.
I mean: Should this be the proper behaviour?

"A user build a form, attach his form on a landing page, and he is not the owner of the contact that came from his own form?"
Sorry, but this doesn't sound right to me.

If you does not want to mean that, sorry for the rigid answer, but i couldn't find another way to put it.

**Comment by escopecz** [comment]
My intention was to resolve your issue. There is campaign action that does exactly what you need. I'm really sorry I upset you with it. I will try to remember to not answer your issues.

I'm skeptical about making contact owner only because it came from a from created by that user. What if another user updates the form? Should he be owner of the contacts created by the form? Does the same apply for landing pages? The owner of the contact should be the one who created the landing page and the contact loaded it? Would this rule apply only for new contacts or the owner should change based on any interaction with Mautic and the users who created the forms, pages, assets, point actions and so on? I think it's better to explicitly tell Mautic who the owner should be with a campaign action.

**Comment by AlbanL74fr** [comment]
Yes I agree, the contact owner has nothing to do with the person who creates the form. The contact owner is the person that will be assign a lead, for example, it can be a sales person of your organization, while the one who created the form might be a developer. Like @escopez suggested, a campaign with a form submission as source is a good way to assign a contact owner, then send an email, and use that owner's signature in the email for example.

**Comment by arymaynart** [comment]
> My intention was to resolve your issue. There is campaign action that does exactly what you need. I'm really sorry I upset you with it. I will try to remember to not answer your issues.
> 
> I'm skeptical about making contact owner only because it came from a from created by that user. What if another user updates the form? Should he be owner of the contacts created by the form? Does the same apply for landing pages? The owner of the contact should be the one who created the landing page and the contact loaded it? Would this rule apply only for new contacts or the owner should change based on any interaction with Mautic and the users who created the forms, pages, assets, point actions and so on? I think it's better to explicitly tell Mautic who the owner should be with a campaign action.

Hi Mate. Sorry if I sounded rude. That was not my intention. Like I sayd: I just didn't finded another way to answer. By the way, my english vocabulary is a litle restrict, so i decided to go directly to the point.
About your answer, understood your point, and it really makes senses when we look on this perspective.
But lets look in another direction:
Lets imagine a single mautic instalation to manage contacts that will came from 4 differents websites, therefore, 4 different owners. So, each contact should see only their own contacts, their own forms sharing global stuffs like Segments and fields.
On this perspective, the colaborative situation that you put back there doesn't fit.
Here, every form created by each user should assign the contact to his creator.
What do you think about that?

**Comment by AlbanL74fr** [comment]
At the moment of form submission, you have multiple options to identify who owns the contact, for example, you can add a tag to the contact, or you can add the contact to a segment, or both if you prefer. After that you can manipulate contacts easily with campaign tree logic. That's always better to start from the use case. Fell free to ask on the Slack channel, there are other folks there that use Mautic as agencies, for multiple clients per instance.

**Comment by arymaynart** [comment]
AlbanL74fr, I know there are several ways to work around this problem. And you are right. I want to use Mautic as an agency.
But, i really do not want to throw this problem on my clients.

Imagine this situation: 

Me: "Hi, I have a digital marketing platform that automates several marketing actions. It can capture leads data end send seguimented E-mails, Messages, Tweets and much more. It is fully customizable and you can full programate marketing campaigns. This can make your job much more easy. But for it to works like a charm, you will need to assign "You" like the contact owner on EVERY form you create using a seguiment or a tag."
Client: "Sounds Great. But, really? On every form that I create, I willl need to assign ME?"
Me: "Yes. On every Form."
Client: "Ok. But, If I forgot to do this and a lead fills in MY form on MY landing page, what will happen with this lead data? For where it goes?"
Me: "Do not worry about that. You can just open a ticket telling us about your problem and send us the e-mails of the contacts that fills in your form. Then we will assign he to you.
Client: Ok. But how do I will know Who filled the form?
Me: ................

Does this makes sense for you?
For me does not.

**Comment by escopecz** [comment]
@arymaynart I think this request comes from an assumption that Mautic was built for agencies to accommodate several clients in one installation. Such assumption is false. Create one Mautic installation for each of your clients and your problems will disappear.
