### ISSUE TITLE
Sending Broadcast Emails are not working

### ISSUE THREAD

**Issue by NipunReddy555** [mautic/mautic#7471]
## Bug Description
Unable to get segment/broadcast emails to send. My segment email shows as published, shows 1 pending email, and publish dates seem to be set as expected.

I run the cron by itself or with different combinations of --id=XX --channel=email. No change. Output is:

+---------------+--------+----------+
| Channel | # sent | # failed |
+---------------+--------+----------+

| Q   | A
| --- | ---
| Mautic version | 2.8.2
| PHP version | 7
| Browser | windows 7

### Steps to reproduce
 1. Create new contact with email address
 2.Add contact to a segment
 3.Create new segment (broadcast) email
 4.Select segment, enter past publish date, future publish end.
 5.Complete email - Email list should show pending stat
 6.Wait for cron to run or execute manually

### Log errors
No log records. Syslog shows cron executing.

**Comment by npracht** [comment]
Hi @NipunReddy555 can you say exactly what is the exact command you use ?

**Comment by NipunReddy555** [comment]
Hi @npracht .
The command I am using is 
php /path/to/mautic/app/console mautic:broadcasts:send --channel=email --id=22

**Comment by npracht** [comment]
and you don't have any error ? Is the email published ?

**Comment by NipunReddy555** [comment]
yes the email is published and i don't have any error.

**Comment by npracht** [comment]
Hi @NipunReddy555 do you still have an error with mautic 2.15 .

**Comment by NipunReddy555** [comment]
Hi @npracht 
I have any issue with mautic 2.8.2 v and the issue still exists.

**Comment by npracht** [comment]
Hi @NipunReddy555, my question is, could you please update your instance and tell if the bug still occurs in 2.15.1 version ?

**Comment by elliott-io** [comment]
I have Mautic 2.15.1 and am having the same problem. Any ideas?

**Comment by npracht** [comment]
Something in the logs @elliott-io ?

**Comment by npracht** [comment]
@elliott-io up.

**Comment by AkkuFresh** [comment]
@NipunReddy555 Can you update PHP to 7.2.22 at least and Mautic to the latest v.2.15.3?
After updating PHP and Mautic please provide the full cron command and all system parameters of the server. I try to help.

**Comment by npracht** [comment]
Without extra information and being an old issue, let close it.

**Comment by BillPackard** [comment]
Need to enter  "Publish at (date/time)" in the form, and after works.
