### ISSUE TITLE
Contact gets assigned to a Stage with lower weight.

### ISSUE THREAD

**Issue by krzysztofmn** [mautic/mautic#7472]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
According to tooltips in Mautic, "a contact cannot change to a stage of lower weight". I would assume it is automatically assured by Mautic. However, when I add a contact to a stage of lower weight than her current one via API, she unfortunately gets assigned to it.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2
| Browser | Firefox Developer Edition 67.0b9

### Steps to reproduce
1. Assign a contact to any stage via Mautic interface or API.
2. Assign a contact to a stage with lower weight via API.
 
### Log errors
Not applicable

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by bradjones1** [comment]
I have reproduced this on Mautic 4.x HEAD. The guard for changing to a stage of lower weight is not applied when making the change over the API.

**Comment by RCheesley** [comment]
Thanks for adding the note about current behaviour @bradjones1 - we will need to have someone take a look and make a PR to fix it.
