### ISSUE TITLE
Segment email fail to send using sendgrid API

### ISSUE THREAD

**Issue by hrouissi** [mautic/mautic#7476]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When using sendgrid API segment email fail to send both through UI and SSH CLI command.

N.B 1 : changing the setup to sendgrid SMTP settings allowed me to send the campaign.
N.B 2 : the setup is ok and the API is connected correctly, multiple test emails have been sent both from email settings and example email.
  
| Q   | A
| --- | ---
| Mautic version | 2.14
| PHP version | 5.6.37
| Browser | Chrome

### Steps to reproduce
1. Setup Sendgrid API as as an email provider
2. Test sendgrid api (result success)
3. save settings and send test email (result succes)
4. create a segment email and send test email (email sent with success)
5. send email through UI (you can see the progression but at the end all emails have not been sent with UI error)
6. try alternative and send email campaign through SSH CLI mautic:boradcast (you see in the UI that the count is updating but when finished report shows 100% failure in sending emails)   
 
### Log errors
Sorry, but don't have an idea where to get logs for it.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
If you look at the detail page of the contact that did not receive the segment email there should be written why in the details of that email send action. Can you share a screenshot of that?

**Comment by hrouissi** [comment]
Sorry, 
But nothing shows up on the contact detail page. As if the email has never been sent.

**Comment by escopecz** [comment]
The error must show up somewhere. How about the notification center?

![notify](https://user-images.githubusercontent.com/1235442/56884113-10f34700-6a69-11e9-9de2-0616072b4243.png)

Also check all the logs mentioned in https://www.mautic.org/docs/en/tips/troubleshooting.html

And look at Sendgrid UI. There should be some event log as well.

**Comment by hrouissi** [comment]
Sorry, the error doesn't show up in the notification panel neither.

**Comment by escopecz** [comment]
Mautic logs, server logs, sendgrid logs? No one can help without any error message.
