### ISSUE TITLE
Allowed memory size of 1073741824 bytes exhausted when add new Contact

### ISSUE THREAD

**Issue by ratkobucic** [mautic/mautic#7477]
## Bug Description
Installed brand new Mautic as per instructions from here.
When I try to add new Contact with Contacts/New button I get nothing after some loading line running on top... and in log I see this error in Apache log:

`[Sun Apr 28 13:08:15.540219 2019] [:error] [pid 1668] [client 178.149.90.128:49443] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 536870920 bytes) in /var/www/html/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php on line 134, referer: https://domain.com/s/contacts`

memory_limit was set to 256M/512M/1024M respective to confirm it report same error.

| Q   | A
| --- | ---
| Mautic version | v2.15.1
| PHP version | PHP 7.0.33
| Browser | Chrome latest

### Steps to reproduce
1. Open Contacts
2. Click on New 
 
### Log errors
Apache:
```
[Sun Apr 28 13:05:20.040506 2019] [:error] [pid 2079] [client 178.149.90.128:49873] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 268435464 bytes) in /var/www/html/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php on line 134, referer: https://domain.com/s/contacts

[Sun Apr 28 13:08:15.540219 2019] [:error] [pid 1668] [client 178.149.90.128:49443] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 536870920 bytes) in /var/www/html/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php on line 134, referer: https://domain.com/s/contacts
```

Mautic app/logs/
```
[2019-04-28 20:08:15] mautic.ERROR: PHP Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 536870920 bytes) - in file /var/www/html/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php - at line 134 [] []
[2019-04-28 20:08:15] mautic.ERROR: Symfony\Component\Debug\Exception\OutOfMemoryException: Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 536870920 bytes) - in file /var/www/html/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php - at line 134 [] []
[2019-04-28 20:08:15] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 536870920 bytes)" at /var/www/html/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php line 134 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 536870920 bytes) at /var/www/html/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php:134)"} []
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Looks like an infinite loop. I know about similar issue although you'll have to confirm it is the same: https://github.com/mautic/mautic/issues/7408

**Comment by ratkobucic** [comment]
Replaced Locale.php file with one stated in #7408 
and now I'm getting another error... 

`[2019-04-29 08:19:05] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)" at /var/www/html/vendor/symfony/intl/Locale.php line 38 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) at /var/www/html/vendor/symfony/intl/Locale.php:38)"} []`

**Comment by ratkobucic** [comment]
But could be this is problem
> PS: It's work for PHP 7.1+, for PHP 7.0 you will have to edit it manually to apply the diff.
as I'm using PHP 7.0

**Comment by escopecz** [comment]
When I look at [line 38](https://github.com/symfony/symfony/blob/2f73c2f66b54b376647b605ebd4fbd7f399b0ff9/src/Symfony/Component/Intl/Locale.php#L38) it uses [nullable type hint syntax](https://php.net/manual/en/migration71.new-features.php) that is supported since PHP 7.1.

Use this version that is suggested as a fix to the new Mautic version:

https://github.com/mautic/intl/blob/master/Locale.php

**Comment by ratkobucic** [comment]
Hm, downloaded https://raw.githubusercontent.com/mautic/intl/master/Locale.php and cleaned cache... 
and again error:
`[2019-04-29 08:53:02] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)" at /var/www/html/vendor/symfony/intl/Locale.php line 38 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) at /var/www/automation.webdrvn.com/vendor/symfony/intl/Locale.php:38)"} []
`
Now even QuickAdd for Contact reporting this error, when I click on Cancel on that form.
```
 Uh oh! I think I broke it. If I do it again, please report me to the system administrator! 
500 Internal Server Error
```
Should I try to use PHP 7.1 maybe ?

**Comment by escopecz** [comment]
Oops, sorry. I forgot to choose the right branch. This is the correct one:

https://github.com/mautic/intl/blob/2.8/Locale.php

**Comment by ratkobucic** [comment]
OK, seems this one is good one, now I see Contact/New working without memory leak. Thanks @escopecz

**Comment by ravinayag** [comment]
I faced this problem relate to memory allocation and similar to this when i do cache:clear:
PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/user/public_html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php

Hence tried to update the mautic version, 2.16.2, the update was success but the memory error not gone.

PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 495616 bytes) in /home/user/public_html/s/vendor/symfony/translation/Translator.php on line 353
[Symfony\Component\Debug\Exception\OutOfMemoryException]
Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 495616 bytes)
Exception trace:
() at /home/user/public_html/s/vendor/symfony/translation/Translator.php:353
################################
the Solution : increase memory_limit in the php.ini file.
memory_limit=1024M

check which php ini config is using by:
php -i | grep "php.ini"
once it updated restart the Apache services.
