### ISSUE TITLE
Slow form submission

### ISSUE THREAD

**Issue by martinduplex** [mautic/mautic#7478]
Hi everyone, does any one experiencing issue where the Mautic form submits after 15-20 seconds - it takes quite long time while displaying "please wait...." in submit button? Our Mautic version is v2.14.2 Certainly this affects user experience

| Mautic version | v2.14.2
| PHP version | 7.1
| Browser | Google Chrome

### Steps to reproduce
1.  Filling in the front end Mautic form embedded in the website
2.  Click Submit button
3. The Submit button displays "Please Wait...." for 20 seconds approx
4. Form cleared the data and changed state of the submit button.

**Comment by escopecz** [comment]
Please upgrade to 2.15.2 and let us know if the issue is still there. I will reopen this issue if so.

**Comment by martinduplex** [comment]
@escopecz Hi John, thanks for that.  
I have cloned staging the Mautic instance and updated it via terminal command line to 2.15.1 (apparently the terminal could find 2.15.1 instead of 2.15.2).

Then I logged in the Mautic to go to existing form item, and click preview form to test the form submission, however the screen ended up showing 500 Internal Server Error. This 500 internal server error also occured when I create new form and submitted test form preview.

I appreciate your advice and assistance.

**Comment by escopecz** [comment]
Read through https://www.mautic.org/docs/en/tips/troubleshooting.html and give us the right error message, please.

**Comment by martinduplex** [comment]
> Read through https://www.mautic.org/docs/en/tips/troubleshooting.html and give us the right error message, please.

Hi John @escopecz , as requested, please find the error logs found in the log file in App folder as instructed:

`[2019-04-30 15:18:16] mautic.WARNING: String could not be parsed as XML [] []`

`[2019-04-30 15:19:00] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Validator\Exception\UnexpectedTypeException: "Expected argument of type "string", "array" given" at /home/xxx/public_html/mauticnew/vendor/symfony/validator/Constraints/LengthValidator.php line 38 {"exception":"[object] (Symfony\\Component\\Validator\\Exception\\UnexpectedTypeException(code: 0): Expected argument of type \"string\", \"array\" given at /home/xxx/public_html/mauticnew/vendor/symfony/validator/Constraints/LengthValidator.php:38)"} []`

`[2019-05-01 09:45:24] mautic.WARNING: PHP Warning - SimpleXMLElement::__construct(): Entity: line 72: parser error : Opening and ending tag mismatch: meta line 8 and head - in file /home/xxx/public_html/mauticnew/vendor/debril/rss-atom-bundle/Debril/RssAtomBundle/Protocol/Parser/XmlParser.php - at line 27 [] []`

**Comment by escopecz** [comment]
1. ` Class 'ZipArchive' not found` Install and/or enable the PHP ZIP module on your server. Restart the server afterwards.
2. `mautic_leads (last_active)': Too many keys specified; max 64 keys allowed` there seem to be a lot of custom fields in your Mautic instance. Try to go through them and delete those you don't need. For example those for social media handles.
3. `SimpleXMLElement::__construct(): Entity: line 138: parser error : Opening and
ending tag mismatch` Double check that you have simpleXML enabled in your PHP. Easiest is to search for it in PHP info. The error message would suggest that the XML feed is not valid but I haven't seen this elsewhere.
4. `Unknown column 't0.validation' in 'field list'` Would suggest your SQL schema is outdated. [See this tutorial](https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful) on how to fix that. It may be related to form submissions.

**Comment by martinduplex** [comment]
Hi @escopecz ,

Thanks for your input.

We have enabled Zip module as well as SimpleXML module, and ran schema update on Mautic, but the issue still persists.

Will review on the custom fields in Mautic to trim down to core only connected to CRM mandatory fields like Last name and postcode which are actually mandatory in CRM. Just thinking maybe keep custom fields to the following:
- First Name
- Last Name
- Company
- Email
- Street
- Phone
- Country
- Postcode
- Industry
- Description/Message

Looking at our Mautic instance, the number of custom fields (core + pro + other) is 99. Is that way too much for optimal performance?

Looking forward to your advice, John. Many thanks.

**Comment by martinduplex** [comment]
Further update here, I've reduced number of fields in Custom Fields page from 99 to 64 fields. and I also ran the command for clean up maintenance in terminal "php app/console mautic:maintenance:cleanup" to purge old history (Visitors history:  96k purged).

**Comment by martinduplex** [comment]
@escopecz 
Interesting find just today, when I add "push to integration" action option to the form, it increases time for submission duration.

- If we add option to push the lead to CRM, the submission time takes 17 seconds.
- If we submit without "push to integration" action to CRM it takes 6 seconds. 

Does this mean that number of mapping fields causes the database lookup query time that significantly affect Mautic performance in "fetching data from fields to match with the CRM core fields"?

**Comment by escopecz** [comment]
It's good to know that all form actions that you set up for concrete form and webhooks with contact create/update and form submitactions (if not configured as a background job) will slow down the form submission. Try to use campaign actions instead if possible as campaign actions are handled in the background and not on the form submission request.

**Comment by escopecz** [comment]
Also, to really know what is taking so long in your case use PHP profiling apps like Tideways or Blackfire or whatever you find like that.

**Comment by martinduplex** [comment]
> Also, to really know what is taking so long in your case use PHP profiling apps like Tideways or Blackfire or whatever you find like that.

Thanks @escopecz , I am not quite familiar with PHP profiling applications, but thanks for information though!

I am considering using CRM webform instead for selected specific forms (pending on testing), but the other forms in the website use Mautic form.

**Comment by martinduplex** [comment]
> It's good to know that all form actions that you set up for concrete form and webhooks with contact create/update and form submitactions (if not configured as a background job) will slow down the form submission. Try to use campaign actions instead if possible as campaign actions are handled in the background and not on the form submission request.

Thanks @escopecz for that recommendation, I am wondering what is the cron job to process that "push to integration" campaign action in the background job, assuming if the top level source is assigned to campaign form (which connect to next to action item that pushes contact to integration). I tried this approach and I can see that the actions are "pending" rather than not pushing in an instant to the integration (Vtiger CRM).

**Comment by martinduplex** [comment]
> Further update here, I've reduced number of fields in Custom Fields page from 99 to 64 fields. and I also ran the command for clean up maintenance in terminal "php app/console mautic:maintenance:cleanup" to purge old history (Visitors history: 96k purged).

It seems this maintenance clean up did not improve form submission speed.

**Comment by martinduplex** [comment]
> > It's good to know that all form actions that you set up for concrete form and webhooks with contact create/update and form submitactions (if not configured as a background job) will slow down the form submission. Try to use campaign actions instead if possible as campaign actions are handled in the background and not on the form submission request.
> 
> Thanks @escopecz for that recommendation, I am wondering what is the cron job command or any other action to process that "push to integration" campaign action in the Campaign Map for the background job, assuming if the top level source is assigned to campaign form (which connect to next to action item that pushes contact to integration). I tried this approach and I can see that the actions are "pending" rather than not pushing in an instant to the integration (Vtiger CRM).

I found out that if we implement the campaign map flow to the following:
1) Source form-  set to Campaign Form where the submission form is (Campaign type form)
2) Decision item - to check whether the visitor submits the campaign form defined above in the source
3) Action item - Push to integration (Vtiger)

Although the submission time improves slightly quick / less than before, it is still under 9 seconds to submit
