### ISSUE TITLE
Custom campaign decision process

### ISSUE THREAD

**Issue by PrasanthTamil** [mautic/mautic#7492]
I have created the new campaign action (ie) voicecall process..Based on the voice call result like (BUSY,NOANSWER,COMPLETED) need to proceed the another action like sending email etc.
I have added the following code on  campaignsubscriber.php.

`public function onCampaignBuild(Events\CampaignBuilderEvent $event)
{
    // Register custom action
    $event->addAction(
        'voicecall.sendobdcall',
        array(
            'eventName'       => VoiceCallEvents::ON_CAMPAIGN_TRIGGER_ACTION,
            'label'           => 'mautic.campaign.voicecall.send_obd_call',
            'description'     => 'mautic.campaign.voicecall.send_obd_call.tooltip',
            'formType'        => 'voicecall_form',
            'formTheme'       => 'MauticVoiceCallBundle:FormTheme\SubmitAction',
            'formTypeOptions' => []
        )
    );

    $event->addDecision(
        'voicecall.busy',
        [
            'label'                  => 'mautic.voicecall.campaign.event.busy',
            'description'            => 'mautic.voicecall.campaign.event.busy_descr',
            'eventName'              => VoiceCallEvents::ON_CAMPAIGN_TRIGGER_DECISION,
                'connectionRestrictions' => [
                    'source' => [
                        'action' => [
                            'voicecall.sendobdcall',
                        ],
                    ],
                ],
        ]
    );

}

public function onCallBusy(CallBusyEvent $event)
{
    $mobile  = $event->getMobile();
    $test = $this->campaignEventModel->triggerEvent('voicecall.busy',$mobile, 'voice', $event->getId());
 }
public function onCampaignTriggerDecision(CampaignExecutionEvent $event)
{
    $eventDetails = $event->getEventDetails();
    $eventParent  = $event->getEvent()['parent'];
    $eventConfig  = $event->getConfig();
    
    if ($eventDetails == null) {
        return $event->setResult(false);
    }
    //check to see if the parent event is a "send call" event and that it matches the current call busy or completed
    
    if (!empty($eventParent) && $eventParent['type'] === 'voicecall.sendobdcall') {
        // busy decision
        if ($event->checkContext('voicecall.busy')) {
            return $event->setResult(true);
        } 
    }

    return $event->setResult(false);
}`

In the above code, onCampaignTriggerDecision function is not triggered and i am not able to proceed further.kindly give your suggestion to sort out this issue

**Comment by escopecz** [comment]
Hi, I'm sorry but this is the place to write issues about Mautic. Not your custom code. I don't believe anyone else can help without the full plugin to debug what is called where. Also your code sample is very hard to read. I can give you few ideas:

1. The subscriber isn't visible for DI. Make sure you have it in a config.php file in the `'events'` section.
2. Clear the cache every time you change a config.php file.
3. Look at where the event is dispatched and debug around there.
