### ISSUE TITLE
Question: Creating a 3rd party plugin for push notifications

### ISSUE THREAD

**Issue by SpacyRicochet** [mautic/mautic#7493]
Hello all,

A quick question about sending push notifications with Mautic. If I'm correct, currently Mautic uses OneSignal under the hood to send push notifications… however, we have our own push notifications service that we use for transactional push notifications, and would like to send marketing push notifications with that as well.

Currently we're using Mautic to set up e-mail marketing campaigns, which works great, so we would like to be able to use Mautic for push as well, but without having to adopt OneSignal.

Is it possible/expected to write our own plugin to replace OneSignal for push notifications?

Thanks!

**Comment by escopecz** [comment]
Hi, yes, you'll have to write a new plugin for it. With the advantage that you can inspire how the OneSignal was written. Can't wait to see it! Good luck.

**Comment by SpacyRicochet** [comment]
Good to know! Thanks :)

**Comment by adirbnology** [comment]
any known plugin that does such thing? we are trying to follow onsesignal integration with no success

**Comment by niralmodi** [comment]
Any update - did anyone get this working successfully.

**Comment by patelvikram1974** [comment]
i have setup a campaign with web push notification using onesignal account. 
subscribe notification is coming on landing page but unable to send web notification through capmaigns.
Am i missing something

**Comment by patelvikram1974** [comment]
is there a firebase plugin to do the same in plugin
