### ISSUE TITLE
Amazon SES with SNS not working to record bounces

### ISSUE THREAD

**Issue by ankush1492** [mautic/mautic#7497]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Trying to record bounces from amazon webhook calling to mautic whenever an email bounces. If this is not workable please suggest any workable means to track bounces.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2

Steps to reproduce
1. Use Amazon SES to send email.
2. Enter IAM SMTP details in mautic configuration->email configuration
3. Configure amazon sns webhook to track bounces, https://www.mautic.org/docs/en/emails/bounce_management.html
 
### Log errors
[2019-05-05 14:02:16] mautic.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\HttpException: "Key 'Type' not found in payload " at /home/foodoutlook/public_html/mailer/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php line 116 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\HttpException(code: 0): Key 'Type' not found in payload  at /home/foodoutlook/public_html/mailer/app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php:116)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by ankush1492** [comment]
SOLVED: Let me write the solution. 

I had set up the notification to subscription in the domain setting, not in the email address from which I was shooting my mailers. I don't know if I missed that part from the guides. If you are facing the same issue check your settings in email address aswell.

**Comment by anguschang007** [comment]
> SOLVED: Let me write the solution.
> 
> I had set up the notification to subscription in the domain setting, not in the email address from which I was shooting my mailers. I don't know if I missed that part from the guides. If you are facing the same issue check your settings in email address aswell.

Do you have more detail? I am facing the same problem, but I am not sure what email address are you talking about!

**Comment by anguschang007** [comment]
The problem solved!
Don't enable the raw message when you are creating the subscription with HTTP/S.
Check the following screenshot if the description is not very clear.

https://www.dropbox.com/s/xnlnvgki2fa19ov/raw%20message.png?dl=0
