### ISSUE TITLE
Long running "sorting result" query to fetch notifications

### ISSUE THREAD

**Issue by visbits** [mautic/mautic#7504]
## Bug Description
Every SINGLE admin page load just burys our MySQL server with this query.   It takes 60-90s to complete and it makes Mautic almost unusable.    We prune our data set to 180 days via the cleanup tools but it has no affect on this.

Query:

> Sorting result | SELECT n0_.id AS id_0, n0_.type AS type_1, n0_.header AS header_2, n0_.message AS message_3, n0_.date_added AS date_added_4, n0_.icon_class AS icon_class_5, n0_.is_read AS is_read_6 FROM notifications n0_ WHERE n0_.user_id = 1 AND n0_.is_read = 0 ORDER BY n0_.date_added DESC LIMIT 200

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version |  7.0 + Opcache
| Browser | Chrome latest.

### Steps to reproduce
1. Use mautic.. 
2. Have a LOT of notifications.

### Log errors
None.

I've truncated my notifications table, this is not a fix and should be handled by cleanup...

**Comment by escopecz** [comment]
https://github.com/mautic/mautic/pull/7413 may help and we are working on another improvement, but yes, it should be maintained with the cleanup tools. Truncating the notifications table is a good tip for quick fix.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
