### ISSUE TITLE
Vtiger CRM Plugin push lead to integration affecting form submission time delay

### ISSUE THREAD

**Issue by martinduplex** [mautic/mautic#7505]
## Bug Description
I have just had another interesting finding regarding Vtiger CRM intregation plugin in Mautic.

When I add "push to integration" action option to the Mautic form to connect and merge field data from Mautic to Vtiger CRM 6.5, it increases time for submission duration time

If we push the lead information to Vtiger CRM taken fro the form fields in Mautic during form submission, the submission time takes 17 seconds to complete.

If we unpublished/disabled Vtiger CRM Integration Plugin to push and map, then submitted the form again - I noticed the submission time takes 6 seconds to complete.

Does this mean that number of mapping fields causes the database lookup query time that significantly affect Mautic performance in "fetching data from fields to match with the custom fields defined in Lead Details in Vtiger CRM 6.5"?

Your opinion is greatly appreciated, many thanks.

| Q   | A
| Mautic version | v2.14.2
| PHP version | 7.1
| Browser | Google Chrome 74.0.3729.131 

### Steps to reproduce
1. Enable Vtiger CRM Plugin via Plugins module, authorise to connect to CRM (filling in CRM URL, username and access key) then mapping fields to CRM fields (there are about 34 fields in Vtiger Lead Details fields) and select contact as the source to pull data
2. Go to existing form in Mautic, click dropdown arrow to preview the form
3. Fill in the fields and submit form
4. The button changes state from "Please wait..." to Submit in about 17 seconds upon successful submission

### Log errors
 mautic.NOTICE: PHP Notice - Array to string conversion - in file /home/x/public_html/mautic/app/bundles/CoreBundle/Views/FormTheme/Custom/widget_attributes.html.php - at line 16 [] [] ?

**Comment by escopecz** [comment]
It's not doing a lookup but it simply pushes the contact created/updated by the form to Vtiger. It takes 11 seconds in your case. Maybe dig a little why Vtiger is so slow. Also check if the push to integration (Vtiger) isn't available as a campaign action. If you could move it to a campaign than the form submission would be faster as campaigns execute actions with a background job.

Let us know if this helped, please.
