### ISSUE TITLE
Campaign won't resume after being turned off

### ISSUE THREAD

**Issue by goranculibrk** [mautic/mautic#7508]
## Bug Description
Hi there, my client has accidentally turned off the campaign that was published and running.
After switching on the campaign, nothing happens. There were scheduled emails two days after the client turned off and back on with existing contacts in it. But campaign:update or campaign:trigger are not doing anything.

Is that expected behavior and the campaign will work only for new contacts or it's an issue?

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.0.33
| Browser | Chrome latest

### Steps to reproduce
1. create the campaign with scheduled emails
2. turn off the campaign
3. turn on the campaign
4, check if emails will be sent
 
### Log errors

There are no errors in the log.

**Comment by RCheesley** [comment]
@goranculibrk is this still an issue with the latest version of Mautic?
