### ISSUE TITLE
API authorization denied.

### ISSUE THREAD

**Issue by skiod** [mautic/mautic#7509]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | 

## Description:
The more details the better...

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 
Hi, I tried to make a sample auth but it throw always this error 

```
code: 401,
message: "The response has unexpected status code (401). Response: {"errors":[{"message":"API authorization denied.","code":401,"type":"access_denied"}],"error":"access_denied","error_description":"API authorization denied. (`error` and `error_description` are deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)"}"
```
my code : 
```
 $apiUrl = "https://mautic.domain.com";

        $settings = array(
            'AuthMethod'       => 'BasicAuth', 
            'userName'         => 'username',
            'password'         => 'password',        
            'apiUrl'           => 'https://mautic.domain.com',         
        );
       
       
       try {
           // Initiate the auth object specifying to use BasicAuth
           $initAuth = new ApiAuth();
           $auth = $initAuth->newAuth($settings);
           
           if ($auth) {
               $api = new MauticApi();
               $contactApi = $api->newApi('contacts', $auth, $apiUrl);
               // Get Contact list
               $results = $contactApi->getList();
               return ($results);
           } else {
               echo "Something went wrong!";
           }
       } catch (Exception $e) {
           echo "Mautic not connected!";	
       }

```
thank you

**Comment by Woeler** [comment]
Did you:
- Turn on the API?
- Specifically permit BasicAuth (it's a separate setting)?
- Clear your caches completely?
