### ISSUE TITLE
2.15.1 : campaign emails not sent

### ISSUE THREAD

**Issue by captainlegrand** [mautic/mautic#7516]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

Hi,
This is my first contribution :) I discovered Mautic about 10 days ago and I find it absolutely brilliant. I am using it in a business project that I am developing. I think I stumbled upon an issue that could be a bug. I have reviewed related issues and troubleshooting, but no luck.

My setup:
- Mautic is running on a domain with a **.army extension** (just in case a less traditional extension would be important)
- It is a clean **2.15.1** install (done twice, just in case)
- I am using **Mailjet** to send emails

Basically, **campaign emails are just not sent**. All other emails are going fine (test emails, segment emails, emails after form completion).

I have reviewed all related issues and tried a number of things. In the end, I created a segment with just 2 contacts, and a campaign that just sends an email without any other decision condition / action. The campaign runs fine, but e-mails simply do not go. 

What I have tried
- reverting to PHP 7.0: no effect
- queuing vs immediate sending of emails: no effect
- transaction vs marketing emails: no effect
- Mailjet vs PHP Mail vs sendmail: no effect

I have also tried 'debug' => true temporarily, but there were no errors in the resulting logs.

If there is anything else I can try, or any info I can supply, I'll be happy to!

Thanks in advance,
Steph.

| Q   | A
| --- | ---
| Mautic version | 2.15.1 
| PHP version | 7.2
| Browser | Google Chrome

### Steps to reproduce
1. Create a campaign on a segment
2. Send email
 
### Log errors

`[2019-05-11 06:09:58] mautic.NOTICE: Swift_TransportException: Connection could not be established with host in-v3.mailjet.com [Connection refused #111] (uncaught exception) at /home/www/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php line 268 while running console command `mautic:emails:send` [] []
`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Thanks for the amazing report and all the things you've tried!

Since Mautic uses the same methods to send emails from campaigns, segments, forms and other places, I can't think of a reason why campaigns aren't sending. Try to clear cache. Like really go to the app/cache/prod folder and delete everything in it. The error you posted would suggest that no emails are going out through mailjet. Also double check that all the cron jobs are running properly.

**Comment by captainlegrand** [comment]
Thank you for your feedback :)

Actually cron jobs were not running properly (due to a php version mistake in my environment), although I was running the commands manually, and I thought it would have the same effect for testing purposes.

Now cron jobs are running properly, and campaign emails started going normally about 1 day later. So, sorry for calling this a bug.

I am still checking a few things that I'm not sure about with campaigns, but again I find Mautic brilliant, and I am definitely going to follow what's happening here.

**Comment by jason-yankee** [comment]
Mautic seems to loop when creating initial email.
