### ISSUE TITLE
[UI Enhancement] Split "New" button into two on "Manage Emails" page

### ISSUE THREAD

**Issue by dobesv** [mautic/mautic#752]
Currently on "Manage Emails" you can click "New" to add an email, then it asks you what kind of email to create - Template or List - in a modal dialog.

This would be streamlined if there were simply two buttons, "New Template Email", "New List Email".

They could have a helpful tooltip or (?) icon to explain the difference.

**Comment by escopecz** [comment]
Closing as part of "old issue closing" process as there hasn't been anyone else requesting/voting for  this change.
