### ISSUE TITLE
Custom dropdown in leads not pre-selected on load

### ISSUE THREAD

**Issue by Celoain** [mautic/mautic#7523]
## Bug Description
We updated our Mautic Instance from 2.14.2 to 2.15.1 and since then, when editing a lead, all custom selects are without pre-selection. We are able to save the lead and the change obviously gets saved. But when reopening the lead for another edit, the saved data doesn't seem to be loaded and the values are overwritten.

| Q   | A
| Mautic version | 2.15.1
| PHP version | 7.0
| Browser | any

**Comment by escopecz** [comment]
What happens between you save the contact with some dropdown values and when you notice the values are gone? I cannot reproduce it.

**Comment by Celoain** [comment]
Nothing happens at all. After i save the contact i reopen the page and have the default values selected again.

**Comment by escopecz** [comment]
Could you check the logs? It seems the save does not work.

https://www.mautic.org/docs/en/tips/troubleshooting.html

**Comment by Celoain** [comment]
I followed every step on the troubleshooting page. Logs are empty. I startet to try to figure out a bit about the problem myself and was able to see that the value is actually being saved. It's just not selected in the form after a reload.

**Comment by escopecz** [comment]
I simply cannot replicate. The selected options stick no matter how badly I try not to.

**Comment by Celoain** [comment]
Did you try a boolean? I just saw that all of our custom options are booleans. Just created a text based and it worked. Just the booleans won't.

**Comment by escopecz** [comment]
Booleans holds the value for me too.

**Comment by Celoain** [comment]
I tried to figure out at which point the data gets "lost". I can see that the entity is actually loading the data but the form is not preselecting. I'd be happy with any hints on how to further debug this.

**Comment by RCheesley** [comment]
@Celoain is this still an issue with the latest version of Mautic?
