### ISSUE TITLE
It is not possible to mark a lead as "Do not contact"

### ISSUE THREAD

**Issue by aristidesneto** [mautic/mautic#7526]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
It is not possible to mark a lead as "Do not contact". When performing this procedure nothing is done.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2
| Browser | Checked in latest version Firefox and Chrome

### Steps to reproduce
1. Click to edit a lead and click Preferences on the arrow next to Close.
2. Check or uncheck the Email option and click Save.
 
### Log errors
Does not contain

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
It works for me. You can't see the Do Not Contact label bellow the contact avatar after you save the preferences with unchecked email channel?
![Screenshot 2019-05-17 at 15 12 32](https://user-images.githubusercontent.com/1235442/57930438-48aa1d80-78b6-11e9-97ed-58de04cb6459.png)

**Comment by aristidesneto** [comment]
> It works for me. You can't see the Do Not Contact label bellow the contact avatar after you save the preferences with unchecked email channel?
> ![Screenshot 2019-05-17 at 15 12 32](https://user-images.githubusercontent.com/1235442/57930438-48aa1d80-78b6-11e9-97ed-58de04cb6459.png)

It does not work for me. Neither to mark or unmark. I need to go straight into the database and insert a record into the responsible table. The system does not work. I have no idea why it does not work. No log error, I already tested it in various browsers, anonymous tab, etc.

**Comment by npracht** [comment]
I also cannot reproduce

**Comment by sbolinches** [comment]
The same problem as @aristidesneto. Uncheck email channel not function. And it's not shown "Do not contact" label 
Mautic 2.15.1
PHP Version  7.1

**Comment by aristidesneto** [comment]
I found the option to mark as "Do not contact" in the menu when selecting a lead. See the picture. Doing it works that way. I do not remember if this option is old, but only now that I have seen it.

![Captura de tela de 2019-05-20 08-22-41](https://user-images.githubusercontent.com/6685135/58018418-1e847580-7ad9-11e9-9952-6fa24eb1d7e9.png)

**Comment by sbolinches** [comment]
Thanks. The option option to Do Not Contact in General CRM run fine to me in Mautic 2.15.1 xD

**Comment by AndrassGray** [comment]
So I can unsubscribe a user (uncheck the email channel) in his Contact Preference Center, but can't re-subscribe him there by checking the email channel.

No log entries.

**Comment by npracht** [comment]
Hi there,

Could someone share a clear **How to reproduce** procedure ?

**Comment by dichvuhuuich** [comment]
> Hi there,
> 
> Could someone share a clear **How to reproduce** procedure ?
1. Go to a contact, go to Preferences of this contact like picture 1
![Mautic-Preferences](https://user-images.githubusercontent.com/4901985/61788683-ea149900-ae3c-11e9-9c2b-c4f2a276a200.JPG)

2. Uncheck tick before email, click save
![Mautic-Untick-email](https://user-images.githubusercontent.com/4901985/61788713-fac50f00-ae3c-11e9-931b-1b87f2fc33f1.JPG)

3. Go to Preferences again, tick still here

**Comment by npracht** [comment]
do you have an error in your browser console when clicking or display the window?

**Comment by aristidesneto** [comment]
> do you have an error in your browser console when clicking or display the window?

Hi, sorry for the delay in responding, I reproduce the steps I mentioned in the ticket opening and today in version 2.15.2 the error no longer happens. It's working as expected.
