### ISSUE TITLE
dwc initial call replies with http status 204 (no content) if using RabbitMQ

### ISSUE THREAD

**Issue by lavita-it** [mautic/mautic#7528]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
We are using RabbitMQ message queue and created dynamic web content. The initial call https://domain.com/dwc/dwc-name?etc replies with 204 (no content). When using the reload button in the browser, the content is shown. Same is, when dwc link is directly opened in browser.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2.13
| Browser | all

### Steps to reproduce
1. Configure Mautic to use RabbitMQ message queue
2. Create DWC component (not campaign based)
3. Integrate div into 3rd party website (separate domain)
4. Open site - no content shown, console shows 204.
5. Reload site - content is shown
 
### Log errors
no errors in logfile

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by yonnath** [comment]
Same issue here. Very similar to this one: https://github.com/mautic/mautic/issues/4061 no?

**Comment by RCheesley** [comment]
Closing in favour of #4061 - feel free to re-open if this is a distinct issue!
