### ISSUE TITLE
Contact overwritten with other contact information

### ISSUE THREAD

**Issue by quintmouthaan** [mautic/mautic#7532]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.25
| Browser | Chrome

### Steps to reproduce
1. I have tracking settings configured to anonimyze IP and all other tracking methods disabled
![image](https://user-images.githubusercontent.com/39469362/57766093-08f10380-7707-11e9-92b9-266d00a029e0.png)

2. Users are using our website and Mautic is tracking their behaviour
3. One of our contacts is being overwritten with data from another contact without clear reason why.
![image](https://user-images.githubusercontent.com/39469362/57766323-7866f300-7707-11e9-92f7-8906ed4cda3a.png)

The two users do not know each other and have never logged in from the same device.
The only explanation I can think of is that Mautic gets confused because we are also updating two custom contact fields from our backend. 

This is a critical issue for us since we don't know if this happens to more users and Mautic might now be sending mails to the wrong users. Any help or pointers to what the issue might be are very welcome!
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
What does this mean?

> Mautic gets confused because we are also updating two custom contact fields from our backend.

I'm afraid you'll have to try to replicate it so we'd understand how it happens and then we will be able to fix it.

If you cannot tell from the Mautic UI then good resource is the audit_log database table where you can see what fields were changed. Then check the events. Is there some event that happened at the same time?
