### ISSUE TITLE
Read ratio not updating in reports after changing date

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#7533]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When you create an email report with read ratio stat in data, the read ratio don't change when you modify the date of the report. All others stats are updated. It happen with a dynamic filter on mail ID

| Q   | A
| --- | ---
| Mautic version | 2.15.0 - 2.15.1
| PHP version | 
| Browser | Chrome
### Steps to reproduce
You must have an instance with at least one email send to several contacts, on multiple days if possible.
1. Create an email (data sources) report with at least read ratio in the columns
2. Add a dynamic ID filter so you can select one email
3. Check the read ratio statut with one range of date
4 Modify the date to have differents numbers for the mail in the report
5 See that the read ratio number is always the same
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Please fill in Mautic version

**Comment by npracht** [comment]
2.15.0 - 2.15.1

**Comment by kuzmany** [comment]
This is related to PR https://github.com/mautic/mautic/pull/7214 and last commit should fixed it https://github.com/mautic/mautic/pull/7214/commits/7c36344e737b61b08c41ca5a723ce0495890045a
