### ISSUE TITLE
View Email Online "{webview_url}" Images are Broken

### ISSUE THREAD

**Issue by ericross** [mautic/mautic#7537]
The view Online link in emails does not show images.

See example:
https://tellone.org/mail/email/view/5cda7c6e6913e994448489

In the builder, the code is:
`<div` data-empty="true">View this <a href="{webview_url}" style="text-decoration: underline;" `target="_blank">Online</a>`

| Mautic version | 2.15.1 
| PHP version | 7.1.14
| Browser | Firefox Quantum 66.0.5 (64-bit)

### Steps to reproduce
1. Email is sent through Channels Email 
2. Reading email in browser Gmail client
3. Click on the View this [Online](https://tellone.org/mail/email/view/5cda7c6e6913e994448489) link
4. Email opens in a new browser tab showing alt-text for images
 

No Errors:
Today's Mautic error log is empty. Check server error log for error messages Mautic didn't have a chance to catch.

**Comment by escopecz** [comment]
I can see that the src is not showing the path to the image but something weird:

`<img src="cid:8433c4de54e43ab10db2cfdc704b6a4b@tellone.org" ...`

Any idea what it could be? Do you have the Base64 option turned on?
![Screenshot 2019-05-17 at 15 34 42](https://user-images.githubusercontent.com/1235442/57931724-5f05a880-78b9-11e9-8bb5-e3b530bcebd7.png)
