### ISSUE TITLE
S3 file not downloading

### ISSUE THREAD

**Issue by Mindbowser** [mautic/mautic#7542]
Using latest Mautic version 2.15.1, I have uploaded publicly accessible files on S3 and attached it to mautic form submission. When form is submitted its not downloading the file whereas if I use local file its working fine.

I inspected the browser page and found that S3 file is properly shown with 200 status but browser not showing as downloading, thoughts?

**Comment by RCheesley** [comment]
Is this still an issue with the latest version @Mindbowser ? Did you see any errors in the logs at all?
