### ISSUE TITLE
[Editor Bug] Email composer inserts extra space at the top of the message each time I edit it.

### ISSUE THREAD

**Issue by dobesv** [mautic/mautic#755]
The email composer inserts extra space at the top of the message each time I edit / save it, after a couple of edits.

Steps to reproduce:

1. Manage Emails
2. New
3. List
4. Subject: Test Spaces
5. Internal Name: Test Spaces
6. Body: Test
7. "Save and Close"
8. "Edit"
9. "Save and Close"
10. "Edit"
11. "Save and Close"
12. "Edit"

Bug: Now each time I return the editor a new blank line is added to the beginning of the message.  Also, the HTML structure of the document becomes kind of screwy

First edit:

```
<html>
<head>
	<title></title>
</head>
<body>
<p>test</p>
</body>
</html>
```
Second:

```
<html>
<head>
</head>
<body></body>
</html>
<p><br />
<title></title>
</p>

<p>test</p>
```

Third:

```
<html>
<head>
</head>
<body>
<p>&nbsp;
<p></p>
</p>
</body>
</html>
<p><br />
<title></title>
</p>

<p>test</p>
```

Fourth:

```
<html>
<head>
</head>
<body>
<p></p>

<p></p>

<p></p>

<p></p>
</body>
</html>
<p><br />
<title></title>
</p>

<p>test</p>
```

This seems to indicate that the rich text editor is mangling the markup somehow.

If I delete the leading paragraphs, the text stabilizes like this:

```
<html>
<head>
</head>
<body>
<p>test</p>
</body>
</html>
<title></title>
```

Having applied this "workaround" I can now do the save / edit loop and no any extra spaces are added to the top of the email body.

However, the HTML is still a bit weird looking.

OS: Windows 8
Browser: Chrome Version 44.0.2403.125 m (64-bit)

**Comment by different-thinking** [comment]
Same at my side!

**Comment by BartKaminski** [comment]
Same problem
