### ISSUE TITLE
Thunderbird Plugin

### ISSUE THREAD

**Issue by AndrassGray** [mautic/mautic#7550]
Would it be possible to create a Thunderbird addon and Mautic plugin? Why should Gmail & Outlook users have all the fun? :D

**Comment by RCheesley** [comment]
Sounds great, here's a feature on the forum, please upvote/discuss there and we can re-open this if/when there is potential for development: https://forum.mautic.org/t/mozilla-thuderbird-integration/6885

**Comment by nithin933** [comment]
https://github.com/nithin933/thunderbird-mautic-helper this works for now
