### ISSUE TITLE
segment permission contactgrid error

### ISSUE THREAD

**Issue by pety-dc** [mautic/mautic#7551]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
A user that has no segment permissions checked (View Others, Edit Others, Delete Others, Full) still has permission to create segments for his own purposes. (Also has permission to create it public) but can't see other users' not-public segments.

When a user with such limited permissions regarding segments creates a new segment and opens it to view an error is generated at the bottom of the page where contact grid should be.

![FireShot Capture 079 - View - petydemoproba_public - KIAZAKI - automation mp d-code hu](https://user-images.githubusercontent.com/25766885/58177035-e1201380-7ca3-11e9-8e47-45358737a69c.png)

If I reload the page I get "Tsk tsk. Apparently you don't have access to this area."

![FireShot Capture 080 - petydemoproba_public - Forbidden - demo leadengine hu](https://user-images.githubusercontent.com/25766885/58177137-1298df00-7ca4-11e9-8a1a-0795e01b8a22.png)

Apparently the error is due to the following chain: 
`ListConstoller::viewAction` partially forwards the request to `ListConstoller::contactsAction` which returns the `EntityContactsTrait::generateContactsGrid` with the `lead:lists:viewother` as a required permission:

```
return $this->generateContactsGrid(
            $objectId,
            $page,
            'lead:lists:viewother',
            'segment',
            'lead_lists_leads',
            null,
            'leadlist_id',
            $listFilters
        );
```
The `EntityContactsTrait::generateContactsGrid` checks if the required permission is granted and returns `$this->accessDenied();` if not.

Problems:
1.) The access denied response from the contactGrid sometimes causes the header buttons (Edit, Close, etc) not to appear. 
2.) A user that has permission at least to view his own contacts should be allowed access to the contacts grid. In fact I can't figure out why `lead:lists:viewother` permission is required for the contacts grid, instead of  `lead:leads:viewown` and/or lead:leads:viewothers. Afterall the contacts grid shows contacts, it should be visible if the user has permission to view contacts. It's strange.
3) I'm not sure, but it seems that the contactGrid doesn't filter contacts based on wthether the user has permission to view own, or others' contacts

I would like some advice to see what the design concepts were regarding the permission check of contactGrid

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2.X
| Browser | 

### Steps to reproduce
1. Create role for a user with no segment permissions
2. Create a new segment with that user
3. Open the segment for view
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by pety-dc** [comment]
Hey @npracht @escopecz 

Could you please advise me on this matter?

**Comment by npracht** [comment]
Hi @pety-dc, I didn't try to reproduce but your bug report is complete so i believe that's a real bug.
What can i do for you?

**Comment by pety-dc** [comment]
Well, I would like to fix the bug, but I'm unsure what the design concepts were regarding the permission requirements of the contactgrid.

**Comment by RCheesley** [comment]
Closing this issue due to a lack of recent engagement and both related PR's being closed for inactivity. If anyone wishes to re-open please create a new issue with a link to this one, or request the PR's be re-opened.

**Comment by huhongbo** [comment]
the bug has still existed in the newest version.
