### ISSUE TITLE
Hubspot - Not sync new field

### ISSUE THREAD

**Issue by comunidademagento** [mautic/mautic#7553]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
We create the field "Curso Online" in Mautic.
https://i.imgur.com/hOioO7s.png

We create the field "Curso Online" in Hubspot.
https://i.imgur.com/gNkEJLm.png

We associate boths fields in Mautic Plugin Hubspot.
https://i.imgur.com/lb3nnGP.png

But, not send this information registered in Mautic to Hubspot.
https://i.imgur.com/PK0Y0PF.png
https://i.imgur.com/gNkEJLm.png

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.0
| Browser | Google Chrome

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by comunidademagento** [comment]
![image](https://user-images.githubusercontent.com/7476455/58293820-81a62e80-7d9d-11e9-86ed-95da89fc461a.png)

**Comment by comunidademagento** [comment]
[2019-05-23 20:44:32] mautic.NOTICE: PHP Notice - Undefined index: properties - in file /home/225851.cloudwaysapps.com/pbemstzhfa/public_html/app/bundles/FormBundle/Views/Field/field_helper.php - at line 33 [] []
[2019-05-23 20:44:35] mautic.NOTICE: PHP Notice - Undefined index: properties - in file /home/225851.cloudwaysapps.com/pbemstzhfa/public_html/app/bundles/FormBundle/Views/Field/field_helper.php - at line 33 [] []

**Comment by valderes-upflux** [comment]
Hi @comunidademagento. How are you? Nice to see you heere. In my case, in Mautic interface, my custom fields are not showing at the map fields "window".

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
