### ISSUE TITLE
Problem with sending an email to correct company based on company custom field

### ISSUE THREAD

**Issue by pilievwm** [mautic/mautic#7554]
BUG: 
If there are two or more companies and use a campaign to send emails based on company custom fields the system sends email based on the data recorded into the primary company.

Example:
We have Company A and Company B. 
We have a custom company filed called: Payment status
We have a segment based on the Payment status field
Company A is a primary company

When a form is submitted with information regarding the payment status for Company B, the contact is added to the correct segment, then the campaign is started corectly and it sends an email to the contact with data related to the **primary company - Company A**.

It turns out that the emails are not relevant to the actions and are not adequate because we want to notify the contact that there is a problem with the payment for Company B!

**Comment by goranculibrk** [comment]
Hi there, 
I started facing the same issue. Contact have multiple companies, but email tokens like {contactfield=companyname} only pulls primary company. 
Was there any progress regarding this?

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by goranculibrk** [comment]
Hi @npracht 
I've just managed to test it on 3.1.0

The issue still persists. 

Steps to reproduce:
1. Create custom field for Company named usage percentage (you can name it whatever you want, it's used for segmenting)
2. Create two companies **(Company A and Company B)** and assign one contact to both of them. Primary company should be **Company A**.
3. Create segment with filter based on custom field created in step 1. In my case, I'm using 80 as usage percentage for the segment to filter out companies that are near their limit of usage.
4. Update custom field from step 1 in **Company B** with value that will match the segment filter. (Usage percentage = 80)
4. Create email that will contain tokens `{contactfield=companyname}` and `{contactfield=f_usage}` (in my case the sentence in email looks like this: "The {contactfield=companyname} has spent {contactfield=f_usage}% of the limit. Consider upgrading your account.")
5. Create campaign with source segment from step 3. that will send email we created in step 4.
6. Run the campaign

The expected value in the email sent to the contact is: The **Company B** has spent **80%** of the limit. Consider upgrading your account.

However, the email contact receives is this: The **Company A** has spent **%** of the limit. Consider upgrading your account.

Not the company or the custom field is added properly to the emails.

**Comment by npracht** [comment]
@goranculibrk thanks a lot for your feedback ! Happy to re-open the issue then.

**Comment by richardriman** [comment]
I'm on version 4.0.1 and this problem still persist.
