### ISSUE TITLE
Email Render Issue

### ISSUE THREAD

**Issue by otsang** [mautic/mautic#7557]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? |  Y
| Feature request? | N
| Enhancement? |  N

## Description:
HTML email suddenly breaks after div line for an email that's been running since 2017 without fail. I tried reproducing the error outside of Mautic in an email rendering platform, and I was unable to reproduce the error which leads me to believe that Mautic may possibly be stripping out something in the code.

Image of email coming out of Mautic when HTML is added into code-only mode:
![Email Broke](https://user-images.githubusercontent.com/45982673/58275959-15024400-7d4b-11e9-9926-e00eef08369b.png)

Image of email from email rendering platform when HTML is added into said platform to conduct further testing:
![Gmail Rendering](https://user-images.githubusercontent.com/45982673/58275702-91485780-7d4a-11e9-8295-b41fefcadfa2.png)

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.15.1
| PHP version | PHP Version 7.0.33
--

### Steps to reproduce:
1. HTML code-only was sent through a live test to email.
2. HTML code-only email renders with breaks.
3. HTML code added into email rendering platform to conduct testing.
4. Could not replicate same breaks that are occurring when email is sent from Mautc.

**Comment by escopecz** [comment]
Please provide HTML of the original email and after it's saved in Mautic.
