### ISSUE TITLE
Contact merge deletes device records and invalidates sessions

### ISSUE THREAD

**Issue by pjeby** [mautic/mautic#7559]
## Bug Description
When two contacts are merged, the device tracking data (in `lead_devices`) is deleted for the "loser" of the merge.  This invalidates any active sessions for the "loser" lead, causing all of those devices to create new anonymous leads on their next hit.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1
| Browser | Any

### Steps to reproduce
1. Create an identified contact
2. Create a new anonymous contact by browsing a tracked page in a test browser.  Take note of the document.cookie `mtc_id` value
3. Merge the second contact into the first (e.g. by adding an email address) in the Mautic UI or via the API
4. Refresh the same tracked page in the test browser and observe that `mtc_id` has changed, and a new anonymous contact has been created, because the old device records were deleted.
 
### Log errors
N/A

### Analysis
The `ContactMerger` class does not take any action to update the `lead_id` fields of existing `lead_devices`, and the device tracker lacks an event listener or `updateLead()` method for merging them.

**Comment by escopecz** [comment]
Try to test https://github.com/mautic/mautic/pull/7717 if it fixes this issue, please.

**Comment by pjeby** [comment]
@escopecz: #7561 is already tested as correcting this issue, while #7717 does not appear to do anything about the merging of lead devices, which is what this issue is about.  #7717 only deals with the process of merging *fields*, and this issue is about devices.

**Comment by pjeby** [comment]
Why is this issue being closed?  As noted above, #7717 only deals with *field* merging, not *device* merging.  I do not see any code in either the 2.x or 3.x branches to handle device merging, ala #7561.

**Comment by npracht** [comment]
sorry i misunderstood your message.

**Comment by npracht** [comment]
@pjeby can you answer that message? https://github.com/mautic/mautic/pull/7561#issuecomment-631370559
