### ISSUE TITLE
Display concise error messages in contact event list

### ISSUE THREAD

**Issue by supercosh** [mautic/mautic#7562]
Sometimes it may happen that automated events are not executed, for various reasons. The first places to check are the notifications in Mautic, or the event list in the contact. An exlamation mark in the event list entry shows that something went wrong. Hovering the exclamation mark shows a generic message like "This event encountered an error during the last attempt to process.".

Now it would be helpful, if the message would be appended with some more information, which for instance is found in the table campaign_lead_event_log in the metadata column. In LeadSubscriber->addTimelineEvents() I found the code which would write the event logs, it seems to me, from this table, into the timeline.

This feature request may help new users to find problems much faster (in my case it was a non-activated email template, which prevented the action from being executed).

**Comment by RCheesley** [comment]
@supercosh would you be up for making a PR to add this functionality?

**Comment by Vartkat** [comment]
1 up on this one. 
I also got the exclamation and thanks to this request I know now where to look, in the database but my regular users won't go there.

**Comment by supercosh** [comment]
> @supercosh would you be up for making a PR to add this functionality?

Unfortunately I'm not enough familiar about the Mautic Code to provide a patch for this. I would be happy if someone could implement this with the help of my above information.
