### ISSUE TITLE
Popup windows are out of the browser

### ISSUE THREAD

**Issue by anaribas** [mautic/mautic#7564]
## Bug Description
When you want to edit a section of a newsletter that we have placed in the templates, the popup is out of the browser and users do not know how to save the changes.

Also, would it be possible to expand the editing section and reduce the width of the display section?

Mautic version 2.15.1
PHP version 7.1.20
Browser Chrome and Firefox

**Comment by escopecz** [comment]
Could you please make a screenshot and drag&drop it here to the comment textarea?

**Comment by anaribas** [comment]
The  test is done with Chrome Version 75.0.3770.80
Here you are the image:
![image001](https://user-images.githubusercontent.com/11192435/59263438-59457d80-8c41-11e9-9654-8189576fcd55.png)

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
