### ISSUE TITLE
Random 404s from scanning bots create contacts only in segment with tag exclusion filter

### ISSUE THREAD

**Issue by aspiers** [mautic/mautic#7565]
## Bug Description

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.27
| Browser | Chrome 71.0.3578.98

### Steps to reproduce

1. Create fresh installation which is directly accessible from the internet
1. Create a couple of tags
1. Create a segment with a filter which excludes those tags
1. Wait a few hours for bots which scan for security vulnerabilities to find the IP and start their attacks, filling the logs with 404s
1. Wait for the next `mautic:segments:update` cron job to run

### Observed results

The contacts get added to the segment by the cron job, e.g.:

        mautic_1  | [CRON] Rebuilding contacts for segment 2
        mautic_1  | [CRON] 213 total contact(s) to be added in batches of 300
        mautic_1  | [CRON] 0/213 [>---------------------------]   0%
        mautic_1  | [CRON] 21/213 [==>-------------------------]   9%
        mautic_1  | [CRON] 42/213 [=====>----------------------]  19%
        mautic_1  | [CRON] 63/213 [========>-------------------]  29%
        mautic_1  | [CRON] 84/213 [===========>----------------]  39%
        mautic_1  | [CRON] 105/213 [=============>--------------]  49%
        mautic_1  | [CRON] 126/213 [================>-----------]  59%
        mautic_1  | [CRON] 147/213 [===================>--------]  69%
        mautic_1  | [CRON] 168/213 [======================>-----]  78%
        mautic_1  | [CRON] 189/213 [========================>---]  88%
        mautic_1  | [CRON] 210/213 [===========================>]  98%
        mautic_1  | [CRON] 213/213 [============================] 100%
        mautic_1  | [CRON] 0 total contact(s) to be removed in batches of 300
        mautic_1  | [CRON] 213 contact(s) affected

After this happened a few times, visiting https://my.mautic.site/s/segments shows `View 286 Contacts` in the `# contacts` column.

This is the first issue, although I believe this was already reported in 2015 in issue #1060.  However there is an additional problem:

When clicking on that to view contacts using a `segment:my-segment-alias` filter, it shows:

    No Results Found

    Seems there are none! Try changing a filter (if applicable) or how about creating a new one?

Similarly, when visiting https://my.mautic.site/s/contacts without a filter, it only shows valid contacts, and none of these spammer contacts.

Despite this, individual contacts can be seen by clicking on the segment view, which goes to a URL like https://my.mautic.site/s/segments/view/1, and then they are all listed at the bottom of the page under the `Contacts` tab.

### Expected results

404 hits from previously unrecognised sources do not add any contacts to the database, because this is just inevitable background noise suffered by every website out there on the internet.

In contrast, there *is* value in tracking 404 hits from previously *recognised* sources, since this could yield valuable information about legitimate, well-intentioned visitors hitting broken links.

### Initial debugging

I enabled the MySQL query log:

    set global general_log=on;

and then visited https://my.mautic.site/s/contacts to reverse-engineer how Mautic compiles the list of contacts to display.  AFAICS, it's using this query:

    SELECT l.* FROM leads l LEFT JOIN users u ON u.id = l.owner_id WHERE l.date_identified IS NOT NULL ORDER BY l.last_active DESC LIMIT 30 OFFSET 0

and indeed the `date_identified` field being `NULL` is what distinguishes the genuine contacts from the spam ones which are polluting the database:

    mysql> select isnull(date_identified), count(isnull(date_identified)) from leads group by isnull(date_identified);
    +-------------------------+--------------------------------+
    | isnull(date_identified) | count(isnull(date_identified)) |
    +-------------------------+--------------------------------+
    |                       0 |                              1 |
    |                       1 |                            288 |
    +-------------------------+--------------------------------+
    2 rows in set (0.00 sec)

How can we progress this to a fix?

It's worth noting that only segments which have this tag exclusion filter get polluted.

**Comment by aspiers** [comment]
A further problem is that there is no obvious way to clean things up by removing the fake contacts from the segment, since they don't appear in any list in the UI which allows bulk editing of any kind.

One possibility would be to write a script using the API, but even [the API only lets you remove contacts from segments one by one](https://developer.mautic.org/#remove-contact-from-a-segment).  I guess I'll just risk doing

    delete from lead_lists_leads where leadlist_id=X`

but that's obviously pretty evil due to bypassing the ORM layer altogether.

**Comment by escopecz** [comment]
Please read about visitors vs contacts: https://www.mautic.org/docs/en/contacts/index.html#visitors-formerly-anonymous-leads. Mautic tracks anonymous contacts (visitors) and all their activity. Once those contacts submit a form or do some action that makes them identified contacts then you'll see also the history of their actions before they became identified. That's quite valuable information. Those are not spam contacts. 

If there is need for disabling tracking of 404 pages, then I suggest to create a new option in the configuration that would allow to disable it. Or track only known contacts. I'm fine with both. It must track 404 by default to avoid a BC change.

**Comment by aspiers** [comment]
[**@escopecz**](https://github.com/escopecz) commented on [May 28, 2019 8:49 AM](https://github.com/mautic/mautic/issues/7565#issuecomment-496404802 "2019-05-28T07:49:24Z - Replied by Github Reply Comments"):
> Please read about visitors vs contacts: [mautic.org/docs/en/contacts/index.html#visitors-formerly-anonymous-leads](https://www.mautic.org/docs/en/contacts/index.html#visitors-formerly-anonymous-leads).

Thank you, that's very helpful!  I hadn't found that page yet.

> Mautic tracks anonymous contacts (visitors) and all their activity. Once those contacts submit a form or do some action that makes them identified contacts then you'll see also the history of their actions before they became identified. That's quite valuable information. Those are not spam contacts.

Yes indeed, I entirely agree in the cases that valid pages are hit, and also even in the case where 404s are hit by known contacts (because that gives useful data on broken links).

> If there is need for disabling tracking of 404 pages,

The only users unaffected by this problem of noise from bots would be those who don't expose their mautic web interface to the internet.  And I presume that will be a minority of users, since they would not be able to use landing pages, forms, or allow their contacts to view web-based versions of emails, and probably several other web-based features I can't immediately think of.

So yes, it really seems to me like there is a significant need.  In fact, I'd flip the question round and ask: who *wouldn't* need to disable tracking of 404s triggered by unknown visitors?  Maybe I'm missing something.

Having said that, if the *only* undesirable side-effect of tracking 404s triggered by anonymous visitors is that they get added to segments which have tag exclusion filters but no inclusion filters, then maybe it's enough to fix the mechanism which adds them to those segments?

> then I suggest to create a new option in the configuration that would allow to disable it. Or track only known contacts.
>
> I'm fine with both. It must track 404 by default to avoid a BC change.

OK thanks.  Yes, an option sounds good if a fix focused purely on segment membership isn't sufficient.  IMHO the behaviour change would need to be specifically for 404s generated by *unknown* contacts (standard contacts or visitors), not *all* 404s.

Personally to me this seems like a big enough problem that it would be worth a behavioural change to fix it by default in *new* deployments of Mautic, at least.  I'm not sure why anyone would want to preserve the existing behaviour, but if there are good reasons for that then the upgrade path could ensure that the option gets set to track 404s by default when upgrading an existing deployment.

I'm totally new to the codebase, so please forgive the newbie question, but am I right in thinking that this is the code which triggers tracking of hits from random bot scans of paths like `/hell.php`?

https://github.com/mautic/mautic/blob/0bfb1c6bec7896cb108d6ef11b1c23a85a3ccb90/app/bundles/PageBundle/Controller/PublicController.php#L293

and this invokes `hitPage`:

https://github.com/mautic/mautic/blob/0bfb1c6bec7896cb108d6ef11b1c23a85a3ccb90/app/bundles/PageBundle/Model/PageModel.php#L462

which invokes `processPageHit`:

https://github.com/mautic/mautic/blob/0bfb1c6bec7896cb108d6ef11b1c23a85a3ccb90/app/bundles/PageBundle/Model/PageModel.php#L561

which in turn dispatches a `PAGE_ON_HIT` event:

https://github.com/mautic/mautic/blob/0bfb1c6bec7896cb108d6ef11b1c23a85a3ccb90/app/bundles/PageBundle/Model/PageModel.php#L778

I think I see 5 subscribers to that event:

- `app/bundles/EmailBundle/EventListener/PageSubscriber.php`
- `app/bundles/PageBundle/EventListener/CampaignSubscriber.php`
- `app/bundles/PageBundle/EventListener/PointSubscriber.php`
- `app/bundles/PageBundle/EventListener/WebhookSubscriber.php`
- `plugins/MauticFocusBundle/EventListener/StatSubscriber.php`

I'm guessing that one of these was responsible for adding the bot visitors to the segment I'd configured to have tag exclusion filters, but I'm not sure which.

If my understanding of the code is correct so far, then it seems like this should not be too hard to fix.

**Comment by aspiers** [comment]
@escopecz Any thoughts on whether the above partial analysis is correct?  Thanks!

**Comment by escopecz** [comment]
What I've learn for the time contributing to this project is that a behavior change that a group of users requests will negatively affects another users for reasons no one could have predicted. So I'd stick with the current behavior and let anyone to choose to change it in the configuration. At least until the Mautic 3.

The code mentions look right.

**Comment by aspiers** [comment]
@escopecz That sounds entirely reasonable to me.  Thanks for the quick response!

**Comment by kuzmany** [comment]
This could fix it: https://github.com/mautic/mautic/pull/7614 
Please test and let comment there

**Comment by RCheesley** [comment]
We are waiting on the conflicts to be resolved in #7614 and then it will need retesting in Mautic 3.x - we have a few weeks to get that done in time for 3.1 if we want to get it merged in that release.

**Comment by RCheesley** [comment]
@aspiers are you able to test the PR #7614 to see if this resolves your issue?

**Comment by aspiers** [comment]
Hi Ruth, really sorry but I've got too much other stuff on my plate right now! Hopefully might be able to get back to Mautic some time in 2021 depending on current work...

**Comment by aspiers** [comment]
... but it's great to see all this progress from the sidelines, congrats ;-)

**Comment by andres-asm** [comment]
Hi, this is still a thing, closing stale issues is really a bad practise, there is a clear loss of visibility of what's broken due to this.

**Comment by RCheesley** [comment]
Thanks, all we need is for someone to reply, to keep the issue active. I've just reopened the issue.
