### ISSUE TITLE
1452 Cannot add or update a child row: a foreign key constraint fails

### ISSUE THREAD

**Issue by MarkKrauss** [mautic/mautic#7566]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Submitting a form is not possible. Even add new Contact gives a error 500.

The errorlog says it "_Integrity constraint violation_". Why is he trying to use the campaign with id **2**?

| Q   | A
| --- | ---
| Mautic version | 2.14->2.15.1
| PHP version | 7.0

### Steps to reproduce
1. Delete a Campaign ? In my case id 2
2. Submit a form or add a new contact
 
### Log errors
mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException: "An exception occurred while executing 'INSERT INTO campaign_leads (date_added, manually_removed, manually_added, date_last_exited, rotation, **_campaign_id_**, lead_id) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["2019-05-28 10:07:21", 0, 1, null, 1, **_2_**, 6095]:  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`mtc_live`.`campaign_leads`, CONSTRAINT `FK_5995213DF639F774` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE CASCADE)" at /var/www/html/mtlive/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by MarkKrauss** [comment]
It looks like this bug is the same: [4852](https://github.com/mautic/mautic/issues/4852) But its close "Not replicable".
But what if you delete an old Campaign (bevor you do an mautic-update) ? I think it's a possible reason.

**Comment by RCheesley** [comment]
Closing as this is a very old issue without any recent activity
