### ISSUE TITLE
[Enhancement] Campaign Custom Fields

### ISSUE THREAD

**Issue by dobesv** [mautic/mautic#757]
It would be great to have some custom fields I could attach to a campaign an insert into emails for that campaign.

My use case is a webinar series.  Sometimes all that changes is the title, date, and webinar link.  If I could attach that information to the campaign and refer to it in the email templates, that would save a lot of time going through all the emails and updating those pieces of information each time I clone the campaign.

**Comment by alanhartless** [comment]
Closing in favor of #831
