### ISSUE TITLE
is there a way to warm up a domain? is it possibile to send campaign by fixed amount mail per day?

### ISSUE THREAD

**Issue by Sano123456** [mautic/mautic#7573]
Mautic is perfect for everything bu there is a big weakness that i didnt solve
when adding a new domain i can't simply send 5K email immediatly, because all will flag it as spam

Is there any solution to gradually send a campaign to wam up a new domain?

thanks

**Comment by Sano123456** [comment]
any idea to solve this?

thanks

**Comment by escopecz** [comment]
There is no such option. The IP warmup should take 5 days to get to 5k emails. ([source](https://www.sparkpost.com/docs/deliverability/ip-warm-up-overview/)), Could you create a segment with filter

`contact ID > 200`

And increase that every day based on the linked table?
