### ISSUE TITLE
Failed to upgrade to 2.15.1 from UI or console

### ISSUE THREAD

**Issue by aimran50** [mautic/mautic#7574]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 7.1.12
| Browser | Any

### Steps to reproduce
1. Upgrade using the web app upgrade process or
2. Via console command: php C:\Bitnami\wampstack-7.1.12-0\apps\mautic\htdocs\app\console mautic:update:apply
 
### Log errors
Step    1 [->--------------------------] Loading update information...
Step    2 [-->-------------------------] Downloading update package...                  PHP Warning:  file_put_contents(C:\Bitnami\wampstack-7.1.12-0\apps\mautic\htdocs\app\cache\prod/index.php?option=com_mauticdownload&task=downloadPackage&id=75): failed to open stream: No error in C:\Bitnami\wampstack-7.1.12-0\apps\mautic\htdocs\app\bundles\CoreBundle\Helper\UpdateHelper.php on line 75

Step    3 [--->------------------------] Validating update package...

The Mautic update could not complete successfully because of the following error: Could not open the ZIP archive to complete the update.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by stevedrobinson** [comment]
@aimran50 I think you need to install php-zip. 

I think this will help you: https://docs.bitnami.com/installer/infrastructure/wamp/configuration/install-modules-php/
