### ISSUE TITLE
Receives a warning "Synchronous XMLHttpRequest on the main thread is deprecated..." in browser console when inserting the form's <script ... > provided in Mautic form to integrate in a web page's body

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#7576]
## Bug Description

Complete message : "[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/."

If Mautic instance is slow, then the rest of the page will not load unless the form as loaded.

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1. Create a form
2. Copy the script for integration
3. Insert in the body of an existing page
4. Open the console
5. Reload the page

Result : The warning is displayed

Expected : Mautic provides further instructions to insert the form in a way that's browser friendly.
 
### Log errors

No errors logged, except a warning in browser's console

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
