### ISSUE TITLE
Extend credential options for AmazonS3Integration in CloudStorage plugin

### ISSUE THREAD

**Issue by virgilwashere** [mautic/mautic#7581]
In the `MauticCloudStorageBundle` plugin, `Integration/AmazonS3Integration.php` has a `getAdapter` function that only works with ACCESS_KEY and ACCESS_SECRET.

If running on an AWS EC2 instance, it's possible to use the default credential provider chain to access resources using the Instance IAM Role.

Ref: <https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_configuration.html?shortFooter=true#credentials>

Would anyone who knows how to write PHP be prepared to enable this functionality?
Extend the class AmazonS3Integration class and modify form build to use default provider chain instead of hardcoded key/secret ?

My dodgy mix of code and pseudo-code:

```php
    public function getAdapter()
    {
         //...
          $service = new S3Client(
                [
                    'version'     => 'latest',
                    'region'      => (empty($keys['region'])) ? 'us-east-1' : $keys['region'],

                    if ("I want to use default provider chain" is selected) {

                // This should also remove client_id and 
			    // client_secret from getRequiredKeyFields on the form.

                    use Aws\DoctrineCacheAdapter;
                    use Doctrine\Common\Cache\ApcuCache;

                        'credentials' => new DoctrineCacheAdapter(new ApcuCache),

                    }
                    
                    // The DEFAULT option
                    else ("I want to use default provider chain" is NOT selected) {
                        'credentials' => [
                            'key'    => $keys['client_id'],
                            'secret' => $keys['client_secret'],
                        ],
                    }
                ],
            );
    }
```

Thanks, 

Virgil

**Comment by RCheesley** [comment]
@virgilwashere I think this is a feature request, in which case can you post it up on the forums for people to discuss?

This category is the place to share: https://forum.mautic.org/c/ideas
