### ISSUE TITLE
Forms are blocked because of mixed content

### ISSUE THREAD

**Issue by nguyenhung** [mautic/mautic#7588]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Forms are blocked because of mixed content. Please see _Log errors_

**My setup**
Nginx <---443 proxy to 8083:80 ---> Mautic (Docker)
- Nginx: redirect all http connection to https
- Nginx: proxy port 443 to 8083
- Mautic(docker): expose 8083:80

| Q   | A
| --- | ---
| Mautic version | 2.15 (mautic/mautic:latest)
| PHP version | 7.1.27
| Browser | Chrome, lastest

### Steps to reproduce
1. Deploy Mautic with docker, expose port 8083:80
2. Setup Nginx locally, redirect all http traffic to https using Nginx
3. Proxy 443 to 8083
4. In Mautic configuration, setup Site URL as:  **http://** mautic.example.com. We have to set up site URL http://mautic.example.com because using https will cause the site ran into a redirection loop
5. Setup a form
6. Include the form inside a landing page
7. View the landing page and submit. Watch browser console
 

### Log errors
`Mixed Content: The page at 'https://mautic.example.com/test' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://mautic.example.com/form/submit?formId=1'. This endpoint should be made available over a secure connection.`

Excerpt from a landing page with a form, even though the landing page is loading in https
```
<script type="text/javascript">
  | /** This section is only needed once per page if manually copying **/
  | if (typeof MauticSDKLoaded == 'undefined') {
  | var MauticSDKLoaded = true;
  | var head            = document.getElementsByTagName('head')[0];
  | var script          = document.createElement('script');
  | script.type         = 'text/javascript';
  | script.src          = 'http://mautic.example.com/media/js/mautic-form.js';
  | script.onload       = function() {
  | MauticSDK.onLoad();
  | };
  | head.appendChild(script);
  | var MauticDomain = 'http://mautic.example.com';
  | var MauticLang   = {
  | 'submittingMessage': "Please wait..."
  | }
  | }
</script>
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by ComputerCarl** [comment]
I am having the same issue running in Docker container on [CapRover](https://github.com/caprover/caprover), however I do have the main Mautic configuration URL set to HTTPS. 
Mautic 2.15.1 (mautic/mautic:latest)

**Comment by ComputerCarl** [comment]
My issue was from not rebuilding the form after setting the **Site URL** value, as instructed in [docs](https://www.mautic.org/docs/en/forms/index.html).
