### ISSUE TITLE
Radio Group values replaced with option number

### ISSUE THREAD

**Issue by hdezela** [mautic/mautic#7591]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When creating a form that has a Radio Group, any values entered into the "Value" field of the group are ignored and instead the option number is recorded.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2.19
| Browser | Any

### Steps to reproduce
1. Create a form with a Radio Group
2. In properties, put in any text for "Value" and assign to a contact field
3. Fill in the form
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Please share screenshot of your form field configuration + your contact field config.

Thanks !
