### ISSUE TITLE
Html export of reports don't have an horizontal slider to display all columns

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#7592]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When you create an html export of a report with lot of columns, the export don't have an horizontal slider so you can't see all columns

| Q   | A
| --- | ---
| Mautic version | 2.15 / 2.15.1
| PHP version | 
| Browser |  Chrome

### Steps to reproduce
1. Create a report with a lot of columns
2. Export in Html the report
3.See that on the html export page, the hozirontal slider is not diplayed, so you can't view all the sheet.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Noa83** [comment]
PR for the correction of this issue: https://github.com/mautic/mautic/pull/7600

**Comment by dennisameling** [comment]
PR #7600 is merged now, so closing this issue. Thanks @Noa83!
