### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by UtenteWeb** [mautic/mautic#7594]
Hi, as on the mautic.org website I read that "If you have a more technical question, or if you believe you’ve found a bug in Mautic then the issue tracker is the best place to post your question or problem", and since I have a technical question, but I haven't found a better section than this to do it, then the place here, apologizing in advance if this is not the right place to post it.
The question is really very, very simple:
Is it possible to install Mautic, as well as on Linux, also on Mac and Windows?
Thanks 1000 for any contribution
Best wishes

**Comment by RCheesley** [comment]
Mautic can be installed on any OS providing you meet the requirements of the software. The requirements are here: https://www.mautic.org/download/requirements/ - you can use XAMPP or similar to run a localhost on your machine as you need.  So the answer to your question is technically yes, but in production you would want to be hosting on a server that is optimised for the purpose.
