### ISSUE TITLE
Internal Server Error (500) when Creating New Segment with new role

### ISSUE THREAD

**Issue by bilkobe** [mautic/mautic#7597]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I want to differentiate all users with their own contacts and segments. When i tried to create Segment with new user, mautic returns internal server error. I can create segment with an user who has Full System Access role.

| Q   | A
| --- | ---
| Mautic version | 2.15.2-dev
| PHP version |  7.2
| Browser | Google Chrome 74.0.3729

### Steps to reproduce
1. Define following role for Contact Permissions and assign to an user.
![image](https://user-images.githubusercontent.com/37382099/59314580-9d2a9800-8cbe-11e9-93bb-7394d7c93fb4.png)

2. Login with related user. Try to create new segment.
 
### Log errors
[2019-06-12 01:24:42] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 253 near 'created_by =': Error: Class Mautic\CampaignBundle\Entity\Campaign has no field or association named created_by" at /var/www/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 253 near 'created_by =': Error: Class Mautic\\CampaignBundle\\Entity\\Campaign has no field or association named created_by at /var/www/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT partial c.{id, name}, partial ll.{id} FROM MauticCampaignBundle:Campaign c INDEX BY c.id LEFT JOIN c.lists ll WHERE c.isPublished = :true AND (c.publishDown IS NULL OR c.publishDown >= :now) AND (c.publishUp IS NULL OR c.publishUp <= :now) AND c.created_by = :id at /var/www/mautic/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by MikeDaniel18** [comment]
Also getting this. Similar thing. 500 error on new account role. Error:

```
mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 253 near 'created_by =': Error: Class Mautic\CampaignBundle\Entity\Campaign has no field or association named created_by" at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 253 near 'created_by =': Error: Class Mautic\\CampaignBundle\\Entity\\Campaign has no field or association named created_by at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT partial c.{id, name}, partial ll.{id} FROM MauticCampaignBundle:Campaign c INDEX BY c.id LEFT JOIN c.lists ll WHERE c.isPublished = :true AND (c.publishDown IS NULL OR c.publishDown >= :now) AND (c.publishUp IS NULL OR c.publishUp <= :now) AND c.created_by = :id at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
```

**Comment by mguntis** [comment]
The same:
Error: Class Mautic\CampaignBundle\Entity\Campaign has no field or association named created_by

**Comment by OlexandrPopov** [comment]
It seems this [line](https://github.com/mautic/mautic/blob/af5e0569e56938ebd5e671b52a5dbfa16c2f7bf7/app/bundles/CampaignBundle/Entity/CampaignRepository.php#L109) needs to be changed to 

```
$q->andWhere($q->expr()->eq('c.createdBy', ':id'))
```

**Comment by cesarmartin** [comment]
> It seems this [line](https://github.com/mautic/mautic/blob/af5e0569e56938ebd5e671b52a5dbfa16c2f7bf7/app/bundles/CampaignBundle/Entity/CampaignRepository.php#L109) needs to be changed to
> 
> ```
> $q->andWhere($q->expr()->eq('c.createdBy', ':id'))
> ```

It works!
This feature must be adjusted to next releases.

**Comment by jonathands** [comment]
> > It seems this [line](https://github.com/mautic/mautic/blob/af5e0569e56938ebd5e671b52a5dbfa16c2f7bf7/app/bundles/CampaignBundle/Entity/CampaignRepository.php#L109) needs to be changed to
> > ```
> > $q->andWhere($q->expr()->eq('c.createdBy', ':id'))
> > ```
> 
> It works!
> This feature must be adjusted for next releases.

I would  risk sending a pull request, but the syntax created_by with underline is used all through the system while createdBy seems t be the exception, I feel uncomfortable sending a pull request for this specific file while the whole system uses a different naming  convention.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Comment by namratasaun** [comment]
> $q->andWhere($q->expr()->eq('c.createdBy', ':id'))

this works. thanks
