### ISSUE TITLE
Social media SSO

### ISSUE THREAD

**Issue by dobesv** [mautic/mautic#760]
It would be nice to allow social login into Mautic, although not a huge benefit.

A more interesting benefit might be letting users auto-fill their name, email, and social profiles using Google login.

First step here would be to get some kind of auth0 integration working.  Auth0 is pretty easy to set up and has a nice UI.

**Comment by plenartech** [comment]
I have similar feature request as @dobesv. I suppose https://github.com/alanhartless/mautic-sso-plugin is for this feature. Does the plugin support SAML2?

**Comment by escopecz** [comment]
Also this PR is related: https://github.com/mautic/mautic/pull/1552
