### ISSUE TITLE
Azure Kubernetes and Mautic: install error

### ISSUE THREAD

**Issue by kidfilkings** [mautic/mautic#7601]
Hey guys,

I'm using Azure Kubernetes Services (AKS) and I deployed Mautic 'successfully' but when I try to access myURL/installer I get the generic error of 'Site is offline'. Can anyone help me finding logs to check what's happening?

**Comment by kidfilkings** [comment]
If I run `kubectl logs mymauticPod` I can see this error message:

> Unable to create the cache directory (/var/www/html/app/cache/prod)

I don't know if the errors are related...

**Comment by npracht** [comment]
It could be. Does all the rights for the app are correctly set ? The directory must be able to be created. This is more about a configuration issue. I'd suggest you to join the community chat on Slack.

**Comment by kidfilkings** [comment]
Hi,
Yes, it was a matter of permission.
For future information:
$ chown -R www-data:www-data app/cache
$ chown -R www-data:www-data app/log
