### ISSUE TITLE
PHP 7.3.5 Support

### ISSUE THREAD

**Issue by cristianuibar** [mautic/mautic#7602]
## Bug Description
When I try to install Mautic on a clean VPS I get the following error message:
`Mautic does not support PHP version 7.3.5-1+ubuntu16.04.1+deb.sury.org+1 at this time. To use Mautic, you will need to downgrade to an earlier version.`

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.3.5
| Browser | Google Chrome

### Steps to reproduce
1. Try to install Mautic on a PHP 7.3.5 server

![image](https://user-images.githubusercontent.com/1476365/59386600-bfc8b980-8d6f-11e9-81bb-406906463e70.png)

**Comment by kuzmany** [comment]
PHP 7.3 support is not  ready yet. You can help with that here https://github.com/mautic/mautic/pull/6991
