### ISSUE TITLE
Email Create API Doesn't allow translationParent to be set

### ISSUE THREAD

**Issue by indorock** [mautic/mautic#7604]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I'm using the PHP library to add new emails to our Mautic environment, to programatically generate translated copies of each (English) email. I'm referring to the docs at https://developer.mautic.org/?php#create-email to design the payload to send, but in trying to send translationParent no parent is actually set to the newly created email. I've tried to send the object as described in the docs (technically it's an array, the one that returns from the GET email endpoint) but that did not work, then tried to send the ID under that key and even under translation_parent_id to no avail. Importantly, the API does not return an error of any kind. 

Can you inform me how I'm properly supposed to set a translation parent for an email with the create API?

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.0.30
| Browser | Chrome 74.0.3729.169 (MacOS)

### Steps to reproduce
1. Form a request to the `create` endpoint of the API using the PHP library, with payload as described in the docs. Add `translationParent` to the payload as an object.
2. Check the value of `translationParent` in the newly created email either in the database or via the Mautic admin UI, notice no translation parent has been set.
 
### Log errors
No related errors are returned

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
```
$data = array(
    'name'        => 'Email B',
    'subject'        => 'Email B',
    'description' => 'This is my first email created via API.',
    'isPublished' => 1,
    'templateTranslationParent'=>1
);
$api              = new MauticApi();
$emailApi       = $api->newApi('emails', $auth, $apiUrl);
$email = $emailApi->edit(3, $data);
```

The parent ID of translation have to set to templateTranslationParent
