### ISSUE TITLE
Cron jobs not working Cpanel

### ISSUE THREAD

**Issue by ZeeshiEli92** [mautic/mautic#7607]
I am trying to setup Mautic on hosting at sub-domain.

I have installed Mautic manually by uploading file and creating DB.

but i am stuck at cron jobs i tried different formats but nothing worked. 

/usr/local/bin/ea-php72 /home/bitens/mls.bitens.com/app/console mautic:segments:update | Edit
php /home/bitens/mls.bitens.com/app/console mautic:segments:update >/dev/null 2>&1 | Edit
/usr/local/cpanel/3rdparty/bin/php /home/bitens/mls.bitens.com/app/console mautic:campaigns:trigger >/dev/null 2>&1 | Edit

tried these formats but nothing worked any help would be appreciated.

**Comment by AkkuFresh** [comment]
Hi, It is not a Mautic problem, a simple Linux cron job syntax problem.
By the way in my servers the '| Edit' part unnecessary.
Please write to your hosting provider to find the proper syntax of cron on that hosting.

> */5 *	* * * /usr/local/bin/php -c /home/-mauticpath-/php.ini /home/-mauticpath-/app/console mautic:emails:send >/home/-logpath-/email_send_log.txt

This is a working syntax from a production server (CentOs 7 and CWP admin panel)
