### ISSUE TITLE
Company field fails to update existing contact's primary company on form submit

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#7608]
When:
- a form references a company field instead of a contact field
- A contact submitting the form already exists and has an associated primary company
- The primary company has either an empty value or a different value from the one submitted via the form

Expected behavior:
the primary company record is updated and the field value is overwritten with the value submitted via the form.

Actual behavior:
The primary company's data value is not updated and continues to read the old value (or empty if previously empty).

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.X
| Browser | N/A

### Steps to reproduce
1. Create a custom field on Companies
2. Create a form referencing that field
3. Submit the form with a value, using an existing known contact
4. Review the value of the custom company field
 
### Log errors
No errors are created in the log.

**Comment by pety-dc** [comment]
@stevedrobinson 

I have ran into the same problem. Luckily, I think I've found a workaround solution

According to the source code the company of the lead is only identified if `company` or `companyName` fields are provided with form submit. It ignores the primary company thing


To solve this, you should add a `hidden` field to the form you want to update primary company fields with and bind the field with the `company` contact field. On the Behavior tab set `Auto fill data` to YES. 

Mautic will include the tracked user's `company` field in the form as a pre-filled hidden value.


Don't forget to read the notes behind the question mark (?)

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
