### ISSUE TITLE
Campaign builder doesn't work on mobile due to lack of hover

### ISSUE THREAD

**Issue by aspiers** [mautic/mautic#7610]
## Bug Description

The Campaign builder relies on mouse hover in order to convert the grey semi-circles into plus icons so that they can be clicked to add new decision/action/condition elements.  However hover is not available on most mobile devices (except maybe some tablets which support stylus input, or some phones which have proximity detection).  So on most mobile devices it's unusable.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.27
| Browser | Chrome 75.0.3770.89 for Android 9

### Steps to reproduce
1. Create a new campaign via mobile browser
2. Launch Campaign Builder
3. Notice that there is no way to add new elements to the campaign.
 
### Log errors

n/a

**Comment by npracht** [comment]
@escopecz i don't know if mautic should be able to be used (especially the campaign builder) on mobile device? Is there a definition somewhere of support compatibility ?
IMO, mautic is a service too advanced to be used on mobile except the contacts/companies pages.

**Comment by escopecz** [comment]
It would be nice to have. If someone must use a mobile device to make a change then we should do our best to make it possible. Maybe the semi-circles could show up on click/tap as well as on hover.

**Comment by aspiers** [comment]
[**@npracht**](https://github.com/npracht) commented on [June 25, 2019 12:41 PM](https://github.com/mautic/mautic/issues/7610#issuecomment-505407340 "2019-06-25T11:41:32Z - Replied by Github Reply Comments"): 
> IMO, mautic is a service too advanced to be used on mobile except the contacts/companies pages.

What if there are only a few minor issues like this one standing in the way of Mautic working on mobile?  If so, it would seem a real shame to chuck away the chance of getting it to work.  And most other stuff I've tried so far seems to work great.  So please let's not give up on this too soon :-)

**Comment by kgroveshok** [comment]
On other projects I've found great success in just adding jQuery Touch Punch plugin (http://touchpunch.furf.com/) which does all the work. Might be worth a try without investing any coding to see if it handles all the requirements.

**Comment by aspiers** [comment]
Yeah Touch Punch has worked for me in another project too.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
