### ISSUE TITLE
The getLeadIpLogs function causes a 'Incorrect DATETIME value' error

### ISSUE THREAD

**Issue by scottybo** [mautic/mautic#7612]
| Q   | A
| --- | ---
| Mautic version | v2.15.2-beta 
| PHP version | PHP 7.2.19-1+ubuntu18.04.1+deb.sury.org+1
| MySQL version | Ver 8.0.16 for Linux on x86_64 (MySQL Community Server - GPL)
| Browser | n/a

## Bug Description

This is a bit of a weird one and I'm not sure how to replicate the issue as it only happens on our production server, but I've identified where the problem is and how to fix it.

In https://github.com/mautic/mautic/blob/staging/app/bundles/CoreBundle/Entity/AuditLogRepository.php we have the function `getLeadIpLogs`

Which contains the following line:

```php
$sqb->expr()->gte('l.date_added', $sqb->expr()->literal($dt->getUtcTimestamp()))
```

When executed, I get the error  detailed at the bottom of this issue. 

Long story short, checking for a timestamp is causing this error.

## (Possible) Solution

By changing the above line to:

```php
$sqb->expr()->gte('l.date_added', $sqb->expr()->literal($lead->getDateAdded()->format('Y-m-d H:i:s')))
```

Everything works as expected. So simply put, the problem seems to be that using a timestamp instead of a datetime string is causing a problem.

### Log errors

```
[2019-06-17 14:38:13] mautic.CRITICAL: 

Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: 
"An exception occurred while executing 'SELECT ip.date_added, ip.ip_address, ip.lead_id, ip.id FROM (SELECT MAX(l.date_added) as date_added, MIN(l.id) as id, l.ip_address, l.object_id as lead_id FROM audit_log l WHERE (l.bundle = 'lead') AND (l.object = 'lead') AND (l.action = 'ipadded') AND ((l.object_id = 71) AND (l.date_added >= '1560775838')) GROUP BY l.ip_address) ip ORDER BY ip.date_added DESC LIMIT 25':  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '1560775838'" at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT ip.date_added, ip.ip_address, ip.lead_id, ip.id FROM (SELECT MAX(l.date_added) as date_added, MIN(l.id) as id, l.ip_address, l.object_id as lead_id FROM audit_log l WHERE (l.bundle = 'lead') AND (l.object = 'lead') AND (l.action = 'ipadded') AND ((l.object_id = 71) AND (l.date_added >= '1560775838')) GROUP BY l.ip_address) ip ORDER BY ip.date_added DESC LIMIT 25': SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '1560775838' 
at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115
Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '1560775838' at/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '1560775838' at /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []

```

**Comment by npracht** [comment]
@scottybo could you PR your solution ?

**Comment by scottybo** [comment]
Not at the moment I'm afraid - massive deadline looming

**Comment by renato14sc** [comment]
I had the same problem in contacts details.  For example, when I click in a contact (path http://server/mautic/index.php/s/contacts/view/4  )  its results in the same error in getLeadIpLogs function.

I used the solution above with sucess.

PHP Version 7.2.19
Apache/2.4.6 
Mautic v2.15.1
Mysql  Ver 8.0.16

**Comment by RafaelAybar** [comment]
i think that the answer could be in https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html

**Comment by dorukgezici** [comment]
Your solution fixed my issue as well, thanks!

**Comment by RCheesley** [comment]
@scottybo @RafaelAybar @dorukgezici anybody able to make a PR to address this issue?

**Comment by victormelimlauro** [comment]
Thanks,
Your solution, resolved this problem in my server
IIS 10 Windows 2016
Mysql 8.0.17 Community
php 7.1.29

**Comment by autoize** [comment]
Creating a contact fails with a 500 error in Mautic 3.0.0-alpha when using MySQL 8.0.18 Community with the following log output. Applying @scottybo's solution makes it work however.

`[2020-01-11 17:31:34] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT ip.date_added, ip.ip_address, ip.lead_id, ip.id FROM (SELECT MAX(l.date_added) as date_added, MIN(l.id) as id, l.ip_address, l.object_id as lead_id FROM audit_log l WHERE (l.bundle = 'lead') AND (l.object = 'lead') AND (l.action = 'ipadded') AND ((l.object_id = 1) AND (l.date_added >= '1578763894')) GROUP BY l.ip_address) ip ORDER BY ip.date_added DESC LIMIT 25':  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '1578763894'" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 106 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'SELECT ip.date_added, ip.ip_address, ip.lead_id, ip.id FROM (SELECT MAX(l.date_added) as date_added, MIN(l.id) as id, l.ip_address, l.object_id as lead_id FROM audit_log l WHERE (l.bundle = 'lead') AND (l.object = 'lead') AND (l.action = 'ipadded') AND ((l.object_id = 1) AND (l.date_added >= '1578763894')) GROUP BY l.ip_address) ip ORDER BY ip.date_added DESC LIMIT 25':\n\nSQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '1578763894' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:106, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '1578763894' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: '1578763894' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:75)"} []`

**Comment by karser** [comment]
I've sent a PR, please test https://github.com/mautic/mautic/pull/8354

**Comment by RCheesley** [comment]
Also seeing this logged here: https://community.bitnami.com/t/bitnami-mautic-2-16-image-is-not-working/76333 with 2.16 - @dennisameling maybe something we could consider for 2.16.1?
