### ISSUE TITLE
Remove robot/monitoring visit

### ISSUE THREAD

**Issue by Muvuk** [mautic/mautic#7613]
Helo,

I use uptime robot to check my site in every 5 minutes automatically. 
And this shows me a lot of traffic which is misleading. 

Is there a way to exclude this kind of traffic, like you did with google robots?

thank you

**Comment by stevedrobinson** [comment]
@Muvuk If you're looking for a quick fix while you wait for this feature request, you can always have the web server deny or redirect traffic from certain IP ranges and block the uptime robot from ever accessing mtc.js. This will prevent the pageviews from logging. 

We did this for a client who was getting hit with a lot of deep link inspection bots scanning mail to get the open rate and clickthrough rate back in line.

**Comment by npracht** [comment]
In the configuration you can exclude IP addresses or ranges. Could that answer your need ?
