### ISSUE TITLE
Contactfield tokens for company fields do not work in campaign webhook actions

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#7615]
## Bug Description
When creating a webhook action in a campaign, you can put tokens in for the values such as {contactfield=email}. This works great for contact level fields, but if you include a field off of the primary company, it comes back blank. 

This should work like tokens in emails, which properly resolve the primary company. 

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2
| Browser | N/A

### Steps to reproduce
1. Create a campaign with a webhook action
2. Within the webhook action, pass a parameter for company zipcode using the token {contactfield=companyzipcode}
3. view payload on the other side of the webhook

 
### Log errors
No errors present in log. It just fails silently.

**Comment by jelukas** [comment]
same here... waiting...

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by benfavre** [comment]
Does not work on my 2.6 install, but I confirm it works on mautic 3.1
Managed to display companyname based on the condition that companyname is not empty
