### ISSUE TITLE
Marking a custom field as "Available for Segments" = No does not prevent index creation

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#7619]
## Bug Description
The toggle on the custom field screen for "Available for Segments" should allow for creation of additional fields in Mautic that don't require indexes, extending the total number of contact fields beyond the limitation of 64 indexes.

However, when you create a field, even if the "Available for Segments" is "No", Doctrine creates an index for the field. 

NOTE: While this is closely related to [Issue #6063](/mautic/mautic/issues/6063), that issue refers to the 64 index limit as a whole, while this is reporting a bug specific to Mautic.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2
| Browser | N/A

### Steps to reproduce
1. Create a custom field, toggling "Available for Segments" to "No"
2. Query the database "SHOW INDEX FROM yourprefix_leads;" and notice that an index is created for the new field

**Comment by npracht** [comment]
The index could be useful for reports or campaign filters, don't you think ?
