### ISSUE TITLE
[Feature] Text messaging / SMS

### ISSUE THREAD

**Issue by dobesv** [mautic/mautic#762]
Sending emails is one thing, but in the modern day sending text messages is a powerful way to remind people to come to a webinar or take another time-sensitive action.

**Comment by dbhurley** [comment]
This has been discussed already, we believe we've identified two: Twilio and Plivo as potential integrations. Any others?

**Comment by that0n3guy** [comment]
We do this on our CRM.  Its super easy to do with twilio (we've used them for years).  I've heard good things about plivo and they have a higher sending rate (speed) than twilio for SMS.  A couple more are tropo, nexmo.

Also an alternative is: https://github.com/mautic/mautic/issues/854

**Comment by phillipwilhelm** [comment]
I'd love to see Twilio support!

**Comment by jacqueshenning** [comment]
If there was the ability to add an HTTP API connection to outside SMSC this system would be better than any other, you could then choose who you use for SMS and not just be limited to Twilio etc
SMPP would be number one for high volumes but its painful to setup.

**Comment by rafaelppaulucci** [comment]
Hi guys, ill love if u provide an HTTP API based on curl to run with other servers.
Here in Brazil all providers are based on HTTP API to send messages.

Something like that: 

http://smsserver/index.php?u=$$$$$\&p=$$$$$$\&to="Number of lead"\&msg="Hello World"

Regards

**Comment by hansakoch** [comment]
Would love Plivo support, as the prices are better and they support two way voice and sms their UK mobile numbers .
https://www.plivo.com/pricing/GB/#!sms

**Comment by littlekid** [comment]
+1 for 46elks , global support & text sender (text 3-11 chars) as sender.
https://www.46elks.com/pricing/united-states-sek

**Comment by escopecz** [comment]
I'll close this issue since Mautic supports SMS since Mautic 2.0.0. Please, open a separate issue if you need another SMS provider.
