### ISSUE TITLE
Attaching a private AWS S3 file fails

### ISSUE THREAD

**Issue by heroic** [mautic/mautic#7620]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Mautic allows selecting a private file in the file browser, via AWS S3, however it is unable to add this file as an attachment, or allow the user to download it. This makes using s3 plugin of no use.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.23
| Browser | Chrome latest

### Steps to reproduce
1. Add a private file to s3 bucket
2. Setup AWS S3 plugin in mautic
3. Select the private file while creating a remote asset.
4. Use the asset to send an email.
5. No attachment in email
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
@heroic is this still an issue for you?

**Comment by heroic** [comment]
@RCheesley It was, but we moved to https://github.com/Mailtrain-org/mailtrain/ out of the need.

**Comment by RCheesley** [comment]
OK will flag it as a bug for investigation, thanks for replying!

**Comment by RCheesley** [comment]
Will need to check if this is still the case in Mautic 3.x and close if not. I'll try to find someone who can help testing!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
