### ISSUE TITLE
MAUTIC REPORT EXPORT URL -- REPORT NOT SHOW DATA ACCORDING SOURCE DATE DEFINE

### ISSUE THREAD

**Issue by angelitodiaz1** [mautic/mautic#7623]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version |  2.15.1
| PHP version | PHP Version 7.0.33
| Browser | Chrome Version 75.0.3770.80 / Firefox 67.0.3 (64bit)

### Steps to reproduce
1. Generate a report with Dates 4 months ago (campaign or mail sorce)
2. Generate a URL export
 
### Log errors
No log. Not error. Only the data is invisible because report show period dates out range define.

![image](https://user-images.githubusercontent.com/6534435/59773254-53701d80-927b-11e9-97ea-3ba98ab74dfc.png)
![image](https://user-images.githubusercontent.com/6534435/59773301-6256d000-927b-11e9-9d7d-0d719d0fc172.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Please confirm mautic version.

**Comment by angelitodiaz1** [comment]
Hi, the version installed is 2.15.1.

**Comment by npracht** [comment]
Could you please test in 2.15.2-beta and confirm if fixed or not ? Please do not test this version in production environment.

**Comment by npracht** [comment]
Hi @angelitodiaz1 any update ?

**Comment by angelitodiaz1** [comment]
Hi, without update. The issue is still live and that is a problem.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, I think this is fixed by https://github.com/mautic/mautic/pull/8737
