### ISSUE TITLE
Asset Downloaded report shows the same downloaded time for all records

### ISSUE THREAD

**Issue by inspiremedia01** [mautic/mautic#7626]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When I create a Asset Downloads report and then export the report to csv, xls, or html the time of day the asset was download always shows as 12:00 am ACST.

If I view the date/time the asset was download via the contact record, the time is always correct.

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1.30
| Browser | Firefox

### Steps to reproduce
1. Create an Asset Downloads report
2. Make sure to add the 'Date Downloaded' field to the report
3. Export the report to any format
4. View the time, it is always showing as 12:00 am ACST
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )
![asset-report](https://user-images.githubusercontent.com/16477672/59828891-273bc600-937b-11e9-96d5-23919a7351b4.jpg)

**Comment by inspiremedia01** [comment]
I am also having the same issue with the 'Form Submission's report. The ' Date Submitted field shows the wrong time, but 'Date Created and 'Date Last Modified seem to be showing the correct data.
![Submitted-Forms-Report](https://user-images.githubusercontent.com/16477672/60061579-d9391080-9734-11e9-868a-a98a26f6638b.jpg)

**Comment by inspiremedia01** [comment]
There seems to be a lot of reports that are not showing/exporting the date correctly (not just the ones I have shown above). Some filtering is not working either. 

Seems to be a lot of issues with reports. I am having to either get data straight from phpmyadmin, or find other ways to make the reports work (like creating a segment and then filter to show only contacts in that segment, which isnt the best way to do this, as I should be able to just use the filter in the reports).

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
