### ISSUE TITLE
Mautic & Amazon SES Integration issues

### ISSUE THREAD

**Issue by IvanSkMkd** [mautic/mautic#7628]
I installed Mautic in-house instance. I tried to integrate it with Amazon SES service. After all was set as needed (please find the screenshot below), I clicked "Test connection" button and got the following error:

> Connection could not be established with host email-smtp.eu-west-1.amazonaws.com [An attempt was made to access a socket in a way forbidden by its access permissions. #10013] Log data: ++ Starting Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport !! Connection could not be established with host email-smtp.eu-west-1.amazonaws.com [An attempt was made to access a socket in a way forbidden by its access permissions. #10013] (code: 0) ++ Starting Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport

Can someone give a hand on this? What am I doing wrong?

Please, check the screenshot: https://gyazo.com/2a695e3f7596a5df77f941aee8d08dd7

**Comment by pierrederuel** [comment]
Check if the port number is blocked by your firewall

**Comment by IvanSkMkd** [comment]
> 
> 
> Check if the port number is blocked by your firewall

Where in Mautic I can check and/or change the port?

**Comment by pierrederuel** [comment]
It's not a problem from mautic, it's from your network config

**Comment by IvanSkMkd** [comment]
> 
> 
> It's not a problem from mautic, it's from your network config

It was working previously. This new version is not working. All with network config is same.
What can I do?

**Comment by pierrederuel** [comment]
Try to change the port number to 587

=> edit the AmazonTransport.php line 71 to parent::__construct($host, 587, 'tls');

**Comment by IvanSkMkd** [comment]
> 
> 
> Try to change the port number to 587
> 
> => edit the AmazonTransport.php line 71 to parent::__construct($host, 587, 'tls');

This did the trick! Thank you a lot Pierre! :)
https://gyazo.com/9dfb81524e94ef404283e7c600cabdc4
