### ISSUE TITLE
Feature request: customize one signal notifications popup

### ISSUE THREAD

**Issue by digitall-it** [mautic/mautic#7633]
| Q  | A
| ---| ---
| Bug report? | N
| Feature request? | Y
| Enhancement? | Y

## Description:
Push notifications message can’t be customized. My site is in Italian and the onesignalsubscription pop up appears in English. Maybe related to #6164

**Comment by digitall-it** [comment]
I propose changing the function `getScript()` in `mautic/app/bundles/NotificationBundle/Helper/NotificationHelper.php` and make at least `$oneSignalInit` customizable via plugin panel, with the default string set as the contents of the file in the HEREDOC at 145:190. This would remove the need to explicitly list all the possible customizations in the OneSignal API, while retaining as best as possible the original implementation.

**Comment by digitall-it** [comment]
If I would happen to code this feature, would you accept it?

**Comment by RCheesley** [comment]
@digitall-it sorry for the super delayed response - if you can propose a PR we can for sure consider it!

**Comment by RCheesley** [comment]
@digitall-it as there has been no response on this I'm going to close down the issues. We now have feature request discussions on the forum at https://forum.mautic.org/c/ideas so please do add a thread there if you want to propose something like this, or you can make the PR directly.
