### ISSUE TITLE
Can't create Campaign using Mautic API

### ISSUE THREAD

**Issue by yassersheikh** [mautic/mautic#7635]
## Can't create Campaign using Mautic API
I am following Mautic API documentation https://developer.mautic.org/#create-campaign to create campaign, but facing issues.

Their document states to POST 'name', 'description' and 'isPublished' on /campaigns/new 

1. Posting same I get "At least one event is required. Use the Launch Campaign Builder button to add one."
2. Adding 'events' I get "At least one contact source is required. Use the Launch Campaign Builder button to add one."
3. Adding 'lists' I get "Looks like I encountered an error (error #500). If I do it again, please report me to the system administrator!"

Screenshot https://i.ibb.co/pr4v62S/Selection-529.png

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
