### ISSUE TITLE
OAuth1 Temporary Credential Request responds with an invalid oauth_callback_confirmed value on the Mautic API

### ISSUE THREAD

**Issue by hoylen** [mautic/mautic#7636]
## Bug Description

The response from the Temporary Credential Request operation (i.e. the POST request to `https://example.com/oauth/v1/request_token` that starts the OAuth1a authentication process) does not conform to the OAuth 1a specification: the response contains this wrong value:

`
oauth_callback_confirmed=1
`

The correct value must be:

`
oauth_callback_confirmed=true
`

See [section 2.1 of RFC 5849](https://tools.ietf.org/html/rfc5849#section-2.1) where it says the _oauth_callback_confirmed_ parameter **MUST be present and set to "true"** - the value t-r-u-e and not "1".

This bug means compliant OAuth1 libraries, which checks that parameter for correctness, will reject the response. The Mautic API cannot be invoked using some OAuth1 client libraries.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.27
| Browser | N/A

### Steps to reproduce
1. Invoke the Temporary Credential Request API operation using valid client credentials.
2. Examine the body of the HTTP response.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by hoylen** [comment]
Confirmed. This bug still exists in Mautic 3.0.1.

It still returns the incorrect `oauth_callback_confirmed=1` instead of the correct `oauth_callback_confirmed=true`

For example,

```
POST /oauth/v1/request_token HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: OAuth oauth_nonce="35170109311299245301594944545", oauth_timestamp="1594944545", oauth_version="1.0", oauth_signature_method="HMAC-SHA1", oauth_consumer_key="3k1j7iig19a8cs8k8cwkw8k0so0o4o4occ8osko4gccwo0c040", oauth_signature="7YOmrZJaePnPuPMQQlC2pKUgunk%3D"
Connection: keep-alive
Content-Length: 0
Host: localhost:16666
User-Agent: HTTPie/2.0.0



HTTP/1.1 200 OK
Cache-Control: no-cache, private
Connection: Keep-Alive
Content-Length: 181
Content-Type: application/x-www-form-urlencoded
Date: Fri, 17 Jul 2020 00:09:03 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.6 (CentOS) PHP/7.3.20
Vary: Authorization
X-Powered-By: PHP/7.3.20

oauth_token=3k0g287o9em8w8wcckss000w0ocsog0k8cgskg04gwkw8kwwss&oauth_token_secret=1mkwz2uixppccco0gssc4cg4gogkwso0048gc0cs48kw40g8cw&oauth_expires_in=3600&oauth_callback_confirmed=1
```

**Comment by RCheesley** [comment]
@hoylen thanks so much for taking the time to check this out, much appreciated! Would you be up for making a PR to address this?

**Comment by hoylen** [comment]
No, am not familiar enough with the codebase to do that.

**Comment by hoylen** [comment]
Still an open issue.
