### ISSUE TITLE
User is not added to campagin after adding to segment

### ISSUE THREAD

**Issue by pavel-janicek** [mautic/mautic#7640]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
**Preconditions**
Have a standalone form which adds contact to segment "A" - Form A
Have a campaign which has segment "A" as a source - Campaign A
**Steps to reproduce**
1. Send Form A
2. Login to Mautic and click "Campaigns" on new contact (Contact A)
3. Verify that "Campaign A" is turned off
4. run "mautic:campaigns:rebuild" cron 
5. Verify that "Campaign A" is turned on

However, this is usually very long delay (up to 15 minutes) to get to be part of "Campaign A" as a user. Especially if we know, that one of Form Actions can be "Send E-mail to the user" and given campaign can track if user read that email or clicked a link.

Is there a way to speed up the progress? When I tested the same in version 2.12.2 the contact was in the campaign immediatelly
| Q   | A
| --- | ---
| Mautic version |  v2.15.1
| PHP version |  7.0.33
| Browser |  Chrome

### Steps to reproduce
**Preconditions**
Have a standalone form which adds contact to segment "A" - Form A
Have a campaign which has segment "A" as a source - Campaign A
**Steps to reproduce**
1. Send Form A
2. Login to Mautic and click "Campaigns" on new contact (Contact A)
3. Verify that "Campaign A" is turned off
4. run "mautic:campaigns:rebuild" cron 
5. Verify that "Campaign A" is turned on

However, this is usually very long delay (up to 15 minutes) to get to be part of "Campaign A" as a user. Especially if we know, that one of Form Actions can be "Send E-mail to the user" and given campaign can track if user read that email or clicked a link.

Is there a way to speed up the progress? When I tested the same in version 2.12.2 the contact was in the campaign immediatelly
 
### Log errors
none

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by pavel-janicek** [comment]
Maybe fixable by https://github.com/mautic/mautic/pull/7606/commits/a3c297181dd1edf3a7d069d50c27ff6a385c4577

going to test it

**Comment by pavel-janicek** [comment]
Update: Confirmed, this can be fixed by applying PR #7606

**Comment by kuzmany** [comment]
Could you approve it directly in PR If works for you?

![image](https://user-images.githubusercontent.com/462477/59999302-ee913a80-9661-11e9-8152-3cc01475264f.png)

**Comment by pavel-janicek** [comment]
@kuzmany Done. Approving comment written. Also closing this issue
