### ISSUE TITLE
Export Contacts is not bound to any permission

### ISSUE THREAD

**Issue by wucherpfennig** [mautic/mautic#7645]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Currently anyone who has a "view" permission for contacts is able to export them as wanted. This is not a desired behavior. At least the "export" function should require "edit" or better **"full" permission**

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7
| Browser | Chrome

### Steps to reproduce
1. Grant Role access to "view" own or other contacts
2. User is able to export all
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by wucherpfennig** [comment]
If somebody could point me to the right direction I could provide PR including this feature...

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Happy to help with guidance on submitting a PR if it is still the case!

**Comment by wucherpfennig** [comment]
Well I am currently not able to check since all our production environment are still m2... As soon as m3 is stable enough I will retest and provide feedback

**Comment by RCheesley** [comment]
@wucherpfennig you can use mautibox.com to test - just select the base branch!

**Comment by medsun88** [comment]
Hi @RCheesley  @npracht 
I have multiple user in mautic.  I have created role, But did not find any permission where I can stop a user to export contact in Excel and csv.  
How can I restrict my user to export contacts ?

Regards
Sonu kumar

**Comment by npracht** [comment]
Hi @medsun88 you can test and review https://github.com/mautic/mautic/pull/5995 that introduce this feature ;)

**Comment by xcellenceit** [comment]
We face the same issue, I would really love to see it is released.
