### ISSUE TITLE
Contact Replies monitor marks all emails as read (Office365)

### ISSUE THREAD

**Issue by goranculibrk** [mautic/mautic#7649]
## Bug Description
Ok, I have one weird problem, which is causing the Mautic to ignore contact replies. I'm connecting to the Office365 email server. The configuration is ok, tested with success. When cronjob is triggered, or the command to fetch emails is run manually, all emails in my inbox are marked as read and Mautic ignores contact replies. I found success when I manually mark the email as read, but that doesn't solve the issue since all other emails are marked as read also, causing a possible issue of missing important emails. So, I've disabled the cronjob and all emails coming to my inbox are not marked as read. So that leads me to the way Mautic communicates with the email server. Whenever it fetches an email, either Mautic, or mail server (Exchange) will mark the message as read. I'm not sure why, but it seems to me that this is a bug.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.0.23

### Steps to reproduce
1. Configure Contact Replies in configuration
Username: user@domain.com
Password: xxxxxx
Server: outlook.office365.com
Certificate: SSL
Click test button - Success
2. Setup cron to monitor email replies:
`* * * * * php /var/www/mautic/public/app/console mautic:email:fetch > /dev/null 2>&1`
Log from manually running the command 
`0 emails processed for {outlook.office365.com:993/imap/ssl}INBOX with a criteria of UNSEEN`
`0 emails processed for {outlook.office365.com:993/imap/ssl}INBOX with a criteria of UID 42419:1000042419`
3. Check email inbox. All messages are marked as read.
4. Mautic is not registering Contact replies

### Log errors
NONE shown since it's not an error.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by goranculibrk** [comment]
@RCheesley Sorry, I cannot confirm this issue, I'm not working for a client that had that issue.

**Comment by RCheesley** [comment]
OK no worries, will close it down for now but if folk come across it in Mautic 3.x in the future please create a new issue and link to this issue!

**Comment by jlpetracca** [comment]
Hi! I am having the same problem.

- Mautic dont check readed messages
- Also Mautic mark all messages as read, so I can't monitor my own email account

My mautic version is v3.2.4
