### ISSUE TITLE
Zoho sunsetting v1 of API December 31 2019

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#7651]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Description
Zoho is sunsetting their v1 of the API  at the end of this year in favor of a REST v2. https://help.zoho.com/portal/community/topic/why-are-we-being-asked-to-migrate-apis-from-1-0-to-2-0. So the Zoho integration will have to be updated to use the new API before then or it will cease working.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 
| Browser |

**Comment by dennisameling** [comment]
Closing as #8272 has been merged :)
