### ISSUE TITLE
Points action at form submission are not working

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#7652]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
of you create a point action with the condition at form submission, the points are not added to contact. Bug on one time action or repeatable ones.

| Q   | A
| --- | ---
| Mautic version | 2.15.1 
| PHP version | 
| Browser | Google Chrome

### Steps to reproduce
1.  create a Point action on form submission
2. Add 10 points 
![image](https://user-images.githubusercontent.com/49391402/60188096-0833ad00-982f-11e9-9653-f324ba4c9859.png)
3. put the repeatable toggle on "Yes"
![image](https://user-images.githubusercontent.com/49391402/60188183-29949900-982f-11e9-836e-787713857a79.png)
4. Create a form and submit it with a contact email
5. Go into the contact history and see that the form has been submit but the contact don't get points.

### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
Are you sure you weren't not logged in in Mautic or you weren't test on localhost? 
Both cases are not trackable, and this  actions are not triggered.
I've tested and works for me.

**Comment by florentpetitjean** [comment]
Hello, 
You're right, I test again and it's working when no logged.
Sorry for that.

**Comment by npracht** [comment]
Don't be sorry it means you tested. And testing is community.
