### ISSUE TITLE
Email Campaigns seem to be sending emails at random times or not at all

### ISSUE THREAD

**Issue by scarlet12** [mautic/mautic#7654]
I don't know where else to turn, on the official Mautic website I am unable to register to ask the question there. When creating my email campaign, the emails do not send at the dates or times I have put them on. They send at random times and not even at the Cron Update times. 

I am also getting notifications that the campaign can't be executed yet the emails will randomly be sent throughout the day. I am not very tech savy so I am not sure how I can find a workaround or solve it.

**Comment by npracht** [comment]
Hi @scarlet12 .
Please give more information as it is in the issue template : mautic version, php version, how to reproduce, screenshots to illustrate ? logs error ?
