### ISSUE TITLE
Relative URL in focus item link breaks into a 500

### ISSUE THREAD

**Issue by AlbanL74fr** [mautic/mautic#7655]
## Bug Description
Only absolute links seem to work in focus item, in conjonction with click tracking.

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 
| Browser | Chromw

### Steps to reproduce
1. Create a focus item with a link
2. Insert a relative url as the href (i.e `/my-page`)
3. Set the focus item in a page
4. Logout from Mautic, or open another browser or instance
5. Trigger the focus and click the link
6. The encrypted link is rendered into 500 error page

Expected : www.whatever-hostname.com/my-page-name
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @AlbanL74fr is on your opinion `www.whatever-hostname.com` supposed to be your Mautic Instance URL or Website URL. Because IMO if relative and focus coming from mautic, I would say Mautic and that's why it seems logic to do not work.

**Comment by redlocal** [comment]
Hi in this issue i find the solution, beanstalkd was not running

https://github.com/pheanstalk/pheanstalk/issues/93
