### ISSUE TITLE
Contact in cc/bcc doesn't get form results in Sparkpost

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#7662]
## Bug Description
defined adresses in cc/bcc fields are ignored for post form submit actions - same issue as in #5967 - but in this case with Sparkpost 

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2
| Browser | any

### Steps to reproduce
1. define a post form submit action: email with bcc or cc set
2. submit form, contact receives message - but cc / bcc not
 
### Log errors
Sparkpost doesn't show any email for the cc / bcc part as being processed. looks like mautic is not submitting it.

**Comment by dsp76** [comment]
#5967

**Comment by npracht** [comment]
Closing in favor of #5967 as far as it is the same issue.
