### ISSUE TITLE
Scheduling in campaign always in UTC

### ISSUE THREAD

**Issue by MauriceW2** [mautic/mautic#7665]
When I schedule a campaign event, for example sending an email, the action is taken **2 hours late**. 

- Server timezone and PHP timezone are both Europe/Amsterdam.
- Default Timezone in Mautic settings is also Europe/Amsterdam
- Timezone in Mautic user profile is Europe/Amsterdam
- Contact custom field: 'mautic.lead.field.timezone' is set to Europe/Amsterdam

But Mautic still uses UTC, which is 2 hours behind Europe/Amsterdam, to take the action.

- No related errors in the Mautic error log.
- No related errors in the Apache server log. 

I only see two 'NOTICES' in the Mautic logging:

- [2019-07-04 02:18:54] mautic.NOTICE: PHP Notice - Undefined index: decisionPath - in file /var/www/clients/client2/web13/web/app/app/bundles/CampaignBundle/Controller/EventController.php - at line 238 [] []
- [2019-07-04 02:18:54] mautic.NOTICE: PHP Notice - Undefined index: eventType - in file /var/www/clients/client2/web13/web/app/app/bundles/CampaignBundle/Controller/EventController.php - at line 257 [] []

Mautic version: 2.15.1
PHP version: 7.1.0

I understood from previous readings that Mautic stores scheduled actions as UTC in the DB.
And then it calculates back when an action has to be taken.
It looks like this calculating back, does not work, or is skipped.

It may look like this issue on https://github.com/mautic/mautic/issues/837, however that was reported in 2015 and that topic is closed.

**Comment by npracht** [comment]
Hi @MauriceW2 can you test https://github.com/mautic/mautic/pull/7244 ? I am quite sure it fixes the issue.
Thanks

**Comment by MauriceW2** [comment]
Hi Norman, that looks promising. It indeed looks like the same sort of bug. I'll test https://github.com/mautic/mautic/pull/7244 asap and report back here.
Thanks

**Comment by MauriceW2** [comment]
I've implemented https://github.com/mautic/mautic/pull/7244. When I schedule a certain action it is now executed as oon as the cron job runs. (every 10 minutes)

In other words when I  schedule an action for example at 21:00H and the current time is before 21:00H, the action is executed as soon as the cron job is fired. So it does not wait. It is not scheduled.

Therefore I cannot check the scheduled time anymore.

**Comment by MauriceW2** [comment]
I found that when I remove the scheduled action and creat a NEW scheduled action in a campaign, this fix does work. But it only works for schedules that have a simple delay of, for example 30 minutes, or 1 hour, or 1 day.

But when I select: 'at a relative time period', select 0 days, and then set the time, the action is executed instantly.

I'm not sure if this is related to this bug, but this is what I experience after implementing this fix.

So how to reproduce:

- Create a campaign
- Add an action, for example, setting a tag
- Give it a name
- Select 'at a relative time period'
- Select 'days' in the dropdown
- At the left enter: 0
- Set the time to a time in the future. For example when it's 15:00, set it to 16:00
- Add a tag that needs to be added to the contact at the scheduled time

- Add the campaign to a contact
- Open the contact. The scheduled action should appear.
- In this case, instead of being scheduled, the action is taken as soon as the campaign cron job is triggered. The tag is added instantly at that moment, instead of waiting for the scheduled time.

![Screenshot_1](https://user-images.githubusercontent.com/6311149/60757996-e3e78580-a011-11e9-8818-4ef8140bf20c.png)

**Comment by npracht** [comment]
Hi @Maxell92, could you please have a look at previous comment? It is based on one of your PR.
Thanks !

**Comment by Maxell92** [comment]
Is this related to segments? That PR should change only behaviour of segments and date field - that means there are no time part.

**Comment by MauriceW2** [comment]
If this PR changes the date field, I think this might also 'touch' other parts of Mautic that use the date field, not only segments.

**Comment by MauriceW2** [comment]
Anyway, the initial issue seems to be solved. (Scheduling in campaign always in UTC).
So maybe it's better to close this issue.

I will open a new issue for the secondary problem taht showed after this one was solved.
(scheduled actions are executed instantly, instead of waiting for the scheduled time)

**Comment by RCheesley** [comment]
Closing this issue down as the original issue is resolved and subsequent issue is dealt with elsewhere.
