### ISSUE TITLE
Points Action "Is sent an email" does not work. No points assigned to lead

### ISSUE THREAD

**Issue by th-markus** [mautic/mautic#7666]
What type of report is this: - Bug report

## Description:
The Mautic Points Actions are all functioning correctly except for one.
The "Is sent an email" when triggered does log that an email was sent to a lead, but it does not assign points to the lead. 
Also, the "Limit to these selected emails" field in the "Add/Edit Point Action" page does not accept any values. It can't find no enter an email into it. It keeps defaulting to a blank value once you click on another form field/button. 

| Mautic version = v2.15.2  | 
| PHP version = 7.1.16 | 

### Steps to reproduce:
1. Create a new "Is sent an email" Points Action
2. Go to "Contacts" and copy the email of the lead at the top (You'll need this in a sec) 
3. Go to "Segments" and click on the "New" button, fill in some test values and tick tick all yes/no options to "Yes". Click on the "Filters" tab. Select "Email" (for contacts) from the drop-down then paste the previously copied email address into the "filter value" text-field. Click on "Save and Close".
5. Go to "Channels -> Emails". Click on the "New" button. Select the "New Segment Email" option. Select any template and fill in some dummy data into the fields to the right. Be sure to select the segment you just created in the "Contact segment". Click on "Save and Close".
6. Click on the "Send" button.
7. Go to the "Contacts" page again. If you click on the contact which email was copied previously you'll notice that a log has been added which specified that an email was sent. But, the points which should have been added via the points action wasn't added.

Extra info: Mautic is setup to send emails immediately. Not via a cron job.
 
### Log errors: 

No error logs are created. Tested with a clean log and no logs where present after the test.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
