### ISSUE TITLE
Mautic update 2.15.1 PHP Warning - ZipArchive::extractTo()

### ISSUE THREAD

**Issue by kidfilkings** [mautic/mautic#7667]
## Bug Description
Updating to version 2.15.1 failling when extracting the package.

Mautic version: 2.15.0
PHP version: 7.1.27 
Browser: any

### Steps to reproduce
1. Click Notifications
2. Click 'Update Now' link.
 
### Log errors
The Mautic update could not complete successfully because of the following error: Could not extract the contents of the ZIP archive to the filesystem.

mautic.WARNING: PHP Warning - ZipArchive::extractTo(): Permission denied - in file /var/www/html/app/bundles/CoreBundle/Controller/AjaxController.php - at line 465 [] []

###Environment Permissions
![image](https://user-images.githubusercontent.com/48958144/60671109-be5b5000-9e48-11e9-820c-7e17fa814438.png)

![image](https://user-images.githubusercontent.com/48958144/60671147-d501a700-9e48-11e9-84c9-e2996ed9a314.png)

**Comment by kidfilkings** [comment]
It's clear it's a matter of permission, but where?

**Comment by autoize** [comment]
Email us at info@autoize.com and we can help with getting the Mautic instance updated. This isn't a bug report but rather seems like an issue with the environment of the server. Do you have PHP running as mod_php or php-fpm? Also, is the php-zip extension installed?

**Comment by npracht** [comment]
Hi @kidfilkings ! This a configuration issue not a bug. Please join Slack to chat with other community members and find your solution.

**Comment by AlessandroFavretto** [comment]
hi @kidfilkings, did you solve this issue? i have same error message during upgrade 2.15.1 to 2.15.2.

Regards

**Comment by vdavid** [comment]
I'm getting the same when trying to upgrade to 2.16. Anyone solved this yet?
