### ISSUE TITLE
"Send a Webhook" campaign action doesn't accept to save two distinct keys that have the same value

### ISSUE THREAD

**Issue by albanleandri** [mautic/mautic#7668]
## Bug Description
If two keys have the same value, only one will remain. It's for Headers, or Data.

| Q   | A
| --- | ---
| Mautic version | 2.14.2
| PHP version | 
| Browser | Chrome

### Steps to reproduce

1. Start a campaign and add a "Send a webhook" action
2. Add the folowing rows to Headers
- Content-Type : application/json
- Accept : application/json
3. Save action
4. Save campaign
5. Open Campaign builder again, and open action Send a Webhook
Result: only one of the keys above remains. The other has disappeared.
 
### Log errors

**Comment by AlbanL74fr** [comment]
@kuzmany FYI

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by mahmood728** [comment]
Yes, I use mautic 3, but the problem persists

**Comment by stfnet** [comment]
It seems this bug is still present in Mautic 4.4.12 that I am using.
Any update ?
