### ISSUE TITLE
Issues with submit button when manually embedding the form

### ISSUE THREAD

**Issue by Aerendir** [mautic/mautic#7669]
## Bug Description
I've created a form and embedded it manually in my page (I needed to add some Bootstrap styling).

The form has some required fields.

I've embedded in the page the javascript code required to handle the form submission and validation.

When I submit the form without any data, the form correctly displays the errors but the button text is set to `undefined`.

The error happens with my edited form and also if I embed the code provided directly by Mautic.

Any guidance or help about how can I debug this problem?

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| Browser | Chrome 75.0.3770.100

### Steps to reproduce

1. Create a form
2. Add a mandatory field
3. Manually embed the javascript code and the form code in a page in Wordpress
4. Try to submit the form

The error described above should happen.
 
### Log errors

No errors are logged in the Chrome console.

**Comment by npracht** [comment]
Something in you mautic logs ?

**Comment by Aerendir** [comment]
@npracht , where can I see Mautic logs? This is an error coming from Javascript and in the console there are no errors. Are there any places where I can search for errors?

**Comment by npracht** [comment]
In your mautic instance, top right (setting), logs.

**Comment by Aerendir** [comment]
Did you mean System Info > Logs?

It is empty...

**Comment by npracht** [comment]
Hello @Aerendir can you test https://github.com/mautic/mautic/pull/7818
Not sure this is exactly the issue it is solving, but it could maybe solve yours at the same time ? :)

**Comment by npracht** [comment]
Without extra information and being an old issue, let close it.

**Comment by ddanninger** [comment]
For anybody who comes across this issue. I had the same problem. Adding 'submitMessage' to the MauticLang variable helped for me.

**Comment by coreyworrell** [comment]
@ddanninger where and how did you add that?
