### ISSUE TITLE
Timezone error in logging

### ISSUE THREAD

**Issue by MauriceW2** [mautic/mautic#7670]
I experience problems in scheduled campaign actions. They're not triggered when they have a time schedule. For example, when I want a mail to be delayed for 30 minutes, of when I want an email to be sent at a certain time today.

Those mails (or other actions) are not executed.

In the Mautic log I have these errors:

`[2019-07-05 07:20:34] mautic.ERROR: CAMPAIGN: DateTimeZone::__construct(): Unknown or bad timezone () [] []`

`[2019-07-05 07:29:52] mautic.NOTICE: PHP Notice - date_default_timezone_set(): Timezone ID '' is invalid - in file /var/www/clients/client2/web13/web/app/app/bundles/CoreBundle/EventListener/EnvironmentSubscriber.php - at line 69 [] []`

Mautic version: 2.15.1
PHP version: 7.1.0

**Comment by npracht** [comment]
Hi @MauriceW2 is there anyway to reproduce it 100% of case ?
I don't have this issue.

**Comment by MauriceW2** [comment]
Hi Norman , no unfortunately not. I'm not able to reproducte it on another Mautic instance.

The only way I can reproduce is by copying all files and export/import the full DB.

I've several Mautic instances and only on one, this error occurs. I've installed Mautic on different servers, and there the issue does not occur.

It might be related to a MySQL curruption somewhere, since when copying everything (files+DB), the errror moves with it.

**Comment by npracht** [comment]
Then i believe this is a question of configuration and we cannot help you more here. I'll suggest you to join Slack chat to speak with other community members. Some of them may have meet that issue and found the way to fix it.
Thanks a lot for taking time to share your experience with the community.

**Comment by MauriceW2** [comment]
In the server logging, I see this (please note a 2 hour time difference between UTC and my local server time). It relates to the second Mautic error.

`[Fri Jul 05 09:29:52.674669 2019] [fcgid:warn] [pid 10361] [client 185.202.167.48:43607] mod_fcgid: stderr: PHP Notice:  date_default_timezone_set(): Timezone ID '' is invalid in /var/www/clients/client2/web13/web/app/app/bundles/CoreBundle/EventListener/EnvironmentSubscriber.php on line 69, referer: https://app.mydomain.nl/app/s/sysinfo`
