### ISSUE TITLE
database migration error 

### ISSUE THREAD

**Issue by mithileshthakur** [mautic/mautic#7671]
## Bug Description
The more details the better...

I am facing issues related mautic database migration 
below issue 
run this command 
$ php app/console doctrine:schema:update --force Updating database schema... [Doctrine\DBAL\Exception\DriverException] An exception occurred while executing 'CREATE INDEX phone_search ON leads ( phone)': SQLSTATE[42000]: Syntax error or access violation: 1069 Too many keys speci fied; max 64 keys allowed [Doctrine\DBAL\Driver\PDOException] SQLSTATE[42000]: Syntax error or access violation: 1069 Too many keys speci fied; max 64 keys allowed [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1069 Too many keys speci fied; max 64 keys allowed doctrine:schema:update [--complete] [--dump-sql] [-f|--force] [--em [EM]] [-h|-- help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n |--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug ] [--] <command>

**Comment by npracht** [comment]
Hi @mithileshthakur you have too many custom fields. mySQL offers a limit of 64 indexes. So if you want to add index on the new custom fields, you may first drop index of others. This is a known technical limitation.

**Comment by altacshekhar** [comment]
> Hi @mithileshthakur you have too many custom fields. mySQL offers a limit of 64 indexes. So if you want to add index on the new custom fields, you may first drop index of others. This is a known technical limitation.

actually i  have droped created index from table then run command
php app/console doctrine:schema:update --force
after getting same error. 
provide me solution steps for this issue
