### ISSUE TITLE
Scheduled actions are executed instantly, instead of waiting for the scheduled time

### ISSUE THREAD

**Issue by MauriceW2** [mautic/mautic#7673]
When I schedule an action in a campaign, and choose:

- 'at a relative time period'
- select 0 days
- and then set a future time

the action is **executed instantly**, instead of waiting until the scheduled time.

How to reproduce:
- Create a campaign
- Add an action, for example, setting a tag
- Give it a name
- Select 'at a relative time period'
- Select 'day(s)' in the dropdown
- At the left enter: 0
- Set the time to a time in the future. For example when it's 15:00, set it to 17:15
- Add a tag that needs to be added to the contact at the scheduled time
- Add the campaign to a contact
- Open the contact. The scheduled action should appear after a short while. (when the campaign cron runs)

In this case, instead of being scheduled, the action is taken as soon as the campaign cron job is triggered. The tag is added instantly at that moment, instead of waiting for the scheduled time.

![60757996-e3e78580-a011-11e9-8818-4ef8140bf20c](https://user-images.githubusercontent.com/6311149/60826599-791f8100-a1ae-11e9-87e4-2a8ce24eb460.png)

Mautic version: 2.15.1
PHP version: 7.1.0

**Comment by npracht** [comment]
@MauriceW2 can you check #7676 and confirm your campaign is configured the same way ?

**Comment by npracht** [comment]
No feedback, closing in favor of https://github.com/mautic/mautic/issues/7676 more complete.
