### ISSUE TITLE
Import/Cron Jobs Not Working

### ISSUE THREAD

**Issue by Jzyehoshua** [mautic/mautic#7674]
The cron jobs are not working to import contacts. The documentation here says a cron job must be added to import contacts as follows:

php /path/to/mautic/app/console mautic:import

https://www.mautic.org/docs/en/contacts/import.html

I know the command works because I used an SSH client to run the command and execute a background import of contacts using the php contact script. However, it only works when ran manually, not as a cron job every 10 minutes. As such, I suspect that the following cron job scripts are also not working:

https://www.mautic.org/docs/en/setup/cron_jobs.html

**Comment by Jzyehoshua** [comment]
I was able to get the imports feature working again. It appears that changing the configuration settings for contacts from anything but 0 makes the import function stop working. However, the import background feature is still not executing due to non-existent file paths for the cron jobs. The documentation here says a cron job must be added for:

php /path/to/mautic/app/console mautic:import

https://www.mautic.org/docs/en/contacts/import.html

However, again, there is no console folder in the app folder. It appears that mautic did away from this folder configuration at some point with its updates, so all of the documentation saying to do cron jobs to the console folder is outdated.

**Comment by npracht** [comment]
Hi @Jzyehoshua ! Is this Crons added to your crontab ? Because the import command is not mentioned here: https://www.mautic.org/docs/en/setup/cron_jobs.html

**Comment by TeeJayK** [comment]
I am having the same issue. I ran the commands manually so I know that the paths are correct.
