### ISSUE TITLE
Campaign Trigger Not Working Correctly

### ISSUE THREAD

**Issue by Jzyehoshua** [mautic/mautic#7677]
When using campaign:trigger to initiate emails, the first batch appears to execute correctly, but after that I get a long list of errors which I would like to address. 

The following three errors just keep reoccurring endlessly. 

/usr/sbin/memory: fork: Cannot allocate memory
2019-07-09 18:27:58 fork failed for TLS check
2019-07-09 18:29:05 lhkycW-006mS7-Uy failed to fork automatic delivery process: Cannot allocate memory

**Comment by npracht** [comment]
Hello @Jzyehoshua please fulfill the issue template given. There is no change we can reproduce with your material and then no chance to solve the issue.
Also, `Cannot allocate memory` seems being a configuration issue of the memory you allocate on the PhP server side.
