### ISSUE TITLE
Boolean fields does not render as expected

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#7678]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I created a custom Boolean field, it does not render well when I update it, this issue happend when I applied patches #7375 and #7376 .

Further investigating this issue, it seems the patch #7376 causes this issue, when I revert it back, it worked as expected.

I checked the error logs there was not any issue there, I also check the database the field is saved correctly but it does not render on the front end as it should.

![image](https://user-images.githubusercontent.com/12627658/60968853-c6bef980-a326-11e9-8a78-a9bde11297b9.png)

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.27
| Browser | Chrome

### Steps to reproduce
1. Create a custom field with Boolean 
2. Apply patches #7375 and #7376 
3. Try to update a contact with with Boolean field
 
### Log errors
No logs for this

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @mabumusa1 this PR #7376 is not merged and closed. You shouldn't wok with it.
Can you try again without this PR ?

Thanks

**Comment by mabumusa1** [comment]
Hi @npracht  I removed the PR it worked as expected. Thanks for your support
