### ISSUE TITLE
Cannot Import Multiselect Fields

### ISSUE THREAD

**Issue by pstevens71** [mautic/mautic#7680]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Trying to import a custom multi-select field in form:
"value1|Value2|value3" and get the error:

(#3) An exception occurred while executing 'UPDATE leads SET past_email_lists = ? WHERE id = ?' with params ["DATA1|DATA2|DATA3", 5048]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'past_email_lists' at row 1

| Q   | A
| --- | ---
| Mautic version |  2.15.1
| PHP version | 7.1
| Browser | 

### Steps to reproduce
1. Import some records with a multi-select field.
2. No rows are imported, each record shows the error above.
 
### Log errors

["DATA1|DATA2|DATA3 (NOTE: DATA Removed for privacy)", 5048]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'past_email_lists' at row 1
[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by pstevens71** [comment]
OK, upon further investigation, looks like my multiselect values are greater than 255 characters.  Is it possible to change the character limit in the database to like 2000?   or is it a better idea to change the field type to TEXT instead of VARCHAR?

**Comment by npracht** [comment]
Please test https://github.com/mautic/mautic/pull/7596

**Comment by pstevens71** [comment]
Nice!  Thanks @npracht .   Question:  The fix looks like it will fix the issue for future Multi-Select fields created.  Can I just change an existing one in the database to a TEXT field?
