### ISSUE TITLE
Move form validation system to HTML5 standard

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#7683]
# Description
Today, the form validation is managed by Javascript and generates extra text (div) into the page that changes the structure of the page itself (quite annoying on mobile device).
We could move the system to standard HTML5 form validation which is now supported by all the browsers ?
https://pageclip.co/blog/2018-02-20-you-should-use-html5-form-validation.html

**Comment by RCheesley** [comment]
@npracht is this still relevant in Mautic 3.x? If so can you pop a thread on the ideas forum to discuss?

**Comment by npracht** [comment]
https://forum.mautic.org/t/move-form-validation-system-to-html5-standard/15465
