### ISSUE TITLE
Broken tracking links e-mails

### ISSUE THREAD

**Issue by vgallotti** [mautic/mautic#7684]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | Np

## Description:
When I add a link to an email, it is replaced for a tracked version. The problem is that the domain is wrong and every link is broken.

Example:

https://mautic.polis.mba/asset/4:programa-mba-projetos

is replaced for

http://url9399.polis.mba/wf/click?upn=sy-2F98sPqCeAdo-2BDP8wpILnAqFZyHpeH2R6aX-2FrFJFRBS8-2BJaaOxyX8wU4dqcpVAc5cXqWJ3crAnmlihFkftWRmEfn8csWS6xQAv5KuGfE4U-3D_n5CWByzVGoyZ-2BxcF09QZIA-2B2dKgFQzGtirDAxP3E9LqXvj7iFihPeoWffE5oxetvJLdCKNnOC4ZMgwDhFJD4u2rDzWglZl5X2-2BtO1JJ2tjrgkzBe-2Fru1ZDFIG1IlFmbk9gMf312Tclp0GjiAhVZi6hGOTKmShGT-2FTbfpisId3T8C4MfK-2BRWOIriSQZi9-2FgKIVFfYde2Ny7Oe-2F-2Bu1-2BSXIF9pLUteXklIDSdaELxqflvk-3D

The mautic address is https://mautic.polis.mba

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.16.0
| PHP version | 7.2

### Steps to reproduce:
1. Add any link to a button inside an e-mail. Send that email to any contact.
 
### Log errors: 

No error logged today by Mautic

**Comment by npracht** [comment]
What is the root of your instance in the configuration page ?

**Comment by vgallotti** [comment]
> What is the root of your instance in the configuration page ?

https://mautic.polis.mba/

**Comment by npracht** [comment]
and your email router?

**Comment by gianluca932** [comment]
I've the same problem, it happens after we install Cloudflare on our environment. 
My links work on email preview instead of email, that change with url6621.mywebsite.com.
It's may something related to DNS changes. I don't know, append my hoping to this conversation.

**Comment by devilmind81** [comment]
Hi,
I have the same issue on the fresh Mautic installation on ubuntu.
Can someone help here?
It is impossible to test campaigns....

Thanks in advance

**Comment by devilmind81** [comment]
I noticed that.
The email tracking isn't working if I try to open the email from the same browser where i logged in mautic.
But I open the email from another browser, better if it is in another location (you could try to install a VPN Plugin to simulate it), it will work.
Probably in mautic there are some checks that managing that.
Let me know if this happening for someone of you also.

**Comment by ricardojlrufino** [comment]
You're right, that's why I use the curl command to test links.

I confirmed that the fact is to use Kubernetes using an Ingress / Loadbalancer.

What I had to do was create a direct path to Mautic's tcp port, because something is getting lost in the middle.

**Comment by ricardojlrufino** [comment]
Side effect: FORMS NOT WORKING:
My workarround is use this.:
![image](https://user-images.githubusercontent.com/515675/64206955-0101ce80-ce72-11e9-89b8-406084772985.png)

![image](https://user-images.githubusercontent.com/515675/64207048-33abc700-ce72-11e9-8db1-692043b9f441.png)

**Comment by ricardojlrufino** [comment]
Using 2 urls has broken multiple tools... File Manager for LeadPages for example...

**Comment by gucio1200** [comment]
Turn on proxy-protocol on both sides or put "'track_private_ip_ranges' => true" to local.php
mautic has to have correct X-Real-IP from client, otherwise it wont track... 8h of debugging..

**Comment by RCheesley** [comment]
See comment here: https://github.com/mautic/mautic/issues/7756#issuecomment-614784429 for a solution.
