### ISSUE TITLE
Creating New Email under Channels

### ISSUE THREAD

**Issue by robstarr** [mautic/mautic#7686]
What type of report is this:

[mautic-email-error.zip](https://github.com/mautic/mautic/files/3388340/mautic-email-error.zip)

| Q | A
| Yes | ---
| Bug report? | Yes

Description:
Cannot create new emails under channels

If a bug:
Q	A
Mautic version	2.15.1
PHP version	7.2.20
Steps to reproduce:
Click "Channels"
Click "Emails"
Click "New"
Select Either "New Template Email" OR "New Segment Email"
Fill out required info on form
Click on "Apply" OR "Save and Close", buttons are greyed out and Error appears in console:

### Log errors
Access to XMLHttpRequest at 'https://www.mywebsite.com/cituam/s/emails/new?mauticUserLastActive=1&mauticLastNotificationId=' (redirected from 'https://mywebsite.com/cituam/s/emails/new?mauticUserLastActive=1&mauticLastNotificationId=') from origin 'https://mywebsite.com' has been blocked by CORS policy: Request header field x-csrf-token is not allowed by Access-Control-Allow-Headers in preflight response.

Also, using the Builder and clicking "Apply" produces the same CORS policy error.

Attached is ZIP file with MP4 movie showing the steps taken to produce the error.

**Comment by npracht** [comment]
Hi @robstarr the message seems clear, there is an issue with your CORS policy. This is a configuration issue. Please check all the issues related that found a solution: https://github.com/mautic/mautic/issues?utf8=%E2%9C%93&q=is%3Aissue+CORS+
