### ISSUE TITLE
Campaign Trigger

### ISSUE THREAD

**Issue by videfrancisco** [mautic/mautic#769]
Is this possible add triggers by previous action?
Because actually triggers i can't send email for example: first e-mail delay 1 day, second e-mail 1 day and 30 minutes after previous right?

**Comment by alanhartless** [comment]
To support this, you would add them on the same level and just offset the wait time accordingly. 

![](http://alan.direct/drop/2015-09-18_23-00-11.png)

If you _really_ wanted a day and 30 minutes, you would have to use a minute offset with something like 2910 minutes (60 minutes * 24 hours * 2 days + 30 minutes)
