### ISSUE TITLE
Tracking Pixel - WP Not Working

### ISSUE THREAD

**Issue by gaberoz1** [mautic/mautic#7690]
Hi Guys,

I have set up a campaign in Mautic and also set up the plug-in inside of Word Press for tracking. The campaign is set up in a way where visitors get transferred between segments related to step of the campaign they are on. Unfortunately the tracking pixels are not tracking at all so the visitor gets lost in the segments created. 

I've done troubleshooting through CRONS and that hasn't helped. I have also taken off the "/" on the ends of all URLS.

Thanks in advance!

**Comment by npracht** [comment]
Hi @gaberoz1. This is clearly incomplete. Please complete the standard issue template to know all the information.
