### ISSUE TITLE
Connecting Amazon SNS with Mautic

### ISSUE THREAD

**Issue by franco011** [mautic/mautic#7691]
I created a subscription in Amazon SNS to manage emails completed and bounced in Mautic.

When I request confirmation, it remains pending.

I have verified on the Mautic side and there are no logs.

The SMTP credentials are well configured and working.

(In this same Amazon account I have a subscription accepted for another instance of Mautic, I do not know if that influences.)

**Comment by mabumusa1** [comment]
@franco011 please send more details about the Mautic instance and some screenshots of the configuration

**Comment by franco011** [comment]
> @franco011 please send more details about the Mautic instance and some screenshots of the configuration

Hello,

Thanks for your help.

I'm using Mautic Bitnami on Amazon SES

Here I share the capture of the instacia, if you need more information tell me.

https://drive.google.com/file/d/1spqVGDXD9YGkmL_yzBew7QvVQ6mlGVhx/

**Comment by mabumusa1** [comment]
@franco011, please move this to the forums. this is not a bug it is a configuration issue that you need to handle.

I think you did not select SES configuration correctly in Mautic

**Comment by franco011** [comment]
@mabumusa1 

I have searched if there is any configuration difference with the other instance that is working correctly.

The only thing that I see differently is that when you access the link's mautic site, it starts https://a.site.com/ and automatically redirects to https://www.a.site.com/

In the other mautic installation (where the SNS works well) that does not happen. It is always https://a.site.com/

This may be affecting the callback?
How can I correct it?

**Comment by virgilwashere** [comment]
The callback URL you use in SNS subscription is based on the SITE_URL

`https://my.mautic.site/mailer/amazon/callback`

Or `http://my...` if not using SSL.

**Comment by franco011** [comment]
Hello,

I have come to one solution.

Apparently when you run `sudo /opt/bitnami/bncert-tool` to generate the SSL Certificate changes are made in the file `/opt/bitnami/apache2/conf/bitnami/bitnami.conf`

The solution was to change the label of the complete port 80.

This is the original:

```
<VirtualHost _default_:80>
  DocumentRoot "/opt/bitnami/apache2/htdocs"
  RewriteEngine On
  # BEGIN: Enable HTTP to HTTPS redirection
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]
  # END: Enable HTTP to HTTPS redirection
  # BEGIN: Enable non-www to www redirection
  RewriteCond %{HTTP_HOST} !^www\. [NC]
  RewriteCond %{HTTP_HOST} !^(localhost|127.0.0.1)
  RewriteCond %{REQUEST_URI} !^/\.well-known
  RewriteRule ^(.*)$ http://www.%{HTTP_HOST}%{REQUEST_URI} [R=permanent,L]
  # END: Enable non-www to www redirection
  <Directory "/opt/bitnami/apache2/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    <IfVersion < 2.3 >
      Order allow,deny
      Allow from all
    </IfVersion>
    <IfVersion >= 2.3 >
      Require all granted
    </IfVersion>
  </Directory>

  # Error Documents
  ErrorDocument 503 /503.html

  # Bitnami applications installed with a prefix URL (default)
  Include "/opt/bitnami/apache2/conf/bitnami/bitnami-apps-prefix.conf"
</VirtualHost>
```
This is the new one:

```
<VirtualHost _default_:80>
  ServerName app.example.com
  ServerAlias www.app.example.com
  RewriteEngine On
  RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
  RewriteRule ^(.*)$ http://%1$1 [R=permanent,L]

  DocumentRoot "/opt/bitnami/apache2/htdocs"
  <Directory "/opt/bitnami/apache2/htdocs">
    Options Indexes FollowSymLinks
    AllowOverride All
    <IfVersion < 2.3 >
      Order allow,deny
      Allow from all
    </IfVersion>
    <IfVersion >= 2.3 >
      Require all granted
    </IfVersion>
  </Directory>

  # Error Documents
  ErrorDocument 503 /503.html

  # Bitnami applications installed with a prefix URL (default)
  Include "/opt/bitnami/apache2/conf/bitnami/bitnami-apps-prefix.conf"
</VirtualHost>
```

In addition to port 443, change the "Rewrite" for these:

```
ServerName app.example.com
ServerAlias www.app.example.com
RewriteEngine On
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
RewriteRule ^(.*)$ https://%1$1 [R=permanent,L]
```

Then restart apache.

I'm a novice, I do not understand what the problem was but now everything works perfect!

Thanks for your help.
