### ISSUE TITLE
folder  /mautic/s/dashboard doesn't exist

### ISSUE THREAD

**Issue by WhiteTiger-IT** [mautic/mautic#7694]
## Bug Description
After installation, File not found with folder  /mautic/s/dashboard
Mod_rewrite is activated and there is also .htaccess.
**What is missing is the "s" folder and all its contents**.
The installation was done with Softaculous

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2.20 (FPM service from Nginx as proxy)
| Browser | Chrome, in Private mode

### Steps to reproduce
1. Installed with Softaculous, in Plesk Onyx 
2. Installed, I simply called the URL
3. Tested with various PHP configurations
 
### Log errors
app/log is empty

**Comment by virgilwashere** [comment]
`/s` is a Symfony PHP framework virtual folder generated from contents `app/bundles/BundleName/Assets`.

I don't think your nginx vhost config is working. 

I have a pinned repo on @virgilwashere with some nginx config examples (l need to push some changes).  I also noticed a "better mautic nginx" repo recently.

**Comment by npracht** [comment]
This is a configuration/installation issue. Please see with your webmaster and Softaculous/Plesk Onyx.
