### ISSUE TITLE
Campaign from segment don't work

### ISSUE THREAD

**Issue by mamontovalida** [mautic/mautic#7695]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | last
| PHP version | PHP Version 7.0.33
| Browser | Yandex

1. I created a new New Standalone Form
2. Get an intagration with plagin Webinar Ignions
3. Set action when complete the form, contact add to segment.
4. Published a campaign from this segment.
5. New test-contacts from my PC add to segment, but don't add campaign.
6. Another contact add also to campaign, but nothing happens.

![2019-07-17_13-54-04](https://user-images.githubusercontent.com/53002624/61372998-40b02f00-a8a1-11e9-9234-58a3053c1944.png)
![2019-07-17_14-45-07](https://user-images.githubusercontent.com/53002624/61373082-81a84380-a8a1-11e9-88b7-5dc18bda4297.png)

But campaign from form is working. What's wrong? We need use  New Standalone Form for records UTM

**Comment by npracht** [comment]
Hi @mamontovalida ! This is not clear sorry:
1. What is `plagin Webinar Ignions`?
2. What is `Mautic version last`? If we ask the question, it is because it is important.
3. `But campaign from form is working. What's wrong? We need use New Standalone Form for records UTM`. So it works or it doesn't ?

So you have something in your logs? What happens when you run your campaign Crons?

**Comment by marketic038** [comment]
We are facing the same issue :

This cron is not working : mautic:campaigns:trigger using cronjob .
I run it manually using SSH and it works .

Is it a bug with Mautic 2.15.2 ( Stable) .?

**Comment by npracht** [comment]
Hi @marketic038. 2.15.2 is stable. Also, without more detailed information, we'll close this issue for lack of information.

**Comment by marketic038** [comment]
Hi,

The issue was fixed later. Few file permission issues were there .
Please close the issue now.

**Comment by npracht** [comment]
Thanks for you feedback. In the future please think about sharing those feedback, this is a lot of administration for us to review all pending issues etc. Feedback is highly appreciated ;)
Have a nice day.
