### ISSUE TITLE
Mautic Freeze (504 error) when notification table is to big.

### ISSUE THREAD

**Issue by pedrosoares** [mautic/mautic#7696]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Something happened in one of my campaign and the notification table get to big (8 billion records), resulting in the mautic return error 504 in any page.

| Q   | A
| --- | ---
| Mautic version |  2.15.1
| PHP version |  7.2.0
| Browser | Any

### Steps to reproduce
1. Install Mautic
2. Get notification table to big.
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @pedrosoares ! This is a bit short, i have 500 mautic instances installed and i don't have the issue even once.
Why do you have so many notifications ? You can empty this table and check why it is so big and fix the issue ?

**Comment by pedrosoares** [comment]
- Why do you have so many notifications ? Some of my campaign was firing multiples errors, i'm solving that problem. 
- You can empty this table and check why it is so big and fix the issue ? That was my solution, clear the table, i opened this ticket to report this problem and to alert others users about it because i was searching for 3h to discover where the problem come from.
