### ISSUE TITLE
Gmail - Monitored Inbox Settings

### ISSUE THREAD

**Issue by 546451cc** [mautic/mautic#7697]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.0
| Browser | Firefox / Chrome

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

Hi I Have Gsuite Basic, And when configure mautic show this error 
"Error communicating with the IMAP server: Can't connect to gmail-imap.l.google.com,993: Network is unreachable"
Here is my configuration:

![gmail](https://user-images.githubusercontent.com/53021603/61415758-3a2cb200-a8b7-11e9-8e35-0fc09c8ec5a2.jpg)

![gmail 2](https://user-images.githubusercontent.com/53021603/61415429-351b3300-a8b6-11e9-9c2e-f797e4696ee4.jpg)
![gmail 3](https://user-images.githubusercontent.com/53021603/61415487-6431a480-a8b6-11e9-847f-db24faea481e.jpg)

I try all, and simple always show that error, why? please, help,
Thanks!

**Comment by AndrassGray** [comment]
@npracht : the Plugin label seems wrong here. OP is trying to connect his monitored inboxes.

I had a similar (or maybe even identical??) case the other day. Client had php7.1-mcrypt installed, but not the mcrypt package itself, leading to identification errors with the Google imap-server.

**Comment by RCheesley** [comment]
It looks like this is an issue with server setup/configuration rather than Mautic itself, so closing the issue.
