### ISSUE TITLE
Mautic Gmail outbound email integration 

### ISSUE THREAD

**Issue by enigma-bit** [mautic/mautic#7698]
Hi guys I've been attempting to link my mautic to my gmail account but everytime I attempt to test the connection, I get this error. 

Connection could not be established with host smtp.gmail.com [Network is unreachable #101] Log data: ++ Starting Swift_SmtpTransport !! Connection could not be established with host smtp.gmail.com [Network is unreachable
#101] (code: 0)
++ Starting Swift_SmtpTransport !! Connection could not be established with
host smtp.gmail.com [Network is unreachable #101] (code: 0)
Please help

**Comment by RCheesley** [comment]
Hi there,

Sounds like this is an issue with ports not being open on your hosting, as the connection can't be established to Gmail. Please ask your hosting provider to help you troubleshoot!
