### ISSUE TITLE
Sequential Campaign Schedules bug

### ISSUE THREAD

**Issue by MauriceW2** [mautic/mautic#7699]
When I have more than 1 scheduled action in a campaign, only the first is scheduled correctly.
The second schedule is always executed instantly after the first one. It does not wait until its scheduled time.

### Steps to reproduce

1. Add an empty segment
2. Create a campaign, set the emtpy segment as 'trigger'
3. Add a scheduled action to the campaign
4. Select 'at a relative time period'
5. Select 0 days
6. Set the time to a future time today
7. Then add a second scheduled action to the campaign
8. Select 'at a relative time period'
9. Select 0 days
10. Set the time to a future time today, AFTER the scheduled time for the first action
11. Connect Scheduled action 1 to scheduled action 2
12. Add a new contact
13. Add the campaign to the contact
14. Check the times when both scheduled actions are executed

See screenshot below for my test setup:
![bug-mautic-schedule](https://user-images.githubusercontent.com/6311149/61467055-49753380-a97b-11e9-8c23-220ce56bc078.png)

Mautic version: v2.15.2-beta
PHP Version : 7.1.0
Browser : Chrome 75.0.3770.100 (Official build) (64-bits)

There are no errors.

**Comment by AlbanL74fr** [comment]
Good catch!

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by moiskydog** [comment]
Hi, I found this bug, so I cannot set schedule events in a row on the same day.

Mautic version: 3.3.1
PHP Version : 7.4.16
Browser : Chrome 94.0.4606.61（Official Build） （arm64）
