### ISSUE TITLE
[Feature] Add a API endpoint for do not contact

### ISSUE THREAD

**Issue by zapur1** [mautic/mautic#770]
Hi,
It would be good to either have a specific '/doNotContact' API endpoint or for the data to be returned when retrieving '/leads', e.g. with a field of of say "donotcontact"

**Comment by ipso** [comment]
+1, handling unsubscribe/do not contact through the API is a critical feature for my intended use case. :(

Adding it into the /leads or /contacts API so existing create/edit functions can be used would be preferred.

**Comment by escopecz** [comment]
Added to 2.3
