### ISSUE TITLE
Add Campaign Source: "added/removed Tags"

### ISSUE THREAD

**Issue by dgram** [mautic/mautic#7700]
hey,

because of the complexity and the amount of data in some projects it would be nice to have an feature to start campaigns by "campaign source" - "added/removed Tags".

With this feature it will be possible to organize the Contacts much better and flexible, because at this stage the lists/segments will be bloated and the possibilities are inflexible.

When its implemented it would be possible to have a hands of lists/segments and work the rest with tags (i.e. Tag Categories as - Action, Checkout Steps, Topics/Interests, Member Type, Trigger etc.) here i would be mentioned https://www.activecampaign.com/learn/guides/what-are-tags/ this is an good instruction at the topic tags and organization.

With an combination of an Tag Manager this would skyrocket mautic :)

If we can chat or something else about the development introduction about this, we could help by developing this feature or something else.

regards, daniel

**Comment by npracht** [comment]
Hi @dgram ! Can't you already filter your segments by tag ?
