### ISSUE TITLE
Setting Field Values for JavaScript embedded Forms

### ISSUE THREAD

**Issue by silvermind** [mautic/mautic#7702]
Hi there

I really like to auto embedded Javascript Forms ala:
`<script type="text/javascript" src="//mautic.demo/form/generate.js?id=1"></script>`

is it already possible to provider some values for the fields? (mostly interested in setting a hidden fields value) something like:
`<script type="text/javascript" src="//mautic.demo/form/generate.js?id=1?mauticform-field-1=SAMPLE-VALUE"></script>`

Is it possible with the iframe option?

**Comment by npracht** [comment]
Hi @silvermind, please join the community chat on slack to discuss this kind of workaround. We store here the bug reports.
Thanks !
