### ISSUE TITLE
Paged forms don't provide navigation back from last page

### ISSUE THREAD

**Issue by aer0s** [mautic/mautic#7712]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.15.0 
| PHP version | 7.1.27
| Browser | All
| Docker | mautic/mautic:latest

### Steps to reproduce
1. Create a form
2. Add Page Breaks
 
### Issue
A form with page breaks, at least multiple page breaks, provides no "Prev" button to return to the previous page from the last page in the form. This will prevent someone from correcting information on the previous page and will potentialy lead to frustration with larger forms.

### Non-Ideal Workaround
To workaround this shortcomming, HTML elements can be added. It would be ideal if these controls could specify the page number, but the current form javascript does not support this. Furthermore, the workaround apears to have several shortfalls itself:

- Prevents default paging controls from rendering
- Submit button renders immediatly after paging controls on last page
- No apparent method for specifing page by number for use in breadcrumbs or links
- Useage of Prev and Next has to be manually decided per page
- Failure to include a `prev` and `next` on every page with controls will cause break in the js render
- Pagebreak numbers must be manually set per instance

```html
<nav class="crumbs" data-mautic-form-pagebreak="1">
    <a data-mautic-form-pagebreak-button="prev">Prev</a>
    <a data-mautic-form-pagebreak-button="next">Next</a>
</nav>
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
