### ISSUE TITLE
Segments - "Tag is empty" not working

### ISSUE THREAD

**Issue by suriite8** [mautic/mautic#7715]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
 Segments were not updated with contact that has no tag

| Q   | A
| --- | ---
| Mautic version | Tested in v 14.2 to 15.1
| PHP version | 7.1.9
| Browser | 

### Steps to reproduce
1. Create one or more contact with tag (eg: mautic)
2. Next Create a segment with *Tags* filter with *Empty* attribute.
3. Execute the segment cron manually.
4.  Segments were not updated with contact that has no tag
 
### Log errors
No errors in log file

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi, i cannot reproduce with your steps. My contacts with tags are here in my segment after segment update.
Can you try to share more information to reproduce ?

**Comment by suriite8** [comment]
@npracht  Sorry, it should segment with Tags filter with Empty attribute.

**Comment by npracht** [comment]
Bug confirmed.

**Comment by Woolgoose** [comment]
Same here:
I tried to filter all contacts without tags (there are plenty of them) but the filter tags>empty returned zero contacts.

A simple way to reproduce it is. Create one or more contacts without tags. Create a segment with the filter tags set to empty. Run the update segments cronjob. The contact count for the segment is still on 0 (zero).

**Comment by varlondon** [comment]
1. Bug confirmed re trying to segment contacts with empty tags (returns zero)
2. I can also add that trying to segment contacts with specific tag ("tag-a") return partial results (2 out of "tag-a" 40 contacts in my case)
3. in relation to point 2: under contacts, searching "is:anonymous tag:tag-a" return the same partial results (just 2)

**Comment by RCheesley** [comment]
Confirmed in 3.0.2!
