### ISSUE TITLE
[Bug] Email heading in lead history

### ISSUE THREAD

**Issue by zapur1** [mautic/mautic#772]
Hi,

In the lead history when a email sent or read item is there, the heading is the subject line of the email. Wouldn't it make more sense for it to show the Internal name as I know that is how I differentiate emails when A/B testing were they have the same subject.

<img width="297" alt="mautic" src="https://cloud.githubusercontent.com/assets/1893622/9186957/8266de62-400e-11e5-9e39-5c15ead4c713.png">

I tried to see if there was a duplicate but wasn't one that I could find.

Thanks,

**Comment by alanhartless** [comment]
Implemented in 1.2.0.
