### ISSUE TITLE
Wrong email queue handling and reporting

### ISSUE THREAD

**Issue by regevbr** [mautic/mautic#7724]
## Bug Description

The `MessageQueueRepository` completely lacks any handling of cancelled emails.

If a message has maxed out its attempts, it will be stuck in `MessageQueue::STATUS_RESCHEDULED`. This will cause reporting to state it as pending, even though it will never be sent again.
If a message is created with 0 max attempts, it will be stuck in `MessageQueue::STATUS_PENDING`, and again, will be counted towards pending emails in the statistics.

Needs to be fixed:
1. If a message is set with 0 max attempts, there is no need to queue it in the first place. Or queue it with `MessageQueue::STATUS_CANCELLED` (for statistics purposes)
2. Once a message has finished all of its attempts, it should be either removed from the repository or marked as  `MessageQueue::STATUS_CANCELLED`

In the case we decide to keep cancelled events in the repository, we need to handle all status queries as they look for all messages without `MessageQueue::STATUS_SENT` state.
Also we should add that cancelled count to the UI here:

![image](https://user-images.githubusercontent.com/5775519/61950415-6b436b80-afb6-11e9-9c58-57430dfff276.png)

**Comment by regevbr** [comment]
@escopecz @kuzmany when (and if) we decide here on the proper fix, I wouldn't mind creating the PR for it.

**Comment by RCheesley** [comment]
@regevbr did you manage to get some time to look into this?

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
