### ISSUE TITLE
Unsubscribed number 

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#7728]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.27
| Browser | Chrome

### Steps to reproduce
1. Create a report with the source emails
2. Add `Unsubscribed` and `Unsubscribed Rate`
3. The `unsubscribed` remains the same for all emails
![Screenshot from 2019-07-26 18-17-35](https://user-images.githubusercontent.com/12627658/61962290-db131f80-afd1-11e9-93f0-ee9af1006669.png)

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Closing in favour of of #8723 which has more discussion about this issue. Let's continue the thread there!
