### ISSUE TITLE
Repeat Campaign Does Not Repeat Actions

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#7729]
##  Bug Description
When I set a campaign to "Allow contacts to restart the campaign" I can get the contact to repeat the campaign without any problem, but the contact does not repeat any of the action steps inside. 

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2
| Browser | N/A

### Steps to reproduce (Version A)
1. Create a campaign and set "Allow contacts to restart the campaign" to true
2. In the builder, add one or more action steps to update fields or increment points.
2.  Make the last step change campaigns, asking Mautic to add the contact back to the same campaign, repeating the campaign
3. Publish the campaign and watch the contact's History tab to see them getting added to the campaign, but not run through any of the same action steps.

### Steps to reproduce (Version B)
1. Create a campaign targeting an empty segment and set "Allow contacts to restart the campaign" to true
2. In the builder, add one or more action steps to update fields or increment points.
2.  Make the last action in the campaign to remove the contact from the segment
3. Publish the campaign
4. Add a contact to the segment and wait for the campaign to run and remove the contact
5. Re-Add the contact to the campaign
 
### Log errors
No errors appear in the log

**Comment by dichvuhuuich** [comment]
I think may be this bug exist by add segment, after that add to this segment again but It is not added to campaign by segment:
**Steps to reproduce**
1. Set tag test for an account test
2. Make a segment Test with tag test
3. Make a campaign Test (turn on Allow contacts to restart the campaign) with source segment Test to do anything, example send an email
4. Test it works normally
5 Remove tag test for account test (account test will be removed from segment Test and campaign T. st)
6. Set tag test for the account test **AGAIN**
7. Account test ONLY added to segment Test and can not added to campaign Test

**Comment by grinono** [comment]
Having the same issues for contacts restarting a campaign.: "Allow contacts to restart the campaign" similar issue at #7704

**Comment by RCheesley** [comment]
Closing as a duplicate
