### ISSUE TITLE
Changing form field ordering displays data incorrectly on lead timeline

### ISSUE THREAD

**Issue by drmmr763** [mautic/mautic#773]
Description of Issue:
When a the form fields on a form are re-ordered after the form has been submitted, the data and the labels in the lead's timeline no longer match the data. 

Steps to reproduce:
1) create a form with 3 fields (email, phone, name)
2) submit the form with just email to create a new lead
3) re-submit the form with email, phone, and name to update the lead
4) re-order the fields in the form so they are not in the same order as when the lead was created
5) view the lead timeline, you should notice the data and labels are mis-matched. 

Example:
![image](https://cloud.githubusercontent.com/assets/643104/9200602/9a149fb0-4016-11e5-99ec-d5723904fc36.png)

Also reported at:
https://www.mautic.org/community/index.php/644-bug-form-submitted-event-display-in-wrong-label/0#p2527

**Comment by alanhartless** [comment]
Fixed in 1.2.0
