### ISSUE TITLE
Unknown column 'bounced' - error when receive SNS notification

### ISSUE THREAD

**Issue by MohHeader** [mautic/mautic#7731]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I use SES to send emails, from few days I just started to use SNS to send callbacks regarding bounced emails & complaints.
It confirmed and everything looked fine,
But later on, I noticed no bounced emails where recorded ( although I still receive emails from SES about bounces )
So I check the logs, and found that indeed there is an error ( Please check Logs below )

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Follow the steps in this guide : https://www.mautic.org/docs/en/emails/bounce_management.html
2. Send an email that should bounce from Mautic
 
### Log errors
 
```
mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT count(*) FROM (SELECT DATE(es.date_sent) AS date_sent1, DATE(es.date_read) AS date_read1, e.subject AS subject2, es.email_address AS email_address1, e.id AS e_id1, IF(dnc.id IS NOT NULL AND dnc.reason=2, 1, 0) AS bounced1 FROM mauticemail_stats es LEFT JOIN mauticemails e ON e.id = es.email_id LEFT JOIN mauticleads l ON l.id = es.lead_id LEFT JOIN mauticip_addresses i ON i.id = es.ip_id LEFT JOIN mauticemails vp ON vp.id = e.variant_parent_id LEFT JOIN mauticcategories c ON c.id = e.category_id LEFT JOIN mauticlead_donotcontact dnc ON e.id = dnc.channel_id AND dnc.channel='email' AND es.lead_id = dnc.lead_id WHERE (es.date_sent IS NULL OR (es.date_sent BETWEEN ? AND ?)) AND (e.is_published = ?) ORDER BY bounced DESC) c' with params ["2019-06-26 00:00:00", "2019-07-26 17:25:02", "1"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'bounced' in 'order clause'" at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT count(*) FROM (SELECT DATE(es.date_sent) AS date_sent1, DATE(es.date_read) AS date_read1, e.subject AS subject2, es.email_address AS email_address1, e.id AS e_id1, IF(dnc.id IS NOT NULL AND dnc.reason=2, 1, 0) AS bounced1 FROM mauticemail_stats es LEFT JOIN mauticemails e ON e.id = es.email_id LEFT JOIN mauticleads l ON l.id = es.lead_id LEFT JOIN mauticip_addresses i ON i.id = es.ip_id LEFT JOIN mauticemails vp ON vp.id = e.variant_parent_id LEFT JOIN mauticcategories c ON c.id = e.category_id LEFT JOIN mauticlead_donotcontact dnc ON e.id = dnc.channel_id AND dnc.channel='email' AND es.lead_id = dnc.lead_id WHERE (es.date_sent IS NULL OR (es.date_sent BETWEEN ? AND ?)) AND (e.is_published = ?) ORDER BY bounced DESC) c' with params [\"2019-06-26 00:00:00\", \"2019-07-26 17:25:02\", \"1\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'bounced' in 'order clause' at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'bounced' in 'order clause' at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'bounced' in 'order clause' at /var/www/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Is your schema up to date? See https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful to find out.

**Comment by MohHeader** [comment]
Thanks for your reply,

The error log disappeared just after I upgraded ( manually ) through the link you sent to the next version ( v2.15.2 )

But, I am still not getting any emails marked as bounced, not sure what the problem now unfortunately, may be it fails silently ?

**Comment by escopecz** [comment]
Have you tried to google how to configure Mautic and SES properly? There are several articles like this one:

https://medium.com/@AndreiVoica/how-to-integrate-mautic-with-amazon-ses-7fe066e9131c

**Comment by MohHeader** [comment]
Yes sure, I already followed the steps in the official Doc : 
https://www.mautic.org/docs/en/emails/bounce_management.html

But let me double check the one you sent too, and coming back to you 
Thanks

**Comment by MohHeader** [comment]
BTW : I am already sending all my emails through SES,
my issue is about receiving bounce reports from SNS and marking those emails as bounced, so not to send them any more emails again

**Comment by MohHeader** [comment]
And I think SNS is configured right, as I did followed the steps in the official Doc + I did received those log errors described before ( so SNS did sent notifications to Mautic )

**Comment by MohHeader** [comment]
Also, as I stopped receiving the InvalidFieldNameException,
May be I am now just facing this issue :
https://github.com/mautic/mautic/issues/4632

**Comment by escopecz** [comment]
Looks like it. Let's close this one and move the focus to #4632
