### ISSUE TITLE
Following installation instructions on github, site will not install correctly.

### ISSUE THREAD

**Issue by thematrixduck** [mautic/mautic#7734]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Maybe, newbie trying first installation.
| Feature request? | 
| Enhancement? | 

## Description:
After following installation instructions on github and insuring composer was installed and available, when I go to http://....../mautic/index.php, I am redirected to http://...../mautic/ and a blank page is displayed.
My server does not have a gui, so I am accessing it remotely via firefox.

When I check the databases, I cannot see one for mautic. 
I don't think a mautic log file is being created I can't find one in /var/logs

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2.7
| MySql version | 5.7.27

### Steps to reproduce:
1. clone site to /home/"user"/www/mautic
2. run firefox and open site samrp.com/mautic/index.php
3. redirects to samrp.com/mautic and displays a blank page.  View page source does not show any html code at all.

### Log errors: 
mautic log not found in mautic/app/log (mautic/app/log directory does not exist).

**Comment by maltonite** [comment]
What web server are you using?

I have had to add the following to the Nginx config file to get parts of Mautic working in the past:

`rewrite ^/index.php/(.*) /$1 permanent;`

**Comment by thematrixduck** [comment]
Hi maltonite,
I'm using apache/centos linux.  The rewrite module is enabled.

**Comment by maltonite** [comment]
I am using Chrome; Your site is returning a 500 error. 

Can you rename the mautic index.php to say indexmautic.php, and put a basic index.php file with:

```
<? php
phpinfo()
```

Is your DB definitely working?

Is there anything in: app/config/local.php

**Comment by thematrixduck** [comment]
I renamed as you suggested and using chrome, I still get a 500 error.

**Comment by maltonite** [comment]
That suggests you have a PHP or Apache issue to me. 

Maybe try checking the Apache or PHP logs? I have had an issue where a .sock file for PHP gets removed from the system.

**Comment by thematrixduck** [comment]
apache and php are fine.  There are two wordpress sites already running. 
I'm going to install 2.15.2 and see if there is a difference.

**Comment by npracht** [comment]
@thematrixduck any feedback ?

**Comment by Lalilu** [comment]
@thematrixduck, can you provide an update of your case?

I have maybe the same problem with my instances. Update from 2.5.1 (or older) to 2.5.2 (or newer) leads to Error 500 immediately. Installations also don't work.

Can someone comment what has change in terms of system requirements from 2.5.1 to 2.5.2.?

**Comment by Lalilu** [comment]
Ah, at least for my case I found the relevant change to 2.5.2: 

### .htaccess's following lines break my setup:

```
# Denie access via HTTP requests to all PHP files.
<Files "*.php">
    Require all denied
</Files>

# Except those whitelisted bellow.
<Files "index.php">
    Require all granted
</Files>
<Files "index_dev.php">
    Require all granted
</Files>
<Files "filemanager.php">
    Require all granted
</Files>
<Files "upgrade.php">
    Require all granted
</Files>
```

Deleting this from .htaccess allowed me to use Mautic 2.5.2+.

@thematrixduck, no idea if this helps you.

**Comment by Lalilu** [comment]
One last message for now: Does someone have an idea why this is an issue? Too old Apache? Old PHP? …

**Comment by npracht** [comment]
Hi guys, i'll suggest you to join forum or chat for that as far as it is an installation issue, not a software issue. Thanks.
