### ISSUE TITLE
Empty option for filter not working in report

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#7737]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
when you set a filter in a report and select empty as value for this filter, the report will stay empty because the filter is not working.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1. Create a contact without an email address
2. Create a new report with contact as data source
3. put email and Last name in column
4. Add a filter on email with empty as value
5. Validate your report
6. See that your contact is not in the report. The report stay empty.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/7746

**Comment by florentpetitjean** [comment]
Tested and working.

@Enc3phale patch de Bienprevoir si possible, merci.

**Comment by dennisameling** [comment]
#7746 is now merged for the 2.16 release, so I'm closing this issue. :)
