### ISSUE TITLE
mautic:broadcasts:send cron job (segment email broadcasting) does not work

### ISSUE THREAD

**Issue by AsianAmericanManAD1979** [mautic/mautic#7738]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
mautic:broadcasts:send cron job (segment email broadcasting) does not send any active segment email(s).

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.28
| Browser | Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)

### Steps to reproduce
1.  In an AWS Lightsail instance with LAMP (PHP 7) blueprint by Bitnami, install Mautic according to the instruction given at https://docs.bitnami.com/aws/infrastructure/lamp/get-started/add-applications-amp/.
2.  Create a Mautic segment.
3.  Create a Mautic contact.
4.  Add the Mautic contact to the Mautic segment.
5.  Create a segment email, with the Mautic segment.
6.  Execute the following command in SSH client (Git Bash).

`sudo su daemon -s /bin/sh -c "/opt/bitnami/php/bin/php /opt/bitnami/apps/mautic/htdocs/app/console mautic:broadcasts:send --limit=50 --batch=1"`

The email shows '1 pending', as it should.  But it doesn't send the email when the above command is executed.

Clicking the 'Send Example' button on the email summary/overview webpage works.

Clicking the 'Send' button on the email summary/overview webpage works.

There have been a lot of Mautic Github issues on this exact same problem, in the previous versions of Mautic.

How can I fix this problem in my version of Mautic?

 
### Log errors
No errors produced.

The above command produces the following output.

+---------+--------+----------+
| Channel | # sent | # failed |
+---------+--------+----------+

Nothing sent, nothing failed.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by coding-machine0001** [comment]
After rummaging through the Mautic source code just a little bit, in an attempt to better position myself at solving this mautic:broadcasts:send cron job failure in Mautic v2.15.1, I've discovered the following.


_/opt/bitnami/apps/mautic/htdocs/app/console_ is the PHP program that executes the Mautic cron jobs.

_/opt/bitnami/apps/mautic/htdocs/app/AppKernel.php_ is used as the Symphony application kernel in the Mautic console program.

Executing the following command shows which file contains the code for handling mautic:broadcasts:send.

`grep -rl "mautic:broadcasts:send" /opt/bitnami/apps/mautic/htdocs`

The above command produces the following output.

```
/opt/bitnami/apps/mautic/htdocs/app/bundles/ChannelBundle/Command/SendChannelBroadcastCommand.php
/opt/bitnami/apps/mautic/htdocs/app/logs/mautic_prod-2019-07-30.php
```

So, apparently, _/opt/bitnami/apps/mautic/htdocs/app/bundles/ChannelBundle/Command/SendChannelBroadcastCommand.php_ contains the code for handling mautic:broadcasts:send cron job.

_/opt/bitnami/apps/mautic/htdocs/app/logs/mautic_prod-2019-07-30.php_ does not contain any error related to mautic:broadcasts:send.


Looking at the contents of _/opt/bitnami/apps/mautic/htdocs/app/bundles/ChannelBundle/Command/SendChannelBroadcastCommand.php_, I get the impression that the code for broadcasting segment emails is fairly complex, something that you cannot easily fix unless you know the intimate details of all the related Mautic code.

**It's unfortunate that while the major reason for using Mautic is fully-automated mass email sending, mautic:broadcasts:send cron job keeps breaking throughout multiple Mautic versions:  It completely defeats the major purpose of using Mautic.**

**Comment by escopecz** [comment]
There is known issue with email sending command in 2.15.2. But it worked on earlier versions. Any errors in the log? What email transport do you use? Switching to another transport did not work?

**Comment by npracht** [comment]
@coding-machine0001 any update ?

**Comment by coding-machine0001** [comment]
@escopecz Read the bug description:  it says "No errors produced" in the Log errors section.  I used Amazon SES for emailing.  I have not, and will not try any other emailing service, since Amazon SES is what I use.  Considering all the other emailing features work in my installation of Mautic (campaign emails, manual email sending, example email sending, and direct email sending to contact from contact view), it's safe to conclude that it's not the email service problem.

**Comment by shanse2** [comment]
I also am running into this problem with Mautic version 2.15.3. Segment emails will stay "pending" even after the "Publish Up" date has passed. The cron job is set to run every 15 minutes.

I'm seeing this error in my log: 

`mautic.NOTICE: Symfony\Component\Console\Exception\RuntimeException: Too many arguments, expected arguments "command". (uncaught exception) at /var/www/html/mautic/vendor/symfony/console/Input/ArgvInput.php line 182 while running console command `mautic:broadcasts:send` [] []`

**Comment by RCheesley** [comment]
Closing this issue due to it relating to 2.x and having no recent interactions.

**Comment by luiszxcv** [comment]
I have the exact same problem.

**Comment by luiszxcv** [comment]
Any suggestions for correction?
