### ISSUE TITLE
mautic:maintenance:cleanup cron job does not work

### ISSUE THREAD

**Issue by coding-machine0001** [mautic/mautic#7739]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
mautic:maintenance:cleanup cron job fails to execute.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.28
| Browser | Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)

### Steps to reproduce
1.  In an AWS Lightsail instance with LAMP (PHP 7) blueprint by Bitnami, install Mautic according to the instruction given at https://docs.bitnami.com/aws/infrastructure/lamp/get-started/add-applications-amp/.
2.  Create a Mautic segment.
3.  Create a Mautic contact.
4.  Add the Mautic contact to the Mautic segment.
5.  Execute the following command in SSH client (Git Bash).

`sudo su daemon -s /bin/sh -c "/opt/bitnami/php/bin/php /opt/bitnami/apps/mautic/htdocs/app/console mautic:maintenance:cleanup --days-old=60 --gdpr -n"`

Is there a way to fix this problem in my installation of Mautic?

 
### Log errors
bitnami@ip-xxx-xxx-xxx-xxx:/opt/bitnami/apps/mautic/htdocs/app$ sudo su daemon -s /bin/sh -c "/opt/bitnami/php/bin/php /opt/bitnami/apps/mautic/htdocs/app/console mautic:maintenance:cleanup --days-old=60 --gdpr -n"

  [Doctrine\DBAL\DBALException]
  An exception occurred while executing 'SELECT id FROM leads l WHERE (l.last
  _active <= :date) OR ((l.date_added <= :date2) AND (l.last_active IS NULL))
   LIMIT 10000 OFFSET 0' with params ["2016-07-30 14:36:45"]:

  Value for :date2 not found in params array. Params array key should be "dat
  e2"

  [Doctrine\DBAL\SQLParserUtilsException]
  Value for :date2 not found in params array. Params array key should be "dat
  e2"

mautic:maintenance:cleanup [-d|--days-old [DAYS-OLD]] [-r|--dry-run] [-g|--gdpr] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Inboundmanager** [comment]
Hi
That kind of error happens when we use the mysqli driver because it doesn´t allow parameters starting by ':'.
Try again with pdo_mysql.

**Comment by RCheesley** [comment]
Closing this issue as resolution suggested above. Please follow up with the Bitnami support team at https://community.bitnami.com/c/mautic if you have further issues.
