### ISSUE TITLE
"Campaign > Contact tags > Condition based on a contact tags" not working

### ISSUE THREAD

**Issue by Marketpedia** [mautic/mautic#7740]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this: | Bug report? | 

| Q  | A
| ---| ---
| Bug report? | Tag added in the campaign not working
| Feature request? | 
| Enhancement? | 

## Description:
"Campaign > Contact tags > Condition based on a contact tags" not working.  In other words, I added a tag in a campaign flow to be added immediately to a contact, but the tag is not getting added to the contact

## If a bug:

| Q   | A
| --- | ---
| Mautic version |  v2.15.1
| PHP version |  7.0.33

### Steps to reproduce:
1.   Create a Campaign
2.   Add an Condition > Contact's Tag
3.  Run a campaign and you will see the tag has not get added to contact
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by dichvuhuuich** [comment]
Hi, Condition is condition with contact has tags and if has the tags in condition will has next steps (blue)... and if has not the tags in condition will has next steps (red)

**Comment by escopecz** [comment]
Yea, conditions do not add anything. They check if the condition you configure is true or false. Use actions to add tags.
