### ISSUE TITLE
Form field value in campaing builder condition doesn't have regexp operator

### ISSUE THREAD

**Issue by lopesrichard** [mautic/mautic#7745]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I can't fint regexp operator when adding a **form field** condition inside campaigns.
When selecting **contact field**, it appears.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.0
| Browser | chrome 75.0.3770.142

### Steps to reproduce
1. Go to campaigns
2. Click in new
3. Open Builder
4. Select Campaing Form
5. Choose one form
6. Click in add
7. Add a condition form field value
8. Select a form
9. Select a field
10. Try to find regexp operator

![image](https://user-images.githubusercontent.com/42302993/62212965-4c5b2580-b378-11e9-8027-0efba949069e.png)
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/ideas as Github is for reporting bugs with Mautic whereas the ideas forum is where we discuss ideas for features and improvements :)
