### ISSUE TITLE
Mautic only sending mail to verified email in Amazon SES

### ISSUE THREAD

**Issue by Mautician** [mautic/mautic#7748]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Trying to send my campaign mails
Tried a test. None of the emails are sending my first mail in the campaign (probably the emails after this one in the campaign either). I am using amazon ses. Thing is, the only test email that got the first mail in the campaign is one that is 'verified' in amazon ses. I am out of the sandbox mode already. Amazon ses says that it sent emails but I don't have any in my inbox.

I have no clue what to do now.

| Q   | A
| --- | ---
| Mautic version | Latest version
| PHP version | 7.2
| Browser | Chrome

### Steps to reproduce
1. Start a campaign
2. Send mail
 
### Log errors
???

[//]: # ( Invisible comment:
Theres 0 logs from today

**Comment by AndrassGray** [comment]
Shouldn't the subject read "amazon ses only sending to verified email" ? I guess Mautic is sending, in the sense of handing over, the email. Now it's up to Amazon to handle the next step.

**Comment by virgilwashere** [comment]
Is the MAILER_FROM_ADDRESS on Email configuration page (or campaign FROM address) verified in Amazon SES ?

Because SES doesn't care about verification of recipients unless they bounce (or complain)

**Comment by npracht** [comment]
@Mautician any feedback please ?

**Comment by npracht** [comment]
Without extra information and being an old issue, let close this issue.
