### ISSUE TITLE
Contact Details Overwritten

### ISSUE THREAD

**Issue by handypreneur** [mautic/mautic#7749]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.0.33
| Browser | Chrome / Safari

**When running through several 'what ifs' I discovered an issue with contact details being overwritten.**

1. I created a submission form using the normal fields: Text (First Name), Text (Last Name), Email
2. Original form submission worked as expected.
3. After updating the form by dropping the Text (Last Name) field and adding a Captcha, I resubmitted the form using the same email address as the original. The form was submitted without any sort of validation error.
4. I checked the contact details and the Text (First Name) field was updated with the second submission's name, overwriting the first.  

I'm not certain if there are any validation steps but this seems as this should not be occurring.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Is the issue that the first name was updated (seems correct to me) or that the validation did not work? What method do you use to embed a form? How is the Captcha field configured?

**Comment by handypreneur** [comment]
I believe I was using the form incorrectly. My apologies. I have several systems being built and I believe this to be my own mistake. Thanks for the response.
