### ISSUE TITLE
Link tracking not updating metrics

### ISSUE THREAD

**Issue by MattBred** [mautic/mautic#7756]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
The URLs in emails are correctly replaced with a mautic.mydomain.com/r/abc123

Clicking on the URL also properly redirects me to the final destination URL.

However, the metrics for click counts do not go up for the email. If I add UTM tags, I do not see them under my contact that opened up the email, either.

I've followed all the steps in https://www.mautic.org/docs/en/emails/troubleshooting.html#email-link-clicks-are-not-getting-tracked to no avail.

**Note: The "Email Read" tracking DOES work, just not link tracking**

**Extra Note: This is using Docker**

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.15.2 (also 2.15.0)
| PHP version | 7.1.26
| Docker? | Yes |

### Steps to reproduce:
1. Create a segment email
2. Add a link to the email
3. Send the email
4. Open the email up (personal email, not attached to anything Mautic, using brower that has never logged into Mautic)
5. Click the link
6. Redirect to the final destination URL
7. In admin dashboard, view the email
8. Click count has not gone up for the URL
 
### Log errors: 
I did see the log for the GET request on the trackable link:
```
mautic_1    | 172.18.0.1 - - [01/Aug/2019:23:47:29 +0000] "GET /r/92e770d1b72fa6ddf729b5f71?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6MTE7fXM6NToiZW1haWwiO2k6MTE7czo0OiJzdGF0IjtzOjIyOiI1ZDQzN2EwYTAzMzY2MTUxMjc0MjMyIjtzOjQ6ImxlYWQiO3M6MjoiNDciO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYWlsIjtpOjExO319& HTTP/1.0" 302 670 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
```

**Comment by escopecz** [comment]
1. Upgrade to latest Mautic 2.15.2. 2.5.0 is quite old version and hundreds of bugs had been fixed in the mean time.
2. Do you test email tracking in an incognito browser or if you log out off of Mautic?

**Comment by MattBred** [comment]
I see that 2.15.2 was just released, and the docker image was updated. I'll try updating and report back.

**Comment by MattBred** [comment]
Confirmed still broken with 2.15.2

**Comment by MattBred** [comment]
Oh and sorry, I meant to write 2.15.0 - I was not on 2.5.0

**Comment by MattBred** [comment]
@escopecz I have seemed to fix the issue. It was an nginx configuration problem.

I debugged my nginx reverse proxy and updated the config to match https://github.com/mautic/docker-mautic/blob/master/examples/mautic-example-nginx-ssl/nginx.conf

After doing so, click tracking started working. I am not sure what part of the nginx config fixed the issue, but it was pretty rough going to debug it. Could there possibly be more logging around the click tracking?

**Comment by escopecz** [comment]
Thanks for describing what helped you to get it working, Matt!

There is debugging if you add `'debug' => true,` to the array in app/config/local.php file.

I'll close this issue as it seemed to be a server configuration that needed to change.

**Comment by autoize** [comment]
Mautic version: 2.15.3
PHP version: 7.2.24-0ubuntu0.18.04.1
Apache Version: Apache/2.4.29 (Ubuntu)
HAProxy version 1.8.8-1ubuntu0.9 2019/12/02

We seem to be experiencing the same issue, but instead of Nginx as a reverse proxy, we are using HAProxy. @MattBred when you resolved your issue with Nginx, were you able to figure out which header(s) need to be forwarded for link clicks to be counted?

The links are being rewritten properly, it is just that the click counts are not incrementing. To troubleshoot, we tried seemingly everything, including clearing the cache, running a doctrine migrate and schema update, tweaking the Mautic site URL, and disabling IPV6. Any thoughts @escopecz ?

Excerpt from HAProxy log:

```
OjQ6ImxlYWQiO3M6NToiMjE2ODYiO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYWlsIjtpOjU5O319 HTTP/1.1"
Dec 10 19:53:51 haproxy haproxy[25766]: 127.0.0.1:53678 [10/Dec/2019:19:53:51.692] www-https~ apache_pool/web1 0/0/0/33/33 302 561 - - ---- 10/10/0/0/0 0/0 "GET /r/87bda1d9ffa8e3605dc00edf1?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6NTk7fXM6NToiZW1haWwiO2k6NTk7czo0OiJzdGF0IjtzOjIyOiI1ZGVmOGUyNzkxNTRmMTM2MjE5NDkzIjtzOjQ6ImxlYWQiO3M6NToiMjE2ODYiO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYWlsIjtpOjU5O319& HTTP/1.1"
```

Excerpt from Mautic log (in debug mode):

`[2019-12-10 19:53:51] mautic.DEBUG: Attempting to load redirect with tracking_id of: 87bda1d9ffa8e3605dc00edf1`

Excerpt from my Apache log (for a different link click):

`fd42:61ba:ce21:2118:216:3eff:fe3c:e50e - - [10/Dec/2019:20:19:36 +0000] "GET /r/5679ca99d51924472275fe96b?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czo1OiJlbWFpbCI7aToxO2k6NTk7fXM6NToiZW1haWwiO2k6NTk7czo0OiJzdGF0IjtzOjIyOiI1ZGVmOGUyNzkxNTRmMTM2MjE5NDkzIjtzOjQ6ImxlYWQiO3M6NToiMjE2ODYiO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYWlsIjtpOjU5O319& HTTP/1.1" 302 566 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"`

Here's the HAProxy configuration:

```
global
log /dev/log local0
log /dev/log local1 notice
chroot /var/lib/haproxy
stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
stats timeout 30s
user haproxy
group haproxy
daemon

# Default SSL material locations
ca-base /etc/ssl/certs
crt-base /etc/ssl/private

# Default ciphers to use on SSL-enabled listening sockets.
# For more information, see ciphers(1SSL). This list is from:
#  https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
# An alternative list with additional directives can be obtained from
#  https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=haproxy
        ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
        ssl-default-bind-ciphers EECDH+AESGCM:EDH+AESGCM
        tune.ssl.default-dh-param 2048

defaults
log global
mode http
option httplog
option dontlognull
        option  forwardfor
        option  http-server-close
        timeout connect 5000
        timeout client  50000
        timeout server  50000
errorfile 400 /etc/haproxy/errors/400.http
errorfile 403 /etc/haproxy/errors/403.http
errorfile 408 /etc/haproxy/errors/408.http
errorfile 500 /etc/haproxy/errors/500.http
errorfile 502 /etc/haproxy/errors/502.http
errorfile 503 /etc/haproxy/errors/503.http
errorfile 504 /etc/haproxy/errors/504.http

frontend www-http
bind *:80
reqadd X-Forwarded-Proto:\ http
default_backend apache_pool

frontend www-https
bind *:443 ssl crt /etc/letsencrypt/live/go.example.org/go.example.org.pem
reqadd X-Forwarded-Proto:\ https
rspadd Strict-Transport-Security:\ max-age=31536000;\ includeSubDomains;\ preload
default_backend apache_pool

backend apache_pool
balance leastconn
redirect scheme https if !{ ssl_fc }
http-request set-header X-Client-IP %[src]
server web1 web1.lxd:80 check
server web2 web2.lxd:80 check
```

**Comment by MattBred** [comment]
@autoize I'm unsure which configuration it was that solved it for me. Looking at my diffs, adding the following fixed it:

```diff
+    proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
+    proxy_set_header        X-Forwarded-Proto  $scheme;
+
+    # drop unused proxy headers to prevent clients from tampering with them
+    proxy_set_header        X-Forwarded-Port   "";
+    proxy_set_header        Forwarded   "";
+    proxy_set_header        X-Real-IP   "";
+    proxy_set_header        X-Forwarded-Host "";
+
+    # sometimes apache mod_rewrite redirects to absolute http:// urls. Replace those with https:// urls
+    proxy_redirect http:// https://;
```
Make sure you're using an incognito window when you test the tracking, as Mautic won't increase the counters if it knows you're an admin.

Also, try the debugging that @escopecz mentioned right above your message.

**Comment by autoize** [comment]
Everything is being tested in Incognito mode with multiple browsers.
I already tried the debugging mode - it didn't reveal much more than
```
[2019-12-11 01:16:38] mautic.DEBUG: Attempting to load redirect with tracking_id of: acd511a95fcad9fe59ad06a73  
[2019-12-11 01:16:38] mautic.DEBUG: Executing Redirect: Mautic\PageBundle\Entity\Redirect with ID #110  
```

In haproxy.cfg, tried adding a few more directives to the **frontend www-https**

```
      option forwardfor
      reqadd X-Forwarded-Proto:\ https
```

and **backend apache_pool**

```
        option forwardfor
        redirect scheme https if !{ ssl_fc }
        http-request set-header X-Client-IP %[src]
        http-request set-header Host go.gooddollar.org
        http-request del-header X-Forwarded-Port
        http-request del-header Forwarded
        http-request del-header X-Real-IP
        http-request del-header X-Forwarded-Host
```

Also updated Apache virtualhosts to listen explicitly on the internal hostnames
`<VirtualHost web1.lxd:80>` instead of `<VirtualHost *:80>`

Still no change in the situation with link tracking.

**Comment by autoize** [comment]
Unfortunately even switching it to the identical Nginx file as @MattBred did not resolve the issue.

```
upstream mautic {
        least_conn;
        server web1.lxd;
        server web2.lxd;
}

server {
	listen 443 ssl;
        ssl_certificate     /etc/letsencrypt/live/go.example.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/go.example.org/privkey.pem;
	location / {
        proxy_set_header        Host               $host;
        proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto  $scheme;

        # drop unused proxy headers to prevent clients from tampering with them
        proxy_set_header        X-Forwarded-Port   "";
        proxy_set_header        Forwarded   "";
        proxy_set_header        X-Real-IP   "";
        proxy_set_header        X-Forwarded-Host "";
		
        proxy_pass http://mautic/;

        # sometimes apache mod_rewrite redirects to absolute http:// urls. Replace those with https:// urls
        proxy_redirect http:// https://;
	}
}
```

**Comment by MattBred** [comment]
What type of email are you sending? A lot of the test emails won't work correctly.

I was testing it by going to `/s/emails/new`, selecting Segment email, filling it out, and then clicking "Send" (**not Send Example**)

**Comment by autoize** [comment]
Both segment and campaign (template) emails have been tried.
These are real, live test emails with their own segment, _not_ sent through **Send Example**.

**Comment by Talbatz** [comment]
Hi there, we are experiencing the same issue with a similar setup.

**Comment by gucio1200** [comment]
Turn on proxy-protocol on both sides or put  "'track_private_ip_ranges' => true" to local.php
mautic has to have correct X-Real-IP from client, otherwise it wont track... 8h of debugging..

**Comment by danielberndt** [comment]
can confirm that adding these two lines to my `nginx.conf` fixed my issue:

```diff
location / {
    proxy_set_header  X-Real-IP  $remote_addr;
+   proxy_set_header  X-Forwarded-For $remote_addr;
+   proxy_set_header  X-Forwarded-Port $server_port;
    proxy_set_header  Host       $http_host;
    proxy_pass        http://127.0.0.1:8090;
  }
```

**Comment by RCheesley** [comment]
Closing as a server config issue with a solution - thanks for sharing @danielberndt !
