### ISSUE TITLE
Special Characters are escaped when sending webhooks

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#7761]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version |  2.15.1
| PHP version | 7.2
| Browser | 

### Steps to reproduce
1. Go to campaigns 
2. Send a webhook
3. Send a param like ```email+1@gmail.com```
4. The webhook will send the value like this ```email 1@gmail'``
5. Maybe there is a need to encode values sent via webhook
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kfrankie** [comment]
that happens only for `+` sign  
please check #7616 for solution
Duplicate of #6197

**Comment by mabumusa1** [comment]
Thanks @kfrankie. I will close this issue

**Comment by kfrankie** [comment]
@mabumusa1 please test solution and if it works 
write a note in #7616 / #6197
