### ISSUE TITLE
Link clicks on unpublished assets recorded as asset download

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#7764]
## Bug Description
If people click to download an asset, which is actually unpublished, it still is recorded as "asset downloaded" in reporting and in the contact history.

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.2
| Browser | any

### Steps to reproduce
1. set asset to unpublished
2. click public link
3. you receive a correct error, that the asset is not available for download
4. look into asset statistics, asset download reporting and in the contacts history - its all recorded as a (successful) download

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by dsp76** [comment]
Yes, this is still the case. An unpublished asset is still counted as downloaded (even though correct 403 error). Also recorded in users timeline as downloaded.

**Comment by RCheesley** [comment]
@dsp76 thanks for checking that, have added the appropriate tags :)
