### ISSUE TITLE
List of IPs to not track in configuration does not work

### ISSUE THREAD

**Issue by bulgin** [mautic/mautic#7765]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.15.2 
| PHP version | PHP Version 7.0.33
| Browser | Firefox & Chrome

### Steps to reproduce
1. place do not track ip address in configuration of mautic
2. access the page with mautic tracking script from do not track ip
3. view report.
4. see do not track ip address listed

![donottrack](https://user-images.githubusercontent.com/16614115/62487100-f7137f80-b78e-11e9-840a-a8f2508de76b.png)
![donottrack2](https://user-images.githubusercontent.com/16614115/62487101-f7137f80-b78e-11e9-8030-32ac8d8d9b4f.png)

### Log errors
[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Do you by any chance know if this worked on older versions?

**Comment by escopecz** [comment]
Does those page hits create a new contact or not?

**Comment by bulgin** [comment]
Hello and thank you.  It worked well intermittently in previous versions (excluded ip's did not show up in reports).  It worked very well in v2.15.1.

No contacts are created for the reported ip addresses.

**Comment by Enc3phale** [comment]
You can test this: https://github.com/mautic/mautic/pull/7805

**Comment by Woeler** [comment]
Merged

**Comment by bulgin** [comment]
Not an expert on git - what does merge mean?  Should I do a pull request and re-install?
