### ISSUE TITLE
Contact page returns 500 after merge

### ISSUE THREAD

**Issue by wittwerch** [mautic/mautic#7766]
## Bug Description
After merging two identical contacts in Mautic, the detail view of the merged contact returns a HTTP 500.

![Screenshot 2019-08-06 at 09 18 56](https://user-images.githubusercontent.com/1575445/62519265-853d4380-b82b-11e9-94da-82f4f2915c90.png)

| Q   | A
| --- | ---
| Mautic version | 2.12.2
| PHP version | 7.1.30
| Browser | Chrome

### Steps to reproduce
1. Create contact 1
2. Create contact 2
3. Go to contact 1 and merge Contact 2 into it
4. Contact 2 gets deleted and a record in `contact_merge_records`
5. Go to /s/contacts/view/2 => HTTP 500 is returned

### Log errors

The `LeadController` checks for merged records, but somehow that lead that gets loaded is not "complete". The call to `$lead->getFields();` returns an empty array and that's why that error message pops up.

**Comment by escopecz** [comment]
Could you upgrade to the lates Mautic version? There is a chance that it was fixed since then.

**Comment by npracht** [comment]
@wittwerch any feedback ? Thanks.

**Comment by wittwerch** [comment]
Indeed, it's fixed in the latest version :)
