### ISSUE TITLE
Mautic 2.15.2 is not redirecting after login to dashboard 

### ISSUE THREAD

**Issue by mjml1982** [mautic/mautic#7768]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Mautic 2.15.2 is not redirecting after login to dashboard when i enable `AllowOverride All` in Apache configuration file, when i set it to none it works, i dont see any logs in apache and Mautic log files, any help would be appreciated.

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7
| Browser | 

I have also deleted the following lines from .htaccess file, but its still not working.
```
Denie access via HTTP requests to all PHP files.
<Files "*.php">
    Require all denied
</Files>
Except those whitelisted bellow.
<Files "index.php">
    Require all granted
</Files>
<Files "index_dev.php">
    Require all granted
</Files>
<Files "filemanager.php">
    Require all granted
</Files>
<Files "upgrade.php">
    Require all granted
</Files>
```
 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by cpot** [comment]
On our side we cannot even login after this 2.15.2. Nothing in the logs. Cache cleared no improvement

**Comment by FilippoIOVINE** [comment]
Same here.
Stuck on the login page after got a "GET /s/login_check HTTP/1.1" 302.

**Comment by escopecz** [comment]
I'm not able to replicate this on Mautic 2.15.2. I guess there is some server configuration difference. I'll need your cooperation to discover what it is. From viewing the [code related to `login_check`](https://github.com/mautic/mautic/search?q=login_check&unscoped_q=login_check) I have these questions:

1. Do you have `mod_rewrite` and `.htaccess` enabled? In other words, do you see `/index.php/` in your Mautic URL?
2. Do you use some other method to login like SSO, Saml, Oauth1/2 to log in somehow?
3. Please try to clear your Mautic cache by executing `rm -rf app/cache/*` (with the star at the end) from the Mautic directory. Did that help?

**Comment by jlemangarin** [comment]
1. Yes it's enabled. Here is the .htaccess : 
```
# Use the front controller as index file. It serves as a fallback solution when
# every other rewrite/redirect fails (e.g. in an aliased environment without
# mod_rewrite). Additionally, this reduces the matching process for the
# start page (path "/") because otherwise Apache will apply the rewriting rules
# to each configured DirectoryIndex file (e.g. index.php, index.html, index.pl).
#DirectoryIndex index.php

<IfModule mod_rewrite.c>
    RewriteEngine On

    # Set Authorization header for OAuth1a for when php is running under fcgi
    RewriteCond %{HTTP:Authorization} .+
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Determine the RewriteBase automatically and set it as environment variable.
    # If you are using Apache aliases to do mass virtual hosting or installed the
    # project in a subdirectory, the base path will be prepended to allow proper
    # resolution of the app.php file and to redirect to the correct URI. It will
    # work in environments without path prefix as well, providing a safe, one-size
    # fits all solution. But as you do not need it in this case, you can comment
    # the following 2 lines to eliminate the overhead.
    RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]

    # Redirect to URI without front controller to prevent duplicate content
    # (with and without `/app.php`). Only do this redirect on the initial
    # rewrite by Apache and not on subsequent cycles. Otherwise we would get an
    # endless redirect loop (request -> rewrite to front controller ->
    # redirect -> request -> ...).
    # So in case you get a "too many redirects" error or you always get redirected
    # to the start page because your Apache does not expose the REDIRECT_STATUS
    # environment variable, you have 2 choices:
    # - disable this feature by commenting the following 2 lines or
    # - use Apache >= 2.3.9 and replace all L flags by END flags and remove the
    #   following RewriteCond (best solution)
    RewriteCond %{ENV:REDIRECT_STATUS} ^$
    RewriteRule ^index\.php(/(.*)|$) %{ENV:BASE}/$2 [R=301,L]

    # If the requested filename exists, simply serve it.
    # We only want to let Apache serve files and not directories.
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule .? - [L]

    # Rewrite all other queries to the front controller.
    RewriteRule .? %{ENV:BASE}/index.php [L]
</IfModule>

<IfModule !mod_rewrite.c>
    <IfModule mod_alias.c>
        # When mod_rewrite is not available, we instruct a temporary redirect of
        # the start page to the front controller explicitly so that the website
        # and the generated links can still be used.
        RedirectMatch 302 ^(?!/(index\.php|index_dev\.php|app|addons|plugins|media|upgrade))(/(.*))$ /index.php$2
        # RedirectTemp cannot be used instead
    </IfModule>
</IfModule>

<IfModule mod_php5.c>
    # @link https://github.com/mautic/mautic/issues/1504
    php_value always_populate_raw_post_data -1
</IfModule>

<IfModule mod_deflate.c>
    <IfModule mod_filter.c>
        AddOutputFilterByType DEFLATE application/javascript
        AddOutputFilterByType DEFLATE application/rss+xml
        AddOutputFilterByType DEFLATE application/vnd.ms-fontobject
        AddOutputFilterByType DEFLATE application/x-font
        AddOutputFilterByType DEFLATE application/x-font-opentype
        AddOutputFilterByType DEFLATE application/x-font-otf
        AddOutputFilterByType DEFLATE application/x-font-truetype
        AddOutputFilterByType DEFLATE application/x-font-ttf
        AddOutputFilterByType DEFLATE application/x-javascript
        AddOutputFilterByType DEFLATE font/opentype
        AddOutputFilterByType DEFLATE font/otf
        AddOutputFilterByType DEFLATE font/ttf
        AddOutputFilterByType DEFLATE image/svg+xml
        AddOutputFilterByType DEFLATE image/x-icon
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE text/javascript
        # Do not enable compression for file types that could contain secrets
        #AddOutputFilterByType DEFLATE text/html
        #AddOutputFilterByType DEFLATE text/plain
        #AddOutputFilterByType DEFLATE text/xml
        #AddOutputFilterByType DEFLATE application/xhtml+xml
        #AddOutputFilterByType DEFLATE application/xml
        #AddOutputFilterByType DEFLATE application/json
        <IfModule mod_setenvif.c>
            <IfModule mod_header.c>
                # Remove browser bugs (only needed for really old browsers)
                BrowserMatch ^Mozilla/4 gzip-only-text/html
                BrowserMatch ^Mozilla/4\.0[678] no-gzip
                BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
                Header append Vary User-Agent
            </IfModule>
        </IfModule>
    </IfModule>
</IfModule>
```
2. No, just login/password auth
3. I tried to debug this issue for many hours and cleared all cache multiple times

**Comment by mjml1982** [comment]
1 ) Yes, those are enabled, when i disable `mod_rewrite` i see the index.php page in the url,but when i enable it shows `https://mautic.domain.com/s` .

2 ) No, i am not using any Single singed on and have't tried it.

3) I have cleared the cache nothings changed.

I have same configuration with mod_rewrite and .htaccess on same server specs with mautic 2.15.1 and its working perfectly fine.

Thanks.

**Comment by hernandez949** [comment]
are you using HTTP or HTTPS?

**Comment by jlemangarin** [comment]
HTTPS here

**Comment by zlobec** [comment]
After update to 2.15.2 i could not change the URL of Mautic installation not to include the "index.php" in the configuration in the Backend. After manually changing the url in the app/config/local.php, the problem (GET 301 redirect) disappeared.

**Comment by escopecz** [comment]
@mjml1982 could you check what your URL in the local.php file is?

**Comment by mjml1982** [comment]
@escopecz here is the url in my mautic instance `https://email.mywebsite.com/index.php`

**Comment by escopecz** [comment]
So it seems it's the same problem @zlobec described. Loose the `/index.php` part, save the file and clear the cache.

My guess how it happened is that you've installed Mautic with .htaccess or mod_rewrite disabled on your server. So it appended the index.php part to the URL. Then you've enabled it. Is that right?

I don't know how it can be related to 2.15.2 version though. I would think it was always like this. Do you have any ideas?

**Comment by mjml1982** [comment]
Yes, i have installed Mautic with .htaccess and when i enabled mod_rewrite it does not redirect me to dashboard after login, but when i set AllowOverride to none then it appends index.php in the url and it allows me to login to dashboard.

I have same configuration of Mautic on same server specification where i am running Mautic 2.15.1 and everything working fine and i dont have to remove `index.php ` from the url, so i believe its the issue with Mautic 2.15.2.

**Comment by escopecz** [comment]
Please remove the index.php part from the URL. It should not be there. Let us know if it solves the redirect issue.

**Comment by mjml1982** [comment]
Yes, when i remove the index.php it works.

**Comment by escopecz** [comment]
@luciano-lobo I'm a bit puzzled by your comment. There is [a quick fix](https://github.com/mautic/mautic/issues/7768#issuecomment-530094008) described from 3 days ago and yet you did not wrote whether you've tried it or not. What is easy engine?

**Comment by luciano-lobo** [comment]
problem solved, sorry for the inconvenience. thank you for the support. ee is a linux shell-script collection

**Comment by woxpeso** [comment]
Same here, when i removed index.php login works.

it's a litle bit confusing because inside the application index.php works (index.php/s/config/edit)

**Comment by DanFaudemer** [comment]
Same here, when I removed index.php in `local.php` and after **clearing the cache** I was able to login.

**Comment by rmalla** [comment]
> After update to 2.15.2 i could not change the URL of Mautic installation not to include the "index.php" in the configuration in the Backend. After manually changing the url in the app/config/local.php, the problem (GET 301 redirect) disappeared.

This resoled my problem too. Thanks!

**Comment by vivekshekar** [comment]
I still have the issue, 
I have v2.16.0 Apache 2.4
I cannot able to remove "index.php" from the url, 
I did tried removing from `app/config/local.php`
After that cleared the cache folder. 
And then when I try to my setup it gives me error, I cannot access login page at all. 
Please advise.

**Comment by escopecz** [comment]
In that case check that .htaccess is enabled as well as mod_rewrite.

**Comment by vivekshekar** [comment]
@escopecz 
Thank you for your reply. 
I double checked. `.htaccess`  and mod_rewire both are fine. 
This is how my `.htaccess` file looks like, 
```
# Use the front controller as index file. It serves as a fallback solution when
# every other rewrite/redirect fails (e.g. in an aliased environment without
# mod_rewrite). Additionally, this reduces the matching process for the
# start page (path "/") because otherwise Apache will apply the rewriting rules
# to each configured DirectoryIndex file (e.g. index.php, index.html, index.pl).
#DirectoryIndex index.php

<IfModule mod_rewrite.c>
    RewriteEngine On

    # Set Authorization header for OAuth1a for when php is running under fcgi
    RewriteCond %{HTTP:Authorization} .+
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Determine the RewriteBase automatically and set it as environment variable.
    # If you are using Apache aliases to do mass virtual hosting or installed the
    # project in a subdirectory, the base path will be prepended to allow proper
    # resolution of the app.php file and to redirect to the correct URI. It will
    # work in environments without path prefix as well, providing a safe, one-size
    # fits all solution. But as you do not need it in this case, you can comment
    # the following 2 lines to eliminate the overhead.
    RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]

    # Redirect to URI without front controller to prevent duplicate content
    # (with and without `/app.php`). Only do this redirect on the initial
    # rewrite by Apache and not on subsequent cycles. Otherwise we would get an
    # endless redirect loop (request -> rewrite to front controller ->
    # redirect -> request -> ...).
    # So in case you get a "too many redirects" error or you always get redirected
    # to the start page because your Apache does not expose the REDIRECT_STATUS
    # environment variable, you have 2 choices:
    # - disable this feature by commenting the following 2 lines or
    # - use Apache >= 2.3.9 and replace all L flags by END flags and remove the
    #   following RewriteCond (best solution)
    RewriteCond %{ENV:REDIRECT_STATUS} ^$
    RewriteRule ^index\.php(/(.*)|$) %{ENV:BASE}/$2 [R=301,L]

    # If the requested filename exists, simply serve it.
    # We only want to let Apache serve files and not directories.
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule .? - [L]

    # Rewrite all other queries to the front controller.
    RewriteRule .? %{ENV:BASE}/index.php [L]
</IfModule>

<IfModule !mod_rewrite.c>
    <IfModule mod_alias.c>
        # When mod_rewrite is not available, we instruct a temporary redirect of
        # the start page to the front controller explicitly so that the website
        # and the generated links can still be used.
        RedirectMatch 302 ^(?!/(index\.php|index_dev\.php|app|addons|plugins|media|upgrade))(/(.*))$ /index.php$2
        # RedirectTemp cannot be used instead
    </IfModule>
</IfModule>

<IfModule mod_php5.c>
    # @link https://github.com/mautic/mautic/issues/1504
    php_value always_populate_raw_post_data -1
</IfModule>

<IfModule mod_deflate.c>
    <IfModule mod_filter.c>
        AddOutputFilterByType DEFLATE application/javascript
        AddOutputFilterByType DEFLATE application/rss+xml
        AddOutputFilterByType DEFLATE application/vnd.ms-fontobject
        AddOutputFilterByType DEFLATE application/x-font
        AddOutputFilterByType DEFLATE application/x-font-opentype
        AddOutputFilterByType DEFLATE application/x-font-otf
        AddOutputFilterByType DEFLATE application/x-font-truetype
        AddOutputFilterByType DEFLATE application/x-font-ttf
        AddOutputFilterByType DEFLATE application/x-javascript
        AddOutputFilterByType DEFLATE font/opentype
        AddOutputFilterByType DEFLATE font/otf
        AddOutputFilterByType DEFLATE font/ttf
        AddOutputFilterByType DEFLATE image/svg+xml
        AddOutputFilterByType DEFLATE image/x-icon
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE text/javascript
        # Do not enable compression for file types that could contain secrets
        #AddOutputFilterByType DEFLATE text/html
        #AddOutputFilterByType DEFLATE text/plain
        #AddOutputFilterByType DEFLATE text/xml
        #AddOutputFilterByType DEFLATE application/xhtml+xml
        #AddOutputFilterByType DEFLATE application/xml
        #AddOutputFilterByType DEFLATE application/json
        <IfModule mod_setenvif.c>
            <IfModule mod_header.c>
                # Remove browser bugs (only needed for really old browsers)
                BrowserMatch ^Mozilla/4 gzip-only-text/html
                BrowserMatch ^Mozilla/4\.0[678] no-gzip
                BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
                Header append Vary User-Agent
            </IfModule>
        </IfModule>
    </IfModule>
</IfModule>

# Apache 2.4+
<IfModule authz_core_module>
    # Deny access via HTTP requests to all PHP files.
    <FilesMatch "\.php$">
        Require all denied
    </FilesMatch>

    # Except those whitelisted bellow.
    <FilesMatch "^(index|index_dev|filemanager|upgrade)\.php$">
        Require all granted
    </FilesMatch>
</IfModule>

# Fallback for Apache < 2.4
<IfModule !authz_core_module>
    # Deny access via HTTP requests to all PHP files.
    <FilesMatch "\.php$">
        Order deny,allow
        Deny from all
    </FilesMatch>

    # Except those whitelisted bellow.
    <FilesMatch "^(index|index_dev|filemanager|upgrade)\.php$">
        Order allow,deny
        Allow from all
    </FilesMatch>
</IfModule>
```
Please advise if I am missing anything here `.htaccess` 
Thank you,

**Comment by nkosi23** [comment]
I am having the same problem as @vivekshekar  . Initially I couldn't login, and after applying the fix (remove cache, and remove index.php from local.php), even the login page cannot be accessed, i am getting an infinite redirect (301) response.

**Comment by nkosi23** [comment]
I am behind a reverse proxy and the SSL termination point is at the reverse proxy (the connection between the reverse proxy and the mautic instance is not encrypted). I am accessing the mautic instance via unencrypted http since the connection goes through a VPN (people coming from the public internet cannot access the login page, there is a block rule in Apache).

I installed Mautic through the VPN tunnel so the site url was something like: "http://localhost:30000" during install. I then changed the site url to the public domain "https://domain.com" so that email links can work. This was all done on the same day (I am new to Mautic), things kept working for a while until later that day when I started rebooting Apache to fiddle with the php config in an attempt to try to fix an issue with file uploads (I cannot upload anything anywhere - Contact Imports are ignored, assets uploads fail even though they are well below the max size limit, and no php error is logged whatsoever, but this is a different topic). Then this problem appeared all of a sudden.

By (1) removing the "https" from the site_url in local.php to change it to "http" and (2) adding "index.php" back at the end of the site_url. I have been able to reach the login page again, however I am still unable to login, I am getting the 301 redirect loop to the login page, so in a sense I am back to square one. Actually square zero since this login issue wasn't on the map initially.

**Comment by TBS093A** [comment]
I have the same problem as @nkosi23, but I'm used nginx (https-portal) and v3-mautic image (everything on docker). Everything looks good when I deploy it on production, but several days ago this app going broken. I get warnings messages like bad csrf / invalid credentials on mautic login operation. login form sometimes redirect on /check_login or repeating infinite redirections. I don't know what is going on.
