### ISSUE TITLE
v2.15.2 not compatible with Nginx - can't update Mautic

### ISSUE THREAD

**Issue by directpromo** [mautic/mautic#7769]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When running update to v2.15.2 from url https://domain.com/s/update 
on step "Moving Package Contents" the process goes on and does not end get an error in server's logs

| Q   | A
| --- | ---
| Mautic version | v2.15.1
| PHP version | 7.1.29 (php-fpm)
| Nginx | 1.10.3
| Apache | not installed, not used

### Steps to reproduce

    1. start update from https://domain.com/s/update
    2. on step "Moving Package Contents" the process goes on and does not end
    3. view server's logs

 
### Log errors
Unable to open primary script: /home/www/domain.com//upgrade/upgrade.php (No such file or directory)" while reading response header from upstream, request: "GET /upgrade/upgrade.php?task=moveBundles&updateState=W10=&_=0124346542111&mauticUserLastActive=10&mauticLastNotificationId= HTTP/2.0

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by AkkuFresh** [comment]
Updating my system I also ran into similar problem (on step "Moving Package Contents" the process goes on and does not end), but manually deleting the contents of the App/Cash folder solved the problem.

**Comment by tradenet** [comment]
> Updating my system I also ran into similar problem (on step "Moving Package Contents" the process goes on and does not end), but manually deleting the contents of the App/Cash folder solved the problem.

Do you mean app/cache ? I tried that but still no luck.

**Comment by directpromo** [comment]
I tried to update after clearing the cache folder. The error repeats. Update failed.

**Comment by Bannerman** [comment]
Clearing the cache didn't solve this for me.

**Comment by AkkuFresh** [comment]
@tradenet Yes, that was the app/cache folder. And I am so sorry, I was careless. I have Apache 2.4 running not Nginx in my server.
I my case the manual deleting of the cache handled the failed update process.

**Comment by RafaelAybar** [comment]
I have no problem with: `nginx version: nginx/1.10.3`
`PHP 7.2.20-2+0~20190725.24+debian9~1.gbp69697c`
and `mysql  Ver 8.0.17`

**Comment by directpromo** [comment]
> I have no problem with: `nginx version: nginx/1.10.3`
> `PHP 7.2.20-2+0~20190725.24+debian9~1.gbp69697c`
> and `mysql Ver 8.0.17`

@RafaelAybar You do not have Apache installed near Nginx?
What version of Mautic do you have? 
Have you installed Mautic from scratch or upgraded from which version?

**Comment by RafaelAybar** [comment]
@directpromo I have not installed Apache, I am running a fresh installation of Mautic. I use the lastest release, 15.2

**Comment by tradenet** [comment]
> @directpromo I have not installed Apache, I am running a fresh installation of Mautic. I use the lastest release, 15.2.
> 
> I use debian 9

So this is a fresh install? Not an attempt to upgrade? Correct?

**Comment by RafaelAybar** [comment]
@tradenet yes, you are right.

**Comment by virgilwashere** [comment]
```console
$ nginx -v
nginx version: nginx/1.16.1
$ php -v
PHP 7.0.33-8+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May 31 2019 11:34:07) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-8+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
$ console | head -n 1
Mautic version 2.15.1 - app/prod
```
