### ISSUE TITLE
sudo -u www-data    php upgrade.php

### ISSUE THREAD

**Issue by lvnilesh** [mautic/mautic#7770]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
<img width="948" alt="Screen Shot 2019-08-06 at 6 15 12 PM" src="https://user-images.githubusercontent.com/93558/62587402-a2e3ca80-b876-11e9-91c1-f606f94f99c6.png">

Upgrade failed on a working mautic 2.15.1 on Debian GNU/Linux 9 (stretch) with Apache/2.4.25 (Debian) and PHP 7.2.16 

| Q   | A
| --- | ---
| Mautic version | 2.15.1 -> 2.15.2 
| PHP version |  7.2.16
| Apache version | 2.4.25 
| Browser | Firefox and Chrome and Safari

### Steps to reproduce

I clear cache

    sudo -u www-data   php app/console cache:clear

grab the upgrade script

    curl -O https://raw.githubusercontent.com/mautic/mautic/master/upgrade.php

attempt the upgrade to 2.15.2

    sudo -u www-data    php upgrade.php

The console did not report any errors and appeared that the upgrade went ok but browser shows errors as seen in the screenshot below.

 
### Log errors

Here is the logs I found on `/var/www/html/app/logs`
 
https://gist.github.com/lvnilesh/45ccdd23ba03da6242050e7dfddaa274
https://gist.github.com/lvnilesh/de53650ceda7ad07e7caae604abc7edb

Appreciate your help in ideas on getting my mautic working again with 2.15.1 or 2.15.2 or any earlier version.

Thanks.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by GenericUK** [comment]
Try cache:warmup

**Comment by GenericUK** [comment]
Try, 
rm -rf app/cache/*
app/console cache:warmup

**Comment by luizeof** [comment]
try to fix file permissions:

chown -R www-data:www-data .

**Comment by dsp76** [comment]
I experienced it in one of two upgrades today and it was fixed with clearing the cache another time.

**Comment by lvnilesh** [comment]
Thanks to @GenericUK and @luizeof for help with ideas and @dsp76 for confirmation. It took multiple attempts at force deleting cache folder and warming up while ensuring the recursive permissions are owned by `www-data` (this `www-data` is specific to debian, ubuntu and derivatives)
