### ISSUE TITLE
Webhook events are missing lead information

### ISSUE THREAD

**Issue by regevbr** [mautic/mautic#7773]
# Bug Description
I have set up a webhook that listens on subscription changed events, in order to update my systems when a user unsubscribes (DNC)
I came to realize pretty soon that __sometimes__, the contacts are not updated on my systems (they do get updated on Mautic).
After some investigation, I managed to realize the issue - the queued webhook event (the issue happens also when using immediate mode) is created but is missing all the contact information.

For example
```json
{  
    "contact":{  
        "isPublished":true,
        "dateAdded":"2019-07-09T20:22:23+00:00",
        "dateModified":"2019-08-08T08:45:05+00:00",
        "createdBy":null,
        "createdByUser":" ",
        "modifiedBy":null,
        "modifiedByUser":" ",
        "id":29913,
        "points":0,
        "color":null,
        "fields":[  

        ],
        "lastActive":"2019-08-08T08:43:02+00:00",
        "owner":null,
        "ipAddresses":[  

        ],
        "tags":[  

        ],
        "utmtags":[  

        ],
        "stage":null,
        "dateIdentified":"2019-07-09T20:22:23+00:00",
        "preferredProfileImage":"gravatar",
        "doNotContact":[  
            {  

            }
        ],
        "frequencyRules":[  

        ]
    },
    "channel":"email",
    "old_status":"contactable",
    "new_status":"unsubscribed"
}
```

This of course doesn't allow my system that processes the webhook to realize the user that this event is related to (the webhook does get sent)

Since the id of the lead is correct, my guess is that the DB call to the custom fields table failed, and as such the data is missing.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1
| Browser | NA

### Steps to reproduce
No idea how to reproduce as this happens sporadiclly

**Comment by regevbr** [comment]
current workaround - get the lead info by the supplied id from the REST api

**Comment by escopecz** [comment]
We have to figure out the exact steps to replicate. Otherwise it's close to impossible to fix it. I'll put the Pending Feedback label to mark that this issue needs additional information.

**Comment by regevbr** [comment]
Sadly I can't produce any additional information. If you have an idea where in the code it can happen, I can add logs to my production code to extract data.

**Comment by npracht** [comment]
Without extra information, let's close this issue.
