### ISSUE TITLE
IsToday with UTC config not working

### ISSUE THREAD

**Issue by Shulito** [mautic/mautic#7774]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I cannot get an "IsToday" condition in a campaign to evaluate to true based on a Date/Time custom field. It does work with a Date custom field (without time information).

| Q   | A
| --- | ---
| OS | Ubuntu 18.04.2 LTS
| OS Timezone | UTC -3 (Argentina/Buenos Aires)
| Mautic version | 2.15.2
| Mautic Default Timezone in Config | UTC
| PHP version | 7.2
| PHP Timezone in php.ini (cli and apache2) | UTC
| MySQL Timezone | UTC
| Browser | Firefox 68.0.1

### Steps to reproduce
1. Create a Date/Time custom field.
2. Create a Boolean custom field.
3. Add a new Contact and set the custom date field to today and the boolean field to false.
4. Create a segment with the contact created in step 3.
5. Create a new Campaign with the segment created in step 4.
    A. First Node => Condition (execute immediately)
                         => Contact Field: the date/time field
                         => Operator: date
                         => Value: Is Today
    B. False branch of condition created in A => Change Campaigns (execute immediately)
                                                                     => Add Contact To: This campaign (restart the campaign)
    C. True branch of condition created in A => Update Contact (execute immediately)
                                                                    => Set the boolean field to True
6. Publish the campaign.
 
### Log errors
No errors in log.

As stated above, if I use a Date field instead of a Date/Time field this works as expected: the conditions evaluates to true and the boolean field is updated.

Is this how you configure the timezones? How would you need to configure the timezones so the dates can be used in the frontend in a timezone other than UTC?

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Shulito** [comment]
I've just installed everything from scratch and configured everything for the timezone Buenos Aires (MySQL, Apache and Mautic) and IsToday works as expected if the custom field is of type Date, but with Date/Time it evaluates to false.

**Comment by dsp76** [comment]
Same here with 2.16.1

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
