### ISSUE TITLE
Salesforce integration - Sync record type

### ISSUE THREAD

**Issue by beloa-fr** [mautic/mautic#7778]
As record types set different business processes, Mautic would be able to send a specific field to set the salesforce record type. So the list of salesforce fields in the salesforce plugin should include it.

**Comment by escopecz** [comment]
What's the issue again? I'll close this issue. Please create a new one with clear description of what the issue is and provide the whole info that was requested in the issue template.

**Comment by beloa-fr** [comment]
OK done: https://github.com/mautic/mautic/issues/7797
