### ISSUE TITLE
Getting a 301 Moved Permanently (from disk cache)

### ISSUE THREAD

**Issue by mungovan** [mautic/mautic#7780]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
**| Bug report? |** 

## Description:
I have embedded a Mautic form in a WordPress site (different domain) and when the WordPress page loads it's giving a "301 Moved Permanently" error when trying to retrieve the following end point:
Request URL: https://subdomain.mymauticinstance.com/media/css/modal.min.css

Interestingly the WordPress page that has the form also attempts to hit the following endpoint:
Request URL: https://**www**.subdomain.mymauticinstance.com/media/css/modal.min.css

And it successfully is able to retrieve this with a 200 response. So it makes two calls to modal.min.css and the one that directs to www is successful. 

Similarly it fails when attempting:
Request URL: https://subdomain.mymauticinstance.com/media/js/mautic-form.js

Yet succeeds when hitting:
Request URL: https://**www**.subdomain.mymauticinstance.com/media/js/mautic-form.j

The form has a Download button on it and just says "Please Wait..." but doesn't do anything even through the endpoint also says it's successful and returns a 200:
Request URL: https://www.subdomain.mymauticinstance.com/form/submit?formId=4

I followed the instructions here:
https://github.com/mautic/mautic/issues/4016

Which included deleting the cache folder on my mautic instance along with the browser cache. I also tested on Chrome and Edge.

## If a bug:

| Q   | A
| --- | ---
| Mautic 2.15.1 | 
| PHP not sure?| 

### Steps to reproduce:
1.  Add a Mautic form to another website 
2. Load the website and inspect the page responses
 
### Log errors: 
I'm not seeing anything here in the error logs that helps.

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by mungovan** [comment]
I updated the site URL in mysite.com/s/config/edit and that resolved the issue.

**Comment by songil88620** [comment]
Hello, How are you...
Could you tell me the way how to solve this issue.
Is this issue domain config error OR other server setting error?
I tried on the side of server.. but there is no result..
Please help me to solve this issue.
Thank you.
