### ISSUE TITLE
Campaign decision not working for open email

### ISSUE THREAD

**Issue by rahulseo90** [mautic/mautic#7781]
Hi Team,

I am running below campaign where decision node(Open Email) always evaluates to NO path even after a mail is read within 30 secs. 
 
![mautic](https://user-images.githubusercontent.com/26229193/62857590-a8795e80-bd15-11e9-941e-7e981b10080e.png)

Thank you

**Comment by vnavarro55** [comment]
Hi!

We updated to 2.15.2 recently and have the same problem.

**Comment by escopecz** [comment]
Do you test the clicks in the browser that has no Mautic administrator cookie? See https://www.mautic.org/docs/en/emails/troubleshooting.html

**Comment by FerRubioMorales** [comment]
We have the same issue. I think it’s not a tracking issue because the email appear as open on the contact timeline but the campaign decission it’s going to the “no” branch.

Some help with this? Segments works correctly but it’s hard for us to implement all the logic using segments.

**Comment by npracht** [comment]
Hi guys, any way to clearly reproduce ?
Maybe an issue in your instance configuration with the root URL of the instance?

**Comment by tuiuiudev** [comment]
Hey, hey, 

We are facing a similar issue with the new release v2.16.2

As we update, it is not displaying in the campaign decision node (Open email).

![image](https://user-images.githubusercontent.com/66097503/83208047-0e12cc00-a12b-11ea-8844-764d334eebed.png)

Is there something wrong with us, or is it general?

Thanks for your attention. I’m looking forward to your reply.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by tuiuiudev** [comment]
> Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
> Thanks!

Hi RCheesley, how are you doing?

Thank you for your support, we have updated our version and it is working fine now.

Kind regards.

**Comment by RCheesley** [comment]
Great - thanks so much for letting us know!
