### ISSUE TITLE
Bundle doesn't read config changes

### ISSUE THREAD

**Issue by Riddeller** [mautic/mautic#7792]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Im new to bundle development for mautic. Im using this as a base: [HelloWorldBundle](https://github.com/anoop904/mautic/tree/master/storage/HelloWorldBundle).

My plugin I'm developing is installed and when I update the config I go back to Mautic and Click Install/Upgrade Plugins which should pick up the new plugin config but it doesn't as the menu items do not display.

My config looks like this:

```
<?php
// plugins/HelloWorldBundle/Config/config.php

return array(
    'name'        => 'Hello World Bundle',
    'description' => 'This is an example config file for a simple Hello World plugin.',
    'author'      => 'Marty Mautibot',
    'version'     => '2.0.0',
    'menu'     => array(
        'main' => array(
            'items'    => array(
                'plugin.helloworld.index' => array(
                    'id'        => 'plugin_helloworld_index',
                    'iconClass' => 'fa-globe',
                    'access'    => 'plugin:helloworld:worlds:view',
                    'parent'    => 'mautic.core.channels',
                    'children'  => array(
                        'plugin.helloworld.manage_worlds'     => array(
                            'route' => 'plugin_helloworld_list'
                        ),
                        'mautic.category.menu.index' => array(
                            'bundle' => 'plugin:helloWorld'
                        )
                    )
                )
            )
        )
    )
);
```

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.1.30
| Browser | Chrome

### Steps to reproduce
1. Install Bundle into Bundles Folder
2. Click Install/Upgrade Plugins
3. Update Bundle Config
4. Clear Cache
5. Click Install/Upgrade Plugins

 
### Log errors
No errors...

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Did you clear the cache after the config change?

**Comment by Riddeller** [comment]
@escopecz I did, multiple times. I've cleared using:

- php -d memory_limit=-1 /var/www/html/app/console cache:clear --env=dev
- Deleting cache folder

**Comment by escopecz** [comment]
If you try to add some simpler example like this one:

https://github.com/mautic/mautic/blob/staging/app/bundles/AssetBundle/Config/config.php#L50

Does it work?

If not, debug in the [MenuBuilder](https://github.com/mautic/mautic/blob/916cb750f2e7896c735b231c98fd9a58c65cf0e5/app/bundles/CoreBundle/Menu/MenuBuilder.php)

**Comment by Riddeller** [comment]
Still doesn't work.

I'm currently using docker-mautic to allow me to develop locally. I'm really struggling to begin developing for mautic.

**Comment by escopecz** [comment]
I gave up using Docker in my development process too. I can't help you with that. But here you can see actual Mautic plugin that has a menu item. It works. I use it in my plugins as well.

https://github.com/mautic/mautic/blob/staging/plugins/MauticFocusBundle/Config/config.php#L161

**Comment by Riddeller** [comment]
Yeah, I'm starting to feel the same. I might look at trying to create a development docker image for Mautic with a example plugin once I get it working. How do you debug MenuBuilder? (I'm .NET developer learning Symfony)

**Comment by escopecz** [comment]
I have Apache, PHP, Mysql and Mautic installed locally. I use Xdebug for debugging but if you don't want to configure it you can use `dump($variable);die();` to get a value out of a variable.

**Comment by npracht** [comment]
Hi @Riddeller and @escopecz i'll suggest to continue this [chat on Mautic Slack](https://www.mautic.org/slack/), this is more about configuration/installation than a software issue. Have a nice day.
