### ISSUE TITLE
CORS issue on ajax form submit

### ISSUE THREAD

**Issue by incentfit** [mautic/mautic#7793]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I created a form with id 1 on my new mautic 2.15.2 implementation.  I try to submit via ajax using `MauticJS.makeCORSRequest('POST', 'https://mautic.mysite.com/form/submit', {'mauticform[first_name]':'Test', 'mauticform[last_name]':'Test', 'mauticform[email]':'test@test.com', 'mauticform[formId]':1});` but it comes back with a CORS policy error even though the origin is explicitally included in the Valid Domains CORS Settings in the Mautic configuration.  I've also tried doing it using jQuery: `jQuery.ajax({
            url: 'https://mautic.mysite.com/index.php/form/submit',
            data: {'mauticform[first_name]':'Test', 'mauticform[last_name]':'Test', 'mauticform[email]':'test@test.com', 'mauticform[formId]':1},
            type: 'POST',
            headers: {'X-Requested-With': 'XMLHttpRequest'},
            crossDomain: true,
});`
The weird thing is that the data actually gets stored in Mautic as a successful form submission.  When using the MauticJS.makeCORSRequest method, it returns a `false` on subsequent requests from the same page up until the page is reloaded (I believe this is by design).  But the jQuery method works fine over and over again....despite the CORS issue being shown in the browser console.

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.2.19
| Browser | Chrome 76

### Steps to reproduce
1. Create a form with 3 fields (first_name, last_name, email).
2. Go to a different domain than the Mautic install, but one that is listed as a Valid Domain in CORS settings.
3. In the console of that page, enter in either of the code snippets from the bug description above.
 
### Log errors
Here's the chrome console:
![image](https://user-images.githubusercontent.com/13243272/62979584-3f1b4d80-bdf2-11e9-8440-f6d99290df95.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Riddeller** [comment]
@incentfit Mautic blocks all domain by default, you need add whitelist the website. 

1. Navigate to your **Mautic Admin -> Configuration -> System Settings -> CORS Settings -> Valid Domains** 
2. Add the full base URL (https://example.com) of the website that the requests are coming from.
3. Save & Apply the settings 
4. Retry your AJAX for submit

Hope this helps

**Comment by incentfit** [comment]
@Riddeller Yes I am aware of this and our full domain is already in that listing.  As I mentioned in the bug report, the form actually gets submitted successfully and the data gets saved in Mautic.  The CORS issue seems to happen after the submission is processed...

**Comment by Riddeller** [comment]
@incentfit When I used the forms I also added Access-Control-Allow-Origin the website the form is embedded on.

In your case you could try also adding **Access-Control-Allow-Origin: https://marketing.incentfit.com** to your wordpress installation.

**Comment by incentfit** [comment]
@Riddeller That doesn't quite make sense to me because the request is originating on incentfit.com and going to marketing.incentfit.com.  Also keep in mind that I don't actually have the form embedded in the site, I just have an ajax request originating from the site as a result of some other activity happening.  For testing purposes, I'm manually triggering the ajax request through the chrome console.

That being said, I tried your solution and unfortunately it didn't work.   You can verify that currently incentfit.com has an allow-origin header for marketing.incentfit.com:
![image](https://user-images.githubusercontent.com/13243272/63132443-1b413e80-bf8f-11e9-85b1-a1d91872d150.png)
and yet the ajax request is still not working:
![image](https://user-images.githubusercontent.com/13243272/63132475-2e540e80-bf8f-11e9-866c-be8169c7adaa.png)

**Comment by Riddeller** [comment]
@incentfit I was trying to understand the redirect which is in the form code. Just a thought have you cleared the mautic cache?

**Comment by incentfit** [comment]
Yes, I've cleared it several times using the command `sudo -u www-data php /var/www/html/app/console cache:clear`

**Comment by incentfit** [comment]
So it seems like something weird is going on here that's causing Mautic (hosted on marketing.incentfit.com) to redirect to Wordpress page (at incentfit.com) after a successful form submission.  I just tried implementing another form that doesn't use AJAX, and instead just uses the recommended mautic js embed.  After successfully submitting the data to Mautic, it still generates this console error: `Refused to display 'https://marketing.incentfit.com/form/submit?formId=4' in a frame because it set 'X-Frame-Options' to 'deny'.` and the submit button is stuck on Please Wait.

This seems to be related to the discussion happening here: [https://gist.github.com/escopecz/136f62b66d526bc32006f0d2358a8e15](https://gist.github.com/escopecz/136f62b66d526bc32006f0d2358a8e15)

**Comment by incentfit** [comment]
I got this to work for me. The trick was to include the mautic form name and messenger parameter.  I have no idea what the messenger parameter is but it's required otherwise I get errors. If anyone knows what that paramter signifies, plese share....

Here's the code:
`MauticJS.makeCORSRequest('POST', 'https://my.mauticsite.com/form/submit', {'mauticform[formId]':9999, 'mauticform[formName]': 'formnamefrommautic', 'mauticform[form_field_from_your_form]':'someformdata', 'mauticform[messenger]': 1});`
Just make sure to set all your post variables to match the formId, formName, and formFields...

**Comment by nguyencongvu** [comment]
> I got this to work for me. The trick was to include the mautic form name and messenger parameter. I have no idea what the messenger parameter is but it's required otherwise I get errors. If anyone knows what that paramter signifies, plese share....
> 
> Here's the code:
> `MauticJS.makeCORSRequest('POST', 'https://my.mauticsite.com/form/submit', {'mauticform[formId]':9999, 'mauticform[formName]': 'formnamefrommautic', 'mauticform[form_field_from_your_form]':'someformdata', 'mauticform[messenger]': 1});`
> Just make sure to set all your post variables to match the formId, formName, and formFields...


Please help me how to use MauticJS (how to create that Object in javascript)

**Comment by sheldoncoupeheure** [comment]
Thank you ! I would've never been able to fix this without your message.

**Comment by chris-aeviator** [comment]
I was only able to solve this by setting the CORS headers in my router/reverse proxy (traefik). It seems to be related to the redirect, though I'm also seeing this when setting the form reply to a message.
