### ISSUE TITLE
Salesforce Plugin - Set a record type

### ISSUE THREAD

**Issue by beloa-fr** [mautic/mautic#7797]
I want to be able to set a Salesforce record type in the Mautic Salesforce plugin.
Record type is used to set which workflow a lead should follow in Salesforce.
It is a required field named "RecordTypeId" in the lead object.
Without it, any new lead in Salesforce takes the default type, and you so cannot follow custom   workflows.

Q | A
Mautic version | 2.15.1
PHP version | 7.0
Browser | chrome 75.0.3770.142

Steps to reproduce:
1. Go to plugins
2. Select Salesforce
3. Go to contact tab
4. In the list of "integration fields", none exists for a "record type" (lead)

<img width="370" alt="integration-fields" src="https://user-images.githubusercontent.com/53921143/63087429-743eb180-bf52-11e9-95ad-0f4bcf771e14.PNG">

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/ideas as Github is for reporting bugs with Mautic whereas the ideas forum is where we discuss ideas for features and improvements :)
