### ISSUE TITLE
Salesforce plugin - Export lead tracking code

### ISSUE THREAD

**Issue by beloa-fr** [mautic/mautic#7798]
I want to be able to send a lead tracking code to Salesforce.
With this, it will be possible to created customf tracking urls in salesforce mails, following this format :

Https://mautic-host/r/asset-id?ct=tracking-code

Q | A
Mautic version | 2.15.1
PHP version | 7.0
Browser | chrome 75.0.3770.142

Steps to reproduce:

1. Go to plugins
2. Select Salesforce
3. Go to contact tab
4. In the list, I should have "Tracking code"

![image](https://user-images.githubusercontent.com/53921143/63087777-460da180-bf53-11e9-986e-966d92cbc769.png)

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/ideas as Github issues are for reporting bugs with Mautic whereas the ideas forum is where we discuss suggestions for new features.
