### ISSUE TITLE
[Feature] Allow merging of leads

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#78]
Sometimes there might be multiple instances of the same person - is it possible to merge leads?  Can they have multiple email addresses for the same person, for example?

Ideally selecting both leads and having some option to merge?

**Comment by alanhartless** [comment]
We don't have this feature yet but it's definitely in the road map for a future version.

Thanks!
Alan

**Comment by RCheesley** [comment]
Just wondered if this was any further along - it's an issue for a few of the potential projects we're looking to set up on Mautic including our own data, ideally I'd like to be able to multi-select on the lead list and press 'merge leads' - or go into a lead, and selectively merge with others.

**Comment by alanhartless** [comment]
The ability to merge leads was added to 1.2.
