### ISSUE TITLE
Error on Lead name (notification)

### ISSUE THREAD

**Issue by bhcruz** [mautic/mautic#780]
See the % name% </ strong> on confirmation notification:
https://gist.github.com/bhcruz/06e1f1317481e7e7c661

This brokes all the layout with </ strong> clode tag and hide all the action buttons. 

The error is on notification table, message field.

**Comment by escopecz** [comment]
I bet this error is related only to your language. Could you go to https://www.transifex.com/mautic/mautic/ and fix it there?

**Comment by bhcruz** [comment]
It was corected at transifex. ID 1323 of pt_BR lang ;)
Thanks

**Comment by escopecz** [comment]
Awecome.

The language will be built automatically (once a day) from Transifex, but you'll have to remove the language folder from `translations` folder, clear cache with the `php app/console cache:clear` command or just delete `app/cache` folder and then save the Mautic configuration.

**Comment by alanhartless** [comment]
Closing this as it's a Transifex issue. Should be resolved now if fixed in Transifex.
