### ISSUE TITLE
Errors while sending bulk emails using Mautic 

### ISSUE THREAD

**Issue by rahulseo90** [mautic/mautic#7801]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors
hi Team, 

I have faced several errors while sending bulk emails. 

1. When I sent 11k email to different segments, several got bounced back and the mautic graph is not reflecting anything.  And I got no result from those bulk emails. 
![imgs email mautic](https://user-images.githubusercontent.com/26229193/63259898-408ac100-c29d-11e9-947c-bee459091e2f.png)
 There was a temporary problem delivering your message to ccccc@companyname.com. Gmail will retry for 47 more hours. You'll be notified if the delivery fails permanently. 

**How can I check how many emails are delivered successfully?** 
**How can I check my emails are landing to clients inbox?** 

2. Mautic is showing only 2 email are read till now. 
![email mautic](https://user-images.githubusercontent.com/26229193/63259848-22bd5c00-c29d-11e9-96dc-2855339c766e.png)

**Why it is not showing actual stats?** 

3. Images are not visible in Gmail inbox but it’s working fine in outlook. 
When I inspected the image the URL was changed. Somehow google add URL just before the image URL. 
src=https://ci6.googleusercontent.com/proxy/sb5Z1pJpUdGuVnSoDK-yoV2dvWai7arv6xv3Ky2v5gyUEVsCfGKXbJ3XcQuVX1BkPeXEtA-9VCt1wrbP3S65zH2CyzdvOH2c0J7sdMg=s0-d-e1-ft#http://mktng.xxxxx.com/media/images/xxxxxxxxx.png

![email imgs](https://user-images.githubusercontent.com/26229193/63260299-23a2bd80-c29e-11e9-9e09-41bdd486c2aa.png)

**Why I am facing this error while it is working fine on other platforms?** 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Please post support requests on the forum at https://forum.mautic.org rather than Github.
