### ISSUE TITLE
Main domain does not generate access token when Mautic installation is present on subdomain of other server

### ISSUE THREAD

**Issue by atulshrma91** [mautic/mautic#7808]
I am getting the error when I try to access the mautic api from the main domain of one server. Mautic is installed on subdomain of other server.

Wordpress subdomain installations are working with same mautic installation(on same server) but main domain wordpress installation(of other server) is not connecting with the api and give us following error.

The response has unexpected status code (401).

Response: {"errors":[{"message":"Looks like I encountered an error (error #401). If I do it again, please report me to the system administrator!","code":401,"type":null}],"error":{"message":"Looks like I encountered an error (error #401). If I do it again, please report me to the system administrator! (error is deprecated as of 2.6.0 and will be removed in 3.0. Use the errors array instead.)","code":401}}

We have turned on api, cleared the cache, permit OAuth1a and started the session.

**Comment by RCheesley** [comment]
Please post requests relating to configuration and support on https://forum.mautic.org rather than on Github.
