### ISSUE TITLE
Allow database conversion to utf8mb4

### ISSUE THREAD

**Issue by enableit** [mautic/mautic#7810]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When attempting to convert a Mautic database to utf8mb4 on MySQL, the following errors prevent a successful outcome:

ALTER TABLE companies CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ERROR 1071 (42000) at line 1: Specified key was too long; max key length is 3072 bytes

ALTER TABLE email_copies CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
[Err] 1833 - Cannot change column 'id': used in a foreign key constraint 'FK_CA0A2625A8752772' of table 'testing_database.email_stats'

ALTER TABLE email_stats CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
[Err] 1832 - Cannot change column 'copy_id': used in a foreign key constraint 'FK_CA0A2625A8752772'

ALTER TABLE plugin_citrix_events CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
[Err] 1071 - Specified key was too long; max key length is 3072 bytes

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP Version | 5.4
| Browser | Any 

### Steps to reproduce
1. Try running the queries:
ALTER TABLE companies CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE email_copies CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE email_stats CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER TABLE plugin_citrix_events CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
 
### Log errors

No application errors as this is an external modification to the database schema

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
@escopecz i have the feeling we already have a discussion about this topic in the past and (i think) we said we should address that in M3. Does it sounds familiar to you?

**Comment by escopecz** [comment]
It does sound familiar. See https://johnlinhart.com/blog/my-mautic-3-wishlist#multibyte-utf8-database

**Comment by escopecz** [comment]
In fact, @hluchas was doing research on this topic today. I'll mark it as WIP as it will be on our plate sooner than later.

**Comment by hluchas** [comment]
We have part of automatic migration solving part of described problems (varchar used as FK in `email_copies`) and working on `companies` and dependent things which needs indexes converted to partial indexes and some dependent things as index management for custom fields which will need fixes too. 

We want to build fully automatic and consistent result soon.

**Comment by RCheesley** [comment]
@hluchas any progress on this issue at all?

**Comment by hluchas** [comment]
@RCheesley Not for now. I'm busy with something else :-/

**Comment by RCheesley** [comment]
OK - can you give any rough timelines so we can plan to include in a future release?

**Comment by hluchas** [comment]
@RCheesley I want to go through these this month (August). I'm still busy with internal task :-/

**Comment by escopecz** [comment]
Maybe I'm missing something but Mautic 3 uses utf8mb4 as the default encoding. So this is fixed for new installations. Is this issue about migration from M2 to M3?

**Comment by RCheesley** [comment]
I believe it was in relation to converting existing tables indeed - if this is dealt with in the migration then maybe we can close it - @enableit could you look into that?

**Comment by escopecz** [comment]
I don't think a normal migration can do this. It will have to disable all or most of constraints and it can run for hours on larger databases. No data can be inserted while this migration would run so the database would not end up in an inconsistent state. If we need that then it should be a separate script.

**Comment by RCheesley** [comment]
OK, this has a WIP label but it doesn't seem like anything is actually in progress. I don't think it is helpful to keep the issue open if nobody is going to work on it within Mautic and it's not something that would be included in core. I'd recommend if you still feel this is a helpful feature or addition to discuss it in the forums @enableit and if folk want to work on a standalone script it could be shared there.
