### ISSUE TITLE
Impossible to create a Company via API without giving full access

### ISSUE THREAD

**Issue by Aerendir** [mautic/mautic#7817]
## Bug Description
I'm trying to create, via API, a contact and a company and associate the contact to the company.

I've created a role "bot" and assigned it full permissions on `contacts` only (without giving him full permissions nor other fine grained permissions).

When I try to create the company, it is not created.

If I grant the role full system access, the company is created and correctly associated to the contact.

But if I want to give fine grained permissions to only give the possibility to create/edit companies and contacts, this is not possible: there is no section dedicated to companies.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
 
### Log errors

> mautic.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Permission class not found for company in permissions classes" at /var/www/archimede.serendipityhq.com/public_html/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php line 128 {"exception":"[object] (InvalidArgumentException(code: 0): Permission class not found for company in permissions classes at /var/www/archimede.serendipityhq.com/public_html/app/bundles/CoreBundle/Security/Permissions/CorePermissions.php:128)"} []

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by Aerendir** [comment]
@npracht , ok, I understand. Currently I'm still on 2.x version and I will upgrade in the next days.

I will comment here in case the problem continues on the new version, too.

Thank you for the feedback.

**Comment by npracht** [comment]
Thanks a lot @Aerendir !
And I'll follow up depending on your feedback :)
