### ISSUE TITLE
Invalid date of asset download

### ISSUE THREAD

**Issue by Simonell** [mautic/mautic#7820]
![Screenshot_2019-08-23 View Jankowski - Mautic](https://user-images.githubusercontent.com/2706043/63592224-5b1cad00-c5b1-11e9-9d45-e3ad4d48c912.png)
What type of report is this: Bug report

Description:
Mautic reported page hit "Yesterday, 3:30 pm", but asset download is in future - "Today, 3:30 pm".
From server side, every aspect of timezone looks ok.
Nothing interesting in logs.

Mautic version - 2.15.0
PHP version - 7.0.33-1

**Comment by npracht** [comment]
@Simonell were you able to reproduce it 100% of case ? Can you share more in details the different settings and how to reproduce (configuration side, sever side, campaign, etc.)

**Comment by RCheesley** [comment]
I think that this is related to #7306

**Comment by npracht** [comment]
Must be fixed by https://github.com/mautic/mautic/pull/7752 and/or https://github.com/mautic/mautic/pull/7617. Please test and confirm !

**Comment by dennisameling** [comment]
#7617 is merged for the 2.16.1 release, please test if that release (scheduled for March 25) fixes the issue :)

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
