### ISSUE TITLE
Segment filter 'Asset Downloads' don't list all the assets

### ISSUE THREAD

**Issue by toledomarcela** [mautic/mautic#7823]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Segment filter 'Asset Downloads' don't list all the assets to select independent of the asset kind or total downloads

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.1.27
| Browser | Chrome

### Steps to reproduce
1. Create a new segment with the filter 'Asset Downloads'
2. Try to select an asset
3. You'll notice that only shows a few assets even if you've created more
 
### Log errors
No errors were shown in logs

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
