### ISSUE TITLE
Fatal error: Class AppKernel.php on line 23

### ISSUE THREAD

**Issue by duchu** [mautic/mautic#7825]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have setup everything that should be done to get Mautic working properly. 
Cron - check 
Chmod - check 
Sending API - check 
Sending - setup to immediately

So wanted to test some sending to be sure that everything works fine. I have build campaign with small tree and marked to send. About 30 minutes of clam waiting to messages come to my inbox nothing happened. So I started to look for a reason why this config is not working. 
First thing to check was of course CRON, so i googled little bit and found little php script which should execute console task which should do CRON. 
When I tried to use any of links in this script every time same result 

`Fatal error: Class 'Symfony\Component\HttpKernel\Kernel' not found in /usr/home/user/domains/domain.com/public_html/app/AppKernel.php on line 23`

Few years ago somebody here have similar problem but solution him not working for me. All folders have write rights. 

So I want to ask you for any help 🙂 

| Q   | A
| --- | ---
| Mautic version | v2.16.0-dev
| PHP version | 7.1.21
| Browser | Safari 12.1.2

### Steps to reproduce
1. Setup campaign 
2. Try to send it
 
### Log errors

There is no error from Mautic

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by raghav111jain** [comment]
when submit 1 timethe form button show only "please wait " then 2 time submit the form your form submitted 
i don't understand and
*i check CROS on off both condition but same issue

**Comment by RCheesley** [comment]
Please post support requests on https://forum.mautic.org - it sounds like this is either an error in configuration or relating to file/folder permissions.
