### ISSUE TITLE
Invalid client ID during Instagram authentication

### ISSUE THREAD

**Issue by digitall-it** [mautic/mautic#7827]
## Bug Description
Cannot authorize the Instagram plugin using the Facebook Developers API client ID and secret.
Seems like the plugin tries to authenticate against the old Instagram API and not using the Facebook API for Instagram product. If that is the case, this is a feature request, otherwise, it is a bug report.
![Schermata 2019-08-28 alle 12 53 51](https://user-images.githubusercontent.com/3578378/63850040-8b8a8f80-c993-11e9-9fa5-470feeb54532.png)

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.1.31
| Browser | Safari 12.1.2 (14607.3.9)

### Steps to reproduce
1. Create a new app in the [Facebook Developer portal](https://developers.facebook.com)
2. Add the Instagram product
3. Publish the app
4. Go to Manage plugins, then Instagram
5. Try to authenticate using the ID and password of the Facebook app
6. Get the error message "Invalid client ID"
 
### Log errors
No error is logged

**Comment by dcambria** [comment]
Hi, same problem here.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
