### ISSUE TITLE
Event type "UTM tags recorded" showing on timeline even if the form submission has no UTM tags

### ISSUE THREAD

**Issue by shimisnow** [mautic/mautic#7828]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

I not sure if it is a bug or a feature request. When a form has a action "Record UTM Tags" and the form is submitted in a URL without UTM tags, the event type "UTM tags recorded" still appears on contact timeline.

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.0
| Browser | no apply

### Steps to reproduce
1. Create a standalone form
2. Include the Record UTM Tags action
3. Make a form submission with a URL without UTM tag (from site or preview mode)
4. UTM tags recorded appears on contact timeline with only the formId

![empty-utm-tags-recorded](https://user-images.githubusercontent.com/14943507/63863069-00ee6400-c984-11e9-8c84-785b6795befa.jpg)

### Log errors

No errors on Mautic Log

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
