### ISSUE TITLE
{webview_text} is not working properly?

### ISSUE THREAD

**Issue by rodolfomatos** [mautic/mautic#7829]
**Bug report**
Greetings. I apologize if what I am reporting is not a bug, but a "feature" and I'm doing something wrong.

**Description:** Every email that I send using a template that includes {webview_text} to have a "Having trouble reading this email? Click here" link, does not work properly.

**Mautic version:** 2.15.1 and 2.15.2 
**PHP version:** 7.2.19

Steps to reproduce (assuming there is a "test contact segment" created  with own email):
1. Channels > Emails > "+New"
2. Select "New Segment Email"
3. Select "New Blank" template (or any other in my case), write something in "Subject", "Internal Name" and use a "Contact segment" with your email
4. Save and close
5. Click on "Preview" and hover over "Having trouble reading this email? Click here"

In my case it shows https://{my domain}/email/view/xxxxxxxxxxxxxx

Ok, this is for trial so, I guess that is ok. Nevertheless, when I use "Send" or "Send Example" in page:

https://{my domain}/s/emails/view/32

what I receive in my email is a link like this:

https://{my domain}/email/view/5d66a291f32d9

And when I click on that one, I reach a page that says:

>  **"I'm sorry! I couldn't find the page you were looking for."** <br>404 Not Found

Funny enough, https://{my domain}/email/preview/32 works without being authenticated. Is that correct?

TIA any assistance on this matter.

**Comment by npracht** [comment]
Hi @rodolfomatos if this is a test email this is normal that the webview URL doesn't work.
If this is a real email, you still have the 404 ? If yes, can you check mautic logs after seeing the 404 ?

Thanks.

**Comment by shimisnow** [comment]
| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.0

I cannot reproduce the issue on my installation. When the preview is sended, the 404 error occurs, as @npracht pointed as normal. When sending the email for real, the web page opens as expected.

**Comment by npracht** [comment]
@rodolfomatos please confirm the issue was because of email test.

**Comment by rodolfomatos** [comment]
My bad, sorry.
Somehow I overlooked the ownership of the cache directory (was root instead of www-data):

[2019-08-29 10:54:02] mautic.CRITICAL: Uncaught PHP Exception RuntimeException: "Unable to write in the cache directory (/var/www/tmp/teste/prod/twig/68)." at /var/www/html/teste/vendor/twig/twig/lib/Twig/Cache/Filesystem.php line 61 {"exception":"[object] (RuntimeException(code: 0): Unable to write in the cache directory (/var/www/tmp/teste/prod/twig/68). at /var/www/html/teste/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:61)"} []

Thank you for your help and apologies for wasting your time.
