### ISSUE TITLE
JS Error embedding forms

### ISSUE THREAD

**Issue by jessenieminen** [mautic/mautic#783]
Whenever I try to add embed a new form on my WordPress page, I keep getting the same JS Error:

    Uncaught TypeError: Cannot read property 'querySelector' of null
    Form.validator.validator.disableSubmitButton @ mautic-form.js:26
    Form.validator.validator.validateForm @ mautic-form.js:13
    Core.validateForm @ mautic-form.js:27
    Form.prepareForms.forms.(anonymous function).onsubmit @ mautic-form.js:6

**Comment by jessenieminen** [comment]
As a result, the user is unable to submit any form on our website.

The form id is published and id correct. The same error happens, no matter whether I use the WP plugin shortcode, automatic JS embed or manual HTML embed method...

**Comment by alanhartless** [comment]
Is this still an issue with 1.2.0?

**Comment by jessenieminen** [comment]
Thanks for your reply!

I’m using the hosted version at mautic.com so I’m not aware of the version number in use but I haven’t gotten these for at least a few weeks now.

From: Alan Hartless
Reply-To: mautic/mautic
Date: Saturday 19 September 2015 07:09
To: mautic/mautic
Cc: Jesse Nieminen
Subject: Re: [mautic] JS Error embedding forms (#783)


Is this still an issue with 1.2.0?

**Comment by alanhartless** [comment]
Ok; I'll close this then.  Thanks!
