### ISSUE TITLE
Item Focus does not complete submission

### ISSUE THREAD

**Issue by marcelloinfoweb** [mautic/mautic#7833]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Problem in "Item Focus", but before I go through all the steps for creation: I create the asset, the form and finally the Item Focus. But when I insert code in the page that someone uses, it is just loading, does not download the asset and does not show the message I set, and sometimes shows the error 524 console. 

![error-focus-mautic-form](https://user-images.githubusercontent.com/2093128/63938891-4b331c00-ca3c-11e9-8c59-e53cdec4e214.png)

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.1
| Browser | Any

### Steps to reproduce
1. I create the asset
2. the form
3. the Item Focus
4. insert code in the page
 
### Log errors
![error-mautic-console](https://user-images.githubusercontent.com/2093128/63938866-39ea0f80-ca3c-11e9-83dc-45281a7bfc86.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Please post support requests at https://forum.mautic.org.
