### ISSUE TITLE
Missing clickthrough in the URL query (PublicController.php line 452)

### ISSUE THREAD

**Issue by trianity** [mautic/mautic#7841]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
PHP Notice about the Undefined index in ../app/bundles/PageBundle/Controller/PublicController.php on line 452

| Q   | A
| --- | ---
| Mautic version | v.2.15.2
| PHP version | 7.2.21 (for Mautic PHP-FPM handler)
| Browser | n./a.

### Steps to reproduce
1. ??
2. - did not find yet
 
### Log errors
Undefined index: ct in /home/path-to/mautic/app/bundles/PageBundle/Controller/PublicController.php on line 452

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

Here is the code from line 451 (starting with //) 
```
        // Unset the clickthrough from the URL query
        $ct = $query['ct'];
        unset($query['ct']);

        // Tak on anything left to the URL
        if (count($query)) {
            $url .= (strpos($url, '?') !== false) ? '&' : '?';
            $url .= http_build_query($query);
        }

        // If the IP address is not trackable, it means it came form a configured "do not track" IP or a "do not track" user agent
        // This prevents simulated clicks from 3rd party services such as URL shorteners from simulating clicks
        $ipAddress = $this->container->get('mautic.helper.ip_lookup')->getIpAddress();
        if ($ipAddress->isTrackable()) {
            // Search replace lead fields in the URL
            /** @var \Mautic\LeadBundle\Model\LeadModel $leadModel */
            $leadModel = $this->getModel('lead');
            $lead      = $leadModel->getContactFromRequest(['ct' => $ct]);

            /** @var \Mautic\PageBundle\Model\PageModel $pageModel */
            $pageModel = $this->getModel('page');
            $pageModel->hitPage($redirect, $this->request, 200, $lead);

            /** @var PrimaryCompanyHelper $primaryCompanyHelper */
            $primaryCompanyHelper = $this->get('mautic.lead.helper.primary_company');
            $leadArray            = ($lead) ? $primaryCompanyHelper->getProfileFieldsWithPrimaryCompany($lead) : [];

            $url = TokenHelper::findLeadTokens($url, $leadArray, true);
        }
```
The issue is easy to correct:
Change line 452:
```
-        $ct = $query['ct'];
+        $ct = $query['ct'] ?? '';
```

Change line 464:
```
-        if ($ipAddress->isTrackable()) {
+        if ($ct && $ipAddress->isTrackable()) {
```

If $query['ct'] data is missing, there is no need to any data process started in line 464.

**Comment by npracht** [comment]
Hi @AkkuFresh can you create a PR with that code ?

**Comment by AkkuFresh** [comment]
I am sorry I was out from this cycle. @AndrassGray PR works in practice.

**Comment by StoppingBuck** [comment]
I can confirm that this is still happening on Mautic 3.1. Getting the occational log message:

```
[2020-09-16 11:56:41] mautic.NOTICE: PHP Notice - Undefined index: ct - in file /var/www/html/mautic/app/bundles/PageBundle/Controller/PublicController.php - at line 451 {"redirectId":"b0dbc4a5049740aa11f808fb0","logger":"[object] (Symfony\\Bridge\\Monolog\\Logger: {})","redirectModel":"[object] (Mautic\\PageBundle\\Model\\RedirectModel: {})","redirect":"[object] (Mautic\\PageBundle\\Entity\\Redirect: Mautic\\PageBundle\\Entity\\Redirect with ID #3990)","url":"https://www.instagram.com/animanorge/?hl=en","query":[]} []
```

The PR by @AndrassGray does not fix the issue but merely hides the message. We still need to triage this to figure out how to fix it.

**Comment by trianity** [comment]
The issue is still exist, but suppress the notice message is better then doing noting. 
I had to handle a ~260 MB size PHP error log due to this issue today, related to the relative high traffic production Mautic instance.
Any idea?

**Comment by Plato39** [comment]
Issue still exists in version 3.1.2

**Comment by MartinMikita** [comment]
This issue still exists in version 3.2.5!

**Comment by jsieber** [comment]
This still exists in 3.3.1 Undefined index: ct in /opt/apps/mautic/htdocs/app/bundles/PageBundle/Controller/PublicController.php on line 458

**Comment by kuzmany** [comment]
Email trackable links are usually in format:


`https://urlofmautic.com/r/110a69363fd96ed4e28d8e662?ct=YTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7coxNDoiY2FtcGFpZ24uZXZlbnQiO2k6MTtpOjI1MTg7fXM6NToiZW1haWwiO2k6MTc5O3M6NDoic3RhdCI7czoyMjojBjMDY5MjI1OTk1NjMzMTkMDc1OCI7czo0OiJsZWFkIjtzOjY6IjI2MzI1NCI7czo3OiJjaGFubmVsIjthOjE6e3M6NToiZW1haWwiO2k6MTc5O319`

But bots https://github.com/mautic/mautic/issues/9798 transform it to 

`https://urlofmautic.com/r/110a69363fd96ed4e28d8e662?somethingelse=cccccc`

Then looks like for redirect links we required always ct param to be track clicks to contact. Probably without ct we should return 404 error page.

I will take look

**Comment by kuzmany** [comment]
This PR should fixed it https://github.com/mautic/mautic/pull/10418
