### ISSUE TITLE
Segment name does not support < character

### ISSUE THREAD

**Issue by shimisnow** [mautic/mautic#7846]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The symbol < is not supported in segment name.
Probably related with #3488

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.0

### Steps to reproduce
1. Create a segment
2. Name it "`Segment | 10000 < x <= 15000`"
3. Apply or Save and Close
4. The name will change to "`Segment | 10000`"
 
### Log errors
There is no errors on Mautic Log or Server Log

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Closing in favor of #3488, same topic.
