### ISSUE TITLE
"Please Wait" form issue ?

### ISSUE THREAD

**Issue by raghav111jain** [mautic/mautic#7847]
when submit the form "please wait" still here and error "403" but resubmit the form 
i tried many type and CROS on off both condition but same issue here 
please ASAP
*vision 2.15.1

**Comment by npracht** [comment]
Hi @raghav111jain. Thanks for your message but you don't respect the issue template. Please give more information by opening a correct PR. In your case this is impossible for me to reproduce without information, my forms are working properly.
