### ISSUE TITLE
Hosting Mautic on Ubuntu and I am having issues with the Virtual Host config file. Please help

### ISSUE THREAD

**Issue by hernandez949** [mautic/mautic#7851]
I have Mautic running fine using HTTP but I wanted to make it more secure and use HTTPS but i am having issues. Can you please help me resolve this I have attached some error log files. along with my VM host file.

Thank you in advance.

I am using Ubuntu 18.04, Apache2 
![error1](https://user-images.githubusercontent.com/43512431/64405940-5a662b00-d035-11e9-94a8-4a8dc21a8c95.png)
![Screenshot from 2019-09-05 23-34-36](https://user-images.githubusercontent.com/43512431/64406090-c6e12a00-d035-11e9-8c41-
![mautic](https://user-images.githubusercontent.com/43512431/64406152-eed08d80-d035-11e9-935f-3bbe51aae559.png)
![screen](https://user-images.githubusercontent.com/43512431/64406247-348d5600-d036-11e9-843a-a75af75e11b6.png)

ee1841c09968.png)

**Comment by hernandez949** [comment]
![config](https://user-images.githubusercontent.com/43512431/64406596-0e1bea80-d037-11e9-916b-5038ec2b76b6.png)

**Comment by hernandez949** [comment]
if i go to the website i get error 404 or if i type localhost i get error 404 but is i type localhost\s\ i get the login screen but once i type in my credentials i get error 500. any ideas?

**Comment by RCheesley** [comment]
Please ask these questions at https://forum.mautic.org where you'll find many more people, and maybe even some resources answering your questions already. Github is for bugs, rather than support requests :)
