### ISSUE TITLE
Obscure behavior of MauticJS.checkTrackingPixel()

### ISSUE THREAD

**Issue by loilo** [mautic/mautic#7852]
## Bug Description
Mautic executes JS code every 9ms.

| Q   | A
| --- | ---
| Mautic version | since 2.1.0
| PHP version | not relevant
| Browser | not relevant

I'm not entirely sure whether this is the desired behavior, but the underlying code strongly looks like a bug to me, hence the issue:

In version 2.1.0, a `MauticJS.pixelLoaded` function [has been added](https://github.com/mautic/mautic/commit/e8b6a0aee447d6837c8ed56bc263505f02daa5cc) (named [`MauticJS.checkForTrackingPixel`](https://github.com/mautic/mautic/blob/2.15.2/app/bundles/CoreBundle/EventListener/BuildJsSubscriber.php#L331-L360) today).

The function *looks* to me like it should
- wait for the DOM to load (invoking itself every 9ms to check)
- afterwards check for existence of the tracking pixel.

However, the conditional checking that determines whether the DOM is loaded [is negated](https://github.com/mautic/mautic/blob/2.15.2/app/bundles/CoreBundle/EventListener/BuildJsSubscriber.php#L332), so what the code actually does is this:
- In case the DOM is already loaded when the function is first invoked, do an infinite 9ms `setTimeout` loop and do nothing else.
- In case the DOM is *not* loaded on first invokation, check for the tracking pixel.

  In most cases, the pixel is probably still detected at some point since it tries for [3,000 times](https://github.com/mautic/mautic/blob/2.15.2/app/bundles/CoreBundle/EventListener/BuildJsSubscriber.php#L336) every [1ms](https://github.com/mautic/mautic/blob/2.15.2/app/bundles/CoreBundle/EventListener/BuildJsSubscriber.php#L358), which is around [12 seconds in practice](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Reasons_for_delays_longer_than_specified).

Since probably virtually nobody loads the Mautic script asynchronously (i.e. after the DOM has loaded), nobody noticed the infinite `setTimeout` loop. However, we've run into it recently which revealed this rather strange behavior.

If the described behavior is considered a bug by maintainers, I'm happy to attach a PR fixing this.

**Comment by RCheesley** [comment]
Sounds suspicious, as you say! 

I'd suggest that if you know how to fix this behaviour, go ahead with submitting a PR and it can be reviewed/discussed as appropriate!
