### ISSUE TITLE
Allow third party content with token in email builder

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#7856]
# Description
For Mautic 3 and email builder re-design, it would be great to anticipate the ability to get third (external) content with email token. For instance `{magento_product_img=48}` to display the image of product ID 48.

So the purpose of this message is not to integrate with Magento, but anticipate technically that third plugins (like Magento sync. for this example) use this technical feature to link content from the outside of the app.

**Comment by kuzmany** [comment]
It's possible add tokens and suggestions to builder by plugin at the moment very easy.

**Comment by dichvuhuuich** [comment]
> It's possible add tokens and suggestions to builder by plugin at the moment very easy.

Could you ·explain more detail, what plugin can use in this case?

**Comment by RCheesley** [comment]
I'm going to close this down as it seems like it's a better discussion for the forums given that it's already possible to add to the tokens and suggestions with a plugin.
