### ISSUE TITLE
Error when clearing cache

### ISSUE THREAD

**Issue by henriquekfmaia** [mautic/mautic#7857]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

| Q   | A
| --- | ---
| Mautic version | 2.16.0-dev
| PHP version | 7.1.30
| Browser | 76.0.3809.132

### Steps to reproduce
1. Clear Mautic Cache
2. 
 
### Problem
When I clear the Mautic cache, it gets inaccessible (ERR_TOO_MANY_REDIRECTS). It seems that the problem is with the .php files inside app/cache/prod, because when I copy back the old files to this folder, Mautic starts working again. I could not find this issue anywhere.

### Log errors
No logs were generated, either on app/logs and /var/log/apache2/error.log

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by nguyencongvu** [comment]
I cleared cache by rm -rf app/cache/* , then got same issues in 2.15.1 (ERR_TOO_MANY_REDIRECTS)

**Comment by RCheesley** [comment]
Clear your cache, and your browser cache as well. Check in an incognito window to see if it's still happening. Please post support questions on https://forum.mautic.org rather than Github :)
