### ISSUE TITLE
Email Builder's Drag & Drop has a strange behaviour if the email content overflows the size of the window vertically

### ISSUE THREAD

**Issue by lipppy** [mautic/mautic#7859]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
...

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 7.2.22
| Browser | Chrome|Firefox

### Steps to reproduce
1. Open the Email Builder, put some contents into the mail wrapper so that the mail content overflows the size of the window (it is in an iframe)
2. Scroll the email block down
3. Try to put a slot or a section into the mail at the bottom (you can not dot it properly because  the drag helper and the cursor are far from each other, the email iframe starts to scroll upward)
 
### Log errors
No errors.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
