### ISSUE TITLE
After upgrade to 2.15.2: Anonymous leads are identified and in the list of known leads

### ISSUE THREAD

**Issue by rally200hh** [mautic/mautic#7860]
After upgrading to 2.15.2 all anonymous visitors appear like identified user on contact tab. There is another bug in the reporting section, I will report later in another topic. 

![Anonyme Kontakte werden trotzdem angezeigt ](https://user-images.githubusercontent.com/55086073/64533657-3f850680-d314-11e9-8868-96b76c6cd6d5.JPG)

Can anybody help?

| Q   | A
| --- | ---
| 2.15.2 | 
| 7.0.31 | 
| Chrome | 

### Steps to reproduce
1. Upgrade from 2.15.0 to 2.15.2
2. app/console doctrine:schema:update --force --dump-sql
 
### Log errors
[2019-09-07 19:34:41] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE INDEX ma_last_active_search ON ma_leads (last_active)':  SQLSTATE[42000]: Syntax error or access violation: 1069 Too many keys specified; max 64 keys allowed (uncaught exception) at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 while running console command `doctrine:migrations:migrate` [] []
[2019-09-07 19:35:02] mautic.ERROR: SCHEMA ERROR: An index with name 'ma_title_search' was already defined on table 'ma_leads'. [] []
[2019-09-07 19:35:02] mautic.ERROR: SCHEMA ERROR: An index with name 'ma_title_search' was already defined on table 'ma_leads'. [] []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by MajesteitBart** [comment]
Same problem here, very annoying!

**Comment by rally200hh** [comment]
No solution available yet?

**Comment by MajesteitBart** [comment]
I haven't found any, but I'm not a developer. You could use a temp workaround: create a segment with filter "e-mail" is not empty. Work from there. The nasty thing is that deleting these 'anonymous' contacts will hurt you in the future, as they contain all tracking info.

**Comment by MajesteitBart** [comment]
Well, look at that. It seems to be related to the new feature identifying companies based on IP. Even though I have it disabled..
 https://github.com/mautic/mautic/issues/6837

**Comment by rally200hh** [comment]
Thanks for link. But I am not sure if this is really the problem. 

Disabling this function didn't not solve the problem of showing only IP adresses in the list of known leads in my installation ...

**Comment by MajesteitBart** [comment]
I know, but maybe it's related as in 'disabling the function doens't work'.

**Comment by buenomsg** [comment]
I think that other inconvenient is that this anonymous contacts are not been filtered in segments for instance.

**Comment by MajesteitBart** [comment]
I've just tried to install a clean instance, but it has the exact same issue.

**Comment by virgilwashere** [comment]
I'm seeing the same thing, with an extra symptom of form submissions that save to Contact fields are not creating a Contact with those details.

I have currently attributed that particular problem to PR #7614, as I have valid Contacts being created from Form submissions now.

**Comment by MajesteitBart** [comment]
What do you mean by that? Isn't this a completely unrelated bug?

**Comment by MajesteitBart** [comment]
I think this problem could be set to solved. It involved the bitnami install containing every field twice. This also included the Unique identifier fields. Deleting all the double fields and clearing the cache solved it.

**Comment by RCheesley** [comment]
@MajesteitBart if you are able, can you post this up on the Bitnami forums so that they might address/resolve this: https://community.bitnami.com/c/mautic? I'll close down the issue if this is Bitnami-specific.
