### ISSUE TITLE
Segment membership condition fails for manually removed leads

### ISSUE THREAD

**Issue by enableit** [mautic/mautic#7862]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.0
| Browser | n/a

### Steps to reproduce
1. Create two segments, one lead. Add lead to segment one and segment two
2. Remove lead from segment two
3. Create campaign with segment one as source, add condition with membership of segment two as filter
4. Run campaign

Expected results

Lead goes down unhappy path as is no longer member of segment two

Actual results

Lead goes down happy path
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
I have tried to reproduce this bug before looking at the PR, following the steps above, but I am not able to.

I created two segments - segment 1 and segment 2.  I added a lead to both segment 1 and segment 2 manually, and then subsequently removed them from segment 2. I confirmed they were only in segment 1 at this stage, post removal.

Campaign set up using segment 1 as a source, with condition of being in segment 2, and having a yes tag and a no tag option.

![screenshot-local mautictest-2019 10 16-12_14_45](https://user-images.githubusercontent.com/2930593/66914427-b21d8c00-f00e-11e9-8d0f-9603d68bf6f6.png)

The lead (correctly) has the 'no' tag applied (Segment-1-only).

![screenshot-local mautictest-2019 10 16-12_15_20](https://user-images.githubusercontent.com/2930593/66914437-b5b11300-f00e-11e9-83ee-7134f42c4e6d.png)

Are there some missing steps?

**Comment by enableit** [comment]
@RCheesley yes I've just tested this myself in Mautibox on a different PR and can't get it to break either. Do you know if there was a change to the way someone is removed from a segment membership, because looking at the code in the LeadListRepository class I can see it still doesn't filter out manually removed contacts? Otherwise there may be some other criteria to trigger the bug that is required - I'll try with the latest release.

**Comment by RCheesley** [comment]
Closing as I believe this was resolved with https://github.com/mautic/mautic/pull/7436 in 2.15.2.
