### ISSUE TITLE
valid email addresses being rejected

### ISSUE THREAD

**Issue by kalaleq** [mautic/mautic#7866]
What type of report is this: Bug report

## Description:
While performing an import, i noticed that some valid emails are being rejected.

The main one is emails with a period at the end of the local-part, which is valid - and actively accepted by gmail.  We have a lot of emails of the form some.name.@gmail.com which is valid but is being rejected by mautic.

It's also rejecting any email with a single quote in the local-part... which is a bit iffier but also technically valid according to RFC 5322 ; for example: john's-email@domain.com.  These ones *are* likely mistakes, but are technically valid.

There may be others but that's what i've seen so far.

| Mautic version | 2.15.2
| PHP version | 7.0.33-0+deb9u3

### Steps to reproduce:
1. Attempt to import any file with an email as mentioned above. The record will be rejected.
 
### Log errors: 

N/A/

**Comment by kalaleq** [comment]
Looks like the single quote (') may be commonly used by folks in Indonesia as so far it's all .id emails where i'm seeing that.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
According to this thread this is fixed in 3.0.1 so closing this issue: https://www.facebook.com/groups/mautic/permalink/3102440749876495/?comment_id=3102473346539902
