### ISSUE TITLE
Emails not getting sent after activation 

### ISSUE THREAD

**Issue by jankiis** [mautic/mautic#7873]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I am tried using gmail & elastic mail to send emails. Test Connection is successful but mails are not sent. Mautic is hosted on my servers, it worked fine in the sandbox.

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @jankiis, without more information we cannot reproduce...

**Comment by npracht** [comment]
Without extra information and being an old issue, let close it.
