### ISSUE TITLE
Suggest to add a new security header "ClientID" for Connectwise Integration

### ISSUE THREAD

**Issue by jjacinto0** [mautic/mautic#7882]
Hi, I found out that Connectwise added a new security header "ClientID". 
![clientid](https://user-images.githubusercontent.com/55176552/65477965-9402b700-deba-11e9-9178-92b480261c94.jpg)

I would like to request to add that in Connectwise Integration.

Thank you.

**Comment by RCheesley** [comment]
@jjacinto0 is this still relevant for Mautic 3.x? Would you be interested in submitting a PR to add this, if so? We do not have many folk using this integration so it would be super helpful to know if it's still a problem!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by Sagardeep-Singh** [comment]
Hi, the clientID value is still missing in the plugin. If no one else is working on this, I can try fixing it and submit the code for consideration for a pull request.

**Comment by RCheesley** [comment]
@Sagardeep-Singh that would be great if you are able to make a PR! Shout if you need any help!

**Comment by RCheesley** [comment]
@jjacinto0 please test the PR that addresses this: #9857
