### ISSUE TITLE
Mautic logs false positive email openings done by GoogleImageProxy (gmail)

### ISSUE THREAD

**Issue by pety-dc** [mautic/mautic#7884]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When emails are sent out, gmail immediately scans the images and Mautic logs tracking pixel openings done by GoogleImageProxy.
This behaviour leads to higher load (GoogleImageProxy requests tracking pixel urls much faster than leads would do.)
This behaviour probably messes up email statistics
This behaviour probably messes up campaigns that rely on email read

https://github.com/mautic/mautic/issues/1298

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2.x
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
I don't know if it is a bug, i have no idea how we should skip Gmail behavior... or even if this is possible. @escopecz an opinion ?

**Comment by pety-dc** [comment]
I gave a few minutes of reading to the topic. Sure, it's not easy, many struggle with this google feature.

There are a few ideas:
- http://octeth.com/blog/gmails-new-image-proxy-feature-and-quick-work-around/
- https://stackoverflow.com/questions/20903967/gmails-new-image-caching-is-breaking-image-links-in-newsletter

**Comment by cyanstar** [comment]
A lot of email platforms give a break down on email client in the email report. It might be worth looking at something similar. We already know on an individual basis which email clients people use. So giving a report on which clients our users are using could help resolve this. I also know Hubspot gives a statement about Gmail in their email overviews, could be worth doing something similar as well.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by swadeshp** [comment]
This bug is still present on v3.3.2
Emails sent on gmail triggers read event, even when emails are not read. Just by opening your gmail account GoogleImageProxy triggers the event. Doesn't matter if email is opened or not.

**Comment by HappyCustomers** [comment]
@npracht &  @RCheesley The Bug is still present  3.2.1. when email sent to Gmail is shows as read even before the email is open.

**Comment by aleeepp** [comment]
Same issue here v3.3.2 👍

**Comment by hounw** [comment]
Same issue here... v3.3.3

**Comment by ghost** [comment]
v4.4.6 issue still persists
