### ISSUE TITLE
Pipedrive sync: Issue when pushing Single options fields from mautic to pipedrive

### ISSUE THREAD

**Issue by janwinkler** [mautic/mautic#7885]
## Bug Description
1. Create a "Single options field" in Pipedrive and Mautic like mentioned [here](https://www.mautic.org/docs/en/plugins/pipedrive.html) under "Multiselect custom field".
2. select an option for this field in a pipedrive contact
3. run .../app/console mautic:integration:pipedrive:push
result: mautic will sync the contact, the contact-field in pipedrive will become empty (current value removed)

![grafik](https://user-images.githubusercontent.com/1705243/65336262-59510400-dbc6-11e9-8ca6-23fd5bd03a70.png)
![grafik](https://user-images.githubusercontent.com/1705243/65336307-6ec62e00-dbc6-11e9-9583-2119b875d414.png)
before mautic:pipedrive:push:
![grafik](https://user-images.githubusercontent.com/1705243/65336378-8bfafc80-dbc6-11e9-9c15-eab180525cbd.png)
after mautic:pipedrive:push:
![grafik](https://user-images.githubusercontent.com/1705243/65336407-99b08200-dbc6-11e9-91d5-55e049f35ce6.png)

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.0.33
| Browser | all

**Comment by janwinkler** [comment]
PS: The issue does not appear when the contact is edited in mautic manually. e.g. if I edit the contact in mautic, the correct value appears in pipedrive. 
PPS: the issue exists for single choice and multiple choice fields

**Comment by npracht** [comment]
@florentpetitjean can you help @janwinkler ? Can you reproduce ?

**Comment by npracht** [comment]
@florentpetitjean ?

**Comment by florentpetitjean** [comment]
Hello, 

I don't reproduce but it seems that you have one more filed in the list in Mautic than in Pipedrive, you must have the exact same value (empty field or not) in the 2 side for the sync to work for list.
