### ISSUE TITLE
Narrow contact activity events per segment through REST API

### ISSUE THREAD

**Issue by jonin** [mautic/mautic#7888]
Documentation hints that it is possible narrow down contact activity with "filters" param in REST API:
https://developer.mautic.org/?json#get-activity-events-for-all-contacts

It would be great to have the list narrowed down to certain segment, i.e. in order to pick up certain segment's activity during a given time period.

(<api-url>/contacts/activity?filters[segment:somesegment] does not seem to work)

**Comment by RCheesley** [comment]
Hi there @jonin thanks for the suggestion, could you propose a PR to implement this? Happy to support if you need any pointers!
