### ISSUE TITLE
When saving a new email template email, after removing English as language, I get the error "500 Internal Server Error"   

### ISSUE THREAD

**Issue by rrrspirit** [mautic/mautic#7889]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When saving a new email template, after removing English as language, I get the error "500 Internal Server Error"   

To solve it, I need to create a new user account, and continue working from there. Then after each hours brokes again. 

| Q   | A
| --- | ---
| Mautic version | v2.16.0-dev
| PHP version | 7.2
| Browser | Chrome

### Steps to reproduce
1. Go to channels, email, new, save as template, then fulfill some name and internal name, remove english as language and try to save it. 
2.  Appears the text: Uh oh! I think I broke it. If I do it again, please report me to the system administrator! 500 Internal Server Error - Mautibot - Report an issue
 
sometimes work fine, sometimes brokes. Once it brokes, I have to delete the user and create a new one to be able to continue working. 

### Log errors
where to check?

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to the lack of response.
