### ISSUE TITLE
Users not being tracked

### ISSUE THREAD

**Issue by toma10** [mautic/mautic#7890]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I am trying users tracking on Wordpress page using WP Mautic plugin (with turned on Track user information when logged on? option). It does not matter if I am logged in or not, no page is being tracked. mtc/event is send with a result of {success: 1, id: null, sid: null, device_id: null, events: [false]}. If I insert a form into a page and submit, cookies are set, and the user begins to be tracked, but the logged user info from Wordpress is not paired in Mautic. Is this current behavior? I would like the user to be always tracked, without having to submit the form. When using form, I want logged in user not to have to fill in email but use user's email  from Wordpress. Am I missing something?

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.30
| WP Mautic | 5.2.3

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @toma10 do you have a cookie management system setup ?

**Comment by toma10** [comment]
@npracht What do you mean cookie management system? Can you guide me?

**Comment by npracht** [comment]
anything used to be GDPR compliant with cookies. Like https://opt-out.ferank.eu/en/ or any other solution.

**Comment by toma10** [comment]
@npracht I tried [https://opt-out.ferank.eu/en/](https://opt-out.ferank.eu/en/) free version, but nothing new for me. It only blocks mtc/event request until you allow cookie usage for mautic. But it still only tracks user if mautic form inserted in wordpress page/post is submitted. It also ignores logged in user information.

**Comment by cesarZubillaga** [comment]
I am having the same error trying to create anonymous contacts in a local environment. I have a basic html in http://localhost:8002/index.php.

First request to mtc returns object:
{
    "id":null,
    "sid":null,
    "device_id":null
}

second request which sends POST variables with title and so on responds with:

{
  "success": 1,
  "id": null,
  "sid": null,
  "device_id": null,
  "events": [
    false
  ]
}

There is a new cookie added to the page.

**Comment by cesarZubillaga** [comment]
Again I did with an extra parameter the request ({company: 'name'}) and I am having this in the server logs.

`[2019-10-15 16:10:19] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\LeadBundle\Entity\CompanyLead#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\LeadBundle\\Entity\\CompanyLead#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #. 
To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []

[2019-10-15 16:10:19] mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\LeadBundle\Entity\CompanyLead#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 92 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\LeadBundle\\Entity\\CompanyLead#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #. 
To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92)"} []`

**Comment by cesarZubillaga** [comment]
Ok, in my case there was a environment configuration. Basically the IP that was doing the request wasn't trackable for the production environment. This was because the real ip wasn't send and the IpLookupHelper didn't work.

Anyways I have to send always the company to create a new contact.

**Comment by toma10** [comment]
It's important to have current version of IP lookup service. If Mautic is running on same machine as Wordpress page, you have to add `track_private_ip_ranges` configuration option to `true` in `app/config/local.php` (for local development). To update (and sync) email from Wordpress page to Mautic, email field in Custom Fields must be set to Publicly updatable.
