### ISSUE TITLE
Why getTrackedLead() return null instead lead?

### ISSUE THREAD

**Issue by bookin** [mautic/mautic#7891]
I found this line in the code:
```
$anotherDeviceAlreadyTracked = $this->leadDeviceRepository->isAnyLeadDeviceTracked($lead);
return $anotherDeviceAlreadyTracked ? null : $lead;
```
[Source](https://github.com/mautic/mautic/blob/916cb750f2e7896c735b231c98fd9a58c65cf0e5/app/bundles/LeadBundle/Tracker/Service/ContactTrackingService/ContactTrackingService.php#L115)

And I can't understand why function returns null if user has tracked devices.
Perhaps it is a bug or I can't understand something.

**Comment by RCheesley** [comment]
@bookin can you please post this as a query in the development category on https://forum.mautic.org rather than reporting as an issue on Github? Thanks!

**Comment by bookin** [comment]
It more like a bug, so I don't see reason post it on forum
