### ISSUE TITLE
Sendgrid API: Email clicks not being tracked.

### ISSUE THREAD

**Issue by YosuCadilla** [mautic/mautic#7892]
## Bug Description

Using Sendgrid API to send emails (no queue).
Emails are delivered and opens are tracked.
**Clicks on emails links are not tracked.**
Mautic returns this warning once per connection to Sendgrid:
mautic.WARNING: PHP Warning - count(): Parameter must be an array or an object that implements Countable - in file  /var/www/html/app/bundles/EmailBundle/Swiftmailer/Transport/SendgridApiTransport.php - at line 141 {"message":"[object] (Mautic\\EmailBundle\\Swiftmailer\\Message\\MauticMessage: Message-ID: <55282c8a3b080103a29acae725296f77@mautic.example.com>\r\nDate: Wed, 25 Sep 2019 14:56:07 +0000\r\nFrom: \r\nTo: name lastname <name.lastame@example.com>, Madt/plain; charset=utf-8\r\nContent-Transfer-Encoding: quoted-printable\r\n)","toBeAdded":1,"type":"to"} []

| Mautic version: 2.15.2 | 
| PHP version |  7.2

### Steps to reproduce
1. Send a campaign or broadcast email via Sendgrid API containing a link in the email.
2. Open the email in your email client, click on the link.
3. Check email statistics (open is tracked, click is not)
3. Check logs, see if the warning msg appears.

### Log errors
mautic.WARNING: PHP Warning - count(): Parameter must be an array or an object that implements Countable - in file  /var/www/html/app/bundles/EmailBundle/Swiftmailer/Transport/SendgridApiTransport.php - at line 141 {"message":"[object] (Mautic\\EmailBundle\\Swiftmailer\\Message\\MauticMessage: Message-ID: <55282c8a3b080103a29acae725296f77@mautic.example.com>\r\nDate: Wed, 25 Sep 2019 14:56:07 +0000\r\nFrom: \r\nTo: name lastname <name.lastame@example.com>, Mad$$t/plain; charset=utf-8\r\nContent-Transfer-Encoding: quoted-printable\r\n)","toBeAdded":1,"type":"to"} []

**Comment by npracht** [comment]
Hi @YosuCadilla,

I don't see the link with Sendgrid knowing that the clicks are managed by mautic. How is your email settings setuped?

**Comment by YosuCadilla** [comment]
Hi @npracht, 
To be honest I don't know what the relationship could be (if any).
This is the only error msg I could find in Mautic Logs (or elsewhere), I figured out maybe SendgridApiTransport.php is not able to "count" the clicks and might be dropping the whole click tracking because of that?

**Comment by YosuCadilla** [comment]
My email is sent directly (no queue) via API connector to Sendgrid.

**Comment by YosuCadilla** [comment]
Just checked back the Apache logs and there I get a similar error:

[proxy_fcgi:error] [pid 12281:tid 140674504120064] [client 10.11.18.16:56570] AH01071: Got error 'PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in  /var/www/html/app/bundles/EmailBundle/Swiftmailer/Transport/SendgridApiTransport.php on line 141\nPHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/app/bundles/EmailBundle/Swiftmailer/Transport/SendgridApiTransport.php on line 141\nPHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/app/bundles/EmailBundle/Swiftmailer/Transport/SendgridApiTransport.php on line 141\nPHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/app/bundles/EmailBundle/Swiftmailer/Transport/SendgridApiTransport.php on line 141\nPHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/app/bundles/EmailBundle/Swiftmailer/Transport/SendgridApiTransport.php on line 141\n', referer: https://mktg.jabmo.com/s/emails/send/12

**Comment by RCheesley** [comment]
@YosuCadilla got someone reporting this in Slack also: https://mautic.slack.com/archives/C02GEN0SG/p1570088744249500

**Comment by YosuCadilla** [comment]
Thanks @RCheesley, we're trying to determine if his issue and mine are the same, we're not getting the same error msgs tho, I told him to add his input here...

**Comment by YosuCadilla** [comment]
Update: Because the particular Mautic instance with the issue is behind a proxy, I'm testing whether headers where correctly being transmitted.

So: I have tested the website click tracking (via WP-Mautic plugin) and it's working fine.
I'm assuming that since both use the same URL rewriting and tracking method this rules out any proxying issues? Please tell me if I'm wrong so I can further test any relationship of the proxy with this issue, thank you!

**Comment by YosuCadilla** [comment]
Today I have tested with 2.15.3-beta, same results sadly.

**Comment by YosuCadilla** [comment]
Today I have completely bypassed the proxy, just in case... no luck (2.15.2)

Just in case I hadn't clearly stated this before:
- URLs are being rewritten.
- Opens are tracked correctly.
- Page hits are registered correctly.

**Comment by YosuCadilla** [comment]
Note: Email's view in browser and unsubscribe links also works properly.

**Today I've tested on 2.15.3 (non-beta) problem persists.**
@npracht is that enough feedback to mark as bug?

**Comment by YosuCadilla** [comment]
A new installation of 2.15.2 I think, no it started before any Mautic upgrades and persisted after these...

**Comment by ZenDevMaster** [comment]
Have just recently begun to use Sendgrid API and also experiencing the same. Read reports, etc seem fine. But link click tracking is clearly not working - Google analytics showing a lot of hits on the landing page but no clicks are reported in Mautic

**Comment by YosuCadilla** [comment]
@ZenDevMaster are your website visits correctly tracked / reported in Mautic compared to GA?

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
