### ISSUE TITLE
Mautic upgrade 2.15.2 broke my installation

### ISSUE THREAD

**Issue by digitart** [mautic/mautic#7894]
## Bug Description
Trying to upgrade from the dashboard from 2.14.0 to 2.15.2 keeps updating forever.
When I tryed to run /upgrade.php directly I get "The site is currently offline due to encountering an error" message and nothing worked anymore.
I wipe it off and tryed a fresh install of 2.15.2 but I get the same message and couldn't even run the install.
Finally I deleted everything and uploaded my 2.14.0 backup and now it's running again.

BTW in my 2.14.0 version I have to change from
`const MAUTIC_MAXIMUM_PHP = '7.1.999'; `
to 
`const MAUTIC_MAXIMUM_PHP = '7.2.999'; `
in VersionCheckMiddleware.php to be able to run Mautic on PHP 7.2.22

| Mautic version |  2.15.2
| PHP version |  7.2.22
| Browser |  Firefox 69.0.1

### Steps to reproduce
1. Update from the Dashboard (didn't upgrade at all) or
2.  Run mysite.com/upgrade.php or
3. A fresh install of ver 2.15.2
 
### Log errors
```
[Fri Sep 27 02:06:43.644317 2019] [php7:notice] [pid 17454] [client 187.189.197.161:18256]
 Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Type error: 
Too few arguments to function Mautic\\LeadBundle\\Model\\FieldModel::__construct(), 2 passed in 
/home/publixit/mautic.publixite.com/app/cache/prod/appProdProjectContainer.php on line 12516 
and exactly 3 expected - in file /home/publixit/domains/publixite.com/public_html/mautic/app/
bundles/LeadBundle/Model/FieldModel.php - at line 324
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there,

There is a [beta release of 2.15.3](https://github.com/mautic/mautic/releases/tag/2.15.3-beta) which was made last Friday. This should be available for general release at the end of the week if testing goes OK.

In the meantime, it might be worth trying a local installation to see if you still have issues?

If you do come across problems with updates failing or not running, please follow these steps: https://www.mautic.org/docs/en/tips/update-failed.html.

**Comment by npracht** [comment]
Also please do what is mentioned here and share feedback --> https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful
