### ISSUE TITLE
Permission error when adding a campaign (campaign builder)

### ISSUE THREAD

**Issue by ojaneri** [mautic/mautic#7897]
Bug Report

## Description:
Error, without permission on campaing builder, when adding a source origin (any)

## If a bug:

PHP Version 7.2.19-0ubuntu0.18.04.2

### Steps to reproduce:
1. Campaign / new
2. Campaign Builder / Choose a new origin source
 
### Log errors: 

On error log, it shows [2019-09-27 23:54:17] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM mautic_lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'wordpress.mautic_lead_fields' doesn't exist [] []

**Comment by ojaneri** [comment]
![erro mail](https://user-images.githubusercontent.com/9010906/65809315-9abb5380-e172-11e9-9785-a34764be3434.PNG)

**Comment by npracht** [comment]
hi @ojaneri. The message is clear, a table is missing in your DB, please follow instructions here https://www.mautic.org/docs/en/tips/troubleshooting.html or here https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

**Comment by npracht** [comment]
Without extra information and being an old issue, let close it.
