### ISSUE TITLE
[Feature] Joomla registration -> Mautic lead

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#79]
If a user registers on a Joomla site (or indeed any CMS), it would be really helpful if that could be tied up with the info we know from the IP address (tracked with the pixel) and push the additional information into Mautic - maybe even trigger point changes.

Not sure if this would require a separate plugin or if the current plugin could do it, but could be useful?

**Comment by alanhartless** [comment]
The first one can possibly be done by utilizing the newly adding "Is publicly updatable" toggle for a lead field added in RC1. This basically allows that field to be updated via a query appended to the tracking pixel URL.  For example, mtracking.gif?customfieldalias=my%20value

Of course we'd have to implement some kind of UI into the Joomla plugin to be able to custom define the fields to be passed.  What additional information are you wanting to capture and by what means is that information captured (a 3rd party Joomla extension, something in the $_SERVER variable, etc?

We'd have to add the option to trigger a point change based on updating a lead's details though so marking this as a feature request for us to prioritize into the roadmap.

Thanks!
Alan

**Comment by RCheesley** [comment]
Basically, registering on a site is an important action - and I could envisage people wanting to change points values based on that action happening.

In the case of a registration (but this could apply to purchase, subscription, etc) you would probably want

- Date of registration
- Email address/name (for matching/updating lead fields)
- IP address

Ecommerce would get more complex as you'd want to know products purchased, value, date of purchase, etc. but that's probably for the other issue regarding ecommerce integration.

Ruth

**Comment by alanhartless** [comment]
If I'm not mistaken, this feature is no available in the Mautic Joomla Plugin so closing this.
