### ISSUE TITLE
Strange response on sending message to contact via API at 2.15.2

### ISSUE THREAD

**Issue by kote-isaev** [mautic/mautic#7900]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Scenario:
Send email to contact via API endpoint.
request has been sent from node.js, via superagent npm package using basic auth. 
This setup worked nicely before upgrade to 2.15.2.
| Q   | A
| --- | ---
| Mautic version | 2.15.2 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Send email template to contact using basic auth
2. From time to time response from API is 
```js 
{"success":false,"failed":[]}
```
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @konstardiy could please give more information about how to reproduce ? What info to you send to API ? Which route ? How are you authentified ? 
Like that we cannot reproduce.
Thanks

**Comment by koteisaev** [comment]
I use following nodejs code snippet to call the API inside nodejs backend with node 8.16.0:
```js
/**
 *
 * @param requestProperties
 * @param {string} requestProperties.url
 * @param {string} requestProperties.method
 * @param {*=} requestProperties.body
 * @param {boolean=} requestProperties.allowRetry
 * @param {number=} retryIndex
 * @param {Object[]=} errors
 */
function invokeMauticAPI(requestProperties , retryIndex, errors) {
    if (requestProperties.allowRetry) {
        retryIndex = (retryIndex === undefined || retryIndex < 0) ? 0 : retryIndex;
        if (errors === null || errors === undefined) {
            errors = [];
        }
    }
    return new Promise((resolve, reject) => {
        let caller = saRequest[requestProperties.method.toLowerCase()](requestProperties.url);
        caller = caller.set("Authorization", "Basic " + generateMauticAuthToken());
        if (requestProperties.body !== undefined && requestProperties.body !== null) {
            caller = caller.send(requestProperties.body);
        } else {
            caller = caller.send();
        }
       caller.end((err, response) => {
           if (err) {
               if (response && !err.response) {
                   err.response = response;
               }
               return reject(err);
           }
           if (response.ok) {
               //creepy case made by mautic which is surely NOT very REST-full
               if (response.body && response.body.success === false) {
                   let errObj = new Error(`Error response from mautic with status ${response.status} `);
                   errObj.details = response.body;
                   reject(errObj);
               }
               return resolve(response.body);
           }
           let errObj = new Error(`Error response from mautic with status ${response.status} `);
           errObj.response = response;
           return reject(errObj);
       })
    }).catch(err => {
        //error handling and retry code omitted
        return Promise.reject(err);
    });
}

```
The `generateMauthAuthToken()` is just function that generates Basic auth literal usig a username and password from a configuration. You can use a pregenerated header value for tests if you have one.
And I call such snippet with parameters like this:
```js
        return invokeMauticAPI({
            method: 'POST',
            url: "https://server.example.com/api/emails/:templateId/contact/:contactId/send".replace(':templateId', templateId).replace(":contactId" , `${contactId}`),
            body: tokensBasket,
            allowRetry: true
        });

```
I think the most tricky part of this bug is that it happens sorta randomly. Sometimes I have to kick the flow the API used in for tons of retries, sometimes it works like charm.
Please ping me if you need more information, I will try reply as soon as I will be online again.

**Comment by konstardiy** [comment]
I still have this issue.
I reviewed source code a bit. I am not a PHP dev, so I am not sure I can fix this myself, but what I understood, is this function 
```php
/**
     * Sends the email to a specific lead.
     *
     * @param int $id     Email ID
     * @param int $leadId Lead ID
     *
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     */
    public function sendLeadAction($id, $leadId)
```
of `app\bundles\EmailBundle\Controller\Api\EmailApiController.php`
at lines like 145 and below.
```php
$result = $this->model->sendEmail(
                $entity,
                $leadFields,
                [
                    'source'            => ['api', 0],
                    'tokens'            => $cleanTokens,
                    'assetAttachments'  => $assetsIds,
                    'return_errors'     => true,
                ]
            );

            if (is_bool($result)) {
                $response['success'] = $result;
            } else {
                $response['failed'] = $result;
            }
```
The call of `$this->model->sendEmail` returns _false_. Not an exception thrown or Response instance returned, but plain `false` returned.
Can someone track down why his can happen?
I have these candidates at hand:
a) line 1328 at EmailModel.php
```php
if (!$email->getId()) {
            return false;
        }
```
b) at 1510 and belo, same file
```php
$success = empty($failedContacts);
        if (!$success && $returnErrorMessages) {
            return $singleEmail ? $errorMessages[$singleEmail] : $errorMessages;
        }

        return $singleEmail ? $success : $failedContacts;
```
even if `$returnErrorMessages` set to true by caller (EmailApiController), and even if `singleEmail` is non-falsy value - and `$errorMessages[$singleEmail]` returns `false`.
 

Common context for this is that a lead/contact has been added and a email sent to it as soon as contact id has been obtained from API. But error repeats for some time even if  I apply retry with some delay to send call.

@npracht any thoughts?

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
