### ISSUE TITLE
"Contact me through email"  is not showing in unsubscribe page 

### ISSUE THREAD

**Issue by Bibhudatta-Sahoo-ASMB** [mautic/mautic#7902]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
In unsubscribe page "Contact me through email" check box is not showing even if the "Show contact preference settings" check box is set to on. It is showing if "Show contact frequency preferences"
 option is on in Email configuration.

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.2
| Browser | firefox

### Steps to reproduce
1. Go to configuration -> Email Setting -> Unsubscribe Setting
2. Then only check "Show contact preference settings" & "Show contact segment preferences" to one
![image](https://user-images.githubusercontent.com/14075239/66059614-9610e980-e53c-11e9-9f17-adfa480fd657.png)

3. Create a test segment and "New Segment Email" channel with the test segment.
4.No create a contact with your email and add that contact to your test segment.
5.Now send a message to a contact from email channel and open the email and click the unsubscribe link.
6.Then you will see there will be no "Contact me through email" check box in that page ( chek this http://prntscr.com/pd8yrf).
 
### Log errors
No Error logs

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
@johbuch you've been working hard on it, maybe you can help @Bibhudatta-Sahoo-ASMB ?

**Comment by johbuch** [comment]
@Bibhudatta-Sahoo-ASMB can you try to: 
create your own preference center in the landing page.
add the bloc segment list for example but also the channel frequency bloc.
assign your PC to your email
shoot your email and click on the unsubscribe link
check if "contact me through email" appears.

If yes, that means there is maybe a bug with the default preference center

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Yes @johbuch , If I addd frequency block then "contact me through email" is appears.

But if I didn't add the frequency block then it will not appear.

**Comment by johbuch** [comment]
@Bibhudatta-Sahoo-ASMB so that means it works with a customized preference center but not with the default preference center right ?

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Yes

**Comment by johbuch** [comment]
all right so it should help developers.
The bug occurs only with the default pref center

**Comment by npracht** [comment]
@Bibhudatta-Sahoo-ASMB what is the default theme used in your instance (you can see that in the configuration).

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
@npracht The default theme is "Mauve" 
Check this http://prntscr.com/phdgc8

**Comment by npracht** [comment]
@johbuch is the mauve theme correctly coded to support the preference center?

N.

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
@npracht any update ?

**Comment by johbuch** [comment]
@Bibhudatta-Sahoo-ASMB I confirm that the issue only occurs if you use the default preferences center. 
It works properly if you create a custom PC and assign it within an email

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Thanks @johbuch I got the thing. It is working in customized preference center and to create customized preference center I have followed [https://mautic.com/help/manage-subscriptions/](https://mautic.com/help/manage-subscriptions/)   this doc.
