### ISSUE TITLE
Double Optin: How to solve this problem?

### ISSUE THREAD

**Issue by Naturalkids** [mautic/mautic#7903]
Hello Community,
I hit a huge problem and I hope, that you can clarify this for me:

If a lead wants to get a freebie from me, they fill out the form and land on the "one klick until I can send you the freebie-page".  _Mautic does not check, if the Lead is still confirmed or not._ 
**The actual process:**

1. Lead visits Freebie-Landingpage
2. Lead fills out the form and submits
3. Lead visits the "One Klick Page
4. Lead gets the Email with confirmation link
5. Lead clicks this confirmationlink
6. Lead ist confirmed and moves in the Segment, where the freebie is delivered.

**Fast forward 3 months later
Lead recognizes, that he can't find the downloaded freebie anymore:**

7. Lead visits Freebie-Landingpage
8. Lead fills out the form and submits
9. Lead visits the One Klick Page AGAIN (this shouldn't happen)
10. Lead doesn't get the confirmation email (although he was suggested to get one because he saw the one klick page...)
11. Lead does not move to the Campaign again (Problem is a Bug und is still not fixed)...
12. Lead does not get that freebie again

I am glad if someone can tell me the workaround for the one-klick-page-problem.
Thank you 
PS: English is not my native language, so if you have any questions, feel free to ask!

**Comment by MxyzptlkFishStix** [comment]
Tag them.

If they enter again, tagged, setup a separate option that sends an email immediately containing the asset download.

**Comment by RCheesley** [comment]
As above, and ensure they can (or can't - depending on the behaviour you want) re-enter the campaign.  As this is a support request rather than a bug I'm closing it, as they should be posted on the forums at https://forum.mautic.org
