### ISSUE TITLE
Choosing form field value in campaign builder results in invalid value warning

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#7905]
###  Bug Description
When creating a campaign form with dropdown options, and using the value as a condition in campaign builder, there is an invalid value error being thrown on first save, which disappears when updating.

See screencast here: https://youtu.be/jYouF9j-MEQ

| Q   | A
| --- | ---
| Mautic version | v2.16.0-dev
| PHP version | 7.2.21
| Browser | Chrome

### Steps to reproduce
1. Create a campaign form with a dropdown field including more than one item
2. Create a campaign, and use the campaign form as the trigger with a condition of 'form field value'
3. Choose the appropriate form, field and value, and hit save - you should see the error
4. Press update, and it saves without any error
 
### Log errors
There are no error logs.

**Comment by npracht** [comment]
@RCheesley is that the solution to your issue ? https://github.com/mautic/mautic/pull/7824

**Comment by npracht** [comment]
@RCheesley up :)

**Comment by RCheesley** [comment]
Just tested in 3.0.2 and it's still happening!

**Comment by barryharmsen** [comment]
This issue still occurs in 3.1.2
