### ISSUE TITLE
Mautic update failed from 2.15.0 to 2.15.2 on Shared C-Panel hosting

### ISSUE THREAD

**Issue by AkkuFresh** [mautic/mautic#7907]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Mautic update failed from v.2.15.0 to v.2.15.2 on Shared C-Panel hosting servers. This issue has occurred in 3 out of 3 cases with different domains. It looks like the problem related to the C-Panel. There was no any issue on C-Panel earlier, but now there is. All other Mautic Ajax function works well as save Contact, Emails etc, but the update Ajax some how went wrong.

| Q   | A
| --- | ---
| Mautic version | 2.15.0 -> 2.15.2
| PHP version | 7.2.22
| C-Panel | 82.0.16
| Apache | 2.4.41
| MySQL | 5.7.27
| C-panel nativ PHP | 5.6.40
| Browser | Google Chrome 77.0.3865.90 

### Steps to reproduce
1. Save files and database on the shared C-Panel hosting server
2. Start the Mautic update process from the browser.
3. On the upgrade.php?task=moveBundles&updateState=W10 the process will hang on (as it shown on the screen-shoot)

The full command that will hang up: https://{--url-to-mautic--}/upgrade/upgrade.php?task=moveBundles&updateState=W10=&_=1569945950242&mauticUserLastActive=46&mauticLastNotificationId=
 
### Log errors
Server PHP log will be empty.
Mautic PHP log will be empty.
Error on the Google Chrome Javascript console in JSon format:
```
{"errors":[{"message":"Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!","code":404,"type":null}],"error":{"message":"Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)","code":404}}
```
Apache log:
```
[Tue Oct 01 18:06:49.671040 2019] [authz_core:error] [pid 1598814:tid 47276737201920] [client ---IP--:1220] AH01630: client denied by server configuration: /home/--path-to-mautic--/upgrade/upgrade.php, referer: https://{--url-to-mautic--}/s/update
```

![update_2019-10-01_1808](https://user-images.githubusercontent.com/6353141/65983147-2f78c680-e47d-11e9-96bd-ba55cba3f513.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

---

Applying the suggestion from John Linhart's blog the update can be finished:
[https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful](https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful)

But trying to update files manually there is an other issue: The uploaded files will give error 500 on the first run and one should repair the folder permission to 755 and files permission to 644 and ownership of files in the Mautic instance to make workable on the C-Panel

**Comment by Woeler** [comment]
The upgrade issue is fixed in 2.15.3-beta, and will be rolled out to 2.15.3 stable soon.

**Comment by AkkuFresh** [comment]
@Woeler Thank you for the information.

**Comment by AkkuFresh** [comment]
I can confirm, the update process works well on 2.15.3 from 2.15.2

**Comment by Woeler** [comment]
Thanks for reporting @AkkuFresh !
