### ISSUE TITLE
Delay between mail

### ISSUE THREAD

**Issue by timtaylorrr** [mautic/mautic#7908]
Hi

I would like to send my emails with a delay of 30 sec between each mail. 

Mail 1
delay 30 sec
Mail 2
delay 30 sec
....

Is this possible with mautic?

Thank you.

**Comment by npracht** [comment]
Hi @timtaylorrr i invite you to join mautic forum or mautic chat on Slack for that type of question. We are here listing the issues we may face using mautic.

thanks a lot for your contributions !
