### ISSUE TITLE
404 error when i click on the link

### ISSUE THREAD

**Issue by Coeur-Digital** [mautic/mautic#7909]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this: Bug

| Q  | A
| ---| ---
| Bug report? | Y
| Feature request? |N 
| Enhancement? | N

## Description:

Everything work email send work fine only this case 

## If a bug:

| Q   | A
| --- | ---
| Mautic version | latest
| PHP version | 7.1
| Ubuntu 18.04 & Apache2
| Mailgun
### Steps to reproduce:
1. Fresh Install i follow the tutorial there 
https://www.linuxbabe.com/ubuntu/install-mautic-self-hosted-email-marketing-platform-ubuntu-18-04
except i use composer for build Mautic
2. I create an email from Channels --> email (i use the basic template) 
3. Click on the link 

404 Not FOUND

### Log errors: 
[2019-10-02 07:48:19] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM ma_lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ma_lead_fields' doesn't exist [] []

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._ 

Nothing on the apache Log

**Comment by kifurax-react** [comment]
I fix It some trouble with cronjob and my php.ini
Thanks

**Comment by kifurax-react** [comment]
It's Work sometime but now i still got some 404 not found. 
Can you tell me how I can investigate more deeply ?
Logs doesn't show too much information

**Comment by RCheesley** [comment]
Please ask in the forums for support at https://forum.mautic.org - you probably need to follow these steps: https://www.mautic.org/docs/en/tips/update-failed.html but this doesn't seem like it's a Mautic bug.
