### ISSUE TITLE
Assets Filter not showing all available assets

### ISSUE THREAD

**Issue by wucherpfennig** [mautic/mautic#7910]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
As requested by @npracht in PR #6182 

After creating a new segment an assets filter was added. the filter does not show all assets available. autocompletion does not load the other assets either.

Currently we are using 150+ assets in our system.

| Q   | A
| --- | ---
| Mautic version | v2.15.3-beta
| PHP version | 7.1.32
| Browser | Chrome latest

### Steps to reproduce
1. Get latest Beta
2. Create a segment
3. Add Filter of Type "Assets"
 
### Log errors

NONE.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by maxlawton** [comment]
As @npracht suggested in #6182, this is likely the result of pagination.

The **ListType** constructor makes a [call](https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Form/Type/ListType.php#L110) to [AssetModel#getLookupResults](https://github.com/mautic/mautic/blob/staging/app/bundles/AssetBundle/Model/AssetModel.php#L464) without a `$limit` argument, thereby defaulting to 10 max results in [AssetRepository#getAssetList](https://github.com/mautic/mautic/blob/staging/app/bundles/AssetBundle/Entity/AssetRepository.php#L67-L70).

To get all assets, that call should have an empty (or larger?) arg for `$limit`.

**Comment by npracht** [comment]
@maxlawton thanks for that! Do you think you could offer a fix (PR) for it?

**Comment by npracht** [comment]
@wucherpfennig please test #7911

**Comment by wucherpfennig** [comment]
I cant confirm that the fix from @maxlawton  #7911 works as expected

**Comment by wucherpfennig** [comment]
This issue can be closed since working commit merged
