### ISSUE TITLE
Unable to  save or edit standalone forms with Redirect URL option

### ISSUE THREAD

**Issue by raymondkent** [mautic/mautic#7913]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

When creating a new or editing an exisitng Mautic form, the form doesn't save.

Issue occurs when creating a new form with "Redirect URL" , or editing an existing (working) form with "Redirect URL" option selected.

| Q   | A
| --- | ---
| Mautic version |  2.14.1
| PHP version | PHP Version 7.0.25
| Browser | Chrome

### Steps to reproduce
1.  After upgrading to 2.14.1
2.  Create a new standalone form
incude just one field for now. i.e email field.

Then save the form.

3 Re open the saved form and change option to Redirect URL, enter i the url, then try to save teh form.

OPTION.
Open exisiting working form to edit.
Change option to Redirect URL
Try saving the form.

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Please update to 2.15.3, your version is **extremely** out of date. 

Re-test once updated (preferred to do this at command line, after updating) and if it's still an issue, then re-open this bug report.
