### ISSUE TITLE
BUG | Textarea showing in just one line when textarea field token included in e-mails.

### ISSUE THREAD

**Issue by galgamo** [mautic/mautic#7916]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:
Line breaks in custom textarea fields are not correctly parsed when used in e-mails or in campaings with a send-email action. The text is shown in one single line.

Looking at e-mail code, the context/plain-text version is correctly but context/html is not. The &lt;br /&gt; or &lt;p&gt; tag is missing

I found another similar bug reported to be solved in 2.12, but it is happening in 2.15.1 and 2.15.2

I couldn't find a solution on my own because of my little knowledge of php but I'm willing to test code and share the results with the community.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.15.1 and 2.15.2
| PHP version | 7.2.22

### Steps to reproduce:
1. Create a custom field with the type TextArea. I have put it in the personal area.
2. Create new contact.
3. Fill at least two lines in the textarea field.
4. Send an email including the token. It can be a segment email, campaing email or just sending the email from the Contact tab.
5. Token will be shown in just one single line.
 
### Log errors: 

I couldn't find anything important in the logs, but I'm willing to do tests and post the results

**Comment by RCheesley** [comment]
@galgamo have you updated to 2.15.3? Does this problem persist?

**Comment by RCheesley** [comment]
I just tested this on 2.15.3 and I am not able to replicate. 

See below, full token included when sending an email direct to the lead

![screenshot-127 0 0 1_8025-2019 11 05-20_08_44](https://user-images.githubusercontent.com/2930593/68242267-1fb64a00-0008-11ea-946a-278b4f22f4cc.png)

Closing due to being unable to replicate, feel free to request re-open if you're able to give more details on testing.
