### ISSUE TITLE
Inserting Asset Token in a email in code mode not working

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#7917]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you create an email in code mode ans want to insert an asset link token in it via the control + space shortcut it doesn't work. (this shortcut is used to display a list of token that you can insert in your code)
![image](https://user-images.githubusercontent.com/49391402/66125873-57386d80-e5e8-11e9-9335-1030e93b6929.png)

The token is well inserted but when you apply the change in the email, the link vanish.
I correct manually the token with double quote instead of single ones and it works.

The token before clicking Apply
![image](https://user-images.githubusercontent.com/49391402/66125515-6f5bbd00-e5e7-11e9-8c0b-4f64d7160776.png)
 The token after clicking Apply 
![image](https://user-images.githubusercontent.com/49391402/66125657-dd07e900-e5e7-11e9-8cc0-2c107a5b4936.png)

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1. Create an asset 
2. Create an email in code mode
3. Edit the email to insert the asset link via control + space shortcut
4. Use the Apply button in the editor to validate change
5. See that the link vanish and the token doesn't work.

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/7921

**Comment by npracht** [comment]
Fixed in 2.16.0, release coming soon.
