### ISSUE TITLE
Mautic embed formdata in HTML emails without escaping 

### ISSUE THREAD

**Issue by fujimotos** [mautic/mautic#7918]
## Bug Description

My company uses Mautic to provide a contact form to our customers. We use
"Form Actions" to email form data to the customer relation division.

Because of the technical nature of our customers, they sometimes include
HTML tags in their inquiry. Here is an example of such messages:

    We tried <style>...</style> but it did not work. What is the correct
    way to set the style on foo?

The problem is that Mautic does not provide a way to escape HTML tags in
form values, so the HTML tags in the form data inevitably gets embedded in
the HTML message **as is**.

This behaviour is very problematic since it means tags in post data are
interpreted valid HTML tags, and it often broke messages very badly.

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | any 
| Browser | any

### Steps to reproduce

1. Set up a form on Mautic and set its action to "send email"
2. Embed formdata to messages like `{leadfield=message}` 
3. Submit form data including HTML tags

### Solution

A possible solution is to add a new message modifier `html` so that we can
safely include form data containing HTML tags (e.g. `{leadfield=message|html}`)

### Log errors

None

**Comment by RCheesley** [comment]
I was able to replicate this, the tags were stripped out of the email.

I wonder if this is perhaps intended by design to prevent malicious code/styling?

![screenshot-127 0 0 1_8025-2019 11 05-20_13_22](https://user-images.githubusercontent.com/2930593/68242657-d87c8900-0008-11ea-9a7c-4125f0c308af.png)

**Comment by fujimotos** [comment]
@RCheesley If you select the text and click "View the source" on your browser,
you'll see the tags are actually exist there.

They are just invisible due to being interpreted as "real" HTML tags.

**Comment by RCheesley** [comment]
Gotcha, hadn't thought of that! So you're suggesting there should be some way to denote that it is code that should not be executed? As a customer completing a form on a website that would be a bit clunky, no? How would you propose it should be managed?

**Comment by fujimotos** [comment]
> How would you propose it should be managed?

Add a new data filter `html` that escapes all the occurrences of `<` and `>`
into  `&lt;` and `&gt;`. With this, we can safely inject user data into a HTML
email via:

```
{leadfield=message|html}
```

In general, I think it is not a good idea for a form generator to allow 
visitors to inject arbitrary HTML tags into messages. It will break the
message, and may have a security implication.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by piroor** [comment]
This problem still happen on Mautic 3.0.2. Embedded tags in a posted message are rendered in delivered mail as regular HTML tags instead of safe source text.
