### ISSUE TITLE
Error 500 when I click build on "Focus Item"

### ISSUE THREAD

**Issue by Lucasfnd** [mautic/mautic#7920]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. When I click build on Focus Item this error appears on screen, my Mautic is at version 2.13
2. In the logs appears the same error.
![Screen Shot 2018-07-26 at 11 33 43 AM](https://user-images.githubusercontent.com/19308594/66156340-dd0fe500-e5f7-11e9-84cb-de29323731d7.png)

Please help me!! hahahahahaha

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by heathdutton** [comment]
Any errors in your logs?

**Comment by Lucasfnd** [comment]
the same error

**Comment by RCheesley** [comment]
Please check on the latest version of Mautic, 2.15.3 after backing up files/database (ideally upgrade at command line, if you're stuck with that follow these instructions - https://www.mautic.org/docs/en/tips/update-failed.html), and provide error logs by going to System Info > Logs.

**Comment by Lucasfnd** [comment]
Alright, I'll try to upgrade and see if the error stops, anything opens another issue, thanks for the help
