### ISSUE TITLE
Focus feature: grab website snapshot not working

### ISSUE THREAD

**Issue by chrispy001** [mautic/mautic#7925]
## Bug Description
This bug was previously reported (https://github.com/mautic/mautic/issues/2036) and has been closed off, but it is still not working and others have found the same on the previous page.
I tried to create a popup with a focus item. I entered my website url for Mautic to grab a screenshot of my website. The preview is not getting displayed.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2
| Browser | Firefox

### Steps to reproduce
1. Go to Channels > Focus
2. Click New
3. Go to Builder
4. Enter URL, Click Fetch

 
### Log errors
No errors, it just asks you to enter the website URL again

**Comment by RCheesley** [comment]
I am able to reproduce this on 2.15.3 on my localhost when I am trying to render sites using SSL.

If I try with http://neverssl.com it works perfectly.

Have you tried non-SSL sites?

I wonder if it's an issue related to https to non-https connections or something along those lines?

**Comment by r-martins** [comment]
I'm able to reproduce with Mautic 2.15.3 + PHP 7.2.24 in the production server.
Both https or fails. Nothing logged in php or app/log folder.

**Comment by jrmarins** [comment]
Same problem here!

Mautic 2.15.3 + PHP 7.2.24

**Comment by RCheesley** [comment]
Closing as a duplicate of #7179 - please move the conversation to that issue.
