### ISSUE TITLE
How to define 3 level sub menus in the config file ?

### ISSUE THREAD

**Issue by lokeshjoshicis** [mautic/mautic#7927]
## Bug Description
I am adding children menus under the children menu but it's showing/working properly.
In the config file, we can add children menu for any root menu. Now I'm trying to add children menus of any children menu but its not working.

| Q   | A
| --- | ---
| Mautic version | v2.14.2 
| PHP version | 7.2
| Browser | Firefox

### Steps to reproduce
1. Open config file of any bundle
2. Try to add sub menus in 3 level like :
-Root Menu
--Children Menus of Root Menu
---Children Menus of Children Menu

### Log errors
NO ERROR

**Comment by lokeshjoshicis** [comment]
@alanhartless Can you please check and let me know for the same. Thanks

**Comment by alanhartless** [comment]
Hi @lokeshjoshicis. I don't believe Mautic's UI currently supports 3 levels deep.

**Comment by lokeshjoshicis** [comment]
@alanhartless, Thanks for your update.
