### ISSUE TITLE
email preview URL is not right

### ISSUE THREAD

**Issue by jcea** [mautic/mautic#7932]
Mautic 2.15.2.

I create a new email. The preview URL is https://XXXX/email/preview/4 . That URL gives a "404 Not found" error.

If I modify the URL manually to https://XXXX/index.php/email/preview/4 , it works.

My Apache configuration is tiny and simple:

```
RewriteEngine on
RewriteRule ^/$   /s/login   [redirect,last]
RewriteRule ^/s/  fcgi://127.0.0.1:9000/home/apache/datos/index.php   [proxy,last]
RewriteRule ^/index.php  fcgi://127.0.0.1:9000/home/apache/datos/index.php   [proxy,last]  # Para la instalación inicial

<Location />
  Require all granted
</Location>
```

Is my Apache config right? Is this a bug in Mautic 2.15.2?

Thanks.

**Comment by RCheesley** [comment]
Seems like you may have a problem with your htaccess file if you've got index.php in your URL?  

As a starter, maybe take a look at the htaccess [here](https://github.com/mautic/mautic/blob/staging/.htaccess) and compare it with the version that you have on your instance (and please, update to 2.15.3 after backing up your files and folders, ideally at command line).
