### ISSUE TITLE
Update date of e-mail while processing the queue

### ISSUE THREAD

**Issue by icetique** [mautic/mautic#7936]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.15.2
| PHP version | PHP Version 7.2.19-0ubuntu0.18.04.2
| Browser | Irrelevant

### Steps to reproduce
1. Create segment with test e-mail
2. Set-up Mautic to handle e-mails in queue (not instant delivery)
3. Set-up low amount of e-mails processed in one queue-process cron task
4. Set-up cron task to send queue
 
### Description
We like to warm up our IPs very slowly. We have mautic instance running on our own server. In e-mail settings we selected Queue in “How should e-mail be handled?” and we often manipulate with “Message limit for queue processing” field to reach the expected time-frame while sending e-mails. Of course, we also have proper cronjobs set up.

The problem we are facing is that when we set-up the queue to send e-mails with-in, for example, 2 days - the last e-mails appear in users inboxes with a date of creating e-mail in the queue instead of the date of processing the e-mail queue. So, even when e-mail is delivered in present moment it appears in following way:
[sample read e-mail title]
[sample read e-mail title]
[sample read e-mail title]
[our unread e-mail title]
[sample read e-mail title]
[sample read e-mail title]
[sample read e-mail title]
[sample read e-mail title]

I am not sure where to look for an answer. Is there any option to send e-mails with the date of processing the queue instead of the date of pushing the e-mail into queue? Please note we use localhost postfix to send e-mails and we are warming up dedicated IP. I searched for an answer on GitHub, but I am unsure if this is Bug, Support issue or Feature request so I would be appreciated of pointing me the steps to handle this as soon as possible.

We are developers ourselves, so if you can point us what we need to modify and where to handle this case, we can do that too and we can submit a patch later into your GitHub, though we do not have experience how Mautic is internally built yet.

Also, please note we are sending segment e-mails.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there,

This would probably best sit on the forums at https://forum.mautic.org as a discussion rather than a bug report. I believe, but am not sure, that this is due to the way you're trying to process the queue.

If it turns out to be a bug, feel free to re-open this issue!
