### ISSUE TITLE
Unable to Update - Endless Loop / Freeze - "Moving Package Contents - In Progress"

### ISSUE THREAD

**Issue by Qubestar** [mautic/mautic#7937]
Hey guys,

When I want to update the Mautic to version 2.15.3, it's freezing on the last stage with an infinite loop. "Moving Package Contents - In Progress".

| Q   | A
| --- | ---
| Mautic version | v2.15.1
| PHP version | 7.1.30
| Browser | Chrome

### Steps to reproduce
1. Click Update Now the Mautic 
 
### Log errors
none

**Comment by ereznet** [comment]
Error found:

PHP Fatal error:  Class 'ComposerAutoloaderInitc5648d1079f8b913015b21b8fe452b2d' not found in /home/USERNAME/domains/xxxxx.com/public_html/vendor/autoload.php on line 7

**Comment by Qubestar** [comment]
Thank you for the error. How can I fix it?

**Comment by ereznet** [comment]
ErezNet

	
		#outlook a						{ padding:0; }
		body							{ direction: rtl; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0; background: #fff; font-family: Arial; }

		.ExternalClass					{ width: 100%; }
		.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
		img								{ outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }
		a img							{ border: none; }
		.image_fix						{ display: block; }
		p								{ margin: 1em 0; }
		h1, h2, h3, h4, h5, h6			{ color: black !important; }
		h1 a, h2 a, h3 a, h4 a, h5 a, h6 a { color: blue !important; }
		h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active { color: red !important; }
		h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited { color: purple !important; }
		table							{ border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; margin: 0; padding: 0; line-height: 100% !important; text-align: center; }
		table td						{ border-collapse: collapse; }
	



	
		
			 
		
	

	
		
			
				
					 
				
				
					
						לקוח יקר,
						החל מתאריך 23.11.17, במייל זה (support@ereznet.co.il) לא תינתן/תסופק תמיכה טכנית.
						אנו שמחים להציג בפניכם את מערכת ה-HelpDesk החדשה שלנו בכתובת:https://www.helpdesk.ereznet.co.il
						
							כל לקוחות ארזנט מתבקשים לבצע הרשמה למערכת בכתובת: https://www.helpdesk.ereznet.co.il/registerההרשמה בחינם, אך חשוב לזכור שעלייכם לבצע הרשמה בעזרת הכתובת דואר שעמה ביצעתם את הזמנתכם!
						
						במערכת HelpDesk ניתן למצוא מגוון רחב של פעולות:
						
							להקים/לפתוח קריאה לשירות במגוון קטגוריות.
							הקמת כרטיס מתבצעת מתוך אתרנו, כך שבמידה ותיבת הדואר שלכם לא פעילה עדיין תוכלו לשלוח פניות.
							צפייה בהסטוריית הכרטיסים שלי.
							מעקב לכרטיס, ושינוי סטטוס.
							אפשרות להוספת מידע פנימי לכרטיס: כגון סיסמאות רגישות וכתובת IP והכל בסביבה מאובטחת (SSL).
							אפשרות לעדכון כרטיס ישירות מתוך תיבת הדואר שלכם, בעזרת שליחת מייל חוזר.
							בנוסף למערכת הכרטיסים, תמצאו מאגר מידע אשר נעדכן עבור הודעות חשובות בחברתנו.
							ועוד מגוון אפשרויות אשר יפיקו תמיכה ושליטה טובה יותר לקהל לקוחותינו.
						
						נשמח לעמוד לשירותכם :)
					
				
				
					 
				
				
					
						בברכה,צוות ארזנט - פתרונות אינטרנטמחלקת תמיכה טכניתטלפון משרד: 077-2148004 | פקס: 077-2148005כתובת אתרינו: https://www.ErezNet.co.il

**Comment by Qubestar** [comment]
No idea what you mean. I'm not a coder.

**Comment by RCheesley** [comment]
Hi @Qubestar and sorry to hear you're having problems updating. Generally it's best to post on the forums at https://forum.mautic.org for support requests rather than Github, as this is for specific issues which are identified.  That being said, we're here now.

What Mautic version were you updating from?

Have you tried clearing the cache (removing the folder in app/cache/prod) to see if this resolves the issue?

Otherwise, please follow these steps and let us know the output at each step: https://www.mautic.org/docs/en/tips/update-failed.html

**Comment by Qubestar** [comment]
@RCheesley thank you for the link to forum - I wasn't aware.

I'm upgrading from v2.15.1.

I was clearing the browser cache but didn't play with folders, so I'll take a look at the materials you've pointed out.

**Comment by AkkuFresh** [comment]
Please check it: #7907

**Comment by Qubestar** [comment]
@AkkuFresh thank you for the link.

I'm not sure - is it stable already?

(I don't understand the code parts nor how to apply them and the https://johnlinhart.com.. link is being blocked by my Avast).

**Comment by AkkuFresh** [comment]
@Qubestar I manage about 10 different Mautic installation in different servers and I can say the 2.15.3 is enough good to use.
If the Avast is blocking the John Linhart blog, so, it is the time to change from Avast to iObit software :-) 
Perhaps you should update manually from the earlier versions. Try to turn off Avast and read the instructions from the John Linhart blog.

**Comment by RCheesley** [comment]
Or, just use the link to the documentation : https://www.mautic.org/docs/en/tips/update-failed.html :)
