### ISSUE TITLE
Translate {unsubscribe_text} - not translate

### ISSUE THREAD

**Issue by Rohaty** [mautic/mautic#7940]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.1.29
| Browser | Chrome

### Steps to reproduce
1. Mautic configuration -System defaults-Default language -Select German
2. Save&Close - Logout
3. Clean cache - Login
4. In directory mautic/htdocs/translations/de/EmailBundle  - was automatically generated file messages.ini. In this file is translate this: 
mautic.email.unsubscribe.text="<a href='%link%'>Abmelden</a> um von uns keine E-Mails mehr zu erhalten."
5. Create email1 and select Language - English -Save&Close
6.  Create email2 and select Language - German - Select email1 from "Is a translation of" -Save&Close
7. Open email1-select Translations-select email2(where is German language)-Preview URL-and {unsubscribe_text} shows in english language instead German language.

Why is English displayed instead of German?
 
### Log errors
Log erros is empty.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by AkkuFresh** [comment]
Hi @Rohaty this {unsubscribe_text} is in the field in the settings page and you can customize it freely. It is not an error.

**Comment by Rohaty** [comment]
Hi, yes, I can change it there, but when I have default language selected German and in Configuration-Email Settings-Unsubscribe Settings I translate the text into German language, then I see the translated text into German everywhere and no English. I always see the text in the language I translated it there. It's a error.

**Comment by Rohaty** [comment]
Hi,
here 

https://github.com/mautic/mautic/issues/1673 

also solved this problem. It was concluded that it would require a lot of changes and change the way it works now, and it was called a feature request.

How's it going?

**Comment by Rohaty** [comment]
Hello,
no one has a problem translating {unsubscribe_text}? Don't you send emails in different languages? No solution?

**Comment by RCheesley** [comment]
@Rohaty as mentioned in the closed issue you referenced, this would be a feature request. Please raise it here: https://forum.mautic.org/c/ideas (you can reference to this issue) to open the discussion. If there is enough interest, then maybe someone will pick it up and write a PR to implement this.
