### ISSUE TITLE
Automatically move SMS responses out of Segments? 

### ISSUE THREAD

**Issue by ackrug** [mautic/mautic#7941]
Is there a way to make it so that when someone responds to a text they are removed from that segment?

**Comment by kuzmany** [comment]
https://github.com/mautic/mautic/pull/7449

**Comment by ackrug** [comment]
I'm not sure this actually solves my issue. 
I want inbound text messages to trigger a segment change

**Comment by RCheesley** [comment]
The PR above enables a reply to an SMS sent via Mautic to change segments, so I am closing this issue.
