### ISSUE TITLE
Contact ID is missing from form result export

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#7942]
## Bug Description
When exporting form results, the contact ID is missing - only submission ID. This is problematic, if you have a form sent to existing users where you don't capture the email address.

(Would be even better, if I could export the email address with the results, bound to the contact ID).

further discussed already here: [Mautic Forum](https://forum.mautic.org/t/is-there-a-reason-that-contact-id-will-not-be-exported-from-form-submits/11248)

| Q   | A
| --- | ---
| Mautic version |  2.15.3 and earlier
| PHP version |  7.x
| Browser |  any

### Steps to reproduce
1. setup a form without email address
2. send the form to a segment of contacts
3. export the results is meaningless, as you can't link them back to contacts
 
### Log errors
none

**Comment by kuzmany** [comment]
https://github.com/mautic/mautic/pull/7872

**Comment by RCheesley** [comment]
Closing this issue as the PR mentioned addresses the bug.
