### ISSUE TITLE
Mautic started redirecting to non-existing HTTPS after cache clear

### ISSUE THREAD

**Issue by TPapajCin** [mautic/mautic#7943]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
My Mautic installation started redirecting to HTTPS for unknown reason. I am running Mautic behind TLS terminator so I want it to work in HTTP and let TLS terminator handle secure connections. This situation made Mautic unavailable because I was getting endless loop errors. My Mautic is not configured for HTTPS.
This problem is related to manually deleting the cache because it started happening shortly after this.

| Q   | A
| --- | ---
| Mautic version |  2.15.2
| PHP version | 7.0.33
| Browser | FireFox 69.0.2

### Steps to reproduce
1. Create a TLS terminator in front of Mautic machine.
2. Install Mautic using TLS terminator.
3. Check if Mautic is running.
4. Delete cache by running rm command.
5. Trying to open Mautic using TLS terminator now returns endless loop. Also, trying to open Mautic directly via its IP redirects to HTTPS port 443 and of course gives connection refused because there's nothing listening on that port.

There is a way to "fix" it in case of emergency:
### Bad workaround
1. Stop Mautic.
2. Start installing different Mautic installation, finishing installation is not needed.
3. Copy cache files from new installation to old Mautic.
4. Old Mautic will work again.
 
### Log errors
Nginx and Mautic do not return any logs of this situation.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Does this persist in an incognito window? I wonder if it's another case of a browser-cached redirect going wonky? Someone else had a similar problem recently.
