### ISSUE TITLE
Contact > Send Email receives 403 response

### ISSUE THREAD

**Issue by RanjithNKtrr** [mautic/mautic#7945]
Mautic version : 2.15.3 
PHP version : 7.0.0.
Linux Server hosting : Direct Admin panel

I have configured the smtp service in email configuration tab and test connection succeeded.

Then i tried to send email through clicking the contacts and send email but i received 403 response 
from this post request /s/contacts/email/3163?mauticUserLastActive=1&mauticLastNotificationId= 

Can anyone help me in this?

**Comment by RCheesley** [comment]
Please can you share the full error logs if this is still a problem for you @RanjithNKtrr ?
