### ISSUE TITLE
I can't save and close configurations

### ISSUE THREAD

**Issue by muhammadshoaibtasleem** [mautic/mautic#7948]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.1
| Browser | Chrome

### Steps to reproduce
1. I installed Mautic and also updated it.
2. when I go to configurations section and, change something and click save and close button it keeps saying "Please Wait". I have tried everything, but nothing worked. 
 
### Log errors
Logs are empty https://prnt.sc/pivolv

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi @muhammadshoaibtasleem does this happen in an incognito window?

Have you tried to clear your cache (in Mautic, by clearing app/cache/prod and in your browser)?

Are you seeing anything in your Chrome console when you hit save (press f12 to open developer tools)?

**Comment by Avocation** [comment]
Same problem. Go to Configuration, click 'Save Changes' or 'Apply' and the 'Please Wait' screen overlay appears and it just sits there.

Mautic 2.15.3
PHP 7.1.14
Browser Chrome & Safari

Looking in Dev tools on Safari and Chrome I see error #406 Failed to load resources (Safari).

Further in Chrome developer tools console view, I see the message - "A cookie associated with a cross-site resource at http://gravatar.com/ was set without the `SameSite` attribute". A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`.

CORS is set to YES and the subsite is named in the valid domains.

The User/Authentication fields for Email, Username, Firstname, Lastname are not set (as can't save entries to those fields).

All help gratefully received.

**Comment by Avocation** [comment]
Output from the browser dev tools console where it gets error #406: 
![Error 406](https://user-images.githubusercontent.com/13272582/68161802-8ecf6800-ff4e-11e9-9c29-67593ad499bb.jpg)

**Comment by muhammadshoaibtasleem** [comment]
hi, contact your host provider. this issue was solved when they whitelisted
my ip. it takes just few minutes

**Comment by Avocation** [comment]
IP address added to whitelist in Wordfence - no improvement, still #406 error response.

**Comment by hokandil** [comment]
Same problem. Go to Configuration, click 'Save & CLose' or 'Apply' and the 'Please Wait' screen overlay appears and it just sits there.

Mautic 2.15.3
PHP 7.1.14
Browser Chrome & IE

**Comment by hokandil** [comment]
> Same problem. Go to Configuration, click 'Save & CLose' or 'Apply' and the 'Please Wait' screen overlay appears and it just sits there.
> 
> Mautic 2.15.3
> PHP 7.1.14
> Browser Chrome & IE

I found it was modsecurity issue , I called Hostgator and they whitwlisted the service and now it is working

**Comment by Avocation** [comment]
Hi @hokandil - thanks for the note and glad you fixed it.

Can I ask, when you say you called Hostgator and 'whitelisted the service', what exactly did you ask them to do? What is 'the service' you asked them to whitelist please?
They say they've whitelisted my IP and it should be working now but clearly not. So what was it that you told them to do that fixed the issue please?

Many thanks

**Comment by hokandil** [comment]
> Hi @hokandil - thanks for the note and glad you fixed it.
> 
> Can I ask, when you say you called Hostgator and 'whitelisted the service', what exactly did you ask them to do? What is 'the service' you asked them to whitelist please?
> They say they've whitelisted my IP and it should be working now but clearly not. So what was it that you told them to do that fixed the issue please?
> 
> Many thanks

Hi,
Hostgator uses modsecurity firewall switch is blocking some services in Mautic. 
I contacted Hostgator live support , I told them that modsecurity is blocking some services and need to whitelist it , he asked me for the domain name or the subdomain,  and then asked me to try to run the service ( so I tried to save the configuration) in order to identify that service . After few minutes of waiting he confirmed he whitelisted the service and give me the ID of that service for any future support ( it will be different for each installation)

**Comment by RCheesley** [comment]
Hi folks, closing this as it seems like it's an issue with the hosting environment/mod_security rather than Mautic itself. If you continue to have problems please raise them at https://forum.mautic.org where the community are best equipped to help with troubleshooting :)
