### ISSUE TITLE
Sendgrid Webhook still not working

### ISSUE THREAD

**Issue by masonkeefe93** [mautic/mautic#7951]
Bug Description
- Still trying to setup the Sendgrid webhook as per the bounce management instructions and I just can't get it to work.
- Have tested the integration on Sendgrid's side by sending test data to my Mautic endpoint, which I can see is being sent.
- When a real bounce or spam request comes through, the data is sent via Sendgrid but nothing happens in Mautic, no updated tags or Do Not Contact label is applied.

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2.22
| Browser | Firefox

### Steps to reproduce
1. Go to https://www.mautic.org/docs/en/emails/bounce_management.html
2. Follow instructions to set up webhook for Sendgrid.
3. Check the callback URL - 'success' message is displayed in the top left in plain text
4. Check contact to see if relevant info has been updated which it hasn't
 
### Log errors
No errors in the log, actually no errors or anything of any kind!
- My mautic instance is running on 'mautic.mydomain.com'
- My server is hosted with RunCloud, root directory filepath is '/home/runcloud/webapps/Mautic'

Any help would be hugely appreciated as I've spent hours trying to fix this and no one has even replied regarding the issue yet. This is listed in the official documentation as a supported webhook yet it doesn't work and use of this webhook would make the bounceback monitoring so much more accurate!

Thank you!

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by angelothegreat13** [comment]
I'm having an issue also in the event webhook
