### ISSUE TITLE
Gotowebinar Not Showing list of webinars in Mautic

### ISSUE THREAD

**Issue by rahulseo90** [mautic/mautic#7954]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
After Updating mautic to v2.15.3. Gotowebinar is not showing list of webinars. Please check the screenshots. 

<img width="960" alt="img2" src="https://user-images.githubusercontent.com/26229193/66836249-a2566700-ef7e-11e9-8d78-6a3b35a94eb7.png">
<img width="575" alt="img1" src="https://user-images.githubusercontent.com/26229193/66836250-a2eefd80-ef7e-11e9-9af8-ebc03cd4c2e3.png">

| Q   | A
| --- | ---
| Mautic version | v2.15.3 
| PHP version | PHP Version 7.0.33-0ubuntu0.16.04.6
| Browser | Chrome

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Do you have any errors in your error logs at all? Just I've seen sometimes people hit the API limit, especially if they are still in testing where it has quite a low limit.

**Comment by rahulseo90** [comment]
@RCheesley no there is no error in logs.

**Comment by miamicityman** [comment]
I'm having the same issues with 2.1.6 (php 7.2). 

GotoWebinar segments sync correctly, but lists won't populate in forms.

Where can you see API limits?

I'm pulling my hair out.

**Comment by miamicityman** [comment]
Answering my own 

> 
> 
> I'm having the same issues with 2.1.6 (php 7.2).
> 
> GotoWebinar segments sync correctly, but lists won't populate in forms.
> 
> Where can you see API limits?
> 
> I'm pulling my hair out.

Answering my own post for anyone else who has the problem:

[2020-03-31 13:36:03] mautic.ERROR: {"err":429,"category":"Rate limit quota","message":"The API call rate has been exceeded for the day."} [] []

**Comment by npracht** [comment]
You must contact you GoToWebinar support to ask them to increase your APi rate.

**Comment by miamicityman** [comment]
Thank you ... I will do so ... but I haven't been able to pull the first registrant from my mautic instance to GotoWebinar. Keep doing testing and testing, but nothing works.
