### ISSUE TITLE
Composer Install requires git on server 

### ISSUE THREAD

**Issue by flossels** [mautic/mautic#7955]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
`dist` section is missing in composer.lock file.

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2.19
| Browser | CLI

### Steps to reproduce
1. Clone ZIP file of version 2.15.3 on GitHub
2. Run `composer install` on shell without having git installed
 
### Log errors
```
[RuntimeException]                                                                                                       
  Failed to clone https://github.com/mautic/intl.git, git was not found, check that it is installed and in your PATH env.  
                                                                                                                           
  sh: 1: git: not found 

[RuntimeException]                                                                                                                           
  Failed to clone https://github.com/mautic/BazingaOAuthServerBundle.git, git was not found, check that it is installed and in your PATH env.  
                                                                                                                                               
  sh: 1: git: not found   
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by micaelomota** [comment]
Does someone know how to bypass this?

**Comment by RCheesley** [comment]
@micaelomota there is a fix proposed here: https://github.com/mautic/mautic/pull/7956 - perhaps you could test and report your findings on the PR?

**Comment by mabumusa1** [comment]
In order to install Mautic please choose the distributable files found on https://github.com/mautic/mautic/releases/tag/3.1.0. 

Downloading the zip file from github directly will give you the `staging` branch files which require git to install dependence
