### ISSUE TITLE
unique vs returning visitors dashboard - wrong query filter?

### ISSUE THREAD

**Issue by pety-dc** [mautic/mautic#7959]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I noticed that the returning visitors query filters to page_hit records that have lead_id as NULL

```
SELECT COUNT(t.id) AS count FROM page_hits t WHERE (lead_id IS NULL) AND (t.date_hit BETWEEN '2019-09-02 00:00:00' AND '2019-10-02 14:23:57')
```

The corresponding funcion looks like this:
```
public function getNewVsReturningPieChartData($dateFrom, $dateTo, $filters = [], $canViewOthers = true)
    {
        $chart              = new PieChart();
        $query              = new ChartQuery($this->em->getConnection(), $dateFrom, $dateTo);
        $allQ               = $query->getCountQuery('page_hits', 'id', 'date_hit', $filters);
        $filters['lead_id'] = [
            'expression' => 'isNull',
        ];
        $returnQ            = $query->getCountQuery('page_hits', 'id', 'date_hit', $filters);

        if (!$canViewOthers) {
            $this->limitQueryToCreator($allQ);
            $this->limitQueryToCreator($returnQ);
        }

        $all = $query->fetchCount($allQ);
//        $unique    = $query->fetchCount($uniqueQ);
        $returning = $query->fetchCount($returnQ);
        $unique    = $all - $returning;
        $chart->setDataset($this->translator->trans('mautic.page.unique'), $unique);
        $chart->setDataset($this->translator->trans('mautic.page.graph.pie.new.vs.returning.returning'), $returning);

        return $chart->render();
    }
```

- This function returns the number of pagehits with `lead_id=NULL` as **returning**, and all other pagehits as **unique** (probably should be new) 
- I wonder if new visits should be filteres as `lead_id=NULL` instead?
- I don't understand how this is related to unique? The dashboard item seem to have changed, but not the name

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.2.x
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to the lack of response.
