### ISSUE TITLE
unable to search by phone number in mautic 

### ISSUE THREAD

**Issue by ackrug** [mautic/mautic#7962]
Using the search I find the person's name externally and search that way. Is there a way to type a phone number into the search and it shows the contact it is associated with?

**Comment by RCheesley** [comment]
Hi there,

You can do this already by using phone:<number> in the search field.

See screenshot:

![screenshot-local mautictest-2019 10 25-10_22_33](https://user-images.githubusercontent.com/2930593/67559734-70c56480-f711-11e9-8379-ef52c9d0d055.png)

**Comment by wgicio** [comment]
I too am having a problem searching by phone numbers through n8n via the API
Just does not work most of the time
