### ISSUE TITLE
Endpoint `POST /contacts/new` update exists user instead of creating the new one

### ISSUE THREAD

**Issue by DevelopMan** [mautic/mautic#7963]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.0.33
| Browser | API

### Steps to reproduce
1. From browser or API create a new user with the only email: "test@user.email"
2. Save it
3. Execute `POST` request to endpoint `api/contacts/new` with json body
```
{
	"email": "te,st@user..email",
	"firstname": "test",
	"lastname": "user"
}

``` 
### Log errors
There is no any errors in the log, related to the issue.

### Description
The user email "test@user.email" and  "te,st@user..email" are different, but after these 3 steps we can see, that Mautic does not create a new user, but update the old one.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by si4dev** [comment]
Related to this I've experienced no email creation in case of another owner via the API while via the web interface it will create 2 lead records. So if you execute following two POST to accounts/new then the second payload will update the contact and change to owner 2:

```
{
	"email": "test@user.email",
	"firstname": "test",
	"lastname": "user",
	"owner": 1
}
```
and
```
{
	"email": "test@user.email",
	"firstname": "test",
	"lastname": "user",
	"owner": 2
}
```

**Comment by DevelopMan** [comment]
@si4dev But this is expected behavior. There are few fields to check if contact unique. One of them is email. So, if you use the same email - then the existing contact will be found and update.

**Comment by si4dev** [comment]
So the behaviour with the API is different from the browser login? When I login manually as owner 1 then I create test@user.email en re-login as owner 2 then I don't see test@user.email and can create a new contact test@user.email which also results in 2 records on the leads table.

For that reason I would expect the same behaviour with the API. As now you can 'hijack' others leads as it will make yourself the new owner.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by DevelopMan** [comment]
@RCheesley 
> Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
> Thanks!

Hi.
I can't check it. Because after the upgrade to 3.0.2 API does not work.
After generating authorization link and use it, I put my credentials and the just have a blank screen with URL /index.php/oauth/v2/authorize_login_check
So, the application don't redirect me to my website.

**Comment by DevelopMan** [comment]
> Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
> Thanks!

Confirmed that the issue continues in Mautic 3.0.2

**Comment by RCheesley** [comment]
Great - thanks for taking the time to check and report back!

**Comment by DevelopMan** [comment]
Should we wait for a fix here?
