### ISSUE TITLE
Manual emails, {signature} token generates incorrect signature

### ISSUE THREAD

**Issue by richmarks20** [mautic/mautic#7964]
The manual "Send a custom email to [contact email]" dialogue, as accessed via "Send Email" button in contact detail page does not respect the "Mailer is Owner" setting OR use the currently logged in user's signature when replacing the {signature} token. The signature used is always the "Default email signature" as defined at /s/config/edit

[Docs state](https://www.mautic.org/docs/en/emails/mailer_is_owner.html) "There is one exception where the contact owner's signature won't be used. When a user sends an email directly from a contact detail, the currently logged in user's signature will be used. It doesn't matter if the contact has another owner assigned or if it doesn't have an owner at all."

| Mautic version | 2.15.3
| PHP version | 7.2.10

**Comment by richmarks20** [comment]
@RCheesley this is still the case in 3.0.1 - does this issue need to be labelled for M3? Thanks!

**Comment by kuzmany** [comment]
Maybe this should work better for this https://github.com/mautic/mautic/pull/8373

**Comment by RCheesley** [comment]
@richmarks20 thanks for reporting back - can you take a look at the PR that @kuzmany mentioned and let us know if that would resolve the issue?

**Comment by mikemathewson** [comment]
Can anyone confirm this is fully fixed? The linked fix #8373 seems to focus the contact owner signature being applied, however I still experience the error when a logged-in user directly emails a contact. It seems to always use the system default signature and not the signature of the logged in user.

This is contrary to what the docs say which is: "When a user sends an email directly from a contact, the currently logged in user's signature will be used and not the lead owner." I am on version 3.1.0 and also have "Mailer is owner" set to off.
