### ISSUE TITLE
Mautic form submit remains hang up with the massage "Please wait"

### ISSUE THREAD

**Issue by garzettone** [mautic/mautic#7966]
Mautic form submit remains hang up wth the massage "Please wait" and doesn't do redirect.
The form is inside a Mautic landing page (using the {form=4} tag) and the Mautic landing page is opened directly fom the browser (is not embedded in other page).

Form data have stored in Mautic DB and all actions have performed, but it doesn't redirect or show message.

I read other people had same problem in the past but the solutions they found is not related to this.

PHP 7.2.21
Mautic v2.15.3

What I have already done
Cache clear, cache rebuilt, edit and save of the form, remove checkbox

**Comment by RCheesley** [comment]
Hi @garzettone do you have any errors in your Mautic logs at all?

**Comment by garzettone** [comment]
No I have not errors in Moutic logs neither php error logs.
You can see the form at thi address https://farmaciazadei.servizivisionova.it/iscrizione-alla-newsletter

**Comment by garzettone** [comment]
The problem arose after upgrading to version v2.15.3 from 2.15.2 and impacted all the Mautic installations I manage

**Comment by garzettone** [comment]
I have restored v.2.15.2 program files and kept v.2.15.3 DB  but the problem persists

**Comment by garzettone** [comment]
I created a new form from scratch with:
a single text field,
no actions, action after submit
action after successuful submit: "Show message"
message: 'ok'

Same problem

**Comment by garzettone** [comment]
I solved adding the following line to .htaccess inside the mautic folder:
**Header always unset X-Frame-Options**

Please note that I have no restriceted domain in CORS settings
