### ISSUE TITLE
Relative date segment filter (like -3 days/+3 days) doesn't take into account Mautic timezone setting

### ISSUE THREAD

**Issue by anton-vlasenko** [mautic/mautic#7967]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Relative date segment filter (like -x days/+5 days) doesn't take into account Mautic timezone setting. It assumes user is in the UTC timezone.
| Q   | A
| --- |
| Mautic version | 2.15.3
| PHP version | 7.2
| Browser | Safari / Any

### Steps to reproduce
1. Create a couple of identified leads, e.g. 6.
2. Go to the `leads` table and update `date_added` value for them as shown on the screenshot.
<img width="445" alt="Snímek obrazovky 2019-10-18 v 19 15 21" src="https://user-images.githubusercontent.com/43744263/67114613-a41d6600-f1dc-11e9-9b9c-9622d18bc77b.png">
3. Create a segment with relative `Date Added` filter to match the majority of leads. E.g. if today is 18th of October and you updated `date_added` as shown on the screenshot above, you should enter `-3 days` to match 15th of October.
<img width="804" alt="Snímek obrazovky 2019-10-18 v 19 54 55" src="https://user-images.githubusercontent.com/43744263/67116675-3889c780-f1e1-11e9-8eab-02e876d6c664.png">
4. Run `php app/console mautic:segments:update` command, go to the `lead_lists_leads` table to check what leads were added to your segment.

### Expected result:
Leads must be added to your segment depending on your local Mautic timezone setting.
E.g. if it set to `Europe/Paris, you should get leads between `2019-10-14 22:00:00` and `2019-10-15 21:59:59` because `2019-10-15 00:00:00` in Paris timezone equals `2019-10-14 22:00:00` UTC.
So the following leads IDS must be added to your segment: 2,3,4,5.

### Actual Result:
The filter doesn't take into account your Mautic timezone settings. You will get leads that have either `2019-10-14%` or `2019-10-15%` as their `date_added` value.
I mean either leads IDs 1, 2 or 3, 4, 5, 6. But most of the times your are not in the UTC timezone and this is not correct.
To fix it segment query filter should get leads using the range date filter, I mean: 
```sql
WHERE `date_added` >= `2019-10-14 22:00:00` AND `date_added` < `2019-10-15 21:59:59`.
``` 
Now it uses
```sql
date_added LIKE `2019-15-10%`
```
and this is nor correct or accurate. It should take into account the actual timezone setting.
Also, https://github.com/mautic/mautic/pull/7752 has to be merged first before fixing this issue . That other PR fixes bug in the DateTimeHelper::setDateTime method.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
@anton-vlasenko this PR doesn't fix it? https://github.com/mautic/mautic/pull/7122 ?

**Comment by kuzmany** [comment]
@anton-vlasenko this should fixed it 
https://github.com/mautic/mautic/pull/8044

Please test

**Comment by anton-vlasenko** [comment]
@kuzmany Thank you. I will review and test it soon.

**Comment by RCheesley** [comment]
Closing this old issue as the PR to fix it was merged already
