### ISSUE TITLE
Upgrade 2.15.3 failed : The file containing the list of deleted files was not found, could not process the deleted file list.

### ISSUE THREAD

**Issue by robov** [mautic/mautic#7969]
Upgrade 2.15.3 failed : The file containing the list of deleted files was not found, could not process the deleted file list.

**Comment by RCheesley** [comment]
Hello @robov can you share the errors you're seeing in the Mautic error logs?  It would also be helpful for you to share what version of Mautic you were upgrading from, and your PHP version.

Have you followed this process: https://www.mautic.org/docs/en/tips/update-failed.html step by step after the upgrade failed?

**Comment by npracht** [comment]
Let close it for lack of information.
