### ISSUE TITLE
500 ERROR on clicking configuration option from settings

### ISSUE THREAD

**Issue by RanjithNKtrr** [mautic/mautic#7970]
## Bug Description
When clicking the configuration option from settings it gives me 500 as response. While i checked the error log i find the below error

PHP Error: Maximum execution time of 60 seconds exceeded - in file ..\app\bundles\CoreBundle\Templating\TemplateReference.php - at line 93 [] []

Do i need to increase the execution timeout more than 1 minute or why it takes 1 minute to open the configuration page.

Kindly anyone help with this

| Mautic version | 2.15.3
| PHP version | 7.2
| Browser | Chrome

**Comment by RCheesley** [comment]
Hi @RanjithNKtrr if you increase the timeout period this should resolve the issue. 

This sounds more like a server config issue than a problem with Mautic, which are better addressed via the forums at https://forum.mautic.org/c/support.
