### ISSUE TITLE
Replies not tracked after changing monitored email settings

### ISSUE THREAD

**Issue by glebihan** [mautic/mautic#7972]
## Description:
When changing the email address used to track email replies, the value of the "EmailBundle_replies" entry in the "cache_items" table is not being reset. Due to that, replies in the mailbox are read but not processed.

| Q   | A
| --- | ---
Mautic version | 2.15.2
PHP version | 7.2.13

### Steps to reproduce:
1. Set a monitored email address for email replies
2. Let it run for a while
3. Change the monitored email address to a new one

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to the lack of response.
