### ISSUE TITLE
Can't create segments by Owner

### ISSUE THREAD

**Issue by gitlares** [mautic/mautic#7981]
## Bug Description

Perform the installation as specified on the official website, download the package from Github and run composer.

Operating System: Ubuntu Server 18.04.02
Web Server: nginx/1.14.0
PHP 7.2.19
Mautic: v2.16.0-dev
Web browser: Chrome, Brave, Firefox. Latest versions

### Steps to reproduce

1.- As administrator go to the Segments section.
2.- Add a new Segment.
3.- Add a new filter to the Segment. Select Owner equal to...

**Comment by RCheesley** [comment]
Unable to replicate - have created a segment with the owner equal to the administrative user, and it works fine, segment is populated.

Please provide more details if you still have this issue.
