### ISSUE TITLE
Help text "Configuration > Email > Disable trackable urls" outdated

### ISSUE THREAD

**Issue by AndrassGray** [mautic/mautic#7983]
## Bug Description

Not actually a bug, but outdated.  And probably wrong.

**Configuration > Email > Disable trackable urls**

has a help text "Gmail (and GSuite) don't like redirecting urls. This is explicitly mentioned in the Gmail guidelines here: https://support.google.com/mail/answer/81126 under 'Format' (4th bullet)" that apparently has been edited and does not speak about trackable links.

I guess the help hover could be entirely deleted.

**Comment by RCheesley** [comment]
Just made a PR to remove the reference to the link.

**Comment by npracht** [comment]
Fixed in 2.16.0, release coming soon.

**Comment by dennisameling** [comment]
Fix is merged, closing this ticket.
