### ISSUE TITLE
M3: Refactor Deprecations - ApiBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#7985]
- [ ] Remove uses of `MauticFactory`
- [ ] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [ ] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

ApiBundle/Form/Validator/Constraints/OAuthCallbackValidator.php
- [ ] Nr. 350 line 52: Calling deprecated method Symfony\Component\Validator\ConstraintValidator->buildViolation()

ApiBundle/Form/Type/ClientType.php
- [ ] Nr. 351 line 267: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 352 line 267: Overriding deprecated method Mautic\ApiBundle\Form\Type\ClientType->setDefaultOptions()
- [ ] Nr. 353 line 280: Overriding deprecated method Mautic\ApiBundle\Form\Type\ClientType->getName()

ApiBundle/Form/Type/ConfigType.php
- [ ] Nr. 354 line 117: Overriding deprecated method Mautic\ApiBundle\Form\Type\ConfigType->getName()

**Comment by anton-vlasenko** [comment]
I will review it.
