### ISSUE TITLE
M3: Refactor Deprecations - AssetBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#7986]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

AssetBundle/Form/Type/PointActionAssetDownloadType.php
- [x] Nr. 355 line 45: Overriding deprecated method Mautic\AssetBundle\Form\Type\PointActionAssetDownloadType->getName()

AssetBundle/Form/Type/CampaignEventAssetDownloadType.php
- [x] Nr. 356 line 41: Overriding deprecated method Mautic\AssetBundle\Form\Type\CampaignEventAssetDownloadType->getName()

AssetBundle/Form/Type/ConfigType.php
- [x] Nr. 357 line 75: Overriding deprecated method Mautic\AssetBundle\Form\Type\ConfigType->getName()

AssetBundle/Form/Type/FormSubmitActionDownloadFileType.php
- [x] Nr. 358 line 59: Overriding deprecated method Mautic\AssetBundle\Form\Type\FormSubmitActionDownloadFileType->getName()

AssetBundle/Form/Type/AssetListType.php
- [x] Nr. 359 line 49: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 360 line 49: Overriding deprecated method Mautic\AssetBundle\Form\Type\AssetListType->setDefaultOptions()
- [x] Nr. 361 line 63: Overriding deprecated method Mautic\AssetBundle\Form\Type\AssetListType->getName()

AssetBundle/Form/Type/AssetType.php
- [x] Nr. 362 line 185: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 363 line 185: Overriding deprecated method Mautic\AssetBundle\Form\Type\AssetType->setDefaultOptions()
- [x] Nr. 364 line 193: Overriding deprecated method Mautic\AssetBundle\Form\Type\AssetType->getName()

**Comment by escopecz** [comment]
PR: https://github.com/mautic/mautic/pull/8069
