### ISSUE TITLE
M3: Refactor Deprecations - CategoryBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#7988]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

CategoryBundle/Form/Type/CategoryListType.php
- [x] Nr. 267 line 122: Overriding deprecated method Mautic\CategoryBundle\Form\Type\CategoryListType->getName()

CategoryBundle/Form/Type/CategoryBundlesType.php
- [x] Nr. 268 line 63: Overriding deprecated method Mautic\CategoryBundle\Form\Type\CategoryBundlesType->getName()

CategoryBundle/Form/Type/CategoryType.php
- [x] Nr. 269 line 176: Overriding deprecated method Mautic\CategoryBundle\Form\Type\CategoryType->getName()

**Comment by Enc3phale** [comment]
I take this one.
