### ISSUE TITLE
M3: Refactor Deprecations - WebhookBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#7990]
- [ ] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [ ] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

WebhookBundle/Form/Type/CampaignEventSendWebhookType.php
- [ ] Nr. 21 line 133: Overriding deprecated method Mautic\WebhookBundle\Form\Type\CampaignEventSendWebhookType->getName()

WebhookBundle/Form/Type/WebhookType.php
- [ ] Nr. 22 line 162: Overriding deprecated method Mautic\WebhookBundle\Form\Type\WebhookType->getName()

WebhookBundle/Form/Type/ConfigType.php
- [ ] Nr. 23 line 67: Overriding deprecated method Mautic\WebhookBundle\Form\Type\ConfigType->getName()

**Comment by hluchas** [comment]
PR https://github.com/mautic/mautic/pull/8061
