### ISSUE TITLE
M3: Refactor Deprecations - ChannelBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#7992]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

ChannelBundle/Form/Type/MessageListType.php
- [x] Nr. 32 line 62: Overriding deprecated method Mautic\ChannelBundle\Form\Type\MessageListType->getName()

ChannelBundle/Form/Type/MessageSendType.php
- [x] Nr. 33 line 124: Overriding deprecated method Mautic\ChannelBundle\Form\Type\MessageSendType->getName()

**Comment by anton-vlasenko** [comment]
PR: https://github.com/mautic/mautic/issues/8062
