### ISSUE TITLE
M3: Refactor Deprecations - UserBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#7995]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form (i.e. `cascade_validation`)

UserBundle/Form/Type/PermissionListType.php
- [x] Nr. 52 line 26: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 53 line 26: Overriding deprecated method Mautic\UserBundle\Form\Type\PermissionListType->setDefaultOptions()
- [x] Nr. 54 line 54: Overriding deprecated method Mautic\UserBundle\Form\Type\PermissionListType->getName()

UserBundle/Form/Type/ContactType.php
- [x] Nr. 55 line 80: Overriding deprecated method Mautic\UserBundle\Form\Type\ContactType->getName()

UserBundle/Form/Type/ConfigType.php
- [x] Nr. 56 line 220: Overriding deprecated method Mautic\UserBundle\Form\Type\ConfigType->getName()

UserBundle/Form/Type/PasswordResetType.php
- [x] Nr. 57 line 59: Overriding deprecated method Mautic\UserBundle\Form\Type\PasswordResetType->getName()

UserBundle/Form/Type/PasswordResetConfirmType.php
- [x] Nr. 58 line 105: Overriding deprecated method Mautic\UserBundle\Form\Type\PasswordResetConfirmType->getName()

UserBundle/Form/Type/PermissionsType.php
- [x] Nr. 59 line 53: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 60 line 45: Overriding deprecated method Mautic\UserBundle\Form\Type\PermissionsType->getName()
- [x] Nr. 61 line 53: Overriding deprecated method Mautic\UserBundle\Form\Type\PermissionsType->setDefaultOptions()

UserBundle/Form/Type/RoleListType.php
- [x] Nr. 62 line 60: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 63 line 60: Overriding deprecated method Mautic\UserBundle\Form\Type\RoleListType->setDefaultOptions()
- [x] Nr. 64 line 76: Overriding deprecated method Mautic\UserBundle\Form\Type\RoleListType->getName()

UserBundle/Form/Type/RoleType.php
- [x] Nr. 65 line 79: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 66 line 79: Overriding deprecated method Mautic\UserBundle\Form\Type\RoleType->setDefaultOptions()
- [x] Nr. 67 line 91: Overriding deprecated method Mautic\UserBundle\Form\Type\RoleType->getName()

UserBundle/Form/Type/UserType.php
- [x] Nr. 68 line 294: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 69 line 294: Overriding deprecated method Mautic\UserBundle\Form\Type\UserType->setDefaultOptions()
- [x] Nr. 70 line 312: Overriding deprecated method Mautic\UserBundle\Form\Type\UserType->getName()

UserBundle/Form/Type/UserListType.php
- [x] Nr. 71 line 57: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 72 line 57: Overriding deprecated method Mautic\UserBundle\Form\Type\UserListType->setDefaultOptions()
- [x] Nr. 73 line 73: Overriding deprecated method Mautic\UserBundle\Form\Type\UserListType->getName()

**Comment by escopecz** [comment]
PR: https://github.com/mautic/mautic/pull/8083
