### ISSUE TITLE
M3: Refactor Deprecations - PointBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#7997]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

PointBundle/Form/Type/PointActionType.php
- [x] Nr. 81 line 48: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 82 line 48: Overriding deprecated method Mautic\PointBundle\Form\Type\PointActionType->setDefaultOptions()
- [x] Nr. 83 line 59: Overriding deprecated method Mautic\PointBundle\Form\Type\PointActionType->getName()

PointBundle/Form/Type/TriggerType.php
- [x] Nr. 84 line 194: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 85 line 194: Overriding deprecated method Mautic\PointBundle\Form\Type\TriggerType->setDefaultOptions()
- [x] Nr. 86 line 206: Overriding deprecated method Mautic\PointBundle\Form\Type\TriggerType->getName()

PointBundle/Form/Type/PointType.php
- [x] Nr. 87 line 168: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 88 line 168: Overriding deprecated method Mautic\PointBundle\Form\Type\PointType->setDefaultOptions()
- [x] Nr. 89 line 182: Overriding deprecated method Mautic\PointBundle\Form\Type\PointType->getName()

PointBundle/Form/Type/TriggerEventType.php
- [x] Nr. 90 line 95: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 91 line 95: Overriding deprecated method Mautic\PointBundle\Form\Type\TriggerEventType->setDefaultOptions()
- [x] Nr. 92 line 107: Overriding deprecated method Mautic\PointBundle\Form\Type\TriggerEventType->getName()

PointBundle/Form/Type/GenericPointSettingsType.php
- [x] Nr. 93 line 52: Overriding deprecated method Mautic\PointBundle\Form\Type\GenericPointSettingsType->getName()

**Comment by Dcoutelle** [comment]
I'll take this one.

**Comment by escopecz** [comment]
I'll take over the work on this as David is not available this week.

**Comment by escopecz** [comment]
PR: https://github.com/mautic/mautic/pull/8230
