### ISSUE TITLE
M3: Refactor Deprecations - EmailBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#7998]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

EmailBundle/Form/Type/ConfigMonitoredMailboxesType.php
- [x] Nr. 94 line 255: Overriding deprecated method Mautic\EmailBundle\Form\Type\ConfigMonitoredMailboxesType->getName()

EmailBundle/Form/Type/EmailListType.php
- [x] Nr. 95 line 75: Overriding deprecated method Mautic\EmailBundle\Form\Type\EmailListType->getName()

EmailBundle/Form/Type/VariantType.php
- [x] Nr. 96 line 100: Overriding deprecated method Mautic\EmailBundle\Form\Type\VariantType->getName()

EmailBundle/Form/Type/BatchSendType.php
- [x] Nr. 97 line 52: Overriding deprecated method Mautic\EmailBundle\Form\Type\BatchSendType->getName()

EmailBundle/Form/Type/EmailClickDecisionType.php
- [x] Nr. 98 line 43: Overriding deprecated method Mautic\EmailBundle\Form\Type\EmailClickDecisionType->getName()

EmailBundle/Form/Type/AbTestPropertiesType.php
- [x] Nr. 99 line 38: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 100 line 38: Overriding deprecated method Mautic\EmailBundle\Form\Type\AbTestPropertiesType->setDefaultOptions()
- [x] Nr. 101 line 49: Overriding deprecated method Mautic\EmailBundle\Form\Type\AbTestPropertiesType->getName()

EmailBundle/Form/Type/FormSubmitActionUserEmailType.php
- [x] Nr. 102 line 49: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 103 line 49: Overriding deprecated method Mautic\EmailBundle\Form\Type\FormSubmitActionUserEmailType->setDefaultOptions()
- [x] Nr. 104 line 59: Overriding deprecated method Mautic\EmailBundle\Form\Type\FormSubmitActionUserEmailType->getName()

EmailBundle/Form/Type/ConfigType.php
- [x] Nr. 105 line 793: Overriding deprecated method Mautic\EmailBundle\Form\Type\ConfigType->getName()

EmailBundle/Form/Type/EmailToUserType.php
- [x] Nr. 106 line 78: Overriding deprecated method Mautic\EmailBundle\Form\Type\EmailToUserType->getName()

EmailBundle/Form/Type/DashboardEmailsInTimeWidgetType.php
- [x] Nr. 107 line 91: Overriding deprecated method Mautic\EmailBundle\Form\Type\DashboardEmailsInTimeWidgetType->getName()

EmailBundle/Form/Type/EmailSendType.php
- [x] Nr. 108 line 208: Overriding deprecated method Mautic\EmailBundle\Form\Type\EmailSendType->getName()

EmailBundle/Form/Type/EmailOpenType.php
- [x] Nr. 109 line 54: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 110 line 54: Overriding deprecated method Mautic\EmailBundle\Form\Type\EmailOpenType->setDefaultOptions()
- [x] Nr. 111 line 62: Overriding deprecated method Mautic\EmailBundle\Form\Type\EmailOpenType->getName()

EmailBundle/Form/Type/ConfigMonitoredEmailType.php
- [x] Nr. 112 line 78: Overriding deprecated method Mautic\EmailBundle\Form\Type\ConfigMonitoredEmailType->getName()

EmailBundle/Form/Type/EmailUtmTagsType.php
- [x] Nr. 113 line 84: Overriding deprecated method Mautic\EmailBundle\Form\Type\EmailUtmTagsType->getName()

EmailBundle/Form/Type/EmailType.php
- [x] Nr. 114 line 559: Overriding deprecated method Mautic\EmailBundle\Form\Type\EmailType->getName()

EmailBundle/Form/Type/DashboardMostHitEmailRedirectsWidgetType.php
- [x] Nr. 115 line 63: Overriding deprecated method Mautic\EmailBundle\Form\Type\DashboardMostHitEmailRedirectsWidgetType->getName()

EmailBundle/Form/Type/DashboardSentEmailToContactsWidgetType.php
- [x] Nr. 116 line 63: Overriding deprecated method Mautic\EmailBundle\Form\Type\DashboardSentEmailToContactsWidgetType->getName()

**Comment by escopecz** [comment]
PR: https://github.com/mautic/mautic/pull/8049
