### ISSUE TITLE
M3: Refactor Deprecations - LeadBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8000]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

LeadBundle/Form/Type/ActionAddUtmTagsType.php
- [x] Nr. 133 line 44: Overriding deprecated method Mautic\LeadBundle\Form\Type\ActionAddUtmTagsType->getName()

LeadBundle/Form/Type/DeviceType.php
- [x] Nr. 134 line 50: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 135 line 50: Overriding deprecated method Mautic\LeadBundle\Form\Type\DeviceType->setDefaultOptions()
- [x] Nr. 136 line 60: Overriding deprecated method Mautic\LeadBundle\Form\Type\DeviceType->getName()

LeadBundle/Form/Type/CompanyType.php
- [x] Nr. 137 line 166: Overriding deprecated method Mautic\LeadBundle\Form\Type\CompanyType->getName()

LeadBundle/Form/Type/ListActionType.php
- [x] Nr. 138 line 52: Overriding deprecated method Mautic\LeadBundle\Form\Type\ListActionType->getName()

LeadBundle/Form/Type/CampaignEventLeadSegmentsType.php
- [x] Nr. 139 line 43: Overriding deprecated method Mautic\LeadBundle\Form\Type\CampaignEventLeadSegmentsType->getName()

LeadBundle/Form/Type/CampaignEventLeadTagsType.php
- [x] Nr. 140 line 54: Overriding deprecated method Mautic\LeadBundle\Form\Type\CampaignEventLeadTagsType->getName()

LeadBundle/Form/Type/TagType.php
- [x] Nr. 141 line 54: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 142 line 54: Overriding deprecated method Mautic\LeadBundle\Form\Type\TagType->setDefaultOptions()
- [x] Nr. 143 line 75: Overriding deprecated method Mautic\LeadBundle\Form\Type\TagType->getName()

LeadBundle/Form/Type/CampaignEventLeadOwnerType.php
- [x] Nr. 144 line 45: Overriding deprecated method Mautic\LeadBundle\Form\Type\CampaignEventLeadOwnerType->getName()

LeadBundle/Form/Type/StageActionType.php
- [x] Nr. 145 line 37: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 146 line 37: Overriding deprecated method Mautic\LeadBundle\Form\Type\StageActionType->setDefaultOptions()
- [x] Nr. 147 line 67: Overriding deprecated method Mautic\LeadBundle\Form\Type\StageActionType->getName()

LeadBundle/Form/Type/CampaignEventLeadCampaignsType.php
- [x] Nr. 148 line 99: Overriding deprecated method Mautic\LeadBundle\Form\Type\CampaignEventLeadCampaignsType->getName()

LeadBundle/Form/Type/BatchType.php
- [x] Nr. 149 line 78: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 150 line 78: Overriding deprecated method Mautic\LeadBundle\Form\Type\BatchType->setDefaultOptions()
- [x] Nr. 151 line 90: Overriding deprecated method Mautic\LeadBundle\Form\Type\BatchType->getName()

LeadBundle/Form/Type/LeadImportFieldType.php
- [x] Nr. 152 line 168: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 153 line 168: Overriding deprecated method Mautic\LeadBundle\Form\Type\LeadImportFieldType->setDefaultOptions()
- [x] Nr. 154 line 177: Overriding deprecated method Mautic\LeadBundle\Form\Type\LeadImportFieldType->getName()

LeadBundle/Form/Type/ContactFrequencyType.php
- [x] Nr. 155 line 137: Overriding deprecated method Mautic\LeadBundle\Form\Type\ContactFrequencyType->getName()

LeadBundle/Form/Type/ConfigType.php
- [x] Nr. 156 line 41: Overriding deprecated method Mautic\LeadBundle\Form\Type\ConfigType->getName()

LeadBundle/Form/Type/DashboardLeadsInTimeWidgetType.php
- [x] Nr. 157 line 49: Overriding deprecated method Mautic\LeadBundle\Form\Type\DashboardLeadsInTimeWidgetType->getName()

LeadBundle/Form/Type/PointActionType.php
- [x] Nr. 158 line 53: Overriding deprecated method Mautic\LeadBundle\Form\Type\PointActionType->getName()

LeadBundle/Form/Type/FieldType.php
- [x] Nr. 159 line 570: Overriding deprecated method Mautic\LeadBundle\Form\Type\FieldType->getName()

LeadBundle/Form/Type/StageType.php
- [x] Nr. 160 line 65: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 161 line 65: Overriding deprecated method Mautic\LeadBundle\Form\Type\StageType->setDefaultOptions()
- [x] Nr. 162 line 77: Overriding deprecated method Mautic\LeadBundle\Form\Type\StageType->getName()

LeadBundle/Form/Type/LeadFieldsType.php
- [x] Nr. 163 line 40: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 164 line 40: Overriding deprecated method Mautic\LeadBundle\Form\Type\LeadFieldsType->setDefaultOptions()
- [x] Nr. 165 line 82: Overriding deprecated method Mautic\LeadBundle\Form\Type\LeadFieldsType->getName()

LeadBundle/Form/Type/LeadImportType.php
- [x] Nr. 166 line 141: Overriding deprecated method Mautic\LeadBundle\Form\Type\LeadImportType->getName()

LeadBundle/Form/Type/ListType.php
- [x] Nr. 167 line 255: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 168 line 255: Overriding deprecated method Mautic\LeadBundle\Form\Type\ListType->setDefaultOptions()
- [x] Nr. 169 line 289: Overriding deprecated method Mautic\LeadBundle\Form\Type\ListType->getName()

LeadBundle/Form/Type/LeadCategoryType.php
- [x] Nr. 170 line 37: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 171 line 37: Overriding deprecated method Mautic\LeadBundle\Form\Type\LeadCategoryType->setDefaultOptions()
- [x] Nr. 172 line 67: Overriding deprecated method Mautic\LeadBundle\Form\Type\LeadCategoryType->getName()

LeadBundle/Form/Type/LeadLookupListType.php
- [x] Nr. 173 line 52: Overriding deprecated method Mautic\LeadBundle\Form\Type\LeadLookupListType->getName()

LeadBundle/Form/Type/LeadListType.php
- [x] Nr. 174 line 37: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 175 line 37: Overriding deprecated method Mautic\LeadBundle\Form\Type\LeadListType->setDefaultOptions()
- [x] Nr. 176 line 70: Overriding deprecated method Mautic\LeadBundle\Form\Type\LeadListType->getName()

LeadBundle/Form/Type/LeadType.php
- [x] Nr. 177 line 212: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 178 line 212: Overriding deprecated method Mautic\LeadBundle\Form\Type\LeadType->setDefaultOptions()
- [x] Nr. 179 line 227: Overriding deprecated method Mautic\LeadBundle\Form\Type\LeadType->getName()

LeadBundle/Form/Type/CampaignEventLeadFieldValueType.php
- [x] Nr. 180 line 240: Overriding deprecated method Mautic\LeadBundle\Form\Type\CampaignEventLeadFieldValueType->getName()

LeadBundle/Form/Type/DashboardLeadsLifetimeWidgetType.php
- [x] Nr. 181 line 62: Overriding deprecated method Mautic\LeadBundle\Form\Type\DashboardLeadsLifetimeWidgetType->getName()

LeadBundle/Form/Type/ListTriggerType.php
- [x] Nr. 182 line 52: Overriding deprecated method Mautic\LeadBundle\Form\Type\ListTriggerType->getName()

LeadBundle/Form/Type/FilterType.php
- [x] Nr. 183 line 90: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 184 line 90: Overriding deprecated method Mautic\LeadBundle\Form\Type\FilterType->setDefaultOptions()
- [x] Nr. 185 line 131: Overriding deprecated method Mautic\LeadBundle\Form\Type\FilterType->getName()

LeadBundle/Form/Type/MergeType.php
- [x] Nr. 186 line 71: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 187 line 71: Overriding deprecated method Mautic\LeadBundle\Form\Type\MergeType->setDefaultOptions()
- [x] Nr. 188 line 79: Overriding deprecated method Mautic\LeadBundle\Form\Type\MergeType->getName()

LeadBundle/Form/Type/ActionRemoveDoNotContact.php
- [x] Nr. 189 line 33: Overriding deprecated method Mautic\LeadBundle\Form\Type\ActionRemoveDoNotContact->getName()

LeadBundle/Form/Type/UpdateLeadActionType.php
- [x] Nr. 190 line 65: Overriding deprecated method Mautic\LeadBundle\Form\Type\UpdateLeadActionType->getName()

LeadBundle/Form/Type/NoteType.php
- [x] Nr. 191 line 89: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 192 line 89: Overriding deprecated method Mautic\LeadBundle\Form\Type\NoteType->setDefaultOptions()
- [x] Nr. 193 line 99: Overriding deprecated method Mautic\LeadBundle\Form\Type\NoteType->getName()

LeadBundle/Form/Type/OwnerType.php
- [x] Nr. 194 line 65: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 195 line 65: Overriding deprecated method Mautic\LeadBundle\Form\Type\OwnerType->setDefaultOptions()
- [x] Nr. 196 line 77: Overriding deprecated method Mautic\LeadBundle\Form\Type\OwnerType->getName()

LeadBundle/Form/Type/FormSubmitActionPointsChangeType.php
- [x] Nr. 197 line 64: Overriding deprecated method Mautic\LeadBundle\Form\Type\FormSubmitActionPointsChangeType->getName()

LeadBundle/Form/Type/ModifyLeadTagsType.php
- [x] Nr. 198 line 75: Overriding deprecated method Mautic\LeadBundle\Form\Type\ModifyLeadTagsType->getName()

LeadBundle/Form/Type/EmailType.php
- [x] Nr. 199 line 141: Overriding deprecated method Mautic\LeadBundle\Form\Type\EmailType->getName()

LeadBundle/Form/Type/CompanyChangeScoreActionType.php
- [x] Nr. 200 line 53: Overriding deprecated method Mautic\LeadBundle\Form\Type\CompanyChangeScoreActionType->getName()

LeadBundle/Form/Type/CampaignEventLeadDeviceType.php
- [x] Nr. 201 line 78: Overriding deprecated method Mautic\LeadBundle\Form\Type\CampaignEventLeadDeviceType->getName()

LeadBundle/Form/Type/TagEntityType.php
- [x] Nr. 202 line 33: Overriding deprecated method Mautic\LeadBundle\Form\Type\TagEntityType->getName()

LeadBundle/Form/Type/UpdateCompanyActionType.php
- [x] Nr. 203 line 67: Overriding deprecated method Mautic\LeadBundle\Form\Type\UpdateCompanyActionType->getName()

LeadBundle/Form/Type/CompanyMergeType.php
- [x] Nr. 204 line 61: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 205 line 61: Overriding deprecated method Mautic\LeadBundle\Form\Type\CompanyMergeType->setDefaultOptions()
- [x] Nr. 206 line 71: Overriding deprecated method Mautic\LeadBundle\Form\Type\CompanyMergeType->getName()

LeadBundle/Form/Type/CompanyListType.php
- [x] Nr. 207 line 53: Overriding deprecated method Mautic\LeadBundle\Form\Type\CompanyListType->getName()

LeadBundle/Form/Type/PointTriggerType.php
- [x] Nr. 208 line 40: Overriding deprecated method Mautic\LeadBundle\Form\Type\PointTriggerType->getName()

LeadBundle/Form/Type/TagListType.php
- [x] Nr. 209 line 63: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 210 line 63: Overriding deprecated method Mautic\LeadBundle\Form\Type\TagListType->setDefaultOptions()
- [x] Nr. 211 line 73: Overriding deprecated method Mautic\LeadBundle\Form\Type\TagListType->getName()

LeadBundle/Form/Type/AddToCompanyActionType.php
- [x] Nr. 212 line 84: Overriding deprecated method Mautic\LeadBundle\Form\Type\AddToCompanyActionType->getName()

LeadBundle/Form/Type/DncType.php
- [x] Nr. 213 line 62: Overriding deprecated method Mautic\LeadBundle\Form\Type\DncType->getName()

LeadBundle/Model/LeadModel.php
- [x] Nr. 214 line 1733: Using deprecated function key_exists()

LeadBundle/Helper/EventHelper.php
- [x] Nr. 215 line 66: Using deprecated function key_exists()
- [x] Nr. 216 line 68: Using deprecated function key_exists()
- [x] Nr. 217 line 72: Using deprecated function key_exists()
- [x] Nr. 218 line 74: Using deprecated function key_exists()
- [x] Nr. 219 line 78: Using deprecated function key_exists()
- [x] Nr. 220 line 80: Using deprecated function key_exists()
- [x] Nr. 221 line 84: Using deprecated function key_exists()
- [x] Nr. 222 line 86: Using deprecated function key_exists()
- [x] Nr. 223 line 90: Using deprecated function key_exists()
- [x] Nr. 224 line 92: Using deprecated function key_exists()

**Comment by escopecz** [comment]
PR: https://github.com/mautic/mautic/pull/8137
