### ISSUE TITLE
M3: Refactor Deprecations - FormBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8001]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

FormBundle/Form/Type/CampaignEventFormSubmitType.php
- [x] Nr. 225 line 41: Overriding deprecated method Mautic\FormBundle\Form\Type\CampaignEventFormSubmitType->getName()

FormBundle/Form/Type/FormFieldPlaceholderType.php
- [x] Nr. 226 line 38: Overriding deprecated method Mautic\FormBundle\Form\Type\FormFieldPlaceholderType->getName()

FormBundle/Form/Type/FormFieldCaptchaType.php
- [x] Nr. 227 line 68: Overriding deprecated method Mautic\FormBundle\Form\Type\FormFieldCaptchaType->getName()

FormBundle/Form/Type/FormFieldGroupType.php
- [x] Nr. 228 line 59: Overriding deprecated method Mautic\FormBundle\Form\Type\FormFieldGroupType->getName()

FormBundle/Form/Type/FieldType.php
- [x] Nr. 229 line 558: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 230 line 558: Overriding deprecated method Mautic\FormBundle\Form\Type\FieldType->setDefaultOptions()
- [x] Nr. 231 line 574: Overriding deprecated method Mautic\FormBundle\Form\Type\FieldType->getName()

FormBundle/Form/Type/PointActionFormSubmitType.php
- [x] Nr. 232 line 41: Overriding deprecated method Mautic\FormBundle\Form\Type\PointActionFormSubmitType->getName()

FormBundle/Form/Type/FormFieldSelectType.php
- [x] Nr. 233 line 76: Overriding deprecated method Mautic\FormBundle\Form\Type\FormFieldSelectType->getName()

FormBundle/Form/Type/CampaignEventFormFieldValueType.php
- [x] Nr. 234 line 194: Overriding deprecated method Mautic\FormBundle\Form\Type\CampaignEventFormFieldValueType->getName()

FormBundle/Form/Type/FormListType.php
- [x] Nr. 235 line 38: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 236 line 38: Overriding deprecated method Mautic\FormBundle\Form\Type\FormListType->setDefaultOptions()
- [x] Nr. 237 line 75: Overriding deprecated method Mautic\FormBundle\Form\Type\FormListType->getName()

FormBundle/Form/Type/FormFieldTextType.php
- [x] Nr. 238 line 41: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 239 line 41: Overriding deprecated method Mautic\FormBundle\Form\Type\FormFieldTextType->setDefaultOptions()
- [x] Nr. 240 line 51: Overriding deprecated method Mautic\FormBundle\Form\Type\FormFieldTextType->getName()

FormBundle/Form/Type/FormFieldHTMLType.php
- [x] Nr. 241 line 39: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 242 line 39: Overriding deprecated method Mautic\FormBundle\Form\Type\FormFieldHTMLType->setDefaultOptions()
- [x] Nr. 243 line 49: Overriding deprecated method Mautic\FormBundle\Form\Type\FormFieldHTMLType->getName()

FormBundle/Form/Type/FormType.php
- [x] Nr. 244 line 206: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 245 line 206: Overriding deprecated method Mautic\FormBundle\Form\Type\FormType->setDefaultOptions()
- [x] Nr. 246 line 220: Overriding deprecated method Mautic\FormBundle\Form\Type\FormType->getName()

FormBundle/Form/Type/ActionType.php
- [x] Nr. 247 line 97: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 248 line 97: Overriding deprecated method Mautic\FormBundle\Form\Type\ActionType->setDefaultOptions()
- [x] Nr. 249 line 109: Overriding deprecated method Mautic\FormBundle\Form\Type\ActionType->getName()

FormBundle/Form/Type/SubmitActionEmailType.php
- [x] Nr. 250 line 179: Overriding deprecated method Mautic\FormBundle\Form\Type\SubmitActionEmailType->getName()

**Comment by escopecz** [comment]
@dongilbert I'll help you with this one if you don't mind
