### ISSUE TITLE
M3: Refactor Deprecations - NotificationBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8002]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

NotificationBundle/Form/Type/MobileNotificationSendType.php
- [x] Nr. 251 line 100: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 252 line 100: Overriding deprecated method Mautic\NotificationBundle\Form\Type\MobileNotificationSendType->setDefaultOptions()
- [x] Nr. 253 line 108: Overriding deprecated method Mautic\NotificationBundle\Form\Type\MobileNotificationSendType->getName()

NotificationBundle/Form/Type/NotificationListType.php
- [x] Nr. 254 line 64: Overriding deprecated method Mautic\NotificationBundle\Form\Type\NotificationListType->getName()

NotificationBundle/Form/Type/MobileNotificationType.php
- [x] Nr. 255 line 209: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 256 line 209: Overriding deprecated method Mautic\NotificationBundle\Form\Type\MobileNotificationType->setDefaultOptions()
- [x] Nr. 257 line 223: Overriding deprecated method Mautic\NotificationBundle\Form\Type\MobileNotificationType->getName()

NotificationBundle/Form/Type/NotificationType.php
- [x] Nr. 258 line 211: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 259 line 211: Overriding deprecated method Mautic\NotificationBundle\Form\Type\NotificationType->setDefaultOptions()
- [x] Nr. 260 line 225: Overriding deprecated method Mautic\NotificationBundle\Form\Type\NotificationType->getName()

NotificationBundle/Form/Type/ConfigType.php
- [x] Nr. 261 line 152: Overriding deprecated method Mautic\NotificationBundle\Form\Type\ConfigType->getName()

NotificationBundle/Form/Type/MobileNotificationListType.php
- [x] Nr. 262 line 64: Overriding deprecated method Mautic\NotificationBundle\Form\Type\MobileNotificationListType->getName()

NotificationBundle/Form/Type/MobileNotificationDetailsType.php
- [x] Nr. 263 line 277: Overriding deprecated method Mautic\NotificationBundle\Form\Type\MobileNotificationDetailsType->getName()

NotificationBundle/Form/Type/NotificationSendType.php
- [x] Nr. 264 line 100: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 265 line 100: Overriding deprecated method Mautic\NotificationBundle\Form\Type\NotificationSendType->setDefaultOptions()
- [x] Nr. 266 line 108: Overriding deprecated method Mautic\NotificationBundle\Form\Type\NotificationSendType->getName()

**Comment by hluchas** [comment]
I was little bit lof.
PR link: https://github.com/mautic/mautic/pull/8091

TY!
