### ISSUE TITLE
M3: Refactor Deprecations - QueueBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8003]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

QueueBundle/Form/Type/ConfigType.php
- [x] Nr. 270 line 71: Overriding deprecated method Mautic\QueueBundle\Form\Type\ConfigType->getName()

**Comment by anton-vlasenko** [comment]
PR: https://github.com/mautic/mautic/pull/8214
