### ISSUE TITLE
M3: Refactor Deprecations - CoreBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8004]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form (i.e.  `\Mautic\CoreBundle\Form\Extension\CustomFormExtension`)

CoreBundle/Form/Type/ButtonGroupType.php
- [x] Nr. 271 line 43: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 272 line 35: Overriding deprecated method Mautic\CoreBundle\Form\Type\ButtonGroupType->getName()
- [x] Nr. 273 line 43: Overriding deprecated method Mautic\CoreBundle\Form\Type\ButtonGroupType->setDefaultOptions()

CoreBundle/Form/Type/SlotTextType.php
- [x] Nr. 274 line 41: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotTextType->getName()

CoreBundle/Form/Type/SlotImageCaptionType.php
- [x] Nr. 275 line 51: Using deprecated class Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList
- [x] Nr. 276 line 65: Using deprecated class Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList
- [x] Nr. 277 line 88: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotImageCaptionType->getName()

CoreBundle/Form/Type/SpacerType.php
- [x] Nr. 278 line 28: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 279 line 28: Overriding deprecated method Mautic\CoreBundle\Form\Type\SpacerType->setDefaultOptions()
- [x] Nr. 280 line 65: Overriding deprecated method Mautic\CoreBundle\Form\Type\SpacerType->getName()

CoreBundle/Form/Type/SlotButtonType.php
- [x] Nr. 281 line 73: Using deprecated class Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList
- [x] Nr. 282 line 87: Using deprecated class Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList
- [x] Nr. 283 line 119: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotButtonType->getName()

CoreBundle/Form/Type/HiddenEntityType.php
- [x] Nr. 284 line 49: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 285 line 49: Overriding deprecated method Mautic\CoreBundle\Form\Type\HiddenEntityType->setDefaultOptions()
- [x] Nr. 286 line 72: Overriding deprecated method Mautic\CoreBundle\Form\Type\HiddenEntityType->getName()

CoreBundle/Form/Type/ThemeListType.php
- [x] Nr. 287 line 69: Overriding deprecated method Mautic\CoreBundle\Form\Type\ThemeListType->getName()

CoreBundle/Form/Type/SortableListType.php
- [x] Nr. 288 line 129: Overriding deprecated method Mautic\CoreBundle\Form\Type\SortableListType->getName()

CoreBundle/Form/Type/FormButtonsType.php
- [x] Nr. 289 line 112: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 290 line 112: Overriding deprecated method Mautic\CoreBundle\Form\Type\FormButtonsType->setDefaultOptions()
- [x] Nr. 291 line 145: Overriding deprecated method Mautic\CoreBundle\Form\Type\FormButtonsType->getName()

CoreBundle/Form/Type/ThemeUploadType.php
- [x] Nr. 292 line 56: Overriding deprecated method Mautic\CoreBundle\Form\Type\ThemeUploadType->getName()

CoreBundle/Form/Type/SlotSuccessMessageType.php
- [x] Nr. 293 line 44: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotSuccessMessageType->getName()

CoreBundle/Form/Type/DateRangeType.php
- [x] Nr. 294 line 108: Overriding deprecated method Mautic\CoreBundle\Form\Type\DateRangeType->getName()

CoreBundle/Form/Type/ConfigType.php
- [x] Nr. 295 line 676: Overriding deprecated method Mautic\CoreBundle\Form\Type\ConfigType->getName()

CoreBundle/Form/Type/SlotSocialShareType.php
- [x] Nr. 296 line 33: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotSocialShareType->getName()

CoreBundle/Form/Type/DynamicContentFilterType.php
- [x] Nr. 297 line 86: Overriding deprecated method Mautic\CoreBundle\Form\Type\DynamicContentFilterType->getName()

CoreBundle/Form/Type/SlotDwcType.php
- [x] Nr. 298 line 63: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotDwcType->getName()

CoreBundle/Form/Type/SlotImageCardType.php
- [x] Nr. 299 line 51: Using deprecated class Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList
- [x] Nr. 300 line 65: Using deprecated class Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList
- [x] Nr. 301 line 110: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotImageCardType->getName()

CoreBundle/Form/Type/StandAloneButtonType.php
- [x] Nr. 302 line 25: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 303 line 25: Overriding deprecated method Mautic\CoreBundle\Form\Type\StandAloneButtonType->setDefaultOptions()
- [x] Nr. 304 line 35: Overriding deprecated method Mautic\CoreBundle\Form\Type\StandAloneButtonType->getName()

CoreBundle/Form/Type/SlotSegmentListType.php
- [x] Nr. 305 line 53: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotSegmentListType->getName()

CoreBundle/Form/Type/GatedVideoType.php
- [x] Nr. 306 line 110: Calling deprecated static method Symfony\Component\Form\FormTypeInterface::setDefaultOptions()
- [x] Nr. 307 line 103: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 308 line 103: Overriding deprecated method Mautic\CoreBundle\Form\Type\GatedVideoType->setDefaultOptions()
- [x] Nr. 309 line 116: Overriding deprecated method Mautic\CoreBundle\Form\Type\GatedVideoType->getName()

CoreBundle/Form/Type/SlotSeparatorType.php
- [x] Nr. 310 line 52: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotSeparatorType->getName()

CoreBundle/Form/Type/DynamicContentFilterEntryType.php
- [x] Nr. 311 line 115: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 312 line 115: Overriding deprecated method Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryType->setDefaultOptions()
- [x] Nr. 313 line 128: Overriding deprecated method Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryType->getName()

CoreBundle/Form/Type/ConfigThemeType.php
- [x] Nr. 314 line 56: Overriding deprecated method Mautic\CoreBundle\Form\Type\ConfigThemeType->getName()

CoreBundle/Form/Type/YesNoButtonGroupType.php
- [x] Nr. 315 line 34: Overriding deprecated method Mautic\CoreBundle\Form\Type\YesNoButtonGroupType->getName()

CoreBundle/Form/Type/DynamicListType.php
- [x] Nr. 316 line 54: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 317 line 54: Overriding deprecated method Mautic\CoreBundle\Form\Type\DynamicListType->setDefaultOptions()
- [x] Nr. 318 line 118: Overriding deprecated method Mautic\CoreBundle\Form\Type\DynamicListType->getName()

CoreBundle/Form/Type/SlotCategoryListType.php
- [x] Nr. 319 line 53: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotCategoryListType->getName()

CoreBundle/Form/Type/IpLookupDownloadDataStoreButtonType.php
- [x] Nr. 320 line 70: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 321 line 70: Overriding deprecated method Mautic\CoreBundle\Form\Type\IpLookupDownloadDataStoreButtonType->setDefaultOptions()
- [x] Nr. 322 line 96: Overriding deprecated method Mautic\CoreBundle\Form\Type\IpLookupDownloadDataStoreButtonType->getName()

CoreBundle/Form/Type/SlotChannelFrequencyType.php
- [x] Nr. 323 line 97: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotChannelFrequencyType->getName()

CoreBundle/Form/Type/SlotImageType.php
- [x] Nr. 324 line 36: Using deprecated class Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList
- [x] Nr. 325 line 48: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotImageType->getName()

CoreBundle/Form/Type/SlotDynamicContentType.php
- [x] Nr. 326 line 32: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotDynamicContentType->getName()

CoreBundle/Form/Type/SlotSocialFollowType.php
- [x] Nr. 327 line 84: Using deprecated class Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList
- [x] Nr. 328 line 94: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotSocialFollowType->getName()

CoreBundle/Form/Type/BuilderSectionType.php
- [x] Nr. 329 line 98: Overriding deprecated method Mautic\CoreBundle\Form\Type\BuilderSectionType->getName()

CoreBundle/Form/Type/SlotCodeModeType.php
- [x] Nr. 330 line 46: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotCodeModeType->getName()

CoreBundle/Form/Type/SlotType.php
- [x] Nr. 331 line 62: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotType->getName()

CoreBundle/Form/Type/TelType.php - this broke https://github.com/mautic/mautic/issues/8084
- [x] Nr. 332 line 25: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 333 line 25: Overriding deprecated method Mautic\CoreBundle\Form\Type\TelType->setDefaultOptions()
- [x] Nr. 334 line 43: Overriding deprecated method Mautic\CoreBundle\Form\Type\TelType->getName()

CoreBundle/Form/Type/SlotSavePrefsButtonType.php
- [x] Nr. 335 line 80: Using deprecated class Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList
- [x] Nr. 336 line 94: Using deprecated class Symfony\Component\Form\Extension\Core\ChoiceList\ChoiceList
- [x] Nr. 337 line 126: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotSavePrefsButtonType->getName()

CoreBundle/Form/Type/SlotPreferredChannelType.php
- [x] Nr. 338 line 53: Overriding deprecated method Mautic\CoreBundle\Form\Type\SlotPreferredChannelType->getName()

CoreBundle/Form/Type/DynamicContentFilterEntryFiltersType.php
- [x] Nr. 339 line 89: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 340 line 89: Overriding deprecated method Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryFiltersType->setDefaultOptions()
- [x] Nr. 341 line 113: Overriding deprecated method Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryFiltersType->getName()

CoreBundle/Templating/Twig/Extension/AssetExtension.php
- [x] Nr. 342 line 50: Overriding deprecated method Mautic\CoreBundle\Templating\Twig\Extension\AssetExtension->getName()
- [x] Nr. 343 line 50: Overriding deprecated method Mautic\CoreBundle\Templating\Twig\Extension\AssetExtension->getName()

CoreBundle/Templating/Twig/Extension/SlotExtension.php
- [x] Nr. 344 line 42: Overriding deprecated method Mautic\CoreBundle\Templating\Twig\Extension\SlotExtension->getName()
- [x] Nr. 345 line 42: Overriding deprecated method Mautic\CoreBundle\Templating\Twig\Extension\SlotExtension->getName()

CoreBundle/Controller/Api/ThemeApiController.php
- [x] Nr. 346 line 53: Calling deprecated method Symfony\Bundle\FrameworkBundle\Controller\Controller->getRequest()

CoreBundle/EventListener/CoreSubscriber.php
- [x] Nr. 347 line 143: Calling deprecated method Symfony\Component\Security\Core\SecurityContext->isGranted()
- [x] Nr. 348 line 143: Calling deprecated method Symfony\Component\Security\Core\SecurityContext->isGranted()
- [x] Nr. 349 line 83: Using deprecated class Symfony\Component\Security\Core\SecurityContext

- [x] https://github.com/mautic/mautic/blob/c90f59d5b56608190fac791f6c008f40db29c733/app/bundles/CoreBundle/Views/Exception/base.html.php#L12-L11 exception renamed to `Symfony\Component\Debug\Exception\FlattenException`

- [x] Search for use of `choices`
- [x] Convert symfony core field types
- [x] Search for collection's use of options

**Comment by alanhartless** [comment]
https://github.com/mautic/mautic/pull/7813 Needs to be merged for this.

**Comment by escopecz** [comment]
I created another issue for Alan's comment above: https://github.com/mautic/mautic/issues/8154
