### ISSUE TITLE
M3: Refactor Deprecations - SmsBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8006]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

SmsBundle/Form/Type/SmsType.php
- [x] Nr. 394 line 172: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 395 line 172: Overriding deprecated method Mautic\SmsBundle\Form\Type\SmsType->setDefaultOptions()
- [X] Nr. 396 line 186: Overriding deprecated method Mautic\SmsBundle\Form\Type\SmsType->getName()

SmsBundle/Form/Type/SmsListType.php
- [x] Nr. 397 line 63: Overriding deprecated method Mautic\SmsBundle\Form\Type\SmsListType->getName()

SmsBundle/Form/Type/ConfigType.php
- [x] Nr. 398 line 73: Overriding deprecated method Mautic\SmsBundle\Form\Type\ConfigType->getName()

SmsBundle/Form/Type/SmsSendType.php
- [x] Nr. 399 line 122: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [x] Nr. 400 line 122: Overriding deprecated method Mautic\SmsBundle\Form\Type\SmsSendType->setDefaultOptions()
- [x] Nr. 401 line 130: Overriding deprecated method Mautic\SmsBundle\Form\Type\SmsSendType->getName()

**Comment by hluchas** [comment]
PR https://github.com/mautic/mautic/pull/8081

**Comment by npracht** [comment]
Hey @hluchas, all the checkboxes in this issues are done ?

**Comment by hluchas** [comment]
@npracht Yes!
I can't check the checkboxes in description
