### ISSUE TITLE
M3: Refactor Deprecations - PluginBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8007]
- [ ] Remove uses of `MauticFactory`
- [ ] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [ ] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

PluginBundle/Form/Type/FieldsType.php
- [ ] Nr. 402 line 58: Overriding deprecated method Mautic\PluginBundle\Form\Type\FieldsType->getName()

PluginBundle/Form/Type/IntegrationCampaignsType.php
- [ ] Nr. 403 line 45: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 404 line 45: Overriding deprecated method Mautic\PluginBundle\Form\Type\IntegrationCampaignsType->setDefaultOptions()
- [ ] Nr. 405 line 54: Overriding deprecated method Mautic\PluginBundle\Form\Type\IntegrationCampaignsType->getName()

PluginBundle/Form/Type/CompanyFieldsType.php
- [ ] Nr. 406 line 58: Overriding deprecated method Mautic\PluginBundle\Form\Type\CompanyFieldsType->getName()

PluginBundle/Form/Type/IntegrationsListType.php
- [ ] Nr. 407 line 157: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 408 line 157: Overriding deprecated method Mautic\PluginBundle\Form\Type\IntegrationsListType->setDefaultOptions()
- [ ] Nr. 409 line 170: Overriding deprecated method Mautic\PluginBundle\Form\Type\IntegrationsListType->getName()

PluginBundle/Form/Type/DetailsType.php
- [ ] Nr. 410 line 138: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 411 line 138: Overriding deprecated method Mautic\PluginBundle\Form\Type\DetailsType->setDefaultOptions()
- [ ] Nr. 412 line 150: Overriding deprecated method Mautic\PluginBundle\Form\Type\DetailsType->getName()

PluginBundle/Form/Type/FeatureSettingsType.php
- [ ] Nr. 413 line 193: Overriding deprecated method Mautic\PluginBundle\Form\Type\FeatureSettingsType->getName()

PluginBundle/Form/Type/IntegrationConfigType.php
- [ ] Nr. 414 line 51: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 415 line 51: Overriding deprecated method Mautic\PluginBundle\Form\Type\IntegrationConfigType->setDefaultOptions()
- [ ] Nr. 416 line 63: Overriding deprecated method Mautic\PluginBundle\Form\Type\IntegrationConfigType->getName()

PluginBundle/Form/Type/KeysType.php
- [ ] Nr. 417 line 80: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 418 line 80: Overriding deprecated method Mautic\PluginBundle\Form\Type\KeysType->setDefaultOptions()
- [ ] Nr. 419 line 90: Overriding deprecated method Mautic\PluginBundle\Form\Type\KeysType->getName()

**Comment by anton-vlasenko** [comment]
I've accidentally moved this issue into "in progress" column.
