### ISSUE TITLE
M3: Refactor Deprecations - MauticCloudStorageBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8008]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

MauticCloudStorageBundle/Form/Type/RackspaceType.php
- [x] Nr. 1 line 44: Overriding deprecated method MauticPlugin\MauticCloudStorageBundle\Form\Type\RackspaceType->getName()

MauticCloudStorageBundle/Form/Type/OpenStackType.php
- [x] Nr. 2 line 41: Overriding deprecated method MauticPlugin\MauticCloudStorageBundle\Form\Type\OpenStackType->getName()

**Comment by escopecz** [comment]
PR: https://github.com/mautic/mautic/pull/8147
