### ISSUE TITLE
M3: Refactor Deprecations - MauticFullContactBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8009]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

MauticFullContactBundle/Form/Type/BatchLookupType.php
- [x] Nr. 3 line 62: Overriding deprecated method MauticPlugin\MauticFullContactBundle\Form\Type\BatchLookupType->getName()

MauticFullContactBundle/Form/Type/LookupType.php
- [x] Nr. 4 line 70: Overriding deprecated method MauticPlugin\MauticFullContactBundle\Form\Type\LookupType->getName()

**Comment by dongilbert** [comment]
https://github.com/mautic/mautic/issues/8079
