### ISSUE TITLE
Error in german language files

### ISSUE THREAD

**Issue by camenisch** [mautic/mautic#801]
When I setup a german speaking user I get the following error message and the applicaiton is not working anymore: 

'AH01071: Got error 'PHP message: PHP Warning:  syntax error, unexpected '(' in /opt/bitnami/apps/mautic/htdocs/translations/de/ApiBundle/messages.ini on line 34\n in /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Loader/TranslationLoader.php on line 105\nPHP message: PHP Catchable fatal error:  Argument 1 passed to Symfony\\Component\\Translation\\Loader\\ArrayLoader::flatten() must be of the type array, boolean given, called in /opt/bitnami/apps/mautic/htdocs/vendor/symfony/translation/Symfony/Component/Translation/Loader/ArrayLoader.php on line 32 and defined in /opt/bitnami/apps/mautic/htdocs/vendor/symfony/translation/Symfony/Component/Translation/Loader/ArrayLoader.php on line 53\n''

**Comment by mbabker** [comment]
#805 should fix the source file then once this is pushed to Transifex and the translations updated this should go away.

**Comment by mbabker** [comment]
Translations are updated on Transifex.
