### ISSUE TITLE
M3: Refactor Deprecations - MauticClearbitBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8010]
- [x] Remove uses of `MauticFactory`
- [x] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [x] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

MauticClearbitBundle/Form/Type/BatchLookupType.php
- [x] Nr. 5 line 62: Overriding deprecated method MauticPlugin\MauticClearbitBundle\Form\Type\BatchLookupType->getName()

MauticClearbitBundle/Form/Type/LookupType.php
- [x] Nr. 6 line 70: Overriding deprecated method MauticPlugin\MauticClearbitBundle\Form\Type\LookupType->getName()

**Comment by anton-vlasenko** [comment]
PR: https://github.com/mautic/mautic/pull/8072
