### ISSUE TITLE
M3: Refactor Deprecations - MauticCrmBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8011]
- [ ] Remove uses of `MauticFactory`
- [ ] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [ ] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

MauticCrmBundle/Form/Type/IntegrationCampaignsTaskType.php
- [ ] Nr. 7 line 43: Using deprecated interface Symfony\Component\Validator\ExecutionContextInterface
- [ ] Nr. 8 line 77: Using deprecated interface Symfony\Component\Validator\ExecutionContextInterface
- [ ] Nr. 9 line 92: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 10 line 92: Overriding deprecated method MauticPlugin\MauticCrmBundle\Form\Type\IntegrationCampaignsTaskType->setDefaultOptions()
- [ ] Nr. 11 line 100: Overriding deprecated method MauticPlugin\MauticCrmBundle\Form\Type\IntegrationCampaignsTaskType->getName()

**Comment by anton-vlasenko** [comment]
PR: https://github.com/mautic/mautic/pull/8143
