### ISSUE TITLE
M3: Refactor Deprecations - MauticSocialBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8013]
- [ ] Remove uses of `MauticFactory`
- [ ] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [ ] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

MauticSocialBundle/Form/Type/LinkedInType.php
- [ ] Nr. 27 line 45: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\LinkedInType->getName()

MauticSocialBundle/Form/Type/SocialLoginType.php
- [ ] Nr. 28 line 90: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\SocialLoginType->getName()

MauticSocialBundle/Form/Type/TwitterAbstractType.php
- [ ] Nr. 29 line 47: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\TwitterAbstractType->getName()

MauticSocialBundle/Form/Type/ConfigType.php
- [ ] Nr. 30 line 56: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\ConfigType->getName()

MauticSocialBundle/Form/Type/TweetSendType.php
- [ ] Nr. 31 line 123: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 32 line 123: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\TweetSendType->setDefaultOptions()
- [ ] Nr. 33 line 131: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\TweetSendType->getName()

MauticSocialBundle/Form/Type/TwitterMentionType.php
- [ ] Nr. 34 line 54: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\TwitterMentionType->getName()

MauticSocialBundle/Form/Type/FacebookType.php
- [ ] Nr. 35 line 70: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\FacebookType->getName()

MauticSocialBundle/Form/Type/TweetType.php
- [ ] Nr. 36 line 181: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 37 line 181: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\TweetType->setDefaultOptions()
- [ ] Nr. 38 line 186: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\TweetType->getName()

MauticSocialBundle/Form/Type/TwitterType.php
- [ ] Nr. 39 line 95: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\TwitterType->getName()

MauticSocialBundle/Form/Type/TwitterCustomType.php
- [ ] Nr. 40 line 37: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\TwitterCustomType->getName()

MauticSocialBundle/Form/Type/GooglePlusType.php
- [ ] Nr. 41 line 59: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\GooglePlusType->getName()

MauticSocialBundle/Form/Type/TweetListType.php
- [ ] Nr. 42 line 55: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\TweetListType->getName()

MauticSocialBundle/Form/Type/MonitoringType.php
- [ ] Nr. 43 line 112: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 44 line 112: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\MonitoringType->setDefaultOptions()
- [ ] Nr. 45 line 125: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\MonitoringType->getName()

MauticSocialBundle/Form/Type/TwitterHashtagType.php
- [ ] Nr. 46 line 54: Overriding deprecated method MauticPlugin\MauticSocialBundle\Form\Type\TwitterHashtagType->getName()

**Comment by npracht** [comment]
@anton-vlasenko all the checkboxes here are done ?

**Comment by anton-vlasenko** [comment]
PR: https://github.com/mautic/mautic/pull/8085

**Comment by anton-vlasenko** [comment]
> @anton-vlasenko all the checkboxes here are done ?

@npracht Yes, they are done. I haven't found anything left.
I don't have permissions to edit descriptions so I can't "check" those checkboxes.
