### ISSUE TITLE
M3: Refactor Deprecations - MauticEmailMarketingBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8014]
- [ ] Remove uses of `MauticFactory`
- [ ] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [ ] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

MauticEmailMarketingBundle/Form/Type/MailchimpType.php
- [ ] Nr. 47 line 188: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 48 line 188: Overriding deprecated method MauticPlugin\MauticEmailMarketingBundle\Form\Type\MailchimpType->setDefaultOptions()
- [ ] Nr. 49 line 196: Overriding deprecated method MauticPlugin\MauticEmailMarketingBundle\Form\Type\MailchimpType->getName()

MauticEmailMarketingBundle/Form/Type/IcontactType.php
- [ ] Nr. 50 line 133: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 51 line 133: Overriding deprecated method MauticPlugin\MauticEmailMarketingBundle\Form\Type\IcontactType->setDefaultOptions()
- [ ] Nr. 52 line 141: Overriding deprecated method MauticPlugin\MauticEmailMarketingBundle\Form\Type\IcontactType->getName()

MauticEmailMarketingBundle/Form/Type/ConstantContactType.php
- [ ] Nr. 53 line 137: Using deprecated interface Symfony\Component\OptionsResolver\OptionsResolverInterface
- [ ] Nr. 54 line 137: Overriding deprecated method MauticPlugin\MauticEmailMarketingBundle\Form\Type\ConstantContactType->setDefaultOptions()
- [ ] Nr. 55 line 145: Overriding deprecated method MauticPlugin\MauticEmailMarketingBundle\Form\Type\ConstantContactType->getName()

**Comment by anton-vlasenko** [comment]
PR: https://github.com/mautic/mautic/pull/8139
