### ISSUE TITLE
M3: Refactor Deprecations - MauticCitrixBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8015]
- [ ] Remove uses of `MauticFactory`
- [ ] Search for and remove/refactor M2 `@deprecated` code if simple otherwise, create a new issue with details to be prioritized
- [ ] https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#form

MauticCitrixBundle/Form/Type/CitrixListType.php
- [ ] Nr. 56 line 73: Overriding deprecated method MauticPlugin\MauticCitrixBundle\Form\Type\CitrixListType->getName()

MauticCitrixBundle/Form/Type/CitrixCampaignActionType.php
- [ ] Nr. 57 line 125: Overriding deprecated method MauticPlugin\MauticCitrixBundle\Form\Type\CitrixCampaignActionType->getName()

MauticCitrixBundle/Form/Type/CitrixActionType.php
- [ ] Nr. 58 line 218: Overriding deprecated method MauticPlugin\MauticCitrixBundle\Form\Type\CitrixActionType->getName()

MauticCitrixBundle/Form/Type/CitrixCampaignEventType.php
- [ ] Nr. 59 line 104: Overriding deprecated method MauticPlugin\MauticCitrixBundle\Form\Type\CitrixCampaignEventType->getName()
Finished rendering output.

**Comment by anton-vlasenko** [comment]
PR: https://github.com/mautic/mautic/pull/8165
