### ISSUE TITLE
M3: Refactor Deprecations - Deep items use in ParameterBag

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8023]
ParameterBag's support for deep/nested items was removed https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#httpfoundation. There are a few places in Mautic that depends on this and thus needs to be refactored. 

For example:
https://github.com/mautic/mautic/blob/4b46c63e08ce8907c195e0cbb7c20d41dadf5f77/app/bundles/PointBundle/Controller/TriggerEventController.php#L156
https://github.com/mautic/mautic/blob/23d4a90bba636bff7c15dcf190e0f4020bf25247/app/bundles/FormBundle/Controller/FieldController.php#L191

Search and refactor all uses of the ParameterBag's `->get(` that leverage deep items.

**Comment by dongilbert** [comment]
https://github.com/mautic/mautic/pull/8180
