### ISSUE TITLE
M3: Refactor Deprecations - BazingaOAuthServerBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8024]
Mautic has a forked version of the BazingaOAuthServerBundle but it is no longer maintained upstream and it is not compatible with Symfony 3.4. 

Remove and upgrade deprecated code in this release branch https://github.com/mautic/BazingaOAuthServerBundle/tree/release-0.0.3 per https://github.com/symfony/symfony/blob/3.0/UPGRADE-3.0.md#httpfoundation

**Comment by alanhartless** [comment]
Started to update in order to load M3 in https://github.com/mautic/mautic/commits/3.x but need to test once M3 is more stable

**Comment by escopecz** [comment]
I found several issues in Mautic. Not in the BazingaOAuthServerBundle itself.

PR: https://github.com/mautic/mautic/pull/8270
