### ISSUE TITLE
M3: JMS Serializer

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8027]
JMS serializer is used for Mautic's API. Some BC breaks are introduced in the latest version that needs to be changed in Mautic 3.

See https://github.com/schmittjoh/JMSSerializerBundle/blob/master/UPGRADING.md

**Comment by alanhartless** [comment]
Started in https://github.com/mautic/mautic/commit/32aa9243e0849fcbb66208884edd820d88e19dc0 under https://github.com/mautic/mautic/tree/3.x in order to get M3 loading.

**Comment by escopecz** [comment]
As part of this issue we'll have to deal with this:
`Fatal error: Class 'JMS\Serializer\Metadata\Driver\PhpDriver' not found in /Users/jan/dev/mautic/app/bundles/ApiBundle/Serializer/Driver/ApiMetadataDriver.php on line 18`

Run PHPSTAN to replicate quickly.

**Comment by dongilbert** [comment]
Not a big deal. Extend the `Metadata\Driver\AbstractFileDriver` instead of the `PhpDriver`, then add the `getExtension` method from the `PhpDriver` that returns `return 'php';`

**Comment by dongilbert** [comment]
This is what I have so far @escopecz https://github.com/mautic/mautic/pull/8201/files
