### ISSUE TITLE
M3: PHPUnit 5.x to 7.x

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8028]
Tests need to be upgraded from 5.x to 7.x. For now, we cannot support PHPUnit 8.x due to the dependency on phpunit-selenium. 

Changes required to tests are noted in: 
https://phpunit.de/announcements/phpunit-6.html
https://phpunit.de/announcements/phpunit-7.html

Discussion - Per Symfony 3.4, all tests should be moved into a /tests directory in the root. Should Mautic 3 do this and if so, how should tests for plugins be handled?

**Comment by escopecz** [comment]
PR: https://github.com/mautic/mautic/pull/8190
