### ISSUE TITLE
M3: IntegrationsBundle

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8030]
Mautic/Acquia, Inc has written a plugin, [IntegrationsBundle](https://github.com/mautic-inc/plugin-integrations), with cleaner implementations than the PluginBundle's AbstractIntegration class. This bundle can be copied into core Mautic for future integration development in M3. The plugin will remain intact for M2 use.

- [x] Copy IntegrationsBundle into app/bundles
- [x] Search/replace `MauticPlugin\IntegrationsBundle` with `Mautic\IntegrationsBundle`

**Comment by escopecz** [comment]
I will take a look into this. I'll try to preserve the git history. If I won't find the way I'll take over DB's PR.
