### ISSUE TITLE
Field ID has inconsistent types switching between String and Long when editing Contacts

### ISSUE THREAD

**Issue by lisandrop** [mautic/mautic#8031]
## Bug Description
The type of attribute ID in field of Contacts switch between String and Long making it harder to serialize data to work with Objects in strongly typed languages like Java.

While building a Java connector for Mautic, I noticed that when tests run against [Edit contact](https://developer.mautic.org/#edit-contact)) using `PUT` when the contact is `created` I get the following response:

```
{
    "contact": {
        "isPublished": true,
        "dateAdded": "2019-10-27T15:36:47+00:00",
        "dateModified": null,
        "createdBy": 2,
        "createdByUser": "API API",
        "modifiedBy": null,
        "modifiedByUser": null,
        "id": 7404,
        "points": 0,
        "color": null,
        "fields": {
            "core": {
                "title": {
                    "id": 1,              // Notice the id field is a Number
                    "group": "core",
                    "label": "Title",
                    "alias": "title",
                    "type": "lookup",
                    "value": ""
                },
```

But when the contact already existed the ID field is a String:

```
{
    "contact": {
        "isPublished": true,
        "dateAdded": "2019-10-26T14:36:42+00:00",
        "dateModified": "2019-10-27T15:22:39+00:00",
        "createdBy": 2,
        "createdByUser": "API API",
        "modifiedBy": 2,
        "modifiedByUser": "API API",
        "id": 7342,
        "points": 0,
        "color": null,
        "fields": {
            "core": {
                "title": {
                    "id": "1",              // Notice the id field is a String
                    "label": "Title",
                    "alias": "title",
                    "type": "lookup",
                    "group": "core",
                    "object": "lead",
                    "is_fixed": "1",
                    "value": ""
                },
```

Resulting types should be consistent regardless of behavior. 

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.0.33
| Browser | API Issue

### Steps to reproduce
1. Edit existing user get field ID as String
2. Edit non existing user, gets created and returns field ID as Number.
 
### Log errors
No log Errors

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!
