### ISSUE TITLE
Unable to open file for reading

### ISSUE THREAD

**Issue by Mancy** [mautic/mautic#8034]
## Bug Description
Send Email to contact using api fails when embed image option is enabled and the image source has tokens in the url.
I guess that Images being embedded before the processing of the token parameters

| Q   | A
| --- | ---
| Mautic version | v2.15.3
| PHP version | 7.0.33
| Browser | Chrome

### Steps to reproduce
1. Enable Embed Image
2. set template code as "{site_url}/images/logo/{img}.png"
3. sendEmail to contact using `$emailApi->sendToContact($emailId, $contactId, array('tokens'=>array('site_url'=>'https://urlto.src/png', 'img'=>'logo')));`

 
### Log errors
```
{
  "success": false,
  "failed": "Unable to open file for reading [{site_url}/images/logo/{img}.png]"
}
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
This. has been resolved by #8600 so closing the issue - thank you for taking the time to report it.
