### ISSUE TITLE
Special Characters in UTM tags make urls not working

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#8039]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you use special characters in the UTM tags for email,  the url generate in the email links will be wrong leading to an error page.
Special characters are bad in url in general so a tooltip mentioning to not use them in the UTM tag would be useful. 

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create an email with a link to click
2. Enter UTM tags with special characters (like ' or é) 
3. Send the email and click on the link
4. See that you got an error page
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, can you check what database collation you're using?

**Comment by RCheesley** [comment]
@florentpetitjean as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2? Thanks!
