### ISSUE TITLE
Leads no longer being created in SugarCRM

### ISSUE THREAD

**Issue by SulphurDioxide** [mautic/mautic#8040]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I've had the SugarCRM plugin enabled on Mautic for a while and it's been working as expected. When a certain trigger is fired, a lead is created in SugarCRM. I recently updated to version 2.15.3 and since, I have had repeated notifications saying 'Failed to execute campaign event' and no users are being pushed through to SugarCRM as they previously had been.

### Other items of note:
 - The version of SugarCRM I'm using has not changed.
 - The only Mautic error appears to be: 
>  mautic.NOTICE: PHP Notice - Undefined index: eventType - in file <path>/app/bundles/CampaignBundle/Controller/EventController.php - at line 257
 - SugarCRM reports no errors. In fact, it seems to indicate that a login was successful.
 - Could this be related to #7555 @npracht ?

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2.10
| Browser | N/A

### Steps to reproduce
1. Setup and configure SugarCRM
2. Add 'Sugar CRM' as a plugin in mautic and authorise it
3. Setup the contact mapping with required fields
 
### SugarCRM Log errors

> [Tue Oct 29 10:55:11.620907 2019] [:error] [pid 22153:tid 140452163446528] [client xxx.xxx.x.x:xxxxx] PHP Notice:  Undefined property: User::$default_team in <path>/service/v4/SugarWebServiceImplv4.php on line 168
> [Tue Oct 29 10:55:11.621024 2019] [:error] [pid 22153:tid 140452163446528] [client xxx.xxx.x.x:xxxxx] PHP Notice:  Undefined index: wl_list_max_entries_per_page in <path>/service/v4/SugarWebServiceImplv4.php on line 177
> [Tue Oct 29 10:55:11.621056 2019] [:error] [pid 22153:tid 140452163446528] [client xxx.xxx.x.x:xxxxx] PHP Notice:  Undefined index: wl_list_max_entries_per_subpanel in <path>/service/v4/SugarWebServiceImplv4.php on line 178

I've added the above log lines from apache but I'm pretty sure they're irrelevant because they've existed alongside the plugin working.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @SulphurDioxide !
I don't think it is related to https://github.com/mautic/mautic/pull/7555. Also, without any logs... it is complicated to know what is the issue. The issue itself seems coming from the campaign.

Can you try to clear cache ? Also clear plugin cache and redo the settings ?

**Comment by SulphurDioxide** [comment]
Hi @npracht - Thanks for the reply! 

I've cleared the cache by using `app/console cache:clear` and it reported that the cache was successfully cleared. I didn't realise there was a plugin cache and I can't seem to find anything that indicates how I can clear it. Additionally, I don't see a way of disabling or removing the settings for a plugin without saving blanks into the fields. 

The only logs generated during this process are above - I've tried to debug this myself but the lack of any logs has slowed me up too.

**Comment by npracht** [comment]
If you go in the DB, you have a table plugin cache.

**Comment by SulphurDioxide** [comment]
Hmm, I can't find that table in the database:
![plugins](https://user-images.githubusercontent.com/14162920/67853097-b618d600-fb05-11e9-9ec2-675fe0a989fd.PNG)

And the only tables I have that contain 'cache' are:
![cache](https://user-images.githubusercontent.com/14162920/67853114-c2049800-fb05-11e9-891f-8bd3b9517c98.PNG)

**Comment by pstevens71** [comment]
I have kind of a similar Problem.  I had leads syncing from contact form fills working no problem, and on form completion a Mautic Action to push it to SuiteCRM.  I have a form on WordPress with Gravity Forms that creates the lead in Mautic, then Mautic pushes it to SuiteCRM.  This works no problem and has been working for like over a year on various versions.  I just upgraded to 2.15.3 and now Gravity Forms still creates the lead in Mautic, but it pushes a blank contact to SuiteCRM.  I've looked in the DB and the lead created in Mautic looks good.  The weird thing is I can create a lead with the exact same mautic form on a mautic landing page and it creates the lead in Mautic and pushes it to SuiteCRM properly.  The problem only exists when the lead is created by the Gravity Forms API.  However, the lead looks good in Mautic, even in the DB I can't see any difference between leads created by Mautic that get pushed to SuiteCRM and leads that are created by API and don't get pushed to SuiteCRM?

**Comment by richmarks20** [comment]
Haven't investigated in detail, but same problem - no leads pushed to Sugar since updating to Mautic 2.15.3 - Lots of "Failed to execute campaign event" errors in the Mautic UI. 

Can create leads using my Sugar API from other software using the same credentials.
Mautic to Sugar connectivity is fine
Nothing has changed with my Sugar setup.

**Comment by pstevens71** [comment]
I tried to push the leads via campaign and got same "Failed to execute...."   In the lead it says "this event encountered an unknown error",   There is an error in the log about "unknown error obtaining the access token".  I've tried re-authorizing the app and that works not problem but doesn't help.

**Comment by pstevens71** [comment]
If it helps, I just replaced the  /plugins/MauticCRMBundle/Integration/SugarcrmIntegration.php with the previous version I had that was working on 2.15.1  and it works again.  So that kind of narrows it down to the changes made in the last two releases.

**Comment by SulphurDioxide** [comment]
@pstevens71 Ah, that's good to know, thanks. I had it working reliably on 2.15.2 which is why I figured the cause might be #7555 because it was seemingly the only change to the sugar integration file between 2.15.2 and 2.15.3.

**Comment by pstevens71** [comment]
Did some more testing, my "fix" of using an older version of the file, fixes the push from form issue I was having, but push via campaign still doesn't work.

**Comment by richmarks20** [comment]
Hi @Enc3phale - could you spare a few mins to have a look at this? Any input/ideas appreciated.

**Comment by autoize** [comment]
We tested the SuiteCRM integration between Mautic 2.15.2 and SuiteCRM 7.11.5 (Sugar version 6.5.25) and **were successful** having Contacts created in SuiteCRM, to be created as a Mautic Contact. Any edits made to synced contacts (from the SuiteCRM side) **do update** over to the corresponding Mautic Contact - as we had set SuiteCRM as the system of record.

However data is **not** pushing from Mautic => SuiteCRM.
Creating a test segment and campaign in Mautic, where any contact added to the segment should be pushed to SuiteCRM by the "Push to Integration" action **does not work**. A notification appears in the Mautic dashboard saying the action has failed, and a generic error is recorded in the contact record.

**Neither does** the standalone form action "Push to Integration" work. Normally with other integrations like Vtiger, HubSpot, or Dynamics, after the form with this action is filled, a corresponding contact is automatically created on the Integration side. 

We tried @pstevens71 's suggestion to downgrade the SugarcrmIntegration.php to **2.15.1** to no avail. Additionally, downgrading to **2.15.0** also did not help with transmitting data between Mautic => SuiteCRM. 

Nothing notable was written to the Mautic error log.

**Comment by lead2crm** [comment]
Same issue as above.

**Comment by ig-fernando** [comment]
Same problem on the "push to integration" option. we are using SugarCRM.

**Comment by mrbarletta** [comment]
Same issue when the sync, I modified this file `plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php` to make it work again.

I can't do a PR as I don't fully understand what I am doing but had to add on line 1357
```
$this->buildCompositeBody(
                        $mauticData,
                        $availableFields,
                        $contactSugarFieldsToCreate, //use all matched fields when creating new records in Sugar
                        'Contacts',
                        $lead,
                        $ownerAssignedUserIdByEmail
                    );
```

and modify line 1284 
```
//Contacts fields
            $contactSugarFieldsToCreate            = $this->cleanSugarData($config, array_keys($config['leadFields']), 'Contacts');
            $fieldsToUpdateInContactsSugar = $this->cleanSugarData($config, $fieldsToUpdateInSugar, 'Contacts');
            $contactSugarFields            = array_intersect_key($contactSugarFieldsToCreate, $fieldsToUpdateInContactsSugar);
```

this will get the push to work again but this was a quick fix (few hours debugging though)

**Comment by lead2crm** [comment]
> Same issue when the sync, I modified this file `plugins/MauticCrmBundle/Integration/SugarcrmIntegration.php` to make it work again.
> 
> I can't do a PR as I don't fully understand what I am doing but had to add on line 1357
> 
> ```
> $this->buildCompositeBody(
>                         $mauticData,
>                         $availableFields,
>                         $contactSugarFieldsToCreate, //use all matched fields when creating new records in Sugar
>                         'Contacts',
>                         $lead,
>                         $ownerAssignedUserIdByEmail
>                     );
> ```
> 
> and modify line 1284
> 
> ```
> //Contacts fields
>             $contactSugarFieldsToCreate            = $this->cleanSugarData($config, array_keys($config['leadFields']), 'Contacts');
>             $fieldsToUpdateInContactsSugar = $this->cleanSugarData($config, $fieldsToUpdateInSugar, 'Contacts');
>             $contactSugarFields            = array_intersect_key($contactSugarFieldsToCreate, $fieldsToUpdateInContactsSugar);
> ```
> 
> this will get the push to work again but this was a quick fix (few hours debugging though)

I made these changes (added the new contact line) and modified the line with what you wrote (i see the only change there was array_intersect_key, but I replaced the whole chunk with your code.

Still didnt push a contact from mautic campaign to the crm, unfortunately.

my error log doesnt show anything specific
`[2020-04-06 00:55:13] mautic.WARNING: PHP Warning - array_merge(): Argument #1 is not an array - in file /home/lead2crm/public_html/map/app/bundles/ReportBundle/Entity/Report.php - at line 490 [] []
[2020-04-06 00:55:13] mautic.WARNING: PHP Warning - in_array() expects parameter 2 to be array, null given - in file /home/lead2crm/public_html/map/app/bundles/ReportBundle/Event/ReportGeneratorEvent.php - at line 401 {"column":"comp.companyname","columns":null} []`

**Comment by mrbarletta** [comment]
@lead2crm I tested this using the cron, not the campaign, do you know which method is called when the campaign triggers?

**Comment by lead2crm** [comment]
> @lead2crm I tested this using the cron, not the campaign, do you know which method is called when the campaign triggers?

Unfortunately not :(

**Comment by ig-fernando** [comment]
Any progress on this, this is major, it is creating challenges for people using SugarCRM and in times of Covid, when no one is around, automation is key... is there an estimate for the next update that could have this fix?

**Comment by lead2crm** [comment]
The edits to the lines of code above did not help my sync. Autoize above has resolved this, you may want to reach out to them to get a quote to fix.

**Comment by npracht** [comment]
Hi there, I don’t understand you issue, we’re using it everyday and it works properly. Have you apply all pending PRs concerning Sugar? You can reach me on Slack if you like, I’ll give more information.

**Comment by richmarks20** [comment]
@npracht just a thought, but perhaps you're using enterprise/hosted Sugar 7.x? The problem is with SugarCE 6.x (Which is also the basis of SuiteCRM). 

For clarity, the issue is; in Mautic, when the plugin settings' system of record is Sugar (ie, the mapping arrows point from Sugar, towards Mautic), contacts are not pushed to Sugar when campaign events are triggered. 

- The notifications panel shows '_Failed to execute campaign event for [contact name]_'
- The contacts/view/[user id] page shows '_Last execution error: Generic error._'
- At the trigger execution times, there's nothing of interest in the php, Mautic, or Sugar logs
- Sugar access log shows no inbound request from Mautic.

I'm now running Mautic 3.0.1 and this is still the case. Behaviour exactly the same as the initial post at the top of this issue.

Worth noting that when the system of record is Mautic, leads are created in Sugar (using the same creds etc). When I change the arrow direction (to make Sugar the system of record), and save the plugin settings, it stops working.

**Comment by npracht** [comment]
Did you map all mandatories fields of Sugar ?

**Comment by richmarks20** [comment]
Yes, absolutely certain. Caches cleared, reathorised plugin/oauth etc. Tried everything. As in the first post, it was working fine, but stopped after 2.15.3 upgrade. Tried on a clean 3.0.1 dev install, same behaviour. Even tried with a vanilla Sugar install with bare minimum required fields - same behaviour.

**Comment by npracht** [comment]
Did you try https://github.com/mautic/mautic/pull/7420 ?

**Comment by pstevens71** [comment]
Did anyone get this working with SuiteCRM?  I'm afraid to upgrade past 2.15.3, which I kind of have mostly synching except for push from Mautic to SuiteCRM.  Any updates?

**Comment by RCheesley** [comment]
@pstevens71 I would recommend updating in a local environment and testing it there.

We have had real difficulty trying to find people to help us test the fixes and features for Sugar/Suite which means that we cannot merge them in a timely fashion sadly - for example the PR mentioned: https://github.com/mautic/mautic/pull/7420 which was recently closed for that reason.

Would you be able to help us with testing going forward?

**Comment by pstevens71** [comment]
hey @RCheesley if you guys are actively working on a solution, I'm happy to upgrade to the latest version of Mautic and use my "live" environment for testing/fixing this feature.  It's not a big deal if the sync doesn't work for a couple of weeks if we're actively working on fixing it.  The only issue with setting up a test environment is that its a huge project in itself.  I'll have to set up a duplicate Mautic instance and a duplicate SuiteCRM instance and then set up the "sync", etc.  Just to test.  I'd rather spend my time testing in the live environment for this particular issue, as long as it's being actively worked on.

So, if I upgrade my live to 2.16.3 are you up for solving this one with me?  I'm pretty good at the testing part and trying different scenarios, but I' not a developer.  I need some help with that part.  Plus, I'm really familiar with both SuiteCRM and Mautic from a fairly advanced user perspective and on the SuiteCRM side have a pretty good understanding of DB and how it all works together.

**Comment by RCheesley** [comment]
@pstevens71 assuming that 'you guys' is referring to the community, we are actively working on getting through the ~450 issues and ~200 open PR's. It's a huge task, we are a small group of people. We need the support of the wider community with this :).

The PR I mentioned was abandoned by the original author and as we had no interest from community testers we closed it, but we can re-open if you would be able to help us with testing. It may need to be updated to support Mautic 3.x - I don't know at present.

We have mautibox.com which can be used for testing in many situations or you can spin up your local instance which might be preferable when testing integrations.

Happy to help where we can with testing and troubleshooting!

**Comment by pstevens71** [comment]
Ok, I'll do the upgrade and report findings.  The particular problem with this issue is it doesn't generate any errors on the Mautic side or SuiteCRM side, so its really difficult to find any sort of root of the problem.

**Comment by pstevens71** [comment]
hey @RCheesley I upgraded to Mautic 3.01  here's what I've tested so far:

Create lead in Mautic ->Syncs to SuiteCRM -OK
Create lead in SuiteCRM-> syncs to SuiteCRM -OK
Change record in SuiteCRM -> Changes record in Mautic -OK
Change field in Mautic (that supposed to update SuiteCRM) -> NO, does not update the SuiteCRM Record
Push Lead to SuiteCRM via Form Action or Campaign Action -> NO, does not work, it creates a blank record in SuiteCRM with all the fields blank.

Is there anything else you want my to test or try?

**Comment by RCheesley** [comment]
@pstevens71 thanks so much for testing! 

Do you have any logs from Mautic or SuiteCRM?

**Comment by RCheesley** [comment]
@autoize did you manage to look into this at all? Would anybody in your team be able to debug and share a PR?

**Comment by pstevens71** [comment]
These are the only errors in Mautic Log  (I don't think they pertain to the problem as the timings do not match:
[2020-07-30 23:04:05] mautic.ERROR: UPDATE CHECK: Could not fetch a release list: cURL error 2: easy handle already used in multi handle (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] []
[2020-07-31 08:32:17] mautic.ERROR: UPDATE CHECK: Could not fetch a release list: cURL error 2: easy handle already used in multi handle (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] []
[2020-07-31 09:25:27] mautic.ERROR: UPDATE CHECK: Could not fetch a release list: cURL error 2: easy handle already used in multi handle (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] []

On the SuiteCRM side, not 100% sure, going to do some more testing, but this error seems to be generated around the time they syncs were supposed to happen:

Fri Jul 31 13:31:35 2020 [1284][1][FATAL] SugarBean::populateDefaultValues $field_defs should be an array

**Comment by pstevens71** [comment]
just an update, tried the "push" again with both error logs open.  No errors are generated in either SuiteCRM or Muatic side, so disregard previous comment.

**Comment by RCheesley** [comment]
OK great - thanks for checking!

**Comment by rashaqqel** [comment]
Hello, Can the mautic team look into this? ive tried mautic 2.15.3/2.16.x and 3.1.x and suitecrm 6.5 module doesnt work.. any ideas to get it working? it authorizes fine but no leads get pushed or pulled.

**Comment by J-Light** [comment]
We have two instance of Mautic in production. Both are at v3.1.2, only difference in setup is show below. Once the leads sync, the other the leads do not sync. No errors in the log files. 

Not working instance (we only really want form to go to leads)
![image](https://user-images.githubusercontent.com/2544660/99025501-0d78cf80-25bd-11eb-98e9-e42621d38118.png)

Working instance
![image](https://user-images.githubusercontent.com/2544660/99025536-22edf980-25bd-11eb-9c2d-15f84205fb00.png)
