### ISSUE TITLE
File path for default Form Thank you page

### ISSUE THREAD

**Issue by ackrug** [mautic/mautic#8045]
I'm trying to change the default form thank you page, can anyone tell me where this file might be?

**Comment by npracht** [comment]
Hi @ackrug ! thanks for your message.
The mautic policies requests that all chat, question, feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
