### ISSUE TITLE
Refactor FormSubmitHelpers in all bundles to use events over the static method

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#8051]
See https://github.com/mautic/mautic/blob/916cb750f2e7896c735b231c98fd9a58c65cf0e5/app/bundles/EmailBundle/Helper/FormSubmitHelper.php#L26 <- this method must be refactored to a subscriber probably.

It's used twice in https://github.com/mautic/mautic/blob/916cb750f2e7896c735b231c98fd9a58c65cf0e5/app/bundles/EmailBundle/EventListener/FormSubscriber.php#L48 where we should replace the callback with dispatching an event.

**Comment by dongilbert** [comment]
https://github.com/mautic/mautic/pull/8186

**Comment by escopecz** [comment]
Closing as duplicate of https://github.com/mautic/mautic/issues/8066
