### ISSUE TITLE
Refactor PointEventHelper in all bundles from static methods into events

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#8055]
Here it is: https://github.com/mautic/mautic/blob/916cb750f2e7896c735b231c98fd9a58c65cf0e5/app/bundles/EmailBundle/Helper/PointEventHelper.php#L20

We need that to get rid of MauticFactory

**Comment by kuzmany** [comment]
This PR already rewrite it:
https://github.com/mautic/mautic/pull/7330

**Comment by escopecz** [comment]
Awesome! I'll move it to M3 board.

**Comment by escopecz** [comment]
Well, that's not necessary. Let's track it in this issue. Would you mind if I change the PR to point to m2-to-m3 branch?

**Comment by kuzmany** [comment]
Do you ask me to rebase it for m2-to-m3 branch, right?

**Comment by escopecz** [comment]
No need to rebase. It's the same as staging. Just point your PR to m2-to-m3 branch instead of staging so if someone clicks the merge button it would go to the right branch.

**Comment by RCheesley** [comment]
@escopecz @kuzmany what was the status on this? I saw another PR. which was closed (https://github.com/mautic/mautic/pull/8161) - can we close this issue or is it still needed?

**Comment by kuzmany** [comment]
I need revert back it and rebased based on M3 codebase
I will do it in few days
