### ISSUE TITLE
Refactor onCampaignTriggerActionSendEmailToUser()

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#8058]
This method is using deprecated `EmailEvents::ON_CAMPAIGN_TRIGGER_ACTION` action. Use `EmailEvents::ON_CAMPAIGN_BATCH_ACTION` instead.

https://github.com/mautic/mautic/blob/991b5c74a6dcfbb3d13881dc2033c84d5197f240/app/bundles/EmailBundle/EventListener/CampaignSubscriber.php#L380

**Comment by kuzmany** [comment]
Fixed https://github.com/mautic/mautic/pull/8172

**Comment by kuzmany** [comment]
Also need refactor 

https://github.com/mautic/mautic/blob/991b5c74a6dcfbb3d13881dc2033c84d5197f240/app/bundles/EmailBundle/EventListener/CampaignSubscriber.php#L225

Nobody did it?

**Comment by escopecz** [comment]
I don't think so. Can you either add a new issue to the M3 board or refactor it as part of https://github.com/mautic/mautic/pull/8172?
