### ISSUE TITLE
Refactor use of MailHelper out of MauticFactory

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#8060]
MailHelper::validateEmail() is deprecated. Use EmailValidator service instead. Then remove the deprecated method.

https://github.com/mautic/mautic/blob/916cb750f2e7896c735b231c98fd9a58c65cf0e5/plugins/MauticCrmBundle/Api/HubspotApi.php#L65

**Comment by ondrejsibl** [comment]
This issue is more complexed. We can't inject EmailValidator service easily, because the class HubspotApi is created in https://github.com/mautic/mautic/blob/916cb750f2e7896c735b231c98fd9a58c65cf0e5/plugins/MauticCrmBundle/Integration/CrmAbstractIntegration.php#L184

**Comment by p365labs** [comment]
@ondrejsibl I'm not getting the point why we are validating the email and them send to HUBSPOT and they will validate it again...

**Comment by p365labs** [comment]
@alanhartless & @escopecz I've a PR for this if u want to have a look I can open it. wdyt?

**Comment by alanhartless** [comment]
@p365labs Definitely PR something once ready! Or if you'd like us to review it before hand, just ensure that WIP is in the title. Thanks!
