### ISSUE TITLE
M3: Refactor Deprecations - Search for use of `choices` and ensure key/value pair is correct

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8070]
Mautic 2 is dependent on the BC Break introduced in 2.7 and thus needs to be searched and replaced with key => value pair of label => value with the `choices_as_values` as true so that it's testable in M2

In Symfony 2.7 a small BC break was introduced with the new choices_as_values option. In order to have the choice values populated to the html value attribute you had to define the choice_value option. This is now not any more needed.

Before:
```
$form->add('status', 'choice', array(
    'choices' => array(
        'Enabled' => Status::ENABLED,
        'Disabled' => Status::DISABLED,
        'Ignored' => Status::IGNORED,
    ),
    // choices_as_values defaults to true in Symfony 3.0
    // and setting it to anything else is deprecated as of 3.0
    'choices_as_values' => true,
    // important if you rely on your option value attribute (e.g. for JavaScript)
    // this will keep the same functionality as before
    'choice_value' => function ($choice) {
        return $choice;
    },
));
```
After:
```
$form->add('status', ChoiceType::class, array(
    'choices' => array(
        'Enabled' => Status::ENABLED,
        'Disabled' => Status::DISABLED,
        'Ignored' => Status::IGNORED,
    )
));
```

**Comment by escopecz** [comment]
@mtshaw3 this is meant to be done after all bundles refactoring has been done. I will add it to the has dependencies column as Ondrej made the same move :)
