### ISSUE TITLE
Send form results to different users based on conditional logic 

### ISSUE THREAD

**Issue by ineedhelp2018** [mautic/mautic#8077]
Does this already exist?

I have created a campaign for the form sign up. The campaign filters different emails to go out that is based on the form dropdown value. 

There are multiple users that the form results must go to within the company but it doesn't actually send the form results when pulled through in a campaign, it shows the form fields are there but doesn't pull the actual data through.

Does it exist already? (I feel it would do just I'm missing something here).

If not is there a way to achieve this?

To give some context, it's based on people applying to sign up to different locations of a fitness company. So rather than the owner getting all the emails and routing them to the right people, it would be easier when people apply to sign up or for a call back that it gets routed to the right person first time. 

Thank you

**Comment by RCheesley** [comment]
Please ask such questions at https://forum.mautic.org. Github is the place for bugs and issues, the forum is the place for support and questions :)
