### ISSUE TITLE
M3: Refactor EntityFieldsBuildFormTrait to support form type by FQCN

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8084]
In refactoring the Mautic\CoreBundle\Form\Type\TelType, `\Mautic\LeadBundle\Form\Type\EntityFieldsBuildFormTrait` expects that the field type matches the form type which throws an exception that the form type doesn't exist. https://github.com/mautic/mautic/blob/master/app/bundles/LeadBundle/Form/Type/EntityFieldsBuildFormTrait.php#L84 will have to figure out how make this work.

**Comment by escopecz** [comment]
PR: https://github.com/mautic/mautic/pull/8237
