### ISSUE TITLE
M3: Refactor BuilderTokenHelper away from MauticFactory

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8088]
\Mautic\CoreBundle\Helper\BuilderTokenHelper is dependent on MauticFactory and thus needs to be refactored to a service instead in order to use dependency injection.

**Comment by escopecz** [comment]
Note: Try to use https://github.com/mautic/mautic/pull/8148 as a base as it touch related code

**Comment by escopecz** [comment]
Related PR: https://github.com/mautic/mautic/pull/8160
