### ISSUE TITLE
Laravel and Mautic API integration - When pushing data into mautic, mautic requires log in ? 

### ISSUE THREAD

**Issue by ineedhelp2018** [mautic/mautic#8090]
Currently trying to integrate Laravel and mautic. API is working and shows successful integration however when pushing the data through, Mautic requires a log in therefore can't push it through.
I have cleared cache. Any ideas what may be missing?
Thanks

**Comment by RCheesley** [comment]
Please ask this on the development area at https://forum.mautic.org. Forums for questions and support, github for issues and bugs :)
