### ISSUE TITLE
500 (Internal Server Error) when submitting forms

### ISSUE THREAD

**Issue by cedoe** [mautic/mautic#8092]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2.24
| Browser | Chrome 78.0

After updating Mautic from 2.15.0 to 2.15.3 none of our forms are working anymore. When submitting a form it is stuck in 'Please wait...' and the browser's debug console shows this error message:
`POST https://****/mautic/form/submit?formId=2 500 (Internal Server Error)`

This happens with the existing and newly created forms.

I have tried clearing the Mautic cache, 'Rebuild Cache' under Components->Forms, run `mautic:assets:generate`, go back to Mautic 2.15.2 and 2.15.1.

After reverting to version 2.15.0 the forms are working again.

I would assume the internal server error means that something in the server configuration is messed up.

### Steps to reproduce
1. Update to a Mautic version higher than 2.15.0
2. Submit form data
 
### Log errors

`[2019-11-04 15:26:47] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.date_added AS date_added_2, t0.client_info AS client_info_3, t0.device AS device_4, t0.device_os_name AS device_os_name_5, t0.device_os_shortname AS device_os_shortname_6, t0.device_os_version AS device_os_version_7, t0.device_os_platform AS device_os_platform_8, t0.device_brand AS device_brand_9, t0.device_model AS device_model_10, t0.device_fingerprint AS device_fingerprint_11, t0.tracking_id AS tracking_id_12, t0.lead_id AS lead_id_13 FROM lead_devices t0 WHERE t0.lead_id = ? AND t0.device = ? AND t0.device_brand = ? AND t0.device_model = ? LIMIT 1' with params [289, "desktop", "", ""]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.tracking_id' in 'field list'" at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 71 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.date_added AS date_added_2, t0.client_info AS client_info_3, t0.device AS device_4, t0.device_os_name AS device_os_name_5, t0.device_os_shortname AS device_os_shortname_6, t0.device_os_version AS device_os_version_7, t0.device_os_platform AS device_os_platform_8, t0.device_brand AS device_brand_9, t0.device_model AS device_model_10, t0.device_fingerprint AS device_fingerprint_11, t0.tracking_id AS tracking_id_12, t0.lead_id AS lead_id_13 FROM lead_devices t0 WHERE t0.lead_id = ? AND t0.device = ? AND t0.device_brand = ? AND t0.device_model = ? LIMIT 1' with params [289, \"desktop\", \"\", \"\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.tracking_id' in 'field list' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.tracking_id' in 'field list' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.tracking_id' in 'field list' at /var/www/html/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Please follow the steps here: https://www.mautic.org/docs/en/tips/update-failed.html

It seems there are some issues with database fields missing which sounds like an incomplete/failed update.
