### ISSUE TITLE
doctrine schema update error because of custom field with alias "segment"

### ISSUE THREAD

**Issue by carlos-moreira** [mautic/mautic#8093]
### Steps to reproduce

1. Create a custom field with alias 'segment'
2. Execute the command `php /var/www/html/app/console doctrine:schema:update --force`

Error message:
```  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'CREATE INDEX segment_search ON leads (segment)':

  SQLSTATE[42000]: Syntax error or access violation: 1069 Too many keys specified; max 64 keys allowed
```

### Steps to fix (hotfix)
1. Delete this custom field.

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.0.33-0+deb9u1
| Browser | 70.0.1 (64-bit)

**Comment by RCheesley** [comment]
Does this happen with any other alias or just using segment? I wonder if it's some kind of protected phrase, given its importance in Mautic.

**Comment by carloshmm** [comment]
@RCheesley I do have a lot of custom fields with other aliases and none of them are causing any trouble, I had 2 Mautic environments running with the same problem, I just removed this alias from them and the update passed. I think it would be necessary more tests in other environments, it is a simple test:
1. Create a custom field with alias 'segment'.
2. Run the command  `php /var/www/html/app/console doctrine:schema:update --force`

I won't trust only my tests, It would be better if someone else could reproduce the same error.

**Comment by npracht** [comment]
This must be checked as a forbidden alias or we should fix that somehow. It is a bug.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
