### ISSUE TITLE
M3: Remove CommonSubscriber and do direct dependency injection

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8094]
Many subscribers extend CommonSubscriber just to get access to some common dependencies whether used or not. Those subscribers should be refactored to dependency injection with just what they are using. 

Example https://github.com/mautic/mautic/blob/4b46c63e08ce8907c195e0cbb7c20d41dadf5f77/app/bundles/EmailBundle/EventListener/PageSubscriber.php#L23

Depends on https://github.com/mautic/mautic/issues/8100

**Comment by escopecz** [comment]
PR: https://github.com/mautic/mautic/pull/8148
