### ISSUE TITLE
Refactor uses of \Mautic\CoreBundle\Doctrine\Helper\SchemaHelperFactory 

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8097]
There are various uses of \Mautic\CoreBundle\Doctrine\Helper\SchemaHelperFactory but uses of this need to be refactored to use the applicable schema helper service (TableSchemaHelper, IndexSchemaHelper, and/or ColumnSchemaHelper).

**Comment by p365labs** [comment]
@alanhartless this morning as it seems a quick one I've tried to remove SchemaHelperFactory, if it's ok 4 u and @escopecz I'll take it.

**Comment by escopecz** [comment]
That'd be great! I think we can still merge it even though M3-beta is out. Unless someone disagrees.

**Comment by p365labs** [comment]
good today I'll work on it I have a couple of things to fix and it's done
