### ISSUE TITLE
Create New company option disapear if you enter letters in the company field in contact edit page

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#8101]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When you create a contact, if you enter some letter to search for a company in the company field and then you erase what you type. the select option "Create New" disapear from the field. 

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1. Create a new contact and stay on the edit page
![image](https://user-images.githubusercontent.com/49391402/68202123-65045880-ffc3-11e9-9239-c941c0d67d3d.png)
2. Clic on the company field and see the "Create new" option
![image](https://user-images.githubusercontent.com/49391402/68202107-57e76980-ffc3-11e9-9603-636197d75575.png)
3. In the edit page enter some letters in the company field
![image](https://user-images.githubusercontent.com/49391402/68202172-78afbf00-ffc3-11e9-893d-7115f85dbe74.png)
4. Erase what you just enter without validating with enter
5. Clic again in the field > you see the "Create New" option but if you click it it just vanished and do nothing

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
I cannot reproduce it, I tried many ways

![captured (1)](https://user-images.githubusercontent.com/462477/68209246-38583d00-ffd3-11e9-9eb4-30f85c732dbc.gif)

**Comment by florentpetitjean** [comment]
The edit company page open when you click after erasing ?  Because you can see the option but clicking it do nothing for me.

**Comment by kuzmany** [comment]
@florentpetitjean I got it. Looks ugly :(

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/8107
I noticed another issue during the tests, I fixed it too.
