### ISSUE TITLE
Mautic does not support PHP version 7.2.22 at this time.

### ISSUE THREAD

**Issue by hendrikhendrik** [mautic/mautic#8110]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by hendrikhendrik** [comment]
upgrage from php 5.6 to 7.2 found mautic error. have see https://github.com/mautic/mautic for solustion but still not understand how to solve. help

**Comment by RCheesley** [comment]
Please post support requests at https://forum.mautic.org providing full details requested in the post template.
