### ISSUE TITLE
Form field condition always return true when old submissions satisfies the condition

### ISSUE THREAD

**Issue by trsenna** [mautic/mautic#8111]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | No
| Enhancement? | No

## Description:

I believe it's a bug but I'm new to Mautic, so maybe it's a expected behaviour for you. In the campaign builder when creating conditions using submitted form fields the condition will return true when exists older submitted data that satisfies the condition (submitted by the same contact). I have already tried with hidden and select fields. With both the error happens.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | v2.15.2
| PHP version | 7.1.33

### Steps to reproduce:
1. Create a form with the fields like name, email that persists in contact
2. In the form add a field (Select Type) named "course". It should not link to a contact field
3. The course field must contain at least two options, like for example: course-php, course-java
4. Create a campaign that uses the created form as source. Also check that it 'allows contacts to restart the campaign'
6. Create a condition in the campaign that uses the Form field condition
7. The condition must check if the course is equals to 'course-php'
8. If course equals to 'course-php' an action should add +1 point to the contact (or send an e-mail)
9. Save everything, and now open the form to submit data with it. Make sure that the campaign is published
10. Fill the form but in Course field choose the 'course-php' option
11. Trigger the campaign from command line or cron
12. Make sure +1 point was added to the contact
13. Now fill the form with same data (same contact) but choose the 'course-java' option
14. Trigger the campaign from command line or cron
15. **Check that contact has +1 point added, but I did not added this action for course-java in campaign-builder. This is the bug.**
 
### Some extra information: 

I uploaded some screenshots that maybe can help. In contact-history.png I have a form submitted before publishing the campaign at 7:57. At 7:58 another form was submitted but with the campaign published. The selected field in the second submit was 'rh' but the condition checking if the values was 'cursos' returned true. Probably this happend because the data was submitted right before at 7:57

![campaign-builder](https://user-images.githubusercontent.com/177555/68340769-d2001700-00c5-11ea-92b4-769c04ff8c16.png)
![campaign-builder-condition](https://user-images.githubusercontent.com/177555/68340770-d2001700-00c5-11ea-9675-23c84a3bc608.png)
![contact-history](https://user-images.githubusercontent.com/177555/68340771-d298ad80-00c5-11ea-9b01-7ecdec7eb6d0.png)
![submitted-forms](https://user-images.githubusercontent.com/177555/68340772-d298ad80-00c5-11ea-9d73-a6444c709899.png)

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by trsenna** [comment]
Hi,

I did the test with Mautic 3.0.1 today and the behavior I have reported continues to happen.

**Comment by RCheesley** [comment]
@trsenna thanks for reporting back and sorry for the delay in replying!
