### ISSUE TITLE
How to Change Date Feild format in Forms

### ISSUE THREAD

**Issue by NipunReddy555** [mautic/mautic#8112]
## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | V2.8.2
| PHP version | 7.0
| Browser | Chrome, Firefox

### Steps to reproduce
1. Create a form with field type "Date".
2. Create an action "send Form Results".
3. Submit the form. 
4. Go to results page. Here the value of date field is formatted in  YYYY-MM-DD and the Form results in email notification is also formatted in YYYY-MM-DD.
But I need it to be  MM-DD-YYYY format, and I don’t know where to format this.
Can anybody help me? Thanks.

**Comment by npracht** [comment]
Hi @NipunReddy555 !
Please read the documentation https://www.mautic.org/docs/en/emails/manage_emails.html chapter `Date Format`
