### ISSUE TITLE
Some Segment Filters options increase drastically CPU consuming

### ISSUE THREAD

**Issue by maxitromer** [mautic/mautic#8113]
| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2
| Browser | Chrome

My mautic production instance have a list with 260.000 subscribers and I was having to increase the server capacity in processor and in hard disk size a lot in the last time.

Thats why I start testing why mautic is consuming so much resources and I find that the segments that has filters takes several minutes to run (about 40 for every segment) and the other "non filtered segments" only seconds.

The most strange here is that this filtered segments takes the sames 40 minutes to run if they have to process 10 or 5000 contacts.

![08-11-2019 - 09:45:24 - screenshot](https://user-images.githubusercontent.com/6311835/68477617-aa679680-020c-11ea-93f2-561a9d4695e7.png)

Seems that every time the cron jobs run all the contacts in my DB must be processed instead only the contacts that needs to be added or removed.

This makes cronjobs runs ones over the others and increase drastically the CPU consuming.

I think this is a bug.

I think the correct way to solve something like this is not only solving this bug but the way mautic works with cronjobs that doesnt solve the run-over cronjobs and leave this task to the end user.

The end user is a marketer and doesnt know about php and crons and the internal task of the app they use.

Maybe Mautic can model something like the Wordpress cronjobs, that users even know that exist but work amaizinglly well in the dark to offer and incredible experience to the guy who only needs a blog or a website.

### Steps to reproduce

1. Config a segment like this (with or without custom fields):

![07-11-2019 - 19:25:13 - screenshot](https://user-images.githubusercontent.com/6311835/68433029-5d47de00-0194-11ea-8147-f7932b3153dd.png)

2. Run in CLI:

`php .../app/console mautic:segments:update --no-interaction --no-ansi`
 
3. To see this issue appear you will need to run the cronjob more than once (new segments runs fine the first time) and preferible with a big size list of contacts in your instance.

**Comment by TiagoRodrigues** [comment]
Same here with a 100k contacts lists.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by maxitromer** [comment]
I can't sorry.

This still happens on my 2.15.3 mautic instance but I'm not able to reproduce the same tests in the new version because I'm not using mautic 3.0.1 in production.

**Comment by RCheesley** [comment]
OK, if you can test locally or when you do a test migration it would be super helpful!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
