### ISSUE TITLE
Add new regions to Amazon SES configuration options

### ISSUE THREAD

**Issue by ci2014** [mautic/mautic#8118]
A while ago Amazon introduced Amazon SES in Frankfurt, EU Central 1

The Mail server is: email-smtp.eu-central-1.amazonaws.com

Unfortunately, it is missing in the dropdown in the email settings of mautic.

Any chance to get this updated?

Thank you.

**Comment by virgilwashere** [comment]
Actually,  there are now 6 regions.


## Announcement

<https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-ses-is-now-available-in-three-additional-aws-regions/>

> Amazon Simple Email Service (Amazon SES) is now available in the Asia Pacific (Mumbai), Asia Pacific (Sydney), and EU (Frankfurt) Regions, in addition to the US East (Virginia), US West (Oregon), and Europe (Ireland) regions.

## SES regions

<https://docs.aws.amazon.com/general/latest/gr/rande.html#ses_region>

**Comment by bob-swinkels** [comment]
According to https://docs.aws.amazon.com/ses/latest/DeveloperGuide/regions.html#region-receive-email it seems that the new regions don't support receiving, maybe something to keep in mind.

**Comment by dorukgezici** [comment]
Nobody cared to fix this? ):

**Comment by RCheesley** [comment]
I've just changed the title to reflect that there's more than one region to be added :)

**Comment by mgnanaprakash11** [comment]
Oops. Still not added. Add the regions ASAP.

**Comment by cristianuibar** [comment]
Please fix this.

**Comment by mattnelsonuk** [comment]
+1 I need email-smtp.eu-west-2.amazonaws.com

Would a text box be better than a dropdown? Is there any reason why you need to give the options?

**Comment by RCheesley** [comment]
Hi folks, there is a pull request to address this which needs testing. Take a look at [Mautibox](https://mautibox.com/8735) and test for yourselves. 

Please report back here by clicking on files changed [on the PR](https://github.com/mautic/mautic/pull/8735/files) and then review changes, selecting approve and adding a comment if this works.

**Comment by prabhucbe** [comment]
+ email-smtp.ap-south-1.amazonaws.com

Please add this region too

**Comment by romancretnik** [comment]
Hi, if anyone else has this problem in Mautic - this is a simple solution for any Amazon SES region. 

Instead of waiting for a new Amazon SES dropdown in the Email Settings of Mautic just choose "Other SMTP Server". 

The credentials you need to use are stored in AWS SES Management Console under "SMTP Settings".

Example:
Host: paste the url of the selected server (e.g. email-smtp.eu-central-1.amazonaws.com)
SMTP encryption type: TLS
Port: 25 (if that doesn't work try 465, 587 or 2587)
SMTP Authentication mode: Login

**Comment by wise-gorilla** [comment]
@RCheesley I think this issue can be closed since it solved on PR #9005 and all avilable 14 regions got added for both SMTP and API.

**Comment by RCheesley** [comment]
@Wise-Gorilla I have linked the PR to the issue, when it is merged into staging the magic 🧙‍♂️ at Github will close the issue automagically! ✨
