### ISSUE TITLE
Attempted to call an undefined method named "getLine"

### ISSUE THREAD

**Issue by bookin** [mautic/mautic#8119]
When I try use `php app/console cache:clear` I see error  `Attempted to call an undefined method named "getLine" of class "Twig_Node_Expression_Constant"` - https://prnt.sc/pvj6n1

Problem in the file `/vendor/symfony/twig-bridge/Node/SearchAndRenderBlockNode.php` line 40
Insted method `$lineno = $label->getLine();` should be `$lineno = $label->getTemplateLine();`
So seems problem with version of `symfony/twig-bundle` package

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2

**Comment by oytuntez** [comment]
If you enforce >3 twig-bundle version, it seem to be work:

```
"symfony/twig-bundle": "~3.0",
```

**Comment by nickveenhof** [comment]
I'm seeing this today while doing a composer install of the develop branch. Trying to see if we can fix this.

**Comment by nickveenhof** [comment]
Actually, the thing that fixes this is adding     "symfony/twig-bridge": "2.8" to the composer.json. will make a PR.

**Comment by npracht** [comment]
@bookin please test #8119

**Comment by oytuntez** [comment]
Last week during our migration to 2.16, we experienced a good amount of dependency conflicts with Twig packages in Mautic `staging`. We ended up removing our `require-dev` and use `"symfony/twig-bundle": "~3.1.0",`.

Just FYI.

**Comment by nickveenhof** [comment]
Moving to 3.0 doesn't make sense as you are based on symfony 2.x. Try my suggestion, pretty sure that will work as well.

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.0.2 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
