### ISSUE TITLE
Modal component closing on click release event

### ISSUE THREAD

**Issue by jonathands** [mautic/mautic#8123]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

Some modal windows (Eg: Components > Forms > Actions ) are closing when the mouse is released (probably onMouseUp) , which leads to users losing the data being typed, this often happens when someone clicks near the end of a form component as it's normal for users to drag a little bit.

![click-release-annoying](https://user-images.githubusercontent.com/959141/68764098-cd24f100-05f8-11ea-971c-79993306d6ec.gif)

| Q   | A
| --- | ---
| Mautic version | v2.16.0-dev
| PHP version |  7.2
| Browser |  78

### Steps to reproduce
1. Click inside the modal component and release outside the component area
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by jonathands** [comment]
I know this seems to be a bit of a nitpick, but this usability issue has arose with me and 3 of my coworkers. I'm going to fix this on my test environment and try my hand at fixing it.

**Comment by maxitromer** [comment]
This apperars not only in forms but in campaigns and when you send an email to a subscriber inside their profile.

Will be amaizing if could be solved.

**Comment by RCheesley** [comment]
Closing as the is not reproduced in Mautic 3.x
