### ISSUE TITLE
Contact fails to load: Unserialize class erroneously rejects string

### ISSUE THREAD

**Issue by enableit** [mautic/mautic#8126]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version |  7.0
| Browser | Any

### Steps to reproduce
1. Capture a page hit containing o:
2. Try to load contact linked to hit
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

When a web page has a title that contains the string 'o:', the contact who hits that page (if the hit is registered in Mautic), will fail to load due to the blunt way the unserializer class checks for the presence of an object in the unserialize string.

The current test is:

if (stripos($serializedString, 'o:') !== false) {

I would recommend a regex instead, for instance:

if (preg_match('/o:\d+:"[a-z0-9_]+":\d+:{.*?}/i', $serializedString) !== 0) {

File app/bundles/CoreBundle/Helper/Serializer.php

**Comment by enableit** [comment]
File is app/bundles/CoreBundle/Helper/Serializer.php - apologies for not including in original report.

**Comment by npracht** [comment]
Hi @enableit fixed by #8142
I'm closing this in favor of #8158 i think it is the same issue.
