### ISSUE TITLE
Ubuntu 19.10 PHP 7.3.11 support?

### ISSUE THREAD

**Issue by cspenn** [mautic/mautic#8131]
Received this today after an upgrade to the server:

```
Mautic does not support PHP version 7.3.11-0ubuntu0.19.10.1 at this time. To use Mautic, you will need to downgrade to an earlier version.
```

Is support for 7.3.11 coming soon? Thanks!

**Comment by npracht** [comment]
Hi @cspenn !
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.

Moreover, we're currently working on the Mautic 3.0 version and that will be updated at that time :)

Thanks for contributing!

N.
