### ISSUE TITLE
Replace usages of deprecated methods in LeadModel and refactor their usages

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#8138]
There are several methods in LeadBundle that are marked as deprecated but also used elsewhere. Each deprecation message contains a hint what method replaces the deprecated one. 

Build the PR on top of https://github.com/mautic/mautic/pull/8137

Delete LegacyLeadModel afterwards as it won't be used anywhere.

**Comment by dongilbert** [comment]
PR Merged
