### ISSUE TITLE
CRM integration (salesforce) cannot auth

### ISSUE THREAD

**Issue by evenloooo** [mautic/mautic#8146]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Cannot connect to Salesforce, there is error message: `TLS 1.1 has been disabled in this organization. Please use TLS 1.2 or higher when connecting to Salesforce using https.`, it seems Salesforce disabled SSL 1.1 https://help.salesforce.com/HTViewSolution?id=000221207

| Q   | A
| --- | ---
| Mautic version | 2.16.0-dev
| PHP version | 7.0.33
| Browser | Chrome 78.0.3904.108 (Official Build) (64-bit)

### Steps to reproduce
1. In Salesforce, create an App, and fill Mautic callback url with https
2. In Mautic, go to plugins, fill `Consumer ID`, `Consumer Secret`, click authorize App 
 
### Log errors
There is error message: `TLS 1.1 has been disabled in this organization. Please use TLS 1.2 or higher when connecting to Salesforce using https.`
![image](https://user-images.githubusercontent.com/9351031/69414864-851b7200-0d4e-11ea-89ea-fab4e0a38dfb.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
fixed by https://github.com/mautic/mautic/pull/7814
