### ISSUE TITLE
Q&A : Is it possible to set dateAdded field in contact through the API?

### ISSUE THREAD

**Issue by jitheshkt** [mautic/mautic#8152]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A

## Description:
Hi, Is it possible to set `dateAdded `manually when creating contact through the API? Currently, it automatically takes the current date or the first identified date. I am migrating old contacts from another marketing tool to Mautic. It would be great if this is possible because then I can understand how old is the customer with us.

**Comment by RCheesley** [comment]
Please post questions and support requests at https://forum.mautic.org :)
