### ISSUE TITLE
Campaigns emails not sending. Please help?

### ISSUE THREAD

**Issue by Bill2020** [mautic/mautic#8156]
## Bug Description
Hello everyone, I know that this is an "open source" software and since that is the case I can't expect the world from the community. But with that being said, any advice that I can get to fix this issue would be greatly appreciated.

My issue is that campaigns are not working. I can send test emails, as well as emails to contacts directly, so Amazon SES is not the issue.

I see this issue a lot but nobody's issue seems to be exactly like the one that I have.
The cron jobs that I have installed are here:

 0 | 0 | 1 | 1 | * | /usr/local/php71/bin/php /home/mautic/email/app/console mautic:maintenance:cleanup > /dev/null 2>&1
 */4 | * | * | * | * | /usr/local/php71/bin/php /home/mautic/email/app/console mautic:campaigns:trigger > /dev/null 2>&1 
 */10 | * | * | * | * | /usr/local/php71/bin/php /home/mautic/email/app/console mautic:campaigns:rebuild > /dev/null 2>&1 
 */6 | * | * | * | * | /usr/local/php71/bin/php /home/mautic/email/app/console mautic:fetch:email > /dev/null 2>&1
 */7 | * | * | * | * | /usr/local/php71/bin/php /home/mautic/email/app/console mautic:campaigns:update > /dev/null 2>&1 
 */9 | * | * | * | * | /usr/local/php71/bin/php /home/mautic/email/app/console mautic:webhooks:process > /dev/null 2>&1
 */20 | * | * | * | * | /usr/local/php71/bin/php /home/mautic/email/console mautic:leadlists:update > /dev/null 2>&1
 */15 | * | * | * | * | /usr/local/php71/bin/php /home/mautic/email/app/console mautic:segments:update > /dev/null 2>&1
 */8 | * | * | * | * | /usr/local/php71/bin/php /home/mautic/email/app/console mautic:email:process > /dev/null 2>&1
 */29 | * | * | * | * | /usr/local/php71/bin/php /home/mautic/email/app/console mautic:broadcasts:send > /dev/null 2>&1
 */2 | * | * | * | * | /usr/local/php71/bin/php /home/mautic/email/app/console mautic:email:fetch > /dev/null 2>&1
 */5 | * | * | * | * | /usr/local/php71/bin/php /home/mautic/email/app/console mautic:iplookup:download > /dev/null 2>&1

Just like everybody else states, I have been searching for a solution everywhere online for 3 days straight. I looked on slack, mautic community forums, youtbe and here, and I haven't seemed to find a solution that works.     

| Mautic version | v2.15.3
| PHP version | 7.1
| Browser | chrome/opera/firefox

### Steps to reproduce
I have my campaign set up very basic to trigger an email as soon as an email comes through my form and each one simply lands in the "pending" slot and nothing else happens from there.
 
### Log errors
I checked for the log errors in the app folder and there were none, also in the PHPmyadmin logs and there were none there either.

I'm not a huge "techy" person, (I know enough to get myself into trouble), so whoever responds to me could you please give me the dummy version of your explanation? lol 
Like where exactly do I look to raise my PHP limit...

Thank you in advance. :)

**Comment by Bill2020** [comment]
Mautic would be great if it actually worked as advertised, but it looks to me like the community is all but dead, and the platform is too buggy.

**Comment by RCheesley** [comment]
Please request support on the forums, rather than GitHub. You can search and find answers to many questions there already.
