### ISSUE TITLE
Custom field is updated after 'Accessed from IP'

### ISSUE THREAD

**Issue by mimikama** [mautic/mautic#8168]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

| Mautic version | v2.15.3

Hello everyone,
we have an issue with a custom field of the mautic contacts that is updated automatically on its own after getting in the Audit log of the contact: 
`Accessed from IP`

Did anybody have the same issue before?
Why is this happening?

Note: 
In the Settings>> Custom Fields >> myCustomField >> Publicly updatable >> No
Is this related to the updated custom field we have?

### Steps to reproduce
1. We created new contacts with myCustomField value to Yes (1)
2. After we get in the `History` of the contact:

-Page hit | Today, 6:16 pm
-Accessed from IP | Today, 6:16 pm
-Email read | Yesterday, 6:16 pm
-Email sent | Yesterday, 5:01 pm

3. In the meantime we get in the `Audit log` of the contact:

-System | Contact updated | Yesterday, 6:16 pm
-- | -- | --
Field/Object | New Value | Old Value
hadregistered |                | 1
ipAddresses | . . . 

-The contact was accessed from: ip    , Yesterday, 6:16 pm
-Field/Object | New Value | Old Value
myCustomField | 1 |                             ,November 15, 2019 6:27 pm

-EmailDaemon ApiAuthorization | Contact updated | November 15, 2019 6:39 pm
-- | -- | --
Field/Object | New Value | Old Value
hadregistered | 1 |    
 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Please check this PR: https://github.com/mautic/mautic/pull/7595 which is pending a test - shout if you need any assistance with testing the PR and leave any comments on the PR :)
