### ISSUE TITLE
Add v3 PHP extensions to Composer config

### ISSUE THREAD

**Issue by szepeviktor** [mautic/mautic#8171]
To prevent installing on systems without these PHP extensions.

```json
    "require": {
        "ext-zip": "*",
        "ext-xml": "*",
        "ext-mcrypt": "*",
        "ext-imap": "*",
        "ext-mailparse": "*",
    },
    "suggest": {
        "ext-openssl": "Symmetric and asymmetric encryption and decryption",
        "ext-zend-opcache": "OPcache, precompiled script bytecode stored in shared memory",
        "ext-apcu": "APC User Cache",
        "ext-memcached": "High-performance, distributed memory object caching",
    }
```

Related #6901

What do you think?

**Comment by directpromo** [comment]
get error:


    - The requested PHP extension ext-mcrypt * is missing from your system. Install or enable PHP's mcrypt extension.

    - The requested PHP extension ext-mailparse * is missing from your system. Install or enable PHP's mailparse extension.

**Comment by szepeviktor** [comment]
I do not really remember how I've put together the above list.

Maybe from here https://github.com/mautic/mautic/blob/bed2b402092452a8b4363478cad8af5937b480a8/app/bundles/InstallBundle/Translations/en_US/messages.ini#L16-L22

**Comment by szepeviktor** [comment]
or here?
https://github.com/mautic/mautic/tree/3.x#mautic-requirements

**Comment by clemens-tolboom** [comment]
@szepeviktor not sure what your issue **summary** is :-0

Anyways https://github.com/mautic/mautic/blob/f59e78392410705bdb87ad5513f42e13c33a2e20/app/bundles/InstallBundle/Translations/en_US/messages.ini#L13-L18 has new content

PHP extensions requirements from that file are

```
curl
fileinfo
imap
mbstring
openssl
zip
```

and https://github.com/mautic/mautic/tree/3.x#mautic-requirements has no requirements.

It would be nice to know these requirement (`php-imap` seems the only odd one on my Homebrew@Mac?) beforehand when trying to install locally.

**Comment by szepeviktor** [comment]
> not sure what your issue **summary** is :-0

It is a snippet to be included in `composer.json`
so you can check for PHP extensions at Composer install time.

**Comment by szepeviktor** [comment]
require -> mandatory
suggest -> optional

**Comment by clemens-tolboom** [comment]
It was a hint to update the summary ;-) [edit]to make a PR out of it[/edit]

**Comment by szepeviktor** [comment]
https://github.com/mautic/mautic/blob/e478a20c31c971cf265951bd92683400a2a66b19/composer.json#L19-L21

seems like 3.x has requirements :(

I SEE! Requirements **section** in the README.

**Comment by szepeviktor** [comment]
> to make a PR out of it

I think I'm not able to stand the pressure emanating from this project.
e.g. those empty lines in composer.json or the inline script in `scripts:`

**Comment by clemens-tolboom** [comment]
When I check https://github.com/mautic/mautic/issues/new/choose those issue template have/need more user input ... you are not explaing in the issue summary what went wrong and why you want those in.

**Comment by szepeviktor** [comment]
It is for your benefit: to prevent installing on systems without those PHP extensions.

**Comment by szepeviktor** [comment]
in the above linked PR:

> Add php ext to composer json to stop certain ide's from complaining, and for consistency.

**Comment by clemens-tolboom** [comment]
What I meant to say is edit https://github.com/mautic/mautic/issues/8171#issue-530081416 and tell the problem and the proposed solution. Or maybe better close this issue and add comments to the PR #6901.

**Comment by szepeviktor** [comment]
Okay, I've just came up with this.

> prevent installing on systems without these PHP extensions

Please decide what to do.
I may send a PR if you provide a list of `require` and `suggest`.

**Comment by RCheesley** [comment]
https://github.com/mautic/mautic-documentation/issues/89 issue added to the docs repo to list out all the requirements in case someone  wants to jump on that :)

**Comment by szepeviktor** [comment]
Simply take your source code

https://github.com/mautic/mautic/blob/b584b356315fea69208daac881541f4c7d01311a/composer.json#L6-L16

ask PHP CompatInfo what extensions are needed

https://github.com/llaville/php-compat-info

and remove default extensions (mainly `php -n -m`)

Done 🍏

**Comment by CybotTM** [comment]
according to phpcompatinfo, the following extensions are used, and should therefore be listed in composer.json:
```
    Extension  REF        EXT min/Max     PHP min/Max
    Core       Core       7.0.2           7.1.0
    Reflection Reflection 5.4.0           7.1.0
    SimpleXML  SimpleXML  5.0.0           5.0.0
 C  apcu       apcu       4.0.0           5.3.0
    ctype      ctype      4.0.4           4.0.4
    curl       curl       5.5.19RC1       5.5.19RC1
    date       date       5.5.0           7.1.0
    dom        dom        5.0.0           5.0.0
    exif       exif       4.3.0           4.3.0
 C  fileinfo   fileinfo   1.0.5-dev       5.3.0
    filter     filter     0.11.0          5.0.0
    gd         gd         4.3.0           4.3.0
    hash       hash       5.6.0beta1      5.6.0beta1
    http       http       4.0.0           4.3.0 => 5.5.38
    imap       imap       5.1.3           5.1.3
    intl       intl       1.0.0beta       5.2.0
    json       json       5.4.0           5.4.0
    libxml     libxml     5.4.0           5.4.0
    mbstring   mbstring   4.4.3           4.4.3
    openssl    openssl    5.3.3           5.3.3
    pcre       pcre       5.3.0           5.3.0
    phar       phar       2.0.0a1         5.2.0
    spl        spl        7.2.0 => 5.2.17 7.2.0beta3
    standard   standard   7.3.0           7.3.0alpha4
    xml        xml        4.0.0 => 7.1.25 4.0.0
    zip        zip        1.6.0           5.3.0
    zlib       zlib       4.0.0           4.0.0
    Total [27]                            7.3.0alpha4 => 5.5.38
```

(Even if built in by default)

**Comment by CybotTM** [comment]
Why is this required?

Because otherwise you cannot automatically and programmatically ensure your built Mautic RE (PHP container) has all required extensions installed.

With the above added, any built of Mautic in an PHP RE without required extensions will fail and prevent releasing/deploying a broken container image

Currently, as a maintainer for such a container image, you have to maintain this extension by yourself, without being able to rely on official (mautic) sources.

**Comment by CybotTM** [comment]
This (#8171) and mautic/mautic-documentation#89  are crucial to enable your community to provide solid OPS for the application when maintaining it.

**Comment by szepeviktor** [comment]
If you need an even sharper knife 🔪 https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/php-env-check.php#L47-L50

**Comment by RCheesley** [comment]
@CybotTM @szepeviktor thanks for the input! We actually have a Strategic Initiative this year to[ implement Composer support fully in Mautic Core](https://mautic.atlassian.net/wiki/spaces/MI/pages/324337710/Composer+Support). We also have another one focused on [improving the installation and upgrade process & documentation](https://mautic.atlassian.net/wiki/spaces/MI/pages/324435990/Improve+the+Installation+and+Upgrade+Process).

I think that the points you raise are valid ones and we do not currently have this documented properly (see https://github.com/mautic/mautic-documentation/issues/89).

If anybody would like to help with either aspects please do jump in. Join us on Slack (https://mautic.org/slack for an invite) on #i-composer-support and #i-install-upgrade for the initiatives and #t-education if you are interested to help us improve our documentation.
