### ISSUE TITLE
Weird log errors

### ISSUE THREAD

**Issue by PublyaDev** [mautic/mautic#8179]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I was having a problem with opening leads #8158, bu that has been worked around for now, but with the workaround, a new log error ocurred, that's probably because I didn't escape the colons properly and the serializer is getting an error.

I'm also having problems with Leads not being created upon converting on a form, but I can't correlate these two issues.

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2
| Browser | Firefox

### Steps to reproduce
1. Have problems opening certain leads because of #8158
2. Apply workaround by escaping colons on page_hits.query column
 
### Log errors

[2019-12-02 16:37:41] mautic.NOTICE: PHP Notice - unserialize(): Error at offset 0 of 427 bytes - in file /var/www/html/mautic/app/bundles/CoreBundle/Helper/Serializer.php - at line 39 {"serializedString":"a;11;{s;10;"page_title";s;57;"Publya - Trading Desk Especializada em Midia Programatica";s;13;"page_language";s;5;"pt-BR";s;13;"page_referrer";s;0;"";s;8;"page_url";s;19;"https;//publya.com/";s;7;"counter";s;1;"0";s;10;"resolution";s;8;"1366x768";s;15;"timezone_offset";s;3;"180";s;8;"platform";s;5;"Win32";s;12;"do_not_track";s;7;"unknown";s;7;"adblock";s;5;"false";s;11;"fingerprint";s;32;"3ac3e85f38fc078e2149ea3ac7cdee84";}","options":{"allowed_classes":false}} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by dcweeks** [comment]
Why do you think this is related to the other one? Just the timing? I don't see any colon or escape in this page title here.  Could it just be a coincidence?   It is only a notice so it is far less important than the critical error thrown by the other issue.  Have more of these appeared in your logs since then, and can you verify that none were appearing before you escaped the colons in the DB?  My gut feeling is that this is unrelated and I am guessing developers will want to know if you are seeing any functionality problems that you can attribute to this.

**Comment by PublyaDev** [comment]
Good question... The timing was what made me think they are related... yet as of today nothing appears in the log...
I'll close it for now since it's not affecting anything, and there are no more logs.
Thanks for your attention.
