### ISSUE TITLE
HTML in signature not working in some cases

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#8181]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you put a signature with HTML code in the signature field,  it displays the signature the wrong way.  I don't know if there some limit for the length of the text in this field ? 
code of the signature : 
 ```
</font>
      <html>
        <head>
          <meta charset="windows-1252" />
        </head>
        <body>
          <table>
            <tr>
              <td valign="middle" style="padding:0 8px 0 0;">
              </td>
              <td valign="middle" style="font-size:80%;font-family: calibri;border-left:3px solid;padding:0 0 0 8px;border-color:#d60f16;">
                <div>
                  <span>
                    <span style="font-size:12.5pt ;color:#d60f16;">
                      <strong>John Doe;
                      </strong>
                    </span>
                    <br />
                      <span style="font-size:11.5pt ;color:#686868;">
                      <strong>Marketing & Communication Executive
                                                                                           </strong>
                    </span>
                  </span>
                  <br />
                  <span style="font-size:11.5pt; color:#686868;">
                    <strong>
                    </strong>
                  </span>
                </div>
                <div>
                  <span>
                  </span>
                </div>
                <div>
                  <span>
                    <span style="font-size:10.5pt;color:#d60f16;">t :&nbsp;
                    </span>
                    <span style="font-size:10.5pt;color:#686868;">01 02 03 04 05    
                    </span>
                  </span>
                  </span>
            </div>
            <div>
              <span>
                <span style="font-size:10.5pt;color:#d60f16;">m :&nbsp;
                </span>
                <span style="font-size:10.5pt;color:#686868;">06 07 08 09 10
                </span>
              </span>    
              </span>
            </div>
          <div>
            <span style="font-size:10.5pt;color:#d60f16;">e :&nbsp;
            </span>
            <span>
              <a href="mailto:imajdoub@olfeo.com  " target="_blank" style="font-size:10.5pt;text-decoration:none;color:#686868;">johan@doe.com 
              </a>
            </span> 
            </span>
          <span>
            <span style="font-size:10.5pt;color:#d60f16;">w :&nbsp;
            </span>
            <span>
              www.johandoe.com
              </a>
            </span> 
          </span>
          <span>
            </div>
          <div>
            <span style="font-size:10.5pt;color:#686868;">1 rue de l'inconnu 75000 Paris
            </span> 
          </div>
          <span>
                    
            </a>
          </span> 
          </td>
        </tr>
      </table>
    </body>
  </html>
 
<br />
 <br />`
```
What we expect to see : 
![image](https://user-images.githubusercontent.com/49391402/70150527-6dc37980-16aa-11ea-9f19-8b45427fa310.png)

What we got  : 
![image](https://user-images.githubusercontent.com/49391402/70150394-3d7bdb00-16aa-11ea-8e49-42f14265d9d6.png)

Step to reproduce : 
. 

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Go into configuration > Email settings
2. Copy the code above in the default signature field : 
![image](https://user-images.githubusercontent.com/49391402/70150647-9c415480-16aa-11ea-80d8-8742fbb90884.png)
3 Validate
4 Create an email  with the {signature} token in it
5 Send the email to a test contact
6 See that the signature display is broken

### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
We noticed that backspace in signature editor is replaced by html `<br />`. So this is a bug but you can handle it by removing backspace in your signature text area.

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
