### ISSUE TITLE
MySQL 8 and invalid date values

### ISSUE THREAD

**Issue by davidbnk** [mautic/mautic#8198]
Since MySQL 8 it will not allow date comparisons with invalid values.

This is a problem when you have a Custom Field with the Date or Date/Time type. Because when you create a segment, and the condition of the segment is that your custom field is empty, Mautic will generate a query like this:

`SELECT ... FROM leads WHERE (mycustomdatefield IS NULL) OR (mycustomdatefield= '')`

But this will give the following mysql error: 

`Incorrect DATETIME value: ''`

If the custom field is of the date type, the comparison should use only the `IS NULL` condition

Mautic version: v2.15.3
PHP version: 7.1.33
MySQL version: 8.0.16

**Comment by davidbnk** [comment]
Related but not the same issue: #7612

**Comment by davidbnk** [comment]
This was a breaking change introduced in MySQL 8.0.16 but not treated as such, mautic works on 8.0.15 and earlier
Discussion here: https://bugs.mysql.com/bug.php?id=93513

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by danclaydon** [comment]
I get the same error on Mysql 8.0.17 running Mautic 3.1.1

**Comment by loscoto** [comment]
I can confirm the same error with Mautic 3.2.2 and MySQL 8.0.22 when having Identified segment filtered by Identified date to be not null. 
`SELECT count(leadIdPrimary) count, max(leadIdPrimary) maxId, min(leadIdPrimary) minId FROM (SELECT DISTINCT l.id as leadIdPrimary, vMerGkjS.lead_id AS vMerGkjS_lead_id FROM leads l LEFT JOIN lead_lists_leads vMerGkjS ON vMerGkjS.lead_id = l.id and (vMerGkjS.leadlist_id = 7) WHERE ((l.date_identified IS NOT NULL) AND (l.date_identified <> '')) AND (vMerGkjS.lead_id IS NULL)) sss':  SQLSTATE[HY000]: General error: 1525 Incorrect DATETIME value: ''`
Changing the date filter to greater than "2000-01-01" resolves the issue.

**Comment by grandfso** [comment]
The error is present in current version of Mautic (v3.2.5). 
When using campaign condition where DATE field is empty: 
https://i.imgur.com/0zpgyDT.png

`mautic.ERROR: CAMPAIGN: An exception occurred while executing 'SELECT l.id FROM v_3_1_2_leads l WHERE (l.id = ?) AND ((l.last_email_sent_date IS NOT NULL) AND (l.last_email_sent_date <> ''))' with params [488801]:  SQLSTATE[HY000]: General error: 1525 Incorrect DATE value: '' [] []`

**Comment by pwned555** [comment]
Confirmed this is still an issue as well when using MySQL.  We actually are using MariaDB on all environments except one and this isn't an issue on them so we updated the one environment to use MariaDB instead.

Note:  This is an issue anywhere you can add a date filter of empty or not empty I believe.  Off the top of my head this should cause issues in Campaigns, Segments, and Reports.

**Comment by karser** [comment]
This PR #9876 fixes this issue, wdyt?

**Comment by kuzmany** [comment]
Fixed for segment filters

https://github.com/mautic/mautic/pull/11124

**Comment by kuzmany** [comment]
Issue still persist on campaign contact field value condition and probably form value condition at least
