### ISSUE TITLE
[feature request] Suppression/Blacklist for email addresses

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#820]
Since mautic can be used for bulk emailing, a suppression list is needed.  A suppression list is essentially a place to add email addresses that will never (ever) be emailed.  

This will be used later on when bounce/spam functionality is added.  

Some example use cases: 
* hard bounced email: added to suppression list right away
* soft bounced email: wait till soft bounced 5 times, then add to suppression list (this number can vary, but 5 is kind of industry standard I think)
* flagged as spam: added to suppression list right away.
* irate customer calls/emails saying never ever email email them again (you would add them manually to the list)

**Comment by alanhartless** [comment]
1.2 will have bounce monitoring of an IMAP account(s) and the ability to manually add lead's to the "do not email" list that the system uses to not send automated email to the user (same list they are added to when they unsubscribe from an email).

**Comment by alanhartless** [comment]
https://github.com/mautic/mautic/pull/797
https://github.com/mautic/mautic/pull/807

**Comment by that0n3guy** [comment]
@alanhartless I saw that, but since I'm still pretty new, I was thinking that unsubscribes were per list (similar to most email marketing platforms).  

Based on what your telling me, unsubscribes are system wide... correct?  If that's the case, then suppression list = unsubscribe list, right?

**Comment by alanhartless** [comment]
I think 1.2.0 introduced support for most of these.  Closing while leaving #822 open for the unsubscribe enhancements.
