### ISSUE TITLE
want to setup soft delete functionality. please advise

### ISSUE THREAD

**Issue by chiragob** [mautic/mautic#8203]
**Please DO NOT report security vulnerabilities here. Send them to security@mautic.com instead.**

What type of report is this:

| Q  | A
| ---| ---
| Bug report? | 0
| Feature request? | 0
| Enhancement? | 1

## Description:
want to setup soft delete functionality.
How to setup a this functionality in mautic
please advise me.
## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 7.1

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
Hi there,

Please ask questions and support requests at https://forum.mautic.org rather than on Github, which is for bug reports.
