### ISSUE TITLE
Error apc_clear_cache with PHP 7

### ISSUE THREAD

**Issue by jesusmr25** [mautic/mautic#8208]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Fatal error with apc_clear_cache function running PHP 7
When you are trying to create a dev environment in Mautic with PHP 7, apc_clear_cache is not working with PHP 7. The new name in PHP 7 is apcu_clear_cache.

You can try to create a function to detect php version to use one or the other one.

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2.22
| Browser | 

### Steps to reproduce
1. Install or upgrade to PHP 7
2. Try to create a dev environment
 
### Log errors
Fatal error: Uncaught Error: Call to undefined function apc_clear_cache() in /var/www/html/index_dev.php:24 Stack trace: #0 {main} thrown in /var/www/html/index_dev.php on line 24

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
I believe this is resolved with the following PR: https://github.com/mautic/mautic/pull/7215 so I will link the two!
