### ISSUE TITLE
How to setup onesignal push request to multiple domains

### ISSUE THREAD

**Issue by souzadavi** [mautic/mautic#8211]
I would like to setup push notification in Mautic, I already did it, but I have multiple domains. Every language has it own domain. I'm getting error, because push notification only work in one domain. There is any work around to setup mautic with push notification in multiple domains (or subdomains)?

thanks in advance.

**Comment by RCheesley** [comment]
Hi there,

Please post support requests and ideas/feature requests at https://forum.mautic.org.
