### ISSUE TITLE
FullContact APIs (v2) will be discontinued on December 31, 2019.

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#8213]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

New generated api key doesn't work at the moment.  API must be migrated to v3

Migrating

https://docs.fullcontact.com/#migrating

Main changes:  

- POST instead of GET 
- Authorization Header with Bearer 

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
@escopecz Does Acquia work on it, or not yet?

**Comment by escopecz** [comment]
It's not used by our customers, so it's not in our backlog.

**Comment by kuzmany** [comment]
Maybe we should remove some plugins and integration in Mautic 3 (maybe also mail transports - same like SMS transports) and get it as separate bundle for community.
It's really hard to maintenance so many APIs, services..

**Comment by escopecz** [comment]
I'd leave it for M4. Otherwise we will never release M3 if we keep adding more tasks to the project.

**Comment by kuzmany** [comment]
I can take removal stuff for Mautic 3 :)
Save us bunch of time in future

**Comment by mohit-rocks** [comment]
I'll be working on upgrading FullContact API to V3

**Comment by npracht** [comment]
You rock

**Comment by mabumusa1** [comment]
Closing in favor of https://github.com/mautic/mautic/pull/8783
