### ISSUE TITLE
Refactor MauticFactory from SubmissionModel

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#8216]

**Comment by RCheesley** [comment]
@escopecz is this still an open task to be completed?

**Comment by escopecz** [comment]
It is. It was planned for M3 refactoring but we had to draw a line because of time constraints and some refactoring tasks did not make it. It is waiting for M4.

**Comment by RCheesley** [comment]
Ok, is that the case for all the issues in the 3.x milestone? If so I'll create the 4.0 milestone and assign them to it :)

**Comment by escopecz** [comment]
Yes, it is. I guess we can rename the 3.x milestone to 4.0
