### ISSUE TITLE
Anonymous > Known Contact Overwrites Partial Address from IP Lookup

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#8233]
If:
- Maxmind or another IP lookup is installed
- An anonymous website visitor gets geocoded by MaxMind and assigned a city/state/country
- The anonymous visitor also exists in the database as a known contact
- The known record for the website visitor has a full address that differs from the geocoded info from IP Lookup
- The anonymous website visitor completes a form or gets assigned an email address to become known

Then:
When the anonymous and known records merge, the physical address info from the IP lookup will be combined with the full address of the known contact record in the database, to potentially create a nonsense address. 

For example...
1. Jim Smith exists in the Mautic database with a full address of 123 Main St, Chicago, IL 63012
2. Jim visits the website on his iPad, where he is not known in Mautic and is assigned a new MTC id to a blank record in Mautic
3. The Maxmind database reverses out Jim's IP address to New York, NY and appends his anonymous record with that city and state
4. Jim completes the newsletter signup form from his iPad, making his anonymous record known and merging it with the previously existing known record
5. Jim's address in Mautic is now 123 Main St, New York, NY 63012 and now he can't receive snail mail from us anymore :(

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2
| Browser | Chrome

### Steps to reproduce
1. Create a record in mautic with the email address of me@mydomain.com and a full and complete address in a city far from where you are
2. In an incognito window, visit the website
3. Inspect your cookies in your incognito window, and lookup the mtc_id in Mautic to verify maxmind has assigned a geographic location different from the full and complete address you entered for step 1
4. In the incognito window, complete a form on the website as me@mydomain.com
5. Take a look at the mautic record created in step 1 and verify that it is partially the address you entered in step 1 and partially the geo location from maxmind you saw in step 3

 
### Log errors
No Errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by stevedrobinson** [comment]
I'm thinking the most straightforward answer is to add some code to prevent a less complete address from ever wiping out part or all of a more complete address. I'm just too rusty of a developer to dig in and submit a PR.

**Comment by kuzmany** [comment]
If this happen after form submit, then this PR https://github.com/mautic/mautic/pull/7818 should fix it.

**Comment by dennisameling** [comment]
#7818 Has been merged for the 2.16 release, so I'm closing this issue. Thanks @kuzmany
