### ISSUE TITLE
Special character ">" and "<" are not usable in Select and Multi-select values in API

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#8235]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you create a Select or Multi-select value via API you can't use the "<" or the ">" character. 

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1. Create a select or multi select field by API
2. Add for example >18yearsold as a value
3. Execute the request and see that there is an error message
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
