### ISSUE TITLE
M3: Enabling rabbitmq or beanstalkd in Mautic 3 results in cache exception 

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8240]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
At face value, it seems that `registerExtension` inside another extension is failing as the extension must be registered before the container is compiled and thus the QueueBundle's MauticQueueExtension has to be refactored. 

| Q   | A
| --- | ---
| Mautic version | 3.0 dev (3.x branch)
| PHP version | 7.2
| Browser | Chrome

### Steps to reproduce
1. The configuration currently does not work without https://github.com/mautic/mautic/pull/8239 and https://github.com/mautic/mautic/pull/8239; but with them it loads so manually merge them or wait till they are merged into 3.x. Alternatively, add `'queue_protocol' => 'rabbitmq',` to your app/cache/local.php and delete var/cache/dev (or prod)
2. Go to the Queue bundle settings in /s/config/edit
3. Enable rabbitmq or beanstalkd and save
4. Notice the exception 
```
Symfony\Component\DependencyInjection\Exception\LogicException: You cannot register extension "OldSound\RabbitMqBundle\DependencyInjection\OldSoundRabbitMqExtension" from "Mautic\QueueBundle\DependencyInjection\MauticQueueExtension". Extensions must be registered before the container is compiled.
```

### Log errors
```
/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:166 at
/app/bundles/QueueBundle/DependencyInjection/MauticQueueExtension.php:39 at Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder -> registerExtension ( object(OldSoundRabbitMqExtension) )
/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:71 at Mautic\QueueBundle\DependencyInjection\MauticQueueExtension -> load ( array(array()), object(MergeExtensionConfigurationContainerBuilder) )
/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39 at Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass -> process ( object(ContainerBuilder) )
/vendor/symfony/dependency-injection/Compiler/Compiler.php:140 at Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass -> process ( object(ContainerBuilder) )
/vendor/symfony/dependency-injection/ContainerBuilder.php:790 at Symfony\Component\DependencyInjection\Compiler\Compiler -> compile ( object(ContainerBuilder) )
/vendor/symfony/http-kernel/Kernel.php:643 at Symfony\Component\DependencyInjection\ContainerBuilder -> compile ( )
/app/AppKernel.php:518 at Symfony\Component\HttpKernel\Kernel -> initializeContainer ( )
/app/AppKernel.php:278 at AppKernel -> initializeContainer ( )
/app/AppKernel.php:110 at AppKernel -> boot ( )
/app/middlewares/CORSMiddleware.php:93 at AppKernel -> handle ( object(Request), '1', true )
/app/middlewares/CatchExceptionMiddleware.php:45 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/Dev/IpRestrictMiddleware.php:66 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/VersionCheckMiddleware.php:55 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/run/src/Stack/run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request) )
/index_dev.php:33 at Stack\run ( object(StackedHttpKernel) )
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by dongilbert** [comment]
Need to update the MauticQueueBundle class to use the `getContainerExtension` method which will access the container in order to get the parameter to see which Queue is enabled. From there, it will return the correct extension class name. do the same check in the compiler pass and bail early if the RabbitMQ queue is not enabled. Finally, always load both configurations into the container (move the content of the beanstalk.php and rabbitmq.php file into the MauticQueueBundle. The configs are namespaced so they shouldn't conflict.)

**Comment by hluchas** [comment]
This is how extensions are registered in standard way :
![Snímek obrazovky 2020-01-09 v 17 10 46](https://user-images.githubusercontent.com/12815758/72084047-19439780-3303-11ea-857c-6440fdd58dc2.png)

How it works:
1. Extension is registered via Kernel (one bundle means one extension class)
2. Container is build and parameters are injected.

Probs:
1. We need params before container is build to decide which extension to use.
2. One bundle can have only one extension.

Simply no way how to do this inside bundle.
https://symfony.com/doc/current/bundles/extension.html

**Comment by dongilbert** [comment]
Could we load the config file directly and get the configured queue bundle? `include ../path/to/local.php`. Or @alanhartless Do you think your work on the container could help with this?

**Comment by alanhartless** [comment]
@dongilbert Not really mainly because @hluchas that is how it behaves today https://github.com/mautic/mautic/blob/37752324550b5dea3ec98869061ed06fc248bf23/app/bundles/QueueBundle/DependencyInjection/MauticQueueExtension.php#L34. But something has changed in Symfony 3 to make that no longer work. Getting whether the parameter to determine if queuing is enabled really a problem.

**Comment by hluchas** [comment]
@alanhartless I see this. I'll try something

**Comment by hluchas** [comment]
TY for hint @dongilbert . This way is/was used in JMSSerializer I thing.

**Comment by hluchas** [comment]
Okay, this is still producing the same error. Moving to pending feedback.

**Comment by hluchas** [comment]
I tested this again and it works well for me. Moving to done
