### ISSUE TITLE
Precision option not working for "number" custom field ending by 0

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#8243]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you set up a "Number" custom field with precision option set to 2 or more ans Round up rounding mode and use it with number like 4,5000 the number will always display 4,5 whatever the precision is set to. 
Works if the final number is not zero. 

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a contact custom field with "Number" type
2. Leave rouding mod to up and set precision to 3
![image](https://user-images.githubusercontent.com/49391402/71006378-8ccbfd80-20e5-11ea-98c5-d9580798ea05.png)

3. Create a contact and fill the Number field with 4,5000 value
4. See in the contact panel or in an email token on this field that the displayed value is 4.5
 
![image](https://user-images.githubusercontent.com/49391402/71006622-e0d6e200-20e5-11ea-9115-8b3da47b6cd7.png)

### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
@florentpetitjean 

@escopecz  Does it bug?

I think this should works properly.

4.12345 change to 4.123
4,1000 change to 4.1 
For me it's correct

**Comment by escopecz** [comment]
I also think it works correctly. If you expect that 4,5000 with precision of 3 should be 4,500, then no. It's not precision, it's number format. 4,500 = 4.5. Adding the zeros does not change the value.

**Comment by npracht** [comment]
agree with @kuzmany @escopecz 👍 just a mathematic convention.
