### ISSUE TITLE
SAML Single Sign On problems in 2.15.3

### ISSUE THREAD

**Issue by rodolfomatos** [mautic/mautic#8245]
## Bug Description
According to the documentation ( https://www.mautic.org/docs/en/authentication/saml.html ), the "Entity ID"  will be site URL. However, if the URL is something like "https://mydomain/mautic1", the "Entity ID" will be changed to "https://mydomain" instead.
That is a big problem for me, since I'm configuring a domain with several mautic installations (e.g. "https://mydomain/mautic1", "https://mydomain/mautic2", "https://mydomain/mautic3") using the same IDP. That means that all installations are indistinguishable from each other.

There is no logs on this, because it seems to work "normally".

I've tried to manually change  'saml_idp_entity_id' in local.php, but to no avail...

Other small glitches, are these:
1. using the zip file for production installations, I needed to install composer's libraries "lightsaml/lightsaml", "lightsaml/symfony-bridge", "lightsaml/sp-bundle" to make SAML SSO work, and "mautic/api-library" for API HTTP basic auth . Shouldn't they be present by default?
2. uploading the "Identity provider metadata file", the "X.509 certificate", or "Private key" gives a error 500. (The reason seems to be an Uncaught PHP Exception Exception: "Serialization of 'Symfony\Component\HttpFoundation\File\UploadedFile' is not allowed", as you can see in the logs snippet that I've included). (Refreshing the page, seems to be everything ok, though.)

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 7.2.24-0ubuntu0.18.04.1
| Browser | Chrome (Linux) 73.0.3683.86 (64 bits)

### Steps to reproduce
1. install mautic (from zip file) in a place different of the document root (e.g. https://mydomain/mautic1)
2. go to Configuration > User/Authentication Settings
3. Check the line that states "Use the following entity ID in the IDP: https://mydomain". Shouldn't it be https://mydomain/mautic1 ?
 
### Log errors
mautic.CRITICAL: Uncaught PHP Exception Exception: "Serialization of 'Symfony\Component\HttpFoundation\File\UploadedFile' is not allowed" at /var/www/ht
ml/MYDOMAIN/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php line 43 {"exception":"[object] (Exception(code: 0): Serialization of 'Symfony\\Component\\HttpFoundation\\File
\\UploadedFile' is not allowed at /var/www/html/MYDOMAIN/app/bundles/CoreBundle/Doctrine/Type/ArrayType.php:43)
[stacktrace]

**Comment by rodolfomatos** [comment]
I changed a line in app/config/security.php, and it seems to have solved my problem.

/app/config$ diff security.php security.bak.php 
185,186c185
< 	//$entityId = $scheme.'://'.$parts['host'];
< 	$entityId = $container->getParameter('mautic.site_url');
---
>         $entityId = $scheme.'://'.$parts['host'];

**Comment by npracht** [comment]
@alanhartless what do you think of this ?

**Comment by alanhartless** [comment]
Yea I discovered these myself and fixed in https://github.com/mautic/mautic/pull/8265 for Mautic 3. We can back port a few things to M2. 

There’s also a PR open here for M2 that fixes the UploadedFile issue.

**Comment by npracht** [comment]
fixed in 3.0.0
