### ISSUE TITLE
Form Results Date Submitted Filter Relative Syntax Not Properly Working

### ISSUE THREAD

**Issue by jrean** [mautic/mautic#8246]
Hi,

Mautic version: 2.15.2
PHP version: 7.2.24

According to the documentation:
https://www.mautic.org/docs/en/contacts/manage_segments.html

```
...
Beside this you can specify your date with text. These formulas are translatable, so make sure you use them in correct format.
birthday / anniversary
birthday -7 days / anniversary -7 days
today / tomorrow / yesterday
this week / last week / next week
this month / last month / next month
this year / last year / next year
...

Example (Consider that today is 2018-03-02):
last month returns all contacts identified between 2018-02-01 and 2018-02-28.
...
```

`https://mautic-instance.com/s/forms/results/$id`

Consider that today is 2019-12-18

Typing `last month` in the `Date Submitted` column to filter will display only entries from previous month so `November` but only for the `18`! Impossible to get all entries from 2019-11-01 until 2019-11-30 as it should be.

Is that normal?

Best,

J.

**Comment by npracht** [comment]
Hi @jrean the feature you talk about (relative dates) is implemented on segment filters, not on form results list. That's why !
If you want to suggest this improvement, please do it on the forum.
Thanks !
