### ISSUE TITLE
mau_unique_bundle is not unique

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#825]
When I run `php app/console doctrine:schema:update --force` command on my devel Mautic running on Postgres, I get 
```
  [Doctrine\DBAL\DBALException]                                                                           
  An exception occurred while executing 'CREATE UNIQUE INDEX mau_unique_bundle ON mau_plugins (bundle)':  
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "mau_unique_bundle" already exists      
```
I searched for this constraint and it does not exists. I've read about it and it seems that constraint name has to be unique from table or column names. I couldn't find that either. Maybe there is something else named that way. No clue what causes this conflict. But, if I rename `unique_bundle` to `unique_bundle_name` for example, I got no error and the SQL get's updated. Can I send a PR with this change or is there a better solution?

FYI I'm talking about this line:
https://github.com/mautic/mautic/blob/staging/app/bundles/PluginBundle/Entity/Plugin.php#L82

**Comment by alanhartless** [comment]
@escopecz I just hit this in another scenario because another table had the same named index.  Is it possible you have a backup table or something in the same database that has the same index?

**Comment by escopecz** [comment]
Hmm, the error is gone now. No idea what fixed it. Closing.
