### ISSUE TITLE
The service "mautic...subscriber" has a dependency on a non-existent service "mautic...removed_contact_tracker"

### ISSUE THREAD

**Issue by rodrigocvb** [mautic/mautic#8255]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | Yes
| Feature request? | 
| Enhancement? | 

## Description:
I tried to update my Mautic from dashboard and it got stuck. I clicked to logout and since then my Mautic website (mautic.mydomain) is offline. I'm trying to follow many tips, changing permissions, clearing cache, updating schema and so on. But I always get:

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                                                               
  The service "mautic.lead.campaignbundle.action_delete_contacts.subscriber" has a dependency on a non-existent service "mautic.campaign.helper.removed_contact_tracker". 

Every time someone access my website (not mautic.mydomain but mydomain) this error is also logged with a 'referer' to the page this person have accessed. I suppose this is because I have the Mautic tracking pixel on the website.

## If a bug:

| Q   | A
| --- | ---
| Mautic version | 2.13.1
| PHP version | 7.0.27

### Steps to reproduce:
1. Update from 2.13.1 to 2.15.3 from dashboard
2. Logout while moving packages
 
### Log errors: 

There is no Mautic error since my instance is offline. Apache's error log gives me this:
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                                                               
  The service "mautic.lead.campaignbundle.action_delete_contacts.subscriber" has a dependency on a non-existent service "mautic.campaign.helper.removed_contact_tracker".

**Comment by npracht** [comment]
Hi @rodrigocvb !
Did you try to follow that ? https://johnlinhart.com/blog/uh-oh-mautic-upgrade-was-not-successful

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
