### ISSUE TITLE
Replace the filemanager

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8259]
Mautic's [filemanager](https://github.com/simogeo/Filemanager) is EOL and the [replacement](https://github.com/servocoder/RichFilemanager) doesn't look very active. 

We could use something like https://github.com/helios-ag/FMElfinderBundle which uses Elfinder but we'd have to test it with jQuery 3 since it comes native with 1.x. There are closed issues with commit references that fixes jQuery 3 compatibility issues so hopefully it'll work.

**Comment by anton-vlasenko** [comment]
PR: https://github.com/mautic/mautic/pull/8306

**Comment by alanhartless** [comment]
Closed as done
