### ISSUE TITLE
Test distribution build script and installer on M3

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8260]
Installation must be tested on the 3.x branch. 

Execute the build script
- [x] `php build/package_release.php -b=3.x` 
- [x] Fix issues until packaging script works
- [x] Move build/packages/3.0.0-alpha.zip to another web directory and extract
- [x] Run through Mautic's installer from the zip's installation and report/fix any issues

**Comment by escopecz** [comment]
PR: https://github.com/mautic/mautic/pull/8269

**Comment by escopecz** [comment]
The installation of Mautic from the built script was smooth. No issue noticed.
