### ISSUE TITLE
Mautic are very slow - 1,5m+ contacts

### ISSUE THREAD

**Issue by PierreAmmeloot** [mautic/mautic#8261]
Q | A
-- | --
Mautic version | 2.15.2
PHP version | 7.0
Browser | any

## Bug Description 
This issue persisted in Mautic for quite a long time, but seems like recent update made it worse.

Given: quite big Mautic installation, servicing 1,5m+ contacts, 45+ segments, sending 200k+ emails weekly. 
Mautic tables are using InnoDB engine on MariaDB 10.1.41

Server setup : 
- 1 server for dedicated for DB.
- 3 server for execute code (including 1 server dedicated to CRON tasks)
- 1 load balancer on front

My 8 heaviest tables are : 
- campaign_lead_event_log       16 543 718         204,7 Gio
- lead_event_log                          300 594 547     63,8 Gio
- email_stats                                 3 009 627         34,2 Gio
- notifications                               56 661 425       15,7 Gio
- page_hits                                    8 010 191           15 Gio
- audit_log                                     10 931 856        5,5 Gio
- leads                                            1 242 362          2,5 Gio
- ip_addresses                              9 058 213          1,5 Gio

## We investigate
I have search a CRON for delete old data.
On my case I can delete email stats and campaign log more than 180 days old.

Browse on Mautic back office are very slow.
Do you have a process to have a big Mautic installation with normal user experience for user?

Can we add index on table to speed up SQL request processing ?

For exemple this request : 
`SELECT n0_.id AS id_0, n0_.type AS type_1, n0_.header AS header_2, n0_.message AS message_3, n0_.date_added AS date_added_4, n0_.icon_class AS icon_class_5, n0_.is_read AS is_read_6 FROM notifications n0_ WHERE n0_.user_id = 6 AND n0_.is_read = 0 ORDER BY n0_.date_added DESC LIMIT 200`

22m lines read and to be sorted! To output 200 results
<a href="https://ibb.co/SK4S6qz"><img src="https://i.ibb.co/gDLYrsx/image001-1.png" alt="image001-1" border="0"></a>

This one on the triggers is not bad either.

`SELECT cl.campaign_id, c.name AS campaign_name, l.firstname, l.lastname, ce.type AS event_type, ce.name as event_name, cat.color, cl.trigger_date AS start FROM campaign_lead_event_log cl LEFT JOIN campaigns c ON cl.campaign_id = c.id LEFT JOIN leads l ON cl.lead_id = l.id LEFT JOIN campaign_events ce ON cl.event_id = ce.id LEFT JOIN categories cat ON cat.id = c.category_id AND cat.bundle='campaign' WHERE (cl.trigger_date >= '2019-12-01') AND (cl.trigger_date <= '2020-01-12') AND (cl.trigger_date >= '2019-12-16 13:59:33') LIMIT 50 OFFSET 0`

570m lines ( the whole table )
<a href="https://ibb.co/Vm5cKDy"><img src="https://i.ibb.co/NSbd4ph/image002.png" alt="image002" border="0"></a>

Anyway, it probably lacks an index... or not really made for these table sizes on some screens.

### Steps to reproduce
Install Mautic with 1,5 millions (or more) contacts and use it.
 
### Log errors
N/A

**Comment by heathdutton** [comment]
How much ram do you have dedicated to your database? 
There are some indexes that will simply stop being used (depending on your version of MariaDB) when you reach a certain capacity if they cannot fit in Ram.

- Increase ram to your DB if you can. We have over 350m leads in our Mautic, but it runs on an AuroraDB cluster (read and write replica), with a minimum of 2 instances and 120GB of ram. Scales up as necessary. You may need to double your ram to continue scaling up.
- Truncate the `notifications` table periodically, because core mautic doesn't clean this out automatically yet.
- Remove dashboard widgets that are not necessary. Some of those are problematic. You can update the default.json file to be a new simplified default for the users. These widgets drastically slow down login when you have millions of leads.
- If you are keen on patching with PRs, try some that address specific performance issues like #7806  #6651 #7901 (I use these in prod). Comment if they help you so we can get them in the next version.
- Try `SET GLOBAL TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;` in MySQL so that concurrent modifications (like bulk deletions) do not cause outages.

**Comment by PierreAmmeloot** [comment]
Thank you @heathdutton. I'll test this and get back to you. :-)

**Comment by PierreAmmeloot** [comment]
Hello @heathdutton :

Increase ram to your DB if you can. How much ram do you have dedicated to your database?
There are some indexes that will simply stop being used (depending on your version of MariaDB) when you reach a certain capacity if they cannot fit in Ram. We have over 350m leads in our Mautic, but it runs on an AuroraDB cluster (read and write replica), with a minimum of 2 instances and 120GB of ram. Scales up as necessary. You may need to double your ram to continue scaling up.
**I have 28GB of RAM on my database server. 
At the moment the SQL server never uses all its RAM. It won't do much good to increase the server's RAM. What's your recommendation?**

Truncate the notifications table periodically, because core mautic doesn't clean this out automatically yet.
**Now, I delete every night all notifications more than 4 weeks old.**

Remove dashboard widgets that are not necessary. Some of those are problematic. You can update the default.json file to be a new simplified default for the users. These widgets drastically slow down login when you have millions of leads.
**I only keep one widget on display.**

If you are keen on patching with PRs, try some that address specific performance issues like #7806 #6651 #7901 (I use these in prod). Comment if they help you so we can get them in the next version.
**I check this today.**

Try SET GLOBAL TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; in MySQL so that concurrent modifications (like bulk deletions) do not cause outages.
**If I follow this step I crash admin panel. I have removed this SQL command.**

Thanks you @heathdutton for your help!
**Do you have any other tips?**

**Comment by npracht** [comment]
@PierreAmmeloot & @heathdutton please move your discussion on forums or chat. Thanks.

**Comment by PierreAmmeloot** [comment]
I think that this "bug" is important to trace because there are probably hundreds of companies in the same case as us. When Mautic has a lot of contacts in the database, it becomes **unusable**. 

What do you think about it @escopecz?

**Comment by escopecz** [comment]
I agree. Go for it.

**Comment by PierreAmmeloot** [comment]
Thanks @escopecz can you reopen this issue?

**Comment by escopecz** [comment]
I don't see how a closed issue would forbid you to work on it. I do the same in https://github.com/mautic/mautic/pull/8257. The issue is closed but it won't stop me 😉

**Comment by PierreAmmeloot** [comment]
@escopecz Indeed, on the other hand, it is no longer visible to the people arriving on the issue list. It therefore lacks future comments that could help make Mautic faster, more efficient and therefore even more used by the community. :-)

**Comment by YosuCadilla** [comment]
Hello @PierreAmmeloot 
Adding more RAM will help you indeed, but that's not a definitive solution, if your stack is not perfectly optimized you will experience slowness no matter how much RAM you throw at it.

For 1,2MM contacts [(but contacts are not everything that matters)](https://mauteam.org/infrastructure/mautic-installation-mautic-hardware-requirements/), 28 GB RAM for RDS plus 8-16GB for your HTTP server and Mautic, **should** be enough.

You might additionally want to take a look into:
Choosing the right MPM for your needs.
Choosing the right PHP Interpreter for your needs.
Fine-tuning your database engine.
Make sure you have proper caching installed and fine-tuned.

**Comment by Kwadz** [comment]
Why this issue has been closed?

**Comment by npracht** [comment]
Hi ! I let you read the previous messages. This is more a configuration and server performance issue. Go to forum or slack if you want to discuss about it.
