### ISSUE TITLE
Transactional e-mails are not sent immediatly on queue mode

### ISSUE THREAD

**Issue by dbritopt** [mautic/mautic#8262]
Hello,

We have our mautic set to handle emails using queue. Nevertheless, that makes sense only for marketing e-mails, transactional e-mails (password recovery e-mails, sign-up confirmation, etc) should be sent immediately and not wait for the cron. How can this be achieved without changing the email handling mode?
Thank you very much in advance

**Comment by npracht** [comment]
Hello @dbritopt,

This is not how mautic works today. I'll recommend you to chat about it on the forum and suggest any feature/configuration enhancement.
