### ISSUE TITLE
Error in setting up AWS

### ISSUE THREAD

**Issue by jaichugani** [mautic/mautic#8264]
Hi, I get the following errors during setup of AWS

Inputing credentials (Testing connection)
---------------------
Connection could not be established with host email-smtp.us-east-1.amazonaws.com [Connection refused #111] Log data: ++ Starting Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport !! Connection could not be established with host email-smtp.us-east-1.amazonaws.com [Connection refused #111] (code: 0)
++ Starting Mautic\EmailBundle\Swiftmailer\Transport\AmazonTransport

Sending test email via AWS
---------------------
Connection could not be established with host email-smtp.us-east-1.amazonaws.com [Connection refused #111]

I'm using php 7.2 (tried alt-php & ea-php) - both give same issue.

The domain, email, DKIM, SPF are all verified by Amazon SES.

CRON jobs in place - https://prnt.sc/qgqtm2

SNS in place - https://prnt.sc/qgqwll

Installed Mautic 2.15.1 via cpanel (even tried upgrade to 2.15.3 still error).

My hosting company is asking if any PORT that needs to be whitelisted or if using static IP. 

Kindly suggest.

**Comment by npracht** [comment]
Hello @jaichugani !
I believe this is a configuration issue and the PORT might be a good solution. I'll recommend you to move the discussion to mautic forums or chat on Slack. Thanks a lot for using mautic community !
