### ISSUE TITLE
Forms don't work after upgrade from 2.15.1 to 2.15.3

### ISSUE THREAD

**Issue by miamicityman** [mautic/mautic#8271]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1
| Browser | FF/Chrome

### Steps to reproduce
1. Upgrade from 2.15.1 to 2.15.3 via onboard method
2. Get a bunch of errors.
3. Fix most of errors following instructions via: https://www.youtube.com/watch?v=cIG9CBzxg5w
4. Still get error accessing forms in backend.
5. Revert back to version 2.15.1 initially installed with Softaculous.
6. All good again.

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by dsp76** [comment]
In my case, upgrading Mautic on shell didn't work properly due to the bad hosting environment.
There was one database migration missing:

ALTER TABLE forms ADD form_attr VARCHAR(255) DEFAULT NULL

You might want to check, if that column exists.

**Comment by RCheesley** [comment]
Closing due to old issue and likely as a result of a failed update
