### ISSUE TITLE
Remove doctrine/doctrine-cache-bundle dependency

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#8289]
> This release drops support for PHP < 7.1 and marks this bundle as deprecated. With Symfony shipping its own cache component, there is no need to configure caches using this bundle in Symfony anymore.

Read more details at https://github.com/doctrine/DoctrineCacheBundle/releases/tag/1.4.0

We use it only for API limiter that was added a year ago 

https://github.com/mautic/mautic/blame/61907dd315985842dccbd1a5a60614fd6cfbce02/app/config/config.php#L360

@Dcoutelle or @npracht will you have time to change that to use Symfony's cache bundle instead so we could remove that deprecated dependency? 

https://symfony.com/doc/current/cache.html#configuring-cache-with-frameworkbundle

**Comment by Dcoutelle** [comment]
Hi John,

@Enc3phale is currently working on it, it should be done beginning of next week.

**Comment by Enc3phale** [comment]
This seems to be good : https://github.com/mautic/mautic/pull/8305

**Comment by escopecz** [comment]
Oops, I merged the PR prematurely. There is one more thing to do. It should be possible to remove the `doctrine/doctrine-cache-bundle` dependency from composer.json and everything should still work. I leave this issue open until another PR removes that.

**Comment by anton-vlasenko** [comment]
PR: https://github.com/mautic/mautic/pull/8319
