### ISSUE TITLE
[feature request] Campaign Variables

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#831]
#### Campaign variables:

The idea behind this is that you can set variables in a campaign (text, dates, numbers) and then use those variables throughout the campaign.
#### Use cases:

Similar campaign emails for several campaigns (liek Webinar emails):  See #757.  Can create a campaign with a series of emails.  Set the Webinar title, webinar url, webinar date as campaign variables.  Then you can use these variables in emails.  This allows an email template to be used for many different webinar campaigns

Makes campaigns easier to clone and re-use.  Use variables when updating contacts, setting lists, etc...  

There are probably thousands of use-cases.  In software dev, you can't live w/o variables... so lets put them in campaigns.

**Comment by CyberZen53** [comment]
Any idea when this is scheduled for development? I'm also looking for the same feature.

**Comment by moxival** [comment]
Is this implemented? I am confused, can somebody point me to the documentation explaining how to use this?

**Comment by ston3o** [comment]
Hello @dbhurley, why are you closed this issue ? This feature is implemented somewhere ?

**Comment by npracht** [comment]
Hello @ston3o !
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
