### ISSUE TITLE
Auto generated text for an email does not include links from dynamic content blocks

### ISSUE THREAD

**Issue by jsieber** [mautic/mautic#8317]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.1.25
| Browser | Google Chrome

### Steps to reproduce
1. Create an email with a "dynamic content" section that includes html links.
2. Auto-generate the text version of the email. 
3.The auto-generated text will have something like this in the generated text. {dynamiccontent="Dynamic Content 2"}
4. Send the email to your account and inspect the orginal version of the email. In the text/plain mime version the links in the dynamic content will just be the text for the link but not include the link itself as text.

###Expected
The generated text version should include the actual link after the link text. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
I was able to reproduce this on 3.1. Thanks for reporting it @jsieber-aca !
