### ISSUE TITLE
Form creates duplicates of companies that contain ampersands

### ISSUE THREAD

**Issue by cedoe** [mautic/mautic#8318]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
We have a form where a contact can also enter the name of their company. There are two fields in the form editor that can set the company name: 'Primary Company' for a 'Contact' and 'Company Name' for the 'Primary Company'.
If the form field is set to change the 'Primary Company' and a contact enters  a company name that contains an ampersand or an apostrophe then Mautic creates two companies with the same name and assigns both to the new contact.
If the company does not contain either of these symbols or I modify the form to set the 'Company Name' instead then only one company is created.

| Q   | A
| --- | ---
| Mautic version | 2.15.3, confirmed in 3.2.1
| PHP version | 7.2.24
| Browser | 

### Steps to reproduce
1. Create a new form.
2. Add a text field that sets '**Contact** Primary company'.
3. Enter a company name that contains '&'.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by cedoe** [comment]
Hi. Yes, this is still happening in 3.0.1.

**Comment by RCheesley** [comment]
Hi @cedoe thanks for the confirmation, we've had quite a few fixes since 3.0.1 - is this still persisting for you? If so could you let us know so we can look into it? Thanks!

**Comment by cedoe** [comment]
Hi @RCheesley , I have tested this with 3.2.1 and the problem still persists.
