### ISSUE TITLE
M3 Installation Process is Broken

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#8324]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
1. Try to install M3 either from the released edition or the one hosted on Github.
2. When you reach the point in the installation process, the point to select sending email using queue. 
3. You will get 500 error due to `mkdir` permission issue. 

The error cause is the parameters saved in the file `local.php` which is generated during the installation, it uses the variable `kernel_root_dir` which should point the root directory of M3 installation, instead it points to `app` folder. 

Therefore an error is generated because it tries to create a folder called `default` inside the folder `app/var/spool/default/` but this folder does not exist. instead it should be created at `/var/spool/`.

A quick solution could be changing the folder location to a fixed path, the same problem occur to the folders `cache` and `logs`

| Q   | A
| --- | ---
| Mautic version | 3.0.0-alpha
| PHP version |  7.2.24
| Browser | Chrome

### Steps to reproduce
**Mentioned in the steps above** 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
Thanks for the bug report!

1. Could you paste the actual error message here?
2. Isn't a mkdir issue just a server configuration issue?

**Comment by mabumusa1** [comment]
Here is the log

``[2020-01-15 10:05:01] mautic.CRITICAL: Uncaught PHP Exception Swift_IoException: "Unable to create path "/home/user/mautic-3/app/var/spool/default"." at /home/user/mautic-3/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php line 42 {"exception":"[object] (Swift_IoException(code: 0): Unable to create path \"/home/user/mautic-3/app/var/spool/default\". at /home/user/mautic-3/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php:42)"} []
``

I thought it is a server configurtion issue but when I read the log, it was clear that the installer is trying to create the folder `default` inside `app/var/spool` which is wrong it must be `/var/spool`

I think the variable `%kernel.root_dir%` that is inside `local.php` is pointing to the directory `app/` rather than `/`

BTW, I changed the value in `local.php` from
``'mailer_spool_path' => '%kernel.root_dir%/var/spool',``
to 
`'mailer_spool_path' => '/home/user/mautic-3/var/spool',`

it worked, so it is not a permission issue

**Comment by dennisameling** [comment]
Can confirm this behavior.

Mautic 2.15.3:
```bash
denni@mautic2153-web:/var/www/html$ ls /var
backups  cache  lib  local  lock  log  mail  opt  run  spool  tmp  www

denni@mautic2153-web:/var/www/html$ ls /var/www/html/app
AppCache.php   AppTestKernel.php  autoload.php         bundles  config   logs         migrations
AppKernel.php  Resources          bootstrap.php.cache  cache    console  middlewares  version.txt
```
Mautic 3 Alpha:
```bash
denni@mautic-web:/var/www/html$ ls /var
backups  cache  lib  local  lock  log  mail  opt  run  spool  tmp  www

denni@mautic-web:/var/www/html$ ls /var/www/html/app
AppCache.php   AppTestKernel.php  autoload.php  config   middlewares  phpunit.xml.dist  version.txt
AppKernel.php  Resources          bundles       console  migrations   var

denni@mautic-web:/var/www/html$ ls /var/www/html/app/var
cache  logs
```

In Mautic 3, a new folder `var` is created inside the `app` folder. We'd need to check the logic that replaces the value `%kernel.root_dir%`

@npracht can you assign me to this issue?

**Comment by dennisameling** [comment]
Just had a quick chat with @alanhartless and he already came across a similar issue. This should be fixed in https://github.com/mautic/mautic/pull/8265/commits/09d2293d034302ba03a8b8b2c761bbd5280ff1cf and https://github.com/mautic/mautic/pull/8265/commits/d304fc0e530c3e49e3c140e43a980e0a1a596ee2 (when https://github.com/mautic/mautic/pull/8265 is merged)

**Comment by escopecz** [comment]
Tested on https://github.com/mautic/mautic/pull/8265. The bug is fixed there.

**Comment by cloudpotions** [comment]
@escopecz @mavimo I found a solution that worked for me on this... The error occured when I deleted the information in "Path to the email queue directory" (this is located under Configuration and then email settings). After I deleted this, I then changed my mind and changed the other setting "Path to the email queue directory" from 'Queue' to 'Send Immediately". Once I did that and tried to reload, the website broke. Took me a while to figure it out, but what I did to fix it is below 

Step 1: go to your local.php file located under the domain you installed Mautic. It will be under something like <your-domain>  httpdocs / mautic / app / config / local.php
Step 2: In this file look for the line 'mailer_spool_path' => 'file', and change it to 'mailer_spool_path' => null,
Step 3: Run a cron to clear the cache, if it does not let you then physically delete the cache folder located at <your domain> httpdocs /mautic /app/ cache  (dont worry you can delete it and it will come back) 

Refresh the site and it should work :)
