### ISSUE TITLE
What is the best reccommendation for Mautic hosting?

### ISSUE THREAD

**Issue by IvanCyber** [mautic/mautic#8327]
Can someone precisely define what are parameters of most optimal hosting for Mautic ver. 2.15.3, that uses Amazon SES for mass e-mail sending (for sending to over 1.000.000 e-mail addresses at a time) like:
- PHP version
- MySQL version
- RAM
- Number of processor cores
- Bandwidth
- Dedicated IP addresses (Yes or No, and how many?)
- Type of hosting (Shared, VPS or Dedicated?)
- allowing options for "Send immediately" and "Queue" with cron job
- and optimal price :)
(if something missed, please add)

What are the top 5 hosting providers from your experience that are the best according to the above parameters?
Please, support with links to read these offers and recommendations, as well.

Thank you

**Comment by npracht** [comment]
Hi @IvanCyber !
Thanks for your message. Nevertheless, we use GitHub to report issues. If you'd like to chat, I'd recommend you to join the forums or Slack.
You can also have a look there: https://github.com/mautic/mautic#requirements

Best !
