### ISSUE TITLE
lookup field on contact creation does not show suggested values

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#8331]
## Bug Description
When you create a contact, lookup type field does not show suggested values.

| Q   | A
| --- | ---
| Mautic version | 3.0.0-alpha
| PHP version | 7.2
| Browser | 

### Steps to reproduce
1. Create a contact
2. Add a value in Title field (created by default on a fresh installation) and see that it does not suggest an existing value.
![Capture d’écran 2020-01-14 à 17 22 12](https://user-images.githubusercontent.com/14075239/72362136-e75f7600-36f2-11ea-9011-d71d7bd4c19c.png)
![Capture d’écran 2020-01-14 à 17 22 20](https://user-images.githubusercontent.com/14075239/72362138-e7f80c80-36f2-11ea-837d-d7240f8f886a.png)

 
### Log errors
None

**Comment by dennisameling** [comment]
@npracht Can you please assign me to this issue?

Some first investigation shows that this issue only seems to apply to the "Title" field. As far as I can see, this issue is already present in Mautic 2, and thus not M3-specific.

![image](https://user-images.githubusercontent.com/17739158/72757188-99a1ac80-3bcf-11ea-9b33-f66fc59df9a4.png)

Looking further into this now.

**Comment by npracht** [comment]
Hi @dennisameling i assigned you. No i am not aware of a version where it works.
It is supposed to behave like companies, suggests the already existing values for that field.

**Comment by npracht** [comment]
According to your comment concerning M2, I'll remove the mautic 3 regression label.
If you want to fix it this is excellent, but if you focus on a M3 issue it is even better !

**Comment by dennisameling** [comment]
@npracht Alright, I'll park this issue for a few weeks to focus on M3 issues. Will work on this one later 👍

**Comment by RCheesley** [comment]
@dennisameling not clear from the discussions above if this is still an issue with Mautic 3.01 but assume so, correct if wrong!

**Comment by ODSMarcus** [comment]
I can confirm this issue is still present within Mautic 4.0 @dennisameling @npracht

**Comment by jos0405** [comment]
It is still an issue in 4.0.1
