### ISSUE TITLE
Unsubscribe from a category

### ISSUE THREAD

**Issue by mimikama** [mautic/mautic#8336]
## Bug Description

| Q   | A
| --- | ---
| Mautic version | v2.15.3

Hello everybody!

Probably it is a bug, or I am missing something :)

### Steps to reproduce
1. I have created a Global Category `asdf`
2. I added that Category to a contact (which belongs to a segments `test segment`)
3. I turned the configs (->email settings->unsubscribe settings->Show contact's categories) to `Yes`
4. I created a new Segment Email and I added it to `asdf` Category and sent it to `test segment`
5. After receiving that email, I unsubscribe from `asdf` Category
6. repeat 4th step
7. The contact is still receiving email of the `asdf` Category that had unsubscribed.

This is supposed to happen? 

How a contact can unsubscribe from a category, so that no longer receive emails that belong to that category?

Note: 
  For the unsubscribe link I use the following token:
`href="{unsubscribe_url}"`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Are you running the cron jobs necessary to rebuild segments between steps 5-7?

You need to remove them from the segment (test-segment) to prevent them from receiving the emails.

**Comment by mimikama** [comment]
Thanks for answering.

Actually, what I needed to have is
 separated "cateogries" of template emails (that are being sent to single contacts through a different api) and
to be able to unsubscribe from each one of these "cateogries" || segments..

Finally, what I did, is to GET in my api the segments that the contact belongs and if they do not belong to that segment (that corresponds to that email) - they do not receive that email.
