### ISSUE TITLE
Webhooks data

### ISSUE THREAD

**Issue by zapur1** [mautic/mautic#834]
Hi,

I'm running into a bit of a issue with how the webhook data is returned. So I captured the result of the "New Lead Event" webhook. I've then grabbed this as a basis for adding to the Zapier integration as sample data and this is how it interprets it
<img width="861" alt="webhook" src="https://cloud.githubusercontent.com/assets/1893622/9565980/7db8c568-4f33-11e5-8b57-939abe566760.png">

If it were interpreting it properly then all the leads would be shown and names could be assigned but as all the data sits under the JSON array "mautic.lead_post_save_new" it isn't able to interpret it. This will probably lead to some issues for me personally adding webhooks to the integration and possibly others as well trying to use the API.

From a Zapier point of view a new webhook URL is created for each event so I was quite surprised to see that in Mautic one URL can be used for many events which then means that putting the data inside a JSON array is needed to differentiate between what kind of data it is. 

So is there any reason why the top-level JSON array couldn't be removed and webhooks be changed so each webhook only triggers one event? One URL per a event is what I personally have come across in the past, how about everyone else?

**Comment by alanhartless** [comment]
Hi. 

The webhooks bundle was modeled after the Mandrill webhooks setup where events can be batched and sent in groups. 

But it is a setting in Mautics configuration to send immediately or to batch. In the case of an immediate send, I can see the need to format the payload differently. 

Can you update your PR to honor the  setting? If set to batch, leave the payload as it was originally. However if set to send immediately, then format the way you changed it to. Does that make sense? 

Thanks!
Alan

**Comment by zapur1** [comment]
That is a good solution to it and I had a feeling that it would fall over
when sending as a batch. I will get it implemented and working.

When it comes to selecting what events trigger it should it also change
from one to many depending on if it is in batch mode or not?

Zac

**Comment by alanhartless** [comment]
I think you can actually leave that as multiple because it doesn't affect how the payload is packaged but just how the bundle finds what URL to send payloads to based on the event dispatched in Mautic.  Otherwise one would have to create a web hook per event type for the same URL.

**Comment by zapur1** [comment]
You know what, some of the issues I was expecting to occur as a result of it being setup this way aren't going to be a problem. The only issue will be if a webhook is triggered off of multiple events so I will just make a note of that in the setup instructions.
