### ISSUE TITLE
Notification for Scheduled Email Send Failures

### ISSUE THREAD

**Issue by bpcook920** [mautic/mautic#8344]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | No
| Feature request? | Yes
| Enhancement? | Yes

## Description:
Mautic 2.15.2 introduced a bug where [scheduled segment emails would not send](https://github.com/mautic/mautic/issues/7767). There was no notification from Mautic itself and on-demand emails would send just fine. Due to the lack of notification, we assumed there were no issues with segment emails and they were sending as scheduled. We have setup monitoring on our configured email host so we know if that is down, but it would be nice to have a configurable alert system within Mautic to alert when scheduled emails fail to send due to exceptions or otherwise.

**Comment by RCheesley** [comment]
Hi there,
I have raised this on the forums, which is the appropriate place for a feature request: https://forum.mautic.org/t/notification-for-scheduled-email-send-failures/12548
