### ISSUE TITLE
custom url parameter how to get multicustomfield data???

### ISSUE THREAD

**Issue by raghav111jain** [mautic/mautic#8346]
this script work for get email from URL but i want email with firstname and mobile so how to do that please help me ASAP
Already enable public updatable.

```
> <script>
> 	function getUrlParameter(name) {
> 		name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
> 		var regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
> 		var results = regex.exec(location.search);
> 		return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
> 	};
> 	
>     (function(w,d,t,u,n,a,m){w['MauticTrackingObject']=n;
>         w[n]=w[n]||function(){(w[n].q=w[n].q||[]).push(arguments)},a=d.createElement(t),
>         m=d.getElementsByTagName(t)[0];a.async=1;a.src=u;m.parentNode.insertBefore(a,m)
>     })(window,document,'script','https://demo.test.com/test/mtc.js','mt');
> 
> 	var email  = getUrlParameter('email');
> 
> 	if(email !== ''){
> 		mt('send', 'pageview', {email: email});
> 	} else {
> 		mt('send', 'pageview');
> 	}
> </script>
> 
```

[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as this is a question rather than a bug, please post at https://forum.mautic.org where you will have more people able to help you.
