### ISSUE TITLE
"php bin/console" command (with no arguments) throws an exception

### ISSUE THREAD

**Issue by anton-vlasenko** [mautic/mautic#8359]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you try to run `php bin/console` you will get the following error in the console:
```
PHP Warning:  include(): Failed opening '
/vendor/composer/../../app/bundles/LeadBundle/Tests/DataFixtures/ORM/LoadPageHitData.php' for inclusion (include_path='.:/usr/local/Cellar/php@7.2/7.2.25/share/php@7.2/pear') in /vendor/composer/ClassLoader.php on line 444
```
It's happening because LoadPageHitData.php file is not included into the M3 distribution package.
We don't include all the `Test/` folders into our distribution packages.
We need to find a way to fix that.

| Q   | A
| --- | ---
| Mautic version | 3.0.0-alpha
| PHP version | 7.2.25
| Browser | N/A

### Steps to reproduce
1. Checkout 3.x branch.
2. Create a distribution package using `build/package_release.php` script (make sure you've updated the 3.0.0-alpha tag to point to the latest commit in your branch).
3. Install Mautic from the package that you've just generated.
4. Run `php bin/console`.
5. Observe errors in the console.
 
### Log errors
```
PHP Warning:  include(): Failed opening '
/vendor/composer/../../app/bundles/LeadBundle/Tests/DataFixtures/ORM/LoadPageHitData.php' for inclusion (include_path='.:/usr/local/Cellar/php@7.2/7.2.25/share/php@7.2/pear') in /vendor/composer/ClassLoader.php on line 444
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by dongilbert** [comment]
PR was merged

**Comment by lukassykora** [comment]
PR is here: https://github.com/mautic/mautic/pull/8377. It is not merged to mautic/mautic yet.

**Comment by anton-vlasenko** [comment]
https://github.com/mautic/mautic/pull/8377#pullrequestreview-352262861
