### ISSUE TITLE
When assigning multiple companies to a contact at the same time, all of them receive the 'is_primary' mark

### ISSUE THREAD

**Issue by benedekAdam** [mautic/mautic#8360]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When assigning companies to a lead, the newly assigned companies receive the 'primary company' mark. In the case of assigning multiple companies at the same time (in the same update action) all of them receive the mark, which should be impossible (as manually marking an already assigned company primary removes the mark from the previous primary company).

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 7.1.30
| Browser | Google Chrome Version 79.0.3945.130

### Steps to reproduce
1. Create at least two companies (can be skipped if the are already more that two companies exists)
2. Create a new contact, or update an existing one
3. On the form, in the 'Company' input, select multiple companies
4. Save the form
5. Navigate to the contact's page
6. All of the newly added companies should display the primary mark (yellow checkmark)
7. In the database, in the companies_leads table, all of the new added records have the 'is_primary' attribute as 1

**Comment by benedekAdam** [comment]
One could also argue that automatically overwriting the previously marked primary company on adding a new one (or multiple) can be considered a bug.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
