### ISSUE TITLE
Discussion for "Allow save image to contact profile from form"

### ISSUE THREAD

**Issue by dennisameling** [mautic/mautic#8363]
This ticket is to follow up on #7886, where the following comment was made by @RCheesley:

> One question though, I did wonder (as a user) why the profile image wasn't available as a matching field in the way you would usually associate a form field with a Mautic field. As this is the way most users will associate form data with Mautic fields, perhaps that's where we should have the ability to match the field?
>
> Maybe that could be a better way of doing it than having another yes/no switch cluttering the UI? I'm not sure on the technical restrictions that this might present, so just a suggestion.

Now that #7886 is merged as a good first step, it should be explored whether the functionality as discussed above is technically feasible.

**Comment by RCheesley** [comment]
I think the option will be OK for now. I do think being able to file match would be better from the UI/UX perspective, but this works well enough.
