### ISSUE TITLE
Segment permission "view others"don't work 

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#8367]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hello, 
If you set a role without permission for the segment,  the user with that role will continue to see others segments,  he can't edit or delete them but still can view them.  He also view all segment in the segment list selection in a segment email. 

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1. Create some segments with an admin user
1. Create a new role
2. Don't give any right for segments in the contact permission option
![image](https://user-images.githubusercontent.com/49391402/73350486-67f2aa80-428d-11ea-811e-d37bf43dfab4.png)
3. Create a new user with the new role
4. Log in with the new user
5. See that you can see all segment in the segment list  or when creating an segment email
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
I think It works properly.
Segments have different permission setup.

- you can allow view others - then user see all segments
- you can disable public - then just you and all users with view others see that segment

![image](https://user-images.githubusercontent.com/462477/73645866-6ef82f00-4678-11ea-9af5-2a59f5e729a4.png)
