### ISSUE TITLE
Mails from a campaign are scheduled in UTC

### ISSUE THREAD

**Issue by different-thinking** [mautic/mautic#837]
Hi,

I've setup mautic to GMT+1 within the settings. When I now schedule mails in a campaign the get scheduled in UTC. 

I expected that they are scheduled in my configured time zone.

Robert

**Comment by alanhartless** [comment]
All dates are saved to the database as UTC to safely support users and leads in multiple timezones.  But the dates should be converted back to the local timezone when retrieved. Are you finding that the date is showing up somewhere incorrectly?

**Comment by different-thinking** [comment]
Hi Alan,

well not showing up wrong, but unexpected. When I schedule a mail within a campaign:

![image](https://cloud.githubusercontent.com/assets/10116611/9595990/d137bdc0-506e-11e5-864a-88acbb17ef19.png)

My local time is selected - great. Afterwards I see the following within in the campaign:
![image](https://cloud.githubusercontent.com/assets/10116611/9595993/f4a92dca-506e-11e5-85ba-641b7ad14fc8.png)

Now it is shown as UTC - before I thought it is my local timezone. And mautic will deliver at UTC time.

So I'm confused! And together with https://github.com/mautic/mautic/issues/838 - I'm a bit in trouble.

Best,

Robert

**Comment by alanhartless** [comment]
Hey Robert,

I can't reproduce this.  Can you verify that your user profile's timezone is not set to UTC? I tried several combinations of system default timezone and my user profile's timezone, creating new events, editing events, etc and they all displayed the timezone correctly.

**Comment by different-thinking** [comment]
Hey Alan,

I'm sorry - I didn't recognize that there is a time setting in the user profile! I changed this and now I see my times in CEST!

Thank you very much! Please excuse my mistake!

Robert

**Comment by ankit-verma** [comment]
I'm also having same issue. I've changed mautic system timezone from configuration and also set the correct timezone in php.ini but still campaigns showing UTC time while scheduling. Need to fix this urgently.

**Comment by MauriceW2** [comment]
Same here. I know thi sis a pretty old issue and closed, but in mautic 2.15.1 all campaign scheduled emails use UTC. User profile timezone, default timezone in Mautic are Europe/Amsterdam. Server timezone and PHP timezone are also Europe/Amsterdam. Nothing works. Mautic keeps scheduling at UTC.
