### ISSUE TITLE
`Render Style` resets to default when cloning a form

### ISSUE THREAD

**Issue by vdrover** [mautic/mautic#8371]
## Bug Description
Forms have a setting to enable/disable the mautic CSS called Render Style. If you disable this option and then clone the form, the option re-enables.

| Mautic version | v2.15.3
| PHP version | 7.2.26
| Browser | Chrome 79.0.3945.130

### Steps to reproduce
1. Create a new standalone form. 
2. Disable the `Render Style` option.
3. Clone form.
4. Edit the cloned form. The `Render Style` option will be enabled.
 
### Log errors
N/A

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
I was able to confirm this in 3.1.
