### ISSUE TITLE
Duplicated IPs in DB when anonymizing IPs is turned on

### ISSUE THREAD

**Issue by lellebebbl** [mautic/mautic#8372]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When you turn on "Anonymize IP" in the Tracking settings multiple duplicate IPs will be created in the Table "ip_adresses" on one page hit. When I'm testing it, there are always 5 IPs generated. One of them is connected to the created Lead and one is connected to the page hit. But there are 3 more Addresses which are not connected in the DB to any other entry. So they are not used.

| Q   | A
| --- | ---
| Mautic version | v2.16.0-dev
| PHP version | PHP 7.2.24
| Browser | 

### Steps to reproduce
1. Activate Anonymize IP in Settings > Configuration > Tracking Settings
2. Open a tracked page
3. Look into Database: You should see more than 2 new entries

### Workaround
It's possible to delete the unused IPs with the command `mautic:unusedip:delete --limit 10000` (https://github.com/mautic/mautic/pull/7491) 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by lellebebbl** [comment]
This probably happens because in the class IpLookupHelper the `getIpAddress($ip)` function searches for the corresponding IP. But at this time it's not anonymized so it will not find the corresponding anonymized IP. But this function gets called not just for the Page-Hit and connecting the lead. So the IP gets persisted at every function call of `getIpAddress($ip)`

**Comment by kuzmany** [comment]
This should fixed it
https://github.com/mautic/mautic/pull/8175

**Comment by lellebebbl** [comment]
Thank you, works like expected :)
