### ISSUE TITLE
Campaign cloned via API does not have events

### ISSUE THREAD

**Issue by darkkoala** [mautic/mautic#8376]
When I try to clone a Campaign via API call, the cloned campaign is created, but the events and forms are not copied to the new clone.

Mautic version 2.15.3
PHP version 7.2.24 (both the Mautic server and the machine making the api call)

Steps to reproduce
1. Create a campaign with a simple workflow
2. Clone the campaign via an API call (cloneCampaign)
3. Check the cloned campaign in Mautic (OR the returned campaign information from the API call) for the events / forms, and see they are not present

**Comment by adiux** [comment]
I was able to reproduce this with v3.0.0

**Comment by RCheesley** [comment]
Thanks for the confirmation @adiwegs !

**Comment by smartyaunt** [comment]
I was able to reproduce this with v3.3.3

**Comment by smartyaunt** [comment]
This problem is still not resolved, in the latest version 3.3.3

**Comment by smartyaunt** [comment]
mautic version: 3.3.3
php version: 7.4

Cloned campaign will not show any events,
but if I go to clone through the UI page, it work. Can anyone help me?

**Comment by woutersf** [comment]
@RCheesley We (@dedius and I)  have also experienced this issue in 4.0.0, Can you re-open this issue please?
