### ISSUE TITLE
Contact owner can't access contact attachement

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#8378]
## Bug Description

Contact attachments can't be accessed as contact owner, who is not admin. Role has access to own contacts only.

| Q   | A
| --- | ---
| Mautic version | 2.15.3 
| PHP version |  7.2
| Browser |  any

### Steps to reproduce
1. create a contact, via form with an attached document (gets linked to contact)
2. assign an owner to this contact, with limited rights (should only access his owned contacts)
3. log in with this user from a clean new browser tab (not the one which was admin before, even after logout the admin, this file is still accessible - which is another bug I guess)
4. go to your contact, open details
5. click attachement link

will result in 403 forbidden.

Expected behaviour: as user has full access to his owned contact, he should also see the attachement!
 
### Log errors
none

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by dsp76** [comment]
Yes, its still there. Limited User can't see attachment to a form her owned contact submitted. She still sees all the other fields within the contacts timeline. 

![image](https://user-images.githubusercontent.com/1241376/88483782-7682fb80-cf6a-11ea-844f-6d8a6c41ae7a.png)

Things change, when I allow the user to "view other forms". 

![image](https://user-images.githubusercontent.com/1241376/88483897-180a4d00-cf6b-11ea-81f9-2dfb2e1afd79.png)

But this is too much, as she shouldn't be allowed to see all form submits of all forms. I guess there needs to be some inheritance: A user should probably see all form details her contact submitted in any form. Not just the fields content, but also the attached files for her contacts submission record.

**Comment by RCheesley** [comment]
Thanks for getting back to us @dsp76 - and for the additional details!
