### ISSUE TITLE
Zapier | Company isn't passed via the "Create a new contact" option

### ISSUE THREAD

**Issue by cyanstar** [mautic/mautic#8391]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
There is an issue with the option in Zapier when "create a new contact" is used. It doesn't pull the company data even if it's selected and mapped out correctly. The sample data shows the company name correctly, but when the API is enabled it doesn't pull it. Any ideas?

I'm using Workbooks and trying to link a contact to an organisation/company. If the company name in Mautic matches the organisation name in Workbooks it'll automatically add the contact to the existing Org. If the Org doesn't exist it'll create a new one and assign the contact to that new Org. I'm trying to get this to work with the "New Contact" settings as we plan to use the Outlook plugin and few other tactics such as social to generate new data in Mautic, rather then just via form submissions.

| Q   | A
| --- | ---
| Mautic version | v2.15.3
| PHP version | 7.1.30
| Browser |  Chrome

### Log errors

![mautic-error-1](https://user-images.githubusercontent.com/10960390/73746100-61ac7480-474c-11ea-8e0b-4d8dc442a8e6.PNG)

![mautic-error-2](https://user-images.githubusercontent.com/10960390/73746105-64a76500-474c-11ea-88c9-0af100bd232f.PNG)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Do you have an error message in your Zap history ? Or in mautic ?

**Comment by cyanstar** [comment]
@npracht There are no errors in Mautic, but this is what Zapier gives...

![zapier-error](https://user-images.githubusercontent.com/10960390/73747286-0cbe2d80-474f-11ea-8804-07ac35d6f750.PNG)

**Comment by mabumusa1** [comment]
@cyanstar @npracht I ran into the same error two days ago

**Comment by cyanstar** [comment]
@mabumusa1 @npracht  Wish I could help solve this one, but my knowledge around the API's is basically none existent.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
