### ISSUE TITLE
Mautic | Config infinite load after adding IMAP settings

### ISSUE THREAD

**Issue by cyanstar** [mautic/mautic#8398]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I added the IMAP settings to my Mautic installation and now when I go to the Configuration page it continuously loads.  There is the below error in the logs. 

How can I go about removing the IMAP settings without reinstalling Mautic. I'm really rusty on all this now >_<

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| Browser | Chrome

### Log errors
`[2020-02-05 10:36:03] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: require(): Failed opening required '/opt/bitnami/apps/mautic/htdocs/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:/opt/bitnami/php/lib/php')" at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php line 209 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: require(): Failed opening required '/opt/bitnami/apps/mautic/htdocs/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:/opt/bitnami/php/lib/php') at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:209)"} []` 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by cyanstar** [comment]
Nevermind, I figured it out >_<

If anyone else has this issue, the IMAP and config page not loading problem is a known bug.

In this case I only needed to remove the IMAP settings, which are found in the /app/config/local.php file.

**Comment by Puspendert** [comment]
@cyanstar Thanks mate. I was hitting my head hard due to this. But can you point me to the PR/FR/Issue where this issue is mentioned? Also, how do you manage the IMAP now?

**Comment by Puspendert** [comment]
In my case, it was wrong IMAP details. So, make sure you "save" only after testing the configuration.
