### ISSUE TITLE
Translation error in "Quotes" field for brazilian portuguese

### ISSUE THREAD

**Issue by eddiecsilva** [mautic/mautic#8399]
## Bug Description
The translation of the field "Quotes" is incorrect for the language "Brazilian Portuguese".
In the beta version it appears as "Sitação" and the correct spelling is "Citação".

| Q   | A
| --- | ---
| Mautic version | v2.16.0-beta
| PHP version | 7.2.27
| Browser | Google Chrome 80.0.3987.87

### Steps to reproduce
1. Setting > Configurations > Default Language: change to brazilian portuguese
2. Logout and login again to reload the interface
3. Go to Setting > Configurations > Plugins
4. Select Facebook 
5. Click in "Contact Mapping"
6. The "Quotes" translation for brazilian portuguese is misspelled
 
![Captura de tela de 2020-02-05 09-06-59](https://user-images.githubusercontent.com/751446/73844347-2c149380-47ff-11ea-8a69-7f49be2f8f53.png)

**Comment by npracht** [comment]
Hi @eddiecsilva actually that comes from Facebook then, this is the name given by Facebook. We cannot do anything here.
