### ISSUE TITLE
Feature: Admin Notifications Email Subscribe

### ISSUE THREAD

**Issue by MaxOnTheHill** [mautic/mautic#84]
In the Mautic self hosted install admin interface > update settings
Ability for people to have "notify by email" for email notifications from Mautic.org (update notice, security notice, etc options - like embedded remote lead form ... so have their email on mautic.org email lists to be able to notify them directly of important news  :)

**Comment by escopecz** [comment]
Notifications from mautic.org are already pushed to every self-hosted Mautic via built in notification center.
