### ISSUE TITLE
REST API 500 error return mixed of HTML and JSON response

### ISSUE THREAD

**Issue by luk4s** [mautic/mautic#8406]
## Bug Description
If mautic return 500 internal server for API request, response body contains mixed of HTML and json => so its not easy to parse it. 
Also it's inconsistent with others reponses with error.

Issue is wrong API response format, not 500 itself.

| Q   | A
| --- | ---
| Mautic version | v2.13.1 1
| PHP version | 7.1.30-2+0~20190710.21+debian9~1.gbp011d3c|
| Browser | 

### Steps to reproduce
1. In my case, our mautic raise exception `mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes)"`
2. for GET Contact by ID
 
### Log errors
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Site is offline</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="icon" type="image/x-icon" href="/media/images/favicon.ico"/>
    <link rel="stylesheet" href="/media/css/libraries.css"/>
    <link rel="stylesheet" href="/media/css/app.css"/>
</head>

<body>
<div class="container">
    <div class="row">
                <div class="col-sm-offset-3 col-sm-6">
            <div class="bg-white pa-lg text-center" style="margin-top:100px;">
                <i class="fa fa-warning fa-5x"></i>
                <h2>The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.</h2>
                                <h4 class="mt-15">System administrators, check server logs for errors.</h4>
                            </div>
        </div>
            </div>
    </div>
</body>
</html>
{"errors":[{"message":"Looks like I encountered an error (error #500). If I do it again, please report me to the system administrator!","code":500,"type":null}],"error":{"message":"Looks like I encountered an error (error #500). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)","code":500}}
```

**Comment by k16101997** [comment]
Please review the permissions and reload server

to rewrite permissions: 

sudo chown -R www-data:www-data /path-to-mautic-installation
sudo chmod -R 755 /path-to-mautic-installation

reload the server (nginx, apache or the one you use)

**Comment by luk4s** [comment]
Hello @k16101997 , thank you for answer.
I checked permissions but it not helps. 500 error still return mixed html + json in body

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by luk4s** [comment]
Hi, currently we still running on version 2x. In staging, I am not able to reproduce any 50x error 🙂

**Comment by dedelkov** [comment]
Was having the same problem on Mautic v4.4.0 with API library v3.0.0.
Cleaning the cache then warming up and updating the permissions solved the issue for me.

Try these on your mautic installation folder:
php bin/console cache:clear
php bin/console cache:warmup

chown -R www-data:www-data .
chmod -R g+rw .
