### ISSUE TITLE
[feature request] Action/decision "type" labels in campaign builder

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#841]
When looking at the campaign builder, I have no idea what type of action or decision something is w/o stating it in the "name".  

See the attached image.
![mautic-campaign-type-labels](https://cloud.githubusercontent.com/assets/113870/9588052/9661ff5e-4feb-11e5-93a1-90b578f425e6.png)

It should be pretty easy to add the "type" to the upper left corner of bubble so its easy to see it.

**Comment by kuzmany** [comment]
vote +1

**Comment by alanhartless** [comment]
Does the name of the event not provide this? You can label the event via the name however you wish.

But I think this probably falls in line with #454 so closing this to "merge" with it.
