### ISSUE TITLE
[BUG] Manually embedded form submits data two times

### ISSUE THREAD

**Issue by Aerendir** [mautic/mautic#8415]
# Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.3
| Browser | Chrome 80.0.3987.87

## Steps to reproduce
1. Create a form
2. Embed it manually on a page outside of Mautic (both the `mautic-form.js` script and the html of the form
3. Submit the data
4. Go to Components > Forms, then click on "View results" in the "Results" column (the one immediately before the ID, on the extreme right of the table)

At this point you should see two entries for one submission.
 
## Log errors
No logs.

# More info

I've tried to not include the script `mautic-form.js` on the page and so the error disappeared.

If the script is present on the page, I see two network requests to the API.

One seems to be cancelled, but anyway I see two entries for one submission.

I've described and debugged the problem extensively on Mautic'forum:
https://forum.mautic.org/t/manually-embedded-form-submits-two-times/12623

There, there are also illustrative images and some thoughts about the problem.

**Comment by RCheesley** [comment]
Closing as marked resolved on the forums:  

> Ok, after a bit of research and digging in the dev tools, I found the double submission was caused by the WordPress plugin AntiSpam by CleanTalk.
> This is a plugin that monitors every form field on a page, preventing the spam.
> Disabling it solved the issue.
