### ISSUE TITLE
Widget "Most hit email redirect" not working

### ISSUE THREAD

**Issue by florentpetitjean** [mautic/mautic#8424]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hello, I can't make the widget : "Most hit email redirect" works. I tried all 3 filters but I always got a blank widget (also not working without filters) : 
![image](https://user-images.githubusercontent.com/49391402/74247035-b9ffeb00-4ce5-11ea-9321-3b1726d7b8b3.png)
Is it a real bug or did I miss something in the configuration (try segments or campaign with real clicks in it)
Thanks

| Q   | A
| --- | ---
| Mautic version | 2.15.2
| PHP version | 
| Browser | Chrome

### Steps to reproduce
1. Do to the Dashboard
2. Open the widget menu 
![image](https://user-images.githubusercontent.com/49391402/74247345-32ff4280-4ce6-11ea-860d-8e3239edf2c0.png)
3. Add the "Most hit email redirect" widget
4. Set some filter with email that got clicked in it
![image](https://user-images.githubusercontent.com/49391402/74247681-bae54c80-4ce6-11ea-9dd7-06b80630a5f8.png)

5. See that the widget stay blank.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
Let's test: https://github.com/mautic/mautic/pull/8460

**Comment by dennisameling** [comment]
Fix landed in 3.0.1 which is scheduled for release on June 29th 🚀
