### ISSUE TITLE
Unable to select form source when creating Campaign 

### ISSUE THREAD

**Issue by FrancisSamo** [mautic/mautic#8427]
## Bug Description
When creating a Campaign with "Campaign forms" as contact source, Mautic can't find any forms created. Evan when I type in the full form name and click add, it wouldn't add it. It just prompts "This value is not valid." as you can see here:
![Mautic 3 0 0 Contact Source Issue](https://user-images.githubusercontent.com/5165185/74289269-e3913480-4d2e-11ea-9cc6-44e213e7300b.gif)

| Q   | A
| --- | ---
| Mautic version | 3.0.0
| PHP version | 7.2
| Browser | Chrome

### Steps to reproduce
1. Create a form first. Shouldn't be a Problem!
2. Start creating a Campaign.
3. Open Campaign Builder and choose "Campaign forms" as contact source.
4. Search for the previously created form - GOOD LUCK 😜
 
### Log errors
No Mautic Log error, nor Browser console errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
I am able to reproduce ! Thanks for catching it !
