### ISSUE TITLE
Uncorrect API answer (500) when wrong callback URL with OAuth2

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#8437]
## Bug Description
API returns error 500 when trying to authenticate with wrong callback URL. Maybe we could have a clearer answer, 500 let's believe mautic server has an issue.

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 
| Browser |

**Comment by dennisameling** [comment]
@npracht Is this for OAuth1a or OAuth2? Or both?

**Comment by npracht** [comment]
OAuth2, didn't test OAuth1a

**Comment by RCheesley** [comment]
Hi there @npracht, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.2?
Thanks!

**Comment by npracht** [comment]
@kuzmany can you tell if this is still relevant for M3?

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
