### ISSUE TITLE
resubscribe form

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#844]
When I click unsubscribe form a mail...

I have configured a form to ask the reason and send the user the last email (goodbye email).

I want say "If it is one error you can resubscribe doing.... " 

how the user can resubscribe to the mailing?

**Comment by alanhartless** [comment]
There is a URL embedded in the unsubscribe confirmation page that allows the user to resubscribe and includes a message very similar to that.  In 1.2.0, the message will be configurable via Mautic's Configuration rather than hard coded as a translation string.
