### ISSUE TITLE
Filter contacts by Event Name

### ISSUE THREAD

**Issue by mimikama** [mautic/mautic#8445]
Hello to all,

I would like to filter contacts according to a specific `Event Name` from history. Is this possible, to get a report or to get them directly in contact page?

**Comment by npracht** [comment]
Hi @mimikama ! Thanks fo your message.
The mautic policies requests that all the feature requests, questions and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.

Concerning your message, i don't think it is possible. It could be by creating a new report type. Also it is already possible by API.

Thanks for contributing!

N.
