### ISSUE TITLE
URLs don't replace tokens

### ISSUE THREAD

**Issue by heroic** [mautic/mautic#8446]
## Bug Description
When sending transactional emails, urls may be dynamic. If the configuration is set to allow tracking clicks on urls, then Mautic does not replace tokens in the url, it only replaces them in the text.

Here's a sample email

```
<a href="https://example.com/email/verify/{EMAIL_VERIFICATION_CODE}" rel="noopener noreferrer" target="_blank">https://example.com/email/verify/{EMAIL_VERIFICATION_CODE}</a>
```

This results in:

```
<a href="https://mautic.example.com/r/hadshedcontent?ct=jkgqfyegwkfyg" rel="noopener noreferrer" target="_blank">https://example.com/email/verify/theTokenValue</a>
```

The redirected url is:
```
https://example.com/email/verify/%7BEMAIL_VERIFICATION_CODE%7D
```

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 7.1
| Browser | Chrome

### Steps to reproduce
1. Create an email with an "A" tag with href containing a token
2. Send the email
3. URL does not have the token replaced.
4. Disable link tracking and the token in the URL gets replaced as expected.

**Comment by dennisameling** [comment]
@heroic Thanks for your bug report! Could you please let us know whether you had this issue with Mautic 2.15.3 as well, or did you just start using Mautic with the 2.16.0 version? I'm just trying to understand whether this is a regression (as in, it was working in 2.15.3) or a bug that affects multiple versions of Mautic. Thanks in advance!

**Comment by npracht** [comment]
Hi @heroic can you please try this PR, I think it should solve your issue.

**Comment by heroic** [comment]
@dennisameling I just started with 2.16.0

@npracht Which PR?

**Comment by npracht** [comment]
https://github.com/mautic/mautic/issues/7548
