### ISSUE TITLE
2.16 | Company Name Personalisation Tag Doesn't Pull Through Data

### ISSUE THREAD

**Issue by cyanstar** [mautic/mautic#8458]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Unable to use the {contactfield=companyname} personalisation tag via dynamic content and emails. The personalisation part just doesn't appear if the filter parameters are meant. The default / fallback does work if the filters aren't met. 

I'm working on a clean install of Mautic 2.16 that is linked to a Wordpress website. The WP site is using dynamic content as apart of the home page etc. 

| Q   | A
| --- | ---
| Mautic version |  2.16.0

### Steps to reproduce
1. Create any dynamic content or email using the above personalisation tag.

There seems to be a few issues around the Company Name field. Was anything changed between 2.15 and 2.16? I've had a few issues related to API and forms since updating from 2.15.0 to 2.15.3 and 2.16. 
 
### Log errors

None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @cyanstar can you add screenshots of your DC configuration?
Thanks

**Comment by cyanstar** [comment]
Hi @npracht I'm using a bitnami LAMP stack with the mautic install in it. What's weird is the personalisation tags work fine IE contact name, email etc. It's just the company name one that doesn't. 

It does work in forms, however. So if we're asking for a company name in the form, if the field has Auto fill data enabled, it is pulling it properly. 

_Side note, the descriptor on the auto fill data, states it'll only work on landing Mautic landing pages, even though I have mautic installed separately and the form embed on a Wordpress site. Does that need updating?_

![auto-fill-descriptor](https://user-images.githubusercontent.com/10960390/78127813-bac31c80-740c-11ea-8002-1fac6633914f.PNG)

**Comment by RCheesley** [comment]
@cyanstar I wondered if you can confirm whether this is persisting in the latest release?

**Comment by npracht** [comment]
Closing for lack of feedback. If more later, we'll re-open the issue.
