### ISSUE TITLE
Mail attachment not sent

### ISSUE THREAD

**Issue by nosyminotaur** [mautic/mautic#8461]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

| Q   | A
| --- | ---
| Mautic version | 2.16 
| PHP version | 7.0
| Browser | Firefox

### Steps to reproduce
1. Create a template email. 
2. Attach a file to the email on the advanced tab, send it through a campaign or manually to a user
3. The email is received, but, the attachment is not attached.
4. If a test mail is sent from the email template page, an attachment is sent.
This means that the bug isn't in my mail server.
I'm using a custom mail server of my company's domain, if that matters.
 
### Log errors
No errors 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
>If a test mail is sent from the email template page, an attachment is sent.

Hi @nosyminotaur what does that mean? Could add screenshots?

**Comment by nosyminotaur** [comment]
If we send a direct email from the contacts tab, no attachment is sent.
The attachment is sent as a link instead.
While sending the attachment from the email template page, or through a campaign, the attachment is sent.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
