### ISSUE TITLE
Undefined class constant ON_CAMPAIGN_ACTION_ADD_DONOTCONTACT

### ISSUE THREAD

**Issue by petebytes** [mautic/mautic#8463]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Error 'The site is currently offline due to encountering an error' after upgrading to 2.16.0

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 7.2.24
| Browser | Multiple

### Steps to reproduce
php app/console cache:clear
php app/console mautic:update:find
php app/console mautic:update:apply
php app/console cache:clear 

### Log errors
Symfony\Component\Debug\Exception\FatalThrowableError: Undefined class constant 'ON_CAMPAIGN_ACTION_ADD_DONOTCONTACT' - in file /app/app/bundles/LeadBundle/EventListener/CampaignActionDNCSubscriber.php - at line 56

Seems to be related to https://github.com/mautic/mautic/pull/7567

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @petebytes could you please test https://github.com/mautic/mautic/pull/8434 ?

**Comment by petebytes** [comment]
@npracht love to test #8434
How do I apply this PR to my deployed Mautic instance installed using wget not git?
Thanks

**Comment by npracht** [comment]
@dennisameling you can help for that ?

**Comment by petebytes** [comment]
@npracht I manually replaced the 3 files, cleared cache then restarted the app.

Now seeing
```[21-Feb-2020 20:29:45 UTC] Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "ConfigSubscriber" from namespace "Mautic\FormBundle\EventListener".
Did you forget a "use" statement for e.g. "Mautic\PageBundle\EventListener\ConfigSubscriber", "Mautic\CampaignBundle\EventListener\ConfigSubscriber", "Mautic\SmsBundle\EventListener\ConfigSubscriber", "Mautic\ApiBundle\EventListener\ConfigSubscriber", "Mautic\WebhookBundle\EventListener\ConfigSubscriber", "Mautic\UserBundle\EventListener\ConfigSubscriber", "Mautic\CoreBundle\EventListener\ConfigSubscriber", "Mautic\AssetBundle\EventListener\ConfigSubscriber", "Mautic\EmailBundle\EventListener\ConfigSubscriber", "Mautic\ReportBundle\EventListener\ConfigSubscriber", "Mautic\LeadBundle\EventListener\ConfigSubscriber", "Mautic\QueueBundle\EventListener\ConfigSubscriber", "Mautic\ConfigBundle\EventListener\ConfigSubscriber" or "MauticPlugin\MauticSocialBundle\EventListener\ConfigSubscriber"? - in file /app/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php - at line 138
172.17.0.1 - - [21/Feb/2020:20:29:45 +0000] "GET /media/css/app.css HTTP/1.1" 200 21457 "https://mautic.launchmuse.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/82.0.4065.1 Safari/537.36
[21-Feb-2020 20:29:54 UTC] Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "ConfigSubscriber" from namespace "Mautic\FormBundle\EventListener".
Did you forget a "use" statement for e.g. "Mautic\PageBundle\EventListener\ConfigSubscriber", "Mautic\CampaignBundle\EventListener\ConfigSubscriber", "Mautic\SmsBundle\EventListener\ConfigSubscriber", "Mautic\ApiBundle\EventListener\ConfigSubscriber", "Mautic\WebhookBundle\EventListener\ConfigSubscriber", "Mautic\UserBundle\EventListener\ConfigSubscriber", "Mautic\CoreBundle\EventListener\ConfigSubscriber", "Mautic\AssetBundle\EventListener\ConfigSubscriber", "Mautic\EmailBundle\EventListener\ConfigSubscriber", "Mautic\ReportBundle\EventListener\ConfigSubscriber", "Mautic\LeadBundle\EventListener\ConfigSubscriber", "Mautic\QueueBundle\EventListener\ConfigSubscriber", "Mautic\ConfigBundle\EventListener\ConfigSubscriber" or "MauticPlugin\MauticSocialBundle\EventListener\ConfigSubscriber"? - in file /app/vendor/symfony/event-dispatcher/ContainerAwareEventDispatcher.php - at line 138
172.17.0.1 - - [21/Feb/2020:20:29:54 +0000] "GET / HTTP/1.1" 500 1124 "https://mautic.launchmuse.com" "Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)

**Comment by kuzmany** [comment]
Your update was not successful. 
You have to check 

app\bundles\LeadBundle\LeadEvents.php

https://github.com/mautic/mautic/blob/8c8f017efe2dfbf145d92f11844622591585bfd8/app/bundles/LeadBundle/LeadEvents.php#L470

Two constants probably missing

ON_CAMPAIGN_ACTION_ADD_DONOTCONTACT 
ON_CAMPAIGN_ACTION_REMOVE_DONOTCONTACT 

Or missing use statement here

https://github.com/mautic/mautic/blob/eadf3d58ce85d20544e0d9c0f694dfe477a0d3b9/app/bundles/LeadBundle/EventListener/CampaignActionDNCSubscriber.php#L20

**Comment by petebytes** [comment]
Thaks for the assistance.
I was unable to fix the server, built new one and migrated data.
