### ISSUE TITLE
filters on category type is inefficient

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#8465]
## Bug Description
In the menu categories, you have a filter but it is inefficient. When you use it, it shows all results anyway.

| Q   | A
| --- | ---
| Mautic version | https://m3.mautibox.com/3.x/
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create 2 categories with different type
2. Filter in the categories list view on one of those 2 types
3. See both results

**To be tested on local environment, i don't know if this is because of mautibox or not because i see jQuery issues in console.**

**Comment by lukassykora** [comment]
@npracht please, review this PR: https://github.com/mautic/mautic/pull/8479
