### ISSUE TITLE
In the API response Page.Videohit events do not contain a related ContactID 

### ISSUE THREAD

**Issue by MajesteitBart** [mautic/mautic#8468]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
In the api response of /api/contacts/activity, every single event contains a reference to the related contact using contactID, except for page.videohit events.

![image](https://user-images.githubusercontent.com/8057288/75156140-c20e5080-5711-11ea-86a7-185d35b67cc2.png)

| Q   | A
| --- | ---
| Mautic version  | 2.16.0
| PHP Version  | 7.1.32

### Steps to reproduce
1. Watch video that is being tracked by Mautic using <video data-mautic-video="true"></video> tags.
2. GET .../api/contacts/activity 
3. See response of the event, it will not contain a Contact ID, just an event ID.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by MajesteitBart** [comment]
Had to test it first, so it took a while. However, tt seems like this problem still exists in v3.0.2
![image](https://user-images.githubusercontent.com/8057288/90492714-c7d57380-e141-11ea-9957-41f7b244d123.png)

**Comment by RCheesley** [comment]
@MajesteitBart thanks for taking the time to confirm this! Would you consider looking into making a PR to add the missing information if it persists in 3.2.1?

**Comment by MajesteitBart** [comment]
I would gladly help, but I'm not a developer, so it would probably not fix anything 😅
