### ISSUE TITLE
M3: Form submission  fatal error from preview

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#8469]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Just simple form with email field return fatal error

`mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getType() on null" at C:\wamp3-1-4\www\mautic3\app\bundles\FormBundle\Event\SubmissionEvent.php line 275 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getType() on null at C:\\wamp3-1-4\\www\\mautic3\\app\\bundles\\FormBundle\\Event\\SubmissionEvent.php:275)`

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by mtshaw3** [comment]
PR: https://github.com/mautic/mautic/pull/8474
