### ISSUE TITLE
update bit.ly api to v4

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#8471]
## Bug Description
According to bit.ly communication, their API v3 used by mautic will reach EOL in 5 days.
>We've updated our API to v4 (version 4), and it's important that you're connecting to Bitly using this latest version, because all old versions will stop working when we shut them off on March 1, 2020.

| Q   | A
| --- | ---
| Mautic version | any
| PHP version | 
| Browser | 

I found it only here in code ?
https://github.com/mautic/mautic/blob/f7eff0d188b1c9d246324bfb3df3e143bc8c738b/app/bundles/CoreBundle/Translations/en_US/messages.ini#L105

**Does it means we just need to change the text in the tooltip and ask users to update their configuration?**
**---> Maybe a migration script to update URLs saved in users DB?**

**Comment by escopecz** [comment]
The main change I see from the docs is in the authentication. It will need deeper code changes. The URL is being used in https://github.com/mautic/mautic/blob/17d135145049501b15a3dfc3d07a1b7fc4f1acdb/app/bundles/CoreBundle/Helper/UrlHelper.php#L44

**Comment by alanhartless** [comment]
Yea, this will now require a decent refactoring of this feature that will require new events, new config options to keep BC with current implementation and a new bit.ly integration that hooks into an oauth2 authentication process.

**Comment by florentpetitjean** [comment]
Hello any news on this transition ?
Thanks

**Comment by RaianHN** [comment]
is this going to be updated to v4 or do we get patch for 2.16.2 release ?

**Comment by solomojo** [comment]
@npracht is this ready to be tested or worked on?  If so, I have a team who can help out.  We are eager to have the URL shortening functionality restored in Mautic for our SMS Campaigns.

**Comment by npracht** [comment]
Hi @solomojo this has not been done yet. We would be very excited to have your help. Can i assign this issue to you ?

**Comment by npracht** [comment]
We finally have the final date for bitly update:
>In early 2019, the Bitly API was updated to V4. Bitly no longer supports older versions of the API, and outdated connections will be phased out by September 14, 2020.


https://support.bitly.com/hc/en-us/articles/360004395631-Migrating-from-V3-to-V4-of-the-Bitly-API

@RCheesley it means that it should be addressed in 3.1.0 latest.

**Comment by npracht** [comment]
@solomojo did you have the opportunity to work on this ?

**Comment by mabumusa1** [comment]
@solomojo I was wondering if you had the chance to work on this issue?

**Comment by jobiaya** [comment]
Hey Mautic Community,

I found an alternative solution that I thought I'd share. I use [Polr](https://polrproject.org/) which is an open source url shortener. The installation is pretty easy and works just as well as bit.ly.

INSTALLATION INSTRUCTION: https://docs.polrproject.org/en/latest/user-guide/installation/
INSTALLATION TUTORIAL: https://www.youtube.com/watch?v=4mxR2WsKYt4

**IMPORTANT NOTES:** 

1. There's been reports of technical issues when trying to install it with PHP 8.0+. I used 7.4 and it was fine, but never tried a higher version. 
2. Also, when going through the setup screen after initial install do NOT set the admin username or email...only the password. If you try to set username or password it will throw the error "Whoops something went wrong".
3. Obviously, make sure to activate the API key feature.
4. Increase the API call limit. The default is 60 per minute, but probably won't be a lot probably won't be enough as it issues an individual url link to each person that gets a text.
5. Finally, use the following format when putting the the url shortener query link in Mautic. "**_http://example.com/api/v2/action/shorten?key=[API_KEY]&response_type=plain_text&url=_**" (Make sure to add the "=" sign on to the end of the url or it won't work.)

I struggled for a few days trying to figure a work around, so I hope this solution helps someone else.

**Comment by fastyzfr1** [comment]
+1 on this issue. I know that this is an open source project. Yet I am not sure why it wouldn't be completed by now. The new API and authentication was released over a year ago.

@jobiaya how are you hosting your Mautic version? Is it on AWS, Bitnami or self hosted? That might make a difference on installation.

**Comment by RCheesley** [comment]
Hey there! It hasn't been worked on because very few people use this feature therefore it is low priority for the core team given the huge workload just to keep pace with the mandatory updates we have to do, and no developers have decided to work on it from the community.

Perhaps consider adding a bounty if you want to have someone pick this up, or if it is urgent for you, feel free to hire a freelancer and have them contribute it back as a PR.

**Comment by jobiaya** [comment]
Self host

**Comment by fastyzfr1** [comment]
@RCheesley Got it. Makes sense to me.

I already created a patch to test if it is a bitly link and to send a post command with the authorization in the header. I did it for v3 and v4. I didn't realize my bitnami install had version 3.3 whereas the github version was 4.

V4 uses guzzlehttp which I am very familiar with, whereas v3.3 uses Joomla/http/http and I didn't know much about. So my patch worked when I tested locally but on my install it didn't due to the different http classes. However, I was able to fix that fairly easy.

It is working now on my server though. Just ran through some tests. It looks for bitly.com in the url string and parses it to get the access token, then sends to bitly api and returns the new link on success.

**Comment by RCheesley** [comment]
@fastyzfr1 if you would like to make a PR for the team to review that would be great.  We have some documentation here: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests - please make it against the Features branch as we are preparing for the Mautic 4 release on that branch.

Shout on the Mautic 4 (mautic-4) or Product Team (t-product) channel on Slack (https://mautic.org/slack) if you need any help!

**Comment by fastyzfr1** [comment]
@RCheesley I would love to make a PR. However, I am not sure I want to contribute to Acquia. This may sound horrible but I was burned by Acquia and even though I love Mautic (before Acquia acquisition), I would have a hard time contributing to a company that would burn bridges as they did.
(Acquia is in the MAUTIC CONTRIBUTOR AGREEMENT)
I will not contribute to them making a profit and I was saddened to see them purchase the rights of the software. I thought it would keep it open source status without their involvement.

**Comment by RCheesley** [comment]
Ok sorry to hear that. We will just have to wait for someone who is willing to contribute a PR before this issue will be addressed, in that case.

**Comment by npracht** [comment]
Dear all, plugin is ready to test ---> https://github.com/mautic/mautic/pull/12312

**Comment by npracht** [comment]
I close it, it'll be published on marketplace soon.
