### ISSUE TITLE
[feature request] Insert leadfields/extras/assets/etc... to email body without builder

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#848]
Right now, the only way to easily add eadfields/extras/assets/landingpages to an email is to use the email builder.

It would be nice to be able to easily add these items to the body of an email w/o the builder.

**Comment by alanhartless** [comment]
You can by using the token lookup.  Starting typing `{lead` in the editor and all the lead field tokens will appear to choose from.  Same with `{page`, `{asset`, `{form`, etc.  If you want to search by label instead such as the lead field name, page title, etc, use `{@start of the label/title`.

**Comment by that0n3guy** [comment]
Oh snap.... sweet. Ok, so a description needs to be added to the `/emails/new page`.

Is that documented anywhere?

**Comment by that0n3guy** [comment]
Found a blog post about this: https://www.mautic.org/blog/tip-of-the-week-insert-fields/

Needs to get added to documentation....

**Comment by drmmr763** [comment]
No doubt it needs to be documented; but I'm gonna close this as an issue.
