### ISSUE TITLE
[UI fix] Asset search engine visibility switch should have colours reversed

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8481]
## Bug Description
Generally when working with assets in Mautic, hiding them from search engines is the desired state, because otherwise people could access your resources without going through the processes you have in place.

Currently, we have the switch to decide if an asset should be made available in search engines showing 'yes' as green and 'no' as red.

I believe this signals yes as being desirable, and no being undesirable, when in fact it should be the other way round.

![screenshot-m3 mautibox com-2020 02 28-13_25_17](https://user-images.githubusercontent.com/2930593/75552432-31e04c00-5a2e-11ea-9a04-98b59efe3291.png)

Super easy fix no doubt!

| Q   | A
| --- | ---
| Mautic version | 3.0 beta
| PHP version | 7.2
| Browser | Chrome

### Steps to reproduce
1. Create or edit asset
2. View the switch for search engine visibility and notice the green/red options seem reversed.

**Comment by npracht** [comment]
Then i think it is more a question of wording also.
We should have a positive way to structure the sentence.

"Enable indexing asset on search engine"
Yes = green
No = red

____
Why ? Having yes in red sounds not logic to me.

**Comment by RCheesley** [comment]
In terms of why the suggestion to switch the colours, for the reasons mentioned above: 

> Generally when working with assets in Mautic, **hiding** them from search engines is the desired state, because otherwise people could access your resources without going through the processes you have in place.

So, saying 'yes, please index this in search engines' is not a good thing.

The suggestion to change the colour of the switch was because generally Red = danger, green = safety. 

I do see what you mean by yes = green as well, so perhaps it's a personal preference / opinion.

**Comment by npracht** [comment]
It is counter intuitive in terms of UX, when you go to red it is negative action, green is positive.

Also from a marketing automation perspective, if you host an asset, most of the time it is to offer it after a form submission, which means you don't want it indexed as far as it is a private asset (you expect an email address against).

**Comment by RCheesley** [comment]
OK! Makes sense :)

**Comment by npracht** [comment]
Beside that, i still believe you are right, we should change the text. It should be turned positively to:
"Enable indexing asset on search engine"
* Yes = green
* No = red

Today it is negative : "block indexing, etc.."
