### ISSUE TITLE
Line alignment seems off in page activity history on page overview

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8483]
## Bug Description
On the page overview for a landing page in M3 (on Mautibox), it seems like the line on the page activity history display is a little off-centre and the text is in the wrong place. 

![screenshot-m3 mautibox com-2020 02 28-17_02_27](https://user-images.githubusercontent.com/2930593/75569109-6bc04b00-5a4c-11ea-8a01-562cf733b88a.png)

On Mautibox with a 2.x test environment it appears central so I think this is a UI bug.

![screenshot-mautibox com-2020 02 28-17_10_00](https://user-images.githubusercontent.com/2930593/75569549-38ca8700-5a4d-11ea-9d0a-eb63f23a9c0f.png)

| Q   | A
| --- | ---
| Mautic version | 3.0 beta
| PHP version | 7.2
| Browser | Chrome

### Steps to reproduce
1. Open landing page with more than one activity history entry
2. Check out the wonky line :)

**Comment by hluchas** [comment]
after short investigation i found that fixing `CoreBundle\Assets\css\app.css:1528` with
```
.media-list.media-list-bubble > .media .media-object {
  ...
  padding-right: 0;
  margin-right: 10px;
}
```
fixes position of figures (icons), but not text itself

**Comment by anton-vlasenko** [comment]
PR: https://github.com/mautic/mautic/pull/8562
