### ISSUE TITLE
Mautic 3: Unable to connect with TLS encryption to Amazon or PostMark SMTP

### ISSUE THREAD

**Issue by ivanionut** [mautic/mautic#8484]
Hi,
i am trying to configure Mautic 3 (beta) and Amazon SES for the first time but i get the following error:

![mautic error](https://hostr.co/file/fRlHXlUSdpq1/mautic_error.png)

Do you have any advice?

Thank you!

**Comment by alanhartless** [comment]
Are you able to reproduce this in Mautic 2? The error suggests more a connection issue than a code issue.

**Comment by ivanionut** [comment]
Hi @alanhartless 

I have tried to install 2.16.0 version and I have the same problem. Could this be due to some PHP configuration (7.3.15)? 😕

**Comment by ivanionut** [comment]
mmhhh, exactly the same problem with PostMark.
Do I need to do any particular php / openssl configuration?


![postmark](https://hostr.co/file/oslZN39TdEAW/mautic_postmark.png)

**Comment by ghost** [comment]
Found a solution here: https://stackoverflow.com/questions/37280019/mautic-unable-to-connect-with-tls-smtp

**Comment by RCheesley** [comment]
@nancorrea thanks for sharing the link, content below for ease of reference:

> The problem is TLS version constant defined in SwiftMailer (STREAM_CRYPTO_METHOD_TLS_CLIENT). For backwards compatibility it points to 1.0 v. of TLS. You can change STREAM_CRYPTO_METHOD_TLS_CLIENT to STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT (or other version) in `/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php`.

There are suggestions for a [hotfix and for longer term solutions](https://github.com/swiftmailer/swiftmailer/issues/598). Looks like a fix is already shipped in a later version of Swiftmailer ([maybe 6.1.0](https://github.com/swiftmailer/swiftmailer/pull/935#issuecomment-382671760)?) according to [this PR](https://github.com/swiftmailer/swiftmailer/pull/935).

We are currently on 3.3 of the Symfony Swiftmailer bundle so this may need a pretty big dependency bump as I understand it - something for the Product Team to consider.
