### ISSUE TITLE
Three language strings missing for Companies layout

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8487]
## Bug Description

Strings read properly however it is throwing a warning (see attachment below)
![image (4)](https://user-images.githubusercontent.com/2930593/75610952-db4a3f00-5b0d-11ea-8b85-e058a196798e.png)

| Q   | A
| --- | ---
| Mautic version | 3.0 beta
| PHP version | 7.2.24
| Browser | Chrome

### Steps to reproduce
1. Go to companies and open one
2. Check for untranslated strings

**Comment by RCheesley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Companies > Ensure all language strings are properly translated (labels and field default text/tooltips)](https://trello.com/c/0q59DSFr/272-companies-ensure-all-language-strings-are-properly-translated-labels-and-field-default-text-tooltips)

**Comment by alanhartless** [comment]
Looks like these are translated strings that are being translated again and OK to ignore for now as we do this often in Mautic. 

/cc @mtshaw3
