### ISSUE TITLE
media-body cs class is off in M3 (used in recent activity lists and contact notes)

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8490]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
View any detail page that has a "recent activity" timeline and you'll see that the details no longer align to the right of the bullets. 

| Q   | A
| --- | ---
| Mautic version | 3.0 beta
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Go to a email details page (or any other details page such as forms; create an entity if it doesn't exist)
2. Look to the right notice the timeline UI is off compared to M2
3. Also go to a contact details page, click on the notes tab and create a new note. 

<img width="373" alt="Screen Shot 2020-02-29 at 15 32 04" src="https://user-images.githubusercontent.com/63312/75615455-7856a900-5b09-11ea-95b0-84481d81b721.png">
<img width="668" alt="Screen Shot 2020-03-01 at 19 27 22" src="https://user-images.githubusercontent.com/63312/75638784-428def00-5bf3-11ea-90f4-581b87d6f3e7.png">

**Comment by RCheesley** [comment]
I think maybe this is related to #8483

**Comment by lukassykora** [comment]
PR: https://github.com/mautic/mautic/pull/8553
