### ISSUE TITLE
Cannot delete multiple forms

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#8495]
When I go to the list of forms, select multiple and try to delete them I get this 500 error:

`FormID can't be null`

at https://github.com/mautic/mautic/blob/3.x/app/bundles/FormBundle/Helper/FormUploader.php#L141

request:
`https://mautic.test/index_dev.php/s/forms/batchDelete?ids=[%22420%22,%22421%22,%22422%22,%22423%22,%22424%22,%22425%22,%22426%22,%22427%22,%22428%22,%22429%22,%22430%22,%22431%22,%22432%22,%22433%22,%22434%22,%22435%22,%22436%22,%22437%22,%22438%22,%22439%22,%22440%22,%22441%22,%22442%22,%22443%22,%22444%22,%22445%22]&mauticUserLastActive=1&mauticLastNotificationId=311`

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Forms > Delete multiple forms from list (warning: deletes forms!)](https://trello.com/c/OH4upEPo/164-forms-delete-multiple-forms-from-list-warning-deletes-forms)
