### ISSUE TITLE
Form filter has:results 500 error

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#8496]
Go to the list of forms and search for `has:results` forms. It errors with `Too many parameters: the query defines 0 parameters and you bound 1` at `vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:105`

Same happens when using the `name:*` search.

**Comment by lukassykora** [comment]
It is solved by this PR: https://github.com/mautic/mautic/pull/8525/files

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Forms > Search filter - check all search query variables work](https://trello.com/c/5DgM3DOT/171-forms-search-filter-check-all-search-query-variables-work)
