### ISSUE TITLE
Sequential Conditional Firing Issues

### ISSUE THREAD

**Issue by zackrspv** [mautic/mautic#8503]
## Bug Description
When using multiple conditions within a campaign flow (such as for a menu), the conditions fire sequentially, as planned, but for every antecedent failure, all previous positive conditions also fire, instead of only that one condition that's true.  For example, let's assume you have a campaign with a condition of 'Day equal 1' and tie that positive event to a jump event ('send to day 1') and then have the negative branch tie to another condition 'Day equal 2' and tie that positive step to a jump event ('send to day 2'). If you send a contact THROUGH the campaign and their 'Day' is equal to 1, it correctly jumps to the event. If you send a contact through and it's 'Day' is equal to 2, it correctly sends to Day 2, but also fires Day 1's success. So in this case, both jump events fire. 

| Q   | A
| --- | ---
|Mautic Version |  2.1.6 | 
| PHP Version | 7.2.28. | 
| Browser | Chrome| 

### Steps to reproduce
1. Create a blank segment, name it 'Test'
2. Create a custom field with the name of 'Day'
3. Create two contacts. Set the first contact to have a Day of 1, set the second contact to have a Day of 2
4. Create a campaign that is based on the 'Test' segment
5. Add a condition to the first step of the campaign. Make it based on the contact field value 'Day' and set it to 'equals' and '1'
6. Create a non connected action, such as 'Send Email' and label it 'Email 1'
7. Set the Positive event for step 5 to be a Jump Action that jumps to the 'Email 1' action
8. Set the negative event for step 5 to be another conditional that is based on the contact field value
9. Set that contact field value to be 'Day' 'equals' and then '2'
10. Create a non connected action, such as 'Send Email' and label it 'Email 2'
11. Set the positive event for step 9 to be a Jump Event to 'Email 2'
12. Connect Email 1 and Email 2
13. Add a 1 day delay to Email 2
14. Publish the campaign

Now, add your day 1 contact to the Test Segment. 
Watch as it sends Email 1, and schedules Email 2 a day later

Now, add your day 2 contact to the Test segment. 
Watch as it sends Email 1, and sends Email 2, and schedules email 2 a day later. 

It shouldn't be triggering email 1 at all, as it should have taken the negative branch. 
 
### Log errors
No log errors

### Example Campaign (very detailed)
![examplecampaign](https://user-images.githubusercontent.com/1069198/75695908-9b936c80-5c5f-11ea-8d61-b7cf45f337d8.png)
In this campaign there are several actions that are taking place. This is a 20 day campaign that sends an email per day, and updates the 'Day' counter every time an email is sent. There is also a commander section of the campaign on the LEFT hand side that fires whenever someone is added to the campaign. This commander section allows us to add people to the necessary DAY based on when they JOINED the campaign. For example, if they joined on day 1, they'd start on Day 1. If they joined on Day 5, they'd start on Day 5 (skipping all the previous emails). 

Unfortunately, that's now how it's working right now. Right now, if someone joins on Day 5, they get all the previous emails too, because for some reason, if it flows down the NEGATIVE path, it still triggers the positive actions of each individual preceding action.

**Comment by RCheesley** [comment]
Hi @zackrspv thanks so much for the detailed bug report! Can you confirm if this persists in Mautic 3.0.1?

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
