### ISSUE TITLE
Email dynamic content fails validation the first save

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8505]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When saving a new variant in an email for dynamic content, it fails validation (without any errors) but the operators are different after going back into the builder. It seems that the JS generated operators are switched then are correct after the form is rendered from the server. 

| Q   | A
| --- | ---
| Mautic version | 3 beta
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Create a new email
2. Open the builder
3. Drag and drop a dynamic content slot onto the preview
4. Click on the Dynamic Content
5. Click Add Variant in the Customize Slot
6. Add a "Country" filter and select `!=`
7. Close the builder and save and close (fill in the rest of the required info if applicable)
8. The form will not save
9. Open the builder and click on the Dynamic Content to edit it
10. Click the Variation 1 tab and note that the operators are now words, not symbols. 
11. Select Not equals, close the builder and save. 
12. This time it saves. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Channels/Emails > Insert Dynamic content and test sending to 2 contacts with different variants](https://trello.com/c/pPQdzYEQ/229-channels-emails-insert-dynamic-content-and-test-sending-to-2-contacts-with-different-variants)

**Comment by lukassykora** [comment]
PR: https://github.com/mautic/mautic/pull/8524
