### ISSUE TITLE
A/B tests "Make winner" for landing pages does not work

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8508]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This is an existing issue in M2 that persist in M3. A/B tests generally work for landing pages (although the criteria is a bit outdated). But, one cannot set one as the winner due to an exception that setVariantSentCount method is not defined. 

| Q   | A
| --- | ---
| Mautic version | 2.16/3.0
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Create a landing page
2. Create an A/B test of that landing page, chose 50% weight and lowest bounce rate as the criteria. Publish and save
3. Open incognito browser and go the landing page's URL
4. Open developer tools and delete the cookies
5. Go the URL again and you should get the opposite test
6. Go back to Mautic and check the landing page details
7. There should be a button with a trophy on it in teh variants tab. Click on it. Notice that 1) the button is not translated but 2) once clicked, an error occurs

### Log errors
```
Uncaught PHP Exception InvalidArgumentException: "Method setVariantSentCount not exists" at /var/app/current/code/pulls/3.x/app/bundles/CoreBundle/Entity/CommonEntity.php line 44
Hide context    Hide trace
[▼
  "exception" => InvalidArgumentException {#2023 ▶}
]
{▼
  /var/app/current/code/pulls/3.x/app/bundles/CoreBundle/Entity/CommonEntity.php:44 {▼
    › 
    ›     throw new \InvalidArgumentException('Method '.$name.' not exists');
    › }
  }
  /var/app/current/code/pulls/3.x/var/cache/dev/doctrine/orm/Proxies/__CG__MauticPageBundleEntityPage.php:864 {▶}
  /var/app/current/code/pulls/3.x/app/bundles/CoreBundle/Model/VariantModelTrait.php:51 {▶}
  /var/app/current/code/pulls/3.x/app/bundles/PageBundle/Controller/PageController.php:944 {▶}
  /var/app/current/code/pulls/3.x/app/bundles/CoreBundle/Controller/CommonController.php:449 {▶}
  /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/HttpKernel.php:151 {▶}
  /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/HttpKernel.php:68 {▶}
  /var/app/current/code/pulls/3.x/vendor/symfony/http-kernel/Kernel.php:200 {▶}
  /var/app/current/code/pulls/3.x/app/AppKernel.php:135 {▶}
  /var/app/current/code/pulls/3.x/app/middlewares/CORSMiddleware.php:91 {▶}
  /var/app/current/code/pulls/3.x/app/middlewares/CatchExceptionMiddleware.php:43 {▶}
  /var/app/current/code/pulls/3.x/app/middlewares/Dev/IpRestrictMiddleware.php:64 {▶}
  /var/app/current/code/pulls/3.x/app/middlewares/VersionCheckMiddleware.php:52 {▶}
  /var/app/current/code/pulls/3.x/app/middlewares/TrustMiddleware.php:51 {▶}
  /var/app/current/code/pulls/3.x/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 {▶}
  /var/app/current/code/pulls/3.x/vendor/stack/run/src/Stack/run.php:13 {▶}
  /var/app/current/code/pulls/3.x/index_dev.php:25 {▶}
  /var/app/current/code/pulls/3.x/index.php:6 {▶}
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Landing Pages > Add A/B Test (please check all options work and check stats)](https://trello.com/c/reV5ny3D/268-landing-pages-add-a-b-test-please-check-all-options-work-and-check-stats)

**Comment by RCheesley** [comment]
@alanhartless another one we need to check to see if it persists!
