### ISSUE TITLE
Programmatically searching for leads by using the value of a custom field does not seem to work

### ISSUE THREAD

**Issue by StEtz** [mautic/mautic#8509]
## Bug Description
I am not sure if this is actually a bug or if I am doing something wrong. If so, please correct me and close the ticket.

I added a custom field in the Mautic leads table (and activated the "Is Unique Identifier" switch).
The idea is that I want to be able to filter for lead entries with a given value in this field. 
This shall happen inside a plugin which I write.

Therefore the code I use is this one:
`
    $leadRepository = $this->entityManager->getRepository(Lead::class);
    $filter = [ 'mycustomfield' => $key ];
    $result = $leadRepository ->findOneBy( $filter );
`

When executing this code I get the error message:
`
  [Doctrine\ORM\ORMException]
  Unrecognized field: mycustomfield
`

As said I am not sure if this is a bug or I am doing something wrong. But when using a "standard" field, such as "id" or "Email" (something which is part of the standard column set of the Lead table) it works. 

| Q   | A
| --- | ---
| Mautic version | Mautic 3.x alpha (downloaded on the 11.Jan) (developer mode)
| PHP version | 7.2.25
| Browser | Firefox 73.0.1 (64-Bit) Windows 10

### Steps to reproduce
1. Add a custom field the lead table 
2. Tick the option "Is Unique Identifier"
3. Execute the php code from above in any php section inside Mautic (e. g. a Command in a test plugin which can be called from the command line)
4. You should get the error message
 
### Log errors
See my description

**Comment by RCheesley** [comment]
Hi there, does this persist on 3.0.1?

**Comment by StEtz** [comment]
Hi,

I would need to test it with the latest version, because I am currently working with a 2.6 installation.
However if you follow the steps from my description, you can easily test it. Maybe you want to ask a developer to check it?

Something else:
I just tried to install the latest version of Mautic on an AWS EC2 instance (on an Ubunty 20.04-amd64-server instance) and there I am getting an error after the installation. Once the installation is finished and Mautic should redirect me to the login page, I am getting an error message: "Not Found -- The requested URL was not found on this server" and the browser stops with the url "<...>/mautic/s/dashboard". What I would have expected is that I get redirected to the login page...

I did some quick checks and it seems that this issue has been introduced between the git tags 3.0.0-alpha and 3.0.0-beta. I didn't trace it down to the single commit because there are quite a lot in between. Are you aware of this? I can send you my phpinfo if this helps... The apache.log doesn't show anything beside the 404 error message. In case there is anything I can provide to support you, let me know.

If you help me to sort this out I can test the issue with the custom fields in exchange :-)

**Comment by RCheesley** [comment]
Please test with a local instance if you are able :) With over 650 issues to triage we need some help from those reporting to check for whether it exists in Mautic 3.x.

Please look on the Mautic 3.x support forum at https://forum.mautic.org where the 404 issue is being discussed.

**Comment by StEtz** [comment]
Hi,
ok I have solved the 404 issue in my Mautic and performed the test with the latest version (commit id: b584b356315).
And I can repoduce the error with this version.

I have created a simple command plugin which can be installed by your developers to help them to repoduce the problem without much effort.

You can find it here: https://github.com/StEtz/MauticCustomFieldTestCommand

Let me know if you need any more information.

**Comment by RCheesley** [comment]
Thanks for the additional information!

**Comment by adirbnology** [comment]
any update here or workaround ?

**Comment by StEtz** [comment]
Hi adirbnology,

I didn't found a way which made this working using customised fields. 

But a workaround for me was that I did a query of all datasets and then in a for loop the filtering by myself:


        $repo = $this->em->getRepository(Lead::class);
        $es = $repo->getEntities();

        $key = "...";

        foreach($es as $it)
        {
            if($it->get<YourFieldname>() == $key)
            {
                // Process it directly in here or
                // put it into an array for later processing ...
            }
        }

It is not the most efficient way, but it did its job.

**Comment by adirbnology** [comment]
thx @StEtz . it did the job. although im afraid using it in production wont be a great idea . 

@RCheesley r we planning to look into this ?

**Comment by RCheesley** [comment]
@adirbnology we have not got anybody looking into this directly, if someone wants to take ownership please do step up and see if you can look into it in more detail. If it is a bug we have a patch release coming up at the end of the month but would need a PR and to have it tested to be considered for inclusion!

**Comment by escopecz** [comment]
@StEtz you cannot use classic Doctrine ORM for custom fields as Doctrine ORM does not support crating new columns dynamically. Here is the solution:

```php
$leadRepository = $this->entityManager->getRepository(Lead::class);
$leads = $leadRepository->getLeadsByFieldValue('mycustomfield', 'the value');
```

https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Entity/LeadRepository.php#L96
