### ISSUE TITLE
Show what leads read email, opened email, or failed on email details page

### ISSUE THREAD

**Issue by hisaltesse** [mautic/mautic#851]
1. There needs to be a way to view on this sent email page the:
2. list of emails sent, 
3. list of emails read 
4. and emails failed. 
   Maybe add tabs for that below the graph?
5. Also please provide a way to close and go back to the list of email templates

![mautic feedback 1 2b 1](https://cloud.githubusercontent.com/assets/5560918/9620981/0d1926f0-50ef-11e5-8fa9-c56c48aee199.png)

**Comment by troelsfeodor** [comment]
+1

**Comment by ericgopak** [comment]
Is this feature anywhere on the TODO list? Any hints when this could be introduced? Maybe while it is being developed you could share an SQL queries to get these results?

Thank you for all what you're doing! :)

**Comment by npracht** [comment]
@escopecz maybe we can close that in favor of https://github.com/mautic/mautic/issues/3532 ?

**Comment by escopecz** [comment]
I'll close #3532 instead. This issue is older and has more descriptive title. Comment with your ideas from that issue here please.

**Comment by npracht** [comment]
# This issue regroups multiple issues and feature request concerning email stats
As you may see on github issues, statistics are often underlined as not satisfying. Let's make a better brief.
Even in https://github.com/mautic/mautic/pull/3071, a lot has been brought, the ability to have stats email by email directly on email page is very important and easy to use (going through report every time we shoot an email can be annoying).

| Q  | A
| ---| ---
| Bug report? | 
| Feature request? | 
| Enhancement? | x

# Description:
## Complete email stats view to read easily
Today we have:
* a first box with global stats but with no rate (rates are what is needed for a marketer, we don't care of absolute values.
* a 2nd box with tabs with the amount of clics (still no rate)
![capture d ecran 2017-02-27 a 12 22 14](https://cloud.githubusercontent.com/assets/14075239/23359827/72445972-fce8-11e6-8ee1-12b646213f8f.png)
![capture d ecran 2017-02-27 a 12 22 31](https://cloud.githubusercontent.com/assets/14075239/23359825/70bb6780-fce8-11e6-9338-8854596b59e1.png)
## Suggestions
* Move the first zone under a tab "overview"
* Add a tab for stats (rate) by domain name. Very useful in a B2B approach and existing in some competitors (Net-Results)
* Add a tab called "detailed stats" with a table done that way:

| | Sent emails | Read | Clicked | Unsubscribed | Bounces
| ---| ---| ---| ---| ---| ---
| Amount | 
| Ratio | 
| View contacts (button) | 

* Move client (tablet, desktop, mobile) on a second tab "client support"
* Keep the click detail under "click details" with add of a "view contacts" button (issue https://github.com/mautic/mautic/issues/1883)
