### ISSUE TITLE
Text message select lists are empty in Marketing Messages and Send Text Message campaign action

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8513]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Text message drop downs are empty in Marketing Messages and in campaign action's send text message. 

| Q   | A
| --- | ---
| Mautic version | 3.0 beta
| PHP version |  7.3
| Browser | chrome

### Steps to reproduce
1. Add bogus credentials to twilio integration and publish
2. Go to Channels -> Text Messages and create a new one
3. Create a new marketing message, click the Text Message, click Yes and notice the drop down is empty
4. Create a new campaign, and add a send text message action, also notice the drop down is empty

### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by lukassykora** [comment]
PR: https://github.com/mautic/mautic/pull/8542
