### ISSUE TITLE
Marketing message breakdown of who received what channel is empty

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8515]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
After sending a marketing message and viewing the overview, all contacts who received the MM shows up on the Contacts tab. But nothing shows up under the channel tabs. 

| Q   | A
| --- | ---
| Mautic version | 2.16; 3.0
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Create a MM with an email and send through a campaign
2. View the details of the MM and notice that the contacts are listed on the Contacts tab but nothing is listed on the Email tabs. 
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Marketing Messages > Ensure all tabs update when changing date filter on overview](https://trello.com/c/JJn59644/309-marketing-messages-ensure-all-tabs-update-when-changing-date-filter-on-overview)

**Comment by RCheesley** [comment]
@alanhartless was this still a bug in 3.0.2 do you know?

**Comment by npracht** [comment]
Closing for lack of feedback. If more later, we'll re-open the issue.
