### ISSUE TITLE
Category list's type filter defaults to "messages" and does nothing when selected

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8516]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
There's a random "messages" in the category type filter dropdown (/s/categories). It does nothing when selected. I assume it's probably something injected by Marketing Messages. 

| Q   | A
| --- | ---
| Mautic version | 2.16, 3.0 beta
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Go to Categories (/s/categories)
2. Look at the type filter dropdown and it'll default to "messages" instead of "Select."  Changing the type to something else and back causes an empty list. 
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Categories -> Ensure can filter category list by selecting a type](https://trello.com/c/XVVRxoYk/319-categories-ensure-can-filter-category-list-by-selecting-a-type)

**Comment by npracht** [comment]
Could https://github.com/mautic/mautic/pull/8462 fix it ?

**Comment by npracht** [comment]
@kuzmany @alanhartless your opinion ?

**Comment by alanhartless** [comment]
@npracht Yea, it looks like that's the same issue.
