### ISSUE TITLE
Default custom fields are duplicated on mautic:install:data

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8522]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Running `php bin/console mautic:install:data` is duplicating custom fields.

| Q   | A
| --- | ---
| Mautic version | 3.0 beta
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Backup database if required
2. Run `php bin/console mautic:install:data`
2. Login to Mautic
3. Go to custom fields
4. Notice field are duplicated (search `title`)
 
### Log errors
none

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by lukassykora** [comment]
PR: https://github.com/mautic/mautic/pull/8532
