### ISSUE TITLE
Unable to upload custom contact image

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8529]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When selecting "custom" for the "Preferred profile image" when editing a contact, no upload input is displayed. It looks like the values and labels are reversed for that field because the labels are all lowercase where they are capital in M2. https://github.com/mautic/mautic/issues/8530 may be related or caused by the same issue. 

Also, the preview is too large and cuts off. 

M2 (good):
<img width="668" alt="Screen Shot 2020-03-05 at 17 39 57" src="https://user-images.githubusercontent.com/63312/76035953-69f0fe80-5f08-11ea-968f-056b3f017659.png">

M3 (bad):
<img width="668" alt="Screen Shot 2020-03-05 at 17 40 13" src="https://user-images.githubusercontent.com/63312/76035964-6fe6df80-5f08-11ea-8328-8609ce765e39.png">

| Q   | A
| --- | ---
| Mautic version | 3.0 beta
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Edit/create a new contact
2. On the left, choose "custom" for the preferred profile image
3. The upload input does not show up
 
[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by lukassykora** [comment]
PR: https://github.com/mautic/mautic/pull/8545
