### ISSUE TITLE
Gravatar image does not load

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8530]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The gravatar image is not loading for a contact even though gravatar is selected and the email address is registered. 

This could very well be because of https://github.com/mautic/mautic/issues/8529 if the value/label pairs are flipped and there are checks that `"Gravatar" !== "gravatar"` and thus fixed by the PR that fixes that. 

| Q   | A
| --- | ---
| Mautic version | 3.0.0 beta 
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Edit a contact
2. Add an email for a known gravatar
3. Save
4. Notice that the default avatar image is still displayed
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by lukassykora** [comment]
PR: https://github.com/mautic/mautic/pull/8540
