### ISSUE TITLE
Fields are not shown on the Fields tab on the details page of a form

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8531]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The fields are not displaying on the Fields tab of the form details page. 

![](https://trello-attachments.s3.amazonaws.com/5e5a3dd3cd64384f21a52b5d/5e5c1324cb0a3966a270c75f/1836fbedf6f57c12e9d59908c86144e3/image.png)

| Q   | A
| --- | ---
| Mautic version | 3 beta
| PHP version |7.3
| Browser | chrome

### Steps to reproduce
1. Create a new form
2. View the details page 
3. Notice that the Fields tab is empty
 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Form > fields not displayed](https://trello.com/c/ChoVI3NB/298-form-fields-not-displayed)

**Comment by lukassykora** [comment]
PR: https://github.com/mautic/mautic/pull/8533
