### ISSUE TITLE
The new file manager does not insert selected images into code mode LP or emails

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#8534]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The old file manager would insert the URL to a selected image when used for a LP or email in "code mode" template. The new file manager does nothing when an image is selected. 

| Q   | A
| --- | ---
| Mautic version | 3 beta
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. Create a new landing page
2. Choose Code Mode
3. Click Launch Builder
4. Click the Media Manager button
5. Double click on an image
6. The manager closes without nothing else happening

In M2, the URL would have been inserted. 
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Landing Pages > Create new landing page in code mode](https://trello.com/c/fb5m4MOZ/248-landing-pages-create-new-landing-page-in-code-mode)

**Comment by anton-vlasenko** [comment]
PR: https://github.com/mautic/mautic/pull/8559
