### ISSUE TITLE
SendGrid API Does not send Attachments

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#8543]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When Mautic is configured to send emails via SendGrid API, attachments are not being sent, this issue includes an email with an attachment, including reports 

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 7.1
| Browser | Chrome

### Steps to reproduce
1. Configure Mautic to send Emails via SendGrid API
2. Upload an asset.
3. Create a new template email.
4. Attach the asset to the email.
5. Send test email
6. Received email does not have the asset as an attachment 
 
### Log errors
**No errors in the logs**
**No attachment found in SendGrid logs**

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
@mabumusa1 thanks for reporting this. Can you clarify if you were using a remote asset (e.g. something hosted elsewhere like S3) or a local asset (e.g. a file you've uploaded directly)?

I found an old bug report about S3 files not attaching (https://github.com/mautic/mautic/issues/7620) and a PR that fixed a problem with Sendgrid (https://github.com/mautic/mautic/pull/1033) but it seems strange that no errors are being thrown in your logs.

**Comment by mabumusa1** [comment]
@RCheesley  I found this issue you are referring to when I was looking for others who reported the problem. 

I tested with a local file, it was not sent with SendGrid, to confirm the issue, I tested with Gmail and the attachment was sent

**Comment by RCheesley** [comment]
OK so it seems to be a Sendgrid related issue then if it works OK with Gmail. Thanks for the info!

**Comment by RCheesley** [comment]
Have you tried with other types of emails (e.g. not template emails, sending via/not via campaign, etc?)

**Comment by mabumusa1** [comment]
@RCheesley I know that reports do not have their attachments, test emails as well. I do not think sending via campaign would make any difference.

**Comment by mabumusa1** [comment]
@RCheesley I tested this bug with 2.16.0-beta. attachments were sent normally. I will look more into this issue to verify if it is really a bug or a configuration issue

**Comment by RCheesley** [comment]
@mabumusa1 OK great, thanks for reporting back! So do you mean it works OK with 2.16.0 beta but not with the stable release?

**Comment by mabumusa1** [comment]
Yes, exactly.

**Comment by RCheesley** [comment]
@mabumusa1 did you get anywhere with this issue? Can we close it or is it still a problem in 3.0.2?

**Comment by mabumusa1** [comment]
@RCheesley this issue is solved with 3.0.2. thanks for following up
