### ISSUE TITLE
Pipedrive Client error: `PUT https://....pipedrive.com/v1/persons/123?api_token=...` resulted in a `400 Bad Request` response: {"success":false,"error":"Updating ID with PUT request is not allowed. ...

### ISSUE THREAD

**Issue by janwinkler** [mautic/mautic#8551]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.15.0
| PHP version | 7.1.26
| Browser | -

### Steps to reproduce
1. Connect Mautic to Pipedrive as described here https://www.mautic.org/docs/en/plugins/pipedrive.html
2. Sync your contacts from Pipedrive to Mautic
3. Change the contact in Mautic (e.g. the name)
4. (Issue) Contact will not be changed in Pipedrive
 
### Log errors
[2020-03-11 14:45:06] mautic.ERROR: INTEGRATION ERROR: Pipedrive - Client error: `PUT https://yourpipedrivename.pipedrive.com/v1/persons/123?api_token=....` resulted in a `400 Bad Request` response: {"success":false,"error":"Updating ID with PUT request is not allowed. If you have any questions, please contact Pipedri (truncated...)  [

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
The message seems clear. You try to update your contact ID in pipedrive which is not allowed. Remove it from mapping.

**Comment by janwinkler** [comment]
it appears for all contacts. it seem the issue is not the rights but that mautic tries to PUT and ID instead of updating the rest of the data

**Comment by npracht** [comment]
Again, is the ID in the contact mapping ?

**Comment by janwinkler** [comment]
yes the ID in mautic contact mapping is the correct/same one as the person ID in pipedrive

**Comment by npracht** [comment]
So you should not map this field like that. Because then mautic tries to put mautic contact ID in pipdrive person ID which is not an editable field.
**2 options:**
1. Remove from mapping
2. Map the pipedrive ID to another another text field

**Comment by janwinkler** [comment]
Ok, that solved the problem. Remains the question why the Pipedrive Plugin settings allow to match ID with mautic contact ID ;-)

**Comment by npracht** [comment]
You can also map it with email. The interface let you map whatever you want for all the plugins. A good enhancement would be to only map email type with email type, etc.
