### ISSUE TITLE
Installation error - SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by BenJackGill** [mautic/mautic#8557]
## Bug Description
When trying to do a fresh install of Mautic I am seeing an error message after subitting my database details.

I have found what seems to be a very similar bug, but it was supposedly fixed in 2.15.1 and has sicne been marked as resolved: https://github.com/mautic/mautic/issues/5647. But for me, doing a fresh install on 2.16.0 has brought the bug back.

Mautic Version: 2.16.0
PHP version: 7.2
MySQL Version: 5.6
Browser: Chrome

### Steps to reproduce
1. Upload mautic
2. Visit the installation URL
3. Input the database settings (username, password, etc) and click Next Step
4. The error message is displayed (copied below)
 
### Log errors

`
An error occurred while attempting to install the data: An exception occurred while executing 'CREATE TABLE tweets (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, page_id INT DEFAULT NULL, asset_id INT DEFAULT NULL, is_published TINYINT(1) NOT NULL, date_added DATETIME DEFAULT NULL, created_by INT DEFAULT NULL, created_by_user VARCHAR(255) DEFAULT NULL, date_modified DATETIME DEFAULT NULL, modified_by INT DEFAULT NULL, modified_by_user VARCHAR(255) DEFAULT NULL, checked_out DATETIME DEFAULT NULL, checked_out_by INT DEFAULT NULL, checked_out_by_user VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, media_id VARCHAR(255) DEFAULT NULL, media_path VARCHAR(255) DEFAULT NULL, text VARCHAR(280) NOT NULL, sent_count INT DEFAULT NULL, favorite_count INT DEFAULT NULL, retweet_count INT DEFAULT NULL, lang VARCHAR(255) DEFAULT NULL, INDEX IDX_AA38402512469DE2 (category_id), INDEX IDX_AA384025C4663E4 (page_id), INDEX IDX_AA3840255DA1941 (asset_id), INDEX tweet_text_index (text), INDEX sent_count_index (sent_count), INDEX favorite_count_index (favorite_count), INDEX retweet_count_index (retweet_count), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB ROW_FORMAT = DYNAMIC': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
`

**Comment by RCheesley** [comment]
Thanks for the report. Have you tried addressing it using the info in the earlier reported issue?

It's worth mentioning that you will need to update your MySQL version if you want to use Mautic 3 (see requirements: https://www.mautic.org/download/requirements) - I wouldn't expect this will be addressed between now and then in the 2.x branch given the forthcoming release and MySQL version bump, which will resolve the problem.
