### ISSUE TITLE
Issue when trying to create a new assest while system langauge is set to Hebrew

### ISSUE THREAD

**Issue by OmerGafny** [mautic/mautic#8561]
[//]: # (READ THIS BEFORE PUBLISHING YOUR ISSUE)

[//]: # (Please post questions, support requests and feature requests/ideas at https://forum.mautic.org.)
[//]: # (Strictly follow the instructions hereunder, otherwise your issue will be closed for lack of information.)
[//]: # (DO NOT report security vulnerabilities here. Send them to security@mautic.com.)

Detail your bug report:

| Q  | A
| ---| ---
| Confirm it is a Bug report | Yes
| Mautic version | All Versions
| PHP version | 7.1

[//]: # (Feature request? ---> Go to forum please ---> https://forum.mautic.org/c/ideas)
[//]: # (Enhancement? ---> Go to forum please ---> https://forum.mautic.org/c/ideas)
[//]: # (Need support, have questions? ---> Go to forum please ---> https://forum.mautic.org/c/support)

## Description:
When trying to create a new asset while system or user account language is set to Hebrew, after pressing the "new" button, the page is redirected to the create a new asset page, but the URL path stays on "/s/assets" instaed of "/s/assets/new". Because of that, the page seems to "hang on"
and you cant drop or download files to the file manager box

### Steps to reproduce:
1. Set account or system langauge to Hebrew
2. Navigate to domain/s/assets and try to create a new asset. You will see you get redirected to the create a new asset page but the url is still domain/s/assets. You will also see that the page is stuck and you can drag and drop or upload files
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
Thanks for the bug report @OmerGafny can you share whether there are any errors in your log at all?

You'll find the log in /app/log or via the settings cog > system info >logs

**Comment by RCheesley** [comment]
I just tested this on M3 Mautibox and was able to replicate.

In Hebrew, I see the following when opening the new asset screen in Chrome console:

```
Uncaught SyntaxError: Unexpected identifier
    at DOMEval (2.jquery.js:111)
    at domManip (2.jquery.js:5762)
    at jQuery.fn.init.append (2.jquery.js:5898)
    at jQuery.fn.init.<anonymous> (2.jquery.js:5992)
    at access (2.jquery.js:3939)
    at jQuery.fn.init.html (2.jquery.js:5959)
    at Object.Mautic.processPageContent (1a.content.js:240)
    at Object.success (1a.content.js:54)
    at fire (2.jquery.js:3268)
    at Object.fireWith [as resolveWith] (2.jquery.js:3398)
DOMEval @ 2.jquery.js:111
domManip @ 2.jquery.js:5762
append @ 2.jquery.js:5898
(anonymous) @ 2.jquery.js:5992
access @ 2.jquery.js:3939
html @ 2.jquery.js:5959
Mautic.processPageContent @ 1a.content.js:240
success @ 1a.content.js:54
fire @ 2.jquery.js:3268
fireWith @ 2.jquery.js:3398
done @ 2.jquery.js:9305
(anonymous) @ 2.jquery.js:9548
load (async)
send @ 2.jquery.js:9567
ajax @ 2.jquery.js:9206
Mautic.loadContent @ 1a.content.js:21
Mautic.ajaxifyLink @ 1a.content.js:959
(anonymous) @ 1a.content.js:824
dispatch @ 2.jquery.js:5183
elemData.handle @ 2.jquery.js:4991
```

I was not able to reproduce this when the user language was set to English.

**Comment by morettic2015** [comment]
Same here but PHP version is different: 

### PHP Version 7.2.26-1+ubuntu18.04.1+deb.sury.org+1

`mauticAssetUploadEndpoint = "/s/_uploader/asset/upload";	mauticAssetUploadMaxSize = 2;	mauticAssetUploadMaxSizeError = "ההעלאה נכשלה מאחר וגודל הקובץ הוא  {{filesize}} MB שגדול מהגודל המקסימלי המותר. ניתן לשנות את הגדרות גודל הקובץ ב"הגדרות"";	mauticAssetUploadExtensions = ".csv, .doc, .docx, .epub, .gif, .jpg, .jpeg, .mpg, .mpeg, .mp3, .odt, .odp, .ods, .pdf, .png, .ppt, .pptx, .tif, .tiff, .txt, .xls, .xlsx, .wav";	mauticAssetUploadExtensionError = "ההעלאה נכשלה מאחר וסוג הקובץ אינו ברשימת סוגי הקבצים הנתמכים (.csv, .doc, .docx, .epub, .gif, .jpg, .jpeg, .mpg, .mpeg, .mp3, .odt, .odp, .ods, .pdf, .png, .ppt, .pptx, .tif, .tiff, .txt, .xls, .xlsx, .wav). ניתן לשנות הגדרה זו ב"הגדרות"";`

Javascript ERROR: 

`Uncaught SyntaxError: Unexpected identifier
    at eval (<anonymous>)
    at Function.globalEval (libraries.js?v69e2127b:149)
    at jQuery.fn.init.domManip (libraries.js?v69e2127b:470)
    at jQuery.fn.init.append (libraries.js?v69e2127b:458)
    at jQuery.fn.init.<anonymous> (libraries.js?v69e2127b:465)
    at jQuery.access (libraries.js?v69e2127b:343)
    at jQuery.fn.init.html (libraries.js?v69e2127b:462)
    at Object.Mautic.processPageContent (app.js?v69e2127b:56)
    at Object.success (app.js?v69e2127b:44)
    at fire (libraries.js?v69e2127b:328)`

**Comment by morettic2015** [comment]
Seems like  ב"הגדרות"";  " especial char is not been scaped!

**Comment by RCheesley** [comment]
Ah thanks for snagging that @morettic2015 !  I'll set this as a L1 bug as hopefully it's easy to fix!

**Comment by OmerGafny** [comment]
> Seems like ב"הגדרות""; " especial char is not been scaped!

Hi @morettic2015 nice catch! I removed the quotes signs from the translations file in translations/he_IL/AssetBundle/messages.ini and it fixed the issue. I retranslated the phrase that caused the issue, so it won't have quotes and updated it in Transifax

**Comment by RCheesley** [comment]
@OmerGafny would you make a PR with the changes to translations/he_IL/AssetBundle/messages.ini so we can get that merged?

**Comment by RCheesley** [comment]
Oh wait, maybe we don't need to if you've done the work in Transifex?

**Comment by OmerGafny** [comment]
Hi @RCheesley dont think PR is necessary, if someone encounters the issue he just need to download the transaltion and clear the cache

**Comment by RCheesley** [comment]
OK perfect, thanks for fixing this so quickly - I'll close the issue down in that case! Great work folks :rocket:
