### ISSUE TITLE
mautic hubspot integration date error

### ISSUE THREAD

**Issue by josecastano01** [mautic/mautic#8563]
I have configured the Hubspot extension with Mautic.

Everything syncs properly except for the date. When going from Hubspot to Mautic appears

7473-12-17
8564-05-23
1583-10-07 00:00:00

The year is not displayed correctly

Mautic and the server are configured in UTC-5

I have searched other threads without finding this size.

I appreciate your collaboration.

**Comment by Daxtermania** [comment]
Duplicated
https://github.com/mautic/mautic/issues/8569

**Comment by RCheesley** [comment]
Closing as duplicate.
