### ISSUE TITLE
dates error in mautic hubspot integration

### ISSUE THREAD

**Issue by josecastano01** [mautic/mautic#8569]
I have configured the Hubspot extension with Mautic.

Everything syncs properly except for the date. When going from Hubspot to Mautic appears

7473-12-17
8564-05-23
1583-10-07 00:00:00

The year is not displayed correctly

Mautic and the server are configured in UTC-5

I have searched other threads without finding this size.

I appreciate your collaboration.

**Comment by josecastano01** [comment]
> @josecastano01, side note. I'm curious, how in the hell are you able to even get Hubspot and Mautic syncing? I've tried everything from the built-in plugin to trying to setup Zapier and NONE of them will work.


Hi.

Install the latest version of Mautic and the integration works perfectly.

All contacts are synchronized in Mautic.

Only the contacts found through the form in Mautic go to Hubspot.

**Comment by CarlVanderLaan** [comment]
> > @josecastano01, side note. I'm curious, how in the hell are you able to even get Hubspot and Mautic syncing? I've tried everything from the built-in plugin to trying to setup Zapier and NONE of them will work.
> 
> Hi.
> 
> Install the latest version of Mautic and the integration works perfectly.
> 
> All contacts are synchronized in Mautic.
> 
> Only the contacts found through the form in Mautic go to Hubspot.

I have the latest Mautic installed. Cron jobs setup, just not having any luck. 

Are you getting a two-way sync? Is your data entered into Hubspot pushed to Mautic?

**Comment by josecastano01** [comment]
Can anyone help me with this case?

Thank you.

**Comment by RCheesley** [comment]
Closing as a probable duplicate/related issue to https://github.com/mautic/mautic/issues/8814
