### ISSUE TITLE
BCC field has no effect

### ISSUE THREAD

**Issue by enableit** [mautic/mautic#8574]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar reports among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When someone fills out the form and you have an action to send the results to the client and also yourself via BCC it doesn't send it out to both only to the client

| Q   | A
| --- | ---
| Mautic version | 2.1.6
| PHP version | 7.1
| Browser | Chrome

### Steps to reproduce
1. Create a Form
2. Create a send form results account
3. Add your email to the BCC
4. Fill out the form with another email and submit the form
5. the BCC email gets nothing while the form email does.

Checking mail servers it looks like it completely just ignores the BCC field bit
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by enableit** [comment]
This case 

https://github.com/mautic/mautic/issues/5967

Looks like the same issue too but CC field

**Comment by RCheesley** [comment]
Thanks for reporting @enableit but I believe it is a duplicate given the comment here includes BCC: https://github.com/mautic/mautic/issues/5967#issuecomment-383200196 so will close this issue down in favour of the existing discussions on #5967
