### ISSUE TITLE
"Latest" link is broken, is there a new one?

### ISSUE THREAD

**Issue by ikolubr** [mautic/mautic#8581]
Hi guys,
I have a script to download Mautic automatically, it was using the link: https://www.mautic.org/download/latest until yesterday. I tried to use the script right now and the link is broken. Do you guys have a new link where it always points to the latest version of Mautic, or could you guys fix that one?

Thank you so much,

**Comment by RCheesley** [comment]
Hi there,

Please download at mautic.org/download - this always has the latest version - or via Github - https://github.com/mautic/mautic/releases/latest.

Will look into whether we can resurrect that link, the new site was deployed last Friday so that's why it has changed.
