### ISSUE TITLE
An error while updating the database

### ISSUE THREAD

**Issue by szczepkacpra** [mautic/mautic#8594]
Updating Mautic from 2.16.0 to 2.16.1
PHP 7.3.15

**Step to reproduce**

Update from notification.
 
**Two initial logs**

> [2020-03-26 03:33:20] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `ma_leads` CHANGE `profil` `profil` TEXT':  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'profil' used in key specification without a key length (uncaught exception) at /mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 while running console command `doctrine:migrations:migrate` [] []

> [2020-03-26 03:33:20] mautic.ERROR: [UPGRADE ERROR] Exit code 1; Mautic Migrations \ Migrating up to 20190724110039 from 20160225000000 \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20160615000000 \ -> DROP INDEX ma_email_date_read ON ma_email_stats -> CREATE INDEX ma_email_date_read ON ma_email_stats (date_read) \ ++ migrated (0.28s) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20160712000000 \ -> UPDATE ma_lead_fields SET properties = 'a:2:{s:9:"roundmode";s:1:"4";s:9:"precision";s:1:"2";}' WHERE alias = 'attribution' \ ++ migrated (0.19s) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20160720000000 \ -> DELETE FROM ma_lead_utmtags WHERE utm_campaign is null and utm_content is null and utm_medium is null and utm_source is null and utm_term is null \ ++ migrated (0.16s) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20160726000001 \ -> ALTER TABLE ma_emails DROP FOREIGN KEY FK_7FBA02D79091A2FB -> ALTER TABLE ma_emails ADD CONSTRAINT FK_7FBA02D79091A2FB FOREIGN KEY (translation_parent_id) REFERENCES ma_emails (id) ON DELETE CASCADE -> ALTER TABLE ma_emails DROP FOREIGN KEY FK_7FBA02D791861123 -> ALTER TABLE ma_emails ADD CONSTRAINT FK_7FBA02D791861123 FOREIGN KEY (variant_parent_id) REFERENCES ma_emails (id) ON DELETE CASCADE -> ALTER TABLE ma_pages DROP FOREIGN KEY FK_188385189091A2FB -> ALTER TABLE ma_pages ADD CONSTRAINT FK_188385189091A2FB FOREIGN KEY (translation_parent_id) REFERENCES ma_pages (id) ON DELETE CASCADE -> ALTER TABLE ma_pages DROP FOREIGN KEY FK_1883851891861123 -> ALTER TABLE ma_pages ADD CONSTRAINT FK_1883851891861123 FOREIGN KEY (variant_parent_id) REFERENCES ma_pages (id) ON DELETE CASCADE -> ALTER TABLE ma_dynamic_content DROP FOREIGN KEY FK_36E126B09091A2FB -> ALTER TABLE ma_dynamic_content ADD CONSTRAINT FK_36E126B09091A2FB FOREIGN KEY (translation_parent_id) REFERENCES ma_dynamic_content (id) ON DELETE CASCADE -> ALTER TABLE ma_dynamic_content DROP FOREIGN KEY FK_36E126B091861123 -> ALTER TABLE ma_dynamic_content ADD CONSTRAINT FK_36E126B091861123 FOREIGN KEY (variant_parent_id) REFERENCES ma_dynamic_content (id) ON DELETE CASCADE \ ++ migrated (0.4s) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20160731000000 \ -> update ma_campaign_lead_event_log log inner join ma_campaign_events events on log.event_id = events.id set log.metadata = 'a:0:{}' where events.type = 'email.send' and log.metadata = 'a:2:{s:6:"failed";i:1;s:6:"reason";s:50:"mautic.notification.campaign.failed.not_subscribed";}' \ ++ migrated (0.15s) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20160926182807 \ -> insert into ma_companies (companyname, is_published) (SELECT DISTINCT TRIM(company), 1 from ma_leads l left join ma_companies c ON l.company = c.companyname where company IS NOT NULL and company <> '' and c.companyname is null) -> insert into ma_companies_leads (company_id, lead_id, date_added, manually_added, manually_removed) SELECT c.id, l.id, '2020-03-26 02:33:05', 0, 0 from ma_leads l join ma_companies c on c.companyname = l.company ON DUPLICATE KEY UPDATE company_id = c.id; \ ++ migrated (0.19s) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20161123225456 \ Migration 20161123225456 was executed but did not result in any SQL statements. \ ++ migrated (0.16s) \ ++ migrating 20161124145649 \ -> ALTER TABLE ma_lead_frequencyrules CHANGE `frequency_number` `frequency_number` SMALLINT DEFAULT NULL; -> ALTER TABLE ma_lead_frequencyrules CHANGE `frequency_time` `frequency_time` VARCHAR(25) DEFAULT NULL; \ ++ migrated (0.18s) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20170108012944 \ -> ALTER TABLE ma_push_notifications CHANGE button button LONGTEXT NULL -> ALTER TABLE ma_dynamic_content_lead_data DROP FOREIGN KEY FK_FA4DD22355458D -> ALTER TABLE ma_dynamic_content_lead_data CHANGE lead_id lead_id INT NOT NULL -> ALTER TABLE ma_dynamic_content_lead_data ADD CONSTRAINT FK_FA4DD22355458D FOREIGN KEY (lead_id) REFERENCES ma_leads (id) ON DELETE CASCADE \ ++ migrated (0.18s) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20171024153459 \ -> ALTER TABLE ma_reports ADD is_scheduled TINYINT(1) NOT NULL, ADD schedule_unit VARCHAR(255) DEFAULT NULL, ADD schedule_day VARCHAR(255) DEFAULT NULL, ADD schedule_month_frequency VARCHAR(255) DEFAULT NULL \ ++ migrated (0.19s) \ ++ migrating 20171027134920 \ -> CREATE TABLE IF NOT EXISTS ma_reports_schedulers (id INT AUTO_INCREMENT NOT NULL, report_id INT NOT NULL, schedule_date DATETIME NOT NULL COMMENT '(DC2Type:datetime)', INDEX IDX_9A36497E4BD2A4C0 (report_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB -> ALTER TABLE ma_reports_schedulers ADD CONSTRAINT FK_9A36497E4BD2A4C0 FOREIGN KEY (report_id) REFERENCES ma_reports (id) ON DELETE CASCADE \ ++ migrated (0.23s) \ ++ migrating 20171031164327 \ -> ALTER TABLE ma_reports ADD to_address VARCHAR(255) DEFAULT NULL \ ++ migrated (0.19s) \ ++ migrating 20171208130606 \ -> ALTER TABLE ma_lead_devices ADD tracking_id VARCHAR(255) DEFAULT NULL \ ++ migrated (0.2s) \ ++ migrating 20180105090000 \ -> ALTER TABLE ma_pages CHANGE redirect_url redirect_url VARCHAR(2048) DEFAULT NULL; \ ++ migrated (0.17s) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20180329185634 \ -> ALTER TABLE ma_lead_event_log DROP FOREIGN KEY FK_3364E8F155458D -> ALTER TABLE ma_lead_event_log ADD CONSTRAINT FK_3364E8F155458D FOREIGN KEY (lead_id) REFERENCES ma_leads (id) ON DELETE CASCADE \ ++ migrated (0.19s) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20180410101632 \ -> ALTER TABLE `ma_lead_devices` ADD UNIQUE `ma_tracking_id` (`tracking_id`); \ ++ migrated (0.2s) \ ++ migrating 20180419145934 \ -> UPDATE `ma_lead_fields` SET is_listable = 1 WHERE is_listable = 0; \ ++ migrated (0.16s) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20180830004341 \ Migration 20180830004341 was executed but did not result in any SQL statements. \ ++ migrated (0.18s) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20181011150000 \ -> UPDATE `ma_page_hits` SET url = replace(url, '&', '&') WHERE url LIKE "%&%"; \ ++ migrated (0.18s) \ ++ migrating 20181017154600 \ -> UPDATE `ma_lead_lists` SET filters = REPLACE(filters, 'Cordóba', 'Córdoba') WHERE filters LIKE '%Cordóba%' -> UPDATE `ma_dynamic_content` SET filters = REPLACE(filters, 'Cordóba', 'Córdoba') WHERE filters LIKE '%Cordóba%' -> UPDATE `ma_reports` SET filters = REPLACE(filters, 'Cordóba', 'Córdoba') WHERE filters LIKE '%Cordóba%' \ ++ migrated (0.23s) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20181129105419 \ -> ALTER TABLE ma_lead_utmtags CHANGE url url LONGTEXT DEFAULT NULL \ ++ migrated (0.18s) \ ++ migrating 20181204000000 \ Migration 20181204000000 was executed but did not result in any SQL statements. \ ++ migrated (0.18s) \ ++ migrating 20190704154940 \ Migration 20190704154940 was executed but did not result in any SQL statements. \ ++ migrated (0.16s) \ SS skipped (Reason: Schema includes this migration) \ ++ migrating 20190724110039 \ -> ALTER TABLE `ma_leads` CHANGE `profil` `profil` TEXT Migration 20190724110039 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `ma_leads` CHANGE `profil` `profil` TEXT': \ SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'profil' used in key specification without a key length \ [Doctrine\DBAL\Exception\DriverException] An exception occurred while executing 'ALTER TABLE `ma_leads` CHANGE `profil` `profil` TEXT': \ SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'profil' used in key specification without a key length \ [Doctrine\DBAL\Driver\PDOException] SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'profil' used in key specification without a key length \ [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'profil' used in key specification without a key length \ doctrine:migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--]  [] \ [] []

**Two logs recurring every 20-25 min after the initial error**

> [2020-03-26 03:42:36] mautic.NOTICE: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `ma_leads` CHANGE `profil` `profil` TEXT':  SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'profil' used in key specification without a key length (uncaught exception) at /mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 while running console command `doctrine:migrations:migrate` [] []

> [2020-03-26 03:42:36] mautic.ERROR: [UPGRADE ERROR] Exit code 1; Mautic Migrations \ Migrating up to 20190724110039 from 20190715065013 \ ++ migrating 20190724110039 \ -> ALTER TABLE `ma_leads` CHANGE `profil` `profil` TEXT Migration 20190724110039 failed during Execution. Error An exception occurred while executing 'ALTER TABLE `ma_leads` CHANGE `profil` `profil` TEXT': \ SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'profil' used in key specification without a key length \ [Doctrine\DBAL\Exception\DriverException] An exception occurred while executing 'ALTER TABLE `ma_leads` CHANGE `profil` `profil` TEXT': \ SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'profil' used in key specification without a key length \ [Doctrine\DBAL\Driver\PDOException] SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'profil' used in key specification without a key length \ [PDOException] SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'profil' used in key specification without a key length \ doctrine:migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--]  [] \ [] []

**Comment by RCheesley** [comment]
Did your update succeed? Please follow the steps outlined [here](https://docs.mautic.org/en/troubleshooting/update-failed) as it seems that perhaps it failed. Note we currently recommend [updating via command line](https://docs.mautic.org/en/setup/updating-at-command-line).

**Comment by szczepkacpra** [comment]
Yes, the update to 2.16.1 succeeded, but an error occurred while updating the database.

I got back to 2.16.0 from the backup and updated one again, this time via SSH just like you recommended. Unfortunately with the same result.

Removing Custom Field "profil" fixed the issue.
