### ISSUE TITLE
Space in url not handled well

### ISSUE THREAD

**Issue by vdavid** [mautic/mautic#8597]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If there is a space at the beginning or end of the URL of a link href, Mautic shows a 404 error page when a user clicks on the link in the email.

**Note:** Adding a space to the beginning or end of the URL is a *user error*. But users of the Mautic front end is not only technical people, and simple users tend not to care too much about whitespaces. Mautic could be prepared for this scenario.

Here is an example email: https://www.screencast.com/t/J0QAXqvwjm
Here is the source of the example email: https://www.screencast.com/t/07jeK3kY9
Here is the code in Mautic 2.16.0 that handles this URL: https://www.screencast.com/t/MTyAd2jhBq

This code uses PHP's `filter_var()` function, namely: `filter_var($url, FILTER_VALIDATE_URL)` in `PublicController::redirectAction`. But `filter_var()` will return `false` for any URL that has a space at its end. :(

Suggestion: apply a `trim()` on the `$url` before the `filter_var()` call.

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 7.2.16
| Browser | latest Chrome

### Steps to reproduce
1. Create an email in Mautic which includes a link. In the URL part, add e.g. `http://google.com ` (note the space at the end.)
2. Send the email with the tracking settings on. It will correctly replace the URL and add Mautic's tracking URL, so the mistake will be accepted silently.
3. Receive the email and click on the link in it. You'll see a 404 page.
 
### Log errors
(No errors in the log.)

Thanks a lot for your work btw, we love you guys.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for reporting this @vdavid, would you be up for submitting a PR to implement the suggestions you've made? If so, please ensure you mention that it resolves this issue so that the two get linked up :)

**Comment by vdavid** [comment]
Thanks for your response @RCheesley!
I'd be happy to do that, but I don't have the tools (PHP) at hand to test my changes.
Also, while I was a PHP dev for years, my PHP is rusty. Considering this, would it be fine and helpful to submit an _untested_ PR as well? Because that I'd be happy to do.

**Comment by RCheesley** [comment]
@vdavid any PR requires two community testers before it is merged, so if you can submit something which you believe resolves the issue, we'll handle the testing :)

**Comment by kuzmany** [comment]
This should fixed it https://github.com/mautic/mautic/pull/8345
Can you test it?

**Comment by vdavid** [comment]
Thanks a lot for your PR @kuzmany! I had on my roadmap to respond with a PR, but I kept on pushing it to later. Unfortunately, as ai mentioned before, I don't have a PHP environment now so I can't really test it. I hope someone can review soon and it can be merged.

**Comment by kuzmany** [comment]
@vdavid you can test it by Mautibox 

http://m3.mautibox.com/8345

Emails are fake and you can find it http://m3.mautibox.com/mail after queue command triggering

**Comment by vdavid** [comment]
Oh I see. Thanks. :) Will take a look at it then.

**Comment by dennisameling** [comment]
@vdavid I can't seem to reproduce this issue on Mautic 3.

I added `http://google.com ` (including the space at the end) to an email, enabled tracking, and the URL is replaced by the tracking URL correctly.

![image](https://user-images.githubusercontent.com/17739158/85923920-50950900-b88f-11ea-9db7-723342c6a0c7.png)

I'm getting redirected to Google without problems:

![image](https://user-images.githubusercontent.com/17739158/85923928-5ab70780-b88f-11ea-9a60-d4e28c7f5eb3.png)

Can you please try to reproduce the issue on Mautic 3?

**Comment by kuzmany** [comment]
@dennisameling which PR do you comment? this is issue

**Comment by dennisameling** [comment]
@kuzmany no PR, just trying to reproduce the issue that's described in the issue description :) can't seem to reproduce the issue on M3

**Comment by npracht** [comment]
@kuzmany brought several enhancement on that in 3.x. We can close
