### ISSUE TITLE
[Feature] Set lead source by form

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#86]
If I create a form for a website, I don't always have a field which associates with the lead source (unless I use a hidden field), but I know that all leads coming from that form will be originating from a specific source, generally.

If I want to update a lead to specify the source, it expects this value to come from a form field.

While I appreciate you can use a hidden field, it seems somewhat clunky, it might be better to allow the manual specification of fields to be updated?

**Comment by alanhartless** [comment]
So basically you want a form submit action that will allow you to update a lead's custom field with a specific value defined at the time of building the form?

**Comment by RCheesley** [comment]
Yes I think that's a good explanation - it might be relevant for other fields than source, that was just the one which I came across :)

**Comment by npracht** [comment]
That can also be an action done by submiting the form that modify a data into a custom field ?

**Comment by escopecz** [comment]
I'll close this in favour of https://github.com/mautic/mautic/issues/3906
