### ISSUE TITLE
Citrix plugin not working with stand-alone forms

### ISSUE THREAD

**Issue by miamicityman** [mautic/mautic#8612]
## Bug Description

Steps I have tried to fix the problem:

• Cleared Cached for Mautic
• Removed 3rd party integration via Zapier to GOTOWEBINAR
• Removed integration with MAILCHIMP via Mautic plugin
• Disactivated & reauthorized GOTOWEBINAR plugin for Mautic
• Deleted & Recreated GOTOWEBINAR plugin for Mautic
• Increased Citrix API limits for GOTOWEBINAR plugin for Mautic
• Set cron to run every 17 minutes @ php /app/console mautic:citrix:sync --product=webinar
• Updated database schema successfully.
• Made sure database collation is utf8mb64

**Nothing works**

| Q   | A
| --- | ---
| Mautic version | 2.6.1
| PHP version | 7.2
| Browser | FF & Chrome

### Steps to reproduce

See for yourself:

• https://marketing.latinpressinc.com/form/37
• https://marketing.latinpressinc.com/form/41
 
### Log errors

`[2020-03-31 15:07:34] mautic.ERROR: registerToProduct: Bad request
[2020-03-31 15:07:34] mautic.ERROR: onProductRegistration - webinar: Bad request`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by miamicityman** [comment]
Furthermore with more tests on drop down selection of webinars at form ::

https://marketing.latinpressinc.com/form/36

Erro Log comes back:

`[2020-03-31 19:41:29] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'UPDATE mktng_leads SET date_modified = ?, last_active = ? WHERE id = ?' with params ["2020-03-31 19:41:29", "2020-03-31 19:41:29", 5777]:  SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction" at /home/temp1239/public_html/aaa-sites/marketing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'UPDATE mktng_leads SET date_modified = ?, last_active = ? WHERE id = ?' with params [\"2020-03-31 19:41:29\", \"2020-03-31 19:41:29\", 5777]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /home/temp1239/public_html/aaa-sites/marketing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:115, Doctrine\\DBAL\\Driver\\PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /home/temp1239/public_html/aaa-sites/marketing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /home/temp1239/public_html/aaa-sites/marketing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"}`

**Comment by miamicityman** [comment]
Hello? Anyone care to comment?

**Comment by npracht** [comment]
Hi, yes we do care. I à not able to reproduce your issue, I’m using that everyday and it works properly.

**Comment by npracht** [comment]
Can you contact GTW support to have more information about why the request is bad ?

**Comment by miamicityman** [comment]
Well ... I'm embarrassed that it took me so long. 

The good thing is that I now have a much better idea of how to properly install/operate Mautic.

We have so many past webinars in GTW that there is an error accessing past history via API. I created a new account in GTW and with sample webinar and problem is resolved.

Thanks for responding.
