### ISSUE TITLE
Mautic is predicting the future.... 

### ISSUE THREAD

**Issue by cyanstar** [mautic/mautic#8614]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
So I've just seen a really weird issue. On some of my contacts it's recorded activity as today but in the future. It's currently 11:11 am and it's marked down email read activity for today at 1:34 pm 🤣 

It appears to me that the initial date bit, today/yesterday, is grouped across all records. Once it's been a few days and it changes over to an actual date, fixing the issue.

I did think about the timezones, but I thought Mautic was meant to convert the time over to what the system setting is. Or is it not? IE, if the user opens the email at 11AM in Spain, it would change that activity time to the system set one, so 10AM BST.

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | PHP Version 7.1.30
| Browser | Chrome

### Steps to reproduce
1. Send an email, look at the open activity on a contact.
2. 
 
### Log errors

Time at publishing this ticket it's 11:20 GMT. Yet you can see in the screenshot below it shows activity for today at 12:55PM and 2:22PM. I actually think the first 7 rows are meant to show "yesterday" not today. And then the most recent one at "Today 8:34am" is correct.

![email-time-issue](https://user-images.githubusercontent.com/10960390/78126378-5e5efd80-740a-11ea-8aec-85a862add0d8.PNG)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
I believe this is already an issue that has been flagged in multiple other issues and fixed in https://github.com/mautic/mautic/pull/7752 - see all the issue mentions in that thread.

Perhaps you could test that PR and report back on the PR if it resolves your problem?

Closing this one as a duplication.

**Comment by cyanstar** [comment]
Cheers for the merge @RCheesley I missed that one >_<
