### ISSUE TITLE
Clarify labels and tooltip in form creation for "Render style"

### ISSUE THREAD

**Issue by Aerendir** [mautic/mautic#8615]
| Q   | A
| --- | ---
| Mautic version | 2.16.0 |

## Bug Description
This is not properly a bug but more a labeling issue.

Creating a new form, the option to disable rendering is confusing.

<img width="172" alt="Schermata 2020-04-01 alle 18 32 23" src="https://user-images.githubusercontent.com/1968622/78162491-3a6ddd00-7447-11ea-844c-4b9c354c4812.png">

"Render styles?": No, I don't want them to be rendered, so I select "No"
[Tooltip] "Disable CSS rendering": Mmm, so I have to select "yes" as I want to disable CSS rendering?

I suggest a better labeling like:
Label: Render styles?
Tooltip: Enable CSS rendering

This way the two labels direct the action in the same direction: "Yes" to enable CSS, "No" to disable them.

**Comment by RCheesley** [comment]
That's a great suggestion @Aerendir - are you able to make a PR to implement the changes you suggested?

I found the language strings in the following location - it should be a simple fix I think which could be done via the Github UI if you prefer:

[app/bundles/FormBundle/Translations/en_US/messages.ini
](https://github.com/mautic/mautic/blob/staging/app/bundles/FormBundle/Translations/en_US/messages.ini#L139)

**Comment by RCheesley** [comment]
@Aerendir this should be a fairly easy one to PR - let me know if you need any help! I'd love to get this considered for 3.1 if possible (needs to be done by mid-August and tested by 2 people).

**Comment by Aerendir** [comment]
@RCheesley , I need some time: I just got a new computer and I'm in the process of configuring it and migrating data.

Once finished I will inspect the code to apply the change.

Please, assign this issue to me, so I will see it in my todo list here in GitHub.

**Comment by RCheesley** [comment]
OK perfect, I know the feeling I also have a new laptop!

We need to have it ready and tested no later than 14th August so we have a bit of time yet!

**Comment by Aerendir** [comment]
@RCheesley , a bit late, but finally fixed 😅
