### ISSUE TITLE
Missing translation string in A/B testing on emails

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8616]
###  Bug Description
While doing some documentation writing I came across a string which is missing in the A/B testing parts of the email bundle.

![ab-test-warning](https://user-images.githubusercontent.com/2930593/78178911-457d3900-7458-11ea-8bdb-f5a9ea9dbb21.png)

![make-winner-missing-string](https://user-images.githubusercontent.com/2930593/78179052-7eb5a900-7458-11ea-959c-5be652562d41.png)

Should hopefully be a quick fix!

| Q   | A
| --- | ---
| Mautic version | 2.16.1
| PHP version | 7.3.16
| Browser | Chrome

### Steps to reproduce
1. Create a variant for an email
2. Check out the two items above - one is when assigning a winner (you'll need to send to a segment) and one is just by hovering over the trophy.
 
### Log errors
N/A

**Comment by mohit-rocks** [comment]
PR #8818 fixes the issue.

**Comment by dennisameling** [comment]
Fixed in #8818
