### ISSUE TITLE
Apply button in builder close builder

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#8626]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce

1. Just create or edit email and open builder. 
2. Then try apply from builder
3. Builder is closed (not like in M2) - same for code mode

![captured (4)](https://user-images.githubusercontent.com/462477/78504808-9e5a1380-776f-11ea-9252-5dacb317409d.gif)

**Comment by escopecz** [comment]
PR: https://github.com/mautic/mautic/pull/8689
