### ISSUE TITLE
Froala bug: URL with special char broke HTML

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#8627]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
Create email and paste to editor/or code mode anchor with href with special chars, for example: 

`<a href="https://m3.mautibox.com/3.x/media/images/testá.png">fdsfs</a>`

![image](https://user-images.githubusercontent.com/462477/78504990-a23a6580-7770-11ea-8045-a11424f97003.png)

After apply

![image](https://user-images.githubusercontent.com/462477/78505040-ee85a580-7770-11ea-8039-9e2dbd807f24.png)

![image](https://user-images.githubusercontent.com/462477/78505140-b16de300-7771-11ea-898e-4cee297df267.png)

**Comment by mabumusa1** [comment]
@kuzmany the cause of the error is this [line](https://github.com/mautic/mautic/blob/48640968c068e73ae744a91f9eb779c0284cf2eb/app/bundles/CoreBundle/Helper/InputHelper.php#L440), it cleans any Unicode input
