### ISSUE TITLE
looking to integrate it with amazon ses 

### ISSUE THREAD

**Issue by cadentic** [mautic/mautic#8628]
We've decided to use GitHub issues as a bug tracker only so the bug reports wouldn't be hidden in long list of ideas and support questions. Please go to https://mautic.org to find support and discuss features.

looking to integrate it with amazon ses  . do we need to integrate through send mail ? 

thx
sayantan

**Comment by RCheesley** [comment]
Hi there,

You can use SMTP, and there's full documentation on using SES/SNS for bounce management available in the docs.

Here on Github is not the place for such questions so I'm going to close down this issue. 

In the future, please use https://forum.mautic.org for questions, and head to https://docs.mautic.org for the documentation.
