### ISSUE TITLE
Cloning the landing page with Form and editing with Builder generates artifacts for Forms

### ISSUE THREAD

**Issue by nilyin** [mautic/mautic#8658]
Hi, I use AWS instance with
Mautic 2.16.1 (docker)
PHP Version 7.1.33

I was trying to edit my custom landing page. To save original version and not to destroy it, I first decided to clone it. My Theme has existing Mautic' newsletter subscribe form linked at the LP's header as token in Builder. After cloning and opening form in Editor, then in Builder and saving the page it now shows multiple copies of existing form (actually usually 1-2 extra forms located one in a row)

steps to reproduce:
1. select existing landing page which has a link (insert) to Mautic existing e-mail form. I actually use landing page (LP),which has a translations. Or add new form to your existing Landing page at top section and save the LP.
2) Open list of LPs, select this landing and click "clone" , but better click first "Edit", select needed translation variant and select "clone" for it by using drop-down button at top-right corner of the screen. you will be forwarded at edit details page.
3) select new name for the LP and click "Apply"
4) then select open in Builder and you LP will be opened in Builder
5) make some edits in other parts of the LP. For example create new 1 or 2 column new section at the very bottom of your LP and put some text inside it.
6) Click Apply in Builder
7) Click exit from Builder
8) Click on  Save'n'Exit editor (or may open preview url right now)
9) Open the newly saved (under new name) LP and check your original form view.

I can do a video to illustrate if needed. thank you.

**Comment by RCheesley** [comment]
Hi @nilyin thanks for taking the time to report this! Can you confirm if it exists in Mautic 3.0.1? A short screencast may indeed be helpful!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
