### ISSUE TITLE
CSRF token error generated on mautic site even if there is no ad-blocker

### ISSUE THREAD

**Issue by Sandipan15** [mautic/mautic#8663]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v3.0.0-beta 
| PHP version | 
| Browser | Chrome Version 80.0.3987.163 

### Steps to reproduce
1. Login to the mautic site
2. Let the page load to see the error 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
@Sandipan15 there is insufficient information in this bug report for us to investigate.

Please provide details on your CORS settings, the specific error that you are seeing and what steps you have taken to troubleshoot. It would also be helpful to know if this persists in Mautic 3.0.

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
