### ISSUE TITLE
Clicking into contact owner field results in field jumping

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8674]
## Bug Description
Noticed this when writing some acceptance tests which kept failing despite using the correct selectors.  

When clicking into the Contact Owner field, the options open and immediately close.  This makes it very difficult to select an option - and impossible I should think if you were using a screen reader (or in my case programmatically trying to select the option).

See screen capture:

![New Contact _ Mautic](https://user-images.githubusercontent.com/2930593/79079768-fca36b00-7d08-11ea-9fc9-13f1ae70fa87.gif)

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.2
| Browser | Chrome

### Steps to reproduce
1. Create new contact with more than one user available (e.g. with Mautic sample data
2. Try to choose a contact owner - notice the field jumps up and down without allowing selection.

**Comment by cyanstar** [comment]
Can confirm this. 

I might be mixing it up with a different platform I use, but didn't the dropdown used to open above if the field was in the lower 20% of the screen?

**Comment by RCheesley** [comment]
> Can confirm this.
> 
> I might be mixing it up with a different platform I use, but didn't the dropdown used to open above if the field was in the lower 20% of the screen?

I think it should do this! But it doesn't! Confirm that this persists on Mautic 3.x

**Comment by DevelopMan** [comment]
@RCheesley Didn't reproduce on macOS Catalina 10.15.6 with browsers:
1. Safari 14.0
2. Chrome 85.0.4183.121
3. Firefox 81.0

Mautic version 3.1.0
PHP version 7.2.32-1
But still, it has an issue. It's very hard to user dropdown in such a case
![Safari example](https://user-images.githubusercontent.com/2499467/96257426-9e5a8c00-0fba-11eb-89e9-51192850852b.png)

A can fix it as @cyanstar described. Show this kind of dropdowns from down to up like on this example:
![How it could be, an example](https://user-images.githubusercontent.com/2499467/96258603-8c79e880-0fbc-11eb-9102-ab7daa543e31.png)
