### ISSUE TITLE
Mautic marking queue emails as sent, not able to track actual emails sent.

### ISSUE THREAD

**Issue by mjml1982** [mautic/mautic#8678]
[//]: # (READ THIS BEFORE PUBLISHING YOUR ISSUE)

[//]: # (Please post questions, support requests and feature requests/ideas at https://forum.mautic.org.)
[//]: # (Strictly follow the instructions hereunder, otherwise your issue will be closed for lack of information.)
[//]: # (DO NOT report security vulnerabilities here. Send them to security@mautic.com.)

Detail your bug report:

Hello Everyone, 

I'm using mautic 2.15.3, and I have set it up to send queue emails about 20 emails per hour. When the campaign runs(First hour)Mautic straight away add all subscribers of the segment to campaign and mark the status(100%) that email has been sent to all subscribers while it should say 20 emails have been sent in the first hour, so I can not track how many emails have been sent in each hour and can not compare open rates as well, however, I can confirm that queue emails are working because it shows the right amount of emails per hour in SMTP dashboard, is someone else facing the same issue.

Please see the screenshot, I have added 100 subscribers in this email segment and in the first hour, Mautic set the campaign status 100% and sent the campaign to 100 subscribers while it should send to 20 subscribers as I set the queue status to send 20 emails per hour.

## Screenshoot:

![Firefox_Screenshot_2020-04-07T14-44-21 844Z(2)](https://user-images.githubusercontent.com/38753697/79156212-e8846a00-7deb-11ea-951d-2a4e135fc84a.png)

| Q  | A
| ---| ---
| Confirm it is a Bug report |
| Mautic version | 2.15.3
| PHP version | PHP 7.1

**Comment by colourfulowl** [comment]
That's an interesting use case you have.

On the email itself does the sent number match to the SMTP dash or does it show it as if it's sent all? The email tracking stats are a little inconsistent - it's something that's being worked on last time I checked.

![mautic-email-stats](https://user-images.githubusercontent.com/41902603/79466706-d88ba680-7ff4-11ea-9724-e3ddd6863cb6.PNG)

**Comment by mjml1982** [comment]
@colourfulowl No, on the email itself it does not match with the SMTP dashboard, it is showing as its has been sent to all, in this screenshot the email has been sent to 2 emails and 3rd is in the queue while mautic is showing us it's been sent to all.


![image](https://user-images.githubusercontent.com/38753697/79689717-09c3db00-8270-11ea-9de4-5aa695a36559.png)

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
It may also be helpful to understand how you are limiting the send rate.

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
