### ISSUE TITLE
Amazon S3 bug with browsing remote files on PHP 7.2

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8681]
##  Bug Description
When writing some documentation for the Amazon S3 plugin I encountered a bug.

I have configured a bucket using the region eu-west-2 and uploaded a file which I want to link to in Mautic.

When I create a new asset, click on Remote Files and then browse S3, I see the following error:

Symfony\Component\Debug\Exception\ContextErrorException: PHP Warning - count(): Parameter must be an array or an object that implements Countable
/vendor/knplabs/gaufrette/src/Gaufrette/Adapter/AwsS3.php:221

I did a bit of digging in the vendor's Github issues:

https://github.com/KnpLabs/Gaufrette/issues/539

Seems it was addressed back in Jan 2018 in the [0.5.0 release](https://github.com/KnpLabs/Gaufrette/tree/v0.5.0) with this PR: https://github.com/KnpLabs/Gaufrette/pull/544.

| Q   | A
| --- | ---
| Mautic version | 2.16.0 beta
| PHP version | 7.2.1
| Browser | Chrome

### Steps to reproduce
1. Connect up the S3 plugin
2. Upload a file to S3
3. Browse remote files
 
### Log errors

[2020-04-13 20:58:53] mautic.ERROR: Symfony\Component\Debug\Exception\ContextErrorException: PHP Warning - count(): Parameter must be an array or an object that implements Countable - in file /vendor/knplabs/gaufrette/src/Gaufrette/Adapter/AwsS3.php - at line 221

**Comment by npracht** [comment]
Hi there ! We will not support mautic 2.x anymore except for security matters, in consequence we're working on mautic 2 issues triage.

Can you reproduce your issue on Mautic 3.1.0 which is the latest version ? Thanks for your feedback.

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by favour-chibueze** [comment]
HI @RCheesley has this bug been fixed? Is there any need adding it to the new documentation as a bug for users to take note of?
