### ISSUE TITLE
Get contacts according to one company

### ISSUE THREAD

**Issue by laabidi21** [mautic/mautic#8684]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

| Q   | A
| --- | ---
| Mautic version | v2.16.1
| PHP version | 7.0.33
| Browser | Chrome Version 80

### Steps to reproduce
1. it is possible to search for contacts according to one company. We have the compaies ID, and we are looking for the contact list ?
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by colourfulowl** [comment]
You can search by a contacts primary company using the following search parameter:

company:"Awesome Co"

You can also find all contacts for a company by heading over to the Companies page, finding the company you want, and clicking on the contacts button in the table view.

![mautic-companycontacts](https://user-images.githubusercontent.com/41902603/79465859-c78e6580-7ff3-11ea-91f1-8ec124a02f5e.PNG)

For a list of all the search parameters available, click on the little? next to the search box. These can be chained together, so you can have something like:

company:"awesome co" John Smith

This would find every contact called John Smith who worked at Awesome Co.

![mautic-filters](https://user-images.githubusercontent.com/41902603/79466187-2653df00-7ff4-11ea-821f-d41c24052bf3.PNG)

**Comment by laabidi21** [comment]
@colourfulowl is it possible to find contacts who have no company in relation? (Without company in relationships)

**Comment by colourfulowl** [comment]
@Ziedpad the easiest way to do that would be to create a segment and add a filter for primary company is Blank. 😊

**Comment by laabidi21** [comment]
@colourfulowl it is another problem to create mautic segments. segments do not find instant contacts. and mautic recommended that we use the crons as follows:
0,15,30,45 * * * * www-data php /var/www/html/mautic/app/console mautic:segments:update --batch-limit=500 > /var/log/cron.pipe 2>&1
https://docs.mautic.org/en/setup/cron-jobs
i.e. the segments cannot find contacts at the right time. So to find my contacts without companies, the segments is not a good idea, is it?

**Comment by colourfulowl** [comment]
@Ziedpad I personally run my cronjobs for segments, campaigns and sending every few minutes to make sure when something is automated, it works at the time I need it to. This is how most automation platforms work. Waiting 15 minutes for a segment list to update is just bonkers! But I get why it's recommended that way.

Was on my phone when I last replied. You can use the following to search for just blank companies:

company:!

**Comment by laabidi21** [comment]
@colourfulowl  I have a problem, in the timing of creation of segments and campaigns. maybe you can give me your Mautic crontab? that I can compare with mine

**Comment by colourfulowl** [comment]
@Ziedpad These are how mine are set up:
 
![mautic-crons](https://user-images.githubusercontent.com/41902603/79863468-b8326200-83cf-11ea-99c7-9b6ac8cc485f.PNG)

On the right it says what it's used for :)

**Comment by laabidi21** [comment]
@colourfulowl  you can orient me maybe with Email / campaigns. I have prepared emails and campaigns related to segments, but with:
/ var / www / html / mautic / app / console mautic: email: fetch
-> 0 emails processed for {imap.strato.de:993/imap/ssl{INBOX with a criteria of UNSEEN
I think I should configure Queue-Mode in Mautic.
in Email-Settings I changed the immediate sending to the sending with Queue, but:
  / var / www / html / mautic / app / console mautic: queue: process
You have not configured mautic to use queue mode, nothing will be processed

**Comment by colourfulowl** [comment]
@Ziedpad The queue function is really meant for if you're dealing with a large database and want to cap when and how things operator.

I'm not really sure what you're asking here. But in a nut shell these are what the cronjobs do:

**mautic:segment:update** will update your segments based on the filters applied.

**mautic:campaign:rebuild** is used for when you make adjustments to a campaign and have users who restart it.

**mautic:campaign:trigger** is used to automatically run your campaign actions, decision and conditions. 

**mautic:webhook:process** is for all things webhook related ;)

**mautic: email :fetch** will pull emails from a specific inbox. It's meant for bounce management. 

_For example, I have an email account of bounces@domain.com. I'm using AWS SES to send my emails. AWS SNS sends a bounce notification to bounces@domain.com. Mautic then Fetches those bounces and assigns the bounce tag to the contact._ 

**mautic:message:send** is used to automatically send emails, SMS (texts) and other channel related items at the time specified.

**mautic:social:monitor** is used for updating the twitter hashtag/mention stuff in social monitoring.

**mautic:import** is for when you import contacts. Large lists are automatically queued for import.

For more details on the cronjobs I suggest you check out the Cronjob page on mautic here: https://docs.mautic.org/en/setup/cron-jobs

**Comment by laabidi21** [comment]
@colourfulowl the email is not sent at Mautic, I always have: 0 emails processed for {imap.strato.de:993/imap/ssl{INBOX with a criteria of UNSEEN

**Comment by colourfulowl** [comment]
@Ziedpad I've not personally come across this issue before. But doing a quick search found this issue that might help you to fix it: https://github.com/mautic/mautic/issues/2405

**Comment by npracht** [comment]
Hi there, i let you move your discussion to slack or forums ;)
