### ISSUE TITLE
Max of 100 Lead Notes shown on Calendar, and ordering is confused

### ISSUE THREAD

**Issue by versantus** [mautic/mautic#8685]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
A maximum of 100 lead notes/calendar events are added to the Calendar view, and because they're 
not explicitly ordered (and I'm therefore assuming the DB returns them in ID order), the results are unexpected. 

The ajax request to populate the calendar uses events  generated in app/bundles/LeadBundle/EventListener/CalendarSubscriber.php.  onCalendarGenerate() function has a "setMaxResults(100)".

The events/notes come from the "lead_notes" table

If you have more than 100 events for **tomorrow** with lower lead_note ID, any events for **today** will not show up on the calendar.

Changing maxResults(100) to maxResults (500) brings the missing results back.

Suggested fix: make the maxResults number configurable, or large enough to be less likely (performance impact?), or make it more intelligent - e.g. prioritise results for the next few days.

| Q   | A
| --- | ---
| Mautic version | v2.15.3
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1. Add a lead, and add 100 notes with a date in the future
2. Add another lead, and add one event for today
3. Only the 100 events for the first lead will appear (as it goes beyond 100 max)
4. Delete one of the 100 events, and the second lead's event will appear (as the max number is now 100)
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by versantus** [comment]
Crappy but quick fix for anyone with this problem
```diff --git a/public_html/app/bundles/LeadBundle/EventListener/CalendarSubscriber.php b/public_html/app/bundles/LeadBundle/EventListener/CalendarSubscriber.php
index 90b2f380..9352ea99 100644
--- a/public_html/app/bundles/LeadBundle/EventListener/CalendarSubscriber.php
+++ b/public_html/app/bundles/LeadBundle/EventListener/CalendarSubscriber.php
@@ -52,7 +52,7 @@ class CalendarSubscriber extends CommonSubscriber
             ->setParameter('start', $dates['start_date'])
             ->setParameter('end', $dates['end_date'])
             ->setFirstResult(0)
-            ->setMaxResults(100);
+            ->setMaxResults(500);
 
         $results = $query->execute()->fetchAll();
```

**Comment by colourfulowl** [comment]
@versantus Out of curiosity, what do you use the calendar for? I've been using mautic for a long time now and pretty much ignored that entire feature :rofl:

**Comment by versantus** [comment]
@colourfulowl very little! But one of our customers uses it as a reminder to follow up with people. They're not yet trusting the automation entirely, and so are doing some things manually based on calendar notes.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
