### ISSUE TITLE
User is able to publish email without role permission if edit permission is enabled

### ISSUE THREAD

**Issue by kervin5** [mautic/mautic#8686]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I've been trying to define a role that should allow a user to create emails but not publish them. I created a role that only has email permission to create, edit own, and view own. The role doesn't have permission to publish an email but for some reason the user still has the option to mark the email as "published" or set a publish date.

![image](https://user-images.githubusercontent.com/15281277/79266065-dcc89000-7e4b-11ea-96c7-d981c5d0f373.png)

| Q   | A
| --- | ---
| Mautic version | 2.16.1
| PHP version | 7.0.33
| Browser | Chrome:  80.0.3987.163 (Official Build) (64-bit) Firefox: 71.0 (64-bit)

### Steps to reproduce
1. Create a new role with email permissions to: create, view own, edit own.
2. Create a user and assign it to the role
3. Create a new segment email
4. Set publish to yes or set a publish date.
5. Save the email. The email will be saved marked as publish even without having permission to do so.
 
### Log errors
No error output

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kervin5** [comment]
It seems like this hasn't been implemented on form.html.php but I was able to work around it using the following to hide the controls:

```php
<?php if ($view['security']->isGranted( array('email:emails:publishown','email:emails:publishother',),'MATCH_ONE')): ?>
                     <?php echo $view['form']->row($form['isPublished']); ?>
                    <?php echo $view['form']->row($form['publishUp']); ?>
                    <?php echo $view['form']->row($form['publishDown']); ?>
                <?php endif; ?>
```

The problem is that this only hides the control from the frontend but it like the backend is not taking the permissions into accountability since it would still allow the user to publish the email if the controls were visible and when the user creates a new email, the system will automatically save it as published.

**Comment by colourfulowl** [comment]
Bit of a side issue for anyone who wants to pick this up. 

If a person has any "Edit" permissions for emails, they can hit send even if they don't have "publish" permissions. This means if a segment email is set as "published", they can send it. What I'd like to see here is have additional Permission for Emails and Text messages around "sending".

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Comment by burnoutberni** [comment]
@RCheesley This is still a bug in Mautic 3.3.0 – should open a new ticket or should I add my bug report here?

**Comment by burnoutberni** [comment]
Actually, I'll open a new ticket, since I found more issues with the email permissions.

**Comment by RCheesley** [comment]
@burnoutberni please check in the latest release (ideally 4.0-beta) and raise a new issue
