### ISSUE TITLE
Reports - Panels not 100% width

### ISSUE THREAD

**Issue by cyanstar** [mautic/mautic#8691]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The panels in the report don't 100% width the column. I've tested this in Chrome, Firefox, Edge and IE. It only seems to affect Chrome and Firefox. It's a simple enough fix, I'll submit a PR shortly, but wanted to see if anyone else can confirm the issue.

![mautic-panel-issue](https://user-images.githubusercontent.com/10960390/79339223-75c8db00-7f20-11ea-881d-ad61c17400d0.PNG)

| Q   | A
| --- | ---
| Mautic version | 2.16.1
| Browser | Chrome or Firefox / Nightly - Via Windows 10

### Steps to reproduce
1. Create a report that has panels that are set into different sized columns. 
2. View the report in Chrome or Firefox.

### Fix
Add min-width:100% to .panel in the app.css. Line 326

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
