### ISSUE TITLE
Email Link Tracking - Instant Clicks - Spam filters?

### ISSUE THREAD

**Issue by cyanstar** [mautic/mautic#8692]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I'm having an issue where contacts are instantly clicking every single link inside the email with 10 seconds of them getting it. At first, I put it down to spam scanning systems replacing the links, but it seems to be more common than usual and it's happening sporadically on contacts. Is anyone else seeing something similar? This client is only sending out a small data pool but it's messing up the click tracking and lead scoring massively.

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.1.30
| Browser | Chrome

### Steps to reproduce
1. Send an email campaign. 
2. View a contact who's clicked the campaign, look at their activities.

 
### Log errors
None

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
