### ISSUE TITLE
Email Overview Stats

### ISSUE THREAD

**Issue by cyanstar** [mautic/mautic#8694]
This is one of those little niggling things about mautic that I'd love to see resolved. Can we get the click's add to the email overview? Also, when inside the email details view, can we can some links added for unsubs and reads as well - it could be a case of making the chart clickable.

The clicks link could be something like this:
![mautic-clicks](https://user-images.githubusercontent.com/10960390/79344629-fc34eb00-7f27-11ea-8579-6a8e5f02e657.PNG)
This is just using the info label that's already in the css

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.

**Comment by cyanstar** [comment]
Hey @npracht 

Not more platforms to get used to :rofl: I'm getting far too old for this 😉 

Have the mautic forums been fixed? The last time a checked a few months ago they where getting backlogged with spam.

**Comment by ghost** [comment]
I agree, this would be nice to have

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/ideas as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems or suggesting features - and they have been fixed [almost a year now](https://www.mautic.org/blog/community/mautic-community-forums-re-launched)! :)
