### ISSUE TITLE
MAUTIC-Images are not displaying when sending email

### ISSUE THREAD

**Issue by VMCASIQUE** [mautic/mautic#8696]
Hello,

I configured a new template with html but I configure the images just as I did before but the images are not displaying in Outlook nor Gmail 

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by colourfulowl** [comment]
Hi @VMCASIQUE 
Have you checked your error logs for any errors?

Without any error logs or code to look at, the only thing I can suggest is to check the following setting:

Inside the **Configuration > Emails Settings** you'll find a section called **Message Settings**. Disable "Convert embed images to Base64" if it's enabled. 

![mautic-images](https://user-images.githubusercontent.com/41902603/79464467-00c5d600-7ff2-11ea-949b-f9d892f9bd78.PNG)

If this doesn't work it may be an issue with the template.

Kind regards, 
Owl.

**Comment by VMCASIQUE** [comment]
Hi @colourfulowl it is disable 

Looking the logs this is what appear 

[2020-04-16 13:47:53] mautic.WARNING: PHP Warning - preg_match(): Compilation failed: nothing to repeat at offset 14 - in file /opt/bitnami/apps/mautic/htdocs/app/bundles/CoreBundle/Entity/IpAddress.php - at line 204 {"ip":"66.249.64.***"}

**Comment by colourfulowl** [comment]
Hi @VMCASIQUE That error won't affect your images. That error is common and is actually "fine". It's to do with a google Bot crawling your mautic instance.

Just to clarify, when you say your images don't appear, do you mean they don't display without the person downloading images? This is pretty much standard for emails with images from a sender that hasn't been marked as a safe sender. There are loads of tricks you can try, but they're often a waste of time. This isn't a mautic issue, but an email client issue.

![mautic-images-display](https://user-images.githubusercontent.com/41902603/79547458-d6285b80-808b-11ea-9592-ff5b3d98b509.PNG)

![mautic-images-displayissue](https://user-images.githubusercontent.com/41902603/79547456-d58fc500-808b-11ea-9370-fc27306d9876.PNG)
