### ISSUE TITLE
/s/emails/view/ -> Filter "Unique Clicks" with german backend leads to zero results

### ISSUE THREAD

**Issue by abteilung** [mautic/mautic#8698]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When setting mautic backend to german, filter settings (like Channels -> Emails -> Unique Clicks) return empty results. Apparently, some filter label translations lead to an error.

Default language filter example:
page_source:email page_source_id:8 page_id:12

German language filter example:
page_source:email page_source_id:8 Seiten ID:12

page_id should not be translated to "Seiten ID"

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.2
| Browser | Chrome, Safari

### Steps to reproduce
1. Click on Channels -> Emails -> Email Name -> Click Counts -> Unique Clicks
2. By clicking on the blue label, the results return zero instead of the actual results
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by colourfulowl** [comment]
@abteilung If you change it to seiten_id:12 does it work?

**Comment by abteilung** [comment]
No, it doesn't. Also checked Upper/Lower case variations.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by abteilung** [comment]
Hi RCheesley. It appears to be working with Mautic 3.x, so you don't have to follow it.
