### ISSUE TITLE
[Feature Request] Progressive profiling forms

### ISSUE THREAD

**Issue by troelsfeodor** [mautic/mautic#870]
It would be great to allow embedded forms to present new fields to a known visitor who returns. 
You'd set the order of the fields to be shown and then when a user returns after first submitting his email, he'll be asked for one or more new fields next time.

I used this feature with Marketo, but their implementation is not necessarily great: https://docs.marketo.com/display/public/DOCS/Configure+Form+Progressive+Profiling

**Comment by npracht** [comment]
Hi,

Net Results does the same and it's a very powerfull feature.
https://www.net-results.com/drag-drop-form-builder/

**Comment by alanhartless** [comment]
I think this is a duplicate of #414
