### ISSUE TITLE
error Mautic v2.16.0  does not update the segments

### ISSUE THREAD

**Issue by Dancpa** [mautic/mautic#8700]
Hello to the whole github community, I wanted to comment that I have just installed Mautic v2.16.0 and I have a problem in the segments part, I have created a test tag and when I re-register a contact in a form my contacts are not update in the segment that eleji.

He configured everything and only that problem I present, if someone can help or favor me, thank you very much for your help.

I tried executing the cron job and effectively only this way they are updated.

**Comment by colourfulowl** [comment]
Have you checked the time against your cronjob in your crontab? I think the default update time for segments is every 15 minutes.

**Comment by jlpetracca** [comment]
**Same problem**
v2.16.2

- Contact remain in form's results but never update to segments

**Cronjobs:**
- 0,15,30,45
 /usr/local/bin/php /home/xxx/xxx/app/console mautic:segments:update
- 5,20,35,50
/usr/local/bin/php /home/xxx/xxx/app/console mautic:campaigns:update
- 10,25,40,55
/usr/local/bin/php /home/xx/xxx/app/console mautic:campaigns:trigger
- 2,7,12,17,22,27,32,37,42,47,52,57
/usr/local/bin/php /home/xxx/xxx/app/console mautic:emails:send

**Email from cronjob**
Rebuilding contacts for segment 1
0 total contact(s) to be added in batches of 300
0 total contact(s) to be removed in batches of 300
0 contact(s) affected

Rebuilding contacts for segment 2
0 total contact(s) to be added in batches of 300
0 total contact(s) to be removed in batches of 300
0 contact(s) affected

Thanks!

**Comment by npracht** [comment]
Also can you reproduce your issue on latest version 2.16.2 ?

**Comment by RCheesley** [comment]
Closing due to lack of feedback.
