### ISSUE TITLE
Create category from emails redirect to category instead close modal window

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#8708]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you want create category from any pages (emails...) Save and close or cancel not close modal window and redirect to category.

![image](https://user-images.githubusercontent.com/462477/79645149-c4d77000-81ad-11ea-9011-8c555bdf3c76.png)

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Go to  emails and try create email
2. Try create category inside create/edit email page
3. Try save and close category.
4. You are redirect to category page (expect close windows modal and set selectbox to new created category)
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by alanhartless** [comment]
Closing with #8800
