### ISSUE TITLE
[Patched][Bug] Tokens require scalar values, no filter in place

### ISSUE THREAD

**Issue by oytuntez** [mautic/mautic#8709]
## Bug Description
If you use non-scalar token values in your emails, for instance through a custom flow in your Mautic codebase, Mautic won't be able to use them and will issue a PHP warning. If you send an `Array`, for instance, it will warn for `Array to string conversion`.

| Q   | A
| --- | ---
| Mautic version | 2.16-beta
| PHP version |  7.3
| Browser | -

Opening PRs is quite difficult for us as we maintain our fork in BitBucket, so I am attaching a patch here (with `.log` extension, GitHub doesn't allow `.patch` or `.diff` ... Forgive me for the extra work :( 

Here:
[0001-scalar-value-check-in-token-replacements-core-fix.log](https://github.com/mautic/mautic/files/4497394/0001-scalar-value-check-in-token-replacements-core-fix.log)

Also here:

```diff
Date: Sat, 18 Apr 2020 14:36:55 -0400
Subject: [PATCH] scalar value check in token replacements - core fix

---
 app/bundles/EmailBundle/Event/EmailSendEvent.php | 5 ++++-
 app/bundles/EmailBundle/Helper/MailHelper.php    | 1 +
 2 files changed, 5 insertions(+), 1 deletion(-)

diff --git a/app/bundles/EmailBundle/Event/EmailSendEvent.php b/app/bundles/EmailBundle/Event/EmailSendEvent.php
index 8c51df5db..925f4c700 100755
--- a/app/bundles/EmailBundle/Event/EmailSendEvent.php
+++ b/app/bundles/EmailBundle/Event/EmailSendEvent.php
@@ -186,7 +186,10 @@ class EmailSendEvent extends CommonEvent
             $content = $this->content;
         }
 
-        return ($replaceTokens) ? str_replace(array_keys($this->getTokens()), $this->getTokens(), $content) : $content;
+        $tokens = $this->getTokens();
+        $tokens = array_filter($tokens, "is_scalar");
+
+        return ($replaceTokens) ? str_replace(array_keys($tokens), $tokens, $content) : $content;
     }
 
     /**
diff --git a/app/bundles/EmailBundle/Helper/MailHelper.php b/app/bundles/EmailBundle/Helper/MailHelper.php
index 2cc73594b..04d151656 100755
--- a/app/bundles/EmailBundle/Helper/MailHelper.php
+++ b/app/bundles/EmailBundle/Helper/MailHelper.php
@@ -411,6 +411,7 @@ class MailHelper
                     }
                 } elseif (!empty($tokens)) {
                     // Replace tokens
+                    $tokens = array_filter($tokens, "is_scalar");
                     $search  = array_keys($tokens);
                     $replace = $tokens;
 
-- 
2.23.0


```

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
