### ISSUE TITLE
Pipedrive API deprecations require update to Pipedrive sync plugin

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#8715]
Pipedrive has deprecated a portion of their API which I believe the Pipedrive plugin uses. Our current Pipedrive plugin will stop working on 3/31/2021, which seems far away, but I'm sure will sneak up fast.

Parking this issue here to make sure we don't lose site of it.

https://pipedrive.readme.io/docs/new-search-api-migration-guide

**Comment by RCheesley** [comment]
Thanks for the heads up! I think we should aim for 3.2 given how full the 3.1 milestone is currently!
