### ISSUE TITLE
The date is displayed without regard to the format in the settings

### ISSUE THREAD

**Issue by directpromo** [mautic/mautic#8717]
## Bug Description
In the lead tables, the date is displayed in 12 hour format without taking into account the format in the settings (24 hour format)

I found a bug in the files
/app/bundles/LeadBundle/Views/Lead/list_rows.html.php
/app/bundles/LeadBundle/Views/Timeline/list.html.php

$view['date']->**toTex**t(...) displays the date only in 12 hour format

after changing to $view['date']->**toFull**(...) the date is displayed in the format from the settings 

Not sure. It may be better to modify the  **toText()** function in the file /app/bundles/CoreBundle/Templating/Helper/DateHelper.php
I'm not a programmer, I can't do it :(

| Q   | A
| --- | ---
| Mautic version | 2.16.2 
| PHP version | 7.2

**Comment by RCheesley** [comment]
Pretty sure that this was fixed with #8809/#8848 which were merged in 3.0.1. Can you please confirm?

**Comment by RCheesley** [comment]
Closed as this issue should have been resolved in 3.0.1
