### ISSUE TITLE
count the non-existent open letter

### ISSUE THREAD

**Issue by directpromo** [mautic/mautic#8718]
## Bug Description
Emails are considered read if they are scanned by the mail system bot. The person did not open the email.
For example
![2020-04-23_02-13](https://user-images.githubusercontent.com/42971248/80042573-1b271480-8508-11ea-9364-2eee1f670480.png)

It distorts the real statistics

| Q   | A
| --- | ---
| Mautic version | 2.16.2

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by directpromo** [comment]
@RCheesley As soon as version 3.x is stable I will be able to check. I don't risk updating now
I thought the question through .htaccess adding strings
```
SetEnvIfNoCase User-Agent "(bot|bots)" block_visit
SetEnvIfNoCase User-Agent "YandexImageResizer" block_visit
SetEnvIfNoCase User-Agent "Yahoo" block_visit
```

**Comment by RCheesley** [comment]
See comments re. testing locally or on mautibox.com :)

**Comment by directpromo** [comment]
> See comments re. testing locally or on mautibox.com :)

To check this bug I need the email to arrive at a real email in the domain yandex.ru

**Comment by RCheesley** [comment]
If you set up Mailhog locally you can release mails that you choose by adding SMTP server details: https://github.com/mailhog/MailHog (in case it is helpful to know!)

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
