### ISSUE TITLE
emails are not sent in campaigns if the Mautic settings are in Russian

### ISSUE THREAD

**Issue by directpromo** [mautic/mautic#8719]
## Bug Description
emails are not sent in campaigns if the Mautic settings are in Russian.
This  bug does not appear in English or for messages without specifying the language

Maybe this bug is similar to #8716 

I have moderator rights in https://www.transifex.com/mautic/mautic 
Deleting erroneous translation lines in Russian does not help, because the lines still remain in the translation files. When I delete folders with language files it is downloaded again with lines that cause an error

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.2

### Steps to reproduce
1. In the settings, set the translation to Russian.
2. Clear app/console cachecache:clear
3. app/console translation: update
4. set the language for test emails to Russian 
![2020-04-23_11-13](https://user-images.githubusercontent.com/42971248/80075500-72060b80-8553-11ea-8d93-95cb921abf9f.png)

5. create an action to send this email to a published campaign
4. to launch the campaign
5. see the history of sending the message in channels and inside the contact. Emails will be scheduled, but not sent

 
### Log errors
2020-04-22 22:17:02] mautic.ERROR: CAMPAIGN: Unable to choose a translation for "Всего {0} 0 событий было выполнено|Всего {1} 1 событие было выполнено|[2,Inf] Всего %events% событий было выполнено" with locale "ru" for value "0". Double check that this translation has the correct plural options (e.g. "There is one apple|There are %count% apples").

**Comment by RCheesley** [comment]
Hi there, when I looked at transifex I noticed that we have some warnings on the translations. 

![screenshot-www transifex com-2020 05 16-16_25_49](https://user-images.githubusercontent.com/2930593/82123628-43660400-9792-11ea-9685-7ca30340e4b8.png)

![screenshot-www transifex com-2020 05 16-16_26_40](https://user-images.githubusercontent.com/2930593/82123629-44973100-9792-11ea-82f4-8e078a756005.png)

While I don't speak Russian it looks like these warnings might relate to the errors that you are seeing above. 

Perhaps this is something that the translation team need to address.

**Comment by directpromo** [comment]
Hi @RCheesley 
> Hi there, when I looked at transifex I noticed that we have some warnings on the translations.
> While I don't speak Russian it looks like these warnings might relate to the errors that you are seeing above.
> 
> Perhaps this is something that the translation team need to address.

![2020-05-25_21-35](https://user-images.githubusercontent.com/42971248/82836705-b88eb300-9ecf-11ea-8b79-765cd19dcd31.png)

These warnings are not related to the bug. 

Because transifex checks for open and close brackets. The use of parentheses is a matter of precision in meaning. 

Here (below) is the translation string associated with the error. There are no transifex warnings in it.
![2020-05-25_21-39](https://user-images.githubusercontent.com/42971248/82836968-7023c500-9ed0-11ea-88a0-7eafe848308c.png)

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by directpromo** [comment]
@RCheesley As soon as version 3.x is stable I will be able to check. I don't risk updating now

**Comment by RCheesley** [comment]
3.0.1 was launched on Monday :)

**Comment by RCheesley** [comment]
P.S. you can test in a local environment ... or on the base branch of mautibox.com.

**Comment by directpromo** [comment]
@RCheesley 
> 3.0.1 was launched on Monday :)

released does not mean that it is stable. Wait for the bug reports )

> P.S. you can test in a local environment ... or on the base branch of mautibox.com.

In mautibox.com I don't understand how to check email sending

**Comment by RCheesley** [comment]
Here: https://mautibox.com/mail/ :)

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
