### ISSUE TITLE
Test connection with Sendgrid

### ISSUE THREAD

**Issue by Diegowhitebite** [mautic/mautic#8721]
I have the following error when I perform a connection test with my Sendgrid.

Expected response code 250 but got code "", with message "" Log data: ++ Starting Swift_SmtpTransport << 220 SG ESMTP service ready at ismtpd0001p1lon1.sendgrid.net >> EHLO marketing.isspaces.com << 250-smtp.sendgrid.net 250-8BITMIME 250-PIPELINING 250-SIZE 31457280 250-STARTTLS 250-AUTH PLAIN LOGIN 250 AUTH=PLAIN LOGIN >> STARTTLS << 220 Begin TLS negotiation now >> EHLO marketing.isspaces.com << 250-smtp.sendgrid.net 250-8BITMIME 250-PIPELINING 250-SIZE 31457280 250-STARTTLS 250-AUTH PLAIN LOGIN 250 AUTH=PLAIN LOGIN >> AUTH LOGIN << 334 VXNlcm5hbWU6 >> aW5zdXI= << 334 UGFzc3dvcmQ6 >> aW5zdXIyMDE2 << 451 Authentication failed: Maximum credits exceeded !! Expected response code 235 but got code "451", with message "451 Authentication failed: Maximum credits exceeded " (code: 451) >> RSET << !! Expected response code 250 but got code "", with message "" (code: 0)
++ Starting Swift_SmtpTransport << 220 SG ESMTP service ready at ismtpd0001p1lon1.sendgrid.net >> EHLO marketing.isspaces.com << 250-smtp.sendgrid.net 250-8BITMIME 250-PIPELINING 250-SIZE 31457280 250-STARTTLS 250-AUTH PLAIN LOGIN 250 AUTH=PLAIN LOGIN >> STARTTLS << 220 Begin TLS negotiation now >> EHLO marketing.isspaces.com << 250-smtp.sendgrid.net 250-8BITMIME 250-PIPELINING 250-SIZE 31457280 250-STARTTLS 250-AUTH PLAIN LOGIN 250 AUTH=PLAIN LOGIN >> AUTH LOGIN << 334 VXNlcm5hbWU6 >> aW5zdXI= << 334 UGFzc3dvcmQ6 >> aW5zdXIyMDE2 << 451 Authentication failed: Maximum credits exceeded !! Expected response code 235 but got code "451", with message "451 Authentication failed: Maximum credits exceeded " (code: 451) >> RSET << !! Expected response code 250 but got code "", with message "" (code: 0)

**Comment by RCheesley** [comment]
Hi there this is not a bug with mautic, it looks like you have a problem with your sendgrid account. You can see in the error message that there is a failure relating to having exceeded the maximum credits available.

> Authentication failed: Maximum credits exceeded 

Please take a look at [this resource](https://sendgrid.com/docs/for-developers/sending-email/smtp-errors-and-troubleshooting/) 

> There is a credit limit of emails per day enforced in error. Contact support to remove that limit. 

You will need to contact your customer service advisor at sendgrid.
