### ISSUE TITLE
Import stops and never restart even if "In Progress" is still shown

### ISSUE THREAD

**Issue by ap76** [mautic/mautic#8723]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The contact import is killed and never restart with CRON

I host an instance of Matic on Bluehost. I scheduled the import of contacts (about 30 000), the import is scheduled, then starts and contacts are added.
After a few minutes, no more contacts are added but the import is still "in progress". 
I restart manually the import in the terminal, and it's not starting because it's not queued anymore. So I have to stop it in order to restart it (manually or CRON).
In the terminal, I noticed that the task is killed, but I can't tell what's killing it.
The issue is that once the import task is killed, it's not queued anymore and never restarts if you don't stop and queue it again.

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.0.33
| Browser | Safari

### Steps to reproduce
1. Queue an import
2. Kill the task (it's happening for a reason I couldn't find yet on my side)
3. The import stays in progress but doesn't update anymore
4. Stop the import and queue it again in order to continue the import
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by ap76** [comment]
Just an example to show what's happening in the console.

(...)/mautic/app/console mautic:import
Import 5 with 31638 rows is starting.
 24423/31638 [=====================>------]  77%Killed

(...)/mautic/app/console mautic:import
Import 5 with 31638 rows is starting.
 25838/31638 [======================>-----]  81%Killed

(...)/mautic/app/console mautic:import
Import 5 with 31638 rows is starting.
 27135/31638 [========================>---]  85%Killed

(...)/mautic/app/console mautic:import
Import 5 with 31638 rows is starting.
 28533/31638 [=========================>--]  90%Killed

(...)/mautic/app/console mautic:import
Import 5 with 31638 rows is starting.
 29715/31638 [==========================>-]  93%Killed

**Comment by endri55** [comment]
Hi @ap76 

This is not a bug, you will need to edit your php.ini file and set **memory_limit** to 256M or more to prevent scripts from being killed by running out of memory.

I would also recommend setting **max_execution_time** to 300 or more.

Restart PHP after editing your php.ini file and you should not be having any issues with mautic:import

**Comment by RCheesley** [comment]
As mentioned this is not a bug with Mautic but to do with your hosting setup. Please take a look at [this article](https://docs.mautic.org/en/troubleshooting/working-with-php-ini-resource-limits) on the documentation which will help you with setting the limits.
