### ISSUE TITLE
Checkbox and radio groups output invalid form HTML

### ISSUE THREAD

**Issue by marcaddeo** [mautic/mautic#8724]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When using checkboxes or radios in a Mautic form, they're output using invalid HTML. For some reason they're [output within the label](https://github.com/mautic/mautic/blob/staging/app/bundles/FormBundle/Views/Field/group.html.php#L55-L58) element. Which according to the [label element spec](https://www.w3.org/TR/html4/interact/forms.html#h-17.9.1), is not valid.

Normally the browser doesn't mind this, and will display without issue. However, we're consuming the form via Mautic API and displaying the cached HTML that way. Somewhere along the lines in our CMS (Drupal 8), the invalid HTML gets stripped out. I'm thinking it's Twig, but it's not really something we'd want to disable as a whole.

| Q   | A
| --- | ---
| Mautic version | Hosted on mautic.net
| PHP version | Hosted on mautic.net
| Browser | Any

### Steps to reproduce
1. Create a radio/checkbox group
2. View the HTML that is output when rendering the form
 
### ~Log errors~ Invalid HTML
```html
<div id="mauticform_formtemplate2contactusnond8sales1512_email_opt_in"  class="mauticform-row mauticform-checkboxgrp mauticform-field-23">
  <div class="mauticform-checkboxgrp-row">
      <label id="mauticform_checkboxgrp_label_email_opt_in_10" for="mauticform_checkboxgrp_checkbox_email_opt_in_10"  class="mauticform-checkboxgrp-label">
          <input  class="mauticform-checkboxgrp-checkbox" name="mauticform[email_opt_in][]" id="mauticform_checkboxgrp_checkbox_email_opt_in_10" type="checkbox" value="1" />
          Yes, I would like to receive updates
      </label>
  </div>
  <span class="mauticform-errormsg" style="display: none;"></span>
</div>

```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Please test #8732 !

**Comment by marcaddeo** [comment]
Just learned of MauticBox, and tested it on there: https://mautibox.com/8732/s/forms/view/1

Seems to be working as intended!

**Comment by npracht** [comment]
@marcaddeo can you directly add your review on the PR --> https://github.com/mautic/mautic/issues/8724. You click top right "view files" and then you can add a review (agree or not).

Thanks !

**Comment by marcaddeo** [comment]
Sure thing

**Comment by alanhartless** [comment]
8732 was merged so closing
