### ISSUE TITLE
Cannot authenticate Mautic inside Zapier

### ISSUE THREAD

**Issue by BenJackGill** [mautic/mautic#8725]
## Bug Description
I'm following these docs to setup Zapier integration: https://docs.mautic.org/en/plugins/zapier. But after inputting Mautic credentials (username, password, base url) Zapier says "authentication failed" due to a 404 error. Therefore I cannot setup Mautic with Zapier because it cannot be authenticated.

Mautic version: 2.16
PHP version: 7.3
Browser: Chrome and Firefox (I tried both)

### Steps to reproduce
1. Create a zap in Zapier
2. Connect Mautic by inputting user details (username, password) and base URL
3. Error will appear after you try to submit those login details
 
### Log errors
This is the error message from Zapier: `authentication failed: Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!`
There are no error logs inside Mautic.

**Comment by BenJackGill** [comment]
Seems many others also having this same problem: https://github.com/mautic/mautic-zapier/issues/2

Clearing `app/cache` worked for me (as described on the issue linked) but this really needs to be added into the docs or have the underlying problem fixed because it's been happening since 2017.

**Comment by nickwild-999** [comment]
Hi, Yes I have this problem too across all integrations using the api too. 

I tried deleting the cache, but all this did was cause an endless redirect loop. Does anyone else have any suggestions?

**Comment by RCheesley** [comment]
Hi all, it is super simple to update the documentation, all you need to do is click the Edit on Github button at the bottom of the page. 

I have just made the edit to add the instruction that you should clear your cache if you experience an error as others have mentioned, and therefore will close this issue seeing as this resolved the problem.

**Comment by webma5ter23** [comment]
The same here, I can't get it to work. I cleared cache, I enabled the api and nothing
