### ISSUE TITLE
Mautic LinkedIn Plugin | Missing Parameter "code"

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#8726]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I've just gone to add the LinkedIn config details to one of my instances of Mautic 2.16.1. When I go to Authorise the app it throws up the below error. I didn't even know "code" was a parameter, any ideas?

![mautic-linkedin-auth](https://user-images.githubusercontent.com/41902603/80193799-58c39480-8611-11ea-99d9-93d18b440cd0.PNG)

| Q   | A
| --- | ---
| Mautic version | 2.16.1
| PHP version | 7.1.30
| Browser | Chrome

### Steps to reproduce
1. 
2. 
 
### Log errors
None in the system log, other then what is shown above.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there,

Looking into the integration, it seems we are [using v1 of the LinkedIn API](https://github.com/mautic/mautic/blob/916cb750f2e7896c735b231c98fd9a58c65cf0e5/plugins/MauticSocialBundle/Integration/LinkedInIntegration.php#L115) which has [been deprecated](https://engineering.linkedin.com/blog/2018/12/developer-program-updates).

> Update: As of May 1, 2019, Version 1.0 of our API is no longer supported. Applications requesting Version 1.0 APIs may experience issues as we begin to remove services.

This may not be related to the problem you have, however at a guess I would say we need to update the plug-in.

**Comment by npracht** [comment]
closing in favor of https://github.com/mautic/mautic/issues/8895
