### ISSUE TITLE
Support language specific unsubscribe/re-subscribe confirmation messages

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#873]
If Email has filled the language in settings, this language is not affect on Unsubscribe and Resubscribe page. 
Tested on version 1.2.

**Comment by alanhartless** [comment]
In 1.2.0, the language strings for that page are pretty much now obsolete and are only used to prefill the default for the new configuration settings. Go to Mautic's Configuration -> Email Settings and you'll see where you can customize them. 

![](http://alan.direct/drop/2015-09-07_12-48-14.png)

**Comment by alanhartless** [comment]
Although, I see what you're referring to now.  TBH, I'm not sure that language setting does anything but help categorize emails.  With landing pages, it can be used in conjuncture with the {langbar} token.  But there isn't really a use for emails other than the issue you pointed out.  Supporting that now will take some thought so changing this to a feature request/enhancement for us to look at.

**Comment by kuzmany** [comment]
Thank you Alan for response.
We use Mautic for English, German, Slovak and Czech customers  and this feature will be very useful. It's not right show english message after unsubscribe for german customers. 
Therefore I made dirty hack for myself.

**Comment by marcocevoli** [comment]
+1 for this feature. Working in a translation company, having complete multilanguage content is mandatory.
