### ISSUE TITLE
unable to delete

### ISSUE THREAD

**Issue by humdude** [mautic/mautic#8734]
[//]: # (READ THIS BEFORE PUBLISHING YOUR ISSUE)

[//]: # (Please post questions, support requests and feature requests/ideas at https://forum.mautic.org.)
[//]: # (Strictly follow the instructions hereunder, otherwise your issue will be closed for lack of information.)
[//]: # (DO NOT report security vulnerabilities here. Send them to security@mautic.com.)

Detail your bug report:

| Q  | A
| ---| ---
| Confirm it is a Bug report | No
| Mautic version | v2.15.1
| PHP version | 7.2.30

[//]: # (Feature request? ---> Go to forum please ---> https://forum.mautic.org/c/ideas)
[//]: # (Enhancement? ---> Go to forum please ---> https://forum.mautic.org/c/ideas)
[//]: # (Need support, have questions? ---> Go to forum please ---> https://forum.mautic.org/c/support)

## Description:
I have cloned a form which contains different fields "HTML area" is one of them. However in the cloned form I'm unable to delete this field!!

### Steps to reproduce:
1. 
2. 
 
### Log errors: 
None 
Also in Settings > System Info > Log  > Current Error Log says-
"Today's Mautic error log is empty. Check server error log for error messages Mautic didn't have a chance to catch."

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by npracht** [comment]
Please complete your message.
