### ISSUE TITLE
Auto Update Form Submission email field if contact email is updated...

### ISSUE THREAD

**Issue by BillyHilly** [mautic/mautic#8747]
This is a real-world issue I've faced, and I think this updated would really help everyone.

So, for reasons beyond the scope of this email, I cannot hook up Mautic's bounce management. Even if it was hooked up, I don't think it'd do what I'm about to propose.

# The Problem:
I have to manage bounced emails manually.
9 times out of 10, it's simple user entry error, and I'm able to correctly guess what the email should be. Basic stuff like "gnail.com" or "iclude.com" I've seen.
I could do double opt-in or re-enter your email and validate, but these are for forms where I don't want to trouble the user anymore than necessary — and managing the bounces manually is fine.

The problem is, when I fix an email address on a contact, it doesn't update the bad email the user entered in the form. So then, when a colleague goes and pulls a CSV file of form submissions to upload to another system, the issue starts to propagate. Integration could solve this in the future, but not everyone will have that, and could deal with an issue like this:
* Bounced email found and corrected on contact record
* Bounced email that's bad keeps getting shipped to other systems for use b/c it's coming from the form submission record.

## The Solution:
It'd be great that, if a contact's email is updated, possibly manually/by admin, then also check that contact records form submissions and correct or augment the correct email to the form submission record too — update everywhere.

I can't think of a single reason one would want to keep the bounced bad email anywhere IF the correct email is known.

Not sure how that should all work, but everything to do it already seems to be in place.

Hope to see this become the default!
Thanks for Mautic!

**Comment by akhill10** [comment]
Solution : While importing the contact's we shall verify the email is valid or not by using open source api like trumail. This would decrease the number of bouncing emails.

I would like to work on this, with above solution.

**Comment by colourfulowl** [comment]
Regarding bounces, I'd love to see a plugin for Neverbounce added. They recently released their api documents.

As to exporting, it maybe worth setting up a segment and exporting from there instead of from the form. This way it'll export any updated details.

**Comment by RCheesley** [comment]
Sounds like a couple of possible solutions to this issue - please do submit a PR and link to this issue!
