### ISSUE TITLE
Title field not suggest options

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#8748]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
While I tested https://github.com/mautic/mautic/pull/8740 on Mautibox https://m3.mautibox.com/8741/s/dwc/edit/1 the title field not load values as we expected from Mautic 2 (see image below)

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Try create contat
2. Try type title - Mr
3. No suggestions show unlike in Mautic 2 

![image](https://user-images.githubusercontent.com/462477/80923374-a06dbd00-8d83-11ea-9b0a-bf92590b3882.png)

**Comment by alanhartless** [comment]
Closing as fixed by 8740
