### ISSUE TITLE
Trouble adding note to lead in 1.2.0

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#875]
I can't seem to add a not to a lead. When pressing the "+Add note" button the spinner shows but that's it.

I can't see a JS error being thrown. The apache logs and mautic log are empty as well.

I've tried it in Chrome (regulare and incognito) and firefox.

**Comment by wderuijter** [comment]
Tried on different hosting accounts. Same result.

**Comment by juliopontes** [comment]
I was able to add a note as well.

**Comment by alanhartless** [comment]
Fixed and will be part of 1.2.1.
