### ISSUE TITLE
Add option to bulk-change contacts company

### ISSUE THREAD

**Issue by jensolsson** [mautic/mautic#8750]
## Bug Description
It is not possible to change Company for contacts in the Contacts view even though this is described in documentation?
If I select a couple of contacts and press the green/blue dropdown arrow I can change campaigns, categories, segments etc, but not Company. 

### Steps to reproduce
1. Go to contacts
2. Select a couple of contacts
3. Press the dropdown arrow
4. Assign Company is not displayed

This is on Mautic v2.16.2

Please also see discussion here: https://forum.mautic.org/t/how-to-assign-multiple-contacts-to-a-company/13980

**Comment by colourfulowl** [comment]
If i recall you can do it on individual contacts but not if you have multiple selected.

If theres quite a lot, then what I normally do is set up a system campaign to update the contacts and then delete the campaign.

**Comment by RCheesley** [comment]
Definitely agree this would be a useful feature!
