### ISSUE TITLE
Add support for PHP 7.4

### ISSUE THREAD

**Issue by afonseca08** [mautic/mautic#8752]
PHP 7.4 was released in November, 2019 and is now available from many web hosts. Mautic 3 and later should support this latest PHP release.

**Comment by npracht** [comment]
Hello @afonseca08 ! Thanks for you message. We have introduced PHP 7.3 support in Mautic 3 branch. We’ll see later for a minor version if we can add 7.4. Otherwise it’ll come for the next major version ! We keep an eye on it ;)

**Comment by afonseca08** [comment]
@npracht thank you, is there a separate issue to track this request or should we leave this one open?

**Comment by npracht** [comment]
There is no issue for that, it is not necessary this is part of the core team job to maintain updated dependencies.

**Comment by RCheesley** [comment]
There is already a WIP PR which @escopecz is working on https://github.com/mautic/mautic/pull/8447

**Comment by antonzapevalov** [comment]
What about PHP 7.4?

**Comment by RCheesley** [comment]
See the WIP PR above @ZapevalovAnton !
