### ISSUE TITLE
The Email Sent report not working well

### ISSUE THREAD

**Issue by wesley-if** [mautic/mautic#8753]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.16.1
| PHP version | 7.2.28
| Browser | Chrome

### Steps to reproduce
1. Create report and select Emails Sent as data source
2. Set ID and Clicked as dynamic field under filters
3. Save report
 
### Log errors
On the report view page, it is working fine when nothing is set. 
When clicked filter has set to Yes, no data return. 

Under particular email view page, urls click count are recorded under Click Counts tab.

Based on my findings, $event->getFilterValues('e.id') return empty value on line 380 
in /app/bundles/EmailBundle/EventListener/ReportSubscriber.php

Report is working fine once the comment out line 377 - 381.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @wesley-if ! Thanks for you report ! Can you reproduce it on Mautic 3 ?

@kuzmany what do you think of the suggested workaround ?

**Comment by wesley-if** [comment]
@npracht I just installed Mautic 3 and it seems like the issue still persists by seeing the query.

SELECT DATE(es.date_sent) AS date_sent, DATE(es.date_read) AS date_read, e.subject AS subject1, es.email_address AS email_address, e.id AS e_id, IF(cut.hits is NULL, 0, 1) AS is_hit 
FROM mtc_email_stats es 
LEFT JOIN mtc_emails e ON e.id = es.email_id 
LEFT JOIN mtc_leads l ON l.id = es.lead_id 
LEFT JOIN mtc_ip_addresses i ON i.id = es.ip_id 
LEFT JOIN mtc_emails vp ON vp.id = e.variant_parent_id 
LEFT JOIN mtc_categories c ON c.id = e.category_id 
LEFT JOIN (SELECT COUNT(ph.id) AS hits, COUNT(DISTINCT(ph.redirect_id)) AS unique_hits, cut2.channel_id, ph.lead_id 
	FROM mtc_channel_url_trackables cut2 
	INNER JOIN mtc_page_hits ph ON cut2.redirect_id = ph.redirect_id AND cut2.channel_id = ph.source_id 
	WHERE (cut2.channel = 'email' AND ph.source = 'email') AND (**cut2.channel_id = NULL**) 
	GROUP BY cut2.channel_id, ph.lead_id) cut ON e.id = cut.channel_id AND es.lead_id = cut.lead_id 
WHERE (es.date_sent IS NULL OR (es.date_sent BETWEEN '2020-04-01 00:00:00' AND '2020-05-05 08:06:22')) 
	AND ((**e.id = 123**) AND (IF(cut.hits is NULL, 0, 1) = 1)) 
ORDER BY es.date_sent ASC 
LIMIT 30

In Mautic 2, cut2.channel_id = NULL was cut2.channel_id IN (NULL). Query has slightly changed but outcome still the change. It should be replace the NULL to 123 in my case.

**Comment by escopecz** [comment]
Oops, didn't want to close it. Just wanted to point out that there is currently 182 open PRs containing keyword "report" so there is a great chance this may be already solved.
