### ISSUE TITLE
Google+ plugin

### ISSUE THREAD

**Issue by PierreAmmeloot** [mautic/mautic#8758]
Hello, can you delete Google+ plugin on Mautic ?

Best regards,
Pierre

**Comment by RCheesley** [comment]
Hi Pierre,

I had thought this and dug into it a bit some time ago, however I discovered that there are still some enterprises who use the network.  While it was deprecated for users, I believe it is still available to enterprise. May be useful to see if there are any organisations using Mautic who use that integration before we remove it?

Or, do you mean disable it within your Mautic instance?

**Comment by PierreAmmeloot** [comment]
Hello @RCheesley, I think we need to disable this plugin completely.
Today the Google+ service is stopped.

What do you think about it?
Pierr

**Comment by kuzmany** [comment]
It's removed in Mautic 3
