### ISSUE TITLE
Cant import contact to mautic ( libraries.js error 500 POST)

### ISSUE THREAD

**Issue by budzyn0** [mautic/mautic#8759]
When I try to import contacts by Contacts>Import both using the "Import in Browser" and "Import in Background" options I get the POST Error 500 in my console and no contacts are getting imported.
![2020-05-05_19h32_01](https://user-images.githubusercontent.com/43236231/81096738-28c89b00-8f07-11ea-8341-e1b54333e4ac.png)

My Import can be seen in the "Import History" tab, with 0% Progress
![2020-05-05_19h33_42](https://user-images.githubusercontent.com/43236231/81096901-5b729380-8f07-11ea-8acd-c8ad9fb3c53b.png)

Here is the link to to example file, which cant be imported: https://gofile.io/?c=w5FLKv

Any ideas?

**Comment by RCheesley** [comment]
Hi there, sorry to hear you're having a problem thanks for flagging it up as a potential bug. Unfortunately without the details requested in the issue template is very difficult for us to help you.

Please provide the details requested, at a minimum we require your Mautic version, your PHP version, and the entries from your error log which should give you an indication as to what is causing the error.

You can access the error log by browsing to the app/logs folder or by checking under settings > system information > log.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
