### ISSUE TITLE
Campign emails are not getting sent

### ISSUE THREAD

**Issue by sgkhode** [mautic/mautic#8761]
## Bug Description
I have hosted Mautic on AWS ec2. I created a form and on form submission,

 I want to send email through a campaign.

I can see the campaign is getting assigned to the contacts but email is not getting sent. 
Here is my campaign
![m1](https://user-images.githubusercontent.com/8581889/81146240-83a8d380-8f95-11ea-926e-812194180221.png)

I can see the campaign is getting added
![m2](https://user-images.githubusercontent.com/8581889/81146518-134e8200-8f96-11ea-9556-05bbb9f94245.png)

I cleared cache too. But still it's not working.

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2.

**Comment by npracht** [comment]
Hello,

Can you confirm your mautic version + it must be an email configuration issue.

**Comment by jeancymungedi** [comment]
I'm getting the same issue, the Email segment is working perfect but not the email from campaign with error " Failed to execute campaign event "

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
