### ISSUE TITLE
Use case for Social Monitoring feature

### ISSUE THREAD

**Issue by PierreAmmeloot** [mautic/mautic#8763]
Hello everyone, what is the use case of the Mautic Social Monitoring feature?

I tried to use it and it allows me to create Contacts that use a specific hashtag in their Tweet mentioning a particular account.
But concretely, once I have these new contacts in Mautic, what can I use it for in a marketing campaign?

I have the feeling that this feature is just there to show that technically Mautic can do it but it doesn't make any marketing sense.
I'd be happy if you would prove me wrong by showing me the concrete use case you make with this feature. :-)

See you soon,
Pierre

**Comment by RCheesley** [comment]
Hi Pierre, Github is for issues rather than questions. Please post this on the forums at https://forum.mautic.org. Also please take a look at the documentation here: https://docs.mautic.org/en/channels/social-monitoring

**Comment by PierreAmmeloot** [comment]
Hello @RCheesley, I think this lift belongs here.
Because if this feature has no concrete use then I suggest removing it to simplify the code and its maintenance.

What do you think?
Pierre

**Comment by npracht** [comment]
You can do some stuff with it, get leads, send tweets to them. As mentioned Ruth, if you wanna discuss that it should be on forum and chat, not github.
Thanks.
