### ISSUE TITLE
2.16.2 Cnnot be installed

### ISSUE THREAD

**Issue by Suitntie** [mautic/mautic#8775]
Hello,
I use always : MTC= to install
But the last update crash my mautic and when i want to install it with:
MTC=2.16.2;
URL=https://github.com/mautic/mautic/releases/download/${MTC}/${MTC}.zip;
wget "${URL}";
unzip -o "${MTC}.zip";
rm "${MTC}.zip";
![2020-05-08 19_03_33-DigitalOcean Droplet Console](https://user-images.githubusercontent.com/65035641/81429831-b05c1700-915e-11ea-8830-960cae0ff6ef.png)

Any idea ? I use Runcloud and Digitalocean

Thank you :)

**Comment by tomekjarosik** [comment]
@Suitntie There is a problem with your DNS server - most likely your internet is disconnected. First make sure that "ping github.com" works.

**Comment by Suitntie** [comment]
thank you tomek problem resolve
