### ISSUE TITLE
Won't download or update selected language

### ISSUE THREAD

**Issue by afuggini** [mautic/mautic#8777]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I am using Mautic on Google Cloud through the marketplace solution.

When switching to es_ES the language won't change. I checked the files via SSH and it doesn't seem the translation files are there either.

| Q   | A
| --- | ---
| Mautic version | v2.16.2
| PHP version | 7.2.29
| Browser | Google Chrome

### Steps to reproduce
1. Change language to es_AR
2. Language won't change

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
