### ISSUE TITLE
"Email Sent Date" filter is not working on segments

### ISSUE THREAD

**Issue by aafaq-hassan-confiz** [mautic/mautic#8778]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
"Email Sent Date" filter is not working on segments.

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 5.6.40
| Browser | Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)

### Steps to reproduce
1. Create or edit any segment.
2. Add "Email Sent Date" filter with "less than or equal" option and select a date, for instance, "2020-03-26 23:59".
 
### Log errors
It should filter leads to whom email was sent on or before "2020-03-26 23:59". But it doesn't filter any leads, leads count remains same as before when this filter was not applied. Leads are filtered correctly when 'Date sent' filter with same value ("2020-03-26 23:59") is applied on "Emails Sent" Data Source report in Reports section.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by kolevmm** [comment]
Hello there,
Custom field/Date - 2020-07-10
Segment with filter custom field: equals: Today doesn't work.
Mautic version 3.0.1
Before update to 3.0.1 the segment work perfect.

**Comment by RCheesley** [comment]
@kolevmm thanks for taking the time to check this in Mautic 3 - have added the relevant labels! I know we've had a few people bumping up against this issue!
