### ISSUE TITLE
Adding Trusted hosts causes mautic to go offline

### ISSUE THREAD

**Issue by rdh001** [mautic/mautic#8779]
Ref: https://github.com/mautic/mautic/issues/3323

**Adding Trusted hosts causes mautic to go offline #3323**

This has been closed with no apparent resolution -- is there at least a solution for when the problem occurs"?

 I have the same problem -- I am locked out after adding a value in 'Trusted Hosts'

Error message:

**The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
System administrators, check server logs for errors.'**

**Comment by rdh001** [comment]
Solution that worked for me:

**(1)** Correct the local.php file

Remove the offending line altogether.

In app/config/local.php file

from:

```
'trusted_hosts' => array( 
'0' => 'http://domain-xyz.com'
 ),
```
to:

```
'trusted_hosts' => array(

 ),
```

**(2) Clear the cache**

`sudo rm -fr app/cache/*`

**Comment by RCheesley** [comment]
Great - this has also been updated in Mautic 3.x so will close this issue!
