### ISSUE TITLE
Lead fields in HTML attributes breaks the HTML

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#879]
If I want to create an email with a link to lead's domain, it breaks after save.

### Steps to replicate the issue
1. Create an email with custom HTML.
2. Insert a link with a lead field in the href attribute. For example `<a href="http://{leadfield=domain}">Link</a>`
3. Save and close the email
4. Open the email

In Mautic 1.2.0, the HTML of the link is modified to
```
<a false="" href="http://&lt;strong contenteditable=">**Domain**&quot;&gt;Link</a>
```

**Comment by davkap92** [comment]
Think my issue (#880) may be the same thing

**Comment by rick4470** [comment]
+1 for this feature.

**Comment by dnjusa** [comment]
Getting the same formatting problem then makes the link not trackable.

**Comment by juliopontes** [comment]
Editor still changing the string
from: <a href="http://{leadfield=domain}">Link</a>
to: http://%7Bleadfield=domain%7D
after save a email template.
