### ISSUE TITLE
Can't see 'Priview Tab' in a campaign on view mode 

### ISSUE THREAD

**Issue by alamsarwar** [mautic/mautic#8790]
![Untitled](https://user-images.githubusercontent.com/51904995/81934018-e04a6500-960b-11ea-955f-15d8e0e91ef4.png)
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I recently updated to 2.16.2 from 2.14.x, earlier version was working fine for me but as soon as I updated I found that the 'Preview' tab inside a published campaign always showing error message. I checked nginx log and found nothing, then checked mautic log and found something could related and couldn't understand as I not a developer, attaching the same below. Would be great if anyone can assist.

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.2
| Browser | Mozilla

### Steps to reproduce
1. create a campaign and publish
2. open the campaign at `..../index.php/s/campaigns/view/xx`
 
### Log errors
`[2020-05-14 17:48:52] mautic.ERROR: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT t0.is_published AS is_published_1, t0.date_added AS date_added_2, t0.created_by AS created_by_3, t0.created_by_user AS created_by_user_4, t0.date_modified AS date_modified_5, t0.modified_by AS modified_by_6, t0.modified_by_user AS modified_by_user_7, t0.checked_out AS checked_out_8, t0.checked_out_by AS checked_out_by_9, t0.checked_out_by_user AS checked_out_by_user_10, t0.id AS id_11, t0.name AS name_12, t0.description AS description_13, t0.alias AS alias_14, t0.form_attr AS form_attr_15, t0.cached_html AS cached_html_16, t0.post_action AS post_action_17, t0.post_action_property AS post_action_property_18, t0.publish_up AS publish_up_19, t0.publish_down AS publish_down_20, t0.template AS template_21, t0.in_kiosk_mode AS in_kiosk_mode_22, t0.render_style AS render_style_23, t0.form_type AS form_type_24, t0.no_index AS no_index_25, t0.category_id AS category_id_26 FROM forms t0 INNER JOIN campaign_form_xref ON t0.id = campaign_form_xref.form_id WHERE campaign_form_xref.campaign_id = ?' with params [41]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.form_attr' in 'field list' - in file /path/to/mautic/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php - at line 71 [][]`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.

**Comment by ChetanGoti** [comment]
https://github.com/mautic/mautic/issues/8271#issuecomment-571185122 fixed the issue.
