### ISSUE TITLE
Anchor in url doesn't work after redirect with utm (+patch)

### ISSUE THREAD

**Issue by directpromo** [mautic/mautic#8791]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.16.2 
| Mautic version | 3 

Perhaps in the 3rd version of Mautic this problem is also present

### Steps to reproduce
1. Create an email with an anchor link (for example, #my_anchor). 
2. In the email settings, fill in the Google Analytics UTM tags fields. 
3. Send an email **by segment or through a campaign**. 
4. In this received email, follow the link. 
5. It turns out that the anchor is located inside the url, although it should be at the very end. 
not correct:
`https://domain.com/test_url#my_anchor?utm_source=1&utm_medium=1&utm_campaign=3&utm_content=4`

after the patch correctly:
`https://domain.com/test_url?utm_source=1&utm_medium=1&utm_campaign=3&utm_content=4#my_anchor`
 
Patch for Mautic 2.16.2:  [PublicController.patch.txt](https://github.com/mautic/mautic/files/4629858/PublicController.patch.txt)

**Comment by RCheesley** [comment]
Hi @directpromo thanks for raising this issue, and for providing the fix. 

Could you please make a pull request against the 3.0 branch so that we can consider this for inclusion in a future version of Mautic to fix this problem? 

Happy to help if you need a hand creating the PR, please ensure that you mention in the description that it resolves #8791, that way this issue will automatically be closed when the pull request is merged!

**Comment by directpromo** [comment]
Hi @RCheesley 

> Could you please make a pull request against the 3.0 branch so that we can consider this for inclusion in a future version of Mautic to fix this problem?

Attach patch for Mautic 3 https://github.com/mautic/mautic/blob/3.x/app/bundles/PageBundle/Controller/PublicController.php

[PublicController.patch.txt for 3.x](https://github.com/mautic/mautic/files/4678228/PublicController.patch.txt)

Unfortunately, I can't do pull requests. I'm a marketer, not a programmer. If you tell me how to do it I'll try to learn

**Comment by directpromo** [comment]
> Happy to help if you need a hand creating the PR, please ensure that you mention in the description that it resolves #8791, that way this issue will automatically be closed when the pull request is merged!

@RCheesley  
I tried it https://github.com/mautic/mautic/pull/8829
did I do the right thing?

**Comment by RCheesley** [comment]
Thanks @directpromo PR looks good, it will be reviewed by one of the team and hopefully make its way into one of the upcoming patch releases.  Well done on your first contribution! :tada:
