### ISSUE TITLE
Zoho plugin only works on pre tracked account

### ISSUE THREAD

**Issue by nathanielkam** [mautic/mautic#8792]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Zoho integration only works on accounts that already are being tracked. When submitting from incognito or a NEW device, it fails with the error "invalid query formed" in logs and internal error 500 communicated to browser. 

Turning Push to CRM Option OFF for form does not solve issue. Turning Zoho plugin off DOES solve issue. 

| Q   | A
| --- | ---
| Mautic version | v2.16.2
| PHP version | 7.2.31
| Browser | Version 81.0.4044.138 (Official Build) (64-bit)

### Steps to reproduce
1. Turn on Zoho integration following - https://mautic.com/help/set-zoho-integration/ and https://docs.mautic.org/en/plugins/zoho-crm (you need to use the 2nd one as well since its on V2 with Oauth now) 
2. Setup form with minimal info, example https://nathanielkam.com/test (currently live)
3. Open form in incognito and try to submit
4. You will get a 500 error
5. Print_r on variables being passed to line 39 where it fails: 
$url = https://www.zohoapis.com/crm/v2/Leads/searchArray 
$parameters = ( [criteria] => (Email:equals:) ) 
$method = GETArray 
$settings = ( [headers] => Array ( [Authorization] => Zoho-oauthtoken 1000.5cff34d14c4c78e20e7a33e3d627338f.e92e8180c81958c9da54b5251e931877 ) )
 
### Log errors
[2020-05-14 23:20:56] mautic.CRITICAL: Uncaught PHP Exception Mautic\PluginBundle\Exception\ApiErrorException: "invalid query formed" at /var/www/content.nathanielkam/plugins/MauticCrmBundle/Api/ZohoApi.php line 39 {"exception":"[object] (Mautic\\PluginBundle\\Exception\\ApiErrorException(code: 0): invalid query formed at /var/www/content.nathanielkam/plugins/MauticCrmBundle/Api/ZohoApi.php:39)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by nathanielkam** [comment]
If someone could help me find what is calling ZohoApi->request() that would really help, tried doing a backtrace but it just overran and crashed before I could get anything out of it. Also tried searching "request(" but that was a needle in a hay stack.

**Comment by nathanielkam** [comment]
Have temporarily moved forms back to hubspot for the time being but would prefer for all my marketing to run through Mautic once we resolve this one.

**Comment by RCheesley** [comment]
Hi @nathanielkam thanks for reporting this bug.

I am not sure exactly what is causing the problem, but do you have the printout for the variables when this succeeds? I wonder if that might give any insights.

**Comment by nathanielkam** [comment]
@RCheesley will try to get them tonight, will pull form and request data if that helps. Also if anyone knowns what the backtrace SHOULD look like I can help try to debug from the PHP side as well.

**Comment by nathanielkam** [comment]
Might have to do with this, got a 404 against mautic-form.js (form post did work though) - 

**Contact Created via Form Submission and ZOHO OFF -**
![Capture2](https://user-images.githubusercontent.com/7692778/82244482-2b0efa00-98f6-11ea-8f39-4f77b14eee41.PNG)

**404 against https://content.nathanielkam.com/index.php/media/js/mautic-form.js -** 
![Capture](https://user-images.githubusercontent.com/7692778/82244373-fd29b580-98f5-11ea-9da7-47354a58f824.PNG)

**Request Headers-** 
`GET /index.php/media/js/mautic-form.js HTTP/1.1
Host: content.nathanielkam.com
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Accept: */*
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: script
Referer: https://nathanielkam.com/test/?mauticMessage=test123
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,la;q=0.8
Cookie: _ga=GA###; hubspotutk=###; __hs_opt_out=no; __hs_initial_opt_in=true; _gid=GA###; __hssrc=1; ###=###; __hstc=###5; __hssc=###`

**Comment by nathanielkam** [comment]
Now that i have a tracked mautic user, I can turn Zoho back ON and submit the form cookied and it will work fine and sends contact to zoho as expected. 

**Now that I am a tracked user, turned Zoho ON, and resubmitted form -**
Responses below, 

**Request Headers-**  
`Request URL: https://forms.hubspot.com/collected-forms/submit/form
Request Method: POST
Status Code: 204 

:authority: forms.hubspot.com
:method: POST
:path: /collected-forms/submit/form
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,la;q=0.8
content-length: 478
content-type: application/json
origin: https://nathanielkam.com
referer: https://nathanielkam.com/test/?mauticMessage=test123
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36`

**Response Header -** 
`access-control-allow-credentials: false
access-control-allow-headers: Accept, Accept-Charset, Accept-Encoding, Accept-Language, Content-Type, Host, Origin, Referer, User-Agent
access-control-allow-methods: GET, OPTIONS, PUT, POST, DELETE, PATCH, HEAD
access-control-allow-origin: https://nathanielkam.com
cf-cache-status: DYNAMIC
cf-ray: 59577742b8120517-LAX
cf-request-id: 02ca88ddaf000005177423e200000001
date: Mon, 18 May 2020 17:58:21 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
set-cookie: __cfduid=d6f1c258bd66fa80851643bcd5b503f081589824701; expires=Wed, 17-Jun-20 17:58:21 GMT; path=/; domain=.hubspot.com; HttpOnly; SameSite=Lax
status: 204
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-trace: 2B68D3C8D0707E0DC2672D999FD462F4C812F46F45000000000000000000`

**Payload -**
`{contactFields: {email: "ee@ff.com", lastName: "Zoho"}, formSelectorClasses: "",…}
contactFields: {email: "ee@ff.com", lastName: "Zoho"}
formSelectorClasses: ""
formSelectorId: "#mauticform_pushtozoho"
formValues: {Company: "On"}
labelToNameMap: {Company: "mauticform[company]"}
pageTitle: "Test - Nathaniel Kam"
pageUrl: "https://nathanielkam.com/test/?mauticMessage=test123"
portalId: 7695339
type: "SCRAPED"
utk: "daaddbd7f322373a0d3e00ca19e7432d"
uuid: "e48d360b-7aeb-4afb-ac98-44ceb29bfdc8"
version: "collected-forms-embed-js-static-1.166"`

![Capture3](https://user-images.githubusercontent.com/7692778/82245228-665df880-98f7-11ea-9c8c-b7d32f74eeea.PNG)

**Comment by nathanielkam** [comment]
Leaving cookied browser to incognito BUT still using the identified user ee@ff.com, submit form failed (this suggests it is NOT related to create user)

`Request URL: https://content.nathanielkam.com/index.php/form/submit?formId=3
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: 54.153.121.199:443
Referrer Policy: no-referrer-when-downgrade`

**Request Header -** 
`Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,la;q=0.8
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 843
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryVdYA7wvAiTSB6LXF
Cookie: ###=###; _ga=GA1.2.###; _gid=GA1.2###; _gat=1; __hstc=###; hubspotutk=###; __hssrc=1; __hssc=###; __hs_opt_out=no; __hs_initial_opt_in=true; _gali=mauticform_input_pushtozoho_submit
Host: content.nathanielkam.com
Origin: https://nathanielkam.com
Referer: https://nathanielkam.com/test/
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-site
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36`

**Form Data -** 
`mauticform[email]: ee@ff.com
mauticform[last_name]: Incognito Test on Existing User
mauticform[company]: test2222
mauticform[submit]: 
mauticform[formId]: 3
mauticform[return]: 
mauticform[formName]: pushtozoho`

![Capture4](https://user-images.githubusercontent.com/7692778/82245597-15023900-98f8-11ea-8a39-011de3665571.PNG)

**Comment by nathanielkam** [comment]
@RCheesley requests and response data uploaded as comments, let me know if you need any other info. I will look into the processing workflow for /form/submit?formId= later tonight to see if I can get any more debug info on why it is failing.

**Comment by nathanielkam** [comment]
checking in on this to see if anyone has any more ideas, I am working on some more debug this weekend, hoping to get this resolved soon.

**Comment by nathanielkam** [comment]
Got this figured out kinda, at some point I upgraded to PHP7.4.6 which isn't supported. There were also potentially some issues with Mcrypt extension not being valid API version. There may also be an issue with my logs where all logs are created as root but need web server ownership to write to. 

Effectively after doing a stack rebuild in 7.3 I did get this working.

**Comment by RCheesley** [comment]
Mautic does not yet support PHP 7.4 (There is a [WIP PR](https://github.com/mautic/mautic/pull/8447)) so will close this issue down as that seems to be the cause!
