### ISSUE TITLE
URL not decoding &amp back to & - Google Analytics Tracking Campaign

### ISSUE THREAD

**Issue by davkap92** [mautic/mautic#880]
Hi,
Really enjoying this project,
just one thing I'm having trouble with, i add a url in ckeditor hyperlink form -  www.example.com/index.php?utm_campaign=test&utm_medium=email  etc,
but i can see in mandrill that after the click is handled by mautic it goes into the browser url with "& amp;" , not sure if there's a step I'm missing? 

Many thanks

**Comment by davkap92** [comment]
anyone, help pls?, I'd try fix it myself but don't know the project too well or even which bundle to look in, thanks!

**Comment by alanhartless** [comment]
Just to confirm; is this with 1.1.3 or 1.2.0?

**Comment by davkap92** [comment]
HI Alan,
1.2.0

Thanks

**Comment by alanhartless** [comment]
See if #917 solves your issue. -Thanks

**Comment by davkap92** [comment]
Great seems to be working fine
Url parameters now intact after going to url

Thanks!
