### ISSUE TITLE
"Open email" condition does not work for emails created in code mode

### ISSUE THREAD

**Issue by joel-zutobi** [mautic/mautic#8803]
## Bug Description
I have a "Open email" condition set up in a campaign and then a "Send email" action. The second email gets sent, no matter if the first email is opened or not. Both emails are created in code mode. If I actually open the email, the "email read" event registers correctly, but I don't think it's ever regarded by the system. 

Screenshot of the campaign actions:
![Screenshot from 2020-05-18 10-42-41](https://user-images.githubusercontent.com/39857933/82192829-c99a5b80-98f4-11ea-8319-e3162bb2f879.png)

This is the event log in Mautic for a user that has entered the campaign. As you can see, the user is sent the second email without having opened the first.
![Screenshot from 2020-05-18 10-47-54](https://user-images.githubusercontent.com/39857933/82193745-1e8aa180-98f6-11ea-82cc-52071e2a5eaf.png)

For reference, this is how the event when a user has opened an email looks:
![Screenshot from 2020-05-18 10-56-38](https://user-images.githubusercontent.com/39857933/82193868-4843c880-98f6-11ea-8ec1-231ef432c65b.png)

| Q   | A
| --- | ---
| Mautic version | v2.16.2
| PHP version | 7.1.33-14+ubuntu16.04.1+deb.sury.org+1

### Steps to reproduce
1. Create two emails via code view. 
2. Create a campaign. Send email1 when user enters segment. Create "open email" condition for the email that was sent. If email1 is opened, send email2.
3. Email2 will be sent even if the user haven't opened email1.

### Log errors
No log errors.

**Comment by RCheesley** [comment]
Hi, based on the screenshot above, the logic you have used is that if they **do not open** the email within one minute, then send the second email. 

The red decision path means this did not happen, whereas the green decision path means this did happen.

If you are intending for the second email to be sent when they **do** open the email, that should be set on the green decision pathway.  This might explain the behaviour you are seeing.

**Comment by joel-zutobi** [comment]
@RCheesley Thank you! It works great when using the correct decision path!

As a side note. The purpose for the two paths should be clearer, having a green and red path isn't intuitive enough and easily overlooked. If people are color blind they'll have no idea the paths even differ.

**Comment by RCheesley** [comment]
Glad this helped to solve the problem. You might find this documentation page helpful:
https://docs.mautic.org/en/campaigns/using-campaign-builder#decisions
