### ISSUE TITLE
Links In the sent Email doesn't work sometimes

### ISSUE THREAD

**Issue by Shivanshu-Gour** [mautic/mautic#8808]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.

**Comment by RCheesley** [comment]
Hi there, does this persist in Mautic 3.0.1?

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
