### ISSUE TITLE
Pipedrive Plugin won't open

### ISSUE THREAD

**Issue by lrqnet** [mautic/mautic#8810]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hello community! I tested the Pipedrive plugin but it won't open, it's on an infinite loading screen. All the other plugins open, only the Pipedrive doesn't.

| Q   | A
| --- | ---
| Mautic version | v2.15.3
| PHP version | 7.1.33
| Browser | Chrome

### Steps to reproduce
1. When entering the Plugins page.
2. Every plugin on the page loads, except Pipedrive, is in a "loading" loop.
 
![image](https://user-images.githubusercontent.com/15186323/82384176-aca17d80-9a05-11ea-99f1-cef54506d11f.png)

### Log errors
The log does not report any errors.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
