### ISSUE TITLE
Wrong contact identification while it is identified via API.

### ISSUE THREAD

**Issue by jurczykpawel** [mautic/mautic#8811]
## Bug Description
| Q   | A
| --- | ---
| Mautic version | v2.16.2
| PHP version | 7.1.33
| Browser | Chrome

### Steps to reproduce
The problem appears when anonymous contact is identified via API using the backend of the website.

Let me describe the scenario.
I have Mautic installed on a different domain than my website. I have CORS configured properly, so cookies are stored for both, Mautic and website, domains. I have mtc.js embedded on my website. My website is integrated with Mautic - when someone purchases something a contact is being created via API.
Assume I have one contact identified in Mautic (johndoe@domain.com with ID=1).

1) Someone opens my website for the first time.
2) mtc.js sends the request to Mautic and it generates new ID=2 for anonymous contact.
3) All cookies (mtc_id, mautic_device_id, mtc_sid) which identify anonymous contact are stored for both, Mautic and website, domains.
4) Someone makes a purchase using email johndoe@domain.com.
5) All information about the customer (together with all cookies) is sent to Mautic via API.
6) Mautic merges contact ID=2 with contact ID=1 and returns new values of cookies via API. Cookies are stored but only on the local domain. Mautic cookies cannot be updated because are stored for a different domain.
7) Anonymous contact with ID=2 does not exist and therefore session for this contact is no longer valid.
8) When customer refreshes the page or goes to another page within the website, mtc.js sends another request but still using old cookies from Mautic domain.
9) Mautic cannot find contact with ID=2 and generates and returns next anonymous contact with ID=3.
10) mtc.js overwrites local cookies using new anonymous contact ID. Identified contact is again anonymous contact.

According to docs local cookies are stored when CORS is configured properly.
https://docs.mautic.org/en/contacts/manage-contacts/contact-monitoring#local-contact-cookie
Why not use local cookies by mtc.js? 
It would be easier to manage contacts while using both API and mtc.js events.

I also tried to use PHP library https://github.com/escopecz/mautic-form-submit provided by @escopecz and it is working in exact same way.

**Comment by RCheesley** [comment]
I think that this is a duplicate of #7559 and was fixed in https://github.com/mautic/mautic/pull/8836 - can you confirm if this persists in Mautic 3.0.1?

**Comment by jurczykpawel** [comment]
Thank you for update. It looks it is working properly in Mautic 3.0.1.
