### ISSUE TITLE
In case of multiple domains use - batch email sending doesnt use default domain set in config but the current user domain

### ISSUE THREAD

**Issue by enguerr** [mautic/mautic#8813]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
In case of multiple domains set up in the mautic box. 
For example, one for internet (company.net) and one for internal lan access (company.local).
In configuration, set up the default domain to company.net.
SendExampleAction =>work as expected with company.net links. unsubscribe link work.
SendBathAction => doesnt work well, it uses the current domain of the user who launch the batch. company.local. unsubscribe links doesnt work. 

| Q   | A
| --- | ---
| Mautic version | 2.6.2
| PHP version | 7.2
| Browser | Chrome

### Steps to reproduce
1. Configure default domain company.net
2. Access mautic with company.local
3.Send batch email
4.Unsubscribe links use company.local and doesnt work. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by enguerr** [comment]
Hi, i confirm this bug is also present in 3.x branche.
Here is a screenshot of my pull request (deleted) 25 days ago.
![image](https://user-images.githubusercontent.com/9450193/86262716-881df100-bbc0-11ea-82c7-359621973228.png)

My precedent pull-request doesnt seems to gain interests to mautic team members ... so i deleted it .
Do i need to re-pullrequest it ?

**Comment by RCheesley** [comment]
Please open a PR if you can address the issue!
