### ISSUE TITLE
Write upgrade script for M2 to M3

### ISSUE THREAD

**Issue by dennisameling** [mautic/mautic#8819]
The latest Mautic 3 beta (https://github.com/mautic/mautic/releases/tag/3.0.0-beta2) doesn't support upgrades from Mautic 2 yet, as there's no migration script in place yet to M3.

This issue is to track work on an upgrade script for M2 to M3.

**Pre-upgrade checks**
- [x] PHP version >= 7.2.21 and <= 7.3999
- [x] Current database driver = `pdo_mysql` or `mysqli` (get from existing Mautic config file)
- [x] MySQL version > 5.7.14 or MariaDB version > 10.1
- [x] Mautic version >= 2.16.3. Mautic 2.16 has PHP 7.3 support, so e.g. if the user is currently using PHP 7.1, they can choose between 7.2 and 7.3 prior to upgrading. Next to that, we are then sure that the user has all database migrations prior to upgrading to 3.0. We'll introduce a 2.16.3 version that adds support for upgrading to M3.
- [x] Check if there is a custom configuration for api_rate_limiter_cache in the local.php file (see [here](https://github.com/mautic/mautic/blob/3.x/UPGRADE-3.0.md#configuration) for details)
- [x] Check if Mautic's root folder is writable by creating + deleting a dummy folder
- [x] Ensure PHP's max_execution_time is at least 240 (4 mins). Try to set it to 240 if it's lower than that, if not raise an error.
- [x] Check if `mysqldump` is available on the system, otherwise trigger a warning that the user should take care of the backup
- [x] Inform user to update cron jobs after upgrade (`app/console` to `bin/console`)
- [x] Check if enough free disk space is available for the upgrade [with PHP's](https://www.php.net/manual/en/function.disk-free-space.php) `disk_free_space()` function. NOTE (tested on server with Plesk): This is not reliable on shared hosting, as it will give the total amount of disk space available, not the disk space that's available just to the user's subscription. Best we can do is to raise a warning, not a hard error
- [x] Check if configured spool folder is empty
- [x] Check if there are custom plugins installed (they need to be disabled/upgraded prior to upgrade). Just to be sure I moved the part where we move back plugins/themes/etc. to the very end of the process
- [x] Check if PHP's `memory_limit` is at least 256M

**Upgrade process**
- [x] Send upgrade telemetry to stats server, upgrade status = `started` (https://github.com/mautic/statsapp/pull/1)
- [x] Do a database backup if `mysqldump` is available
- [x] Run database migrations from 2.x branch, just to make sure we're up to date prior to the 3.x upgrade
- [x] Download Mautic 3 files, unzip to a temporary folder called `mautic-3-temp-files`
- [x] Move all current Mautic 2 files to a temporary folder called `mautic-2-backup-files`
- [x] Update all configuration parameters (e.g. `api_rate_limiter_cache`) based on all parameters mentioned in https://github.com/mautic/mautic/issues/8831
- [x] Move files from `mautic-3-temp-files` to Mautic's root folder
- [x] Move config/themes/images/user dashboards/etc. from `mautic-2-backup-files` back into the "empty" 3.0 folder
- [x] Create cache for 3.x
- [x] Run database migrations
- [x] Generate random hashes for the mautic 2 backup folder and database backup file, so we can leave it there just in case something goes wrong.
- [x] Move .htaccess.m3 to .htaccess after we're done
- [x] Add a note about deleting the backup files (button in UI + CLI switch) to give the user the opportunity to delete backup files easily (after confirming everything works as expected)
- [x] Send upgrade telemetry to stats server, upgrade status = `succeeded` | `failed` (https://github.com/mautic/statsapp/pull/1)

**Misc tasks**
- [x] Add error codes with links to the documentation to allow for better troubleshooting
- [x] Build integration with Mautic's "find updates" command to show the upgrade to M3 available if Mautic version > 2.16.3 and kill switch for upgrades = off (on our server)
- [x] Fix steps for CLI upgrade
- [ ] Enable `mysqldump` DB backup only if user has <10000 contacts in their instance and/or recommend user to perform upgrade via CLI instead
- [x] Double-check other configuration changes in `local.php` between M2 and M3 (it also looks like things like mail driver names have changed, as I'm getting SwiftMailer warnings)
- [x] Write testing steps in this PR (including steps to test custom plugins/themes/etc. migrations)
- [x] Database migrations not working
- [x] Add extensive logging to upgrade process and write it into a log file, so that users can send in their log files
- [x] Pass Symfony console errors to the logfile to help us troubleshoot with the users (currently being written to `NullOutput`, should be `BufferedOutput`)
- [x] Build JSON updates in UI so that users see the progress per step and aren't looking at a blank screen for multiple minutes
- [x] Run database migrations 1 by 1 to prevent PHP timeouts (clean 2.16.2 installation has 136 (!) migrations it has to go through)
- [x] Send upgrade error codes to stats server if applicable, so we can see where users are stuck
- [x] Use mau.tc URL shortener for redirecting to the docs
 
I'll create a new `upgrade_v3.php` which will just be included in M2 installations 2.16.3+, to prevent any potential clashes with the existing `upgrade.php`

**Comment by RCheesley** [comment]
Would we want to back up/copy the DB first in case of failure, or do we assume it is already done?

**Comment by dennisameling** [comment]
@RCheesley I've been researching that a bit. Ideally, we'd trigger a script called `mysqldump` (bundled with MySQL installations), but not all hosting environments (like shared hosting) allow that. The alternative is to build a 100% PHP script that walks through all database tables 1 by 1 to create a backup, but this would be a lot of work to build & test, plus I'm not sure if it will be safe/stable enough.

What I could do that's feasible, is to check if `mysqldump` is accessible on the user's system and if not, show a warning:

> We can't make a database backup for you due to restrictions on your system. **Only continue if you have your own database backup available!** Do you have a backup? Yes/No

Just updated the opening post to include `mysqldump` 👍

**Comment by dennisameling** [comment]
I'd be very interested in collecting (anonymous) data about the M2 > M3 upgrade success rates, so we can monitor closely whether upgrades succeed or not, and maybe even have a "kill switch" if there's too many failed upgrades (e.g. >25%). [We are already collecting data](https://github.com/mautic/mautic/blob/staging/upgrade.php#L354-L367) during updates and send it to https://updates.mautic.org/stats.

For proper monitoring, I'd need to know:
- Source Mautic version (e.g. 2.16.1)
- PHP version
- Server OS & version
- Upgrade succeeded Yes/No? (If no, allow the user to easily create a bug ticket in GitHub or a GForm?)

@RCheesley @alanhartless thoughts on this?

**Comment by alanhartless** [comment]
Doing an automatic backup will be tricky. I’d suggest just warning the user to do this before they attempt to run the script. 

As for the stats, I think we can get those through the existing stat collection. As soon as the upgrade happens, mautic will send the stats for the M3 version. It’s Actually the last thing we need to update to remove the dependency on updates.mautic.org.

**Comment by alanhartless** [comment]
What is the typical max execution time on most shared hosts? If less than 240, that could prevent them from upgrading.

**Comment by alanhartless** [comment]
Just a note that there are parts of the current script that the in app upgrade process needs.

**Comment by dennisameling** [comment]
**Stats**: the existing stat collection won't show us the amount of failed upgrades, as we'll only have numbers of instances per version AFAIK. Is there some other database/stats server that we're planning to migrate to?

**Max execution time**: depends per host, but I believe most limit it to 120 seconds. However, users often have ways to increase it, e.g. by adding .ini config files etc. - could add instructions like "contact your host to increase your max_execution_time, otherwise the upgrade will most likely fail". 

Think it's a good thing to slowly start enforcing `max_execution_time` everywhere, as many support-related questions have to do with this, but that's a discussion for later :)

**Comment by RCheesley** [comment]
Here's the (old and broken UI) stats package @dennisameling in case it's useful https://github.com/mautic/statsapp

**Comment by dennisameling** [comment]
Update: the migration script is pretty much done (on the filesystem level, everything is working as expected).

Database migrations not working: after the upgrade, we only have the following DB migrations left:

![image](https://user-images.githubusercontent.com/17739158/82765365-84a38700-9e16-11ea-94c9-ad6984f1be52.png)

When running `php bin/console doctrine:migrations:migrate --no-interaction --env=prod --no-debug`, the following errors show up:

```
[2020-05-24 21:21:38] Migration 20181111095447 failed during Pre-Checks. Error Class 'Zend\Code\Generator\ClassGenerator' not found

In ClassGenerator.php line 15:
                                                                                  
  Attempted to load class "ClassGenerator" from namespace "Zend\Code\Generator".  
  Did you forget a "use" statement for "Laminas\Code\Generator\ClassGenerator"?   
                                                                                  

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]
```

I remember @escopecz [mentioning something about the database schema after M3 upgrade](https://mautic.slack.com/archives/CPVGZE516/p1589381352043400?thread_ts=1589314709.040800&cid=CPVGZE516) on Slack, could this be related?

**UPDATE**: Just tried on a fresh M3 beta-2 installation and getting the same error. Creating a bug ticket now.

**Comment by escopecz** [comment]
@dennisameling can you run it with `-e dev -vvv` flags to see what the full trace looks like?

**Comment by dennisameling** [comment]
@escopecz Unfortunately not, using `--env=dev` to get more details doesn't work as it's the [production package](https://github.com/mautic/mautic/releases/download/3.0.0-beta2/3.0.0-beta2.zip) which misses some dev dependencies.

However, when I run the same command on an instance that's cloned from GitHub (git clone https://github.com/mautic/mautic & checkout 3.x), it works without issues. So I'm assuming there's some dependency that's currently missing in the production dependencies and which is only in the devDependencies

Bug ticket created as I'm able to reproduce with a fresh installation of the [production package](https://github.com/mautic/mautic/releases/download/3.0.0-beta2/3.0.0-beta2.zip): https://github.com/mautic/mautic/issues/8826

**Comment by dennisameling** [comment]
@escopecz `-vvv` seems to work without the `-e dev`. Have posted details in #8826, let's follow up over there

**Comment by dennisameling** [comment]
Need some decisions made on the `app/config/local.php` file (which parameters should be updated with new M3 default values)? This prevents me from finalizing the upgrade script. See https://github.com/mautic/mautic/issues/8831 for details. Hoping that @alanhartless @escopecz can help me with this one 😊

**Comment by RCheesley** [comment]
Just a thought, do we also need to check that there is sufficient free space available to make the backups and database dump? Either before it runs or ensure we throw an error in the event that it runs out of space? If we can't do that we should ensure we make it clear to folk how to check if they have sufficient space available.

**Comment by dennisameling** [comment]
@RCheesley I thought about that, but left it out because it might not be reliable on e.g. shared hosting, where hosts can enforce disk space limits on subscription level (so e.g. the hard drive will have 200GB+ free space, but the subscription of the customer only has 1GB of disk space available). Will need to test if the PHP function `disk_free_space()` https://www.php.net/manual/en/function.disk-free-space.php works on those hosts as well.

I'll add it as a checkbox above so I'll look into it, but best I can do is to raise a pre-upgrade warning (not a hard error) because it might not be reliable. To be continued

**Comment by RCheesley** [comment]
Good point @dennisameling , I think therefore we need to make this super clear and give people an idea of the magnitude of spare space they need - for example double or triple the space Mautic currently takes up on your server - in all of our release docs/comms

**Comment by dennisameling** [comment]
CLI version of the upgrade script is also working now 🎉 

```
denni@mautic-web:/var/www/html$ php upgrade_v3.php
Doing pre-upgrade checks...
Starting upgrade...
Applying Mautic 2 migrations, just so we're sure your database is up to date before upgrading. This might take a while, DO NOT ABORT THE SCRIPT!!!
Downloading Mautic 3...
Extracting the update package...
Extracting done!
Moving Mautic 2 files into mautic-2-backup and moving the Mautic 3 files in place, this might take a while... DO NOT ABORT THE SCRIPT!!!
Done!
Restoring your user data like custom plugins/themes/media from the Mautic 2 installation. This might take a while... DO NOT ABORT THE SCRIPT!!!
Done! Your user data has been restored.
Updating your config/local.php with new settings that were changed/introduced in Mautic 3...
Done! Your config file has been updated.
Preparing for phase 2 of the upgrade...
IMPORTANT: NOT DONE YET! Due to the large amount of changes in Composer dependencies, we now need to restart the script to continue. We've saved your state, so we'll continue where we left off.
PLEASE RUN php upgrade_v3.php AGAIN TO START PHASE 2 OF THE UPGRADE!

denni@mautic-web:/var/www/html$ php upgrade_v3.php
Welcome to Phase 2 of the Mautic 3 upgrade! We'll continue where we left off.
Building cache for Mautic 3...
Done! Cache has been built.
Applying database migrations for Mautic 3... This might take a while, DO NOT ABORT THE SCRIPT!!!
Done! Your Mautic 3 installation is ready. Just one more thing:
Cleaning up installation files that we no longer need...
Cleaned up successfully!
We're done! Enjoy using Mautic 3 :)
```

Next to that, added file cleanup, **then tested both a CLI upgrade and a UI upgrade. Both work now in my test environment**, there's just one minor note for the CLI upgrade: I had to separate the CLI upgrade into 2 phases. The second phase starts after the M3 files are put in place, after which the script needs to be restarted for Symfony commands (like building cache, running database migrations) to succeed.

Commit for reference: https://github.com/mautic/mautic/pull/8824/commits/ae88af52e00a684c5ec7feb696271477144c25f7

**Comment by dennisameling** [comment]
Just finished the pre-upgrade checks: https://github.com/mautic/mautic/pull/8824/commits/9c9c4e50e32ef6ad1fc2975b880521fd7a5ac953

Hope to finish the rest of the script within the next day or two, so we can start testing 🎉

**Comment by dennisameling** [comment]
Just added `mysqldump` database backup functionality, added a note about `api_rate_limiter_cache` (see [here](https://github.com/mautic/mautic/issues/8831#issuecomment-638389557) for details) and fixed several bugs. https://github.com/mautic/mautic/pull/8824/commits/e246a6fb157c6107537585a6f3ad8ea84b6ca3a7

I already ran into some issues while testing, e.g. with a custom plugin that wasn't compatible with Mautic 3 and therefore blocked the cache clearing process. Will need further investigation.

While I finetune some things like error handling here and there, I expect to be able to provide exact testing steps during the weekend. To be continued!

**Comment by dennisameling** [comment]
Did a major overhaul of the UI upgrade of M3 today (otherwise users see a blank loading screen for a few minutes). Gives them exact details of which step is currently running. If an error occurs, error details are shown including a link to the docs for that specific error, e.g. https://docs.mautic.org/en/mautic-3-upgrade-errors#err_move_mautic_2_and_3_files

![Muatic upgrade script success](https://user-images.githubusercontent.com/17739158/83956629-6d29bc80-a860-11ea-94d4-6b4f04b143d6.gif)

Also introduced extensive logging (also creates a logfile) which will help us to troubleshoot failed upgrades MUCH faster together with the users. More on that later.

Found 1 blocking issue which is throwing warnings during cache creation, should be quick to fix, will check tomorrow https://github.com/mautic/mautic/issues/8885

**Comment by dennisameling** [comment]
Things done today:
- Database migrations in the UI are now executed 1 by 1 instead of all at once, to prevent PHP timeout errors. Added benefit is that we can show the amount of migrations that still need to run (e.g. 12 migrations left...)
- Send error codes to Telemetry server (need to finish https://github.com/mautic/statsapp/pull/1 in order to get that to work)
- Built integration with Mautic's native update functionality:

**CLI upgrade:**
```
denni@mautic-web:/var/www/html$ app/console mautic:update:find
Version 3.0.0 of Mautic is available for download. Please visit https://mautic.org for more information.
To update, you can run 'php upgrade_v3.php' from the command line.
``` 

If the user still tries to run `app/console mautic:update:apply`, they'll see

```
denni@mautic-web:/var/www/html$ app/console mautic:update:apply
Are you sure you wish to update Mautic to the latest version? y
Step    1 [->--------------------------] Loading update information...                  

You can only upgrade to Mautic 3 by running 'php upgrade_v3.php' instead of this command.
``` 

Even if a user tries to specify a Mautic 3 file during the upgrade, they will see the error:

```
denni@mautic-web:/var/www/html$ app/console mautic:update:apply --update-package=3.0.0-beta2.zip
Are you sure you wish to update Mautic to the latest version? y
Step    1 [->--------------------------] Loading specified package...                  

You can only upgrade to Mautic 3 by running 'php upgrade_v3.php' instead of this command.
```

**UI upgrade:**

![image](https://user-images.githubusercontent.com/17739158/83974118-27fe9c80-a8eb-11ea-8cf2-01da62197d69.png)

The "Update now" button directly goes to `upgrade_v3.php` instead of Mautic's default update page.

**Comment by dennisameling** [comment]
Note to self while we are in the beta period:
- Look into `open_basedir` issue https://github.com/mautic/mautic/pull/8824#issuecomment-640285227
- Add pre-upgrade check for when instance has >10000 contacts, then recommend to do CLI instead of UI upgrade

**Comment by dennisameling** [comment]
Closing in favor of https://github.com/mautic/mautic/issues/8931
