### ISSUE TITLE
Points are not getting increased for visit pages campaigns

### ISSUE THREAD

**Issue by rnagabandi** [mautic/mautic#882]
Steps:

1) Created two leads
2) created list
3) created email template
4) created campaign with below options
 send email  , open email , visit pages. For each actions try to give some points.

Actual:

Points are not considering for Visit pages or other actions except Send / Open email.

Could you please check and let me know what is missing?

**Comment by escopecz** [comment]
As I replied in https://www.mautic.org/community/index.php/768-points-are-not-getting-increased-for-visit-pages-campaigns

I tested it like that:

- Created a Page
- Created a campaign with a Lead List Source -> add tag -> visited a page from 1 -> add 3 points
- I visited the page from in an anonymous browser (Mautic doesn't track you if you are logged in as admin) with a lead from the list (as a lead source from 2)
- I triggered app/console mautic:campaign:trigger command (should be triggered by a cron job)

In the lead detail I can see that tag was added, page visited and points increased.

**Comment by alanhartless** [comment]
A common reason for visits pages to be ignored is that it's being tested while logged into Mautic.  Mautic will ignore user generated data to prevent skewing stats used for A/B tests etc.  If this could be the case for you, try using another browser, a private browsing session or logout of Mautic while testing.

**Comment by alanhartless** [comment]
Just following up to see if this is still an issue or if it was resolved?

**Comment by Pasley70** [comment]
I had a similar problem. I had given the tracking code for PHP as described under https://www.mautic.org/docs/leads/lead_monitoring.html. However, if you set 'page_url' => $ _SERVER ['REQUEST_URI'] (in PHP) or window.location.href (in JavaScript) the parameter does NOT provided the **host**. The documentation is true only for the HTML Snippet (page_url=**http%3a%2f%2fyourdomain.com**%2fyour-product-page& ...).

After I added the host manually in PHP ('**http://yourdomain.com**'.$_SERVER ['REQUEST_URI']), the tracking of the target URL has worked!

**Comment by escopecz** [comment]
@Pasley70 I made a PR which should fix your problem. Please, check if it is correct now. https://github.com/mautic/documentation/pull/24

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to re-open if you still experience the issue.
