### ISSUE TITLE
Sample data says installed, but there is no data

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8820]
### Bug Description
Setting up to test, and when I ran bin/console mautic:install:data It completes and tells me that it has been successful, however there does not seem to be any data in the database. This is a problem because it means I cannot run acceptance tests.

| Q   | A
| --- | ---
| Mautic version | 3.0.0-beta-2
| PHP version | 7.2.30
| Browser | Chrome

### Steps to reproduce
1. Install Mautic 3
2. Run command `bin/console mautic:install:data`

```
$ bin/console mautic:install:data
This will replace all of the data currently in Mautic's tables. Are you sure you want to continue? (y = Yes, n = No): y
Success! Mautic default data has been installed. The default login is admin/mautic.
```

3. Command completes but there are no dummy leads etc created
 
### Log errors

Don't think these are related:
[2020-05-23 14:45:33] mautic.ERROR: SCHEMA ERROR: An exception occurred while executing 'SELECT f.alias, f.is_unique_identifer as is_unique, f.type, f.object FROM mau_lead_fields f WHERE f.object = 'lead' ORDER BY f.field_order ASC':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic-acceptance-tests.mau_lead_fields' doesn't exist [] []
[2020-05-23 14:46:31] mautic.ERROR: STAT UPDATE: Error communicating with the stat server: 500 (Internal Server Error) [] []

**Comment by dennisameling** [comment]
Just checked Git commit history. Turns out this behavior was changed in this PR: https://github.com/mautic/mautic/pull/8366

You now need to run `bin/console doctrine:fixtures:load`, then the dummy data is inserted into the database. @lukassykora is this how it's supposed to work now after #8366? In 2.16, when we ran `app/console mautic:install:data` it also installed all the dummy data, now we also need to run `bin/console doctrine:fixtures:load` to get that data. If the behavior changed indeed, we'll need to update the docs accordingly.

**Comment by shinde-rahul** [comment]
> doctrine:fixtures:load
loads the data.

**Comment by RCheesley** [comment]
> Just checked Git commit history. Turns out this behavior was changed in this PR: #8366
> 
> You now need to run `bin/console doctrine:fixtures:load`, then the dummy data is inserted into the database. @lukassykora is this how it's supposed to work now after #8366? In 2.16, when we ran `app/console mautic:install:data` it also installed all the dummy data, now we also need to run `bin/console doctrine:fixtures:load` to get that data. If the behavior changed indeed, we'll need to update the docs accordingly.

Perfect, definitely need a docs update for this change, I will make the necessary PR
