### ISSUE TITLE
Selecting audit log filters results in poor layout

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8823]
## Bug Description
When selecting multiple filters the field expands (outside its container)  and shoves the table across the page which is not a great user experience.

![screenshot-m3 mautibox com-2020 05 23-18_15_50](https://user-images.githubusercontent.com/2930593/82736481-fea61400-9d21-11ea-9055-dd79364de328.png)

| Q   | A
| --- | ---
| Mautic version | 3.0.0-beta-2
| PHP version | 7.2.24 (mautibox)
| Browser | Chrome

### Steps to reproduce
1. Open a contact with multiple audit logs
2. Filter by multiple typesand notice the effect on the user interface

**Comment by RCheesley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Contact > Ensure audit log filters and include/exclude options work as expected](https://trello.com/c/WKVNYoWP/54-contact-ensure-audit-log-filters-and-include-exclude-options-work-as-expected)

**Comment by kuzmany** [comment]
Fix https://github.com/mautic/mautic/pull/8848

**Comment by dennisameling** [comment]
Fixed in #8848
