### ISSUE TITLE
running mautic behind ssl teminator

### ISSUE THREAD

**Issue by regevbr** [mautic/mautic#8827]
## Bug Description

When running mautic with https address (which is set in the configuration), the following code enforces all connections to be ssl:
https://github.com/mautic/mautic/blob/916cb750f2e7896c735b231c98fd9a58c65cf0e5/app/bundles/CoreBundle/Loader/RouteLoader.php#L72-L81

Meaning that trying to access http://localhost will cause a 301 redirect to https://localhost.
In general this behavior is great! But in my scenario, where the mautic instance is actually running behind an api gateway that is in charge of handling ssl (ssl terminator) and forcing ssl connections, this behavior causes issues. The issues arise when one tries to make api calls to the mautic instance from within the vpc. In this scenario there is no need for ssl nor doing the round trip via the load balancer and as such direct http requests are made.
When using http requests, mautic redirects them to https which doesn't actually exists, causing all api calls to fail.

| Q   | A
| --- | ---
| Mautic version | 2.15.1
| PHP version | 7.1.30
| Browser | chrome

### Steps to reproduce
1. Run mautic behind ssl terminator, but configure its url (like you should) to use https
2. Try making an api call directly to the instance using http (without using the ssl terminator)
3. You will receive 301 redirect to https which will fail as no one listens on 443.
 
### Suggest solution
Allow to configure if you want to enforce ssl or not

My current workaround was to disable the forceSsl variable in the snippet I mentioned.
One can also remove the https:// part all together from the configuration but I think that is not a good use case.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by regevbr** [comment]
I customized my instance a lot since the bugs and features I needed took a long time to be addressed (if any) so upgrading the version will take me a long time that I don't have... 
The code at the master branch seems unchanged so my guess is that the issue still persists

https://github.com/mautic/mautic/blob/235534b59afa64d568f15d199b04e10c498feaf6/app/bundles/CoreBundle/Loader/RouteLoader.php#L72-L80

**Comment by RCheesley** [comment]
Thanks for clarifying, would you consider looking at making a PR to address this issue?

**Comment by janus-reith** [comment]
I have to deal with the same issue, and changing core code was the only option aswell.

I wonder if that Redirect logic should belong there anyway?
I would expect a Proxy to take care of this.

Maybe this could be optional, not enabled by default but shown as a separate toggle besides the site url configuration?

**Comment by RCheesley** [comment]
Perhaps this PR will help which has just been merged for the next release: https://github.com/mautic/mautic/pull/9499 @regevbr @janus-reith ?
