### ISSUE TITLE
In Manage List , clicking on leads(with CTRL) is always show complete lists instead of actual leads for that list

### ISSUE THREAD

**Issue by rnagabandi** [mautic/mautic#883]
Steps:

1) created 4 leads
2) created 2 lists , each list assigned two leads
3) go to Manage List page , click on leads number,

Actual:

It shows all leads in the system instead of actual leads

**Comment by alanhartless** [comment]
I'm not able to reproduce this.  Is this still an issue?

**Comment by alanhartless** [comment]
Just following up to see if this is still an issue or if it was resolved?

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to re-open if you still experience the issue.
