### ISSUE TITLE
Role access permissions segments view.

### ISSUE THREAD

**Issue by ravinayag** [mautic/mautic#8832]
Hi, 
Currently, There is no Role detailed  access permission defined for Segments, As users can able to see segments defined by other users.  

Can this be hidden segments list view from other user created.  Like the access perm need to enhance like others,  (contacts) view own, view others, edit own, edit others. 

 I feel this  need to be as like others modules.

thanks

**Comment by RCheesley** [comment]
Hi there, this is found under contacts:

![screenshot-local mautic3-2020 07 01-12_51_22](https://user-images.githubusercontent.com/2930593/86240761-b0462980-bb99-11ea-8fc3-6b1a24ae7694.png)

**Comment by ravinayag** [comment]
@RCheesley 
Yes, I tried that but no effect of role permissions.
How to recreate 
1,  Create new role ,  Ref. as per the pic i.e do not select any under segment user access.
![image](https://user-images.githubusercontent.com/52193049/86469556-45425180-bd57-11ea-9b5e-bc850b6f63d7.png)
2,  Create a  new user and assign the role 
3, Login as new user and check, you still able to view the contact segments list. 
![image](https://user-images.githubusercontent.com/52193049/86469747-ab2ed900-bd57-11ea-90c9-da67297f3cef.png)


Expected : 
No segments should be visible if "View Others" is not selected.

**Comment by ravinayag** [comment]
Seems more or less its similar,  but unsure need to check.. 

https://github.com/mautic/mautic/pull/8957

**Comment by ahmad-mushtaq** [comment]
@ravinayag you will need to change the segment settings to non-public.
![segmen](https://github.com/mautic/mautic/assets/7525036/dd325f4d-9ce8-4ac4-930c-f91b2d3e6db4)
