### ISSUE TITLE
Unable to change owner of company

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8839]
## Bug Description
When editing a company and changing the owner a 500 error is thrown due to a column not being found 'companyfax'

| Q   | A
| --- | ---
| Mautic version | 3.0.0-beta-2
| PHP version | 7.2.31
| Browser | Chrome 83

### Steps to reproduce
1. Edit a company
2. Assign owner and save
 
### Log errors

```
 500 Internal Server Error - An exception occurred while executing 'UPDATE 3_x_companies SET companyfax = ? WHERE id = ?' with params ["11", 5]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'companyfax' in 'field list' 
Mautibot
Report an issue
Doctrine\DBAL\Exception\InvalidFieldNameException
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60 at
/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:166 at Doctrine\DBAL\Driver\AbstractMySQLDriver -> convertException ( 'An exception occurred while executing 'UPDATE 3_x_companies SET companyfax = ? WHERE id = ?' with params ["11", 5]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'companyfax' in 'field list'', object(PDOException) )
/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:146 at Doctrine\DBAL\DBALException :: wrapException ( object(Driver), object(PDOException), 'An exception occurred while executing 'UPDATE 3_x_companies SET companyfax = ? WHERE id = ?' with params ["11", 5]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'companyfax' in 'field list'' )
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1069 at Doctrine\DBAL\DBALException :: driverExceptionDuringQuery ( object(Driver), object(PDOException), 'UPDATE 3_x_companies SET companyfax = ? WHERE id = ?', array('11', '5') )
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:743 at Doctrine\DBAL\Connection -> executeUpdate ( 'UPDATE 3_x_companies SET companyfax = ? WHERE id = ?', array('11', '5'), array() )
/app/bundles/LeadBundle/Entity/CustomFieldRepositoryTrait.php:270 at Doctrine\DBAL\Connection -> update ( '3_x_companies', array('companyfax' => '11'), array('id' => '5') )
/app/bundles/CoreBundle/Model/FormModel.php:111 at Mautic\LeadBundle\Entity\CompanyRepository -> saveEntity ( object(Company) )
/app/bundles/LeadBundle/Model/CompanyModel.php:87 at Mautic\CoreBundle\Model\FormModel -> saveEntity ( object(Company), true )
/app/bundles/LeadBundle/Controller/CompanyController.php:354 at Mautic\LeadBundle\Model\CompanyModel -> saveEntity ( object(Company), true )
/app/bundles/CoreBundle/Controller/CommonController.php:449 at Mautic\LeadBundle\Controller\CompanyController -> editAction ( '5', '' )
/vendor/symfony/http-kernel/HttpKernel.php:151 at Mautic\CoreBundle\Controller\CommonController -> executeAction ( 'edit', '5', '0', '' )
/vendor/symfony/http-kernel/HttpKernel.php:68 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
/vendor/symfony/http-kernel/Kernel.php:200 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
/app/AppKernel.php:104 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
/app/middlewares/CORSMiddleware.php:91 at AppKernel -> handle ( object(Request), '1', true )
/app/middlewares/CatchExceptionMiddleware.php:43 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/Dev/IpRestrictMiddleware.php:64 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/VersionCheckMiddleware.php:67 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/TrustMiddleware.php:51 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\TrustMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/run/src/Stack/run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request) )
/index_dev.php:25 at Stack\run ( object(StackedHttpKernel) )
/index.php:6 at require_once ( '/var/app/current/code/pulls/3.x/index_dev.php' )
Previous Exceptions
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'companyfax' in 'field list'
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'companyfax' in 'field list'
```

**Comment by RCheesley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Companies > Change company owner](https://trello.com/c/JVyfQVRZ/123-companies-change-company-owner)

**Comment by RCheesley** [comment]
After doing a bit of digging on this, it seems like this may well relate to sample data. When I create a company from scratch I do not experience this problem.

**Comment by dsp76** [comment]
Nope. I can confirm this also exists with new companies. At least when you enter it the second time and trying to save&close.

**Comment by dsp76** [comment]
@RCheesley same issue with "Change owner of contact". Probably same root cause? Could we change the title and keep it in one issue?

`Error 500 Internal Server Error - An exception occurred while executing 'UPDATE 3_x_leads SET fax = ?, preferred_locale = ?, attribution_date = ?, website = ?, facebook = ?, foursquare = ?, instagram = ?, linkedin = ?, skype = ?, twitter = ? WHERE id = ?' with params ["9", null, "2020-05-27", "http:\/\/21", "22", "23", "24", "25", "26", "27", "5"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fax' in 'field list' `

**Comment by RCheesley** [comment]
Have you tried this locally on an Mautic 3.x instance @dsp76? Still unable to reproduce outside of Mautibox.

**Comment by kuzmany** [comment]
I can't reproduce. Obliviously related to Mautibox and some changes there  - I see two Company Fax custom fields there etc

**Comment by npracht** [comment]
@RCheesley are you able to reproduce on a local environment ? Or Acquia’s prod instance for example ?

**Comment by kuzmany** [comment]
@RCheesley is not able to reproduce in local enviroment. Then we can close  this issue

**Comment by RCheesley** [comment]
@heathdutton pinging FYI

**Comment by heathdutton** [comment]
Agreed this must be connected to manual changes made on the 3.x mautibox or an old migration. Perhaps someone deleted a field or something? In other mautibox PRs I could not reproduce. I'll clean that stage's db, and you can test again.

**Comment by RCheesley** [comment]
Is it possible to automate that on a time basis? I recall talking about it a while back and we were concerned about the chance of kicking someone out mid test, from memory

**Comment by heathdutton** [comment]
It is automated to catch updates/migrations/etc but not to purge and rebuild from scratch. That's by manual decision currently. That being said, perhaps the 3.x/staging branch should be treated differently than the PRs and purged daily?

I'd be cool with that.

**Comment by heathdutton** [comment]
I wonder if the issue was caused by such a forced migration update from a 3.x branch change in the last ~4 days?
