### ISSUE TITLE
Mautic file attachement form

### ISSUE THREAD

**Issue by meetingb** [mautic/mautic#8842]
Hello

i have mautic form with file attachement, have automatic response for suscriber and automatic repport for admin, but can't send file link form or file attachement in admin mail, dont find token for do this and dont see file link in suscriber profile and not have field file in all field list and can't create it!

can you tell me what can i do?

thankyou

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
