### ISSUE TITLE
Plugin submenu (channel->plugin->submenu) wont open?

### ISSUE THREAD

**Issue by dhilst** [mautic/mautic#8850]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version 2.16.0-beta-197-gc4c7260be| 
| 7.3 | 
| Firefox 76.0.1, Safari 13.0.5 |

### Steps to reproduce
I created a gist to reproduce this
1. mkdir -p plugins/HelloWorldBundle/Config
2. curl -o plugins/HelloWorldBundle/HelloWorldBundle.php https://gist.githubusercontent.com/dhilst/43212bb26d6f32a96b25c0f58fcc7671/raw/8bdc8b439f3df08b16a47061f0ddb1d371ea44a5/HelloWorldBundle.php
3. curl -o plugins/HelloWorldBundle/Config/config.php https://gist.githubusercontent.com/dhilst/43212bb26d6f32a96b25c0f58fcc7671/raw/8bdc8b439f3df08b16a47061f0ddb1d371ea44a5/config.php
4. rm -rf app/cache/prod && app/console mautic:plugins:reload
5. Open browser and try to expand the menu

I expect it to expand the submenu `plugin.helloworld.manageworld` but it collapses the `Channels` menu instead.

It seems that it's expanding the submenu then collapsing channel menu, if I go in devtools I can find the submenu into the dom, so it seems a pure javascript problem. If I remove the `collapse` class from submenu manually I can see it

<img width="558" alt="image" src="https://user-images.githubusercontent.com/392820/83303229-132b5600-a1d3-11ea-954b-2f9b6feafbd3.png">

I tried to record a gif, but failed miserably 

 
### Log errors

There are no errors on the devtools console

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by dhilst** [comment]
I will try that on 3.

**Comment by RCheesley** [comment]
Great, will wait to hear back!

**Comment by RCheesley** [comment]
@dhilst any progress at all? Should we close this issue or is it still persisting in Mautic 3.0.2?

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
