### ISSUE TITLE
Change wording for publish dates (as it does not change the published status)

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8851]
## Bug Description
When a landing page is published and has a date time to publish, this works successfully and I said it expired icon against the landing page when that date time has passed.

When the landing page is **unpublished** however, and there is a date time for it to be **published**, nothing happens. The page remains and unpublished after the date time has passed. Edit: This is confusing for the user, perhaps we should call it 'active date' given the comments below that it does not actually affect the published status?

| Q   | A
| --- | ---
| Mautic version | 3.0.0-beta-2
| PHP version | 7.2.31
| Browser | Chrome 83

### Steps to reproduce
1. Create an unpublished landing page with a publish date in the future
2. When the time passes, it does not become published
 
### Log errors
No errors

**Comment by RCheesley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Landing Pages > Create landing page and check publish and unpublish at date/time feature works as expected](https://trello.com/c/pucRndT9/251-landing-pages-create-landing-page-and-check-publish-and-unpublish-at-date-time-feature-works-as-expected)

**Comment by kuzmany** [comment]
You're talking about Page URL or Public Preview URL
From my tests public preview works, but Page Url doesn't work. For me works properly

![image](https://user-images.githubusercontent.com/462477/83355517-3a635e00-a360-11ea-9f84-315966bc195d.png)

**Comment by RCheesley** [comment]
The physical landing page in the list is still showing as unpublished, despite the date for publishing being set.  So the switch says 'unpublished' and it's red, rather than being changed to 'published' and being green, after the date on which it should be published has passed.

When I tried with the opposite behaviour (unpublishing a published page) when the time passed, the page changed to 'expired'.

**Comment by kuzmany** [comment]
But I don't understand what is issue. If page it's unpublished, then publish date/unpublished date are irrelevant. You need publish page and then the status of page relevant to setup dates

**Comment by RCheesley** [comment]
Here is a short screencast to explain https://youtu.be/eYgOzH9sLLs

**Comment by npracht** [comment]
@RCheesley and @kuzmany what is conclusion of your discussions ? :)

**Comment by kuzmany** [comment]
@RCheesley I think it's not issue.

This is feature across all Mautic.

If entity (email, landing page, text message..) is unpublished, then is unpublished even no matter what you set in publish up/publish down - dates are ignored.
If entity is published, then If you set publish up/publish down - the dates are used based on values:

- if publish up is in the future - then entity is not accessible
- If publish up is in past and publish down is in the future - then entity is accessible
- If publish up is in past and publish down is in part -  then entity is not accessible

**Comment by RCheesley** [comment]
So if I understand you correctly, the published/unpublished status of something in Mautic is not related to the publish up/publish down dates but instead they relate to a resource becoming expired when the publish down date is reached?

My understanding as a user would be published up = published, published down = unpublished.  So it seems a bit strange having two different types of availability, and also that we flag something as being expired but nothing happens when something is scheduled to become available, at least from my testing. 

Perhaps we should rename the publish down date as something like expiry date if it is unrelated to the publishing status? It seems very confusing to me!

So I guess if this is default behaviour indeed, then we can close the issue and I will raise this as a UX issue.

**Comment by kuzmany** [comment]
@RCheesley renaming could be good way to improve it

**Comment by staringispolite** [comment]
I had this same issue, and the only way I figured this out was that we paid a Mautic consultant. IMO this issue is causing real confusion which is costing your users money and time.

I think the _logic_ makes sense: the user has a hardwired switch that overrides automatic sending parameters, and that switch defaults to off so that beginners don't accidentally send. It's just that the English labelling of the feature causes confusion. A "publish at" date/time setting implies that the system will publish at that date/time. It doesn't make sense that you have to "publish" the email yourself, which doesn't publish, in order for the system to publish, which does finally publish the email.

Currently there's:
Publish = Yes/No <-- This seems to mean that the email is now "live", or "primed", or "unlocked". The safety is off. Ready for the system to do whatever it is going to do with the settings below
Publish at = Date/time <-- This seems to mean when to send automatically, as long as you've marked it as ready
Unpublish at = Date/time <-- This seems to mean when it becomes unpublished (optional)

I'd propose the following, but personally I'd be open to any wording that doesn't use the same words for both:
**Ready** = Yes/No
Publish at = Date/time
Unpublish at = Date/time

**Comment by RCheesley** [comment]
Re-opening as this is still an issue

**Comment by MutiatBash** [comment]
Hello @RCheesley .....Please i'll like to make a fix for this issue

**Comment by andersonjeccel** [comment]
This definitely needs a fix

The only reason someone would leave a page disabled and schedule to publish obviously is to make it enabled

in which other case someone would use that field?

**Comment by MutiatBash** [comment]
@andersonjeccel …..Are you currently making a fix for it

**Comment by andersonjeccel** [comment]
@MutiatBash Nope, what is your idea for a fix?

From what I understood, the issue title is not exactly pointing the right solution anymore

For example, we can change the wording used, but is the field actually doing something? The fix might be to completely remove the "Publish at" _(currently called "Available from (date/time)")_ field from there

We can start by understanding what's the use for the field before making changes (so you avoid wasting time), I'll assign this to you in the meanwhile

Keep me updated

**Comment by RCheesley** [comment]
@MutiatBash please go ahead and work on a fix for this issue, it'd be great if you can share how you will approach this with @andersonjeccel who leads our UX/UI team to make sure that we're all aligned on how we'll update the language here.

**Comment by MutiatBash** [comment]
@RCheesley .....does this require me setting up the PHP code base

**Comment by RCheesley** [comment]
Hi @MutiatBash you will need to set up your local environment or use gitpod. You'll need to contribute it to the 5.x branch.

Here's some docs: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests

Here's the onboarding call for developers: https://drive.google.com/file/d/1atooVcXnTrIVA5Z_v-MMGAf-zvLmbakX/view?usp=drive_link.

**Comment by MutiatBash** [comment]
@andersonjeccel .....From what i can see...available from-- is the date set for the page to be published...while unavailable from is for unpublishing right?....So i notice that when the time set for publishing has passed...the page still shows unavailable....Is that the issue?

**Comment by andersonjeccel** [comment]
@MutiatBash It's complicated...

I fixed many things about statuses feedback that aren't released yet, this might confuse you.

And @RCheesley, I tested many variations to understand the exact behavior

Let's take an example from an Asset (a PDF that you'd like to provide to leads for download).

When **Available for use** is **Yes**:
- The resource becomes available and can be downloaded accessing the link, including the green Available tag in its details page
- If you set an Available from date, it becomes "Not started yet" and contacts cannot download accessing the link, it'll show a blue tag
- When the Available from date comes, it becomes "Available for use" with green tag and contacts can download accessing the link again
- If you set an Unavailable from date, just defining it does nothing on the status until it comes, but this also seems dependent on the previous field
- When the date for Unavailable from comes, it becomes "Expired on schedule" with blue tag and the respective status message, and the download link cannot be accessed anymore

When **Available for use** is **No**:
- Contacts cannot download the asset accessing the link
- No matter what you set for Available from or Unavailable from, none has effect but you still can set them
- The Available from field doesn't make the asset become available and downloadable

**Comment by RCheesley** [comment]
@andersonjeccel so is this task completed? Or is there work still to be done here, do you think? I feel like it's been completed with the work you've been doing.

**Comment by andersonjeccel** [comment]
@RCheesley It's completed, but I've been forgetting to mention issues in the PR description to close automatically when merged

we might have more issues already done for 5.2

**Comment by RCheesley** [comment]
Great, I am trying to chip away at the old issue backlog to make sure we're closing things promptly! Thanks for letting me know.
