### ISSUE TITLE
Missing language string on marketing message delete modal

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8857]
## Bug Description
When the delete confirmation modal appears after deleting a marketing message from the message view, there is a missing language string: mautic.message.form.confirmdelete

| Q   | A
| --- | ---
| Mautic version | 3,0.0-beta-2
| PHP version | 7.2.31
| Browser | Chrome 83

### Steps to reproduce
1. Open a marketing message and select to delete from the dropdown menu
2. Notice the missing string

![screenshot-local mautic3-2020 05 31-21_32_16](https://user-images.githubusercontent.com/2930593/83362066-4b26ca80-a386-11ea-9940-24e3cde3c711.png)

**Comment by RCheesley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Marketing Messages > Delete message](https://trello.com/c/wUvDHGDE/304-marketing-messages-delete-message)

**Comment by dennisameling** [comment]
Fixed in #8893
