### ISSUE TITLE
Landing page hit does not provide consistent results

### ISSUE THREAD

**Issue by Error-418** [mautic/mautic#8859]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I've created a Double-Opt in email campaign. As described in the [Creating a Double Opt-In Email Campaign](https://www.mautic.org/blog/integrator/creating-a-double-opt-in-email-campaign#) blog post. Including:

* **Form**: New User Sign Up info
* **Landing pages**: New User Sign Up form, Thank you landing page, Confirmed Landing Page
* **Email**: using a template that fixes issues discovered with the Sunday theme (the default button doesn't allow editing separate bug).
* **Campaign**: as described in the tutorial. 
* **Segments**: Pending Opt-in and Confirmed

After visiting the New User Sign Up landing page and filling out a form (and passing reCAPTCHA), the user is sent to the Thank You page. In the backend they are placed in a Pending Opt-In segment, and has an email with a button link for verification sent to them. After the button is clicked they are taken to a Confirmed verification page, and their Segment is changed to Confirmed, and they are then able to start into the campaign (ideally). In reality, some users--after clicking the verification link in the email--are taken to the landing page, but this is never reflected in their Contact information.

In fact, multiple things can happen when they land on the page:

1. Nothing at all. They land on the page and that's the end of it. There's no change to their Contact info, no segment change is made, they do not progress further in the campaign. They just go into a void.
2. The page hit isn't recorded, and the segment isn't updated, but my QA testers (or me) have clicked the link to go to the page.
3. The page hit isn't recorded, but the segment is updated.
4. The page hit is recorded, and the segment is updated. 

| Q   | A |
| --- | --- |
| Mautic version |  2.16.2 |
| PHP version |  7.0.33 | 
| Browser |  Various (FireFox, Chrome, Edge, Brave, Chromebook) |

### Steps to reproduce
1. Follow [Creating a Double Opt-In Email Campaign](https://www.mautic.org/blog/integrator/creating-a-double-opt-in-email-campaign#)
2. Create contacts, have multiple QA testers create contacts in different browsers, with different plugins loaded or not loaded.
3. Monitor Contacts pages and Pending Opt-in segments
 
### Notes
I believe this is related to issues: #5618, #5593, #5079. I've also noted that a formal Double Opt-In system has been requested since at least [2015](https://forum.mautic.org/t/double-opt-in/1532/12), and have noted more than one complaint in various places around the Forums and community about how patchy Double Opt-In implementation is when using Mautic by itself, which is driving users to other 3rd party platforms for email verification, then using Mautic to drive the campaign itself.  

### Log errors
N/A

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
