### ISSUE TITLE
Separate secure config from non-secure config and support env variables in config

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#886]
I very much like how the config is file based and not db based.  

That said, I think it would be smart to separate secure config from the other config.  I don't like storing my db user/pass, mandrill user/pass, etc... in a potentially web accessible location.

Another idea (I just thought of it) would be to allow you to put in environment variables in the config form for secure stuff.  

Example, for db password, be able to put %env.dbpass% (or something like that).  This keeps my secure stuff out of the config file.

**Comment by alanhartless** [comment]
Hey Peter,

You can move the config file anywhere you want once installed or if you're using a non-web installer such as a Docker image.  Create a app/config/paths_local.php file and set `$paths['local_config'] = '/path/to/config.php;`  Then delete app/cache/prod (or dev). 

You should be able to use environment variables inside your config file.  Or are you thinking of through the installer's form?

**Comment by that0n3guy** [comment]
Alan,

> You can move the config file anywhere you want once installed or if you're using a non-web installer such as a Docker image. Create a app/config/paths_local.php file and set $paths['local_config'] = '/path/to/config.php; Then delete app/cache/prod (or dev).

Awesome, I didn't know that.  

> You should be able to use environment variables inside your config file. Or are you thinking of through the installer's form?

Through the installers form would be handy, but not necessary at all.  

If I use env vars in the config file (getevn('db_password') for example), they are overwritten whenever the web config is saved.

**Comment by alanhartless** [comment]
Are they getting overwritten by the actual value/string?

**Comment by that0n3guy** [comment]
Yup, I just tested it.

**Comment by alanhartless** [comment]
So there is a way around this by using a app/config/parameters_local.php.  Basically it allows you to force/override configuration parameters.  Obviously not for the average user but in there for non-Mautic web installers, Docker stuff, etc if needed.

You can either remove or leave blank the db config stuff in the configuration file.  Then set the overrides in app/config/parameters_local.php:

```
$parameters = array(
    'db_password' => getevn('db_password'),
    // ...
);
```

That should prevent them from getting overwritten.

**Comment by that0n3guy** [comment]
Gotcha.   That works for now.  

It would still be nice if we had a `getenv` for something like you do with `%kernel.root_dir%`  To add directly in the form.  Something like `%getenv.db_password%`.

**Comment by alanhartless** [comment]
:+1: I'll mark this as a feature request.
