### ISSUE TITLE
CORS ISSUE

### ISSUE THREAD

**Issue by starshunter88** [mautic/mautic#8861]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

I keep receiving CORS errors in my Chrome Console. I enabled all origins options in both Htacess files but there is no solution. I believe this depends from the browser settings. Is that possible?

Access to XMLHttpRequest at 'https://.../mtc/event' from origin 'https://digitaldojo.it' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute .../mtc/event:1 Failed to load resource: net::ERR_FAILED
mtc.js:61 Uncaught TypeError: Cannot read property 'type' of undefined
    at mtc.js:61
    at mtc.js:3
    at Object.MauticJS.processGatedVideos (mtc.js:61)
    at MauticJS.initGatedVideo (mtc.js:60)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
