### ISSUE TITLE
Missing language string on marketing message overview

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8863]
## Bug Description
When viewing a marketing message, there is a missing language string: mautic.campaign.message.send

| Q   | A
| --- | ---
| Mautic version | 3.0.0-beta-2
| PHP version | 7.2.31
| Browser | Chrome 83

### Steps to reproduce
1. Create and send a marketing message
2. View message overview and note the missing string
 
![screenshot-local mautic3-2020 06 01-15_09_15](https://user-images.githubusercontent.com/2930593/83417807-8541ac00-a41a-11ea-9195-1783c65a841d.png)

**Comment by mohit-rocks** [comment]
https://github.com/mautic/mautic/pull/8871 fixes the issue.

**Comment by dennisameling** [comment]
Fixed in https://github.com/mautic/mautic/pull/8871
