### ISSUE TITLE
Didnt receive the email for user validation so I can't log in

### ISSUE THREAD

**Issue by pchernandes** [mautic/mautic#8866]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, you'll need to include a bit more detail if anybody is going to be able to help you. Log in where, for example?

**Comment by pchernandes** [comment]
Here: https://prnt.sc/ssasxp

I didn't receive the email to confirm my email, so I can't log in anywhere.

**Comment by RCheesley** [comment]
Hi, This is related to the website, not Mautic - ping me on Slack if you still need help with this (https://mautic.org/slack to get an invite)

**Comment by pchernandes** [comment]
Ok, sent through Slack.

Em qua., 1 de jul. de 2020 às 08:38, Ruth Cheesley <notifications@github.com>
escreveu:
