### ISSUE TITLE
Reschedule event or cancel event in contact's history isn't working

### ISSUE THREAD

**Issue by jadersbr** [mautic/mautic#8867]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
In contact's history, specifically at scheduled event, we have an option to cancel event or reschedule event, but, this feature isn't working.

| Q   | A
| --- | ---
| Mautic version | 3.0.0-beta2 and 2.16.0
| PHP version | For M3 PHP 7.3 for M2 PHP 7.1
| Browser | Google Chrome

### Steps to reproduce
1. Add contact to campaign that has an event scheduled to future.

example...
![Anotação 2020-06-01 222312](https://user-images.githubusercontent.com/58928002/83469713-c9eb3880-a456-11ea-8feb-eb5ab1154886.png)

2. Try cancel this event in contact's history. Visually, the event was canceled, but if you refresh page, the event it's still scheduled and will be fired.

3. Try reschedule this event in contact's history. Reschedule to be executed now, early or future, isn't working.
 
### Log errors
Today's Mautic error log is empty. Check server error log for error messages Mautic didn't have a chance to catch.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
This should fixed it https://github.com/mautic/mautic/pull/8116

**Comment by jadersbr** [comment]
> This should fixed it #8116

I applied this PR in Mautic 3.0.0-beta2 and Mautic 2.16.0. The issue with cancel event was fixed. The scheduled event was deleted.

However, reschedule the event didn't work.
