### ISSUE TITLE
[bug] Config page not showing updated values using "apply"

### ISSUE THREAD

**Issue by that0n3guy** [mautic/mautic#887]
Here is how to duplicate this:
* go to your config (/s/config/edit)
* edit your mandrill username
* hit apply.  The page will reload and **show the old username**, but the local.php file will show the updated one.
* hit refresh to see the changes you actually made.

I'm on v1.2.0

**Comment by alanhartless** [comment]
@that0n3guy 

I've been trying to reproduce this but haven't been successful in doing so.  

Is this reproducible on other fields?

Are you by chance using Chrome and have auto-fill enabled? (Chrome ignores `autocomplete="off"` now; we had a workaround by using `autocomplete="false"` but seems a merge with the last release overwrote one of the templates and thus didn't make the change for the config file fields; will fix that).

Are you using an opcache of some sort and if so, which one?

Thanks!
Alan

**Comment by alanhartless** [comment]
Just following up to see if this is still an issue or if it was resolved?

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to re-open if you still experience the issue.
