### ISSUE TITLE
Non administrator role can not override locked segment

### ISSUE THREAD

**Issue by nrfocus** [mautic/mautic#8870]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Non administrator role can not override locked segment

| Q   | A
| --- | ---
| Mautic version | v2.16.2-5
| PHP version | 7.2.28
| Browser | Google Chrome

### Steps to reproduce
1. I created a Role let’s call it “R1” with the following “Contact permissions”
Contacts - User has access to : Full
Segments - User has access to: Full
Import - User has access to: View

2. When user “U1” having role “R1” edit a segment “S1”, user “U2” having role “R1” can not override the locked segment S1.
Only a user having “Administrator” role can override the locked segment “S1”.
 
### Log errors
no errors

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
