### ISSUE TITLE
Webhook payload stage object not complete

### ISSUE THREAD

**Issue by jpuebla** [mautic/mautic#8872]
Mautic version v2.16.2

Payload stage object from webkook "lead_post_save_update" is not complete, some properties missing:

["mautic.mautic.lead_post_save_update"]
{[
  {
    .....
      "ipAddresses": [],
      "tags": [],
      "utmtags": [],
      "stage": {
        **"createdByUser": "Name LastName",
        "modifiedByUser": null**
      },

I only get 2 properties of lead stage.

If I try to get contact from REST Api instead Webhook stage properties are correct:

"stage": {
            "createdByUser": "Name LastName",
            "modifiedByUser": null,
            "id": 1,
            "name": "Cuenta nueva",
            "category": null,
            "weight": 0,
            "description": null
        },

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
