### ISSUE TITLE
vTiger Plugin - Some leads not syned to vtiger when they submit the form at the same time

### ISSUE THREAD

**Issue by ithieund** [mautic/mautic#8873]
## Bug Description
Let's say we have 5 to 10 customers that submit the landing page at the same time
Only some of that leads can be synced to vtiger, many of them not be synced!

## Environment
Mautic version: v2.16.2 and v3.x
PHP version: v7.1.32 and v7.3.9
Browser: Chrome, Firefox, Safari

### Steps to reproduce
1. Create a new Form with some fields that match the lead fields. Set Action for this form to call Push to Intergration and select vTiger there. Then save the form.
2. Create a new Landing Page and load the form we created at step 1 then save the page
3. Send Landing Page public link to multiple testers, ask them to input the form but not submit it yet
4. When more than 5 testers entered the form, ask them to submit the form at the same time
5. Check Contacts list in Mautic, all lead are there
6. Check Leads list in vTiger, some leads are missing, not all of them come to CRM
 
### Log errors
There is no error log but I had debug the code and turned out that the mapped data is empty for some leads. Thats why they can not be pushed to createLead function
![image](https://user-images.githubusercontent.com/4217195/83734906-d1d6f280-a679-11ea-8538-072dd682501e.png)

### My Research
Mautic calls vTiger native webservice that need a long process before creating lead
- getChallenge
- getToken
- describe (to get field list for mapping)
- create

=> When multiple connections call that process, the connection come later will cause session name in the previous connection invalid and only some latest connection that does not conflict with each other can be done successfully. Other previous connection well have invalid session name and can not do anything futher.

Hope that infomation can help you fix this bug :)

**Comment by RCheesley** [comment]
Thanks for submitting this issue @ithieund - are you able to make a PR to address the problem at all?
