### ISSUE TITLE
Disable public access to Mautic login/dashboard

### ISSUE THREAD

**Issue by S733** [mautic/mautic#8877]
Hi,
   For security reasons I need to restrict public access to mautic login/dashboard. I'm using the mautic docker container along with nginx-proxy container. I tried to add nginx rules to block access to /s/.  For authorized users I'm getting 404 and for unauthorized users, getting 403 Forbidden. I used the below code, any one please suggest what I'm doing wrong or any other way to get this working. I think the culprit here may be the symfony or apache redirect after the nginx proxy.

location ^~ /s { 
allow xxx.xxx.xxx.xxx/32;
deny all;
 }

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems or have questions :)
