### ISSUE TITLE
 Froala messes up the HTML source

### ISSUE THREAD

**Issue by vdavid** [mautic/mautic#8879]
## Bug Description

In the "send email" window, when I edit an email, Froala messes up the HTML source by adding `fr-original-class`, `fr-original-style` HTML attributes, removes others, and rearranges the code somewhat.

Email screenshot: https://www.screencast.com/t/NygKFsqW
Code screenshot: https://www.screencast.com/t/myHM0ybj
(left side: good version, right side: messed up by Froala)

Version: Mautic 2.16.1
PHP version: 7.2.x
Browser: Chrome

This is an open bug where this bug could be linked: https://github.com/mautic/mautic/issues/7272
This is the closed bug: https://github.com/mautic/mautic/issues/2368, maybe it could be linked here as well.

| Q   | A
| --- | ---
| Mautic version | 2.16.1
| PHP version | 7.2.x
| Browser | Chrome

### Steps to reproduce
1. Edit an email in the "send email" window that has "class" and "style" attributes.
2. Observe how Froala messes up the HTML source by adding `fr-original-class`, `fr-original-style` HTML attributes, removes others, and rearranges the code.
 
### Log errors

None.

**Comment by claudeschneider** [comment]
Also seeing this exact same issue when working with emails, Mautic version 2.16.2

Additional comments:

- when editing email in Builder, the HTML code looks fine
- when we click "Preview", the HTML style/class is displayed in fr-original-class/fr-original-style elements, and the actual style/class elements contains minimal/different content
- when the changes are saved, the HTML stored in the DB contains "fr-original-style" attributes with all our desired style
- when I edit the email again later, the style is shown correctly in the raw HTML of the email being edited.

It looks like Froala is moving AND saving our desired style into fr-original-style, and not keeping it in "style"


This Froala bug (https://github.com/froala/wysiwyg-editor/issues/2317) may be relevant, with a `useClasses` flag defining whether to store modified attributes in fr-original-style

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Actually I'm going to close this in favour of #7272 and make that issue title more general so we have the discussions in one place.
