### ISSUE TITLE
Can't edit existing segments after update to 2.16.2

### ISSUE THREAD

**Issue by cefimadmin** [mautic/mautic#8880]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | PHP Version 5.6.40-0+deb8u11
| Browser | Chrome 83.0.4103.61

### Steps to reproduce
1. Try to edit an existing published segment
2. The segment does not open
3. On the other hand, I can create a new segment and then edit it. And i can also edit an existing unpublished segment.
 
### Log errors
 mautic.ERROR: PHP Error - Argument 1 passed to Mautic\LeadBundle\Segment\Stat\ChartQuery\SegmentContactsLineChartQuery::getTotalStats() must be an instance of Mautic\LeadBundle\Segment\Stat\ChartQuery\int, string given, called in /var/www/mautic/app/bundles/LeadBundle/Segment/Stat/SegmentChartQueryFactory.php on line 30 and defined - in file /var/www/mautic/app/bundles/LeadBundle/Segment/Stat/ChartQuery/SegmentContactsLineChartQuery.php - at line 90

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
