### ISSUE TITLE
Add Stage as a filter to email dynamic content creates 500 server error

### ISSUE THREAD

**Issue by PeachySoftware** [mautic/mautic#8887]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Dynamic Content in a email filtered by *Stage* will cause a 500 Server Error when Apply or Close Builder clicked.  

| Q   | A
| --- | ---
| Mautic version | 2.16 & 3.0 (m3.mautibox.com)
| PHP version | 7.3 (on mine)
| Browser | Chrome

### Steps to reproduce
1. Create/Edit Email
2. In Email Builder, add a Dynamic Content section
3. Add a variant
4. Add a Filter by Stage. (equals S1 or any stage created)
5. Click Apply. Prod version shows error, Beta Site shows error page.
`500 Internal Server Error - PHP Notice - Undefined index: stage`

 
### Log errors
`/app/bundles/LeadBundle/Form/Type/FilterTrait.php:172 at
/app/bundles/LeadBundle/Form/Type/FilterTrait.php:172 at Mautic\CoreBundle\ErrorHandler\ErrorHandler -> handleError ( '8', 'PHP Notice - Undefined index: stage', '/var/app/current/code/pulls/3.x/app/bundles/LeadBundle/Form/Type/FilterTrait.php', '172', array('eventName' => 'form.pre_bind', 'event' => object(FormEvent), 'translator' => object(DataCollectorTranslator), 'currentListId' => null, 'data' => array('glue' => 'and', 'operator' => '=', 'filter' => '1', 'display' => '', 'field' => 'stage', 'type' => 'stage', 'object' => 'lead'), 'form' => object(Form), 'options' => array('disabled' => false, 'label_format' => null, 'translation_domain' => null, 'trim' => true, 'required' => true, 'mapped' => true, 'by_reference' => true, 'inherit_data' => false, 'compound' => true, 'method' => 'POST', 'action' => '', 'post_max_size_message' => 'The uploaded file was too large. Please try to upload a smaller file.', 'allow_file_upload' => false, 'error_mapping' => array(), 'invalid_message' => 'This value is not valid.', 'invalid_message_parameters' => array(), 'allow_extra_fields' => false, 'extra_fields_message' => 'This form should not contain extra fields.', 'csrf_protection' => true, 'csrf_field_name' => '_token', 'csrf_message' => 'The CSRF token is invalid. Please try to resubmit the form.', 'csrf_token_manager' => object(CsrfTokenManager), 'csrf_token_id' => null, 'block_name' => 'entry', 'label' => false, 'attr' => array('class' => 'form-control'), 'auto_initialize' => false, 'data_class' => null, 'empty_data' => object(Closure), 'property_path' => '[0]', 'error_bubbling' => false, 'label_attr' => array(), 'upload_max_size_message' => object(Closure), 'validation_groups' => null, 'constraints' => array(), 'position' => null, 'countries' => array('Afghanistan' => 'Afghanistan', 'Åland Islands' => 'Åland Islands', 'Albania' => 'Albania', 'Algeria' => 'Algeria', 'Andorra' => 'Andorra', 'Angola' => 'Angola', 'Anguilla' => 'Anguilla', 'Antarctica' => 'Antarctica', 'Antigua and Barbuda' => 'Antigua and Barbuda', 'Argentina' => 'Argentina', 'Armenia' => 'Armenia', 'Aruba' => 'Aruba', 'Australia' => 'Australia', 'Austria' => 'Austria', 'Azerbaijan' => 'Azerbaijan', 'Bahamas' => 'Bahamas', 'Bahrain' => 'Bahrain', 'Bangladesh' => 'Bangladesh', 'Barbados' => 'Barbados', 'Belarus' => 'Belarus', 'Belgium' => 'Belgium', 'Belize' => 'Belize', 'Benin' => 'Benin', 'Bermuda' => 'Bermuda', 'Bhutan' => 'Bhutan', 'Bolivia' => 'Bolivia', 'Bonaire, Saint Eustatius and Saba' => 'Bonaire, Saint Eustatius and Saba', 'Bosnia and Herzegovina' => 'Bosnia and Herzegovina', 'Botswana' => 'Botswana', 'Bouvet Island' => 'Bouvet Island', 'Brazil' => 'Brazil', 'Brunei' => 'Brunei', 'Bulgaria' => 'Bulgaria', 'Burkina Faso' => 'Burkina Faso', 'Burundi' => 'Burundi', 'Cape Verde' => 'Cape Verde', 'Cambodia' => 'Cambodia', 'Ca`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Possibly related to #8875 for Mautic 3

**Comment by RCheesley** [comment]
@PeachySoftware as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1? Thanks!

**Comment by PeachySoftware** [comment]
@RCheesley Unfortunately it does. I just updated to 3.0.1. Here is a link to a [CloudApp recording ](https://share.getcloudapp.com/xQuDRpDn),

Also a brief copy of that line in the log.

`[2020-07-03 13:51:33] mautic.NOTICE: PHP Notice - Undefined index: stage - in file /home/forge/lists.xxxx.xxx/mautic/app/bundles/LeadBundle/Form/Type/FilterTrait.php - at line 172 {"eventName":"form.pre_bind","event":"[object] (Symfony\\Component\\Form\\FormEvent: {})","translator":"[object] (Mautic\\CoreBundle\\Translation\\Translator: {})","currentListId":null,"data":{"glue":"and","operator":"=","filter":"1","display":"","fie`

Hope that helps.

**Comment by RCheesley** [comment]
@PeachySoftware thanks so much for checking and for the recording! Hopefully it is the same bug in a different place as was fixed by #8907 so should be a quick fix!
