### ISSUE TITLE
 difference between outlook mac and windows

### ISSUE THREAD

**Issue by panart-reclamestudio** [mautic/mautic#8888]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v2.16.0-dev
| PHP version | 7(i think)
| Browser | chrome

### Steps to reproduce
Hee i got a problem with my e-mails. when i look at the previeuw email send by mautic on Mac outlook everything looks good. But when i look on windows in outlook there are some issu's like an button i created got a little block on the top of it and the spacing between elements are not oke. is there anything i can do?

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
