### ISSUE TITLE
Erro com o Login

### ISSUE THREAD

**Issue by LMGomesCosmeticos** [mautic/mautic#8890]
Olá, tudo bem?
Meu nome é Heloisa, falo em nome da LMgomes Cosméticos.

Recentemente, começamos a introduzir o Mautic em nossa empresa. Então por enquanto, o único conhecimento que eu possuo do Mautic, é o cadastro de leads. Ou seja, estou bem perdida rsrs.

Tem 1 semana mais ou menos que eu não estou conseguindo mais logar na conta do Mautic. Ele abre a página para fazer o login, mas quando eu clico em logar, não acontece nada.
Já procurei em outros lugares, mas não achei como resolver isso.

obs: foi uma outra pessoa que fez a implementação, e eu não estou mais conseguindo entrar em contato com essa pessoa.

Alguém poderia me ajudar?
![Login Mautic](https://user-images.githubusercontent.com/66643577/84072373-74a6ae00-a9a5-11ea-8aed-c4b635a087f1.png)

**Comment by marcusrfaust** [comment]
> Olá, tudo bem?
> Meu nome é Heloisa, falo em nome da LMgomes Cosméticos.
> 
> Recentemente, começamos a introduzir o Mautic em nossa empresa. Então por enquanto, o único conhecimento que eu possuo do Mautic, é o cadastro de leads. Ou seja, estou bem perdida rsrs.
> 
> Tem 1 semana mais ou menos que eu não estou conseguindo mais logar na conta do Mautic. Ele abre a página para fazer o login, mas quando eu clico em logar, não acontece nada.
> Já procurei em outros lugares, mas não achei como resolver isso.
> 
> obs: foi uma outra pessoa que fez a implementação, e eu não estou mais conseguindo entrar em contato com essa pessoa.
> 
> Alguém poderia me ajudar?
> ![Login Mautic](https://user-images.githubusercontent.com/66643577/84072373-74a6ae00-a9a5-11ea-8aed-c4b635a087f1.png)

Você conseguiu resolver de que forma?

Estou com o mesmo problema.

**Comment by marcusrfaust** [comment]
Consegui resolver indo no servidor > Pasta de instalação do Mautic  
Acionando o seguinte código:

rm -rf var/cache/*
