### ISSUE TITLE
pageview of anonymous/non existing contact are not tracked

### ISSUE THREAD

**Issue by sirpy** [mautic/mautic#8899]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
when a user sends the mt('send','pageview') event, he is not added to the anonymous contacts
also if we send with email (enabled as public+unique) mt('send','pageview',{email:someemail})
it also doesnt appear as a new contact.
only if contact with email already exists then the pageview event is registered

| Q   | A
| --- | ---
| Mautic version | 2.15
| PHP version | 
| Browser | any

### Steps to reproduce
1. with incognito browser and not identified by fingeerprint before send mt('send','pageview') from console (or visit a page with the tracking javascript added)

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by sirpy** [comment]
@RCheesley 
i'm not sure what's the expected behaviour. I actually later found in the docs example that you should first add the user via calling the API to submit a form (with user email).

**Comment by RCheesley** [comment]
You should see anon users by [toggling the option or searching in contacts](https://docs.mautic.org/en/contacts#search-text) - otherwise you only see known leads.

I will close this an it does not seem to be a bug with Mautic
