### ISSUE TITLE
Problems exporting report in CSV format

### ISSUE THREAD

**Issue by dmarkotter** [mautic/mautic#890]
I set up a new report to export a csv file containing lead data- FirstName, LastName, Email. Phone, Mobile etc.

1. The resulting csv file contains blank rows - presumably deleted leads.
2. The phone field strips leading zeros and reformats the phone numbers, e.g.

* Original number: 073 090 7665
* CSV output: 730 907 665

3. The XLSX file contains the blank rows, but the phone numbers are correct.

**Comment by dmarkotter** [comment]
Just checked the CSV file itself. The problem is with the way Excel interprets the phone number field. Open Office imports the file perfectly.

**Comment by alanhartless** [comment]
Sounds like we could possibly solve this by wrapping the value in quotes when we export to CSV.

**Comment by alanhartless** [comment]
After looking into this and reading other services that export to CSV, it seems this is a common issue with Excel and recommended by others to use Excel's import wizard as the fix. A quick search brings up articles like https://support.office.com/en-us/article/Text-Import-Wizard-c5b02af6-fda1-4440-899f-f78bafe41857 and https://support.office.com/en-us/article/Import-or-export-text-txt-or-csv-files-e8ab9ff3-be8d-43f1-9d52-b5e8a008ba5c#bmimport_data_from_a_text_file_by_openi (see the Note under #3).
