### ISSUE TITLE
Wrong page.hit queue with mtracking.gif

### ISSUE THREAD

**Issue by evenloooo** [mautic/mautic#8900]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I embedded mautic tracking pixel in some web page and email letter to `page.hit`.

I found an issue with `page.hit` with queue(RabbitMQ), I've set up queue in Mautic, but I didn't run `php /var/www/mautic/app/console mautic:queue:process`, I thought all of `page.hit` events(tracking pixel and `GET /mtc/event`) should be store in queue first, `GET /mtc/event` work perfectly, but tracking pixel doesn't store in queue first.

This is my access log with `mtracking.gif`, I didn't run `mautic:queue:process`, but these data already store in Contacts.
![image](https://user-images.githubusercontent.com/9351031/84388214-c611a000-ac26-11ea-887c-59a16d85f66c.png)

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.3.17
| Browser | Chrome 83.0.4103.97

### Steps to reproduce
1. set up RabbitMQ in mautic configuration, didn't run `php /var/www/mautic/app/console mautic:queue:process` on server
2. visit tracking pixel url `http://yourdomain.com/mtracking.gif?email=example@example.com`
3. go to Contacts on admin panel
4. found `example@example.com` in Contacts

### Log errors
No error

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)
