### ISSUE TITLE
{contactfield=ipAddress} variable does not work

### ISSUE THREAD

**Issue by zietbukuel** [mautic/mautic#8902]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I've tried to use `{contactfield=ipAddress}` to display the IP Address of the user in DWC and Landing Pages, but this doesn't seem to be working as nothing gets printed. Shouldn't this display the current user's IP?

I've also tried with `{contactfield=ipaddress}` (all lowercase) but still nothing.

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.3
| Browser | Chrome, Firefox, Safari

### Steps to reproduce
1. Create a DWC or Landing page 
2. Use the variable/token `{contactfield=ipAddress}`
 
### Log errors
None.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by npracht** [comment]
Hi, without any feedback we cannot carry this issue open anymore. I'll close it and in case a new comment justify to re-open it, I'll be glad to do it :)

**Comment by zietbukuel** [comment]
Sorry for the delay, I tested this but I'm unable to use this variable/token in Mautic 3.0.1 or 3.0.2.
