### ISSUE TITLE
Integration not updated when Lead/Campaign Member removed in Salesforce

### ISSUE THREAD

**Issue by crms-matt** [mautic/mautic#8904]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Integration association with Salesforce Lead and Campaign Members is not removed when records are deleted in Salesforce.

If a Lead is deleted in Salesforce, the Integration tab still shows an association between the Mautic Contact and the Lead record in Salesforce.  If the contact is removed from Mautic, it become recreated by the integration at the next sync.

If a Campaign Member is deleted in Salesforce, the Integration tab still shows an association between the Mautic Contact and the Campaign Member record in Salesforce.

(I assume the same is the case for Salesforce Contact records too).

Ideal behaviour would be...
* Lead/Contact deleted in Salesforce removes the Lead/Contact integration record in Mautic
* Campaign Member record deleted in Salesforce removes the relevant Campaign Member Integration record in Mautic

Salesforce include a queryable IsDeleted boolean on these objects and this is set to true for deleted records (before they are purged from the database).  After they are purged from the database (by a user emptying the Recycle Bin), the record Id is not queryable.

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.3.17
| Browser | Chrome

### Steps to reproduce
**Lead Removal**
1. Contact in Mautic in sync with Lead in Salesforce
2. Delete the Lead in Salesforce
3. Wait for sync to complete
4. Delete the Lead in Mautic
5. Mautic recreates the (deleted) Lead from Salesforce at the next sync

**Campaign Member Removal**
1. Contact in Mautic in sync with Lead in Salesforce
2. Lead in Salesforce becomes associated with the a Campaign in Salesforce (CampaignMember record created)
3. Integration CampaignMember record created in Mautic
4. Remove the Lead's association with the Campaign in Salesforce (delete the Campaign Member record)
5. Wait for integration sync
6. CampaignMember record in Mautic not removed

 
### Log errors
No errors logged

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by michaeljansse** [comment]
@RCheesley we've tried to make this work in Mautic 3.0.1. We get an error when creating a segment with the filter Integration Campaign Members. When you select a SalesForce Campaign and click on Apply, you get an error that says "This value is not valid". The log shows this error:
[2020-07-20 10:15:16] mautic.WARNING: PHP Warning - array_flip(): Can only flip STRING and INTEGER values! - in file /var/www/html/mautic3test/public/app/bundles/LeadBundle/Form/Type/FilterTrait.php - at line 274

**Comment by jvdborre** [comment]
I was facing the same issue in Mautic 3.1.2, upgraded to 3.2 with no succes

here's my errorstring: mautic.WARNING: PHP Warning - array_flip(): Can only flip STRING and INTEGER values! - in file /home/mauticuser/webapps/Mautic/app/bundles/LeadBundle/Form/Type/FilterTrait.php -
 at line 275
