### ISSUE TITLE
Problem with Lookup and Select fields

### ISSUE THREAD

**Issue by dmarkotter** [mautic/mautic#891]
I'm using Mautic 1.2.

I'm trying to create a Lookup field, but when I try to save and close the field, the progress bar animates for a few seconds, then the Cancel/Save&Close/Apply buttons grey out, without the field being saved.

I've tried this with the Select field type as well - the same thing happens.

At least 2 other people are having the same problem: 

https://www.mautic.org/community/index.php/751-problem-with-lookup-and-select-fields

**Comment by wderuijter** [comment]
I've got the same issue.

**Comment by escopecz** [comment]
Fixed in https://github.com/mautic/mautic/pull/895. Ready to test.

**Comment by alanhartless** [comment]
Fixed and will be part of 1.2.1.
