### ISSUE TITLE
Emails of automation campaign are being sent with risk alert

### ISSUE THREAD

**Issue by Vitoria96** [mautic/mautic#8911]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I created a campaign which emails are programmed to trigger to my contacts every 3 days, but they are all being sent with risk/spam alerts and people can only click the content after clicking in "seems safe." Can you please advise? I dont know how to fix this problem. 

Thanks, 

Vitória 

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there,

Please post this at https://forum.mautic.org where you will be more likely to get support, as Github is only for bugs with Mautic.
