### ISSUE TITLE
Address quick & dirty fix for API default settings from #8854

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#8913]
## Bug Description
We applied a quick and dirty fix to address this issue (see #8854 and PR #8912) , but we need to fix the root cause.

Parking for revisiting in 3.0.1.

**Comment by npracht** [comment]
@RCheesley is it closed by #8914 ?

**Comment by RCheesley** [comment]
No, this issue was about the [default settings for the API being incorrect](https://github.com/mautic/mautic/issues/8854) - we [did a fudge to fix](https://github.com/mautic/mautic/issues/8913) it but this issue was to make sure that it is properly addressed.
