### ISSUE TITLE
how to add new font in emailer  "builder" (mautic3)!!!!!!

### ISSUE THREAD

**Issue by raghav111jain** [mautic/mautic#8918]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.0
| PHP version | 7.2
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**how to add new font in builder not option there (mautic3)!!!!!! if already exits that feature let me know please ASAP**

**Comment by RCheesley** [comment]
Hi there, Github is for reporting bugs, please post your question at https://forum.mautic.org
