### ISSUE TITLE
Problem adding custom fields

### ISSUE THREAD

**Issue by dmarkotter** [mautic/mautic#892]
When I add a custom field, the new field is inserted at the top of the list, rather than at the end of the list. 

It doesn't seem to be possible to sort by field ID, so every new field has to be manually dragged to the bottom of the list. 

It would be helpful to be able to sort the list by group, by field ID or by label.

**Comment by alanhartless** [comment]
When creating or editing a lead field, there's an order drop down that you could use to set the order.  Then you wouldn't have to manually drag them.

![](http://alan.direct/drop/2015-09-18_23-56-47.png)

Selecting the order would basically put the new field in the selected field's position and move the rest down.
