### ISSUE TITLE
Unable to install Mautic | Probably Database Problem

### ISSUE THREAD

**Issue by raiyansarker** [mautic/mautic#8920]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
My Mautic is unable to install. I am unable to set database, database name and user with email are correct. But it is showing me this error, "
An error occurred while attempting to add default data: An exception occurred while executing 'CREATE INDEX instagram_search ON leads (instagram)': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOB". I don't know what to do. Please help me to get relief. The website url is : mautic.weblearn.website. I am running on Apache server!

| Q   | A
| --- | ---
| Mautic version | 3
| PHP version | 7.3
| Browser | Chrome, Firefox
 
### Log errors
An error occurred while attempting to add default data: An exception occurred while executing 'CREATE INDEX instagram_search ON leads (instagram)': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOB

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
This has been raised on the support forum, please can you provide input there? I will leave this as a bug as it saves us raising it, but the correct place to get support is on the forums.

Here is the link to the issue: https://forum.mautic.org/t/mautic-3-0-installation-error-row-size-too-large/14801?u=rcheesley

**Comment by RCheesley** [comment]
Please see https://forum.mautic.org/t/mautic-3-0-installation-error-row-size-too-large/14801 - looks to be an issue with the database version being unsupported.

**Comment by raiyansarker** [comment]
I am unable to post in the forum. But I saw the post yesterday and the solution today. I checked my database version and it is what I found, "mysql  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2". I am not using any panels, just apache2 and MySQL. I followed this guide to create the server and installation, https://blog.h-educate.com/how-to-install-mautic/

**Comment by RCheesley** [comment]
You just need to browse the forum for ~10 mins to get access to post and reply.

Looks like MariaDB 10.1, so suggest looking at updating that or installing where the version is higher.
