### ISSUE TITLE
Mautic Batch API getting extremely slow after importing ~1M contacts

### ISSUE THREAD

**Issue by liquidsnk** [mautic/mautic#8921]
## Bug Description
We're importing and synchronizing a great deal of leads/contacts into out Mautic database using the Batch API. Specifically `POST /api/contacts/batch/new`, `PUT /api/contacts/batch/edit` and `PATCH /api/contacts/batch/edit` depending on the situation.
We're sending batches of 200 items, one request at a time, which is the max on the default configuration and we determined initially it was the fastest method.
The process was working fine, although we could see that import times were deteriorating.
After we reached around 1M contacts in our database, creating/updating 200 contacts started to take a very long time, of more than **2 minutes**, which required us to increase php/apache timeouts and also php memory limits.
The hardware we're running on has a lot of room for this, however, apparently the process is more CPU bound than anything? We don't thing the database is being hit hard either.
I don't think the process to create new contacts should degrade this much even when having a lot of contacts already in there?

| Q   | A
| --- | ---
| Mautic version | 2.16.2 | 
| PHP version | 7.2.27 | 
| Browser | n/a | 

### Steps to reproduce
1. Batch import (via API) ~1M contacts into Mautic.
2. Keep performing batch imports of 200 items at a time.
3. Time to process the batches will degrade incredibly.
 
### Log errors
We started noticing the issue by getting timeout errors and memory errors (don't know if this indicates a leak of some sort or not).
[2020-06-16 21:32:12] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\OutOfMemoryException: "Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes)" at /home/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php line 2780 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\OutOfMemoryException(code: 0): Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) at /home/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2780)"} []
We've received this error from multiple places after running our process a while and we've have since increased our memory for PHP to 5GB.

While I am not familiar with the system I've attempted to profile a similar operation made to another server which was also starting to see degradation on a count of about ~150k contacts, in case it's useful: https://1drv.ms/u/s!AsCcPLJG5_swgsBhWaBufSxN-baZ8w?e=tuP6ds

![image](https://user-images.githubusercontent.com/283740/84911412-7a2f8280-b08e-11ea-9ea9-e928199134ca.png)

**Comment by liquidsnk** [comment]
The slowness was actually caused by what it appears to be a bug in the batch API that was creating "phantom" stages over and over when patching contacts without providing a current stage. While checking stages we saw hundred of thousands of copies of the default stage we were using for contacts... after removing those and starting to always provide the stage on updates the problem was solved.

**Comment by RCheesley** [comment]
Could you raise an issue for this with your findings?

**Comment by simcen** [comment]
Stumbling across this, might be related to https://github.com/mautic/mautic/issues/8951
