### ISSUE TITLE
New import page is not opening anymore 

### ISSUE THREAD

**Issue by felipe0silva** [mautic/mautic#8923]
We can not open the import page anymore because there is some previous import failed in the queue

I cant cancel this failed proccess and i'm not able to open a new import. Please Help, what can i do to solve this?

Look this image: https://imgur.com/a/Nuk2kr3

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
