### ISSUE TITLE
Pipedrive Synch - Companies Duplicated in Pipedrive

### ISSUE THREAD

**Issue by renanwilliam** [mautic/mautic#8926]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have a problem in fetching Organizations from Pipedrive to Mautic. When a setup a integration between a Mautic installation that already have existing companies manually synched with Pipedrive using a CSV, all Mautic Companies are send again to Pipedrive and duplicate all common organizations.

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.1.33
| Browser | Chrome 83.0.4103.106 

### Steps to reproduce
- Pipedrive integration is off and never executed before
- I'm already have loaded company data in Mautic manually using a CSV file based on Pipedrive data.
- Turned on Pipedrive Integration
- Executed the command `php app/console mautic:integration:pipedrive:fetch`
- The output is:
```
Pulling company
===============

 Pulled 0

 ! [NOTE] Using 121.634816 megabytes of ram.                                                                            

 Pulling more...
 Pulled 0

 ! [NOTE] Using 123.731968 megabytes of ram.                                                                            

 Pulling more...
 Pulled 0

 ! [NOTE] Using 130.023424 megabytes of ram.                                                                            

 Pulling more...
 Pulled 0

 ! [NOTE] Using 136.31488 megabytes of ram.     
```
 - Note that is paginating against my 2000 companies in Pipedrive but always prints "Pulled 0"
 - Looking at error log file, it's showing the following message: 
   `mautic.ERROR: INTEGRATION ERROR: Pipedrive - Company already exist [] []`

Because this, isn't created the entry in **integration_entity** with relation between Pipedrive organization and Mautic Company.

After that, when I execute the command `php app/console mautic:integration:pipedrive:push`, Mautic will create all companies again in Pipedrive.

In my understanding, when I fetch the data, the plugin needs to match the company/organization name and save this relation on integration_entity table, for when system push the data, not duplicate on Pipedrive.
 
### Log errors
- mautic.ERROR: INTEGRATION ERROR: Pipedrive - Company already exist [] []

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by renanwilliam** [comment]
Yes, 3.0.1 has the same behavior. I have made some research and I think that the code responsible is [here](https://github.com/mautic/mautic/blob/3.x/plugins/MauticCrmBundle/Integration/Pipedrive/Import/CompanyImport.php#L57).

**Comment by RCheesley** [comment]
Thanks for the quick reply, would you be up for making a pull request to address this?

**Comment by svassaux** [comment]
i still have the same issue on v4.1.2

After running `php console mautic:integration:pipedrive:fetch`

i have 

![image](https://user-images.githubusercontent.com/9137903/156390360-64dbaf77-c613-4105-b9fe-9c4a049e9a07.png)

and it fails because of memory exhaustion 

should it not liberate memory after each iteration? I have 100k contacts/companies, how am I supposed to make it work ?

@RCheesley can we reopen the issue?
