### ISSUE TITLE
CSV file import frozen on browser and background 

### ISSUE THREAD

**Issue by raghav111jain** [mautic/mautic#8927]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.0
| PHP version | 7.2
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**same thing happened if upload csv don't process ij front and background also. if click background not process only show in q and if click import on browser both are condition not processing then if import on browser and refresh the page import same contact . i don't understand what type issue Please help ASAP**

**Comment by RCheesley** [comment]
Hi there, please check the [documentation](https://docs.mautic.org/en/contacts/import-contacts#background-import) for guidance on using the background import - notably that you must trigger it with a cron job.

If you are stuck please post at https://forum.mautic.org/c/support.
