### ISSUE TITLE
Only the last link is tracked in emails

### ISSUE THREAD

**Issue by nkosi23** [mautic/mautic#8928]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When sending an email, if the email contains the same link repeated multiple times, Mautic only turns the last occurrence of the link into a trackable link, the other links are not replaced with trackable links while they should be. 

To clarify, if an email contains 4 "plain" links A, B, C, D (with their trackable versions being TA, TB, TC, and TD). If the email contains - for example - the following sequence of links represented with vector notation (A, B, C, A, A,  D) the transformation applied by Mautic results in the following (A, TB, TC, A, TA, TD) - only the last plain link A is transformed into TA.

This is problematic because it is quite common to repeat the call to action multiple times in a marketing email in different manners. Some leads will click on the first link others on the last etc...

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.2.31
| Browser | 

### Steps to reproduce
1. Create an email template with multiple links and some of the links appearing multiple times in the email as previously explained
1. Send the email through a campaign
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi @nkosi23 as we are only providing fixes for Mautic 3.x going forward, can you confirm if this persists in Mautic 3.0.1?

**Comment by janus-reith** [comment]
I can observe the described behavior in v3.0.1 and now v3.0.2 aswell.
Only the last two links are replaced by redirecting tracking links.

**Comment by RCheesley** [comment]
@janus-reith thanks for checking this, I'll update the labels!

**Comment by CyberMarsl** [comment]
In my installation of Mautic 3.0.2 both links in the Email are replaced (same links).

I use the latest 7.3.x php and i have it configures with the url shortener bit.ly (but the link is replaced with: \*.mjt.lu/lnk/\*
