### ISSUE TITLE
form multiple time summited ??

### ISSUE THREAD

**Issue by raghav111jain** [mautic/mautic#8933]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.0
| PHP version | 7.2
| Browser | chrome 
### Steps to reproduce
1. 
2. 
 
### Log errors

**form multiple time summited ?? 
if you click multiple time submit button then form submit multiple time** 
![image](https://user-images.githubusercontent.com/53876757/85208464-644fe500-b34e-11ea-90ca-c44299b409bd.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, this does not sound like a bug but intended behaviour if you have the form set to remain on the same page. If you need support with setting up your forms, please take a look at the [documentation](https://docs.mautic.org/en/components/forms) and post on https://forum.mautic.org/c/support if you get stuck!
