### ISSUE TITLE
Mautic getting hanged while processing.

### ISSUE THREAD

**Issue by faheemrazaa** [mautic/mautic#8939]
Hello,

i have installed Mautic at http://regrowme.com/mail/

While im importing contacts or sending mails to the contacts the whole application is getting hanged.

I'm not sure if it is happening due to server speed issue or have any bug in this application.

Kindly check this Screenshot attached with this.

Plz provide me solution for this issue.

Thanks
Author at [PickCamera](https://pickcamera.com)

![d85a9e95-90cc-4635-8927-ef2c8e8577b4](https://user-images.githubusercontent.com/36882362/85388533-d4838400-b563-11ea-9dea-b9e559797470.png)

**Comment by RCheesley** [comment]
Hi there, please post on the forums at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic rather than for support.
