### ISSUE TITLE
Unable to delete used tags via API

### ISSUE THREAD

**Issue by luk4s** [mautic/mautic#8947]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If some tags are still used on contacts, there is no way delete them. If I try it trough API, it raise mysql error.
I must delete tags directly in mysql, from table `erm_lead_tags_xref` first, then `erm_lead_tags`.

I am not sure if its general error (missing some dependency in code) or its just issue my instance...

| Q   | A
| --- | ---
| Mautic version |  v2.16.2
| PHP version | 7.1.30-2+0~20190710.21+debian9~1.gbp011d3c
| Browser | Safari

### Steps to reproduce
1. Basically I send DELETE request for each tag returned by API
2. https://developer.mautic.org/#delete-tag
3. almost every request end with mysql error...
 
### Log errors

```
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic`.`erm_lead_tags_xref`, CONSTRAINT `FK_1DE6B74EBAD26311` FOREIGN KEY (`tag_id`) REFERENCES `erm_lead_tags` (`id`)) at /data/www/mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic`.`erm_lead_tags_xref`, CONSTRAINT `FK_1DE6B74EBAD26311` FOREIGN KEY (`tag_id`) REFERENCES `erm_lead_tags` (`id`)) at /data/www/mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mautic`.`erm_lead_tags_xref`, CONSTRAINT `FK_1DE6B74EBAD26311` FOREIGN KEY (`tag_id`) REFERENCES `erm_lead_tags` (`id`)) at /data/www/mautic/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105)"} []
```
[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
