### ISSUE TITLE
Using Batch API to update contacts via PATCH can create weird copies of the contact stage if no stage is provided

### ISSUE THREAD

**Issue by liquidsnk** [mautic/mautic#8951]
## Bug Description
While importing/updating contacts through the batch API we discovered that strange "copies" of the initial stage we were indicating for these contact were being generated. It seemed like copies would appear per each contact included in the batch or most of them, also, these copies did not ended up associated to the contact (the original stage was still the one being assigned to them).
Apparently this issue was triggered when a PATCH call was made to `/api/contacts/{id}/edit` without including any stage (id) in the payload. To work around it at the moment we started providing the stage id on every PATCH call we make.

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.2.27
| Browser | n/a

### Steps to reproduce
1. Create two contacts and assign them to a same **stage**.
2. Call `PATCH /api/contacts/batch/edit` with any payload updating these two **existing** contacts.
Could be as simple as: `[{ "id": 1 }, { "id": 2 }]` supposing those are their IDs.
3. A duplicate of the stage assigned to the contacts will be created.

If the **stage id** is included in the call for each of the contacts, no duplicate is created.

### Log errors
n/a

**Comment by RCheesley** [comment]
Thanks for reporting this bug! Would you be up for taking a look at fixing it with a PR?
