### ISSUE TITLE
{pagelink} malforms URL

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#8955]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When using the {pagelink=X} shortcode as a link, the URL returned is malformed and does not work.

| Q   | A
| --- | ---
| Mautic version | v3.0.0
| PHP version | 7.3
| Browser | Chrome Version 83.0.4103.106 
### Steps to reproduce
1. Create link in email to a landing page using the {permalink=X} shortcode
2. You should see that the URL built when the email is previewed etc is incorrect. For me, emails are formed like so: https://https//contact.domain.com/confirm
 
### Log errors
Don't see any issues in the log for this.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for taking the time to report this! Is it still the case on 3.0.1?
