### ISSUE TITLE
Mautic stops working with error:Failed to authenticate on SMTP server

### ISSUE THREAD

**Issue by wildlily980** [mautic/mautic#8960]
Mautic had worked for years but it has stopped from sending any emails since 4 days ago without changes
There are many files in app/spool/, I had to remove them manually to free disk space
SMTP server is working fine if I send an email by shell.

| Mautic version |  unknown
PHP Version 5.6.30

I'm not sure if this is a bug or not. Any help is greatly appreciated

### Log errors from dashboard->mail send setting->servce to send email though->test connection
Failed to authenticate on SMTP server with username "xxx" using 2 possible authenticators
... >> AUTH LOGIN << 334 VXNlcm5hbWU6 >> base64(xxx) << 334 UGFzc3dvcmQ6 >> xxx << 535 5.7.8 Error: authentication failed: Connection lost to authentication server !!

### Log errors from app/logs

[2020-06-27 09:27:12] mautic.NOTICE: Swift_TransportException: Failed to authenticate on SMTP server with username "xxxx" using 1 possible authenticators (uncaught exception) at /var/www/htmlpt/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php line 181 while running console command `mautic:emails:send` [] []

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
