### ISSUE TITLE
Return-Path/Bounce Uses + Character Mailserver Not Allows

### ISSUE THREAD

**Issue by TnowL** [mautic/mautic#8962]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The current Return-Path uses + character. Example, `bounce+bounce_5ef5fba271203@example.com`. The problem with that is now mailservers are not allowing + character anymore.

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.2.30
| Browser | Firefox

### Steps to reproduce
1. Fill out all fields correctly and test was success!
2. Subscribed to form with fake non-existing domains and non-existing addresses.
3. No bounce
 
### Log errors
 None, emails never came because mailserver rejected all email addresses with + character.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### Possible Solution?
This used to work fine before but as mailservers updating as mine had. It's now a problem. Can we replace the + with _ or - character? I think that will work fine.

Also unsubscribe as well, `bounce+unsubscribe_5ef5fba271203@example.com`.

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by TnowL** [comment]
> 
> 
> Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
> Thanks!

I've just upgraded to v3.0.1 and this is still an issue.

**Comment by TnowL** [comment]
After researching for the last few weeks, I now understand why using + character now. I guess mailservers treat `user+list@domain.com` as `user@domain.com`. Just some mailservers for some reasons don't allowed +. I have to find another open source mailserver that will work for now.

**Comment by RCheesley** [comment]
OOK, as this is a mailserver issue I will close the issue!
