### ISSUE TITLE
can't end set up  

### ISSUE THREAD

**Issue by picaso212** [mautic/mautic#8964]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.0.0
| PHP version | 7.3
| Browser | firefox

### Steps to reproduce
1. download mautic | unzip by ssh in vps 
2. begin setup | localhost OK | data user ok | data base ok 
 
### Log errors
An error occurred while attempting to add default data: An exception occurred while executing 'CREATE INDEX instagram_search ON leads (instagram)': Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by JakubHelis** [comment]
+1,
Same issue:
SQL: 10.1.44-MariaDB
PHP 7.3.18-1
Mautic version: Github 3.x branch

**Comment by RCheesley** [comment]
You need to update your database version - see the minimum requirements here: https://www.mautic.org/download/requirements.

Also, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
