### ISSUE TITLE
form using http: when configured to use https: causing form submission to fail

### ISSUE THREAD

**Issue by petebytes** [mautic/mautic#8966]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Submitting a form using shortcode fails.
Although the error message initially indicates a CORS issue, it is more likely a problem with the form being submited with http: instead of https: I think the mautic javascript which generates the form is not respecting the site url settings and instead using http:
Note the last error below `This request has been blocked; the content must be served over HTTPS`

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | 7.3.19
| Browser | Safari 13.1.1; Firefox; Chrome Canary 86.0.4185.0

### Steps to reproduce
1. Configure WP shortcode to submit form [mautic type="form" id="1"]
2. attempt to submit form
 
**Mautic url is configured to use https**
![image](https://user-images.githubusercontent.com/676739/85961502-b5b82f80-b95f-11ea-87d1-44540d3f39b0.png)

**WP Mautic is configured to use https**
![image](https://user-images.githubusercontent.com/676739/85961528-d1bbd100-b95f-11ea-8652-3de09b335efb.png)

I have rebuilt the form cache and it did not solve the issue.

### Log errors
`POST https://mautic.healing.courageousjourneys.com/form/submit?formId=18 500
app.js?vc74e26bf:243 `

`Uncaught DOMException: Blocked a frame with origin "https://mautic.healing.courageousjourneys.com" from accessing a cross-origin frame.
    at HTMLDocument.<anonymous> (https://mautic.healing.courageousjourneys.com/media/js/app.js?vc74e26bf:243:347)
    at fire (https://mautic.healing.courageousjourneys.com/media/js/libraries.js?vc74e26bf:328:299)
    at Object.fireWith [as resolveWith] (https://mautic.healing.courageousjourneys.com/media/js/libraries.js?vc74e26bf:333:198)
    at Function.ready (https://mautic.healing.courageousjourneys.com/media/js/libraries.js?vc74e26bf:340:11)
    at HTMLDocument.completed (https://mautic.healing.courageousjourneys.com/media/js/libraries.js?vc74e26bf:340:291)
(anonymous) @ app.js?vc74e26bf:243
fire @ libraries.js?vc74e26bf:328
fireWith @ libraries.js?vc74e26bf:333
ready @ libraries.js?vc74e26bf:340
completed @ libraries.js?vc74e26bf:340
submit?formId=18:1 `

`Mixed Content: The page at 'https://courageousjourneys.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mautic.healing.courageousjourneys.com/s/login'. This request has been blocked; the content must be served over HTTPS.`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by petebytes** [comment]
I disabled WP Mautic and configured the form manually.  It unfortunately did not solve the issue.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by petebytes** [comment]
Thanks - I believe this is a bug - site should not break when url is correctly identified as https
My workaround for now is to not change that setting (but based on search results others have run into the same issue)
