### ISSUE TITLE
Hebrew Page Title Tracking Error in Mautic 3

### ISSUE THREAD

**Issue by chendwww** [mautic/mautic#8984]
## Bug Description
The page titles are still in wrong names in Mautic 3.0.1, the issue has been opened since Mautic 2.15, see  [7525 ](https://github.com/mautic/mautic/issues/7525)

In the dicussion in [7525 ](https://github.com/mautic/mautic/issues/7525), it says the issue will be fixed in Mautic 3, but I still see the issue in Mautic 3.0.1 version:

![image](https://user-images.githubusercontent.com/25785677/86387260-81c56d00-bcc5-11ea-8a5b-8f815167ae74.png)

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1.  Install Mautic track code at any non-english web page, such as Japanese, Chinese 
2. check the contact info and see page view events
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, what database collation and encoding are you using?

**Comment by chendwww** [comment]
> Hi there, what database collation and encoding are you using?

We use utf8mb4, MySQL version is 8.0. The Mautic files set to utf-8 when unzip to server.

**Comment by chendwww** [comment]
There are some screenshot about the event sent to mautic 3. It might help:

![event](https://user-images.githubusercontent.com/25785677/86860577-b1c2a500-c0f7-11ea-9999-b437a9663291.png)


Request Data:

page_title=WinDeal%E6%97%A0%E4%BB%A3%E7%A0%81%E9%9B%86%E6%88%90%E4%B8%8EAI%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD%E5%B9%B3%E5%8F%B0-%E6%90%AD%E5%BB%BA%E4%BC%81%E4%B8%9A%E8%87%AA%E5%8A%A8%E5%8C%96%E4%B8%8E%E6%99%BA%E8%83%BD%E5%8C%96%E7%9A%84%E5%95%86%E4%B8%9A%E6%B5%81%E7%A8%8B&page_language=zh-CN&page_referrer=&page_url=http%3A%2F%2Fwindeal.cn%2F&counter=0&timezone_offset=-480&resolution=2560x1440&platform=Windows&do_not_track=false&mautic_device_id=y8lcwdopvh2hkt6tgvc9lrr

The Data in MySQL

![event2](https://user-images.githubusercontent.com/25785677/86860645-d1f26400-c0f7-11ea-93a2-2a6eb8a70077.png)
