### ISSUE TITLE
Mautic 3 breaks form fields - if custom form field attributes are applied

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#8985]
## Bug Description
Mautic forms customization is broken currently in version 3.

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3.14
| Browser | any

### Steps to reproduce
1. add e.g. ​`class="fusion-one-half one_half fusion-layout-column fusion-spacing-yes"` to "field container attributes" field for a text field in a form
2. check the manual code of the created for the form (dynamic code will have the same issue) - instead of `<div id="mauticform_form_field" class="mauticform-text mauticform-field-5 fusion-one-half one_half fusion-layout-column fusion-spacing-yes" ... >
` it shows as `<div id="mauticform_form_field" mauticform-text mauticform-field-5 fusion-one-half one_half fusion-layout-column fusion-spacing-yes ... >`

The class element and its wrapping is completely missing, if you decide to add classes to it via the above mentioned field.
 
### Log errors
none

**Comment by RCheesley** [comment]
Yuck, what a frustrating bug! Thanks for taking the time to report it! Seems like a missing class= somewhere - could you take a look and see if you can submit a fix?

**Comment by dsp76** [comment]
@RCheesley as in the other issue: I can't fix it as of now. I can help spotting issues, testing and investigating into it. :/

**Comment by RCheesley** [comment]
@dsp76 thanks - we have a whole bunch of issues labeled with the [triage-Mautic-3](https://github.com/mautic/mautic/issues?q=is%3Aopen+is%3Aissue+label%3Atriage-Mautic-3) label that need confirming whether they still exist in Mautic 3.x - if you'd like to help with those it would be hugely appreciated!

**Comment by dsp76** [comment]
Seems to have been fixed. Can't recreate in 3.2.5.

**Comment by RCheesley** [comment]
Thanks for reporting back!
