### ISSUE TITLE
URL Link in form description area field of unstyled form still contains element styling

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#8987]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Even when forms are set to render style no, links in description fields get element styles attached:

    background: transparent;
    box-sizing: border-box;
    color: rgb(78, 93, 157);
    text-decoration: none;

| Q   | A
| --- | ---
| Mautic version |  2.16.2 and 3.0.1
| PHP version | 7.3.14
| Browser | any

### Steps to reproduce
1. add description area field to a form and include a link into it
2. set to render style "no"
2. check source code of rendered form
 
### Log errors
none

**Comment by RCheesley** [comment]
@dsp76 thanks for reporting the bug, would you be up for taking a look at fixing this?

**Comment by dsp76** [comment]
Hi @RCheesley - thats way beyond my capabilities ;)
I did some investigation however and think it might be some buggy behaviour of Froala
(similar to this: https://github.com/froala/wysiwyg-editor/issues/2317)

Not sure if its Froala adding styles or mautic... 
The style applied to the link in the rendered form doesn't show up in the source within Froala though.

**Comment by RCheesley** [comment]
OK I think that this is a duplicate of #7272 which relates to froala interfering with the html? Thanks for checking that it happens in Mautic 3.x as well!
