### ISSUE TITLE
The lead is not assigned to the segment by API

### ISSUE THREAD

**Issue by marcerebrum** [mautic/mautic#8990]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
See this screencast.

https://www.loom.com/share/e3d8936a8eb14b678128fbd6d7c332c4

The lead is not assigned to the segment by API.

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.2.31
| Browser | Google Chrome

### Steps to reproduce

https://www.loom.com/share/e3d8936a8eb14b678128fbd6d7c332c4
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, unfortunately Thrive Leads have stopped updating their Mautic integration as discussed in [this forum thread](https://forum.mautic.org/t/mautic-3-0-0-this-form-is-no-longer-available-thrive-leads/14892), and it is no longer listed on their[ integrations page](https://thrivethemes.com/integrations/). I suspect that this might be the problem.

I recommend contacting them on the forum [here](https://thrivethemes.com/forums/topic/mautic-support/) - needs a paid account to access - and requesting them to update their integration!
