### ISSUE TITLE
HTML Image Map links not converted to trackable links

### ISSUE THREAD

**Issue by Jammmmm** [mautic/mautic#8992]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Links in HTML image maps (\<map\>) are not converted into Mautic's trackable links.
Regular links (\<a\>) are converted without problems.

| Q   | A
| --- | ---
| Mautic version | 2.16.3
| PHP version | 7.3.19
| Browser | Chromium and Mozilla Thunderbird

### Steps to reproduce
1. Create and send an e-mail similar to the following:

```
<html>
<title>{subject}</title>
<body>
	<img src="https://example.com/images/2020/07/example.jpg" width="600" height="1200" usemap="#Map" border="0" /><br />
	<a href="https://example.com/">This link will convert without problems</a>
	<map name="Map" id="Map">
	  <area shape="rect" coords="108,100,205,128" href="https://www.example.com/" />
	  <area shape="rect" coords="412,101,492,125" href="https://www.example.com/about" />
	</map>
</body>
</html>
```

2. Note the \<a\> link converts into a tracked URL, but the two URLs within the \<map\> remain the same.
 
### Log errors
N/A

----

I am not using 3.x yet since I don't have the time to oversee the upgrade just yet, but I assume this is an ongoing bug in all versions.

The easiest solution would have been to explicitly define trackable links using the {externallink=https://www.example.com/} functionality, however that seems to have been removed (I couldn't find it in the code).

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for raising the issue!

**Comment by Jammmmm** [comment]
This is being marked as stale but as far as I can tell, the problem still exists.

**Comment by Jammmmm** [comment]
Just wondering if the {externallink} tags can be re-implemented because I haven't been able to track e-mails ever since I permanently switched to Mautic over 1 year ago.

There is definitely a bug here but the tag seems like it would be easier to reimplement rather than tracking down the bug.

**Comment by Jammmmm** [comment]
Replying to remove stale label.

This issue still exists in community 3.3.3. I have not tested the 4.x series.

**Comment by Jammmmm** [comment]
As above. Replying to keep this issue open because it still exists. Also as above, I have not tested the 4.x series.

**Comment by Jammmmm** [comment]
I'm still on 3.x for now, which hasn't had an update since August 30, 2021. The problem still exists in 3.x.

I haven't upgraded to 4.x yet. At some point I will and will re-test when I do.

So for now, yes, the bug definitely still exists in 3.x. Unconfirmed in 4.x.

**Comment by RCheesley** [comment]
Hi @Jammmmm please review and test #11391 which fixes this issue. We will not be making any future releases of Mautic 3, so you will need to update to Mautic 4 in order to get the fix.

Here is how to review a pull request using Gitpod: https://contribute.mautic.org/contributing-to-mautic/tester#the-easy-way-using-gitpod and how to leave a review after testing: https://contribute.mautic.org/contributing-to-mautic/tester#leaving-your-review.

**Comment by Jammmmm** [comment]
I'm glad to see that this has potentially been fixed!

Unfortunately we're still running Mautic 3.x. We do intend on updating to 4.x but we're not sure of the timeframe just yet so I won't be able to test for a while.

**Comment by RCheesley** [comment]
Thanks @Jammmmm - you can always help by testing on Gitpod :) We have merged the PR so it will be in the next bug fix release thanks to @biozshock 🥳
