### ISSUE TITLE
Second Focus item won't trigger

### ISSUE THREAD

**Issue by wavelski** [mautic/mautic#8993]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have two Focus items installed on my webstie:

1. Newsletter form (triggered once per session on ANY page, upon arrival, Timeout before engage null and How often to engage? set to Once per session)
2. Another form (triggered once per session on a PARTICULAR page, uppon arrival, with Timeout before engage set to 5 seconds and How often to engage? set to Every page)
both installed with GTM.

**The problem:**

Second Focus item won't trigger. If I access PARTICULAR page directly in incognito, first Focus Item triggers with no problems. Any ideas what I'm doing wrong? ;)
| Q   | A
| --- | ---
| Mautic version | v2.16.3
| PHP version | 7.2.31
| Browser | Chrome Version 83.0.4103.116 (Official Build) (64-bit)

### Steps to reproduce
1. Create two or more Focus Items
2. Trigger both on one page
 
### Log errors
none

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, can you confirm if this persists in Mautic 3.0.1? We are only providing security fixes for the 2.x series going forward. Thanks!

**Comment by RCheesley** [comment]
Closing due to a lack of recent activity. Please create a new issue and link to this one if necessary.
