### ISSUE TITLE
Same image embedded in email multiple times

### ISSUE THREAD

**Issue by ramandi** [mautic/mautic#8995]
## Bug Description
When email is configured to get the images embedded, if the same image is referenced multiple times in the message, it gets added multiple times, even when only one reference will be used.

In function convertEmbedImages in https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/Helper/MailHelper.php we can see that for every match we get this executed:
                    $this->embedImagesReplaces[$match] = $this->message->embed(\Swift_Image::fromPath($match));

When the match is repeated, the key will be overwritten in $this->embedImagesReplaces, but message->embed will still be executed and the same image will be embedded multiple times.

I think before embedding the image you should check if key already exists.

| Q   | A
| --- | ---
| Mautic version | 2.16.0
| PHP version | 7.3
| Browser | N/A

### Steps to reproduce
1. Configure email to embed images in base64.
2. Create an email that references the same image several times.
3. Send the email and review the source code.

**Comment by RCheesley** [comment]
Hi there, have you tried updating? We pushed several fixes in 2.16.1 and 2.16.2, some of which related to embedded images.

**Comment by ramandi** [comment]
Not really, since I thought the problematic code was still there.  I will try it tomorrow.  Thank you!

**Comment by RCheesley** [comment]
Ok great. As a side point, we are not providing fixes for the Mautic 2 series outside of security fixes, so if this does not exist in 3.0.1 we will close the issue.

**Comment by ramandi** [comment]
I have updated to 2.16.3 and images are not being embedded at all, so I can't check the original problem.  Do you know if that is a known problem or what could I be missing?

Thank you!

**Comment by ramandi** [comment]
Ok, I guess that emails sent manually don't get images embedded, but the ones sent from campaigns do.  I don't know if this is the expected behaviour.
Anyway, the problem described is still there also in version 3.0.1.

**Comment by RCheesley** [comment]
Thanks for checking, I have tagged the issue and hopefully we can get this looked into shortly!

**Comment by ramandi** [comment]
I'm not confident enough to send patches, but I think I solved this changing
      if (false === strpos($match, 'cid:')) {
by
      if (false === strpos($match, 'cid:') and !array_key_exists($match,$this->embedImagesReplaces)) {
in https://github.com/mautic/mautic/blob/staging/app/bundles/EmailBundle/Helper/MailHelper.php#L983

Best regards!

**Comment by RCheesley** [comment]
> I'm not confident enough to send patches

Would you like to learn? We are happy to walk people through how to create a pull request :)

**Comment by ramandi** [comment]
I'm not confident enough in my code and in my knowledge about mautic and mautic code.  I mean someone should review it.  But if it helps, I will be glad to send a pull request.

**Comment by ramandi** [comment]
I'm sorry for the "noise", but I think I finally managed to create the pull request.

**Comment by ramandi** [comment]
> 
> 
> > I'm not confident enough to send patches
> 
> Would you like to learn? We are happy to walk people through how to create a pull request :)

Hi @RCheesley,

I just submitted 2 PRs (https://github.com/mautic/mautic/pull/9080 for this issue and https://github.com/mautic/mautic/pull/9081 for another one). In both of them the automatic checks are complaining about lack of tests.  I didn't add any line of code, so the situation was exactly the same before.  Are the PRs ok like that?  Can I expect someone to review and merge them?  TBH, I don't think I can find the time to learn how to write tests right now.

Thank you!

**Comment by RCheesley** [comment]
Thanks for the PR's - we have a sprint this weekend so hopefully we can take a look! 

A few tests will run to check for test coverage and also to check automated tests, codestyle and so forth.

**Comment by npracht** [comment]
Fixed in 3.2.2
