### ISSUE TITLE
[bug] Add to mailchimp spinner keeps spinning after fields are loaded

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#90]
Minor thing, but the add to mailchimp spinners (there are two, not sure why) keep spinning after the fields are displayed when adding actions to a form

http://nimb.ws/j0xYNU

**Comment by alanhartless** [comment]
Based on the screenshot and the missing description box, I think this is probably related to #89 and the JS errors due to a cached JS file after the upgrade.

Thanks!
Alan

**Comment by RCheesley** [comment]
Thanks, yes this is working after clearing cache!
