### ISSUE TITLE
Mautic Error Screen - Report an Issue Shortlink is 404

### ISSUE THREAD

**Issue by jordan8037310** [mautic/mautic#9000]
## Bug Description
When encountering an issue on Mautic 3.x, there is a shortlink to `Report an Issue` which links to:

http://mau.tc/report-issue

This URL redirects the User to A support forums search that doesn't exist: https://forum.mautic.org/search?q=%2523support%2520order%253Alatest

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.2
| Browser | Chrome

### Steps to reproduce
1. When receiving a 500 error (could be any error) 
2. Click on the link to `Report an Issue`
3. Land on Support Forums experience that doesn't exist.

**Comment by jordan8037310** [comment]
Screenshot for context 

![image](https://user-images.githubusercontent.com/3300713/87089323-1dd20580-c1eb-11ea-929d-35d786661069.png)

**Comment by RCheesley** [comment]
Thanks for reporting this - it seems the query syntax changed at some point so I have updated the link to point at the Support forum which should not change!
