### ISSUE TITLE
Some emails don't get the embedded images

### ISSUE THREAD

**Issue by ramandi** [mautic/mautic#9003]
## Bug Description
When email is configured to embed images, by default only 100 emails get the images properly embeded.  The rest of them go without them.

This seem to be related to the cron job "bin/console mautic:campaigns:trigger", since we can change the --batch-limit parameter to control how many mails are created correctly.

This --batch-limit serves as a workaround for us, but I think this is a bug.

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3
| Browser | N/A

### Steps to reproduce
1. Disable cron jobs.
2. Configure email to embed images in base64.
3. Create an email that references some images.
4. Create a campaign for at least 2 recipients.
5. Execute these jobs manually:
php <mauticdir>/bin/console mautic:segments:update
php <mauticdir>/bin/console mautic:campaigns:rebuild
php <mauticdir>/bin/console mautic:campaigns:trigger --batch-limit=1
6. Go to spool folder and check the different sizes
7. Execute these jobs:
php <mauticdir>/bin/console mautic:messages:send
php <mauticdir>/bin/console mautic:emails:send
8. Check that one of the mails includes images while the other doesn't.

**Comment by RCheesley** [comment]
Thanks for reporting the bug!

**Comment by mboron83** [comment]
This issue also occurs in version v2.16.5. What do you suggest to do?
