### ISSUE TITLE
Bounce is Not Showing In View Contact and Not Adding to Segment

### ISSUE THREAD

**Issue by TnowL** [mautic/mautic#9004]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Bounce contacts do show up in Contact list with the icon. The problem is bounce contacts are not moved to the bounce segment with filter set Bounce - Email > equals > Yes. Also in View Contact, the "Do Not Contact" in red doesn't show.

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3.19
| Browser | Firefox

### Steps to reproduce
1. Bounce setup is correct
2. Checked bounce account and saw new bounce emails and then saw it was read when cron ran.
3. Checked the contact list and saw the Do Not Contact icon for bounce contacts.
4. Checked bounce segment that has filter Bounce - Email > equals > Yes and don't see any contact.
5. Tried sending emails to bounce contacts and no contact pending. So at least I know that emails are not sending to bounce contacts. (that's the good news)
 
### Log errors
No error in log.

**Comment by RCheesley** [comment]
Thanks for taking the time to report the bug - do you happen to have any screenshots showing what you were expecting to see/where things are missing?

**Comment by TnowL** [comment]
![bounce-icon](https://user-images.githubusercontent.com/47170989/87694380-53ad5600-c7b8-11ea-966c-82557f115058.jpg)
The contact emails was bounced. So it's working as normal.

---------------------------------------------------------------------------------

![do-not-contact](https://user-images.githubusercontent.com/47170989/87694639-9f5fff80-c7b8-11ea-801c-75a779f096f2.jpg)
The "Do Not Contact" is missing.

-----------------------------------------------------------------------------------

![expecting](https://user-images.githubusercontent.com/47170989/87695380-a0ddf780-c7b9-11ea-8252-7ae238b722a1.jpg)
Expecting this.

--------------------------------------------------------------------------------------

![bounce-segment](https://user-images.githubusercontent.com/47170989/87694769-cb7b8080-c7b8-11ea-9aa3-6ea51897e412.jpg)
The bounce segment which filter set to Bounce - Email > equals > Yes is still zero. Bounced contacts are not adding to it.

**Comment by RCheesley** [comment]
Can you share what email transport you are using and whether this persists in 3.2.1? We merged a bunch of fixes relating to bounce and DNC in the 3.1->3.2 process so I am hopeful that this has been resolved already!

**Comment by TnowL** [comment]
> 
> 
> Can you share what email transport you are using and whether this persists in 3.2.1? We merged a bunch of fixes relating to bounce and DNC in the 3.1->3.2 process so I am hopeful that this has been resolved already!

I'm currently on v3.2.1 and it seems like it has been resolved. Thank you.

**Comment by ashishajmani** [comment]
Hello

I am facing the same issue. my mautic version is 3.3.1

my email transport is SendGrid and I have added webhook like this

![image](https://user-images.githubusercontent.com/43143416/118261167-d2564b00-b4d0-11eb-9870-81244f5d1609.png)


Am I missing something ?

Thanks
Ashish
