### ISSUE TITLE
Email Settings > GMAIL Serv > ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by quadcom** [mautic/mautic#9007]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Setting mail sending method to GMAIL and connecting to GSuite account results in an error sending even though test connection successful.

Setting Sending Method to 'Other SMTP' and providing GSuite login details works. Based on the error message, I suspect this is due to a possible change to TLS requirements of the sending server that the predefined GMAIL sending method does not have preconfigured. Mainly TLS.

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3.20
| Browser | Chrome 83.0.4103.116

### Steps to reproduce
1. Set sending method to GMAIL
2. Send test email
 
### Log errors
The error returned from GMAIL server 

`Connection could not be established with host smtp.gmail.com :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for reporting this - I know we were tracking the [turning off of 'less secure apps'](https://mautic.atlassian.net/browse/TPROD-52) which necessitates a rewrite of the Gmail integration but that was pushed back by Google indefinitely, so this seems to be something different.

**Comment by incancanada** [comment]
Still Facing this issue 

Connection could not be established with host smtp.gmail.com :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
Any solution for this

Test Connection seems to work but fails on send test email
