### ISSUE TITLE
API "id" field changed from int to string in the /api/contacts operation from v2.16.3 to v3.0.0

### ISSUE THREAD

**Issue by hoylen** [mautic/mautic#9008]
## Bug Description

| Q   | A
| --- | ---
| Mautic version | 3.0.0 and later (e.g. 3.0.1)
| PHP version | 7.3.20
| Browser | N/A

### Steps to reproduce
1. Create a segment with at least one contact in it.
2. Invoke the list-contacts operation on the segment. For example:

    curl --user USERNAME:PASSWORD \\
        'http://HOSTNAME/api/contacts?search=segment%3ASEGMENT&limit=1'

Replacing words in all caps with actual values. Note: "%3A" is a URL-encoded equal sign before the segment name.

### Expected result

Inside the "all" member, the JSON object contains an "id" member whose value is a **JSON integer**.

    "all":{"id":42,

This is what the API produced in Mautic 2.16.3 and earlier.

### Actual result

The JSON object contains an "id" member whose value is a **JSON string**.

    "all":{"id":"42",

This is syntactically and semantically different JSON, which causes clients in type-safe languages to fail.

### Related issues

This issue is similar to the "id" inconsistently switching between string and long, as reported in <https://github.com/mautic/mautic/issues/8031>.

It is related to the "total" being returned as a string instead of as an integer, as reported in <https://github.com/mautic/mautic/issues/7319>.

This is a new issue, since it is about an unexpected breaking change to the API between different versions of Mautic. Whereas those other issues are about undesired behaviour in the same version of Mautic. Ideally, they should all be addressed by representing the "id" and other numeric values consistently as a JSON integer.

**Comment by RCheesley** [comment]
@hoylen thanks for taking the time to report this issue!

**Comment by hoylen** [comment]
A fix in the 3.0.2 milestone would be great: before clients start expecting the string as the "new normal".

Hope it can address the other string vs int issues at the same time, since addressing them is technically a "breaking change" to the API... and a major version jump to 3.x.x would have been an ideal time for breaking changes. But it is questionable whether 3.0.1 to 3.0.2 should have any breaking changes. For those other changes, maybe it could be argued that it was intended to be a breaking change for 3.0.0, but it was a bug it didn't happen, so 3.0.2 fixes that "bug"!

Either way, there is going to be some pain for type-safe clients...unless they somehow managed to skip 3.0.0 and 3.01 and jump straight to 3.0.2.

**Comment by RCheesley** [comment]
There will not be breaking changes until 4.0 but we can get bug fixes addressed and put out information about the fixes. If you're able, please do consider looking into making a PR if you can fix the problem, we only have this week to get PR's finalised for 3.0.2 so we are somewhat up against the clock!

**Comment by hoylen** [comment]
Sorry, I'm not familiar with the Mautic codebase, so I can't help with a PR for this.

**Comment by hoylen** [comment]
This is still an issue in Mautic 3.2.2.
