### ISSUE TITLE
Mautic 3.0.1 doesn't send campaigns "None of possible cryptography libraries is supported" Error

### ISSUE THREAD

**Issue by joshk19** [mautic/mautic#9010]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.2.31
| Browser | Chrome

### Steps to reproduce
1. Create a new template Email 
2. Create a new campaign
3. Contact source a segment
4. Select new action send email created before
5. Apply, Save
6. Run the commands line  **mautic:campaigns:update** (wait it finish)
7. Run the command line  **mautic:campaigns:trigger**
 
### Log errors
[2020-07-13 23:57:34] mautic.ERROR: CAMPAIGN: None of possible cryptography libraries is supported [] []

When run the **mautic:campaigns:trigger** command to trigger the campaigns the log is sended. 
I already checked if is there an answer for this issue, but I didn't find anything similar.

I don't know if I missing some step before create and send a new email campaign.

For send the emails I'm using sendgird. 
When send the email  Send Example in the email menu it works. 
But when I create and trigger a campaign it breaks.
Im trying to send to 3 emails for test.
NOTE: Im using xampp in Windows 10.

### Comand line error
In the command line shows this when run **mautic:campaigns:trigger**

**[WARNING] Some commands could not be registered:**
_In EncryptionHelper.php line 43:_
**None of possible cryptography libraries is supported**

Triggering events for campaign 2
Triggering events for newly added contacts
3 total event(s) to be processed in batches of 100 contacts
3/3 [===============] 100%

Thanks for any help.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, I don't think that this is a bug with Mautic, it sounds like you maybe don't have your xampp environment configured correctly.  I believe that this error relates to OpenSSL not being available having found the error message above in a PR which introduced it, could you take a look at https://stackoverflow.com/questions/9466086/enabling-the-openssl-in-xampp#11040496 and see if this might help? Remember to restart your services after making changes.

**Comment by joshk19** [comment]
Hi, @RCheesley , you were right!! :D, I enabled the OpenSSL in my php.ini and this error not appear anymore.

Thank you so much for the help.

**Comment by RCheesley** [comment]
No probs! Glad you got it sorted :)

**Comment by pavel-janicek** [comment]
I had similar issue, but allowing OpenSSL did not help me. What helped me, was to update OpenSSL library on my server. full article here:
https://support.stripe.com/questions/upgrade-openssl-to-support-tls-1-2

Most important commands to run on Ubuntu:

```
sudo apt-get update && sudo apt-get install --only-upgrade openssl
sudo apt-get update && sudo apt-get install --only-upgrade libssl-dev
sudo service apache2 restart
```
