### ISSUE TITLE
Mautic doesn’t track anything

### ISSUE THREAD

**Issue by annakuprina** [mautic/mautic#9013]
Hello
I deployed the version 2.16.2 mautic to https://phpstack-405060-1323590.cloudwaysapps.com/ everything works correctly,
the error log does not contain errors - http://joxi.ru/DrlznyRt0LOYZ2
For tracking data, I posted the script http://joxi.ru/1A5Z4wvCGVyoZr on another site
The script on the site is running http://joxi.net/52an4KEibMNYBA, requests go the mautic and look successfully http://joxi.net/p27RkwvHWG9bkm
But the mautic doesn’t track anything, I don’t see information about the pages viewed or about the users
All reports are empty - http://joxi.ru/823LZwEHDPlnRA

Server Use PHP 7.2

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
