### ISSUE TITLE
symfony cache exception with Mautic API in 3.0.1

### ISSUE THREAD

**Issue by brafreider** [mautic/mautic#9014]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
After Upgrading to Mautic 3.0.1 I am getting an error 500 when I try to access the Mautic API with oAuth2 from integromat.com (a zapier-like service).
It looks like this is also happening with Mautic WooCommerce Integration (https://wordpress.org/plugins/enhanced-woocommerce-mautic-integration/#description)
``` 
mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\InvalidArgumentException: "Cache key "*.api.YTg.[.....]wNg.https://[XX OUR MAUTIC DOMAIN XX]" contains reserved characters {}()/\@:." at /var/www/clients/client414/web1810/web/vendor/symfony/cache/CacheItem.php line 168 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\InvalidArgumentException(code: 0): Cache key \"*.api.YTg0Nm[....]YzcwNg.https://[XX OUR MAUTIC DOMAIN XX]\" contains reserved characters {}()/\\@:. at /var/www/clients/client1/web1/web/vendor/symfony/cache/CacheItem.php:168)"} []
``` 
The Authentication and token refresh seem to be working fine. The error happens with authenticated API calls.

The error looks like a cache key naming issue in Mautic. Probably it's the URI "https://mautic.domain.com" that contains reserved characters ".", "/" and  ":". In the Mautic API-UI, name and redirect URL do not contain the domain that appears in the error message.

Has anyone seen this problem before, or is there a way to get the API with oAuth2 working? again?
| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.2.32
| Browser | oAuth2 server2server

Thanks, Björn

**Comment by brafreider** [comment]
this also happens with basic authenticaition;
```
curl -i -X GET -H "Authorization:Basic [HASH]" 'https://mautic.domain.com/api/contacts'
```
results in 
```
[2020-07-16 16:08:52] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Cache\Exception\InvalidArgumentException: "Cache key "*.api.https://mautic.domain.com" contains reserved characters {}()/\@:." at /var/www/clients/client1/web1/web/vendor/symfony/cache/CacheItem.php line 168 {"exception":"[object] (Symfony\\Component\\Cache\\Exception\\InvalidArgumentException(code: 0): Cache key \"*.api.https://mautic.domain.com\" contains reserved characters {}()/\\@:. at /var/www/clients/client1/web1/web/vendor/symfony/cache/CacheItem.php:168)"} []
```

**Comment by RCheesley** [comment]
Thanks for reporting the issue.

I did a bit of digging and found: https://github.com/symfony/symfony/pull/29313 but that was merged in an earlier version of Symfony than we are using, so that shouldn't be the issue.

Will need to do a bit more digging!

**Comment by brafreider** [comment]
Hi Ruth, thanks for investigating. Do you have an updated system on 3.0.1 where the API is working like expected?
in our system, the getReadAccessInfo function does not mask the same chars like it does in the merge request you linked:
```
private function getReadAccessInfo($class, $property)
    {
        $key = str_replace('\\', '.', $class).'..'.$property;

        if (isset($this->readPropertyCache[$key])) {
            return $this->readPropertyCache[$key];
        }

        if ($this->cacheItemPool) {
```
I already tried to figure out the symfony version on our system, but I didn't find a hint within the code.

Cheers,
Björn

**Comment by brafreider** [comment]
Hi @RCheesley 
I just updated to 3.0.2 and the problem persists. Is that something special to our system? Is the API working as expected on other systems?
Cheers,
Björn

**Comment by devintegromat** [comment]
Hello everybody,

have you found a solution? We have customers who are facing with this issue and we are trying to solve it. 

Thanks

**Comment by brafreider** [comment]
no, still waiting for someone with an upgraded system and working api, to know if it's a general Mautic error or something specific to our system. We have put the upgrade for two more systems on hold until there is a solution. You are talking about customers - this means multiple - how many with this problem?
Cheers,
Björn

**Comment by brafreider** [comment]
finally I had the time to deep dive into it. 
This problem happen as soon as api_rate_limiter_limit in app/config/local.php is set to a value other than 0.
It seems like there is no way to change this within the UI - however, my updated system was set to 1200, the fresh install was set to 0.
Changing this in local.php and purging the cache afterwards solved the issue for me.

Nevertheless, I think it is a Mautic bug, otherwise the api_rate_limiter could be removed.

Cheers,
Björn

**Comment by RCheesley** [comment]
Hi there,

Please take a look at the Mautic 3 upgrade info - have you updated your configuration as below?  Not sure if this applies to your situation but crossed my mind!

https://github.com/mautic/mautic/blob/staging/UPGRADE-3.0.md#configuration

Specifically:

> Note on the api_rate_limiter_cache parameter: this is an advanced feature that we only expect a very small subset of users to be using currently.
> 
> If you had a custom API rate limiter other than the filesystem (default), you'll need to specify a Symfony cache adapter as of Mautic 3. The upgrade script will change it to 'cache.adapter.filesystem' to prevent issues in the upgrade process, so you should change it yourself post-upgrade. For example, if you had Memcached set up with the following configuration:
> 
> 'api_rate_limiter_cache' => array(
>   'memcached' => array(
>     'servers' => array(
>       '0' => array(
>         'host' => 'memcached.local',
>           'port' => '12345'
>       )
>     )
>   )
> ),
> ... it should now be:
> 
> 'api_rate_limiter_cache' => array(
>   'adapter' => 'cache.adapter.memcached',
>   'provider' => 'memcached://memcached.local:12345'
> ),

**Comment by brafreider** [comment]
not sure, if I have seen this document before updating. I just checked the history of our local.php
we have installed this system about a year ago, the initial value (Mautic 2) looked like this:
```
'api_rate_limiter_limit' => 0,
'api_rate_limiter_cache' =>  array(
    'type' => 'file_system'
),
```
in February it changed, I can't remember why, manual or update or configuration change, but the API still worked:
```
'api_rate_limiter_limit' => 1200,
'api_rate_limiter_cache' =>  array(
    'type' => 'file_system'
),
```
when we updated to 3.0.1, it changed almost like described in the document you mention and the API stopped working:
```
'api_rate_limiter_limit' => 1200,
'api_rate_limiter_cache' =>  
array(
    'adapter' => 'cache.adapter.filesystem',
),
```
due to the document the limit should have been changed to 0. The fact, that it does not work with a value of 1200 could mean, that, for the people who want to use it, the rate limiter will not work at all, or at least not in conjunction with the filesystem adapter. My guess is, that it won't work at all, as the error message does not come from the filesystem adapter, but from a generic cache function.
But for my system the issue is solved, as our API works again, so it's on you, if you want to close the issue :-)
Cheers,
Björn

**Comment by brafreider** [comment]
in 2.16.2, there is a configuration for api_rate_limiter_limit option under api settings

**Comment by kuzmany** [comment]
This should fixed it https://github.com/mautic/mautic/pull/9237 . Please try, and write comment in that PR If works. It help merge it in next version

**Comment by RCheesley** [comment]
Thanks for the fix @kuzmany I've just linked the PR to this issue so it will be auto-closed when we merge the fix.
