### ISSUE TITLE
Froala bug: HTML <a> tag with special char in the title attribute broke HTML

### ISSUE THREAD

**Issue by trianity** [mautic/mautic#9015]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3.19
| Browser | Google Chrome latest

### Steps to reproduce
1. Use Email Builder in code mode
2. Add a HTML <a> tag with characters like öüőúéáí or ÖÜÓŐÚÁŰÍ in title tag
3. Save the email with button Apply
4. After ajax request the refreshed screen will show the broken HTML
 
### Log errors
No

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

Important notes: This issue was not appeared in the Mautic 2.16.x version. The screen shots were taken from a production Mauitc instance that sent out HTML formatted emails more the 600 pcs using Mautic 2.15.x, 2.16.x without any problem.

The screen shots show the issue:

1.) Well formatted email with proper HTML code:

![2020-07-16_20-48-22](https://user-images.githubusercontent.com/6353141/87713113-fd391b00-c7a9-11ea-9ae7-65f8126fb221.png)

2.) The images are in place
 
![2020-07-16_20-51-17](https://user-images.githubusercontent.com/6353141/87713145-0924dd00-c7aa-11ea-83e5-a9ba79b4fb3a.png)

3.) After clicking the Apply button (save) some of the <a> tag and all HTML will be broken

![2020-07-16_20-55-59](https://user-images.githubusercontent.com/6353141/87713172-104beb00-c7aa-11ea-8eea-dbcb04181144.png)

Because not all <a> tag was broken I started investigate what is the difference between not broken and broken HTML <a> tags. The only difference was the title attribute. If you will use typical Hungarian letters like öüőúéáí or ÖÜÓŐÚÁŰÍ in the title, the issue will be shown.

Changing the title text of these <a> tags (e.g remove special chars) the email will be saved as normal.

The issue may related with https://github.com/mautic/mautic/issues/8627 and with 
https://github.com/mautic/mautic/pull/8345 and with
https://github.com/mautic/mautic/issues/3966

**Comment by RCheesley** [comment]
Thanks for reporting this - I think it is likely the same as the other issue #8627 so let's have the discussion over there!
