### ISSUE TITLE
Role Campaign Permissions allows view on all calendar

### ISSUE THREAD

**Issue by ShareBtech** [mautic/mautic#9022]
[//]: # (READ THIS BEFORE PUBLISHING YOUR ISSUE)
[//]: # (Please post questions, support requests and feature requests/ideas at https://forum.mautic.org.)
[//]: # (Strictly follow the instructions hereunder, otherwise your issue will be closed for lack of information.)
[//]: # (DO NOT report security vulnerabilities here. Send them to security@mautic.com.)
[//]: # (MAUTIC 2 is not supported any more except for security matters, report your issue only if it relates to the Mautic 3 series.)

Detail your bug report:
When assigning a Role permission to see their calendar, they are able to see all campaigns and other calendars as well

| Q  | A
| ---| ---
| Confirm it is a Bug report | Confirmed
| Mautic version | 3. Mautibot - Latest Version
| PHP version | 7.2

[//]: # (Feature request? ---> Go to forum please ---> https://forum.mautic.org/c/ideas)
[//]: # (Enhancement? ---> Go to forum please ---> https://forum.mautic.org/c/ideas)
[//]: # (Need support, have questions? ---> Go to forum please ---> https://forum.mautic.org/c/support)

## Description:
In order to provide access to a Role to view events in calendar, when choosing View Own, they are able to see all calendar events (both campaigns and others notes/events)

### Steps to reproduce:
1. Create Role
2. Create User
3. Assign View Own permissions in Campaign
 
### Log errors: 
none

**Comment by websmartit** [comment]
Hi


I can confirm this is still an issue with the latest stable version of mastic 3.0.2

**Comment by RCheesley** [comment]
Thanks folks, if someone can double check this on the latest release so that we can confirm it's persisting we can hopefully get someone to look into it!

**Comment by pjrobertson** [comment]
This is still an issue with Mautic 4.2.0.

If I set a user as only having 'View Own' permissions for campaigns, all campaigns, including those from other users are also viewable from the 'Calendar' (see attached image). If the user tries to click one of the calendar events, they get the message:

> Tsk tsk. Apparently you don't have access to this area.
 
![Screenshot 2022-03-09 at 11 29 37](https://user-images.githubusercontent.com/150431/157367343-3e0f9bb5-e146-4b95-9204-f9de6a37fe44.png)

**Comment by RCheesley** [comment]
Thanks for following up @pjrobertson :)

**Comment by pjrobertson** [comment]
No worries! I also created a new issue #10944. I wasn't sure of the right protocol, but if this can be re-opened, then that's best. I will close #10944 :)

**Comment by RCheesley** [comment]
Yeah we usually say to open a new issue if it's been closed for ages but we'll leave this one for now! If you are able to have a look into addressing it just shout and we can help you get started!

**Comment by pjrobertson** [comment]
This is still an issue.

**Comment by RCheesley** [comment]
Thanks for flagging this up @pjrobertson - we are aware of some issues with the permissions which we are working on. It's worth bearing in mind that the calendar is being removed in Mautic 5.0 (see #11270) so it will not be an issue at that point.

**Comment by pjrobertson** [comment]
Appreciate the update Ruth! Looking forward to seeing v5.0 roll out the
door. Good luck!

On Tuesday, 16 August 2022, Ruth Cheesley ***@***.***> wrote:
> Thanks for flagging this up @pjrobertson - we are aware of some issues
with the permissions which we are working on. It's worth bearing in mind
that the calendar is being removed in Mautic 5.0 (see #11270) so it will
not be an issue at that point.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci6.googleusercontent.com/proxy/kDjjAqO6wimfywgsa3plJu_tpbkrHUKq0gbCWJ6qN8EawHNCpQ5N1NoYbY0h0GMJfBxDJ8wibnywaeLZqsjYsP-x5MNs5ooSYm1sCGTh2BODKp5CEz7UhL_q9oy0EGlBJQY9cq9GJzoWSNc6X0X8sSrvUKAj92IVMKKnCW4TctF_U_cs8awaw-FVLF0cQ3ms10cmzRE9ziOx2WEkQnqs0xr4DyIy_5-oGVe0kOjwFw=s0-d-e1-ft#https://github.com/notifications/beacon/AABEXH3PFPX53LO7L4G2RADVZNWRJA5CNFSM4PCVF4WKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOJCA5XNY.gif>Message
ID: ***@***.***>

**Comment by pjrobertson** [comment]
This is still am issue, hopefully v5.0 will be rolled out soon!
