### ISSUE TITLE
Validate email campaign action does not validate against MX records

### ISSUE THREAD

**Issue by OmerGafny** [mautic/mautic#9023]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This is related to #7904 
While the action sucessfully validates empty email or malformed addresses like 1111@1111.111, it does not check the email against MX recrods as it should. Non-existent email address like dfgdfgdgf@dfgdfglkdlgkdfglk.com will still considered valid email.

| Q   | A
| --- | ---
| Mautic version | 2.16.2
| PHP version | .7.2XXX
| Browser | All of them

### Steps to reproduce
1. Add a non existent email like dfgdfgdgf@dfgdfglkdlgkdfglk.com to your contacts
2. Create a segment for this email
3. Create a campaign with the segment and add a Check Valid Email action. Add tag "email not valid" on the negative route of the action. The tag wont be added to the contact, because his email will be valid according to the action
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
Thanks!

**Comment by RCheesley** [comment]
See also a previous issue: https://github.com/mautic/mautic/issues/7904#issuecomment-588141026

**Comment by OmerGafny** [comment]
> Hi there, as we are only providing fixes for Mautic 3.x going forward, can you confirm if this continues in Mautic 3.0.1?
> Thanks!

Sorry, for now i cant confirm if its going on 3.0.1

**Comment by OmerGafny** [comment]
Hi @RCheesley, 

I have just tested this in the base branch of https://m3.mautibox.com/ , and i can confirm this issue still persists in 3.0.1

**Comment by RCheesley** [comment]
@OmerGafny thanks so much for testing on Mautic 3, I've added the appropriate labels :)

**Comment by evgu** [comment]
@OmerGafny pls check 3.1.1 release, should have this fixed. Pls close this issue if resolved. 
This is the PR and code that fixes the issue. https://github.com/mautic/mautic/pull/9215 / https://github.com/mautic/mautic/commit/2e72b71b608910e4f8db14b32ac414703ff0f509
