### ISSUE TITLE
Asset upload not completing

### ISSUE THREAD

**Issue by nford** [mautic/mautic#9030]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3.19
| Browser | Safari, Chrome, Firefox

### Steps to reproduce
1. Drag and drop pdf file to dropzone on /s/assets/new
 
### Log errors

None as there is no error shown in PHP or JavaScript. There is an Apache log showing success:

10.1.0.51 - - [23/Jul/2020:17:28:21 +0000] "POST /mautic/s/_uploader/asset/upload HTTP/1.1" 200 45 "-" "Amazon CloudFront"

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

The upload appears to work as the response is 200 from Apache and a file is created in media/files/tmp but the interface shows an error with an empty error message.

Size of the file uploaded is 12kb

![Screen Shot 2020-07-23 at 1 11 06 PM (2)](https://user-images.githubusercontent.com/19161/88319685-7f659a00-ccea-11ea-920c-5fe6227d7006.png)

**Comment by RCheesley** [comment]
Hi there, looks like you need to increase the maximum filesize in your Mautic config - as this is not a bug with Mautic I am going to close this issue, please post on https://forum.mautic.org/c/support if you need further help with this.

**Comment by nford** [comment]
@RCheesley as pointed out in the ticket the file size was 12kb

**Comment by nford** [comment]
> Hi there, looks like you need to increase the maximum filesize in your Mautic config - as this is not a bug with Mautic I am going to close this issue, please post on https://forum.mautic.org/c/support if you need further help with this.

The file was only 12 kilobytes and this was mentioned in the bug report! Secondly, as mentioned in the bug report the files are uploading and being placed into subdirectories of media/files/tmp

**Comment by RCheesley** [comment]
Oooh sorry, I totally missed that part! Re-opened the issue!

**Comment by RCheesley** [comment]
Can you give more details on your server setup/config/hosting as I am not able to replicate this in the same version of Mautic so I do not think that this is a bug with Mautic itself.

Are you able to upload images in the builders (email/landing page) or are they also affected?

**Comment by nford** [comment]
Hi Ruth, I'm using a self-installed Mautic installation on Amazon Linux 2 with CloudFront. In light of your update I did some additional troubleshooting and it looks like the issue is that the dropzonejs uploader requires the 'Accept' header to be whitelisted in CloudFront. Thanks, I'll close this.
