### ISSUE TITLE
Email links not tracked 3.0.1

### ISSUE THREAD

**Issue by Rid** [mautic/mautic#9031]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Link tracking is not incrementing the "Click Counts" table in the email view. I am not using test emails, only emails directly from a form action (the URLs are being replaced correctly). I have also tried sending emails from a campaign and have the same issue. I have tried using incognito mode and using curl with no cookies. I have checked https://docs.mautic.org/en/channels/emails/troubleshooting-emails and cannot find any issues with my setup.

I have an nginx reverse proxy setup with the following proxy headers:

```
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
```

I have the following in my apache config:

```
RemoteIPHeader X-Forwarded-For
RemoteIPInternalProxy 172.20.0.0/12
```

apache is picking up the correct IP from the proxy and the URLs are being replaced with the tracking links (x.x.x.x) is my external IP:

```
x.x.x.x - - [23/Jul/2020:21:45:39 +0000] "GET /r/e09889a06755a4a341a116ab5?ct=YTo0OntzOjY6InNvdXJjZSI7YTowOnt9czo1OiJlbWFpbCI7TjtzOjQ6InN0YXQiO047czo0OiJsZWFkIjtzOjI6IjY2Ijt9 HTTP/1.1" 302 962 "-" "curl/7.54.0"
```

The response is the following:

```
*   Trying x.x.x.x...
* TCP_NODELAY set
* Connected to mautic.appbox.co (x.x.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=mautic.example.com
*  start date: Jul 20 13:10:33 2020 GMT
*  expire date: Oct 18 13:10:33 2020 GMT
*  subjectAltName: host "mautic.example.com" matched cert's "mautic.example.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fc3ff000000)
> GET /r/e09889a06755a4a341a116ab5?ct=YTo0OntzOjY6InNvdXJjZSI7YTowOnt9czo1OiJlbWFpbCI7TjtzOjQ6InN0YXQiO047czo0OiJsZWFkIjtzOjI6IjY2Ijt9 HTTP/2
> Host: mautic.example.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 302
< server: nginx/1.19.0
< date: Thu, 23 Jul 2020 21:45:39 GMT
< content-type: text/html; charset=UTF-8
< x-powered-by: PHP/7.3.20-1+ubuntu18.04.1+deb.sury.org+1
< cache-control: no-cache, private
< set-cookie: mautic_device_id=usr3850cw25vmf91tg7tthl; expires=Fri, 23-Jul-2021 21:45:39 GMT; Max-Age=31536000; path=/
< set-cookie: mtc_id=74; path=/
< set-cookie: mtc_sid=usr3850cw25vmf91tg7tthl; path=/
< set-cookie: mautic_referer_id=71; expires=Thu, 23-Jul-2020 22:15:39 GMT; Max-Age=1800; path=/
< location: https://www.example.com
< strict-transport-security: max-age=63072000
<
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='https://www.example.com'" />

        <title>Redirecting to https://www.example.com</title>
    </head>
    <body>
        Redirecting to <a href="https://www.example.com">https://www.example.com</a>.
    </body>
* Connection #0 to host mautic.example.com left intact
</html>
```

Everything seems to be setup properly, but no links are being tracked.

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3.20-1+ubuntu18.04.1+deb.sury.org+1
| Browser | Chrome / Firefox / Curl

### Steps to reproduce
1. Send an email with links (not test)
2. Click a link
 
### Log errors
No errors in the logs (even with debug => true).

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for raising this, are you seeing the clicks hitting the database in the email stats table? If so, do you see the info in a report? (Just wondering if it is an issue with the email stat view).

Also not sure if #8928 might be related?

**Comment by Rid** [comment]
@RCheesley thanks for the reply.

The clicks are not hitting the DB. I've had a look at https://github.com/mautic/mautic/issues/8928 but it does not apply, I have tried clicking all links in the email and none of them are registered.

**Comment by Rid** [comment]
After further inspection, link clicking does work. However I found a bug/feature which is possibly unexpected.

I have a form which I want to sent an email from immediately after it's submitted, if I have the form send an email via a campaign (even if it's set to immediately send), it has to wait for the cron to send the email which is up to a minute later.

The email contains a coupon so the user may get bored of waiting and forget about the email when checking their inbox for more than 30 seconds.

I then decided to use the form action of "Send form results" which does send an email immediately to the user signing up via the form, however the email opens and clicks are not tracked when using this method. Is that an expected result or a bug?

If it's expected, does this mean there's really no way of immediately sending an email generated via a form and tracking the results?

**Comment by alfmos** [comment]
> After further inspection, link clicking does work. However I found a bug/feature which is possibly unexpected.
> 
Could you please elaborate? I have the same problem and I'm not able to understand what's happening

**Comment by afzaal-ameer** [comment]
I just setup v3 and seeing the same problem. The trackable link is generated, and clicking it redirects correctly but the counter does not increment.

I am using `/api/emails/[id]/contact/[id]/send` endpoint to send emails.

**Comment by ItDoBeNord** [comment]
I'm having this issue too, I create an email template with 3 links and send it out via a campaign to test clicking the links. I clicked all three but Mautic registers no clicks
