### ISSUE TITLE
Mautic cross-site cookies blocked by Chrome

### ISSUE THREAD

**Issue by spka** [mautic/mautic#9032]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Chrome 84 blocks cookies without samesite=none and secure parameters when loaded from a different domain. The file mtc.js doesn't yet set cookies (mtc_id, mtc_sid, mautic_device_id) with these properties.

| Q   | A
| --- | ---
| Mautic version | 2.16
| PHP version | 7.3
| Browser | Chrome 84

### Steps to reproduce
1. Host mautic on a different domain then the tracked domain.
2. Open the tracked domain in chrome.
 
### Log errors
A cookie associated with a cross-site resource was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

### Solution
CookieHelper.php already supports the parameters but DeviceTrackingService.php function createTrackingCookies (line 190) doesn't yet set them.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, thanks for reporting this issue. It is already being tracked in #9019 so I am going to close this issue as a duplicate.
