### ISSUE TITLE
Blank screen when opening email builder

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#9033]
At the moment, on a fresh installation of Mautic 3, when I go into the Email Builder after I've selected and applied a template, this is all I see:

![mauticBuilder](https://user-images.githubusercontent.com/262545/88403121-fde23a80-cdc3-11ea-9c63-e820e51c592e.png)

There are no errors in the PHP logs that I can find, nor are there any errors in the browser console.  I'm wondering if the new builder might solve this, and if there's a chance it will then should I follow the exisiting instructions which appear to be for Mautic 2

_Originally posted by @proffalken in https://github.com/mautic/mautic/issues/7360#issuecomment-663573376_

**Comment by proffalken** [comment]
Some more details:

Webserver: NGinx
PHP Version: PHP-FPM 7.2
PHP Source: Remi's RPM Repo
OS: CentOS 7
DB: MySQL 8

Browser: Firefox

**Comment by RCheesley** [comment]
This sometimes can occur if you click through to the builder too fast after selecting the template - does it happen with every template?

**Comment by proffalken** [comment]
Yup, although the "code mode" works as expected:

![CodeModeInitial](https://user-images.githubusercontent.com/262545/88404381-ba88cb80-cdc5-11ea-9402-0801164d0423.png)
![CodeModeTestText](https://user-images.githubusercontent.com/262545/88404384-ba88cb80-cdc5-11ea-9369-eb18a322b0b3.png)

**Comment by proffalken** [comment]
I've just checked and I get the same result in Chromium as well as Firefox.

**Comment by proffalken** [comment]
I removed the web-root, downloaded a fresh version of 3.0.2 from the Mautic website, re-installed, and this now works.

@RCheesley - not sure if you want to mark this down as an anomaly or not?


(I hate that download form btw, just let me download the software without having to give you my personal details every time please! :) 

I know this is a marketing tool, but seriously, I should be able to download it without registering, especially as it's Open Source! </rant>)

**Comment by jantonk** [comment]
@RCheesley  It seems we've the same issue here...  When i go to the Email template page i see in chrome console some 500 errors:

```
https://mautic.domain.com/s/emails/new
libraries.js?v271294bf:766 GET https://mautic.domain.com/s/emails/builder/new_31bd13304cf31ddde63cc841019ddfeb8229d676?template=blank&_=1597133827051&mauticUserLastActive=8&mauticLastNotificationId= 500
send @ libraries.js?v271294bf:766
ajax @ libraries.js?v271294bf:744
jQuery.<computed> @ libraries.js?v271294bf:756
Mautic.setThemeHtml @ app.js?v271294bf:171
Mautic.initSelectTheme @ app.js?v271294bf:168
Mautic.emailOnLoad @ app.js?v271294bf:501
Mautic.onPageLoad @ app.js?v271294bf:85
Mautic.processPageContent @ app.js?v271294bf:64
success @ app.js?v271294bf:43
fire @ libraries.js?v271294bf:344
fireWith @ libraries.js?v271294bf:350
done @ libraries.js?v271294bf:752
(anonymous) @ libraries.js?v271294bf:765
load (async)
send @ libraries.js?v271294bf:765
ajax @ libraries.js?v271294bf:744
Mautic.loadContent @ app.js?v271294bf:40
Mautic.ajaxifyLink @ app.js?v271294bf:103
(anonymous) @ app.js?v271294bf:88
dispatch @ libraries.js?v271294bf:465
elemData.handle @ libraries.js?v271294bf:451



libraries.js?v271294bf:766 GET https://mautic.domain.com/s/emails/builder/4?template=vibrant&_=1597134303240&mauticUserLastActive=5&mauticLastNotificationId= 500
send @ libraries.js?v271294bf:766
ajax @ libraries.js?v271294bf:744
jQuery.<computed> @ libraries.js?v271294bf:756
Mautic.setThemeHtml @ app.js?v271294bf:171
(anonymous) @ app.js?v271294bf:170
dispatch @ libraries.js?v271294bf:465
elemData.handle @ libraries.js?v271294bf:451
```

**Comment by RCheesley** [comment]
> @RCheesley It seems we've the same issue here... When i go to the Email template page i see in chrome console some 500 errors:

Does this happen if you allow the page to fully load, select the template, wait a few seconds until it is definitely selected? Just trying to rule out opening the builder before a template has been selected.

Which template are you trying to use?

**Comment by jantonk** [comment]
Yes page get fully loaded. However the problem already start on the theme page where i see the 500 error in the console from my previous comment.

All templates have this issue, except the code mode as mentioned by @proffalken

**Comment by RCheesley** [comment]
OK thanks for the clarification!  Seems strange that it went away entirely with the new instance as @proffalken mentioned - @jantonk can you share your server config? It might help us to get to the bottom of this.

**Comment by henderbj** [comment]
I work with jantonk and on our system the problem was lack of write permissions on /path/to/mautic/var.
By checking logs in ./var/logs we noted:
[2020-08-11 18:39:38] mautic.ERROR: [MAIL ERROR] Unable to create a file for enqueuing Message in "/path/to/mautic/app/../var/spool". (send); mymail@gmail.com {"exception":"[object] (Swift_IoException(code: 0): Unable to create a file for enqueuing Message in \"/path/to/mautic/app/../var/spool\". at /path/to/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/FileSpool.php:111)"} []

It was fixed with:
chown -R www-user:www-user /path/to/mautic/var.

After this, this issue was solved for us.

**Comment by henderbj** [comment]
Also, if you have problems after changing theme, you need to create a new email instead of modify a previous one, as shown in the warning, and image below.

![mautic-warning-theme](https://user-images.githubusercontent.com/7970531/89938705-2d43d480-dc17-11ea-8c86-7a580eb3efb0.png)

**Comment by RCheesley** [comment]
@proffalken could this be the case for you?

**Comment by RCheesley** [comment]
@henderbj @jantonk thanks for taking the time to get back to us with what you found out by the way, it is really appreciated!

**Comment by proffalken** [comment]
@RCheesley apologies, I missed this!

I think my issue was that I'd installed from Git, not from the download package file.  Not sure why that would make a difference, but I switched to the package file from the download form and all of the issues I was seeing went away.

Not very helpful bug resolution reports go, I know, but don't really have anything else that will help, sorry :(

**Comment by RCheesley** [comment]
OK, let's close it for now and if it recurs we can re-open!

**Comment by ayushgangrade11** [comment]
This issue is happening to me and affecting the goal in which I was planning to use Mautic.
Please fix this soon.

I have recently installed v3.1 Using bitnami on gcp

**Comment by trancemanone** [comment]
same issue here 

v 3.1 ubuntu 18.04

**Comment by kale1d0code** [comment]
I have upgraded to v4.1.1 in docker.
the only theme that works is the code mode as long as I am not trying to use the grapesjs plugin
email template editing does not work at all if I try to use the grapesjs plugin

I get 500 error message for a request to https://SITE_URL/s/grapesjsbuilder/email/1?template=confirmme&_=1643111811729&mauticUserLastActive=4&mauticLastNotificationId=

and when changing the theme to different themes I get the message
```
setThemeHtml - Request failed: error | builder.js:65
```
```
content.service.js:119 Uncaught Error: No valid HTML template found
    at Function.getOriginalContentHtml (content.service.js:119:13)
```

**Comment by peter-palmer** [comment]
same issue here, there is no resolution???

**Comment by peter-palmer** [comment]
I'm getting this error in the console...
![image](https://user-images.githubusercontent.com/58218056/162693946-4ac664b3-b1f6-4b6f-bc6a-2747769b9812.png)

**Comment by peter-palmer** [comment]
# Solution!

**So finally, I have solved the issue!!**

I have followed these steps to solve it:

1. Back up (download) all Mautic files from your server to your local computer, using File Transfer Protocol (FTP) or the [scp command](http://manpages.ubuntu.com/manpages/precise/en/man1/scp.1.html) which is much faster.
2. Delete all Mautic files and folders on your server. Use FTP or the [rm command](http://manpages.ubuntu.com/manpages/precise/en/man1/rm.1.html) (use the latter with extreme caution).
3. Download the latest Mautic package from https://www.mautic.org/download.
4. Upload the zip package to the server, to the Mautic folder, using FTP or the [scp command](http://manpages.ubuntu.com/manpages/precise/en/man1/scp.1.html) which is much faster.
5. Unzip the package with unzip 3.3.3.zip -change the filename to match the one you have uploaded. You can then remove the zip file using the command rm 3.3.3.zip.
6. Upload app/config/local.php from your backup on your local machine to the fresh Mautic folder on the server - Mautic should now run.
7. Upload your custom data if you have some. Custom files may be found in the following folders: media/files; plugins; themes; translations.
