### ISSUE TITLE
Issue when importing contact information in Mautic 3.0.0

### ISSUE THREAD

**Issue by Mohamed1308** [mautic/mautic#9034]
Hello!

I am currently using Mautic 3.0.0 with PHP 7.3.20.

I tried importing a CSV file from my local computer to Mautic. I uploaded the file and I chose **,** as a delimiter, **"** as an enclosure, \ as an escape and **100** as a limit (the default import settings). I was then redirected to the next step without any issues and because the file’s header column matches Mautic’s custom fields’ aliases, I just clicked on “Import”. I was then redirected to Mautic’s import history page and the import’s status was “Queued”.

The problem is that even after several hours, the progress is still 0% (0 rows inserted, updated or ignored). I thought that the reason was the slow connection or the file’s volume, but trying to import a much smaller file gave the same result.

Please find attached a PDF version of the small CSV file.

[contacts_csv.pdf](https://github.com/mautic/mautic/files/4976272/contacts_csv.pdf)

**Comment by RCheesley** [comment]
Hi there, if you used background import, did you run the [cron job](https://docs.mautic.org/en/contacts/import-contacts#background-import)?

In the future, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by Mohamed1308** [comment]
Hello @RCheesley and thank you for your reply
I used the GUI to import the contacts, so I suppose that I didn't run the cron job

I have already posted this issue in Mautic Community Forums and I am sorry that I posted it also here ( I thought that GitHub is used to get support too :-) )

**Comment by RCheesley** [comment]
Ok let's dealt with this in the forums as that's the correct place :)

**Comment by Mohamed1308** [comment]
Ok! Here is the link: https://forum.mautic.org/t/issue-when-importing-contact-information-in-mautic-3-0-0/15386/3

I think that I have already found where the problem comes from.
Anyway, thank you for your help!
