### ISSUE TITLE
Rename Asset attachments name

### ISSUE THREAD

**Issue by sourabhlk** [mautic/mautic#9039]
Hi.. Is there a way to change the name of attachment..
For ex: I am creating file using api which creates with {random id}.pdf
But when i am sending email with attachment.. It is sent as is with the id name..
Is there a way to rename it..?
![image](https://user-images.githubusercontent.com/18000741/88659727-25524380-d0f3-11ea-9998-e575b3ce5ddb.png)

**Comment by sourabhlk** [comment]
Hi any updates pls..
Need to fix this urgently

**Comment by RCheesley** [comment]
Please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
