### ISSUE TITLE
Mandrill integration sends the email but returns error

### ISSUE THREAD

**Issue by jclimac** [mautic/mautic#9041]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

Hello!

I'm using Mandrill and I'm getting the error bellow when I try to send or test connection on Email setting screen.

Despite the error the email is sent and I receive it perfectly. Both the test and regular emails (campaign, broadcast, etc) are sent but Mautic detects an error and don't register the email as sent, so Mautic is not registering clicks and openings related to that emails.

As Mandrill is not open and requires a Mailchimp subscription, I can provide an API key for tests. Just let me know.

Thank you!!

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.2.24
| Browser | Anyone

### Steps to reproduce
1. Select Mandril as email service on configuration
2. Save and try to send a email test
3. Also try to send a broadcast email -> It will be reported that all emails fail but they are sent.
 
### Log errors
`[2020-07-28 11:15:14] mautic.ERROR: [MAIL ERROR] Mandrill failed to authenticate (send); my@email.com {"exception":"[object] (Swift_TransportException(code: 0): Mandrill failed to authenticate at /var/www/mautic.dir/app/bundles/EmailBundle/Swiftmailer/Transport/AbstractTokenArrayTransport.php:300)"} []`

From Mandrill API logs, this is the response:
`[ { "email": "to.my@email.com", "status": "sent", "_id": "bcf9f58ef651437dbe941d9645903cDS", "reject_reason": null } ]`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi @jclimac thanks for taking the time to make the bug report and for the offer to help us with troubleshooting!

**Comment by rjdjohnston** [comment]
Is there any movement on this issue? I have the exact same problem

**Comment by RCheesley** [comment]
@rjdjohnston not as yet - we need someone to pick this up and look into it / write a PR if it is a bug.
