### ISSUE TITLE
Add a license key for Maxmind into the CI pipeline

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#9044]
## Bug Description

> Consider adding a license key into the CI pipeline, without the key being accessible to the internet publicly, so that IP lookup tests will be included in the CI pipeline

Source: https://github.com/mautic/mautic/pull/8337#issuecomment-578953976

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.3.2
| Browser | Chrome

**Comment by RCheesley** [comment]
@dennisameling presume we can do this with a GH secret?

**Comment by dennisameling** [comment]
@RCheesley correct! Could you create the secret with a name like `MAXMIND_KEY`? I'm happy to add it to GH Actions then

**Comment by RCheesley** [comment]
Done! 🚀

**Comment by dennisameling** [comment]
Not so fast! We need to actually enable it in GH Actions now. Re-opening this issue 😉

**Comment by RCheesley** [comment]
Oh .... ooops! Though the issue was just to add the key as a secret! 😊

**Comment by RCheesley** [comment]
@dennisameling seems like this could be a simple thing to do - is it just a case of adding the secret or do we need to write the tests to check the functionality?
