### ISSUE TITLE
Sendgrid Bounce details not showing in graph for email chanel tab

### ISSUE THREAD

**Issue by Bibhudatta-Sahoo-ASMB** [mautic/mautic#9045]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
In the Mautic email channel I had sent a broadcast mail to around 5000 contacts and it was delivered properly.
But for some contact it was bounce, but it is not the problem.
The problem is, the bounce count is not showing in the channel graph but the contacts are added to the bounce segment.

On further check I got to know that the bounce email id is coming  to Mautic properly but it is not storing the details properly due to which we are not able to see the graph.

It is storing null as value for channel id in the bounce details table, which is lead_donotcontact.

On further checking I got known that the **channel ID** is not passed to storing function in the details table.
I am using the **2.16.3** version but the code is the same for **3.0.2**.
Please check the screenshot http://prntscr.com/tqjy70 

Please let us know if it has any solution.

| Q   | A
| --- | ---
| Mautic version | 2.16.3 (also present on 3.0.2)
| PHP version |  7.2.30
| Browser | Mozilla Firefox

### Steps to reproduce
1. Create an Email channel with segment
2. Add some contact with some bounce contact
3. Then send a broadcast mail
 
### Log errors
No error log

Mautic email channel graph is not showing bounce contact count.
Please check the screenshot http://prntscr.com/tqk2ps

For any question I will be more than happy to answer :)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for taking the time to report the bug - can you add a screenshot of the graph where the data is incorrect?

Would you be up for working on a pull request to address this issue?

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi @RCheesley ,
I have already added a screen shot on the bug description that is
  
![image](https://user-images.githubusercontent.com/44962124/89156192-e0f9f400-d587-11ea-9238-93497940dfae.png)

And in this channel have sent emails to 15 contacts and only 7 are delivered and rest are bounced.

So it should show 8 records are bounced in the graph but as you can see in picture it is showing zero. 

Yes I am working on this and if I get any solution then definitely I will do a pull request.

**Comment by RCheesley** [comment]
Thanks for the added info! It would be super if you could make a PR - shout if you need any help!

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
You are welcome! Yes I am on it.

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi @RCheesley ,
I have done a PR for this.
So please review and Merg.

**Comment by RCheesley** [comment]
Great, please take a look at the messages in the PR - the next bug fix release is at the end of September so we will need to get two people to test and confirm that it works by then!

Thank you for making the PR, it's much appreciated! 🎉

**Comment by ilsebrase** [comment]
Hi, currently running 3.3.4 but still seeing this issue:
<img width="869" alt="Screenshot 2021-12-06 at 21 41 44" src="https://user-images.githubusercontent.com/65490217/144911592-95f76f81-44eb-4899-8f65-64900731a67b.png">

Could someone guide me on how to resolve or status of PR please?

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi @ilsebrase ,
I had added the pull request, but due to some formalities the PR is not added.
But if you wish you can check the PR, please find the link below.
https://github.com/mautic/mautic/pull/9106

**Comment by mabumusa1** [comment]
@Bibhudatta-Sahoo-ASMB I can help you get your PR merged. Are you still interested?

**Comment by Bibhudatta-Sahoo-ASMB** [comment]
Hi @mabumusa1,
Yes I am interested.

**Comment by riazanovslv** [comment]
I also look forward to this merge.

**Comment by mabumusa1** [comment]
Let's pick this PR again
