### ISSUE TITLE
Pre-populating a form from the URL on a landing page causes a 500 error

### ISSUE THREAD

**Issue by gregharvey** [mautic/mautic#9046]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Attempting to pre-populate a Mautic form embedded in a landing page via parameters in the URL appears to cause a 500 error.

| Q   | A
| --- | ---
| Mautic version | bleeding edge! (https://mautibox.com/staging/)
| PHP version | see above
| Browser | Google Chrome for Linux Version 84.0.4147.105 (Official Build) (64-bit)

### Steps to reproduce
1. Go to https://mautibox.com/staging/
2. Make a new form with some fields linked to contact fields and auto-fillable (I tested with Contact: Email)
3. Make a new landing page and embed the form in Code Mode using the JavaScript method
4. Go to that landing page in an incognito window and try to pass in a value, e.g. append `?email=foo@bar.com` to the landing page URL
5. You get a 500 error (see below)

I actually took the trouble to follow my steps on Mautibox again, for now there's an example here:
https://mautibox.com/staging/pre-populate-test?email=foo@bar.com

But this might get destroyed of course.
 
### Log errors

Output on page is as follows:

```
500 Internal Server Error - PHP Warning - Invalid argument supplied for foreach()

Symfony\Component\Debug\Exception\ContextErrorException
/app/bundles/PageBundle/Model/PageModel.php:1169 at
/app/bundles/PageBundle/Model/PageModel.php:1169 at Mautic\CoreBundle\ErrorHandler\ErrorHandler -> handleError ( '2', 'PHP Warning - Invalid argument supplied for foreach()', '/var/app/current/code/pulls/staging/app/bundles/PageBundle/Model/PageModel.php', '1169', array('query' => 'email=foo%40bar.com') )
/app/bundles/PageBundle/Model/PageModel.php:589 at Mautic\PageBundle\Model\PageModel -> cleanQuery ( 'email=foo%40bar.com' )
/app/bundles/PageBundle/Model/PageModel.php:530 at Mautic\PageBundle\Model\PageModel -> processPageHit ( object(Hit), object(Page), object(Request), object(Lead), true )
/app/bundles/PageBundle/Controller/PublicController.php:287 at Mautic\PageBundle\Model\PageModel -> hitPage ( object(Page), object(Request), '200', object(Lead), 'email=foo%40bar.com' )
/vendor/symfony/http-kernel/HttpKernel.php:151 at Mautic\PageBundle\Controller\PublicController -> indexAction ( 'pre-populate-test', object(Request) )
/vendor/symfony/http-kernel/HttpKernel.php:68 at Symfony\Component\HttpKernel\HttpKernel -> handleRaw ( object(Request), '1' )
/vendor/symfony/http-kernel/Kernel.php:200 at Symfony\Component\HttpKernel\HttpKernel -> handle ( object(Request), '1', true )
/app/AppKernel.php:104 at Symfony\Component\HttpKernel\Kernel -> handle ( object(Request), '1', true )
/app/middlewares/CORSMiddleware.php:91 at AppKernel -> handle ( object(Request), '1', true )
/app/middlewares/CatchExceptionMiddleware.php:43 at Mautic\Middleware\CORSMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/Dev/IpRestrictMiddleware.php:64 at Mautic\Middleware\CatchExceptionMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/VersionCheckMiddleware.php:67 at Mautic\Middleware\Dev\IpRestrictMiddleware -> handle ( object(Request), '1', true )
/app/middlewares/TrustMiddleware.php:51 at Mautic\Middleware\VersionCheckMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 at Mautic\Middleware\TrustMiddleware -> handle ( object(Request), '1', true )
/vendor/stack/run/src/Stack/run.php:13 at Stack\StackedHttpKernel -> handle ( object(Request) )
/index_dev.php:25 at Stack\run ( object(StackedHttpKernel) )
/index.php:6 at require_once ( '/var/app/current/code/pulls/staging/index_dev.php' )
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for taking the time to add a bug report!
