### ISSUE TITLE
[BUG] A/B test results based on last edit date

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#9047]
| Q  | A
| ---| ---
| Confirm it is a Bug report |
| Mautic version | v2.16.1 .2 .3 and v3.0.2
| PHP version | 

[//]: # (Feature request? ---> Go to forum please ---> https://forum.mautic.org/c/ideas)
[//]: # (Enhancement? ---> Go to forum please ---> https://forum.mautic.org/c/ideas)
[//]: # (Need support, have questions? ---> Go to forum please ---> https://forum.mautic.org/c/support)

## Description:
I've recently ran an A/B email campaign as a segmented email. I noticed that the A/B results seem to have cleared when the emails unpublished a day later. When moving the unpublished data through away the data got completely reset and updated with a message stating the A/B test time started at the time I updated the unpublished date.

Just to explain, I personally always set an unpublished time of 24 hours after a segmented campaign is sent to prevent accidental sending in the future. 

### Steps to reproduce:
1. Run an AB email campaign with an unpublished data - Check for the results you'll see they disappear when the email unpublishes.
2.  Update the unpublished date and you'll see the A/B test starts from the last updated date, not the published date.
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
Thanks for raising this bug, we are tracking this in #7276 but we were waiting for confirmation that it persisted in Mautic 3.x so I will close this and take the discussion over there.
