### ISSUE TITLE
Unable to upgrade via CLI

### ISSUE THREAD

**Issue by uhlhosting** [mautic/mautic#9051]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | latest 2.x
| PHP version | PHP 7.2.32-1
| Browser | Safari / Firefox / Chrome

### Steps to reproduce
1. Trying to upgrade from latest 2x to 3x tried online version:

The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
System administrators, check server logs for errors.
visible at https://ma.uhlhosting.ch/

2. composer upgrade from cli details bellow
 
### Log errors
`ma@ma:/var/www/html/mautic$ composer upgrade
Loading composer repositories with package information
Updating dependencies (including require-dev)                          
Nothing to install or update

                                                                                                                    
  [ErrorException]                                                                                                  
  file_put_contents(/var/www/html/mautic/vendor/composer/installed.json): failed to open stream: Permission denied  
                                                                                                                    

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

ma@ma:/var/www/html/mautic$ sudo composer upgrade
[sudo] password for ma: 
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)                          
Nothing to install or update
Package babdev/transifex is abandoned, you should avoid using it. No replacement was suggested.
Package facebook/webdriver is abandoned, you should avoid using it. Use php-webdriver/webdriver instead.
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Package phpunit/dbunit is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Package sensio/generator-bundle is abandoned, you should avoid using it. Use symfony/maker-bundle instead.
Generating autoload files
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the prod environment with debug false                                                        

                                                                                                                        
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.                                          
                                                                                                                        

> php -r "if(file_exists('./.git')&&file_exists('./build/hooks/pre-commit'.(PHP_OS=='WINNT'?'.win':''))){copy('./build/hooks/pre-commit'.(PHP_OS=='WINNT'?'.win':''),'./.git/hooks/pre-commit');}"
> php -r "if(file_exists('./.git/hooks/pre-commit')&&(PHP_OS!='WINNT')){chmod('./.git/hooks/pre-commit',0755);}"
ma@ma:/var/www/html/mautic$ php bin/console mautic:update:find
Could not open input file: bin/console
ma@ma:/var/www/html/mautic$ ls
app    codeception.yml  favicon.ico    index.php            media         package-lock.json  robots.txt   themes              upgrade_log.txt  vendor
bin    composer.json    Gruntfile.js   LICENSE.txt          offline.php   plugins            SECURITY.md  translations        upgrade.php
build  composer.lock    index_dev.php  mautic-3-temp-files  package.json  README.md          tests        upgrade_errors.txt  upgrade_v3.php
ma@ma:/var/www/html/mautic$ php bin/console mautic:update:find
Could not open input file: bin/console
ma@ma:/var/www/html/mautic$ cd bin/
ma@ma:/var/www/html/mautic/bin$ ls
codecept  dbunit  doctrine  doctrine-dbal  doctrine-migrations  doctrine.php  jp.php  php-cs-fixer  phpunit  security-checker
ma@ma:/var/www/html/mautic/bin$ cd ..
`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by uhlhosting** [comment]
This is in the install_log.txt

```root@ma:/var/www/html/mautic# less upgrade_log.txt 

[2020-08-02 06:43:58] Running pre-upgrade checks...
[2020-08-02 06:44:00] One or more errors occurred in the pre-upgrade checks:
- Your MySQL/MariaDB version is not supported. You need at least MySQL 5.7.14 or MariaDB 10.2 in order to run Mautic 3.

[2020-08-02 06:44:00] One or more warnings occurred in the pre-upgrade checks:
- You seem to have installed Mautic by cloning from GitHub. We don't support upgrading with the upgrade script in this scenario. Proceed at your own risk or reinstall with the official package at <a target="_blank" href="https://github.com/mautic/mautic/releases/tag/2.16.3">https://github.com/mautic/mautic/releases/tag/2.16.3</a>

[2020-08-02 09:13:52] ===== STARTING MAUTIC 3 UPGRADE AT 2020-08-02 09:13:52... =====
Installed Mautic version:       2.16.3
PHP version:                            7.2.32-1+ubuntu18.04.1+deb.sury.org+1
OS:                                                     Linux
Upgrade type:                           UI

[2020-08-02 09:13:54] Running pre-upgrade checks...
[2020-08-02 09:14:04] One or more errors occurred in the pre-upgrade checks:
- Your MySQL/MariaDB version is not supported. You need at least MySQL 5.7.14 or MariaDB 10.2 in order to run Mautic 3.

[2020-08-02 09:14:04] One or more warnings occurred in the pre-upgrade checks:
- You seem to have installed Mautic by cloning from GitHub. We don't support upgrading with the upgrade script in this scenario. Proceed at your own risk or reinstall with the official package at <a target="_blank" href="https://github.com/mautic/mautic/releases/tag/2.16.3">https://github.com/mautic/mautic/releases/tag/2.16.3</a>```

**Comment by uhlhosting** [comment]
I also runned all commands to fix permission from troubleshooting guide:

Runned all these to fix permissions:

```
root@ma:/var/www/html/mautic# find . -type f -not -perm 644 -exec chmod 644 {} +
root@ma:/var/www/html/mautic# find . -type d -not -perm 644 -exec chmod 755 {} +
root@ma:/var/www/html/mautic# chmod -R g+w app/cache/ app/logs/ app/config/
root@ma:/var/www/html/mautic# chmod -R g+w media/files/ media/images/ translations/
root@ma:/var/www/html/mautic# rm -rf app/cache/*
```

Made sure all permissions are on local user and on web server and tried to run composer outside of sudo/root:

```
ma@ma:/var/www/html/mautic$ composer upgrade
Loading composer repositories with package information
Updating dependencies (including require-dev)                          
Nothing to install or update

                                                                                                                    
  [ErrorException]                                                                                                  
  file_put_contents(/var/www/html/mautic/vendor/composer/installed.json): failed to open stream: Permission denied  
                                                                                                                    

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

ma@ma:/var/www/html/mautic$ 
```

**Comment by brafreider** [comment]
> [2020-08-02 09:14:04] One or more errors occurred in the pre-upgrade checks:
> - Your MySQL/MariaDB version is not supported. You need at least MySQL 5.7.14 or MariaDB 10.2 in order to run Mautic 3.

Mautic 3 requires MySQL 5.7 or MariaDB 10.2, as this is a failed check, update will stop here.

Cheers,
Björn

**Comment by RCheesley** [comment]
Hi there, to upgrade from Mautic 2.x to Mautic 3.x you should update to 2.16.3 and then the upgrade script will be available to you either at CLI (preferable) or in the browser - you will see the upgrade script appear in the root of your Mautic directory when you have updated to 2.16.3.  

You should not need to be doing anything with composer to do the 2->3 update.

The upgrade script does all the necessary pre-flight checks and will flag up things like the wrong database versions and have you fix them before you are able to proceed.

Please take a look at the documentation for further guidance: https://docs.mautic.org/en/mautic-3-upgrade/upgrade-steps

Please post in the dedicated support forum when you have followed the correct steps above and are still experiencing problems: https://forum.mautic.org/c/support/mautic-3-install-upgrade-support/98

**Comment by uhlhosting** [comment]
> > [2020-08-02 09:14:04] One or more errors occurred in the pre-upgrade checks:
> > 
> > * Your MySQL/MariaDB version is not supported. You need at least MySQL 5.7.14 or MariaDB 10.2 in order to run Mautic 3.
> 
> Mautic 3 requires MySQL 5.7 or MariaDB 10.2, as this is a failed check, update will stop here.
> 
> Cheers,
> Björn

After upgrading mysql mautic stops working.
