### ISSUE TITLE
Contact to Company Relationship Custom Fields Not Working As Variables

### ISSUE THREAD

**Issue by schoettlera** [mautic/mautic#9054]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If we compose an email with tokens/variables that consist of values associated with the contact's "primary company" (i.e. {contactfield=companyurl}, none of the values populate. Inside of (one of many) Mautic documentation repos (mautic.com/help/emails) it states that if you're using a company field, still use the same format as Mautic pulls data from the contact's primary company. We have tried on several instances to do this, with test contact manually filling in the fields, using built-in fields and custom fields, with no success. 

| Q   | A
| --- | ---
| Mautic Version | 3.0.2 | 
| PHP Version  |7.2.24 | 
| Browser |Chrome 84.0.4147.105 (Windows) | 

### Steps to reproduce
1. Create any custom field associated with company core.
2. Create a new company and populate the custom field with any value.
3. Create a new contact and populate the primary company with the new company you created that houses the custom field, add your email address.
4. Create a template email with custom code (or any email template).
5. Create a test block and navigate to tokens.
6. Select the token that is associated with the new company custom field created (which should pull from the contact's primary company).
7. Save and close email template.
8. Go to contacts and in the dropdown choose send email.
9. Navigate to choose an email template and select the newly created template
10. Send email.
11. See empty values in the email which should have been dynamically populated.
 
### Log errors
No log errors as it's email related.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by k2-Marketing** [comment]
I have tried this. I can confirm that this is a bug. in 3.1.0

**Comment by RCheesley** [comment]
Thanks for the bug report folks, is anybody able to double check if it's still a problem with the latest release?

**Comment by MapleSage** [comment]
Any update or way around this issue, even with the latest Bitnami Certified 3.3.2 version I'm facing this issue.

**Comment by Robmobius** [comment]
This bug exists in 3.3.3

I am using company tokens in dynamic content and they are not pulling through. Some are custom fields and some are base mautic company fields.

**Comment by sboytsov** [comment]
still bug in v3.3.4. Any solution?

**Comment by kuzmany** [comment]
This is related for custom email, segment/campaign emails should works.
We are working on fix.

**Comment by pascalinger** [comment]
> This is related for custom email, segment/campaign emails should works. We are working on fix.

Hi there! Any update on this fix?

**Comment by pascalinger** [comment]
Just tested this and can confirm Company information can still not be used inside ad-hoc emails sent to specific contacts. Works fine inside campaigns
