### ISSUE TITLE
Mautic v3.0.2 | DWC | Filter | Unable to select tag

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#9055]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.0.2 
| PHP version | 7.3
| Browser | Chrome 84.0.4147.105 (Official Build) (64-bit)
### Steps to reproduce
1. Create a DWC item with "Is campaign based?" set to No.
2. Under Filters, attempt to select a tag. The tag will be populated into the box as expected, though after saving it will be rejected, Mautic reporting that the value is not valid. 
3. Occasionally, the respective tag's ID # is shown or sometimes it will just be accepted, though the tag will be shown as its respective ID # as opposed to its name. Sometimes it just saves, but the tag ID is shown instead of it's name, too. 

See screenshots. 
![issue1](https://user-images.githubusercontent.com/7994227/89400249-eab06280-d713-11ea-9b8f-95470cc513b1.png)
![issue3](https://user-images.githubusercontent.com/7994227/89400255-ed12bc80-d713-11ea-915f-4bcbaacfb466.png)
![issue4](https://user-images.githubusercontent.com/7994227/89400311-03b91380-d714-11ea-9a74-15379eb2e7e6.png)

 
### Log errors
Unable to find anything in logs. Please let me know if there is somewhere else I should checking other than /var/logs.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by diamondtheta** [comment]
I confirm that this bug exists in mautic 3.1 also. Any solution or workaround? :(((

**Comment by kuzmany** [comment]
Tags filter is not supported in dynamic contents.
This PR https://github.com/mautic/mautic/pull/9260 display just supported filters in DC

**Comment by diamondtheta** [comment]
Oh, thanks, I see 3.2 will be awesome :)))

**Comment by RCheesley** [comment]
Closing the PR as it is an unsupported feature rather than a bug
