### ISSUE TITLE
Inbox received the reply but Mautic didn't recognize it

### ISSUE THREAD

**Issue by olgadoking** [mautic/mautic#9058]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hi there! First I am a newbie on this open source marketing automation so please bear with me :)

So I've been analyzing the performance of our campaign. Basically what it does is just send emails and if it receives replies it would then update that contact stage saying we got his/her First Reply. Some worked pretty well and their response was received by the INBOX of the account where it is supposed to reply AND Mautic was able to recognize it as well labeling it "Email Replied". NOW, here's the issue, some response was received by the INBOX **BUT** Mautic WAS NOT ABLE to recognize it even though the reply was sent just on time. No bounce emails were also received. and the contact was able to reply on the right "FROM" email I used to send out emails.

Why do you think is this happening?

Is it because of the email service used for the reply? or is it because of my email server? I don't know.

I hope you could enlighten me what to do or how to further troubleshoot this problem of mine. 

| Q   | A
| --- | ---
| Mautic version | 3.0.1
| PHP version | 7.3.14-1
| Browser | Microsoft Edge

### Steps to reproduce
1.  Create custom value for contacts
2.  Create campaign that sends emails to these contacts
3.  If contact didn't reply for 3 DAYS to the first email send the 1st follow-up, if contact did reply, update contact stage to 'Received 1st Reply'
4.  If contact didn't reply for 3 DAYS to the 2nd email send the 2nd follow-up, if contact did reply, update contact stage to 'Received 1st Reply'
5.  If contact didn't reply for 3 DAYS to the 3rd email send the 2nd email request for a call, if contact did reply, update contact stage to 'Received 1st Reply'.

### Log Errors
There were no errors logged. 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi @gnikkk31 and welcome to Mautic! 

Sorry to hear you're having some issues with getting the reply feature working.  We have some resources in the [documentation](https://docs.mautic.org/en/channels/emails/contact-replies) that might be helpful, but I would ask that you post the issue at https://forum.mautic.org/c/support as that's where we offer help/guidance rather than here on Github. We try to keep this clear from support requests and only have bug reports in the issue queue.

I'll close the issue down as a result - if it does turn out to be a bug with Mautic then please do raise an issue in the future!
