### ISSUE TITLE
MIME type and extension not being set for remote asset uploaded via API

### ISSUE THREAD

**Issue by StevenChin** [mautic/mautic#9074]
## Description:
After uploading a remote asset via the Mautic API, the `mime` and `extension` fields for the asset are returned as null. However, performing the same upload via the UI sets these fields and you are able to preview the asset.

### Steps to reproduce:
1. Make POST request to `/assets/new` endpoint:

   ```bash
   curl --request POST 'https://example.com/api/assets/new' \
   --data-urlencode 'file=http://assetserver.com/asset.pdf' \
   --data-urlencode 'storageLocation=remote' \
   --data-urlencode 'title=asset.pdf'
   ```
2. The `extension` and `mime` fields in the response body are null.

**Comment by StevenChin** [comment]
Any insights here? I'd be willing to do a PR if I'm pointed in the right direction as I'm not too familiar with the codebase.

**Comment by mabumusa1** [comment]
@StevenChin check this [file](https://github.com/mautic/mautic/blob/48640968c068e73ae744a91f9eb779c0284cf2eb/app/bundles/AssetBundle/Entity/Asset.php#L903) 

I think this is the cause of the error, I have not tested your bug report yet so I can not confirm it. May you please run 
`curl --request GET 'https://example.com/api/assets/id'` where `id` is the id of a remote asset. if you get `null` here as well that means the entity file needs some attention

**Comment by StevenChin** [comment]
@mabumusa1 thanks for the response. I can confirm that the test you suggested returns null for both the mime and extension fields.

I did a bit of debugging and I noted that the the asset entity fields are null at the point in the ApiController where Mautic tries to retrieve the file information for the remote file, see https://github.com/mautic/mautic/blob/staging/app/bundles/AssetBundle/Controller/Api/AssetApiController.php#L73.

I'm not too sure how the request parameters are used to create the entity but at the point in the controller identified above, the asset entity fields are null.

**Comment by mabumusa1** [comment]
@StevenChin thanks for taking the time to look into that, I think the cause of this error is on this [function](https://github.com/mautic/mautic/blob/48640968c068e73ae744a91f9eb779c0284cf2eb/app/bundles/AssetBundle/Entity/Asset.php#L903)

I suggest you test this function and see what type of output do you get when you are dealing with a remote file. 

Do you need help getting started with debugging? I suggest you start with this [article](https://www.mautic.org/blog/developer/local-mautic-development-with-ddev)

**Comment by StevenChin** [comment]
> I think the cause of this error is on this function

@mabumusa1 yes that is correct. 

What's happening is that the API Controller isn't populating the asset entity fields for the create request before [this point](https://github.com/mautic/mautic/blob/staging/app/bundles/AssetBundle/Controller/Api/AssetApiController.php#L73). Here's what I observed afterwards:
 
  1. There's an attempt to set the file info for asset entity via `$entity->setFileInfoFromFile()`

  2. An attempt is made to get the file info via curl request via `$entity->getFileInfo()`

  3. The asset is checked to see if it is a remote file as this determines how the file information is retrieved. `$entity->isRemote()` returns false as `$entity->storageLocation` is defaulted to `local` [here](https://github.com/mautic/mautic/blob/staging/app/bundles/AssetBundle/Entity/Asset.php#L47)

  4. An attempt is made to load the file from the local file system via `$entity->loadFile()` but null is returned this an empty string is returned for the file information.

  5. File information is not set, thus mime and extension properties are null.

I think the root cause of this issue is that the entity fields aren't being set after the form POST to the API. I'm not too sure why that is, maybe it's an oversight or maybe there are something is wrong with the format of my request or the parameters I'm specifying.

**Comment by mabumusa1** [comment]
@StevenChin I think you are moving in the right direction,  do you want to provide a PR for this? I can help review the code

**Comment by StevenChin** [comment]
@mabumusa1 I would but I don't know how to solve the problem. I just have an idea of what it is, I need someone who has a bit more context to determine exact problem and the appropriate solution.

**Comment by mabumusa1** [comment]
@StevenChin sometime you just wish that the error you get is related to the thing you are fixing!. I fixed the issue by upgrading some packages related to S3 and changed a bit in the plugin code. 

I will push PR today



![image](https://user-images.githubusercontent.com/12627658/91160073-a3ddd900-e6d1-11ea-8ae0-49e61087f20b.png)

**Comment by StevenChin** [comment]
That's wonderful news @mabumusa1! Thanks for the assistance. I will test this PR later today.
