### ISSUE TITLE
continue 2 targeting switch is equivalent to break 2 - Mautic Reports

### ISSUE THREAD

**Issue by diletecsoftware** [mautic/mautic#9087]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When accessing the reports, Mautic generates an error in the Log described in "Log errors".

I found an error report in stackOverflow that claimed to be the composer version. The update was made to version 1.10.10, but the error continues.

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.3.21
| Browser | Google Chrome 84.0.4147.105

### Steps to reproduce
1. Access any report
 
### Log errors
[2020-08-14 12:05:49] mautic.WARNING: PHP Warning - "continue 2" targeting switch is equivalent to "break 2". Did you mean to use "continue 3"? - in file /home/mkt/public_html/mkt.com/app/bundles/ReportBundle/Builder/MauticReportBuilder.php - at line 444 {"file":"/home/mkt/public_html/mkt.com/vendor/composer/../../app/bundles/ReportBundle/Builder/MauticReportBuilder.php"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there,

I am unable to reproduce this in 3.1-Release Candidate - I have tested all the reports that ship with Mautic and none are throwing an error.

Can you please check and see if this persists for you in 3.1? Also double check the usual things like cache clearing etc :)

**Comment by diletecsoftware** [comment]
Hello,

I'm running Mautic 3.1.0 and without the error reporting.
