### ISSUE TITLE
Unrealistic visitors count on the dashboard

### ISSUE THREAD

**Issue by trancemanone** [mautic/mautic#9094]
Hi guys, 

I have two issues with mautic 3.0.2: 

The first is the wrong page viaitors count. 

The second is the ability to edit widgets on the dadhboard. It doesnt go to the editing section and gets stuck there forever. 

![image](https://user-images.githubusercontent.com/67905330/90397323-5f828580-e0a0-11ea-8056-aba51a3880ed.jpeg)

Any ideas? 

Thanks

**Comment by trancemanone** [comment]
Any ideas ?

**Comment by StoppingBuck** [comment]
Hi @trancemanone as far as I know that graph does not show visitor count, but number of contacts created in Mautic on a specific date. Chances are, maybe you imported a CSV with a bunch of new contacts, or pushed them via the API, somewhere in early August?

The part about the stuck Loading screen definitely looks like a bug, though. Is anything shown in the logs?

**Comment by trancemanone** [comment]
> Hi @trancemanone as far as I know that graph does not show visitor count, but number of contacts created in Mautic on a specific date. Chances are, maybe you imported a CSV with a bunch of new contacts, or pushed them via the API, somewhere in early August?
> 
> 
> 
> The part about the stuck Loading screen definitely looks like a bug, though. Is anything shown in the logs?

Thank you so much for your reply. 

I think I have posted the wrong image my bad, here is the right one: 

![image](https://user-images.githubusercontent.com/67905330/90628389-32f87600-e226-11ea-94a8-bf27e0ab029f.jpeg)￼

The website I have is hardly having 6 - 15 visits a day. 

So when I turned off the tracking it went down to zero even though I haven't planted the Mautic code in my website. 

Regarding the widgets issue,the log doesn't have any errors what so ever. 

Mautic: 3.0.2 

PHP Version 7.3.20
ubuntu 16.04.1

**Comment by colourfulowl** [comment]
I've had something similar happen in the past. It can happen if you are using a shared hosting provider. An east way to see if this is the case is to look at your contacts and see where the anonymous ones have generated from. You might see a lot of it comes from your servers IP.

**Comment by trancemanone** [comment]
> I've had something similar happen in the past. It can happen if you are using a shared hosting provider. An east way to see if this is the case is to look at your contacts and see where the anonymous ones have generated from. You might see a lot of it comes from your servers IP.

It cant be because Im not using a shared hosting provider I'm using a VPS with a designated IP address for mautic. I'm surprised that not many people are reporting this even though I had multiple installs ( mautic 3.0 and above ) and they all have the same issue even though I have used different installation methods like the composer and the unzip with no luck at all. 

Could you please point out the installation method you have used

**Comment by colourfulowl** [comment]
I have a few different installs, all of which are on bespoke AWS EC2 servers.

Some are deployed using an image from Bitnami, other manual depending on server requirements and database sizing.

The visitor tracking is a little off compared to google analytics, but not that far off. I do sometimes have traffic appear that pings the server, but have a campaign that removes those from my data.

**Comment by RCheesley** [comment]
Hi folks,

Some other things to look into are whether you're getting hits from bots (you should be able to look into your server logs to check that) or any kind of monitoring tool that might be triggering this kind of behaviour. Ultimately I don't think this is a bug with Mautic so I'm going to close the issue - if you need help understanding what's going on in more depth please open up a topic at https://forum.mautic.org/c/support.
