### ISSUE TITLE
Oauth2 not working M3

### ISSUE THREAD

**Issue by weismannweb** [mautic/mautic#9098]
## Bug Description
API oauth2 not working....

| Q   | A
| --- | ---
| Mautic version | 3.0.2 
| PHP version | 7.3
| Browser | chrome on ubuntu 20.04

### Steps to reproduce
1. use integromat, zapier or anything to try and connect to mautic via oauth 2
2. hit the accept button when mautic asks you if you want to accept
2. get error:
Error
[401] API authorization denied
3. clear cache both -d memory_limit=2G bin/console cache:clear and rm -rf var/cache/*
4. try again and get same error but this time it skips asking you if you want to accept the connection, it goes right back and says the error

Attempt #2:
1. go to https://oauthdebugger.com/
2. enter oauth url https://readers.rebeccagraceallen.com/oauth/v2/authorize (do i have this right)?
3. enter secret and client keys
4. i tried both code and token and each one on thier own
5. i tried all 
 query
 form_post
 fragment
6. i login
7. it takes me to preference center, so i changed the root url of mautic from preference center to dashboard and cleared cache, it then took me to dashboard, did not go back to the tester but there was no error

I tested zapier too but that must have a special connection cause I only had to enter the domain and it never went through oauth2 process.

This was with a secondary admin user not the first one I created in Mautic

### Log errors
none

**Comment by npracht** [comment]
Hi @weismannweb thanks for reporting this issue.
I cannot reproduce, it is working for me. Are you sure about user rights ? API configuration in menu ?
Any chance to have a server configuration issue ?

Do you have something in your logs ?

**Comment by weismannweb** [comment]
Actually i did a little more hard core debugging and it seems to work via:

1.  go to https://oauthdebugger.com/
2. enter oauth url https://readers.rebeccagraceallen.com/oauth/v2/authorize
3. client keys and test for scope
4. use code
5. use query
6. when it goes to mautic and gives 500 error remove "scope=test&" from url then refresh and it should work (as per doc mautic does not use this)
7. run this command on command line:
curl -d "grant_type=authorization_code&code=[authocdeyougot]&client_id=[yourclientid]&redirect_uri=https%3A%2F%2Foauthdebugger.com%2Fdebug" https://readers.rebeccagraceallen.com/oauth/v2/token
8. you will then get an auth code
9. use it on command line to get token:
curl -X GET https://readers.rebeccagraceallen.com/api/contacts/1?access_token=[useacceestokenhere]
10. it WORKS so i will follow up with integromat and tell them this

For now I have no proof that this is a bug with Mautic.  Therefore you can close it.
