### ISSUE TITLE
When selecting a "Push to integration" action, show message to configure via integration's config rather than nothing when no overriding options are available

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#91]
When trying to push a lead to vTiger from a form using an action, the vTiger option doesn't work - the spinner keeps spinning but fields never emerge.

http://nimb.ws/4HCL36

**Comment by RCheesley** [comment]
Not sure if this is working or not, I tried it again and it didn't have the spinner, but it also didn't show any fields - is it supposed to? Was expecting something like the Mailchimp interface to match fields etc.

**Comment by alanhartless** [comment]
The mailing list integrations were designed that way as some of the the services allow custom fields per mailing list. Right now, CRMs do not populate custom lead field matching in the push to integration forms.  Is there a common scenario where you would push a Mautic's lead value to different CRM lead fields?

Thanks,
Alan

**Comment by alanhartless** [comment]
Also for the CRM integrations, you would match the lead fields in the CRM integration configuration under Manage Integrations.  You would do the same of the 'defaults' for mailing list integrations, but for the reason stated above, you can override these in the push to integration form.

Thanks,
Alan

**Comment by RCheesley** [comment]
Thanks @alanhartless - I had expected to see something like the Mailchimp fields with the defaults being populated, or a 'Options are configured under Manage Integrations' notification, but nothing showed.  If you have to set up the linked fields under manage integrations, I'd recommend stating that when someone selects the push to CRM function, just so that people are aware.

I'm still exploring VTiger (as we use a CRM that isn't supported at the moment) so I can't give any specific information about when you might want to put the value into a different field.
