### ISSUE TITLE
Compound fields are not getting mapped in plugin contact fields

### ISSUE THREAD

**Issue by k2-Marketing** [mautic/mautic#9102]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When mapping contact fields in plugins like CRM plugins (hubspot tested) (fields: id, contact link, do not contact by email) the fields does not get mapped properly.

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.2
| Browser | 

### Steps to reproduce
1. Open Hubspot plugin configuration
2. Map contact field (id,  timeline link or do not contact by email) to a hubspot field
3. click save and close. 

you will see a warning triangle next to the contact fields tab and window won't close. mautic field is then left blank.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Can you do a short screencast (eg using Screencastify) to show this in action please?

**Comment by k2-Marketing** [comment]
![Manage Plugins _ Mautic](https://user-images.githubusercontent.com/48127606/91038680-76c6f300-e60b-11ea-9b1a-bb0e14a7a6d2.gif)

**Comment by RCheesley** [comment]
@k2-Marketing thanks for the screencast, are you still having this in 3.1.1?  Is this only happening with custom fields, or do you have the same if you were to try and connect it with a regular field?

**Comment by RCheesley** [comment]
Closing due to lack of recent response.
