### ISSUE TITLE
Update Lodash etc.

### ISSUE THREAD

**Issue by dennisameling** [mautic/mautic#9104]
As reported by @npracht, we need to bump some NPM dependencies due to security issues. Tracking the updates with this issue

![image](https://user-images.githubusercontent.com/17739158/90526912-3b42a980-e171-11ea-955a-b4aa38d7fca2.png)

**Comment by RCheesley** [comment]
We still have [quite a few of these to deal with](https://github.com/mautic/mautic/security/dependabot) - I suggest that we look at 4.1 being a dependency update release in addition to the regular theme.

**Comment by RCheesley** [comment]
@escopecz I am not sure if this old issue is still required? We just keep bumping the milestone 🙈

**Comment by escopecz** [comment]
I updated all NPM dependencies in https://github.com/mautic/mautic/pull/11113/commits/2e34ac9ea37f62e91aa4dc9cb70f541730aa6768 which was released in 4.3.0, so I'm closing this.
