### ISSUE TITLE
Custom Field (options) not working in Email

### ISSUE THREAD

**Issue by CyberMarsl** [mautic/mautic#9105]
## Bug Description
Sending the content of a custom field of type "options" the data will not be displayed in mautic email.
(simple text fields like name are working).

Mautic Version 

| Mautic version | 3.0.2
| PHP version | 7.3.21

### Steps to reproduce
1. Create a custom field for contacts and preset some values
2. Create a vorm to create a contact using the custom field.
3. Start a campaign from this form. As Action send an email and include the custom_value with {contactfield=fieldname} where as fieldname is the name of the the custom field you created in step 1.
4. Start the campaign by entering the form. (and have the campaign triggered by cron or manually). 

### Log errors
No Errors in Log

**Comment by RCheesley** [comment]
Hi there, sorry for the delay in replying, we have been a little swamped with the 3.1 release 😅 

Can you clarify what you mean by "custom field of type "options"" please?

**Comment by CyberMarsl** [comment]
It seems that the problem happens earlier in the process so that the field is not set proper and therefore not displayed in the email.

I have a custom field, which you can select mutliple checkboxes. This field is not stored in the user database (should be!) but I can access it via campaign check form field. 

(another problem about the creation of the form field is already documented in another isseu on github).

another strange behaviour: when I submit a new lead via a form, the lead is created and I can change the properties. 
after executing the the console m:c:t => I can edit the lead, but saving leads to a Server 500 Error.

The error log:
 mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\NonUniqueResultException: "More than one result was found for query although one row or none was expected." at /[mauticpath]/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php line 804 {"exception":"[object] (Doctrine\\ORM\\NonUniqueResultException(code: 0): More than one result was found for query although one row or none was expected. at [mauticpath/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:804)"} []

(mauticpath is the path to the mautic installation)

It seems that somehow more than 1 unique lead was found for the lead to edit.
(using: mysql  Ver 15.1 Distrib 10.3.17-MariaDB)

So to be clear the issue: {contactfield=myfieldname} shows the values (would prefer to show the label in user email)
maybe a general check for label/value usage in all areas would be a good idea (including: campaign custom value, forms etc.)

**Comment by RCheesley** [comment]
@CyberMarsl would you be up for looking into writing a PR to address this issue? There's documentation here if you need any guidance: https://contribute.mautic.org/contributing-to-mautic/developer.

**Comment by alanhartless** [comment]
@CyberMarsl by "custom field" are you referring to a Mautic Form field or a Mautic Contact field? 

`I have a custom field, which you can select mutliple checkboxes. This field is not stored in the user database (should be!) but I can access it via campaign check form field.` The only field in Mautic that can be configured to not be persisted to the database is a Form field and those are not accessible via the {contactfield=X} tokens. You'd have to create a matching Contact custom field and map it to the Form field in the Form field UI. If it is already mapped, then there may be a bug in how non-persisted (to the database) Form data is mapped to the Contact profile. 

Form fields not persisted to the database showing up in the Campaign condition reads like a UI bug.
