### ISSUE TITLE
Forms on website does not handle + (plus sign) in emails well

### ISSUE THREAD

**Issue by weismannweb** [mautic/mautic#9110]
## Bug Description
When an email is using plus addressing using a plus sign in the email the embeded mautic forms do not handle it well when the email is pre-filled by known identified contact data in Mautic.

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.2
| Browser | chrome Version 83.0.4103.116 (Official Build) (64-bit) on linux

### Steps to reproduce
1. enter an email on your contact record with a + in it like this test+test@domain.com
2. create form on mautic with an email field and set it to populate it if the contact is known
3. place form on website using javascript method (didn't check other methods)
4. make sure you are identified by mautic then go to form (might need to click on an email link first) also make sure your not logged in as admin or you wont be identified.  The email should be prefilled to know its working.  But notice the + is missing and if you don't change it and just submit the form then it fails validation because the + is actually a space now.
 
### Log errors
none

**Comment by RCheesley** [comment]
I am trying to reproduce this in a local environment using a separate Chrome profile to test but struggling (field is not being populated at all)- maybe it won't work for 127.0.0.1 ... doing a bit more digging.

**Comment by RCheesley** [comment]
@weismannweb I wasn't able to reproduce this - are there any specific settings that are needed for the pre-populating to work?

**Comment by RCheesley** [comment]
Closing due to a lack of response from the original poster and being unable to reproduce.
