### ISSUE TITLE
Send form results does not create a trigger for emails in the CC field

### ISSUE THREAD

**Issue by diletecsoftware** [mautic/mautic#9111]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Mautic is not sending e-mail to CC field emails when using the "Send form results" Action when triggering a form submission.

I opened the email created by Mautic in "var / spool /" I did not find the email addresses that were in the CC field. I changed the email addresses to the TO field and when performing a new test all emails were written to the email file in "var / spool".

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.3.21
| Browser | Google Chrome
| SMTP | Sendgrid API OR Amazon SES

| Q   | A
| --- | ---
PHP 7.3.21 | PHP-FPM
max_execution_time | 60
max_input_time | 600
max_input_vars | 3000
memory_limit | 512M
post_max_size | 8M
upload_max_filesize | 8M

### Steps to reproduce
1. Create a form with the "Send form results" action, and put some emails in the CC field
2. Use the form
3. When opening the "email" files in "var / spool" the email addresses will not be present in the files and the addresses will not receive the email with the form data.
 
### Log errors
There are no errors in the Log

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi @Diletec thanks for reporting this bug -  I did a bit of testing locally on 3.1-Release Candidate.  You didn't mention what email provider you are using which may be relevant here.  

![screenshot-local mautic31-2020 08 21-14_16_39](https://user-images.githubusercontent.com/2930593/90894900-32441900-e3b9-11ea-90fe-5b0d82bcd6b8.png)
 
We would expect 
* Reply-to address set to the contact's address
* 1 email sent to the contact (reply to address not relevant here)
* 1 email sent to the owner (where set)
* 1 email sent to the details in the form

### Result:

#### 4 emails: 

**Email 1** - To:  Address in To field; Replyto: contact's address; CC: address supplied in CC field  BCC: Nothing set ❌  Not sure why this one is being sent

![screenshot-127 0 0 1_8025-2020 08 21-14_21_15](https://user-images.githubusercontent.com/2930593/90895362-f6f61a00-e3b9-11ea-8393-2701a72cf17b.png)

**Email 2 - to the details in the form:** To: Address in To field; ReplyTo: contact's address; CC: address supplied in CC field BCC: address supplied in BCC field ✅  all correct for the mail sent to the addresses specified

![screenshot-127 0 0 1_8025-2020 08 21-14_24_34](https://user-images.githubusercontent.com/2930593/90895568-476d7780-e3ba-11ea-91c7-b201d61dbede.png)

**Email 3 - to the contact**: To: contact's address;  ReplyTo: not set; CC: not set
BCC: not set ✅  all correct for the mail sent to the contact

![screenshot-127 0 0 1_8025-2020 08 21-14_26_34](https://user-images.githubusercontent.com/2930593/90896549-c1eac700-e3bb-11ea-97ec-cfef76b056e4.png)

**Email 4 - sent to the owner**: To: Owner; From: Mautic instance address (happens to be the same); CC: Not set; BCC:  Not Set ✅  all correct for the mail to the owner

![screenshot-127 0 0 1_8025-2020 08 21-14_38_38](https://user-images.githubusercontent.com/2930593/90896758-155d1500-e3bc-11ea-982a-bc503b863389.png)

## With no options selected in the send form results screen

![screenshot-local mautic31-2020 08 21-14_45_15](https://user-images.githubusercontent.com/2930593/90897381-f27f3080-e3bc-11ea-8f95-2bb0da890fbb.png)

We would expect 
* 1 email sent to the details in the form

### Result: 

**Email 1** - To:  Address in To field; CC: address supplied in CC field BCC: Nothing set ❌  Not sure why this one is being sent

![screenshot-127 0 0 1_8025-2020 08 21-14_46_59](https://user-images.githubusercontent.com/2930593/90897573-3d994380-e3bd-11ea-9602-39515c1f71b8.png)

**Email 2 - to the details in the form:** To: Address in To field; CC: address supplied in CC field BCC: address supplied in BCC field ✅  all correct for the mail sent to the addresses specified

![screenshot-127 0 0 1_8025-2020 08 21-14_47_48](https://user-images.githubusercontent.com/2930593/90897721-7b966780-e3bd-11ea-87d0-8809b4c695f1.png)

## Testing with more than one address in the fields

I thought I would test with more than one address in the address fields as I know there were some PR's about this recently.

### With no options selected 

I get an error thrown:

`[2020-08-21 13:52:24] mautic.ERROR: [MAIL ERROR] Address in mailbox given [] does not comply with RFC 2822, 3.6.2. (bcc) {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [] does not comply with RFC 2822, 3.6.2. at /Users/ruth.cheesley/Sites/local.mautic31/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355)"} []`

###  With all options selected

Email 1 - sent to the contact ✅ 

![screenshot-127 0 0 1_8025-2020 08 21-14_56_48](https://user-images.githubusercontent.com/2930593/90898508-a1703c00-e3be-11ea-8250-593b3ddea337.png)

Email 2: sent to the owner ✅ 

![screenshot-127 0 0 1_8025-2020 08 21-14_57_44](https://user-images.githubusercontent.com/2930593/90898650-c4025500-e3be-11ea-9e27-56ad3680dc6b.png)

Email to the addresses in the form: Nope! Error in the log:

`[2020-08-21 13:55:46] mautic.ERROR: [MAIL ERROR] Address in mailbox given [] does not comply with RFC 2822, 3.6.2. (bcc) {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [] does not comply with RFC 2822, 3.6.2. at /Users/ruth.cheesley/Sites/local.mautic31/mautic/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355)"} []
`

So it looks like the CC/BCC is working but there are extraneous emails being sent with only the CC address, and in the case of using multiple addresses, no email is being sent and an error is being thrown in the logs.

## PR that may be related: 

This may be related to this PR: https://github.com/mautic/mautic/pull/8768

## Issues that might be related:

This issue could possibly be related to https://github.com/mautic/mautic/issues/5967 and maybe https://github.com/mautic/mautic/issues/5967.

**Comment by RCheesley** [comment]
Note: should the replyto be set in the email to the owner? I don't know the answer there!

**Comment by diletecsoftware** [comment]
Hello,
  I updated my information. one installation is performed with SMTP Sendgrid API and the other with SMTP Amazon SES, "both on the same server with the same settings". Both with the same problem in sending the email to the CC, but only with Sendgrid he writes me the error below in the log.

Erro SMTP Sendgrid API
[2020-08-26 17:38:23] mautic.ERROR: [MAIL ERROR] Address in mailbox given [] does not comply with RFC 2822, 3.6.2. (cc) {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [] does not comply with RFC 2822, 3.6.2. at /home/mkt/public_html/mkt.com/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355)"} []

In our settings the Contact Owner does not receive an email due to the ratification of employees in the marketing team, and the contact (lead) receives a personalized email, so the Send to contact option is also disabled (NO) .

Another observation is that even if you activate Send Immediately (Yes), emails are being created in / var / spool and are only launched to SMTP when the send email cron is triggered.

![Edit-Form-Form-Full-Fale-conosco-Mautic](https://user-images.githubusercontent.com/33742238/91359408-e3d4b700-e7ca-11ea-81cd-601ebd1d2be1.png)

**Comment by RCheesley** [comment]
@diletecsoftware is this persisting in the latest 3.2.1 release?

**Comment by npracht** [comment]
Closing for lack of feedback. If more later, we'll re-open the issue.
