### ISSUE TITLE
date_left is not set on page_hits table

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#9113]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

I've noticed date_left in page_hits  is still null on each hit requests. 
This block using a lot of feature like Points action depends on time spent on site.

I've made research and trackingNewlyGenerated is still true

https://github.com/mautic/mautic/blob/8cb3c509a09224fe9c71abe84faebdb69c11c934/app/bundles/PageBundle/Model/PageModel.php#L617 

Property is set here https://github.com/mautic/mautic/blob/8cb3c509a09224fe9c71abe84faebdb69c11c934/app/bundles/PageBundle/Model/PageModel.php#L530 and comming from https://github.com/mautic/mautic/blob/ec67ca60a020930f8bb10b005292780a25281884/app/bundles/LeadBundle/Tracker/DeviceTracker.php#L105 (always true)

Anybody experience with that? 
@escopecz Can you check if date_left is set on your instances?

| Q   | A
| --- | ---
| Mautic version | Mautic 2.16.x
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by escopecz** [comment]
I checked a customer database and date_left is filled in some cases. The date_left is filled backwards by the consecutive page hit for the same session AFAIK.

**Comment by kuzmany** [comment]
I know, It could based on mautic_referer_id set date_left to previous page_hit. But It don't. 
If you have time can you test it (Chrome) - make few page hits with tracking code and check page_hits table If date_left was set. It doesn't work on your side too, then is issue with deviceWasChanged always true.

**Comment by RCheesley** [comment]
@kuzmany wondering if this is still an issue in 3.x?

**Comment by kuzmany** [comment]
Closing
