### ISSUE TITLE
User avatar is broken, bad gravatar request

### ISSUE THREAD

**Issue by niklasfjeldberg** [mautic/mautic#9119]
## Bug Description
The image of the user avatar is broken. The image src is equal to "https://www.gravatar.com/avatar/fd8964708540dfe8edc6b9b16ac108ef?s=250&d=https%3A%2F%2Fmautic.dyfo.no%2Fmedia%2Fimages%2Favatar.png" and shows the error "We cannot complete this request, remote server returned an unexpected status code (503)". I have seen the gravatar future work for contacts before, so I do believe this issue is only for a user avatar. Any ideas about what the problem could be?

| Q   | A
| --- | ---
| Mautic version | 3.1.
| PHP version | 7.3.21
| Browser | Firefox and Chrome

### Steps to reproduce
The issue is always present, and i have no other issues.
 
### Log errors
Nettwork log of browser
400 - https://i2.wp.com/mautic.dyfo.no/media/images/avatar.png?ssl=1
302 - https://www.gravatar.com/avatar/fd8964708540dfe8edc6b9b16ac108ef?s=250&d=https://mautic.dyfo.no/media/images/avatar.png

There are no errors in the log.

**Comment by frankofno** [comment]
had the same issue. In my case port 80/443 were restricted and only accessable for my IP. Make sure to add wp.com with IP 192.0.78.24 to allow access over port 80/443 - as soon as you add an email address to a contact, mautic will check on gravatar.com if this address has an account. If not a host from wp.com will use the avatar in the assets folder on mautic server.

**Comment by RCheesley** [comment]
This is more than likely a server configuration issue (per [this forum thread](https://forum.mautic.org/t/avatar-png/16423)) so I am going to close this issue, please continue support discussions on the forums.

**Comment by samuelfaith** [comment]
Line 64 of CoreBundle/Templating/Helper/GravatarHelper.php contains direct link to default_avatar.png on Mautic.org. I changed it to: '/media/images/avatar.png' which is the local default avatar file. It works.
