### ISSUE TITLE
TLS Handshake error connecting imap 

### ISSUE THREAD

**Issue by NetOldie** [mautic/mautic#9122]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When setting up a fresh mautic installation, there is no further action at this point.
My mail server offers TLSv1.2 and TLSv.1.3. No SSL and no older TLS versions.
The SMTP configuration works fine.

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.3.21
| Browser | Firefox
|OS|Debian Bullseye on VPS

### Steps to reproduce
1. 
2. 
 
### Log errors
Message from IMAP config
Error communicating with the IMAP server: TLS/SSL failure for mail.XXXXX.de: SSL negotiation failed

Entry in my mail.log file:
Aug 25 18:07:07 mx01 dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip={IPv6 - Address}, lip={IPv6 - Address}, TLS handshaking: SSL_accept() failed: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol, session=</HEX5bWttLwqA0AAAAYUZgAAAAAAAAAC>
![Bildschirmfoto von 2020-08-25 18-32-03](https://user-images.githubusercontent.com/64497200/91202012-7f99f080-e701-11ea-84e3-3828a7d2638e.png)

![Bildschirmfoto von 2020-08-25 18-45-42](https://user-images.githubusercontent.com/64497200/91203788-9fcaaf00-e703-11ea-80f1-c13b6d521404.png)
![Bildschirmfoto von 2020-08-25 18-47-17](https://user-images.githubusercontent.com/64497200/91203806-a2c59f80-e703-11ea-8dcc-3ce3ba746631.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by NetOldie** [comment]
In extension of my post:
I turned off the encryption, saved this change, reloaded the page and initiated a test connection. 
It tries to establish a TLS/SSL connection. Unencrypted does not work even for testing.
![Bildschirmfoto von 2020-08-26 07-18-30](https://user-images.githubusercontent.com/64497200/91258707-4e570a00-e76d-11ea-82ac-08f621cf1955.png)

**Comment by RCheesley** [comment]
Hi, sorry to hear you're having problems. I think this is possibly related to an existing issue, have a look at [this comment](https://github.com/mautic/mautic/issues/8484#issuecomment-654815639).

We haven't yet had anyone submit a PR to address this in an elegant way, so I think this is probably why you're having issues. The workaround should work - shout if not and we'll re-open.

**Comment by dikdust** [comment]
Sorry for necropost @NetOldie have you ever solved this problem ? I have solved the smtp part with suggested change but the imap part (I'm using dovecot) still persists. I'm on mautic 2.16.5. Something changed with 3.x version or I will obtain same issue ?
