### ISSUE TITLE
Contacts Link to Company Not updated to View Layout

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#9123]
| Q   | A
| --- | ---
| Mautic version | 3.1.0+

### Steps to reproduce
1. Go to a contact who is assigned to a company.
2. Click on the link on the right side to the company page. It's currently set to the "edit" view instead of the new "view" layout.

![mautic-companylink](https://user-images.githubusercontent.com/41902603/91232617-59874700-e727-11ea-9844-64ab6f44eea3.PNG)

**Comment by RCheesley** [comment]
Good spot - the company 'view' overview was new with 3.1 so it didn't exist before then. Would you like to submit a PR to fix this?

I think you need to dig into this file: app/bundles/LeadBundle/Views/Lead/lead.html.php around [line 598](https://github.com/mautic/mautic/blob/staging/app/bundles/LeadBundle/Views/Lead/lead.html.php#L598).

**Comment by colourfulowl** [comment]
pull request: #9277

**Comment by npracht** [comment]
Fixed in 3.1.2
