### ISSUE TITLE
Base64 and Mautic 3

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#9124]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I've spotted a few weird things going on here. 

1. If you have the append tracking pixel enabled and base64 enable it actually prevents you from sending the email. (Not sure if that's intentional or not as a protection from the auto view bug.)
2. When Base64 is enabled in the updated version, Images aren't loaded at all. It could be a weird migration issue I'm having, but it is affecting 3 different instances of Mautic 3 that I have running. - These were all clean installs, with data and assets, migrated over.  Disabling Base64 fixes the issue and the images do however load.

| Q   | A
| --- | ---
| Mautic version | 3.0.1 - 3.1.0

### Steps to reproduce
1. Enable "Convert embed images to Base64" in the config.
2.  Send an email.
3. Disable Base64, and send the same email.
 
### Log errors
None - strangely.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, thanks for reporting this.

I'm pretty sure we are already tracking this under the following issues: #9069 #9003 #8995

Let me know if you think this is something unrelated to those three issues please, otherwise let's close this and keep the conversation in one place :)

**Comment by colourfulowl** [comment]
I must be going blind in my old age 🤣 #9069 Hits the nail on the head. 

Closed in favour.

**Comment by DASAT** [comment]
I have the same problem.
If I turn on Base64 pictures don't show up in the emails. "Can not open file image.jpg" 
Any work arround?
Thanks
