### ISSUE TITLE
Focus item from campaign not working

### ISSUE THREAD

**Issue by javiergas** [mautic/mautic#9125]
## Bug Description
When inserting a focus item form a campaign in a related site using CORS and tracking code, a 404 error is generated because the Focus item script is inserted form the related site instead of the Mautic Site.

For this example:

Mautic site : HELLO2.xxxxx.com
Related site: WWW.xxxxx.com

![image](https://user-images.githubusercontent.com/30293899/91238591-69912d80-e70b-11ea-934c-c1d02cc01a74.png)

![image](https://user-images.githubusercontent.com/30293899/91238187-75302480-e70a-11ea-96ae-3f842196b297.png)

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.2.24-0ubuntu0.18.04.6
| Browser | Google Chrome 84.0.4147.135

### Steps to reproduce
1. Configure CORS to allow communication with the related site
2. Insert Mautic's tracking code in the related site
3. Configure campaign to show a focus item
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by javiergas** [comment]
I temporary fixed it by replacing

MauticJS.insertScript(e[i]['js']);
for
MauticJS.insertScript(MauticDomain+e[i]['js']);

in 
/app/bundles/PageBundle/EventListener/BuildJsSubscriber.php #581

**Comment by javiergas** [comment]
The bug is still present in version 3.1.1

**Comment by RCheesley** [comment]
Hi there, please share your CORS setting? I would think this is most likely to be because a domain is missing from the configuration but can't be sure without knowing exactly what's in your CORS settings.

**Comment by javiergas** [comment]
Hi Ruth,
![Screenshot_1](https://user-images.githubusercontent.com/30293899/95585052-0b977b80-0a15-11eb-9be1-a33ef4bf5095.png)

It was working fine with the same configuration before version 3.x.x.

Thanks!

**Comment by javiergas** [comment]
Hi Ruth,
Do you need more feedback?

**Comment by javiergas** [comment]
I tried with 3.1.2 and the problem is still there

**Comment by javiergas** [comment]
Still the same in 3.2.1
Am I the only one experiencing this issue?

**Comment by RCheesley** [comment]
Hi @javiergas, pretty sure that this has to be something to do with your focus item / website CORS settings rather than a bug with Mautic.

Your focus item URL seems to not be from your Mautic instance (hello2.example.com) but from your domain (example.com), according to the screenshot here: https://user-images.githubusercontent.com/30293899/91238591-69912d80-e70b-11ea-934c-c1d02cc01a74.png

The focus item script URL should be from your Mautic instance, not from your website.

EG my mautic instance is mautic.example.com the script would be:

<script src="//mautic.example.com/focus/1.js" type="text/javascript" charset="utf-8" async="async"></script>

**Comment by javiergas** [comment]
Hi @RCheesley
This focus item is meant to be displayed in a wordpress site integrated with the Mautic Plugin for Wordpress and it was working perfectly before updating to Mautic 3.0.

I also tested it with a fresh Mautic 3 installation and the problem is the same.

I was able to fix it making this change in /app/bundles/PageBundle/EventListener/BuildJsSubscriber.php #581
```
MauticJS.insertScript(e[i]['js']);
for
MauticJS.insertScript(MauticDomain+e[i]['js']);
```

This change must be done every time I update my Mautic installation.

In reviewing the sourcecode I got to the same conclusion that is a CORS problem in Mautic 3 which generates this behavior. 

Best
Javier

**Comment by RCheesley** [comment]
OK let's see if anyone else has this issue.

Are you able to deploy the focus items without using a campaign (e.g. directly on the page) or does that also cause a problem?

**Comment by javiergas** [comment]
@RCheesley in that case it works fine using the JS for the specific focus item.

**Comment by simcen** [comment]
I actually came across the exact same issue.

I'll try to submit a bugfix.

@RCheesley The use case is to display the focus item via campaign action and not by adding the focus snippet directly into the website.

**Comment by Robmobius** [comment]
Problem persist in 3.3.4 and 4.1 

Tried @javiergas suggested code edit but no joy for me.
