### ISSUE TITLE
Campaign condition 'Has valid email address' always returning positive.

### ISSUE THREAD

**Issue by evgu** [mautic/mautic#9131]
## Bug Description
Campaign condition 'Has valid email address' always returning positive results, regardless if the email address is valid or not. Several tests were attempted with invalid WHOIS, non-existent MX DNS record, and nonexistent email account (on a valid domain with valid MX record)

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3.21
| Browser | Safari 13.1.2

### Steps to reproduce
1. Create a test campaign, with a 'test segment'. (see example screenshot). 
2. Add  'Has valid email address' condition to campaign.
3. Wire up +5/-5 contact points, to be able to test. 
4. Add a contact with correctly formatted email address but with non-existent domain - e.g. test@test123testinvalid.com 
(verify domain has no WHOIS record by using an online WHOIS tool). 
5. Update contact points to 100, so points can be subtracted from.
6. Add contact to test segment / or to test campaign. 
7.  Observe condition 'Has valid email address' always returning positive results. See the contact's history log and the contact points wrongly increasing. 

<img width="502" alt="Screenshot 2020-08-26 at 15 32 47" src="https://user-images.githubusercontent.com/18371928/91310493-3b1a5d80-e7b2-11ea-83f8-98a1541d5592.png">
 
### Log errors
None observed in Mautic or apache log files.

**Comment by evgu** [comment]
- Related Issues: #9023 #7904
- Suggested solution: 
in `Mautic\EmailBundle\EventListener\CampaignConditionSubscriber::onCampaignTriggerCondition`
when calling `validate()`, pass `true` as the second ($doDnsCheck) parameter, as it is defaulted to `false` in the function's definition. 

e.g. update code to  `$this->validator->validate($event->getLead()->getEmail(), true);`

**Comment by evgu** [comment]
PR #9144 is for staging branch. Let me know if PRs are needed for 3.0 and 3.x branches as this issue seems to be present there as well?

**Comment by RCheesley** [comment]
Hi @evgu this was fixed in #9215 - the 3.1 branch is used for bug fix releases and Staging is used for feature releases. The 3.1 branch is merged up into staging after each release. So we should be good to go as this issue should now be addressed :)
