### ISSUE TITLE
Mautic 3.1 Bounce Chart not updating

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#9136]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The chart on the emails doesn't show the number of bounces. I think this is a legacy bug as I've never actually had this work.

| Q   | A
| --- | ---
| Mautic version | 3.0.1 - 3.1.0

### Steps to reproduce
1. Send an email that bounces - I'm using Amazon SES and SNS.
2. Email successfully bounces, but the email chart doesn't show how many bounced from that email.
 
![mautic-bounce-chart](https://user-images.githubusercontent.com/41902603/91326892-c7318280-e7bc-11ea-915e-b70afa452ed6.PNG)

**Comment by colourfulowl** [comment]
Just to add to this. When viewing the email data in the report view it produces null in the chart.

![mautic-bouncereport](https://user-images.githubusercontent.com/41902603/91327099-052ea680-e7bd-11ea-8306-f3a87fa8a9c5.PNG)

**Comment by wise-gorilla** [comment]
If you are using SES SMTP then you probably didn't check those 2 checkboxes
![image](https://user-images.githubusercontent.com/65309837/91477942-5fa03380-e89f-11ea-8451-fd6d52277050.png)

Please note that tracking the bounce dont work with SES API and i dont think there is anyway to get it to work, the reason for that is that normally Mautic send a custom email header called X-EMAIL-ID which is the email id to the mailing service (SES), and then SNS send a callback to Mautic that includes the email headers but unfortuinatly the method used to send emails via ses (Templated emails) doesn't support custom headers which mean that when Mautic receive a callback from SNS it will not know for which email is that callback.

The only way i can think about to solve that issue and also enable the use of custom headers is to use SES SendRawEmails method but i think it will not be as fast as the currently used method

**Comment by mabumusa1** [comment]
@Wise-Gorilla this brings us back to the original discussion where we said `SendRawEmails` is the one that should be used. Although `SendEmail` with templates sends to up to `50` at a single API call, we lose a lot of valuable information and headers like this is one of them.

Let's start thinking of `SendRawEmails` instead

**Comment by colourfulowl** [comment]
@Wise-Gorilla  All of the settings inside of SES are as they should be. What I did notice is that email that was previously sent in version 2.16 that bounced, now do show up in the chart correctly. But anything after 3.0 do not. Bit of a weird one :/

**Comment by wise-gorilla** [comment]
@colourfulowl This PR #9150 should fix that issue, but atm API only works with Send immediatly not queue.

**Comment by ziedMauticMecanik** [comment]
to find emails opened and sent and clicks, and bounces, I found an API:
$events = $contactApi->getActivity($search, $includeEvents, $excludeEvents, $orderBy, $orderByDir, $page, $dateFrom, $dateTo);
how can I filter events from campaign_id or email_id in the $search variable? and what should I write in this variable?

**Comment by RCheesley** [comment]
@colourfulowl was this issue resolved with the updates to the SES API integration / bounce that we pushed in recent releases?
