### ISSUE TITLE
Amazon SES API not working

### ISSUE THREAD

**Issue by javiergas** [mautic/mautic#9137]
The more details the better...

Hi,
Amazon API email test works fine, but it's not working for a real mass email.

When email is set to Send Immediately I get and error in the log:
mautic.ERROR: [MAIL ERROR] Token amount (51) is larger than the capacity (14). (send); XXX@XXX.COM, ...

When email is set to Queue I get and error in the console when excuting:
php ./bin/console mautic:emails:send
In AmazonApiTransport.php line 195: Attempted to call an undefined method named "getAttachments" of class "Swift_Message".

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.2.24-0ubuntu0.18.04.6
| Browser | Google Chrome 85.0.4183.83 (Official Build) (64-bit)

### Steps to reproduce
1. Configure Amazon API
2. Create and send a New Segment Email (I used a segment with 630 contacts)
 
### Log errors
mautic.ERROR: [MAIL ERROR] Token amount (51) is larger than the capacity (14). (send); XXX@XXX.COM, ...
In AmazonApiTransport.php line 195: Attempted to call an undefined method named "getAttachments" of class "Swift_Message".

**Comment by wise-gorilla** [comment]
@javiergas I think you can temporarly fix that untill the release of the next Mautic version by editing line 631 of AmazonApiTransport.php and change
`return 50;`
to
`return (50 > $this->concurrency) ? $this->concurrency : 50;`
Let me know if this worked for you

**Comment by dctechnoIn** [comment]
Same issue .. after update 3.0.1 to 3.1  .. Adding as suggested

**Comment by dctechnoIn** [comment]
no, Not working -

 In AmazonApiTransport.php line 195:

  Attempted to call an undefined method named "getAttachments" of class "Swift_Message".

**Comment by dctechnoIn** [comment]
mautic.WARNING: Command `mautic:emails:send` exited with status code 1 [] []

Send Email not working with SES API

**Comment by dctechnoIn** [comment]
SMTP - working fine - FYI

**Comment by javiergas** [comment]
SMTP working fine for me too

**Comment by dctechnoIn** [comment]
mailer/amazon/Callback giving 400 Error - after update

**Comment by wise-gorilla** [comment]
If you set the sending option to "Send immediatly" instead of queue and changed the line #631 i mentioned above this should solve the problem.

Will fix that on the next Mautic release

**Comment by RCheesley** [comment]
Bumping this issue back to 3.1.2 as we did not have time to address it fully before the release freeze.

**Comment by StoppingBuck** [comment]
> If you set the sending option to "Send immediatly" instead of queue and changed the line #631 i mentioned above this should solve the problem.
> 
> Will fix that on the next Mautic release

What if we need to use the Queue option due to large sendouts?

**Comment by wise-gorilla** [comment]
@StoppingBuck atm the queue dont work with SES API, Did you try to apply this PR #9150 and send a large campaign and it failed?

**Comment by benfavre** [comment]
FYI I am using "send immediately" and broadcast:send and I am using this to send 200K messages a day with no issues.
I had to slow down the processing because I was over 200 messages/seconds limit on my account

**Comment by wise-gorilla** [comment]
> FYI I am using "send immediately" and broadcast:send and I am using this to send 200K messages a day with no issues.
> I had to slow down the processing because I was over 200 messages/seconds limit on my account

@benfavre do you mean that you changed the getMaxBatchLimit() to 200 instead of 0?, I think you dont need to do that since the transport should detect your sending limits automaticly and do the proper throtling

**Comment by chescos** [comment]
Experiencing the same issue here. Thanks for working on this? Is this still scheduled to be fixed in 3.1.2?

**Comment by benfavre** [comment]
```php
        $message .= "\n--$separator_multipart\n";
        $message .= "Content-Type: text/html; charset=\"UTF-8\"\n";
        $msg['html'] = str_replace(['<table'], "\n<table", $msg['html']);
        $message .= "\n".$msg['html']."\n";
```

I've had to add this to make sure my clients don't send huge one liner emails and exceed line lengths allowed by mail clients

**Comment by npracht** [comment]
Did you test https://github.com/mautic/mautic/pull/9290 ?

**Comment by npracht** [comment]
closing in favor of https://github.com/mautic/mautic/issues/8903
