### ISSUE TITLE
Email link not tracking

### ISSUE THREAD

**Issue by Spinnenfrau** [mautic/mautic#914]
Hello,

i worked at this tutorial: 

https://www.mautic.org/blog/creating-a-double-opt-in-email-campaign/

But it not working! 

I don't use mautic as a selfhosting Newsletter. I used mautic.org

I try a couple of scenarios. All working! Why? 

I put after the send opt-in link to the opt-in page, a change the lead to the newsletter list.

And in the second Campaine i do my autoresponder, with 3 mails, 1. after 2 min. 2. after 5 min. 3. after 10 min. 

Now the user signup. Than he get the confirmation mail. He click on the confirmation link. Ok it works.

But it's not tracking. The user, don't switch from pending to confirm list. But he get the newsletter mails. But is still in the pending list.

What i do wrong?

![mautic](https://cloud.githubusercontent.com/assets/14358826/9975611/1e9604c6-5ec2-11e5-9b0d-19837e2cf42d.jpg)
![mautic2](https://cloud.githubusercontent.com/assets/14358826/9975616/4f524ac0-5ec2-11e5-8e1b-da950939348a.jpg)

**Comment by alanhartless** [comment]
Hi!

This is better suited for the community forums at https://mautic.org/community or maybe Slack at https://mautic.org/slack.  Github issues is reserved for feature requests and/or confirmed bugs; not support in general.

Thanks for your understanding as we try to keep communication organized!
