### ISSUE TITLE
base url does not refresh in form action

### ISSUE THREAD

**Issue by 410Gone** [mautic/mautic#9140]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | V3.0.3
| PHP version | 7.3.21-1+ubuntu18.04.1+deb.sury.org+1
| Browser | Chrome and edge (but doesn't matter in this case)

### Steps to reproduce
1. Have a mautic instance with a base url like https://ndd.com (without www.)
2. Create a form  components
3. Look at the html suggested in the manual copy option in the form. (look specificaly at the form action which integrate the base url without the www. till this time, all is ok)
4. Change the base url of mautic in system configuration general setting Site URL (add the www.)
5. Perform a cache:clear in command line
6. Look at the html suggested in the manual copy in the same form than step 3, the form action doesn't include the www in the base domain url.

Please note that if you open and save the form again it fix the problem. But can be hard if you perform it after lot's of form already created
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by colourfulowl** [comment]
This may be fixed by selecting the forms are rebuilding the cache. 

![mautic-rebuildformcache](https://user-images.githubusercontent.com/41902603/91458110-0d4e1b00-e87d-11ea-9b87-d613abcec803.PNG)

Please give the above a try and let us know if it works or not. If that does work, then the issue here is that the cache clear command isn't rebuilding the forms cache.

**Comment by 410Gone** [comment]
honestly i'm beginer on mautic and I didn't know this rebuild cache option.
That's why i directly try the clear:cache commande
So we may dedut that the clear:cache command doesn't clear "this" form cache no ?

**Comment by mabumusa1** [comment]
@410Gone did things work out for you?

**Comment by 410Gone** [comment]
I'm not able to test it again, (i was just signaling a problem i had to help futur bug fix)
It cas easily reproduced, and according to what i told, the clear cache command didn't clear this specific cache. 

Hope it'll help.

**Comment by RCheesley** [comment]
OK let's close this issue down as it seems like the form cache was not cleared.
