### ISSUE TITLE
Campaigns are gone after enabling the mail Queue Delivery option

### ISSUE THREAD

**Issue by cardillos** [mautic/mautic#9147]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
We updated how should email be handled from Immediate delivery  to Queue delivery  as per this doc https://docs.mautic.org/en/channels/emails
After this, a number of campaigns, emails and segments were gone. Also one of the app user says that the email she just created was gone. 2 users who were created in the last 2 weeks were also missing from the user area. It seems items worked on or created in the last 2/3 weeks have gone.

| Q   | A
| --- | ---
| Mautic version |  2.15.3
| PHP version | v7.0.3
| Browser |  Google Chrome

### Steps to reproduce
1.  Change option from  Immediate delivery  to Queue delivery 
2. 
 
### Log errors
 mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\EntityNotFoundException: "Entity of type 'Mautic\LeadBundle\Entity\LeadList' for IDs id(123) was not found" at /var/www/vhosts/mautic.zeald.com/httpdocs/vendor/doctrine/orm/lib/Doctrine/ORM/EntityNotFoundException.php line 47 {"exception":"[object] (Doctrine\\ORM\\EntityNotFoundException(code: 0): Entity of type 'Mautic\\LeadBundle\\Entity\\LeadList' for IDs id(123) was not found at /var/www/vhosts/mautic.zeald.com/httpdocs/vendor/doctrine/orm/lib/Doctrine/ORM/EntityNotFoundException.php:47)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi @cardillos, sorry to hear you're having problems. We no longer support the 2.x version of Mautic, so please raise your issue at https://forum.mautic.org/c/support where you may be able to get some help with troubleshooting.

Unfortunately it's a long way out of date now and there have been a lot of fixes since 2.15.3 so it might be quite tricky to track down.
