### ISSUE TITLE
SAML entity ID will not updating on mautic_url change.

### ISSUE THREAD

**Issue by rez0n** [mautic/mautic#9148]
## Bug Description
I've run clean Mautic in Docker with default URL `localhost`, then I change URL in the app/config/local.php and set the environment variable `MAUTIC_URL` and changed Site URL in the "System Settings", restarted everything but anyway I have `http://localhost` on the "SAML SSO Settings" page.
![image](https://user-images.githubusercontent.com/725860/91564720-b5311a80-e949-11ea-8495-ff66a4fa3fdc.png)

![image](https://user-images.githubusercontent.com/725860/91564599-8450e580-e949-11ea-864a-58fee9c6f0b9.png)

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3
| Browser | Any

### Steps to reproduce
1. Run Mautic using default URL `http://localhost`
2. Change domain 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by mabumusa1** [comment]
@rez0n did you clear cache after the change?

**Comment by Frankniesten** [comment]
I have the same problem. Clearing the cache is not working. I solved it temporarily by changing the 'saml_idp_entity_id' parameter in the app/config/local.php file.

**Comment by stenioanibal** [comment]
Same problem here. I fix it using the @Frankniesten alternative solution. When I update the URL, does not change this.

**Comment by mabumusa1** [comment]
@rez0n @stenioanibal that is correct they are two independent parameters that get created during the setup, so changing the URL will not change the `saml_idp_entity_id`. I will mark this is a feature request to be implemented.

**Comment by jenshine** [comment]
What's the repercussion of this parameter not getting updated with the actual domain? Thx.
