### ISSUE TITLE
Bounce does not work

### ISSUE THREAD

**Issue by jrmarins** [mautic/mautic#9149]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
After updating to version 3.0.1 Mautic stopped correctly marking Bounce, the treatment is done, the tag appears in the contact list, but nothing appears in the contact's register and the follow-up does not list it.

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.2
| Browser | Any

### Steps to reproduce
1. Register a non-existent email and run cron `mautic:email:send`
2. Run the cron `mautic:email:fetch`
 
### Log errors
none

Listing:
![image](https://user-images.githubusercontent.com/11929307/91578698-ec3f0600-e920-11ea-9609-c5db9a8732ef.png)

Registration screen:
![image](https://user-images.githubusercontent.com/11929307/91578852-24464900-e921-11ea-953b-8776ef624f5d.png)

**Comment by mabumusa1** [comment]
@jrmarins please send more details regarding your configuration, is the cron job working as expected? do you see anything in the logs?

**Comment by jrmarins** [comment]
Hi, @mabumusa1! Thanks for answering.

No log is generated and the cron is working perfectly.
The contact is marked as Bounce, Mautic stops sending e-mail to him, but the segment that lists the bounce does not seek this contact and in his registration is not marked as bounce in the icon below the contact's photo.
The normal dialing appears in the contact list.

Contact list:
![image](https://user-images.githubusercontent.com/11929307/91722767-1e46a700-eb71-11ea-8be2-ea67492b62ff.png)

Contact Screen:
![image](https://user-images.githubusercontent.com/11929307/91722873-47673780-eb71-11ea-9f77-0f174f23bdf8.png)

**Comment by jrmarins** [comment]
Hi, @mabumusa1! Thanks for answering.

No log is generated and the cron is working perfectly.
The contact is marked as Bounce, Mautic stops sending e-mail to him, but the segment that lists the bounce does not seek this contact and in his registration is not marked as bounce in the icon below the contact's photo.
The normal dialing appears in the contact list.

Contact list:
![image](https://user-images.githubusercontent.com/11929307/91757532-d6da0e00-eba4-11ea-9046-eea04f211c42.png)


Contact Screen:
![image](https://user-images.githubusercontent.com/11929307/91757555-e48f9380-eba4-11ea-9e3f-e54c16db8e48.png)

**Comment by StoppingBuck** [comment]
I believe this might be related to #9175 , since bounces are normally set by reason=2 in the `lead_donotcontact` table, and that logic is broken in a number of places in M3.

**Comment by jrmarins** [comment]
Hi, @StoppingBuck.
Thanks for answering!
I was using the monitored inbox, but as I couldn't find a solution to this problem I ended up switching to the option for webhook (https://docs.mautic.org/en/channels/emails/bounce-management#amazon-webhook) and now everything works.

I will keep it that way and finalize this issue.

**Comment by TnowL** [comment]
I have reported this before. https://github.com/mautic/mautic/issues/9004

**Comment by swaraj02** [comment]
> Hi, @StoppingBuck.
> Thanks for answering!
> I was using the monitored inbox, but as I couldn't find a solution to this problem I ended up switching to the option for webhook (https://docs.mautic.org/en/channels/emails/bounce-management#amazon-webhook) and now everything works.
> 
> I will keep it that way and finalize this issue.

Is your bounce segment getting updated? I am using Sendgrid webhook but it's not working for me.
