### ISSUE TITLE
Wrong Order in Lead-Log - simple to fix and brings much prouducitvity by analyzing

### ISSUE THREAD

**Issue by CyberMarsl** [mautic/mautic#9152]
## Bug Description
Looking at the Lead´s log in Mautic backend (Leads) -> Contact has a confused log, as the order of the entries is not proper waht makes campaign analyzing harder and costs unnecessary much time and brain power.

Lets say we have a Campaing performing Like

   A1 - Campaign Trigger
   A2 - Set Segment Pending
   A3 - Check if condition matches 
   A4 - Since A2 matches, we send out an email
   A5 - Now we wait for Confirm Page clicked
   A6 - Since Page is now confirmed, we change segment to confirmed
   A7 - we remove the segment pending

(I make A6 and a7 2 steps just for this example, althought it can be done in one step it´s only a example to describe the problem).

So then the order in the Lead Log should be:

 A7-A6-A5-A4-A3-A2-A1

but the Order in this case would be:
  
  **A5**-A6-A7-**A1**-A2-A3-A4

So the problem seems to be to have two different ways of logging: ascending and descending
Generaly the batchesare descending, but inside the batch itself is ascending.

A simple solution could be reverse the order of the log entries inside the batches.
Another solution if you would like to keep the order as is for some reason, then there should be a Horizontal Line inbetween each batch of log entries, i.e. like this but in better format:
 <hr />

Another suggestion is to include the Seconds in the execution time what also clariyfies the order, because if I have more batches within 1 minute, the action time seems to be the same.

| Mautic version | 3.1.0 (but I think it is at least since 2.x or longer)
| PHP version | 7.3.21
| Browser | Any

### Steps to reproduce
1. Create a Campaing with pauses inbetween steps and multiple activites inside each step, 
   .E. 3 Action/Decisions -> WaitForEvent -> Next 3 Actions/Decisions -> Wait for another Event -> Next 3 Actions/Decisions
2. Start the Campaing an perform the events waiting for so it runs through all steps but needs multiple camaping tirggering (console m:c:t)
 
### Log errors
No error in the Log file, but a wrong mixed order in lead log.

**Comment by RCheesley** [comment]
Thanks for raising this @CyberMarsl - I can see how that would be confusing! Thinking out loud, I wonder if it might be a better option to nest the related items rather than have them all listed out?

Would you be up for creating a PR to look at addressing the issue?

**Comment by ttencate** [comment]
Related to #8309?

**Comment by RCheesley** [comment]
@CyberMarsl are you up for creating a PR to address this issue?

**Comment by dsp76** [comment]
Wouldn't a more accurate timestamp fix the issue right away? It looks like its only tracking by minute and thus within a minute a lot of actions may happen. Then its sorted by some second characteristics and its getting messed up in order.
