### ISSUE TITLE
Segments are not getting populated with the contacts

### ISSUE THREAD

**Issue by himanshuinboundmantra** [mautic/mautic#9155]
I am trying to create segments in my Mautic account but it is not populating.

I have created a **[video](https://www.loom.com/share/767ea1e30b2e493791f1c31a060f7745)** explaining the complete issue and what I did to solve it but still not get the achievement, pls help :(

**Comment by wise-gorilla** [comment]
console is inside bin folder not in app folder, you need to change the cron path, that path got changed on Mautic 3.0
