### ISSUE TITLE
Bug: When using Amazon SES API, Amazon SNS callback returns 404

### ISSUE THREAD

**Issue by darkogj** [mautic/mautic#9159]
Type: Bug
Mautic version: 3.1
PHP Version: 7.2
Email sending method: Amazon SES API
HTTPS: Enabled

Problem: I'm using the Amazon SES API. I'm trying to connect to Amazon SNS (creating a topic, and then a subscription) but the status is stuck as "Pending confirmation". I've turned on CloudWatch and the error is:

`
{
    "notification": {
        "messageId": "fdacbca2-c1c1-4316-bb64-607abad3fd2c",
        "topicArn": "arn:aws:sns:us-west-2:084549634276:bnc-hrs1",
        "timestamp": "2020-09-01 18:08:19.483"
    },
    "delivery": {
        "deliveryId": "e23650c8-8f2f-52c7-a6a2-07001f7c71e3",
        "destination": "http://site.com/mailer/amazon/callback",
        "providerResponse": "Not Found",
        "dwellTimeMs": 313,
        "attempts": 1,
        "statusCode": 404
    },
    "status": "SUCCESS"
}
`

I've also tried to access mysite.com/mailer/amazon/callback as a logged-in user. and got a 404 error

Steps to reproduce:

Just install Mautic 3.0, upgrade to 3.1, install/configure certbot. configure Amazon SES API and try to configure Amazon SNS. I have bot http and https versions enabled, and tried to create a subscription with bot http and https, but none worked.

A similar problem by another guy was [reported on the Mautic community forum](https://forum.mautic.org/t/3-1-0-ses-api-working-but-not-sns-404-worker-amazon-callback/15832)

This seems to be an issue when you're using the newly released Amazon SES API.

**Comment by mabumusa1** [comment]
@darkogj please try with `mailer/amazon_api/callback` this should be the right callback for SES API

**Comment by Av1dLearner** [comment]
Please update docs @RCheesley with new callback URL
https://docs.mautic.org/en/channels/emails/bounce-management

**Comment by RCheesley** [comment]
@Av1dLearner we would welcome a PR to update it. Please click on the edit button at the bottom of the page, and you'll be taken directly to the file you need to modify in the documentation. Many thanks!

**Comment by Av1dLearner** [comment]
Sorry, I don't think I'm skilled or qualified to do that
> @Av1dLearner we would welcome a PR to update it. Please click on the edit button at the bottom of the page, and you'll be taken directly to the file you need to modify in the documentation. Many thanks!
