### ISSUE TITLE
500 Internal server error when updating Contact fields

### ISSUE THREAD

**Issue by pandeynandancse** [mautic/mautic#9163]
Whenever I try to edit contact form field except some fields like title, firstname , lastname, address,  email and mobile number, it gives the error 500.

Currently I have tried to update fields such as  whatsapp_sent, survey, contact_added_by but it served me error.
How to resolve this.
Also When I tried to update it with api , it didn't worked .

Thanks in advance..

**Comment by npracht** [comment]
Please fulfil the issue template given by the community. We miss your version, how to reproduce, etc.
I'll reopen once the issue is complete.
