### ISSUE TITLE
Filter not showing all available categories in "Contact Preference Center"

### ISSUE THREAD

**Issue by introfini** [mautic/mautic#9165]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The "My categories" in "Contact Preference Center" doesn't show all available global categories, it's limited to only 10.

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3
| Browser | Firefox

### Steps to reproduce
1. Add more than 10 global categories.
2. Try to change the user subscribed categories in "Contact Preference Center"
3. Only 10 categories are available to select.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by introfini** [comment]
**The fix is:**

On `app/bundles/LeadBundle/Form/Type/LeadCategoryType.php`

From:
` $categories = $this->categoryModel->getLookupResults('global');`
To
`$categories = $this->categoryModel->getLookupResults('global', null, 0);`

**Comment by npracht** [comment]
PR is here https://github.com/mautic/mautic/pull/9176

**Comment by introfini** [comment]
@npracht that PR doesn't have the fix for the Contact Preference Center, just for segments.

I think the fix must be done also in app/bundles/LeadBundle/Form/Type/LeadCategoryType.php

**Comment by RCheesley** [comment]
@introfini would you be up for creating the PR to address this? We have some guidelines on getting started with creating PR's here: https://contribute.mautic.org/contributing-to-mautic/developer - shout if you need any help!
