### ISSUE TITLE
Syncing IDs in Pipedrive Connector results in silent error

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#9166]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When the Pipedrive contact ID is mapped to a field in Mautic, it causes sync failures without any meaningful detail in the logs. 

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.4
| Browser | Chrome/Mac (current)

### Steps to reproduce
1. In the pipedrive plugin configuration, map the Pipedrive contact ID to a field in Mautic
2. Create a contact in Mautic
2. Create a campaign in Mautic
3. Include a campaign action step to push the contact to integration and select Pipedrive
4. Review contact activity log
 
### Log errors
This is the only error that comes up and it's not helpful :(
<img width="591" alt="Screen Shot 2020-09-03 at 9 41 26 AM" src="https://user-images.githubusercontent.com/866855/92130252-21889f80-edca-11ea-9db8-7bf9b9715b31.png">

The Mautic log itself is empty. 

There is an error produced by Guzzle, but because of a try/catch it never surfaces to the user:
`Inserting ID with POST request is not allowed. If you have any questions, please contact Piped (truncated...)`

### More Detail
I see this as two separate bugs:
1. the plugin cannot handle mapping the ID field, despite offering it as an option for mapping
2. The error produced by guzzle never makes it to the user, so if this were actually user error, the user wouldn't know what they did wrong.

I was able to get it to work by editing /plugins/MauticCrmBundle/Integration/Pipedrive/Export/LeadExport.php and simply adding the line unset($mappedData["id"]); just inside the try at line 58 before it tries to send the mappedData to Pipedrive.

I think there may be a more elegant solution, so rather than post a PR, I'm creating this bug report as a better description of the issue I discovered in issue #9166 

It is unclear if the issue will also happen if the company ID field is mapped, though I suspect the same bug exists there as well.

**Comment by npracht** [comment]
Hi @stevedrobinson, are you sure the contact has data in all required field in your Pipedrive ?

**Comment by stevedrobinson** [comment]
I have an update. I was able to get the raw error from Guzzle:

`Inserting ID with POST request is not allowed. If you have any questions, please contact Piped (truncated...) `

This makes sense, since we map the pipedrive id back to Mautic to make it easy to use it in tokens in alerts to the team. 

I was able to get it to work by editing /plugins/MauticCrmBundle/Integration/Pipedrive/Export/LeadExport.php and simply adding the line `unset($mappedData["id"]);` just inside the try at line 58 before it tries to send the mappedData to Pipedrive. 

I'm not sure this is the most elegant solution and I'm not set up to post a PR so I'm hoping someone else can take this and run with it. If not, i'll circle back when I have more time and a proper dev environment set up.

**Comment by RCheesley** [comment]
Thanks for reporting back @stevedrobinson - hopefully we should be able to dig into it in a bit more detail with your findings!

**Comment by stevedrobinson** [comment]
@RCheesley I opened a clearer issue as #9648. I May have some developer resources to throw at this issue shortly and wanted something clean and clear to provide the developer.

**Comment by kuzmany** [comment]
@stevedrobinson ID could be used just to pull to Mautic, not to push to Integration.

**Comment by RCheesley** [comment]
@stevedrobinson please can you post the detail above in the existing issue so that we can keep everything together? Otherwise we are duplicating the work/effort and things could easily get missed or two people could try to work on fixing the same thing,

I will close this issue and label it as a duplicate of the existing one.

**Comment by RCheesley** [comment]
Please update this issue @stevedrobinson rather than creating a duplicate.

**Comment by stevedrobinson** [comment]
@RCheesley Updated this one. I apologize for taking the wrong action. 

@kuzmany I do not understand your comment. Are you suggesting a code change or a configuration change to make IDs sync only one way. The Pipedrive connector is a two-way sync, automatically, and does not have the sync direction arrows in the UI:

![image](https://user-images.githubusercontent.com/866855/107702173-77b61480-6c7f-11eb-9fe6-c5c36e7e9ec7.png)

**Comment by RCheesley** [comment]
> @RCheesley Updated this one. I apologize for taking the wrong action.

No probs at all ! Thanks for updating the issue :)

**Comment by stevedrobinson** [comment]
This is still an issue, but I think I have a quick fix I can post as a PR.

**Comment by cofundhub** [comment]
Same issue with sugar plugin -- mapping the field mauticcontactid results in system error.

**Comment by kuzmany** [comment]
This should fixed it https://github.com/mautic/mautic/pull/10283
