### ISSUE TITLE
Allow to override curl settings in AbstractIntegration with PluginIntegrationRequestEvent

### ISSUE THREAD

**Issue by Z0zol3** [mautic/mautic#9167]
Hi everyone,

I've got an issue on a server, which is using SSL Certificates not included in Mozilla bundle (the default ones included in Http Component) and a third party integration which doesn't allow any kind of modifications before sending out requests.

I've found a event called PluginIntegrationRequestEvent in AbstractIntegration->makeRequest which would be perfect to fix this issue with a plugin. 

My problem is the only thing I can alter at this point is only headers and parameters. 

I would only need to set 'curl.certpath' (Joomla\Http\Transport\Curl) to an empty strink for it to work. 

Would it be possible to add `$settings= $event->getSettings();` in AbstractIntegration->makeRequest (line 802 in 3.0.0-beta2)?

**Comment by Z0zol3** [comment]
I added a commit for this here https://github.com/mautic/mautic/commit/dd5175119f5a9891fd1951f34974092ad6592420

**Comment by npracht** [comment]
Can you create a pull request with this commit ?

**Comment by Z0zol3** [comment]
#9177

**Comment by Z0zol3** [comment]
also #9178 for 2.16

**Comment by npracht** [comment]
we don't support enhancements for 2.x anymore ;)

**Comment by Z0zol3** [comment]
Ok, I'll keep in mind for the future.

**Comment by RCheesley** [comment]
@Z0zol3 please can you sign the contributors agreement and take a look at the codestyle fix that is required on the PR? If we don't hear from you on these we'll close the issue and PR due to inactivity. Thanks!
