### ISSUE TITLE
Segment Filter "Subscribed Categories" not showing all available categories if > 10

### ISSUE THREAD

**Issue by introfini** [mautic/mautic#9169]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Segment Filter of type "Subscribed Categories" not showing all available categories , it's limited to only 10.

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3
| Browser | Firefox

### Steps to reproduce
1. Add more than 10 global categories.
2. Add the filter "Subscribed Categories"
3. Only 10 categories are available to select.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by introfini** [comment]
The fix is:

On app/bundles/LeadBundle/Form/Type/ListType.php, line 116.

From:
$categories = $categoryModel->getLookupResults('global');

To:
$categories = $categoryModel->getLookupResults('global', null, 0);

**Comment by npracht** [comment]
@introfini can you test https://github.com/mautic/mautic/pull/9176 and add your review ?

**Comment by introfini** [comment]
> add your review ?

Done!

**Comment by mabumusa1** [comment]
Closing inf favor of https://github.com/mautic/mautic/pull/9176
