### ISSUE TITLE
When you click on email builder, you cant do anything, the page is broken.

### ISSUE THREAD

**Issue by hassancs91** [mautic/mautic#9171]
## Bug Description
Hi, there is a bug in the latest mautic version (3.1) the template or email editor is not broken. when you click on the email builder, you can't do anything, the page is broken.

| Q   | A
| --- | ---
| Mautic 3.1 | 
| 7.3 | 
| Chrome, Firefox, edge...|

**Comment by christianrss** [comment]
Same error here.

**Comment by christianrss** [comment]
{"errors":[{"message":"URL requerida n\u00e3o encontrada: \/s\/grapesjsbuilder\/email\/new_41614dde21647c68f9de71c53369b275cb04cded?template=blank\u0026_=1599236961994\u0026mauticUserLastActive=1432\u0026mauticLastNotificationId=","code":404,"type":null}]}

**Comment by colourfulowl** [comment]
There is a known issue with 3.0.1, 3.0.2 and 3.1 where the JS file that powers the editor crashes. Check here #9138

**Comment by hassancs91** [comment]
This worked for me:
Open Putty, navigate to mautic directory like this:
**cd /var/www/html/mautic**
then run this command:
**php bin/console mautic:assets:generate**
Clear your browser cache, done!

**Comment by christianrss** [comment]
> This worked for me:
> Open Putty, navigate to mautic directory like this:
> **cd /var/www/html/mautic**
> then run this command:
> **php bin/console mautic:assets:generate**
> Clear your browser cache, done!

this worked for me too!

**Comment by christianrss** [comment]
Thanks!

**Comment by romven** [comment]
I had the exact same issue. SOlved by running **php bin/console mautic:assets:generate**
Remember that if you have a Bitnami Mautic installation the route to run the command is: **/opt/bitnami/apps/mautic/htdocs**
Also I had to run **php bin/console cache:clear** to see the changes take effect

**Comment by colourfulowl** [comment]
Hi guys. I've just tested the above, it does resolve the above issue regarding the standard editor. However, it does still throw up a JS error in the console - It also doesn't resolve the JS issue with code mode :/ This can be closed and favour of #9138

**Comment by npracht** [comment]
closed in favor of https://github.com/mautic/mautic/issues/9138

**Comment by jarridlima** [comment]
> This worked for me:
> Open Putty, navigate to mautic directory like this:
> **cd /var/www/html/mautic**
> then run this command:
> **php bin/console mautic:assets:generate**
> Clear your browser cache, done!

Thank you!!! Its worked for me.
