### ISSUE TITLE
Error when trying to save configuration changes under "MAUTIC_URL/s/config/edit"

### ISSUE THREAD

**Issue by mcgumbel** [mautic/mautic#9172]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When I click "Save & Close" or "Apply" in the configuration menue the page freezes and changes that I made are not saved. This happend to me after migrating to Mautic 3.0 or 3.1.

### Solution
Change the ownership of all files in /var/www/vhosts/MAUTIC_DIR/var/logs in such a way that your webserver can access the files.

### Action Points
Fix the update script that the webserver can access files in /var/www/vhosts/MAUTIC_DIR/var/logs

| --- | ---
| Mautic version 3.1 |  Upgraded from Mautic 2
| PHP version 7.2.33 | 
| Browser Vivaldi (Chrome), Firefox| 
 
### Log errors
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/vhosts/MAUTIC_DIR/app/../var/logs/mautic_prod-2020-09-04.php" could not be opened: failed to open stream: Permission denied in /var/www/vhosts/MAUTIC_DIR/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108\nStack trace:\n#0 /var/www/vhosts/MAUTIC_DIR/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/vhosts/MAUTIC_DIR/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/vhosts/MAUTIC_DIR/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/vhosts/MAUTIC_DIR/vendor/monolog/monolog/src/Monolog/Logger.php(740): Monolog\\Logger->addRecord(500, 'Unc...\nPHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/vhosts/MAUTIC_DIR/app/../var/logs/mautic_prod-2020-09-04.php" could not be opened: failed to open stream: Permission denied in /var/www/vhosts/MAUTIC_DIR/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:108\nStack trace:\n#0 /var/www/vhosts/MAUTIC_DIR/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(119): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/vhosts/MAUTIC_DIR/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(39): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/vhosts/MAUTIC_DIR/vendor/monolog/monolog/src/Monolog/Logger.php(344): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/vhosts/MAUTIC_DIR/vendor/monolog/monolog/src/Monolog/Logger.php(614): Monolog\\Logger->addRecord(400, 'PHP...\n', referer: https://MAUTIC_URL/s/config/edit

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by mcgumbel** [comment]
There are also ownership errors in /var/www/vhosts/MAUTIC_DIR/var/cache. Both subdirectories "prod" and "run" are owned by "root". Hence, the webserver cannot access them and an error is thrown, i.e. when I saved changes in the configuration via the web interface.

**Comment by colourfulowl** [comment]
@mcgumbel I can't recall if it was a mautic 3.0 or 3.1 change, but the logs directory did get moved when I last did an update. It may be worth just checking server-side where your log files are and making sure they have full permissions (775 - sometimes it may need 777 depending on your set up).

**Comment by npracht** [comment]
@mcgumbel did you have the opportunity to check your permissions on server side ?

**Comment by mcgumbel** [comment]
@colourfulowl Thanks for the tipp, that did the job. It was a indeed a permission problem. I am not shure though if it was caused by a cron job. I currently run them as "root"- user but I will change that in the future.
@npracht thanks for your follow-up
