### ISSUE TITLE
Audit log seems to be missing data in dnc_channel_status and dnc_status

### ISSUE THREAD

**Issue by StoppingBuck** [mautic/mautic#9173]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
It seems that the Audit log is missing some data when viewing changes to DNC (at least when DNC is added through the API - not sure if it's different when done locally).
Namely, the "Old value" for `dnc_channel_status` is blank even in cases when there are old values, and the "New value" for `dnc_status` is blank for all cases, causing confusion about what has actually been changed.

![image](https://user-images.githubusercontent.com/8426548/92365226-10a29b80-f0f4-11ea-9f3c-19358247f5fe.png)

This might be related to #9076 as changing the DNC status via API does not seem to actually change the existing DNC status, but merely add an extra row to `lead_donotcontact` table.

| Q   | A
| --- | ---
| Mautic version | 3.1
| PHP version | 7.3
| Browser | Chromium

### Steps to reproduce
1. Set someone to DNC via the dnc/add API endpoint
2. Check their Audit log tab

**Comment by RCheesley** [comment]
@StoppingBuck was this resolved with the plethora of fixes we made for the DNC feature?

**Comment by npracht** [comment]
Closing for lack of feedback. If more later, we'll re-open the issue.
