### ISSUE TITLE
Add PHP 7.4 support

### ISSUE THREAD

**Issue by frankofno** [mautic/mautic#9179]
We've decided to use GitHub issues as a bug tracker only so the bug reports wouldn't be hidden in long list of ideas and support questions. Please go to https://forum.mautic.org/c/ideas to find support and discuss features.

since i can't sign up on the ideas site - something went wrong - i drop my question here. Any plans on becoming compatible with PHP 7.4.9 in the near future?

"Mautic does not support PHP version 7.4.9 at this time. To use Mautic, you will need to downgrade to an earlier version."

**Comment by dennisameling** [comment]
@frankofno PHP 7.4 support is basically ready, but we have some issues with our CI pipeline (Travis). Please check this PR for updates: https://github.com/mautic/mautic/pull/8447 - if you have some time/capacity to help us with it, that'd be fantastic!
