### ISSUE TITLE
[Feature request] Oktopost integration

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#918]
Oktopost currently integrates with many Mautic competitors and partners including:

- Marketo
- Act-on
- Eloqua
- Net-Results
- Salesfusion
- Hubspot
- Salesforce & Pardot

It would be really awesome if it could integrate with Mautic!

**Comment by RCheesley** [comment]
I also posted this on the Oktopost community feature requests: http://community.oktopost.com/forums/136896-feedback/suggestions/9831393-add-mautic-open-source-marketing-automation-inte

**Comment by danielkushner** [comment]
Interesting! Would love to learn more about Mautic and see where an integration would fit. Who's the best person to talk to?

**Comment by RCheesley** [comment]
I've put Alan/David in touch with our contact :)

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 21 September 2015 at 12:05, danielkushner <notifications@github.com>
wrote:

> Interesting! Would love to learn more about Mautic and see where an
> integration would fit. Who's the best person to talk to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/918#issuecomment-141943123>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.
