### ISSUE TITLE
"Clear all notifications" button doesn't work

### ISSUE THREAD

**Issue by StoppingBuck** [mautic/mautic#9182]
## Bug Description
The button to 'clear all notifications' does not work. It simply hides the notifications temporarily - they all return when updating the page or moving to another page.

Notibly, clearing individual notifications by clicking the 'Clear this notification' next to a particular notification works fine. It's only the 'clear all notifications' button which is broken.

| Q   | A
| --- | ---
| Mautic version | 3.1
| PHP version | 7.3
| Browser | Chromium

### Steps to reproduce
1. Have a number of unread notifications (red circle on the the bell icon)
2. Click the bell icon and then click the red cross with 'Clear all notifications'
3. Now the notifications seem to have been cleared
4. Either reload the page or simply navigate to another Mautic page
5. All the notifications are back
 
### Log errors
Nothing of relevance seems to be in the logs.

**Comment by dudanogueira** [comment]
I have the same problem :) Probably got a lot of notifications to be removed.
It was already like that before the 3.0 migrations.

Let me know if I can help triagging this bug.

**Comment by RCheesley** [comment]
I had the same issue when I was testing another issue - so I confirm this as a bug!

Would anyone like to take a stab at making a PR to fix this?

**Comment by olissongs** [comment]
Did today Update from 3.3 to 4.4 on PHP 7.4

Clear notification Button in frontend, only deletes notifications in the frontend list.
After a page reload, all notification are here again.

My workarround in phpmyadmin sql-command:

truncate TABLE `notifications`;
