### ISSUE TITLE
Form fields with HTML name form_id or submission_id breaks visualization of form submissions

### ISSUE THREAD

**Issue by fabiofabbri84** [mautic/mautic#9183]
If you have a form field with HTML name form_id or submission_id, the table cell with the values of this field are not in the form result page, and the columns on the left will be shifted under the wrong column header

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3

### Steps to reproduce
- create a form and save it
- add a form field with label "Form ID" or "Submission ID". The HTML name will be form_id or submission_id
- add other form fields after that and save the form
- fill in and submit the form
- go to the form result page. You will notice that the column for the Form ID field contains the values of the following field, and all the values of the following columns are shifted to the left, like if the Form ID column is missing except the head

**Comment by RCheesley** [comment]
Hi @fabiofabbri84 thanks for raising this issue.

Unfortunately I am unable to create a form using the field labels that you mentioned - it blocks me from saving with either of those fields present in the form:

![screenshot-local mautic3-2020 10 08-18_18_57](https://user-images.githubusercontent.com/2930593/95492328-cfbbd200-0992-11eb-9540-018729892506.png)

Here are the fields:

![screenshot-local mautic3-2020 10 08-18_19_44](https://user-images.githubusercontent.com/2930593/95492359-df3b1b00-0992-11eb-984f-6a9a8da4611c.png)

Can you clarify how you created the form in the first place?

**Comment by fabiofabbri84** [comment]
I saved the form before adding the fields. I updated the original post

However I think what you found is a bug too :D probably related to this bug.

It seems to me "form_id" and "submission_id" are used somewhere else and should not be used as field name, so it should be implemented a validator for field names to avoid conflict with names used somewhere else

**Comment by RCheesley** [comment]
These are protected names and therefore I believe that it is expected behaviour to prevent you using them as a field name. Therefore closing this issue.
