### ISSUE TITLE
url too long when adding a remote asset generate 500

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#9187]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.1.1
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a remote asset
2. Add a long URL (longer than the SQL limit) : `https://www.test.com/test/replays-webinars/mn-test-cybercite-acquisition-fidelisation/merci-replay-mn-test-cybercite-acquisition-fidelisation/video-workshops-conseil-recommandations-adaptees-workshops-conseil-recommandations-adaptees-test-cybercite-acquisition-fidelisation/merci-replay-mn-test-cybercite-acquisition-fidelisation/video-workshops-conseil-recommandations-adaptees-workshops-conseil-recommandations-adaptees` (this link does not exist, don't care of that)

See that the app thrown a 500.

## Suggestions/options to solve this
1. Change this field type to TEXT or LONGTEXT ? It would need migration script.
2. Just handle the limit in the UI by throwing a message saying "too long URL, please make it shorter".
3. Just handle the limit in the UI by interrupting the user from adding more char in the input.

**Comment by RCheesley** [comment]
@npracht I think I would favour the first option - especially when using UTM tags the links can easily get quite long!

**Comment by saitanay** [comment]
Tried to fix via https://github.com/mautic/mautic/pull/9541

**Comment by RCheesley** [comment]
@cla-bot check
