### ISSUE TITLE
Contacts created & page visits widgets are not Working Properly.

### ISSUE THREAD

**Issue by lostKingd0m** [mautic/mautic#9193]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
as we can see in screenshots i add 4 contacts on 12 august and after that i add 24 contacts more contacts on 28 august on my list but  but apart form these entries contacts created widgets showing 4 contacts created every day which is not correct sometimes is goes to 1 & 2 contacts created on a day and exactly same thing happening to page visits widgets. and both widgets are showing a similar data on a particular day like on 20 august its showing 4 contacts created (which is no correct )then the page visits also showing 4 page visits. 

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.2.23
| Browser |  chrome

### Steps to reproduce
1. go to dashboard
2. check the contacts created and page visits widgets
![github](https://user-images.githubusercontent.com/71144305/93000506-c0ee1680-f4dd-11ea-8e28-f2926764df82.jpg)

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, I'm trying to understand your bug report, you mention that the import data is correct but you're seeing incorrect data when contacts are being added through other sources?

How many contacts are you expecting to see being added each day (e.g. how many are filling out forms or whatever) compared to the count you're seeing in the charts?

**Comment by lostKingd0m** [comment]
No. only the contact widget is showing incorrect data .  as you can see in picture I added only 28 contacts on 28 august.and after that I didn't add any contacts but the graph is showing me incorrect data .

**Comment by colourfulowl** [comment]
@lostKingd0m the Created Contacts widget by default shows all. This will show any anonymous contact that mautic has automatically generated base on page views. For your use case maybe try changing the Contact in time widget to show only "identified". Please let us know if changing the widget segment resolves your issue.

![mautic-identified-contacts](https://user-images.githubusercontent.com/41902603/95224087-348bf680-07f2-11eb-8c33-2e2309f30b45.PNG)

**Comment by RCheesley** [comment]
Closing due to lack of recent response from the original poster.
