### ISSUE TITLE
blank install page

### ISSUE THREAD

**Issue by frankofno** [mautic/mautic#9198]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
blank install page

I've installed mautic for the first time. Started with the 3.x version - got a blank install page. So I deleted the mautic folder and downloaded the master version - blank / white install page
I tried again with the 3.1 version - same issue.

the folder permissions are set 0755 for mautic

chown -R apache:apache /var/www/*  was executed

A look in the logs showing me a 301 error 
so here is my vhost conf

<VirtualHost *:80>
  ServerName notmautic.mydomain.tld
  Redirect permanent / https://notmautic.mydomain.tld
RewriteEngine on
RewriteCond %{SERVER_NAME} =notmautic.mydomain.tld
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:443>
  ServerName notmautic.mydomain.tld
  DocumentRoot /var/www/html/notmautic

  <Directory />
    Options FollowSymLinks
    AllowOverride All
  </Directory>

  <Directory /var/www/html/notmautic>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
  </Directory>

  ErrorLog /var/www/logs/notmautic/error.log
  LogLevel warn

SSLCertificateFile /etc/letsencrypt/live/notmautic.mydomain.tld-0001/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/notmautic.mydomain.tld-0001/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>

| Q   | A
| --- | ---
| Mautic master / 3.x / 3.0 | 
| PHP PHP 7.3.22 | 
| Firefox / Safari | 
 
### Log errors
httpd log
myip - - [14/Sep/2020:11:21:03 +0200] "GET / HTTP/1.1" 301 239 "-" "Mozilla/5.0

mauticlog
myip - - [14/Sep/2020:11:25:40 +0200] "GET / HTTP/1.1" 500 - "-" "Mozilla/5.0 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
