### ISSUE TITLE
Add Tabs Menu" in Dashboard to switch between different dashboards

### ISSUE THREAD

**Issue by khalidzamer** [mautic/mautic#9206]
Add a user-friendly tab menu "like a toolbar" to display multiple tabs in the dashboard page-header to easily navigate accessible pre-defined dashboard templates, something similar to screenshots.

- Based on user role default access
- Option to toggle the dashboard in the menu like a bookmark/quick list 
- Enable drag to sort the order of menu items
- Possibly limit to 3,4 or 5 max to fit the page header div

![image](https://user-images.githubusercontent.com/43134718/93312293-bac6a580-f80f-11ea-961f-a9a37c3c9a95.png)

![image](https://user-images.githubusercontent.com/43134718/93312769-42141900-f810-11ea-92a1-f5659b70b55b.png)

**Comment by RCheesley** [comment]
Hi there, thanks for taking the time to share this suggestion.

Please post your issue over at https://forum.mautic.org/c/ideas as Github issues are for reporting bugs with Mautic whereas the Ideas forum is where we discuss ideas and feature requests before there is any code to accompany the feature.
