### ISSUE TITLE
Social Settings - just a dropdown list no settings

### ISSUE THREAD

**Issue by frankofno** [mautic/mautic#9208]
## Bug Description
In the Configuration / Social Settings I find a dropdown list. I can choose an entry from the list, but no settings are showing up. Only the dropdown list, where I can choose an entry. Not sure what the purpose of those setting page is.

| Q   | A
| --- | ---
mautic 3.1.0 (loaded from github)
PHP 7.3.22
firefox 80.0.1 (64-bit)
CentOS 8.2

### Steps to reproduce
1. Click on configuration (right top corner)
2. Click on Social Settings
 

![Screenshot 2020-09-17 at 15 12 26](https://user-images.githubusercontent.com/35775329/93486624-b5975280-f904-11ea-92d2-935aeb172e43.png)
![Screenshot 2020-09-17 at 15 12 34](https://user-images.githubusercontent.com/35775329/93486640-b92ad980-f904-11ea-911f-62ee16e4c392.png)
![Screenshot 2020-09-17 at 16 38 33](https://user-images.githubusercontent.com/35775329/93486812-e7a8b480-f904-11ea-9555-71ed04b7cd38.png)

**Comment by colourfulowl** [comment]
This section is having more work done on it. However with recent changes to Facebook's Third Party policy, and others predicted, it's likely the whole social posting element in Mautic might get scrapped. I wouldn't worry about these settings if I was you. They're doing what they need to.

**Comment by frankofno** [comment]
guess that's why the social profiling is not working?
On a contact page I only get:


No Social Profiles Found

Click here to search for social media profiles based on contact's available profile data. (Social networks must be configured in the Integration Manager).

**Comment by colourfulowl** [comment]
Have you made sure to set up your twitter integration plugin? For support on plugins etc, its best to post questions on the official forums. Github is more for bug fixing.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
