### ISSUE TITLE
Missing assets on login page | user avatar

### ISSUE THREAD

**Issue by frankofno** [mautic/mautic#9209]
## Bug Description
Some assets seem to be missing. On the installation page (first time setup), the icon above seems to be missing.
After login, the avatar of the user seems to be missing. Can't find a field where to set / change the avatar. Instead it looks like a missing icon.

| Q   | A
| --- | ---
mautic version 3.1.0 (loaded from github)
PHP 7.3.22
80.0.1 (64-bit) 

### Steps to reproduce
1. Install page is missing a graphic icon
2. The user avatar field and user photos / graphic is missing

Missing Avatar image (right corner, next to user name)

![Screenshot 2020-09-17 at 16 45 17](https://user-images.githubusercontent.com/35775329/93488625-db255b80-f906-11ea-81c9-dcac4fe7ad03.png)

Account Page with no field where i can set the avatar
![Screenshot 2020-09-17 at 16 50 39](https://user-images.githubusercontent.com/35775329/93487949-14a99700-f906-11ea-8107-979b3a9d92a3.png)

**Comment by colourfulowl** [comment]
This is a weird one. Can you check on the server-side and see if the Avatar file is there? File-path is /media/images/avatar.png

If it's not there then you might need to rebuild your  assets folder, you can do so by doing the following:

php bin/console mautic:assets:generate
rm -rf app/cache/*
sudo chmod 777 app/cache

**Comment by frankofno** [comment]
yep, it's there:
-rw-r--r-- 1 apache apache 15995 Aug 24 19:53 avatar.png

Shouldn't there be a field, where I can upload or set my avatar in the profile/account page?

**Comment by RCheesley** [comment]
This is likely to be related to server config/permissions - please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by frankofno** [comment]
sorry to bother you again. The avatar image from the assets folder was showing up in Safari. Today the avatar.png from the mautic assets folder is no longer showing up.

i changed the permissions to 777 for avatar.png but still not available in mautic.

The user image / avatar can not be uploaded/changed manually, because there is no option to upload it or define a url etc. Therefor I think this is a bug.

Screenshot:
![Screenshot 2020-10-05 at 16 44 55](https://user-images.githubusercontent.com/35775329/95094401-27a3d000-072a-11eb-8a6f-a03e41392036.png)

![Screenshot 2020-10-05 at 16 38 48](https://user-images.githubusercontent.com/35775329/95094303-0c38c500-072a-11eb-8c4b-a2b554add306.png)

**Comment by colourfulowl** [comment]
What error are you given in your console?

If you don't see any error, then try uploading a dummy image with the name avatar.png into your media/images folder. If it's not a permissions issue the dummy image you upload should load and replace all of those markers.

**Comment by frankofno** [comment]
In my case port 80/443 were restricted and only accessable for my IP. So I had to make sure to add wp.com with IP 192.0.78.24 to allow access over port 80/443 - as soon as you add an email address to a contact, mautic will check on gravatar.com if this address has an account. If not a host from wp.com will use the avatar in the assets folder on mautic server and therefor the IP needs to be allowed. I think this can become a legal / GDPR issue, if all email addresses are sent to US servers to check if an gravatar exists. Although you might think all data is processed on your own server.
