### ISSUE TITLE
no points added when user opens / reads an email

### ISSUE THREAD

**Issue by frankofno** [mautic/mautic#9210]
## Bug Description
The points action doesn't seem to work. 

| Q   | A
| --- | ---
mautic 3.1.0
7.3.22
Firefox 80
CentOS 8.2

### Steps to reproduce
1. Go to points (left side bar)
2. Create Action 10 points when a contact opens an email. is repeatable yes.
 
### Log errors
no changes in the points of the contact.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
