### ISSUE TITLE
no contacts in segment | filter = email is not empty

### ISSUE THREAD

**Issue by frankofno** [mautic/mautic#9211]
## Bug Description
I can't get any contacts in any segment. 

| Q   | A
| --- | ---
mautic 3.1.0 (loaded from git)
7.3.22
Firefox 80
CentOS 8.2

### Steps to reproduce
1. new segment | filter with email is not empty results in no contacts. the contacts where added manually before via mautic.

**Comment by RCheesley** [comment]
Hi  there,

Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
