### ISSUE TITLE
I fixed a bug but I dont know how too Committ - Amazon SNS Notification Bug 

### ISSUE THREAD

**Issue by cloudpotions** [mautic/mautic#9212]
Okay so my mautic/mailer/amazon/callback will always stay in "pending" confirmation and never confirm in Mautic 3. I found a really easy fix... They accidentally put Port 2587 and it should be port 587 !!!

I just opened my Plesk panel and deleted the 2 and voila it worked seconds later.... Someone please commit this! 

Here it is: 

In app/bundles/EmailBundle/Swiftmailer/Transport/AmazonTransport.php ---  the following change must be made in order to make the connection successful:

From

Code:
parent::__construct($host, 2587, 'tls');
TO:
Code:
parent::__construct($host, 587, 'tls');

**Comment by cloudpotions** [comment]
<img width="975" alt="Ashampoo_Snap_Thursday, 17 September 2020_23h26m25s_001_" src="https://user-images.githubusercontent.com/34029756/93563928-b6000f80-f93d-11ea-9042-45f6f75babd2.png">

**Comment by mabumusa1** [comment]
This not a bug, the port 2587 is used for sending SMTP mail, SNS is not configured to post back to this port
I think this a configuration issue, please refer to the documentation for more information on how to configure SES

**Comment by cloudpotions** [comment]
@mabumusa1 - I understand that Mautic uses port 2587. I think in that file we should put Port 2587 and port 587. The reason why, once port 587 is added, in the Amazon SNS dashboard, under Subscriptions - This can not turn to state "confirmed" until the Port 587 is in that file. I have also seen other posts about this topic on the internet.

**Comment by cloudpotions** [comment]
Also one more thing @mabumusa1  - I am talking about SNS - I am not talking about SES.
