### ISSUE TITLE
Builder feature not working

### ISSUE THREAD

**Issue by zucaina** [mautic/mautic#9213]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The builder feature is static, I cannot interact or use any of the functions available. It feels like it's missing a library or some simple tweaks. 

At this link, you will see a screenshot of what I see when using the feature. 

https://drive.google.com/file/d/1jiNYH3vlBYk73kYqqptUX-YGOfNtQ4Bi/view?usp=sharing

| Q   | A
| --- | ---
| Mautic version | I'm using a bitmani distribution on AWS, hosted on an EC2 server. 
| PHP version | PHP Version 7.2.33
| Browser | I used a combination of Chrome, Safari, and Edge and all of them renders the same issue.

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, we have seen several people reporting this with Bitnami-based instances but it is not reproduced in Mautic itself. 

Please can you post on the Bitnami support forum here: https://community.bitnami.com/t/mautic-emails-and-landing-pages-are-blank-and-do-not-allow-editing-on-builder/86018 as they need to update their builds to incorporate the fix.
