### ISSUE TITLE
Twilio plug-in is missing after migration from v2.16.3 to 3.0.1 on Windows Server

### ISSUE THREAD

**Issue by ludovicfourrage** [mautic/mautic#9220]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Clean install of Mautic v2.16.3 on Windows Server 2016, IIS, PHP Version 7.2.31, MySQL 5.7.30
After the migration to v3.0.1 which goes well without generating error, the plug-in Twilio is missing and can no longer be configured. The Channel "Text Messages" is also missing.

| Mautic version |  2.16.3
| PHP version |  7.2.31
| MySQL version | 5.7.30
| OS |  Windows Server 2016

### Steps to reproduce
1. Clean install of Mautic v2.16.3 on Windows Server 2016 | MySQL 5.7.30 | PHP 7.2.31
2. Configure the Twilio plugin and enable it
3. Upgrade to Mautic v3.0.1 via CLI
4. Check the Twilio config - the plugin is gone, the "Text Messages" channel is also missing.
 
### Log errors
No log errors during the migration

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by gmenezesg** [comment]
Same here. For me, the Onesignal plugin is missing as well.

**Comment by ludovicfourrage** [comment]
Same for me with OneSignal. I've noticed they both have 'null' as their `plugin_id `in the table `mtc_plugin_integration_settings`, and are the only ones like that. They also don't show up in the `mtc_plugins` table (both for a db as of 2.16.3). Might be the culprit?
Are you on Windows as well gmenezesg?

**Comment by mabumusa1** [comment]
@ludovicfourrage what happens when you click this button
![image](https://user-images.githubusercontent.com/12627658/93754638-b8e35480-fc0a-11ea-9acd-f6e4a6247914.png)

Could it be that plugins are not reloaded?

**Comment by ludovicfourrage** [comment]
It doesn't fix it. The overlay message is '0 new plugins were installed and 0 were updated'

**Comment by RCheesley** [comment]
I am also seeing reports of this with folk who are on Bitnami-based instances: https://community.bitnami.com/t/i-launched-aws-bitnami-image-for-mautic-the-plugins-are-missing/85747

**Comment by kuzmany** [comment]
This should fixed it https://github.com/mautic/mautic/pull/9274
Please test and let comment to speed up merging to official release

**Comment by ludovicfourrage** [comment]
Hi kuzmani, I tested the fix and the Twilio and OneSignal plugins are there now! Thank you!

**Comment by npracht** [comment]
Fixed in 3.1.2
