### ISSUE TITLE
exception occurred while executing 'CREATE INDEX tableinstagram_search ON tableleads (instagram)': SQLSTATE[42000]

### ISSUE THREAD

**Issue by joyloan** [mautic/mautic#9223]
[//]: # (READ THIS BEFORE PUBLISHING YOUR ISSUE)

[//]: # (Please post questions, support requests and feature requests/ideas at https://forum.mautic.org.)
[//]: # (Strictly follow the instructions hereunder, otherwise your issue will be closed for lack of information.)
[//]: # (DO NOT report security vulnerabilities here. Send them to security@mautic.com.)
[//]: # (MAUTIC 2 is not supported any more (except for security matters), report your issue only if it relates to the Mautic 3 series.)

**Mautic: 3.0.2
Php: 7.2
At the time of installation>>Ready to install>>Database setup>>Error as follow**

An error occurred while attempting to add default data: An exception occurred while executing 'CREATE INDEX tableinstagram_search ON tableleads (instagram)': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

Detail your bug report:

| Q  | A
| ---| ---
| Confirm it is a Bug report |
| 3.0.2 | **MAUTIC 2 is not supported any more**
| 7.2| 

[//]: # (Feature request? ---> Go to forum please ---> https://forum.mautic.org/c/ideas)
[//]: # (Enhancement? ---> Go to forum please ---> https://forum.mautic.org/c/ideas)
[//]: # (Need support, have questions? ---> Go to forum please ---> https://forum.mautic.org/c/support)

## Description:
The more details the better...

### Steps to reproduce:
1. 
2. 
 
### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by joyloan** [comment]
When I enter my details and click the next step these error appears.

**1.**
An error occurred while attempting to add default data: An exception occurred while executing 'CREATE INDEX tableinstagram_search ON tableleads (instagram)': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**2.** 
An error occurred while attempting to install the data: An exception occurred while executing 'CREATE TABLE tableleads (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, owner_id INT UNSIGNED DEFAULT NULL, stage_id INT UNSIGNED DEFAULT NULL, is_published TINYINT(1) NOT NULL, date_added DATETIME DEFAULT NULL, created_by INT DEFAULT NULL, created_by_user VARCHAR(191) DEFAULT NULL, date_modified DATETIME DEFAULT NULL, modified_by INT DEFAULT NULL, modified_by_user VARCHAR(191) DEFAULT NULL, checked_out DATETIME DEFAULT NULL, checked_out_by INT DEFAULT NULL, checked_out_by_user VARCHAR(191) DEFAULT NULL, points INT NOT NULL, last_active DATETIME DEFAULT NULL, internal LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', social_cache LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', date_identified DATETIME DEFAULT NULL, preferred_profile_image VARCHAR(191) DEFAULT NULL, title VARCHAR(191) DEFAULT NULL, firstname VARCHAR(191) DEFAULT NULL, lastname VARCHAR(191) DEFAULT NULL, company VARCHAR(191) DEFAULT NULL, position VARCHAR(191) DEFAULT NULL, email VARCHAR(191) DEFAULT NULL, phone VARCHAR(191) DEFAULT NULL, mobile VARCHAR(191) DEFAULT NULL, address1 VARCHAR(191) DEFAULT NULL, address2 VARCHAR(191) DEFAULT NULL, city VARCHAR(191) DEFAULT NULL, state VARCHAR(191) DEFAULT NULL, zipcode VARCHAR(191) DEFAULT NULL, timezone VARCHAR(191) DEFAULT NULL, country VARCHAR(191) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, preferred_locale VARCHAR(255) DEFAULT NULL, attribution_date DATETIME DEFAULT NULL, attribution DOUBLE PRECISION DEFAULT NULL, website LONGTEXT DEFAULT NULL, facebook VARCHAR(255) DEFAULT NULL, foursquare VARCHAR(255) DEFAULT NULL, instagram VARCHAR(255) DEFAULT NULL, linkedin VARCHAR(255) DEFAULT NULL, skype VARCHAR(255) DEFAULT NULL, twitter VARCHAR(255) DEFAULT NULL, INDEX IDX_6375827E3C61F9 (owner_id), INDEX IDX_6375822298D193 (stage_id), INDEX tablelead_date_added (date_added), INDEX tabledate_identified (date_identified), INDEX tabletitle_search (title), INDEX tablefirstname_search (firstname), INDEX tablelastname_search (lastname), INDEX tablecompany_search (company), INDEX tableposition_search (position), INDEX tableemail_search (email), INDEX tablemobile_search (mobile), INDEX tablephone_search (phone), INDEX tablepoints_search (points), INDEX tablefax_search (fax), INDEX tableaddress1_search (address1), INDEX tableaddress2_search (address2), INDEX tablecity_search (city), INDEX  etc etc.........

**Comment by joyloan** [comment]
I tried installing through Softaculous

But there too installation gets stuck between 7-10%. Then nothing happens for hours. I tried so many times

**Comment by RCheesley** [comment]
Hi there, In most cases we have found this to be due to a database version that is not supported. Please take a look at [this thread](https://forum.mautic.org/t/solved-upgrade-to-3-0-1-row-size-too-large-mariadb-10-5/15495) in the forums, and the minimum requirements [here](https://www.mautic.org/download/requirements).

As this is not likely to be a bug with Mautic itself, I'm going to close this issue - in the future please use the forums for support requests, as Github is for reporting bugs with Mautic itself.
