### ISSUE TITLE
issue with code mode bloc added in the builder

### ISSUE THREAD

**Issue by Datch06** [mautic/mautic#9225]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| 3.0.1 | 
| 7.3 fpm | 
| Chrome| 

### Steps to reproduce
1. Go to Channels/Emails
2. New/Edit/Code mode/Builder
3. Add an image html tag with an alt attribute and a special char in it (é, €, etc...)
4) Save, it will load infinitely without saving

By the way to solve this you could replace you specials chars with html entities. BUT when you save the builder, it will automatically transform these html entities in special char. so if you save again it will reproduce the bug.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, can you confirm whether this persists on 3.1 as we have had several fixes related to the editor since 3.0.1.

**Comment by Datch06** [comment]
You're right it was resolved with 3.1. thanks

**Comment by RCheesley** [comment]
Fab, I'll go ahead and close the issue then :) Thanks for reporting back!
