### ISSUE TITLE
DKIM Header Changed : DKIM Signature Body Hash Did Not Verify

### ISSUE THREAD

**Issue by trancemanone** [mautic/mautic#9232]
| Mautic version | 3.1
| PHP version | 7.3
| Browser | Chrome

Hello all, 

I use [Postal](https://github.com/postalhq/postal) as my SMTP. I have all the DNS records installed correctly : SPF DKIM and DMARC and verified 10/10 on mail-tester.

When I test these records by sending a test directly from Postal to my gmail account and then test my email header with mxtoolbox or [appmaildev](https://www.appmaildev.com/site/testfile/dkim?lang=en)  I get a DKIM pass reply.

However, When I send a test email from Mautic to my gmail account and test the header with mxtoolbox or [appmaildev](https://www.appmaildev.com/site/testfile/dkim?lang=en) the DKIM authentication will fail!

The reason is: ".... Expected-Body-Hash: WIOFbA0nxr9LK59pSvSPyPaEz8meJEvP78rzNyVxlsA=
DKIM-Result: fail (wrong body hash: mILyW/egpTCSgQk90NKV5kWnYZOYwm92W2KqSz9SAP8=)"

Any Idea on how to solve this ? Does Mautic change the DKIM header ? 

Thanks

**Comment by trancemanone** [comment]
Just in case its not clear. I use: 
Email Settings > Service to send mail through > Other SMTP server

**Comment by trancemanone** [comment]
I use Postal as my SMTP. I have all the DNS records installed correctly : SPF DKIM and DMARC and verified 10/10 on mail-tester.

When I test these records by sending a test directly from Postal to my gmail account and then test my email header with mxtoolbox or appmaildev I get a DKIM pass reply.

However, When I send a test email from Mautic to my gmail account and test the header with mxtoolbox or appmaildev the DKIM authentication will fail!

The reason is: ".... Expected-Body-Hash: WIOFbA0nxr9LK59pSvSPyPaEz8meJEvP78rzNyVxlsA=
DKIM-Result: fail (wrong body hash: mILyW/egpTCSgQk90NKV5kWnYZOYwm92W2KqSz9SAP8=)"

Any Idea on how to solve this ? Does Mautic change the DKIM header ?

Thanks

**Comment by mabumusa1** [comment]
Please verify the headers, I use Postal sometimes and I never got this problem. I suggest you send a simple email without headers and attachments to see if this problem reoccurs.

I do no think this is Mautic problem, as Mautic uses swiftmailer to send out emails and it works just fine with Postal, so please look into your configurations

**Comment by trancemanone** [comment]
> Please verify the headers, I use Postal sometimes and I never got this problem. I suggest you send a simple email without headers and attachments to see if this problem reoccurs.
> 
> I do no think this is Mautic problem, as Mautic uses swiftmailer to send out emails and it works just fine with Postal, so please look into your configurations

Thank you for your reply. 

When I send a direct email from postal then test the header there was no issues at all with the DKIM authentication on mxtoolbox . 

But the issue is while using Mautic or any other marketing platform something in between isnt right. 

By the way I have managed to get DKIM authenticated on mautic if testing is done on [maildev](https://www.appmaildev.com/site/testfile/dkim?lang=en) but not on this [tool](https://mxtoolbox.com/EmailHeaders.aspx) 

Can it be that you are using another tool on mxtoolsbox like this one [here](https://mxtoolbox.com/deliverability) : ?

**Comment by RCheesley** [comment]
Hi folks, as this doesn't seem to be a bug with Mautic, please take the discussion over to https://forum.mautic.org/c/support.
