### ISSUE TITLE
Focus Item - Form Page Breaks Not Compatible

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#9235]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Create a form that uses multiple page breaks and add as a focus item. Mautic seems to remove the page break code from the form. This would be a handy option to have given the GDPR privacy statements that need to be included for us in the EU. I was trying to do something similar to Hubspot's Intent to Leave on their blog. You get an initial splash screen, followed by the form, followed by the consent page.

Example here: https://blog.hubspot.com/sales/winning-sales-team-crm-software - Simply move your mouse out of the screen to get the popup.

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a form that uses multiple pages. 
2. Use this form as the focus item form.
3. Preview the form.
 
### Log errors
None.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there,

Thanks for raising it, unfortunately I raised it myself back in 2016 😱  in this issue #2992 - it seems it's still knocking around! Will close this as a duplicate!
