### ISSUE TITLE
Error 500 when submit form

### ISSUE THREAD

**Issue by admin-fcosson** [mautic/mautic#9238]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I recently upgraded Mautic to 3.1.0 version and now I got error 500 when submiting a form. I tried to empty the cache but it didn't work. It seems to be an issue when I'm not logged to Mautic as user, because I got the problem only in private browser, it's working well when I submit the form while logged to Mautic

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.2.31
| Browser | Chrome

### Steps to reproduce
1. 
2. 
 
### Log errors
mautic.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Mautic\FormBundle\Entity\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\LeadBundle\Entity\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"})." at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php line 102 {"exception":"[object] (Doctrine\\ORM\\ORMInvalidArgumentException(code: 0): A new entity was found through the relationship 'Mautic\\FormBundle\\Entity\\Submission#lead' that was not configured to cascade persist operations for entity: Mautic\\LeadBundle\\Entity\\Lead with ID #. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={\"persist\"}). at /opt/bitnami/apps/mautic/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:102)"} []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by admin-fcosson** [comment]
Still have the problem, any ideas? :(

**Comment by colourfulowl** [comment]
Did you migrate from v2 by any chance? There seems to be some migration issues from v2 to v3 that could be causing the above.

As a precautionary step, have you cleared the Form Cache? Cleaning the System Cache doesn't clear the Form Cache. To clear the form cache you need to hop over to forms, click on the drop down at the top and rebuild cache. 

![mautic-form-cache](https://user-images.githubusercontent.com/41902603/95195072-f381eb00-07cd-11eb-9196-acc15db22eee.PNG)

**Comment by automation-wavekeeper** [comment]
Hello,

Thank you for your help. Indeed, we have migrated from v2.

I tried to clear the Form Cache like you said but we are still facing the same issue.  I also tried to recreate the form but it didn't help.

Do you have any others ideas?

**Comment by admin-fcosson** [comment]
Hello,

Thank you for your help. Indeed, we have migrated from v2.

I tried to clear the Form Cache like you said but we are still facing the same issue. I also tried to recreate the form but it didn't help.

Do you have any others ideas?

**Comment by RCheesley** [comment]
Have you cleared the cache in /yourmautic/var/cache?

You mentioned that it did not work but I wasn't clear if you meant that clearing the cache didn't work, or clearing the cache didn't fix the issue.

**Comment by admin-fcosson** [comment]
Yes, I cleared the cache in /var/cache.
Clearing the cache, didn't fix the issue, even with the Form Cache.

Sorry if I wasn't clear.

**Comment by admin-fcosson** [comment]
I also tried to upgrade to the new version 3.1.1 today. We are still facing the same issue, the form is working well only when a user is logged to Mautic. 

If we submit the form from a private browser or from any other browser where the user is not logged in, the form will failed with the error in the description.

**Comment by admin-fcosson** [comment]
Any ideas?

As you can see below, it's only a basic form with only 1 submit button showing "TEST" when submitted.

Below the result when I am  logged to Mautic (working well)
![image](https://user-images.githubusercontent.com/47249624/96236020-cab2e000-0f9b-11eb-8384-4f182d142e9e.png)

Below the result in private browser (not working)
![image](https://user-images.githubusercontent.com/47249624/96235806-84f61780-0f9b-11eb-98f9-f5cdce122ce5.png)

**Comment by admin-fcosson** [comment]
Any ideas? :(

**Comment by admin-fcosson** [comment]
@colourfulowl @RCheesley  Any update?

**Comment by admin-fcosson** [comment]
@RCheesley @colourfulowl  Hello, could we have pls any update? We are still facing the same issue...

**Comment by admin-fcosson** [comment]
The form is available on this URL https://notification.wavestone-app.com/test

**Comment by RCheesley** [comment]
@admin-fcosson can you tell us about the form itself? What is is doing? 

Is it a campaign form or standalone? 

What actions do you have happening on submit?

**Comment by iml885203** [comment]
same issue with me.
It will happen a form without a contact field.

version: 2.16.2 and 3.0.2 and 3.1.2

1. create campaign or standalone form
2. add a new field: text
3. type the label into "My name"
4. Save & Close
