### ISSUE TITLE
TextareaType is not reusable

### ISSUE THREAD

**Issue by pjoulot** [mautic/mautic#9241]
| Q   | A
| --- | ---
| Mautic version | 3

Hello,

I am trying to create a new slot type with one Rich text and one image. It is kind of the same as "Image Card" but the text is not a simple input, it is a rich text.

The current code in core is considering that if a slot has a TextareaType, the whole HTML of the slot is for this rich text field. SlotTextType is using it.

In 4.builder.js
```
focusForm.find('textarea.editor').each(function () {
                var theEditor = this;
                var slotHtml = parent.mQuery('<div/>').html(clickedSlot.html());
```

It works well with the basic core because there is only one slot type that is using the rich text. But if you create custom ones, with one rich text and something else or more than one rich text, then the core is just messing up everything. It will include take the whole HTML instead of just a part. SlotTextType doesn't allow other slots to reuse TextareaType.

**clickedSlot.html()** is causing this issue. SlotTextType seems defining a 'data-slot-param' => 'content' but the javascript doesn't seem to use it, which is completely blocking plugins to reuse TextareaType.

Should it use data-slot-param as the other types in order to identify a specific zone in the HTML?

In order to do what I wanted, I had to patch the core with something like this which is pretty dirty...

```
var slotHtmlElement = (type === 'mycustomplugin') ? clickedSlot.find('.custom-class') : clickedSlot;
var slotHtml = parent.mQuery('<div/>').html(slotHtmlElement.html());
```

**Comment by RCheesley** [comment]
Thanks for raising this @pjoulot - would you be up for working on a PR with support from some of the core team? It sounds like this could be a real pain for people using the builder as you describe.

Although we have a new builder in the pipeline, it could be useful to get this fixed for folk who decide to use the old builder.

**Comment by pjoulot** [comment]
Honestly, I went through the code a lot to manage what I wanted to do.
The Slots are modular and well organized in the PHP. But in the Javascript, it has not been thought modular at all, it would probably need an almost complete override.
If there is a new builder in the pipeline, maybe it would be better to raise this concern in the building of the new one. Is it a complete rewriting?
I don't think I'll have time for such a big task, sorry. I already maintain Drupal modules and I barely find enough of my free time to manage the issues.

**Comment by RCheesley** [comment]
Hi there,

Indeed we're planning to implement a new builder using the GrapeJS framework, the initiative is about to kick off and we hope to have a beta shipping with the 3.3 release in February with the General Availability being released with M4 in May.

So, given you're not able to work on this I'll go ahead and close the issue down, if you want to know more about the builders initiative do join #i-builders on Slack!
