### ISSUE TITLE
Image upload not working with Firefox

### ISSUE THREAD

**Issue by pjoulot** [mautic/mautic#9242]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

When using Firefox, the plugin to upload images is not working correctly (Only the drag and drop works, not the click). It works perfectly on Chrome. The click feature to choose a file is not working.

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.2.33
| Browser | Firefox 83
| Operating system | Ubuntu 18

### Steps to reproduce
1. Edit an email
2. Click on a slot with an image
3. Click on the replace button
4. Click in the zone with the message "Drop image (or click)"
5. Nothing happens, it should open the operating system modal to pick a file but it is just closing the tooltip to drop the file.
 
### Log errors

No javascript error in the console.

![Screenshot_2020-09-25 Edit Email - test Mautic](https://user-images.githubusercontent.com/6329139/94324757-2a473e00-ff50-11ea-8eba-03c7ee01094c.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for reporting this @pjoulot - I was able to reproduce this on Firefox.

**Comment by saitanay** [comment]
Seems to work on Mautic 3.2.1 with latest Firefox 84.0.1 (64-bit)
(issue originally reported and verified by Ruth earlier with Mautic 3.0.2 and FF 7.x)

https://www.loom.com/share/bf3030b13bdb459b8939ce414ea1e16c
