### ISSUE TITLE
Campaigns inconsistently reported as a JSON array instead of object

### ISSUE THREAD

**Issue by giomasce** [mautic/mautic#9243]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3.19-1~deb10u1
| Browser | Firefox 81.0 from Debian sid

### Steps to reproduce
Request the campaigns a contact is into with the API:

    $ curl -H 'Authorization: Basic XXXXXXXXXXXXXXXXXX==' 'https://mautictest.mascellani.eu/api/contacts/15/campaigns'
    {"total":2,"campaigns":{"1":{"id":1,"name":"Campagna uno","listMembership":[2],"dateAdded":"2020-09-27T17:00:30+00:00","manuallyRemoved":false,"manuallyAdded":true},"2":{"id":2,"name":"Campagna due","listMembership":[3],"dateAdded":"2020-09-27T17:00:40+00:00","manuallyRemoved":false,"manuallyAdded":true}}}
 
Returned object has a field `total`, which an integer, and a field `campaigns`, which is an object itself. However, if the contact has no campaigns, the following is returned:

    {"total":0,"campaigns":[]}

Field `campaigns` is no longer an object, but an array. This is inconsistent and causes problems for strongly-types languages like Python. Field `campaigns` should be an empty object when there are no campaigns.

I don't know if the same happens for other Mautic entities.

### Log errors
Error log is empty.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for reporting this @giomasce - I think it maybe also relates to a couple of existing issues that we have open: #8153 and #7385 in particular.

We also have an open PR https://github.com/mautic/mautic/pull/7723 which may be addressing this issue, but that PR has some conflicts which need to be addressed.

Would you be up for looking into a fix if the PR above doesn't address the issue for you?

**Comment by giomasce** [comment]
Hi @RCheesley, unfortunately I have very cursory experience with PHP and none with the framework Mautic is based on, so I am not able to rebase the PR properly or independently search for a fix. Sorry!

For my use case, I just modified the application that needs to consume Mautic's API to convert an array to an object when it is empty.

**Comment by RCheesley** [comment]
@giomasce OK no worries, we'll try to get this merged in 3.2 if we can get someone to address the conflicts!

**Comment by giomasce** [comment]
I doubt this has been solved. Feel free to close it if you wish, as I have worked it around satisfactorily, but in the general interests of Mautic users I think you should keep it open until it gets fixed.

**Comment by giomasce** [comment]
Not stale, it requires implementation.
