### ISSUE TITLE
validation error on webform

### ISSUE THREAD

**Issue by frankofno** [mautic/mautic#9246]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I've a simple sign up form on my website. name | e-mail | message (all required fields).
Instead of showing me the message "Enter E-Mail Adress" when not filling out the E-Mail, I get redirected to my homepage, allthough i've set a redirect url on "successfull submit". 

| Q   | A
| --- | ---
CentOS 8.2
mautic 3.1.1-rc (from github)
php 7.3.22
Firefox

### Steps to reproduce
the form is implemented via the HTML code snipet.
 
[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
