### ISSUE TITLE
Feature Request - General Comments Field on Email Templates/Assets - Custom Fields

### ISSUE THREAD

**Issue by TornMarketing** [mautic/mautic#9247]
We would be very keen to have a **general comments** field or **custom fields** for that matter against all emails, assets, campaigns etc so that we are able to put internal notes against all elements that are managed manually in Mautic.

We often build emails and store them as templates, but we then are missing context of what, when, how, who and where this email template was used for when we look back at the template with time passed. 

With each element we built there is always referencing material to working assets that relates to the template/asset such as XD/Adobe files or project tasks in our PM tools.

**Comment by RCheesley** [comment]
Please see my other comments on your other issues and pop this up on the forum at https://forum.mautic.org/c/ideas.
