### ISSUE TITLE
Feature Request - Form submission via API / webhook

### ISSUE THREAD

**Issue by TornMarketing** [mautic/mautic#9248]
Feature Request - Form submission via API / webhook

Request is to enhance the API to support form submissions.

We manage alot of our integrations now via middleware software for websites such as Zapier or Integromat, we are missing a feature to be able to submit a form via these methods. 

Currently we are having to submit upsert contacts with new tags which will then trigger to be submitted into a campaign.
There are a lot of features we are missing as a result of this, and we really need to use the forms if we are to do this successfully.

Officially we could submit it to the frontend form, but the requirements for serializing the data makes this a very complex task and very difficult to maintain via these middleware platforms.

**Comment by RCheesley** [comment]
Hi there,

Please see my comment on your other issue and pop your suggestions on https://forum.mautic.org/c/ideas :) 

Thanks for your interest in helping us make Mautic more awesome!
