### ISSUE TITLE
User Friendly Interface: Slot ID showing instead of Slot label

### ISSUE THREAD

**Issue by pjoulot** [mautic/mautic#9255]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

When creating emails, the name of the slot that appears when you hover it is the ID not the label of the slot. It is buggy with the Dynamic Content one from core but it will be with any custom slots that have a name with spaces or special characters. Ids are not user friendly and we do have a label for a slot type so we should use it.
.

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.2.33
| Browser | All

### Steps to reproduce
1. Edit an email
2. Add a Dynamic content slot
3. Hover the Dynamic content slot
4. It is showing "DYNAMICCONTENT", it should show the label with the space not the key. End users don't care about keys.
 
### Log errors

None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for flagging this up, indeed it makes more sense to show the label.

Would you be up for making a pull request to change this behaviour?

**Comment by pjoulot** [comment]
If I remember well, it was not just one line since the slot ID arriving in parameter of the function is coming from above.
But this issue is maybe not too time consuming for me to create a pull request. I'll try to have a look.

**Comment by RCheesley** [comment]
@pjoulot did you get a chance to take a look at improving this?

We have an initiative to implement a new builder so it might mean that this becomes irrelevant in a few months, but if you wanted to submit a bugfix we could get it into one of the upcoming patch releases a bit sooner!

**Comment by saitanay** [comment]
Triage - 

This seems to be the behavior with not just **Dynamic Content**, but also other slots like **"Image Card"** , **"Code Mode"** or any type of slot that has more than one word. 

This method in 4.builder.js seems to be converting the machine name of the slot type, to upper case, to print it the title of the slot toolbar. 

`
Mautic.getSlotToolbar = function(type) {
    Mautic.builderContents.find('[data-slot-toolbar]').remove();

    var slotToolbar = mQuery('<div/>').attr('data-slot-toolbar', true);
    var deleteLink  = Mautic.getSlotDeleteLink();
    var cloneLink = Mautic.getSlotCloneLink();
    if (typeof type !== 'undefined') {
        mQuery('<span style="color:#fff;margin-left:10px;font-family:sans-serif;font-size:smaller">' + type.toUpperCase() + '</span>').appendTo(slotToolbar);
    }
    deleteLink.appendTo(slotToolbar);
    cloneLink.appendTo(slotToolbar);

    return slotToolbar; };`


Only the type seems to be passed from the calling method in the same 4.builder.js
`var slotToolbar = Mautic.getSlotToolbar(type);`

Possible solution could include changing the signature of the getSlotToolbar() to accept the slot label as the second param, and pass on the slot title as well from the calling method(s) taking the slot label from the slot object they have (if it has it available?)
