### ISSUE TITLE
double scrolling over notification field

### ISSUE THREAD

**Issue by frankofno** [mautic/mautic#9259]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When an error e.g. on a mailing occurs and you click on that "bell icon" so you can see the notifications it is possible to scroll down. At the same time the whole page underneath will scoll as well.

| Q   | A
| --- | ---
CentOS 8.2
mautic 3.1.1-rc (from github)
php 7.3.22
Firefox

### Steps to reproduce
make an error  : )
make another error : )
click on the notification icon (bell icon) and scroll
 
Scroll inside the red rectangel and the page underneath will scroll too:

![Screenshot 2020-09-29 at 00 33 36](https://user-images.githubusercontent.com/35775329/94493059-f8520800-01eb-11eb-966a-462e8ee60a50.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
I was able to reproduce this, thanks for reporting it!
