### ISSUE TITLE
Expire entity lock automatically based on time

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#926]
Hi guys,

I've noticed an issue, when a user edit an email and quit by quitting directly the page (little cross), without clicking on "close the editor", the security lock stays active.
By consequence when another user tries to edit the same email, he stays out:
"Email 1 is currently checked out by User 1 (checked out on September 22, 2015 at 8:08 am). Override Lock".

Would be great that the User 1 is automatically pushed out when he quit the page.

N.

**Comment by alanhartless** [comment]
HI!

I'm not sure I'm following what is happening.  Which "little cross" are you referring to? Do you mean closing the browser's tab? 

The lock is designed to disengage when the cancel, save and close, or apply button is clicked or if the user leaves the page by clicking on another link.  

If you're closing the tab or browser, then we no longer have access to make any calls to automatically unlock the entity.

But if you're referring to something else, maybe a screenshot will help me understand exactly what's being referred to.  

Thanks!
Alan

**Comment by npracht** [comment]
Hi Alan,

Yes that's what i meant, closing the tab/browser.
"If you're closing the tab or browser, then we no longer have access to make any calls to automatically unlock the entity."
---> Here is the point. Then can we imagine that after X minutes/hours of inactivity the user is kicked out of the page that he was editing ? Anyway he'll have his session expiring at a certain point. At least kick him out at that time ?

Thanks,

N.

**Comment by alanhartless** [comment]
Gotcha; marked this as a feature request.
