### ISSUE TITLE
Error when migrating for 3.1.1 update

### ISSUE THREAD

**Issue by streamworksaudio** [mautic/mautic#9267]
I tried to perform the update to 3.1.1 today and while it seems that the code was updated, the migration for the database fails.

When tying to do it from the command line with:

`php bin/console doctrine:migration:migrate`

I get the following error:

`Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.`

I read that some recommended checking the MySQL version in the config.php file.  I did try to change it to 5.7 (it was at 5.5) and then running the command to clear the cache, but still I get the same error.

I am running the commands as the www-data user (sudo -u www-data...), I am not sure if there is an issue with doing so, but I wouldn't think so.

**Comment by streamworksaudio** [comment]
I was able to get the migration to work by editing the parameters array in app/config/local.php, specifically I change the 'db_server_version' variable to 5.7 to match the version of MySQL installed on our server.

Just to recap I change...

`'db_server_version' => '5.5',`

to:

`'db_server_version' => '5.7',`

Just in case somebody else lands here from a Google search.

**Comment by RCheesley** [comment]
Thanks for reporting back with the fix, I'll mark this as closed!
