### ISSUE TITLE
Javascript Errors on Preference Center

### ISSUE THREAD

**Issue by streamworksaudio** [mautic/mautic#9268]
In the preference center, when clicking on the 'Contact me Though Email' checkbox results in a javascript error:

`Uncaught TypeError: Cannot set property 'disabled' of null`

When clicking on save, this leads to a 500 error.  Clicking save without checking the checkbox does not result in an error.

Mautic 3.1.1
PHP Version 7.2.24-0ubuntu0.18.04.6

**Comment by streamworksaudio** [comment]
The issue seems to be with the js function togglePreferredChannel() which is executing:

`document.getElementById('lead_contact_frequency_rules_frequency_number_' + channel).disabled = true;`

But there is no element `'lead_contact_frequency_rules_frequency_number_' + channel'` on the page.

I have also noticed that the only way to show the option 'Contact me through email' is if I have the 'Show contact frequency preferences' enabled.  Would be good if you could set the 'Contact me through email' without showing the options to frequency preferences.  Or am I missing something?

**Comment by streamworksaudio** [comment]
Perhaps nobody is following this issue... but....

After looking at the DOM some more I am wondering if there were some name changes to the ID that were missed in the JS.  

For example, I see the element (by ID) `lead_contact_frequency_rules_lead_channels_frequency_number_email`

However the JS is trying to select the element `lead_contact_frequency_rules_frequency_number_' + channel`

Perhaps the element name was updated along the way and the JS was not?

I would love to use this software, but since trying to send our first email I have been trying to work around several bugs.  I cannot send out mail if the email preference center does not allow people to correctly subscribe and unsubscribe (especially consider the various laws regarding the issue).  This is a critical bug I would think then that needs to be addressed.

**Comment by npracht** [comment]
Hi @streamworksaudio do you think you'd be able to offer a PR to fix this ?

**Comment by streamworksaudio** [comment]
There are 3 js files that I can see that have this code, so I am not sure which one is being used when loading the preference center.  I will have to dig a little to see if I can find that out.  Perhaps somebody from the community already knows?

**Comment by streamworksaudio** [comment]
Some more digging (without forking the project, thought I would test it on a current install)...

Changing the JS at the top of the file app/bundles/EmailBundle/Views/Lead/preference_options.html.php to:

```
function togglePreferredChannel(channel){
       var status = document.getElementById(channel).checked;
       if(status)
           {
                document.getElementById('lead_contact_frequency_rules_lead_channels_frequency_number_' + channel).disabled = false;
                document.getElementById('lead_contact_frequency_rules_lead_channels_frequency_time_' + channel).disabled = false;
                document.getElementById('lead_contact_frequency_rules_lead_channels_contact_pause_start_date_' + channel).disabled = false;
                document.getElementById('lead_contact_frequency_rules_lead_channels_contact_pause_end_date_' + channel).disabled = false;
            } else {
                document.getElementById('lead_contact_frequency_rules_lead_channels_frequency_number_' + channel).disabled = true;
                document.getElementById('lead_contact_frequency_rules_lead_channels_frequency_time_' + channel).disabled = true;
                document.getElementById('lead_contact_frequency_rules_lead_channels_contact_pause_start_date_' + channel).disabled = true;
                document.getElementById('lead_contact_frequency_rules_lead_channels_contact_pause_end_date_' + channel).disabled = true;
            }
        }
```

Fixes the issue when select the checkbox returning NULL.  However now when I submit the form I get and error trying to remove the contact from the DNC (do not contact) list.  Logs says...

`[2020-10-06 13:09:30] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "removeDncForLead" of class "Mautic\LeadBundle\Model\LeadModel"." at /var/www/html/app/bundles/LeadBundle/Controller/FrequencyRuleTrait.php line 180 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"removeDncForLead\" of class \"Mautic\\LeadBundle\\Model\\LeadModel\". at /var/www/html/app/bundles/LeadBundle/Controller/FrequencyRuleTrait.php:180)"} []`

So it does appear to be the javascript in the app/bundles/EmailBundle/Views/Lead/preference_options.html.php file.  I could do a fork and a Pull Request... but perhaps somebody already contributing to the project can update this?

**Comment by RCheesley** [comment]
Hi @streamworksaudio sorry for the delay on following up with you for this issue.

Firstly, I'd ask if you're able to check if it persists on the latest version as we don't want to waste your time if it's already resolved!

If it is still an issue, it would be super helpful if you'd consider making a PR to address this. We have some great resources at https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests to help you get started, and please join slack (https://mautic.org/slack for an invite) - hop into the #t-product channel where one of the team can help you out!

**Comment by streamworksaudio** [comment]
Sorry, I stopped using Mautic shortly after I opened this issue so I am not sure if it was addressed or not.

**Comment by mabumusa1** [comment]
This issue still exists
