### ISSUE TITLE
URL tracking dont work if the URL has an ampersand in dynamic content

### ISSUE THREAD

**Issue by wise-gorilla** [mautic/mautic#9278]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
That issue got solved on this PR [#2060](https://github.com/mautic/mautic/pull/2060) but only for the urls added directly inside the email however it didn't solve the issue with the urls added inside a dynamic content

| Q   | A
| --- | ---
| Mautic version | 3.1.1
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1. Add a url with an ampersand like https://example.com/?foo=bar&bar=foo inside a dynamic content
2. Use this dynamic content inside an email by ex. <a href='{dynamiccontent="Dynamic Content 1"}'>Click here</a>
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @Wise-Gorilla would you please test https://github.com/mautic/mautic/pull/8345 and tell if it fixes the issue ?

**Comment by wise-gorilla** [comment]
@npracht I tested that PR and unfortuinatly it don't solve that issue

**Comment by npracht** [comment]
@kuzmany maybe you can tackle that in your PR ?

**Comment by arturromaorocha** [comment]
I have the same problem, mautic only identifies the first get parameter and ignores the rest.

://site?foo=bar&bar=foo&other=...
only foo is sent to the destination

v4.2.2

PHP Version 7.4.3

Database info
Version 8.0.28-0ubuntu0.20.04.3
Doctrine driver pdo_mysql


![image](https://user-images.githubusercontent.com/11146355/166418872-9a27cac4-09f1-4e83-8e2c-a222b27b0d0e.png)


![image](https://user-images.githubusercontent.com/11146355/166419204-1e8743ca-89c8-4804-8dc4-2e030de4a606.png)
