### ISSUE TITLE
1 user, 2 separated forms --> creates 2 leads

### ISSUE THREAD

**Issue by Jakub087** [mautic/mautic#928]
Hi,

I have several Mautic forms on my website. If 1 user with same email address fill in 2 separated forms, then 2 leads are created....It does not matter if other form fields (name, phone, domain) are same or different (but email address is still the same) --> everytime it creates 2 different leads.

I know about manual merging of task but that is not acceptable for me. I need automatic solution.

Thanks for advice, Jacob

Mautic v. 1.2.0.

**Comment by alanhartless** [comment]
Obviously this shouldn't be happening.  Can you check something for me? Go to Leads -> Manage Fields and look in the far right column.  Does the email field have a key icon? If not, edit the field and make sure it is set as a "unique identifier". If it is set as so, we'll dig into it a bit more.

Thanks!
Alan

**Comment by roderik** [comment]
I've experienced the same thing, but I wanted to chain several forms (like a wizard) where I asked email only in the first one. I assumed that the "session" would make sure additional info gathered in other forms would automatically be added to the "users" browsing.

**Comment by Jakub087** [comment]
Hi @alanhartless, key icon is set as "unique identifier" for email field. Any ideas how to prevent duplicating? Thanks

**Comment by npracht** [comment]
Hi @alanhartless,

I meet the same issue, i can create as much duplicates as i want. I thought Email is unique ID (and it is written like that), but it's not effective.
![capture d ecran 2015-10-19 a 15 16 52](https://cloud.githubusercontent.com/assets/14075239/10578768/7c05bb64-7674-11e5-99b8-5c3bef686f57.png)
![capture d ecran 2015-10-19 a 15 16 52](https://cloud.githubusercontent.com/assets/14075239/10578801/acbdda02-7674-11e5-9515-baa22717297a.png)

SOS !

**Comment by escopecz** [comment]
@npracht did you create those duplicates from within Mautic administration (A) or by different Mautic forms embedded into your website (B)?

(A) That is intentional behavior. Administrator can create duplicates. The question is if it is good for some workflow or totally unwanted.
(B) That is not intentional, but the thing is that it works in some cases and doesn't work in case no one was able to describe. If you'd be able to write a step-by-step tutorial how to create this issue, developers will be able to fix it.

**Comment by npracht** [comment]
Hi @escopecz,

It was definitely case (A). I created a new contact manually.
I think in anycase that's totally critical. We cannot wish to have duplicates..

**Comment by Jakub087** [comment]
Hi @escopecz ,

in my case it was case (A):
- we are using our own forms (RSforms component in Joomla!) and we mapped these on forms in Mautic forms (both forms have same fields)
- form #1 is just 1 field form (email)
- form #2 is more fields, one of them is again email
--> if user fill out both form --> 2 separated leads are created and not merged

Any suggestion? Need more description?

**Comment by escopecz** [comment]
Hopefully, this issue with be fixed in 1.2.1 by PR https://github.com/mautic/mautic/pull/1037

**Comment by alanhartless** [comment]
@Jakub087 Can you confirm if 1.2.2 fixes the your duplicate issue? 
@npracht Could you create a new issue to add unique identifier validations for the admin lead forms so we can track it as a separate issue?

Thanks!

**Comment by escopecz** [comment]
Closing for lack of feedback. Feel free to re-open if you still experience the issue.

**Comment by lucasmmendes** [comment]
Dear friends, 
I am having a different issue with Unique Identifer.
I created an Custom Field called Facebook ID and enabled the Unique Identifier, but when I import a second list of leads in csv format it duplicates. 
It is only merging the leads with same e-mails. 
Another point, I alread did the cron "console mautic:leadlists:update" and the leads are still duplicated.
Any idea?
Best wishes,
Lucas

**Comment by youyanghuang** [comment]
@lucasmmendes the same issue!
