### ISSUE TITLE
Import CSV does not import some values

### ISSUE THREAD

**Issue by Dylan-86** [mautic/mautic#9280]
## Bug Description
When you import a CSV file, some fields/values are not imported.

For example, I have a "Ranking" field that can be 1,2,3,4,5, N/A. I have created a custom field "select" type in Mautic too, with the same values.

When I import a CSV file and map the fields:
- The contacts get properly imported, with their names and emails
- The field "Ranking" is imported for 1,2,3,4,5 but not for "N/A".

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3
| Browser | Chrome - Any

### Steps to reproduce
1. Create a custom field _test_ in Mautic with values "N/A", "1", "2",
2. Import a CSV where there are values for _test_ = N/A, 1, 2
 
### Log errors

No errors logged anywhere.

My initial idea is that the "/" character is creating problems but I am not sure.

**Comment by npracht** [comment]
Hi @Dylan-86 
Did you create a select or multi select type field ? Because if you import multiselect values in a select field then you have an issue. Or i misunderstood something ?

**Comment by Dylan-86** [comment]
> Hi @Dylan-86
> Did you create a select or multi select type field ? Because if you import multiselect values in a select field then you have an issue. Or i misunderstood something ?

Hi @npracht ,

The field can be set to just ONE value (either "1" or "2" or "3" or "N/A") so the field in Mautic is a "Select", not a "multi select"

**Comment by npracht** [comment]
Hi @Dylan-86 i just tested in 2.x, 3.0 and mautibox (last version) and i cannot reproduce.
Can you test on mautibox too ? https://www.mautic.org/blog/community/become-a-community-contributor-by-easily-testing-mautic

Maybe it is already fixed in latest version ?

**Comment by Dylan-86** [comment]
Hi @npracht 

You're right, with the latest staging version it works.
I will update accordingly.
Thanks!
