### ISSUE TITLE
Zoho + Mautic plugin not importing some custom fields

### ISSUE THREAD

**Issue by Dylan-86** [mautic/mautic#9281]
## Bug Description

I have a Zoho account and have installed the Zoho plugin in Mautic.
Contacts from Zoho are correctly created in Mautic ("PULL"). Everything is fine except that some fields are not imported.

1. I have some "true/false" checkboxes in Zoho. I have created the same custom field in Mautic, "boolean". I have mapped the field. These fields are not imported. It seems to me that Zoho assigns "true/false" values while Mautic looks for "0/1".
2. I have a field "current status" in Zoho, which can be "open, closed, abandoned, lost, suspended". I have created in Mautic a custom field "Select" with these values. I have mapped the field. This fields is completely ignored.
3. Likewise, I have a "product" field in Zoho. Recreated in Mautic and mapped. It gets ignored.

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3
| Browser | Chrome, Firefox, Edge. 

### Steps to reproduce
1. You need to have a Zoho account and probably a paid version that lets you create custom fields. 
2. Configure the Zoho plugin in Mautic, map the fields
3. Try to create a contact that has a custom field (in the type of a "select" and "boolean"), 
4. You should see the contact created in Mautic, but missing the values for the custom fields.
 
### Log errors
No error logged.

**Comment by npracht** [comment]
Hi @Dylan-86 !
Could you test https://github.com/mautic/mautic/pull/7867 ?

**Comment by Dylan-86** [comment]
> Hi @Dylan-86 !
> Could you test #7867 ?

Hi @npracht ,
Tried after your suggestion. It doesn't work, at all. When I open the Zoho plugin, this is what I get with this version:
![image](https://user-images.githubusercontent.com/58813956/96334370-965d2380-1070-11eb-9de9-8e0235cbe525.png)
