### ISSUE TITLE
Elastic Email Webhook Notification marked as Bounced if configured with click or open events

### ISSUE THREAD

**Issue by emanuelflp** [mautic/mautic#9282]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have configured ElasticEmail to send notification when an email contact open an email or click in a link.

But, when ElasticEmail send the notification, my contacts are marked as bounce, with reason Unknown

| Q   | A
| --- | ---
| Mautic version | 3.0.2
| PHP version | 7.3.20
| Browser | Google Chrome 85.0.4183.121

### Steps to reproduce
1. Go to settings Page in ElasticEmail: https://elasticemail.com/account#/settings/notifications
Mark Opened and Clicked in your Webhook configuration
![image](https://user-images.githubusercontent.com/11159014/95633866-f8110280-0a5e-11eb-8324-1b4ff8797257.png)
2. Send a test mail to your address and click in a link inside email.
 
3. Check the contact status:
![image](https://user-images.githubusercontent.com/11159014/95634885-4e7f4080-0a61-11eb-85b1-5420a2503241.png)

### Log errors

172.16.1.6 - - [09/Oct/2020:21:47:34 +0000] "GET /mailer/elasticemail/callback?transaction=3e12ca19-8cb1-0105-0019-acd3138b620e&to=ema*******%40g****.com&from=contato%40g*****.com.br&date=10%2f9%2f2020+9%3a47%3a03+PM&status=Clicked&channel=SMTP+API&account=sy******%40g***********.com.br&category=Unknown&target=https%3a%2f%2f_MAUTIC_URL_%2fr%2fe9855fd905f30203c7ce779f0%3fct%3dYTo1OntzOjY6InNvdXJjZSI7YToyOntpOjA7czoxNDoiY2FtcGFpZ24uZXZlbnQiO2k6MTtpOjQxNDt9czo1OiJlbWFpbCI7aToxNjc7czo0OiJzdGF0IjtzOjIyOiI1ZjgwZDZkMjdjNDBhNzI0NTg1MTg5IjtzOjQ6ImxlYWQiO3M6NToiODQ1OTEiO3M6NzoiY2hhbm5lbCI7YToxOntzOjU6ImVtYWlsIjtpOjE2Nzt9fQ%3d%3d%26&subject=Eu+preciso+te+contar+esse+segredo...&messageid=nuEq5mDI68i192p9cOrC8A2 HTTP/1.1" 200 214 "-" "-"

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by colourfulowl** [comment]
Is the bounced message returned in the contact activity log?

![mautic-bounce-message](https://user-images.githubusercontent.com/41902603/95738075-93cd8900-0c80-11eb-8489-e01d32e5fd3f.PNG)

**Comment by ziedMauticMecanik** [comment]
@colourfulowl 
$events = $contactApi->getActivity($search, $includeEvents, $excludeEvents, $orderBy, $orderByDir, $page, $dateFrom, $dateTo);

how can I filter events from campaign_id or email_id in the $search variable? and what should I write in this variable?

**Comment by npracht** [comment]
Hi,

I think the integration is done to fetch bounces with the webhook action. But you enabled webhook feedback for clicks and opens.
Clicks and opens are directly managed by mautic (with the tracking pixel in email and URL re-write for tracking).

I'd suggest you to simply uncheck these boxes and grab with webhook actions only bounced.

You confirm open tracking and clicks still work ?

**Comment by emanuelflp** [comment]
Hummm. Ok. I will test here. Thanks

**Comment by RCheesley** [comment]
@emanuelflp any update on this?
