### ISSUE TITLE
Database Performance Issue when enable tracking 

### ISSUE THREAD

**Issue by mlahlouh** [mautic/mautic#9286]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 2.16
| PHP version | 
| Browser | 

### Steps to reproduce

when enabling site tracking in mautic, this causes huge IO on MySQL server and high-frequency logging in slow log and the query scanned millions of records, 
SQL: 
```
SELECT 
    COUNT(leadIdPrimary) count,
    MAX(leadIdPrimary) maxId,
    MIN(leadIdPrimary) minId
FROM
    (SELECT DISTINCT
        l.id AS leadIdPrimary, jcFpmfqK.lead_id AS jcFpmfqK_lead_id
    FROM
        leads l
    LEFT JOIN lead_lists_leads jcFpmfqK ON jcFpmfqK.lead_id = l.id
        AND (jcFpmfqK.leadlist_id = 28)
    WHERE
        (EXISTS( SELECT 
                NULL
            FROM
                page_hits ukHACSMZ
            WHERE
                (ukHACSMZ.lead_id = l.id)
                    AND (ukHACSMZ.url = 'https://domain.com/future-ready/')))
            AND (jcFpmfqK.lead_id IS NULL)) sss;
```
Query Profilinig:

executing | 0.000004
-- | --
Sending data | 0.000012
executing | 0.000003
Sending data | 0.000010
executing | 0.000003
Sending data | 0.000010
executing | 0.000002
Sending data | 0.000008
executing | 0.000002
Sending data | 0.000006
executing | 0.000002
Sending data | 0.000006
executing | 0.000002
Sending data | 0.000007
executing | 0.000002
Sending data | 0.000009
executing | 0.000002
Sending data | 0.000006
executing | 0.000002
Sending data | 0.000006
executing | 0.000002
Sending data | 0.000007
executing | 0.000002
Sending data | 0.000007
executing | 0.000002
Sending data | 0.000007
executing | 0.000002
Sending data | 0.000030
executing | 0.000002
Sending data | 0.000006
executing | 0.000002
Sending data | 0.000005
executing | 0.000002
Sending data | 0.000022
executing | 0.000002
Sending data | 0.000008
executing | 0.000002
Sending data | 0.000005
executing | 0.000002
Sending data | 0.000021
executing | 0.000002
Sending data | 0.000011
executing | 0.000002
Sending data | 0.000016
executing | 0.000002
Sending data | 0.000011
executing | 0.000002
Sending data | 0.000013
executing | 0.000002
Sending data | 0.000005
executing | 0.000002
Sending data | 0.000008
executing | 0.000002
Sending data | 0.000056
executing | 0.000002
Sending data | 0.000005
executing | 0.000002
Sending data | 0.000005
executing | 0.000002
Sending data | 0.000019
executing | 0.000002
Sending data | 0.000040
executing | 0.000002
Sending data | 0.000005
executing | 0.000002
Sending data | 0.000027
executing | 0.000002
Sending data | 0.000005
executing | 0.000002
Sending data | 0.000004
executing | 0.000002
Sending data | 0.000005
executing | 0.000002
Sending data | 0.000004
executing | 0.000002
Sending data | 0.000011
executing | 0.000002
Sending data | 0.000053
executing | 0.000002
Sending data | 0.000005
executing | 0.000002
Sending data | 0.000253
executing | 0.000003
Sending data | 0.000055
executing | 0.000002
Sending data | 0.000005
executing | 0.000002
Sending data | 0.000033
end | 0.000009
query end | 0.000010
removing tmp table | 0.000005
query end | 0.000003
closing tables | 0.000003
removing tmp table | 0.000003
closing tables | 0.000013
freeing items | 0.000044
storing result in query cache | 0.000007
cleaned up | 0.000005
logging slow query | 0.000042
cleaning up | 0.000005

I rewrite the SQL to be like:
```
SELECT 
    COUNT(l.id) AS count, MAX(l.id) maxId, MIN(l.id) minId
FROM
    leads l
        JOIN
    page_hits ukHACSMZ ON ((ukHACSMZ.lead_id = l.id)
        AND (ukHACSMZ.url = 'https://domain.com/future-ready/'))
        LEFT JOIN
    lead_lists_leads jcFpmfqK ON jcFpmfqK.lead_id = l.id
        AND (jcFpmfqK.leadlist_id = 28)
WHERE
    (jcFpmfqK.lead_id IS NULL);
```
Query Profilinig:

starting | 0.000016
-- | --
checking query cache for query | 0.000092
checking permissions | 0.000004
checking permissions | 0.000002
checking permissions | 0.000004
Opening tables | 0.000023
init | 0.000040
System lock | 0.000023
optimizing | 0.000019
statistics | 0.000089
preparing | 0.000024
executing | 0.000003
Sending data | 0.611488
end | 0.000021
query end | 0.000012
closing tables | 0.000017
freeing items | 0.000052
storing result in query cache | 0.000008
cleaned up | 0.000006
cleaning up | 0.000005

This change make it vast, and less IO on MySQL server.

 
### Log errors
no error logs

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @mlahlouh !
Can you create a pull request to re-write this SQL query ? Then people can test it and probably we can merge it into mautic.

**Comment by RCheesley** [comment]
Closing the issue due to a lack of response from the original poster and it relating to 2.x
