### ISSUE TITLE
Ver 3.02 - campaign reporting email as missing or not plublished

### ISSUE THREAD

**Issue by Robmobius** [mautic/mautic#9287]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Simple campaign to send a simple email. Campaign fires but the email is not sent. Contact history shows
"this event encountered an error during the last attempt to process
Last execution error: Email not found or published"
Other campaign actions fire successfully like adding tags, changing segments

Tried the same in another instance of Mautic, same version on the same VPS. Both installed via Softaculous. Same issue

| Q   | A
| --- | ---
| Mautic version | 3.02
| PHP version | 7.2.34
| Browser | Chrome

### Steps to reproduce
1. Create email
2. Create a campaign to send email
 
### Log errors
mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: “An exception occurred while executing ‘REPLACE INTO maukw_campaign_lead_event_failed_log( log_id, date_added, reason) SELECT id, :dateAdded as date_added, :message as reason from maukw_campaign_lead_event_log WHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation’: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':dateAdded as date_added, :message as reason from maukw_campaign_lead_event_log ’ at line 2” at /home/company/demo.company.biz/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 79 {“exception”:"[object] (Doctrine\DBAL\Exception\SyntaxErrorException(code: 0): An exception occurred while executing ‘REPLACE INTO maukw_campaign_lead_event_failed_log( log_id, date_added, reason)\nSELECT id, :dateAdded as date_added, :message as reason from maukw_campaign_lead_event_log\nWHERE is_scheduled = 1 AND lead_id = :contactId AND campaign_id = :campaignId AND rotation = :rotation’:\n\nYou have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘:dateAdded as date_added, :message as reason from maukw_campaign_lead_event_log\n’ at line 2 at /home/company/demo.company.biz/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:79, Doctrine\DBAL\Driver\Mysqli\MysqliException(code: 0): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘:dateAdded as date_added, :message as reason from maukw_campaign_lead_event_log\n’ at line 2 at /home/company/demo.company.biz/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:86)"} 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Robmobius** [comment]
https://github.com/mautic/mautic/pull/6574

Solved the issue

**Comment by lgwapnitsky** [comment]
> #6574
> 
> Solved the issue

how? I'm seeing this on my side
