### ISSUE TITLE
Image preview is not showing

### ISSUE THREAD

**Issue by dhmusman** [mautic/mautic#9288]
We have a fresh installation of Mautic. The image preview is not showing.
![image_2020_10_12T08_21_27_954Z](https://user-images.githubusercontent.com/12247463/95734665-3431a680-0c9d-11eb-8721-65d8469b351b.png)

**Comment by colourfulowl** [comment]
Mine also operates like the above. I actually thought that was how it was supposed to work >_<

**Comment by evgu** [comment]
What happens when you click on the image you want to preview? 

See example sequence which works in the image browser (when drafting emails):
<img width="993" alt="Example" src="https://user-images.githubusercontent.com/18371928/95865534-192b6900-0d67-11eb-889f-27d5cc42e0e1.png">

**Comment by colourfulowl** [comment]
Hi @evgu  If I open the preview, it shows the image.

Is the file manager not suppose to show a preview instead of the "png" icon in your above screenshot? Like the media manager in Wordpress?

**Comment by evgu** [comment]
@colourfulowl as far as I know Mautic displays icons in image manager, as shown in my screenshot above. Simply judging by the look and feel of the image magegers (and I may be wrong here) - Mautic and Wordpress seem to use different image managers.

**Comment by colourfulowl** [comment]
@evgu Sorry if my comment caused any confusion. Mautic and WordPress don't use the same file manager. I was simply referring to how it should be showing image thumbnails.

Mautic 3 using an open-source file manager called elfinder. Elfinder is supposed to provide thumbnails in the preview, however it appears to be misconfigured which is preventing it from doing such.

**Comment by npracht** [comment]
Please test https://github.com/mautic/mautic/pull/9367 !
