### ISSUE TITLE
Duplicated Name (IP) anonymous

### ISSUE THREAD

**Issue by mauropontara** [mautic/mautic#9305]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hi, i have a mautic 3.1.1 into hosting with php 7.2.33 i connect wiith wordpress 5.5.1 and plugin version 2.4.0.
When a visit web site with mobile (IOS) into contacs anonymous appear a lot of name with the same ip and same time.
I need to close the browser into mobile to stop creation. This issue doesn't appear from web browser.
Thanks

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1.  Connect to url of my site https://www.nefertarishop.it from ios mobile
2. 
 
### Log errors
No errors log

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by andrekutianski** [comment]
I have a similar problem  on 3.1.2-rc #9320 but installing 3.1.1 the issue persist

![image](https://user-images.githubusercontent.com/5316107/96590834-dfa1b300-12bc-11eb-9a69-fcc655969c0f.png)

**Comment by mauropontara** [comment]
I discovery one solution if my site is https://www.sitename.com the problem appears if site is https://test.sitename.com the probllem is solved.
