### ISSUE TITLE
Api to get all contacts inside a segment.

### ISSUE THREAD

**Issue by alexalxs** [mautic/mautic#9306]
Api to get all contacts inside a segment.
I am using this:
/contacts
But return all contacts into and out of the specific segment.
I need make this using API by GET like above, not using php.
thank

**Comment by npracht** [comment]
Hi @alexalxs next time please use Slack or forums for questions. We use GitHub to record all bugs that need to be addressed.

You can use https://developer.mautic.org/#list-contacts with search parameter segment=segment-alias

**Comment by andrew-dixon** [comment]
For anyone else who comes across this looking at how to do this, it is a GET request to the following:

```
https://[your_mauitc_domain]/api/contacts?search=segement:segment-alias
```

replacing `segment-alias` with your alias. Essentially, the `search` parameter can be anything you can use in the search in the Mautic UI, as described here:

https://docs.mautic.org/en/mautic-search
