### ISSUE TITLE
User Function and Campaign

### ISSUE THREAD

**Issue by leobaccili** [mautic/mautic#931]
Hello,

I create a new user function with not full access to the system, but full access to campaign.
The page no open and the log writes this:

[2015-09-22 20:59:45] mautic.ERROR: Fatal: Call to a member function getId() on a non-object - in file \app\bundles\FormBundle\Entity\FormRepository.php - at line 62 [] []

**Comment by escopecz** [comment]
Do I understand it right that you modified a Mautic PHP file and now you are experiencing the PHP error? Well, I don't think anyone can help you with that.

**Comment by leobaccili** [comment]
No, i don't change the php file, i create a new user function in configuration panel.
I use the permissions.

**Comment by escopecz** [comment]
Eh, ok. I still don't know where are you creating what function. Could you make a step by step tutorial how to recreate the error so I could test it?

**Comment by leobaccili** [comment]
I'm sorry, i believe i using wrong words. I'm create Roles , and this generate the error.

**Comment by leobaccili** [comment]
![pci1](https://cloud.githubusercontent.com/assets/14761612/10045192/1a54e16c-61d7-11e5-882d-940944db27f8.png)

![pci2](https://cloud.githubusercontent.com/assets/14761612/10045193/1c638dfa-61d7-11e5-9ad5-eca0a456bd97.png)

![pic3](https://cloud.githubusercontent.com/assets/14761612/10045197/239d692e-61d7-11e5-9363-a0bcf6d060d4.png)

After create this role, i create a new user with role, and login with this user.

I open option "Manage Campaign" nothing happens. In the log, show the erro.

**Comment by escopecz** [comment]
Ok, now I understand. Great description of the steps to reproduce the error. I'll mark it as a bug.

**Comment by escopecz** [comment]
Will be fixed in 1.2.1. Fix just got merged. https://github.com/mautic/mautic/pull/940
