### ISSUE TITLE
Multiple anonymous contact for the same IP 

### ISSUE THREAD

**Issue by andrekutianski** [mautic/mautic#9320]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v3.1.2-rc
| PHP version | 7.3.21
| Browser | Chrome/86.0.4240.75 Firefox/81.0

### Steps to reproduce
1. Insert tracking code on a website
2. Access the pages without identify the contact
 
### Log errors

Each time that an anonymous contact hits a page with the same IP Mautic creates a new anonymous contact.

![image](https://user-images.githubusercontent.com/5316107/96511185-18964500-1235-11eb-98a6-76949ca3702d.png)

I have a fresh Mautic installation and the following tracking settings:

* Identify visitor by tracking URL: yes
* Identify visitors by IP: yes
* Anonymize IP: no

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by andrekutianski** [comment]
now I believe that I fully understand. Each time that Mautic identifies or creates a new Mautic Device Id even the IP is the same I will get a different contact, but the config option _Identify visitors by IP_ should not merge regardless of the device id?

**Comment by mauropontara** [comment]
Hi, have you check if the problem is from mobile? I can't test from android but from ios it happens. Browsing from desktop doesn't have this problem.

**Comment by andrekutianski** [comment]
> Hi, have you check if the problem is from mobile? I can't test from android but from ios it happens. Browsing from desktop doesn't have this problem.

I have this issue in mobile and desktop tracking

**Comment by RCheesley** [comment]
Hi folks, can you confirm if this is still persisting on 3.2.1 please?

**Comment by npracht** [comment]
Closing for lack of feedback. If more later, we'll re-open the issue.

**Comment by andrekutianski** [comment]
Having the same behavior in Mautic 3.2.4

![image](https://user-images.githubusercontent.com/5316107/105710514-ff68f880-5ef5-11eb-9eb2-d88c16f811ac.png)

**Comment by andrekutianski** [comment]
> Hi folks, can you confirm if this is still persisting on 3.2.1 please?

Hi @RCheesley I having the same behavior on 3.2.4

**Comment by imihandstand** [comment]
I have the same problem with **3.3.2** (and **3.2.5** before that). My post: https://github.com/mautic/mautic/issues/9910

**Comment by tke852** [comment]
I think this is still an issue but it happened to me after upgrading to 4.3.1.  I can see myself navigating through the page and I'm given a new ID with every page I go to so there is no continuity in a visit.

I have an installation that hasn't been upgraded for a different website running 3.3.3 that works as expected.

Did anyone ever figure out why this is happening?  It basically makes Mautic worthless.

[https://forum.mautic.org/t/mautic-is-creating-a-new-id-with-every-page-load-for-anonymous-users/24758]

**Comment by andrekutianski** [comment]
> I think this is still an issue but it happened to me after upgrading to 4.3.1. I can see myself navigating through the page and I'm given a new ID with every page I go to so there is no continuity in a visit.
> 
> I have an installation that hasn't been upgraded for a different website running 3.3.3 that works as expected.
> 
> Did anyone ever figure out why this is happening? It basically makes Mautic worthless.
> 
> [https://forum.mautic.org/t/mautic-is-creating-a-new-id-with-every-page-load-for-anonymous-users/24758]

I've given up on understanding why and how this happens. I've been having this for many versions of Mautic. I've tested numerous scenarios, and always the same result. I've come to terms with that.
