### ISSUE TITLE
Regression in Citrix GoToWebinar Integration in #8745

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#9321]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The bug fix in PR #8745 had the opposite effect of that which was intended by the author. I eneded up with the array keys flipped in the UI and my segments would not build. 

Removing all of the `array_flip` statements from the author's commits fixed the problem for me. 

| Q   | A
| --- | ---
| Mautic version | 3.1
| PHP version | 7.3

### Steps to reproduce
1. Go to Segment.
1. Turn on GoToWebinar Plugin
1. Register some emails from Mautic contacts to webinars
1. Filter by Webinar registered
1. You should see flipped keys values for webinar, choose one and save it
1. The segment update does not work: mautic:segments:update
 
### Log errors
No Errors, but segment does not build

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by gabepri** [comment]
I confirmed that this bug is happening to me as well.  The fix @stevedrobinson recommended [in his comments on #8745](https://github.com/mautic/mautic/pull/8745#issuecomment-712468919) worked as a fix for this in my testing.

**Comment by gabepri** [comment]
This is fixed by https://github.com/mautic/mautic/pull/9251

**Comment by npracht** [comment]
Fixed in 3.2.0 which will be release next monday ;)
