### ISSUE TITLE
Direct Emails to contacts do not add attachments or headers

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#9322]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.1.2
| PHP version | 7.3
| Browser | Irrelevent

### Steps to reproduce
1. Create a template email with headers and an attachment
2. Create a contact
3. Send a direct email to that contact via the contact profile page
4. The attachment and the headers will not be sent

The cause of the issue is on this file, new lines are required to add the attachments and headers

https://github.com/mautic/mautic/blob/825e2aeea56d46f315159d6a6a70c572aa787513/app/bundles/LeadBundle/Controller/LeadController.php#L1375
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by andrekutianski** [comment]
this can cause a 403 error when sending a direct email to contact?

**Comment by mabumusa1** [comment]
> this can cause a 403 error when sending a direct email to contact?

@andrekutianski I do not think so.

**Comment by saitanay** [comment]
Can confirm this is the behavior. 

The options added in Advanced section of the email are not present in the email received. 
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/3456349/103259620-2f3ce300-49c0-11eb-9500-564186ead83f.png">


Fixing this might require not just updating the parsing of the email being sent to include the attachment and headers, but will also require an UI update to show the attachment and headers on the preview pane while sending email from contact page - so the sender knows what they are sending (including the headers and attachment)
<img width="733" alt="image" src="https://user-images.githubusercontent.com/3456349/103259689-7cb95000-49c0-11eb-9949-c1b6c7dd892f.png">

**Comment by alanhartless** [comment]
I think #8537 would address this as well but I had concerns about implications of the way it's fixing it. https://github.com/mautic/mautic/pull/8537#issuecomment-790174328

**Comment by jessebrightman** [comment]
We too have encountered this issue.  There are some tutorials online showing that the Attachments dropdown would show on the Direct to Contact Email Modal but as of v 4.4.9, sadly, it does not show.  We are also currently using text links on the body to link to the Asset but would prefer to use the Attachment dropdown.  I am available to help troubleshoot if we could get this opened back up.  Thanks.

**Comment by RCheesley** [comment]
Thanks for being willing to troubleshoot, can you try to reproduce it on Mautic 5 please? Instructions can be found at https://mau.tc/tester.

**Comment by RCheesley** [comment]
Closing this old issue due to lack of responses. Feel free to request a re-open.
