### ISSUE TITLE
[bug] 'Last Active' resets count on 30+ day 

### ISSUE THREAD

**Issue by kianabeauty** [mautic/mautic#935]
**Issue:** The 'Last Active' column in the _list_ view resets the count of days in 30 day increments.
i.e. If a user was last active 31 days ago, Mautic will display 1 days ago in the last active column.

![Screenshot of Last Days Column](http://i.imgur.com/1l21464.png)

Other than resolving this count to the exact date, other solutions could involve putting the actual date in the _last active_ column. 

Date filtering is a bit of an issue with the current Mautic system, so that may be a feature request in future updates to improve the CRM aspect of Mautic.

**Version:** 1.2, Hosted

Also reported on https://www.mautic.org/community/index.php//823-bug-last-active-resets-count-on-30-day

**Comment by alanhartless** [comment]
Fixed and will be part of 1.2.1.
