### ISSUE TITLE
Postpone weekend emails

### ISSUE THREAD

**Issue by reg3project** [mautic/mautic#9350]
I have a business case where I need to send my emails like the following:

1. When someone submits a form, I need this to happen
2. If it is a weekday, I need to send the first email after two hours of submission.
3. If it Friday to Tuesday I want to send another email after 72 from the submission date.
4. If it is Wednesday or Thursday, I want to wait for Monday. It means if Wednesday wait 120 hours, if Thursday wait 96 hours.

I tried several solutions including:
1. Jumping within a campaign.
2. Have a chain of campaigns

None of the above solutions worked, how do you suggest I do it? would it require extra coding to be done?

**Comment by elilogan** [comment]
Probably have to split this into 2 campaigns. I believe you can open the email step within campaign and select the dates and times you wish to send. You can also set a cron job to send a specific email at a specific time.  I’m not certain this will fit all of your very specific requirements but it’s the closest thing to a solution as far as I know.

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
