### ISSUE TITLE
Adjusting points from Form

### ISSUE THREAD

**Issue by eVolpeConsultingGroup** [mautic/mautic#9351]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.1.2
| PHP version | 7.3
| Browser | Google Chrome

### Steps to reproduce
1. Create Contact with Last Name and Email filled and 0 Points
2. Create Standalone Form with 
2.1. 'Email' field mapped with 'Contact Email'
2.2. 'Adjust contact's points' action, Operator: add(+), Amount to change points by (for example): 9
3. Create Landing page and in Builder add Form (from step 2.)
4. Open Page URL of Landing Page in browser and submit form using Email of Contact (from step 1.)
5. Contact (from step 1.) will:
5.1. receive 'Form submitted' event, so it is correct
5.2. receive 'Point gained' event but not receive 9 points (Contact will still have 0 points), so it is incorrect
6. It happens only when Contact has 0 points before Form submitting
 
### Log errors
No errors in logs. Probably the 0 points before and 9 after are swapped: 9 before and 0 after Form submitting in adjust points logic.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Tested in 3.2.1 and unable to reproduce.

Before:

![screenshot-mautibox com-2020 12 11-15_16_35 (1)](https://user-images.githubusercontent.com/2930593/101920699-047f1c00-3bc4-11eb-9fc0-e21faf9902bd.png)

After:

![screenshot-mautibox com-2020 12 11-15_16_35](https://user-images.githubusercontent.com/2930593/101920718-09dc6680-3bc4-11eb-81ac-f4e38e4b7cef.png)
