### ISSUE TITLE
"1" instead of AnalyticsScript included

### ISSUE THREAD

**Issue by tiwaszkiewicz** [mautic/mautic#9352]
## Bug Description
If AnalyticsScript is configured under LandingPageSettings, 
the expected AnalyticsScript are not visible on LandingPages (template based nor script-mode based)

Instead of scripts the character "1" (one) appears (see it on screenshot) 

<img width="569" alt="Zrzut ekranu 2020-10-30 o 13 12 24" src="https://user-images.githubusercontent.com/47384466/97713147-ba345680-1abf-11eb-85aa-aad1cf3a1ec4.png">

| Q   | A
| --- | ---

| Mautic version | 3.1.1 (3.0.2 also)
| PHP version | PHP Version 7.3.22-1+ubuntu18.04.1+deb.sury.org+1 
| Browser | all

### Steps to reproduce
1. Go to Configuration -> Landing Page Settings  (https://mautic-address/s/config/edit#pageconfig)
2. Put analytics tracking code (or any other string) in Analytics script pane 
3. Try random LandingPage form mautic instance

<img width="1054" alt="Zrzut ekranu 2020-10-30 o 15 05 21" src="https://user-images.githubusercontent.com/47384466/97714385-5f9bfa00-1ac1-11eb-8585-637170ce2839.png">

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by steve3g** [comment]
This appears to be the same issue as #9192. I confirmed that removing the Analytics Script also removes the '1'

**Comment by npracht** [comment]
Please test https://github.com/mautic/mautic/pull/9389

**Comment by RCheesley** [comment]
As this has been merged for the next release I'm going to close the issue!
