### ISSUE TITLE
Duplicate Tag in Builder

### ISSUE THREAD

**Issue by fredroo** [mautic/mautic#9353]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )
![69d8cc3a-a496-44f6-967e-7d0f26b24ba4](https://user-images.githubusercontent.com/6863089/97730415-93bbee80-1ab2-11eb-9fa2-0239222226f0.png)

## Bug Description
The more details the better...
Duplicate Tag in Builder

| Q   | A
| --- | ---
| Mautic version |  v3.1.1
| PHP version |  7.3
| Browser |  Google Chrome 86.0.4240.111 - 64 bits

### Steps to reproduce
1. Open New Builder Mail Empty
2. Apply
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
@fredroo would you be up for taking a look into what is causing this, if it is persisting in 3.2.1?
