### ISSUE TITLE
We don't support upgrading with the upgrade script in this scenario

### ISSUE THREAD

**Issue by vesper8** [mautic/mautic#9356]
Hello awesome developers, I read the upgrade notes but it doesn't address my concerns so that's why I'm posting here..

I've been using Mautic for over 2 years, I guess I must have installed it by cloning from github at the beginning, it's been over 2 years. I've run multiple updates via the CLI since then, but now I'm getting this scary looking warning when attempting to update from 2.16.3 to v3

It recommends to first download the package from https://github.com/mautic/mautic/releases/tag/2.16.3 and to "reinstall that" but I would like more details on how exactly to do that

First of all, on that link https://github.com/mautic/mautic/releases/tag/2.16.3 there is both a 2.16.3-update.zip and a 2.16.3.zip.. so which one should I get?

Then, is it safe to just unzip this package in my current "originally cloned from Github" directory ? Will this rectify the scary warning?

Or am I supposed to unzip it in a completely different folder, and then copy over the `app/config/local.php` file so that it can connect to my existing database? 

If I do have to unzip in a different folder.. is there anything else I need to "bring in" to this folder aside from the `local.php` file? Another post I saw mentioned "all you have to do is import your assets" but I have no idea what this means or implies.

Is there another way? Such as installing a fresh standalone version of v3 and then having this version link to my v2.16.3 database and have it apply all the transformations/migrations necessary? Or is the only way forward to do the 2.16.3 -> 3 upgrade?

Also, while attempting to run `php upgrade_v3.php` I got this warning as well `mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces`

I already assigned all privileges to the database user specified in `local.php` except the "GRANT OPTION" which is standard. So I don't know why this warning is occurring.. although I did already do a manual backup of my database so perhaps this one can be ignored though I would have preferred to get to the bottom of that one too and fix whatever needs fixing.

Many thanks for your time

**Comment by npracht** [comment]
>First of all, on that link 2.16.3 (release) there is both a 2.16.3-update.zip and a 2.16.3.zip.. so which one should I get?

2.16.3-update.zip to update, 2.16.3.zip to install a fresh installation.

I'll encourage you to move your discussion to forums or Slack to chat with other developers.
Thanks
