### ISSUE TITLE
Link to latest 3.x release

### ISSUE THREAD

**Issue by ikolubr** [mautic/mautic#9361]
Guys, do we have a link that points to the latest release of Mautic 3.x? Like we have/had for 2.x?

Like this one that always points to the latest 2.x: https://www.mautic.org/download/latest

If yes, could you please let me know what is it?

Thank you,

**Comment by RCheesley** [comment]
Hi there,

You can get the releases from Github, there are quite a few examples of how to do this [on Google](https://www.google.com/search?q=get+latest+release+github).

Thanks for flagging this, I'll get that URL updated as we haven't used the web-based files for releases since 3.x.
