### ISSUE TITLE
Invalid scope during Instagram authentication

### ISSUE THREAD

**Issue by blazzzz** [mautic/mautic#9369]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When trying to authorize the Instagram plugin using client ID and secret it returns error message: Invalid scope
Seems like the plugin doesn't sends the parameter "scope" as described in Instagram Basic Display API Documentation.

![image](https://user-images.githubusercontent.com/40625037/98109381-c0e71300-1e9d-11eb-80bf-cdedfb8fcb40.png)

| Q   | A
| --- | ---
| Mautic version | 3.1.0
| PHP version | 7.3.23-1
| Browser | Firefox 82.0

### Steps to reproduce
1. Create a new app in the Facebook Developer portal
2. Add the Instagram Basic Display product
3. Add Instagram tester account
4. Publish the app
5. Go to Manage plugins, then Instagram
6. Try to authenticate using the ID and password of the Facebook app
7. Get the error Invalid scope
 
### Log errors

No error is logged

**Comment by RCheesley** [comment]
This has been an issue since Instagram changed their API - the integration needs to be updated.
