### ISSUE TITLE
Error in Form radio field value condition

### ISSUE THREAD

**Issue by wderuijter** [mautic/mautic#9370]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Form submission condition always returns false due to text/value fail

| Q   | A
| --- | ---
| Mautic version | 3.1.1
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1. create a form with a radio button
2. add items with different Label and Value 
![screenshot-mtc roc-nijmegen nl-2020 11 04-19_26_48](https://user-images.githubusercontent.com/618804/98154198-b98f2c00-1ed4-11eb-810e-afa28f78cdeb.png)
3. Save the form and create a campaign
4. In this campaign create a condition Form field value
5. Select the form you made and the field you want to use for the condition. You will see in the Value field the Labels are show, and not the Values.
![screenshot-mtc roc-nijmegen nl-2020 11 04-19_29_17](https://user-images.githubusercontent.com/618804/98154445-14288800-1ed5-11eb-8a5e-f26483f9aefd.png)
6. Click the +Add button, an error shows: _This value is not valid._. And now suddenly the radio field's values are show in the Value field.
![screenshot-mtc roc-nijmegen nl-2020 11 04-19_29_38](https://user-images.githubusercontent.com/618804/98154595-4d60f800-1ed5-11eb-9639-caf57d765d27.png)
7. Click the _Update_ button and the condition gets saved properly.
8. Test the campagne and notice the condition always fails.
9. Head back to the form's radio field, change both the Value and Label of the radio items to the same value, for example 16-11-2020 and 19-11-2020 and start at step 3. again. Now saving the campagne condition will not throw an error (because value and label are identical). And the condition in the campagne will work as expected.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @wderuijter i think this is fixed by https://github.com/mautic/mautic/pull/9348
Can you test it and add a review on the PR ?
Thanks !

**Comment by wderuijter** [comment]
@npracht tested with https://mautibox.com/9348. Works, added a review on the PR.

**Comment by npracht** [comment]
thanks for confirmation

**Comment by npracht** [comment]
Fixed in 3.2.2
