### ISSUE TITLE
the offset at GET “SENT EMAIL TO CONTACTS” WIDGET will be ignored

### ISSUE THREAD

**Issue by laabidi21** [mautic/mautic#9374]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version 3.1.2| 
| PHP Version 7.2.33 | 
| cURL Information 7.47.0|
|-- | --

| 

### Steps to reproduce
$api        = new MauticApi();
$dataApi = $api->newApi("data", $auth, $apiUrl)

$campaignId = 87;
$dateTo = "2020-11-06";
$dateFrom = "2020-09-25";
$limit = 1;
$offset = 0;
$options = ['dateFrom' => $dateFrom, 'dateTo' => $dateTo, 'timeUnit' => "m", 'filter' => ['campaignId' => $Campaign_id],
            'limit' => $limit, 'offset' => $offset];
$WIDGETS = $MauticAPI->get('sent.email.to.contacts', $options);

http://172.16.8.123/api/data/sent.email.to.contacts?dateFrom=2020-09-25&dateTo=2020-11-05&timeUnit=m&filter%5BcampaignId%5D=87&limit=1&offset=0

{
   "success":1,
   "cached":false,
   "execution_time":0.008898019790649414,
   "data":{
      "headItems":[
         "mautic.dashboard.label.contact.id",
         "mautic.dashboard.label.contact.email.address",
         "mautic.dashboard.label.contact.open",
         "mautic.dashboard.label.contact.click",
         "mautic.dashboard.label.contact.links.clicked",
         "mautic.dashboard.label.email.id",
         "mautic.dashboard.label.email.name",
         "mautic.dashboard.label.segment.id",
         "mautic.dashboard.label.segment.name",
         "mautic.dashboard.label.company.id",
         "mautic.dashboard.label.company.name",
         "mautic.dashboard.label.campaign.id",
         "mautic.dashboard.label.campaign.name",
         "mautic.dashboard.label.date.sent",
         "mautic.dashboard.label.date.read"
      ],
      "bodyItems":{
         "411":{
            "contact_id":"74",
            "contact_email":"test2222@isc-ub.de",
            "open":"0",
            "click":"0",
            "links_clicked":[
               
            ],
            "email_id":"43",
            "email_name":"Email11",
            "segment_id":"69",
            "segment_name":"All Contacts",
            "company_id":"132",
            "company_name":"Mautic_ZL_Test20201023T1140",
            "campaign_id":"105",
            "campaign_name":"test20201110T1110",
            "date_sent":"2020-11-10 10:11:39"
         }
      }
   }
}

AND if I change the offset to 1
http://172.16.8.123/api/data/sent.email.to.contacts?dateFrom=2020-09-25&dateTo=2020-11-05&timeUnit=m&filter%5BcampaignId%5D=87&limit=1&offset=1

Reponse: 
{
   "success":1,
   "cached":false,
   "execution_time":0.008898019790649414,
   "data":{
      "headItems":[
         "mautic.dashboard.label.contact.id",
         "mautic.dashboard.label.contact.email.address",
         "mautic.dashboard.label.contact.open",
         "mautic.dashboard.label.contact.click",
         "mautic.dashboard.label.contact.links.clicked",
         "mautic.dashboard.label.email.id",
         "mautic.dashboard.label.email.name",
         "mautic.dashboard.label.segment.id",
         "mautic.dashboard.label.segment.name",
         "mautic.dashboard.label.company.id",
         "mautic.dashboard.label.company.name",
         "mautic.dashboard.label.campaign.id",
         "mautic.dashboard.label.campaign.name",
         "mautic.dashboard.label.date.sent",
         "mautic.dashboard.label.date.read"
      ],
      "bodyItems":{
         "411":{
            "contact_id":"74",
            "contact_email":"test2222@isc-ub.de",
            "open":"0",
            "click":"0",
            "links_clicked":[
               
            ],
            "email_id":"43",
            "email_name":"Email11",
            "segment_id":"69",
            "segment_name":"All Contacts",
            "company_id":"132",
            "company_name":"Mautic_ZL_Test20201023T1140",
            "campaign_id":"105",
            "campaign_name":"test20201110T1110",
            "date_sent":"2020-11-10 10:11:39"
         }
      }
   }
}

It always gives the "contact_id":"74". despite if i change limit to 30, it will gives 19 ['data']['bodyItems'].

I think the offset in this call will not be taken.

it will give a single ['data']['bodyItems'] but will always start from the beginning. and not by the index 1 or 2
 
the question is: how I can call Widgets in an offset and limit call ?

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by Ziedpad** [comment]
@npracht do you have an explanation for this? maybe the composer is changed from version 2 to version 3?

**Comment by laabidi21** [comment]
if we change the offset to 10 and the limit to 100. the request will start from 0 and limit 100. but it must start with 10 (&offset=10).

**Comment by Ziedpad** [comment]
@RCheesley @npracht  the call of the widgets with the offset is generated? ?

**Comment by ziedMauticMecanik** [comment]
I have the same problem. to collect Widgets ('sent.email.to.contacts'). It always starts with offset 0, although I gave an offset = 10

**Comment by npracht** [comment]
@laabidi21 would you dig into it and try to fix it with a PR ?

**Comment by laabidi21** [comment]
@npracht frankly, I will not succeed in making the necessary changes. Sorry
