### ISSUE TITLE
Cannot Edit Dashboard Widgets

### ISSUE THREAD

**Issue by yesblogger** [mautic/mautic#9378]
## Bug Description
Widgets on the dashboard cannot be edited. When the edit button is clicked it gets stuck on the loading page. Happens with all widgets. 

![Screenshot_1](https://user-images.githubusercontent.com/25710585/98520433-09387380-2298-11eb-9343-7d698b282422.png)

| Mautic version | 3.1.2
| PHP version | 7.2.34
| Browser | 

### Steps to reproduce
1. Go to the dashboard
2. Click on edit from a widget.

**Comment by npracht** [comment]
Hi,

What is the message in your logs ?
Thanks

**Comment by yesblogger** [comment]
Resolved, wrongly entered HTTP instead of https in the site URL.
