### ISSUE TITLE
Mautic login page flagged a phishing website by Netcraft 

### ISSUE THREAD

**Issue by evgu** [mautic/mautic#9379]
## Bug Description
This morning we weke up to a nightmare, where Mautic login page and the entire Mautic hosting domain were flagged as a phishing page by Netcraft. This consequently flagged all pages on our main website as phishing due to Mautic's mtc.js. As most major web brousers use the Netcrafts phishing websites feed, then quickly all major browsers started red-flagging our website. 

<img width="1070" alt="Screenshot 2020-11-09 at 10 51 12" src="https://user-images.githubusercontent.com/18371928/98526124-af28b580-2279-11eb-8575-180320a047da.png">

Speaking to Netcraft, they explained that this is due to what is seen as misrepresntation on the footer of the standard Mautic login page: "Copyright 2020 Mautic. All Rights Reserved.". 

<img width="707" alt="Screenshot 2020-11-09 at 10 56 54" src="https://user-images.githubusercontent.com/18371928/98526748-70472f80-227a-11eb-90e6-3ed344dbdf79.png">

What they say is that it should at least mention the Company hosting the Mautic instance. As currently worded, it can be seen that any Mautic instance misleads a nonsuspecting user that this is the Mautic website login page (as opposed to Mautic instance hosted on another company's domain). 

**Solution Suggestion:** 
Would suggest for the Acqua legal team to reword the footer message and/or to add a field for the company name hosting the instance.

**Comment by npracht** [comment]
@mautic/acquia-po this one it for you ?

**Comment by RCheesley** [comment]
@evgu thanks for reporting this. As this is just one login page and many tools have exactly the same across the whole website (e.g. look at most of the CMS systems which will often have similar copyright notices) I don't think this is the cause of the problem.  We have seen some issues with Google flagging the tracking script as malicious as well, but we're struggling to pin that down (see #7524) which I would think is much more likely what you're experiencing.

If this is a problem for you and it definitely relates to the Mautic login page, I'd suggest making an override to customise the landing page, or even restricting access to it and preventing bots from crawling it.

**Comment by evgu** [comment]
@RCheesley this issue showed up once only for us. The JS tracking script was flagged as the main offender within the browser. But when I spoke to Netcrafts (the company which flags websites for the browsers to block) they pointed me to the Copyright notice. I spoke to them several times trying to get to the bottom of the root cause of the issue, but got back no concrete technical explanation what triggered the block, just the Copyright notice. I gave them pretty much the same feedback as yours, as their reasoning seemed rather unfounded.
