### ISSUE TITLE
Pipedrive never updates exiting leads/contacts/companies

### ISSUE THREAD

**Issue by janwinkler** [mautic/mautic#9381]
Issue in: https://github.com/mautic/mautic/blob/075c718194d13e2200e741123969724b94b04838/plugins/MauticCrmBundle/Integration/Pipedrive/Import/LeadImport.php#L52

Pipedrive sync will always only create new contacts but never update existing updates.

Line:
        if ($integrationEntity) {
            throw new \Exception('Lead already have integration', Response::HTTP_CONFLICT);
        }

should be replaced with:
        if ($integrationEntity) {
            return $this->update($data);
        }

(same in import of companies)

**Comment by RCheesley** [comment]
@janwinkler another one here, please make a PR to address this, if it isn't already addressed by one of the [open PR's relating to Pipedrive](https://github.com/mautic/mautic/pulls?q=is%3Apr+is%3Aopen+pipedrive). Then we should be able to get it tested and merged in a future release!

**Comment by powertictech** [comment]
@RCheesley same here

**Comment by RCheesley** [comment]
> @RCheesley same here

Sorry, what is the same here?
