### ISSUE TITLE
Issue getFields on Pipedrive API intergation

### ISSUE THREAD

**Issue by janwinkler** [mautic/mautic#9383]
https://github.com/mautic/mautic/blob/32401017622b13c7bb80331e6e821667c74d8aa6/plugins/MauticCrmBundle/Api/PipedriveApi.php#L184

Line seems incorrect, will result in giving back the HTTP Response when called multiple times instead of the response data. Change it to:

        $data = $this->getResponseData($response);
        $this->apiFields[$object] = !empty($data) ? $data : [];
        return $this->apiFields[$object];

**Comment by RCheesley** [comment]
@janwinkler thanks for this, same applies to my other response. Please can you give a bit more detail, and make the PR if you can fix this? Please check the [open PR's](https://github.com/mautic/mautic/pulls?q=is%3Apr+is%3Aopen+pipedrive) beforehand to make sure it hasn't already been addressed - if it has please give a report on the PR so we can look at merging in the next release!
