### ISSUE TITLE
PHP Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set

### ISSUE THREAD

**Issue by vikijel** [mautic/mautic#939]
Please, implement some workaround for CURLOPT_FOLLOWLOCATION.

Secure servers always have open_basedir configured and classes like app/bundles/AssetBundle/Entity/Asset.php are unable to fetch remote storage files.

Workarounds: https://www.google.com/search?q=curlopt_followlocation+workaround

Something like this:

```php
if (ini_get('open_basedir') == '' && strtolower(ini_get('safe_mode')) == 'off')
{
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_exec($ch);
}
else
{
    //use workaround function (which calls curl_exec without followlocation opt + checks response header with Location: xxx and repeats curl request to xxx until response is without Location header and finally returns last curl_exec response)
}
```

Thank you very much!

PS: We successfully use workaround similar to curl_redirect_exec function here: http://stackoverflow.com/questions/3890631/php-curl-with-curlopt-followlocation-error

**Comment by escopecz** [comment]
Could you check if the issue is still there with this PR if you have a chance to test it?

https://github.com/mautic/mautic/pull/965

Joomla Framework should take care about it:

https://github.com/joomla-framework/http/blob/548e56d882b5d9bff98a9c0e275e25945285625a/src/Transport/Curl.php#L157-L160

**Comment by alanhartless** [comment]
Just following up on this to see if it is still an issue in the latest versions or if we can close the ticket?

**Comment by escopecz** [comment]
Closing for lack of feedback
