### ISSUE TITLE
List-Unsubscribe Header Not Included In emails (Sent With SES API)

### ISSUE THREAD

**Issue by Av1dLearner** [mautic/mautic#9393]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version |  3.1.2
| PHP version | 7.2.24
| Browser | Chrome

### Steps to reproduce
1. Send an email using SES
2. Check original headers for List-Unsubscribe
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by mabumusa1** [comment]
Solved by https://github.com/mautic/mautic/pull/9290
