### ISSUE TITLE
Form Submit gets stuck sometimes and won't reload for entire session.

### ISSUE THREAD

**Issue by bvanrhijn** [mautic/mautic#9396]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Your software
My Mautic version is: 3.1.2
My PHP version is: 7.3.24
My Database type and version is: 10.3.25

Your problem
I have landing pages setup with forms but forms submit unreliably. Sometimes it works sometimes it just gets stuck at loading. Last night it was working for hours during testing. Today no dice. 1 in two form submits fails continually and not just for a few seconds but for the entire session in that browser.

Forms and landing pages use the blank theme so it has no externall scripts and config on it that could stall submission.

Practically this does not make me hopeful that I’ll get any good responses to landing pages if Mautic keeps on being unpredictable in every way imaginable.

The error logs seem to imply that Mautic is having issues pushing data of unsupported data type into the log.

More detail here: https://forum.mautic.org/t/forms-stall-randomly-on-submit/16941

| Q   | A
| --- | ---
| Mautic version |  3.1.2
| PHP version | 7.3
| Browser | Chrome latest / Firefox latest

### Steps to reproduce
1. Install Mautic 3.1.2 
2. Create several landing pages with a different form that redirects to another Mautic landing page
2. Test it then wait a day and test again. Some work others don't No difference in how the form is setup.
 
### Log errors

    No errors in Mautic’s error log within 3hours

Apache error log reports:
[Mon Nov 09 16:37:50.114815 2020] [php7:error] [pid 696] [client 10.219.198.175:56722] PHP Fatal error: Uncaught TypeError: Argument 3 passed to Monolog\Logger::log() must be of the type array, null given, called in /var/www/html/app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php on line 424 and defined in /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php:610\nStack trace:\n#0 /var/www/html/app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php(424): Monolog\Logger->log(‘notice’, ‘PHP Notice - Un…’, NULL)\n#1 /var/www/html/app/bundles/CoreBundle/ErrorHandler/ErrorHandler.php(173): Mautic\CoreBundle\ErrorHandler\ErrorHandler->log(‘notice’, ‘PHP Notice - Un…’, NULL)\n#2 [internal function]: Mautic\CoreBundle\ErrorHandler\ErrorHandler->handleError(8, ‘PHP Notice - Un…’, ‘Unknown’, 0, NULL)\n#3 {main}\n thrown in /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php on line 610, referer: https://contact.nutriwise.co.za/s/forms/view/5
[Mon Nov 09 16:40:26.783479 2020] [core:notice] [pid 693] AH00051: child pid 696 exit signal Segmentation fault (11), possible coredump in /etc/apache2

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
A couple of questions:

1. Are you using any kind of web application firewall (e.g. with Wordpress or any other CMS)?
2. Is this persisting in 3.2.1?
3. Are there any errors in your browser console?
4. Does it happen in an incognito window?
