### ISSUE TITLE
Mautic API get Contacts/Events (getActivity) With Filters Campaign_ID or Email_ID

### ISSUE THREAD

**Issue by ziedMauticMecanik** [mautic/mautic#9397]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version  3.1.2| 
| PHP version 7.2 | 
| Browser | 

### Steps to reproduce
1. 
$includeEvents = array(
		'email.sent',
		'lead.donotcontact',
		'page.hit'
	);
$excludeEvents = array();
$dateTo = "2120-11-05";
$dateFrom = "2020-09-25";
$orderBy = '';
$orderByDir = 'ASC';
$page = 1;
$search = ???????
$events = $contactApi->getActivity($search, $includeEvents, $excludeEvents, $orderBy, $orderByDir, $page, $dateFrom, $dateTo);

how can I filter events from campaign_id or email_id in the $search variable? and what should I write in this variable?

### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @ziedMauticMecanik please move your discussion to slack and/or forums.
Thanks !
