### ISSUE TITLE
Mautic editor shows text left justified but arrive in mobiles as centered

### ISSUE THREAD

**Issue by bulgin** [mautic/mautic#9401]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

Your problem
My problem is:
When composing emails using Mautic editor, I can easily see what is and what isn’t justified center or justified left, etc. However, left justified text which shows as left justified in the editor is arriving in mobile devices as centered, yet the same email arrives in mail clients as properly left justified.

This happens in both android and iPhones.

This happens even when just sending the sample templates with no input changes.

See attached screen grabs.
| Q   | A
| --- | ---
| Mautic version | v3.1.2
| PHP version | 7.3.23
| Browser 

My Database type and version is:mysqlnd 5.0.12-dev

### Steps to reproduce
1. Create any email with the editor and introduce a paragraph with say, about 10 lines or so.
2. Left justify the text. Confirm it is left justified in Mautic editor.
3. View in email client see that text is left justified.
4. View in desktop computer mail client like Thunderbird or other and see that paragraph is left justified.
5. View in mobile either both Android or iPhone or just one or the other and see that the paragraph is centered, not left justified as it should be.

As viewed in Mautic editor when composing:
![8949a3a124520a2010b908fd856f2e9a3619b07f_2_451x500](https://user-images.githubusercontent.com/16614115/99004848-be279600-250d-11eb-8949-00f7337a688d.png)

As viewed in mail client (Thunderbird):
![e75ff5a61f8744f3548012d973d442dd2503491c_2_343x500](https://user-images.githubusercontent.com/16614115/99004850-bec02c80-250d-11eb-81fc-2b3d38b49b4f.png)

As viewed on Android and iPhone (notice text is centered, not left justified.
![2f6d308d554f082ca21d7937c73f393953b92658_2_281x500](https://user-images.githubusercontent.com/16614115/99004852-bec02c80-250d-11eb-9bd7-65deef078d3b.png)

 
### Log errors
none present

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
@bulgin it sounds like this is something to do with the media queries in the theme you are using switching up to center align at smaller resolutions. If this is a core Mautic theme, would you be up for having a dig and seeing if you can fix it?
