### ISSUE TITLE
URLs dont become trackable links, when <a> tag spans more than one line (includes a line break)

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#9408]
## Bug Description
We used the Code Mode and an E-Mail generated by MJML Builder.
For whatever reason MJML Builder sometimes creates <a> html link tags, which spanned more than one line.  So it contains a line break between < and >.

`            <a href="https://REMOVED" target="_blank"
               style="display:inline-block;background:#c80f37;color:#ffffff;font-family:Georgia, Helvetica, Arial, sans-serif;font-size:13px;font-weight:normal;line-height:120%;margin:0;text-decoration:none;text-transform:none;padding:10px 25px;mso-padding-alt:0px;border-radius:3px;"
            >
              LINKTEXT REMOVED 
            </a>`

This leads to the situation, that the link will not be converted into a trackable link.

| Q   | A
| --- | ---
| Mautic version |  3.1.2
| PHP version | 7.3.x

### Steps to reproduce
1. Create a link which contain several lines within the opening <a> tag
2. Send the mail and see, that the link doesn't get converted
 
### Log errors
might be related:

[2020-11-15 11:25:21] mautic.ERROR: Invalid clickthrough value: Yjo4OntmOjk6ImZiaGVkZiI7Yjo1Ont2OjM7Zjo0NzoiZGJ6Y2J2dGEuZmlmYWciO3Y6NDt2OjU7fWY6ODoiZnpidnkiO3Y6NDQ7Zjo3OiJmZ2JnIjtmOjU1OiI4YWM0NDM0ODE3OWZmOTEwNTUzODM0IjtmOjc6InlmYmUiO2Y6NjoiNjkwIjtmOjA6ImR1YmFhZnkiO2I6NDp7Zjo4OiJmemJ2eSI7djo0NDt9fQ== {"exception":"[object] (Mautic\\CoreBundle\\Exception\\InvalidDecodedStringException(code: 0): The string b:8:{f:9:\"fbhedf\";b:5:{v:3;f:47:\"dbzcbvta.fifag\";v:4;v:5;}f:8:\"fzbvy\";v:44;f:7:\"fgbg\";f:55:\"8ac44348179ff910553834\";f:7:\"yfbe\";f:6:\"690\";f:0:\"dubaafy\";b:4:{f:8:\"fzbvy\";v:44;}} is not a serialized array at /REMOVED/app/bundles/CoreBundle/Helper/ClickthroughHelper.php:46)"} []

**Comment by dsp76** [comment]
(the line breaks don't show up in the copied code, but in the code editor)

**Comment by dsp76** [comment]
Just for reference - in parallel I try to find out why MJML behaves this way: https://stackoverflow.com/questions/64899475/is-there-a-reason-that-mjml-renders-e-g-opening-a-tags-across-several-lines

**Comment by dsp76** [comment]
https://stackoverflow.com/questions/3314535/white-space-inside-xml-html-tags ... it should not be an issue that tag span more than one line.  thus mautic should not have a problem to encode an URL for tracking, when its inside a tag that spans multiple lines.

**Comment by npracht** [comment]
@kuzmany maybe you can share an advise with @dsp76, we fixed that on our side right ?

**Comment by janus-reith** [comment]
Any news on this? @npracht @kuzmany If you have fixed this, could you share the changes involved to get this working? :)

**Comment by rutherfordiummichahellis** [comment]
Any news on this issue? We're having problems with this when generating our e-mails.

Mautic version: 4.4.2

**Comment by kuzmany** [comment]
This should fixed it https://github.com/mautic/mautic/pull/11401
