### ISSUE TITLE
Gotowebinar: token {webinar_button} is just a label without link

### ISSUE THREAD

**Issue by incentfit-product** [mautic/mautic#9411]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
According to the [docs](https://mautic.org/docs/en/plugins/citrix.html), we should be able to use {webinar_button} and {webinar_link} tokens in emails to fill in the customized join link for a GoToWebinar.  Unfortunately this isn't working at all.  In all my test emails, the {webinar_link} button is replaced with nothing and the {webinar_button} is replaced with a styled button that has no href.

| Q   | A
| --- | ---
| Mautic version | 3.1.2
| PHP version | 7.2.24
| Browser | Chrome 86

### Steps to reproduce
1. Follow the instructions at https://docs.mautic.org/en/plugins/citrix#update-join-gotowebinar-button-token in the Update: Join GoToWebinar button token.
2. The last step says the token should be replaced, but it isn't.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by incentfit-product** [comment]
FYI...this appears to have happened before [here](https://github.com/mautic/mautic/issues/3953)

**Comment by incentfit-product** [comment]
After doing some more digging, it appears the problem is that the current {webinar_button} and {webinar_link} tokens are only supposed to work if the email is a part of a campaign that is based on a segment that has within it a filter to only include contacts that have registered for a webinar.  The system is supposed to throw an error to the user if they try to add the tokens to an email that doesn't match that criteria.  However, this functionality appears to be broken as both myself and #3953 experienced.  This appears to have been broken since the [PR that introduced GoToWebinar tokens](https://github.com/mautic/mautic/pull/3817) was introduced in 2017.

All that being said, this architecture seems pretty bad.  Rather than fixing the error, I think the token should just work without an associated segment.  That would alleviate confusion and add a lot of functionality.

**Comment by gabepri** [comment]
Looking through the code, the documentation that says the {webinar_link} and {webinar_button} tokens are only supposed to work in tandem with a webinar filter on a segment is true only in the case of a segment email.  For campaign emails, those tokens are supposed to just pull the last webinar the contact registered for regardless of any segments.

Everything appears to work fine if the contact registers via GoToWebinar and then the registration is synced to Mautic via cron.  However, if the registration is done via a Mautic form that then sends the registration info to GoToWebinar, the join URL itself is not saved in the database.  Therefore it cannot be inserted into emails.  I'm preparing a pull request to solve this.

**Comment by npracht** [comment]
@incentfit can you please test #9477 ?

**Comment by incentfit-product** [comment]
it worked!

**Comment by gabepri** [comment]
don't think this is stale.  there is a pull request that works that has yet to be approved.
