### ISSUE TITLE
Amazon SES host: sa-east-1 not available 

### ISSUE THREAD

**Issue by pbdco** [mautic/mautic#9414]
email-smtp.sa-east-1.amazonaws.com is not included in the dropdown list. If I add it mannualy it gives "This value is not valid."

![image](https://user-images.githubusercontent.com/64397076/99414584-b719d280-28d5-11eb-93ee-ef36cc996545.png)

**Comment by mabumusa1** [comment]
@pbdco would like to start a PR to add this region?

**Comment by pbdco** [comment]
https://github.com/mautic/mautic/pull/9446

**Comment by saitanay** [comment]
@pbdco @mabumusa1 

1. **amazon_region.sa_east_1** is the same as **South America (São Paulo)** - which is available as an option in the drop down. Can you try with that and confirm if you are able to configure and if it is working. 

Ref - https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-availability-zones

<img width="602" alt="image" src="https://user-images.githubusercontent.com/3456349/103210078-a6279c80-492a-11eb-960b-4342c0d99f76.png">

2. Further, even in the case of an unavailable/ new region, you should be able to use the **Other Region** option
<img width="956" alt="image" src="https://user-images.githubusercontent.com/3456349/103210133-d838fe80-492a-11eb-8e05-6922a9f870c7.png">


Both the above options should work for sa-east-1 . Can you give them try and confirm if that works?
