### ISSUE TITLE
External Cron Jobs

### ISSUE THREAD

**Issue by patricksimonian** [mautic/mautic#9416]
Hi I'm not sure where to put this. I have been working on an install in an Openshift Environment and have a question about Cron jobs...

In most containerized environments you do not have control of when your containers will quit and be brought back up. It's a process that is out of your hands in the case of processes like k8s which will schedule new workloads across different host machines. 

My question is, will the cron job process in mautic handle these interruptions to the container?

**Comment by npracht** [comment]
Hi @patricksimonian, please move your discussion to Slack or Forum ;)
