### ISSUE TITLE
Field order on form - update not saved

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#942]
Hi,

I've created a campaign form with 3 inputs:
- Last name (text)
- Email (email)
- Description area

1. I save.
2. Then i edit.
3. I try to modify the field order by drag and drop.
4. Save.
5. Come back.
6. The field order change has not been saved.

____

We tried to modify directly in the MySQL database the field named "field_order" ---> Here it works.

Can you help ?
Thanks,

N.

**Comment by escopecz** [comment]
I was able to recreate the issue

**Comment by juliopontes** [comment]
I was able to recreate the issue too.

**Comment by alanhartless** [comment]
Fixed and will be part of 1.2.1.

**Comment by tudormateescu** [comment]
I have again the same problem in latest version. The order is not saved after drag and drop the order of the forms.

**Comment by jbacarro** [comment]
Same issue on the latest version.
