### ISSUE TITLE
Discussion: Kubernetes/Openshift Ready deployment of Mautic

### ISSUE THREAD

**Issue by patricksimonian** [mautic/mautic#9426]
## Description:
Our team is working on converting the mautic app into a kubernetes/openshift ready deployment fully set up with redudancy in the form of multiple containers for each microservice (mautic app and the mysql database). The work is very much in progress still but i'd love to share our work when ready. We are using Redhat Openshift 4.5 at the moment and the infrastructure will be based on that platform. It will however be *mostly* compatible with a native kubernetes cluster as well. 

My question is: 

__Once we have a verified, well running, deployment of Mautic in a containerized environment, what would be the best way to contribute to the project?__

## Architecture Summary

Our goal for our deployment of Mautic is to set up infrastructure for a

- 3 pod mautic deployment that shares its cache/logging
- 3 pod mysql cluster for high availability
- k8s ready apache config (run on a non privileged port etc)
- backup strategies for the database as well as logging
- log surfacing to other monitoring apps such as prometheus and or sysdig
- automated mautic redeployment so that there is minimal manual intervention to install the app
- removing specific user permissions from the deployment since K8s provides random users when running pods
- probably more that i'm forgetting

We most likely will not be able to touch on all these points as we lack the capacity but its a good north star

**Comment by mabumusa1** [comment]
@patricksimonian I would love to work with you on this
@mlahlouh and I been working on something similar we can share experiences with you

**Comment by RCheesley** [comment]
@patricksimonian @mabumusa1 if this is a discussion please could we take this to the forums for greater visibility at https://forum.mautic.org? The issue queue here is for bugs with Mautic so let's not crowd the queue with discussions.

**Comment by jordan8037310** [comment]
@patricksimonian we have completed most of this work for deploying Mautic with Helm 3 charts to AWS EKS. I plan to finalize my code review and open source next week. 

https://github.com/FacetInteractive/mautic-k8s is a placeholder

I need to separate our charts. We have some terraform templates in a separate repo. Our stack is LEMP, Redis, rabbitmq, and RDS as a database.

Feel free to reach out in Slack and let’s collaborate :)

**Comment by RCheesley** [comment]
Also, we have created #kubernetes on Slack :)
