### ISSUE TITLE
Email links getting replaced leading to broken links

### ISSUE THREAD

**Issue by afsalshameer** [mautic/mautic#9428]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

I tried adding a url to to emails. They are getting replaced by the following links which appears to be broken and is triggering Gmail spam filters.

http://url9156.motivesmedia.in/ls/click?upn=r1I3730w6uT5Y-2F1VS0EcEa6mVXyfIdORD1s4GHTFFGmFiirbW6nwIfkY6YGDQ4R-2B53sf0qOqcp1sMdeFmWbCPQ9IR2WbGVz7om2qClGMZ3H2jb-2BMYi10Cs4PIMVw-2BVCIVhIYDnmhf3sVkz9mxgcGALJQPWRFJm8-2FscN0sIbzITKqzKvFR3gAIUBXTDUsgN-2BVo6BYeB40YHYHS6soAu-2BendJzCPiH4ZdolH7v-2BxflDJtXqlHyjQlS5rtC-2Bdez3HbprER9j29g43oQGbQI7kr2cmf4y6Wb0MP-2BOZcmLc1j6SPxz9pOW0raMmyRInuXvrPM3CkgXC5DXqCDBcuVm3bVnaO8FLQpv1n590vO2sY2r9Lw7-2FyLTP9T2D-2FjXGzHD8vbRcmpQxXOg0ae-2BrEJ2RcZrA-3D-3D8LJs_JZHjo7Iyk6KmIbqvM4N7ab34zxuAK4n5HtR9OHOpxkngg7afD-2FZ2jVRmLFUmgoUskyBbE3Bi-2F9OO534waDayFbPUopg6tOQCst7vXZtbzcRBkET0dtqJ9gpbZap6lV8kJwSB6A3uktLZOKUYH5yxhy7cXkbbHf06zILRskCpPoSUZRIZRAZe5h-2Fgq8-2B2t-2BUA2n1YgKKrhMwmz61v0nfrra-2B50gwmSykieNdRVWRxFeE-3D

There are no log errors being shown.

Please tell me why this is happening and any solution to this problem. Thanks in advance.

**Comment by afsalshameer** [comment]
Someone please help

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
