### ISSUE TITLE
Delete Contacts in Mautic upon Deletion in Hubspot (data quality + gdpr issues)

### ISSUE THREAD

**Issue by ksoekhram** [mautic/mautic#9430]
I have connected Mautic with Hubspot, but when I choose to delete a contact in Hubspot, the contact remains in Mautic. 

This can lead to drop in data quality and issues with GDPR. 

Is this a bug or a feature?

Alternatively, is there a way to "tag" a contact in Mautic upon deletion in Hubspot?

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
