### ISSUE TITLE
Gated video showing play button above form

### ISSUE THREAD

**Issue by gabepri** [mautic/mautic#9431]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I created an mp4 gated video following the instructions [here](https://docs.mautic.org/en/gated-video).  Everything worked well except after the form shows up and pauses the video, the play button for the video is on top of the form so the user can just press play and not fill out the form.

| Q   | A
| --- | ---
| Mautic version | 3.1.2
| PHP version | 7.2.24
| Browser | Chrome 86

### Steps to reproduce
1. Follow [these instructions](https://docs.mautic.org/en/gated-video) to include a gated video either on landing page or on any site that has mautic enabled.
2. Play the video until the form shows up and you'll see the play button clickable above the form.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by gabepri** [comment]
This is exactly the same thing as this issue: https://github.com/mautic/mautic/issues/6745
This PR was supposed to fix it: https://github.com/mautic/mautic/pull/6750

But it didn't fix it, as [kmanojkumar commented](https://github.com/mautic/mautic/pull/6750#issuecomment-480895503).  Looks to me like the author had the right idea but the changes didn't also get made to the minified css file...

**Comment by RCheesley** [comment]
Thanks for raising this issue, hopefully we can get the PR merged in the next bugfix release!

**Comment by npracht** [comment]
Fixed by https://github.com/mautic/mautic/pull/9476 merged in 3.2.5. Released next Monday.
