### ISSUE TITLE
Unsubscribe count does not take the date range into account

### ISSUE THREAD

**Issue by nickveenhof** [mautic/mautic#9445]
[//]: # ( Invisible comment: 

## Bug Description
As you can see in the report, we get a suspiciously similar amount for each newsletter in terms of unsubscribes.
![image](https://user-images.githubusercontent.com/161341/100361241-3310ca80-2ffa-11eb-9248-1106f491c8e0.png)

When we look deeper in the database, this seems to be the total of unsubscribes for all times. This makes me wonder how the report query is constructed and does not take context such as newsletter nor date into account?

![image](https://user-images.githubusercontent.com/161341/100361189-22f8eb00-2ffa-11eb-9cfa-84748c452785.png)

| Q   | A
| --- | ---
| Mautic version | 
2.16 latest (upgrading to 3.x tomorrow, not sure if this solves it. Will report back here if so)
| PHP version | 
7.1
| Browser | 
Chrome

### Steps to reproduce
1. Create a report
2.Make sure someone unsubscribes from your email
3. Filter the report on a date later than the unsubscribe, look at how the number in your report doesn't change. 
 
### Log errors

No log errors

**Comment by nickveenhof** [comment]
Maybe related to https://github.com/mautic/mautic/pull/7088 but not entirely sure

**Comment by npracht** [comment]
Hi @nickveenhof did you update to a mautic 3.1 or 3.2 fixed it ?
I am quite sure https://github.com/mautic/mautic/pull/8478 in 3.0.1 fixes it.

I close it and reopen if after update you say it is still not fixed

**Comment by nickveenhof** [comment]
3.x solves this. Can indeed be closed!
