### ISSUE TITLE
"Cannot user scalar value as array" during installation

### ISSUE THREAD

**Issue by dhilst** [mautic/mautic#9448]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | staging
| PHP version | 7.4
| Browser | Chrome

### Steps to reproduce
1. Run the installer 

I faced this error 
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/392820/100460593-36619000-30a6-11eb-9fbb-922d935bd1d1.png">

Can anybody confirm? I quick fixed by doing this:

```
From ed79a647fd4a952f7f8a00cc0684cce06bc1d6ff Mon Sep 17 00:00:00 2001
From: Daniel Hilst Selli <danielhilst@gmail.com>
Date: Thu, 26 Nov 2020 20:23:03 -0300
Subject: [PATCH] Fix bug on installer

---
 app/bundles/InstallBundle/Install/InstallService.php | 1 +
 1 file changed, 1 insertion(+)

diff --git a/app/bundles/InstallBundle/Install/InstallService.php b/app/bundles/InstallBundle/Install/InstallService.php
index ee8658d8a..30b4939b0 100644
--- a/app/bundles/InstallBundle/Install/InstallService.php
+++ b/app/bundles/InstallBundle/Install/InstallService.php
@@ -334,6 +334,7 @@ class InstallService
                         'flashes');
                 }
             } catch (\Exception $exception) {
+                $messages          = [];
                 $messages['error'] = $translator->trans(
                     'mautic.installer.error.connecting.database',
                     ['%exception%' => $exception->getMessage()],
-- 
2.28.0
```

Can anybody confirm if this is a bug?

### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
@dhilst what is the mautic version you try to install?

**Comment by dhilst** [comment]
I was in staging branch, trying to migrate a plug-in, I'm not sure at what version, I will try with 3.2 branch, what you think?

**Comment by dhilst** [comment]
I tried at 3.2 branch, this commit 0fea369d5 to be precise and the problem persist

**Comment by RCheesley** [comment]
Hi there,

Seems this is the same issue I faced and documented here #9473 - it throws this error if the credentials are incorrect whereas it should handle it gracefully.

**Comment by ekkeguembel** [comment]
@RCheesley FYI, issue still exists in 4.0.0-alpha1

**Comment by RCheesley** [comment]
Please use #9473 to report issues - this one is closed as a duplicate of that issue.
