### ISSUE TITLE
Fully deployable artifacts in tar & zip archives?

### ISSUE THREAD

**Issue by ringular** [mautic/mautic#945]
I'm creating a chef-solo rep & cookbook to fully setup mautic on a remote server. Currently, the zipped & tar  archieves still require composer to be run. This gets challenging because user would need to generate a github access token.

Is it possible to have download artifacts already have dependencies installed?

**Comment by that0n3guy** [comment]
I'm pretty sure you don't need a github access token.  Try something like: 
`composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction`

We use this in docker and no github tokens are needed.

**Comment by escopecz** [comment]
Is there a problem to use the zip package from mautic.org? It has all vendor libraries in it. The latest version on GH is not meant to be used in production. For example production assets are not updated from the source files.

**Comment by ringular** [comment]
I had to do composer install before the app could run.
