### ISSUE TITLE
Mautic 3.x SAML 2.0 Not working with AWS SSO

### ISSUE THREAD

**Issue by Bibhudatta-Sahoo-ASMB** [mautic/mautic#9450]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I am using AWS SSO for SAML 2.0 Mautic login and done all the setup, but when try to login with AWS it is saying "`Invalid login. Please verify credentials.`".
But when check the console the URL  `https://my-domain/s/saml/login_check` giving `302 error` and then redirect to `/s/login` page. 
I have also checked this in code level and got below
`/app/bundles/UserBundle/Config/config.php`
```
  'lightsaml_sp.login_check' => [
                'path' => '/saml/login_check',
            ],
```
But I am not getting, what to do next. I have checked a lot of bug report for the issue but there is no solution for it.
So, Please let us know if any one have any solution for this.

| Q   | A
| --- | ---
| Mautic version | v3.1.2
| PHP version | 7.2.24
| Browser | Mozila Firefox

### Steps to reproduce
1. Get Mautic metadata
2. Create Account in AWS and setup Single Sign On in AWS.
3. Create a application in AWS and use 
_Application ACS URL_  : `https://mydomain/s/saml/login_check`
_Application SAML audience_  : `https://mydomain`
4. Get the metadat from AWS and setup in Mautic
5 Then go to `https://mydomain` url and it will redirect to ASW user login
 
### Log errors
No Error log but when try to login, it is saying `Invalid login. Please verify credentials.`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for reporting the bug @Bibhudatta-Sahoo-ASMB - we had a few fixes in 3.1 for SAML which you should have with your version, I'm not versed well enough in SAML to review so I'll ask one of @mautic/core-team to take a look.
