### ISSUE TITLE
Plugin for ZoneMTA email transport

### ISSUE THREAD

**Issue by user592965** [mautic/mautic#9454]
zone-mta is a modern open source outbound MTA wich can send bulk emails on a selfhosted server (https://github.com/zone-eu/zone-mta) and it also have APIs like Amazon SES for sending emails.

Having a plugin in mautic to be able to directly use ZoneMTA's APIs to send emails would be an excellent open source alternative to Amazon SES, it would be great to consider such a plugin.
Mailtrain already uses ZoneMTA as a plugin to send its mailings and it works well.

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
