### ISSUE TITLE
Mautic update breaks contacts

### ISSUE THREAD

**Issue by DerMeulendreeZ** [mautic/mautic#9459]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Run de update from the browser
2. Click in the contacts button in the menus
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hello @DerMeulendreeZ from which version to which version ? What is your OS ? You PhP version ?
Please give the informations given in the issue template and we'll reopen the issue.

**Comment by DerMeulendreeZ** [comment]
Hi @npracht, 

Sorry about that:

OS: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-53-generic x86_64)
PHP (downgrade from 7.4 for Mautic): 
PHP 7.3.24-3+ubuntu20.04.1+deb.sury.org+1 (cli) (built: Oct 31 2020 17:00:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.24, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.24-3+ubuntu20.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

Old Version: 

{
  "version": "3.1.2",
  "stability": "stable",
  "minimum_php_version": "7.2.21",
  "maximum_php_version": "7.3.99",
  "minimum_mautic_version": "3.0.0-alpha",
  "announcement_url": ""
}

Upgraded to 3.2.

No log files as restored a backup straight away to keep using Mautic.
