### ISSUE TITLE
Recreate database schema fails

### ISSUE THREAD

**Issue by madorin** [mautic/mautic#9466]
## Bug Description
Due to a failed upgrade, while running migrations (fk client_id, reported in issues) I exported the data from current DB, then tried to recreate an empty database from scratch, then reimport the data from backup.

| Q   | A
| --- | ---
| Mautic version | 3.2.0
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1. Launch console and run one by one the commands

- doctrine:database:drop
- doctrine:database:create
- doctrine:schema:create

**Comment by RCheesley** [comment]
Hi there, I do not believe this is a bug with Mautic. Please check the steps in the documentation here: https://docs.mautic.org/en/troubleshooting/update-failed regarding steps to take in the event of a failed update.

If you encounter problems, please post these on the forums at forum.mautic.org/c/support where you get help with addressing the issues you're facing.

**Comment by madorin** [comment]
Why it is not an issue if the DB schema recreation fails? 
It should work by default no? How then to recreate a new/empty DB?
