### ISSUE TITLE
v3.2.1 upgrade fails from command line

### ISSUE THREAD

**Issue by evgu** [mautic/mautic#9469]
When upgrading from 3.2.0 to 3.2.1 via command line, the upgrade process fails. 

| Q   | A
| --- | ---
| Mautic version | 3.2.0
| PHP version | 7.3.25
| Browser | n/a (command line)

### Steps to reproduce
1. go to mautic installation dirctory
2. run:  `sudo -u www php bin/console mautic:update:apply -vvv`
 
Output observed is: 
```
Are you sure you wish to update Mautic to the latest version? y
Step    2 [-->-------------------------] Downloading update package...                  

```
i.e. script quits after Step 2 Download.  

### Log errors
In mautic log file the following is observed: 
`mautic.WARNING: Command `mautic:update:apply` exited with status code 1 [] []`

**Comment by RCheesley** [comment]
@evgu this usually means there was a problem connecting to Github to get the packages, rather than a bug with Mautic.

**Comment by evgu** [comment]
@RCheesley, you are right, thank you! 
I tried to manually downloaded the update and specified the zip on the command line, which worked: 
```
wget https://github.com/mautic/mautic/releases/download/3.2.1/3.2.1-update.zip
sudo -u www php bin/console mautic:update:apply --update-package=3.2.1-update.zip 
```
