### ISSUE TITLE
Cleanup confirmation i18n message is wrong

### ISSUE THREAD

**Issue by iurisilvio** [mautic/mautic#9470]
## Bug Description
Yes/No confirmation in `mautic:maintenance:cleanup` does not respect i18n.

Executing cleanup give me this message (in portuguese):

> Isto irá excluir permanentemente os dados com mais de 365 dias! Por favor, faça um backup antes de prosseguir. Execute este comando com --dry-run para obter a quantidade aproximada de registros a serem excluídos. Continuar? (s/n)

I answer with `s` and it does nothing. It works as expected with `y`.

| Q   | A
| --- | ---
| Mautic version | 2.15.3

### Steps to reproduce
1. I'm using portuguese lang
1. php /var/www/html/app/console mautic:maintenance:cleanup --days-old=365
2. Confirm with `s` just end the program
 
### Log errors
No errors, the command confirmation `s` is ignored, probably because it is not `y`.

**Comment by RCheesley** [comment]
Thanks for raising this issue @iurisilvio - would you be up for looking into this in more detail?
