### ISSUE TITLE
Migration failed during Pre-Checks. Error Class 'Doctrine\DBAL\Migrations\SkipMigrationException' not found

### ISSUE THREAD

**Issue by directpromo** [mautic/mautic#9479]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When updating via the web interface I get an error at the URL step https://mydomain.com/s/update/schema?update=1
![2020-12-07_13-55](https://user-images.githubusercontent.com/42971248/101342611-e0ee6580-3893-11eb-93a4-ee0642ee4294.png)

| Q   | A
| --- | ---
| Mautic version | 3.2.0 -> 3.2.1
| PHP version | 7.2+

### Steps to reproduce
1. uploading Mautic from the git repository ( git clone https://github.com/mautic/mautic.git ) 
2. Successfully installing. Getting version 3.2.0
3. The system notifies that there is an update for 3.2.1. I Agree and launch the update via the web
4. Stop and erros https://mydomain.com/s/update/schema?update=1 
 
### Log errors

In the logs I see:
[2020-12-07 10:39:49] mautic.WARNING: Command `doctrine:migrations:migrate` exited with status code 1 [] []
[2020-12-07 10:39:49] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "SkipMigrationException" from namespace "Doctrine\DBAL\Migrations". Did you forget a "use" statement for another namespace?" at /public_html/app/migrations/Version20191017140848.php line 30 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"SkipMigrationException\" from namespace \"Doctrine\\DBAL\\Migrations\".\nDid you forget a \"use\" statement for another namespace? at /public_html/app/migrations/Version20191017140848.php:30)"} []

Then I tried using the command line:
/bin/console doctrine:migrations:migrate

I get this error:

WARNING! You are about to execute a database migration that could result in schema changes and data loss. Are you sure you wish to continue? (y/n)y
Migrating up to 20200815153711 from 20190724110039
Migration 20191017140848 failed during Pre-Checks. Error Class 'Doctrine\DBAL\Migrations\SkipMigrationException' not found

In Version20191017140848.php line 30:                                                                                     
  Attempted to load class "SkipMigrationException" from namespace "Doctrine\DBAL\Migrations".  
  Did you forget a "use" statement for another namespace? 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by dennisameling** [comment]
Just did a very quick check and can confirm this is a bug:

![image](https://user-images.githubusercontent.com/17739158/101346569-075ad380-3889-11eb-8eb2-69868a0a77ab.png)

@directpromo as a quick fix, please can you open the file `app/migrations/` and replace the following:

**LINE 13**: replace `use Doctrine\DBAL\Migrations\SkipMigrationException;` with `use Doctrine\Migrations\Exception\SkipMigration;`

**LINE 31**: replace `throw new SkipMigrationException` with `SkipMigration`.

CC @npracht this wasn't caught by our testing in https://github.com/mautic/mautic/pull/7879, bug introduced in Mautic 3.2.0. I'll provide a PR later this week which fixes this issue, and which updates PHPSTAN to also check migration files for these kind of bugs

**Comment by RCheesley** [comment]
Closing this issue now that the PR to fix it has been merged! 🎉
