### ISSUE TITLE
Point Trigger: send email overwrites campaign level email template resulting in information leak

### ISSUE THREAD

**Issue by nick-vanpraet** [mautic/mautic#9483]
## Bug Description

During campaign processing, if the sending of an email to a contact on the campaign list (triggering email) triggers an action which also sends an email (action email), then the action email's template will be used for every subsequent campaign contact. Also, the triggering email itself is never sent.

What, after a lot of debugging, seems to be happening:

In app/bundles/EmailBundle/Model/EmailModel.php, line 1452:

```        foreach ($groupedContactsByEmail as $parentId => $translatedEmails) {
            $useSettings = $emailSettings[$parentId];
            foreach ($translatedEmails as $translatedId => $contacts) {
                $emailEntity = ($translatedId === $parentId) ? $useSettings['entity'] : $useSettings['translations'][$translatedId];

                $this->sendModel->setEmail($emailEntity, $channel, $customHeaders, $assetAttachments)
                    ->setListId($listId);

                foreach ($contacts as $contact) {
                    try {
                        $this->sendModel->setContact($contact, $tokens)
                            ->send();

                        // Update $emailSetting so campaign a/b tests are handled correctly
                        ++$emailSettings[$parentId]['sentCount'];

                        if (!empty($emailSettings[$parentId]['isVariant'])) {
                            ++$emailSettings[$parentId]['variantCount'];
                        }
                    } catch (FailedToSendToContactException $exception) {
                        // move along to the next contact
                    }
                }
            }
        }
```

Here, after splitting contacts into groups per email template for the campaign, we set the corresponding email template, then start to loop over all the contacts that should receive that email.

BUT, somewhere else, not 100% sure where but somewhere in the Event system EmailModel::sendEmailToUser is called, after our action email is triggered. And that method ALSO sets the email, though in this case directly on the mailer class instead of via the mailerHelper. Line 1558.

```
        $mailer            = $this->mailHelper->getMailer();
        if (!isset($lead['companies'])) {
            $lead['companies'] = $this->companyModel->getRepository()->getCompaniesByLeadId($lead['id']);
        }
        $mailer->setLead($lead, true);
        $mailer->setTokens($tokens);
        $mailer->setEmail($email, false, $emailSettings[$emailId]['slots'], $assetAttachments, (!$saveStat));
        $mailer->setCc($cc);
        $mailer->setBcc($bcc);
```

Seems mailer and mailerHelper are singletons or something like it because from that moment on that email template continues to be used in the original loop. This can be fixed by placing the `$this->sendModel->setEmail($emailEntity, $channel, $customHeaders, $assetAttachments)->setListId($listId);` call inside the loop over `$contacts` BUT, we still lose the original triggering email. Something somewhere seems to flush it away, and that one is never sent.

Sort of fixed:

```        foreach ($groupedContactsByEmail as $parentId => $translatedEmails) {
            $useSettings = $emailSettings[$parentId];
            foreach ($translatedEmails as $translatedId => $contacts) {
                $emailEntity = ($translatedId === $parentId) ? $useSettings['entity'] : $useSettings['translations'][$translatedId];

                foreach ($contacts as $contact) {
                    try {
                        $this->sendModel->setEmail($emailEntity, $channel, $customHeaders, $assetAttachments)
                             ->setListId($listId);
                        $this->sendModel->setContact($contact, $tokens)
                            ->send();

                        // Update $emailSetting so campaign a/b tests are handled correctly
                        ++$emailSettings[$parentId]['sentCount'];

                        if (!empty($emailSettings[$parentId]['isVariant'])) {
                            ++$emailSettings[$parentId]['variantCount'];
                        }
                    } catch (FailedToSendToContactException $exception) {
                        // move along to the next contact
                    }
                }
            }
        }
```

Real life example:

We have a campaign, 1000 contacts. 
We have a Point Action: -1 points if a contact is sent an email.
We have a Point Trigger: send "Hot lead" email to sales team if a contact has more than 50 points (basically just says, hey, this lead has a lot of points)
We trigger the campaign on terminal with console: mautic:campaigns:trigger (after updating)

What we expected to happen:

1000 happy contacts, who each received some variation of our campaign email and a fair few "Hot lead" emails in our sales team's inbox for contacts that have more than 50 points.

What happened:

600 happy contacts, then one contact triggered the "hot lead" (they receive no email at all), and the other 399 contacts after that contact each received a "hot lead" email instead of the proper campaign email. The sales team inbox was correct with hot leads only if the contact had more than 50 points.

| Q   | A
| --- | ---
| Mautic version | 3.2.1
| PHP version | 7.3
| Browser | Terminal, no browser

### Steps to reproduce
1. Create a Point Action that listens to "Contact is sent an email" and adds or removes some points.
2. Create a Point Trigger that sends an email to some address or addresses when a contact's point total is larger than X.
3. Create a campaign wherein at least one contact will meet the Point Trigger threshold after the Point Action is applied to them by the sending of the campaign email.
4. Run bin/console mautic:campaigns:update and mautic:campaigns:trigger to start your campaign
5. Behold as that triggering email disappears into the aether and every subsequent email uses the Point Trigger email.
 
Here is a database dump with the above set up: [bugbackup.zip](https://github.com/mautic/mautic/files/5667384/bugbackup.zip)
  
All that's left to do is a) make sure mailhog or something catches the emails and b) run the console commands.

Should result in something close to this (not 100% because of your shuffle):

![example](https://user-images.githubusercontent.com/7923739/101662711-248ad000-3a4a-11eb-92bd-a043342bb285.png)

**Comment by RCheesley** [comment]
@nick-vanpraet thanks so much for the detailed write-up of this bug, I know it has taken quite some time to get to the bottom of how this happened! Hopefully we can figure out a fix for this nasty bug!

**Comment by jordan8037310** [comment]
I read through the context and to be honest it seems like points architecture needs a major overhaul to reduce risk. Sure this can be solved short-term but this kind of coupling shouldn't be allowed...

Points (Actions / Triggers) should be a separate queue, perhaps not even an event-based system to take action but instead a queuing system. There would be more checks and balances with a separate queue_points and actions can be processed independently (cron). This means that interfaces likely gain the benefit of their own independent tests and there are no unintended consequences.

Events-based processing means that these two systems are coupled and a failure in points can be determinant on the original action.

Perhaps an overreaction based on my read through :)
