### ISSUE TITLE
Mautic can not get list contact by api

### ISSUE THREAD

**Issue by phanhongminh206** [mautic/mautic#9484]
I’m doings connection https://mautic.org to the document here: https://developer.mautic.org.

I have obtained **ACCESS_TOKEN** but when I use that **ACCESS_TOKEN** to get data such as: contacts, fields ..., I get the following results:
```
{
    "errors": [
        {
            "message": "Requested URL not found: /api/contacts",
            "code": 404,
            "type": null
        }
    ]
}
```

- For example when I retrieve the contacts list, I try 2 options:
1. send a request to https://mautic.xxx.com/api/contacts?access_token=ACCESS_TOKEN
2. Send https://mautic.xxx.com/api/contacts in the header I have to **Authorization**: **Bearer ACCESS_TOKEN** then also received the same results.

I Don't know whether I am wrong or right. Do I need further configuration?

I hope you can help me with this matter

**Comment by RCheesley** [comment]
Hi there, please post requests for support over at https://forum.mautic.org/c/development or https://forum.mautic.org/c/support for generic help rather than here on Github, as we use this issue queue solely for bugs with Mautic itself.
