### ISSUE TITLE
Segment: Regexp search for preferred locale field doesn't work

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#9487]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Can't do a regexp search for locale in segment definition. The field remains a selection field - regexp can't be entered anywhere.

![image](https://user-images.githubusercontent.com/1241376/101804960-7b5bdc80-3b12-11eb-92af-dd74fed59a13.png)

| Q   | A
| --- | ---
| Mautic version | 3.2.1
| PHP version | 7.3
| Browser | any

### Steps to reproduce
1. try to define a segment based on a regexp for the "preferred locale" field
2. the input field is still a selector field - no way to enter an expression
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for flagging these issues, I suspect they might be due to the same root cause but we'll see when someone has the chance to dig into it!

**Comment by namratasaun** [comment]
hey, any solutions for this yet? @dsp76

**Comment by dsp76** [comment]
Regex also doesn't work for other non-text fields. It should be decided, whether regex works for all fields or will only be given as an option to selected fields.
