### ISSUE TITLE
how to setup Mautic Recommender Bundle in mautic 3

### ISSUE THREAD

**Issue by altarankumar** [mautic/mautic#9490]
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Mautic\CoreBundle\EventListener\CommonSubscriber' not found

### Log errors: 

_Please check for related errors in the latest log file in [mautic root]/var/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable._

**Comment by RCheesley** [comment]
@altarankumar this is a third party plugin. You will need to speak with the developers for guidance.
