### ISSUE TITLE
Reproducing <!doctype html> on every save of the email

### ISSUE THREAD

**Issue by trianity** [mautic/mautic#9491]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.2.1
| PHP version | 7.3.23
| Browser | Google Chrome

### Steps to reproduce
1. Open code mode email
2. Save the email
3. Every save will add exactly 1 more <!doctype html> tag to the begginig of the email
4. You will see the reproducing <!doctype html> tags in the beginning of the email.
 
### Log errors

No logs, here is the screenshot.

![ScreenShot_20201105224203](https://user-images.githubusercontent.com/6353141/101940881-7b79dc00-3be7-11eb-8ef1-34c5aab2efce.png)

The issue is appeared with Mauitc 3.1.x and still exists with Mauitc 3.2.1

Pull https://github.com/mautic/mautic/pull/669 handled the opposite of this issue.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for reporting the bug @trianity !

**Comment by kuzmany** [comment]
This PR cause it: https://github.com/mautic/mautic/pull/9108
It happend If you use in email any unicode character 
Continue investigation what are we able to do with it

**Comment by trianity** [comment]
@kuzmany Thanks for the idea.

The PR #9108 is irrelevant from the view point of this issue, but the line 452 in the /app/bundles/CoreBundle/Helper/InputHelper.php file is responsible for it.

Line 452:
```
// Was a doctype found?
if ($doctypeFound) {
    $value = "$doctype[0]$value";
}
```
The condition is wrong, if the $doctypeFound is TRUE, e.g the info element is found in the line 400, so the element `<!DOCTYPE html>` is exist, it will reproduce it.

The proper code is with NOT prefix:
```
// Was a doctype found?
if (!$doctypeFound) {
    $value = "$doctype[0]$value";
}
```
But it will not handle the missing  `<!DOCTYPE html>` tag, because the PHP preg_match will return nothing in the case (line 400).

So, the proper code is like it:

```
// Was a doctype found?
if (!$doctypeFound) {
    $value = "<!DOCTYPE html>$value";
} else {
    //do something if the duplicated <!DOCTYPE html> information element should handled - if it is necessary
}
```

This solution works, I tested in my Mautic instance. The reproducing of the element is stopped, and the missing  `<!DOCTYPE html>` information is added.

@RCheesley Can you do a PR from this solution?

**Comment by npracht** [comment]
Hi @kuzmany and @trianity can you test https://github.com/mautic/mautic/pull/9514 and confirm ?
Then we can merge for next release.

**Comment by kuzmany** [comment]
@trianity  No, that condition is right. Your change failed on basic html content

```
<!DOCTYPE html>
        <html>
        </html>
```

Doctype is added to code because is removed on cleanup html https://github.com/mautic/mautic/blob/features/app/bundles/CoreBundle/Helper/InputHelper.php#L446

`$value = self::getFilter(true)->clean($value, 'html');`

We need figure out why this method from 

```
'<!DOCTYPE html>\r\n
        <html>\r\n
        <body>\r\n
            <a href="https://m3.mautibox.com/3.x/media/images/testá.png">test with unicode</a>\r\n
        </body>\r\n
        </html>'
```

return

```
'<!DOCTYPE html>\r\n
        <html>\r\n
        <body>\r\n
            a href="https//m3.mautibox.com/3.x/media/images/testá.png&quot;"test with unicode</a>\r\n
        </body>\r\n
        </html>'
```

I've tried last version of cleaner https://github.com/joomla-framework/filter/blob/master/src/InputFilter.php  but without success.

**Comment by infomanPMF** [comment]
Hi, I'd like to confirm that I've also experienced the error.

**Comment by kuzmany** [comment]
I think I have solution on this

**Comment by kuzmany** [comment]
This should fixed it https://github.com/mautic/mautic/pull/9516 

Please test

**Comment by MarketSmart** [comment]
@kuzmany I tested this on my end. Seems to have fixed it for me. Can one other person test this as well.

**Comment by trianity** [comment]
@kuzmany I also tested the solution and in my side it works well, the issue was fixed.

**Comment by kuzmany** [comment]
@MarketSmart @trianity can you go to PR and approve it. Then we can merge it to 4.1 I hope (@RCheesley )

![image](https://user-images.githubusercontent.com/462477/144018149-c20a898c-3596-46cb-b7a4-2d3ddb698158.png)

**Comment by RCheesley** [comment]
4.1 was released last night, so the soonest this will be released is 4.1.1 toward the end of December.

**Comment by trianity** [comment]
> @MarketSmart @trianity can you go to PR and approve it. Then we can merge it to 4.1 I hope (@RCheesley )
> 
> ![image](https://user-images.githubusercontent.com/462477/144018149-c20a898c-3596-46cb-b7a4-2d3ddb698158.png)

@kuzmany I am sorry, but I am not authorized to approve and merge PR-s.

**Comment by trianity** [comment]
@kuzmany The PR was already approved by @npracht but this automatic check was failed:
https://github.com/mautic/mautic/pull/9516/checks?check_run_id=3643945735

**Comment by trianity** [comment]
The issue still exist on the latest Mauitc 4.2 also.
@npracht @kuzmany the PR failed and the correction script is not merged to the branch.

**Comment by trianity** [comment]
@RCheesley Can you look at it?

**Comment by RCheesley** [comment]
PR needs to be rebased to 4.2 before it could be merged.

**Comment by trianity** [comment]
@kuzmany @RCheesley The issue steel exists on Mautic v.4.4.1 and not only email builder can repeat the `<!DOCTYPE html>` but the pagebuilder of landing pages in code mode.

![Képernyőkép ekkor: 2022-08-06 09-14-56](https://user-images.githubusercontent.com/6353141/183254947-aef715a9-ecb0-43d6-9432-d4222556cafc.png)

![Képernyőkép ekkor: 2022-08-06 08-43-49](https://user-images.githubusercontent.com/6353141/183254958-2e7cd60f-435c-4560-8b55-821434f5c7f6.png)

How to @kuzmany  https://github.com/mautic/mautic/pull/9516 fix apply for the next release?
