### ISSUE TITLE
SameSite=none not set behind proxy

### ISSUE THREAD

**Issue by christopheg** [mautic/mautic#9495]
Problem:
Tracking cookie is not set with 'SameSite=none'

Environment:
- Debian Linux 10
- PHP 7.3
- Mariadb server 10.3
- Mautc v3.2.1
- Served from behind nginx reverse proxy with SSL termination

cause:
- The connection is not seen as 'secure'
- header X-Forwarded-Proto = 'https' is set via nginx

**Comment by christopheg** [comment]
The correct way to determine the HTTP/HTTPS connection with Symfoy seems to be the 'isSecure()' method

**Comment by npracht** [comment]
closing in favor of https://github.com/mautic/mautic/issues/8944
