### ISSUE TITLE
Email template issue within Mautic

### ISSUE THREAD

**Issue by LogProd** [mautic/mautic#9497]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have designed a very basic text email (for testing purposes) only to find that within the builder it looks as one would expect. However, when a contact and "send email" I have found the same layout cocmpletely changes. All text is centered and there are large margins in the top and bottom. Mautic seems to have a bug at remembering email layouts and overrides them. This is a new install without any customization of Mautic. 

| Q   | A
| --- | ---
| Mautic version |  3.2.1
| PHP version | 7.3
| Browser |  Chrome

### Steps to reproduce
1.  Design email
2.  goto contacts and select "send email"
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Can you please provide us with some screenshots of the email that you created, the theme that you used and include the source for the email?

Also which devices are you testing on to view the layout? 

We have a reported bug in mobile devices relating to styling: #9401 which may be related?

**Comment by npracht** [comment]
I'll close this for lack of feedback and knowing that the builder itself is not responsive. You should start from template or use the newly introduced grapes.js plugin for new email builder.
