### ISSUE TITLE
[feature request] Add the option for new delayed actions in a campaign to be immediately sent to all leads that are past that time point.

### ISSUE THREAD

**Issue by zeinmaciel** [mautic/mautic#950]
It's a bit frustrating that new delayed actions in a campaign will only apply to the leads at that time point right now.

Let's say I have a campaign for a smart list with 7 email follow-ups, each of them going off once a day after the opt-in.

If I have this campaign going on for over a month and want to add an email to the 8th day, this email will only be sent to the leads that are right now on the 8th day, and to the ones that get to the 8th day in the future... everybody past the 8th, the people who opted-in in the first 3 weeks, will not get it.

This basically means you need to have your whole campaign ready before deploying it, without the possibility of adding emails to it in the future and have them be sent to leads past that time point.

This feature could come in a form of a checkbox when adding a new delayed email to the end of the campaign's timeline, "apply this action to all leads past this time point/in queue".

The only way to go around this that I can think of right now would be to add an "add tag" action to the end of such campaign... And then, whenever the need to add new emails to this campaign would appear, to create a new smart list with this new tag as a required field, and then create a new campaign to this new smart list. I assume that this way, with all the leads being built into this new smart list at the same time, the new campaign would trigger to all of them at once.

This assuming the campaigns timeline is set to trigger having "entering smart list" ad day 0, and not the leads opt-in time in the system as day 0.

It's not optimal, though. A checkbox to "apply this action to all leads past this time point/in queue" would be much better.

If anyone has a better solution for this please reply about it here.

**Comment by gpassarelli** [comment]
+1
