### ISSUE TITLE
Column not found: 1054 Unknown column 't.generated_sent_date' in 'field list'"

### ISSUE THREAD

**Issue by Gp2mv3** [mautic/mautic#9500]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Error 500 when using dashboard widget of type "Emails in time". 

Mautic is completly unusable as it's on the homepage (after login). We have to delete the record from the `widget` table to "repair" Mautic.

| Q   | A
| --- | ---
| Mautic version | 3.1.2
| PHP version |  7.3.24
| Browser | Not relevant (Firefox & Chrome)

### Steps to reproduce
1. Create a widget of type "Email in time" in the dashboard
2. You'll already see a 500 error in the modal.
3. Save
4. Refresh the page
5. You should be seeing a 500 error and the following log in the PHP logs:
 
### Log errors
I have the following PHP error:
> [2020-12-15 15:55:50] mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT t.generated_sent_date AS date, COUNT(*) AS count FROM email_stats t WHERE (t.date_sent BETWEEN ? AND ?) AND (EXISTS (SELECT null FROM lead_lists_leads lll WHERE (lll.leadlist_id = ?) AND (lll.lead_id = t.lead_id) AND (lll.manually_removed = 0))) GROUP BY t.generated_sent_date ORDER BY t.generated_sent_date ASC LIMIT 29' with params ["2020-11-17 00:00:00", "2020-12-15 15:55:50", 9]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't.generated_sent_date' in 'field list'" at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t.generated_sent_date AS date, COUNT(*) AS count FROM email_stats t WHERE (t.date_sent BETWEEN ? AND ?) AND (EXISTS (SELECT null FROM lead_lists_leads lll WHERE (lll.leadlist_id = ?) AND (lll.lead_id = t.lead_id) AND (lll.manually_removed = 0))) GROUP BY t.generated_sent_date ORDER BY t.generated_sent_date ASC LIMIT 29' with params [\"2020-11-17 00:00:00\", \"2020-12-15 15:55:50\", 9]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't.generated_sent_date' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't.generated_sent_date' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't.generated_sent_date' in 'field list' at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []

### More details
We use a docker-compose configuration with an image running PHP 7 & Apache for Mautic. And a second image with PerconaDB.

**Comment by Gp2mv3** [comment]
Here is the structure of the emails_stats table (which doesn't have any `generated_sent_date` column:
![Screenshot from 2020-12-15 16-12-45](https://user-images.githubusercontent.com/1221806/102233410-863ab680-3ef0-11eb-8806-265a75fb01ab.png)

**Comment by RCheesley** [comment]
Hi @Gp2mv3 thanks for taking the time to report this.  

Can you check if you have any outstanding migrations? You can do this without applying them using the steps documented here: https://docs.mautic.org/en/troubleshooting/update-failed#3-check-for-outstanding-database-migrations

This column was added with [this PR](https://github.com/mautic/mautic/pull/7094) which was merged in the 3.1.0 release, and I note the information here:

> Generated fields doesn't have a migration file because we don't know whether the database supports generated fields. So we check the database version and run the alter table queries only if the database supports it. 

Maybe this was not executed and hence you are seeing those errors?

According to the [documentation](https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html):

> Generated columns are supported by the NDB storage engine beginning with MySQL NDB Cluster 7.5.3.

**Comment by Gp2mv3** [comment]
Oops, that was indeed the case... 2 migrations awaiting.

Thanks a lot for your message!

**Comment by RCheesley** [comment]
No problem! As always, take a backup before applying! :)
