### ISSUE TITLE
extrange caracters in email

### ISSUE THREAD

**Issue by miguelpascual** [mautic/mautic#9503]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
In Send email to user
Send email to system user, contact owner or other email addresses
If there the email in CC have some estrange caracter like ñ á ó etc the queue blocks and mautic says to send the mails but they do not get out of the server

Cleaning the queue and removing the caracter all recovered

| Q   | A
| --- | ---
| Mautic version | v3.1.2
| PHP version | 7.2.34
| Browser | not relevant

### Steps to reproduce
1. In one campaing create and action Send email to user
2. In field To or CC insert this fake email begoña@pérez.es
3. Process the campaign 
4. mautic reports maild send but te queue dont send the email and next mails also estay blocked 
 
### Log errors

EncoderException: Non-ASCII characters not supported in local-part (uncaught exception) at /var/www/vhosts/wxxxs/gxxxxxxxs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/AddressEncoder/IdnAddressEncoder.php line 40 while running console command `mautic:emails:send` [] []

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Please update to 3.2.5 and report back if you are still experiencing this issue.
