### ISSUE TITLE
Problem with Multiple Campaign handling: Creating second campaign causes MAUTIC to "ignore" previous one

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#9508]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
It seems like there is a problem handling multiple campaigns. I noticed that creating a second campaign causes MAUTIC to ignore the previous campaign while not delivering emails triggered to go out.

| Q   | A
| --- | ---
| Mautic version | 3.2.1
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1. Create 2 separate campaigns and schedule emails according to contact segments to go out. Use different schedule times.
2.  Notice that emails for the second campaign created will be triggered to go out while deliveries in the first campaign will be ignored.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by saitanay** [comment]
@omert37 

I tried testing this with 2 campaigns set to different schedules, and observed that the emails from the 2 campaigns were delivered as expected. 

1) Would it be possible to add more details about the campaigns you have, like the source of the campaigns, the schedules of the campaigns, and any other steps or configuration you feel is relevant to replicating this issue. 
2) Also, can you share any logs you observed in /var/logs in mautic, as well as any apache/php logs corresponding to this timeline.
