### ISSUE TITLE
Attempted to call an undefined method named "validateValue" of class "Symfony\Component\Validator\Validator\RecursiveValidator"

### ISSUE THREAD

**Issue by pwned555** [mautic/mautic#9512]
Mautic version - v3.2.1
PHP version - 7.3.24 

## Description:
Error when trying to create a new custom field of type Time (and I believe Date).

### Steps to reproduce:
1. Create a new custom field for company that is a time field (I believe date will do this as well)
2. Populate the values and try to save the new custom field, below error will be given
 
### Log errors: 

mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "validateValue" of class "Symfony\Component\Validator\Validator\RecursiveValidator"." at mautic\app\bundles\LeadBundle\Form\Type\FieldType.php line 354 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"validateValue\" of class \"Symfony\\Component\\Validator\\Validator\\RecursiveValidator\". at mautic\\app\\bundles\\LeadBundle\\Form\\Type\\FieldType.php:354)"} []

### Fix:
I am unable to fix this right now, but it seems to be an easy fix locally.  I believe validateValue has been changed to validate.  This need to be updated in two places in LeadBundle\Form\Type\FieldType.php  Lines 337 and 354.

Old code:
$violations = $validator->validateValue(...

New code:
$violations = $validator->validate(...

**Comment by npracht** [comment]
Hi @pwned555 ! Can you please test https://github.com/mautic/mautic/pull/9534 ?

**Comment by pwned555** [comment]
I have tested the change and it fixes the bug.
