### ISSUE TITLE
Campaign break after do you connetc this node like the sample

### ISSUE THREAD

**Issue by leoborlot** [mautic/mautic#9513]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hi folks. Did I help a customer to solve a trouble, he does the campaign like the image attached. 
He deos 2 conections to same "email send" action. No erro still this point. When he save and try open the campaign config editor Mautic return "no permission" message. 
If I click on the chek box at campagins list page and select "edit" option, mautic permisshi me access the editors page, but, if I click on the campagin name its return the no permission message (erro print image was atteched)

![chrome_dQrqBFonyX](https://user-images.githubusercontent.com/20361821/102694218-66600700-41fe-11eb-8a6b-db1ac1e00305.png)

![chrome_7qaSWOa7PE](https://user-images.githubusercontent.com/20361821/102694209-62cc8000-41fe-11eb-959a-3c86b42efcdf.png)

| Q   | A
| --- | ---
| Mautic version | 3.2.1 
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1. Create a new campagin and add the actions like the image attached.  
2. Add the connections as pointed for red arrow
3. Save and close the editor
4. on the campaigns list page, click on the campaings name.
5. To edit, come back to campaings list page and select the edit option on the checkbox selec.
6. If you remove one of this 2 conections the problem was solve. 
7. 
![chrome_dK3akxmP9K](https://user-images.githubusercontent.com/20361821/102694216-65c77080-41fe-11eb-907b-a0274bea689d.png)

 
### Log errors
No log erros. 
No webserver erros.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by vgpastor** [comment]
I have the same issue in 3.2.1, the error happend wheen two actions based in time or date are assigned to one send email block. In my case to solve this separate the email to send in two blocks and return to the other chain if it's neccesary.

**Comment by RCheesley** [comment]
Can you check if this happens with 3.2.5 and report back (you are both running versions that are [vulnerable to attack](https://www.mautic.org/blog/community/security-release-all-versions-mautic-prior-2-16-5-and-3-2-4) and should be updated as a matter of priority!)

**Comment by kuzmany** [comment]
I think this should fixed it in 3.2.2 by this PR https://github.com/mautic/mautic/pull/9380

**Comment by npracht** [comment]
Then i'll close and re-open if @leonardoborlot says it's not fixed.
