### ISSUE TITLE
Mautic is not set to queue email

### ISSUE THREAD

**Issue by LogProd** [mautic/mautic#9518]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

Installed 3.2.1 and its cron jobs however segments are not being sent and only stay cued. I have checked the log and found "Mautic is not set to queue email."  

I used the code php /path/to/mautic/bin/console mautic:broadcasts:send [--id=ID] [--channel=CHANNEL] and replaced it with the proper parameters for my path as I have done with others that work. 

I'm on a self hosted environment and have found no current documents which explain what setup step is missing. 

Any/all help and direction is great appreciated. 

| Q   | A
| --- | ---
| Mautic version | 3.2.1
| PHP version | 7.3
| Browser |  chrome

### Steps to reproduce
1.  add email to segment
2. segments added to cue and segment cron job is not triggering them
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by elilogan** [comment]
It’s customary to post error logs found in mautic/var/log so we can help you determine the exact nature of the error. 
In the meantime can you verify in Settings / Configuration / Email Settings that “How should email be handled” is set to Queue

Open path/to/mautic/app/config/local.php with your favorite text editor and set Debug to “True” and save it (Line 471 on my test install buy yours may vary depending on your settings and variables)

Then run `/path/to/mautic/bin/console mautic:email:send` with whatever parameters  appropriate and post your results.

**Comment by npracht** [comment]
Also you use the command that send automatically segment email. But did you add a publish date to segment email to trigger it automatically ?
