### ISSUE TITLE
Campaign update contact action is updating all blank date/time fields with today's date

### ISSUE THREAD

**Issue by alanhartless** [mautic/mautic#9528]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
https://github.com/mautic/mautic/pull/6126 introduced a feature to support relative dates for update contact update action. Unfortunately, it also introduced a bug that set all date fields to today if left empty. 

<img width="672" alt="Screen Shot 2020-12-21 at 20 52 27" src="https://user-images.githubusercontent.com/63312/102843444-d58c5580-43ce-11eb-921c-5c909f826ac0.png">
<img width="1168" alt="Screen Shot 2020-12-21 at 20 54 38" src="https://user-images.githubusercontent.com/63312/102843450-d7561900-43ce-11eb-8613-510e7e4be154.png">

| Q   | A
| --- | ---
| Mautic version | 3.2.1
| PHP version | 7.3
| Browser | Chrome

#### Steps to reproduce the bug:
1. Create two custom fields that are date or datetime.
2. Create a campaign with an "update contact" action and set one of the fields to "yesterday" and leave the other empty
3. Let the campaign run and look at the contact's profile audit log tab
4. Notice that the field with "yesterday" should have yesterday's date but the field that should have remained blank now has today's date. 

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Fixed in 3.2.2
