### ISSUE TITLE
Reporting problem: Bounce callback via endpoint (SendGrid webhook) Recorded & Processed BUT not showing up on reports

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#9532]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have been using the SendGrid callback endpoint on MAUTIC to manage bounces and while they are being recorded and processed, it looks as though they are absent from the reports.

| Q   | A
| --- | ---
| Mautic version | 3.2.1
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1. Configure SendGrid Webhook with the MAUTIC Sendgrid callback with Bounces.
2. Send a deliberate Bounce
3. Notice Bounce is recorded and processed for contact via callback but...
4. Notice it doesn't show up on Reports.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @omert37 !
Could you please test https://github.com/mautic/mautic/pull/9106 and tell if it helps to solve your issue ?
Thanks !
