### ISSUE TITLE
Version 3.2.1-1 performance

### ISSUE THREAD

**Issue by diegolr62** [mautic/mautic#9535]
Our installation has 200k contacts and sends about 800k messages per week. With the old 2.16.3 version we managed to tune the database and the performance was reasonble. Our VM has 4 cores and 16 Gb assigned.

After upgrading to version 3.2.1  MySQL, is taking about 9Gb of that RAM but the performance is really poor, login in takes more than 5 minutes and when we are sending emails the system get stuck.

After doing research on the DB side we found queries that are not optimized. I know that Mautic code uses an ORM to manage persistence and maybe is the piece causing the problems.

The not optimized queries are using 'columnDate BETWEEN date1 AND date2'. I've found that Mysql is not good optimizing that syntax, so is better to change it to 'date1 >= columnDate and date2<= columnDate' this change makes a big difference.

Is it possible to change the queries generated by the ORM to avoid the use of BETWEEN ?

Regards

**Comment by npracht** [comment]
Hi @diegolr62 !
Thanks a lot for your message. Would you kindly propose a Pull Request for the change your suggest ? That might be the best way to test it and ask other contributors to review it and probably merge it in core.
