### ISSUE TITLE
Install issues when using Galera Cluster

### ISSUE THREAD

**Issue by smcpeck** [mautic/mautic#9540]
Because of how a [Galera cluster works](https://galeracluster.com/library/kb/auto-increment-multiples.html) (each node has its own "next value" for an `auto_increment` column), there can be inconsistency when installing Mautic and creating the admin user.

The install code assumes that the `Administrator` role will always have an `id` of 1.

https://github.com/mautic/mautic/blob/37ed5ee87900522c888b09ed3857ad0452fb33df/app/bundles/InstallBundle/Install/InstallService.php#L522

However, as noted above, this is not a safe assumption. On a 3 node cluster, we can expect a random 33.3% chance of a Mautic install being successful.

As a workaround, I was able to go and force this `id` column to 1 in the database after the database step and before submitting the admin user information.

**Comment by RCheesley** [comment]
@smcpeck would you be up for seeing if you can come up with a better way of doing this and making a PR?

**Comment by mabumusa1** [comment]
@mlahlouh How do you think we can solve this issue?

**Comment by mlahlouh** [comment]
@mabumusa1 
Mautic install script should insert a record with value 1 for ID for administrator, should not relay on MySQL auto-increment.

and this will work fine in Galera Cluster, Single server, and Master-Master setup. (MySQL, MariaDB, and Percona)
