### ISSUE TITLE
mautic email going in spam and also not display image please Help ASAP

### ISSUE THREAD

**Issue by raghav111jain** [mautic/mautic#9546]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.0
| PHP version | 7.4
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Email show in spam and also image not display is SSL issue because my site SSL expire please let  me know ASAP**

**Comment by raghav111jain** [comment]
**please let me know if my site SSL Expire if you sent email with image but not display in mail & also going in spam so that's SSL Issue ??? Please Help ASAP**

**Comment by Aerendir** [comment]
Do you really think that with a message like this we can help you? 😳

Anyway this is not the right place where to ask for support.

Go here: https://forum.mautic.org/

**Comment by raghav111jain** [comment]
@Aerendir thanks you
