### ISSUE TITLE
Mapping of entities is invalid

### ISSUE THREAD

**Issue by Aerendir** [mautic/mautic#9548]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Running `bin/console doctrine:schema:validate` returns the following errors:

```console
public_html# php bin/console doctrine:schema:validate

Mapping
-------

 [FAIL] The entity-class Mautic\DynamicContentBundle\Entity\DynamicContentLeadData mapping is invalid:
 * The association Mautic\DynamicContentBundle\Entity\DynamicContentLeadData#dynamicContent refers to the inverse side field Mautic\DynamicContentBundle\Entity\DynamicContent#id which is not defined as association.
 * The association Mautic\DynamicContentBundle\Entity\DynamicContentLeadData#dynamicContent refers to the inverse side field Mautic\DynamicContentBundle\Entity\DynamicContent#id which does not exist.


 [FAIL] The entity-class Bazinga\OAuthServerBundle\Model\RequestToken mapping is invalid:
 * The field 'Bazinga\OAuthServerBundle\Model\RequestToken#expiresAt' uses a non-existent type 'int'.


 [FAIL] The entity-class Bazinga\OAuthServerBundle\Model\AccessToken mapping is invalid:
 * The field 'Bazinga\OAuthServerBundle\Model\AccessToken#expiresAt' uses a non-existent type 'int'.
```

| Q   | A
| --- | ---
| Mautic version | 3.2.0 (but is present since 2.16.0, maybe also before)

### Steps to reproduce
1. Run `bin/console doctrine:schema:validate`
 
### Other info

May be useful to add the Symfony's checks to the GitHub actions to avoid errors like those in future.

**Comment by Plato39** [comment]
Still present in 3.2.4

Do these validation errors cause any actual issues in Mautic?

**Comment by Aerendir** [comment]
@Plato39 not always... maybe yes... maybe not... It depends...

And depends on the features you use...

**Comment by RCheesley** [comment]
> May be useful to add the Symfony's checks to the GitHub actions to avoid errors like those in future.

@Aerendir would you be up for helping to implement that?

**Comment by Aerendir** [comment]
Not this week... May be the next one... Can you assign this issue to me?

**Comment by RCheesley** [comment]
Sure, have assigned it to you! Timeline wise the next release will be at the end of the month and we have the Release Candidate freeze on 15th February, so if you are able to get something together before then we can get it tested and hopefully shipped fairly swiftly! Seeing as it will relate to GH rather than Mautic itself I will also add the CI and chore labels.

**Comment by Aerendir** [comment]
@RCheesley , ok, it is all clear: I will try to work on this next week...

**Comment by Aerendir** [comment]
@RCheesley , from which branch should have I to create my PR branch?

Here are some guidance:
https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests#step-5-work-on-your-pull-request

But I don't know anyway which should be the starting branch.

**Comment by RCheesley** [comment]
@Aerendir for the upcoming release it will be the features branch. Once 3.3 is released, bug fixes will go against the 3.3 branch and features against the features branch :)

**Comment by Aerendir** [comment]
So, I have to use the `features` branch, right?

**Comment by RCheesley** [comment]
Yes please! :)

**Comment by Aerendir** [comment]
@RCheesley , I'm seeing the code: the entities use directly the `ClassMetadataBuilder` and I've never used it: I use annotations that are more clear and simpler to use.

Also digging into the code, I cannot find a reason for the error.

The `DynamicContent::$id` field, in fact, [is created in the entity `DynamicContent`](https://github.com/mautic/mautic/blob/features/app/bundles/DynamicContentBundle/Entity/DynamicContent.php#L141), so I'm not understanding why it is reported as non-existent.

More, the other errors that refer to `Bazinga\OAuthServerBundle\Model\RequestToken` and to `Bazinga\OAuthServerBundle\Model\AccessToken`, are in a dependency (`willdurand/oauth-server-bundle`) and so are outside of control of Mautic: a PR to that repository is required. And the package is 7 years old...

In the end:

1. I'm not able to fix the issue in `DynamicContentBundle`
2. The other errors refer to 3d party dependency that I don't know if is still supported
3. Add CI checks in this moment has no sense as they will always fail due to the point 1 and 2.

WDYT?

**Comment by Aerendir** [comment]
This is not solved and is not stale.

**Comment by Plato39** [comment]
This is still not solved.  I'm not sure if it's actually breaking anything.
