### ISSUE TITLE
Wrong company in Contact list

### ISSUE THREAD

**Issue by cpot** [mautic/mautic#9551]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When associating a contact to several companies and then removing companies to keep just one, in the view Contact list (and also in export), the oldest Company is displayed even if not linked anymore to the Contact.
Mautic is a great tool, but this is a very annoying bug that is here forever IMHO

| Q   | A
| --- | ---
| Mautic version | 3.2.1 and previous
| PHP version | 7.2
| Browser | FF 84

### Steps to reproduce
1. Create a contact, associate a company, then associate another and remove the old one
2. Go to view Contact, the column "Company" displays the old company not the new one
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by saitanay** [comment]
Checked on 3.2.1

Added a contact, added Company 1, added Company 2, to contact. 

Deleted Company 1. 

Contact overview page shows Company 2 only as expected. 

Verified that the entries in the below tables are updated accordingly

- companies
- companies_leads

@cpot  - can you see if you have any entries in the log when you deleted the first company?

**Comment by cpot** [comment]
@saitanay thank you for investigating, i have not myself access to the logs but will see if i can request them to the IT dept.

**Comment by RCheesley** [comment]
@cpot any updates on this? Does it persist with 3.3.1?

**Comment by cpot** [comment]
> 
> 
> @cpot any updates on this? Does it persist with 3.3.1?

We are still in 3.21, will keep you posted

**Comment by npracht** [comment]
Hi @cpot any feedback to share ?
Thanks :)

**Comment by cpot** [comment]
> 
> 
> Hi @cpot any feedback to share ?
> Thanks :)

From what i know from my team the problem is still there. However we will do the latest update and reopen if needed cc @jlemangarin @odernovaya
