### ISSUE TITLE
Autofilled form fields not respecting visibility flag on landing page

### ISSUE THREAD

**Issue by smcpeck** [mautic/mautic#9552]
## Bug Description
When autofilling form fields on a landing page, the fields are not hidden if `Show when value exists` is set to `No` for the field's `Behavior`.

![image](https://user-images.githubusercontent.com/8724583/103421099-474b6880-4b60-11eb-8f72-6a190a366e51.png)

| Q   | A
| --- | ---
| Mautic version | 3.2.2
| PHP version | 7.2.34

There is some tangentially related discussion in #9545.

### Steps to reproduce
1. Create form with text input field (e.g. First name).
2. Under `Behavior`, set `Show when value exists` to `No`.
3. Create landing page with form embedded.
4. Navigate to landing page with query string parameters to autofill the field (i.e. `?first_name=Shaun`)
5. Notice that the field is populated and still visible; expectation is that the fields should **not** be visible. 
 
### Workaround
I developed a JavaScript hack that seems to get the job done for me from a functional POV, but I expect the real fix goes in the backend PHP code.

```
var fields = ['first_name', 'last_name', 'email_address'];
$("input:not([value=''])").filter(
   function() {
      $inp = $(this)[0];
      return fields.filter(
         function(el) {
            return $inp.name.includes(el);
         }
      ).length != 0;
   }
).closest("div").hide(); 
```

**Comment by RCheesley** [comment]
@smcpeck is this still an issue with 3.2.5? Would you be open to taking a dig into the code to find what is causing it and make a PR to address the issue?

**Comment by smcpeck** [comment]
Hi, @RCheesley. I can look at updating to 3.2.5 soon. I'm on a custom docker image for 3.2.2 for my deployment.  Do you know if database schema migrations, etc. will happen properly as just part of how Mautic works if I were to bump that code to 3.2.5 in my custom image? Maybe there are no database migrations between the two version so I'll just be safe on that account.

Not sure I'll have the time in the near future to dive into the PHP code as that's where I presume the issue lies, but I'll keep this on my radar as I'd love to contribute to the project.

Cheers!

**Comment by RCheesley** [comment]
> I'm on a custom docker image for 3.2.2 for my deployment. Do you know if database schema migrations, etc. will happen properly as just part of how Mautic works if I were to bump that code to 3.2.5 in my custom image?

Something to ask in #docker on Slack!

> I'll keep this on my radar as I'd love to contribute to the project.

Great - if you need a hand getting started let us know - we also need help with testing (just need to be able to use Mautic) and a range of other non-development tasks if you have the time available!
