### ISSUE TITLE
Mautic campaign not sending out emails

### ISSUE THREAD

**Issue by linuxhead2** [mautic/mautic#9555]
Hi, 

I have mautic marketing automation system installed on Centos 7 running on PHP 7.3.

Mautic doesn't send out emails though you have contacts in the segment and also in the campaign. The status of the campaign is pending. Campaign and marketing messages are published.

Any ways to solve this?

**Comment by jos0405** [comment]
Hi, can you confirm, that all cron jobs are running properly?
Are you using queue for sending emails?
Do you see any emails in spool/default folder?

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
