### ISSUE TITLE
SplFileInfo::getSize(): stat failed  when running upgrade_v3.php

### ISSUE THREAD

**Issue by r-martins** [mautic/mautic#9556]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When upgrading from 2.16.4 to 3.x using the upgrade_v3.php I got PHP Fatal error:  Uncaught RuntimeException: SplFileInfo::getSize(): stat failed for /Users/martins/www/mautic-magenteiro/bin/dbunit in /Users/martins/www/mautic-magenteiro/upgrade_v3.php:259.

| Q   | A
| --- | ---
| Mautic version | 2.16.4
| PHP version | 7.3.19

### Steps to reproduce
1. Using Mautic 2.16.1, I upgraded to 2.16.4 (mautic:update:find / apply + adding the line to ignore v3 updates on local.xml)
2. After it was successfully updated, I removed the line (to ignore v3) in local.xml, cleaned the cache and rerun the update:find command
3. ran php upgrade_v3.php
 
### Log errors
Thank you, continuing...
===== STARTING MAUTIC 3 UPGRADE AT 2021-01-05 03:59:06... =====
Installed Mautic version:       2.16.4
PHP version:                            7.3.19
OS:                                                     Darwin
Upgrade type:                           CLI

Doing pre-upgrade checks...
PHP Fatal error:  Uncaught RuntimeException: SplFileInfo::getSize(): stat failed for /Users/martins/www/mautic-magenteiro/bin/dbunit in /Users/martins/www/mautic-magenteiro/upgrade_v3.php:259
Stack trace:
#0 /Users/martins/www/mautic-magenteiro/upgrade_v3.php(259): SplFileInfo->getSize()
#1 /Users/martins/www/mautic-magenteiro/upgrade_v3.php(736): runPreUpgradeChecks()
#2 {main}
  thrown in /Users/martins/www/mautic-magenteiro/upgrade_v3.php on line 259

Fatal error: Uncaught RuntimeException: SplFileInfo::getSize(): stat failed for /Users/martins/www/mautic-magenteiro/bin/dbunit in /Users/martins/www/mautic-magenteiro/upgrade_v3.php on line 259

RuntimeException: SplFileInfo::getSize(): stat failed for /Users/martins/www/mautic-magenteiro/bin/dbunit in /Users/martins/www/mautic-magenteiro/upgrade_v3.php on line 259

Call Stack:
    0.0030     703544   1. {main}() /Users/martins/www/mautic-magenteiro/upgrade_v3.php:0
    2.0490     752192   2. runPreUpgradeChecks() /Users/martins/www/mautic-magenteiro/upgrade_v3.php:736
    2.1996     792840   3. SplFileInfo->getSize() /Users/martins/www/mautic-magenteiro/upgrade_v3.php:259

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

### Extra info
After some debug, I can see the stat failed because:
bin/dbunit is a symlink pointing to ../vendor/phpunit/dbunit/dbunit which doesn't exist

**Comment by dennisameling** [comment]
Thanks for reporting this. Haven't seen this kind of issue before, and we tested extensively on Linux/Windows. Maybe this issue is Mac-related (looking at your upgrade log)?

The part where this error occurs is the step which checks if you have enough disk space available to do the Mautic 3 upgrade.

If you're 100% sure that there's enough disk space available, I'd like to offer you the following workaround since this is a non-critical part of the upgrade process:

- Open `upgrade_v3.php` in a text editor
- Go to [line 259](https://github.com/mautic/mautic/blob/2.16.4/upgrade_v3.php#L259) which is `$mauticRootFolderSize += $file->getSize();`
- Replace it with `$mauticRootFolderSize = 50000000;`

That should allow you to proceed with the upgrade. Please let us know if that helps!

**Comment by RCheesley** [comment]
@r-martins can you let us know if you have any feedback on this? If not we will close the issue down.

**Comment by r-martins** [comment]
Thanks for your feedback and solution folks.
In fact I was using mac. I always perform the updates on my local, test it, and only after that I push the changes to the server.
At that time I had enough space (around 100gb) for sure.
I ended up reinstalling mautic and now using composer to perform updates.
