### ISSUE TITLE
missing table prefix on campaign repository 

### ISSUE THREAD

**Issue by adirbnology** [mautic/mautic#9558]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.2.2 -rc
| PHP version | 7.3.25
| Browser | firefox

### Steps to reproduce
1. update mautic to 3.2.2
2. go to segments and open one of them
 
### Log errors
mautic.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\TableNotFoundException: "An exception occurred while executing 'SELECT c.id, c.name, ROUND(IFNULL(COUNT(DISTINCT t.lead_id)/COUNT(DISTINCT cl.lead_id)*100, 0),1) segmentCampaignShare FROM mgtcampaigns c LEFT JOIN mgtcampaign_leads cl ON cl.campaign_id = c.id AND cl.manually_removed = 0 LEFT JOIN (SELECT lll.lead_id AS ll, lll.lead_id FROM lead_lists_leads lll WHERE lll.leadlist_id = 40 AND lll.manually_removed = 0) t ON t.lead_id = cl.lead_id WHERE c.id IN (31, 30, 26) GROUP BY c.id':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_gt.lead_lists_leads' doesn't exist" at /var/www/mautic_gt/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 42 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT c.id, c.name, ROUND(IFNULL(COUNT(DISTINCT t.lead_id)/COUNT(DISTINCT cl.lead_id)*100, 0),1) segmentCampaignShare FROM mgtcampaigns c LEFT JOIN mgtcampaign_leads cl ON cl.campaign_id = c.id AND cl.manually_removed = 0 LEFT JOIN (SELECT lll.lead_id AS ll, lll.lead_id FROM lead_lists_leads lll WHERE lll.leadlist_id = 40 AND lll.manually_removed = 0) t ON t.lead_id = cl.lead_id WHERE c.id IN (31, 30, 26) GROUP BY c.id':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_gt.lead_lists_leads' doesn't exist at /var/www/mautic_gt/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:42, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_gt.lead_lists_leads' doesn't exist at /var/www/mautic_gt/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:80, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mautic_gt.lead_lists_leads' doesn't exist at /var/www/mautic_gt/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:75)"} []

### Solution
the issue caused by missing table extension in the campaign repository ('CampaignBundle\Entity\CampaignRepository.php')
replace  '(SELECT lll.lead_id AS ll, lll.lead_id FROM lead_lists_leads lll WHERE lll.leadlist_id = '  with '(SELECT lll.lead_id AS ll, lll.lead_id FROM '.MAUTIC_TABLE_PREFIX.'lead_lists_leads lll WHERE lll.leadlist_id = ' should solve the issue

![image](https://user-images.githubusercontent.com/67871785/103633835-ec928200-4f4e-11eb-9388-c364e09b3d4b.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi @adirbnology thanks for reporting this, can you confirm if this happened after updating to 3.2.2 (as a side note you should really be using the released version rather than the Release Candidate if you're in a live environment!) or with a new install?

Can you check if the table exists in your instance, and if not whether there are any outstanding schema updates (see docs [here](https://docs.mautic.org/en/troubleshooting/update-failed#checking-for-schema-updates))?

**Comment by adirbnology** [comment]
i can confirm its happening after updating to 3.2.2.

regarding the table - it exists with a prefix. users who has no table prefix on their setup wont have this bug.

**Comment by RCheesley** [comment]
Would you be up for making the PR to fix this? Happy to help or there are some docs here: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests

**Comment by adirbnology** [comment]
i can try.
