### ISSUE TITLE
Cookie Use and Classification

### ISSUE THREAD

**Issue by nbwpuk** [mautic/mautic#9563]
## Description
I have the pleasant task of task of updating our cookies policy and classifying all cookies that we use. We have Mautic setup to track website visitors and current customers.
We have four cookies that are being set by Mautic: mtc_id, mautic_device_id, mautic_referer_id & mtc_sid
I have search the documentation but can only find details for mtc_id ( https://docs.mautic.org/en/contacts/manage-contacts/contact-monitoring#local-contact-cookie ) as a Targeting cookie and that "This cookie will have the value of the ID for the currently tracked contact. This provides access to server side software to the contact ID and thus providing the ability to integrate with Mautic's REST API as well."

Where can I find out how these should be classified (Functional, Targeting, Performance or Strictly Necessary) and a short description of what they are used for within Mautic?

| Q   | A
| --- | ---
| Mautic version | 3.2.2
| PHP version | 7.3
| Browser | Firefox

**Comment by RCheesley** [comment]
Hi @nbwpuk a great question, but one suited for the forums at https://forum.mautic.org rather than Github. Please can you pop a post up there, and hopefully with the replies we can collectively improve the documentation on this important topic!
