### ISSUE TITLE
No options for multiple sending domain (multiple feature feedback)

### ISSUE THREAD

**Issue by erizonweb** [mautic/mautic#9565]
Hi, I first would like to say something about Mautic.

I originally started using Mautic on my self-hosted VPS email server and absolutely loved it, so I want to thank the community for making such a great tool.

.... however, I have unfortunately been forced to move over to MailWizz for 1 main reason = lack of options for multiple sending domains.

For such an amazing tool this is such a big shame not to have something so basic and necessary like this. As I am not an experienced developer I do not know exactly how this can be solved, but from a high level perspective this would be my solution.

- Similarly to MailWizz, rather than having only 1 dedicated area to integrate only 1 email server, give the option to create multiple delivery servers allowing the admin to enter the credentials (SMTP or SendGird or Mailgun etc) for each extra domain!
- MailWizz also has an option to create multiple bounce server which is just as important and as shown in the picture below has a dedicated area to do this as well.
- When creating a campaign Mautic already has this feature where you can specify the send from email but witht his feature added and you enter any of your additional domains they will be fully authenticated with the SMTP credentials you previously entered in the delivery server section. It would also be nice to have a drop down selection menu and for Mautic to present you with the domains automatically detected from your delivery server section. By having this, users are less likely to accidentally misspell their email domain and also Mautic could pop-up a message letting a user know "you have manually entered an email that has not been authenticated yet, do you want to create a delivery server for this domain? If yes click here" sort of thing.
- As an extra bonus later on you can also give the admin an option to create customer accounts like MailWizz has. This basically creates an extra instance of Mautic with stripped down functionality allowing only the basics like creating a campaign, list, etc removing all the complicating aspects a client would not need to see and reserving those for the admin.

All in all I am disheartened to see the great potential of Mautic not being reached. Like I said I have been forced onto MailWizz for my own personal requirements even though the tool is way less user-friendly and elegant compared to Mautic. I hope my feedback is taken seriously and one day we can see this implemented into Mautic.

I don't want to be just negative, here are some features I absolutely love about Mautic and will struggle to live without

1. The drag and drop automated campaign builder — so amazing!
2. The vast amount of action to choose from (did they open, did the download something, did they click a link, etc)
3. The email template designer, super handy but could still be improved to the level of the beefree email builder.
4. Just the overall work-flow and feel of the tool
5. I love the branding and design of Mautic
6. Much more...!

Again thank you to the open source community of Mautic and I appreciate the love you put into such an excellent software.

![mailwizz_functionality](https://user-images.githubusercontent.com/76046120/103843673-4c9d3b80-50a9-11eb-9280-5c89dc3606a4.png)

**Comment by RCheesley** [comment]
Hi there, thanks for the suggestions however we use the forums for feature requests and I notice that we already have this feature requested [here](https://forum.mautic.org/t/ability-to-specify-different-email-gateways-to-use-for-different-purposes/10620/5).

Please add your vote there and any additional details.

If you wish to work on this we welcome pull requests - the documentation for contributing can be found here: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests.
