### ISSUE TITLE
Internal Error 500 when opening Segments

### ISSUE THREAD

**Issue by dl-lim** [mautic/mautic#9567]
| Q   | A
| --- | ---
| Mautic version |  3.2.2
| PHP version | 7 (Docker mautic:v3)
|Database type and version | mariadb:10.4
| Browser | Chrome

### Steps to reproduce
I use the mautic:v3 docker image and spun up a container. Then updated via the bell icon on the web interface, from 3.0.2 to 3.1.2 and then from 3.1.2 to 3.2.2. Please let me know if there is a better way to do this directly to get 3.2.2 via docker, since this is suggested in https://github.com/mautic/docker-mautic/issues/182. Not sure if this is specifically a docker issue or a Mautic Issue.

Now, when I click on Segments, the load bar shows up for a few seconds before disappearing and then nothing happens. If I open Segments on a new tab, it shows Internal Error 500.

What’s wrong???

### Log errors

If this is referring to the docker logs for the container, which I believe is the apache log, no error is showing. Otherwise, please let me know where to locate the log. happy to post it here. [mautic root]/app/log/ is empty.

**Comment by andrew-dixon** [comment]
I have the same issue after following the same upgrade steps. Generally works but certain things don't work and generate the  "Uh oh!...." response in the interface, e.g. saving a new email. Other things just don't respond, like clicking on a contact to open the contact, but they are also generating the same 500 response in the background. 

Cannot find anything in any log file or log output on the server beyond the 500 errors in the "access" log output to Docker, e.g.:

```
172.17.0.1 - - [12/Jan/2021:10:06:44 +0000] "POST /s/emails/new?mauticUserLastActive=12&mauticLastNotificationId= HTTP/1.1" 500 55772 "https://mautic.mydomain.com/s/emails/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
```

I've tried switching "debug" on in `app/config/local.php` file, e.g.:

```
        'debug' => true,
```

But this seems to have no effect at all, even after restarting the container and generating more errors in the Mautic interface. The `app/logs` is completely empty.

**Comment by andrew-dixon** [comment]
So, after a bit more digging about I managed to find some error logs in `var/logs` and these pointed me to the fact it was a database error, specifically a missing column from the DB. In the documentation it suggests running:

```
http://[your-mautic-url]/s/update/schema
```

However, this just said everything was up-to-date. So instead I took a look at the command line `console` tool and found the `doctrine:migrations` options in it. I tried the `status` command and the output seemed to suggest and issue as it reported the following:

```
    >> Executed Migrations:                                134
    >> Executed Unavailable Migrations:                    134
    >> Available Migrations:                               17
    >> New Migrations:                                     17
```

With the second 134 highlighted in red and the last 17 in teal. I tried the commands including the command to "migrate" but they didn't do anything. I noticed in the status it showed this data was held in a DB table:

```
    >> Version Table Name:                                 mym_migrations
```

So using Navicat I created a duplicate of this table as a backup and then truncated it, (FYI `mym_` is my table prefix, your table prefix will be different). After truncating this table I ran the status command again and got:

```
    >> Executed Migrations:                                0
    >> Executed Unavailable Migrations:                    0
    >> Available Migrations:                               17
    >> New Migrations:                                     17
```

And then ran the `migrate` command and it applied all the missing DB changes to the database and now everything seems to work (not test fully yet).

The commands you need in full are:

```
php bin/console doctrine:migrations:status
php bin/console doctrine:migrations:migrate
```

Run these from the app root, e.g. `/var/www/html/`

@alderson59 hope this helps you as well.

**Comment by lucasmonnin** [comment]
Hi everyone,
had the same issue after upgrading to Mautic 3.2.2, I couldn't access to contacts.
I ran this command via SSH and it came back to normal :

`php /home/default/html/bin/console cache:clear `

Hope this will help :)

**Comment by alderson59** [comment]
@andrew-dixon Thanks, I just got around to attempting your php commands.

However, suddenly, today, I wasn't able to update at all. I did exactly the same steps, to no avail. The web update just got stuck at "Downloading package", status "In progress", for a full 30 mins. Tried this 3 times on 3 fresh containers. Cleared cache, pulled new container.

Did no changes to the server except try again. Updated fine the other day. Now it didn't work anymore. Logs not showing anything other than my browser connection and cron requests.

**Comment by dl-lim** [comment]
@andrew-dixon , Thank you for the help! 

I did as you suggested, while clearing cache before and after each step. Works well at 3.2.2 now!

Perhaps this could be added to the docker mautic documentation?

Here are my steps for reference:
Click on the bell icon on top left after signing in to update via web.

After updating, `docker exec` into the container, and do the following:

Clear cache
`rm -r var/cache/*`
Check new migrations available
`php bin/console doctrine:migrations:status`
`php bin/console doctrine:migrations:migrate`
Clear cache again
`rm -r var/cache/*`

Repeat for each update version.

**Comment by RCheesley** [comment]
We have an open issue in the Docs repo for writing documentation on working with Docker: https://github.com/mautic/mautic-documentation/issues/159 - please do hop in as we would appreciate all contributions!
