### ISSUE TITLE
[Feature request] Display custom content on the website based on lead's actions

### ISSUE THREAD

**Issue by inseti** [mautic/mautic#957]
It'll be great to be able to push a custom conditional message or content inside a web page based in the lead's points (or other lead's info) who is visiting the page.

It could be done through a token or an script as it's done with embedded forms.

Providing this kind of user experience will be really awesome!

**Comment by troelsfeodor** [comment]
+1

**Comment by RCheesley** [comment]
That sounds really interesting, could you also potentially pull in details
that you know about the user and make use of that, too?

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 30 September 2015 at 23:26, inseti <notifications@github.com> wrote:

> It'll be great to be able to push a custom conditional message or content
> inside a web page based in the lead's points (or other lead's info) who is
> visiting the page.
>
> It could be done through a token or an script as it's done with embedded
> forms.
>
> Providing this kind of user experience will be really awesome!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/957>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by that0n3guy** [comment]
@RCheesley I think your right, points are a little narrow focused.  Basing it on lead fields, tags and list (as well as points) would be good.

X2 CRM does this pretty well.  Here is a quick example video I created of how it is done in x2: https://goo.gl/a9SkHB

**Comment by RCheesley** [comment]
Well what I was meaning is that you could maybe visually alter the page
they land on, using data from Mautic - so if they have visited the purchase
page last week you might want to give them a different experience to
someone who has visited the 'I want to complain' page yesterday :)

Ruth

*Ruth Cheesley*
*CEO & Co-Founder*

Virya Group Limited

P: +44 (0) 1473 852130
E: ruth.cheesley@viryagroup.com
M: +44 (0) 7920 404314

On 6 November 2015 at 20:00, that0n3guy <notifications@github.com> wrote:

> @RCheesley <https://github.com/RCheesley> I think your right, points are
> a little narrow focused. Basing it on lead fields, tags and list (as well
> as points) would be good.
>
> X2 CRM does this pretty well. Here is a quick example video I created of
> how it is done in x2: https://goo.gl/a9SkHB
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mautic/mautic/issues/957#issuecomment-154422855>.
>

-- 
Be like me, be Carbon free - don't print this and save a tree
IMPORTANT: The contents of this email and any attachments are confidential. 
They are intended for the named recipient(s) only. If you have received 
this email by mistake, please notify the sender immediately and do not 
disclose the contents to anyone or make copies thereof.

**Comment by ispajic** [comment]
+1

**Comment by terzeab** [comment]
+1

**Comment by wderuijter** [comment]
+1
You're totally right @RCheesley. We're using a persona lead field in Mautic. It would be great to present different info to different persona's.

It would be awesome to get a field value (in our case 'persona' for example) from mautic and match it to an access level in WP or Joomla. That way you can show or hide pages/articles/modules for certain people.

**Comment by philippelarcher** [comment]
On the same idea, smart forms would be great with those features :

- choose which fields to display according to the visitor

- pre-fill (populate) the fields according to the visitor

That kind of features is called "progressive profiling" usually.

**Comment by npracht** [comment]
Hi,

I think it now de eloped due to web push notification channel https://github.com/mautic/mautic/pull/1656 and dynamic content channels https://github.com/mautic/mautic/pull/1882.

N.

**Comment by ispajic** [comment]
Pretty f-ing awesome
