### ISSUE TITLE
possible bug in resend code in retry times handling

### ISSUE THREAD

**Issue by pety-dc** [mautic/mautic#9572]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When an email send failes, it gets resent. Should be tried a few times.
https://github.com/mautic/mautic/blob/features/app/bundles/EmailBundle/EventListener/EmailSubscriber.php
The `onEmailResend` method contains an odd condition:
```
if (true || $retries > 3) {
                    //tried too many times so just fail
```

This looks like a debugging condition left in the code. 
Or is it deliberate?

| Q   | A
| --- | ---
| Mautic version |  3.2
| PHP version | -
| Browser | -

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
Related slack conversation https://mautic.slack.com/archives/G01AMQPDZSB/p1611604540000500
Yes, it's bug from codebase from 2014 :) and could be removed
