### ISSUE TITLE
Error 500 on new install

### ISSUE THREAD

**Issue by PatricioMds** [mautic/mautic#9576]
| Mautic version = 3.2.1
| PHP version = 7.4.9
| Browser = tested on Firefox and Chrome

Hello,
I've uploaded all the files to a new folder on the server and followed the instructions in here https://docs.mautic.org/en/setup/getting-started about the file ownership. But when I load the application to start the installation it shows error 500. I don't even get the page to set the database.

The cache and logs are empty.
Please can you help?

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by spencerthayer** [comment]
> Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

@RCheesley is doesn't seem like the Mautic team is actually fixing the problem  in the forums. @PatricioMds did you find a fix?

**Comment by RCheesley** [comment]
This is not an issue with Mautic, but with the server setup/configuration. There is nothing to be fixed by the Mautic team. Please find a freelancer to set up your instance or work with a SaaS provider if you are finding there are technical challenges that you are not able to resolve yourself.

**Comment by spencerthayer** [comment]
> This is not an issue with Mautic, but with the server setup/configuration.
~@RCheesley

Perhaps the official [minimum requirements documentation](https://www.mautic.org/download/requirements) needs to be updated in greater detail so that people can be sure they have the proper setup/configuration?
