### ISSUE TITLE
Add email via API requires "publish others" permission for own email to be published

### ISSUE THREAD

**Issue by andrew-dixon** [mautic/mautic#9582]
## Bug Description
If you add a user role with the permissions to "create" and "publish own" emails and then use the API to create a new email and you send `isPublished=1` in the call, meaning the email should be published, it will return as `isPublished: false` in the response and show as unpublished in the Mautic interface. 

If you change the user role to include the "publish others" emails permission, then the same call returns `isPublished: true` and the email shows as published in the Mautic interface.

As the email is being added and published in the same call, "publish own" should be enough permission to allow the user to publish the email.

| Q   | A
| --- | ---
| Mautic version | 3.2.2
| PHP version | 7.4
| Browser | N/A

### Steps to reproduce
1. Add a user role with permission to "create" emails and "publish own" emails.
2. Add a user in the new role.
3. Send an `emails/new` request to the API with the `isPublished` variable set to `1` (true) using the user created in step 2.
4. See in the response the `isPublished` is set to `false`
5. Add the permission "publish others" emails to the user role created in step 1.
6. Send the same request from step 3 and see in the response the `isPublished` is set to `true`

**Comment by RCheesley** [comment]
Thanks for reporting this @andrew-dixon  - does this persist with 3.2.5?

Would you be up for looking into it and making a PR to address it?

**Comment by andrew-dixon** [comment]
@RCheesley Yes, this issue still exists on 3.2.5 and no I don't have the skillset to great a PR at this time.

**Comment by RCheesley** [comment]
OK thank you for confirming!
