### ISSUE TITLE
Install Error mautic 3.2.2

### ISSUE THREAD

**Issue by maddy2101** [mautic/mautic#9583]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

| Q   | A
| --- | ---
| Mautic version | 3.2.2
| PHP version | 7.2, 7.3
| Browser | Google Chrome

### Steps to reproduce
New local install of mautic 3.2.2, I downloaded the zip from github.
I fill in the form to provide DB credentials, click next step, and the sad mautibot (I like him anyway) reports the 500 error.
 
### Log errors

WARNING: [pool www] child 1724 said into stderr: "NOTICE: PHP message: PHP Warning:  Cannot use a scalar value as an array in /var/www/html/app/bundles/InstallBundle/Install/InstallService.php on line 337"
[error] 1714#1714: *6 FastCGI sent in stderr: "PHP message: PHP Warning:  Cannot use a scalar value as an array in /var/www/html/app/bundles/InstallBundle/Install/InstallService.php on line 337" while reading response header from upstream, client: 172.19.0.6, server: _, request: "POST /index.php/installer/step/1 HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "mautic.ddev.site", referrer: "https://mautic.ddev.site/index.php/installer/step/1"

Code wise InstallService->createDatabaseStep sets $messages to true in line 311, then the DB connection fails (I get an exception) and in line 331 $messages is to be reused as an array. This fails.

The Exception I get is a DBAL Driver connection stating "An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory"

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by dennisameling** [comment]
`SQLSTATE[HY000] [2002] No such file or directory` normally means that you entered a non-existing database host IIRC. Could that be the case here?

**Comment by maddy2101** [comment]
not exactly, I had a typo in the host address. But the issue is not about my wrong DB credentials, but about the unneccessary error 500. A real error message telling me no connection can be made to my DB would have been much more helpful.

**Comment by RCheesley** [comment]
We already have an issue tracking this regression in #9473 so I will close this issue in favour of the existing issue.
