### ISSUE TITLE
Updating contact fields via campaign fills date fields

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#9584]
## Bug Description
I created a campaign which should automatically fill custom contact fields. This worked well, but also all date and date+time fields in the contact were updated, even if I didn't select them. They were updated with the current date and time

| mautic v3.2.1 | 
| PHP version 7.3.22 | 

### Steps to reproduce
1. create a campaign
2. use the action "update contact"
3. fill in a value in a field which is not date or date+time
4. after running the cronjobs the contacts' date and date+time fields are updated with the current date/time
 
### Log errors

no log errors

**Comment by MaraKasubke** [comment]
Hey karo-me, thanks for creating this bug description. I have the same problem when updating a contact via campaign.

PHP Version 7.3.24-3
Mautic v3.2.1

**Comment by MaraKasubke** [comment]
Would updating to Mautic 3.2.4 solve this issue?

**Comment by MaraKasubke** [comment]
We have now updated Mautic to 3.2.4. This has resolved the issue for us. Can you confirm this @karo-me ?

**Comment by ghost** [comment]
Hi @MaraKasubke
Right now I'm still working with my developers on a backup-process. I don't want to try to restart the campaign before I have a backup of my data. So I will give you feedback soon.

**Comment by ghost** [comment]
@MaraKasubke Now I finally could test it again. And now everything is working as it should. Thank you!!
