### ISSUE TITLE
Not all calendar items are displayed on certain months

### ISSUE THREAD

**Issue by netzimon** [mautic/mautic#9586]
## Bug Description
When I add a note to a contact and assign a date on a month where I have lots of events, the note entry is not displayed on the Calendar. When I switch the date to a month with less entries (either before or after the month that has lots of entries) the note shows up just fine on the calendar.
Is this a bug related only to version 2.x of Mautic? If so, is there a patch that can be applied? I am unable to upgrade this installation of Mautic to version 3 because of the MySQL/MariaDB requirement (MySQL 5.7.14 or MariaDB 10.2 or higher) which I can't update on this specific server.

| Q   | A
| --- | ---
| Mautic version | 2.16.3
| PHP version | 7.2.29
| Browser | Chrome 87.0.4280.141

### Steps to reproduce
1. Add a new note (with a date and time assigned) under a contact entry.
2. Go to Calendar section - note does not show up under the date assigned.
 
### Log errors
No log errors found

**Comment by netzimon** [comment]
This issue may be the same as mentioned here: [Max of 100 Lead Notes shown on Calendar, and ordering is confused](https://github.com/mautic/mautic/issues/8685)

If so, is that bug fixed?

**Comment by netzimon** [comment]
Confirmed - by changing the value declared in setMaxResults in the file app/bundles/LeadBundle/EventListener/CalendarSubscriber.php the calendar works normally again.

Is this something that will be fixed in a future version of Mautic? Meaning: either raising this limit by default or allowing the value to be changed in the config file.

**Comment by RCheesley** [comment]
Hi there, we are no longer supporting Mautic 2.x so I am closing this issue. If you experience this with 3.2.5 or later and wish to make a pull request to change the behaviour please do!
