### ISSUE TITLE
REST API permits the creation of bool fields without yes/no label. This then crashes Segment->New page.

### ISSUE THREAD

**Issue by dhilst** [mautic/mautic#9591]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The REST API permits you to create a bool custom field and do not provide the yes/no label. As result the fields are created with empty label. This then crashes at line 807 of app/bundles/LeadBundle/Model/ListModel.php

<img width="520" alt="image" src="https://user-images.githubusercontent.com/392820/104764237-ddc57f80-5745-11eb-95e1-72e7568e814f.png">

`$properties['no']` raises undefined index.

This is not critical in IMO, just annoying. We have lots and lots of custom fields so I use an ansible playbook to create it and then faced this bug. The mitigation is very easy too, just find the buggy field and fill the yes/no labels and everything start to work again. IMO the API should return 400 if these labels are missing.

| Q   | A
| --- | ---
| Mautic version | 3.2.4
| PHP version | 7.3
| Browser | Firefox

### Steps to reproduce
1. Create a boolean field without labels from the REST API (note that the browser interface auto fill the yes/no labels so the bug isn't hit)
2. Try to create a new segment
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
@dhilst thanks for taking the time - indeed sounds a bit annoying! Would you be up for digging into this and making a PR to implement your suggestions?

**Comment by dhilst** [comment]
I can do it, I'm just rushing right now but once I get some free time I can do it :)
