### ISSUE TITLE
Leads stuck in loop inside tag check pre DST [$30]

### ISSUE THREAD

**Issue by ldrrp** [mautic/mautic#9592]
## Bug Description
When a campaign event was triggered for some leads on Oct 30th 2020 and scheduled past DST change, For example Nov 2nd 2020. The lead will get stuck in "should schedule" where date_triggered is always greater than now() causing the lead to get stuck in an endless loop where it reschedules. This is probably pertaining to how PHP DateTime works with comparing dates.

| Q   | A
| --- | ---
| Mautic version | Replicated in all versions up to date 3.x, including prior 2.16.x installs
| PHP version | 7.3
| Browser | N/A

### Steps to reproduce
1. Create a campaign and add a condition based on a contacts tags.
![Screen Shot 2021-01-15 at 4 19 50 PM](https://user-images.githubusercontent.com/985837/104779726-99d67880-574d-11eb-843a-08bcc18210e0.png)
2. Add the user to the campaign, They will be scheduled out for 3 days after running the cron.
3. Go into database and alter the `date_triggered` for the event inside `campaign_lead_event_log` table to be a date prior to Nov 1st
4. You can either wait 3 days now or reschedule to be 1 min ahead of your current time. Then rerun the cron.
5. User will be pushed to reschedule because as shown in the log below (2021-01-14 15:43:18 EST > 2021-01-14 19:43:18 UTC) = true ALWAYS
 
### Log errors

```
[2021-01-14 19:43:18] mautic.DEBUG: CAMPAIGN: Triggering scheduled events  
[2021-01-14 19:43:18] mautic.DEBUG: CAMPAIGN: 1 events scheduled to execute.  
[2021-01-14 19:43:18] mautic.DEBUG: CAMPAIGN: Comparing calculated executed time for event ID 14 and contact ID 36671 with 2020-10-30 20:52:06 UTC  
[2021-01-14 19:43:18] mautic.DEBUG: CAMPAIGN: Scheduling event ID 14 for contact ID 36671 based on hour range of 10:00 UTC to 20:00 UTC  
[2021-01-14 19:43:18] mautic.DEBUG: CAMPAIGN: Scheduling event ID 14 for contact ID 36671 based on DOW restrictions of 1,2,3,4,5  
[2021-01-14 19:43:18] mautic.DEBUG: CAMPAIGN: Log ID #26137 to be executed on 2021-01-14 15:43:18 America/New_York compared to 2021-01-14 19:43:18 UTC
```

### Temporary workaround

List affected leads
```
SELECT * FROM campaign_lead_event_log WHERE is_scheduled = 1 AND date_triggered <= "2020-11-01 02:00:00";
```

Fix affected leads
```
UPDATE campaign_lead_event_log SET date_triggered = '2020-11-02 00:00:00' WHERE is_scheduled = 1 AND date_triggered <= "2020-11-01 02:00:00";
```

**Comment by RCheesley** [comment]
@ldrrp thanks for reporting the bug and for the workaround! Would you be able to look into a fix for this?

**Comment by ldrrp** [comment]
@RCheesley unfortunately im not sure I have the time to fix this at the moment myself thats why I did the workaround. I did post a bounty. I might try and see if my workplace might increase it.

**Comment by rivael** [comment]
Thank you for the information!
My mautic install got into loop and the database was bloated.

**Comment by ldrrp** [comment]
@rivael can you help increase the bounty?

**Comment by rivael** [comment]
Sure. How do I do that?

**Comment by ldrrp** [comment]
https://www.bountysource.com/issues/96018512 @rivael Thank you, Yea i know this is going to be a problem for both of us again come next DST change

**Comment by rivael** [comment]
Done. (Added $15).

I have it again. It pauses my mautic operation.
Can it also be caused by delayed action that start from another delayed action?

**Comment by rivael** [comment]
Got this log entries:
[2021-02-23 10:07:22] mautic.DEBUG: CAMPAIGN: Action ID# 34 for contact ID# 18555 has timing that is not appropriate and thus scheduled for 2021-02-24 10:02:07 UTC
[2021-02-23 10:07:22] mautic.DEBUG: CAMPAIGN: Action ID# 34 for contact ID# 18600 has timing that is not appropriate and thus scheduled for 2021-02-24 10:02:07 UTC
[2021-02-23 10:07:22] mautic.DEBUG: CAMPAIGN: Action ID# 34 for contact ID# 18662 has timing that is not appropriate and thus scheduled for 2021-02-24 10:02:07 UTC

**Comment by ldrrp** [comment]
@rivael thats some interesting logs. I have not seen those in my logs. According to the source code though:

```
//lead actively triggered this event, a decision wasn't involved, or it was system triggered and a "no" path so schedule the event to be fired at the defined time
```

Is the event inactive?

This may be a separate issue altogether but i wouldn't know. Would you be able to post a screenshot of the campaign?

**Comment by rivael** [comment]
@ldrrp  Does this makes sense:

![Screenshot from 2021-02-23 16-55-09](https://user-images.githubusercontent.com/27514201/108861675-2a7b6080-75f8-11eb-908e-9968145a1533.png)

**Comment by rivael** [comment]
Well, I spend the last two days debugging it.
It appear that the scheduler is fetching the same contacts over and over again when the date is wrong or missing.

For now, I patched this in ./vendor/symfony/console/Helper/ProgressBar.php by throwing exception when the we reach the limit.
(I am not sure I am not harming something else):
    /**
     * Sets the current progress.
     *
     * @param int $step The current progress
     */
    public function setProgress($step)
    {
        $step = (int) $step;

        if ($this->max && $step > $this->max) {
**// mik change here: 2/3/21
            throw new LogicException('The current position is higher than the maximum. We are in a LOOP!');**
            $this->max = $step;
        } elseif ($step < 0) {
            $step = 0;
        }

        $prevPeriod = (int) ($this->step / $this->redrawFreq);
        $currPeriod = (int) ($step / $this->redrawFreq);
        $this->step = $step;
        $this->percent = $this->max ? (float) $this->step / $this->max : 0;
        if ($prevPeriod !== $currPeriod || $this->max === $step) {
            $this->display();
        }
    }

**Comment by ldrrp** [comment]
> Well, I spend the last two days debugging it.
> It appear that the scheduler is fetching the same contacts over and over again when the date is wrong or missing.
> 
> For now, I patched this in ./vendor/symfony/console/Helper/ProgressBar.php by throwing exception when the we reach the limit.
> (I am not sure I am not harming something else):
> /**
> * Sets the current progress.
> *
> * @param int $step The current progress
> */
> public function setProgress($step)
> {
> $step = (int) $step;
> 
> ```
>     if ($this->max && $step > $this->max) {
> ```
> 
> **// mik change here: 2/3/21 throw new LogicException('The current position is higher than the maximum. We are in a LOOP!');**
> $this->max = $step;
> } elseif ($step < 0) {
> $step = 0;
> }
> 
> ```
>     $prevPeriod = (int) ($this->step / $this->redrawFreq);
>     $currPeriod = (int) ($step / $this->redrawFreq);
>     $this->step = $step;
>     $this->percent = $this->max ? (float) $this->step / $this->max : 0;
>     if ($prevPeriod !== $currPeriod || $this->max === $step) {
>         $this->display();
>     }
> }
> ```

Im not sure if this applies to both loops. It seems there may be two scenarios here of a loop relating to DST. But i think the best option would be to fix it at a higher level by fixing the datetime calculations. 

Secondly for anyone reading. March 14th dont forget to set your clocks forward and run the query again the next day
