### ISSUE TITLE
PHP Notice - Undefined index: log - in file mautic\app\bundles\DynamicContentBundle\Views\SubscribedEvents\Timeline\index.html.php - at line 11

### ISSUE THREAD

**Issue by pwned555** [mautic/mautic#9597]
Mautic version - v3.2.1
PHP version - 7.3.24

## Description:
The above error is thrown when trying to open a contact that has a dynamic_content_stats table record for their id.  The contact view page will never be opened.

## Steps to reproduce:
Navigate to contacts and attempt to open a contact page and above error will be thrown if the contact has records in the dynamic_content_stats table.

I'm not 100% sure how easy this bug will be to replicate, we have some customization that allows DWC to be added to an Email.  It looks like there is coding already to track that when it's sent and it populates the dynamic_content_stats table in the database.  If there are currently other ways to get records in that table for a specific lead then doing so and trying to view the lead page will most likely cause issues.

If there isn't an easy way to replicate one possibility would be simply to populate a record in this table for a lead.  I have tested and this will cause the above error when trying to view the lead.  Example sql insert for junk data that will break lead 1 would be

insert into dynamic_content_stats (dynamic_content_id, lead_id, date_sent, source, source_id, tokens, sent_count, last_sent, sent_details)
values (null, 1, CURDATE(), 'asdf', null, 'a:0:{}', null, null, 'a:0:{}')

### Log errors: 
PHP Notice - Undefined index: log - in file mautic\app\bundles\DynamicContentBundle\Views\SubscribedEvents\Timeline\index.html.php - at line 11

## Fix:
This seems to be a copy and paste error.  The index.html.php file in mautic\app\bundles\DynamicContentBundle\Views\SubscribedEvents\Timeline has this code on line 11

Old code:
$data = $event['extra']['log']['metadata'];

The problem is if you look at where this object is created in \mautic\app\bundles\DynamicContentBundle\EventListener\LeadSubscriber.php function onTimelineGenerate(LeadTimelineEvent $event) extra is being set as follows

'extra'     => [
                                'stat' => $stat,
                                'type' => 'sent',
                            ],

So there is no 'log', it should instead be 'stat' and there is also no 'metadata' for 'stat' being returned by getLeadStats, I believe the column that looks correct is 'sentDetails'.

New code:
$data = $event['extra']['stat']['sentDetails'];

**Comment by RCheesley** [comment]
@pwned555 thanks for reporting this - would you be able to make a PR to fix the issue?

**Comment by MajesteitBart** [comment]
I've run into the same issue, with Dynamic Content on my website, not in emails. 

`[2021-02-11 13:53:12] mautic.NOTICE: PHP Notice - Undefined index: log - in file / var / www / mautic / app / bundles / DynamicContentBundle / Views / SubscribedEvents / Timeline / index.html.php - at line 11 { "mauticTemplateVars": { "app" :"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\GlobalVariables: {})",
"event": { "event" :"dynamic.content.sent",
"eventId" :"dynamic.content.sent212",
"eventLabel": { "label" :"Call to action tekst",
"href" :"/s/dwc/view/3" },
"eventType" :"Dynamische Inhoud verstuurd",
"timestamp" :"2021-01-27 23:15:17",
"extra": { "stat": { "dynamic_content_id" :"3",
"id" :"212",
"dateSent" :"2021-01-27 23:15:17",
"name" :"Call to action tekst",
"sentDetails" :[] },
"type" :"sent" },
"contentTemplate" :"MauticDynamicContentBundle:SubscribedEvents\\Timeline:index.html.php",
"icon" :"fa-envelope",
"contactId" :"1" },
"lead" :"[object] (Mautic\\LeadBundle\\Entity\\Lead: Mautic\\LeadBundle\\Entity\\Lead with ID #1)",
"mauticContent" :"lead",
"mauticTemplate" :"MauticDynamicContentBundle:SubscribedEvents\\Timeline:index.html.php",
"view" :"[object] (Mautic\\CoreBundle\\Templating\\Engine\\PhpEngine: {})" },
"app" :"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\GlobalVariables: {})",
"event": { "event" :"dynamic.content.sent",
"eventId" :"dynamic.content.sent212",
"eventLabel": { "label" :"Call to action tekst",
"href" :"/s/dwc/view/3" },
"eventType" :"Dynamische Inhoud verstuurd",
"timestamp" :"2021-01-27 23:15:17",
"extra": { "stat": { "dynamic_content_id" :"3",
"id" :"212",
"dateSent" :"2021-01-27 23:15:17",
"name" :"Call to action tekst",
"sentDetails" :[] },
"type" :"sent" },
"contentTemplate" :"MauticDynamicContentBundle:SubscribedEvents\\Timeline:index.html.php",
"icon" :"fa-envelope",
"contactId" :"1" },
"lead" :"[object] (Mautic\\LeadBundle\\Entity\\Lead: Mautic\\LeadBundle\\Entity\\Lead with ID #1)",
"mauticContent" :"lead",
"mauticTemplate" :"MauticDynamicContentBundle:SubscribedEvents\\Timeline:index.html.php",
"view" :"[object] (Mautic\\CoreBundle\\Templating\\Engine\\PhpEngine: {})" } [] `

**Comment by npracht** [comment]
I reopen as far it has been reproduced and @volha-pivavarchyk offered a fix ready to test !
