### ISSUE TITLE
CKEDITOR is stripping html

### ISSUE THREAD

**Issue by igisho** [mautic/mautic#960]
Hi ck editor is stripping html comments which are totaly essential for responsive email design, this is serious issue for email marketing system.

**Comment by alanhartless** [comment]
See #847.

**Comment by ramezrafla** [comment]
@alanhartless  and @igisho,
Truth is, we shouldn't be removing any comments from the email HTML code entered by the user. For instance, when debugging on an email client, we want to see those comments. The space / bandwidth they take is minimal (just like developers keep their comments on their webpages)

**Comment by alanhartless** [comment]
That's what #847 fixes and will be part of 1.2.1.

**Comment by ramezrafla** [comment]
Got it, sorry for misunderstanding, saw the 'Ready To Test' labels.

**Comment by mbabker** [comment]
Referenced item was merged.
