### ISSUE TITLE
Internal server error 500

### ISSUE THREAD

**Issue by badhonhitech** [mautic/mautic#9603]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Use  7.4.14
2. Use NGINX with Ubuntu 18.04
![Screenshot from 2021-01-20 23-01-34](https://user-images.githubusercontent.com/8156135/105210915-ac6bfb80-5b19-11eb-9dc2-d9992cb4c2bc.png)
![Screenshot from 2021-01-20 23-18-15](https://user-images.githubusercontent.com/8156135/105210930-ae35bf00-5b19-11eb-9c12-47094891cdce.png)
![Screenshot from 2021-01-20 23-19-10](https://user-images.githubusercontent.com/8156135/105210973-b8f05400-5b19-11eb-9c94-9a8826499656.png)

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by DevOpsEvangelist** [comment]
I am also having this issue

**Comment by RCheesley** [comment]
Hey folks, per the error logs, you need to downgrade to Composer 1. We cannot support Composer 2 until Mautic 4.0 as to do so requires breaking changes.
