### ISSUE TITLE
Height error in images inserted with mail builder

### ISSUE THREAD

**Issue by simopetrelli** [mautic/mautic#9604]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

on mobile devices (Mail Gmail) the height of the images is not responsive (screenshot https://prnt.sc/xbf3z6).
I created the mail from mail builder (see screenshot https://prnt.sc/xbf685)
There should be no height tag (see screenshot https://prnt.sc/xbfcr7). Is there any way to fix this?

Thanks a lot.

| Q   | A
| --- | ---
| Mautic version | 3.2.4
| PHP version | 7.2.24
| Browser | Chrome 87.0.4280.141

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
@simopetrelli as we are mid way through an initiative to replace the builders we probably won't be working on issues like this. I would suggest to manually remove the height in the code as a workaround or ask on https://forum.mautic.org/c/support.
