### ISSUE TITLE
There are plans to update the symfony version

### ISSUE THREAD

**Issue by gnovaro** [mautic/mautic#9608]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Version 3 is no longer supported by Symfony community

| Q   | A
| --- | ---
| Mautic version | latest
| PHP version | 7.4
| Browser | -

### Steps to reproduce
1. -
 
### Log errors
-

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, we have a Mautic 4 working group which is already part way through implementing support for Symfony 4. Take a look at #9409 and join #mautic-4 on Slack (https://mautic.org/slack to get an invite) if you would like to contribute to this!

You may also find it interesting to watch the keynote from MautiCon:  https://www.youtube.com/watch?v=FqwMjDZ8ofA where I shared the long term vision and roadmap for Mautic :)
