### ISSUE TITLE
500 error on unsubscribe

### ISSUE THREAD

**Issue by AdamLeonSmith** [mautic/mautic#9609]
## Bug Description
I am using the out of the box unsubscribe.  That is, contact preference forms are not used.

# Config

Email template references {unsubscribe_url} with a text link.
In the campaign email settings - no unsbuscribe or contact preference form is selected
In configuration / email settings - all unsubscribe options are set to no

# Steps to reproduce

Delete contact
Clear cache and restart apache to be safe!
Logout of mautic
Re-add the contact (via scripts)
Re-add the contact to a segment to trigger a campaign email to the segment (via cron jobs)

# Results
Email is received with an unsubscribe link (https://mautic.pglabs.co.uk/email/unsubscribe/600ad7881b859842335877)
Link triggers a 500 error in incognito browser
500 error shown in access log - no other errors in logs

| Q   | A
| --- | ---
| Mautic version | 3.2.4
| PHP version | 7.3.26-1
| Browser | Chrome 88.0.4324.96 (Official Build) (64-bit)

**Comment by RCheesley** [comment]
> 500 error shown in access log - no other errors in logs

Can you please share the 500 error from your Mautic log?

**Comment by AdamLeonSmith** [comment]
Apache Access log:
10.0.9.104 - - [25/Jan/2021:09:58:37 +0000] "GET /email/unsubscribe/600adb8ecc931597996003 HTTP/1.1" 500 1841 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"

There is NO corresponding errors  (or other messages) in the mautic application logs.

**Comment by elilogan** [comment]
Check permissions on var/logs folder. Set to 777 to test and then try the unsubscribe link again. Be sure to walk back your permissions after testing.

**Comment by AdamLeonSmith** [comment]
This was indeed the problem, thank you
