### ISSUE TITLE
Failed network error

### ISSUE THREAD

**Issue by sns192** [mautic/mautic#9611]
The download file at the link - https://www.mautic.org/download is not getting downloaded due to failed network, 
Please fix the issue.
Thanks in advance.

**Comment by RCheesley** [comment]
Hi there, can you please be a bit more specific about "due to failed network"?

I have just tested and the download worked as expected.

**Comment by dennisameling** [comment]
Also downloads as expected here (NL) - do you see any difference if you download from a different network (e.g. mobile hotspot)?

**Comment by sns192** [comment]
Hello, 
I am downloading this file in India and I am getting failed network error at the end when the download completes.

**Comment by mohit-rocks** [comment]
Hi @sns192 
I am based in India and able to download from the broadband and mobile connection as well.
Alternatively, you can also download from the releases page https://github.com/mautic/mautic/releases
You can download the latest release "Mautic Community 3.2.4"

Closing this issue, for now, please reopen if you face any further issues.
