### ISSUE TITLE
Field order ignored for contact /edit page

### ISSUE THREAD

**Issue by andrew-dixon** [mautic/mautic#9612]
## Bug Description
It is possible to order the contact fields in the "Custom Fields" editor and this order is used on the "Quick Add" and "New" contact screens/forms, but isn't for the "Details" output on the Contact View page or on the Contact Edit page, which appears to use the order in which the fields were created instead. This makes the user interface inconsistent and annoying to use for a user with lots field they expect in a particular order. The pages in question are:

`/s/contacts/view/[id]`

and

`/s/contacts/edit/[id]`

| Q   | A
| --- | ---
| Mautic version | v3.2.2
| PHP version | v7.3.20
| Browser | Chrome

### Steps to reproduce
1. Go to the Custom Field edit page and reorder some of the fields.
2. Go to the Contacts page and click "Quick Add" and see the fields in the order you just arranged them.
3. Click on a Contact to view them.
4. Click the "DETAILS" button on the top left of the view page and see the fields are not in the same order.
5. Click the "Edit" button on the top right of the view page and on the edit page, see the fields are not in the same order.

**Comment by npracht** [comment]
HI @andrew-dixon !
That might be fixed by https://github.com/mautic/mautic/pull/9494 in next 3.3.0.
Can you test the PR, confirm and if yes, close your issue ?

Thanks !

**Comment by andrew-dixon** [comment]
@npracht I've not got a setup at the moment where I could test that, but looking at the file changes in the pull request, I think it would only resolve half of it, the details view on the contact view page and not the edit contact page.

**Comment by npracht** [comment]
@andrew-dixon did you have the time to test for the edition ?
Thanks
