### ISSUE TITLE
Contact List missing direct link to view contact

### ISSUE THREAD

**Issue by andrew-dixon** [mautic/mautic#9613]
## Bug Description
If you remove the "Name" and "ID" columns from the "Contacts" list view, none of the columns is then linked to view the contact. Instead, either there should always be a "view" icon output, maybe on the far right, or the first column should always be linked to view the contact (my preferred option).

I'm aware you can still click the down arrow next to the tick box and then click the "Details" option to view the contact, but this isn't particularly obvious to "standard" users and is a little clunky to do.

| Q   | A
| --- | ---
| Mautic version | v3.2.2
| PHP version | 7.3.20
| Browser | Chrome

### Steps to reproduce
1. Go to Configure > Contact Settings 
2. Remove the ID and "First name Last name" columns from the "Columns" section under "Contact List Settings" and Apply.
3. Go to "Contacts" and see the list is now missing any direct link to view the contact.

**Comment by RCheesley** [comment]
Thanks for flagging that @andrew-dixon - honestly my first thought would be 'well, don't remove the ID field'!

I don't know that we would want to add a superfluous icon given that the vast majority of users would not have this issue, however we can see what UX folks think!

**Comment by andrew-dixon** [comment]
@RCheesley I would say if there is the option to remove it, then there needs to be something sensible in place to replace it if you do remove it. I was specifically asked by my end user to "remove the useless ID column", as for them it has no value, for their workflow, but then of course they complained they couldn't easily get the view screen 😃 

So I guess the options here are to either remove the option to remove the ID column or changing it to always link the first column, whatever that is set to, but then if it is set to a column that can have no value, then that might not work either. The joys of software design 😃

**Comment by andersonjeccel** [comment]
It's fixed using an individual column for actions, with the option Details under the dropdown.
