### ISSUE TITLE
error while connecting gmail account. has anyone successfully connected to gmail account?

### ISSUE THREAD

**Issue by sns192** [mautic/mautic#9615]
I allowed access to less secure apps in my gmail account, yet I am getting almost a page long error while configuring gmail settings in mautic. what is the solution?

**Comment by jos0405** [comment]
Hi, can you be plz more specific: is it fetching incoming mail or sending email via gmail smtp?

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
