### ISSUE TITLE
Emails are landing in promotion tab. How it fix it? 

### ISSUE THREAD

**Issue by sns192** [mautic/mautic#9620]
Hello, I recently switched to Mautic to send emails to my subscribers. 
Emails are being sent to the promotion box instead of the mailbox. When I used other CRMs to send emails they landed in inbox, not promotion tab. 

I read this forum which discusses the issue the detail - https://forum.mautic.org/t/mautic-lands-in-promotions-or-spam-folders-seems-to-be-impossible-to-tweak-any-idea/16675

The two people who are discussing the issue tried almost everything to fix it but in vain. 

From what I understand, it is because of "Bulk" tag added by mautic in emails, due to which it is landing in promotions tab. 

So now how to fix it? I have small number of subscribers and landed their inbox, Now after I switched to mautic emails are landing in promotions tab. 

How to remove "Bulk" tag from emails? 

New to mautic - please let me know know incase more details required.

Mautic version - latest version at https://www.mautic.org/download which is 3
PHP version - 7.4

**Comment by jos0405** [comment]
Hi, please read the discussion in the forum in full. I advised strongly against removing the Bulk tag. In my opinion it would be dangerous to remove it or give the option to do so as if marketers don't understand why it is there. It is actually protecting your reputation if you are sending bulk.
If you want to remove the Bulk precedence, search for the code and uncomment the line. But again - I advise against it.

**Comment by jos0405** [comment]
Maybe we can have a special setting in Mautic, that once someone sends more than 50 emails / day, than we are automatically adding the Bulk tag...

**Comment by sns192** [comment]
Well, I am new to mautic. Can you tell me how to remove bulk precedence from email we send from mautic? 
Alsom you advise against it, but then do you have any other option to achieve. There are my subscribers, emails shouldn't go to promotion tab. 

Please tell me how to remove Bulk Precedence. 

What I tried? 
Well I went to configuration settings but could not find a way to configure it there. 

Thank you in advance.

**Comment by sns192** [comment]
I have been trying really hard to fix this. Can anyone guide me on how to achieve this?

**Comment by jos0405** [comment]
It is normal to land in promotion when you start sending, you will be moved out eventually. You are using new iP suddenly probably and you need to build up your reputation. Please check if you had the 'Bulk' tag in your previous provider.
In the forum article you could see the worst way of testing inboxing: checking 5 occurrences and deciding, that 100% goes to promo. You can try to remove bulk by searching for 'BULK' in the whole code and remove corresponding lines.

**Comment by RCheesley** [comment]
Hi folks, as this is not a bug with Mautic, please take the conversation over to the forum thread so that we do not clutter up the issue queue :)

**Comment by sns192** [comment]
I have been trying to sign up the community forum to discuss this, but due to some error haven't been able to login. 
And my my domain is more than a year old and I have been using zoho crm. All my emails landed in inbox. But now they are going to promotion tab. 

_You can try to remove bulk by searching for 'BULK' in the whole code and remove corresponding lines._ - where to search for code? I am using text template with email.

**Comment by sns192** [comment]
You may not call it a bug but it is a very serious problem. Many people are facing this issue, I request the community to come up with a solution to this. Moreover, it was said the community forum to take this to GitHub, now you are asking us to take it back to the community forum. 

Please open the issue and let the community give the solution.

**Comment by jos0405** [comment]
I'm not sure that this is a bug, but rather a feature.
Majority of users use Mautic for marketing automation to scale communication, make it less work. It has to be built for that audience. But obviously not always: on one account I'm sending around 100 emails / day, almost all customized, I'm inboxing just fine. Plz check this MautiCon clip: https://www.youtube.com/watch?v=q7VO1Kf34IE

Maybe test out without sending the bulk tag in the header, share your findings (in a proper testing environment).
But as Mautic is open source you can always create a plugin, that allows you to remove the bulk precedence from the emailing, upon low email volume.

**Comment by sns192** [comment]
Hi thanks for your input. I am not a developer so not possible for me to create a plugin for mautic. 
Even mails a customize for each recipient lands in promotion box. 
Can you please tell me how to remove bulk tag in the header? I am not a software developer so difficult for me to figure it all out. 

Thanks in advance.

**Comment by jos0405** [comment]
Hi,
When you send test email, also landing in promo?

**Comment by sns192** [comment]
Hi,
Yup, test mails, personlized email written for each mail contact mails (sent manually) and campaign emails, all three landing in promotion tab. And this was not a case before while using zoho crm.

I request you to give me a solution.
Tell me how to remove bulk tag from header, I will try and let you know the outcome. 

Thanks in advance for the support.

**Comment by jos0405** [comment]
Okay, then Mautic is not the culprit. Test mails, personal emails don't have the bulk header.
I suggest you duckduckgo why you are landing in promo, it is def not the bulk setting. Start comparing your previous sending and this one. Learn about inboxing, there are tremendous material on the web.
