### ISSUE TITLE
Inconsisent behavior in batch edit users action

### ISSUE THREAD

**Issue by dennisameling** [mautic/mautic#9621]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The batch endpoint `PATCH api/users/batch/edit` shows inconsistent behavior. If often reports the following errors: `username: Username is already in use. Please choose another., email: Email is already in use. Please choose another.` - however, this is not consistent. Sometimes the action succeeds.

**⚠️ This is a regression that was introduced in 3.2.5, very likely with this PR: https://github.com/mautic/mautic/pull/7815 ⚠️** - I wasn't able to reproduce this in Mautic 3.2.4 and lower.

I originally came across this while [moving the API library tests to GitHub Actions](https://github.com/mautic/api-library/runs/1765120475?check_suite_focus=true):

```
4) Mautic\Tests\Api\UsersTest::testBatchEndpoints
username: Username is already in use. Please choose another., email: Email is already in use. Please choose another.; username: Username is already in use. Please choose another., email: Email is already in use. Please choose another.

Failed asserting that false is true.

/home/runner/work/api-library/api-library/tests/Api/MauticApiTestCase.php:89
/home/runner/work/api-library/api-library/tests/Api/MauticApiTestCase.php:104
/home/runner/work/api-library/api-library/tests/Api/MauticApiTestCase.php:284
/home/runner/work/api-library/api-library/tests/Api/UsersTest.php:132
```

| Q   | A
| --- | ---
| Mautic version | 3.2.5 (features branch)
| PHP version | 7.3.25
| Browser | N/A (API)

### Steps to reproduce
1. Clone this minimal repo I created: https://github.com/dennisameling/mautic-users-batch-repo
2. Follow the steps in the repo to reproduce 
 
### Log errors
When testing with my minimal repo, this was my output after multiple attempts:

```
dennis@mautic-users-batch-repo-web:/var/www/html$ php index.php
Successfully created user with ID 215 and username API_9STdqrKb
Successfully created user with ID 216 and username API_t3BkHRX1
Successfully created user with ID 217 and username API_UyzMXT6L
Successfully updated 3 users
Successfully deleted 3 users

dennis@mautic-users-batch-repo-web:/var/www/html$ php index.php
Successfully created user with ID 218 and username API_W5smdejC
Successfully created user with ID 219 and username API_xkgQYW2F
Successfully created user with ID 220 and username API_4plzg5Xs
Error in edit action - 400: username: Username is already in use. Please choose another., email: Email is already in use. Please choose another.
Error in edit action - 400: username: Username is already in use. Please choose another., email: Email is already in use. Please choose another.
Error in edit action - 400: username: Username is already in use. Please choose another., email: Email is already in use. Please choose another.

dennis@mautic-users-batch-repo-web:/var/www/html$ php index.php
Successfully created user with ID 239 and username API_7SEjbTzZ
Successfully created user with ID 240 and username API_slbf40QD
Successfully created user with ID 241 and username API_y2zULNGV
Successfully updated 3 users
Successfully deleted 3 users

dennis@mautic-users-batch-repo-web:/var/www/html$ php index.php
Successfully created user with ID 242 and username API_Xena0Jw7
Successfully created user with ID 243 and username API_Vwv8AIyZ
Successfully created user with ID 244 and username API_2VSnFgsp
Error in edit action - 400: username: Username is already in use. Please choose another., email: Email is already in use. Please choose another.
Error in edit action - 400: username: Username is already in use. Please choose another., email: Email is already in use. Please choose another.
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by dennisameling** [comment]
@alanhartless as you're the author of https://github.com/mautic/mautic/pull/7815, do you have any idea what could be causing these issues? The fact that it's inconsistent makes it rather hard to debug on my side 😞

**Comment by RCheesley** [comment]
@alanhartless are you able to look into this? Or @mautic/acquia-po can we have the community rotation person dig into it?

**Comment by lukassykora** [comment]
Hi, I think the problem is in the CommonApiController::getBatchEntities. I think it does not return the entities in the right order. I am working on the fix.

**Comment by alanhartless** [comment]
Yea. The problem is that the repositories are returning entities in a
default order defined by the repo. But getBatchEntities is then processing
based on the parameters key so they are mismatched.

There’s a line in the ID order helper that just returns by array key if
found to be numerical keys. Can that just be removed and let the logic of
ID mapping do it’s thing? If changing anything, be sure to look at the PR
that made the change to ensure that batch delete returns as expected.

**Comment by lukassykora** [comment]
The PR is: https://github.com/mautic/mautic/pull/9745. It goes to the 3.3 because the 3.2 has some failures.

**Comment by RCheesley** [comment]
Great - thanks for making the PR @lukassykora!

**Comment by dennisameling** [comment]
Fixed in https://github.com/mautic/mautic/pull/9745 so closing this issue 👍🏼
