### ISSUE TITLE
Resubscribe link causes error message output

### ISSUE THREAD

**Issue by andrew-dixon** [mautic/mautic#9624]
## Bug Description
When a user clicks on the "resubscribe" option on the unsubscribe page, it causes the "Uh oh!" error message page to be output. Whilst it does resubscribe the user, it doesn't tell the user this.

I've discussed this bug here: https://forum.mautic.org/t/resubscribe-link-errors/17911

Essentially, it isn't passing the theme to the Theme Helper constructor in `app/bundles/CoreBundle/Templating/Helper/ThemeHelper.php` and if you override the code and hardcode one of the theme names, e.g. oxygen, into the constructor, it then doesn't error. 

I think it might be related to the `$template` variable passed here:

https://github.com/mautic/mautic/blob/37ed5ee87900522c888b09ed3857ad0452fb33df/app/bundles/EmailBundle/Controller/PublicController.php#L394

but I'm not really sure, but I'm sure someone who is more familiar with the code base will know straight away.

| Q   | A
| --- | ---
| Mautic version | 3.2.2
| PHP version | 7.3.20
| Browser | Chrome

### Steps to reproduce
1. Click the unsubscribe link in an email
2. Click the resubscribe link on the unsubscribe message page.
 
### Log errors
```
[2021-01-25 09:57:03] mautic.CRITICAL: Uncaught PHP Exception Mautic\CoreBundle\Exception\BadConfigurationException: " is missing a required config file" at /var/www/html/app/bundles/CoreBundle/Templating/Helper/ThemeHelper.php line 64 {"exception":"[object] (Mautic\\CoreBundle\\Exception\\BadConfigurationException(code: 0):  is missing a required config file at /var/www/html/app/bundles/CoreBundle/Templating/Helper/ThemeHelper.php:64)"} []
```

**Comment by RCheesley** [comment]
Hi @andrew-dixon and thanks for flagging this up and looking into what might be the problem.

Would you be up for looking into making a PR to address the issue?

I'd also ask you to check on 3.2.5 (you should update as that version is [vulnerable to attack](https://www.mautic.org/blog/community/security-release-all-versions-mautic-prior-2-16-5-and-3-2-4)).

**Comment by andrew-dixon** [comment]
@RCheesley I really don't know either the Mautic codebase or PHP well enough to attempt a fix.

With regards to 3.2.5, yes the error still exists there as well.

**Comment by RCheesley** [comment]
OK thanks for confirming! Hopefully we can get someone to take a look and resolve the issue!

**Comment by npracht** [comment]
Hi @andrew-dixon did you have time to have a look at this ?

**Comment by andrew-dixon** [comment]
@npracht See my previous answer https://github.com/mautic/mautic/issues/9624#issuecomment-778608447 😄

**Comment by npracht** [comment]
Oh sorry i misunderstood ! <3

**Comment by alanhartless** [comment]
@andrew-dixon Does the Email itself still exist in Mautic? Does the template originally used by the email still exist in Mautic? 

Is there a full trace by chance for the exception in your log? 

Does it happen for any email sent from Mautic (campaign, segment email/broadcast/blast, etc)? 

I wasn't able to reproduce this.

**Comment by andrew-dixon** [comment]
@alanhartless Yes, both the emails and template still exist and it happens for all types of email. The "theme" used for the email isn't the same theme as the email, as the emails use a custom theme that is email only, so maybe it is related to that? The theme used for the unsubscribe page is one of the built-in theme, as per the details on the forum post, linked in my original posting.

**Comment by andrew-dixon** [comment]
@alanhartless Sorry, forgot to say, the only error message I can see in any logs is the one posts above.
