### ISSUE TITLE
Amazon SES Max Send Rate not supported.

### ISSUE THREAD

**Issue by jurczykpawel** [mautic/mautic#9627]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Emails send via Amazon SES API are not properly throttled which causes that some contacts do not receive messages.
I added my own email address to segment and I send segment email. I did not get the message, so I did some investigation.

Mautic shows that all emails were sent correctly while in SES dashboard I see that less than 50% of messages were processed.

| Mautic | SES
| --- | ---
| ![image](https://user-images.githubusercontent.com/25389342/106138342-4f50f500-616c-11eb-9e0f-da9b1b00eae1.png) | ![image](https://user-images.githubusercontent.com/25389342/106138390-5f68d480-616c-11eb-96ae-833572c78a69.png)

I suppose that this might be a problem how Max Send Rate is handled. 
As far as I understand in AmazonApiTransport.php `MaxSendRate` option is taken from Amazon account and its value is used as `concurrency` parameter in `CommandPool` config. The value is correct (in my case it is 14 emails/second).
I think the problem is that, as described in CommandPool.php, this value is used for limiting the _number of commands to execute concurrently_, but it is not equal to a number of emails sent per second. In case of commands are executed fast there is a chance that MaxSendRate is exceeded.

Also, I did not find any option in Mautic to configure the limit of emails sent per second. I know that it is possible to set Quota but this is related to the cron settings and I don't want to run `mautic:broadcasts:send` each second, all the time.

| Q   | A
| --- | ---
| Mautic version | v3.2.5 
| PHP version | 7.3.23
| Browser | N/A

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Paging @mabumusa1 @Wise-Gorilla as our resident SES experts! Thanks for reporting this.

**Comment by mabumusa1** [comment]
@pavvel11 this issue you should be solved by this PR https://github.com/mautic/mautic/pull/9735

**Comment by ivanmonteiro** [comment]
Sorry to comment on a closed issue, but is there any work-around?

**Comment by dsp76** [comment]
This should not go stale... Amazon SES is a primary service for mautic, it should not run into trouble with a fast server sending faster than the API limit allows. There is currently no way to find out, which mails have dropped from the sending.

**Comment by mabumusa1** [comment]
We are working on a migration from swiftmailer to symphony mailer on Mautic version 5.

We need testers, those who are interested, please let me know

**Comment by mabumusa1** [comment]
hello all,

Please checkout this PR https://github.com/mautic/mautic/pull/10742#issuecomment-1054681380

We are changing the whole game, we count your support to get feedback and comments on this PR for Mautic5

**Comment by jos0405** [comment]
I closed this bug as M5 will be moving to a direction making this irrelevant. If you don't agree plz reopen it.

**Comment by jurczykpawel** [comment]
@jos0405 could you shed some light on what will be changed and how it will be resolved in M5?
