### ISSUE TITLE
Can't disable trackable URLs in SMS when not using Twilio

### ISSUE THREAD

**Issue by anki630** [mautic/mautic#9629]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I am using another SMS integration plugin (not Twilio) to send SMS.
All URLs in the text message will convert into trackable URLs automatically.
And then the URLs become too long to insert into one SMS message.
So the word count always exceeds the limit of one SMS.
I can't disable SMS (Text messages) trackable URLs.
The only way to disable this function is to enable the Twilio plugin and then enter the login info so that you can disable this function.
The setting shouldn't tie into the Twilio plugin.

| Q   | A
| --- | ---
| Mautic version | v3.2.4
| PHP version | 7.3.25
| Browser | Chrome 88.0.4324.96

### Steps to reproduce
1. register a Twilio account
2. enable Twilio plugin
2. fill in the Twilio login info
3. then you can only disable the trackable URLs function here!

https://github.com/mautic/mautic/blob/features/app/bundles/SmsBundle/Helper/SmsHelper.php

line 114:
```
public function getDisableTrackableUrls()
    {
        $integration = $this->integrationHelper->getIntegrationObject('Twilio');
        $settings    = $integration->getIntegrationSettings()->getFeatureSettings();

        return !empty($settings['disable_trackable_urls']) ? true : false;
    }
}
```

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for raising this issue @anki630 - I have asked @mohit-rocks to take a look at this. Maybe you might consider taking a look at making a PR to have this be platform-agnostic?

**Comment by luchaninov** [comment]
Still not working
