### ISSUE TITLE
Campaign doesn't publish at all when setting specific date/time

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#9632]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Setting a campaign to UNPUBLISH at a specific date/time does work.
However...
Setting a campaign to PUBLISH at a certain date/time does NOT work.

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1. Create campaign
2. Set future publishing date/time
3. Notice that it doesn't publish at all at specified date/time
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by jurczykpawel** [comment]
I think this is not a bug.
Campaign should be published manually even if you set date/time. In such a case, the campaign should have Pending status, and next should be automatically changed into Published at specified date and time.

**Comment by omert37** [comment]
You're right. Woops!
