### ISSUE TITLE
Going into segment editing VERY SLOW for large databases

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#9634]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This is a long-standing issue that I'm sure many users have encountered.
Going in to try and edit segments is VERY SLOW (takes well over 5 minutes to enter the segment editing screen).

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1. Load 700K contacts into MAUTIC system
2. Create multiple segments consisting of 50K contacts each
3.  In addition, create a segment consisting of at least 6 of the previously created segments.
4.  Wait for segments to populate
5.  Try to click on one of the segments in order to edit it. Notice the length of time it takes.
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there!  Thanks for reporting this, we are doing a lot of work at present on scalability so this could well be something we're already working on.

Can you please share the filters that you are using in the segments you mention?
