### ISSUE TITLE
Reports link to contact edit page instead of view

### ISSUE THREAD

**Issue by andrew-dixon** [mautic/mautic#9635]
## Bug Description
On reports, if you include the "Contact ID" as a field it is clickable on the report, but instead of taking you to "view the user" as it does from other locations, e.g. the Contacts page, it takes you to "edit the user". This isn't a big deal until you have a user who only has "view" permissions for contacts.

| Q   | A
| --- | ---
| Mautic version | 3.2.2
| PHP version | 7.3.20
| Browser | Any

### Steps to reproduce
1. Create a report that includes the "Contact ID" column.
2. View the report and click a Contact ID in the report. This will take you to `contacts/edit/[ID]` instead of `contacts/view/[ID]`

**Comment by RCheesley** [comment]
Hi Andrew, thanks for reporting this. Indeed it probably should be a view rather than edit.

Would you be up for making a PR to update the link from edit to view?  Hopefully it should be a small fix to do! Let us know if you need a hand getting started!
