### ISSUE TITLE
Relative dates in segments don't work

### ISSUE THREAD

**Issue by directpromo** [mautic/mautic#9636]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
If you specify "10 days ago" in the filter for a field with the date type, the exact date will be saved instead of the relative date.

At the same time, the filter by date with the value "today" or" yesterday" works correctly.

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.2

### Steps to reproduce
1. Create a segment with a filter by the relative date "2 days ago" or "3 months ago" , etc.
2. Save and then go to edit the segment. Instead of a relative date, there will be an exact date and even a time
3. At first, the segment will work, but as soon as more than a relative date passes in time, contacts with an outdated date will not be deleted from the segment.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, thanks for taking the time to report this.

Does the same happen if you use the numerical references rather than the phrases?

**Comment by directpromo** [comment]
If I write "-20 days" or "-2 months", then it works

**Comment by RCheesley** [comment]
OK thanks for checking! I would suggest using that as a workaround while we find someone to look into this :)

**Comment by directpromo** [comment]
Got it. 
Now I checked, dates like "last day of previous month" do not work either. 
I don't know what to replace it with :(

**Comment by RCheesley** [comment]
Looks like we have a fix from @shinde-rahul #9678 - please take a look @directpromo !

**Comment by directpromo** [comment]
Thank you. Hopefully it will be included in the release.

**Comment by RCheesley** [comment]
It will need to be tested, you can help with that :) Once tested it should be feasible for the 3.3.1 release

**Comment by directpromo** [comment]
I would help, but I don't know how to test the code itself. Only as a user can I create a segment, etc. 

If necessary, as a user, remind me how can I run a test instance of Mautic with this folder?

**Comment by RCheesley** [comment]
Sure - it is a good one to test on MautiBox. Follow the instructions here: https://github.com/mautic/mautic/pull/9678#issue-574194355 - click through the link to open MautiBox and it will spin up a Mautic instance for you to test with the PR applied. Usual credentials of admin/mautic.

Report back if successful by going here: https://github.com/mautic/mautic/pull/9678/files and clicking the green 'review changes' option and leave a note.

**Comment by RCheesley** [comment]
(user tests are required, in addition to code review, and are super important! We would really value your help!)

**Comment by directpromo** [comment]
> Sure - it is a good one to test on MautiBox. Follow the instructions here: [#9678 (comment)](https://github.com/mautic/mautic/pull/9678#issue-574194355) - click through the link to open MautiBox and it will spin up a Mautic instance for you to test with the PR applied. Usual credentials of admin/mautic.
> 
> Report back if successful by going here: https://github.com/mautic/mautic/pull/9678/files and clicking the green 'review changes' option and leave a note.

I created the segment manually and tried the "1 minute ago" filter. It works with "greater" and "less".

Perhaps this is not enough, because all contacts with the same date and time or with an empty value.
The test needs different dates.

How do I generate contacts with different dates in the fields? Or is it not required and a test with the "1 minute ago" filter is enough?

**Comment by RCheesley** [comment]
It should have about 50 contacts in the instance - so you can use any of them to test with - maybe try with a custom field as a date? :)

**Comment by directpromo** [comment]
> It should have about 50 contacts in the instance - so you can use any of them to test

Yes, but all 50 have the same creation date to the minute. I won't be able to check different filters by date this way. Other core date fields are empty



> maybe try with a custom field as a date?

I can create a field, yes. I will have to manually enter different dates. 

Well, I'll try. 

I thought there was a way to generate it automatically )
