### ISSUE TITLE
Wrong timestamp for asset downloaded in contact event log

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#9638]
## Bug Description
Looks like "asset download" timestamp in event log is wrong by 24h. The asset download report shows the correct date "yesterday, 10:08 am" ... however the event log within the contact shows "Today, 10:08 am" (see screenshot).

The order of events don't make any sense:
* visiting the landing page yesterday
* downloading today
* moving into the related segment yesterday

Whats wrong here?
The issue is related to https://github.com/mautic/mautic/issues/9152 as well.

![image](https://user-images.githubusercontent.com/1241376/106819182-b80f0480-6679-11eb-9bc5-6b7a39817de2.png)

| Q   | A
| --- | ---
| Mautic version | 3.2.4 (and many more before)
| PHP version | 7.3
| Browser | any

### Steps to reproduce
1. create a contact that downloads an asset, linked by e.g. mail
2. see log
 
### Log errors
no errors logged

**Comment by RCheesley** [comment]
Thanks for flagging up this issue, so my understanding is that the asset download time is reporting as 24 hours late from what it should be (today rather than yesterday) - but only in the contact activity log and not in the report. Is that correct?

**Comment by dsp76** [comment]
Correct - it only happens, when the download really was yesterday. It works fine, if it was today - or has a date and no relative dates anymore. Is shows "today" when it was yesterday. Tested and confirmed the bug with en-uk, en-us and de-de.

Reports always have absolute date/timestamps. But the activity log has no real timestamp for today and yesterday.
