### ISSUE TITLE
Contact details doesnt work in some contacts

### ISSUE THREAD

**Issue by MaldonDev** [mautic/mautic#9643]
Mautic Version: 2,14.2
PHP Versión: 7.1.33 

I have a weird error, when i click in a contact to see its details, depends on the contact, its load correctly  or i get a 500 screen error. 

In the log appear nothing, and the contact that present that error get the same error when click on "unsuscribe", a 500 error ( but the contact  unsuscribe correctly on mautic.

I tried to change the PHP versión and the error still happening, i dont know what to do. Its happen to multitude of contacts, news and old, and its totally random. 

Thes logs doesnt show anithing, ¿any suggestion?

Thanks :)

**Comment by RCheesley** [comment]
Hi there, as this relates to a version of Mautic that is [no longer supported](https://www.mautic.org/blog/community/goodbye-mautic-2-its-been-good-know-you) this issue will be closed. Please update your instance as the version that you are running is [vulnerable to attack](https://www.mautic.org/blog/community/security-release-all-versions-mautic-prior-2-16-5-and-3-2-4).

If you require support please post in https://forum.mautic.org/c/support.
