### ISSUE TITLE
AWS SES Transport fails on sending a batch immediately 

### ISSUE THREAD

**Issue by mabumusa1** [mautic/mautic#9644]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.4
| Browser | 

### Steps to reproduce
1. Make sure you are sending using immediate mode 
2. Create a segment with more than 50 contacts
3. Send an email to that segment
4. The email will be failed to send
5. There is a related error for throttling (logs below) 
 
### Log errors
```
[2021-02-03 08:01:33] mautic.ERROR: [MAIL ERROR] Token amount (51) is larger than the capacity (3). (send); {"exception":"[object] (Swift_TransportException(code: 0): Token amount (51) is larger than the capacity (3). at app/bundles/EmailBundle/Swiftmailer/Transport/AbstractTokenArrayTransport.php:300)"} []

[2021-02-05 08:25:00] mautic.ERROR: [MAIL ERROR] Expected response code 250 but got code "454", with message "454 Throttling failure: Maximum sending rate exceeded. " (send); email@domain.com {"exception":"[object] (Swift_TransportException(code: 454): Expected response code 250 but got code \"454\", with message \"454 Throttling failure: Maximum sending rate exceeded.\r\n\" at /home/smartconnectamba/public_html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457)"} []
```

### Solution to be implemented must look into the following lines: 
```
        if (!$this->started) {
            $this->amazonClient  = $this->createAmazonClient();

            $account             = $this->amazonClient->getAccount();
            $emailQuotaRemaining = $account->get('SendQuota')['Max24HourSend'] - $account->get('SendQuota')['SentLast24Hours'];

            if (!$account->get('SendingEnabled')) {
                $this->logger->error('Your AWS SES is not enabled for sending');
                throw new \Exception('Your AWS SES is not enabled for sending');
            }

            if (!$account->get('ProductionAccessEnabled')) {
                $this->logger->info('Your AWS SES is in sandbox mode, consider moving it to production state');
            }

            if ($emailQuotaRemaining <= 0) {
                $this->logger->error('Your AWS SES quota is currently exceeded, used '.$account->get('SentLast24Hours').' of '.$account->get('Max24HourSend'));
                throw new \Exception('Your AWS SES quota is currently exceeded');
            }

            $this->concurrency   = floor($account->get('SendQuota')['MaxSendRate']);

            $this->started = true;
        }
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for flagging up this issue @mabumusa1 - are you able to work on this or should we find someone to fix this?

**Comment by mabumusa1** [comment]
@RCheesley I am working on a solution for it.

**Comment by RCheesley** [comment]
Amazing - thanks for letting us know!

**Comment by mabumusa1** [comment]
> Thanks for flagging up this issue @mabumusa1 - are you able to work on this or should we find someone to fix this?

The fix is on the attached PR
