### ISSUE TITLE
Mail Service Configure using API !

### ISSUE THREAD

**Issue by 3birds-ronak** [mautic/mautic#9645]
We are using mautic 3.2.0 version and we need to configure mail service using API.
Any feature available for configure mail service using api?

**Comment by RCheesley** [comment]
Yes, there are multiple email transports available including Amazon SES. - if you need to write your own please make reference to them and use developer.mautic.org to take a look at our developer docs.

Please post your questions over at https://forum.mautic.org/c/development as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
