### ISSUE TITLE
Email Templates Provided Hang The System

### ISSUE THREAD

**Issue by Mer-idium** [mautic/mautic#9646]
Hi all,

Mautic Version: 3.2.5
PHP Version: 7.4.14
Database: Maria DB 10.2.36
Browsers: Chrome and Edge

When I create an email using the templates provided within the Channels > Emails section, on clicking Apply or Save & Close the system hangs and it never creates the email, I would need to refresh before having control. This does not occur for every template, so far I have identified that the Vibrant, Aurora and Sparse templates work without issue but everything else fails. Including the Blank and Code Mode templates.

Steps to reproduce
1. Create new template email within Channels > Emails
2. Select any template **apart** from Vibrant, Aurora and Sparse
3. Modify the template using the builder and select Apply or Safe & Close
4. System hangs and email template does not get created
 
Log errors
For the webpage:
`https://domain/s/emails/new?mauticUserLastActive=39&mauticLastNotificationId=403` on failure
`https://domain/s/emails/edit/8` on success using Aurora as template

For PHP
`mautic.NOTICE: PHP Notice - Trying to access array offset on value of type null - in file /home/gotomark/public_html/app/bundles/EmailBundle/Views/FormTheme/Email/_emailform_dynamicContent_entry_filters_entry_filters_entry_widget.html.php - at line 14 {"mauticTemplateVars":{"app":"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\GlobalVariables: {})","value":null,"attr":{"class":"form-control"},"form":"[object] (Symfony\\Component\\Form\\FormView: null)","id":"emailform_dynamicContent_0_filters_0_filters___name__","name":"__name__","full_name":"emailform[dynamicContent][0][filters][0][filters][__name__]","disabled":false,"label":false,"label_format":null,"multipart":false,"block_prefixes":["form","dynamic_content_filter_entry_filters","_emailform_dynamicContent_entry_filters_entry_filters_entry"],"unique_block_prefix":"_emailform_dynamicContent_entry_filters_entry_filters_entry","translation_domain":null,"cache_key":"_emailform_dynamicContent_entry_filters_entry_filters_entry_dynamic_content_filter_entry_filters","errors":"[object] (Symfony\\Component\\Form\\FormErrorIterator: )","valid":true,"data":null,"required":true,"size":null,"label_attr":[],"compound":true,"method":"POST","action":"","submitted":false,"mauticContent":"email","mauticTemplate":"MauticEmailBundle:FormTheme\\Email:_emailform_dynamicContent_entry_filters_entry_filters_entry_widget.html.php","view":"[object] (Mautic\\CoreBundle\\Templating\\Engine\\PhpEngine: {})"},"app":"[object] (Symfony\\Bundle\\FrameworkBundle\\Templating\\GlobalVariables: {})","value":null,"attr":{"class":"form-control"},"form":"[object] (Symfony\\Component\\Form\\FormView: null)","id":"emailform_dynamicContent_0_filters_0_filters___name__","name":"__name__","full_name":"emailform[dynamicContent][0][filters][0][filters][__name__]","disabled":false,"label":false,"label_format":null,"multipart":false,"block_prefixes":["form","dynamic_content_filter_entry_filters","_emailform_dynamicContent_entry_filters_entry_filters_entry"],"unique_block_prefix":"_emailform_dynamicContent_entry_filters_entry_filters_entry","translation_domain":null,"cache_key":"_emailform_dynamicContent_entry_filters_entry_filters_entry_dynamic_content_filter_entry_filters","errors":"[object] (Symfony\\Component\\Form\\FormErrorIterator: )","valid":true,"data":null,"required":true,"size":null,"label_attr":[],"compound":true,"method":"POST","action":"","submitted":false,"mauticContent":"email","mauticTemplate":"MauticEmailBundle:FormTheme\\Email:_emailform_dynamicContent_entry_filters_entry_filters_entry_widget.html.php","view":"[object] (Mautic\\CoreBundle\\Templating\\Engine\\PhpEngine: {})","isPrototype":true,"filterType":"","filterGroup":""} []`

I have already:
- Cleared the cache
- Fixed database schema
- Checked ModSecurity on hosting provider
- Reuploaded the themes folder containing the templates using an older release

Thanks for the help

**Comment by RCheesley** [comment]
Thanks for reporting this and for explaining the specific themes where you are seeing the issue.

**Comment by Mer-idium** [comment]
Thanks @RCheesley is there anything I can do in the meantime to troubleshoot?

**Comment by RCheesley** [comment]
Are you using dynamic content in the emails at all?

**Comment by Mer-idium** [comment]
Not at the moment, even when i add a single character to the basic template it will hang.

**Comment by RCheesley** [comment]
@LPCoderAu I have tested this in 3.2.5 and I am unable to reproduce it. I would expect that this is probably something to do with your hosting environment rather than with Mautic.

For that reason please make a post over at https://forum.mautic.org/c/support with the details you have posted in the forum and the Community will be able to help you with troubleshooting.

**Comment by jos0405** [comment]
Hi @LPCoderAu, do you use Grammarly?

**Comment by adonaicruz** [comment]
the same problem occurred to me, with the same configuration
