### ISSUE TITLE
Add reserved keywords to create custom fields alias

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#9647]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
- [x] contact_id
- [x] company_id
- [x] source
- [x] campaign

If you create custom field with alias `campaign` then you're not able to use segment filter campaign membership. This filter use same naming 'campaign' and If you try use campaign membership filter, query is made  as custom field.

It would be good to make reserved keywords during the alias already exists validation for custom field. This could be provide by dispatcher to allow plugin extend that list.

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
The issue also come If user make custom field `company_id` 
In this case company selector on contact edit page does not work properly

**Comment by npracht** [comment]
This is still an issue

**Comment by kuzmany** [comment]
This was fixed times ago by this PR https://github.com/mautic/mautic/pull/5838
But looks like not work anymore.

**Comment by kuzmany** [comment]
Fixed by https://github.com/mautic/mautic/pull/10224

**Comment by npracht** [comment]
Same with `source`

**Comment by kuzmany** [comment]
@npracht even with this https://github.com/mautic/mautic/pull/10224 ?

**Comment by npracht** [comment]
@kuzmany maybe you can fix the style issue on @Damzoneuh PR and extend to the 2 other reserved keywords ?

**Comment by kuzmany** [comment]
@npracht source is covered by default 

![image](https://user-images.githubusercontent.com/462477/147491048-3bf77b47-3f60-4c7e-bbb9-e3007febd237.png)

**Comment by jos0405** [comment]
Seems to be fixed in 4.2+, so I'll close it. Yell and reopen if I'm mistaken.

**Comment by saidhasyim** [comment]
> Seems to be fixed in 4.2+, so I'll close it. Yell and reopen if I'm mistaken.

Still happening on "source"
