### ISSUE TITLE
email UTM tags feature append extra "?" mark instead of "&" when using URLs with query string

### ISSUE THREAD

**Issue by anki630** [mautic/mautic#9655]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When inserting a URL with a query string, the email UTM tags feature will append a query string start with "?" instead of "&".
For example, when I have a coupon code that I want to send to my customers, the URL will be the following:
https://www.my-domain.com/?coupon_code=vip-2021
When I insert the UTM tags in the email setting field:
Campaign source: newsletter
Campaign medium: edm
Campaign name: vip-campaign
Campaign content: v1

Then the URL will become:
https://www.my-domain.com/?coupon_code=vip-2021?utm_medium=edm&utm_campaign=vip-campaign&utm_content=v1
instead of
https://www.my-domain.com/?coupon_code=vip-2021&utm_medium=edm&utm_campaign=vip-campaign&utm_content=v1

| Q   | A
| --- | ---
| Mautic version | v3.2.5
| PHP version | 7.3.25
| Browser | Chrome 88.0.4324.150

### Steps to reproduce
1. create an email with UTM tags
2. edit the email and add a button
3. set the button URL using a contact field variable with a URL that contains a query string
4. test this email with a real campaign
5. there are 2 "?" mark in the button URL
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, this sounds remarkably similar to this issue: https://github.com/mautic/mautic/issues/9536

The resolution to that was:

> I figured it out now. We used {contactfield=mwb_abncart_url} as URL and it seems to replace the placeholder after Mautic added UTM parameters so Mautic didn't detect the "?".

Could this be the same issue?

**Comment by anki630** [comment]
> Hi there, this sounds remarkably similar to this issue: #9536
> 
> The resolution to that was:
> 
> > I figured it out now. We used {contactfield=mwb_abncart_url} as URL and it seems to replace the placeholder after Mautic added UTM parameters so Mautic didn't detect the "?".
> 
> Could this be the same issue?

Yes, this is the same issue.

**Comment by RCheesley** [comment]
OK, I'd suggest seeing if you can get in touch with the team at MWB and ask what their suggestions are for a workaround!

**Comment by anki630** [comment]
> OK, I'd suggest seeing if you can get in touch with the team at MWB and ask what their suggestions are for a workaround!

Not only for MWB.
As I mentioned, URLs with query string could have the same issue.
For example, there is a standard feature in WooCommerce, when people didn't pay for their order, there will be a unique URL for them to finish their payment. Like this:
https://yourdomain.com/checkout/order-pay/42127/?pay_for_order=true&key=wc_order_3bI0pzxv0NDLJ

**Comment by valmedia** [comment]
> OK, I'd suggest seeing if you can get in touch with the team at MWB and ask what their suggestions are for a workaround!

It seems like I encounter another problem with using link tracking with the email service provider.

So I went through the mautic code and it seems to be Mautic is adding the UTM tags to {contactfield=mwb_abncart_url} before replacing the dynamic content. Mautic should replace the dynamic content before adding UTM tags.

Another issue is that clicks will not be"tracked because the "dynamic content" placeholder is changed to a URL so it is different than what's tracked.
