### ISSUE TITLE
Link disappears in the email

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#966]
Hi guys,

I dunno why, but there is a small interpretation of the code by the email builder.
I add the following code:
`<td align="center" style="text-align:center;display: block;" valign="middle">
<a href="http://test.com">
<button style="height: 2.57em;padding: 0 1.42em;border: 0;border-radius: 999px;text-transform: uppercase;font-size: 14px;line-height: 2.57em;color: #fff;background-image: url('');" type="button">
<b>Je parraine mes amis !</b>
</button>
</a>
</td>`

And when i receive the email, the link on the button has disappeared, and the link is not in the email builder anymore:
`<td align="center" style="text-align:center;display: block;" valign="middle">
<button style="height: 2.57em;padding: 0 1.42em;border: 0;border-radius: 999px;text-transform: uppercase;font-size: 14px;line-height: 2.57em;color: #fff;background-image: url('https://www.charlesviancin.com/wp-content/themes/charlesviancincorporate/assets/images/button-texture.jpg');" type="button">
<b>Je parraine mes amis !</b>
</button>
</td>`

Tell me if i'm doing something wrong.
Thanks,

N.

**Comment by escopecz** [comment]
The builder uses (CK editor)[http://ckeditor.com/] and it sometimes strips some parts of HTML.

But in your case, is there some reason why to have a button in a link? I've never seen such thing. Use just the link and style it like a button.

**Comment by npracht** [comment]
Hi,

I could do that but you may know that styling a link with display block for instance is very tricky with the client email interpretation (outlook, gmail & stuff).

I'll try different stuff.

N.
