### ISSUE TITLE
Option to add  points manually

### ISSUE THREAD

**Issue by Jakub087** [mautic/mautic#967]
Hello,

I miss the option to add points to leads manually. I would really like to see it in new version :). Or did I overlook this option somewhere?

Thanks, Jacob

**Comment by trops** [comment]
I second that! I cannot use points at all unless this is implemented in the API. Im using mautic to monitor an iPhone app...everything is awesome but wanted to manage events, etc, based on points...need this in the API! :-)

**Comment by khairulazan** [comment]
I also to have this feature available. Sometimes my customers interact with my company offline like attend my training and buying product. I would like to add some points to them.

**Comment by samtuke** [comment]
+1

**Comment by marekliebl** [comment]
+1

**Comment by jkuchar** [comment]
+1

**Comment by LAN-Laurene** [comment]
Hello,
Webmecanik is working on this feature, and we will do a pull request in fews days.
We will add API call with setPointTolead, addPointToLead and subtractPointToLead

**Comment by samtuke** [comment]
Fantastic news - thanks for the update.

**Comment by trops** [comment]
Truly thanking you!!!

John P. Giatropoulos
Founder and CEO, swingbot.com
http://www.swingbot.com

**Comment by jkuchar** [comment]
Awesome news! :)

**Comment by LAN-Laurene** [comment]
Hello,

We want to add through the API a function to apply an existing point action on a lead.

## Tech info :
### API :

- api librairie =>  `apply_action(lead_id, action_id) ;`
- Add route in `config.php` (PointBundle/config) with `path = /points/action/{id}/lead/{leadid}` and `controller = MauticPointBundle:Api\PointApi :apply_action`
 - create function `PointApi.php→ apply_action(lead_id, action_id)`

### Mautic :
- Add type :  `api.call`
- create class `ApiBundle/EventListener/Pointsubscribe.php`
 - create function `onPointBuild(PointBuilderEvent $event)`
  - callback : `ApiBundle/Helper/PointEventHelper-> validateApicall(...)`
- create class `ApiBundle/Helper/PointEventHelper.php`
 - create function `validateApiCall()`
- add in `ApiBundle/EventListener/Pointsubscribe.php`
 - create function `onApiCall(ApiEvent $e)` :
  - `$this→factory→getmodel('point')→triggerAction('api.call', $e→getApi());`
- create class `ApiBundle/Event /ApiEvent (extends CommonEvent)`


@alanhartless @escopecz : Do you have technical recommendations ?

**Comment by escopecz** [comment]
I would create a new EventBundle for this. It would also show the events at the lead detail timelines, it could trigger actions at campaign events and so on. The FormBundle has the similar functionality so it would could be copied, renamed and modified.

Also, I'd like the option to create/use the events the same as Google Analytics can. From public requests. For example if I'd visited this URL:
```
https://mymautic.com/event/[event_name]?[key1]=[value1]&...
```
_values in [...] are variables_

This would create the event if it does not exist and tracked the additional data.

Then a small JS library could be developed to push the events to Mautic on user actions similarly [how GA does it](https://developers.google.com/analytics/devguides/collection/gajs/eventTrackerGuide#intro):
```
_trackEvent(category, action, opt_label, opt_value, opt_noninteraction)
```

At least that is the idea in my head...

**Comment by LAN-Laurene** [comment]
Hello, 

We suggest adding the following functions:

1. `set` -> Overwrite the score (you can define what will be noted in the lead's history)
2. `add` -> add points to the score (you can define what will be noted in the lead's history)
3. `substract` -> substract points to the score (you can define what will be noted in the lead's history)
4. `apply_rule` -> applies a existing score rule to the lead (this rule must be of type "api.call")

**Comment by archangel2106** [comment]
This would be great to have, many people in sales have a separate conversation or note that helps them keep track of the "emotion" aspect of sales. Thanks!

**Comment by vdittgen** [comment]
+1

**Comment by seologico** [comment]
It would be an appreciated feature, many thanks.

Diego Gualdoni
http://www.seologico.it

**Comment by Directinvent** [comment]
+1

**Comment by Getron** [comment]
It would be great, but, maybe, somehow, to be able to see in admin that it was added manually, separated, or "Automated" - "Manually" Points.

**Comment by merlin0** [comment]
+1

**Comment by Arnevv** [comment]
+1

**Comment by zenzozen** [comment]
+1

**Comment by cpot** [comment]
+1

**Comment by agallewale** [comment]
Hi, Just wondering if there is any update on this?

**Comment by npracht** [comment]
Thanks to https://github.com/mautic/mautic/issues/3858 you can modify points manually.

**Comment by agallewale** [comment]
Wow. Very good thanks for your prompt reply. Looking forward to 2.9
