### ISSUE TITLE
Going into companies editing or view VERY SLOW for large number of data

### ISSUE THREAD

**Issue by 3birds-ronak** [mautic/mautic#9674]
inside companies tab, open any company to view contact details and chart data loading issue 

## Bug Description
In companies view page execution much loading time issue that I'm sure in company view page charts takes more time to load when in charts get a count of engagements and points of contact's lead_id. Because it’s used loop for every contact. if the company has only 3-10 contacts but it takes more time. Not 10k or more contacts.
In Mautic code, I have debugged but use the old method for displaying contact details with a chart and also use looping for contact data view or chart.
also share some path location of code and method name:
mautic/app/bundles/LeadBundle/Controller/LeadDetailsTrait.php

![mautic-2021](https://user-images.githubusercontent.com/60380658/107942332-16f54780-6fb1-11eb-9293-c7ebfbbddec1.jpg)

| Q   | A
| --- | ---
| Mautic version |  3.2.0
| PHP version | 7.2/7.3
| Browser |  Chrome

### Steps to reproduce
1. Go to the companies list page
2. Click on Company name and redirect on the view page
3. Charts calculate contacts engagement, points, and takes more time in looping. The calculation is possible without looping for reducing time to execute the company view page
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for raising this, the company view feature was only added in 3.2 so it is a relatively new feature.

We would absolutely welcome some optimisation work if you would be up for making a PR to improve some of the queries - shout if you need any help with that!

**Comment by RCheesley** [comment]
Also pinging @alfredoct96 who contributed this feature originally!

**Comment by 3birds-ronak** [comment]
Thanks for the reply and I hope, @alfredoct96 will resolve the issue asap.
Please let me know when this issue is fixed.

**Comment by alfredoct96** [comment]
I'll try to fix it
