### ISSUE TITLE
Email theme upload is expecting email.html.twig but this is not present in MJML themes

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#9676]
## Bug Description
When trying to install a new MJML theme with the upload option in the Theme section we get the following error:

The theme you tried to install is missing the following required files and thus could not be installed: html/email.html.twig

An MJML theme will include an email.mjml.twig file rather than email.html.twig. We should probably add a check that looks for either?

| Q   | A
| --- | ---
| Mautic version | 3.3 Release Candidate 
| PHP version | 7.4
| Browser | Chrome

### Steps to reproduce
1. Try to install an MJML Theme eg [this blank theme](https://github.com/Webmecanik/plugin-grapesjs-builder/files/4757520/blank_mjml.zip)
2. Notice the issue when you try to upload it via the Themes UI

**Comment by luizeof** [comment]
I can't send an MJML theme in 3.2.5 and the problem persists in 3.3.0

**Comment by kuzmany** [comment]
I fixed it by this PR https://github.com/mautic/plugin-grapesjs-builder/pull/74

**Comment by RCheesley** [comment]
Closing this issue as the fixing PR has been merged.

**Comment by andres-asm** [comment]
Weird, we're on 4.0 and we are still seeing this problem...

**Comment by kuzmany** [comment]
@fr500 in Mautic 4 you have to put MJML template to  `email.html.twig`. 

`email.mjml.twig` is not supported anymore

**Comment by dsp76** [comment]
@kuzmany when we tried this, we were able to upload the theme ... but it didn't work properly with the editor. It didn't load the grapeJS. When we uploaded the unchanged theme (email.mjml.twig not renamed) - it worked as expected. This is on version 4.4.

Are you sure that the proposed way is the way to go? It seems not to work...
