### ISSUE TITLE
bin/console doctrine:schema:update --force command results in error

### ISSUE THREAD

**Issue by surefooted** [mautic/mautic#9684]
**Description** 

I have been trying to install a plugin to integrate Mautic with SuiteCRM. The plugin is unable to communicate with SuiteCRM. Their support points out that we have a incorrect built Mautic database and missing several columns. We had upgraded from v 2.6.1 to v 3.2.5 recently but Mautic installation was working fine. They gave us a series of commands which went well till we came to bin/console doctrine:schema:update --force. This gave the following error.

================================================

Updating database schema...

In AbstractMySQLDriver.php line 106:

  An exception occurred while executing 'ALTER TABLE oauth2_accesstokens CHANGE client_id client_id INT UNSIGNED NOT NULL, CHANGE user_id user_id INT UNSIGNED NOT NULL, CHANGE token token VARCHAR(191) NOT NULL, CHANGE expires_at expir
  es_at BIGINT DEFAULT NULL, CHANGE scope scope VARCHAR(191) DEFAULT NULL':

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key constraint 'FK_3A18CA5A19EB6921'

In PDOConnection.php line 80:

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key constraint 'FK_3A18CA5A19EB6921'

In PDOConnection.php line 75:

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'client_id': used in a foreign key constraint 'FK_3A18CA5A19EB6921'

===================================
Do not know how to resolve this. Please help.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by escopecz** [comment]
Please do not use this command. Especially not on production Mautic instance. See https://github.com/mautic/mautic/issues/11204#issuecomment-1161441244
