### ISSUE TITLE
Clicks registered in default UTC timestamp instead of local machine timezone?

### ISSUE THREAD

**Issue by omert37** [mautic/mautic#9696]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
My Linux machine is set for UTC+02:00
The PHP service is set for UTC+02:00
The MySQL service is set for UTC+02:00
Even my NginX service is set to UTC+02:00
And yet... it seems that MAUTIC is timestamping clicks at 13:00 instead of 15:00.
Can anybody verify for me if they are experiencing the same issue?

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.4
| Browser | 

### Steps to reproduce
1. Click campaign link
2. Check MySQL timstamp for link
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi @omert37 have you checked what timezone you have set in your Mautic config? That will determine the display within Mautic.

There are two places to check, the global config:

![screenshot-mautic32 ddev site-2021 02 26-15_03_16](https://user-images.githubusercontent.com/2930593/109316787-df558d80-7843-11eb-9e4e-345ef3b6090e.png)

and your user profile:

![screenshot-mautic32 ddev site-2021 02 26-15_03_36](https://user-images.githubusercontent.com/2930593/109316815-e7153200-7843-11eb-939c-cc66bb4ac80d.png)

**Comment by RCheesley** [comment]
@omert37 did this resolve the issue for you?

**Comment by omert37** [comment]
@RCheesley I already know about this. My system default has the correct timezone (UTC+2:00) and my personal user setting is set to the system default. Mautic is still stamping at UTC.

**Comment by RCheesley** [comment]
OK thanks for confirming that!
