### ISSUE TITLE
sms_pending:ID in search bar doesn’t work

### ISSUE THREAD

**Issue by nfakhour** [mautic/mautic#9697]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
when we have pending messages , if we search sms_pending:ID  there are no leads although we have "x pending" messages
<img width="445" alt="Capture d’écran 2021-02-16 à 15 16 56" src="https://user-images.githubusercontent.com/72491743/108483003-7e094980-729a-11eb-9584-2c9917cfe8d3.png">
<img width="1009" alt="Capture d’écran 2021-02-16 à 15 16 39" src="https://user-images.githubusercontent.com/72491743/108483070-94170a00-729a-11eb-8fa6-0400bce272d9.png">

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.3

### Steps to reproduce
1. Have pending Sms
2. click on pending or search sms_pending:ID
3. Once you click on it is searches sms_pending:ID
 
### Log errors
no log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for reporting this @nfakhour - would you be up for seeing if you could debug and maybe make a PR to address this?
