### ISSUE TITLE
TransportInterface::sendSms compatibility

### ISSUE THREAD

**Issue by vovchok** [mautic/mautic#9698]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

The `TransportInterface::sendSms` method doesn't have the `Stat` argument.

https://github.com/mautic/mautic/blob/1e4ec81d9e07a8a3d1f687d08e96bdd0e2a70135/app/bundles/SmsBundle/Sms/TransportInterface.php#L23

There are several method invocation that passing `Stat` object like third argument.

https://github.com/mautic/mautic/blob/1e4ec81d9e07a8a3d1f687d08e96bdd0e2a70135/app/bundles/SmsBundle/Model/SmsModel.php#L333

https://github.com/mautic/mautic/blob/1e4ec81d9e07a8a3d1f687d08e96bdd0e2a70135/app/bundles/SmsBundle/Sms/TransportChain.php#L97

| Q   | A
| --- | ---
| Mautic version | 3.2
| PHP version | 7.1
| Browser | any

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
@vovchok thanks for reporting this. Have you checked the behaviour continues in 3.3.1? 3.2 is a bit outdated now.  You will need to be using PHP 7.3 or above though, in order to test.

If you are up for is could you look at writing a bit more about why this is an issue (ie what is the consequence of the omission) and maybe consider making a PR to address it?

**Comment by vovchok** [comment]
Yes, it remains in 3.3. The Stat object passes like third argument and it could be useful in custom transport extension but the Transport interface declares only two arguments. Did you forget to extend the Transport interface with Stat argument?

**Comment by kuzmany** [comment]
@vovchok stat object was added later in my PR
Add it to TransportInterface would break few plugins what already exists, then I do not decide put it there. 
If you have time, feel free create PR with it for upcoming Mautic4 release
