### ISSUE TITLE
Pending emails

### ISSUE THREAD

**Issue by videfrancisco** [mautic/mautic#97]
Hello friends,

I installed mautic using mysqli everything correctly, create a list, then form page, then e-mail and after the campaign but when I create the campaign and set up to make submissions at intervals, all these emails are as pending and have to submit manually. The shipping should be automated?

**Comment by alanhartless** [comment]
Hi! 

I'm closing this in favor of the forum conversation at https://www.mautic.org/community/index.php/151-pending-emails.

Thanks!
Alan
