### ISSUE TITLE
mautic.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away"

### ISSUE THREAD

**Issue by matthiasexl** [mautic/mautic#9701]
Ubuntu 18.04.5 LTS
Plesk Obsidian Version 18.0.33
Maria DB 10.3.27, we connect to the DB via ‘db_driver’ => ‘pdo_mysql’
We tested on PHP 7.3.x and are now on PHP Version 7.4.15, We run on Apache FPM / not Nginx
Mautic v3.2.5 fresh install, only some testing accounts, test campaigns and test mails.

We followed the troubleshooting steps: https://docs.mautic.org/en/troubleshooting, cleared the cache and updated schema.

As soon as we click on Channels / Emails and try to delete any old email, we get this error (I replaced Path/privacy):

[2021-02-21 10:34:53] mautic.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" at /var/www/vhosts/PATH/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1354 {"exception":"[object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 2006 MySQL server has gone away at /var/www/vhosts/PATH/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1354)"} []

SQL is gone and restarts. We posted a support request here: https://forum.mautic.org/t/message-frequency-rule-and-email-delete-issue/18232 and here: https://forum.mautic.org/t/mysql-server-has-gone-away/10060/9

**Comment by mabumusa1** [comment]
@matthiasexl Thanks for submittin this issue, it is not an issue related to the code base of Mautic but rather the server capabilities you have. I think your database server is misconfigured or overloaded which makes it switch off or halt, so please check that.

I will close this issue since it is a support issue and you already started a ticket on the forums

**Comment by matthiasexl** [comment]
Thank you @mabumusa1 . I will continue to research in the forum. Could be the MariaDB Version too high?

**Comment by matthiasexl** [comment]
@mabumusa1 I was able to find the solution: 
The error was caused, as I had not installed a Cron Job " /bin/console mautic:broadcasts:send --channel=email"  yet.
This caused a pending email in the email that I tried to delete. This caused the fatal error of the DB.
After the Cron ran, the delete process worked fine.
