### ISSUE TITLE
Multiple value on List-Unsubscribe header

### ISSUE THREAD

**Issue by adirbnology** [mautic/mautic#9704]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Multiple value on List-Unsubscribe header
I found multiple value on List-Unsubscribe header in every email sent via Mautic if using the Monitored Inbox feature. 
this issue happens to me with amazon SES API. 

i have found #6339 that was closed long time ago but couldnt find any help there

this is critical issue as some email providers creating wrong unsubscription 

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.3.25
| Browser | firefox

### Steps to reproduce
1.  create a campaign with more than 1 receipt. 
2.  open the email received and check original message.
3. on the header u should find  List-Unsubscribe that would contain a list of email with the following structure: {monitored_email_name}+unsubscribe{tracking_hash}@{monitored_email_domain}

as u can find bellow there is more than one email to unsubscribe , the reason is that users gets all tracking_hashes that were sent pare batch.
 
### Log errors
![image](https://user-images.githubusercontent.com/67871785/108732164-f6d80200-7535-11eb-9c47-a70f9ce0b8f0.png)

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
@mabumusa1 would you be able to take a look at this? Seems like an old problem has resurfaced. Would be good to get this under an automated test if it keeps happening?

**Comment by mabumusa1** [comment]
@RCheesley @adirbnology I do not think this issue applies to amazon API or SMTP only, this issue applies to the providers we use to send out emails. 

If you enable monitored inbox, it will change the List-Unsubscribe to monitor all the values for the list that you are sending to. In the case of any transport that supports webhoosk, we do not enable monitored inbox for bounces and subscribers because they are done via webhooks.

I suggest we disable monitored inbox for any transport other than `Other SMTP` as it is the only that do not provide webhooks

**Comment by RCheesley** [comment]
OK - so in this case @adirbnology should set up the webhook as per [the docs ](https://docs.mautic.org/en/channels/emails/bounce-management#amazon-webhook)to manage the unsubscribe requests?

**Comment by StudioMaX** [comment]
If I remember correctly, Amazon SNS can send webhooks only about Bounces/Complaints/Deliveries, but not about Unsubscriptions.

**Comment by adirbnology** [comment]
@StudioMaX  u remember correct. there is no web-hook option for unsubscribe in SES. 

Tried to disable monitor. here are the results :  
"List-Unsubscribe" is still getting added into the headers. only change is that instead email and link to unsubscribe , now there is only a link. which is wrong as well. again very similar issue to the one mentioned above as all users in batch has the same link to unsubscribe

**Comment by adirbnology** [comment]
so i tried to figure out the cause of getting the same unsubscribe link for all batch and here are my findings: 

setMessageHeaders() is called once per batch. and with that fact the only way unsubscribe would work is by using tokens.

which referred me to getUnsubscribeHeader(): 
![image](https://user-images.githubusercontent.com/67871785/108761361-6d392c00-7557-11eb-8977-fc249eac0116.png)

changing the return "<$url>"; to  return '<{unsubscribe_url}>'; would solve this issue. although im not sure what it would break :)

**Comment by mabumusa1** [comment]
> If I remember correctly, Amazon SNS can send webhooks only about Bounces/Complaints/Deliveries, but not about Unsubscriptions.


You are correct, we track only bounces and complaints using SNS.

The unsubscribe header is generated by Mautic and added to the message before sending, it has nothing to deal with SNS

**Comment by mabumusa1** [comment]
> so i tried to figure out the cause of getting the same unsubscribe link for all batch and here are my findings:
> 
> setMessageHeaders() is called once per batch. and with that fact the only way unsubscribe would work is by using tokens.
> 
> which referred me to getUnsubscribeHeader():
> ![image](https://user-images.githubusercontent.com/67871785/108761361-6d392c00-7557-11eb-8977-fc249eac0116.png)
> 
> changing the return "<$url>"; to return '<{unsubscribe_url}>'; would solve this issue. although im not sure what it would break :)

This might be a good solution, I suggest you make a PR and then we can review and see if it breaks anything.

**Comment by adirbnology** [comment]
> > so i tried to figure out the cause of getting the same unsubscribe link for all batch and here are my findings:
> > setMessageHeaders() is called once per batch. and with that fact the only way unsubscribe would work is by using tokens.
> > which referred me to getUnsubscribeHeader():
> > ![image](https://user-images.githubusercontent.com/67871785/108761361-6d392c00-7557-11eb-8977-fc249eac0116.png)
> > changing the return "<$url>"; to return '<{unsubscribe_url}>'; would solve this issue. although im not sure what it would break :)
> 
> This might be a good solution, I suggest you make a PR and then we can review and see if it breaks anything.

I can do that , i just thought maybe someone knows that part of code . I guessed there is a reason for returning what it returns

**Comment by mabumusa1** [comment]
@adirbnology it might be a bug, so I think a PR is the first step
