### ISSUE TITLE
Focus item cookie session bug

### ISSUE THREAD

**Issue by wise-gorilla** [mautic/mautic#9705]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Mautic sets the expiration date of mautic_focus_1 cookie to "Saturday, January 1, 10000 at 1:59:59 AM" instead of "Session" even when the focus item is set to appear once per session, that issue happens on Chrome and the new edge but it wors fine with Firefox. that issue will cause the focus item to appear only once

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.4
| Browser | Chrome  88.0.4324.182

### Steps to reproduce
1. Create a focus item and set it to appear once per session.
2. Check the mautic_focus_x cookie expiration date on Chrome or Edge Chromium.
3. close the browser and open it again and the focus item will not appear again
### Log errors
No errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for reporting it @Wise-Gorilla.  Just to clarify, is the session cookie changing between the tests (ie indicating a new session)?

**Comment by wise-gorilla** [comment]
> Thanks for reporting it @Wise-Gorilla. Just to clarify, is the session cookie changing between the tests (ie indicating a new session)?

mtc_sid cookie value changes between session on Firefox but it don't change on Chrome and Edge Chromium
