### ISSUE TITLE
Mautic not fetching Read/Clicks from Mandrill

### ISSUE THREAD

**Issue by leobarcellos** [mautic/mautic#971]
The email has already been read and clicked as the Mandrill says, but on Mautic it keeps saying only "Sent", 0 Read, all emails ignored. 

Any clue?

![screen shot 2015-10-02 at 2 31 45 pm](https://cloud.githubusercontent.com/assets/3453303/10253181/56af727a-6912-11e5-8719-5ce2a2bbf178.png)

![screen shot 2015-10-02 at 2 32 50 pm](https://cloud.githubusercontent.com/assets/3453303/10253196/7d9529c0-6912-11e5-9b25-6250fe7e8e9d.png)

**Comment by alanhartless** [comment]
Mautic doesn't support fetching the read/click stats from Mandrill directly.

But if Mautic is not noting open/reads, I'd first check to ensure the tracking pixel is using the right URL.  Campaigns send via the cron job will use the Site URL in Mautic's Configuration as the base URL to the emails tracking pixel.  If that is incorrect, the image in the email that tracks opens will be incorrect.

Also, in 1.2.1, if a lead clicks a link in an email, the email will be marked as read.

**Comment by escopecz** [comment]
Closing for lack of feedback
