### ISSUE TITLE
Integration not possible to complete

### ISSUE THREAD

**Issue by IgorGalic1** [mautic/mautic#9716]
Hello Guys, Is there a way to contact someone from mautic support? Im trying to connect Syncspider with Mautic and we have a native integration with Mautic, but for some reason, after i put in my credentials and accept the connection with syncspider I just get whitescreened, so if i get to the part where i can connect with Mautic but mautic doesnt connect the integration, Im suspecting its something wrong with Mautic

Mautic is on a local database
 
![image](https://user-images.githubusercontent.com/79528767/108867427-7973c680-75f5-11eb-85f5-8641428f5770.png)

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by IgorGalic1** [comment]
Hello Sir, I dont see the button where I can post the issue on forum .
please advise.
