### ISSUE TITLE
Relative dates for segments shifted by one day

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#9719]
## Bug Description
We want to do a segment that contains all users one day before a defined date (e.g. end of trial, end of contract etc.). We found out, that the relative date is shifted by 1 day each.

This is how we defined the segment:
<img width="569" alt="Bildschirmfoto 2021-02-23 um 21 50 14" src="https://user-images.githubusercontent.com/1241376/108906929-c40b3800-7621-11eb-91fb-00d8fae8651b.png">

For real it should be **<= +1 day** and **>= -1 day** of the given end date (very difficult and hard to understand logic by the way 😎) 
However, it only works if you make use of **<= +2 day** and **>= -2 day** to define this 1 day before segment.

<img width="371" alt="Bildschirmfoto 2021-02-23 um 21 51 59" src="https://user-images.githubusercontent.com/1241376/108907216-1cdad080-7622-11eb-96c9-8c2a79614f64.png">

This was the only way to get it to work at all.

| Q   | A
| --- | ---
| Mautic version |  3.2.5
| PHP version |  7.3
| Browser |  any

### Steps to reproduce
1. define a custom field with a date for the lead (end of contract for instance)
2. define a segment as described - it only works with adding a day in each direction. 
 
### Log errors
none

**Comment by RCheesley** [comment]
Thanks for reporting this, it does indeed sound like a bug. Assuming that all the other dates in your Mautic instance are working and it's not some issue with the system clock for example? Just wanted to check before we dive into looking to fix it!

**Comment by dsp76** [comment]
No system clock is correct. If it was a wrong date, it would only shift in one direction - not in both?

**Comment by dsp76** [comment]
Looks like, this is still happening in v4
