### ISSUE TITLE
Multi-segment emails reports don't add up correctly

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#9727]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.2.32
| Browser | Chrome

### Steps to reproduce
1. Send a segmented email to more than one segment list.
2. Check the chart after the send.

The chart view on segment emails has always caused me headaches, things have never really worked correctly here. It's normally only a couple out but in a recent campaign quite obvious that it didn't add up correctly. 

First of all, the Sent counter says 1916 emails sent, but when looking at "All lists combined" it only shows 1902.

![mautic-emails-sent-chart](https://user-images.githubusercontent.com/41902603/109138557-675b6a80-7752-11eb-84d0-72b92f807cf2.PNG)

The same thing is happening with the reads. The read counter shows 326, but on the graph, it shows 298. 

![mautic-email-read-chart](https://user-images.githubusercontent.com/41902603/109138574-6de9e200-7752-11eb-8f90-a691d132e5e9.PNG)

In that same campaign, it says there were 439 sends for segment 1, and 1477 sends for segment 2. With a total number of sends being 1902. But if you add those 2 figures together it gives you 1916, which is what we get in the Sent field. It also shows me at the bottom of the contacts section that 1916 contacts have been sent the email.

Reads gets even funkier. Segment 1 has 72 reads, segment 2 has 228 with an all list read count of 298. Again, if you add those 2 up, that should be 300. But that doesn't match what is in the read field or what is in the "all list" column. If I click on the Read link via the Email List view, it actually shows me as having 300 contacts who have read the email. But the read count for the campaign is 326. 

![mautic-email-list-view](https://user-images.githubusercontent.com/41902603/109138925-cf11b580-7752-11eb-9e0c-d5798209552b.PNG)

The chart is showing the number of contacts, and a contact might view the email more than once. I get that, but the issue here is the inconsistency between the statistics you see when looking at a campaign. If the stats on the Email List view are looking at total interactions, I think the report shown within needs to reflect that.

In an ideal world, we'd maybe have a secondary chart that looks at the Contact (Segment) performance. It's also not obvious that the segment chart is looking at the Contacts, rather than interactions. I can see this tripping up a lot of users.

The actual bug report here is the chart not calculating properly.

 
### Log errors
No Log errors.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
I think we have a PR to address this - let me have a search!

**Comment by RCheesley** [comment]
https://github.com/mautic/mautic/pull/9580 Does this PR address the issues you are mentioning @colourfulowl ?

**Comment by RCheesley** [comment]
Bumped to 3.3.3 - please test the PR linked to this issue as it may resolve the problem for you.
