### ISSUE TITLE
Download Link outdated

### ISSUE THREAD

**Issue by NicoHood** [mautic/mautic#9729]
https://www.mautic.org/mautic-releases
Points to the 3.2.4 release.

**Comment by RCheesley** [comment]
🕵️‍♀️  Gosh, thanks for flagging that! I had entirely forgotten that we created that page!

Will add it to the release leader workflow to update it!

**Comment by NicoHood** [comment]
Well, it is the main download button. I even waited a day, cause I was not sure if 3.2.x is kept there for some specific reason...

**Comment by RCheesley** [comment]
https://www.mautic.org/download is the main place to download Mautic. That will always get the latest version. You can also always go direct to the Releases on Github :)

**Comment by RCheesley** [comment]
Page updated! 😅

**Comment by NicoHood** [comment]
But how do you get there? I just clicked the menu Download -> Releases -> Mautic Releases

**Comment by RCheesley** [comment]
![screenshot-www mautic org-2021 02 25-18_41_39](https://user-images.githubusercontent.com/2930593/109200990-2b97c380-7799-11eb-9d6e-6f18970ccb60.png)
