### ISSUE TITLE
Check database version in installation script

### ISSUE THREAD

**Issue by NicoHood** [mautic/mautic#9730]
I came here from [this issue](https://github.com/mautic/mautic/issues/8587). My debian server still uses a too old version of maria DB it seems. This issue was not reported when installing mautic 3.3.1. I guess this can be improved.

Here is an equivalent forum post:
https://forum.mautic.org/t/include-database-version-test-in-installer/14872

**Comment by RCheesley** [comment]
Hi there, we actually have an [open issue](https://github.com/mautic/mautic/issues/9607) to bring across the checks that we do in the Mautic 3 upgrade to the install and Upgrade process, as part of one of our Strategic Initiatives. This would likely have picked up on issues like the one you've explained.

I agree that you should not be able to install when you're using incompatible architecture so we will need to address that.

How did you install in the first place, did you use the release package or clone from GitHub?

What are the versions of MariaDB, PHP etc on your server?

**Comment by NicoHood** [comment]
I copied the 3.3.1 release on my server and connected to the database. I saw the mentioned error. The server uses Debian stretch with mariadb 10.1 and php 7.4
https://packages.debian.org/de/stretch/mariadb-server

**Comment by RCheesley** [comment]
Right, so did you run through the GUI installer to run the installation? Or just grabbed the files and connected to an existing database?

**Comment by NicoHood** [comment]
I've never used mautic before, so it was all a clean install.
I ran the gui installer and it crashed with a database connection error. Now after a quick google it turned out that my database version is too old. But it would be better if the check in the first place would have told me that.

**Comment by RCheesley** [comment]
Ahh gotcha sorry that was not clear to me. Indeed that is why we want to bring those checks over into the install and upgrade from our 2->3  migration script! 

As we are already tracking this in #9607 I will close down this issue so that we can keep things in the same place. Thanks for adding your voice!
