### ISSUE TITLE
Upgrading from v3.2.5 to v3.3 or v3.3.1 breaks the dashboard

### ISSUE THREAD

**Issue by jcmartinez** [mautic/mautic#9738]
## Bug Description
See description in the forum post: https://forum.mautic.org/t/unable-to-complete-upgrade-from-v3-2-5-to-3-3/18267

| Q   | A
| --- | ---
| Mautic version | v3.2.5 to v3.3 or v3.3.1
| PHP version | 7.3.27
| Browser | Chrome Version 88.0.4324.182 (Official Build) (64-bit)

### Steps to reproduce
1. Update from v3.2.5 to v3.3 or v3.3.1 using the CLI
 
### Log errors
See the forum post: https://forum.mautic.org/t/unable-to-complete-upgrade-from-v3-2-5-to-3-3/18267

**Comment by jcmartinez** [comment]
By the way, I noticed that there is a commit on https://github.com/mautic/mautic/issues/9709. 
This is still happening.

**Comment by RCheesley** [comment]
Thanks for reporting this. Can you check to see if you have any errors in your log? What about the browser console?

Also does this persist after clearing the cache?

**Comment by jcmartinez** [comment]
Somehow, today the dashboard started working. I had cleared the cache multiple times and I tried using different browsers.
It works now. I'll report back if it happens again.
Thanks!
