### ISSUE TITLE
Database schema file

### ISSUE THREAD

**Issue by Thileepan** [mautic/mautic#974]
Hi Guys,

I want to install the mautic in our local enviroment. Also, I would like to view the MySQL schema file for fresh install. Please help me to find the path. Thanks

**Comment by alanhartless** [comment]
Mautic doesn't have a sql file to install rather it uses Doctrine to generate the schema from the entities which happens during the web installer process. If you want to do that via cli instead, you could use the command `php /path/to/mautic/app/console doctrine:schema:install`

Thanks!
Alan

**Comment by Thileepan** [comment]
Thanks Alan.

I installed using composer. Now whenever I access the interface through web browser using below URL,

http://localhost/mautic-master/

it redirects to http://localhost/index.php/mautic-master/ and says below error.
The requested URL /index.php/mautic-master/ was not found on this server.

Please help me.

Thanks
Thileepan

**Comment by Thileepan** [comment]
No Issues. I have fixed it. The issue is rewrite module in apache was not enabled.
