### ISSUE TITLE
UTM tags not added to links inside email messages

### ISSUE THREAD

**Issue by jcmartinez** [mautic/mautic#9740]
## Bug Description

The links inside the email messages don't have the UTM tags, even though they have been added in the email message editing page. This was noticed after sending a campaign where users clicked the links and Google anlytics didn't register the clicks.

| Q   | A
| --- | ---
| Mautic version | v3.2.5
| PHP version | 7.3
| Browser | Chrome

### Steps to reproduce
1. Create an email and add your custom values to the UTM tag fields
2. Create a marketing campaign that uses the email message above
3. Start sending the email messages
4. Email message links are missing the UTM parameters

**Comment by RCheesley** [comment]
Hi there, thanks for reporting this. Does it persist in the latest release, 3.3.1?

**Comment by jcmartinez** [comment]
@RCheesley
I can't tell whether it is happening with 3.3.1 because after updating, my emails aren't going out. I'm opening another issue. 
I'll report back on this issue as soon as I get the other issue fixed and can see if 3.3.1 is adding the UTM parameters.
Thanks!

**Comment by jcmartinez** [comment]
Tested on a fresh installation.

This problem is present in v3.3.1
