### ISSUE TITLE
Contact view in campaigns stuck in 30 items view

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#9758]
Contact list in campaigns view will not respect selected number of contacts in view.

![image](https://user-images.githubusercontent.com/1241376/110294235-e1f87580-7fef-11eb-8ee3-732f40130a90.png)

| Q   | A
| --- | ---
| Mautic version | 3.2.5, 3.3.1
| PHP version | 7.4
| Browser | any

### Steps to reproduce
1. go to a campaign with more than 30 contacts included
2. try to switch view to a different number than 30
3. will directly switch back to 30

**Comment by RCheesley** [comment]
Thanks for reporting - have reproduced this is 3.3.1 - seems to be an issue with the pagination: https://youtu.be/-UP20NGPpwY
