### ISSUE TITLE
Image directory not opening

### ISSUE THREAD

**Issue by martinstr** [mautic/mautic#9759]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | v3.3.1
| PHP version | 7.3.27
| Browser | Chrome

### Steps to reproduce
1. Create a new email
2. Add a new image slot and click replace; choose an image from your directory the window will not open. It will work if we choose text slot and then add an imige that way.
 
### Log errors
None

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hello @martinstr can you please test https://github.com/mautic/mautic/pull/9651 ? I think it solves your issue.

**Comment by martinstr** [comment]
> Hello @martinstr can you please test #9651 ? I think it solves your issue.

Nope, the fix did not work.

**Comment by npracht** [comment]
Thanks for confirmation
