### ISSUE TITLE
Import of company details to a contact get lost

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#9764]
Trying to import company data into several company fields (e.g. address fields, company email, company website etc.).
I have a list of contact - company (1:1 relationship). Import does work for the company name, but not for the other fields.

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 7.4
| Browser | any

### Steps to reproduce
1. import a list with contacts with company details as well
2. map company name, company email, company address fields

result: only the company name will be imported for the contact. the rest of the fields data gets lost.

### Log errors
none, looks like this feature is not finished

**Comment by RCheesley** [comment]
Thanks for reporting the issue!

**Comment by jcmartinez** [comment]
I have seen this issue in v3.2.5 and v3.3.0.

**Comment by RCheesley** [comment]
Maybe this is related/addressed by this PR: https://github.com/mautic/mautic/pull/9782 - could you take a look?

**Comment by RCheesley** [comment]
Confirmed this bug in action!

**Comment by RCheesley** [comment]
Unfortunately this is not resolved by #9782 (at least from my testing) so we would need to look at whether it is a case of the import function not having the ability to import those fields or if something is broken.

**Comment by jcmartinez** [comment]
When this happened to me I have used custom SQL queries to populate the missing fields in the company table and the other table that matches both, the company and the lead. 

When I do that I can see everything in Mautic; therefore, this is not a problem of the output, this is a problem on the input side. 

As the author of this ticket said, only company name gets imported, the other fields in the table are empty.

**Comment by benfavre** [comment]
This is super breaking, and have spent countless support hours handling this.
Any progress or plan to adress this ?

**Comment by patrykgruszka** [comment]
This issue is fixed by #9461. I've added unit test to ensure that this works as expected. 

There is a workaround for this issue. It should import data correctly when you map `Company Name` (from company fields group) instead of `Company` (from contact fields group).

**Comment by RCheesley** [comment]
Closing the issue as #9461 has been merged! Thanks all!

@all-contributors please add @dsp76 for bug
