### ISSUE TITLE
Rate opening superior 100%

### ISSUE THREAD

**Issue by BethsyFR** [mautic/mautic#9778]
Hello

The open rate on some emails sent, only to certain segments exceeds 100% at the end of the sending.
How to solve this problem?

Thanks

**Comment by elilogan** [comment]
Select the contacts in the campaign and examine email opens in "History" Tab. If you find any **Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)** Your email was scanned by google thus the tracking pixel was served and it counts as one email open.
![Screenshot (8)](https://user-images.githubusercontent.com/35710540/111529623-5e95fd00-8730-11eb-93b5-2c9667a4b05e.png)


There is no current fix I'm aware of.

**Comment by mabumusa1** [comment]
This issue is related to https://github.com/mautic/mautic/issues/9798

**Comment by RCheesley** [comment]
Closing in favour of centralising the discussions in #9798
