### ISSUE TITLE
Tracking contacts behaviour within different campaigns

### ISSUE THREAD

**Issue by Pegasus-consultancy** [mautic/mautic#9787]
**Hi everyone,**

I was hoping to get advice on how to achieve the following.

**Assumptions**

- Each of our contacts can be included in multiple and different campaigns (based on the segment they belong to).
- Each of these contacts could answer positively to emails originating from campaign A, do not reply at all to emails originating 
   from campaign B, or reply negatively to emails originating from campaign C.

**Objective**

- We need to be able to know in which campaigns the contact is involved.
- We need to know the ‘status’ of the contact within each campaign (=we need to know to which campaigns he replied 
   positively/negatively or to which he didn’t reply at all).

**Questions**

- Is there a way to determine whether the content of the reply was positive/negative (some kind of sentiment analysis)?
- Is there a place where the contact’s replies would be listed (history of communication)?
- Is there a way to track the contact behavior within the different campaigns in which he’s involved? (we have looked at ‘stages’ 
   but those seem to be global, not specific to a campaign-contact combination; tags do not seem appropriate either since we 
   might end up with too many)?

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
