### ISSUE TITLE
Using ‘stage’ as a campaign condition

### ISSUE THREAD

**Issue by Pegasus-consultancy** [mautic/mautic#9788]
Hello everyone!

Does anyone know if, when defining a campaign, it is possible to create a condition based on a contact’s ‘stage’?

What I’m trying to achieve is:
Have the ability to include a contact in campaign A and potentially be able to exclude it from campaign B, depending on what the contact’s stage (status of the contact within the sales pipeline) is.
As far as I understand, campaigns can only be associated with ‘segments’, not to a combination of ‘segment’ and ‘stage’, therefore the idea of creating a condition for the stage.

Any thought/recommendation?

Thank you.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
