### ISSUE TITLE
Information about campaigns in contacts

### ISSUE THREAD

**Issue by Pegasus-consultancy** [mautic/mautic#9789]
Hi everyone!

I’m currently setting up Mautic and I came across with a doubt. Is it possible to see the campaigns that contacts are related to? or how can I see this info?

I greatly appreciate your help!

Thanks!

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
