### ISSUE TITLE
Opt-out option

### ISSUE THREAD

**Issue by Pegasus-consultancy** [mautic/mautic#9790]
Hi everyone!

I am currently migrating to Mautic from Reply.io 1. I noticed that Reply has an option of opt-out and I wanted to know if there’s an option that could do that in Mautic?

I greatly appreciate your advice!

Thanks!

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
