### ISSUE TITLE
Report (Table) Graph Panel Not Filling Space

### ISSUE THREAD

**Issue by colourfulowl** [mautic/mautic#9791]
| Q   | A
| --- | ---
| Mautic version | V2 - V3.2.5
| PHP version | 
| Browser | Chrome & Firefox

### Steps to reproduce
1. Create a report with a table panel view in it. For instance, the standard Submission of published Forms. The Panels at the bottom (.panel css class) don't fill the bootstrap column in Chrome and Firefox but it works fine in MS Edge. I've had this issue since v2 across multiple databases.

![mautic-panel-width](https://user-images.githubusercontent.com/41902603/111149300-a1b36d00-8584-11eb-802d-a309f7909289.PNG)
_Top left - Chrome, Bottom Left - Firefox, Right - MS Edge_

A simple enough fix is to add the "width:100%" to the .panel class in .app.css

Before I create a pull request, is anyone else having this issue, or is it just something funky going on on my end.

**Comment by RCheesley** [comment]
Hi there,

To rule out something being buggy with the dashboard sizing, what have you got set in this field for the widgets?

![screenshot-mautic32 ddev site-2021 03 15-12_05_10](https://user-images.githubusercontent.com/2930593/111150978-b7c22d00-8586-11eb-840d-1cb1b9e27011.png)

I tried this with 50% set for two widgets and it worked as expected.

![screenshot-mautic32 ddev site-2021 03 15-12_06_35](https://user-images.githubusercontent.com/2930593/111151116-f0620680-8586-11eb-95e1-bc85d1de7228.png)

**Comment by colourfulowl** [comment]
Hi @RCheesley

Sorry I was supposed to change the title. This only effects the Reports or any legacy views that use .panel for the class. The Dashboards use a different system with the Card-flex and widgets. 

It only seems to appear when you add a "table" in the graphs section of the reports. It does this any report you create that outputs a (Table) graph.

![mautic-panel-report-widths](https://user-images.githubusercontent.com/41902603/111156261-71bc9780-858d-11eb-8514-45e561c07e8e.PNG)

**Comment by RCheesley** [comment]
Gotcha - makes sense now!

Yes I see the same thing when I look at that report now:

![screenshot-mautic32 ddev site-2021 03 17-13_00_08](https://user-images.githubusercontent.com/2930593/111471417-c93f3c80-8720-11eb-862f-f807e9998d29.png)

Seems like a UI bug - would you be up for digging into it and making a PR?
