### ISSUE TITLE
typo in date format

### ISSUE THREAD

**Issue by HN-PRO** [mautic/mautic#9792]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This bug was fixed in [#7693](https://github.com/mautic/mautic/pull/7693), why does it still exist [2.16.1](https://forum.mautic.org/t/announcing-mautic-2-16-1-beta/13438)？

| Q   | A
| --- | ---
| Mautic version | 3.3.0
| PHP version | 7.3.2
| Browser | 

### Steps to reproduce
1. none
2. none
 
### Log errors
none

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there,

We are no longer supporting Mautic 2. The last version was 2.16.5 so you should update as there was a serious security vulnerability which was patched in a recent release.

If this issue persists in 3.3.2 please request to reopen the issue.

Thanks!
