### ISSUE TITLE
Mautic 3.3.1 SAML 2.0 SSO Logout with Keycloak IDP

### ISSUE THREAD

**Issue by FlavioCostaeSilva** [mautic/mautic#9793]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Mautic redirects to "/ s / login" after logout, not to the Keycloak login page
User session is also not terminated on Keycloak
Has Mautic SAML SSO Logout implemented?

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 7.4.14
| Browser | Google Chrome 88.0.4324.182 - 64 bits

### Steps to reproduce
1. Configure SAML on Keycloak and Mautic
1.1 Map Keycloak username, email, firstName and lastName user attributes on Mappers tab from client section
1.2 Download Keycloak config file on Installation tab (Select Mod Auth Mellon files format)
1.3 Unzip files, edit idp-metadata.xml removing <md:EntitiesDescriptor> superior tag
1.4 Add -----BEGIN CERTIFICATE----- and -----END CERTIFICATE----- to client-cert.pem file
1.5 Add -----BEGIN RSA PRIVATE KEY-----and -----END RSA PRIVATE KEY----- to client-private-key.pem file
1.6 Upload idp-metadata.xml, client-cert.pem, client-private-key.pem on Mautic SAML SSO config page
2. Go to Mautic home page "/", on Keycload IDP login page, log in with a valid user, login will be OK
3. Inside Mautic, do logout

### Log errors
No one log is generated by Mautic or Keycloak IDP

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi @FlavioCostaeSilva thanks for reporting this. Was this an issue before (eg it stopped working with the 3.3.1 release) or are you having trouble configuring it for the first time?

**Comment by FlavioCostaeSilva** [comment]
Hi @RCheesley, 
Is my first time configuring it

**Comment by RCheesley** [comment]
OK sounds like it might be an issue with this specific provider then - will have to see if we can get someone to help troubleshoot. Are you able to auth with any other provider?

**Comment by FlavioCostaeSilva** [comment]
I work for a brazilian company, we use Keycloak IDP for all the identity management.
I will configure and try other IAM tool with SAML support. I will check if we have the same issue. After this, I back with the news for us
Thanks for help :)

**Comment by FlavioCostaeSilva** [comment]
Today I tried configure the auth0.com IDP online service, with SAML 2.0 support, but I had problems to configure correctly attribute mapping on Auth0 configuration interface

Due a lack of time, I will focuse on try to fix the issue with the Mautic SSO SAML Logout on Keycloak. On success, I will write a PR for Mautic team
