### ISSUE TITLE
Dublicated Contact created by logmein GoToWebinar Plugin

### ISSUE THREAD

**Issue by Corsnec** [mautic/mautic#9794]
## Bug Description

If a contact has attended or registered for several different GoToWebinars, the GotoWebinar plugin will create duplicate contacts with the same email addresses. 
A fresh installation was used for testing. No custom field was created.

![grafik](https://user-images.githubusercontent.com/47634604/111334747-1f09db00-8674-11eb-9e6d-e2c6402486b7.png)

3 times a Contact with the same E-Mail

Registration and Attended created two Contacts
**History Contact#1**
![tempsnip2](https://user-images.githubusercontent.com/47634604/111335713-e4ed0900-8674-11eb-9461-5867b6966e31.png)
**History Contact#2**
![tempsnip3](https://user-images.githubusercontent.com/47634604/111335716-e4ed0900-8674-11eb-8afb-4f574c3b1b26.png)

A later registration created another Contact.
**History Contact#3**
![tempsnip](https://user-images.githubusercontent.com/47634604/111335711-e4547280-8674-11eb-88ce-db5cecb3a46d.png)

| Q   | A
| --- | ---

| Mautic version: 3.3.1 | 
| PHP version: 7.4.16 | 
| Browser: Firefox | 

### Steps to reproduce
1. Connect GoToWebinar Plugin
2. Run Cronjob
3. Search for Duplicates

or

1. Go to Contacts and press "+ New"
2. Create new Contact
3. Save and Close
4. Create another new Contact with the same Email Adress
5. Save an Close

 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for raising this bug @Corsnec! Hopefully we can have someone take a look at confirming it soon - are you able to dig into it yourself at all?

**Comment by Corsnec** [comment]
@RCheesley I'm not really able to dig into it. I just did a look into the table plugin_citrix_events. It looks like there is a problem with the case sensitive.  The big number is the lead_id.


![Unbenannt-1](https://user-images.githubusercontent.com/47634604/111628398-78971480-87f0-11eb-81aa-e8b059bd0a86.png)

**Comment by kuzmany** [comment]
@Corsnec maybe this could help you https://github.com/mautic/mautic/pull/9366
This PR prevent this case sensitive issues.

**Comment by Corsnec** [comment]
@kuzmany  #9366 Doesn't work on php bin/console mautic:citrix:sync just tested it

**Comment by dsp76** [comment]
This is still happening... Mautic should not treat contacts with same email, but different capitalization as different contacts. Should be lowercased before compared.

**Comment by Corsnec** [comment]
I could solve the problem with db tiggers...... Problem effects everyone!

CREATE TRIGGER `E-Mail Lower Case (Before Insert)` BEFORE INSERT ON `leads`
 FOR EACH ROW SET NEW.email = LOWER(NEW.email)

CREATE TRIGGER `E-Mail Lower Case (Before Update)` BEFORE UPDATE ON `leads`
 FOR EACH ROW SET NEW.email = LOWER(NEW.email)

**Comment by RCheesley** [comment]
@dsp76 @Corsnec can one of you check in 4.0.0-rc and let us know if it persists? Thanks!

**Comment by dsp76** [comment]
Despite a warning, Mautic still creates the duplicate in version 4.0.1. That's a no-no.

![image](https://user-images.githubusercontent.com/1241376/138185176-efe7c66a-6d30-4ff6-bb50-06c77e1ce9e9.png)
