### ISSUE TITLE
Installer warning about missing imap but it's installed

### ISSUE THREAD

**Issue by JHGitty** [mautic/mautic#980]
I get warning on installer that 'imap' php extension is not installed. I use PHP5.6 and the 'imap' extension is already installed and should work fine. Is there any bug on the check?

**Comment by alanhartless** [comment]
It sounds like it's installed but not enabled.  Do you have access to a phpinfo() output to verify?

**Comment by JHGitty** [comment]
Imap is installed and enabled. I use Plesk 12.5 with PHP 5.6.

Output of phpinfo()
```
imap
IMAP c-Client Version 	2007f
SSL Support 	enabled
Kerberos Support 	enabled 
```

**Comment by mbabker** [comment]
See #981

**Comment by JHGitty** [comment]
@mbabker Wow, that was fast. Thanks!
Will there be a hotfix for 1.2.0 ? I am not sure if we should use a dev-version? ..

**Comment by mbabker** [comment]
It should be patched with the next release.  In the meantime, just ignore the message (as it's an optional check it doesn't block install).

**Comment by JHGitty** [comment]
@mbabker Oh yes, you are right. My mistake, thanks! :-)
