### ISSUE TITLE
Safari 7.1.8/13.0.5 Form Submission Bug

### ISSUE THREAD

**Issue by fitzg2** [mautic/mautic#9800]
## Bug Description

SiteA > Simple HTML form which submits to
SiteB > Mautic install

The first time the site was loaded and the form submitted Safari threw a SSL warning even though the certificate is valid, then the browser went straight to the form which of course received 403 from Mautic.

We are getting the following warnings

![image](https://user-images.githubusercontent.com/17569693/111623547-46be8780-87c9-11eb-88bf-24d2f68b067a.png)

The form submit button stays with ''please wait''

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 7.4.14
| Browser | Safari 7.1.8 and 13.0.5

### Steps to reproduce
1. 
2. 
 
### Log errors
See image.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by fitzg2** [comment]
![image](https://user-images.githubusercontent.com/17569693/112056440-c6848300-8b36-11eb-883b-d267682764ce.png)

Here are expanded warnings.

**Comment by RCheesley** [comment]
Thanks for flagging the issue and for the error reports!

**Comment by RCheesley** [comment]
@fitzg2 are you able to reproduce this in Mautic 4? Does this happen in any other browsers, or just Safari in the specified versions?
