### ISSUE TITLE
api filters operator issue

### ISSUE THREAD

**Issue by giorgiopaolucci** [mautic/mautic#9802]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hello,
I'm porting my mautic installation based on 2.13 to 3.3.1.
I have been populating and maintaining contacts and segments using api for two years and everything is working fine on my 2.13 installation.  The same api command I use on 2.13 gives error with 3.3.1 , specifically mautic complains about wrong values with the filters/operator parameter.

Here is what is returned:
root@providence:/tmp# curl -k -X POST   -d name=automatico-lista-utenti.unicloud -d alias=automatico-lista-utenti.unicloud -d isPublished=1 -d isGlobal=false -d "filters%5B0%5D%5Bglue%5D=and" -d "filters%5B0%5D%5Bfield%5D=tags" -d "filters%5B0%5D%5Bobject%5D=lead" -d "filters%5B0%5D%5Btype%5D=tags" -d "filters%5B0%5D%5Boperator%5D%=in" -d "filters%5B0%5D%5Bfilter%5D=68"  https://user:xxxxxx@10.10.10.10/mautic/api/segments/new

Output:
{"errors":[{"code":400,"message":"operator: This value is not valid.","details":{"operator":["This value is not valid."]}}]}root@providence:/tmp# 

The same command with a NULL value for 'operator'  attribute works fine, as you can see below:

root@providence:/tmp# curl -k -X POST   -d name=automatico-lista-utenti.unicloud -d alias=automatico-lista-utenti.unicloud -d isPublished=1 -d isGlobal=false -d "filters%5B0%5D%5Bglue%5D=and" -d "filters%5B0%5D%5Bfield%5D=tags" -d "filters%5B0%5D%5Bobject%5D=lead" -d "filters%5B0%5D%5Btype%5D=tags" -d "filters%5B0%5D%5Boperator%5D%=" -d "filters%5B0%5D%5Bfilter%5D=68"  https://user:xxxxxx@10.10.10.10/mautic/api/segments/new

Output:
{"list":{"isPublished":true,"dateAdded":"2021-03-19T13:40:02+00:00","dateModified":null,"createdBy":1,"createdByUser":"Admin Admin","modifiedBy":null,"modifiedByUser":null,"id":19,"name":"automatico-lista-utenti.unicloud","publicName":"automatico-lista-utenti.unicloud","alias":"automatico-lista-utentiunicloud1","description":null,"filters":[{"glue":"and","field":"tags","object":"lead","type":"tags","filter":["68"],"display":null,"operator":null}],"isGlobal":false,"isPreferenceCenter":false}}
root@providence:/tmp#

Please note that both  statements works fine on my server based on 2.13.

Same error is returned with 'edit' api.

Mautic does not produce any log even in debug mode.

Any help is appreciated.
Best regards.
Giorgio Paolucci

| Q   | A
| --- | ---
| Mautic 3.3.1 | 
| PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS ) Copyright (c) The PHP Group Zend Engine v3.4.0, Copyright (c) Zend  Technologies with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
 | 
| Browser: n.a | 

### Steps to reproduce
1.  try to create a new segment  with  filters criteria including 'operator' field and value not NULL ('in' for example)

 
### Log errors
no log produced

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Hi there, here is the [Mautic 3.x upgrade docs](https://github.com/mautic/mautic/blob/features/UPGRADE-3.0.md) in case that helps to track things down - unfortunately our dev docs at [developer.mautic.org](https://developer.mautic.org) are rather out of date so they may not be much help (we are working on it!).

I'll post this in the Dev channel on Slack and see if anyone can assist.

**Comment by giorgiopaolucci** [comment]
Hi Ruth, thank you for your feedback...Unfortunately I couldn't find any useful information in the docs you suggested and mautic code complexity is far beyond my skills to try to debug it and track this issue...
All the best.
Giorgio
