### ISSUE TITLE
Report Hide Field 

### ISSUE THREAD

**Issue by logixbytes** [mautic/mautic#9805]
Hi guys,

I use Mautic regularly and find that HIDE field would be of a great help if it is added to the Reporting section.

Any ideas or updates on this if it is being worked on the feature.

Warm Regards,

Venkatesha

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/ideas as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems or suggesting features :)
