### ISSUE TITLE
Feature Request: Date range at MauticCitrixBundle

### ISSUE THREAD

**Issue by insane85** [mautic/mautic#9808]
Hello all,

I found a to-do in your code where the time period should be configured when fetching the webinars from GoToWebinar. This has not been done yet, so I had to adapt the code directly. Could you estimate when this feature will be available in Mautic, otherwise an update of the plug-ins would undo our customisation?

To-Do found in line 175 CitrixHelper.php

Best Regards 
Hüseyin

**Comment by RCheesley** [comment]
Thanks for raising this - if you have implemented the todo item why not make a PR to include that in core? Then it would not be a problem with future updates!

Here is some info on how to get started and make a PR: https://contribute.mautic.org/contributing-to-mautic/developer/code/pull-requests and feel free to ask for help in #t-product on Slack if you need a hand with anything (https://mautic.org/slack in case you need an invite!)
