### ISSUE TITLE
Cron is not working due to LazyCollection

### ISSUE THREAD

**Issue by pramirezrey** [mautic/mautic#9816]
Mautic version is: v3.3.1
PHP version is: PHP Version 7.4.16
Database type and version is: MySQL 5.7
Browser: N/A

**Steps**

I setup all the crons as the guide said. When it's time to execute the cron, the action is not taken and the following error is shown in the Apache log.

**Crons**

*/15 * * * * php /home/xxxxxx/www/bin/console mautic:webhooks:process >> /home/xxxxxx/logs/cron_logs/cron_mautic_webhooks 2>&1
*/15 * * * * php /home/xxxxxx/www/bin/console mautic:social:monitoring >> /home/xxxxxx/logs/cron_logs/cron_mautic_social 2>&1
00 01 * * 7 php /home/xxxxxx/www/bin/console mautic:iplookup:download >> /home/xxxxxx/logs/cron_logs/cron_mautic_iplookup 2>&1
*/15 * * * * php /home/xxxxxx/www/bin/console mautic:import >> /home/xxxxxx/logs/cron_logs/cron_mautic_import 2>&1
*/15 * * * * php /home/xxxxxx/www/bin/console mautic:email:fetch >> /home/xxxxxx/logs/cron_logs/cron_mautic_fetch 2>&1
*/15 * * * * php /home/xxxxxx/www/bin/console mautic:segments:update >> /home/xxxxxx/logs/cron_logs/cron_mautic_segments 2>&1
*/15 * * * * php /home/xxxxxx/www/bin/console mautic:campaigns:update >> /home/xxxxxx/logs/cron_logs/cron_mautic_campaigns 2>&1
*/15 * * * * php /home/xxxxxx/www/bin/console mautic:emails:send >> /home/xxxxxx/logs/cron_logs/cron_mautic_emailsend 2>&1
*/15 * * * * php /home/xxxxxx/www/bin/console mautic:campaigns:trigger >> /home/xxxxxx/logs/cron_logs/cron_mautic_triggers 2>&1
MAILTO='xxx@xxx.com'

**These errors are showing in the log:**
PHP Warning: Class ‘Tightenco\Collect\Support\LazyCollection’ not found in /home/xxxxxx/www/vendor/tightenco/collect/src/Collect/Support/alias.php on line 19
PHP Parse error: syntax error, unexpected ‘=’ in /home/xxxxxx/www/vendor/tightenco/collect/src/Collect/Support/LazyCollection.php on line 611

**Comment by RCheesley** [comment]
The [forum thread you created](https://forum.mautic.org/t/cron-is-not-working-due-to-lazycollection/18683) is where we will respond to support requests.

**Comment by pramirezrey** [comment]
Ok, perfect!
