### ISSUE TITLE
Bugged mautic:campaigns:trigger task and base64 embedded images issue for Mautic 3

### ISSUE THREAD

**Issue by mboron83** [mautic/mautic#9819]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
When mautic is configured to embed images as base64 CID-s, by default only 100 emails get the images properly embeded. The rest of them go without any image. It is related to --batch-limit parameter to control how many mails are created correctly. It's big problem if number of segment contacts changes every hour. 

In my opinion issue appeared first time for Mautic 2.16.0 and it's still preserved even for latest 3.3.2 version. It means that issue is still unsolved for more than 1 year. I found related but closed without any solution issue #9003 so it might be helpful to fix.

BTW: On second server I use Mautic 2.15.1 and there is no such issue.

| Q   | A
| --- | ---
| Mautic version | 3.3.2
| PHP version | 7.4.16
| Browser | Chrome 89.0

### Steps to reproduce
1. Disable cron jobs - just for test purpose
2. Enable **Convert embed images to Base64** option under Configuration -> Email Settings
3. Create an email that references some images.
4. Create a campaign for at least 2 recipients.
5. Run these jobs manually:
```
bin/console mautic:segments:update
bin/console mautic:campaigns:rebuild
bin/console mautic:campaigns:trigger --batch-limit=1
```

6. Take a look at var/spool folder and check the different sizes of created emails. Look, how huge is difference.
```
root@mailing:/var/www/app#  ls -lah var/spool/
total 158K
-rw-r--r-- 1 www-data www-data  31K mar 24 12:45 eR-K1tqmhh.message
-rw-r--r-- 1 www-data www-data 127K mar 24 12:45 hTowKeWHEL.message
```

7. Finally run these job manually:
```
bin/console mautic:emails:send
```
Check that one of the emails includes images while the other doesn't. 
 
### Log errors
Unfortunately there is no log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
Thanks for reporting this - we did seem to have a bunch of issues relating to the base64 feature - see also #9069.

Would you be up for looking into a fix for this?

**Comment by mboron83** [comment]
> Thanks for reporting this - we did seem to have a bunch of issues relating to the base64 feature - see also #9069.
> 
> Would you be up for looking into a fix for this?

I'd love to but unfortunately I'm too busy right now. How about Mautic dev team? They know every line of code so fixing it wouldn't be tough for them.

**Comment by RCheesley** [comment]
> How about Mautic dev team?

That would be volunteers just like you - that is the 'mautic dev team'.

**Comment by mboron83** [comment]
Did anyone try to reproduce this bug on 3.3.3 version?

**Comment by helirexi** [comment]
> Did anyone try to reproduce this bug on 3.3.3 version?

Yes, I can confirm this bug in 3.3.3
yesterday we send about 6K emails with Base64 option. About 200 from 350 last emails to send in var/spool/ was 6-times smaller size.
And one email from this sending fortunately arrived to our colleague inbox, without any images. Confirmed bug.
