### ISSUE TITLE
Segment based on tag with operator "in" (including) not work in mautic 3.3.1

### ISSUE THREAD

**Issue by ced-shubhamverma** [mautic/mautic#9825]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

Hello , I am creating tag based segment with REST API (Mautic Developer Doc- Segment API) in Version 3.3.1 using operator "in" including 
always show error "code":400,"message":"operator: This value is not valid.",
My Json code is this-- when send null or blank in operator then segment create with empty operator
{
    "name": "segment2",
    "alias": "segment2",
    "filters": [
        {
            "glue": "and",
            "field": "tags",
            "object": "lead",
            "type": "tags",
            "filter": [
                16
            ],
            "display": null,
            "operator": "in"
        }
    ]
}

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 7.3
| Browser | chrome

### Steps to reproduce
1. 
2. 
 
### Log errors
 "code":400,"message":"operator: This value is not valid.",

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hello,

In documentation : https://developer.mautic.org/#create-segment
You can see that this value `in` is not offered. Can you try with a correct operator ?
<img width="664" alt="Capture d’écran 2021-04-22 à 15 21 00" src="https://user-images.githubusercontent.com/14075239/115721465-5a3bb000-a37e-11eb-99e7-7de1beb6e21a.png">


I close the issue and we'll reopen if this is still not working while using a correct operator.
Best !

**Comment by ced-shubhamverma** [comment]
Thanks for your response but i need to create segment based on tag with filter tag (including) and can you please let me know the operator for including filter. 

When i create a segment with tag filter and add condition including  <Tag_name> and get the segment with APIs it show that operator = 'in' 
![image](https://user-images.githubusercontent.com/49013175/116688422-4de5d180-a9d4-11eb-9d8d-bb975a0c2798.png)

**Comment by scottmont** [comment]
This is the same result for myself.  I have tried to update the list manually with a contains operator but that's not meant for tags and breaks the filter.

**Comment by biblio-francisco** [comment]
@npracht -
I believe this is an existing issue with all segment filter operators. I am able to reproduce it even with the operators that are supposed to be supported. 

For example:
`{'name': 'All Contacts X', 'filters': [{'object': 'lead', 'glue': 'and', 'field': 'date_identified', 'type': 'date', 'filter': '2021-11-11', 'operator': '='}]`

Gives this response:
`[{'code': 400, 'message': 'operator: This value is not valid.', 'details': {'operator': ['This value is not valid.']}}]`

Also, the "gte" and "lt" operators used to be supported, even if they were undocumented, but stopped being supported some time recently. If I do a GET call to one of my older segments, you can see that it is defined using a "gte" operator:

`"filters": [
            {
                "object": "lead",
                "glue": "and",
                "field": "date_identified",
                "type": "date",
                "filter": "2021-12-01",
                "display": null,
                "operator": "gte"
            }
        ],`

Also, you can specify "greater than or equal" in the UI: 
![image](https://user-images.githubusercontent.com/81978069/144678151-6ed4fd3d-3173-4e82-813a-5117f73cba57.png)
