### ISSUE TITLE
Mautic 3.2.2 Modify contact’s tags in Form Actions disappeared

### ISSUE THREAD

**Issue by suresh-iyengar** [mautic/mautic#9832]
Mautic version is: 3.3.2
PHP version is: 7.3.22

Problem:
I upgraded our Mautic to version 3.3.2 and now the "Modify contact’s tags"option in the Form’s Actions just disappeared.

Log errors: none

Steps I have tried to fix the problem:
Even though it is missing in the dropdown list, I was able to type "Modify contact's tags" in the search box under Form Actions to make it appear. However, on saving it, the tag does not show up. It disappeared.

Please advise on the steps to fix this issue.
Thanks.

**Comment by npracht** [comment]
Hello,

Which type of form are you using ?

**Comment by suresh-iyengar** [comment]
I'm using the Campaign Form.

**Comment by npracht** [comment]
Hi @suresh-iyengar this is what i was guessing. Campaign forms never had this action. You can:
1. Use standalone forms (they have this action)
2. Add the "add tag" action from the campaign behind your form.

Best,

N.

**Comment by jos0405** [comment]
Hello @npracht I checked, and this feature is available in 2.16. It just disappeared in 3+
Is it possible, that it disappeared by mistake? If so, can we reopen it? Maybe it's a quick fix.
![image](https://user-images.githubusercontent.com/4246909/113855435-4c900300-97a0-11eb-9565-39ee15ae388b.png)
