### ISSUE TITLE
20k emails were suddenly sent over the last 24 hours and we can't understand why

### ISSUE THREAD

**Issue by vesper8** [mautic/mautic#9871]
## Bug Description
We enabled email scheduling about 1 week ago.

This is my crontab

```
0,15,30,45 * * * * /usr/bin/php /home/forge/mautic.domain.com/bin/console mautic:segments:update
5,20,35,50 * * * * /usr/bin/php /home/forge/mautic.domain.com/bin/console mautic:campaigns:update
10,25,40,55 * * * * /usr/bin/php /home/forge/mautic.domain.com/bin/console mautic:campaigns:trigger

*/5 * * * * /usr/bin/php /home/forge/mautic.domain.com/bin/console mautic:emails:send

*/10 * * * * /usr/bin/php /home/forge/mautic.domain.com/bin/console mautic:broadcasts:send
```

Then, nothing happened. We didn't schedule any new emails, we didn't even log in or touch Mautic.. nothing weird happened over the last week, then all of a sudden in the last 24 hours we're getting a ton of old emails that started sending.. I think those old emails, still published and still with 'pending' (undelivered) emails are now suddenly sending. SendGrid reports we've sent 20k emails in the last 24 hours.. some of these date back to 2017!

I have no idea why now, why suddenly it started sending in the last 24 hours??

Any help or insight would be appreciated

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 7.4
| Browser |

**Comment by RCheesley** [comment]
Hi @vesper8, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
