### ISSUE TITLE
Question: Confusion with API and Basic Auth

### ISSUE THREAD

**Issue by patricksimonian** [mautic/mautic#9872]
Howdy there,

I had question with regard to using basic auth and the mautic API.  My use case is that I would like to run some jobs in the form shell scripts (in containers) against the Mautic API. For this reason an OAuth user is not ideal. 
 
I've run into the 401 issues as described here #7509.

So my question is, who is the basic user? Is it the Mautic user found in the database or is it the Apache Basic User as described by ` /etc/apache2/.htpasswd`?

Follow up question, are there plans to open up mautic for open api support such as using access tokens (like github does)? This would allow CI/CD pipelines to more effectively use the mautic services.

**Comment by dennisameling** [comment]
Hi @patricksimonian, thanks for your question!

You'll need to use an existing Mautic user when using Basic Auth against the API. Make sure you activate both the API and Basic Auth under Configuration > API settings, and clear Mautic's cache (`rm -rf var/cache`) after that. Then Basic Auth should work.

A PR was just merged which adds support for OAuth2 Client Credentials: https://github.com/mautic/mautic/pull/9837 - this will be in Mautic 4 which is schedule for stable release in May. With Client Credentials you're not interacting as a user but as a machine with Mautic's API, using access tokens. 

In terms of OpenAPI support (if I understand your question correctly): this is planned for Mautic Next Generation (https://www.mautic.org/next-generation), which hopefully will arrive some time in 2022. It will be a full (API-first) rewrite of Mautic. For more details please go to the link above and join us on Slack!

**Comment by jensenhertz** [comment]
I'm having 401 API issue with v4.4.1.

I rm -rf'd var/cache but I'm still getting 401 when trying to access the API. No HTTP Basic popup triggered when I access something like `/api/contacts?limit=1&minimal=1`. Both API and HTTP Basic are enabled.

Any ideas?
