### ISSUE TITLE
Question: how to update the headers for an email template

### ISSUE THREAD

**Issue by gaoxingliang** [mautic/mautic#9873]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Hi, I'm trying to edit / update the email headers (the name and value pair) for an email, but I found this can't be patched by the api:
```
https://developer.mautic.org/?json#edit-email
```
but the name of an email can be updated.
<img width="949" alt="图片" src="https://user-images.githubusercontent.com/3148215/113403390-2998d400-93d9-11eb-9117-916f0383cb00.png">

| Q   | A
| --- | ---
| Mautic version |  - not found in the information page.
| PHP version | 7.0.33
| Browser | any

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by kuzmany** [comment]
You can do it in Advanced tab of create/update email page

![image](https://user-images.githubusercontent.com/462477/113407164-11ab5b00-93ad-11eb-9b44-ef999e785efe.png)

**Comment by gaoxingliang** [comment]
Hi @kuzmany, I mean how to update it by the api: `/api/emails/emailId/edit`.  In the api doc: https://developer.mautic.org/?json#edit-email it said I can use the http patch method to update some field. but I can't update the Custome headers even this field is returned when doing a http get `/api/emails/emailId`

**Comment by gaoxingliang** [comment]
I fixed this by trying to update the emails table directly.
