### ISSUE TITLE
Can't load New Template Email

### ISSUE THREAD

**Issue by an3i** [mautic/mautic#9884]
Hi,

Mautic version: 3.3.2
PHP version: PHP 7.4.16
OS: Centos 7

Steps to reproduce the error: Channels > Emails > when I'm trying to load new template email I get blank page.

Log: [2021-04-06 18:32:53] mautic.CRITICAL: Uncaught PHP Exception RuntimeException: "Unable to write in the cache directory (/var/www/html/app/../var/tmp/twig/2d)." at /var/www/html/vendor/twig/twig/src/Cache/FilesystemCache.php line 61 {"exception":"[object] (RuntimeException(code: 0): Unable to write in the cache directory (/var/www/html/app/../var/tmp/twig/2d). at /var/www/html/vendor/twig/twig/src/Cache/FilesystemCache.php:61)"} []

I already tried to restore/setup file permission but nothing changed.

Thank you!

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)  

Looks like an issue with your cache directory not being writable from the error message.
