### ISSUE TITLE
Change lead field token visual placeholder from strong to span tag

### ISSUE THREAD

**Issue by npracht** [mautic/mautic#989]
Hi guys,

When you insert a lead fiel in the email generator, it's bold (strong tag).
I tried to change it by changing the strong by span tag but by consequence the dynamic values does not work anymore.
I guess the system is looking for a dynamic value in a strong tag.

--> Would it be possible to make it in a span tag? That would avoid the design applied to a strong tag?

Thanks,

N.

**Comment by that0n3guy** [comment]
+1

**Comment by alanhartless** [comment]
I'm not sure I'm following this.  The lead field shown in the editor should be simply visual and should not affect the design of the email sent/previewed.  Are you finding otherwise? If so, can you give an example?

**Comment by npracht** [comment]
@alanhartless,
Anytime i integrate a lead field, it's included in a >strong< tag ----> Consequence the lead field is bold.
Attached screenshots.
![capture d ecran 2015-10-21 a 18 27 22](https://cloud.githubusercontent.com/assets/14075239/10643135/961bb2d4-7821-11e5-9e5c-c34ed8d7b7f2.png)
![capture d ecran 2015-10-21 a 18 27 28](https://cloud.githubusercontent.com/assets/14075239/10643136/96357db8-7821-11e5-90d5-07fcb2890d60.png)

I manually tried to change strong by span, but it breaks the code.

Thanks,

N.

**Comment by alanhartless** [comment]
The bold is only for the visual representation of the token in the builder but should not translate to the actual lead's name being bold when the email is sent. I'll mark this as a UI change request though.

**Comment by dbhurley** [comment]
Fixed
