### ISSUE TITLE
MMS functionality in Twilio Integration

### ISSUE THREAD

**Issue by jobiaya** [mautic/mautic#9890]
Would be awesome to be able to send MMS text messages via the Twilio plugin. Text message alerts with images or emojis typically get a higher click through rate.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/ideas as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems or suggesting ideas :)

**Comment by escopecz** [comment]
This is ready for testing: https://github.com/mautic/mautic/pull/15999
