### ISSUE TITLE
Send Individual Text Messages to Contacts 

### ISSUE THREAD

**Issue by jobiaya** [mautic/mautic#9891]
Is there a way to send individual text messages to contacts? I found a tutorial that shows the capability, but don't see it in Mautic 3.1. Would be a great feature to add if it doesn't exist in open source version.

EXAMPLE: https://www.higher-education-marketing.com/mautic/send-individual-sms#:~:text=To%20send%20text%20messages%20on,many%20texts%20each%20one%20includes.

**Comment by RCheesley** [comment]
Please post this on the forums - see other reply!
