### ISSUE TITLE
IpAddress->isTrackable() returns false 

### ISSUE THREAD

**Issue by pkaltenboeck** [mautic/mautic#9896]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I ran into the problem, that my campaign actions didn't trigger for some users using the activation link. After some debugging and analysis I worked out that it has to do with IPv6 addresses. As long as IPv6 was activated the visits haven't been recognized by Mautic, as soon as I turned IPv6 off and refreshed the page it worked.

Checking the table _ip_addresses_ confirmed my assumption, the ip_details of the corresponding IPv6 address was set to "N;". But not all addresses are affected.

Not working IPv6 addresses:
- `xx:xx:xx:80ee::1`
- `xx:xx:xx:8327:100::168`
- `xx:xx:xx:2512::1`

Working IPv6 addresses:
- `xx:xx:xx:8327:100::768`
- `xx:xx:xx:xx:xx:1873:6b11`

To find the issue I debbuged the code and found the following problem:

The attribute _$this->doNotTrack_ in class _Mautic\CoreBundle\Entity\IpAddress_ contains the loopback addresses (if no other are set):
`array(2) {
  [0]=>
  string(9) "127.0.0.1"
  [1]=>
  string(3) "::1"
}`

In line 203 there is a preg_match check against the _$this->doNotTrack_ list and the ip address, because of the doNotTrack entry **::1**, the regular expression matches for the not working ip adresses (containing ::1) and the _isTrackable()_ method returns **false**.

| Q   | A
| --- | ---
| Mautic version | 3.3.2
| PHP version |  7.4.16
| Browser | independent

### Steps to reproduce
1. access a Landing page using a IPv6 address containing _::1_
2. check Page views -> ip address not present or check database --> ip address marked as N;
 
### Log errors
none

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @pkaltenboeck would you feel confortable offering a PR to the community with your code suggestions ?

**Comment by pkaltenboeck** [comment]
Hi @npracht sorry for the late answer, didn't receive a notification from github. I'll look at it and will create a PR, currently I just uncommented the return statement to fit my needs.

**Comment by npracht** [comment]
Hi @pkaltenboeck would you have time to handle the PR ? :)
