### ISSUE TITLE
wrong update when using batch/edit

### ISSUE THREAD

**Issue by sharon-asana** [mautic/mautic#9897]
Hi,

First of all i wanted to thank everyone that is working on this great tool.

i've recently upgraded to Mautic 3.2.5 and i'm using `/api/contacts/batch/edit` for pushing a very big list of updates for existing contacts.

I'm calling the api using python and it worked with older versions of Mautic (2.15/2.16), but now the updates are very strange, if i put more than 2 contacts in the json, the data is taken from the next contact data that appears in my json.

(i've tested that with Postman to make sure that it's not an issue with my python code)

I've sent the following json:
`[
{"id": 3641650, "subscription_expiry_date": "2022-04-10 18:51", "paid_subscription": "true", "paid_subscription_plan_id": "com.asanayoga.asanarebel.iap.subscription.yearly"}, 
{"id": 3630860, "subscription_expiry_date": "2022-04-10 12:20", "paid_subscription": "true", "paid_subscription_plan_id": "recurly_12m_notrial_v001"},
{"id": 3635996, "subscription_expiry_date": "2022-04-10 14:40", "paid_subscription": "true", "paid_subscription_plan_id": "recurly_12m_notrial_v001"},
{"id": 3637352, "subscription_expiry_date": "2022-04-10 14:53", "paid_subscription": "true", "paid_subscription_plan_id": "ASANA_SUPER_12_MONTH"},
{"id": 3624885, "subscription_expiry_date": "2022-04-10 11:02", "paid_subscription": "true", "paid_subscription_plan_id": "com.asanayoga.asanarebel.iap.subscription.yearly"}
]`

and for example for contact id `3641650` i see the `subscription_expiry_date` of contact `3630860`.

Could someone have a look at that and tell me what am I doing wrong?

Thanks.
Sharon.

**Comment by dennisameling** [comment]
Hi @sharon-asana, thanks for reporting this issue! I've transferred it to the main `mautic/mautic` repo since the API library is for PHP only. Since you mentioned it's also happening when you try with Postman (which directly calls the API), this repo is more appropriate and has more eyes looking at it.

Unfortunately we're a bit short on community capacity currently, so I'm going to mark this as `Needs triage` for others to look into this and try to reproduce the issue.

**Comment by sharon-asana** [comment]
Hi @dennisameling , thank you for the quick response, looking forward to see that being fix

**Comment by Rigiytip** [comment]
Hi! I caught this bug too. I think problem is in this row:
https://github.com/mautic/mautic/blob/a16eb83f6cff0d3c5ea39bc172a5eb262ce2616b/app/bundles/ApiBundle/Controller/CommonApiController.php#L276

because order of entities is not like order of parameters.

I changed this part to:

```
        $entities    = $this->getBatchEntities($parameters, $errors, false, 'id', null, false);

        foreach ($parameters as $key => $params) {
            $method = $this->request->getMethod();
            $entity = (isset($entities[$params['id']])) ? $entities[$params['id']] : null;
```

**Comment by riazanovslv** [comment]
I've encountered this too. Is it possible to apply this https://github.com/mautic/mautic/issues/9897#issuecomment-853817582 fix?
