### ISSUE TITLE
Custom HTML content tokens in Email and Page builders

### ISSUE THREAD

**Issue by lance-spurgeon** [mautic/mautic#99]
We would want the ability to create custom tokens that can be dragged and dropped into the builder? Or maybe a button in the editor that opens a dialogue where you can manage/insert predefined text blocks.

Is when the deciding factor for when to send an email with an unsubscribe link versus one without? Or are you wanting to build some custom templates with the text hardcoded?

https://www.mautic.org/community/index.php/117-personalised-email-templates/0#p457

**Comment by RCheesley** [comment]
+1 from me on this one, Quoteroller does this really nicely with a "content library" which you can use to recycle content.

I'm often having to copy/paste code blocks from one email to another which is time consuming and error-prone!

**Comment by Shirkit** [comment]
So there's currently no way for me to define once a {custom token} and use on the builder without using the API?
