### ISSUE TITLE
V3 Feature regression: "Tags" filter missing on Dynamic Web Content [$65 awarded]

### ISSUE THREAD

**Issue by stevedrobinson** [mautic/mautic#9904]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Mautic V2 allowed Tags to be used as a filter type for dynamic web content. This filter type is missing in Mautic V3.

| Q   | A
| --- | ---
| Mautic version | 3.2.5
| PHP version | 7.4
| Browser | N/A

### Steps to reproduce
1. Create new Dynamic Web Content (not campaign based)
2. On the filters tab, attempt to add a tags filter type

### Dropdown in 2.16
![image](https://user-images.githubusercontent.com/866855/114779419-b88fdf80-9d3b-11eb-9c0a-295695bb3bb0.png)

### Dropdown in 3.2.5
![image](https://user-images.githubusercontent.com/866855/114779515-d78e7180-9d3b-11eb-82f4-3b84f7003627.png)

**Comment by npracht** [comment]
@stevedrobinson as far as i remember it has been removed from UI because it was not a supported feature. So just there by "error".

Are you sure this is working in 2.x version ?

**Comment by stevedrobinson** [comment]
@npracht 100% certain it worked. We were actively using it.

**Comment by alanhartless** [comment]
Looks like there was special handling for tags so this is a regression introduced in https://github.com/mautic/mautic/pull/9260

https://github.com/mautic/mautic/blob/8dc40b4fb767a81bcaeb9292b85861a6822eb9f7/app/bundles/DynamicContentBundle/Helper/DynamicContentHelper.php#L242
https://github.com/mautic/mautic/blob/0f6bbbb3579f5a33a8264fd271b7e3881cc0b561/app/bundles/EmailBundle/EventListener/MatchFilterForLeadTrait.php#L97

**Comment by stevedrobinson** [comment]
I put a small bounty on this on BountySource.

**Comment by kuzmany** [comment]
Probably this should fixed it https://github.com/mautic/mautic/pull/10067

**Comment by RCheesley** [comment]
@all-contributors please add @stevedrobinson for bug

**Comment by stevedrobinson** [comment]
@RCheesley This bug is back. Tags is missing again.
