### ISSUE TITLE
Health Plugin does not work in mautic 3.* version

### ISSUE THREAD

**Issue by 3birds-ronak** [mautic/mautic#9906]
We have installed the mautic 3.2.0 version and installed the health plugin but we are not finding any configuration part of the plugin and also we did not find of health plugin document file.

please help me out or please provide solutions as soon as possible.
I hope we will provide me some support for the plugin.

https://github.com/TheDMSGroup/mautic-health/

**Comment by RCheesley** [comment]
Hi there, 

This relates to a third party plugin, not to Mautic.

As you have already raised an issue on the relevant repo I will close this issue.
