### ISSUE TITLE
Cloning a form duplicates the submit button

### ISSUE THREAD

**Issue by escopecz** [mautic/mautic#991]
Form clones has duplicated Submit button. There is no way how to delete the duplicated button.
![mautic-form-submit-duplicated](https://cloud.githubusercontent.com/assets/1235442/10338014/dabbb5e8-6d03-11e5-8b92-ead4df329cbb.png)

**Comment by escopecz** [comment]
I cannot recreate the issue on the latest GH staging. It'd been probably solved in some merged PR.

**Comment by duduric** [comment]
This is happening to me in the latest version v1.2.3. Actually, all the fields got merged. I suspect it's related to cloning but keeping the same internal name, but couldn't replicate. It happened once in a older version too, seems random.

**Comment by escopecz** [comment]
Here is the bug described more extensively: https://github.com/mautic/mautic/issues/1267
