### ISSUE TITLE
Tag added to anonym visitor ID, instead of the identified contact

### ISSUE THREAD

**Issue by imihandstand** [mautic/mautic#9910]
**Originally, this is how it should work:** 

1. A visitor visits a page with a Mautic-form, a new anonym user gets created (let's say anonym visitor-id 169)
2. After he **submits** the form, he gets an **email** with a link (for double-optin)
3. He clicks the **link**, which leads him to an **"Email confirmed"-page**
4. This page adds a **tag** "_DoubleOptin: Finished_", because of:
`mt('send', 'pageview', { 'tags': 'DoubleOptin: Finished' });`

## Bug Description
However, I just realized this is not working anymore. Because now, after submitting the form, a new identified visitor id (let's say identified visitor 170) get's created.

This is a big problem. Especially because if now the new subscriber clicks the link in the email, **the tag "_DoubleOptin: Finished_" will be attached to the ANONYM visitor 169, instead of the identified contact 170**!

So, at visiting the Email-Confirmed-Page, this happens:

> **Anonym visitor 169:**
> -- "Page hit: 'Email confirmed'" added
> -- Tag "DoubleOptin: Finished" added
> 
> **Identified visitor 170**
> -- "Page hit: 'Email confirmed'" added
> -- But no tag added

**Btw, I now realized that for every single new page-view (any page of my site), Mautic creates a new anonym visitor ID.**

**My settings:**
- Identify visitor by tracking url: Yes
- Anonymize IP: yes (but the problem is even with not anonymized IP)
- I discovered this issue today with Mautic v3.2.5, upgraded it a few hours ago to 3.3.2 to hopefully solve it, but no luck
- **BROWSERS**: The issue is in Opera and Safari, but not in Firefox, Chrome, Edge, IE and Firefox Mobile Android

| Q   | A
| --- | ---
| Mautic version | 3.2.5 and 3.3.2
| PHP version | 7.3.27
| Browser | Opera, Safari (but not: Firefox, Chrome, Edge, IE, Firefox Mobile Android)

**Comment by imihandstand** [comment]
After 4 days of testing, I solved it.

**There were 2 problems:**
1.) Some browsers (like Safari) forbid cross-site tracking regarding cookies
2.) The "_Identify visitor by tracking url_" feature of Mautic doesn't seem to work correctly

**How I solved it:**
...By telling Mautic which email-address that "new visitor" is. For this, 2 things are needed:

- The **link "_Click here to confirm your email-address_"** in the email "_Please confirm your email-address_" must contain the **email-token** (so the link will be like website.com/confirmed?email=example@example.com )

- **Mautic's Javascript-tracking-code** must contain this:
`mt('send', 'pageview'<?php if ($_GET["email"]) { echo ", { , 'email': '" . $_GET["email"] . "'}"; } ?> );`
...instead of just this:
`mt('send', 'pageview');`

**So the script gets the Email-Address from the URL and helps so Mautic to correctly identify the visitor.**

**Comment by npracht** [comment]
Hello @imihandstand,

>1.) Some browsers (like Safari) forbid cross-site tracking regarding cookies

Yes this is known and not a mautic issue. Just a standard of cookies for now 1 year. You need to have your mautic instance on same domain of your website (to create a first party cookie). And your website pages on same domain as well.

On top of that, if the visitor is in incognito mode or stuff like that, the tracking will be broken (logic because each tab has a different unique cookie ID).

So I'd conclude there is no bug, just technical tracking limits due to browser behavior.

You confirm or you see still an issue ?
Thanks a lot for your contribution :)

**Comment by imihandstand** [comment]
> Yes this is known and not a mautic issue. Just a standard of cookies for now 1 year. You need to have your mautic instance on same domain of your website (to create a first party cookie). And your website pages on same domain as well.

Yes, I already realized that the cookie-problem isn't Mautic's fault.

> So I'd conclude there is no bug, just technical tracking limits due to browser behavior.
> You confirm or you see still an issue ?

I still think, that the "Identify visitor by tracking url" isn't really working as supposed, as it should be able to tell without cookies and without IP to which email-address a link from a sent email (sent via the form) belongs to. But with my PHP-workaround my double-optin-process works, so my issue can be closed.

> Thanks a lot for your contribution :)

You are welcome - hope it will help somebody in the future :)

**Comment by npracht** [comment]
👍🏽
