### ISSUE TITLE
Mautic "Add Contacts" Bug?

### ISSUE THREAD

**Issue by jamesjosh912** [mautic/mautic#9912]
Hello, I am trying to add contacts, but I am getting this error. Why is it asking for a password here? Is this some glitch, because all of the fields are clearly filled in.
![password blank](https://user-images.githubusercontent.com/68710900/115169965-78a76000-a08d-11eb-98d1-4ca4dd744ed1.png)

**Comment by RCheesley** [comment]
Hi there,

You should be seeing the fields below for you to match - looks like the import file is not working as it should.

Please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by jamesjosh912** [comment]
Ok, thank you. How do I ask a question on there? There is no obvious "post a question" button.
