### ISSUE TITLE
add more segment operators to some field types (other than text type)

### ISSUE THREAD

**Issue by RehanNischal** [mautic/mautic#9913]
![Capture4](https://user-images.githubusercontent.com/43839944/115237909-badaab00-a13a-11eb-8901-648b69c8812e.PNG)
When I use regex filter while creating a segment, I am unable to use characters in the input field for the data types other than the text field.

**Comment by dsp76** [comment]
seems to be related to https://github.com/mautic/mautic/issues/9487 ...

**Comment by RehanNischal** [comment]
Yes, it is related to that. Any solutions yet?

**Comment by namratasaun** [comment]
hello, having a similar issue.
Any solutions for it yet @RehanNischal @dsp76

**Comment by npracht** [comment]
Hello all !
This is not an issue but an improvement you ask (add more operators to some type of fields).

Is anyone of you ready to help ? You could suggest a community contribution by doing a PR ?

Thanks !

**Comment by namratasaun** [comment]
> Hello all !
> This is not an issue but an improvement you ask (add more operators to some type of fields).
> 
> Is anyone of you ready to help ? You could suggest a community contribution by doing a PR ?
> 
> Thanks !

hello @npracht . Sure will try to code the solution.
Just wanted to confirm that I am able to see the regexp filter in segment but you mean that it is not complete and we can pick it up and complete it.
Just confirming as I can already see the filter even when the type is number, date or select. Just that cannot type my regular expression.

**Comment by namratasaun** [comment]
> > Hello all !
> > This is not an issue but an improvement you ask (add more operators to some type of fields).
> > Is anyone of you ready to help ? You could suggest a community contribution by doing a PR ?
> > Thanks !
> 
> hello @npracht . Sure will try to code the solution.
> Just wanted to confirm that I am able to see the regexp filter in segment but you mean that it is not complete and we can pick it up and complete it.
> Just confirming as I can already see the filter even when the type is number, date or select. Just that cannot type my regular expression.

@npracht ? i can see the regexp filter, so i believe it is not compatible with other fields?

**Comment by npracht** [comment]
I think most of everything is possible. We "just" need to extend/code it ?
