### ISSUE TITLE
🚨 Potential Security Vulnerability - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [mautic/mautic#9914]
#### ⚠️ Potential Vulnerability in mautic

👋 Hello, @alanhartless, @escopecz, @kuzmany - @ranjit-git has disclosed a potential vulnerability in your repository. To validate or invalidate this potential vulnerability, please visit https://huntr.dev/bounties/2-other-mautic and join our community in helping secure open-source code.

---

#### ☎️ Need further support?

Come and join us on our [Discord](https://huntr.dev/discord) and a member of our team will be happy to help! 🤗

cc - @JamieSlome

**Comment by RCheesley** [comment]
Hi there, please follow our process for responsible disclosures: https://www.mautic.org/mautic-security-team/how-to-report-a-security-issue. Thanks!
