### ISSUE TITLE
add error message when importing unexpected values in pre-created select fields (state, country, etc.)

### ISSUE THREAD

**Issue by dsp76** [mautic/mautic#9915]
## Bug Description
We imported a test set of data into Mautic. "State" is a predefined set of data. By mistake we imported "Freistaat Sachsen" instead of the predefined "Sachsen" into the system (same with "Freistaat Bayern" instead of "Bayern"). 
![image](https://user-images.githubusercontent.com/1241376/115291738-642e9a80-a155-11eb-8561-59cfc628ae3b.png)

Now this data is written into the related contact field but can't be filtered in any condition in segments
![image](https://user-images.githubusercontent.com/1241376/115291943-a5bf4580-a155-11eb-9c15-c9c17f74b898.png)

nor in campaigns
![image](https://user-images.githubusercontent.com/1241376/115292135-df904c00-a155-11eb-86f0-2548b9833b5d.png)

Only workaround is to make use of a regexp condition for campaigns. Workaround doesn't work in segments due to https://github.com/mautic/mautic/issues/9913
![image](https://user-images.githubusercontent.com/1241376/115294092-6d6d3680-a158-11eb-949d-7732b4030b6c.png)

| Q   | A
| --- | ---
| Mautic version |  3.3.2
| PHP version |  7.3
| Browser | any

### Steps to reproduce
1. Import test data with a state not predefined in the states list of Mautic
2. Try to select it within segments or campaigns
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RehanNischal** [comment]
Any updates ?? is it solved yet?

**Comment by npracht** [comment]
Hi there,

You should not import wrong data in a select type field... This is the issue.
I'll rename the issue to "add error when importing wrong values in pre-created select fields as `state`". For me this is the issue, the UI should not let the user add wrong data in the field.
