### ISSUE TITLE
Where do I post a question on https://forum.mautic.org/c/support/8 ???

### ISSUE THREAD

**Issue by jamesjosh912** [mautic/mautic#9916]
Hi,

I am trying to post a support question on the mautic support page, but I see no "post question" button? Where is it?

https://forum.mautic.org/c/support/8

**Comment by RCheesley** [comment]
You have to be active for a minimum amount of time, per the warning in the blue box at the top. Once you are ranked up you'll get a PM from Mautibot and a blue button will show to allow you to post.
