### ISSUE TITLE
500 Internal Server Error when creating a custom unsubscribe page

### ISSUE THREAD

**Issue by svenkubiak** [mautic/mautic#9918]
**Mautic version:** 3.3.2
**PHP version:** 7.4
**Browser:** Chrome 90.0.4430.72

## Bug Description
I am running into an issue, when trying to add a custom unsubscribe page. I either have a blank page or the moment I add the "Preferred channels" I get an 500 Internal Server Error.

- I have a landing Page which is set "Published" and "Set as preference center page" 

![Bildschirmfoto 2021-04-20 um 14 16 28](https://user-images.githubusercontent.com/67564/115394488-1a8c9100-a1e3-11eb-8b53-d1e0b89f07aa.png)

- In mautic configuration -> email settings "Show contact pereferences settings" is set to "yes"

![Bildschirmfoto 2021-04-20 um 14 17 47](https://user-images.githubusercontent.com/67564/115394595-38f28c80-a1e3-11eb-95d6-b70a22f09ce5.png)

- In the email channel the landing page is set to "preference center page"

![Bildschirmfoto 2021-04-20 um 14 18 48](https://user-images.githubusercontent.com/67564/115394728-5de6ff80-a1e3-11eb-91cc-339a5b226e65.png)

Afaik, this is correct if I look at other issues around a 500 regarding this topic.

The landing page is created using the builder using "Blank page", where I added the "Preferred Channel" Slot and "Save preferences".

![Bildschirmfoto 2021-04-20 um 14 21 34](https://user-images.githubusercontent.com/67564/115395425-288ee180-a1e4-11eb-9150-c8180fe121a4.png)

If I leave it like that, I get a 500 and the below log entry. If I remove the "Preferred Channel" Slot from the template, I'll get a blank page without any log entry.

### Steps to reproduce
1. See above description
 
### Log errors
```
[2021-04-20 14:07:11] mautic.NOTICE: PHP Notice - Undefined index: preferred_channel - in file /var/www/mautic/vendor/symfony/form/FormView.php - at line 113 {"name":"preferred_channel"} []
[2021-04-20 14:07:11] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Symfony\Bundle\FrameworkBundle\Templating\Helper\FormHelper::row() must be an instance of Symfony\Component\Form\FormView, null given, called in /var/www/mautic/app/bundles/CoreBundle/Views/Slots/preferredchannel.html.php on line 15 at /var/www/mautic/vendor/symfony/framework-bundle/Templating/Helper/FormHelper.php:149)"} []
```

**Comment by npracht** [comment]
@svenkubiak hello !

As far as i remember, in your global configuration, you need to enable more features of PC. I think you need to add channel preference in your case because you use this slot in your built PC. Careful, you need to enable in configuration all info you use in PC.

please confirm :)

**Comment by svenkubiak** [comment]
@npracht Thanks for the feedback.

I have added "channel preference" in the global configuration. The result is a blank page.

And just to confirm, this is how my global config looks:

![image](https://user-images.githubusercontent.com/67564/115739028-df7a9100-a38d-11eb-8e79-a40c87b9922f.png)

If I switch "channel preferences" back to "no", i'll get the error 500 page.

**Comment by npracht** [comment]
Ok, "better". Can you try to add the channel slot in your PC ?

**Comment by svenkubiak** [comment]
@npracht Sure. Once I do, I'll get the Error 500 as mentioned above.

**Comment by npracht** [comment]
Okay, i don't know much more.. I'll tag this as a bug that need to be addressed.

**Comment by spencerthayer** [comment]
Seems like the 500 error is plaguing Mautic.

**Comment by dsp76** [comment]
We can confirm this bug in several instances as well. Seems to be an important bug for long time user - still preventing them to update to 3.3

Is this bug getting any love?

**Comment by RCheesley** [comment]
Hmm we have had a few of these cropping up, @mohit-rocks it looks like the other 500 errors that you fixed. 

Can someone test in 4.0.0-rc and see if it's still happening? If so hopefully it's a relatively quick fix!

**Comment by luigicarlini1988** [comment]
Hi, we are facing the same problem on Mautic v3.3.4
followed all the steps provided in Mautic documentation to create a Preference Center page, but we receive a 500 error message when clicking on Unsubscribe button. Are there any news on this Bug?
