### ISSUE TITLE
Pagebreaks won't work if using the "Form"-Focus Item

### ISSUE THREAD

**Issue by LeonOltmanns** [mautic/mautic#9923]
## Bug Description
When using pagebreaks in a Mautic form to switch from one page to another all the form-fields will just be piled up on a single page instead of being displayed  in multiple pages. 

If you use the preview function to display a form with pagebreak, they show up and work normally.

| Q   | A
| --- | ---
| Mautic version | 3.3.2
| PHP version | 7.4
| Browser | Chrome / Firefox

### Steps to reproduce
1. Create a Form
2. Use the Pagebreak-Fields to seperate the form into multple pages
3. Create a Focus Item with the type "Form"
4. Select the Form created in step 1
5. Embed the Focus Item on a Landing Page 
6. See that the Pagebreak wont be displayed
 
### Log errors
-none

### Screenshots:

Using Preview:
![Preview](https://user-images.githubusercontent.com/55587275/115571977-c7d4d700-a2bf-11eb-8ec2-16dfb0276934.png)

![Screenshot at Apr 21 16-38-23](https://user-images.githubusercontent.com/55587275/115572262-07032800-a2c0-11eb-9bca-c8cacce13a4e.png)

Using Focus Item:
![Focus Item](https://user-images.githubusercontent.com/55587275/115571989-c99e9a80-a2bf-11eb-83aa-cb30b975d17b.png)

**Comment by kuzmany** [comment]
Related PR https://github.com/mautic/mautic/pull/9737

**Comment by npracht** [comment]
@oltmanns-leuchtfeuer can you please test the PR and confirm it fixes your issue ?

**Comment by LeonOltmanns** [comment]
@npracht Will do! :)

**Comment by RCheesley** [comment]
This is a duplicate of a **very** old issue I raised back in 2016 😱  #2992 so closing this issue!
