### ISSUE TITLE
Date range form in segments or reports does not trigger ajax request

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#9924]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...
I found strange issue with date range form.

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. Logout and login from Mautic
2. Go to segments by click on left menu
3. Open segment detail by click on segment
4. Try change date in date range form of graph and try click submit
5. Ajax request is not provided, just loader on the button run

![image](https://user-images.githubusercontent.com/462477/115668626-a15a7e80-a347-11eb-91af-867f2e0d1742.png)

6. If I refresh browser, then start works everywhere
7.  Everytime when you logoud/login happen again

### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by adiux** [comment]
I looked into it. It is only the Segments, the Dashboard filter works fine.

I would have to debug some more. @kuzmany do yo know how this data-toggle ajax works? Which function is called? It looks like it is not calling `Mautic.ajaxifyLink`
![image](https://user-images.githubusercontent.com/13075514/115949008-0c37c100-a4d2-11eb-8c8f-0a56401a823b.png)

**Comment by kuzmany** [comment]
I found ajaxifyForm method https://github.com/mautic/mautic/blob/features/app/bundles/CoreBundle/Assets/js/6.forms.js#L46

**Comment by adiux** [comment]
I think this function initializes the ajax setup. But when I click on the button, we dont go to the ajaxifyForm function. Also not on the Dashboard.
![image](https://user-images.githubusercontent.com/13075514/115951646-1661bb80-a4e2-11eb-820f-1ad7719354b9.png)

**Comment by adiux** [comment]
I figured out that this function is called when it works. But it is not called when you click it for the first time after the login 
![image](https://user-images.githubusercontent.com/13075514/115952103-8ec97c00-a4e4-11eb-9b73-a0da491fb97e.png)

**Comment by cesaroito** [comment]
My Mautic has this issue too. I don't get to use filter on reports and segments. I have to disable and use Global Date Range on my Dashboard.

**Comment by kuzmany** [comment]
@cesaroito 

> I have to disable and use Global Date Range on my Dashboard.

What option do you mean?

**Comment by kuzmany** [comment]
Fixed with https://github.com/mautic/mautic/pull/10421

**Comment by kuzmany** [comment]
Close favor to https://github.com/mautic/mautic/pull/10421
