### ISSUE TITLE
Mautic command cache:clear throws Exception when /tmp directory is not accessible

### ISSUE THREAD

**Issue by pedrodejesus** [mautic/mautic#9928]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The constructor of the Symfony class \Symfony\Component\Cache\Adapter\FilesystemAdapter expects a `$directory` parameter, and when it's not provided it uses the /tmp directory.

Usually on shared environments the /tmp dir isn't avaliable for usage. On my case, we have many users that use /tmp/user.

| Q   | A
| --- | ---
| Mautic version | 3.3.1
| PHP version | 7.4.16
| Browser | Any

### Steps to reproduce
1. Download Mautic on an Unix environment without access to /tmp
2. Run the cache clear command: `php path/to/your/mautic/instalation/folder/bin/console cache:clear`
 
### Log errors
```
php7.4 bin/console c:c -vvv

 // Clearing the cache for the prod environment with debug false                                                        

In CacheClearSubscriber.php line 55:
                                             
  [Exception]                                
  Failed to clear FilesystemTagAwareAdapter  
                                             

Exception trace:
  at /home/pedro/mkt/app/bundles/CacheBundle/EventListener/CacheClearSubscriber.php:55
 Mautic\CacheBundle\EventListener\CacheClearSubscriber->clear() at /home/pedro/mkt/vendor/symfony/http-kernel/CacheClearer/ChainCacheClearer.php:41
 Symfony\Component\HttpKernel\CacheClearer\ChainCacheClearer->clear() at /home/pedro/mkt/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:111
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /home/pedro/mkt/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /home/pedro/mkt/vendor/symfony/console/Application.php:1005
 Symfony\Component\Console\Application->doRunCommand() at /home/pedro/mkt/vendor/symfony/framework-bundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /home/pedro/mkt/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at /home/pedro/mkt/vendor/symfony/framework-bundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/pedro/mkt/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /home/pedro/mkt/bin/console:43
```

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by PierreAmmeloot** [comment]
Hello all,

I have the same problem today on Mautic 4.2.0 and 4.2.1 when until now everything worked fine.

When I run the command : 
`php bin/console mautic:update:find`

I have the error message : 

```
 // Clearing the cache for the prod environment with debug false                                                        


In CacheClearSubscriber.php line 55:
                                             
  Failed to clear FilesystemTagAwareAdapter  
                                             

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

I have not changed anything on my side.
Where does this come from?

P.S.: @RCheesley Is it possible to re-open this issue?

Pierre

**Comment by PierreAmmeloot** [comment]
@RCheesley the bug still exists, does this issue really have to be closed automatically?

**Comment by mabumusa1** [comment]
@PierreAmmeloot let's get it merged.
