### ISSUE TITLE
 <link rel=preload> for the mautic CSS 

### ISSUE THREAD

**Issue by chente38** [mautic/mautic#9938]
Hi,

i'm using mautic forme integrated in m website with the scipt given by mautic.

I received alert of google that told me that I should use <link rel=preload> for the mautic CSS => media/css/modal.min.css

is there a way to solve this issue, please?

thanks in advance

<a href="https://imgbb.com/"><img src="https://i.ibb.co/SvZJJ8K/Screenshot-2021-04-26-112450.jpg" alt="Screenshot-2021-04-26-112450" border="0"></a>

//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @chente38 !
Thanks a lot for your message but it is incomplete. You miss the image, the mautic version, etc.

Please share a better feedback. Thanks a lot.
