### ISSUE TITLE
Mail attachment not sent

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#9939]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
This same: https://github.com/mautic/mautic/issues/8461

| Q   | A
| --- | ---
| Mautic version | 3.3.2
| PHP version | 7.4
| Browser | Edge

### Steps to reproduce

1. Create a template email.
2. Attach a file to the email on the advanced tab, send it through a campaign or manually to a user
3. The email is received, but, the attachment is not attached.
4. If a test mail is sent from the email template page, an attachment is sent.
5. If we send a direct email from the contacts tab, no attachment is sent.

 
### Log errors
No errors.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @biggala2310 !
Thanks for that feedback. Can you please tell which email transport you use ?
