### ISSUE TITLE
Header too large preventing sends of segment emails on Mailgun

### ISSUE THREAD

**Issue by imihandstand** [mautic/mautic#9941]
## Bug Description
Usually I send out emails just via campaigns. Now I wanted to try out segment-emails, but they fail to send.

**It says "Pending" forever:**

![Screenshot 2021-04-27 at 17 00 30](https://user-images.githubusercontent.com/44979581/116268480-a40d0780-a77d-11eb-8623-ebfe9ca2fdfe.png)

When I go the the email and click the "Send" button in the top-right corner, it says "There are 73 pending contacts":

![Screenshot 2021-04-27 at 17 00 45](https://user-images.githubusercontent.com/44979581/116268670-d3237900-a77d-11eb-9903-16c332f728d8.png)

If I now click the blue "Send" button, here, I get this: **"0 sent and 73 failed"**:

![Screenshot 2021-04-27 at 17 01 02](https://user-images.githubusercontent.com/44979581/116268799-edf5ed80-a77d-11eb-9492-a0b5e52ed866.png)

**Every other Email-sending (campaigns, test-emails) seems to work fine** (note: I'm using the MailGun API). btw, I'm not using the email-queue, "_How should email be handled?_" is set to send immediately.

I tried **following commands** too, but none of them helped:
- php bin/console swiftmailer:spool:send (the "var/spool" folder is empty)
- php bin/console mautic:emails:send
- php bin/console mautic:broadcasts:send

| Q   | A
| --- | ---
| Mautic version | 3.3.2
| PHP version | 7.3.27

### Steps to reproduce
1. Create a segment which has 73 (or whatever) contacts
2. Create a segment-email, attach it to that created segment and publish the email
 
### Log errors
This is the error in the log:
> [2021-04-27 16:12:11] mautic.ERROR: [MAIL ERROR] Client error: `POST https://api.eu.mailgun.net/v3/MY-MAUTIC-DOMAIN/messages` resulted in a `400 Bad Request` response: <html> <head><title>400 Request Header Or Cookie Too Large</title></head> <body> <center><h1>400 Bad Request</h1></ce (truncated...)  (send); HERE-ARE-THE-73-EMAILADDRESSES {"exception":"[object] (Swift_TransportException(code: 0): Client error: `POST https://api.eu.mailgun.net/v3/_MY-MAUTIC-DOMAIN_/messages` resulted in a `400 Bad Request` response:\n<html>\r\n<head><title>400 Request Header Or Cookie Too Large</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></ce (truncated...)\n at /home/MY-MAUTIC-PATH/mautic/app/bundles/EmailBundle/Swiftmailer/Transport/AbstractTokenArrayTransport.php:300)"} []

**Comment by RCheesley** [comment]
@mabumusa1 I think you have been doing some work with Mailgun - have you come across this bug "400 Request Header Or Cookie Too Large"?

**Comment by imihandstand** [comment]
btw, here is a proof that both the **"_Send Example_"** for that very same segment-email and the **"Send test email"** (at "Configuration => Email Settings => Mail Send Settings") are working fine:

![Screenshot 2021-04-27 at 18 32 39](https://user-images.githubusercontent.com/44979581/116278919-3cf45080-a787-11eb-8859-daa99a18a79a.png)

So the MailGun-connection and sending seems to be fine.

However, I tried now sending the pending segment-email with the **SendGrid API** and it worked fine - no errors, and the 73 emails were sent (and arrived).

EDIT: btw, for MailGun API I use this: https://github.com/stars05/mautic-mailgun-mailer-plugin

**Comment by imihandstand** [comment]
Update: Unfortunately campaign-emails don't seem to work perfectly either. The campaign sent an email to some, but not to all. Same error.

**Comment by imihandstand** [comment]
I stop using MailGun, so I close this issue.
