### ISSUE TITLE
Invalid default Site URL leads to 404 when loading media/js/mautic-form.js on other sites

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#9942]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
I have installed a fresh install of Mautic 3.3.2. Running on Debian GNU/Linux 10 (buster),  nginx/1.19.10 with php-fpm7.4, PHP 7.4.16 and mysqld 8.0.24. When installing I did everything to fix recommendations on the install page so there was no more recommendations. After installation and trying to insert a form created in Mautic to another site there is a load error
![mautic-bug1](https://user-images.githubusercontent.com/56940608/116301396-4807aa80-a7a0-11eb-9d41-5972ddf950e4.png)
If you try to go manually to the link https://mautic.example.com/index.php/media/js/mautic-form.js you will get
![mautic-bug2](https://user-images.githubusercontent.com/56940608/116302020-fc093580-a7a0-11eb-9661-1586d327a7d2.png)

This is because the default site has index.php added in the Site URL by default.
![mautic-bug3](https://user-images.githubusercontent.com/56940608/116302244-3c68b380-a7a1-11eb-9eef-df6da364e2a4.png)

My relevant nginx config

``` 
server_name mautic.example.com
index index.php index.html
root /var/www/mautic/
```

/var/www/mautic/ is the location where all mautic files are.

Looking at the other paths in the 
Path to the cache directory : /var/www/mautic/app/../var/cache
Path to the log directory: /var/www/mautic/app/../var/logs

they look invalid:
![mautic-bug4](https://user-images.githubusercontent.com/56940608/116302933-10016700-a7a2-11eb-9ee4-c897d2e9f03b.png)

also 
Path to the asset directory: /var/www/mautic/app/../media/files
![mautic-bug5](https://user-images.githubusercontent.com/56940608/116303712-4d65f480-a7a2-11eb-92fa-45a6fa9b5c9e.png)

and  Mail Send Settings: 
Path to the email queue directory: %kernel.root_dir%/../var/spool
![mautic-bug6](https://user-images.githubusercontent.com/56940608/116304348-c36a5b80-a7a2-11eb-9f73-a7427a50c76a.png)

If we look into System Info the Folder & File Permissions look fine.
![mautic-bug7](https://user-images.githubusercontent.com/56940608/116304675-1e9c4e00-a7a3-11eb-9b7c-771cb5fba869.png)

I have also upgraded Mautic from 3.3.2 to 3.3.3 version to see if any of this was fixed but no changes.

There should at least be a warning that it's not recommended to have mautic.example.com/index.php as a default Site URL to avoid this problems in the future.

| Q   | A
| --- | ---
| Mautic version | 3.3.2 and 3.3.3
| PHP version | PHP 7.4.16
| Browser | any

### Steps to reproduce
1. Install Mautic on Debian GNU/Linux 10 (buster),  nginx/1.19.10 with php-fpm7.4, PHP 7.4.16 and mysqld 8.0.24 with default settings.
2. Create a form on Mautic and try to insert form into another site.
3. Your form will not load properly as https://mautic.example.com/index.php/media/js/mautic-form.js it's not valid location for mautic-form.js.
 
### Log errors
Noted above.

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @dynamiccontent ! Thanks for your message. Nevertheless, following the steps we are unable to reproduce.
Please join the forums or slack to find help from community members about your configuration issue.
