### ISSUE TITLE
Cannot Create Email Channel

### ISSUE THREAD

**Issue by jamesjosh912** [mautic/mautic#9943]
I cannot create an email channel using the "new" button in the top right corner of the "channels" ---> "emails" section. The button doesn't respond. I tried deleting the cache folder in WINSCP, but it did not help.

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
