### ISSUE TITLE
Link to form uploaded file not working

### ISSUE THREAD

**Issue by ghost** [mautic/mautic#9946]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Email with form results doesn't contain correct link to file.
It looks example as:
file: /forms/results/file/9/file  

This bug is new. I hadn't this problem on 2.16.3

| Q   | A
| --- | ---
| Mautic version | 3.3.2
| PHP version | 7.4
| Browser | Edge

### Steps to reproduce
1. Create new file field in form and publish
2. Set up notification
3. Upload file by a form
4. Link in notification contains only middle part of link
 
### Log errors
No logs

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @biggala2310 can you please try https://github.com/mautic/mautic/pull/9233 and add your review ?
I think it might fix you issue.

**Comment by jos0405** [comment]
Yeah, the mentioned PR fixes it.
![image](https://user-images.githubusercontent.com/4246909/132681432-e89709c7-984c-426e-b1d9-f6eed9c7bd73.png)
Tested, works.

**Comment by jos0405** [comment]
Actually, it's a bit weird, that "filename" is the filename. Seems to be hardcoded...

**Comment by RCheesley** [comment]
Closing this issue as the PR to fix it has been addressed.
