### ISSUE TITLE
Implementing Tags Reporting

### ISSUE THREAD

**Issue by edutj** [mautic/mautic#995]
In the version 1.2.0 is not possible to view tags inside the reports area. This feature is important due to the functionality that can be applied to tags.

**Comment by npracht** [comment]
Hi,

This is true, in the contact type report. The "field" `tags` is not displayable as a column of the contact.
It would be great to be able to select this field here:
![capture d ecran 2016-09-23 a 09 45 27](https://cloud.githubusercontent.com/assets/14075239/18778017/824fd572-8172-11e6-975c-ea044599a4ad.png)

N.

**Comment by marcchristopher** [comment]
Any news on this? Is this feature being worked on? This seems indispensible for exporting the database of contacts to a CSV file, e.g. for doing backups or for migrating to another server. (Same goes, by the way, for the field `stage`.)

**Comment by drimlike** [comment]
+1
Hello, is it going to be released soon? This feature would be a great improvement!
