### ISSUE TITLE
Buttons in modal window in wrong order

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#9950]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
The more details the better...
Buttons group was re-aranged by this PR https://github.com/mautic/mautic/pull/9895

But now in the modal are in revered order like we used to in Mautic 3

![image](https://user-images.githubusercontent.com/462477/116557703-fc1f4780-a8fe-11eb-95bb-afab5d6569ab.png)

I click to cancel maybe hundreds time, because I used to use button to submit there. People will hate it

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by shinde-rahul** [comment]
@kuzmany, the modal used the same order. As per your comment https://github.com/mautic/mautic/pull/9895#pullrequestreview-633227732, we should start discussing the UX changes, as these might be helpful to review UI changes.

@RCheesley @mohit-rocks your thoughts.

**Comment by kuzmany** [comment]
Just saying, If after upgrade to M4, I accidentally close modal window hundred times due the change orders of buttons, then something smell bad. Cannot imagine how not technical users go mad after upgrade.

Not talking about create/edit page. In that pages I am okay with it. 
I am talking about modal windows.

**Comment by RCheesley** [comment]
Hey folks!

Thanks for raising your concerns @kuzmany. 

I feel that we should be consistent with the button order across the product. It makes no sense to have apply|update / cancel in one place and cancel / apply|update in another place. This is, in my opinion, more important than which order the buttons are displayed in.

Personally speaking, I always found with Mautic that it was frustrating for the buttons to be the reverse to what I was used to - for example in Joomla cancel is on the right:

![button-order-joomla](https://user-images.githubusercontent.com/2930593/119137729-0c779d80-ba39-11eb-9661-dc891010ad6f.png)

Drupal also has cancel/delete on the right:
![screenshot-www mautic org-2021 05 21-13_33_40](https://user-images.githubusercontent.com/2930593/119137885-33ce6a80-ba39-11eb-8f63-568e4e246e44.png)

![screenshot-mauticon mautic org-2021 05 21-13_29_45](https://user-images.githubusercontent.com/2930593/119137892-34ff9780-ba39-11eb-889d-f2d1cc695a34.png)

Reading around the topic, it seems to be very much based on your own conditioning (what OS you use, what programmes you use) as to whether you expect negative actions on the left or right of positive actions:

- https://uxdesign.cc/buttons-placement-and-order-bb1c4abadfcb
- https://ux.stackexchange.com/questions/1072/ok-cancel-on-left-right

I find this conclusion from the first link quite helpful:

> First of all, decide whether you will place the main button on the right or on the left. If you decide to place it on right, like it is done in MacOS, be prepared for trouble deciding whether to be consistent or absurd.
> If you choose to place the main button on the left, you will not have consistency problems, and your button placement will not break natural human behavior, where “yes” is followed by “no”.
> As for button placement on pages, left and center alignment will work the best in most of the cases when the main button goes first.

As mentioned in the comment linked above, Mautic 4 being a major release is the time to change this if we are going to change it, and make it consistent product-wide. 

I feel that the way we have it set now (affirmative preceding negative) is the best way forward for the product, however also appreciated that there will be some adjusting to do for those of us who are used to how it used to be.

Going forward this is exactly why we need to have a UX tiger team to be able to give insights and feedback on proposals like this - if you know anyone who would be interested do let us know!
