### ISSUE TITLE
Forms are not able to submit

### ISSUE THREAD

**Issue by kuzmany** [mautic/mautic#9951]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Forms are not able to submit in preview or everywhere. 

![image](https://user-images.githubusercontent.com/462477/116558234-81a2f780-a8ff-11eb-83f5-df227b9766d4.png)

| Q   | A
| --- | ---
| Mautic version | 
| PHP version | 
| Browser | 

### Steps to reproduce
1. 
2. 
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by RCheesley** [comment]
This must be a relatively new thing as I have been testing and submitting forms in Mautic 4 - will take a look!

**Comment by RCheesley** [comment]
Yep - confirmed:

```
2:1 Uncaught SyntaxError: Unexpected token } in JSON at position 12
    at JSON.parse (<anonymous>)
    at Object.Core.parseToObject (mautic-form.js?vda52b6f1:47)
    at mautic-form.js?vda52b6f1:48
    at mautic-form.js?vda52b6f1:49
mautic-form.js?vda52b6f1:8 Uncaught TypeError: Cannot read property 'testingform' of undefined
    at Object.Form.prepareValidation (mautic-form.js?vda52b6f1:8)
    at Object.Form.prepareForms (mautic-form.js?vda52b6f1:6)
    at Object.Core.onLoad (mautic-form.js?vda52b6f1:47)
    at HTMLScriptElement.script.onload (2:20)
mautic-form.js?vda52b6f1:17 Uncaught ReferenceError: MauticFormValidations is not defined
    at Object.validateForm (mautic-form.js?vda52b6f1:17)
    at Object.Core.validateForm (mautic-form.js?vda52b6f1:39)
    at HTMLFormElement.theForm.onsubmit (mautic-form.js?vda52b6f1:6)
```

Strange that this has not been picked up by tests failing? Or do we not have any tests that check if a form actually can submit?

**Comment by kuzmany** [comment]
Reason is change to generate path  to js file after upgrade: 

`media/js/mautic-form-src.js?va4d145851`

before it was

`media/js/mautic-form-src.js`

**Comment by RCheesley** [comment]
I think that was one of the PRs that was merged recently - will look!

**Comment by kuzmany** [comment]
I will try fixed it

**Comment by RCheesley** [comment]
OK - I thought that I had seen a PR about versioning the asset files for caching purposes, but I am struggling to find it!

**Comment by RCheesley** [comment]
https://github.com/mautic/mautic/pull/9843/commits/8b4cd18285b69ecd5f0caefed9d9522ba219ba48 here is the relevant commit I think, it was within the PR to add CKEditor.

**Comment by kuzmany** [comment]
Fix https://github.com/mautic/mautic/pull/9972
