### ISSUE TITLE
E-mail. Edited subject is not taken into account at sending time

### ISSUE THREAD

**Issue by jonathandhn** [mautic/mautic#9954]
## Bug Description
Hi, we've done an e-mailing earlier today.  The message was not fired with the right subject. There were one subject input in mautic weeks ago, and it was change a week ago. The e-mail was fired with the old subject.

| Mautic version  3.3.3 | 
| PHP version 7.4.16 | 

### Steps to reproduce

1. Create e-mail
2. Input subject
3. Save
4. Change subject
5. Save
6. Send
 
### Log errors
none

**Comment by npracht** [comment]
Hello @jonathandhn i don't face this issue. Are you sure that the email you received was not an old email blocked in your spool that get suddenly unblocked ?

**Comment by jonathandhn** [comment]
Fortunately yes, because it was fired minutes after someone published it, days after being redacted.

It was redacted in mautic 3.3.2 and send with mautic 3.3.3 to 2800 contacts.

This e-mail used grapesJS with a Mjml template.

I'm not the user of this mautic, only mainter and templates builder so I can't know who used what buttons when because I'm remote from the team, but basically there were a few list set in receivers, a publish date and a stop date set one hour later, and a custom unsubscribe page.

There were a broken image replaced at the same time of the subject, and that new image is part of the mailing sent.

I hope it was a one shoot bug, that will not happens again because we don't know subjects of our e-mail when we start composing, so we always input dummy one in order to work with the editor and save.

Jonathan Dahan
