### ISSUE TITLE
Pipedrive Error Pushing Contacts to Integration

### ISSUE THREAD

**Issue by luizeof** [mautic/mautic#9958]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description

Mautic don´t sync leads with Pipedrive when Pushing Contacts to Integration

| Q   | A
| --- | ---
| Mautic version | 3.3.0
| PHP version | 7.4
| Browser | 

### Steps to reproduce
1. Setup Pipedrive API and Webhooks
2. Send a Lead to Integration (by campaign or form)
3. Run command  ```php bin/console mautic:integration:pipedrive:push -vvv``` 
 
### Log errors

`mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function setEventData() on null" at /var/www/html/plugins/MauticCrmBundle/Integration/Pipedrive/Import/LeadImport.php line 101 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function setEventData() on null at /var/www/html/plugins/MauticCrmBundle/Integration/Pipedrive/Import/LeadImport.php:101)"} []`

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Hi @luizeof !
I don't understand why you use command, if you use campaign or form action it is not necessary.
Are you fields correctly mapped ? Do you send contact with all required fields ?
