### ISSUE TITLE
Feature - Better filtering/lists - Ability to hide inactive elements by default (emails/segments/campaigns) toggle on list page

### ISSUE THREAD

**Issue by TornMarketing** [mautic/mautic#9975]
Feature - Better filtering/lists - Ability to hide inactive elements by default (emails/segments/campaigns) toggle on list page

We live in a world of too much information, and seeing what is relevant is key

We use the inactive and active published functions alot but it would be great to hide these inactive elements from the interface at a toggle of a button by default on each list. 

Handing over systems to other people scares them when they see alot of legacy assets, we lose system buy in when the system looks busy.

Also be able to hide inactive elements from the search results in the campaign builder. After a several years of content in Mautic, it builds up and the only way we search these days is labelling all assets reverse date order so that they are alphanumeric sort and easier to search based on date range rather than name. 

Likewise the ability to remember the default sort order based on last interaction, ie the default is name I believe, but ID is logical so that you see the most recent at the top. I would add to this the ability to sort/filter based on created/modified dates

**Comment by npracht** [comment]
Hello!
The mautic policies requests that all the feature requests and integration requests are discussed on the [mautic slack](https://mautic.slack.com) or on the [mautic forums](https://www.mautic.org/forums/).
Github is better used for issues reporting and code proposition.
Thanks for contributing!

N.
