### ISSUE TITLE
Campaign Builder Tooltip Misspelling

### ISSUE THREAD

**Issue by vexersa** [mautic/mautic#9979]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Use campaign builder and note the below tooltip message.

Word "withing" should be "within"

![image](https://user-images.githubusercontent.com/7994227/117532285-f6082580-afe6-11eb-8a63-842ebd689234.png)

| Q   | A
| --- | ---
| Mautic version | 
v3.3.3
| PHP version | 
| Browser | 

### Steps to reproduce
1. Create a campaign in Campaign Builder
2. Note the error in the tooltip (not sure how to recreate the tooltip, but should be easy to find)
 
### Log errors

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by npracht** [comment]
Fix here: https://github.com/mautic/mautic/pull/10136
