### ISSUE TITLE
Update to newest version of grapesjs

### ISSUE THREAD

**Issue by adiux** [mautic/mautic#9986]
I think we should update to the newest version before we launch it:
https://github.com/artf/grapesjs/releases

**Comment by RCheesley** [comment]
Agreed if this is possible!

**Comment by adiux** [comment]
The newest version as of today is https://github.com/artf/grapesjs/releases/tag/v0.17.4

**Comment by adiux** [comment]
also updated mjml update: https://github.com/artf/grapesjs-mjml/releases
