### ISSUE TITLE
builder.js - Can't find variable: Mautic

### ISSUE THREAD

**Issue by kroll07** [mautic/mautic#9991]
Error in the JS 

console for landing pages

`Can't find variable: Mautic` for `Mautic.initSelectTheme` in builder.js

<img width="961" alt="Screenshot 2021-04-26 at 19 23 08" src="https://user-images.githubusercontent.com/60008103/116125113-66e53e80-a6c5-11eb-8045-53907056724a.png">

**Comment by RCheesley** [comment]
Closing as this is no longer an issue with Mautic 4.
