### ISSUE TITLE
Social icons are getting pulled in from mailjet.com

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#9992]
I happened across this because Mailjet is a blocked domain on our work machines, but it looks like the social icon blocks are pulling in images from mailjet.com:

![screenshot-nimbus-capture-2021 04 25-12_38_10](https://user-images.githubusercontent.com/2930593/115992012-4b920a80-a5c3-11eb-893c-0c4b426ce415.png)
 
I think this is coming from GrapesJS rather than from the themes, so not sure if there is anything that we can do about it!

**Comment by RCheesley** [comment]
@adiux @jos0405 I am not sure if this is related to our implementation, or if it's something to do with GrapesJS itself? Either way it's not ideal, I think.

**Comment by npracht** [comment]
It is coming from mjml lib which is owned by Mailjet.

**Comment by tkima** [comment]
😮Now mailjet is just injecting their images / tracker in every mail send by mautic with the social banner.

As of the GDPR in Europe it can be a thing to reckoned with.

**Comment by RCheesley** [comment]
I'd suggest as a workaround just embedding your own images and linking them up, if it's a big problem for you. Also means you have more control over the appearance!

**Comment by tkima** [comment]
Thank you but this is a Bug report and not a "Workaround question". So the maintainers are aware.
