### ISSUE TITLE
A couple of Mautic specific building blocks such as segment list & save preferences are missing TPROD-208

### ISSUE THREAD

**Issue by nickveenhof** [mautic/mautic#9994]
As the title mentions, A couple of Mautic specific building blocks such as segment list & save preferences are missing.
I am wondering if this is somewhere on the roadmap, a patch that I can help test or if this is still in the "needs help" phase? Pointers are very welcome, so maybe I/my team can help.

The existing mautic builder
![image](https://user-images.githubusercontent.com/161341/112470679-3d09c680-8d6b-11eb-8c60-35d321014143.png)

The new grapesjs builder
![image](https://user-images.githubusercontent.com/161341/112470708-42ffa780-8d6b-11eb-9a7e-13f83dacfd5a.png)

We're currently using the existing builder and this gives us the following HTML code for a preference center https://github.com/mautic/mautic/tree/37ed5ee87900522c888b09ed3857ad0452fb33df/app/bundles/CoreBundle/Views/Slots
See https://github.com/mautic/mautic/blob/37ed5ee87900522c888b09ed3857ad0452fb33df/app/bundles/CoreBundle/Views/Slots/saveprefsbutton.html.php & https://github.com/mautic/mautic/blob/37ed5ee87900522c888b09ed3857ad0452fb33df/app/bundles/CoreBundle/Views/Slots/segmentlist.html.php

Am I missing something as I don't see those slots in grapesjs? I also can't see them in https://github.com/mautic/grapesjs-preset-mautic 

I think, in order to mark this as stable, the slots in core mautic should at least be supported no?

**Comment by RCheesley** [comment]
We have a developer working on this for us through UpWork. The WIP PR can be found here: https://github.com/mautic/grapesjs-preset-mautic/pull/8
