### ISSUE TITLE
Cant do space or delete or backspace for text in buttons

### ISSUE THREAD

**Issue by weismannweb** [mautic/mautic#9997]
Cant do space or delete or backspace for text in buttons

Steps to recreate:

Add button to email/page.

Type text in button and hit space bar then type text.

Observer space is not done.

Same goes for backspace and delete.

https://drive.google.com/file/d/1bnKWwe62puqXzrSQRYJDB2FW1Z4gM4iw/view?usp=sharing

Could it be because of this code:

https://github.com/Webmecanik/plugin-grapesjs-builder/blob/6fd88c362333084dd12732f03f6790113753db84/Assets/js/builder.js#L118-L125

**Comment by RCheesley** [comment]
This is still an issue with the current Features branch as it is currently.

**Comment by ChrisRAoW** [comment]
It's still an issue in the current 4.0.0-rc branch. What I found out is that when you insert the button component into your mail the "Button" label is prepend by a lot of spaces. When you're gonna edit that label those spaces are converted into `&nbsp;`. When I remove those spaces and than edit the Label it all goes well. Not sure I that is really the fix, but maybe it points you in the right direction to solve this.

**Comment by RCheesley** [comment]
@ChrisRAoW thanks for checking in, we know that this is still an issue with the builder and we are hoping that we will be able to address it soon.

**Comment by adiux** [comment]
I started working on it yesterday.

**Comment by ChrisRAoW** [comment]
@adiux Awesome! Good luck! Just let met know when you have something ready to test.

**Comment by RCheesley** [comment]
This is resolved with the work that @adiux and @disha-pishavadia24 have been doing on the builder which will soon be merged. Please check in with the team in #i-builders on Slack if you want instructions on how to test!
